VideoCore Library: interface/vcos/vcos_semaphore.h File Reference
vcos_semaphore.h File Reference
#include "interface/vcos/vcos_types.h"
#include "vcos.h"
Macros
#define VCOS_SEMAPHORE_H
#define VCOS_SEMAPHORE_H
Functions
VCOS_INLINE_DECL VCOS_STATUS_T vcos_semaphore_create (VCOS_SEMAPHORE_T *sem, const char *name, VCOS_UNSIGNED count)
Create a semaphore.
VCOS_INLINE_DECL VCOS_STATUS_T vcos_semaphore_wait (VCOS_SEMAPHORE_T *sem)
Wait on a semaphore.
VCOS_INLINE_DECL VCOS_STATUS_T vcos_semaphore_wait_timeout (VCOS_SEMAPHORE_T *sem, VCOS_UNSIGNED timeout)
Wait on a semaphore with a timeout.
VCOS_INLINE_DECL VCOS_STATUS_T vcos_semaphore_trywait (VCOS_SEMAPHORE_T *sem)
Try to wait for a semaphore.
VCOS_INLINE_DECL VCOS_STATUS_T vcos_semaphore_post (VCOS_SEMAPHORE_T *sem)
Post a semaphore.
VCOS_INLINE_DECL void vcos_semaphore_delete (VCOS_SEMAPHORE_T *sem)
Delete a semaphore, releasing any resources consumed by it.
Detailed Description
Semaphores
This provides counting semaphores. Semaphores are not re-entrant. On sensible operating systems a semaphore can always be posted but can only be taken in thread (not interrupt) context. Under Nucleus, a LISR cannot post a semaphore, although it would not be hard to lift this restriction.
Timeout
On both Nucleus and ThreadX a semaphore can be taken with a timeout. This is not supported by VCOS because it makes the non-timeout code considerably more complicated (and hence slower). In the unlikely event that you need a timeout with a semaphore, and you cannot simply redesign your code to avoid it, use an event flag (vcos_event_flags.h).
Changes from Nucleus:
Semaphores are always "FIFO" - i.e. sleeping threads are woken in FIFO order. That's because:
there's no support for NU_PRIORITY in threadx (though it can be emulated, slowly)
we don't appear to actually consciously use it - for example, Dispmanx uses it, but all threads waiting are the same priority.
Definition in file vcos_semaphore.h.
Macro Definition Documentation
VCOS_SEMAPHORE_H [1/2]
#define VCOS_SEMAPHORE_H
VCOS_SEMAPHORE_H [2/2]
#define VCOS_SEMAPHORE_H
Function Documentation
vcos_semaphore_create()
VCOS_INLINE_DECL VCOS_STATUS_T vcos_semaphore_create (VCOS_SEMAPHORE_T * sem, const char * name, VCOS_UNSIGNED count)
Create a semaphore.
Create a semaphore.
Parameters
sem Pointer to memory to be initialized
name A name for this semaphore. The name may be truncated internally.
count The initial count for the semaphore.
Returns
VCOS_SUCCESS if the semaphore was created.
Referenced by ilclient_init(), main(), mmal_graph_create(), mmal_queue_create(), mmal_wrapper_create(), mmalplay_create(), raspitex_init(), svp_create(), vcos_dummy_thread_create(), and vcos_msgq_pool_create().
vcos_semaphore_delete()
VCOS_INLINE_DECL void vcos_semaphore_delete (VCOS_SEMAPHORE_T * sem)
Delete a semaphore, releasing any resources consumed by it.
Parameters
sem Semaphore to wait on
Referenced by ilclient_cleanup_components(), ilclient_destroy(), mmal_graph_destroy(), mmal_port_free(), mmal_queue_destroy(), mmal_wrapper_destroy(), mmalplay_destroy(), OMX_FreeHandle(), raspitex_destroy(), svp_destroy(), and vcos_msgq_pool_delete().
vcos_semaphore_post()
VCOS_INLINE_DECL VCOS_STATUS_T vcos_semaphore_post (VCOS_SEMAPHORE_T * sem)
Post a semaphore.
Parameters
sem Semaphore to wait on
Referenced by ilclient_disable_port_buffers(), ilclient_get_input_buffer(), ilclient_get_output_buffer(), mmal_queue_put(), mmal_queue_put_back(), mmalomx_commands_actions_signal(), mmalplay_stop(), OMX_FreeHandle(), raspitex_capture(), vcil_out_create_component(), and vcos_msgq_pool_free().
vcos_semaphore_trywait()
VCOS_INLINE_DECL VCOS_STATUS_T vcos_semaphore_trywait (VCOS_SEMAPHORE_T * sem)
Try to wait for a semaphore.
Try to obtain the semaphore. If it is already taken, return VCOS_TIMEOUT.
Parameters
sem Semaphore to wait on
Returns
VCOS_SUCCESS - semaphore was taken. VCOS_EAGAIN - could not take semaphore
Referenced by mmal_queue_get(), and vcos_msgq_pool_alloc().
vcos_semaphore_wait()
VCOS_INLINE_DECL VCOS_STATUS_T vcos_semaphore_wait (VCOS_SEMAPHORE_T * sem)
Wait on a semaphore.
There is no timeout option on a semaphore, as adding this will slow down implementations on some platforms. If you need that kind of behaviour, use an event group.
On most platforms this always returns VCOS_SUCCESS, and so would ideally be a void function, however some platforms allow a wait to be interrupted so it remains non-void.
Parameters
sem Semaphore to wait on
Returns
VCOS_SUCCESS - semaphore was taken. VCOS_EAGAIN - could not take semaphore
Referenced by ilclient_disable_port_buffers(), ilclient_get_input_buffer(), ilclient_get_output_buffer(), mmal_encode_test(), mmal_queue_wait(), mmal_wrapper_buffer_get_empty(), mmal_wrapper_buffer_get_full(), mmalplay_play(), raspitex_capture(), vcil_out_create_component(), vcos_msg_peek(), vcos_msg_wait(), and vcos_msgq_pool_wait().
vcos_semaphore_wait_timeout()
VCOS_INLINE_DECL VCOS_STATUS_T vcos_semaphore_wait_timeout (VCOS_SEMAPHORE_T * sem, VCOS_UNSIGNED timeout)
Wait on a semaphore with a timeout.
Note that this function may not be implemented on all platforms, and may not be efficient on all platforms (see comment in vcos_semaphore_wait)
Try to obtain the semaphore. If it is already taken, return VCOS_EAGAIN.
Parameters
sem Semaphore to wait on
timeout Number of milliseconds to wait before returning if the semaphore can't be acquired.
Returns
VCOS_SUCCESS - semaphore was taken. VCOS_EAGAIN - could not take semaphore (i.e. timeout expired) VCOS_EINVAL - Some other error (most likely bad parameters).
Referenced by mmal_queue_timedwait().