VideoCore Library: containers/asf/asf_writer.c File Reference
asf_writer.c File Reference
#include <stdlib.h>
#include <string.h>
#include "containers/core/containers_private.h"
#include "containers/core/containers_io_helpers.h"
#include "containers/core/containers_utils.h"
#include "containers/core/containers_writer_utils.h"
#include "containers/core/containers_logging.h"
Classes
struct VC_CONTAINER_TRACK_MODULE_T
struct VC_CONTAINER_MODULE_T
Macros
#define CONTAINER_HELPER_LOG_INDENT(a) (a)->priv->module->object_level
#define ASF_TRACKS_MAX 16
#define ASF_OBJECT_HEADER_SIZE (16+8)
Typedefs
typedef struct VC_CONTAINER_TRACK_MODULE_T VC_CONTAINER_TRACK_MODULE_T
typedef struct VC_CONTAINER_MODULE_T VC_CONTAINER_MODULE_T
Enumerations
enum ASF_OBJECT_TYPE_T {
ASF_OBJECT_TYPE_UNKNOWN = 0, ASF_OBJECT_TYPE_HEADER, ASF_OBJECT_TYPE_FILE_PROPS, ASF_OBJECT_TYPE_STREAM_PROPS,
ASF_OBJECT_TYPE_EXT_STREAM_PROPS, ASF_OBJECT_TYPE_DATA, ASF_OBJECT_TYPE_SIMPLE_INDEX, ASF_OBJECT_TYPE_INDEX,
ASF_OBJECT_TYPE_HEADER_EXT, ASF_OBJECT_TYPE_HEADER_EXT_INTERNAL, ASF_OBJECT_TYPE_CODEC_LIST, ASF_OBJECT_TYPE_CONTENT_DESCRIPTION,
ASF_OBJECT_TYPE_EXT_CONTENT_DESCRIPTION, ASF_OBJECT_TYPE_STREAM_BITRATE_PROPS, ASF_OBJECT_TYPE_LANGUAGE_LIST, ASF_OBJECT_TYPE_METADATA,
ASF_OBJECT_TYPE_PADDING
}
Functions
VC_CONTAINER_STATUS_T asf_writer_open (VC_CONTAINER_T *p_ctx)
Macro Definition Documentation
ASF_OBJECT_HEADER_SIZE
#define ASF_OBJECT_HEADER_SIZE (16+8)
Definition at line 45 of file asf_writer.c.
ASF_TRACKS_MAX
#define ASF_TRACKS_MAX 16
Definition at line 44 of file asf_writer.c.
CONTAINER_HELPER_LOG_INDENT
#define CONTAINER_HELPER_LOG_INDENT (a) (a)->priv->module->object_level
Definition at line 37 of file asf_writer.c.
Typedef Documentation
VC_CONTAINER_MODULE_T
typedef struct VC_CONTAINER_MODULE_T VC_CONTAINER_MODULE_T
VC_CONTAINER_TRACK_MODULE_T
typedef struct VC_CONTAINER_TRACK_MODULE_T VC_CONTAINER_TRACK_MODULE_T
Enumeration Type Documentation
ASF_OBJECT_TYPE_T
enum ASF_OBJECT_TYPE_T
Enumerator
ASF_OBJECT_TYPE_UNKNOWN
ASF_OBJECT_TYPE_HEADER
ASF_OBJECT_TYPE_FILE_PROPS
ASF_OBJECT_TYPE_STREAM_PROPS
ASF_OBJECT_TYPE_EXT_STREAM_PROPS
ASF_OBJECT_TYPE_DATA
ASF_OBJECT_TYPE_SIMPLE_INDEX
ASF_OBJECT_TYPE_INDEX
ASF_OBJECT_TYPE_HEADER_EXT
ASF_OBJECT_TYPE_HEADER_EXT_INTERNAL
ASF_OBJECT_TYPE_CODEC_LIST
ASF_OBJECT_TYPE_CONTENT_DESCRIPTION
ASF_OBJECT_TYPE_EXT_CONTENT_DESCRIPTION
ASF_OBJECT_TYPE_STREAM_BITRATE_PROPS
ASF_OBJECT_TYPE_LANGUAGE_LIST
ASF_OBJECT_TYPE_METADATA
ASF_OBJECT_TYPE_PADDING
Definition at line 50 of file asf_writer.c.
              {
    ASF_OBJECT_TYPE_UNKNOWN = 0,
    ASF_OBJECT_TYPE_HEADER,
    ASF_OBJECT_TYPE_FILE_PROPS,
    ASF_OBJECT_TYPE_STREAM_PROPS,
    ASF_OBJECT_TYPE_EXT_STREAM_PROPS,
    ASF_OBJECT_TYPE_DATA,
    ASF_OBJECT_TYPE_SIMPLE_INDEX,
    ASF_OBJECT_TYPE_INDEX,
    ASF_OBJECT_TYPE_HEADER_EXT,
    ASF_OBJECT_TYPE_HEADER_EXT_INTERNAL,
    ASF_OBJECT_TYPE_CODEC_LIST,
    ASF_OBJECT_TYPE_CONTENT_DESCRIPTION,
    ASF_OBJECT_TYPE_EXT_CONTENT_DESCRIPTION,
    ASF_OBJECT_TYPE_STREAM_BITRATE_PROPS,
    ASF_OBJECT_TYPE_LANGUAGE_LIST,
    ASF_OBJECT_TYPE_METADATA,
    ASF_OBJECT_TYPE_PADDING,
 } ASF_OBJECT_TYPE_T;
Function Documentation
asf_writer_open()
VC_CONTAINER_STATUS_T asf_writer_open (VC_CONTAINER_T * p_ctx)
Definition at line 528 of file asf_writer.c.
References error(), extension, VC_CONTAINER_PRIVATE_T::module, VC_CONTAINER_MODULE_T::null, VC_CONTAINER_PRIVATE_T::pf_close, VC_CONTAINER_T::priv, status, VC_CONTAINER_MODULE_T::tracks, VC_CONTAINER_T::tracks, VC_CONTAINER_PRIVATE_T::uri, VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED, VC_CONTAINER_ERROR_OUT_OF_MEMORY, VC_CONTAINER_SUCCESS, vc_container_writer_extraio_create_null(), vc_uri_find_query(), and vc_uri_path_extension().
 {
    VC_CONTAINER_STATUS_T status = VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED;
    const char *extension = vc_uri_path_extension(p_ctx->priv->uri);
    VC_CONTAINER_MODULE_T *module = 0;
    unsigned int i;
    /* Check if the user has specified a container */
    vc_uri_find_query(p_ctx->priv->uri, 0, "container", &extension);
    /* Check we're the right writer for this */
    if(!extension)
       return VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED;
    if(strcasecmp(extension, "asf") && strcasecmp(extension, "wmv") &&
       strcasecmp(extension, "wma"))
       return VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED;
    /* Allocate our context */
    module = malloc(sizeof(*module));
    if(!module) { status = VC_CONTAINER_ERROR_OUT_OF_MEMORY; goto error; }
    memset(module, 0, sizeof(*module));
    p_ctx->priv->module = module;
    p_ctx->tracks = module->tracks;
    /* Create a null i/o writer to help us out in writing our data */
    status = vc_container_writer_extraio_create_null(p_ctx, &module->null);
    if(status != VC_CONTAINER_SUCCESS) goto error;
    /* We'll only write the header once we've got all our tracks */
    p_ctx->priv->pf_close = asf_writer_close;
    p_ctx->priv->pf_write = asf_writer_write;
    p_ctx->priv->pf_control = asf_writer_control;
    return VC_CONTAINER_SUCCESS;
  error:
    LOG_DEBUG(p_ctx, "asf: error opening stream");
    for(i = 0; i < ASF_TRACKS_MAX && p_ctx->tracks && p_ctx->tracks[i]; i++)
       vc_container_free_track(p_ctx, p_ctx->tracks[i]);
    free(module);
    return status;
 }
Variable Documentation
guid
const GUID_T* guid
Definition at line 136 of file asf_writer.c.
pf_func
VC_CONTAINER_STATUS_T(* pf_func) (VC_CONTAINER_T *)
Definition at line 138 of file asf_writer.c.
psz_name
const char* psz_name
Definition at line 137 of file asf_writer.c.
type
const ASF_OBJECT_TYPE_T type
Definition at line 135 of file asf_writer.c.