VideoCore Library: containers/net/net_sockets_common.c File Reference
net_sockets_common.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "containers/containers.h"
#include "containers/core/containers_common.h"
#include "containers/core/containers_logging.h"
#include "net_sockets.h"
#include "net_sockets_priv.h"
Classes
struct vc_container_net_tag
Functions
VC_CONTAINER_NET_T * vc_container_net_open (const char *address, const char *port, vc_container_net_open_flags_t flags, vc_container_net_status_t *p_status)
vc_container_net_status_t vc_container_net_close (VC_CONTAINER_NET_T *p_ctx)
vc_container_net_status_t vc_container_net_status (VC_CONTAINER_NET_T *p_ctx)
size_t vc_container_net_read (VC_CONTAINER_NET_T *p_ctx, void *buffer, size_t size)
size_t vc_container_net_write (VC_CONTAINER_NET_T *p_ctx, const void *buffer, size_t size)
vc_container_net_status_t vc_container_net_listen (VC_CONTAINER_NET_T *p_ctx, uint32_t maximum_connections)
vc_container_net_status_t vc_container_net_accept (VC_CONTAINER_NET_T *p_server_ctx, VC_CONTAINER_NET_T **pp_client_ctx)
bool vc_container_net_is_data_available (VC_CONTAINER_NET_T *p_ctx)
size_t vc_container_net_maximum_datagram_size (VC_CONTAINER_NET_T *p_ctx)
vc_container_net_status_t vc_container_net_get_client_name (VC_CONTAINER_NET_T *p_ctx, char *name, size_t name_len)
vc_container_net_status_t vc_container_net_get_client_port (VC_CONTAINER_NET_T *p_ctx, unsigned short *port)
vc_container_net_status_t vc_container_net_control (VC_CONTAINER_NET_T *p_ctx, vc_container_net_control_t operation, va_list args)
uint32_t vc_container_net_to_host (uint32_t value)
uint32_t vc_container_net_from_host (uint32_t value)
uint16_t vc_container_net_to_host_16 (uint16_t value)
uint16_t vc_container_net_from_host_16 (uint16_t value)
Function Documentation
vc_container_net_accept()
vc_container_net_status_t vc_container_net_accept (VC_CONTAINER_NET_T * p_server_ctx, VC_CONTAINER_NET_T ** pp_client_ctx)
Accept a client connection on a listening stream server socket. Attempting to use this on anything other than a listening stream server socket shall trigger an error. When a client connection is made, the new instance representing it is returned via pp_client_ctx.
Parameters
p_server ctx The server socket instance.
pp_client_ctx The address where the pointer to the new client's socket instance is written.
Returns
The status of the socket.
Definition at line 431 of file net_sockets_common.c.
References error(), INFINITE_TIMEOUT_MS, INVALID_SOCKET, vc_container_net_tag::max_datagram_size, NULL, vc_container_net_tag::read_timeout_ms, vc_container_net_tag::sa, vc_container_net_tag::socket, vc_container_net_tag::status, STREAM_CLIENT, STREAM_SERVER, vc_container_net_tag::to_addr, vc_container_net_tag::to_addr_len, vc_container_net_tag::type, VC_CONTAINER_NET_ERROR_INVALID_PARAMETER, VC_CONTAINER_NET_ERROR_INVALID_SOCKET, VC_CONTAINER_NET_ERROR_NO_MEMORY, VC_CONTAINER_NET_ERROR_NOT_ALLOWED, vc_container_net_private_init(), vc_container_net_private_last_error(), vc_container_net_private_maximum_datagram_size(), and VC_CONTAINER_NET_SUCCESS.
 {
    VC_CONTAINER_NET_T *p_client_ctx = NULL;
    if (!p_server_ctx)
       return VC_CONTAINER_NET_ERROR_INVALID_SOCKET;
    if (!pp_client_ctx)
       return VC_CONTAINER_NET_ERROR_INVALID_PARAMETER;
    *pp_client_ctx = NULL;
    if (p_server_ctx->type != STREAM_SERVER)
    {
       p_server_ctx->status = VC_CONTAINER_NET_ERROR_NOT_ALLOWED;
       goto error;
    }
    p_client_ctx = (VC_CONTAINER_NET_T *)malloc(sizeof(VC_CONTAINER_NET_T));
    if (!p_client_ctx)
    {
       p_server_ctx->status = VC_CONTAINER_NET_ERROR_NO_MEMORY;
       goto error;
    }
    /* Initialise the new context with the address information from the server context */
    memset(p_client_ctx, 0, sizeof(*p_client_ctx));
    memcpy(&p_client_ctx->to_addr, &p_server_ctx->to_addr, p_server_ctx->to_addr_len);
    p_client_ctx->to_addr_len = p_server_ctx->to_addr_len;
    p_client_ctx->socket = accept(p_server_ctx->socket, &p_client_ctx->to_addr.sa, &p_client_ctx->to_addr_len);
    if (p_client_ctx->socket == INVALID_SOCKET)
    {
       p_server_ctx->status = vc_container_net_private_last_error();
       goto error;
    }
    /* Need to bump up the initialisation count, as a new context has been created */
    p_server_ctx->status = vc_container_net_private_init();
    if (p_server_ctx->status != VC_CONTAINER_NET_SUCCESS)
       goto error;
    p_client_ctx->type = STREAM_CLIENT;
    p_client_ctx->max_datagram_size = vc_container_net_private_maximum_datagram_size(p_client_ctx->socket);
    p_client_ctx->read_timeout_ms = INFINITE_TIMEOUT_MS;
    p_client_ctx->status = VC_CONTAINER_NET_SUCCESS;
    *pp_client_ctx = p_client_ctx;
    return VC_CONTAINER_NET_SUCCESS;
 error:
    if (p_client_ctx)
       free(p_client_ctx);
    return p_server_ctx->status;
 }
vc_container_net_close()
vc_container_net_status_t vc_container_net_close (VC_CONTAINER_NET_T * p_ctx)
Closes a network socket instance. The p_ctx pointer must not be used after it has been closed.
Parameters
p_ctx The socket instance to close.
Returns
The status code for closing the socket.
Definition at line 279 of file net_sockets_common.c.
References INVALID_SOCKET, vc_container_net_tag::socket, VC_CONTAINER_NET_ERROR_INVALID_SOCKET, vc_container_net_private_close(), vc_container_net_private_deinit(), and VC_CONTAINER_NET_SUCCESS.
 {
    if (!p_ctx)
       return VC_CONTAINER_NET_ERROR_INVALID_SOCKET;
    if (p_ctx->socket != INVALID_SOCKET)
    {
       vc_container_net_private_close(p_ctx->socket);
       p_ctx->socket = INVALID_SOCKET;
    }
    free(p_ctx);
    vc_container_net_private_deinit();
    return VC_CONTAINER_NET_SUCCESS;
 }
vc_container_net_control()
vc_container_net_status_t vc_container_net_control (VC_CONTAINER_NET_T * p_ctx, vc_container_net_control_t operation, va_list args)
Perform a control operation on the socket. See vc_container_net_control_t for more details.
Parameters
p_ctx The socket instance.
operation The control operation to perform.
args Variable list of additional arguments to the operation.
Returns
The status of the socket.
Definition at line 576 of file net_sockets_common.c.
References vc_container_net_tag::status, and VC_CONTAINER_NET_CONTROL_SET_READ_BUFFER_SIZE.
 {
    vc_container_net_status_t status;
    switch (operation)
    {
    case VC_CONTAINER_NET_CONTROL_SET_READ_BUFFER_SIZE:
       status = socket_set_read_buffer_size(p_ctx, va_arg(args, uint32_t));
       break;
    case VC_CONTAINER_NET_CONTROL_SET_READ_TIMEOUT_MS:
       status = socket_set_read_timeout_ms(p_ctx, va_arg(args, uint32_t));
       break;
    default:
       status = VC_CONTAINER_NET_ERROR_NOT_ALLOWED;
    }
    return status;
 }
vc_container_net_from_host()
uint32_t vc_container_net_from_host (uint32_t value)
Convert a 32-bit unsigned value from host order to network order (big endian).
Parameters
value The value to be converted.
Returns
The converted value.
Definition at line 604 of file net_sockets_common.c.
 {
    return htonl(value);
 }
vc_container_net_from_host_16()
uint16_t vc_container_net_from_host_16 (uint16_t value)
Convert a 16-bit unsigned value from host order to network order (big endian).
Parameters
value The value to be converted.
Returns
The converted value.
Definition at line 616 of file net_sockets_common.c.
 {
    return htons(value);
 }
vc_container_net_get_client_name()
vc_container_net_status_t vc_container_net_get_client_name (VC_CONTAINER_NET_T * p_ctx, char * name, size_t name_len)
Get the DNS name or IP address of a stream server client, if connected. The length of the name will be limited by name_len, taking into account a terminating NUL character. Calling this function on a non-stream server instance, or one that is not connected to a client, will result in an error status.
Parameters
p_ctx The socket instance.
name Pointer where the name should be written.
name_len Maximum number of characters to write to name.
Returns
The status of the socket.
Definition at line 526 of file net_sockets_common.c.
References INVALID_SOCKET, NULL, vc_container_net_tag::sa, vc_container_net_tag::socket, vc_container_net_tag::status, vc_container_net_tag::to_addr, vc_container_net_tag::to_addr_len, VC_CONTAINER_NET_ERROR_INVALID_PARAMETER, VC_CONTAINER_NET_ERROR_INVALID_SOCKET, and VC_CONTAINER_NET_ERROR_NOT_CONNECTED.
 {
    int result;
    if (!p_ctx)
       return VC_CONTAINER_NET_ERROR_INVALID_SOCKET;
    if (p_ctx->socket == INVALID_SOCKET)
       p_ctx->status = VC_CONTAINER_NET_ERROR_NOT_CONNECTED;
    else if (!name || !name_len)
       p_ctx->status = VC_CONTAINER_NET_ERROR_INVALID_PARAMETER;
    else if ((result = getnameinfo(&p_ctx->to_addr.sa, p_ctx->to_addr_len, name, name_len, NULL, 0, 0)) != 0)
       p_ctx->status = translate_getnameinfo_error(result);
    else
       p_ctx->status = VC_CONTAINER_NET_SUCCESS;
    return p_ctx->status;
 }
vc_container_net_get_client_port()
vc_container_net_status_t vc_container_net_get_client_port (VC_CONTAINER_NET_T * p_ctx, unsigned short * port)
Get the port of a stream server client, if connected. The port is written to the address in host order. Calling this function on a non-stream server instance, or one that is not connected to a client, will result in an error status.
Parameters
p_ctx The socket instance.
port Pointer where the port should be written.
Returns
The status of the socket.
Definition at line 546 of file net_sockets_common.c.
References vc_container_net_tag::in, vc_container_net_tag::in6, INVALID_SOCKET, vc_container_net_tag::sa, vc_container_net_tag::socket, vc_container_net_tag::status, vc_container_net_tag::to_addr, VC_CONTAINER_NET_ERROR_GENERAL, VC_CONTAINER_NET_ERROR_INVALID_PARAMETER, VC_CONTAINER_NET_ERROR_INVALID_SOCKET, VC_CONTAINER_NET_ERROR_NOT_CONNECTED, and VC_CONTAINER_NET_SUCCESS.
 {
    if (!p_ctx)
       return VC_CONTAINER_NET_ERROR_INVALID_SOCKET;
    if (p_ctx->socket == INVALID_SOCKET)
       p_ctx->status = VC_CONTAINER_NET_ERROR_NOT_CONNECTED;
    else if (!port)
       p_ctx->status = VC_CONTAINER_NET_ERROR_INVALID_PARAMETER;
    else
    {
       p_ctx->status = VC_CONTAINER_NET_SUCCESS;
       switch (p_ctx->to_addr.sa.sa_family)
       {
       case AF_INET:
          *port = ntohs(p_ctx->to_addr.in.sin_port);
          break;
       case AF_INET6:
          *port = ntohs(p_ctx->to_addr.in6.sin6_port);
          break;
       default:
          /* Highly unexepcted address family! */
          p_ctx->status = VC_CONTAINER_NET_ERROR_GENERAL;
       }
    }
    return p_ctx->status;
 }
vc_container_net_is_data_available()
bool vc_container_net_is_data_available (VC_CONTAINER_NET_T * p_ctx)
Non-blocking check for data being available to read. If an error occurs, the function will return false and the error can be obtained using socket_status().
Parameters
p_ctx The socket instance.
Returns
True if there is data available to read immediately.
Definition at line 489 of file net_sockets_common.c.
References DATAGRAM_SENDER, vc_container_net_tag::status, vc_container_net_tag::type, and VC_CONTAINER_NET_ERROR_NOT_ALLOWED.
 {
    if (!p_ctx)
       return false;
    if (p_ctx->type == DATAGRAM_SENDER)
    {
       p_ctx->status = VC_CONTAINER_NET_ERROR_NOT_ALLOWED;
       return false;
    }
    return socket_wait_for_data(p_ctx, 0);
 }
vc_container_net_listen()
vc_container_net_status_t vc_container_net_listen (VC_CONTAINER_NET_T * p_ctx, uint32_t maximum_connections)
Start a stream server socket listening for connections from clients. Attempting to use this on anything other than a stream server socket shall trigger an error.
Parameters
p_ctx The socket instance.
maximum_connections The maximum number of queued connections to allow.
Returns
The status of the socket.
Definition at line 412 of file net_sockets_common.c.
References vc_container_net_tag::socket, SOCKET_ERROR, vc_container_net_tag::status, STREAM_SERVER, vc_container_net_tag::type, VC_CONTAINER_NET_ERROR_INVALID_SOCKET, VC_CONTAINER_NET_ERROR_NOT_ALLOWED, vc_container_net_private_last_error(), and VC_CONTAINER_NET_SUCCESS.
 {
    if (!p_ctx)
       return VC_CONTAINER_NET_ERROR_INVALID_SOCKET;
    p_ctx->status = VC_CONTAINER_NET_SUCCESS;
    if (p_ctx->type == STREAM_SERVER)
    {
       if (listen(p_ctx->socket, maximum_connections) == SOCKET_ERROR)
          p_ctx->status = vc_container_net_private_last_error();
    } else {
       p_ctx->status = VC_CONTAINER_NET_ERROR_NOT_ALLOWED;
    }
    return p_ctx->status;
 }
vc_container_net_maximum_datagram_size()
size_t vc_container_net_maximum_datagram_size (VC_CONTAINER_NET_T * p_ctx)
Returns the maximum size of a datagram in bytes, for sending or receiving. The limit for reading from or writing to stream sockets will generally be greater than this value, although the call can also be made on such sockets.
Parameters
p_ctx The socket instance.
Returns
The maximum size of a datagram in bytes.
Definition at line 504 of file net_sockets_common.c.
References vc_container_net_tag::max_datagram_size.
 {
    return p_ctx ? p_ctx->max_datagram_size : 0;
 }
vc_container_net_open()
VC_CONTAINER_NET_T* vc_container_net_open (const char * address, const char * port, vc_container_net_open_flags_t flags, vc_container_net_status_t * p_status)
Opens a network socket instance. The network address can be a host name, dotted IP4, hex IP6 address or NULL. Passing NULL signifies the socket is either to be used as a datagram receiver or a stream server, depending on the flags. VC_CONTAINER_NET_OPEN_FLAG_STREAM will open the socket for connected streaming. The default is to use connectionless datagrams. VC_CONTAINER_NET_OPEN_FLAG_FORCE_IP4 will force the use of IPv4 addressing or fail to open the socket. The default is to pick the first available. VC_CONTAINER_NET_OPEN_FLAG_FORCE_IP6 will force the use of IPv6 addressing or fail to open the socket. The default is to pick the first available. VC_CONTAINER_NET_OPEN_FLAG_IP4_BROADCAST will use IPv4 broadcast addressing for a datagram sender. Use with an IPv6 address, stream socket or datagram receiver will raise an error. If the p_status parameter is not NULL, the status code will be written to it to indicate the reason for failure, or VC_CONTAINER_NET_SUCCESS on success. Sockets shall be bound and connected as necessary. Stream server sockets shall further need to have vc_container_net_listen and vc_container_net_accept called on them before data can be transferred.
Parameters
address Network address or NULL.
port Network port or well-known name. This is the local port for receivers/servers.
flags Flags controlling socket type.
p_status Optional pointer to variable to receive status of operation.
Returns
The socket instance or NULL on error.
Definition at line 135 of file net_sockets_common.c.
References DATAGRAM_RECEIVER, DATAGRAM_SENDER, error(), INVALID_SOCKET, LOG_ERROR, NULL, vc_container_net_tag::socket, SOCKET_ERROR, vc_container_net_tag::status, STREAM_CLIENT, STREAM_SERVER, vc_container_net_tag::type, VC_CONTAINER_NET_ERROR_INVALID_PARAMETER, VC_CONTAINER_NET_ERROR_NO_MEMORY, VC_CONTAINER_NET_OPEN_FLAG_FORCE_IP4, VC_CONTAINER_NET_OPEN_FLAG_FORCE_IP6, VC_CONTAINER_NET_OPEN_FLAG_FORCE_MASK, VC_CONTAINER_NET_OPEN_FLAG_STREAM, vc_container_net_private_deinit(), vc_container_net_private_init(), vc_container_net_private_last_error(), vc_container_net_private_set_reusable(), and VC_CONTAINER_NET_SUCCESS.
 {
    VC_CONTAINER_NET_T *p_ctx;
    struct addrinfo hints, *info, *p;
    int result;
    vc_container_net_status_t status;
    SOCKET_T sock = INVALID_SOCKET;
    status = vc_container_net_private_init();
    if (status != VC_CONTAINER_NET_SUCCESS)
    {
       LOG_ERROR(NULL, "vc_container_net_open: platform initialization failure: %d", status);
       if (p_status)
          *p_status = status;
       return NULL;
    }
    p_ctx = (VC_CONTAINER_NET_T *)malloc(sizeof(VC_CONTAINER_NET_T));
    if (!p_ctx)
    {
       if (p_status)
          *p_status = VC_CONTAINER_NET_ERROR_NO_MEMORY;
       LOG_ERROR(NULL, "vc_container_net_open: malloc fail for VC_CONTAINER_NET_T");
       vc_container_net_private_deinit();
       return NULL;
    }
    /* Initialize the net socket instance structure */
    memset(p_ctx, 0, sizeof(*p_ctx));
    p_ctx->socket = INVALID_SOCKET;
    if (flags & VC_CONTAINER_NET_OPEN_FLAG_STREAM)
       p_ctx->type = address ? STREAM_CLIENT : STREAM_SERVER;
    else
       p_ctx->type = address ? DATAGRAM_SENDER : DATAGRAM_RECEIVER;
    /* Create the address info linked list from the data provided */
    memset(&hints, 0, sizeof(hints));
    switch (flags & VC_CONTAINER_NET_OPEN_FLAG_FORCE_MASK)
    {
    case 0:
       hints.ai_family = AF_UNSPEC;
       break;
    case VC_CONTAINER_NET_OPEN_FLAG_FORCE_IP4:
       hints.ai_family = AF_INET;
       break;
    case VC_CONTAINER_NET_OPEN_FLAG_FORCE_IP6:
       hints.ai_family = AF_INET6;
       break;
    default:
       status = VC_CONTAINER_NET_ERROR_INVALID_PARAMETER;
       LOG_ERROR(NULL, "vc_container_net_open: invalid address forcing flag");
       goto error;
    }
    hints.ai_socktype = (flags & VC_CONTAINER_NET_OPEN_FLAG_STREAM) ? SOCK_STREAM : SOCK_DGRAM;
    result = getaddrinfo(address, port, &hints, &info);
    if (result)
    {
       status = vc_container_net_private_last_error();
       LOG_ERROR(NULL, "vc_container_net_open: unable to get address info: %d", status);
       goto error;
    }
    /* Not all address infos may be useable. Search for one that is by skipping any
     * that provoke errors. */
    for(p = info; (p != NULL) && (sock == INVALID_SOCKET) ; p = p->ai_next)
    {
       sock = socket(p->ai_family, p->ai_socktype, p->ai_protocol);
       if (sock == INVALID_SOCKET)
       {
          status = vc_container_net_private_last_error();
          continue;
       }
       switch (p_ctx->type)
       {
       case STREAM_CLIENT:
             /* Simply connect to the given address/port */
             if (connect(sock, p->ai_addr, p->ai_addrlen) == SOCKET_ERROR)
                status = vc_container_net_private_last_error();
             break;
       case DATAGRAM_SENDER:
             /* Nothing further to do */
             break;
       case STREAM_SERVER:
             /* Try to avoid socket reuse timing issues on TCP server sockets */
             vc_container_net_private_set_reusable(sock, true);
             /* Allow any source address */
             socket_clear_address(p->ai_addr);
             if (bind(sock, p->ai_addr, p->ai_addrlen) == SOCKET_ERROR)
                status = vc_container_net_private_last_error();
             break;
       case DATAGRAM_RECEIVER:
             /* Allow any source address */
             socket_clear_address(p->ai_addr);
             if (bind(sock, p->ai_addr, p->ai_addrlen) == SOCKET_ERROR)
                status = vc_container_net_private_last_error();
             break;
       }
       if (status == VC_CONTAINER_NET_SUCCESS)
       {
          /* Save addressing information for later use */
          p_ctx->to_addr_len = p->ai_addrlen;
          memcpy(&p_ctx->to_addr, p->ai_addr, p->ai_addrlen);
       } else {
          vc_container_net_private_close(sock);   /* Try next entry in list */
          sock = INVALID_SOCKET;
       }
    }
    freeaddrinfo(info);
    if (sock == INVALID_SOCKET)
    {
       LOG_ERROR(NULL, "vc_container_net_open: failed to open socket: %d", status);
       goto error;
    }
    p_ctx->socket = sock;
    p_ctx->max_datagram_size = vc_container_net_private_maximum_datagram_size(sock);
    p_ctx->read_timeout_ms = INFINITE_TIMEOUT_MS;
    if (p_status)
       *p_status = VC_CONTAINER_NET_SUCCESS;
    return p_ctx;
 error:
    if (p_status)
       *p_status = status;
    (void)vc_container_net_close(p_ctx);
    return NULL;
 }
vc_container_net_read()
size_t vc_container_net_read (VC_CONTAINER_NET_T * p_ctx, void * buffer, size_t size)
Read data from the socket. The function will read up to the requested number of bytes into the buffer. If there is no data immediately available to read, the function will block until data arrives, an error occurs or the timeout is reached (if set). When the function returns zero, the socket may have been closed, an error may have occurred, a zero length datagram received, or the timeout reached. Check vc_container_net_status() to differentiate. Attempting to read on a datagram sender socket will trigger an error.
Parameters
p_ctx The socket instance.
buffer The buffer into which bytes will be read.
size The maximum number of bytes to read.
Returns
The number of bytes actually read.
Definition at line 305 of file net_sockets_common.c.
References vc_container_net_tag::status, STREAM_CLIENT, STREAM_SERVER, vc_container_net_tag::type, VC_CONTAINER_NET_ERROR_INVALID_PARAMETER, and VC_CONTAINER_NET_SUCCESS.
 {
    int result = 0;
    if (!p_ctx)
       return 0;
    if (!buffer)
    {
       p_ctx->status = VC_CONTAINER_NET_ERROR_INVALID_PARAMETER;
       return 0;
    }
    p_ctx->status = VC_CONTAINER_NET_SUCCESS;
    switch (p_ctx->type)
    {
    case STREAM_CLIENT:
    case STREAM_SERVER:
       /* Receive data from the stream */
       if (socket_wait_for_data(p_ctx, p_ctx->read_timeout_ms))
       {
          result = recv(p_ctx->socket, buffer, (int)size, 0);
          if (!result)
             p_ctx->status = VC_CONTAINER_NET_ERROR_CONNECTION_LOST;
       } else
          p_ctx->status = VC_CONTAINER_NET_ERROR_TIMED_OUT;
       break;
    case DATAGRAM_RECEIVER:
       {
          /* Receive the packet */
          /* FIXME Potential for data loss, as rest of packet will be lost if buffer was not large enough */
          if (socket_wait_for_data(p_ctx, p_ctx->read_timeout_ms))
          {
             result = recvfrom(p_ctx->socket, buffer, size, 0, &p_ctx->to_addr.sa, &p_ctx->to_addr_len);
             if (!result)
                p_ctx->status = VC_CONTAINER_NET_ERROR_CONNECTION_LOST;
          } else
             p_ctx->status = VC_CONTAINER_NET_ERROR_TIMED_OUT;
       }
       break;
    default: /* DATAGRAM_SENDER */
       p_ctx->status = VC_CONTAINER_NET_ERROR_NOT_ALLOWED;
       result = 0;
       break;
    }
    if (result == SOCKET_ERROR)
    {
       p_ctx->status = vc_container_net_private_last_error();
       result = 0;
    }
    return (size_t)result;
 }
vc_container_net_status()
vc_container_net_status_t vc_container_net_status (VC_CONTAINER_NET_T * p_ctx)
Query the latest status of the socket.
Parameters
p_ctx The socket instance.
Returns
The status of the socket.
Definition at line 297 of file net_sockets_common.c.
References vc_container_net_tag::status, and VC_CONTAINER_NET_ERROR_INVALID_SOCKET.
 {
    if (!p_ctx)
       return VC_CONTAINER_NET_ERROR_INVALID_SOCKET;
    return p_ctx->status;
 }
vc_container_net_to_host()
uint32_t vc_container_net_to_host (uint32_t value)
Convert a 32-bit unsigned value from network order (big endian) to host order.
Parameters
value The value to be converted.
Returns
The converted value.
Definition at line 598 of file net_sockets_common.c.
 {
    return ntohl(value);
 }
vc_container_net_to_host_16()
uint16_t vc_container_net_to_host_16 (uint16_t value)
Convert a 16-bit unsigned value from network order (big endian) to host order.
Parameters
value The value to be converted.
Returns
The converted value.
Definition at line 610 of file net_sockets_common.c.
 {
    return ntohs(value);
 }
vc_container_net_write()
size_t vc_container_net_write (VC_CONTAINER_NET_T * p_ctx, const void * buffer, size_t size)
Write data to the socket. If the socket cannot send the requested number of bytes in one go, the function will return a value smaller than size. Attempting to write on a datagram receiver socket will trigger an error.
Parameters
p_ctx The socket instance.
buffer The buffer from which bytes will be written.
size The maximum number of bytes to write.
Returns
The number of bytes actually written.
Definition at line 364 of file net_sockets_common.c.
References DATAGRAM_SENDER, vc_container_net_tag::max_datagram_size, vc_container_net_tag::sa, send, vc_container_net_tag::socket, SOCKET_ERROR, vc_container_net_tag::status, STREAM_CLIENT, STREAM_SERVER, vc_container_net_tag::to_addr, vc_container_net_tag::to_addr_len, vc_container_net_tag::type, VC_CONTAINER_NET_ERROR_INVALID_PARAMETER, VC_CONTAINER_NET_ERROR_NOT_ALLOWED, vc_container_net_private_last_error(), and VC_CONTAINER_NET_SUCCESS.
 {
    int result;
    if (!p_ctx)
       return 0;
    if (!buffer)
    {
       p_ctx->status = VC_CONTAINER_NET_ERROR_INVALID_PARAMETER;
       return 0;
    }
    p_ctx->status = VC_CONTAINER_NET_SUCCESS;
    switch (p_ctx->type)
    {
    case STREAM_CLIENT:
    case STREAM_SERVER:
       /* Send data to the stream */
       result = send(p_ctx->socket, buffer, (int)size, 0);
       break;
    case DATAGRAM_SENDER:
       /* Send the datagram */
       if (size > p_ctx->max_datagram_size)
          size = p_ctx->max_datagram_size;
       result = sendto(p_ctx->socket, buffer, size, 0, &p_ctx->to_addr.sa, p_ctx->to_addr_len);
       break;
    default: /* DATAGRAM_RECEIVER */
       p_ctx->status = VC_CONTAINER_NET_ERROR_NOT_ALLOWED;
       result = 0;
       break;
    }
    if (result == SOCKET_ERROR)
    {
       p_ctx->status = vc_container_net_private_last_error();
       result = 0;
    }
    return (size_t)result;
 }