VideoCore Library: interface/khronos/egl/egl_client_config.c File Reference
egl_client_config.c File Reference
#include "interface/khronos/common/khrn_int_common.h"
#include "interface/khronos/common/khrn_client_platform.h"
#include "interface/khronos/include/EGL/eglext.h"
#include "interface/khronos/egl/egl_client_config.h"
#include "interface/khronos/egl/egl_client_config_cr.c"
Classes
struct FEATURES_AND_FORMATS_T
Macros
#define FEATURES_PACK(r, g, b, a, d, s, m, mask, lockable) ((FEATURES_T)((((uint32_t)(r)) << 28 | (g) << 24 | (b) << 20 | (a) << 16 | (d) << 8 | (s) << 4 | (m) << 3 | ((mask) >> 3) << 2) | (lockable) << 1))
Typedefs
typedef uint32_t FEATURES_T
Functions
void egl_config_install_configs (int type)
KHRN_IMAGE_FORMAT_T egl_config_get_color_format (int id)
KHRN_IMAGE_FORMAT_T egl_config_get_depth_format (int id)
KHRN_IMAGE_FORMAT_T egl_config_get_mask_format (int id)
KHRN_IMAGE_FORMAT_T egl_config_get_multisample_format (int id)
bool egl_config_get_multisample (int id)
bool egl_config_bindable (int id, EGLenum format)
bool egl_config_match_pixmap_info (int id, KHRN_IMAGE_WRAP_T *image)
uint32_t egl_config_get_api_support (int id)
uint32_t egl_config_get_api_conformance (int id)
bool egl_config_bpps_match (int id0, int id1)
Macro Definition Documentation
FEATURES_PACK
#define FEATURES_PACK (r, g, b, a, d, s, m, mask, lockable) ((FEATURES_T)((((uint32_t)(r)) << 28 | (g) << 24 | (b) << 20 | (a) << 16 | (d) << 8 | (s) << 4 | (m) << 3 | ((mask) >> 3) << 2) | (lockable) << 1))
Definition at line 38 of file egl_client_config.c.
Typedef Documentation
FEATURES_T
typedef uint32_t FEATURES_T
Definition at line 36 of file egl_client_config.c.
Function Documentation
egl_config_bindable()
bool egl_config_bindable (int id, EGLenum format)
Definition at line 231 of file egl_client_config.c.
References EGL_MAX_CONFIGS, EGL_NO_TEXTURE, EGL_TEXTURE_RGB, and vcos_assert.
 {
    vcos_assert(id >= 0 && id < EGL_MAX_CONFIGS);
    switch (format) {
    case EGL_NO_TEXTURE:
       return true;
    case EGL_TEXTURE_RGB:
       return bindable_rgb(formats[id].features);
    case EGL_TEXTURE_RGBA:
       return bindable_rgba(formats[id].features);
    default:
       UNREACHABLE();
       return false;
    }
 }
egl_config_bpps_match()
bool egl_config_bpps_match (int id0, int id1)
Definition at line 343 of file egl_client_config.c.
References egl_config_get_color_format(), EGL_MAX_CONFIGS, FEATURES_AND_FORMATS_T::features, FEATURES_UNPACK_ALPHA, FEATURES_UNPACK_BLUE, FEATURES_UNPACK_DEPTH, FEATURES_UNPACK_GREEN, FEATURES_UNPACK_LOCKABLE, FEATURES_UNPACK_MASK, FEATURES_UNPACK_RED, FEATURES_UNPACK_STENCIL, and vcos_assert.
 {
    FEATURES_T config0 = formats[id0].features;
    FEATURES_T config1 = formats[id1].features;
    return
       FEATURES_UNPACK_RED(config0)     == FEATURES_UNPACK_RED(config1) &&
       FEATURES_UNPACK_GREEN(config0)   == FEATURES_UNPACK_GREEN(config1) &&
       FEATURES_UNPACK_BLUE(config0)    == FEATURES_UNPACK_BLUE(config1) &&
       FEATURES_UNPACK_ALPHA(config0)   == FEATURES_UNPACK_ALPHA(config1) &&
       FEATURES_UNPACK_DEPTH(config0)   == FEATURES_UNPACK_DEPTH(config1) &&
       FEATURES_UNPACK_STENCIL(config0) == FEATURES_UNPACK_STENCIL(config1) &&
       FEATURES_UNPACK_MASK(config0)    == FEATURES_UNPACK_MASK(config1);
 }
egl_config_get_api_conformance()
uint32_t egl_config_get_api_conformance (int id)
Definition at line 337 of file egl_client_config.c.
References egl_config_get_api_support(), EGL_OPENVG_BIT, and FEATURES_UNPACK_MULTI.
 {
    /* vg doesn't support multisampled surfaces properly */
    return egl_config_get_api_support(id) & ~(FEATURES_UNPACK_MULTI(formats[id].features) ? EGL_OPENVG_BIT : 0);
 }
egl_config_get_api_support()
uint32_t egl_config_get_api_support (int id)
Definition at line 291 of file egl_client_config.c.
References ABGR_8888_LT, ABGR_8888_RSO, ABGR_8888_TF, ARGB_8888_LT, ARGB_8888_RSO, ARGB_8888_TF, egl_config_get_color_format(), EGL_OPENGL_ES2_BIT, EGL_OPENGL_ES_BIT, EGL_OPENVG_BIT, RGB_565_LT, RGB_565_RSO, RGB_565_TF, XBGR_8888_LT, XBGR_8888_RSO, XBGR_8888_TF, XRGB_8888_LT, XRGB_8888_RSO, and XRGB_8888_TF.
Referenced by egl_config_filter(), and egl_config_get_api_conformance().
 {
    /* no configs are api-specific (ie if you can use a config with gl, you can
     * use it with vg too, and vice-versa). however, some configs have color
     * buffer formats that are incompatible with the hardware, and so can't be
     * used with any api. such configs may still be useful eg with the surface
     * locking extension... */
 #if EGL_KHR_lock_surface
    /* to reduce confusion, just say no for all lockable configs. this #if can be
     * safely commented out -- the color buffer format check below will catch
     * lockable configs we actually can't use */
    if (egl_config_is_lockable(id)) {
       return 0;
    }
 #endif
    switch (egl_config_get_color_format(id)) {
    case ABGR_8888_RSO: case ABGR_8888_TF: case ABGR_8888_LT:
    case XBGR_8888_RSO: case XBGR_8888_TF: case XBGR_8888_LT:
    case ARGB_8888_RSO: case ARGB_8888_TF: case ARGB_8888_LT:
    case XRGB_8888_RSO: case XRGB_8888_TF: case XRGB_8888_LT:
    case RGB_565_RSO: case RGB_565_TF: case RGB_565_LT:
 #ifndef NO_OPENVG
       return (uint32_t)(EGL_OPENGL_ES_BIT | EGL_OPENVG_BIT | EGL_OPENGL_ES2_BIT);
 #else
       return (uint32_t)(EGL_OPENGL_ES_BIT | EGL_OPENGL_ES2_BIT);
 #endif
    default:
       break;
    }
    return 0;
 }
egl_config_get_color_format()
KHRN_IMAGE_FORMAT_T egl_config_get_color_format (int id)
Definition at line 125 of file egl_client_config.c.
References FEATURES_AND_FORMATS_T::color, EGL_MAX_CONFIGS, and vcos_assert.
Referenced by egl_config_bpps_match(), and egl_config_get_api_support().
 {
    vcos_assert(id >= 0 && id < EGL_MAX_CONFIGS);
    return formats[id].color;
 }
egl_config_get_depth_format()
KHRN_IMAGE_FORMAT_T egl_config_get_depth_format (int id)
Definition at line 144 of file egl_client_config.c.
References FEATURES_AND_FORMATS_T::depth, EGL_MAX_CONFIGS, and vcos_assert.
 {
    vcos_assert(id >= 0 && id < EGL_MAX_CONFIGS);
    return formats[id].depth;
 }
egl_config_get_mask_format()
KHRN_IMAGE_FORMAT_T egl_config_get_mask_format (int id)
Definition at line 163 of file egl_client_config.c.
References EGL_MAX_CONFIGS, FEATURES_AND_FORMATS_T::mask, and vcos_assert.
 {
    vcos_assert(id >= 0 && id < EGL_MAX_CONFIGS);
    return formats[id].mask;
 }
egl_config_get_multisample()
bool egl_config_get_multisample (int id)
Definition at line 201 of file egl_client_config.c.
References EGL_MAX_CONFIGS, FEATURES_UNPACK_MULTI, and vcos_assert.
 {
    vcos_assert(id >= 0 && id < EGL_MAX_CONFIGS);
    return FEATURES_UNPACK_MULTI(formats[id].features);
 }
egl_config_get_multisample_format()
KHRN_IMAGE_FORMAT_T egl_config_get_multisample_format (int id)
Definition at line 182 of file egl_client_config.c.
References EGL_MAX_CONFIGS, FEATURES_AND_FORMATS_T::multisample, and vcos_assert.
 {
    vcos_assert(id >= 0 && id < EGL_MAX_CONFIGS);
    return formats[id].multisample;
 }
egl_config_install_configs()
void egl_config_install_configs (int type)
Definition at line 94 of file egl_client_config.c.
References ARR_COUNT, and FEATURES_AND_FORMATS_T::color.
Referenced by client_process_state_init().
 {
    uint32_t i;
    for (i = 0; i != ARR_COUNT(formats); ++i) {
       formats[i].color = (type == 0) ?
          khrn_image_to_rso_format(formats[i].color) :
          khrn_image_to_tf_format(formats[i].color);
    }
 }
egl_config_match_pixmap_info()
bool egl_config_match_pixmap_info (int id, KHRN_IMAGE_WRAP_T * image)
Definition at line 265 of file egl_client_config.c.
References EGL_MAX_CONFIGS, FEATURES_AND_FORMATS_T::features, FEATURES_UNPACK_ALPHA, FEATURES_UNPACK_BLUE, FEATURES_UNPACK_GREEN, FEATURES_UNPACK_RED, KHRN_IMAGE_WRAP_T::format, khrn_image_get_alpha_size(), khrn_image_get_blue_size(), khrn_image_get_green_size(), khrn_image_get_red_size(), and vcos_assert.
Referenced by egl_config_filter().
 {
    FEATURES_T features = formats[id].features;
    KHRN_IMAGE_FORMAT_T format = image->format;
    vcos_assert(id >= 0 && id < EGL_MAX_CONFIGS);
    return
       khrn_image_get_red_size(format)   == FEATURES_UNPACK_RED(features) &&
       khrn_image_get_green_size(format) == FEATURES_UNPACK_GREEN(features) &&
       khrn_image_get_blue_size(format)  == FEATURES_UNPACK_BLUE(features) &&
       khrn_image_get_alpha_size(format) == FEATURES_UNPACK_ALPHA(features);
 }