VideoCore Library: Container I/O API
Container I/O API
Classes
struct VC_CONTAINER_IO_T
Enumerations
enum VC_CONTAINER_IO_MODE_T { VC_CONTAINER_IO_MODE_READ = 0, VC_CONTAINER_IO_MODE_WRITE = 1 }
Functions
VC_CONTAINER_IO_T * vc_container_io_open (const char *uri, VC_CONTAINER_IO_MODE_T mode, VC_CONTAINER_STATUS_T *status)
VC_CONTAINER_IO_T * vc_container_io_create (const char *uri, VC_CONTAINER_IO_MODE_T mode, VC_CONTAINER_IO_CAPABILITIES_T capabilities, VC_CONTAINER_STATUS_T *p_status)
VC_CONTAINER_STATUS_T vc_container_io_close (VC_CONTAINER_IO_T *context)
size_t vc_container_io_peek (VC_CONTAINER_IO_T *context, void *buffer, size_t size)
size_t vc_container_io_read (VC_CONTAINER_IO_T *context, void *buffer, size_t size)
size_t vc_container_io_skip (VC_CONTAINER_IO_T *context, size_t size)
size_t vc_container_io_write (VC_CONTAINER_IO_T *context, const void *buffer, size_t size)
VC_CONTAINER_STATUS_T vc_container_io_seek (VC_CONTAINER_IO_T *context, int64_t offset)
VC_CONTAINER_STATUS_T vc_container_io_control_list (VC_CONTAINER_IO_T *context, VC_CONTAINER_CONTROL_T operation, va_list args)
VC_CONTAINER_STATUS_T vc_container_io_control (VC_CONTAINER_IO_T *context, VC_CONTAINER_CONTROL_T operation,...)
size_t vc_container_io_cache (VC_CONTAINER_IO_T *context, size_t size)
Container I/O Capabilities
The following flags are exported by container i/o modules to describe their capabilities
typedef uint32_t VC_CONTAINER_IO_CAPABILITIES_T
#define VC_CONTAINER_IO_CAPS_CANT_SEEK 0x1
#define VC_CONTAINER_IO_CAPS_SEEK_SLOW 0x2
#define VC_CONTAINER_IO_CAPS_NO_CACHING 0x4
Detailed Description
Macro Definition Documentation
VC_CONTAINER_IO_CAPS_CANT_SEEK
#define VC_CONTAINER_IO_CAPS_CANT_SEEK 0x1
Seeking is not supported
Definition at line 56 of file containers_io.h.
Referenced by vc_container_io_cache(), and vc_container_io_peek().
VC_CONTAINER_IO_CAPS_NO_CACHING
#define VC_CONTAINER_IO_CAPS_NO_CACHING 0x4
The I/O doesn't provide any caching of the data
Definition at line 60 of file containers_io.h.
VC_CONTAINER_IO_CAPS_SEEK_SLOW
#define VC_CONTAINER_IO_CAPS_SEEK_SLOW 0x2
Seeking is slow and should be avoided
Definition at line 58 of file containers_io.h.
Referenced by vc_container_io_cache().
Typedef Documentation
VC_CONTAINER_IO_CAPABILITIES_T
typedef uint32_t VC_CONTAINER_IO_CAPABILITIES_T
Type definition for container I/O capabilities
Definition at line 54 of file containers_io.h.
Enumeration Type Documentation
VC_CONTAINER_IO_MODE_T
enum VC_CONTAINER_IO_MODE_T
Container io opening mode. This is used to specify whether a reader or writer is requested.
Enumerator
VC_CONTAINER_IO_MODE_READ
Container io opened in reading mode
VC_CONTAINER_IO_MODE_WRITE
Container io opened in writing mode
Definition at line 45 of file containers_io.h.
              {
    VC_CONTAINER_IO_MODE_READ = 0,
    VC_CONTAINER_IO_MODE_WRITE = 1
 } VC_CONTAINER_IO_MODE_T;
Function Documentation
vc_container_io_cache()
size_t vc_container_io_cache (VC_CONTAINER_IO_T * context, size_t size)
Cache the pointed region of the i/o stream (from current position). This will allow future seeking into the specified region even on non-seekable streams.
Parameters
context Pointer to the VC_CONTAINER_IO_T instance to use
size Size of the region to cache
Returns
Status of the operation
Definition at line 446 of file containers_io.c.
References VC_CONTAINER_IO_PRIVATE_T::actual_offset, VC_CONTAINER_IO_PRIVATE_CACHE_T::buffer, VC_CONTAINER_IO_PRIVATE_CACHE_T::buffer_end, VC_CONTAINER_IO_PRIVATE_T::cache, VC_CONTAINER_IO_T::capabilities, VC_CONTAINER_IO_PRIVATE_CACHE_T::end, VC_CONTAINER_IO_PRIVATE_CACHE_T::io, MAX_NUM_CACHED_AREAS, VC_CONTAINER_IO_PRIVATE_CACHE_T::mem, MEM_CACHE_AREA_READ_MAX_SIZE, MEM_CACHE_READ_MAX_SIZE, VC_CONTAINER_IO_PRIVATE_CACHE_T::mem_max_size, VC_CONTAINER_IO_PRIVATE_CACHE_T::mem_size, VC_CONTAINER_IO_PRIVATE_CACHE_T::offset, VC_CONTAINER_IO_T::offset, VC_CONTAINER_IO_PRIVATE_CACHE_T::position, VC_CONTAINER_IO_T::priv, VC_CONTAINER_IO_PRIVATE_CACHE_T::size, VC_CONTAINER_IO_PRIVATE_CACHE_T::start, status, VC_CONTAINER_IO_CAPS_CANT_SEEK, VC_CONTAINER_IO_CAPS_SEEK_SLOW, vc_container_io_seek(), and VC_CONTAINER_SUCCESS.
 {
    VC_CONTAINER_IO_PRIVATE_T *private = p_ctx->priv;
    VC_CONTAINER_IO_PRIVATE_CACHE_T *cache, *main_cache;
    VC_CONTAINER_STATUS_T status;
    /* Sanity checking */
    if(private->cached_areas_num >= MAX_NUM_CACHED_AREAS) return 0;
    cache = &private->cached_areas[private->cached_areas_num];
    cache->start = p_ctx->offset;
    cache->end = cache->start + size;
    cache->offset = p_ctx->offset;
    cache->position = 0;
    cache->size = 0;
    cache->io = p_ctx;
    /* Set the size of the cache area depending on the capabilities of the i/o */
    if(p_ctx->capabilities & VC_CONTAINER_IO_CAPS_CANT_SEEK)
       cache->mem_max_size = MEM_CACHE_AREA_READ_MAX_SIZE;
    else if((p_ctx->capabilities & VC_CONTAINER_IO_CAPS_SEEK_SLOW) &&
            size <= MEM_CACHE_AREA_READ_MAX_SIZE)
       cache->mem_max_size = MEM_CACHE_AREA_READ_MAX_SIZE;
    else
       cache->mem_max_size = MEM_CACHE_READ_MAX_SIZE;
    cache->mem_size = size;
    if(cache->mem_size > cache->mem_max_size) cache->mem_size = cache->mem_max_size;
    cache->mem = malloc(cache->mem_size);
    cache->buffer = cache->mem;
    cache->buffer_end = cache->mem + cache->mem_size;
    if(!cache->mem) return 0;
    private->cached_areas_num++;
    /* Copy any data we've got in the current cache into the new cache */
    main_cache = p_ctx->priv->cache;
    if(main_cache && main_cache->position < main_cache->size)
    {
       cache->size = main_cache->size - main_cache->position;
       if(cache->size > cache->mem_size) cache->size = cache->mem_size;
       memcpy(cache->buffer, main_cache->buffer + main_cache->position, cache->size);
       main_cache->position += cache->size;
    }
    /* Read the rest of the cache directly from the stream */
    if(cache->mem_size > cache->size)
    {
       size_t ret = cache->io->pf_read(cache->io, cache->buffer + cache->size,
                                       cache->mem_size - cache->size);
       cache->size += ret;
       cache->io->priv->actual_offset = cache->offset + cache->size;
    }
    status = vc_container_io_seek(p_ctx, cache->end);
    if(status != VC_CONTAINER_SUCCESS)
       return 0;
    if(p_ctx->capabilities & VC_CONTAINER_IO_CAPS_CANT_SEEK)
       return cache->size;
    else
       return size;
 }
vc_container_io_close()
VC_CONTAINER_STATUS_T vc_container_io_close (VC_CONTAINER_IO_T * context)
Closes an instance of a container i/o module.
Parameters
context Pointer to the VC_CONTAINER_IO_T context of the instance to close
Returns
VC_CONTAINER_SUCCESS on success.
Definition at line 231 of file containers_io.c.
References VC_CONTAINER_IO_PRIVATE_T::caches, VC_CONTAINER_IO_PRIVATE_T::caches_num, VC_CONTAINER_IO_PRIVATE_CACHE_T::dirty, and VC_CONTAINER_IO_T::priv.
Referenced by main(), vc_container_close(), vc_container_open_reader(), and vc_container_open_writer().
 {
    unsigned int i;
    if(p_ctx)
    {
       if(p_ctx->priv)
       {
          if(p_ctx->priv->caches_num)
          {
             if(p_ctx->priv->caches.dirty)
                vc_container_io_cache_flush( p_ctx, &p_ctx->priv->caches, 1 );
          }
          if(p_ctx->priv->async_io)
             async_io_stop( p_ctx->priv->async_io );
          else if(p_ctx->priv->caches_num)
             free(p_ctx->priv->caches.mem);
          for(i = 0; i < p_ctx->priv->cached_areas_num; i++)
             free(p_ctx->priv->cached_areas[i].mem);
          if(p_ctx->pf_close)
             p_ctx->pf_close(p_ctx);
       }
       vc_uri_release(p_ctx->uri_parts);
       free(p_ctx);
    }
    return VC_CONTAINER_SUCCESS;
 }
vc_container_io_control()
VC_CONTAINER_STATUS_T vc_container_io_control (VC_CONTAINER_IO_T * context, VC_CONTAINER_CONTROL_T operation, ...)
Perform control operation on an i/o stream (varargs).
Parameters
context Pointer to the VC_CONTAINER_IO_T instance to use
operation Control operation to be performed
... Additional arguments for the operation
Returns
Status of the operation
Definition at line 433 of file containers_io.c.
 {
    VC_CONTAINER_STATUS_T result;
    va_list args;
    va_start(args, operation);
    result = vc_container_io_control_list(context, operation, args);
    va_end(args);
    return result;
 }
vc_container_io_control_list()
VC_CONTAINER_STATUS_T vc_container_io_control_list (VC_CONTAINER_IO_T * context, VC_CONTAINER_CONTROL_T operation, va_list args)
Perform control operation on an i/o stream (va_list).
Parameters
context Pointer to the VC_CONTAINER_IO_T instance to use
operation Control operation to be performed
args Additional arguments for the operation
Returns
Status of the operation
Definition at line 402 of file containers_io.c.
 {
    VC_CONTAINER_STATUS_T status = VC_CONTAINER_ERROR_UNSUPPORTED_OPERATION;
    if (context->pf_control)
       status = context->pf_control(context, operation, args);
    /* Option to add generic I/O control here */
    if(operation == VC_CONTAINER_CONTROL_IO_FLUSH && context->priv->cache)
    {
       status = VC_CONTAINER_SUCCESS;
       (void)vc_container_io_cache_flush( context, context->priv->cache, 1 );
    }
    if(operation == VC_CONTAINER_CONTROL_SET_IO_PERF_STATS && context->priv->async_io)
    {
       status = VC_CONTAINER_SUCCESS;
       async_io_stats_initialise(context->priv->async_io, va_arg(args, int));
    }
    if(operation == VC_CONTAINER_CONTROL_GET_IO_PERF_STATS && context->priv->async_io)
    {
       status = VC_CONTAINER_SUCCESS;
       async_io_stats_get(context->priv->async_io, va_arg(args, VC_CONTAINER_WRITE_STATS_T *));
    }
    return status;
 }
vc_container_io_create()
VC_CONTAINER_IO_T* vc_container_io_create (const char * uri, VC_CONTAINER_IO_MODE_T mode, VC_CONTAINER_IO_CAPABILITIES_T capabilities, VC_CONTAINER_STATUS_T * p_status)
Creates an empty i/o stream. The i/o function pointers will have to be set by the caller before the i/o gets used. This will create an instance of the container i/o module.
Parameters
uri Uniform Resource Identifier pointing to the multimedia container
mode Mode in which the i/o stream will be opened
capabilities Flags indicating the capabilities of the i/o
status Returns the status of the operation
Returns
If successful, this returns a pointer to the new instance of the i/o module. Returns NULL on failure.
Definition at line 223 of file containers_io.c.
 {
    return vc_container_io_open_core( uri, mode, capabilities, false, p_status );
 }
vc_container_io_open()
VC_CONTAINER_IO_T* vc_container_io_open (const char * uri, VC_CONTAINER_IO_MODE_T mode, VC_CONTAINER_STATUS_T * status)
Opens an i/o stream pointed to by a URI. This will create an instance of the container i/o module.
Parameters
uri Uniform Resource Identifier pointing to the multimedia container
mode Mode in which the i/o stream will be opened
status Returns the status of the operation
Returns
If successful, this returns a pointer to the new instance of the i/o module. Returns NULL on failure.
Definition at line 216 of file containers_io.c.
Referenced by main(), vc_container_open_reader(), and vc_container_open_writer().
 {
    return vc_container_io_open_core( uri, mode, 0, true, p_status );
 }
vc_container_io_peek()
size_t vc_container_io_peek (VC_CONTAINER_IO_T * context, void * buffer, size_t size)
Read data from an i/o stream without advancing the read position within the stream.
Parameters
context Pointer to the VC_CONTAINER_IO_T instance to use
buffer Pointer to the buffer where the data will be read
size Number of bytes to read
Returns
The size of the data actually read.
Definition at line 263 of file containers_io.c.
References VC_CONTAINER_IO_PRIVATE_T::cache, VC_CONTAINER_IO_T::capabilities, VC_CONTAINER_IO_PRIVATE_CACHE_T::offset, VC_CONTAINER_IO_T::offset, VC_CONTAINER_IO_T::priv, VC_CONTAINER_IO_CAPS_CANT_SEEK, vc_container_io_read(), and vc_container_io_seek().
Referenced by vc_container_io_peek_be_uint16(), vc_container_io_peek_be_uint24(), vc_container_io_peek_be_uint32(), vc_container_io_peek_be_uint64(), vc_container_io_peek_le_uint16(), vc_container_io_peek_le_uint24(), vc_container_io_peek_le_uint32(), vc_container_io_peek_le_uint64(), and vc_container_io_peek_uint8().
 {
    size_t ret;
    if(p_ctx->priv->cache)
    {
       /* FIXME: do something a bit more clever than this */
       int64_t offset = p_ctx->offset;
       ret = vc_container_io_read(p_ctx, buffer, size);
       vc_container_io_seek(p_ctx, offset);
       return ret;
    }
    if (p_ctx->capabilities & VC_CONTAINER_IO_CAPS_CANT_SEEK)
       return 0;
    ret = p_ctx->pf_read(p_ctx, buffer, size);
    p_ctx->pf_seek(p_ctx, p_ctx->offset);
    return ret;
 }
vc_container_io_read()
size_t vc_container_io_read (VC_CONTAINER_IO_T * context, void * buffer, size_t size)
Read data from an i/o stream.
Parameters
context Pointer to the VC_CONTAINER_IO_T instance to use
buffer Pointer to the buffer where the data will be read
size Number of bytes to read
Returns
The size of the data actually read.
Definition at line 285 of file containers_io.c.
References VC_CONTAINER_IO_PRIVATE_T::cache, and VC_CONTAINER_IO_T::priv.
Referenced by main(), vc_container_helper_read_debug(), vc_container_io_peek(), vc_container_io_read_be_uint16(), vc_container_io_read_be_uint24(), vc_container_io_read_be_uint32(), vc_container_io_read_be_uint40(), vc_container_io_read_be_uint48(), vc_container_io_read_be_uint56(), vc_container_io_read_be_uint64(), vc_container_io_read_fourcc(), vc_container_io_read_le_uint16(), vc_container_io_read_le_uint24(), vc_container_io_read_le_uint32(), vc_container_io_read_le_uint40(), vc_container_io_read_le_uint48(), vc_container_io_read_le_uint56(), vc_container_io_read_le_uint64(), vc_container_io_read_uint8(), and vc_container_io_skip().
 {
    size_t ret;
    if(p_ctx->priv->cache)
       ret = vc_container_io_cache_read( p_ctx, p_ctx->priv->cache, (uint8_t*)buffer, size );
    else
    {
       ret = p_ctx->pf_read(p_ctx, buffer, size);
       p_ctx->priv->actual_offset += ret;
    }
    p_ctx->offset += ret;
    return ret;
 }
vc_container_io_seek()
VC_CONTAINER_STATUS_T vc_container_io_seek (VC_CONTAINER_IO_T * context, int64_t offset)
Seek into an i/o stream.
Parameters
context Pointer to the VC_CONTAINER_IO_T instance to use
offset Absolute file offset to seek to
Returns
Status of the operation
Definition at line 341 of file containers_io.c.
References VC_CONTAINER_IO_PRIVATE_T::cache, VC_CONTAINER_IO_PRIVATE_T::cached_areas, VC_CONTAINER_IO_PRIVATE_T::cached_areas_num, VC_CONTAINER_IO_PRIVATE_T::caches, VC_CONTAINER_IO_PRIVATE_T::caches_num, VC_CONTAINER_IO_PRIVATE_CACHE_T::end, VC_CONTAINER_IO_T::priv, VC_CONTAINER_IO_PRIVATE_CACHE_T::start, and status.
Referenced by vc_container_io_cache(), and vc_container_io_peek().
 {
    VC_CONTAINER_STATUS_T status;
    unsigned int i;
    /* Check if the requested position is in one of the cached areas */
    for(i = 0; i < p_ctx->priv->cached_areas_num; i++)
    {
       VC_CONTAINER_IO_PRIVATE_CACHE_T *cache = &p_ctx->priv->cached_areas[i];
       if(offset >= cache->start && offset < cache->end)
       {
          p_ctx->priv->cache = cache;
          break;
       }
    }
    if(i == p_ctx->priv->cached_areas_num)
       p_ctx->priv->cache = p_ctx->priv->caches_num ? &p_ctx->priv->caches : 0;
    if(p_ctx->priv->cache)
    {
       status = vc_container_io_cache_seek( p_ctx, p_ctx->priv->cache, offset );
       if(status == VC_CONTAINER_SUCCESS) p_ctx->offset = offset;
       return status;
    }
    if(p_ctx->status == VC_CONTAINER_SUCCESS &&
       offset == p_ctx->offset) return VC_CONTAINER_SUCCESS;
    status = p_ctx->pf_seek(p_ctx, offset);
    if(status == VC_CONTAINER_SUCCESS) p_ctx->offset = offset;
    p_ctx->priv->actual_offset = p_ctx->offset;
    return status;
 }
vc_container_io_skip()
size_t vc_container_io_skip (VC_CONTAINER_IO_T * context, size_t size)
Skip data in an i/o stream without reading it.
Parameters
context Pointer to the VC_CONTAINER_IO_T instance to use
size Number of bytes to skip
Returns
The size of the data actually skipped.
Definition at line 319 of file containers_io.c.
References VC_CONTAINER_IO_PRIVATE_T::cache, VC_CONTAINER_IO_T::priv, and vc_container_io_read().
Referenced by vc_container_helper_read_debug().
 {
    if(!size) return 0;
    if(size < 8)
    {
       uint8_t value[8];
       return vc_container_io_read(p_ctx, value, size);
    }
    if(p_ctx->priv->cache)
    {
       if(vc_container_io_cache_seek(p_ctx, p_ctx->priv->cache, p_ctx->offset + size)) return 0;
       p_ctx->offset += size;
       return size;
    }
    if(vc_container_io_seek(p_ctx, p_ctx->offset + size)) return 0;
    return size;
 }
vc_container_io_write()
size_t vc_container_io_write (VC_CONTAINER_IO_T * context, const void * buffer, size_t size)
Write data to an i/o stream.
Parameters
context Pointer to the VC_CONTAINER_IO_T instance to use
buffer Pointer to the buffer containing the data to write
size Number of bytes to write
Returns
The size of the data actually written.
Definition at line 302 of file containers_io.c.
References VC_CONTAINER_IO_PRIVATE_T::cache, and VC_CONTAINER_IO_T::priv.
Referenced by main(), vc_container_helper_write_debug(), vc_container_io_write_be_uint16(), vc_container_io_write_be_uint24(), vc_container_io_write_be_uint32(), vc_container_io_write_be_uint64(), vc_container_io_write_fourcc(), vc_container_io_write_le_uint16(), vc_container_io_write_le_uint24(), vc_container_io_write_le_uint32(), vc_container_io_write_le_uint64(), and vc_container_io_write_uint8().
 {
    int32_t ret;
    if(p_ctx->priv->cache)
       ret = vc_container_io_cache_write( p_ctx, p_ctx->priv->cache, (const uint8_t*)buffer, size );
    else
    {
       ret = p_ctx->pf_write(p_ctx, buffer, size);
       p_ctx->priv->actual_offset += ret;
    }
    p_ctx->offset += ret;
    return ret < 0 ? 0 : ret;
 }