VideoCore Library: host_applications/linux/apps/raspicam/RaspiHelpers.c File Reference
RaspiHelpers.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <string.h>
#include <memory.h>
#include <unistd.h>
#include <stdint.h>
#include "interface/vcos/vcos.h"
#include "interface/mmal/mmal.h"
#include "interface/mmal/mmal_logging.h"
#include "interface/mmal/util/mmal_default_components.h"
#include "interface/mmal/mmal_parameters_camera.h"
#include "interface/mmal/util/mmal_connection.h"
#include "RaspiCLI.h"
#include "RaspiPreview.h"
#include "RaspiCamControl.h"
#include "RaspiCommonSettings.h"
Macros
#define GIT_COMMIT_ID "Not found"
#define TAINTED ""
Functions
void print_app_details (FILE *fd)
void display_valid_parameters (char *name, void(*app_help)(char *))
void get_sensor_defaults (int camera_num, char *camera_name, int *width, int *height)
void set_app_name (const char *name)
const char * get_app_name ()
MMAL_STATUS_T connect_ports (MMAL_PORT_T *output_port, MMAL_PORT_T *input_port, MMAL_CONNECTION_T **connection)
void check_disable_port (MMAL_PORT_T *port)
void default_signal_handler (int signal_number)
int mmal_status_to_int (MMAL_STATUS_T status)
uint64_t get_microseconds64 ()
Macro Definition Documentation
GIT_COMMIT_ID
#define GIT_COMMIT_ID "Not found"
Definition at line 50 of file RaspiHelpers.c.
TAINTED
#define TAINTED ""
Definition at line 56 of file RaspiHelpers.c.
Function Documentation
check_disable_port()
void check_disable_port (MMAL_PORT_T * port)
Checks if specified port is valid and enabled, then disables it
Parameters
port Pointer the port
Definition at line 187 of file RaspiHelpers.c.
References MMAL_PORT_T::is_enabled, and mmal_port_disable().
 {
    if (port && port->is_enabled)
       mmal_port_disable(port);
 }
connect_ports()
MMAL_STATUS_T connect_ports (MMAL_PORT_T * output_port, MMAL_PORT_T * input_port, MMAL_CONNECTION_T ** connection)
Connect two specific ports together
Parameters
output_port Pointer the output port
input_port Pointer the input port
Pointer to a mmal connection pointer, reassigned if function successful
Returns
Returns a MMAL_STATUS_T giving result of operation
Definition at line 165 of file RaspiHelpers.c.
References mmal_connection_create(), mmal_connection_destroy(), mmal_connection_enable(), MMAL_CONNECTION_FLAG_ALLOCATION_ON_INPUT, MMAL_CONNECTION_FLAG_TUNNELLING, MMAL_SUCCESS, and status.
 {
    MMAL_STATUS_T status;
    status =  mmal_connection_create(connection, output_port, input_port, MMAL_CONNECTION_FLAG_TUNNELLING | MMAL_CONNECTION_FLAG_ALLOCATION_ON_INPUT);
    if (status == MMAL_SUCCESS)
    {
       status =  mmal_connection_enable(*connection);
       if (status != MMAL_SUCCESS)
          mmal_connection_destroy(*connection);
    }
    return status;
 }
default_signal_handler()
void default_signal_handler (int signal_number)
Handler for sigint signals
Parameters
signal_number ID of incoming signal.
Definition at line 199 of file RaspiHelpers.c.
 {
    if (signal_number == SIGUSR1)
    {
       // Handle but ignore - prevents us dropping out if started in none-signal mode
       // and someone sends us the USR1 signal anyway
    }
    else
    {
       // Going to abort on all other signals
       vcos_log_error("Aborting program\n");
       exit(130);
    }
 }
display_valid_parameters()
void display_valid_parameters (char * name, void(*)(char *) app_help)
Definition at line 69 of file RaspiHelpers.c.
References name, print_app_details(), raspicamcontrol_display_help(), raspicommonsettings_display_help(), and raspipreview_display_help().
 {
    print_app_details(stdout);
    // This should be defined in the main app source code
    if (app_help)
       (*app_help)(name);
    // general settings
    raspicommonsettings_display_help();
    // Help for preview options
    raspipreview_display_help();
    // Now display any help information from the camcontrol code
    raspicamcontrol_display_help();
    fprintf(stdout, "\n");
 }
get_app_name()
const char* get_app_name ()
Definition at line 150 of file RaspiHelpers.c.
 {
    return app_name;
 }
get_microseconds64()
uint64_t get_microseconds64 ()
Definition at line 285 of file RaspiHelpers.c.
 {
    struct timespec spec;
    uint64_t us;
    clock_gettime(CLOCK_MONOTONIC_RAW, &spec);
    us = spec.tv_sec * 1000000ULL;
    us += spec.tv_nsec / 1000;
    return us;
 }
get_sensor_defaults()
void get_sensor_defaults (int camera_num, char * camera_name, int * width, int * height)
Definition at line 90 of file RaspiHelpers.c.
References MMAL_PARAMETER_CAMERA_INFO_CAMERA_T::camera_name, MMAL_PARAMETER_CAMERA_INFO_T::cameras, MMAL_COMPONENT_T::control, MMAL_PARAMETER_CAMERA_INFO_T::hdr, MMAL_PARAMETER_HEADER_T::id, MMAL_PARAMETER_CAMERA_INFO_CAMERA_T::max_height, MMAL_PARAMETER_CAMERA_INFO_CAMERA_T::max_width, mmal_component_create(), MMAL_COMPONENT_DEFAULT_CAMERA_INFO, mmal_component_destroy(), MMAL_PARAMETER_CAMERA_INFO, MMAL_PARAMETER_CAMERA_INFO_MAX_STR_LEN, mmal_port_parameter_get(), MMAL_SUCCESS, MMAL_PARAMETER_CAMERA_INFO_T::num_cameras, MMAL_PARAMETER_HEADER_T::size, and status.
 {
    MMAL_COMPONENT_T *camera_info;
    MMAL_STATUS_T status;
    // Default to the OV5647 setup
    strncpy(camera_name, "OV5647", MMAL_PARAMETER_CAMERA_INFO_MAX_STR_LEN);
    // Try to get the camera name and maximum supported resolution
    status = mmal_component_create(MMAL_COMPONENT_DEFAULT_CAMERA_INFO, &camera_info);
    if (status == MMAL_SUCCESS)
    {
       MMAL_PARAMETER_CAMERA_INFO_T param;
       param.hdr.id = MMAL_PARAMETER_CAMERA_INFO;
       param.hdr.size = sizeof(param)-4;  // Deliberately undersize to check firmware version
       status = mmal_port_parameter_get(camera_info->control, &param.hdr);
       if (status != MMAL_SUCCESS)
       {
          // Running on newer firmware
          param.hdr.size = sizeof(param);
          status = mmal_port_parameter_get(camera_info->control, &param.hdr);
          if (status == MMAL_SUCCESS && param.num_cameras > camera_num)
          {
             // Take the parameters from the first camera listed.
             if (*width == 0)
                *width = param.cameras[camera_num].max_width;
             if (*height == 0)
                *height = param.cameras[camera_num].max_height;
             strncpy(camera_name, param.cameras[camera_num].camera_name, MMAL_PARAMETER_CAMERA_INFO_MAX_STR_LEN);
             camera_name[MMAL_PARAMETER_CAMERA_INFO_MAX_STR_LEN-1] = 0;
          }
          else
             vcos_log_error("Cannot read camera info, keeping the defaults for OV5647");
       }
       else
       {
          // Older firmware
          // Nothing to do here, keep the defaults for OV5647
       }
       mmal_component_destroy(camera_info);
    }
    else
    {
       vcos_log_error("Failed to create camera_info component");
    }
    // default to OV5647 if nothing detected..
    if (*width == 0)
       *width = 2592;
    if (*height == 0)
       *height = 1944;
 }
mmal_status_to_int()
int mmal_status_to_int (MMAL_STATUS_T status)
Convert a MMAL status return value to a simple boolean of success ALso displays a fault if code is not success
Parameters
status The error code to convert
Returns
0 if status is success, 1 otherwise
Definition at line 222 of file RaspiHelpers.c.
References MMAL_EAGAIN, MMAL_ECONFIG, MMAL_ECORRUPT, MMAL_EFAULT, MMAL_EINVAL, MMAL_EIO, MMAL_EISCONN, MMAL_ENOENT, MMAL_ENOMEM, MMAL_ENOSPC, MMAL_ENOSYS, MMAL_ENOTCONN, MMAL_ENOTREADY, MMAL_ENXIO, MMAL_ESPIPE, and MMAL_SUCCESS.
Referenced by raspicamcontrol_set_annotate(), raspicamcontrol_set_awb_gains(), raspicamcontrol_set_awb_mode(), raspicamcontrol_set_brightness(), raspicamcontrol_set_colourFX(), raspicamcontrol_set_contrast(), raspicamcontrol_set_DRC(), raspicamcontrol_set_exposure_compensation(), raspicamcontrol_set_exposure_mode(), raspicamcontrol_set_flicker_avoid_mode(), raspicamcontrol_set_flips(), raspicamcontrol_set_gains(), raspicamcontrol_set_imageFX(), raspicamcontrol_set_ISO(), raspicamcontrol_set_metering_mode(), raspicamcontrol_set_ROI(), raspicamcontrol_set_rotation(), raspicamcontrol_set_saturation(), raspicamcontrol_set_sharpness(), raspicamcontrol_set_shutter_speed(), raspicamcontrol_set_stats_pass(), raspicamcontrol_set_stereo_mode(), raspicamcontrol_set_video_stabilisation(), and raspicamcontrol_zoom_in_zoom_out().
 {
    if (status == MMAL_SUCCESS)
       return 0;
    else
    {
       switch (status)
       {
       case MMAL_ENOMEM :
          vcos_log_error("Out of memory");
          break;
       case MMAL_ENOSPC :
          vcos_log_error("Out of resources (other than memory)");
          break;
       case MMAL_EINVAL:
          vcos_log_error("Argument is invalid");
          break;
       case MMAL_ENOSYS :
          vcos_log_error("Function not implemented");
          break;
       case MMAL_ENOENT :
          vcos_log_error("No such file or directory");
          break;
       case MMAL_ENXIO :
          vcos_log_error("No such device or address");
          break;
       case MMAL_EIO :
          vcos_log_error("I/O error");
          break;
       case MMAL_ESPIPE :
          vcos_log_error("Illegal seek");
          break;
       case MMAL_ECORRUPT :
          vcos_log_error("Data is corrupt \attention FIXME: not POSIX");
          break;
       case MMAL_ENOTREADY :
          vcos_log_error("Component is not ready \attention FIXME: not POSIX");
          break;
       case MMAL_ECONFIG :
          vcos_log_error("Component is not configured \attention FIXME: not POSIX");
          break;
       case MMAL_EISCONN :
          vcos_log_error("Port is already connected ");
          break;
       case MMAL_ENOTCONN :
          vcos_log_error("Port is disconnected");
          break;
       case MMAL_EAGAIN :
          vcos_log_error("Resource temporarily unavailable. Try again later");
          break;
       case MMAL_EFAULT :
          vcos_log_error("Bad address");
          break;
       default :
          vcos_log_error("Unknown status error");
          break;
       }
       return 1;
    }
 }
print_app_details()
void print_app_details (FILE * fd)
Definition at line 61 of file RaspiHelpers.c.
Referenced by display_valid_parameters().
 {
    if (!app_name)
       app_name = "Un-named";
    fprintf(fd, "\n\"%s\" Camera App (commit %s%s)\n\n", basename(app_name), GIT_COMMIT_ID, TAINTED);
 }
set_app_name()
void set_app_name (const char * name)
Definition at line 145 of file RaspiHelpers.c.
 {
    app_name = name;
 }