VideoCore Library: interface/mmal/core/mmal_port.c File Reference
mmal_port.c File Reference
#include "mmal.h"
#include "util/mmal_util.h"
#include "core/mmal_component_private.h"
#include "core/mmal_port_private.h"
#include "interface/vcos/vcos.h"
#include "mmal_logging.h"
#include "interface/mmal/mmal_parameters.h"
#include <stdio.h>
Classes
struct MMAL_PORT_PRIVATE_CORE_T
Macros
#define MMAL_COLLECT_PORT_STATS_ENABLED 0
#define LOCK_PORT(a) vcos_mutex_lock(&(a)->priv->core->lock);
#define UNLOCK_PORT(a) vcos_mutex_unlock(&(a)->priv->core->lock);
#define LOCK_SENDING(a) vcos_mutex_lock(&(a)->priv->core->send_lock);
#define UNLOCK_SENDING(a) vcos_mutex_unlock(&(a)->priv->core->send_lock);
#define LOCK_CONNECTION(a) vcos_mutex_lock(&(a)->priv->core->connection_lock);
#define UNLOCK_CONNECTION(a) vcos_mutex_unlock(&(a)->priv->core->connection_lock);
#define IN_TRANSIT_INCREMENT(a)
#define IN_TRANSIT_DECREMENT(a)
#define IN_TRANSIT_WAIT(a)
#define IN_TRANSIT_COUNT(a) (a)->priv->core->transit_buffer_headers
#define PORT_NAME_FORMAT "%s:%.2222s:%i%c%4.4s)"
Typedefs
typedef struct MMAL_PORT_PRIVATE_CORE_T MMAL_PORT_PRIVATE_CORE_T
Functions
MMAL_PORT_T * mmal_port_alloc (MMAL_COMPONENT_T *component, MMAL_PORT_TYPE_T type, unsigned int extra_size)
void mmal_port_free (MMAL_PORT_T *port)
MMAL_PORT_T ** mmal_ports_alloc (MMAL_COMPONENT_T *component, unsigned int ports_num, MMAL_PORT_TYPE_T type, unsigned int extra_size)
void mmal_ports_free (MMAL_PORT_T **ports, unsigned int ports_num)
MMAL_STATUS_T mmal_port_format_commit (MMAL_PORT_T *port)
MMAL_STATUS_T mmal_port_enable (MMAL_PORT_T *port, MMAL_PORT_BH_CB_T cb)
MMAL_STATUS_T mmal_port_disable (MMAL_PORT_T *port)
MMAL_STATUS_T mmal_port_send_buffer (MMAL_PORT_T *port, MMAL_BUFFER_HEADER_T *buffer)
MMAL_STATUS_T mmal_port_flush (MMAL_PORT_T *port)
MMAL_STATUS_T mmal_port_parameter_set (MMAL_PORT_T *port, const MMAL_PARAMETER_HEADER_T *param)
MMAL_STATUS_T mmal_port_parameter_get (MMAL_PORT_T *port, MMAL_PARAMETER_HEADER_T *param)
void mmal_port_buffer_header_callback (MMAL_PORT_T *port, MMAL_BUFFER_HEADER_T *buffer)
void mmal_port_event_send (MMAL_PORT_T *port, MMAL_BUFFER_HEADER_T *buffer)
MMAL_STATUS_T mmal_port_connect (MMAL_PORT_T *port, MMAL_PORT_T *other_port)
MMAL_STATUS_T mmal_port_disconnect (MMAL_PORT_T *port)
uint8_t * mmal_port_payload_alloc (MMAL_PORT_T *port, uint32_t payload_size)
void mmal_port_payload_free (MMAL_PORT_T *port, uint8_t *payload)
MMAL_STATUS_T mmal_port_event_get (MMAL_PORT_T *port, MMAL_BUFFER_HEADER_T **buffer, uint32_t event)
MMAL_STATUS_T mmal_port_pause (MMAL_PORT_T *port, MMAL_BOOL_T pause)
MMAL_BOOL_T mmal_port_is_connected (MMAL_PORT_T *port)
Macro Definition Documentation
IN_TRANSIT_COUNT
#define IN_TRANSIT_COUNT (a) (a)->priv->core->transit_buffer_headers
Definition at line 150 of file mmal_port.c.
Referenced by mmal_port_buffer_header_callback().
IN_TRANSIT_DECREMENT
#define IN_TRANSIT_DECREMENT (a)
Value:
vcos_mutex_lock(&(a)->priv->core->transit_lock); \
   if (!--(a)->priv->core->transit_buffer_headers) \
      vcos_semaphore_post(&(a)->priv->core->transit_sema); \
   vcos_mutex_unlock(&(a)->priv->core->transit_lock)
Definition at line 142 of file mmal_port.c.
Referenced by mmal_port_send_buffer().
IN_TRANSIT_INCREMENT
#define IN_TRANSIT_INCREMENT (a)
Value:
vcos_mutex_lock(&(a)->priv->core->transit_lock); \
   if (!(a)->priv->core->transit_buffer_headers++) \
      vcos_semaphore_wait(&(a)->priv->core->transit_sema); \
   vcos_mutex_unlock(&(a)->priv->core->transit_lock)
Definition at line 137 of file mmal_port.c.
Referenced by mmal_port_send_buffer().
IN_TRANSIT_WAIT
#define IN_TRANSIT_WAIT (a)
Value:
vcos_semaphore_wait(&(a)->priv->core->transit_sema); \
   vcos_semaphore_post(&(a)->priv->core->transit_sema)
Definition at line 147 of file mmal_port.c.
LOCK_CONNECTION
#define LOCK_CONNECTION (a) vcos_mutex_lock(&(a)->priv->core->connection_lock);
Definition at line 132 of file mmal_port.c.
Referenced by mmal_port_connect(), mmal_port_disable(), mmal_port_disconnect(), and mmal_port_enable().
LOCK_PORT
#define LOCK_PORT (a) vcos_mutex_lock(&(a)->priv->core->lock);
Definition at line 124 of file mmal_port.c.
Referenced by mmal_port_format_commit(), mmal_port_parameter_get(), mmal_port_parameter_set(), mmal_port_payload_alloc(), and mmal_port_payload_free().
LOCK_SENDING
#define LOCK_SENDING (a) vcos_mutex_lock(&(a)->priv->core->send_lock);
Definition at line 128 of file mmal_port.c.
Referenced by mmal_port_flush(), mmal_port_pause(), and mmal_port_send_buffer().
MMAL_COLLECT_PORT_STATS_ENABLED
#define MMAL_COLLECT_PORT_STATS_ENABLED 0
Only collect port stats if enabled in build. Performance could be affected on an ARM since gettimeofday() involves a system call.
Definition at line 48 of file mmal_port.c.
Referenced by mmal_port_buffer_header_callback().
PORT_NAME_FORMAT
#define PORT_NAME_FORMAT "%s:%.2222s:%i%c%4.4s)"
Definition at line 153 of file mmal_port.c.
Referenced by mmal_port_alloc().
UNLOCK_CONNECTION
#define UNLOCK_CONNECTION (a) vcos_mutex_unlock(&(a)->priv->core->connection_lock);
Definition at line 133 of file mmal_port.c.
Referenced by mmal_port_connect(), mmal_port_disable(), mmal_port_disconnect(), and mmal_port_enable().
UNLOCK_PORT
#define UNLOCK_PORT (a) vcos_mutex_unlock(&(a)->priv->core->lock);
Definition at line 125 of file mmal_port.c.
Referenced by mmal_port_payload_alloc(), and mmal_port_payload_free().
UNLOCK_SENDING
#define UNLOCK_SENDING (a) vcos_mutex_unlock(&(a)->priv->core->send_lock);
Definition at line 129 of file mmal_port.c.
Referenced by mmal_port_flush(), mmal_port_pause(), and mmal_port_send_buffer().
Typedef Documentation
MMAL_PORT_PRIVATE_CORE_T
typedef struct MMAL_PORT_PRIVATE_CORE_T MMAL_PORT_PRIVATE_CORE_T
Definition of the core's private structure for a port.
Function Documentation
mmal_port_alloc()
MMAL_PORT_T* mmal_port_alloc (MMAL_COMPONENT_T * component, MMAL_PORT_TYPE_T type, unsigned int extra_size)
Allocate a port structure
Definition at line 158 of file mmal_port.c.
References MMAL_PORT_T::component, MMAL_PORT_PRIVATE_T::core, MMAL_PORT_PRIVATE_CORE_T::lock, LOG_ERROR, LOG_TRACE, MMAL_PORT_PRIVATE_T::module, MMAL_COMPONENT_T::name, MMAL_PORT_T::name, MMAL_PORT_PRIVATE_CORE_T::name, MMAL_PORT_PRIVATE_CORE_T::name_size, PORT_NAME_FORMAT, MMAL_PORT_T::priv, MMAL_PORT_T::type, and vcos_calloc().
Referenced by mmal_port_clock_alloc(), and mmal_ports_alloc().
 {
    MMAL_PORT_T *port;
    MMAL_PORT_PRIVATE_CORE_T *core;
    unsigned int name_size = strlen(component->name) + sizeof(PORT_NAME_FORMAT);
    unsigned int size = sizeof(*port) + sizeof(MMAL_PORT_PRIVATE_T) +
       sizeof(MMAL_PORT_PRIVATE_CORE_T) + name_size + extra_size;
    MMAL_BOOL_T lock = 0, lock_send = 0, lock_transit = 0, sema_transit = 0;
    MMAL_BOOL_T lock_stats = 0, lock_connection = 0;
    LOG_TRACE("component:%s type:%u extra:%u", component->name, type, extra_size);
    port = vcos_calloc(1, size, "mmal port");
    if (!port)
    {
       LOG_ERROR("failed to allocate port, size %u", size);
       return 0;
    }
    port->type = type;
    port->priv = (MMAL_PORT_PRIVATE_T *)(port+1);
    port->priv->core = core = (MMAL_PORT_PRIVATE_CORE_T *)(port->priv+1);
    if (extra_size)
       port->priv->module = (struct MMAL_PORT_MODULE_T *)(port->priv->core+1);
    port->component = component;
    port->name = core->name = ((char *)(port->priv->core+1)) + extra_size;
    core->name_size = name_size;
    mmal_port_name_update(port);
    core->queue_last = &core->queue_first;
    port->priv->pf_connect = mmal_port_connect_default;
    lock = vcos_mutex_create(&port->priv->core->lock, "mmal port lock") == VCOS_SUCCESS;
    lock_send = vcos_mutex_create(&port->priv->core->send_lock, "mmal port send lock") == VCOS_SUCCESS;
    lock_transit = vcos_mutex_create(&port->priv->core->transit_lock, "mmal port transit lock") == VCOS_SUCCESS;
    sema_transit = vcos_semaphore_create(&port->priv->core->transit_sema, "mmal port transit sema", 1) == VCOS_SUCCESS;
    lock_stats = vcos_mutex_create(&port->priv->core->stats_lock, "mmal stats lock") == VCOS_SUCCESS;
    lock_connection = vcos_mutex_create(&port->priv->core->connection_lock, "mmal connection lock") == VCOS_SUCCESS;
    if (!lock || !lock_send || !lock_transit || !sema_transit || !lock_stats || !lock_connection)
    {
       LOG_ERROR("%s: failed to create sync objects (%u,%u,%u,%u,%u,%u)",
             port->name, lock, lock_send, lock_transit, sema_transit, lock_stats, lock_connection);
       goto error;
    }
    port->format = mmal_format_alloc();
    if (!port->format)
    {
       LOG_ERROR("%s: failed to allocate format object", port->name);
       goto error;
    }
    port->priv->core->format_ptr_copy = port->format;
    LOG_TRACE("%s: created at %p", port->name, port);
    return port;
  error:
    if (lock) vcos_mutex_delete(&port->priv->core->lock);
    if (lock_send) vcos_mutex_delete(&port->priv->core->send_lock);
    if (lock_transit) vcos_mutex_delete(&port->priv->core->transit_lock);
    if (sema_transit) vcos_semaphore_delete(&port->priv->core->transit_sema);
    if (lock_stats) vcos_mutex_delete(&port->priv->core->stats_lock);
    if (lock_connection) vcos_mutex_delete(&port->priv->core->connection_lock);
    if (port->format) mmal_format_free(port->format);
    vcos_free(port);
    return 0;
 }
mmal_port_buffer_header_callback()
void mmal_port_buffer_header_callback (MMAL_PORT_T * port, MMAL_BUFFER_HEADER_T * buffer)
Buffer header callback.
Definition at line 897 of file mmal_port.c.
References MMAL_BUFFER_HEADER_T::cmd, MMAL_PORT_T::component, MMAL_BUFFER_HEADER_T::data, IN_TRANSIT_COUNT, MMAL_PORT_T::index, MMAL_BUFFER_HEADER_T::length, LOG_ERROR, LOG_TRACE, MMAL_COLLECT_PORT_STATS_ENABLED, MMAL_COMPONENT_T::name, MMAL_PORT_T::name, MMAL_BUFFER_HEADER_T::offset, MMAL_PORT_T::type, and vcos_verify.
Referenced by mmal_port_flush().
 {
 #ifdef ENABLE_MMAL_EXTRA_LOGGING
    LOG_TRACE("%s(%i:%i) port %p, buffer %p (%i,%p,%i,%i)",
              port->component->name, (int)port->type, (int)port->index, port, buffer,
              buffer ? (int)buffer->cmd : 0, buffer ? buffer->data : 0,
              buffer ? (int)buffer->offset : 0, buffer ? (int)buffer->length : 0);
 #endif
    if (!vcos_verify(IN_TRANSIT_COUNT(port) >= 0))
       LOG_ERROR("%s: buffer headers in transit < 0 (%d)", port->name, (int)IN_TRANSIT_COUNT(port));
    if (MMAL_COLLECT_PORT_STATS_ENABLED)
    {
       mmal_port_update_port_stats(port, MMAL_CORE_STATS_TX);
    }
    port->priv->core->buffer_header_callback(port, buffer);
    IN_TRANSIT_DECREMENT(port);
 }
mmal_port_event_send()
void mmal_port_event_send (MMAL_PORT_T * port, MMAL_BUFFER_HEADER_T * buffer)
Event callback
Definition at line 920 of file mmal_port.c.
References MMAL_PORT_PRIVATE_CORE_T::buffer_header_callback, MMAL_PORT_PRIVATE_T::core, MMAL_PORT_T::index, LOG_ERROR, mmal_buffer_header_release(), MMAL_PORT_T::priv, and MMAL_PORT_T::type.
Referenced by mmal_event_eos_send(), mmal_event_error_send(), and mmal_event_forward().
 {
    if (port->priv->core->buffer_header_callback)
    {
       port->priv->core->buffer_header_callback(port, buffer);
    }
    else
    {
       LOG_ERROR("event lost on port %i,%i (buffer header callback not defined)",
                 (int)port->type, (int)port->index);
       mmal_buffer_header_release(buffer);
    }
 }
mmal_port_free()
void mmal_port_free (MMAL_PORT_T * port)
Free a port structure
Definition at line 228 of file mmal_port.c.
References MMAL_PORT_PRIVATE_CORE_T::connection_lock, MMAL_PORT_PRIVATE_T::core, MMAL_PORT_T::format, MMAL_PORT_PRIVATE_CORE_T::format_ptr_copy, MMAL_PORT_PRIVATE_CORE_T::lock, LOG_TRACE, mmal_format_free(), MMAL_PORT_T::name, MMAL_PORT_T::priv, MMAL_PORT_PRIVATE_CORE_T::send_lock, MMAL_PORT_PRIVATE_CORE_T::stats_lock, MMAL_PORT_PRIVATE_CORE_T::transit_lock, MMAL_PORT_PRIVATE_CORE_T::transit_sema, vcos_assert, vcos_free(), vcos_mutex_delete(), and vcos_semaphore_delete().
Referenced by mmal_ports_free().
 {
    LOG_TRACE("%s at %p", port ? port->name : "<invalid>", port);
    if (!port)
       return;
    vcos_assert(port->format == port->priv->core->format_ptr_copy);
    mmal_format_free(port->priv->core->format_ptr_copy);
    vcos_mutex_delete(&port->priv->core->connection_lock);
    vcos_mutex_delete(&port->priv->core->stats_lock);
    vcos_semaphore_delete(&port->priv->core->transit_sema);
    vcos_mutex_delete(&port->priv->core->transit_lock);
    vcos_mutex_delete(&port->priv->core->send_lock);
    vcos_mutex_delete(&port->priv->core->lock);
    vcos_free(port);
 }
mmal_port_is_connected()
MMAL_BOOL_T mmal_port_is_connected (MMAL_PORT_T * port)
Returns whether a port is connected or not
Definition at line 1506 of file mmal_port.c.
References MMAL_PORT_PRIVATE_CORE_T::connected_port, MMAL_PORT_PRIVATE_T::core, and MMAL_PORT_T::priv.
 {
    return !!port->priv->core->connected_port;
 }
mmal_port_pause()
MMAL_STATUS_T mmal_port_pause (MMAL_PORT_T * port, MMAL_BOOL_T pause)
Pause processing on a port
Definition at line 1464 of file mmal_port.c.
References MMAL_PORT_PRIVATE_T::core, MMAL_PORT_T::is_enabled, MMAL_PORT_PRIVATE_CORE_T::is_paused, LOCK_SENDING, MMAL_SUCCESS, MMAL_BUFFER_HEADER_T::next, MMAL_PORT_PRIVATE_T::pf_send, MMAL_PORT_T::priv, MMAL_PORT_PRIVATE_CORE_T::queue_first, MMAL_PORT_PRIVATE_CORE_T::queue_last, status, and UNLOCK_SENDING.
Referenced by mmal_component_disable(), and mmal_component_enable().
 {
    MMAL_STATUS_T status = MMAL_SUCCESS;
    LOCK_SENDING(port);
    /* When resuming from pause, we send all our queued buffers to the port */
    if (!pause && port->is_enabled)
    {
       MMAL_BUFFER_HEADER_T *buffer = port->priv->core->queue_first;
       while (buffer)
       {
          MMAL_BUFFER_HEADER_T *next = buffer->next;
          status = port->priv->pf_send(port, buffer);
          if (status != MMAL_SUCCESS)
          {
             buffer->next = next;
             break;
          }
          buffer = next;
       }
       /* If for some reason we could not send one of the buffers, we just
        * leave all the buffers in our internal queue and return an error. */
       if (status != MMAL_SUCCESS)
       {
          port->priv->core->queue_first = buffer;
       }
       else
       {
          port->priv->core->queue_first = 0;
          port->priv->core->queue_last = &port->priv->core->queue_first;
       }
    }
    if (status == MMAL_SUCCESS)
       port->priv->core->is_paused = pause;
    UNLOCK_SENDING(port);
    return status;
 }
mmal_ports_alloc()
MMAL_PORT_T** mmal_ports_alloc (MMAL_COMPONENT_T * component, unsigned int ports_num, MMAL_PORT_TYPE_T type, unsigned int extra_size)
Allocate an array of ports
Definition at line 247 of file mmal_port.c.
References MMAL_PORT_T::index, mmal_port_alloc(), and vcos_calloc().
Referenced by mmal_ports_clock_alloc().
 {
    MMAL_PORT_T **ports;
    unsigned int i;
    ports = vcos_calloc(1, sizeof(MMAL_PORT_T *) * ports_num, "mmal ports");
    if (!ports)
       return 0;
    for (i = 0; i < ports_num; i++)
    {
       ports[i] = mmal_port_alloc(component, type, extra_size);
       if (!ports[i])
          break;
       ports[i]->index = i;
       mmal_port_name_update(ports[i]);
    }
    if (i != ports_num)
    {
       for (ports_num = i, i = 0; i < ports_num; i++)
          mmal_port_free(ports[i]);
       vcos_free(ports);
       return 0;
    }
    return ports;
 }
mmal_ports_free()
void mmal_ports_free (MMAL_PORT_T ** ports, unsigned int ports_num)
Free an array of ports
Definition at line 278 of file mmal_port.c.
References mmal_port_free(), and vcos_free().
 {
    unsigned int i;
    for (i = 0; i < ports_num; i++)
       mmal_port_free(ports[i]);
    vcos_free(ports);
 }