VideoCore Library: interface/mmal/openmaxil/mmalomx_marks.c File Reference
mmalomx_marks.c File Reference
#include "mmalomx.h"
#include "mmalomx_buffer.h"
#include "mmalomx_marks.h"
#include "mmalomx_commands.h"
#include "mmalomx_logging.h"
Macros
#define MMALOMX_GET_MARK(port, mark)
#define MMALOMX_PUT_MARK(port, mark)
Functions
void mmalomx_mark_process_incoming (MMALOMX_COMPONENT_T *component, MMALOMX_PORT_T *port, OMX_BUFFERHEADERTYPE *omx_buffer)
void mmalomx_mark_process_outgoing (MMALOMX_COMPONENT_T *component, MMALOMX_PORT_T *port, OMX_BUFFERHEADERTYPE *omx_buffer)
Detailed Description
OpenMAX IL adaptation layer for MMAL - Marking related functions
Note that we do not support buffer marks properly other than for conformance testing. For input ports, we just move the mark over to the output port.
Definition in file mmalomx_marks.c.
Macro Definition Documentation
MMALOMX_GET_MARK
#define MMALOMX_GET_MARK (port, mark)
Value:
mark = &port->marks[port->marks_first]; \
   port->marks_num--; \
   port->marks_first = ++port->marks_first == MAX_MARKS_NUM ? 0 : port->marks_first
Definition at line 41 of file mmalomx_marks.c.
Referenced by mmalomx_mark_process_incoming(), and mmalomx_mark_process_outgoing().
MMALOMX_PUT_MARK
#define MMALOMX_PUT_MARK (port, mark)
Value:
port->marks[(port->marks_first + port->marks_num) % MAX_MARKS_NUM] = *mark; \
   port->marks_num++;
Definition at line 45 of file mmalomx_marks.c.
Referenced by mmalomx_mark_process_incoming().
Function Documentation
mmalomx_mark_process_incoming()
void mmalomx_mark_process_incoming (MMALOMX_COMPONENT_T * component, MMALOMX_PORT_T * port, OMX_BUFFERHEADERTYPE * omx_buffer)
Definition at line 49 of file mmalomx_marks.c.
References MMALOMX_PORT_T::direction, OMX_MARKTYPE::hMarkTargetComponent, OMX_BUFFERHEADERTYPE::hMarkTargetComponent, MMALOMX_PORT_T::index, MMALOMX_PORT_T::marks_num, MAX_MARKS_NUM, mmalomx_callback_event_handler(), MMALOMX_GET_MARK, MMALOMX_PUT_MARK, NULL, OMX_CommandMarkBuffer, OMX_DirInput, OMX_DirOutput, OMX_EventCmdComplete, OMX_MARKTYPE::pMarkData, OMX_BUFFERHEADERTYPE::pMarkData, MMALOMX_COMPONENT_T::ports, and MMALOMX_COMPONENT_T::ports_num.
Referenced by mmalomx_buffer_send().
 {
    /* Tag buffers with OMX marks */
    if (!omx_buffer->hMarkTargetComponent && port->marks_num > 0 &&
        port->direction == OMX_DirInput)
    {
       OMX_MARKTYPE *mark;
       MMALOMX_GET_MARK(port, mark);
       omx_buffer->hMarkTargetComponent = mark->hMarkTargetComponent;
       omx_buffer->pMarkData = mark->pMarkData;
       mmalomx_callback_event_handler(component, OMX_EventCmdComplete,
          OMX_CommandMarkBuffer, port->index, NULL);
    }
    /* We do not support buffer marks properly other than for conformance testing.
     * For input ports, we just move the mark over to the output port. */
    if (port->direction == OMX_DirInput && omx_buffer->hMarkTargetComponent)
    {
       OMX_MARKTYPE mark = {omx_buffer->hMarkTargetComponent, omx_buffer->pMarkData};
       unsigned int i;
       for (i = 0; i < component->ports_num; i++)
       {
          if (component->ports[i].direction != OMX_DirOutput ||
              component->ports[i].marks_num >= MAX_MARKS_NUM)
             continue;
          MMALOMX_PUT_MARK((&component->ports[i]), (&mark));
       }
    }
 }
mmalomx_mark_process_outgoing()
void mmalomx_mark_process_outgoing (MMALOMX_COMPONENT_T * component, MMALOMX_PORT_T * port, OMX_BUFFERHEADERTYPE * omx_buffer)
Definition at line 81 of file mmalomx_marks.c.
References MMALOMX_PORT_T::direction, OMX_MARKTYPE::hMarkTargetComponent, OMX_BUFFERHEADERTYPE::hMarkTargetComponent, MMALOMX_PORT_T::marks_num, mmalomx_callback_event_handler(), MMALOMX_GET_MARK, NULL, MMALOMX_COMPONENT_T::omx, OMX_DirOutput, OMX_EventMark, OMX_MARKTYPE::pMarkData, and OMX_BUFFERHEADERTYPE::pMarkData.
 {
    /* Tag buffers with OMX marks */
    if (port->direction == OMX_DirOutput &&
        !omx_buffer->hMarkTargetComponent && port->marks_num)
    {
          OMX_MARKTYPE *mark;
          MMALOMX_GET_MARK(port, mark);
          omx_buffer->hMarkTargetComponent = mark->hMarkTargetComponent;
          omx_buffer->pMarkData = mark->pMarkData;
    }
    /* Check if we need to trigger a Mark event */
    if (omx_buffer->hMarkTargetComponent &&
        omx_buffer->hMarkTargetComponent == (OMX_HANDLETYPE)&component->omx)
    {
       mmalomx_callback_event_handler(component, OMX_EventMark, 0, 0, omx_buffer->pMarkData);
       omx_buffer->hMarkTargetComponent = NULL;
       omx_buffer->pMarkData = NULL;
    }
 }