VideoCore Library: interface/mmal/vc/mmal_vc_client.c File Reference
mmal_vc_client.c File Reference
#include "mmal.h"
#include "mmal_vc_msgs.h"
#include "mmal_vc_api.h"
#include "mmal_vc_client_priv.h"
#include "interface/vcos/vcos.h"
#include "vchiq_util.h"
#include "interface/mmal/core/mmal_buffer_private.h"
#include "interface/mmal/core/mmal_component_private.h"
#include "interface/mmal/core/mmal_port_private.h"
#include "interface/mmal/util/mmal_list.h"
#include "interface/mmal/util/mmal_util.h"
#include "interface/mmal/mmal_logging.h"
#include <stdio.h>
Classes
struct MMAL_WAITER_T
struct MMAL_WAITPOOL_T
struct MMAL_CLIENT_T
struct MMAL_CLIENT_COMPONENT_T
struct MMAL_CLIENT_COMPONENT_POOL_T
struct MMAL_CLIENT_CONTEXT_T
struct MMAL_CLIENT_CONTEXT_POOL_T
Macros
#define VCOS_LOG_CATEGORY (&mmal_ipc_log_category)
#define MAX_WAITERS 16
#define MAX_COMPONENT_HANDLES 128
#define MAX_CLIENT_CONTEXTS 512
#define CLIENT_CONTEXT_MAGIC 0xFEDC0000
#define CLIENT_CONTEXT_MAGIC_MASK(a) (a & 0xFFFF)
#define CLIENT_CONTEXT_MAGIC_CHECK(a) (a & 0xFFFF0000)
Typedefs
typedef struct MMAL_WAITER_T MMAL_WAITER_T
Functions
uint32_t mmal_vc_allocate_client_component (MMAL_COMPONENT_T *component)
void mmal_vc_release_client_component (MMAL_COMPONENT_T *component)
uint32_t mmal_vc_allocate_client_context (MMAL_VC_CLIENT_BUFFER_CONTEXT_T *context)
MMAL_VC_CLIENT_BUFFER_CONTEXT_T * mmal_vc_lookup_client_context (int index)
void mmal_vc_release_client_context (MMAL_VC_CLIENT_BUFFER_CONTEXT_T *context)
MMAL_STATUS_T mmal_vc_sendwait_message (struct MMAL_CLIENT_T *client, mmal_worker_msg_header *msg_header, size_t size, uint32_t msgid, void *dest, size_t *destlen, MMAL_BOOL_T send_dummy_bulk)
MMAL_STATUS_T mmal_vc_send_message (MMAL_CLIENT_T *client, mmal_worker_msg_header *msg_header, size_t size, uint8_t *data, size_t data_size, uint32_t msgid)
MMAL_STATUS_T mmal_vc_use (void)
MMAL_STATUS_T mmal_vc_release (void)
MMAL_STATUS_T mmal_vc_init_fd (int dev_vchiq_fd)
MMAL_STATUS_T mmal_vc_init (void)
void mmal_vc_deinit (void)
MMAL_CLIENT_T * mmal_vc_get_client (void)
Macro Definition Documentation
CLIENT_CONTEXT_MAGIC
#define CLIENT_CONTEXT_MAGIC 0xFEDC0000
Definition at line 173 of file mmal_vc_client.c.
Referenced by mmal_vc_lookup_client_context().
CLIENT_CONTEXT_MAGIC_CHECK
#define CLIENT_CONTEXT_MAGIC_CHECK (a) (a & 0xFFFF0000)
Definition at line 175 of file mmal_vc_client.c.
Referenced by mmal_vc_lookup_client_context().
CLIENT_CONTEXT_MAGIC_MASK
#define CLIENT_CONTEXT_MAGIC_MASK (a) (a & 0xFFFF)
Definition at line 174 of file mmal_vc_client.c.
Referenced by mmal_vc_lookup_client_context().
MAX_CLIENT_CONTEXTS
#define MAX_CLIENT_CONTEXTS 512
Definition at line 157 of file mmal_vc_client.c.
Referenced by mmal_vc_lookup_client_context().
MAX_COMPONENT_HANDLES
#define MAX_COMPONENT_HANDLES 128
Definition at line 91 of file mmal_vc_client.c.
Referenced by mmal_vc_allocate_client_component(), and mmal_vc_release_client_component().
MAX_WAITERS
#define MAX_WAITERS 16
Definition at line 46 of file mmal_vc_client.c.
VCOS_LOG_CATEGORY
#define VCOS_LOG_CATEGORY (&mmal_ipc_log_category)
Definition at line 41 of file mmal_vc_client.c.
Typedef Documentation
MMAL_WAITER_T
typedef struct MMAL_WAITER_T MMAL_WAITER_T
Client threads use one of these to wait for a reply from VideoCore.
Function Documentation
mmal_vc_allocate_client_component()
uint32_t mmal_vc_allocate_client_component (MMAL_COMPONENT_T * component)
Definition at line 108 of file mmal_vc_client.c.
References MMAL_CLIENT_COMPONENT_T::component, MMAL_CLIENT_COMPONENT_POOL_T::components, MMAL_CLIENT_COMPONENT_T::index, MMAL_CLIENT_COMPONENT_T::inuse, MMAL_CLIENT_COMPONENT_POOL_T::lock, MAX_COMPONENT_HANDLES, vcos_mutex_lock(), vcos_mutex_unlock(), and vcos_verify.
 {
    int i;
    vcos_mutex_lock(&client_component_pool.lock);
    for (i=0; i<MAX_COMPONENT_HANDLES; i++)
    {
       if (client_component_pool.components[i].inuse == 0)
          break;
    }
    if (vcos_verify(i != MAX_COMPONENT_HANDLES))
    {
       client_component_pool.components[i].index = i;
       client_component_pool.components[i].component = component;
       client_component_pool.components[i].inuse = 1;
    }
    vcos_mutex_unlock(&client_component_pool.lock);
    return i;
 }
mmal_vc_allocate_client_context()
uint32_t mmal_vc_allocate_client_context (MMAL_VC_CLIENT_BUFFER_CONTEXT_T * context)
Definition at line 177 of file mmal_vc_client.c.
 {
    int i;
    vcos_mutex_lock(&client_context_pool.lock);
    for (i=0; i<MAX_CLIENT_CONTEXTS; i++)
    {
       if (client_context_pool.contexts[i].inuse == 0)
          break;
    }
    if (vcos_verify(i != MAX_CLIENT_CONTEXTS))
    {
       client_context_pool.contexts[i].index = i;
       client_context_pool.contexts[i].ctx = context;
       client_context_pool.contexts[i].inuse = 1;
    }
    vcos_mutex_unlock(&client_context_pool.lock);
    return i | CLIENT_CONTEXT_MAGIC;
 }
mmal_vc_deinit()
void mmal_vc_deinit (void)
Definition at line 1028 of file mmal_vc_client.c.
References MMAL_CLIENT_T::bulk_lock, MMAL_CLIENT_T::lock, MMAL_CLIENT_T::refcount, vcos_mutex_delete(), vcos_mutex_lock(), and vcos_mutex_unlock().
Referenced by mmal_vc_drm_get_lhs32(), and mmal_vc_drm_get_time().
 {
    int count;
    vcos_mutex_lock(&client.lock);
    count = --client.refcount;
    if (count != 0)
    {
       /* Still in use so don't do anything */
       vcos_mutex_unlock(&client.lock);
       return;
    }
    vcos_mutex_delete(&client.bulk_lock);
    destroy_waitpool(&client.waitpool);
    vchiq_close_service(client.service);
    vchiq_shutdown(mmal_vchiq_instance);
    vcos_log_unregister(VCOS_LOG_CATEGORY);
    client.service = VCHIQ_SERVICE_HANDLE_INVALID;
    client.inited = 0;
    vcos_mutex_unlock(&client.lock);
 }
mmal_vc_get_client()
MMAL_CLIENT_T* mmal_vc_get_client (void)
Definition at line 1052 of file mmal_vc_client.c.
Referenced by mmal_vc_compact(), mmal_vc_consume_mem(), mmal_vc_drm_get_lhs32(), mmal_vc_drm_get_time(), mmal_vc_get_core_stats(), mmal_vc_get_stats(), mmal_vc_get_version(), mmal_vc_host_log(), mmal_vc_lmk(), mmal_vc_opaque_acquire(), mmal_vc_opaque_alloc_desc(), and mmal_vc_opaque_release().
 {
    return &client;
 }
mmal_vc_init()
MMAL_STATUS_T mmal_vc_init (void)
Definition at line 1023 of file mmal_vc_client.c.
References mmal_vc_init_fd().
Referenced by mmal_vc_drm_get_lhs32(), and mmal_vc_drm_get_time().
 {
    return mmal_vc_init_fd(-1);
 }
mmal_vc_init_fd()
MMAL_STATUS_T mmal_vc_init_fd (int dev_vchiq_fd)
Definition at line 924 of file mmal_vc_client.c.
References MMAL_EIO, status, and vcos_once().
Referenced by mmal_vc_init().
 {
    VCHIQ_SERVICE_PARAMS_T vchiq_params;
    MMAL_BOOL_T vchiq_initialised = 0, waitpool_initialised = 0;
    MMAL_BOOL_T service_initialised = 0;
    MMAL_STATUS_T status = MMAL_EIO;
    VCHIQ_STATUS_T vchiq_status;
    int count;
    vcos_once(&once, init_once);
    vcos_mutex_lock(&client.lock);
    count = client.refcount++;
    if (count > 0)
    {
       /* Already initialised so nothing to do */
       vcos_mutex_unlock(&client.lock);
       return MMAL_SUCCESS;
    }
    vcos_log_register("mmalipc", VCOS_LOG_CATEGORY);
    /* Initialise a VCHIQ instance */
    vchiq_status = vchiq_initialise_fd(&mmal_vchiq_instance, dev_vchiq_fd);
    if (vchiq_status != VCHIQ_SUCCESS)
    {
       LOG_ERROR("failed to initialise vchiq");
       status = MMAL_EIO;
       goto error;
    }
    vchiq_initialised = 1;
    vchiq_status = vchiq_connect(mmal_vchiq_instance);
    if (vchiq_status != VCHIQ_SUCCESS)
    {
       LOG_ERROR("failed to connect to vchiq");
       status = MMAL_EIO;
       goto error;
    }
    memset(&vchiq_params,0,sizeof(vchiq_params));
    vchiq_params.fourcc = MMAL_CONTROL_FOURCC();
    vchiq_params.callback = mmal_vc_vchiq_callback;
    vchiq_params.userdata = &client;
    vchiq_params.version = WORKER_VER_MAJOR;
    vchiq_params.version_min = WORKER_VER_MINIMUM;
    vchiq_status = vchiq_open_service(mmal_vchiq_instance, &vchiq_params, &client.service);
    if (vchiq_status != VCHIQ_SUCCESS)
    {
       LOG_ERROR("could not open vchiq service");
       status = MMAL_EIO;
       goto error;
    }
    client.usecount = 1; /* usecount set to 1 by the open call. */
    service_initialised = 1;
    status = create_waitpool(&client.waitpool);
    if (status != MMAL_SUCCESS)
    {
       LOG_ERROR("could not create wait pool");
       goto error;
    }
    waitpool_initialised = 1;
    if (vcos_mutex_create(&client.bulk_lock, "mmal client bulk lock") != VCOS_SUCCESS)
    {
       LOG_ERROR("could not create bulk lock");
       status = MMAL_ENOSPC;
       goto error;
    }
    client.inited = 1;
    vcos_mutex_unlock(&client.lock);
    /* assume we're not using VC immediately.  Do this outside the lock */
    mmal_vc_release();
    return MMAL_SUCCESS;
  error:
    if (waitpool_initialised)
       destroy_waitpool(&client.waitpool);
    if (service_initialised)
    {
       client.usecount = 0;
       vchiq_close_service(client.service);
    }
    if (vchiq_initialised)
       vchiq_shutdown(mmal_vchiq_instance);
    vcos_log_unregister(VCOS_LOG_CATEGORY);
    client.refcount--;
    vcos_mutex_unlock(&client.lock);
    return status;
 }
mmal_vc_lookup_client_context()
MMAL_VC_CLIENT_BUFFER_CONTEXT_T* mmal_vc_lookup_client_context (int index)
Definition at line 199 of file mmal_vc_client.c.
References CLIENT_CONTEXT_MAGIC, CLIENT_CONTEXT_MAGIC_CHECK, CLIENT_CONTEXT_MAGIC_MASK, MMAL_CLIENT_CONTEXT_POOL_T::contexts, MMAL_CLIENT_CONTEXT_T::ctx, MMAL_WAITER_T::inuse, MAX_CLIENT_CONTEXTS, NULL, vcos_assert, and vcos_verify.
 {
    if (vcos_verify((CLIENT_CONTEXT_MAGIC_CHECK(index) == CLIENT_CONTEXT_MAGIC) &&
                    (CLIENT_CONTEXT_MAGIC_MASK(index) < MAX_CLIENT_CONTEXTS)))
    {
       vcos_assert(client_context_pool.contexts[CLIENT_CONTEXT_MAGIC_MASK(index)].inuse);
       return client_context_pool.contexts[CLIENT_CONTEXT_MAGIC_MASK(index)].ctx;
    }
    return NULL;
 }
mmal_vc_release()
MMAL_STATUS_T mmal_vc_release (void)
Definition at line 916 of file mmal_vc_client.c.
References MMAL_CLIENT_T::inited, MMAL_ENOTCONN, and status.
 {
    MMAL_STATUS_T status = MMAL_ENOTCONN;
    if(client.inited)
       status = mmal_vc_release_internal(&client);
    return status;
 }
mmal_vc_release_client_component()
void mmal_vc_release_client_component (MMAL_COMPONENT_T * component)
Definition at line 141 of file mmal_vc_client.c.
References MMAL_CLIENT_COMPONENT_T::component, MMAL_CLIENT_COMPONENT_POOL_T::components, MMAL_CLIENT_COMPONENT_T::inuse, MMAL_CLIENT_COMPONENT_POOL_T::lock, MAX_COMPONENT_HANDLES, NULL, vcos_mutex_lock(), and vcos_mutex_unlock().
 {
    int i;
    vcos_mutex_lock(&client_component_pool.lock);
    for (i=0; i<MAX_COMPONENT_HANDLES; i++)
    {
       if (client_component_pool.components[i].component == component)
       {
          client_component_pool.components[i].component = NULL;
          client_component_pool.components[i].inuse = 0;
       }
    }
    vcos_mutex_unlock(&client_component_pool.lock);
 }
mmal_vc_release_client_context()
void mmal_vc_release_client_context (MMAL_VC_CLIENT_BUFFER_CONTEXT_T * context)
Definition at line 211 of file mmal_vc_client.c.
 {
    int i;
    vcos_mutex_lock(&client_context_pool.lock);
    for (i=0; i<MAX_CLIENT_CONTEXTS; i++)
    {
       if (client_context_pool.contexts[i].ctx == context)
       {
          client_context_pool.contexts[i].ctx = NULL;
          client_context_pool.contexts[i].inuse = 0;
          break;
       }
    }
    if (i >= MAX_CLIENT_CONTEXTS)
       LOG_ERROR("Failed to release context %p - not found", context);
    vcos_mutex_unlock(&client_context_pool.lock);
 }
mmal_vc_send_message()
MMAL_STATUS_T mmal_vc_send_message (MMAL_CLIENT_T * client, mmal_worker_msg_header * msg_header, size_t size, uint8_t * data, size_t data_size, uint32_t msgid)
Send a message and do not wait for a reply.
Note
This function should only be called from within a mmal component, so vchiq_use/release_service calls aren't required (dealt with at higher level).
Parameters
client client to send message for
msg_header message header to send
size length of message, including header
msgid message id
Definition at line 848 of file mmal_vc_client.c.
References MMAL_CLIENT_T::bulk_lock, error(), MMAL_CLIENT_T::inited, LOG_ERROR, LOG_TRACE, mmal_worker_msg_header::magic, MMAL_EINVAL, MMAL_EIO, MMAL_MAGIC, MMAL_SUCCESS, mmal_worker_msg_header::msgid, MMAL_CLIENT_T::service, vchiq_queue_bulk_transmit(), vchiq_queue_message(), VCHIQ_SUCCESS, vcos_assert, vcos_mutex_lock(), vcos_mutex_unlock(), and vcos_verify.
 {
    VCHIQ_STATUS_T vst;
    VCHIQ_ELEMENT_T elems[] = {{msg_header, size}};
    MMAL_BOOL_T using_bulk_transfer = (data_size != 0);
    LOG_TRACE("len %zu", data_size);
    vcos_assert(size >= sizeof(mmal_worker_msg_header));
    if (!client->inited)
    {
       vcos_assert(0);
       return MMAL_EINVAL;
    }
    if (using_bulk_transfer)
       vcos_mutex_lock(&client->bulk_lock);
    msg_header->msgid  = msgid;
    msg_header->magic  = MMAL_MAGIC;
    vst = vchiq_queue_message(client->service, elems, 1);
    if (vst != VCHIQ_SUCCESS)
    {
       if (using_bulk_transfer)
          vcos_mutex_unlock(&client->bulk_lock);
       LOG_ERROR("failed");
       goto error;
    }
    if (using_bulk_transfer)
    {
       LOG_TRACE("bulk transmit: %p, %zu", data, data_size);
       data_size = (data_size + 3) & ~3;
       vst = vchiq_queue_bulk_transmit(client->service, data, data_size, msg_header);
       vcos_mutex_unlock(&client->bulk_lock);
       if (!vcos_verify(vst == VCHIQ_SUCCESS))
       {
          LOG_ERROR("failed bulk transmit");
          /* This really should not happen and if it does, things will go wrong as
           * we've already queued the vchiq message above. */
          vcos_assert(0);
          goto error;
       }
    }
    return MMAL_SUCCESS;
  error:
    return MMAL_EIO;
 }
mmal_vc_sendwait_message()
MMAL_STATUS_T mmal_vc_sendwait_message (struct MMAL_CLIENT_T * client, mmal_worker_msg_header * msg_header, size_t size, uint32_t msgid, void * dest, size_t * destlen, MMAL_BOOL_T send_dummy_bulk)
Send a message and wait for a reply.
Parameters
client client to send message for
msg_header message vchiq_header to send
size length of message, including header
msgid message id
dest destination for reply
destlen size of destination, updated with actual length
send_dummy_bulk whether to send a dummy bulk transfer
Definition at line 750 of file mmal_vc_client.c.
References MMAL_CLIENT_T::bulk_lock, MMAL_CLIENT_T::inited, MMAL_EINVAL, vcos_assert, and vcos_mutex_lock().
Referenced by mmal_vc_compact(), mmal_vc_consume_mem(), mmal_vc_drm_get_lhs32(), mmal_vc_drm_get_time(), mmal_vc_get_core_stats(), mmal_vc_get_stats(), mmal_vc_get_version(), mmal_vc_host_log(), mmal_vc_lmk(), mmal_vc_opaque_acquire(), mmal_vc_opaque_alloc_desc(), and mmal_vc_opaque_release().
 {
    MMAL_STATUS_T ret;
    MMAL_WAITER_T *waiter;
    VCHIQ_STATUS_T vst;
    VCHIQ_ELEMENT_T elems[] = {{msg_header, size}};
    vcos_assert(size >= sizeof(mmal_worker_msg_header));
    vcos_assert(dest);
    if (!client->inited)
    {
       vcos_assert(0);
       return MMAL_EINVAL;
    }
    if (send_dummy_bulk)
       vcos_mutex_lock(&client->bulk_lock);
    waiter = get_waiter(client);
    msg_header->msgid  = msgid;
    msg_header->u.waiter = waiter->index;
    msg_header->magic  = MMAL_MAGIC;
    waiter->dest    = dest;
    waiter->destlen = *destlen;
    LOG_TRACE("wait %p, reply to %p", waiter, dest);
    mmal_vc_use_internal(client);
    vst = vchiq_queue_message(client->service, elems, 1);
    if (vst != VCHIQ_SUCCESS)
    {
       ret = MMAL_EIO;
       if (send_dummy_bulk)
         vcos_mutex_unlock(&client->bulk_lock);
       goto fail_msg;
    }
    if (send_dummy_bulk)
    {
       uint32_t data_size = 8;
       /* The data is just some dummy bytes so it's fine for it to be static */
       static uint8_t data[8];
       vst = vchiq_queue_bulk_transmit(client->service, data, data_size, msg_header);
       vcos_mutex_unlock(&client->bulk_lock);
       if (!vcos_verify(vst == VCHIQ_SUCCESS))
       {
          LOG_ERROR("failed bulk transmit");
          /* This really should not happen and if it does, things will go wrong as
           * we've already queued the vchiq message above. */
          vcos_assert(0);
          ret = MMAL_EIO;
          goto fail_msg;
       }
    }
    /* now wait for the reply...
     *
     * FIXME: we could do with a timeout here. Need to be careful to cancel
     * the semaphore on a timeout.
     */
    /* coverity[lock] This semaphore isn't being used as a mutex */
    vcos_semaphore_wait(&waiter->sem);
    mmal_vc_release_internal(client);
    LOG_TRACE("got reply (len %i/%i)", (int)*destlen, (int)waiter->destlen);
    *destlen = waiter->destlen;
    release_waiter(client, waiter);
    return MMAL_SUCCESS;
 fail_msg:
    mmal_vc_release_internal(client);
    release_waiter(client, waiter);
    return ret;
 }
mmal_vc_use()
MMAL_STATUS_T mmal_vc_use (void)
Definition at line 908 of file mmal_vc_client.c.
References MMAL_CLIENT_T::inited, MMAL_ENOTCONN, and status.
 {
    MMAL_STATUS_T status = MMAL_ENOTCONN;
    if(client.inited)
       status = mmal_vc_use_internal(&client);
    return status;
 }