VideoCore Library: interface/vcos/glibc/vcos_backtrace.c File Reference
vcos_backtrace.c File Reference
#include <interface/vcos/vcos.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
Functions
void vcos_backtrace_self (void)
Function Documentation
vcos_backtrace_self()
void vcos_backtrace_self (void)
Print out a backtrace, on supported platforms.
Definition at line 39 of file vcos_backtrace.c.
Referenced by vcos_abort(), vcos_pthreads_logging_assert(), and vcos_thread_get_name().
 {
 #ifdef HAVE_EXECINFO_H
    void *stack[64];
    int depth = backtrace(stack, sizeof(stack)/sizeof(stack[0]));
    char **names = backtrace_symbols(stack, depth);
    int i;
    if (names)
    {
       for (i=0; i<depth; i++)
       {
          printf("%s\n", names[i]);
       }
       free(names);
    }
 #endif
 }