VideoCore Library: interface/khronos/common/khrn_int_util.h File Reference
khrn_int_util.h File Reference
#include <ctype.h>
#include <float.h>
#include <math.h>
#include "interface/khronos/common/khrn_int_common.h"
#include "interface/vcos/vcos.h"
#include "interface/khronos/common/khrn_int_util_cr.h"
Classes
union KHRN_FLOAT_BITS_T
Macros
#define ARR_COUNT(ARR) (sizeof(ARR) / sizeof(*(ARR)))
#define alignof(T) (sizeof(struct { T t; char ch; }) - sizeof(T))
#define KHRN_INT_UTIL_H
#define ARR_COUNT(ARR) (sizeof(ARR) / sizeof(*(ARR)))
#define alignof(T) (sizeof(struct { T t; char ch; }) - sizeof(T))
Functions
int khrn_get_type_size (int type)
void khrn_clip_range (int32_t *x0, int32_t *l0, int32_t x1, int32_t l1)
void khrn_clip_range2 (int32_t *ax0, int32_t *bx0, int32_t *l0, int32_t ax1, int32_t al1, int32_t bx1, int32_t bl1)
void khrn_clip_rect (int32_t *x0, int32_t *y0, int32_t *w0, int32_t *h0, int32_t x1, int32_t y1, int32_t w1, int32_t h1)
void khrn_clip_rect2 (int32_t *ax0, int32_t *ay0, int32_t *bx0, int32_t *by0, int32_t *w0, int32_t *h0, int32_t ax1, int32_t ay1, int32_t aw1, int32_t ah1, int32_t bx1, int32_t by1, int32_t bw1, int32_t bh1)
Macro Definition Documentation
alignof [1/2]
#define alignof (T) (sizeof(struct { T t; char ch; }) - sizeof(T))
Definition at line 438 of file khrn_misc.h.
alignof [2/2]
#define alignof (T) (sizeof(struct { T t; char ch; }) - sizeof(T))
ARR_COUNT [1/2]
#define ARR_COUNT (ARR) (sizeof(ARR) / sizeof(*(ARR)))
ARR_COUNT [2/2]
#define ARR_COUNT (ARR) (sizeof(ARR) / sizeof(*(ARR)))
Definition at line 182 of file khrn_misc.h.
Referenced by egl_config_install_configs().
KHRN_INT_UTIL_H
#define KHRN_INT_UTIL_H
Definition at line 30 of file khrn_misc.h.
Function Documentation
khrn_clip_range()
void khrn_clip_range (int32_t * x0, int32_t * l0, int32_t x1, int32_t l1)
Definition at line 35 of file khrn_int_util.c.
References vcos_assert.
Referenced by khrn_clip_rect().
 {
    int32_t min_x0;
    int32_t l0;
    int32_t max_x0;
    int32_t max_x1;
    vcos_assert((*l0_io >= 0) && (l1 >= 0));
    min_x0 = *min_x0_io;
    l0 = *l0_io;
    max_x0 = _adds(min_x0, l0);
    max_x1 = min_x1 + l1;
    if (min_x0 < min_x1) {
       min_x0 = min_x1;
    }
    if (max_x0 > max_x1) {
       max_x0 = max_x1;
    }
    l0 = _max(_subs(max_x0, min_x0), 0);
    *min_x0_io = (l0 == 0) ? min_x1 : min_x0;
    *l0_io = l0;
 }
khrn_clip_range2()
void khrn_clip_range2 (int32_t * ax0, int32_t * bx0, int32_t * l0, int32_t ax1, int32_t al1, int32_t bx1, int32_t bl1)
Definition at line 65 of file khrn_int_util.c.
References vcos_assert.
Referenced by khrn_clip_rect2().
 {
    int32_t min_ax0;
    int32_t min_bx0;
    int32_t l0;
    int32_t max_ax0;
    int32_t max_bx0;
    int32_t max_ax1;
    int32_t max_bx1;
    vcos_assert((*l0_io >= 0) && (al1 >= 0) && (bl1 >= 0));
    min_ax0 = *min_ax0_io;
    min_bx0 = *min_bx0_io;
    l0 = *l0_io;
    l0 = _adds(_max(min_ax0, min_bx0), l0) - _max(min_ax0, min_bx0); /* clamp l0 to avoid overflow */
    max_ax0 = min_ax0 + l0;
    max_bx0 = min_bx0 + l0;
    max_ax1 = min_ax1 + al1;
    max_bx1 = min_bx1 + bl1;
    /*
       if any of the following _adds/_subs overflow, we will get either
       min_ax0 >= max_ax0 or min_bx0 >= max_bx0, so l0 will be 0
    */
    if (min_ax0 < min_ax1) {
       min_bx0 = _adds(min_bx0, _subs(min_ax1, min_ax0));
       min_ax0 = min_ax1;
    }
    if (max_ax0 > max_ax1) {
       max_bx0 = _subs(max_bx0, _subs(max_ax0, max_ax1));
       max_ax0 = max_ax1;
    }
    if (min_bx0 < min_bx1) {
       min_ax0 = _adds(min_ax0, _subs(min_bx1, min_bx0));
       min_bx0 = min_bx1;
    }
    if (max_bx0 > max_bx1) {
       max_ax0 = _subs(max_ax0, _subs(max_bx0, max_bx1));
       max_bx0 = max_bx1;
    }
    l0 = _max(_subs(max_ax0, min_ax0), 0);
    vcos_assert(l0 == _max(_subs(max_bx0, min_bx0), 0));
    *min_ax0_io = (l0 == 0) ? min_ax1 : min_ax0;
    *min_bx0_io = (l0 == 0) ? min_bx1 : min_bx0;
    *l0_io = l0;
 }
khrn_clip_rect()
void khrn_clip_rect (int32_t * x0, int32_t * y0, int32_t * w0, int32_t * h0, int32_t x1, int32_t y1, int32_t w1, int32_t h1)
Definition at line 121 of file khrn_int_util.c.
References khrn_clip_range().
 {
    khrn_clip_range(x0, w0, x1, w1);
    khrn_clip_range(y0, h0, y1, h1);
 }
khrn_clip_rect2()
void khrn_clip_rect2 (int32_t * ax0, int32_t * ay0, int32_t * bx0, int32_t * by0, int32_t * w0, int32_t * h0, int32_t ax1, int32_t ay1, int32_t aw1, int32_t ah1, int32_t bx1, int32_t by1, int32_t bw1, int32_t bh1)
Definition at line 129 of file khrn_int_util.c.
References khrn_clip_range2().
 {
    khrn_clip_range2(ax0, bx0, w0, ax1, aw1, bx1, bw1);
    khrn_clip_range2(ay0, by0, h0, ay1, ah1, by1, bh1);
 }
khrn_get_type_size()
int khrn_get_type_size (int type)
Definition at line 138 of file khrn_int_util.c.
References GL_BYTE, GL_FIXED, GL_FLOAT, GL_HALF_FLOAT_OES, GL_SHORT, GL_UNSIGNED_BYTE, GL_UNSIGNED_SHORT, and UNREACHABLE.
 {
    switch ((GLenum)type) {
    case GL_BYTE:
    case GL_UNSIGNED_BYTE:
       return 1;
    case GL_SHORT:
    case GL_UNSIGNED_SHORT:
    case GL_HALF_FLOAT_OES:
       return 2;
    case GL_FIXED:
    case GL_FLOAT:
       return 4;
    default:
       UNREACHABLE();
       return 0;
    }
 }