VideoCore Library: interface/khronos/vg/vg_int_mat3x3.h File Reference
vg_int_mat3x3.h File Reference
Classes
struct VG_MAT3X3_T
Functions
void vg_mat3x3_set_identity (VG_MAT3X3_T *a)
void vg_mat3x3_set_clean (VG_MAT3X3_T *a, const float *matrix, bool force_affine)
void vg_mat3x3_get (const VG_MAT3X3_T *a, float *matrix)
bool vg_mat3x3_identical (const VG_MAT3X3_T *a, const VG_MAT3X3_T *b)
void vg_mat3x3_mul (VG_MAT3X3_T *a, const VG_MAT3X3_T *b, const VG_MAT3X3_T *c)
void vg_mat3x3_postmul_translate (VG_MAT3X3_T *a, float x, float y)
void vg_mat3x3_postmul_scale (VG_MAT3X3_T *a, float x, float y)
void vg_mat3x3_postmul_shear (VG_MAT3X3_T *a, float x, float y)
void vg_mat3x3_postmul_rotate (VG_MAT3X3_T *a, float angle)
void vg_mat3x3_postmul_rotate_sc (VG_MAT3X3_T *a, float s, float c)
void vg_mat3x3_premul_translate (VG_MAT3X3_T *a, float x, float y)
void vg_mat3x3_premul_scale (VG_MAT3X3_T *a, float x, float y)
void vg_mat3x3_premul_shear (VG_MAT3X3_T *a, float x, float y)
void vg_mat3x3_premul_rotate (VG_MAT3X3_T *a, float angle)
void vg_mat3x3_premul_rotate_sc (VG_MAT3X3_T *a, float s, float c)
bool vg_mat3x3_is_affine (const VG_MAT3X3_T *a)
bool vg_mat3x3_is_affine_or_nans (const VG_MAT3X3_T *a)
float vg_mat3x3_det (const VG_MAT3X3_T *a)
float vg_mat3x3_affine_det (const VG_MAT3X3_T *a)
bool vg_mat3x3_is_invertible (const VG_MAT3X3_T *a)
bool vg_mat3x3_affine_is_invertible (const VG_MAT3X3_T *a)
void vg_mat3x3_invert (VG_MAT3X3_T *a)
void vg_mat3x3_affine_invert (VG_MAT3X3_T *a)
void vg_mat3x3_affine_transform (const VG_MAT3X3_T *a, float *x, float *y)
void vg_mat3x3_affine_transform_t (const VG_MAT3X3_T *a, float *x, float *y)
void vg_mat3x3_rsq (const VG_MAT3X3_T *a, float *r, float *s0, float *s1)
Function Documentation
vg_mat3x3_affine_det()
float vg_mat3x3_affine_det (const VG_MAT3X3_T * a)
Definition at line 421 of file vg_int_mat3x3.c.
References VG_MAT3X3_T::m, vcos_assert, and vg_mat3x3_is_affine_or_nans().
 {
    vcos_assert(vg_mat3x3_is_affine_or_nans(a));
    return (a->m[0][0] * a->m[1][1]) - (a->m[1][0] * a->m[0][1]);
 }
vg_mat3x3_affine_invert()
void vg_mat3x3_affine_invert (VG_MAT3X3_T * a)
Definition at line 504 of file vg_int_mat3x3.c.
References vcos_assert, and vg_mat3x3_affine_is_invertible().
 {
    float oo_det;
    float m00, m01, m02, m10;
    vcos_assert(vg_mat3x3_affine_is_invertible(a));
    oo_det = recip_(vg_mat3x3_affine_det(a));
    m00 = a->m[0][0];
    m01 = a->m[0][1];
    m02 = a->m[0][2];
    m10 = a->m[1][0];
    a->m[0][0] = a->m[1][1] * oo_det;
    a->m[0][1] = -m01 * oo_det;
    a->m[0][2] = ((a->m[1][2] * m01) - (a->m[1][1] * m02)) * oo_det;
    a->m[1][0] = -m10 * oo_det;
    a->m[1][1] = m00 * oo_det;
    a->m[1][2] = ((m10 * m02) - (a->m[1][2] * m00)) * oo_det;
    a->m[2][0] = 0.0f;
    a->m[2][1] = 0.0f;
    a->m[2][2] = 1.0f;
 }
vg_mat3x3_affine_is_invertible()
bool vg_mat3x3_affine_is_invertible (const VG_MAT3X3_T * a)
Definition at line 454 of file vg_int_mat3x3.c.
Referenced by vg_mat3x3_affine_invert().
 {
    return absf_(vg_mat3x3_affine_det(a)) >= EPS;
 }
vg_mat3x3_affine_transform()
void vg_mat3x3_affine_transform (const VG_MAT3X3_T * a, float * x, float * y)
Definition at line 540 of file vg_int_mat3x3.c.
References VG_MAT3X3_T::m.
 {
    float x = (a->m[0][0] * *x_io) + (a->m[0][1] * *y_io) + a->m[0][2];
    float y = (a->m[1][0] * *x_io) + (a->m[1][1] * *y_io) + a->m[1][2];
    *x_io = x;
    *y_io = y;
 }
vg_mat3x3_affine_transform_t()
void vg_mat3x3_affine_transform_t (const VG_MAT3X3_T * a, float * x, float * y)
Definition at line 558 of file vg_int_mat3x3.c.
References VG_MAT3X3_T::m.
 {
    float x = (a->m[0][0] * *x_io) + (a->m[0][1] * *y_io);
    float y = (a->m[1][0] * *x_io) + (a->m[1][1] * *y_io);
    *x_io = x;
    *y_io = y;
 }
vg_mat3x3_det()
float vg_mat3x3_det (const VG_MAT3X3_T * a)
Definition at line 404 of file vg_int_mat3x3.c.
References VG_MAT3X3_T::m.
 {
    return (a->m[0][0] * ((a->m[2][2] * a->m[1][1]) - (a->m[2][1] * a->m[1][2]))) +
           (a->m[1][0] * ((a->m[0][2] * a->m[2][1]) - (a->m[0][1] * a->m[2][2]))) +
           (a->m[2][0] * ((a->m[1][2] * a->m[0][1]) - (a->m[1][1] * a->m[0][2])));
 }
vg_mat3x3_get()
void vg_mat3x3_get (const VG_MAT3X3_T * a, float * matrix)
Definition at line 96 of file vg_int_mat3x3.c.
References VG_MAT3X3_T::m.
 {
    matrix[0] = a->m[0][0];
    matrix[3] = a->m[0][1];
    matrix[6] = a->m[0][2];
    matrix[1] = a->m[1][0];
    matrix[4] = a->m[1][1];
    matrix[7] = a->m[1][2];
    matrix[2] = a->m[2][0];
    matrix[5] = a->m[2][1];
    matrix[8] = a->m[2][2];
 }
vg_mat3x3_identical()
bool vg_mat3x3_identical (const VG_MAT3X3_T * a, const VG_MAT3X3_T * b)
Definition at line 121 of file vg_int_mat3x3.c.
 {
    return floats_identical(a->m[0][0], b->m[0][0]) && floats_identical(a->m[0][1], b->m[0][1]) && floats_identical(a->m[0][2], b->m[0][2]) &&
           floats_identical(a->m[1][0], b->m[1][0]) && floats_identical(a->m[1][1], b->m[1][1]) && floats_identical(a->m[1][2], b->m[1][2]) &&
           floats_identical(a->m[2][0], b->m[2][0]) && floats_identical(a->m[2][1], b->m[2][1]) && floats_identical(a->m[2][2], b->m[2][2]);
 }
vg_mat3x3_invert()
void vg_mat3x3_invert (VG_MAT3X3_T * a)
Definition at line 469 of file vg_int_mat3x3.c.
References vcos_assert, and vg_mat3x3_is_invertible().
 {
    float oo_det;
    VG_MAT3X3_T b;
    vcos_assert(vg_mat3x3_is_invertible(a));
    oo_det = recip_(vg_mat3x3_det(a));
    b.m[0][0] = ((a->m[2][2] * a->m[1][1]) - (a->m[2][1] * a->m[1][2])) * oo_det;
    b.m[0][1] = ((a->m[0][2] * a->m[2][1]) - (a->m[0][1] * a->m[2][2])) * oo_det;
    b.m[0][2] = ((a->m[1][2] * a->m[0][1]) - (a->m[1][1] * a->m[0][2])) * oo_det;
    b.m[1][0] = ((a->m[2][0] * a->m[1][2]) - (a->m[2][2] * a->m[1][0])) * oo_det;
    b.m[1][1] = ((a->m[0][0] * a->m[2][2]) - (a->m[0][2] * a->m[2][0])) * oo_det;
    b.m[1][2] = ((a->m[1][0] * a->m[0][2]) - (a->m[1][2] * a->m[0][0])) * oo_det;
    b.m[2][0] = ((a->m[2][1] * a->m[1][0]) - (a->m[2][0] * a->m[1][1])) * oo_det;
    b.m[2][1] = ((a->m[0][1] * a->m[2][0]) - (a->m[0][0] * a->m[2][1])) * oo_det;
    b.m[2][2] = ((a->m[1][1] * a->m[0][0]) - (a->m[1][0] * a->m[0][1])) * oo_det;
    *a = b;
 }
vg_mat3x3_is_affine()
bool vg_mat3x3_is_affine (const VG_MAT3X3_T * a)
Definition at line 374 of file vg_int_mat3x3.c.
References VG_MAT3X3_T::m.
 {
    return (a->m[2][0] == 0.0f) && (a->m[2][1] == 0.0f) && (a->m[2][2] == 1.0f);
 }
vg_mat3x3_is_affine_or_nans()
bool vg_mat3x3_is_affine_or_nans (const VG_MAT3X3_T * a)
Definition at line 389 of file vg_int_mat3x3.c.
Referenced by vg_mat3x3_affine_det().
 {
    return !nan_ne_(a->m[2][0], 0.0f) && !nan_ne_(a->m[2][1], 0.0f) && !nan_ne_(a->m[2][2], 1.0f);
 }
vg_mat3x3_is_invertible()
bool vg_mat3x3_is_invertible (const VG_MAT3X3_T * a)
Definition at line 438 of file vg_int_mat3x3.c.
Referenced by vg_mat3x3_invert().
 {
    return absf_(vg_mat3x3_det(a)) >= EPS;
 }
vg_mat3x3_mul()
void vg_mat3x3_mul (VG_MAT3X3_T * a, const VG_MAT3X3_T * b, const VG_MAT3X3_T * c)
Definition at line 138 of file vg_int_mat3x3.c.
References VG_MAT3X3_T::m.
 {
    uint32_t j, i;
    for (j = 0; j != 3; ++j) {
       for (i = 0; i != 3; ++i) {
          a->m[j][i] =
             (b->m[j][0] * c->m[0][i]) +
             (b->m[j][1] * c->m[1][i]) +
             (b->m[j][2] * c->m[2][i]);
       }
    }
 }
vg_mat3x3_postmul_rotate()
void vg_mat3x3_postmul_rotate (VG_MAT3X3_T * a, float angle)
Definition at line 224 of file vg_int_mat3x3.c.
 {
    float s, c;
    sin_cos_(&s, &c, angle);
    vg_mat3x3_postmul_rotate_sc(a, s, c);
 }
vg_mat3x3_postmul_rotate_sc()
void vg_mat3x3_postmul_rotate_sc (VG_MAT3X3_T * a, float s, float c)
Definition at line 243 of file vg_int_mat3x3.c.
References VG_MAT3X3_T::m.
 {
    float m00 = a->m[0][0], m10 = a->m[1][0], m20 = a->m[2][0];
    a->m[0][0] = (m00 * c) + (a->m[0][1] * s);
    a->m[0][1] = (a->m[0][1] * c) - (m00 * s);
    a->m[1][0] = (m10 * c) + (a->m[1][1] * s);
    a->m[1][1] = (a->m[1][1] * c) - (m10 * s);
    a->m[2][0] = (m20 * c) + (a->m[2][1] * s);
    a->m[2][1] = (a->m[2][1] * c) - (m20 * s);
 }
vg_mat3x3_postmul_scale()
void vg_mat3x3_postmul_scale (VG_MAT3X3_T * a, float x, float y)
Definition at line 178 of file vg_int_mat3x3.c.
References VG_MAT3X3_T::m.
 {
    a->m[0][0] *= x;
    a->m[0][1] *= y;
    a->m[1][0] *= x;
    a->m[1][1] *= y;
    a->m[2][0] *= x;
    a->m[2][1] *= y;
 }
vg_mat3x3_postmul_shear()
void vg_mat3x3_postmul_shear (VG_MAT3X3_T * a, float x, float y)
Definition at line 200 of file vg_int_mat3x3.c.
References VG_MAT3X3_T::m.
 {
    float m00 = a->m[0][0], m10 = a->m[1][0], m20 = a->m[2][0];
    a->m[0][0] += a->m[0][1] * y;
    a->m[0][1] += m00 * x;
    a->m[1][0] += a->m[1][1] * y;
    a->m[1][1] += m10 * x;
    a->m[2][0] += a->m[2][1] * y;
    a->m[2][1] += m20 * x;
 }
vg_mat3x3_postmul_translate()
void vg_mat3x3_postmul_translate (VG_MAT3X3_T * a, float x, float y)
Definition at line 161 of file vg_int_mat3x3.c.
References VG_MAT3X3_T::m.
 {
    a->m[0][2] += (a->m[0][0] * x) + (a->m[0][1] * y);
    a->m[1][2] += (a->m[1][0] * x) + (a->m[1][1] * y);
    a->m[2][2] += (a->m[2][0] * x) + (a->m[2][1] * y);
 }
vg_mat3x3_premul_rotate()
void vg_mat3x3_premul_rotate (VG_MAT3X3_T * a, float angle)
Definition at line 332 of file vg_int_mat3x3.c.
 {
    float s, c;
    sin_cos_(&s, &c, angle);
    vg_mat3x3_premul_rotate_sc(a, s, c);
 }
vg_mat3x3_premul_rotate_sc()
void vg_mat3x3_premul_rotate_sc (VG_MAT3X3_T * a, float s, float c)
Definition at line 351 of file vg_int_mat3x3.c.
References VG_MAT3X3_T::m.
 {
    float m00 = a->m[0][0], m01 = a->m[0][1], m02 = a->m[0][2];
    a->m[0][0] = (m00 * c) - (a->m[1][0] * s);
    a->m[0][1] = (m01 * c) - (a->m[1][1] * s);
    a->m[0][2] = (m02 * c) - (a->m[1][2] * s);
    a->m[1][0] = (m00 * s) + (a->m[1][0] * c);
    a->m[1][1] = (m01 * s) + (a->m[1][1] * c);
    a->m[1][2] = (m02 * s) + (a->m[1][2] * c);
 }
vg_mat3x3_premul_scale()
void vg_mat3x3_premul_scale (VG_MAT3X3_T * a, float x, float y)
Definition at line 288 of file vg_int_mat3x3.c.
References VG_MAT3X3_T::m.
 {
    a->m[0][0] *= x;
    a->m[0][1] *= x;
    a->m[0][2] *= x;
    a->m[1][0] *= y;
    a->m[1][1] *= y;
    a->m[1][2] *= y;
 }
vg_mat3x3_premul_shear()
void vg_mat3x3_premul_shear (VG_MAT3X3_T * a, float x, float y)
Definition at line 309 of file vg_int_mat3x3.c.
References VG_MAT3X3_T::m.
 {
    float m00 = a->m[0][0], m01 = a->m[0][1], m02 = a->m[0][2];
    a->m[0][0] += a->m[1][0] * x;
    a->m[0][1] += a->m[1][1] * x;
    a->m[0][2] += a->m[1][2] * x;
    a->m[1][0] += m00 * y;
    a->m[1][1] += m01 * y;
    a->m[1][2] += m02 * y;
 }
vg_mat3x3_premul_translate()
void vg_mat3x3_premul_translate (VG_MAT3X3_T * a, float x, float y)
Definition at line 267 of file vg_int_mat3x3.c.
References VG_MAT3X3_T::m.
 {
    a->m[0][0] += a->m[2][0] * x;
    a->m[0][1] += a->m[2][1] * x;
    a->m[0][2] += a->m[2][2] * x;
    a->m[1][0] += a->m[2][0] * y;
    a->m[1][1] += a->m[2][1] * y;
    a->m[1][2] += a->m[2][2] * y;
 }
vg_mat3x3_rsq()
void vg_mat3x3_rsq (const VG_MAT3X3_T * a, float * r, float * s0, float * s1)
Definition at line 586 of file vg_int_mat3x3.c.
References VG_MAT3X3_T::m.
 {
    /*
       a = R * S * Q (svd, R is rotation, S is scale, Q is rotation/flip)
       a^T = Q^T * S * R^T
       a * a^T = R * S * Q * Q^T * S * R^T = R * S^2 * R^T
       eigenvalues of a * a^T will give S^2
       eigenvectors of a * a^T will give R
    */
    /*
       ( b c ) = a * a^T
       ( d e )
    */
    float b = (a->m[0][0] * a->m[0][0]) + (a->m[0][1] * a->m[0][1]);
    float c = (a->m[0][0] * a->m[1][0]) + (a->m[0][1] * a->m[1][1]);
    /* d = c */
    float e = (a->m[1][0] * a->m[1][0]) + (a->m[1][1] * a->m[1][1]);
    float bpe = b + e;
    float bme = b - e;
    /*
       solve:
       bx + cy = sx
       dx + ey = sy
       cy * dx = (s - b)x * (s - e)y
       c^2 = (s - b) * (s - e)
       s^2 - (b + e)s + (be - c^2) = 0
       s = (b + e +/- sqrt((b + e)^2 - 4(be - c^2))) / 2
       s = (b + e +/- sqrt(b^2 + e^2 - 2be + 4c^2)) / 2
       s = (b + e +/- sqrt((b - e)^2 + 4c^2)) / 2
    */
    float t = sqrt_((bme * bme) + (4.0f * c * c));
    float v = (bpe + t) * 0.5f; /* first eigenvalue */
    if (s0) {
       *s0 = sqrt_(v);
    }
    if (s1) {
       *s1 = sqrt_(
          /* second eigenvalue */
          _maxf(bpe - t, 0.0f) * 0.5f);
    }
    /*
       angle of eigenvector corresponds to r
    */
    if (r) {
       /* first eigenvector is (c, v - b) / (v - e, c) */
       float x = (v - e) + c;
       float y = (v - b) + c;
       *r = ((absf_(x) < EPS) && (absf_(y) < EPS)) ? 0.0f : atan2_(y, x);
    }
 }
vg_mat3x3_set_clean()
void vg_mat3x3_set_clean (VG_MAT3X3_T * a, const float * matrix, bool force_affine)
Definition at line 65 of file vg_int_mat3x3.c.
References VG_MAT3X3_T::m.
 {
    a->m[0][0] = clean_float(matrix[0]);
    a->m[0][1] = clean_float(matrix[3]);
    a->m[0][2] = clean_float(matrix[6]);
    a->m[1][0] = clean_float(matrix[1]);
    a->m[1][1] = clean_float(matrix[4]);
    a->m[1][2] = clean_float(matrix[7]);
    if (force_affine) {
       a->m[2][0] = 0.0f;
       a->m[2][1] = 0.0f;
       a->m[2][2] = 1.0f;
    } else {
       a->m[2][0] = clean_float(matrix[2]);
       a->m[2][1] = clean_float(matrix[5]);
       a->m[2][2] = clean_float(matrix[8]);
    }
 }
vg_mat3x3_set_identity()
void vg_mat3x3_set_identity (VG_MAT3X3_T * a)
Definition at line 43 of file vg_int_mat3x3.c.
References VG_MAT3X3_T::m.
 {
    a->m[0][0] = 1.0f;  a->m[0][1] = 0.0f;  a->m[0][2] = 0.0f;
    a->m[1][0] = 0.0f;  a->m[1][1] = 1.0f;  a->m[1][2] = 0.0f;
    a->m[2][0] = 0.0f;  a->m[2][1] = 0.0f;  a->m[2][2] = 1.0f;
 }