VideoCore Library: host_applications/linux/apps/hello_pi/libs/vgfont/vgfont.h File Reference
vgfont.h File Reference
#include <stdint.h>
#include "interface/vmcs_host/vc_dispservice_x_defs.h"
#include "interface/vctypes/vc_image_types.h"
#include "interface/vcos/vcos.h"
Macros
#define GRAPHICS_RESOURCE_WIDTH 0xFFFF
#define GRAPHICS_RESOURCE_HEIGHT 0xFFFF
#define R_888_MASK (0x00FF0000)
#define G_888_MASK (0x0000FF00)
#define B_888_MASK (0x000000FF)
#define ALPHA_888_MASK (0xFF000000)
#define GRAPHICS_RGBA32(r, g, b, a) GRAPHICS_RGBA888(r, g, b, a)
#define GRAPHICS_RGBA888(r, g, b, a) ((((a) << (8+8+8)) & ALPHA_888_MASK) | (((b) << (8+8)) & R_888_MASK) | (((g) << 8) & G_888_MASK) | ((r) & B_888_MASK))
#define GRAPHICS_TRANSPARENT_COLOUR 0x00000001UL
Typedefs
typedef struct GRAPHICS_RESOURCE_HANDLE_TABLE_T * GRAPHICS_RESOURCE_HANDLE
Enumerations
enum GRAPHICS_RESOURCE_TYPE_T {
GRAPHICS_RESOURCE_HANDLE_TYPE_MIN, GRAPHICS_RESOURCE_RGB565, GRAPHICS_RESOURCE_RGB888, GRAPHICS_RESOURCE_RGBA32,
GRAPHICS_RESOURCE_TF_RGB32A, GRAPHICS_RESOURCE_TF_RGB565, GRAPHICS_RESOURCE_YUV420, GRAPHICS_RESOURCE_HANDLE_TYPE_MAX
}
Functions
VCOS_STATUS_T gx_graphics_init (const char *font_dir)
int32_t graphics_delete_resource (GRAPHICS_RESOURCE_HANDLE res)
VCOS_STATUS_T gx_create_window (uint32_t screen_id, uint32_t width, uint32_t height, GRAPHICS_RESOURCE_TYPE_T image_type, GRAPHICS_RESOURCE_HANDLE *resource_handle)
int32_t graphics_display_resource (GRAPHICS_RESOURCE_HANDLE res, const uint16_t screen_number, const int16_t z_order, const uint16_t offset_x, const uint16_t offset_y, const uint16_t dest_width, const uint16_t dest_height, const VC_DISPMAN_TRANSFORM_T transform, const uint8_t display)
int32_t graphics_resource_fill (GRAPHICS_RESOURCE_HANDLE res, uint32_t x, uint32_t y, uint32_t width, uint32_t height, uint32_t fill_colour)
int32_t graphics_update_displayed_resource (GRAPHICS_RESOURCE_HANDLE res, const uint32_t x_offset, const uint32_t y_offset, const uint32_t width, const uint32_t height)
int32_t graphics_resource_render_text_ext (GRAPHICS_RESOURCE_HANDLE res, const int32_t x, const int32_t y, const uint32_t width, const uint32_t height, const uint32_t fg_colour, const uint32_t bg_colour, const char *text, const uint32_t text_length, const uint32_t text_size)
int32_t graphics_resource_text_dimensions_ext (GRAPHICS_RESOURCE_HANDLE res, const char *text, const uint32_t text_length, uint32_t *width, uint32_t *height, const uint32_t text_size)
int32_t graphics_get_resource_size (const GRAPHICS_RESOURCE_HANDLE res, uint32_t *w, uint32_t *h)
int32_t graphics_update_start (void)
int32_t graphics_update_end (void)
int32_t graphics_resource_text_dimensions (GRAPHICS_RESOURCE_HANDLE resource_handle, const char *text, const uint32_t text_length, uint32_t *width, uint32_t *height)
Macro Definition Documentation
ALPHA_888_MASK
#define ALPHA_888_MASK (0xFF000000)
Definition at line 46 of file vgfont.h.
Referenced by gx_priv_colour_to_paint().
B_888_MASK
#define B_888_MASK (0x000000FF)
Definition at line 45 of file vgfont.h.
Referenced by gx_priv_colour_to_paint().
G_888_MASK
#define G_888_MASK (0x0000FF00)
Definition at line 44 of file vgfont.h.
Referenced by gx_priv_colour_to_paint().
GRAPHICS_RESOURCE_HEIGHT
#define GRAPHICS_RESOURCE_HEIGHT 0xFFFF
Definition at line 41 of file vgfont.h.
Referenced by graphics_bitblt(), gx_fill_gradient(), and main().
GRAPHICS_RESOURCE_WIDTH
#define GRAPHICS_RESOURCE_WIDTH 0xFFFF
Definition at line 40 of file vgfont.h.
Referenced by graphics_bitblt(), gx_fill_gradient(), and main().
GRAPHICS_RGBA32
#define GRAPHICS_RGBA32 (r, g, b, a) GRAPHICS_RGBA888(r, g, b, a)
Definition at line 47 of file vgfont.h.
Referenced by main().
GRAPHICS_RGBA888
#define GRAPHICS_RGBA888 (r, g, b, a) ((((a) << (8+8+8)) & ALPHA_888_MASK) | (((b) << (8+8)) & R_888_MASK) | (((g) << 8) & G_888_MASK) | ((r) & B_888_MASK))
Definition at line 48 of file vgfont.h.
GRAPHICS_TRANSPARENT_COLOUR
#define GRAPHICS_TRANSPARENT_COLOUR 0x00000001UL
Definition at line 49 of file vgfont.h.
R_888_MASK
#define R_888_MASK (0x00FF0000)
Definition at line 43 of file vgfont.h.
Referenced by gx_priv_colour_to_paint().
Typedef Documentation
GRAPHICS_RESOURCE_HANDLE
typedef struct GRAPHICS_RESOURCE_HANDLE_TABLE_T* GRAPHICS_RESOURCE_HANDLE
Definition at line 70 of file vgfont.h.
Enumeration Type Documentation
GRAPHICS_RESOURCE_TYPE_T
enum GRAPHICS_RESOURCE_TYPE_T
Enumerator
GRAPHICS_RESOURCE_HANDLE_TYPE_MIN
GRAPHICS_RESOURCE_RGB565
GRAPHICS_RESOURCE_RGB888
GRAPHICS_RESOURCE_RGBA32
GRAPHICS_RESOURCE_TF_RGB32A
GRAPHICS_RESOURCE_TF_RGB565
GRAPHICS_RESOURCE_YUV420
GRAPHICS_RESOURCE_HANDLE_TYPE_MAX
Definition at line 53 of file vgfont.h.
 {
    GRAPHICS_RESOURCE_HANDLE_TYPE_MIN,
    GRAPHICS_RESOURCE_RGB565,
    GRAPHICS_RESOURCE_RGB888, /*  888 format is ONLY used when loading bitmaps
                                  - you can't create or delete bitmaps with this format */
    GRAPHICS_RESOURCE_RGBA32,
    GRAPHICS_RESOURCE_TF_RGB32A,
    GRAPHICS_RESOURCE_TF_RGB565,
    GRAPHICS_RESOURCE_YUV420,
    GRAPHICS_RESOURCE_HANDLE_TYPE_MAX
 } GRAPHICS_RESOURCE_TYPE_T;
Function Documentation
graphics_delete_resource()
int32_t graphics_delete_resource (GRAPHICS_RESOURCE_HANDLE res)
Definition at line 394 of file graphics.c.
References GX_DISPLAY_T::disp, eglDestroySurface(), eglWaitClient(), GX_PBUFFER, gx_priv_destroy_native_window(), gx_priv_restore(), gx_priv_save(), GX_TRACE, GX_WINDOW, GRAPHICS_RESOURCE_HANDLE_TABLE_T::magic, GRAPHICS_RESOURCE_HANDLE_TABLE_T::pixmap, RES_MAGIC, GRAPHICS_RESOURCE_HANDLE_TABLE_T::surface, GRAPHICS_RESOURCE_HANDLE_TABLE_T::type, GRAPHICS_RESOURCE_HANDLE_TABLE_T::u, vcos_assert, vcos_free(), vgDestroyImage(), and vgGetError().
Referenced by main().
 {
    EGLBoolean result;
    if (!res)
    {
       // let it slide - mimics old behaviour
       return 0;
    }
    GX_TRACE("delete resource @%p", res);
    vcos_assert(res->magic == RES_MAGIC);
    if (res->type == GX_PBUFFER)
    {
       GX_CLIENT_STATE_T save;
       gx_priv_save(&save, res);
       vgDestroyImage(res->u.pixmap);
       vcos_assert(vgGetError() == 0);
       gx_priv_restore(&save);
    }
    GX_TRACE("graphics_delete_resource: calling eglDestroySurface...");
    result = eglDestroySurface(display.disp, res->surface);
    vcos_assert(result);
    GX_TRACE("graphics_delete_resource: calling eglWaitClient...");
    eglWaitClient(); // wait for EGL to finish sorting out its surfaces
    if (res->type == GX_WINDOW)
    {
       GX_TRACE("graphics_delete_resource: calling gx_priv_destroy_native_window...");
       gx_priv_destroy_native_window(res);
    }
    res->magic = ~RES_MAGIC;
    vcos_free(res);
    GX_TRACE("graphics_delete_resource: done");
    return 0;
 }
graphics_display_resource()
int32_t graphics_display_resource (GRAPHICS_RESOURCE_HANDLE res, const uint16_t screen_number, const int16_t z_order, const uint16_t offset_x, const uint16_t offset_y, const uint16_t dest_width, const uint16_t dest_height, const VC_DISPMAN_TRANSFORM_T transform, const uint8_t display)
Definition at line 1431 of file graphics.c.
References CHANGE_LAYER, gx_priv_state_t::current_update, graphics_update_start(), GRAPHICS_RESOURCE_HANDLE_TABLE_T::height, GRAPHICS_RESOURCE_HANDLE_TABLE_T::magic, RES_MAGIC, GRAPHICS_RESOURCE_HANDLE_TABLE_T::transform, vcos_assert, vcos_verify, void(), and GRAPHICS_RESOURCE_HANDLE_TABLE_T::width.
Referenced by main().
 {
    DISPMANX_UPDATE_HANDLE_T update;
    int32_t rc;
    int xform_changed;
    if (!res)
    {
       // mimics old behaviour.
       (void)vcos_verify(0);
       return 0;
    }
    vcos_assert(res->magic == RES_MAGIC);
    xform_changed = transform != res->transform;
    res->transform = transform;
    rc = graphics_update_start();
    update = gx.current_update;
    vcos_assert(rc == 0);
    if (display)
    {
       VC_RECT_T src_rect, dest_rect;
       int32_t src_width = res->width;
       int32_t src_height = res->height;
       uint32_t change_flags = CHANGE_LAYER;
       // has the destination position changed?
       uint32_t w = auto_size(dest_width, res->width);
       uint32_t h = auto_size(dest_height, res->height);
       vcos_assert(screen_number == res->screen_id);
       if (gx.screens[screen_number] == 0)
       {
          vcos_assert(0);
          DISPMANX_DISPLAY_HANDLE_T display_handle;
          gx_priv_open_screen(screen_number, &display_handle);
       }
       if ((offset_x != res->dest.x) ||
           (offset_y != res->dest.y) ||
           (h != res->dest.height) ||
           (w != res->dest.width))
       {
          change_flags |= CHANGE_DEST;
          res->dest.x      = offset_x;
          res->dest.y      = offset_y;
          res->dest.height = h;
          res->dest.width  = w;
       }
       if (xform_changed)
          change_flags |= CHANGE_XFORM;
       vc_dispmanx_rect_set( &src_rect, 0, 0, ((uint32_t)src_width)<<16, ((uint32_t)src_height)<<16 );
       vc_dispmanx_rect_set( &dest_rect, offset_x, offset_y, w, h);
       rc = vc_dispmanx_element_change_attributes(update,
          res->u.native_window.egl_win.element,
          change_flags,
          z_order, /* layer */
          0xff, /* opacity */
          &dest_rect,
          &src_rect,
          0, transform);
       vcos_assert(rc==0);
       gx_priv_flush(res);
    }
    else
    {
       vgFinish();
       eglWaitClient();
       rc = vc_dispmanx_element_change_source(update, res->u.native_window.egl_win.element, 0);
       vcos_assert(rc==0);
    }
    rc = graphics_update_end();
    vcos_assert(rc==0);
    return rc;
 }
graphics_get_resource_size()
int32_t graphics_get_resource_size (const GRAPHICS_RESOURCE_HANDLE res, uint32_t * w, uint32_t * h)
Definition at line 519 of file graphics.c.
References GRAPHICS_RESOURCE_HANDLE_TABLE_T::height, and GRAPHICS_RESOURCE_HANDLE_TABLE_T::width.
Referenced by gx_priv_get_pixels(), and render_subtitle().
 {
    if (w) *w = res->width;
    if (h) *h = res->height;
    return 0;
 }
graphics_resource_fill()
int32_t graphics_resource_fill (GRAPHICS_RESOURCE_HANDLE res, uint32_t x, uint32_t y, uint32_t width, uint32_t height, uint32_t fill_colour)
Definition at line 454 of file graphics.c.
References gx_priv_resource_fill(), gx_priv_restore(), gx_priv_save(), GRAPHICS_RESOURCE_HANDLE_TABLE_T::height, and VCOS_SUCCESS.
Referenced by main().
 {
    GX_CLIENT_STATE_T save;
    gx_priv_save(&save, res);
    VCOS_STATUS_T st = gx_priv_resource_fill(
       res,
       x, res->height-y-height,
       width, height,
       fill_colour);
    gx_priv_restore(&save);
    return st == VCOS_SUCCESS ? 0 : -1;
 }
graphics_resource_render_text_ext()
int32_t graphics_resource_render_text_ext (GRAPHICS_RESOURCE_HANDLE res, const int32_t x, const int32_t y, const uint32_t width, const uint32_t height, const uint32_t fg_colour, const uint32_t bg_colour, const char * text, const uint32_t text_length, const uint32_t text_size)
Definition at line 476 of file graphics.c.
References gx_priv_render_text(), GRAPHICS_RESOURCE_HANDLE_TABLE_T::height, and VCOS_SUCCESS.
Referenced by graphics_resource_render_text().
 {
    /*
    * FIXME: Not at all optimal - re-renders each time.
    * FIXME: Not UTF-8 safe
    * FIXME: much better caching (or any caching)
    */
    VCOS_STATUS_T rc = gx_priv_render_text(
       &display, res,
       x, res->height-y-text_size, width, height, fg_colour, bg_colour,
       text, text_length, text_size);
    return (rc == VCOS_SUCCESS) ? 0 : -1;
 }
graphics_resource_text_dimensions()
int32_t graphics_resource_text_dimensions (GRAPHICS_RESOURCE_HANDLE resource_handle, const char * text, const uint32_t text_length, uint32_t * width, uint32_t * height)
Definition at line 1051 of file graphics.c.
References ATEXT_FONT_SIZE, and graphics_resource_text_dimensions_ext().
 {
    return graphics_resource_text_dimensions_ext(resource_handle, text, text_length, width, height, ATEXT_FONT_SIZE);
 }
graphics_resource_text_dimensions_ext()
int32_t graphics_resource_text_dimensions_ext (GRAPHICS_RESOURCE_HANDLE res, const char * text, const uint32_t text_length, uint32_t * width, uint32_t * height, const uint32_t text_size)
Definition at line 328 of file font.c.
References gx_font_cache_entry_t::font, and gx_priv_save().
Referenced by graphics_resource_text_dimensions(), and render_subtitle().
 {
    GX_CLIENT_STATE_T save;
    VGfloat w, h;
    int ret = -1;
    gx_priv_save(&save, res);
    VGFT_FONT_T *font = find_font(text, text_size);
    if (!font)
       goto finish;
    vgft_get_text_extents(font, text, text_length, 0.0, 0.0, &w, &h);
    *width = w;
    *height = h;
    ret = 0;
 finish:
    gx_priv_restore(&save);
    return ret;
 }
graphics_update_displayed_resource()
int32_t graphics_update_displayed_resource (GRAPHICS_RESOURCE_HANDLE res, const uint32_t x_offset, const uint32_t y_offset, const uint32_t width, const uint32_t height)
Definition at line 437 of file graphics.c.
References gx_priv_flush(), gx_priv_restore(), and gx_priv_save().
Referenced by main().
 {
    GX_CLIENT_STATE_T save;
    gx_priv_save(&save, res);
    gx_priv_flush(res);
    gx_priv_restore(&save);
    return 0;
 }
graphics_update_end()
int32_t graphics_update_end (void)
Definition at line 1577 of file graphics.c.
References gx_priv_state_t::current_update, gx_priv_state_t::dispman_start_count, DISPMANX_NO_HANDLE, eglWaitClient(), vc_assert, vc_dispmanx_update_submit_sync(), and vcos_verify.
 {
    int32_t success = -1;
    // make sure you are checking the return value of graphics_update_start
    if(vcos_verify(gx.current_update != DISPMANX_NO_HANDLE))
    {
       //check we are in an update
       if(vcos_verify(gx.dispman_start_count > 0))
       {
          //dec the counter
          gx.dispman_start_count--;
          success = 0;
          //is the counter now 0?
          if( 0 == gx.dispman_start_count )
          {
             eglWaitClient();
             if( vc_dispmanx_update_submit_sync( gx.current_update ) != 0 )
             {
                //error
                success = -1;
                vc_assert( 0 );
             }
          }
       }
    }
    return success;
 }
graphics_update_start()
int32_t graphics_update_start (void)
Definition at line 1539 of file graphics.c.
References gx_priv_state_t::current_update, gx_priv_state_t::dispman_start_count, DISPMANX_NO_HANDLE, vc_assert, and vc_dispmanx_update_start().
Referenced by graphics_display_resource().
 {
    int32_t success = 0;
    //check we are not already in an update
    if ( 0 == gx.dispman_start_count )
    {
       gx.current_update = vc_dispmanx_update_start( 10 );
       if( gx.current_update == DISPMANX_NO_HANDLE )
       {
          //error
          success = -1;
          vc_assert( 0 );
       }
    }
    if( success == 0 )
    {
       //inc the counter
       gx.dispman_start_count++;
    }
    return success;
 }
gx_create_window()
VCOS_STATUS_T gx_create_window (uint32_t screen_id, uint32_t width, uint32_t height, GRAPHICS_RESOURCE_TYPE_T image_type, GRAPHICS_RESOURCE_HANDLE * resource_handle)
Definition at line 313 of file graphics.c.
References status, and VCOS_SUCCESS.
Referenced by main().
 {
    int rc;
    VCOS_STATUS_T status = VCOS_SUCCESS;
    GRAPHICS_RESOURCE_HANDLE h;
    EGLBoolean egl_result;
    void *cookie;
    GX_CLIENT_STATE_T save;
    if (!gx_contexts[image_type])
    {
       GX_LOG("Invalid image type %d", image_type);
       return VCOS_EINVAL;
    }
    h = vcos_calloc(1,sizeof(*h), "graphics_x_resource");
    if (!h)
    {
       GX_LOG("%s: no memory for resource", __FUNCTION__);
       return VCOS_ENOMEM;
    }
    // now need to get the native window
    rc = gx_priv_create_native_window(screen_id,
                                      width, height, image_type,
                                      &h->u.native_window,
                                      &cookie);
    if (rc < 0)
    {
       GX_LOG("%s: could not create native window", __FUNCTION__);
       status = VCOS_ENOMEM;
       goto fail_create_native_win;
    }
    h->magic = RES_MAGIC;
    h->type  = GX_WINDOW;
    h->alpha = 1.0;
    h->surface = eglCreateWindowSurface(display.disp, gx_configs[image_type], &h->u.native_window.egl_win, NULL);
    if (!h->surface)
    {
       GX_LOG("Could not create window surface: 0x%x", eglGetError());
       status = VCOS_ENOMEM;
       goto fail_win;
    }
    egl_result = eglSurfaceAttrib(display.disp, h->surface,
       EGL_SWAP_BEHAVIOR, EGL_BUFFER_PRESERVED);
    vcos_assert(egl_result);
    h->context   = gx_contexts[image_type];
    h->screen_id = screen_id;
    h->width     = width;
    h->height    = height;
    h->restype   = image_type;
    gx_priv_save(&save, h);
    // fill it with black
    status = gx_priv_resource_fill(h, 0, 0, width, height, GRAPHICS_RGBA32(0,0,0,0xff));
    vcos_assert(status == VCOS_SUCCESS);
    gx_priv_finish_native_window(h, cookie);
    gx_priv_flush(h);
    *resource_handle = h;
    gx_priv_restore(&save);
    return status;
 fail_win:
    gx_priv_destroy_native_window(h);
 fail_create_native_win:
    vcos_free(h);
    return status;
 }
gx_graphics_init()
VCOS_STATUS_T gx_graphics_init (const char * font_dir)
Definition at line 971 of file graphics.c.
References gx_priv_save(), and NULL.
Referenced by main().
 {
    GX_CLIENT_STATE_T save;
    VCOS_STATUS_T rc;
    gx_priv_save(&save, NULL);
    rc = gx_priv_initialise();
    if (rc == VCOS_SUCCESS)
       rc = gx_priv_font_init(font_dir);
    gx_priv_restore(&save);
    return rc;
 }