VideoCore Library: containers/mpga/mpga_reader.c File Reference
mpga_reader.c File Reference
#include <stdlib.h>
#include <string.h>
#include "containers/core/containers_private.h"
#include "containers/core/containers_io_helpers.h"
#include "containers/core/containers_utils.h"
#include "containers/core/containers_logging.h"
#include "mpga_common.h"
Classes
struct VC_CONTAINER_MODULE_T
Macros
#define CONTAINER_IS_BIG_ENDIAN
#define CONTAINER_HELPER_LOG_INDENT(a) 0
#define MPGA_XING_HAS_FRAMES 0x00000001
#define MPGA_XING_HAS_BYTES 0x00000002
#define MPGA_XING_HAS_TOC 0x00000004
#define MPGA_XING_HAS_QUALITY 0x00000008
#define MPGA_MAX_BAD_FRAMES
Typedefs
typedef struct VC_CONTAINER_MODULE_T VC_CONTAINER_MODULE_T
Functions
VC_CONTAINER_STATUS_T mpga_reader_open (VC_CONTAINER_T *)
Macro Definition Documentation
CONTAINER_HELPER_LOG_INDENT
#define CONTAINER_HELPER_LOG_INDENT (a) 0
Definition at line 33 of file mpga_reader.c.
CONTAINER_IS_BIG_ENDIAN
#define CONTAINER_IS_BIG_ENDIAN
Definition at line 30 of file mpga_reader.c.
MPGA_MAX_BAD_FRAMES
#define MPGA_MAX_BAD_FRAMES
Value:
4096 /*< Maximum number of failed byte-wise syncs,
                                        should be at least 2881+4 to cover the largest
                                        frame size (MPEG2.5 Layer 2, 160kbit/s 8kHz)
                                        + next frame header */
Definition at line 48 of file mpga_reader.c.
MPGA_XING_HAS_BYTES
#define MPGA_XING_HAS_BYTES 0x00000002
Definition at line 44 of file mpga_reader.c.
MPGA_XING_HAS_FRAMES
#define MPGA_XING_HAS_FRAMES 0x00000001
Definition at line 43 of file mpga_reader.c.
MPGA_XING_HAS_QUALITY
#define MPGA_XING_HAS_QUALITY 0x00000008
Definition at line 46 of file mpga_reader.c.
MPGA_XING_HAS_TOC
#define MPGA_XING_HAS_TOC 0x00000004
Definition at line 45 of file mpga_reader.c.
Typedef Documentation
VC_CONTAINER_MODULE_T
typedef struct VC_CONTAINER_MODULE_T VC_CONTAINER_MODULE_T
Function Documentation
mpga_reader_open()
VC_CONTAINER_STATUS_T mpga_reader_open (VC_CONTAINER_T * p_ctx)
Definition at line 464 of file mpga_reader.c.
References error(), extension, guid, LOG_DEBUG, VC_CONTAINER_PRIVATE_T::module, NULL, PEEK_BYTES, VC_CONTAINER_MODULE_T::pf_parse_header, VC_CONTAINER_T::priv, VC_CONTAINER_MODULE_T::track, VC_CONTAINER_T::tracks, VC_CONTAINER_T::tracks_num, VC_CONTAINER_PRIVATE_T::uri, vc_container_allocate_track(), VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED, VC_CONTAINER_ERROR_OUT_OF_MEMORY, VC_CONTAINER_SUCCESS, vc_uri_find_query(), and vc_uri_path_extension().
 {
    const char *extension = vc_uri_path_extension(p_ctx->priv->uri);
    VC_CONTAINER_MODULE_T *module = 0;
    VC_CONTAINER_STATUS_T status = VC_CONTAINER_SUCCESS;
    VC_CONTAINER_TRACK_T *track = NULL;
    unsigned int i;
    GUID_T guid;
    /* Check if the user has specified a container */
    vc_uri_find_query(p_ctx->priv->uri, 0, "container", &extension);
    /* Since mpeg audio is difficult to auto-detect, we use the extension as
       part of the autodetection */
    if(!extension)
       return VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED;
    if(strcasecmp(extension, "mp3") && strcasecmp(extension, "mp2") &&
       strcasecmp(extension, "aac") && strcasecmp(extension, "adts"))
       return VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED;
    /* Check we're not in fact dealing with an ASF file */
    if(PEEK_BYTES(p_ctx, (uint8_t *)&guid, sizeof(guid)) == sizeof(guid) &&
       !memcmp(&guid, &asf_guid_header, sizeof(guid)))
       return VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED;
    LOG_DEBUG(p_ctx, "using mpga reader");
    /* Allocate our context */
    if ((module = malloc(sizeof(*module))) == NULL)
    {
       status = VC_CONTAINER_ERROR_OUT_OF_MEMORY;
       goto error;
    }
    memset(module, 0, sizeof(*module));
    p_ctx->priv->module = module;
    p_ctx->tracks = &module->track;
    p_ctx->tracks[0] = vc_container_allocate_track(p_ctx, 0);
    if(!p_ctx->tracks[0])
    {
       status = VC_CONTAINER_ERROR_OUT_OF_MEMORY;
       goto error;
    }
    p_ctx->tracks_num = 1;
    module->pf_parse_header = mpga_read_header;
    if(!strcasecmp(extension, "aac") || !strcasecmp(extension, "adts"))
       module->pf_parse_header = adts_read_header;
    if ((status = mpga_sync(p_ctx)) != VC_CONTAINER_SUCCESS)
    {
       /* An error here probably means it's not an mpga file at all */
       if(status == VC_CONTAINER_ERROR_FORMAT_INVALID)
          status = VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED;
       goto error;
    }
    /* If we got this far, we're probably dealing with an mpeg audio file */
    track = p_ctx->tracks[0];
    track->format->es_type = VC_CONTAINER_ES_TYPE_AUDIO;
    track->format->codec = VC_CONTAINER_CODEC_MPGA;
    if(module->pf_parse_header == adts_read_header)
    {
       uint8_t *extra = track->format->extradata = module->extradata;
       unsigned int sr_id;
       for( sr_id = 0; sr_id < 13; sr_id++ )
          if( mpga_sample_rate_adts[sr_id] == module->sample_rate ) break;
       extra[0] = (module->version << 3) | ((sr_id & 0xe) >> 1);
       extra[1] = ((sr_id & 0x1) << 7) | (module->channels << 3);
       track->format->extradata_size = 2;
       track->format->codec = VC_CONTAINER_CODEC_MP4A;
    }
    track->format->flags |= VC_CONTAINER_ES_FORMAT_FLAG_FRAMED;
    track->is_enabled = true;
    track->format->type->audio.channels = module->channels;
    track->format->type->audio.sample_rate = module->sample_rate;
    track->format->type->audio.bits_per_sample = 0;
    track->format->type->audio.block_align = 1;
    module->data_offset = STREAM_POSITION(p_ctx);
    /* Look for VBR headers within the first frame */
    status = mpga_read_vbr_headers(p_ctx);
    if (status && status != VC_CONTAINER_ERROR_NOT_FOUND) goto error;
    /* If we couldn't get this information from VBR headers, try to determine
       file size, bitrate, number of frames and duration */
    if (!module->data_size)
       module->data_size = MAX(p_ctx->priv->io->size - module->data_offset, INT64_C(0));
    if (!module->bitrate)
    {
       if (STREAM_SEEKABLE(p_ctx))
       {
          /* Scan past a few hundred frames (audio will often have
             silence in the beginning so we need to see more than
             just a few frames) and estimate bitrate */
          for (i = 0; i < 256; ++i)
             if (mpga_reader_read(p_ctx, NULL, VC_CONTAINER_READ_FLAG_SKIP)) break;
          /* Seek back to start of data */
          SEEK(p_ctx, module->data_offset);
          module->frame_index = 0;
          module->frame_offset = INT64_C(0);
          module->frame_time_pos = mpga_calculate_frame_time(p_ctx);
       }
       else
       {
          /* Bitrate will be correct for CBR only */
          module->bitrate = module->frame_bitrate;
       }
    }
    track->format->bitrate = module->bitrate;
    if (!module->num_frames)
    {
       module->num_frames = (module->data_size * module->sample_rate * 8LL) /
                               (module->bitrate * module->frame_size_samples);
    }
    if (!p_ctx->duration && module->bitrate)
    {
       p_ctx->duration = (INT64_C(8000000) * module->data_size) / module->bitrate;
    }
    p_ctx->priv->pf_close = mpga_reader_close;
    p_ctx->priv->pf_read = mpga_reader_read;
    p_ctx->priv->pf_seek = mpga_reader_seek;
    if(STREAM_SEEKABLE(p_ctx)) p_ctx->capabilities |= VC_CONTAINER_CAPS_CAN_SEEK;
    if(STREAM_STATUS(p_ctx) != VC_CONTAINER_SUCCESS) goto error;
    return VC_CONTAINER_SUCCESS;
 error:
    if(status == VC_CONTAINER_SUCCESS || status == VC_CONTAINER_ERROR_EOS)
       status = VC_CONTAINER_ERROR_FORMAT_INVALID;
    LOG_DEBUG(p_ctx, "error opening stream (%i)", status);
    if (p_ctx->tracks_num != 0)
       vc_container_free_track(p_ctx, p_ctx->tracks[0]);
    p_ctx->tracks = NULL;
    p_ctx->tracks_num = 0;
    if (module) free(module);
    p_ctx->priv->module = NULL;
    return status;
 }