VideoCore Library: interface/mmal/core/mmal_events_private.h File Reference
mmal_events_private.h File Reference
#include "mmal_events.h"
Functions
MMAL_STATUS_T mmal_event_error_send (MMAL_COMPONENT_T *component, MMAL_STATUS_T status)
MMAL_STATUS_T mmal_event_eos_send (MMAL_PORT_T *port)
MMAL_STATUS_T mmal_event_forward (MMAL_BUFFER_HEADER_T *event, MMAL_PORT_T *port)
Function Documentation
mmal_event_eos_send()
MMAL_STATUS_T mmal_event_eos_send (MMAL_PORT_T * port)
Send an eos event through a specific port.
Parameters
port port to receive the error event.
Returns
MMAL_SUCCESS or an error if the event could not be sent.
Definition at line 78 of file mmal_events.c.
References MMAL_PORT_T::component, MMAL_COMPONENT_T::control, MMAL_BUFFER_HEADER_T::data, MMAL_PORT_T::index, MMAL_BUFFER_HEADER_T::length, LOG_ERROR, MMAL_EINVAL, MMAL_EVENT_EOS, mmal_port_event_get(), mmal_port_event_send(), MMAL_SUCCESS, MMAL_PORT_T::name, MMAL_EVENT_END_OF_STREAM_T::port_index, MMAL_EVENT_END_OF_STREAM_T::port_type, status, and MMAL_PORT_T::type.
 {
    MMAL_EVENT_END_OF_STREAM_T *event;
    MMAL_BUFFER_HEADER_T *buffer;
    MMAL_STATUS_T status;
    if(!port)
    {
       LOG_ERROR("invalid port");
       return MMAL_EINVAL;
    }
    status = mmal_port_event_get(port->component->control, &buffer, MMAL_EVENT_EOS);
    if (status != MMAL_SUCCESS)
    {
       LOG_ERROR("event not available for port %s %p, result %d", port->name, port, status);
       return status;
    }
    buffer->length = sizeof(*event);
    event = (MMAL_EVENT_END_OF_STREAM_T *)buffer->data;
    event->port_type = port->type;
    event->port_index = port->index;
    mmal_port_event_send(port->component->control, buffer);
    return MMAL_SUCCESS;
 }
mmal_event_error_send()
MMAL_STATUS_T mmal_event_error_send (MMAL_COMPONENT_T * component, MMAL_STATUS_T status)
Send an error event through the component's control port. The error event data will be the MMAL_STATUS_T passed in.
Parameters
component component to receive the error event.
status the error status to be sent.
Returns
MMAL_SUCCESS or an error if the event could not be sent.
Definition at line 53 of file mmal_events.c.
References MMAL_COMPONENT_T::control, MMAL_BUFFER_HEADER_T::data, LOG_ERROR, MMAL_EINVAL, MMAL_EVENT_ERROR, mmal_port_event_get(), mmal_port_event_send(), MMAL_SUCCESS, MMAL_COMPONENT_T::name, and status.
 {
    MMAL_BUFFER_HEADER_T* event;
    MMAL_STATUS_T status;
    if(!component)
    {
       LOG_ERROR("invalid component");
       return MMAL_EINVAL;
    }
    status = mmal_port_event_get(component->control, &event, MMAL_EVENT_ERROR);
    if (status != MMAL_SUCCESS)
    {
       LOG_ERROR("event not available for component %s %p, result %d", component->name, component, status);
       return status;
    }
    event->length = sizeof(MMAL_STATUS_T);
    *(MMAL_STATUS_T *)event->data = error_status;
    mmal_port_event_send(component->control, event);
    return MMAL_SUCCESS;
 }
mmal_event_forward()
MMAL_STATUS_T mmal_event_forward (MMAL_BUFFER_HEADER_T * event, MMAL_PORT_T * port)
Forward an event onto an output port. This will allocate a new event buffer on the output port, make a copy of the event buffer which will then be forwarded.
event to forward.
Parameters
port port to forward event to.
Returns
MMAL_SUCCESS or an error if the event could not be forwarded.
Definition at line 106 of file mmal_events.c.
References MMAL_BUFFER_HEADER_T::alloc_size, MMAL_BUFFER_HEADER_T::cmd, MMAL_PORT_T::component, MMAL_COMPONENT_T::control, MMAL_BUFFER_HEADER_T::data, MMAL_BUFFER_HEADER_T::flags, MMAL_BUFFER_HEADER_T::length, LOG_ERROR, mmal_buffer_header_release(), MMAL_EINVAL, MMAL_ENOSPC, mmal_port_event_get(), mmal_port_event_send(), MMAL_PORT_TYPE_OUTPUT, MMAL_SUCCESS, MMAL_PORT_T::name, MMAL_BUFFER_HEADER_T::offset, MMAL_BUFFER_HEADER_T::pts, status, and MMAL_PORT_T::type.
 {
    MMAL_BUFFER_HEADER_T *buffer;
    MMAL_STATUS_T status;
    if(!port || port->type != MMAL_PORT_TYPE_OUTPUT)
    {
       LOG_ERROR("invalid port");
       return MMAL_EINVAL;
    }
    status = mmal_port_event_get(port->component->control, &buffer, event->cmd);
    if (status != MMAL_SUCCESS)
    {
       LOG_ERROR("event not available for port %s %p, result %d", port->name, port, status);
       return status;
    }
    if (buffer->alloc_size < event->length)
    {
       LOG_ERROR("event buffer too small (%i/%i)", buffer->alloc_size, event->length);
       mmal_buffer_header_release(buffer);
       return MMAL_ENOSPC;
    }
    memcpy(buffer->data, event->data, event->length);
    buffer->length = event->length;
    buffer->offset = event->offset;
    buffer->flags = event->flags;
    buffer->pts = event->pts;
    mmal_port_event_send(port->component->control, buffer);
    return MMAL_SUCCESS;
 }