VideoCore Library: interface/khronos/wf/wfc_client_ipc.c File Reference
wfc_client_ipc.c File Reference
#include "interface/khronos/wf/wfc_client_ipc.h"
#include "interface/khronos/wf/wfc_ipc.h"
#include "interface/vcos/vcos.h"
#include "interface/vchiq_arm/vchiq.h"
Classes
struct WFC_WAITER_T
struct WFC_WAITPOOL_T
struct WFC_CLIENT_IPC_T
Macros
#define VCOS_LOG_CATEGORY (&wfc_client_ipc_log_category)
#define WFC_CLIENT_IPC_LOGLEVEL VCOS_LOG_WARN
#define WFC_CLIENT_IPC_MAX_WAITERS 16
Typedefs
typedef struct WFC_WAITER_T WFC_WAITER_T
typedef struct WFC_CLIENT_IPC_T WFC_CLIENT_IPC_T
Functions
VCOS_STATUS_T wfc_client_ipc_sendwait (WFC_IPC_MSG_HEADER_T *msg, size_t size, void *dest, size_t *destlen)
VCOS_STATUS_T wfc_client_ipc_send (WFC_IPC_MSG_HEADER_T *msg, size_t size)
VCOS_STATUS_T wfc_client_ipc_init (void)
bool wfc_client_ipc_deinit (void)
void wfc_client_ipc_use_keep_alive (void)
void wfc_client_ipc_release_keep_alive (void)
WFC_CLIENT_IPC_T * wfc_client_ipc_get_client (void)
Macro Definition Documentation
VCOS_LOG_CATEGORY
#define VCOS_LOG_CATEGORY (&wfc_client_ipc_log_category)
Definition at line 33 of file wfc_client_ipc.c.
WFC_CLIENT_IPC_LOGLEVEL
#define WFC_CLIENT_IPC_LOGLEVEL VCOS_LOG_WARN
Definition at line 39 of file wfc_client_ipc.c.
WFC_CLIENT_IPC_MAX_WAITERS
#define WFC_CLIENT_IPC_MAX_WAITERS 16
Definition at line 42 of file wfc_client_ipc.c.
Typedef Documentation
WFC_CLIENT_IPC_T
typedef struct WFC_CLIENT_IPC_T WFC_CLIENT_IPC_T
Definition at line 77 of file wfc_client_ipc.c.
WFC_WAITER_T
typedef struct WFC_WAITER_T WFC_WAITER_T
Client threads use one of these to wait for a reply from VideoCore.
Function Documentation
wfc_client_ipc_deinit()
bool wfc_client_ipc_deinit (void)
Deinitialise the OpenWF-C client IPC.
Returns
True if the service has been destroyed, false if there are other users still active.
Definition at line 451 of file wfc_client_ipc.c.
References vcos_once().
Referenced by wfc_server_disconnect().
 {
    bool service_destroyed = false;
    vcos_once(&wfc_client_ipc_once, init_once);
    vcos_mutex_lock(&wfc_client_ipc.lock);
    if (!wfc_client_ipc.refcount)
    {
       /* Never initialised */
       goto completed;
    }
    if (--wfc_client_ipc.refcount != 0)
    {
       /* Still in use so don't do anything */
       goto completed;
    }
    vcos_log_trace("%s: starting deinitialisation", VCOS_FUNCTION);
    /* Last reference dropped, tear down service */
    wfc_client_ipc_destroy_waitpool(&wfc_client_ipc.waitpool);
    vchiq_remove_service(wfc_client_ipc.service);
    vchiq_shutdown(wfc_client_ipc_vchiq_instance);
    vcos_log_unregister(VCOS_LOG_CATEGORY);
    wfc_client_ipc.service = 0;
    service_destroyed = true;
 completed:
    vcos_mutex_unlock(&wfc_client_ipc.lock);
    return service_destroyed;
 }
wfc_client_ipc_get_client()
WFC_CLIENT_IPC_T* wfc_client_ipc_get_client (void)
Definition at line 518 of file wfc_client_ipc.c.
 {
    return &wfc_client_ipc;
 }
wfc_client_ipc_init()
VCOS_STATUS_T wfc_client_ipc_init (void)
Initialise the OpenWF-C client IPC. If successful, this must be balanced by a call to wfc_client_ipc_deinit(). This must be called at least once before sending a message.
Returns
Success or the error code for failure.
Definition at line 359 of file wfc_client_ipc.c.
References VCOS_ENXIO, and vcos_once().
Referenced by wfc_server_connect().
 {
    VCHIQ_SERVICE_PARAMS_T vchiq_params;
    bool vchiq_initialised = false, waitpool_initialised = false;
    bool service_initialised = false;
    VCOS_STATUS_T status = VCOS_ENXIO;
    VCHIQ_STATUS_T vchiq_status;
    vcos_once(&wfc_client_ipc_once, init_once);
    vcos_mutex_lock(&wfc_client_ipc.lock);
    if (wfc_client_ipc.refcount++ > 0)
    {
       /* Already initialised so nothing to do */
       vcos_mutex_unlock(&wfc_client_ipc.lock);
       return VCOS_SUCCESS;
    }
    vcos_log_set_level(VCOS_LOG_CATEGORY, WFC_CLIENT_IPC_LOGLEVEL);
    vcos_log_register("wfcipc", VCOS_LOG_CATEGORY);
    vcos_log_trace("%s: starting initialisation", VCOS_FUNCTION);
    /* Initialise a VCHIQ instance */
    vchiq_status = vchiq_initialise(&wfc_client_ipc_vchiq_instance);
    if (vchiq_status != VCHIQ_SUCCESS)
    {
       vcos_log_error("%s: failed to initialise vchiq: %d", VCOS_FUNCTION, vchiq_status);
       goto error;
    }
    vchiq_initialised = true;
    vchiq_status = vchiq_connect(wfc_client_ipc_vchiq_instance);
    if (vchiq_status != VCHIQ_SUCCESS)
    {
       vcos_log_error("%s: failed to connect to vchiq: %d", VCOS_FUNCTION, vchiq_status);
       goto error;
    }
    memset(&vchiq_params, 0, sizeof(vchiq_params));
    vchiq_params.fourcc = WFC_IPC_CONTROL_FOURCC();
    vchiq_params.callback = wfc_client_ipc_vchiq_callback;
    vchiq_params.userdata = &wfc_client_ipc;
    vchiq_params.version = WFC_IPC_VER_CURRENT;
    vchiq_params.version_min = WFC_IPC_VER_MINIMUM;
    vchiq_status = vchiq_open_service(wfc_client_ipc_vchiq_instance, &vchiq_params, &wfc_client_ipc.service);
    if (vchiq_status != VCHIQ_SUCCESS)
    {
       vcos_log_error("%s: could not open vchiq service: %d", VCOS_FUNCTION, vchiq_status);
       goto error;
    }
    service_initialised = true;
    status = wfc_client_ipc_create_waitpool(&wfc_client_ipc.waitpool);
    if (status != VCOS_SUCCESS)
    {
       vcos_log_error("%s: could not create wait pool: %d", VCOS_FUNCTION, status);
       goto error;
    }
    waitpool_initialised = true;
    /* Allow videocore to suspend, drops count to zero. */
    vchiq_release_service(wfc_client_ipc.service);
    vcos_mutex_unlock(&wfc_client_ipc.lock);
    status = wfc_client_ipc_send_client_pid();
    if (status != VCOS_SUCCESS)
    {
       vcos_log_error("%s: could not send client pid: %d", VCOS_FUNCTION, status);
       vcos_mutex_lock(&wfc_client_ipc.lock);
       goto error;
    }
    return VCOS_SUCCESS;
 error:
    if (waitpool_initialised)
       wfc_client_ipc_destroy_waitpool(&wfc_client_ipc.waitpool);
    if (service_initialised)
       vchiq_remove_service(wfc_client_ipc.service);
    if (vchiq_initialised)
       vchiq_shutdown(wfc_client_ipc_vchiq_instance);
    vcos_log_unregister(VCOS_LOG_CATEGORY);
    wfc_client_ipc.refcount--;
    vcos_mutex_unlock(&wfc_client_ipc.lock);
    return status;
 }
wfc_client_ipc_release_keep_alive()
void wfc_client_ipc_release_keep_alive (void)
Drop the keep alive count by one. If it reaches zero, the VideoCore may be suspended.
Definition at line 503 of file wfc_client_ipc.c.
References vcos_mutex_lock().
Referenced by wfc_server_release_keep_alive().
 {
    vcos_mutex_lock(&wfc_client_ipc.lock);
    if (vcos_verify(wfc_client_ipc.keep_alive_count > 0))
    {
       if (!--wfc_client_ipc.keep_alive_count)
          vchiq_release_service(wfc_client_ipc.service);
    }
    vcos_mutex_unlock(&wfc_client_ipc.lock);
 }
wfc_client_ipc_send()
VCOS_STATUS_T wfc_client_ipc_send (WFC_IPC_MSG_HEADER_T * msg, size_t size)
Send a message and do not wait for a reply.
Parameters
msg_header message header to send
size length of message, including header
msgid message id
Returns
Success or the error code for failure.
Definition at line 324 of file wfc_client_ipc.c.
References WFC_IPC_MSG_HEADER_T::type, vcos_assert, VCOS_FUNCTION, and vcos_verify.
Referenced by wfc_server_stream_destroy(), wfc_server_stream_on_image_available(), wfc_server_stream_on_rects_change(), wfc_server_stream_register(), wfc_server_stream_signal_eglimage_data(), wfc_server_stream_signal_image(), wfc_server_stream_signal_mm_image_data(), wfc_server_stream_signal_raw_pixels(), and wfc_server_stream_unregister().
 {
    VCHIQ_STATUS_T vst;
    VCHIQ_ELEMENT_T elems[] = {{msg, size}};
    vcos_log_trace("%s: type %d, len %d", VCOS_FUNCTION, msg->type, size);
    vcos_assert(size >= sizeof(*msg));
    if (!vcos_verify(wfc_client_ipc.refcount))
    {
       VCOS_ALERT("%s: client uninitialised", VCOS_FUNCTION);
       /* Client has not been initialised */
       return VCOS_EINVAL;
    }
    msg->magic  = WFC_IPC_MSG_MAGIC;
    msg->waiter.ptr = NULL;
    wfc_client_ipc_use_keep_alive();
    vst = vchiq_queue_message(wfc_client_ipc.service, elems, 1);
    wfc_client_ipc_release_keep_alive();
    if (vst != VCHIQ_SUCCESS)
    {
       vcos_log_error("%s: failed to queue, 0x%x", VCOS_FUNCTION, vst);
       return VCOS_ENXIO;
    }
    return VCOS_SUCCESS;
 }
wfc_client_ipc_sendwait()
VCOS_STATUS_T wfc_client_ipc_sendwait (WFC_IPC_MSG_HEADER_T * msg, size_t size, void * dest, size_t * destlen)
Send a message and wait for a reply.
Parameters
msg message to send
size length of message, including header
dest destination for reply data, or NULL
destlen size of destination, updated with actual length
Returns
Success or the error code for failure.
Definition at line 267 of file wfc_client_ipc.c.
References vcos_assert, VCOS_SUCCESS, and vcos_verify.
Referenced by wfc_server_stream_allocate_images(), wfc_server_stream_create(), and wfc_server_stream_create_info().
 {
    VCOS_STATUS_T ret = VCOS_SUCCESS;
    WFC_WAITER_T *waiter;
    VCHIQ_STATUS_T vst;
    VCHIQ_ELEMENT_T elems[] = {{msg, size}};
    vcos_assert(size >= sizeof(*msg));
    vcos_assert(dest);
    if (!vcos_verify(wfc_client_ipc.refcount))
    {
       VCOS_ALERT("%s: client uninitialised", VCOS_FUNCTION);
       /* Client has not been initialised */
       return VCOS_EINVAL;
    }
    msg->magic = WFC_IPC_MSG_MAGIC;
    waiter = wfc_client_ipc_get_waiter(&wfc_client_ipc);
    waiter->dest = dest;
    waiter->destlen = *destlen;
    msg->waiter.ptr = waiter;
    wfc_client_ipc_use_keep_alive();
    vcos_log_trace("%s: wait %p, reply to %p", VCOS_FUNCTION, waiter, dest);
    vst = vchiq_queue_message(wfc_client_ipc.service, elems, 1);
    if (vst != VCHIQ_SUCCESS)
    {
       vcos_log_error("%s: failed to queue, 0x%x", VCOS_FUNCTION, vst);
       ret = VCOS_ENXIO;
       goto completed;
    }
    /* now wait for the reply...
     *
     * FIXME: we could do with a timeout here. Need to be careful to cancel
     * the semaphore on a timeout.
     */
    vcos_semaphore_wait(&waiter->sem);
    vcos_log_trace("%s: got reply (len %i/%i)", VCOS_FUNCTION, (int)*destlen, (int)waiter->destlen);
    *destlen = waiter->destlen;
    /* Drop through completion code */
 completed:
    wfc_client_ipc_release_waiter(&wfc_client_ipc, waiter);
    wfc_client_ipc_release_keep_alive();
    return ret;
 }
wfc_client_ipc_use_keep_alive()
void wfc_client_ipc_use_keep_alive (void)
Increase the keep alive count by one. If it rises from zero, the VideoCore will be prevented from being suspended.
Definition at line 491 of file wfc_client_ipc.c.
References vcos_mutex_lock().
Referenced by wfc_server_use_keep_alive().
 {
    vcos_mutex_lock(&wfc_client_ipc.lock);
    if (!wfc_client_ipc.keep_alive_count++)
       vchiq_use_service(wfc_client_ipc.service);
    vcos_mutex_unlock(&wfc_client_ipc.lock);
 }