VideoCore Library: host_applications/linux/apps/raspicam/RaspiGPS.h File Reference
RaspiGPS.h File Reference
#include <pthread.h>
#include <time.h>
#include "libgps_loader.h"
Functions
int raspi_gps_setup (int verbose)
void raspi_gps_shutdown (int verbose)
struct gps_data_t * raspi_gps_lock ()
void raspi_gps_unlock ()
char * raspi_gps_location_string ()
Function Documentation
raspi_gps_location_string()
char* raspi_gps_location_string ()
Definition at line 188 of file RaspiGPS.c.
References gps_fix_t::altitude, ALTITUDE_SET, gps_data_t::fix, gps_fix_t::latitude, LATLON_SET, gps_fix_t::longitude, gps_fix_t::mode, MODE_2D, MODE_3D, MPS_TO_KPH, gps_data_t::online, raspi_gps_lock(), raspi_gps_unlock(), gps_data_t::set, gps_fix_t::speed, SPEED_SET, gps_fix_t::time, TIME_SET, gps_fix_t::track, and TRACK_SET.
 {
    char lat[24] = {"n/a"};
    char lon[24] = {"n/a"};
    char alt[24] = {"Altitude n/a"};
    char speed[24] = {"Speed n/a"};
    char track[24] = {"Track n/a"};
    char datetime[32] = {"Time n/a"};
    char *text;
    struct gps_data_t *gpsdata = raspi_gps_lock();
    if (gpsdata->set & TIME_SET)
    {
       time_t rawtime;
       struct tm *timeinfo;
       rawtime = gpsdata->fix.time;
       timeinfo = localtime(&rawtime);
       strftime(datetime, sizeof(datetime), "%Y:%m:%d %H:%M:%S", timeinfo);
    }
    if (gpsdata->online && gpsdata->fix.mode >= MODE_2D)
    {
       if (gpsdata->set & LATLON_SET)
       {
          if (!isnan(gpsdata->fix.latitude))
             snprintf(lat, sizeof(lat), "%.6lf", gpsdata->fix.latitude);
          if (!isnan(gpsdata->fix.longitude))
             snprintf(lon, sizeof(lon), "%.6lf", gpsdata->fix.longitude);
       }
       if ((gpsdata->set & ALTITUDE_SET) && (gpsdata->fix.mode >= MODE_3D) &&
             (!isnan(gpsdata->fix.altitude)))
       {
          snprintf(alt, sizeof(alt), "Altitude=%.2fm", gpsdata->fix.altitude);
       }
       if ((gpsdata->set & SPEED_SET) && !isnan(gpsdata->fix.speed))
       {
          snprintf(speed, sizeof(speed), "Speed=%.2fkph", gpsdata->fix.speed*MPS_TO_KPH);
       }
       if ((gpsdata->set & TRACK_SET) && !isnan(gpsdata->fix.track))
       {
          snprintf(track, sizeof(track), "Track=%.2f", gpsdata->fix.track);
       }
    }
    raspi_gps_unlock();
    asprintf(&text,  "%s Lat %s Long %s %s %s %s", datetime, lat, lon, alt, speed, track);
    return text;
 }
raspi_gps_lock()
struct gps_data_t* raspi_gps_lock ()
Definition at line 52 of file RaspiGPS.c.
References GPS_READER_DATA::gps_cache_mutex, and GPS_READER_DATA::gpsdata_cache.
Referenced by raspi_gps_location_string().
 {
    pthread_mutex_lock(&gps_reader_data.gps_cache_mutex);
    return &gps_reader_data.gpsdata_cache;
 }
raspi_gps_setup()
int raspi_gps_setup (int verbose)
Definition at line 136 of file RaspiGPS.c.
References connect_gpsd(), GPS_READER_DATA::gps_cache_mutex, gpsd_info::gps_errstr, GPS_READER_DATA::gps_reader_thread, GPS_READER_DATA::gpsd, gpsd_init(), libgps_load(), libgps_unload(), NULL, gpsd_info::port, gpsd_info::server, and wait_gps_time().
 {
    memset(&gps_reader_data, 0, sizeof(gps_reader_data));
    pthread_mutex_init(&gps_reader_data.gps_cache_mutex, NULL);
    gpsd_init(&gps_reader_data.gpsd);
    if (libgps_load(&gps_reader_data.gpsd))
    {
       pthread_mutex_destroy(&gps_reader_data.gps_cache_mutex);
       fprintf(stderr, "Unable to load the libGPS library");
       return -1;
    }
    if (verbose)
       fprintf(stderr, "Connecting to gpsd @ %s:%s\n",
               gps_reader_data.gpsd.server, gps_reader_data.gpsd.port);
    if (connect_gpsd(&gps_reader_data.gpsd))
    {
       fprintf(stderr, "no gpsd running or network error: %d, %s\n",
               errno, gps_reader_data.gpsd.gps_errstr(errno));
       libgps_unload(&gps_reader_data.gpsd);
       pthread_mutex_destroy(&gps_reader_data.gps_cache_mutex);
       return -1;
    }
    if (verbose)
       fprintf(stderr, "Waiting for GPS time\n");
    if (wait_gps_time(&gps_reader_data.gpsd, 2))
    {
       if (verbose)
          fprintf(stderr, "Warning: GPS time not available\n");
    }
    if (verbose)
       fprintf(stderr, "Creating GPS reader thread\n");
    if (pthread_create(&gps_reader_data.gps_reader_thread, NULL,
                       gps_reader_process, &gps_reader_data))
    {
       fprintf(stderr, "Error creating GPS reader thread\n");
       gps_reader_data.terminated = 1;
       raspi_gps_shutdown(verbose);
       return -1;
    }
    gps_reader_data.gps_reader_thread_ok = 1;
    return 0;
 }
raspi_gps_shutdown()
void raspi_gps_shutdown (int verbose)
Definition at line 115 of file RaspiGPS.c.
References disconnect_gpsd(), GPS_READER_DATA::gps_cache_mutex, GPS_READER_DATA::gps_reader_thread, GPS_READER_DATA::gps_reader_thread_ok, GPS_READER_DATA::gpsd, gpsd_info::gpsd_connected, libgps_unload(), NULL, and GPS_READER_DATA::terminated.
 {
    gps_reader_data.terminated = 1;
    if (gps_reader_data.gps_reader_thread_ok)
    {
       if (verbose)
          fprintf(stderr, "Waiting for GPS reader thread to terminate\n");
       pthread_join(gps_reader_data.gps_reader_thread, NULL);
    }
    if (verbose && gps_reader_data.gpsd.gpsd_connected)
       fprintf(stderr, "Closing gpsd connection\n\n");
    disconnect_gpsd(&gps_reader_data.gpsd);
    libgps_unload(&gps_reader_data.gpsd);
    pthread_mutex_destroy(&gps_reader_data.gps_cache_mutex);
 }
raspi_gps_unlock()
void raspi_gps_unlock ()
Definition at line 58 of file RaspiGPS.c.
References GPS_READER_DATA::gps_cache_mutex.
Referenced by raspi_gps_location_string().
 {
    pthread_mutex_unlock(&gps_reader_data.gps_cache_mutex);
 }