VideoCore Library: interface/mmal/vc/mmal_vc_api.c File Reference
mmal_vc_api.c File Reference
#include "interface/mmal/mmal_logging.h"
#include "interface/mmal/mmal.h"
#include "mmal_vc_api.h"
#include "mmal_vc_msgs.h"
#include "mmal_vc_client_priv.h"
#include "mmal_vc_opaque_alloc.h"
#include "mmal_vc_shm.h"
#include "interface/mmal/util/mmal_util.h"
#include "interface/mmal/core/mmal_component_private.h"
#include "interface/mmal/core/mmal_port_private.h"
#include "interface/mmal/core/mmal_buffer_private.h"
#include "interface/vcos/vcos.h"
Classes
struct MMAL_PORT_MODULE_T
struct MMAL_COMPONENT_MODULE_T
Typedefs
typedef enum MMAL_ZEROLEN_CHECK_T MMAL_ZEROLEN_CHECK_T
typedef enum MMAL_PORT_FLUSH_CHECK_T MMAL_PORT_FLUSH_CHECK_T
typedef struct MMAL_PORT_MODULE_T MMAL_PORT_MODULE_T
typedef struct MMAL_COMPONENT_MODULE_T MMAL_COMPONENT_MODULE_T
Enumerations
enum MMAL_ZEROLEN_CHECK_T { ZEROLEN_NOT_INITIALIZED, ZEROLEN_COMPATIBLE, ZEROLEN_INCOMPATIBLE }
enum MMAL_PORT_FLUSH_CHECK_T { PORT_FLUSH_NOT_INITIALIZED, PORT_FLUSH_COMPATIBLE, PORT_FLUSH_INCOMPATIBLE }
Functions
MMAL_STATUS_T mmal_vc_get_version (uint32_t *major, uint32_t *minor, uint32_t *minimum)
MMAL_STATUS_T mmal_vc_get_stats (MMAL_VC_STATS_T *stats, int reset)
MMAL_STATUS_T mmal_vc_consume_mem (size_t size, uint32_t *handle)
MMAL_STATUS_T mmal_vc_compact (MMAL_VC_COMPACT_MODE_T mode, uint32_t *duration)
MMAL_STATUS_T mmal_vc_lmk (uint32_t alloc_size)
MMAL_STATUS_T mmal_vc_host_log (const char *msg)
MMAL_STATUS_T mmal_vc_get_core_stats (MMAL_CORE_STATISTICS_T *stats, MMAL_STATS_RESULT_T *result, char *name, size_t namelen, MMAL_PORT_TYPE_T type, unsigned component_index, unsigned port_index, MMAL_CORE_STATS_DIR dir, MMAL_BOOL_T reset)
MMAL_CONSTRUCTOR (mmal_register_component_videocore)
void mmal_register_component_videocore (void)
Typedef Documentation
MMAL_COMPONENT_MODULE_T
typedef struct MMAL_COMPONENT_MODULE_T MMAL_COMPONENT_MODULE_T
MMAL_PORT_FLUSH_CHECK_T
typedef enum MMAL_PORT_FLUSH_CHECK_T MMAL_PORT_FLUSH_CHECK_T
MMAL_PORT_MODULE_T
typedef struct MMAL_PORT_MODULE_T MMAL_PORT_MODULE_T
MMAL_ZEROLEN_CHECK_T
typedef enum MMAL_ZEROLEN_CHECK_T MMAL_ZEROLEN_CHECK_T
Private information for MMAL VC components
Enumeration Type Documentation
MMAL_PORT_FLUSH_CHECK_T
enum MMAL_PORT_FLUSH_CHECK_T
Enumerator
PORT_FLUSH_NOT_INITIALIZED
PORT_FLUSH_COMPATIBLE
PORT_FLUSH_INCOMPATIBLE
Definition at line 51 of file mmal_vc_api.c.
 {
    PORT_FLUSH_NOT_INITIALIZED,
    PORT_FLUSH_COMPATIBLE,
    PORT_FLUSH_INCOMPATIBLE
 } MMAL_PORT_FLUSH_CHECK_T;
MMAL_ZEROLEN_CHECK_T
enum MMAL_ZEROLEN_CHECK_T
Private information for MMAL VC components
Enumerator
ZEROLEN_NOT_INITIALIZED
ZEROLEN_COMPATIBLE
ZEROLEN_INCOMPATIBLE
Definition at line 44 of file mmal_vc_api.c.
 {
    ZEROLEN_NOT_INITIALIZED,
    ZEROLEN_COMPATIBLE,
    ZEROLEN_INCOMPATIBLE
 } MMAL_ZEROLEN_CHECK_T;
Function Documentation
MMAL_CONSTRUCTOR()
MMAL_CONSTRUCTOR (mmal_register_component_videocore)
mmal_register_component_videocore()
void mmal_register_component_videocore (void)
Definition at line 1547 of file mmal_vc_api.c.
References mmal_component_supplier_register(), and VIDEOCORE_PREFIX.
 {
    mmal_component_supplier_register(VIDEOCORE_PREFIX, mmal_vc_component_create);
 }
mmal_vc_compact()
MMAL_STATUS_T mmal_vc_compact (MMAL_VC_COMPACT_MODE_T mode, uint32_t * duration)
Trigger relocatable heap compaction.
Definition at line 844 of file mmal_vc_api.c.
References mmal_worker_compact::duration, mmal_worker_compact::header, len, MMAL_FALSE, MMAL_SUCCESS, mmal_vc_get_client(), mmal_vc_sendwait_message(), MMAL_WORKER_COMPACT, mmal_worker_compact::mode, status, mmal_worker_compact::status, and vcos_assert.
 {
    MMAL_STATUS_T status;
    mmal_worker_compact req;
    mmal_worker_compact reply;
    size_t len = sizeof(reply);
    req.mode = (uint32_t)mode;
    status = mmal_vc_sendwait_message(mmal_vc_get_client(),
                                      &req.header, sizeof(req),
                                      MMAL_WORKER_COMPACT,
                                      &reply, &len, MMAL_FALSE);
    if (status == MMAL_SUCCESS)
    {
       vcos_assert(len == sizeof(reply));
       status = reply.status;
       *duration = reply.duration;
    }
    return status;
 }
mmal_vc_consume_mem()
MMAL_STATUS_T mmal_vc_consume_mem (size_t size, uint32_t * handle)
Consumes memory in the relocatable heap.
The existing reserved memory is freed first then the new chunk is allocated. If zero is specified for the size then the previously reserved memory is freed and no allocation occurs.
At startup no memory is reserved.
Parameters
size Size of memory to consume in bytes.
handle Set to the mem handle for the reserved memory or zero if no memory was allocated.
Returns
MMAL_SUCCESS if memory was reserved (or size zero requested), MMAL_ENOSPC if the allocation failed or MMAL_ENOSYS if the API is not supported e.g in release mode VC images.
Definition at line 822 of file mmal_vc_api.c.
References mmal_worker_consume_mem::handle, mmal_worker_consume_mem::header, len, MMAL_FALSE, MMAL_SUCCESS, mmal_vc_get_client(), mmal_vc_sendwait_message(), MMAL_WORKER_CONSUME_MEM, mmal_worker_consume_mem::size, status, mmal_worker_consume_mem::status, and vcos_assert.
 {
    MMAL_STATUS_T status;
    mmal_worker_consume_mem req;
    mmal_worker_consume_mem reply;
    size_t len = sizeof(reply);
    req.size = (uint32_t) size;
    status = mmal_vc_sendwait_message(mmal_vc_get_client(),
                                      &req.header, sizeof(req),
                                      MMAL_WORKER_CONSUME_MEM,
                                      &reply, &len, MMAL_FALSE);
    if (status == MMAL_SUCCESS)
    {
       vcos_assert(len == sizeof(reply));
       status = reply.status;
       *handle = reply.handle;
    }
    return status;
 }
mmal_vc_get_core_stats()
MMAL_STATUS_T mmal_vc_get_core_stats (MMAL_CORE_STATISTICS_T * stats, MMAL_STATS_RESULT_T * result, char * name, size_t namelen, MMAL_PORT_TYPE_T type, unsigned component, unsigned port, MMAL_CORE_STATS_DIR dir, MMAL_BOOL_T reset)
Return the MMAL core statistics for a given component/port.
Parameters
stats Updated with given port statistics
result Whether the port/component was found
name Filled in with the name of the port
namelen Length of name
component Which component (indexed from zero)
port_type Which type of port
port Which port (index from zero)
reset Reset the stats.
Definition at line 906 of file mmal_vc_api.c.
References mmal_worker_get_core_stats_for_port::component_index, mmal_worker_get_core_stats_for_port_reply::component_name, mmal_worker_get_core_stats_for_port::dir, mmal_worker_get_core_stats_for_port::header, len, MMAL_FALSE, MMAL_SUCCESS, mmal_vc_get_client(), mmal_vc_sendwait_message(), MMAL_WORKER_GET_CORE_STATS_FOR_PORT, mmal_worker_get_core_stats_for_port::port_index, mmal_worker_get_core_stats_for_port::reset, mmal_worker_get_core_stats_for_port_reply::result, mmal_worker_get_core_stats_for_port_reply::stats, status, mmal_worker_get_core_stats_for_port::type, and vcos_assert.
 {
    mmal_worker_get_core_stats_for_port req;
    mmal_worker_get_core_stats_for_port_reply reply;
    MMAL_STATUS_T status;
    size_t len = sizeof(reply);
    req.component_index = component_index;
    req.port_index = port_index;
    req.type = type;
    req.reset = reset;
    req.dir = dir;
    status = mmal_vc_sendwait_message(mmal_vc_get_client(),
                                      &req.header, sizeof(req),
                                      MMAL_WORKER_GET_CORE_STATS_FOR_PORT,
                                      &reply, &len, MMAL_FALSE);
    if (status == MMAL_SUCCESS)
    {
       vcos_assert(len == sizeof(reply));
       *stats = reply.stats;
       *result = reply.result;
       strncpy(name, reply.component_name, namelen);
       name[namelen-1] = '\0';
    }
    return status;
 }
mmal_vc_get_stats()
MMAL_STATUS_T mmal_vc_get_stats (MMAL_VC_STATS_T * stats, int reset)
Definition at line 121 of file mmal_vc_api.c.
References mmal_worker_stats::header, len, MMAL_FALSE, MMAL_SUCCESS, mmal_vc_get_client(), mmal_vc_sendwait_message(), MMAL_WORKER_GET_STATS, mmal_worker_stats::reset, mmal_worker_stats::stats, status, and vcos_assert.
 {
    mmal_worker_stats msg;
    size_t len = sizeof(msg);
    msg.reset = reset;
    MMAL_STATUS_T status = mmal_vc_sendwait_message(mmal_vc_get_client(),
                                                    &msg.header, sizeof(msg),
                                                    MMAL_WORKER_GET_STATS,
                                                    &msg, &len, MMAL_FALSE);
    if (status == MMAL_SUCCESS)
    {
       vcos_assert(len == sizeof(msg));
       *stats = msg.stats;
    }
    return status;
 }
mmal_vc_get_version()
MMAL_STATUS_T mmal_vc_get_version (uint32_t * major, uint32_t * minor, uint32_t * minimum)
Definition at line 99 of file mmal_vc_api.c.
References mmal_worker_version::header, len, mmal_worker_version::major, mmal_worker_version::minimum, mmal_worker_version::minor, MMAL_EINVAL, MMAL_FALSE, MMAL_SUCCESS, mmal_vc_get_client(), mmal_vc_sendwait_message(), MMAL_WORKER_GET_VERSION, status, and vcos_verify.
 {
    mmal_worker_version msg;
    size_t len = sizeof(msg);
    MMAL_STATUS_T status;
    status = mmal_vc_sendwait_message(mmal_vc_get_client(), &msg.header, sizeof(msg),
                                      MMAL_WORKER_GET_VERSION, &msg, &len, MMAL_FALSE);
    if (status != MMAL_SUCCESS)
       return status;
    if (!vcos_verify(len == sizeof(msg)))
       return MMAL_EINVAL;
    *major = msg.major;
    *minor = msg.minor;
    *minimum = msg.minimum;
    return MMAL_SUCCESS;
 }
mmal_vc_host_log()
MMAL_STATUS_T mmal_vc_host_log (const char * msg)
Stores an arbitrary text message in a circular buffer inside the MMAL VC server. The purpose of this message is to log high level events from the host in order to diagnose problems that require multiple actions to reproduce. e.g. taking multiple pictures with different settings.
Parameters
msg The message text.
Returns
MMAL_SUCCESS if the message was logged or MMAL_ENOSYS if the API if not supported.
Definition at line 881 of file mmal_vc_api.c.
References mmal_worker_host_log::header, MMAL_EINVAL, MMAL_FALSE, MMAL_SUCCESS, mmal_vc_get_client(), mmal_vc_sendwait_message(), MMAL_WORKER_HOST_LOG, mmal_worker_host_log::msg, status, mmal_worker_reply::status, vcos_assert, vcos_min, and vcos_safe_strcpy().
 {
    MMAL_STATUS_T status = MMAL_EINVAL;
    if (msg)
    {
       mmal_worker_host_log req;
       mmal_worker_reply reply;
       size_t replylen = sizeof(reply);
       size_t msg_len = vcos_safe_strcpy(req.msg, msg, sizeof(req.msg), 0);
       /* Reduce the length if it is shorter than the max message length */
       status = mmal_vc_sendwait_message(mmal_vc_get_client(), &req.header,
             sizeof(req) - sizeof(req.msg) + vcos_min(sizeof(req.msg), msg_len + 1),
             MMAL_WORKER_HOST_LOG,
             &reply, &replylen, MMAL_FALSE);
       if (status == MMAL_SUCCESS)
       {
          vcos_assert(replylen == sizeof(reply));
          status = reply.status;
       }
    }
    return status;
 }
mmal_vc_lmk()
MMAL_STATUS_T mmal_vc_lmk (uint32_t alloc_size)
Trigger LMK action from VC, for diagnostics.
Definition at line 865 of file mmal_vc_api.c.
References mmal_worker_lmk::alloc_size, mmal_worker_lmk::header, len, MMAL_FALSE, mmal_vc_get_client(), mmal_vc_sendwait_message(), MMAL_WORKER_LMK, and status.
 {
    MMAL_STATUS_T status;
    mmal_worker_lmk req;
    mmal_worker_lmk reply;
    size_t len = sizeof(reply);
    req.alloc_size = alloc_size;
    status = mmal_vc_sendwait_message(mmal_vc_get_client(),
                                      &req.header, sizeof(req),
                                      MMAL_WORKER_LMK,
                                      &reply, &len, MMAL_FALSE);
    return status;
 }