VideoCore Library: containers/test/crc_32.c File Reference
crc_32.c File Reference
#include <stdio.h>
#include <stdint.h>
Macros
#define Error_ 1
#define Success_ 0
#define UPDC32(octet, crc)
Typedefs
typedef unsigned Boolean_T
typedef uint32_t UNS_32_BITS
Functions
uint32_t updateCRC32 (unsigned char ch, uint32_t crc)
Boolean_T crc32file (char *name, uint32_t *crc, long *charcnt)
uint32_t crc32buf (const uint8_t *buf, size_t len)
Macro Definition Documentation
Error_
#define Error_ 1
Definition at line 36 of file crc_32.c.
Referenced by crc32file().
Success_
#define Success_ 0
Definition at line 40 of file crc_32.c.
Referenced by crc32file().
UPDC32
#define UPDC32 (octet, crc)
Value:
(crc_32_tab[((crc)\
     ^ ((uint8_t)octet)) & 0xff] ^ ((crc) >> 8))
Definition at line 43 of file crc_32.c.
Referenced by crc32buf(), crc32file(), and updateCRC32().
Typedef Documentation
Boolean_T
typedef unsigned Boolean_T
Definition at line 33 of file crc_32.c.
UNS_32_BITS
typedef uint32_t UNS_32_BITS
Definition at line 64 of file crc_32.c.
Function Documentation
crc32buf()
uint32_t crc32buf (const uint8_t * buf, size_t len)
Definition at line 197 of file crc_32.c.
References crc32file(), len, main(), and UPDC32.
Referenced by TESTER_T::run().
 {
       register uint32_t oldcrc32;
       oldcrc32 = 0xFFFFFFFF;
       for ( ; len; --len, ++buf)
       {
             oldcrc32 = UPDC32(*buf, oldcrc32);
       }
       return ~oldcrc32;
 }
crc32file()
Boolean_T crc32file (char * name, uint32_t * crc, long * charcnt)
Definition at line 163 of file crc_32.c.
References Error_, NULL, Success_, and UPDC32.
Referenced by crc32buf().
 {
       register FILE *fin;
       register uint32_t oldcrc32;
       register int c;
       oldcrc32 = 0xFFFFFFFF; *charcnt = 0;
 #ifdef MSDOS
       if ((fin=fopen(name, "rb"))==NULL)
 #else
       if ((fin=fopen(name, "r"))==NULL)
 #endif
       {
             perror(name);
             return Error_;
       }
       while ((c=getc(fin))!=EOF)
       {
             ++*charcnt;
             oldcrc32 = UPDC32(c, oldcrc32);
       }
       if (ferror(fin))
       {
             perror(name);
             *charcnt = -1;
       }
       fclose(fin);
       *crc = oldcrc32 = ~oldcrc32;
       return Success_;
 }
updateCRC32()
uint32_t updateCRC32 (unsigned char ch, uint32_t crc)
Definition at line 158 of file crc_32.c.
References UPDC32.
 {
       return UPDC32(ch, crc);
 }