VideoCore Library: containers/core/containers_uri.h File Reference
containers_uri.h File Reference
#include "containers/containers.h"
Typedefs
typedef struct VC_URI_PARTS_T VC_URI_PARTS_T
Functions
VC_URI_PARTS_T * vc_uri_create (void)
void vc_uri_release (VC_URI_PARTS_T *p_uri)
void vc_uri_clear (VC_URI_PARTS_T *p_uri)
bool vc_uri_parse (VC_URI_PARTS_T *p_uri, const char *uri)
uint32_t vc_uri_build (const VC_URI_PARTS_T *p_uri, char *buffer, size_t buffer_size)
const char * vc_uri_scheme (const VC_URI_PARTS_T *p_uri)
const char * vc_uri_userinfo (const VC_URI_PARTS_T *p_uri)
const char * vc_uri_host (const VC_URI_PARTS_T *p_uri)
const char * vc_uri_port (const VC_URI_PARTS_T *p_uri)
const char * vc_uri_path (const VC_URI_PARTS_T *p_uri)
const char * vc_uri_path_extension (const VC_URI_PARTS_T *p_uri)
const char * vc_uri_fragment (const VC_URI_PARTS_T *p_uri)
uint32_t vc_uri_num_queries (const VC_URI_PARTS_T *p_uri)
void vc_uri_query (const VC_URI_PARTS_T *p_uri, uint32_t index, const char **p_name, const char **p_value)
bool vc_uri_find_query (VC_URI_PARTS_T *p_uri, uint32_t *p_index, const char *name, const char **p_value)
bool vc_uri_set_scheme (VC_URI_PARTS_T *p_uri, const char *scheme)
bool vc_uri_set_userinfo (VC_URI_PARTS_T *p_uri, const char *userinfo)
bool vc_uri_set_host (VC_URI_PARTS_T *p_uri, const char *host)
bool vc_uri_set_port (VC_URI_PARTS_T *p_uri, const char *port)
bool vc_uri_set_path (VC_URI_PARTS_T *p_uri, const char *path)
bool vc_uri_set_fragment (VC_URI_PARTS_T *p_uri, const char *fragment)
bool vc_uri_add_query (VC_URI_PARTS_T *p_uri, const char *name, const char *value)
bool vc_uri_merge (const VC_URI_PARTS_T *base_uri, VC_URI_PARTS_T *relative_uri)
Detailed Description
API for parsing and building URI strings as described in RFC3986.
Definition in file containers_uri.h.
Typedef Documentation
VC_URI_PARTS_T
typedef struct VC_URI_PARTS_T VC_URI_PARTS_T
Definition at line 41 of file containers_uri.h.
Function Documentation
vc_uri_add_query()
bool vc_uri_add_query (VC_URI_PARTS_T * p_uri, const char * name, const char * value)
Adds an query to the array. Note that the queries pointer may change after this function is called. May fail due to memory allocation failure or invalid parameters.
Parameters
p_uri Pointer to a URI parts structure.
name Unescaped query name.
value Unescaped query value. May be NULL.
Returns
True if successful, false if not.
Definition at line 997 of file containers_uri.c.
References VC_URI_QUERY_T::name, NULL, VC_URI_PARTS_T::num_queries, VC_URI_PARTS_T::queries, and VC_URI_QUERY_T::value.
 {
    VC_URI_QUERY_T *queries;
    uint32_t count;
    if (!p_uri || !name)
       return false;
    count = p_uri->num_queries;
    if (p_uri->queries)
       queries = (VC_URI_QUERY_T *)realloc(p_uri->queries, (count + 1) * sizeof(VC_URI_QUERY_T));
    else
       queries = (VC_URI_QUERY_T *)malloc(sizeof(VC_URI_QUERY_T));
    if (!queries)
       return false;
    /* Always store the pointer, in case it has changed, and even if we fail to copy name/value */
    p_uri->queries = queries;
    queries[count].name = NULL;
    queries[count].value = NULL;
    if (duplicate_string(name, &queries[count].name))
    {
       if (duplicate_string(value, &queries[count].value))
       {
          /* Successful exit path */
          p_uri->num_queries++;
          return true;
       }
       release_string(&queries[count].name);
    }
    return false;
 }
vc_uri_build()
uint32_t vc_uri_build (const VC_URI_PARTS_T * p_uri, char * buffer, size_t buffer_size)
Builds the URI component parts into a URI string. If buffer is NULL, or buffer_size is too small, nothing is written to the buffer but the required string length is still returned. buffer_size must be at least one more than the value returned.
Parameters
p_uri Pointer to a URI parts structure.
buffer Pointer to where the URI string is to be built, or NULL.
buffer_size Number of bytes available in the buffer.
Returns
The length of the URI string.
Definition at line 852 of file containers_uri.c.
 {
    uint32_t required_length;
    if (!p_uri)
       return 0;
    required_length = calculate_uri_length(p_uri);
    if (buffer && required_length < buffer_size)  /* Allow for NUL */
       build_uri(p_uri, buffer, buffer_size);
    return required_length;
 }
vc_uri_clear()
void vc_uri_clear (VC_URI_PARTS_T * p_uri)
Clear a URI structure. Any URI component strings held are released, but the structure itself is not.
Parameters
p_uri Pointer to a URI parts structure.
Definition at line 720 of file containers_uri.c.
Referenced by vc_uri_parse(), and vc_uri_release().
 {
    if (!p_uri)
       return;
    release_string(&p_uri->scheme);
    release_string(&p_uri->userinfo);
    release_string(&p_uri->host);
    release_string(&p_uri->port);
    release_string(&p_uri->path);
    release_string(&p_uri->fragment);
    if (p_uri->queries)
    {
       VC_URI_QUERY_T *queries = p_uri->queries;
       uint32_t count = p_uri->num_queries;
       while (count--)
       {
          release_string(&queries[count].name);
          release_string(&queries[count].value);
       }
       free(queries);
       p_uri->queries = NULL;
       p_uri->num_queries = 0;
    }
 }
vc_uri_create()
VC_URI_PARTS_T* vc_uri_create (void)
Create an empty URI structure.
Returns
The new URI structure.
Definition at line 706 of file containers_uri.c.
Referenced by main().
 {
    VC_URI_PARTS_T *p_uri;
    p_uri = (VC_URI_PARTS_T *)malloc(sizeof(VC_URI_PARTS_T));
    if (p_uri)
    {
       memset(p_uri, 0, sizeof(VC_URI_PARTS_T));
    }
    return p_uri;
 }
vc_uri_find_query()
bool vc_uri_find_query (VC_URI_PARTS_T * p_uri, uint32_t * p_index, const char * name, const char ** p_value)
Finds a specific query in the array. If p_index is NULL, then it is assumed the search should start at index 0, otherwise the search will start at the specified index and the index will be updated on return to point to the query which has been found. If p_value is NULL, that part of the query is not returned, otherwise it is set to the address of the value string (which may itself be NULL).
Parameters
p_uri Pointer to a URI parts structure.
p_index Index from which to start the search. May be NULL.
name Unescaped query name.
value Unescaped query value. May be NULL.
Returns
True if successful, false if not.
Definition at line 936 of file containers_uri.c.
References VC_URI_QUERY_T::name, VC_URI_PARTS_T::num_queries, VC_URI_PARTS_T::queries, and VC_URI_QUERY_T::value.
Referenced by asf_writer_open(), avi_writer_open(), binary_reader_open(), binary_writer_open(), dummy_writer_open(), mp4_writer_open(), mpga_reader_open(), ps_reader_open(), rawvideo_reader_open(), rawvideo_writer_open(), simple_writer_open(), vc_container_open_reader_with_io(), and vc_container_open_writer().
 {
    unsigned int i = p_index ? *p_index : 0;
    if (!p_uri)
       return false;
    for (; name && i < p_uri->num_queries; i++)
    {
       if (!strcmp(name, p_uri->queries[i].name))
       {
          if (p_value)
             *p_value = p_uri->queries[i].value;
          if (p_index)
             *p_index = i;
          return true;
       }
    }
    return false;
 }
vc_uri_fragment()
const char* vc_uri_fragment (const VC_URI_PARTS_T * p_uri)
Retrieves the fragment of the URI. The string is valid until either the fragment is changed or the URI is released.
Parameters
p_uri The parsed URI.
Returns
Pointer to the fragment string.
Definition at line 903 of file containers_uri.c.
References VC_URI_PARTS_T::fragment, and NULL.
 {
    return p_uri ? p_uri->fragment : NULL;
 }
vc_uri_host()
const char* vc_uri_host (const VC_URI_PARTS_T * p_uri)
Retrieves the host of the URI. The string is valid until either the host is changed or the URI is released.
Parameters
p_uri The parsed URI.
Returns
Pointer to the host string.
Definition at line 879 of file containers_uri.c.
References VC_URI_PARTS_T::host, and NULL.
 {
    return p_uri ? p_uri->host : NULL;
 }
vc_uri_merge()
bool vc_uri_merge (const VC_URI_PARTS_T * base_uri, VC_URI_PARTS_T * relative_uri)
Merge a base URI and a relative URI. In general, where the relative URI does not have a given element, the corresponding element from the base URI is used. See RFC1808. The combined URI is left in relative_uri. If the function is unsuccessful, the relative_uri may have been partially modified.
Parameters
base_uri Pointer to the base URI parts structure.
relative_uri Pointer to the relative URI parts structure.
Returns
True if successful, false if not.
Definition at line 1035 of file containers_uri.c.
References VC_URI_PARTS_T::scheme.
 {
    bool success = true;
    const char *relative_path;
    /* If scheme is already set, the URI is already absolute */
    if (relative_uri->scheme)
       return true;
    /* Otherwise, copy the base scheme */
    if (!duplicate_string(base_uri->scheme, &relative_uri->scheme))
       return false;
    /* If any of the network info is set, use the rest of the relative URI as-is */
    if (relative_uri->host || relative_uri->port || relative_uri->userinfo)
       return true;
    /* Otherwise, copy the base network info */
    if (!duplicate_string(base_uri->host, &relative_uri->host) ||
          !duplicate_string(base_uri->port, &relative_uri->port) ||
          !duplicate_string(base_uri->userinfo, &relative_uri->userinfo))
       return false;
    relative_path = relative_uri->path;
    if (!relative_path || !*relative_path)
    {
       /* No relative path (could be queries and/or fragment), so take base path */
       success = vc_uri_copy_base_path(base_uri, relative_uri);
    }
    else if (*relative_path != '/')
    {
       const char *base_path = base_uri->path;
       char *merged_path;
       char *slash;
       size_t len;
       /* Path is relative, merge in with base path */
       if (!base_path || !*base_path)
       {
          if (relative_uri->host || relative_uri->port || relative_uri->userinfo)
             base_path = "/";  /* Need a separator to split network info from path */
          else
             base_path = "";
       }
       len = strlen(base_path) + strlen(relative_path) + 1;
       /* Allocate space for largest possible combined path */
       merged_path = (char *)malloc(len);
       if (!merged_path)
          return false;
       strncpy(merged_path, base_path, len);
       slash = strrchr(merged_path, '/');  /* Note: reverse search */
       if (*relative_path == ';')
       {
          char *semi;
          /* Relative path is just parameters, so remove any base parameters in final segment */
          if (!slash)
             slash = merged_path;
          semi = strchr(slash, ';');
          if (semi)
             semi[0] = '\0';
       } else {
          /* Remove final segment */
          if (slash)
             slash[1] = '\0';
          else
             merged_path[0] = '\0';
       }
       strncat(merged_path, relative_path, len - strlen(merged_path) - 1);
       vc_uri_remove_single_dot_segments(merged_path);
       vc_uri_remove_double_dot_segments(merged_path);
       success = duplicate_string(merged_path, &relative_uri->path);
       free(merged_path);
    }
    /* Otherwise path is absolute, which can be left as-is */
    return success;
 }
vc_uri_num_queries()
uint32_t vc_uri_num_queries (const VC_URI_PARTS_T * p_uri)
Returns the number of query name/value pairs stored.
Parameters
p_uri The parsed URI.
Returns
Number of queries stored.
Definition at line 909 of file containers_uri.c.
References VC_URI_PARTS_T::num_queries.
 {
    return p_uri ? p_uri->num_queries : 0;
 }
vc_uri_parse()
bool vc_uri_parse (VC_URI_PARTS_T * p_uri, const char * uri)
Parses and unescapes a URI into the component parts.
Parameters
p_uri Pointer to a URI parts structure.
uri Pointer to a URI string to be parsed.
Returns
True if successful, false if not.
Definition at line 761 of file containers_uri.c.
References len, and vc_uri_clear().
 {
    const char *marker;
    uint32_t len;
    if (!p_uri || !uri)
       return false;
    vc_uri_clear(p_uri);
    /* URI = scheme ":" hier_part [ "?" query ] [ "#" fragment ] */
    /* Find end of scheme, or another separator */
    marker = vc_uri_find_delimiter(uri, SCHEME_DELIMITERS);
    if (*marker == ':')
    {
       len = (marker - uri);
       if (isalpha((int)*uri) && len == 1 && marker[1] == '\\')
       {
          /* Looks like a bare, absolute DOS/Windows filename with a drive letter */
          /* coverity[double_free] Pointer freed and set to NULL */
          bool ret = duplicate_string(uri, &p_uri->path);
          vc_uri_set_path_extension(p_uri);
          return ret;
       }
       p_uri->scheme = create_unescaped_string(uri, len);
       if (!p_uri->scheme)
          goto error;
       to_lower_string(p_uri->scheme);  /* Schemes should be handled case-insensitively */
       uri = marker + 1;
    }
    if (uri[0] == '/' && uri[1] == '/') /* hier-part includes authority */
    {
       const char *userinfo_end = NULL;
       /* authority = [ userinfo "@" ] host [ ":" port ] */
       uri += 2;
       marker = vc_uri_find_delimiter(uri, NETWORK_DELIMITERS);
       if (*marker == '@')
       {
          userinfo_end = marker;
          marker = vc_uri_find_delimiter(marker + 1, HOST_PORT_DELIMITERS);
       }
       if (!parse_authority(p_uri, uri, marker - uri, userinfo_end))
          goto error;
       uri = marker;
    }
    /* path */
    marker = vc_uri_find_delimiter(uri, PATH_DELIMITERS);
    len = marker - uri;
    if (len)
    {
       p_uri->path = create_unescaped_string(uri, len);
       vc_uri_set_path_extension(p_uri);
       if (!p_uri->path)
          goto error;
    }
    /* query */
    if (*marker == '?')
    {
       uri = marker + 1;
       marker = vc_uri_find_delimiter(uri, QUERY_DELIMITERS);
       if (!parse_query(p_uri, uri, marker - uri))
          goto error;
    }
    /* fragment */
    if (*marker == '#')
    {
       uri = marker + 1;
       p_uri->fragment = create_unescaped_string(uri, strlen(uri));
       if (!p_uri->fragment)
          goto error;
    }
    return true;
 error:
    vc_uri_clear(p_uri);
    return false;
 }
vc_uri_path()
const char* vc_uri_path (const VC_URI_PARTS_T * p_uri)
Retrieves the path of the URI. The string is valid until either the path is changed or the URI is released.
Parameters
p_uri The parsed URI.
Returns
Pointer to the path string.
Definition at line 891 of file containers_uri.c.
References NULL, and VC_URI_PARTS_T::path.
Referenced by binary_reader_open(), and vc_container_io_file_open().
 {
    return p_uri ? p_uri->path : NULL;
 }
vc_uri_path_extension()
const char* vc_uri_path_extension (const VC_URI_PARTS_T * p_uri)
Retrieves the extension part of the path of the URI. The string is valid until either the path is changed or the URI is released.
Parameters
p_uri The parsed URI.
Returns
Pointer to the extension string.
Definition at line 897 of file containers_uri.c.
References NULL, and VC_URI_PARTS_T::path_extension.
Referenced by asf_writer_open(), avi_writer_open(), binary_reader_open(), binary_writer_open(), dummy_writer_open(), mp4_writer_open(), mpga_reader_open(), ps_reader_open(), rawvideo_reader_open(), rawvideo_writer_open(), simple_writer_open(), vc_container_open_reader_with_io(), and vc_container_open_writer().
 {
    return p_uri ? p_uri->path_extension : NULL;
 }
vc_uri_port()
const char* vc_uri_port (const VC_URI_PARTS_T * p_uri)
Retrieves the port of the URI. The string is valid until either the port is changed or the URI is released.
Parameters
p_uri The parsed URI.
Returns
Pointer to the port string.
Definition at line 885 of file containers_uri.c.
References NULL, and VC_URI_PARTS_T::port.
 {
    return p_uri ? p_uri->port : NULL;
 }
vc_uri_query()
void vc_uri_query (const VC_URI_PARTS_T * p_uri, uint32_t index, const char ** p_name, const char ** p_value)
Retrieves a given query's name and value If either p_name or p_value are NULL, that part of the query is not returned, otherwise it is set to the address of the string (which may itself be NULL).
Parameters
p_uri The parsed URI.
index Selects the query to get.
p_name Address of a string pointer to receive query name, or NULL.
p_value Address of a string pointer to receive query value, or NULL.
Definition at line 915 of file containers_uri.c.
References index, VC_URI_QUERY_T::name, NULL, VC_URI_PARTS_T::queries, and VC_URI_QUERY_T::value.
 {
    const char *name = NULL;
    const char *value = NULL;
    if (p_uri)
    {
       if (index < p_uri->num_queries)
       {
          name = p_uri->queries[index].name;
          value = p_uri->queries[index].value;
       }
    }
    if (p_name)
       *p_name = name;
    if (p_value)
       *p_value = value;
 }
vc_uri_release()
void vc_uri_release (VC_URI_PARTS_T * p_uri)
Destroy a URI structure.
Parameters
p_uri Pointer to a URI parts structure.
Definition at line 750 of file containers_uri.c.
References vc_uri_clear().
 {
    if (!p_uri)
       return;
    vc_uri_clear(p_uri);
    free(p_uri);
 }
vc_uri_scheme()
const char* vc_uri_scheme (const VC_URI_PARTS_T * p_uri)
Retrieves the scheme of the URI. The string is valid until either the scheme is changed or the URI is released.
Parameters
p_uri The parsed URI.
Returns
Pointer to the scheme string.
Definition at line 867 of file containers_uri.c.
References NULL, and VC_URI_PARTS_T::scheme.
Referenced by rtp_reader_open(), rtsp_reader_open(), vc_container_io_http_open(), and vc_container_io_null_open().
 {
    return p_uri ? p_uri->scheme : NULL;
 }
vc_uri_set_fragment()
bool vc_uri_set_fragment (VC_URI_PARTS_T * p_uri, const char * fragment)
Sets the fragment of the URI. The string will be copied and stored in the URI, releasing and replacing any existing string. If NULL is passed, any existing string shall simply be released.
Parameters
p_uri The parsed URI.
fragment Pointer to the new fragment string, or NULL.
Returns
True if successful, false on memory allocation failure.
Definition at line 991 of file containers_uri.c.
 {
    return p_uri ? duplicate_string(fragment, &p_uri->fragment) : false;
 }
vc_uri_set_host()
bool vc_uri_set_host (VC_URI_PARTS_T * p_uri, const char * host)
Sets the host of the URI. The string will be copied and stored in the URI, releasing and replacing any existing string. If NULL is passed, any existing string shall simply be released.
Parameters
p_uri The parsed URI.
host Pointer to the new host string, or NULL.
Returns
True if successful, false on memory allocation failure.
Definition at line 971 of file containers_uri.c.
 {
    return p_uri ? duplicate_string(host, &p_uri->host) : false;
 }
vc_uri_set_path()
bool vc_uri_set_path (VC_URI_PARTS_T * p_uri, const char * path)
Sets the path of the URI. The string will be copied and stored in the URI, releasing and replacing any existing string. If NULL is passed, any existing string shall simply be released.
Parameters
p_uri The parsed URI.
path Pointer to the new path string, or NULL.
Returns
True if successful, false on memory allocation failure.
Definition at line 983 of file containers_uri.c.
 {
    bool ret = p_uri ? duplicate_string(path, &p_uri->path) : false;
    vc_uri_set_path_extension(p_uri);
    return ret;
 }
vc_uri_set_port()
bool vc_uri_set_port (VC_URI_PARTS_T * p_uri, const char * port)
Sets the port of the URI. The string will be copied and stored in the URI, releasing and replacing any existing string. If NULL is passed, any existing string shall simply be released.
Parameters
p_uri The parsed URI.
port Pointer to the new port string, or NULL.
Returns
True if successful, false on memory allocation failure.
Definition at line 977 of file containers_uri.c.
 {
    return p_uri ? duplicate_string(port, &p_uri->port) : false;
 }
vc_uri_set_scheme()
bool vc_uri_set_scheme (VC_URI_PARTS_T * p_uri, const char * scheme)
Sets the scheme of the URI. The string will be copied and stored in the URI, releasing and replacing any existing string. If NULL is passed, any existing string shall simply be released.
Parameters
p_uri The parsed URI.
scheme Pointer to the new scheme string, or NULL.
Returns
True if successful, false on memory allocation failure.
Definition at line 959 of file containers_uri.c.
 {
    return p_uri ? duplicate_string(scheme, &p_uri->scheme) : false;
 }
vc_uri_set_userinfo()
bool vc_uri_set_userinfo (VC_URI_PARTS_T * p_uri, const char * userinfo)
Sets the userinfo of the URI. The string will be copied and stored in the URI, releasing and replacing any existing string. If NULL is passed, any existing string shall simply be released.
Parameters
p_uri The parsed URI.
userinfo Pointer to the new userinfo string, or NULL.
Returns
True if successful, false on memory allocation failure.
Definition at line 965 of file containers_uri.c.
 {
    return p_uri ? duplicate_string(userinfo, &p_uri->userinfo) : false;
 }
vc_uri_userinfo()
const char* vc_uri_userinfo (const VC_URI_PARTS_T * p_uri)
Retrieves the userinfo of the URI. The string is valid until either the userinfo is changed or the URI is released.
Parameters
p_uri The parsed URI.
Returns
Pointer to the userinfo string.
Definition at line 873 of file containers_uri.c.
References NULL, and VC_URI_PARTS_T::userinfo.
 {
    return p_uri ? p_uri->userinfo : NULL;
 }