VideoCore Library: interface/mmal/core/mmal_port_clock.c File Reference
mmal_port_clock.c File Reference
#include "mmal_clock.h"
#include "mmal_logging.h"
#include "core/mmal_clock_private.h"
#include "core/mmal_port_private.h"
#include "util/mmal_util.h"
Classes
struct MMAL_PORT_CLOCK_T
Macros
#define MMAL_PORT_CLOCK_BUFFERS_MIN 16
Typedefs
typedef struct MMAL_PORT_CLOCK_T MMAL_PORT_CLOCK_T
Functions
MMAL_PORT_T * mmal_port_clock_alloc (MMAL_COMPONENT_T *component, unsigned int extra_size, MMAL_PORT_CLOCK_EVENT_CB event_cb)
void mmal_port_clock_free (MMAL_PORT_T *port)
MMAL_PORT_T ** mmal_ports_clock_alloc (MMAL_COMPONENT_T *component, unsigned int ports_num, unsigned int extra_size, MMAL_PORT_CLOCK_EVENT_CB event_cb)
void mmal_ports_clock_free (MMAL_PORT_T **ports, unsigned int ports_num)
MMAL_STATUS_T mmal_port_clock_request_add (MMAL_PORT_T *port, int64_t media_time, MMAL_PORT_CLOCK_REQUEST_CB cb, void *cb_data)
MMAL_STATUS_T mmal_port_clock_request_flush (MMAL_PORT_T *port)
MMAL_STATUS_T mmal_port_clock_reference_set (MMAL_PORT_T *port, MMAL_BOOL_T reference)
MMAL_BOOL_T mmal_port_clock_reference_get (MMAL_PORT_T *port)
MMAL_STATUS_T mmal_port_clock_active_set (MMAL_PORT_T *port, MMAL_BOOL_T active)
MMAL_BOOL_T mmal_port_clock_active_get (MMAL_PORT_T *port)
MMAL_STATUS_T mmal_port_clock_scale_set (MMAL_PORT_T *port, MMAL_RATIONAL_T scale)
MMAL_RATIONAL_T mmal_port_clock_scale_get (MMAL_PORT_T *port)
MMAL_STATUS_T mmal_port_clock_media_time_set (MMAL_PORT_T *port, int64_t media_time)
int64_t mmal_port_clock_media_time_get (MMAL_PORT_T *port)
MMAL_STATUS_T mmal_port_clock_update_threshold_set (MMAL_PORT_T *port, const MMAL_CLOCK_UPDATE_THRESHOLD_T *threshold)
MMAL_STATUS_T mmal_port_clock_update_threshold_get (MMAL_PORT_T *port, MMAL_CLOCK_UPDATE_THRESHOLD_T *threshold)
MMAL_STATUS_T mmal_port_clock_discont_threshold_set (MMAL_PORT_T *port, const MMAL_CLOCK_DISCONT_THRESHOLD_T *threshold)
MMAL_STATUS_T mmal_port_clock_discont_threshold_get (MMAL_PORT_T *port, MMAL_CLOCK_DISCONT_THRESHOLD_T *threshold)
MMAL_STATUS_T mmal_port_clock_request_threshold_set (MMAL_PORT_T *port, const MMAL_CLOCK_REQUEST_THRESHOLD_T *threshold)
MMAL_STATUS_T mmal_port_clock_request_threshold_get (MMAL_PORT_T *port, MMAL_CLOCK_REQUEST_THRESHOLD_T *threshold)
void mmal_port_clock_input_buffer_info (MMAL_PORT_T *port, const MMAL_CLOCK_BUFFER_INFO_T *info)
void mmal_port_clock_output_buffer_info (MMAL_PORT_T *port, const MMAL_CLOCK_BUFFER_INFO_T *info)
Macro Definition Documentation
MMAL_PORT_CLOCK_BUFFERS_MIN
#define MMAL_PORT_CLOCK_BUFFERS_MIN 16
Minimum number of buffers required on a clock port
Definition at line 39 of file mmal_port_clock.c.
Typedef Documentation
MMAL_PORT_CLOCK_T
typedef struct MMAL_PORT_CLOCK_T MMAL_PORT_CLOCK_T
Private clock port context
Function Documentation
mmal_port_clock_active_get()
MMAL_BOOL_T mmal_port_clock_active_get (MMAL_PORT_T * port)
Definition at line 671 of file mmal_port_clock.c.
References MMAL_PORT_CLOCK_T::clock, MMAL_PORT_PRIVATE_T::clock, mmal_clock_is_active(), and MMAL_PORT_T::priv.
 {
    return mmal_clock_is_active(port->priv->clock->clock);
 }
mmal_port_clock_active_set()
MMAL_STATUS_T mmal_port_clock_active_set (MMAL_PORT_T * port, MMAL_BOOL_T active)
Get/set the clock port's active state
Definition at line 656 of file mmal_port_clock.c.
References MMAL_PORT_CLOCK_T::clock, MMAL_PORT_PRIVATE_T::clock, MMAL_PORT_CLOCK_T::is_reference, mmal_clock_active_set(), MMAL_SUCCESS, MMAL_PORT_T::priv, and status.
 {
    MMAL_STATUS_T status;
    status = mmal_clock_active_set(port->priv->clock->clock, active);
    if (status != MMAL_SUCCESS)
       return status;
    if (port->priv->clock->is_reference)
       status = mmal_port_clock_forward_active_state(port, active);
    return status;
 }
mmal_port_clock_alloc()
MMAL_PORT_T* mmal_port_clock_alloc (MMAL_COMPONENT_T * component, unsigned int extra_size, MMAL_PORT_CLOCK_EVENT_CB event_cb)
Allocate a clock port.
Parameters
component The component requesting the alloc
extra_size Size of the port module
event_cb Clock event callback
Returns
Pointer to new clock port or NULL on failure.
Definition at line 563 of file mmal_port_clock.c.
References mmal_port_alloc(), MMAL_PORT_TYPE_CLOCK, and NULL.
 {
    MMAL_PORT_T *port;
    port = mmal_port_alloc(component, MMAL_PORT_TYPE_CLOCK,
                           extra_size + sizeof(MMAL_PORT_CLOCK_T));
    if (!port)
       return NULL;
    if (mmal_port_clock_setup(port, extra_size, event_cb) != MMAL_SUCCESS)
    {
       mmal_port_free(port);
       return NULL;
    }
    return port;
 }
mmal_port_clock_discont_threshold_get()
MMAL_STATUS_T mmal_port_clock_discont_threshold_get (MMAL_PORT_T * port, MMAL_CLOCK_DISCONT_THRESHOLD_T * threshold)
Definition at line 761 of file mmal_port_clock.c.
References MMAL_PORT_CLOCK_T::clock, MMAL_PORT_PRIVATE_T::clock, mmal_clock_discont_threshold_get(), and MMAL_PORT_T::priv.
 {
    return mmal_clock_discont_threshold_get(port->priv->clock->clock, threshold);
 }
mmal_port_clock_discont_threshold_set()
MMAL_STATUS_T mmal_port_clock_discont_threshold_set (MMAL_PORT_T * port, const MMAL_CLOCK_DISCONT_THRESHOLD_T * threshold)
Get/set the clock port's discontinuity threshold
Definition at line 745 of file mmal_port_clock.c.
References MMAL_PORT_CLOCK_T::clock, MMAL_PORT_PRIVATE_T::clock, MMAL_PORT_CLOCK_T::is_reference, mmal_clock_discont_threshold_set(), MMAL_SUCCESS, MMAL_PORT_T::priv, and status.
 {
    MMAL_STATUS_T status;
    status = mmal_clock_discont_threshold_set(port->priv->clock->clock, threshold);
    if (status != MMAL_SUCCESS)
       return status;
    if (port->priv->clock->is_reference)
       status = mmal_port_clock_forward_discont_threshold(port, threshold);
    return status;
 }
mmal_port_clock_free()
void mmal_port_clock_free (MMAL_PORT_T * port)
Free a clock port.
Parameters
port The clock port to free
Definition at line 583 of file mmal_port_clock.c.
Referenced by mmal_ports_clock_free().
 {
    mmal_port_clock_teardown(port);
    mmal_port_free(port);
 }
mmal_port_clock_input_buffer_info()
void mmal_port_clock_input_buffer_info (MMAL_PORT_T * port, const MMAL_CLOCK_BUFFER_INFO_T * info)
Provide information regarding a buffer received on the component's input/output port
Definition at line 791 of file mmal_port_clock.c.
References MMAL_PORT_CLOCK_T::buffer_info_reporting, MMAL_PORT_PRIVATE_T::clock, and MMAL_PORT_T::priv.
 {
    if (port->priv->clock->buffer_info_reporting)
       mmal_port_clock_forward_input_buffer_info(port, info);
 }
mmal_port_clock_media_time_get()
int64_t mmal_port_clock_media_time_get (MMAL_PORT_T * port)
Definition at line 716 of file mmal_port_clock.c.
References MMAL_PORT_CLOCK_T::clock, MMAL_PORT_PRIVATE_T::clock, mmal_clock_media_time_get(), and MMAL_PORT_T::priv.
 {
    return mmal_clock_media_time_get(port->priv->clock->clock);
 }
mmal_port_clock_media_time_set()
MMAL_STATUS_T mmal_port_clock_media_time_set (MMAL_PORT_T * port, int64_t media_time)
Get/set the clock port's media-time
Definition at line 698 of file mmal_port_clock.c.
References MMAL_PORT_CLOCK_T::clock, MMAL_PORT_PRIVATE_T::clock, MMAL_PORT_CLOCK_T::is_reference, LOG_DEBUG, mmal_clock_media_time_set(), MMAL_SUCCESS, MMAL_PORT_T::priv, and status.
 {
    MMAL_STATUS_T status;
    status = mmal_clock_media_time_set(port->priv->clock->clock, media_time);
    if (status != MMAL_SUCCESS)
    {
       LOG_DEBUG("clock media-time update ignored");
       return status;
    }
    if (port->priv->clock->is_reference)
       status = mmal_port_clock_forward_media_time(port, media_time);
    return status;
 }
mmal_port_clock_output_buffer_info()
void mmal_port_clock_output_buffer_info (MMAL_PORT_T * port, const MMAL_CLOCK_BUFFER_INFO_T * info)
Definition at line 798 of file mmal_port_clock.c.
References MMAL_PORT_CLOCK_T::buffer_info_reporting, MMAL_PORT_PRIVATE_T::clock, and MMAL_PORT_T::priv.
 {
    if (port->priv->clock->buffer_info_reporting)
       mmal_port_clock_forward_output_buffer_info(port, info);
 }
mmal_port_clock_reference_get()
MMAL_BOOL_T mmal_port_clock_reference_get (MMAL_PORT_T * port)
Definition at line 650 of file mmal_port_clock.c.
References MMAL_PORT_PRIVATE_T::clock, MMAL_PORT_CLOCK_T::is_reference, and MMAL_PORT_T::priv.
 {
    return port->priv->clock->is_reference;
 }
mmal_port_clock_reference_set()
MMAL_STATUS_T mmal_port_clock_reference_set (MMAL_PORT_T * port, MMAL_BOOL_T reference)
Get/set the clock port's reference state
Definition at line 643 of file mmal_port_clock.c.
References MMAL_PORT_PRIVATE_T::clock, MMAL_PORT_CLOCK_T::is_reference, MMAL_SUCCESS, and MMAL_PORT_T::priv.
 {
    port->priv->clock->is_reference = reference;
    return MMAL_SUCCESS;
 }
mmal_port_clock_request_add()
MMAL_STATUS_T mmal_port_clock_request_add (MMAL_PORT_T * port, int64_t media_time, MMAL_PORT_CLOCK_REQUEST_CB cb, void * cb_data)
Register a request with the clock port. When the specified media-time is reached, the clock port will invoke the supplied callback.
Parameters
port The clock port
media_time The media-time at which the callback should be invoked (microseconds)
cb Callback to invoke
cb_data Client-supplied callback data
Returns
MMAL_SUCCESS on success
Definition at line 629 of file mmal_port_clock.c.
References MMAL_PORT_CLOCK_T::clock, MMAL_PORT_PRIVATE_T::clock, mmal_clock_request_add(), and MMAL_PORT_T::priv.
 {
    return mmal_clock_request_add(port->priv->clock->clock, media_time,
                                  mmal_port_clock_request_cb, cb_data, (MMAL_CLOCK_VOID_FP)cb);
 }
mmal_port_clock_request_flush()
MMAL_STATUS_T mmal_port_clock_request_flush (MMAL_PORT_T * port)
Remove all previously registered clock port requests.
Parameters
port The clock port
Returns
MMAL_SUCCESS on success
Definition at line 637 of file mmal_port_clock.c.
References MMAL_PORT_CLOCK_T::clock, MMAL_PORT_PRIVATE_T::clock, mmal_clock_request_flush(), and MMAL_PORT_T::priv.
 {
    return mmal_clock_request_flush(port->priv->clock->clock);
 }
mmal_port_clock_request_threshold_get()
MMAL_STATUS_T mmal_port_clock_request_threshold_get (MMAL_PORT_T * port, MMAL_CLOCK_REQUEST_THRESHOLD_T * threshold)
Definition at line 784 of file mmal_port_clock.c.
References MMAL_PORT_CLOCK_T::clock, MMAL_PORT_PRIVATE_T::clock, mmal_clock_request_threshold_get(), and MMAL_PORT_T::priv.
 {
    return mmal_clock_request_threshold_get(port->priv->clock->clock, threshold);
 }
mmal_port_clock_request_threshold_set()
MMAL_STATUS_T mmal_port_clock_request_threshold_set (MMAL_PORT_T * port, const MMAL_CLOCK_REQUEST_THRESHOLD_T * threshold)
Get/set the clock port's request threshold
Definition at line 768 of file mmal_port_clock.c.
References MMAL_PORT_CLOCK_T::clock, MMAL_PORT_PRIVATE_T::clock, MMAL_PORT_CLOCK_T::is_reference, mmal_clock_request_threshold_set(), MMAL_SUCCESS, MMAL_PORT_T::priv, and status.
 {
    MMAL_STATUS_T status;
    status = mmal_clock_request_threshold_set(port->priv->clock->clock, threshold);
    if (status != MMAL_SUCCESS)
       return status;
    if (port->priv->clock->is_reference)
       status = mmal_port_clock_forward_request_threshold(port, threshold);
    return status;
 }
mmal_port_clock_scale_get()
MMAL_RATIONAL_T mmal_port_clock_scale_get (MMAL_PORT_T * port)
Definition at line 692 of file mmal_port_clock.c.
References MMAL_PORT_CLOCK_T::clock, MMAL_PORT_PRIVATE_T::clock, mmal_clock_scale_get(), and MMAL_PORT_T::priv.
 {
    return mmal_clock_scale_get(port->priv->clock->clock);
 }
mmal_port_clock_scale_set()
MMAL_STATUS_T mmal_port_clock_scale_set (MMAL_PORT_T * port, MMAL_RATIONAL_T scale)
Get/set the clock port's scale
Definition at line 677 of file mmal_port_clock.c.
References MMAL_PORT_CLOCK_T::clock, MMAL_PORT_PRIVATE_T::clock, MMAL_PORT_CLOCK_T::is_reference, mmal_clock_scale_set(), MMAL_SUCCESS, MMAL_PORT_T::priv, and status.
 {
    MMAL_STATUS_T status;
    status = mmal_clock_scale_set(port->priv->clock->clock, scale);
    if (status != MMAL_SUCCESS)
       return status;
    if (port->priv->clock->is_reference)
       status = mmal_port_clock_forward_scale(port, scale);
    return status;
 }
mmal_port_clock_update_threshold_get()
MMAL_STATUS_T mmal_port_clock_update_threshold_get (MMAL_PORT_T * port, MMAL_CLOCK_UPDATE_THRESHOLD_T * threshold)
Definition at line 738 of file mmal_port_clock.c.
References MMAL_PORT_CLOCK_T::clock, MMAL_PORT_PRIVATE_T::clock, mmal_clock_update_threshold_get(), and MMAL_PORT_T::priv.
 {
    return mmal_clock_update_threshold_get(port->priv->clock->clock, threshold);
 }
mmal_port_clock_update_threshold_set()
MMAL_STATUS_T mmal_port_clock_update_threshold_set (MMAL_PORT_T * port, const MMAL_CLOCK_UPDATE_THRESHOLD_T * threshold)
Get/set the clock port's update threshold
Definition at line 722 of file mmal_port_clock.c.
References MMAL_PORT_CLOCK_T::clock, MMAL_PORT_PRIVATE_T::clock, MMAL_PORT_CLOCK_T::is_reference, mmal_clock_update_threshold_set(), MMAL_SUCCESS, MMAL_PORT_T::priv, and status.
 {
    MMAL_STATUS_T status;
    status = mmal_clock_update_threshold_set(port->priv->clock->clock, threshold);
    if (status != MMAL_SUCCESS)
       return status;
    if (port->priv->clock->is_reference)
       status = mmal_port_clock_forward_update_threshold(port, threshold);
    return status;
 }
mmal_ports_clock_alloc()
MMAL_PORT_T** mmal_ports_clock_alloc (MMAL_COMPONENT_T * component, unsigned int ports_num, unsigned int extra_size, MMAL_PORT_CLOCK_EVENT_CB event_cb)
Allocate an array of clock ports.
Parameters
component The component requesting the alloc
ports_num Number of ports to allocate
extra_size Size of the port module
event_cb Clock event callback
Returns
Pointer to a new array of clock ports or NULL on failure.
Definition at line 590 of file mmal_port_clock.c.
References MMAL_PORT_TYPE_CLOCK, mmal_ports_alloc(), and NULL.
 {
    unsigned int i;
    MMAL_PORT_T **ports;
    ports = mmal_ports_alloc(component, ports_num, MMAL_PORT_TYPE_CLOCK,
                             extra_size + sizeof(MMAL_PORT_CLOCK_T));
    if (!ports)
       return NULL;
    for (i = 0; i < ports_num; i++)
    {
       if (mmal_port_clock_setup(ports[i], extra_size, event_cb) != MMAL_SUCCESS)
          break;
    }
    if (i != ports_num)
    {
       for (ports_num = i, i = 0; i < ports_num; i++)
          mmal_port_clock_free(ports[i]);
       vcos_free(ports);
       return NULL;
    }
    return ports;
 }
mmal_ports_clock_free()
void mmal_ports_clock_free (MMAL_PORT_T ** ports, unsigned int ports_num)
Free an array of clock ports.
Parameters
ports The clock ports to free
ports_num Number of ports to free
Definition at line 619 of file mmal_port_clock.c.
References mmal_port_clock_free(), and vcos_free().
 {
    unsigned int i;
    for (i = 0; i < ports_num; i++)
       mmal_port_clock_free(ports[i]);
    vcos_free(ports);
 }