VideoCore Library: host_applications/linux/apps/hello_pi/hello_fft/hello_fft_2d.c File Reference
hello_fft_2d.c File Reference
#include <string.h>
#include <stdio.h>
#include <time.h>
#include "gpu_fft_trans.h"
#include "hello_fft_2d_bitmap.h"
Macros
#define log2_N 9
#define N (1<<log2_N)
#define GPU_FFT_ROW(fft, io, y) ((fft)->io+(fft)->step*(y))
Functions
unsigned Microseconds (void)
int main (int argc, char *argv[])
Macro Definition Documentation
GPU_FFT_ROW
#define GPU_FFT_ROW (fft, io, y) ((fft)->io+(fft)->step*(y))
Definition at line 39 of file hello_fft_2d.c.
Referenced by main().
log2_N
#define log2_N 9
Definition at line 36 of file hello_fft_2d.c.
Referenced by gpu_fft_prepare(), and main().
N
#define N (1<<log2_N)
Definition at line 37 of file hello_fft_2d.c.
Referenced by main().
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 47 of file hello_fft_2d.c.
References BI_RGB, BITMAPFILEHEADER, BITMAPINFOHEADER, gpu_fft_execute(), gpu_fft_prepare(), gpu_fft_release(), GPU_FFT_REV, GPU_FFT_ROW, gpu_fft_trans_execute(), gpu_fft_trans_prepare(), gpu_fft_trans_release(), GPU_FFT::in, log2_N, mbox_open(), Microseconds(), N, and GPU_FFT::out.
{
     int x, y, ret, mb = mbox_open();
     unsigned t[4];
     struct GPU_FFT_COMPLEX *row;
     struct GPU_FFT_TRANS *trans;
     struct GPU_FFT *fft_pass[2];
     BITMAPFILEHEADER bfh;
     BITMAPINFOHEADER bih;
     // Create Windows bitmap file
     FILE *fp = fopen("hello_fft_2d.bmp", "wb");
     if (!fp) return -666;
     // Write bitmap header
     memset(&bfh, 0, sizeof(bfh));
     bfh.bfType = 0x4D42; //"BM"
     bfh.bfSize = N*N*3;
     bfh.bfOffBits = sizeof(bfh) + sizeof(bih);
     fwrite(&bfh, sizeof(bfh), 1, fp);
     // Write bitmap info
     memset(&bih, 0, sizeof(bih));
     bih.biSize = sizeof(bih);
     bih.biWidth = N;
     bih.biHeight = N;
     bih.biPlanes = 1;
     bih.biBitCount = 24;
     bih.biCompression = BI_RGB;
     fwrite(&bih, sizeof(bih), 1, fp);
     // Prepare 1st FFT pass
     ret = gpu_fft_prepare(mb, log2_N, GPU_FFT_REV, N, fft_pass+0);
     if (ret) {
         return ret;
     }
     // Prepare 2nd FFT pass
     ret = gpu_fft_prepare(mb, log2_N, GPU_FFT_REV, N, fft_pass+1);
     if (ret) {
         gpu_fft_release(fft_pass[0]);
         return ret;
     }
     // Transpose from 1st pass output to 2nd pass input
     ret = gpu_fft_trans_prepare(mb, fft_pass[0], fft_pass[1], &trans);
     if (ret) {
         gpu_fft_release(fft_pass[0]);
         gpu_fft_release(fft_pass[1]);
         return ret;
     }
     // Clear input array
     for (y=0; y<N; y++) {
         row = GPU_FFT_ROW(fft_pass[0], in, y);
         for (x=0; x<N; x++) row[x].re = row[x].im = 0;
     }
     // Setup input data
     GPU_FFT_ROW(fft_pass[0], in,   2)[  2].re = 60;
     GPU_FFT_ROW(fft_pass[0], in, N-2)[N-2].re = 60;
     // ==> FFT() ==> T() ==> FFT() ==>
     usleep(1); /* yield to OS */   t[0] = Microseconds();
     gpu_fft_execute(fft_pass[0]);  t[1] = Microseconds();
     gpu_fft_trans_execute(trans);  t[2] = Microseconds();
     gpu_fft_execute(fft_pass[1]);  t[3] = Microseconds();
     // Write output to bmp file
     for (y=0; y<N; y++) {
         row = GPU_FFT_ROW(fft_pass[1], out, y);
         for (x=0; x<N; x++) {
             fputc(128+row[x].re, fp); // blue
             fputc(128+row[x].re, fp); // green
             fputc(128+row[x].re, fp); // red
         }
     }
     printf( "1st FFT   %6d usecs\n"
             "Transpose %6d usecs\n"
             "2nd FFT   %6d usecs\n",
             t[3]-t[2], t[2]-t[1], t[1]-t[0]);
     // Clean-up properly.  Videocore memory lost if not freed !
     gpu_fft_release(fft_pass[0]);
     gpu_fft_release(fft_pass[1]);
     gpu_fft_trans_release(trans);
     return 0;
 }
Microseconds()
unsigned Microseconds (void)
Definition at line 41 of file hello_fft_2d.c.
Referenced by main().
{
     struct timespec ts;
     clock_gettime(CLOCK_REALTIME, &ts);
     return ts.tv_sec*1000000 + ts.tv_nsec/1000;
 }