VideoCore Library: host_applications/linux/apps/hello_pi/hello_tiger/main.c File Reference
main.c File Reference
Tiger sample application. Resizing the application window rerenders the tiger in the new resolution. Pressing 1,2,3 or 4 sets pixel zoom factor, mouse moves inside the zoomed image (mouse move works on OpenGL >= 1.2).
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <assert.h>
#include <string.h>
#include "VG/openvg.h"
#include "VG/vgu.h"
#include "EGL/egl.h"
#include "revision.h"
#include "tiger.h"
Classes
struct PathData
struct PS
Macros
#define UNREF(X) ((void)(X))
Functions
PS * PS_construct (const char *commands, int commandCount, const float *points, int pointCount)
void PS_destruct (PS *ps)
void PS_render (PS *ps)
void render (int w, int h)
void init (NativeWindowType window)
void deinit (void)
Variables
const float aspectRatio = 612.0f / 792.0f
int renderWidth = 0
int renderHeight = 0
EGLDisplay egldisplay
EGLConfig eglconfig
EGLSurface eglsurface
EGLContext eglcontext
PS * tiger = NULL
Detailed Description
Tiger sample application. Resizing the application window rerenders the tiger in the new resolution. Pressing 1,2,3 or 4 sets pixel zoom factor, mouse moves inside the zoomed image (mouse move works on OpenGL >= 1.2).
Note
Definition in file main.c.
Macro Definition Documentation
UNREF
#define UNREF (X) ((void)(X))
Definition at line 41 of file main.c.
Referenced by PS_construct().
Function Documentation
deinit()
void deinit (void)
Definition at line 382 of file main.c.
References aspectRatio, assert(), bcm_host_init(), DISPMANX_PROTECTION_NONE, EGL_NO_CONTEXT, EGL_NO_SURFACE, EGL_SUCCESS, egldisplay, eglGetError(), eglMakeCurrent(), eglReleaseThread(), eglTerminate(), EGL_DISPMANX_WINDOW_T::element, get_processor_id(), graphics_get_display_size(), tag_VC_RECT_T::height, EGL_DISPMANX_WINDOW_T::height, init(), main(), NULL, PROCESSOR_BCM2838, PS_destruct(), render(), vc_dispmanx_display_open(), vc_dispmanx_element_add(), vc_dispmanx_update_start(), vc_dispmanx_update_submit_sync(), tag_VC_RECT_T::width, EGL_DISPMANX_WINDOW_T::width, tag_VC_RECT_T::x, and tag_VC_RECT_T::y.
 {
     PS_destruct(tiger);
     eglMakeCurrent(egldisplay, EGL_NO_SURFACE, EGL_NO_SURFACE, EGL_NO_CONTEXT);
     assert(eglGetError() == EGL_SUCCESS);
     eglTerminate(egldisplay);
     assert(eglGetError() == EGL_SUCCESS);
     eglReleaseThread();
 }
init()
void init (NativeWindowType window)
Definition at line 346 of file main.c.
References assert(), EGL_ALPHA_SIZE, EGL_BLUE_SIZE, EGL_DEFAULT_DISPLAY, EGL_DONT_CARE, EGL_GREEN_SIZE, EGL_LUMINANCE_SIZE, EGL_NONE, EGL_OPENVG_API, EGL_RED_SIZE, EGL_SAMPLES, EGL_SUCCESS, EGL_SURFACE_TYPE, EGL_WINDOW_BIT, eglBindAPI(), eglChooseConfig(), eglconfig, eglcontext, eglCreateContext(), eglCreateWindowSurface(), egldisplay, eglGetDisplay(), eglGetError(), eglInitialize(), eglMakeCurrent(), eglsurface, NULL, PS_construct(), tigerCommandCount, tigerCommands, tigerPointCount, and tigerPoints.
Referenced by deinit().
 {
     static const EGLint s_configAttribs[] =
     {
         EGL_RED_SIZE,       8,
         EGL_GREEN_SIZE,     8,
         EGL_BLUE_SIZE,      8,
         EGL_ALPHA_SIZE,     8,
         EGL_LUMINANCE_SIZE, EGL_DONT_CARE,          //EGL_DONT_CARE
         EGL_SURFACE_TYPE,   EGL_WINDOW_BIT,
         EGL_SAMPLES,        1,
         EGL_NONE
     };
     EGLint numconfigs;
     egldisplay = eglGetDisplay(EGL_DEFAULT_DISPLAY);
     eglInitialize(egldisplay, NULL, NULL);
     assert(eglGetError() == EGL_SUCCESS);
     eglBindAPI(EGL_OPENVG_API);
     eglChooseConfig(egldisplay, s_configAttribs, &eglconfig, 1, &numconfigs);
     assert(eglGetError() == EGL_SUCCESS);
     assert(numconfigs == 1);
     eglsurface = eglCreateWindowSurface(egldisplay, eglconfig, window, NULL);
     assert(eglGetError() == EGL_SUCCESS);
     eglcontext = eglCreateContext(egldisplay, eglconfig, NULL, NULL);
     assert(eglGetError() == EGL_SUCCESS);
     eglMakeCurrent(egldisplay, eglsurface, eglsurface, eglcontext);
     assert(eglGetError() == EGL_SUCCESS);
     tiger = PS_construct(tigerCommands, tigerCommandCount, tigerPoints, tigerPointCount);
 }
PS_construct()
PS* PS_construct (const char * commands, int commandCount, const float * points, int pointCount)
Definition at line 91 of file main.c.
References assert(), PathData::m_capStyle, PathData::m_fillPaint, PathData::m_fillRule, PathData::m_joinStyle, PathData::m_miterLimit, PS::m_numPaths, PathData::m_paintMode, PathData::m_path, PS::m_paths, PathData::m_strokePaint, PathData::m_strokeWidth, UNREF, VG_ABSOLUTE, VG_CAP_BUTT, VG_CAP_ROUND, VG_CAP_SQUARE, VG_CLOSE_PATH, VG_CUBIC_TO, VG_EVEN_ODD, VG_FILL_PATH, VG_JOIN_BEVEL, VG_JOIN_MITER, VG_JOIN_ROUND, VG_LINE_TO, VG_MOVE_TO, VG_NON_ZERO, VG_PAINT_COLOR, VG_PAINT_TYPE, VG_PAINT_TYPE_COLOR, VG_PATH_CAPABILITY_ALL, VG_PATH_DATATYPE_F, VG_PATH_FORMAT_STANDARD, VG_STROKE_PATH, vgAppendPathData(), vgCreatePaint(), vgCreatePath(), vgSetParameterfv(), and vgSetParameteri().
Referenced by init().
 {
     PS* ps = (PS*)malloc(sizeof(PS));
     int p = 0;
     int c = 0;
     int i = 0;
     int paths = 0;
     int maxElements = 0;
     unsigned char* cmd;
     UNREF(pointCount);
     while(c < commandCount)
     {
         int elements, e;
         c += 4;
         p += 8;
         elements = (int)points[p++];
         assert(elements > 0);
         if(elements > maxElements)
             maxElements = elements;
         for(e=0;e<elements;e++)
         {
             switch(commands[c])
             {
             case 'M': p += 2; break;
             case 'L': p += 2; break;
             case 'C': p += 6; break;
             case 'E': break;
             default:
                 assert(0);      //unknown command
             }
             c++;
         }
         paths++;
     }
     ps->m_numPaths = paths;
     ps->m_paths = (PathData*)malloc(paths * sizeof(PathData));
     cmd = (unsigned char*)malloc(maxElements);
     i = 0;
     p = 0;
     c = 0;
     while(c < commandCount)
     {
         int elements, startp, e;
         float color[4];
         //fill type
         int paintMode = 0;
         ps->m_paths[i].m_fillRule = VG_NON_ZERO;
         switch( commands[c] )
         {
         case 'N':
             break;
         case 'F':
             ps->m_paths[i].m_fillRule = VG_NON_ZERO;
             paintMode |= VG_FILL_PATH;
             break;
         case 'E':
             ps->m_paths[i].m_fillRule = VG_EVEN_ODD;
             paintMode |= VG_FILL_PATH;
             break;
         default:
             assert(0);      //unknown command
         }
         c++;
         //stroke
         switch( commands[c] )
         {
         case 'N':
             break;
         case 'S':
             paintMode |= VG_STROKE_PATH;
             break;
         default:
             assert(0);      //unknown command
         }
         ps->m_paths[i].m_paintMode = (VGPaintMode)paintMode;
         c++;
         //line cap
         switch( commands[c] )
         {
         case 'B':
             ps->m_paths[i].m_capStyle = VG_CAP_BUTT;
             break;
         case 'R':
             ps->m_paths[i].m_capStyle = VG_CAP_ROUND;
             break;
         case 'S':
             ps->m_paths[i].m_capStyle = VG_CAP_SQUARE;
             break;
         default:
             assert(0);      //unknown command
         }
         c++;
         //line join
         switch( commands[c] )
         {
         case 'M':
             ps->m_paths[i].m_joinStyle = VG_JOIN_MITER;
             break;
         case 'R':
             ps->m_paths[i].m_joinStyle = VG_JOIN_ROUND;
             break;
         case 'B':
             ps->m_paths[i].m_joinStyle = VG_JOIN_BEVEL;
             break;
         default:
             assert(0);      //unknown command
         }
         c++;
         //the rest of stroke attributes
         ps->m_paths[i].m_miterLimit = points[p++];
         ps->m_paths[i].m_strokeWidth = points[p++];
         //paints
         color[0] = points[p++];
         color[1] = points[p++];
         color[2] = points[p++];
         color[3] = 1.0f;
         ps->m_paths[i].m_strokePaint = vgCreatePaint();
         vgSetParameteri(ps->m_paths[i].m_strokePaint, VG_PAINT_TYPE, VG_PAINT_TYPE_COLOR);
         vgSetParameterfv(ps->m_paths[i].m_strokePaint, VG_PAINT_COLOR, 4, color);
         color[0] = points[p++];
         color[1] = points[p++];
         color[2] = points[p++];
         color[3] = 1.0f;
         ps->m_paths[i].m_fillPaint = vgCreatePaint();
         vgSetParameteri(ps->m_paths[i].m_fillPaint, VG_PAINT_TYPE, VG_PAINT_TYPE_COLOR);
         vgSetParameterfv(ps->m_paths[i].m_fillPaint, VG_PAINT_COLOR, 4, color);
         //read number of elements
         elements = (int)points[p++];
         assert(elements > 0);
         startp = p;
         for(e=0;e<elements;e++)
         {
             switch( commands[c] )
             {
             case 'M':
                 cmd[e] = VG_MOVE_TO | VG_ABSOLUTE;
                 p += 2;
                 break;
             case 'L':
                 cmd[e] = VG_LINE_TO | VG_ABSOLUTE;
                 p += 2;
                 break;
             case 'C':
                 cmd[e] = VG_CUBIC_TO | VG_ABSOLUTE;
                 p += 6;
                 break;
             case 'E':
                 cmd[e] = VG_CLOSE_PATH;
                 break;
             default:
                 assert(0);      //unknown command
             }
             c++;
         }
         ps->m_paths[i].m_path = vgCreatePath(VG_PATH_FORMAT_STANDARD, VG_PATH_DATATYPE_F, 1.0f, 0.0f, 0, 0, (unsigned int)VG_PATH_CAPABILITY_ALL);
         vgAppendPathData(ps->m_paths[i].m_path, elements, cmd, points + startp);
         i++;
     }
     free(cmd);
     return ps;
 }
PS_destruct()
void PS_destruct (PS * ps)
Definition at line 266 of file main.c.
References assert(), PathData::m_fillPaint, PS::m_numPaths, PathData::m_path, PS::m_paths, PathData::m_strokePaint, vgDestroyPaint(), and vgDestroyPath().
Referenced by deinit().
 {
     int i;
     assert(ps);
     for(i=0;i<ps->m_numPaths;i++)
     {
         vgDestroyPaint(ps->m_paths[i].m_fillPaint);
         vgDestroyPaint(ps->m_paths[i].m_strokePaint);
         vgDestroyPath(ps->m_paths[i].m_path);
     }
     free(ps->m_paths);
     free(ps);
 }
PS_render()
void PS_render (PS * ps)
Definition at line 280 of file main.c.
References assert(), PathData::m_capStyle, PathData::m_fillPaint, PathData::m_fillRule, PathData::m_joinStyle, PathData::m_miterLimit, PS::m_numPaths, PathData::m_paintMode, PathData::m_path, PS::m_paths, PathData::m_strokePaint, PathData::m_strokeWidth, VG_BLEND_MODE, VG_BLEND_SRC_OVER, VG_FILL_PATH, VG_FILL_RULE, VG_NO_ERROR, VG_STROKE_CAP_STYLE, VG_STROKE_JOIN_STYLE, VG_STROKE_LINE_WIDTH, VG_STROKE_MITER_LIMIT, VG_STROKE_PATH, vgDrawPath(), vgGetError(), vgSetf(), vgSeti(), and vgSetPaint().
Referenced by render().
 {
     int i;
     assert(ps);
     vgSeti(VG_BLEND_MODE, VG_BLEND_SRC_OVER);
     for(i=0;i<ps->m_numPaths;i++)
     {
         vgSeti(VG_FILL_RULE, ps->m_paths[i].m_fillRule);
         vgSetPaint(ps->m_paths[i].m_fillPaint, VG_FILL_PATH);
         if(ps->m_paths[i].m_paintMode & VG_STROKE_PATH)
         {
             vgSetf(VG_STROKE_LINE_WIDTH, ps->m_paths[i].m_strokeWidth);
             vgSeti(VG_STROKE_CAP_STYLE, ps->m_paths[i].m_capStyle);
             vgSeti(VG_STROKE_JOIN_STYLE, ps->m_paths[i].m_joinStyle);
             vgSetf(VG_STROKE_MITER_LIMIT, ps->m_paths[i].m_miterLimit);
             vgSetPaint(ps->m_paths[i].m_strokePaint, VG_STROKE_PATH);
         }
         vgDrawPath(ps->m_paths[i].m_path, ps->m_paths[i].m_paintMode);
     }
     assert(vgGetError() == VG_NO_ERROR);
 }
render()
void render (int w, int h)
Definition at line 309 of file main.c.
References assert(), EGL_SUCCESS, egldisplay, eglGetError(), eglsurface, eglSwapBuffers(), PS_render(), renderHeight, renderWidth, tigerMaxX, tigerMaxY, tigerMinX, tigerMinY, VG_CLEAR_COLOR, VG_NO_ERROR, vgClear(), vgGetError(), vgLoadIdentity(), vgRotate(), vgScale(), vgSetfv(), and vgTranslate().
Referenced by deinit().
 {
 #ifndef __RASPBERRYPI__
     if(renderWidth != w || renderHeight != h)
 #endif
     {
         float clearColor[4] = {1,1,1,1};
         float scale = w / (tigerMaxX - tigerMinX);
         eglSwapBuffers(egldisplay, eglsurface); //force EGL to recognize resize
         vgSetfv(VG_CLEAR_COLOR, 4, clearColor);
         vgClear(0, 0, w, h);
         vgLoadIdentity();
 #ifdef __RASPBERRYPI__
                 vgTranslate(w * 0.5f, h * 0.5f);
                 vgRotate(rotateN);
                 vgTranslate(-w * 0.5f, -h * 0.5f);
 #endif
         vgScale(scale, scale);
         vgTranslate(-tigerMinX, -tigerMinY + 0.5f * (h / scale - (tigerMaxY - tigerMinY)));
         PS_render(tiger);
         assert(vgGetError() == VG_NO_ERROR);
         renderWidth = w;
         renderHeight = h;
     }
 #ifndef __RASPBERRYPI__
     eglSwapBuffers(egldisplay, eglsurface);
     assert(eglGetError() == EGL_SUCCESS);
 #endif
 }
Variable Documentation
aspectRatio
const float aspectRatio = 612.0f / 792.0f
Definition at line 62 of file main.c.
Referenced by deinit().
eglconfig
EGLConfig eglconfig
Definition at line 66 of file main.c.
Referenced by init().
eglcontext
EGLContext eglcontext
Definition at line 68 of file main.c.
Referenced by init().
egldisplay
EGLDisplay egldisplay
Definition at line 65 of file main.c.
Referenced by deinit(), init(), and render().
eglsurface
EGLSurface eglsurface
Definition at line 67 of file main.c.
Referenced by init(), and render().
renderHeight
int renderHeight = 0
Definition at line 64 of file main.c.
Referenced by render().
renderWidth
int renderWidth = 0
Definition at line 63 of file main.c.
Referenced by render().
tiger
PS* tiger = NULL
Definition at line 305 of file main.c.