VideoCore Library: interface/mmal/openmaxil/mmalomx_roles.c File Reference
mmalomx_roles.c File Reference
#include "mmalomx.h"
#include "mmalomx_roles.h"
#include "mmalomx_registry.h"
#include "mmalomx_logging.h"
Functions
const char * mmalomx_role_to_name (MMALOMX_ROLE_T role)
MMALOMX_ROLE_T mmalomx_role_from_name (const char *name)
OMX_ERRORTYPE mmalomx_role_set (MMALOMX_COMPONENT_T *component, const char *name)
Function Documentation
mmalomx_role_from_name()
MMALOMX_ROLE_T mmalomx_role_from_name (const char * name)
Definition at line 70 of file mmalomx_roles.c.
Referenced by mmalomx_role_set().
 {
    unsigned int i;
    for (i = 0; mmalomx_roles[i].name; i++)
       if (!strcmp(mmalomx_roles[i].name, name))
          break;
    return mmalomx_roles[i].role;
 }
mmalomx_role_set()
OMX_ERRORTYPE mmalomx_role_set (MMALOMX_COMPONENT_T * component, const char * name)
Definition at line 146 of file mmalomx_roles.c.
References encoding, MMAL_ENCODING_UNKNOWN, MMAL_ES_TYPE_UNKNOWN, mmalomx_registry_component_supports_role(), mmalomx_role_from_name(), OMX_ErrorUnsupportedSetting, MMALOMX_COMPONENT_T::registry_id, role, and MMALOMX_COMPONENT_T::role.
 {
    const MMALOMX_ROLE_T role = mmalomx_role_from_name(name);
    MMAL_FOURCC_T encoding = MMAL_ENCODING_UNKNOWN;
    MMAL_ES_TYPE_T es_type = MMAL_ES_TYPE_UNKNOWN;
    unsigned int port;
    MMAL_ES_FORMAT_T *format;
    if (!role || !mmalomx_registry_component_supports_role(component->registry_id, role))
       return OMX_ErrorUnsupportedSetting;
    component->role = role;
    mmalomx_format_encoding_from_role(role, &encoding, &es_type, &port);
    if (encoding == MMAL_ENCODING_UNKNOWN)
       return OMX_ErrorNone;
    format = component->ports[port].mmal->format;
    format->type = es_type;
    format->encoding = encoding;
    format->bitrate = 64000;
    switch (es_type)
    {
    case MMAL_ES_TYPE_VIDEO:
       format->es->video.width = 176;
       format->es->video.height = 144;
       format->es->video.frame_rate.num = 15;
       format->es->video.frame_rate.den = 1;
       break;
    default:
       break;
    }
    switch (role)
    {
    case MMALOMX_ROLE_VIDEO_DECODER_H263:
    case MMALOMX_ROLE_VIDEO_ENCODER_H263:
       component->ports[port].format_param.h263.eProfile = OMX_VIDEO_H263ProfileBaseline;
       component->ports[port].format_param.h263.eLevel = OMX_VIDEO_H263Level10;
       component->ports[port].format_param.h263.bPLUSPTYPEAllowed = OMX_FALSE;
       component->ports[port].format_param.h263.bForceRoundingTypeToZero = OMX_TRUE;
       break;
    case MMALOMX_ROLE_VIDEO_DECODER_MPEG4:
    case MMALOMX_ROLE_VIDEO_ENCODER_MPEG4:
       component->ports[port].format_param.mpeg4.eProfile = OMX_VIDEO_MPEG4ProfileSimple;
       component->ports[port].format_param.mpeg4.eLevel = OMX_VIDEO_MPEG4Level1;
       break;
    case MMALOMX_ROLE_VIDEO_DECODER_AVC:
    case MMALOMX_ROLE_VIDEO_ENCODER_AVC:
       component->ports[port].format_param.avc.eProfile = OMX_VIDEO_AVCProfileBaseline;
       component->ports[port].format_param.avc.eLevel = OMX_VIDEO_AVCLevel1;
       break;
    case MMALOMX_ROLE_VIDEO_DECODER_WMV:
       component->ports[port].format_param.wmv.eFormat = OMX_VIDEO_WMVFormat9;
       break;
    default:
       break;
    }
    if (mmal_port_format_commit(component->ports[port].mmal) != MMAL_SUCCESS)
       LOG_ERROR("failed to commit format to %s for role %s",
                 component->ports[port].mmal->name, name);
    return OMX_ErrorNone;
 }
mmalomx_role_to_name()
const char* mmalomx_role_to_name (MMALOMX_ROLE_T role)
Definition at line 61 of file mmalomx_roles.c.
Referenced by OMX_GetRolesOfComponent().
 {
     unsigned int i;
     for (i = 0; mmalomx_roles[i].name; i++)
        if (mmalomx_roles[i].role == role)
           break;
     return mmalomx_roles[i].name;
 }
Variable Documentation
name
const char* name
Definition at line 34 of file mmalomx_roles.c.
role
MMALOMX_ROLE_T role
Definition at line 35 of file mmalomx_roles.c.
Referenced by mmalomx_role_set(), OMX_GetComponentsOfRole(), and OMX_GetRolesOfComponent().