VideoCore Library: interface/vcos/vcos_event_flags.h File Reference
vcos_event_flags.h File Reference
#include "interface/vcos/vcos_types.h"
#include "vcos.h"
Macros
#define VCOS_EVENT_FLAGS_SUSPEND VCOS_SUSPEND
#define VCOS_EVENT_FLAGS_NO_SUSPEND VCOS_NO_SUSPEND
Typedefs
typedef VCOS_OPTION VCOS_EVENTGROUP_OPERATION_T
Functions
VCOS_INLINE_DECL VCOS_STATUS_T vcos_event_flags_create (VCOS_EVENT_FLAGS_T *flags, const char *name)
VCOS_INLINE_DECL void vcos_event_flags_set (VCOS_EVENT_FLAGS_T *flags, VCOS_UNSIGNED events, VCOS_OPTION op)
VCOS_INLINE_DECL VCOS_STATUS_T vcos_event_flags_get (VCOS_EVENT_FLAGS_T *flags, VCOS_UNSIGNED requested_events, VCOS_OPTION op, VCOS_UNSIGNED ms_suspend, VCOS_UNSIGNED *retrieved_events)
VCOS_INLINE_DECL void vcos_event_flags_delete (VCOS_EVENT_FLAGS_T *)
Detailed Description
Defines event flags API.
Similar to Nucleus event groups.
These have the same semantics as Nucleus event groups and ThreadX event flags. As such, they are quite complex internally; if speed is important they might not be your best choice.
Definition in file vcos_event_flags.h.
Macro Definition Documentation
VCOS_EVENT_FLAGS_NO_SUSPEND
#define VCOS_EVENT_FLAGS_NO_SUSPEND VCOS_NO_SUSPEND
Definition at line 44 of file vcos_event_flags.h.
VCOS_EVENT_FLAGS_SUSPEND
#define VCOS_EVENT_FLAGS_SUSPEND VCOS_SUSPEND
Definition at line 43 of file vcos_event_flags.h.
Referenced by ilclient_flush_tunnels().
Typedef Documentation
VCOS_EVENTGROUP_OPERATION_T
typedef VCOS_OPTION VCOS_EVENTGROUP_OPERATION_T
Definition at line 45 of file vcos_event_flags.h.
Function Documentation
vcos_event_flags_create()
VCOS_INLINE_DECL VCOS_STATUS_T vcos_event_flags_create (VCOS_EVENT_FLAGS_T * flags, const char * name)
Create an event flags instance.
Parameters
flags Pointer to event flags instance, filled in on return.
name Name for the event flags, used for debug.
Returns
VCOS_SUCCESS if succeeded.
vcos_event_flags_delete()
VCOS_INLINE_DECL void vcos_event_flags_delete (VCOS_EVENT_FLAGS_T *)
Delete an event flags instance.
Referenced by ilclient_cleanup_components().
vcos_event_flags_get()
VCOS_INLINE_DECL VCOS_STATUS_T vcos_event_flags_get (VCOS_EVENT_FLAGS_T * flags, VCOS_UNSIGNED requested_events, VCOS_OPTION op, VCOS_UNSIGNED ms_suspend, VCOS_UNSIGNED * retrieved_events)
Retrieve some events.
Waits until the specified events have been set.
Parameters
flags Instance to wait on
requested_events The bitmask to wait for
op VCOS_OR - get any; VCOS_AND - get all.
ms_suspend How long to wait, in milliseconds
retrieved_events the events actually retrieved.
Returns
VCOS_SUCCESS if events were retrieved. VCOS_EAGAIN if the timeout expired.
Referenced by ilclient_disable_port_buffers(), ilclient_get_input_buffer(), and ilclient_get_output_buffer().
vcos_event_flags_set()
VCOS_INLINE_DECL void vcos_event_flags_set (VCOS_EVENT_FLAGS_T * flags, VCOS_UNSIGNED events, VCOS_OPTION op)
Set some events.
Parameters
flags Instance to set flags on
events Bitmask of the flags to actually set
op How the flags should be set. VCOS_OR will OR in the flags; VCOS_AND will AND them in, possibly clearing existing flags.