VideoCore Library: interface/vcos/vcos_cmd.h File Reference
vcos_cmd.h File Reference
#include "interface/vcos/vcos.h"
#include "interface/vcos/vcos_stdint.h"
Classes
struct VCOS_CMD_PARAM_T
struct VCOS_CMD_S
Typedefs
typedef struct VCOS_CMD_S VCOS_CMD_T
typedef VCOS_STATUS_T(* VCOS_CMD_FUNC_T) (VCOS_CMD_PARAM_T *param)
Functions
VCOSPRE_ void VCOSPOST_ vcos_cmd_error (VCOS_CMD_PARAM_T *param, const char *fmt,...) VCOS_FORMAT_ATTR_(printf
VCOSPRE_ void VCOSPOST_ VCOSPRE_ void VCOSPOST_ vcos_cmd_printf (VCOS_CMD_PARAM_T *param, const char *fmt,...) VCOS_FORMAT_ATTR_(printf
VCOSPRE_ void VCOSPOST_ VCOSPRE_ void VCOSPOST_ VCOSPRE_ void VCOSPOST_ vcos_cmd_vprintf (VCOS_CMD_PARAM_T *param, const char *fmt, va_list args) VCOS_FORMAT_ATTR_(printf
VCOSPRE_ void VCOSPOST_ vcos_cmd_always_log_output (struct VCOS_LOG_CAT_T *log_category)
VCOSPRE_ void VCOSPOST_ vcos_cmd_usage (VCOS_CMD_PARAM_T *param)
VCOSPRE_ VCOS_STATUS_T VCOSPOST_ vcos_cmd_register (VCOS_CMD_T *cmd_entry)
VCOSPRE_ VCOS_STATUS_T VCOSPOST_ vcos_cmd_register_multiple (VCOS_CMD_T *cmd_entry)
VCOSPRE_ VCOS_STATUS_T VCOSPOST_ vcos_cmd_execute (int argc, char **argv, size_t result_size, char *result_buf)
VCOSPRE_ void VCOSPOST_ vcos_cmd_shutdown (void)
Typedef Documentation
VCOS_CMD_FUNC_T
typedef VCOS_STATUS_T(* VCOS_CMD_FUNC_T) (VCOS_CMD_PARAM_T *param)
Definition at line 60 of file vcos_cmd.h.
VCOS_CMD_T
typedef struct VCOS_CMD_S VCOS_CMD_T
Definition at line 42 of file vcos_cmd.h.
Function Documentation
vcos_cmd_always_log_output()
VCOSPRE_ void VCOSPOST_ vcos_cmd_always_log_output (struct VCOS_LOG_CAT_T * log_category)
Definition at line 111 of file vcos_cmd.c.
 {
     cmd_globals.log_category = log_category;
 }
vcos_cmd_error()
VCOSPRE_ void VCOSPOST_ vcos_cmd_error (VCOS_CMD_PARAM_T * param, const char * fmt, ...)
vcos_cmd_execute()
VCOSPRE_ VCOS_STATUS_T VCOSPOST_ vcos_cmd_execute (int argc, char ** argv, size_t result_size, char * result_buf)
Definition at line 548 of file vcos_cmd.c.
References VCOS_EINVAL, and vcos_once().
 {
     VCOS_STATUS_T       rc = VCOS_EINVAL;
     VCOS_CMD_PARAM_T    param;
     vcos_once( &cmd_globals.initialized, vcos_cmd_init );
     param.argc = argc;
     param.argv = param.argv_orig = argv;
     param.use_log = 0;
     param.result_size = result_size;
     param.result_ptr = result_buf;
     param.result_buf = result_buf;
     result_buf[0] = '\0';
     vcos_mutex_lock( &cmd_globals.lock );
     rc = execute_cmd( &param, cmd_globals.cmd_entry );
     if ( param.use_log )
     {
         cmd_log_results( &param );
         vcos_snprintf( result_buf, result_size, "results logged" );
     }
     else
     if ( cmd_globals.log_category != NULL )
     {
         if ( result_buf[0] != '\0' )
         {
             /* There is a partial line still buffered. */
             vcos_cmd_printf( &param, "\n" );
         }
     }
     vcos_mutex_unlock( &cmd_globals.lock );
     return rc;
 }
vcos_cmd_printf()
VCOSPRE_ void VCOSPOST_ VCOSPRE_ void VCOSPOST_ vcos_cmd_printf (VCOS_CMD_PARAM_T * param, const char * fmt, ...)
vcos_cmd_register()
VCOSPRE_ VCOS_STATUS_T VCOSPOST_ vcos_cmd_register (VCOS_CMD_T * cmd_entry)
Definition at line 596 of file vcos_cmd.c.
References vcos_once().
Referenced by vcos_cmd_register_multiple().
 {
     VCOS_STATUS_T   rc;
     VCOS_UNSIGNED   new_num_cmd_alloc;
     VCOS_CMD_T     *new_cmd_entry;
     VCOS_CMD_T     *old_cmd_entry;
     VCOS_CMD_T     *scan_entry;
     vcos_once( &cmd_globals.initialized, vcos_cmd_init );
     vcos_assert( cmd_entry != NULL );
     vcos_assert( cmd_entry->name != NULL );
     vcos_log_trace( "%s: cmd '%s'", __FUNCTION__, cmd_entry->name );
     vcos_assert( cmd_entry->args != NULL );
     vcos_assert(( cmd_entry->cmd_fn != NULL ) || ( cmd_entry->sub_cmd_entry != NULL ));
     vcos_assert( cmd_entry->descr != NULL );
     /* We expect vcos_cmd_init to be called before vcos_logging_init, so we
      * need to defer registering our logging category until someplace
      * like right here.
      */
     if ( vcos_cmd_log_category.name == NULL )
     {
         /*
          * If you're using the command interface, you pretty much always want
          * log messages from this file to show up. So we change the default
          * from ERROR to be the more reasonable INFO level.
          */
         vcos_log_set_level(&vcos_cmd_log_category, VCOS_LOG_INFO);
         vcos_log_register("vcos_cmd", &vcos_cmd_log_category);
         /* We register a help command so that it shows up in the usage. */
         vcos_cmd_register( &cmd_help );
 #ifdef HAVE_VCOS_VERSION
         vcos_cmd_register( &cmd_version );
 #endif
     }
     vcos_mutex_lock( &cmd_globals.lock );
     if ( cmd_globals.num_cmd_entries >= cmd_globals.num_cmd_alloc )
     {
         if ( cmd_globals.num_cmd_alloc == 0 )
         {
             /* We haven't allocated a table yet */
         }
         /* The number 8 is rather arbitrary. */
         new_num_cmd_alloc = cmd_globals.num_cmd_alloc + 8;
         /* The + 1 is to ensure that we always have a NULL entry at the end. */
         new_cmd_entry = (VCOS_CMD_T *)vcos_calloc( new_num_cmd_alloc + 1, sizeof( *cmd_entry ), "vcos_cmd_entries" );
         if ( new_cmd_entry == NULL )
         {
             rc = VCOS_ENOMEM;
             goto out;
         }
         memcpy( new_cmd_entry, cmd_globals.cmd_entry, cmd_globals.num_cmd_entries * sizeof( *cmd_entry ));
         cmd_globals.num_cmd_alloc = new_num_cmd_alloc;
         old_cmd_entry = cmd_globals.cmd_entry;
         cmd_globals.cmd_entry = new_cmd_entry;
         vcos_free( old_cmd_entry );
     }
     if ( cmd_globals.num_cmd_entries == 0 )
     {
         /* This is the first command being registered */
         cmd_globals.cmd_entry[0] = *cmd_entry;
     }
     else
     {
         /* Keep the list in alphabetical order. We start at the end and work backwards
          * shuffling entries up one until we find an insertion point.
          */
         for ( scan_entry = &cmd_globals.cmd_entry[cmd_globals.num_cmd_entries - 1];
               scan_entry >= cmd_globals.cmd_entry; scan_entry-- )
         {
             if ( vcos_strcmp( cmd_entry->name, scan_entry->name ) > 0 )
             {
                 /* We found an insertion point. */
                 break;
             }
             scan_entry[1] = scan_entry[0];
         }
         scan_entry[1] = *cmd_entry;
     }
     cmd_globals.num_cmd_entries++;
     rc = VCOS_SUCCESS;
 out:
     vcos_mutex_unlock( &cmd_globals.lock );
     return rc;
 }
vcos_cmd_register_multiple()
VCOSPRE_ VCOS_STATUS_T VCOSPOST_ vcos_cmd_register_multiple (VCOS_CMD_T * cmd_entry)
Definition at line 709 of file vcos_cmd.c.
References VCOS_CMD_S::name, NULL, status, vcos_cmd_register(), and VCOS_SUCCESS.
 {
     VCOS_STATUS_T   status;
     while ( cmd_entry->name != NULL )
     {
         if (( status = vcos_cmd_register( cmd_entry )) != VCOS_SUCCESS )
         {
             return status;
         }
         cmd_entry++;
     }
     return VCOS_SUCCESS;
 }
vcos_cmd_shutdown()
VCOSPRE_ void VCOSPOST_ vcos_cmd_shutdown (void)
Definition at line 534 of file vcos_cmd.c.
References vcos_mutex_delete().
 {
     vcos_mutex_delete( &cmd_globals.lock );
     vcos_free( cmd_globals.cmd_entry );
     cmd_globals.cmd_entry = NULL;
 }
vcos_cmd_usage()
VCOSPRE_ void VCOSPOST_ vcos_cmd_usage (VCOS_CMD_PARAM_T * param)
Definition at line 318 of file vcos_cmd.c.
References VCOS_CMD_PARAM_T::cmd_entry, NULL, and VCOS_CMD_S::sub_cmd_entry.
 {
     VCOS_CMD_T *cmd_entry;
     cmd_entry = param->cmd_entry;
     if ( cmd_entry->sub_cmd_entry != NULL )
     {
         /* This command is command with sub-commands */
         usage( param, param->cmd_entry->sub_cmd_entry );
     }
     else
     {
         vcos_cmd_printf( param, "Usage: " );
         print_argument_prefix( param );
         vcos_cmd_printf( param, "%s %s - %s\n",
                          param->argv[0],
                          param->cmd_entry->args,
                          param->cmd_entry->descr );
     }
 }
vcos_cmd_vprintf()
VCOSPRE_ void VCOSPOST_ VCOSPRE_ void VCOSPOST_ VCOSPRE_ void VCOSPOST_ vcos_cmd_vprintf (VCOS_CMD_PARAM_T * param, const char * fmt, va_list args)