VideoCore Library: interface/khronos/common/abstract/khrn_client_platform_filler_abstract.h File Reference
khrn_client_platform_filler_abstract.h File Reference
#include "interface/vcos/vcos.h"
Classes
struct PLATFORM_MUTEX_T
Macros
#define KHR_SUCCESS 0
Typedefs
typedef int KHR_STATUS_T
typedef struct PLATFORM_MUTEX_T PLATFORM_MUTEX_T
typedef VCOS_NAMED_SEMAPHORE_T PLATFORM_SEMAPHORE_T
typedef void * PLATFORM_TLS_T
Functions
VCOS_STATIC_INLINE VCOS_STATUS_T platform_mutex_create (PLATFORM_MUTEX_T *mutex)
VCOS_STATIC_INLINE void platform_mutex_destroy (PLATFORM_MUTEX_T *mutex)
VCOS_STATIC_INLINE void platform_mutex_acquire (PLATFORM_MUTEX_T *mutex)
VCOS_STATIC_INLINE void platform_mutex_release (PLATFORM_MUTEX_T *mutex)
VCOS_STATUS_T khronos_platform_semaphore_create (PLATFORM_SEMAPHORE_T *sem, int name[3], int count)
void khronos_platform_semaphore_destroy (PLATFORM_SEMAPHORE_T *sem)
void khronos_platform_semaphore_acquire (PLATFORM_SEMAPHORE_T *sem)
void khronos_platform_semaphore_release (PLATFORM_SEMAPHORE_T *sem)
VCOS_STATUS_T platform_tls_create (PLATFORM_TLS_T *tls)
void platform_tls_destroy (PLATFORM_TLS_T tls)
void platform_tls_set (PLATFORM_TLS_T tls, void *v)
void * platform_tls_get (PLATFORM_TLS_T tls)
void * platform_tls_get_check (PLATFORM_TLS_T tls)
void platform_tls_remove (PLATFORM_TLS_T tls)
Macro Definition Documentation
KHR_SUCCESS
#define KHR_SUCCESS 0
Definition at line 34 of file khrn_client_platform_filler_abstract.h.
Referenced by client_process_attach(), and vg_client_shared_state_alloc().
Typedef Documentation
KHR_STATUS_T
typedef int KHR_STATUS_T
Definition at line 33 of file khrn_client_platform_filler_abstract.h.
PLATFORM_MUTEX_T
typedef struct PLATFORM_MUTEX_T PLATFORM_MUTEX_T
PLATFORM_SEMAPHORE_T
typedef VCOS_NAMED_SEMAPHORE_T PLATFORM_SEMAPHORE_T
Definition at line 80 of file khrn_client_platform_filler_abstract.h.
PLATFORM_TLS_T
typedef void* PLATFORM_TLS_T
Definition at line 102 of file khrn_client_platform_filler_abstract.h.
Function Documentation
khronos_platform_semaphore_acquire()
void khronos_platform_semaphore_acquire (PLATFORM_SEMAPHORE_T * sem)
Definition at line 82 of file khrn_client_platform_filler_vcos.h.
{
    vcos_named_semaphore_wait(sem);
 }
khronos_platform_semaphore_create()
VCOS_STATUS_T khronos_platform_semaphore_create (PLATFORM_SEMAPHORE_T * sem, int name[3], int count)
Definition at line 71 of file khrn_client_platform_linux.c.
 {
    char buf[64];
    vcos_snprintf(buf,sizeof(buf),"KhanSemaphore%08x%08x%08x", name[0], name[1], name[2]);
    return vcos_named_semaphore_create(sem, buf, count);
 }
khronos_platform_semaphore_destroy()
void khronos_platform_semaphore_destroy (PLATFORM_SEMAPHORE_T * sem)
Definition at line 77 of file khrn_client_platform_filler_vcos.h.
{
    vcos_named_semaphore_delete(sem);
 }
khronos_platform_semaphore_release()
void khronos_platform_semaphore_release (PLATFORM_SEMAPHORE_T * sem)
Definition at line 92 of file khrn_client_platform_filler_vcos.h.
{
    vcos_named_semaphore_post(sem);
 }
platform_mutex_acquire()
VCOS_STATIC_INLINE void platform_mutex_acquire (PLATFORM_MUTEX_T * mutex)
Definition at line 63 of file khrn_client_platform_filler_abstract.h.
Referenced by platform_client_lock(), and rpc_begin().
 {
    UNUSED(mutex);
    /* Nothing to do */
 }
platform_mutex_create()
VCOS_STATIC_INLINE VCOS_STATUS_T platform_mutex_create (PLATFORM_MUTEX_T * mutex)
Definition at line 49 of file khrn_client_platform_filler_abstract.h.
Referenced by client_process_attach(), and vg_client_shared_state_alloc().
{
    UNUSED(mutex);
    // Nothing to do
    return VCOS_SUCCESS;
 }
platform_mutex_destroy()
VCOS_STATIC_INLINE void platform_mutex_destroy (PLATFORM_MUTEX_T * mutex)
Definition at line 56 of file khrn_client_platform_filler_abstract.h.
Referenced by client_process_attach(), client_process_detach(), and vg_client_shared_state_alloc().
 {
    UNUSED(mutex);
    /* Nothing to do */
 }
platform_mutex_release()
VCOS_STATIC_INLINE void platform_mutex_release (PLATFORM_MUTEX_T * mutex)
Definition at line 70 of file khrn_client_platform_filler_abstract.h.
Referenced by platform_client_release(), and rpc_end().
 {
    UNUSED(mutex);
    /* Nothing to do */
 }
platform_tls_create()
VCOS_STATUS_T platform_tls_create (PLATFORM_TLS_T * tls)
Referenced by client_process_attach().
platform_tls_destroy()
void platform_tls_destroy (PLATFORM_TLS_T tls)
platform_tls_get()
void* platform_tls_get (PLATFORM_TLS_T tls)
Definition at line 87 of file khrn_client_platform_linux.c.
 {
    void *ret;
    if (!process_attached)
       /* TODO: this isn't thread safe */
    {
       vcos_log_trace("Attaching process");
       client_process_attach();
       process_attached = true;
       tls = client_tls;
       vc_vchi_khronos_init();
    }
    ret = vcos_tls_get(tls);
    if (!ret)
    {
      /* The problem here is that on VCFW, the first notification we get that a thread
        * exists at all is when it calls an arbitrary EGL function. We need to detect this
        * case and initiliase the per-thread state.
        *
        * On Windows this gets done in DllMain.
        */
       client_thread_attach();
       vcos_thread_at_exit(client_thread_detach, NULL);
       ret = vcos_tls_get(tls);
    }
    return ret;
 }
platform_tls_get_check()
void* platform_tls_get_check (PLATFORM_TLS_T tls)
Definition at line 118 of file khrn_client_platform_linux.c.
 {
    return platform_tls_get(tls);
 }
platform_tls_remove()
void platform_tls_remove (PLATFORM_TLS_T tls)
platform_tls_set()
void platform_tls_set (PLATFORM_TLS_T tls, void * v)