VideoCore Library: OpenMAX IL core
OpenMAX IL core
Modules
Tunneling
Content Pipes
Classes
struct OMX_COMPONENTREGISTERTYPE
Typedefs
typedef enum OMX_COMMANDTYPE OMX_COMMANDTYPE
typedef OMX_ERRORTYPE(* OMX_COMPONENTINITTYPE) (OMX_IN OMX_HANDLETYPE hComponent)
typedef struct OMX_COMPONENTREGISTERTYPE OMX_COMPONENTREGISTERTYPE
Enumerations
enum OMX_COMMANDTYPE {
OMX_CommandStateSet, OMX_CommandFlush, OMX_CommandPortDisable, OMX_CommandPortEnable,
OMX_CommandMarkBuffer, OMX_CommandKhronosExtensions = 0x6F000000, OMX_CommandVendorStartUnused = 0x7F000000, OMX_CommandMax = 0X7FFFFFFF
}
Functions
OMX_API OMX_ERRORTYPE OMX_APIENTRY OMX_Init (void)
OMX_API OMX_ERRORTYPE OMX_APIENTRY OMX_Deinit (void)
OMX_API OMX_ERRORTYPE OMX_APIENTRY OMX_ComponentNameEnum (OMX_OUT OMX_STRING cComponentName, OMX_IN OMX_U32 nNameLength, OMX_IN OMX_U32 nIndex)
OMX_API OMX_ERRORTYPE OMX_APIENTRY OMX_GetHandle (OMX_OUT OMX_HANDLETYPE *pHandle, OMX_IN OMX_STRING cComponentName, OMX_IN OMX_PTR pAppData, OMX_IN OMX_CALLBACKTYPE *pCallBacks)
OMX_API OMX_ERRORTYPE OMX_APIENTRY OMX_FreeHandle (OMX_IN OMX_HANDLETYPE hComponent)
OMX_API OMX_ERRORTYPE OMX_GetComponentsOfRole (OMX_IN OMX_STRING role, OMX_INOUT OMX_U32 *pNumComps, OMX_INOUT OMX_U8 **compNames)
OMX_API OMX_ERRORTYPE OMX_GetRolesOfComponent (OMX_IN OMX_STRING compName, OMX_INOUT OMX_U32 *pNumRoles, OMX_OUT OMX_U8 **roles)
Variables
OMX_COMPONENTREGISTERTYPE OMX_ComponentRegistered []
Detailed Description
In the following we define groups that help building doxygen documentation Functions and structure related to the OMX IL core
Typedef Documentation
OMX_COMMANDTYPE
typedef enum OMX_COMMANDTYPE OMX_COMMANDTYPE
OMX_Core.h - OpenMax IL version 1.1.2 The OMX_Core header file contains the definitions used by both the application and the component to access common items.The OMX_COMMANDTYPE enumeration is used to specify the action in the OMX_SendCommand macro.
OMX_COMPONENTINITTYPE
typedef OMX_ERRORTYPE(* OMX_COMPONENTINITTYPE) (OMX_IN OMX_HANDLETYPE hComponent)
Definition at line 287 of file OMX_Core.h.
OMX_COMPONENTREGISTERTYPE
typedef struct OMX_COMPONENTREGISTERTYPE OMX_COMPONENTREGISTERTYPE
Enumeration Type Documentation
OMX_COMMANDTYPE
enum OMX_COMMANDTYPE
OMX_Core.h - OpenMax IL version 1.1.2 The OMX_Core header file contains the definitions used by both the application and the component to access common items.The OMX_COMMANDTYPE enumeration is used to specify the action in the OMX_SendCommand macro.
Enumerator
OMX_CommandStateSet
Change the component state
OMX_CommandFlush
Flush the data queue(s) of a component
OMX_CommandPortDisable
Disable a port on a component.
OMX_CommandPortEnable
Enable a port on a component.
OMX_CommandMarkBuffer
Mark a component/buffer for observation
OMX_CommandKhronosExtensions
Reserved region for introducing Khronos Standard Extensions
OMX_CommandVendorStartUnused
Reserved region for introducing Vendor Extensions
OMX_CommandMax
Definition at line 60 of file OMX_Core.h.
 {
     OMX_CommandStateSet,
     OMX_CommandFlush,
     OMX_CommandPortDisable,
     OMX_CommandPortEnable,
     OMX_CommandMarkBuffer,
     OMX_CommandKhronosExtensions = 0x6F000000,
     OMX_CommandVendorStartUnused = 0x7F000000,
     OMX_CommandMax = 0X7FFFFFFF
 } OMX_COMMANDTYPE;
Function Documentation
OMX_ComponentNameEnum()
OMX_API OMX_ERRORTYPE OMX_APIENTRY OMX_ComponentNameEnum (OMX_OUT OMX_STRING cComponentName, OMX_IN OMX_U32 nNameLength, OMX_IN OMX_U32 nIndex)
The OMX_ComponentNameEnum method will enumerate through all the names of recognised valid components in the system. This function is provided as a means to detect all the components in the system run-time. There is no strict ordering to the enumeration order of component names, although each name will only be enumerated once. If the OMX core supports run-time installation of new components, it is only requried to detect newly installed components when the first call to enumerate component names is made (i.e. when nIndex is 0x0).
The core should return from this call in 20 msec.
Parameters
[out] cComponentName pointer to a null terminated string with the component name. The names of the components are strings less than 127 bytes in length plus the trailing null for a maximum size of 128 bytes. An example of a valid component name is "OMX.TI.AUDIO.DSP.MIXER\0". Names are assigned by the vendor, but shall start with "OMX." and then have the Vendor designation next.
[in] nNameLength number of characters in the cComponentName string. With all component name strings restricted to less than 128 characters (including the trailing null) it is recomended that the caller provide a input string for the cComponentName of 128 characters.
[in] nIndex number containing the enumeration index for the component. Multiple calls to OMX_ComponentNameEnum with increasing values of nIndex will enumerate through the component names in the system until OMX_ErrorNoMore is returned. The value of nIndex is 0 to (N-1), where N is the number of valid installed components in the system.
Returns
OMX_ERRORTYPE If the command successfully executes, the return code will be OMX_ErrorNone. When the value of nIndex exceeds the number of components in the system minus 1, OMX_ErrorNoMore will be returned. Otherwise the appropriate OMX error will be returned.
Definition at line 162 of file ilcore.c.
References ilcs_get_common(), NULL, OMX_ErrorBadParameter, and vcil_out_component_name_enum().
 {
    if(ilcs_service == NULL)
       return OMX_ErrorBadParameter;
    return vcil_out_component_name_enum(ilcs_get_common(ilcs_service), cComponentName, nNameLength, nIndex);
 }
OMX_Deinit()
OMX_API OMX_ERRORTYPE OMX_APIENTRY OMX_Deinit (void)
The OMX_Deinit method is used to deinitialize the OMX core. It shall be the last call made into OMX. In the event that the core determines that thare are components loaded when this call is made, the core may return with an error rather than try to unload the components.
The core should return from this call within 20 msec.
Returns
OMX_ERRORTYPE If the command successfully executes, the return code will be OMX_ErrorNone. Otherwise the appropriate OMX error will be returned.
Definition at line 133 of file ilcore.c.
References LOG_TRACE, mmalomx_logging_deinit(), and OMX_ErrorNone.
Referenced by audioplay_delete(), and cleanup().
 {
    if(coreInit == 0) // || (coreInit == 1 && nActiveHandles > 0))
       return OMX_ErrorNotReady;
    vcos_mutex_lock(&lock);
 #ifdef USE_VCHIQ_ARM
    coreInit--;
 #endif
    if(coreInit == 0)
    {
       // we need to teardown the ILCS connection to VideoCore
       ilcs_deinit(ilcs_service);
       ilcs_service = NULL;
    }
 #ifdef WANT_LOCAL_OMX
    vc_OMX_Deinit(); // deinitialise local core as well
 #endif
    vcos_mutex_unlock(&lock);
    return OMX_ErrorNone;
 }
OMX_FreeHandle()
OMX_API OMX_ERRORTYPE OMX_APIENTRY OMX_FreeHandle (OMX_IN OMX_HANDLETYPE hComponent)
The OMX_FreeHandle method will free a handle allocated by the OMX_GetHandle method. If the component reference count goes to zero, the component will be unloaded from memory.
The core should return from this call within 20 msec when the component is in the OMX_StateLoaded state.
Parameters
[in] hComponent Handle of the component to be accessed. This is the component handle returned by the call to the GetHandle function.
Returns
OMX_ERRORTYPE If the command successfully executes, the return code will be OMX_ErrorNone. Otherwise the appropriate OMX error will be returned.
Definition at line 245 of file ilcore.c.
References OMX_COMPONENTTYPE::ComponentDeInit, NULL, OMX_ErrorBadParameter, OMX_ErrorNone, OMX_COMPONENTTYPE::pApplicationPrivate, and vcos_mutex_lock().
Referenced by ilclient_cleanup_components().
 {
    OMX_ERRORTYPE eError = OMX_ErrorNone;
    OMX_COMPONENTTYPE *pComp;
    if (hComponent == NULL || ilcs_service == NULL)
       return OMX_ErrorBadParameter;
    pComp = (OMX_COMPONENTTYPE*)hComponent;
 #ifdef WANT_LOCAL_OMX
    // xxx: a bit of a bodge, we rely on knowing that
    // the local core doesn't make use of this field but
    // ILCS does...
    if (pComp->pApplicationPrivate == NULL)
       return vc_OMX_FreeHandle(hComponent);
 #endif
    if (ilcs_service == NULL)
       return OMX_ErrorBadParameter;
    eError = (pComp->ComponentDeInit)(hComponent);
    if (eError == OMX_ErrorNone) {
       vcos_mutex_lock(&lock);
       --nActiveHandles;
       vcos_mutex_unlock(&lock);
       free(pComp);
    }
    vcos_assert(nActiveHandles >= 0);
    return eError;
 }
OMX_GetComponentsOfRole()
OMX_API OMX_ERRORTYPE OMX_GetComponentsOfRole (OMX_IN OMX_STRING role, OMX_INOUT OMX_U32 * pNumComps, OMX_INOUT OMX_U8 ** compNames)
The OMX_GetComponentsOfRole method will return the number of components that support the given role and (if the compNames field is non-NULL) the names of those components. The call will fail if an insufficiently sized array of names is supplied. To ensure the array is sufficiently sized the client should: first call this function with the compNames field NULL to determine the number of component names second call this function with the compNames field pointing to an array of names allocated according to the number returned by the first call.
The core should return from this call within 5 msec.
Parameters
[in] role This is generic standard component name consisting only of component class name and the type within that class (e.g. 'audio_decoder.aac').
[in,out] pNumComps This is used both as input and output.
If compNames is NULL, the input is ignored and the output specifies how many components support the given role.
If compNames is not NULL, on input it bounds the size of the input structure and on output, it specifies the number of components string names listed within the compNames parameter.
Parameters
[in,out] compNames If NULL this field is ignored. If non-NULL this points to an array of 128-byte strings which accepts a list of the names of all physical components that implement the specified standard component name. Each name is NULL terminated. numComps indicates the number of names.
Definition at line 316 of file ilcore.c.
References OMX_ErrorNone.
 {
    OMX_ERRORTYPE eError = OMX_ErrorNone;
    *pNumComps = 0;
    return eError;
 }
OMX_GetHandle()
OMX_API OMX_ERRORTYPE OMX_APIENTRY OMX_GetHandle (OMX_OUT OMX_HANDLETYPE * pHandle, OMX_IN OMX_STRING cComponentName, OMX_IN OMX_PTR pAppData, OMX_IN OMX_CALLBACKTYPE * pCallBacks)
The OMX_GetHandle method will locate the component specified by the component name given, load that component into memory and then invoke the component's methods to create an instance of the component.
The core should return from this call within 20 msec.
Parameters
[out] pHandle pointer to an OMX_HANDLETYPE pointer to be filled in by this method.
[in] cComponentName pointer to a null terminated string with the component name. The names of the components are strings less than 127 bytes in length plus the trailing null for a maximum size of 128 bytes. An example of a valid component name is "OMX.TI.AUDIO.DSP.MIXER\0". Names are assigned by the vendor, but shall start with "OMX." and then have the Vendor designation next.
[in] pAppData pointer to an application defined value that will be returned during callbacks so that the application can identify the source of the callback.
[in] pCallBacks pointer to a OMX_CALLBACKTYPE structure that will be passed to the component to initialize it with.
Returns
OMX_ERRORTYPE If the command successfully executes, the return code will be OMX_ErrorNone. Otherwise the appropriate OMX error will be returned.
Definition at line 175 of file ilcore.c.
References OMX_COMPONENTTYPE::ComponentDeInit, ilcs_get_common(), OMX_COMPONENTTYPE::nSize, NULL, OMX_COMPONENTTYPE::nVersion, OMX_VERSIONTYPE::nVersion, OMX_ErrorBadParameter, OMX_ErrorInsufficientResources, OMX_ErrorInvalidComponent, OMX_ErrorNone, OMX_VERSION, OMX_COMPONENTTYPE::SetCallbacks, vcil_out_create_component(), vcos_assert, and vcos_mutex_lock().
 {
    OMX_ERRORTYPE eError;
    OMX_COMPONENTTYPE *pComp;
    OMX_HANDLETYPE hHandle = 0;
    if (pHandle == NULL || cComponentName == NULL || pCallBacks == NULL || ilcs_service == NULL)
    {
       if(pHandle)
          *pHandle = NULL;
       return OMX_ErrorBadParameter;
    }
 #if defined(WANT_LOCAL_OMX) && 0
    if ((eError = vc_OMX_GetHandle(pHandle, cComponentName, pAppData, pCallBacks)) != OMX_ErrorNone)
 #endif
    {
       pComp = (OMX_COMPONENTTYPE *)malloc(sizeof(OMX_COMPONENTTYPE));
       if (!pComp)
       {
          vcos_assert(0);
          return OMX_ErrorInsufficientResources;
       }
       memset(pComp, 0, sizeof(OMX_COMPONENTTYPE));
       hHandle = (OMX_HANDLETYPE)pComp;
       pComp->nSize = sizeof(OMX_COMPONENTTYPE);
       pComp->nVersion.nVersion = OMX_VERSION;
       eError = vcil_out_create_component(ilcs_get_common(ilcs_service), hHandle, cComponentName);
       if (eError == OMX_ErrorNone) {
          // Check that all function pointers have been filled in.
          // All fields should be non-zero.
          int i;
          uint32_t *p = (uint32_t *) pComp;
          for(i=0; i<sizeof(OMX_COMPONENTTYPE)>>2; i++)
             if(*p++ == 0)
                eError = OMX_ErrorInvalidComponent;
          if(eError != OMX_ErrorNone && pComp->ComponentDeInit)
             pComp->ComponentDeInit(hHandle);
       }
       if (eError == OMX_ErrorNone) {
          eError = pComp->SetCallbacks(hHandle,pCallBacks,pAppData);
          if (eError != OMX_ErrorNone)
             pComp->ComponentDeInit(hHandle);
       }
       if (eError == OMX_ErrorNone) {
          *pHandle = hHandle;
       }
       else {
          *pHandle = NULL;
          free(pComp);
       }
    }
    if (eError == OMX_ErrorNone) {
       vcos_mutex_lock(&lock);
       nActiveHandles++;
       vcos_mutex_unlock(&lock);
    }
    return eError;
 }
OMX_GetRolesOfComponent()
OMX_API OMX_ERRORTYPE OMX_GetRolesOfComponent (OMX_IN OMX_STRING compName, OMX_INOUT OMX_U32 * pNumRoles, OMX_OUT OMX_U8 ** roles)
The OMX_GetRolesOfComponent method will return the number of roles supported by the given component and (if the roles field is non-NULL) the names of those roles. The call will fail if an insufficiently sized array of names is supplied. To ensure the array is sufficiently sized the client should: first call this function with the roles field NULL to determine the number of role names second call this function with the roles field pointing to an array of names allocated according to the number returned by the first call.
The core should return from this call within 5 msec.
Parameters
[in] compName This is the name of the component being queried about.
[in,out] pNumRoles This is used both as input and output.
If roles is NULL, the input is ignored and the output specifies how many roles the component supports.
If compNames is not NULL, on input it bounds the size of the input structure and on output, it specifies the number of roles string names listed within the roles parameter.
Parameters
[out] roles If NULL this field is ignored. If non-NULL this points to an array of 128-byte strings which accepts a list of the names of all standard components roles implemented on the specified component name. numComps indicates the number of names.
Definition at line 328 of file ilcore.c.
References OMX_ErrorNone.
 {
    OMX_ERRORTYPE eError = OMX_ErrorNone;
    *pNumRoles = 0;
    return eError;
 }
OMX_Init()
OMX_API OMX_ERRORTYPE OMX_APIENTRY OMX_Init (void)
The OMX_Init method is used to initialize the OMX core. It shall be the first call made into OMX and it should only be executed one time without an interviening OMX_Deinit call.
The core should return from this call within 20 msec.
Returns
OMX_ERRORTYPE If the command successfully executes, the return code will be OMX_ErrorNone. Otherwise the appropriate OMX error will be returned.
Definition at line 84 of file ilcore.c.
References LOG_TRACE, mmalomx_logging_init(), OMX_ErrorNone, status, and vcos_once().
 {
    VCOS_STATUS_T status;
    OMX_ERRORTYPE err = OMX_ErrorNone;
    status = vcos_once(&once, initOnce);
    vcos_demand(status == VCOS_SUCCESS);
    vcos_mutex_lock(&lock);
 #ifdef WANT_LOCAL_OMX
    vc_OMX_Init(); // initialise local core first
 #endif
    if(coreInit == 0)
    {
       // we need to connect via an ILCS connection to VideoCore
       VCHI_INSTANCE_T initialise_instance;
       VCHI_CONNECTION_T *connection;
       ILCS_CONFIG_T config;
       vc_host_get_vchi_state(&initialise_instance, &connection);
       vcilcs_config(&config);
 #ifdef USE_VCHIQ_ARM
       ilcs_service = ilcs_init((VCHIQ_INSTANCE_T) initialise_instance, (void **) &connection, &config, 0);
 #else
       ilcs_service = ilcs_init((VCHIQ_STATE_T *) initialise_instance, (void **) &connection, &config, 0);
 #endif
       if(ilcs_service == NULL)
       {
          err = OMX_ErrorHardware;
          goto end;
       }
       coreInit = 1;
    }
 #ifdef USE_VCHIQ_ARM
    else
       coreInit++;
 #endif
 end:
    vcos_mutex_unlock(&lock);
    return err;
 }
Variable Documentation
OMX_ComponentRegistered
OMX_COMPONENTREGISTERTYPE OMX_ComponentRegistered[]