VideoCore Library: Container API
Container API
Modules
Container Metadata
Container Elementary Stream Format
Container Packet
Classes
struct VC_CONTAINER_PACKET_T
struct VC_CONTAINER_TRACK_T
struct VC_CONTAINER_DRM_T
struct VC_CONTAINER_T
struct VC_CONTAINER_STATS_T
struct VC_CONTAINER_WRITE_STATS_T
Macros
#define VC_CONTAINER_STATS_BINS 10
#define VC_CONTAINER_READ_TIMEOUT_BLOCK (uint32_t)(-1)
Typedefs
typedef uint32_t VC_CONTAINER_FOURCC_T
typedef uint8_t VC_CONTAINER_LANGUAGE_T[3]
typedef struct VC_CONTAINER_TRACK_T VC_CONTAINER_TRACK_T
typedef struct VC_CONTAINER_DRM_T VC_CONTAINER_DRM_T
typedef VC_CONTAINER_STATUS_T(* VC_CONTAINER_PROGRESS_REPORT_FUNC_T) (void *userdata, int64_t length, unsigned int percentage_done)
typedef struct VC_CONTAINER_T VC_CONTAINER_T
typedef struct VC_CONTAINER_IO_T VC_CONTAINER_IO_T
typedef struct VC_CONTAINER_STATS_T VC_CONTAINER_STATS_T
typedef struct VC_CONTAINER_WRITE_STATS_T VC_CONTAINER_WRITE_STATS_T
Enumerations
enum VC_CONTAINER_STATUS_T {
VC_CONTAINER_SUCCESS = 0, VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED, VC_CONTAINER_ERROR_FORMAT_FEATURE_NOT_SUPPORTED, VC_CONTAINER_ERROR_FORMAT_INVALID,
VC_CONTAINER_ERROR_CORRUPTED, VC_CONTAINER_ERROR_URI_NOT_FOUND, VC_CONTAINER_ERROR_URI_OPEN_FAILED, VC_CONTAINER_ERROR_OUT_OF_MEMORY,
VC_CONTAINER_ERROR_OUT_OF_SPACE, VC_CONTAINER_ERROR_OUT_OF_RESOURCES, VC_CONTAINER_ERROR_EOS, VC_CONTAINER_ERROR_LIMIT_REACHED,
VC_CONTAINER_ERROR_BUFFER_TOO_SMALL, VC_CONTAINER_ERROR_INCOMPLETE_DATA, VC_CONTAINER_ERROR_NO_TRACK_AVAILABLE, VC_CONTAINER_ERROR_TRACK_FORMAT_NOT_SUPPORTED,
VC_CONTAINER_ERROR_UNSUPPORTED_OPERATION, VC_CONTAINER_ERROR_INVALID_ARGUMENT, VC_CONTAINER_ERROR_CONTINUE, VC_CONTAINER_ERROR_ABORTED,
VC_CONTAINER_ERROR_NOT_FOUND, VC_CONTAINER_ERROR_DRM_NOT_AUTHORIZED, VC_CONTAINER_ERROR_DRM_EXPIRED, VC_CONTAINER_ERROR_DRM_FAILED,
VC_CONTAINER_ERROR_FAILED, VC_CONTAINER_ERROR_NOT_READY
}
enum VC_CONTAINER_CHAR_ENCODING_T { VC_CONTAINER_CHAR_ENCODING_UNKNOWN = 0, VC_CONTAINER_CHAR_ENCODING_UTF8 }
enum VC_CONTAINER_SEEK_MODE_T { VC_CONTAINER_SEEK_MODE_TIME = 0, VC_CONTAINER_SEEK_MODE_PERCENT }
enum VC_CONTAINER_CONTROL_T {
VC_CONTAINER_CONTROL_TRACK_ADD = 0, VC_CONTAINER_CONTROL_TRACK_ADD_DONE, VC_CONTAINER_CONTROL_TRACK_CHANGE, VC_CONTAINER_CONTROL_TRACK_DEL,
VC_CONTAINER_CONTROL_DRM_PLAY, VC_CONTAINER_CONTROL_METADATA_ADD, VC_CONTAINER_CONTROL_METADATA_CHANGE, VC_CONTAINER_CONTROL_METADATA_DEL,
VC_CONTAINER_CONTROL_CHAPTER_ADD, VC_CONTAINER_CONTROL_CHAPTER_DEL, VC_CONTAINER_CONTROL_SET_MAXIMUM_SIZE, VC_CONTAINER_CONTROL_SET_IO_PERF_STATS,
VC_CONTAINER_CONTROL_GET_IO_PERF_STATS, VC_CONTAINER_CONTROL_SET_IO_BUFFER_FULL_CALLBACK, VC_CONTAINER_CONTROL_IO_SET_READ_BUFFER_SIZE, VC_CONTAINER_CONTROL_IO_SET_READ_TIMEOUT_MS,
VC_CONTAINER_CONTROL_SET_TIMESTAMP_BASE, VC_CONTAINER_CONTROL_SET_NEXT_SEQUENCE_NUMBER, VC_CONTAINER_CONTROL_SET_SOURCE_ID, VC_CONTAINER_CONTROL_GET_DRM_METADATA,
VC_CONTAINER_CONTROL_ENCRYPT_TRACK, VC_CONTAINER_CONTROL_IO_FLUSH, VC_CONTAINER_CONTROL_TRACK_PACKETIZE, VC_CONTAINER_CONTROL_USER_EXTENSIONS = 0x1000
}
Functions
VC_CONTAINER_T * vc_container_open_reader (const char *psz_uri, VC_CONTAINER_STATUS_T *status, VC_CONTAINER_PROGRESS_REPORT_FUNC_T pf_progress, void *progress_userdata)
VC_CONTAINER_T * vc_container_open_reader_with_io (VC_CONTAINER_IO_T *p_io, const char *psz_uri, VC_CONTAINER_STATUS_T *status, VC_CONTAINER_PROGRESS_REPORT_FUNC_T pf_progress, void *progress_userdata)
VC_CONTAINER_T * vc_container_open_writer (const char *psz_uri, VC_CONTAINER_STATUS_T *status, VC_CONTAINER_PROGRESS_REPORT_FUNC_T pf_progress, void *progress_userdata)
VC_CONTAINER_STATUS_T vc_container_close (VC_CONTAINER_T *context)
VC_CONTAINER_STATUS_T vc_container_read (VC_CONTAINER_T *context, VC_CONTAINER_PACKET_T *packet, VC_CONTAINER_READ_FLAGS_T flags)
VC_CONTAINER_STATUS_T vc_container_write (VC_CONTAINER_T *context, VC_CONTAINER_PACKET_T *packet)
VC_CONTAINER_STATUS_T vc_container_seek (VC_CONTAINER_T *context, int64_t *offset, VC_CONTAINER_SEEK_MODE_T mode, VC_CONTAINER_SEEK_FLAGS_T flags)
VC_CONTAINER_STATUS_T vc_container_control (VC_CONTAINER_T *context, VC_CONTAINER_CONTROL_T operation,...)
Container Capabilities
The following flags are exported by containers to describe their capabilities
typedef uint32_t VC_CONTAINER_CAPABILITIES_T
#define VC_CONTAINER_CAPS_CAN_SEEK 0x1
#define VC_CONTAINER_CAPS_SEEK_IS_FAST 0x2
#define VC_CONTAINER_CAPS_CAN_CONTROL_PACE 0x4
#define VC_CONTAINER_CAPS_HAS_INDEX 0x8
#define VC_CONTAINER_CAPS_DATA_HAS_KEYFRAME_FLAG 0x10
#define VC_CONTAINER_CAPS_DYNAMIC_TRACK_ADD 0x20
#define VC_CONTAINER_CAPS_FORCE_TRACK 0x40
Track flags
The following flags describe properties of a track
#define VC_CONTAINER_TRACK_FLAG_CHANGED 0x1
Container Events
The following flags are exported by containers to notify the application of events
typedef uint32_t VC_CONTAINER_EVENTS_T
#define VC_CONTAINER_EVENT_TRACKS_CHANGE 1
#define VC_CONTAINER_EVENT_METADATA_CHANGE 2
Container read flags
The following flags can be passed during a read call
typedef uint32_t VC_CONTAINER_READ_FLAGS_T
#define VC_CONTAINER_READ_FLAG_INFO 1
#define VC_CONTAINER_READ_FLAG_SKIP 2
#define VC_CONTAINER_READ_FLAG_FORCE_TRACK 4
Container Seek Flags
The following flags control seek operations
typedef uint32_t VC_CONTAINER_SEEK_FLAGS_T
#define VC_CONTAINER_SEEK_FLAG_PRECISE 0x1
#define VC_CONTAINER_SEEK_FLAG_FORWARD 0x2
Detailed Description
API for container readers and writers
Macro Definition Documentation
VC_CONTAINER_CAPS_CAN_CONTROL_PACE
#define VC_CONTAINER_CAPS_CAN_CONTROL_PACE 0x4
The container controls the pace at which it is reading the data
Definition at line 98 of file containers.h.
VC_CONTAINER_CAPS_CAN_SEEK
#define VC_CONTAINER_CAPS_CAN_SEEK 0x1
The container can seek
Definition at line 94 of file containers.h.
Referenced by TESTER_T::run(), and wav_reader_open().
VC_CONTAINER_CAPS_DATA_HAS_KEYFRAME_FLAG
#define VC_CONTAINER_CAPS_DATA_HAS_KEYFRAME_FLAG 0x10
The container provides keyframe information
Definition at line 102 of file containers.h.
VC_CONTAINER_CAPS_DYNAMIC_TRACK_ADD
#define VC_CONTAINER_CAPS_DYNAMIC_TRACK_ADD 0x20
The container supports adding tracks after TRACK_ADD_DONE control message has been sent
Definition at line 104 of file containers.h.
Referenced by dummy_writer_open().
VC_CONTAINER_CAPS_FORCE_TRACK
#define VC_CONTAINER_CAPS_FORCE_TRACK 0x40
The container supports forcing reading of a given track
Definition at line 106 of file containers.h.
Referenced by TESTER_T::run().
VC_CONTAINER_CAPS_HAS_INDEX
#define VC_CONTAINER_CAPS_HAS_INDEX 0x8
The container provides an index. This basically means that seeking will be precise and fast
Definition at line 100 of file containers.h.
VC_CONTAINER_CAPS_SEEK_IS_FAST
#define VC_CONTAINER_CAPS_SEEK_IS_FAST 0x2
Seeking is fast. The absence of this flag can be used as a hint to avoid seeking as much as possible
Definition at line 96 of file containers.h.
VC_CONTAINER_EVENT_METADATA_CHANGE
#define VC_CONTAINER_EVENT_METADATA_CHANGE 2
Metadata has changed
Definition at line 372 of file containers.h.
VC_CONTAINER_EVENT_TRACKS_CHANGE
#define VC_CONTAINER_EVENT_TRACKS_CHANGE 1
Track information has changed
Definition at line 371 of file containers.h.
VC_CONTAINER_READ_FLAG_FORCE_TRACK
#define VC_CONTAINER_READ_FLAG_FORCE_TRACK 4
Force the container to read data from the specified track
Definition at line 491 of file containers.h.
Referenced by TESTER_T::run(), and vc_container_read().
VC_CONTAINER_READ_FLAG_INFO
#define VC_CONTAINER_READ_FLAG_INFO 1
Ask the container to only return information on the next packet without reading it
Definition at line 487 of file containers.h.
Referenced by TESTER_T::run(), vc_container_read(), and vc_packetizer_read().
VC_CONTAINER_READ_FLAG_SKIP
#define VC_CONTAINER_READ_FLAG_SKIP 2
Ask the container to skip the next packet
Definition at line 489 of file containers.h.
Referenced by vc_container_read(), and vc_packetizer_read().
VC_CONTAINER_READ_TIMEOUT_BLOCK
#define VC_CONTAINER_READ_TIMEOUT_BLOCK (uint32_t)(-1)
Used with the VC_CONTAINER_CONTROL_IO_SET_READ_TIMEOUT_MS control to indicate the read shall block until either data is available, or an error occurs.
Definition at line 728 of file containers.h.
VC_CONTAINER_SEEK_FLAG_FORWARD
#define VC_CONTAINER_SEEK_FLAG_FORWARD 0x2
By default a seek will always seek to the keyframe which comes just before the requested position. This flag allows the caller to force the container to seek to the keyframe which comes just after the requested position.
Definition at line 547 of file containers.h.
Referenced by TESTER_T::run(), and vc_container_seek().
VC_CONTAINER_SEEK_FLAG_PRECISE
#define VC_CONTAINER_SEEK_FLAG_PRECISE 0x1
Choose precise seeking even if slower
Definition at line 543 of file containers.h.
VC_CONTAINER_STATS_BINS
#define VC_CONTAINER_STATS_BINS 10
Performance statistics.The maximum number of bins a statistics value is held in
Definition at line 564 of file containers.h.
VC_CONTAINER_TRACK_FLAG_CHANGED
#define VC_CONTAINER_TRACK_FLAG_CHANGED 0x1
Track definition has changed
Definition at line 331 of file containers.h.
Typedef Documentation
VC_CONTAINER_CAPABILITIES_T
typedef uint32_t VC_CONTAINER_CAPABILITIES_T
Type definition for container capabilities
Definition at line 92 of file containers.h.
VC_CONTAINER_DRM_T
typedef struct VC_CONTAINER_DRM_T VC_CONTAINER_DRM_T
Definition of the DRM type
VC_CONTAINER_EVENTS_T
typedef uint32_t VC_CONTAINER_EVENTS_T
Type definition for container events
Definition at line 370 of file containers.h.
VC_CONTAINER_FOURCC_T
typedef uint32_t VC_CONTAINER_FOURCC_T
Four Character Code type used to identify codecs, etc.
Definition at line 76 of file containers.h.
VC_CONTAINER_IO_T
typedef struct VC_CONTAINER_IO_T VC_CONTAINER_IO_T
Forward declaration of a container input / output context. This structure defines the context for a container io instance
Definition at line 405 of file containers.h.
VC_CONTAINER_LANGUAGE_T
typedef uint8_t VC_CONTAINER_LANGUAGE_T[3]
Type definition for language codes. Language are defined as ISO639 Alpha-3 codes (http://en.wikipedia.org/wiki/List_of_ISO_639-2_codes)
Definition at line 80 of file containers.h.
VC_CONTAINER_PROGRESS_REPORT_FUNC_T
typedef VC_CONTAINER_STATUS_T(* VC_CONTAINER_PROGRESS_REPORT_FUNC_T) (void *userdata, int64_t length, unsigned int percentage_done)
Type definition for the progress reporting function. This function will be called regularly by the container during a call which blocks for too long and will report the progress of the operation as an estimated total length in microseconds and a percentage done. Returning anything else than VC_CONTAINER_SUCCESS in this function will abort the current operation.
Definition at line 363 of file containers.h.
VC_CONTAINER_READ_FLAGS_T
typedef uint32_t VC_CONTAINER_READ_FLAGS_T
Type definition for the read flags
Definition at line 485 of file containers.h.
VC_CONTAINER_SEEK_FLAGS_T
typedef uint32_t VC_CONTAINER_SEEK_FLAGS_T
Type definition for the seek flags
Definition at line 541 of file containers.h.
VC_CONTAINER_STATS_T
typedef struct VC_CONTAINER_STATS_T VC_CONTAINER_STATS_T
This type is used to represent multiple values of a statistic.
VC_CONTAINER_T
typedef struct VC_CONTAINER_T VC_CONTAINER_T
Definition of the container context
VC_CONTAINER_TRACK_T
typedef struct VC_CONTAINER_TRACK_T VC_CONTAINER_TRACK_T
Definition of the track type
VC_CONTAINER_WRITE_STATS_T
typedef struct VC_CONTAINER_WRITE_STATS_T VC_CONTAINER_WRITE_STATS_T
This type represents the statistics saved by the io layer.
Enumeration Type Documentation
VC_CONTAINER_CHAR_ENCODING_T
enum VC_CONTAINER_CHAR_ENCODING_T
Enumeration of the character encodings supported.
Enumerator
VC_CONTAINER_CHAR_ENCODING_UNKNOWN
Encoding is unknown
VC_CONTAINER_CHAR_ENCODING_UTF8
UTF8 encoding
Definition at line 83 of file containers.h.
              {
    VC_CONTAINER_CHAR_ENCODING_UNKNOWN = 0,
    VC_CONTAINER_CHAR_ENCODING_UTF8
 } VC_CONTAINER_CHAR_ENCODING_T;
VC_CONTAINER_CONTROL_T
enum VC_CONTAINER_CONTROL_T
Control operations which can be done on containers.
Enumerator
VC_CONTAINER_CONTROL_TRACK_ADD
Adds a new track to the list of tracks. This should be used by writers to create their list of tracks.
Arguments:
arg1= VC_CONTAINER_ES_FORMAT_T *: format of the track to add
return= VC_CONTAINER_ERROR_TRACK_FORMAT_NOT_SUPPORTED if the format is not supported
VC_CONTAINER_CONTROL_TRACK_ADD_DONE
Specifies that we're done adding new tracks. This is optional but can be used by writers to trigger the writing of the container header early. If this isn't used, the header will be written when the first data packet is received.
No arguments.
return= VC_CONTAINER_ERROR_TRACK_FORMAT_NOT_SUPPORTED if the format is not supported
VC_CONTAINER_CONTROL_TRACK_CHANGE
Change the format of a track in the list of tracks. This should be used by writers to modify the format of a track at run-time.
Arguments:
arg1= unsigned int: index of track to change
arg2= VC_CONTAINER_ES_FORMAT_T *: format of the track to add
return= VC_CONTAINER_ERROR_TRACK_FORMAT_NOT_SUPPORTED if the format is not supported
VC_CONTAINER_CONTROL_TRACK_DEL
Deletes a track from the list of tracks. This should be used by writers to delete tracks during run-time. Note that vc_container_close will automatically delete all track so it isn't necessary to call this before closing a writer.
Arguments:
arg1= index of the track to delete
VC_CONTAINER_CONTROL_DRM_PLAY
Activate the playback of DRM protected content.
No arguments.
return= one of the VC_CONTAINER_ERROR_DRM error codes if content can't be played
VC_CONTAINER_CONTROL_METADATA_ADD
TBD
VC_CONTAINER_CONTROL_METADATA_CHANGE
TBD
VC_CONTAINER_CONTROL_METADATA_DEL
TBD
VC_CONTAINER_CONTROL_CHAPTER_ADD
TBD
VC_CONTAINER_CONTROL_CHAPTER_DEL
TBD
VC_CONTAINER_CONTROL_SET_MAXIMUM_SIZE
Set a maximum size for files generated by writers.
Arguments:
arg1= uint64_t: maximum size
VC_CONTAINER_CONTROL_SET_IO_PERF_STATS
Enables/disabled performance statistic gathering.
Arguments:
arg1= bool: enable or disable
VC_CONTAINER_CONTROL_GET_IO_PERF_STATS
Collects performance statistics.
Arguments:
arg1= VC_CONTAINER_WRITE_STATS_T *:
VC_CONTAINER_CONTROL_SET_IO_BUFFER_FULL_CALLBACK
HACK.
Arguments:
arg1= void (*)(void *): callback function arg1= void *: opaque pointer to pass during the callback
VC_CONTAINER_CONTROL_IO_SET_READ_BUFFER_SIZE
Set the I/O read buffer size to be used.
Arguments:
arg1= uint32_t: New buffer size in bytes
VC_CONTAINER_CONTROL_IO_SET_READ_TIMEOUT_MS
Set the timeout on I/O read operations, if applicable.
Arguments:
arg1= uint32_t: New timeout in milliseconds, or VC_CONTAINER_READ_TIMEOUT_BLOCK
VC_CONTAINER_CONTROL_SET_TIMESTAMP_BASE
Set the timestamp base.
The timestamp passed equates to time zero for the stream.
Arguments:
arg1= uint32_t: Timestamp base in stream clock units.
VC_CONTAINER_CONTROL_SET_NEXT_SEQUENCE_NUMBER
Set the next expected sequence number for the stream.
Arguments:
arg1= uint32_t: Next expected sequence number.
VC_CONTAINER_CONTROL_SET_SOURCE_ID
Set the source ID for the container.
Arguments:
arg1= uint32_t: Source identifier.
VC_CONTAINER_CONTROL_GET_DRM_METADATA
Arguments:
arg1= void *: metadata buffer arg2= unsigned long: length of metadata in bytes
VC_CONTAINER_CONTROL_ENCRYPT_TRACK
Arguments:
arg1= unsigned long: track number arg2= VC_CONTAINER_FOURCC_T : drm type arg3= void *: encryption configuration parameters. arg4= unsigned long: configuration data length
VC_CONTAINER_CONTROL_IO_FLUSH
Causes the io to be flushed.
Arguments: none
VC_CONTAINER_CONTROL_TRACK_PACKETIZE
Request the container reader to packetize data for the specified track. Arguments:
arg1= unsigned long: track number arg2= VC_CONTAINER_FOURCC_T: codec variant to output
VC_CONTAINER_CONTROL_USER_EXTENSIONS
Private user extensions must be above this number
Definition at line 603 of file containers.h.
 {
    VC_CONTAINER_CONTROL_TRACK_ADD = 0,
    VC_CONTAINER_CONTROL_TRACK_ADD_DONE,
    VC_CONTAINER_CONTROL_TRACK_CHANGE,
    VC_CONTAINER_CONTROL_TRACK_DEL,
    VC_CONTAINER_CONTROL_DRM_PLAY,
    VC_CONTAINER_CONTROL_METADATA_ADD,
    VC_CONTAINER_CONTROL_METADATA_CHANGE,
    VC_CONTAINER_CONTROL_METADATA_DEL,
    VC_CONTAINER_CONTROL_CHAPTER_ADD,
    VC_CONTAINER_CONTROL_CHAPTER_DEL,
    VC_CONTAINER_CONTROL_SET_MAXIMUM_SIZE,
    VC_CONTAINER_CONTROL_SET_IO_PERF_STATS,
    VC_CONTAINER_CONTROL_GET_IO_PERF_STATS,
    VC_CONTAINER_CONTROL_SET_IO_BUFFER_FULL_CALLBACK,
    VC_CONTAINER_CONTROL_IO_SET_READ_BUFFER_SIZE,
    VC_CONTAINER_CONTROL_IO_SET_READ_TIMEOUT_MS,
    VC_CONTAINER_CONTROL_SET_TIMESTAMP_BASE,
    VC_CONTAINER_CONTROL_SET_NEXT_SEQUENCE_NUMBER,
    VC_CONTAINER_CONTROL_SET_SOURCE_ID,
    VC_CONTAINER_CONTROL_GET_DRM_METADATA,
    VC_CONTAINER_CONTROL_ENCRYPT_TRACK,
    VC_CONTAINER_CONTROL_IO_FLUSH,
    VC_CONTAINER_CONTROL_TRACK_PACKETIZE,
    VC_CONTAINER_CONTROL_USER_EXTENSIONS = 0x1000
 } VC_CONTAINER_CONTROL_T;
VC_CONTAINER_SEEK_MODE_T
enum VC_CONTAINER_SEEK_MODE_T
Definition of the different seek modes
Enumerator
VC_CONTAINER_SEEK_MODE_TIME
The offset provided for seeking is an absolute time offset in microseconds
VC_CONTAINER_SEEK_MODE_PERCENT
The offset provided for seeking is a percentage (Q32 ?)
Definition at line 528 of file containers.h.
 {
    VC_CONTAINER_SEEK_MODE_TIME = 0,
    VC_CONTAINER_SEEK_MODE_PERCENT
 } VC_CONTAINER_SEEK_MODE_T;
VC_CONTAINER_STATUS_T
enum VC_CONTAINER_STATUS_T
Status codes returned by the container API
Enumerator
VC_CONTAINER_SUCCESS
No error
VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED
Format of container is not supported
VC_CONTAINER_ERROR_FORMAT_FEATURE_NOT_SUPPORTED
Format of container uses unsupported features
VC_CONTAINER_ERROR_FORMAT_INVALID
Format of container is invalid
VC_CONTAINER_ERROR_CORRUPTED
Container is corrupted
VC_CONTAINER_ERROR_URI_NOT_FOUND
URI could not be found
VC_CONTAINER_ERROR_URI_OPEN_FAILED
URI could not be opened
VC_CONTAINER_ERROR_OUT_OF_MEMORY
Out of memory
VC_CONTAINER_ERROR_OUT_OF_SPACE
Out of disk space (used when writing)
VC_CONTAINER_ERROR_OUT_OF_RESOURCES
Out of resources (other than memory)
VC_CONTAINER_ERROR_EOS
End of stream reached
VC_CONTAINER_ERROR_LIMIT_REACHED
User defined limit reached (used when writing)
VC_CONTAINER_ERROR_BUFFER_TOO_SMALL
Given buffer is too small for data to be copied
VC_CONTAINER_ERROR_INCOMPLETE_DATA
Requested data is incomplete
VC_CONTAINER_ERROR_NO_TRACK_AVAILABLE
Container doesn't have any track
VC_CONTAINER_ERROR_TRACK_FORMAT_NOT_SUPPORTED
Format of the track is not supported
VC_CONTAINER_ERROR_UNSUPPORTED_OPERATION
The requested operation is not supported
VC_CONTAINER_ERROR_INVALID_ARGUMENT
The argument provided is invalid
VC_CONTAINER_ERROR_CONTINUE
The requested operation was interrupted and needs to be tried again
VC_CONTAINER_ERROR_ABORTED
The requested operation was aborted
VC_CONTAINER_ERROR_NOT_FOUND
The requested data was not found
VC_CONTAINER_ERROR_DRM_NOT_AUTHORIZED
The DRM was not authorized
VC_CONTAINER_ERROR_DRM_EXPIRED
The DRM has expired
VC_CONTAINER_ERROR_DRM_FAILED
Generic DRM error
VC_CONTAINER_ERROR_FAILED
Generic error
VC_CONTAINER_ERROR_NOT_READY
The container was not yet able to carry out the operation.
Definition at line 45 of file containers.h.
 {
    VC_CONTAINER_SUCCESS = 0,
    VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED,
    VC_CONTAINER_ERROR_FORMAT_FEATURE_NOT_SUPPORTED,
    VC_CONTAINER_ERROR_FORMAT_INVALID,
    VC_CONTAINER_ERROR_CORRUPTED,
    VC_CONTAINER_ERROR_URI_NOT_FOUND,
    VC_CONTAINER_ERROR_URI_OPEN_FAILED,
    VC_CONTAINER_ERROR_OUT_OF_MEMORY,
    VC_CONTAINER_ERROR_OUT_OF_SPACE,
    VC_CONTAINER_ERROR_OUT_OF_RESOURCES,
    VC_CONTAINER_ERROR_EOS,
    VC_CONTAINER_ERROR_LIMIT_REACHED,
    VC_CONTAINER_ERROR_BUFFER_TOO_SMALL,
    VC_CONTAINER_ERROR_INCOMPLETE_DATA,
    VC_CONTAINER_ERROR_NO_TRACK_AVAILABLE,
    VC_CONTAINER_ERROR_TRACK_FORMAT_NOT_SUPPORTED,
    VC_CONTAINER_ERROR_UNSUPPORTED_OPERATION,
    VC_CONTAINER_ERROR_INVALID_ARGUMENT,
    VC_CONTAINER_ERROR_CONTINUE,
    VC_CONTAINER_ERROR_ABORTED,
    VC_CONTAINER_ERROR_NOT_FOUND,
    VC_CONTAINER_ERROR_DRM_NOT_AUTHORIZED,
    VC_CONTAINER_ERROR_DRM_EXPIRED,
    VC_CONTAINER_ERROR_DRM_FAILED,
    VC_CONTAINER_ERROR_FAILED,
    VC_CONTAINER_ERROR_NOT_READY
 } VC_CONTAINER_STATUS_T;
Function Documentation
vc_container_close()
VC_CONTAINER_STATUS_T vc_container_close (VC_CONTAINER_T * context)
Closes an instance of a container reader / writer. This will free all the resources associated with the context.
Parameters
context Pointer to the context of the instance to close
Returns
the status of the operation
Definition at line 180 of file containers.c.
References VC_CONTAINER_PRIVATE_T::drm_filter, VC_CONTAINER_PRIVATE_T::io, VC_CONTAINER_T::meta, VC_CONTAINER_T::meta_num, VC_CONTAINER_PRIVATE_T::module_handle, VC_CONTAINER_TRACK_PRIVATE_T::packetizer, VC_CONTAINER_PRIVATE_T::packetizer_buffer, VC_CONTAINER_PRIVATE_T::pf_close, VC_CONTAINER_TRACK_T::priv, VC_CONTAINER_T::priv, VC_CONTAINER_T::tracks, VC_CONTAINER_T::tracks_num, VC_CONTAINER_ERROR_INVALID_ARGUMENT, vc_container_filter_close(), vc_container_io_close(), VC_CONTAINER_SUCCESS, vc_container_unload(), and vc_packetizer_close().
Referenced by TESTER_T::run(), vc_container_open_reader_with_io(), and vc_container_open_writer().
 {
    unsigned int i;
    if(!p_ctx)
       return VC_CONTAINER_ERROR_INVALID_ARGUMENT;
    for(i = 0; i < p_ctx->tracks_num; i++)
       if(p_ctx->tracks[i]->priv->packetizer)
          vc_packetizer_close(p_ctx->tracks[i]->priv->packetizer);
    if(p_ctx->priv->packetizer_buffer) free(p_ctx->priv->packetizer_buffer);
    if(p_ctx->priv->drm_filter) vc_container_filter_close(p_ctx->priv->drm_filter);
    if(p_ctx->priv->pf_close) p_ctx->priv->pf_close(p_ctx);
    if(p_ctx->priv->io) vc_container_io_close(p_ctx->priv->io);
    if(p_ctx->priv->module_handle) vc_container_unload(p_ctx);
    for(i = 0; i < p_ctx->meta_num; i++) free(p_ctx->meta[i]);
    if(p_ctx->meta_num) free(p_ctx->meta);
    p_ctx->meta_num = 0;
    free(p_ctx);
    return VC_CONTAINER_SUCCESS;
 }
vc_container_control()
VC_CONTAINER_STATUS_T vc_container_control (VC_CONTAINER_T * context, VC_CONTAINER_CONTROL_T operation, ...)
Extensible control function for container readers and writers. This function takes a variable number of arguments which will depend on the specific operation.
Parameters
context Pointer to the VC_CONTAINER_T context to use
operation The requested operation
Returns
the status of the operation. Can be VC_CONTAINER_ERROR_UNSUPPORTED_OPERATION if the operation is not supported or implemented by the container.
Definition at line 445 of file containers.c.
References status, VC_CONTAINER_CONTROL_ENCRYPT_TRACK, and VC_CONTAINER_ERROR_UNSUPPORTED_OPERATION.
Referenced by vc_container_write().
 {
    VC_CONTAINER_STATUS_T status = VC_CONTAINER_ERROR_UNSUPPORTED_OPERATION;
    va_list args;
    va_start( args, operation );
    if(operation == VC_CONTAINER_CONTROL_ENCRYPT_TRACK)
    {
       VC_CONTAINER_FOURCC_T type = va_arg(args, VC_CONTAINER_FOURCC_T);
       uint32_t track_num = va_arg(args, uint32_t);
       void *p_drm_data = va_arg(args, void *);
       int drm_data_size = va_arg(args, uint32_t);
       if(!p_ctx->priv->drm_filter && track_num < p_ctx->tracks_num)
       {
          VC_CONTAINER_TRACK_T * p_track = p_ctx->tracks[track_num];
          if ((status = vc_container_track_allocate_drmdata(p_ctx, p_track, drm_data_size)) != VC_CONTAINER_SUCCESS)
          {
             LOG_DEBUG(p_ctx, "failed to allocate memory for 'drm data' (%d bytes)", drm_data_size);
             goto end;
          }
          memcpy(p_track->priv->drmdata, p_drm_data, drm_data_size);
          /* Track encryption enabled and no filter - create one now. */
          p_ctx->priv->drm_filter = vc_container_filter_open(VC_FOURCC('d','r','m',' '), type, p_ctx, &status);
          if(status != VC_CONTAINER_SUCCESS)
             goto end;
          status = vc_container_filter_control(p_ctx->priv->drm_filter, operation, track_num);
       }
    }
    else if(operation == VC_CONTAINER_CONTROL_GET_DRM_METADATA)
    {
       void *p_drm_data = va_arg(args, void *);
       int *drm_data_size = va_arg(args, int *);
       status = vc_container_filter_control(p_ctx->priv->drm_filter, operation, p_drm_data, drm_data_size);
    }
    if(status == VC_CONTAINER_ERROR_UNSUPPORTED_OPERATION && p_ctx->priv->pf_control)
       status = p_ctx->priv->pf_control(p_ctx, operation, args);
    /* If the request has already been handled then we're done */
    if(status != VC_CONTAINER_ERROR_UNSUPPORTED_OPERATION)
       goto end;
    switch(operation)
    {
    case VC_CONTAINER_CONTROL_DRM_PLAY:
       if (p_ctx->priv->drm_filter)
          status = vc_container_filter_control(p_ctx->priv->drm_filter, operation, args);
       break;
    case VC_CONTAINER_CONTROL_SET_MAXIMUM_SIZE:
       p_ctx->priv->max_size = (uint64_t)va_arg( args, uint64_t );
       if(p_ctx->priv->io->max_size &&
          p_ctx->priv->max_size > p_ctx->priv->io->max_size)
          p_ctx->priv->max_size = p_ctx->priv->io->max_size;
       status = VC_CONTAINER_SUCCESS;
       break;
    case VC_CONTAINER_CONTROL_TRACK_PACKETIZE:
       {
          unsigned int track_num = va_arg(args, unsigned int);
          VC_CONTAINER_FOURCC_T fourcc = va_arg(args, VC_CONTAINER_FOURCC_T);
          VC_CONTAINER_TRACK_T *p_track;
          if(track_num >= p_ctx->tracks_num)
          {
             status = VC_CONTAINER_ERROR_INVALID_ARGUMENT;
             break;
          }
          if(p_ctx->tracks[track_num]->priv->packetizer)
          {
             status = VC_CONTAINER_SUCCESS;
             break;
          }
          p_track = p_ctx->tracks[track_num];
          p_track->priv->packetizer = vc_packetizer_open( p_track->format, fourcc, &status );
          if(!p_track->priv->packetizer)
             break;
          if(!p_ctx->priv->packetizer_buffer)
          {
             p_ctx->priv->packetizer_buffer = malloc(PACKETIZER_BUFFER_SIZE);
             if(!p_ctx->priv->packetizer_buffer)
             {
                status = VC_CONTAINER_ERROR_OUT_OF_MEMORY;
                vc_packetizer_close(p_track->priv->packetizer);
                p_track->priv->packetizer = NULL;
                break;
             }
          }
          vc_container_format_copy(p_track->format, p_track->priv->packetizer->out,
             p_track->format->extradata_size);
          p_track->format->flags |= VC_CONTAINER_ES_FORMAT_FLAG_FRAMED;
          p_ctx->priv->packetizing = true;
       }
       break;
    default: break;
    }
    if (status == VC_CONTAINER_ERROR_UNSUPPORTED_OPERATION)
       status = vc_container_io_control_list(p_ctx->priv->io, operation, args);
  end:
    va_end( args );
    return status;
 }
vc_container_open_reader()
VC_CONTAINER_T* vc_container_open_reader (const char * psz_uri, VC_CONTAINER_STATUS_T * status, VC_CONTAINER_PROGRESS_REPORT_FUNC_T pf_progress, void * progress_userdata)
Opens the media container pointed to by the URI for reading. This will create an an instance of a container reader and its associated context. The context returned will also be filled with the information retrieved from the media.
If the media isn't accessible or recognized, this will return a null pointer as well as an error code indicating why this failed.
Parameters
psz_uri Unified Resource Identifier pointing to the media container
status Returns the status of the operation
pf_progress User provided function pointer to a progress report function. Can be set to null if no progress report is wanted. This function will be used during the whole lifetime of the instance (i.e. it will be used during open / seek / close)
progress_userdata User provided pointer that will be passed during the progress report function call.
Returns
A pointer to the context of the new instance of the container reader. Returns NULL on failure.
Definition at line 110 of file containers.c.
References vc_container_io_close(), VC_CONTAINER_IO_MODE_READ, vc_container_io_open(), and vc_container_open_reader_with_io().
Referenced by TESTER_T::run().
 {
    VC_CONTAINER_IO_T *io;
    VC_CONTAINER_T *ctx;
    /* Start by opening the URI */
    io = vc_container_io_open( uri, VC_CONTAINER_IO_MODE_READ, p_status );
    if (!io)
       return 0;
    ctx = vc_container_open_reader_with_io( io, uri, p_status, pfn_progress, progress_userdata);
    if (!ctx)
       vc_container_io_close(io);
    return ctx;
 }
vc_container_open_reader_with_io()
VC_CONTAINER_T* vc_container_open_reader_with_io (VC_CONTAINER_IO_T * p_io, const char * psz_uri, VC_CONTAINER_STATUS_T * status, VC_CONTAINER_PROGRESS_REPORT_FUNC_T pf_progress, void * progress_userdata)
Opens for reading the media container pointed to by the container i/o. This will create an an instance of a container reader and its associated context. The context returned will also be filled with the information retrieved from the media.
If the media isn't accessible or recognized, this will return a null pointer as well as an error code indicating why this failed.
Parameters
p_io Instance of the container i/o to use
psz_uri Unified Resource Identifier pointing to the media container (optional)
status Returns the status of the operation
pf_progress User provided function pointer to a progress report function. Can be set to null if no progress report is wanted. This function will be used during the whole lifetime of the instance (i.e. it will be used during open / seek / close)
progress_userdata User provided pointer that will be passed during the progress report function call.
Returns
A pointer to the context of the new instance of the container reader. Returns NULL on failure.
Definition at line 42 of file containers.c.
References VC_CONTAINER_T::drm, VC_CONTAINER_PRIVATE_T::drm_filter, error(), extension, VC_CONTAINER_PRIVATE_T::io, LOG_ERROR, NULL, VC_CONTAINER_T::priv, VC_CONTAINER_IO_T::size, VC_CONTAINER_T::size, status, VC_CONTAINER_PRIVATE_T::uri, VC_CONTAINER_IO_T::uri_parts, vc_container_close(), VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED, VC_CONTAINER_ERROR_INVALID_ARGUMENT, VC_CONTAINER_ERROR_OUT_OF_MEMORY, vc_container_filter_open(), vc_container_load_reader(), vc_container_log_get_default_verbosity(), VC_CONTAINER_PARAM_UNUSED, VC_CONTAINER_SUCCESS, VC_FOURCC, vc_uri_find_query(), vc_uri_path_extension(), and VC_CONTAINER_PRIVATE_T::verbosity.
Referenced by vc_container_open_reader().
 {
    VC_CONTAINER_STATUS_T status = VC_CONTAINER_SUCCESS;
    VC_CONTAINER_T *p_ctx = 0;
    const char *extension;
    VC_CONTAINER_PARAM_UNUSED(pfn_progress);
    VC_CONTAINER_PARAM_UNUSED(progress_userdata);
    VC_CONTAINER_PARAM_UNUSED(uri);
    /* Sanity check the i/o */
    if (!io || !io->pf_read || !io->pf_seek)
    {
       LOG_ERROR(0, "invalid i/o instance: %p", io);
       status = VC_CONTAINER_ERROR_INVALID_ARGUMENT;
       goto error;
    }
    /* Allocate our context before trying out the different readers / writers */
    p_ctx = malloc( sizeof(*p_ctx) + sizeof(*p_ctx->priv) + sizeof(*p_ctx->drm));
    if(!p_ctx) { status = VC_CONTAINER_ERROR_OUT_OF_MEMORY; goto error; }
    memset(p_ctx, 0, sizeof(*p_ctx) + sizeof(*p_ctx->priv) + sizeof(*p_ctx->drm));
    p_ctx->priv = (VC_CONTAINER_PRIVATE_T *)(p_ctx + 1);
    p_ctx->priv->verbosity = vc_container_log_get_default_verbosity();
    p_ctx->drm = (VC_CONTAINER_DRM_T *)(p_ctx->priv + 1);
    p_ctx->size = io->size;
    p_ctx->priv->io = io;
    p_ctx->priv->uri = io->uri_parts;
    /* If the uri has an extension, use it as a hint when loading the container */
    extension = vc_uri_path_extension(p_ctx->priv->uri);
    /* If the user has specified a container, then use that instead */
    vc_uri_find_query(p_ctx->priv->uri, 0, "container", &extension);
    status = vc_container_load_reader(p_ctx, extension);
    if (status != VC_CONTAINER_SUCCESS)
       goto error;
    p_ctx->priv->drm_filter = vc_container_filter_open(VC_FOURCC('d','r','m',' '),
       VC_FOURCC('u','n','k','n'), p_ctx, &status);
    if (status != VC_CONTAINER_SUCCESS)
    {
       /* Some other problem occurred aside from the filter not being appropriate or
          the stream not needing it. */
       if (status != VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED) goto error;
       /* Report no DRM and continue as normal */
       p_ctx->drm = NULL;
       status = VC_CONTAINER_SUCCESS;
    }
 end:
    if(p_status) *p_status = status;
    return p_ctx;
 error:
    if (p_ctx)
    {
       p_ctx->priv->io = NULL; /* The i/o doesn't belong to us */
       vc_container_close(p_ctx);
       p_ctx = NULL;
    }
    goto end;
 }
vc_container_open_writer()
VC_CONTAINER_T* vc_container_open_writer (const char * psz_uri, VC_CONTAINER_STATUS_T * status, VC_CONTAINER_PROGRESS_REPORT_FUNC_T pf_progress, void * progress_userdata)
Opens the media container pointed to by the URI for writing. This will create an an instance of a container writer and its associated context. The context returned will be initialised to sensible values.
The application will need to add all the media tracks using vc_container_control before it starts writing data using vc_container_write.
If the media isn't accessible or recognized, this will return a null pointer as well as an error code indicating why this failed.
Parameters
psz_uri Unified Resource Identifier pointing to the media container
status Returns the status of the operation
pf_progress User provided function pointer to a progess report function. Can be set to null if no progress report is wanted.
progress_userdata User provided pointer that will be passed during the progress report function call.
Returns
A pointer to the context of the new instance of the container writer. Returns NULL on failure.
Definition at line 128 of file containers.c.
References error(), extension, VC_CONTAINER_PRIVATE_T::io, LOG_DEBUG, VC_CONTAINER_IO_T::max_size, NULL, VC_CONTAINER_T::priv, status, VC_CONTAINER_PRIVATE_T::uri, VC_CONTAINER_IO_T::uri_parts, vc_container_close(), VC_CONTAINER_ERROR_OUT_OF_MEMORY, VC_CONTAINER_ERROR_OUT_OF_RESOURCES, vc_container_io_close(), VC_CONTAINER_IO_MODE_WRITE, vc_container_io_open(), vc_container_load_writer(), vc_container_log_get_default_verbosity(), VC_CONTAINER_PARAM_UNUSED, VC_CONTAINER_SUCCESS, vc_uri_find_query(), vc_uri_path_extension(), VC_CONTAINER_PRIVATE_T::verbosity, and WRITER_SPACE_SAFETY_MARGIN.
 {
    VC_CONTAINER_STATUS_T status = VC_CONTAINER_SUCCESS;
    VC_CONTAINER_T *p_ctx = 0;
    VC_CONTAINER_IO_T *io;
    const char *extension;
    VC_CONTAINER_PARAM_UNUSED(pfn_progress);
    VC_CONTAINER_PARAM_UNUSED(progress_userdata);
    /* Start by opening the URI */
    io = vc_container_io_open( uri, VC_CONTAINER_IO_MODE_WRITE, &status );
    if(!io) goto error;
    /* Make sure we have enough space available to start writing */
    if(io->max_size && io->max_size < WRITER_SPACE_SAFETY_MARGIN)
    {
       LOG_DEBUG(p_ctx, "not enough space available to open a writer");
       status = VC_CONTAINER_ERROR_OUT_OF_RESOURCES;
       goto error;
    }
    /* Allocate our context before trying out the different readers / writers */
    p_ctx = malloc( sizeof(*p_ctx) + sizeof(*p_ctx->priv));
    if(!p_ctx) { status = VC_CONTAINER_ERROR_OUT_OF_MEMORY; goto error; }
    memset(p_ctx, 0, sizeof(*p_ctx) + sizeof(*p_ctx->priv));
    p_ctx->priv = (VC_CONTAINER_PRIVATE_T *)(p_ctx + 1);
    p_ctx->priv->verbosity = vc_container_log_get_default_verbosity();
    p_ctx->priv->io = io;
    p_ctx->priv->uri = io->uri_parts;
    io = NULL; /* io now owned by the context */
    /* If the uri has an extension, use it as a hint when loading the container */
    extension = vc_uri_path_extension(p_ctx->priv->uri);
    /* If the user has specified a container, then use that instead */
    vc_uri_find_query(p_ctx->priv->uri, 0, "container", &extension);
    status = vc_container_load_writer(p_ctx, extension);
    if(status != VC_CONTAINER_SUCCESS) goto error;
  end:
    if(p_status) *p_status = status;
    return p_ctx;
 error:
    if(io) vc_container_io_close(io);
    if (p_ctx) vc_container_close(p_ctx);
    p_ctx = NULL;
    goto end;
 }
vc_container_read()
VC_CONTAINER_STATUS_T vc_container_read (VC_CONTAINER_T * context, VC_CONTAINER_PACKET_T * packet, VC_CONTAINER_READ_FLAGS_T flags)
Reads a data packet from a container reader. By default, the reader will read whatever packet comes next in the container and update the given VC_CONTAINER_PACKET_T structure with this packet's information. This behaviour can be changed using the VC_CONTAINER_READ_FLAGS_T.
VC_CONTAINER_READ_FLAG_INFO will instruct the reader to only return information on the following packet but not its actual data. The data can be retreived later by issuing another read request.
VC_CONTAINER_READ_FLAG_FORCE_TRACK will force the reader to read the next packet for the selected track (as present in the VC_CONTAINER_PACKET_T structure) instead of defaulting to reading the packet which comes next in the container.
VC_CONTAINER_READ_FLAG_SKIP will instruct the reader to skip the next packet. In this case it isn't necessary for the caller to pass a pointer to a VC_CONTAINER_PACKET_T structure unless the VC_CONTAINER_READ_FLAG_INFO is also given.
A combination of all these flags can be used.
Parameters
context Pointer to the context of the reader to use
packet Pointer to the VC_CONTAINER_PACKET_T structure describing the data packet This needs to be partially filled before the call (buffer, buffer_size)
flags Flags controlling the read operation
Returns
the status of the operation
Definition at line 244 of file containers.c.
References VC_CONTAINER_PACKET_T::data, VC_CONTAINER_TRACK_T::is_enabled, VC_CONTAINER_PRIVATE_T::packetizer_packet, VC_CONTAINER_PRIVATE_T::packetizing, VC_CONTAINER_T::priv, status, VC_CONTAINER_PACKET_T::track, VC_CONTAINER_T::tracks, VC_CONTAINER_T::tracks_num, VC_CONTAINER_ERROR_CONTINUE, VC_CONTAINER_ERROR_INVALID_ARGUMENT, VC_CONTAINER_READ_FLAG_FORCE_TRACK, VC_CONTAINER_READ_FLAG_INFO, and VC_CONTAINER_READ_FLAG_SKIP.
Referenced by TESTER_T::run().
 {
    VC_CONTAINER_STATUS_T status = VC_CONTAINER_ERROR_CONTINUE;
    VC_PACKETIZER_FLAGS_T packetizer_flags = 0;
    VC_PACKETIZER_T *packetizer;
    uint32_t force = flags & VC_CONTAINER_READ_FLAG_FORCE_TRACK;
    unsigned int i;
    if(!p_packet && !(flags & VC_CONTAINER_READ_FLAG_SKIP))
       return VC_CONTAINER_ERROR_INVALID_ARGUMENT;
    if(!p_packet && (flags & VC_CONTAINER_READ_FLAG_INFO))
       return VC_CONTAINER_ERROR_INVALID_ARGUMENT;
    if(p_packet && !p_packet->data && !(flags & (VC_CONTAINER_READ_FLAG_INFO | VC_CONTAINER_READ_FLAG_SKIP)))
       return VC_CONTAINER_ERROR_INVALID_ARGUMENT;
    if((flags & VC_CONTAINER_READ_FLAG_FORCE_TRACK) &&
       (!p_packet || p_packet->track >= p_ctx->tracks_num || !p_ctx->tracks[p_packet->track]->is_enabled))
       return VC_CONTAINER_ERROR_INVALID_ARGUMENT;
    /* Always having a packet structure to work with simplifies things */
    if(!p_packet)
       p_packet = &p_ctx->priv->packetizer_packet;
    /* Simple/Fast case first */
    if(!p_ctx->priv->packetizing)
    {
       status = container_read_packet( p_ctx, p_packet, flags );
       goto end;
    }
    if(flags & VC_CONTAINER_READ_FLAG_INFO)
       packetizer_flags |= VC_PACKETIZER_FLAG_INFO;
    if(flags & VC_CONTAINER_READ_FLAG_SKIP)
       packetizer_flags |= VC_PACKETIZER_FLAG_SKIP;
    /* Loop through all the packetized tracks first to see if we've got any
     * data to consume there */
    for(i = 0; i < p_ctx->tracks_num; i++)
    {
       VC_PACKETIZER_T *packetizer = p_ctx->tracks[i]->priv->packetizer;
       if(!p_ctx->tracks[i]->is_enabled || !packetizer ||
          (force && i != p_packet->track))
          continue;
       status = vc_packetizer_read(packetizer, p_packet, packetizer_flags);
       p_packet->track = i;
       if(status == VC_CONTAINER_SUCCESS)
          break;
    }
    if(i < p_ctx->tracks_num) /* We've got some data */
       goto end;
    /* Let's go and read some data from the actual container */
    while(1)
    {
       VC_CONTAINER_PACKET_T *tmp = &p_ctx->priv->packetizer_packet;
       tmp->track = p_packet->track;
       /* Let's check what the container has to offer */
       status = container_read_packet( p_ctx, tmp, force|VC_PACKETIZER_FLAG_INFO );
       if(status != VC_CONTAINER_SUCCESS)
          return status;
       if(!p_ctx->tracks[tmp->track]->priv->packetizer)
       {
          status = container_read_packet( p_ctx, p_packet, flags );
          break;
       }
       /* Feed data from the container onto the packetizer */
       packetizer = p_ctx->tracks[tmp->track]->priv->packetizer;
       tmp->data = p_ctx->priv->packetizer_buffer;
       tmp->buffer_size = PACKETIZER_BUFFER_SIZE;
       tmp->size = 0;
       status = container_read_packet( p_ctx, tmp, force );
       if(status != VC_CONTAINER_SUCCESS)
          return status;
       p_packet->track = tmp->track;
       vc_packetizer_push(packetizer, tmp);
       vc_packetizer_pop(packetizer, &tmp, VC_PACKETIZER_FLAG_FORCE_RELEASE_INPUT);
       status = vc_packetizer_read(packetizer, p_packet, packetizer_flags);
       if(status == VC_CONTAINER_SUCCESS)
          break;
    }
  end:
    if(status != VC_CONTAINER_SUCCESS)
       return status;
    if(p_packet && p_packet->dts > p_ctx->position)
       p_ctx->position = p_packet->dts;
    if(p_packet && p_packet->pts > p_ctx->position)
       p_ctx->position = p_packet->pts;
    return VC_CONTAINER_SUCCESS;
 }
vc_container_seek()
VC_CONTAINER_STATUS_T vc_container_seek (VC_CONTAINER_T * context, int64_t * offset, VC_CONTAINER_SEEK_MODE_T mode, VC_CONTAINER_SEEK_FLAGS_T flags)
Seek into a container reader.
Parameters
context Pointer to the context of the reader to use
offset Offset to seek to. Used as an input as well as output value.
mode Seeking mode requested.
flags Flags affecting the seeking operation.
Returns
the status of the operation
Definition at line 413 of file containers.c.
References LOG_DEBUG, offset, VC_CONTAINER_TRACK_PRIVATE_T::packetizer, VC_CONTAINER_PRIVATE_T::pf_seek, VC_CONTAINER_TRACK_T::priv, VC_CONTAINER_T::priv, status, VC_CONTAINER_T::tracks, VC_CONTAINER_T::tracks_num, VC_CONTAINER_SEEK_FLAG_FORWARD, VC_CONTAINER_SUCCESS, and vc_packetizer_reset().
Referenced by TESTER_T::run().
 {
    VC_CONTAINER_STATUS_T status;
    int64_t offset = *p_offset;
    unsigned int i;
    /* Reset all packetizers */
    for(i = 0; i < p_ctx->tracks_num; i++)
       if(p_ctx->tracks[i]->priv->packetizer)
          vc_packetizer_reset(p_ctx->tracks[i]->priv->packetizer);
    status = p_ctx->priv->pf_seek(p_ctx, p_offset, mode, flags);
    /* */
    if(status == VC_CONTAINER_SUCCESS && (flags & VC_CONTAINER_SEEK_FLAG_FORWARD) &&
       *p_offset < offset)
    {
       LOG_DEBUG(p_ctx, "container didn't seek forward as requested (%"PRIi64"/%"PRIi64")",
                 *p_offset, offset);
       for(i = 1; i <= 5 && *p_offset < offset; i++)
       {
          *p_offset = offset + i * i * 100000;
          status = p_ctx->priv->pf_seek(p_ctx, p_offset, mode, flags);
          if(status != VC_CONTAINER_SUCCESS) break;
       }
    }
    return status;
 }
vc_container_write()
VC_CONTAINER_STATUS_T vc_container_write (VC_CONTAINER_T * context, VC_CONTAINER_PACKET_T * packet)
Writes a data packet to a container writer.
Parameters
context Pointer to the context of the writer to use
packet Pointer to the VC_CONTAINER_PACKET_T structure describing the data packet
Returns
the status of the operation
Definition at line 344 of file containers.c.
References VC_CONTAINER_PACKET_T::buffer_size, VC_CONTAINER_PACKET_T::data, VC_CONTAINER_PRIVATE_T::drm_filter, VC_CONTAINER_PACKET_T::dts, VC_CONTAINER_PACKET_T::flags, VC_CONTAINER_PACKET_T::frame_size, VC_CONTAINER_PRIVATE_T::io, VC_CONTAINER_IO_T::max_size, VC_CONTAINER_PRIVATE_T::max_size, NULL, VC_CONTAINER_PACKET_T::num, VC_CONTAINER_IO_T::offset, VC_CONTAINER_PRIVATE_T::pf_write, VC_CONTAINER_T::priv, VC_CONTAINER_PACKET_T::pts, VC_CONTAINER_PACKET_T::size, VC_CONTAINER_T::size, status, VC_CONTAINER_PRIVATE_T::status, VC_CONTAINER_PRIVATE_T::tmp_io, VC_CONTAINER_PACKET_T::track, VC_CONTAINER_T::tracks_num, vc_container_control(), VC_CONTAINER_CONTROL_GET_DRM_METADATA, VC_CONTAINER_ERROR_INVALID_ARGUMENT, VC_CONTAINER_ERROR_LIMIT_REACHED, VC_CONTAINER_ERROR_NOT_READY, VC_CONTAINER_ERROR_OUT_OF_SPACE, VC_CONTAINER_ERROR_UNSUPPORTED_OPERATION, vc_container_filter_process(), VC_CONTAINER_PACKET_FLAG_FRAME_END, VC_CONTAINER_PACKET_FLAG_FRAME_START, VC_CONTAINER_SUCCESS, VC_CONTAINER_TIME_UNKNOWN, and WRITER_SPACE_SAFETY_MARGIN.
 {
    VC_CONTAINER_STATUS_T status;
    void * p_metadata_buffer = NULL;
    uint32_t metadata_length = 0;
    /* TODO: check other similar argument errors and non-stateless errors */
    if (!p_packet || !p_packet->data || p_packet->track >= p_ctx->tracks_num)
       return VC_CONTAINER_ERROR_INVALID_ARGUMENT;
    /* Check for a previous error */
    if(p_ctx->priv->status != VC_CONTAINER_SUCCESS && p_ctx->priv->status != VC_CONTAINER_ERROR_NOT_READY)
       return p_ctx->priv->status;
    /* Check we have enough space to write the data */
    if(p_ctx->priv->max_size &&
       p_ctx->size + p_packet->size + WRITER_SPACE_SAFETY_MARGIN > p_ctx->priv->max_size)
    {status = VC_CONTAINER_ERROR_LIMIT_REACHED; goto end;}
    if(p_ctx->priv->io->max_size &&
       p_ctx->size + p_packet->size + WRITER_SPACE_SAFETY_MARGIN +
          (p_ctx->priv->tmp_io ? p_ctx->priv->tmp_io->offset : 0) > p_ctx->priv->io->max_size)
    {status = VC_CONTAINER_ERROR_OUT_OF_SPACE; goto end;}
    /* If a filter is created, then send the packet to the filter for encryption. */
    if(p_ctx->priv->drm_filter)
    {
       status = vc_container_filter_process(p_ctx->priv->drm_filter, p_packet);
       if(status == VC_CONTAINER_SUCCESS)
       {
          /* Get the encryption metadata and send it to the output first. */
          if(vc_container_control(p_ctx, VC_CONTAINER_CONTROL_GET_DRM_METADATA,
              &p_metadata_buffer, &metadata_length) == VC_CONTAINER_SUCCESS && metadata_length > 0)
          {
             /* Make a packet up with the metadata in the payload and write it. */
             VC_CONTAINER_PACKET_T metadata_packet;
             metadata_packet.data = p_metadata_buffer;
             metadata_packet.buffer_size = metadata_length;
             metadata_packet.size = metadata_length;
             metadata_packet.frame_size = p_packet->frame_size + metadata_length;
             metadata_packet.pts = p_packet->pts;
             metadata_packet.dts = p_packet->dts;
             metadata_packet.num = p_packet->num;
             metadata_packet.track = p_packet->track;
             /* As this packet is written first, we must transfer any frame start
                flag from the following packet. Also, this packet can never have the end flag set. */
             metadata_packet.flags = p_packet->flags & ~VC_CONTAINER_PACKET_FLAG_FRAME_END;
             p_packet->pts = p_packet->dts = VC_CONTAINER_TIME_UNKNOWN;
             p_packet->flags &= ~VC_CONTAINER_PACKET_FLAG_FRAME_START;
             if(p_ctx->priv->pf_write(p_ctx, &metadata_packet) != VC_CONTAINER_SUCCESS) goto end;
          }
       }
       else if (status != VC_CONTAINER_ERROR_UNSUPPORTED_OPERATION)
       {
          /* Encryption was appropriate but a problem has occurred. Skip the write of data
             to the io and return the status to the caller. */
          goto end;
       }
    }
    status = p_ctx->priv->pf_write(p_ctx, p_packet);
  end:
    p_ctx->priv->status = status;
    return status;
 }