VideoCore Library: host_applications/linux/apps/dtoverlay/dtoverlay_main.c File Reference
dtoverlay_main.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <stdarg.h>
#include <sys/stat.h>
#include <dirent.h>
#include <errno.h>
#include <libfdt.h>
#include "dtoverlay.h"
#include "utils.h"
Classes
struct state_struct
Macros
#define CFG_DIR_1 "/sys/kernel/config"
#define CFG_DIR_2 "/config"
#define DT_SUBDIR "/device-tree"
#define WORK_DIR "/tmp/.dtoverlays"
#define OVERLAY_SRC_SUBDIR "overlays"
#define README_FILE "README"
#define DT_OVERLAYS_SUBDIR "overlays"
#define DTOVERLAY_PATH_MAX 128
#define DIR_MODE 0755
Typedefs
typedef struct state_struct STATE_T
Enumerations
enum {
OPT_ADD, OPT_REMOVE, OPT_REMOVE_FROM, OPT_LIST,
OPT_LIST_ALL, OPT_HELP
}
Functions
int main (int argc, const char **argv)
int dtparam_callback (int override_type, const char *override_value, DTBLOB_T *dtb, int node_off, const char *prop_name, int target_phandle, int target_off, int target_size, void *callback_state)
int dtparam_apply (DTBLOB_T *dtb, const char *override_name, const char *override_data, int data_len, const char *override_value, STRING_VEC_T *used_props)
int seq_filter (const struct dirent *de)
int seq_compare (const struct dirent **de1, const struct dirent **de2)
Variables
const char * cmd_name
const char * work_dir = WORK_DIR
const char * overlay_src_dir
const char * dt_overlays_dir
const char * error_file = NULL
int dry_run = 0
Macro Definition Documentation
CFG_DIR_1
#define CFG_DIR_1 "/sys/kernel/config"
Definition at line 43 of file dtoverlay_main.c.
CFG_DIR_2
#define CFG_DIR_2 "/config"
Definition at line 44 of file dtoverlay_main.c.
DIR_MODE
#define DIR_MODE 0755
Definition at line 51 of file dtoverlay_main.c.
DT_OVERLAYS_SUBDIR
#define DT_OVERLAYS_SUBDIR "overlays"
Definition at line 49 of file dtoverlay_main.c.
DT_SUBDIR
#define DT_SUBDIR "/device-tree"
Definition at line 45 of file dtoverlay_main.c.
DTOVERLAY_PATH_MAX
#define DTOVERLAY_PATH_MAX 128
Definition at line 50 of file dtoverlay_main.c.
OVERLAY_SRC_SUBDIR
#define OVERLAY_SRC_SUBDIR "overlays"
Definition at line 47 of file dtoverlay_main.c.
README_FILE
#define README_FILE "README"
Definition at line 48 of file dtoverlay_main.c.
WORK_DIR
#define WORK_DIR "/tmp/.dtoverlays"
Definition at line 46 of file dtoverlay_main.c.
Typedef Documentation
STATE_T
typedef struct state_struct STATE_T
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
OPT_ADD
OPT_REMOVE
OPT_REMOVE_FROM
OPT_LIST
OPT_LIST_ALL
OPT_HELP
Definition at line 54 of file dtoverlay_main.c.
      {
     OPT_ADD,
     OPT_REMOVE,
     OPT_REMOVE_FROM,
     OPT_LIST,
     OPT_LIST_ALL,
     OPT_HELP
 };
Function Documentation
dtparam_apply()
int dtparam_apply (DTBLOB_T * dtb, const char * override_name, const char * override_data, int data_len, const char * override_value, STRING_VEC_T * used_props)
Definition at line 361 of file dtoverlay_main.c.
References dtoverlay_error(), dtoverlay_foreach_override_target(), dtparam_callback(), FDT_ERR_NOSPACE, and NON_FATAL.
 {
     void *data;
     int err;
     /* Copy the override data in case it moves */
     data = malloc(data_len);
     if (data)
     {
     memcpy(data, override_data, data_len);
     err = dtoverlay_foreach_override_target(dtb, override_name,
                         data, data_len,
                         override_value,
                         dtparam_callback,
                         used_props);
     free(data);
     }
     else
     {
     dtoverlay_error("out of memory");
     err = NON_FATAL(FDT_ERR_NOSPACE);
     }
     return err;
 }
dtparam_callback()
int dtparam_callback (int override_type, const char * override_value, DTBLOB_T * dtb, int node_off, const char * prop_name, int target_phandle, int target_off, int target_size, void * callback_state)
Definition at line 331 of file dtoverlay_main.c.
References dtoverlay_override_one_target(), FDT_ERR_INTERNAL, string_vec_add(), and string_vec_find().
Referenced by dtparam_apply().
 {
     STRING_VEC_T *used_props = callback_state;
     char prop_id[80];
     int err;
     err = dtoverlay_override_one_target(override_type,
                     override_value,
                     dtb, node_off,
                     prop_name, target_phandle,
                     target_off, target_size,
                     callback_state);
     if ((err == 0) && (target_phandle != 0))
     {
     if (snprintf(prop_id, sizeof(prop_id), "%08x%s", target_phandle,
              prop_name) < 0)
         err = FDT_ERR_INTERNAL;
     else if (string_vec_find(used_props, prop_id, 0) < 0)
         string_vec_add(used_props, prop_id, 0);
     }
     return err;
 }
main()
int main (int argc, const char ** argv)
Definition at line 107 of file dtoverlay_main.c.
References NULL, and OPT_ADD.
 {
     int argn = 1;
     int opt = OPT_ADD;
     int is_dtparam;
     const char *overlay = NULL;
     const char **params = NULL;
     int ret = 0;
     STATE_T *state = NULL;
     const char *cfg_dir;
     cmd_name = argv[0];
     if (strrchr(cmd_name, '/'))
         cmd_name = strrchr(cmd_name, '/') + 1;
     is_dtparam = (strcmp(cmd_name, "dtparam") == 0);
     while ((argn < argc) && (argv[argn][0] == '-'))
     {
         const char *arg = argv[argn++];
         if (strcmp(arg, "-r") == 0)
         {
             if (opt != OPT_ADD)
                 usage();
             opt = OPT_REMOVE;
         }
         else if (strcmp(arg, "-R") == 0)
         {
             if (opt != OPT_ADD)
                 usage();
             opt = OPT_REMOVE_FROM;
         }
         else if (strcmp(arg, "-D") == 0)
         {
             if (opt != OPT_ADD)
                 usage();
             dry_run = 1;
             work_dir = ".";
         }
         else if ((strcmp(arg, "-l") == 0) ||
                  (strcmp(arg, "--list") == 0))
         {
             if (opt != OPT_ADD)
                 usage();
             opt = OPT_LIST;
         }
         else if ((strcmp(arg, "-a") == 0) ||
                  (strcmp(arg, "--listall") == 0) ||
                  (strcmp(arg, "--all") == 0))
         {
         if (opt != OPT_ADD)
         usage();
         opt = OPT_LIST_ALL;
     }
     else if (strcmp(arg, "-d") == 0)
     {
         if (argn == argc)
         usage();
         overlay_src_dir = argv[argn++];
     }
     else if (strcmp(arg, "-v") == 0)
     {
         opt_verbose = 1;
     }
     else if (strcmp(arg, "-h") == 0)
     {
         opt = OPT_HELP;
     }
     else
     {
         fprintf(stderr, "* unknown option '%s'\n", arg);
         usage();
     }
     }
     if ((opt == OPT_ADD) || (opt == OPT_REMOVE) ||
     (opt == OPT_REMOVE_FROM) || (opt == OPT_HELP))
     {
     if ((argn == argc) &&
         ((!is_dtparam &&
           ((opt == OPT_ADD) || (opt == OPT_HELP))) ||
          (is_dtparam && (opt == OPT_HELP))))
         usage();
     if (is_dtparam && (opt == OPT_ADD) && (argn == argc))
         opt = OPT_HELP;
     if (is_dtparam &&
         ((opt == OPT_ADD) || (opt == OPT_HELP)))
         overlay = "dtparam";
     else if (argn < argc)
         overlay = argv[argn++];
     }
     if ((opt == OPT_HELP) && (argn < argc))
     {
     params = &argv[argn];
     argn = argc;
     }
     if ((opt != OPT_ADD) && (argn != argc))
     usage();
     dtoverlay_enable_debug(opt_verbose);
     if (!overlay_src_dir)
     {
     /* Find the overlays and README */
     int i;
     for (i = 0; boot_dirs[i]; i++)
     {
         overlay_src_dir = sprintf_dup("%s/" OVERLAY_SRC_SUBDIR,
                       boot_dirs[i]);
         if (dir_exists(overlay_src_dir))
         break;
         free_string(overlay_src_dir);
         overlay_src_dir = NULL;
     }
     if (!overlay_src_dir)
         fatal_error("Failed to find overlays directory");
     }
     if (opt == OPT_HELP)
     {
     overlay_help(overlay, params);
     goto orderly_exit;
     }
     if (!dir_exists(work_dir))
     {
     if (mkdir(work_dir, DIR_MODE) != 0)
         fatal_error("Failed to create '%s' - %d", work_dir, errno);
     }
     error_file = sprintf_dup("%s/%s", work_dir, "error.dtb");
     cfg_dir = CFG_DIR_1 DT_SUBDIR;
     if (!dry_run && !dir_exists(cfg_dir))
     {
     root_check();
     cfg_dir = CFG_DIR_2;
     if (!dir_exists(cfg_dir))
     {
         if (mkdir(cfg_dir, DIR_MODE) != 0)
         fatal_error("Failed to create '%s' - %d", cfg_dir, errno);
     }
     cfg_dir = CFG_DIR_2 DT_SUBDIR;
     if (!dir_exists(cfg_dir) &&
         (run_cmd("mount -t configfs none '%s'", cfg_dir) != 0))
         fatal_error("Failed to mount configfs - %d", errno);
     }
     dt_overlays_dir = sprintf_dup("%s/%s", cfg_dir, DT_OVERLAYS_SUBDIR);
     if (!dir_exists(dt_overlays_dir))
     fatal_error("configfs overlays folder not found - incompatible kernel");
     if (!dry_run)
     {
         state = read_state(work_dir);
         if (!state)
             fatal_error("Failed to read state");
     }
     switch (opt)
     {
     case OPT_ADD:
     case OPT_REMOVE:
     case OPT_REMOVE_FROM:
         if (!dry_run)
         {
             root_check();
             run_cmd("which dtoverlay-pre >/dev/null 2>&1 && dtoverlay-pre");
         }
         break;
     default:
     break;
     }
     switch (opt)
     {
     case OPT_ADD:
     ret = dtoverlay_add(state, overlay, argc - argn, argv + argn);
     break;
     case OPT_REMOVE:
     ret = dtoverlay_remove(state, overlay, 0);
     break;
     case OPT_REMOVE_FROM:
     ret = dtoverlay_remove(state, overlay, 1);
     break;
     case OPT_LIST:
     ret = dtoverlay_list(state);
     break;
     case OPT_LIST_ALL:
     ret = dtoverlay_list_all(state);
     break;
     default:
     ret = 1;
     break;
     }
     switch (opt)
     {
     case OPT_ADD:
     case OPT_REMOVE:
     case OPT_REMOVE_FROM:
     if (!dry_run)
         run_cmd("which dtoverlay-post >/dev/null 2>&1 && dtoverlay-post");
     break;
     default:
     break;
     }
 orderly_exit:
     if (state)
     free_state(state);
     free_strings();
     if ((ret == 0) && error_file)
     unlink(error_file);
     return ret;
 }
seq_compare()
int seq_compare (const struct dirent ** de1, const struct dirent ** de2)
Definition at line 1038 of file dtoverlay_main.c.
 {
     int num1 = atoi((*de1)->d_name);
     int num2 = atoi((*de2)->d_name);
     if (num1 < num2)
         return -1;
     else if (num1 == num2)
         return 0;
     else
         return 1;
 }
seq_filter()
int seq_filter (const struct dirent * de)
Definition at line 1032 of file dtoverlay_main.c.
References dirent::d_name.
 {
     int num;
     return (sscanf(de->d_name, "%d_", &num) == 1);
 }
Variable Documentation
cmd_name
const char* cmd_name
Definition at line 99 of file dtoverlay_main.c.
dry_run
int dry_run = 0
Definition at line 105 of file dtoverlay_main.c.
dt_overlays_dir
const char* dt_overlays_dir
Definition at line 103 of file dtoverlay_main.c.
error_file
const char* error_file = NULL
Definition at line 104 of file dtoverlay_main.c.
overlay_src_dir
const char* overlay_src_dir
Definition at line 102 of file dtoverlay_main.c.
work_dir
const char* work_dir = WORK_DIR
Definition at line 101 of file dtoverlay_main.c.