VideoCore Library: interface/mmal/vc/mmal_vc_opaque_alloc.h File Reference
mmal_vc_opaque_alloc.h File Reference
#include <stdint.h>
#include "interface/mmal/mmal.h"
Typedefs
typedef uint32_t MMAL_OPAQUE_IMAGE_HANDLE_T
Functions
MMAL_OPAQUE_IMAGE_HANDLE_T mmal_vc_opaque_alloc (void)
MMAL_OPAQUE_IMAGE_HANDLE_T mmal_vc_opaque_alloc_desc (const char *description)
MMAL_STATUS_T mmal_vc_opaque_release (MMAL_OPAQUE_IMAGE_HANDLE_T h)
MMAL_STATUS_T mmal_vc_opaque_acquire (MMAL_OPAQUE_IMAGE_HANDLE_T h)
Typedef Documentation
MMAL_OPAQUE_IMAGE_HANDLE_T
typedef uint32_t MMAL_OPAQUE_IMAGE_HANDLE_T
Definition at line 39 of file mmal_vc_opaque_alloc.h.
Function Documentation
mmal_vc_opaque_acquire()
MMAL_STATUS_T mmal_vc_opaque_acquire (MMAL_OPAQUE_IMAGE_HANDLE_T h)
Acquire an additional reference to an opaque image.
Parameters
handle handle allocated earlier
Returns
MMAL_SUCCESS or error code if handle not found
mmal_vc_opaque_alloc()
MMAL_OPAQUE_IMAGE_HANDLE_T mmal_vc_opaque_alloc (void)
Allocate an opaque image on VideoCore.
Returns
allocated handle, or zero if allocation failed.
Definition at line 51 of file mmal_vc_opaque_alloc.c.
References mmal_vc_opaque_alloc_desc().
 {
    return mmal_vc_opaque_alloc_desc("?");
 }
mmal_vc_opaque_alloc_desc()
MMAL_OPAQUE_IMAGE_HANDLE_T mmal_vc_opaque_alloc_desc (const char * description)
Allocate an opaque image on VideoCore, providing a description.
Returns
allocated handle, or zero if allocation failed.
Definition at line 32 of file mmal_vc_opaque_alloc.c.
References mmal_worker_opaque_allocator::description, mmal_worker_opaque_allocator::handle, mmal_worker_opaque_allocator::header, len, MMAL_FALSE, MMAL_SUCCESS, mmal_vc_get_client(), mmal_vc_sendwait_message(), MMAL_WORKER_OPAQUE_ALLOCATOR_DESC, MMAL_WORKER_OPAQUE_MEM_ALLOC, mmal_worker_opaque_allocator::op, and vcos_safe_strcpy().
Referenced by mmal_vc_opaque_alloc().
 {
    MMAL_STATUS_T ret;
    MMAL_OPAQUE_IMAGE_HANDLE_T h = 0;
    mmal_worker_opaque_allocator msg;
    size_t len = sizeof(msg);
    msg.op = MMAL_WORKER_OPAQUE_MEM_ALLOC;
    vcos_safe_strcpy(msg.description, description, sizeof(msg.description), 0);
    ret = mmal_vc_sendwait_message(mmal_vc_get_client(),
                                   &msg.header, sizeof(msg),
                                   MMAL_WORKER_OPAQUE_ALLOCATOR_DESC,
                                   &msg, &len, MMAL_FALSE);
    if (ret == MMAL_SUCCESS)
    {
       h = msg.handle;
    }
    return h;
 }
mmal_vc_opaque_release()
MMAL_STATUS_T mmal_vc_opaque_release (MMAL_OPAQUE_IMAGE_HANDLE_T h)
Release an opaque image.
Parameters
handle handle allocated earlier
Returns
MMAL_SUCCESS or error code if handle not found