VideoCore Library: opensrc/helpers/libfdt/fdt_sw.c File Reference
fdt_sw.c File Reference
#include "libfdt_env.h"
#include <fdt.h>
#include <libfdt.h>
#include "libfdt_internal.h"
Macros
#define FDT_SW_PROBE(fdt)
#define FDT_SW_PROBE_MEMRSV(fdt)
#define FDT_SW_PROBE_STRUCT(fdt)
Functions
int fdt_create_with_flags (void *buf, int bufsize, uint32_t flags)
int fdt_create (void *buf, int bufsize)
int fdt_resize (void *fdt, void *buf, int bufsize)
int fdt_add_reservemap_entry (void *fdt, uint64_t addr, uint64_t size)
int fdt_finish_reservemap (void *fdt)
int fdt_begin_node (void *fdt, const char *name)
int fdt_end_node (void *fdt)
int fdt_property_placeholder (void *fdt, const char *name, int len, void **valp)
int fdt_property (void *fdt, const char *name, const void *val, int len)
int fdt_finish (void *fdt)
Macro Definition Documentation
FDT_SW_PROBE
#define FDT_SW_PROBE (fdt)
Value:
{ \
        int err; \
        if ((err = fdt_sw_probe_(fdt)) != 0) \
            return err; \
    }
Definition at line 22 of file fdt_sw.c.
Referenced by fdt_resize().
FDT_SW_PROBE_MEMRSV
#define FDT_SW_PROBE_MEMRSV (fdt)
Value:
{ \
        int err; \
        if ((err = fdt_sw_probe_memrsv_(fdt)) != 0) \
            return err; \
    }
Definition at line 46 of file fdt_sw.c.
Referenced by fdt_add_reservemap_entry().
FDT_SW_PROBE_STRUCT
#define FDT_SW_PROBE_STRUCT (fdt)
Value:
{ \
        int err; \
        if ((err = fdt_sw_probe_struct_(fdt)) != 0) \
            return err; \
    }
Definition at line 72 of file fdt_sw.c.
Referenced by fdt_begin_node(), fdt_end_node(), fdt_finish(), and fdt_property_placeholder().
Function Documentation
fdt_add_reservemap_entry()
int fdt_add_reservemap_entry (void * fdt, uint64_t addr, uint64_t size)
Definition at line 180 of file fdt_sw.c.
References fdt_reserve_entry::address, FDT_ERR_NOSPACE, fdt_off_dt_struct, FDT_SW_PROBE_MEMRSV, fdt_totalsize, and offset.
Referenced by fdt_finish_reservemap().
 {
     struct fdt_reserve_entry *re;
     int offset;
     FDT_SW_PROBE_MEMRSV(fdt);
     offset = fdt_off_dt_struct(fdt);
     if ((offset + sizeof(*re)) > fdt_totalsize(fdt))
         return -FDT_ERR_NOSPACE;
     re = (struct fdt_reserve_entry *)((char *)fdt + offset);
     re->address = cpu_to_fdt64(addr);
     re->size = cpu_to_fdt64(size);
     fdt_set_off_dt_struct(fdt, offset + sizeof(*re));
     return 0;
 }
fdt_begin_node()
int fdt_begin_node (void * fdt, const char * name)
Definition at line 211 of file fdt_sw.c.
References FDT_SW_PROBE_STRUCT.
Referenced by fdt_create_empty_tree().
 {
     struct fdt_node_header *nh;
     int namelen;
     FDT_SW_PROBE_STRUCT(fdt);
     namelen = strlen(name) + 1;
     nh = fdt_grab_space_(fdt, sizeof(*nh) + FDT_TAGALIGN(namelen));
     if (! nh)
         return -FDT_ERR_NOSPACE;
     nh->tag = cpu_to_fdt32(FDT_BEGIN_NODE);
     memcpy(nh->name, name, namelen);
     return 0;
 }
fdt_create()
int fdt_create (void * buf, int bufsize)
fdt_create - begin creation of a new fdt : pointer to memory allocated where fdt will be created : size of the memory space at fdt
fdt_create() is equivalent to fdt_create_with_flags() with flags=0.
returns: 0, on success -FDT_ERR_NOSPACE, bufsize is insufficient for a minimal fdt
Definition at line 139 of file fdt_sw.c.
References fdt_create_with_flags().
Referenced by fdt_create_empty_tree().
 {
     return fdt_create_with_flags(buf, bufsize, 0);
 }
fdt_create_with_flags()
int fdt_create_with_flags (void * buf, int bufsize, uint32_t flags)
fdt_create_with_flags - begin creation of a new fdt : pointer to memory allocated where fdt will be created : size of the memory space at fdt : a valid combination of FDT_CREATE_FLAG_ flags, or 0.
fdt_create_with_flags() begins the process of creating a new fdt with the sequential write interface.
fdt creation process must end with fdt_finished() to produce a valid fdt.
returns: 0, on success -FDT_ERR_NOSPACE, bufsize is insufficient for a minimal fdt -FDT_ERR_BADFLAGS, flags is not valid
Definition at line 105 of file fdt_sw.c.
References FDT_ALIGN, FDT_CREATE_FLAGS_ALL, FDT_ERR_BADFLAGS, FDT_ERR_NOSPACE, FDT_LAST_SUPPORTED_VERSION, fdt_off_mem_rsvmap, and FDT_SW_MAGIC.
Referenced by fdt_create().
 {
     const size_t hdrsize = FDT_ALIGN(sizeof(struct fdt_header),
                      sizeof(struct fdt_reserve_entry));
     void *fdt = buf;
     if (bufsize < hdrsize)
         return -FDT_ERR_NOSPACE;
     if (flags & ~FDT_CREATE_FLAGS_ALL)
         return -FDT_ERR_BADFLAGS;
     memset(buf, 0, bufsize);
     /*
      * magic and last_comp_version keep intermediate state during the fdt
      * creation process, which is replaced with the proper FDT format by
      * fdt_finish().
      *
      * flags should be accessed with sw_flags().
      */
     fdt_set_magic(fdt, FDT_SW_MAGIC);
     fdt_set_version(fdt, FDT_LAST_SUPPORTED_VERSION);
     fdt_set_last_comp_version(fdt, flags);
     fdt_set_totalsize(fdt,  bufsize);
     fdt_set_off_mem_rsvmap(fdt, hdrsize);
     fdt_set_off_dt_struct(fdt, fdt_off_mem_rsvmap(fdt));
     fdt_set_off_dt_strings(fdt, 0);
     return 0;
 }
fdt_end_node()
int fdt_end_node (void * fdt)
Definition at line 228 of file fdt_sw.c.
References FDT_SW_PROBE_STRUCT.
Referenced by fdt_create_empty_tree().
 {
     fdt32_t *en;
     FDT_SW_PROBE_STRUCT(fdt);
     en = fdt_grab_space_(fdt, FDT_TAGSIZE);
     if (! en)
         return -FDT_ERR_NOSPACE;
     *en = cpu_to_fdt32(FDT_END_NODE);
     return 0;
 }
fdt_finish()
int fdt_finish (void * fdt)
Definition at line 329 of file fdt_sw.c.
References FDT_SW_PROBE_STRUCT, offset, and fdt_property::tag.
Referenced by fdt_create_empty_tree().
 {
     char *p = (char *)fdt;
     fdt32_t *end;
     int oldstroffset, newstroffset;
     uint32_t tag;
     int offset, nextoffset;
     FDT_SW_PROBE_STRUCT(fdt);
     /* Add terminator */
     end = fdt_grab_space_(fdt, sizeof(*end));
     if (! end)
         return -FDT_ERR_NOSPACE;
     *end = cpu_to_fdt32(FDT_END);
     /* Relocate the string table */
     oldstroffset = fdt_totalsize(fdt) - fdt_size_dt_strings(fdt);
     newstroffset = fdt_off_dt_struct(fdt) + fdt_size_dt_struct(fdt);
     memmove(p + newstroffset, p + oldstroffset, fdt_size_dt_strings(fdt));
     fdt_set_off_dt_strings(fdt, newstroffset);
     /* Walk the structure, correcting string offsets */
     offset = 0;
     while ((tag = fdt_next_tag(fdt, offset, &nextoffset)) != FDT_END) {
         if (tag == FDT_PROP) {
             struct fdt_property *prop =
                 fdt_offset_ptr_w_(fdt, offset);
             int nameoff;
             nameoff = fdt32_to_cpu(prop->nameoff);
             nameoff += fdt_size_dt_strings(fdt);
             prop->nameoff = cpu_to_fdt32(nameoff);
         }
         offset = nextoffset;
     }
     if (nextoffset < 0)
         return nextoffset;
     /* Finally, adjust the header */
     fdt_set_totalsize(fdt, newstroffset + fdt_size_dt_strings(fdt));
     /* And fix up fields that were keeping intermediate state. */
     fdt_set_last_comp_version(fdt, FDT_FIRST_SUPPORTED_VERSION);
     fdt_set_magic(fdt, FDT_MAGIC);
     return 0;
 }
fdt_finish_reservemap()
int fdt_finish_reservemap (void * fdt)
Definition at line 200 of file fdt_sw.c.
References fdt_add_reservemap_entry(), and fdt_totalsize.
Referenced by fdt_create_empty_tree().
 {
     int err = fdt_add_reservemap_entry(fdt, 0LL, 0LL);
     if (err)
         return err;
     fdt_set_off_dt_strings(fdt, fdt_totalsize(fdt));
     return 0;
 }
fdt_property()
int fdt_property (void * fdt, const char * name, const void * val, int len)
Definition at line 317 of file fdt_sw.c.
References fdt_property_placeholder().
 {
     void *ptr;
     int ret;
     ret = fdt_property_placeholder(fdt, name, len, &ptr);
     if (ret)
         return ret;
     memcpy(ptr, val, len);
     return 0;
 }
fdt_property_placeholder()
int fdt_property_placeholder (void * fdt, const char * name, int len, void ** valp)
Definition at line 285 of file fdt_sw.c.
References allocated, FDT_SW_PROBE_STRUCT, and fdt_property::nameoff.
Referenced by fdt_property().
 {
     struct fdt_property *prop;
     int nameoff;
     int allocated;
     FDT_SW_PROBE_STRUCT(fdt);
     /* String de-duplication can be slow, _NO_NAME_DEDUP skips it */
     if (sw_flags(fdt) & FDT_CREATE_FLAG_NO_NAME_DEDUP) {
         allocated = 1;
         nameoff = fdt_add_string_(fdt, name);
     } else {
         nameoff = fdt_find_add_string_(fdt, name, &allocated);
     }
     if (nameoff == 0)
         return -FDT_ERR_NOSPACE;
     prop = fdt_grab_space_(fdt, sizeof(*prop) + FDT_TAGALIGN(len));
     if (! prop) {
         if (allocated)
             fdt_del_last_string_(fdt, name);
         return -FDT_ERR_NOSPACE;
     }
     prop->tag = cpu_to_fdt32(FDT_PROP);
     prop->nameoff = cpu_to_fdt32(nameoff);
     prop->len = cpu_to_fdt32(len);
     *valp = prop->data;
     return 0;
 }
fdt_resize()
int fdt_resize (void * fdt, void * buf, int bufsize)
Definition at line 144 of file fdt_sw.c.
References FDT_ERR_INTERNAL, FDT_ERR_NOSPACE, fdt_off_dt_strings, fdt_off_dt_struct, fdt_size_dt_strings, fdt_size_dt_struct, FDT_SW_PROBE, and fdt_totalsize.
 {
     size_t headsize, tailsize;
     char *oldtail, *newtail;
     FDT_SW_PROBE(fdt);
     headsize = fdt_off_dt_struct(fdt) + fdt_size_dt_struct(fdt);
     tailsize = fdt_size_dt_strings(fdt);
     if ((headsize + tailsize) > fdt_totalsize(fdt))
         return -FDT_ERR_INTERNAL;
     if ((headsize + tailsize) > bufsize)
         return -FDT_ERR_NOSPACE;
     oldtail = (char *)fdt + fdt_totalsize(fdt) - tailsize;
     newtail = (char *)buf + bufsize - tailsize;
     /* Two cases to avoid clobbering data if the old and new
      * buffers partially overlap */
     if (buf <= fdt) {
         memmove(buf, fdt, headsize);
         memmove(newtail, oldtail, tailsize);
     } else {
         memmove(newtail, oldtail, tailsize);
         memmove(buf, fdt, headsize);
     }
     fdt_set_totalsize(buf, bufsize);
     if (fdt_off_dt_strings(buf))
         fdt_set_off_dt_strings(buf, bufsize);
     return 0;
 }