VideoCore Library: interface/vcos/generic/vcos_generic_blockpool.h File Reference
vcos_generic_blockpool.h File Reference
#include "interface/vcos/vcos_types.h"
Classes
struct VCOS_BLOCKPOOL_HEADER_TAG
struct VCOS_BLOCKPOOL_SUBPOOL_TAG
struct VCOS_BLOCKPOOL_TAG
Macros
#define VCOS_BLOCKPOOL_SUBPOOL_BITS 3
#define VCOS_BLOCKPOOL_MAX_SUBPOOLS (1 << VCOS_BLOCKPOOL_SUBPOOL_BITS)
#define INDEX_OFFSET 1
#define VCOS_BLOCKPOOL_HANDLE_GET_INDEX(h) (((h) >> VCOS_BLOCKPOOL_SUBPOOL_BITS) - INDEX_OFFSET)
#define VCOS_BLOCKPOOL_HANDLE_GET_SUBPOOL(h) ((h) & ((1 << VCOS_BLOCKPOOL_SUBPOOL_BITS) - 1))
#define VCOS_BLOCKPOOL_HANDLE_CREATE(i, s) ((((i) + INDEX_OFFSET) << VCOS_BLOCKPOOL_SUBPOOL_BITS) | (s))
#define VCOS_BLOCKPOOL_INVALID_HANDLE 0
#define VCOS_BLOCKPOOL_ALIGN_DEFAULT sizeof(unsigned long)
#define VCOS_BLOCKPOOL_FLAG_NONE 0
#define VCOS_BLOCKPOOL_ROUND_UP(x, s) (((x) + ((s) - 1)) & ~((s) - 1))
#define VCOS_BLOCKPOOL_SIZE(num_blocks, block_size, align)
#define VCOS_BLOCKPOOL_IS_VALID_HANDLE_FORMAT(handle, max_blocks)
Typedefs
typedef struct VCOS_BLOCKPOOL_HEADER_TAG VCOS_BLOCKPOOL_HEADER_T
typedef struct VCOS_BLOCKPOOL_SUBPOOL_TAG VCOS_BLOCKPOOL_SUBPOOL_T
typedef struct VCOS_BLOCKPOOL_TAG VCOS_BLOCKPOOL_T
Functions
VCOSPRE_ VCOS_STATUS_T VCOSPOST_ vcos_generic_blockpool_init (VCOS_BLOCKPOOL_T *pool, VCOS_UNSIGNED num_blocks, VCOS_UNSIGNED block_size, void *start, VCOS_UNSIGNED pool_size, VCOS_UNSIGNED align, VCOS_UNSIGNED flags, const char *name)
VCOSPRE_ VCOS_STATUS_T VCOSPOST_ vcos_generic_blockpool_create_on_heap (VCOS_BLOCKPOOL_T *pool, VCOS_UNSIGNED num_blocks, VCOS_UNSIGNED block_size, VCOS_UNSIGNED align, VCOS_UNSIGNED flags, const char *name)
VCOSPRE_ VCOS_STATUS_T VCOSPOST_ vcos_generic_blockpool_extend (VCOS_BLOCKPOOL_T *pool, VCOS_UNSIGNED num_extensions, VCOS_UNSIGNED num_blocks)
VCOSPRE_ void VCOSPOST_ * vcos_generic_blockpool_alloc (VCOS_BLOCKPOOL_T *pool)
VCOSPRE_ void VCOSPOST_ * vcos_generic_blockpool_calloc (VCOS_BLOCKPOOL_T *pool)
VCOSPRE_ void VCOSPOST_ vcos_generic_blockpool_free (void *block)
VCOSPRE_ VCOS_UNSIGNED VCOSPOST_ vcos_generic_blockpool_available_count (VCOS_BLOCKPOOL_T *pool)
VCOSPRE_ VCOS_UNSIGNED VCOSPOST_ vcos_generic_blockpool_used_count (VCOS_BLOCKPOOL_T *pool)
VCOSPRE_ void VCOSPOST_ vcos_generic_blockpool_delete (VCOS_BLOCKPOOL_T *pool)
VCOSPRE_ uint32_t VCOSPOST_ vcos_generic_blockpool_elem_to_handle (void *block)
VCOSPRE_ void VCOSPOST_ * vcos_generic_blockpool_elem_from_handle (VCOS_BLOCKPOOL_T *pool, uint32_t handle)
VCOSPRE_ uint32_t VCOSPOST_ vcos_generic_blockpool_is_valid_elem (VCOS_BLOCKPOOL_T *pool, const void *block)
Detailed Description
This provides a generic, thread safe implementation of a VCOS block pool fixed size memory allocator.
Definition in file vcos_generic_blockpool.h.
Macro Definition Documentation
INDEX_OFFSET
#define INDEX_OFFSET 1
Definition at line 58 of file vcos_generic_blockpool.h.
VCOS_BLOCKPOOL_ALIGN_DEFAULT
#define VCOS_BLOCKPOOL_ALIGN_DEFAULT sizeof(unsigned long)
Definition at line 70 of file vcos_generic_blockpool.h.
Referenced by _vcos_named_semaphore_init(), vcos_generic_blockpool_init(), and vcos_msgq_pool_create().
VCOS_BLOCKPOOL_FLAG_NONE
#define VCOS_BLOCKPOOL_FLAG_NONE 0
Definition at line 71 of file vcos_generic_blockpool.h.
VCOS_BLOCKPOOL_HANDLE_CREATE
#define VCOS_BLOCKPOOL_HANDLE_CREATE (i, s) ((((i) + INDEX_OFFSET) << VCOS_BLOCKPOOL_SUBPOOL_BITS) | (s))
Definition at line 66 of file vcos_generic_blockpool.h.
Referenced by vcos_generic_blockpool_elem_to_handle().
VCOS_BLOCKPOOL_HANDLE_GET_INDEX
#define VCOS_BLOCKPOOL_HANDLE_GET_INDEX (h) (((h) >> VCOS_BLOCKPOOL_SUBPOOL_BITS) - INDEX_OFFSET)
Definition at line 60 of file vcos_generic_blockpool.h.
Referenced by vcos_generic_blockpool_elem_from_handle().
VCOS_BLOCKPOOL_HANDLE_GET_SUBPOOL
#define VCOS_BLOCKPOOL_HANDLE_GET_SUBPOOL (h) ((h) & ((1 << VCOS_BLOCKPOOL_SUBPOOL_BITS) - 1))
Definition at line 63 of file vcos_generic_blockpool.h.
Referenced by vcos_generic_blockpool_elem_from_handle().
VCOS_BLOCKPOOL_INVALID_HANDLE
#define VCOS_BLOCKPOOL_INVALID_HANDLE 0
Definition at line 69 of file vcos_generic_blockpool.h.
VCOS_BLOCKPOOL_IS_VALID_HANDLE_FORMAT
#define VCOS_BLOCKPOOL_IS_VALID_HANDLE_FORMAT (handle, max_blocks)
Value:
((handle) != VCOS_BLOCKPOOL_INVALID_HANDLE \
     && VCOS_BLOCKPOOL_HANDLE_GET_INDEX((handle)) < (max_blocks))
Sanity check to verify whether a handle is potentially a blockpool handle when the pool pointer is not available.
If the pool pointer is available use vcos_blockpool_elem_to_handle instead.
Parameters
handle the handle to verify
max_blocks the expected maximum number of block in the pool that the handle belongs to.
Definition at line 159 of file vcos_generic_blockpool.h.
VCOS_BLOCKPOOL_MAX_SUBPOOLS
#define VCOS_BLOCKPOOL_MAX_SUBPOOLS (1 << VCOS_BLOCKPOOL_SUBPOOL_BITS)
Definition at line 51 of file vcos_generic_blockpool.h.
Referenced by _vcos_named_semaphore_init(), vcos_generic_blockpool_elem_to_handle(), and vcos_generic_blockpool_extend().
VCOS_BLOCKPOOL_ROUND_UP
#define VCOS_BLOCKPOOL_ROUND_UP (x, s) (((x) + ((s) - 1)) & ~((s) - 1))
Definition at line 132 of file vcos_generic_blockpool.h.
Referenced by vcos_generic_blockpool_init().
VCOS_BLOCKPOOL_SIZE
#define VCOS_BLOCKPOOL_SIZE (num_blocks, block_size, align)
Value:
((VCOS_BLOCKPOOL_ROUND_UP((block_size) + (align >= 4096 ? 32 : 0) + sizeof(VCOS_BLOCKPOOL_HEADER_T), \
                             (align)) * (num_blocks)) + (align))
Calculates the size in bytes required for a block pool containing num_blocks of size block_size plus any overheads.
The block pool header (VCOS_BLOCKPOOL_T) is allocated separately
Overheads: block_size + header must be rounded up to meet the required alignment The start of the first block may need to be up to align bytes into the given buffer because statically allocated buffers within structures are not guaranteed to be aligned as required.
Definition at line 145 of file vcos_generic_blockpool.h.
Referenced by vcos_generic_blockpool_alloc(), vcos_generic_blockpool_create_on_heap(), vcos_generic_blockpool_delete(), and vcos_generic_blockpool_init().
VCOS_BLOCKPOOL_SUBPOOL_BITS
#define VCOS_BLOCKPOOL_SUBPOOL_BITS 3
Bits 0 to (VCOS_BLOCKPOOL_SUBPOOL_BITS - 1) are used to store the subpool id.
Definition at line 50 of file vcos_generic_blockpool.h.
Typedef Documentation
VCOS_BLOCKPOOL_HEADER_T
typedef struct VCOS_BLOCKPOOL_HEADER_TAG VCOS_BLOCKPOOL_HEADER_T
VCOS_BLOCKPOOL_SUBPOOL_T
typedef struct VCOS_BLOCKPOOL_SUBPOOL_TAG VCOS_BLOCKPOOL_SUBPOOL_T
VCOS_BLOCKPOOL_T
typedef struct VCOS_BLOCKPOOL_TAG VCOS_BLOCKPOOL_T
Function Documentation
vcos_generic_blockpool_alloc()
VCOSPRE_ void VCOSPOST_* vcos_generic_blockpool_alloc (VCOS_BLOCKPOOL_T * pool)
Definition at line 264 of file vcos_generic_blockpool.c.
References VCOS_BLOCKPOOL_TAG::align, ASSERT_POOL, VCOS_BLOCKPOOL_SUBPOOL_TAG::available_blocks, VCOS_BLOCKPOOL_TAG::block_data_size, VCOS_BLOCKPOOL_TAG::mutex, VCOS_BLOCKPOOL_TAG::name, NULL, VCOS_BLOCKPOOL_TAG::num_extension_blocks, VCOS_BLOCKPOOL_TAG::num_subpools, VCOS_BLOCKPOOL_SUBPOOL_TAG::start, VCOS_BLOCKPOOL_TAG::subpools, VCOS_BLOCKPOOL_SIZE, VCOS_FUNCTION, vcos_malloc(), and vcos_mutex_lock().
Referenced by vcos_generic_blockpool_calloc().
 {
    VCOS_UNSIGNED i;
    void* ret = NULL;
    VCOS_BLOCKPOOL_SUBPOOL_T *subpool = NULL;
    ASSERT_POOL(pool);
    vcos_mutex_lock(&pool->mutex);
    /* Starting with the main pool try and find a free block */
    for (i = 0; i < pool->num_subpools; ++i)
    {
       if (pool->subpools[i].start && pool->subpools[i].available_blocks > 0)
       {
          subpool = &pool->subpools[i];
          break; /* Found a subpool with free blocks */
       }
    }
    if (! subpool)
    {
       /* All current subpools are full, try to allocate a new one */
       for (i = 1; i < pool->num_subpools; ++i)
       {
          if (! pool->subpools[i].start)
          {
             VCOS_BLOCKPOOL_SUBPOOL_T *s = &pool->subpools[i];
             size_t size = VCOS_BLOCKPOOL_SIZE(pool->num_extension_blocks,
                   pool->block_data_size, pool->align);
             void *mem = vcos_malloc(size, pool->name);
             if (mem)
             {
                vcos_log_trace("%s: Allocated subpool %d", VCOS_FUNCTION, i);
                vcos_generic_blockpool_subpool_init(pool, s, mem, size,
                      pool->num_extension_blocks,
                      pool->align,
                      VCOS_BLOCKPOOL_SUBPOOL_FLAG_OWNS_MEM |
                      VCOS_BLOCKPOOL_SUBPOOL_FLAG_EXTENSION);
                subpool = s;
                break; /* Created a subpool */
             }
             else
             {
                vcos_log_warn("%s: Failed to allocate subpool", VCOS_FUNCTION);
             }
          }
       }
    }
    if (subpool)
    {
       /* Remove from free list */
       VCOS_BLOCKPOOL_HEADER_T* nb = subpool->free_list;
       vcos_assert(subpool->free_list);
       subpool->free_list = nb->owner.next;
       /* Owner is pool so free can be called without passing pool
        * as a parameter */
       nb->owner.subpool = subpool;
       ret = nb + 1; /* Return pointer to block data */
       --(subpool->available_blocks);
    }
    vcos_mutex_unlock(&pool->mutex);
    VCOS_BLOCKPOOL_DEBUG_LOG("pool %p subpool %p ret %p", pool, subpool, ret);
    if (ret)
    {
       vcos_assert(ret > subpool->start);
       vcos_assert(ret < subpool->end);
    }
    return ret;
 }
vcos_generic_blockpool_available_count()
VCOSPRE_ VCOS_UNSIGNED VCOSPOST_ vcos_generic_blockpool_available_count (VCOS_BLOCKPOOL_T * pool)
Definition at line 385 of file vcos_generic_blockpool.c.
References ASSERT_POOL, ASSERT_SUBPOOL, VCOS_BLOCKPOOL_SUBPOOL_TAG::available_blocks, VCOS_BLOCKPOOL_TAG::mutex, VCOS_BLOCKPOOL_TAG::num_extension_blocks, VCOS_BLOCKPOOL_TAG::num_subpools, VCOS_BLOCKPOOL_SUBPOOL_TAG::start, VCOS_BLOCKPOOL_TAG::subpools, vcos_mutex_lock(), and vcos_mutex_unlock().
 {
    VCOS_UNSIGNED ret = 0;
    VCOS_UNSIGNED i;
    ASSERT_POOL(pool);
    vcos_mutex_lock(&pool->mutex);
    for (i = 0; i < pool->num_subpools; ++i)
    {
       VCOS_BLOCKPOOL_SUBPOOL_T *subpool = &pool->subpools[i];
       ASSERT_SUBPOOL(subpool);
       /* Assume the malloc of sub pool would succeed */
       if (subpool->start)
          ret += subpool->available_blocks;
       else
          ret += pool->num_extension_blocks;
    }
    vcos_mutex_unlock(&pool->mutex);
    return ret;
 }
vcos_generic_blockpool_calloc()
VCOSPRE_ void VCOSPOST_* vcos_generic_blockpool_calloc (VCOS_BLOCKPOOL_T * pool)
Definition at line 339 of file vcos_generic_blockpool.c.
References VCOS_BLOCKPOOL_TAG::block_data_size, and vcos_generic_blockpool_alloc().
 {
    void* ret = vcos_generic_blockpool_alloc(pool);
    if (ret)
       memset(ret, 0, pool->block_data_size);
    return ret;
 }
vcos_generic_blockpool_create_on_heap()
VCOSPRE_ VCOS_STATUS_T VCOSPOST_ vcos_generic_blockpool_create_on_heap (VCOS_BLOCKPOOL_T * pool, VCOS_UNSIGNED num_blocks, VCOS_UNSIGNED block_size, VCOS_UNSIGNED align, VCOS_UNSIGNED flags, const char * name)
Definition at line 202 of file vcos_generic_blockpool.c.
References fail, VCOS_BLOCKPOOL_SUBPOOL_TAG::flags, status, VCOS_BLOCKPOOL_TAG::subpools, VCOS_BLOCKPOOL_SIZE, VCOS_BLOCKPOOL_SUBPOOL_FLAG_OWNS_MEM, VCOS_ENOMEM, vcos_free(), VCOS_FUNCTION, vcos_generic_blockpool_init(), vcos_malloc(), and VCOS_SUCCESS.
 {
    VCOS_STATUS_T status = VCOS_SUCCESS;
    size_t size = VCOS_BLOCKPOOL_SIZE(num_blocks, block_size, align);
    void* mem = vcos_malloc(size, name);
    vcos_log_trace("%s: num_blocks %d block_size %d name %s",
          VCOS_FUNCTION, num_blocks, block_size, name);
    if (! mem)
       return VCOS_ENOMEM;
    status = vcos_generic_blockpool_init(pool, num_blocks,
          block_size, mem, size, align, flags, name);
    if (status != VCOS_SUCCESS)
       goto fail;
    pool->subpools[0].flags |= VCOS_BLOCKPOOL_SUBPOOL_FLAG_OWNS_MEM;
    return status;
 fail:
    vcos_free(mem);
    return status;
 }
vcos_generic_blockpool_delete()
VCOSPRE_ void VCOSPOST_ vcos_generic_blockpool_delete (VCOS_BLOCKPOOL_T * pool)
Definition at line 426 of file vcos_generic_blockpool.c.
References VCOS_BLOCKPOOL_TAG::align, ASSERT_POOL, ASSERT_SUBPOOL, VCOS_BLOCKPOOL_TAG::block_data_size, VCOS_BLOCKPOOL_SUBPOOL_TAG::flags, VCOS_BLOCKPOOL_SUBPOOL_TAG::mem, VCOS_BLOCKPOOL_TAG::mutex, NULL, VCOS_BLOCKPOOL_SUBPOOL_TAG::num_blocks, VCOS_BLOCKPOOL_TAG::num_subpools, VCOS_BLOCKPOOL_SUBPOOL_TAG::start, VCOS_BLOCKPOOL_TAG::subpools, VCOS_BLOCKPOOL_SIZE, VCOS_BLOCKPOOL_SUBPOOL_FLAG_OWNS_MEM, vcos_free(), VCOS_FUNCTION, and vcos_mutex_delete().
 {
    vcos_log_trace("%s: pool %p", VCOS_FUNCTION, pool);
    if (pool)
    {
       VCOS_UNSIGNED i;
       ASSERT_POOL(pool);
       for (i = 0; i < pool->num_subpools; ++i)
       {
          VCOS_BLOCKPOOL_SUBPOOL_T *subpool = &pool->subpools[i];
          ASSERT_SUBPOOL(subpool);
          if (subpool->mem)
          {
             /* For debugging */
             memset(subpool->mem,
                   0xBE,
                   VCOS_BLOCKPOOL_SIZE(subpool->num_blocks,
                      pool->block_data_size, pool->align));
             if (subpool->flags & VCOS_BLOCKPOOL_SUBPOOL_FLAG_OWNS_MEM)
                vcos_free(subpool->mem);
             subpool->mem = NULL;
             subpool->start = NULL;
          }
       }
       vcos_mutex_delete(&pool->mutex);
       memset(pool, 0xBE, sizeof(VCOS_BLOCKPOOL_T)); /* For debugging */
    }
 }
vcos_generic_blockpool_elem_from_handle()
VCOSPRE_ void VCOSPOST_* vcos_generic_blockpool_elem_from_handle (VCOS_BLOCKPOOL_T * pool, uint32_t handle)
Definition at line 496 of file vcos_generic_blockpool.c.
References ASSERT_POOL, VCOS_BLOCKPOOL_TAG::block_size, index, VCOS_BLOCKPOOL_SUBPOOL_TAG::magic, VCOS_BLOCKPOOL_SUBPOOL_TAG::mem, VCOS_BLOCKPOOL_TAG::mutex, NULL, VCOS_BLOCKPOOL_HEADER_TAG::owner, VCOS_BLOCKPOOL_SUBPOOL_TAG::start, VCOS_BLOCKPOOL_HEADER_TAG::subpool, VCOS_BLOCKPOOL_TAG::subpools, VCOS_BLOCKPOOL_HANDLE_GET_INDEX, VCOS_BLOCKPOOL_HANDLE_GET_SUBPOOL, VCOS_BLOCKPOOL_SUBPOOL_MAGIC, VCOS_FUNCTION, vcos_mutex_lock(), and vcos_mutex_unlock().
 {
    VCOS_BLOCKPOOL_SUBPOOL_T *subpool;
    uint32_t subpool_id;
    uint32_t index;
    void *ret = NULL;
    ASSERT_POOL(pool);
    vcos_mutex_lock(&pool->mutex);
    subpool_id = VCOS_BLOCKPOOL_HANDLE_GET_SUBPOOL(handle);
    if (subpool_id < pool->num_subpools)
    {
       index = VCOS_BLOCKPOOL_HANDLE_GET_INDEX(handle);
       subpool = &pool->subpools[subpool_id];
       if (pool->subpools[subpool_id].magic == VCOS_BLOCKPOOL_SUBPOOL_MAGIC &&
             pool->subpools[subpool_id].mem && index < subpool->num_blocks)
       {
          VCOS_BLOCKPOOL_HEADER_T *hdr = (VCOS_BLOCKPOOL_HEADER_T*)
             ((size_t) subpool->start + (index * pool->block_size));
          if (hdr->owner.subpool == subpool) /* Check block is allocated */
             ret = hdr + 1;
       }
    }
    vcos_mutex_unlock(&pool->mutex);
    vcos_log_trace("%s: pool %p handle 0x%08x elem %p", VCOS_FUNCTION, pool,
          handle, ret);
    return ret;
 }
vcos_generic_blockpool_elem_to_handle()
VCOSPRE_ uint32_t VCOSPOST_ vcos_generic_blockpool_elem_to_handle (void * block)
Definition at line 458 of file vcos_generic_blockpool.c.
References ASSERT_POOL, ASSERT_SUBPOOL, VCOS_BLOCKPOOL_TAG::block_size, index, VCOS_BLOCKPOOL_TAG::mutex, NULL, VCOS_BLOCKPOOL_HEADER_TAG::owner, VCOS_BLOCKPOOL_SUBPOOL_TAG::owner, VCOS_BLOCKPOOL_SUBPOOL_TAG::start, VCOS_BLOCKPOOL_HEADER_TAG::subpool, VCOS_BLOCKPOOL_TAG::subpools, vcos_assert, VCOS_BLOCKPOOL_HANDLE_CREATE, VCOS_BLOCKPOOL_MAX_SUBPOOLS, VCOS_FUNCTION, vcos_mutex_lock(), and vcos_mutex_unlock().
 {
    uint32_t ret = -1;
    uint32_t index = -1;
    VCOS_BLOCKPOOL_HEADER_T *hdr = NULL;
    VCOS_BLOCKPOOL_T *pool = NULL;
    VCOS_BLOCKPOOL_SUBPOOL_T *subpool = NULL;
    uint32_t subpool_id;
    vcos_assert(block);
    hdr = (VCOS_BLOCKPOOL_HEADER_T*) block - 1;
    subpool = hdr->owner.subpool;
    ASSERT_SUBPOOL(subpool);
    pool = subpool->owner;
    ASSERT_POOL(pool);
    vcos_mutex_lock(&pool->mutex);
    /* The handle is the index into the array of blocks combined
     * with the subpool id.
     */
    index = ((size_t) hdr - (size_t) subpool->start) / pool->block_size;
    vcos_assert(index < subpool->num_blocks);
    subpool_id = ((char*) subpool - (char*) &pool->subpools[0]) /
       sizeof(VCOS_BLOCKPOOL_SUBPOOL_T);
    vcos_assert(subpool_id < VCOS_BLOCKPOOL_MAX_SUBPOOLS);
    vcos_assert(subpool_id < pool->num_subpools);
    ret = VCOS_BLOCKPOOL_HANDLE_CREATE(index, subpool_id);
    vcos_log_trace("%s: index %d subpool_id %d handle 0x%08x",
          VCOS_FUNCTION, index, subpool_id, ret);
    vcos_mutex_unlock(&pool->mutex);
    return ret;
 }
vcos_generic_blockpool_extend()
VCOSPRE_ VCOS_STATUS_T VCOSPOST_ vcos_generic_blockpool_extend (VCOS_BLOCKPOOL_T * pool, VCOS_UNSIGNED num_extensions, VCOS_UNSIGNED num_blocks)
Definition at line 230 of file vcos_generic_blockpool.c.
References ASSERT_POOL, VCOS_BLOCKPOOL_SUBPOOL_TAG::magic, VCOS_BLOCKPOOL_SUBPOOL_TAG::mem, NULL, VCOS_BLOCKPOOL_TAG::num_extension_blocks, VCOS_BLOCKPOOL_TAG::num_subpools, VCOS_BLOCKPOOL_SUBPOOL_TAG::start, VCOS_BLOCKPOOL_TAG::subpools, VCOS_BLOCKPOOL_MAX_SUBPOOLS, VCOS_BLOCKPOOL_SUBPOOL_MAGIC, VCOS_EACCESS, VCOS_EINVAL, VCOS_FUNCTION, and VCOS_SUCCESS.
 {
    VCOS_UNSIGNED i;
    ASSERT_POOL(pool);
    vcos_log_trace("%s: pool %p num_extensions %d num_blocks %d",
          VCOS_FUNCTION, pool, num_extensions, num_blocks);
    /* Extend may only be called once */
    if (pool->num_subpools > 1)
       return VCOS_EACCESS;
    if (num_extensions < 1 ||
          num_extensions > VCOS_BLOCKPOOL_MAX_SUBPOOLS - 1)
       return VCOS_EINVAL;
    if (num_blocks < 1)
       return VCOS_EINVAL;
    pool->num_subpools += num_extensions;
    pool->num_extension_blocks = num_blocks;
    /* Mark these subpools as valid but unallocated */
    for (i = 1; i < pool->num_subpools; ++i)
    {
       pool->subpools[i].magic = VCOS_BLOCKPOOL_SUBPOOL_MAGIC;
       pool->subpools[i].start = NULL;
       pool->subpools[i].mem = NULL;
    }
    return VCOS_SUCCESS;
 }
vcos_generic_blockpool_free()
VCOSPRE_ void VCOSPOST_ vcos_generic_blockpool_free (void * block)
Definition at line 347 of file vcos_generic_blockpool.c.
References ASSERT_POOL, ASSERT_SUBPOOL, VCOS_BLOCKPOOL_SUBPOOL_TAG::available_blocks, VCOS_BLOCKPOOL_TAG::block_data_size, VCOS_BLOCKPOOL_SUBPOOL_TAG::flags, VCOS_BLOCKPOOL_SUBPOOL_TAG::free_list, VCOS_BLOCKPOOL_SUBPOOL_TAG::mem, VCOS_BLOCKPOOL_TAG::mutex, VCOS_BLOCKPOOL_HEADER_TAG::next, NULL, VCOS_BLOCKPOOL_SUBPOOL_TAG::num_blocks, VCOS_BLOCKPOOL_HEADER_TAG::owner, VCOS_BLOCKPOOL_SUBPOOL_TAG::owner, VCOS_BLOCKPOOL_SUBPOOL_TAG::start, VCOS_BLOCKPOOL_HEADER_TAG::subpool, vcos_assert, VCOS_BLOCKPOOL_DEBUG_LOG, VCOS_BLOCKPOOL_OVERWRITE_ON_FREE, VCOS_BLOCKPOOL_SUBPOOL_FLAG_EXTENSION, vcos_free(), VCOS_FUNCTION, vcos_mutex_lock(), and vcos_mutex_unlock().
 {
    VCOS_BLOCKPOOL_DEBUG_LOG("block %p", block);
    if (block)
    {
       VCOS_BLOCKPOOL_HEADER_T* hdr = (VCOS_BLOCKPOOL_HEADER_T*) block - 1;
       VCOS_BLOCKPOOL_SUBPOOL_T *subpool = hdr->owner.subpool;
       VCOS_BLOCKPOOL_T *pool = NULL;
       ASSERT_SUBPOOL(subpool);
       pool = subpool->owner;
       ASSERT_POOL(pool);
       vcos_mutex_lock(&pool->mutex);
       vcos_assert((unsigned) subpool->available_blocks < subpool->num_blocks);
       /* Change ownership of block to be the free list */
       hdr->owner.next = subpool->free_list;
       subpool->free_list = hdr;
       ++(subpool->available_blocks);
       if (VCOS_BLOCKPOOL_OVERWRITE_ON_FREE)
          memset(block, 0xBD, pool->block_data_size); /* For debugging */
       if ( (subpool->flags & VCOS_BLOCKPOOL_SUBPOOL_FLAG_EXTENSION) &&
             subpool->available_blocks == subpool->num_blocks)
       {
          VCOS_BLOCKPOOL_DEBUG_LOG("%s: freeing subpool %p mem %p", VCOS_FUNCTION,
                subpool, subpool->mem);
          /* Free the sub-pool if it was dynamically allocated */
          vcos_free(subpool->mem);
          subpool->mem = NULL;
          subpool->start = NULL;
       }
       vcos_mutex_unlock(&pool->mutex);
    }
 }
vcos_generic_blockpool_init()
VCOSPRE_ VCOS_STATUS_T VCOSPOST_ vcos_generic_blockpool_init (VCOS_BLOCKPOOL_T * pool, VCOS_UNSIGNED num_blocks, VCOS_UNSIGNED block_size, void * start, VCOS_UNSIGNED pool_size, VCOS_UNSIGNED align, VCOS_UNSIGNED flags, const char * name)
Definition at line 140 of file vcos_generic_blockpool.c.
References VCOS_BLOCKPOOL_TAG::align, VCOS_BLOCKPOOL_TAG::block_data_size, VCOS_BLOCKPOOL_TAG::block_size, VCOS_BLOCKPOOL_TAG::magic, VCOS_BLOCKPOOL_TAG::mutex, VCOS_BLOCKPOOL_TAG::num_extension_blocks, VCOS_BLOCKPOOL_TAG::num_subpools, status, VCOS_BLOCKPOOL_TAG::subpools, vcos_assert, VCOS_BLOCKPOOL_ALIGN_DEFAULT, VCOS_BLOCKPOOL_MAGIC, VCOS_BLOCKPOOL_ROUND_UP, VCOS_BLOCKPOOL_SIZE, vcos_demand, VCOS_EINVAL, VCOS_ENOMEM, VCOS_FUNCTION, vcos_mutex_create(), VCOS_SUCCESS, and vcos_unused.
Referenced by vcos_generic_blockpool_create_on_heap().
 {
    VCOS_STATUS_T status = VCOS_SUCCESS;
    vcos_unused(name);
    vcos_unused(flags);
    vcos_log_trace(
          "%s: pool %p num_blocks %d block_size %d start %p pool_size %d name %p",
          VCOS_FUNCTION, pool, num_blocks, block_size, start, pool_size, name);
    vcos_demand(pool);
    vcos_demand(start);
    vcos_assert((block_size > 0));
    vcos_assert(num_blocks > 0);
    if (! align)
       align = VCOS_BLOCKPOOL_ALIGN_DEFAULT;
    if (align & 0x3)
    {
       vcos_log_error("%s: invalid alignment %d", VCOS_FUNCTION, align);
       return VCOS_EINVAL;
    }
    if (VCOS_BLOCKPOOL_SIZE(num_blocks, block_size, align) > pool_size)
    {
       vcos_log_error("%s: Pool is too small" \
             " num_blocks %d block_size %d align %d"
             " pool_size %d required size %d", VCOS_FUNCTION,
             num_blocks, block_size, align,
             pool_size, (int) VCOS_BLOCKPOOL_SIZE(num_blocks, block_size, align));
       return VCOS_ENOMEM;
    }
    status = vcos_mutex_create(&pool->mutex, "vcos blockpool mutex");
    if (status != VCOS_SUCCESS)
       return status;
    pool->block_data_size = block_size;
    /* TODO - create flag that if set forces the header to be in its own cache
     * line */
    pool->block_size = VCOS_BLOCKPOOL_ROUND_UP(pool->block_data_size +
          (align >= 4096 ? 32 : 0) +
          sizeof(VCOS_BLOCKPOOL_HEADER_T), align);
    pool->magic = VCOS_BLOCKPOOL_MAGIC;
    pool->num_subpools = 1;
    pool->num_extension_blocks = 0;
    pool->align = align;
    memset(pool->subpools, 0, sizeof(pool->subpools));
    vcos_generic_blockpool_subpool_init(pool, &pool->subpools[0], start,
          pool_size, num_blocks, align, VCOS_BLOCKPOOL_SUBPOOL_FLAG_NONE);
    return status;
 }
vcos_generic_blockpool_is_valid_elem()
VCOSPRE_ uint32_t VCOSPOST_ vcos_generic_blockpool_is_valid_elem (VCOS_BLOCKPOOL_T * pool, const void * block)
Definition at line 530 of file vcos_generic_blockpool.c.
References ASSERT_POOL, ASSERT_SUBPOOL, VCOS_BLOCKPOOL_TAG::block_size, VCOS_BLOCKPOOL_SUBPOOL_TAG::mem, VCOS_BLOCKPOOL_TAG::mutex, VCOS_BLOCKPOOL_SUBPOOL_TAG::num_blocks, VCOS_BLOCKPOOL_TAG::num_subpools, VCOS_BLOCKPOOL_HEADER_TAG::owner, VCOS_BLOCKPOOL_SUBPOOL_TAG::owner, VCOS_BLOCKPOOL_SUBPOOL_TAG::start, VCOS_BLOCKPOOL_HEADER_TAG::subpool, VCOS_BLOCKPOOL_TAG::subpools, vcos_mutex_lock(), and vcos_mutex_unlock().
 {
    uint32_t ret = 0;
    const char *pool_end;
    VCOS_UNSIGNED i = 0;
    ASSERT_POOL(pool);
    if (((size_t) block) & 0x3)
       return 0;
    vcos_mutex_lock(&pool->mutex);
    for (i = 0; i < pool->num_subpools; ++i)
    {
       VCOS_BLOCKPOOL_SUBPOOL_T *subpool = &pool->subpools[i];
       ASSERT_SUBPOOL(subpool);
       if (subpool->mem && subpool->start)
       {
          pool_end = (const char*)subpool->start +
             (subpool->num_blocks * pool->block_size);
          if ((const char*)block > (const char*)subpool->start &&
                (const char*)block < pool_end)
          {
             const VCOS_BLOCKPOOL_HEADER_T *hdr = (
                   const VCOS_BLOCKPOOL_HEADER_T*) block - 1;
             /* If the block has a header where the owner points to the pool then
              * it's a valid block. */
             ret = (hdr->owner.subpool == subpool && subpool->owner == pool);
             break;
          }
       }
    }
    vcos_mutex_unlock(&pool->mutex);
    return ret;
 }
vcos_generic_blockpool_used_count()
VCOSPRE_ VCOS_UNSIGNED VCOSPOST_ vcos_generic_blockpool_used_count (VCOS_BLOCKPOOL_T * pool)
Definition at line 407 of file vcos_generic_blockpool.c.
References ASSERT_POOL, ASSERT_SUBPOOL, VCOS_BLOCKPOOL_SUBPOOL_TAG::available_blocks, VCOS_BLOCKPOOL_TAG::mutex, VCOS_BLOCKPOOL_SUBPOOL_TAG::num_blocks, VCOS_BLOCKPOOL_TAG::num_subpools, VCOS_BLOCKPOOL_SUBPOOL_TAG::start, VCOS_BLOCKPOOL_TAG::subpools, vcos_mutex_lock(), and vcos_mutex_unlock().
 {
    VCOS_UNSIGNED ret = 0;
    VCOS_UNSIGNED i;
    ASSERT_POOL(pool);
    vcos_mutex_lock(&pool->mutex);
    for (i = 0; i < pool->num_subpools; ++i)
    {
       VCOS_BLOCKPOOL_SUBPOOL_T *subpool = &pool->subpools[i];
       ASSERT_SUBPOOL(subpool);
       if (subpool->start)
          ret += (subpool->num_blocks - subpool->available_blocks);
    }
    vcos_mutex_unlock(&pool->mutex);
    return ret;
 }