VideoCore Library: host_applications/linux/apps/hello_pi/hello_fft/gpu_fft.c File Reference
gpu_fft.c File Reference
#include <string.h>
#include "gpu_fft.h"
Macros
#define GPU_FFT_BUSY_WAIT_LIMIT (5<<12)
Typedefs
typedef struct GPU_FFT_COMPLEX COMPLEX
Functions
int gpu_fft_prepare (int mb, int log2_N, int direction, int jobs, struct GPU_FFT **fft)
unsigned gpu_fft_execute (struct GPU_FFT *info)
void gpu_fft_release (struct GPU_FFT *info)
Macro Definition Documentation
GPU_FFT_BUSY_WAIT_LIMIT
#define GPU_FFT_BUSY_WAIT_LIMIT (5<<12)
Definition at line 33 of file gpu_fft.c.
Referenced by gpu_fft_prepare().
Typedef Documentation
COMPLEX
typedef struct GPU_FFT_COMPLEX COMPLEX
Definition at line 35 of file gpu_fft.c.
Function Documentation
gpu_fft_execute()
unsigned gpu_fft_execute (struct GPU_FFT * info)
Definition at line 129 of file gpu_fft.c.
References GPU_FFT::base, gpu_fft_base_exec(), and GPU_FFT_QPUS.
Referenced by main().
{
     return gpu_fft_base_exec(&info->base, GPU_FFT_QPUS);
 }
gpu_fft_prepare()
int gpu_fft_prepare (int mb, int log2_N, int direction, int jobs, struct GPU_FFT ** fft)
Definition at line 37 of file gpu_fft.c.
References GPU_FFT_PTR::arm, GPU_FFT_PTR::cptr, GPU_FFT_PTR::fptr, gpu_fft_alloc(), GPU_FFT_BUSY_WAIT_LIMIT, gpu_fft_ptr_inc(), GPU_FFT_QPUS, gpu_fft_shader_code(), gpu_fft_shader_size(), gpu_fft_twiddle_data(), gpu_fft_twiddle_size(), GPU_FFT::in, log2_N, GPU_FFT::out, passes, shared, GPU_FFT::step, unique, GPU_FFT_PTR::uptr, GPU_FFT_PTR::vc, GPU_FFT_BASE::vc_code, GPU_FFT_BASE::vc_msg, GPU_FFT_BASE::vc_unifs, GPU_FFT_PTR::vptr, GPU_FFT::x, and GPU_FFT::y.
Referenced by main().
{
     unsigned info_bytes, twid_bytes, data_bytes, code_bytes, unif_bytes, mail_bytes;
     unsigned size, *uptr, vc_tw, vc_data;
     int i, q, shared, unique, passes, ret;
     struct GPU_FFT_BASE *base;
     struct GPU_FFT_PTR ptr;
     struct GPU_FFT *info;
     if (gpu_fft_twiddle_size(log2_N, &shared, &unique, &passes)) return -2;
     info_bytes = 4096;
     data_bytes = (1+((sizeof(COMPLEX)<<log2_N)|4095));
     code_bytes = gpu_fft_shader_size(log2_N);
     twid_bytes = sizeof(COMPLEX)*16*(shared+GPU_FFT_QPUS*unique);
     unif_bytes = sizeof(int)*GPU_FFT_QPUS*(5+jobs*2);
     mail_bytes = sizeof(int)*GPU_FFT_QPUS*2;
     size  = info_bytes +        // header
             data_bytes*jobs*2 + // ping-pong data, aligned
             code_bytes +        // shader, aligned
             twid_bytes +        // twiddles
             unif_bytes +        // uniforms
             mail_bytes;         // mailbox message
     ret = gpu_fft_alloc(mb, size, &ptr);
     if (ret) return ret;
     // Header
     info = (struct GPU_FFT *) ptr.arm.vptr;
     base = (struct GPU_FFT_BASE *) info;
     gpu_fft_ptr_inc(&ptr, info_bytes);
     // For transpose
     info->x = 1<<log2_N;
     info->y = jobs;
     // Ping-pong buffers leave results in or out of place
     info->in = info->out = ptr.arm.cptr;
     info->step = data_bytes / sizeof(COMPLEX);
     if (passes&1) info->out += info->step * jobs; // odd => out of place
     vc_data = gpu_fft_ptr_inc(&ptr, data_bytes*jobs*2);
     // Shader code
     memcpy(ptr.arm.vptr, gpu_fft_shader_code(log2_N), code_bytes);
     base->vc_code = gpu_fft_ptr_inc(&ptr, code_bytes);
     // Twiddles
     gpu_fft_twiddle_data(log2_N, direction, ptr.arm.fptr);
     vc_tw = gpu_fft_ptr_inc(&ptr, twid_bytes);
     uptr = ptr.arm.uptr;
     // Uniforms
     for (q=0; q<GPU_FFT_QPUS; q++) {
         *uptr++ = vc_tw;
         *uptr++ = vc_tw + sizeof(COMPLEX)*16*(shared + q*unique);
         *uptr++ = q;
         for (i=0; i<jobs; i++) {
             *uptr++ = vc_data + data_bytes*i;
             *uptr++ = vc_data + data_bytes*i + data_bytes*jobs;
         }
         *uptr++ = 0;
         *uptr++ = (q==0); // For mailbox: IRQ enable, master only
         base->vc_unifs[q] = gpu_fft_ptr_inc(&ptr, sizeof(int)*(5+jobs*2));
     }
     if ((jobs<<log2_N) <= GPU_FFT_BUSY_WAIT_LIMIT) {
         // Direct register poking with busy wait
         base->vc_msg = 0;
     }
     else {
         // Mailbox message
         for (q=0; q<GPU_FFT_QPUS; q++) {
             *uptr++ = base->vc_unifs[q];
             *uptr++ = base->vc_code;
         }
         base->vc_msg = ptr.vc;
     }
     *fft = info;
     return 0;
 }
gpu_fft_release()
void gpu_fft_release (struct GPU_FFT * info)
Definition at line 133 of file gpu_fft.c.
References GPU_FFT::base, and gpu_fft_base_release().
Referenced by main().
{
     gpu_fft_base_release(&info->base);
 }