VideoCore Library: interface/mmal/vc/mmal_vc_client_priv.h File Reference
mmal_vc_client_priv.h File Reference
Classes
struct MMAL_VC_CLIENT_BUFFER_CONTEXT_T
Typedefs
typedef struct MMAL_CLIENT_T MMAL_CLIENT_T
typedef struct MMAL_VC_CLIENT_BUFFER_CONTEXT_T MMAL_VC_CLIENT_BUFFER_CONTEXT_T
Functions
void mmal_vc_client_init (void)
MMAL_CLIENT_T * mmal_vc_get_client (void)
MMAL_STATUS_T mmal_vc_sendwait_message (MMAL_CLIENT_T *client, mmal_worker_msg_header *header, size_t size, uint32_t msgid, void *dest, size_t *destlen, MMAL_BOOL_T send_dummy_bulk)
MMAL_STATUS_T mmal_vc_send_message (MMAL_CLIENT_T *client, mmal_worker_msg_header *header, size_t size, uint8_t *data, size_t data_size, uint32_t msgid)
uint32_t mmal_vc_allocate_client_component (MMAL_COMPONENT_T *component)
void mmal_vc_release_client_component (MMAL_COMPONENT_T *component)
uint32_t mmal_vc_allocate_client_context (MMAL_VC_CLIENT_BUFFER_CONTEXT_T *context)
MMAL_VC_CLIENT_BUFFER_CONTEXT_T * mmal_vc_lookup_client_context (int index)
void mmal_vc_release_client_context (MMAL_VC_CLIENT_BUFFER_CONTEXT_T *context)
Detailed Description
Internal API for vchiq_arm MMAL client.
Definition in file mmal_vc_client_priv.h.
Typedef Documentation
MMAL_CLIENT_T
typedef struct MMAL_CLIENT_T MMAL_CLIENT_T
Definition at line 37 of file mmal_vc_client_priv.h.
MMAL_VC_CLIENT_BUFFER_CONTEXT_T
typedef struct MMAL_VC_CLIENT_BUFFER_CONTEXT_T MMAL_VC_CLIENT_BUFFER_CONTEXT_T
Hold the context required when sending a buffer to the copro.
Function Documentation
mmal_vc_allocate_client_component()
uint32_t mmal_vc_allocate_client_component (MMAL_COMPONENT_T * component)
Definition at line 108 of file mmal_vc_client.c.
References MMAL_CLIENT_COMPONENT_T::component, MMAL_CLIENT_COMPONENT_POOL_T::components, MMAL_CLIENT_COMPONENT_T::index, MMAL_CLIENT_COMPONENT_T::inuse, MMAL_CLIENT_COMPONENT_POOL_T::lock, MAX_COMPONENT_HANDLES, vcos_mutex_lock(), vcos_mutex_unlock(), and vcos_verify.
 {
    int i;
    vcos_mutex_lock(&client_component_pool.lock);
    for (i=0; i<MAX_COMPONENT_HANDLES; i++)
    {
       if (client_component_pool.components[i].inuse == 0)
          break;
    }
    if (vcos_verify(i != MAX_COMPONENT_HANDLES))
    {
       client_component_pool.components[i].index = i;
       client_component_pool.components[i].component = component;
       client_component_pool.components[i].inuse = 1;
    }
    vcos_mutex_unlock(&client_component_pool.lock);
    return i;
 }
mmal_vc_allocate_client_context()
uint32_t mmal_vc_allocate_client_context (MMAL_VC_CLIENT_BUFFER_CONTEXT_T * context)
Definition at line 177 of file mmal_vc_client.c.
 {
    int i;
    vcos_mutex_lock(&client_context_pool.lock);
    for (i=0; i<MAX_CLIENT_CONTEXTS; i++)
    {
       if (client_context_pool.contexts[i].inuse == 0)
          break;
    }
    if (vcos_verify(i != MAX_CLIENT_CONTEXTS))
    {
       client_context_pool.contexts[i].index = i;
       client_context_pool.contexts[i].ctx = context;
       client_context_pool.contexts[i].inuse = 1;
    }
    vcos_mutex_unlock(&client_context_pool.lock);
    return i | CLIENT_CONTEXT_MAGIC;
 }
mmal_vc_client_init()
void mmal_vc_client_init (void)
mmal_vc_get_client()
MMAL_CLIENT_T* mmal_vc_get_client (void)
Definition at line 1052 of file mmal_vc_client.c.
Referenced by mmal_vc_compact(), mmal_vc_consume_mem(), mmal_vc_drm_get_lhs32(), mmal_vc_drm_get_time(), mmal_vc_get_core_stats(), mmal_vc_get_stats(), mmal_vc_get_version(), mmal_vc_host_log(), mmal_vc_lmk(), mmal_vc_opaque_acquire(), mmal_vc_opaque_alloc_desc(), and mmal_vc_opaque_release().
 {
    return &client;
 }
mmal_vc_lookup_client_context()
MMAL_VC_CLIENT_BUFFER_CONTEXT_T* mmal_vc_lookup_client_context (int index)
Definition at line 199 of file mmal_vc_client.c.
References CLIENT_CONTEXT_MAGIC, CLIENT_CONTEXT_MAGIC_CHECK, CLIENT_CONTEXT_MAGIC_MASK, MMAL_CLIENT_CONTEXT_POOL_T::contexts, MMAL_CLIENT_CONTEXT_T::ctx, MMAL_WAITER_T::inuse, MAX_CLIENT_CONTEXTS, NULL, vcos_assert, and vcos_verify.
 {
    if (vcos_verify((CLIENT_CONTEXT_MAGIC_CHECK(index) == CLIENT_CONTEXT_MAGIC) &&
                    (CLIENT_CONTEXT_MAGIC_MASK(index) < MAX_CLIENT_CONTEXTS)))
    {
       vcos_assert(client_context_pool.contexts[CLIENT_CONTEXT_MAGIC_MASK(index)].inuse);
       return client_context_pool.contexts[CLIENT_CONTEXT_MAGIC_MASK(index)].ctx;
    }
    return NULL;
 }
mmal_vc_release_client_component()
void mmal_vc_release_client_component (MMAL_COMPONENT_T * component)
Definition at line 141 of file mmal_vc_client.c.
References MMAL_CLIENT_COMPONENT_T::component, MMAL_CLIENT_COMPONENT_POOL_T::components, MMAL_CLIENT_COMPONENT_T::inuse, MMAL_CLIENT_COMPONENT_POOL_T::lock, MAX_COMPONENT_HANDLES, NULL, vcos_mutex_lock(), and vcos_mutex_unlock().
 {
    int i;
    vcos_mutex_lock(&client_component_pool.lock);
    for (i=0; i<MAX_COMPONENT_HANDLES; i++)
    {
       if (client_component_pool.components[i].component == component)
       {
          client_component_pool.components[i].component = NULL;
          client_component_pool.components[i].inuse = 0;
       }
    }
    vcos_mutex_unlock(&client_component_pool.lock);
 }
mmal_vc_release_client_context()
void mmal_vc_release_client_context (MMAL_VC_CLIENT_BUFFER_CONTEXT_T * context)
Definition at line 211 of file mmal_vc_client.c.
 {
    int i;
    vcos_mutex_lock(&client_context_pool.lock);
    for (i=0; i<MAX_CLIENT_CONTEXTS; i++)
    {
       if (client_context_pool.contexts[i].ctx == context)
       {
          client_context_pool.contexts[i].ctx = NULL;
          client_context_pool.contexts[i].inuse = 0;
          break;
       }
    }
    if (i >= MAX_CLIENT_CONTEXTS)
       LOG_ERROR("Failed to release context %p - not found", context);
    vcos_mutex_unlock(&client_context_pool.lock);
 }
mmal_vc_send_message()
MMAL_STATUS_T mmal_vc_send_message (MMAL_CLIENT_T * client, mmal_worker_msg_header * msg_header, size_t size, uint8_t * data, size_t data_size, uint32_t msgid)
Send a message and do not wait for a reply.
Note
This function should only be called from within a mmal component, so vchiq_use/release_service calls aren't required (dealt with at higher level).
Parameters
client client to send message for
msg_header message header to send
size length of message, including header
msgid message id
Definition at line 848 of file mmal_vc_client.c.
References MMAL_CLIENT_T::bulk_lock, error(), MMAL_CLIENT_T::inited, LOG_ERROR, LOG_TRACE, mmal_worker_msg_header::magic, MMAL_EINVAL, MMAL_EIO, MMAL_MAGIC, MMAL_SUCCESS, mmal_worker_msg_header::msgid, MMAL_CLIENT_T::service, vchiq_queue_bulk_transmit(), vchiq_queue_message(), VCHIQ_SUCCESS, vcos_assert, vcos_mutex_lock(), vcos_mutex_unlock(), and vcos_verify.
 {
    VCHIQ_STATUS_T vst;
    VCHIQ_ELEMENT_T elems[] = {{msg_header, size}};
    MMAL_BOOL_T using_bulk_transfer = (data_size != 0);
    LOG_TRACE("len %zu", data_size);
    vcos_assert(size >= sizeof(mmal_worker_msg_header));
    if (!client->inited)
    {
       vcos_assert(0);
       return MMAL_EINVAL;
    }
    if (using_bulk_transfer)
       vcos_mutex_lock(&client->bulk_lock);
    msg_header->msgid  = msgid;
    msg_header->magic  = MMAL_MAGIC;
    vst = vchiq_queue_message(client->service, elems, 1);
    if (vst != VCHIQ_SUCCESS)
    {
       if (using_bulk_transfer)
          vcos_mutex_unlock(&client->bulk_lock);
       LOG_ERROR("failed");
       goto error;
    }
    if (using_bulk_transfer)
    {
       LOG_TRACE("bulk transmit: %p, %zu", data, data_size);
       data_size = (data_size + 3) & ~3;
       vst = vchiq_queue_bulk_transmit(client->service, data, data_size, msg_header);
       vcos_mutex_unlock(&client->bulk_lock);
       if (!vcos_verify(vst == VCHIQ_SUCCESS))
       {
          LOG_ERROR("failed bulk transmit");
          /* This really should not happen and if it does, things will go wrong as
           * we've already queued the vchiq message above. */
          vcos_assert(0);
          goto error;
       }
    }
    return MMAL_SUCCESS;
  error:
    return MMAL_EIO;
 }
mmal_vc_sendwait_message()
MMAL_STATUS_T mmal_vc_sendwait_message (struct MMAL_CLIENT_T * client, mmal_worker_msg_header * msg_header, size_t size, uint32_t msgid, void * dest, size_t * destlen, MMAL_BOOL_T send_dummy_bulk)
Send a message and wait for a reply.
Parameters
client client to send message for
msg_header message vchiq_header to send
size length of message, including header
msgid message id
dest destination for reply
destlen size of destination, updated with actual length
send_dummy_bulk whether to send a dummy bulk transfer
Definition at line 750 of file mmal_vc_client.c.
References MMAL_CLIENT_T::bulk_lock, MMAL_CLIENT_T::inited, MMAL_EINVAL, vcos_assert, and vcos_mutex_lock().
Referenced by mmal_vc_compact(), mmal_vc_consume_mem(), mmal_vc_drm_get_lhs32(), mmal_vc_drm_get_time(), mmal_vc_get_core_stats(), mmal_vc_get_stats(), mmal_vc_get_version(), mmal_vc_host_log(), mmal_vc_lmk(), mmal_vc_opaque_acquire(), mmal_vc_opaque_alloc_desc(), and mmal_vc_opaque_release().
 {
    MMAL_STATUS_T ret;
    MMAL_WAITER_T *waiter;
    VCHIQ_STATUS_T vst;
    VCHIQ_ELEMENT_T elems[] = {{msg_header, size}};
    vcos_assert(size >= sizeof(mmal_worker_msg_header));
    vcos_assert(dest);
    if (!client->inited)
    {
       vcos_assert(0);
       return MMAL_EINVAL;
    }
    if (send_dummy_bulk)
       vcos_mutex_lock(&client->bulk_lock);
    waiter = get_waiter(client);
    msg_header->msgid  = msgid;
    msg_header->u.waiter = waiter->index;
    msg_header->magic  = MMAL_MAGIC;
    waiter->dest    = dest;
    waiter->destlen = *destlen;
    LOG_TRACE("wait %p, reply to %p", waiter, dest);
    mmal_vc_use_internal(client);
    vst = vchiq_queue_message(client->service, elems, 1);
    if (vst != VCHIQ_SUCCESS)
    {
       ret = MMAL_EIO;
       if (send_dummy_bulk)
         vcos_mutex_unlock(&client->bulk_lock);
       goto fail_msg;
    }
    if (send_dummy_bulk)
    {
       uint32_t data_size = 8;
       /* The data is just some dummy bytes so it's fine for it to be static */
       static uint8_t data[8];
       vst = vchiq_queue_bulk_transmit(client->service, data, data_size, msg_header);
       vcos_mutex_unlock(&client->bulk_lock);
       if (!vcos_verify(vst == VCHIQ_SUCCESS))
       {
          LOG_ERROR("failed bulk transmit");
          /* This really should not happen and if it does, things will go wrong as
           * we've already queued the vchiq message above. */
          vcos_assert(0);
          ret = MMAL_EIO;
          goto fail_msg;
       }
    }
    /* now wait for the reply...
     *
     * FIXME: we could do with a timeout here. Need to be careful to cancel
     * the semaphore on a timeout.
     */
    /* coverity[lock] This semaphore isn't being used as a mutex */
    vcos_semaphore_wait(&waiter->sem);
    mmal_vc_release_internal(client);
    LOG_TRACE("got reply (len %i/%i)", (int)*destlen, (int)waiter->destlen);
    *destlen = waiter->destlen;
    release_waiter(client, waiter);
    return MMAL_SUCCESS;
 fail_msg:
    mmal_vc_release_internal(client);
    release_waiter(client, waiter);
    return ret;
 }