VideoCore Library: interface/vcos/vcos_timer.h File Reference
vcos_timer.h File Reference
#include "interface/vcos/vcos_types.h"
#include "vcos.h"
Functions
VCOSPRE_ VCOS_STATUS_T VCOSPOST_ vcos_timer_init (void)
VCOS_INLINE_DECL VCOS_STATUS_T vcos_timer_create (VCOS_TIMER_T *timer, const char *name, void(*expiration_routine)(void *context), void *context)
VCOS_INLINE_DECL void vcos_timer_set (VCOS_TIMER_T *timer, VCOS_UNSIGNED delay)
VCOS_INLINE_DECL void vcos_timer_cancel (VCOS_TIMER_T *timer)
VCOS_INLINE_DECL void vcos_timer_reset (VCOS_TIMER_T *timer, VCOS_UNSIGNED delay)
VCOS_INLINE_DECL void vcos_timer_delete (VCOS_TIMER_T *timer)
Detailed Description
Timers are single shot.
Timer times are in milliseconds.
Note
that timer callback functions are called from an arbitrary thread context. The expiration function should do its work as quickly as possible; blocking should be avoided.
On Windows, the separate function vcos_timer_init() must be called as timer initialization from DllMain is not possible.
Definition in file vcos_timer.h.
Function Documentation
vcos_timer_cancel()
VCOS_INLINE_DECL void vcos_timer_cancel (VCOS_TIMER_T * timer)
Stop an already running timer.
Parameters
timer timer handle
Referenced by _vcos_task_timer_cancel(), and svp_stop().
vcos_timer_create()
VCOS_INLINE_DECL VCOS_STATUS_T vcos_timer_create (VCOS_TIMER_T * timer, const char * name, void(*)(void *context) expiration_routine, void * context)
Create a timer in a disabled state.
The timer is initially disabled.
Parameters
timer timer handle
name name for timer
expiration_routine function to call when timer expires
context context passed to expiration routine
Referenced by _vcos_task_timer_set(), and svp_create().
vcos_timer_delete()
VCOS_INLINE_DECL void vcos_timer_delete (VCOS_TIMER_T * timer)
Referenced by svp_destroy().
vcos_timer_init()
VCOSPRE_ VCOS_STATUS_T VCOSPOST_ vcos_timer_init (void)
Perform timer subsystem initialization. This function is not needed on non-Windows platforms but is still present so that it can be called. On Windows it is needed because vcos_init() gets called from DLL initialization where it is not possible to create a time queue (deadlock occurs if you try).
Returns
VCOS_SUCCESS on success. VCOS_EEXIST if this has already been called once. VCOS_ENOMEM if resource allocation failed.
Definition at line 742 of file vcos_pthreads.c.
References VCOS_SUCCESS.
 {
    return VCOS_SUCCESS;
 }
vcos_timer_reset()
VCOS_INLINE_DECL void vcos_timer_reset (VCOS_TIMER_T * timer, VCOS_UNSIGNED delay)
Stop a timer and restart it.
Parameters
timer timer handle
delay delay in ms
vcos_timer_set()
VCOS_INLINE_DECL void vcos_timer_set (VCOS_TIMER_T * timer, VCOS_UNSIGNED delay)
Start a timer running.
Timer must be stopped.
Parameters
timer timer handle
delay Delay to wait for, in ms