VideoCore Library: interface/mmal/core/mmal_buffer.c File Reference
mmal_buffer.c File Reference
#include "mmal.h"
#include "mmal_buffer.h"
#include "core/mmal_buffer_private.h"
#include "mmal_logging.h"
Macros
#define ROUND_UP(s, align) ((((unsigned long)(s)) & ~((align)-1)) + (align))
#define DEFAULT_COMMAND_SIZE 256
#define ALIGN 8
Functions
void mmal_buffer_header_acquire (MMAL_BUFFER_HEADER_T *header)
void mmal_buffer_header_reset (MMAL_BUFFER_HEADER_T *header)
void mmal_buffer_header_release (MMAL_BUFFER_HEADER_T *header)
void mmal_buffer_header_release_continue (MMAL_BUFFER_HEADER_T *header)
MMAL_STATUS_T mmal_buffer_header_replicate (MMAL_BUFFER_HEADER_T *dest, MMAL_BUFFER_HEADER_T *src)
unsigned int mmal_buffer_header_size (MMAL_BUFFER_HEADER_T *header)
MMAL_BUFFER_HEADER_T * mmal_buffer_header_initialise (void *mem, unsigned int length)
MMAL_DRIVER_BUFFER_T * mmal_buffer_header_driver_data (MMAL_BUFFER_HEADER_T *header)
MMAL_BUFFER_HEADER_T * mmal_buffer_header_reference (MMAL_BUFFER_HEADER_T *header)
MMAL_STATUS_T mmal_buffer_header_mem_lock (MMAL_BUFFER_HEADER_T *header)
void mmal_buffer_header_mem_unlock (MMAL_BUFFER_HEADER_T *header)
void mmal_buffer_header_pre_release_cb_set (MMAL_BUFFER_HEADER_T *header, MMAL_BH_PRE_RELEASE_CB_T cb, void *userdata)
Macro Definition Documentation
ALIGN
#define ALIGN 8
Definition at line 35 of file mmal_buffer.c.
Referenced by mmal_buffer_header_size().
DEFAULT_COMMAND_SIZE
#define DEFAULT_COMMAND_SIZE 256
256 bytes of space for commands
Definition at line 34 of file mmal_buffer.c.
Referenced by mmal_buffer_header_size().
ROUND_UP
#define ROUND_UP (s, align) ((((unsigned long)(s)) & ~((align)-1)) + (align))
Definition at line 33 of file mmal_buffer.c.
Referenced by mmal_buffer_header_size().
Function Documentation
mmal_buffer_header_driver_data()
MMAL_DRIVER_BUFFER_T* mmal_buffer_header_driver_data (MMAL_BUFFER_HEADER_T * header)
Return a pointer to the area reserved for the driver
Definition at line 141 of file mmal_buffer.c.
References MMAL_BUFFER_HEADER_PRIVATE_T::driver_area, and MMAL_BUFFER_HEADER_T::priv.
 {
    return (MMAL_DRIVER_BUFFER_T *)header->priv->driver_area;
 }
mmal_buffer_header_initialise()
MMAL_BUFFER_HEADER_T* mmal_buffer_header_initialise (void * mem, unsigned int length)
Initialise a MMAL_BUFFER_HEADER_T
Definition at line 124 of file mmal_buffer.c.
References mmal_buffer_header_size(), MMAL_BUFFER_HEADER_T::priv, and MMAL_BUFFER_HEADER_T::type.
 {
    MMAL_BUFFER_HEADER_T *header;
    unsigned int header_size = mmal_buffer_header_size(0);
    if(length < header_size)
       return 0;
    memset(mem, 0, header_size);
    header = (MMAL_BUFFER_HEADER_T *)mem;
    header->type = (void *)&header[1];
    header->priv = (MMAL_BUFFER_HEADER_PRIVATE_T *)&header->type[1];
    return header;
 }
mmal_buffer_header_reference()
MMAL_BUFFER_HEADER_T* mmal_buffer_header_reference (MMAL_BUFFER_HEADER_T * header)
Return a pointer to a referenced buffer header
Definition at line 147 of file mmal_buffer.c.
References MMAL_BUFFER_HEADER_T::priv, and MMAL_BUFFER_HEADER_PRIVATE_T::reference.
 {
    return header->priv->reference;
 }
mmal_buffer_header_size()
unsigned int mmal_buffer_header_size (MMAL_BUFFER_HEADER_T * header)
Get the size in bytes of a fully initialised MMAL_BUFFER_HEADER_T
Definition at line 112 of file mmal_buffer.c.
References ALIGN, DEFAULT_COMMAND_SIZE, MMAL_BUFFER_HEADER_T::priv, ROUND_UP, and MMAL_BUFFER_HEADER_T::type.
Referenced by mmal_buffer_header_initialise(), and mmal_pool_create_with_allocator().
 {
    unsigned int header_size;
    header_size = ROUND_UP(sizeof(*header), ALIGN);
    header_size += ROUND_UP(sizeof(*header->type), ALIGN);
    header_size += ROUND_UP(DEFAULT_COMMAND_SIZE, ALIGN);
    header_size += ROUND_UP(sizeof(*header->priv), ALIGN);
    return header_size;
 }