VideoCore Library: interface/vmcs_host/vc_vchi_filesys.c File Reference
vc_vchi_filesys.c File Reference
#include <string.h>
#include <stdio.h>
#include <stdarg.h>
#include <ctype.h>
#include <assert.h>
#include "vchost.h"
#include "interface/vcos/vcos.h"
#include "interface/vchi/vchi.h"
#include "interface/vchi/common/endian.h"
#include "vc_vchi_filesys.h"
#include "interface/vmcs_host/vc_vchi_fileservice_defs.h"
Classes
struct FILESYS_SERVICE_T
Enumerations
enum VC_SECTOR_IO_T { VC_SECTOR_IO_NONE, VC_SECTOR_IO_READING, VC_SECTOR_IO_WRITING }
Functions
int vc_vchi_filesys_init (VCHI_INSTANCE_T initialise_instance, VCHI_CONNECTION_T **connections, uint32_t num_connections)
void vc_filesys_stop ()
int vc_filesys_close (int fildes)
long vc_filesys_lseek (int fildes, long offset, int whence)
int64_t vc_filesys_lseek64 (int fildes, int64_t offset, int whence)
int vc_filesys_mount (const char *device, const char *mountpoint, const char *options)
int vc_filesys_umount (const char *mountpoint)
int vc_filesys_open (const char *path, int vc_oflag)
int vc_filesys_read (int fildes, void *buf, unsigned int nbyte)
int vc_filesys_write (int fildes, const void *buf, unsigned int nbyte)
int vc_filesys_closedir (void *dhandle)
int vc_filesys_format (const char *path)
int vc_filesys_freespace (const char *path)
int64_t vc_filesys_freespace64 (const char *path)
int vc_filesys_get_attr (const char *path, fattributes_t *attr)
int vc_filesys_fstat (int fildes, FSTAT_T *buf)
int vc_filesys_mkdir (const char *path)
void * vc_filesys_opendir (const char *dirname)
int64_t vc_filesys_dirsize (const char *path, uint32_t *num_files, uint32_t *num_dirs)
struct dirent * vc_filesys_readdir_r (void *dhandle, struct dirent *result)
int vc_filesys_remove (const char *path)
int vc_filesys_rename (const char *oldfile, const char *newfile)
int vc_filesys_reset ()
int vc_filesys_set_attr (const char *path, fattributes_t attr)
int vc_filesys_setend (int fildes)
void vc_filesys_scandisk (const char *path)
int vc_filesys_chkdsk (const char *path, int fix_errors)
int vc_filesys_size (const char *path)
int vc_filesys_totalspace (const char *path)
int64_t vc_filesys_totalspace64 (const char *path)
int vc_filesys_diskwritable (const char *path)
int vc_filesys_fstype (const char *path)
int vc_filesys_open_disk_raw (const char *path)
int vc_filesys_close_disk_raw (const char *path)
int vc_filesys_open_disk (const char *path)
int vc_filesys_close_disk (const char *path)
int vc_filesys_numsectors (const char *path)
int vc_filesys_read_sectors (const char *path, uint32_t sector_num, char *sectors, uint32_t num_sectors, uint32_t *sectors_read)
int vc_filesys_write_sectors (const char *path, uint32_t sector_num, char *sectors, uint32_t num_sectors, uint32_t *sectors_written)
int vc_filesys_errno (void)
void vc_filesys_sendreset (void)
Enumeration Type Documentation
VC_SECTOR_IO_T
enum VC_SECTOR_IO_T
Enumerator
VC_SECTOR_IO_NONE
VC_SECTOR_IO_READING
VC_SECTOR_IO_WRITING
Definition at line 49 of file vc_vchi_filesys.c.
              {
    VC_SECTOR_IO_NONE,
    VC_SECTOR_IO_READING,
    VC_SECTOR_IO_WRITING
 } VC_SECTOR_IO_T;
Function Documentation
vc_filesys_chkdsk()
int vc_filesys_chkdsk (const char * path, int fix_errors)
Definition at line 1352 of file vc_vchi_filesys.c.
 {
    return vc_filesys_single_string(fix_errors, path, VC_FILESYS_CHKDSK, 1);
 }
vc_filesys_close()
int vc_filesys_close (int fildes)
Definition at line 408 of file vc_vchi_filesys.c.
Referenced by vc_filesys_size().
 {
    return vc_filesys_single_param((uint32_t) fildes, VC_FILESYS_CLOSE);
 }
vc_filesys_close_disk()
int vc_filesys_close_disk (const char * path)
Definition at line 1561 of file vc_vchi_filesys.c.
 {
    return vc_filesys_single_string(0, path, VC_FILESYS_CLOSE_DISK, 1);
 }
vc_filesys_close_disk_raw()
int vc_filesys_close_disk_raw (const char * path)
Definition at line 1520 of file vc_vchi_filesys.c.
 {
    return vc_filesys_single_string(0, path, VC_FILESYS_CLOSE_DISK_RAW, 1);
 }
vc_filesys_closedir()
int vc_filesys_closedir (void * dhandle)
Definition at line 910 of file vc_vchi_filesys.c.
 {
    return vc_filesys_single_param((uint32_t)dhandle, VC_FILESYS_CLOSEDIR);
 }
vc_filesys_dirsize()
int64_t vc_filesys_dirsize (const char * path, uint32_t * num_files, uint32_t * num_dirs)
Definition at line 1130 of file vc_vchi_filesys.c.
 {
    int64_t ret = -1;
    if(lock_obtain() == 0)
    {
       strncpy((char *)vc_filesys_client.fileserv_msg.data, path, FS_MAX_PATH);
       // FIXME: Should probably use a non-blocking call here since it may take a
       // long time to do the operation...
       if ( vchi_msg_stub(&vc_filesys_client.fileserv_msg,
                          VC_FILESYS_DIRSIZE,
                          (int)(16+strlen((char *)vc_filesys_client.fileserv_msg.data)+1)) == FILESERV_RESP_OK )
       {
          ret = vc_filesys_client.fileserv_msg.params[0];
          ret += (int64_t)vc_filesys_client.fileserv_msg.params[1] << 32;
          if (num_files)
             *num_files = vc_filesys_client.fileserv_msg.params[2];
          if (num_dirs)
             *num_dirs = vc_filesys_client.fileserv_msg.params[3];
       }
       lock_release();
    }
    return ret;
 }
vc_filesys_diskwritable()
int vc_filesys_diskwritable (const char * path)
Definition at line 1460 of file vc_vchi_filesys.c.
 {
    return vc_filesys_single_string(0, path, VC_FILESYS_DISKWRITABLE, 1);
 }
vc_filesys_errno()
int vc_filesys_errno (void)
Definition at line 1756 of file vc_vchi_filesys.c.
References FILESYS_SERVICE_T::err_no.
 {
    return (int) vc_filesys_client.err_no;
 }
vc_filesys_format()
int vc_filesys_format (const char * path)
Definition at line 931 of file vc_vchi_filesys.c.
 {
    return vc_filesys_single_string(0, path, VC_FILESYS_FORMAT, 0);
 }
vc_filesys_freespace()
int vc_filesys_freespace (const char * path)
Definition at line 953 of file vc_vchi_filesys.c.
 {
    return vc_filesys_single_string(0, path, VC_FILESYS_FREESPACE, 1);
 }
vc_filesys_freespace64()
int64_t vc_filesys_freespace64 (const char * path)
Definition at line 975 of file vc_vchi_filesys.c.
 {
    int64_t freespace = -1LL;
    if(lock_obtain() == 0)
    {
       strncpy((char *)vc_filesys_client.fileserv_msg.data, path, FS_MAX_PATH);
       if (vchi_msg_stub(&vc_filesys_client.fileserv_msg, VC_FILESYS_FREESPACE64,
                         (int)(16+strlen((char *)vc_filesys_client.fileserv_msg.data)+1)) == FILESERV_RESP_OK)
       {
          freespace = vc_filesys_client.fileserv_msg.params[0];
          freespace += (int64_t)vc_filesys_client.fileserv_msg.params[1] << 32;
       }
       lock_release();
    }
    return freespace;
 }
vc_filesys_fstat()
int vc_filesys_fstat (int fildes, FSTAT_T * buf)
Definition at line 1050 of file vc_vchi_filesys.c.
References NULL.
 {
    int success = -1;
    if (buf != NULL && lock_obtain() == 0)
    {
       vc_filesys_client.fileserv_msg.params[0] = (uint32_t) fildes;
       if ( vchi_msg_stub(&vc_filesys_client.fileserv_msg, VC_FILESYS_FSTAT, 4) == FILESERV_RESP_OK )
       {
          buf->st_size = (int64_t)vc_filesys_client.fileserv_msg.params[0];          // LSB
          buf->st_size |= (int64_t)vc_filesys_client.fileserv_msg.params[1] << 32;    // MSB
          buf->st_modtime = (uint32_t)vc_filesys_client.fileserv_msg.params[2];
          // there's room for expansion here to pass across more elements of the structure if required...
          success = 0;
       }
       lock_release();
    }
    return success;
 }
vc_filesys_fstype()
int vc_filesys_fstype (const char * path)
Definition at line 1480 of file vc_vchi_filesys.c.
 {
    return vc_filesys_single_string(0, path, VC_FILESYS_FSTYPE, 1);
 }
vc_filesys_get_attr()
int vc_filesys_get_attr (const char * path, fattributes_t * attr)
Definition at line 1012 of file vc_vchi_filesys.c.
 {
    int success = -1;
    if(lock_obtain() == 0)
    {
       strncpy((char *)vc_filesys_client.fileserv_msg.data, path, FS_MAX_PATH);
       if (vchi_msg_stub(&vc_filesys_client.fileserv_msg, VC_FILESYS_GET_ATTR,
                         (int)(16+strlen((char *)vc_filesys_client.fileserv_msg.data)+1)) == FILESERV_RESP_OK)
       {
          success = 0;
          *attr = (fattributes_t) vc_filesys_client.fileserv_msg.params[0];
       }
       lock_release();
    }
    return success;
 }
vc_filesys_lseek()
long vc_filesys_lseek (int fildes, long offset, int whence)
Definition at line 429 of file vc_vchi_filesys.c.
Referenced by vc_filesys_size().
 {
    long set = -1;
    if(lock_obtain() == 0)
    {
       vc_filesys_client.fileserv_msg.params[0] = (uint32_t) fildes;
       vc_filesys_client.fileserv_msg.params[1] = (uint32_t) offset;
       vc_filesys_client.fileserv_msg.params[2] = (uint32_t) whence;
       if (vchi_msg_stub(&vc_filesys_client.fileserv_msg, VC_FILESYS_LSEEK, 12) == FILESERV_RESP_OK)
          set = (long) vc_filesys_client.fileserv_msg.params[0];
       lock_release();
    }
    return set;
 }
vc_filesys_lseek64()
int64_t vc_filesys_lseek64 (int fildes, int64_t offset, int whence)
Definition at line 463 of file vc_vchi_filesys.c.
 {
    int64_t set = -1;
    if(lock_obtain() == 0)
    {
       vc_filesys_client.fileserv_msg.params[0] = (uint32_t) fildes;
       vc_filesys_client.fileserv_msg.params[1] = (uint32_t) offset;        // LSB
       vc_filesys_client.fileserv_msg.params[2] = (uint32_t)(offset >> 32); // MSB
       vc_filesys_client.fileserv_msg.params[3] = (uint32_t) whence;
       if (vchi_msg_stub(&vc_filesys_client.fileserv_msg, VC_FILESYS_LSEEK64, 16) == FILESERV_RESP_OK)
       {
          set = vc_filesys_client.fileserv_msg.params[0];
          set += (int64_t)vc_filesys_client.fileserv_msg.params[1] << 32;
       }
       lock_release();
    }
    return set;
 }
vc_filesys_mkdir()
int vc_filesys_mkdir (const char * path)
Definition at line 1088 of file vc_vchi_filesys.c.
 {
    return vc_filesys_single_string(0, path, VC_FILESYS_MKDIR, 0);
 }
vc_filesys_mount()
int vc_filesys_mount (const char * device, const char * mountpoint, const char * options)
Definition at line 500 of file vc_vchi_filesys.c.
 {
    int set = -1, len;
    int a = strlen(device);
    int b = strlen(mountpoint);
    int c = strlen(options);
    if(a + b + c + 3 < FILESERV_MAX_DATA && lock_obtain() == 0)
    {
       char *str = (char *) vc_filesys_client.fileserv_msg.data;
       memcpy(str, device, a);
       str[a] = 0;
       memcpy(str+a+1, mountpoint, b);
       str[a+1+b] = 0;
       memcpy(str+a+b+2, options, c);
       str[a+b+c+2] = 0;
       len = a + b + c + 3 + (int)(((FILESERV_MSG_T *)0)->data);
       len = ((len + (VCHI_BULK_GRANULARITY-1)) & ~(VCHI_BULK_GRANULARITY-1)) + VCHI_BULK_GRANULARITY;
       if (vchi_msg_stub(&vc_filesys_client.fileserv_msg, VC_FILESYS_MOUNT, len) == FILESERV_RESP_OK)
          set = (int) vc_filesys_client.fileserv_msg.params[0];
       lock_release();
    }
    return set;
 }
vc_filesys_numsectors()
int vc_filesys_numsectors (const char * path)
Definition at line 1581 of file vc_vchi_filesys.c.
 {
    return vc_filesys_single_string(0, path, VC_FILESYS_NUMSECTORS, 1);
 }
vc_filesys_open()
int vc_filesys_open (const char * path, int vc_oflag)
Definition at line 564 of file vc_vchi_filesys.c.
Referenced by vc_filesys_size().
 {
    return vc_filesys_single_string((uint32_t) vc_oflag, path, VC_FILESYS_OPEN, 1);
 }
vc_filesys_open_disk()
int vc_filesys_open_disk (const char * path)
Definition at line 1541 of file vc_vchi_filesys.c.
 {
    return vc_filesys_single_string(0, path, VC_FILESYS_OPEN_DISK, 1);
 }
vc_filesys_open_disk_raw()
int vc_filesys_open_disk_raw (const char * path)
Definition at line 1500 of file vc_vchi_filesys.c.
 {
    return vc_filesys_single_string(0, path, VC_FILESYS_OPEN_DISK_RAW, 1);
 }
vc_filesys_opendir()
void* vc_filesys_opendir (const char * dirname)
Definition at line 1109 of file vc_vchi_filesys.c.
 {
    return (void *) vc_filesys_single_string(0, dirname, VC_FILESYS_OPENDIR, 1);
 }
vc_filesys_read()
int vc_filesys_read (int fildes, void * buf, unsigned int nbyte)
Definition at line 688 of file vc_vchi_filesys.c.
 {
    int bulk_bytes = 0;
    int actual_read = 0;
    int total_byte = 0;
    uint8_t* ptr = (uint8_t*)buf;
    if (nbyte == 0) {
       return 0;
    }
    if(lock_obtain() == 0)
    {
       do {
          bulk_bytes = nbyte > FILESERV_MAX_BULK ? FILESERV_MAX_BULK : nbyte;
          //we overwrite the response here so fill in data again
          vc_filesys_client.fileserv_msg.params[0] = (uint32_t)fildes;
          vc_filesys_client.fileserv_msg.params[1] = 0xffffffffU;        // offset: use -1 to indicate no offset
          actual_read = vc_vchi_msg_bulk_read(&vc_filesys_client.fileserv_msg , VC_FILESYS_READ, (uint32_t)bulk_bytes, (uint8_t*)ptr);
          if(bulk_bytes != actual_read) {
             if(actual_read < 0)
                total_byte = -1;
             else
                total_byte += actual_read;
             //exit loop
             break;
          }
          ptr+=bulk_bytes;
          nbyte -= actual_read;
          total_byte += actual_read;
       }while(nbyte > 0);
       lock_release();
    }
    return total_byte;
 }
vc_filesys_read_sectors()
int vc_filesys_read_sectors (const char * path, uint32_t sector_num, char * sectors, uint32_t num_sectors, uint32_t * sectors_read)
Definition at line 1600 of file vc_vchi_filesys.c.
References FS_MAX_PATH, and len.
 {
 #if VCHI_BULK_ALIGN > 1
    uint32_t align_bytes = 0;
 #endif
    char* bulk_addr = sectors;
    int len;
    int ret = -1;
    if((len = (int)strlen(path)) < FS_MAX_PATH && lock_obtain() == 0)
    {
       strncpy((char *)vc_filesys_client.fileserv_msg.data, path, FS_MAX_PATH);
       vc_filesys_client.fileserv_msg.params[0] = sector_num;
       vc_filesys_client.fileserv_msg.params[1] = num_sectors;
 #if VCHI_BULK_ALIGN > 1
       //required to make buffer aligned for bulk
       align_bytes = VCHI_BULK_ALIGN_NBYTES(sectors);
 #endif
       //note for read we are currently doing memcpy on host to tell 2727 align is 0
       vc_filesys_client.fileserv_msg.params[2] = 0;
       //we send read request
       if (vchi_msg_stub_noblock(&vc_filesys_client.fileserv_msg, VC_FILESYS_READ_SECTORS, 16+len+1) == 0)
       {
          while(num_sectors)
          {
             uint32_t bulk_sectors = (num_sectors > FILESERV_MAX_BULK_SECTOR) ? (uint32_t)FILESERV_MAX_BULK_SECTOR : num_sectors;
             if(vchi_bulk_queue_receive( vc_filesys_client.open_handle,
 #if VCHI_BULK_ALIGN > 1
                                         align_bytes ? vc_filesys_client.bulk_buffer : bulk_addr,
 #else
                                         bulk_addr,
 #endif
                                         (bulk_sectors*FILESERV_SECTOR_LENGTH), VCHI_FLAGS_BLOCK_UNTIL_OP_COMPLETE, NULL) != 0)
                break;
 #if VCHI_BULK_ALIGN > 1
             if(align_bytes) {
                //this is bad but will do for now..
                memcpy( bulk_addr, vc_filesys_client.bulk_buffer, (bulk_sectors*FILESERV_SECTOR_LENGTH));
             }
 #endif
             bulk_addr += (bulk_sectors*FILESERV_SECTOR_LENGTH);
             num_sectors -= bulk_sectors;
          }
          // now wait to receive resp from original msg...
          if(vcos_event_wait(&vc_filesys_client.response_event) == VCOS_SUCCESS && vc_filesys_client.fileserv_msg.cmd_code == FILESERV_RESP_OK)
          {
             *sectors_read = vc_filesys_client.fileserv_msg.params[0];
             ret = 0;
          }
          else
          {
             //error code in [0]
             *sectors_read = vc_filesys_client.fileserv_msg.params[1];
             ret = vc_filesys_client.fileserv_msg.params[0];
          }
       }
       lock_release();
    }
    return ret;
 }
vc_filesys_readdir_r()
struct dirent* vc_filesys_readdir_r (void * dhandle, struct dirent * result)
Definition at line 1176 of file vc_vchi_filesys.c.
References NULL.
 {
    struct dirent *ret = NULL;
    if(lock_obtain() == 0)
    {
       vc_filesys_client.fileserv_msg.params[0] = (uint32_t)dhandle;
       if (vchi_msg_stub(&vc_filesys_client.fileserv_msg, VC_FILESYS_READDIR, 4) == FILESERV_RESP_OK)
       {
          fs_host_direntbytestream_interp(result, (void *)vc_filesys_client.fileserv_msg.data);
          ret = result;
       }
       lock_release();
    }
    return ret;
 }
vc_filesys_remove()
int vc_filesys_remove (const char * path)
Definition at line 1212 of file vc_vchi_filesys.c.
 {
    return vc_filesys_single_string(0, path, VC_FILESYS_REMOVE, 0);
 }
vc_filesys_rename()
int vc_filesys_rename (const char * oldfile, const char * newfile)
Definition at line 1234 of file vc_vchi_filesys.c.
References FS_MAX_PATH.
 {
    int a, b, success = -1;
    // Ensure the pathnames aren't too long
    if ((a = strlen(oldfile)) < FS_MAX_PATH && (b = strlen(newfile)) < FS_MAX_PATH && lock_obtain() == 0)
    {
       strncpy((char *)vc_filesys_client.fileserv_msg.data, oldfile, FS_MAX_PATH);
       strncpy((char *)&vc_filesys_client.fileserv_msg.data[a+1], newfile, FS_MAX_PATH);
       if (vchi_msg_stub(&vc_filesys_client.fileserv_msg, VC_FILESYS_RENAME, 16+a+1+b+1) == FILESERV_RESP_OK)
          success = 0;
       lock_release();
    }
    return success;
 }
vc_filesys_reset()
int vc_filesys_reset (void)
Definition at line 1269 of file vc_vchi_filesys.c.
 {
    return vc_filesys_single_param(0, VC_FILESYS_RESET);
 }
vc_filesys_scandisk()
void vc_filesys_scandisk (const char * path)
Definition at line 1332 of file vc_vchi_filesys.c.
 {
    vc_filesys_single_string(0, path, VC_FILESYS_SCANDISK, 0);
    return;
 }
vc_filesys_sendreset()
void vc_filesys_sendreset (void)
Definition at line 2506 of file vc_vchi_filesys.c.
 {
    //TODO
 }
vc_filesys_set_attr()
int vc_filesys_set_attr (const char * path, fattributes_t attr)
Definition at line 1290 of file vc_vchi_filesys.c.
 {
    return vc_filesys_single_string((uint32_t) attr, path, VC_FILESYS_SET_ATTR, 0);
 }
vc_filesys_setend()
int vc_filesys_setend (int fildes)
Definition at line 1311 of file vc_vchi_filesys.c.
 {
    return vc_filesys_single_param((uint32_t) fildes, VC_FILESYS_SETEND);
 }
vc_filesys_size()
int vc_filesys_size (const char * path)
Definition at line 1371 of file vc_vchi_filesys.c.
References vc_filesys_close(), vc_filesys_lseek(), vc_filesys_open(), VC_O_RDONLY, and void().
 {
    int fd;
    int end_pos = 0;
    int success = -1;
    if((fd = vc_filesys_open(path, VC_O_RDONLY)) == 0)
    {
       end_pos = vc_filesys_lseek(fd, 0, SEEK_END);
       success = vc_filesys_close(fd);
       (void)success;
    }
    return end_pos;
 }
vc_filesys_stop()
void vc_filesys_stop (void)
Definition at line 301 of file vc_vchi_filesys.c.
 {
    int32_t result;
    void *dummy;
    if(lock_obtain() != 0)
       return;
    result = vchi_service_close(vc_filesys_client.open_handle);
    vcos_assert(result == 0);
    vc_filesys_client.initialised = 0;
    vcos_event_signal(&vc_filesys_client.filesys_msg_avail);
    vcos_thread_join(&vc_filesys_client.filesys_thread, &dummy);
    vcos_event_delete(&vc_filesys_client.filesys_msg_avail);
    vcos_event_delete(&vc_filesys_client.response_event);
    vcos_mutex_delete(&vc_filesys_client.filesys_lock);
    if(vc_filesys_client.bulk_buffer)
       vcos_free(vc_filesys_client.bulk_buffer);
 }
vc_filesys_totalspace()
int vc_filesys_totalspace (const char * path)
Definition at line 1401 of file vc_vchi_filesys.c.
 {
    return vc_filesys_single_string(0, path, VC_FILESYS_TOTALSPACE, 1);
 }
vc_filesys_totalspace64()
int64_t vc_filesys_totalspace64 (const char * path)
Definition at line 1423 of file vc_vchi_filesys.c.
 {
    int64_t totalspace = -1LL;
    if(lock_obtain() == 0)
    {
       strncpy((char *)vc_filesys_client.fileserv_msg.data, path, FS_MAX_PATH);
       if (vchi_msg_stub(&vc_filesys_client.fileserv_msg, VC_FILESYS_TOTALSPACE64,
                         (int)(16+strlen((char *)vc_filesys_client.fileserv_msg.data)+1)) == FILESERV_RESP_OK)
       {
          totalspace = vc_filesys_client.fileserv_msg.params[0];
          totalspace += (int64_t)vc_filesys_client.fileserv_msg.params[1] << 32;
       }
       lock_release();
    }
    return totalspace;
 }
vc_filesys_umount()
int vc_filesys_umount (const char * mountpoint)
Definition at line 544 of file vc_vchi_filesys.c.
 {
    return vc_filesys_single_string(0, mountpoint, VC_FILESYS_UMOUNT, 1);
 }
vc_filesys_write()
int vc_filesys_write (int fildes, const void * buf, unsigned int nbyte)
Definition at line 849 of file vc_vchi_filesys.c.
 {
    int num_wrt = 0;
    int bulk_bytes = 0;
    int actual_written = 0;
    uint8_t *ptr = (uint8_t*) buf;
    if (nbyte == 0) {
       return 0;
    }
    if(lock_obtain() == 0)
    {
       //will split the read into 4K chunks based on vc fwrite buffer size array size
       //we will make this more dynamic later
       do {
          bulk_bytes = nbyte > FILESERV_MAX_BULK ? FILESERV_MAX_BULK : nbyte;
          //we overwrite the response here so fill in data again
          vc_filesys_client.fileserv_msg.params[0] = (uint32_t)fildes;
          vc_filesys_client.fileserv_msg.params[1] = 0xffffffffU;        // offset: use -1 to indicate no offset
          actual_written = vc_vchi_msg_bulk_write(&vc_filesys_client.fileserv_msg , VC_FILESYS_WRITE, (uint32_t)bulk_bytes, (uint8_t*)ptr);
          if(bulk_bytes != actual_written) {
             if(actual_written < 0)
                num_wrt = -1;
             else
                num_wrt += actual_written;
             break;
          }
          ptr+=bulk_bytes;
          nbyte -= actual_written;
          num_wrt += actual_written;
       }while(nbyte > 0);
       lock_release();
    }
    return num_wrt;
 }
vc_filesys_write_sectors()
int vc_filesys_write_sectors (const char * path, uint32_t sector_num, char * sectors, uint32_t num_sectors, uint32_t * sectors_written)
Definition at line 1681 of file vc_vchi_filesys.c.
References FS_MAX_PATH, and len.
 {
    uint32_t align_bytes = 0;
    char* bulk_addr = sectors;
    int len;
    int ret = -1;
    len = (int) strlen(path);
    if((len = (int) strlen(path)) < FS_MAX_PATH && lock_obtain() == 0)
    {
       vc_filesys_client.fileserv_msg.params[0] = sector_num;
       vc_filesys_client.fileserv_msg.params[1] = num_sectors;
       //required to make buffer aligned for bulk
       align_bytes = ((unsigned long)sectors & (VCHI_BULK_ALIGN-1));
       vc_filesys_client.fileserv_msg.params[2] = align_bytes;
       //copy path at end of any alignbytes
       strncpy(((char *)vc_filesys_client.fileserv_msg.data), path, FS_MAX_PATH);
       //we send write request
       if (vchi_msg_stub_noblock(&vc_filesys_client.fileserv_msg, VC_FILESYS_WRITE_SECTORS, 16+len+1) == 0)
       {
          if(align_bytes) {
             //note we are cheating and going backward to make addr aligned and sending more data...
             bulk_addr -= align_bytes;
          }
          while(num_sectors) {
             uint32_t bulk_sectors = (num_sectors > FILESERV_MAX_BULK_SECTOR) ? (uint32_t)FILESERV_MAX_BULK_SECTOR : num_sectors;
             //we send some extra data at the start
             if(vchi_bulk_queue_transmit( vc_filesys_client.open_handle, bulk_addr,
                                          VCHI_BULK_ROUND_UP((bulk_sectors*FILESERV_SECTOR_LENGTH)+align_bytes),
                                          VCHI_FLAGS_BLOCK_UNTIL_DATA_READ, NULL) != 0)
                break;
             //go to next ALIGNED address
             bulk_addr += FILESERV_MAX_BULK;
             num_sectors -= bulk_sectors;
          }
          // now wait to receive resp from original msg...
          if(vcos_event_wait(&vc_filesys_client.response_event) == VCOS_SUCCESS && vc_filesys_client.fileserv_msg.cmd_code == FILESERV_RESP_OK)
          {
             *sectors_written = vc_filesys_client.fileserv_msg.params[0];
             ret = 0;
          }
          else
          {
             //error code in [0]
             *sectors_written = vc_filesys_client.fileserv_msg.params[1];
             ret = vc_filesys_client.fileserv_msg.params[0];
          }
       }
       lock_release();
    }
    return ret;
 }
vc_vchi_filesys_init()
int vc_vchi_filesys_init (VCHI_INSTANCE_T initialise_instance, VCHI_CONNECTION_T ** connections, uint32_t num_connections)
Definition at line 154 of file vc_vchi_filesys.c.
References FILESYS_SERVICE_T::bulk_buffer, SERVICE_CREATION_T::callback, SERVICE_CREATION_T::connection, FILESYS_SERVICE_T::cur_xid, FILESERV_4CC, FILESERV_MAX_BULK, FILESYS_SERVICE_T::filesys_lock, FILESYS_SERVICE_T::filesys_msg_avail, FILESYS_SERVICE_T::num_connections, FILESYS_SERVICE_T::response_event, SERVICE_CREATION_T::rx_fifo_size, SERVICE_CREATION_T::service_id, status, SERVICE_CREATION_T::tx_fifo_size, vcos_assert, vcos_event_create(), vcos_malloc_aligned(), vcos_mutex_create(), VCOS_SUCCESS, and vcos_verify.
 {
    int32_t success = 0;
    SERVICE_CREATION_T filesys_parameters;
    VCOS_THREAD_ATTR_T attrs;
    VCOS_STATUS_T status;
    // record the number of connections
    memset( &vc_filesys_client, 0, sizeof(FILESYS_SERVICE_T) );
    vc_filesys_client.num_connections = num_connections;
    if(!vcos_verify(vc_filesys_client.num_connections < 2))
       return -1;
    status = vcos_mutex_create(&vc_filesys_client.filesys_lock, "HFilesys");
    vcos_assert(status == VCOS_SUCCESS);
    status = vcos_event_create(&vc_filesys_client.filesys_msg_avail, "HFilesys");
    vcos_assert(status == VCOS_SUCCESS);
    //create sema used to signal cmd response has arrived
    status = vcos_event_create(&vc_filesys_client.response_event, "HFilesys");
    vcos_assert(status == VCOS_SUCCESS);
    vc_filesys_client.bulk_buffer = vcos_malloc_aligned(FILESERV_MAX_BULK, 16, "HFilesys bulk_recv");
    vc_filesys_client.cur_xid = 0;
    memset(&filesys_parameters, 0, sizeof(filesys_parameters));
    filesys_parameters.service_id = FILESERV_4CC;   // 4cc service code
    filesys_parameters.connection = connections[0]; // passed in fn ptrs
    filesys_parameters.rx_fifo_size = 0;            // rx fifo size (unused)
    filesys_parameters.tx_fifo_size = 0;            // tx fifo size (unused)
    filesys_parameters.callback = &filesys_callback;
    filesys_parameters.callback_param = &vc_filesys_client.filesys_msg_avail;
    filesys_parameters.want_unaligned_bulk_rx = 0;
    filesys_parameters.want_unaligned_bulk_tx = 0;
    filesys_parameters.want_crc = 0;
    filesys_parameters.version.version = VC_FILESERV_VER;
    filesys_parameters.version.version_min = VC_FILESERV_VER;
    success = vchi_service_open( initialise_instance, &filesys_parameters, &vc_filesys_client.open_handle );
    vcos_assert( success == 0 );
    vcos_thread_attr_init(&attrs);
    vcos_thread_attr_setstacksize(&attrs, 4000);
    vcos_thread_attr_settimeslice(&attrs, 1);
    vc_filesys_client.initialised = 1;
    status = vcos_thread_create(&vc_filesys_client.filesys_thread, "HFilesys", &attrs, filesys_task_func, NULL);
    vcos_assert(status == VCOS_SUCCESS);
    /* Not using service immediately - release videocore */
    vchi_service_release(vc_filesys_client.open_handle);
    return (int)success;
 }