/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/models2.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "proto/models2.pb-c.h"
void   fcws__para__init
                     (FCWS__Para         *message)
{
  static const FCWS__Para init_value = FCWS__PARA__INIT;
  *message = init_value;
}
size_t fcws__para__get_packed_size
                     (const FCWS__Para *message)
{
  assert(message->base.descriptor == &fcws__para__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fcws__para__pack
                     (const FCWS__Para *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &fcws__para__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fcws__para__pack_to_buffer
                     (const FCWS__Para *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &fcws__para__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FCWS__Para *
       fcws__para__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FCWS__Para *)
     protobuf_c_message_unpack (&fcws__para__descriptor,
                                allocator, len, data);
}
void   fcws__para__free_unpacked
                     (FCWS__Para *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &fcws__para__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   fcws__local__init
                     (FCWS__Local         *message)
{
  static const FCWS__Local init_value = FCWS__LOCAL__INIT;
  *message = init_value;
}
size_t fcws__local__get_packed_size
                     (const FCWS__Local *message)
{
  assert(message->base.descriptor == &fcws__local__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fcws__local__pack
                     (const FCWS__Local *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &fcws__local__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fcws__local__pack_to_buffer
                     (const FCWS__Local *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &fcws__local__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FCWS__Local *
       fcws__local__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FCWS__Local *)
     protobuf_c_message_unpack (&fcws__local__descriptor,
                                allocator, len, data);
}
void   fcws__local__free_unpacked
                     (FCWS__Local *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &fcws__local__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   fcws__vehicle__model__init
                     (FCWS__VehicleModel         *message)
{
  static const FCWS__VehicleModel init_value = FCWS__VEHICLE__MODEL__INIT;
  *message = init_value;
}
size_t fcws__vehicle__model__get_packed_size
                     (const FCWS__VehicleModel *message)
{
  assert(message->base.descriptor == &fcws__vehicle__model__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fcws__vehicle__model__pack
                     (const FCWS__VehicleModel *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &fcws__vehicle__model__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fcws__vehicle__model__pack_to_buffer
                     (const FCWS__VehicleModel *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &fcws__vehicle__model__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FCWS__VehicleModel *
       fcws__vehicle__model__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FCWS__VehicleModel *)
     protobuf_c_message_unpack (&fcws__vehicle__model__descriptor,
                                allocator, len, data);
}
void   fcws__vehicle__model__free_unpacked
                     (FCWS__VehicleModel *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &fcws__vehicle__model__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   fcws__models__init
                     (FCWS__Models         *message)
{
  static const FCWS__Models init_value = FCWS__MODELS__INIT;
  *message = init_value;
}
size_t fcws__models__get_packed_size
                     (const FCWS__Models *message)
{
  assert(message->base.descriptor == &fcws__models__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fcws__models__pack
                     (const FCWS__Models *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &fcws__models__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fcws__models__pack_to_buffer
                     (const FCWS__Models *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &fcws__models__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FCWS__Models *
       fcws__models__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FCWS__Models *)
     protobuf_c_message_unpack (&fcws__models__descriptor,
                                allocator, len, data);
}
void   fcws__models__free_unpacked
                     (FCWS__Models *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &fcws__models__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue fcws__para__type__enum_values_by_number[5] =
{
  { "UnKonwn", "FCWS__PARA__TYPE__UnKonwn", -1 },
  { "PCA", "FCWS__PARA__TYPE__PCA", 0 },
  { "PCA2", "FCWS__PARA__TYPE__PCA2", 1 },
  { "ICA", "FCWS__PARA__TYPE__ICA", 2 },
  { "TOTAL", "FCWS__PARA__TYPE__TOTAL", 3 },
};
static const ProtobufCIntRange fcws__para__type__value_ranges[] = {
{-1, 0},{0, 5}
};
static const ProtobufCEnumValueIndex fcws__para__type__enum_values_by_name[5] =
{
  { "ICA", 3 },
  { "PCA", 1 },
  { "PCA2", 2 },
  { "TOTAL", 4 },
  { "UnKonwn", 0 },
};
const ProtobufCEnumDescriptor fcws__para__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "FCWS.Para.Type",
  "Type",
  "FCWS__Para__Type",
  "FCWS",
  5,
  fcws__para__type__enum_values_by_number,
  5,
  fcws__para__type__enum_values_by_name,
  1,
  fcws__para__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const FCWS__Para__Type fcws__para__type__default_value = FCWS__PARA__TYPE__UnKonwn;
static const ProtobufCFieldDescriptor fcws__para__field_descriptors[4] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(FCWS__Para, type),
    &fcws__para__type__descriptor,
    &fcws__para__type__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rows",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(FCWS__Para, rows),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cols",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(FCWS__Para, cols),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(FCWS__Para, n_data),
    offsetof(FCWS__Para, data),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fcws__para__field_indices_by_name[] = {
  2,   /* field[2] = cols */
  3,   /* field[3] = data */
  1,   /* field[1] = rows */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange fcws__para__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor fcws__para__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FCWS.Para",
  "Para",
  "FCWS__Para",
  "FCWS",
  sizeof(FCWS__Para),
  4,
  fcws__para__field_descriptors,
  fcws__para__field_indices_by_name,
  1,  fcws__para__number_ranges,
  (ProtobufCMessageInit) fcws__para__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue fcws__local__type__enum_values_by_number[5] =
{
  { "UnKonwn", "FCWS__LOCAL__TYPE__UnKonwn", -1 },
  { "LEFT", "FCWS__LOCAL__TYPE__LEFT", 0 },
  { "RIGHT", "FCWS__LOCAL__TYPE__RIGHT", 1 },
  { "CENTER", "FCWS__LOCAL__TYPE__CENTER", 2 },
  { "TOTAL", "FCWS__LOCAL__TYPE__TOTAL", 3 },
};
static const ProtobufCIntRange fcws__local__type__value_ranges[] = {
{-1, 0},{0, 5}
};
static const ProtobufCEnumValueIndex fcws__local__type__enum_values_by_name[5] =
{
  { "CENTER", 3 },
  { "LEFT", 1 },
  { "RIGHT", 2 },
  { "TOTAL", 4 },
  { "UnKonwn", 0 },
};
const ProtobufCEnumDescriptor fcws__local__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "FCWS.Local.Type",
  "Type",
  "FCWS__Local__Type",
  "FCWS",
  5,
  fcws__local__type__enum_values_by_number,
  5,
  fcws__local__type__enum_values_by_name,
  1,
  fcws__local__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const FCWS__Local__Type fcws__local__local__default_value = FCWS__LOCAL__TYPE__UnKonwn;
static const ProtobufCFieldDescriptor fcws__local__field_descriptors[2] =
{
  {
    "local",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(FCWS__Local, local),
    &fcws__local__type__descriptor,
    &fcws__local__local__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "para",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(FCWS__Local, n_para),
    offsetof(FCWS__Local, para),
    &fcws__para__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fcws__local__field_indices_by_name[] = {
  0,   /* field[0] = local */
  1,   /* field[1] = para */
};
static const ProtobufCIntRange fcws__local__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor fcws__local__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FCWS.Local",
  "Local",
  "FCWS__Local",
  "FCWS",
  sizeof(FCWS__Local),
  2,
  fcws__local__field_descriptors,
  fcws__local__field_indices_by_name,
  1,  fcws__local__number_ranges,
  (ProtobufCMessageInit) fcws__local__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue fcws__vehicle__model__type__enum_values_by_number[10] =
{
  { "UnKonwn", "FCWS__VEHICLE__MODEL__TYPE__UnKonwn", -1 },
  { "Compact", "FCWS__VEHICLE__MODEL__TYPE__Compact", 0 },
  { "Midsize", "FCWS__VEHICLE__MODEL__TYPE__Midsize", 1 },
  { "Large", "FCWS__VEHICLE__MODEL__TYPE__Large", 2 },
  { "SUV", "FCWS__VEHICLE__MODEL__TYPE__SUV", 3 },
  { "BUS", "FCWS__VEHICLE__MODEL__TYPE__BUS", 4 },
  { "TRUCK", "FCWS__VEHICLE__MODEL__TYPE__TRUCK", 5 },
  { "MOTOCYCLE", "FCWS__VEHICLE__MODEL__TYPE__MOTOCYCLE", 6 },
  { "BYCYCLE", "FCWS__VEHICLE__MODEL__TYPE__BYCYCLE", 7 },
  { "TOTAL", "FCWS__VEHICLE__MODEL__TYPE__TOTAL", 8 },
};
static const ProtobufCIntRange fcws__vehicle__model__type__value_ranges[] = {
{-1, 0},{0, 10}
};
static const ProtobufCEnumValueIndex fcws__vehicle__model__type__enum_values_by_name[10] =
{
  { "BUS", 5 },
  { "BYCYCLE", 8 },
  { "Compact", 1 },
  { "Large", 3 },
  { "MOTOCYCLE", 7 },
  { "Midsize", 2 },
  { "SUV", 4 },
  { "TOTAL", 9 },
  { "TRUCK", 6 },
  { "UnKonwn", 0 },
};
const ProtobufCEnumDescriptor fcws__vehicle__model__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "FCWS.Vehicle_Model.Type",
  "Type",
  "FCWS__VehicleModel__Type",
  "FCWS",
  10,
  fcws__vehicle__model__type__enum_values_by_number,
  10,
  fcws__vehicle__model__type__enum_values_by_name,
  1,
  fcws__vehicle__model__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const FCWS__VehicleModel__Type fcws__vehicle__model__type__default_value = FCWS__VEHICLE__MODEL__TYPE__UnKonwn;
static const ProtobufCFieldDescriptor fcws__vehicle__model__field_descriptors[2] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(FCWS__VehicleModel, type),
    &fcws__vehicle__model__type__descriptor,
    &fcws__vehicle__model__type__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "local",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(FCWS__VehicleModel, n_local),
    offsetof(FCWS__VehicleModel, local),
    &fcws__local__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fcws__vehicle__model__field_indices_by_name[] = {
  1,   /* field[1] = local */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange fcws__vehicle__model__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor fcws__vehicle__model__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FCWS.Vehicle_Model",
  "VehicleModel",
  "FCWS__VehicleModel",
  "FCWS",
  sizeof(FCWS__VehicleModel),
  2,
  fcws__vehicle__model__field_descriptors,
  fcws__vehicle__model__field_indices_by_name,
  1,  fcws__vehicle__model__number_ranges,
  (ProtobufCMessageInit) fcws__vehicle__model__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor fcws__models__field_descriptors[1] =
{
  {
    "vm",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(FCWS__Models, n_vm),
    offsetof(FCWS__Models, vm),
    &fcws__vehicle__model__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fcws__models__field_indices_by_name[] = {
  0,   /* field[0] = vm */
};
static const ProtobufCIntRange fcws__models__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor fcws__models__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FCWS.Models",
  "Models",
  "FCWS__Models",
  "FCWS",
  sizeof(FCWS__Models),
  1,
  fcws__models__field_descriptors,
  fcws__models__field_indices_by_name,
  1,  fcws__models__number_ranges,
  (ProtobufCMessageInit) fcws__models__init,
  NULL,NULL,NULL    /* reserved[123] */
};
