VideoCore Library: interface/mmal/core/mmal_clock_private.h File Reference
mmal_clock_private.h File Reference
#include "interface/mmal/mmal.h"
#include "interface/mmal/mmal_clock.h"
Classes
struct MMAL_CLOCK_T
Typedefs
typedef struct MMAL_CLOCK_T MMAL_CLOCK_T
typedef void(* MMAL_CLOCK_VOID_FP) (void)
typedef void(* MMAL_CLOCK_REQUEST_CB) (MMAL_CLOCK_T *clock, int64_t media_time, void *cb_data, MMAL_CLOCK_VOID_FP priv)
Functions
MMAL_STATUS_T mmal_clock_create (MMAL_CLOCK_T **clock)
MMAL_STATUS_T mmal_clock_destroy (MMAL_CLOCK_T *clock)
MMAL_STATUS_T mmal_clock_request_add (MMAL_CLOCK_T *clock, int64_t media_time, MMAL_CLOCK_REQUEST_CB cb, void *cb_data, MMAL_CLOCK_VOID_FP priv)
MMAL_STATUS_T mmal_clock_request_flush (MMAL_CLOCK_T *clock)
MMAL_STATUS_T mmal_clock_media_time_set (MMAL_CLOCK_T *clock, int64_t media_time)
MMAL_STATUS_T mmal_clock_scale_set (MMAL_CLOCK_T *clock, MMAL_RATIONAL_T scale)
MMAL_STATUS_T mmal_clock_active_set (MMAL_CLOCK_T *clock, MMAL_BOOL_T active)
MMAL_RATIONAL_T mmal_clock_scale_get (MMAL_CLOCK_T *clock)
int64_t mmal_clock_media_time_get (MMAL_CLOCK_T *clock)
MMAL_BOOL_T mmal_clock_is_active (MMAL_CLOCK_T *clock)
MMAL_STATUS_T mmal_clock_update_threshold_get (MMAL_CLOCK_T *clock, MMAL_CLOCK_UPDATE_THRESHOLD_T *update_threshold)
MMAL_STATUS_T mmal_clock_update_threshold_set (MMAL_CLOCK_T *clock, const MMAL_CLOCK_UPDATE_THRESHOLD_T *update_threshold)
MMAL_STATUS_T mmal_clock_discont_threshold_get (MMAL_CLOCK_T *clock, MMAL_CLOCK_DISCONT_THRESHOLD_T *discont)
MMAL_STATUS_T mmal_clock_discont_threshold_set (MMAL_CLOCK_T *clock, const MMAL_CLOCK_DISCONT_THRESHOLD_T *discont)
MMAL_STATUS_T mmal_clock_request_threshold_get (MMAL_CLOCK_T *clock, MMAL_CLOCK_REQUEST_THRESHOLD_T *req)
MMAL_STATUS_T mmal_clock_request_threshold_set (MMAL_CLOCK_T *clock, const MMAL_CLOCK_REQUEST_THRESHOLD_T *req)
Typedef Documentation
MMAL_CLOCK_REQUEST_CB
typedef void(* MMAL_CLOCK_REQUEST_CB) (MMAL_CLOCK_T *clock, int64_t media_time, void *cb_data, MMAL_CLOCK_VOID_FP priv)
Definition at line 70 of file mmal_clock_private.h.
MMAL_CLOCK_T
typedef struct MMAL_CLOCK_T MMAL_CLOCK_T
Handle to a clock.
MMAL_CLOCK_VOID_FP
typedef void(* MMAL_CLOCK_VOID_FP) (void)
Definition of a clock request callback. This is invoked when the media-time requested by the client is reached.
Parameters
clock The clock which serviced the request
media_time The current media-time
cb_data Client-supplied data
priv Function pointer used by the framework
Definition at line 69 of file mmal_clock_private.h.
Function Documentation
mmal_clock_active_set()
MMAL_STATUS_T mmal_clock_active_set (MMAL_CLOCK_T * clock, MMAL_BOOL_T active)
Set the clock state.
Parameters
clock The clock
active TRUE -> clock is active and media-time is advancing
Returns
MMAL_SUCCESS on success
Definition at line 765 of file mmal_clock.c.
Referenced by mmal_port_clock_active_set().
 {
    if (active)
       mmal_clock_start(clock);
    else
       mmal_clock_stop(clock);
    return MMAL_SUCCESS;
 }
mmal_clock_create()
MMAL_STATUS_T mmal_clock_create (MMAL_CLOCK_T ** clock)
Create a new instance of a clock.
Parameters
clock Returned clock
Returns
MMAL_SUCCESS on success
Definition at line 542 of file mmal_clock.c.
References CLOCK_DISCONT_DURATION, CLOCK_DISCONT_THRESHOLD, CLOCK_UPDATE_THRESHOLD_LOWER, CLOCK_UPDATE_THRESHOLD_UPPER, LOG_ERROR, mmal_clock_scale_set(), MMAL_EINVAL, MMAL_ENOMEM, MMAL_ENOSPC, MMAL_FALSE, MMAL_SUCCESS, NULL, vcos_calloc(), vcos_free(), vcos_mutex_create(), and VCOS_SUCCESS.
 {
    unsigned int size = sizeof(MMAL_CLOCK_PRIVATE_T);
    MMAL_RATIONAL_T scale = { 1, 1 };
    MMAL_CLOCK_PRIVATE_T *private;
    /* Sanity checking */
    if (clock == NULL)
       return MMAL_EINVAL;
    private = vcos_calloc(1, size, "mmal-clock");
    if (!private)
    {
       LOG_ERROR("failed to allocate memory");
       return MMAL_ENOMEM;
    }
    if (vcos_mutex_create(&private->lock, "mmal-clock lock") != VCOS_SUCCESS)
    {
       LOG_ERROR("failed to create lock mutex");
       vcos_free(private);
       return MMAL_ENOSPC;
    }
    /* Set the default threshold values */
    private->update_threshold_lower = CLOCK_UPDATE_THRESHOLD_LOWER;
    private->update_threshold_upper = CLOCK_UPDATE_THRESHOLD_UPPER;
    private->discont_threshold      = CLOCK_DISCONT_THRESHOLD;
    private->discont_duration       = CLOCK_DISCONT_DURATION;
    private->request_threshold      = 0;
    private->request_threshold_enable = MMAL_FALSE;
    /* Default scale = 1.0, i.e. normal playback speed */
    mmal_clock_scale_set(&private->clock, scale);
    *clock = &private->clock;
    return MMAL_SUCCESS;
 }
mmal_clock_destroy()
MMAL_STATUS_T mmal_clock_destroy (MMAL_CLOCK_T * clock)
Destroy a previously created clock.
Parameters
clock The clock to destroy
Returns
MMAL_SUCCESS on success
Definition at line 582 of file mmal_clock.c.
 {
    MMAL_CLOCK_PRIVATE_T *private = (MMAL_CLOCK_PRIVATE_T*)clock;
    if (private->scheduling)
       mmal_clock_destroy_scheduling(private);
    vcos_mutex_delete(&private->lock);
    vcos_free(private);
    return MMAL_SUCCESS;
 }
mmal_clock_discont_threshold_get()
MMAL_STATUS_T mmal_clock_discont_threshold_get (MMAL_CLOCK_T * clock, MMAL_CLOCK_DISCONT_THRESHOLD_T * discont)
Get the clock's discontinuity threshold values.
Parameters
clock The clock
discont Pointer to clock discontinuity threshold values to fill
Returns
MMAL_SUCCESS on success
Definition at line 837 of file mmal_clock.c.
References MMAL_CLOCK_DISCONT_THRESHOLD_T::duration, LOCK, MMAL_SUCCESS, MMAL_CLOCK_DISCONT_THRESHOLD_T::threshold, and UNLOCK.
Referenced by mmal_port_clock_discont_threshold_get().
 {
    MMAL_CLOCK_PRIVATE_T *private = (MMAL_CLOCK_PRIVATE_T *)clock;
    LOCK(private);
    discont->threshold = private->discont_threshold;
    discont->duration  = private->discont_duration;
    UNLOCK(private);
    return MMAL_SUCCESS;
 }
mmal_clock_discont_threshold_set()
MMAL_STATUS_T mmal_clock_discont_threshold_set (MMAL_CLOCK_T * clock, const MMAL_CLOCK_DISCONT_THRESHOLD_T * discont)
Set the clock's discontinuity threshold values.
Parameters
clock The clock
discont Pointer to new clock discontinuity threshold values
Returns
MMAL_SUCCESS on success
Definition at line 850 of file mmal_clock.c.
References MMAL_CLOCK_DISCONT_THRESHOLD_T::duration, LOCK, LOG_TRACE, MMAL_SUCCESS, MMAL_CLOCK_DISCONT_THRESHOLD_T::threshold, and UNLOCK.
Referenced by mmal_port_clock_discont_threshold_set().
 {
    MMAL_CLOCK_PRIVATE_T *private = (MMAL_CLOCK_PRIVATE_T *)clock;
    LOG_TRACE("new clock discontinuity values: threshold %"PRIi64", duration %"PRIi64,
          discont->threshold, discont->duration);
    LOCK(private);
    private->discont_threshold = discont->threshold;
    private->discont_duration  = discont->duration;
    UNLOCK(private);
    return MMAL_SUCCESS;
 }
mmal_clock_is_active()
MMAL_BOOL_T mmal_clock_is_active (MMAL_CLOCK_T * clock)
Get the clock's state.
Parameters
clock The clock to query
Returns
TRUE if clock is running (i.e. local media-time is advancing)
Definition at line 802 of file mmal_clock.c.
Referenced by mmal_port_clock_active_get().
 {
    return ((MMAL_CLOCK_PRIVATE_T*)clock)->is_active;
 }
mmal_clock_media_time_get()
int64_t mmal_clock_media_time_get (MMAL_CLOCK_T * clock)
Get the clock's current media-time. This takes the clock scale and media-time offset into account.
Parameters
clock The clock to query
Returns
Current media-time in microseconds
Definition at line 789 of file mmal_clock.c.
References LOCK, and MMAL_CLOCK_REQUEST_T::media_time.
Referenced by mmal_port_clock_media_time_get().
 {
    int64_t media_time;
    MMAL_CLOCK_PRIVATE_T *private = (MMAL_CLOCK_PRIVATE_T*)clock;
    LOCK(private);
    media_time = mmal_clock_media_time_get_locked(private);
    UNLOCK(private);
    return media_time;
 }
mmal_clock_media_time_set()
MMAL_STATUS_T mmal_clock_media_time_set (MMAL_CLOCK_T * clock, int64_t media_time)
Update the clock's media-time.
Parameters
clock The clock to update
media_time New media-time to be applied (microseconds)
Returns
MMAL_SUCCESS on success
Definition at line 672 of file mmal_clock.c.
References LOCK, MMAL_CLOCK_REQUEST_T::media_time, MMAL_SUCCESS, MMAL_TRUE, UNLOCK, and vcos_getmicrosecs().
Referenced by mmal_port_clock_media_time_set().
 {
    MMAL_CLOCK_PRIVATE_T *private = (MMAL_CLOCK_PRIVATE_T*)clock;
    MMAL_BOOL_T wake_thread = MMAL_TRUE;
    int64_t time_diff;
    LOCK(private);
    if (!private->is_active)
    {
       uint32_t time_now = vcos_getmicrosecs();
       private->wall_time = time_now;
       private->media_time = media_time;
       private->media_time_frac = 0;
       private->rtc_at_update = time_now;
       UNLOCK(private);
       return MMAL_SUCCESS;
    }
    if (mmal_clock_is_paused(clock))
    {
       LOG_TRACE("clock is paused; ignoring update");
       UNLOCK(private);
       return MMAL_SUCCESS;
    }
    /* Reset the local media-time with the given time reference */
    mmal_clock_update_local_time_locked(private);
    time_diff = private->media_time - media_time;
    if (time_diff >  private->update_threshold_upper ||
        time_diff < -private->update_threshold_upper)
    {
       LOG_TRACE("cur:%"PRIi64" new:%"PRIi64" diff:%"PRIi64, private->media_time, media_time, time_diff);
       private->media_time = media_time;
       private->average_ref_diff = 0;
    }
    else
    {
       private->average_ref_diff = ((private->average_ref_diff << 6) - private->average_ref_diff + time_diff) >> 6;
       if(private->average_ref_diff >  private->update_threshold_lower ||
          private->average_ref_diff < -private->update_threshold_lower)
       {
          LOG_TRACE("cur:%"PRIi64" new:%"PRIi64" ave:%"PRIi64, private->media_time,
                private->media_time - private->average_ref_diff, private->average_ref_diff);
          private->media_time -= private->average_ref_diff;
          private->average_ref_diff = 0;
       }
       else
       {
          /* Don't update the media-time */
          wake_thread = MMAL_FALSE;
          LOG_TRACE("cur:%"PRIi64" new:%"PRIi64" diff:%"PRIi64" ave:%"PRIi64" ignored", private->media_time,
                media_time, private->media_time - media_time, private->average_ref_diff);
       }
    }
    UNLOCK(private);
    if (wake_thread)
       mmal_clock_wake_thread(private);
    return MMAL_SUCCESS;
 }
mmal_clock_request_add()
MMAL_STATUS_T mmal_clock_request_add (MMAL_CLOCK_T * clock, int64_t media_time, MMAL_CLOCK_REQUEST_CB cb, void * cb_data, MMAL_CLOCK_VOID_FP priv)
Register a request with the clock. When the specified media-time is reached, the clock will invoke the supplied callback.
Parameters
clock The clock
media_time The media-time at which the callback should be invoked (microseconds)
cb Callback to invoke
cb_data Client-supplied callback data
priv Function pointer used by the framework
Returns
MMAL_SUCCESS on success
Definition at line 597 of file mmal_clock.c.
References LOCK, LOG_TRACE, and MMAL_FALSE.
Referenced by mmal_port_clock_request_add().
 {
    MMAL_CLOCK_PRIVATE_T *private = (MMAL_CLOCK_PRIVATE_T*)clock;
    MMAL_CLOCK_REQUEST_T *request;
    MMAL_BOOL_T wake_thread = MMAL_FALSE;
    int64_t media_time_now;
    LOG_TRACE("media time %"PRIi64, media_time);
    LOCK(private);
    media_time_now = mmal_clock_media_time_get_locked(private);
    /* Drop the request if request_threshold_enable and the frame exceeds the request threshold */
    if (private->request_threshold_enable && (media_time > (media_time_now + private->request_threshold)))
    {
       LOG_TRACE("dropping request: media time %"PRIi64" now %"PRIi64, media_time, media_time_now);
       UNLOCK(private);
       return MMAL_ECORRUPT;
    }
    /* The clock module is usually only used for time-keeping, so all the
     * objects needed to process client requests are not allocated by default
     * and need to be created on the first client request received */
    if (!private->scheduling)
    {
       if (mmal_clock_create_scheduling(private) != MMAL_SUCCESS)
       {
          LOG_ERROR("failed to create scheduling objects");
          UNLOCK(private);
          return MMAL_ENOSPC;
       }
    }
    request = (MMAL_CLOCK_REQUEST_T*)mmal_list_pop_front(private->request.list_free);
    if (request == NULL)
    {
       LOG_ERROR("no more free clock request slots");
       UNLOCK(private);
       return MMAL_ENOSPC;
    }
    request->cb = cb;
    request->cb_data = cb_data;
    request->priv = priv;
    request->media_time = media_time;
    request->media_time_adj = media_time - (int64_t)(private->scale * CLOCK_TARGET_OFFSET >> 16);
    if (mmal_clock_request_insert(private, request))
       wake_thread = private->is_active;
    UNLOCK(private);
    /* Notify the worker thread */
    if (wake_thread)
       mmal_clock_wake_thread(private);
    return MMAL_SUCCESS;
 }
mmal_clock_request_flush()
MMAL_STATUS_T mmal_clock_request_flush (MMAL_CLOCK_T * clock)
Remove all previously registered clock requests.
Parameters
clock The clock
Returns
MMAL_SUCCESS on success
Definition at line 659 of file mmal_clock.c.
References LOCK.
Referenced by mmal_port_clock_request_flush().
 {
    MMAL_CLOCK_PRIVATE_T *private = (MMAL_CLOCK_PRIVATE_T*)clock;
    LOCK(private);
    if (private->scheduling)
       mmal_clock_request_flush_locked(private, MMAL_TIME_UNKNOWN);
    UNLOCK(private);
    return MMAL_SUCCESS;
 }
mmal_clock_request_threshold_get()
MMAL_STATUS_T mmal_clock_request_threshold_get (MMAL_CLOCK_T * clock, MMAL_CLOCK_REQUEST_THRESHOLD_T * req)
Get the clock's request threshold values.
Parameters
clock The clock
future Pointer to clock request threshold values to fill
Returns
MMAL_SUCCESS on success
Definition at line 866 of file mmal_clock.c.
References LOCK, MMAL_SUCCESS, MMAL_CLOCK_REQUEST_THRESHOLD_T::threshold, MMAL_CLOCK_REQUEST_THRESHOLD_T::threshold_enable, and UNLOCK.
Referenced by mmal_port_clock_request_threshold_get().
 {
    MMAL_CLOCK_PRIVATE_T *private = (MMAL_CLOCK_PRIVATE_T *)clock;
    LOCK(private);
    req->threshold = private->request_threshold;
    req->threshold_enable = private->request_threshold_enable;
    UNLOCK(private);
    return MMAL_SUCCESS;
 }
mmal_clock_request_threshold_set()
MMAL_STATUS_T mmal_clock_request_threshold_set (MMAL_CLOCK_T * clock, const MMAL_CLOCK_REQUEST_THRESHOLD_T * req)
Set the clock's request threshold values.
Parameters
clock The clock
discont Pointer to new clock request threshold values
Returns
MMAL_SUCCESS on success
Definition at line 879 of file mmal_clock.c.
References LOCK, LOG_TRACE, MMAL_SUCCESS, MMAL_CLOCK_REQUEST_THRESHOLD_T::threshold, MMAL_CLOCK_REQUEST_THRESHOLD_T::threshold_enable, and UNLOCK.
Referenced by mmal_port_clock_request_threshold_set().
 {
    MMAL_CLOCK_PRIVATE_T *private = (MMAL_CLOCK_PRIVATE_T *)clock;
    LOG_TRACE("new clock request values: threshold %"PRIi64,
          req->threshold);
    LOCK(private);
    private->request_threshold = req->threshold;
    private->request_threshold_enable = req->threshold_enable;
    UNLOCK(private);
    return MMAL_SUCCESS;
 }
mmal_clock_scale_get()
MMAL_RATIONAL_T mmal_clock_scale_get (MMAL_CLOCK_T * clock)
Get the clock's scale.
Parameters
clock The clock
Returns
Current clock scale
Definition at line 776 of file mmal_clock.c.
References LOCK, and UNLOCK.
Referenced by mmal_port_clock_scale_get().
 {
    MMAL_CLOCK_PRIVATE_T *private = (MMAL_CLOCK_PRIVATE_T*)clock;
    MMAL_RATIONAL_T scale;
    LOCK(private);
    scale = private->scale_rational;
    UNLOCK(private);
    return scale;
 }
mmal_clock_scale_set()
MMAL_STATUS_T mmal_clock_scale_set (MMAL_CLOCK_T * clock, MMAL_RATIONAL_T scale)
Set the clock's scale.
Parameters
clock The clock
scale Scale factor
Returns
MMAL_SUCCESS on success
Definition at line 739 of file mmal_clock.c.
References MMAL_RATIONAL_T::den, LOCK, LOG_TRACE, and MMAL_RATIONAL_T::num.
Referenced by mmal_clock_create(), and mmal_port_clock_scale_set().
 {
    MMAL_CLOCK_PRIVATE_T *private = (MMAL_CLOCK_PRIVATE_T*)clock;
    LOG_TRACE("new scale %d/%d", scale.num, scale.den);
    LOCK(private);
    mmal_clock_update_local_time_locked(private);
    private->scale_rational = scale;
    private->scale = mmal_rational_to_fixed_16_16(scale);
    if (private->scale)
       private->scale_inv = (int32_t)((1LL << 32) / (int64_t)private->scale);
    else
       private->scale_inv = Q16_ONE; /* clock is paused */
    UNLOCK(private);
    mmal_clock_wake_thread(private);
    return MMAL_SUCCESS;
 }
mmal_clock_update_threshold_get()
MMAL_STATUS_T mmal_clock_update_threshold_get (MMAL_CLOCK_T * clock, MMAL_CLOCK_UPDATE_THRESHOLD_T * update_threshold)
Get the clock's media-time update threshold values.
Parameters
clock The clock
update_threshold Pointer to clock update threshold values to fill
Returns
MMAL_SUCCESS on success
Definition at line 808 of file mmal_clock.c.
References LOCK, MMAL_SUCCESS, MMAL_CLOCK_UPDATE_THRESHOLD_T::threshold_lower, MMAL_CLOCK_UPDATE_THRESHOLD_T::threshold_upper, and UNLOCK.
Referenced by mmal_port_clock_update_threshold_get().
 {
    MMAL_CLOCK_PRIVATE_T *private = (MMAL_CLOCK_PRIVATE_T *)clock;
    LOCK(private);
    update_threshold->threshold_lower = private->update_threshold_lower;
    update_threshold->threshold_upper = private->update_threshold_upper;
    UNLOCK(private);
    return MMAL_SUCCESS;
 }
mmal_clock_update_threshold_set()
MMAL_STATUS_T mmal_clock_update_threshold_set (MMAL_CLOCK_T * clock, const MMAL_CLOCK_UPDATE_THRESHOLD_T * update_threshold)
Set the clock's media-time update threshold values.
Parameters
clock The clock
update_threshold Pointer to new clock update threshold values
Returns
MMAL_SUCCESS on success
Definition at line 821 of file mmal_clock.c.
References LOCK, LOG_TRACE, MMAL_SUCCESS, MMAL_CLOCK_UPDATE_THRESHOLD_T::threshold_lower, MMAL_CLOCK_UPDATE_THRESHOLD_T::threshold_upper, and UNLOCK.
Referenced by mmal_port_clock_update_threshold_set().
 {
    MMAL_CLOCK_PRIVATE_T *private = (MMAL_CLOCK_PRIVATE_T *)clock;
    LOG_TRACE("new clock update thresholds: upper %"PRIi64", lower %"PRIi64,
          update_threshold->threshold_lower, update_threshold->threshold_upper);
    LOCK(private);
    private->update_threshold_lower = update_threshold->threshold_lower;
    private->update_threshold_upper = update_threshold->threshold_upper;
    UNLOCK(private);
    return MMAL_SUCCESS;
 }