VideoCore Library: interface/khronos/include/VG/openvg.h File Reference
openvg.h File Reference
OpenVG 1.1 API.
#include "vgplatform.h"
Macros
#define OPENVG_VERSION_1_0 1
#define OPENVG_VERSION_1_0_1 1
#define OPENVG_VERSION_1_1 2
#define VG_MAXSHORT 0x7FFF
#define VG_MAXINT 0x7FFFFFFF
#define VG_MAX_ENUM 0x7FFFFFFF
#define VG_INVALID_HANDLE ((VGHandle)0)
#define VG_FALSE 0
#define VG_TRUE 1
#define VG_PATH_FORMAT_STANDARD 0
#define _OPENVG_H
#define OPENVG_VERSION_1_0 1
#define OPENVG_VERSION_1_0_1 1
#define OPENVG_VERSION_1_1 2
#define VG_MAXSHORT 0x7FFF
#define VG_MAXINT 0x7FFFFFFF
#define VG_MAX_ENUM 0x7FFFFFFF
#define VG_INVALID_HANDLE ((VGHandle)0)
#define VG_FALSE 0
#define VG_TRUE 1
#define VG_PATH_FORMAT_STANDARD 0
Typedefs
typedef VGuint VGHandle
typedef VGHandle VGPath
typedef VGHandle VGImage
typedef VGHandle VGMaskLayer
typedef VGHandle VGFont
typedef VGHandle VGPaint
typedef VGuint VGboolean
Enumerations
enum VGErrorCode {
VG_NO_ERROR = 0, VG_BAD_HANDLE_ERROR = 0x1000, VG_ILLEGAL_ARGUMENT_ERROR = 0x1001, VG_OUT_OF_MEMORY_ERROR = 0x1002,
VG_PATH_CAPABILITY_ERROR = 0x1003, VG_UNSUPPORTED_IMAGE_FORMAT_ERROR = 0x1004, VG_UNSUPPORTED_PATH_FORMAT_ERROR = 0x1005, VG_IMAGE_IN_USE_ERROR = 0x1006,
VG_NO_CONTEXT_ERROR = 0x1007, VG_ERROR_CODE_FORCE_SIZE = VG_MAX_ENUM
}
enum VGParamType {
VG_MATRIX_MODE = 0x1100, VG_FILL_RULE = 0x1101, VG_IMAGE_QUALITY = 0x1102, VG_RENDERING_QUALITY = 0x1103,
VG_BLEND_MODE = 0x1104, VG_IMAGE_MODE = 0x1105, VG_SCISSOR_RECTS = 0x1106, VG_COLOR_TRANSFORM = 0x1170,
VG_COLOR_TRANSFORM_VALUES = 0x1171, VG_STROKE_LINE_WIDTH = 0x1110, VG_STROKE_CAP_STYLE = 0x1111, VG_STROKE_JOIN_STYLE = 0x1112,
VG_STROKE_MITER_LIMIT = 0x1113, VG_STROKE_DASH_PATTERN = 0x1114, VG_STROKE_DASH_PHASE = 0x1115, VG_STROKE_DASH_PHASE_RESET = 0x1116,
VG_TILE_FILL_COLOR = 0x1120, VG_CLEAR_COLOR = 0x1121, VG_GLYPH_ORIGIN = 0x1122, VG_MASKING = 0x1130,
VG_SCISSORING = 0x1131, VG_PIXEL_LAYOUT = 0x1140, VG_SCREEN_LAYOUT = 0x1141, VG_FILTER_FORMAT_LINEAR = 0x1150,
VG_FILTER_FORMAT_PREMULTIPLIED = 0x1151, VG_FILTER_CHANNEL_MASK = 0x1152, VG_MAX_SCISSOR_RECTS = 0x1160, VG_MAX_DASH_COUNT = 0x1161,
VG_MAX_KERNEL_SIZE = 0x1162, VG_MAX_SEPARABLE_KERNEL_SIZE = 0x1163, VG_MAX_COLOR_RAMP_STOPS = 0x1164, VG_MAX_IMAGE_WIDTH = 0x1165,
VG_MAX_IMAGE_HEIGHT = 0x1166, VG_MAX_IMAGE_PIXELS = 0x1167, VG_MAX_IMAGE_BYTES = 0x1168, VG_MAX_FLOAT = 0x1169,
VG_MAX_GAUSSIAN_STD_DEVIATION = 0x116A, VG_PARAM_TYPE_FORCE_SIZE = VG_MAX_ENUM
}
enum VGRenderingQuality { VG_RENDERING_QUALITY_NONANTIALIASED = 0x1200, VG_RENDERING_QUALITY_FASTER = 0x1201, VG_RENDERING_QUALITY_BETTER = 0x1202, VG_RENDERING_QUALITY_FORCE_SIZE = VG_MAX_ENUM }
enum VGPixelLayout {
VG_PIXEL_LAYOUT_UNKNOWN = 0x1300, VG_PIXEL_LAYOUT_RGB_VERTICAL = 0x1301, VG_PIXEL_LAYOUT_BGR_VERTICAL = 0x1302, VG_PIXEL_LAYOUT_RGB_HORIZONTAL = 0x1303,
VG_PIXEL_LAYOUT_BGR_HORIZONTAL = 0x1304, VG_PIXEL_LAYOUT_FORCE_SIZE = VG_MAX_ENUM
}
enum VGMatrixMode {
VG_MATRIX_PATH_USER_TO_SURFACE = 0x1400, VG_MATRIX_IMAGE_USER_TO_SURFACE = 0x1401, VG_MATRIX_FILL_PAINT_TO_USER = 0x1402, VG_MATRIX_STROKE_PAINT_TO_USER = 0x1403,
VG_MATRIX_GLYPH_USER_TO_SURFACE = 0x1404, VG_MATRIX_MODE_FORCE_SIZE = VG_MAX_ENUM
}
enum VGMaskOperation {
VG_CLEAR_MASK = 0x1500, VG_FILL_MASK = 0x1501, VG_SET_MASK = 0x1502, VG_UNION_MASK = 0x1503,
VG_INTERSECT_MASK = 0x1504, VG_SUBTRACT_MASK = 0x1505, VG_MASK_OPERATION_FORCE_SIZE = VG_MAX_ENUM
}
enum VGPathDatatype {
VG_PATH_DATATYPE_S_8 = 0, VG_PATH_DATATYPE_S_16 = 1, VG_PATH_DATATYPE_S_32 = 2, VG_PATH_DATATYPE_F = 3,
VG_PATH_DATATYPE_FORCE_SIZE = VG_MAX_ENUM
}
enum VGPathAbsRel { VG_ABSOLUTE = 0, VG_RELATIVE = 1, VG_PATH_ABS_REL_FORCE_SIZE = VG_MAX_ENUM }
enum VGPathSegment {
VG_CLOSE_PATH = (0 << 1), VG_MOVE_TO = (1 << 1), VG_LINE_TO = (2 << 1), VG_HLINE_TO = (3 << 1),
VG_VLINE_TO = (4 << 1), VG_QUAD_TO = (5 << 1), VG_CUBIC_TO = (6 << 1), VG_SQUAD_TO = (7 << 1),
VG_SCUBIC_TO = (8 << 1), VG_SCCWARC_TO = (9 << 1), VG_SCWARC_TO = (10 << 1), VG_LCCWARC_TO = (11 << 1),
VG_LCWARC_TO = (12 << 1), VG_SEGMENT_MASK = 0xf << 1, VG_PATH_SEGMENT_FORCE_SIZE = VG_MAX_ENUM
}
enum VGPathCommand {
VG_MOVE_TO_ABS = VG_MOVE_TO | VG_ABSOLUTE, VG_MOVE_TO_REL = VG_MOVE_TO | VG_RELATIVE, VG_LINE_TO_ABS = VG_LINE_TO | VG_ABSOLUTE, VG_LINE_TO_REL = VG_LINE_TO | VG_RELATIVE,
VG_HLINE_TO_ABS = VG_HLINE_TO | VG_ABSOLUTE, VG_HLINE_TO_REL = VG_HLINE_TO | VG_RELATIVE, VG_VLINE_TO_ABS = VG_VLINE_TO | VG_ABSOLUTE, VG_VLINE_TO_REL = VG_VLINE_TO | VG_RELATIVE,
VG_QUAD_TO_ABS = VG_QUAD_TO | VG_ABSOLUTE, VG_QUAD_TO_REL = VG_QUAD_TO | VG_RELATIVE, VG_CUBIC_TO_ABS = VG_CUBIC_TO | VG_ABSOLUTE, VG_CUBIC_TO_REL = VG_CUBIC_TO | VG_RELATIVE,
VG_SQUAD_TO_ABS = VG_SQUAD_TO | VG_ABSOLUTE, VG_SQUAD_TO_REL = VG_SQUAD_TO | VG_RELATIVE, VG_SCUBIC_TO_ABS = VG_SCUBIC_TO | VG_ABSOLUTE, VG_SCUBIC_TO_REL = VG_SCUBIC_TO | VG_RELATIVE,
VG_SCCWARC_TO_ABS = VG_SCCWARC_TO | VG_ABSOLUTE, VG_SCCWARC_TO_REL = VG_SCCWARC_TO | VG_RELATIVE, VG_SCWARC_TO_ABS = VG_SCWARC_TO | VG_ABSOLUTE, VG_SCWARC_TO_REL = VG_SCWARC_TO | VG_RELATIVE,
VG_LCCWARC_TO_ABS = VG_LCCWARC_TO | VG_ABSOLUTE, VG_LCCWARC_TO_REL = VG_LCCWARC_TO | VG_RELATIVE, VG_LCWARC_TO_ABS = VG_LCWARC_TO | VG_ABSOLUTE, VG_LCWARC_TO_REL = VG_LCWARC_TO | VG_RELATIVE,
VG_PATH_COMMAND_FORCE_SIZE = VG_MAX_ENUM
}
enum VGPathCapabilities {
VG_PATH_CAPABILITY_APPEND_FROM = (1 << 0), VG_PATH_CAPABILITY_APPEND_TO = (1 << 1), VG_PATH_CAPABILITY_MODIFY = (1 << 2), VG_PATH_CAPABILITY_TRANSFORM_FROM = (1 << 3),
VG_PATH_CAPABILITY_TRANSFORM_TO = (1 << 4), VG_PATH_CAPABILITY_INTERPOLATE_FROM = (1 << 5), VG_PATH_CAPABILITY_INTERPOLATE_TO = (1 << 6), VG_PATH_CAPABILITY_PATH_LENGTH = (1 << 7),
VG_PATH_CAPABILITY_POINT_ALONG_PATH = (1 << 8), VG_PATH_CAPABILITY_TANGENT_ALONG_PATH = (1 << 9), VG_PATH_CAPABILITY_PATH_BOUNDS = (1 << 10), VG_PATH_CAPABILITY_PATH_TRANSFORMED_BOUNDS = (1 << 11),
VG_PATH_CAPABILITY_ALL = (1 << 12) - 1, VG_PATH_CAPABILITIES_FORCE_SIZE = VG_MAX_ENUM
}
enum VGPathParamType {
VG_PATH_FORMAT = 0x1600, VG_PATH_DATATYPE = 0x1601, VG_PATH_SCALE = 0x1602, VG_PATH_BIAS = 0x1603,
VG_PATH_NUM_SEGMENTS = 0x1604, VG_PATH_NUM_COORDS = 0x1605, VG_PATH_PARAM_TYPE_FORCE_SIZE = VG_MAX_ENUM
}
enum VGCapStyle { VG_CAP_BUTT = 0x1700, VG_CAP_ROUND = 0x1701, VG_CAP_SQUARE = 0x1702, VG_CAP_STYLE_FORCE_SIZE = VG_MAX_ENUM }
enum VGJoinStyle { VG_JOIN_MITER = 0x1800, VG_JOIN_ROUND = 0x1801, VG_JOIN_BEVEL = 0x1802, VG_JOIN_STYLE_FORCE_SIZE = VG_MAX_ENUM }
enum VGFillRule { VG_EVEN_ODD = 0x1900, VG_NON_ZERO = 0x1901, VG_FILL_RULE_FORCE_SIZE = VG_MAX_ENUM }
enum VGPaintMode { VG_STROKE_PATH = (1 << 0), VG_FILL_PATH = (1 << 1), VG_PAINT_MODE_FORCE_SIZE = VG_MAX_ENUM }
enum VGPaintParamType {
VG_PAINT_TYPE = 0x1A00, VG_PAINT_COLOR = 0x1A01, VG_PAINT_COLOR_RAMP_SPREAD_MODE = 0x1A02, VG_PAINT_COLOR_RAMP_PREMULTIPLIED = 0x1A07,
VG_PAINT_COLOR_RAMP_STOPS = 0x1A03, VG_PAINT_LINEAR_GRADIENT = 0x1A04, VG_PAINT_RADIAL_GRADIENT = 0x1A05, VG_PAINT_PATTERN_TILING_MODE = 0x1A06,
VG_PAINT_PARAM_TYPE_FORCE_SIZE = VG_MAX_ENUM
}
enum VGPaintType {
VG_PAINT_TYPE_COLOR = 0x1B00, VG_PAINT_TYPE_LINEAR_GRADIENT = 0x1B01, VG_PAINT_TYPE_RADIAL_GRADIENT = 0x1B02, VG_PAINT_TYPE_PATTERN = 0x1B03,
VG_PAINT_TYPE_FORCE_SIZE = VG_MAX_ENUM
}
enum VGColorRampSpreadMode { VG_COLOR_RAMP_SPREAD_PAD = 0x1C00, VG_COLOR_RAMP_SPREAD_REPEAT = 0x1C01, VG_COLOR_RAMP_SPREAD_REFLECT = 0x1C02, VG_COLOR_RAMP_SPREAD_MODE_FORCE_SIZE = VG_MAX_ENUM }
enum VGTilingMode {
VG_TILE_FILL = 0x1D00, VG_TILE_PAD = 0x1D01, VG_TILE_REPEAT = 0x1D02, VG_TILE_REFLECT = 0x1D03,
VG_TILING_MODE_FORCE_SIZE = VG_MAX_ENUM
}
enum VGImageFormat {
VG_sRGBX_8888 = 0, VG_sRGBA_8888 = 1, VG_sRGBA_8888_PRE = 2, VG_sRGB_565 = 3,
VG_sRGBA_5551 = 4, VG_sRGBA_4444 = 5, VG_sL_8 = 6, VG_lRGBX_8888 = 7,
VG_lRGBA_8888 = 8, VG_lRGBA_8888_PRE = 9, VG_lL_8 = 10, VG_A_8 = 11,
VG_BW_1 = 12, VG_A_1 = 13, VG_A_4 = 14, VG_sXRGB_8888 = 0 | (1 << 6),
VG_sARGB_8888 = 1 | (1 << 6), VG_sARGB_8888_PRE = 2 | (1 << 6), VG_sARGB_1555 = 4 | (1 << 6), VG_sARGB_4444 = 5 | (1 << 6),
VG_lXRGB_8888 = 7 | (1 << 6), VG_lARGB_8888 = 8 | (1 << 6), VG_lARGB_8888_PRE = 9 | (1 << 6), VG_sBGRX_8888 = 0 | (1 << 7),
VG_sBGRA_8888 = 1 | (1 << 7), VG_sBGRA_8888_PRE = 2 | (1 << 7), VG_sBGR_565 = 3 | (1 << 7), VG_sBGRA_5551 = 4 | (1 << 7),
VG_sBGRA_4444 = 5 | (1 << 7), VG_lBGRX_8888 = 7 | (1 << 7), VG_lBGRA_8888 = 8 | (1 << 7), VG_lBGRA_8888_PRE = 9 | (1 << 7),
VG_sXBGR_8888 = 0 | (1 << 6) | (1 << 7), VG_sABGR_8888 = 1 | (1 << 6) | (1 << 7), VG_sABGR_8888_PRE = 2 | (1 << 6) | (1 << 7), VG_sABGR_1555 = 4 | (1 << 6) | (1 << 7),
VG_sABGR_4444 = 5 | (1 << 6) | (1 << 7), VG_lXBGR_8888 = 7 | (1 << 6) | (1 << 7), VG_lABGR_8888 = 8 | (1 << 6) | (1 << 7), VG_lABGR_8888_PRE = 9 | (1 << 6) | (1 << 7),
VG_IMAGE_FORMAT_FORCE_SIZE = VG_MAX_ENUM
}
enum VGImageQuality { VG_IMAGE_QUALITY_NONANTIALIASED = (1 << 0), VG_IMAGE_QUALITY_FASTER = (1 << 1), VG_IMAGE_QUALITY_BETTER = (1 << 2), VG_IMAGE_QUALITY_FORCE_SIZE = VG_MAX_ENUM }
enum VGImageParamType { VG_IMAGE_FORMAT = 0x1E00, VG_IMAGE_WIDTH = 0x1E01, VG_IMAGE_HEIGHT = 0x1E02, VG_IMAGE_PARAM_TYPE_FORCE_SIZE = VG_MAX_ENUM }
enum VGImageMode { VG_DRAW_IMAGE_NORMAL = 0x1F00, VG_DRAW_IMAGE_MULTIPLY = 0x1F01, VG_DRAW_IMAGE_STENCIL = 0x1F02, VG_IMAGE_MODE_FORCE_SIZE = VG_MAX_ENUM }
enum VGImageChannel {
VG_RED = (1 << 3), VG_GREEN = (1 << 2), VG_BLUE = (1 << 1), VG_ALPHA = (1 << 0),
VG_IMAGE_CHANNEL_FORCE_SIZE = VG_MAX_ENUM
}
enum VGBlendMode {
VG_BLEND_SRC = 0x2000, VG_BLEND_SRC_OVER = 0x2001, VG_BLEND_DST_OVER = 0x2002, VG_BLEND_SRC_IN = 0x2003,
VG_BLEND_DST_IN = 0x2004, VG_BLEND_MULTIPLY = 0x2005, VG_BLEND_SCREEN = 0x2006, VG_BLEND_DARKEN = 0x2007,
VG_BLEND_LIGHTEN = 0x2008, VG_BLEND_ADDITIVE = 0x2009, VG_BLEND_MODE_FORCE_SIZE = VG_MAX_ENUM
}
enum VGFontParamType { VG_FONT_NUM_GLYPHS = 0x2F00, VG_FONT_PARAM_TYPE_FORCE_SIZE = VG_MAX_ENUM }
enum VGHardwareQueryType { VG_IMAGE_FORMAT_QUERY = 0x2100, VG_PATH_DATATYPE_QUERY = 0x2101, VG_HARDWARE_QUERY_TYPE_FORCE_SIZE = VG_MAX_ENUM }
enum VGHardwareQueryResult { VG_HARDWARE_ACCELERATED = 0x2200, VG_HARDWARE_UNACCELERATED = 0x2201, VG_HARDWARE_QUERY_RESULT_FORCE_SIZE = VG_MAX_ENUM }
enum VGStringID {
VG_VENDOR = 0x2300, VG_RENDERER = 0x2301, VG_VERSION = 0x2302, VG_EXTENSIONS = 0x2303,
VG_STRING_ID_FORCE_SIZE = VG_MAX_ENUM
}
Functions
VG_API_CALL VGErrorCode VG_API_ENTRY vgGetError (void) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgFlush (void) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgFinish (void) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgSetf (VGParamType type, VGfloat value) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgSeti (VGParamType type, VGint value) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgSetfv (VGParamType type, VGint count, const VGfloat *values) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgSetiv (VGParamType type, VGint count, const VGint *values) VG_API_EXIT
VG_API_CALL VGfloat VG_API_ENTRY vgGetf (VGParamType type) VG_API_EXIT
VG_API_CALL VGint VG_API_ENTRY vgGeti (VGParamType type) VG_API_EXIT
VG_API_CALL VGint VG_API_ENTRY vgGetVectorSize (VGParamType type) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgGetfv (VGParamType type, VGint count, VGfloat *values) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgGetiv (VGParamType type, VGint count, VGint *values) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgSetParameterf (VGHandle object, VGint paramType, VGfloat value) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgSetParameteri (VGHandle object, VGint paramType, VGint value) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgSetParameterfv (VGHandle object, VGint paramType, VGint count, const VGfloat *values) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgSetParameteriv (VGHandle object, VGint paramType, VGint count, const VGint *values) VG_API_EXIT
VG_API_CALL VGfloat VG_API_ENTRY vgGetParameterf (VGHandle object, VGint paramType) VG_API_EXIT
VG_API_CALL VGint VG_API_ENTRY vgGetParameteri (VGHandle object, VGint paramType)
VG_API_CALL VGint VG_API_ENTRY vgGetParameterVectorSize (VGHandle object, VGint paramType) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgGetParameterfv (VGHandle object, VGint paramType, VGint count, VGfloat *values) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgGetParameteriv (VGHandle object, VGint paramType, VGint count, VGint *values) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgLoadIdentity (void) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgLoadMatrix (const VGfloat *m) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgGetMatrix (VGfloat *m) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgMultMatrix (const VGfloat *m) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgTranslate (VGfloat tx, VGfloat ty) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgScale (VGfloat sx, VGfloat sy) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgShear (VGfloat shx, VGfloat shy) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgRotate (VGfloat angle) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgMask (VGHandle mask, VGMaskOperation operation, VGint x, VGint y, VGint width, VGint height) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgRenderToMask (VGPath path, VGbitfield paintModes, VGMaskOperation operation) VG_API_EXIT
VG_API_CALL VGMaskLayer VG_API_ENTRY vgCreateMaskLayer (VGint width, VGint height) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgDestroyMaskLayer (VGMaskLayer maskLayer) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgFillMaskLayer (VGMaskLayer maskLayer, VGint x, VGint y, VGint width, VGint height, VGfloat value) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgCopyMask (VGMaskLayer maskLayer, VGint dx, VGint dy, VGint sx, VGint sy, VGint width, VGint height) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgClear (VGint x, VGint y, VGint width, VGint height) VG_API_EXIT
VG_API_CALL VGPath VG_API_ENTRY vgCreatePath (VGint pathFormat, VGPathDatatype datatype, VGfloat scale, VGfloat bias, VGint segmentCapacityHint, VGint coordCapacityHint, VGbitfield capabilities) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgClearPath (VGPath path, VGbitfield capabilities) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgDestroyPath (VGPath path) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgRemovePathCapabilities (VGPath path, VGbitfield capabilities) VG_API_EXIT
VG_API_CALL VGbitfield VG_API_ENTRY vgGetPathCapabilities (VGPath path) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgAppendPath (VGPath dstPath, VGPath srcPath) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgAppendPathData (VGPath dstPath, VGint numSegments, const VGubyte *pathSegments, const void *pathData) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgModifyPathCoords (VGPath dstPath, VGint startIndex, VGint numSegments, const void *pathData) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgTransformPath (VGPath dstPath, VGPath srcPath) VG_API_EXIT
VG_API_CALL VGboolean VG_API_ENTRY vgInterpolatePath (VGPath dstPath, VGPath startPath, VGPath endPath, VGfloat amount) VG_API_EXIT
VG_API_CALL VGfloat VG_API_ENTRY vgPathLength (VGPath path, VGint startSegment, VGint numSegments) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgPointAlongPath (VGPath path, VGint startSegment, VGint numSegments, VGfloat distance, VGfloat *x, VGfloat *y, VGfloat *tangentX, VGfloat *tangentY) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgPathBounds (VGPath path, VGfloat *minX, VGfloat *minY, VGfloat *width, VGfloat *height) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgPathTransformedBounds (VGPath path, VGfloat *minX, VGfloat *minY, VGfloat *width, VGfloat *height) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgDrawPath (VGPath path, VGbitfield paintModes) VG_API_EXIT
VG_API_CALL VGPaint VG_API_ENTRY vgCreatePaint (void) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgDestroyPaint (VGPaint paint) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgSetPaint (VGPaint paint, VGbitfield paintModes) VG_API_EXIT
VG_API_CALL VGPaint VG_API_ENTRY vgGetPaint (VGPaintMode paintMode) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgSetColor (VGPaint paint, VGuint rgba) VG_API_EXIT
VG_API_CALL VGuint VG_API_ENTRY vgGetColor (VGPaint paint) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgPaintPattern (VGPaint paint, VGImage pattern) VG_API_EXIT
VG_API_CALL VGImage VG_API_ENTRY vgCreateImage (VGImageFormat format, VGint width, VGint height, VGbitfield allowedQuality) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgDestroyImage (VGImage image) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgClearImage (VGImage image, VGint x, VGint y, VGint width, VGint height) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgImageSubData (VGImage image, const void *data, VGint dataStride, VGImageFormat dataFormat, VGint x, VGint y, VGint width, VGint height) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgGetImageSubData (VGImage image, void *data, VGint dataStride, VGImageFormat dataFormat, VGint x, VGint y, VGint width, VGint height) VG_API_EXIT
VG_API_CALL VGImage VG_API_ENTRY vgChildImage (VGImage parent, VGint x, VGint y, VGint width, VGint height) VG_API_EXIT
VG_API_CALL VGImage VG_API_ENTRY vgGetParent (VGImage image) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgCopyImage (VGImage dst, VGint dx, VGint dy, VGImage src, VGint sx, VGint sy, VGint width, VGint height, VGboolean dither) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgDrawImage (VGImage image) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgSetPixels (VGint dx, VGint dy, VGImage src, VGint sx, VGint sy, VGint width, VGint height) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgWritePixels (const void *data, VGint dataStride, VGImageFormat dataFormat, VGint dx, VGint dy, VGint width, VGint height) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgGetPixels (VGImage dst, VGint dx, VGint dy, VGint sx, VGint sy, VGint width, VGint height) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgReadPixels (void *data, VGint dataStride, VGImageFormat dataFormat, VGint sx, VGint sy, VGint width, VGint height) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgCopyPixels (VGint dx, VGint dy, VGint sx, VGint sy, VGint width, VGint height) VG_API_EXIT
VG_API_CALL VGFont VG_API_ENTRY vgCreateFont (VGint glyphCapacityHint) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgDestroyFont (VGFont font) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgSetGlyphToPath (VGFont font, VGuint glyphIndex, VGPath path, VGboolean isHinted, VGfloat glyphOrigin [2], VGfloat escapement[2]) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgSetGlyphToImage (VGFont font, VGuint glyphIndex, VGImage image, VGfloat glyphOrigin [2], VGfloat escapement[2]) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgClearGlyph (VGFont font, VGuint glyphIndex) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgDrawGlyph (VGFont font, VGuint glyphIndex, VGbitfield paintModes, VGboolean allowAutoHinting) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgDrawGlyphs (VGFont font, VGint glyphCount, const VGuint *glyphIndices, const VGfloat *adjustments_x, const VGfloat *adjustments_y, VGbitfield paintModes, VGboolean allowAutoHinting) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgColorMatrix (VGImage dst, VGImage src, const VGfloat *matrix) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgConvolve (VGImage dst, VGImage src, VGint kernelWidth, VGint kernelHeight, VGint shiftX, VGint shiftY, const VGshort *kernel, VGfloat scale, VGfloat bias, VGTilingMode tilingMode) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgSeparableConvolve (VGImage dst, VGImage src, VGint kernelWidth, VGint kernelHeight, VGint shiftX, VGint shiftY, const VGshort *kernelX, const VGshort *kernelY, VGfloat scale, VGfloat bias, VGTilingMode tilingMode) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgGaussianBlur (VGImage dst, VGImage src, VGfloat stdDeviationX, VGfloat stdDeviationY, VGTilingMode tilingMode) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgLookup (VGImage dst, VGImage src, const VGubyte *redLUT, const VGubyte *greenLUT, const VGubyte *blueLUT, const VGubyte *alphaLUT, VGboolean outputLinear, VGboolean outputPremultiplied) VG_API_EXIT
VG_API_CALL void VG_API_ENTRY vgLookupSingle (VGImage dst, VGImage src, const VGuint *lookupTable, VGImageChannel sourceChannel, VGboolean outputLinear, VGboolean outputPremultiplied) VG_API_EXIT
VG_API_CALL VGHardwareQueryResult VG_API_ENTRY vgHardwareQuery (VGHardwareQueryType key, VGint setting) VG_API_EXIT
VG_API_CALL const VGubyte *VG_API_ENTRY vgGetString (VGStringID name) VG_API_EXIT
Detailed Description
OpenVG 1.1 API.
Definition in file openvg.h.
Macro Definition Documentation
_OPENVG_H
#define _OPENVG_H
Definition at line 36 of file khrn_misc.h.
OPENVG_VERSION_1_0 [1/2]
#define OPENVG_VERSION_1_0 1
Definition at line 43 of file khrn_misc.h.
OPENVG_VERSION_1_0 [2/2]
#define OPENVG_VERSION_1_0 1
OPENVG_VERSION_1_0_1 [1/2]
#define OPENVG_VERSION_1_0_1 1
Definition at line 44 of file khrn_misc.h.
OPENVG_VERSION_1_0_1 [2/2]
#define OPENVG_VERSION_1_0_1 1
OPENVG_VERSION_1_1 [1/2]
#define OPENVG_VERSION_1_1 2
Definition at line 45 of file khrn_misc.h.
OPENVG_VERSION_1_1 [2/2]
#define OPENVG_VERSION_1_1 2
VG_FALSE [1/2]
#define VG_FALSE 0
Definition at line 70 of file khrn_misc.h.
Referenced by gx_priv_resource_fill().
VG_FALSE [2/2]
#define VG_FALSE 0
VG_INVALID_HANDLE [1/2]
#define VG_INVALID_HANDLE ((VGHandle)0)
VG_INVALID_HANDLE [2/2]
#define VG_INVALID_HANDLE ((VGHandle)0)
Definition at line 67 of file khrn_misc.h.
Referenced by graphics_bitblt(), gx_create_gradient(), vgft_font_convert_glyphs(), and vgft_font_init().
VG_MAX_ENUM [1/2]
#define VG_MAX_ENUM 0x7FFFFFFF
VG_MAX_ENUM [2/2]
#define VG_MAX_ENUM 0x7FFFFFFF
Definition at line 56 of file khrn_misc.h.
VG_MAXINT [1/2]
#define VG_MAXINT 0x7FFFFFFF
Definition at line 52 of file khrn_misc.h.
VG_MAXINT [2/2]
#define VG_MAXINT 0x7FFFFFFF
VG_MAXSHORT [1/2]
#define VG_MAXSHORT 0x7FFF
VG_MAXSHORT [2/2]
#define VG_MAXSHORT 0x7FFF
Definition at line 48 of file khrn_misc.h.
VG_PATH_FORMAT_STANDARD [1/2]
#define VG_PATH_FORMAT_STANDARD 0
VG_PATH_FORMAT_STANDARD [2/2]
#define VG_PATH_FORMAT_STANDARD 0
Definition at line 191 of file khrn_misc.h.
Referenced by gx_fill_gradient(), gx_render_arrowhead(), PS_construct(), and vgft_font_convert_glyphs().
VG_TRUE [1/2]
#define VG_TRUE 1
VG_TRUE [2/2]
#define VG_TRUE 1
Definition at line 71 of file khrn_misc.h.
Typedef Documentation
VGboolean
typedef VGuint VGboolean
Definition at line 69 of file openvg.h.
VGFont
typedef VGHandle VGFont
Definition at line 64 of file openvg.h.
VGHandle
typedef VGuint VGHandle
Definition at line 59 of file openvg.h.
VGImage
typedef VGHandle VGImage
Definition at line 62 of file openvg.h.
VGMaskLayer
typedef VGHandle VGMaskLayer
Definition at line 63 of file openvg.h.
VGPaint
typedef VGHandle VGPaint
Definition at line 65 of file openvg.h.
VGPath
typedef VGHandle VGPath
Definition at line 61 of file openvg.h.
Enumeration Type Documentation
VGBlendMode
enum VGBlendMode
Enumerator
VG_BLEND_SRC
VG_BLEND_SRC_OVER
VG_BLEND_DST_OVER
VG_BLEND_SRC_IN
VG_BLEND_DST_IN
VG_BLEND_MULTIPLY
VG_BLEND_SCREEN
VG_BLEND_DARKEN
VG_BLEND_LIGHTEN
VG_BLEND_ADDITIVE
VG_BLEND_MODE_FORCE_SIZE
Definition at line 448 of file openvg.h.
              {
   VG_BLEND_SRC                                = 0x2000,
   VG_BLEND_SRC_OVER                           = 0x2001,
   VG_BLEND_DST_OVER                           = 0x2002,
   VG_BLEND_SRC_IN                             = 0x2003,
   VG_BLEND_DST_IN                             = 0x2004,
   VG_BLEND_MULTIPLY                           = 0x2005,
   VG_BLEND_SCREEN                             = 0x2006,
   VG_BLEND_DARKEN                             = 0x2007,
   VG_BLEND_LIGHTEN                            = 0x2008,
   VG_BLEND_ADDITIVE                           = 0x2009,
   VG_BLEND_MODE_FORCE_SIZE                    = VG_MAX_ENUM
 } VGBlendMode;
VGCapStyle
enum VGCapStyle
Enumerator
VG_CAP_BUTT
VG_CAP_ROUND
VG_CAP_SQUARE
VG_CAP_STYLE_FORCE_SIZE
Definition at line 287 of file openvg.h.
              {
   VG_CAP_BUTT                                 = 0x1700,
   VG_CAP_ROUND                                = 0x1701,
   VG_CAP_SQUARE                               = 0x1702,
   VG_CAP_STYLE_FORCE_SIZE                     = VG_MAX_ENUM
 } VGCapStyle;
VGColorRampSpreadMode
enum VGColorRampSpreadMode
Enumerator
VG_COLOR_RAMP_SPREAD_PAD
VG_COLOR_RAMP_SPREAD_REPEAT
VG_COLOR_RAMP_SPREAD_REFLECT
VG_COLOR_RAMP_SPREAD_MODE_FORCE_SIZE
Definition at line 346 of file openvg.h.
              {
   VG_COLOR_RAMP_SPREAD_PAD                    = 0x1C00,
   VG_COLOR_RAMP_SPREAD_REPEAT                 = 0x1C01,
   VG_COLOR_RAMP_SPREAD_REFLECT                = 0x1C02,
   VG_COLOR_RAMP_SPREAD_MODE_FORCE_SIZE        = VG_MAX_ENUM
 } VGColorRampSpreadMode;
VGErrorCode
enum VGErrorCode
Enumerator
VG_NO_ERROR
VG_BAD_HANDLE_ERROR
VG_ILLEGAL_ARGUMENT_ERROR
VG_OUT_OF_MEMORY_ERROR
VG_PATH_CAPABILITY_ERROR
VG_UNSUPPORTED_IMAGE_FORMAT_ERROR
VG_UNSUPPORTED_PATH_FORMAT_ERROR
VG_IMAGE_IN_USE_ERROR
VG_NO_CONTEXT_ERROR
VG_ERROR_CODE_FORCE_SIZE
Definition at line 73 of file openvg.h.
              {
   VG_NO_ERROR                                 = 0,
   VG_BAD_HANDLE_ERROR                         = 0x1000,
   VG_ILLEGAL_ARGUMENT_ERROR                   = 0x1001,
   VG_OUT_OF_MEMORY_ERROR                      = 0x1002,
   VG_PATH_CAPABILITY_ERROR                    = 0x1003,
   VG_UNSUPPORTED_IMAGE_FORMAT_ERROR           = 0x1004,
   VG_UNSUPPORTED_PATH_FORMAT_ERROR            = 0x1005,
   VG_IMAGE_IN_USE_ERROR                       = 0x1006,
   VG_NO_CONTEXT_ERROR                         = 0x1007,
   VG_ERROR_CODE_FORCE_SIZE                    = VG_MAX_ENUM
 } VGErrorCode;
VGFillRule
enum VGFillRule
Enumerator
VG_EVEN_ODD
VG_NON_ZERO
VG_FILL_RULE_FORCE_SIZE
Definition at line 303 of file openvg.h.
              {
   VG_EVEN_ODD                                 = 0x1900,
   VG_NON_ZERO                                 = 0x1901,
   VG_FILL_RULE_FORCE_SIZE                     = VG_MAX_ENUM
 } VGFillRule;
VGFontParamType
enum VGFontParamType
Enumerator
VG_FONT_NUM_GLYPHS
VG_FONT_PARAM_TYPE_FORCE_SIZE
Definition at line 463 of file openvg.h.
              {
   VG_FONT_NUM_GLYPHS                          = 0x2F00,
   VG_FONT_PARAM_TYPE_FORCE_SIZE               = VG_MAX_ENUM
 } VGFontParamType;
VGHardwareQueryResult
enum VGHardwareQueryResult
Enumerator
VG_HARDWARE_ACCELERATED
VG_HARDWARE_UNACCELERATED
VG_HARDWARE_QUERY_RESULT_FORCE_SIZE
Definition at line 476 of file openvg.h.
              {
   VG_HARDWARE_ACCELERATED                     = 0x2200,
   VG_HARDWARE_UNACCELERATED                   = 0x2201,
   VG_HARDWARE_QUERY_RESULT_FORCE_SIZE         = VG_MAX_ENUM
 } VGHardwareQueryResult;
VGHardwareQueryType
enum VGHardwareQueryType
Enumerator
VG_IMAGE_FORMAT_QUERY
VG_PATH_DATATYPE_QUERY
VG_HARDWARE_QUERY_TYPE_FORCE_SIZE
Definition at line 469 of file openvg.h.
              {
   VG_IMAGE_FORMAT_QUERY                       = 0x2100,
   VG_PATH_DATATYPE_QUERY                      = 0x2101,
   VG_HARDWARE_QUERY_TYPE_FORCE_SIZE           = VG_MAX_ENUM
 } VGHardwareQueryType;
VGImageChannel
enum VGImageChannel
Enumerator
VG_RED
VG_GREEN
VG_BLUE
VG_ALPHA
VG_IMAGE_CHANNEL_FORCE_SIZE
Definition at line 439 of file openvg.h.
              {
   VG_RED                                      = (1 << 3),
   VG_GREEN                                    = (1 << 2),
   VG_BLUE                                     = (1 << 1),
   VG_ALPHA                                    = (1 << 0),
   VG_IMAGE_CHANNEL_FORCE_SIZE                 = VG_MAX_ENUM
 } VGImageChannel;
VGImageFormat
enum VGImageFormat
Enumerator
VG_sRGBX_8888
VG_sRGBA_8888
VG_sRGBA_8888_PRE
VG_sRGB_565
VG_sRGBA_5551
VG_sRGBA_4444
VG_sL_8
VG_lRGBX_8888
VG_lRGBA_8888
VG_lRGBA_8888_PRE
VG_lL_8
VG_A_8
VG_BW_1
VG_A_1
VG_A_4
VG_sXRGB_8888
VG_sARGB_8888
VG_sARGB_8888_PRE
VG_sARGB_1555
VG_sARGB_4444
VG_lXRGB_8888
VG_lARGB_8888
VG_lARGB_8888_PRE
VG_sBGRX_8888
VG_sBGRA_8888
VG_sBGRA_8888_PRE
VG_sBGR_565
VG_sBGRA_5551
VG_sBGRA_4444
VG_lBGRX_8888
VG_lBGRA_8888
VG_lBGRA_8888_PRE
VG_sXBGR_8888
VG_sABGR_8888
VG_sABGR_8888_PRE
VG_sABGR_1555
VG_sABGR_4444
VG_lXBGR_8888
VG_lABGR_8888
VG_lABGR_8888_PRE
VG_IMAGE_FORMAT_FORCE_SIZE
Definition at line 363 of file openvg.h.
              {
   /* RGB{A,X} channel ordering */
   VG_sRGBX_8888                               =  0,
   VG_sRGBA_8888                               =  1,
   VG_sRGBA_8888_PRE                           =  2,
   VG_sRGB_565                                 =  3,
   VG_sRGBA_5551                               =  4,
   VG_sRGBA_4444                               =  5,
   VG_sL_8                                     =  6,
   VG_lRGBX_8888                               =  7,
   VG_lRGBA_8888                               =  8,
   VG_lRGBA_8888_PRE                           =  9,
   VG_lL_8                                     = 10,
   VG_A_8                                      = 11,
   VG_BW_1                                     = 12,
   VG_A_1                                      = 13,
   VG_A_4                                      = 14,
   /* {A,X}RGB channel ordering */
   VG_sXRGB_8888                               =  0 | (1 << 6),
   VG_sARGB_8888                               =  1 | (1 << 6),
   VG_sARGB_8888_PRE                           =  2 | (1 << 6),
   VG_sARGB_1555                               =  4 | (1 << 6),
   VG_sARGB_4444                               =  5 | (1 << 6),
   VG_lXRGB_8888                               =  7 | (1 << 6),
   VG_lARGB_8888                               =  8 | (1 << 6),
   VG_lARGB_8888_PRE                           =  9 | (1 << 6),
   /* BGR{A,X} channel ordering */
   VG_sBGRX_8888                               =  0 | (1 << 7),
   VG_sBGRA_8888                               =  1 | (1 << 7),
   VG_sBGRA_8888_PRE                           =  2 | (1 << 7),
   VG_sBGR_565                                 =  3 | (1 << 7),
   VG_sBGRA_5551                               =  4 | (1 << 7),
   VG_sBGRA_4444                               =  5 | (1 << 7),
   VG_lBGRX_8888                               =  7 | (1 << 7),
   VG_lBGRA_8888                               =  8 | (1 << 7),
   VG_lBGRA_8888_PRE                           =  9 | (1 << 7),
   /* {A,X}BGR channel ordering */
   VG_sXBGR_8888                               =  0 | (1 << 6) | (1 << 7),
   VG_sABGR_8888                               =  1 | (1 << 6) | (1 << 7),
   VG_sABGR_8888_PRE                           =  2 | (1 << 6) | (1 << 7),
   VG_sABGR_1555                               =  4 | (1 << 6) | (1 << 7),
   VG_sABGR_4444                               =  5 | (1 << 6) | (1 << 7),
   VG_lXBGR_8888                               =  7 | (1 << 6) | (1 << 7),
   VG_lABGR_8888                               =  8 | (1 << 6) | (1 << 7),
   VG_lABGR_8888_PRE                           =  9 | (1 << 6) | (1 << 7),
   VG_IMAGE_FORMAT_FORCE_SIZE                  = VG_MAX_ENUM
 } VGImageFormat;
VGImageMode
enum VGImageMode
Enumerator
VG_DRAW_IMAGE_NORMAL
VG_DRAW_IMAGE_MULTIPLY
VG_DRAW_IMAGE_STENCIL
VG_IMAGE_MODE_FORCE_SIZE
Definition at line 431 of file openvg.h.
              {
   VG_DRAW_IMAGE_NORMAL                        = 0x1F00,
   VG_DRAW_IMAGE_MULTIPLY                      = 0x1F01,
   VG_DRAW_IMAGE_STENCIL                       = 0x1F02,
   VG_IMAGE_MODE_FORCE_SIZE                    = VG_MAX_ENUM
 } VGImageMode;
VGImageParamType
enum VGImageParamType
Enumerator
VG_IMAGE_FORMAT
VG_IMAGE_WIDTH
VG_IMAGE_HEIGHT
VG_IMAGE_PARAM_TYPE_FORCE_SIZE
Definition at line 423 of file openvg.h.
              {
   VG_IMAGE_FORMAT                             = 0x1E00,
   VG_IMAGE_WIDTH                              = 0x1E01,
   VG_IMAGE_HEIGHT                             = 0x1E02,
   VG_IMAGE_PARAM_TYPE_FORCE_SIZE              = VG_MAX_ENUM
 } VGImageParamType;
VGImageQuality
enum VGImageQuality
Enumerator
VG_IMAGE_QUALITY_NONANTIALIASED
VG_IMAGE_QUALITY_FASTER
VG_IMAGE_QUALITY_BETTER
VG_IMAGE_QUALITY_FORCE_SIZE
Definition at line 415 of file openvg.h.
              {
   VG_IMAGE_QUALITY_NONANTIALIASED             = (1 << 0),
   VG_IMAGE_QUALITY_FASTER                     = (1 << 1),
   VG_IMAGE_QUALITY_BETTER                     = (1 << 2),
   VG_IMAGE_QUALITY_FORCE_SIZE                 = VG_MAX_ENUM
 } VGImageQuality;
VGJoinStyle
enum VGJoinStyle
Enumerator
VG_JOIN_MITER
VG_JOIN_ROUND
VG_JOIN_BEVEL
VG_JOIN_STYLE_FORCE_SIZE
Definition at line 295 of file openvg.h.
              {
   VG_JOIN_MITER                               = 0x1800,
   VG_JOIN_ROUND                               = 0x1801,
   VG_JOIN_BEVEL                               = 0x1802,
   VG_JOIN_STYLE_FORCE_SIZE                    = VG_MAX_ENUM
 } VGJoinStyle;
VGMaskOperation
enum VGMaskOperation
Enumerator
VG_CLEAR_MASK
VG_FILL_MASK
VG_SET_MASK
VG_UNION_MASK
VG_INTERSECT_MASK
VG_SUBTRACT_MASK
VG_MASK_OPERATION_FORCE_SIZE
Definition at line 180 of file openvg.h.
              {
   VG_CLEAR_MASK                               = 0x1500,
   VG_FILL_MASK                                = 0x1501,
   VG_SET_MASK                                 = 0x1502,
   VG_UNION_MASK                               = 0x1503,
   VG_INTERSECT_MASK                           = 0x1504,
   VG_SUBTRACT_MASK                            = 0x1505,
   VG_MASK_OPERATION_FORCE_SIZE                = VG_MAX_ENUM
 } VGMaskOperation;
VGMatrixMode
enum VGMatrixMode
Enumerator
VG_MATRIX_PATH_USER_TO_SURFACE
VG_MATRIX_IMAGE_USER_TO_SURFACE
VG_MATRIX_FILL_PAINT_TO_USER
VG_MATRIX_STROKE_PAINT_TO_USER
VG_MATRIX_GLYPH_USER_TO_SURFACE
VG_MATRIX_MODE_FORCE_SIZE
Definition at line 170 of file openvg.h.
              {
   VG_MATRIX_PATH_USER_TO_SURFACE              = 0x1400,
   VG_MATRIX_IMAGE_USER_TO_SURFACE             = 0x1401,
   VG_MATRIX_FILL_PAINT_TO_USER                = 0x1402,
   VG_MATRIX_STROKE_PAINT_TO_USER              = 0x1403,
   VG_MATRIX_GLYPH_USER_TO_SURFACE             = 0x1404,
   VG_MATRIX_MODE_FORCE_SIZE                   = VG_MAX_ENUM
 } VGMatrixMode;
VGPaintMode
enum VGPaintMode
Enumerator
VG_STROKE_PATH
VG_FILL_PATH
VG_PAINT_MODE_FORCE_SIZE
Definition at line 310 of file openvg.h.
              {
   VG_STROKE_PATH                              = (1 << 0),
   VG_FILL_PATH                                = (1 << 1),
   VG_PAINT_MODE_FORCE_SIZE                    = VG_MAX_ENUM
 } VGPaintMode;
VGPaintParamType
enum VGPaintParamType
Enumerator
VG_PAINT_TYPE
VG_PAINT_COLOR
VG_PAINT_COLOR_RAMP_SPREAD_MODE
VG_PAINT_COLOR_RAMP_PREMULTIPLIED
VG_PAINT_COLOR_RAMP_STOPS
VG_PAINT_LINEAR_GRADIENT
VG_PAINT_RADIAL_GRADIENT
VG_PAINT_PATTERN_TILING_MODE
VG_PAINT_PARAM_TYPE_FORCE_SIZE
Definition at line 317 of file openvg.h.
              {
   /* Color paint parameters */
   VG_PAINT_TYPE                               = 0x1A00,
   VG_PAINT_COLOR                              = 0x1A01,
   VG_PAINT_COLOR_RAMP_SPREAD_MODE             = 0x1A02,
   VG_PAINT_COLOR_RAMP_PREMULTIPLIED           = 0x1A07,
   VG_PAINT_COLOR_RAMP_STOPS                   = 0x1A03,
   /* Linear gradient paint parameters */
   VG_PAINT_LINEAR_GRADIENT                    = 0x1A04,
   /* Radial gradient paint parameters */
   VG_PAINT_RADIAL_GRADIENT                    = 0x1A05,
   /* Pattern paint parameters */
   VG_PAINT_PATTERN_TILING_MODE                = 0x1A06,
   VG_PAINT_PARAM_TYPE_FORCE_SIZE              = VG_MAX_ENUM
 } VGPaintParamType;
VGPaintType
enum VGPaintType
Enumerator
VG_PAINT_TYPE_COLOR
VG_PAINT_TYPE_LINEAR_GRADIENT
VG_PAINT_TYPE_RADIAL_GRADIENT
VG_PAINT_TYPE_PATTERN
VG_PAINT_TYPE_FORCE_SIZE
Definition at line 337 of file openvg.h.
              {
   VG_PAINT_TYPE_COLOR                         = 0x1B00,
   VG_PAINT_TYPE_LINEAR_GRADIENT               = 0x1B01,
   VG_PAINT_TYPE_RADIAL_GRADIENT               = 0x1B02,
   VG_PAINT_TYPE_PATTERN                       = 0x1B03,
   VG_PAINT_TYPE_FORCE_SIZE                    = VG_MAX_ENUM
 } VGPaintType;
VGParamType
enum VGParamType
Enumerator
VG_MATRIX_MODE
VG_FILL_RULE
VG_IMAGE_QUALITY
VG_RENDERING_QUALITY
VG_BLEND_MODE
VG_IMAGE_MODE
VG_SCISSOR_RECTS
VG_COLOR_TRANSFORM
VG_COLOR_TRANSFORM_VALUES
VG_STROKE_LINE_WIDTH
VG_STROKE_CAP_STYLE
VG_STROKE_JOIN_STYLE
VG_STROKE_MITER_LIMIT
VG_STROKE_DASH_PATTERN
VG_STROKE_DASH_PHASE
VG_STROKE_DASH_PHASE_RESET
VG_TILE_FILL_COLOR
VG_CLEAR_COLOR
VG_GLYPH_ORIGIN
VG_MASKING
VG_SCISSORING
VG_PIXEL_LAYOUT
VG_SCREEN_LAYOUT
VG_FILTER_FORMAT_LINEAR
VG_FILTER_FORMAT_PREMULTIPLIED
VG_FILTER_CHANNEL_MASK
VG_MAX_SCISSOR_RECTS
VG_MAX_DASH_COUNT
VG_MAX_KERNEL_SIZE
VG_MAX_SEPARABLE_KERNEL_SIZE
VG_MAX_COLOR_RAMP_STOPS
VG_MAX_IMAGE_WIDTH
VG_MAX_IMAGE_HEIGHT
VG_MAX_IMAGE_PIXELS
VG_MAX_IMAGE_BYTES
VG_MAX_FLOAT
VG_MAX_GAUSSIAN_STD_DEVIATION
VG_PARAM_TYPE_FORCE_SIZE
Definition at line 87 of file openvg.h.
              {
   /* Mode settings */
   VG_MATRIX_MODE                              = 0x1100,
   VG_FILL_RULE                                = 0x1101,
   VG_IMAGE_QUALITY                            = 0x1102,
   VG_RENDERING_QUALITY                        = 0x1103,
   VG_BLEND_MODE                               = 0x1104,
   VG_IMAGE_MODE                               = 0x1105,
   /* Scissoring rectangles */
   VG_SCISSOR_RECTS                            = 0x1106,
   /* Color Transformation */
   VG_COLOR_TRANSFORM                          = 0x1170,
   VG_COLOR_TRANSFORM_VALUES                   = 0x1171,
   /* Stroke parameters */
   VG_STROKE_LINE_WIDTH                        = 0x1110,
   VG_STROKE_CAP_STYLE                         = 0x1111,
   VG_STROKE_JOIN_STYLE                        = 0x1112,
   VG_STROKE_MITER_LIMIT                       = 0x1113,
   VG_STROKE_DASH_PATTERN                      = 0x1114,
   VG_STROKE_DASH_PHASE                        = 0x1115,
   VG_STROKE_DASH_PHASE_RESET                  = 0x1116,
   /* Edge fill color for VG_TILE_FILL tiling mode */
   VG_TILE_FILL_COLOR                          = 0x1120,
   /* Color for vgClear */
   VG_CLEAR_COLOR                              = 0x1121,
   /* Glyph origin */
   VG_GLYPH_ORIGIN                             = 0x1122,
   /* Enable/disable alpha masking and scissoring */
   VG_MASKING                                  = 0x1130,
   VG_SCISSORING                               = 0x1131,
   /* Pixel layout information */
   VG_PIXEL_LAYOUT                             = 0x1140,
   VG_SCREEN_LAYOUT                            = 0x1141,
   /* Source format selection for image filters */
   VG_FILTER_FORMAT_LINEAR                     = 0x1150,
   VG_FILTER_FORMAT_PREMULTIPLIED              = 0x1151,
   /* Destination write enable mask for image filters */
   VG_FILTER_CHANNEL_MASK                      = 0x1152,
   /* Implementation limits (read-only) */
   VG_MAX_SCISSOR_RECTS                        = 0x1160,
   VG_MAX_DASH_COUNT                           = 0x1161,
   VG_MAX_KERNEL_SIZE                          = 0x1162,
   VG_MAX_SEPARABLE_KERNEL_SIZE                = 0x1163,
   VG_MAX_COLOR_RAMP_STOPS                     = 0x1164,
   VG_MAX_IMAGE_WIDTH                          = 0x1165,
   VG_MAX_IMAGE_HEIGHT                         = 0x1166,
   VG_MAX_IMAGE_PIXELS                         = 0x1167,
   VG_MAX_IMAGE_BYTES                          = 0x1168,
   VG_MAX_FLOAT                                = 0x1169,
   VG_MAX_GAUSSIAN_STD_DEVIATION               = 0x116A,
   VG_PARAM_TYPE_FORCE_SIZE                    = VG_MAX_ENUM
 } VGParamType;
VGPathAbsRel
enum VGPathAbsRel
Enumerator
VG_ABSOLUTE
VG_RELATIVE
VG_PATH_ABS_REL_FORCE_SIZE
Definition at line 202 of file openvg.h.
              {
   VG_ABSOLUTE                                 = 0,
   VG_RELATIVE                                 = 1,
   VG_PATH_ABS_REL_FORCE_SIZE                  = VG_MAX_ENUM
 } VGPathAbsRel;
VGPathCapabilities
enum VGPathCapabilities
Enumerator
VG_PATH_CAPABILITY_APPEND_FROM
VG_PATH_CAPABILITY_APPEND_TO
VG_PATH_CAPABILITY_MODIFY
VG_PATH_CAPABILITY_TRANSFORM_FROM
VG_PATH_CAPABILITY_TRANSFORM_TO
VG_PATH_CAPABILITY_INTERPOLATE_FROM
VG_PATH_CAPABILITY_INTERPOLATE_TO
VG_PATH_CAPABILITY_PATH_LENGTH
VG_PATH_CAPABILITY_POINT_ALONG_PATH
VG_PATH_CAPABILITY_TANGENT_ALONG_PATH
VG_PATH_CAPABILITY_PATH_BOUNDS
VG_PATH_CAPABILITY_PATH_TRANSFORMED_BOUNDS
VG_PATH_CAPABILITY_ALL
VG_PATH_CAPABILITIES_FORCE_SIZE
Definition at line 258 of file openvg.h.
              {
   VG_PATH_CAPABILITY_APPEND_FROM              = (1 <<  0),
   VG_PATH_CAPABILITY_APPEND_TO                = (1 <<  1),
   VG_PATH_CAPABILITY_MODIFY                   = (1 <<  2),
   VG_PATH_CAPABILITY_TRANSFORM_FROM           = (1 <<  3),
   VG_PATH_CAPABILITY_TRANSFORM_TO             = (1 <<  4),
   VG_PATH_CAPABILITY_INTERPOLATE_FROM         = (1 <<  5),
   VG_PATH_CAPABILITY_INTERPOLATE_TO           = (1 <<  6),
   VG_PATH_CAPABILITY_PATH_LENGTH              = (1 <<  7),
   VG_PATH_CAPABILITY_POINT_ALONG_PATH         = (1 <<  8),
   VG_PATH_CAPABILITY_TANGENT_ALONG_PATH       = (1 <<  9),
   VG_PATH_CAPABILITY_PATH_BOUNDS              = (1 << 10),
   VG_PATH_CAPABILITY_PATH_TRANSFORMED_BOUNDS  = (1 << 11),
   VG_PATH_CAPABILITY_ALL                      = (1 << 12) - 1,
   VG_PATH_CAPABILITIES_FORCE_SIZE             = VG_MAX_ENUM
 } VGPathCapabilities;
VGPathCommand
enum VGPathCommand
Enumerator
VG_MOVE_TO_ABS
VG_MOVE_TO_REL
VG_LINE_TO_ABS
VG_LINE_TO_REL
VG_HLINE_TO_ABS
VG_HLINE_TO_REL
VG_VLINE_TO_ABS
VG_VLINE_TO_REL
VG_QUAD_TO_ABS
VG_QUAD_TO_REL
VG_CUBIC_TO_ABS
VG_CUBIC_TO_REL
VG_SQUAD_TO_ABS
VG_SQUAD_TO_REL
VG_SCUBIC_TO_ABS
VG_SCUBIC_TO_REL
VG_SCCWARC_TO_ABS
VG_SCCWARC_TO_REL
VG_SCWARC_TO_ABS
VG_SCWARC_TO_REL
VG_LCCWARC_TO_ABS
VG_LCCWARC_TO_REL
VG_LCWARC_TO_ABS
VG_LCWARC_TO_REL
VG_PATH_COMMAND_FORCE_SIZE
Definition at line 229 of file openvg.h.
              {
   VG_MOVE_TO_ABS                              = VG_MOVE_TO    | VG_ABSOLUTE,
   VG_MOVE_TO_REL                              = VG_MOVE_TO    | VG_RELATIVE,
   VG_LINE_TO_ABS                              = VG_LINE_TO    | VG_ABSOLUTE,
   VG_LINE_TO_REL                              = VG_LINE_TO    | VG_RELATIVE,
   VG_HLINE_TO_ABS                             = VG_HLINE_TO   | VG_ABSOLUTE,
   VG_HLINE_TO_REL                             = VG_HLINE_TO   | VG_RELATIVE,
   VG_VLINE_TO_ABS                             = VG_VLINE_TO   | VG_ABSOLUTE,
   VG_VLINE_TO_REL                             = VG_VLINE_TO   | VG_RELATIVE,
   VG_QUAD_TO_ABS                              = VG_QUAD_TO    | VG_ABSOLUTE,
   VG_QUAD_TO_REL                              = VG_QUAD_TO    | VG_RELATIVE,
   VG_CUBIC_TO_ABS                             = VG_CUBIC_TO   | VG_ABSOLUTE,
   VG_CUBIC_TO_REL                             = VG_CUBIC_TO   | VG_RELATIVE,
   VG_SQUAD_TO_ABS                             = VG_SQUAD_TO   | VG_ABSOLUTE,
   VG_SQUAD_TO_REL                             = VG_SQUAD_TO   | VG_RELATIVE,
   VG_SCUBIC_TO_ABS                            = VG_SCUBIC_TO  | VG_ABSOLUTE,
   VG_SCUBIC_TO_REL                            = VG_SCUBIC_TO  | VG_RELATIVE,
   VG_SCCWARC_TO_ABS                           = VG_SCCWARC_TO | VG_ABSOLUTE,
   VG_SCCWARC_TO_REL                           = VG_SCCWARC_TO | VG_RELATIVE,
   VG_SCWARC_TO_ABS                            = VG_SCWARC_TO  | VG_ABSOLUTE,
   VG_SCWARC_TO_REL                            = VG_SCWARC_TO  | VG_RELATIVE,
   VG_LCCWARC_TO_ABS                           = VG_LCCWARC_TO | VG_ABSOLUTE,
   VG_LCCWARC_TO_REL                           = VG_LCCWARC_TO | VG_RELATIVE,
   VG_LCWARC_TO_ABS                            = VG_LCWARC_TO  | VG_ABSOLUTE,
   VG_LCWARC_TO_REL                            = VG_LCWARC_TO  | VG_RELATIVE,
   VG_PATH_COMMAND_FORCE_SIZE                  = VG_MAX_ENUM
 } VGPathCommand;
VGPathDatatype
enum VGPathDatatype
Enumerator
VG_PATH_DATATYPE_S_8
VG_PATH_DATATYPE_S_16
VG_PATH_DATATYPE_S_32
VG_PATH_DATATYPE_F
VG_PATH_DATATYPE_FORCE_SIZE
Definition at line 193 of file openvg.h.
              {
   VG_PATH_DATATYPE_S_8                        =  0,
   VG_PATH_DATATYPE_S_16                       =  1,
   VG_PATH_DATATYPE_S_32                       =  2,
   VG_PATH_DATATYPE_F                          =  3,
   VG_PATH_DATATYPE_FORCE_SIZE                 = VG_MAX_ENUM
 } VGPathDatatype;
VGPathParamType
enum VGPathParamType
Enumerator
VG_PATH_FORMAT
VG_PATH_DATATYPE
VG_PATH_SCALE
VG_PATH_BIAS
VG_PATH_NUM_SEGMENTS
VG_PATH_NUM_COORDS
VG_PATH_PARAM_TYPE_FORCE_SIZE
Definition at line 276 of file openvg.h.
              {
   VG_PATH_FORMAT                              = 0x1600,
   VG_PATH_DATATYPE                            = 0x1601,
   VG_PATH_SCALE                               = 0x1602,
   VG_PATH_BIAS                                = 0x1603,
   VG_PATH_NUM_SEGMENTS                        = 0x1604,
   VG_PATH_NUM_COORDS                          = 0x1605,
   VG_PATH_PARAM_TYPE_FORCE_SIZE               = VG_MAX_ENUM
 } VGPathParamType;
VGPathSegment
enum VGPathSegment
Enumerator
VG_CLOSE_PATH
VG_MOVE_TO
VG_LINE_TO
VG_HLINE_TO
VG_VLINE_TO
VG_QUAD_TO
VG_CUBIC_TO
VG_SQUAD_TO
VG_SCUBIC_TO
VG_SCCWARC_TO
VG_SCWARC_TO
VG_LCCWARC_TO
VG_LCWARC_TO
VG_SEGMENT_MASK
VG_PATH_SEGMENT_FORCE_SIZE
Definition at line 209 of file openvg.h.
              {
   VG_CLOSE_PATH                               = ( 0 << 1),
   VG_MOVE_TO                                  = ( 1 << 1),
   VG_LINE_TO                                  = ( 2 << 1),
   VG_HLINE_TO                                 = ( 3 << 1),
   VG_VLINE_TO                                 = ( 4 << 1),
   VG_QUAD_TO                                  = ( 5 << 1),
   VG_CUBIC_TO                                 = ( 6 << 1),
   VG_SQUAD_TO                                 = ( 7 << 1),
   VG_SCUBIC_TO                                = ( 8 << 1),
   VG_SCCWARC_TO                               = ( 9 << 1),
   VG_SCWARC_TO                                = (10 << 1),
   VG_LCCWARC_TO                               = (11 << 1),
   VG_LCWARC_TO                                = (12 << 1),
   VG_SEGMENT_MASK                             = 0xf << 1,
   VG_PATH_SEGMENT_FORCE_SIZE                  = VG_MAX_ENUM
 } VGPathSegment;
VGPixelLayout
enum VGPixelLayout
Enumerator
VG_PIXEL_LAYOUT_UNKNOWN
VG_PIXEL_LAYOUT_RGB_VERTICAL
VG_PIXEL_LAYOUT_BGR_VERTICAL
VG_PIXEL_LAYOUT_RGB_HORIZONTAL
VG_PIXEL_LAYOUT_BGR_HORIZONTAL
VG_PIXEL_LAYOUT_FORCE_SIZE
Definition at line 160 of file openvg.h.
              {
   VG_PIXEL_LAYOUT_UNKNOWN                     = 0x1300,
   VG_PIXEL_LAYOUT_RGB_VERTICAL                = 0x1301,
   VG_PIXEL_LAYOUT_BGR_VERTICAL                = 0x1302,
   VG_PIXEL_LAYOUT_RGB_HORIZONTAL              = 0x1303,
   VG_PIXEL_LAYOUT_BGR_HORIZONTAL              = 0x1304,
   VG_PIXEL_LAYOUT_FORCE_SIZE                  = VG_MAX_ENUM
 } VGPixelLayout;
VGRenderingQuality
enum VGRenderingQuality
Enumerator
VG_RENDERING_QUALITY_NONANTIALIASED
VG_RENDERING_QUALITY_FASTER
VG_RENDERING_QUALITY_BETTER
VG_RENDERING_QUALITY_FORCE_SIZE
Definition at line 152 of file openvg.h.
              {
   VG_RENDERING_QUALITY_NONANTIALIASED         = 0x1200,
   VG_RENDERING_QUALITY_FASTER                 = 0x1201,
   VG_RENDERING_QUALITY_BETTER                 = 0x1202, /* Default */
   VG_RENDERING_QUALITY_FORCE_SIZE             = VG_MAX_ENUM
 } VGRenderingQuality;
VGStringID
enum VGStringID
Enumerator
VG_VENDOR
VG_RENDERER
VG_VERSION
VG_EXTENSIONS
VG_STRING_ID_FORCE_SIZE
Definition at line 483 of file openvg.h.
              {
   VG_VENDOR                                   = 0x2300,
   VG_RENDERER                                 = 0x2301,
   VG_VERSION                                  = 0x2302,
   VG_EXTENSIONS                               = 0x2303,
   VG_STRING_ID_FORCE_SIZE                     = VG_MAX_ENUM
 } VGStringID;
VGTilingMode
enum VGTilingMode
Enumerator
VG_TILE_FILL
VG_TILE_PAD
VG_TILE_REPEAT
VG_TILE_REFLECT
VG_TILING_MODE_FORCE_SIZE
Definition at line 354 of file openvg.h.
              {
   VG_TILE_FILL                                = 0x1D00,
   VG_TILE_PAD                                 = 0x1D01,
   VG_TILE_REPEAT                              = 0x1D02,
   VG_TILE_REFLECT                             = 0x1D03,
   VG_TILING_MODE_FORCE_SIZE                   = VG_MAX_ENUM
 } VGTilingMode;
Function Documentation
vgAppendPath()
VG_API_CALL void VG_API_ENTRY vgAppendPath (VGPath dstPath, VGPath srcPath)
Definition at line 2935 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_PATH_T *dst;
    VG_CLIENT_PATH_T *src;
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    platform_mutex_acquire(&state->shared_state->mutex);
    dst = (VG_CLIENT_PATH_T *)lookup_object(state, dst_vg_handle, VG_CLIENT_OBJECT_TYPE_PATH);
    src = (VG_CLIENT_PATH_T *)lookup_object(state, src_vg_handle, VG_CLIENT_OBJECT_TYPE_PATH);
    if (dst && src &&
       (dst->caps & VG_PATH_CAPABILITY_APPEND_TO) && (src->caps & VG_PATH_CAPABILITY_APPEND_FROM) &&
       need_path_segments(dst->caps)) {
       VGuint segments_count = src->segments.size;
       if (!khrn_vector_extend(&dst->segments, segments_count)) {
          set_error(VG_OUT_OF_MEMORY_ERROR);
          platform_mutex_release(&state->shared_state->mutex);
          return;
       }
       memcpy((VGubyte *)dst->segments.data + (dst->segments.size - segments_count), src->segments.data, segments_count);
    }
    platform_mutex_release(&state->shared_state->mutex);
    RPC_CALL2(vgAppendPath_impl,
              thread,
              VGAPPENDPATH_ID,
              RPC_HANDLE(dst_vg_handle),
              RPC_HANDLE(src_vg_handle));
 }
vgAppendPathData()
VG_API_CALL void VG_API_ENTRY vgAppendPathData (VGPath dstPath, VGint numSegments, const VGubyte * pathSegments, const void * pathData)
Definition at line 2971 of file vg_client.c.
Referenced by PS_construct().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_PATH_T *path;
    VGPathDatatype datatype;
    VGuint datatype_size;
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    platform_mutex_acquire(&state->shared_state->mutex);
    path = (VG_CLIENT_PATH_T *)lookup_object(state, vg_handle, VG_CLIENT_OBJECT_TYPE_PATH);
    if (!path) {
       set_error(VG_BAD_HANDLE_ERROR);
       platform_mutex_release(&state->shared_state->mutex);
       return;
    }
    datatype = path->datatype;
    if ((segments_count <= 0) || !segments ||
       contains_illegal_segment(segments, segments_count) ||
       !coords || !is_aligned_path_datatype(coords, datatype)) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       platform_mutex_release(&state->shared_state->mutex);
       return;
    }
    if (!(path->caps & VG_PATH_CAPABILITY_APPEND_TO)) {
       set_error(VG_PATH_CAPABILITY_ERROR);
       platform_mutex_release(&state->shared_state->mutex);
       return;
    }
    if (need_path_segments(path->caps)) {
       if (!khrn_vector_extend(&path->segments, segments_count)) {
          set_error(VG_OUT_OF_MEMORY_ERROR);
          platform_mutex_release(&state->shared_state->mutex);
          return;
       }
       memcpy((VGubyte *)path->segments.data + (path->segments.size - segments_count), segments, segments_count);
    }
    platform_mutex_release(&state->shared_state->mutex);
    datatype_size = get_path_datatype_size(datatype);
    #ifdef RPC_DIRECT
       {
          VGuint coords_count = 0;
          VGuint i;
          for (i = 0; i != segments_count; ++i) {
             coords_count += get_segment_coords_count(segments[i] & ~VG_RELATIVE);
          }
          RPC_CALL6(vgAppendPathData_impl, thread, no_id,
             vg_handle,
             datatype,
             segments_count, segments,
             coords_count * datatype_size, coords);
       }
    #else
       /*
          split into multiple calls if necessary to avoid overflowing control buffer
       */
       while (segments_count != 0) {
          #define MESSAGE_SIZE 20
          VGuint size_max = rpc_send_ctrl_longest(thread, MESSAGE_SIZE + rpc_pad_ctrl(1) + rpc_pad_ctrl(6 * datatype_size)) - MESSAGE_SIZE; /* fit at least one segment */
          VGint chunk_segments_count = 0;
          VGuint chunk_coords_size = 0;
          for (; chunk_segments_count != segments_count; ++chunk_segments_count) {
             VGuint segment_coords_size = get_segment_coords_count(segments[chunk_segments_count] & ~VG_RELATIVE) * datatype_size;
             if ((rpc_pad_ctrl(chunk_segments_count + 1) +
                rpc_pad_ctrl(chunk_coords_size + segment_coords_size)) > size_max) {
                /*
                   can't fit this segment in
                */
                break;
             }
             chunk_coords_size += segment_coords_size;
          }
          {
             uint32_t message[] = {
                VGAPPENDPATHDATA_ID,
                RPC_HANDLE(vg_handle),
                RPC_ENUM(datatype),
                RPC_INT(chunk_segments_count),
                RPC_UINT(chunk_coords_size) };
             vcos_static_assert(sizeof(message) == MESSAGE_SIZE);
             #undef MESSAGE_SIZE
             CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
             rpc_send_ctrl_begin(thread, sizeof(message) + rpc_pad_ctrl(chunk_segments_count) + rpc_pad_ctrl(chunk_coords_size));
             rpc_send_ctrl_write(thread, message, sizeof(message));
             rpc_send_ctrl_write(thread, (uint32_t *)segments, chunk_segments_count);
             rpc_send_ctrl_write(thread, (uint32_t *)coords, chunk_coords_size);
             rpc_send_ctrl_end(thread);
          }
          segments_count -= chunk_segments_count;
          segments += chunk_segments_count;
          coords = (const uint8_t *)coords + chunk_coords_size;
       }
    #endif
 }
vgChildImage()
VG_API_CALL VGImage VG_API_ENTRY vgChildImage (VGImage parent, VGint x, VGint y, VGint width, VGint height)
Definition at line 4012 of file vg_client.c.
Referenced by graphics_bitblt().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_IMAGE_T *parent;
    VGImageFormat format;
    VGint parent_width;
    VGint parent_height;
 #if EGL_BRCM_global_image && EGL_KHR_image
    VGuint parent_global_image_id_0, parent_global_image_id_1;
 #endif
    VGHandle vg_handle;
    VG_CLIENT_IMAGE_T *image;
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return VG_INVALID_HANDLE;
    }
    platform_mutex_acquire(&state->shared_state->mutex);
    parent = (VG_CLIENT_IMAGE_T *)lookup_object(state, parent_vg_handle, VG_CLIENT_OBJECT_TYPE_IMAGE);
    if (!parent) {
       set_error(VG_BAD_HANDLE_ERROR);
       platform_mutex_release(&state->shared_state->mutex);
       return VG_INVALID_HANDLE;
    }
    format = parent->format;
    parent_width = parent->width;
    parent_height = parent->height;
 #if EGL_BRCM_global_image && EGL_KHR_image
    parent_global_image_id_0 = parent->global_image_id[0];
    parent_global_image_id_1 = parent->global_image_id[1];
 #endif
    platform_mutex_release(&state->shared_state->mutex); /* mustn't hold this mutex when calling get_stem, so release now and acquire again later */
    if ((x < 0) || (y < 0) || (width <= 0) || (height <= 0) ||
       /* x + width / y + height will fit in VGuint (may not fit in VGint) */
       (((VGuint)(x + width)) > (VGuint)parent_width) ||
       (((VGuint)(y + height)) > (VGuint)parent_height)) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return VG_INVALID_HANDLE;
    }
    vg_handle = get_stem(state);
    if (vg_handle == VG_INVALID_HANDLE) {
       set_error(VG_OUT_OF_MEMORY_ERROR);
       return VG_INVALID_HANDLE;
    }
    image = image_alloc(format, width, height
 #if EGL_BRCM_global_image && EGL_KHR_image
       , parent_global_image_id_0, parent_global_image_id_1
 #endif
       );
    if (!image) {
       set_error(VG_OUT_OF_MEMORY_ERROR);
       destroy_stem(vg_handle);
       return VG_INVALID_HANDLE;
    }
    platform_mutex_acquire(&state->shared_state->mutex);
    if (!insert_object(state, vg_handle, image)) {
       set_error(VG_OUT_OF_MEMORY_ERROR);
       platform_mutex_release(&state->shared_state->mutex);
       image_free(image);
       destroy_stem(vg_handle);
       return VG_INVALID_HANDLE;
    }
    platform_mutex_release(&state->shared_state->mutex);
    RPC_CALL8(vgChildImage_impl,
              thread,
              VGCHILDIMAGE_ID,
              RPC_HANDLE(vg_handle),
              RPC_HANDLE(parent_vg_handle),
              RPC_INT(parent_width), RPC_INT(parent_height),
              RPC_INT(x), RPC_INT(y),
              RPC_INT(width), RPC_INT(height));
    return vg_handle;
 }
vgClear()
VG_API_CALL void VG_API_ENTRY vgClear (VGint x, VGint y, VGint width, VGint height)
Definition at line 2739 of file vg_client.c.
Referenced by gx_priv_resource_fill(), and render().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    //TODO: pixmap behaviour can be better optimized to handle clears
    if (state->render_callback)
       state->render_callback();
    RPC_CALL4(vgClear_impl,
              thread,
              VGCLEAR_ID,
              RPC_INT(x),
              RPC_INT(y),
              RPC_INT(width),
              RPC_INT(height));
 }
vgClearGlyph()
VG_API_CALL void VG_API_ENTRY vgClearGlyph (VGFont font, VGuint glyphIndex)
Definition at line 4583 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
 #if EGL_BRCM_global_image && EGL_KHR_image
    VG_CLIENT_FONT_T *font;
 #endif
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
 #if EGL_BRCM_global_image && EGL_KHR_image
    platform_mutex_acquire(&state->shared_state->mutex);
    font = (VG_CLIENT_FONT_T *)lookup_object(state, vg_handle, VG_CLIENT_OBJECT_TYPE_FONT);
    if (font) {
       khrn_global_image_map_delete(&font->glyph_global_images, glyph_id);
    }
    platform_mutex_release(&state->shared_state->mutex);
 #endif
    RPC_CALL2(vgClearGlyph_impl,
              thread,
              VGCLEARGLYPH_ID,
              RPC_HANDLE(vg_handle),
              RPC_UINT(glyph_id));
 }
vgClearImage()
VG_API_CALL void VG_API_ENTRY vgClearImage (VGImage image, VGint x, VGint y, VGint width, VGint height)
Definition at line 3763 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (!VG_GET_CLIENT_STATE(thread)) {
       return;
    }
    RPC_CALL5(vgClearImage_impl,
              thread,
              VGCLEARIMAGE_ID,
              RPC_HANDLE(vg_handle),
              RPC_INT(x), RPC_INT(y),
              RPC_INT(width), RPC_INT(height));
 }
vgClearPath()
VG_API_CALL void VG_API_ENTRY vgClearPath (VGPath path, VGbitfield capabilities)
Definition at line 2834 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_STATE_T *state;
    VG_CLIENT_PATH_T *path;
    caps &= VG_PATH_CAPABILITY_ALL;
    state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    platform_mutex_acquire(&state->shared_state->mutex);
    path = (VG_CLIENT_PATH_T *)lookup_object(state, vg_handle, VG_CLIENT_OBJECT_TYPE_PATH);
    if (path) {
       if (need_path_segments(path->caps) && need_path_segments(caps)) {
          khrn_vector_clear(&path->segments);
       }
       path_update_caps(path, caps);
    }
    platform_mutex_release(&state->shared_state->mutex);
    RPC_CALL2(vgClearPath_impl,
              thread,
              VGCLEARPATH_ID,
              RPC_HANDLE(vg_handle),
              RPC_BITFIELD(caps));
 }
vgColorMatrix()
VG_API_CALL void VG_API_ENTRY vgColorMatrix (VGImage dst, VGImage src, const VGfloat * matrix)
Definition at line 4746 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (!VG_GET_CLIENT_STATE(thread)) {
       return;
    }
    if (!matrix || !is_aligned_float(matrix)) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return;
    }
    RPC_CALL3_IN_CTRL(vgColorMatrix_impl,
                      thread,
                      VGCOLORMATRIX_ID,
                      RPC_HANDLE(dst_vg_handle),
                      RPC_HANDLE(src_vg_handle),
                      matrix,
                      20 * sizeof(VGfloat));
 }
vgConvolve()
VG_API_CALL void VG_API_ENTRY vgConvolve (VGImage dst, VGImage src, VGint kernelWidth, VGint kernelHeight, VGint shiftX, VGint shiftY, const VGshort * kernel, VGfloat scale, VGfloat bias, VGTilingMode tilingMode)
Definition at line 4769 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    scale = clean_float(scale);
    bias = clean_float(bias);
    if (!VG_GET_CLIENT_STATE(thread)) {
       return;
    }
    if ((kernel_width <= 0) || (kernel_height <= 0) ||
       (kernel_width > VG_CONFIG_MAX_KERNEL_SIZE) || (kernel_height > VG_CONFIG_MAX_KERNEL_SIZE) ||
       !kernel || !is_aligned_short(kernel)) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return;
    }
    RPC_CALL10_IN_CTRL(vgConvolve_impl,
                       thread,
                       VGCONVOLVE_ID,
                       RPC_HANDLE(dst_vg_handle), RPC_HANDLE(src_vg_handle),
                       RPC_INT(kernel_width), RPC_INT(kernel_height),
                       RPC_INT(shift_x), RPC_INT(shift_y),
                       RPC_FLOAT(scale), RPC_FLOAT(bias),
                       RPC_ENUM(tiling_mode),
                       kernel,
                       kernel_width * kernel_height * sizeof(VGshort));
 }
vgCopyImage()
VG_API_CALL void VG_API_ENTRY vgCopyImage (VGImage dst, VGint dx, VGint dy, VGImage src, VGint sx, VGint sy, VGint width, VGint height, VGboolean dither)
Definition at line 4113 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (!VG_GET_CLIENT_STATE(thread)) {
       return;
    }
    RPC_CALL9(vgCopyImage_impl,
              thread,
              VGCOPYIMAGE_ID,
              RPC_HANDLE(dst_vg_handle), RPC_INT(dst_x), RPC_INT(dst_y),
              RPC_HANDLE(src_vg_handle), RPC_INT(src_x), RPC_INT(src_y),
              RPC_INT(width), RPC_INT(height),
              RPC_BOOLEAN(clean_boolean(dither)));
 }
vgCopyMask()
VG_API_CALL void VG_API_ENTRY vgCopyMask (VGMaskLayer maskLayer, VGint dx, VGint dy, VGint sx, VGint sy, VGint width, VGint height)
Definition at line 2719 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (!VG_GET_CLIENT_STATE(thread)) {
       return;
    }
    RPC_CALL7(vgCopyMask_impl,
              thread,
              VGCOPYMASK_ID,
              RPC_HANDLE(dst_vg_handle),
              RPC_INT(dst_x), RPC_INT(dst_y),
              RPC_INT(src_x), RPC_INT(src_y),
              RPC_INT(width), RPC_INT(height));
 }
vgCopyPixels()
VG_API_CALL void VG_API_ENTRY vgCopyPixels (VGint dx, VGint dy, VGint sx, VGint sy, VGint width, VGint height)
Definition at line 4392 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    if (state->render_callback)
       state->render_callback();
    RPC_CALL6(vgCopyPixels_impl,
              thread,
              VGCOPYPIXELS_ID,
              RPC_INT(dst_x), RPC_INT(dst_y),
              RPC_INT(src_x), RPC_INT(src_y),
              RPC_INT(width), RPC_INT(height));
 }
vgCreateFont()
VG_API_CALL VGFont VG_API_ENTRY vgCreateFont (VGint glyphCapacityHint)
Definition at line 4418 of file vg_client.c.
Referenced by vgft_font_init().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VGHandle vg_handle;
    VG_CLIENT_FONT_T *font;
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return VG_INVALID_HANDLE;
    }
    if (glyphs_capacity < 0) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return VG_INVALID_HANDLE;
    }
    vg_handle = get_stem(state);
    if (vg_handle == VG_INVALID_HANDLE) {
       set_error(VG_OUT_OF_MEMORY_ERROR);
       return VG_INVALID_HANDLE;
    }
    font = font_alloc();
    if (!font) {
       set_error(VG_OUT_OF_MEMORY_ERROR);
       destroy_stem(vg_handle);
       return VG_INVALID_HANDLE;
    }
    platform_mutex_acquire(&state->shared_state->mutex);
    if (!insert_object(state, vg_handle, font)) {
       set_error(VG_OUT_OF_MEMORY_ERROR);
       platform_mutex_release(&state->shared_state->mutex);
       font_free(font);
       destroy_stem(vg_handle);
       return VG_INVALID_HANDLE;
    }
    platform_mutex_release(&state->shared_state->mutex);
    RPC_CALL2(vgCreateFont_impl,
              thread,
              VGCREATEFONT_ID,
              RPC_HANDLE(vg_handle),
              RPC_INT(glyphs_capacity));
    return vg_handle;
 }
vgCreateImage()
VG_API_CALL VGImage VG_API_ENTRY vgCreateImage (VGImageFormat format, VGint width, VGint height, VGbitfield allowedQuality)
Definition at line 3680 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VGHandle vg_handle;
    VG_CLIENT_IMAGE_T *image;
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return VG_INVALID_HANDLE;
    }
    if (!is_allowed_quality(allowed_quality) ||
       (width <= 0) || (height <= 0) ||
       (width > VG_CONFIG_MAX_IMAGE_WIDTH) || (height > VG_CONFIG_MAX_IMAGE_HEIGHT) ||
       ((width * height) > VG_CONFIG_MAX_IMAGE_PIXELS)) { /* todo: VG_CONFIG_MAX_IMAGE_BYTES */
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return VG_INVALID_HANDLE;
    }
    if (!is_image_format(format)) {
       set_error(VG_UNSUPPORTED_IMAGE_FORMAT_ERROR);
       return VG_INVALID_HANDLE;
    }
    vg_handle = get_stem(state);
    if (vg_handle == VG_INVALID_HANDLE) {
       set_error(VG_OUT_OF_MEMORY_ERROR);
       return VG_INVALID_HANDLE;
    }
    image = image_alloc(format, width, height
 #if EGL_BRCM_global_image && EGL_KHR_image
       , 0, 0
 #endif
       );
    if (!image) {
       set_error(VG_OUT_OF_MEMORY_ERROR);
       destroy_stem(vg_handle);
       return VG_INVALID_HANDLE;
    }
    platform_mutex_acquire(&state->shared_state->mutex);
    if (!insert_object(state, vg_handle, image)) {
       set_error(VG_OUT_OF_MEMORY_ERROR);
       platform_mutex_release(&state->shared_state->mutex);
       image_free(image);
       destroy_stem(vg_handle);
       return VG_INVALID_HANDLE;
    }
    platform_mutex_release(&state->shared_state->mutex);
    RPC_CALL5(vgCreateImage_impl,
              thread,
              VGCREATEIMAGE_ID,
              RPC_HANDLE(vg_handle),
              RPC_ENUM(format),
              RPC_INT(width), RPC_INT(height),
              RPC_BITFIELD(allowed_quality));
    return vg_handle;
 }
vgCreateMaskLayer()
VG_API_CALL VGMaskLayer VG_API_ENTRY vgCreateMaskLayer (VGint width, VGint height)
Definition at line 2621 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VGHandle vg_handle;
    VG_CLIENT_MASK_LAYER_T *mask_layer;
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return VG_INVALID_HANDLE;
    }
    if ((width <= 0) || (height <= 0) ||
       (width > VG_CONFIG_MAX_IMAGE_WIDTH) || (height > VG_CONFIG_MAX_IMAGE_HEIGHT) ||
       ((width * height) > VG_CONFIG_MAX_IMAGE_PIXELS)) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return VG_INVALID_HANDLE;
    }
    if (egl_config_get_mask_format(egl_config_to_id(
       CLIENT_GET_THREAD_STATE()->openvg.draw->config)) == IMAGE_FORMAT_INVALID) {
       return VG_INVALID_HANDLE;
    }
    vg_handle = get_stem(state);
    if (vg_handle == VG_INVALID_HANDLE) {
       set_error(VG_OUT_OF_MEMORY_ERROR);
       return VG_INVALID_HANDLE;
    }
    mask_layer = mask_layer_alloc(width, height);
    if (!mask_layer) {
       set_error(VG_OUT_OF_MEMORY_ERROR);
       destroy_stem(vg_handle);
       return VG_INVALID_HANDLE;
    }
    platform_mutex_acquire(&state->shared_state->mutex);
    if (!insert_object(state, vg_handle, mask_layer)) {
       set_error(VG_OUT_OF_MEMORY_ERROR);
       platform_mutex_release(&state->shared_state->mutex);
       mask_layer_free(mask_layer);
       destroy_stem(vg_handle);
       return VG_INVALID_HANDLE;
    }
    platform_mutex_release(&state->shared_state->mutex);
    RPC_CALL3(vgCreateMaskLayer_impl,
              thread,
              VGCREATEMASKLAYER_ID,
              RPC_HANDLE(vg_handle),
              RPC_INT(width),
              RPC_INT(height));
    return vg_handle;
 }
vgCreatePaint()
VG_API_CALL VGPaint VG_API_ENTRY vgCreatePaint (void)
Definition at line 3463 of file vg_client.c.
Referenced by graphics_bitblt(), gx_create_gradient(), and PS_construct().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VGHandle vg_handle;
    VG_CLIENT_PAINT_T *paint;
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return VG_INVALID_HANDLE;
    }
    vg_handle = get_stem(state);
    if (vg_handle == VG_INVALID_HANDLE) {
       set_error(VG_OUT_OF_MEMORY_ERROR);
       return VG_INVALID_HANDLE;
    }
    paint = paint_alloc();
    if (!paint) {
       set_error(VG_OUT_OF_MEMORY_ERROR);
       destroy_stem(vg_handle);
       return VG_INVALID_HANDLE;
    }
    platform_mutex_acquire(&state->shared_state->mutex);
    if (!insert_object(state, vg_handle, paint)) {
       set_error(VG_OUT_OF_MEMORY_ERROR);
       platform_mutex_release(&state->shared_state->mutex);
       paint_free(paint);
       destroy_stem(vg_handle);
       return VG_INVALID_HANDLE;
    }
    platform_mutex_release(&state->shared_state->mutex);
    RPC_CALL1(vgCreatePaint_impl,
              thread,
              VGCREATEPAINT_ID,
              RPC_HANDLE(vg_handle));
    return vg_handle;
 }
vgCreatePath()
VG_API_CALL VGPath VG_API_ENTRY vgCreatePath (VGint pathFormat, VGPathDatatype datatype, VGfloat scale, VGfloat bias, VGint segmentCapacityHint, VGint coordCapacityHint, VGbitfield capabilities)
Definition at line 2766 of file vg_client.c.
Referenced by gx_fill_gradient(), gx_render_arrowhead(), PS_construct(), and vgft_font_convert_glyphs().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_STATE_T *state;
    VGHandle vg_handle;
    VG_CLIENT_PATH_T *path;
    scale = clean_float(scale);
    bias = clean_float(bias);
    caps &= VG_PATH_CAPABILITY_ALL;
    state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return VG_INVALID_HANDLE;
    }
    if (!is_path_format(format)) {
       set_error(VG_UNSUPPORTED_PATH_FORMAT_ERROR);
       return VG_INVALID_HANDLE;
    }
    if (!is_path_datatype(datatype) || is_zero(scale)) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return VG_INVALID_HANDLE;
    }
    vg_handle = get_stem(state);
    if (vg_handle == VG_INVALID_HANDLE) {
       set_error(VG_OUT_OF_MEMORY_ERROR);
       return VG_INVALID_HANDLE;
    }
    path = path_alloc(format, datatype, scale, bias, caps, segments_capacity);
    if (!path) {
       set_error(VG_OUT_OF_MEMORY_ERROR);
       destroy_stem(vg_handle);
       return VG_INVALID_HANDLE;
    }
    platform_mutex_acquire(&state->shared_state->mutex);
    if (!insert_object(state, vg_handle, path)) {
       set_error(VG_OUT_OF_MEMORY_ERROR);
       platform_mutex_release(&state->shared_state->mutex);
       path_free(path);
       destroy_stem(vg_handle);
       return VG_INVALID_HANDLE;
    }
    platform_mutex_release(&state->shared_state->mutex);
    RPC_CALL8(vgCreatePath_impl,
              thread,
              VGCREATEPATH_ID,
              RPC_HANDLE(vg_handle),
              RPC_INT(format),
              RPC_ENUM(datatype),
              RPC_FLOAT(scale), RPC_FLOAT(bias),
              RPC_INT(segments_capacity),
              RPC_INT(coords_capacity),
              RPC_BITFIELD(caps));
    return vg_handle;
 }
vgDestroyFont()
VG_API_CALL void VG_API_ENTRY vgDestroyFont (VGFont font)
Definition at line 4467 of file vg_client.c.
Referenced by vgft_font_convert_glyphs(), and vgft_font_term().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    platform_mutex_acquire(&state->shared_state->mutex);
    delete_object(state, vg_handle, VG_CLIENT_OBJECT_TYPE_FONT);
    platform_mutex_release(&state->shared_state->mutex);
    RPC_CALL1(vgDestroyFont_impl,
              thread,
              VGDESTROYFONT_ID,
              RPC_HANDLE(vg_handle));
 }
vgDestroyImage()
VG_API_CALL void VG_API_ENTRY vgDestroyImage (VGImage image)
Definition at line 3744 of file vg_client.c.
Referenced by graphics_bitblt(), and graphics_delete_resource().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    platform_mutex_acquire(&state->shared_state->mutex);
    delete_object(state, vg_handle, VG_CLIENT_OBJECT_TYPE_IMAGE);
    platform_mutex_release(&state->shared_state->mutex);
    RPC_CALL1(vgDestroyImage_impl,
              thread,
              VGDESTROYIMAGE_ID,
              RPC_HANDLE(vg_handle));
 }
vgDestroyMaskLayer()
VG_API_CALL void VG_API_ENTRY vgDestroyMaskLayer (VGMaskLayer maskLayer)
Definition at line 2678 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    platform_mutex_acquire(&state->shared_state->mutex);
    delete_object(state, vg_handle, VG_CLIENT_OBJECT_TYPE_MASK_LAYER);
    platform_mutex_release(&state->shared_state->mutex);
    RPC_CALL1(vgDestroyMaskLayer_impl,
              thread,
              VGDESTROYMASKLAYER_ID,
              RPC_HANDLE(vg_handle));
 }
vgDestroyPaint()
VG_API_CALL void VG_API_ENTRY vgDestroyPaint (VGPaint paint)
Definition at line 3505 of file vg_client.c.
Referenced by graphics_bitblt(), gx_destroy_paint(), and PS_destruct().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    platform_mutex_acquire(&state->shared_state->mutex);
    delete_object(state, vg_handle, VG_CLIENT_OBJECT_TYPE_PAINT);
    platform_mutex_release(&state->shared_state->mutex);
    RPC_CALL1(vgDestroyPaint_impl,
              thread,
              VGDESTROYPAINT_ID,
              RPC_HANDLE(vg_handle));
 }
vgDestroyPath()
VG_API_CALL void VG_API_ENTRY vgDestroyPath (VGPath path)
Definition at line 2866 of file vg_client.c.
Referenced by gx_fill_gradient(), gx_render_arrowhead(), and PS_destruct().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    platform_mutex_acquire(&state->shared_state->mutex);
    delete_object(state, vg_handle, VG_CLIENT_OBJECT_TYPE_PATH);
    platform_mutex_release(&state->shared_state->mutex);
    RPC_CALL1(vgDestroyPath_impl,
              thread,
              VGDESTROYPATH_ID,
              RPC_HANDLE(vg_handle));
 }
vgDrawGlyph()
VG_API_CALL void VG_API_ENTRY vgDrawGlyph (VGFont font, VGuint glyphIndex, VGbitfield paintModes, VGboolean allowAutoHinting)
Definition at line 4613 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_STATE_T *state;
 #ifdef VG_NO_STROKING
    paint_modes &= ~VG_STROKE_PATH;
    if (!paint_modes) { return; }
 #endif
    state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    sync_matrix(state, VG_MATRIX_GLYPH_USER_TO_SURFACE);
    sync_matrix(state, VG_MATRIX_FILL_PAINT_TO_USER); /* image glyphs will use, so have to send even if paint_modes doesn't have VG_FILL_PATH */
    if (paint_modes & VG_STROKE_PATH) {
       sync_matrix(state, VG_MATRIX_STROKE_PAINT_TO_USER);
    }
    if (state->render_callback)
       state->render_callback();
    RPC_CALL4(vgDrawGlyph_impl,
              thread,
              VGDRAWGLYPH_ID,
              RPC_HANDLE(vg_handle),
              RPC_UINT(glyph_id),
              RPC_BITFIELD(paint_modes),
              RPC_BOOLEAN(clean_boolean(allow_autohinting)));
 }
vgDrawGlyphs()
VG_API_CALL void VG_API_ENTRY vgDrawGlyphs (VGFont font, VGint glyphCount, const VGuint * glyphIndices, const VGfloat * adjustments_x, const VGfloat * adjustments_y, VGbitfield paintModes, VGboolean allowAutoHinting)
Definition at line 4650 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_STATE_T *state;
 #ifdef VG_NO_STROKING
    paint_modes &= ~VG_STROKE_PATH;
    if (!paint_modes) { return; }
 #endif
    state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    if ((glyphs_count <= 0) || !glyph_ids || !is_aligned_uint(glyph_ids) ||
       (adjustments_x && !is_aligned_float(adjustments_x)) ||
       (adjustments_y && !is_aligned_float(adjustments_y))) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return;
    }
    sync_matrix(state, VG_MATRIX_GLYPH_USER_TO_SURFACE);
    sync_matrix(state, VG_MATRIX_FILL_PAINT_TO_USER); /* image glyphs will use, so have to send even if paint_modes doesn't have VG_FILL_PATH */
    if (paint_modes & VG_STROKE_PATH) {
       sync_matrix(state, VG_MATRIX_STROKE_PAINT_TO_USER);
    }
    if (state->render_callback)
       state->render_callback();
    #ifdef RPC_DIRECT
       RPC_CALL7(vgDrawGlyphs_impl, thread, no_id,
          vg_handle,
          glyphs_count, glyph_ids,
          adjustments_x, adjustments_y,
          paint_modes,
          clean_boolean(allow_autohinting));
    #else
       {
          /*
             split into multiple calls if necessary to avoid overflowing control buffer
             todo: if there's an invalid glyph, we're not supposed to draw anything
             at all. currently, this works on a per-chunk level (ie we will try to
             draw the glyphs in a chunk iff there are no invalid glyphs in the chunk)
          */
          VGuint glyph_size = sizeof(VGuint) +
             (adjustments_x ? sizeof(VGfloat) : 0) +
             (adjustments_y ? sizeof(VGfloat) : 0);
          while (glyphs_count != 0) {
             #define MESSAGE_SIZE 24
             /* at least 8 glyphs. this is a hack for the cts -- it checks that we don't draw anything if there's an invalid glyph (see above) */
             VGint chunk_glyphs_count = _min(glyphs_count, (rpc_send_ctrl_longest(thread, MESSAGE_SIZE + (8 * glyph_size)) - MESSAGE_SIZE) / glyph_size);
             uint32_t message[] = {
                VGDRAWGLYPHS_ID,
                RPC_HANDLE(vg_handle),
                RPC_INT(chunk_glyphs_count),
                RPC_BITFIELD((!!adjustments_x << 0) | (!!adjustments_y << 1)),
                RPC_BITFIELD(paint_modes),
                RPC_BOOLEAN(clean_boolean(allow_autohinting)) };
             vcos_static_assert(sizeof(message) == MESSAGE_SIZE);
             #undef MESSAGE_SIZE
             rpc_send_ctrl_begin(thread, sizeof(message) + (chunk_glyphs_count * glyph_size));
             rpc_send_ctrl_write(thread, message, sizeof(message));
             rpc_send_ctrl_write(thread, (uint32_t *)glyph_ids, chunk_glyphs_count * sizeof(VGuint));
             if (adjustments_x) { rpc_send_ctrl_write(thread, (uint32_t *)adjustments_x, chunk_glyphs_count * sizeof(VGfloat)); }
             if (adjustments_y) { rpc_send_ctrl_write(thread, (uint32_t *)adjustments_y, chunk_glyphs_count * sizeof(VGfloat)); }
             rpc_send_ctrl_end(thread);
             glyphs_count -= chunk_glyphs_count;
             glyph_ids += chunk_glyphs_count;
             if (adjustments_x) { adjustments_x += chunk_glyphs_count; }
             if (adjustments_y) { adjustments_y += chunk_glyphs_count; }
          }
       }
    #endif
 }
vgDrawImage()
VG_API_CALL void VG_API_ENTRY vgDrawImage (VGImage image)
Definition at line 4133 of file vg_client.c.
Referenced by graphics_bitblt().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    sync_matrix(state, VG_MATRIX_IMAGE_USER_TO_SURFACE);
    sync_matrix(state, VG_MATRIX_FILL_PAINT_TO_USER);
    if (state->render_callback)
       state->render_callback();
    RPC_CALL1(vgDrawImage_impl,
              thread,
              VGDRAWIMAGE_ID,
              RPC_HANDLE(vg_handle));
 }
vgDrawPath()
VG_API_CALL void VG_API_ENTRY vgDrawPath (VGPath path, VGbitfield paintModes)
Definition at line 3424 of file vg_client.c.
Referenced by gx_fill_gradient(), gx_render_arrowhead(), and PS_render().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_STATE_T *state;
 #ifdef VG_NO_STROKING
    paint_modes &= ~VG_STROKE_PATH;
    if (!paint_modes) { return; }
 #endif
    state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    sync_matrix(state, VG_MATRIX_PATH_USER_TO_SURFACE);
    if (paint_modes & VG_FILL_PATH) {
       sync_matrix(state, VG_MATRIX_FILL_PAINT_TO_USER);
    }
    if (paint_modes & VG_STROKE_PATH) {
       sync_matrix(state, VG_MATRIX_STROKE_PAINT_TO_USER);
    }
    if (state->render_callback)
       state->render_callback();
    RPC_CALL2(vgDrawPath_impl,
              thread,
              VGDRAWPATH_ID,
              RPC_HANDLE(vg_handle),
              RPC_BITFIELD(paint_modes));
 }
vgFillMaskLayer()
VG_API_CALL void VG_API_ENTRY vgFillMaskLayer (VGMaskLayer maskLayer, VGint x, VGint y, VGint width, VGint height, VGfloat value)
Definition at line 2697 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    value = clean_float(value);
    if (!VG_GET_CLIENT_STATE(thread)) {
       return;
    }
    RPC_CALL6(vgFillMaskLayer_impl,
              thread,
              VGFILLMASKLAYER_ID,
              RPC_HANDLE(vg_handle),
              RPC_INT(x), RPC_INT(y),
              RPC_INT(width), RPC_INT(height),
              RPC_FLOAT(value));
 }
vgFinish()
VG_API_CALL void VG_API_ENTRY vgFinish (void)
Definition at line 927 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    (void)RPC_UINT_RES(RPC_CALL0_RES(vgFinish_impl,
                                     thread,
                                     VGFINISH_ID)); /* return value ignored -- read performed to ensure blocking */
 #ifdef KHRN_COMMAND_MODE_DISPLAY
    {
    //Check for single buffered windows surface in which case call surface updater
       EGL_SURFACE_T *surface = CLIENT_GET_THREAD_STATE()->openvg.draw;
       if (surface->type == WINDOW && surface->buffers==1) {
          platform_surface_update(surface->internal_handle);
       }
    }
 #endif
    if (state->flush_callback)
       state->flush_callback(true);
 }
vgFlush()
VG_API_CALL void VG_API_ENTRY vgFlush (void)
Definition at line 900 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    RPC_CALL0(vgFlush_impl,
              thread,
              VGFLUSH_ID);
    RPC_FLUSH(thread);
 #ifdef KHRN_COMMAND_MODE_DISPLAY
    {
       //Check for single buffered windows surface in which case call surface updater
       EGL_SURFACE_T *surface = CLIENT_GET_THREAD_STATE()->openvg.draw;
       if (surface->type == WINDOW && surface->buffers==1) {
          platform_surface_update(surface->internal_handle);
       }
    }
 #endif
    if (state->flush_callback)
       state->flush_callback(false);
 }
vgGaussianBlur()
VG_API_CALL void VG_API_ENTRY vgGaussianBlur (VGImage dst, VGImage src, VGfloat stdDeviationX, VGfloat stdDeviationY, VGTilingMode tilingMode)
Definition at line 4858 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    std_dev_x = clean_float(std_dev_x);
    std_dev_y = clean_float(std_dev_y);
    if (!VG_GET_CLIENT_STATE(thread)) {
       return;
    }
    RPC_CALL5(vgGaussianBlur_impl,
              thread,
              VGGAUSSIANBLUR_ID,
              RPC_HANDLE(dst_vg_handle), RPC_HANDLE(src_vg_handle),
              RPC_FLOAT(std_dev_x), RPC_FLOAT(std_dev_y),
              RPC_ENUM(tiling_mode));
 }
vgGetColor()
VG_API_CALL VGuint VG_API_ENTRY vgGetColor (VGPaint paint)
Definition at line 3610 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_PAINT_T *paint;
    VGuint rgba;
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return 0;
    }
    platform_mutex_acquire(&state->shared_state->mutex);
    paint = (VG_CLIENT_PAINT_T *)lookup_object(state, vg_handle, VG_CLIENT_OBJECT_TYPE_PAINT);
    if (!paint) {
       set_error(VG_BAD_HANDLE_ERROR);
       platform_mutex_release(&state->shared_state->mutex);
       return 0;
    }
    rgba = color_floats_to_rgba_clean(paint->color);
    platform_mutex_release(&state->shared_state->mutex);
    return khrn_color_rgba_flip(rgba);
 }
vgGetError()
VG_API_CALL VGErrorCode VG_API_ENTRY vgGetError (void)
Definition at line 890 of file vg_client.c.
Referenced by graphics_bitblt(), graphics_delete_resource(), gx_bind_vg(), gx_create_gradient(), gx_fill_gradient(), gx_priv_get_pixels(), gx_priv_resource_fill(), gx_render_arrowhead(), PS_render(), and render().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (!VG_GET_CLIENT_STATE(thread)) {
       return VG_NO_CONTEXT_ERROR;
    }
    return get_error();
 }
vgGetf()
VG_API_CALL VGfloat VG_API_ENTRY vgGetf (VGParamType type)
Definition at line 1905 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VGfloat value = 0.0f;
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return 0.0f;
    }
    if (is_vector_param_type(param_type)) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return 0.0f;
    }
    get_ifv(thread, state, param_type, 1, true, &value);
    return value;
 }
vgGetfv()
VG_API_CALL void VG_API_ENTRY vgGetfv (VGParamType type, VGint count, VGfloat * values)
Definition at line 2010 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    if ((count <= 0) || !values || !is_aligned_float(values)) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return;
    }
    get_ifv(thread, state, param_type, count, true, values);
 }
vgGeti()
VG_API_CALL VGint VG_API_ENTRY vgGeti (VGParamType type)
Definition at line 1925 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VGint value = 0;
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return 0;
    }
    if (is_vector_param_type(param_type)) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return 0;
    }
    get_ifv(thread, state, param_type, 1, false, &value);
    return value;
 }
vgGetImageSubData()
VG_API_CALL void VG_API_ENTRY vgGetImageSubData (VGImage image, void * data, VGint dataStride, VGImageFormat dataFormat, VGint x, VGint y, VGint width, VGint height)
Definition at line 3891 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_IMAGE_T *src;
    VGint src_width;
    VGint src_height;
    VGint dst_x = 0, dst_y = 0;
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    if (!is_image_format(data_format)) {
       set_error(VG_UNSUPPORTED_IMAGE_FORMAT_ERROR);
       return;
    }
    if (!data || !is_aligned_image_format(data, data_format) ||
       ((height != 1) && !is_aligned_image_format((void *)(uintptr_t)data_stride, data_format)) ||
       (width <= 0) || (height <= 0)) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return;
    }
    platform_mutex_acquire(&state->shared_state->mutex);
    src = (VG_CLIENT_IMAGE_T *)lookup_object(state, vg_handle, VG_CLIENT_OBJECT_TYPE_IMAGE);
    if (!src) {
       set_error(VG_BAD_HANDLE_ERROR);
       platform_mutex_release(&state->shared_state->mutex);
       return;
    }
    src_width = src->width;
    src_height = src->height;
    platform_mutex_release(&state->shared_state->mutex);
    khrn_clip_rect2(
       &dst_x, &dst_y, &src_x, &src_y, &width, &height,
       0, 0, width, height,
       0, 0, src_width, src_height);
    if (width <= 0 || height <= 0) {
       return;
    }
    data = (VGubyte *)data + (dst_y * data_stride);
    #ifdef RPC_DIRECT
       RPC_CALL11(vgGetImageSubData_impl, thread, no_id,
          vg_handle,
          src_width, src_height,
          data, data_stride,
          data_format,
          dst_x,
          src_x, src_y,
          width, height);
    #else
       {
          VGuint log2_bpp = get_log2_image_format_bpp(data_format);
          VGuint line_size;
          VGuint first_mask;
          VGuint last_mask;
          VGuint chunk_height_max;
          data = (VGubyte *)data + ((dst_x << log2_bpp) >> 3);
          dst_x = ((dst_x << log2_bpp) & 0x7) >> log2_bpp;
          line_size = (((dst_x + width) << log2_bpp) + 0x7) >> 3;
          first_mask = (1 << (dst_x << log2_bpp)) - 1;
          last_mask = ~((2 << ((((dst_x + width) << log2_bpp) - 1) & 0x7)) - 1) & 0xff;
          /*
             split into KHDISPATCH_WORKSPACE_SIZE chunks (or thereabouts)
          */
          chunk_height_max = (line_size == 0) ? height : (KHDISPATCH_WORKSPACE_SIZE / line_size);
          vcos_assert((height == 0) || (chunk_height_max != 0));
          while (height != 0) {
             VGint chunk_height = _min(height, chunk_height_max);
             uint32_t message[] = {
                VGGETIMAGESUBDATA_ID,
                RPC_HANDLE(vg_handle),
                RPC_INT(src_width), RPC_INT(src_height),
                RPC_UINT(line_size),
                RPC_ENUM(data_format),
                RPC_INT(dst_x),
                RPC_INT(src_x), RPC_INT(src_y),
                RPC_INT(width), RPC_INT(chunk_height) };
             rpc_begin(thread);
             rpc_send_ctrl_begin(thread, sizeof(message));
             rpc_send_ctrl_write(thread, message, sizeof(message));
             rpc_send_ctrl_end(thread);
             {
                uint32_t len[] = { 0, data_stride, chunk_height, first_mask, last_mask };
                rpc_recv(thread, data, len, (RPC_RECV_FLAG_T)(RPC_RECV_FLAG_BULK | RPC_RECV_FLAG_BULK_SCATTER | RPC_RECV_FLAG_LEN));
                data = (VGubyte *)data + (chunk_height * data_stride);
                if (len[0] == 0) {  //The command has failed so no data sent back
                   rpc_end(thread);
                   break;
                }
                vcos_assert(len[0] == line_size);
             }
             rpc_end(thread);
             height -= chunk_height;
             src_y += chunk_height;
          }
       }
    #endif
 }
vgGetiv()
VG_API_CALL void VG_API_ENTRY vgGetiv (VGParamType type, VGint count, VGint * values)
Definition at line 2029 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    if ((count <= 0) || !values || !is_aligned_int(values)) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return;
    }
    get_ifv(thread, state, param_type, count, false, values);
 }
vgGetMatrix()
VG_API_CALL void VG_API_ENTRY vgGetMatrix (VGfloat * m)
Definition at line 2458 of file vg_client.c.
Referenced by graphics_bitblt().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    if (!matrix || !is_aligned_float(matrix)) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return;
    }
    vg_mat3x3_get(&get_matrix_sync(state, state->matrix_mode)->client, matrix);
 }
vgGetPaint()
VG_API_CALL VGPaint VG_API_ENTRY vgGetPaint (VGPaintMode paintMode)
Definition at line 3564 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return VG_INVALID_HANDLE;
    }
    if (!is_paint_mode(paint_mode)) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return VG_INVALID_HANDLE;
    }
    return (paint_mode == VG_FILL_PATH) ? state->fill_paint : state->stroke_paint;
 }
vgGetParameterf()
VG_API_CALL VGfloat VG_API_ENTRY vgGetParameterf (VGHandle object, VGint paramType)
Definition at line 2154 of file vg_client.c.
 {
    VGfloat value = 0.0f;
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return 0.0f;
    }
    if (is_vector_object_param_type(param_type)) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return 0.0f;
    }
    get_parameter_ifv(thread, state, vg_handle, param_type, 1, true, &value);
    return value;
 }
vgGetParameterfv()
VG_API_CALL void VG_API_ENTRY vgGetParameterfv (VGHandle object, VGint paramType, VGint count, VGfloat * values)
Definition at line 2381 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    if ((count <= 0) || !values || !is_aligned_float(values)) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return;
    }
    get_parameter_ifv(thread, state, vg_handle, param_type, count, true, values);
 }
vgGetParameteri()
VG_API_CALL VGint VG_API_ENTRY vgGetParameteri (VGHandle object, VGint paramType)
Definition at line 2175 of file vg_client.c.
 {
    VGint value = 0;
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return 0;
    }
    if (is_vector_object_param_type(param_type)) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return 0;
    }
    get_parameter_ifv(thread, state, vg_handle, param_type, 1, false, &value);
    return value;
 }
vgGetParameteriv()
VG_API_CALL void VG_API_ENTRY vgGetParameteriv (VGHandle object, VGint paramType, VGint count, VGint * values)
Definition at line 2401 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    if ((count <= 0) || !values || !is_aligned_int(values)) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return;
    }
    get_parameter_ifv(thread, state, vg_handle, param_type, count, false, values);
 }
vgGetParameterVectorSize()
VG_API_CALL VGint VG_API_ENTRY vgGetParameterVectorSize (VGHandle object, VGint paramType)
Definition at line 2196 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    void *object;
    VGint count = 0;
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return 0;
    }
    platform_mutex_acquire(&state->shared_state->mutex);
    object = khrn_pointer_map_lookup(&state->shared_state->objects, nice_handle(vg_handle));
    if (!object) {
       set_error(VG_BAD_HANDLE_ERROR);
       platform_mutex_release(&state->shared_state->mutex);
       return 0;
    }
    switch (*(VG_CLIENT_OBJECT_TYPE_T *)object) {
    case VG_CLIENT_OBJECT_TYPE_PATH:
    {
       switch (param_type) {
       /*
          scalar param types
       */
       case VG_PATH_FORMAT:
       case VG_PATH_DATATYPE:
       case VG_PATH_SCALE:
       case VG_PATH_BIAS:
       case VG_PATH_NUM_SEGMENTS:
       case VG_PATH_NUM_COORDS:
       {
          count = 1;
          break;
       }
       /*
          invalid param type
       */
       default:
          set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       }
       break;
    }
    case VG_CLIENT_OBJECT_TYPE_PAINT:
    {
       switch (param_type) {
       /*
          scalar param types
       */
       case VG_PAINT_TYPE:
       case VG_PAINT_COLOR_RAMP_SPREAD_MODE:
       case VG_PAINT_COLOR_RAMP_PREMULTIPLIED:
       case VG_PAINT_PATTERN_TILING_MODE:
       {
          count = 1;
          break;
       }
       /*
          vector param types
       */
       case VG_PAINT_COLOR:
       {
          count = 4;
          break;
       }
       case VG_PAINT_COLOR_RAMP_STOPS:
       {
          VG_CLIENT_PAINT_T *paint = (VG_CLIENT_PAINT_T *)object;
          count = paint->gradient ? paint->gradient->ramp_stops_count : 0;
          break;
       }
       case VG_PAINT_LINEAR_GRADIENT:
       {
          count = 4;
          break;
       }
       case VG_PAINT_RADIAL_GRADIENT:
       {
          count = 5;
          break;
       }
       /*
          invalid param type
       */
       default:
          set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       }
       break;
    }
    case VG_CLIENT_OBJECT_TYPE_IMAGE:
    {
       switch (param_type) {
       /*
          scalar param types
       */
       case VG_IMAGE_FORMAT:
       case VG_IMAGE_WIDTH:
       case VG_IMAGE_HEIGHT:
       {
          count = 1;
          break;
       }
       /*
          invalid param type
       */
       default:
          set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       }
       break;
    }
    case VG_CLIENT_OBJECT_TYPE_MASK_LAYER:
    {
       switch (param_type) {
       /*
          scalar param types
       */
       case VG_IMAGE_WIDTH:
       case VG_IMAGE_HEIGHT:
       {
          count = 1;
          break;
       }
       /*
          invalid param type
       */
       default:
          set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       }
       break;
    }
    case VG_CLIENT_OBJECT_TYPE_FONT:
    {
       switch (param_type) {
       /*
          scalar param types
       */
       case VG_FONT_NUM_GLYPHS:
       {
          count = 1;
          break;
       }
       /*
          invalid param type
       */
       default:
          set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       }
       break;
    }
    default:
    {
       UNREACHABLE();
    }
    }
    platform_mutex_release(&state->shared_state->mutex);
    return count;
 }
vgGetParent()
VG_API_CALL VGImage VG_API_ENTRY vgGetParent (VGImage image)
Definition at line 4099 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (!VG_GET_CLIENT_STATE(thread)) {
       return VG_INVALID_HANDLE;
    }
    return RPC_HANDLE_RES(RPC_CALL1_RES(vgGetParent_impl,
                                        thread,
                                        VGGETPARENT_ID,
                                        RPC_HANDLE(vg_handle)));
 }
vgGetPathCapabilities()
VG_API_CALL VGbitfield VG_API_ENTRY vgGetPathCapabilities (VGPath path)
Definition at line 2911 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VGbitfield caps = 0;
    VG_CLIENT_PATH_T *path;
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return 0;
    }
    platform_mutex_acquire(&state->shared_state->mutex);
    path = (VG_CLIENT_PATH_T *)lookup_object(state, vg_handle, VG_CLIENT_OBJECT_TYPE_PATH);
    if (path) {
       caps = path->caps;
    } else {
       set_error(VG_BAD_HANDLE_ERROR);
    }
    platform_mutex_release(&state->shared_state->mutex);
    return caps;
 }
vgGetPixels()
VG_API_CALL void VG_API_ENTRY vgGetPixels (VGImage dst, VGint dx, VGint dy, VGint sx, VGint sy, VGint width, VGint height)
Definition at line 4274 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (!VG_GET_CLIENT_STATE(thread)) {
       return;
    }
    RPC_CALL7(vgGetPixels_impl,
              thread,
              VGGETPIXELS_ID,
              RPC_HANDLE(dst_vg_handle), RPC_INT(dst_x), RPC_INT(dst_y),
              RPC_INT(src_x), RPC_INT(src_y),
              RPC_INT(width), RPC_INT(height));
 }
vgGetString()
VG_API_CALL const VGubyte* VG_API_ENTRY vgGetString (VGStringID name)
Definition at line 4974 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (!VG_GET_CLIENT_STATE(thread)) {
       return NULL;
    }
    switch (name) {
    case VG_VENDOR:     return (const VGubyte *)VG_CONFIG_VENDOR;
    case VG_RENDERER:   return (const VGubyte *)VG_CONFIG_RENDERER;
    case VG_VERSION:    return (const VGubyte *)"1.1";
    case VG_EXTENSIONS: return (const VGubyte *)VG_CONFIG_EXTENSIONS;
    default:            return NULL;
    }
 }
vgGetVectorSize()
VG_API_CALL VGint VG_API_ENTRY vgGetVectorSize (VGParamType type)
Definition at line 1945 of file vg_client.c.
References VG_GET_CLIENT_STATE.
 {
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(CLIENT_GET_THREAD_STATE());
    if (!state) {
       return 0;
    }
    switch (param_type) {
    /*
       scalar param types
    */
    case VG_MATRIX_MODE:
    case VG_FILL_RULE:
    case VG_IMAGE_QUALITY:
    case VG_RENDERING_QUALITY:
    case VG_BLEND_MODE:
    case VG_IMAGE_MODE:
    case VG_COLOR_TRANSFORM:
    case VG_STROKE_LINE_WIDTH:
    case VG_STROKE_CAP_STYLE:
    case VG_STROKE_JOIN_STYLE:
    case VG_STROKE_MITER_LIMIT:
    case VG_STROKE_DASH_PHASE:
    case VG_STROKE_DASH_PHASE_RESET:
    case VG_MASKING:
    case VG_SCISSORING:
    case VG_PIXEL_LAYOUT:
    case VG_SCREEN_LAYOUT:
    case VG_FILTER_FORMAT_LINEAR:
    case VG_FILTER_FORMAT_PREMULTIPLIED:
    case VG_FILTER_CHANNEL_MASK:
    case VG_MAX_SCISSOR_RECTS:
    case VG_MAX_DASH_COUNT:
    case VG_MAX_KERNEL_SIZE:
    case VG_MAX_SEPARABLE_KERNEL_SIZE:
    case VG_MAX_COLOR_RAMP_STOPS:
    case VG_MAX_IMAGE_WIDTH:
    case VG_MAX_IMAGE_HEIGHT:
    case VG_MAX_IMAGE_PIXELS:
    case VG_MAX_IMAGE_BYTES:
    case VG_MAX_FLOAT:
    case VG_MAX_GAUSSIAN_STD_DEVIATION: return 1;
    /*
       vector param types
    */
    case VG_SCISSOR_RECTS:          return state->scissor_rects_count;
    case VG_COLOR_TRANSFORM_VALUES: return 8;
    case VG_STROKE_DASH_PATTERN:    return state->stroke_dash_pattern_count;
    case VG_TILE_FILL_COLOR:
    case VG_CLEAR_COLOR:            return 4;
    case VG_GLYPH_ORIGIN:           return 2;
    /*
       invalid param type
    */
    default: set_error(VG_ILLEGAL_ARGUMENT_ERROR); return 0;
    }
 }
vgHardwareQuery()
VG_API_CALL VGHardwareQueryResult VG_API_ENTRY vgHardwareQuery (VGHardwareQueryType key, VGint setting)
Definition at line 4955 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (!VG_GET_CLIENT_STATE(thread)) {
       return (VGHardwareQueryResult)0;
    }
    if (!is_hardware_query_type(hardware_query_type) ||
       ((hardware_query_type == VG_IMAGE_FORMAT_QUERY) && !is_image_format((VGImageFormat)setting)) ||
       ((hardware_query_type == VG_PATH_DATATYPE_QUERY) && !is_path_datatype((VGPathDatatype)setting))) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return (VGHardwareQueryResult)0;
    }
    return VG_HARDWARE_ACCELERATED;
 }
vgImageSubData()
VG_API_CALL void VG_API_ENTRY vgImageSubData (VGImage image, const void * data, VGint dataStride, VGImageFormat dataFormat, VGint x, VGint y, VGint width, VGint height)
Definition at line 3781 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_IMAGE_T *dst;
    VGint dst_width;
    VGint dst_height;
    VGint src_x = 0, src_y = 0;
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    if (!is_image_format(data_format)) {
       set_error(VG_UNSUPPORTED_IMAGE_FORMAT_ERROR);
       return;
    }
    if (!data || !is_aligned_image_format(data, data_format) ||
       ((height != 1) && !is_aligned_image_format((void *)(uintptr_t)data_stride, data_format)) ||
       (width <= 0) || (height <= 0)) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return;
    }
    platform_mutex_acquire(&state->shared_state->mutex);
    dst = (VG_CLIENT_IMAGE_T *)lookup_object(state, vg_handle, VG_CLIENT_OBJECT_TYPE_IMAGE);
    if (!dst) {
       set_error(VG_BAD_HANDLE_ERROR);
       platform_mutex_release(&state->shared_state->mutex);
       return;
    }
    dst_width = dst->width;
    dst_height = dst->height;
    platform_mutex_release(&state->shared_state->mutex);
    khrn_clip_rect2(
       &dst_x, &dst_y, &src_x, &src_y, &width, &height,
       0, 0, dst_width, dst_height,
       0, 0, width, height);
    if (width <= 0 || height <= 0) {
       return;
    }
    data = (const VGubyte *)data + (src_y * data_stride);
    #ifdef RPC_DIRECT
       RPC_CALL11(vgImageSubData_impl, thread, no_id,
          vg_handle,
          dst_width, dst_height,
          data, data_stride,
          data_format,
          src_x,
          dst_x, dst_y,
          width, height);
    #else
       {
          VGuint log2_bpp = get_log2_image_format_bpp(data_format);
          VGuint line_size;
          VGuint chunk_height_max;
          data = (const VGubyte *)data + ((src_x << log2_bpp) >> 3);
          src_x = ((src_x << log2_bpp) & 0x7) >> log2_bpp;
          line_size = (((src_x + width) << log2_bpp) + 0x7) >> 3;
          /*
             split into KHDISPATCH_WORKSPACE_SIZE chunks (or thereabouts)
          */
          chunk_height_max = (line_size == 0) ? height : (KHDISPATCH_WORKSPACE_SIZE / line_size);
          vcos_assert((height == 0) || (chunk_height_max != 0));
          while (height != 0) {
             VGint chunk_height = _min(height, chunk_height_max);
             uint32_t message[] = {
                VGIMAGESUBDATA_ID,
                RPC_HANDLE(vg_handle),
                RPC_INT(dst_width), RPC_INT(dst_height),
                RPC_UINT(line_size),
                RPC_ENUM(data_format),
                RPC_INT(src_x),
                RPC_INT(dst_x), RPC_INT(dst_y),
                RPC_INT(width), RPC_INT(chunk_height) };
             rpc_begin(thread);
             rpc_send_ctrl_begin(thread, sizeof(message));
             rpc_send_ctrl_write(thread, message, sizeof(message));
             rpc_send_ctrl_end(thread);
             rpc_send_bulk_gather(thread, data, line_size, data_stride, chunk_height);
             data = (const VGubyte *)data + (chunk_height * data_stride);
             rpc_end(thread);
             height -= chunk_height;
             dst_y += chunk_height;
          }
       }
    #endif
 }
vgInterpolatePath()
VG_API_CALL VGboolean VG_API_ENTRY vgInterpolatePath (VGPath dstPath, VGPath startPath, VGPath endPath, VGfloat amount)
Definition at line 3229 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_STATE_T *state;
    VG_CLIENT_PATH_T *dst;
    VG_CLIENT_PATH_T *begin;
    VG_CLIENT_PATH_T *end;
    t = clean_float(t);
    state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return VG_FALSE;
    }
    platform_mutex_acquire(&state->shared_state->mutex);
    dst = (VG_CLIENT_PATH_T *)lookup_object(state, dst_vg_handle, VG_CLIENT_OBJECT_TYPE_PATH);
    begin = (VG_CLIENT_PATH_T *)lookup_object(state, begin_vg_handle, VG_CLIENT_OBJECT_TYPE_PATH);
    end = (VG_CLIENT_PATH_T *)lookup_object(state, end_vg_handle, VG_CLIENT_OBJECT_TYPE_PATH);
    if (dst && begin && end &&
       (dst->caps & VG_PATH_CAPABILITY_INTERPOLATE_TO) && (begin->caps & VG_PATH_CAPABILITY_INTERPOLATE_FROM) && (end->caps & VG_PATH_CAPABILITY_INTERPOLATE_FROM)) {
       if ((begin->segments.size != end->segments.size) ||
          !interpolate_segments_compatible((const VGubyte *)begin->segments.data, (const VGubyte *)end->segments.data, begin->segments.size)) {
          /*
             incompatible paths. no error -- just return false
          */
          platform_mutex_release(&state->shared_state->mutex);
          return VG_FALSE;
       }
       if (need_path_segments(dst->caps)) {
          VGuint segments_count = begin->segments.size;
          if (!khrn_vector_extend(&dst->segments, segments_count)) {
             set_error(VG_OUT_OF_MEMORY_ERROR);
             platform_mutex_release(&state->shared_state->mutex);
             return VG_FALSE;
          }
          {
             VGubyte *dst_segments = (VGubyte *)dst->segments.data + (dst->segments.size - segments_count);
             const VGubyte *begin_segments = (const VGubyte *)begin->segments.data;
             for (; segments_count != 0; ++dst_segments, ++begin_segments, --segments_count) {
                *dst_segments = (VGubyte)normalise_segment(*begin_segments & ~VG_RELATIVE);
             }
          }
       }
    }
    platform_mutex_release(&state->shared_state->mutex);
    RPC_CALL4(vgInterpolatePath_impl,
              thread,
              VGINTERPOLATEPATH_ID,
              RPC_HANDLE(dst_vg_handle),
              RPC_HANDLE(begin_vg_handle),
              RPC_HANDLE(end_vg_handle),
              RPC_FLOAT(t));
    return VG_TRUE;
 }
vgLoadIdentity()
VG_API_CALL void VG_API_ENTRY vgLoadIdentity (void)
Definition at line 2425 of file vg_client.c.
Referenced by graphics_bitblt(), and render().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_MAT3X3_SYNC_T *matrix_sync;
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    matrix_sync = get_matrix_sync(state, state->matrix_mode);
    vg_mat3x3_set_identity(&matrix_sync->client);
 }
vgLoadMatrix()
VG_API_CALL void VG_API_ENTRY vgLoadMatrix (const VGfloat * m)
Definition at line 2439 of file vg_client.c.
Referenced by graphics_bitblt().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_MAT3X3_SYNC_T *matrix_sync;
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    if (!matrix || !is_aligned_float(matrix)) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return;
    }
    matrix_sync = get_matrix_sync(state, state->matrix_mode);
    vg_mat3x3_set_clean(&matrix_sync->client, matrix, is_matrix_affine(state->matrix_mode));
 }
vgLookup()
VG_API_CALL void VG_API_ENTRY vgLookup (VGImage dst, VGImage src, const VGubyte * redLUT, const VGubyte * greenLUT, const VGubyte * blueLUT, const VGubyte * alphaLUT, VGboolean outputLinear, VGboolean outputPremultiplied)
Definition at line 4879 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (!VG_GET_CLIENT_STATE(thread)) {
       return;
    }
    if (!red_lut || !green_lut || !blue_lut || !alpha_lut) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return;
    }
    #ifdef RPC_DIRECT
       RPC_CALL8(vgLookup_impl, thread, no_id,
          dst_vg_handle, src_vg_handle,
          red_lut, green_lut, blue_lut, alpha_lut,
          clean_boolean(output_linear),
          clean_boolean(output_pre));
    #else
       {
          uint32_t message[] = {
             VGLOOKUP_ID,
             RPC_HANDLE(dst_vg_handle), RPC_HANDLE(src_vg_handle),
             RPC_BOOLEAN(clean_boolean(output_linear)),
             RPC_BOOLEAN(clean_boolean(output_pre)) };
          rpc_send_ctrl_begin(thread, sizeof(message) + 1024);
          rpc_send_ctrl_write(thread, message, sizeof(message));
          rpc_send_ctrl_write(thread, (uint32_t *)red_lut, 256);
          rpc_send_ctrl_write(thread, (uint32_t *)green_lut, 256);
          rpc_send_ctrl_write(thread, (uint32_t *)blue_lut, 256);
          rpc_send_ctrl_write(thread, (uint32_t *)alpha_lut, 256);
          rpc_send_ctrl_end(thread);
       }
    #endif
 }
vgLookupSingle()
VG_API_CALL void VG_API_ENTRY vgLookupSingle (VGImage dst, VGImage src, const VGuint * lookupTable, VGImageChannel sourceChannel, VGboolean outputLinear, VGboolean outputPremultiplied)
Definition at line 4923 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (!VG_GET_CLIENT_STATE(thread)) {
       return;
    }
    if (!lut || !is_aligned_uint(lut)) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return;
    }
    RPC_CALL6_IN_CTRL(vgLookupSingle_impl,
                      thread,
                      VGLOOKUPSINGLE_ID,
                      RPC_HANDLE(dst_vg_handle), RPC_HANDLE(src_vg_handle),
                      RPC_ENUM(source_channel),
                      RPC_BOOLEAN(clean_boolean(output_linear)),
                      RPC_BOOLEAN(clean_boolean(output_pre)),
                      lut,
                      256 * sizeof(VGuint));
 }
vgMask()
VG_API_CALL void VG_API_ENTRY vgMask (VGHandle mask, VGMaskOperation operation, VGint x, VGint y, VGint width, VGint height)
Definition at line 2571 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (!VG_GET_CLIENT_STATE(thread)) {
       return;
    }
    RPC_CALL6(vgMask_impl,
              thread,
              VGMASK_ID,
              RPC_HANDLE(vg_handle),
              RPC_ENUM(operation),
              RPC_INT(dst_x),
              RPC_INT(dst_y),
              RPC_INT(width),
              RPC_INT(height));
 }
vgModifyPathCoords()
VG_API_CALL void VG_API_ENTRY vgModifyPathCoords (VGPath dstPath, VGint startIndex, VGint numSegments, const void * pathData)
Definition at line 3088 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_PATH_T *path;
    VGPathDatatype datatype;
    VGuint datatype_size;
    VGuint coords_offset;
    VGuint coords_size;
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    platform_mutex_acquire(&state->shared_state->mutex);
    path = (VG_CLIENT_PATH_T *)lookup_object(state, vg_handle, VG_CLIENT_OBJECT_TYPE_PATH);
    if (!path) {
       set_error(VG_BAD_HANDLE_ERROR);
       platform_mutex_release(&state->shared_state->mutex);
       return;
    }
    if (!(path->caps & VG_PATH_CAPABILITY_MODIFY)) {
       set_error(VG_PATH_CAPABILITY_ERROR);
       platform_mutex_release(&state->shared_state->mutex);
       return;
    }
    datatype = path->datatype;
    if ((segments_i < 0) || (segments_count <= 0) ||
       /* will fit in VGuint (may not fit in VGint) */
       (((VGuint)(segments_i + segments_count)) > path->segments.size) ||
       !coords || !is_aligned_path_datatype(coords, datatype)) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       platform_mutex_release(&state->shared_state->mutex);
       return;
    }
    datatype_size = get_path_datatype_size(path->datatype);
    coords_offset = get_coords_count((const VGubyte *)path->segments.data, segments_i) * datatype_size;
    coords_size = get_coords_count((const VGubyte *)path->segments.data + segments_i, segments_count) * datatype_size;
    platform_mutex_release(&state->shared_state->mutex);
    #ifdef RPC_DIRECT
       RPC_CALL5(vgModifyPathCoords_impl, thread, no_id,
          vg_handle,
          datatype,
          coords_offset, coords_size, coords);
    #else
       /*
          split into multiple calls if necessary to avoid overflowing control buffer
       */
       while (coords_size != 0) {
          #define MESSAGE_SIZE 20
          VGuint chunk_coords_size = _min(coords_size, rpc_send_ctrl_longest(thread, MESSAGE_SIZE + rpc_pad_ctrl(4)) - MESSAGE_SIZE); /* fit at least one coordinate */
          uint32_t message[] = {
             VGMODIFYPATHCOORDS_ID,
             RPC_HANDLE(vg_handle),
             RPC_ENUM(datatype),
             RPC_UINT(coords_offset),
             RPC_UINT(chunk_coords_size) };
          vcos_static_assert(sizeof(message) == MESSAGE_SIZE);
          #undef MESSAGE_SIZE
          rpc_send_ctrl_begin(thread, sizeof(message) + rpc_pad_ctrl(chunk_coords_size));
          rpc_send_ctrl_write(thread, message, sizeof(message));
          rpc_send_ctrl_write(thread, (uint32_t *)coords, chunk_coords_size);
          rpc_send_ctrl_end(thread);
          coords_size -= chunk_coords_size;
          coords_offset += chunk_coords_size;
          coords = (const uint8_t *)coords + chunk_coords_size;
       }
    #endif
 }
vgMultMatrix()
VG_API_CALL void VG_API_ENTRY vgMultMatrix (const VGfloat * m)
Definition at line 2474 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_MAT3X3_T a;
    VG_MAT3X3_SYNC_T *matrix_sync;
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    if (!matrix || !is_aligned_float(matrix)) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return;
    }
    vg_mat3x3_set_clean(&a, matrix, is_matrix_affine(state->matrix_mode));
    matrix_sync = get_matrix_sync(state, state->matrix_mode);
    vg_mat3x3_postmul(&matrix_sync->client, &a);
 }
vgPaintPattern()
VG_API_CALL void VG_API_ENTRY vgPaintPattern (VGPaint paint, VGImage pattern)
Definition at line 3634 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_PAINT_T *paint;
    VG_CLIENT_IMAGE_T *pattern;
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    platform_mutex_acquire(&state->shared_state->mutex);
    paint = (VG_CLIENT_PAINT_T *)lookup_object(state, vg_handle, VG_CLIENT_OBJECT_TYPE_PAINT);
    pattern = (pattern_vg_handle == VG_INVALID_HANDLE) ? NULL : (VG_CLIENT_IMAGE_T *)lookup_object(state, pattern_vg_handle, VG_CLIENT_OBJECT_TYPE_IMAGE);
    if (!paint || ((pattern_vg_handle != VG_INVALID_HANDLE) && !pattern)) {
       set_error(VG_BAD_HANDLE_ERROR);
       platform_mutex_release(&state->shared_state->mutex);
       return;
    }
    if (paint->pattern != pattern_vg_handle) {
       paint->pattern = pattern_vg_handle;
 #if EGL_BRCM_global_image && EGL_KHR_image
       if (pattern && (pattern->global_image_id[0] || pattern->global_image_id[1])) {
          platform_acquire_global_image(pattern->global_image_id[0], pattern->global_image_id[1]);
       }
       if (paint->pattern_global_image_id[0] || paint->pattern_global_image_id[1]) {
          platform_release_global_image(paint->pattern_global_image_id[0], paint->pattern_global_image_id[1]);
       }
       paint->pattern_global_image_id[0] = pattern ? pattern->global_image_id[0] : 0;
       paint->pattern_global_image_id[1] = pattern ? pattern->global_image_id[1] : 0;
 #endif
       RPC_CALL2(vgPaintPattern_impl,
                 thread,
                 VGPAINTPATTERN_ID,
                 RPC_HANDLE(vg_handle),
                 RPC_HANDLE(pattern_vg_handle));
    }
    platform_mutex_release(&state->shared_state->mutex);
 }
vgPathBounds()
VG_API_CALL void VG_API_ENTRY vgPathBounds (VGPath path, VGfloat * minX, VGfloat * minY, VGfloat * width, VGfloat * height)
Definition at line 3353 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VGfloat values[4];
    if (!VG_GET_CLIENT_STATE(thread)) {
       return;
    }
    if (!min_x || !is_aligned_float(min_x) || !min_y || !is_aligned_float(min_y) ||
       !width || !is_aligned_float(width) || !height || !is_aligned_float(height)) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return;
    }
    if (RPC_BOOLEAN_RES(RPC_CALL2_OUT_CTRL_RES(vgPathBounds_impl,
                                               thread,
                                               VGPATHBOUNDS_ID,
                                               RPC_HANDLE(vg_handle),
                                               values))) {
       /*
          no error occurred on the server side
       */
       *min_x = values[0];
       *min_y = values[1];
       *width = values[2];
       *height = values[3];
    }
 }
vgPathLength()
VG_API_CALL VGfloat VG_API_ENTRY vgPathLength (VGPath path, VGint startSegment, VGint numSegments)
Definition at line 3292 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (!VG_GET_CLIENT_STATE(thread)) {
       return 0.0f;
    }
    return RPC_FLOAT_RES(RPC_CALL3_RES(vgPathLength_impl,
                                       thread,
                                       VGPATHLENGTH_ID,
                                       RPC_HANDLE(vg_handle),
                                       RPC_INT(segments_i), RPC_INT(segments_count)));
 }
vgPathTransformedBounds()
VG_API_CALL void VG_API_ENTRY vgPathTransformedBounds (VGPath path, VGfloat * minX, VGfloat * minY, VGfloat * width, VGfloat * height)
Definition at line 3387 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VGfloat values[4];
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    if (!min_x || !is_aligned_float(min_x) || !min_y || !is_aligned_float(min_y) ||
       !width || !is_aligned_float(width) || !height || !is_aligned_float(height)) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return;
    }
    sync_matrix(state, VG_MATRIX_PATH_USER_TO_SURFACE);
    if (RPC_BOOLEAN_RES(RPC_CALL2_OUT_CTRL_RES(vgPathTransformedBounds_impl,
                                               thread,
                                               VGPATHTRANSFORMEDBOUNDS_ID,
                                               RPC_HANDLE(vg_handle),
                                               values))) {
       /*
          no error occurred on the server side
       */
       *min_x = values[0];
       *min_y = values[1];
       *width = values[2];
       *height = values[3];
    }
 }
vgPointAlongPath()
VG_API_CALL void VG_API_ENTRY vgPointAlongPath (VGPath path, VGint startSegment, VGint numSegments, VGfloat distance, VGfloat * x, VGfloat * y, VGfloat * tangentX, VGfloat * tangentY)
Definition at line 3308 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VGfloat values[4];
    distance = clean_float(distance);
    if (!VG_GET_CLIENT_STATE(thread)) {
       return;
    }
    if ((x && !is_aligned_float(x)) || (y && !is_aligned_float(y)) ||
       (tangent_x && !is_aligned_float(tangent_x)) || (tangent_y && !is_aligned_float(tangent_y))) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return;
    }
    if (RPC_BOOLEAN_RES(RPC_CALL6_OUT_CTRL_RES(vgPointAlongPath_impl,
                                               thread,
                                               VGPOINTALONGPATH_ID,
                                               RPC_HANDLE(vg_handle),
                                               RPC_INT(segments_i), RPC_INT(segments_count),
                                               RPC_FLOAT(distance),
                                               RPC_BITFIELD(((x && y) << 0) | ((tangent_x && tangent_y) << 1)),
                                               values))) {
       /*
          no error occurred on the server side
       */
       if (x && y) {
          *x = values[0];
          *y = values[1];
       }
       if (tangent_x && tangent_y) {
          *tangent_x = values[2];
          *tangent_y = values[3];
       }
    }
 }
vgReadPixels()
VG_API_CALL void VG_API_ENTRY vgReadPixels (void * data, VGint dataStride, VGImageFormat dataFormat, VGint sx, VGint sy, VGint width, VGint height)
Definition at line 4292 of file vg_client.c.
Referenced by gx_priv_get_pixels().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    EGL_SURFACE_T *frame;
    VGint dst_x = 0, dst_y = 0;
    if (!VG_GET_CLIENT_STATE(thread)) {
       return;
    }
    if (!is_image_format(data_format)) {
       set_error(VG_UNSUPPORTED_IMAGE_FORMAT_ERROR);
       return;
    }
    if (!data || !is_aligned_image_format(data, data_format) ||
       ((height != 1) && !is_aligned_image_format((void *)(uintptr_t)data_stride, data_format)) ||
       (width <= 0) || (height <= 0)) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return;
    }
    frame = CLIENT_GET_THREAD_STATE()->openvg.draw;
    khrn_clip_rect2(
       &dst_x, &dst_y, &src_x, &src_y, &width, &height,
       0, 0, width, height,
       0, 0, frame->width, frame->height);
    if (width <= 0 || height <= 0) {
       return;
    }
    data = (VGubyte *)data + (dst_y * data_stride);
    #ifdef RPC_DIRECT
       RPC_CALL8(vgReadPixels_impl, thread, no_id,
          data, data_stride,
          data_format,
          dst_x,
          src_x, src_y,
          width, height);
    #else
       {
          VGuint log2_bpp = get_log2_image_format_bpp(data_format);
          VGuint line_size;
          VGuint first_mask;
          VGuint last_mask;
          VGuint chunk_height_max;
          data = (VGubyte *)data + ((dst_x << log2_bpp) >> 3);
          dst_x = ((dst_x << log2_bpp) & 0x7) >> log2_bpp;
          line_size = (((dst_x + width) << log2_bpp) + 0x7) >> 3;
          first_mask = (1 << (dst_x << log2_bpp)) - 1;
          last_mask = ~((2 << ((((dst_x + width) << log2_bpp) - 1) & 0x7)) - 1) & 0xff;
          /*
             split into KHDISPATCH_WORKSPACE_SIZE chunks (or thereabouts)
          */
          chunk_height_max = (line_size == 0) ? height : (KHDISPATCH_WORKSPACE_SIZE / line_size);
          vcos_assert((height == 0) || (chunk_height_max != 0));
          while (height != 0) {
             VGint chunk_height = _min(height, chunk_height_max);
             uint32_t message[] = {
                VGREADPIXELS_ID,
                RPC_UINT(line_size),
                RPC_ENUM(data_format),
                RPC_INT(dst_x),
                RPC_INT(src_x), RPC_INT(src_y),
                RPC_INT(width), RPC_INT(chunk_height) };
 #ifndef __SYMBIAN32__
             rpc_begin(thread);
 #endif
             rpc_send_ctrl_begin(thread, sizeof(message));
             rpc_send_ctrl_write(thread, message, sizeof(message));
             rpc_send_ctrl_end(thread);
             {
                uint32_t len[] = { line_size, data_stride, chunk_height, first_mask, last_mask };
                rpc_recv(thread, data, len, (RPC_RECV_FLAG_T)(RPC_RECV_FLAG_BULK | RPC_RECV_FLAG_BULK_SCATTER));
                data = (VGubyte *)data + (chunk_height * data_stride);
             }
 #ifndef __SYMBIAN32__
             rpc_end(thread);
 #endif
             height -= chunk_height;
             src_y += chunk_height;
          }
       }
    #endif
 }
vgRemovePathCapabilities()
VG_API_CALL void VG_API_ENTRY vgRemovePathCapabilities (VGPath path, VGbitfield capabilities)
Definition at line 2885 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_PATH_T *path;
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    platform_mutex_acquire(&state->shared_state->mutex);
    path = (VG_CLIENT_PATH_T *)lookup_object(state, vg_handle, VG_CLIENT_OBJECT_TYPE_PATH);
    if (path) {
       path_update_caps(path, path->caps & ~caps);
    }
    platform_mutex_release(&state->shared_state->mutex);
    RPC_CALL2(vgRemovePathCapabilities_impl,
              thread,
              VGREMOVEPATHCAPABILITIES_ID,
              RPC_HANDLE(vg_handle),
              RPC_BITFIELD(caps));
 }
vgRenderToMask()
VG_API_CALL void VG_API_ENTRY vgRenderToMask (VGPath path, VGbitfield paintModes, VGMaskOperation operation)
Definition at line 2593 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_STATE_T *state;
 #ifdef VG_NO_STROKING
    paint_modes &= ~VG_STROKE_PATH;
    if (!paint_modes) { return; }
 #endif
    state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    sync_matrix(state, VG_MATRIX_PATH_USER_TO_SURFACE);
    RPC_CALL3(vgRenderToMask_impl,
              thread,
              VGRENDERTOMASK_ID,
              RPC_HANDLE(vg_handle),
              RPC_BITFIELD(paint_modes),
              RPC_ENUM(operation));
 }
vgRotate()
VG_API_CALL void VG_API_ENTRY vgRotate (VGfloat angle)
Definition at line 2550 of file vg_client.c.
Referenced by render().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_STATE_T *state;
    VG_MAT3X3_SYNC_T *matrix_sync;
    angle = clean_float(angle);
    state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    matrix_sync = get_matrix_sync(state, state->matrix_mode);
    vg_mat3x3_postmul_rotate(&matrix_sync->client, angle * (PI / 180.0f));
 }
vgScale()
VG_API_CALL void VG_API_ENTRY vgScale (VGfloat sx, VGfloat sy)
Definition at line 2514 of file vg_client.c.
Referenced by graphics_bitblt(), and render().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_STATE_T *state;
    VG_MAT3X3_SYNC_T *matrix_sync;
    x = clean_float(x);
    y = clean_float(y);
    state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    matrix_sync = get_matrix_sync(state, state->matrix_mode);
    vg_mat3x3_postmul_scale(&matrix_sync->client, x, y);
 }
vgSeparableConvolve()
VG_API_CALL void VG_API_ENTRY vgSeparableConvolve (VGImage dst, VGImage src, VGint kernelWidth, VGint kernelHeight, VGint shiftX, VGint shiftY, const VGshort * kernelX, const VGshort * kernelY, VGfloat scale, VGfloat bias, VGTilingMode tilingMode)
Definition at line 4804 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    scale = clean_float(scale);
    bias = clean_float(bias);
    if (!VG_GET_CLIENT_STATE(thread)) {
       return;
    }
    if ((kernel_width <= 0) || (kernel_height <= 0) ||
       (kernel_width > VG_CONFIG_MAX_SEPARABLE_KERNEL_SIZE) || (kernel_height > VG_CONFIG_MAX_SEPARABLE_KERNEL_SIZE) ||
       !kernel_x || !is_aligned_short(kernel_x) || !kernel_y || !is_aligned_short(kernel_y)) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return;
    }
    #ifdef RPC_DIRECT
       RPC_CALL11(vgSeparableConvolve_impl, thread, no_id,
          dst_vg_handle, src_vg_handle,
          kernel_width, kernel_height,
          shift_x, shift_y,
          kernel_x, kernel_y,
          scale, bias,
          tiling_mode);
    #else
       {
          uint32_t message[] = {
             VGSEPARABLECONVOLVE_ID,
             RPC_HANDLE(dst_vg_handle), RPC_HANDLE(src_vg_handle),
             RPC_INT(kernel_width), RPC_INT(kernel_height),
             RPC_INT(shift_x), RPC_INT(shift_y),
             RPC_FLOAT(scale), RPC_FLOAT(bias),
             RPC_ENUM(tiling_mode) };
          VGuint kernel_x_size = kernel_width * sizeof(VGshort);
          VGuint kernel_y_size = kernel_height * sizeof(VGshort);
          rpc_send_ctrl_begin(thread, sizeof(message) + rpc_pad_ctrl(kernel_x_size) + rpc_pad_ctrl(kernel_y_size));
          rpc_send_ctrl_write(thread, message, sizeof(message));
          rpc_send_ctrl_write(thread, (uint32_t *)kernel_x, kernel_x_size);
          rpc_send_ctrl_write(thread, (uint32_t *)kernel_y, kernel_y_size);
          rpc_send_ctrl_end(thread);
       }
    #endif
 }
vgSetColor()
VG_API_CALL void VG_API_ENTRY vgSetColor (VGPaint paint, VGuint rgba)
Definition at line 3581 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_STATE_T *state;
    VG_CLIENT_PAINT_T *paint;
    rgba = khrn_color_rgba_flip(rgba);
    state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    platform_mutex_acquire(&state->shared_state->mutex);
    paint = (VG_CLIENT_PAINT_T *)lookup_object(state, vg_handle, VG_CLIENT_OBJECT_TYPE_PAINT);
    if (!paint) {
       set_error(VG_BAD_HANDLE_ERROR);
       platform_mutex_release(&state->shared_state->mutex);
       return;
    }
    if (color_floats_to_rgba_clean(paint->color) != rgba) {
       set_parameter_iv_server(vg_handle, VG_CLIENT_OBJECT_TYPE_PAINT, VG_PAINT_COLOR, 1, (const VGint *)&rgba);
    }
    khrn_color_rgba_to_floats(paint->color, rgba);
    platform_mutex_release(&state->shared_state->mutex);
 }
vgSetf()
VG_API_CALL void VG_API_ENTRY vgSetf (VGParamType type, VGfloat value)
Definition at line 1797 of file vg_client.c.
Referenced by PS_render().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    if (is_vector_param_type(param_type)) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return;
    }
    set_ifv(thread, state, param_type, 1, true, &value);
 }
vgSetfv()
VG_API_CALL void VG_API_ENTRY vgSetfv (VGParamType type, VGint count, const VGfloat * values)
Definition at line 1833 of file vg_client.c.
Referenced by gx_priv_resource_fill(), and render().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    /*
     * Verify the arguments, and report an error if any of the following holds:
     *   - 'count' is negative
     *   - 'count' is greater than zero and 'values' is NULL
     *   - 'values' is non-NULL but not aligned on an float boundary
     *
     * If 'count' is zero, then 'values' will not (and must not) be dereferenced
     * in this function or any of it's descendents.  The OpenVG Specification
     * Version 1.1, section 5.2 Setting and Querying Context Parameter Values
     * states:
     *
     *   "If the count parameter is 0, the pointer argument is not dereferenced.
     *    For example, the call vgSet(VG_STROKE_DASH_PATTERN, 0, (void *) 0)
     *    sets the dash pattern to a zero-length array (which has the effect of
     *    disabling dashing) without dereferencing the third parameter."
     *
     * Automatic checking tools such as Coverity may flag this case ('values'
     * not verified non-NULL when 'count' is zero) as a potential NULL pointer
     * dereference. In this case it is not.
     */
    if ((count < 0) || ((count > 0) && !values) || (values && !is_aligned_float(values))) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return;
    }
    set_ifv(thread, state, param_type, count, true, values);
 }
vgSetGlyphToImage()
VG_API_CALL void VG_API_ENTRY vgSetGlyphToImage (VGFont font, VGuint glyphIndex, VGImage image, VGfloat glyphOrigin[2], VGfloat escapement[2])
Definition at line 4530 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
 #if EGL_BRCM_global_image && EGL_KHR_image
    VG_CLIENT_FONT_T *font;
    VG_CLIENT_IMAGE_T *image;
 #endif
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    if (!glyph_origin || !is_aligned_float(glyph_origin) ||
       !escapement || !is_aligned_float(escapement)) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return;
    }
 #if EGL_BRCM_global_image && EGL_KHR_image
    platform_mutex_acquire(&state->shared_state->mutex);
    font = (VG_CLIENT_FONT_T *)lookup_object(state, vg_handle, VG_CLIENT_OBJECT_TYPE_FONT);
    image = (image_vg_handle == VG_INVALID_HANDLE) ? NULL : (VG_CLIENT_IMAGE_T *)lookup_object(state, image_vg_handle, VG_CLIENT_OBJECT_TYPE_IMAGE);
    if (font && ((image_vg_handle == VG_INVALID_HANDLE) || image)) {
       if (image && (image->global_image_id[0] || image->global_image_id[1])) {
          if (!khrn_global_image_map_insert(&font->glyph_global_images, glyph_id,
             image->global_image_id[0] | ((uint64_t)image->global_image_id[1] << 32))) {
             set_error(VG_OUT_OF_MEMORY_ERROR);
             platform_mutex_release(&state->shared_state->mutex);
             return;
          }
       } else {
          khrn_global_image_map_delete(&font->glyph_global_images, glyph_id);
       }
    }
    platform_mutex_release(&state->shared_state->mutex);
 #endif
    RPC_CALL7(vgSetGlyphToImage_impl,
              thread,
              VGSETGLYPHTOIMAGE_ID,
              RPC_HANDLE(vg_handle),
              RPC_UINT(glyph_id),
              RPC_HANDLE(image_vg_handle),
              RPC_FLOAT(clean_float(glyph_origin[0])), RPC_FLOAT(clean_float(glyph_origin[1])),
              RPC_FLOAT(clean_float(escapement[0])), RPC_FLOAT(clean_float(escapement[1])));
 }
vgSetGlyphToPath()
VG_API_CALL void VG_API_ENTRY vgSetGlyphToPath (VGFont font, VGuint glyphIndex, VGPath path, VGboolean isHinted, VGfloat glyphOrigin[2], VGfloat escapement[2])
Definition at line 4486 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
 #if EGL_BRCM_global_image && EGL_KHR_image
    VG_CLIENT_FONT_T *font;
 #endif
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    if (!glyph_origin || !is_aligned_float(glyph_origin) ||
       !escapement || !is_aligned_float(escapement)) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return;
    }
 #if EGL_BRCM_global_image && EGL_KHR_image
    platform_mutex_acquire(&state->shared_state->mutex);
    font = (VG_CLIENT_FONT_T *)lookup_object(state, vg_handle, VG_CLIENT_OBJECT_TYPE_FONT);
    if (font && ((path_vg_handle == VG_INVALID_HANDLE) || lookup_object(state, path_vg_handle, VG_CLIENT_OBJECT_TYPE_PATH))) {
       khrn_global_image_map_delete(&font->glyph_global_images, glyph_id);
    }
    platform_mutex_release(&state->shared_state->mutex);
 #endif
    RPC_CALL8(vgSetGlyphToPath_impl,
              thread,
              VGSETGLYPHTOPATH_ID,
              RPC_HANDLE(vg_handle),
              RPC_UINT(glyph_id),
              RPC_HANDLE(path_vg_handle),
              RPC_BOOLEAN(clean_boolean(is_hinted)),
              RPC_FLOAT(clean_float(glyph_origin[0])), RPC_FLOAT(clean_float(glyph_origin[1])),
              RPC_FLOAT(clean_float(escapement[0])), RPC_FLOAT(clean_float(escapement[1])));
 }
vgSeti()
VG_API_CALL void VG_API_ENTRY vgSeti (VGParamType type, VGint value)
Definition at line 1815 of file vg_client.c.
Referenced by graphics_bitblt(), gx_priv_resource_fill(), and PS_render().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    if (is_vector_param_type(param_type)) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return;
    }
    set_ifv(thread, state, param_type, 1, false, &value);
 }
vgSetiv()
VG_API_CALL void VG_API_ENTRY vgSetiv (VGParamType type, VGint count, const VGint * values)
Definition at line 1872 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    /*
     * Verify the arguments, and report an error if any of the following holds:
     *   - 'count' is negative
     *   - 'count' is greater than zero and 'values' is NULL
     *   - 'values' is non-NULL but not aligned on an integer boundary
     *
     * If 'count' is zero, then 'values' will not (and must not) be dereferenced
     * in this function or any of it's descendents.  See the comment in vgSetfv()
     * above for more detail.
     *
     * Automatic checking tools such as Coverity may flag this case ('values'
     * not verified non-NULL when 'count' is zero) as a potential NULL pointer
     * dereference. In this case it is not.
     */
    if ((count < 0) || ((count > 0) && !values) || (values && !is_aligned_int(values))) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return;
    }
    set_ifv(thread, state, param_type, count, false, values);
 }
vgSetPaint()
VG_API_CALL void VG_API_ENTRY vgSetPaint (VGPaint paint, VGbitfield paintModes)
Definition at line 3524 of file vg_client.c.
Referenced by graphics_bitblt(), gx_fill_gradient(), gx_render_arrowhead(), and PS_render().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    if (!is_paint_modes(paint_modes)) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return;
    }
    platform_mutex_acquire(&state->shared_state->mutex);
    if ((vg_handle != VG_INVALID_HANDLE) &&
       !lookup_object(state, vg_handle, VG_CLIENT_OBJECT_TYPE_PAINT)) {
       set_error(VG_BAD_HANDLE_ERROR);
       platform_mutex_release(&state->shared_state->mutex);
       return;
    }
    platform_mutex_release(&state->shared_state->mutex);
    if (((paint_modes & VG_FILL_PATH) && (state->fill_paint != vg_handle)) ||
       ((paint_modes & VG_STROKE_PATH) && (state->stroke_paint != vg_handle))) {
       if (paint_modes & VG_FILL_PATH) {
          state->fill_paint = vg_handle;
       }
       if (paint_modes & VG_STROKE_PATH) {
          state->stroke_paint = vg_handle;
       }
       RPC_CALL2(vgSetPaint_impl,
                 thread,
                 VGSETPAINT_ID,
                 RPC_HANDLE(vg_handle),
                 RPC_BITFIELD(paint_modes));
    }
 }
vgSetParameterf()
VG_API_CALL void VG_API_ENTRY vgSetParameterf (VGHandle object, VGint paramType, VGfloat value)
Definition at line 2048 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    if (is_vector_object_param_type(param_type)) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return;
    }
    set_parameter_ifv(thread, state, vg_handle, param_type, 1, true, &value);
 }
vgSetParameterfv()
VG_API_CALL void VG_API_ENTRY vgSetParameterfv (VGHandle object, VGint paramType, VGint count, const VGfloat * values)
Definition at line 2086 of file vg_client.c.
Referenced by graphics_bitblt(), gx_create_gradient(), gx_fill_gradient(), gx_render_arrowhead(), and PS_construct().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    /*
     * Verify the arguments, and report an error if any of the following holds:
     *   - 'count' is negative
     *   - 'count' is greater than zero and 'values' is NULL
     *   - 'values' is non-NULL but not aligned on an float boundary
     *
     * If 'count' is zero, then 'values' will not (and must not) be dereferenced
     * in this function or any of it's descendents.  See the comment in vgSetfv()
     * above for more detail.
     *
     * Automatic checking tools such as Coverity may flag this case ('values'
     * not verified non-NULL when 'count' is zero) as a potential NULL pointer
     * dereference. In this case it is not.
     */
    if ((count < 0) || ((count > 0) && !values) || (values && !is_aligned_float(values))) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return;
    }
    set_parameter_ifv(thread, state, vg_handle, param_type, count, true, values);
 }
vgSetParameteri()
VG_API_CALL void VG_API_ENTRY vgSetParameteri (VGHandle object, VGint paramType, VGint value)
Definition at line 2067 of file vg_client.c.
Referenced by gx_create_gradient(), and PS_construct().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    if (is_vector_object_param_type(param_type)) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return;
    }
    set_parameter_ifv(thread, state, vg_handle, param_type, 1, false, &value);
 }
vgSetParameteriv()
VG_API_CALL void VG_API_ENTRY vgSetParameteriv (VGHandle object, VGint paramType, VGint count, const VGint * values)
Definition at line 2120 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    /*
     * Verify the arguments, and report an error if any of the following holds:
     *   - 'count' is negative
     *   - 'count' is greater than zero and 'values' is NULL
     *   - 'values' is non-NULL but not aligned on an integer boundary
     *
     * If 'count' is zero, then 'values' will not (and must not) be dereferenced
     * in this function or any of it's descendents.  See the comment in vgSetfv()
     * above for more detail.
     *
     * Automatic checking tools such as Coverity may flag this case ('values'
     * not verified non-NULL when 'count' is zero) as a potential NULL pointer
     * dereference. In this case it is not.
     */
    if ((count < 0) || ((count > 0) && !values) || (values && !is_aligned_int(values))) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return;
    }
    set_parameter_ifv(thread, state, vg_handle, param_type, count, false, values);
 }
vgSetPixels()
VG_API_CALL void VG_API_ENTRY vgSetPixels (VGint dx, VGint dy, VGImage src, VGint sx, VGint sy, VGint width, VGint height)
Definition at line 4158 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    if (state->render_callback)
       state->render_callback();
    RPC_CALL7(vgSetPixels_impl,
              thread,
              VGSETPIXELS_ID,
              RPC_INT(dst_x), RPC_INT(dst_y),
              RPC_HANDLE(src_vg_handle), RPC_INT(src_x), RPC_INT(src_y),
              RPC_INT(width), RPC_INT(height));
 }
vgShear()
VG_API_CALL void VG_API_ENTRY vgShear (VGfloat shx, VGfloat shy)
Definition at line 2532 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_STATE_T *state;
    VG_MAT3X3_SYNC_T *matrix_sync;
    x = clean_float(x);
    y = clean_float(y);
    state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    matrix_sync = get_matrix_sync(state, state->matrix_mode);
    vg_mat3x3_postmul_shear(&matrix_sync->client, x, y);
 }
vgTransformPath()
VG_API_CALL void VG_API_ENTRY vgTransformPath (VGPath dstPath, VGPath srcPath)
Definition at line 3174 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_PATH_T *dst;
    VG_CLIENT_PATH_T *src;
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    platform_mutex_acquire(&state->shared_state->mutex);
    dst = (VG_CLIENT_PATH_T *)lookup_object(state, dst_vg_handle, VG_CLIENT_OBJECT_TYPE_PATH);
    src = (VG_CLIENT_PATH_T *)lookup_object(state, src_vg_handle, VG_CLIENT_OBJECT_TYPE_PATH);
    if (dst && src &&
       (dst->caps & VG_PATH_CAPABILITY_TRANSFORM_TO) && (src->caps & VG_PATH_CAPABILITY_TRANSFORM_FROM) &&
       need_path_segments(dst->caps)) {
       VGuint segments_count = src->segments.size;
       if (!khrn_vector_extend(&dst->segments, segments_count)) {
          set_error(VG_OUT_OF_MEMORY_ERROR);
          platform_mutex_release(&state->shared_state->mutex);
          return;
       }
       {
          VGubyte *dst_segments = (VGubyte *)dst->segments.data + (dst->segments.size - segments_count);
          const VGubyte *src_segments = (const VGubyte *)src->segments.data;
          for (; segments_count != 0; ++dst_segments, ++src_segments, --segments_count) {
             VGuint segment = *src_segments;
             if (((segment & ~VG_RELATIVE) == VG_HLINE_TO) || ((segment & ~VG_RELATIVE) == VG_VLINE_TO)) {
                segment = VG_LINE_TO | (segment & VG_RELATIVE);
             }
             /*
                on the server, we also flip arc types if the determinant of the path
                user to surface matrix is negative, but we don't actually care about
                the particular arc type on the client
             */
             *dst_segments = (VGubyte)segment;
          }
       }
    }
    platform_mutex_release(&state->shared_state->mutex);
    sync_matrix(state, VG_MATRIX_PATH_USER_TO_SURFACE);
    RPC_CALL2(vgTransformPath_impl,
              thread,
              VGTRANSFORMPATH_ID,
              RPC_HANDLE(dst_vg_handle),
              RPC_HANDLE(src_vg_handle));
 }
vgTranslate()
VG_API_CALL void VG_API_ENTRY vgTranslate (VGfloat tx, VGfloat ty)
Definition at line 2496 of file vg_client.c.
Referenced by graphics_bitblt(), and render().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    VG_CLIENT_STATE_T *state;
    VG_MAT3X3_SYNC_T *matrix_sync;
    x = clean_float(x);
    y = clean_float(y);
    state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    matrix_sync = get_matrix_sync(state, state->matrix_mode);
    vg_mat3x3_postmul_translate(&matrix_sync->client, x, y);
 }
vgWritePixels()
VG_API_CALL void VG_API_ENTRY vgWritePixels (const void * data, VGint dataStride, VGImageFormat dataFormat, VGint dx, VGint dy, VGint width, VGint height)
Definition at line 4180 of file vg_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    EGL_SURFACE_T *frame;
    VGint src_x = 0, src_y = 0;
    VG_CLIENT_STATE_T *state = VG_GET_CLIENT_STATE(thread);
    if (!state) {
       return;
    }
    if (!is_image_format(data_format)) {
       set_error(VG_UNSUPPORTED_IMAGE_FORMAT_ERROR);
       return;
    }
    if (!data || !is_aligned_image_format(data, data_format) ||
       ((height != 1) && !is_aligned_image_format((void *)(uintptr_t)data_stride, data_format)) ||
       (width <= 0) || (height <= 0)) {
       set_error(VG_ILLEGAL_ARGUMENT_ERROR);
       return;
    }
    frame = CLIENT_GET_THREAD_STATE()->openvg.draw;
    khrn_clip_rect2(
       &dst_x, &dst_y, &src_x, &src_y, &width, &height,
       0, 0, frame->width, frame->height,
       0, 0, width, height);
    if (width <= 0 || height <= 0) {
       return;
    }
    data = (const VGubyte *)data + (src_y * data_stride);
    if (state->render_callback)
       state->render_callback();
    #ifdef RPC_DIRECT
       RPC_CALL8(vgWritePixels_impl, thread, no_id,
          data, data_stride,
          data_format,
          src_x,
          dst_x, dst_y,
          width, height);
    #else
       {
          VGuint log2_bpp = get_log2_image_format_bpp(data_format);
          VGuint line_size;
          VGuint chunk_height_max;
          data = (const VGubyte *)data + ((src_x << log2_bpp) >> 3);
          src_x = ((src_x << log2_bpp) & 0x7) >> log2_bpp;
          line_size = (((src_x + width) << log2_bpp) + 0x7) >> 3;
          /*
             split into KHDISPATCH_WORKSPACE_SIZE chunks (or thereabouts)
          */
          chunk_height_max = (line_size == 0) ? height : (KHDISPATCH_WORKSPACE_SIZE / line_size);
          vcos_assert((height == 0) || (chunk_height_max != 0));
          while (height != 0) {
             VGint chunk_height = _min(height, chunk_height_max);
             uint32_t message[] = {
                VGWRITEPIXELS_ID,
                RPC_UINT(line_size),
                RPC_ENUM(data_format),
                RPC_INT(src_x),
                RPC_INT(dst_x), RPC_INT(dst_y),
                RPC_INT(width), RPC_INT(chunk_height) };
             rpc_begin(thread);
             rpc_send_ctrl_begin(thread, sizeof(message));
             rpc_send_ctrl_write(thread, message, sizeof(message));
             rpc_send_ctrl_end(thread);
             rpc_send_bulk_gather(thread, data, line_size, data_stride, chunk_height);
             data = (const VGubyte *)data + (chunk_height * data_stride);
             rpc_end(thread);
             height -= chunk_height;
             dst_y += chunk_height;
          }
       }
    #endif
 }