VideoCore Library: interface/mmal/openmaxil/mmalomx_buffer.c File Reference
mmalomx_buffer.c File Reference
#include "mmalomx.h"
#include "mmalomx_buffer.h"
#include "mmalomx_commands.h"
#include "mmalomx_marks.h"
#include "mmalomx_logging.h"
#include <util/mmal_util.h>
Functions
OMX_ERRORTYPE mmalomx_buffer_send (MMALOMX_COMPONENT_T *component, OMX_BUFFERHEADERTYPE *omx_buffer, OMX_DIRTYPE direction)
OMX_ERRORTYPE mmalomx_buffer_return (MMALOMX_PORT_T *port, MMAL_BUFFER_HEADER_T *mmal_buffer)
Function Documentation
mmalomx_buffer_return()
OMX_ERRORTYPE mmalomx_buffer_return (MMALOMX_PORT_T * port, MMAL_BUFFER_HEADER_T * mmal_buffer)
Definition at line 187 of file mmalomx_buffer.c.
References MMAL_BUFFER_HEADER_T::cmd, MMALOMX_PORT_T::component, and MMAL_BUFFER_HEADER_T::user_data.
 {
    MMALOMX_COMPONENT_T *component = port->component;
    OMX_BUFFERHEADERTYPE *omx_buffer = (OMX_BUFFERHEADERTYPE *)mmal_buffer->user_data;
    MMAL_BOOL_T signal;
    if (mmal_buffer->cmd)
    {
       mmalomx_buffer_event(port, mmal_buffer);
       mmal_buffer_header_release(mmal_buffer);
       return OMX_ErrorNone;
    }
    if (ENABLE_MMAL_EXTRA_LOGGING)
       LOG_TRACE("hComponent %p, port %i, pBuffer %p", component,
                 port->index, omx_buffer);
    vcos_assert(omx_buffer->pBuffer == mmal_buffer->data);
    mmalil_buffer_header_to_omx(omx_buffer, mmal_buffer);
    mmal_buffer_header_release(mmal_buffer);
    if ((omx_buffer->nFlags & OMX_BUFFERFLAG_EOS) && port->direction == OMX_DirOutput)
    {
       mmalomx_callback_event_handler(component, OMX_EventBufferFlag,
                                      port->index, omx_buffer->nFlags, NULL);
    }
    mmalomx_mark_process_outgoing(component, port, omx_buffer);
    if (port->direction == OMX_DirInput)
       component->callbacks.EmptyBufferDone((OMX_HANDLETYPE)&component->omx,
          component->callbacks_data, omx_buffer );
    else
       component->callbacks.FillBufferDone((OMX_HANDLETYPE)&component->omx,
          component->callbacks_data, omx_buffer );
    MMALOMX_LOCK_PORT(component, port);
    signal = port->actions & MMALOMX_ACTION_CHECK_FLUSHED;
    port->buffers_in_transit--;
    MMALOMX_UNLOCK_PORT(component, port);
    if (signal)
       mmalomx_commands_actions_signal(component);
    return OMX_ErrorNone;
 }
mmalomx_buffer_send()
OMX_ERRORTYPE mmalomx_buffer_send (MMALOMX_COMPONENT_T * component, OMX_BUFFERHEADERTYPE * omx_buffer, OMX_DIRTYPE direction)
Definition at line 37 of file mmalomx_buffer.c.
References MMALOMX_PORT_T::buffers_in_transit, MMALOMX_PORT_T::direction, MMALOMX_PORT_T::enabled, error(), index, LOG_ERROR, MMALOMX_PORT_T::mmal, mmal_port_send_buffer(), mmal_queue_get(), mmal_queue_put_back(), MMAL_SUCCESS, mmalil_buffer_header_to_mmal(), mmalil_error_to_omx(), MMALOMX_LOCK_PORT, mmalomx_mark_process_incoming(), MMALOMX_UNLOCK_PORT, OMX_BUFFERHEADERTYPE::nAllocLen, MMAL_PORT_T::name, OMX_BUFFERHEADERTYPE::nFilledLen, OMX_BUFFERHEADERTYPE::nInputPortIndex, OMX_BUFFERHEADERTYPE::nOffset, OMX_BUFFERHEADERTYPE::nOutputPortIndex, OMX_BUFFERHEADERTYPE::nSize, OMX_DirInput, OMX_ErrorBadParameter, OMX_ErrorBadPortIndex, OMX_ErrorIncorrectStateOperation, OMX_ErrorInvalidComponent, OMX_ErrorInvalidState, OMX_ErrorNone, OMX_ErrorUndefined, OMX_StateExecuting, OMX_StateInvalid, OMX_StatePause, MMALOMX_PORT_T::pool, MMAL_COMPONENT_T::port, MMALOMX_COMPONENT_T::ports, MMALOMX_COMPONENT_T::ports_num, MMAL_POOL_T::queue, MMALOMX_COMPONENT_T::state, status, MMAL_BUFFER_HEADER_T::user_data, and vcos_verify.
 {
    OMX_ERRORTYPE status = OMX_ErrorNone;
    MMAL_BUFFER_HEADER_T *mmal_buffer;
    MMAL_STATUS_T mmal_status;
    MMALOMX_PORT_T *port;
    unsigned int index;
    /* Sanity checks */
    if (!component)
       return OMX_ErrorInvalidComponent;
    if (component->state == OMX_StateInvalid)
       return OMX_ErrorInvalidState;
    if (!omx_buffer || omx_buffer->nSize != sizeof(OMX_BUFFERHEADERTYPE) ||
        omx_buffer->nOffset + omx_buffer->nFilledLen > omx_buffer->nAllocLen)
       return OMX_ErrorBadParameter;
    index = direction == OMX_DirInput ? omx_buffer->nInputPortIndex : omx_buffer->nOutputPortIndex;
    if (index >= component->ports_num)
       return OMX_ErrorBadPortIndex;
    port = &component->ports[index];
    if (port->direction != direction)
       return OMX_ErrorBadPortIndex;
    MMALOMX_LOCK_PORT(component, port);
    if (component->state != OMX_StatePause && component->state != OMX_StateExecuting)
       status = OMX_ErrorIncorrectStateOperation;
    if (!port->enabled  /* FIXME: || flushing || pending idle */)
       status = OMX_ErrorIncorrectStateOperation;
    if (status != OMX_ErrorNone)
       goto error;
    mmal_buffer = mmal_queue_get( port->pool->queue );
    if (!vcos_verify(mmal_buffer)) /* Should never happen */
    {
       status = OMX_ErrorUndefined;
       goto error;
    }
    mmalomx_mark_process_incoming(component, port, omx_buffer);
    mmal_buffer->user_data = (void *)omx_buffer;
    mmalil_buffer_header_to_mmal(mmal_buffer, omx_buffer);
    mmal_status = mmal_port_send_buffer(port->mmal, mmal_buffer);
    if (!vcos_verify(mmal_status == MMAL_SUCCESS))
    {
       LOG_ERROR("failed to send buffer on %s", port->mmal->name);
       mmal_queue_put_back( port->pool->queue, mmal_buffer );
       status = mmalil_error_to_omx(mmal_status);
    }
    else
    {
       port->buffers_in_transit++;
    }
 error:
    MMALOMX_UNLOCK_PORT(component, port);
    return status;
 }