VideoCore Library: containers/net/net_sockets_priv.h File Reference
net_sockets_priv.h File Reference
#include "net_sockets.h"
#include "net_sockets_bsd.h"
Enumerations
enum vc_container_net_type_t { STREAM_CLIENT = 0, STREAM_SERVER, DATAGRAM_SENDER, DATAGRAM_RECEIVER }
Functions
vc_container_net_status_t vc_container_net_private_init (void)
void vc_container_net_private_deinit (void)
vc_container_net_status_t vc_container_net_private_last_error (void)
void vc_container_net_private_close (SOCKET_T sock)
void vc_container_net_private_set_reusable (SOCKET_T sock, bool enable)
size_t vc_container_net_private_maximum_datagram_size (SOCKET_T sock)
Enumeration Type Documentation
vc_container_net_type_t
enum vc_container_net_type_t
Enumerator
STREAM_CLIENT
TCP client
STREAM_SERVER
TCP server
DATAGRAM_SENDER
UDP sender
DATAGRAM_RECEIVER
UDP receiver
Definition at line 43 of file net_sockets_priv.h.
 {
    STREAM_CLIENT = 0,
    STREAM_SERVER,
    DATAGRAM_SENDER,
    DATAGRAM_RECEIVER
 } vc_container_net_type_t;
Function Documentation
vc_container_net_private_close()
void vc_container_net_private_close (SOCKET_T sock)
Implementation-specific internal socket close.
Parameters
sock Internal socket to be closed.
Definition at line 97 of file net_sockets_bsd.c.
Referenced by vc_container_net_close().
 {
    close(sock);
 }
vc_container_net_private_deinit()
void vc_container_net_private_deinit (void)
Perform implementation-specific per-socket deinitialization. This function is always called once for each successful call to socket_private_init().
Definition at line 91 of file net_sockets_bsd.c.
Referenced by vc_container_net_close(), and vc_container_net_open().
 {
    /* No additional deinitialization required */
 }
vc_container_net_private_init()
vc_container_net_status_t vc_container_net_private_init (void)
Perform implementation-specific per-socket initialization.
Returns
VC_CONTAINER_NET_SUCCESS or one of the error codes on failure.
Definition at line 84 of file net_sockets_bsd.c.
References VC_CONTAINER_NET_SUCCESS.
Referenced by vc_container_net_accept(), and vc_container_net_open().
 {
    /* No additional initialization required */
    return VC_CONTAINER_NET_SUCCESS;
 }
vc_container_net_private_last_error()
vc_container_net_status_t vc_container_net_private_last_error (void)
Return the last error from the socket implementation.
Definition at line 46 of file net_sockets_bsd.c.
References VC_CONTAINER_NET_ERROR_ACCESS_DENIED, VC_CONTAINER_NET_ERROR_CONNECTION_LOST, VC_CONTAINER_NET_ERROR_CONNECTION_REFUSED, VC_CONTAINER_NET_ERROR_GENERAL, VC_CONTAINER_NET_ERROR_IN_PROGRESS, VC_CONTAINER_NET_ERROR_IN_USE, VC_CONTAINER_NET_ERROR_INVALID_PARAMETER, VC_CONTAINER_NET_ERROR_INVALID_SOCKET, VC_CONTAINER_NET_ERROR_NETWORK, VC_CONTAINER_NET_ERROR_NO_MEMORY, VC_CONTAINER_NET_ERROR_NOT_CONNECTED, VC_CONTAINER_NET_ERROR_TIMED_OUT, VC_CONTAINER_NET_ERROR_TOO_BIG, and VC_CONTAINER_NET_ERROR_WOULD_BLOCK.
Referenced by vc_container_net_accept(), vc_container_net_listen(), vc_container_net_open(), and vc_container_net_write().
 {
    switch (errno)
    {
    case EACCES:               return VC_CONTAINER_NET_ERROR_ACCESS_DENIED;
    case EFAULT:               return VC_CONTAINER_NET_ERROR_INVALID_PARAMETER;
    case EINVAL:               return VC_CONTAINER_NET_ERROR_INVALID_PARAMETER;
    case EMFILE:               return VC_CONTAINER_NET_ERROR_TOO_BIG;
    case EWOULDBLOCK:          return VC_CONTAINER_NET_ERROR_WOULD_BLOCK;
    case EINPROGRESS:          return VC_CONTAINER_NET_ERROR_IN_PROGRESS;
    case EALREADY:             return VC_CONTAINER_NET_ERROR_IN_PROGRESS;
    case EADDRINUSE:           return VC_CONTAINER_NET_ERROR_IN_USE;
    case EADDRNOTAVAIL:        return VC_CONTAINER_NET_ERROR_INVALID_PARAMETER;
    case ENETDOWN:             return VC_CONTAINER_NET_ERROR_NETWORK;
    case ENETUNREACH:          return VC_CONTAINER_NET_ERROR_NETWORK;
    case ENETRESET:            return VC_CONTAINER_NET_ERROR_CONNECTION_LOST;
    case ECONNABORTED:         return VC_CONTAINER_NET_ERROR_CONNECTION_LOST;
    case ECONNRESET:           return VC_CONTAINER_NET_ERROR_CONNECTION_LOST;
    case ENOBUFS:              return VC_CONTAINER_NET_ERROR_NO_MEMORY;
    case ENOTCONN:             return VC_CONTAINER_NET_ERROR_NOT_CONNECTED;
    case ESHUTDOWN:            return VC_CONTAINER_NET_ERROR_CONNECTION_LOST;
    case ETIMEDOUT:            return VC_CONTAINER_NET_ERROR_TIMED_OUT;
    case ECONNREFUSED:         return VC_CONTAINER_NET_ERROR_CONNECTION_REFUSED;
    case ELOOP:                return VC_CONTAINER_NET_ERROR_INVALID_PARAMETER;
    case ENAMETOOLONG:         return VC_CONTAINER_NET_ERROR_INVALID_PARAMETER;
    case EHOSTDOWN:            return VC_CONTAINER_NET_ERROR_NETWORK;
    case EHOSTUNREACH:         return VC_CONTAINER_NET_ERROR_NETWORK;
    case EUSERS:               return VC_CONTAINER_NET_ERROR_NO_MEMORY;
    case EDQUOT:               return VC_CONTAINER_NET_ERROR_NO_MEMORY;
    case ESTALE:               return VC_CONTAINER_NET_ERROR_INVALID_SOCKET;
    /* All other errors are unexpected, so just map to a general purpose error code. */
    default:
       return VC_CONTAINER_NET_ERROR_GENERAL;
    }
 }
vc_container_net_private_maximum_datagram_size()
size_t vc_container_net_private_maximum_datagram_size (SOCKET_T sock)
Query the maximum datagram size for the socket.
Parameters
sock The socket to query.
Returns
The maximum supported datagram size on the socket.
Definition at line 111 of file net_sockets_bsd.c.
References DEFAULT_MAXIMUM_DATAGRAM_SIZE, and void().
Referenced by vc_container_net_accept().
 {
    (void)sock;
    /* No easy way to determine this, just use the default. */
    return DEFAULT_MAXIMUM_DATAGRAM_SIZE;
 }
vc_container_net_private_set_reusable()
void vc_container_net_private_set_reusable (SOCKET_T sock, bool enable)
Enable or disable socket address reusability.
Parameters
sock Internal socket to be closed.
enable True to enable reusability, false to clear it.
Definition at line 103 of file net_sockets_bsd.c.
References void().
Referenced by vc_container_net_open().
 {
    int opt = enable ? 1 : 0;
    (void)setsockopt(sock, SOL_SOCKET, SO_REUSEADDR, (const char *)&opt, sizeof(opt));
 }