VideoCore Library: host_applications/android/apps/vidtex/svp.h File Reference
svp.h File Reference
Classes
struct SVP_CALLBACKS_T
struct SVP_OPTS_T
struct SVP_STATS_T
Macros
#define SVP_STOP_USER (1 << 0)
#define SVP_STOP_EOS (1 << 1)
#define SVP_STOP_ERROR (1 << 2)
#define SVP_STOP_TIMEUP (1 << 3)
Typedefs
typedef struct SVP_CALLBACKS_T SVP_CALLBACKS_T
typedef struct SVP_OPTS_T SVP_OPTS_T
typedef struct SVP_STATS_T SVP_STATS_T
typedef struct SVP_T SVP_T
Functions
SVP_T * svp_create (const char *uri, SVP_CALLBACKS_T *callbacks, const SVP_OPTS_T *opts)
void svp_destroy (SVP_T *svp)
int svp_start (SVP_T *svp)
void svp_stop (SVP_T *svp)
void svp_get_stats (SVP_T *svp, SVP_STATS_T *stats)
Detailed Description
Simple video player using MMAL. Uses MMAL container reader plus video decode component, and provides callback to retrieve buffers of decoded video frames.
Thread-safety: The public API functions must be called from the same thread for a given SVP_T instance. The user is notified of decoded frames and other events from a separate thread, started by svp_start().
Definition in file svp.h.
Macro Definition Documentation
SVP_STOP_EOS
#define SVP_STOP_EOS (1 << 1)
Stop on end-of-stream
Definition at line 49 of file svp.h.
SVP_STOP_ERROR
#define SVP_STOP_ERROR (1 << 2)
Stop on error
Definition at line 51 of file svp.h.
SVP_STOP_TIMEUP
#define SVP_STOP_TIMEUP (1 << 3)
Stop on timer
Definition at line 53 of file svp.h.
SVP_STOP_USER
#define SVP_STOP_USER (1 << 0)
Flags indicating reason for processing stop Stop on to user request
Definition at line 47 of file svp.h.
Typedef Documentation
SVP_CALLBACKS_T
typedef struct SVP_CALLBACKS_T SVP_CALLBACKS_T
Callback functions and context for player to communicate asynchronous data and events to user.
SVP_OPTS_T
typedef struct SVP_OPTS_T SVP_OPTS_T
Options to SVP playback
SVP_STATS_T
typedef struct SVP_STATS_T SVP_STATS_T
Playback stats
SVP_T
typedef struct SVP_T SVP_T
Simple Video Player instance. Opaque structure.
Definition at line 99 of file svp.h.
Function Documentation
svp_create()
SVP_T* svp_create (const char * uri, SVP_CALLBACKS_T * callbacks, const SVP_OPTS_T * opts)
Create a simple video player instance.
Parameters
uri URI to media, or NULL to use camera preview.
callbacks Callbacks for caller to receive notification of events, such as decoded buffers.
opts Player options.
Returns
Newly created simple video player instance, or NULL on error.
Definition at line 139 of file svp.c.
References SVP_T::callbacks, CHECK_STATUS, SVP_T::created, LOG_TRACE, MMAL_ENOMEM, MMAL_SUCCESS, SVP_T::mutex, NULL, SVP_T::opts, SVP_T::sema, SVP_CALLBACKS_T::stop_cb, SVP_T::timer, vcos_assert, vcos_calloc(), vcos_mutex_create(), vcos_semaphore_create(), VCOS_SUCCESS, vcos_timer_create(), SVP_T::video_decode, SVP_CALLBACKS_T::video_frame_cb, and SVP_T::video_output.
 {
    SVP_T *svp;
    MMAL_STATUS_T st;
    VCOS_STATUS_T vst;
    MMAL_PORT_T *reader_output = NULL;
    MMAL_COMPONENT_T *video_decode = NULL;
    MMAL_PORT_T *video_output = NULL;
    LOG_TRACE("Creating player for %s", (uri ? uri : "camera preview"));
    vcos_assert(callbacks->video_frame_cb);
    vcos_assert(callbacks->stop_cb);
    svp = vcos_calloc(1, sizeof(*svp), "svp");
    CHECK_STATUS((svp ? MMAL_SUCCESS : MMAL_ENOMEM), "Failed to allocate context");
    svp->opts = *opts;
    svp->callbacks = *callbacks;
    /* Semaphore used for synchronising buffer handling for decoded frames */
    vst = vcos_semaphore_create(&svp->sema, "svp-sem", 0);
    CHECK_STATUS((vst == VCOS_SUCCESS ? MMAL_SUCCESS : MMAL_ENOMEM), "Failed to create semaphore");
    svp->created |= SVP_CREATED_SEM;
    vst = vcos_mutex_create(&svp->mutex, "svp-mutex");
    CHECK_STATUS((vst == VCOS_SUCCESS ? MMAL_SUCCESS : MMAL_ENOMEM), "Failed to create mutex");
    svp->created |= SVP_CREATED_MUTEX;
    vst = vcos_timer_create(&svp->timer, "svp-timer", svp_timer_cb, svp);
    CHECK_STATUS((vst == VCOS_SUCCESS ? MMAL_SUCCESS : MMAL_ENOMEM), "Failed to create timer");
    svp->created |= SVP_CREATED_TIMER;
    vst = vcos_timer_create(&svp->wd_timer, "svp-wd-timer", svp_watchdog_cb, svp);
    CHECK_STATUS((vst == VCOS_SUCCESS ? MMAL_SUCCESS : MMAL_ENOMEM), "Failed to create timer");
    svp->created |= SVP_CREATED_WD_TIMER;
    /* Create components */
    svp->reader = NULL;
    svp->video_decode = NULL;
    svp->camera = NULL;
    svp->connection = NULL;
    if (uri)
    {
       /* Video from URI: setup container_reader -> video_decode */
       /* Create and set up container reader */
       st = mmal_component_create(MMAL_COMPONENT_DEFAULT_CONTAINER_READER, &svp->reader);
       CHECK_STATUS(st, "Failed to create container reader");
       st = svp_setup_reader(svp->reader, uri, &reader_output);
       if (st != MMAL_SUCCESS)
          goto error;
       st = mmal_component_enable(svp->reader);
       CHECK_STATUS(st, "Failed to enable container reader");
       st = svp_port_enable(svp, svp->reader->control, svp_bh_control_cb);
       CHECK_STATUS(st, "Failed to enable container reader control port");
       /* Create and set up video decoder */
       st = mmal_component_create(MMAL_COMPONENT_DEFAULT_VIDEO_DECODER, &svp->video_decode);
       CHECK_STATUS(st, "Failed to create video decoder");
       video_decode = svp->video_decode;
       video_output = video_decode->output[0];
       st = mmal_component_enable(video_decode);
       CHECK_STATUS(st, "Failed to enable video decoder");
       st = svp_port_enable(svp, video_decode->control, svp_bh_control_cb);
       CHECK_STATUS(st, "Failed to enable video decoder control port");
    }
    else
    {
       /* Camera preview */
       st = mmal_component_create(MMAL_COMPONENT_DEFAULT_CAMERA, &svp->camera);
       CHECK_STATUS(st, "Failed to create camera");
       st = mmal_component_enable(svp->camera);
       CHECK_STATUS(st, "Failed to enable camera");
       st = svp_port_enable(svp, svp->camera->control, svp_bh_control_cb);
       CHECK_STATUS(st, "Failed to enable camera control port");
       video_output = svp->camera->output[0]; /* Preview port */
    }
    st = mmal_port_parameter_set_boolean(video_output, MMAL_PARAMETER_ZERO_COPY, MMAL_TRUE);
    CHECK_STATUS((st == MMAL_ENOSYS ? MMAL_SUCCESS : st), "Failed to enable zero copy");
    if (uri)
    {
       /* Create connection: container_reader -> video_decoder */
       st = mmal_connection_create(&svp->connection, reader_output, video_decode->input[0],
                                   MMAL_CONNECTION_FLAG_TUNNELLING);
       CHECK_STATUS(st, "Failed to create connection");
    }
    /* Set video output port format.
     * Opaque encoding ensures we get buffer data as handles to relocatable heap. */
    video_output->format->encoding = MMAL_ENCODING_OPAQUE;
    if (!uri)
    {
       /* Set video format for camera preview */
       MMAL_VIDEO_FORMAT_T *vfmt = &video_output->format->es->video;
       CHECK_STATUS((video_output->format->type == MMAL_ES_TYPE_VIDEO) ? MMAL_SUCCESS : MMAL_EINVAL,
                    "Output port isn't video format");
       vfmt->width = SVP_CAMERA_WIDTH;
       vfmt->height = SVP_CAMERA_HEIGHT;
       vfmt->crop.x = 0;
       vfmt->crop.y = 0;
       vfmt->crop.width = vfmt->width;
       vfmt->crop.height = vfmt->height;
       vfmt->frame_rate.num = SVP_CAMERA_FRAMERATE;
       vfmt->frame_rate.den = 1;
    }
    st = mmal_port_format_commit(video_output);
    CHECK_STATUS(st, "Failed to set output port format");
    /* Finally, set buffer num/size. N.B. For container_reader/video_decode, must be after
     * connection created, in order for port format to propagate.
     * Don't enable video output port until want to produce frames. */
    video_output->buffer_num = video_output->buffer_num_recommended;
    video_output->buffer_size = video_output->buffer_size_recommended;
    /* Pool + queue to hold decoded video frames */
    svp->out_pool = mmal_port_pool_create(video_output, video_output->buffer_num,
                                          video_output->buffer_size);
    CHECK_STATUS((svp->out_pool ? MMAL_SUCCESS : MMAL_ENOMEM), "Error allocating pool");
    svp->queue = mmal_queue_create();
    CHECK_STATUS((svp ? MMAL_SUCCESS : MMAL_ENOMEM), "Error allocating queue");
    svp->video_output = video_output;
    return svp;
 error:
    svp_destroy(svp);
    return NULL;
 }
svp_destroy()
void svp_destroy (SVP_T * svp)
Destroy a simple video player instance.
Parameters
svp Simple video player instance. May be NULL, in which case this function does nothing.
Definition at line 327 of file svp.c.
References SVP_T::camera, SVP_T::connection, SVP_T::created, mmal_component_destroy(), mmal_component_disable(), mmal_connection_destroy(), mmal_pool_destroy(), mmal_queue_destroy(), SVP_T::mutex, SVP_T::out_pool, SVP_T::queue, SVP_T::reader, SVP_T::sema, svp_stop(), SVP_T::timer, vcos_countof, vcos_free(), vcos_mutex_delete(), vcos_semaphore_delete(), vcos_timer_delete(), SVP_T::video_decode, and SVP_T::wd_timer.
 {
    if (svp)
    {
       MMAL_COMPONENT_T *components[] = { svp->reader, svp->video_decode, svp->camera };
       MMAL_COMPONENT_T **comp;
       /* Stop thread, disable connection and components */
       svp_stop(svp);
       for (comp = components; comp < components + vcos_countof(components); comp++)
       {
          mmal_component_disable(*comp);
       }
       /* Destroy connection + components */
       if (svp->connection)
       {
          mmal_connection_destroy(svp->connection);
       }
       for (comp = components; comp < components + vcos_countof(components); comp++)
       {
          mmal_component_destroy(*comp);
       }
       /* Free remaining resources */
       if (svp->out_pool)
       {
          mmal_pool_destroy(svp->out_pool);
       }
       if (svp->queue)
       {
          mmal_queue_destroy(svp->queue);
       }
       if (svp->created & SVP_CREATED_WD_TIMER)
       {
          vcos_timer_delete(&svp->wd_timer);
       }
       if (svp->created & SVP_CREATED_TIMER)
       {
          vcos_timer_delete(&svp->timer);
       }
       if (svp->created & SVP_CREATED_MUTEX)
       {
          vcos_mutex_delete(&svp->mutex);
       }
       if (svp->created & SVP_CREATED_SEM)
       {
          vcos_semaphore_delete(&svp->sema);
       }
       vcos_free(svp);
    }
 }
svp_get_stats()
void svp_get_stats (SVP_T * svp, SVP_STATS_T * stats)
Get player stats.
Parameters
svp Simple video player instance.
stats Buffer in which stats are returned.
Definition at line 460 of file svp.c.
References SVP_T::mutex, SVP_T::stats, vcos_mutex_lock(), and vcos_mutex_unlock().
 {
    vcos_mutex_lock(&svp->mutex);
    *stats = svp->stats;
    vcos_mutex_unlock(&svp->mutex);
 }
svp_start()
int svp_start (SVP_T * svp)
Start a simple video player instance. Decoded frames are returned to the SVP_CALLBACKS_T::video_frame_cb function passed to svp_create().
Parameters
svp Simple video player instance.
Returns
0 on success; -1 on failure.
Definition at line 389 of file svp.c.
References svp_stop().
 {
    MMAL_STATUS_T st;
    VCOS_STATUS_T vst;
    /* Ensure SVP is stopped first */
    svp_stop(svp);
    /* Reset the worker thread stop status, before enabling ports that might trigger a stop */
    svp_reset_stop(svp);
    if (svp->connection)
    {
       /* Enable reader->decoder connection */
       st = mmal_connection_enable(svp->connection);
       CHECK_STATUS(st, "Failed to create connection");
    }
    /* Enable video output port */
    st = svp_port_enable(svp, svp->video_output, svp_bh_output_cb);
    CHECK_STATUS(st, "Failed to enable output port");
    /* Reset stats */
    svp->stats.video_frame_count = 0;
    /* Create worker thread */
    vst = vcos_thread_create(&svp->thread, "svp-worker", NULL, svp_worker, svp);
    CHECK_STATUS((vst == VCOS_SUCCESS ? MMAL_SUCCESS : MMAL_ENOMEM), "Failed to create connection");
    svp->created |= SVP_CREATED_THREAD;
    /* Set timer */
    if (svp->camera)
    {
       unsigned ms = svp->opts.duration_ms;
       vcos_timer_set(&svp->timer, ((ms == 0) ? SVP_CAMERA_DURATION_MS : ms));
    }
    /* Start watchdog timer */
    vcos_timer_set(&svp->wd_timer, SVP_WATCHDOG_TIMEOUT_MS);
    return 0;
 error:
    return -1;
 }
svp_stop()
void svp_stop (SVP_T * svp)
Stop a simple video player instance. If the player is not running, then this function does nothing.
Parameters
svp Simple video player instance.
Definition at line 437 of file svp.c.
References SVP_T::created, SVP_T::timer, vcos_timer_cancel(), and SVP_T::wd_timer.
Referenced by svp_destroy(), and svp_start().
 {
    vcos_timer_cancel(&svp->wd_timer);
    vcos_timer_cancel(&svp->timer);
    /* Stop worker thread */
    if (svp->created & SVP_CREATED_THREAD)
    {
       svp_set_stop(svp, SVP_STOP_USER);
       vcos_semaphore_post(&svp->sema);
       vcos_thread_join(&svp->thread, NULL);
       svp->created &= ~SVP_CREATED_THREAD;
    }
    if (svp->connection)
    {
       mmal_connection_disable(svp->connection);
    }
    mmal_port_disable(svp->video_output);
 }