VideoCore Library: interface/vcos/pthreads/vcos_platform.h File Reference
vcos_platform.h File Reference
#include <pthread.h>
#include <semaphore.h>
#include <unistd.h>
#include <sys/types.h>
#include <sched.h>
#include <errno.h>
#include <string.h>
#include <strings.h>
#include <time.h>
#include <signal.h>
#include <stddef.h>
#include <stdlib.h>
#include <dlfcn.h>
#include "interface/vcos/generic/vcos_generic_event_flags.h"
#include "interface/vcos/generic/vcos_generic_blockpool.h"
#include "interface/vcos/generic/vcos_mem_from_malloc.h"
#include "interface/vcos/generic/vcos_generic_reentrant_mtx.h"
#include "interface/vcos/generic/vcos_generic_named_sem.h"
#include "interface/vcos/generic/vcos_generic_quickslow_mutex.h"
#include "interface/vcos/generic/vcos_common.h"
Classes
struct VCOS_LLTHREAD_T
struct VCOS_EVENT_T
struct VCOS_TIMER_T
struct VCOS_THREAD_ATTR_T
struct VCOS_THREAD_EXIT_T
struct VCOS_THREAD_T
struct VCOS_ATOMIC_FLAGS_T
Macros
#define VCOS_HAVE_RTOS 1
#define VCOS_HAVE_SEMAPHORE 1
#define VCOS_HAVE_EVENT 1
#define VCOS_HAVE_QUEUE 0
#define VCOS_HAVE_LEGACY_ISR 0
#define VCOS_HAVE_TIMER 1
#define VCOS_HAVE_CANCELLATION_SAFE_TIMER 1
#define VCOS_HAVE_MEMPOOL 0
#define VCOS_HAVE_ISR 0
#define VCOS_HAVE_ATOMIC_FLAGS 1
#define VCOS_HAVE_THREAD_AT_EXIT 1
#define VCOS_HAVE_ONCE 1
#define VCOS_HAVE_BLOCK_POOL 1
#define VCOS_HAVE_FILE 0
#define VCOS_HAVE_PROC 0
#define VCOS_HAVE_CFG 0
#define VCOS_HAVE_ALIEN_THREADS 1
#define VCOS_HAVE_CMD 1
#define VCOS_HAVE_EVENT_FLAGS 1
#define VCOS_WANT_LOG_CMD 0 /* User apps should do their own thing */
#define VCOS_ALWAYS_WANT_LOGGING
#define VCOS_SO_EXT ".so"
#define VCOS_TIMER_MARGIN_EARLY 0
#define VCOS_TIMER_MARGIN_LATE 15
#define VCOS_ONCE_INIT PTHREAD_ONCE_INIT
#define VCOS_MAX_EXIT_HANDLERS 4
#define VCOS_SUSPEND -1
#define VCOS_NO_SUSPEND 0
#define VCOS_START 1
#define VCOS_NO_START 0
#define VCOS_THREAD_PRI_MIN (sched_get_priority_min(SCHED_OTHER))
#define VCOS_THREAD_PRI_MAX (sched_get_priority_max(SCHED_OTHER))
#define VCOS_THREAD_PRI_INCREASE (1)
#define VCOS_THREAD_PRI_HIGHEST VCOS_THREAD_PRI_MAX
#define VCOS_THREAD_PRI_LOWEST VCOS_THREAD_PRI_MIN
#define VCOS_THREAD_PRI_NORMAL ((VCOS_THREAD_PRI_MAX+VCOS_THREAD_PRI_MIN)/2)
#define VCOS_THREAD_PRI_BELOW_NORMAL (VCOS_THREAD_PRI_NORMAL-VCOS_THREAD_PRI_INCREASE)
#define VCOS_THREAD_PRI_ABOVE_NORMAL (VCOS_THREAD_PRI_NORMAL+VCOS_THREAD_PRI_INCREASE)
#define VCOS_THREAD_PRI_REALTIME VCOS_THREAD_PRI_MAX
#define _VCOS_AFFINITY_DEFAULT 0
#define _VCOS_AFFINITY_CPU0 0x100
#define _VCOS_AFFINITY_CPU1 0x200
#define _VCOS_AFFINITY_MASK 0x300
#define VCOS_CAN_SET_STACK_ADDR 0
#define VCOS_TICKS_PER_SECOND _vcos_get_ticks_per_second()
#define vcos_log_platform_init() _vcos_log_platform_init()
#define VCOS_APPLICATION_ARGC vcos_get_argc()
#define VCOS_APPLICATION_ARGV vcos_get_argv()
#define _VCOS_LOG_LEVEL() getenv("VC_LOGLEVEL")
#define VCOS_DL_LAZY RTLD_LAZY
#define VCOS_DL_NOW RTLD_NOW
#define VCOS_DL_LOCAL RTLD_LOCAL
#define VCOS_DL_GLOBAL RTLD_GLOBAL
Typedefs
typedef sem_t VCOS_SEMAPHORE_T
typedef uint32_t VCOS_UNSIGNED
typedef uint32_t VCOS_OPTION
typedef pthread_key_t VCOS_TLS_KEY_T
typedef pthread_once_t VCOS_ONCE_T
typedef struct VCOS_LLTHREAD_T VCOS_LLTHREAD_T
typedef pthread_mutex_t VCOS_MUTEX_T
typedef struct VCOS_TIMER_T VCOS_TIMER_T
typedef struct VCOS_THREAD_ATTR_T VCOS_THREAD_ATTR_T
typedef struct VCOS_THREAD_EXIT_T VCOS_THREAD_EXIT_T
typedef struct VCOS_THREAD_T VCOS_THREAD_T
typedef void(* VCOS_ISR_HANDLER_T) (VCOS_UNSIGNED vecnum)
Functions
VCOSPRE_ VCOS_STATUS_T vcos_pthreads_map_error (int error)
VCOSPRE_ VCOS_STATUS_T VCOSPOST_ vcos_pthreads_map_errno (void)
VCOS_STATUS_T vcos_thread_at_exit (void(*pfn)(void *), void *cxt)
uint32_t _vcos_get_ticks_per_second (void)
VCOSPRE_ void VCOSPOST_ _vcos_log_platform_init (void)
VCOS_INLINE_DECL void _vcos_thread_sem_wait (void)
VCOS_INLINE_DECL void _vcos_thread_sem_post (VCOS_THREAD_T *)
VCOS_STATIC_INLINE char * vcos_strdup (const char *str)
Variables
int vcos_use_android_log
Detailed Description
Pthreads implementation of VCOS.
Definition in file vcos_platform.h.
Macro Definition Documentation
_VCOS_AFFINITY_CPU0
#define _VCOS_AFFINITY_CPU0 0x100
Definition at line 209 of file vcos_platform.h.
_VCOS_AFFINITY_CPU1
#define _VCOS_AFFINITY_CPU1 0x200
Definition at line 210 of file vcos_platform.h.
_VCOS_AFFINITY_DEFAULT
#define _VCOS_AFFINITY_DEFAULT 0
Definition at line 208 of file vcos_platform.h.
_VCOS_AFFINITY_MASK
#define _VCOS_AFFINITY_MASK 0x300
Definition at line 211 of file vcos_platform.h.
Referenced by vcos_thread_create_classic().
_VCOS_LOG_LEVEL
#define _VCOS_LOG_LEVEL () getenv("VC_LOGLEVEL")
Definition at line 803 of file vcos_platform.h.
VCOS_ALWAYS_WANT_LOGGING
#define VCOS_ALWAYS_WANT_LOGGING
Definition at line 84 of file vcos_platform.h.
VCOS_APPLICATION_ARGC
#define VCOS_APPLICATION_ARGC vcos_get_argc()
Definition at line 795 of file vcos_platform.h.
VCOS_APPLICATION_ARGV
#define VCOS_APPLICATION_ARGV vcos_get_argv()
Definition at line 796 of file vcos_platform.h.
VCOS_CAN_SET_STACK_ADDR
#define VCOS_CAN_SET_STACK_ADDR 0
Definition at line 212 of file vcos_platform.h.
Referenced by vcos_thread_create_classic().
VCOS_DL_GLOBAL
#define VCOS_DL_GLOBAL RTLD_GLOBAL
Definition at line 822 of file vcos_platform.h.
VCOS_DL_LAZY
#define VCOS_DL_LAZY RTLD_LAZY
Definition at line 819 of file vcos_platform.h.
VCOS_DL_LOCAL
#define VCOS_DL_LOCAL RTLD_LOCAL
Definition at line 821 of file vcos_platform.h.
VCOS_DL_NOW
#define VCOS_DL_NOW RTLD_NOW
Definition at line 820 of file vcos_platform.h.
VCOS_HAVE_ALIEN_THREADS
#define VCOS_HAVE_ALIEN_THREADS 1
Definition at line 79 of file vcos_platform.h.
VCOS_HAVE_ATOMIC_FLAGS
#define VCOS_HAVE_ATOMIC_FLAGS 1
Definition at line 72 of file vcos_platform.h.
VCOS_HAVE_BLOCK_POOL
#define VCOS_HAVE_BLOCK_POOL 1
Definition at line 75 of file vcos_platform.h.
VCOS_HAVE_CANCELLATION_SAFE_TIMER
#define VCOS_HAVE_CANCELLATION_SAFE_TIMER 1
Definition at line 69 of file vcos_platform.h.
VCOS_HAVE_CFG
#define VCOS_HAVE_CFG 0
Definition at line 78 of file vcos_platform.h.
VCOS_HAVE_CMD
#define VCOS_HAVE_CMD 1
Definition at line 80 of file vcos_platform.h.
VCOS_HAVE_EVENT
#define VCOS_HAVE_EVENT 1
Definition at line 65 of file vcos_platform.h.
VCOS_HAVE_EVENT_FLAGS
#define VCOS_HAVE_EVENT_FLAGS 1
Definition at line 81 of file vcos_platform.h.
VCOS_HAVE_FILE
#define VCOS_HAVE_FILE 0
Definition at line 76 of file vcos_platform.h.
VCOS_HAVE_ISR
#define VCOS_HAVE_ISR 0
Definition at line 71 of file vcos_platform.h.
VCOS_HAVE_LEGACY_ISR
#define VCOS_HAVE_LEGACY_ISR 0
Definition at line 67 of file vcos_platform.h.
VCOS_HAVE_MEMPOOL
#define VCOS_HAVE_MEMPOOL 0
Definition at line 70 of file vcos_platform.h.
VCOS_HAVE_ONCE
#define VCOS_HAVE_ONCE 1
Definition at line 74 of file vcos_platform.h.
VCOS_HAVE_PROC
#define VCOS_HAVE_PROC 0
Definition at line 77 of file vcos_platform.h.
VCOS_HAVE_QUEUE
#define VCOS_HAVE_QUEUE 0
Definition at line 66 of file vcos_platform.h.
VCOS_HAVE_RTOS
#define VCOS_HAVE_RTOS 1
Definition at line 63 of file vcos_platform.h.
VCOS_HAVE_SEMAPHORE
#define VCOS_HAVE_SEMAPHORE 1
Definition at line 64 of file vcos_platform.h.
VCOS_HAVE_THREAD_AT_EXIT
#define VCOS_HAVE_THREAD_AT_EXIT 1
Definition at line 73 of file vcos_platform.h.
VCOS_HAVE_TIMER
#define VCOS_HAVE_TIMER 1
Definition at line 68 of file vcos_platform.h.
vcos_log_platform_init
#define vcos_log_platform_init () _vcos_log_platform_init()
Definition at line 789 of file vcos_platform.h.
VCOS_MAX_EXIT_HANDLERS
#define VCOS_MAX_EXIT_HANDLERS 4
Definition at line 158 of file vcos_platform.h.
VCOS_NO_START
#define VCOS_NO_START 0
Definition at line 195 of file vcos_platform.h.
VCOS_NO_SUSPEND
#define VCOS_NO_SUSPEND 0
Definition at line 192 of file vcos_platform.h.
VCOS_ONCE_INIT
#define VCOS_ONCE_INIT PTHREAD_ONCE_INIT
Definition at line 121 of file vcos_platform.h.
VCOS_SO_EXT
#define VCOS_SO_EXT ".so"
Definition at line 90 of file vcos_platform.h.
VCOS_START
#define VCOS_START 1
Definition at line 194 of file vcos_platform.h.
VCOS_SUSPEND
#define VCOS_SUSPEND -1
Definition at line 191 of file vcos_platform.h.
VCOS_THREAD_PRI_ABOVE_NORMAL
#define VCOS_THREAD_PRI_ABOVE_NORMAL (VCOS_THREAD_PRI_NORMAL+VCOS_THREAD_PRI_INCREASE)
Definition at line 205 of file vcos_platform.h.
VCOS_THREAD_PRI_BELOW_NORMAL
#define VCOS_THREAD_PRI_BELOW_NORMAL (VCOS_THREAD_PRI_NORMAL-VCOS_THREAD_PRI_INCREASE)
Definition at line 204 of file vcos_platform.h.
VCOS_THREAD_PRI_HIGHEST
#define VCOS_THREAD_PRI_HIGHEST VCOS_THREAD_PRI_MAX
Definition at line 201 of file vcos_platform.h.
VCOS_THREAD_PRI_INCREASE
#define VCOS_THREAD_PRI_INCREASE (1)
Definition at line 200 of file vcos_platform.h.
VCOS_THREAD_PRI_LOWEST
#define VCOS_THREAD_PRI_LOWEST VCOS_THREAD_PRI_MIN
Definition at line 202 of file vcos_platform.h.
VCOS_THREAD_PRI_MAX
#define VCOS_THREAD_PRI_MAX (sched_get_priority_max(SCHED_OTHER))
Definition at line 198 of file vcos_platform.h.
VCOS_THREAD_PRI_MIN
#define VCOS_THREAD_PRI_MIN (sched_get_priority_min(SCHED_OTHER))
Definition at line 197 of file vcos_platform.h.
VCOS_THREAD_PRI_NORMAL
#define VCOS_THREAD_PRI_NORMAL ((VCOS_THREAD_PRI_MAX+VCOS_THREAD_PRI_MIN)/2)
Definition at line 203 of file vcos_platform.h.
VCOS_THREAD_PRI_REALTIME
#define VCOS_THREAD_PRI_REALTIME VCOS_THREAD_PRI_MAX
Definition at line 206 of file vcos_platform.h.
VCOS_TICKS_PER_SECOND
#define VCOS_TICKS_PER_SECOND _vcos_get_ticks_per_second()
Definition at line 214 of file vcos_platform.h.
VCOS_TIMER_MARGIN_EARLY
#define VCOS_TIMER_MARGIN_EARLY 0
Definition at line 93 of file vcos_platform.h.
VCOS_TIMER_MARGIN_LATE
#define VCOS_TIMER_MARGIN_LATE 15
Definition at line 94 of file vcos_platform.h.
VCOS_WANT_LOG_CMD
#define VCOS_WANT_LOG_CMD 0 /* User apps should do their own thing */
Definition at line 82 of file vcos_platform.h.
Typedef Documentation
VCOS_ISR_HANDLER_T
typedef void(* VCOS_ISR_HANDLER_T) (VCOS_UNSIGNED vecnum)
Definition at line 817 of file vcos_platform.h.
VCOS_LLTHREAD_T
typedef struct VCOS_LLTHREAD_T VCOS_LLTHREAD_T
VCOS_MUTEX_T
typedef pthread_mutex_t VCOS_MUTEX_T
Definition at line 110 of file vcos_platform.h.
VCOS_ONCE_T
typedef pthread_once_t VCOS_ONCE_T
Definition at line 100 of file vcos_platform.h.
VCOS_OPTION
typedef uint32_t VCOS_OPTION
Definition at line 98 of file vcos_platform.h.
VCOS_SEMAPHORE_T
typedef sem_t VCOS_SEMAPHORE_T
Definition at line 96 of file vcos_platform.h.
VCOS_THREAD_ATTR_T
typedef struct VCOS_THREAD_ATTR_T VCOS_THREAD_ATTR_T
Thread attribute structure. Don't use pthread_attr directly, as the calls can fail, and inits must match deletes.
VCOS_THREAD_EXIT_T
typedef struct VCOS_THREAD_EXIT_T VCOS_THREAD_EXIT_T
Called at thread exit.
VCOS_THREAD_T
typedef struct VCOS_THREAD_T VCOS_THREAD_T
VCOS_TIMER_T
typedef struct VCOS_TIMER_T VCOS_TIMER_T
VCOS_TLS_KEY_T
typedef pthread_key_t VCOS_TLS_KEY_T
Definition at line 99 of file vcos_platform.h.
VCOS_UNSIGNED
typedef uint32_t VCOS_UNSIGNED
Definition at line 97 of file vcos_platform.h.
Function Documentation
_vcos_get_ticks_per_second()
uint32_t _vcos_get_ticks_per_second (void)
Definition at line 604 of file vcos_pthreads.c.
 {
    return HZ;
 }
_vcos_log_platform_init()
VCOSPRE_ void VCOSPOST_ _vcos_log_platform_init (void)
Definition at line 321 of file vcos_pthreads.c.
References vcos_process_id_current().
 {
    if(vcos_log_to_file)
    {
       char log_fname[100];
 #ifdef ANDROID
       snprintf(log_fname, 100, "/data/log/vcos_log%u.txt", vcos_process_id_current());
 #else
       snprintf(log_fname, 100, "/var/log/vcos_log%u.txt", vcos_process_id_current());
 #endif
       log_fhandle = fopen(log_fname, "w");
    }
    else
       log_fhandle = stderr;
 }
_vcos_thread_sem_post()
VCOS_INLINE_DECL void _vcos_thread_sem_post (VCOS_THREAD_T *)
_vcos_thread_sem_wait()
VCOS_INLINE_DECL void _vcos_thread_sem_wait (void)
vcos_pthreads_map_errno()
VCOSPRE_ VCOS_STATUS_T VCOSPOST_ vcos_pthreads_map_errno (void)
Definition at line 477 of file vcos_pthreads.c.
References vcos_pthreads_map_error().
 {
    return vcos_pthreads_map_error(errno);
 }
vcos_pthreads_map_error()
VCOSPRE_ VCOS_STATUS_T vcos_pthreads_map_error (int error)
Convert errno values into the values recognized by vcos
Definition at line 460 of file vcos_pthreads.c.
References VCOS_EAGAIN, VCOS_EINVAL, VCOS_ENOMEM, VCOS_ENOSPC, and VCOS_ENXIO.
Referenced by vcos_pthreads_map_errno().
 {
    switch (error)
    {
    case ENOMEM:
       return VCOS_ENOMEM;
    case ENXIO:
       return VCOS_ENXIO;
    case EAGAIN:
       return VCOS_EAGAIN;
    case ENOSPC:
       return VCOS_ENOSPC;
    default:
       return VCOS_EINVAL;
    }
 }
vcos_strdup()
VCOS_STATIC_INLINE char* vcos_strdup (const char * str)
Definition at line 806 of file vcos_platform.h.
References len, and NULL.
Referenced by OpenVideoCoreMemoryFileWithOffset().
 {
    size_t len = strlen(str) + 1;
    void *p = malloc(len);
    if (p == NULL)
       return NULL;
    return (char *)memcpy(p, str, len);
 }
vcos_thread_at_exit()
VCOS_STATUS_T vcos_thread_at_exit (void(*)(void *) pfn, void * cxt)
Register a function to be called when the current thread exits.
Definition at line 563 of file vcos_pthreads.c.
References NULL, vcos_assert, VCOS_EINVAL, VCOS_ENOSPC, VCOS_MAX_EXIT_HANDLERS, VCOS_SUCCESS, and vcos_thread_current().
 {
    int i;
    VCOS_THREAD_T *self = vcos_thread_current();
    if (!self)
    {
       vcos_assert(0);
       return VCOS_EINVAL;
    }
    for (i=0; i<VCOS_MAX_EXIT_HANDLERS; i++)
    {
       if (self->at_exit[i].pfn == NULL)
       {
          self->at_exit[i].pfn = pfn;
          self->at_exit[i].cxt = cxt;
          return VCOS_SUCCESS;
       }
    }
    return VCOS_ENOSPC;
 }
Variable Documentation
vcos_use_android_log
int vcos_use_android_log
Set to 1 by default when ANDROID is defined. Allows runtime switching for console apps.
Definition at line 288 of file vcos_pthreads.c.
Referenced by main(), and vcos_getmicrosecs64_internal().