VideoCore Library: interface/mmal/openmaxil/mmalomx_logging.h File Reference
mmalomx_logging.h File Reference
#include "mmal_common.h"
#include "interface/vcos/vcos_logging.h"
#include <mmal_logging.h>
Macros
#define VCOS_LOG_CATEGORY (&mmalomx_log_category)
Functions
void mmalomx_logging_init (void)
void mmalomx_logging_deinit (void)
const char * mmalomx_param_to_string (OMX_INDEXTYPE param)
const char * mmalomx_cmd_to_string (OMX_COMMANDTYPE cmd)
const char * mmalomx_state_to_string (OMX_STATETYPE state)
const char * mmalomx_event_to_string (OMX_EVENTTYPE event)
const char * mmalomx_error_to_string (OMX_ERRORTYPE error)
Variables
VCOS_LOG_CAT_T mmalomx_log_category
Detailed Description
OpenMAX IL adaptation layer for MMAL - Logging functions
Definition in file mmalomx_logging.h.
Macro Definition Documentation
VCOS_LOG_CATEGORY
#define VCOS_LOG_CATEGORY (&mmalomx_log_category)
Definition at line 35 of file mmalomx_logging.h.
Function Documentation
mmalomx_cmd_to_string()
const char* mmalomx_cmd_to_string (OMX_COMMANDTYPE cmd)
Definition at line 114 of file mmalomx_logging.c.
References MMALOMX_SAT, and vcos_countof.
 {
   static const char *names[] = {
     "OMX_CommandStateSet", "OMX_CommandFlush", "OMX_CommandPortDisable",
     "OMX_CommandPortEnable", "OMX_CommandMarkBuffer", "OMX_Command unknown"
   };
   return names[MMALOMX_SAT((int)cmd, 0, (int)vcos_countof(names)-1)];
 }
mmalomx_error_to_string()
const char* mmalomx_error_to_string (OMX_ERRORTYPE error)
Definition at line 148 of file mmalomx_logging.c.
References MMALOMX_SAT, OMX_ErrorInsufficientResources, OMX_ErrorNone, and vcos_countof.
 {
   static const char *names[] = {
     "OMX_ErrorInsufficientResources", "OMX_ErrorUndefined",
     "OMX_ErrorInvalidComponentName", "OMX_ErrorComponentNotFound",
     "OMX_ErrorInvalidComponent", "OMX_ErrorBadParameter",
     "OMX_ErrorNotImplemented", "OMX_ErrorUnderflow",
     "OMX_ErrorOverflow", "OMX_ErrorHardware", "OMX_ErrorInvalidState",
     "OMX_ErrorStreamCorrupt", "OMX_ErrorPortsNotCompatible",
     "OMX_ErrorResourcesLost", "OMX_ErrorNoMore", "OMX_ErrorVersionMismatch",
     "OMX_ErrorNotReady", "OMX_ErrorTimeout", "OMX_ErrorSameState",
     "OMX_ErrorResourcesPreempted", "OMX_ErrorPortUnresponsiveDuringAllocation",
     "OMX_ErrorPortUnresponsiveDuringDeallocation",
     "OMX_ErrorPortUnresponsiveDuringStop", "OMX_ErrorIncorrectStateTransition",
     "OMX_ErrorIncorrectStateOperation", "OMX_ErrorUnsupportedSetting",
     "OMX_ErrorUnsupportedIndex", "OMX_ErrorBadPortIndex",
     "OMX_ErrorPortUnpopulated", "OMX_ErrorComponentSuspended",
     "OMX_ErrorDynamicResourcesUnavailable", "OMX_ErrorMbErrorsInFrame",
     "OMX_ErrorFormatNotDetected", "OMX_ErrorContentPipeOpenFailed",
     "OMX_ErrorContentPipeCreationFailed", "OMX_ErrorSeperateTablesUsed",
     "OMX_ErrorTunnelingUnsupported",
     "OMX_Error unknown"
   };
   if(error == OMX_ErrorNone) return "OMX_ErrorNone";
   error -= OMX_ErrorInsufficientResources;
   return names[MMALOMX_SAT((int)error, 0, (int)vcos_countof(names)-1)];
 }
mmalomx_event_to_string()
const char* mmalomx_event_to_string (OMX_EVENTTYPE event)
Definition at line 135 of file mmalomx_logging.c.
References MMALOMX_SAT, and vcos_countof.
 {
   static const char *names[] = {
     "OMX_EventCmdComplete", "OMX_EventError", "OMX_EventMark",
     "OMX_EventPortSettingsChanged", "OMX_EventBufferFlag",
     "OMX_EventResourcesAcquired", "OMX_EventComponentResumed",
     "OMX_EventDynamicResourcesAvailable", "OMX_EventPortFormatDetected",
     "OMX_Event unknown"
   };
   return names[MMALOMX_SAT((int)event, 0, (int)vcos_countof(names)-1)];
 }
mmalomx_logging_deinit()
void mmalomx_logging_deinit (void)
Definition at line 49 of file mmalomx_logging.c.
Referenced by OMX_Deinit().
 {
    mmalomx_log_level = mmalomx_log_category.level;
    vcos_log_unregister(VCOS_LOG_CATEGORY);
 }
mmalomx_logging_init()
void mmalomx_logging_init (void)
Definition at line 43 of file mmalomx_logging.c.
References VCOS_LOG_CATEGORY, and vcos_log_set_level().
Referenced by OMX_Init().
 {
    vcos_log_set_level(VCOS_LOG_CATEGORY, mmalomx_log_level);
    vcos_log_register("mmalomx", VCOS_LOG_CATEGORY);
 }
mmalomx_param_to_string()
const char* mmalomx_param_to_string (OMX_INDEXTYPE param)
Definition at line 55 of file mmalomx_logging.c.
References mmalomx_parameter_name_omx(), name, OMX_IndexAutoPauseAfterCapture, OMX_IndexConfigCapturing, OMX_IndexConfigCommonDigitalZoom, OMX_IndexConfigCommonExposureValue, OMX_IndexConfigCommonInputCrop, OMX_IndexConfigCommonMirror, OMX_IndexConfigCommonOutputCrop, OMX_IndexConfigCommonRotate, OMX_IndexConfigCommonScale, OMX_IndexConfigCommonWhiteBalance, OMX_IndexParamActiveStream, OMX_IndexParamAudioAac, OMX_IndexParamAudioInit, OMX_IndexParamAudioMp3, OMX_IndexParamAudioPcm, OMX_IndexParamAudioPortFormat, OMX_IndexParamCommonSensorMode, OMX_IndexParamCompBufferSupplier, OMX_IndexParamContentURI, OMX_IndexParamImageInit, OMX_IndexParamImagePortFormat, OMX_IndexParamNumAvailableStreams, OMX_IndexParamOtherInit, OMX_IndexParamOtherPortFormat, OMX_IndexParamPortDefinition, OMX_IndexParamPriorityMgmt, OMX_IndexParamStandardComponentRole, OMX_IndexParamVideoAvc, OMX_IndexParamVideoBitrate, OMX_IndexParamVideoH263, OMX_IndexParamVideoInit, OMX_IndexParamVideoMpeg2, OMX_IndexParamVideoMpeg4, OMX_IndexParamVideoPortFormat, OMX_IndexParamVideoProfileLevelQuerySupported, OMX_IndexParamVideoRv, and OMX_IndexParamVideoWmv.
 {
   static const struct {
     const char *string;
     const OMX_INDEXTYPE param;
   } param_to_names[] =
   {
     {"OMX_IndexParamPriorityMgmt", OMX_IndexParamPriorityMgmt},
     {"OMX_IndexParamAudioInit", OMX_IndexParamAudioInit},
     {"OMX_IndexParamImageInit", OMX_IndexParamImageInit},
     {"OMX_IndexParamVideoInit", OMX_IndexParamVideoInit},
     {"OMX_IndexParamOtherInit", OMX_IndexParamOtherInit},
     {"OMX_IndexParamPortDefinition", OMX_IndexParamPortDefinition},
     {"OMX_IndexParamCompBufferSupplier", OMX_IndexParamCompBufferSupplier},
     {"OMX_IndexParamAudioPortFormat", OMX_IndexParamAudioPortFormat},
     {"OMX_IndexParamVideoPortFormat", OMX_IndexParamVideoPortFormat},
     {"OMX_IndexParamImagePortFormat", OMX_IndexParamImagePortFormat},
     {"OMX_IndexParamOtherPortFormat", OMX_IndexParamOtherPortFormat},
     {"OMX_IndexParamAudioPcm", OMX_IndexParamAudioPcm},
     {"OMX_IndexParamAudioAac", OMX_IndexParamAudioAac},
     {"OMX_IndexParamAudioMp3", OMX_IndexParamAudioMp3},
     {"OMX_IndexParamVideoMpeg2", OMX_IndexParamVideoMpeg2},
     {"OMX_IndexParamVideoMpeg4", OMX_IndexParamVideoMpeg4},
     {"OMX_IndexParamVideoWmv", OMX_IndexParamVideoWmv},
     {"OMX_IndexParamVideoRv", OMX_IndexParamVideoRv},
     {"OMX_IndexParamVideoAvc", OMX_IndexParamVideoAvc},
     {"OMX_IndexParamVideoH263", OMX_IndexParamVideoH263},
     {"OMX_IndexParamStandardComponentRole", OMX_IndexParamStandardComponentRole},
     {"OMX_IndexParamContentURI", OMX_IndexParamContentURI},
     {"OMX_IndexParamCommonSensorMode", OMX_IndexParamCommonSensorMode},
     {"OMX_IndexConfigCommonWhiteBalance", OMX_IndexConfigCommonWhiteBalance},
     {"OMX_IndexConfigCommonDigitalZoom", OMX_IndexConfigCommonDigitalZoom},
     {"OMX_IndexConfigCommonExposureValue", OMX_IndexConfigCommonExposureValue},
     {"OMX_IndexConfigCapturing", OMX_IndexConfigCapturing},
     {"OMX_IndexAutoPauseAfterCapture", OMX_IndexAutoPauseAfterCapture},
     {"OMX_IndexConfigCommonRotate", OMX_IndexConfigCommonRotate},
     {"OMX_IndexConfigCommonMirror", OMX_IndexConfigCommonMirror},
     {"OMX_IndexConfigCommonScale", OMX_IndexConfigCommonScale},
     {"OMX_IndexConfigCommonInputCrop", OMX_IndexConfigCommonInputCrop},
     {"OMX_IndexConfigCommonOutputCrop", OMX_IndexConfigCommonOutputCrop},
     {"OMX_IndexParamNumAvailableStreams", OMX_IndexParamNumAvailableStreams},
     {"OMX_IndexParamActiveStream", OMX_IndexParamActiveStream},
     {"OMX_IndexParamVideoBitrate", OMX_IndexParamVideoBitrate},
     {"OMX_IndexParamVideoProfileLevelQuerySupported", OMX_IndexParamVideoProfileLevelQuerySupported},
     {"OMX_IndexParam unknown", (OMX_INDEXTYPE)0}
   };
   const char *name = mmalomx_parameter_name_omx((uint32_t)param);
   int i;
   if (name)
      return name;
   for(i = 0; param_to_names[i].param &&
       param_to_names[i].param != param; i++);
   return param_to_names[i].string;
 }
mmalomx_state_to_string()
const char* mmalomx_state_to_string (OMX_STATETYPE state)
Definition at line 124 of file mmalomx_logging.c.
 {
   static const char *names[] = {
     "OMX_StateInvalid", "OMX_StateLoaded", "OMX_StateIdle",
     "OMX_StateExecuting", "OMX_StatePause", "OMX_StateWaitForResources",
     "OMX_State unknown"
   };
   return names[MMALOMX_SAT((int)state, 0, (int)vcos_countof(names)-1)];
 }
Variable Documentation
mmalomx_log_category
VCOS_LOG_CAT_T mmalomx_log_category
Definition at line 38 of file mmalomx_logging.c.