VideoCore Library: Rational Utility Functions
Rational Utility Functions
Utility functions
Functions
MMAL_RATIONAL_T mmal_rational_add (MMAL_RATIONAL_T a, MMAL_RATIONAL_T b)
MMAL_RATIONAL_T mmal_rational_subtract (MMAL_RATIONAL_T a, MMAL_RATIONAL_T b)
MMAL_RATIONAL_T mmal_rational_multiply (MMAL_RATIONAL_T a, MMAL_RATIONAL_T b)
MMAL_RATIONAL_T mmal_rational_divide (MMAL_RATIONAL_T a, MMAL_RATIONAL_T b)
int32_t mmal_rational_to_fixed_16_16 (MMAL_RATIONAL_T rational)
MMAL_RATIONAL_T mmal_rational_from_fixed_16_16 (int32_t fixed)
void mmal_rational_simplify (MMAL_RATIONAL_T *rational)
MMAL_BOOL_T mmal_rational_equal (MMAL_RATIONAL_T a, MMAL_RATIONAL_T b)
Detailed Description
The rational utility functions allow easy manipulation of rational numbers.
Function Documentation
mmal_rational_add()
MMAL_RATIONAL_T mmal_rational_add (MMAL_RATIONAL_T a, MMAL_RATIONAL_T b)
Add 2 rational numbers. It is assumed that both input rational numbers are in their simplest form.
Parameters
a First operand
b Second operand
Returns
a + b
Calculate a + b.
Definition at line 64 of file mmal_util_rational.c.
Referenced by mmal_rational_subtract().
 {
    MMAL_RATIONAL_T result;
    int32_t g = gcd(a.den, b.den);
    a.den /= g;
    a.num = a.num * (b.den / g) + b.num * a.den;
    g = gcd(a.num, g);
    a.num /= g;
    a.den *= b.den / g;
    result.num = a.num;
    result.den = a.den;
    return result;
 }
mmal_rational_divide()
MMAL_RATIONAL_T mmal_rational_divide (MMAL_RATIONAL_T a, MMAL_RATIONAL_T b)
Divide 2 rational numbers. It is assumed that both input rational numbers are in their simplest form.
Parameters
a First operand
b Second operand
Returns
a / b
Calculate a / b
Definition at line 99 of file mmal_util_rational.c.
References MMAL_RATIONAL_T::num, and vcos_assert.
 {
    MMAL_RATIONAL_T result;
    int32_t gcd1, gcd2;
    if (b.num == 0)
    {
       vcos_assert(0);
       return a;
    }
    if (a.num == 0)
       return a;
    gcd1 = gcd(a.num, b.num);
    gcd2 = gcd(b.den, a.den);
    result.num = (a.num / gcd1) * (b.den / gcd2);
    result.den = (a.den / gcd2) * (b.num / gcd1);
    return result;
 }
mmal_rational_equal()
MMAL_BOOL_T mmal_rational_equal (MMAL_RATIONAL_T a, MMAL_RATIONAL_T b)
Test 2 rational numbers for equality.
Parameters
a First operand
b Second operand
Returns
true if equal
Tests for equality
Definition at line 153 of file mmal_util_rational.c.
References MMAL_RATIONAL_T::den, MMAL_FALSE, and MMAL_RATIONAL_T::num.
Referenced by mmal_format_compare().
 {
    if (a.num != b.num && a.num * (int64_t)b.num == 0)
       return MMAL_FALSE;
    return a.num * (int64_t)b.den == b.num * (int64_t)a.den;
 }
mmal_rational_from_fixed_16_16()
MMAL_RATIONAL_T mmal_rational_from_fixed_16_16 (int32_t fixed)
Convert a signed 32-bit Q16 number to a rational number.
Parameters
fixed Signed 32-bit Q16 number to convert
Returns
Rational number
Convert a rational number to a signed 32-bit Q16 number.
Definition at line 137 of file mmal_util_rational.c.
References mmal_rational_simplify(), and Q16_ONE.
 {
    MMAL_RATIONAL_T result = { fixed, Q16_ONE };
    mmal_rational_simplify(&result);
    return result;
 }
mmal_rational_multiply()
MMAL_RATIONAL_T mmal_rational_multiply (MMAL_RATIONAL_T a, MMAL_RATIONAL_T b)
Multiply 2 rational numbers. It is assumed that both input rational numbers are in their simplest form.
Parameters
a First operand
b Second operand
Returns
a * b
Calculate a * b
Definition at line 87 of file mmal_util_rational.c.
 {
    MMAL_RATIONAL_T result;
    int32_t gcd1 = gcd(a.num, b.den);
    int32_t gcd2 = gcd(b.num, a.den);
    result.num = (a.num / gcd1) * (b.num / gcd2);
    result.den = (a.den / gcd2) * (b.den / gcd1);
    return result;
 }
mmal_rational_simplify()
void mmal_rational_simplify (MMAL_RATIONAL_T * rational)
Reduce a rational number to it's simplest form.
Parameters
rational Rational number to simplify
Reduce a rational number to it's simplest form.
Definition at line 145 of file mmal_util_rational.c.
Referenced by mmal_rational_from_fixed_16_16(), and mmalomx_param_rational_generic().
 {
    int g = gcd(rational->num, rational->den);
    rational->num /= g;
    rational->den /= g;
 }
mmal_rational_subtract()
MMAL_RATIONAL_T mmal_rational_subtract (MMAL_RATIONAL_T a, MMAL_RATIONAL_T b)
Subtract 2 rational numbers. It is assumed that both input rational numbers are in their simplest form.
Parameters
a First operand
b Second operand
Returns
a - b
Calculate a - b.
Definition at line 80 of file mmal_util_rational.c.
References mmal_rational_add(), and MMAL_RATIONAL_T::num.
 {
    b.num = -b.num;
    return mmal_rational_add(a, b);
 }
mmal_rational_to_fixed_16_16()
int32_t mmal_rational_to_fixed_16_16 (MMAL_RATIONAL_T rational)
Convert a rational number to a 32-bit signed Q16 number. Saturation will occur for rational numbers with an absolute value greater than 32768.
Parameters
rational Rational number to convert
Returns
32-bit signed Q16 number
Convert a rational number to a signed 32-bit Q16 number.
Definition at line 122 of file mmal_util_rational.c.
References MMAL_RATIONAL_T::den, and MMAL_RATIONAL_T::num.
 {
    int64_t result = (int64_t)rational.num << 16;
    if (rational.den)
       result /= rational.den;
    if (result > INT_MAX)
       result = INT_MAX;
    else if (result < INT_MIN)
       result = INT_MIN;
    return (int32_t)result;
 }