VideoCore Library: host_applications/linux/apps/hello_pi/libs/vgfont/vgft.c File Reference
vgft.c File Reference
#include <assert.h>
#include <stdlib.h>
#include "graphics_x_private.h"
#include "vgft.h"
Macros
#define SEGMENTS_COUNT_MAX 256
#define COORDS_COUNT_MAX 1024
#define CHAR_COUNT_MAX 200
Functions
int vgft_init (void)
void vgft_term (void)
VCOS_STATUS_T vgft_font_init (VGFT_FONT_T *font)
VCOS_STATUS_T vgft_font_load_mem (VGFT_FONT_T *font, void *mem, size_t len)
VCOS_STATUS_T vgft_font_load_file (VGFT_FONT_T *font, const char *file)
VCOS_STATUS_T vgft_font_convert_glyphs (VGFT_FONT_T *font, unsigned int char_height, unsigned int dpi_x, unsigned int dpi_y)
void vgft_font_term (VGFT_FONT_T *font)
void vgft_font_draw (VGFT_FONT_T *font, VGfloat x, VGfloat y, const char *text, unsigned text_length, VGbitfield paint_modes)
void vgft_get_text_extents (VGFT_FONT_T *font, const char *text, unsigned text_length, VGfloat unused0, VGfloat unused1, VGfloat *w, VGfloat *h)
VGfloat vgft_first_line_y_offset (VGFT_FONT_T *font)
Macro Definition Documentation
CHAR_COUNT_MAX
#define CHAR_COUNT_MAX 200
Definition at line 259 of file vgft.c.
COORDS_COUNT_MAX
#define COORDS_COUNT_MAX 1024
Definition at line 54 of file vgft.c.
SEGMENTS_COUNT_MAX
#define SEGMENTS_COUNT_MAX 256
Definition at line 53 of file vgft.c.
Function Documentation
vgft_first_line_y_offset()
VGfloat vgft_first_line_y_offset (VGFT_FONT_T * font)
Definition at line 422 of file vgft.c.
{
    return float_from_26_6(font->ft_face->size->metrics.height);
 }
vgft_font_convert_glyphs()
VCOS_STATUS_T vgft_font_convert_glyphs (VGFT_FONT_T * font, unsigned int char_height, unsigned int dpi_x, unsigned int dpi_y)
Convert a font into VG glyphs
Definition at line 202 of file vgft.c.
References assert(), VGFT_FONT_T::ft_face, VCOS_EINVAL, VCOS_ENOMEM, VGFT_FONT_T::vg_font, VG_INVALID_HANDLE, VG_PATH_CAPABILITY_ALL, VG_PATH_DATATYPE_F, VG_PATH_FORMAT_STANDARD, vgCreatePath(), and vgDestroyFont().
 {
    FT_UInt glyph_index;
    FT_ULong ch;
    if (FT_Set_Char_Size(font->ft_face, 0, char_height, dpi_x, dpi_y))
    {
       FT_Done_Face(font->ft_face);
       vgDestroyFont(font->vg_font);
       return VCOS_EINVAL;
    }
    ch = FT_Get_First_Char(font->ft_face, &glyph_index);
    while (ch != 0)
    {
       if (FT_Load_Glyph(font->ft_face, glyph_index, FT_LOAD_DEFAULT)) {
          FT_Done_Face(font->ft_face);
          vgDestroyFont(font->vg_font);
          return VCOS_ENOMEM;
       }
       VGPath vg_path;
       FT_Outline *outline = &font->ft_face->glyph->outline;
       if (outline->n_contours != 0) {
          vg_path = vgCreatePath(VG_PATH_FORMAT_STANDARD, VG_PATH_DATATYPE_F, 1.0f, 0.0f, 0, 0, VG_PATH_CAPABILITY_ALL);
          assert(vg_path != VG_INVALID_HANDLE);
          convert_outline(outline->points, outline->tags, outline->contours, outline->n_contours, outline->n_points);
          vgAppendPathData(vg_path, segments_count, segments, coords);
       } else {
          vg_path = VG_INVALID_HANDLE;
       }
       VGfloat origin[] = { 0.0f, 0.0f };
       VGfloat escapement[] = { float_from_26_6(font->ft_face->glyph->advance.x), float_from_26_6(font->ft_face->glyph->advance.y) };
       vgSetGlyphToPath(font->vg_font, glyph_index, vg_path, VG_FALSE, origin, escapement);
       if (vg_path != VG_INVALID_HANDLE) {
          vgDestroyPath(vg_path);
       }
       ch = FT_Get_Next_Char(font->ft_face, ch, &glyph_index);
    }
    return VCOS_SUCCESS;
 }
vgft_font_draw()
void vgft_font_draw (VGFT_FONT_T * font, VGfloat x, VGfloat y, const char * text, unsigned text_length, VGbitfield paint_modes)
Definition at line 335 of file vgft.c.
 {
    VGfloat descent = float_from_26_6(font->ft_face->size->metrics.descender);
    int last_draw = 0;
    int i = 0;
    y -= descent;
    for (;;) {
       int last = !text[i] || (text_length && i==text_length);
       if ((text[i] == '\n') || last)
       {
          draw_line(font, x, y, text + last_draw, i - last_draw, paint_modes);
          last_draw = i+1;
          y -= float_from_26_6(font->ft_face->size->metrics.height);
       }
       if (last)
       {
          break;
       }
       ++i;
    }
 }
vgft_font_init()
VCOS_STATUS_T vgft_font_init (VGFT_FONT_T * font)
Initialise a FT->VG font
Definition at line 174 of file vgft.c.
References VGFT_FONT_T::ft_face, NULL, VCOS_ENOMEM, VCOS_SUCCESS, VGFT_FONT_T::vg_font, VG_INVALID_HANDLE, and vgCreateFont().
 {
    font->ft_face = NULL;
    font->vg_font = vgCreateFont(0);
    if (font->vg_font == VG_INVALID_HANDLE)
    {
       return VCOS_ENOMEM;
    }
    return VCOS_SUCCESS;
 }
vgft_font_load_file()
VCOS_STATUS_T vgft_font_load_file (VGFT_FONT_T * font, const char * file)
Definition at line 194 of file vgft.c.
 {
    if (FT_New_Face(lib, file, 0, &font->ft_face)) {
       return VCOS_EINVAL;
    }
    return VCOS_SUCCESS;
 }
vgft_font_load_mem()
VCOS_STATUS_T vgft_font_load_mem (VGFT_FONT_T * font, void * mem, size_t len)
Load a font file from memory
Definition at line 185 of file vgft.c.
 {
    if (FT_New_Memory_Face(lib, mem, len, 0, &font->ft_face))
    {
       return VCOS_EINVAL;
    }
    return VCOS_SUCCESS;
 }
vgft_font_term()
void vgft_font_term (VGFT_FONT_T * font)
Release a font.
Definition at line 249 of file vgft.c.
References VGFT_FONT_T::ft_face, VGFT_FONT_T::vg_font, and vgDestroyFont().
Referenced by gx_font_cache_flush().
 {
    if (font->ft_face)
       FT_Done_Face(font->ft_face);
    if (font->vg_font)
       vgDestroyFont(font->vg_font);
    memset(font, 0, sizeof(*font));
 }
vgft_get_text_extents()
void vgft_get_text_extents (VGFT_FONT_T * font, const char * text, unsigned text_length, VGfloat unused0, VGfloat unused1, VGfloat * w, VGfloat * h)
Definition at line 394 of file vgft.c.
{
    int last_draw = 0;
    VGfloat max_x = 0;
    VGfloat y = 0;
    int i, last;
    for (i = 0, last = 0; !last; ++i) {
       last = !text[i] || (text_length && i==text_length);
       if ((text[i] == '\n') || last) {
          VGfloat x = 0;
          line_extents(font, &x, &y, text + last_draw, i - last_draw);
          last_draw = i + 1;
          y -= float_from_26_6(font->ft_face->size->metrics.height);
          if (x > max_x) max_x = x;
       }
    }
    *w = max_x;
    *h = -y;
 }
vgft_init()
int vgft_init (void)
Definition at line 38 of file vgft.c.
Referenced by gx_priv_font_init().
 {
    if (FT_Init_FreeType(&lib) == 0)
       return 0;
    else
    {
       return -1;
    }
 }
vgft_term()
void vgft_term (void)
Definition at line 48 of file vgft.c.
Referenced by gx_priv_font_term().
 {
    FT_Done_FreeType(lib);
 }