VideoCore Library: interface/vcos/vcos_init.h File Reference
vcos_init.h File Reference
#include "interface/vcos/vcos_types.h"
#include "vcos.h"
Functions
VCOSPRE_ VCOS_STATUS_T VCOSPOST_ vcos_init (void)
VCOSPRE_ void VCOSPOST_ vcos_deinit (void)
VCOSPRE_ void VCOSPOST_ vcos_global_lock (void)
VCOSPRE_ void VCOSPOST_ vcos_global_unlock (void)
VCOSPRE_ void VCOSPOST_ vcos_set_args (int argc, const char **argv)
VCOSPRE_ int VCOSPOST_ vcos_get_argc (void)
VCOSPRE_ const char **VCOSPOST_ vcos_get_argv (void)
VCOSPRE_ VCOS_STATUS_T VCOSPOST_ vcos_platform_init (void)
VCOSPRE_ void VCOSPOST_ vcos_platform_deinit (void)
Detailed Description
Some OS support libraries need some initialization. To support this, call vcos_init() function at the start of day; vcos_deinit() at the end.
Definition in file vcos_init.h.
Function Documentation
vcos_deinit()
VCOSPRE_ void VCOSPOST_ vcos_deinit (void)
vcos deinitialization. Call this function when vcos is no longer required, in order to free resources. Calls can be nested within the same process; they are reference counted so that only a call that decrements the reference count to 0 has any effect.
Note
On platforms/toolchains that support it, gcc's destructor attribute or similar is used to invoke this function after exit() or equivalent.
Returns
Status of initialisation.
Definition at line 56 of file vcos_init.c.
References vcos_assert, and vcos_global_lock().
 {
    vcos_global_lock();
    vcos_assert(init_refcount > 0);
    if (init_refcount > 0 && --init_refcount == 0)
       vcos_platform_deinit();
    vcos_global_unlock();
 }
vcos_get_argc()
VCOSPRE_ int VCOSPOST_ vcos_get_argc (void)
Return argc.
Definition at line 590 of file vcos_pthreads.c.
 {
    return vcos_argc;
 }
vcos_get_argv()
VCOSPRE_ const char** VCOSPOST_ vcos_get_argv (void)
Return argv.
Definition at line 595 of file vcos_pthreads.c.
 {
    return vcos_argv;
 }
vcos_global_lock()
VCOSPRE_ void VCOSPOST_ vcos_global_lock (void)
Acquire global lock. This must be available independent of vcos_init()/vcos_deinit().
Definition at line 431 of file vcos_pthreads.c.
Referenced by vcos_deinit(), and vcos_init().
 {
    pthread_mutex_lock(&lock);
 }
vcos_global_unlock()
VCOSPRE_ void VCOSPOST_ vcos_global_unlock (void)
Release global lock. This must be available independent of vcos_init()/vcos_deinit().
Definition at line 436 of file vcos_pthreads.c.
 {
    pthread_mutex_unlock(&lock);
 }
vcos_init()
VCOSPRE_ VCOS_STATUS_T VCOSPOST_ vcos_init (void)
vcos initialization. Call this function before using other vcos functions. Calls can be nested within the same process; they are reference counted so that only a call from uninitialized state has any effect.
Note
On platforms/toolchains that support it, gcc's constructor attribute or similar is used to invoke this function before main() or equivalent.
Returns
Status of initialisation.
Definition at line 42 of file vcos_init.c.
References vcos_global_lock(), and VCOS_SUCCESS.
Referenced by bcm_host_init(), main(), and raspitex_init().
 {
    VCOS_STATUS_T st = VCOS_SUCCESS;
    vcos_global_lock();
    if (init_refcount++ == 0)
       st = vcos_platform_init();
    vcos_global_unlock();
    return st;
 }
vcos_platform_deinit()
VCOSPRE_ void VCOSPOST_ vcos_platform_deinit (void)
Platform-specific de-initialisation. VCOS internal function, not part of public API, do not call from outside vcos. See vcos_platform_init() re reference counting. This function is called with vcos_global_lock held.
Definition at line 426 of file vcos_pthreads.c.
 {
    vcos_term(VCOS_INIT_ALL);
 }
vcos_platform_init()
VCOSPRE_ VCOS_STATUS_T VCOSPOST_ vcos_platform_init (void)
Platform-specific initialisation. VCOS internal function, not part of public API, do not call from outside vcos. vcos_init()/vcos_deinit() reference count calls, so this function is only called from an uninitialized state, i.e. there will not be two consecutive calls to vcos_platform_init() without an intervening call to vcos_platform_deinit(). This function is called with vcos_global_lock held.
Returns
Status of initialisation.
Definition at line 364 of file vcos_pthreads.c.
References _vcos_named_semaphore_init(), VCOS_INIT_NAMED_SEM, VCOS_INIT_PRINTF_LOCK, vcos_mutex_create(), vcos_once(), VCOS_SUCCESS, and vcos_verify.
 {
    VCOS_STATUS_T st;
    uint32_t flags = 0;
    int pst;
    st = _vcos_named_semaphore_init();
    if (!vcos_verify(st == VCOS_SUCCESS))
       goto end;
    flags |= VCOS_INIT_NAMED_SEM;
 #ifdef HAVE_MTRACE
    /* enable glibc memory debugging, if the environment
     * variable MALLOC_TRACE names a valid file.
     */
    mtrace();
 #endif
 #ifdef ANDROID
    st = vcos_mutex_create(&printf_lock, "printf");
    if (!vcos_verify(st == VCOS_SUCCESS))
       goto end;
    flags |= VCOS_INIT_PRINTF_LOCK;
 #endif
    st = vcos_once(&current_thread_key_once, current_thread_key_init);
    if (!vcos_verify(st == VCOS_SUCCESS))
       goto end;
    /* Initialise a VCOS wrapper for the thread which called vcos_init. */
    st = vcos_semaphore_create(&vcos_thread_main.suspend, NULL, 0);
    if (!vcos_verify(st == VCOS_SUCCESS))
       goto end;
    flags |= VCOS_INIT_MAIN_SEM;
    vcos_thread_main.thread = pthread_self();
    pst = pthread_setspecific(_vcos_thread_current_key, &vcos_thread_main);
    if (!vcos_verify(pst == 0))
    {
       st = VCOS_EINVAL;
       goto end;
    }
    st = vcos_msgq_init();
    if (!vcos_verify(st == VCOS_SUCCESS))
       goto end;
    flags |= VCOS_INIT_MSGQ;
    vcos_logging_init();
 end:
    if (st != VCOS_SUCCESS)
       vcos_term(flags);
    return st;
 }
vcos_set_args()
VCOSPRE_ void VCOSPOST_ vcos_set_args (int argc, const char ** argv)
Pass in the argv/argc arguments passed to main()
Definition at line 584 of file vcos_pthreads.c.
 {
    vcos_argc = argc;
    vcos_argv = argv;
 }