VideoCore Library: ILCS_CONFIG_T Struct Reference
ILCS_CONFIG_T Struct Reference
#include <vcilcs.h>
Public Attributes
IL_FN_T * fns
ILCS_COMMON_T *(* ilcs_common_init)(ILCS_SERVICE_T *)
void(* ilcs_common_deinit)(ILCS_COMMON_T *st)
void(* ilcs_thread_init)(ILCS_COMMON_T *st)
unsigned char *(* ilcs_mem_lock)(OMX_BUFFERHEADERTYPE *buffer)
void(* ilcs_mem_unlock)(OMX_BUFFERHEADERTYPE *buffer)
Detailed Description
Definition at line 44 of file vcilcs.h.
Member Data Documentation
fns
IL_FN_T* ILCS_CONFIG_T::fns
Definition at line 45 of file vcilcs.h.
Referenced by vcilcs_config().
ilcs_common_deinit
void(* ILCS_CONFIG_T::ilcs_common_deinit) (ILCS_COMMON_T *st)
Definition at line 47 of file vcilcs.h.
ilcs_common_init
ILCS_COMMON_T*(* ILCS_CONFIG_T::ilcs_common_init) (ILCS_SERVICE_T *)
Definition at line 46 of file vcilcs.h.
ilcs_mem_lock
unsigned char*(* ILCS_CONFIG_T::ilcs_mem_lock) (OMX_BUFFERHEADERTYPE *buffer)
Definition at line 49 of file vcilcs.h.
Referenced by ilcs_pass_buffer(), and ilcs_receive_buffer().
ilcs_mem_unlock
void(* ILCS_CONFIG_T::ilcs_mem_unlock) (OMX_BUFFERHEADERTYPE *buffer)
Definition at line 50 of file vcilcs.h.
Referenced by ilcs_pass_buffer(), and ilcs_receive_buffer().
ilcs_thread_init
void(* ILCS_CONFIG_T::ilcs_thread_init) (ILCS_COMMON_T *st)
Definition at line 48 of file vcilcs.h.
The documentation for this struct was generated from the following file:
interface/vmcs_host/vcilcs.h