VideoCore Library: interface/vcos/vcos_mem.h File Reference
vcos_mem.h File Reference
#include "interface/vcos/vcos_types.h"
#include "vcos.h"
Macros
#define VCOS_MEM_H
#define VCOS_MEM_H
Functions
VCOS_INLINE_DECL void * vcos_malloc (VCOS_UNSIGNED size, const char *description)
void * vcos_kmalloc (VCOS_UNSIGNED size, const char *description)
void * vcos_kcalloc (VCOS_UNSIGNED num, VCOS_UNSIGNED size, const char *description)
VCOS_INLINE_DECL void * vcos_calloc (VCOS_UNSIGNED num, VCOS_UNSIGNED size, const char *description)
VCOS_INLINE_DECL void vcos_free (void *ptr)
void vcos_kfree (void *ptr)
VCOS_INLINE_DECL void * vcos_malloc_aligned (VCOS_UNSIGNED size, VCOS_UNSIGNED align, const char *description)
VCOS_INLINE_DECL unsigned long vcos_get_free_mem (void)
Detailed Description
Memory allocation api (malloc/free equivalents) is for benefit of host applications. VideoCore code should use rtos_XXX functions.
Definition in file vcos_mem.h.
Macro Definition Documentation
VCOS_MEM_H [1/2]
#define VCOS_MEM_H
VCOS_MEM_H [2/2]
#define VCOS_MEM_H
Function Documentation
vcos_calloc()
VCOS_INLINE_DECL void* vcos_calloc (VCOS_UNSIGNED num, VCOS_UNSIGNED size, const char * description)
Allocate cleared memory
Parameters
num Number of items to allocate.
size Size of each item in bytes.
description Description, to aid in debugging. May be ignored internally on some platforms.
Referenced by gx_alloc_context(), gx_create_pbuffer(), mmal_clock_create(), mmal_component_supplier_register(), mmal_format_alloc(), mmal_format_extradata_alloc(), mmal_graph_create(), mmal_pool_create_with_allocator(), mmal_port_alloc(), mmal_port_parameter_alloc_get(), mmal_ports_alloc(), mmal_wrapper_create(), and svp_create().
vcos_free()
VCOS_INLINE_DECL void vcos_free (void * ptr)
Free memory
Free memory that has been allocated.
Referenced by graphics_delete_resource(), gx_font_cache_flush(), gx_free_pixels(), gx_priv_font_term(), ilclient_cleanup_components(), ilclient_destroy(), ilclient_disable_port_buffers(), khrn_platform_free(), mmal_clock_create(), mmal_format_extradata_alloc(), mmal_format_free(), mmal_graph_create(), mmal_graph_destroy(), mmal_list_create(), mmal_list_destroy(), mmal_pool_create_with_allocator(), mmal_pool_destroy(), mmal_port_free(), mmal_port_parameter_alloc_get(), mmal_port_parameter_free(), mmal_port_payload_free(), mmal_ports_clock_free(), mmal_ports_free(), mmal_queue_create(), mmal_queue_destroy(), mmal_wrapper_create(), mmal_wrapper_destroy(), svp_destroy(), vchiu_queue_delete(), vcil_in_free_buffer(), vcil_in_use_buffer(), vcos_dummy_thread_create(), vcos_generic_blockpool_create_on_heap(), vcos_generic_blockpool_delete(), vcos_generic_blockpool_free(), and vcos_thread_exit().
vcos_get_free_mem()
VCOS_INLINE_DECL unsigned long vcos_get_free_mem (void)
Return the amount of free heap memory
vcos_kcalloc()
void* vcos_kcalloc (VCOS_UNSIGNED num, VCOS_UNSIGNED size, const char * description)
vcos_kfree()
void vcos_kfree (void * ptr)
vcos_kmalloc()
void* vcos_kmalloc (VCOS_UNSIGNED size, const char * description)
vcos_malloc()
VCOS_INLINE_DECL void* vcos_malloc (VCOS_UNSIGNED size, const char * description)
Allocate memory
Parameters
size Size of memory to allocate
description Description, to aid in debugging. May be ignored internally on some platforms.
Referenced by gx_priv_get_pixels(), ilclient_init(), ilcs_init(), khrn_platform_malloc(), mmal_connection_create(), mmal_list_create(), mmal_port_payload_alloc(), mmal_queue_create(), vcil_out_create_component(), vcos_dummy_thread_create(), vcos_generic_blockpool_alloc(), and vcos_generic_blockpool_create_on_heap().
vcos_malloc_aligned()
VCOS_INLINE_DECL void* vcos_malloc_aligned (VCOS_UNSIGNED size, VCOS_UNSIGNED align, const char * description)
Allocate aligned memory
Allocate memory aligned on the specified boundary.
Parameters
size Size of memory to allocate
description Description, to aid in debugging. May be ignored internally on some platforms.
Referenced by vc_vchi_cec_init(), vc_vchi_filesys_init(), and vcil_in_use_buffer().