VideoCore Library: containers/dummy/dummy_writer.c File Reference
dummy_writer.c File Reference
#include <stdlib.h>
#include <string.h>
#include "containers/core/containers_private.h"
#include "containers/core/containers_io_helpers.h"
#include "containers/core/containers_utils.h"
#include "containers/core/containers_logging.h"
Classes
struct VC_CONTAINER_MODULE_T
Typedefs
typedef struct VC_CONTAINER_MODULE_T VC_CONTAINER_MODULE_T
Functions
VC_CONTAINER_STATUS_T dummy_writer_open (VC_CONTAINER_T *)
Typedef Documentation
VC_CONTAINER_MODULE_T
typedef struct VC_CONTAINER_MODULE_T VC_CONTAINER_MODULE_T
Function Documentation
dummy_writer_open()
VC_CONTAINER_STATUS_T dummy_writer_open (VC_CONTAINER_T * p_ctx)
Definition at line 97 of file dummy_writer.c.
References VC_CONTAINER_T::capabilities, error(), extension, VC_CONTAINER_PRIVATE_T::module, VC_CONTAINER_PRIVATE_T::pf_close, VC_CONTAINER_T::priv, VC_CONTAINER_MODULE_T::status, VC_CONTAINER_MODULE_T::track, VC_CONTAINER_T::tracks, VC_CONTAINER_PRIVATE_T::uri, VC_CONTAINER_CAPS_DYNAMIC_TRACK_ADD, VC_CONTAINER_ERROR_FORMAT_INVALID, VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED, VC_CONTAINER_ERROR_OUT_OF_MEMORY, vc_uri_find_query(), and vc_uri_path_extension().
 {
    const char *extension = vc_uri_path_extension(p_ctx->priv->uri);
    VC_CONTAINER_MODULE_T *module = 0;
    VC_CONTAINER_STATUS_T status = VC_CONTAINER_ERROR_FORMAT_INVALID;
    /* Check if the user has specified a container */
    vc_uri_find_query(p_ctx->priv->uri, 0, "container", &extension);
    /* Check we're the right writer for this */
    if(!extension)
       return VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED;
    if(strcasecmp(extension, "dummy"))
       return VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED;
    /* Allocate our context */
    module = malloc(sizeof(*module));
    if(!module) { status = VC_CONTAINER_ERROR_OUT_OF_MEMORY; goto error; }
    memset(module, 0, sizeof(*module));
    p_ctx->priv->module = module;
    p_ctx->tracks = module->track;
    p_ctx->capabilities |= VC_CONTAINER_CAPS_DYNAMIC_TRACK_ADD;
    p_ctx->priv->pf_close = dummy_writer_close;
    p_ctx->priv->pf_write = dummy_writer_write;
    p_ctx->priv->pf_control = dummy_writer_control;
    return VC_CONTAINER_SUCCESS;
  error:
    LOG_DEBUG(p_ctx, "dummy: error opening stream (%i)", status);
    return status;
 }