VideoCore Library: host_applications/linux/apps/raspicam/libgps_loader.h File Reference
libgps_loader.h File Reference
#include "gps.h"
Classes
struct gpsd_info
Macros
#define LIBGPS_SO_VERSION "libgps.so.23"
Functions
void gpsd_init (gpsd_info *gpsd)
int libgps_load (gpsd_info *gpsd)
void libgps_unload (gpsd_info *gpsd)
int connect_gpsd (gpsd_info *gpsd)
int disconnect_gpsd (gpsd_info *gpsd)
int wait_gps_time (gpsd_info *gpsd, int timeout_s)
int read_gps_data_once (gpsd_info *gpsd)
int deg_to_str (double f, char *buf, int buf_size)
Variables
const char * LIBGPS_FILE
Macro Definition Documentation
LIBGPS_SO_VERSION
#define LIBGPS_SO_VERSION "libgps.so.23"
Definition at line 34 of file libgps_loader.h.
Function Documentation
connect_gpsd()
int connect_gpsd (gpsd_info * gpsd)
Definition at line 91 of file libgps_loader.c.
References gpsd_info::gps_open, gpsd_info::gps_stream, gpsd_info::gpsd_connected, gpsd_info::gpsdata, gpsd_info::libgps_handle, NULL, gpsd_info::port, gpsd_info::server, and WATCH_ENABLE.
Referenced by raspi_gps_setup().
 {
    if (gpsd->libgps_handle == NULL)
       return -1;
    if (!gpsd->gpsd_connected)
    {
       if (gpsd->gps_open(gpsd->server, gpsd->port, &gpsd->gpsdata) != 0)
          return -1;
       gpsd->gpsd_connected = 1;
       gpsd->gps_stream(&gpsd->gpsdata, WATCH_ENABLE, NULL);
    }
    return 0;
 }
deg_to_str()
int deg_to_str (double f, char * buf, int buf_size)
Definition at line 159 of file libgps_loader.c.
 {
    double fsec, fdeg, fmin;
    if (buf_size <= 0)
       return -1;
    *buf = 0;
    if (f < 0 || f > 360)
       return -1;
    fmin = modf(f, &fdeg);
    fsec = modf(fmin * 60, &fmin);
    fsec *= 60;
    snprintf(buf, buf_size, "%03d/1,%02d/1,%05d/1000", (int)fdeg, (int)fmin, (int)(fsec*1000));
    return 0;
 }
disconnect_gpsd()
int disconnect_gpsd (gpsd_info * gpsd)
Definition at line 105 of file libgps_loader.c.
References gpsd_info::gps_close, gpsd_info::gps_stream, gpsd_info::gpsd_connected, gpsd_info::gpsdata, gpsd_info::libgps_handle, NULL, and WATCH_DISABLE.
Referenced by libgps_unload(), and raspi_gps_shutdown().
 {
    if (gpsd->libgps_handle == NULL)
       return -1;
    if (gpsd->gpsd_connected)
    {
       gpsd->gps_stream(&gpsd->gpsdata, WATCH_DISABLE, NULL);
       gpsd->gps_close(&gpsd->gpsdata);
       gpsd->gpsd_connected = 0;
    }
    return 0;
 }
gpsd_init()
void gpsd_init (gpsd_info * gpsd)
Definition at line 84 of file libgps_loader.c.
References DEFAULT_GPSD_PORT, gpsd_info::port, and gpsd_info::server.
Referenced by raspi_gps_setup().
 {
    memset(gpsd, 0, sizeof(gpsd_info));
    gpsd->server = "localhost";
    gpsd->port = DEFAULT_GPSD_PORT;
 }
libgps_load()
int libgps_load (gpsd_info * gpsd)
Definition at line 51 of file libgps_loader.c.
References dlerror(), dlopen(), LIBGPS_FILE, gpsd_info::libgps_handle, and RTLD_LAZY.
Referenced by raspi_gps_setup().
 {
    int err = 0;
    gpsd->libgps_handle = dlopen(LIBGPS_FILE, RTLD_LAZY);
    if (!gpsd->libgps_handle)
    {
       fprintf(stderr, "%s\n", dlerror());
       return -1;
    }
    err |= libgps_load_sym((void **)(&gpsd->gps_read),    gpsd->libgps_handle, "gps_read");
    err |= libgps_load_sym((void **)(&gpsd->gps_waiting), gpsd->libgps_handle, "gps_waiting");
    err |= libgps_load_sym((void **)(&gpsd->gps_open),    gpsd->libgps_handle, "gps_open");
    err |= libgps_load_sym((void **)(&gpsd->gps_close),   gpsd->libgps_handle, "gps_close");
    err |= libgps_load_sym((void **)(&gpsd->gps_errstr),  gpsd->libgps_handle, "gps_errstr");
    err |= libgps_load_sym((void **)(&gpsd->gps_stream),  gpsd->libgps_handle, "gps_stream");
    if (err)
       return -1;
    return 0;
 }
libgps_unload()
void libgps_unload (gpsd_info * gpsd)
Definition at line 74 of file libgps_loader.c.
References disconnect_gpsd(), dlclose(), gpsd_info::libgps_handle, and NULL.
Referenced by raspi_gps_setup(), and raspi_gps_shutdown().
 {
    if (gpsd->libgps_handle)
    {
       disconnect_gpsd(gpsd);
       dlclose(gpsd->libgps_handle);
       gpsd->libgps_handle = NULL;
    }
 }
read_gps_data_once()
int read_gps_data_once (gpsd_info * gpsd)
Definition at line 138 of file libgps_loader.c.
References gpsd_info::gps_close, gpsd_info::gps_read, gpsd_info::gps_waiting, gpsd_info::gpsd_connected, gpsd_info::gpsdata, gpsd_info::libgps_handle, and NULL.
Referenced by wait_gps_time().
 {
    if (gpsd->libgps_handle == NULL)
       return -1;
    if (gpsd->gpsd_connected)
    {
       if (gpsd->gps_waiting(&gpsd->gpsdata, 200))
       {
          int ret = gpsd->gps_read(&gpsd->gpsdata);
          if (ret < 0)
          {
             gpsd->gps_close(&gpsd->gpsdata);
             gpsd->gpsd_connected = 0;
             ret = 0;
          }
          return ret;
       }
    }
    return 0;
 }
wait_gps_time()
int wait_gps_time (gpsd_info * gpsd, int timeout_s)
Definition at line 118 of file libgps_loader.c.
References gpsd_info::gps_waiting, gpsd_info::gpsd_connected, gpsd_info::gpsdata, gpsd_info::libgps_handle, NULL, gps_data_t::online, read_gps_data_once(), gps_data_t::set, and TIME_SET.
Referenced by raspi_gps_setup().
 {
    if (gpsd->libgps_handle == NULL)
       return -1;
    if (gpsd->gpsd_connected)
    {
       gps_mask_t mask = TIME_SET;
       time_t start = time(NULL);
       while ((time(NULL) - start < timeout_s) &&
              ((!gpsd->gpsdata.online) || ((gpsd->gpsdata.set & mask) == 0)))
       {
          if (gpsd->gps_waiting(&gpsd->gpsdata, 200))
             read_gps_data_once(gpsd);
       }
       if ((gpsd->gpsdata.online) && ((gpsd->gpsdata.set & mask) != 0))
          return 0;
    }
    return -1;
 }
Variable Documentation
LIBGPS_FILE
const char* LIBGPS_FILE
Definition at line 36 of file libgps_loader.c.
Referenced by libgps_load().