VideoCore Library: interface/khronos/common/linux/khrn_client_platform_linux.c File Reference
khrn_client_platform_linux.c File Reference
#include "interface/khronos/common/khrn_client_platform.h"
#include "interface/khronos/common/khrn_client.h"
#include "interface/khronos/common/khrn_client_rpc.h"
#include "interface/khronos/common/khrn_int_ids.h"
#include <stdio.h>
#include <string.h>
#include <assert.h>
Macros
#define VCOS_LOG_CATEGORY (&khrn_client_log)
#define CHROMA_KEY_565 0x0001
#define NUM_PIXMAP_BINDINGS 16
Functions
void vc_vchi_khronos_init ()
VCOS_STATUS_T khronos_platform_semaphore_create (PLATFORM_SEMAPHORE_T *sem, int name[3], int count)
uint64_t khronos_platform_get_process_id ()
void * platform_tls_get (PLATFORM_TLS_T tls)
void * platform_tls_get_check (PLATFORM_TLS_T tls)
void platform_hint_thread_finished ()
void * khrn_platform_malloc (size_t size, const char *name)
void khrn_platform_free (void *v)
bool platform_get_pixmap_info (EGLNativePixmapType pixmap, KHRN_IMAGE_WRAP_T *image)
void khrn_platform_release_pixmap_info (EGLNativePixmapType pixmap, KHRN_IMAGE_WRAP_T *image)
void platform_get_pixmap_server_handle (EGLNativePixmapType pixmap, uint32_t *handle)
bool platform_match_pixmap_api_support (EGLNativePixmapType pixmap, uint32_t api_support)
void platform_client_lock (void)
void platform_client_release (void)
void platform_init_rpc (struct CLIENT_THREAD_STATE *state)
void platform_term_rpc (struct CLIENT_THREAD_STATE *state)
void platform_maybe_free_process (void)
void platform_destroy_winhandle (void *a, uint32_t b)
void platform_surface_update (uint32_t handle)
void egl_gce_win_change_image (void)
void platform_retrieve_pixmap_completed (EGLNativePixmapType pixmap)
void platform_send_pixmap_completed (EGLNativePixmapType pixmap)
uint32_t platform_memcmp (const void *aLeft, const void *aRight, size_t aLen)
void platform_memcpy (void *aTrg, const void *aSrc, size_t aLength)
EGLDisplay khrn_platform_set_display_id (EGLNativeDisplayType display_id)
uint32_t khrn_platform_get_window_position (EGLNativeWindowType win)
void khrn_platform_bind_pixmap_to_egl_image (EGLNativePixmapType pixmap, EGLImageKHR egl_image, bool send)
void khrn_platform_unbind_pixmap_from_egl_image (EGLImageKHR egl_image)
uint32_t platform_get_color_format (uint32_t format)
void platform_dequeue (EGLDisplay dpy, EGLNativeWindowType window)
Variables
VCOS_LOG_CAT_T khrn_client_log
Macro Definition Documentation
CHROMA_KEY_565
#define CHROMA_KEY_565 0x0001
Definition at line 53 of file khrn_client_platform_linux.c.
Referenced by platform_memcpy().
NUM_PIXMAP_BINDINGS
#define NUM_PIXMAP_BINDINGS 16
Definition at line 616 of file khrn_client_platform_linux.c.
Referenced by khrn_platform_bind_pixmap_to_egl_image(), and khrn_platform_unbind_pixmap_from_egl_image().
VCOS_LOG_CATEGORY
#define VCOS_LOG_CATEGORY (&khrn_client_log)
Definition at line 27 of file khrn_client_platform_linux.c.
Function Documentation
egl_gce_win_change_image()
void egl_gce_win_change_image (void)
Definition at line 390 of file khrn_client_platform_linux.c.
References assert().
 {
    assert(0);
 }
khrn_platform_bind_pixmap_to_egl_image()
void khrn_platform_bind_pixmap_to_egl_image (EGLNativePixmapType pixmap, EGLImageKHR egl_image, bool send)
Definition at line 688 of file khrn_client_platform_linux.c.
References NUM_PIXMAP_BINDINGS.
 {
    int i;
    for (i = 0; i < NUM_PIXMAP_BINDINGS; i++)
    {
       if (!pixmap_binding[i].used)
       {
          vcos_log_trace("khrn_platform_bind_pixmap_to_egl_image %d", i);
          pixmap_binding[i].used = true;
          pixmap_binding[i].pixmap = pixmap;
          pixmap_binding[i].egl_image = egl_image;
          pixmap_binding[i].send = send;
          if(send)
             send_bound_pixmap(i);
          return;
       }
    }
    vcos_assert(0);  /* Not enough NUM_PIXMAP_BINDINGS? */
 }
khrn_platform_free()
void khrn_platform_free (void * v)
Free memory
Parameters
v Pointer to memory area to free
Definition at line 156 of file khrn_client_platform_linux.c.
References ABGR_8888_RSO, ARGB_8888_RSO, KHRN_IMAGE_WRAP_T::aux, BGR_888_RSO, KHRN_IMAGE_WRAP_T::format, KHRN_IMAGE_WRAP_T::height, IMAGE_FORMAT_INVALID, NULL, pixmap, platform_get_pixmap_info(), RGB_565_RSO, KHRN_IMAGE_WRAP_T::storage, KHRN_IMAGE_WRAP_T::stride, vcos_free(), and KHRN_IMAGE_WRAP_T::width.
Referenced by egl_context_maybe_free(), khrn_cache_term(), khrn_vector_clear(), khrn_vector_extend(), khrn_vector_term(), and vg_client_shared_state_alloc().
 {
    if (v)
    {
       vcos_free(v);
    }
 }
khrn_platform_get_window_position()
uint32_t khrn_platform_get_window_position (EGLNativeWindowType win)
Definition at line 610 of file khrn_client_platform_linux.c.
Referenced by khrn_platform_set_display_id().
 {
    return xxx_position;
 }
khrn_platform_malloc()
void* khrn_platform_malloc (size_t size, const char * name)
Allocate memory
Parameters
size Size in bytes of memory block to allocate
Returns
pointer to memory block
Definition at line 146 of file khrn_client_platform_linux.c.
References vcos_malloc().
Referenced by khrn_vector_extend(), khrn_vector_init(), and vg_client_shared_state_alloc().
 {
    return vcos_malloc(size, name);
 }
khrn_platform_release_pixmap_info()
void khrn_platform_release_pixmap_info (EGLNativePixmapType pixmap, KHRN_IMAGE_WRAP_T * image)
Definition at line 295 of file khrn_client_platform_linux.c.
Referenced by egl_config_check_attribs(), and egl_config_filter().
 {
    /* Nothing to do */
 }
khrn_platform_set_display_id()
EGLDisplay khrn_platform_set_display_id (EGLNativeDisplayType display_id)
Definition at line 467 of file khrn_client_platform_linux.c.
References EGL_DEFAULT_DISPLAY, EGL_NO_DISPLAY, and khrn_platform_get_window_position().
Referenced by platform_memcpy().
 {
    if (display_id == EGL_DEFAULT_DISPLAY)
       return (EGLDisplay)1;
    else
       return EGL_NO_DISPLAY;
 }
khrn_platform_unbind_pixmap_from_egl_image()
void khrn_platform_unbind_pixmap_from_egl_image (EGLImageKHR egl_image)
Definition at line 710 of file khrn_client_platform_linux.c.
References NUM_PIXMAP_BINDINGS.
 {
    int i;
    for (i = 0; i < NUM_PIXMAP_BINDINGS; i++)
    {
       if (pixmap_binding[i].used && pixmap_binding[i].egl_image == egl_image)
       {
          pixmap_binding[i].used = false;
       }
    }
 }
khronos_platform_get_process_id()
uint64_t khronos_platform_get_process_id (void)
Definition at line 78 of file khrn_client_platform_linux.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    return rpc_get_client_id(thread);
 }
khronos_platform_semaphore_create()
VCOS_STATUS_T khronos_platform_semaphore_create (PLATFORM_SEMAPHORE_T * sem, int name[3], int count)
Definition at line 71 of file khrn_client_platform_linux.c.
 {
    char buf[64];
    vcos_snprintf(buf,sizeof(buf),"KhanSemaphore%08x%08x%08x", name[0], name[1], name[2]);
    return vcos_named_semaphore_create(sem, buf, count);
 }
platform_client_lock()
void platform_client_lock (void)
Definition at line 351 of file khrn_client_platform_linux.c.
References client_mutex, and platform_mutex_acquire().
 {
    platform_mutex_acquire(&client_mutex);
 }
platform_client_release()
void platform_client_release (void)
Definition at line 356 of file khrn_client_platform_linux.c.
References client_mutex, and platform_mutex_release().
 {
    platform_mutex_release(&client_mutex);
 }
platform_dequeue()
void platform_dequeue (EGLDisplay dpy, EGLNativeWindowType window)
Definition at line 829 of file khrn_client_platform_linux.c.
 {}
platform_destroy_winhandle()
void platform_destroy_winhandle (void * a, uint32_t b)
Definition at line 376 of file khrn_client_platform_linux.c.
References assert().
 {
    assert(1);
 }
platform_get_color_format()
uint32_t platform_get_color_format (uint32_t format)
Definition at line 828 of file khrn_client_platform_linux.c.
 { return format; }
platform_get_pixmap_info()
bool platform_get_pixmap_info (EGLNativePixmapType pixmap, KHRN_IMAGE_WRAP_T * image)
Definition at line 282 of file khrn_client_platform_linux.c.
References KHRN_IMAGE_WRAP_T::format.
Referenced by egl_config_check_attribs(), egl_config_filter(), and khrn_platform_free().
 {
    image->format = convert_format(((uint32_t *)pixmap)[4]);
    image->width = ((uint32_t *)pixmap)[2];
    image->height = ((uint32_t *)pixmap)[3];
    /* can't actually access data */
    image->stride = 0;
    image->aux = 0;
    image->storage = 0;
    return image->format != 0;
 }
platform_get_pixmap_server_handle()
void platform_get_pixmap_server_handle (EGLNativePixmapType pixmap, uint32_t * handle)
Definition at line 301 of file khrn_client_platform_linux.c.
 {
    handle[0] = ((uint32_t *)pixmap)[0];
    handle[1] = ((uint32_t *)pixmap)[1];
 }
platform_hint_thread_finished()
void platform_hint_thread_finished (void)
Definition at line 126 of file khrn_client_platform_linux.c.
 {
    /*
       todo: should we do this:
       vcos_thread_deregister_at_exit(client_thread_detach);
       client_thread_detach();
       here?
    */
 }
platform_init_rpc()
void platform_init_rpc (struct CLIENT_THREAD_STATE * state)
Definition at line 361 of file khrn_client_platform_linux.c.
 {
    assert(1);
 }
platform_match_pixmap_api_support()
bool platform_match_pixmap_api_support (EGLNativePixmapType pixmap, uint32_t api_support)
Definition at line 307 of file khrn_client_platform_linux.c.
References EGL_OPENGL_BIT, EGL_OPENGL_ES2_BIT, EGL_OPENGL_ES_BIT, EGL_OPENVG_BIT, EGL_PIXEL_FORMAT_GLES2_TEXTURE_BRCM, EGL_PIXEL_FORMAT_GLES_TEXTURE_BRCM, EGL_PIXEL_FORMAT_RENDER_GL_BRCM, EGL_PIXEL_FORMAT_RENDER_GLES2_BRCM, EGL_PIXEL_FORMAT_RENDER_GLES_BRCM, EGL_PIXEL_FORMAT_RENDER_VG_BRCM, EGL_PIXEL_FORMAT_VG_IMAGE_BRCM, error(), pixmap, and verify.
Referenced by egl_config_filter().
 {
    return
       (!(api_support & EGL_OPENGL_BIT) || (((uint32_t *)pixmap)[4] & EGL_PIXEL_FORMAT_RENDER_GL_BRCM)) &&
       (!(api_support & EGL_OPENGL_ES_BIT) || (((uint32_t *)pixmap)[4] & EGL_PIXEL_FORMAT_RENDER_GLES_BRCM)) &&
       (!(api_support & EGL_OPENGL_ES2_BIT) || (((uint32_t *)pixmap)[4] & EGL_PIXEL_FORMAT_RENDER_GLES2_BRCM)) &&
       (!(api_support & EGL_OPENVG_BIT) || (((uint32_t *)pixmap)[4] & EGL_PIXEL_FORMAT_RENDER_VG_BRCM));
 }
platform_maybe_free_process()
void platform_maybe_free_process (void)
Definition at line 371 of file khrn_client_platform_linux.c.
References assert().
 {
    assert(1);
 }
platform_memcmp()
uint32_t platform_memcmp (const void * aLeft, const void * aRight, size_t aLen)
Definition at line 405 of file khrn_client_platform_linux.c.
 {
    return memcmp(aLeft, aRight, aLen);
 }
platform_memcpy()
void platform_memcpy (void * aTrg, const void * aSrc, size_t aLength)
Definition at line 410 of file khrn_client_platform_linux.c.
References CHROMA_KEY_565, EGL_NO_DISPLAY, khrn_platform_set_display_id(), NULL, platform_get_dimensions(), and platform_get_handle().
 {
    memcpy(aTrg, aSrc, aLength);
 }
platform_retrieve_pixmap_completed()
void platform_retrieve_pixmap_completed (EGLNativePixmapType pixmap)
Definition at line 395 of file khrn_client_platform_linux.c.
References assert().
 {
    assert(0);
 }
platform_send_pixmap_completed()
void platform_send_pixmap_completed (EGLNativePixmapType pixmap)
Definition at line 400 of file khrn_client_platform_linux.c.
References assert().
 {
    assert(0);
 }
platform_surface_update()
void platform_surface_update (uint32_t handle)
Definition at line 381 of file khrn_client_platform_linux.c.
 {
    /*
    XXX This seems as good a place as any to do the client side pixmap hack.
    (called from eglSwapBuffers)
    */
    send_bound_pixmaps();
 }
platform_term_rpc()
void platform_term_rpc (struct CLIENT_THREAD_STATE * state)
Definition at line 366 of file khrn_client_platform_linux.c.
 {
    assert(1);
 }
platform_tls_get()
void* platform_tls_get (PLATFORM_TLS_T tls)
Definition at line 87 of file khrn_client_platform_linux.c.
Referenced by platform_tls_get_check().
 {
    void *ret;
    if (!process_attached)
       /* TODO: this isn't thread safe */
    {
       vcos_log_trace("Attaching process");
       client_process_attach();
       process_attached = true;
       tls = client_tls;
       vc_vchi_khronos_init();
    }
    ret = vcos_tls_get(tls);
    if (!ret)
    {
      /* The problem here is that on VCFW, the first notification we get that a thread
        * exists at all is when it calls an arbitrary EGL function. We need to detect this
        * case and initiliase the per-thread state.
        *
        * On Windows this gets done in DllMain.
        */
       client_thread_attach();
       vcos_thread_at_exit(client_thread_detach, NULL);
       ret = vcos_tls_get(tls);
    }
    return ret;
 }
platform_tls_get_check()
void* platform_tls_get_check (PLATFORM_TLS_T tls)
Definition at line 118 of file khrn_client_platform_linux.c.
References platform_tls_get().
 {
    return platform_tls_get(tls);
 }
vc_vchi_khronos_init()
void vc_vchi_khronos_init ()
Definition at line 169 of file khrn_client_rpc_linux.c.
References vchiq_service_params_struct::callback, vchiq_service_params_struct::fourcc, FOURCC_KHAN, khan_callback(), NULL, status, UNUSED_NDEBUG, vchiq_service_params_struct::userdata, VC_KHRN_VERSION, vchiq_connect(), vchiq_initialise(), vchiq_open_service(), VCHIQ_SUCCESS, vcos_assert, vcos_event_create(), VCOS_SUCCESS, vchiq_service_params_struct::version, and vchiq_service_params_struct::version_min.
 {
    VCOS_STATUS_T status = vcos_event_create(&bulk_event, NULL);
    UNUSED_NDEBUG(status);
    vcos_assert(status == VCOS_SUCCESS);
    if (vchiq_initialise(&khrn_vchiq_instance) != VCHIQ_SUCCESS)
    {
       vcos_log_error("* failed to open vchiq device");
       exit(1);
    }
    vcos_log_trace("gldemo: connecting");
    if (vchiq_connect(khrn_vchiq_instance) != VCHIQ_SUCCESS)
    {
       vcos_log_error("* failed to connect");
       exit(1);
    }
    VCHIQ_STATUS_T khan_return, khrn_return, khhn_return;
    VCHIQ_SERVICE_PARAMS_T params;
    params.userdata = NULL;
    params.version = VC_KHRN_VERSION;
    params.version_min = VC_KHRN_VERSION;
    params.fourcc = FOURCC_KHAN;
    params.callback = khan_callback;
    khan_return = vchiq_open_service(khrn_vchiq_instance, &params, &vchiq_khan_service);
    params.fourcc = FOURCC_KHRN;
    params.callback = khrn_callback;
    khrn_return = vchiq_open_service(khrn_vchiq_instance, &params, &vchiq_khrn_service);
    params.fourcc = FOURCC_KHHN;
    params.callback = khhn_callback;
    khhn_return = vchiq_open_service(khrn_vchiq_instance, &params, &vchiq_khhn_service);
    if (khan_return != VCHIQ_SUCCESS ||
        khrn_return != VCHIQ_SUCCESS ||
        khhn_return != VCHIQ_SUCCESS)
    {
       vcos_log_error("* failed to add service - already in use?");
       exit(1);
    }
    vchiu_queue_init(&khrn_queue, 64);
    vchiu_queue_init(&khhn_queue, 64);
    vcos_log_trace("gldemo: connected");
    /*
       attach to process (there's just one)
    */
 //   bool success = client_process_attach();
 //   vcos_assert(success);
 }
Variable Documentation
egl_image
EGLImageKHR egl_image
Definition at line 622 of file khrn_client_platform_linux.c.
khrn_client_log
VCOS_LOG_CAT_T khrn_client_log
Definition at line 57 of file khrn_client.c.
pixmap
EGLNativePixmapType pixmap
Definition at line 621 of file khrn_client_platform_linux.c.
Referenced by egl_config_filter(), khrn_platform_free(), and platform_match_pixmap_api_support().
send
bool send
Definition at line 620 of file khrn_client_platform_linux.c.
Referenced by vc_container_net_write().
used
bool used
Definition at line 619 of file khrn_client_platform_linux.c.
Referenced by raspicamcontrol_parse_cmdline(), and raspipreview_parse_cmdline().