VideoCore Library: containers/wav/wav_reader.c File Reference
wav_reader.c File Reference
#include <stdlib.h>
#include <string.h>
#include "containers/core/containers_private.h"
#include "containers/core/containers_io_helpers.h"
#include "containers/core/containers_utils.h"
#include "containers/core/containers_logging.h"
#include "containers/core/containers_waveformat.h"
Classes
struct VC_CONTAINER_MODULE_T
Macros
#define CONTAINER_IS_LITTLE_ENDIAN
#define CONTAINER_HELPER_LOG_INDENT(a) 0
#define WAV_EXTRADATA_MAX 16
#define BLOCK_SIZE (16*1024)
Typedefs
typedef struct VC_CONTAINER_MODULE_T VC_CONTAINER_MODULE_T
Functions
VC_CONTAINER_STATUS_T wav_reader_open (VC_CONTAINER_T *)
Macro Definition Documentation
BLOCK_SIZE
#define BLOCK_SIZE (16*1024)
Definition at line 44 of file wav_reader.c.
Referenced by wav_reader_open().
CONTAINER_HELPER_LOG_INDENT
#define CONTAINER_HELPER_LOG_INDENT (a) 0
Definition at line 33 of file wav_reader.c.
CONTAINER_IS_LITTLE_ENDIAN
#define CONTAINER_IS_LITTLE_ENDIAN
Definition at line 30 of file wav_reader.c.
WAV_EXTRADATA_MAX
#define WAV_EXTRADATA_MAX 16
Definition at line 43 of file wav_reader.c.
Typedef Documentation
VC_CONTAINER_MODULE_T
typedef struct VC_CONTAINER_MODULE_T VC_CONTAINER_MODULE_T
Function Documentation
wav_reader_open()
VC_CONTAINER_STATUS_T wav_reader_open (VC_CONTAINER_T * p_ctx)
Definition at line 171 of file wav_reader.c.
References VC_CONTAINER_ES_SPECIFIC_FORMAT_T::audio, VC_CONTAINER_MODULE_T::bitrate, VC_CONTAINER_ES_FORMAT_T::bitrate, VC_CONTAINER_AUDIO_FORMAT_T::bits_per_sample, VC_CONTAINER_AUDIO_FORMAT_T::block_align, BLOCK_SIZE, VC_CONTAINER_MODULE_T::block_size, VC_CONTAINER_T::capabilities, VC_CONTAINER_MODULE_T::channels, VC_CONTAINER_AUDIO_FORMAT_T::channels, VC_CONTAINER_MODULE_T::chunk_size, codec, VC_CONTAINER_ES_FORMAT_T::codec, VC_CONTAINER_MODULE_T::data_offset, VC_CONTAINER_MODULE_T::data_size, VC_CONTAINER_T::duration, error(), VC_CONTAINER_ES_FORMAT_T::es_type, VC_CONTAINER_MODULE_T::extradata, VC_CONTAINER_ES_FORMAT_T::extradata, VC_CONTAINER_ES_FORMAT_T::extradata_size, VC_CONTAINER_TRACK_T::format, guid, VC_CONTAINER_TRACK_T::is_enabled, VC_CONTAINER_PRIVATE_T::module, PEEK_BYTES, VC_CONTAINER_PRIVATE_T::pf_close, VC_CONTAINER_T::priv, READ_BYTES, READ_FOURCC, READ_GUID, READ_U16, READ_U32, VC_CONTAINER_AUDIO_FORMAT_T::sample_rate, SKIP_BYTES, SKIP_FOURCC, SKIP_U16, SKIP_U32, VC_CONTAINER_MODULE_T::status, STREAM_POSITION, STREAM_SEEKABLE, STREAM_STATUS, VC_CONTAINER_MODULE_T::track, VC_CONTAINER_T::tracks, VC_CONTAINER_T::tracks_num, VC_CONTAINER_ES_FORMAT_T::type, vc_container_allocate_track(), VC_CONTAINER_CAPS_CAN_SEEK, VC_CONTAINER_CODEC_ATRAC3, VC_CONTAINER_CODEC_ATRACX, VC_CONTAINER_CODEC_PCM_SIGNED_LE, VC_CONTAINER_CODEC_UNKNOWN, VC_CONTAINER_ERROR_FORMAT_FEATURE_NOT_SUPPORTED, VC_CONTAINER_ERROR_FORMAT_INVALID, VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED, VC_CONTAINER_ERROR_OUT_OF_MEMORY, VC_CONTAINER_ES_TYPE_AUDIO, VC_CONTAINER_SUCCESS, VC_FOURCC, WAVE_FORMAT_EXTENSIBLE, and waveformat_to_codec().
 {
    VC_CONTAINER_MODULE_T *module = 0;
    VC_CONTAINER_STATUS_T status = VC_CONTAINER_SUCCESS;
    VC_CONTAINER_FOURCC_T codec;
    int64_t chunk_size, chunk_pos;
    uint32_t format, channels, samplerate, bitrate, block_align, bps, cbsize = 0;
    uint8_t buffer[12];
    /* Check the RIFF chunk descriptor */
    if( PEEK_BYTES(p_ctx, buffer, 12) != 12 )
      return VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED;
    if( VC_FOURCC(buffer[0], buffer[1], buffer[2], buffer[3]) !=
        VC_FOURCC('R','I','F','F') )
      return VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED;
    if( VC_FOURCC(buffer[8], buffer[9], buffer[10], buffer[11]) !=
        VC_FOURCC('W','A','V','E') )
      return VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED;
    /*
     *  We are dealing with a WAV file
     */
    SKIP_FOURCC(p_ctx, "Chunk ID");
    SKIP_U32(p_ctx, "Chunk size");
    SKIP_FOURCC(p_ctx, "WAVE ID");
    /* We're looking for the 'fmt' sub-chunk */
    do {
       chunk_pos = STREAM_POSITION(p_ctx) + 8;
       if( READ_FOURCC(p_ctx, "Chunk ID") == VC_FOURCC('f','m','t',' ') ) break;
       /* Not interested in this chunk. Skip it. */
       chunk_size = READ_U32(p_ctx, "Chunk size");
       SKIP_BYTES(p_ctx, chunk_size);
    } while(STREAM_STATUS(p_ctx) == VC_CONTAINER_SUCCESS);
    if(STREAM_STATUS(p_ctx) != VC_CONTAINER_SUCCESS)
       return VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED; /* 'fmt' not found */
    /* Parse the 'fmt' sub-chunk */
    chunk_size  = READ_U32(p_ctx, "Chunk size");
    format      = READ_U16(p_ctx, "wFormatTag");
    channels    = READ_U16(p_ctx, "nChannels");
    samplerate  = READ_U32(p_ctx, "nSamplesPerSec");
    bitrate     = READ_U32(p_ctx, "nAvgBytesPerSec") * 8;
    block_align = READ_U16(p_ctx, "nBlockAlign");
    bps         = READ_U16(p_ctx, "wBitsPerSample");
    if(STREAM_POSITION(p_ctx) - chunk_pos <= chunk_size - 2)
       cbsize = READ_U16(p_ctx, "cbSize");
    if(format == WAVE_FORMAT_EXTENSIBLE &&
       chunk_size >= 18 + 22 && cbsize >= 22)
    {
       GUID_T guid;
       codec = VC_CONTAINER_CODEC_UNKNOWN;
       SKIP_U16(p_ctx, "wValidBitsPerSample");
       SKIP_U32(p_ctx, "dwChannelMask");
       READ_GUID(p_ctx, &guid, "SubFormat");
       if(!memcmp(&guid, &pcm_guid, sizeof(guid)))
          codec = VC_CONTAINER_CODEC_PCM_SIGNED_LE;
       else if(!memcmp(&guid, &atracx_guid, sizeof(guid)))
          codec = VC_CONTAINER_CODEC_ATRAC3;
       cbsize -= 22;
       /* TODO: deal with channel mapping */
    }
    else
    {
       codec = waveformat_to_codec(format);
    }
    /* Bail out if we don't recognise the codec */
    if(codec == VC_CONTAINER_CODEC_UNKNOWN)
       return VC_CONTAINER_ERROR_FORMAT_FEATURE_NOT_SUPPORTED;
    /* Do some sanity checking on the info we got */
    if(!channels || !samplerate || !block_align || !bitrate)
       return VC_CONTAINER_ERROR_FORMAT_INVALID;
    if(codec == VC_CONTAINER_CODEC_ATRAC3 && channels > 2)
       return VC_CONTAINER_ERROR_FORMAT_INVALID;
    /* Allocate our context */
    module = malloc(sizeof(*module));
    if(!module) { status = VC_CONTAINER_ERROR_OUT_OF_MEMORY; goto error; }
    memset(module, 0, sizeof(*module));
    p_ctx->priv->module = module;
    p_ctx->tracks_num = 1;
    p_ctx->tracks = &module->track;
    p_ctx->tracks[0] = vc_container_allocate_track(p_ctx, 0);
    if(!p_ctx->tracks[0]) return VC_CONTAINER_ERROR_OUT_OF_MEMORY;
    p_ctx->tracks[0]->format->es_type = VC_CONTAINER_ES_TYPE_AUDIO;
    p_ctx->tracks[0]->format->codec = codec;
    p_ctx->tracks[0]->format->type->audio.channels = channels;
    p_ctx->tracks[0]->format->type->audio.sample_rate = samplerate;
    p_ctx->tracks[0]->format->type->audio.block_align = block_align;
    p_ctx->tracks[0]->format->type->audio.bits_per_sample = bps;
    p_ctx->tracks[0]->format->bitrate = bitrate;
    p_ctx->tracks[0]->is_enabled = true;
    p_ctx->tracks[0]->format->extradata_size = 0;
    p_ctx->tracks[0]->format->extradata = module->extradata;
    module->block_size = block_align;
    /* Prepare the codec extradata */
    if(codec == VC_CONTAINER_CODEC_ATRAC3)
    {
       uint16_t h, mode;
       SKIP_U16(p_ctx, "len");
       SKIP_U16(p_ctx, "layer");
       SKIP_U32(p_ctx, "bytes_per_frame");
       mode = READ_U16(p_ctx, "mode");
       SKIP_U16(p_ctx, "mode_ext");
       SKIP_U16(p_ctx, "num_subframes");
       SKIP_U16(p_ctx, "flags");
       h = (1 << 15);
       if(channels == 2)
       {
          h |= (1 << 13);
          if(mode == 1) h |= (1 << 14);
       }
       h |= block_align & 0x7ff;
       p_ctx->tracks[0]->format->extradata[0] = h >> 8;
       p_ctx->tracks[0]->format->extradata[1] = h & 255;
       p_ctx->tracks[0]->format->extradata_size = 2;
    }
    else if(codec == VC_CONTAINER_CODEC_ATRACX && cbsize >= 6)
    {
       SKIP_BYTES(p_ctx, 2);
       p_ctx->tracks[0]->format->extradata_size =
          READ_BYTES(p_ctx, p_ctx->tracks[0]->format->extradata, 6);
    }
    else if(codec == VC_CONTAINER_CODEC_PCM_SIGNED_LE)
    {
       /* Audioplus can no longer be given anything other than a multiple-of-16 number of samples */
       block_align *= 16;
       module->block_size = (BLOCK_SIZE / block_align) * block_align;
    }
    /* Skip the rest of the 'fmt' sub-chunk */
    SKIP_BYTES(p_ctx, chunk_pos + chunk_size - STREAM_POSITION(p_ctx));
    /* We also need the 'data' sub-chunk */
    do {
       chunk_pos = STREAM_POSITION(p_ctx) + 8;
       if( READ_FOURCC(p_ctx, "Chunk ID") == VC_FOURCC('d','a','t','a') ) break;
       /* Not interested in this chunk. Skip it. */
       chunk_size = READ_U32(p_ctx, "Chunk size");
       SKIP_BYTES(p_ctx, chunk_size);
    } while(STREAM_STATUS(p_ctx) == VC_CONTAINER_SUCCESS);
    if(STREAM_STATUS(p_ctx) != VC_CONTAINER_SUCCESS)
    {
       status = VC_CONTAINER_ERROR_FORMAT_INVALID; /* 'data' not found */;
       goto error;
    }
    module->data_offset = chunk_pos;
    module->data_size = READ_U32(p_ctx, "Chunk size");
    p_ctx->duration = module->data_size * 8000000 / bitrate;
    if(STREAM_SEEKABLE(p_ctx))
       p_ctx->capabilities |= VC_CONTAINER_CAPS_CAN_SEEK;
    /*
     *  We now have all the information we really need to start playing the stream
     */
    p_ctx->priv->pf_close = wav_reader_close;
    p_ctx->priv->pf_read = wav_reader_read;
    p_ctx->priv->pf_seek = wav_reader_seek;
    /* Seek back to the start of the data */
    status = SEEK(p_ctx, module->data_offset);
    if(status != VC_CONTAINER_SUCCESS) goto error;
    return VC_CONTAINER_SUCCESS;
  error:
    LOG_DEBUG(p_ctx, "wav: error opening stream (%i)", status);
    if(module) wav_reader_close(p_ctx);
    return status;
 }