VideoCore Library: interface/mmal/vc/mmal_vc_api_drm.c File Reference
mmal_vc_api_drm.c File Reference
#include "mmal_vc_api_drm.h"
#include "mmal_vc_api.h"
#include "interface/mmal/mmal_logging.h"
#include "interface/mmal/mmal.h"
#include "mmal_vc_msgs.h"
#include "mmal_vc_client_priv.h"
#include "mmal_vc_opaque_alloc.h"
#include "mmal_vc_shm.h"
#include "interface/mmal/util/mmal_util.h"
#include "interface/mmal/core/mmal_component_private.h"
#include "interface/mmal/core/mmal_port_private.h"
#include "interface/mmal/core/mmal_buffer_private.h"
#include "interface/vcos/vcos.h"
Functions
int mmal_vc_drm_get_time (unsigned int *time)
int mmal_vc_drm_get_lhs32 (unsigned char *into)
Function Documentation
mmal_vc_drm_get_lhs32()
int mmal_vc_drm_get_lhs32 (unsigned char * into)
Definition at line 61 of file mmal_vc_api_drm.c.
References len, MMAL_FALSE, MMAL_SUCCESS, mmal_vc_deinit(), mmal_vc_get_client(), mmal_vc_init(), mmal_vc_sendwait_message(), MMAL_WORKER_DRM_GET_LHS32, mmal_worker_drm_get_lhs32_reply::secret, and status.
 {
    MMAL_STATUS_T status;
    mmal_worker_msg_header req;
    mmal_worker_drm_get_lhs32_reply reply;
    size_t len = sizeof(reply);
    status = mmal_vc_init();
    if (status != MMAL_SUCCESS) return status;
    status = mmal_vc_sendwait_message(mmal_vc_get_client(),
                                      &req, sizeof(req),
                                      MMAL_WORKER_DRM_GET_LHS32,
                                      &reply, &len, MMAL_FALSE);
    memcpy(into, reply.secret, 32);
    mmal_vc_deinit();
    return status;
 }
mmal_vc_drm_get_time()
int mmal_vc_drm_get_time (unsigned int * time)
Definition at line 43 of file mmal_vc_api_drm.c.
References len, MMAL_FALSE, MMAL_SUCCESS, mmal_vc_deinit(), mmal_vc_get_client(), mmal_vc_init(), mmal_vc_sendwait_message(), MMAL_WORKER_DRM_GET_TIME, status, and mmal_worker_drm_get_time_reply::time.
 {
    MMAL_STATUS_T status;
    mmal_worker_msg_header req;
    mmal_worker_drm_get_time_reply reply;
    size_t len = sizeof(reply);
    status = mmal_vc_init();
    if (status != MMAL_SUCCESS) return status;
    status = mmal_vc_sendwait_message(mmal_vc_get_client(),
                                      &req, sizeof(req),
                                      MMAL_WORKER_DRM_GET_TIME,
                                      &reply, &len, MMAL_FALSE);
    *time = reply.time;
    mmal_vc_deinit();
    return status;
 }