VideoCore Library: MMAL to OMX IL conversion utilities
MMAL to OMX IL conversion utilities
Utility functions
Classes
union OMX_FORMAT_PARAM_TYPE
Typedefs
typedef union OMX_FORMAT_PARAM_TYPE OMX_FORMAT_PARAM_TYPE
Functions
OMX_ERRORTYPE mmalil_error_to_omx (MMAL_STATUS_T status)
MMAL_STATUS_T mmalil_error_to_mmal (OMX_ERRORTYPE error)
uint32_t mmalil_buffer_flags_to_mmal (OMX_U32 flags)
OMX_U32 mmalil_buffer_flags_to_omx (uint32_t flags)
uint32_t mmalil_video_buffer_flags_to_mmal (OMX_U32 flags)
OMX_U32 mmalil_video_buffer_flags_to_omx (uint32_t flags)
void mmalil_buffer_header_to_omx (OMX_BUFFERHEADERTYPE *omx, MMAL_BUFFER_HEADER_T *mmal)
void mmalil_buffer_header_to_mmal (MMAL_BUFFER_HEADER_T *mmal, OMX_BUFFERHEADERTYPE *omx)
OMX_PORTDOMAINTYPE mmalil_es_type_to_omx_domain (MMAL_ES_TYPE_T type)
MMAL_ES_TYPE_T mmalil_omx_domain_to_es_type (OMX_PORTDOMAINTYPE domain)
uint32_t mmalil_omx_audio_coding_to_encoding (OMX_AUDIO_CODINGTYPE coding)
OMX_AUDIO_CODINGTYPE mmalil_encoding_to_omx_audio_coding (uint32_t encoding)
uint32_t mmalil_omx_video_coding_to_encoding (OMX_VIDEO_CODINGTYPE coding)
OMX_VIDEO_CODINGTYPE mmalil_encoding_to_omx_video_coding (uint32_t encoding)
uint32_t mmalil_omx_image_coding_to_encoding (OMX_IMAGE_CODINGTYPE coding)
OMX_IMAGE_CODINGTYPE mmalil_encoding_to_omx_image_coding (uint32_t encoding)
uint32_t mmalil_omx_coding_to_encoding (uint32_t encoding, OMX_PORTDOMAINTYPE domain)
uint32_t mmalil_omx_color_format_to_encoding (OMX_COLOR_FORMATTYPE coding)
OMX_COLOR_FORMATTYPE mmalil_encoding_to_omx_color_format (uint32_t encoding)
uint32_t mmalil_omx_bayer_format_order_to_encoding (OMX_BAYERORDERTYPE bayer_order, OMX_COLOR_FORMATTYPE color_format)
OMX_BAYERORDERTYPE mmalil_encoding_to_omx_bayer_order (uint32_t encoding)
uint32_t mmalil_omx_color_space_to_mmal (OMX_COLORSPACETYPE coding)
OMX_COLORSPACETYPE mmalil_color_space_to_omx (uint32_t coding)
uint32_t mmalil_omx_video_profile_to_mmal (OMX_U32 level, OMX_VIDEO_CODINGTYPE coding)
OMX_U32 mmalil_video_profile_to_omx (uint32_t profile)
uint32_t mmalil_omx_video_level_to_mmal (OMX_U32 level, OMX_VIDEO_CODINGTYPE coding)
OMX_U32 mmalil_video_level_to_omx (uint32_t level)
MMAL_VIDEO_RATECONTROL_T mmalil_omx_video_ratecontrol_to_mmal (OMX_VIDEO_CONTROLRATETYPE omx)
OMX_VIDEO_CONTROLRATETYPE mmalil_video_ratecontrol_to_omx (MMAL_VIDEO_RATECONTROL_T mmal)
MMAL_VIDEO_INTRA_REFRESH_T mmalil_omx_video_intrarefresh_to_mmal (OMX_VIDEO_INTRAREFRESHTYPE omx)
OMX_INDEXTYPE mmalil_omx_audio_param_index (OMX_AUDIO_CODINGTYPE coding, OMX_U32 *size)
OMX_AUDIO_CODINGTYPE mmalil_omx_audio_param_index_to_coding (OMX_INDEXTYPE index)
MMAL_STATUS_T mmalil_omx_default_channel_mapping (OMX_AUDIO_CHANNELTYPE *channel_mapping, unsigned int nchannels)
MMAL_FOURCC_T mmalil_omx_audio_param_to_format (MMAL_ES_FORMAT_T *format, OMX_AUDIO_CODINGTYPE coding, OMX_FORMAT_PARAM_TYPE *param)
OMX_AUDIO_CODINGTYPE mmalil_format_to_omx_audio_param (OMX_FORMAT_PARAM_TYPE *param, OMX_INDEXTYPE *param_index, MMAL_ES_FORMAT_T *format)
Detailed Description
Typedef Documentation
OMX_FORMAT_PARAM_TYPE
typedef union OMX_FORMAT_PARAM_TYPE OMX_FORMAT_PARAM_TYPE
Union of all the OMX_VIDEO/AUDIO_PARAM types
Function Documentation
mmalil_buffer_flags_to_mmal()
uint32_t mmalil_buffer_flags_to_mmal (OMX_U32 flags)
Convert MMAL buffer header flags into OMX buffer header flags.
Parameters
flags OMX buffer header flags.
Returns
MMAL buffer header flags.
Definition at line 104 of file mmal_il.c.
References MMAL_BUFFER_HEADER_FLAG_CODECSIDEINFO, MMAL_BUFFER_HEADER_FLAG_CONFIG, MMAL_BUFFER_HEADER_FLAG_CORRUPTED, MMAL_BUFFER_HEADER_FLAG_DECODEONLY, MMAL_BUFFER_HEADER_FLAG_DISCONTINUITY, MMAL_BUFFER_HEADER_FLAG_EOS, MMAL_BUFFER_HEADER_FLAG_FRAME_END, MMAL_BUFFER_HEADER_FLAG_KEYFRAME, MMAL_BUFFER_HEADER_FLAG_NAL_END, MMAL_BUFFER_HEADER_FLAG_USER0, MMAL_BUFFER_HEADER_FLAG_USER1, MMAL_BUFFER_HEADER_FLAG_USER2, MMAL_BUFFER_HEADER_FLAG_USER3, MMAL_BUFFER_HEADER_FLAGS_SNAPSHOT, MMAL_BUFFER_HEADER_VIDEO_FLAG_INTERLACED, MMAL_BUFFER_HEADER_VIDEO_FLAG_TOP_FIELD_FIRST, OMX_BUFFERFLAG_CAPTURE_PREVIEW, OMX_BUFFERFLAG_CODECCONFIG, OMX_BUFFERFLAG_CODECSIDEINFO, OMX_BUFFERFLAG_DATACORRUPT, OMX_BUFFERFLAG_DECODEONLY, OMX_BUFFERFLAG_DISCONTINUITY, OMX_BUFFERFLAG_ENDOFFRAME, OMX_BUFFERFLAG_ENDOFNAL, OMX_BUFFERFLAG_EOS, OMX_BUFFERFLAG_INTERLACED, OMX_BUFFERFLAG_SYNCFRAME, OMX_BUFFERFLAG_TOP_FIELD_FIRST, OMX_BUFFERFLAG_USR0, OMX_BUFFERFLAG_USR1, OMX_BUFFERFLAG_USR2, and OMX_BUFFERFLAG_USR3.
Referenced by mmalil_buffer_header_to_mmal().
 {
    uint32_t mmal_flags = 0;
    if (flags & OMX_BUFFERFLAG_SYNCFRAME)
       mmal_flags |= MMAL_BUFFER_HEADER_FLAG_KEYFRAME;
    if (flags & OMX_BUFFERFLAG_ENDOFFRAME)
       mmal_flags |= MMAL_BUFFER_HEADER_FLAG_FRAME_END;
    if (flags & OMX_BUFFERFLAG_EOS)
       mmal_flags |= MMAL_BUFFER_HEADER_FLAG_EOS;
    if (flags & OMX_BUFFERFLAG_CODECCONFIG)
       mmal_flags |= MMAL_BUFFER_HEADER_FLAG_CONFIG;
    if (flags & OMX_BUFFERFLAG_DISCONTINUITY)
       mmal_flags |= MMAL_BUFFER_HEADER_FLAG_DISCONTINUITY;
    if (flags & OMX_BUFFERFLAG_CODECSIDEINFO)
       mmal_flags |= MMAL_BUFFER_HEADER_FLAG_CODECSIDEINFO;
    if (flags & OMX_BUFFERFLAG_CAPTURE_PREVIEW)
       mmal_flags |= MMAL_BUFFER_HEADER_FLAGS_SNAPSHOT;
    if (flags & OMX_BUFFERFLAG_DATACORRUPT)
       mmal_flags |= MMAL_BUFFER_HEADER_FLAG_CORRUPTED;
    if (flags & OMX_BUFFERFLAG_DECODEONLY)
       mmal_flags |= MMAL_BUFFER_HEADER_FLAG_DECODEONLY;
    if (flags & OMX_BUFFERFLAG_INTERLACED)
       mmal_flags |= MMAL_BUFFER_HEADER_VIDEO_FLAG_INTERLACED;
    if (flags & OMX_BUFFERFLAG_TOP_FIELD_FIRST)
       mmal_flags |= MMAL_BUFFER_HEADER_VIDEO_FLAG_TOP_FIELD_FIRST;
    if (flags & OMX_BUFFERFLAG_ENDOFNAL)
       mmal_flags |= MMAL_BUFFER_HEADER_FLAG_NAL_END;
    if (flags & OMX_BUFFERFLAG_USR0)
       mmal_flags |= MMAL_BUFFER_HEADER_FLAG_USER0;
    if (flags & OMX_BUFFERFLAG_USR1)
       mmal_flags |= MMAL_BUFFER_HEADER_FLAG_USER1;
    if (flags & OMX_BUFFERFLAG_USR2)
       mmal_flags |= MMAL_BUFFER_HEADER_FLAG_USER2;
    if (flags & OMX_BUFFERFLAG_USR3)
       mmal_flags |= MMAL_BUFFER_HEADER_FLAG_USER3;
    return mmal_flags;
 }
mmalil_buffer_flags_to_omx()
OMX_U32 mmalil_buffer_flags_to_omx (uint32_t flags)
Convert OMX buffer header flags into MMAL buffer header flags.
Parameters
flags MMAL buffer header flags.
Returns
OMX buffer header flags.
Definition at line 63 of file mmal_il.c.
References MMAL_BUFFER_HEADER_FLAG_CODECSIDEINFO, MMAL_BUFFER_HEADER_FLAG_CONFIG, MMAL_BUFFER_HEADER_FLAG_CORRUPTED, MMAL_BUFFER_HEADER_FLAG_DECODEONLY, MMAL_BUFFER_HEADER_FLAG_DISCONTINUITY, MMAL_BUFFER_HEADER_FLAG_EOS, MMAL_BUFFER_HEADER_FLAG_FRAME_END, MMAL_BUFFER_HEADER_FLAG_KEYFRAME, MMAL_BUFFER_HEADER_FLAG_NAL_END, MMAL_BUFFER_HEADER_FLAG_USER0, MMAL_BUFFER_HEADER_FLAG_USER1, MMAL_BUFFER_HEADER_FLAG_USER2, MMAL_BUFFER_HEADER_FLAG_USER3, MMAL_BUFFER_HEADER_FLAGS_SNAPSHOT, MMAL_BUFFER_HEADER_VIDEO_FLAG_INTERLACED, MMAL_BUFFER_HEADER_VIDEO_FLAG_TOP_FIELD_FIRST, OMX_BUFFERFLAG_CAPTURE_PREVIEW, OMX_BUFFERFLAG_CODECCONFIG, OMX_BUFFERFLAG_CODECSIDEINFO, OMX_BUFFERFLAG_DATACORRUPT, OMX_BUFFERFLAG_DECODEONLY, OMX_BUFFERFLAG_DISCONTINUITY, OMX_BUFFERFLAG_ENDOFFRAME, OMX_BUFFERFLAG_ENDOFNAL, OMX_BUFFERFLAG_EOS, OMX_BUFFERFLAG_INTERLACED, OMX_BUFFERFLAG_SYNCFRAME, OMX_BUFFERFLAG_TOP_FIELD_FIRST, OMX_BUFFERFLAG_USR0, OMX_BUFFERFLAG_USR1, OMX_BUFFERFLAG_USR2, and OMX_BUFFERFLAG_USR3.
Referenced by mmalil_buffer_header_to_omx().
 {
    OMX_U32 omx_flags = 0;
    if(flags & MMAL_BUFFER_HEADER_FLAG_KEYFRAME)
       omx_flags |= OMX_BUFFERFLAG_SYNCFRAME;
    if(flags & MMAL_BUFFER_HEADER_FLAG_FRAME_END)
       omx_flags |= OMX_BUFFERFLAG_ENDOFFRAME;
    if(flags & MMAL_BUFFER_HEADER_FLAG_EOS)
       omx_flags |= OMX_BUFFERFLAG_EOS;
    if(flags & MMAL_BUFFER_HEADER_FLAG_CONFIG)
       omx_flags |= OMX_BUFFERFLAG_CODECCONFIG;
    if(flags & MMAL_BUFFER_HEADER_FLAG_DISCONTINUITY)
       omx_flags |= OMX_BUFFERFLAG_DISCONTINUITY;
    if (flags & MMAL_BUFFER_HEADER_FLAG_CODECSIDEINFO)
       omx_flags |= OMX_BUFFERFLAG_CODECSIDEINFO;
    if (flags & MMAL_BUFFER_HEADER_FLAGS_SNAPSHOT)
       omx_flags |= OMX_BUFFERFLAG_CAPTURE_PREVIEW;
    if (flags & MMAL_BUFFER_HEADER_FLAG_CORRUPTED)
       omx_flags |= OMX_BUFFERFLAG_DATACORRUPT;
    if (flags & MMAL_BUFFER_HEADER_FLAG_DECODEONLY)
       omx_flags |= OMX_BUFFERFLAG_DECODEONLY;
    if (flags & MMAL_BUFFER_HEADER_VIDEO_FLAG_INTERLACED)
       omx_flags |= OMX_BUFFERFLAG_INTERLACED;
    if (flags & MMAL_BUFFER_HEADER_VIDEO_FLAG_TOP_FIELD_FIRST)
      omx_flags |= OMX_BUFFERFLAG_TOP_FIELD_FIRST;
    if (flags & MMAL_BUFFER_HEADER_FLAG_NAL_END)
      omx_flags |= OMX_BUFFERFLAG_ENDOFNAL;
    if (flags & MMAL_BUFFER_HEADER_FLAG_USER0)
       omx_flags |= OMX_BUFFERFLAG_USR0;
    if (flags & MMAL_BUFFER_HEADER_FLAG_USER1)
       omx_flags |= OMX_BUFFERFLAG_USR1;
    if (flags & MMAL_BUFFER_HEADER_FLAG_USER2)
       omx_flags |= OMX_BUFFERFLAG_USR2;
    if (flags & MMAL_BUFFER_HEADER_FLAG_USER3)
       omx_flags |= OMX_BUFFERFLAG_USR3;
    return omx_flags;
 }
mmalil_buffer_header_to_mmal()
void mmalil_buffer_header_to_mmal (MMAL_BUFFER_HEADER_T * mmal, OMX_BUFFERHEADERTYPE * omx)
Convert an OMX buffer header into a MMAL buffer header.
Parameters
mmal Pointer to the destination MMAL buffer header.
omx Pointer to the source OMX buffer header.
Definition at line 193 of file mmal_il.c.
References MMAL_BUFFER_HEADER_T::alloc_size, MMAL_BUFFER_HEADER_T::cmd, MMAL_BUFFER_HEADER_T::data, MMAL_BUFFER_HEADER_T::dts, MMAL_BUFFER_HEADER_T::flags, MMAL_BUFFER_HEADER_T::length, MMAL_TIME_UNKNOWN, mmalil_buffer_flags_to_mmal(), OMX_BUFFERHEADERTYPE::nAllocLen, OMX_BUFFERHEADERTYPE::nFilledLen, OMX_BUFFERHEADERTYPE::nFlags, OMX_BUFFERHEADERTYPE::nOffset, OMX_BUFFERHEADERTYPE::nTimeStamp, MMAL_BUFFER_HEADER_T::offset, OMX_BUFFERFLAG_TIME_IS_DTS, OMX_BUFFERFLAG_TIME_UNKNOWN, omx_ticks_to_s64, OMX_BUFFERHEADERTYPE::pBuffer, and MMAL_BUFFER_HEADER_T::pts.
Referenced by mmalomx_buffer_send().
 {
    mmal->cmd = 0;
    mmal->data = omx->pBuffer;
    mmal->alloc_size = omx->nAllocLen;
    mmal->length = omx->nFilledLen;
    mmal->offset = omx->nOffset;
    if (omx->nFlags & OMX_BUFFERFLAG_TIME_IS_DTS)
    {
      mmal->dts = omx_ticks_to_s64(omx->nTimeStamp);
      mmal->pts = MMAL_TIME_UNKNOWN;
    }
    else if (omx->nFlags & OMX_BUFFERFLAG_TIME_UNKNOWN)
    {
      mmal->dts = MMAL_TIME_UNKNOWN;
      mmal->pts = MMAL_TIME_UNKNOWN;
    }
    else
    {
      mmal->dts = MMAL_TIME_UNKNOWN;
      mmal->pts = omx_ticks_to_s64(omx->nTimeStamp);
    }
    mmal->flags = mmalil_buffer_flags_to_mmal(omx->nFlags);
 }
mmalil_buffer_header_to_omx()
void mmalil_buffer_header_to_omx (OMX_BUFFERHEADERTYPE * omx, MMAL_BUFFER_HEADER_T * mmal)
Convert a MMAL buffer header into an OMX buffer header. Note that only the fields which have a direct mapping between OMX and MMAL are converted.
Parameters
omx Pointer to the destination OMX buffer header.
mmal Pointer to the source MMAL buffer header.
Definition at line 170 of file mmal_il.c.
References MMAL_BUFFER_HEADER_T::alloc_size, MMAL_BUFFER_HEADER_T::data, MMAL_BUFFER_HEADER_T::dts, MMAL_BUFFER_HEADER_T::flags, MMAL_BUFFER_HEADER_T::length, MMAL_TIME_UNKNOWN, mmalil_buffer_flags_to_omx(), OMX_BUFFERHEADERTYPE::nAllocLen, OMX_BUFFERHEADERTYPE::nFilledLen, OMX_BUFFERHEADERTYPE::nFlags, OMX_BUFFERHEADERTYPE::nOffset, OMX_BUFFERHEADERTYPE::nTimeStamp, MMAL_BUFFER_HEADER_T::offset, OMX_BUFFERFLAG_TIME_IS_DTS, OMX_BUFFERFLAG_TIME_UNKNOWN, omx_ticks_from_s64, OMX_BUFFERHEADERTYPE::pBuffer, and MMAL_BUFFER_HEADER_T::pts.
 {
    omx->pBuffer = mmal->data;
    omx->nAllocLen = mmal->alloc_size;
    omx->nFilledLen = mmal->length;
    omx->nOffset = mmal->offset;
    omx->nFlags = mmalil_buffer_flags_to_omx(mmal->flags);
    omx->nTimeStamp = omx_ticks_from_s64(mmal->pts);
    if (mmal->pts == MMAL_TIME_UNKNOWN)
    {
       if (mmal->dts == MMAL_TIME_UNKNOWN)
       {
          omx->nTimeStamp = omx_ticks_from_s64(0);
          omx->nFlags |= OMX_BUFFERFLAG_TIME_UNKNOWN;
       }
       else
       {
         omx->nTimeStamp = omx_ticks_from_s64(mmal->dts);
         omx->nFlags |= OMX_BUFFERFLAG_TIME_IS_DTS;
       }
    }
 }
mmalil_color_space_to_omx()
OMX_COLORSPACETYPE mmalil_color_space_to_omx (uint32_t coding)
Definition at line 882 of file mmal_il.c.
 {
    unsigned int i;
    for(i = 0; mmal_omx_colorspace_coding_table[i].mmal != MMAL_COLOR_SPACE_UNKNOWN; i++)
       if(mmal_omx_colorspace_coding_table[i].mmal == coding) break;
    return mmal_omx_colorspace_coding_table[i].omx;
 }
mmalil_encoding_to_omx_audio_coding()
OMX_AUDIO_CODINGTYPE mmalil_encoding_to_omx_audio_coding (uint32_t encoding)
Definition at line 280 of file mmal_il.c.
Referenced by mmalil_format_to_omx_audio_param().
 {
    unsigned int i;
    for(i = 0; mmal_omx_audio_coding_table[i].encoding != MMAL_ENCODING_UNKNOWN; i++)
       if(mmal_omx_audio_coding_table[i].encoding == encoding) break;
    return mmal_omx_audio_coding_table[i].coding;
 }
mmalil_encoding_to_omx_bayer_order()
OMX_BAYERORDERTYPE mmalil_encoding_to_omx_bayer_order (uint32_t encoding)
Definition at line 848 of file mmal_il.c.
 {
    unsigned int i;
    for(i = 0; mmal_omx_bayer_order_coding_table[i].encoding != MMAL_ENCODING_UNKNOWN; i++)
       if(mmal_omx_bayer_order_coding_table[i].encoding == encoding) break;
    return mmal_omx_bayer_order_coding_table[i].bayer_order;
 }
mmalil_encoding_to_omx_color_format()
OMX_COLOR_FORMATTYPE mmalil_encoding_to_omx_color_format (uint32_t encoding)
Definition at line 794 of file mmal_il.c.
 {
    unsigned int i;
    for(i = 0; mmal_omx_colorformat_coding_table[i].encoding != MMAL_ENCODING_UNKNOWN; i++)
       if(mmal_omx_colorformat_coding_table[i].encoding == encoding) break;
    return mmal_omx_colorformat_coding_table[i].coding;
 }
mmalil_encoding_to_omx_image_coding()
OMX_IMAGE_CODINGTYPE mmalil_encoding_to_omx_image_coding (uint32_t encoding)
Definition at line 702 of file mmal_il.c.
 {
    unsigned int i;
    for(i = 0; mmal_omx_image_coding_table[i].encoding != MMAL_ENCODING_UNKNOWN; i++)
       if(mmal_omx_image_coding_table[i].encoding == encoding) break;
    return mmal_omx_image_coding_table[i].coding;
 }
mmalil_encoding_to_omx_video_coding()
OMX_VIDEO_CODINGTYPE mmalil_encoding_to_omx_video_coding (uint32_t encoding)
Definition at line 671 of file mmal_il.c.
 {
    unsigned int i;
    for(i = 0; mmal_omx_video_coding_table[i].encoding != MMAL_ENCODING_UNKNOWN; i++)
       if(mmal_omx_video_coding_table[i].encoding == encoding) break;
    return mmal_omx_video_coding_table[i].coding;
 }
mmalil_error_to_mmal()
MMAL_STATUS_T mmalil_error_to_mmal (OMX_ERRORTYPE error)
Convert OMX error codes into MMAL status codes.
Parameters
error OMX error code.
Returns
MMAL status code.
Definition at line 54 of file mmal_il.c.
 {
    unsigned int i;
    for(i = 0; mmal_omx_error[i].mmal != (MMAL_STATUS_T)-1; i++)
       if(mmal_omx_error[i].omx == error) break;
    return mmal_omx_error[i].mmal;
 }
mmalil_error_to_omx()
OMX_ERRORTYPE mmalil_error_to_omx (MMAL_STATUS_T status)
Convert MMAL status codes into OMX error codes.
Parameters
status MMAL status code.
Returns
OMX error code.
Definition at line 46 of file mmal_il.c.
Referenced by mmalomx_buffer_send(), and OMX_GetHandle().
 {
    unsigned int i;
    for(i = 0; mmal_omx_error[i].mmal != (MMAL_STATUS_T)-1; i++)
       if(mmal_omx_error[i].mmal == status) break;
    return mmal_omx_error[i].omx;
 }
mmalil_es_type_to_omx_domain()
OMX_PORTDOMAINTYPE mmalil_es_type_to_omx_domain (MMAL_ES_TYPE_T type)
Definition at line 230 of file mmal_il.c.
 {
    unsigned int i;
    for(i = 0; mmal_omx_es_type_table[i].type != MMAL_ES_TYPE_UNKNOWN; i++)
       if(mmal_omx_es_type_table[i].type == type) break;
    return mmal_omx_es_type_table[i].domain;
 }
mmalil_format_to_omx_audio_param()
OMX_AUDIO_CODINGTYPE mmalil_format_to_omx_audio_param (OMX_FORMAT_PARAM_TYPE * param, OMX_INDEXTYPE * param_index, MMAL_ES_FORMAT_T * format)
Convert a MMAL elementary stream format into a OMX_IndexParamAudio structure.
Parameters
param OMX_IndexParamAudio structure to update.
param_index returns the OMX_IndexParamAudio index corresponding to the format.
format Source format structure.
Returns
The OMX aduio coding type if a match was found or OMX_AUDIO_CodingUnused otherwise.
Definition at line 503 of file mmal_il.c.
References OMX_FORMAT_PARAM_TYPE::aac, OMX_FORMAT_PARAM_TYPE::amr, MMAL_ES_SPECIFIC_FORMAT_T::audio, OMX_AUDIO_PARAM_PCMMODETYPE::bInterleaved, MMAL_ES_FORMAT_T::bitrate, MMAL_AUDIO_FORMAT_T::bits_per_sample, MMAL_AUDIO_FORMAT_T::block_align, MMAL_AUDIO_FORMAT_T::channels, coding, OMX_FORMAT_PARAM_TYPE::common, OMX_AUDIO_PARAM_AACPROFILETYPE::eAACStreamFormat, OMX_AUDIO_PARAM_AMRTYPE::eAMRBandMode, OMX_AUDIO_PARAM_PCMMODETYPE::eChannelMapping, OMX_AUDIO_PARAM_PCMMODETYPE::eEndian, OMX_AUDIO_PARAM_WMATYPE::eFormat, MMAL_ES_FORMAT_T::encoding, encoding, MMAL_ES_FORMAT_T::encoding_variant, OMX_AUDIO_PARAM_PCMMODETYPE::eNumData, OMX_AUDIO_PARAM_PCMMODETYPE::ePCMMode, MMAL_ES_FORMAT_T::es, index, MMAL_ENCODING_ALAW, MMAL_ENCODING_AMRNB, MMAL_ENCODING_AMRWB, MMAL_ENCODING_EAC3, MMAL_ENCODING_MULAW, MMAL_ENCODING_PCM_SIGNED_BE, MMAL_ENCODING_PCM_SIGNED_LE, MMAL_ENCODING_PCM_UNSIGNED_BE, MMAL_ENCODING_PCM_UNSIGNED_LE, MMAL_ENCODING_VARIANT_MP4A_ADTS, MMAL_ENCODING_VARIANT_MP4A_DEFAULT, MMAL_ENCODING_WMA1, MMAL_ENCODING_WMA2, mmalil_encoding_to_omx_audio_coding(), mmalil_omx_audio_param_index(), mmalil_omx_default_channel_mapping(), OMX_FORMAT_PARAM_TYPE::mp3, OMX_AUDIO_PARAM_PCMMODETYPE::nBitPerSample, OMX_AUDIO_PARAM_MP3TYPE::nBitRate, OMX_AUDIO_PARAM_AACPROFILETYPE::nBitRate, OMX_AUDIO_PARAM_VORBISTYPE::nBitRate, OMX_AUDIO_PARAM_WMATYPE::nBitRate, OMX_AUDIO_PARAM_AMRTYPE::nBitRate, OMX_AUDIO_PARAM_WMATYPE::nBlockAlign, OMX_AUDIO_PARAM_PCMMODETYPE::nChannels, OMX_AUDIO_PARAM_MP3TYPE::nChannels, OMX_AUDIO_PARAM_AACPROFILETYPE::nChannels, OMX_AUDIO_PARAM_VORBISTYPE::nChannels, OMX_AUDIO_PARAM_WMATYPE::nChannels, OMX_AUDIO_PARAM_AMRTYPE::nChannels, OMX_AUDIO_PARAM_MP3TYPE::nSampleRate, OMX_AUDIO_PARAM_AACPROFILETYPE::nSampleRate, OMX_AUDIO_PARAM_VORBISTYPE::nSampleRate, OMX_AUDIO_PARAM_PCMMODETYPE::nSamplingRate, OMX_AUDIO_PARAM_WMATYPE::nSamplingRate, OMX_PARAM_U32TYPE::nSize, OMX_AUDIO_AACStreamFormatMP4ADTS, OMX_AUDIO_AACStreamFormatRAW, OMX_AUDIO_AMRBandModeNB0, OMX_AUDIO_AMRBandModeWB0, OMX_AUDIO_CodingAAC, OMX_AUDIO_CodingADPCM, OMX_AUDIO_CodingAMR, OMX_AUDIO_CodingDDP, OMX_AUDIO_CodingDTS, OMX_AUDIO_CodingEVRC, OMX_AUDIO_CodingG711, OMX_AUDIO_CodingG723, OMX_AUDIO_CodingG726, OMX_AUDIO_CodingG729, OMX_AUDIO_CodingGSMEFR, OMX_AUDIO_CodingGSMFR, OMX_AUDIO_CodingGSMHR, OMX_AUDIO_CodingMIDI, OMX_AUDIO_CodingMP3, OMX_AUDIO_CodingPCM, OMX_AUDIO_CodingPDCEFR, OMX_AUDIO_CodingPDCFR, OMX_AUDIO_CodingPDCHR, OMX_AUDIO_CodingQCELP13, OMX_AUDIO_CodingQCELP8, OMX_AUDIO_CodingRA, OMX_AUDIO_CodingSBC, OMX_AUDIO_CodingSMV, OMX_AUDIO_CodingTDMAEFR, OMX_AUDIO_CodingTDMAFR, OMX_AUDIO_CodingVORBIS, OMX_AUDIO_CodingWMA, OMX_AUDIO_DDPBitStreamIdAC3, OMX_AUDIO_DDPBitStreamIdEAC3, OMX_AUDIO_PCMModeALaw, OMX_AUDIO_PCMModeLinear, OMX_AUDIO_PCMModeMULaw, OMX_AUDIO_WMAFormat7, OMX_AUDIO_WMAFormat8, OMX_EndianBig, OMX_EndianLittle, OMX_NumericalDataSigned, OMX_NumericalDataUnsigned, OMX_TRUE, OMX_FORMAT_PARAM_TYPE::pcm, MMAL_AUDIO_FORMAT_T::sample_rate, size, vcos_assert, OMX_FORMAT_PARAM_TYPE::vorbis, and OMX_FORMAT_PARAM_TYPE::wma.
 {
    MMAL_AUDIO_FORMAT_T *audio = &format->es->audio;
    OMX_AUDIO_CODINGTYPE coding = mmalil_encoding_to_omx_audio_coding(format->encoding);
    OMX_U32 size = 0;
    OMX_INDEXTYPE index = mmalil_omx_audio_param_index(coding, &size);
    if(param_index) *param_index = index;
    memset(param, 0, size);
    param->common.nSize = size;
    switch(coding)
    {
    case OMX_AUDIO_CodingPCM:
       param->pcm.nChannels = audio->channels;
       param->pcm.nSamplingRate = audio->sample_rate;
       param->pcm.nBitPerSample = audio->bits_per_sample;
       mmalil_omx_default_channel_mapping(param->pcm.eChannelMapping, audio->channels);
       if(format->encoding == MMAL_ENCODING_PCM_SIGNED_BE ||
          format->encoding == MMAL_ENCODING_PCM_SIGNED_LE ||
          format->encoding == MMAL_ENCODING_PCM_UNSIGNED_BE ||
          format->encoding == MMAL_ENCODING_PCM_UNSIGNED_LE)
       {
          param->pcm.ePCMMode = OMX_AUDIO_PCMModeLinear;
          param->pcm.bInterleaved = OMX_TRUE;
          param->pcm.eEndian = OMX_EndianLittle;
          param->pcm.eNumData = OMX_NumericalDataSigned;
          if(format->encoding == MMAL_ENCODING_PCM_SIGNED_BE ||
             format->encoding == MMAL_ENCODING_PCM_UNSIGNED_BE)
             param->pcm.eEndian = OMX_EndianBig;
          if(format->encoding == MMAL_ENCODING_PCM_UNSIGNED_LE ||
             format->encoding == MMAL_ENCODING_PCM_UNSIGNED_BE)
             param->pcm.eNumData = OMX_NumericalDataUnsigned;
       }
       else if(format->encoding == MMAL_ENCODING_ALAW)
          param->pcm.ePCMMode = OMX_AUDIO_PCMModeALaw;
       else if(format->encoding == MMAL_ENCODING_MULAW)
          param->pcm.ePCMMode = OMX_AUDIO_PCMModeMULaw;
       break;
    case OMX_AUDIO_CodingAAC:
       param->aac.nChannels = audio->channels;
       param->aac.nSampleRate = audio->sample_rate;
       param->aac.nBitRate = format->bitrate;
       switch(format->encoding_variant)
       {
       case MMAL_ENCODING_VARIANT_MP4A_ADTS:
          param->aac.eAACStreamFormat = OMX_AUDIO_AACStreamFormatMP4ADTS;
          break;
       case MMAL_ENCODING_VARIANT_MP4A_DEFAULT:
          param->aac.eAACStreamFormat = OMX_AUDIO_AACStreamFormatRAW;
          break;
       default: break;
       }
       break;
    case OMX_AUDIO_CodingMP3:
       param->mp3.nChannels = audio->channels;
       param->mp3.nSampleRate = audio->sample_rate;
       param->mp3.nBitRate = format->bitrate;
       break;
    case OMX_AUDIO_CodingWMA:
       param->wma.nChannels = audio->channels;
       param->wma.nSamplingRate = audio->sample_rate;
       param->wma.nBlockAlign = audio->block_align;
       param->wma.nBitRate = format->bitrate;
       switch(format->encoding)
       {
       case MMAL_ENCODING_WMA1:
          param->wma.eFormat = OMX_AUDIO_WMAFormat7;
          break;
       case MMAL_ENCODING_WMA2:
          param->wma.eFormat = OMX_AUDIO_WMAFormat8;
          break;
       default: break;
       }
       break;
    case OMX_AUDIO_CodingVORBIS:
       param->vorbis.nChannels = audio->channels;
       param->vorbis.nSampleRate = audio->sample_rate;
       param->vorbis.nBitRate = format->bitrate;
       break;
    case OMX_AUDIO_CodingAMR:
       param->amr.nChannels = audio->channels;
       param->amr.nBitRate = format->bitrate;
       if(format->encoding == MMAL_ENCODING_AMRNB)
          param->amr.eAMRBandMode = OMX_AUDIO_AMRBandModeNB0;
       if(format->encoding == MMAL_ENCODING_AMRWB)
          param->amr.eAMRBandMode = OMX_AUDIO_AMRBandModeWB0;
       break;
    case OMX_AUDIO_CodingDDP:
       param->ddp.nChannels = audio->channels;
       param->ddp.nSampleRate = audio->sample_rate;
       param->ddp.eBitStreamId = OMX_AUDIO_DDPBitStreamIdAC3;
       if(format->encoding == MMAL_ENCODING_EAC3)
          param->ddp.eBitStreamId = OMX_AUDIO_DDPBitStreamIdEAC3;
       param->ddp.eBitStreamMode = 0;
       param->ddp.eDolbySurroundMode = 0;
       mmalil_omx_default_channel_mapping(param->ddp.eChannelMapping, audio->channels);
       break;
    case OMX_AUDIO_CodingDTS:
       param->dts.nChannels = audio->channels;
       param->dts.nSampleRate = audio->sample_rate;
       param->dts.nDtsFrameSizeBytes = audio->block_align;
       param->dts.nDtsType = 1;
       param->dts.nFormat = 0;
       mmalil_omx_default_channel_mapping(param->dts.eChannelMapping, audio->channels);
       break;
    case OMX_AUDIO_CodingADPCM:
    case OMX_AUDIO_CodingGSMFR:
    case OMX_AUDIO_CodingGSMEFR:
    case OMX_AUDIO_CodingGSMHR:
    case OMX_AUDIO_CodingPDCFR:
    case OMX_AUDIO_CodingPDCEFR:
    case OMX_AUDIO_CodingPDCHR:
    case OMX_AUDIO_CodingTDMAFR:
    case OMX_AUDIO_CodingTDMAEFR:
    case OMX_AUDIO_CodingQCELP8:
    case OMX_AUDIO_CodingQCELP13:
    case OMX_AUDIO_CodingEVRC:
    case OMX_AUDIO_CodingSMV:
    case OMX_AUDIO_CodingG711:
    case OMX_AUDIO_CodingG723:
    case OMX_AUDIO_CodingG726:
    case OMX_AUDIO_CodingG729:
    case OMX_AUDIO_CodingSBC:
    case OMX_AUDIO_CodingRA:
    case OMX_AUDIO_CodingMIDI:
    default:
       vcos_assert(0);
       break;
    }
    return coding;
 }
mmalil_omx_audio_coding_to_encoding()
uint32_t mmalil_omx_audio_coding_to_encoding (OMX_AUDIO_CODINGTYPE coding)
Definition at line 272 of file mmal_il.c.
Referenced by mmalil_omx_audio_param_to_format(), and mmalil_omx_coding_to_encoding().
 {
    unsigned int i;
    for(i = 0; mmal_omx_audio_coding_table[i].encoding != MMAL_ENCODING_UNKNOWN; i++)
       if(mmal_omx_audio_coding_table[i].coding == coding) break;
    return mmal_omx_audio_coding_table[i].encoding;
 }
mmalil_omx_audio_param_index()
OMX_INDEXTYPE mmalil_omx_audio_param_index (OMX_AUDIO_CODINGTYPE coding, OMX_U32 * size)
Get the OMX_IndexParamAudio index corresponding to a specified audio coding type.
Parameters
coding Audio coding type.
size Pointer used to return the size of the parameter.
Returns
OMX index or 0 if no match was found.
Definition at line 333 of file mmal_il.c.
Referenced by mmalil_format_to_omx_audio_param().
 {
    unsigned int i;
    for(i = 0; mmal_omx_audio_format_table[i].coding != OMX_AUDIO_CodingUnused; i++)
       if(mmal_omx_audio_format_table[i].coding == coding) break;
    if(size) *size = mmal_omx_audio_format_table[i].size;
    return mmal_omx_audio_format_table[i].index;
 }
mmalil_omx_audio_param_index_to_coding()
OMX_AUDIO_CODINGTYPE mmalil_omx_audio_param_index_to_coding (OMX_INDEXTYPE index)
Get the audio coding corresponding to a specified OMX_IndexParamAudio index.
Parameters
index Audio coding type.
Returns
Audio coding type.
Definition at line 324 of file mmal_il.c.
 {
    unsigned int i;
    for(i = 0; mmal_omx_audio_format_table[i].coding != OMX_AUDIO_CodingUnused; i++)
       if(mmal_omx_audio_format_table[i].index == index) break;
    return mmal_omx_audio_format_table[i].coding;
 }
mmalil_omx_audio_param_to_format()
MMAL_FOURCC_T mmalil_omx_audio_param_to_format (MMAL_ES_FORMAT_T * format, OMX_AUDIO_CODINGTYPE coding, OMX_FORMAT_PARAM_TYPE * param)
Convert an OMX_IndexParamAudio into a MMAL elementary stream format.
Parameters
format Format structure to update.
coding Audio coding type.
param Source OMX_IndexParamAudio structure.
Returns
The MMAL encoding if a match was found or MMAL_ENCODING_UNKNOWN otherwise.
Definition at line 372 of file mmal_il.c.
References OMX_FORMAT_PARAM_TYPE::aac, OMX_FORMAT_PARAM_TYPE::amr, MMAL_ES_SPECIFIC_FORMAT_T::audio, OMX_AUDIO_PARAM_PCMMODETYPE::bInterleaved, MMAL_ES_FORMAT_T::bitrate, MMAL_AUDIO_FORMAT_T::bits_per_sample, MMAL_AUDIO_FORMAT_T::block_align, MMAL_AUDIO_FORMAT_T::channels, OMX_AUDIO_PARAM_AACPROFILETYPE::eAACStreamFormat, OMX_AUDIO_PARAM_AMRTYPE::eAMRBandMode, OMX_AUDIO_PARAM_PCMMODETYPE::eEndian, OMX_AUDIO_PARAM_WMATYPE::eFormat, MMAL_ES_FORMAT_T::encoding, MMAL_ES_FORMAT_T::encoding_variant, OMX_AUDIO_PARAM_PCMMODETYPE::eNumData, OMX_AUDIO_PARAM_PCMMODETYPE::ePCMMode, MMAL_ES_FORMAT_T::es, MMAL_ENCODING_ALAW, MMAL_ENCODING_AMRNB, MMAL_ENCODING_AMRWB, MMAL_ENCODING_EAC3, MMAL_ENCODING_MP4A, MMAL_ENCODING_MPGA, MMAL_ENCODING_MULAW, MMAL_ENCODING_PCM_SIGNED_BE, MMAL_ENCODING_PCM_SIGNED_LE, MMAL_ENCODING_PCM_UNSIGNED_BE, MMAL_ENCODING_PCM_UNSIGNED_LE, MMAL_ENCODING_VARIANT_MP4A_ADTS, MMAL_ENCODING_VARIANT_MP4A_DEFAULT, MMAL_ENCODING_WMA1, MMAL_ENCODING_WMA2, mmalil_omx_audio_coding_to_encoding(), OMX_FORMAT_PARAM_TYPE::mp3, OMX_AUDIO_PARAM_PCMMODETYPE::nBitPerSample, OMX_AUDIO_PARAM_MP3TYPE::nBitRate, OMX_AUDIO_PARAM_AACPROFILETYPE::nBitRate, OMX_AUDIO_PARAM_VORBISTYPE::nBitRate, OMX_AUDIO_PARAM_WMATYPE::nBitRate, OMX_AUDIO_PARAM_AMRTYPE::nBitRate, OMX_AUDIO_PARAM_WMATYPE::nBlockAlign, OMX_AUDIO_PARAM_PCMMODETYPE::nChannels, OMX_AUDIO_PARAM_MP3TYPE::nChannels, OMX_AUDIO_PARAM_AACPROFILETYPE::nChannels, OMX_AUDIO_PARAM_VORBISTYPE::nChannels, OMX_AUDIO_PARAM_WMATYPE::nChannels, OMX_AUDIO_PARAM_AMRTYPE::nChannels, OMX_AUDIO_PARAM_MP3TYPE::nSampleRate, OMX_AUDIO_PARAM_AACPROFILETYPE::nSampleRate, OMX_AUDIO_PARAM_VORBISTYPE::nSampleRate, OMX_AUDIO_PARAM_PCMMODETYPE::nSamplingRate, OMX_AUDIO_PARAM_WMATYPE::nSamplingRate, OMX_AUDIO_AACStreamFormatMP2ADTS, OMX_AUDIO_AACStreamFormatMP4ADTS, OMX_AUDIO_AACStreamFormatMP4FF, OMX_AUDIO_AACStreamFormatRAW, OMX_AUDIO_AMRBandModeNB0, OMX_AUDIO_AMRBandModeNB7, OMX_AUDIO_AMRBandModeWB0, OMX_AUDIO_AMRBandModeWB8, OMX_AUDIO_CodingAAC, OMX_AUDIO_CodingADPCM, OMX_AUDIO_CodingAMR, OMX_AUDIO_CodingDDP, OMX_AUDIO_CodingDTS, OMX_AUDIO_CodingEVRC, OMX_AUDIO_CodingG711, OMX_AUDIO_CodingG723, OMX_AUDIO_CodingG726, OMX_AUDIO_CodingG729, OMX_AUDIO_CodingGSMEFR, OMX_AUDIO_CodingGSMFR, OMX_AUDIO_CodingGSMHR, OMX_AUDIO_CodingMIDI, OMX_AUDIO_CodingMP3, OMX_AUDIO_CodingPCM, OMX_AUDIO_CodingPDCEFR, OMX_AUDIO_CodingPDCFR, OMX_AUDIO_CodingPDCHR, OMX_AUDIO_CodingQCELP13, OMX_AUDIO_CodingQCELP8, OMX_AUDIO_CodingRA, OMX_AUDIO_CodingSBC, OMX_AUDIO_CodingSMV, OMX_AUDIO_CodingTDMAEFR, OMX_AUDIO_CodingTDMAFR, OMX_AUDIO_CodingVORBIS, OMX_AUDIO_CodingWMA, OMX_AUDIO_DDPBitStreamIdAC3, OMX_AUDIO_PCMModeALaw, OMX_AUDIO_PCMModeLinear, OMX_AUDIO_PCMModeMULaw, OMX_AUDIO_WMAFormat7, OMX_AUDIO_WMAFormat8, OMX_AUDIO_WMAFormat9, OMX_EndianBig, OMX_EndianLittle, OMX_NumericalDataSigned, OMX_NumericalDataUnsigned, OMX_FORMAT_PARAM_TYPE::pcm, MMAL_AUDIO_FORMAT_T::sample_rate, vcos_assert, OMX_FORMAT_PARAM_TYPE::vorbis, and OMX_FORMAT_PARAM_TYPE::wma.
 {
    MMAL_AUDIO_FORMAT_T *audio = &format->es->audio;
    format->encoding = mmalil_omx_audio_coding_to_encoding(coding);
    format->encoding_variant = 0;
    switch(coding)
    {
    case OMX_AUDIO_CodingPCM:
       audio->channels = param->pcm.nChannels;
       audio->sample_rate = param->pcm.nSamplingRate;
       audio->bits_per_sample = param->pcm.nBitPerSample;
       if(param->pcm.ePCMMode == OMX_AUDIO_PCMModeLinear && param->pcm.bInterleaved)
       {
          if(param->pcm.eEndian == OMX_EndianBig &&
             param->pcm.eNumData == OMX_NumericalDataSigned)
             format->encoding = MMAL_ENCODING_PCM_SIGNED_BE;
          else if(param->pcm.eEndian == OMX_EndianLittle &&
             param->pcm.eNumData == OMX_NumericalDataSigned)
             format->encoding = MMAL_ENCODING_PCM_SIGNED_LE;
          if(param->pcm.eEndian == OMX_EndianBig &&
             param->pcm.eNumData == OMX_NumericalDataUnsigned)
             format->encoding = MMAL_ENCODING_PCM_UNSIGNED_BE;
          if(param->pcm.eEndian == OMX_EndianLittle &&
             param->pcm.eNumData == OMX_NumericalDataUnsigned)
             format->encoding = MMAL_ENCODING_PCM_UNSIGNED_LE;
       }
       else if(param->pcm.ePCMMode == OMX_AUDIO_PCMModeALaw)
          format->encoding = MMAL_ENCODING_ALAW;
       else if(param->pcm.ePCMMode == OMX_AUDIO_PCMModeMULaw)
          format->encoding = MMAL_ENCODING_MULAW;
       break;
    case OMX_AUDIO_CodingAAC:
       audio->channels = param->aac.nChannels;
       audio->sample_rate = param->aac.nSampleRate;
       format->bitrate = param->aac.nBitRate;
       switch(param->aac.eAACStreamFormat)
       {
       case OMX_AUDIO_AACStreamFormatMP2ADTS:
       case OMX_AUDIO_AACStreamFormatMP4ADTS:
          format->encoding = MMAL_ENCODING_MP4A;
          format->encoding_variant = MMAL_ENCODING_VARIANT_MP4A_ADTS;
          break;
       case OMX_AUDIO_AACStreamFormatMP4FF:
       case OMX_AUDIO_AACStreamFormatRAW:
          format->encoding = MMAL_ENCODING_MP4A;
          format->encoding_variant = MMAL_ENCODING_VARIANT_MP4A_DEFAULT;
          break;
       default: break;
       }
       break;
    case OMX_AUDIO_CodingMP3:
       format->encoding = MMAL_ENCODING_MPGA;
       audio->channels = param->mp3.nChannels;
       audio->sample_rate = param->mp3.nSampleRate;
       format->bitrate = param->mp3.nBitRate;
       break;
    case OMX_AUDIO_CodingWMA:
       audio->channels = param->wma.nChannels;
       audio->sample_rate = param->wma.nSamplingRate;
       audio->block_align = param->wma.nBlockAlign;
       format->bitrate = param->wma.nBitRate;
       switch(param->wma.eFormat)
       {
       case OMX_AUDIO_WMAFormat7:
          format->encoding = MMAL_ENCODING_WMA1;
          break;
       case OMX_AUDIO_WMAFormat8:
       case OMX_AUDIO_WMAFormat9:
          format->encoding = MMAL_ENCODING_WMA2;
          break;
       default: break;
       }
       break;
    case OMX_AUDIO_CodingVORBIS:
       audio->channels = param->vorbis.nChannels;
       audio->sample_rate = param->vorbis.nSampleRate;
       format->bitrate = param->vorbis.nBitRate;
       break;
    case OMX_AUDIO_CodingAMR:
       audio->channels = param->amr.nChannels;
       audio->sample_rate = 8000;
       format->bitrate = param->amr.nBitRate;
       if(param->amr.eAMRBandMode >= OMX_AUDIO_AMRBandModeNB0 &&
          param->amr.eAMRBandMode <= OMX_AUDIO_AMRBandModeNB7)
          format->encoding = MMAL_ENCODING_AMRNB;
       if(param->amr.eAMRBandMode >= OMX_AUDIO_AMRBandModeWB0 &&
          param->amr.eAMRBandMode <= OMX_AUDIO_AMRBandModeWB8)
          format->encoding = MMAL_ENCODING_AMRWB;
       break;
    case OMX_AUDIO_CodingDDP:
       audio->channels = param->ddp.nChannels;
       audio->sample_rate = param->ddp.nSampleRate;
       if(param->ddp.eBitStreamId > OMX_AUDIO_DDPBitStreamIdAC3)
          format->encoding = MMAL_ENCODING_EAC3;
       break;
    case OMX_AUDIO_CodingDTS:
       audio->channels = param->dts.nChannels;
       audio->sample_rate = param->dts.nSampleRate;
       audio->block_align = param->dts.nDtsFrameSizeBytes;
       break;
    case OMX_AUDIO_CodingADPCM:
    case OMX_AUDIO_CodingGSMFR:
    case OMX_AUDIO_CodingGSMEFR:
    case OMX_AUDIO_CodingGSMHR:
    case OMX_AUDIO_CodingPDCFR:
    case OMX_AUDIO_CodingPDCEFR:
    case OMX_AUDIO_CodingPDCHR:
    case OMX_AUDIO_CodingTDMAFR:
    case OMX_AUDIO_CodingTDMAEFR:
    case OMX_AUDIO_CodingQCELP8:
    case OMX_AUDIO_CodingQCELP13:
    case OMX_AUDIO_CodingEVRC:
    case OMX_AUDIO_CodingSMV:
    case OMX_AUDIO_CodingG711:
    case OMX_AUDIO_CodingG723:
    case OMX_AUDIO_CodingG726:
    case OMX_AUDIO_CodingG729:
    case OMX_AUDIO_CodingSBC:
    case OMX_AUDIO_CodingRA:
    case OMX_AUDIO_CodingMIDI:
    default:
       vcos_assert(0);
       break;
    }
    return format->encoding;
 }
mmalil_omx_bayer_format_order_to_encoding()
uint32_t mmalil_omx_bayer_format_order_to_encoding (OMX_BAYERORDERTYPE bayer_order, OMX_COLOR_FORMATTYPE color_format)
Definition at line 838 of file mmal_il.c.
 {
    unsigned int i;
    for(i = 0; mmal_omx_bayer_order_coding_table[i].encoding != MMAL_ENCODING_UNKNOWN; i++)
       if(mmal_omx_bayer_order_coding_table[i].bayer_order == bayer_order &&
          mmal_omx_bayer_order_coding_table[i].color_format == color_format)
          break;
    return mmal_omx_bayer_order_coding_table[i].encoding;
 }
mmalil_omx_coding_to_encoding()
uint32_t mmalil_omx_coding_to_encoding (uint32_t encoding, OMX_PORTDOMAINTYPE domain)
Definition at line 710 of file mmal_il.c.
References coding, encoding, MMAL_ENCODING_UNKNOWN, mmalil_omx_audio_coding_to_encoding(), mmalil_omx_image_coding_to_encoding(), mmalil_omx_video_coding_to_encoding(), OMX_PortDomainAudio, OMX_PortDomainImage, and OMX_PortDomainVideo.
 {
    if(domain == OMX_PortDomainVideo)
       return mmalil_omx_video_coding_to_encoding((OMX_VIDEO_CODINGTYPE)encoding);
    else if(domain == OMX_PortDomainAudio)
       return mmalil_omx_audio_coding_to_encoding((OMX_AUDIO_CODINGTYPE)encoding);
    else if(domain == OMX_PortDomainImage)
       return mmalil_omx_image_coding_to_encoding((OMX_IMAGE_CODINGTYPE)encoding);
    else
       return MMAL_ENCODING_UNKNOWN;
 }
mmalil_omx_color_format_to_encoding()
uint32_t mmalil_omx_color_format_to_encoding (OMX_COLOR_FORMATTYPE coding)
Definition at line 786 of file mmal_il.c.
 {
    unsigned int i;
    for(i = 0; mmal_omx_colorformat_coding_table[i].encoding != MMAL_ENCODING_UNKNOWN; i++)
       if(mmal_omx_colorformat_coding_table[i].coding == coding) break;
    return mmal_omx_colorformat_coding_table[i].encoding;
 }
mmalil_omx_color_space_to_mmal()
uint32_t mmalil_omx_color_space_to_mmal (OMX_COLORSPACETYPE coding)
Definition at line 874 of file mmal_il.c.
 {
    unsigned int i;
    for(i = 0; mmal_omx_colorspace_coding_table[i].mmal != MMAL_COLOR_SPACE_UNKNOWN; i++)
       if(mmal_omx_colorspace_coding_table[i].omx == coding) break;
    return mmal_omx_colorspace_coding_table[i].mmal;
 }
mmalil_omx_default_channel_mapping()
MMAL_STATUS_T mmalil_omx_default_channel_mapping (OMX_AUDIO_CHANNELTYPE * channel_mapping, unsigned int nchannels)
Setup a default channel mapping based on the number of channels
Parameters
channel_mapping The output channel mapping
nchannels Number of channels
Returns
MMAL_SUCCESS if we managed to produce a channel mapping
Definition at line 343 of file mmal_il.c.
References MMAL_COUNTOF, MMAL_EINVAL, MMAL_SUCCESS, OMX_AUDIO_ChannelCF, OMX_AUDIO_ChannelCS, OMX_AUDIO_ChannelLF, OMX_AUDIO_ChannelLFE, OMX_AUDIO_ChannelLR, OMX_AUDIO_ChannelLS, OMX_AUDIO_ChannelNone, OMX_AUDIO_ChannelRF, OMX_AUDIO_ChannelRR, and OMX_AUDIO_ChannelRS.
Referenced by mmalil_format_to_omx_audio_param().
 {
    static const OMX_AUDIO_CHANNELTYPE default_mapping[][8] = {
       {OMX_AUDIO_ChannelNone},
       {OMX_AUDIO_ChannelCF},
       {OMX_AUDIO_ChannelLF, OMX_AUDIO_ChannelRF},
       {OMX_AUDIO_ChannelLF, OMX_AUDIO_ChannelRF, OMX_AUDIO_ChannelCF},
       {OMX_AUDIO_ChannelLF, OMX_AUDIO_ChannelRF, OMX_AUDIO_ChannelCF,
          OMX_AUDIO_ChannelCS},
       {OMX_AUDIO_ChannelLF, OMX_AUDIO_ChannelRF, OMX_AUDIO_ChannelCF,
          OMX_AUDIO_ChannelLR, OMX_AUDIO_ChannelRR},
       {OMX_AUDIO_ChannelLF, OMX_AUDIO_ChannelRF, OMX_AUDIO_ChannelCF,
          OMX_AUDIO_ChannelLFE, OMX_AUDIO_ChannelLR, OMX_AUDIO_ChannelRR},
       {OMX_AUDIO_ChannelLF, OMX_AUDIO_ChannelRF, OMX_AUDIO_ChannelCF,
          OMX_AUDIO_ChannelLFE, OMX_AUDIO_ChannelLR, OMX_AUDIO_ChannelRR,
          OMX_AUDIO_ChannelCS},
       {OMX_AUDIO_ChannelLF, OMX_AUDIO_ChannelRF, OMX_AUDIO_ChannelCF,
          OMX_AUDIO_ChannelLFE, OMX_AUDIO_ChannelLR, OMX_AUDIO_ChannelRR,
          OMX_AUDIO_ChannelLS, OMX_AUDIO_ChannelRS}
    };
    if (!nchannels || nchannels >= MMAL_COUNTOF(default_mapping))
       return MMAL_EINVAL;
    memcpy(channel_mapping, default_mapping[nchannels],
       sizeof(default_mapping[0][0]) * nchannels);
    return MMAL_SUCCESS;
 }
mmalil_omx_domain_to_es_type()
MMAL_ES_TYPE_T mmalil_omx_domain_to_es_type (OMX_PORTDOMAINTYPE domain)
Definition at line 238 of file mmal_il.c.
 {
    unsigned int i;
    for(i = 0; mmal_omx_es_type_table[i].type != MMAL_ES_TYPE_UNKNOWN; i++)
       if(mmal_omx_es_type_table[i].domain == domain) break;
    return mmal_omx_es_type_table[i].type;
 }
mmalil_omx_image_coding_to_encoding()
uint32_t mmalil_omx_image_coding_to_encoding (OMX_IMAGE_CODINGTYPE coding)
Definition at line 694 of file mmal_il.c.
Referenced by mmalil_omx_coding_to_encoding().
 {
    unsigned int i;
    for(i = 0; mmal_omx_image_coding_table[i].encoding != MMAL_ENCODING_UNKNOWN; i++)
       if(mmal_omx_image_coding_table[i].coding == coding) break;
    return mmal_omx_image_coding_table[i].encoding;
 }
mmalil_omx_video_coding_to_encoding()
uint32_t mmalil_omx_video_coding_to_encoding (OMX_VIDEO_CODINGTYPE coding)
Definition at line 663 of file mmal_il.c.
Referenced by mmalil_omx_coding_to_encoding().
 {
    unsigned int i;
    for(i = 0; mmal_omx_video_coding_table[i].encoding != MMAL_ENCODING_UNKNOWN; i++)
       if(mmal_omx_video_coding_table[i].coding == coding) break;
    return mmal_omx_video_coding_table[i].encoding;
 }
mmalil_omx_video_intrarefresh_to_mmal()
MMAL_VIDEO_INTRA_REFRESH_T mmalil_omx_video_intrarefresh_to_mmal (OMX_VIDEO_INTRAREFRESHTYPE omx)
Definition at line 1054 of file mmal_il.c.
 {
    unsigned int i;
    for(i = 0; mmal_omx_video_intrarefresh_table[i].mmal != MMAL_VIDEO_INTRA_REFRESH_DUMMY; i++)
       if(mmal_omx_video_intrarefresh_table[i].omx == omx) break;
    return mmal_omx_video_intrarefresh_table[i].mmal;
 }
mmalil_omx_video_level_to_mmal()
uint32_t mmalil_omx_video_level_to_mmal (OMX_U32 level, OMX_VIDEO_CODINGTYPE coding)
Definition at line 993 of file mmal_il.c.
 {
    unsigned int i;
    for(i = 0; mmal_omx_video_level_table[i].mmal != MMAL_VIDEO_LEVEL_DUMMY; i++)
       if(mmal_omx_video_level_table[i].omx == level
          && mmal_omx_video_level_table[i].omx_coding == coding) break;
    return mmal_omx_video_level_table[i].mmal;
 }
mmalil_omx_video_profile_to_mmal()
uint32_t mmalil_omx_video_profile_to_mmal (OMX_U32 level, OMX_VIDEO_CODINGTYPE coding)
Definition at line 933 of file mmal_il.c.
 {
    unsigned int i;
    for(i = 0; mmal_omx_video_profile_table[i].mmal != MMAL_VIDEO_PROFILE_DUMMY; i++)
       if(mmal_omx_video_profile_table[i].omx == profile
          && mmal_omx_video_profile_table[i].omx_coding == coding) break;
    return mmal_omx_video_profile_table[i].mmal;
 }
mmalil_omx_video_ratecontrol_to_mmal()
MMAL_VIDEO_RATECONTROL_T mmalil_omx_video_ratecontrol_to_mmal (OMX_VIDEO_CONTROLRATETYPE omx)
Definition at line 1024 of file mmal_il.c.
 {
    unsigned int i;
    for(i = 0; mmal_omx_video_ratecontrol_table[i].mmal != MMAL_VIDEO_RATECONTROL_DUMMY; i++)
       if(mmal_omx_video_ratecontrol_table[i].omx == omx) break;
    return mmal_omx_video_ratecontrol_table[i].mmal;
 }
mmalil_video_buffer_flags_to_mmal()
uint32_t mmalil_video_buffer_flags_to_mmal (OMX_U32 flags)
Convert MMAL buffer header type video specific flags into OMX buffer header flags.
Parameters
flags OMX buffer header flags.
Returns
MMAL buffer header video specific flags.
Definition at line 157 of file mmal_il.c.
References MMAL_BUFFER_HEADER_VIDEO_FLAG_INTERLACED, MMAL_BUFFER_HEADER_VIDEO_FLAG_TOP_FIELD_FIRST, OMX_BUFFERFLAG_INTERLACED, and OMX_BUFFERFLAG_TOP_FIELD_FIRST.
 {
    uint32_t mmal_flags = 0;
    if (flags & OMX_BUFFERFLAG_INTERLACED)
       mmal_flags |= MMAL_BUFFER_HEADER_VIDEO_FLAG_INTERLACED;
    if (flags & OMX_BUFFERFLAG_TOP_FIELD_FIRST)
       mmal_flags |= MMAL_BUFFER_HEADER_VIDEO_FLAG_TOP_FIELD_FIRST;
    return mmal_flags;
 }
mmalil_video_buffer_flags_to_omx()
OMX_U32 mmalil_video_buffer_flags_to_omx (uint32_t flags)
Convert OMX buffer header flags into MMAL buffer header type video specific flags.
Parameters
flags MMAL buffer header video specific flags.
Returns
OMX buffer header flags.
Definition at line 145 of file mmal_il.c.
References MMAL_BUFFER_HEADER_VIDEO_FLAG_INTERLACED, MMAL_BUFFER_HEADER_VIDEO_FLAG_TOP_FIELD_FIRST, OMX_BUFFERFLAG_INTERLACED, and OMX_BUFFERFLAG_TOP_FIELD_FIRST.
 {
    OMX_U32 omx_flags = 0;
    if (flags & MMAL_BUFFER_HEADER_VIDEO_FLAG_INTERLACED)
       omx_flags |= OMX_BUFFERFLAG_INTERLACED;
    if (flags & MMAL_BUFFER_HEADER_VIDEO_FLAG_TOP_FIELD_FIRST)
      omx_flags |= OMX_BUFFERFLAG_TOP_FIELD_FIRST;
   return omx_flags;
 }
mmalil_video_level_to_omx()
OMX_U32 mmalil_video_level_to_omx (uint32_t level)
Definition at line 1002 of file mmal_il.c.
 {
    unsigned int i;
    for(i = 0; mmal_omx_video_level_table[i].mmal != MMAL_VIDEO_LEVEL_DUMMY; i++)
       if(mmal_omx_video_level_table[i].mmal == level) break;
    return mmal_omx_video_level_table[i].omx;
 }
mmalil_video_profile_to_omx()
OMX_U32 mmalil_video_profile_to_omx (uint32_t profile)
Definition at line 942 of file mmal_il.c.
 {
    unsigned int i;
    for(i = 0; mmal_omx_video_profile_table[i].mmal != MMAL_VIDEO_PROFILE_DUMMY; i++)
       if(mmal_omx_video_profile_table[i].mmal == profile) break;
    return mmal_omx_video_profile_table[i].omx;
 }
mmalil_video_ratecontrol_to_omx()
OMX_VIDEO_CONTROLRATETYPE mmalil_video_ratecontrol_to_omx (MMAL_VIDEO_RATECONTROL_T mmal)
Definition at line 1032 of file mmal_il.c.
 {
    unsigned int i;
    for(i = 0; mmal_omx_video_ratecontrol_table[i].mmal != MMAL_VIDEO_RATECONTROL_DUMMY; i++)
       if(mmal_omx_video_ratecontrol_table[i].mmal == mmal) break;
    return mmal_omx_video_ratecontrol_table[i].omx;
 }