VideoCore Library: Components
Components
Classes
struct MMAL_COMPONENT_T
Typedefs
typedef struct MMAL_COMPONENT_PRIVATE_T MMAL_COMPONENT_PRIVATE_T
typedef struct MMAL_COMPONENT_T MMAL_COMPONENT_T
Functions
MMAL_STATUS_T mmal_component_create (const char *name, MMAL_COMPONENT_T **component)
void mmal_component_acquire (MMAL_COMPONENT_T *component)
MMAL_STATUS_T mmal_component_release (MMAL_COMPONENT_T *component)
MMAL_STATUS_T mmal_component_destroy (MMAL_COMPONENT_T *component)
MMAL_STATUS_T mmal_component_enable (MMAL_COMPONENT_T *component)
MMAL_STATUS_T mmal_component_disable (MMAL_COMPONENT_T *component)
Detailed Description
Definition of a MMAL component and its associated API. A component will always expose ports which it uses to send and receive data in the form of buffer headers (MMAL_BUFFER_HEADER_T)
Typedef Documentation
MMAL_COMPONENT_PRIVATE_T
typedef struct MMAL_COMPONENT_PRIVATE_T MMAL_COMPONENT_PRIVATE_T
Definition at line 45 of file mmal_component.h.
MMAL_COMPONENT_T
typedef struct MMAL_COMPONENT_T MMAL_COMPONENT_T
Definition of a component.
Function Documentation
mmal_component_acquire()
void mmal_component_acquire (MMAL_COMPONENT_T * component)
Acquire a reference on a component. Acquiring a reference on a component will prevent a component from being destroyed until the acquired reference is released (by a call to mmal_component_destroy). References are internally counted so all acquired references need a matching call to release them.
Parameters
component component to acquire
Acquire a reference to a component
Definition at line 334 of file mmal_component.c.
References MMAL_COMPONENT_T::id, LOG_TRACE, MMAL_COMPONENT_T::name, MMAL_COMPONENT_T::priv, MMAL_COMPONENT_PRIVATE_T::refcount, vcos_mutex_lock(), and vcos_mutex_unlock().
Referenced by mmal_graph_add_component(), and mmal_graph_new_component().
 {
    MMAL_COMPONENT_CORE_PRIVATE_T *private = (MMAL_COMPONENT_CORE_PRIVATE_T *)component->priv;
    LOG_TRACE("component %s(%d), refcount %i", component->name, component->id,
              component->priv->refcount);
    vcos_mutex_lock(&private->lock);
    component->priv->refcount++;
    vcos_mutex_unlock(&private->lock);
 }
mmal_component_create()
MMAL_STATUS_T mmal_component_create (const char * name, MMAL_COMPONENT_T ** component)
Create an instance of a component. The newly created component will expose ports to the client. All the exposed ports are disabled by default. Note that components are reference counted and creating a component automatically acquires a reference to it (released when mmal_component_destroy is called).
Parameters
name name of the component to create, e.g. "video_decode"
component returned component
Returns
MMAL_SUCCESS on success
Create an instance of a component
Definition at line 214 of file mmal_component.c.
References LOG_TRACE.
Referenced by get_sensor_defaults(), mmal_graph_new_component(), mmal_wrapper_create(), and OMX_GetHandle().
 {
    LOG_TRACE("%s", name);
    return mmal_component_create_core(name, 0, 0, component);
 }
mmal_component_destroy()
MMAL_STATUS_T mmal_component_destroy (MMAL_COMPONENT_T * component)
Destroy a previously created component Release an acquired reference on a component. Only actually destroys the component when the last reference is being released.
Parameters
component component to destroy
Returns
MMAL_SUCCESS on success
Destroy a component
Definition at line 323 of file mmal_component.c.
References MMAL_COMPONENT_T::id, LOG_TRACE, MMAL_EINVAL, and MMAL_COMPONENT_T::name.
Referenced by get_sensor_defaults(), mmal_wrapper_create(), mmal_wrapper_destroy(), mmalplay_destroy(), OMX_FreeHandle(), and svp_destroy().
 {
    if(!component)
       return MMAL_EINVAL;
    LOG_TRACE("%s %d", component->name, component->id);
    return mmal_component_release_internal(component);
 }
mmal_component_disable()
MMAL_STATUS_T mmal_component_disable (MMAL_COMPONENT_T * component)
Disable processing on a component
Parameters
component component to disable
Returns
MMAL_SUCCESS on success
Disable processing on a component
Definition at line 406 of file mmal_component.c.
References MMAL_COMPONENT_T::id, MMAL_COMPONENT_T::input, MMAL_COMPONENT_T::input_num, MMAL_COMPONENT_T::is_enabled, LOG_TRACE, MMAL_EINVAL, MMAL_ENOSYS, mmal_port_pause(), MMAL_SUCCESS, MMAL_TRUE, MMAL_COMPONENT_T::name, MMAL_COMPONENT_T::output, MMAL_COMPONENT_T::output_num, MMAL_COMPONENT_PRIVATE_T::pf_disable, MMAL_COMPONENT_T::priv, status, vcos_mutex_lock(), and vcos_mutex_unlock().
Referenced by svp_destroy().
 {
    MMAL_COMPONENT_CORE_PRIVATE_T *private;
    MMAL_STATUS_T status = MMAL_ENOSYS;
    unsigned int i;
    if (!component)
       return MMAL_EINVAL;
    private = (MMAL_COMPONENT_CORE_PRIVATE_T *)component->priv;
    LOG_TRACE("%s %d", component->name, component->id);
    vcos_mutex_lock(&private->lock);
    /* Check we have anything to do */
    if (!component->is_enabled)
    {
       vcos_mutex_unlock(&private->lock);
       return MMAL_SUCCESS;
    }
    if (component->priv->pf_disable)
       status = component->priv->pf_disable(component);
    /* If the component does not support enable/disable, we handle that
     * in the core itself */
    if (status == MMAL_ENOSYS)
    {
       status = MMAL_SUCCESS;
       /* Pause all input / output ports */
       for (i = 0; status == MMAL_SUCCESS && i < component->input_num; i++)
          status = mmal_port_pause(component->input[i], MMAL_TRUE);
       for (i = 0; status == MMAL_SUCCESS && i < component->output_num; i++)
          status = mmal_port_pause(component->output[i], MMAL_TRUE);
    }
    if (status == MMAL_SUCCESS)
       component->is_enabled = 0;
    vcos_mutex_unlock(&private->lock);
    return status;
 }
mmal_component_enable()
MMAL_STATUS_T mmal_component_enable (MMAL_COMPONENT_T * component)
Enable processing on a component
Parameters
component component to enable
Returns
MMAL_SUCCESS on success
Enable processing on a component
Definition at line 359 of file mmal_component.c.
References MMAL_COMPONENT_T::id, MMAL_COMPONENT_T::input, MMAL_COMPONENT_T::input_num, MMAL_COMPONENT_T::is_enabled, LOG_TRACE, MMAL_EINVAL, MMAL_ENOSYS, MMAL_FALSE, mmal_port_pause(), MMAL_SUCCESS, MMAL_COMPONENT_T::name, MMAL_COMPONENT_T::output, MMAL_COMPONENT_T::output_num, MMAL_COMPONENT_PRIVATE_T::pf_enable, MMAL_COMPONENT_T::priv, status, vcos_mutex_lock(), and vcos_mutex_unlock().
 {
    MMAL_COMPONENT_CORE_PRIVATE_T *private;
    MMAL_STATUS_T status = MMAL_ENOSYS;
    unsigned int i;
    if(!component)
       return MMAL_EINVAL;
    private = (MMAL_COMPONENT_CORE_PRIVATE_T *)component->priv;
    LOG_TRACE("%s %d", component->name, component->id);
    vcos_mutex_lock(&private->lock);
    /* Check we have anything to do */
    if (component->is_enabled)
    {
       vcos_mutex_unlock(&private->lock);
       return MMAL_SUCCESS;
    }
    if (component->priv->pf_enable)
       status = component->priv->pf_enable(component);
    /* If the component does not support enable/disable, we handle that
     * in the core itself */
    if (status == MMAL_ENOSYS)
    {
       status = MMAL_SUCCESS;
       /* Resume all input / output ports */
       for (i = 0; status == MMAL_SUCCESS && i < component->input_num; i++)
          status = mmal_port_pause(component->input[i], MMAL_FALSE);
       for (i = 0; status == MMAL_SUCCESS && i < component->output_num; i++)
          status = mmal_port_pause(component->output[i], MMAL_FALSE);
    }
    if (status == MMAL_SUCCESS)
       component->is_enabled = 1;
    vcos_mutex_unlock(&private->lock);
    return status;
 }
mmal_component_release()
MMAL_STATUS_T mmal_component_release (MMAL_COMPONENT_T * component)
Release a reference on a component Release an acquired reference on a component. Triggers the destruction of the component when the last reference is being released.
Note
This is in fact an alias of mmal_component_destroy which is added to make client code clearer.
Parameters
component component to release
Returns
MMAL_SUCCESS on success
Release a reference to a component
Definition at line 347 of file mmal_component.c.
References MMAL_COMPONENT_T::id, LOG_TRACE, MMAL_EINVAL, MMAL_COMPONENT_T::name, MMAL_COMPONENT_T::priv, and MMAL_COMPONENT_PRIVATE_T::refcount.
Referenced by main(), and mmal_graph_destroy().
 {
    if(!component)
       return MMAL_EINVAL;
    LOG_TRACE("component %s(%d), refcount %i", component->name, component->id,
              component->priv->refcount);
    return mmal_component_release_internal(component);
 }