VideoCore Library: Container Module API
Container Module API
Classes
struct VC_CONTAINER_TRACK_PRIVATE_T
struct VC_CONTAINER_PRIVATE_T
Typedefs
typedef struct VC_CONTAINER_TRACK_PRIVATE_T VC_CONTAINER_TRACK_PRIVATE_T
typedef struct VC_CONTAINER_PRIVATE_T VC_CONTAINER_PRIVATE_T
Functions
VC_CONTAINER_TRACK_T * vc_container_allocate_track (VC_CONTAINER_T *context, unsigned int extra_size)
void vc_container_free_track (VC_CONTAINER_T *context, VC_CONTAINER_TRACK_T *track)
VC_CONTAINER_STATUS_T vc_container_track_allocate_extradata (VC_CONTAINER_T *context, VC_CONTAINER_TRACK_T *p_track, unsigned int extra_size)
VC_CONTAINER_STATUS_T vc_container_track_allocate_drmdata (VC_CONTAINER_T *context, VC_CONTAINER_TRACK_T *p_track, unsigned int size)
Detailed Description
Private interface for modules implementing container readers and writers
Typedef Documentation
VC_CONTAINER_PRIVATE_T
typedef struct VC_CONTAINER_PRIVATE_T VC_CONTAINER_PRIVATE_T
Context private to the container reader / writer instance. This private context is used to store data which shouldn't be exported by the public API.
VC_CONTAINER_TRACK_PRIVATE_T
typedef struct VC_CONTAINER_TRACK_PRIVATE_T VC_CONTAINER_TRACK_PRIVATE_T
Track context private to the container reader / writer instance. This private context is used to store data which shouldn't be exported by the public API.
Function Documentation
vc_container_allocate_track()
VC_CONTAINER_TRACK_T* vc_container_allocate_track (VC_CONTAINER_T * context, unsigned int extra_size)
Definition at line 561 of file containers.c.
Referenced by mpga_reader_open(), rawvideo_reader_open(), rcv_reader_open(), and wav_reader_open().
 {
    VC_CONTAINER_TRACK_T *p_ctx;
    unsigned int size;
    VC_CONTAINER_PARAM_UNUSED(context);
    size = sizeof(*p_ctx) + sizeof(*p_ctx->priv) + sizeof(*p_ctx->format) +
       sizeof(*p_ctx->format->type) + extra_size;
    p_ctx = malloc(size);
    if(!p_ctx) return 0;
    memset(p_ctx, 0, size);
    p_ctx->priv = (VC_CONTAINER_TRACK_PRIVATE_T *)(p_ctx + 1);
    p_ctx->format = (VC_CONTAINER_ES_FORMAT_T *)(p_ctx->priv + 1);
    p_ctx->format->type = (void *)(p_ctx->format + 1);
    p_ctx->priv->module = (struct VC_CONTAINER_TRACK_MODULE_T *)(p_ctx->format->type + 1);
    return p_ctx;
 }
vc_container_free_track()
void vc_container_free_track (VC_CONTAINER_T * context, VC_CONTAINER_TRACK_T * track)
Definition at line 582 of file containers.c.
 {
    VC_CONTAINER_PARAM_UNUSED(context);
    if(p_track)
    {
       if(p_track->priv->extradata) free(p_track->priv->extradata);
       if(p_track->priv->drmdata) free(p_track->priv->drmdata);
       free(p_track);
    }
 }
vc_container_track_allocate_drmdata()
VC_CONTAINER_STATUS_T vc_container_track_allocate_drmdata (VC_CONTAINER_T * context, VC_CONTAINER_TRACK_T * p_track, unsigned int size)
Definition at line 618 of file containers.c.
 {
    VC_CONTAINER_PARAM_UNUSED(context);
    /* Sanity check the size of the drm data */
    if(size > 200*1024) return VC_CONTAINER_ERROR_UNSUPPORTED_OPERATION;
    /* Check if we need to allocate a buffer */
    if(size > p_track->priv->drmdata_size)
    {
       p_track->priv->drmdata_size = 0;
       if(p_track->priv->drmdata) free(p_track->priv->drmdata);
       p_track->priv->drmdata = malloc(size);
       if(!p_track->priv->drmdata) return VC_CONTAINER_ERROR_OUT_OF_MEMORY;
       p_track->priv->drmdata_size = size;
    }
    return VC_CONTAINER_SUCCESS;
 }
vc_container_track_allocate_extradata()
VC_CONTAINER_STATUS_T vc_container_track_allocate_extradata (VC_CONTAINER_T * context, VC_CONTAINER_TRACK_T * p_track, unsigned int extra_size)
Definition at line 594 of file containers.c.
 {
    VC_CONTAINER_PARAM_UNUSED(context);
    /* Sanity check the size of the extra data */
    if(extra_size > 100*1024) return VC_CONTAINER_ERROR_UNSUPPORTED_OPERATION;
    /* Check if we need to allocate a buffer */
    if(extra_size > p_track->priv->extradata_size)
    {
       p_track->priv->extradata_size = 0;
       if(p_track->priv->extradata) free(p_track->priv->extradata);
       p_track->priv->extradata = malloc(extra_size);
       p_track->format->extradata = p_track->priv->extradata;
       if(!p_track->priv->extradata) return VC_CONTAINER_ERROR_OUT_OF_MEMORY;
       p_track->priv->extradata_size = extra_size;
    }
    p_track->format->extradata = p_track->priv->extradata;
    return VC_CONTAINER_SUCCESS;
 }