VideoCore Library: Packetizer API
Packetizer API
Classes
struct VC_PACKETIZER_T
Typedefs
typedef struct VC_PACKETIZER_T VC_PACKETIZER_T
Functions
VC_PACKETIZER_T * vc_packetizer_open (VC_CONTAINER_ES_FORMAT_T *in, VC_CONTAINER_FOURCC_T out_variant, VC_CONTAINER_STATUS_T *status)
VC_CONTAINER_STATUS_T vc_packetizer_close (VC_PACKETIZER_T *context)
VC_CONTAINER_STATUS_T vc_packetizer_push (VC_PACKETIZER_T *context, VC_CONTAINER_PACKET_T *packet)
VC_CONTAINER_STATUS_T vc_packetizer_pop (VC_PACKETIZER_T *context, VC_CONTAINER_PACKET_T **packet, VC_PACKETIZER_FLAGS_T flags)
VC_CONTAINER_STATUS_T vc_packetizer_read (VC_PACKETIZER_T *context, VC_CONTAINER_PACKET_T *out, VC_PACKETIZER_FLAGS_T flags)
VC_CONTAINER_STATUS_T vc_packetizer_reset (VC_PACKETIZER_T *context)
Packetizer flags
The following flags can be passed during a packetize call
typedef uint32_t VC_PACKETIZER_FLAGS_T
#define VC_PACKETIZER_FLAG_ES_CHANGED 0x1
#define VC_PACKETIZER_FLAG_INFO 0x1
#define VC_PACKETIZER_FLAG_SKIP 0x2
#define VC_PACKETIZER_FLAG_FLUSH 0x4
#define VC_PACKETIZER_FLAG_FORCE_RELEASE_INPUT 0x8
Detailed Description
API for packetizers
Macro Definition Documentation
VC_PACKETIZER_FLAG_ES_CHANGED
#define VC_PACKETIZER_FLAG_ES_CHANGED 0x1
ES definition has changed
Definition at line 48 of file packetizers.h.
VC_PACKETIZER_FLAG_FLUSH
#define VC_PACKETIZER_FLAG_FLUSH 0x4
Ask the packetizer to flush any data being processed
Definition at line 98 of file packetizers.h.
VC_PACKETIZER_FLAG_FORCE_RELEASE_INPUT
#define VC_PACKETIZER_FLAG_FORCE_RELEASE_INPUT 0x8
Force the packetizer to release an input packet
Definition at line 100 of file packetizers.h.
Referenced by vc_packetizer_pop().
VC_PACKETIZER_FLAG_INFO
#define VC_PACKETIZER_FLAG_INFO 0x1
Ask the packetizer to only return information on the next packet without reading it
Definition at line 94 of file packetizers.h.
VC_PACKETIZER_FLAG_SKIP
#define VC_PACKETIZER_FLAG_SKIP 0x2
Ask the packetizer to skip the next packet
Definition at line 96 of file packetizers.h.
Typedef Documentation
VC_PACKETIZER_FLAGS_T
typedef uint32_t VC_PACKETIZER_FLAGS_T
Type definition for the packetizer flags
Definition at line 92 of file packetizers.h.
VC_PACKETIZER_T
typedef struct VC_PACKETIZER_T VC_PACKETIZER_T
Definition of the packetizer type
Function Documentation
vc_packetizer_close()
VC_CONTAINER_STATUS_T vc_packetizer_close (VC_PACKETIZER_T * context)
Closes an instance of a packetizer. This will free all the resources associated with the context.
Parameters
context Pointer to the context of the instance to close
Returns
the status of the operation
Definition at line 115 of file packetizers.c.
References VC_PACKETIZER_T::in, VC_PACKETIZER_PRIVATE_T::module_handle, VC_PACKETIZER_T::out, VC_PACKETIZER_PRIVATE_T::pf_close, VC_PACKETIZER_T::priv, VC_PACKETIZER_PRIVATE_T::stream, vc_container_format_delete(), and VC_CONTAINER_SUCCESS.
Referenced by vc_container_close().
 {
    VC_CONTAINER_BYTESTREAM_T *stream;
    VC_CONTAINER_PACKET_T *packet, *next;
    if(!p_ctx) return VC_CONTAINER_SUCCESS;
    stream = &p_ctx->priv->stream;
    if(p_ctx->in) vc_container_format_delete(p_ctx->in);
    if(p_ctx->out) vc_container_format_delete(p_ctx->out);
    if(p_ctx->priv->pf_close) p_ctx->priv->pf_close(p_ctx);
    if(p_ctx->priv->module_handle) vc_packetizer_unload(p_ctx);
    /* Free the bytestream  */
    for(packet = stream->first; packet; packet = next)
    {
       next = packet->next;
       if(packet->framework_data) free(packet);
    }
    free(p_ctx);
    return VC_CONTAINER_SUCCESS;
 }
vc_packetizer_open()
VC_PACKETIZER_T* vc_packetizer_open (VC_CONTAINER_ES_FORMAT_T * in, VC_CONTAINER_FOURCC_T out_variant, VC_CONTAINER_STATUS_T * status)
Open a packetizer to convert the input format into the requested output format. This will create an an instance of a packetizer and its associated context.
If no packetizer is found for the requested format, this will return a null pointer as well as an error code indicating why this failed.
Parameters
in Input elementary stream format
out_variant Requested output variant for the output elementary stream format
status Returns the status of the operation
Returns
A pointer to the context of the new instance of the packetizer. Returns NULL on failure.
Definition at line 72 of file packetizers.c.
References bytestream_init(), VC_CONTAINER_ES_FORMAT_T::codec_variant, error(), VC_CONTAINER_ES_FORMAT_T::extradata, VC_CONTAINER_ES_FORMAT_T::extradata_size, VC_PACKETIZER_T::in, VC_PACKETIZER_T::out, VC_PACKETIZER_T::priv, status, VC_PACKETIZER_PRIVATE_T::stream, VC_PACKETIZER_PRIVATE_T::time, VC_CONTAINER_ERROR_OUT_OF_MEMORY, vc_container_format_copy(), vc_container_format_create(), VC_CONTAINER_SUCCESS, and vc_container_time_init().
 {
    VC_CONTAINER_STATUS_T status = VC_CONTAINER_SUCCESS;
    VC_PACKETIZER_T *p_ctx = 0;
    /* Allocate our context before trying out the different packetizers */
    p_ctx = malloc( sizeof(*p_ctx) + sizeof(*p_ctx->priv));
    if(!p_ctx) { status = VC_CONTAINER_ERROR_OUT_OF_MEMORY; goto error; }
    memset(p_ctx, 0, sizeof(*p_ctx) + sizeof(*p_ctx->priv));
    p_ctx->priv = (VC_PACKETIZER_PRIVATE_T *)(p_ctx + 1);
    bytestream_init( &p_ctx->priv->stream );
    p_ctx->in = vc_container_format_create(in->extradata_size);
    if(!p_ctx->in) { status = VC_CONTAINER_ERROR_OUT_OF_MEMORY; goto error; }
    p_ctx->out = vc_container_format_create(in->extradata_size);
    if(!p_ctx->out) { status = VC_CONTAINER_ERROR_OUT_OF_MEMORY; goto error; }
    vc_container_format_copy( p_ctx->in, in, in->extradata_size );
    p_ctx->in->extradata_size = 0;
    vc_container_format_copy( p_ctx->out, p_ctx->in, in->extradata_size );
    p_ctx->in->extradata_size = in->extradata_size;
    p_ctx->out->extradata = p_ctx->in->extradata;
    p_ctx->out->extradata_size = p_ctx->in->extradata_size;
    p_ctx->out->codec_variant = out_variant;
    vc_container_time_init(&p_ctx->priv->time, 1000000);
    status = vc_packetizer_load(p_ctx);
    if(status != VC_CONTAINER_SUCCESS)
       goto error;
  end:
    if(p_status) *p_status = status;
    return p_ctx;
  error:
    if(p_ctx) vc_packetizer_close(p_ctx);
    p_ctx = NULL;
    goto end;
 }
vc_packetizer_pop()
VC_CONTAINER_STATUS_T vc_packetizer_pop (VC_PACKETIZER_T * context, VC_CONTAINER_PACKET_T ** packet, VC_PACKETIZER_FLAGS_T flags)
Pop a packet of data from the packetizer. This allows the client to retrieve consumed data from the packetizer. Packets returned by the packetizer in this manner can then be released / recycled by the client. It is possible for the client to retrieve non-consumed data by passing the VC_PACKETIZER_FLAG_FORCE_RELEASE_INPUT flag. This will however trigger some internal buffering inside the packetizer and thus is less efficient.
Parameters
context Pointer to the context of the packetizer to use
packet Pointer used to return a consumed packet
flags Miscellaneous flags controlling the operation
Returns
VC_CONTAINER_SUCCESS if a consumed packet was retrieved, VC_CONTAINER_ERROR_INCOMPLETE_DATA if none is available.
Definition at line 152 of file packetizers.c.
References bytestream_pop(), VC_CONTAINER_BYTESTREAM_T::current, VC_CONTAINER_PACKET_T::data, VC_CONTAINER_BYTESTREAM_T::first, VC_CONTAINER_PACKET_T::framework_data, VC_CONTAINER_BYTESTREAM_T::last, VC_CONTAINER_PACKET_T::next, NULL, VC_PACKETIZER_T::priv, VC_CONTAINER_PACKET_T::size, VC_PACKETIZER_PRIVATE_T::stream, VC_CONTAINER_ERROR_INCOMPLETE_DATA, VC_CONTAINER_ERROR_OUT_OF_MEMORY, VC_CONTAINER_SUCCESS, and VC_PACKETIZER_FLAG_FORCE_RELEASE_INPUT.
 {
    VC_CONTAINER_BYTESTREAM_T *stream = &p_ctx->priv->stream;
    VC_CONTAINER_PACKET_T *packet, *new, **prev;
    /* Release the packets which have been read */
    while((*in = bytestream_pop(stream)) != NULL)
    {
       if(*in && (*in)->framework_data)
       {
          free(*in);
          continue;
       }
       if(*in)
          return VC_CONTAINER_SUCCESS;
    }
    if(!(flags & VC_PACKETIZER_FLAG_FORCE_RELEASE_INPUT))
       return VC_CONTAINER_ERROR_INCOMPLETE_DATA;
    /* Look for the 1st non-framework packet */
    for (packet = stream->first, prev = &stream->first;
         packet && packet->framework_data; prev = &packet->next, packet = packet->next);
    if (!packet || (packet && packet->framework_data))
       return VC_CONTAINER_ERROR_INCOMPLETE_DATA;
    /* We'll currently alloc an internal packet for each packet the client forcefully releases.
     * We could probably do something a bit more clever than that though. */
    /* Replace the packet with a newly allocated one */
    new = malloc(sizeof(*packet) + packet->size);
    if(!new)
       return VC_CONTAINER_ERROR_OUT_OF_MEMORY;
    *new = *packet;
    new->framework_data = new;
    if(!new->next)
       stream->last = &new->next;
    if(stream->current == packet)
       stream->current = new;
    *prev = new;
    new->data = (uint8_t *)&new[1];
    memcpy(new->data, packet->data, packet->size);
    *in = packet;
    return VC_CONTAINER_SUCCESS;
 }
vc_packetizer_push()
VC_CONTAINER_STATUS_T vc_packetizer_push (VC_PACKETIZER_T * context, VC_CONTAINER_PACKET_T * packet)
Push a new packet of data to the packetizer. This is the mechanism used to feed data into the packetizer. Once a packet has been pushed into the packetizer it is owned by the packetizer until released by a call to vc_packetizer_pop
Parameters
context Pointer to the context of the packetizer to use
packet Pointer to the VC_CONTAINER_PACKET_T structure describing the data packet to push into the packetizer.
Returns
the status of the operation
Definition at line 141 of file packetizers.c.
References bytestream_push(), VC_CONTAINER_PACKET_T::framework_data, VC_PACKETIZER_T::priv, VC_PACKETIZER_PRIVATE_T::stream, and VC_CONTAINER_SUCCESS.
 {
    /* Do some sanity checking on packet ? */
    in->framework_data = 0;
    bytestream_push(&p_ctx->priv->stream, in);
    return VC_CONTAINER_SUCCESS;
 }
vc_packetizer_read()
VC_CONTAINER_STATUS_T vc_packetizer_read (VC_PACKETIZER_T * context, VC_CONTAINER_PACKET_T * out, VC_PACKETIZER_FLAGS_T flags)
Read packetized data out of the packetizer.
Parameters
context Pointer to the context of the packetizer to use
packet Pointer to the VC_CONTAINER_PACKET_T structure describing the data packet This might need to be partially filled before the call (buffer, buffer_size) depending on the flags used.
flags Miscellaneous flags controlling the operation
Returns
the status of the operation
Definition at line 203 of file packetizers.c.
References VC_CONTAINER_PACKET_T::data, VC_PACKETIZER_PRIVATE_T::packet, VC_PACKETIZER_PRIVATE_T::pf_packetize, VC_PACKETIZER_T::priv, VC_CONTAINER_ERROR_INVALID_ARGUMENT, VC_CONTAINER_READ_FLAG_INFO, and VC_CONTAINER_READ_FLAG_SKIP.
 {
    if(!packet && !(flags & VC_CONTAINER_READ_FLAG_SKIP))
       return VC_CONTAINER_ERROR_INVALID_ARGUMENT;
    if(!packet && (flags & VC_CONTAINER_READ_FLAG_INFO))
       return VC_CONTAINER_ERROR_INVALID_ARGUMENT;
    if(packet && !packet->data &&
       (!(flags & VC_CONTAINER_READ_FLAG_INFO) &&
        !(flags & VC_CONTAINER_READ_FLAG_SKIP)))
       return VC_CONTAINER_ERROR_INVALID_ARGUMENT;
    /* Always having a packet structure to work with simplifies things */
    if(!packet)
       packet = &p_ctx->priv->packet;
    return p_ctx->priv->pf_packetize(p_ctx, packet, flags);
 }
vc_packetizer_reset()
VC_CONTAINER_STATUS_T vc_packetizer_reset (VC_PACKETIZER_T * context)
Reset packetizer state. This will reset the state of the packetizer as well as mark all data pushed to it as consumed.
Parameters
context Pointer to the context of the packetizer to reset
Returns
the status of the operation
Definition at line 223 of file packetizers.c.
References VC_CONTAINER_BYTESTREAM_T::bytes, bytestream_skip(), VC_CONTAINER_BYTESTREAM_T::current_offset, VC_CONTAINER_BYTESTREAM_T::offset, VC_PACKETIZER_PRIVATE_T::pf_reset, VC_PACKETIZER_T::priv, VC_PACKETIZER_PRIVATE_T::stream, and VC_CONTAINER_SUCCESS.
Referenced by vc_container_seek().
 {
    VC_CONTAINER_BYTESTREAM_T *stream = &p_ctx->priv->stream;
    bytestream_skip( stream, stream->bytes - stream->current_offset - stream->offset );
    if (p_ctx->priv->pf_reset)
       return p_ctx->priv->pf_reset(p_ctx);
    else
       return VC_CONTAINER_SUCCESS;
 }