VideoCore Library: interface/khronos/wf/wfc_client_stream.h File Reference
wfc_client_stream.h File Reference
#include "interface/vctypes/vc_image_types.h"
#include "interface/khronos/common/khrn_int_common.h"
#include "interface/khronos/include/WF/wfc.h"
#include "interface/khronos/wf/wfc_int.h"
#include "interface/khronos/include/EGL/eglext.h"
Macros
Flags
#define WFC_STREAM_FLAGS_NONE 0
#define WFC_STREAM_FLAGS_BUF_AVAIL (1 << 0)
Allow the server to indicate to the host when a buffer is available; for use with wfc_stream_await_buffer().
#define WFC_STREAM_FLAGS_ANDROID_GL_STREAM (1 << 2)
GNL - Hack up a new semaphore thing to make Android rendering wait.
#define WFC_STREAM_FLAGS_ANDROID_MM_STREAM (1 << 3)
So the reference to the vc image in the pool can be released.
#define WFC_STREAM_FLAGS_EGL (WFC_STREAM_FLAGS_BUF_AVAIL)
Flags needed to work with EGL.
Internal flags; do not use directly.
#define WFC_STREAM_FLAGS_REQ_RECT (1 << 31)
Allow the server to indicate to the host that a change to the source and/or destination rectangles has been requested by the server.
Typedefs
typedef void(* WFC_STREAM_REQ_RECT_CALLBACK_T) (void *args, const WFCint dest_rect[WFC_RECT_SIZE], const WFCfloat src_rect[WFC_RECT_SIZE])
Type for callback from wfc_stream_create_req_rect().
Functions
WFCNativeStreamType wfc_stream_get_next (void)
In cases where the caller doesn't want to assign a stream number, provide one for it.
uint32_t wfc_stream_create (WFCNativeStreamType stream, uint32_t flags)
Create a stream, using the given stream handle (typically assigned by the window manager). Return zero if OK.
WFCNativeStreamType wfc_stream_create_assign_id (uint32_t flags)
Create a stream, and automatically assign it a new stream number, which is returned.
uint32_t wfc_stream_create_req_rect (WFCNativeStreamType stream, uint32_t flags, WFC_STREAM_REQ_RECT_CALLBACK_T callback, void *cb_args)
Create a stream, using the given stream handle, which will notify the calling module when the server requests a change in source and/or destination rectangle, using the supplied callback. Return zero if OK.
bool wfc_stream_register_source_or_mask (WFCNativeStreamType stream, bool add_source_or_mask)
Indicate that a source or mask is now associated with this stream, or should now be removed from such an association.
void wfc_stream_await_buffer (WFCNativeStreamType stream)
Suspend until buffer is available on the server (requires WFC_STREAM_FLAGS_ASYNC_SEM to have been specified on creation).
void wfc_stream_destroy (WFCNativeStreamType stream)
Destroy a stream.
void wfc_stream_signal_eglimage_data (WFCNativeStreamType stream, EGLImageKHR im)
void wfc_stream_signal_eglimage_data_protected (WFCNativeStreamType stream, EGLImageKHR im, uint32_t is_protected)
void wfc_stream_release_eglimage_data (WFCNativeStreamType stream, EGLImageKHR im)
void wfc_stream_signal_mm_image_data (WFCNativeStreamType stream, uint32_t im)
void wfc_stream_signal_raw_pixels (WFCNativeStreamType stream, uint32_t handle, uint32_t format, uint32_t w, uint32_t h, uint32_t pitch, uint32_t vpitch)
void wfc_stream_signal_image (WFCNativeStreamType stream, const WFC_STREAM_IMAGE_T *image)
void wfc_stream_register (WFCNativeStreamType stream)
void wfc_stream_unregister (WFCNativeStreamType stream)
Off-screen composition functions
uint32_t wfc_stream_create_for_context (WFCNativeStreamType stream, uint32_t width, uint32_t height)
Create a stream for an off-screen context to output to, with the default number of buffers.
uint32_t wfc_stream_create_for_context_nbufs (WFCNativeStreamType stream, uint32_t width, uint32_t height, uint32_t nbufs)
Create a stream for an off-screen context to output to, with a specific number of buffers.
bool wfc_stream_used_for_off_screen (WFCNativeStreamType stream)
Returns true if this stream exists, and is in use as the output of an off-screen context.
void wfc_stream_register_off_screen (WFCNativeStreamType stream, bool used_for_off_screen)
Called on behalf of an off-screen context, to either set or clear the stream's flag indicating that it's being used as output for that context.
Macro Definition Documentation
WFC_STREAM_FLAGS_ANDROID_GL_STREAM
#define WFC_STREAM_FLAGS_ANDROID_GL_STREAM (1 << 2)
GNL - Hack up a new semaphore thing to make Android rendering wait.
Definition at line 46 of file wfc_client_stream.h.
WFC_STREAM_FLAGS_ANDROID_MM_STREAM
#define WFC_STREAM_FLAGS_ANDROID_MM_STREAM (1 << 3)
So the reference to the vc image in the pool can be released.
Definition at line 48 of file wfc_client_stream.h.
WFC_STREAM_FLAGS_BUF_AVAIL
#define WFC_STREAM_FLAGS_BUF_AVAIL (1 << 0)
Allow the server to indicate to the host when a buffer is available; for use with wfc_stream_await_buffer().
Definition at line 44 of file wfc_client_stream.h.
WFC_STREAM_FLAGS_EGL
#define WFC_STREAM_FLAGS_EGL (WFC_STREAM_FLAGS_BUF_AVAIL)
Flags needed to work with EGL.
Definition at line 51 of file wfc_client_stream.h.
WFC_STREAM_FLAGS_NONE
#define WFC_STREAM_FLAGS_NONE 0
Definition at line 41 of file wfc_client_stream.h.
WFC_STREAM_FLAGS_REQ_RECT
#define WFC_STREAM_FLAGS_REQ_RECT (1 << 31)
Allow the server to indicate to the host that a change to the source and/or destination rectangles has been requested by the server.
Definition at line 59 of file wfc_client_stream.h.
Typedef Documentation
WFC_STREAM_REQ_RECT_CALLBACK_T
typedef void(* WFC_STREAM_REQ_RECT_CALLBACK_T) (void *args, const WFCint dest_rect[WFC_RECT_SIZE], const WFCfloat src_rect[WFC_RECT_SIZE])
Type for callback from wfc_stream_create_req_rect().
Definition at line 66 of file wfc_client_stream.h.
Function Documentation
wfc_stream_await_buffer()
void wfc_stream_await_buffer (WFCNativeStreamType stream)
Suspend until buffer is available on the server (requires WFC_STREAM_FLAGS_ASYNC_SEM to have been specified on creation).
Definition at line 314 of file wfc_client_stream.c.
References VCOS_FUNCTION.
 {
    vcos_log_trace("%s: stream 0x%x", VCOS_FUNCTION, stream);
    WFC_STREAM_T *stream_ptr = wfc_stream_find_stream_ptr(stream);
    if (!stream_ptr)
       return;
    if(vcos_verify(stream_ptr->info.flags & WFC_STREAM_FLAGS_BUF_AVAIL))
    {
       VCOS_SEMAPHORE_T image_available_sem;
       VCOS_STATUS_T status;
       // Long running operation, so keep VC alive until it completes.
       wfc_server_use_keep_alive();
       status = vcos_semaphore_create(&image_available_sem, "WFC image available", 0);
       vcos_assert(status == VCOS_SUCCESS);      // For all relevant platforms
       vcos_unused(status);
       wfc_server_stream_on_image_available(stream, wfc_client_stream_post_sem, &image_available_sem);
       vcos_log_trace("%s: pre async sem wait: stream: %X", VCOS_FUNCTION, stream);
       vcos_semaphore_wait(&image_available_sem);
       vcos_log_trace("%s: post async sem wait: stream: %X", VCOS_FUNCTION, stream);
       vcos_semaphore_delete(&image_available_sem);
       wfc_server_release_keep_alive();
    }
    STREAM_UNLOCK(stream_ptr);
 }
wfc_stream_create()
uint32_t wfc_stream_create (WFCNativeStreamType stream, uint32_t flags)
Create a stream, using the given stream handle (typically assigned by the window manager). Return zero if OK.
Definition at line 164 of file wfc_client_stream.c.
References VCOS_FUNCTION.
Referenced by wfc_stream_create_assign_id().
 {
    WFC_STREAM_T *stream_ptr;
    uint32_t result = 0;
    vcos_log_info("%s: stream 0x%x flags 0x%x", VCOS_FUNCTION, stream, flags);
    // Create stream
    stream_ptr = wfc_stream_create_stream_ptr(stream, false);
    if(stream_ptr == NULL)
    {
       vcos_log_error("%s: unable to create data block for stream 0x%x", VCOS_FUNCTION, stream);
       return VCOS_ENOMEM;
    }
    uint64_t pid = vcos_process_id_current();
    uint32_t pid_lo = (uint32_t) pid;
    uint32_t pid_hi = (uint32_t) (pid >> 32);
    int stream_in_use_retries = WFC_STREAM_RETRIES;
    WFC_STREAM_INFO_T info;
    memset(&info, 0, sizeof(info));
    info.size = sizeof(info);
    info.flags = flags;
    do
    {
       stream_ptr->handle = wfc_server_stream_create_info(stream, &info, pid_lo, pid_hi);
       vcos_log_trace("%s: server create returned 0x%x", VCOS_FUNCTION, stream_ptr->handle);
       // If a handle is re-used rapidly, it may still be in use in the server temporarily
       // Retry after a short delay
       if (stream_ptr->handle == WFC_INVALID_HANDLE)
          vcos_sleep(WFC_STREAM_RETRY_DELAY_MS);
    }
    while (stream_ptr->handle == WFC_INVALID_HANDLE && stream_in_use_retries-- > 0);
    if (stream_ptr->handle == WFC_INVALID_HANDLE)
    {
       // Even after the retries, stream handle was still in use. Fail.
       vcos_log_error("%s: stream 0x%x already exists in server", VCOS_FUNCTION, stream);
       result = VCOS_EEXIST;
       wfc_stream_destroy_if_ready(stream_ptr);
    }
    else
    {
       vcos_assert(stream_ptr->handle == stream);
       stream_ptr->registrations++;
       stream_ptr->info.flags = flags;
       STREAM_UNLOCK(stream_ptr);
    }
    return result;
 }
wfc_stream_create_assign_id()
WFCNativeStreamType wfc_stream_create_assign_id (uint32_t flags)
Create a stream, and automatically assign it a new stream number, which is returned.
Definition at line 224 of file wfc_client_stream.c.
References VCOS_EEXIST, WFC_INVALID_HANDLE, wfc_stream_create(), wfc_stream_create_req_rect(), and wfc_stream_get_next().
 {
    WFCNativeStreamType stream = wfc_stream_get_next();
    uint32_t failure = wfc_stream_create(stream, flags);
    if (failure == VCOS_EEXIST)
    {
       // If a duplicate stream exists, give it one more go with a new ID
       stream = wfc_stream_get_next();
       failure = wfc_stream_create(stream, flags);
    }
    if(failure) {return WFC_INVALID_HANDLE;}
    else {return stream;}
 }
wfc_stream_create_for_context()
uint32_t wfc_stream_create_for_context (WFCNativeStreamType stream, uint32_t width, uint32_t height)
Create a stream for an off-screen context to output to, with the default number of buffers.
Definition at line 391 of file wfc_client_stream.c.
References wfc_stream_create_for_context_nbufs().
 {
    return wfc_stream_create_for_context_nbufs(stream, width, height, 0);
 }
wfc_stream_create_for_context_nbufs()
uint32_t wfc_stream_create_for_context_nbufs (WFCNativeStreamType stream, uint32_t width, uint32_t height, uint32_t nbufs)
Create a stream for an off-screen context to output to, with a specific number of buffers.
Definition at line 398 of file wfc_client_stream.c.
References vcos_verify, and WFC_INVALID_HANDLE.
Referenced by wfc_stream_create_for_context().
 {
    WFC_STREAM_T *stream_ptr;
    bool stream_created = false;
    if(!vcos_verify(stream != WFC_INVALID_HANDLE))
       {return 1;}
    stream_ptr = wfc_stream_find_stream_ptr(stream);
    if (stream_ptr)
    {
       uint32_t flags = stream_ptr->info.flags;
       // Stream already exists, check flags match expected
       STREAM_UNLOCK(stream_ptr);
       if (flags != WFC_STREAM_FLAGS_NONE)
       {
          vcos_log_error("%s: stream flags mismatch (expected 0x%x, got 0x%x)", VCOS_FUNCTION, WFC_STREAM_FLAGS_NONE, flags);
          return 1;
       }
    }
    else
    {
       // Create stream
       if (wfc_stream_create(stream, WFC_STREAM_FLAGS_NONE) != 0)
          return 1;
       stream_created = true;
    }
    // Allocate buffers on the server.
    if (!wfc_server_stream_allocate_images(stream, width, height, nbufs))
    {
       // Failed to allocate buffers
       vcos_log_warn("%s: failed to allocate %u buffers for stream %X size %ux%u", VCOS_FUNCTION, nbufs, stream, width, height);
       if (stream_created)
          wfc_stream_destroy(stream);
       return 1;
    }
    return 0;
 }
wfc_stream_create_req_rect()
uint32_t wfc_stream_create_req_rect (WFCNativeStreamType stream, uint32_t flags, WFC_STREAM_REQ_RECT_CALLBACK_T callback, void * cb_args)
Create a stream, using the given stream handle, which will notify the calling module when the server requests a change in source and/or destination rectangle, using the supplied callback. Return zero if OK.
Definition at line 244 of file wfc_client_stream.c.
Referenced by wfc_stream_create_assign_id().
 {
    vcos_log_info("wfc_stream_create_req_rect: stream %X", stream);
    uint32_t failure;
    failure = wfc_stream_create(stream, flags | WFC_STREAM_FLAGS_REQ_RECT);
    if (failure)
       return failure;
    WFC_STREAM_T *stream_ptr = wfc_stream_find_stream_ptr(stream);
    // Stream just created, so ought to be found
    vcos_assert(stream_ptr);
    // There's no point creating this type of stream if you don't supply a callback
    // to update the src/dest rects via WF-C.
    vcos_assert(callback != NULL);
    stream_ptr->req_rect_callback = callback;
    stream_ptr->req_rect_cb_args = cb_args;
    // Create thread for handling server-side request to change source
    // and/or destination rectangles. One per stream (if enabled).
    VCOS_STATUS_T status = vcos_thread_create(&stream_ptr->rect_req_thread_data, "wfc_stream_rect_req_thread",
       NULL, wfc_stream_rect_req_thread, (void *) stream);
    vcos_demand(status == VCOS_SUCCESS);
    STREAM_UNLOCK(stream_ptr);
    return 0;
 }
wfc_stream_destroy()
void wfc_stream_destroy (WFCNativeStreamType stream)
Destroy a stream.
Definition at line 351 of file wfc_client_stream.c.
References VCOS_FUNCTION.
 {
    vcos_log_info("%s: stream: %X", VCOS_FUNCTION, stream);
    WFC_STREAM_T *stream_ptr = wfc_stream_find_stream_ptr(stream);
    if (stream_ptr)
    {
       /* If stream is still in use (e.g. it's attached to at least one source/mask
        * which is associated with at least one element) then destruction is delayed
        * until it's no longer in use. */
       if (stream_ptr->registrations> 0)
       {
          stream_ptr->registrations--;
          vcos_log_trace("%s: stream: %X ready to destroy?", VCOS_FUNCTION, stream);
       }
       else
       {
          vcos_log_error("%s: stream: %X destroyed when unregistered", VCOS_FUNCTION, stream);
       }
       // Stream is unlocked by destroy_if_ready
       wfc_stream_destroy_if_ready(stream_ptr);
    }
    else
    {
       vcos_log_warn("%s: stream %X doesn't exist", VCOS_FUNCTION, stream);
    }
 }
wfc_stream_get_next()
WFCNativeStreamType wfc_stream_get_next (void)
In cases where the caller doesn't want to assign a stream number, provide one for it.
Definition at line 148 of file wfc_client_stream.c.
References GLOBAL_LOCK.
Referenced by wfc_stream_create_assign_id().
 {
    GLOBAL_LOCK();
    WFCNativeStreamType next_stream = wfc_stream_next_handle;
    wfc_stream_next_handle++;
    GLOBAL_UNLOCK();
    return next_stream;
 }
wfc_stream_register()
void wfc_stream_register (WFCNativeStreamType stream)
Definition at line 983 of file wfc_client_stream.c.
References WFC_STREAM_tag::info, WFC_STREAM_INFO_T::size, status, vcos_process_id_current(), VCOS_SUCCESS, wfc_server_connect(), and wfc_server_stream_get_info().
{
    uint64_t pid = vcos_process_id_current();
    uint32_t pid_lo = (uint32_t)pid;
    uint32_t pid_hi = (uint32_t)(pid >> 32);
    if (wfc_server_connect() == VCOS_SUCCESS)
    {
       WFC_STREAM_INFO_T info;
       uint32_t status;
       info.size = sizeof(info);
       status = wfc_server_stream_get_info(stream, &info);
       if (status == VCOS_SUCCESS)
       {
          WFC_STREAM_T *stream_ptr = wfc_stream_create_stream_ptr(stream, true);
          if (stream_ptr)
          {
             stream_ptr->registrations++;
             memcpy(&stream_ptr->info, &info, info.size);
             STREAM_UNLOCK(stream_ptr);
          }
          wfc_server_stream_register(stream, pid_lo, pid_hi);
       }
       else
       {
          vcos_log_error("%s: get stream info failed: %u", VCOS_FUNCTION, status);
       }
    }
 }
wfc_stream_register_off_screen()
void wfc_stream_register_off_screen (WFCNativeStreamType stream, bool used_for_off_screen)
Called on behalf of an off-screen context, to either set or clear the stream's flag indicating that it's being used as output for that context.
Definition at line 466 of file wfc_client_stream.c.
References VCOS_FUNCTION, and WFC_INVALID_HANDLE.
 {
    if(stream == WFC_INVALID_HANDLE)
       {return;}
    vcos_log_trace("%s: stream 0x%x", VCOS_FUNCTION, stream);
    WFC_STREAM_T *stream_ptr = wfc_stream_find_stream_ptr(stream);
    if (!stream_ptr)
       return;
    stream_ptr->used_for_off_screen = used_for_off_screen;
    if (used_for_off_screen)
       STREAM_UNLOCK(stream_ptr);
    else
    {
       // Stream is unlocked by destroy_if_ready
       wfc_stream_destroy_if_ready(stream_ptr);
    }
 }
wfc_stream_register_source_or_mask()
bool wfc_stream_register_source_or_mask (WFCNativeStreamType stream, bool add_source_or_mask)
Indicate that a source or mask is now associated with this stream, or should now be removed from such an association.
Returns
True if successful, false if not (invalid handle).
Definition at line 282 of file wfc_client_stream.c.
 {
    WFC_STREAM_T *stream_ptr = wfc_stream_find_stream_ptr(stream);
    if (!stream_ptr)
       return false;
    vcos_log_trace("%s: stream 0x%x %d->%d", VCOS_FUNCTION, stream,
          stream_ptr->num_of_sources_or_masks,
          add_source_or_mask ? stream_ptr->num_of_sources_or_masks + 1 : stream_ptr->num_of_sources_or_masks - 1);
    if(add_source_or_mask)
    {
       stream_ptr->num_of_sources_or_masks++;
       STREAM_UNLOCK(stream_ptr);
    }
    else
    {
       if(vcos_verify(stream_ptr->num_of_sources_or_masks > 0))
          {stream_ptr->num_of_sources_or_masks--;}
       // Stream is unlocked by destroy_if_ready
       wfc_stream_destroy_if_ready(stream_ptr);
    }
    return true;
 }
wfc_stream_release_eglimage_data()
void wfc_stream_release_eglimage_data (WFCNativeStreamType stream, EGLImageKHR im)
wfc_stream_signal_eglimage_data()
void wfc_stream_signal_eglimage_data (WFCNativeStreamType stream, EGLImageKHR im)
wfc_stream_signal_eglimage_data_protected()
void wfc_stream_signal_eglimage_data_protected (WFCNativeStreamType stream, EGLImageKHR im, uint32_t is_protected)
wfc_stream_signal_image()
void wfc_stream_signal_image (WFCNativeStreamType stream, const WFC_STREAM_IMAGE_T * image)
Definition at line 977 of file wfc_client_stream.c.
References wfc_server_stream_signal_image().
 {
    wfc_server_stream_signal_image(stream, image);
 }
wfc_stream_signal_mm_image_data()
void wfc_stream_signal_mm_image_data (WFCNativeStreamType stream, uint32_t im)
Definition at line 966 of file wfc_client_stream.c.
References wfc_server_stream_signal_mm_image_data().
 {
    wfc_server_stream_signal_mm_image_data(stream, im);
 }
wfc_stream_signal_raw_pixels()
void wfc_stream_signal_raw_pixels (WFCNativeStreamType stream, uint32_t handle, uint32_t format, uint32_t w, uint32_t h, uint32_t pitch, uint32_t vpitch)
Definition at line 971 of file wfc_client_stream.c.
References wfc_server_stream_signal_raw_pixels().
 {
    wfc_server_stream_signal_raw_pixels(stream, handle, format, w, h, pitch, vpitch);
 }
wfc_stream_unregister()
void wfc_stream_unregister (WFCNativeStreamType stream)
Definition at line 1016 of file wfc_client_stream.c.
References vcos_process_id_current().
{
    uint64_t pid = vcos_process_id_current();
    uint32_t pid_lo = (uint32_t)pid;
    uint32_t pid_hi = (uint32_t)(pid >> 32);
    WFC_STREAM_T *stream_ptr = wfc_stream_find_stream_ptr(stream);
    if (vcos_verify(stream_ptr != NULL))
    {
       wfc_server_stream_unregister(stream, pid_lo, pid_hi);
       if (stream_ptr->registrations > 0)
       {
          stream_ptr->registrations--;
          vcos_log_trace("%s: stream %X", VCOS_FUNCTION, stream);
       }
       else
       {
          vcos_log_error("%s: stream %X already fully unregistered", VCOS_FUNCTION, stream);
       }
       wfc_stream_destroy_if_ready(stream_ptr);
    }
    wfc_server_disconnect();
 }
wfc_stream_used_for_off_screen()
bool wfc_stream_used_for_off_screen (WFCNativeStreamType stream)
Returns true if this stream exists, and is in use as the output of an off-screen context.
Definition at line 444 of file wfc_client_stream.c.
References WFC_STREAM_tag::used_for_off_screen, and VCOS_FUNCTION.
 {
    bool used_for_off_screen;
    vcos_log_trace("%s: stream 0x%x", VCOS_FUNCTION, stream);
    WFC_STREAM_T *stream_ptr = wfc_stream_find_stream_ptr(stream);
    if (!stream_ptr)
       return false;
    used_for_off_screen = stream_ptr->used_for_off_screen;
    STREAM_UNLOCK(stream_ptr);
    return used_for_off_screen;
 }