VideoCore Library: interface/mmal/core/mmal_buffer_private.h File Reference
mmal_buffer_private.h File Reference
Classes
struct MMAL_BUFFER_HEADER_PRIVATE_T
Macros
#define MMAL_DRIVER_BUFFER_SIZE 32
Typedefs
typedef struct MMAL_DRIVER_BUFFER_T MMAL_DRIVER_BUFFER_T
typedef struct MMAL_BUFFER_HEADER_PRIVATE_T MMAL_BUFFER_HEADER_PRIVATE_T
Functions
unsigned int mmal_buffer_header_size (MMAL_BUFFER_HEADER_T *header)
MMAL_BUFFER_HEADER_T * mmal_buffer_header_initialise (void *mem, unsigned int length)
MMAL_DRIVER_BUFFER_T * mmal_buffer_header_driver_data (MMAL_BUFFER_HEADER_T *)
MMAL_BUFFER_HEADER_T * mmal_buffer_header_reference (MMAL_BUFFER_HEADER_T *header)
Macro Definition Documentation
MMAL_DRIVER_BUFFER_SIZE
#define MMAL_DRIVER_BUFFER_SIZE 32
Size of the private area the framework reserves for the driver / communication layer
Definition at line 35 of file mmal_buffer_private.h.
Typedef Documentation
MMAL_BUFFER_HEADER_PRIVATE_T
typedef struct MMAL_BUFFER_HEADER_PRIVATE_T MMAL_BUFFER_HEADER_PRIVATE_T
Typedef for the framework's private area in the buffer header
MMAL_DRIVER_BUFFER_T
typedef struct MMAL_DRIVER_BUFFER_T MMAL_DRIVER_BUFFER_T
Typedef for the private area the framework reserves for the driver / communication layer
Definition at line 32 of file mmal_buffer_private.h.
Function Documentation
mmal_buffer_header_driver_data()
MMAL_DRIVER_BUFFER_T* mmal_buffer_header_driver_data (MMAL_BUFFER_HEADER_T * header)
Return a pointer to the area reserved for the driver.
Return a pointer to the area reserved for the driver
Definition at line 141 of file mmal_buffer.c.
References MMAL_BUFFER_HEADER_PRIVATE_T::driver_area, and MMAL_BUFFER_HEADER_T::priv.
 {
    return (MMAL_DRIVER_BUFFER_T *)header->priv->driver_area;
 }
mmal_buffer_header_initialise()
MMAL_BUFFER_HEADER_T* mmal_buffer_header_initialise (void * mem, unsigned int length)
Initialise a MMAL_BUFFER_HEADER_T
Definition at line 124 of file mmal_buffer.c.
References mmal_buffer_header_size(), MMAL_BUFFER_HEADER_T::priv, and MMAL_BUFFER_HEADER_T::type.
 {
    MMAL_BUFFER_HEADER_T *header;
    unsigned int header_size = mmal_buffer_header_size(0);
    if(length < header_size)
       return 0;
    memset(mem, 0, header_size);
    header = (MMAL_BUFFER_HEADER_T *)mem;
    header->type = (void *)&header[1];
    header->priv = (MMAL_BUFFER_HEADER_PRIVATE_T *)&header->type[1];
    return header;
 }
mmal_buffer_header_reference()
MMAL_BUFFER_HEADER_T* mmal_buffer_header_reference (MMAL_BUFFER_HEADER_T * header)
Return a pointer to a referenced buffer header. It is the caller's responsibility to ensure that the reference is still valid when using it.
Return a pointer to a referenced buffer header
Definition at line 147 of file mmal_buffer.c.
References MMAL_BUFFER_HEADER_T::priv, and MMAL_BUFFER_HEADER_PRIVATE_T::reference.
 {
    return header->priv->reference;
 }
mmal_buffer_header_size()
unsigned int mmal_buffer_header_size (MMAL_BUFFER_HEADER_T * header)
Get the size in bytes of a fully initialised MMAL_BUFFER_HEADER_T
Definition at line 112 of file mmal_buffer.c.
References ALIGN, DEFAULT_COMMAND_SIZE, MMAL_BUFFER_HEADER_T::priv, ROUND_UP, and MMAL_BUFFER_HEADER_T::type.
Referenced by mmal_buffer_header_initialise(), and mmal_pool_create_with_allocator().
 {
    unsigned int header_size;
    header_size = ROUND_UP(sizeof(*header), ALIGN);
    header_size += ROUND_UP(sizeof(*header->type), ALIGN);
    header_size += ROUND_UP(DEFAULT_COMMAND_SIZE, ALIGN);
    header_size += ROUND_UP(sizeof(*header->priv), ALIGN);
    return header_size;
 }