VideoCore Library: interface/mmal/openmaxil/mmalomx_util_params.h File Reference
mmalomx_util_params.h File Reference
Classes
struct MMALOMX_PARAM_OMX_HEADER_T
struct MMALOMX_PARAM_OMX_HEADER_PORTLESS_T
struct MMALOMX_PARAM_ENUM_TRANSLATE_T
struct MMALOMX_PARAM_TRANSLATION_T
Typedefs
typedef struct MMALOMX_PARAM_OMX_HEADER_T MMALOMX_PARAM_OMX_HEADER_T
typedef struct MMALOMX_PARAM_OMX_HEADER_PORTLESS_T MMALOMX_PARAM_OMX_HEADER_PORTLESS_T
typedef struct MMALOMX_PARAM_ENUM_TRANSLATE_T MMALOMX_PARAM_ENUM_TRANSLATE_T
typedef enum MMALOMX_PARAM_TRANSLATION_TYPE_T MMALOMX_PARAM_TRANSLATION_TYPE_T
typedef struct MMALOMX_PARAM_TRANSLATION_T MMALOMX_PARAM_TRANSLATION_T
Enumerations
enum MMALOMX_PARAM_MAPPING_DIRECTION { MMALOMX_PARAM_MAPPING_TO_MMAL, MMALOMX_PARAM_MAPPING_TO_OMX }
enum MMALOMX_PARAM_TRANSLATION_TYPE_T { MMALOMX_PARAM_TRANSLATION_TYPE_NONE = 0, MMALOMX_PARAM_TRANSLATION_TYPE_SIMPLE, MMALOMX_PARAM_TRANSLATION_TYPE_CUSTOM, MMALOMX_PARAM_TRANSLATION_TYPE_DIRECT }
Functions
const char * mmalomx_parameter_name_omx (uint32_t id)
const char * mmalomx_parameter_name_mmal (uint32_t id)
const MMALOMX_PARAM_TRANSLATION_T * mmalomx_find_parameter_from_omx_id (uint32_t id)
const MMALOMX_PARAM_TRANSLATION_T * mmalomx_find_parameter_from_mmal_id (uint32_t id)
const MMALOMX_PARAM_TRANSLATION_T * mmalomx_find_parameter_enum (unsigned int index)
Detailed Description
OpenMAX IL adaptation layer for MMAL - Parameters related functions
Definition in file mmalomx_util_params.h.
Typedef Documentation
MMALOMX_PARAM_ENUM_TRANSLATE_T
typedef struct MMALOMX_PARAM_ENUM_TRANSLATE_T MMALOMX_PARAM_ENUM_TRANSLATE_T
MMALOMX_PARAM_OMX_HEADER_PORTLESS_T
typedef struct MMALOMX_PARAM_OMX_HEADER_PORTLESS_T MMALOMX_PARAM_OMX_HEADER_PORTLESS_T
The structure that all OMX parameters without a port start with
MMALOMX_PARAM_OMX_HEADER_T
typedef struct MMALOMX_PARAM_OMX_HEADER_T MMALOMX_PARAM_OMX_HEADER_T
The structure that all OMX parameters containing a port start with
MMALOMX_PARAM_TRANSLATION_T
typedef struct MMALOMX_PARAM_TRANSLATION_T MMALOMX_PARAM_TRANSLATION_T
MMAL <-> OMX parameter translation information
MMALOMX_PARAM_TRANSLATION_TYPE_T
typedef enum MMALOMX_PARAM_TRANSLATION_TYPE_T MMALOMX_PARAM_TRANSLATION_TYPE_T
Enumeration Type Documentation
MMALOMX_PARAM_MAPPING_DIRECTION
enum MMALOMX_PARAM_MAPPING_DIRECTION
Enumerator
MMALOMX_PARAM_MAPPING_TO_MMAL
MMALOMX_PARAM_MAPPING_TO_OMX
Definition at line 54 of file mmalomx_util_params.h.
              {
    MMALOMX_PARAM_MAPPING_TO_MMAL,
    MMALOMX_PARAM_MAPPING_TO_OMX
 } MMALOMX_PARAM_MAPPING_DIRECTION;
MMALOMX_PARAM_TRANSLATION_TYPE_T
enum MMALOMX_PARAM_TRANSLATION_TYPE_T
Enumerator
MMALOMX_PARAM_TRANSLATION_TYPE_NONE
MMALOMX_PARAM_TRANSLATION_TYPE_SIMPLE
MMALOMX_PARAM_TRANSLATION_TYPE_CUSTOM
MMALOMX_PARAM_TRANSLATION_TYPE_DIRECT
Definition at line 64 of file mmalomx_util_params.h.
{
    MMALOMX_PARAM_TRANSLATION_TYPE_NONE = 0,
    MMALOMX_PARAM_TRANSLATION_TYPE_SIMPLE,
    MMALOMX_PARAM_TRANSLATION_TYPE_CUSTOM,
    MMALOMX_PARAM_TRANSLATION_TYPE_DIRECT,
 } MMALOMX_PARAM_TRANSLATION_TYPE_T;
Function Documentation
mmalomx_find_parameter_enum()
const MMALOMX_PARAM_TRANSLATION_T* mmalomx_find_parameter_enum (unsigned int index)
Definition at line 37 of file mmalomx_util_params.c.
References MMAL_COUNTOF, MMALOMX_PARAM_TRANSLATION_T::mmal_id, MMAL_PARAMETER_UNUSED, and NULL.
Referenced by mmalomx_parameter_extension_index_get().
 {
    unsigned int i, j;
    for (i = 0; i < MMAL_COUNTOF(mmalomx_param_list); i++)
    {
       for (j = 0; mmalomx_param_list[i][j].mmal_id != MMAL_PARAMETER_UNUSED; j++)
       {
          if (!index--)
             break;
       }
       if (mmalomx_param_list[i][j].mmal_id != MMAL_PARAMETER_UNUSED)
          break;
    }
    return i < MMAL_COUNTOF(mmalomx_param_list) ? &mmalomx_param_list[i][j] : NULL;
 }
mmalomx_find_parameter_from_mmal_id()
const MMALOMX_PARAM_TRANSLATION_T* mmalomx_find_parameter_from_mmal_id (uint32_t id)
Definition at line 73 of file mmalomx_util_params.c.
References MMAL_COUNTOF, MMALOMX_PARAM_TRANSLATION_T::mmal_id, MMAL_PARAMETER_UNUSED, and NULL.
Referenced by mmalomx_parameter_name_mmal().
 {
    unsigned int i, j;
    for (i = 0; i < MMAL_COUNTOF(mmalomx_param_list); i++)
    {
       for (j = 0; mmalomx_param_list[i][j].mmal_id != MMAL_PARAMETER_UNUSED; j++)
       {
          if (mmalomx_param_list[i][j].mmal_id == id)
             break;
       }
       if (mmalomx_param_list[i][j].mmal_id != MMAL_PARAMETER_UNUSED)
          break;
    }
    return i < MMAL_COUNTOF(mmalomx_param_list) ? &mmalomx_param_list[i][j] : NULL;
 }
mmalomx_find_parameter_from_omx_id()
const MMALOMX_PARAM_TRANSLATION_T* mmalomx_find_parameter_from_omx_id (uint32_t id)
Definition at line 55 of file mmalomx_util_params.c.
References MMAL_COUNTOF, MMALOMX_PARAM_TRANSLATION_T::mmal_id, MMAL_PARAMETER_UNUSED, and NULL.
Referenced by mmalomx_parameter_name_omx().
 {
    unsigned int i, j;
    for (i = 0; i < MMAL_COUNTOF(mmalomx_param_list); i++)
    {
       for (j = 0; mmalomx_param_list[i][j].mmal_id != MMAL_PARAMETER_UNUSED; j++)
       {
          if (mmalomx_param_list[i][j].omx_id == id)
             break;
       }
       if (mmalomx_param_list[i][j].mmal_id != MMAL_PARAMETER_UNUSED)
          break;
    }
    return i < MMAL_COUNTOF(mmalomx_param_list) ? &mmalomx_param_list[i][j] : NULL;
 }
mmalomx_parameter_name_mmal()
const char* mmalomx_parameter_name_mmal (uint32_t id)
Definition at line 97 of file mmalomx_util_params.c.
References MMALOMX_PARAM_TRANSLATION_T::mmal_name, and mmalomx_find_parameter_from_mmal_id().
 {
    const MMALOMX_PARAM_TRANSLATION_T *xlat = mmalomx_find_parameter_from_mmal_id(id);
    return xlat ? xlat->mmal_name : 0;
 }
mmalomx_parameter_name_omx()
const char* mmalomx_parameter_name_omx (uint32_t id)
Definition at line 91 of file mmalomx_util_params.c.
References mmalomx_find_parameter_from_omx_id(), and MMALOMX_PARAM_TRANSLATION_T::omx_name.
Referenced by mmalomx_param_to_string().
 {
    const MMALOMX_PARAM_TRANSLATION_T *xlat = mmalomx_find_parameter_from_omx_id(id);
    return xlat ? xlat->omx_name : 0;
 }