VideoCore Library: interface/vcos/pthreads/vcos_pthreads.c File Reference
vcos_pthreads.c File Reference
#include "interface/vcos/vcos.h"
#include "interface/vcos/vcos_msgqueue.h"
#include <string.h>
#include <stdarg.h>
#include <stdlib.h>
#include <stdio.h>
#include <sys/time.h>
#include <linux/param.h>
Macros
#define VCOS_DEFAULT_STACK_SIZE 4096
#define NSEC_IN_SEC (1000*1000*1000)
#define MSEC_IN_SEC (1000)
#define NSEC_IN_MSEC (1000*1000)
Typedefs
typedef void(* LEGACY_ENTRY_FN_T) (int, void *)
Enumerations
enum {
VCOS_INIT_NAMED_SEM = (1 << 0), VCOS_INIT_PRINTF_LOCK = (1 << 1), VCOS_INIT_MAIN_SEM = (1 << 2), VCOS_INIT_MSGQ = (1 << 3),
VCOS_INIT_ALL = 0xffffffff
}
Functions
VCOS_STATUS_T vcos_thread_create (VCOS_THREAD_T *thread, const char *name, VCOS_THREAD_ATTR_T *attrs, VCOS_THREAD_ENTRY_FN_T entry, void *arg)
void vcos_thread_join (VCOS_THREAD_T *thread, void **pData)
VCOSPRE_ VCOS_STATUS_T VCOSPOST_ vcos_thread_create_classic (VCOS_THREAD_T *thread, const char *name, void *(*entry)(void *arg), void *arg, void *stack, VCOS_UNSIGNED stacksz, VCOS_UNSIGNED priaff, VCOS_UNSIGNED timeslice, VCOS_UNSIGNED autostart)
Create a thread using an API similar to the one "traditionally" used under Nucleus.
uint64_t vcos_getmicrosecs64_internal (void)
void vcos_vlog_default_impl (const VCOS_LOG_CAT_T *cat, VCOS_LOG_LEVEL_T _level, const char *fmt, va_list args)
void _vcos_log_platform_init (void)
VCOS_STATUS_T vcos_platform_init (void)
void vcos_platform_deinit (void)
void vcos_global_lock (void)
void vcos_global_unlock (void)
void vcos_thread_exit (void *arg)
void vcos_thread_attr_init (VCOS_THREAD_ATTR_T *attrs)
VCOS_STATUS_T vcos_pthreads_map_error (int error)
VCOS_STATUS_T vcos_pthreads_map_errno (void)
void _vcos_task_timer_set (void(*pfn)(void *), void *cxt, VCOS_UNSIGNED ms)
void _vcos_task_timer_cancel (void)
int vcos_vsnprintf (char *buf, size_t buflen, const char *fmt, va_list ap)
int vcos_snprintf (char *buf, size_t buflen, const char *fmt,...)
int vcos_have_rtos (void)
const char * vcos_thread_get_name (const VCOS_THREAD_T *thread)
void vcos_pthreads_logging_assert (const char *file, const char *func, unsigned int line, const char *fmt,...)
VCOS_STATUS_T vcos_thread_at_exit (void(*pfn)(void *), void *cxt)
void vcos_set_args (int argc, const char **argv)
int vcos_get_argc (void)
const char ** vcos_get_argv (void)
uint32_t _vcos_get_ticks_per_second (void)
VCOS_STATUS_T vcos_once (VCOS_ONCE_T *once_control, void(*init_routine)(void))
VCOS_THREAD_T * vcos_dummy_thread_create (void)
VCOS_STATUS_T vcos_timer_init (void)
VCOS_STATUS_T vcos_pthreads_timer_create (VCOS_TIMER_T *timer, const char *name, void(*expiration_routine)(void *context), void *context)
void vcos_pthreads_timer_set (VCOS_TIMER_T *timer, VCOS_UNSIGNED delay_ms)
void vcos_pthreads_timer_cancel (VCOS_TIMER_T *timer)
void vcos_pthreads_timer_delete (VCOS_TIMER_T *timer)
Variables
pthread_key_t _vcos_thread_current_key
int vcos_use_android_log = 0
int vcos_log_to_file = 0
Macro Definition Documentation
MSEC_IN_SEC
#define MSEC_IN_SEC (1000)
Definition at line 678 of file vcos_pthreads.c.
Referenced by vcos_pthreads_timer_set().
NSEC_IN_MSEC
#define NSEC_IN_MSEC (1000*1000)
Definition at line 679 of file vcos_pthreads.c.
Referenced by vcos_pthreads_timer_set().
NSEC_IN_SEC
#define NSEC_IN_SEC (1000*1000*1000)
Definition at line 677 of file vcos_pthreads.c.
VCOS_DEFAULT_STACK_SIZE
#define VCOS_DEFAULT_STACK_SIZE 4096
Definition at line 59 of file vcos_pthreads.c.
Typedef Documentation
LEGACY_ENTRY_FN_T
typedef void(* LEGACY_ENTRY_FN_T) (int, void *)
Definition at line 65 of file vcos_pthreads.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
VCOS_INIT_NAMED_SEM
VCOS_INIT_PRINTF_LOCK
VCOS_INIT_MAIN_SEM
VCOS_INIT_MSGQ
VCOS_INIT_ALL
Definition at line 338 of file vcos_pthreads.c.
 {
    VCOS_INIT_NAMED_SEM   = (1 << 0),
    VCOS_INIT_PRINTF_LOCK = (1 << 1),
    VCOS_INIT_MAIN_SEM    = (1 << 2),
    VCOS_INIT_MSGQ        = (1 << 3),
    VCOS_INIT_ALL         = 0xffffffff
 };
Function Documentation
_vcos_get_ticks_per_second()
uint32_t _vcos_get_ticks_per_second (void)
Definition at line 604 of file vcos_pthreads.c.
 {
    return HZ;
 }
_vcos_log_platform_init()
void _vcos_log_platform_init (void)
Definition at line 321 of file vcos_pthreads.c.
References vcos_process_id_current().
 {
    if(vcos_log_to_file)
    {
       char log_fname[100];
 #ifdef ANDROID
       snprintf(log_fname, 100, "/data/log/vcos_log%u.txt", vcos_process_id_current());
 #else
       snprintf(log_fname, 100, "/var/log/vcos_log%u.txt", vcos_process_id_current());
 #endif
       log_fhandle = fopen(log_fname, "w");
    }
    else
       log_fhandle = stderr;
 }
_vcos_task_timer_cancel()
void _vcos_task_timer_cancel (void)
Definition at line 506 of file vcos_pthreads.c.
References NULL, VCOS_THREAD_T::orig_task_timer_expiration_routine, VCOS_THREAD_T::task_timer, VCOS_THREAD_T::task_timer_created, vcos_thread_current(), and vcos_timer_cancel().
 {
    VCOS_THREAD_T *thread = vcos_thread_current();
    if (thread == NULL || !thread->task_timer_created)
      return;
    vcos_timer_cancel(&thread->task_timer);
    thread->orig_task_timer_expiration_routine = NULL;
 }
_vcos_task_timer_set()
void _vcos_task_timer_set (void(*)(void *) pfn, void * cxt, VCOS_UNSIGNED ms)
Definition at line 482 of file vcos_pthreads.c.
References NULL, VCOS_THREAD_T::orig_task_timer_expiration_routine, VCOS_THREAD_T::task_timer, VCOS_THREAD_T::task_timer_created, vcos_assert, vcos_thread_current(), and vcos_timer_create().
Referenced by vcos_generic_event_flags_get().
 {
    VCOS_THREAD_T *thread = vcos_thread_current();
    if (thread == NULL)
       return;
    vcos_assert(thread->orig_task_timer_expiration_routine == NULL);
    if (!thread->task_timer_created)
    {
       VCOS_STATUS_T st = vcos_timer_create(&thread->task_timer, NULL,
                                 _task_timer_expiration_routine, thread);
       (void)st;
       vcos_assert(st == VCOS_SUCCESS);
       thread->task_timer_created = 1;
    }
    thread->orig_task_timer_expiration_routine = pfn;
    thread->orig_task_timer_context = cxt;
    vcos_timer_set(&thread->task_timer, ms);
 }
vcos_dummy_thread_create()
VCOS_THREAD_T* vcos_dummy_thread_create (void)
Definition at line 631 of file vcos_pthreads.c.
References VCOS_THREAD_T::dummy, NULL, VCOS_THREAD_T::suspend, VCOS_THREAD_T::thread, vcos_assert, vcos_free(), vcos_malloc(), vcos_once(), vcos_semaphore_create(), and VCOS_SUCCESS.
 {
    VCOS_STATUS_T st;
    VCOS_THREAD_T *thread_hndl = NULL;
    int rc;
    thread_hndl = (VCOS_THREAD_T *)vcos_malloc(sizeof(VCOS_THREAD_T), NULL);
    vcos_assert(thread_hndl != NULL);
    memset(thread_hndl, 0, sizeof(VCOS_THREAD_T));
    thread_hndl->dummy = 1;
    thread_hndl->thread = pthread_self();
    st = vcos_semaphore_create(&thread_hndl->suspend, NULL, 0);
    if (st != VCOS_SUCCESS)
    {
       vcos_free(thread_hndl);
       return( thread_hndl );
    }
    vcos_once(&current_thread_key_once, current_thread_key_init);
    rc = pthread_setspecific(_vcos_thread_current_key,
                             thread_hndl);
    (void)rc;
    return( thread_hndl );
 }
vcos_get_argc()
int vcos_get_argc (void)
Return argc.
Definition at line 590 of file vcos_pthreads.c.
 {
    return vcos_argc;
 }
vcos_get_argv()
const char** vcos_get_argv (void)
Return argv.
Definition at line 595 of file vcos_pthreads.c.
 {
    return vcos_argv;
 }
vcos_getmicrosecs64_internal()
uint64_t vcos_getmicrosecs64_internal (void)
Definition at line 260 of file vcos_pthreads.c.
References NULL, vcos_log_to_file, and vcos_use_android_log.
 {
    struct timeval tv;
    uint64_t tm = 0;
    if (!gettimeofday(&tv, NULL))
    {
       tm = (tv.tv_sec * 1000000LL) + tv.tv_usec;
    }
    return tm;
 }
vcos_global_lock()
void vcos_global_lock (void)
Acquire global lock. This must be available independent of vcos_init()/vcos_deinit().
Definition at line 431 of file vcos_pthreads.c.
Referenced by vcos_deinit(), and vcos_init().
 {
    pthread_mutex_lock(&lock);
 }
vcos_global_unlock()
void vcos_global_unlock (void)
Release global lock. This must be available independent of vcos_init()/vcos_deinit().
Definition at line 436 of file vcos_pthreads.c.
 {
    pthread_mutex_unlock(&lock);
 }
vcos_have_rtos()
int vcos_have_rtos (void)
Report whether or not we have an RTOS at all, and hence the ability to create threads.
Definition at line 532 of file vcos_pthreads.c.
 {
    return 1;
 }
vcos_once()
VCOS_STATUS_T vcos_once (VCOS_ONCE_T * once_control, void(*)(void) init_routine)
Definition at line 609 of file vcos_pthreads.c.
References vcos_assert, VCOS_EACCESS, VCOS_EINVAL, and VCOS_SUCCESS.
Referenced by mmal_vc_init_fd(), mmal_vc_shm_init(), OMX_Init(), vc_gpuserv_init(), vcos_cmd_execute(), vcos_cmd_register(), vcos_dummy_thread_create(), vcos_platform_init(), vcsm_init_ex(), wfc_client_ipc_deinit(), wfc_client_ipc_init(), and wfcCreateDevice().
 {
    int rc = pthread_once(once_control, init_routine);
    if (rc != 0)
    {
       switch (errno)
       {
       case EINVAL:
          return VCOS_EINVAL;
       default:
          vcos_assert(0);
          return VCOS_EACCESS;
       }
    }
    else
    {
       return VCOS_SUCCESS;
    }
 }
vcos_platform_deinit()
void vcos_platform_deinit (void)
Platform-specific de-initialisation. VCOS internal function, not part of public API, do not call from outside vcos. See vcos_platform_init() re reference counting. This function is called with vcos_global_lock held.
Definition at line 426 of file vcos_pthreads.c.
 {
    vcos_term(VCOS_INIT_ALL);
 }
vcos_platform_init()
VCOS_STATUS_T vcos_platform_init (void)
Platform-specific initialisation. VCOS internal function, not part of public API, do not call from outside vcos. vcos_init()/vcos_deinit() reference count calls, so this function is only called from an uninitialized state, i.e. there will not be two consecutive calls to vcos_platform_init() without an intervening call to vcos_platform_deinit(). This function is called with vcos_global_lock held.
Returns
Status of initialisation.
Definition at line 364 of file vcos_pthreads.c.
References _vcos_named_semaphore_init(), VCOS_INIT_NAMED_SEM, VCOS_INIT_PRINTF_LOCK, vcos_mutex_create(), vcos_once(), VCOS_SUCCESS, and vcos_verify.
 {
    VCOS_STATUS_T st;
    uint32_t flags = 0;
    int pst;
    st = _vcos_named_semaphore_init();
    if (!vcos_verify(st == VCOS_SUCCESS))
       goto end;
    flags |= VCOS_INIT_NAMED_SEM;
 #ifdef HAVE_MTRACE
    /* enable glibc memory debugging, if the environment
     * variable MALLOC_TRACE names a valid file.
     */
    mtrace();
 #endif
 #ifdef ANDROID
    st = vcos_mutex_create(&printf_lock, "printf");
    if (!vcos_verify(st == VCOS_SUCCESS))
       goto end;
    flags |= VCOS_INIT_PRINTF_LOCK;
 #endif
    st = vcos_once(&current_thread_key_once, current_thread_key_init);
    if (!vcos_verify(st == VCOS_SUCCESS))
       goto end;
    /* Initialise a VCOS wrapper for the thread which called vcos_init. */
    st = vcos_semaphore_create(&vcos_thread_main.suspend, NULL, 0);
    if (!vcos_verify(st == VCOS_SUCCESS))
       goto end;
    flags |= VCOS_INIT_MAIN_SEM;
    vcos_thread_main.thread = pthread_self();
    pst = pthread_setspecific(_vcos_thread_current_key, &vcos_thread_main);
    if (!vcos_verify(pst == 0))
    {
       st = VCOS_EINVAL;
       goto end;
    }
    st = vcos_msgq_init();
    if (!vcos_verify(st == VCOS_SUCCESS))
       goto end;
    flags |= VCOS_INIT_MSGQ;
    vcos_logging_init();
 end:
    if (st != VCOS_SUCCESS)
       vcos_term(flags);
    return st;
 }
vcos_pthreads_logging_assert()
void vcos_pthreads_logging_assert (const char * file, const char * func, unsigned int line, const char * fmt, ...)
Definition at line 546 of file vcos_pthreads.c.
References vcos_backtrace_self().
 {
    va_list ap;
    va_start(ap, fmt);
    fprintf(stderr, "assertion failure:%s:%d:%s():",
            file, line, func);
    vfprintf(stderr, fmt, ap);
    va_end(ap);
    fprintf(stderr, "\n");
 #ifdef VCOS_HAVE_BACKTRACK
    if (vcos_backtrace_self)
       vcos_backtrace_self();
 #endif
    abort();
 }
vcos_pthreads_map_errno()
VCOS_STATUS_T vcos_pthreads_map_errno (void)
Definition at line 477 of file vcos_pthreads.c.
References vcos_pthreads_map_error().
 {
    return vcos_pthreads_map_error(errno);
 }
vcos_pthreads_map_error()
VCOS_STATUS_T vcos_pthreads_map_error (int error)
Convert errno values into the values recognized by vcos
Definition at line 460 of file vcos_pthreads.c.
References VCOS_EAGAIN, VCOS_EINVAL, VCOS_ENOMEM, VCOS_ENOSPC, and VCOS_ENXIO.
Referenced by vcos_pthreads_map_errno().
 {
    switch (error)
    {
    case ENOMEM:
       return VCOS_ENOMEM;
    case ENXIO:
       return VCOS_ENXIO;
    case EAGAIN:
       return VCOS_EAGAIN;
    case ENOSPC:
       return VCOS_ENOSPC;
    default:
       return VCOS_EINVAL;
    }
 }
vcos_pthreads_timer_cancel()
void vcos_pthreads_timer_cancel (VCOS_TIMER_T * timer)
Definition at line 857 of file vcos_pthreads.c.
References VCOS_TIMER_T::lock, and vcos_assert.
 {
    vcos_assert(timer);
    pthread_mutex_lock(&timer->lock);
    _timespec_set_zero(&timer->expires);
    pthread_cond_signal(&timer->settings_changed);
    pthread_mutex_unlock(&timer->lock);
 }
vcos_pthreads_timer_create()
VCOS_STATUS_T vcos_pthreads_timer_create (VCOS_TIMER_T * timer, const char * name, void(*)(void *context) expiration_routine, void * context)
Definition at line 747 of file vcos_pthreads.c.
 {
    pthread_mutexattr_t lock_attr;
    VCOS_STATUS_T result = VCOS_SUCCESS;
    int settings_changed_initialized = 0;
    int lock_attr_initialized = 0;
    int lock_initialized = 0;
    (void)name;
    vcos_assert(timer);
    vcos_assert(expiration_routine);
    memset(timer, 0, sizeof(VCOS_TIMER_T));
    timer->orig_expiration_routine = expiration_routine;
    timer->orig_context = context;
    /* Create conditional variable for notifying the timer's thread
     * when settings change.
     */
    if (result == VCOS_SUCCESS)
    {
       int rc = pthread_cond_init(&timer->settings_changed, NULL);
       if (rc == 0)
          settings_changed_initialized = 1;
       else
          result = vcos_pthreads_map_error(rc);
    }
    /* Create attributes for the lock (we want it to be recursive) */
    if (result == VCOS_SUCCESS)
    {
       int rc = pthread_mutexattr_init(&lock_attr);
       if (rc == 0)
       {
          pthread_mutexattr_settype(&lock_attr, PTHREAD_MUTEX_RECURSIVE);
          lock_attr_initialized = 1;
       }
       else
       {
          result = vcos_pthreads_map_error(rc);
       }
    }
    /* Create lock for the timer structure */
    if (result == VCOS_SUCCESS)
    {
       int rc = pthread_mutex_init(&timer->lock, &lock_attr);
       if (rc == 0)
          lock_initialized = 1;
       else
          result = vcos_pthreads_map_error(rc);
    }
    /* Lock attributes are no longer needed */
    if (lock_attr_initialized)
       pthread_mutexattr_destroy(&lock_attr);
    /* Create the underlying thread */
    if (result == VCOS_SUCCESS)
    {
       int rc = pthread_create(&timer->thread, NULL, _timer_thread, timer);
       if (rc != 0)
          result = vcos_pthreads_map_error(rc);
    }
    /* Clean up if anything went wrong */
    if (result != VCOS_SUCCESS)
    {
       if (lock_initialized)
          pthread_mutex_destroy(&timer->lock);
       if (settings_changed_initialized)
          pthread_cond_destroy(&timer->settings_changed);
    }
    return result;
 }
vcos_pthreads_timer_delete()
void vcos_pthreads_timer_delete (VCOS_TIMER_T * timer)
Definition at line 869 of file vcos_pthreads.c.
References VCOS_TIMER_T::lock, VCOS_TIMER_T::thread, and vcos_assert.
 {
    vcos_assert(timer);
    pthread_mutex_lock(&timer->lock);
    /* Other implementation of this function (e.g. ThreadX)
     * disallow it being called from the expiration routine
     */
    vcos_assert(pthread_self() != timer->thread);
    /* Stop the timer and set flag telling the timer thread to quit */
    _timespec_set_zero(&timer->expires);
    timer->quit = 1;
    /* Notify the timer's thread about the change */
    pthread_cond_signal(&timer->settings_changed);
    /* Release the lock, so that the timer's thread can quit */
    pthread_mutex_unlock(&timer->lock);
    /* Wait for the timer thread to finish */
    pthread_join(timer->thread, NULL);
    /* Free resources used by the timer */
    pthread_mutex_destroy(&timer->lock);
    pthread_cond_destroy(&timer->settings_changed);
 }
vcos_pthreads_timer_set()
void vcos_pthreads_timer_set (VCOS_TIMER_T * timer, VCOS_UNSIGNED delay_ms)
Definition at line 830 of file vcos_pthreads.c.
References VCOS_TIMER_T::expires, VCOS_TIMER_T::lock, MSEC_IN_SEC, NSEC_IN_MSEC, and vcos_assert.
 {
    struct timespec now;
    vcos_assert(timer);
    /* Other implementations of this function do undefined things
     * when delay_ms is 0. This implementation will simply assert and return
     */
    vcos_assert(delay_ms != 0);
    if (delay_ms == 0)
       return;
    pthread_mutex_lock(&timer->lock);
    /* Calculate the new absolute expiry time */
    clock_gettime(CLOCK_REALTIME, &now);
    timer->expires.tv_sec = delay_ms / MSEC_IN_SEC;
    timer->expires.tv_nsec = (delay_ms % MSEC_IN_SEC) * NSEC_IN_MSEC;
    _timespec_add(&timer->expires, &now);
    /* Notify the timer's thread about the change */
    pthread_cond_signal(&timer->settings_changed);
    pthread_mutex_unlock(&timer->lock);
 }
vcos_set_args()
void vcos_set_args (int argc, const char ** argv)
Pass in the argv/argc arguments passed to main()
Definition at line 584 of file vcos_pthreads.c.
 {
    vcos_argc = argc;
    vcos_argv = argv;
 }
vcos_snprintf()
int vcos_snprintf (char * buf, size_t buflen, const char * fmt, ...)
Definition at line 522 of file vcos_pthreads.c.
Referenced by mmal_connection_create(), and vcos_log_dump_mem_impl().
 {
    int ret;
    va_list ap;
    va_start(ap,fmt);
    ret = vsnprintf(buf, buflen, fmt, ap);
    va_end(ap);
    return ret;
 }
vcos_thread_at_exit()
VCOS_STATUS_T vcos_thread_at_exit (void(*)(void *) pfn, void * cxt)
Register a function to be called when the current thread exits.
Definition at line 563 of file vcos_pthreads.c.
References NULL, vcos_assert, VCOS_EINVAL, VCOS_ENOSPC, VCOS_MAX_EXIT_HANDLERS, VCOS_SUCCESS, and vcos_thread_current().
 {
    int i;
    VCOS_THREAD_T *self = vcos_thread_current();
    if (!self)
    {
       vcos_assert(0);
       return VCOS_EINVAL;
    }
    for (i=0; i<VCOS_MAX_EXIT_HANDLERS; i++)
    {
       if (self->at_exit[i].pfn == NULL)
       {
          self->at_exit[i].pfn = pfn;
          self->at_exit[i].cxt = cxt;
          return VCOS_SUCCESS;
       }
    }
    return VCOS_ENOSPC;
 }
vcos_thread_attr_init()
void vcos_thread_attr_init (VCOS_THREAD_ATTR_T * attrs)
Initialize thread attribute struct. This call does not allocate memory, and so cannot fail.
Definition at line 455 of file vcos_pthreads.c.
Referenced by mmal_component_action_register(), and vcos_thread_create_classic().
 {
    *attrs = default_attrs;
 }
vcos_thread_create()
VCOS_STATUS_T vcos_thread_create (VCOS_THREAD_T * thread, const char * name, VCOS_THREAD_ATTR_T * attrs, VCOS_THREAD_ENTRY_FN_T entry, void * arg)
Create a thread. It must be cleaned up by calling vcos_thread_join().
Parameters
thread Filled in on return with thread
name A name for the thread. May be the empty string.
attrs Attributes; default attributes will be used if this is NULL.
entry Entry point.
arg Argument passed to the entry point.
Definition at line 165 of file vcos_pthreads.c.
Referenced by mmal_component_action_register(), mmal_graph_enable(), raspitex_start(), and vcos_thread_create_classic().
 {
    VCOS_STATUS_T st;
    pthread_attr_t pt_attrs;
    VCOS_THREAD_ATTR_T *local_attrs = attrs ? attrs : &default_attrs;
    int rc;
    vcos_assert(thread);
    memset(thread, 0, sizeof(VCOS_THREAD_T));
    rc = pthread_attr_init(&pt_attrs);
    if (rc < 0)
       return VCOS_ENOMEM;
    st = vcos_semaphore_create(&thread->suspend, NULL, 0);
    if (st != VCOS_SUCCESS)
    {
       pthread_attr_destroy(&pt_attrs);
       return st;
    }
    pthread_attr_setstacksize(&pt_attrs, local_attrs->ta_stacksz);
 #if VCOS_CAN_SET_STACK_ADDR
    if (local_attrs->ta_stackaddr)
    {
       pthread_attr_setstackaddr(&pt_attrs, local_attrs->ta_stackaddr);
    }
 #else
    vcos_demand(local_attrs->ta_stackaddr == 0);
 #endif
    /* pthread_attr_setpriority(&pt_attrs, local_attrs->ta_priority); */
    vcos_assert(local_attrs->ta_stackaddr == 0); /* Not possible */
    thread->entry = entry;
    thread->arg = arg;
    thread->legacy = local_attrs->legacy;
    strncpy(thread->name, name, sizeof(thread->name));
    thread->name[sizeof(thread->name)-1] = '\0';
    memset(thread->at_exit, 0, sizeof(thread->at_exit));
    rc = pthread_create(&thread->thread, &pt_attrs, vcos_thread_entry, thread);
    pthread_attr_destroy(&pt_attrs);
    if (rc < 0)
    {
       vcos_semaphore_delete(&thread->suspend);
       return VCOS_ENOMEM;
    }
    else
    {
       return VCOS_SUCCESS;
    }
 }
vcos_thread_create_classic()
VCOSPRE_ VCOS_STATUS_T VCOSPOST_ vcos_thread_create_classic (VCOS_THREAD_T * thread, const char * name, void *(*)(void *arg) entry, void * arg, void * stack, VCOS_UNSIGNED stacksz, VCOS_UNSIGNED priaff, VCOS_UNSIGNED timeslice, VCOS_UNSIGNED autostart)
Create a thread using an API similar to the one "traditionally" used under Nucleus.
This creates a thread which must be cleaned up by calling vcos_thread_join(). The thread cannot be simply terminated (as in Nucleus and ThreadX) as thread termination is not universally supported.
Parameters
thread Filled in with thread instance
name An optional name for the thread. NULL or "" may be used (but a name will aid in debugging).
entry Entry point
arg A single argument passed to the entry point function
stack Pointer to stack address
stacksz Size of stack in bytes
priaff Priority of task, between VCOS_PRI_LOW and VCOS_PRI_HIGH, ORed with the CPU affinity
autostart If non-zero the thread will start immediately.
timeslice Timeslice (system ticks) for this thread.
See also
vcos_thread_terminate vcos_thread_delete
Definition at line 234 of file vcos_pthreads.c.
References _VCOS_AFFINITY_MASK, VCOS_CAN_SET_STACK_ADDR, vcos_thread_attr_init(), vcos_thread_attr_setaffinity(), vcos_thread_attr_setpriority(), vcos_thread_attr_setstacksize(), vcos_thread_create(), and void().
 {
    VCOS_THREAD_ATTR_T attrs;
    vcos_thread_attr_init(&attrs);
    vcos_thread_attr_setstacksize(&attrs, stacksz);
    vcos_thread_attr_setpriority(&attrs, priaff & ~_VCOS_AFFINITY_MASK);
    vcos_thread_attr_setaffinity(&attrs, priaff & _VCOS_AFFINITY_MASK);
    (void)timeslice;
    (void)autostart;
    if (VCOS_CAN_SET_STACK_ADDR)
    {
       vcos_thread_attr_setstack(&attrs, stack, stacksz);
    }
    return vcos_thread_create(thread, name, &attrs, entry, arg);
 }
vcos_thread_exit()
void vcos_thread_exit (void * data)
Exit the thread from within the thread function itself. Resources must still be cleaned up via a call to thread_join().
The thread can also be terminated by simply exiting the thread function.
Parameters
data Data passed to thread_join. May be NULL.
Definition at line 441 of file vcos_pthreads.c.
References VCOS_THREAD_T::dummy, NULL, vcos_free(), and vcos_thread_current().
 {
    VCOS_THREAD_T *thread = vcos_thread_current();
    if ( thread && thread->dummy )
    {
       vcos_free ( (void*) thread );
       thread = NULL;
    }
    pthread_exit(arg);
 }
vcos_thread_get_name()
const char* vcos_thread_get_name (const VCOS_THREAD_T * thread)
Return the name of the given thread.
Definition at line 537 of file vcos_pthreads.c.
References __attribute__(), VCOS_THREAD_T::name, and vcos_backtrace_self().
Referenced by vc_hostfs_init().
 {
    return thread->name;
 }
vcos_thread_join()
void vcos_thread_join (VCOS_THREAD_T * thread, void ** pData)
Wait for a thread to terminate and then clean up its resources.
Parameters
thread Thread to wait for
pData Updated to point at data provided in vcos_thread_exit or exit code of thread function.
Definition at line 227 of file vcos_pthreads.c.
References VCOS_THREAD_T::thread.
Referenced by mmal_component_action_deregister(), OMX_FreeHandle(), and raspitex_stop().
 {
    pthread_join(thread->thread, pData);
    vcos_thread_cleanup(thread);
 }
vcos_timer_init()
VCOS_STATUS_T vcos_timer_init (void)
Perform timer subsystem initialization. This function is not needed on non-Windows platforms but is still present so that it can be called. On Windows it is needed because vcos_init() gets called from DLL initialization where it is not possible to create a time queue (deadlock occurs if you try).
Returns
VCOS_SUCCESS on success. VCOS_EEXIST if this has already been called once. VCOS_ENOMEM if resource allocation failed.
Definition at line 742 of file vcos_pthreads.c.
References VCOS_SUCCESS.
 {
    return VCOS_SUCCESS;
 }
vcos_vlog_default_impl()
void vcos_vlog_default_impl (const VCOS_LOG_CAT_T * cat, VCOS_LOG_LEVEL_T _level, const char * fmt, va_list args)
Definition at line 294 of file vcos_pthreads.c.
References VCOS_LOG_CAT_T::flags, VCOS_LOG_CAT_T::name, NULL, vcos_mutex_lock(), vcos_mutex_unlock(), void(), and VCOS_LOG_CAT_T::want_prefix.
 {
    (void)_level;
 #ifdef ANDROID
    if ( vcos_use_android_log )
    {
       __android_log_vprint(log_prio[_level], cat->name, fmt, args);
    }
    else
    {
       vcos_mutex_lock(&printf_lock);
 #endif
       if(NULL != log_fhandle)
       {
          if (cat->flags.want_prefix)
             fprintf( log_fhandle, "%s: ", cat->name );
          vfprintf(log_fhandle, fmt, args);
          fputs("\n", log_fhandle);
          fflush(log_fhandle);
       }
 #ifdef ANDROID
       vcos_mutex_unlock(&printf_lock);
    }
 #endif
 }
vcos_vsnprintf()
int vcos_vsnprintf (char * buf, size_t buflen, const char * fmt, va_list ap)
Definition at line 517 of file vcos_pthreads.c.
Referenced by vcos_cmd_vprintf(), vcos_safe_sprintf(), and vcos_safe_vsprintf().
 {
    return vsnprintf( buf, buflen, fmt, ap );
 }
Variable Documentation
_vcos_thread_current_key
pthread_key_t _vcos_thread_current_key
Definition at line 81 of file vcos_pthreads.c.
vcos_log_to_file
int vcos_log_to_file = 0
Definition at line 289 of file vcos_pthreads.c.
Referenced by vcos_getmicrosecs64_internal().
vcos_use_android_log
int vcos_use_android_log = 0
Set to 1 by default when ANDROID is defined. Allows runtime switching for console apps.
Definition at line 288 of file vcos_pthreads.c.
Referenced by main(), and vcos_getmicrosecs64_internal().