VideoCore Library: interface/vcos/vcos_dlfcn.h File Reference
vcos_dlfcn.h File Reference
#include "interface/vcos/vcos_types.h"
#include "vcos.h"
Functions
VCOSPRE_ void *VCOSPOST_ vcos_dlopen (const char *name, int mode)
VCOSPRE_ int VCOSPOST_ vcos_dlclose (void *handle)
VCOSPRE_ int VCOSPOST_ vcos_dlerror (int *err, char *buf, size_t buflen)
Variables
VCOSPRE_ void VCOSPOST_(*)(void) vcos_dlsym (void *handle, const char *name)
Detailed Description
Loading dynamic libraries. See also dlfcn.h.
Definition in file vcos_dlfcn.h.
Function Documentation
vcos_dlclose()
VCOSPRE_ int VCOSPOST_ vcos_dlclose (void * handle)
Close a library
Parameters
handle Handle to close
Definition at line 43 of file vcos_dlfcn.c.
References dlclose().
 {
    return dlclose(handle);
 }
vcos_dlerror()
VCOSPRE_ int VCOSPOST_ vcos_dlerror (int * err, char * buf, size_t buflen)
Return error message from library.
Parameters
err On return, set to non-zero if an error has occurred
buf Buffer to write error to
len Size of buffer (including terminating NUL).
Definition at line 48 of file vcos_dlfcn.c.
References dlerror(), and vcos_assert.
 {
    /* not really threadsafe! */
    const char *errmsg = dlerror();
    vcos_assert(buflen > 0);
    if (errmsg)
    {
       *err = -1;
       strncpy(buf, errmsg, buflen);
       buf[buflen-1] = '\0';
    }
    else
    {
       *err = 0;
       buf[0] = '\0';
    }
    return 0;
 }
vcos_dlopen()
VCOSPRE_ void* VCOSPOST_ vcos_dlopen (const char * name, int mode)
Open a dynamic library.
Parameters
name name of the library
mode Load lazily or immediately (VCOS_DL_LAZY, VCOS_DL_NOW, VCOS_DL_LOCAL, VCOS_DL_GLOBAL).
Returns
A handle for use in subsequent calls.
Definition at line 33 of file vcos_dlfcn.c.
References dlopen().
 {
    return dlopen(name, mode);
 }
Variable Documentation
vcos_dlsym
VCOSPRE_ void VCOSPOST_(*)(void) vcos_dlsym(void *handle, const char *name)
Look up a symbol.
Parameters
handle Handle to open
name Name of function
Returns
Function pointer, or NULL.
Definition at line 64 of file vcos_dlfcn.h.