VideoCore Library: interface/khronos/common/khrn_int_generic_map.c File Reference
khrn_int_generic_map.c File Reference
#include "interface/khronos/common/khrn_client_platform.h"
#include "interface/khronos/common/khrn_int_generic_map.h"
#include "interface/khronos/common/khrn_int_util.h"
Macros
#define KHRN_GENERIC_MAP_CMP_VALUE(x, y) (x==y)
#define STRINGIZE2(X) #X
#define STRINGIZE(X) STRINGIZE2(X) /* X will be expanded here */
Functions
bool khrn_generic_map() init (KHRN_GENERIC_MAP(T) *map, uint32_t capacity)
void khrn_generic_map() term (KHRN_GENERIC_MAP(T) *map)
bool khrn_generic_map() insert (KHRN_GENERIC_MAP(T) *map, KHRN_GENERIC_MAP_KEY_T key, KHRN_GENERIC_MAP_VALUE_T value)
bool khrn_generic_map() delete (KHRN_GENERIC_MAP(T) *map, KHRN_GENERIC_MAP_KEY_T key)
uint32_t khrn_generic_map() get_count (KHRN_GENERIC_MAP(T) *map)
KHRN_GENERIC_MAP_VALUE_T khrn_generic_map() lookup (KHRN_GENERIC_MAP(T) *map, KHRN_GENERIC_MAP_KEY_T key)
void khrn_generic_map() iterate (KHRN_GENERIC_MAP(T) *map, KHRN_GENERIC_MAP(CALLBACK_T) func, void *data)
Macro Definition Documentation
KHRN_GENERIC_MAP_CMP_VALUE
#define KHRN_GENERIC_MAP_CMP_VALUE (x, y) (x==y)
Definition at line 33 of file khrn_int_generic_map.c.
Referenced by insert(), iterate(), and term().
STRINGIZE
#define STRINGIZE (X) STRINGIZE2(X) /* X will be expanded here */
STRINGIZE2
#define STRINGIZE2 (X) #X
Function Documentation
delete()
bool khrn_generic_map() delete (KHRN_GENERIC_MAP(T) * map, KHRN_GENERIC_MAP_KEY_T key)
Definition at line 275 of file khrn_int_generic_map.c.
References key, KHRN_GENERIC_MAP_RELOCATABLE, KHRN_GENERIC_MAP_VALUE_DELETED, mem_lock(), mem_unlock(), and vcos_assert.
 {
    KHRN_GENERIC_MAP(ENTRY_T) *entry = get_entry(
 #ifdef KHRN_GENERIC_MAP_RELOCATABLE
       (KHRN_GENERIC_MAP(ENTRY_T) *)mem_lock(map->storage),
 #else
       map->storage,
 #endif
       map->capacity, key);
    if (entry) {
 #ifdef KHRN_GENERIC_MAP_RELEASE_VALUE
       KHRN_GENERIC_MAP_RELEASE_VALUE(entry->value);
 #endif
       entry->value = KHRN_GENERIC_MAP_VALUE_DELETED;
       ++map->deletes;
       vcos_assert(map->entries > 0);
       --map->entries;
    }
 #ifdef KHRN_GENERIC_MAP_RELOCATABLE
    mem_unlock(map->storage);
 #endif
    return !!entry;
 }
get_count()
uint32_t khrn_generic_map() get_count (KHRN_GENERIC_MAP(T) * map)
Definition at line 299 of file khrn_int_generic_map.c.
 {
    return map->entries;
 }
init()
bool khrn_generic_map() init (KHRN_GENERIC_MAP(T) * map, uint32_t capacity)
Definition at line 112 of file khrn_int_generic_map.c.
References vcos_assert.
 {
 #ifdef KHRN_GENERIC_MAP_RELOCATABLE
    MEM_HANDLE_T handle;
 #else
    KHRN_GENERIC_MAP(ENTRY_T) *base;
    uint32_t i;
 #endif
    /*
       we need (capacity - 1) > (capacity / 2) and (capacity - 1) > ((3 * capacity) / 4)
       to ensure we always have at least 1 unused slot
       the smallest number that satisfies these constraints is 8 (7 > 4, 7 > 6)
    */
    vcos_assert(capacity >= 8);
    vcos_assert(is_power_of_2(capacity)); /* hash stuff assumes this */
    /*
       alloc and clear storage
    */
    #define STRINGIZE2(X) #X
    #define STRINGIZE(X) STRINGIZE2(X) /* X will be expanded here */
 #ifdef KHRN_GENERIC_MAP_RELOCATABLE
    handle = mem_alloc_ex(capacity * sizeof(KHRN_GENERIC_MAP(ENTRY_T)), alignof(KHRN_GENERIC_MAP(ENTRY_T)),
       MEM_FLAG_INIT, STRINGIZE(KHRN_GENERIC_MAP(T)) ".storage", MEM_COMPACT_DISCARD); /* no term (struct containing KHRN_GENERIC_MAP(T) must call khrn_generic_map(term)()) */
    if (handle == MEM_INVALID_HANDLE) {
       return false;
    }
    /* all values already initialised to KHRN_GENERIC_MAP_VALUE_NONE */
 #else
    base = (KHRN_GENERIC_MAP(ENTRY_T) *)KHRN_GENERIC_MAP_ALLOC(capacity * sizeof(KHRN_GENERIC_MAP(ENTRY_T)),
       STRINGIZE(KHRN_GENERIC_MAP(T)) ".storage");
    if (!base) {
       return false;
    }
    for (i = 0; i != capacity; ++i) {
       base[i].value = KHRN_GENERIC_MAP_VALUE_NONE;
    }
 #endif
    #undef STRINGIZE
    #undef STRINGIZE2
    /*
       fill in struct (do this only once we are sure to succeed --
       realloc_storage and khrn_generic_map(term) under gl object semantics rely
       on this behaviour)
    */
    map->entries = 0;
    map->deletes = 0;
 #ifdef KHRN_GENERIC_MAP_RELOCATABLE
    map->storage = handle;
 #else
    map->storage = base;
 #endif
    map->capacity = capacity;
    return true;
 }
insert()
bool khrn_generic_map() insert (KHRN_GENERIC_MAP(T) * map, KHRN_GENERIC_MAP_KEY_T key, KHRN_GENERIC_MAP_VALUE_T value)
Definition at line 212 of file khrn_int_generic_map.c.
References key, KHRN_GENERIC_MAP_CMP_VALUE, KHRN_GENERIC_MAP_RELOCATABLE, KHRN_GENERIC_MAP_VALUE_DELETED, KHRN_GENERIC_MAP_VALUE_NONE, mem_lock(), mem_unlock(), and vcos_assert.
 {
    uint32_t capacity = map->capacity;
    KHRN_GENERIC_MAP(ENTRY_T) *entry;
    vcos_assert(!KHRN_GENERIC_MAP_CMP_VALUE(value, KHRN_GENERIC_MAP_VALUE_DELETED));
    vcos_assert(!KHRN_GENERIC_MAP_CMP_VALUE(value, KHRN_GENERIC_MAP_VALUE_NONE));
    entry = get_entry(
 #ifdef KHRN_GENERIC_MAP_RELOCATABLE
       (KHRN_GENERIC_MAP(ENTRY_T) *)mem_lock(map->storage),
 #else
       map->storage,
 #endif
       capacity, key);
    if (entry) {
 #ifdef KHRN_GENERIC_MAP_ACQUIRE_VALUE
       KHRN_GENERIC_MAP_ACQUIRE_VALUE(value);
 #endif
 #ifdef KHRN_GENERIC_MAP_RELEASE_VALUE
       KHRN_GENERIC_MAP_RELEASE_VALUE(entry->value);
 #endif
       entry->value = value;
 #ifdef KHRN_GENERIC_MAP_RELOCATABLE
       mem_unlock(map->storage);
 #endif
    } else {
 #ifdef KHRN_GENERIC_MAP_RELOCATABLE
       mem_unlock(map->storage);
 #endif
       if (map->entries > (capacity / 2)) {
          capacity *= 2;
          if (!realloc_storage(map, capacity)) { return false; }
       } else if ((map->entries + map->deletes) > ((3 * capacity) / 4)) {
          if (!realloc_storage(map, capacity)) { return false; }
       }
 #ifdef KHRN_GENERIC_MAP_ACQUIRE_VALUE
       KHRN_GENERIC_MAP_ACQUIRE_VALUE(value);
 #endif
       entry = get_free_entry(
 #ifdef KHRN_GENERIC_MAP_RELOCATABLE
          (KHRN_GENERIC_MAP(ENTRY_T) *)mem_lock(map->storage),
 #else
          map->storage,
 #endif
          capacity, key);
       if (KHRN_GENERIC_MAP_CMP_VALUE(entry->value, KHRN_GENERIC_MAP_VALUE_DELETED)) {
          vcos_assert(map->deletes > 0);
          --map->deletes;
       }
       entry->key = key;
       entry->value = value;
       ++map->entries;
 #ifdef KHRN_GENERIC_MAP_RELOCATABLE
       mem_unlock(map->storage);
 #endif
    }
    return true;
 }
iterate()
void khrn_generic_map() iterate (KHRN_GENERIC_MAP(T) * map, KHRN_GENERIC_MAP(CALLBACK_T) func, void * data)
Definition at line 325 of file khrn_int_generic_map.c.
References func, key, KHRN_GENERIC_MAP_CMP_VALUE, KHRN_GENERIC_MAP_VALUE_DELETED, KHRN_GENERIC_MAP_VALUE_NONE, mem_lock(), and mem_unlock().
 {
 #ifdef KHRN_GENERIC_MAP_RELOCATABLE
    KHRN_GENERIC_MAP(ENTRY_T) *base = (KHRN_GENERIC_MAP(ENTRY_T) *)mem_lock(map->storage);
 #else
    KHRN_GENERIC_MAP(ENTRY_T) *base = map->storage;
 #endif
    uint32_t i;
    for (i = 0; i != map->capacity; ++i) {
       if ((!KHRN_GENERIC_MAP_CMP_VALUE(base[i].value, KHRN_GENERIC_MAP_VALUE_DELETED)) && (!KHRN_GENERIC_MAP_CMP_VALUE(base[i].value, KHRN_GENERIC_MAP_VALUE_NONE))) {
          func(map, base[i].key, base[i].value, data);
       }
    }
 #ifdef KHRN_GENERIC_MAP_RELOCATABLE
    mem_unlock(map->storage);
 #endif
 }
lookup()
KHRN_GENERIC_MAP_VALUE_T khrn_generic_map() lookup (KHRN_GENERIC_MAP(T) * map, KHRN_GENERIC_MAP_KEY_T key)
Definition at line 304 of file khrn_int_generic_map.c.
References key, khrn_generic_map, KHRN_GENERIC_MAP_KEY_T, KHRN_GENERIC_MAP_RELOCATABLE, KHRN_GENERIC_MAP_VALUE_NONE, KHRN_GENERIC_MAP_VALUE_T, mem_lock(), and mem_unlock().
Referenced by rtp_base64_decode().
 {
    KHRN_GENERIC_MAP_VALUE_T value = khrn_generic_map(lookup_locked)(map, key, mem_lock(map->storage));
    mem_unlock(map->storage);
    return value;
 }
 KHRN_GENERIC_MAP_VALUE_T khrn_generic_map(lookup_locked)(KHRN_GENERIC_MAP(T) *map, KHRN_GENERIC_MAP_KEY_T key, void *storage)
 #endif
 {
    KHRN_GENERIC_MAP(ENTRY_T) *entry = get_entry(
 #ifdef KHRN_GENERIC_MAP_RELOCATABLE
       (KHRN_GENERIC_MAP(ENTRY_T) *)storage,
 #else
       map->storage,
 #endif
       map->capacity, key);
    return entry ? entry->value : KHRN_GENERIC_MAP_VALUE_NONE;
 }
term()
void khrn_generic_map() term (KHRN_GENERIC_MAP(T) * map)
Definition at line 182 of file khrn_int_generic_map.c.
References KHRN_GENERIC_MAP_CMP_VALUE, KHRN_GENERIC_MAP_FREE, KHRN_GENERIC_MAP_VALUE_DELETED, KHRN_GENERIC_MAP_VALUE_NONE, MEM_INVALID_HANDLE, mem_lock(), mem_release(), and mem_unlock().
 {
 #ifdef KHRN_GENERIC_MAP_RELOCATABLE
    if (map->storage != MEM_INVALID_HANDLE) {
 #endif
 #ifdef KHRN_GENERIC_MAP_RELEASE_VALUE
 #ifdef KHRN_GENERIC_MAP_RELOCATABLE
       KHRN_GENERIC_MAP(ENTRY_T) *base = (KHRN_GENERIC_MAP(ENTRY_T) *)mem_lock(map->storage);
 #else
       KHRN_GENERIC_MAP(ENTRY_T) *base = map->storage;
 #endif
       uint32_t i;
       for (i = 0; i != map->capacity; ++i) {
          if ((!KHRN_GENERIC_MAP_CMP_VALUE(base[i].value, KHRN_GENERIC_MAP_VALUE_DELETED)) && (!KHRN_GENERIC_MAP_CMP_VALUE(base[i].value, KHRN_GENERIC_MAP_VALUE_NONE))) {
             KHRN_GENERIC_MAP_RELEASE_VALUE(base[i].value);
          }
       }
 #ifdef KHRN_GENERIC_MAP_RELOCATABLE
       mem_unlock(map->storage);
 #endif
 #endif
 #ifdef KHRN_GENERIC_MAP_RELOCATABLE
       mem_release(map->storage);
       map->storage = MEM_INVALID_HANDLE;
    }
 #else
    KHRN_GENERIC_MAP_FREE(map->storage);
 #endif
 }