VideoCore Library: interface/vcos/generic/vcos_logcat.c File Reference
vcos_logcat.c File Reference
#include "interface/vcos/vcos.h"
#include "interface/vcos/vcos_ctype.h"
#include "interface/vcos/vcos_string.h"
#include "interface/vcos/vcos_inttypes.h"
Macros
#define VCOS_LOG_CATEGORY (&dflt_log_category)
#define VCOS_WANT_LOG_CMD 0
Functions
void vcos_logging_init (void)
const char * vcos_log_level_to_string (VCOS_LOG_LEVEL_T level)
VCOS_STATUS_T vcos_string_to_log_level (const char *str, VCOS_LOG_LEVEL_T *level)
void vcos_log_register (const char *name, VCOS_LOG_CAT_T *category)
void vcos_log_unregister (VCOS_LOG_CAT_T *category)
VCOSPRE_ const VCOS_LOG_CAT_T *VCOSPOST_ vcos_log_get_default_category (void)
void vcos_set_log_options (const char *opt)
void vcos_log_dump_mem_impl (const VCOS_LOG_CAT_T *cat, const char *label, uint32_t addr, const void *voidMem, size_t numBytes)
void vcos_log_impl (const VCOS_LOG_CAT_T *cat, VCOS_LOG_LEVEL_T _level, const char *fmt,...)
void vcos_vlog_impl (const VCOS_LOG_CAT_T *cat, VCOS_LOG_LEVEL_T _level, const char *fmt, va_list args)
void vcos_set_vlog_impl (VCOS_VLOG_IMPL_FUNC_T vlog_impl_func)
Variables
VCOS_LOG_CAT_T * vcos_logging_categories = NULL
Macro Definition Documentation
VCOS_LOG_CATEGORY
#define VCOS_LOG_CATEGORY (&dflt_log_category)
Definition at line 41 of file vcos_logcat.c.
VCOS_WANT_LOG_CMD
#define VCOS_WANT_LOG_CMD 0
Definition at line 61 of file vcos_logcat.c.
Function Documentation
vcos_log_dump_mem_impl()
void vcos_log_dump_mem_impl (const VCOS_LOG_CAT_T * cat, const char * label, uint32_t addr, const void * voidMem, size_t numBytes)
Definition at line 488 of file vcos_logcat.c.
References mem, NULL, offset, vcos_log_impl(), VCOS_LOG_INFO, and vcos_snprintf().
Referenced by vcos_log_set_level().
 {
    const uint8_t  *mem = (const uint8_t *)voidMem;
    size_t          offset;
    char            lineBuf[ 100 ];
    char           *s;
    while ( numBytes > 0 )
    {
        s = lineBuf;
        for ( offset = 0; offset < 16; offset++ )
        {
            if ( offset < numBytes )
            {
                s += vcos_snprintf( s, 4, "%02x ", mem[ offset ]);
            }
            else
            {
                s += vcos_snprintf( s, 4, "   " );
            }
        }
        for ( offset = 0; offset < 16; offset++ )
        {
            if ( offset < numBytes )
            {
                uint8_t ch = mem[ offset ];
                if (( ch < ' ' ) || ( ch > '~' ))
                {
                    ch = '.';
                }
                *s++ = (char)ch;
            }
        }
        *s++ = '\0';
        if (( label != NULL ) && ( *label != '\0' ))
        {
           vcos_log_impl( cat, VCOS_LOG_INFO, "%s: %08" PRIx32 ": %s", label, addr, lineBuf );
        }
        else
        {
           vcos_log_impl( cat, VCOS_LOG_INFO, "%08" PRIx32 ": %s", addr, lineBuf );
        }
        addr += 16;
        mem += 16;
        if ( numBytes > 16 )
        {
            numBytes -= 16;
        }
        else
        {
            numBytes = 0;
        }
    }
 }
vcos_log_get_default_category()
VCOSPRE_ const VCOS_LOG_CAT_T* VCOSPOST_ vcos_log_get_default_category (void)
Return a default logging category, for people too lazy to create their own.
Using the default category will be slow (there's an extra function call overhead). Don't do this in normal code.
Definition at line 478 of file vcos_logcat.c.
 {
    return &dflt_log_category;
 }
vcos_log_impl()
void vcos_log_impl (const VCOS_LOG_CAT_T * cat, VCOS_LOG_LEVEL_T _level, const char * fmt, ...)
Definition at line 553 of file vcos_logcat.c.
References vcos_vlog_impl().
Referenced by vcos_log_dump_mem_impl().
 {
    va_list ap;
    va_start(ap,fmt);
    vcos_vlog_impl( cat, _level, fmt, ap );
    va_end(ap);
 }
vcos_log_level_to_string()
const char* vcos_log_level_to_string (VCOS_LOG_LEVEL_T level)
Convert a VCOS_LOG_LEVEL_T into a printable string. The platform needs to implement this function.
Definition at line 320 of file vcos_logcat.c.
References VCOS_LOG_ERROR, VCOS_LOG_INFO, VCOS_LOG_NEVER, VCOS_LOG_TRACE, VCOS_LOG_UNINITIALIZED, and VCOS_LOG_WARN.
 {
    switch (level)
    {
       case VCOS_LOG_UNINITIALIZED:  return "uninit";
       case VCOS_LOG_NEVER:          return "never";
       case VCOS_LOG_ERROR:          return "error";
       case VCOS_LOG_WARN:           return "warn";
       case VCOS_LOG_INFO:           return "info";
       case VCOS_LOG_TRACE:          return "trace";
    }
    return "???";
 }
vcos_log_register()
void vcos_log_register (const char * name, VCOS_LOG_CAT_T * category)
Register a logging category.
Parameters
name the name of this category.
category the category to register.
Definition at line 373 of file vcos_logcat.c.
References VCOS_LOG_CAT_T::flags, VCOS_LOG_CAT_T::level, name, VCOS_LOG_CAT_T::name, VCOS_LOG_ERROR, VCOS_LOG_UNINITIALIZED, and VCOS_LOG_CAT_T::want_prefix.
Referenced by ilclient_init(), main(), OpenVideoCoreMemoryFileWithOffset(), raspitex_init(), vc_hostfs_init(), vc_vchi_tv_init(), and wfc_server_connect().
 {
    const char *env;
    VCOS_LOG_CAT_T *i;
    category->name  = name;
    if ( category->level == VCOS_LOG_UNINITIALIZED )
    {
       category->level = VCOS_LOG_ERROR;
    }
    category->flags.want_prefix = (category != &dflt_log_category );
    vcos_mutex_lock(&lock);
    /* is it already registered? */
    for (i = vcos_logging_categories; i ; i = i->next )
    {
       if (i == category)
       {
          i->refcount++;
          break;
       }
    }
    if (!i)
    {
       /* not yet registered */
       category->next = vcos_logging_categories;
       vcos_logging_categories = category;
       category->refcount++;
       vcos_log_platform_register(category);
    }
    vcos_mutex_unlock(&lock);
    /* Check to see if this log level has been enabled. Look for
     * (<category:level>,)*
     *
     * VC_LOGLEVEL=ilcs:info,vchiq:warn
     */
    env = _VCOS_LOG_LEVEL();
    if (env && env[0])
    {
       do
       {
          char env_name[64];
          VCOS_LOG_LEVEL_T level;
          if (read_tok(env_name, sizeof(env_name), &env, ':') &&
              read_level(&level, &env, ','))
          {
             if (strcmp(env_name, name) == 0 || strcmp(env_name, "*") == 0)
             {
                // we could match both * and env_name, so make sure * comes
                // first in the logging_level string
                category->level = level;
             }
          }
          else
          {
             if (!warned_loglevel)
             {
                 vcos_log("VC_LOGLEVEL format invalid at %s\n", env);
                 warned_loglevel = 1;
             }
             return;
          }
       } while (env[0] != '\0');
    }
    vcos_log_info( "Registered log category '%s' with level %s",
                   category->name,
                   vcos_log_level_to_string( category->level ));
 }
vcos_log_unregister()
void vcos_log_unregister (VCOS_LOG_CAT_T * category)
Unregister a logging category.
Definition at line 449 of file vcos_logcat.c.
References VCOS_LOG_CAT_T::next, NULL, VCOS_LOG_CAT_T::refcount, vcos_assert, vcos_log_platform_unregister, vcos_logging_categories, vcos_mutex_lock(), and vcos_mutex_unlock().
Referenced by ilclient_destroy(), vc_hostfs_exit(), wfc_server_connect(), and wfc_server_disconnect().
 {
    VCOS_LOG_CAT_T **pcat;
    vcos_mutex_lock(&lock);
    category->refcount--;
    if (category->refcount == 0)
    {
       pcat = &vcos_logging_categories;
       while (*pcat != category)
       {
          if (!*pcat)
             break;   /* possibly deregistered twice? */
          if ((*pcat)->next == NULL)
          {
             vcos_assert(0); /* already removed! */
             vcos_mutex_unlock(&lock);
             return;
          }
          pcat = &(*pcat)->next;
       }
       if (*pcat)
          *pcat = category->next;
       vcos_log_platform_unregister(category);
    }
    vcos_mutex_unlock(&lock);
 }
vcos_logging_init()
void vcos_logging_init (void)
Definition at line 261 of file vcos_logcat.c.
 {
    if (inited)
    {
       /* FIXME: should print a warning or something here */
       return;
    }
    vcos_mutex_create(&lock, "vcos_log");
    vcos_log_platform_init();
    vcos_log_register("default", &dflt_log_category);
 #if VCOS_WANT_LOG_CMD
    vcos_cmd_register( &cmd_log );
 #endif
    vcos_assert(!inited);
    inited = 1;
 }
vcos_set_log_options()
void vcos_set_log_options (const char * opt)
Definition at line 483 of file vcos_logcat.c.
References void().
 {
    (void)opt;
 }
vcos_set_vlog_impl()
void vcos_set_vlog_impl (VCOS_VLOG_IMPL_FUNC_T vlog_impl_func)
Set the function which does the actual logging output. Passing in NULL causes the default logging function to be used.
Definition at line 566 of file vcos_logcat.c.
References NULL.
 {
    if ( vlog_impl_func == NULL )
    {
       vcos_vlog_impl_func = vcos_vlog_default_impl;
    }
    else
    {
       vcos_vlog_impl_func = vlog_impl_func;
    }
 }
vcos_string_to_log_level()
VCOS_STATUS_T vcos_string_to_log_level (const char * str, VCOS_LOG_LEVEL_T * level)
Convert a string into a VCOS_LOG_LEVEL_T The platform needs to implement this function.
Definition at line 334 of file vcos_logcat.c.
References VCOS_EINVAL, VCOS_LOG_ERROR, VCOS_LOG_INFO, VCOS_LOG_NEVER, VCOS_LOG_TRACE, VCOS_LOG_WARN, and VCOS_SUCCESS.
 {
    if (strcmp(str,"error") == 0)
       *level = VCOS_LOG_ERROR;
    else if (strcmp(str,"never") == 0)
       *level = VCOS_LOG_NEVER;
    else if (strcmp(str,"warn") == 0)
       *level = VCOS_LOG_WARN;
    else if (strcmp(str,"warning") == 0)
       *level = VCOS_LOG_WARN;
    else if (strcmp(str,"info") == 0)
       *level = VCOS_LOG_INFO;
    else if (strcmp(str,"trace") == 0)
       *level = VCOS_LOG_TRACE;
    else
       return VCOS_EINVAL;
    return VCOS_SUCCESS;
 }
vcos_vlog_impl()
void vcos_vlog_impl (const VCOS_LOG_CAT_T * cat, VCOS_LOG_LEVEL_T _level, const char * fmt, va_list args)
Definition at line 561 of file vcos_logcat.c.
Referenced by vcos_log_impl().
 {
    vcos_vlog_impl_func( cat, _level, fmt, args );
 }
Variable Documentation
vcos_logging_categories
VCOS_LOG_CAT_T* vcos_logging_categories = NULL
Definition at line 43 of file vcos_logcat.c.
Referenced by vcos_log_unregister().