VideoCore Library: interface/vcos/generic/vcos_generic_safe_string.c File Reference
vcos_generic_safe_string.c File Reference
#include "interface/vcos/vcos.h"
#include <string.h>
#include <stdarg.h>
Functions
size_t vcos_safe_vsprintf (char *buf, size_t buflen, size_t offset, const char *fmt, va_list ap)
size_t vcos_safe_sprintf (char *buf, size_t buflen, size_t offset, const char *fmt,...)
size_t vcos_safe_strcpy (char *dst, const char *src, size_t dstlen, size_t offset)
Function Documentation
vcos_safe_sprintf()
size_t vcos_safe_sprintf (char * buf, size_t buflen, size_t offset, const char * fmt, ...)
Like snprintf, except it places the output at the specified offset. Output is truncated to fit in buflen bytes, and is guaranteed to be NUL-terminated. Returns the string length before/without truncation.
Definition at line 56 of file vcos_generic_safe_string.c.
References NULL, offset, and vcos_vsnprintf().
 {
    size_t space = (offset < buflen) ? (buflen - offset) : 0;
    va_list ap;
    va_start(ap, fmt);
    offset += vcos_vsnprintf(buf ? (buf + offset) : NULL, space, fmt, ap);
    va_end(ap);
    return offset;
 }
vcos_safe_strcpy()
size_t vcos_safe_strcpy (char * dst, const char * src, size_t dstlen, size_t offset)
Copies string src to dst at the specified offset. Output is truncated to fit in dstlen bytes, i.e. the string is at most (buflen - 1) characters long. Unlike strncpy, exactly one NUL is written to dst, which is always NUL-terminated. Returns the string length before/without truncation.
Definition at line 76 of file vcos_generic_safe_string.c.
References offset.
Referenced by main(), mmal_vc_host_log(), mmal_vc_opaque_alloc_desc(), and vc_hostfs_readdir_r().
 {
    if (offset < dstlen)
    {
       const char *p = src;
       char *endp = dst + dstlen -1;
       dst += offset;
       for (; *p!='\0' && dst != endp; dst++, p++)
          *dst = *p;
       *dst = '\0';
    }
    offset += strlen(src);
    return offset;
 }
vcos_safe_vsprintf()
size_t vcos_safe_vsprintf (char * buf, size_t buflen, size_t offset, const char * fmt, va_list ap)
Like vsnprintf, except it places the output at the specified offset. Output is truncated to fit in buflen bytes, and is guaranteed to be NUL-terminated. Returns the string length before/without truncation.
Definition at line 43 of file vcos_generic_safe_string.c.
References NULL, offset, and vcos_vsnprintf().
 {
    size_t space = (offset < buflen) ? (buflen - offset) : 0;
    offset += vcos_vsnprintf(buf ? (buf + offset) : NULL, space, fmt, ap);
    return offset;
 }