VideoCore Library: interface/khronos/egl/egl_client.c File Reference
egl_client.c File Reference
#include "interface/khronos/common/khrn_client_mangle.h"
#include "interface/khronos/common/khrn_int_common.h"
#include "interface/khronos/common/khrn_options.h"
#include "interface/khronos/egl/egl_client_surface.h"
#include "interface/khronos/egl/egl_client_context.h"
#include "interface/khronos/egl/egl_client_config.h"
#include "interface/khronos/common/khrn_client.h"
#include "interface/khronos/common/khrn_client_rpc.h"
#include <stdlib.h>
#include <string.h>
#include "interface/khronos/egl/egl_client_cr.c"
Classes
struct PIXMAP_CHECK_DATA_T
Macros
#define VCOS_LOG_CATEGORY (&egl_client_log_cat)
Functions
void egl_gl_flush_callback (bool wait)
void egl_vg_flush_callback (bool wait)
EGLAPI EGLBoolean EGLAPIENTRY eglInitialize (EGLDisplay dpy, EGLint *major, EGLint *minor)
EGLAPI EGLBoolean EGLAPIENTRY eglTerminate (EGLDisplay dpy)
EGLAPI const char EGLAPIENTRY * eglQueryString (EGLDisplay dpy, EGLint name)
EGLAPI EGLSurface EGLAPIENTRY eglCreateWindowSurface (EGLDisplay dpy, EGLConfig config, EGLNativeWindowType win, const EGLint *attrib_list)
EGLAPI EGLSurface EGLAPIENTRY eglCreatePbufferSurface (EGLDisplay dpy, EGLConfig config, const EGLint *attrib_list)
EGLAPI EGLSurface EGLAPIENTRY eglCreatePixmapSurface (EGLDisplay dpy, EGLConfig config, EGLNativePixmapType pixmap, const EGLint *attrib_list)
EGLAPI EGLBoolean EGLAPIENTRY eglDestroySurface (EGLDisplay dpy, EGLSurface surf)
EGLAPI EGLBoolean EGLAPIENTRY eglQuerySurface (EGLDisplay dpy, EGLSurface surf, EGLint attribute, EGLint *value)
EGLAPI EGLBoolean EGLAPIENTRY eglBindAPI (EGLenum api)
EGLAPI EGLenum EGLAPIENTRY eglQueryAPI (void)
EGLAPI EGLBoolean EGLAPIENTRY eglWaitClient (void)
EGLAPI EGLBoolean EGLAPIENTRY eglReleaseThread (void)
EGLAPI EGLSurface EGLAPIENTRY eglCreatePbufferFromClientBuffer (EGLDisplay dpy, EGLenum buftype, EGLClientBuffer buffer, EGLConfig config, const EGLint *attrib_list)
EGLAPI EGLBoolean EGLAPIENTRY eglSurfaceAttrib (EGLDisplay dpy, EGLSurface surf, EGLint attribute, EGLint value)
EGLAPI EGLBoolean EGLAPIENTRY eglBindTexImage (EGLDisplay dpy, EGLSurface surf, EGLint buffer)
EGLAPI EGLBoolean EGLAPIENTRY eglReleaseTexImage (EGLDisplay dpy, EGLSurface surf, EGLint buffer)
EGLAPI EGLBoolean EGLAPIENTRY eglSwapInterval (EGLDisplay dpy, EGLint interval)
EGLAPI EGLContext EGLAPIENTRY eglCreateContext (EGLDisplay dpy, EGLConfig config, EGLContext share_ctx, const EGLint *attrib_list)
EGLAPI EGLBoolean EGLAPIENTRY eglDestroyContext (EGLDisplay dpy, EGLContext ctx)
void egl_gl_render_callback (void)
void egl_vg_render_callback (void)
EGLAPI EGLBoolean EGLAPIENTRY eglMakeCurrent (EGLDisplay dpy, EGLSurface dr, EGLSurface rd, EGLContext ctx)
EGLAPI EGLContext EGLAPIENTRY eglGetCurrentContext (void)
EGLAPI EGLSurface EGLAPIENTRY eglGetCurrentSurface (EGLint readdraw)
EGLAPI EGLDisplay EGLAPIENTRY eglGetCurrentDisplay (void)
EGLAPI EGLBoolean EGLAPIENTRY eglQueryContext (EGLDisplay dpy, EGLContext ctx, EGLint attribute, EGLint *value)
EGLAPI EGLBoolean EGLAPIENTRY eglWaitGL (void)
EGLAPI EGLBoolean EGLAPIENTRY eglWaitNative (EGLint engine)
EGLAPI EGLBoolean EGLAPIENTRY eglSwapBuffers (EGLDisplay dpy, EGLSurface surf)
EGLAPI EGLBoolean EGLAPIENTRY eglCopyBuffers (EGLDisplay dpy, EGLSurface surf, EGLNativePixmapType target)
Variables
VCOS_LOG_CAT_T egl_client_log_cat
Macro Definition Documentation
VCOS_LOG_CATEGORY
#define VCOS_LOG_CATEGORY (&egl_client_log_cat)
Definition at line 123 of file egl_client.c.
Function Documentation
egl_gl_flush_callback()
void egl_gl_flush_callback (bool wait)
Definition at line 1836 of file egl_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    CLIENT_LOCK();
    retrieve_pixmap(thread->opengl.draw, wait);
    CLIENT_UNLOCK();
 }
egl_gl_render_callback()
void egl_gl_render_callback (void)
Definition at line 1757 of file egl_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    CLIENT_LOCK();
    send_pixmap(thread->opengl.draw);
    CLIENT_UNLOCK();
 }
egl_vg_flush_callback()
void egl_vg_flush_callback (bool wait)
Definition at line 1847 of file egl_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    CLIENT_LOCK();
    retrieve_pixmap(thread->openvg.draw, wait);
    CLIENT_UNLOCK();
 }
egl_vg_render_callback()
void egl_vg_render_callback (void)
Definition at line 1768 of file egl_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    CLIENT_LOCK();
    send_pixmap(thread->openvg.draw);
    CLIENT_UNLOCK();
 }
eglBindAPI()
EGLAPI EGLBoolean EGLAPIENTRY eglBindAPI (EGLenum api)
Definition at line 1155 of file egl_client.c.
Referenced by init().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    switch (api) {
    case EGL_OPENVG_API:
    case EGL_OPENGL_ES_API:
       thread->bound_api = api;
       thread->error = EGL_SUCCESS;
       return EGL_TRUE;
    default:
       thread->error = EGL_BAD_PARAMETER;
       return EGL_FALSE;
    }
 }
eglBindTexImage()
EGLAPI EGLBoolean EGLAPIENTRY eglBindTexImage (EGLDisplay dpy, EGLSurface surf, EGLint buffer)
Definition at line 1376 of file egl_client.c.
 {
    CLIENT_THREAD_STATE_T *thread;
    CLIENT_PROCESS_STATE_T *process;
    EGLBoolean result;
    if (CLIENT_LOCK_AND_GET_STATES(dpy, &thread, &process))
    {
 //TODO: is behaviour correct if there is no current rendering context?
       EGL_SURFACE_T *surface;
       thread->error = EGL_SUCCESS;
       surface = client_egl_get_surface(thread, process, surf);
       if (surface) {
          if (surface->texture_format != EGL_NO_TEXTURE) {
             if (buffer == EGL_BACK_BUFFER) {
                if (surface->type == PBUFFER && surface->texture_target == EGL_TEXTURE_2D) {
                   result = (EGLBoolean) RPC_BOOLEAN_RES(RPC_CALL1_RES(eglIntBindTexImage_impl,
                      thread,
                      EGLINTBINDTEXIMAGE_ID,
                      surface->serverbuffer));
                   if (result != EGL_TRUE) {
                      // If buffer is already bound to a texture then an
                      // EGL_BAD_ACCESS error is returned.
                      // But we don't know whether it is or not until we call
                      // the server.
                      thread->error = EGL_BAD_ACCESS;
                   }
                } else {
                   thread->error = EGL_BAD_SURFACE;
                   result = EGL_FALSE;
                }
             } else {
                thread->error = EGL_BAD_PARAMETER;
                result = EGL_FALSE;
             }
          } else {
             thread->error = EGL_BAD_MATCH;
             result = EGL_FALSE;
          }
       }
       result = (thread->error == EGL_SUCCESS ? EGL_TRUE : EGL_FALSE );
       CLIENT_UNLOCK();
    } else
       result = EGL_FALSE;
    return result;
 }
eglCopyBuffers()
EGLAPI EGLBoolean EGLAPIENTRY eglCopyBuffers (EGLDisplay dpy, EGLSurface surf, EGLNativePixmapType target)
Definition at line 2365 of file egl_client.c.
 {
    CLIENT_THREAD_STATE_T *thread;
    CLIENT_PROCESS_STATE_T *process;
    EGLBoolean result;
    if (CLIENT_LOCK_AND_GET_STATES(dpy, &thread, &process))
    {
       EGL_SURFACE_T *surface;
       thread->error = EGL_SUCCESS;
       surface = client_egl_get_surface(thread, process, surf);
       if ((thread->bound_api == EGL_OPENGL_ES_API && surface != thread->opengl.draw && surface != thread->opengl.read)
        || (thread->bound_api == EGL_OPENVG_API    && surface != thread->openvg.draw)) {
          /* Surface to be displayed must be bound to current context and API */
          /* TODO remove this restriction, as we'll need to for eglSwapBuffers? */
          thread->error = EGL_BAD_SURFACE;
       } else if (surface) {
          KHRN_IMAGE_WRAP_T image;
          if (!platform_get_pixmap_info(target, &image)) {
             thread->error = EGL_BAD_NATIVE_PIXMAP;
          } else {
             if (image.width != surface->width || image.height != surface->height) {
                thread->error = EGL_BAD_MATCH;
             } else {
                //Bear in mind it's possible to call eglCopyBuffers on a pixmap
                //surface which will result in the data being transferred twice, onto
                //two different native pixmaps.
                //TODO: flush the other API too?
                   //TODO: is this necessary?
                flush_current_api(thread);
                   get_color_data(surface->serverbuffer, &image);
             }
             khrn_platform_release_pixmap_info(target, &image);
          }
       }
       result = (thread->error == EGL_SUCCESS);
       CLIENT_UNLOCK();
    }
    else
       result = EGL_FALSE;
    return result;
 }
eglCreateContext()
EGLAPI EGLContext EGLAPIENTRY eglCreateContext (EGLDisplay dpy, EGLConfig config, EGLContext share_ctx, const EGLint * attrib_list)
Definition at line 1538 of file egl_client.c.
Referenced by init().
 {
    CLIENT_THREAD_STATE_T *thread;
    CLIENT_PROCESS_STATE_T *process;
    EGLContext result;
 vcos_log_trace("eglCreateContext start");
    if (CLIENT_LOCK_AND_GET_STATES(dpy, &thread, &process))
    {
       if ((int)(size_t)config < 1 || (int)(size_t)config > EGL_MAX_CONFIGS) {
          thread->error = EGL_BAD_CONFIG;
          result = EGL_NO_CONTEXT;
       } else {
          EGLint max_version = (EGLint) (thread->bound_api == EGL_OPENGL_ES_API ? 2 : 1);
          EGLint version = 1;
          if (!egl_context_check_attribs(attrib_list, max_version, &version)) {
             thread->error = EGL_BAD_ATTRIBUTE;
             result = EGL_NO_CONTEXT;
          } else if (!(egl_config_get_api_support((int)(intptr_t)config - 1) &
             ((thread->bound_api == EGL_OPENVG_API) ? EGL_OPENVG_BIT :
             ((version == 1) ? EGL_OPENGL_ES_BIT : EGL_OPENGL_ES2_BIT)))) {
             thread->error = EGL_BAD_CONFIG;
             result = EGL_NO_CONTEXT;
          } else {
             EGL_CONTEXT_T *share_context;
             if (share_ctx != EGL_NO_CONTEXT) {
                share_context = client_egl_get_context(thread, process, share_ctx);
                if (share_context) {
                   if ((share_context->type == OPENVG && thread->bound_api != EGL_OPENVG_API) ||
                      (share_context->type != OPENVG && thread->bound_api == EGL_OPENVG_API)) {
                      thread->error = EGL_BAD_MATCH;
                      share_context = NULL;
                   }
                } else {
                   thread->error = EGL_BAD_CONTEXT;
                }
             } else {
                share_context = NULL;
             }
             if (share_ctx == EGL_NO_CONTEXT || share_context) {
                EGL_CONTEXT_T *context;
                EGL_CONTEXT_TYPE_T type;
 #ifndef NO_OPENVG
                if (thread->bound_api == EGL_OPENVG_API)
                   type = OPENVG;
                else
 #endif
                   if (version == 1)
                      type = OPENGL_ES_11;
                   else
                      type = OPENGL_ES_20;
                context = egl_context_create(
                                 share_context,
                                 (EGLContext)(size_t)process->next_context,
                                 dpy, config, type);
                if (context) {
                   if (khrn_pointer_map_insert(&process->contexts, process->next_context, context)) {
                      thread->error = EGL_SUCCESS;
                      result = (EGLContext)(size_t)process->next_context++;
                   } else {
                      thread->error = EGL_BAD_ALLOC;
                      result = EGL_NO_CONTEXT;
                      egl_context_term(context);
                      khrn_platform_free(context);
                   }
                } else {
                   thread->error = EGL_BAD_ALLOC;
                   result = EGL_NO_CONTEXT;
                }
             } else {
                /* thread->error set above */
                result = EGL_NO_CONTEXT;
             }
          }
       }
       CLIENT_UNLOCK();
    }
    else
       result = EGL_NO_CONTEXT;
    vcos_log_trace("eglCreateContext end");
    return result;
 }
eglCreatePbufferFromClientBuffer()
EGLAPI EGLSurface EGLAPIENTRY eglCreatePbufferFromClientBuffer (EGLDisplay dpy, EGLenum buftype, EGLClientBuffer buffer, EGLConfig config, const EGLint * attrib_list)
Definition at line 1253 of file egl_client.c.
 {
    CLIENT_THREAD_STATE_T *thread;
    CLIENT_PROCESS_STATE_T *process;
    EGLSurface result;
    if (CLIENT_LOCK_AND_GET_STATES(dpy, &thread, &process))
    {
 #ifndef NO_OPENVG
       if (buftype != EGL_OPENVG_IMAGE) {
          thread->error = EGL_BAD_PARAMETER;
          result = EGL_NO_SURFACE;
       } else if ((int)(size_t)config < 1 || (int)(size_t)config > EGL_MAX_CONFIGS) {
          thread->error = EGL_BAD_CONFIG;
          result = EGL_NO_SURFACE;
       } else {
          bool largest_pbuffer = 0;
          EGLenum texture_format = EGL_NO_TEXTURE;
          EGLenum texture_target = EGL_NO_TEXTURE;
          bool mipmap_texture = EGL_FALSE;
          /* Ignore the width and height as specified by attrib_list */
          /* Also ignore linear and premult */
          if (!egl_surface_check_attribs(PBUFFER, attrib_list, 0, 0, 0, 0, 0, &largest_pbuffer, &texture_format, &texture_target, &mipmap_texture)) {
             thread->error = EGL_BAD_ATTRIBUTE;
             result = EGL_NO_SURFACE;
          } else if (
             (texture_format == EGL_NO_TEXTURE) != (texture_target == EGL_NO_TEXTURE) ||
             !egl_config_bindable((int)(size_t)config - 1, texture_format)
          ) {
          /*
          "In addition, an EGL_BAD_MATCH
          error is generated if any of the following conditions are true:
          - The EGL_TEXTURE_FORMAT attribute is not EGL_NO_TEXTURE, and
          EGL_WIDTH and/or EGL_HEIGHT specify an invalid size (e.g., the texture size
          is not a power of two, and the underlying OpenGL ES implementation does
          not support non-power-of-two textures).
          - The EGL_TEXTURE_FORMAT attribute is EGL_NO_TEXTURE, and
          EGL_TEXTURE_TARGET is something other than EGL_NO_TEXTURE; or,
          EGL_TEXTURE_FORMAT is something other than EGL_NO_TEXTURE, and
          EGL_TEXTURE_TARGET is EGL_NO_TEXTURE."
           */
          /*
          It doesn't seem to explicitly say it in the spec, but I'm also
          generating EGL_BAD_MATCH if the config doesn't support EGL_BIND_TO_TEXTURE_RGB(A)
          and you specify EGL_TEXTURE_FORMAT=EGL_TEXTURE_RGB(A)
          */
             thread->error = EGL_BAD_MATCH;
             result = EGL_NO_SURFACE;
          } else {
             EGLint error;
             EGL_SURFACE_T *surface = egl_surface_from_vg_image(
                        (VGImage)(size_t)buffer,
                        (EGLSurface)(size_t)process->next_surface,
                        config,
                        largest_pbuffer,
                        mipmap_texture,
                        texture_format,
                        texture_target,
                        &error);
             if (surface) {
                if (khrn_pointer_map_insert(&process->surfaces, process->next_surface, surface)) {
                   thread->error = EGL_SUCCESS;
                   result = (EGLSurface)(size_t)process->next_surface++;
                } else {
                   thread->error = EGL_BAD_ALLOC;
                   result = EGL_NO_SURFACE;
                   egl_surface_free(surface);
                }
             } else {
                thread->error = error;
                result = EGL_NO_SURFACE;
             }
          }
       }
 #else
       UNUSED(buftype);
       UNUSED(buffer);
       UNUSED(config);
       UNUSED(attrib_list);
       thread->error = EGL_BAD_PARAMETER;
       result = EGL_NO_SURFACE;
 #endif /* NO_OPENVG */
       CLIENT_UNLOCK();
    }
    else
       result = EGL_NO_SURFACE;
    return result;
 }
eglCreatePbufferSurface()
EGLAPI EGLSurface EGLAPIENTRY eglCreatePbufferSurface (EGLDisplay dpy, EGLConfig config, const EGLint * attrib_list)
Definition at line 817 of file egl_client.c.
 {
    CLIENT_THREAD_STATE_T *thread;
    CLIENT_PROCESS_STATE_T *process;
    EGLSurface result;
    if (CLIENT_LOCK_AND_GET_STATES(dpy, &thread, &process))
    {
       if ((int)(size_t)config < 1 || (int)(size_t)config > EGL_MAX_CONFIGS) {
          thread->error = EGL_BAD_CONFIG;
          result = EGL_NO_SURFACE;
       } else {
          int width = 0;
          int height = 0;
          bool largest_pbuffer = 0;
          EGLenum texture_format = EGL_NO_TEXTURE;
          EGLenum texture_target = EGL_NO_TEXTURE;
          bool mipmap_texture = EGL_FALSE;
          bool linear = EGL_FALSE;
          bool premult = EGL_FALSE;
          if (!egl_surface_check_attribs(PBUFFER, attrib_list, &linear, &premult, 0, &width, &height, &largest_pbuffer, &texture_format, &texture_target, &mipmap_texture)) {
             thread->error = EGL_BAD_ATTRIBUTE;
             result = EGL_NO_SURFACE;
          } else if (
             (texture_format != EGL_NO_TEXTURE && (width == 0 || height == 0)) ||
             ((texture_format == EGL_NO_TEXTURE) != (texture_target == EGL_NO_TEXTURE)) ||
             !egl_config_bindable((int)(size_t)config - 1, texture_format)
          ) {
          /*
          "In addition, an EGL_BAD_MATCH
          error is generated if any of the following conditions are true:
          - The EGL_TEXTURE_FORMAT attribute is not EGL_NO_TEXTURE, and
          EGL_WIDTH and/or EGL_HEIGHT specify an invalid size (e.g., the texture size
          is not a power of two, and the underlying OpenGL ES implementation does
          not support non-power-of-two textures).
          - The EGL_TEXTURE_FORMAT attribute is EGL_NO_TEXTURE, and
          EGL_TEXTURE_TARGET is something other than EGL_NO_TEXTURE; or,
          EGL_TEXTURE_FORMAT is something other than EGL_NO_TEXTURE, and
          EGL_TEXTURE_TARGET is EGL_NO_TEXTURE."
           */
          /*
          TODO It doesn't seem to explicitly say it in the spec, but I'm also
          generating EGL_BAD_MATCH if the config doesn't support EGL_BIND_TO_TEXTURE_RGB(A)
          and you specify EGL_TEXTURE_FORMAT=EGL_TEXTURE_RGB(A)
          */
             thread->error = EGL_BAD_MATCH;
             result = EGL_NO_SURFACE;
          } else if ((width > EGL_CONFIG_MAX_WIDTH || height > EGL_CONFIG_MAX_HEIGHT) && !largest_pbuffer) {
             /*
                TODO no mention of this in the spec, but clearly we fail if we try to allocate
                an oversize pbuffer without the largest_pbuffer stuff enabled
             */
             thread->error = EGL_BAD_ALLOC;
             result = EGL_NO_SURFACE;
          } else {
             EGL_SURFACE_T *surface = egl_surface_create(
                              (EGLSurface)(size_t)process->next_surface,
                              PBUFFER,
                              linear ? LINEAR : SRGB,
                              premult ? PRE : NONPRE,
                              1,
                              width, height,
                              config,
                              0,
                              PLATFORM_WIN_NONE,
                              largest_pbuffer,
                              true,
                              mipmap_texture,
                              texture_format,
                              texture_target,
                              0, 0);
             if (surface) {
                if (khrn_pointer_map_insert(&process->surfaces, process->next_surface, surface)) {
                   thread->error = EGL_SUCCESS;
                   result = (EGLSurface)(size_t)process->next_surface++;
                } else {
                   thread->error = EGL_BAD_ALLOC;
                   result = EGL_NO_SURFACE;
                   egl_surface_free(surface);
                }
             } else {
                thread->error = EGL_BAD_ALLOC;
                result = EGL_NO_SURFACE;
             }
          }
       }
       CLIENT_UNLOCK();
    }
    else
       result = EGL_NO_SURFACE;
    return result;
 }
eglCreatePixmapSurface()
EGLAPI EGLSurface EGLAPIENTRY eglCreatePixmapSurface (EGLDisplay dpy, EGLConfig config, EGLNativePixmapType pixmap, const EGLint * attrib_list)
Definition at line 947 of file egl_client.c.
 {
    CLIENT_THREAD_STATE_T *thread;
    CLIENT_PROCESS_STATE_T *process;
    EGLSurface result;
    vcos_log_trace("eglCreatePixmapSurface");
    if (CLIENT_LOCK_AND_GET_STATES(dpy, &thread, &process))
    {
       if ((int)(size_t)config < 1 || (int)(size_t)config > EGL_MAX_CONFIGS) {
          thread->error = EGL_BAD_CONFIG;
          result = EGL_NO_SURFACE;
       } else {
          bool linear = false;
          bool premult = false;
          if (!egl_surface_check_attribs(PIXMAP, attrib_list, &linear, &premult, 0, 0, 0, 0, 0, 0, 0)) {
             thread->error = EGL_BAD_ATTRIBUTE;
             result = EGL_NO_SURFACE;
          } else {
             EGL_SURFACE_T *surface;
             KHRN_IMAGE_WRAP_T image;
             if (!platform_get_pixmap_info(pixmap, &image)) {
                thread->error = EGL_BAD_NATIVE_PIXMAP;
                result = EGL_NO_SURFACE;
             } else {
                uint32_t server_handle[2] = {0, (uint32_t)-1};
                platform_get_pixmap_server_handle(pixmap, server_handle);
 #if !EGL_BRCM_global_image
                if (server_handle[1] != -1) {
                   thread->error = EGL_BAD_PARAMETER;
                   result = EGL_NO_SURFACE;
                } else
 #endif
                if (image.width > EGL_CONFIG_MAX_WIDTH || image.height > EGL_CONFIG_MAX_HEIGHT) {
                   /* Maybe EGL_BAD_ALLOC might be more appropriate? */
                   thread->error = EGL_BAD_NATIVE_WINDOW;
                   result = EGL_NO_SURFACE;
                } else if (!egl_config_match_pixmap_info((int)(size_t)config - 1, &image) ||
                   !platform_match_pixmap_api_support(pixmap, egl_config_get_api_support((int)(size_t)config - 1))
 #if EGL_BRCM_global_image
                   || ((server_handle[1] != (uint32_t)(-1)) && (
                   (!(image.format & IMAGE_FORMAT_LIN) != !linear) ||
                   (!(image.format & IMAGE_FORMAT_PRE) != !premult)))
 #endif
                   ) {
                   thread->error = EGL_BAD_MATCH;
                   result = EGL_NO_SURFACE;
                } else {
                   /*
                    * Check that we didn't already use this pixmap in an
                    * earlier call to eglCreatePixmapSurface()
                    */
                   PIXMAP_CHECK_DATA_T pixmap_check_data;
                   pixmap_check_data.process = process;
                   pixmap_check_data.pixmap = pixmap;
                   pixmap_check_data.pixmap_server_handle[0] = 0;
                   pixmap_check_data.pixmap_server_handle[1] = (uint32_t)-1;
                   platform_get_pixmap_server_handle(pixmap, pixmap_check_data.pixmap_server_handle);
                   pixmap_check_data.is_dup = 0;
                   khrn_pointer_map_iterate(&process->surfaces, callback_check_duplicate_pixmap, &pixmap_check_data);
                   if (pixmap_check_data.is_dup) {
                      thread->error = EGL_BAD_ALLOC;
                      result = EGL_NO_SURFACE;
                   } else {
                      surface = egl_surface_create(
                                    (EGLSurface)(size_t)process->next_surface,
                                    PIXMAP,
                                    linear ? LINEAR : SRGB,
                                    premult ? PRE : NONPRE,
                                    1,
                                    image.width, image.height,
                                    config,
                                    0,
                                    PLATFORM_WIN_NONE,
                                    false,
                                    false,
                                    false,
                                    EGL_NO_TEXTURE,
                                    EGL_NO_TEXTURE,
                                    pixmap, ((server_handle[0] == 0) && (server_handle[1] == (uint32_t)(-1))) ? NULL : server_handle);
                      if (surface) {
                         if (khrn_pointer_map_insert(&process->surfaces, process->next_surface, surface)) {
                            thread->error = EGL_SUCCESS;
                            result = (EGLSurface)(size_t)process->next_surface++;
                         } else {
                            thread->error = EGL_BAD_ALLOC;
                            result = EGL_NO_SURFACE;
                            egl_surface_free(surface);
                         }
                      } else {
                         thread->error = EGL_BAD_ALLOC;
                         result = EGL_NO_SURFACE;
                      }
                   }
                }
             }
          }
       }
       CLIENT_UNLOCK();
    }
    else
       result = EGL_NO_SURFACE;
    return result;
 }
eglCreateWindowSurface()
EGLAPI EGLSurface EGLAPIENTRY eglCreateWindowSurface (EGLDisplay dpy, EGLConfig config, EGLNativeWindowType win, const EGLint * attrib_list)
Definition at line 578 of file egl_client.c.
Referenced by init().
 {
    CLIENT_THREAD_STATE_T *thread;
    CLIENT_PROCESS_STATE_T *process;
    EGLSurface result;
    vcos_log_trace("eglCreateWindowSurface for window %p", win);
    if (CLIENT_LOCK_AND_GET_STATES(dpy, &thread, &process))
    {
       uint32_t handle = platform_get_handle(dpy, win);
       if ((int)(size_t)config < 1 || (int)(size_t)config > EGL_MAX_CONFIGS) {
          thread->error = EGL_BAD_CONFIG;
          result = EGL_NO_SURFACE;
       } else if (handle == PLATFORM_WIN_NONE) {
          // The platform reports that this is an invalid window handle
          thread->error = EGL_BAD_NATIVE_WINDOW;
          result = EGL_NO_SURFACE;
       } else {
          bool linear = false;
          bool premult = false;
          bool single = false;
          if (!egl_surface_check_attribs(WINDOW, attrib_list, &linear, &premult, &single, 0, 0, 0, 0, 0, 0)) {
             thread->error = EGL_BAD_ATTRIBUTE;
             result = EGL_NO_SURFACE;
          } else {
             EGL_SURFACE_T *surface;
             uint32_t width, height;
             uint32_t num_buffers = 3;
             uint32_t swapchain_count;
             platform_get_dimensions(dpy,
                   win, &width, &height, &swapchain_count);
             if (swapchain_count > 0)
                num_buffers = swapchain_count;
             else
             {
                if (khrn_options.double_buffer)
                   num_buffers = 2;
             }
             if (width <= 0 || width > EGL_CONFIG_MAX_WIDTH || height <= 0 || height > EGL_CONFIG_MAX_HEIGHT) {
                /* TODO: Maybe EGL_BAD_ALLOC might be more appropriate? */
                thread->error = EGL_BAD_NATIVE_WINDOW;
                result = EGL_NO_SURFACE;
             } else {
                surface = egl_surface_create(
                                 (EGLSurface)(size_t)process->next_surface,
                                 WINDOW,
                                 linear ? LINEAR : SRGB,
                                 premult ? PRE : NONPRE,
 #ifdef DIRECT_RENDERING
                                 1,
 #else
                                 (uint32_t)(single ? 1 : num_buffers),
 #endif
                                 width, height,
                                 config,
                                 win,
                                 handle,
                                 false,
                                 false,
                                 false,
                                 EGL_NO_TEXTURE,
                                 EGL_NO_TEXTURE,
                                 0, 0);
                if (surface) {
                   if (khrn_pointer_map_insert(&process->surfaces, process->next_surface, surface)) {
                      thread->error = EGL_SUCCESS;
                      result = (EGLSurface)(size_t)process->next_surface++;
                   } else {
                      thread->error = EGL_BAD_ALLOC;
                      result = EGL_NO_SURFACE;
                      egl_surface_free(surface);
                   }
                } else {
                   thread->error = EGL_BAD_ALLOC;
                   result = EGL_NO_SURFACE;
                }
             }
          }
       }
       CLIENT_UNLOCK();
    }
    else
       result = EGL_NO_SURFACE;
    vcos_log_trace("eglCreateWindowSurface end %i", (int) result);
    return result;
 }
eglDestroyContext()
EGLAPI EGLBoolean EGLAPIENTRY eglDestroyContext (EGLDisplay dpy, EGLContext ctx)
Definition at line 1631 of file egl_client.c.
Referenced by raspitexutil_gl_term().
 {
    CLIENT_THREAD_STATE_T *thread;
    CLIENT_PROCESS_STATE_T *process;
    EGLBoolean result;
    vcos_log_trace("eglDestroyContext ctx=%d.", (int)ctx);
    if (CLIENT_LOCK_AND_GET_STATES(dpy, &thread, &process))
    {
       EGL_CONTEXT_T *context;
       thread->error = EGL_SUCCESS;
       context = client_egl_get_context(thread, process, ctx);
       if (context) {
          context->is_destroyed = true;
          khrn_pointer_map_delete(&process->contexts, (uint32_t)(uintptr_t)ctx);
          egl_context_maybe_free(context);
       }
       result = thread->error == EGL_SUCCESS;
       CLIENT_UNLOCK();
    }
    else
       result = EGL_FALSE;
    return result;
 }
eglDestroySurface()
EGLAPI EGLBoolean EGLAPIENTRY eglDestroySurface (EGLDisplay dpy, EGLSurface surf)
Definition at line 1068 of file egl_client.c.
Referenced by graphics_delete_resource(), and raspitexutil_gl_term().
 {
    CLIENT_THREAD_STATE_T *thread;
    CLIENT_PROCESS_STATE_T *process;
    EGLBoolean result;
    vcos_log_trace("eglDestroySurface: surf=%d.\n calling CLIENT_LOCK_AND_GET_STATES...", (int)surf);
    if (CLIENT_LOCK_AND_GET_STATES(dpy, &thread, &process))
    {
       EGL_SURFACE_T *surface;
       thread->error = EGL_SUCCESS;
       vcos_log_trace("eglDestroySurface: calling client_egl_get_surface...");
       surface = client_egl_get_surface(thread, process, surf);
       if (surface) {
          surface->is_destroyed = true;
          khrn_pointer_map_delete(&process->surfaces, (uint32_t)(uintptr_t)surf);
          vcos_log_trace("eglDestroySurface: calling egl_surface_maybe_free...");
          egl_surface_maybe_free(surface);
       }
       result = (thread->error == EGL_SUCCESS ? EGL_TRUE : EGL_FALSE );
       CLIENT_UNLOCK();
    } else
       result = EGL_FALSE;
    vcos_log_trace("eglDestroySurface: end");
    return result;
 }
eglGetCurrentContext()
EGLAPI EGLContext EGLAPIENTRY eglGetCurrentContext (void)
Definition at line 2052 of file egl_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    EGLContext result;
    CLIENT_LOCK();
    {
       EGL_CURRENT_T *current;
       if (thread->bound_api == EGL_OPENVG_API)
          current = &thread->openvg;
       else
          current = &thread->opengl;
       if (!current->context)
          result = EGL_NO_CONTEXT;
       else
          result = current->context->name;
       thread->error = EGL_SUCCESS;
    }
    CLIENT_UNLOCK();
    return result;
 }
eglGetCurrentDisplay()
EGLAPI EGLDisplay EGLAPIENTRY eglGetCurrentDisplay (void)
Definition at line 2122 of file egl_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    EGLDisplay result;
    CLIENT_LOCK();
    {
       EGL_CURRENT_T *current;
       if (thread->bound_api == EGL_OPENVG_API)
          current = &thread->openvg;
       else
          current = &thread->opengl;
       if (!current->context)
          result = EGL_NO_DISPLAY;
       else
          result = current->context->display;
       thread->error = EGL_SUCCESS;
    }
    CLIENT_UNLOCK();
    return result;
 }
eglGetCurrentSurface()
EGLAPI EGLSurface EGLAPIENTRY eglGetCurrentSurface (EGLint readdraw)
Definition at line 2080 of file egl_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    EGLSurface result;
    CLIENT_LOCK();
    {
       EGL_CURRENT_T *current;
       EGL_SURFACE_T *surface;
       if (thread->bound_api == EGL_OPENVG_API)
          current = &thread->openvg;
       else
          current = &thread->opengl;
       switch (readdraw) {
       case EGL_READ:
          surface = current->read;
          thread->error = EGL_SUCCESS;
          break;
       case EGL_DRAW:
          surface = current->draw;
          thread->error = EGL_SUCCESS;
          break;
       default:
          surface = 0;
          thread->error = EGL_BAD_PARAMETER;
          break;
       }
       if (!surface)
          result = EGL_NO_SURFACE;
       else
          result = surface->name;
    }
    CLIENT_UNLOCK();
    return result;
 }
eglInitialize()
EGLAPI EGLBoolean EGLAPIENTRY eglInitialize (EGLDisplay dpy, EGLint * major, EGLint * minor)
Definition at line 217 of file egl_client.c.
Referenced by init().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    EGLBoolean result;
    CLIENT_LOCK();
    {
       CLIENT_PROCESS_STATE_T *process = client_egl_get_process_state(thread, dpy, EGL_FALSE);
       if (process) {
          if (!client_process_state_init(process))
          {
             thread->error = EGL_NOT_INITIALIZED;
             result = EGL_FALSE;
          }
          else
          {
             thread->error = EGL_SUCCESS;
             result = EGL_TRUE;
          }
       } else
          result = EGL_FALSE;
       if (result) {
          if (major)
             *major = 1;
          if (minor)
             *minor = 4;
       }
    }
    CLIENT_UNLOCK();
    vcos_log_set_level(&egl_client_log_cat, VCOS_LOG_WARN);
    vcos_log_register("egl_client", &egl_client_log_cat);
    vcos_log_info("eglInitialize end. dpy=%d.", (int)dpy);
    khrn_init_options();
    return result;
 }
eglMakeCurrent()
EGLAPI EGLBoolean EGLAPIENTRY eglMakeCurrent (EGLDisplay dpy, EGLSurface dr, EGLSurface rd, EGLContext ctx)
Definition at line 1955 of file egl_client.c.
Referenced by deinit(), init(), and raspitexutil_gl_term().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    EGLBoolean result;
    CLIENT_PROCESS_STATE_T *process = NULL; /* init to avoid warnings */
    CLIENT_LOCK();
    vcos_log_trace("Actual eglMakeCurrent %d %d %x", (int)ctx, (int)dr, (unsigned int) thread->error);
    /*
       check whether we are trying to release the current context
       Note that we can do this even if the display isn't initted.
    */
    if (dr == EGL_NO_SURFACE && rd == EGL_NO_SURFACE && ctx == EGL_NO_CONTEXT) {
       process = client_egl_get_process_state(thread, dpy, EGL_FALSE);
       if (process) {
          /* spec says we should flush in this case */
          flush_current_api(thread);
          egl_current_release(process,
             (thread->bound_api == EGL_OPENVG_API) ? &thread->openvg : &thread->opengl);
          client_send_make_current(thread);
          client_try_unload_server(process);
          thread->error = EGL_SUCCESS;
          result = EGL_TRUE;
       } else {
          result = EGL_FALSE;
       }
    } else  if (dr == EGL_NO_SURFACE || rd == EGL_NO_SURFACE || ctx == EGL_NO_CONTEXT) {
       thread->error = EGL_BAD_MATCH;
       result = EGL_FALSE;
    } else {
       /*
          get display
       */
       process = client_egl_get_process_state(thread, dpy, EGL_TRUE);
       if (!process)
          result = EGL_FALSE;
       else {
          /*
             get context
          */
          EGL_CONTEXT_T *context = client_egl_get_context(thread, process, ctx);
          if (!context) {
             result = EGL_FALSE;
          }  else {
             /*
                get surfaces
             */
             EGL_SURFACE_T *draw = client_egl_get_surface(thread, process, dr);
             EGL_SURFACE_T *read = client_egl_get_surface(thread, process, rd);
             if (!draw || !read) {
                result = EGL_FALSE;
             } else if (context->type == OPENVG && dr != rd) {
                thread->error = EGL_BAD_MATCH;   //TODO: what error are we supposed to return here?
                result = EGL_FALSE;
             } else {
                EGL_CURRENT_T *current;
                if (context->type == OPENVG)
                   current = &thread->openvg;
                else
                   current = &thread->opengl;
                if (!egl_current_set(process, thread, current, context, draw, read))
                   result = EGL_FALSE;
                else {
                   client_send_make_current(thread);
                   thread->error = EGL_SUCCESS;
                   result = EGL_TRUE;
                }
             }
          }
       }
    }
    CLIENT_UNLOCK();
    vcos_log_trace("Actual eglMakeCurrent end %d %d %d %x", (int)ctx, (int)dr, result, (unsigned int)thread->error);
    return result;
 }
eglQueryAPI()
EGLAPI EGLenum EGLAPIENTRY eglQueryAPI (void)
Definition at line 1172 of file egl_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    return thread->bound_api;
 }
eglQueryContext()
EGLAPI EGLBoolean EGLAPIENTRY eglQueryContext (EGLDisplay dpy, EGLContext ctx, EGLint attribute, EGLint * value)
Definition at line 2150 of file egl_client.c.
 {
    CLIENT_THREAD_STATE_T *thread;
    CLIENT_PROCESS_STATE_T *process;
    EGLBoolean result;
    if (CLIENT_LOCK_AND_GET_STATES(dpy, &thread, &process))
    {
       if (!value) {
          thread->error = EGL_BAD_PARAMETER;
          result = EGL_FALSE;
       } else {
          EGL_CONTEXT_T *context;
          thread->error = EGL_SUCCESS;
          context = client_egl_get_context(thread, process, ctx);
          if (context) {
             if (!egl_context_get_attrib(context, attribute, value))
                thread->error = EGL_BAD_ATTRIBUTE;
          }
          result = thread->error == EGL_SUCCESS;
       }
       CLIENT_UNLOCK();
    }
    else
       result = EGL_FALSE;
    return result;
 }
eglQueryString()
EGLAPI const char EGLAPIENTRY* eglQueryString (EGLDisplay dpy, EGLint name)
Definition at line 410 of file egl_client.c.
References NULL.
 {
    CLIENT_THREAD_STATE_T *thread;
    CLIENT_PROCESS_STATE_T *process;
    const char *result = NULL;
    if (CLIENT_LOCK_AND_GET_STATES(dpy, &thread, &process))
    {
       thread->error = EGL_SUCCESS;
       switch (name) {
       case EGL_CLIENT_APIS:
          result = "OpenGL_ES OpenVG";
          break;
       case EGL_EXTENSIONS:
          //TODO: this list isn't quite correct
          result = ""
 #if EGL_KHR_image
             "EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_vg_parent_image EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image "
 #endif
 #if EGL_KHR_lock_surface
             "EGL_KHR_lock_surface "
 #endif
 #if EGL_ANDROID_swap_rectangle
             "EGL_ANDROID_swap_rectangle "
 #endif
 #ifdef ANDROID
             "EGL_ANDROID_image_native_buffer "
 #endif
 #ifdef ANDROID
 #ifdef EGL_KHR_fence_sync
             "EGL_KHR_fence_sync "
 #endif
 #endif
             ;
          break;
       case EGL_VENDOR:
          result = "Broadcom";
          break;
       case EGL_VERSION:
          result = "1.4";
          break;
       default:
          thread->error = EGL_BAD_PARAMETER;
          result = NULL;
       }
       CLIENT_UNLOCK();
    } else
       result = NULL;
    return result;
 }
eglQuerySurface()
EGLAPI EGLBoolean EGLAPIENTRY eglQuerySurface (EGLDisplay dpy, EGLSurface surf, EGLint attribute, EGLint * value)
Definition at line 1102 of file egl_client.c.
 {
    CLIENT_THREAD_STATE_T *thread;
    CLIENT_PROCESS_STATE_T *process;
    EGLBoolean result;
    if (CLIENT_LOCK_AND_GET_STATES(dpy, &thread, &process))
    {
       EGL_SURFACE_T *surface;
       thread->error = EGL_SUCCESS;
       surface = client_egl_get_locked_surface(thread, process, surf);
       if (surface) {
 #if EGL_KHR_lock_surface
          switch (attribute)
          {
          case EGL_BITMAP_POINTER_KHR:
          case EGL_BITMAP_PITCH_KHR:
          case EGL_BITMAP_ORIGIN_KHR:
          case EGL_BITMAP_PIXEL_RED_OFFSET_KHR:
          case EGL_BITMAP_PIXEL_GREEN_OFFSET_KHR:
          case EGL_BITMAP_PIXEL_BLUE_OFFSET_KHR:
          case EGL_BITMAP_PIXEL_ALPHA_OFFSET_KHR:
          case EGL_BITMAP_PIXEL_LUMINANCE_OFFSET_KHR:
             thread->error = egl_surface_get_mapped_buffer_attrib(surface, attribute, value);
             CLIENT_UNLOCK();
             return (thread->error == EGL_SUCCESS ? EGL_TRUE : EGL_FALSE );
          default:
             /* Other attributes can only be queried if the surface is unlocked */
             if (surface->is_locked) {
                thread->error = EGL_BAD_ACCESS;
                CLIENT_UNLOCK();
                return EGL_FALSE;
             }
          }
 #endif
          if (!egl_surface_get_attrib(surface, attribute, value))
             thread->error = EGL_BAD_ATTRIBUTE;
       }
       result = (thread->error == EGL_SUCCESS ? EGL_TRUE : EGL_FALSE );
       CLIENT_UNLOCK();
    } else
       result = EGL_FALSE;
    return result;
 }
eglReleaseTexImage()
EGLAPI EGLBoolean EGLAPIENTRY eglReleaseTexImage (EGLDisplay dpy, EGLSurface surf, EGLint buffer)
Definition at line 1428 of file egl_client.c.
 {
    CLIENT_THREAD_STATE_T *thread;
    CLIENT_PROCESS_STATE_T *process;
    EGLBoolean result;
    if (CLIENT_LOCK_AND_GET_STATES(dpy, &thread, &process))
    {
       EGL_SURFACE_T *surface;
       thread->error = EGL_SUCCESS;
       surface = client_egl_get_surface(thread, process, surf);
       if (surface) {
          if (surface->texture_format != EGL_NO_TEXTURE) {
             if (buffer == EGL_BACK_BUFFER) {
                if (surface->type == PBUFFER) {
                   //TODO: not a "bound" pbuffer?
                   RPC_CALL1(eglIntReleaseTexImage_impl,
                      thread,
                      EGLINTRELEASETEXIMAGE_ID,
                      surface->serverbuffer);
                } else {
                   thread->error = EGL_BAD_SURFACE;
                   result = EGL_FALSE;
                }
             } else {
                thread->error = EGL_BAD_PARAMETER;
                result = EGL_FALSE;
             }
          } else {
             thread->error = EGL_BAD_MATCH;
             result = EGL_FALSE;
          }
       }
       result = (thread->error == EGL_SUCCESS ? EGL_TRUE : EGL_FALSE );
       CLIENT_UNLOCK();
    } else
       result = EGL_FALSE;
    return result;
 }
eglReleaseThread()
EGLAPI EGLBoolean EGLAPIENTRY eglReleaseThread (void)
Definition at line 1203 of file egl_client.c.
Referenced by deinit().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    bool destroy = false;
    vcos_log_trace("eglReleaseThread start.");
    CLIENT_LOCK();
    {
       CLIENT_PROCESS_STATE_T *process = CLIENT_GET_PROCESS_STATE();
       if (process) {
          egl_current_release(process, &thread->opengl);
          egl_current_release(process, &thread->openvg);
 #ifdef RPC_LIBRARY
          /* TODO: not thread safe */
          const KHRONOS_FUNC_TABLE_T *func_table = khronos_server_lock_func_table(client_library_get_connection());
          if (func_table) {
             func_table->khrn_misc_rpc_flush_impl();
          }
          khronos_server_unlock_func_table();
 #else
          RPC_FLUSH(thread);
 #endif
 #ifndef RPC_DIRECT_MULTI
             //move it to khronos_exit()
          client_try_unload_server(process);
 #endif
          thread->error = EGL_SUCCESS;
          destroy = true;
       }
    }
    CLIENT_UNLOCK();
    if (destroy)
       platform_hint_thread_finished();
    vcos_log_trace("eglReleaseThread end.");
    return EGL_TRUE;
    //TODO free thread state?
 }
eglSurfaceAttrib()
EGLAPI EGLBoolean EGLAPIENTRY eglSurfaceAttrib (EGLDisplay dpy, EGLSurface surf, EGLint attribute, EGLint value)
Definition at line 1350 of file egl_client.c.
 {
    CLIENT_THREAD_STATE_T *thread;
    CLIENT_PROCESS_STATE_T *process;
    EGLBoolean result;
    if (CLIENT_LOCK_AND_GET_STATES(dpy, &thread, &process))
    {
       EGL_SURFACE_T *surface;
       thread->error = EGL_SUCCESS;
       surface = client_egl_get_surface(thread, process, surf);
       if (surface)
          thread->error = egl_surface_set_attrib(surface, attribute, value);
       result = (thread->error == EGL_SUCCESS ? EGL_TRUE : EGL_FALSE );
       CLIENT_UNLOCK();
    } else
       result = EGL_FALSE;
    return result;
 }
eglSwapBuffers()
EGLAPI EGLBoolean EGLAPIENTRY eglSwapBuffers (EGLDisplay dpy, EGLSurface surf)
Definition at line 2226 of file egl_client.c.
References EGL_FALSE, and UNREACHABLE.
Referenced by gx_priv_flush(), and render().
 {
 #ifdef DIRECT_RENDERING
    /* Wrapper layer shouldn't call eglSwapBuffers */
    UNREACHABLE();
    return EGL_FALSE;
 #else
    CLIENT_THREAD_STATE_T *thread;
    CLIENT_PROCESS_STATE_T *process;
    EGLBoolean result;
    vcos_log_trace("eglSwapBuffers start. dpy=%d. surf=%d.", (int)dpy, (int)surf);
    if (CLIENT_LOCK_AND_GET_STATES(dpy, &thread, &process))
    {
       EGL_SURFACE_T *surface;
       thread->error = EGL_SUCCESS;
       surface = client_egl_get_surface(thread, process, surf);
       vcos_log_trace("eglSwapBuffers get surface %x",(int)surface);
       if (surface) {
 #if !(EGL_KHR_lock_surface)
          /* Surface to be displayed must be bound to current context and API */
          /* This check is disabled if we have the EGL_KHR_lock_surface extension */
          if (thread->bound_api == EGL_OPENGL_ES_API && surface != thread->opengl.draw && surface != thread->opengl.read
           || thread->bound_api == EGL_OPENVG_API    && surface != thread->openvg.draw) {
             thread->error = EGL_BAD_SURFACE;
          } else
 #endif
          {
             if (surface->type == WINDOW) {
                uint32_t width, height, swapchain_count;
                /* the egl spec says eglSwapBuffers is supposed to be a no-op for
                 * single-buffered surfaces, but we pass it through as the
                 * semantics are potentially useful:
                 * - any ops outstanding on the surface are flushed
                 * - the surface is resubmitted to the display once the
                 *   outstanding ops complete (for displays which have their own
                 *   memory, this is useful)
                 * - the surface is resized to fit the backing window */
                // We need to check at this point if the surface has resized, and pass
                // size data down to the server.
                width = surface->width;
                height = surface->height;
                platform_get_dimensions(dpy, surface->win,
                      &width, &height, &swapchain_count);
                if((width!=surface->width)||(height!=surface->height)) {
                   uint32_t handle = platform_get_handle(dpy, surface->win);
                   surface->internal_handle = handle;
                   surface->width = width;
                   surface->height = height;
                }
                vcos_log_trace("eglSwapBuffers comparison: %d %d, %d %d",
                         surface->width, surface->base_width, surface->height,
                         surface->base_height);
                /* TODO: raise EGL_BAD_ALLOC if we try to enlarge window and then run out of memory
                   if (surface->width <= surface->base_width && surface->height <= surface->base_height ||
                   surface->width <= surface->base_height && surface->height <= surface->base_width)
                   */
                // We don't call flush_current_api() here because it's only relevant
                // for pixmap surfaces (eglIntSwapBuffers takes care of flushing on
                // the server side).
                platform_surface_update(surface->internal_handle);
                vcos_log_trace("eglSwapBuffers server call");
                RPC_CALL6(eglIntSwapBuffers_impl,
                      thread,
                      EGLINTSWAPBUFFERS_ID,
                      RPC_UINT(surface->serverbuffer),
                      RPC_UINT(surface->width),
                      RPC_UINT(surface->height),
                      RPC_UINT(surface->internal_handle),
                      RPC_UINT(surface->swap_behavior == EGL_BUFFER_PRESERVED ? 1 : 0),
                      RPC_UINT(khrn_platform_get_window_position(surface->win)));
                RPC_FLUSH(thread);
 #ifdef ANDROID
                CLIENT_UNLOCK();
                platform_dequeue(dpy, surface->win);
                CLIENT_LOCK();
 #else
 #  ifdef KHRONOS_EGL_PLATFORM_OPENWFC
                wfc_stream_await_buffer((WFCNativeStreamType) surface->internal_handle);
 #  else
 #     ifndef RPC_LIBRARY
                if (surface->buffers > 1) {
                   //TODO implement khan (khronos async notification) receiver for linux
 #        ifndef RPC_DIRECT_MULTI
                   vcos_log_trace("eglSwapBuffers waiting for semaphore");
                   khronos_platform_semaphore_acquire(&surface->avail_buffers);
 #        endif
                }
 #     endif // RPC_LIBRARY
 #  endif // KHRONOS_EGL_PLATFORM_OPENWFC
 #endif   /* ANDROID */
             } else {
 #ifdef KHRN_COMMAND_MODE_DISPLAY
 //Check for single buffered windows surface (and VG) in which case call vgFlush to allow screen update for command mode screens
                EGL_SURFACE_T *surface = CLIENT_GET_THREAD_STATE()->openvg.draw;
                if (surface->type == WINDOW && surface->buffers==1 && thread->bound_api == EGL_OPENVG_API) {
                   vgFlush();
                }
 #endif
             }
             // else do nothing. eglSwapBuffers has no effect on pixmap or pbuffer surfaces
          }
       }
       result = (thread->error == EGL_SUCCESS);
       CLIENT_UNLOCK();
    }
    else
       result = EGL_FALSE;
    vcos_log_trace("eglSwapBuffers end");
    return result;
 #endif // DIRECT_RENDERING
 }
eglSwapInterval()
EGLAPI EGLBoolean EGLAPIENTRY eglSwapInterval (EGLDisplay dpy, EGLint interval)
Definition at line 1473 of file egl_client.c.
 {
    CLIENT_THREAD_STATE_T *thread;
    CLIENT_PROCESS_STATE_T *process;
    EGLBoolean result;
    if (CLIENT_LOCK_AND_GET_STATES(dpy, &thread, &process))
    {
       EGL_CURRENT_T *current;
       EGL_SURFACE_T *surface;
       /* the spec says "the window associated with the current context". it
        * doesn't explicitly say "the current context for the current rendering
        * api" (which it does in most other places), but i'm assuming that's what
        * it means */
       if (thread->bound_api == EGL_OPENVG_API)
          current = &thread->openvg;
       else
          current = &thread->opengl;
       surface = current->draw;
       if (surface) {
          if (surface->type == WINDOW) {
             if (interval < EGL_CONFIG_MIN_SWAP_INTERVAL)
                interval = EGL_CONFIG_MIN_SWAP_INTERVAL;
             if (interval > EGL_CONFIG_MAX_SWAP_INTERVAL)
                interval = EGL_CONFIG_MAX_SWAP_INTERVAL;
             surface->swap_interval = (uint32_t) interval;
          }
          RPC_CALL2(eglIntSwapInterval_impl,
             thread,
             EGLINTSWAPINTERVAL_ID,
             surface->serverbuffer,
             surface->swap_interval);
          /* TODO: should we raise an error if it's not a window
           * surface, or silently ignore it?
           */
          thread->error = EGL_SUCCESS;
          result = EGL_TRUE;
       } else {
          /*
          "If there is no current context
          on the calling thread, a EGL BAD CONTEXT error is generated. If there is no surface
          bound to the current context, a EGL BAD SURFACE error is generated."
          TODO
          This doesn't make sense to me - the current context always has surfaces
          bound to it, so which error do we raise?
          */
          thread->error = EGL_BAD_SURFACE;
          result = EGL_FALSE;
       }
       CLIENT_UNLOCK();
    }
    else
       result = EGL_FALSE;
    return result;
 }
eglTerminate()
EGLAPI EGLBoolean EGLAPIENTRY eglTerminate (EGLDisplay dpy)
Definition at line 309 of file egl_client.c.
Referenced by deinit(), and raspitexutil_gl_term().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    vcos_log_trace("eglTerminate start. dpy=%d", (int)dpy);
 #ifdef RPC_DIRECT_MULTI
     return true;  //it is moved to khronos_exit
 #else
    {
       EGLBoolean result;
       CLIENT_LOCK();
       {
          CLIENT_PROCESS_STATE_T *process = client_egl_get_process_state(thread, dpy, EGL_FALSE);
          if (process) {
             client_process_state_term(process);
             thread->error = EGL_SUCCESS;
             result = EGL_TRUE;
             client_try_unload_server(process);
          } else
             result = EGL_FALSE;
       }
       CLIENT_UNLOCK();
       vcos_log_trace("eglTerminate end. dpy=%d", (int)dpy);
       vcos_log_unregister(&egl_client_log_cat);
       return result;
    }
 #endif
 }
eglWaitClient()
EGLAPI EGLBoolean EGLAPIENTRY eglWaitClient (void)
Definition at line 1179 of file egl_client.c.
Referenced by graphics_delete_resource(), and graphics_update_end().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    //TODO: "If the surface associated with the calling thread's current context is no
    //longer valid, EGL_FALSE is returned and an EGL_BAD_CURRENT_SURFACE error is
    //generated".
    (void) RPC_INT_RES(RPC_CALL2_RES(eglIntFlushAndWait_impl,
                  thread,
                  EGLINTFLUSHANDWAIT_ID,
                  RPC_UINT(thread->bound_api == EGL_OPENGL_ES_API),
                  RPC_UINT(thread->bound_api == EGL_OPENVG_API)));   // return unimportant - read is just to cause blocking
    if (thread->bound_api == EGL_OPENGL_ES_API)
       egl_gl_flush_callback(true);
    else
       egl_vg_flush_callback(true);
    thread->error = EGL_SUCCESS;
    return EGL_TRUE;
 }
eglWaitGL()
EGLAPI EGLBoolean EGLAPIENTRY eglWaitGL (void)
Definition at line 2183 of file egl_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    EGLBoolean result;
    //TODO: "If the surface associated with the calling thread's current context is no
    //longer valid, EGL_FALSE is returned and an EGL_BAD_CURRENT_SURFACE error is
    //generated".
    (void) RPC_INT_RES(RPC_CALL2_RES(eglIntFlushAndWait_impl,
                  thread,
                  EGLINTFLUSHANDWAIT_ID,
                  RPC_UINT(true),
                  RPC_UINT(false)));   // return unimportant - read is just to cause blocking
    egl_gl_flush_callback(true);
    thread->error = EGL_SUCCESS;
    result = EGL_TRUE;
    return result;
 }
eglWaitNative()
EGLAPI EGLBoolean EGLAPIENTRY eglWaitNative (EGLint engine)
Definition at line 2205 of file egl_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    EGLBoolean result;
    //TODO: "If the surface associated with the calling thread's current context is no
    //longer valid, EGL_FALSE is returned and an EGL_BAD_CURRENT_SURFACE error is
    //generated".
    if (engine == EGL_CORE_NATIVE_ENGINE) {
    //TODO: currently nothing we can do here
       thread->error = EGL_SUCCESS;
       result = EGL_TRUE;
    } else {
       thread->error = EGL_BAD_PARAMETER;
       result = EGL_FALSE;
    }
    return result;
 }
Variable Documentation
egl_client_log_cat
VCOS_LOG_CAT_T egl_client_log_cat
Definition at line 159 of file egl_client.c.