VideoCore Library: interface/vcos/generic/vcos_mem_from_malloc.h File Reference
vcos_mem_from_malloc.h File Reference
Functions
VCOSPRE_ void *VCOSPOST_ vcos_generic_mem_alloc (VCOS_UNSIGNED sz, const char *desc)
VCOSPRE_ void *VCOSPOST_ vcos_generic_mem_calloc (VCOS_UNSIGNED count, VCOS_UNSIGNED sz, const char *descr)
VCOSPRE_ void VCOSPOST_ vcos_generic_mem_free (void *ptr)
VCOSPRE_ void *VCOSPOST_ vcos_generic_mem_alloc_aligned (VCOS_UNSIGNED sz, VCOS_UNSIGNED align, const char *desc)
Detailed Description
Create the vcos malloc API from a regular system malloc/free library.
The API lets callers specify an alignment.
Under VideoCore this is not needed, as we can simply use the rtos_malloc routines. But on host platforms that won't be the case.
Definition in file vcos_mem_from_malloc.h.
Function Documentation
vcos_generic_mem_alloc()
VCOSPRE_ void* VCOSPOST_ vcos_generic_mem_alloc (VCOS_UNSIGNED sz, const char * desc)
Definition at line 73 of file vcos_mem_from_malloc.c.
References MIN_ALIGN, and vcos_generic_mem_alloc_aligned().
 {
    return vcos_generic_mem_alloc_aligned(size,MIN_ALIGN,desc);
 }
vcos_generic_mem_alloc_aligned()
VCOSPRE_ void* VCOSPOST_ vcos_generic_mem_alloc_aligned (VCOS_UNSIGNED sz, VCOS_UNSIGNED align, const char * desc)
Definition at line 52 of file vcos_mem_from_malloc.c.
References _vcos_platform_malloc, malloc_header_s::description, malloc_header_s::guardword, GUARDWORDHEAP, NULL, malloc_header_s::ptr, malloc_header_s::size, and VCOS_ALIGN_UP.
Referenced by vcos_generic_mem_alloc(), and vcos_generic_mem_calloc().
 {
    int local_align = align == 0 ? 1 : align;
    int required_size = size + local_align + sizeof(MALLOC_HEADER_T);
    void *ptr = _vcos_platform_malloc(required_size);
    void *ret = NULL;
    MALLOC_HEADER_T *h;
    if (ptr)
    {
       ret = (void *)VCOS_ALIGN_UP(((char *)ptr)+sizeof(MALLOC_HEADER_T), local_align);
       h = ((MALLOC_HEADER_T *)ret)-1;
       h->size = size;
       h->description = desc;
       h->guardword = GUARDWORDHEAP;
       h->ptr = ptr;
    }
    return ret;
 }
vcos_generic_mem_calloc()
VCOSPRE_ void* VCOSPOST_ vcos_generic_mem_calloc (VCOS_UNSIGNED count, VCOS_UNSIGNED sz, const char * descr)
Definition at line 78 of file vcos_mem_from_malloc.c.
References MIN_ALIGN, malloc_header_s::ptr, and vcos_generic_mem_alloc_aligned().
 {
    uint32_t size = count*sz;
    void *ptr = vcos_generic_mem_alloc_aligned(size,MIN_ALIGN,desc);
    if (ptr)
    {
       memset(ptr, 0, size);
    }
    return ptr;
 }
vcos_generic_mem_free()
VCOSPRE_ void VCOSPOST_ vcos_generic_mem_free (void * ptr)
Definition at line 89 of file vcos_mem_from_malloc.c.
References _vcos_platform_free, malloc_header_s::guardword, GUARDWORDHEAP, malloc_header_s::ptr, and vcos_assert.
 {
    MALLOC_HEADER_T *h;
    if (! ptr) return;
    h = ((MALLOC_HEADER_T *)ptr)-1;
    vcos_assert(h->guardword == GUARDWORDHEAP);
    _vcos_platform_free(h->ptr);
 }