VideoCore Library: interface/khronos/glxx/glxx_client.h File Reference
glxx_client.h File Reference
#include "interface/khronos/common/khrn_client.h"
#include "interface/khronos/common/khrn_client_platform.h"
#include "interface/khronos/common/khrn_client_cache.h"
#include "interface/khronos/egl/egl_client_context.h"
#include "interface/khronos/glxx/glxx_int_attrib.h"
#include "interface/khronos/glxx/glxx_int_config.h"
Classes
struct buffer_info
struct GLXX_CLIENT_STATE_T
Macros
#define GLXX_GET_CLIENT_STATE(thread) glxx_get_client_state(thread)
#define GLXX_API_11 (1<<(OPENGL_ES_11))
#define GLXX_API_20 (1<<(OPENGL_ES_20))
#define GLXX_API_11_OR_20 (GLXX_API_11|GLXX_API_20)
#define IS_OPENGLES_11(thread) is_opengles_api(thread, GLXX_API_11)
#define IS_OPENGLES_20(thread) is_opengles_api(thread, GLXX_API_20)
#define IS_OPENGLES_11_OR_20(thread) is_opengles_api(thread, GLXX_API_11_OR_20)
#define IS_OPENGLES_API(thread, api) is_opengles_api(thread, api)
Typedefs
typedef void(* GL_RENDER_CALLBACK_T) (void)
typedef void(* GL_FLUSH_CALLBACK_T) (bool wait)
typedef struct buffer_info GLXX_BUFFER_INFO_T
Functions
int gl11_client_state_init (GLXX_CLIENT_STATE_T *state)
int gl20_client_state_init (GLXX_CLIENT_STATE_T *state)
void glxx_client_state_free (GLXX_CLIENT_STATE_T *state)
void glxx_buffer_info_get (GLXX_CLIENT_STATE_T *state, GLenum target, GLXX_BUFFER_INFO_T *buffer)
void glxx_buffer_info_set (GLXX_CLIENT_STATE_T *state, GLenum target, GLXX_BUFFER_INFO_T *buffer)
void glxx_set_error (GLXX_CLIENT_STATE_T *state, GLenum error)
void glxx_set_error_api (uint32_t api, GLenum error)
void glintAttribPointer (uint32_t api, uint32_t indx, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const GLvoid *ptr)
void glintAttrib (uint32_t api, uint32_t indx, float x, float y, float z, float w)
void glintColor (float red, float green, float blue, float alpha)
void glintAttribEnable (uint32_t api, uint32_t indx, bool enabled)
void * glintAttribGetPointer (uint32_t api, uint32_t indx)
Macro Definition Documentation
GLXX_API_11
#define GLXX_API_11 (1<<(OPENGL_ES_11))
Definition at line 132 of file glxx_client.h.
Referenced by glGetPointerv(), glMultiTexCoord4f(), glMultiTexCoord4x(), glNormal3f(), glNormal3x(), and glPointSizex().
GLXX_API_11_OR_20
#define GLXX_API_11_OR_20 (GLXX_API_11|GLXX_API_20)
Definition at line 134 of file glxx_client.h.
GLXX_API_20
#define GLXX_API_20 (1<<(OPENGL_ES_20))
Definition at line 133 of file glxx_client.h.
Referenced by glDisableVertexAttribArray(), glEnableVertexAttribArray(), glGetVertexAttribPointerv(), glVertexAttrib1f(), glVertexAttrib1fv(), glVertexAttrib2f(), glVertexAttrib2fv(), glVertexAttrib3f(), glVertexAttrib3fv(), glVertexAttrib4f(), and glVertexAttrib4fv().
GLXX_GET_CLIENT_STATE
#define GLXX_GET_CLIENT_STATE (thread) glxx_get_client_state(thread)
Definition at line 119 of file glxx_client.h.
IS_OPENGLES_11
#define IS_OPENGLES_11 (thread) is_opengles_api(thread, GLXX_API_11)
Definition at line 141 of file glxx_client.h.
IS_OPENGLES_11_OR_20
#define IS_OPENGLES_11_OR_20 (thread) is_opengles_api(thread, GLXX_API_11_OR_20)
Definition at line 143 of file glxx_client.h.
IS_OPENGLES_20
#define IS_OPENGLES_20 (thread) is_opengles_api(thread, GLXX_API_20)
Definition at line 142 of file glxx_client.h.
IS_OPENGLES_API
#define IS_OPENGLES_API (thread, api) is_opengles_api(thread, api)
Definition at line 144 of file glxx_client.h.
Typedef Documentation
GL_FLUSH_CALLBACK_T
typedef void(* GL_FLUSH_CALLBACK_T) (bool wait)
Definition at line 51 of file glxx_client.h.
GL_RENDER_CALLBACK_T
typedef void(* GL_RENDER_CALLBACK_T) (void)
Definition at line 44 of file glxx_client.h.
GLXX_BUFFER_INFO_T
typedef struct buffer_info GLXX_BUFFER_INFO_T
Function Documentation
gl11_client_state_init()
int gl11_client_state_init (GLXX_CLIENT_STATE_T * state)
Definition at line 5527 of file glxx_client.c.
References OPENGL_ES_11, and GLXX_CLIENT_STATE_T::type.
 {
    state->type = OPENGL_ES_11;
    //perform common initialisation
    glxx_client_state_init(state);
    //gl2.0 specific
    state->active_texture.client = GL_TEXTURE0;
    state->active_texture.server = GL_TEXTURE0;
    gl11_attrib_init(state->attrib);
 #ifdef GLXX_NO_VERTEX_CACHE
    return 1;
 #else
    return khrn_cache_init(&state->cache);
 #endif
 }
gl20_client_state_init()
int gl20_client_state_init (GLXX_CLIENT_STATE_T * state)
Definition at line 5547 of file glxx_client.c.
References OPENGL_ES_20, and GLXX_CLIENT_STATE_T::type.
 {
    state->type = OPENGL_ES_20;
    //perform common initialisation
    glxx_client_state_init(state);
    //gl2.0 specific
    state->default_framebuffer = true;
    gl20_attrib_init(state->attrib);
 #ifdef GLXX_NO_VERTEX_CACHE
    return 1;
 #else
    return khrn_cache_init(&state->cache);
 #endif
 }
glintAttrib()
void glintAttrib (uint32_t api, uint32_t indx, float x, float y, float z, float w)
Definition at line 5639 of file glxx_client.c.
Referenced by glMultiTexCoord4f(), glMultiTexCoord4x(), glNormal3f(), glNormal3x(), glPointSizex(), glVertexAttrib1f(), glVertexAttrib1fv(), glVertexAttrib2f(), glVertexAttrib2fv(), glVertexAttrib3f(), glVertexAttrib3fv(), glVertexAttrib4f(), and glVertexAttrib4fv().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_API(thread, api))
    {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       if (attrib_translate(state, &indx))
       {
          vcos_assert(indx < GLXX_CONFIG_MAX_VERTEX_ATTRIBS);
          state->attrib[indx].value[0] = x;
          state->attrib[indx].value[1] = y;
          state->attrib[indx].value[2] = z;
          state->attrib[indx].value[3] = w;
          RPC_CALL6(glintAttrib_impl,
                    thread,
                    GLINTATTRIB_ID,
                    RPC_UINT(api),
                    RPC_UINT(indx),
                    RPC_FLOAT(x),
                    RPC_FLOAT(y),
                    RPC_FLOAT(z),
                    RPC_FLOAT(w));
       }
    }
 }
glintAttribEnable()
void glintAttribEnable (uint32_t api, uint32_t indx, bool enabled)
Definition at line 5692 of file glxx_client.c.
Referenced by glDisableVertexAttribArray(), and glEnableVertexAttribArray().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_API(thread, api))
    {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       if (attrib_translate(state, &indx))
       {
          state->attrib[indx].enabled = enabled;
          RPC_CALL3(glintAttribEnable_impl,
                    thread,
                    GLINTATTRIBENABLE_ID,
                    RPC_UINT(api),
                    RPC_UINT(indx),
                    RPC_BOOLEAN(enabled));
       }
    }
 }
glintAttribGetPointer()
void* glintAttribGetPointer (uint32_t api, uint32_t indx)
Definition at line 5712 of file glxx_client.c.
Referenced by glGetPointerv(), and glGetVertexAttribPointerv().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_API(thread, api))
    {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       if (attrib_translate(state, &indx))
          return (void *)state->attrib[indx].pointer;
    }
    return NULL;
 }
glintAttribPointer()
void glintAttribPointer (uint32_t api, uint32_t indx, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const GLvoid * ptr)
Definition at line 5610 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_API(thread, api))
    {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       if (attrib_translate(state, &indx))
       {
          state->attrib[indx].size = size;
          state->attrib[indx].type = type;
          state->attrib[indx].normalized = normalized;
          state->attrib[indx].stride = stride;
          state->attrib[indx].pointer = ptr;
          state->attrib[indx].buffer = state->bound_buffer.array;
          RPC_CALL7(glintAttribPointer_impl,
                    thread,
                    GLINTATTRIBPOINTER_ID,
                    RPC_UINT(api),
                    RPC_UINT(indx),
                    RPC_INT(size),
                    RPC_ENUM(type),
                    RPC_BOOLEAN(normalized),
                    RPC_SIZEI(stride),
                    RPC_INTPTR((GLintptr)ptr));
       }
    }
 }
glintColor()
void glintColor (float red, float green, float blue, float alpha)
Definition at line 5670 of file glxx_client.c.
Referenced by glColor4f(), glColor4ub(), and glColor4x().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread))
    {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       state->attrib[GL11_IX_COLOR].value[0] = x;
       state->attrib[GL11_IX_COLOR].value[1] = y;
       state->attrib[GL11_IX_COLOR].value[2] = z;
       state->attrib[GL11_IX_COLOR].value[3] = w;
       RPC_CALL4(glintColor_impl_11,
                 thread,
                 GLINTCOLOR_ID_11,
                 RPC_FLOAT(x),
                 RPC_FLOAT(y),
                 RPC_FLOAT(z),
                 RPC_FLOAT(w));
    }
 }
glxx_buffer_info_get()
void glxx_buffer_info_get (GLXX_CLIENT_STATE_T * state, GLenum target, GLXX_BUFFER_INFO_T * buffer)
Definition at line 173 of file glxx_client.c.
 {
    GLuint buffer = get_bound_buffer(state, target);
    memset(buffer_info,0,sizeof(GLXX_BUFFER_INFO_T));
    buffer_info->id = 0;
    if(buffer != 0)
    {
       GLXX_BUFFER_INFO_T *stored = khrn_pointer_map_lookup(&state->buffers, buffer);
       if(stored)
          *buffer_info = *stored;
    }
 }
glxx_buffer_info_set()
void glxx_buffer_info_set (GLXX_CLIENT_STATE_T * state, GLenum target, GLXX_BUFFER_INFO_T * buffer)
Definition at line 155 of file glxx_client.c.
 {
    GLuint buffer = get_bound_buffer(state, target);
    if(buffer != 0)
    {
       GLXX_BUFFER_INFO_T *stored = khrn_pointer_map_lookup(&state->buffers, buffer);
       if(!stored)
       {
          stored = khrn_platform_malloc(sizeof(GLXX_BUFFER_INFO_T), "GLXX_BUFFER_INFO_T");
          khrn_pointer_map_insert(&state->buffers, buffer, stored);
       }
       buffer_info->id = buffer;
       //copy into stored
       *stored = *buffer_info;
    }
 }
glxx_client_state_free()
void glxx_client_state_free (GLXX_CLIENT_STATE_T * state)
Definition at line 5574 of file glxx_client.c.
References GLXX_CLIENT_STATE_T::buffers.
 {
    khrn_pointer_map_iterate(&state->buffers, callback_delete_buffer_info, NULL);
    khrn_pointer_map_term(&state->buffers);
 #ifndef GLXX_NO_VERTEX_CACHE
    khrn_cache_term(&state->cache);
 #endif
    khrn_platform_free(state);
 }
glxx_set_error()
void glxx_set_error (GLXX_CLIENT_STATE_T * state, GLenum error)
Definition at line 116 of file glxx_client.c.
References set_error.
 {
    set_error(state,error);
 }
glxx_set_error_api()
void glxx_set_error_api (uint32_t api, GLenum error)
Definition at line 121 of file glxx_client.c.
Referenced by glGetPointerv(), glGetVertexAttribPointerv(), and glMultiTexCoord4f().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_API(thread, api))
    {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       glxx_set_error(state, error);
    }
 }