VideoCore Library: host_applications/linux/libs/debug_sym/debug_sym.h File Reference
debug_sym.h File Reference
#include "interface/vcos/vcos.h"
#include "interface/vcos/vcos_stdint.h"
Macros
#define TO_VC_MEM_ADDR(ptr) ((VC_MEM_ADDR_T)(unsigned long)(ptr))
#define ALIAS_NORMAL(x) ((VC_MEM_ADDR_T)(((unsigned long)(x)&~0xc0000000uL)|0x00000000uL))
#define IS_ALIAS_PERIPHERAL(x) (((unsigned long)(x)>>29)==0x3uL)
Typedefs
typedef struct opaque_vc_mem_access_handle_t * VC_MEM_ACCESS_HANDLE_T
typedef uint32_t VC_MEM_ADDR_T
typedef uint32_t VC_MEM_SIZE_T
typedef uint32_t VC_MEM_PTRDIFF_T
Functions
int OpenVideoCoreMemory (VC_MEM_ACCESS_HANDLE_T *handle)
int OpenVideoCoreMemoryFile (const char *filename, VC_MEM_ACCESS_HANDLE_T *vcHandlePtr)
int OpenVideoCoreMemoryFileWithOffset (const char *filename, VC_MEM_ACCESS_HANDLE_T *vcHandlePtr, size_t loadOffset)
unsigned NumVideoCoreSymbols (VC_MEM_ACCESS_HANDLE_T handle)
int GetVideoCoreSymbol (VC_MEM_ACCESS_HANDLE_T handle, unsigned idx, char *nameBuf, size_t nameBufSize, VC_MEM_ADDR_T *vcMemAddr, size_t *vcMemSize)
int LookupVideoCoreSymbol (VC_MEM_ACCESS_HANDLE_T handle, const char *symbol, VC_MEM_ADDR_T *vcMemAddr, size_t *vcMemSize)
int LookupVideoCoreUInt32Symbol (VC_MEM_ACCESS_HANDLE_T handle, const char *symbol, VC_MEM_ADDR_T *vcMemAddr)
int ReadVideoCoreMemory (VC_MEM_ACCESS_HANDLE_T handle, void *buf, VC_MEM_ADDR_T vcMemAddr, size_t numBytes)
VCOS_STATIC_INLINE int ReadVideoCoreUInt32 (VC_MEM_ACCESS_HANDLE_T handle, uint32_t *val, VC_MEM_ADDR_T vcMemAddr)
int ReadVideoCoreMemoryBySymbol (VC_MEM_ACCESS_HANDLE_T vcHandle, const char *symbol, void *buf, size_t numBytes)
VCOS_STATIC_INLINE int ReadVideoCoreUInt32BySymbol (VC_MEM_ACCESS_HANDLE_T handle, const char *symbol, uint32_t *val)
int ReadVideoCoreStringBySymbol (VC_MEM_ACCESS_HANDLE_T handle, const char *symbol, char *buf, size_t bufSize)
int WriteVideoCoreMemory (VC_MEM_ACCESS_HANDLE_T handle, void *buf, VC_MEM_ADDR_T vcMemAddr, size_t numBytes)
VCOS_STATIC_INLINE int WriteVideoCoreUInt32 (VC_MEM_ACCESS_HANDLE_T handle, uint32_t val, VC_MEM_ADDR_T vcMemAddr)
void CloseVideoCoreMemory (VC_MEM_ACCESS_HANDLE_T handle)
VC_MEM_ADDR_T GetVideoCoreMemoryBase (VC_MEM_ACCESS_HANDLE_T handle)
VC_MEM_SIZE_T GetVideoCoreMemorySize (VC_MEM_ACCESS_HANDLE_T handle)
VC_MEM_ADDR_T GetVideoCoreMemoryPhysicalAddress (VC_MEM_ACCESS_HANDLE_T handle)
Macro Definition Documentation
ALIAS_NORMAL
#define ALIAS_NORMAL (x) ((VC_MEM_ADDR_T)(((unsigned long)(x)&~0xc0000000uL)|0x00000000uL))
Definition at line 61 of file debug_sym.h.
IS_ALIAS_PERIPHERAL
#define IS_ALIAS_PERIPHERAL (x) (((unsigned long)(x)>>29)==0x3uL)
Definition at line 62 of file debug_sym.h.
TO_VC_MEM_ADDR
#define TO_VC_MEM_ADDR (ptr) ((VC_MEM_ADDR_T)(unsigned long)(ptr))
Definition at line 51 of file debug_sym.h.
Referenced by OpenVideoCoreMemoryFileWithOffset().
Typedef Documentation
VC_MEM_ACCESS_HANDLE_T
typedef struct opaque_vc_mem_access_handle_t* VC_MEM_ACCESS_HANDLE_T
Definition at line 42 of file debug_sym.h.
VC_MEM_ADDR_T
typedef uint32_t VC_MEM_ADDR_T
Definition at line 47 of file debug_sym.h.
VC_MEM_PTRDIFF_T
typedef uint32_t VC_MEM_PTRDIFF_T
Definition at line 49 of file debug_sym.h.
VC_MEM_SIZE_T
typedef uint32_t VC_MEM_SIZE_T
Definition at line 48 of file debug_sym.h.
Function Documentation
CloseVideoCoreMemory()
void CloseVideoCoreMemory (VC_MEM_ACCESS_HANDLE_T handle)
Definition at line 786 of file debug_sym.c.
References VC_DEBUG_SYMBOL_T::label, opaque_vc_mem_access_handle_t::memFd, opaque_vc_mem_access_handle_t::numSymbols, and opaque_vc_mem_access_handle_t::symbol.
Referenced by WriteVideoCoreUInt32().
 {
     unsigned i;
     if ( vcHandle->symbol )
         for ( i = 0; i < vcHandle->numSymbols; i++ )
             free( (char *)vcHandle->symbol[i].label );
     free( vcHandle->symbol );
     if ( vcHandle->memFd >= 0 )
         close( vcHandle->memFd );
     free( vcHandle );
 }
GetVideoCoreMemoryBase()
VC_MEM_ADDR_T GetVideoCoreMemoryBase (VC_MEM_ACCESS_HANDLE_T handle)
Definition at line 806 of file debug_sym.c.
References opaque_vc_mem_access_handle_t::vcMemBase.
Referenced by WriteVideoCoreUInt32().
 {
     return vcHandle->vcMemBase;
 }
GetVideoCoreMemoryPhysicalAddress()
VC_MEM_ADDR_T GetVideoCoreMemoryPhysicalAddress (VC_MEM_ACCESS_HANDLE_T handle)
Definition at line 828 of file debug_sym.c.
References opaque_vc_mem_access_handle_t::vcMemPhys.
Referenced by WriteVideoCoreUInt32().
 {
     return vcHandle->vcMemPhys;
 }
GetVideoCoreMemorySize()
VC_MEM_SIZE_T GetVideoCoreMemorySize (VC_MEM_ACCESS_HANDLE_T handle)
Definition at line 817 of file debug_sym.c.
References opaque_vc_mem_access_handle_t::vcMemSize.
Referenced by WriteVideoCoreUInt32().
 {
     return vcHandle->vcMemSize;
 }
GetVideoCoreSymbol()
int GetVideoCoreSymbol (VC_MEM_ACCESS_HANDLE_T handle, unsigned idx, char * nameBuf, size_t nameBufSize, VC_MEM_ADDR_T * vcMemAddr, size_t * vcMemSize)
Definition at line 458 of file debug_sym.c.
References VC_DEBUG_SYMBOL_T::addr, VC_DEBUG_SYMBOL_T::label, NULL, opaque_vc_mem_access_handle_t::numSymbols, VC_DEBUG_SYMBOL_T::size, and opaque_vc_mem_access_handle_t::symbol.
Referenced by LookupVideoCoreSymbol().
 {
     VC_DEBUG_SYMBOL_T   *sym;
     if ( idx >= vcHandle->numSymbols )
     {
         return -EINVAL;
     }
     sym = &vcHandle->symbol[ idx ];
     strncpy( labelBuf, sym->label, labelBufSize );
     labelBuf[labelBufSize - 1] = '\0';
     if ( vcMemAddr != NULL )
     {
         *vcMemAddr = (VC_MEM_ADDR_T)sym->addr;
     }
     if ( vcMemSize != NULL )
     {
         *vcMemSize = sym->size;
     }
     return 0;
 }
LookupVideoCoreSymbol()
int LookupVideoCoreSymbol (VC_MEM_ACCESS_HANDLE_T handle, const char * symbol, VC_MEM_ADDR_T * vcMemAddr, size_t * vcMemSize)
Definition at line 492 of file debug_sym.c.
References DBG, GetVideoCoreSymbol(), NULL, and opaque_vc_mem_access_handle_t::numSymbols.
Referenced by LookupVideoCoreUInt32Symbol(), ReadVideoCoreMemoryBySymbol(), and ReadVideoCoreStringBySymbol().
 {
     unsigned        idx;
     char            symName[ 64 ];
     VC_MEM_ADDR_T   symAddr = 0;
     size_t          symSize = 0;
     for ( idx = 0; idx < vcHandle->numSymbols; idx++ )
     {
         GetVideoCoreSymbol( vcHandle, idx, symName, sizeof( symName ), &symAddr, &symSize );
         if ( strcmp( symbol, symName ) == 0 )
         {
             if ( vcMemAddr != NULL )
             {
                 *vcMemAddr = symAddr;
             }
             if ( vcMemSize != 0 )
             {
                 *vcMemSize = symSize;
             }
             DBG( "%s found, addr = 0x%08x size = %zu", symbol, symAddr, symSize );
             return 1;
         }
     }
     if ( vcMemAddr != NULL )
     {
         *vcMemAddr = 0;
     }
     if ( vcMemSize != 0 )
     {
         *vcMemSize = 0;
     }
     DBG( "%s not found", symbol );
     return 0;
 }
LookupVideoCoreUInt32Symbol()
int LookupVideoCoreUInt32Symbol (VC_MEM_ACCESS_HANDLE_T handle, const char * symbol, VC_MEM_ADDR_T * vcMemAddr)
Definition at line 537 of file debug_sym.c.
References ERR, LookupVideoCoreSymbol(), and opaque_vc_mem_access_handle_t::vcMemSize.
 {
     size_t  vcMemSize;
     if ( !LookupVideoCoreSymbol( vcHandle, symbol, vcMemAddr, &vcMemSize ))
     {
         return 0;
     }
     if ( vcMemSize != sizeof( uint32_t ))
     {
         ERR( "Symbol: '%s' has a size of %zu, expecting %zu", symbol, vcMemSize, sizeof( uint32_t ));
         return 0;
     }
     return 1;
 }
NumVideoCoreSymbols()
unsigned NumVideoCoreSymbols (VC_MEM_ACCESS_HANDLE_T handle)
Definition at line 447 of file debug_sym.c.
References opaque_vc_mem_access_handle_t::numSymbols.
 {
     return vcHandle->numSymbols;
 }
OpenVideoCoreMemory()
int OpenVideoCoreMemory (VC_MEM_ACCESS_HANDLE_T * handle)
Definition at line 131 of file debug_sym.c.
References NULL, and OpenVideoCoreMemoryFile().
 {
     return OpenVideoCoreMemoryFile( NULL, vcHandlePtr );
 }
OpenVideoCoreMemoryFile()
int OpenVideoCoreMemoryFile (const char * filename, VC_MEM_ACCESS_HANDLE_T * vcHandlePtr)
Definition at line 175 of file debug_sym.c.
References OpenVideoCoreMemoryFileWithOffset().
Referenced by OpenVideoCoreMemory().
 {
     return OpenVideoCoreMemoryFileWithOffset( filename, vcHandlePtr, 0 );
 }
OpenVideoCoreMemoryFileWithOffset()
int OpenVideoCoreMemoryFileWithOffset (const char * filename, VC_MEM_ACCESS_HANDLE_T * vcHandlePtr, size_t loadOffset)
Definition at line 180 of file debug_sym.c.
References VC_DEBUG_SYMBOL_T::addr, DBG, ERR, VC_DEBUG_SYMBOL_T::label, len, MAX_VC_SIZE, opaque_vc_mem_access_handle_t::memFd, opaque_vc_mem_access_handle_t::memFdBase, NULL, opaque_vc_mem_access_handle_t::numSymbols, ReadVideoCoreMemory(), VC_DEBUG_SYMBOL_T::size, opaque_vc_mem_access_handle_t::symbol, TO_VC_MEM_ADDR, opaque_vc_mem_access_handle_t::use_vc_mem, VC_MEM_IOC_MEM_BASE, VC_MEM_IOC_MEM_LOAD, VC_MEM_IOC_MEM_PHYS_ADDR, VC_MEM_IOC_MEM_SIZE, VC_SYMBOL_BASE_OFFSET, opaque_vc_mem_access_handle_t::vcMemBase, opaque_vc_mem_access_handle_t::vcMemEnd, opaque_vc_mem_access_handle_t::vcMemLoad, opaque_vc_mem_access_handle_t::vcMemPhys, opaque_vc_mem_access_handle_t::vcMemSize, vcos_log_register(), vcos_strdup(), and opaque_vc_mem_access_handle_t::vcSymbolTableOffset.
Referenced by OpenVideoCoreMemoryFile().
 {
     int                     rc = 0;
     VC_MEM_ACCESS_HANDLE_T  newHandle;
     VC_DEBUG_SYMBOL_T       debug_sym;
     VC_MEM_ADDR_T           symAddr;
     size_t                  symTableSize;
     unsigned                symIdx;
     struct
     {
         VC_DEBUG_HEADER_T header;
         VC_DEBUG_PARAMS_T params;
     } vc_dbg;
     vcos_log_register( "debug_sym", &debug_sym_log_category );
     if (( newHandle = calloc( 1, sizeof( *newHandle ))) == NULL )
     {
         return -ENOMEM;
     }
     if ( filename == NULL )
     {
         newHandle->use_vc_mem = 1;
         filename = "/dev/vc-mem";
     }
     else
     {
         newHandle->use_vc_mem = 0;
     }
     if (( newHandle->memFd = open( filename, ( newHandle->use_vc_mem ? O_RDWR : O_RDONLY ) | O_SYNC )) < 0 )
     {
         ERR( "Unable to open '%s': %s(%d)\n", filename, strerror( errno ), errno );
         free(newHandle);
         return -errno;
     }
     DBG( "Opened %s memFd = %d", filename, newHandle->memFd );
     if ( newHandle->use_vc_mem )
     {
         newHandle->memFdBase = 0;
 #if defined(WIN32) || defined(__CYGWIN__)
 #define VC_MEM_SIZE  (128 * 1024 * 1024)
         newHandle->vcMemSize = VC_MEM_SIZE;
         newHandle->vcMemBase = 0;
         newHandle->vcMemLoad = 0;
         newHandle->vcMemPhys = 0;
 #else
         if ( ioctl( newHandle->memFd, VC_MEM_IOC_MEM_SIZE, &newHandle->vcMemSize ) != 0 )
         {
             ERR( "Failed to get memory size via ioctl: %s(%d)\n",
                 strerror( errno ), errno );
             free(newHandle);
             return -errno;
         }
         if ( ioctl( newHandle->memFd, VC_MEM_IOC_MEM_BASE, &newHandle->vcMemBase ) != 0 )
         {
             ERR( "Failed to get memory base via ioctl: %s(%d)\n",
                 strerror( errno ), errno );
             free(newHandle);
             return -errno;
         }
         if ( ioctl( newHandle->memFd, VC_MEM_IOC_MEM_LOAD, &newHandle->vcMemLoad ) != 0 )
         {
             ERR( "Failed to get memory load via ioctl: %s(%d)\n",
                 strerror( errno ), errno );
                 /* Backward compatibility. */
             newHandle->vcMemLoad = newHandle->vcMemBase;
         }
         if ( ioctl( newHandle->memFd, VC_MEM_IOC_MEM_PHYS_ADDR, &newHandle->vcMemPhys ) != 0 )
         {
             ERR( "Failed to get memory physical address via ioctl: %s(%d)\n",
                 strerror( errno ), errno );
             free(newHandle);
             return -errno;
         }
 #endif
     }
     else
     {
         off_t len = lseek( newHandle->memFd, 0, SEEK_END );
         if ( len < 0 )
         {
             ERR( "Failed to seek to end of file: %s(%d)\n", strerror( errno ), errno );
             free(newHandle);
             return -errno;
         }
         newHandle->vcMemPhys = 0;
         newHandle->vcMemSize = len;
         newHandle->vcMemBase = 0;
         newHandle->vcMemLoad = loadOffset;
         newHandle->memFdBase = 0;
     }
     DBG( "vcMemSize = %08x", newHandle->vcMemSize );
     DBG( "vcMemBase = %08x", newHandle->vcMemBase );
     DBG( "vcMemLoad = %08x", newHandle->vcMemLoad );
     DBG( "vcMemPhys = %08x", newHandle->vcMemPhys );
     newHandle->vcMemEnd = newHandle->vcMemBase + newHandle->vcMemSize - 1;
     // See if we can detect the symbol table
     if ( !ReadVideoCoreMemory( newHandle,
                                &newHandle->vcSymbolTableOffset,
                                newHandle->vcMemLoad + VC_SYMBOL_BASE_OFFSET,
                                sizeof( newHandle->vcSymbolTableOffset )))
     {
         ERR( "ReadVideoCoreMemory @VC_SYMBOL_BASE_OFFSET (0x%08x) failed\n", VC_SYMBOL_BASE_OFFSET );
         rc = -EIO;
         goto err_exit;
     }
     // When reading from a file, the VC binary is read into a buffer and the effective base is 0.
     // But that may not be the actual base address the binary is intended to be loaded to.  The
     // following reads the debug header to find out what the actual base address is.
     if( !newHandle->use_vc_mem )
     {
         // Read the complete debug header
         if ( !ReadVideoCoreMemory( newHandle,
                                    &vc_dbg,
                                    newHandle->vcMemLoad + VC_SYMBOL_BASE_OFFSET,
                                    sizeof( vc_dbg )))
         {
             ERR( "ReadVideoCoreMemory @VC_SYMBOL_BASE_OFFSET (0x%08x) failed\n", VC_SYMBOL_BASE_OFFSET );
             rc = -EIO;
             goto err_exit;
         }
         // The vc_dbg header gives the "base" address of the VC binary,
         // which debug_sym calls the "load" address, so we need to adjust
         // it by loadOffset to find the base of the whole memory dump file
         newHandle->memFdBase = vc_dbg.params.vcMemBase - loadOffset;
         newHandle->vcMemBase = vc_dbg.params.vcMemBase - loadOffset;
         newHandle->vcMemLoad = vc_dbg.params.vcMemBase;
         newHandle->vcMemEnd = newHandle->memFdBase + newHandle->vcMemSize - 1;
         DBG( "Updated from debug header:" );
         DBG( "vcMemSize = %08x", newHandle->vcMemSize );
         DBG( "vcMemBase = %08x", newHandle->vcMemBase );
         DBG( "vcMemLoad = %08x", newHandle->vcMemLoad );
         DBG( "vcMemPhys = %08x", newHandle->vcMemPhys );
     }
     DBG( "vcSymbolTableOffset = 0x%08x", newHandle->vcSymbolTableOffset );
     // Make sure that the pointer points into the first few megabytes of
     // the memory space.
     if ( (newHandle->vcSymbolTableOffset - newHandle->vcMemLoad) > ( MAX_VC_SIZE * 1024 * 1024 ))
     {
         ERR( "newHandle->vcSymbolTableOffset (0x%x - 0x%x) > %dMB\n", newHandle->vcSymbolTableOffset, newHandle->vcMemLoad, MAX_VC_SIZE );
         rc = -EIO;
         goto err_exit;
     }
     // Make a pass to count how many symbols there are.
     symAddr = newHandle->vcSymbolTableOffset;
     newHandle->numSymbols = 0;
     do
     {
         if ( !ReadVideoCoreMemory( newHandle,
                                    &debug_sym,
                                    symAddr,
                                    sizeof( debug_sym )))
         {
             ERR( "ReadVideoCoreMemory @ symAddr(0x%08x) failed\n", symAddr );
             rc = -EIO;
             goto err_exit;
         }
         newHandle->numSymbols++;
         DBG( "Symbol %d: label: 0x%p addr: 0x%08x size: %zu",
              newHandle->numSymbols,
              debug_sym.label,
              debug_sym.addr,
              debug_sym.size );
         if ( newHandle->numSymbols > 1024 )
         {
             // Something isn't sane.
             ERR( "numSymbols (%d) > 1024 - looks wrong\n", newHandle->numSymbols );
             rc = -EIO;
             goto err_exit;
         }
         symAddr += sizeof( debug_sym );
     } while ( debug_sym.label != 0 );
     newHandle->numSymbols--;
     DBG( "Detected %d symbols", newHandle->numSymbols );
     // Allocate some memory to hold the symbols, and read them in.
     symTableSize = newHandle->numSymbols * sizeof( debug_sym );
     if (( newHandle->symbol = malloc( symTableSize )) == NULL )
     {
         rc = -ENOMEM;
         goto err_exit;
     }
     if ( !ReadVideoCoreMemory( newHandle,
                                newHandle->symbol,
                                newHandle->vcSymbolTableOffset,
                                symTableSize ))
     {
         ERR( "ReadVideoCoreMemory @ newHandle->vcSymbolTableOffset(0x%08x) failed\n", newHandle->vcSymbolTableOffset );
         rc = -EIO;
         goto err_exit;
     }
     // The names of the symbols are pointers in videocore space. We want
     // to have them available locally, so we make copies and fixup
     // the pointer.
     for ( symIdx = 0; symIdx < newHandle->numSymbols; symIdx++ )
     {
         VC_DEBUG_SYMBOL_T   *sym;
         char                 symName[ 256 ];
         sym = &newHandle->symbol[ symIdx ];
         DBG( "Symbol %d: label: 0x%p addr: 0x%08x size: %zu",
              symIdx,
              sym->label,
              sym->addr,
              sym->size );
         if ( !ReadVideoCoreMemory( newHandle,
                                    symName,
                                    TO_VC_MEM_ADDR(sym->label),
                                    sizeof( symName )))
         {
             ERR( "ReadVideoCoreMemory @ sym->label(0x%08x) failed\n", TO_VC_MEM_ADDR(sym->label) );
             rc = -EIO;
             goto err_exit;
         }
         symName[ sizeof( symName ) - 1 ] = '\0';
         sym->label = vcos_strdup( symName );
         DBG( "Symbol %d (@0x%p): label: '%s' addr: 0x%08x size: %zu",
              symIdx,
              sym,
              sym->label,
              sym->addr,
              sym->size );
     }
     *vcHandlePtr = newHandle;
     return 0;
 err_exit:
     close( newHandle->memFd );
     free( newHandle );
     return rc;
 }
ReadVideoCoreMemory()
int ReadVideoCoreMemory (VC_MEM_ACCESS_HANDLE_T handle, void * buf, VC_MEM_ADDR_T vcMemAddr, size_t numBytes)
Definition at line 686 of file debug_sym.c.
Referenced by OpenVideoCoreMemoryFileWithOffset(), ReadVideoCoreMemoryBySymbol(), ReadVideoCoreStringBySymbol(), and ReadVideoCoreUInt32().
 {
     return AccessVideoCoreMemory( vcHandle, READ_MEM, buf, vcMemAddr, numBytes );
 }
ReadVideoCoreMemoryBySymbol()
int ReadVideoCoreMemoryBySymbol (VC_MEM_ACCESS_HANDLE_T vcHandle, const char * symbol, void * buf, size_t numBytes)
Definition at line 700 of file debug_sym.c.
References ERR, LookupVideoCoreSymbol(), ReadVideoCoreMemory(), and opaque_vc_mem_access_handle_t::vcMemSize.
Referenced by ReadVideoCoreUInt32(), and ReadVideoCoreUInt32BySymbol().
 {
     VC_MEM_ADDR_T   vcMemAddr;
     size_t          vcMemSize;
     if ( !LookupVideoCoreSymbol( vcHandle, symbol, &vcMemAddr, &vcMemSize ))
     {
         ERR( "Symbol not found: '%s'", symbol );
         return 0;
     }
     if ( vcMemSize > bufSize )
     {
         vcMemSize = bufSize;
     }
     if ( !ReadVideoCoreMemory( vcHandle, buf, vcMemAddr, vcMemSize ))
     {
         ERR( "Unable to read %zu bytes @ 0x%08x", vcMemSize, vcMemAddr );
         return 0;
     }
     return 1;
 }
ReadVideoCoreStringBySymbol()
int ReadVideoCoreStringBySymbol (VC_MEM_ACCESS_HANDLE_T handle, const char * symbol, char * buf, size_t bufSize)
Definition at line 732 of file debug_sym.c.
References ERR, LookupVideoCoreSymbol(), ReadVideoCoreMemory(), and opaque_vc_mem_access_handle_t::vcMemSize.
Referenced by ReadVideoCoreUInt32BySymbol().
 {
     VC_MEM_ADDR_T   vcMemAddr;
     size_t          vcMemSize;
     if ( !LookupVideoCoreSymbol( vcHandle, symbol, &vcMemAddr, &vcMemSize ))
     {
         ERR( "Symbol not found: '%s'", symbol );
         return 0;
     }
     if ( vcMemSize > bufSize )
     {
         vcMemSize = bufSize;
     }
     if ( !ReadVideoCoreMemory( vcHandle, buf, vcMemAddr, vcMemSize ))
     {
         ERR( "Unable to read %zu bytes @ 0x%08x", vcMemSize, vcMemAddr );
         return 0;
     }
     // Make sure that the result is null-terminated
     buf[vcMemSize-1] = '\0';
     return 1;
 }
ReadVideoCoreUInt32()
VCOS_STATIC_INLINE int ReadVideoCoreUInt32 (VC_MEM_ACCESS_HANDLE_T handle, uint32_t * val, VC_MEM_ADDR_T vcMemAddr)
Definition at line 135 of file debug_sym.h.
References ReadVideoCoreMemory(), ReadVideoCoreMemoryBySymbol(), and opaque_vc_mem_access_handle_t::symbol.
 {
     return ReadVideoCoreMemory( handle, val, vcMemAddr, sizeof( *val ));
 }
ReadVideoCoreUInt32BySymbol()
VCOS_STATIC_INLINE int ReadVideoCoreUInt32BySymbol (VC_MEM_ACCESS_HANDLE_T handle, const char * symbol, uint32_t * val)
Definition at line 152 of file debug_sym.h.
References ReadVideoCoreMemoryBySymbol(), ReadVideoCoreStringBySymbol(), and WriteVideoCoreMemory().
 {
     return ReadVideoCoreMemoryBySymbol( handle, symbol, val, sizeof( *val ));
 }
WriteVideoCoreMemory()
int WriteVideoCoreMemory (VC_MEM_ACCESS_HANDLE_T handle, void * buf, VC_MEM_ADDR_T vcMemAddr, size_t numBytes)
Definition at line 772 of file debug_sym.c.
Referenced by ReadVideoCoreUInt32BySymbol(), and WriteVideoCoreUInt32().
 {
     return AccessVideoCoreMemory( vcHandle, WRITE_MEM, buf, vcMemAddr, numBytes );
 }
WriteVideoCoreUInt32()
VCOS_STATIC_INLINE int WriteVideoCoreUInt32 (VC_MEM_ACCESS_HANDLE_T handle, uint32_t val, VC_MEM_ADDR_T vcMemAddr)
Definition at line 182 of file debug_sym.h.
References CloseVideoCoreMemory(), GetVideoCoreMemoryBase(), GetVideoCoreMemoryPhysicalAddress(), GetVideoCoreMemorySize(), and WriteVideoCoreMemory().
 {
     return WriteVideoCoreMemory( handle, &val, vcMemAddr, sizeof( val ));
 }