VideoCore Library: interface/khronos/common/khrn_client_rpc.h File Reference
khrn_client_rpc.h File Reference
#include "interface/khronos/common/khrn_int_util.h"
#include "interface/khronos/common/khrn_client.h"
#include <stdlib.h>
#include "interface/khronos/common/khrn_int_ids.h"
#include "interface/khronos/include/GLES/gl.h"
#include "interface/khronos/include/VG/openvg.h"
#include <string.h>
Macros
#define RPC_DELAYED_USE_OF_POINTERS
#define RPC_FLOAT(f) (float_to_bits(f))
#define RPC_ENUM(e) ((uint32_t)(e))
#define RPC_INT(i) ((uint32_t)(i))
#define RPC_INTPTR(p) ((uint32_t)(p))
#define RPC_UINT(u) ((uint32_t)(u))
#define RPC_SIZEI(s) ((uint32_t)(s))
#define RPC_SIZEIPTR(p) ((uint32_t)(p))
#define RPC_BOOLEAN(b) ((uint32_t)(b))
#define RPC_BITFIELD(b) ((uint32_t)(b))
#define RPC_FIXED(f) ((uint32_t)(f))
#define RPC_HANDLE(h) ((uint32_t)(h))
#define RPC_EGLID(i) ((uint32_t)(size_t)(i))
#define RPC_FLOAT_RES(f) (float_from_bits(f))
#define RPC_ENUM_RES(e) ((GLenum)(e))
#define RPC_INT_RES(i) ((GLint)(i))
#define RPC_UINT_RES(u) ((GLuint)(u))
#define RPC_BOOLEAN_RES(b) (!!(b))
#define RPC_BITFIELD_RES(b) ((GLbitfield)(b))
#define RPC_HANDLE_RES(h) ((VGHandle)(h))
#define RPC_INIT() khclient_rpc_init()
#define RPC_TERM() rpc_term()
#define RPC_FLUSH(thread) rpc_flush(thread)
#define RPC_HIGH_PRIORITY_BEGIN(thread) rpc_high_priority_begin(thread)
#define RPC_HIGH_PRIORITY_END(thread) rpc_high_priority_end(thread)
#define RPC_CALL8_MAKECURRENT(fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7) rpc_call8_makecurrent(thread, id, p0, p1, p2, p3, p4, p5, p6, p7)
#define RPC_CALL(thread, ...)
#define RPC_CALL_IN_CTRL(thread, IN, LEN, ...)
#define RPC_CALL_IN_BULK(thread, IN, LEN, ...)
#define RPC_CALL0(fn, thread, id) rpc_call0(thread, id)
#define RPC_CALL1(fn, thread, id, p0) rpc_call1(thread, id, p0)
#define RPC_CALL2(fn, thread, id, p0, p1) rpc_call2(thread, id, p0, p1)
#define RPC_CALL3(fn, thread, id, p0, p1, p2) rpc_call3(thread, id, p0, p1, p2)
#define RPC_CALL4(fn, thread, id, p0, p1, p2, p3) rpc_call4(thread, id, p0, p1, p2, p3)
#define RPC_CALL5(fn, thread, id, p0, p1, p2, p3, p4) rpc_call5(thread, id, p0, p1, p2, p3, p4)
#define RPC_CALL6(fn, thread, id, p0, p1, p2, p3, p4, p5) rpc_call6(thread, id, p0, p1, p2, p3, p4, p5)
#define RPC_CALL7(fn, thread, id, p0, p1, p2, p3, p4, p5, p6) rpc_call7(thread, id, p0, p1, p2, p3, p4, p5, p6)
#define RPC_CALL8(fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7) rpc_call8(thread, id, p0, p1, p2, p3, p4, p5, p6, p7)
#define RPC_CALL9(fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8) rpc_call9(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8)
#define RPC_CALL10(fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9) rpc_call10(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9)
#define RPC_CALL11(fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) rpc_call10(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10)
#define RPC_CALL16(fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15) rpc_call16(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15)
#define RPC_CALL18(fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17) rpc_call18(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17)
#define RPC_CALL0_RES(fn, thread, id) rpc_call0_res(thread, id)
#define RPC_CALL1_RES(fn, thread, id, p0) rpc_call1_res(thread, id, p0)
#define RPC_CALL2_RES(fn, thread, id, p0, p1) rpc_call2_res(thread, id, p0, p1)
#define RPC_CALL3_RES(fn, thread, id, p0, p1, p2) rpc_call3_res(thread, id, p0, p1, p2)
#define RPC_CALL4_RES(fn, thread, id, p0, p1, p2, p3) rpc_call4_res(thread, id, p0, p1, p2, p3)
#define RPC_CALL5_RES(fn, thread, id, p0, p1, p2, p3, p4) rpc_call5_res(thread, id, p0, p1, p2, p3, p4)
#define RPC_CALL6_RES(fn, thread, id, p0, p1, p2, p3, p4, p5) rpc_call6_res(thread, id, p0, p1, p2, p3, p4, p5)
#define RPC_CALL7_RES(fn, thread, id, p0, p1, p2, p3, p4, p5, p6) rpc_call7_res(thread, id, p0, p1, p2, p3, p4, p5, p6)
#define RPC_CALL8_RES(fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7) rpc_call8_res(thread, id, p0, p1, p2, p3, p4, p5, p6, p7)
#define RPC_CALL9_RES(fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8) rpc_call9_res(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8)
#define RPC_CALL10_RES(fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9) rpc_call10_res(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9)
#define RPC_CALL11_RES(fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) rpc_call11_res(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10)
#define RPC_CALL12_RES(fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11) rpc_call12_res(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11)
#define RPC_CALL1_IN_CTRL(fn, thread, id, in, len) rpc_call1_in_ctrl(thread, id, in, len)
#define RPC_CALL2_IN_CTRL(fn, thread, id, p0, in, len) rpc_call2_in_ctrl(thread, id, p0, in, len)
#define RPC_CALL3_IN_CTRL(fn, thread, id, p0, p1, in, len) rpc_call3_in_ctrl(thread, id, p0, p1, in, len)
#define RPC_CALL4_IN_CTRL(fn, thread, id, p0, p1, p2, in, len) rpc_call4_in_ctrl(thread, id, p0, p1, p2, in, len)
#define RPC_CALL5_IN_CTRL(fn, thread, id, p0, p1, p2, p3, in, len) rpc_call5_in_ctrl(thread, id, p0, p1, p2, p3, in, len)
#define RPC_CALL6_IN_CTRL(fn, thread, id, p0, p1, p2, p3, p4, in, len) rpc_call6_in_ctrl(thread, id, p0, p1, p2, p3, p4, in, len)
#define RPC_CALL7_IN_CTRL(fn, thread, id, p0, p1, p2, p3, p4, p5, in, len) rpc_call7_in_ctrl(thread, id, p0, p1, p2, p3, p4, p5, in, len)
#define RPC_CALL8_IN_CTRL(fn, thread, id, p0, p1, p2, p3, p4, p5, p6, in, len) rpc_call8_in_ctrl(thread, id, p0, p1, p2, p3, p4, p5, p6, in, len)
#define RPC_CALL9_IN_CTRL(fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, in, len) rpc_call9_in_ctrl(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, in, len)
#define RPC_CALL10_IN_CTRL(fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, in, len) rpc_call10_in_ctrl(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, in, len)
#define RPC_CALL1_OUT_CTRL(fn, thread, id, out) rpc_call1_out_ctrl(thread, id, out)
#define RPC_CALL2_OUT_CTRL(fn, thread, id, p0, out) rpc_call2_out_ctrl(thread, id, p0, out)
#define RPC_CALL3_OUT_CTRL(fn, thread, id, p0, p1, out) rpc_call3_out_ctrl(thread, id, p0, p1, out)
#define RPC_CALL4_OUT_CTRL(fn, thread, id, p0, p1, p2, out) rpc_call4_out_ctrl(thread, id, p0, p1, p2, out)
#define RPC_CALL5_OUT_CTRL(fn, thread, id, p0, p1, p2, p3, out) rpc_call5_out_ctrl(thread, id, p0, p1, p2, p3, out)
#define RPC_CALL6_OUT_CTRL(fn, thread, id, p0, p1, p2, p3, p4, out) rpc_call6_out_ctrl(thread, id, p0, p1, p2, p3, p4, out)
#define RPC_CALL7_OUT_CTRL(fn, thread, id, p0, p1, p2, p3, p4, p5, out) rpc_call7_out_ctrl(thread, id, p0, p1, p2, p3, p4, p5, out)
#define RPC_CALL8_OUT_CTRL(fn, thread, id, p0, p1, p2, p3, p4, p5, p6, out) rpc_call8_out_ctrl(thread, id, p0, p1, p2, p3, p4, p5, p6, out)
#define RPC_CALL9_OUT_CTRL(fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, out) rpc_call9_out_ctrl(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, out)
#define RPC_CALL10_OUT_CTRL(fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, out) rpc_call10_out_ctrl(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, out)
#define RPC_CALL11_OUT_CTRL(fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, out) rpc_call11_out_ctrl(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, out)
#define RPC_CALL12_OUT_CTRL(fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, out) rpc_call12_out_ctrl(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, out)
#define RPC_CALL13_OUT_CTRL(fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, out) rpc_call13_out_ctrl(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, out)
#define RPC_CALL14_OUT_CTRL(fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, out) rpc_call14_out_ctrl(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, out)
#define RPC_CALL15_OUT_CTRL(fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, out) rpc_call15_out_ctrl(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, out)
#define RPC_CALL1_OUT_CTRL_RES(fn, thread, id, out) rpc_call1_out_ctrl_res(thread, id, out)
#define RPC_CALL2_OUT_CTRL_RES(fn, thread, id, p0, out) rpc_call2_out_ctrl_res(thread, id, p0, out)
#define RPC_CALL3_OUT_CTRL_RES(fn, thread, id, p0, p1, out) rpc_call3_out_ctrl_res(thread, id, p0, p1, out)
#define RPC_CALL4_OUT_CTRL_RES(fn, thread, id, p0, p1, p2, out) rpc_call4_out_ctrl_res(thread, id, p0, p1, p2, out)
#define RPC_CALL5_OUT_CTRL_RES(fn, thread, id, p0, p1, p2, p3, out) rpc_call5_out_ctrl_res(thread, id, p0, p1, p2, p3, out)
#define RPC_CALL6_OUT_CTRL_RES(fn, thread, id, p0, p1, p2, p3, p4, out) rpc_call6_out_ctrl_res(thread, id, p0, p1, p2, p3, p4, out)
#define RPC_CALL7_OUT_CTRL_RES(fn, thread, id, p0, p1, p2, p3, p4, p5, out) rpc_call7_out_ctrl_res(thread, id, p0, p1, p2, p3, p4, p5, out)
#define RPC_CALL8_OUT_CTRL_RES(fn, thread, id, p0, p1, p2, p3, p4, p5, p6, out) rpc_call8_out_ctrl_res(thread, id, p0, p1, p2, p3, p4, p5, p6, out)
#define RPC_CALL9_OUT_CTRL_RES(fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, out) rpc_call9_out_ctrl_res(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, out)
#define RPC_CALL10_OUT_CTRL_RES(fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, out) rpc_call10_out_ctrl_res(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, out)
#define RPC_CALL1_IN_BULK(fn, thread, id, in, len) rpc_call1_in_bulk(thread, id, in, len)
#define RPC_CALL2_IN_BULK(fn, thread, id, p0, in, len) rpc_call2_in_bulk(thread, id, p0, in, len)
#define RPC_CALL3_IN_BULK(fn, thread, id, p0, p1, in, len) rpc_call3_in_bulk(thread, id, p0, p1, in, len)
#define RPC_CALL4_IN_BULK(fn, thread, id, p0, p1, p2, in, len) rpc_call4_in_bulk(thread, id, p0, p1, p2, in, len)
#define RPC_CALL5_IN_BULK(fn, thread, id, p0, p1, p2, p3, in, len) rpc_call5_in_bulk(thread, id, p0, p1, p2, p3, in, len)
#define RPC_CALL6_IN_BULK(fn, thread, id, p0, p1, p2, p3, p4, in, len) rpc_call6_in_bulk(thread, id, p0, p1, p2, p3, p4, in, len)
#define RPC_CALL7_IN_BULK(fn, thread, id, p0, p1, p2, p3, p4, p5, in, len) rpc_call7_in_bulk(thread, id, p0, p1, p2, p3, p4, p5, in, len)
#define RPC_CALL8_IN_BULK(fn, thread, id, p0, p1, p2, p3, p4, p5, p6, in, len) rpc_call8_in_bulk(thread, id, p0, p1, p2, p3, p4, p5, p6, in, len)
#define RPC_CALL9_IN_BULK(fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, in, len) rpc_call9_in_bulk(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, in, len)
#define RPC_CALL10_IN_BULK(fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, in, len) rpc_call10_in_bulk(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, in, len)
#define RPC_CALL1_OUT_BULK(fn, thread, id, out) rpc_call1_out_bulk(thread, id, out)
#define RPC_CALL2_OUT_BULK(fn, thread, id, p0, out) rpc_call2_out_bulk(thread, id, p0, out)
#define RPC_CALL3_OUT_BULK(fn, thread, id, p0, p1, out) rpc_call3_out_bulk(thread, id, p0, p1, out)
#define RPC_CALL4_OUT_BULK(fn, thread, id, p0, p1, p2, out) rpc_call4_out_bulk(thread, id, p0, p1, p2, out)
#define RPC_CALL5_OUT_BULK(fn, thread, id, p0, p1, p2, p3, out) rpc_call5_out_bulk(thread, id, p0, p1, p2, p3, out)
#define RPC_CALL6_OUT_BULK(fn, thread, id, p0, p1, p2, p3, p4, out) rpc_call6_out_bulk(thread, id, p0, p1, p2, p3, p4, out)
#define RPC_CALL7_OUT_BULK(fn, thread, id, p0, p1, p2, p3, p4, p5, out) rpc_call7_out_bulk(thread, id, p0, p1, p2, p3, p4, p5, out)
#define RPC_CALL8_OUT_BULK(fn, thread, id, p0, p1, p2, p3, p4, p5, p6, out) rpc_call8_out_bulk(thread, id, p0, p1, p2, p3, p4, p5, p6, out)
#define RPC_CALL9_OUT_BULK(fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, out) rpc_call9_out_bulk(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, out)
#define RPC_CALL10_OUT_BULK(fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, out) rpc_call10_out_bulk(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, out)
#define RPC_CALL1_IN_BULK_RES(fn, thread, id, in, len) rpc_call1_in_bulk_res(thread, id, in, len)
#define RPC_CALL2_IN_BULK_RES(fn, thread, id, p0, in, len) rpc_call2_in_bulk_res(thread, id, p0, in, len)
#define RPC_CALL3_IN_BULK_RES(fn, thread, id, p0, p1, in, len) rpc_call3_in_bulk_res(thread, id, p0, p1, in, len)
#define RPC_CALL4_IN_BULK_RES(fn, thread, id, p0, p1, p2, in, len) rpc_call4_in_bulk_res(thread, id, p0, p1, p2, in, len)
#define RPC_CALL5_IN_BULK_RES(fn, thread, id, p0, p1, p2, p3, in, len) rpc_call5_in_bulk_res(thread, id, p0, p1, p2, p3, in, len)
#define RPC_CALL6_IN_BULK_RES(fn, thread, id, p0, p1, p2, p3, p4, in, len) rpc_call6_in_bulk_res(thread, id, p0, p1, p2, p3, p4, in, len)
#define RPC_CALL7_IN_BULK_RES(fn, thread, id, p0, p1, p2, p3, p4, p5, in, len) rpc_call7_in_bulk_res(thread, id, p0, p1, p2, p3, p4, p5, in, len)
#define RPC_CALL8_IN_BULK_RES(fn, thread, id, p0, p1, p2, p3, p4, p5, p6, in, len) rpc_call8_in_bulk_res(thread, id, p0, p1, p2, p3, p4, p5, p6, in, len)
#define RPC_CALL9_IN_BULK_RES(fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, in, len) rpc_call9_in_bulk_res(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, in, len)
#define RPC_CALL10_IN_BULK_RES(fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, in, len) rpc_call10_in_bulk_res(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, in, len)
#define RPC_CALL1_OUT_BULK_RES(fn, thread, id, out) rpc_call1_out_bulk_res(thread, id, out)
#define RPC_CALL2_OUT_BULK_RES(fn, thread, id, p0, out) rpc_call2_out_bulk_res(thread, id, p0, out)
#define RPC_CALL3_OUT_BULK_RES(fn, thread, id, p0, p1, out) rpc_call3_out_bulk_res(thread, id, p0, p1, out)
#define RPC_CALL4_OUT_BULK_RES(fn, thread, id, p0, p1, p2, out) rpc_call4_out_bulk_res(thread, id, p0, p1, p2, out)
#define RPC_CALL5_OUT_BULK_RES(fn, thread, id, p0, p1, p2, p3, out) rpc_call5_out_bulk_res(thread, id, p0, p1, p2, p3, out)
#define RPC_CALL6_OUT_BULK_RES(fn, thread, id, p0, p1, p2, p3, p4, out) rpc_call6_out_bulk_res(thread, id, p0, p1, p2, p3, p4, out)
#define RPC_CALL7_OUT_BULK_RES(fn, thread, id, p0, p1, p2, p3, p4, p5, out) rpc_call7_out_bulk_res(thread, id, p0, p1, p2, p3, p4, p5, out)
#define RPC_CALL8_OUT_BULK_RES(fn, thread, id, p0, p1, p2, p3, p4, p5, p6, out) rpc_call8_out_bulk_res(thread, id, p0, p1, p2, p3, p4, p5, p6, out)
#define RPC_CALL9_OUT_BULK_RES(fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, out) rpc_call9_out_bulk_res(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, out)
#define RPC_CALL10_OUT_BULK_RES(fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, out) rpc_call10_out_bulk_res(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, out)
Enumerations
enum RPC_RECV_FLAG_T {
RPC_RECV_FLAG_RES = 1 << 0, RPC_RECV_FLAG_CTRL = 1 << 1, RPC_RECV_FLAG_BULK = 1 << 2, RPC_RECV_FLAG_BULK_SCATTER = 1 << 3,
RPC_RECV_FLAG_LEN = 1 << 4
}
Functions
bool khclient_rpc_init (void)
void rpc_term (void)
void rpc_flush (CLIENT_THREAD_STATE_T *thread)
void rpc_high_priority_begin (CLIENT_THREAD_STATE_T *thread)
void rpc_high_priority_end (CLIENT_THREAD_STATE_T *thread)
uint64_t rpc_get_client_id (CLIENT_THREAD_STATE_T *thread)
uint32_t rpc_send_ctrl_longest (CLIENT_THREAD_STATE_T *thread, uint32_t len_min)
void rpc_send_ctrl_begin (CLIENT_THREAD_STATE_T *thread, uint32_t len)
void rpc_send_ctrl_write (CLIENT_THREAD_STATE_T *thread, const uint32_t msg[], uint32_t msglen)
void rpc_send_ctrl_end (CLIENT_THREAD_STATE_T *thread)
void rpc_send_bulk (CLIENT_THREAD_STATE_T *thread, const void *in, uint32_t len)
void rpc_send_bulk_gather (CLIENT_THREAD_STATE_T *thread, const void *in, uint32_t len, int32_t stride, uint32_t n)
uint32_t rpc_recv (CLIENT_THREAD_STATE_T *thread, void *out, uint32_t *len, RPC_RECV_FLAG_T flags)
void rpc_recv_bulk_gather (CLIENT_THREAD_STATE_T *thread, void *out, uint32_t *len, RPC_RECV_FLAG_T flags)
void rpc_begin (CLIENT_THREAD_STATE_T *thread)
void rpc_end (CLIENT_THREAD_STATE_T *thread)
void rpc_call8_makecurrent (CLIENT_THREAD_STATE_T *thread, uint32_t id, uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4, uint32_t p5, uint32_t p6, uint32_t p7)
uint32_t khronos_kernel_semaphore_create (uint32_t name, uint32_t count)
uint32_t khronos_kernel_semaphore_acquire (uint32_t semaphore)
uint32_t khronos_kernel_semaphore_acquire_and_release (uint32_t semaphore)
uint32_t khronos_kernel_semaphore_release (uint32_t semaphore)
uint32_t khronos_kernel_semaphore_destroy (uint32_t semaphore)
Macro Definition Documentation
RPC_BITFIELD
#define RPC_BITFIELD (b) ((uint32_t)(b))
Definition at line 434 of file khrn_client_rpc.h.
RPC_BITFIELD_RES
#define RPC_BITFIELD_RES (b) ((GLbitfield)(b))
Definition at line 444 of file khrn_client_rpc.h.
RPC_BOOLEAN
#define RPC_BOOLEAN (b) ((uint32_t)(b))
Definition at line 433 of file khrn_client_rpc.h.
RPC_BOOLEAN_RES
#define RPC_BOOLEAN_RES (b) (!!(b))
Definition at line 443 of file khrn_client_rpc.h.
RPC_CALL
#define RPC_CALL (thread, ...)
Value:
do { \
         uint32_t message_[] = { __VA_ARGS__ }; \
         rpc_send_ctrl_begin(thread, sizeof(message_)); \
         rpc_send_ctrl_write(thread, message_, sizeof(message_)); \
         rpc_send_ctrl_end(thread); \
      } while (0)
Definition at line 511 of file khrn_client_rpc.h.
RPC_CALL0
#define RPC_CALL0 (fn, thread, id) rpc_call0(thread, id)
Definition at line 569 of file khrn_client_rpc.h.
Referenced by client_process_state_init().
RPC_CALL0_RES
#define RPC_CALL0_RES (fn, thread, id) rpc_call0_res(thread, id)
Definition at line 629 of file khrn_client_rpc.h.
RPC_CALL1
#define RPC_CALL1 (fn, thread, id, p0) rpc_call1(thread, id, p0)
Definition at line 570 of file khrn_client_rpc.h.
RPC_CALL10
#define RPC_CALL10 (fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9) rpc_call10(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9)
Definition at line 579 of file khrn_client_rpc.h.
RPC_CALL10_IN_BULK
#define RPC_CALL10_IN_BULK (fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, in, len) rpc_call10_in_bulk(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, in, len)
Definition at line 759 of file khrn_client_rpc.h.
RPC_CALL10_IN_BULK_RES
#define RPC_CALL10_IN_BULK_RES (fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, in, len) rpc_call10_in_bulk_res(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, in, len)
Definition at line 807 of file khrn_client_rpc.h.
RPC_CALL10_IN_CTRL
#define RPC_CALL10_IN_CTRL (fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, in, len) rpc_call10_in_ctrl(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, in, len)
Definition at line 670 of file khrn_client_rpc.h.
RPC_CALL10_OUT_BULK
#define RPC_CALL10_OUT_BULK (fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, out) rpc_call10_out_bulk(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, out)
Definition at line 783 of file khrn_client_rpc.h.
RPC_CALL10_OUT_BULK_RES
#define RPC_CALL10_OUT_BULK_RES (fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, out) rpc_call10_out_bulk_res(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, out)
Definition at line 831 of file khrn_client_rpc.h.
RPC_CALL10_OUT_CTRL
#define RPC_CALL10_OUT_CTRL (fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, out) rpc_call10_out_ctrl(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, out)
Definition at line 699 of file khrn_client_rpc.h.
RPC_CALL10_OUT_CTRL_RES
#define RPC_CALL10_OUT_CTRL_RES (fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, out) rpc_call10_out_ctrl_res(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, out)
Definition at line 728 of file khrn_client_rpc.h.
RPC_CALL10_RES
#define RPC_CALL10_RES (fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9) rpc_call10_res(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9)
Definition at line 639 of file khrn_client_rpc.h.
RPC_CALL11
#define RPC_CALL11 (fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) rpc_call10(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10)
Definition at line 580 of file khrn_client_rpc.h.
RPC_CALL11_OUT_CTRL
#define RPC_CALL11_OUT_CTRL (fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, out) rpc_call11_out_ctrl(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, out)
Definition at line 700 of file khrn_client_rpc.h.
RPC_CALL11_RES
#define RPC_CALL11_RES (fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10) rpc_call11_res(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10)
Definition at line 640 of file khrn_client_rpc.h.
RPC_CALL12_OUT_CTRL
#define RPC_CALL12_OUT_CTRL (fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, out) rpc_call12_out_ctrl(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, out)
Definition at line 701 of file khrn_client_rpc.h.
RPC_CALL12_RES
#define RPC_CALL12_RES (fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11) rpc_call12_res(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11)
Definition at line 641 of file khrn_client_rpc.h.
RPC_CALL13_OUT_CTRL
#define RPC_CALL13_OUT_CTRL (fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, out) rpc_call13_out_ctrl(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, out)
Definition at line 702 of file khrn_client_rpc.h.
RPC_CALL14_OUT_CTRL
#define RPC_CALL14_OUT_CTRL (fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, out) rpc_call14_out_ctrl(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, out)
Definition at line 703 of file khrn_client_rpc.h.
RPC_CALL15_OUT_CTRL
#define RPC_CALL15_OUT_CTRL (fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, out) rpc_call15_out_ctrl(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, out)
Definition at line 704 of file khrn_client_rpc.h.
RPC_CALL16
#define RPC_CALL16 (fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15) rpc_call16(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15)
Definition at line 581 of file khrn_client_rpc.h.
RPC_CALL18
#define RPC_CALL18 (fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17) rpc_call18(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17)
Definition at line 583 of file khrn_client_rpc.h.
RPC_CALL1_IN_BULK
#define RPC_CALL1_IN_BULK (fn, thread, id, in, len) rpc_call1_in_bulk(thread, id, in, len)
Definition at line 750 of file khrn_client_rpc.h.
RPC_CALL1_IN_BULK_RES
#define RPC_CALL1_IN_BULK_RES (fn, thread, id, in, len) rpc_call1_in_bulk_res(thread, id, in, len)
Definition at line 798 of file khrn_client_rpc.h.
RPC_CALL1_IN_CTRL
#define RPC_CALL1_IN_CTRL (fn, thread, id, in, len) rpc_call1_in_ctrl(thread, id, in, len)
Definition at line 661 of file khrn_client_rpc.h.
RPC_CALL1_OUT_BULK
#define RPC_CALL1_OUT_BULK (fn, thread, id, out) rpc_call1_out_bulk(thread, id, out)
Definition at line 774 of file khrn_client_rpc.h.
RPC_CALL1_OUT_BULK_RES
#define RPC_CALL1_OUT_BULK_RES (fn, thread, id, out) rpc_call1_out_bulk_res(thread, id, out)
Definition at line 822 of file khrn_client_rpc.h.
RPC_CALL1_OUT_CTRL
#define RPC_CALL1_OUT_CTRL (fn, thread, id, out) rpc_call1_out_ctrl(thread, id, out)
Definition at line 690 of file khrn_client_rpc.h.
RPC_CALL1_OUT_CTRL_RES
#define RPC_CALL1_OUT_CTRL_RES (fn, thread, id, out) rpc_call1_out_ctrl_res(thread, id, out)
Definition at line 719 of file khrn_client_rpc.h.
RPC_CALL1_RES
#define RPC_CALL1_RES (fn, thread, id, p0) rpc_call1_res(thread, id, p0)
Definition at line 630 of file khrn_client_rpc.h.
RPC_CALL2
#define RPC_CALL2 (fn, thread, id, p0, p1) rpc_call2(thread, id, p0, p1)
Definition at line 571 of file khrn_client_rpc.h.
RPC_CALL2_IN_BULK
#define RPC_CALL2_IN_BULK (fn, thread, id, p0, in, len) rpc_call2_in_bulk(thread, id, p0, in, len)
Definition at line 751 of file khrn_client_rpc.h.
RPC_CALL2_IN_BULK_RES
#define RPC_CALL2_IN_BULK_RES (fn, thread, id, p0, in, len) rpc_call2_in_bulk_res(thread, id, p0, in, len)
Definition at line 799 of file khrn_client_rpc.h.
RPC_CALL2_IN_CTRL
#define RPC_CALL2_IN_CTRL (fn, thread, id, p0, in, len) rpc_call2_in_ctrl(thread, id, p0, in, len)
Definition at line 662 of file khrn_client_rpc.h.
RPC_CALL2_OUT_BULK
#define RPC_CALL2_OUT_BULK (fn, thread, id, p0, out) rpc_call2_out_bulk(thread, id, p0, out)
Definition at line 775 of file khrn_client_rpc.h.
RPC_CALL2_OUT_BULK_RES
#define RPC_CALL2_OUT_BULK_RES (fn, thread, id, p0, out) rpc_call2_out_bulk_res(thread, id, p0, out)
Definition at line 823 of file khrn_client_rpc.h.
RPC_CALL2_OUT_CTRL
#define RPC_CALL2_OUT_CTRL (fn, thread, id, p0, out) rpc_call2_out_ctrl(thread, id, p0, out)
Definition at line 691 of file khrn_client_rpc.h.
RPC_CALL2_OUT_CTRL_RES
#define RPC_CALL2_OUT_CTRL_RES (fn, thread, id, p0, out) rpc_call2_out_ctrl_res(thread, id, p0, out)
Definition at line 720 of file khrn_client_rpc.h.
RPC_CALL2_RES
#define RPC_CALL2_RES (fn, thread, id, p0, p1) rpc_call2_res(thread, id, p0, p1)
Definition at line 631 of file khrn_client_rpc.h.
RPC_CALL3
#define RPC_CALL3 (fn, thread, id, p0, p1, p2) rpc_call3(thread, id, p0, p1, p2)
Definition at line 572 of file khrn_client_rpc.h.
RPC_CALL3_IN_BULK
#define RPC_CALL3_IN_BULK (fn, thread, id, p0, p1, in, len) rpc_call3_in_bulk(thread, id, p0, p1, in, len)
Definition at line 752 of file khrn_client_rpc.h.
RPC_CALL3_IN_BULK_RES
#define RPC_CALL3_IN_BULK_RES (fn, thread, id, p0, p1, in, len) rpc_call3_in_bulk_res(thread, id, p0, p1, in, len)
Definition at line 800 of file khrn_client_rpc.h.
RPC_CALL3_IN_CTRL
#define RPC_CALL3_IN_CTRL (fn, thread, id, p0, p1, in, len) rpc_call3_in_ctrl(thread, id, p0, p1, in, len)
Definition at line 663 of file khrn_client_rpc.h.
RPC_CALL3_OUT_BULK
#define RPC_CALL3_OUT_BULK (fn, thread, id, p0, p1, out) rpc_call3_out_bulk(thread, id, p0, p1, out)
Definition at line 776 of file khrn_client_rpc.h.
RPC_CALL3_OUT_BULK_RES
#define RPC_CALL3_OUT_BULK_RES (fn, thread, id, p0, p1, out) rpc_call3_out_bulk_res(thread, id, p0, p1, out)
Definition at line 824 of file khrn_client_rpc.h.
RPC_CALL3_OUT_CTRL
#define RPC_CALL3_OUT_CTRL (fn, thread, id, p0, p1, out) rpc_call3_out_ctrl(thread, id, p0, p1, out)
Definition at line 692 of file khrn_client_rpc.h.
RPC_CALL3_OUT_CTRL_RES
#define RPC_CALL3_OUT_CTRL_RES (fn, thread, id, p0, p1, out) rpc_call3_out_ctrl_res(thread, id, p0, p1, out)
Definition at line 721 of file khrn_client_rpc.h.
RPC_CALL3_RES
#define RPC_CALL3_RES (fn, thread, id, p0, p1, p2) rpc_call3_res(thread, id, p0, p1, p2)
Definition at line 632 of file khrn_client_rpc.h.
RPC_CALL4
#define RPC_CALL4 (fn, thread, id, p0, p1, p2, p3) rpc_call4(thread, id, p0, p1, p2, p3)
Definition at line 573 of file khrn_client_rpc.h.
RPC_CALL4_IN_BULK
#define RPC_CALL4_IN_BULK (fn, thread, id, p0, p1, p2, in, len) rpc_call4_in_bulk(thread, id, p0, p1, p2, in, len)
Definition at line 753 of file khrn_client_rpc.h.
RPC_CALL4_IN_BULK_RES
#define RPC_CALL4_IN_BULK_RES (fn, thread, id, p0, p1, p2, in, len) rpc_call4_in_bulk_res(thread, id, p0, p1, p2, in, len)
Definition at line 801 of file khrn_client_rpc.h.
RPC_CALL4_IN_CTRL
#define RPC_CALL4_IN_CTRL (fn, thread, id, p0, p1, p2, in, len) rpc_call4_in_ctrl(thread, id, p0, p1, p2, in, len)
Definition at line 664 of file khrn_client_rpc.h.
RPC_CALL4_OUT_BULK
#define RPC_CALL4_OUT_BULK (fn, thread, id, p0, p1, p2, out) rpc_call4_out_bulk(thread, id, p0, p1, p2, out)
Definition at line 777 of file khrn_client_rpc.h.
RPC_CALL4_OUT_BULK_RES
#define RPC_CALL4_OUT_BULK_RES (fn, thread, id, p0, p1, p2, out) rpc_call4_out_bulk_res(thread, id, p0, p1, p2, out)
Definition at line 825 of file khrn_client_rpc.h.
RPC_CALL4_OUT_CTRL
#define RPC_CALL4_OUT_CTRL (fn, thread, id, p0, p1, p2, out) rpc_call4_out_ctrl(thread, id, p0, p1, p2, out)
Definition at line 693 of file khrn_client_rpc.h.
RPC_CALL4_OUT_CTRL_RES
#define RPC_CALL4_OUT_CTRL_RES (fn, thread, id, p0, p1, p2, out) rpc_call4_out_ctrl_res(thread, id, p0, p1, p2, out)
Definition at line 722 of file khrn_client_rpc.h.
RPC_CALL4_RES
#define RPC_CALL4_RES (fn, thread, id, p0, p1, p2, p3) rpc_call4_res(thread, id, p0, p1, p2, p3)
Definition at line 633 of file khrn_client_rpc.h.
RPC_CALL5
#define RPC_CALL5 (fn, thread, id, p0, p1, p2, p3, p4) rpc_call5(thread, id, p0, p1, p2, p3, p4)
Definition at line 574 of file khrn_client_rpc.h.
RPC_CALL5_IN_BULK
#define RPC_CALL5_IN_BULK (fn, thread, id, p0, p1, p2, p3, in, len) rpc_call5_in_bulk(thread, id, p0, p1, p2, p3, in, len)
Definition at line 754 of file khrn_client_rpc.h.
RPC_CALL5_IN_BULK_RES
#define RPC_CALL5_IN_BULK_RES (fn, thread, id, p0, p1, p2, p3, in, len) rpc_call5_in_bulk_res(thread, id, p0, p1, p2, p3, in, len)
Definition at line 802 of file khrn_client_rpc.h.
RPC_CALL5_IN_CTRL
#define RPC_CALL5_IN_CTRL (fn, thread, id, p0, p1, p2, p3, in, len) rpc_call5_in_ctrl(thread, id, p0, p1, p2, p3, in, len)
Definition at line 665 of file khrn_client_rpc.h.
RPC_CALL5_OUT_BULK
#define RPC_CALL5_OUT_BULK (fn, thread, id, p0, p1, p2, p3, out) rpc_call5_out_bulk(thread, id, p0, p1, p2, p3, out)
Definition at line 778 of file khrn_client_rpc.h.
RPC_CALL5_OUT_BULK_RES
#define RPC_CALL5_OUT_BULK_RES (fn, thread, id, p0, p1, p2, p3, out) rpc_call5_out_bulk_res(thread, id, p0, p1, p2, p3, out)
Definition at line 826 of file khrn_client_rpc.h.
RPC_CALL5_OUT_CTRL
#define RPC_CALL5_OUT_CTRL (fn, thread, id, p0, p1, p2, p3, out) rpc_call5_out_ctrl(thread, id, p0, p1, p2, p3, out)
Definition at line 694 of file khrn_client_rpc.h.
RPC_CALL5_OUT_CTRL_RES
#define RPC_CALL5_OUT_CTRL_RES (fn, thread, id, p0, p1, p2, p3, out) rpc_call5_out_ctrl_res(thread, id, p0, p1, p2, p3, out)
Definition at line 723 of file khrn_client_rpc.h.
RPC_CALL5_RES
#define RPC_CALL5_RES (fn, thread, id, p0, p1, p2, p3, p4) rpc_call5_res(thread, id, p0, p1, p2, p3, p4)
Definition at line 634 of file khrn_client_rpc.h.
RPC_CALL6
#define RPC_CALL6 (fn, thread, id, p0, p1, p2, p3, p4, p5) rpc_call6(thread, id, p0, p1, p2, p3, p4, p5)
Definition at line 575 of file khrn_client_rpc.h.
RPC_CALL6_IN_BULK
#define RPC_CALL6_IN_BULK (fn, thread, id, p0, p1, p2, p3, p4, in, len) rpc_call6_in_bulk(thread, id, p0, p1, p2, p3, p4, in, len)
Definition at line 755 of file khrn_client_rpc.h.
RPC_CALL6_IN_BULK_RES
#define RPC_CALL6_IN_BULK_RES (fn, thread, id, p0, p1, p2, p3, p4, in, len) rpc_call6_in_bulk_res(thread, id, p0, p1, p2, p3, p4, in, len)
Definition at line 803 of file khrn_client_rpc.h.
RPC_CALL6_IN_CTRL
#define RPC_CALL6_IN_CTRL (fn, thread, id, p0, p1, p2, p3, p4, in, len) rpc_call6_in_ctrl(thread, id, p0, p1, p2, p3, p4, in, len)
Definition at line 666 of file khrn_client_rpc.h.
RPC_CALL6_OUT_BULK
#define RPC_CALL6_OUT_BULK (fn, thread, id, p0, p1, p2, p3, p4, out) rpc_call6_out_bulk(thread, id, p0, p1, p2, p3, p4, out)
Definition at line 779 of file khrn_client_rpc.h.
RPC_CALL6_OUT_BULK_RES
#define RPC_CALL6_OUT_BULK_RES (fn, thread, id, p0, p1, p2, p3, p4, out) rpc_call6_out_bulk_res(thread, id, p0, p1, p2, p3, p4, out)
Definition at line 827 of file khrn_client_rpc.h.
RPC_CALL6_OUT_CTRL
#define RPC_CALL6_OUT_CTRL (fn, thread, id, p0, p1, p2, p3, p4, out) rpc_call6_out_ctrl(thread, id, p0, p1, p2, p3, p4, out)
Definition at line 695 of file khrn_client_rpc.h.
RPC_CALL6_OUT_CTRL_RES
#define RPC_CALL6_OUT_CTRL_RES (fn, thread, id, p0, p1, p2, p3, p4, out) rpc_call6_out_ctrl_res(thread, id, p0, p1, p2, p3, p4, out)
Definition at line 724 of file khrn_client_rpc.h.
RPC_CALL6_RES
#define RPC_CALL6_RES (fn, thread, id, p0, p1, p2, p3, p4, p5) rpc_call6_res(thread, id, p0, p1, p2, p3, p4, p5)
Definition at line 635 of file khrn_client_rpc.h.
RPC_CALL7
#define RPC_CALL7 (fn, thread, id, p0, p1, p2, p3, p4, p5, p6) rpc_call7(thread, id, p0, p1, p2, p3, p4, p5, p6)
Definition at line 576 of file khrn_client_rpc.h.
RPC_CALL7_IN_BULK
#define RPC_CALL7_IN_BULK (fn, thread, id, p0, p1, p2, p3, p4, p5, in, len) rpc_call7_in_bulk(thread, id, p0, p1, p2, p3, p4, p5, in, len)
Definition at line 756 of file khrn_client_rpc.h.
RPC_CALL7_IN_BULK_RES
#define RPC_CALL7_IN_BULK_RES (fn, thread, id, p0, p1, p2, p3, p4, p5, in, len) rpc_call7_in_bulk_res(thread, id, p0, p1, p2, p3, p4, p5, in, len)
Definition at line 804 of file khrn_client_rpc.h.
RPC_CALL7_IN_CTRL
#define RPC_CALL7_IN_CTRL (fn, thread, id, p0, p1, p2, p3, p4, p5, in, len) rpc_call7_in_ctrl(thread, id, p0, p1, p2, p3, p4, p5, in, len)
Definition at line 667 of file khrn_client_rpc.h.
RPC_CALL7_OUT_BULK
#define RPC_CALL7_OUT_BULK (fn, thread, id, p0, p1, p2, p3, p4, p5, out) rpc_call7_out_bulk(thread, id, p0, p1, p2, p3, p4, p5, out)
Definition at line 780 of file khrn_client_rpc.h.
RPC_CALL7_OUT_BULK_RES
#define RPC_CALL7_OUT_BULK_RES (fn, thread, id, p0, p1, p2, p3, p4, p5, out) rpc_call7_out_bulk_res(thread, id, p0, p1, p2, p3, p4, p5, out)
Definition at line 828 of file khrn_client_rpc.h.
RPC_CALL7_OUT_CTRL
#define RPC_CALL7_OUT_CTRL (fn, thread, id, p0, p1, p2, p3, p4, p5, out) rpc_call7_out_ctrl(thread, id, p0, p1, p2, p3, p4, p5, out)
Definition at line 696 of file khrn_client_rpc.h.
RPC_CALL7_OUT_CTRL_RES
#define RPC_CALL7_OUT_CTRL_RES (fn, thread, id, p0, p1, p2, p3, p4, p5, out) rpc_call7_out_ctrl_res(thread, id, p0, p1, p2, p3, p4, p5, out)
Definition at line 725 of file khrn_client_rpc.h.
RPC_CALL7_RES
#define RPC_CALL7_RES (fn, thread, id, p0, p1, p2, p3, p4, p5, p6) rpc_call7_res(thread, id, p0, p1, p2, p3, p4, p5, p6)
Definition at line 636 of file khrn_client_rpc.h.
RPC_CALL8
#define RPC_CALL8 (fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7) rpc_call8(thread, id, p0, p1, p2, p3, p4, p5, p6, p7)
Definition at line 577 of file khrn_client_rpc.h.
Referenced by rpc_call8_makecurrent().
RPC_CALL8_IN_BULK
#define RPC_CALL8_IN_BULK (fn, thread, id, p0, p1, p2, p3, p4, p5, p6, in, len) rpc_call8_in_bulk(thread, id, p0, p1, p2, p3, p4, p5, p6, in, len)
Definition at line 757 of file khrn_client_rpc.h.
RPC_CALL8_IN_BULK_RES
#define RPC_CALL8_IN_BULK_RES (fn, thread, id, p0, p1, p2, p3, p4, p5, p6, in, len) rpc_call8_in_bulk_res(thread, id, p0, p1, p2, p3, p4, p5, p6, in, len)
Definition at line 805 of file khrn_client_rpc.h.
RPC_CALL8_IN_CTRL
#define RPC_CALL8_IN_CTRL (fn, thread, id, p0, p1, p2, p3, p4, p5, p6, in, len) rpc_call8_in_ctrl(thread, id, p0, p1, p2, p3, p4, p5, p6, in, len)
Definition at line 668 of file khrn_client_rpc.h.
RPC_CALL8_MAKECURRENT
#define RPC_CALL8_MAKECURRENT (fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7) rpc_call8_makecurrent(thread, id, p0, p1, p2, p3, p4, p5, p6, p7)
Definition at line 458 of file khrn_client_rpc.h.
RPC_CALL8_OUT_BULK
#define RPC_CALL8_OUT_BULK (fn, thread, id, p0, p1, p2, p3, p4, p5, p6, out) rpc_call8_out_bulk(thread, id, p0, p1, p2, p3, p4, p5, p6, out)
Definition at line 781 of file khrn_client_rpc.h.
RPC_CALL8_OUT_BULK_RES
#define RPC_CALL8_OUT_BULK_RES (fn, thread, id, p0, p1, p2, p3, p4, p5, p6, out) rpc_call8_out_bulk_res(thread, id, p0, p1, p2, p3, p4, p5, p6, out)
Definition at line 829 of file khrn_client_rpc.h.
RPC_CALL8_OUT_CTRL
#define RPC_CALL8_OUT_CTRL (fn, thread, id, p0, p1, p2, p3, p4, p5, p6, out) rpc_call8_out_ctrl(thread, id, p0, p1, p2, p3, p4, p5, p6, out)
Definition at line 697 of file khrn_client_rpc.h.
RPC_CALL8_OUT_CTRL_RES
#define RPC_CALL8_OUT_CTRL_RES (fn, thread, id, p0, p1, p2, p3, p4, p5, p6, out) rpc_call8_out_ctrl_res(thread, id, p0, p1, p2, p3, p4, p5, p6, out)
Definition at line 726 of file khrn_client_rpc.h.
RPC_CALL8_RES
#define RPC_CALL8_RES (fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7) rpc_call8_res(thread, id, p0, p1, p2, p3, p4, p5, p6, p7)
Definition at line 637 of file khrn_client_rpc.h.
RPC_CALL9
#define RPC_CALL9 (fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8) rpc_call9(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8)
Definition at line 578 of file khrn_client_rpc.h.
RPC_CALL9_IN_BULK
#define RPC_CALL9_IN_BULK (fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, in, len) rpc_call9_in_bulk(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, in, len)
Definition at line 758 of file khrn_client_rpc.h.
RPC_CALL9_IN_BULK_RES
#define RPC_CALL9_IN_BULK_RES (fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, in, len) rpc_call9_in_bulk_res(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, in, len)
Definition at line 806 of file khrn_client_rpc.h.
RPC_CALL9_IN_CTRL
#define RPC_CALL9_IN_CTRL (fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, in, len) rpc_call9_in_ctrl(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, in, len)
Definition at line 669 of file khrn_client_rpc.h.
RPC_CALL9_OUT_BULK
#define RPC_CALL9_OUT_BULK (fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, out) rpc_call9_out_bulk(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, out)
Definition at line 782 of file khrn_client_rpc.h.
RPC_CALL9_OUT_BULK_RES
#define RPC_CALL9_OUT_BULK_RES (fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, out) rpc_call9_out_bulk_res(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, out)
Definition at line 830 of file khrn_client_rpc.h.
RPC_CALL9_OUT_CTRL
#define RPC_CALL9_OUT_CTRL (fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, out) rpc_call9_out_ctrl(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, out)
Definition at line 698 of file khrn_client_rpc.h.
RPC_CALL9_OUT_CTRL_RES
#define RPC_CALL9_OUT_CTRL_RES (fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, out) rpc_call9_out_ctrl_res(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, out)
Definition at line 727 of file khrn_client_rpc.h.
RPC_CALL9_RES
#define RPC_CALL9_RES (fn, thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8) rpc_call9_res(thread, id, p0, p1, p2, p3, p4, p5, p6, p7, p8)
Definition at line 638 of file khrn_client_rpc.h.
RPC_CALL_IN_BULK
#define RPC_CALL_IN_BULK (thread, IN, LEN, ...)
Value:
do { \
         const void *in_ = IN; \
         uint32_t len_ = LEN; \
         uint32_t message_[] = { __VA_ARGS__, in_ ? len_ : LENGTH_SIGNAL_NULL }; \
         rpc_send_ctrl_begin(thread, sizeof(message_)); \
         rpc_send_ctrl_write(thread, message_, sizeof(message_)); \
         rpc_send_ctrl_end(thread); \
         rpc_send_bulk(thread, in_, len_); \
      } while (0)
Definition at line 530 of file khrn_client_rpc.h.
RPC_CALL_IN_CTRL
#define RPC_CALL_IN_CTRL (thread, IN, LEN, ...)
Value:
do { \
         const void *in_ = IN; \
         uint32_t len_ = LEN; \
         uint32_t message_[] = { __VA_ARGS__ }; \
         rpc_send_ctrl_begin(thread, sizeof(message_) + rpc_pad_ctrl(len_)); \
         rpc_send_ctrl_write(thread, message_, sizeof(message_)); \
         rpc_send_ctrl_write(thread, in_, len_); \
         rpc_send_ctrl_end(thread); \
      } while (0)
Definition at line 519 of file khrn_client_rpc.h.
RPC_DELAYED_USE_OF_POINTERS
#define RPC_DELAYED_USE_OF_POINTERS
Definition at line 31 of file khrn_client_rpc.h.
RPC_EGLID
#define RPC_EGLID (i) ((uint32_t)(size_t)(i))
Definition at line 437 of file khrn_client_rpc.h.
RPC_ENUM
#define RPC_ENUM (e) ((uint32_t)(e))
Definition at line 427 of file khrn_client_rpc.h.
RPC_ENUM_RES
#define RPC_ENUM_RES (e) ((GLenum)(e))
Definition at line 440 of file khrn_client_rpc.h.
RPC_FIXED
#define RPC_FIXED (f) ((uint32_t)(f))
Definition at line 435 of file khrn_client_rpc.h.
RPC_FLOAT
#define RPC_FLOAT (f) (float_to_bits(f))
Definition at line 426 of file khrn_client_rpc.h.
RPC_FLOAT_RES
#define RPC_FLOAT_RES (f) (float_from_bits(f))
Definition at line 439 of file khrn_client_rpc.h.
RPC_FLUSH
#define RPC_FLUSH (thread) rpc_flush(thread)
Definition at line 454 of file khrn_client_rpc.h.
RPC_HANDLE
#define RPC_HANDLE (h) ((uint32_t)(h))
Definition at line 436 of file khrn_client_rpc.h.
RPC_HANDLE_RES
#define RPC_HANDLE_RES (h) ((VGHandle)(h))
Definition at line 445 of file khrn_client_rpc.h.
RPC_HIGH_PRIORITY_BEGIN
#define RPC_HIGH_PRIORITY_BEGIN (thread) rpc_high_priority_begin(thread)
Definition at line 455 of file khrn_client_rpc.h.
RPC_HIGH_PRIORITY_END
#define RPC_HIGH_PRIORITY_END (thread) rpc_high_priority_end(thread)
Definition at line 456 of file khrn_client_rpc.h.
RPC_INIT
#define RPC_INIT () khclient_rpc_init()
Definition at line 451 of file khrn_client_rpc.h.
Referenced by client_process_attach().
RPC_INT
#define RPC_INT (i) ((uint32_t)(i))
Definition at line 428 of file khrn_client_rpc.h.
RPC_INT_RES
#define RPC_INT_RES (i) ((GLint)(i))
Definition at line 441 of file khrn_client_rpc.h.
RPC_INTPTR
#define RPC_INTPTR (p) ((uint32_t)(p))
Definition at line 429 of file khrn_client_rpc.h.
RPC_SIZEI
#define RPC_SIZEI (s) ((uint32_t)(s))
Definition at line 431 of file khrn_client_rpc.h.
RPC_SIZEIPTR
#define RPC_SIZEIPTR (p) ((uint32_t)(p))
Definition at line 432 of file khrn_client_rpc.h.
RPC_TERM
#define RPC_TERM () rpc_term()
Definition at line 452 of file khrn_client_rpc.h.
Referenced by client_process_detach().
RPC_UINT
#define RPC_UINT (u) ((uint32_t)(u))
Definition at line 430 of file khrn_client_rpc.h.
RPC_UINT_RES
#define RPC_UINT_RES (u) ((GLuint)(u))
Definition at line 442 of file khrn_client_rpc.h.
Enumeration Type Documentation
RPC_RECV_FLAG_T
enum RPC_RECV_FLAG_T
Enumerator
RPC_RECV_FLAG_RES
RPC_RECV_FLAG_CTRL
RPC_RECV_FLAG_BULK
RPC_RECV_FLAG_BULK_SCATTER
RPC_RECV_FLAG_LEN
Definition at line 368 of file khrn_client_rpc.h.
              {
    RPC_RECV_FLAG_RES          = 1 << 0,
    RPC_RECV_FLAG_CTRL         = 1 << 1,
    RPC_RECV_FLAG_BULK         = 1 << 2, /* len bytes written, rpc_pad_bulk(len) bytes read */
    RPC_RECV_FLAG_BULK_SCATTER = 1 << 3, /* len = { len, stride, n, first_mask, last_mask }, n * len bytes written, rpc_pad_bulk(n * len) bytes read */
    RPC_RECV_FLAG_LEN          = 1 << 4  /* len provided by other side */
 } RPC_RECV_FLAG_T;
Function Documentation
khclient_rpc_init()
bool khclient_rpc_init (void)
Definition at line 231 of file khrn_client_rpc_linux.c.
 {
    workspace = NULL;
    return platform_mutex_create(&mutex) == KHR_SUCCESS;
 }
khronos_kernel_semaphore_acquire()
uint32_t khronos_kernel_semaphore_acquire (uint32_t semaphore)
khronos_kernel_semaphore_acquire_and_release()
uint32_t khronos_kernel_semaphore_acquire_and_release (uint32_t semaphore)
khronos_kernel_semaphore_create()
uint32_t khronos_kernel_semaphore_create (uint32_t name, uint32_t count)
khronos_kernel_semaphore_destroy()
uint32_t khronos_kernel_semaphore_destroy (uint32_t semaphore)
khronos_kernel_semaphore_release()
uint32_t khronos_kernel_semaphore_release (uint32_t semaphore)
rpc_begin()
void rpc_begin (CLIENT_THREAD_STATE_T * thread)
Definition at line 481 of file khrn_client_rpc_linux.c.
References platform_mutex_acquire(), and UNUSED.
Referenced by rpc_call8_makecurrent().
 {
    UNUSED(thread);
    platform_mutex_acquire(&mutex);
 }
rpc_call8_makecurrent()
void rpc_call8_makecurrent (CLIENT_THREAD_STATE_T * thread, uint32_t id, uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4, uint32_t p5, uint32_t p6, uint32_t p7)
Definition at line 503 of file khrn_client_rpc_linux.c.
References CLIENT_MAKE_CURRENT_SIZE, EGLINTMAKECURRENT_ID, CLIENT_THREAD_STATE::merge_buffer, CLIENT_THREAD_STATE::merge_pos, rpc_begin(), RPC_CALL8, rpc_end(), and vcos_assert.
 {
    uint32_t data;
    if (thread->merge_pos == CLIENT_MAKE_CURRENT_SIZE && (memcpy(&data,thread->merge_buffer,sizeof(data)), data == EGLINTMAKECURRENT_ID))
    {
       rpc_begin(thread);
       vcos_log_trace("rpc_call8_makecurrent collapse onto previous makecurrent");
       thread->merge_pos = 0;
       RPC_CALL8(eglIntMakeCurrent_impl, thread, EGLINTMAKECURRENT_ID, p0, p1, p2, p3, p4, p5, p6, p7);
       vcos_assert(thread->merge_pos == CLIENT_MAKE_CURRENT_SIZE);
       rpc_end(thread);
    }
    else
    {
       RPC_CALL8(eglIntMakeCurrent_impl, thread, EGLINTMAKECURRENT_ID, p0, p1, p2, p3, p4, p5, p6, p7);
    }
 }
rpc_end()
void rpc_end (CLIENT_THREAD_STATE_T * thread)
Definition at line 487 of file khrn_client_rpc_linux.c.
References platform_mutex_release(), and UNUSED.
Referenced by rpc_call8_makecurrent().
 {
    UNUSED(thread);
    platform_mutex_release(&mutex);
 }
rpc_flush()
void rpc_flush (CLIENT_THREAD_STATE_T * thread)
Definition at line 300 of file khrn_client_rpc_linux.c.
 {
    merge_flush(thread);
 }
rpc_get_client_id()
uint64_t rpc_get_client_id (CLIENT_THREAD_STATE_T * thread)
Definition at line 525 of file khrn_client_rpc_linux.c.
References vchiq_get_client_id().
Referenced by client_send_make_current().
 {
    return vchiq_get_client_id(get_handle(thread));
 }
rpc_high_priority_begin()
void rpc_high_priority_begin (CLIENT_THREAD_STATE_T * thread)
Definition at line 305 of file khrn_client_rpc_linux.c.
References CLIENT_THREAD_STATE::high_priority, and vcos_assert.
 {
    vcos_assert(!thread->high_priority);
    merge_flush(thread);
    thread->high_priority = true;
 }
rpc_high_priority_end()
void rpc_high_priority_end (CLIENT_THREAD_STATE_T * thread)
Definition at line 312 of file khrn_client_rpc_linux.c.
References CLIENT_THREAD_STATE::high_priority, and vcos_assert.
 {
    vcos_assert(thread->high_priority);
    merge_flush(thread);
    thread->high_priority = false;
 }
rpc_recv()
uint32_t rpc_recv (CLIENT_THREAD_STATE_T * thread, void * out, uint32_t * len, RPC_RECV_FLAG_T flags)
Definition at line 427 of file khrn_client_rpc_linux.c.
References len, RPC_RECV_FLAG_BULK, RPC_RECV_FLAG_CTRL, RPC_RECV_FLAG_LEN, RPC_RECV_FLAG_RES, and vcos_assert.
 {
    uint32_t res = 0;
    uint32_t len;
    bool recv_ctrl;
    if (!len_io) { len_io = &len; }
    recv_ctrl = flags & (RPC_RECV_FLAG_RES | RPC_RECV_FLAG_CTRL | RPC_RECV_FLAG_LEN); /* do we want to receive anything in the control channel at all? */
    vcos_assert(recv_ctrl || (flags & RPC_RECV_FLAG_BULK)); /* must receive something... */
    vcos_assert(!(flags & RPC_RECV_FLAG_CTRL) || !(flags & RPC_RECV_FLAG_BULK)); /* can't receive user data over both bulk and control... */
    if (recv_ctrl || len_io[0]) { /* do nothing if we're just receiving bulk of length 0 */
       merge_flush(thread);
       if (recv_ctrl) {
          VCHIQ_HEADER_T *header = vchiu_queue_pop(get_queue(thread));
          uint8_t *ctrl = (uint8_t *)header->data;
          vcos_assert(header->size >= (!!(flags & RPC_RECV_FLAG_LEN)*4 + !!(flags & RPC_RECV_FLAG_RES)*4) );
          if (flags & RPC_RECV_FLAG_LEN) {
             len_io[0] = *((uint32_t *)ctrl);
             ctrl += 4;
          }
          if (flags & RPC_RECV_FLAG_RES) {
             res = *((uint32_t *)ctrl);
             ctrl += 4;
          }
          if (flags & RPC_RECV_FLAG_CTRL) {
             memcpy(out, ctrl, len_io[0]);
             ctrl += len_io[0];
          }
          vcos_assert(ctrl == ((uint8_t *)header->data + header->size));
          vchiq_release_message(get_handle(thread), header);
       }
       if ((flags & RPC_RECV_FLAG_BULK) && len_io[0]) {
          if (flags & RPC_RECV_FLAG_BULK_SCATTER) {
             if ((len_io[0] == len_io[1]) && !len_io[3] && !len_io[4]) {
                /* hopefully should be the common case */
                recv_bulk(thread, out, len_io[2] * len_io[0]);
             } else {
                check_workspace(len_io[2] * len_io[0]);
                recv_bulk(thread, workspace, len_io[2] * len_io[0]);
                rpc_scatter(out, len_io[0], len_io[1], len_io[2], len_io[3], len_io[4], workspace);
             }
          } else {
             recv_bulk(thread, out, len_io[0]);
          }
       }
    }
    return res;
 }
rpc_recv_bulk_gather()
void rpc_recv_bulk_gather (CLIENT_THREAD_STATE_T * thread, void * out, uint32_t * len, RPC_RECV_FLAG_T flags)
rpc_send_bulk()
void rpc_send_bulk (CLIENT_THREAD_STATE_T * thread, const void * in, uint32_t len)
Definition at line 394 of file khrn_client_rpc_linux.c.
 {
    if (in && len) {
       //CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
       merge_flush(thread);
       send_bulk(thread, in, len);
    }
 }
rpc_send_bulk_gather()
void rpc_send_bulk_gather (CLIENT_THREAD_STATE_T * thread, const void * in, uint32_t len, int32_t stride, uint32_t n)
Definition at line 405 of file khrn_client_rpc_linux.c.
 {
 #if 1
    if (in && len) {
       //CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
       merge_flush(thread);
       if (len == stride) {
          /* hopefully should be the common case */
          send_bulk(thread, in, n * len);
       } else {
          check_workspace(n * len);
          rpc_gather(workspace, in, len, stride, n);
          send_bulk(thread, workspace, n * len);
       }
    }
 #else
    UNREACHABLE();
 #endif
 }
rpc_send_ctrl_begin()
void rpc_send_ctrl_begin (CLIENT_THREAD_STATE_T * thread, uint32_t len)
Definition at line 328 of file khrn_client_rpc_linux.c.
References vcos_assert.
 {
    //CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    vcos_assert(len == rpc_pad_ctrl(len));
    if ((thread->merge_pos + len) > MERGE_BUFFER_SIZE) {
       merge_flush(thread);
    }
    thread->merge_end = thread->merge_pos + len;
 }
rpc_send_ctrl_end()
void rpc_send_ctrl_end (CLIENT_THREAD_STATE_T * thread)
Definition at line 349 of file khrn_client_rpc_linux.c.
References CLIENT_THREAD_STATE::merge_end, CLIENT_THREAD_STATE::merge_pos, and vcos_assert.
 {
    //CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    vcos_assert(thread->merge_pos == thread->merge_end);
 }
rpc_send_ctrl_longest()
uint32_t rpc_send_ctrl_longest (CLIENT_THREAD_STATE_T * thread, uint32_t len_min)
Definition at line 319 of file khrn_client_rpc_linux.c.
References CLIENT_MAKE_CURRENT_SIZE, len, MERGE_BUFFER_SIZE, and CLIENT_THREAD_STATE::merge_pos.
 {
    uint32_t len = MERGE_BUFFER_SIZE - thread->merge_pos;
    if (len < len_min) {
       len = MERGE_BUFFER_SIZE - CLIENT_MAKE_CURRENT_SIZE;
    }
    return len;
 }
rpc_send_ctrl_write()
void rpc_send_ctrl_write (CLIENT_THREAD_STATE_T * thread, const uint32_t msg[], uint32_t msglen)
Definition at line 340 of file khrn_client_rpc_linux.c.
References CLIENT_THREAD_STATE::merge_buffer, and CLIENT_THREAD_STATE::merge_pos.
 {
    //CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    memcpy(thread->merge_buffer + thread->merge_pos, in, len);
    thread->merge_pos += rpc_pad_ctrl(len);
    vcos_assert(thread->merge_pos <= MERGE_BUFFER_SIZE);
 }
rpc_term()
void rpc_term (void)
Definition at line 237 of file khrn_client_rpc_linux.c.
 {
    if (workspace) { khrn_platform_free(workspace); }
    platform_mutex_destroy(&mutex);
 }