VideoCore Library: interface/vcos/vcos_once.h File Reference
vcos_once.h File Reference
#include "interface/vcos/vcos_types.h"
#include "vcos.h"
Functions
VCOS_STATUS_T vcos_once (VCOS_ONCE_T *once_control, void(*init_routine)(void))
Detailed Description
Ensure something is called only once.
Initialize once_control to VCOS_ONCE_INIT. The first time this is called, the init_routine will be called. Thereafter it won't.
See also
pthread_once()
Definition in file vcos_once.h.
Function Documentation
vcos_once()
VCOS_STATUS_T vcos_once (VCOS_ONCE_T * once_control, void(*)(void) init_routine)
Definition at line 609 of file vcos_pthreads.c.
References vcos_assert, VCOS_EACCESS, VCOS_EINVAL, and VCOS_SUCCESS.
Referenced by mmal_vc_init_fd(), mmal_vc_shm_init(), OMX_Init(), vc_gpuserv_init(), vcos_cmd_execute(), vcos_cmd_register(), vcos_dummy_thread_create(), vcos_platform_init(), vcsm_init_ex(), wfc_client_ipc_deinit(), wfc_client_ipc_init(), and wfcCreateDevice().
 {
    int rc = pthread_once(once_control, init_routine);
    if (rc != 0)
    {
       switch (errno)
       {
       case EINVAL:
          return VCOS_EINVAL;
       default:
          vcos_assert(0);
          return VCOS_EACCESS;
       }
    }
    else
    {
       return VCOS_SUCCESS;
    }
 }