VideoCore Library: interface/vchi/vchi.h File Reference
vchi.h File Reference
#include "interface/vcos/vcos.h"
#include "interface/vchi/vchi_cfg.h"
#include "interface/vchi/vchi_common.h"
#include "interface/vchi/connections/connection.h"
#include "vchi_mh.h"
Classes
struct VCHI_VERSION_T
struct vchi_msg_vector_ex
struct VCHI_HELD_MSG_T
struct SERVICE_CREATION_T
struct service_info_tag
Macros
#define VCHI_H_
#define VCHI_SERVICE_HANDLE_INVALID 0
#define VCHI_BULK_ROUND_UP(x) ((((unsigned long)(x))+VCHI_BULK_ALIGN-1) & ~(VCHI_BULK_ALIGN-1))
#define VCHI_BULK_ROUND_DOWN(x) (((unsigned long)(x)) & ~(VCHI_BULK_ALIGN-1))
#define VCHI_BULK_ALIGN_NBYTES(x) (VCHI_BULK_ALIGNED(x) ? 0 : (VCHI_BULK_ALIGN - ((unsigned long)(x) & (VCHI_BULK_ALIGN-1))))
#define VCHI_BULK_ALIGNED(x) (((unsigned long)(x) & (VCHI_BULK_ALIGN-1)) == 0)
#define VCHI_VERSION(v_) { v_, v_ }
#define VCHI_VERSION_EX(v_, m_) { v_, m_ }
#define VCHI_VEC_POINTER(p, l) VCHI_VEC_POINTER, { { (VCHI_MEM_HANDLE_T)(p), (l) } }
#define VCHI_VEC_HANDLE(h, o, l) VCHI_VEC_HANDLE, { { (h), (o), (l) } }
#define MAKE_FOURCC(x) ((fourcc_t)((x[0] << 24) | (x[1] << 16) | (x[2] << 8) | x[3]))
#define FOURCC_TO_CHAR(x) (x >> 24) & 0xFF,(x >> 16) & 0xFF,(x >> 8) & 0xFF, x & 0xFF
#define VCHI_SERVICE_HANDLE_INVALID 0
#define VCHI_BULK_ROUND_UP(x) ((((unsigned long)(x))+VCHI_BULK_ALIGN-1) & ~(VCHI_BULK_ALIGN-1))
#define VCHI_BULK_ROUND_DOWN(x) (((unsigned long)(x)) & ~(VCHI_BULK_ALIGN-1))
#define VCHI_BULK_ALIGN_NBYTES(x) (VCHI_BULK_ALIGNED(x) ? 0 : (VCHI_BULK_ALIGN - ((unsigned long)(x) & (VCHI_BULK_ALIGN-1))))
#define VCHI_BULK_ALIGNED(x) (((unsigned long)(x) & (VCHI_BULK_ALIGN-1)) == 0)
#define VCHI_VERSION(v_) { v_, v_ }
#define VCHI_VERSION_EX(v_, m_) { v_, m_ }
#define VCHI_VEC_POINTER(p, l) VCHI_VEC_POINTER, { { (VCHI_MEM_HANDLE_T)(p), (l) } }
#define VCHI_VEC_HANDLE(h, o, l) VCHI_VEC_HANDLE, { { (h), (o), (l) } }
#define MAKE_FOURCC(x) ((fourcc_t)((x[0] << 24) | (x[1] << 16) | (x[2] << 8) | x[3]))
#define FOURCC_TO_CHAR(x) (x >> 24) & 0xFF,(x >> 16) & 0xFF,(x >> 8) & 0xFF, x & 0xFF
Typedefs
typedef struct vchi_msg_vector_ex VCHI_MSG_VECTOR_EX_T
typedef struct opaque_vchi_instance_handle_t * VCHI_INSTANCE_T
typedef unsigned int VCHI_SERVICE_HANDLE_T
typedef void(* VCHI_SERVICE_INIT) (VCHI_INSTANCE_T initialise_instance, VCHI_CONNECTION_T **connections, uint32_t num_connections)
typedef struct service_info_tag SERVICE_INFO_T
Enumerations
enum VCHI_MSG_VECTOR_TYPE_T { VCHI_VEC_POINTER, VCHI_VEC_HANDLE, VCHI_VEC_LIST }
Functions
VCHI_CONNECTION_T * vchi_create_connection (const VCHI_CONNECTION_API_T *function_table, const VCHI_MESSAGE_DRIVER_T *low_level)
int32_t vchi_initialise (VCHI_INSTANCE_T *instance_handle)
int32_t vchi_connect (VCHI_CONNECTION_T **connections, const uint32_t num_connections, VCHI_INSTANCE_T instance_handle)
int32_t vchi_disconnect (VCHI_INSTANCE_T instance_handle)
int32_t vchi_crc_control (VCHI_CONNECTION_T *connection, VCHI_CRC_CONTROL_T control)
void * vchi_allocate_buffer (VCHI_SERVICE_HANDLE_T handle, uint32_t *length)
void vchi_free_buffer (VCHI_SERVICE_HANDLE_T handle, void *address)
uint32_t vchi_current_time (VCHI_INSTANCE_T instance_handle)
int32_t vchi_service_create (VCHI_INSTANCE_T instance_handle, SERVICE_CREATION_T *setup, VCHI_SERVICE_HANDLE_T *handle)
int32_t vchi_service_destroy (const VCHI_SERVICE_HANDLE_T handle)
int32_t vchi_service_open (VCHI_INSTANCE_T instance_handle, SERVICE_CREATION_T *setup, VCHI_SERVICE_HANDLE_T *handle)
int32_t vchi_get_peer_version (const VCHI_SERVICE_HANDLE_T handle, short *peer_version)
int32_t vchi_service_close (const VCHI_SERVICE_HANDLE_T handle)
int32_t vchi_service_use (const VCHI_SERVICE_HANDLE_T handle)
int32_t vchi_service_release (const VCHI_SERVICE_HANDLE_T handle)
int32_t vchi_service_set_option (const VCHI_SERVICE_HANDLE_T handle, VCHI_SERVICE_OPTION_T option, int value)
int32_t vchi_msg_queue (VCHI_SERVICE_HANDLE_T handle, const void *data, uint32_t data_size, VCHI_FLAGS_T flags, void *msg_handle)
int32_t vchi_msg_queuev_ex (VCHI_SERVICE_HANDLE_T handle, VCHI_MSG_VECTOR_EX_T *vector, uint32_t count, VCHI_FLAGS_T flags, void *msg_handle)
int32_t vchi_msg_queuev (VCHI_SERVICE_HANDLE_T handle, VCHI_MSG_VECTOR_T *vector, uint32_t count, VCHI_FLAGS_T flags, void *msg_handle)
int32_t vchi_msg_dequeue (VCHI_SERVICE_HANDLE_T handle, void *data, uint32_t max_data_size_to_read, uint32_t *actual_msg_size, VCHI_FLAGS_T flags)
int32_t vchi_msg_peek (VCHI_SERVICE_HANDLE_T handle, void **data, uint32_t *msg_size, VCHI_FLAGS_T flags)
int32_t vchi_msg_remove (VCHI_SERVICE_HANDLE_T handle)
int32_t vchi_msg_hold (VCHI_SERVICE_HANDLE_T handle, void **data, uint32_t *msg_size, VCHI_FLAGS_T flags, VCHI_HELD_MSG_T *message_descriptor)
int32_t vchi_msg_look_ahead (VCHI_SERVICE_HANDLE_T handle, VCHI_MSG_ITER_T *iter, VCHI_FLAGS_T flags)
void * vchi_held_msg_ptr (const VCHI_HELD_MSG_T *message)
int32_t vchi_held_msg_size (const VCHI_HELD_MSG_T *message)
uint32_t vchi_held_msg_tx_timestamp (const VCHI_HELD_MSG_T *message)
uint32_t vchi_held_msg_rx_timestamp (const VCHI_HELD_MSG_T *message)
int32_t vchi_held_msg_release (VCHI_HELD_MSG_T *message)
vcos_bool_t vchi_msg_iter_has_next (const VCHI_MSG_ITER_T *iter)
int32_t vchi_msg_iter_next (VCHI_MSG_ITER_T *iter, void **data, uint32_t *msg_size)
int32_t vchi_msg_iter_remove (VCHI_MSG_ITER_T *iter)
int32_t vchi_msg_iter_hold (VCHI_MSG_ITER_T *iter, VCHI_HELD_MSG_T *message)
int32_t vchi_msg_iter_hold_next (VCHI_MSG_ITER_T *iter, void **data, uint32_t *msg_size, VCHI_HELD_MSG_T *message)
int32_t vchi_bulk_queue_receive (VCHI_SERVICE_HANDLE_T handle, void *data_dst, uint32_t data_size, VCHI_FLAGS_T flags, void *transfer_handle)
int32_t vchi_bulk_queue_receive_reloc (const VCHI_SERVICE_HANDLE_T handle, VCHI_MEM_HANDLE_T h_dst, uint32_t offset, uint32_t data_size, const VCHI_FLAGS_T flags, void *const bulk_handle)
int32_t vchi_bulk_queue_receive_reloc_func (const VCHI_SERVICE_HANDLE_T handle, VCHI_MEM_HANDLE_T h_dst, uint32_t offset, uint32_t data_size, const VCHI_FLAGS_T flags, void *const bulk_handle, int copy_pagelist(char *vcptr, const struct pagelist_struct *pagelist))
int32_t vchi_bulk_queue_transmit (VCHI_SERVICE_HANDLE_T handle, const void *data_src, uint32_t data_size, VCHI_FLAGS_T flags, void *transfer_handle)
const VCHI_CONNECTION_API_T * single_get_func_table (void)
const VCHI_MESSAGE_DRIVER_T * vchi_mphi_message_driver_func_table (void)
int32_t vchi_bulk_queue_transmit_reloc (VCHI_SERVICE_HANDLE_T handle, VCHI_MEM_HANDLE_T h_src, uint32_t offset, uint32_t data_size, VCHI_FLAGS_T flags, void *transfer_handle)
Macro Definition Documentation
FOURCC_TO_CHAR [1/2]
#define FOURCC_TO_CHAR (x) (x >> 24) & 0xFF,(x >> 16) & 0xFF,(x >> 8) & 0xFF, x & 0xFF
FOURCC_TO_CHAR [2/2]
#define FOURCC_TO_CHAR (x) (x >> 24) & 0xFF,(x >> 16) & 0xFF,(x >> 8) & 0xFF, x & 0xFF
Definition at line 109 of file vchi.h.
MAKE_FOURCC [1/2]
#define MAKE_FOURCC (x) ((fourcc_t)((x[0] << 24) | (x[1] << 16) | (x[2] << 8) | x[3]))
Definition at line 108 of file vchi.h.
MAKE_FOURCC [2/2]
#define MAKE_FOURCC (x) ((fourcc_t)((x[0] << 24) | (x[1] << 16) | (x[2] << 8) | x[3]))
Referenced by vc_vchi_gencmd_init().
VCHI_BULK_ALIGN_NBYTES [1/2]
#define VCHI_BULK_ALIGN_NBYTES (x) (VCHI_BULK_ALIGNED(x) ? 0 : (VCHI_BULK_ALIGN - ((unsigned long)(x) & (VCHI_BULK_ALIGN-1))))
Definition at line 48 of file vchi.h.
VCHI_BULK_ALIGN_NBYTES [2/2]
#define VCHI_BULK_ALIGN_NBYTES (x) (VCHI_BULK_ALIGNED(x) ? 0 : (VCHI_BULK_ALIGN - ((unsigned long)(x) & (VCHI_BULK_ALIGN-1))))
VCHI_BULK_ALIGNED [1/2]
#define VCHI_BULK_ALIGNED (x) (((unsigned long)(x) & (VCHI_BULK_ALIGN-1)) == 0)
Definition at line 53 of file vchi.h.
VCHI_BULK_ALIGNED [2/2]
#define VCHI_BULK_ALIGNED (x) (((unsigned long)(x) & (VCHI_BULK_ALIGN-1)) == 0)
VCHI_BULK_ROUND_DOWN [1/2]
#define VCHI_BULK_ROUND_DOWN (x) (((unsigned long)(x)) & ~(VCHI_BULK_ALIGN-1))
VCHI_BULK_ROUND_DOWN [2/2]
#define VCHI_BULK_ROUND_DOWN (x) (((unsigned long)(x)) & ~(VCHI_BULK_ALIGN-1))
Definition at line 47 of file vchi.h.
VCHI_BULK_ROUND_UP [1/2]
#define VCHI_BULK_ROUND_UP (x) ((((unsigned long)(x))+VCHI_BULK_ALIGN-1) & ~(VCHI_BULK_ALIGN-1))
VCHI_BULK_ROUND_UP [2/2]
#define VCHI_BULK_ROUND_UP (x) ((((unsigned long)(x))+VCHI_BULK_ALIGN-1) & ~(VCHI_BULK_ALIGN-1))
Definition at line 46 of file vchi.h.
VCHI_H_
#define VCHI_H_
VCHI_SERVICE_HANDLE_INVALID [1/2]
#define VCHI_SERVICE_HANDLE_INVALID 0
VCHI_SERVICE_HANDLE_INVALID [2/2]
#define VCHI_SERVICE_HANDLE_INVALID 0
Definition at line 44 of file vchi.h.
VCHI_VEC_HANDLE [1/2]
#define VCHI_VEC_HANDLE (h, o, l) VCHI_VEC_HANDLE, { { (h), (o), (l) } }
VCHI_VEC_HANDLE [2/2]
#define VCHI_VEC_HANDLE (h, o, l) VCHI_VEC_HANDLE, { { (h), (o), (l) } }
Definition at line 105 of file vchi.h.
VCHI_VEC_POINTER [1/2]
#define VCHI_VEC_POINTER (p, l) VCHI_VEC_POINTER, { { (VCHI_MEM_HANDLE_T)(p), (l) } }
VCHI_VEC_POINTER [2/2]
#define VCHI_VEC_POINTER (p, l) VCHI_VEC_POINTER, { { (VCHI_MEM_HANDLE_T)(p), (l) } }
Definition at line 102 of file vchi.h.
VCHI_VERSION [1/2]
#define VCHI_VERSION (v_) { v_, v_ }
Referenced by vc_vchi_cec_init(), vc_vchi_dispmanx_init(), vc_vchi_gencmd_init(), and vc_vchi_tv_init().
VCHI_VERSION [2/2]
#define VCHI_VERSION (v_) { v_, v_ }
Definition at line 61 of file vchi.h.
VCHI_VERSION_EX [1/2]
#define VCHI_VERSION_EX (v_, m_) { v_, m_ }
Definition at line 62 of file vchi.h.
VCHI_VERSION_EX [2/2]
#define VCHI_VERSION_EX (v_, m_) { v_, m_ }
Typedef Documentation
SERVICE_INFO_T
typedef struct service_info_tag SERVICE_INFO_T
VCHI_INSTANCE_T
typedef struct opaque_vchi_instance_handle_t* VCHI_INSTANCE_T
Definition at line 140 of file vchi.h.
VCHI_MSG_VECTOR_EX_T
typedef struct vchi_msg_vector_ex VCHI_MSG_VECTOR_EX_T
VCHI_SERVICE_HANDLE_T
typedef unsigned int VCHI_SERVICE_HANDLE_T
Definition at line 143 of file vchi.h.
VCHI_SERVICE_INIT
typedef void(* VCHI_SERVICE_INIT) (VCHI_INSTANCE_T initialise_instance, VCHI_CONNECTION_T **connections, uint32_t num_connections)
Definition at line 146 of file vchi.h.
Enumeration Type Documentation
VCHI_MSG_VECTOR_TYPE_T
enum VCHI_MSG_VECTOR_TYPE_T
Enumerator
VCHI_VEC_POINTER
VCHI_VEC_HANDLE
VCHI_VEC_LIST
Definition at line 64 of file vchi.h.
 {
    VCHI_VEC_POINTER,
    VCHI_VEC_HANDLE,
    VCHI_VEC_LIST
 } VCHI_MSG_VECTOR_TYPE_T;
Function Documentation
single_get_func_table()
const VCHI_CONNECTION_API_T* single_get_func_table (void)
Definition at line 672 of file vchiq_lib.c.
References NULL.
 {
    return NULL;
 }
vchi_allocate_buffer()
void* vchi_allocate_buffer (VCHI_SERVICE_HANDLE_T handle, uint32_t * length)
vchi_bulk_queue_receive()
int32_t vchi_bulk_queue_receive (VCHI_SERVICE_HANDLE_T handle, void * data_dst, uint32_t data_size, VCHI_FLAGS_T flags, void * transfer_handle)
Definition at line 806 of file vchiq_lib.c.
 {
    VCHI_SERVICE_T *service = find_service_by_handle(handle);
    VCHIQ_QUEUE_BULK_TRANSFER_T args;
    int ret;
    if (!service)
       return VCHIQ_ERROR;
    switch ((int)flags) {
    case VCHI_FLAGS_CALLBACK_WHEN_OP_COMPLETE | VCHI_FLAGS_BLOCK_UNTIL_QUEUED:
       args.mode = VCHIQ_BULK_MODE_CALLBACK;
       break;
    case VCHI_FLAGS_BLOCK_UNTIL_OP_COMPLETE:
       args.mode = VCHIQ_BULK_MODE_BLOCKING;
       break;
    case VCHI_FLAGS_BLOCK_UNTIL_QUEUED:
    case VCHI_FLAGS_NONE:
       args.mode = VCHIQ_BULK_MODE_NOCALLBACK;
       break;
    default:
       vcos_assert(0);
       break;
    }
    args.handle = service->handle;
    args.data = data_dst;
    args.size = data_size;
    args.userdata = bulk_handle;
    RETRY(ret, ioctl(service->fd, VCHIQ_IOC_QUEUE_BULK_RECEIVE, &args));
    return ret;
 }
vchi_bulk_queue_receive_reloc()
int32_t vchi_bulk_queue_receive_reloc (const VCHI_SERVICE_HANDLE_T handle, VCHI_MEM_HANDLE_T h_dst, uint32_t offset, uint32_t data_size, const VCHI_FLAGS_T flags, void *const bulk_handle)
vchi_bulk_queue_receive_reloc_func()
int32_t vchi_bulk_queue_receive_reloc_func (const VCHI_SERVICE_HANDLE_T handle, VCHI_MEM_HANDLE_T h_dst, uint32_t offset, uint32_t data_size, const VCHI_FLAGS_T flags, void *const bulk_handle, int copy_pagelistchar *vcptr, const struct pagelist_struct *pagelist)
vchi_bulk_queue_transmit()
int32_t vchi_bulk_queue_transmit (VCHI_SERVICE_HANDLE_T handle, const void * data_src, uint32_t data_size, VCHI_FLAGS_T flags, void * transfer_handle)
Definition at line 859 of file vchiq_lib.c.
 {
    VCHI_SERVICE_T *service = find_service_by_handle(handle);
    VCHIQ_QUEUE_BULK_TRANSFER_T args;
    int ret;
    if (!service)
       return VCHIQ_ERROR;
    switch ((int)flags) {
    case VCHI_FLAGS_CALLBACK_WHEN_OP_COMPLETE | VCHI_FLAGS_BLOCK_UNTIL_QUEUED:
       args.mode = VCHIQ_BULK_MODE_CALLBACK;
       break;
    case VCHI_FLAGS_BLOCK_UNTIL_DATA_READ:
    case VCHI_FLAGS_BLOCK_UNTIL_OP_COMPLETE:
       args.mode = VCHIQ_BULK_MODE_BLOCKING;
       break;
    case VCHI_FLAGS_BLOCK_UNTIL_QUEUED:
    case VCHI_FLAGS_NONE:
       args.mode = VCHIQ_BULK_MODE_NOCALLBACK;
       break;
    default:
       vcos_assert(0);
       break;
    }
    args.handle = service->handle;
    args.data = (void *)data_src;
    args.size = data_size;
    args.userdata = bulk_handle;
    RETRY(ret, ioctl(service->fd, VCHIQ_IOC_QUEUE_BULK_TRANSMIT, &args));
    return ret;
 }
vchi_bulk_queue_transmit_reloc()
int32_t vchi_bulk_queue_transmit_reloc (VCHI_SERVICE_HANDLE_T handle, VCHI_MEM_HANDLE_T h_src, uint32_t offset, uint32_t data_size, VCHI_FLAGS_T flags, void * transfer_handle)
vchi_connect()
int32_t vchi_connect (VCHI_CONNECTION_T ** connections, const uint32_t num_connections, VCHI_INSTANCE_T instance_handle)
Definition at line 1121 of file vchiq_lib.c.
References status, vchiq_connect(), VCHIQ_SUCCESS, and vcos_unused.
Referenced by main().
 {
    VCHIQ_STATUS_T status;
    vcos_unused(connections);
    vcos_unused(num_connections);
    status = vchiq_connect((VCHIQ_INSTANCE_T)instance_handle);
    return (status == VCHIQ_SUCCESS) ? 0 : -1;
 }
vchi_crc_control()
int32_t vchi_crc_control (VCHI_CONNECTION_T * connection, VCHI_CRC_CONTROL_T control)
vchi_create_connection()
VCHI_CONNECTION_T* vchi_create_connection (const VCHI_CONNECTION_API_T * function_table, const VCHI_MESSAGE_DRIVER_T * low_level)
Definition at line 678 of file vchiq_lib.c.
References NULL, and vcos_unused.
 {
    vcos_unused(function_table);
    vcos_unused(low_level);
    return NULL;
 }
vchi_current_time()
uint32_t vchi_current_time (VCHI_INSTANCE_T instance_handle)
vchi_disconnect()
int32_t vchi_disconnect (VCHI_INSTANCE_T instance_handle)
Definition at line 1148 of file vchiq_lib.c.
References status, vchiq_shutdown(), and VCHIQ_SUCCESS.
Referenced by main().
 {
    VCHIQ_STATUS_T status;
    status = vchiq_shutdown((VCHIQ_INSTANCE_T)instance_handle);
    return (status == VCHIQ_SUCCESS) ? 0 : -1;
 }
vchi_free_buffer()
void vchi_free_buffer (VCHI_SERVICE_HANDLE_T handle, void * address)
vchi_get_peer_version()
int32_t vchi_get_peer_version (const VCHI_SERVICE_HANDLE_T handle, short * peer_version)
vchi_held_msg_ptr()
void* vchi_held_msg_ptr (const VCHI_HELD_MSG_T * message)
vchi_held_msg_release()
int32_t vchi_held_msg_release (VCHI_HELD_MSG_T * message)
Definition at line 1020 of file vchiq_lib.c.
References VCHI_HELD_MSG_T::message, and VCHI_HELD_MSG_T::service.
 {
    int ret = -1;
    if (message && message->message && !message->service)
    {
       free_msgbuf(message->message);
       ret = 0;
    }
    return ret;
 }
vchi_held_msg_rx_timestamp()
uint32_t vchi_held_msg_rx_timestamp (const VCHI_HELD_MSG_T * message)
vchi_held_msg_size()
int32_t vchi_held_msg_size (const VCHI_HELD_MSG_T * message)
vchi_held_msg_tx_timestamp()
uint32_t vchi_held_msg_tx_timestamp (const VCHI_HELD_MSG_T * message)
vchi_initialise()
int32_t vchi_initialise (VCHI_INSTANCE_T * instance_handle)
Definition at line 1094 of file vchiq_lib.c.
Referenced by bcm_host_init(), and main().
 {
    VCHIQ_INSTANCE_T instance;
    instance = vchiq_lib_init(-1);
    vcos_log_trace( "%s: returning instance handle %p", __func__, instance );
    *instance_handle = (VCHI_INSTANCE_T)instance;
    return (instance != NULL) ? 0 : -1;
 }
vchi_mphi_message_driver_func_table()
const VCHI_MESSAGE_DRIVER_T* vchi_mphi_message_driver_func_table (void)
Definition at line 663 of file vchiq_lib.c.
References NULL.
 {
    return NULL;
 }
vchi_msg_dequeue()
int32_t vchi_msg_dequeue (VCHI_SERVICE_HANDLE_T handle, void * data, uint32_t max_data_size_to_read, uint32_t * actual_msg_size, VCHI_FLAGS_T flags)
Definition at line 913 of file vchiq_lib.c.
 {
    VCHI_SERVICE_T *service = find_service_by_handle(handle);
    VCHIQ_DEQUEUE_MESSAGE_T args;
    int ret;
    vcos_assert(flags == VCHI_FLAGS_NONE || flags == VCHI_FLAGS_BLOCK_UNTIL_OP_COMPLETE);
    if (!service)
       return VCHIQ_ERROR;
    if (service->peek_size >= 0)
    {
       vcos_log_error("vchi_msg_dequeue -> using peek buffer\n");
       if ((uint32_t)service->peek_size <= max_data_size_to_read)
       {
          memcpy(data, service->peek_buf, service->peek_size);
          *actual_msg_size = service->peek_size;
          /* Invalidate the peek data, but retain the buffer */
          service->peek_size = -1;
          ret = 0;
       }
       else
       {
          ret = -1;
       }
    }
    else
    {
       args.handle = service->handle;
       args.blocking = (flags == VCHI_FLAGS_BLOCK_UNTIL_OP_COMPLETE);
       args.bufsize = max_data_size_to_read;
       args.buf = data;
       RETRY(ret, ioctl(service->fd, VCHIQ_IOC_DEQUEUE_MESSAGE, &args));
       if (ret >= 0)
       {
          *actual_msg_size = ret;
          ret = 0;
       }
    }
    if ((ret < 0) && (errno != EWOULDBLOCK))
       fprintf(stderr, "vchi_msg_dequeue -> %d(%d)\n", ret, errno);
    return ret;
 }
vchi_msg_hold()
int32_t vchi_msg_hold (VCHI_SERVICE_HANDLE_T handle, void ** data, uint32_t * msg_size, VCHI_FLAGS_T flags, VCHI_HELD_MSG_T * message_descriptor)
Definition at line 1050 of file vchiq_lib.c.
 {
    VCHI_SERVICE_T *service = find_service_by_handle(handle);
    int ret;
    if (!service)
       return VCHIQ_ERROR;
    ret = fill_peek_buf(service, flags);
    if (ret == 0)
    {
       *data = service->peek_buf;
       *msg_size = service->peek_size;
       message_handle->message = service->peek_buf;
       message_handle->service = NULL;
       service->peek_size = -1;
       service->peek_buf = NULL;
    }
    return 0;
 }
vchi_msg_iter_has_next()
vcos_bool_t vchi_msg_iter_has_next (const VCHI_MSG_ITER_T * iter)
vchi_msg_iter_hold()
int32_t vchi_msg_iter_hold (VCHI_MSG_ITER_T * iter, VCHI_HELD_MSG_T * message)
vchi_msg_iter_hold_next()
int32_t vchi_msg_iter_hold_next (VCHI_MSG_ITER_T * iter, void ** data, uint32_t * msg_size, VCHI_HELD_MSG_T * message)
vchi_msg_iter_next()
int32_t vchi_msg_iter_next (VCHI_MSG_ITER_T * iter, void ** data, uint32_t * msg_size)
vchi_msg_iter_remove()
int32_t vchi_msg_iter_remove (VCHI_MSG_ITER_T * iter)
vchi_msg_look_ahead()
int32_t vchi_msg_look_ahead (VCHI_SERVICE_HANDLE_T handle, VCHI_MSG_ITER_T * iter, VCHI_FLAGS_T flags)
vchi_msg_peek()
int32_t vchi_msg_peek (VCHI_SERVICE_HANDLE_T handle, void ** data, uint32_t * msg_size, VCHI_FLAGS_T flags)
Definition at line 702 of file vchiq_lib.c.
 {
    VCHI_SERVICE_T *service = find_service_by_handle(handle);
    int ret;
    if (!service)
       return VCHIQ_ERROR;
    ret = fill_peek_buf(service, flags);
    if (ret == 0)
    {
       *data = service->peek_buf;
       *msg_size = service->peek_size;
    }
    return ret;
 }
vchi_msg_queue()
int32_t vchi_msg_queue (VCHI_SERVICE_HANDLE_T handle, const void * data, uint32_t data_size, VCHI_FLAGS_T flags, void * msg_handle)
Definition at line 766 of file vchiq_lib.c.
 {
    VCHI_SERVICE_T *service = find_service_by_handle(handle);
    VCHIQ_QUEUE_MESSAGE_T args;
    VCHIQ_ELEMENT_T element = {data, data_size};
    int ret;
    vcos_unused(msg_handle);
    vcos_assert(flags == VCHI_FLAGS_BLOCK_UNTIL_QUEUED);
    if (!service)
       return VCHIQ_ERROR;
    args.handle = service->handle;
    args.elements = &element;
    args.count = 1;
    RETRY(ret, ioctl(service->fd, VCHIQ_IOC_QUEUE_MESSAGE, &args));
    return ret;
 }
vchi_msg_queuev()
int32_t vchi_msg_queuev (VCHI_SERVICE_HANDLE_T handle, VCHI_MSG_VECTOR_T * vector, uint32_t count, VCHI_FLAGS_T flags, void * msg_handle)
Definition at line 984 of file vchiq_lib.c.
 {
    VCHI_SERVICE_T *service = find_service_by_handle(handle);
    VCHIQ_QUEUE_MESSAGE_T args;
    int ret;
    vcos_unused(msg_handle);
    vcos_assert(flags == VCHI_FLAGS_BLOCK_UNTIL_QUEUED);
    if (!service)
       return VCHIQ_ERROR;
    args.handle = service->handle;
    args.elements = (const VCHIQ_ELEMENT_T *)vector;
    args.count = count;
    RETRY(ret, ioctl(service->fd, VCHIQ_IOC_QUEUE_MESSAGE, &args));
    return ret;
 }
vchi_msg_queuev_ex()
int32_t vchi_msg_queuev_ex (VCHI_SERVICE_HANDLE_T handle, VCHI_MSG_VECTOR_EX_T * vector, uint32_t count, VCHI_FLAGS_T flags, void * msg_handle)
vchi_msg_remove()
int32_t vchi_msg_remove (VCHI_SERVICE_HANDLE_T handle)
Definition at line 735 of file vchiq_lib.c.
 {
    VCHI_SERVICE_T *service = find_service_by_handle(handle);
    if (!service)
       return VCHIQ_ERROR;
    /* Why would you call vchi_msg_remove without calling vchi_msg_peek first? */
    vcos_assert(service->peek_size >= 0);
    /* Invalidate the content but reuse the buffer */
    service->peek_size = -1;
    return 0;
 }
vchi_service_close()
int32_t vchi_service_close (const VCHI_SERVICE_HANDLE_T handle)
Definition at line 1217 of file vchiq_lib.c.
Referenced by vc_gpuserv_deinit().
 {
    VCHI_SERVICE_T *service = find_service_by_handle(handle);
    int ret;
    if (!service)
       return VCHIQ_ERROR;
    RETRY(ret,ioctl(service->fd, VCHIQ_IOC_CLOSE_SERVICE, service->handle));
    if (service->is_client)
       service->lib_handle = VCHIQ_SERVICE_HANDLE_INVALID;
    return ret;
 }
vchi_service_create()
int32_t vchi_service_create (VCHI_INSTANCE_T instance_handle, SERVICE_CREATION_T * setup, VCHI_SERVICE_HANDLE_T * handle)
open
Definition at line 1195 of file vchiq_lib.c.
References SERVICE_CREATION_T::callback_param, vchiq_service_params_struct::fourcc, SERVICE_CREATION_T::service_id, status, vchiq_service_params_struct::userdata, VCHI_VERSION_T::version, vchiq_service_params_struct::version, SERVICE_CREATION_T::version, VCHI_VERSION_T::version_min, and vchiq_service_params_struct::version_min.
 {
    VCHIQ_SERVICE_PARAMS_T params;
    VCHIQ_STATUS_T status;
    memset(&params, 0, sizeof(params));
    params.fourcc = setup->service_id;
    params.userdata = setup->callback_param;
    params.version = (short)setup->version.version;
    params.version_min = (short)setup->version.version_min;
    status = create_service((VCHIQ_INSTANCE_T)instance_handle,
       &params,
       setup->callback,
       0,
       (VCHIQ_SERVICE_HANDLE_T *)handle);
    return (status == VCHIQ_SUCCESS) ? 0 : -1;
 }
vchi_service_destroy()
int32_t vchi_service_destroy (const VCHI_SERVICE_HANDLE_T handle)
Definition at line 1234 of file vchiq_lib.c.
 {
    VCHI_SERVICE_T *service = find_service_by_handle(handle);
    int ret;
    if (!service)
       return VCHIQ_ERROR;
    RETRY(ret,ioctl(service->fd, VCHIQ_IOC_REMOVE_SERVICE, service->handle));
    service->lib_handle = VCHIQ_SERVICE_HANDLE_INVALID;
    return ret;
 }
vchi_service_open()
int32_t vchi_service_open (VCHI_INSTANCE_T instance_handle, SERVICE_CREATION_T * setup, VCHI_SERVICE_HANDLE_T * handle)
Definition at line 1172 of file vchiq_lib.c.
References SERVICE_CREATION_T::callback_param, vchiq_service_params_struct::fourcc, SERVICE_CREATION_T::service_id, status, vchiq_service_params_struct::userdata, VCHI_VERSION_T::version, vchiq_service_params_struct::version, SERVICE_CREATION_T::version, VCHI_VERSION_T::version_min, and vchiq_service_params_struct::version_min.
 {
    VCHIQ_SERVICE_PARAMS_T params;
    VCHIQ_STATUS_T status;
    memset(&params, 0, sizeof(params));
    params.fourcc = setup->service_id;
    params.userdata = setup->callback_param;
    params.version = (short)setup->version.version;
    params.version_min = (short)setup->version.version_min;
    status = create_service((VCHIQ_INSTANCE_T)instance_handle,
       &params,
       setup->callback,
       1/*open*/,
       (VCHIQ_SERVICE_HANDLE_T *)handle);
    return (status == VCHIQ_SUCCESS) ? 0 : -1;
 }
vchi_service_release()
int32_t vchi_service_release (const VCHI_SERVICE_HANDLE_T handle)
Definition at line 1330 of file vchiq_lib.c.
Referenced by release_gencmd_service().
 {
    VCHI_SERVICE_T *service = find_service_by_handle(handle);
    int ret;
    if (!service)
       return VCHIQ_ERROR;
    RETRY(ret,ioctl(service->fd, VCHIQ_IOC_RELEASE_SERVICE, service->handle));
    return ret;
 }
vchi_service_set_option()
int32_t vchi_service_set_option (const VCHI_SERVICE_HANDLE_T handle, VCHI_SERVICE_OPTION_T option, int value)
Definition at line 1354 of file vchiq_lib.c.
 {
    VCHIQ_SET_SERVICE_OPTION_T args;
    VCHI_SERVICE_T *service = find_service_by_handle(handle);
    int ret;
    switch (option)
    {
    case VCHI_SERVICE_OPTION_TRACE:
       args.option = VCHIQ_SERVICE_OPTION_TRACE;
       break;
    default:
       service = NULL;
       break;
    }
    if (!service)
       return VCHIQ_ERROR;
    args.handle = service->handle;
    args.value  = value;
    RETRY(ret, ioctl(service->fd, VCHIQ_IOC_SET_SERVICE_OPTION, &args));
    return ret;
 }
vchi_service_use()
int32_t vchi_service_use (const VCHI_SERVICE_HANDLE_T handle)
Definition at line 1308 of file vchiq_lib.c.
Referenced by use_gencmd_service(), vc_dispmanx_update_submit(), vc_tv_hdmi_ddc_read_id(), vc_tv_hdmi_get_supported_modes_new_id(), and VCOS_DEPRECATED().
 {
    VCHI_SERVICE_T *service = find_service_by_handle(handle);
    int ret;
    if (!service)
       return VCHIQ_ERROR;
    RETRY(ret,ioctl(service->fd, VCHIQ_IOC_USE_SERVICE, service->handle));
    return ret;
 }