VideoCore Library: host_applications/linux/apps/hello_pi/hello_fft/gpu_fft_trans.c File Reference
gpu_fft_trans.c File Reference
#include <string.h>
#include "gpu_fft_trans.h"
#include "hex/shader_trans.hex"
Functions
int gpu_fft_trans_prepare (int mb, struct GPU_FFT *src, struct GPU_FFT *dst, struct GPU_FFT_TRANS **out)
unsigned gpu_fft_trans_execute (struct GPU_FFT_TRANS *info)
void gpu_fft_trans_release (struct GPU_FFT_TRANS *info)
Function Documentation
gpu_fft_trans_execute()
unsigned gpu_fft_trans_execute (struct GPU_FFT_TRANS * info)
Definition at line 89 of file gpu_fft_trans.c.
References GPU_FFT_TRANS::base, and gpu_fft_base_exec().
Referenced by main().
{
     return gpu_fft_base_exec(&info->base, 1);
 }
gpu_fft_trans_prepare()
int gpu_fft_trans_prepare (int mb, struct GPU_FFT * src, struct GPU_FFT * dst, struct GPU_FFT_TRANS ** out)
Definition at line 37 of file gpu_fft_trans.c.
References GPU_FFT_PTR::arm, gpu_fft_alloc(), gpu_fft_ptr_inc(), and GPU_FFT_PTR::vptr.
Referenced by main().
{
     unsigned size, info_bytes, code_bytes, unif_bytes, mail_bytes;
     int ret;
     struct GPU_FFT_TRANS *info;
     struct GPU_FFT_BASE *base;
     struct GPU_FFT_PTR ptr;
     info_bytes = code_bytes = unif_bytes = mail_bytes = 4096; // 4k align
     size  = info_bytes +        // control
             code_bytes +        // shader, aligned
             unif_bytes +        // uniforms
             mail_bytes;         // mailbox message
     ret = gpu_fft_alloc(mb, size, &ptr);
     if (ret) return ret;
     // Control header
     info = (struct GPU_FFT_TRANS *) ptr.arm.vptr;
     base = (struct GPU_FFT_BASE *) info;
     gpu_fft_ptr_inc(&ptr, info_bytes);
     // Shader code
     memcpy(ptr.arm.vptr, shader_trans, code_bytes);
     base->vc_code = gpu_fft_ptr_inc(&ptr, code_bytes);
     // Uniforms
     ptr.arm.uptr[0] = src->base.vc_msg;
     ptr.arm.uptr[1] = ((char*)src->out) - ((char*)src->in); // output buffer offset
     ptr.arm.uptr[2] = dst->base.vc_msg;
     ptr.arm.uptr[3] = 0;
     ptr.arm.uptr[4] = src->step * sizeof(struct GPU_FFT_COMPLEX);
     ptr.arm.uptr[5] = dst->step * sizeof(struct GPU_FFT_COMPLEX);
     ptr.arm.uptr[6] = src->x < dst->y? src->x : dst->y;
     ptr.arm.uptr[7] = src->y < dst->x? src->y : dst->x;
     base->vc_unifs[0] = gpu_fft_ptr_inc(&ptr, unif_bytes);
     // Mailbox message
     ptr.arm.uptr[0] = base->vc_unifs[0];
     ptr.arm.uptr[1] = base->vc_code;
     base->vc_msg = gpu_fft_ptr_inc(&ptr, mail_bytes);
     *out = info;
     return 0;
 }
gpu_fft_trans_release()
void gpu_fft_trans_release (struct GPU_FFT_TRANS * info)
Definition at line 93 of file gpu_fft_trans.c.
References GPU_FFT_TRANS::base, and gpu_fft_base_release().
Referenced by main().
{
     gpu_fft_base_release(&info->base);
 }