VideoCore Library: containers/core/containers_codecs.c File Reference
containers_codecs.c File Reference
#include <stdlib.h>
#include <string.h>
#include "containers/containers.h"
#include "containers/containers_codecs.h"
#include "containers/core/containers_utils.h"
Functions
VC_CONTAINER_FOURCC_T waveformat_to_codec (uint16_t waveformat_id)
uint16_t codec_to_waveformat (VC_CONTAINER_FOURCC_T codec)
VC_CONTAINER_FOURCC_T vfw_fourcc_to_codec (uint32_t fourcc)
uint32_t codec_to_vfw_fourcc (VC_CONTAINER_FOURCC_T codec)
VC_CONTAINER_FOURCC_T fourcc_to_codec (uint32_t fourcc)
uint32_t codec_to_fourcc (VC_CONTAINER_FOURCC_T codec)
Function Documentation
codec_to_fourcc()
uint32_t codec_to_fourcc (VC_CONTAINER_FOURCC_T codec)
Definition at line 202 of file containers_codecs.c.
 {
    unsigned int i;
    for(i = 0; codec_to_fourcc_table[i].codec != VC_CONTAINER_CODEC_UNKNOWN; i++)
       if(codec_to_fourcc_table[i].codec == codec) break;
    return codec_to_fourcc_table[i].fourcc;
 }
codec_to_vfw_fourcc()
uint32_t codec_to_vfw_fourcc (VC_CONTAINER_FOURCC_T codec)
Tries to convert a VC_CONTAINER_FOURCC_T into a VideoForWindows fourcc.
Parameters
codec VC_CONTAINER_FOURCC_T to convert
Returns
a valid vfw fourcc or 0 if no mapping was found.
Definition at line 155 of file containers_codecs.c.
Referenced by vc_container_es_format_to_bitmapinfoheader(), and vc_container_write_bitmapinfoheader().
 {
    unsigned int i;
    for(i = 0; codec_to_vfw_table[i].codec != VC_CONTAINER_CODEC_UNKNOWN; i++)
       if(codec_to_vfw_table[i].codec == codec) break;
    return codec_to_vfw_table[i].fourcc;
 }
codec_to_waveformat()
uint16_t codec_to_waveformat (VC_CONTAINER_FOURCC_T codec)
Converts a VC_CONTAINER_FOURCC_T into a WaveFormat ID.
Parameters
codec VC_CONTAINER_FOURCC_T to convert
Returns
a valid WaveFormat ID of 0 if no mapping was found.
Definition at line 78 of file containers_codecs.c.
Referenced by vc_container_es_format_to_waveformatex(), and vc_container_write_waveformatex().
 {
    unsigned int i;
    for(i = 0; codec_to_wf_table[i].codec != VC_CONTAINER_CODEC_UNKNOWN; i++)
       if(codec_to_wf_table[i].codec == codec) break;
    return codec_to_wf_table[i].id;
 }
fourcc_to_codec()
VC_CONTAINER_FOURCC_T fourcc_to_codec (uint32_t fourcc)
Tries to convert a generic fourcc into a VC_CONTAINER_FOURCC_T.
Parameters
fourcc fourcc to convert
Returns
a valid VC_CONTAINER_FOURCC_T or VC_CONTAINER_CODEC_UNKNOWN if no mapping was found.
Definition at line 193 of file containers_codecs.c.
Referenced by vc_container_bitmapinfoheader_to_es_format().
 {
    unsigned int i;
    for(i = 0; codec_to_fourcc_table[i].codec != VC_CONTAINER_CODEC_UNKNOWN; i++)
       if(codec_to_fourcc_table[i].fourcc == fourcc) break;
    return codec_to_fourcc_table[i].codec;
 }
vfw_fourcc_to_codec()
VC_CONTAINER_FOURCC_T vfw_fourcc_to_codec (uint32_t fourcc)
Tries to convert VideoForWindows fourcc into a VC_CONTAINER_FOURCC_T.
Parameters
fourcc vfw fourcc to convert
Returns
a valid VC_CONTAINER_FOURCC_T or VC_CONTAINER_CODEC_UNKNOWN if no mapping was found.
Definition at line 143 of file containers_codecs.c.
Referenced by vc_container_bitmapinfoheader_to_es_format().
 {
    unsigned int i;
    for(i = 0; codec_to_vfw_table[i].codec != VC_CONTAINER_CODEC_UNKNOWN; i++)
       if(codec_to_vfw_table[i].fourcc == fourcc) break;
    if(codec_to_vfw_table[i].codec == VC_CONTAINER_CODEC_UNKNOWN)
       return fourcc;
    return codec_to_vfw_table[i].codec;
 }
waveformat_to_codec()
VC_CONTAINER_FOURCC_T waveformat_to_codec (uint16_t waveformat_id)
Converts a WaveFormat ID into a VC_CONTAINER_FOURCC_T.
Parameters
waveformat_id WaveFormat ID to convert
Returns
a valid VC_CONTAINER_FOURCC_T or VC_CONTAINER_CODEC_UNKNOWN if no mapping was found.
Definition at line 70 of file containers_codecs.c.
Referenced by vc_container_waveformatex_to_es_format(), and wav_reader_open().
 {
    unsigned int i;
    for(i = 0; codec_to_wf_table[i].codec != VC_CONTAINER_CODEC_UNKNOWN; i++)
       if(codec_to_wf_table[i].id == waveformat_id) break;
    return codec_to_wf_table[i].codec;
 }
Variable Documentation
codec
VC_CONTAINER_FOURCC_T codec
Definition at line 37 of file containers_codecs.c.
fourcc
uint32_t fourcc
Definition at line 88 of file containers_codecs.c.
Referenced by vc_container_bitmapinfoheader_to_es_format(), vc_container_es_format_to_bitmapinfoheader(), vc_container_waveformatex_to_es_format(), and vc_container_write_bitmapinfoheader().
id
uint16_t id
Definition at line 38 of file containers_codecs.c.