VideoCore Library: host_applications/linux/apps/raspicam/RaspiTexUtil.c File Reference
RaspiTexUtil.c File Reference
#include "RaspiTexUtil.h"
#include "RaspiTex.h"
#include <bcm_host.h>
#include <GLES2/gl2.h>
Functions
void raspitexutil_gl_term (RASPITEX_STATE *raspitex_state)
int raspitexutil_create_native_window (RASPITEX_STATE *raspitex_state)
void raspitexutil_destroy_native_window (RASPITEX_STATE *raspitex_state)
int raspitexutil_create_textures (RASPITEX_STATE *raspitex_state)
int raspitexutil_gl_init_1_0 (RASPITEX_STATE *raspitex_state)
int raspitexutil_gl_init_2_0 (RASPITEX_STATE *raspitex_state)
int raspitexutil_do_update_texture (EGLDisplay display, EGLenum target, EGLClientBuffer mm_buf, GLuint *texture, EGLImageKHR *egl_image)
int raspitexutil_update_texture (RASPITEX_STATE *raspitex_state, EGLClientBuffer mm_buf)
int raspitexutil_update_y_texture (RASPITEX_STATE *raspitex_state, EGLClientBuffer mm_buf)
int raspitexutil_update_u_texture (RASPITEX_STATE *raspitex_state, EGLClientBuffer mm_buf)
int raspitexutil_update_v_texture (RASPITEX_STATE *raspitex_state, EGLClientBuffer mm_buf)
int raspitexutil_update_model (RASPITEX_STATE *raspitex_state)
int raspitexutil_redraw (RASPITEX_STATE *raspitex_state)
void raspitexutil_close (RASPITEX_STATE *raspitex_state)
void raspitexutil_brga_to_rgba (uint8_t *buffer, size_t size)
int raspitexutil_capture_bgra (RASPITEX_STATE *state, uint8_t **buffer, size_t *buffer_size)
int raspitexutil_build_shader_program (RASPITEXUTIL_SHADER_PROGRAM_T *p)
Variables
VCOS_LOG_CAT_T raspitex_log_category
Detailed Description
Provides default implementations for the raspitex_scene_ops functions and general utility functions.
Definition in file RaspiTexUtil.c.
Function Documentation
raspitexutil_brga_to_rgba()
void raspitexutil_brga_to_rgba (uint8_t * buffer, size_t size)
Performs an in-place byte swap from BGRA to RGBA.
Parameters
buffer The buffer to modify.
size Size of the buffer in bytes.
Definition at line 439 of file RaspiTexUtil.c.
Referenced by raspitex_capture().
 {
    uint8_t* out = buffer;
    uint8_t* end = buffer + size;
    while (out < end)
    {
       uint8_t tmp = out[0];
       out[0] = out[2];
       out[2] = tmp;
       out += 4;
    }
 }
raspitexutil_build_shader_program()
int raspitexutil_build_shader_program (RASPITEXUTIL_SHADER_PROGRAM_T * p)
Takes a description of shader program, compiles it and gets the locations of uniforms and attributes.
Parameters
p The shader program state.
Returns
Zero if successful.
Definition at line 502 of file RaspiTexUtil.c.
References RASPITEXUTIL_SHADER_PROGRAM_T::attribute_locations, RASPITEXUTIL_SHADER_PROGRAM_T::attribute_names, fail, RASPITEXUTIL_SHADER_PROGRAM_T::fragment_source, RASPITEXUTIL_SHADER_PROGRAM_T::fs, GL_COMPILE_STATUS, GL_FRAGMENT_SHADER, GL_LINK_STATUS, GL_VERTEX_SHADER, glAttachShader(), glCompileShader(), glCreateProgram(), glCreateShader(), glDeleteProgram(), glDeleteShader(), glGetAttribLocation(), glGetProgramInfoLog(), glGetProgramiv(), glGetShaderInfoLog(), glGetShaderiv(), glGetUniformLocation(), glLinkProgram(), glShaderSource(), NULL, RASPITEXUTIL_SHADER_PROGRAM_T::program, SHADER_MAX_ATTRIBUTES, SHADER_MAX_UNIFORMS, status, RASPITEXUTIL_SHADER_PROGRAM_T::uniform_locations, RASPITEXUTIL_SHADER_PROGRAM_T::uniform_names, vcos_assert, VCOS_FUNCTION, RASPITEXUTIL_SHADER_PROGRAM_T::vertex_source, and RASPITEXUTIL_SHADER_PROGRAM_T::vs.
 {
    GLint status;
    int i = 0;
    char log[1024];
    int logLen = 0;
    vcos_assert(p);
    vcos_assert(p->vertex_source);
    vcos_assert(p->fragment_source);
    if (! (p && p->vertex_source && p->fragment_source))
       goto fail;
    p->vs = p->fs = 0;
    p->vs = glCreateShader(GL_VERTEX_SHADER);
    glShaderSource(p->vs, 1, &p->vertex_source, NULL);
    glCompileShader(p->vs);
    glGetShaderiv(p->vs, GL_COMPILE_STATUS, &status);
    if (! status)
    {
       glGetShaderInfoLog(p->vs, sizeof(log), &logLen, log);
       vcos_log_error("Program info log %s", log);
       goto fail;
    }
    p->fs = glCreateShader(GL_FRAGMENT_SHADER);
    glShaderSource(p->fs, 1, &p->fragment_source, NULL);
    glCompileShader(p->fs);
    glGetShaderiv(p->fs, GL_COMPILE_STATUS, &status);
    if (! status)
    {
       glGetShaderInfoLog(p->fs, sizeof(log), &logLen, log);
       vcos_log_error("Program info log %s", log);
       goto fail;
    }
    p->program = glCreateProgram();
    glAttachShader(p->program, p->vs);
    glAttachShader(p->program, p->fs);
    glLinkProgram(p->program);
    glGetProgramiv(p->program, GL_LINK_STATUS, &status);
    if (! status)
    {
       vcos_log_error("Failed to link shader program");
       glGetProgramInfoLog(p->program, sizeof(log), &logLen, log);
       vcos_log_error("Program info log %s", log);
       goto fail;
    }
    for (i = 0; i < SHADER_MAX_ATTRIBUTES; ++i)
    {
       if (! p->attribute_names[i])
          break;
       p->attribute_locations[i] = glGetAttribLocation(p->program, p->attribute_names[i]);
       if (p->attribute_locations[i] == -1)
       {
          vcos_log_error("Failed to get location for attribute %s",
                         p->attribute_names[i]);
          goto fail;
       }
       else
       {
          vcos_log_trace("Attribute for %s is %d",
                         p->attribute_names[i], p->attribute_locations[i]);
       }
    }
    for (i = 0; i < SHADER_MAX_UNIFORMS; ++i)
    {
       if (! p->uniform_names[i])
          break;
       p->uniform_locations[i] = glGetUniformLocation(p->program, p->uniform_names[i]);
       if (p->uniform_locations[i] == -1)
       {
          vcos_log_error("Failed to get location for uniform %s",
                         p->uniform_names[i]);
          goto fail;
       }
       else
       {
          vcos_log_trace("Uniform for %s is %d",
                         p->uniform_names[i], p->uniform_locations[i]);
       }
    }
    return 0;
 fail:
    vcos_log_error("%s: Failed to build shader program", VCOS_FUNCTION);
    if (p)
    {
       glDeleteProgram(p->program);
       glDeleteShader(p->fs);
       glDeleteShader(p->vs);
    }
    return -1;
 }
raspitexutil_capture_bgra()
int raspitexutil_capture_bgra (RASPITEX_STATE * state, uint8_t ** buffer, size_t * buffer_size)
Uses glReadPixels to grab the current frame-buffer contents and returns the result in a newly allocate buffer along with the its size. Data is returned in BGRA format for TGA output. PPM output doesn't require the channel order swap but would require a vflip. The TGA format also supports alpha. The byte swap is not done in this function to avoid blocking the GL rendering thread.
Parameters
state Pointer to the GL preview state.
buffer Address of pointer to set to pointer to new buffer.
buffer_size The size of the new buffer in bytes (out param)
Returns
Zero if successful.
Definition at line 466 of file RaspiTexUtil.c.
Referenced by raspitex_set_defaults().
 {
    const int bytes_per_pixel = 4;
    vcos_log_trace("%s: %dx%d %d", VCOS_FUNCTION,
                   state->width, state->height, bytes_per_pixel);
    *buffer_size = state->width * state->height * bytes_per_pixel;
    *buffer = calloc(*buffer_size, 1);
    if (! *buffer)
       goto error;
    glReadPixels(0, 0, state->width, state->height, GL_RGBA,
                 GL_UNSIGNED_BYTE, *buffer);
    if (glGetError() != GL_NO_ERROR)
       goto error;
    return 0;
 error:
    *buffer_size = 0;
    if (*buffer)
       free(*buffer);
    *buffer = NULL;
    return -1;
 }
raspitexutil_close()
void raspitexutil_close (RASPITEX_STATE * raspitex_state)
Default is a no-op
Parameters
raspitex_state A pointer to the GL preview state.
Definition at line 429 of file RaspiTexUtil.c.
References void().
Referenced by raspitex_set_defaults().
 {
    (void) raspitex_state;
 }
raspitexutil_create_native_window()
int raspitexutil_create_native_window (RASPITEX_STATE * raspitex_state)
Creates a native window for the GL surface using dispmanx
Parameters
raspitex_state A pointer to the GL preview state.
Returns
Zero if successful, otherwise, -1 is returned.
Definition at line 80 of file RaspiTexUtil.c.
References RASPITEX_STATE::disp, DISPMANX_FLAGS_ALPHA_FIXED_ALL_PIXELS, DISPMANX_NO_HANDLE, DISPMANX_NO_ROTATE, DISPMANX_PROTECTION_NONE, EGL_DISPMANX_WINDOW_T::element, error(), tag_VC_RECT_T::height, EGL_DISPMANX_WINDOW_T::height, RASPITEX_STATE::height, RASPITEX_STATE::native_window, NULL, VC_DISPMANX_ALPHA_T::opacity, RASPITEX_STATE::opacity, vc_dispmanx_display_open(), vc_dispmanx_element_add(), vc_dispmanx_update_start(), vc_dispmanx_update_submit_sync(), VCOS_FUNCTION, tag_VC_RECT_T::width, EGL_DISPMANX_WINDOW_T::width, RASPITEX_STATE::width, RASPITEX_STATE::win, tag_VC_RECT_T::x, RASPITEX_STATE::x, tag_VC_RECT_T::y, and RASPITEX_STATE::y.
Referenced by raspitex_set_defaults().
 {
    VC_DISPMANX_ALPHA_T alpha = {DISPMANX_FLAGS_ALPHA_FIXED_ALL_PIXELS, 255, 0};
    VC_RECT_T src_rect = {0};
    VC_RECT_T dest_rect = {0};
    uint32_t disp_num = 0; // Primary
    uint32_t layer_num = 0;
    DISPMANX_ELEMENT_HANDLE_T elem;
    DISPMANX_UPDATE_HANDLE_T update;
    alpha.opacity = raspitex_state->opacity;
    dest_rect.x = raspitex_state->x;
    dest_rect.y = raspitex_state->y;
    dest_rect.width = raspitex_state->width;
    dest_rect.height = raspitex_state->height;
    vcos_log_trace("%s: %d,%d,%d,%d %d,%d,0x%x,0x%x", VCOS_FUNCTION,
                   src_rect.x, src_rect.y, src_rect.width, src_rect.height,
                   dest_rect.x, dest_rect.y, dest_rect.width, dest_rect.height);
    src_rect.width = dest_rect.width << 16;
    src_rect.height = dest_rect.height << 16;
    raspitex_state->disp = vc_dispmanx_display_open(disp_num);
    if (raspitex_state->disp == DISPMANX_NO_HANDLE)
    {
       vcos_log_error("Failed to open display handle");
       goto error;
    }
    update = vc_dispmanx_update_start(0);
    if (update == DISPMANX_NO_HANDLE)
    {
       vcos_log_error("Failed to open update handle");
       goto error;
    }
    elem = vc_dispmanx_element_add(update, raspitex_state->disp, layer_num,
                                   &dest_rect, 0, &src_rect, DISPMANX_PROTECTION_NONE, &alpha, NULL,
                                   DISPMANX_NO_ROTATE);
    if (elem == DISPMANX_NO_HANDLE)
    {
       vcos_log_error("Failed to create element handle");
       goto error;
    }
    raspitex_state->win.element = elem;
    raspitex_state->win.width = raspitex_state->width;
    raspitex_state->win.height = raspitex_state->height;
    vc_dispmanx_update_submit_sync(update);
    raspitex_state->native_window = (EGLNativeWindowType*) &raspitex_state->win;
    return 0;
 error:
    return -1;
 }
raspitexutil_create_textures()
int raspitexutil_create_textures (RASPITEX_STATE * raspitex_state)
Definition at line 228 of file RaspiTexUtil.c.
References GLCHK, glGenTextures(), RASPITEX_STATE::texture, RASPITEX_STATE::u_texture, RASPITEX_STATE::v_texture, and RASPITEX_STATE::y_texture.
 {
    GLCHK(glGenTextures(1, &raspitex_state->texture));
    GLCHK(glGenTextures(1, &raspitex_state->y_texture));
    GLCHK(glGenTextures(1, &raspitex_state->u_texture));
    GLCHK(glGenTextures(1, &raspitex_state->v_texture));
    return 0;
 }
raspitexutil_destroy_native_window()
void raspitexutil_destroy_native_window (RASPITEX_STATE * raspitex_state)
Destroys the pools of buffers used by the GL renderer.
Parameters
raspitex_state A pointer to the GL preview state.
Definition at line 141 of file RaspiTexUtil.c.
References RASPITEX_STATE::disp, DISPMANX_NO_HANDLE, vc_dispmanx_display_close(), and VCOS_FUNCTION.
Referenced by raspitex_set_defaults().
 {
    vcos_log_trace("%s", VCOS_FUNCTION);
    if (raspitex_state->disp != DISPMANX_NO_HANDLE)
    {
       vc_dispmanx_display_close(raspitex_state->disp);
       raspitex_state->disp = DISPMANX_NO_HANDLE;
    }
 }
raspitexutil_do_update_texture()
int raspitexutil_do_update_texture (EGLDisplay display, EGLenum target, EGLClientBuffer mm_buf, GLuint * texture, EGLImageKHR * egl_image)
Advances the texture and EGL image to the next MMAL buffer.
Parameters
display The EGL display.
target The EGL image target e.g. EGL_IMAGE_BRCM_MULTIMEDIA
mm_buf The EGL client buffer (mmal opaque buffer) that is used to create the EGL Image for the preview texture.
egl_image Pointer to the EGL image to update with mm_buf.
texture Pointer to the texture to update from EGL image.
Returns
Zero if successful.
Definition at line 329 of file RaspiTexUtil.c.
Referenced by raspitexutil_update_texture(), raspitexutil_update_u_texture(), raspitexutil_update_v_texture(), and raspitexutil_update_y_texture().
 {
    vcos_log_trace("%s: mm_buf %u", VCOS_FUNCTION, (unsigned) mm_buf);
    GLCHK(glBindTexture(GL_TEXTURE_EXTERNAL_OES, *texture));
    if (*egl_image != EGL_NO_IMAGE_KHR)
    {
       /* Discard the EGL image for the preview frame */
       eglDestroyImageKHR(display, *egl_image);
       *egl_image = EGL_NO_IMAGE_KHR;
    }
    *egl_image = eglCreateImageKHR(display, EGL_NO_CONTEXT, target, mm_buf, NULL);
    GLCHK(glEGLImageTargetTexture2DOES(GL_TEXTURE_EXTERNAL_OES, *egl_image));
    return 0;
 }
raspitexutil_gl_init_1_0()
int raspitexutil_gl_init_1_0 (RASPITEX_STATE * raspitex_state)
Creates an OpenGL ES 1.X context.
Parameters
raspitex_state A pointer to the GL preview state.
Returns
Zero if successful.
Definition at line 242 of file RaspiTexUtil.c.
References EGL_ALPHA_SIZE, EGL_BLUE_SIZE, RASPITEX_STATE::egl_config_attribs, EGL_CONTEXT_CLIENT_VERSION, EGL_DEPTH_SIZE, EGL_GREEN_SIZE, EGL_NONE, EGL_OPENGL_ES_BIT, EGL_RED_SIZE, and EGL_RENDERABLE_TYPE.
Referenced by raspitex_set_defaults().
 {
    int rc;
    const EGLint* attribs = raspitex_state->egl_config_attribs;
    const EGLint default_attribs[] =
    {
       EGL_RED_SIZE,   8,
       EGL_GREEN_SIZE, 8,
       EGL_BLUE_SIZE,  8,
       EGL_ALPHA_SIZE, 8,
       EGL_DEPTH_SIZE, 16,
       EGL_RENDERABLE_TYPE, EGL_OPENGL_ES_BIT,
       EGL_NONE
    };
    const EGLint context_attribs[] =
    {
       EGL_CONTEXT_CLIENT_VERSION, 1,
       EGL_NONE
    };
    if (! attribs)
       attribs = default_attribs;
    rc = raspitexutil_gl_common(raspitex_state, attribs, context_attribs);
    if (rc != 0)
       goto end;
    GLCHK(glEnable(GL_TEXTURE_EXTERNAL_OES));
    rc = raspitexutil_create_textures(raspitex_state);
 end:
    return rc;
 }
raspitexutil_gl_init_2_0()
int raspitexutil_gl_init_2_0 (RASPITEX_STATE * raspitex_state)
Creates an OpenGL ES 2.X context.
Parameters
raspitex_state A pointer to the GL preview state.
Returns
Zero if successful.
Definition at line 283 of file RaspiTexUtil.c.
References EGL_ALPHA_SIZE, EGL_BLUE_SIZE, RASPITEX_STATE::egl_config_attribs, EGL_CONTEXT_CLIENT_VERSION, EGL_DEPTH_SIZE, EGL_GREEN_SIZE, EGL_NONE, EGL_OPENGL_ES2_BIT, EGL_RED_SIZE, EGL_RENDERABLE_TYPE, and VCOS_FUNCTION.
 {
    int rc;
    const EGLint* attribs = raspitex_state->egl_config_attribs;;
    const EGLint default_attribs[] =
    {
       EGL_RED_SIZE,   8,
       EGL_GREEN_SIZE, 8,
       EGL_BLUE_SIZE,  8,
       EGL_ALPHA_SIZE, 8,
       EGL_DEPTH_SIZE, 16,
       EGL_RENDERABLE_TYPE, EGL_OPENGL_ES2_BIT,
       EGL_NONE
    };
    const EGLint context_attribs[] =
    {
       EGL_CONTEXT_CLIENT_VERSION, 2,
       EGL_NONE
    };
    if (! attribs)
       attribs = default_attribs;
    vcos_log_trace("%s", VCOS_FUNCTION);
    rc = raspitexutil_gl_common(raspitex_state, attribs, context_attribs);
    if (rc != 0)
       goto end;
    rc = raspitexutil_create_textures(raspitex_state);
 end:
    return rc;
 }
raspitexutil_gl_term()
void raspitexutil_gl_term (RASPITEX_STATE * raspitex_state)
Deletes textures and EGL surfaces and context.
Parameters
raspitex_state Pointer to the Raspi
Definition at line 47 of file RaspiTexUtil.c.
References RASPITEX_STATE::context, RASPITEX_STATE::display, RASPITEX_STATE::egl_image, EGL_NO_CONTEXT, EGL_NO_IMAGE_KHR, EGL_NO_SURFACE, eglDestroyContext(), eglDestroyImageKHR(), eglDestroySurface(), eglMakeCurrent(), eglTerminate(), glDeleteTextures(), RASPITEX_STATE::surface, RASPITEX_STATE::texture, RASPITEX_STATE::u_egl_image, RASPITEX_STATE::u_texture, RASPITEX_STATE::v_egl_image, RASPITEX_STATE::v_texture, VCOS_FUNCTION, RASPITEX_STATE::y_egl_image, and RASPITEX_STATE::y_texture.
Referenced by raspitex_set_defaults().
 {
    vcos_log_trace("%s", VCOS_FUNCTION);
    /* Delete OES textures */
    glDeleteTextures(1, &raspitex_state->texture);
    eglDestroyImageKHR(raspitex_state->display, raspitex_state->egl_image);
    raspitex_state->egl_image = EGL_NO_IMAGE_KHR;
    glDeleteTextures(1, &raspitex_state->y_texture);
    eglDestroyImageKHR(raspitex_state->display, raspitex_state->y_egl_image);
    raspitex_state->y_egl_image = EGL_NO_IMAGE_KHR;
    glDeleteTextures(1, &raspitex_state->u_texture);
    eglDestroyImageKHR(raspitex_state->display, raspitex_state->u_egl_image);
    raspitex_state->u_egl_image = EGL_NO_IMAGE_KHR;
    glDeleteTextures(1, &raspitex_state->v_texture);
    eglDestroyImageKHR(raspitex_state->display, raspitex_state->v_egl_image);
    raspitex_state->v_egl_image = EGL_NO_IMAGE_KHR;
    /* Terminate EGL */
    eglMakeCurrent(raspitex_state->display, EGL_NO_SURFACE,
                   EGL_NO_SURFACE, EGL_NO_CONTEXT);
    eglDestroyContext(raspitex_state->display, raspitex_state->context);
    eglDestroySurface(raspitex_state->display, raspitex_state->surface);
    eglTerminate(raspitex_state->display);
 }
raspitexutil_redraw()
int raspitexutil_redraw (RASPITEX_STATE * raspitex_state)
Default is a no-op
Parameters
raspitex_state A pointer to the GL preview state.
Returns
Zero.
Definition at line 419 of file RaspiTexUtil.c.
References void().
Referenced by raspitex_set_defaults().
 {
    (void) raspitex_state;
    return 0;
 }
raspitexutil_update_model()
int raspitexutil_update_model (RASPITEX_STATE * raspitex_state)
Default is a no-op
Parameters
raspitex_state A pointer to the GL preview state.
Returns
Zero.
Definition at line 408 of file RaspiTexUtil.c.
References void().
Referenced by raspitex_set_defaults().
 {
    (void) raspitex_state;
    return 0;
 }
raspitexutil_update_texture()
int raspitexutil_update_texture (RASPITEX_STATE * raspitex_state, EGLClientBuffer mm_buf)
Updates the RGBX texture to the specified MMAL buffer.
Parameters
raspitex_state A pointer to the GL preview state.
mm_buf The MMAL buffer.
Returns
Zero if successful.
Definition at line 353 of file RaspiTexUtil.c.
References RASPITEX_STATE::display, RASPITEX_STATE::egl_image, EGL_IMAGE_BRCM_MULTIMEDIA, raspitexutil_do_update_texture(), and RASPITEX_STATE::texture.
 {
    return raspitexutil_do_update_texture(raspitex_state->display,
                                          EGL_IMAGE_BRCM_MULTIMEDIA, mm_buf,
                                          &raspitex_state->texture, &raspitex_state->egl_image);
 }
raspitexutil_update_u_texture()
int raspitexutil_update_u_texture (RASPITEX_STATE * raspitex_state, EGLClientBuffer mm_buf)
Updates the U plane texture to the specified MMAL buffer.
Parameters
raspitex_state A pointer to the GL preview state.
mm_buf The MMAL buffer.
Returns
Zero if successful.
Definition at line 381 of file RaspiTexUtil.c.
References RASPITEX_STATE::display, EGL_IMAGE_BRCM_MULTIMEDIA_U, raspitexutil_do_update_texture(), RASPITEX_STATE::u_egl_image, and RASPITEX_STATE::u_texture.
 {
    return raspitexutil_do_update_texture(raspitex_state->display,
                                          EGL_IMAGE_BRCM_MULTIMEDIA_U, mm_buf,
                                          &raspitex_state->u_texture, &raspitex_state->u_egl_image);
 }
raspitexutil_update_v_texture()
int raspitexutil_update_v_texture (RASPITEX_STATE * raspitex_state, EGLClientBuffer mm_buf)
Updates the V plane texture to the specified MMAL buffer.
Parameters
raspitex_state A pointer to the GL preview state.
mm_buf The MMAL buffer.
Returns
Zero if successful.
Definition at line 395 of file RaspiTexUtil.c.
References RASPITEX_STATE::display, EGL_IMAGE_BRCM_MULTIMEDIA_V, raspitexutil_do_update_texture(), RASPITEX_STATE::v_egl_image, and RASPITEX_STATE::v_texture.
 {
    return raspitexutil_do_update_texture(raspitex_state->display,
                                          EGL_IMAGE_BRCM_MULTIMEDIA_V, mm_buf,
                                          &raspitex_state->v_texture, &raspitex_state->v_egl_image);
 }
raspitexutil_update_y_texture()
int raspitexutil_update_y_texture (RASPITEX_STATE * raspitex_state, EGLClientBuffer mm_buf)
Updates the Y plane texture to the specified MMAL buffer.
Parameters
raspitex_state A pointer to the GL preview state.
mm_buf The MMAL buffer.
Returns
Zero if successful.
Definition at line 367 of file RaspiTexUtil.c.
References RASPITEX_STATE::display, EGL_IMAGE_BRCM_MULTIMEDIA_Y, raspitexutil_do_update_texture(), RASPITEX_STATE::y_egl_image, and RASPITEX_STATE::y_texture.
 {
    return raspitexutil_do_update_texture(raspitex_state->display,
                                          EGL_IMAGE_BRCM_MULTIMEDIA_Y, mm_buf,
                                          &raspitex_state->y_texture, &raspitex_state->y_egl_image);
 }
Variable Documentation
raspitex_log_category
VCOS_LOG_CAT_T raspitex_log_category
Definition at line 34 of file RaspiTexUtil.c.