VideoCore Library: RASPITEX_SCENE_OPS Struct Reference
RASPITEX_SCENE_OPS Struct Reference
#include <RaspiTex.h>
Public Attributes
int(* create_native_window)(struct RASPITEX_STATE *state)
int(* gl_init)(struct RASPITEX_STATE *state)
Creates EGL surface for native window.
int(* update_texture)(struct RASPITEX_STATE *state, EGLClientBuffer mm_buf)
int(* update_y_texture)(struct RASPITEX_STATE *state, EGLClientBuffer mm_buf)
int(* update_u_texture)(struct RASPITEX_STATE *state, EGLClientBuffer mm_buf)
int(* update_v_texture)(struct RASPITEX_STATE *state, EGLClientBuffer mm_buf)
int(* update_model)(struct RASPITEX_STATE *state)
Advance to the next animation step.
int(* redraw)(struct RASPITEX_STATE *state)
Draw the scene - called after update_model.
int(* capture)(struct RASPITEX_STATE *state, uint8_t **buffer, size_t *buffer_size)
void(* gl_term)(struct RASPITEX_STATE *state)
Creates EGL surface for native window.
void(* destroy_native_window)(struct RASPITEX_STATE *state)
Destroys the native window.
void(* close)(struct RASPITEX_STATE *state)
Called when the scene is unloaded.
Detailed Description
Definition at line 56 of file RaspiTex.h.
Member Data Documentation
capture
int(* RASPITEX_SCENE_OPS::capture) (struct RASPITEX_STATE *state, uint8_t **buffer, size_t *buffer_size)
Allocates a buffer and copies the pixels from the current frame-buffer into it.
Definition at line 89 of file RaspiTex.h.
Referenced by raspitex_set_defaults().
close
void(* RASPITEX_SCENE_OPS::close) (struct RASPITEX_STATE *state)
Called when the scene is unloaded.
Definition at line 99 of file RaspiTex.h.
Referenced by raspitex_destroy(), and raspitex_set_defaults().
create_native_window
int(* RASPITEX_SCENE_OPS::create_native_window) (struct RASPITEX_STATE *state)
Creates a native window that will be used by egl_init to create a window surface.
Definition at line 60 of file RaspiTex.h.
Referenced by raspitex_set_defaults().
destroy_native_window
void(* RASPITEX_SCENE_OPS::destroy_native_window) (struct RASPITEX_STATE *state)
Destroys the native window.
Definition at line 96 of file RaspiTex.h.
Referenced by raspitex_destroy(), and raspitex_set_defaults().
gl_init
int(* RASPITEX_SCENE_OPS::gl_init) (struct RASPITEX_STATE *state)
Creates EGL surface for native window.
Definition at line 63 of file RaspiTex.h.
Referenced by mirror_open(), raspitex_set_defaults(), sobel_open(), square_open(), teapot_open(), vcsm_square_open(), and yuv_open().
gl_term
void(* RASPITEX_SCENE_OPS::gl_term) (struct RASPITEX_STATE *state)
Creates EGL surface for native window.
Definition at line 93 of file RaspiTex.h.
Referenced by raspitex_set_defaults().
redraw
int(* RASPITEX_SCENE_OPS::redraw) (struct RASPITEX_STATE *state)
Draw the scene - called after update_model.
Definition at line 85 of file RaspiTex.h.
Referenced by raspitex_set_defaults().
update_model
int(* RASPITEX_SCENE_OPS::update_model) (struct RASPITEX_STATE *state)
Advance to the next animation step.
Definition at line 82 of file RaspiTex.h.
Referenced by raspitex_set_defaults().
update_texture
int(* RASPITEX_SCENE_OPS::update_texture) (struct RASPITEX_STATE *state, EGLClientBuffer mm_buf)
Updates the RGBX texture from the next MMAL buffer Set to null if this texture type is not required
Definition at line 67 of file RaspiTex.h.
update_u_texture
int(* RASPITEX_SCENE_OPS::update_u_texture) (struct RASPITEX_STATE *state, EGLClientBuffer mm_buf)
Updates the U plane texture from the next MMAL buffer Set to null if this texture type is not required
Definition at line 75 of file RaspiTex.h.
update_v_texture
int(* RASPITEX_SCENE_OPS::update_v_texture) (struct RASPITEX_STATE *state, EGLClientBuffer mm_buf)
Updates the V plane texture from the next MMAL buffer Set to null if this texture type is not required
Definition at line 79 of file RaspiTex.h.
update_y_texture
int(* RASPITEX_SCENE_OPS::update_y_texture) (struct RASPITEX_STATE *state, EGLClientBuffer mm_buf)
Updates the Y' plane texture from the next MMAL buffer Set to null if this texture type is not required
Definition at line 71 of file RaspiTex.h.
The documentation for this struct was generated from the following file:
host_applications/linux/apps/raspicam/RaspiTex.h