VideoCore Library: helpers/dtoverlay/dtoverlay.h File Reference
dtoverlay.h File Reference
#include <stdarg.h>
Classes
struct dtoverlay_struct
struct dtblob_struct
struct pin_iter_struct
Macros
#define BE4(x) ((x)>>24)&0xff, ((x)>>16)&0xff, ((x)>>8)&0xff, ((x)>>0)&0xff
#define GETBE4(p, off)
#define SETBE4(p, off, x)
#define NON_FATAL(err) (((err) < 0) ? -(err) : (err))
#define IS_FATAL(err) ((err) < 0)
#define ONLY_FATAL(err) (IS_FATAL(err) ? (err) : 0)
#define DTOVERLAY_PADDING(size) (-(size))
Typedefs
typedef struct dtoverlay_struct DTOVERLAY_PARAM_T
typedef struct dtblob_struct DTBLOB_T
typedef struct pin_iter_struct PIN_ITER_T
typedef void DTOVERLAY_LOGGING_FUNC(dtoverlay_logging_type_t type, const char *fmt, va_list args)
typedef int(* override_callback_t) (int override_type, const char *override_value, DTBLOB_T *dtb, int node_off, const char *prop_name, int target_phandle, int target_off, int target_size, void *callback_state)
Enumerations
enum dtoverlay_logging_type_t { DTOVERLAY_ERROR, DTOVERLAY_DEBUG }
Functions
uint8_t dtoverlay_read_u8 (const void *src, int off)
uint16_t dtoverlay_read_u16 (const void *src, int off)
uint32_t dtoverlay_read_u32 (const void *src, int off)
uint64_t dtoverlay_read_u64 (const void *src, int off)
void dtoverlay_write_u8 (void *dst, int off, uint32_t val)
void dtoverlay_write_u16 (void *dst, int off, uint32_t val)
void dtoverlay_write_u32 (void *dst, int off, uint32_t val)
void dtoverlay_write_u64 (void *dst, int off, uint64_t val)
int dtoverlay_create_node (DTBLOB_T *dtb, const char *node_name, int path_len)
int dtoverlay_delete_node (DTBLOB_T *dtb, const char *node_name, int path_len)
int dtoverlay_find_node (DTBLOB_T *dtb, const char *node_path, int path_len)
int dtoverlay_set_node_properties (DTBLOB_T *dtb, const char *node_path, DTOVERLAY_PARAM_T *properties, unsigned int num_properties)
int dtoverlay_create_prop_fragment (DTBLOB_T *dtb, int idx, int target_phandle, const char *prop_name, const void *prop_data, int prop_len)
int dtoverlay_fixup_overlay (DTBLOB_T *base_dtb, DTBLOB_T *overlay_dtb)
int dtoverlay_merge_overlay (DTBLOB_T *base_dtb, DTBLOB_T *overlay_dtb)
int dtoverlay_merge_params (DTBLOB_T *dtb, const DTOVERLAY_PARAM_T *params, unsigned int num_params)
const char * dtoverlay_find_override (DTBLOB_T *dtb, const char *override_name, int *data_len)
int dtoverlay_override_one_target (int override_type, const char *override_value, DTBLOB_T *dtb, int node_off, const char *prop_name, int target_phandle, int target_off, int target_size, void *callback_state)
int dtoverlay_foreach_override_target (DTBLOB_T *dtb, const char *override_name, const char *override_data, int data_len, const char *override_value, override_callback_t callback, void *callback_value)
int dtoverlay_apply_override (DTBLOB_T *dtb, const char *override_name, const char *override_data, int data_len, const char *override_value)
int dtoverlay_set_synonym (DTBLOB_T *dtb, const char *dst, const char *src)
int dtoverlay_dup_property (DTBLOB_T *dtb, const char *node_name, const char *dst, const char *src)
DTBLOB_T * dtoverlay_create_dtb (int max_size)
DTBLOB_T * dtoverlay_load_dtb_from_fp (FILE *fp, int max_size)
DTBLOB_T * dtoverlay_load_dtb (const char *filename, int max_size)
DTBLOB_T * dtoverlay_import_fdt (void *fdt, int max_size)
int dtoverlay_save_dtb (const DTBLOB_T *dtb, const char *filename)
int dtoverlay_extend_dtb (DTBLOB_T *dtb, int new_size)
int dtoverlay_dtb_totalsize (DTBLOB_T *dtb)
void dtoverlay_pack_dtb (DTBLOB_T *dtb)
void dtoverlay_free_dtb (DTBLOB_T *dtb)
int dtoverlay_find_pins_for_device (DTBLOB_T *dtb, const char *symbol, PIN_ITER_T *iter)
int dtoverlay_next_pin (PIN_ITER_T *iter, int *pin, int *func, int *pull)
int dtoverlay_find_phandle (DTBLOB_T *dtb, int phandle)
int dtoverlay_find_symbol (DTBLOB_T *dtb, const char *symbol_name)
int dtoverlay_find_matching_node (DTBLOB_T *dtb, const char **node_names, int pos)
int dtoverlay_node_is_enabled (DTBLOB_T *dtb, int pos)
const void * dtoverlay_get_property (DTBLOB_T *dtb, int pos, const char *prop_name, int *prop_len)
int dtoverlay_set_property (DTBLOB_T *dtb, int pos, const char *prop_name, const void *prop, int prop_len)
const char * dtoverlay_get_alias (DTBLOB_T *dtb, const char *alias_name)
int dtoverlay_set_alias (DTBLOB_T *dtb, const char *alias_name, const char *value)
void dtoverlay_set_logging_func (DTOVERLAY_LOGGING_FUNC *func)
void dtoverlay_enable_debug (int enable)
void dtoverlay_error (const char *fmt,...)
void dtoverlay_debug (const char *fmt,...)
Macro Definition Documentation
BE4
#define BE4 (x) ((x)>>24)&0xff, ((x)>>16)&0xff, ((x)>>8)&0xff, ((x)>>0)&0xff
Definition at line 33 of file dtoverlay.h.
DTOVERLAY_PADDING
#define DTOVERLAY_PADDING (size) (-(size))
Definition at line 47 of file dtoverlay.h.
GETBE4
#define GETBE4 (p, off)
Value:
((((unsigned char *)p)[off + 0]<<24) + (((unsigned char *)p)[off + 1]<<16) + \
                  (((unsigned char *)p)[off + 2]<<8) + (((unsigned char *)p)[off + 3]<<0))
Definition at line 34 of file dtoverlay.h.
Referenced by dtoverlay_next_pin().
IS_FATAL
#define IS_FATAL (err) ((err) < 0)
Definition at line 44 of file dtoverlay.h.
NON_FATAL
#define NON_FATAL (err) (((err) < 0) ? -(err) : (err))
Definition at line 43 of file dtoverlay.h.
Referenced by dtoverlay_merge_overlay(), dtoverlay_merge_params(), and dtparam_apply().
ONLY_FATAL
#define ONLY_FATAL (err) (IS_FATAL(err) ? (err) : 0)
Definition at line 45 of file dtoverlay.h.
SETBE4
#define SETBE4 (p, off, x)
Value:
do { \
   ((unsigned char *)p)[off + 0] = ((x>>24) & 0xff); \
   ((unsigned char *)p)[off + 1] = ((x>>16) & 0xff); \
   ((unsigned char *)p)[off + 2] = ((x>>8) & 0xff); \
   ((unsigned char *)p)[off + 3] = ((x>>0) & 0xff); \
} while (0)
Definition at line 36 of file dtoverlay.h.
Typedef Documentation
DTBLOB_T
typedef struct dtblob_struct DTBLOB_T
DTOVERLAY_LOGGING_FUNC
typedef void DTOVERLAY_LOGGING_FUNC(dtoverlay_logging_type_t type, const char *fmt, va_list args)
Definition at line 89 of file dtoverlay.h.
DTOVERLAY_PARAM_T
typedef struct dtoverlay_struct DTOVERLAY_PARAM_T
override_callback_t
typedef int(* override_callback_t) (int override_type, const char *override_value, DTBLOB_T *dtb, int node_off, const char *prop_name, int target_phandle, int target_off, int target_size, void *callback_state)
Definition at line 92 of file dtoverlay.h.
PIN_ITER_T
typedef struct pin_iter_struct PIN_ITER_T
Enumeration Type Documentation
dtoverlay_logging_type_t
enum dtoverlay_logging_type_t
Enumerator
DTOVERLAY_ERROR
DTOVERLAY_DEBUG
Definition at line 49 of file dtoverlay.h.
 {
    DTOVERLAY_ERROR,
    DTOVERLAY_DEBUG
 } dtoverlay_logging_type_t;
Function Documentation
dtoverlay_apply_override()
int dtoverlay_apply_override (DTBLOB_T * dtb, const char * override_name, const char * override_data, int data_len, const char * override_value)
Definition at line 1503 of file dtoverlay.c.
References dtoverlay_foreach_override_target(), dtoverlay_override_one_target(), and NULL.
 {
    return dtoverlay_foreach_override_target(dtb, override_name,
                         override_data, data_len,
                         override_value,
                         dtoverlay_override_one_target,
                         NULL);
 }
dtoverlay_create_dtb()
DTBLOB_T* dtoverlay_create_dtb (int max_size)
Definition at line 1948 of file dtoverlay.c.
References dtoverlay_error(), dtblob_struct::fdt, fdt_create_empty_tree(), dtblob_struct::max_phandle, NULL, and dtblob_struct::trailer.
 {
    DTBLOB_T *dtb = NULL;
    void *fdt = NULL;
    fdt = malloc(max_size);
    if (!fdt)
    {
       dtoverlay_error("out of memory");
       goto error_exit;
    }
    if (fdt_create_empty_tree(fdt, max_size) != 0)
    {
       dtoverlay_error("failed to create empty dtb");
       goto error_exit;
    }
    dtb = calloc(1, sizeof(DTBLOB_T));
    if (!dtb)
    {
       dtoverlay_error("out of memory");
       goto error_exit;
    }
    dtb->fdt = fdt;
    dtb->max_phandle = 0; // Not a valid phandle
    return dtb;
 error_exit:
    free(fdt);
    if (dtb)
       free(dtb->trailer);
    free(dtb);
    return NULL;
 }
dtoverlay_create_node()
int dtoverlay_create_node (DTBLOB_T * dtb, const char * node_name, int path_len)
Definition at line 147 of file dtoverlay.c.
References dtblob_struct::fdt, fdt_add_subnode_namelen(), FDT_ERR_BADPATH, and fdt_subnode_offset_namelen().
Referenced by dtoverlay_merge_params(), and dtoverlay_set_node_properties().
 {
    const char *path_ptr;
    const char *path_end;
    int node_off = 0;
    if (!path_len)
       path_len = strlen(node_path);
    path_ptr = node_path;
    path_end = node_path + path_len;
    if ((path_len > 0) && (path_ptr[path_len - 1] == '/'))
        path_end--;
    while (path_ptr < path_end)
    {
       const char *path_next;
       int subnode_off;
       if (*path_ptr != '/')
          return -FDT_ERR_BADPATH;
       // find the next path separator (or the end of the string)
       path_ptr++;
       for (path_next = path_ptr;
            (path_next != path_end) && (*path_next != '/');
            path_next++)
          continue;
       subnode_off = fdt_subnode_offset_namelen(dtb->fdt, node_off, path_ptr,
                                                path_next - path_ptr);
       if (subnode_off >= 0)
          node_off = subnode_off;
       else
          node_off = fdt_add_subnode_namelen(dtb->fdt, node_off, path_ptr,
                                             path_next - path_ptr);
       if (node_off < 0)
          break;
       path_ptr = path_next;
    }
    if ((node_off >= 0) && (path_ptr != path_end))
       return -FDT_ERR_BADPATH;
    return node_off;
 }
dtoverlay_create_prop_fragment()
int dtoverlay_create_prop_fragment (DTBLOB_T * dtb, int idx, int target_phandle, const char * prop_name, const void * prop_data, int prop_len)
Definition at line 514 of file dtoverlay.c.
References dtblob_struct::fdt, and fdt_add_subnode().
 {
     char fragment_name[20];
     int frag_off, ovl_off;
     int ret;
     snprintf(fragment_name, sizeof(fragment_name), "fragment-%u", idx);
     frag_off = fdt_add_subnode(dtb->fdt, 0, fragment_name);
     if (frag_off < 0)
         return frag_off;
     ret = fdt_setprop_u32(dtb->fdt, frag_off, "target", target_phandle);
     if (ret < 0)
         return ret;
     ovl_off = fdt_add_subnode(dtb->fdt, frag_off, "__overlay__");
     if (ovl_off < 0)
         return ovl_off;
     return fdt_setprop(dtb->fdt, ovl_off, prop_name, prop_data, prop_len);
 }
dtoverlay_debug()
void dtoverlay_debug (const char * fmt, ...)
Definition at line 2358 of file dtoverlay.c.
Referenced by dtoverlay_delete_node(), dtoverlay_dup_property(), dtoverlay_find_override(), dtoverlay_merge_overlay(), and dtoverlay_save_dtb().
 {
    va_list args;
    if (dtoverlay_debug_enabled)
    {
       va_start(args, fmt);
       (*dtoverlay_logging_func)(DTOVERLAY_DEBUG, fmt, args);
       va_end(args);
    }
 }
dtoverlay_delete_node()
int dtoverlay_delete_node (DTBLOB_T * dtb, const char * node_name, int path_len)
Definition at line 197 of file dtoverlay.c.
References dtoverlay_debug(), dtblob_struct::fdt, fdt_del_node(), and fdt_path_offset_namelen().
 {
    int node_off = 0;
    if (!path_len)
       path_len = strlen(node_path);
    dtoverlay_debug("delete_node(%.*s)", path_len, node_path);
    node_off = fdt_path_offset_namelen(dtb->fdt, node_path, path_len);
    if (node_off < 0)
       return node_off;
    return fdt_del_node(dtb->fdt, node_off);
 }
dtoverlay_dtb_totalsize()
int dtoverlay_dtb_totalsize (DTBLOB_T * dtb)
Definition at line 2201 of file dtoverlay.c.
References dtblob_struct::fdt, and fdt_totalsize.
 {
    return fdt_totalsize(dtb->fdt);
 }
dtoverlay_dup_property()
int dtoverlay_dup_property (DTBLOB_T * dtb, const char * node_name, const char * dst, const char * src)
Definition at line 1855 of file dtoverlay.c.
References dtoverlay_debug(), dtblob_struct::fdt, fdt_getprop(), fdt_path_offset(), fdt_setprop(), and fdt_setprop_inplace().
Referenced by dtoverlay_set_synonym().
 {
    /* Find the node and src property */
    const DTBLOB_T *src_prop;
    int node_off;
    int prop_len = 0;
    int err = 0;
    node_off = fdt_path_offset(dtb->fdt, node_name);
    if (node_off < 0)
       return 0;
    src_prop = fdt_getprop(dtb->fdt, node_off, src, &prop_len);
    if (!src_prop)
       return 0;
    err = fdt_setprop_inplace(dtb->fdt, node_off, dst, src_prop, prop_len);
    if (err != 0)
    {
       void *prop_data;
       /* Copy the src property, just in case things move */
       prop_data = malloc(prop_len);
       memcpy(prop_data, src_prop, prop_len);
       err = fdt_setprop(dtb->fdt, node_off, dst, prop_data, prop_len);
       free(prop_data);
    }
    if (err == 0)
       dtoverlay_debug("%s:%s=%s", node_name, dst, src);
    return err;
 }
dtoverlay_enable_debug()
void dtoverlay_enable_debug (int enable)
Definition at line 2345 of file dtoverlay.c.
Referenced by main().
 {
    dtoverlay_debug_enabled = enable;
 }
dtoverlay_error()
void dtoverlay_error (const char * fmt, ...)
Definition at line 2350 of file dtoverlay.c.
References DTOVERLAY_ERROR.
Referenced by dtoverlay_create_dtb(), dtoverlay_find_symbol(), dtoverlay_import_fdt(), dtoverlay_load_dtb(), dtoverlay_load_dtb_from_fp(), dtoverlay_merge_overlay(), dtoverlay_save_dtb(), dtoverlay_set_property(), and dtparam_apply().
 {
    va_list args;
    va_start(args, fmt);
    (*dtoverlay_logging_func)(DTOVERLAY_ERROR, fmt, args);
    va_end(args);
 }
dtoverlay_extend_dtb()
int dtoverlay_extend_dtb (DTBLOB_T * dtb, int new_size)
Definition at line 2164 of file dtoverlay.c.
References dtblob_struct::fdt, FDT_ERR_NOSPACE, dtblob_struct::fdt_is_malloced, and fdt_totalsize.
 {
    int size = fdt_totalsize(dtb->fdt);
    int err = 0;
    if (new_size < 0)
       new_size = size - new_size;
    if (new_size > size)
    {
       void *fdt;
       fdt = malloc(new_size);
       if (fdt)
       {
          memcpy(fdt, dtb->fdt, size);
          fdt_set_totalsize(fdt, new_size);
          if (dtb->fdt_is_malloced)
             free(dtb->fdt);
          dtb->fdt = fdt;
          dtb->fdt_is_malloced = 1;
       }
       else
       {
          err = -FDT_ERR_NOSPACE;
       }
    }
    else if (new_size < size)
    {
       /* Can't shrink it */
       err = -FDT_ERR_NOSPACE;
    }
    return err;
 }
dtoverlay_find_matching_node()
int dtoverlay_find_matching_node (DTBLOB_T * dtb, const char ** node_names, int pos)
Definition at line 2261 of file dtoverlay.c.
References dtblob_struct::fdt, fdt_get_name(), fdt_next_node(), and NULL.
 {
    while (1)
    {
       const char *node_name;
       pos = fdt_next_node(dtb->fdt, pos, NULL);
       if (pos < 0)
          break;
       node_name = fdt_get_name(dtb->fdt, pos, NULL);
       if (node_name)
       {
          int i;
          for (i = 0; node_names[i]; i++)
          {
             const char *node = node_names[i];
             int matchlen = strlen(node);
             if ((strncmp(node_name, node, matchlen) == 0) &&
                 ((node[matchlen] == '\0') ||
                  (node[matchlen] == '@')))
                return pos;
          }
       }
    }
    return -1;
 }
dtoverlay_find_node()
int dtoverlay_find_node (DTBLOB_T * dtb, const char * node_path, int path_len)
Definition at line 212 of file dtoverlay.c.
References dtblob_struct::fdt, and fdt_path_offset_namelen().
 {
    if (!path_len)
       path_len = strlen(node_path);
    return fdt_path_offset_namelen(dtb->fdt, node_path, path_len);
 }
dtoverlay_find_override()
const char* dtoverlay_find_override (DTBLOB_T * dtb, const char * override_name, int * data_len)
Definition at line 1114 of file dtoverlay.c.
References dtoverlay_debug(), dtblob_struct::fdt, fdt_getprop(), fdt_path_offset(), dynstring::len, and NULL.
 {
    int overrides_off;
    const char *data;
    int len;
    // Find the table of overrides
    overrides_off = fdt_path_offset(dtb->fdt, "/__overrides__");
    if (overrides_off < 0)
    {
       dtoverlay_debug("/__overrides__ node not found");
       *data_len = overrides_off;
       return NULL;
    }
    // Locate the property
    data = fdt_getprop(dtb->fdt, overrides_off, override_name, &len);
    *data_len = len;
    if (data)
       dtoverlay_debug("Found override %s", override_name);
    else
       dtoverlay_debug("/__overrides__ has no %s property", override_name);
    return data;
 }
dtoverlay_find_phandle()
int dtoverlay_find_phandle (DTBLOB_T * dtb, int phandle)
Definition at line 2223 of file dtoverlay.c.
References dtblob_struct::fdt, and fdt_node_offset_by_phandle().
Referenced by dtoverlay_next_pin().
 {
    return fdt_node_offset_by_phandle(dtb->fdt, phandle);
 }
dtoverlay_find_pins_for_device()
int dtoverlay_find_pins_for_device (DTBLOB_T * dtb, const char * symbol, PIN_ITER_T * iter)
Definition at line 1890 of file dtoverlay.c.
References pin_iter_struct::dtb, dtoverlay_find_symbol(), dtoverlay_get_property(), dtoverlay_node_is_enabled(), pin_iter_struct::pinctrl, and pin_iter_struct::pinctrl_len.
 {
    int pos = dtoverlay_find_symbol(dtb, symbol);
    memset(iter, 0, sizeof(*iter));
    if (pos < 0)
       return pos;
    iter->dtb = dtb;
    if (dtoverlay_node_is_enabled(dtb, pos))
       iter->pinctrl = dtoverlay_get_property(dtb, pos, "pinctrl-0", &iter->pinctrl_len);
    return 0;
 }
dtoverlay_find_symbol()
int dtoverlay_find_symbol (DTBLOB_T * dtb, const char * symbol_name)
Definition at line 2228 of file dtoverlay.c.
References dtoverlay_error(), dtoverlay_get_alias(), dtblob_struct::fdt, FDT_ERR_NOTFOUND, fdt_getprop(), fdt_path_offset(), and fdt_path_offset_namelen().
Referenced by dtoverlay_find_pins_for_device().
 {
    int symbols_off, path_len;
    const char *node_path;
    node_path = dtoverlay_get_alias(dtb, symbol_name);
    if (node_path)
    {
       path_len = strlen(node_path);
    }
    else
    {
       symbols_off = fdt_path_offset(dtb->fdt, "/__symbols__");
       if (symbols_off < 0)
       {
          dtoverlay_error("No symbols found");
          return -FDT_ERR_NOTFOUND;
       }
       node_path = fdt_getprop(dtb->fdt, symbols_off, symbol_name, &path_len);
       if (path_len < 0)
          return -FDT_ERR_NOTFOUND;
       //Ensure we don't have trailing NULLs
       if (path_len > strnlen(node_path, path_len))
          path_len = strnlen(node_path, path_len);
    }
    return fdt_path_offset_namelen(dtb->fdt, node_path, path_len);
 }
dtoverlay_fixup_overlay()
int dtoverlay_fixup_overlay (DTBLOB_T * base_dtb, DTBLOB_T * overlay_dtb)
Definition at line 1043 of file dtoverlay.c.
 {
    int err;
    // To do: Check the "compatible" string?
    err = dtoverlay_resolve_fixups(base_dtb, overlay_dtb);
    if (err >= 0)
       err = dtoverlay_resolve_phandles(base_dtb, overlay_dtb);
    overlay_dtb->fixups_applied = 1;
    return NON_FATAL(err);
 }
dtoverlay_foreach_override_target()
int dtoverlay_foreach_override_target (DTBLOB_T * dtb, const char * override_name, const char * override_data, int data_len, const char * override_value, override_callback_t callback, void * callback_value)
Definition at line 1419 of file dtoverlay.c.
Referenced by dtoverlay_apply_override(), and dtparam_apply().
 {
    int err = 0;
    int target_phandle = 0;
    char *data_buf, *data, *data_end;
    /* Short-circuit the degenerate case of an empty parameter, avoiding an
       apparent memory allocation failure. */
    if (!data_len)
       return 0;
    /* Copy the override data in case it moves */
    data_buf = malloc(data_len);
    if (!data_buf)
    {
       dtoverlay_error("  out of memory");
       return NON_FATAL(FDT_ERR_NOSPACE);
    }
    memcpy(data_buf, override_data, data_len);
    data = data_buf;
    data_end = data + data_len;
    while (err == 0)
    {
       const char *target_prop = NULL;
       static char prop_name[256];
       static char target_value[256];
       int name_len = 0;
       int target_off = 0;
       int target_size = 0;
       int override_type;
       int node_off = 0;
       strcpy(target_value, override_value);
       override_type = dtoverlay_extract_override(override_name,
                                                  target_value, sizeof(target_value),
                                                  &target_phandle,
                                                  (const char **)&data, data_end,
                                                  &target_prop, &name_len,
                                                  &target_off, &target_size);
       if (override_type < 0)
       {
          err = override_type;
          break;
       }
       /* Pass DTOVERRIDE_END to the callback, in case it is interested */
       if (target_phandle != 0)
       {
          node_off = fdt_node_offset_by_phandle(dtb->fdt, target_phandle);
          if (node_off < 0)
          {
             dtoverlay_error("  phandle %d not found", target_phandle);
             err = NON_FATAL(node_off);
             break;
          }
       }
       /* Sadly there are no '_namelen' setprop variants, so copies are required */
       if (target_prop)
       {
          memcpy(prop_name, target_prop, name_len);
          prop_name[name_len] = '\0';
       }
       err = callback(override_type, target_value, dtb, node_off, prop_name,
              target_phandle, target_off, target_size, callback_state);
       if (override_type == DTOVERRIDE_END)
          break;
    }
    free(data_buf);
    return err;
 }
dtoverlay_free_dtb()
void dtoverlay_free_dtb (DTBLOB_T * dtb)
Definition at line 2211 of file dtoverlay.c.
References dtblob_struct::fdt, dtblob_struct::fdt_is_malloced, dtblob_struct::trailer, and dtblob_struct::trailer_is_malloced.
 {
    if (dtb)
    {
       if (dtb->fdt_is_malloced)
          free(dtb->fdt);
       if (dtb->trailer_is_malloced)
          free(dtb->trailer);
       free(dtb);
    }
 }
dtoverlay_get_alias()
const char* dtoverlay_get_alias (DTBLOB_T * dtb, const char * alias_name)
Definition at line 2315 of file dtoverlay.c.
References dtblob_struct::fdt, fdt_getprop(), and fdt_path_offset().
Referenced by dtoverlay_find_symbol().
 {
    int node_off;
    int prop_len;
    const char *alias;
    node_off = fdt_path_offset(dtb->fdt, "/aliases");
    alias = fdt_getprop(dtb->fdt, node_off, alias_name, &prop_len);
    if (alias && !prop_len)
        alias = "";
    return alias;
 }
dtoverlay_get_property()
const void* dtoverlay_get_property (DTBLOB_T * dtb, int pos, const char * prop_name, int * prop_len)
Definition at line 2301 of file dtoverlay.c.
References dtblob_struct::fdt, and fdt_getprop().
Referenced by dtoverlay_find_pins_for_device(), dtoverlay_next_pin(), and dtoverlay_node_is_enabled().
 {
    return fdt_getprop(dtb->fdt, pos, prop_name, prop_len);
 }
dtoverlay_import_fdt()
DTBLOB_T* dtoverlay_import_fdt (void * fdt, int max_size)
Definition at line 2077 of file dtoverlay.c.
References dtoverlay_error(), dtblob_struct::fdt, fdt_check_header(), FDT_ERR_NOSPACE, fdt_get_phandle(), fdt_next_node(), fdt_totalsize, dtblob_struct::max_phandle, and NULL.
Referenced by dtoverlay_load_dtb_from_fp().
 {
    DTBLOB_T *dtb = NULL;
    int node_off;
    int dtb_len;
    int err;
    err = fdt_check_header(fdt);
    if (err != 0)
    {
       dtoverlay_error("not a valid FDT - err %d", err);
       goto error_exit;
    }
    dtb_len = fdt_totalsize(fdt);
    if (buf_size < dtb_len)
    {
       dtoverlay_error("fdt is too large");
       err = -FDT_ERR_NOSPACE;
       goto error_exit;
    }
    if (buf_size > dtb_len)
          fdt_set_totalsize(fdt, buf_size);
    dtb = calloc(1, sizeof(DTBLOB_T));
    if (!dtb)
    {
       dtoverlay_error("out of memory");
       goto error_exit;
    }
    dtb->fdt = fdt;
    dtb->max_phandle = 0; // Not a valid phandle
    // Find the minimum and maximum phandles, in case it is necessary to
    // relocate existing ones or create new ones.
    for (node_off = 0;
         node_off >= 0;
         node_off = fdt_next_node(fdt, node_off, NULL))
    {
       uint32_t phandle = fdt_get_phandle(fdt, node_off);
       if (phandle > dtb->max_phandle)
          dtb->max_phandle = phandle;
    }
 error_exit:
    return dtb;
 }
dtoverlay_load_dtb()
DTBLOB_T* dtoverlay_load_dtb (const char * filename, int max_size)
Definition at line 2068 of file dtoverlay.c.
References dtoverlay_error(), dtoverlay_load_dtb_from_fp(), and NULL.
 {
    FILE *fp = fopen(filename, "rb");
    if (fp)
       return dtoverlay_load_dtb_from_fp(fp, max_size);
    dtoverlay_error("Failed to open '%s'", filename);
    return NULL;
 }
dtoverlay_load_dtb_from_fp()
DTBLOB_T* dtoverlay_load_dtb_from_fp (FILE * fp, int max_size)
Definition at line 1987 of file dtoverlay.c.
References dtoverlay_error(), dtoverlay_import_fdt(), dtblob_struct::fdt_is_malloced, fdt_totalsize, dynstring::len, NULL, dtblob_struct::trailer, dtblob_struct::trailer_is_malloced, and dtblob_struct::trailer_len.
Referenced by dtoverlay_load_dtb().
 {
    DTBLOB_T *dtb = NULL;
    void *fdt = NULL;
    if (fp)
    {
       long len;
       long bytes_read;
       int dtb_len;
       fseek(fp, 0, SEEK_END);
       len = ftell(fp);
       fseek(fp, 0, SEEK_SET);
       if (max_size > 0)
       {
          if (max_size < len)
          {
             dtoverlay_error("file too large (%d bytes) for max_size", len);
             goto error_exit;
          }
       }
       else if (max_size < 0)
       {
          max_size = len - max_size;
       }
       else
       {
          max_size = len;
       }
       fdt = malloc(max_size);
       if (!fdt)
       {
          dtoverlay_error("out of memory");
          goto error_exit;
       }
       bytes_read = fread(fdt, 1, len, fp);
       fclose(fp);
       if (bytes_read != len)
       {
          dtoverlay_error("fread failed");
          goto error_exit;
       }
       // Record the total size before any expansion
       dtb_len = fdt_totalsize(fdt);
       dtb = dtoverlay_import_fdt(fdt, max_size);
       if (!dtb)
          goto error_exit;
       dtb->fdt_is_malloced = 1;
       if (len > dtb_len)
       {
          /* Load the trailer */
          dtb->trailer_len = len - dtb_len;
          dtb->trailer = malloc(dtb->trailer_len);
          if (!dtb->trailer)
          {
             dtoverlay_error("out of memory");
             goto error_exit;
          }
          dtb->trailer_is_malloced = 1;
          memcpy(dtb->trailer, (char *)fdt + dtb_len, dtb->trailer_len);
       }
    }
    return dtb;
 error_exit:
    free(fdt);
    if (dtb)
       free(dtb->trailer);
    free(dtb);
    return NULL;
 }
dtoverlay_merge_overlay()
int dtoverlay_merge_overlay (DTBLOB_T * base_dtb, DTBLOB_T * overlay_dtb)
Definition at line 958 of file dtoverlay.c.
References dtoverlay_debug(), dtoverlay_error(), dtblob_struct::fdt, FDT_ERR_BADSTRUCTURE, fdt_first_subnode(), fdt_get_name(), fdt_getprop(), fdt_next_subnode(), fdt_node_offset_by_phandle(), fdt_path_offset_namelen(), fdt_subnode_offset(), dynstring::len, NON_FATAL, and NULL.
 {
    // Merge each fragment node
    int frag_off;
    for (frag_off = fdt_first_subnode(overlay_dtb->fdt, 0);
         frag_off >= 0;
         frag_off = fdt_next_subnode(overlay_dtb->fdt, frag_off))
    {
       const char *node_name, *target_path;
       const char *frag_name;
       int target_off, overlay_off;
       int len, err;
       node_name = fdt_get_name(overlay_dtb->fdt, frag_off, NULL);
       if (strncmp(node_name, "fragment@", 9) != 0 &&
           strncmp(node_name, "fragment-", 9) != 0)
          continue;
       frag_name = node_name + 9;
       dtoverlay_debug("Found fragment %s (offset %d)", frag_name, frag_off);
       // Find the target and overlay nodes
       overlay_off = fdt_subnode_offset(overlay_dtb->fdt, frag_off, "__overlay__");
       if (overlay_off < 0)
       {
          if (fdt_subnode_offset(overlay_dtb->fdt, frag_off, "__dormant__"))
             dtoverlay_debug("fragment %s disabled", frag_name);
          else
             dtoverlay_error("no overlay in fragment %s", frag_name);
          continue;
       }
       target_path = fdt_getprop(overlay_dtb->fdt, frag_off, "target-path", &len);
       if (target_path)
       {
          if (len && (target_path[len - 1] == '\0'))
             len--;
          target_off = fdt_path_offset_namelen(base_dtb->fdt, target_path, len);
          if (target_off < 0)
          {
             dtoverlay_error("invalid target-path '%.*s'", len, target_path);
             return NON_FATAL(target_off);
          }
       }
       else
       {
          const void *target_prop;
          target_prop = fdt_getprop(overlay_dtb->fdt, frag_off, "target", &len);
          if (!target_prop)
          {
             dtoverlay_error("no target or target-path");
             return NON_FATAL(len);
          }
          if (len != 4)
             return NON_FATAL(FDT_ERR_BADSTRUCTURE);
          target_off =
             fdt_node_offset_by_phandle(base_dtb->fdt,
                                        fdt32_to_cpu(*(fdt32_t *)target_prop));
          if (target_off < 0)
          {
             dtoverlay_error("invalid target");
             return NON_FATAL(target_off);
          }
       }
       // Now do the merge
       err = dtoverlay_merge_fragment(base_dtb, target_off, overlay_dtb,
                                      overlay_off, 0);
       if (err != 0)
       {
          dtoverlay_error("merge failed");
          return err;
       }
    }
    base_dtb->max_phandle = overlay_dtb->max_phandle;
    return 0;
 }
dtoverlay_merge_params()
int dtoverlay_merge_params (DTBLOB_T * dtb, const DTOVERLAY_PARAM_T * params, unsigned int num_params)
Definition at line 1060 of file dtoverlay.c.
References dtoverlay_create_node(), FDT_ERR_BADPATH, NON_FATAL, and dtoverlay_struct::param.
 {
    int err = 0;
    unsigned int i;
    for (i=0; (i<num_params) && (err == 0); i++) {
       const DTOVERLAY_PARAM_T *p;
       const char *node_name, *slash;
       int node_off, path_len;
       p = params + i;
       node_name = p->param;
       slash = strrchr(node_name, '/');
       if (!slash)
       {
          err = NON_FATAL(FDT_ERR_BADPATH);
          break;
       }
       // Ensure that root properties ("/xxx") work
       if (slash == node_name)
          path_len = 1;
       else
          path_len = slash - node_name;
       // find node, create if it does not exist yet
       node_off = dtoverlay_create_node(dtb, node_name, path_len);
       if (node_off >= 0)
       {
          const char *prop_name = slash + 1;
          int prop_len;
          struct fdt_property *prop;
          if ((strcmp(prop_name, "bootargs") == 0) &&
             ((prop = fdt_get_property_w(dtb->fdt, node_off, prop_name, &prop_len)) != NULL) &&
             (prop_len > 0) && *prop->data)
          {
             prop->data[prop_len - 1] = ' ';
             err = fdt_appendprop(dtb->fdt, node_off, prop_name, p->b, p->len);
          }
          else
             err = fdt_setprop(dtb->fdt, node_off, prop_name, p->b, p->len);
       }
       else
          err = node_off;
    }
    return err;
 }
dtoverlay_next_pin()
int dtoverlay_next_pin (PIN_ITER_T * iter, int * pin, int * func, int * pull)
Definition at line 1908 of file dtoverlay.c.
References pin_iter_struct::dtb, dtoverlay_find_phandle(), dtoverlay_get_property(), pin_iter_struct::funcs, pin_iter_struct::funcs_len, GETBE4, pin_iter_struct::pin_off, pin_iter_struct::pinctrl, pin_iter_struct::pinctrl_len, pin_iter_struct::pinctrl_off, pin_iter_struct::pins, pin_iter_struct::pins_len, pin_iter_struct::pulls, and pin_iter_struct::pulls_len.
 {
    if (pin)
       *pin = -1;
    if (func)
       *func = -1;
    if (pull)
       *pull = -1;
    while (1)
    {
       int phandle, pos;
       if ((iter->pin_off) + 4 <= iter->pins_len)
       {
          int off = iter->pin_off;
          *pin = GETBE4(iter->pins, off);
          if (func && iter->funcs_len)
             *func = GETBE4(iter->funcs, (iter->funcs_len > 4) ? off : 0);
          if (pull && iter->pulls_len)
             *pull = GETBE4(iter->pulls, (iter->pulls_len > 4) ? off : 0);
          iter->pin_off = off + 4;
          return 1;
       }
       if ((iter->pinctrl_off + 4) > iter->pinctrl_len)
          break;
       phandle = GETBE4(iter->pinctrl, iter->pinctrl_off);
       iter->pinctrl_off += 4;
       pos = dtoverlay_find_phandle(iter->dtb, phandle);
       iter->pins = dtoverlay_get_property(iter->dtb, pos, "brcm,pins", &iter->pins_len);
       iter->funcs = dtoverlay_get_property(iter->dtb, pos, "brcm,function", &iter->funcs_len);
       iter->pulls = dtoverlay_get_property(iter->dtb, pos, "brcm,pull", &iter->pulls_len);
       iter->pin_off = 0;
    }
    return 0;
 }
dtoverlay_node_is_enabled()
int dtoverlay_node_is_enabled (DTBLOB_T * dtb, int pos)
Definition at line 2288 of file dtoverlay.c.
References dtoverlay_get_property(), and NULL.
Referenced by dtoverlay_find_pins_for_device().
 {
    if (pos >= 0)
    {
       const void *prop = dtoverlay_get_property(dtb, pos, "status", NULL);
       if (prop &&
           ((strcmp((const char *)prop, "okay") == 0) ||
            (strcmp((const char *)prop, "ok") == 0)))
          return 1;
    }
    return 0;
 }
dtoverlay_override_one_target()
int dtoverlay_override_one_target (int override_type, const char * override_value, DTBLOB_T * dtb, int node_off, const char * prop_name, int target_phandle, int target_off, int target_size, void * callback_state)
Definition at line 1154 of file dtoverlay.c.
References DTOVERRIDE_STRING.
Referenced by dtoverlay_apply_override(), and dtparam_callback().
 {
    int err = 0;
    if (override_type == DTOVERRIDE_STRING)
    {
       char *prop_val;
       int prop_len;
       /* Replace the whole property with the string */
       if ((strcmp(prop_name, "bootargs") == 0) &&
       ((prop_val = fdt_getprop_w(dtb->fdt, node_off, prop_name,
                      &prop_len)) != NULL) &&
       (prop_len > 0) && prop_val[0])
       {
      prop_val[prop_len - 1] = ' ';
      err = fdt_appendprop_string(dtb->fdt, node_off, prop_name, override_value);
       }
       else if (strcmp(prop_name, "name") == 0) // "name" is a pseudo-property
       {
          err = dtoverlay_set_node_name(dtb, node_off, override_value);
       }
       else
      err = fdt_setprop_string(dtb->fdt, node_off, prop_name, override_value);
    }
    else if (override_type == DTOVERRIDE_BYTE_STRING)
    {
       /* Replace the whole property with the byte string */
       uint8_t bytes_buf[32]; // For efficiency/laziness, place a limit on the length
       const char *p = override_value;
       int byte_count = 0;
       while (*p)
       {
           int nib1, nib2;
           // whitespace and colons are legal separators
           if (*p == ':' || *p == ' ' || *p == '\t')
           {
              p++;
              continue;
           }
           nib1 = hex_digit(*p++);
           nib2 = hex_digit(*p++);
           if (nib1 < 0 || nib2 < 0)
           {
              dtoverlay_error("invalid bytestring '%s'", override_value);
              return NON_FATAL(FDT_ERR_BADVALUE);
           }
           if (byte_count == sizeof(bytes_buf))
           {
              dtoverlay_error("bytestring '%s' too long", override_value);
              return NON_FATAL(FDT_ERR_BADVALUE);
           }
           bytes_buf[byte_count++] = (nib1 << 4) | nib2;
       }
       err = fdt_setprop(dtb->fdt, node_off, prop_name, bytes_buf, byte_count);
    }
    else if (override_type != DTOVERRIDE_END)
    {
       const char *p;
       char *end;
       char *prop_val;
       void *prop_buf = NULL;
       int prop_len;
       int new_prop_len;
       uint64_t override_int;
       uint32_t frag_num;
       /* Parse as an integer */
       override_int = strtoull(override_value, &end, 0);
       if (end[0] != '\0')
       {
          if ((strcmp(override_value, "y") == 0) ||
              (strcmp(override_value, "yes") == 0) ||
              (strcmp(override_value, "on") == 0) ||
              (strcmp(override_value, "true") == 0) ||
              (strcmp(override_value, "down") == 0))
             override_int = 1;
          else if ((strcmp(override_value, "n") == 0) ||
                   (strcmp(override_value, "no") == 0) ||
                   (strcmp(override_value, "off") == 0) ||
                   (strcmp(override_value, "false") == 0))
             override_int = 0;
          else if (strcmp(override_value, "up") == 0)
             override_int = 2;
          else
          {
             dtoverlay_error("invalid override value '%s' - ignored",
                             override_value);
             return NON_FATAL(FDT_ERR_INTERNAL);
          }
       }
       switch (override_type)
       {
       case DTOVERRIDE_INTEGER:
      /* Patch a word within the property */
      prop_val = (void *)fdt_getprop(dtb->fdt, node_off, prop_name,
                     &prop_len);
      new_prop_len = target_off + target_size;
      if (prop_len < new_prop_len)
      {
          /* This property either doesn't exist or isn't long enough.
         Create a buffer containing any existing property data
         with zero padding, which will later be patched and written
         back. */
          prop_buf = calloc(1, new_prop_len);
          if (!prop_buf)
          {
          dtoverlay_error("  out of memory");
          return NON_FATAL(FDT_ERR_NOSPACE);
          }
          if (prop_len > 0)
          memcpy(prop_buf, prop_val, prop_len);
          prop_val = prop_buf;
      }
      switch (target_size)
      {
      case 1:
          dtoverlay_write_u8(prop_val, target_off, (uint32_t)override_int);
          break;
      case 2:
          dtoverlay_write_u16(prop_val, target_off, (uint32_t)override_int);
          break;
      case 4:
          dtoverlay_write_u32(prop_val, target_off, (uint32_t)override_int);
          break;
      case 8:
          dtoverlay_write_u64(prop_val, target_off, override_int);
          break;
      default:
          break;
      }
          if (prop_buf)
          {
             /* Add/extend the property by setting it */
             if (strcmp(prop_name, "reg") != 0) // Don't create or extend "reg" - it must be a pseudo-property
                err = fdt_setprop(dtb->fdt, node_off, prop_name, prop_buf, new_prop_len);
             free(prop_buf);
          }
          if (strcmp(prop_name, "reg") == 0 && target_off == 0)
          {
             const char *old_name = fdt_get_name(dtb->fdt, node_off, NULL);
             const char *atpos = strchr(old_name, '@');
             if (atpos)
             {
                int name_len = (atpos - old_name);
                char *new_name = malloc(name_len + 1 + 16 + 1);
                if (!new_name)
                   return -FDT_ERR_NOSPACE;
                sprintf(new_name, "%.*s@%x", name_len, old_name, (uint32_t)override_int);
                err = dtoverlay_set_node_name(dtb, node_off, new_name);
                free(new_name);
             }
          }
      break;
       case DTOVERRIDE_BOOLEAN:
       case DTOVERRIDE_BOOLEAN_INV:
      /* This is a boolean property (present->true, absent->false) */
      if (override_int ^ (override_type == DTOVERRIDE_BOOLEAN_INV))
         err = fdt_setprop(dtb->fdt, node_off, prop_name, NULL, 0);
      else
      {
         err = fdt_delprop(dtb->fdt, node_off, prop_name);
         if (err == -FDT_ERR_NOTFOUND)
            err = 0;
      }
      break;
       case DTOVERRIDE_OVERLAY:
      /* Apply the overlay-wide override. The supported options are (<frag> is a fragment number):
         +<frag>    Enable a fragment
         -<frag>    Disable a fragment
         =<frag>    Enable/disable the fragment according to the override value
         !<frag>    Disable/enable the fragment according to the inverse of the override value */
      p = prop_name;
      while (*p && !err)
      {
         char type = *p;
         int frag_off;
         switch (type)
         {
         case '+':
         case '-':
         case '=':
         case '!':
            frag_num = strtoul(p + 1, &end, 0);
            if (end != p)
            {
           /* Change fragment@<frag_num>/__overlay__<->__dormant__ as necessary */
           const char *states[2] = { "__dormant__", "__overlay__" };
           char node_name[24];
           int active = (type == '+') ||
               ((type == '=') && (override_int != 0)) ||
               ((type == '!') && (override_int == 0));
           snprintf(node_name, sizeof(node_name), "/fragment@%u", frag_num);
           frag_off = fdt_path_offset(dtb->fdt, node_name);
           if (frag_off < 0)
           {
               snprintf(node_name, sizeof(node_name), "/fragment-%u", frag_num);
               frag_off = fdt_path_offset(dtb->fdt, node_name);
           }
           if (frag_off >= 0)
           {
              frag_off = fdt_subnode_offset(dtb->fdt, frag_off, states[!active]);
              if (frag_off >= 0)
             (void)dtoverlay_set_node_name(dtb, frag_off, states[active]);
           }
           else
           {
              dtoverlay_error("  fragment %u not found", frag_num);
              err = NON_FATAL(frag_off);
           }
           p = end;
            }
            else
            {
           dtoverlay_error("  invalid overlay override '%s'", prop_name);
           err = NON_FATAL(FDT_ERR_BADVALUE);
            }
            break;
         }
      }
      break;
       }
    }
    return err;
 }
dtoverlay_pack_dtb()
void dtoverlay_pack_dtb (DTBLOB_T * dtb)
Definition at line 2206 of file dtoverlay.c.
References dtblob_struct::fdt, and fdt_pack().
 {
    fdt_pack(dtb->fdt);
 }
dtoverlay_read_u16()
uint16_t dtoverlay_read_u16 (const void * src, int off)
Definition at line 88 of file dtoverlay.c.
 {
    const unsigned char *p = src;
    return (p[off + 0] << 8) | (p[off + 1] << 0);
 }
dtoverlay_read_u32()
uint32_t dtoverlay_read_u32 (const void * src, int off)
Definition at line 94 of file dtoverlay.c.
 {
    const unsigned char *p = src;
    return (p[off + 0] << 24) | (p[off + 1] << 16) |
           (p[off + 2] << 8)  | (p[off + 3] << 0);
 }
dtoverlay_read_u64()
uint64_t dtoverlay_read_u64 (const void * src, int off)
Definition at line 101 of file dtoverlay.c.
 {
    const unsigned char *p = src;
    return ((uint64_t)p[off + 0] << 56) | ((uint64_t)p[off + 1] << 48) |
           ((uint64_t)p[off + 2] << 40)  | ((uint64_t)p[off + 3] << 32) |
           (p[off + 4] << 24) | (p[off + 5] << 16) |
           (p[off + 6] << 8)  | (p[off + 7] << 0);
 }
dtoverlay_read_u8()
uint8_t dtoverlay_read_u8 (const void * src, int off)
Definition at line 82 of file dtoverlay.c.
 {
    const unsigned char *p = src;
    return (p[off + 0] << 0);
 }
dtoverlay_save_dtb()
int dtoverlay_save_dtb (const DTBLOB_T * dtb, const char * filename)
Definition at line 2129 of file dtoverlay.c.
References dtoverlay_debug(), dtoverlay_error(), dtblob_struct::fdt, fdt_totalsize, dynstring::len, dtblob_struct::trailer, and dtblob_struct::trailer_len.
 {
    FILE *fp = fopen(filename, "wb");
    int err = 0;
    if (fp)
    {
       long len = fdt_totalsize(dtb->fdt);
       if (len != fwrite(dtb->fdt, 1, len, fp))
       {
          dtoverlay_error("fwrite failed");
          err = -2;
          goto error_exit;
       }
       if (dtb->trailer_len &&
           (fwrite(dtb->trailer, 1, dtb->trailer_len, fp) != dtb->trailer_len))
       {
          dtoverlay_error("fwrite failed");
          err = -2;
          goto error_exit;
       }
       dtoverlay_debug("Wrote %ld bytes to '%s'", len, filename);
       fclose(fp);
    }
    else
    {
       dtoverlay_debug("Failed to create '%s'", filename);
       err = -1;
    }
 error_exit:
    return err;
 }
dtoverlay_set_alias()
int dtoverlay_set_alias (DTBLOB_T * dtb, const char * alias_name, const char * value)
Definition at line 2329 of file dtoverlay.c.
References dtblob_struct::fdt, fdt_add_subnode(), fdt_path_offset(), and fdt_setprop_string.
 {
    int node_off;
    node_off = fdt_path_offset(dtb->fdt, "/aliases");
    if (node_off < 0)
        node_off = fdt_add_subnode(dtb->fdt, 0, "aliases");
    return fdt_setprop_string(dtb->fdt, node_off, alias_name, value);
 }
dtoverlay_set_logging_func()
void dtoverlay_set_logging_func (DTOVERLAY_LOGGING_FUNC * func)
Definition at line 2340 of file dtoverlay.c.
 {
     dtoverlay_logging_func = func;
 }
dtoverlay_set_node_properties()
int dtoverlay_set_node_properties (DTBLOB_T * dtb, const char * node_path, DTOVERLAY_PARAM_T * properties, unsigned int num_properties)
Definition at line 220 of file dtoverlay.c.
References dtoverlay_struct::b, dtoverlay_create_node(), dtblob_struct::fdt, fdt_path_offset(), fdt_setprop(), dtoverlay_struct::len, and dtoverlay_struct::param.
 {
    int err = 0;
    int node_off;
    node_off = fdt_path_offset(dtb->fdt, node_path);
    if (node_off < 0)
       node_off = dtoverlay_create_node(dtb, node_path, 0);
    if (node_off >= 0)
    {
       int i;
       for (i = 0; (i < num_properties) && (err == 0); i++)
       {
          DTOVERLAY_PARAM_T *p;
          p = properties + i;
          err = fdt_setprop(dtb->fdt, node_off, p->param, p->b, p->len);
       }
    }
    else
       err = node_off;
    return err;
 }
dtoverlay_set_property()
int dtoverlay_set_property (DTBLOB_T * dtb, int pos, const char * prop_name, const void * prop, int prop_len)
Definition at line 2306 of file dtoverlay.c.
References dtoverlay_error(), dtblob_struct::fdt, and fdt_setprop().
 {
    int err = fdt_setprop(dtb->fdt, pos, prop_name, prop, prop_len);
    if (err < 0)
       dtoverlay_error("Failed to set property '%s'", prop_name);
    return err;
 }
dtoverlay_set_synonym()
int dtoverlay_set_synonym (DTBLOB_T * dtb, const char * dst, const char * src)
Definition at line 1839 of file dtoverlay.c.
References dtoverlay_dup_property().
 {
    /* Add/update all aliases, symbols and overrides named dst
       to be equivalent to those named src.
       An absent src is ignored.
    */
    int err;
    err = dtoverlay_dup_property(dtb, "/aliases", dst, src);
    if (err == 0)
       err = dtoverlay_dup_property(dtb, "/__symbols__", dst, src);
    if (err == 0)
       dtoverlay_dup_property(dtb, "/__overrides__", dst, src);
    return err;
 }
dtoverlay_write_u16()
void dtoverlay_write_u16 (void * dst, int off, uint32_t val)
Definition at line 116 of file dtoverlay.c.
 {
    unsigned char *p = dst;
    p[off + 0] = (val >> 8) & 0xff;
    p[off + 1] = (val >> 0) & 0xff;
 }
dtoverlay_write_u32()
void dtoverlay_write_u32 (void * dst, int off, uint32_t val)
Definition at line 123 of file dtoverlay.c.
 {
    unsigned char *p = dst;
    p[off + 0] = (val >> 24) & 0xff;
    p[off + 1] = (val >> 16) & 0xff;
    p[off + 2] = (val >> 8) & 0xff;
    p[off + 3] = (val >> 0) & 0xff;
 }
dtoverlay_write_u64()
void dtoverlay_write_u64 (void * dst, int off, uint64_t val)
Definition at line 132 of file dtoverlay.c.
 {
    unsigned char *p = dst;
    p[off + 0] = (val >> 56) & 0xff;
    p[off + 1] = (val >> 48) & 0xff;
    p[off + 2] = (val >> 40) & 0xff;
    p[off + 3] = (val >> 32) & 0xff;
    p[off + 4] = (val >> 24) & 0xff;
    p[off + 5] = (val >> 16) & 0xff;
    p[off + 6] = (val >> 8) & 0xff;
    p[off + 7] = (val >> 0) & 0xff;
 }
dtoverlay_write_u8()
void dtoverlay_write_u8 (void * dst, int off, uint32_t val)
Definition at line 110 of file dtoverlay.c.
 {
    unsigned char *p = dst;
    p[off] = (val >> 0) & 0xff;
 }