VideoCore Library: Container Filter API
Container Filter API
Classes
struct VC_CONTAINER_FILTER_T
Typedefs
typedef struct VC_CONTAINER_FILTER_T VC_CONTAINER_FILTER_T
Functions
VC_CONTAINER_FILTER_T * vc_container_filter_open (VC_CONTAINER_FOURCC_T filter, VC_CONTAINER_FOURCC_T type, VC_CONTAINER_T *container, VC_CONTAINER_STATUS_T *status)
VC_CONTAINER_STATUS_T vc_container_filter_close (VC_CONTAINER_FILTER_T *context)
VC_CONTAINER_STATUS_T vc_container_filter_process (VC_CONTAINER_FILTER_T *context, VC_CONTAINER_PACKET_T *p_packet)
VC_CONTAINER_STATUS_T vc_container_filter_control (VC_CONTAINER_FILTER_T *context, VC_CONTAINER_CONTROL_T operation,...)
Detailed Description
Typedef Documentation
VC_CONTAINER_FILTER_T
typedef struct VC_CONTAINER_FILTER_T VC_CONTAINER_FILTER_T
Container Filter Context. This structure defines the context for a container filter instance
Function Documentation
vc_container_filter_close()
VC_CONTAINER_STATUS_T vc_container_filter_close (VC_CONTAINER_FILTER_T * context)
Closes an instance of a container filter.
Parameters
context Pointer to the VC_CONTAINER_FILTER_T context of the instance to close
Returns
VC_CONTAINER_SUCCESS on success.
Definition at line 130 of file containers_filters.c.
References VC_CONTAINER_FILTER_PRIVATE_T::handle, and VC_CONTAINER_FILTER_T::priv.
Referenced by vc_container_close().
 {
    if (p_ctx)
    {
       if(p_ctx->pf_close) p_ctx->pf_close(p_ctx);
       if(p_ctx->priv && p_ctx->priv->handle) vc_container_filter_unload(p_ctx);
       free(p_ctx);
    }
    return VC_CONTAINER_SUCCESS;
 }
vc_container_filter_control()
VC_CONTAINER_STATUS_T vc_container_filter_control (VC_CONTAINER_FILTER_T * context, VC_CONTAINER_CONTROL_T operation, ...)
Extensible control function for container filter modules. This function takes a variable number of arguments which will depend on the specific operation.
Parameters
context Pointer to the VC_CONTAINER_FILTER_T instance to use
operation The requested operation
args Arguments for the operation
Returns
the status of the operation
Definition at line 149 of file containers_filters.c.
References status, and VC_CONTAINER_ERROR_UNSUPPORTED_OPERATION.
 {
    VC_CONTAINER_STATUS_T status = VC_CONTAINER_ERROR_UNSUPPORTED_OPERATION;
    va_list args;
    va_start( args, operation );
    if(p_ctx->pf_control)
       status = p_ctx->pf_control(p_ctx, operation, args);
    va_end( args );
    return status;
 }
vc_container_filter_open()
VC_CONTAINER_FILTER_T* vc_container_filter_open (VC_CONTAINER_FOURCC_T filter, VC_CONTAINER_FOURCC_T type, VC_CONTAINER_T * container, VC_CONTAINER_STATUS_T * status)
Opens a container filter using a four character code describing the filter. This will create an instance of the container filter.
Parameters
filter Four Character Code describing the filter
type Four Character Code describing the subtype - indicated whether filter is encrypt or decrypt
container Pointer to the container instance
status Returns the status of the operation
Returns
If successful, this returns a pointer to the new instance of the container filter. Returns NULL on failure.
Definition at line 100 of file containers_filters.c.
References VC_CONTAINER_FILTER_T::container, error(), VC_CONTAINER_FILTER_T::priv, status, VC_CONTAINER_ERROR_NOT_FOUND, and VC_CONTAINER_ERROR_OUT_OF_MEMORY.
Referenced by vc_container_open_reader_with_io().
 {
    VC_CONTAINER_STATUS_T status = VC_CONTAINER_ERROR_NOT_FOUND;
    VC_CONTAINER_FILTER_T *p_ctx = 0;
    VC_CONTAINER_FILTER_PRIVATE_T *priv = 0;
    /* Allocate our context before trying out the different filter modules */
    p_ctx = malloc(sizeof(*p_ctx) + sizeof(*priv));
    if(!p_ctx) { status = VC_CONTAINER_ERROR_OUT_OF_MEMORY; goto error; }
    memset(p_ctx, 0, sizeof(*p_ctx) + sizeof(*priv));
    p_ctx->priv = priv = (VC_CONTAINER_FILTER_PRIVATE_T *)&p_ctx[1];
    p_ctx->container = p_container;
    status = vc_container_filter_load(p_ctx, filter, type);
    if(status != VC_CONTAINER_SUCCESS) goto error;
  end:
    if(p_status) *p_status = status;
    return p_ctx;
  error:
    if(p_ctx) free(p_ctx);
    p_ctx = 0;
    goto end;
 }
vc_container_filter_process()
VC_CONTAINER_STATUS_T vc_container_filter_process (VC_CONTAINER_FILTER_T * context, VC_CONTAINER_PACKET_T * p_packet)
Filter a data packet using a container filter module.
Parameters
context Pointer to the VC_CONTAINER_FILTER_T instance to use
packet Pointer to the VC_CONTAINER_PACKET_T structure to process
Returns
the status of the operation
Definition at line 142 of file containers_filters.c.
References status.
Referenced by vc_container_write().
 {
    VC_CONTAINER_STATUS_T status;
    status = p_ctx->pf_process(p_ctx, p_packet);
    return status;
 }