VideoCore Library: interface/vcos/generic/vcos_cmd.c File Reference
vcos_cmd.c File Reference
#include "interface/vcos/vcos.h"
Classes
struct VCOS_CMD_GLOBALS_T
Macros
#define VCOS_LOG_CATEGORY (&vcos_cmd_log_category)
Functions
void vcos_cmd_always_log_output (VCOS_LOG_CAT_T *log_category)
void vcos_cmd_vprintf (VCOS_CMD_PARAM_T *param, const char *fmt, va_list args)
void vcos_cmd_printf (VCOS_CMD_PARAM_T *param, const char *fmt,...)
void vcos_cmd_error (VCOS_CMD_PARAM_T *param, const char *fmt,...)
void vcos_cmd_usage (VCOS_CMD_PARAM_T *param)
void vcos_cmd_shutdown (void)
VCOS_STATUS_T vcos_cmd_execute (int argc, char **argv, size_t result_size, char *result_buf)
VCOS_STATUS_T vcos_cmd_register (VCOS_CMD_T *cmd_entry)
VCOS_STATUS_T vcos_cmd_register_multiple (VCOS_CMD_T *cmd_entry)
Variables
VCOS_LOG_CAT_T vcos_cmd_log_category
Macro Definition Documentation
VCOS_LOG_CATEGORY
#define VCOS_LOG_CATEGORY (&vcos_cmd_log_category)
Definition at line 51 of file vcos_cmd.c.
Function Documentation
vcos_cmd_always_log_output()
void vcos_cmd_always_log_output (VCOS_LOG_CAT_T * log_category)
Definition at line 111 of file vcos_cmd.c.
 {
     cmd_globals.log_category = log_category;
 }
vcos_cmd_error()
void vcos_cmd_error (VCOS_CMD_PARAM_T * param, const char * fmt, ...)
Definition at line 250 of file vcos_cmd.c.
 {
     va_list args;
     print_argument_prefix( param );
     va_start( args, fmt );
     vcos_cmd_vprintf( param, fmt, args );
     va_end( args );
     vcos_cmd_printf( param, "\n" );
 }
vcos_cmd_execute()
VCOS_STATUS_T vcos_cmd_execute (int argc, char ** argv, size_t result_size, char * result_buf)
Definition at line 548 of file vcos_cmd.c.
References VCOS_EINVAL, and vcos_once().
 {
     VCOS_STATUS_T       rc = VCOS_EINVAL;
     VCOS_CMD_PARAM_T    param;
     vcos_once( &cmd_globals.initialized, vcos_cmd_init );
     param.argc = argc;
     param.argv = param.argv_orig = argv;
     param.use_log = 0;
     param.result_size = result_size;
     param.result_ptr = result_buf;
     param.result_buf = result_buf;
     result_buf[0] = '\0';
     vcos_mutex_lock( &cmd_globals.lock );
     rc = execute_cmd( &param, cmd_globals.cmd_entry );
     if ( param.use_log )
     {
         cmd_log_results( &param );
         vcos_snprintf( result_buf, result_size, "results logged" );
     }
     else
     if ( cmd_globals.log_category != NULL )
     {
         if ( result_buf[0] != '\0' )
         {
             /* There is a partial line still buffered. */
             vcos_cmd_printf( &param, "\n" );
         }
     }
     vcos_mutex_unlock( &cmd_globals.lock );
     return rc;
 }
vcos_cmd_printf()
void vcos_cmd_printf (VCOS_CMD_PARAM_T * param, const char * fmt, ...)
Definition at line 218 of file vcos_cmd.c.
References vcos_cmd_vprintf().
 {
     va_list args;
     va_start( args, fmt );
     vcos_cmd_vprintf( param, fmt, args );
     va_end( args );
 }
vcos_cmd_register()
VCOS_STATUS_T vcos_cmd_register (VCOS_CMD_T * cmd_entry)
Definition at line 596 of file vcos_cmd.c.
References vcos_once().
Referenced by vcos_cmd_register_multiple().
 {
     VCOS_STATUS_T   rc;
     VCOS_UNSIGNED   new_num_cmd_alloc;
     VCOS_CMD_T     *new_cmd_entry;
     VCOS_CMD_T     *old_cmd_entry;
     VCOS_CMD_T     *scan_entry;
     vcos_once( &cmd_globals.initialized, vcos_cmd_init );
     vcos_assert( cmd_entry != NULL );
     vcos_assert( cmd_entry->name != NULL );
     vcos_log_trace( "%s: cmd '%s'", __FUNCTION__, cmd_entry->name );
     vcos_assert( cmd_entry->args != NULL );
     vcos_assert(( cmd_entry->cmd_fn != NULL ) || ( cmd_entry->sub_cmd_entry != NULL ));
     vcos_assert( cmd_entry->descr != NULL );
     /* We expect vcos_cmd_init to be called before vcos_logging_init, so we
      * need to defer registering our logging category until someplace
      * like right here.
      */
     if ( vcos_cmd_log_category.name == NULL )
     {
         /*
          * If you're using the command interface, you pretty much always want
          * log messages from this file to show up. So we change the default
          * from ERROR to be the more reasonable INFO level.
          */
         vcos_log_set_level(&vcos_cmd_log_category, VCOS_LOG_INFO);
         vcos_log_register("vcos_cmd", &vcos_cmd_log_category);
         /* We register a help command so that it shows up in the usage. */
         vcos_cmd_register( &cmd_help );
 #ifdef HAVE_VCOS_VERSION
         vcos_cmd_register( &cmd_version );
 #endif
     }
     vcos_mutex_lock( &cmd_globals.lock );
     if ( cmd_globals.num_cmd_entries >= cmd_globals.num_cmd_alloc )
     {
         if ( cmd_globals.num_cmd_alloc == 0 )
         {
             /* We haven't allocated a table yet */
         }
         /* The number 8 is rather arbitrary. */
         new_num_cmd_alloc = cmd_globals.num_cmd_alloc + 8;
         /* The + 1 is to ensure that we always have a NULL entry at the end. */
         new_cmd_entry = (VCOS_CMD_T *)vcos_calloc( new_num_cmd_alloc + 1, sizeof( *cmd_entry ), "vcos_cmd_entries" );
         if ( new_cmd_entry == NULL )
         {
             rc = VCOS_ENOMEM;
             goto out;
         }
         memcpy( new_cmd_entry, cmd_globals.cmd_entry, cmd_globals.num_cmd_entries * sizeof( *cmd_entry ));
         cmd_globals.num_cmd_alloc = new_num_cmd_alloc;
         old_cmd_entry = cmd_globals.cmd_entry;
         cmd_globals.cmd_entry = new_cmd_entry;
         vcos_free( old_cmd_entry );
     }
     if ( cmd_globals.num_cmd_entries == 0 )
     {
         /* This is the first command being registered */
         cmd_globals.cmd_entry[0] = *cmd_entry;
     }
     else
     {
         /* Keep the list in alphabetical order. We start at the end and work backwards
          * shuffling entries up one until we find an insertion point.
          */
         for ( scan_entry = &cmd_globals.cmd_entry[cmd_globals.num_cmd_entries - 1];
               scan_entry >= cmd_globals.cmd_entry; scan_entry-- )
         {
             if ( vcos_strcmp( cmd_entry->name, scan_entry->name ) > 0 )
             {
                 /* We found an insertion point. */
                 break;
             }
             scan_entry[1] = scan_entry[0];
         }
         scan_entry[1] = *cmd_entry;
     }
     cmd_globals.num_cmd_entries++;
     rc = VCOS_SUCCESS;
 out:
     vcos_mutex_unlock( &cmd_globals.lock );
     return rc;
 }
vcos_cmd_register_multiple()
VCOS_STATUS_T vcos_cmd_register_multiple (VCOS_CMD_T * cmd_entry)
Definition at line 709 of file vcos_cmd.c.
References VCOS_CMD_S::name, NULL, status, vcos_cmd_register(), and VCOS_SUCCESS.
 {
     VCOS_STATUS_T   status;
     while ( cmd_entry->name != NULL )
     {
         if (( status = vcos_cmd_register( cmd_entry )) != VCOS_SUCCESS )
         {
             return status;
         }
         cmd_entry++;
     }
     return VCOS_SUCCESS;
 }
vcos_cmd_shutdown()
void vcos_cmd_shutdown (void)
Definition at line 534 of file vcos_cmd.c.
References vcos_mutex_delete().
 {
     vcos_mutex_delete( &cmd_globals.lock );
     vcos_free( cmd_globals.cmd_entry );
     cmd_globals.cmd_entry = NULL;
 }
vcos_cmd_usage()
void vcos_cmd_usage (VCOS_CMD_PARAM_T * param)
Definition at line 318 of file vcos_cmd.c.
References VCOS_CMD_PARAM_T::cmd_entry, NULL, and VCOS_CMD_S::sub_cmd_entry.
 {
     VCOS_CMD_T *cmd_entry;
     cmd_entry = param->cmd_entry;
     if ( cmd_entry->sub_cmd_entry != NULL )
     {
         /* This command is command with sub-commands */
         usage( param, param->cmd_entry->sub_cmd_entry );
     }
     else
     {
         vcos_cmd_printf( param, "Usage: " );
         print_argument_prefix( param );
         vcos_cmd_printf( param, "%s %s - %s\n",
                          param->argv[0],
                          param->cmd_entry->args,
                          param->cmd_entry->descr );
     }
 }
vcos_cmd_vprintf()
void vcos_cmd_vprintf (VCOS_CMD_PARAM_T * param, const char * fmt, va_list args)
Definition at line 169 of file vcos_cmd.c.
References VCOS_CMD_PARAM_T::result_buf, VCOS_CMD_PARAM_T::result_ptr, VCOS_CMD_PARAM_T::result_size, and vcos_vsnprintf().
Referenced by vcos_cmd_printf().
 {
     int     bytes_written;
     int     bytes_remaining;
     bytes_remaining = (int)(param->result_size - ( param->result_ptr - param->result_buf ));
     bytes_written = vcos_vsnprintf( param->result_ptr, bytes_remaining, fmt, args );
     if ( cmd_globals.log_category != NULL )
     {
         /* We're going to log each line as we encounter it. If the buffer
          * doesn't end in a newline, then we'll wait for one first.
          */
         if ( (( bytes_written + 1 ) >= bytes_remaining )
         ||   ( param->result_ptr[ bytes_written - 1 ] == '\n' ))
         {
             cmd_log_results( param );
         }
         else
         {
             param->result_ptr += bytes_written;
         }
     }
     else
     {
         if (( bytes_written + 1 ) >= bytes_remaining )
         {
             /* Output doesn't fit - switch over to logging */
             param->use_log = 1;
             *param->result_ptr = '\0';  /* Zap the partial line that didn't fit above. */
             cmd_log_results( param );   /* resets result_ptr */
             bytes_written = vcos_vsnprintf( param->result_ptr, bytes_remaining, fmt, args );
         }
         param->result_ptr += bytes_written;
     }
 }
Variable Documentation
vcos_cmd_log_category
VCOS_LOG_CAT_T vcos_cmd_log_category
Definition at line 52 of file vcos_cmd.c.