#!/bin/sh

# Mount /dev/mmcblk0p2 for writable /etc
if [ -b /dev/mmcblk0 ];then
    if [ -b /dev/mmcblk0p2 ];then
        mkdir -p /tmp/etc
        mount /dev/mmcblk0p2 /tmp/etc
        cp -aru /etc/* /tmp/etc
        mount --bind /tmp/etc/ /etc
    fi
fi

# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done

if [ -f /etc/rc.local ];then
    /etc/rc.local
fi
