VideoCore Library: host_applications/linux/apps/raspicam/RaspiTexStub.c File Reference
RaspiTexStub.c File Reference
#include "RaspiTex.h"
#include "RaspiCLI.h"
#include "interface/vcos/vcos.h"
#include "interface/mmal/mmal_buffer.h"
#include "interface/mmal/util/mmal_util.h"
#include "interface/mmal/util/mmal_util_params.h"
Macros
#define DEFAULT_WIDTH 640
#define DEFAULT_HEIGHT 480
Enumerations
enum { CommandGLScene, CommandGLWin }
Functions
int raspitex_parse_cmdline (RASPITEX_STATE *state, const char *arg1, const char *arg2)
void raspitex_display_help ()
int raspitex_configure_preview_port (RASPITEX_STATE *state, MMAL_PORT_T *preview_port)
int raspitex_init (RASPITEX_STATE *state)
void raspitex_destroy (RASPITEX_STATE *state)
void raspitex_set_defaults (RASPITEX_STATE *state)
void raspitex_stop (RASPITEX_STATE *state)
int raspitex_start (RASPITEX_STATE *state)
int raspitex_capture (RASPITEX_STATE *state, FILE *output_file)
Macro Definition Documentation
DEFAULT_HEIGHT
#define DEFAULT_HEIGHT 480
Definition at line 76 of file RaspiTexStub.c.
DEFAULT_WIDTH
#define DEFAULT_WIDTH 640
Definition at line 75 of file RaspiTexStub.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
CommandGLScene
CommandGLWin
Definition at line 78 of file RaspiTexStub.c.
 {
    CommandGLScene,
    CommandGLWin
 };
Function Documentation
raspitex_capture()
int raspitex_capture (RASPITEX_STATE * state, FILE * output_file)
Writes the next GL frame-buffer to a RAW .ppm formatted file using the specified file-handle.
Parameters
state Pointer to the GL preview state.
outpt_file Output file handle for the ppm image.
Returns
Zero on success.
Definition at line 237 of file RaspiTexStub.c.
References RASPITEX_CAPTURE::buffer, RASPITEX_STATE::capture, RASPITEX_CAPTURE::completed_sem, RASPITEX_STATE::height, NULL, raspitexutil_brga_to_rgba(), RASPITEX_CAPTURE::request, RASPITEX_CAPTURE::size, RASPITEX_CAPTURE::start_sem, VCOS_FUNCTION, vcos_semaphore_post(), vcos_semaphore_wait(), RASPITEX_STATE::width, and write_tga().
 {
    return -1;
 }
raspitex_configure_preview_port()
int raspitex_configure_preview_port (RASPITEX_STATE * state, MMAL_PORT_T * preview_port)
Definition at line 179 of file RaspiTexStub.c.
References MMAL_PORT_T::buffer_num, MMAL_PORT_T::buffer_num_recommended, MMAL_PORT_T::buffer_size, MMAL_PORT_T::buffer_size_recommended, MMAL_ENOMEM, MMAL_PARAMETER_ZERO_COPY, mmal_port_enable(), mmal_port_format_commit(), mmal_port_parameter_set_boolean(), mmal_port_pool_create(), mmal_queue_create(), MMAL_SUCCESS, MMAL_TRUE, RASPITEX_STATE::preview_pool, RASPITEX_STATE::preview_port, RASPITEX_STATE::preview_queue, status, MMAL_PORT_T::userdata, and VCOS_FUNCTION.
 {
    return -1;
 }
raspitex_destroy()
void raspitex_destroy (RASPITEX_STATE * state)
Definition at line 197 of file RaspiTexStub.c.
References RASPITEX_STATE::capture, RASPITEX_SCENE_OPS::close, RASPITEX_CAPTURE::completed_sem, RASPITEX_SCENE_OPS::destroy_native_window, mmal_pool_destroy(), mmal_queue_destroy(), NULL, RASPITEX_STATE::ops, RASPITEX_STATE::preview_pool, RASPITEX_STATE::preview_queue, RASPITEX_CAPTURE::start_sem, VCOS_FUNCTION, and vcos_semaphore_delete().
 {
 }
raspitex_display_help()
void raspitex_display_help ()
Display help for command line options
Definition at line 163 of file RaspiTexStub.c.
References raspicli_display_help().
 {
    fprintf(stdout, "\nGL parameter commands\n\n");
    raspicli_display_help(cmdline_commands, cmdline_commands_size);
 }
raspitex_init()
int raspitex_init (RASPITEX_STATE * state)
Definition at line 189 of file RaspiTexStub.c.
References RASPITEX_STATE::capture, RASPITEX_CAPTURE::completed_sem, error(), mirror_open(), RASPITEX_SCENE_MIRROR, RASPITEX_SCENE_SOBEL, RASPITEX_SCENE_SQUARE, RASPITEX_SCENE_TEAPOT, RASPITEX_SCENE_VCSM_SQUARE, RASPITEX_SCENE_YUV, RASPITEX_STATE::scene_id, sobel_open(), square_open(), RASPITEX_CAPTURE::start_sem, status, teapot_open(), VCOS_FUNCTION, vcos_init(), VCOS_LOG_CATEGORY, VCOS_LOG_INFO, vcos_log_register(), vcos_log_set_level(), VCOS_LOG_WARN, vcos_semaphore_create(), VCOS_SUCCESS, vcsm_square_open(), RASPITEX_STATE::verbose, and yuv_open().
 {
    return -1;
 }
raspitex_parse_cmdline()
int raspitex_parse_cmdline (RASPITEX_STATE * state, const char * arg1, const char * arg2)
Parse a possible command pair - command and parameter
Parameters
arg1 Command
arg2 Parameter (could be NULL)
Returns
How many parameters were used, 0,1,2
Definition at line 98 of file RaspiTexStub.c.
 {
    int command_id, used = 0, num_parameters;
    if (!arg1)
       return 0;
    command_id = raspicli_get_command_id(cmdline_commands,
                                         cmdline_commands_size, arg1, &num_parameters);
    // If invalid command, or we are missing a parameter, drop out
    if (command_id==-1 || (command_id != -1 && num_parameters > 0 && arg2 == NULL))
       return 0;
    switch (command_id)
    {
    case CommandGLWin: // Allows a GL window to be different to preview-res
    {
       int tmp;
       tmp = sscanf(arg2, "%d,%d,%d,%d",
                    &state->x, &state->y, &state->width, &state->height);
       if (tmp != 4)
       {
          // Default to safe size on parse error
          state->x = state->y = 0;
          state->width = DEFAULT_WIDTH;
          state->height = DEFAULT_HEIGHT;
       }
       else
       {
          state->gl_win_defined = 1;
       }
       used = 2;
       break;
    }
    case CommandGLScene: // Selects the GL scene
    {
       if (strcmp(arg2, "square") == 0)
          state->scene_id = RASPITEX_SCENE_SQUARE;
       else if (strcmp(arg2, "teapot") == 0)
          state->scene_id = RASPITEX_SCENE_TEAPOT;
       else if (strcmp(arg2, "mirror") == 0)
          state->scene_id = RASPITEX_SCENE_MIRROR;
       else if (strcmp(arg2, "yuv") == 0)
          state->scene_id = RASPITEX_SCENE_YUV;
       else if (strcmp(arg2, "sobel") == 0)
          state->scene_id = RASPITEX_SCENE_SOBEL;
       else if (strcmp(arg2, "vcsm_square") == 0)
          state->scene_id = RASPITEX_SCENE_VCSM_SQUARE;
       else
          fprintf(stderr, "Unknown scene %s", arg2);
       used = 2;
       break;
    }
    }
    return used;
 }
raspitex_set_defaults()
void raspitex_set_defaults (RASPITEX_STATE * state)
Definition at line 207 of file RaspiTexStub.c.
References RASPITEX_SCENE_OPS::capture, RASPITEX_SCENE_OPS::close, RASPITEX_STATE::context, RASPITEX_SCENE_OPS::create_native_window, DEFAULT_HEIGHT, DEFAULT_WIDTH, RASPITEX_SCENE_OPS::destroy_native_window, RASPITEX_STATE::display, RASPITEX_STATE::egl_image, EGL_NO_CONTEXT, EGL_NO_DISPLAY, EGL_NO_IMAGE_KHR, EGL_NO_SURFACE, RASPITEX_SCENE_OPS::gl_init, RASPITEX_SCENE_OPS::gl_term, RASPITEX_STATE::height, RASPITEX_STATE::opacity, RASPITEX_STATE::ops, RASPITEX_SCENE_SQUARE, RASPITEX_VERSION_MAJOR, RASPITEX_VERSION_MINOR, raspitexutil_capture_bgra(), raspitexutil_close(), raspitexutil_create_native_window(), raspitexutil_destroy_native_window(), raspitexutil_gl_init_1_0(), raspitexutil_gl_term(), raspitexutil_redraw(), raspitexutil_update_model(), RASPITEX_SCENE_OPS::redraw, RASPITEX_STATE::scene_id, RASPITEX_STATE::surface, RASPITEX_STATE::u_egl_image, RASPITEX_SCENE_OPS::update_model, RASPITEX_STATE::v_egl_image, RASPITEX_STATE::version_major, RASPITEX_STATE::version_minor, RASPITEX_STATE::width, and RASPITEX_STATE::y_egl_image.
 {
 }
raspitex_start()
int raspitex_start (RASPITEX_STATE * state)
Starts the worker / GL renderer thread.
Precondition
raspitex_init was successful
raspitex_configure_preview_port was successful
Parameters
state Pointer to the GL preview state.
Returns
Zero on success, otherwise, -1 is returned
Definition at line 225 of file RaspiTexStub.c.
References NULL, RASPITEX_STATE::preview_thread, status, VCOS_FUNCTION, and vcos_thread_create().
 {
    return -1;
 }
raspitex_stop()
void raspitex_stop (RASPITEX_STATE * state)
Definition at line 214 of file RaspiTexStub.c.
References NULL, RASPITEX_STATE::preview_stop, RASPITEX_STATE::preview_thread, and vcos_thread_join().
 {
 }