VideoCore Library: interface/vmcs_host/vc_vchi_gpuserv.c File Reference
vc_vchi_gpuserv.c File Reference
#include <string.h>
#include <stdio.h>
#include <stdarg.h>
#include <ctype.h>
#include <assert.h>
#include "vchost.h"
#include "interface/vcos/vcos.h"
#include "interface/vcos/vcos_logging.h"
#include "vcinclude/common.h"
#include "vc_vchi_gpuserv.h"
#include "vchiq.h"
#include "interface/vcos/vcos_stdbool.h"
Classes
struct GPUSERV_SERVICE_T
Macros
#define VCOS_LOG_CATEGORY (&vcos_log_category)
#define GPUSERV_MAX_LENGTH 512
#define MAX_JOBS 8
Functions
int32_t vc_gpuserv_init (void)
void vc_gpuserv_deinit (void)
int32_t vc_gpuserv_execute_code (int num_jobs, struct gpu_job_s jobs[])
Macro Definition Documentation
GPUSERV_MAX_LENGTH
#define GPUSERV_MAX_LENGTH 512
Definition at line 53 of file vc_vchi_gpuserv.c.
MAX_JOBS
#define MAX_JOBS 8
Definition at line 227 of file vc_vchi_gpuserv.c.
Referenced by vc_gpuserv_execute_code().
VCOS_LOG_CATEGORY
#define VCOS_LOG_CATEGORY (&vcos_log_category)
Definition at line 45 of file vc_vchi_gpuserv.c.
Function Documentation
vc_gpuserv_deinit()
void vc_gpuserv_deinit (void)
Definition at line 165 of file vc_vchi_gpuserv.c.
References GPUSERV_SERVICE_T::lock, GPUSERV_SERVICE_T::refcount, GPUSERV_SERVICE_T::service, vchi_service_close(), vcos_mutex_lock(), and vcos_mutex_unlock().
 {
    vcos_mutex_lock(&gpuserv_client.lock);
    if (gpuserv_client.refcount > 0 && --gpuserv_client.refcount == 0)
    {
       vchi_service_close(gpuserv_client.service);
       gpuserv_client.service = 0;
    }
    vcos_mutex_unlock(&gpuserv_client.lock);
 }
vc_gpuserv_execute_code()
int32_t vc_gpuserv_execute_code (int num_jobs, struct gpu_job_s jobs[])
Definition at line 228 of file vc_vchi_gpuserv.c.
References VCHIQ_ELEMENT_T::data, MAX_JOBS, GPUSERV_SERVICE_T::service, VCHIQ_ELEMENT_T::size, vc_gpuserv_init(), vchiq_queue_message(), VCHIQ_SUCCESS, and VCOS_FUNCTION.
 {
    VCHIQ_ELEMENT_T elements[MAX_JOBS];
    int i;
    // hack: temporarily allow calling this function without calling vc_gpuserv_init
    // will be removed later
    if (!gpuserv_client.service)
    {
       vc_gpuserv_init();
       vcos_log_error("%s: called without calling vc_gpuserv_init", VCOS_FUNCTION);
    }
    if (!gpuserv_client.service)
    {
       vcos_log_error("%s: vchiq service not initialised", VCOS_FUNCTION);
       return -1;
    }
    if (num_jobs > MAX_JOBS)
       return -1;
    for (i=0; i<num_jobs; i++)
    {
       elements[i].data = jobs + i;
       elements[i].size = sizeof *jobs;
    }
    if (vchiq_queue_message(gpuserv_client.service, elements, num_jobs) != VCHIQ_SUCCESS)
    {
       goto error_exit;
    }
    return 0;
    error_exit:
    return -1;
 }
vc_gpuserv_init()
int32_t vc_gpuserv_init (void)
Definition at line 94 of file vc_vchi_gpuserv.c.
References vcos_once().
Referenced by vc_gpuserv_execute_code().
 {
    VCHIQ_SERVICE_PARAMS_T vchiq_params;
    VCHIQ_STATUS_T vchiq_status;
    vcos_once(&gpuserv_client_once, init_once);
    vcos_mutex_lock(&gpuserv_client.lock);
    if (gpuserv_client.refcount++ > 0)
    {
       /* Already initialised so nothing to do */
       vcos_mutex_unlock(&gpuserv_client.lock);
       return VCOS_SUCCESS;
    }
    vcos_log_set_level(VCOS_LOG_CATEGORY, VCOS_LOG_TRACE);
    vcos_log_register("gpuserv", VCOS_LOG_CATEGORY);
    vcos_log_trace("%s: starting initialisation", VCOS_FUNCTION);
    /* Initialise a VCHIQ instance */
    vchiq_status = vchiq_initialise(&gpuserv_client_vchiq_instance);
    if (vchiq_status != VCHIQ_SUCCESS)
    {
       vcos_log_error("%s: failed to initialise vchiq: %d", VCOS_FUNCTION, vchiq_status);
       goto error;
    }
    vchiq_status = vchiq_connect(gpuserv_client_vchiq_instance);
    if (vchiq_status != VCHIQ_SUCCESS)
    {
       vcos_log_error("%s: failed to connect to vchiq: %d", VCOS_FUNCTION, vchiq_status);
       goto error;
    }
    memset(&vchiq_params, 0, sizeof(vchiq_params));
    vchiq_params.fourcc = VCHIQ_MAKE_FOURCC('G','P','U','S');
    vchiq_params.callback = gpuserv_callback;
    vchiq_params.userdata = NULL;
    vchiq_params.version = 1;
    vchiq_params.version_min = 1;
    vchiq_status = vchiq_open_service(gpuserv_client_vchiq_instance, &vchiq_params, &gpuserv_client.service);
    if (vchiq_status != VCHIQ_SUCCESS)
    {
       vcos_log_error("%s: could not open vchiq service: %d", VCOS_FUNCTION, vchiq_status);
       goto error;
    }
    vcos_mutex_unlock(&gpuserv_client.lock);
    return 0;
 error:
    vcos_mutex_unlock(&gpuserv_client.lock);
    return -1;
 }