VideoCore Library: host_applications/linux/apps/hello_pi/hello_fft/mailbox.h File Reference
mailbox.h File Reference
#include <linux/ioctl.h>
Macros
#define MAJOR_NUM 100
#define IOCTL_MBOX_PROPERTY _IOWR(MAJOR_NUM, 0, char *)
#define DEVICE_FILE_NAME "/dev/vcio"
Functions
int mbox_open ()
void mbox_close (int file_desc)
unsigned get_version (int file_desc)
unsigned mem_alloc (int file_desc, unsigned size, unsigned align, unsigned flags)
unsigned mem_free (int file_desc, unsigned handle)
unsigned mem_lock (int file_desc, unsigned handle)
unsigned mem_unlock (int file_desc, unsigned handle)
void * mapmem (unsigned base, unsigned size)
void unmapmem (void *addr, unsigned size)
unsigned execute_code (int file_desc, unsigned code, unsigned r0, unsigned r1, unsigned r2, unsigned r3, unsigned r4, unsigned r5)
unsigned execute_qpu (int file_desc, unsigned num_qpus, unsigned control, unsigned noflush, unsigned timeout)
unsigned qpu_enable (int file_desc, unsigned enable)
Macro Definition Documentation
DEVICE_FILE_NAME
#define DEVICE_FILE_NAME "/dev/vcio"
Definition at line 32 of file mailbox.h.
Referenced by mbox_open().
IOCTL_MBOX_PROPERTY
#define IOCTL_MBOX_PROPERTY _IOWR(MAJOR_NUM, 0, char *)
Definition at line 31 of file mailbox.h.
MAJOR_NUM
#define MAJOR_NUM 100
Definition at line 30 of file mailbox.h.
Referenced by mbox_open().
Function Documentation
execute_code()
unsigned execute_code (int file_desc, unsigned code, unsigned r0, unsigned r1, unsigned r2, unsigned r3, unsigned r4, unsigned r5)
Definition at line 181 of file mailbox.c.
References code.
 {
    int i=0;
    unsigned p[32];
    p[i++] = 0; // size
    p[i++] = 0x00000000; // process request
    p[i++] = 0x30010; // (the tag id)
    p[i++] = 28; // (size of the buffer)
    p[i++] = 28; // (size of the data)
    p[i++] = code;
    p[i++] = r0;
    p[i++] = r1;
    p[i++] = r2;
    p[i++] = r3;
    p[i++] = r4;
    p[i++] = r5;
    p[i++] = 0x00000000; // end tag
    p[0] = i*sizeof *p; // actual size
    mbox_property(file_desc, p);
    return p[5];
 }
execute_qpu()
unsigned execute_qpu (int file_desc, unsigned num_qpus, unsigned control, unsigned noflush, unsigned timeout)
Definition at line 226 of file mailbox.c.
Referenced by gpu_fft_base_exec().
{
    int i=0;
    unsigned p[32];
    p[i++] = 0; // size
    p[i++] = 0x00000000; // process request
    p[i++] = 0x30011; // (the tag id)
    p[i++] = 16; // (size of the buffer)
    p[i++] = 16; // (size of the data)
    p[i++] = num_qpus;
    p[i++] = control;
    p[i++] = noflush;
    p[i++] = timeout; // ms
    p[i++] = 0x00000000; // end tag
    p[0] = i*sizeof *p; // actual size
    mbox_property(file_desc, p);
    return p[5];
 }
get_version()
unsigned get_version (int file_desc)
mapmem()
void* mapmem (unsigned base, unsigned size)
Definition at line 42 of file mailbox.c.
References mem, offset, and PAGE_SIZE.
Referenced by gpu_fft_alloc().
 {
    int mem_fd;
    unsigned offset = base % PAGE_SIZE;
    base = base - offset;
    size = size + offset;
    /* open /dev/mem */
    if ((mem_fd = open("/dev/mem", O_RDWR|O_SYNC) ) < 0) {
       printf("can't open /dev/mem\nThis program should be run as root. Try prefixing command with: sudo\n");
       exit (-1);
    }
    void *mem = mmap(
       0,
       size,
       PROT_READ|PROT_WRITE,
       MAP_SHARED/*|MAP_FIXED*/,
       mem_fd,
       base);
 #ifdef DEBUG
    printf("base=0x%x, mem=%p\n", base, mem);
 #endif
    if (mem == MAP_FAILED) {
       printf("mmap error %d\n", (int)mem);
       exit (-1);
    }
    close(mem_fd);
    return (char *)mem + offset;
 }
mbox_close()
void mbox_close (int file_desc)
Definition at line 260 of file mailbox.c.
{
   close(file_desc);
 }
mbox_open()
int mbox_open ()
Definition at line 247 of file mailbox.c.
References DEVICE_FILE_NAME, and MAJOR_NUM.
Referenced by main().
                 {
    int file_desc;
    // open a char device file used for communicating with kernel mbox driver
    file_desc = open(DEVICE_FILE_NAME, 0);
    if (file_desc < 0) {
       printf("Can't open device file: %s\n", DEVICE_FILE_NAME);
       printf("Try creating a device file with: sudo mknod %s c %d 0\n", DEVICE_FILE_NAME, MAJOR_NUM);
       exit(-1);
    }
    return file_desc;
 }
mem_alloc()
unsigned mem_alloc (int file_desc, unsigned size, unsigned align, unsigned flags)
Definition at line 103 of file mailbox.c.
 {
    int i=0;
    unsigned p[32];
    p[i++] = 0; // size
    p[i++] = 0x00000000; // process request
    p[i++] = 0x3000c; // (the tag id)
    p[i++] = 12; // (size of the buffer)
    p[i++] = 12; // (size of the data)
    p[i++] = size; // (num bytes? or pages?)
    p[i++] = align; // (alignment)
    p[i++] = flags; // (MEM_FLAG_L1_NONALLOCATING)
    p[i++] = 0x00000000; // end tag
    p[0] = i*sizeof *p; // actual size
    mbox_property(file_desc, p);
    return p[5];
 }
mem_free()
unsigned mem_free (int file_desc, unsigned handle)
Definition at line 124 of file mailbox.c.
Referenced by gpu_fft_alloc(), and gpu_fft_base_release().
 {
    int i=0;
    unsigned p[32];
    p[i++] = 0; // size
    p[i++] = 0x00000000; // process request
    p[i++] = 0x3000f; // (the tag id)
    p[i++] = 4; // (size of the buffer)
    p[i++] = 4; // (size of the data)
    p[i++] = handle;
    p[i++] = 0x00000000; // end tag
    p[0] = i*sizeof *p; // actual size
    mbox_property(file_desc, p);
    return p[5];
 }
mem_lock()
unsigned mem_lock (int file_desc, unsigned handle)
Definition at line 143 of file mailbox.c.
Referenced by delete(), gpu_fft_alloc(), insert(), iterate(), lookup(), mmal_buffer_header_mem_lock(), and term().
 {
    int i=0;
    unsigned p[32];
    p[i++] = 0; // size
    p[i++] = 0x00000000; // process request
    p[i++] = 0x3000d; // (the tag id)
    p[i++] = 4; // (size of the buffer)
    p[i++] = 4; // (size of the data)
    p[i++] = handle;
    p[i++] = 0x00000000; // end tag
    p[0] = i*sizeof *p; // actual size
    mbox_property(file_desc, p);
    return p[5];
 }
mem_unlock()
unsigned mem_unlock (int file_desc, unsigned handle)
Definition at line 162 of file mailbox.c.
Referenced by delete(), gpu_fft_base_release(), insert(), iterate(), lookup(), mmal_buffer_header_mem_unlock(), and term().
 {
    int i=0;
    unsigned p[32];
    p[i++] = 0; // size
    p[i++] = 0x00000000; // process request
    p[i++] = 0x3000e; // (the tag id)
    p[i++] = 4; // (size of the buffer)
    p[i++] = 4; // (size of the data)
    p[i++] = handle;
    p[i++] = 0x00000000; // end tag
    p[0] = i*sizeof *p; // actual size
    mbox_property(file_desc, p);
    return p[5];
 }
qpu_enable()
unsigned qpu_enable (int file_desc, unsigned enable)
Definition at line 206 of file mailbox.c.
Referenced by gpu_fft_alloc(), and gpu_fft_base_release().
 {
    int i=0;
    unsigned p[32];
    p[i++] = 0; // size
    p[i++] = 0x00000000; // process request
    p[i++] = 0x30012; // (the tag id)
    p[i++] = 4; // (size of the buffer)
    p[i++] = 4; // (size of the data)
    p[i++] = enable;
    p[i++] = 0x00000000; // end tag
    p[0] = i*sizeof *p; // actual size
    mbox_property(file_desc, p);
    return p[5];
 }
unmapmem()
void unmapmem (void * addr, unsigned size)
Definition at line 71 of file mailbox.c.
References offset, and PAGE_SIZE.
Referenced by gpu_fft_base_release().
 {
    const intptr_t offset = (intptr_t)addr % PAGE_SIZE;
    addr = (char *)addr - offset;
    size = size + offset;
    int s = munmap(addr, size);
    if (s != 0) {
       printf("munmap error %d\n", s);
       exit (-1);
    }
 }