VideoCore Library: interface/vchiq_arm/vchiq_if.h File Reference
vchiq_if.h File Reference
#include "interface/vchi/vchi_mh.h"
Classes
struct vchiq_header_struct
struct VCHIQ_ELEMENT_T
struct vchiq_service_base_struct
struct vchiq_service_params_struct
struct vchiq_config_struct
Macros
#define VCHIQ_SERVICE_HANDLE_INVALID 0
#define VCHIQ_SLOT_SIZE 4096
#define VCHIQ_MAX_MSG_SIZE (VCHIQ_SLOT_SIZE - sizeof(VCHIQ_HEADER_T))
#define VCHIQ_CHANNEL_SIZE VCHIQ_MAX_MSG_SIZE /* For backwards compatibility */
#define VCHIQ_MAKE_FOURCC(x0, x1, x2, x3) (((x0) << 24) | ((x1) << 16) | ((x2) << 8) | (x3))
#define VCHIQ_GET_SERVICE_USERDATA(service) vchiq_get_service_userdata(service)
#define VCHIQ_GET_SERVICE_FOURCC(service) vchiq_get_service_fourcc(service)
Typedefs
typedef struct vchiq_header_struct VCHIQ_HEADER_T
typedef unsigned int VCHIQ_SERVICE_HANDLE_T
typedef VCHIQ_STATUS_T(* VCHIQ_CALLBACK_T) (VCHIQ_REASON_T, VCHIQ_HEADER_T *, VCHIQ_SERVICE_HANDLE_T, void *)
typedef struct vchiq_service_base_struct VCHIQ_SERVICE_BASE_T
typedef struct vchiq_service_params_struct VCHIQ_SERVICE_PARAMS_T
typedef struct vchiq_config_struct VCHIQ_CONFIG_T
typedef struct vchiq_instance_struct * VCHIQ_INSTANCE_T
typedef void(* VCHIQ_REMOTE_USE_CALLBACK_T) (void *cb_arg)
Enumerations
enum VCHIQ_REASON_T {
VCHIQ_SERVICE_OPENED, VCHIQ_SERVICE_CLOSED, VCHIQ_MESSAGE_AVAILABLE, VCHIQ_BULK_TRANSMIT_DONE,
VCHIQ_BULK_RECEIVE_DONE, VCHIQ_BULK_TRANSMIT_ABORTED, VCHIQ_BULK_RECEIVE_ABORTED
}
enum VCHIQ_STATUS_T { VCHIQ_ERROR = -1, VCHIQ_SUCCESS = 0, VCHIQ_RETRY = 1 }
enum VCHIQ_BULK_MODE_T { VCHIQ_BULK_MODE_CALLBACK, VCHIQ_BULK_MODE_BLOCKING, VCHIQ_BULK_MODE_NOCALLBACK }
enum VCHIQ_SERVICE_OPTION_T {
VCHIQ_SERVICE_OPTION_AUTOCLOSE, VCHIQ_SERVICE_OPTION_SLOT_QUOTA, VCHIQ_SERVICE_OPTION_MESSAGE_QUOTA, VCHIQ_SERVICE_OPTION_SYNCHRONOUS,
VCHIQ_SERVICE_OPTION_TRACE
}
Functions
VCHIQ_STATUS_T vchiq_initialise (VCHIQ_INSTANCE_T *pinstance)
VCHIQ_STATUS_T vchiq_initialise_fd (VCHIQ_INSTANCE_T *pinstance, int dev_vchiq_fd)
VCHIQ_STATUS_T vchiq_shutdown (VCHIQ_INSTANCE_T instance)
VCHIQ_STATUS_T vchiq_connect (VCHIQ_INSTANCE_T instance)
VCHIQ_STATUS_T vchiq_add_service (VCHIQ_INSTANCE_T instance, const VCHIQ_SERVICE_PARAMS_T *params, VCHIQ_SERVICE_HANDLE_T *pservice)
VCHIQ_STATUS_T vchiq_open_service (VCHIQ_INSTANCE_T instance, const VCHIQ_SERVICE_PARAMS_T *params, VCHIQ_SERVICE_HANDLE_T *pservice)
VCHIQ_STATUS_T vchiq_close_service (VCHIQ_SERVICE_HANDLE_T service)
VCHIQ_STATUS_T vchiq_remove_service (VCHIQ_SERVICE_HANDLE_T service)
VCHIQ_STATUS_T vchiq_use_service (VCHIQ_SERVICE_HANDLE_T service)
VCHIQ_STATUS_T vchiq_release_service (VCHIQ_SERVICE_HANDLE_T service)
VCHIQ_STATUS_T vchiq_queue_message (VCHIQ_SERVICE_HANDLE_T service, const VCHIQ_ELEMENT_T *elements, int count)
void vchiq_release_message (VCHIQ_SERVICE_HANDLE_T service, VCHIQ_HEADER_T *header)
VCHIQ_STATUS_T vchiq_queue_bulk_transmit (VCHIQ_SERVICE_HANDLE_T service, const void *data, int size, void *userdata)
VCHIQ_STATUS_T vchiq_queue_bulk_receive (VCHIQ_SERVICE_HANDLE_T service, void *data, int size, void *userdata)
VCHIQ_STATUS_T vchiq_queue_bulk_transmit_handle (VCHIQ_SERVICE_HANDLE_T service, VCHI_MEM_HANDLE_T handle, const void *offset, int size, void *userdata)
VCHIQ_STATUS_T vchiq_queue_bulk_receive_handle (VCHIQ_SERVICE_HANDLE_T service, VCHI_MEM_HANDLE_T handle, void *offset, int size, void *userdata)
VCHIQ_STATUS_T vchiq_bulk_transmit (VCHIQ_SERVICE_HANDLE_T service, const void *data, int size, void *userdata, VCHIQ_BULK_MODE_T mode)
VCHIQ_STATUS_T vchiq_bulk_receive (VCHIQ_SERVICE_HANDLE_T service, void *data, int size, void *userdata, VCHIQ_BULK_MODE_T mode)
VCHIQ_STATUS_T vchiq_bulk_transmit_handle (VCHIQ_SERVICE_HANDLE_T service, VCHI_MEM_HANDLE_T handle, const void *offset, int size, void *userdata, VCHIQ_BULK_MODE_T mode)
VCHIQ_STATUS_T vchiq_bulk_receive_handle (VCHIQ_SERVICE_HANDLE_T service, VCHI_MEM_HANDLE_T handle, void *offset, int size, void *userdata, VCHIQ_BULK_MODE_T mode, int copy_pagelist(char *vcptr, const struct pagelist_struct *pagelist))
int vchiq_get_client_id (VCHIQ_SERVICE_HANDLE_T service)
void * vchiq_get_service_userdata (VCHIQ_SERVICE_HANDLE_T service)
int vchiq_get_service_fourcc (VCHIQ_SERVICE_HANDLE_T service)
VCHIQ_STATUS_T vchiq_get_config (VCHIQ_INSTANCE_T instance, int config_size, VCHIQ_CONFIG_T *pconfig)
VCHIQ_STATUS_T vchiq_set_service_option (VCHIQ_SERVICE_HANDLE_T service, VCHIQ_SERVICE_OPTION_T option, int value)
VCHIQ_STATUS_T vchiq_remote_use (VCHIQ_INSTANCE_T instance, VCHIQ_REMOTE_USE_CALLBACK_T callback, void *cb_arg)
VCHIQ_STATUS_T vchiq_remote_release (VCHIQ_INSTANCE_T instance)
VCHIQ_STATUS_T vchiq_dump_phys_mem (VCHIQ_SERVICE_HANDLE_T service, void *ptr, size_t num_bytes)
VCHIQ_STATUS_T vchiq_get_peer_version (VCHIQ_SERVICE_HANDLE_T handle, short *peer_version)
Macro Definition Documentation
VCHIQ_CHANNEL_SIZE
#define VCHIQ_CHANNEL_SIZE VCHIQ_MAX_MSG_SIZE /* For backwards compatibility */
Definition at line 41 of file vchiq_if.h.
VCHIQ_GET_SERVICE_FOURCC
#define VCHIQ_GET_SERVICE_FOURCC (service) vchiq_get_service_fourcc(service)
Definition at line 45 of file vchiq_if.h.
VCHIQ_GET_SERVICE_USERDATA
#define VCHIQ_GET_SERVICE_USERDATA (service) vchiq_get_service_userdata(service)
Definition at line 44 of file vchiq_if.h.
VCHIQ_MAKE_FOURCC
#define VCHIQ_MAKE_FOURCC (x0, x1, x2, x3) (((x0) << 24) | ((x1) << 16) | ((x2) << 8) | (x3))
Definition at line 43 of file vchiq_if.h.
VCHIQ_MAX_MSG_SIZE
#define VCHIQ_MAX_MSG_SIZE (VCHIQ_SLOT_SIZE - sizeof(VCHIQ_HEADER_T))
Definition at line 40 of file vchiq_if.h.
VCHIQ_SERVICE_HANDLE_INVALID
#define VCHIQ_SERVICE_HANDLE_INVALID 0
Definition at line 37 of file vchiq_if.h.
VCHIQ_SLOT_SIZE
#define VCHIQ_SLOT_SIZE 4096
Definition at line 39 of file vchiq_if.h.
Typedef Documentation
VCHIQ_CALLBACK_T
typedef VCHIQ_STATUS_T(* VCHIQ_CALLBACK_T) (VCHIQ_REASON_T, VCHIQ_HEADER_T *, VCHIQ_SERVICE_HANDLE_T, void *)
Definition at line 107 of file vchiq_if.h.
VCHIQ_CONFIG_T
typedef struct vchiq_config_struct VCHIQ_CONFIG_T
VCHIQ_HEADER_T
typedef struct vchiq_header_struct VCHIQ_HEADER_T
VCHIQ_INSTANCE_T
typedef struct vchiq_instance_struct* VCHIQ_INSTANCE_T
Definition at line 134 of file vchiq_if.h.
VCHIQ_REMOTE_USE_CALLBACK_T
typedef void(* VCHIQ_REMOTE_USE_CALLBACK_T) (void *cb_arg)
Definition at line 135 of file vchiq_if.h.
VCHIQ_SERVICE_BASE_T
typedef struct vchiq_service_base_struct VCHIQ_SERVICE_BASE_T
VCHIQ_SERVICE_HANDLE_T
typedef unsigned int VCHIQ_SERVICE_HANDLE_T
Definition at line 105 of file vchiq_if.h.
VCHIQ_SERVICE_PARAMS_T
typedef struct vchiq_service_params_struct VCHIQ_SERVICE_PARAMS_T
Enumeration Type Documentation
VCHIQ_BULK_MODE_T
enum VCHIQ_BULK_MODE_T
Enumerator
VCHIQ_BULK_MODE_CALLBACK
VCHIQ_BULK_MODE_BLOCKING
VCHIQ_BULK_MODE_NOCALLBACK
Definition at line 64 of file vchiq_if.h.
 {
    VCHIQ_BULK_MODE_CALLBACK,
    VCHIQ_BULK_MODE_BLOCKING,
    VCHIQ_BULK_MODE_NOCALLBACK
 } VCHIQ_BULK_MODE_T;
VCHIQ_REASON_T
enum VCHIQ_REASON_T
Enumerator
VCHIQ_SERVICE_OPENED
VCHIQ_SERVICE_CLOSED
VCHIQ_MESSAGE_AVAILABLE
VCHIQ_BULK_TRANSMIT_DONE
VCHIQ_BULK_RECEIVE_DONE
VCHIQ_BULK_TRANSMIT_ABORTED
VCHIQ_BULK_RECEIVE_ABORTED
Definition at line 47 of file vchiq_if.h.
              {
    VCHIQ_SERVICE_OPENED,         // service, -, -
    VCHIQ_SERVICE_CLOSED,         // service, -, -
    VCHIQ_MESSAGE_AVAILABLE,      // service, header, -
    VCHIQ_BULK_TRANSMIT_DONE,     // service, -, bulk_userdata
    VCHIQ_BULK_RECEIVE_DONE,      // service, -, bulk_userdata
    VCHIQ_BULK_TRANSMIT_ABORTED,  // service, -, bulk_userdata
    VCHIQ_BULK_RECEIVE_ABORTED    // service, -, bulk_userdata
 } VCHIQ_REASON_T;
VCHIQ_SERVICE_OPTION_T
enum VCHIQ_SERVICE_OPTION_T
Enumerator
VCHIQ_SERVICE_OPTION_AUTOCLOSE
VCHIQ_SERVICE_OPTION_SLOT_QUOTA
VCHIQ_SERVICE_OPTION_MESSAGE_QUOTA
VCHIQ_SERVICE_OPTION_SYNCHRONOUS
VCHIQ_SERVICE_OPTION_TRACE
Definition at line 71 of file vchiq_if.h.
 {
    VCHIQ_SERVICE_OPTION_AUTOCLOSE,
    VCHIQ_SERVICE_OPTION_SLOT_QUOTA,
    VCHIQ_SERVICE_OPTION_MESSAGE_QUOTA,
    VCHIQ_SERVICE_OPTION_SYNCHRONOUS,
    VCHIQ_SERVICE_OPTION_TRACE
 } VCHIQ_SERVICE_OPTION_T;
VCHIQ_STATUS_T
enum VCHIQ_STATUS_T
Enumerator
VCHIQ_ERROR
VCHIQ_SUCCESS
VCHIQ_RETRY
Definition at line 57 of file vchiq_if.h.
 {
    VCHIQ_ERROR   = -1,
    VCHIQ_SUCCESS = 0,
    VCHIQ_RETRY   = 1
 } VCHIQ_STATUS_T;
Function Documentation
vchiq_add_service()
VCHIQ_STATUS_T vchiq_add_service (VCHIQ_INSTANCE_T instance, const VCHIQ_SERVICE_PARAMS_T * params, VCHIQ_SERVICE_HANDLE_T * pservice)
open
Definition at line 269 of file vchiq_lib.c.
References vchiq_service_params_struct::callback, vchiq_service_params_struct::fourcc, status, and VCHIQ_ERROR.
 {
    VCHIQ_STATUS_T status;
    vcos_log_trace( "%s called fourcc = 0x%08x (%c%c%c%c)",
                    __func__,
                    params->fourcc,
                    (params->fourcc >> 24) & 0xff,
                    (params->fourcc >> 16) & 0xff,
                    (params->fourcc >>  8) & 0xff,
                    (params->fourcc      ) & 0xff );
    if (!params->callback)
       return VCHIQ_ERROR;
    if (!is_valid_instance(instance))
       return VCHIQ_ERROR;
    status = create_service(instance,
       params,
       NULL/*vchi_callback*/,
       0,
       phandle);
    vcos_log_trace( "%s returning service handle = 0x%08x", __func__, (uint32_t)*phandle );
    return status;
 }
vchiq_bulk_receive()
VCHIQ_STATUS_T vchiq_bulk_receive (VCHIQ_SERVICE_HANDLE_T service, void * data, int size, void * userdata, VCHIQ_BULK_MODE_T mode)
Definition at line 511 of file vchiq_lib.c.
References NULL, VCHI_MEM_HANDLE_INVALID, and vchiq_bulk_receive_handle().
 {
    return vchiq_bulk_receive_handle(handle, VCHI_MEM_HANDLE_INVALID, data, size, userdata, mode, NULL);
 }
vchiq_bulk_receive_handle()
VCHIQ_STATUS_T vchiq_bulk_receive_handle (VCHIQ_SERVICE_HANDLE_T service, VCHI_MEM_HANDLE_T handle, void * offset, int size, void * userdata, VCHIQ_BULK_MODE_T mode, int copy_pagelistchar *vcptr, const struct pagelist_struct *pagelist)
vchiq_bulk_transmit()
VCHIQ_STATUS_T vchiq_bulk_transmit (VCHIQ_SERVICE_HANDLE_T service, const void * data, int size, void * userdata, VCHIQ_BULK_MODE_T mode)
Definition at line 485 of file vchiq_lib.c.
Referenced by vchiq_bulk_transmit_handle().
 {
    VCHIQ_SERVICE_T *service = find_service_by_handle(handle);
    VCHIQ_QUEUE_BULK_TRANSFER_T args;
    int ret;
    vcos_log_trace( "%s called service handle = 0x%08x", __func__, (uint32_t)handle );
    if (!service)
       return VCHIQ_ERROR;
    args.handle = service->handle;
    args.data = (void *)data;
    args.size = size;
    args.userdata = userdata;
    args.mode = mode;
    RETRY(ret, ioctl(service->fd, VCHIQ_IOC_QUEUE_BULK_TRANSMIT, &args));
    return (ret >= 0) ? VCHIQ_SUCCESS : VCHIQ_ERROR;
 }
vchiq_bulk_transmit_handle()
VCHIQ_STATUS_T vchiq_bulk_transmit_handle (VCHIQ_SERVICE_HANDLE_T service, VCHI_MEM_HANDLE_T handle, const void * offset, int size, void * userdata, VCHIQ_BULK_MODE_T mode)
Definition at line 521 of file vchiq_lib.c.
References VCHI_MEM_HANDLE_INVALID, vchiq_bulk_transmit(), and vcos_assert.
 {
    vcos_assert(memhandle == VCHI_MEM_HANDLE_INVALID);
    return vchiq_bulk_transmit(handle, offset, size, userdata, mode);
 }
vchiq_close_service()
VCHIQ_STATUS_T vchiq_close_service (VCHIQ_SERVICE_HANDLE_T service)
Definition at line 333 of file vchiq_lib.c.
 {
    VCHIQ_SERVICE_T *service = find_service_by_handle(handle);
    int ret;
    vcos_log_trace( "%s called service handle = 0x%08x", __func__, (uint32_t)handle );
    if (!service)
       return VCHIQ_ERROR;
    RETRY(ret,ioctl(service->fd, VCHIQ_IOC_CLOSE_SERVICE, service->handle));
    if (service->is_client)
       service->lib_handle = VCHIQ_SERVICE_HANDLE_INVALID;
    if (ret != 0)
       return VCHIQ_ERROR;
    return VCHIQ_SUCCESS;
 }
vchiq_connect()
VCHIQ_STATUS_T vchiq_connect (VCHIQ_INSTANCE_T instance)
Definition at line 230 of file vchiq_lib.c.
References status, and VCHIQ_SUCCESS.
Referenced by vc_vchi_khronos_init(), and vchi_connect().
 {
    VCHIQ_STATUS_T status = VCHIQ_SUCCESS;
    VCOS_THREAD_ATTR_T attrs;
    int ret;
    vcos_log_trace( "%s called", __func__ );
    if (!is_valid_instance(instance))
       return VCHIQ_ERROR;
    vcos_mutex_lock(&instance->mutex);
    if (instance->connected)
       goto out;
    ret = ioctl(instance->fd, VCHIQ_IOC_CONNECT, 0);
    if (ret != 0)
    {
       status = VCHIQ_ERROR;
       goto out;
    }
    vcos_thread_attr_init(&attrs);
    if (vcos_thread_create(&instance->completion_thread, "VCHIQ completion",
                           &attrs, completion_thread, instance) != VCOS_SUCCESS)
    {
       status = VCHIQ_ERROR;
       goto out;
    }
    instance->connected = 1;
 out:
    vcos_mutex_unlock(&instance->mutex);
    return status;
 }
vchiq_dump_phys_mem()
VCHIQ_STATUS_T vchiq_dump_phys_mem (VCHIQ_SERVICE_HANDLE_T service, void * ptr, size_t num_bytes)
Definition at line 1395 of file vchiq_lib.c.
References vchiq_service_struct::fd, VCHIQ_DUMP_MEM_T::num_bytes, RETRY, VCHIQ_ERROR, VCHIQ_IOC_DUMP_PHYS_MEM, VCHIQ_SUCCESS, and VCHIQ_DUMP_MEM_T::virt_addr.
 {
    VCHIQ_SERVICE_T *service = (VCHIQ_SERVICE_T *)handle;
    VCHIQ_DUMP_MEM_T  dump_mem;
    int ret;
    if (!service)
       return VCHIQ_ERROR;
    dump_mem.virt_addr = ptr;
    dump_mem.num_bytes = num_bytes;
    RETRY(ret,ioctl(service->fd, VCHIQ_IOC_DUMP_PHYS_MEM, &dump_mem));
    return (ret >= 0) ? VCHIQ_SUCCESS : VCHIQ_ERROR;
 }
vchiq_get_client_id()
int vchiq_get_client_id (VCHIQ_SERVICE_HANDLE_T service)
Definition at line 564 of file vchiq_lib.c.
Referenced by khan_callback(), and rpc_get_client_id().
 {
    VCHIQ_SERVICE_T *service = find_service_by_handle(handle);
    if (!service)
       return VCHIQ_ERROR;
    return ioctl(service->fd, VCHIQ_IOC_GET_CLIENT_ID, service->handle);
 }
vchiq_get_config()
VCHIQ_STATUS_T vchiq_get_config (VCHIQ_INSTANCE_T instance, int config_size, VCHIQ_CONFIG_T * pconfig)
Definition at line 591 of file vchiq_lib.c.
 {
    VCHIQ_GET_CONFIG_T args;
    int ret;
    if (!is_valid_instance(instance))
       return VCHIQ_ERROR;
    args.config_size = config_size;
    args.pconfig = pconfig;
    RETRY(ret, ioctl(instance->fd, VCHIQ_IOC_GET_CONFIG, &args));
    return (ret >= 0) ? VCHIQ_SUCCESS : VCHIQ_ERROR;
 }
vchiq_get_peer_version()
VCHIQ_STATUS_T vchiq_get_peer_version (VCHIQ_SERVICE_HANDLE_T handle, short * peer_version)
vchiq_get_service_fourcc()
int vchiq_get_service_fourcc (VCHIQ_SERVICE_HANDLE_T service)
Definition at line 583 of file vchiq_lib.c.
 {
    VCHIQ_SERVICE_T *service = find_service_by_handle(handle);
    return service ? service->base.fourcc : 0;
 }
vchiq_get_service_userdata()
void* vchiq_get_service_userdata (VCHIQ_SERVICE_HANDLE_T service)
Definition at line 575 of file vchiq_lib.c.
 {
    VCHIQ_SERVICE_T *service = find_service_by_handle(handle);
    return service ? service->base.userdata : NULL;
 }
vchiq_initialise()
VCHIQ_STATUS_T vchiq_initialise (VCHIQ_INSTANCE_T * pinstance)
Definition at line 161 of file vchiq_lib.c.
References vchiq_initialise_fd().
Referenced by bcm_host_init(), and vc_vchi_khronos_init().
 {
    return vchiq_initialise_fd(pinstance, -1);
 }
vchiq_initialise_fd()
VCHIQ_STATUS_T vchiq_initialise_fd (VCHIQ_INSTANCE_T * pinstance, int dev_vchiq_fd)
Definition at line 147 of file vchiq_lib.c.
Referenced by vchiq_initialise().
 {
    VCHIQ_INSTANCE_T instance;
    instance = vchiq_lib_init(dev_vchiq_fd);
    vcos_log_trace( "%s: returning instance handle %p", __func__, instance );
    *pinstance = instance;
    return (instance != NULL) ? VCHIQ_SUCCESS : VCHIQ_ERROR;
 }
vchiq_open_service()
VCHIQ_STATUS_T vchiq_open_service (VCHIQ_INSTANCE_T instance, const VCHIQ_SERVICE_PARAMS_T * params, VCHIQ_SERVICE_HANDLE_T * pservice)
Definition at line 301 of file vchiq_lib.c.
References vchiq_service_params_struct::callback, vchiq_service_params_struct::fourcc, status, and VCHIQ_ERROR.
Referenced by vc_vchi_khronos_init().
 {
    VCHIQ_STATUS_T status;
    vcos_log_trace( "%s called fourcc = 0x%08x (%c%c%c%c)",
                    __func__,
                    params->fourcc,
                    (params->fourcc >> 24) & 0xff,
                    (params->fourcc >> 16) & 0xff,
                    (params->fourcc >>  8) & 0xff,
                    (params->fourcc      ) & 0xff );
    if (!params->callback)
       return VCHIQ_ERROR;
    if (!is_valid_instance(instance))
       return VCHIQ_ERROR;
    status = create_service(instance,
       params,
       NULL/*vchi_callback*/,
       1/*open*/,
       phandle);
    vcos_log_trace( "%s returning service handle = 0x%08x", __func__, (uint32_t)*phandle );
    return status;
 }
vchiq_queue_bulk_receive()
VCHIQ_STATUS_T vchiq_queue_bulk_receive (VCHIQ_SERVICE_HANDLE_T service, void * data, int size, void * userdata)
Definition at line 432 of file vchiq_lib.c.
Referenced by ilcs_receive_buffer(), and vchiq_queue_bulk_receive_handle().
 {
    VCHIQ_SERVICE_T *service = find_service_by_handle(handle);
    VCHIQ_QUEUE_BULK_TRANSFER_T args;
    int ret;
    vcos_log_trace( "%s called service handle = 0x%08x", __func__, (uint32_t)handle );
    if (!service)
       return VCHIQ_ERROR;
    args.handle = service->handle;
    args.data = data;
    args.size = size;
    args.userdata = userdata;
    args.mode = VCHIQ_BULK_MODE_CALLBACK;
    RETRY(ret, ioctl(service->fd, VCHIQ_IOC_QUEUE_BULK_RECEIVE, &args));
    return (ret >= 0) ? VCHIQ_SUCCESS : VCHIQ_ERROR;
 }
vchiq_queue_bulk_receive_handle()
VCHIQ_STATUS_T vchiq_queue_bulk_receive_handle (VCHIQ_SERVICE_HANDLE_T service, VCHI_MEM_HANDLE_T handle, void * offset, int size, void * userdata)
Definition at line 471 of file vchiq_lib.c.
References VCHI_MEM_HANDLE_INVALID, vchiq_queue_bulk_receive(), and vcos_assert.
Referenced by ilcs_receive_buffer().
 {
    vcos_assert(memhandle == VCHI_MEM_HANDLE_INVALID);
    vcos_log_trace( "%s called service handle = 0x%08x", __func__, (uint32_t)handle );
    return vchiq_queue_bulk_receive(handle, offset, size, userdata);
 }
vchiq_queue_bulk_transmit()
VCHIQ_STATUS_T vchiq_queue_bulk_transmit (VCHIQ_SERVICE_HANDLE_T service, const void * data, int size, void * userdata)
Definition at line 407 of file vchiq_lib.c.
Referenced by mmal_vc_send_message(), and vchiq_queue_bulk_transmit_handle().
 {
    VCHIQ_SERVICE_T *service = find_service_by_handle(handle);
    VCHIQ_QUEUE_BULK_TRANSFER_T args;
    int ret;
    vcos_log_trace( "%s called service handle = 0x%08x", __func__, (uint32_t)handle );
    if (!service)
       return VCHIQ_ERROR;
    args.handle = service->handle;
    args.data = (void *)data;
    args.size = size;
    args.userdata = userdata;
    args.mode = VCHIQ_BULK_MODE_CALLBACK;
    RETRY(ret, ioctl(service->fd, VCHIQ_IOC_QUEUE_BULK_TRANSMIT, &args));
    return (ret >= 0) ? VCHIQ_SUCCESS : VCHIQ_ERROR;
 }
vchiq_queue_bulk_transmit_handle()
VCHIQ_STATUS_T vchiq_queue_bulk_transmit_handle (VCHIQ_SERVICE_HANDLE_T service, VCHI_MEM_HANDLE_T handle, const void * offset, int size, void * userdata)
Definition at line 457 of file vchiq_lib.c.
References VCHI_MEM_HANDLE_INVALID, vchiq_queue_bulk_transmit(), and vcos_assert.
 {
    vcos_assert(memhandle == VCHI_MEM_HANDLE_INVALID);
    vcos_log_trace( "%s called service handle = 0x%08x", __func__, (uint32_t)handle );
    return vchiq_queue_bulk_transmit(handle, offset, size, userdata);
 }
vchiq_queue_message()
VCHIQ_STATUS_T vchiq_queue_message (VCHIQ_SERVICE_HANDLE_T service, const VCHIQ_ELEMENT_T * elements, int count)
Definition at line 376 of file vchiq_lib.c.
Referenced by mmal_vc_send_message(), and vc_gpuserv_execute_code().
 {
    VCHIQ_SERVICE_T *service = find_service_by_handle(handle);
    VCHIQ_QUEUE_MESSAGE_T args;
    int ret;
    vcos_log_trace( "%s called service handle = 0x%08x", __func__, (uint32_t)handle );
    if (!service)
       return VCHIQ_ERROR;
    args.handle = service->handle;
    args.elements = elements;
    args.count = count;
    RETRY(ret, ioctl(service->fd, VCHIQ_IOC_QUEUE_MESSAGE, &args));
    return (ret >= 0) ? VCHIQ_SUCCESS : VCHIQ_ERROR;
 }
vchiq_release_message()
void vchiq_release_message (VCHIQ_SERVICE_HANDLE_T service, VCHIQ_HEADER_T * header)
Definition at line 398 of file vchiq_lib.c.
 {
    vcos_log_trace( "%s handle=%08x, header=%x", __func__, (uint32_t)handle, (uint32_t)header );
    free_msgbuf(header);
 }
vchiq_release_service()
VCHIQ_STATUS_T vchiq_release_service (VCHIQ_SERVICE_HANDLE_T service)
Definition at line 623 of file vchiq_lib.c.
 {
    VCHIQ_SERVICE_T *service = find_service_by_handle(handle);
    int ret;
    if (!service)
       return VCHIQ_ERROR;
    RETRY(ret,ioctl(service->fd, VCHIQ_IOC_RELEASE_SERVICE, service->handle));
    return ret;
 }
vchiq_remote_release()
VCHIQ_STATUS_T vchiq_remote_release (VCHIQ_INSTANCE_T instance)
vchiq_remote_use()
VCHIQ_STATUS_T vchiq_remote_use (VCHIQ_INSTANCE_T instance, VCHIQ_REMOTE_USE_CALLBACK_T callback, void * cb_arg)
vchiq_remove_service()
VCHIQ_STATUS_T vchiq_remove_service (VCHIQ_SERVICE_HANDLE_T service)
Definition at line 355 of file vchiq_lib.c.
 {
    VCHIQ_SERVICE_T *service = find_service_by_handle(handle);
    int ret;
    vcos_log_trace( "%s called service handle = 0x%08x", __func__, (uint32_t)handle );
    if (!service)
       return VCHIQ_ERROR;
    RETRY(ret,ioctl(service->fd, VCHIQ_IOC_REMOVE_SERVICE, service->handle));
    service->lib_handle = VCHIQ_SERVICE_HANDLE_INVALID;
    if (ret != 0)
       return VCHIQ_ERROR;
    return VCHIQ_SUCCESS;
 }
vchiq_set_service_option()
VCHIQ_STATUS_T vchiq_set_service_option (VCHIQ_SERVICE_HANDLE_T service, VCHIQ_SERVICE_OPTION_T option, int value)
Definition at line 636 of file vchiq_lib.c.
 {
    VCHIQ_SET_SERVICE_OPTION_T args;
    VCHIQ_SERVICE_T *service = find_service_by_handle(handle);
    int ret;
    if (!service)
       return VCHIQ_ERROR;
    args.handle = service->handle;
    args.option = option;
    args.value  = value;
    RETRY(ret, ioctl(service->fd, VCHIQ_IOC_SET_SERVICE_OPTION, &args));
    return (ret >= 0) ? VCHIQ_SUCCESS : VCHIQ_ERROR;
 }
vchiq_shutdown()
VCHIQ_STATUS_T vchiq_shutdown (VCHIQ_INSTANCE_T instance)
Definition at line 167 of file vchiq_lib.c.
Referenced by vchi_disconnect().
 {
    vcos_log_trace( "%s called", __func__ );
    if (!is_valid_instance(instance))
       return VCHIQ_ERROR;
    vcos_mutex_lock(&instance->mutex);
    if (instance->initialised == 1)
    {
       int i;
       instance->initialised = -1; /* Enter limbo */
       /* Remove all services */
       for (i = 0; i < instance->used_services; i++)
       {
          if (instance->services[i].lib_handle != VCHIQ_SERVICE_HANDLE_INVALID)
          {
             vchiq_remove_service(instance->services[i].lib_handle);
             instance->services[i].lib_handle = VCHIQ_SERVICE_HANDLE_INVALID;
          }
       }
       if (instance->connected)
       {
          int ret;
          RETRY(ret, ioctl(instance->fd, VCHIQ_IOC_SHUTDOWN, 0));
          vcos_assert(ret == 0);
          vcos_thread_join(&instance->completion_thread, NULL);
          instance->connected = 0;
       }
       close(instance->fd);
       instance->fd = -1;
    }
    else if (instance->initialised > 1)
    {
       instance->initialised--;
    }
    vcos_mutex_unlock(&instance->mutex);
    vcos_global_lock();
    if (instance->initialised == -1)
    {
       vcos_mutex_delete(&instance->mutex);
       instance->initialised = 0;
    }
    vcos_global_unlock();
    vcos_log_trace( "%s returning", __func__ );
    vcos_log_unregister(&vchiq_lib_log_category);
    return VCHIQ_SUCCESS;
 }
vchiq_use_service()
VCHIQ_STATUS_T vchiq_use_service (VCHIQ_SERVICE_HANDLE_T service)
Definition at line 610 of file vchiq_lib.c.
 {
    VCHIQ_SERVICE_T *service = find_service_by_handle(handle);
    int ret;
    if (!service)
       return VCHIQ_ERROR;
    RETRY(ret,ioctl(service->fd, VCHIQ_IOC_USE_SERVICE, service->handle));
    return ret;
 }