VideoCore Library: interface/vcos/vcos_event.h File Reference
vcos_event.h File Reference
#include "interface/vcos/vcos_types.h"
#include "vcos.h"
Macros
#define VCOS_EVENT_H
#define VCOS_EVENT_H
Functions
VCOS_INLINE_DECL VCOS_STATUS_T vcos_event_create (VCOS_EVENT_T *event, const char *name)
VCOS_INLINE_DECL void vcos_event_signal (VCOS_EVENT_T *event)
VCOS_INLINE_DECL VCOS_STATUS_T vcos_event_wait (VCOS_EVENT_T *event)
VCOS_INLINE_DECL VCOS_STATUS_T vcos_event_try (VCOS_EVENT_T *event)
VCOS_INLINE_DECL void vcos_event_delete (VCOS_EVENT_T *event)
Detailed Description
An event is akin to the Win32 auto-reset event.
Signalling an event will wake up one waiting thread only. Once one thread has been woken the event atomically returns to the unsignalled state.
If no threads are waiting on the event when it is signalled it remains signalled.
This is almost, but not quite, completely unlike the "event flags" object based on Nucleus event groups and ThreadX event flags.
In particular, it should be similar in speed to a semaphore, unlike the event flags.
Definition in file vcos_event.h.
Macro Definition Documentation
VCOS_EVENT_H [1/2]
#define VCOS_EVENT_H
VCOS_EVENT_H [2/2]
#define VCOS_EVENT_H
Function Documentation
vcos_event_create()
VCOS_INLINE_DECL VCOS_STATUS_T vcos_event_create (VCOS_EVENT_T * event, const char * name)
Create an event instance.
Parameters
event Filled in with constructed event.
name Name of the event (for debugging)
Returns
VCOS_SUCCESS on success, or error code.
Referenced by mmal_component_action_register(), vc_vchi_cec_init(), vc_vchi_dispmanx_init(), vc_vchi_filesys_init(), vc_vchi_gencmd_init(), vc_vchi_khronos_init(), and vc_vchi_tv_init().
vcos_event_delete()
VCOS_INLINE_DECL void vcos_event_delete (VCOS_EVENT_T * event)
Referenced by mmal_component_action_deregister(), mmal_component_action_register(), and vchiu_queue_delete().
vcos_event_signal()
VCOS_INLINE_DECL void vcos_event_signal (VCOS_EVENT_T * event)
Signal the event. The event will return to being unsignalled after exactly one waiting thread has been woken up. If no threads are waiting it remains signalled.
Parameters
event The event to signal
Referenced by khhn_callback(), khrn_callback(), mmal_component_action_deregister(), mmal_component_action_trigger(), vchiu_queue_pop(), and vchiu_queue_push().
vcos_event_try()
VCOS_INLINE_DECL VCOS_STATUS_T vcos_event_try (VCOS_EVENT_T * event)
Try event, but don't block.
Parameters
event The event to try
Returns
VCOS_SUCCESS on success, VCOS_EAGAIN if the event is not currently signalled
vcos_event_wait()
VCOS_INLINE_DECL VCOS_STATUS_T vcos_event_wait (VCOS_EVENT_T * event)
Wait for the event.
Parameters
event The event to wait for
Returns
VCOS_SUCCESS on success, VCOS_EAGAIN if the wait was interrupted.
Referenced by ilcs_receive_buffer(), vchiu_queue_peek(), vchiu_queue_pop(), and vchiu_queue_push().