VideoCore Library: interface/khronos/common/khrn_client.h File Reference
khrn_client.h File Reference
#include "interface/khronos/common/khrn_client_platform.h"
#include "interface/khronos/egl/egl_client_context.h"
#include "interface/khronos/egl/egl_client_surface.h"
#include "interface/khronos/include/EGL/eglext.h"
#include "interface/khronos/common/khrn_client_pointermap.h"
#include "interface/khronos/common/khrn_client_global_image_map.h"
Classes
struct EGL_CURRENT_T
struct CLIENT_THREAD_STATE
struct CLIENT_PROCESS_STATE
Macros
#define MERGE_BUFFER_SIZE 4080
#define CLIENT_MAKE_CURRENT_SIZE 36 /* RPC_CALL8 */
Typedefs
typedef struct CLIENT_PROCESS_STATE CLIENT_PROCESS_STATE_T
typedef struct CLIENT_THREAD_STATE CLIENT_THREAD_STATE_T
Functions
void client_try_unload_server (CLIENT_PROCESS_STATE_T *process)
void client_thread_state_init (CLIENT_THREAD_STATE_T *state)
void client_thread_state_term (CLIENT_THREAD_STATE_T *state)
bool client_process_state_init (CLIENT_PROCESS_STATE_T *process)
void client_process_state_term (CLIENT_PROCESS_STATE_T *process)
CLIENT_PROCESS_STATE_T * client_egl_get_process_state (CLIENT_THREAD_STATE_T *thread, EGLDisplay dpy, EGLBoolean check_inited)
EGL_CONTEXT_T * client_egl_get_context (CLIENT_THREAD_STATE_T *thread, CLIENT_PROCESS_STATE_T *process, EGLContext ctx)
EGL_SURFACE_T * client_egl_get_surface (CLIENT_THREAD_STATE_T *thread, CLIENT_PROCESS_STATE_T *process, EGLSurface surf)
EGL_SURFACE_T * client_egl_get_locked_surface (CLIENT_THREAD_STATE_T *thread, CLIENT_PROCESS_STATE_T *process, EGLSurface surf)
EGLNativeWindowType client_egl_get_window (CLIENT_THREAD_STATE_T *thread, CLIENT_PROCESS_STATE_T *process, EGLNativeWindowType window)
void client_send_make_current (CLIENT_THREAD_STATE_T *thread)
void client_set_error (uint32_t server_context_name)
bool client_process_attach (void)
bool client_thread_attach (void)
void client_thread_detach (void *dummy)
void client_process_detach (void)
Variables
PLATFORM_TLS_T client_tls
CLIENT_PROCESS_STATE_T client_process_state
PLATFORM_MUTEX_T client_mutex
Macro Definition Documentation
CLIENT_MAKE_CURRENT_SIZE
#define CLIENT_MAKE_CURRENT_SIZE 36 /* RPC_CALL8 */
Definition at line 354 of file khrn_client.h.
Referenced by rpc_call8_makecurrent(), and rpc_send_ctrl_longest().
MERGE_BUFFER_SIZE
#define MERGE_BUFFER_SIZE 4080
Definition at line 67 of file khrn_client.h.
Referenced by rpc_send_ctrl_longest().
Typedef Documentation
CLIENT_PROCESS_STATE_T
typedef struct CLIENT_PROCESS_STATE CLIENT_PROCESS_STATE_T
Definition at line 30 of file khrn_client.h.
CLIENT_THREAD_STATE_T
typedef struct CLIENT_THREAD_STATE CLIENT_THREAD_STATE_T
Definition at line 31 of file khrn_client.h.
Function Documentation
client_egl_get_context()
EGL_CONTEXT_T* client_egl_get_context (CLIENT_THREAD_STATE_T * thread, CLIENT_PROCESS_STATE_T * process, EGLContext ctx)
Definition at line 307 of file khrn_client.c.
 {
    EGL_CONTEXT_T *context = (EGL_CONTEXT_T *)khrn_pointer_map_lookup(&process->contexts, (uint32_t)(size_t)ctx);
    vcos_assert(!context || !context->is_destroyed);
    if (!context)
       thread->error = EGL_BAD_CONTEXT;
    return context;
 }
client_egl_get_locked_surface()
EGL_SURFACE_T* client_egl_get_locked_surface (CLIENT_THREAD_STATE_T * thread, CLIENT_PROCESS_STATE_T * process, EGLSurface surf)
Definition at line 342 of file khrn_client.c.
References EGL_BAD_SURFACE, CLIENT_THREAD_STATE::error, EGL_SURFACE_T::is_destroyed, CLIENT_PROCESS_STATE::surfaces, and vcos_assert.
 {
    EGL_SURFACE_T *surface = (EGL_SURFACE_T *)khrn_pointer_map_lookup(&process->surfaces, (uint32_t)(size_t)surf);
    vcos_assert (!surface || !surface->is_destroyed);
    if (!surface)
       thread->error = EGL_BAD_SURFACE;
    return surface;
 }
client_egl_get_process_state()
CLIENT_PROCESS_STATE_T* client_egl_get_process_state (CLIENT_THREAD_STATE_T * thread, EGLDisplay dpy, EGLBoolean check_inited)
Definition at line 126 of file khrn_client_cr.c.
 {
    if ((size_t)dpy == 1) {
       CLIENT_PROCESS_STATE_T *process = CLIENT_GET_PROCESS_STATE();
       if (check_inited && !process->inited) {
          thread->error = EGL_NOT_INITIALIZED;
          return NULL;
       } else
          return process;
    } else {
       thread->error = EGL_BAD_DISPLAY;
       return NULL;
    }
 }
client_egl_get_surface()
EGL_SURFACE_T* client_egl_get_surface (CLIENT_THREAD_STATE_T * thread, CLIENT_PROCESS_STATE_T * process, EGLSurface surf)
Definition at line 319 of file khrn_client.c.
References EGL_BAD_ACCESS, EGL_BAD_SURFACE, CLIENT_THREAD_STATE::error, EGL_SURFACE_T::is_destroyed, NULL, CLIENT_PROCESS_STATE::surfaces, and vcos_assert.
 {
    EGL_SURFACE_T *surface = (EGL_SURFACE_T *)khrn_pointer_map_lookup(&process->surfaces, (uint32_t)(size_t)surf);
    vcos_assert (!surface || !surface->is_destroyed);
    if (!surface)
       thread->error = EGL_BAD_SURFACE;
 #if EGL_KHR_lock_surface
    if (surface && surface->is_locked) {
       thread->error = EGL_BAD_ACCESS;
       surface = NULL;
    }
 #endif
    return surface;
 }
client_egl_get_window()
EGLNativeWindowType client_egl_get_window (CLIENT_THREAD_STATE_T * thread, CLIENT_PROCESS_STATE_T * process, EGLNativeWindowType window)
Definition at line 357 of file khrn_client.c.
References CLIENT_PROCESS_STATE::windows.
 {
    EGLNativeWindowType win = (EGLNativeWindowType)khrn_pointer_map_lookup(&process->windows, (uint32_t)(size_t)window);
    return win;
 }
client_process_attach()
bool client_process_attach (void)
Definition at line 427 of file khrn_client.c.
References client_tls, KHR_SUCCESS, platform_mutex_create(), platform_mutex_destroy(), platform_tls_create(), platform_tls_destroy, RPC_INIT, and status.
 {
    KHR_STATUS_T status;
    status = platform_tls_create(&client_tls);
    if (status != KHR_SUCCESS) {
       return false;
    }
 #ifdef CLIENT_THREAD_IS_PROCESS
    status = platform_tls_create(&client_tls_process);
    if (status != KHR_SUCCESS) {
       return false;
    }
    status = platform_tls_create(&client_tls_mutex);
    if (status != KHR_SUCCESS) {
       return false;
    }
 #endif
    status = platform_mutex_create(&client_mutex);
    if (status != KHR_SUCCESS) {
       platform_tls_destroy(client_tls);
       return false;
    }
    if (!RPC_INIT()) {
       platform_mutex_destroy(&client_mutex);
       platform_tls_destroy(client_tls);
       return false;
    }
    return true;
 }
client_process_detach()
void client_process_detach (void)
Definition at line 530 of file khrn_client.c.
References client_tls, platform_mutex_destroy(), platform_tls_destroy, and RPC_TERM.
 {
    RPC_TERM();
    platform_tls_destroy(client_tls);
    platform_mutex_destroy(&client_mutex);
 #ifdef CLIENT_THREAD_IS_PROCESS
     platform_tls_destroy(client_tls_process);
 #endif
 }
client_process_state_init()
bool client_process_state_init (CLIENT_PROCESS_STATE_T * process)
Definition at line 142 of file khrn_client.c.
References CLIENT_PROCESS_STATE::contexts, egl_config_install_configs(), CLIENT_PROCESS_STATE::inited, CLIENT_PROCESS_STATE::next_context, CLIENT_PROCESS_STATE::next_surface, NULL, RPC_CALL0, CLIENT_PROCESS_STATE::surfaces, and CLIENT_PROCESS_STATE::windows.
 {
    if (!process->inited) {
       if (!khrn_pointer_map_init(&process->contexts, 64))
          return false;
       if (!khrn_pointer_map_init(&process->surfaces, 64))
       {
          khrn_pointer_map_term(&process->contexts);
          return false;
       }
       if (!khrn_pointer_map_init(&process->windows, 64))
       {
          khrn_pointer_map_term(&process->contexts);
          khrn_pointer_map_term(&process->surfaces);
          return false;
       }
 #if EGL_KHR_sync
       if (!khrn_pointer_map_init(&process->syncs, 64))
       {
          khrn_pointer_map_term(&process->contexts);
          khrn_pointer_map_term(&process->surfaces);
          khrn_pointer_map_term(&process->windows);
          return false;
       }
 #endif
 #if EGL_BRCM_global_image && EGL_KHR_image
       khrn_global_image_map_init(&process->global_image_egl_images, 8);
 #endif
       process->next_surface = 1;
       process->next_context = 1;
 #if EGL_KHR_sync
       process->next_sync = 0x80000001;
 #endif
 #if EGL_BRCM_global_image && EGL_KHR_image
       process->next_global_image_egl_image = 1 << 31;
 #endif
 #if EGL_BRCM_perf_monitor
       process->perf_monitor_inited = false;
 #endif
 #ifdef RPC_LIBRARY
       if (!process->connected) {
          process->khrn_connection.make_current_func = client_library_send_make_current;
          khronos_server_lock_func_table(&process->khrn_connection);
          khronos_server_connect(&process->khrn_connection);
          khronos_server_unlock_func_table();
          RPC_CALL0(khrn_misc_startup_impl, NULL, no_id);
          process->connected = true;
       }
 #endif
       process->inited = true;
    }
 #ifndef ABSTRACT_PLATFORM
 #if defined(ANDROID) && !defined (ANDROID_HWCOMPOSER)
    egl_config_install_configs(1); // T-format configs
 #else
    egl_config_install_configs(0); // RSO configs
 #endif
 #endif
    return true;
 }
client_process_state_term()
void client_process_state_term (CLIENT_PROCESS_STATE_T * process)
Definition at line 239 of file khrn_client.c.
References CLIENT_PROCESS_STATE::contexts, and CLIENT_PROCESS_STATE::inited.
 {
    if (process->inited) {
       khrn_pointer_map_iterate(&process->contexts, callback_destroy_context, NULL);
       khrn_pointer_map_term(&process->contexts);
       khrn_pointer_map_iterate(&process->surfaces, callback_destroy_surface, NULL);
       khrn_pointer_map_term(&process->surfaces);
       khrn_pointer_map_term(&process->windows);
 #if EGL_KHR_sync
       egl_sync_destroy_all(&process->syncs);
       khrn_pointer_map_term(&process->syncs);
 #endif
 #if EGL_BRCM_global_image && EGL_KHR_image
       khrn_global_image_map_term(&process->global_image_egl_images);
 #endif
 #if EGL_BRCM_perf_monitor
       egl_perf_monitor_term(process);
 #endif
 #if EGL_BRCM_driver_monitor
       egl_driver_monitor_term(process);
 #endif
       process->inited = false;
    }
 }
client_send_make_current()
void client_send_make_current (CLIENT_THREAD_STATE_T * thread)
Definition at line 373 of file khrn_client.c.
References EGL_CURRENT_T::context, CLIENT_THREAD_STATE::opengl, and rpc_get_client_id().
 {
    uint64_t pid                  = rpc_get_client_id(thread);
    uint32_t gltype               = thread->opengl.context ? convert_gltype(thread->opengl.context->type) : 0;
    EGL_GL_CONTEXT_ID_T servergl  = thread->opengl.context ? thread->opengl.context->servercontext : EGL_SERVER_NO_GL_CONTEXT;
    EGL_SURFACE_ID_T servergldraw = thread->opengl.draw    ? thread->opengl.draw->serverbuffer     : EGL_SERVER_NO_SURFACE;
    EGL_SURFACE_ID_T serverglread = thread->opengl.read    ? thread->opengl.read->serverbuffer     : EGL_SERVER_NO_SURFACE;
    EGL_VG_CONTEXT_ID_T servervg  = thread->openvg.context ? thread->openvg.context->servercontext : EGL_SERVER_NO_VG_CONTEXT;
    EGL_SURFACE_ID_T servervgsurf = thread->openvg.draw    ? thread->openvg.draw->serverbuffer     : EGL_SERVER_NO_SURFACE;
    /*
       if the size of this call in the merge buffer changes,
       CLIENT_MAKE_CURRENT_SIZE in khrn_client.h should be updated
    */
    if (!thread->opengl.context || !thread->opengl.draw)
    {
       vcos_log_trace("Send null make current %x %x",
                  (unsigned int)(char *)thread->opengl.context, (unsigned int)(char *)thread->opengl.draw);
    }
    else
    {
       vcos_log_trace("Send make current %d[%d %s%s] %d[%d %d%s]",
             (int)thread->opengl.context->name,
             thread->opengl.context->servercontext,
             thread->opengl.context->is_current ? " C" : "",
             thread->opengl.context->is_destroyed ? " D" : "",
             (int)thread->opengl.draw->name,
             thread->opengl.draw->serverbuffer,
             thread->opengl.draw->context_binding_count,
             thread->opengl.draw->is_destroyed ? " D" : "");
    }
    RPC_CALL8_MAKECURRENT(eglIntMakeCurrent_impl,
                          thread,
                          EGLINTMAKECURRENT_ID,
                          RPC_UINT((uint32_t)pid),
                          RPC_UINT((uint32_t)(pid >> 32)),
                          RPC_UINT(gltype),
                          RPC_UINT(servergl),
                          RPC_UINT(servergldraw),
                          RPC_UINT(serverglread),
                          RPC_UINT(servervg),
                          RPC_UINT(servervgsurf));
 }
client_set_error()
void client_set_error (uint32_t server_context_name)
client_thread_attach()
bool client_thread_attach (void)
Definition at line 461 of file khrn_client.c.
 {
    CLIENT_THREAD_STATE_T *state = (CLIENT_THREAD_STATE_T *)khrn_platform_malloc(sizeof(CLIENT_THREAD_STATE_T), "CLIENT_THREAD_STATE_T");
    if (!state)
       return false;
    client_thread_state_init(state);
    platform_tls_set(client_tls, state);
 #ifdef CLIENT_THREAD_IS_PROCESS
     {  //add mutex into thread's tls
         KHR_STATUS_T status;
         PLATFORM_MUTEX_T *local_mutex = (PLATFORM_MUTEX_T*)vcos_tls_get(client_tls_mutex);
         if (!local_mutex)
         {
             local_mutex = (PLATFORM_MUTEX_T*)khrn_platform_malloc(sizeof(PLATFORM_MUTEX_T),"thread mutex");
             if (!local_mutex)
                 return false;
             status = platform_mutex_create(local_mutex);
             if (status != KHR_SUCCESS) {
                 khrn_platform_free(local_mutex);
                 return false;
             }
             vcos_tls_set(client_tls_mutex,local_mutex);
         }
     }
 #endif
 #ifndef RPC_LIBRARY    //TODO
    client_send_make_current(state);
 #endif
    return true;
 }
client_thread_detach()
void client_thread_detach (void * dummy)
Definition at line 500 of file khrn_client.c.
 {
    CLIENT_THREAD_STATE_T *state = CLIENT_GET_THREAD_STATE();
    UNUSED(dummy);
    platform_tls_remove(client_tls);
    client_thread_state_term(state);
    khrn_platform_free(state);
    platform_maybe_free_process();
 #ifdef CLIENT_THREAD_IS_PROCESS
     {
         CLIENT_PROCESS_STATE_T *process = CLIENT_GET_PROCESS_STATE();
     khrn_platform_free(process);
         platform_tls_remove(client_tls_process);
     }
     {
         PLATFORM_MUTEX_T *local_mutex = (PLATFORM_MUTEX_T*)vcos_tls_get(client_tls_mutex);
         vcos_assert(local_mutex);
         platform_mutex_destroy(local_mutex);
         khrn_platform_free(local_mutex);
         platform_tls_remove(client_tls_mutex);
     }
 #endif
 }
client_thread_state_init()
void client_thread_state_init (CLIENT_THREAD_STATE_T * state)
Definition at line 278 of file khrn_client.c.
 {
    state->error = EGL_SUCCESS;
    state->bound_api = EGL_OPENGL_ES_API;
    state->opengl.context = 0;
    state->opengl.draw = 0;
    state->opengl.read = 0;
    state->openvg.context = 0;
    state->openvg.draw = 0;
    state->openvg.read = 0;
    state->high_priority = false;
    state->merge_pos = 0;
    state->merge_end = 0;
     state->glgeterror_hack = 0;
     state->async_error_notification = false;
 }
client_thread_state_term()
void client_thread_state_term (CLIENT_THREAD_STATE_T * state)
Definition at line 301 of file khrn_client.c.
 {
    // TODO: termination
    platform_term_rpc( state );
 }
client_try_unload_server()
void client_try_unload_server (CLIENT_PROCESS_STATE_T * process)
Definition at line 79 of file khrn_client.c.
References CLIENT_PROCESS_STATE::context_current_count, CLIENT_PROCESS_STATE::inited, and NULL.
 {
    if (/* some context is current */
       (process->context_current_count != 0) ||
       /* egl is initialised */
       process->inited) {
       return;
    }
    /*
       Prompt the server to unload Khronos VLL if it can,
       and wait until it is done
    */
 #ifdef RPC_LIBRARY   //TODO: not thread safe
    if (process->connected) {
       const KHRONOS_FUNC_TABLE_T *func_table;
       func_table = khronos_server_lock_func_table(client_library_get_connection());
       if (func_table != NULL)
       {
          func_table->khrn_misc_try_unload_impl();
          khronos_server_disconnect();
       }
       khronos_server_unlock_func_table();
       process->connected = false;
    }
 #else
    {
       CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
       RPC_INT_RES(RPC_CALL0_RES(khrn_misc_try_unload_impl, thread, KHRNMISCTRYUNLOAD_ID)); // return unimportant - read is just to cause blocking
    }
 #endif
 }
Variable Documentation
client_mutex
PLATFORM_MUTEX_T client_mutex
Definition at line 421 of file khrn_client.c.
Referenced by platform_client_lock(), and platform_client_release().
client_process_state
CLIENT_PROCESS_STATE_T client_process_state
Definition at line 271 of file khrn_client.c.
client_tls
PLATFORM_TLS_T client_tls
Definition at line 420 of file khrn_client.c.
Referenced by client_process_attach(), and client_process_detach().