VideoCore Library: interface/vmcs_host/vc_dispmanx.h File Reference
vc_dispmanx.h File Reference
#include "interface/vcos/vcos.h"
#include "interface/vctypes/vc_image_types.h"
#include "vc_dispservice_x_defs.h"
#include "interface/vmcs_host/vc_dispmanx_types.h"
#include "interface/vchi/vchi.h"
Macros
#define _VC_DISPMANX_H_
Functions
VCHPRE_ int VCHPOST_ vc_dispman_init (void)
VCHPRE_ void VCHPOST_ vc_dispmanx_stop (void)
VCHPRE_ int VCHPOST_ vc_dispmanx_rect_set (VC_RECT_T *rect, uint32_t x_offset, uint32_t y_offset, uint32_t width, uint32_t height)
VCHPRE_ DISPMANX_RESOURCE_HANDLE_T VCHPOST_ vc_dispmanx_resource_create (VC_IMAGE_TYPE_T type, uint32_t width, uint32_t height, uint32_t *native_image_handle)
VCHPRE_ int VCHPOST_ vc_dispmanx_resource_write_data (DISPMANX_RESOURCE_HANDLE_T res, VC_IMAGE_TYPE_T src_type, int src_pitch, void *src_address, const VC_RECT_T *rect)
VCHPRE_ int VCHPOST_ vc_dispmanx_resource_write_data_handle (DISPMANX_RESOURCE_HANDLE_T res, VC_IMAGE_TYPE_T src_type, int src_pitch, VCHI_MEM_HANDLE_T handle, uint32_t offset, const VC_RECT_T *rect)
VCHPRE_ int VCHPOST_ vc_dispmanx_resource_read_data (DISPMANX_RESOURCE_HANDLE_T handle, const VC_RECT_T *p_rect, void *dst_address, uint32_t dst_pitch)
VCHPRE_ int VCHPOST_ vc_dispmanx_resource_delete (DISPMANX_RESOURCE_HANDLE_T res)
VCHPRE_ DISPMANX_DISPLAY_HANDLE_T VCHPOST_ vc_dispmanx_display_open (uint32_t device)
VCHPRE_ DISPMANX_DISPLAY_HANDLE_T VCHPOST_ vc_dispmanx_display_open_mode (uint32_t device, uint32_t mode)
VCHPRE_ DISPMANX_DISPLAY_HANDLE_T VCHPOST_ vc_dispmanx_display_open_offscreen (DISPMANX_RESOURCE_HANDLE_T dest, DISPMANX_TRANSFORM_T orientation)
VCHPRE_ int VCHPOST_ vc_dispmanx_display_reconfigure (DISPMANX_DISPLAY_HANDLE_T display, uint32_t mode)
VCHPRE_ int VCHPOST_ vc_dispmanx_display_set_destination (DISPMANX_DISPLAY_HANDLE_T display, DISPMANX_RESOURCE_HANDLE_T dest)
VCHPRE_ int VCHPOST_ vc_dispmanx_display_set_background (DISPMANX_UPDATE_HANDLE_T update, DISPMANX_DISPLAY_HANDLE_T display, uint8_t red, uint8_t green, uint8_t blue)
VCHPRE_ int VCHPOST_ vc_dispmanx_display_get_info (DISPMANX_DISPLAY_HANDLE_T display, DISPMANX_MODEINFO_T *pinfo)
VCHPRE_ int VCHPOST_ vc_dispmanx_display_close (DISPMANX_DISPLAY_HANDLE_T display)
VCHPRE_ DISPMANX_UPDATE_HANDLE_T VCHPOST_ vc_dispmanx_update_start (int32_t priority)
VCHPRE_ DISPMANX_ELEMENT_HANDLE_T VCHPOST_ vc_dispmanx_element_add (DISPMANX_UPDATE_HANDLE_T update, DISPMANX_DISPLAY_HANDLE_T display, int32_t layer, const VC_RECT_T *dest_rect, DISPMANX_RESOURCE_HANDLE_T src, const VC_RECT_T *src_rect, DISPMANX_PROTECTION_T protection, VC_DISPMANX_ALPHA_T *alpha, DISPMANX_CLAMP_T *clamp, DISPMANX_TRANSFORM_T transform)
VCHPRE_ int VCHPOST_ vc_dispmanx_element_change_source (DISPMANX_UPDATE_HANDLE_T update, DISPMANX_ELEMENT_HANDLE_T element, DISPMANX_RESOURCE_HANDLE_T src)
VCHPRE_ int VCHPOST_ vc_dispmanx_element_change_layer (DISPMANX_UPDATE_HANDLE_T update, DISPMANX_ELEMENT_HANDLE_T element, int32_t layer)
VCHPRE_ int VCHPOST_ vc_dispmanx_element_modified (DISPMANX_UPDATE_HANDLE_T update, DISPMANX_ELEMENT_HANDLE_T element, const VC_RECT_T *rect)
VCHPRE_ int VCHPOST_ vc_dispmanx_element_remove (DISPMANX_UPDATE_HANDLE_T update, DISPMANX_ELEMENT_HANDLE_T element)
VCHPRE_ int VCHPOST_ vc_dispmanx_update_submit (DISPMANX_UPDATE_HANDLE_T update, DISPMANX_CALLBACK_FUNC_T cb_func, void *cb_arg)
VCHPRE_ int VCHPOST_ vc_dispmanx_update_submit_sync (DISPMANX_UPDATE_HANDLE_T update)
VCHPRE_ int VCHPOST_ vc_dispmanx_query_image_formats (uint32_t *supported_formats)
VCHPRE_ int VCHPOST_ vc_dispmanx_element_change_attributes (DISPMANX_UPDATE_HANDLE_T update, DISPMANX_ELEMENT_HANDLE_T element, uint32_t change_flags, int32_t layer, uint8_t opacity, const VC_RECT_T *dest_rect, const VC_RECT_T *src_rect, DISPMANX_RESOURCE_HANDLE_T mask, DISPMANX_TRANSFORM_T transform)
VCHPRE_ uint32_t VCHPOST_ vc_dispmanx_resource_get_image_handle (DISPMANX_RESOURCE_HANDLE_T res)
VCHPRE_ void VCHPOST_ vc_vchi_dispmanx_init (VCHI_INSTANCE_T initialise_instance, VCHI_CONNECTION_T **connections, uint32_t num_connections)
VCHPRE_ int VCHPOST_ vc_dispmanx_snapshot (DISPMANX_DISPLAY_HANDLE_T display, DISPMANX_RESOURCE_HANDLE_T snapshot_resource, DISPMANX_TRANSFORM_T transform)
VCHPRE_ int VCHPOST_ vc_dispmanx_resource_set_palette (DISPMANX_RESOURCE_HANDLE_T handle, void *src_address, int offset, int size)
VCHPRE_ int VCHPOST_ vc_dispmanx_vsync_callback (DISPMANX_DISPLAY_HANDLE_T display, DISPMANX_CALLBACK_FUNC_T cb_func, void *cb_arg)
Macro Definition Documentation
_VC_DISPMANX_H_
#define _VC_DISPMANX_H_
Function Documentation
vc_dispman_init()
VCHPRE_ int VCHPOST_ vc_dispman_init (void)
vc_dispmanx_display_close()
VCHPRE_ int VCHPOST_ vc_dispmanx_display_close (DISPMANX_DISPLAY_HANDLE_T display)
Definition at line 672 of file vc_vchi_dispmanx.c.
Referenced by graphics_get_display_size(), and raspitexutil_destroy_native_window().
{
    int success;
    display = VC_HTOV32(display);
    success = (int) dispmanx_send_command( EDispmanDisplayClose | DISPMANX_NO_REPLY_MASK,
                                         &display, sizeof(display));
    return success;
 }
vc_dispmanx_display_get_info()
VCHPRE_ int VCHPOST_ vc_dispmanx_display_get_info (DISPMANX_DISPLAY_HANDLE_T display, DISPMANX_MODEINFO_T * pinfo)
Definition at line 642 of file vc_vchi_dispmanx.c.
Referenced by graphics_get_display_size().
 {
    GET_INFO_DATA_T info;
    int32_t success;
    display = VC_HTOV32(display);
    success = dispmanx_send_command_reply (EDispmanDisplayGetInfo,
                                           &display, sizeof(display),
                                           &info, sizeof(info));
    if(success == 0) {
       pinfo->width = VC_VTOH32(info.width);
       pinfo->height = VC_VTOH32(info.height);
       pinfo->transform = (DISPMANX_TRANSFORM_T)VC_VTOH32(info.transform);
       pinfo->input_format = (DISPLAY_INPUT_FORMAT_T)VC_VTOH32(info.input_format);
    }
    return (int) success;
 }
vc_dispmanx_display_open()
VCHPRE_ DISPMANX_DISPLAY_HANDLE_T VCHPOST_ vc_dispmanx_display_open (uint32_t device)
Definition at line 512 of file vc_vchi_dispmanx.c.
References VC_HTOV32.
Referenced by deinit(), graphics_get_display_size(), and raspitexutil_create_native_window().
{
    uint32_t display_handle;
    char *env = getenv("VC_DISPLAY");
    if (device == 0 && env)
    {
       device = atoi(env);
    }
    device = VC_HTOV32(device);
    display_handle = dispmanx_get_handle(EDispmanDisplayOpen,
                                                  &device, sizeof(device));
    return (DISPMANX_DISPLAY_HANDLE_T) display_handle;
 }
vc_dispmanx_display_open_mode()
VCHPRE_ DISPMANX_DISPLAY_HANDLE_T VCHPOST_ vc_dispmanx_display_open_mode (uint32_t device, uint32_t mode)
Definition at line 540 of file vc_vchi_dispmanx.c.
References VC_HTOV32.
{
    uint32_t display_open_param[] = {VC_HTOV32(device), VC_HTOV32(mode)};
    uint32_t display_handle = dispmanx_get_handle(EDispmanDisplayOpenMode,
                                                  &display_open_param, sizeof(display_open_param));
    return (DISPMANX_DISPLAY_HANDLE_T) display_handle;
 }
vc_dispmanx_display_open_offscreen()
VCHPRE_ DISPMANX_DISPLAY_HANDLE_T VCHPOST_ vc_dispmanx_display_open_offscreen (DISPMANX_RESOURCE_HANDLE_T dest, DISPMANX_TRANSFORM_T orientation)
Definition at line 560 of file vc_vchi_dispmanx.c.
References VC_HTOV32.
{
    uint32_t display_open_param[] = {(uint32_t)VC_HTOV32(dest), (uint32_t)VC_HTOV32(orientation)};
    uint32_t display_handle = dispmanx_get_handle(EDispmanDisplayOpenOffscreen,
                                                  &display_open_param, sizeof(display_open_param));
    return (DISPMANX_DISPLAY_HANDLE_T) display_handle;
 }
vc_dispmanx_display_reconfigure()
VCHPRE_ int VCHPOST_ vc_dispmanx_display_reconfigure (DISPMANX_DISPLAY_HANDLE_T display, uint32_t mode)
Definition at line 580 of file vc_vchi_dispmanx.c.
References VC_HTOV32.
{
    uint32_t display_param[] = {(uint32_t)VC_HTOV32(device), VC_HTOV32(mode)};
    int32_t success = dispmanx_send_command(  EDispmanDisplayReconfigure | DISPMANX_NO_REPLY_MASK,
                                              display_param, sizeof(display_param));
    return (int) success;
 }
vc_dispmanx_display_set_background()
VCHPRE_ int VCHPOST_ vc_dispmanx_display_set_background (DISPMANX_UPDATE_HANDLE_T update, DISPMANX_DISPLAY_HANDLE_T display, uint8_t red, uint8_t green, uint8_t blue)
Definition at line 621 of file vc_vchi_dispmanx.c.
{
    uint32_t display_param[] = {(uint32_t)VC_HTOV32(update), (uint32_t) VC_HTOV32(display), VC_HTOV32(red), VC_HTOV32(green), VC_HTOV32(blue)};
    int success = (int) dispmanx_send_command( EDispmanDisplaySetBackground | DISPMANX_NO_REPLY_MASK,
                                         display_param, sizeof(display_param));
    return success;
 }
vc_dispmanx_display_set_destination()
VCHPRE_ int VCHPOST_ vc_dispmanx_display_set_destination (DISPMANX_DISPLAY_HANDLE_T display, DISPMANX_RESOURCE_HANDLE_T dest)
Definition at line 599 of file vc_vchi_dispmanx.c.
{
    uint32_t display_param[] = {(uint32_t)VC_HTOV32(display), (uint32_t)VC_HTOV32(dest)};
    int32_t success = dispmanx_send_command(  EDispmanDisplaySetDestination | DISPMANX_NO_REPLY_MASK,
                                              display_param, sizeof(display_param));
    return (int) success;
 }
vc_dispmanx_element_add()
VCHPRE_ DISPMANX_ELEMENT_HANDLE_T VCHPOST_ vc_dispmanx_element_add (DISPMANX_UPDATE_HANDLE_T update, DISPMANX_DISPLAY_HANDLE_T display, int32_t layer, const VC_RECT_T * dest_rect, DISPMANX_RESOURCE_HANDLE_T src, const VC_RECT_T * src_rect, DISPMANX_PROTECTION_T protection, VC_DISPMANX_ALPHA_T * alpha, DISPMANX_CLAMP_T * clamp, DISPMANX_TRANSFORM_T transform)
Definition at line 775 of file vc_vchi_dispmanx.c.
Referenced by deinit(), and raspitexutil_create_native_window().
{
    int32_t element_param[] = {
       (int32_t) VC_HTOV32(update),
       (int32_t) VC_HTOV32(display),
       (int32_t) VC_HTOV32(layer),
       (int32_t) VC_HTOV32(dest_rect->x),
       (int32_t) VC_HTOV32(dest_rect->y),
       (int32_t) VC_HTOV32(dest_rect->width),
       (int32_t) VC_HTOV32(dest_rect->height),
       (int32_t) VC_HTOV32(src),
       (int32_t) VC_HTOV32(src_rect->x),
       (int32_t) VC_HTOV32(src_rect->y),
       (int32_t) VC_HTOV32(src_rect->width),
       (int32_t) VC_HTOV32(src_rect->height),
       (int32_t) VC_HTOV32(protection),
       alpha ? (int32_t) VC_HTOV32(alpha->flags) : 0,
       alpha ? (int32_t) VC_HTOV32(alpha->opacity) : 0,
       alpha ? (int32_t) VC_HTOV32(alpha->mask) : 0,
       clamp ? (int32_t) VC_HTOV32(clamp->mode) : 0,
       clamp ? (int32_t) VC_HTOV32(clamp->key_mask) : 0,
       clamp ? (int32_t) VC_HTOV32(clamp->key_value.yuv.yy_upper) : 0,
       clamp ? (int32_t) VC_HTOV32(clamp->key_value.yuv.yy_lower) : 0,
       clamp ? (int32_t) VC_HTOV32(clamp->key_value.yuv.cr_upper) : 0,
       clamp ? (int32_t) VC_HTOV32(clamp->key_value.yuv.cr_lower) : 0,
       clamp ? (int32_t) VC_HTOV32(clamp->key_value.yuv.cb_upper) : 0,
       clamp ? (int32_t) VC_HTOV32(clamp->key_value.yuv.cb_lower) : 0,
       clamp ? (int32_t) VC_HTOV32(clamp->replace_value) : 0,
       (int32_t) VC_HTOV32(transform)
    };
    uint32_t handle =  dispmanx_get_handle(EDispmanElementAdd,
                                           element_param, sizeof(element_param));
    return (DISPMANX_ELEMENT_HANDLE_T) handle;
 }
vc_dispmanx_element_change_attributes()
VCHPRE_ int VCHPOST_ vc_dispmanx_element_change_attributes (DISPMANX_UPDATE_HANDLE_T update, DISPMANX_ELEMENT_HANDLE_T element, uint32_t change_flags, int32_t layer, uint8_t opacity, const VC_RECT_T * dest_rect, const VC_RECT_T * src_rect, DISPMANX_RESOURCE_HANDLE_T mask, DISPMANX_TRANSFORM_T transform)
Definition at line 942 of file vc_vchi_dispmanx.c.
References ELEMENT_CHANGE_DEST_RECT, ELEMENT_CHANGE_SRC_RECT, tag_VC_RECT_T::height, VC_HTOV32, tag_VC_RECT_T::width, tag_VC_RECT_T::x, and tag_VC_RECT_T::y.
{
    uint32_t element_param[15] = { (uint32_t) VC_HTOV32(update),
                                   (uint32_t) VC_HTOV32(element),
                                   VC_HTOV32(change_flags),
                                   VC_HTOV32(layer),
                                   VC_HTOV32(opacity),
                                   (uint32_t) VC_HTOV32(mask),
                                   (uint32_t) VC_HTOV32(transform), 0, 0, 0, 0, 0, 0, 0, 0};
    uint32_t param_length = 7*sizeof(uint32_t);
    int success;
    if(dest_rect) {
       element_param[7]  = VC_HTOV32(dest_rect->x);
       element_param[8]  = VC_HTOV32(dest_rect->y);
       element_param[9]  = VC_HTOV32(dest_rect->width);
       element_param[10] = VC_HTOV32(dest_rect->height);
       element_param[2] |= ELEMENT_CHANGE_DEST_RECT;
       param_length += 4*sizeof(uint32_t);
    }
    if(src_rect) {
       element_param[11] = VC_HTOV32(src_rect->x);
       element_param[12] = VC_HTOV32(src_rect->y);
       element_param[13] = VC_HTOV32(src_rect->width);
       element_param[14] = VC_HTOV32(src_rect->height);
       element_param[2] |= ELEMENT_CHANGE_SRC_RECT;
       param_length += 4*sizeof(uint32_t);
    }
    success = (int) dispmanx_send_command( EDispmanElementChangeAttributes | DISPMANX_NO_REPLY_MASK,
                                             element_param, param_length);
    return success;
 }
vc_dispmanx_element_change_layer()
VCHPRE_ int VCHPOST_ vc_dispmanx_element_change_layer (DISPMANX_UPDATE_HANDLE_T update, DISPMANX_ELEMENT_HANDLE_T element, int32_t layer)
Definition at line 858 of file vc_vchi_dispmanx.c.
References VC_HTOV32.
 {
    uint32_t element_param[] = { (uint32_t) VC_HTOV32(update),
                                 (uint32_t) VC_HTOV32(element),
                                 (uint32_t) VC_HTOV32(layer) };
    int success = (int) dispmanx_send_command( EDispmanElementChangeLayer | DISPMANX_NO_REPLY_MASK,
                                               element_param, sizeof(element_param));
    return success;
 }
vc_dispmanx_element_change_source()
VCHPRE_ int VCHPOST_ vc_dispmanx_element_change_source (DISPMANX_UPDATE_HANDLE_T update, DISPMANX_ELEMENT_HANDLE_T element, DISPMANX_RESOURCE_HANDLE_T src)
Definition at line 833 of file vc_vchi_dispmanx.c.
References VC_HTOV32.
{
    uint32_t element_param[] = { (uint32_t) VC_HTOV32(update),
                                 (uint32_t) VC_HTOV32(element),
                                 (uint32_t) VC_HTOV32(src) };
    int success = (int) dispmanx_send_command( EDispmanElementChangeSource | DISPMANX_NO_REPLY_MASK,
                                               element_param, sizeof(element_param));
    return success;
 }
vc_dispmanx_element_modified()
VCHPRE_ int VCHPOST_ vc_dispmanx_element_modified (DISPMANX_UPDATE_HANDLE_T update, DISPMANX_ELEMENT_HANDLE_T element, const VC_RECT_T * rect)
Definition at line 885 of file vc_vchi_dispmanx.c.
References tag_VC_RECT_T::height, VC_HTOV32, tag_VC_RECT_T::width, tag_VC_RECT_T::x, and tag_VC_RECT_T::y.
{
    uint32_t element_param[6] = { (uint32_t) VC_HTOV32(update),
                                  (uint32_t) VC_HTOV32(element), 0, 0, 0, 0};
    uint32_t param_length = 2*sizeof(uint32_t);
    int success;
    if(rect) {
       element_param[2] = VC_HTOV32(rect->x);
       element_param[3] = VC_HTOV32(rect->y);
       element_param[4] = VC_HTOV32(rect->width);
       element_param[5] = VC_HTOV32(rect->height);
       param_length = 6*sizeof(uint32_t);
    }
    success = (int) dispmanx_send_command( EDispmanElementModified | DISPMANX_NO_REPLY_MASK,
                                             element_param, param_length);
    return success;
 }
vc_dispmanx_element_remove()
VCHPRE_ int VCHPOST_ vc_dispmanx_element_remove (DISPMANX_UPDATE_HANDLE_T update, DISPMANX_ELEMENT_HANDLE_T element)
Definition at line 916 of file vc_vchi_dispmanx.c.
References VC_HTOV32.
Referenced by gx_priv_destroy_native_window().
{
    uint32_t element_param[] = {(uint32_t) VC_HTOV32(update), (uint32_t) VC_HTOV32(element)};
    int success = (int) dispmanx_send_command( EDispmanElementRemove | DISPMANX_NO_REPLY_MASK,
                                               element_param, sizeof(element_param));
    return success;
 }
vc_dispmanx_query_image_formats()
VCHPRE_ int VCHPOST_ vc_dispmanx_query_image_formats (uint32_t * supported_formats)
Definition at line 297 of file vc_vchi_dispmanx.c.
{
    *supported_formats = dispmanx_get_handle(EDispmanQueryImageFormats, NULL, 0);
    return (*supported_formats)? 0 : -1;
 }
vc_dispmanx_rect_set()
VCHPRE_ int VCHPOST_ vc_dispmanx_rect_set (VC_RECT_T * rect, uint32_t x_offset, uint32_t y_offset, uint32_t width, uint32_t height)
Definition at line 275 of file vc_vchi_dispmanx.c.
References tag_VC_RECT_T::height, tag_VC_RECT_T::width, tag_VC_RECT_T::x, and tag_VC_RECT_T::y.
{
    rect->x = (int32_t) x_offset;
    rect->y = (int32_t) y_offset;
    rect->width = (int32_t) width;
    rect->height = (int32_t) height;
    return 0;
 }
vc_dispmanx_resource_create()
VCHPRE_ DISPMANX_RESOURCE_HANDLE_T VCHPOST_ vc_dispmanx_resource_create (VC_IMAGE_TYPE_T type, uint32_t width, uint32_t height, uint32_t * native_image_handle)
Definition at line 315 of file vc_vchi_dispmanx.c.
References VC_HTOV32.
{
    uint32_t resourceCreateParams[] = { (uint32_t)VC_HTOV32(type), VC_HTOV32(width), VC_HTOV32(height) };
    uint32_t resource = 0;
    resource = dispmanx_get_handle(EDispmanResourceCreate, resourceCreateParams, sizeof(resourceCreateParams));
    //We don't get an image handle back, so explicitly set this to zero to let the caller know
    *native_image_handle = 0;
    //The caller should call vc_dispmanx_resource_get_image_handle below to get the VC_IMAGE_T *
    //This will be deprecated soon, however
    return (DISPMANX_RESOURCE_HANDLE_T) resource;
 }
vc_dispmanx_resource_delete()
VCHPRE_ int VCHPOST_ vc_dispmanx_resource_delete (DISPMANX_RESOURCE_HANDLE_T res)
Definition at line 355 of file vc_vchi_dispmanx.c.
References status, and VC_HTOV32.
{
    int status;
    res = VC_HTOV32(res);
    //We block to make sure the memory is freed after the call
    status = (int) dispmanx_send_command(EDispmanResourceDelete, &res, sizeof(res));
    return status;
 }
vc_dispmanx_resource_get_image_handle()
VCHPRE_ uint32_t VCHPOST_ vc_dispmanx_resource_get_image_handle (DISPMANX_RESOURCE_HANDLE_T res)
Definition at line 340 of file vc_vchi_dispmanx.c.
{
    return dispmanx_get_handle(EDispmanResourceGetImage, &res, sizeof(res));
 }
vc_dispmanx_resource_read_data()
VCHPRE_ int VCHPOST_ vc_dispmanx_resource_read_data (DISPMANX_RESOURCE_HANDLE_T handle, const VC_RECT_T * p_rect, void * dst_address, uint32_t dst_pitch)
Definition at line 418 of file vc_vchi_dispmanx.c.
References tag_VC_RECT_T::height, VC_HTOV32, and tag_VC_RECT_T::y.
 {
    uint8_t* host_start;
    int32_t  bulk_len;
    int32_t  success = 0;
    if ( p_rect == 0 || dst_address == 0 || dst_pitch == 0 )
    {
       return -1;
    }
    host_start = (uint8_t *)dst_address + (dst_pitch * p_rect->y);
    bulk_len   = (int32_t)dst_pitch * p_rect->height;
    // Now send the bulk transfer across
    // command parameters: resource handle, destination y, bulk length
    uint32_t param[] = { VC_HTOV32(handle), VC_HTOV32(p_rect->y), VC_HTOV32(bulk_len) };
    success = dispmanx_send_command( EDispmanBulkRead | DISPMANX_NO_REPLY_MASK, param, sizeof(param));
    if (success == 0)
    {
       lock_obtain();
       success = vchi_bulk_queue_receive(  dispmanx_client.client_handle[0],
                                           host_start,
                                           bulk_len,
                                           VCHI_FLAGS_BLOCK_UNTIL_OP_COMPLETE,
                                           0 );
       lock_release();
    }
    return (int) success;
 }
vc_dispmanx_resource_set_palette()
VCHPRE_ int VCHPOST_ vc_dispmanx_resource_set_palette (DISPMANX_RESOURCE_HANDLE_T handle, void * src_address, int offset, int size)
Definition at line 1029 of file vc_vchi_dispmanx.c.
References VC_HTOV32.
{
    //Note that x coordinate of the rect is NOT used
    //Address of data in host
    uint8_t *host_start = src_address;
    int32_t bulk_len = size, success = 0;
    //Now send the bulk transfer across
    //command parameters: resource size
    uint32_t param[] = {VC_HTOV32(handle), VC_HTOV32(offset), VC_HTOV32(bulk_len) };
    success = dispmanx_send_command(  EDispmanSetPalette | DISPMANX_NO_REPLY_MASK, param, sizeof(param));
    if(success == 0)
    {
       lock_obtain();
       success = vchi_bulk_queue_transmit( dispmanx_client.client_handle[0],
                                           host_start,
                                           bulk_len,
                                           VCHI_FLAGS_BLOCK_UNTIL_DATA_READ,
                                           NULL );
       lock_release();
    }
    return (int) success;
 }
vc_dispmanx_resource_write_data()
VCHPRE_ int VCHPOST_ vc_dispmanx_resource_write_data (DISPMANX_RESOURCE_HANDLE_T res, VC_IMAGE_TYPE_T src_type, int src_pitch, void * src_address, const VC_RECT_T * rect)
Definition at line 378 of file vc_vchi_dispmanx.c.
References tag_VC_RECT_T::height, VC_HTOV32, void(), and tag_VC_RECT_T::y.
{
     (void)src_type;
    //Note that x coordinate of the rect is NOT used
    //Address of data in host
    uint8_t *host_start = (uint8_t *)src_address + src_pitch * rect->y;
    int32_t bulk_len = src_pitch * rect->height, success = 0;
    //Now send the bulk transfer across
    //command parameters: resource handle, destination y, bulk length
    uint32_t param[] = {VC_HTOV32(handle), VC_HTOV32(rect->y), VC_HTOV32(bulk_len), VC_HTOV32(src_type) };
    success = dispmanx_send_command(  EDispmanBulkWrite | DISPMANX_NO_REPLY_MASK, param, sizeof(param));
    if(success == 0)
    {
       lock_obtain();
       success = vchi_bulk_queue_transmit( dispmanx_client.client_handle[0],
                                           host_start,
                                           bulk_len,
                                           VCHI_FLAGS_BLOCK_UNTIL_DATA_READ,
                                           NULL );
       lock_release();
    }
    return (int) success;
 }
vc_dispmanx_resource_write_data_handle()
VCHPRE_ int VCHPOST_ vc_dispmanx_resource_write_data_handle (DISPMANX_RESOURCE_HANDLE_T res, VC_IMAGE_TYPE_T src_type, int src_pitch, VCHI_MEM_HANDLE_T handle, uint32_t offset, const VC_RECT_T * rect)
vc_dispmanx_snapshot()
VCHPRE_ int VCHPOST_ vc_dispmanx_snapshot (DISPMANX_DISPLAY_HANDLE_T display, DISPMANX_RESOURCE_HANDLE_T snapshot_resource, DISPMANX_TRANSFORM_T transform)
Definition at line 999 of file vc_vchi_dispmanx.c.
 {
    uint32_t display_snapshot_param[] = {
       VC_HTOV32(display),
       VC_HTOV32(snapshot_resource),
       VC_HTOV32(transform)};
    int success = (int) dispmanx_send_command( EDispmanSnapshot,
                                               display_snapshot_param,
                                               sizeof(display_snapshot_param));
    return success;
 }
vc_dispmanx_stop()
VCHPRE_ void VCHPOST_ vc_dispmanx_stop (void)
Definition at line 233 of file vc_vchi_dispmanx.c.
References DISPMANX_SERVICE_T::initialised.
{
    // Wait for the current lock-holder to finish before zapping dispmanx.
    //TODO: kill the notifier task
    void *dummy;
    uint32_t i;
    if (!dispmanx_client.initialised)
       return;
    lock_obtain();
    for (i=0; i<dispmanx_client.num_connections; i++) {
       int32_t result;
       result = vchi_service_close(dispmanx_client.client_handle[i]);
       vcos_assert( result == 0 );
       result = vchi_service_close(dispmanx_client.notify_handle[i]);
       vcos_assert( result == 0 );
    }
    lock_release();
    dispmanx_client.initialised = 0;
    vcos_event_signal(&dispmanx_notify_available_event);
    vcos_thread_join(&dispmanx_notify_task, &dummy);
    vcos_mutex_delete(&dispmanx_client.lock);
    vcos_event_delete(&dispmanx_message_available_event);
    vcos_event_delete(&dispmanx_notify_available_event);
 }
vc_dispmanx_update_start()
VCHPRE_ DISPMANX_UPDATE_HANDLE_T VCHPOST_ vc_dispmanx_update_start (int32_t priority)
Definition at line 690 of file vc_vchi_dispmanx.c.
References VC_HTOV32.
Referenced by deinit(), graphics_update_start(), gx_priv_destroy_native_window(), and raspitexutil_create_native_window().
{
    uint32_t handle;
    priority = VC_HTOV32(priority);
    handle = dispmanx_get_handle(EDispmanUpdateStart,
                                          &priority, sizeof(priority));
    return (DISPMANX_UPDATE_HANDLE_T) handle;
 }
vc_dispmanx_update_submit()
VCHPRE_ int VCHPOST_ vc_dispmanx_update_submit (DISPMANX_UPDATE_HANDLE_T update, DISPMANX_CALLBACK_FUNC_T cb_func, void * cb_arg)
Definition at line 713 of file vc_vchi_dispmanx.c.
References DISPMANX_SERVICE_T::notify_handle, DISPMANX_SERVICE_T::pending_update_handle, DISPMANX_SERVICE_T::update_callback, DISPMANX_SERVICE_T::update_callback_param, VC_HTOV32, vchi_service_use(), and vcos_assert.
{
    uint32_t update_param[] = {(uint32_t) VC_HTOV32(update), (uint32_t) ((cb_func)? VC_HTOV32(1) : 0)};
    int success;
    vcos_assert(update); // handles must be non-zero
    if (update)
    {
       //Set the callback
       dispmanx_client.update_callback = cb_func;
       dispmanx_client.update_callback_param = cb_arg;
       dispmanx_client.pending_update_handle = update;
       vchi_service_use(dispmanx_client.notify_handle[0]); // corresponding release is in dispmanx_notify_func
       success = (int) dispmanx_send_command( EDispmanUpdateSubmit | DISPMANX_NO_REPLY_MASK,
                                              update_param, sizeof(update_param));
    }
    else
    {
       success = -1;
    }
    return success;
 }
vc_dispmanx_update_submit_sync()
VCHPRE_ int VCHPOST_ vc_dispmanx_update_submit_sync (DISPMANX_UPDATE_HANDLE_T update)
Definition at line 746 of file vc_vchi_dispmanx.c.
References VC_HTOV32.
Referenced by deinit(), graphics_update_end(), gx_priv_destroy_native_window(), gx_priv_finish_native_window(), and raspitexutil_create_native_window().
{
    int success;
    update = VC_HTOV32(update);
    success = (int) dispmanx_send_command( EDispmanUpdateSubmitSync,
                                           &update, sizeof(update));
    return success;
 }
vc_dispmanx_vsync_callback()
VCHPRE_ int VCHPOST_ vc_dispmanx_vsync_callback (DISPMANX_DISPLAY_HANDLE_T display, DISPMANX_CALLBACK_FUNC_T cb_func, void * cb_arg)
Definition at line 1067 of file vc_vchi_dispmanx.c.
 {
    // Steal the invalid 0 handle to indicate this is a vsync request
    DISPMANX_UPDATE_HANDLE_T update = 0;
    int enable = (cb_func != NULL);
    uint32_t update_param[] = {(uint32_t) VC_HTOV32(display), VC_HTOV32(update), (int32_t)enable};
    int success;
    // Set the callback
    dispmanx_client.vsync_callback = cb_func;
    dispmanx_client.vsync_callback_param = cb_arg;
    if (!dispmanx_client.vsync_enabled && enable) {
       // An extra "use" is required while a vsync callback is registered.
       // The corresponding "release" is below.
       vchi_service_use(dispmanx_client.notify_handle[0]);
    }
    success = (int) dispmanx_send_command( EDispmanVsyncCallback | DISPMANX_NO_REPLY_MASK,
                                           update_param, sizeof(update_param));
    if (dispmanx_client.vsync_enabled && !enable) {
       // The extra "use" added above is no longer required.
       vchi_service_release(dispmanx_client.notify_handle[0]);
    }
    dispmanx_client.vsync_enabled = enable;
    return (int) success;
 }
vc_vchi_dispmanx_init()
VCHPRE_ void VCHPOST_ vc_vchi_dispmanx_init (VCHI_INSTANCE_T initialise_instance, VCHI_CONNECTION_T ** connections, uint32_t num_connections)
Definition at line 148 of file vc_vchi_dispmanx.c.
References DISPMANX_CLIENT_NAME, DISPMANX_SERVICE_T::initialised, DISPMANX_SERVICE_T::lock, DISPMANX_SERVICE_T::num_connections, status, VC_DISPMANX_VERSION, VCHI_VERSION, vcos_assert, vcos_event_create(), vcos_mutex_create(), and VCOS_SUCCESS.
{
    VCOS_STATUS_T status;
    int32_t success;
    uint32_t i;
    if (dispmanx_client.initialised)
      return;
    // record the number of connections
    memset( &dispmanx_client, 0, sizeof(DISPMANX_SERVICE_T) );
    dispmanx_client.num_connections = num_connections;
    status = vcos_mutex_create(&dispmanx_client.lock, "HDispmanx");
    vcos_assert(status == VCOS_SUCCESS);
    status = vcos_event_create(&dispmanx_message_available_event, "HDispmanx");
    vcos_assert(status == VCOS_SUCCESS);
    status = vcos_event_create(&dispmanx_notify_available_event, "HDispmanx");
    vcos_assert(status == VCOS_SUCCESS);
    dispmanx_client.initialised = 1;
    for (i=0; i<dispmanx_client.num_connections; i++) {
       VCOS_THREAD_ATTR_T attrs;
       // Create a 'Client' service on the each of the connections
       SERVICE_CREATION_T dispmanx_parameters = { VCHI_VERSION(VC_DISPMANX_VERSION),
                                                  DISPMANX_CLIENT_NAME,     // 4cc service code
                                                  connections[i],           // passed in fn ptrs
                                                  0,                        // tx fifo size (unused)
                                                  0,                        // tx fifo size (unused)
                                                  &dispmanx_client_callback, // service callback
                                                  &dispmanx_message_available_event,  // callback parameter
                                                  VC_FALSE,                  // want_unaligned_bulk_rx
                                                  VC_FALSE,                  // want_unaligned_bulk_tx
                                                  VC_FALSE,                  // want_crc
                                                  };
       SERVICE_CREATION_T dispmanx_parameters2 = { VCHI_VERSION(VC_DISPMANX_VERSION),
                                                   DISPMANX_NOTIFY_NAME,   // 4cc service code
                                                   connections[i],           // passed in fn ptrs
                                                   0,                        // tx fifo size (unused)
                                                   0,                        // tx fifo size (unused)
                                                   &dispmanx_notify_callback, // service callback
                                                   &dispmanx_notify_available_event,  // callback parameter
                                                   VC_FALSE,                  // want_unaligned_bulk_rx
                                                   VC_FALSE,                  // want_unaligned_bulk_tx
                                                   VC_FALSE,                  // want_crc
                                                    };
       success = vchi_service_open( initialise_instance, &dispmanx_parameters, &dispmanx_client.client_handle[i] );
       vcos_assert( success == 0 );
       // Create the async service of dispman to handle update callback
       success = vchi_service_open( initialise_instance, &dispmanx_parameters2, &dispmanx_client.notify_handle[i] );
       vcos_assert( success == 0 );
       //Create the notifier task
       vcos_thread_attr_init(&attrs);
       vcos_thread_attr_setstacksize(&attrs, 2048);
       vcos_thread_attr_settimeslice(&attrs, 1);
       status = vcos_thread_create(&dispmanx_notify_task, "HDispmanx Notify", &attrs, dispmanx_notify_func, NULL);
       vcos_assert(status == VCOS_SUCCESS);
       // release services until they're actually used
       vchi_service_release(dispmanx_client.client_handle[i]);
       vchi_service_release(dispmanx_client.notify_handle[i]);
    }
 }