VideoCore Library: host_applications/linux/apps/dtoverlay/utils.c File Reference
utils.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <stdarg.h>
#include <sys/stat.h>
#include <errno.h>
#include "utils.h"
Classes
struct overlay_help_state_struct
Macros
#define OVERLAY_HELP_INDENT 8
Functions
OVERLAY_HELP_STATE_T * overlay_help_open (const char *helpfile)
void overlay_help_close (OVERLAY_HELP_STATE_T *state)
int overlay_help_find (OVERLAY_HELP_STATE_T *state, const char *name)
int overlay_help_find_field (OVERLAY_HELP_STATE_T *state, const char *field)
const char * overlay_help_field_data (OVERLAY_HELP_STATE_T *state)
void overlay_help_print_field (OVERLAY_HELP_STATE_T *state, const char *field, const char *label, int indent, int strip_blanks)
int run_cmd (const char *fmt,...)
void free_string (const char *string)
void free_strings (void)
char * sprintf_dup (const char *fmt,...)
char * vsprintf_dup (const char *fmt, va_list ap)
int dir_exists (const char *dirname)
int file_exists (const char *dirname)
void string_vec_init (STRING_VEC_T *vec)
char * string_vec_add (STRING_VEC_T *vec, const char *str, int len)
int string_vec_find (STRING_VEC_T *vec, const char *str, int len)
int string_vec_compare (const void *a, const void *b)
void string_vec_sort (STRING_VEC_T *vec)
void string_vec_uninit (STRING_VEC_T *vec)
int error (const char *fmt,...)
void fatal_error (const char *fmt,...)
Variables
int opt_verbose
int opt_dry_run
Macro Definition Documentation
OVERLAY_HELP_INDENT
#define OVERLAY_HELP_INDENT 8
Definition at line 38 of file utils.c.
Function Documentation
dir_exists()
int dir_exists (const char * dirname)
Definition at line 356 of file utils.c.
 {
     struct stat finfo;
     return (stat(dirname, &finfo) == 0) && S_ISDIR(finfo.st_mode);
 }
error()
int error (const char * fmt, ...)
Definition at line 443 of file utils.c.
Referenced by asf_reader_open(), asf_writer_open(), audioplay_create(), audioplay_delete(), audioplay_get_latency(), audioplay_play_buffer(), audioplay_set_dest(), avi_writer_open(), CONFIGURATION_T::CONFIGURATION_T(), dummy_writer_open(), flv_reader_open(), ilclient_cleanup_components(), ilclient_disable_port(), ilclient_disable_port_buffers(), ilclient_disable_tunnel(), ilclient_enable_port(), ilclient_enable_port_buffers(), ilclient_flush_tunnels(), ilclient_setup_tunnel(), ilclient_suggest_bufsize(), ilclient_teardown_tunnels(), main(), mkv_reader_open(), mmal_connection_create(), mmal_list_create(), mmal_port_event_get(), mmal_port_parameter_alloc_get(), mmal_vc_send_message(), mmal_wrapper_create(), mmalomx_buffer_send(), mp4_reader_open(), mp4_writer_open(), mpga_reader_open(), platform_match_pixmap_api_support(), ps_reader_open(), raspitex_init(), raspitexutil_create_native_window(), rawvideo_reader_open(), rawvideo_writer_open(), rcv_reader_open(), rtsp_reader_open(), simple_writer_open(), vc_container_filter_open(), vc_container_index_create(), vc_container_io_file_open(), vc_container_io_http_open(), vc_container_net_accept(), vc_container_net_open(), vc_container_open_reader_with_io(), vc_container_open_writer(), vc_packetizer_open(), vc_tv_hdmi_get_supported_modes_new_id(), vcil_in_free_buffer(), vcil_in_use_buffer(), and wav_reader_open().
 {
     va_list ap;
     fprintf(stderr, "* ");
     va_start(ap, fmt);
     vfprintf(stderr, fmt, ap);
     va_end(ap);
     fprintf(stderr, "\n");
     return 1;
 }
fatal_error()
void fatal_error (const char * fmt, ...)
Definition at line 454 of file utils.c.
Referenced by string_vec_add(), and vsprintf_dup().
 {
     va_list ap;
     fprintf(stderr, "* ");
     va_start(ap, fmt);
     vfprintf(stderr, fmt, ap);
     va_end(ap);
     fprintf(stderr, "\n");
     exit(1);
 }
file_exists()
int file_exists (const char * dirname)
Definition at line 362 of file utils.c.
 {
     struct stat finfo;
     return (stat(dirname, &finfo) == 0) && S_ISREG(finfo.st_mode);
 }
free_string()
void free_string (const char * string)
Definition at line 277 of file utils.c.
References string_struct::next, NULL, string_struct::prev, and str.
Referenced by run_cmd().
 {
     STRING_T *str;
     if (!string)
     return;
     str = (STRING_T *)(string - sizeof(STRING_T));
     if (str == allocated_strings)
     {
     allocated_strings = str->next;
     if (allocated_strings == str)
         allocated_strings = NULL;
     }
     str->prev->next = str->next;
     str->next->prev = str->prev;
     free(str);
 }
free_strings()
void free_strings (void)
Definition at line 297 of file utils.c.
References str.
 {
     if (allocated_strings)
     {
     STRING_T *str = allocated_strings;
     do
     {
         STRING_T *t = str;
         str = t->next;
         free(t);
     } while (str != allocated_strings);
     allocated_strings = NULL;
     }
 }
overlay_help_close()
void overlay_help_close (OVERLAY_HELP_STATE_T * state)
Definition at line 74 of file utils.c.
 {
     fclose(state->fp);
     free(state);
 }
overlay_help_field_data()
const char* overlay_help_field_data (OVERLAY_HELP_STATE_T * state)
Definition at line 138 of file utils.c.
 {
     int line_len, pos;
     if (state->end_of_field)
         return NULL;
     line_len = state->line_len;
     if ((state->line_pos < 0) ||
         (state->line_pos >= line_len))
     {
         line_len = overlay_help_get_line(state);
         /* Fields end at the start of the next field or the end of the record */
         if ((line_len < 0) || (state->line_buf[0] != ' '))
         {
             state->end_of_field = 1;
             return NULL;
         }
         if (line_len == 0)
             return "";
     }
     /* Return field data starting at OVERLAY_HELP_INDENT, if there is any */
     pos = line_len;
     if (pos > OVERLAY_HELP_INDENT)
         pos = OVERLAY_HELP_INDENT;
     state->line_pos = -1;
     return &state->line_buf[pos];
 }
overlay_help_find()
int overlay_help_find (OVERLAY_HELP_STATE_T * state, const char * name)
Definition at line 80 of file utils.c.
 {
     state->line_pos = -1;
     state->rec_pos = -1;
     state->blank_count = 0;
     fseek(state->fp, 0, SEEK_SET);
     while (overlay_help_find_field(state, "Name"))
     {
         const char *overlay = overlay_help_field_data(state);
         if (overlay && (strcmp(overlay, name) == 0))
         {
             state->rec_pos = (long)ftell(state->fp);
             return 1;
         }
     }
     return 0;
 }
overlay_help_find_field()
int overlay_help_find_field (OVERLAY_HELP_STATE_T * state, const char * field)
Definition at line 101 of file utils.c.
 {
     int field_len = strlen(field);
     int found = 0;
     if (state->rec_pos >= 0)
         fseek(state->fp, state->rec_pos, SEEK_SET);
     while (!found)
     {
         int line_len = overlay_help_get_line(state);
         if (line_len < 0)
             break;
         /* Check for the "<field>:" prefix */
         if ((line_len >= (field_len + 1)) &&
             (state->line_buf[field_len] == ':') &&
             (memcmp(state->line_buf, field, field_len) == 0))
         {
             /* Found it
                If this initial line has no content then skip it */
             if (line_len > OVERLAY_HELP_INDENT)
                 state->line_pos = OVERLAY_HELP_INDENT;
             else
                 state->line_pos = -1;
             state->end_of_field = 0;
             found = 1;
         }
         else
         {
             state->line_pos = -1;
         }
     }
     return found;
 }
overlay_help_open()
OVERLAY_HELP_STATE_T* overlay_help_open (const char * helpfile)
Definition at line 57 of file utils.c.
 {
     OVERLAY_HELP_STATE_T *state = NULL;
     FILE *fp = fopen(helpfile, "r");
     if (fp)
     {
         state = calloc(1, sizeof(OVERLAY_HELP_STATE_T));
         if (!state)
                 fatal_error("Out of memory");
         state->fp = fp;
         state->line_pos = -1;
         state->rec_pos = -1;
     }
     return state;
 }
overlay_help_print_field()
void overlay_help_print_field (OVERLAY_HELP_STATE_T * state, const char * field, const char * label, int indent, int strip_blanks)
Definition at line 172 of file utils.c.
 {
     if (!overlay_help_find_field(state, field))
         return;
     while (1)
     {
     const char *line = overlay_help_field_data(state);
     if (!line)
         break;
     if (label)
     {
         int spaces = indent - strlen(label);
         if (spaces < 0)
         spaces = 0;
         printf("%s%*s%s\n", label, spaces, "", line);
         label = NULL;
     }
     else if (line[0])
     {
         printf("%*s%s\n", indent, "", line);
     }
     else if (!strip_blanks)
     {
         printf("\n");
     }
     }
     if (!strip_blanks)
     printf("\n");
 }
run_cmd()
int run_cmd (const char * fmt, ...)
Definition at line 256 of file utils.c.
References free_string(), opt_dry_run, opt_verbose, and vsprintf_dup().
 {
     va_list ap;
     char *cmd;
     int ret;
     va_start(ap, fmt);
     cmd = vsprintf_dup(fmt, ap);
     va_end(ap);
     if (opt_dry_run || opt_verbose)
     fprintf(stderr, "run_cmd: %s\n", cmd);
     ret = opt_dry_run ? 0 : system(cmd);
     free_string(cmd);
     return ret;
 }
sprintf_dup()
char* sprintf_dup (const char * fmt, ...)
Definition at line 313 of file utils.c.
References str, and vsprintf_dup().
 {
     va_list ap;
     char *str;
     va_start(ap, fmt);
     str = vsprintf_dup(fmt, ap);
     va_end(ap);
     return str;
 }
string_vec_add()
char* string_vec_add (STRING_VEC_T * vec, const char * str, int len)
Definition at line 375 of file utils.c.
References fatal_error(), len, string_vec_struct::max_strings, string_vec_struct::num_strings, and string_vec_struct::strings.
Referenced by dtparam_callback().
 {
     char *copy;
     if (vec->num_strings == vec->max_strings)
     {
     if (vec->max_strings)
         vec->max_strings *= 2;
     else
         vec->max_strings = 16;
     vec->strings = realloc(vec->strings, vec->max_strings * sizeof(const char *));
     if (!vec->strings)
         fatal_error("Out of memory");
     }
     if (len)
     {
     copy = malloc(len + 1);
     strncpy(copy, str, len);
     copy[len] = '\0';
     }
     else
        copy = strdup(str);
     if (!copy)
     fatal_error("Out of memory");
     vec->strings[vec->num_strings++] = copy;
     return copy;
 }
string_vec_compare()
int string_vec_compare (const void * a, const void * b)
Definition at line 425 of file utils.c.
Referenced by string_vec_sort().
 {
     return strcmp(*(const char **)a, *(const char **)b);
 }
string_vec_find()
int string_vec_find (STRING_VEC_T * vec, const char * str, int len)
Definition at line 406 of file utils.c.
References string_vec_struct::num_strings, and string_vec_struct::strings.
Referenced by dtparam_callback().
 {
     int i;
     for (i = 0; i < vec->num_strings; i++)
     {
     if (len)
     {
         if ((strncmp(vec->strings[i], str, len) == 0) &&
         (vec->strings[i][len] == '\0'))
         return i;
     }
     else if (strcmp(vec->strings[i], str) == 0)
         return i;
     }
     return -1;
 }
string_vec_init()
void string_vec_init (STRING_VEC_T * vec)
Definition at line 368 of file utils.c.
References string_vec_struct::max_strings, NULL, string_vec_struct::num_strings, and string_vec_struct::strings.
 {
     vec->num_strings = 0;
     vec->max_strings = 0;
     vec->strings = NULL;
 }
string_vec_sort()
void string_vec_sort (STRING_VEC_T * vec)
Definition at line 430 of file utils.c.
References string_vec_struct::num_strings, string_vec_compare(), and string_vec_struct::strings.
 {
     qsort(vec->strings, vec->num_strings, sizeof(char *), &string_vec_compare);
 }
string_vec_uninit()
void string_vec_uninit (STRING_VEC_T * vec)
Definition at line 435 of file utils.c.
References string_vec_struct::num_strings, and string_vec_struct::strings.
 {
     int i;
     for (i = 0; i < vec->num_strings; i++)
     free(vec->strings[i]);
     free(vec->strings);
 }
vsprintf_dup()
char* vsprintf_dup (const char * fmt, va_list ap)
Definition at line 324 of file utils.c.
References string_struct::data, fatal_error(), len, string_struct::next, and str.
Referenced by run_cmd(), and sprintf_dup().
 {
     char scratch[512];
     int len;
     STRING_T *str;
     len = vsnprintf(scratch, sizeof(scratch), fmt, ap) + 1;
     if (len > sizeof(scratch))
     fatal_error("Maximum string length exceeded");
     str = malloc(sizeof(STRING_T) + len);
     if (!str)
     fatal_error("Out of memory");
     memcpy(str->data, scratch, len);
     if (allocated_strings)
     {
     str->next = allocated_strings;
     str->prev = allocated_strings->prev;
     str->next->prev = str;
     str->prev->next = str;
     }
     else
     {
     str->next = str;
     str->prev = str;
     allocated_strings = str;
     }
     return str->data;
 }
Variable Documentation
opt_dry_run
int opt_dry_run
Definition at line 41 of file utils.c.
Referenced by run_cmd().
opt_verbose
int opt_verbose
Definition at line 40 of file utils.c.
Referenced by run_cmd().