VideoCore Library: containers/core/containers_bits.c File Reference
containers_bits.c File Reference
#include "containers/core/containers_bits.h"
#include "containers/core/containers_common.h"
Functions
void vc_container_bits_init (VC_CONTAINER_BITS_T *bit_stream, const uint8_t *buffer, uint32_t available)
uint32_t vc_container_bits_invalidate (VC_CONTAINER_BITS_T *bit_stream)
bool vc_container_bits_valid (VC_CONTAINER_BITS_T *bit_stream)
void vc_container_bits_reset (VC_CONTAINER_BITS_T *bit_stream)
const uint8_t * vc_container_bits_current_pointer (const VC_CONTAINER_BITS_T *bit_stream)
void vc_container_bits_copy_stream (VC_CONTAINER_BITS_T *dst, const VC_CONTAINER_BITS_T *src)
uint32_t vc_container_bits_available (const VC_CONTAINER_BITS_T *bit_stream)
uint32_t vc_container_bits_bytes_available (const VC_CONTAINER_BITS_T *bit_stream)
void vc_container_bits_skip (VC_CONTAINER_BITS_T *bit_stream, uint32_t bits_to_skip)
void vc_container_bits_skip_bytes (VC_CONTAINER_BITS_T *bit_stream, uint32_t bytes_to_skip)
void vc_container_bits_reduce_bytes (VC_CONTAINER_BITS_T *bit_stream, uint32_t bytes_to_reduce)
void vc_container_bits_copy_bytes (VC_CONTAINER_BITS_T *bit_stream, uint32_t bytes_to_copy, uint8_t *dst)
uint32_t vc_container_bits_read_u32 (VC_CONTAINER_BITS_T *bit_stream, uint32_t value_bits)
void vc_container_bits_skip_exp_golomb (VC_CONTAINER_BITS_T *bit_stream)
uint32_t vc_container_bits_read_u32_exp_golomb (VC_CONTAINER_BITS_T *bit_stream)
int32_t vc_container_bits_read_s32_exp_golomb (VC_CONTAINER_BITS_T *bit_stream)
Function Documentation
vc_container_bits_available()
uint32_t vc_container_bits_available (const VC_CONTAINER_BITS_T * bit_stream)
Return the number of bits left to take from the stream. If the stream is invalid, zero is returned.
Precondition
bit_stream is not NULL.
Parameters
bit_stream The bit stream object.
Returns
The number of bits left to take.
Definition at line 222 of file containers_bits.c.
References vc_container_bits_tag::bits, vc_container_bits_tag::buffer, and vc_container_bits_tag::bytes.
Referenced by vc_container_bits_bytes_available(), vc_container_bits_read_u32(), and vc_container_bits_skip().
 {
    if (!bit_stream->buffer)
       return 0;
    return (bit_stream->bytes << 3) + bit_stream->bits;
 }
vc_container_bits_bytes_available()
uint32_t vc_container_bits_bytes_available (const VC_CONTAINER_BITS_T * bit_stream)
Return the number of bytes left to take from the stream. If the stream is invalid, zero is returned.
Precondition
bit_stream is not NULL.
Parameters
bit_stream The bit stream object.
Returns
The number of bytes left to take.
Definition at line 230 of file containers_bits.c.
References vc_container_bits_tag::bits, vc_container_bits_tag::buffer, vc_container_assert, and vc_container_bits_available().
 {
    if (!bit_stream->buffer)
       return 0;
    vc_container_assert(!bit_stream->bits);
    return vc_container_bits_available(bit_stream) >> 3;
 }
vc_container_bits_copy_bytes()
void vc_container_bits_copy_bytes (VC_CONTAINER_BITS_T * bit_stream, uint32_t bytes_to_copy, uint8_t * dst)
Copies a number of bytes from the stream to a byte buffer. If the stream is or becomes invalid, no data is copied.
Precondition
bit_stream is not NULL.
The stream is on a byte boundary.
Parameters
bit_stream The bit stream object.
bytes_to_copy The number of bytes to copy.
dst The byte buffer destination.
Definition at line 282 of file containers_bits.c.
References vc_container_bits_tag::bits, vc_container_bits_tag::buffer, vc_container_bits_tag::bytes, vc_container_assert, and vc_container_bits_invalidate().
 {
    vc_container_assert(!bit_stream->bits);
    if (bit_stream->bytes < bytes_to_copy)
    {
       /* Not enough data */
       vc_container_bits_invalidate(bit_stream);
       return;
    }
    /* When the number of bits is zero, the next byte to take is at buffer + 1 */
    memcpy(dst, bit_stream->buffer + 1, bytes_to_copy);
    bit_stream->buffer += bytes_to_copy;
    bit_stream->bytes -= bytes_to_copy;
 }
vc_container_bits_copy_stream()
void vc_container_bits_copy_stream (VC_CONTAINER_BITS_T * dst, const VC_CONTAINER_BITS_T * src)
Copy one bit stream to another. If the source stream is invalid, the destination one will become so as well.
Precondition
Neither bit stream is NULL.
Parameters
dst The destination bit stream object.
src The source bit stream object.
Definition at line 215 of file containers_bits.c.
 {
    memcpy(dst, src, sizeof(VC_CONTAINER_BITS_T));
 }
vc_container_bits_current_pointer()
const uint8_t* vc_container_bits_current_pointer (const VC_CONTAINER_BITS_T * bit_stream)
Return the current byte pointer for the bit stream.
Precondition
bit_stream is not NULL.
The stream is on a byte boundary.
Parameters
bit_stream The bit stream object.
Returns
The current byte pointer, or NULL if the stream is invalid.
Definition at line 204 of file containers_bits.c.
References vc_container_bits_tag::bits, vc_container_bits_tag::buffer, NULL, and vc_container_assert.
 {
    const uint8_t *buffer = bit_stream->buffer;
    /* Only valid on byte boundaries, where buffer pointer has not been moved yet */
    vc_container_assert(!bit_stream->bits);
    return buffer ? (buffer + 1) : NULL;
 }
vc_container_bits_init()
void vc_container_bits_init (VC_CONTAINER_BITS_T * bit_stream, const uint8_t * buffer, uint32_t available)
Initialise a bit stream object.
Precondition
bit_stream is not NULL.
Parameters
bit_stream The bit stream object to initialise.
buffer Pointer to the start of the byte buffer.
available Number of bytes in the bit stream.
Definition at line 170 of file containers_bits.c.
References vc_container_bits_tag::bits, vc_container_bits_tag::buffer, vc_container_bits_tag::bytes, and vc_container_assert.
 {
    vc_container_assert(buffer && (buffer != (const uint8_t *)1));
    /* Start with buffer pointing at the previous byte with no bits available
     * to make the mathematics easier */
    bit_stream->buffer = buffer - 1;
    bit_stream->bytes = available;
    bit_stream->bits = 0;
 }
vc_container_bits_invalidate()
uint32_t vc_container_bits_invalidate (VC_CONTAINER_BITS_T * bit_stream)
Invalidates the bit stream. Also returns zero, because it allows callers that need to invalidate and immediately return zero to do so in a single statement.
Precondition
bit_stream is not NULL.
Parameters
bit_stream The bit stream object.
Returns
Zero, always.
Definition at line 184 of file containers_bits.c.
References vc_container_bits_tag::buffer, and NULL.
Referenced by vc_container_bits_copy_bytes(), vc_container_bits_read_s32_exp_golomb(), vc_container_bits_read_u32(), vc_container_bits_reduce_bytes(), and vc_container_bits_skip().
 {
    bit_stream->buffer = NULL;
    return 0;
 }
vc_container_bits_read_s32_exp_golomb()
int32_t vc_container_bits_read_s32_exp_golomb (VC_CONTAINER_BITS_T * bit_stream)
Returns the next signed Exp-Golomb value from the stream. See section 9.1.1 of ITU-T REC H.264 201003 for details. If there are not enough bits in the stream to complete an Exp-Golomb value, the stream becomes invalid. If the next signed Exp-Golomb value in the stream is larger than 32 bits, or the stream is or becomes invalid, zero is returned.
Precondition
bit_stream is not NULL.
Parameters
bit_stream The bit stream object.
Returns
The next signed value from the stream, or zero on error.
Definition at line 376 of file containers_bits.c.
References vc_container_assert, vc_container_bits_invalidate(), vc_container_bits_read_u32_exp_golomb(), vc_container_log(), VC_CONTAINER_LOG_FORMAT, and VC_CONTAINER_PARAM_UNUSED.
 {
    uint32_t uval;
    uval = vc_container_bits_read_u32_exp_golomb(bit_stream);
    /* The signed Exp-Golomb code 0xFFFFFFFF cannot be represented as a signed 32-bit
     * integer, because it should be one larger than the largest positive value. */
    if (uval == 0xFFFFFFFF)
       return vc_container_bits_invalidate(bit_stream);
    /* Definition of conversion is
     *    s = ((-1)^(u + 1)) * Ceil(u / 2)
     * where '^' is power, but this should be equivalent */
    return ((int32_t)((uval & 1) << 1) - 1) * (int32_t)((uval >> 1) + (uval & 1));
 }
vc_container_bits_read_u32()
uint32_t vc_container_bits_read_u32 (VC_CONTAINER_BITS_T * bit_stream, uint32_t value_bits)
Returns the next value_bits from the stream. The last bit will be the least significant bit in the returned value. If value_bits is greater than the number of bits available in the stream, the stream becomes invalid. If the stream is invalid, or becomes invalid while reading the value, zero is returned.
Precondition
bit_stream is not NULL.
value_bits is not larger than 32.
Parameters
bit_stream The bit stream object.
value_bits The number of bits to retrieve.
Returns
The value read from the stream, or zero if the stream is invalid.
Definition at line 302 of file containers_bits.c.
References vc_container_bits_tag::bits, vc_container_bits_tag::buffer, vc_container_bits_tag::bytes, vc_container_assert, vc_container_bits_available(), and vc_container_bits_invalidate().
 {
    uint32_t value = 0;
    uint32_t needed = value_bits;
    uint32_t bits;
    vc_container_assert(value_bits <= 32);
    if (needed > vc_container_bits_available(bit_stream))
       return vc_container_bits_invalidate(bit_stream);
    bits = bit_stream->bits;
    while (needed)
    {
       uint32_t take;
       if (!bits)
       {
          bit_stream->bytes--;
          bit_stream->buffer++;
          bits = 8;
       }
       take = bits;
       if (needed < take) take = needed;
       bits -= take;
       needed -= take;
       value <<= take;
       if (take == 8)
          value |= *bit_stream->buffer;  /* optimize whole byte case */
       else
          value |= (*bit_stream->buffer >> bits) & ((1 << take) - 1);
    }
    bit_stream->bits = bits;
    return value;
 }
vc_container_bits_read_u32_exp_golomb()
uint32_t vc_container_bits_read_u32_exp_golomb (VC_CONTAINER_BITS_T * bit_stream)
Returns the next unsigned Exp-Golomb value from the stream. See section 9.1 of ITU-T REC H.264 201003 for details. If there are not enough bits in the stream to complete an Exp-Golomb value, the stream becomes invalid. If the next unsigned Exp-Golomb value in the stream is larger than 32 bits, or the stream is or becomes invalid, zero is returned.
Precondition
bit_stream is not NULL.
Parameters
bit_stream The bit stream object.
Returns
The next unsigned value from the stream, or zero on error.
Definition at line 350 of file containers_bits.c.
Referenced by vc_container_bits_read_s32_exp_golomb().
 {
    uint32_t leading_zero_bits;
    uint32_t codeNum;
    leading_zero_bits = vc_container_bits_get_leading_zero_bits(bit_stream);
    /* Anything bigger than 32 bits is definitely overflow */
    if (leading_zero_bits > 32)
       return vc_container_bits_invalidate(bit_stream);
    codeNum = vc_container_bits_read_u32(bit_stream, leading_zero_bits);
    if (leading_zero_bits == 32)
    {
       /* If codeNum is non-zero, it would need 33 bits, so is also overflow */
       if (codeNum)
          return vc_container_bits_invalidate(bit_stream);
       return 0xFFFFFFFF;
    }
    return codeNum + (1 << leading_zero_bits) - 1;
 }
vc_container_bits_reduce_bytes()
void vc_container_bits_reduce_bytes (VC_CONTAINER_BITS_T * bit_stream, uint32_t bytes_to_reduce)
Reduce the length of the bit stream by a number of bytes. This reduces the number of bits/bytes available without changing the current position in the stream. If bytes_to_reduce is greater than the number of bytes available in the stream, the stream becomes invalid. If the stream is already invalid, this has no effect.
Precondition
bit_stream is not NULL.
Parameters
bit_stream The bit stream object.
bytes_to_reduce The number of bytes by which to reduce the stream.
Definition at line 272 of file containers_bits.c.
References vc_container_bits_tag::bytes, and vc_container_bits_invalidate().
 {
    if (bit_stream->bytes >= bytes_to_reduce)
       bit_stream->bytes -= bytes_to_reduce;
    else
       vc_container_bits_invalidate(bit_stream);
 }
vc_container_bits_reset()
void vc_container_bits_reset (VC_CONTAINER_BITS_T * bit_stream)
Reset a valid bit stream object to appear empty. Once a stream has become invalid, reset has no effect.
Precondition
bit_stream is not NULL.
Parameters
bit_stream The bit stream object.
Definition at line 197 of file containers_bits.c.
References vc_container_bits_tag::bits, and vc_container_bits_tag::bytes.
 {
    bit_stream->bytes = 0;
    bit_stream->bits = 0;
 }
vc_container_bits_skip()
void vc_container_bits_skip (VC_CONTAINER_BITS_T * bit_stream, uint32_t bits_to_skip)
Skip past a number of bits in the stream. If bits_to_skip is greater than the number of bits available in the stream, the stream becomes invalid. If the stream is already invalid, this has no effect.
Precondition
bit_stream is not NULL.
Parameters
bit_stream The bit stream object.
bits_to_skip The number of bits to skip.
Definition at line 241 of file containers_bits.c.
References vc_container_bits_tag::bits, vc_container_bits_tag::buffer, vc_container_bits_tag::bytes, vc_container_bits_available(), and vc_container_bits_invalidate().
Referenced by vc_container_bits_skip_bytes(), and vc_container_bits_skip_exp_golomb().
 {
    uint32_t have_bits;
    uint32_t new_bytes;
    have_bits = vc_container_bits_available(bit_stream);
    if (have_bits < bits_to_skip)
    {
       vc_container_bits_invalidate(bit_stream);
       return;
    }
    have_bits -= bits_to_skip;
    new_bytes = have_bits >> 3;
    bit_stream->bits = have_bits & 7;
    bit_stream->buffer += (bit_stream->bytes - new_bytes);
    bit_stream->bytes = new_bytes;
 }
vc_container_bits_skip_bytes()
void vc_container_bits_skip_bytes (VC_CONTAINER_BITS_T * bit_stream, uint32_t bytes_to_skip)
Skip past a number of bytes in the stream. If bytes_to_skip is greater than the number of bytes available in the stream, the stream becomes invalid. If the stream is already invalid, this has no effect.
Precondition
bit_stream is not NULL.
The stream is on a byte boundary.
Parameters
bit_stream The bit stream object.
bytes_to_skip The number of bytes to skip.
Definition at line 262 of file containers_bits.c.
References vc_container_bits_tag::bits, vc_container_assert, and vc_container_bits_skip().
 {
    /* Only valid on byte boundaries */
    vc_container_assert(!bit_stream->bits);
    vc_container_bits_skip(bit_stream, bytes_to_skip << 3);
 }
vc_container_bits_skip_exp_golomb()
void vc_container_bits_skip_exp_golomb (VC_CONTAINER_BITS_T * bit_stream)
Skips the next Exp-Golomb value in the stream. See section 9.1 of ITU-T REC H.264 201003 for details. If there are not enough bits in the stream to complete an Exp-Golomb value, the stream becomes invalid. If the stream is already invalid, this has no effect.
Precondition
bit_stream is not NULL.
Parameters
bit_stream The bit stream object.
Definition at line 344 of file containers_bits.c.
References vc_container_bits_skip().
 {
    vc_container_bits_skip(bit_stream, vc_container_bits_get_leading_zero_bits(bit_stream));
 }
vc_container_bits_valid()
bool vc_container_bits_valid (VC_CONTAINER_BITS_T * bit_stream)
Returns true if the bit stream is currently valid. The stream becomes invalid when a read or skip operation goe beyond the end of the stream.
Precondition
bit_stream is not NULL.
Parameters
bit_stream The bit stream object.
Returns
True if the stream is valid, false if it is invalid.
Definition at line 191 of file containers_bits.c.
References vc_container_bits_tag::buffer, and NULL.
 {
    return (bit_stream->buffer != NULL);
 }