VideoCore Library: opensrc/helpers/libfdt/fdt_wip.c File Reference
fdt_wip.c File Reference
#include "libfdt_env.h"
#include <fdt.h>
#include <libfdt.h>
#include "libfdt_internal.h"
Functions
int fdt_setprop_inplace_namelen_partial (void *fdt, int nodeoffset, const char *name, int namelen, uint32_t idx, const void *val, int len)
int fdt_setprop_inplace (void *fdt, int nodeoffset, const char *name, const void *val, int len)
int fdt_nop_property (void *fdt, int nodeoffset, const char *name)
int fdt_node_end_offset_ (void *fdt, int offset)
int fdt_nop_node (void *fdt, int nodeoffset)
Function Documentation
fdt_node_end_offset_()
int fdt_node_end_offset_ (void * fdt, int offset)
Definition at line 73 of file fdt_wip.c.
References fdt_next_node(), and offset.
Referenced by fdt_del_node(), and fdt_nop_node().
 {
     int depth = 0;
     while ((offset >= 0) && (depth >= 0))
         offset = fdt_next_node(fdt, offset, &depth);
     return offset;
 }
fdt_nop_node()
int fdt_nop_node (void * fdt, int nodeoffset)
fdt_nop_node - replace a node (subtree) with nop tags : pointer to the device tree blob : offset of the node to nop
fdt_nop_node() will replace a given node's representation in the blob, including all its subnodes, if any, with FDT_NOP tags, effectively removing it from the tree.
This function will alter only the bytes in the blob which contain the node and its properties and subnodes, and will not alter or move any other part of the tree.
returns: 0, on success -FDT_ERR_BADOFFSET, nodeoffset did not point to FDT_BEGIN_NODE tag -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, -FDT_ERR_TRUNCATED, standard meanings
Definition at line 83 of file fdt_wip.c.
References fdt_node_end_offset_().
 {
     int endoffset;
     endoffset = fdt_node_end_offset_(fdt, nodeoffset);
     if (endoffset < 0)
         return endoffset;
     fdt_nop_region_(fdt_offset_ptr_w(fdt, nodeoffset, 0),
             endoffset - nodeoffset);
     return 0;
 }
fdt_nop_property()
int fdt_nop_property (void * fdt, int nodeoffset, const char * name)
Definition at line 59 of file fdt_wip.c.
References len.
 {
     struct fdt_property *prop;
     int len;
     prop = fdt_get_property_w(fdt, nodeoffset, name, &len);
     if (!prop)
         return len;
     fdt_nop_region_(prop, len + sizeof(*prop));
     return 0;
 }
fdt_setprop_inplace()
int fdt_setprop_inplace (void * fdt, int nodeoffset, const char * name, const void * val, int len)
Definition at line 33 of file fdt_wip.c.
References FDT_ERR_NOSPACE, fdt_getprop(), and fdt_setprop_inplace_namelen_partial().
Referenced by dtoverlay_dup_property().
 {
     const void *propval;
     int proplen;
     propval = fdt_getprop(fdt, nodeoffset, name, &proplen);
     if (!propval)
         return proplen;
     if (proplen != len)
         return -FDT_ERR_NOSPACE;
     return fdt_setprop_inplace_namelen_partial(fdt, nodeoffset, name,
                            strlen(name), 0,
                            val, len);
 }
fdt_setprop_inplace_namelen_partial()
int fdt_setprop_inplace_namelen_partial (void * fdt, int nodeoffset, const char * name, int namelen, uint32_t idx, const void * val, int len)
Definition at line 13 of file fdt_wip.c.
Referenced by fdt_setprop_inplace().
 {
     void *propval;
     int proplen;
     propval = fdt_getprop_namelen_w(fdt, nodeoffset, name, namelen,
                     &proplen);
     if (!propval)
         return proplen;
     if (proplen < (len + idx))
         return -FDT_ERR_NOSPACE;
     memcpy((char *)propval + idx, val, len);
     return 0;
 }