VideoCore Library: interface/khronos/ext/gl_oes_framebuffer_object.c File Reference
gl_oes_framebuffer_object.c File Reference
#include "interface/khronos/common/khrn_client_mangle.h"
#include "interface/khronos/common/khrn_int_common.h"
#include "interface/khronos/glxx/glxx_client.h"
#include "interface/khronos/common/khrn_client_rpc.h"
#include "interface/khronos/include/GLES/gl.h"
#include "interface/khronos/include/GLES/glext.h"
Macros
#define GL_GLEXT_PROTOTYPES /* we want the prototypes so the compiler will check that the signatures match */
Functions
GLboolean glxx_client_IsRenderbuffer (GLuint renderbuffer)
void glxx_client_BindRenderbuffer (GLenum target, GLuint renderbuffer)
void glxx_client_DeleteRenderbuffers (GLsizei n, const GLuint *renderbuffers)
void glxx_client_GenRenderbuffers (GLsizei n, GLuint *renderbuffers)
void glxx_client_RenderbufferStorage (GLenum target, GLenum internalformat, GLsizei width, GLsizei height)
void glxx_client_GetRenderbufferParameteriv (GLenum target, GLenum pname, GLint *params)
GLboolean glxx_client_IsFramebuffer (GLuint framebuffer)
void glxx_client_BindFramebuffer (GLenum target, GLuint framebuffer)
void glxx_client_DeleteFramebuffers (GLsizei n, const GLuint *framebuffers)
void glxx_client_GenFramebuffers (GLsizei n, GLuint *framebuffers)
GLenum glxx_client_CheckFramebufferStatus (GLenum target)
void glxx_client_FramebufferTexture2D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
void glxx_client_FramebufferRenderbuffer (GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer)
void glxx_client_GetFramebufferAttachmentParameteriv (GLenum target, GLenum attachment, GLenum pname, GLint *params)
void glxx_client_GenerateMipmap (GLenum target)
GL_API GLboolean GL_APIENTRY glIsRenderbufferOES (GLuint renderbuffer)
GL_API void GL_APIENTRY glBindRenderbufferOES (GLenum target, GLuint renderbuffer)
GL_API void GL_APIENTRY glDeleteRenderbuffersOES (GLsizei n, const GLuint *renderbuffers)
GL_API void GL_APIENTRY glGenRenderbuffersOES (GLsizei n, GLuint *renderbuffers)
GL_API void GL_APIENTRY glRenderbufferStorageOES (GLenum target, GLenum internalformat, GLsizei width, GLsizei height)
GL_API void GL_APIENTRY glGetRenderbufferParameterivOES (GLenum target, GLenum pname, GLint *params)
GL_API GLboolean GL_APIENTRY glIsFramebufferOES (GLuint framebuffer)
GL_API void GL_APIENTRY glBindFramebufferOES (GLenum target, GLuint framebuffer)
GL_API void GL_APIENTRY glDeleteFramebuffersOES (GLsizei n, const GLuint *framebuffers)
GL_API void GL_APIENTRY glGenFramebuffersOES (GLsizei n, GLuint *framebuffers)
GL_API GLenum GL_APIENTRY glCheckFramebufferStatusOES (GLenum target)
GL_API void GL_APIENTRY glFramebufferRenderbufferOES (GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer)
GL_API void GL_APIENTRY glFramebufferTexture2DOES (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
GL_API void GL_APIENTRY glGetFramebufferAttachmentParameterivOES (GLenum target, GLenum attachment, GLenum pname, GLint *params)
GL_API void GL_APIENTRY glGenerateMipmapOES (GLenum target)
Macro Definition Documentation
GL_GLEXT_PROTOTYPES
#define GL_GLEXT_PROTOTYPES /* we want the prototypes so the compiler will check that the signatures match */
Definition at line 28 of file gl_oes_framebuffer_object.c.
Function Documentation
glBindFramebufferOES()
GL_API void GL_APIENTRY glBindFramebufferOES (GLenum target, GLuint framebuffer)
Definition at line 96 of file gl_oes_framebuffer_object.c.
References glxx_client_BindFramebuffer().
 {
    glxx_client_BindFramebuffer(target, framebuffer);
 }
glBindRenderbufferOES()
GL_API void GL_APIENTRY glBindRenderbufferOES (GLenum target, GLuint renderbuffer)
Definition at line 66 of file gl_oes_framebuffer_object.c.
References glxx_client_BindRenderbuffer().
 {
    glxx_client_BindRenderbuffer(target, renderbuffer);
 }
glCheckFramebufferStatusOES()
GL_API GLenum GL_APIENTRY glCheckFramebufferStatusOES (GLenum target)
Definition at line 111 of file gl_oes_framebuffer_object.c.
References glxx_client_CheckFramebufferStatus().
 {
    return glxx_client_CheckFramebufferStatus(target);
 }
glDeleteFramebuffersOES()
GL_API void GL_APIENTRY glDeleteFramebuffersOES (GLsizei n, const GLuint * framebuffers)
Definition at line 101 of file gl_oes_framebuffer_object.c.
References glxx_client_DeleteFramebuffers().
 {
    glxx_client_DeleteFramebuffers(n, framebuffers);
 }
glDeleteRenderbuffersOES()
GL_API void GL_APIENTRY glDeleteRenderbuffersOES (GLsizei n, const GLuint * renderbuffers)
Definition at line 71 of file gl_oes_framebuffer_object.c.
References glxx_client_DeleteRenderbuffers().
 {
    glxx_client_DeleteRenderbuffers(n, renderbuffers);
 }
glFramebufferRenderbufferOES()
GL_API void GL_APIENTRY glFramebufferRenderbufferOES (GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer)
Definition at line 116 of file gl_oes_framebuffer_object.c.
References glxx_client_FramebufferRenderbuffer().
 {
    glxx_client_FramebufferRenderbuffer(target, attachment, renderbuffertarget, renderbuffer);
 }
glFramebufferTexture2DOES()
GL_API void GL_APIENTRY glFramebufferTexture2DOES (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
Definition at line 121 of file gl_oes_framebuffer_object.c.
References glxx_client_FramebufferTexture2D().
 {
    glxx_client_FramebufferTexture2D(target, attachment, textarget, texture, level);
 }
glGenerateMipmapOES()
GL_API void GL_APIENTRY glGenerateMipmapOES (GLenum target)
Definition at line 131 of file gl_oes_framebuffer_object.c.
References glxx_client_GenerateMipmap().
 {
    glxx_client_GenerateMipmap(target);
 }
glGenFramebuffersOES()
GL_API void GL_APIENTRY glGenFramebuffersOES (GLsizei n, GLuint * framebuffers)
Definition at line 106 of file gl_oes_framebuffer_object.c.
References glxx_client_GenFramebuffers().
 {
    glxx_client_GenFramebuffers(n, framebuffers);
 }
glGenRenderbuffersOES()
GL_API void GL_APIENTRY glGenRenderbuffersOES (GLsizei n, GLuint * renderbuffers)
Definition at line 76 of file gl_oes_framebuffer_object.c.
References glxx_client_GenRenderbuffers().
 {
    glxx_client_GenRenderbuffers(n, renderbuffers);
 }
glGetFramebufferAttachmentParameterivOES()
GL_API void GL_APIENTRY glGetFramebufferAttachmentParameterivOES (GLenum target, GLenum attachment, GLenum pname, GLint * params)
Definition at line 126 of file gl_oes_framebuffer_object.c.
References glxx_client_GetFramebufferAttachmentParameteriv().
 {
    glxx_client_GetFramebufferAttachmentParameteriv(target, attachment, pname, params);
 }
glGetRenderbufferParameterivOES()
GL_API void GL_APIENTRY glGetRenderbufferParameterivOES (GLenum target, GLenum pname, GLint * params)
Definition at line 86 of file gl_oes_framebuffer_object.c.
References glxx_client_GetRenderbufferParameteriv().
 {
    glxx_client_GetRenderbufferParameteriv(target, pname, params);
 }
glIsFramebufferOES()
GL_API GLboolean GL_APIENTRY glIsFramebufferOES (GLuint framebuffer)
Definition at line 91 of file gl_oes_framebuffer_object.c.
References glxx_client_IsFramebuffer().
 {
    return glxx_client_IsFramebuffer(framebuffer);
 }
glIsRenderbufferOES()
GL_API GLboolean GL_APIENTRY glIsRenderbufferOES (GLuint renderbuffer)
Definition at line 61 of file gl_oes_framebuffer_object.c.
References glxx_client_IsRenderbuffer().
 {
    return glxx_client_IsRenderbuffer(renderbuffer);
 }
glRenderbufferStorageOES()
GL_API void GL_APIENTRY glRenderbufferStorageOES (GLenum target, GLenum internalformat, GLsizei width, GLsizei height)
Definition at line 81 of file gl_oes_framebuffer_object.c.
References glxx_client_RenderbufferStorage().
 {
    glxx_client_RenderbufferStorage(target, internalformat, width, height);
 }
glxx_client_BindFramebuffer()
void glxx_client_BindFramebuffer (GLenum target, GLuint framebuffer)
Definition at line 5284 of file glxx_client.c.
Referenced by glBindFramebuffer(), and glBindFramebufferOES().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       RPC_CALL2(glBindFramebuffer_impl,
                 thread,
                 GLBINDFRAMEBUFFER_ID,
                 RPC_ENUM(target),
                 RPC_UINT(framebuffer));
       //TODO: this may be set incorrectly if there's an error
       state->default_framebuffer = (framebuffer == 0);
    }
 }
glxx_client_BindRenderbuffer()
void glxx_client_BindRenderbuffer (GLenum target, GLuint renderbuffer)
Definition at line 5146 of file glxx_client.c.
Referenced by glBindRenderbuffer(), and glBindRenderbufferOES().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL2(glBindRenderbuffer_impl,
                 thread,
                 GLBINDRENDERBUFFER_ID,
                 RPC_ENUM(target),
                 RPC_UINT(renderbuffer));
    }
 }
glxx_client_CheckFramebufferStatus()
GLenum glxx_client_CheckFramebufferStatus (GLenum target)
Definition at line 5360 of file glxx_client.c.
Referenced by glCheckFramebufferStatus(), and glCheckFramebufferStatusOES().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       return RPC_ENUM_RES(RPC_CALL1_RES(glCheckFramebufferStatus_impl,
                            thread,
                            GLCHECKFRAMEBUFFERSTATUS_ID,
                            RPC_ENUM(target)));
    }
    return GL_NONE;
 }
glxx_client_DeleteFramebuffers()
void glxx_client_DeleteFramebuffers (GLsizei n, const GLuint * framebuffers)
Definition at line 5305 of file glxx_client.c.
Referenced by glDeleteFramebuffers(), and glDeleteFramebuffersOES().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    int offset = 0;
    do {
       int32_t items = (int32_t)(KHDISPATCH_WORKSPACE_SIZE / sizeof(GLuint));
       int32_t batch = _min(items, (int32_t)n);
       if (IS_OPENGLES_11_OR_20(thread)) {
          RPC_CALL2_IN_BULK(glDeleteFramebuffers_impl,
                            thread,
                            GLDELETEFRAMEBUFFERS_ID,
                            RPC_SIZEI(batch),
                            framebuffers + offset,
                            batch > 0 ? batch * sizeof(GLuint) : 0);
       }
       offset += batch;
       n -= batch;
    } while (n > 0);
 }
glxx_client_DeleteRenderbuffers()
void glxx_client_DeleteRenderbuffers (GLsizei n, const GLuint * renderbuffers)
Definition at line 5164 of file glxx_client.c.
Referenced by glDeleteRenderbuffers(), and glDeleteRenderbuffersOES().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    int offset = 0;
    do {
       int32_t items = (int32_t) (KHDISPATCH_WORKSPACE_SIZE / sizeof(GLuint));
       int32_t batch = _min(items, (int32_t)n);
       if (IS_OPENGLES_11_OR_20(thread)) {
          RPC_CALL2_IN_BULK(glDeleteRenderbuffers_impl,
                            thread,
                            GLDELETERENDERBUFFERS_ID,
                            RPC_SIZEI(batch),
                            renderbuffers + offset,
                            batch > 0 ? batch * sizeof(GLuint) : 0);
       }
       offset += batch;
       n -= batch;
    } while (n > 0);
 }
glxx_client_FramebufferRenderbuffer()
void glxx_client_FramebufferRenderbuffer (GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer)
Definition at line 5398 of file glxx_client.c.
Referenced by glFramebufferRenderbuffer(), and glFramebufferRenderbufferOES().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL4(glFramebufferRenderbuffer_impl,
                 thread,
                 GLFRAMEBUFFERRENDERBUFFER_ID,
                 RPC_ENUM(target),
                 RPC_ENUM(attachment),
                 RPC_ENUM(renderbuffertarget),
                 RPC_UINT(renderbuffer));
    }
 }
glxx_client_FramebufferTexture2D()
void glxx_client_FramebufferTexture2D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
Definition at line 5378 of file glxx_client.c.
Referenced by glFramebufferTexture2D(), and glFramebufferTexture2DOES().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL5(glFramebufferTexture2D_impl,
                 thread,
                 GLFRAMEBUFFERTEXTURE2D_ID,
                 RPC_ENUM(target),
                 RPC_ENUM(attachment),
                 RPC_ENUM(textarget),
                 RPC_UINT(texture),
                 RPC_INT(level));
    }
 }
glxx_client_GenerateMipmap()
void glxx_client_GenerateMipmap (GLenum target)
Definition at line 5436 of file glxx_client.c.
Referenced by glGenerateMipmapOES().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL1(glGenerateMipmap_impl,
                 thread,
                 GLGENERATEMIPMAP_ID,
                 RPC_ENUM(target));
    }
 }
glxx_client_GenFramebuffers()
void glxx_client_GenFramebuffers (GLsizei n, GLuint * framebuffers)
Definition at line 5333 of file glxx_client.c.
Referenced by glGenFramebuffers(), and glGenFramebuffersOES().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    int offset = 0;
    do {
       int32_t items = (int32_t)(KHDISPATCH_WORKSPACE_SIZE / sizeof(GLuint));
       int32_t batch = _min(items, (int32_t)n);
       if (IS_OPENGLES_11_OR_20(thread)) {
          RPC_CALL2_OUT_BULK(glGenFramebuffers_impl,
                             thread,
                             GLGENFRAMEBUFFERS_ID,
                             RPC_SIZEI(batch),
                             framebuffers + offset);
       }
       offset += batch;
       n -= batch;
    } while (n > 0);
 }
glxx_client_GenRenderbuffers()
void glxx_client_GenRenderbuffers (GLsizei n, GLuint * renderbuffers)
Definition at line 5192 of file glxx_client.c.
Referenced by glGenRenderbuffers(), and glGenRenderbuffersOES().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    int offset = 0;
    do {
       int32_t items = (int32_t)(KHDISPATCH_WORKSPACE_SIZE / sizeof(GLuint));
       int32_t batch = _min(items, (int32_t)n);
       if (IS_OPENGLES_11_OR_20(thread)) {
          RPC_CALL2_OUT_BULK(glGenRenderbuffers_impl,
                             thread,
                             GLGENRENDERBUFFERS_ID,
                             RPC_SIZEI(batch),
                             renderbuffers + offset);
       }
       offset += batch;
       n -= batch;
    } while (n > 0);
 }
glxx_client_GetFramebufferAttachmentParameteriv()
void glxx_client_GetFramebufferAttachmentParameteriv (GLenum target, GLenum attachment, GLenum pname, GLint * params)
Definition at line 5417 of file glxx_client.c.
Referenced by glGetFramebufferAttachmentParameteriv(), and glGetFramebufferAttachmentParameterivOES().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL4_OUT_CTRL(glGetFramebufferAttachmentParameteriv_impl,
                          thread,
                          GLGETFRAMEBUFFERATTACHMENTPARAMETERIV_ID,
                          RPC_ENUM(target),
                          RPC_ENUM(attachment),
                          RPC_ENUM(pname),
                          params);
    }
 }
glxx_client_GetRenderbufferParameteriv()
void glxx_client_GetRenderbufferParameteriv (GLenum target, GLenum pname, GLint * params)
Definition at line 5238 of file glxx_client.c.
Referenced by glGetRenderbufferParameteriv(), and glGetRenderbufferParameterivOES().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL3_OUT_CTRL(glGetRenderbufferParameteriv_impl,
                          thread,
                          GLGETRENDERBUFFERPARAMETERIV_ID,
                          RPC_ENUM(target),
                          RPC_ENUM(pname),
                          params);
    }
 }
glxx_client_IsFramebuffer()
GLboolean glxx_client_IsFramebuffer (GLuint framebuffer)
Definition at line 5256 of file glxx_client.c.
Referenced by glIsFramebuffer(), and glIsFramebufferOES().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       return RPC_BOOLEAN_RES(RPC_CALL1_RES(glIsFramebuffer_impl,
                                            thread,
                                            GLISFRAMEBUFFER_ID,
                                            RPC_UINT(framebuffer)));
    }
    return 0;
 }
glxx_client_IsRenderbuffer()
GLboolean glxx_client_IsRenderbuffer (GLuint renderbuffer)
Definition at line 5127 of file glxx_client.c.
Referenced by glIsRenderbuffer(), and glIsRenderbufferOES().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       return RPC_BOOLEAN_RES(RPC_CALL1_RES(glIsRenderbuffer_impl,
                                            thread,
                                            GLISRENDERBUFFER_ID,
                                            RPC_UINT(renderbuffer)));
    }
    return 0;
 }
glxx_client_RenderbufferStorage()
void glxx_client_RenderbufferStorage (GLenum target, GLenum internalformat, GLsizei width, GLsizei height)
Definition at line 5219 of file glxx_client.c.
Referenced by glRenderbufferStorage(), and glRenderbufferStorageOES().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL4(glRenderbufferStorage_impl,
                 thread,
                 GLRENDERBUFFERSTORAGE_ID,
                 RPC_ENUM(target),
                 RPC_ENUM(internalformat),
                 RPC_SIZEI(width),
                 RPC_SIZEI(height));
    }
 }