VideoCore Library: containers/core/containers_utils.c File Reference
containers_utils.c File Reference
#include <stdlib.h>
#include <string.h>
#include "containers/containers.h"
#include "containers/core/containers_common.h"
#include "containers/core/containers_utils.h"
Classes
struct VC_CONTAINER_ES_FORMAT_PRIVATE_T
Macros
#define BITMAPINFOHEADER_SIZE_MAX 40
#define MAX_EXTENSION_SIZE 4
#define VC_CONTAINER_ES_FORMAT_MAGIC ((uint32_t)VC_FOURCC('m','a','g','f'))
#define EXTRADATA_SIZE_DEFAULT 32
#define EXTRADATA_SIZE_MAX (10*1024)
Typedefs
typedef struct VC_CONTAINER_ES_FORMAT_PRIVATE_T VC_CONTAINER_ES_FORMAT_PRIVATE_T
Functions
VC_CONTAINER_ES_FORMAT_T * vc_container_format_create (unsigned int extradata_size)
void vc_container_format_delete (VC_CONTAINER_ES_FORMAT_T *format)
VC_CONTAINER_STATUS_T vc_container_format_extradata_alloc (VC_CONTAINER_ES_FORMAT_T *format, unsigned int size)
VC_CONTAINER_STATUS_T vc_container_format_copy (VC_CONTAINER_ES_FORMAT_T *p_out, VC_CONTAINER_ES_FORMAT_T *p_in, unsigned int extra_buffer_size)
int utf8_from_charset (const char *charset, char *out, unsigned int out_size, const void *in, unsigned int in_size)
unsigned int vc_container_es_format_to_waveformatex (VC_CONTAINER_ES_FORMAT_T *format, uint8_t *buffer, unsigned int buffer_size)
VC_CONTAINER_STATUS_T vc_container_waveformatex_to_es_format (uint8_t *p, unsigned int buffer_size, unsigned int *extra_offset, unsigned int *extra_size, VC_CONTAINER_ES_FORMAT_T *format)
unsigned int vc_container_es_format_to_bitmapinfoheader (VC_CONTAINER_ES_FORMAT_T *format, uint8_t *buffer, unsigned int buffer_size)
VC_CONTAINER_STATUS_T vc_container_bitmapinfoheader_to_es_format (uint8_t *p, unsigned int buffer_size, unsigned int *extra_offset, unsigned int *extra_size, VC_CONTAINER_ES_FORMAT_T *format)
const char * vc_container_metadata_id_to_string (VC_CONTAINER_METADATA_KEY_T key)
int64_t vc_container_maths_gcd (int64_t a, int64_t b)
void vc_container_maths_rational_simplify (uint32_t *num, uint32_t *den)
Macro Definition Documentation
BITMAPINFOHEADER_SIZE_MAX
#define BITMAPINFOHEADER_SIZE_MAX 40
Definition at line 38 of file containers_utils.c.
Referenced by vc_container_bitmapinfoheader_to_es_format(), and vc_container_es_format_to_bitmapinfoheader().
EXTRADATA_SIZE_DEFAULT
#define EXTRADATA_SIZE_DEFAULT 32
Definition at line 42 of file containers_utils.c.
Referenced by vc_container_format_create().
EXTRADATA_SIZE_MAX
#define EXTRADATA_SIZE_MAX (10*1024)
Definition at line 43 of file containers_utils.c.
Referenced by vc_container_format_extradata_alloc().
MAX_EXTENSION_SIZE
#define MAX_EXTENSION_SIZE 4
Definition at line 39 of file containers_utils.c.
VC_CONTAINER_ES_FORMAT_MAGIC
#define VC_CONTAINER_ES_FORMAT_MAGIC ((uint32_t)VC_FOURCC('m','a','g','f'))
Definition at line 41 of file containers_utils.c.
Referenced by vc_container_format_create(), vc_container_format_delete(), and vc_container_format_extradata_alloc().
Typedef Documentation
VC_CONTAINER_ES_FORMAT_PRIVATE_T
typedef struct VC_CONTAINER_ES_FORMAT_PRIVATE_T VC_CONTAINER_ES_FORMAT_PRIVATE_T
Function Documentation
utf8_from_charset()
int utf8_from_charset (const char * charset, char * out, unsigned int out_size, const void * in, unsigned int in_size)
Definition at line 145 of file containers_utils.c.
Referenced by vc_container_helper_read_debug().
 {
    unsigned int i;
    const uint16_t *in16 = (const uint16_t *)in;
    const uint8_t *in8 = (const uint8_t *)in;
    if(out_size < 1) return 1;
    if(!strcmp(charset, "UTF16-LE")) goto utf16le;
    if(!strcmp(charset, "UTF8")) goto utf8;
    else return 1;
  utf16le:
    for(i = 0; i < in_size / 2 && in16[i] && i < out_size - 1; i++)
    {
       out[i] = in16[i];
    }
    out[i] = 0;
    return 0;
  utf8:
    for(i = 0; i < in_size && in8[i] && i < out_size - 1; i++)
    {
       out[i] = in8[i];
    }
    out[i] = 0;
    return 0;
 }
vc_container_bitmapinfoheader_to_es_format()
VC_CONTAINER_STATUS_T vc_container_bitmapinfoheader_to_es_format (uint8_t * p, unsigned int buffer_size, unsigned int * extra_offset, unsigned int * extra_size, VC_CONTAINER_ES_FORMAT_T * format)
Definition at line 290 of file containers_utils.c.
References BITMAPINFOHEADER_SIZE_MAX, VC_CONTAINER_ES_FORMAT_T::codec, VC_CONTAINER_ES_FORMAT_T::es_type, fourcc, fourcc_to_codec(), VC_CONTAINER_VIDEO_FORMAT_T::height, VC_CONTAINER_ES_FORMAT_T::type, VC_CONTAINER_CODEC_UNKNOWN, VC_CONTAINER_ERROR_INVALID_ARGUMENT, VC_CONTAINER_ES_TYPE_VIDEO, VC_CONTAINER_SUCCESS, vfw_fourcc_to_codec(), VC_CONTAINER_ES_SPECIFIC_FORMAT_T::video, and VC_CONTAINER_VIDEO_FORMAT_T::width.
 {
    VC_CONTAINER_FOURCC_T fourcc;
    if(!p || buffer_size < BITMAPINFOHEADER_SIZE_MAX) return VC_CONTAINER_ERROR_INVALID_ARGUMENT;
    /* size = (p[3] << 24) | (p[2] << 16) | (p[1] << 8) | p[0]; */
    format->type->video.width = (p[7] << 24) | (p[6] << 16) | (p[5] << 8) | p[4];
    format->type->video.height = (p[11] << 24) | (p[10] << 16) | (p[9] << 8) | p[8];
    memcpy(&fourcc, p + 16, 4);
    format->es_type = VC_CONTAINER_ES_TYPE_VIDEO;
    format->codec = vfw_fourcc_to_codec(fourcc);
    /* If no mapping is found from vfw, try a more generic one */
    if (format->codec == fourcc && (fourcc = fourcc_to_codec(fourcc)) != VC_CONTAINER_CODEC_UNKNOWN)
       format->codec = fourcc;
    if(extra_offset) *extra_offset = BITMAPINFOHEADER_SIZE_MAX;
    if(extra_size)
    {
       if (buffer_size > BITMAPINFOHEADER_SIZE_MAX)
          *extra_size = buffer_size - BITMAPINFOHEADER_SIZE_MAX;
       else
          *extra_size = 0;
    }
    return VC_CONTAINER_SUCCESS;
 }
vc_container_es_format_to_bitmapinfoheader()
unsigned int vc_container_es_format_to_bitmapinfoheader (VC_CONTAINER_ES_FORMAT_T * format, uint8_t * buffer, unsigned int buffer_size)
Definition at line 258 of file containers_utils.c.
References BITMAPINFOHEADER_SIZE_MAX, VC_CONTAINER_ES_FORMAT_T::codec, codec_to_vfw_fourcc(), VC_CONTAINER_ES_FORMAT_T::es_type, VC_CONTAINER_ES_FORMAT_T::extradata, VC_CONTAINER_ES_FORMAT_T::extradata_size, fourcc, VC_CONTAINER_VIDEO_FORMAT_T::height, VC_CONTAINER_ES_FORMAT_T::type, VC_CONTAINER_CODEC_UNKNOWN, VC_CONTAINER_ES_TYPE_VIDEO, VC_CONTAINER_ES_SPECIFIC_FORMAT_T::video, and VC_CONTAINER_VIDEO_FORMAT_T::width.
 {
    uint32_t fourcc = codec_to_vfw_fourcc(format->codec);
    uint32_t size = BITMAPINFOHEADER_SIZE_MAX + format->extradata_size;
    if(format->es_type != VC_CONTAINER_ES_TYPE_VIDEO ||
       fourcc == VC_CONTAINER_CODEC_UNKNOWN) return 0;
    if(!buffer) return size;
    if(buffer_size < size) return 0;
    /* Build a bitmapinfoheader header */
    memset(buffer, 0, BITMAPINFOHEADER_SIZE_MAX);
    buffer[0] = (size >> 0) & 0xFF;
    buffer[1] = (size >> 8) & 0xFF;
    buffer[2] = (size >> 16) & 0xFF;
    buffer[3] = (size >> 24) & 0xFF;
    buffer[4] = (format->type->video.width >> 0) & 0xFF;
    buffer[5] = (format->type->video.width >> 8) & 0xFF;
    buffer[6] = (format->type->video.width >> 16) & 0xFF;
    buffer[7] = (format->type->video.width >> 24) & 0xFF;
    buffer[8] = (format->type->video.height >> 0) & 0xFF;
    buffer[9] = (format->type->video.height >> 8) & 0xFF;
    buffer[10] = (format->type->video.height >> 16) & 0xFF;
    buffer[11] = (format->type->video.height >> 24) & 0xFF;
    memcpy(buffer + 16, &fourcc, 4);
    memcpy(buffer + BITMAPINFOHEADER_SIZE_MAX, format->extradata, format->extradata_size);
    return size;
 }
vc_container_es_format_to_waveformatex()
unsigned int vc_container_es_format_to_waveformatex (VC_CONTAINER_ES_FORMAT_T * format, uint8_t * buffer, unsigned int buffer_size)
Definition at line 175 of file containers_utils.c.
References VC_CONTAINER_ES_SPECIFIC_FORMAT_T::audio, VC_CONTAINER_ES_FORMAT_T::bitrate, VC_CONTAINER_AUDIO_FORMAT_T::bits_per_sample, VC_CONTAINER_AUDIO_FORMAT_T::block_align, VC_CONTAINER_AUDIO_FORMAT_T::channels, VC_CONTAINER_ES_FORMAT_T::codec, codec_to_waveformat(), VC_CONTAINER_ES_FORMAT_T::es_type, VC_CONTAINER_ES_FORMAT_T::extradata, VC_CONTAINER_ES_FORMAT_PRIVATE_T::extradata_size, VC_CONTAINER_ES_FORMAT_T::extradata_size, VC_CONTAINER_AUDIO_FORMAT_T::sample_rate, VC_CONTAINER_ES_FORMAT_T::type, VC_CONTAINER_ES_TYPE_AUDIO, and WAVE_FORMAT_UNKNOWN.
 {
    uint16_t waveformat = codec_to_waveformat(format->codec);
    if(format->es_type != VC_CONTAINER_ES_TYPE_AUDIO ||
       waveformat == WAVE_FORMAT_UNKNOWN) return 0;
    if(!buffer) return format->extradata_size + 18;
    if(buffer_size < format->extradata_size + 18) return 0;
    /* Build a waveformatex header */
    buffer[0] = waveformat;
    buffer[1] = waveformat >> 8;
    buffer[2] = format->type->audio.channels;
    buffer[3] = 0;
    buffer[4] = (format->type->audio.sample_rate >> 0) & 0xFF;
    buffer[5] = (format->type->audio.sample_rate >> 8) & 0xFF;
    buffer[6] = (format->type->audio.sample_rate >> 16) & 0xFF;
    buffer[7] = (format->type->audio.sample_rate >> 24) & 0xFF;
    buffer[8] = (format->bitrate >> 3) & 0xFF;
    buffer[9] = (format->bitrate >> 11) & 0xFF;
    buffer[10] = (format->bitrate >> 19) & 0xFF;
    buffer[11] = (format->bitrate >> 27) & 0xFF;
    buffer[12] = (format->type->audio.block_align >> 0) & 0xFF;
    buffer[13] = (format->type->audio.block_align >> 8) & 0xFF;
    buffer[14] = (format->type->audio.bits_per_sample >> 0) & 0xFF;
    buffer[15] = (format->type->audio.bits_per_sample >> 8) & 0xFF;
    buffer[16] = (format->extradata_size >> 0) & 0xFF;
    buffer[17] = (format->extradata_size >> 8) & 0xFF;
    memcpy(buffer+18, format->extradata, format->extradata_size);
    return format->extradata_size + 18;
 }
vc_container_format_copy()
VC_CONTAINER_STATUS_T vc_container_format_copy (VC_CONTAINER_ES_FORMAT_T * p_out, VC_CONTAINER_ES_FORMAT_T * p_in, unsigned int extra_buffer_size)
Definition at line 122 of file containers_utils.c.
References VC_CONTAINER_ES_FORMAT_PRIVATE_T::extradata, VC_CONTAINER_ES_FORMAT_T::extradata, VC_CONTAINER_ES_FORMAT_T::extradata_size, VC_CONTAINER_ES_FORMAT_PRIVATE_T::type, VC_CONTAINER_ES_FORMAT_T::type, VC_CONTAINER_ERROR_BUFFER_TOO_SMALL, and VC_CONTAINER_SUCCESS.
Referenced by avc1_packetizer_open(), mpgv_packetizer_open(), and vc_packetizer_open().
 {
    void *type = p_out->type;
    uint8_t *extradata = p_out->extradata;
    /* Check we have a sufficient buffer to copy the extra data */
    if(p_in->extradata_size > extra_buffer_size ||
       (p_in->extradata_size && !p_out->extradata))
       return VC_CONTAINER_ERROR_BUFFER_TOO_SMALL;
    *p_out->type = *p_in->type;
    *p_out = *p_in;
    p_out->type = type;
    p_out->extradata = extradata;
    if(p_in->extradata_size)
       memcpy(p_out->extradata, p_in->extradata, p_in->extradata_size);
    return VC_CONTAINER_SUCCESS;
 }
vc_container_format_create()
VC_CONTAINER_ES_FORMAT_T* vc_container_format_create (unsigned int extradata_size)
Definition at line 61 of file containers_utils.c.
References EXTRADATA_SIZE_DEFAULT, NULL, status, VC_CONTAINER_ES_FORMAT_MAGIC, vc_container_format_extradata_alloc(), and VC_CONTAINER_SUCCESS.
Referenced by vc_packetizer_open().
 {
    VC_CONTAINER_ES_FORMAT_PRIVATE_T *private;
    VC_CONTAINER_STATUS_T status;
    private = malloc(sizeof(*private));
    if(!private) return 0;
    memset(private, 0, sizeof(*private));
    private->magic = VC_CONTAINER_ES_FORMAT_MAGIC;
    private->format.type = (void *)&private->type;
    private->extradata_size = EXTRADATA_SIZE_DEFAULT;
    status = vc_container_format_extradata_alloc(&private->format, extradata_size);
    if(status != VC_CONTAINER_SUCCESS)
    {
       free(private);
       return NULL;
    }
    return &private->format;
 }
vc_container_format_delete()
void vc_container_format_delete (VC_CONTAINER_ES_FORMAT_T * format)
Definition at line 85 of file containers_utils.c.
References vc_container_assert, and VC_CONTAINER_ES_FORMAT_MAGIC.
Referenced by vc_packetizer_close().
 {
    VC_CONTAINER_ES_FORMAT_PRIVATE_T *private = (VC_CONTAINER_ES_FORMAT_PRIVATE_T *)format;
    vc_container_assert(private->magic == VC_CONTAINER_ES_FORMAT_MAGIC);
    if(private->extradata) free(private->extradata);
    free(private);
 }
vc_container_format_extradata_alloc()
VC_CONTAINER_STATUS_T vc_container_format_extradata_alloc (VC_CONTAINER_ES_FORMAT_T * format, unsigned int size)
Definition at line 94 of file containers_utils.c.
References EXTRADATA_SIZE_MAX, vc_container_assert, VC_CONTAINER_ERROR_CORRUPTED, VC_CONTAINER_ERROR_OUT_OF_MEMORY, VC_CONTAINER_ES_FORMAT_MAGIC, and VC_CONTAINER_SUCCESS.
Referenced by vc_container_format_create().
 {
    VC_CONTAINER_ES_FORMAT_PRIVATE_T *private = (VC_CONTAINER_ES_FORMAT_PRIVATE_T *)format;
    vc_container_assert(private->magic == VC_CONTAINER_ES_FORMAT_MAGIC);
    /* Sanity check the size requested */
    if(size > EXTRADATA_SIZE_MAX)
       return VC_CONTAINER_ERROR_CORRUPTED;
    /* Allocate memory if needed */
    if(private->extradata_size < size)
    {
       if(private->extradata) free(private->extradata);
       private->extradata = malloc(size);
       if(!private->extradata)
          return VC_CONTAINER_ERROR_OUT_OF_MEMORY;
       private->extradata_size = size;
    }
    /* Set the fields in the actual format structure */
    if(private->extradata) private->format.extradata = private->extradata;
    else private->format.extradata = private->buffer;
    return VC_CONTAINER_SUCCESS;
 }
vc_container_maths_gcd()
int64_t vc_container_maths_gcd (int64_t a, int64_t b)
Find the greatest common denominator of 2 numbers.
Parameters
a first number
b second number
Returns
greatest common denominator of a and b
Definition at line 346 of file containers_utils.c.
Referenced by vc_container_maths_rational_simplify().
 {
    while(b != 0)
    {
       int64_t t = b;
       b = a % b;
       a = t;
    }
    return a;
 }
vc_container_maths_rational_simplify()
void vc_container_maths_rational_simplify (uint32_t * num, uint32_t * den)
Reduce a rational number to it's simplest form.
Parameters
num Pointer to the numerator of the rational number to simplify
den Pointer to the denominator of the rational number to simplify
Definition at line 358 of file containers_utils.c.
References vc_container_maths_gcd().
 {
    int64_t div = vc_container_maths_gcd((int64_t)*num, (int64_t)*den);
    if(div)
    {
       *num /= div;
       *den /= div;
    }
 }
vc_container_metadata_id_to_string()
const char* vc_container_metadata_id_to_string (VC_CONTAINER_METADATA_KEY_T key)
Definition at line 337 of file containers_utils.c.
 {
    int i;
    for(i = 0; meta_key_conv[i].key != VC_CONTAINER_METADATA_KEY_UNKNOWN; i++ )
       if(meta_key_conv[i].key == key) break;
    return meta_key_conv[i].name;
 }
vc_container_waveformatex_to_es_format()
VC_CONTAINER_STATUS_T vc_container_waveformatex_to_es_format (uint8_t * p, unsigned int buffer_size, unsigned int * extra_offset, unsigned int * extra_size, VC_CONTAINER_ES_FORMAT_T * format)
Definition at line 211 of file containers_utils.c.
References VC_CONTAINER_ES_SPECIFIC_FORMAT_T::audio, VC_CONTAINER_ES_FORMAT_T::bitrate, VC_CONTAINER_AUDIO_FORMAT_T::bits_per_sample, VC_CONTAINER_AUDIO_FORMAT_T::block_align, VC_CONTAINER_AUDIO_FORMAT_T::channels, VC_CONTAINER_ES_FORMAT_T::codec, VC_CONTAINER_ES_FORMAT_T::es_type, fourcc, VC_CONTAINER_AUDIO_FORMAT_T::sample_rate, VC_CONTAINER_ES_FORMAT_T::type, VC_CONTAINER_CODEC_PCM_UNSIGNED_LE, VC_CONTAINER_ERROR_INVALID_ARGUMENT, VC_CONTAINER_ES_TYPE_AUDIO, VC_CONTAINER_SUCCESS, WAVE_FORMAT_MPEGLAYER3, WAVE_FORMAT_PCM, and waveformat_to_codec().
 {
    VC_CONTAINER_FOURCC_T fourcc;
    uint32_t waveformat_id;
    if(!p || buffer_size < 16) return VC_CONTAINER_ERROR_INVALID_ARGUMENT;
    waveformat_id = (p[1] << 8) | p[0];
    fourcc = waveformat_to_codec(waveformat_id);
    /* Read the waveformatex header */
    if(extra_offset) *extra_offset = 16;
    if(extra_size) *extra_size = 0;
    format->type->audio.channels = p[2];
    format->type->audio.sample_rate = (p[7] << 24) | (p[6] << 16) | (p[5] << 8) | p[4];
    format->bitrate = ((p[11] << 24) | (p[10] << 16) | (p[9] << 8) | p[8]) * 8;
    format->type->audio.block_align = (p[13] << 8) | p[12];
    format->type->audio.bits_per_sample = (p[15] << 8) | p[14];
    if(waveformat_id == WAVE_FORMAT_PCM && format->type->audio.bits_per_sample == 8)
       fourcc = VC_CONTAINER_CODEC_PCM_UNSIGNED_LE;
    if(buffer_size >= 18)
    {
       if(extra_size)
       {
          *extra_size = (p[17] << 8) | p[16];
          if(*extra_size + 18 > buffer_size) *extra_size = buffer_size - 18;
       }
       if(extra_offset) *extra_offset = 18;
    }
    /* Skip the MPEGLAYER3WAVEFORMAT structure */
    if(waveformat_id == WAVE_FORMAT_MPEGLAYER3 && extra_size)
    {
       if(extra_offset) *extra_offset += *extra_size;
       *extra_size = 0;
    }
    format->es_type = VC_CONTAINER_ES_TYPE_AUDIO;
    format->codec = fourcc;
    return VC_CONTAINER_SUCCESS;
 }
Variable Documentation
key
VC_CONTAINER_METADATA_KEY_T key
Definition at line 323 of file containers_utils.c.
Referenced by delete(), insert(), iterate(), khrn_hashlittle(), and lookup().
name
const char* name
Definition at line 324 of file containers_utils.c.