VideoCore Library: interface/vmcs_host/vc_vchi_cecservice.c File Reference
vc_vchi_cecservice.c File Reference
#include <string.h>
#include <stdio.h>
#include "vchost_platform_config.h"
#include "vchost.h"
#include "interface/vcos/vcos.h"
#include "interface/vchi/vchi.h"
#include "interface/vchi/common/endian.h"
#include "interface/vchi/message_drivers/message.h"
#include "vc_cecservice.h"
#include "vc_service_common.h"
Classes
struct CECSERVICE_HOST_STATE_T
Macros
#define _min(x, y) (((x) <= (y))? (x) : (y))
#define _max(x, y) (((x) >= (y))? (x) : (y))
Functions
VCHPRE_ void VCHPOST_ vc_vchi_cec_init (VCHI_INSTANCE_T initialise_instance, VCHI_CONNECTION_T **connections, uint32_t num_connections)
VCHPRE_ void VCHPOST_ vc_vchi_cec_stop (void)
VCHPRE_ void VCHPOST_ vc_cec_register_callback (CECSERVICE_CALLBACK_T callback, void *callback_data)
VCHPRE_ int VCOS_DEPRECATED ("has no effect")
VCHPRE_ int VCHPOST_ vc_cec_send_message (const uint32_t follower, const uint8_t *payload, uint32_t length, vcos_bool_t is_reply)
VCHPRE_ int VCHPOST_ vc_cec_get_logical_address (CEC_AllDevices_T *logical_address)
VCHPRE_ int VCHPOST_ vc_cec_alloc_logical_address (void)
VCHPRE_ int VCHPOST_ vc_cec_release_logical_address (void)
VCHPRE_ int VCOS_DEPRECATED ("returns invalid result")
VCHPRE_ int VCHPOST_ vc_cec_set_vendor_id (uint32_t id)
VCHPRE_ int VCHPOST_ vc_cec_set_osd_name (const char *name)
VCHPRE_ int VCHPOST_ vc_cec_get_physical_address (uint16_t *physical_address)
VCHPRE_ int VCHPOST_ vc_cec_get_vendor_id (const CEC_AllDevices_T logical_address, uint32_t *vendor_id)
VCHPRE_ CEC_DEVICE_TYPE_T VCHPOST_ vc_cec_device_type (const CEC_AllDevices_T logical_address)
VCHPRE_ int VCHPOST_ vc_cec_send_message2 (const VC_CEC_MESSAGE_T *message)
VCHPRE_ int VCHPOST_ vc_cec_param2message (const uint32_t reason, const uint32_t param1, const uint32_t param2, const uint32_t param3, const uint32_t param4, VC_CEC_MESSAGE_T *message)
VCHPRE_ int VCHPOST_ vc_cec_poll_address (const CEC_AllDevices_T logical_address)
VCHPRE_ int VCHPOST_ vc_cec_set_logical_address (const CEC_AllDevices_T logical_address, const CEC_DEVICE_TYPE_T device_type, const uint32_t vendor_id)
VCHPRE_ int VCHPOST_ vc_cec_set_passive (vcos_bool_t enabled)
VCHPRE_ int VCHPOST_ vc_cec_send_FeatureAbort (uint32_t follower, CEC_OPCODE_T opcode, CEC_ABORT_REASON_T reason)
VCHPRE_ int VCHPOST_ vc_cec_send_ActiveSource (uint16_t physical_address, vcos_bool_t is_reply)
VCHPRE_ int VCHPOST_ vc_cec_send_ImageViewOn (uint32_t follower, vcos_bool_t is_reply)
VCHPRE_ int VCHPOST_ vc_cec_send_SetOSDString (uint32_t follower, CEC_DISPLAY_CONTROL_T disp_ctrl, const char *string, vcos_bool_t is_reply)
VCHPRE_ int VCHPOST_ vc_cec_send_Standby (uint32_t follower, vcos_bool_t is_reply)
VCHPRE_ int VCHPOST_ vc_cec_send_MenuStatus (uint32_t follower, CEC_MENU_STATE_T menu_state, vcos_bool_t is_reply)
VCHPRE_ int VCHPOST_ vc_cec_send_ReportPhysicalAddress (uint16_t physical_address, CEC_DEVICE_TYPE_T device_type, vcos_bool_t is_reply)
Variables
VCOS_LOG_CAT_T cechost_log_category
Macro Definition Documentation
_max
#define _max (x, y) (((x) >= (y))? (x) : (y))
Definition at line 46 of file vc_vchi_cecservice.c.
Referenced by khrn_vector_extend().
_min
#define _min (x, y) (((x) <= (y))? (x) : (y))
Definition at line 43 of file vc_vchi_cecservice.c.
Referenced by vc_cec_send_message(), and vc_cec_send_SetOSDString().
Function Documentation
vc_cec_alloc_logical_address()
VCHPRE_ int VCHPOST_ vc_cec_alloc_logical_address (void)
vc_cec_alloc_logical_address starts the allocation of a logical address. Logical address is automatically allocated after HDMI power on is complete and AV mute is deassert. The host only needs to call this if the initial allocation failed (logical address being 0xF and physical address is NOT 0xFFFF from VC_CEC_LOGICAL_ADDR notification), or if the host explicitly released its logical address.
Parameters
none
Returns
zero if the command is successful, non-zero otherwise If successful, there will be a callback notification VC_CEC_LOGICAL_ADDR. The host should wait for this before calling this function again.
Definition at line 800 of file vc_vchi_cecservice.c.
{
    return cecservice_send_command( VC_CEC_ALLOC_LOGICAL_ADDR, NULL, 0, 0);
 }
vc_cec_device_type()
VCHPRE_ CEC_DEVICE_TYPE_T VCHPOST_ vc_cec_device_type (const CEC_AllDevices_T logical_address)
vc_cec_device_type(returns the default device type of a particular logical address, which can be used as the argument to vc_cec_send_ReportPhysicalAddress.
Parameters
logical address
Returns
the default device type, if there is any error, the return device type will be CEC_DeviceType_Invalid
Definition at line 959 of file vc_vchi_cecservice.c.
References CEC_AllDevices_eAudioSystem, CEC_AllDevices_eDVD1, CEC_AllDevices_eDVD2, CEC_AllDevices_eDVD3, CEC_AllDevices_eFreeUse, CEC_AllDevices_eRec1, CEC_AllDevices_eRec2, CEC_AllDevices_eRec3, CEC_AllDevices_eRsvd3, CEC_AllDevices_eRsvd4, CEC_AllDevices_eSTB1, CEC_AllDevices_eSTB2, CEC_AllDevices_eSTB3, CEC_AllDevices_eSTB4, CEC_AllDevices_eTV, CEC_DeviceType_Audio, CEC_DeviceType_Invalid, CEC_DeviceType_Playback, CEC_DeviceType_Rec, CEC_DeviceType_Reserved, CEC_DeviceType_Tuner, CEC_DeviceType_TV, and vcos_assert.
{
    CEC_DEVICE_TYPE_T device_type = CEC_DeviceType_Invalid;
    switch(logical_address) {
    case CEC_AllDevices_eSTB1:
    case CEC_AllDevices_eSTB2:
    case CEC_AllDevices_eSTB3:
    case CEC_AllDevices_eSTB4:
       device_type = CEC_DeviceType_Tuner;
       break;
    case CEC_AllDevices_eDVD1:
    case CEC_AllDevices_eDVD2:
    case CEC_AllDevices_eDVD3:
       device_type = CEC_DeviceType_Playback;
       break;
    case CEC_AllDevices_eRec1:
    case CEC_AllDevices_eRec2:
    case CEC_AllDevices_eRec3:
       device_type = CEC_DeviceType_Rec;
       break;
    case CEC_AllDevices_eAudioSystem:
       device_type = CEC_DeviceType_Audio;
       break;
    case CEC_AllDevices_eTV:
       device_type = CEC_DeviceType_TV;
       break;
    case CEC_AllDevices_eRsvd3:
    case CEC_AllDevices_eRsvd4:
    case CEC_AllDevices_eFreeUse:
       device_type = CEC_DeviceType_Reserved; //XXX: Are we allowed to use this?
       break;
    default:
       vcos_assert(0); //Invalid
       break;
    }
    return device_type;
 }
vc_cec_get_logical_address()
VCHPRE_ int VCHPOST_ vc_cec_get_logical_address (CEC_AllDevices_T * logical_address)
vc_cec_get_logical_address gets the logical address, If one is being allocated 0xF (unregistered) will be set. A address value of 0xF also means CEC system is not yet ready to send or receive any messages.
Parameters
pointer to logical address (set to allocated address)
Returns
zero if the command is successful, non-zero otherwise logical_address is not modified if command failed
Definition at line 771 of file vc_vchi_cecservice.c.
{
    uint32_t response;
    int32_t success = cecservice_send_command_reply( VC_CEC_GET_LOGICAL_ADDR, NULL, 0,
                                                     &response, sizeof(response));
    if(success == 0) {
       *logical_address = (CEC_AllDevices_T)(VC_VTOH32(response) & 0xF);
       vc_cec_log_info("CEC got logical address %d", *logical_address);
    }
    return success;
 }
vc_cec_get_physical_address()
VCHPRE_ int VCHPOST_ vc_cec_get_physical_address (uint16_t * physical_address)
vc_cec_get_physical_address gets our physical address
Parameters
pointer to physical address (returned as 16-bit packed value)
Returns
zero if the command is successful, non-zero otherwise If failed, physical address argument will not be changed A physical address of 0xFFFF means CEC is not supported
Definition at line 902 of file vc_vchi_cecservice.c.
{
    uint32_t response;
    int32_t success = cecservice_send_command_reply( VC_CEC_GET_PHYSICAL_ADDR, NULL, 0,
                                                     &response, sizeof(response));
    if(success == 0) {
       *physical_address = (uint16_t)(VC_VTOH32(response) & 0xFFFF);
       vc_cec_log_info("CEC got physical address: %d.%d.%d.%d",
                       (*physical_address >> 12), (*physical_address >> 8) & 0xF,
                       (*physical_address >> 4) & 0xF, (*physical_address) & 0xF);
    }
    return success;
 }
vc_cec_get_vendor_id()
VCHPRE_ int VCHPOST_ vc_cec_get_vendor_id (const CEC_AllDevices_T logical_address, uint32_t * vendor_id)
vc_cec_get_vendor_id(gets the vendor id of a particular logical address
Parameters
logical_address is the logical address of the device [in]
vendorid is the pointer to vendor ID (24-bit IEEE OUI value) [out]
Returns
zero if the command is successful, non-zero otherwise If failed, vendor id argument will not be changed A vendor ID of 0xFFFFFF means the device does not exist A vendor ID of 0x0 means vendor ID is not known and the application can send <Give device="" vendor="" id>=""> to that device
Definition at line 932 of file vc_vchi_cecservice.c.
References VC_HTOV32.
{
    uint32_t log_addr = VC_HTOV32(logical_address);
    uint32_t response;
    int32_t success = cecservice_send_command_reply( VC_CEC_GET_VENDOR_ID, &log_addr, sizeof(log_addr),
                                                     &response, sizeof(response));
    if(success == 0) {
       vcos_assert(vendor_id);
       *vendor_id = VC_VTOH32(response);
       vc_cec_log_info("CEC got vendor id 0x%X", *vendor_id);
    }
    return success;
 }
vc_cec_param2message()
VCHPRE_ int VCHPOST_ vc_cec_param2message (const uint32_t reason, const uint32_t param1, const uint32_t param2, const uint32_t param3, const uint32_t param4, VC_CEC_MESSAGE_T * message)
Definition at line 1037 of file vc_vchi_cecservice.c.
References CEC_CB_FOLLOWER, CEC_CB_INITIATOR, CEC_CB_MSG_LENGTH, CEC_CB_REASON, VC_CEC_MESSAGE_T::follower, VC_CEC_MESSAGE_T::initiator, VC_CEC_MESSAGE_T::length, VC_CEC_MESSAGE_T::payload, VC_CEC_LOGICAL_ADDR, VC_CEC_TOPOLOGY, vcos_memcpy(), vcos_memset(), and vcos_verify.
{
    if(vcos_verify(message &&
                   CEC_CB_REASON(reason) != VC_CEC_LOGICAL_ADDR &&
                   CEC_CB_REASON(reason) != VC_CEC_TOPOLOGY)) {
       message->length = CEC_CB_MSG_LENGTH(reason) - 1; //Length is without the header byte
       message->initiator = CEC_CB_INITIATOR(param1);
       message->follower = CEC_CB_FOLLOWER(param1);
       if(message->length) {
          uint32_t tmp = param1 >> 8;
          vcos_memcpy(message->payload, &tmp, sizeof(uint32_t)-1);
          vcos_memcpy(message->payload+sizeof(uint32_t)-1, &param2, sizeof(uint32_t));
          vcos_memcpy(message->payload+sizeof(uint32_t)*2-1, &param3, sizeof(uint32_t));
          vcos_memcpy(message->payload+sizeof(uint32_t)*3-1, &param4, sizeof(uint32_t));
       } else {
          vcos_memset(message->payload, 0, sizeof(message->payload));
       }
       return 0;
    } else {
       return -1;
    }
 }
vc_cec_poll_address()
VCHPRE_ int VCHPOST_ vc_cec_poll_address (const CEC_AllDevices_T logical_address)
vc_cec_poll_address sets and polls a particular address to find out its availability in the CEC network. Only available when CEC is running in passive mode. The host can only call this function during logical address allocation stage.
Parameters
logical address to try
Returns
0 if poll is successful (address is occupied) >0 if poll is unsuccessful (Error code is in VC_CEC_ERROR_T in vc_cec.h) <0 VCHI errors
Definition at line 1079 of file vc_vchi_cecservice.c.
References VC_CEC_ERROR_INVALID_ARGUMENT, vc_cec_log_info, and VC_HTOV32.
{
    uint32_t log_addr = VC_HTOV32(logical_address);
    int32_t response =  VC_CEC_ERROR_INVALID_ARGUMENT;
    int32_t success = -1;
    vc_cec_log_info("CEC polling address %d", logical_address);
    success = cecservice_send_command_reply( VC_CEC_POLL_ADDR, &log_addr, sizeof(log_addr),
                                                     &response, sizeof(response));
    return (success == 0)? response : success;
 }
vc_cec_register_callback()
VCHPRE_ void VCHPOST_ vc_cec_register_callback (CECSERVICE_CALLBACK_T callback, void * callback_data)
Host applications use vc_cec_register_callaback to register callback to handle all CEC notifications. If more than one applications need to use CEC, there should be ONE central application which acts on behalf of all clients and handles all communications with CEC services.
Parameters
callback function
context to be passed when function is called
Returns
void
Definition at line 355 of file vc_vchi_cecservice.c.
{
    if(lock_obtain() == 0){
       cecservice_client.notify_fn   = callback;
       cecservice_client.notify_data = callback_data;
       vc_cec_log_info("CEC service registered callback 0x%x", (uint32_t) callback);
       lock_release();
    } else {
       vc_cec_log_error("CEC service registered callback 0x%x failed", (uint32_t) callback);
    }
 }
vc_cec_release_logical_address()
VCHPRE_ int VCHPOST_ vc_cec_release_logical_address (void)
Normally vc_cec_release_logical_address will not be called by the host application. It is used to release our logical address. This effectively disables CEC. The host will need to allocate a new logical address before doing any CEC calls (send/receive message, get topology, etc.).
Parameters
none
Returns
zero if the command is successful, non-zero otherwise The host should get a callback VC_CEC_LOGICAL_ADDR with 0xF being the logical address and 0xFFFF being the physical address.
Definition at line 819 of file vc_vchi_cecservice.c.
{
    return cecservice_send_command( VC_CEC_RELEASE_LOGICAL_ADDR, NULL, 0, 0);
 }
vc_cec_send_ActiveSource()
VCHPRE_ int VCHPOST_ vc_cec_send_ActiveSource (uint16_t physical_address, vcos_bool_t is_reply)
vc_cec_send_ActiveSource broadcasts <Active source>=""> to all devices
Parameters
physical address (16-bit packed)
reply or not (normally not)
Returns
zero if the command is successful, non-zero otherwise Tx callback if successful
Definition at line 1220 of file vc_vchi_cecservice.c.
References CEC_BROADCAST_ADDR, CEC_Opcode_ActiveSource, and vc_cec_send_message().
{
    uint8_t tx_buf[3];
    tx_buf[0] = CEC_Opcode_ActiveSource;    // <Active Source>
    tx_buf[1] = physical_address >> 8;      // physical address msb
    tx_buf[2] = physical_address & 0x00FF;  // physical address lsb
    return vc_cec_send_message(CEC_BROADCAST_ADDR, // This is a broadcast only message
                               tx_buf,
                               sizeof(tx_buf),
                               is_reply);
 }
vc_cec_send_FeatureAbort()
VCHPRE_ int VCHPOST_ vc_cec_send_FeatureAbort (uint32_t follower, CEC_OPCODE_T opcode, CEC_ABORT_REASON_T reason)
Functions beginning with vc_cec_send_xxx make it easier for the host application to send CEC message xxx to other devices vc_cec_send_FeatureAbort sends <Feature abort>=""> for a received command.
Parameters
follower (cannot be 0xF)
rejected opcode
reject reason CEC_ABORT_REASON_T
Returns
zero if the command is successful, non-zero otherwise Tx callback if successful
Definition at line 1195 of file vc_vchi_cecservice.c.
References CEC_Opcode_FeatureAbort, vc_cec_send_message(), and VC_TRUE.
{
    uint8_t tx_buf[3];
    tx_buf[0] = CEC_Opcode_FeatureAbort;    // <Feature Abort>
    tx_buf[1] = opcode;
    tx_buf[2] = reason;
    return vc_cec_send_message(follower,
                               tx_buf,
                               sizeof(tx_buf),
                               VC_TRUE);
 }
vc_cec_send_ImageViewOn()
VCHPRE_ int VCHPOST_ vc_cec_send_ImageViewOn (uint32_t follower, vcos_bool_t is_reply)
vc_cec_send_ImageViewOn sends <Image view="" on>="">
Parameters
follower
reply or not (normally not)
Returns
zero if the command is successful, non-zero otherwise Tx callback if successful
Definition at line 1243 of file vc_vchi_cecservice.c.
References CEC_Opcode_ImageViewOn, and vc_cec_send_message().
{
    uint8_t tx_buf[1];
    tx_buf[0] = CEC_Opcode_ImageViewOn;      // <Image View On> no param required
    return vc_cec_send_message(follower,
                               tx_buf,
                               sizeof(tx_buf),
                               is_reply);
 }
vc_cec_send_MenuStatus()
VCHPRE_ int VCHPOST_ vc_cec_send_MenuStatus (uint32_t follower, CEC_MENU_STATE_T menu_state, vcos_bool_t is_reply)
vc_cec_send_MenuStatus sends <Menu status>=""> (response to <Menu request>="">)
Parameters
follower
menu state CEC_MENU_STATE_T but NOT CEC_MENU_STATE_QUERY
reply or not (should always be yes)
Returns
zero if the command is successful, non-zero otherwise Tx callback if successful
Definition at line 1314 of file vc_vchi_cecservice.c.
References CEC_MENU_STATE_QUERY, CEC_Opcode_MenuStatus, vc_cec_send_message(), and vcos_verify.
{
    uint8_t tx_buf[2];
    if(!vcos_verify(menu_state < CEC_MENU_STATE_QUERY))
       return -1;
    tx_buf[0] = CEC_Opcode_MenuStatus;        // <Menu Status>
    tx_buf[1] = menu_state;
    return vc_cec_send_message(follower,
                               tx_buf,
                               sizeof(tx_buf),
                               is_reply);
 }
vc_cec_send_message()
VCHPRE_ int VCHPOST_ vc_cec_send_message (const uint32_t follower, const uint8_t * payload, uint32_t length, vcos_bool_t is_reply)
vc_cec_send_message allows a host application to send a CEC message to another device. There are several built-in functions for sending command messages. The host application MUST have a valid logical address (between 1 and 14 inclusive) before it can send a message. (For poll message set payload to NULL and length to zero).
Parameters
Follower's logical address
Message payload WITHOUT the header byte (can be NULL)
Payload length WITHOUT the header byte (can be zero)
VC_TRUE if the message is a reply to an incoming message
Returns
zero if the command is successful, non-zero otherwise If the command is successful, there will be a Tx callback in due course to indicate whether the message has been acknowledged by the recipient or not
Definition at line 726 of file vc_vchi_cecservice.c.
References _min, CEC_MAX_XMIT_LENGTH, CEC_SEND_MSG_PARAM_T::follower, CEC_SEND_MSG_PARAM_T::is_reply, CEC_SEND_MSG_PARAM_T::length, CECSERVICE_HOST_STATE_T::logical_address, CEC_SEND_MSG_PARAM_T::payload, vc_cec_log_info, VC_HTOV32, vcos_memcpy(), vcos_memset(), and vcos_verify.
Referenced by vc_cec_send_ActiveSource(), vc_cec_send_FeatureAbort(), vc_cec_send_ImageViewOn(), vc_cec_send_MenuStatus(), vc_cec_send_message2(), vc_cec_send_ReportPhysicalAddress(), vc_cec_send_SetOSDString(), and vc_cec_send_Standby().
{
    int success = -1;
    CEC_SEND_MSG_PARAM_T param;
    if(!vcos_verify(length <= CEC_MAX_XMIT_LENGTH))
       return -1;
    param.follower = VC_HTOV32(follower);
    param.length = VC_HTOV32(length);
    param.is_reply = VC_HTOV32(is_reply);
    vcos_memset(param.payload, 0, sizeof(param.payload));
    vc_cec_log_info("CEC service sending CEC message (%d->%d) (0x%02X) length %d%s",
                    cecservice_client.logical_address, follower,
                    (payload)? payload[0] : 0xFF, length, (is_reply)? " as reply" : "");
    if(length > 0 && vcos_verify(payload)) {
       char s[96] = {0}, *p = &s[0];
       int i;
       vcos_memcpy(param.payload, payload, _min(length, CEC_MAX_XMIT_LENGTH));
       p += sprintf(p, "0x%02X",  (cecservice_client.logical_address << 4) | (follower & 0xF));
       for(i = 0; i < _min(length, CEC_MAX_XMIT_LENGTH); i++) {
          p += sprintf(p, " %02X", payload[i]);
       }
       vc_cec_log_info("CEC message: %s", s);
    }
    success = cecservice_send_command( VC_CEC_SEND_MSG, &param, sizeof(param), 1);
    return success;
 }
vc_cec_send_message2()
VCHPRE_ int VCHPOST_ vc_cec_send_message2 (const VC_CEC_MESSAGE_T * message)
These couple of functions are provided for host application's convenience: If the xmit message is encapsulate in a VC_CEC_MESSAGE_T then it can be sent as a normal message (not as a reply) and the initiator field is ignored with vc_cec_send_message2 and return zero for success
Applications can call vc_cec_param2message to turn the callback parameters into a VC_CEC_MESSAGE_T (not for LOGICAL_ADDR and TOPOLOGY callbacks). It also returns zero for success.
Definition at line 1011 of file vc_vchi_cecservice.c.
References VC_CEC_MESSAGE_T::follower, VC_CEC_MESSAGE_T::length, NULL, VC_CEC_MESSAGE_T::payload, vc_cec_send_message(), VC_FALSE, and vcos_verify.
{
    if(vcos_verify(message)) {
       return vc_cec_send_message(message->follower,
                                  (message->length)?
                                  message->payload : NULL,
                                  message->length,
                                  VC_FALSE);
    } else {
       return -1;
    }
 }
vc_cec_send_ReportPhysicalAddress()
VCHPRE_ int VCHPOST_ vc_cec_send_ReportPhysicalAddress (uint16_t physical_address, CEC_DEVICE_TYPE_T device_type, vcos_bool_t is_reply)
vc_cec_send_ReportPhysicalAddress broadcasts <Report physical="" address>=""> to all devices. Note although the passed in device type can be override the default one associated the allocated logical address, it is not recommended to do so. One can use vc_cec_device_type to get the default device type associated with the logical address returned via VC_CEC_LOGICAL_ADDR callback.
Parameters
physical address (16-bit packed)
device type to be broadcasted
reply or not (normally not)
Returns
zero if the command is successful, non-zero otherwise Tx callback if successful
Definition at line 1345 of file vc_vchi_cecservice.c.
References CEC_BROADCAST_ADDR, CEC_CLEAR_ADDR, CEC_Opcode_ReportPhysicalAddress, CECSERVICE_HOST_STATE_T::physical_address, VC_CEC_ERROR_NO_PA, vc_cec_log_error, vc_cec_send_message(), and vcos_verify.
{
    uint8_t tx_buf[4];
    if(vcos_verify(physical_address == cecservice_client.physical_address &&
                   cecservice_client.physical_address != CEC_CLEAR_ADDR)) {
       tx_buf[0] = CEC_Opcode_ReportPhysicalAddress;
       tx_buf[1] = physical_address >> 8;       // physical address msb
       tx_buf[2] = physical_address & 0x00FF;   // physical address lsb
       tx_buf[3] = device_type;                 // 'device type'
       return vc_cec_send_message(CEC_BROADCAST_ADDR, // This is a broadcast only message
                                  tx_buf,
                                  sizeof(tx_buf),
                                  is_reply);
    } else {
       //Current we do not allow sending a random physical address
       vc_cec_log_error("CEC cannot send physical address 0x%X, does not match internal 0x%X",
                        physical_address, cecservice_client.physical_address);
       return VC_CEC_ERROR_NO_PA;
    }
 }
vc_cec_send_SetOSDString()
VCHPRE_ int VCHPOST_ vc_cec_send_SetOSDString (uint32_t follower, CEC_DISPLAY_CONTROL_T disp_ctrl, const char * string, vcos_bool_t is_reply)
vc_cec_send_SetOSDString sends <Set osd="" string>="">
Parameters
follower
string (char[13])
display control CEC_DISPLAY_CONTROL_T
reply or not (normally not)
Returns
zero if the command is successful, non-zero otherwise Tx callback if successful
Definition at line 1265 of file vc_vchi_cecservice.c.
References _min, CEC_MAX_XMIT_LENGTH, CEC_Opcode_SetOSDString, vc_cec_send_message(), vcos_memcpy(), and vcos_memset().
{
    uint8_t tx_buf[CEC_MAX_XMIT_LENGTH];
    tx_buf[0] = CEC_Opcode_SetOSDString;     // <Set OSD String>
    tx_buf[1] = disp_ctrl;
    vcos_memset(&tx_buf[2], 0, sizeof(tx_buf)-2);
    vcos_memcpy(&tx_buf[2], string, _min(strlen(string), CEC_MAX_XMIT_LENGTH-2));
    return vc_cec_send_message(follower,
                               tx_buf,
                               sizeof(tx_buf),
                               is_reply);
 }
vc_cec_send_Standby()
VCHPRE_ int VCHPOST_ vc_cec_send_Standby (uint32_t follower, vcos_bool_t is_reply)
vc_cec_send_Standby sends <Standby>. This will put any/all devices to standby if they support this CEC message.
Parameters
follower (can be 0xF)
reply or not (normally not)
Returns
zero if the command is successful, non-zero otherwise Tx callback if successful
Definition at line 1292 of file vc_vchi_cecservice.c.
References CEC_Opcode_Standby, and vc_cec_send_message().
{
    uint8_t tx_buf[1];
    tx_buf[0] = CEC_Opcode_Standby;           // <Standby>
    return vc_cec_send_message(follower,
                               tx_buf,
                               sizeof(tx_buf),
                               is_reply);
 }
vc_cec_set_logical_address()
VCHPRE_ int VCHPOST_ vc_cec_set_logical_address (const CEC_AllDevices_T logical_address, const CEC_DEVICE_TYPE_T device_type, const uint32_t vendor_id)
vc_cec_set_logical_address sets the logical address, device type and vendor ID to be in use. Only available when CEC is running in passive mode. It is the responsibility of the host to make sure the logical address is actually free to be used. Physical address will be what is read from EDID.
Parameters
logical address
device type
vendor ID
Returns
0 if successful, non-zero otherwise
Definition at line 1104 of file vc_vchi_cecservice.c.
References CEC_AllDevices_eUnRegistered, CEC_DeviceType_Invalid, CEC_DeviceType_VidProc, VC_CEC_ERROR_INVALID_ARGUMENT, vc_cec_log_info, VC_HTOV32, and vcos_verify.
{
    CEC_SET_LOGICAL_ADDR_PARAM_T param = {VC_HTOV32(logical_address),
                                          VC_HTOV32(device_type),
                                          VC_HTOV32(vendor_id)};
    int32_t response = VC_CEC_ERROR_INVALID_ARGUMENT;
    int32_t success = VC_CEC_ERROR_INVALID_ARGUMENT;
    if(vcos_verify(logical_address <= CEC_AllDevices_eUnRegistered &&
                   (device_type <= CEC_DeviceType_VidProc ||
                    device_type == CEC_DeviceType_Invalid))) {
       vc_cec_log_info("CEC setting logical address to %d; device type %s; vendor 0x%X",
                       logical_address,
                       cecservice_devicetype_strings[device_type], vendor_id );
       success = cecservice_send_command_reply( VC_CEC_SET_LOGICAL_ADDR, &param, sizeof(param),
                                                &response, sizeof(response));
    } else {
       vc_cec_log_error("CEC invalid arguments for set_logical_address");
    }
    return (success == 0)? response : success;
 }
vc_cec_set_osd_name()
VCHPRE_ int VCHPOST_ vc_cec_set_osd_name (const char * name)
Use vc_cec_set_osd_name to set the response to <Give osd="" name>="">
Parameters
OSD name (14 byte char array)
Returns
zero if the command is successful, non-zero otherwise
Definition at line 884 of file vc_vchi_cecservice.c.
References vc_cec_log_info.
{
    vc_cec_log_info("CEC setting OSD name to %s", name);
    return cecservice_send_command( VC_CEC_SET_OSD_NAME, name, OSD_NAME_LENGTH, 0);
 }
vc_cec_set_passive()
VCHPRE_ int VCHPOST_ vc_cec_set_passive (vcos_bool_t enabled)
vc_cec_set_passive enables and disables passive mode. Call this function first (with VC_TRUE as the argument) to enable passive mode before calling any of the above passive API functions
Parameters
TRUE to enable passive mode, FALSE to disable
Returns
0 if successful, non-zero otherwise
Definition at line 1170 of file vc_vchi_cecservice.c.
References VC_HTOV32.
{
    uint32_t param = VC_HTOV32(enabled);
    int32_t response;
    int32_t success = cecservice_send_command_reply( VC_CEC_SET_PASSIVE, &param, sizeof(param),
                                                     &response, sizeof(response));
    return (success == 0)? response : success;
 }
vc_cec_set_vendor_id()
VCHPRE_ int VCHPOST_ vc_cec_set_vendor_id (const uint32_t id)
Use vc_cec_set_vendor_id to set the response to <Give device="" vendor="" id>="">
Parameters
24-bit IEEE vendor id
Returns
zero if the command is successful, non-zero otherwise
Definition at line 867 of file vc_vchi_cecservice.c.
References vc_cec_log_info, and VC_HTOV32.
{
    uint32_t vendor_id = VC_HTOV32(id);
    vc_cec_log_info("CEC setting vendor id to 0x%x", vendor_id);
    return cecservice_send_command( VC_CEC_SET_VENDOR_ID, &vendor_id, sizeof(vendor_id), 0);
 }
vc_vchi_cec_init()
VCHPRE_ void VCHPOST_ vc_vchi_cec_init (VCHI_INSTANCE_T initialise_instance, VCHI_CONNECTION_T ** connections, uint32_t num_connections)
Call vc_vchi_cec_init to initialise the CEC service for use.
Parameters
initialise_instance is the VCHI instance
connections are array of pointers to VCHI connections
num_connections is the number of connections in array
Returns
void
Definition at line 213 of file vc_vchi_cecservice.c.
References CEC_AllDevices_eUnRegistered, CEC_CLEAR_ADDR, CECSERVICE_CLIENT_NAME, CECSERVICE_HOST_STATE_T::initialised, CECSERVICE_HOST_STATE_T::lock, CECSERVICE_HOST_STATE_T::logical_address, CECSERVICE_HOST_STATE_T::num_connections, CECSERVICE_HOST_STATE_T::physical_address, status, CECSERVICE_HOST_STATE_T::topology, vc_cec_log_info, VC_CECSERVICE_VER, VCHI_VERSION, vcos_assert, vcos_event_create(), vcos_malloc_aligned(), vcos_memset(), vcos_mutex_create(), and VCOS_SUCCESS.
{
    int32_t success = -1;
    VCOS_STATUS_T status;
    VCOS_THREAD_ATTR_T attrs;
    uint32_t i;
    if (cecservice_client.initialised)
      return;
    vc_cec_log_info("Initialising CEC service");
    // record the number of connections
    vcos_memset( &cecservice_client, 0, sizeof(CECSERVICE_HOST_STATE_T) );
    cecservice_client.num_connections = num_connections;
    cecservice_client.physical_address = CEC_CLEAR_ADDR;
    cecservice_client.logical_address = CEC_AllDevices_eUnRegistered;
    status = vcos_mutex_create(&cecservice_client.lock, "HCEC");
    vcos_assert(status == VCOS_SUCCESS);
    status = vcos_event_create(&cecservice_message_available_event, "HCEC");
    vcos_assert(status == VCOS_SUCCESS);
    status = vcos_event_create(&cecservice_notify_available_event, "HCEC");
    vcos_assert(status == VCOS_SUCCESS);
    cecservice_client.topology = vcos_malloc_aligned(sizeof(VC_CEC_TOPOLOGY_T), 16, "HCEC topology");
    vcos_assert(cecservice_client.topology);
    for (i=0; i < cecservice_client.num_connections; i++) {
       // Create a 'Client' service on the each of the connections
       SERVICE_CREATION_T cecservice_parameters = { VCHI_VERSION(VC_CECSERVICE_VER),
                                                    CECSERVICE_CLIENT_NAME,     // 4cc service code
                                                    connections[i],             // passed in fn ptrs
                                                    0,                          // tx fifo size (unused)
                                                    0,                          // tx fifo size (unused)
                                                    &cecservice_client_callback,// service callback
                                                    &cecservice_message_available_event,  // callback parameter
                                                    VC_FALSE,                   // want_unaligned_bulk_rx
                                                    VC_FALSE,                   // want_unaligned_bulk_tx
                                                    VC_FALSE,                   // want_crc
       };
       SERVICE_CREATION_T cecservice_parameters2 = { VCHI_VERSION(VC_CECSERVICE_VER),
                                                     CECSERVICE_NOTIFY_NAME,    // 4cc service code
                                                     connections[i],            // passed in fn ptrs
                                                     0,                         // tx fifo size (unused)
                                                     0,                         // tx fifo size (unused)
                                                     &cecservice_notify_callback,// service callback
                                                     &cecservice_notify_available_event,  // callback parameter
                                                     VC_FALSE,                  // want_unaligned_bulk_rx
                                                     VC_FALSE,                  // want_unaligned_bulk_tx
                                                     VC_FALSE,                  // want_crc
       };
       //Create the client to normal CEC service
       success = vchi_service_open( initialise_instance, &cecservice_parameters, &cecservice_client.client_handle[i] );
       vcos_assert( success == 0 );
       if(success)
          vc_cec_log_error("Failed to connected to CEC service: %d", success);
       //Create the client to the async CEC service (any CEC related notifications)
       success = vchi_service_open( initialise_instance, &cecservice_parameters2, &cecservice_client.notify_handle[i] );
       vcos_assert( success == 0 );
       if(success)
          vc_cec_log_error("Failed to connected to CEC async service: %d", success);
       vchi_service_release(cecservice_client.client_handle[i]);
       vchi_service_release(cecservice_client.notify_handle[i]);
    }
    //Create the notifier task
    vcos_thread_attr_init(&attrs);
    vcos_thread_attr_setstacksize(&attrs, 2048);
    vcos_thread_attr_settimeslice(&attrs, 1);
    //Initialise logging
    cecservice_logging_init();
    status = vcos_thread_create(&cecservice_notify_task, "HCEC Notify", &attrs, cecservice_notify_func, &cecservice_client);
    vcos_assert(status == VCOS_SUCCESS);
    cecservice_client.initialised = 1;
    vc_cec_log_info("CEC service initialised");
 }
vc_vchi_cec_stop()
VCHPRE_ void VCHPOST_ vc_vchi_cec_stop (void)
Call vc_vchi_cec_stop to stop host side CEC service.
Parameters
none
Returns
void
Definition at line 309 of file vc_vchi_cecservice.c.
References CECSERVICE_HOST_STATE_T::initialised.
{
    // Wait for the current lock-holder to finish before zapping TV service
    uint32_t i;
    if (!cecservice_client.initialised)
       return;
    if(lock_obtain() == 0)
    {
       void *dummy;
       vchi_service_release(cecservice_client.client_handle[0]);
       vc_cec_log_info("Stopping CEC service");
       for (i=0; i < cecservice_client.num_connections; i++) {
          int32_t result;
          vchi_service_use(cecservice_client.client_handle[i]);
          vchi_service_use(cecservice_client.notify_handle[i]);
          result = vchi_service_close(cecservice_client.client_handle[i]);
          vcos_assert( result == 0 );
          result = vchi_service_close(cecservice_client.notify_handle[i]);
          vcos_assert( result == 0 );
       }
       cecservice_client.initialised = 0;
       lock_release();
       cecservice_client.to_exit = 1;
       vcos_event_signal(&cecservice_notify_available_event);
       vcos_thread_join(&cecservice_notify_task, &dummy);
       vcos_mutex_delete(&cecservice_client.lock);
       vcos_event_delete(&cecservice_message_available_event);
       vcos_event_delete(&cecservice_notify_available_event);
       vcos_free(cecservice_client.topology);
       vc_cec_log_info("CEC service stopped");
    }
 }
VCOS_DEPRECATED() [1/2]
VCHPRE_ int VCOS_DEPRECATED ("has no effect")
Definition at line 664 of file vc_vchi_cecservice.c.
References vc_cec_deregister_all(), vc_cec_deregister_command(), vc_cec_register_all(), VCHPOST_, and VCHPRE_.
{
    return 0;
 }
VCOS_DEPRECATED() [2/2]
VCHPRE_ int VCOS_DEPRECATED ("returns invalid result")
Definition at line 833 of file vc_vchi_cecservice.c.
References CECSERVICE_HOST_STATE_T::client_handle, and vchi_service_use().
{
    int32_t success = -1;
    vchi_service_use(cecservice_client.client_handle[0]);
    success = cecservice_send_command( VC_CEC_GET_TOPOLOGY, NULL, 0, 1);
    if(success == 0) {
       success = cecservice_wait_for_bulk_receive(cecservice_client.topology, sizeof(VC_CEC_TOPOLOGY_T));
    }
    vchi_service_release(cecservice_client.client_handle[0]);
    if(success == 0) {
       int i;
       cecservice_client.topology->active_mask = VC_VTOH16(cecservice_client.topology->active_mask);
       cecservice_client.topology->num_devices = VC_VTOH16(cecservice_client.topology->num_devices);
       vc_cec_log_info("CEC topology: mask=0x%x; #device=%d",
                       cecservice_client.topology->active_mask,
                       cecservice_client.topology->num_devices);
       for(i = 0; i < 15; i++) {
          cecservice_client.topology->device_attr[i] = VC_VTOH32(cecservice_client.topology->device_attr[i]);
       }
       vcos_memcpy(topology, cecservice_client.topology, sizeof(VC_CEC_TOPOLOGY_T));
    }
    return success;
 }
Variable Documentation
cechost_log_category
VCOS_LOG_CAT_T cechost_log_category
Definition at line 194 of file vc_vchi_cecservice.c.