VideoCore Library: interface/vcos/vcos_msgqueue.h File Reference
vcos_msgqueue.h File Reference
#include "vcos_types.h"
#include "vcos.h"
#include "vcos_blockpool.h"
Classes
struct VCOS_MSG_WAITER_T
struct VCOS_MSGQUEUE_T
struct VCOS_MSG_T
struct VCOS_MSGQ_POOL_T
Macros
#define VCOS_MSGQ_MAGIC 0x5147534d
#define VCOS_MSG_DATA(_msg) (void*)((_msg)->data)
#define VCOS_MSG_N_QUIT 1
#define VCOS_MSG_N_OPEN 2
#define VCOS_MSG_N_CLOSE 3
#define VCOS_MSG_N_PRIVATE (1<<20)
#define VCOS_MSG_REPLY_BIT (1<<31)
#define __VCOS_MAY_ALIAS
#define MSG_REPLY_BIT (1<<31)
#define VCOS_MSG_INITIALIZER {VCOS_MSGQ_MAGIC, 0, NULL, NULL, NULL, 0}
Typedefs
typedef struct VCOS_MSG_WAITER_T VCOS_MSG_WAITER_T
typedef struct VCOS_MSGQUEUE_T VCOS_MSGQUEUE_T
typedef struct VCOS_MSG_T VCOS_MSG_T
typedef struct VCOS_MSGQ_POOL_T VCOS_MSGQ_POOL_T
Functions
VCOSPRE_ VCOS_STATUS_T VCOSPOST_ vcos_msgq_init (void)
VCOSPRE_ void VCOSPOST_ vcos_msgq_deinit (void)
VCOSPRE_ void VCOSPOST_ vcos_msg_send (VCOS_MSGQUEUE_T *dest, uint32_t code, VCOS_MSG_T *msg)
VCOSPRE_ VCOS_STATUS_T VCOSPOST_ vcos_msg_sendwait (VCOS_MSGQUEUE_T *queue, uint32_t code, VCOS_MSG_T *msg)
VCOSPRE_ VCOS_MSG_T *VCOSPOST_ vcos_msg_wait (VCOS_MSGQUEUE_T *queue)
VCOSPRE_ VCOS_MSG_T *VCOSPOST_ vcos_msg_peek (VCOS_MSGQUEUE_T *queue)
VCOSPRE_ void VCOSPOST_ vcos_msg_reply (VCOS_MSG_T *msg)
VCOSPRE_ void VCOSPOST_ vcos_msg_set_source (VCOS_MSG_T *msg, VCOS_MSGQUEUE_T *queue)
VCOSPRE_ void VCOSPOST_ vcos_msg_init (VCOS_MSG_T *msg)
VCOSPRE_ VCOS_STATUS_T VCOSPOST_ vcos_msgq_create (VCOS_MSGQUEUE_T *queue, const char *name)
VCOSPRE_ void VCOSPOST_ vcos_msgq_delete (VCOS_MSGQUEUE_T *queue)
VCOSPRE_ VCOS_STATUS_T VCOSPOST_ vcos_msgq_pool_create (VCOS_MSGQ_POOL_T *pool, size_t count, size_t payload_size, const char *name)
VCOSPRE_ void VCOSPOST_ vcos_msgq_pool_delete (VCOS_MSGQ_POOL_T *pool)
VCOSPRE_ VCOS_MSG_T *VCOSPOST_ vcos_msgq_pool_alloc (VCOS_MSGQ_POOL_T *pool)
VCOSPRE_ VCOS_MSG_T *VCOSPOST_ vcos_msgq_pool_wait (VCOS_MSGQ_POOL_T *pool)
VCOSPRE_ void VCOSPOST_ vcos_msgq_pool_free (VCOS_MSG_T *msg)
Detailed Description
Packet-like messages, based loosely on those found in TRIPOS and derivatives thereof.
A task can send a message pointer to another task, where it is queued on a linked list and the task woken up. The receiving task consumes all of the messages on its input queue, and optionally sends back replies using the original message memory.
A caller can wait for the reply to a specific message - any other messages that arrive in the meantime are queued separately.
All messages have a standard common layout, but the payload area can be used freely to extend this.
Definition in file vcos_msgqueue.h.
Macro Definition Documentation
__VCOS_MAY_ALIAS
#define __VCOS_MAY_ALIAS
Make gnuc compiler be happy about pointer punning
Definition at line 87 of file vcos_msgqueue.h.
MSG_REPLY_BIT
#define MSG_REPLY_BIT (1<<31)
Definition at line 127 of file vcos_msgqueue.h.
Referenced by vcos_msg_reply().
VCOS_MSG_DATA
#define VCOS_MSG_DATA (_msg) (void*)((_msg)->data)
Map the payload portion of a message to a structure pointer.
Definition at line 73 of file vcos_msgqueue.h.
VCOS_MSG_INITIALIZER
#define VCOS_MSG_INITIALIZER {VCOS_MSGQ_MAGIC, 0, NULL, NULL, NULL, 0}
Initialize a VCOS_MSG_T. Can also use vcos_msg_init().
Definition at line 131 of file vcos_msgqueue.h.
VCOS_MSG_N_CLOSE
#define VCOS_MSG_N_CLOSE 3
Definition at line 78 of file vcos_msgqueue.h.
VCOS_MSG_N_OPEN
#define VCOS_MSG_N_OPEN 2
Definition at line 77 of file vcos_msgqueue.h.
VCOS_MSG_N_PRIVATE
#define VCOS_MSG_N_PRIVATE (1<<20)
Definition at line 79 of file vcos_msgqueue.h.
VCOS_MSG_N_QUIT
#define VCOS_MSG_N_QUIT 1
Standard message ids - FIXME - these need to be done properly!
Definition at line 76 of file vcos_msgqueue.h.
VCOS_MSG_REPLY_BIT
#define VCOS_MSG_REPLY_BIT (1<<31)
Definition at line 81 of file vcos_msgqueue.h.
VCOS_MSGQ_MAGIC
#define VCOS_MSGQ_MAGIC 0x5147534d
Definition at line 69 of file vcos_msgqueue.h.
Typedef Documentation
VCOS_MSG_T
typedef struct VCOS_MSG_T VCOS_MSG_T
A single message
VCOS_MSG_WAITER_T
typedef struct VCOS_MSG_WAITER_T VCOS_MSG_WAITER_T
VCOS_MSGQ_POOL_T
typedef struct VCOS_MSGQ_POOL_T VCOS_MSGQ_POOL_T
A pool of messages. This contains its own waiter and semaphore, as well as a blockpool for the actual memory management.
When messages are returned to the waiter, it posts the semaphore.
When waiting for a message, we just wait on the semaphore. When allocating without waiting, we just try-wait on the semaphore.
If we managed to claim the semaphore, then by definition there must be at least that many free messages in the blockpool.
VCOS_MSGQUEUE_T
typedef struct VCOS_MSGQUEUE_T VCOS_MSGQUEUE_T
A single message queue.
Function Documentation
vcos_msg_init()
VCOSPRE_ void VCOSPOST_ vcos_msg_init (VCOS_MSG_T * msg)
Initialise a newly allocated message. This only needs to be called for messages allocated on the stack, heap or statically. It is not needed for messages allocated from a pool.
Definition at line 383 of file vcos_msgqueue.c.
References MAGIC, VCOS_MSG_T::magic, VCOS_MSG_T::next, NULL, VCOS_MSG_T::pool, and VCOS_MSG_T::waiter.
 {
    msg->magic = MAGIC;
    msg->next = NULL;
    msg->waiter = NULL;
    msg->pool = NULL;
 }
vcos_msg_peek()
VCOSPRE_ VCOS_MSG_T* VCOSPOST_ vcos_msg_peek (VCOS_MSGQUEUE_T * queue)
Peek for a message on this thread's endpoint. If a message is not available, NULL is returned. If a message is available it will be removed from the endpoint and returned.
Definition at line 205 of file vcos_msgqueue.c.
References VCOS_MSGQUEUE_T::head, VCOS_MSGQUEUE_T::lock, VCOS_MSG_T::next, NULL, VCOS_MSGQUEUE_T::sem, VCOS_MSGQUEUE_T::tail, vcos_mutex_lock(), vcos_mutex_unlock(), and vcos_semaphore_wait().
 {
    VCOS_MSG_T *msg;
    vcos_mutex_lock(&queue->lock);
    msg = queue->head;
    /* if there's a message, remove it from the queue */
    if (msg)
    {
       queue->head = msg->next;
       if (queue->head == NULL)
          queue->tail = NULL;
       /* keep the semaphore count consistent */
       /* coverity[lock_order]
        * the semaphore must have a non-zero count so cannot block here.
        */
       vcos_semaphore_wait(&queue->sem);
    }
    vcos_mutex_unlock(&queue->lock);
    return msg;
 }
vcos_msg_reply()
VCOSPRE_ void VCOSPOST_ vcos_msg_reply (VCOS_MSG_T * msg)
Send a reply to a message
Definition at line 263 of file vcos_msgqueue.c.
References VCOS_MSG_T::code, MAGIC, VCOS_MSG_T::magic, MSG_REPLY_BIT, VCOS_MSG_WAITER_T::on_reply, vcos_assert, VCOS_FUNCTION, and VCOS_MSG_T::waiter.
 {
    vcos_assert(msg->magic == MAGIC);
    msg->code |= MSG_REPLY_BIT;
    if (msg->waiter)
    {
       msg->waiter->on_reply(msg->waiter, msg);
    }
    else
    {
       VCOS_ALERT("%s: reply to non-reply message id %d",
                  VCOS_FUNCTION,
                  msg->code);
       vcos_assert(0);
    }
 }
vcos_msg_send()
VCOSPRE_ void VCOSPOST_ vcos_msg_send (VCOS_MSGQUEUE_T * dest, uint32_t code, VCOS_MSG_T * msg)
Send a message.
Parameters
dest Destination message queue
code Message code.
msg Pointer to message to send. Must not go out of scope before message is received (do not declare on the stack).
Definition at line 231 of file vcos_msgqueue.c.
References MAGIC, VCOS_MSG_T::magic, and vcos_assert.
 {
    vcos_assert(msg->magic == MAGIC);
    vcos_msg_send_helper(NULL, dest, code, msg);
 }
vcos_msg_sendwait()
VCOSPRE_ VCOS_STATUS_T VCOSPOST_ vcos_msg_sendwait (VCOS_MSGQUEUE_T * dest, uint32_t code, VCOS_MSG_T * msg)
Send a message and wait for a reply.
Parameters
dest Destination message queue
code Message code.
msg Pointer to message to send. May be declared on the stack.
Send on to the target queue, then wait on a simple waiter for the reply
Definition at line 239 of file vcos_msgqueue.c.
References MAGIC, VCOS_MSG_T::magic, NULL, vcos_assert, and VCOS_MSG_T::waiter.
 {
    VCOS_STATUS_T st;
    VCOS_MSG_SIMPLE_WAITER_T waiter;
    vcos_assert(msg->magic == MAGIC);
    /* if this fires, you've set a waiter up but are now about to obliterate it
     * with the 'wait for a reply' waiter.
     */
    vcos_assert(msg->waiter == NULL);
    if ((st=vcos_msgq_simple_waiter_init(&waiter)) != VCOS_SUCCESS)
       return st;
    vcos_msg_send_helper(&waiter.waiter, dest, code, msg);
    vcos_semaphore_wait(&waiter.waitsem);
    vcos_msgq_simple_waiter_deinit(&waiter);
    return VCOS_SUCCESS;
 }
vcos_msg_set_source()
VCOSPRE_ void VCOSPOST_ vcos_msg_set_source (VCOS_MSG_T * msg, VCOS_MSGQUEUE_T * queue)
Set the reply queue for a message. When the message is replied-to, it will return to the given queue.
Parameters
msg Message
queue Message queue the message should return to
Definition at line 280 of file vcos_msgqueue.c.
References MAGIC, VCOS_MSG_T::magic, vcos_assert, VCOS_MSGQUEUE_T::waiter, and VCOS_MSG_T::waiter.
 {
    vcos_assert(msg);
    vcos_assert(msg->magic == MAGIC);
    vcos_assert(queue);
    msg->waiter = &queue->waiter;
 }
vcos_msg_wait()
VCOSPRE_ VCOS_MSG_T* VCOSPOST_ vcos_msg_wait (VCOS_MSGQUEUE_T * queue)
Wait for a message on a queue.
Definition at line 187 of file vcos_msgqueue.c.
References VCOS_MSGQUEUE_T::head, VCOS_MSGQUEUE_T::lock, VCOS_MSG_T::next, NULL, VCOS_MSGQUEUE_T::sem, VCOS_MSGQUEUE_T::tail, vcos_assert, vcos_mutex_lock(), vcos_mutex_unlock(), and vcos_semaphore_wait().
 {
    VCOS_MSG_T *msg;
    vcos_semaphore_wait(&queue->sem);
    vcos_mutex_lock(&queue->lock);
    msg = queue->head;
    vcos_assert(msg);    /* should always be a message here! */
    queue->head = msg->next;
    if (queue->head == NULL)
       queue->tail = NULL;
    vcos_mutex_unlock(&queue->lock);
    return msg;
 }
vcos_msgq_create()
VCOSPRE_ VCOS_STATUS_T VCOSPOST_ vcos_msgq_create (VCOS_MSGQUEUE_T * queue, const char * name)
Create a message queue to wait on.
Definition at line 114 of file vcos_msgqueue.c.
 {
    VCOS_STATUS_T st;
    st = vcos_msgq_create_internal(q, name);
    return st;
 }
vcos_msgq_deinit()
VCOSPRE_ void VCOSPOST_ vcos_msgq_deinit (void)
De-initialise the library. Normally called from vcos_deinit().
Definition at line 163 of file vcos_msgqueue.c.
References _VCOS_INLINE.
 {
 }
vcos_msgq_delete()
VCOSPRE_ void VCOSPOST_ vcos_msgq_delete (VCOS_MSGQUEUE_T * queue)
Destroy a queue
Definition at line 123 of file vcos_msgqueue.c.
 {
    vcos_msgq_delete_internal(q);
 }
vcos_msgq_init()
VCOSPRE_ VCOS_STATUS_T VCOSPOST_ vcos_msgq_init (void)
Initialise the library. Normally called from vcos_init().
Definition at line 158 of file vcos_msgqueue.c.
References VCOS_SUCCESS.
 {
    return VCOS_SUCCESS;
 }
vcos_msgq_pool_alloc()
VCOSPRE_ VCOS_MSG_T* VCOSPOST_ vcos_msgq_pool_alloc (VCOS_MSGQ_POOL_T * pool)
Allocate a message from a message pool.
Note:
If the alloc fails (returns NULL) then your worker thread has stopped servicing requests or your pool is too small for the latency in the system. Your best bet to handle this is to fail the call that needs to send the message.
The returned message payload area is initialised to zero.
Parameters
pool Pool to allocate from.
Returns
Message or NULL if pool exhausted.
Definition at line 338 of file vcos_msgqueue.c.
References VCOS_MSGQ_POOL_T::blockpool, MAGIC, VCOS_MSG_T::magic, NULL, VCOS_MSG_T::pool, VCOS_MSGQ_POOL_T::sem, vcos_assert, vcos_blockpool_calloc(), vcos_semaphore_trywait(), VCOS_SUCCESS, VCOS_MSG_T::waiter, and VCOS_MSGQ_POOL_T::waiter.
 {
    VCOS_MSG_T *msg;
    if (vcos_semaphore_trywait(&pool->sem) == VCOS_SUCCESS)
    {
       msg = vcos_blockpool_calloc(&pool->blockpool);
       vcos_assert(msg);
       msg->magic = MAGIC;
       msg->waiter = &pool->waiter;
       msg->pool = pool;
    }
    else
    {
       msg = NULL;
    }
    return msg;
 }
vcos_msgq_pool_create()
VCOSPRE_ VCOS_STATUS_T VCOSPOST_ vcos_msgq_pool_create (VCOS_MSGQ_POOL_T * pool, size_t count, size_t payload_size, const char * name)
Create a pool of messages. Messages can be allocated from the pool and sent to a message queue. Replying to the message will automatically free it back to the pool.
The pool is threadsafe.
Parameters
count number of messages in the pool
payload_size maximum message payload size, not including MSG_T.
Definition at line 292 of file vcos_msgqueue.c.
References VCOS_MSGQ_POOL_T::blockpool, VCOS_MSG_WAITER_T::on_reply, VCOS_MSGQ_POOL_T::sem, status, VCOS_BLOCKPOOL_ALIGN_DEFAULT, vcos_blockpool_create_on_heap(), vcos_semaphore_create(), VCOS_SUCCESS, and VCOS_MSGQ_POOL_T::waiter.
 {
    VCOS_STATUS_T status;
    int bp_size = payload_size + sizeof(VCOS_MSG_T);
    status = vcos_blockpool_create_on_heap(&pool->blockpool,
                                           count, bp_size,
                                           VCOS_BLOCKPOOL_ALIGN_DEFAULT,
                                           0,
                                           name);
    if (status != VCOS_SUCCESS)
       goto fail_pool;
    status = vcos_semaphore_create(&pool->sem, name, count);
    if (status != VCOS_SUCCESS)
       goto fail_sem;
    pool->waiter.on_reply = vcos_msgq_pool_on_reply;
    pool->magic = MAGIC;
    return status;
 fail_sem:
    vcos_blockpool_delete(&pool->blockpool);
 fail_pool:
    return status;
 }
vcos_msgq_pool_delete()
VCOSPRE_ void VCOSPOST_ vcos_msgq_pool_delete (VCOS_MSGQ_POOL_T * pool)
Destroy a message pool.
Definition at line 321 of file vcos_msgqueue.c.
References VCOS_MSGQ_POOL_T::blockpool, VCOS_MSGQ_POOL_T::sem, vcos_blockpool_delete(), and vcos_semaphore_delete().
 {
    vcos_blockpool_delete(&pool->blockpool);
    vcos_semaphore_delete(&pool->sem);
 }
vcos_msgq_pool_free()
VCOSPRE_ void VCOSPOST_ vcos_msgq_pool_free (VCOS_MSG_T * msg)
Explicitly free a message and return it to its pool.
Parameters
msg Message to free. No-op if NULL.
Definition at line 356 of file vcos_msgqueue.c.
References MAGIC, VCOS_MSGQ_POOL_T::magic, VCOS_MSG_T::pool, VCOS_MSGQ_POOL_T::sem, vcos_assert, vcos_blockpool_free(), and vcos_semaphore_post().
 {
    if (msg)
    {
       VCOS_MSGQ_POOL_T *pool;
       vcos_assert(msg->pool);
       pool = msg->pool;
       vcos_assert(msg->pool->magic == MAGIC);
       vcos_blockpool_free(msg);
       vcos_semaphore_post(&pool->sem);
    }
 }
vcos_msgq_pool_wait()
VCOSPRE_ VCOS_MSG_T* VCOSPOST_ vcos_msgq_pool_wait (VCOS_MSGQ_POOL_T * pool)
Wait for a message from a message pool. Waits until a message is available in the pool and then allocates it. If one is already available, returns immediately.
This call can never fail.
The returned message payload area is initialised to zero.
Parameters
pool Pool to allocate from.
Returns
Message
Definition at line 371 of file vcos_msgqueue.c.
References VCOS_MSGQ_POOL_T::blockpool, MAGIC, VCOS_MSG_T::magic, VCOS_MSG_T::pool, VCOS_MSGQ_POOL_T::sem, vcos_assert, vcos_blockpool_calloc(), vcos_semaphore_wait(), VCOS_MSG_T::waiter, and VCOS_MSGQ_POOL_T::waiter.
 {
    VCOS_MSG_T *msg;
    vcos_semaphore_wait(&pool->sem);
    msg = vcos_blockpool_calloc(&pool->blockpool);
    vcos_assert(msg);
    msg->magic = MAGIC;
    msg->waiter = &pool->waiter;
    msg->pool = pool;
    return msg;
 }