VideoCore Library: interface/vcos/vcos_string.h File Reference
vcos_string.h File Reference
#include "interface/vcos/vcos_types.h"
#include "vcos.h"
#include <string.h>
Macros
#define VCOS_STRING_H
#define VCOS_SAFE_VSPRINTF(buf, offset, fmt, ap) vcos_safe_vsprintf(buf, sizeof(buf) + ((char (*)[sizeof(buf)])buf - &(buf)), offset, fmt, ap)
#define VCOS_SAFE_SPRINTF(buf, offset, ...) vcos_safe_sprintf(buf, sizeof(buf) + ((char (*)[sizeof(buf)])buf - &(buf)), offset, __VA_ARGS__)
#define VCOS_SAFE_STRCPY(dst, src, offset) vcos_safe_strcpy(dst, src, sizeof(dst) + ((char (*)[sizeof(dst)])dst - &(dst)), offset)
#define VCOS_SAFE_VSPRINTF(buf, offset, fmt, ap) vcos_safe_vsprintf(buf, sizeof(buf) + ((char (*)[sizeof(buf)])buf - &(buf)), offset, fmt, ap)
#define VCOS_SAFE_SPRINTF(buf, offset, ...) vcos_safe_sprintf(buf, sizeof(buf) + ((char (*)[sizeof(buf)])buf - &(buf)), offset, __VA_ARGS__)
#define VCOS_SAFE_STRCPY(dst, src, offset) vcos_safe_strcpy(dst, src, sizeof(dst) + ((char (*)[sizeof(dst)])dst - &(dst)), offset)
#define VCOS_STRING_H
#define VCOS_SAFE_VSPRINTF(buf, offset, fmt, ap) vcos_safe_vsprintf(buf, sizeof(buf) + ((char (*)[sizeof(buf)])buf - &(buf)), offset, fmt, ap)
#define VCOS_SAFE_SPRINTF(buf, offset, ...) vcos_safe_sprintf(buf, sizeof(buf) + ((char (*)[sizeof(buf)])buf - &(buf)), offset, __VA_ARGS__)
#define VCOS_SAFE_STRCPY(dst, src, offset) vcos_safe_strcpy(dst, src, sizeof(dst) + ((char (*)[sizeof(dst)])dst - &(dst)), offset)
Functions
VCOS_INLINE_DECL int vcos_strcasecmp (const char *s1, const char *s2)
VCOS_INLINE_DECL int vcos_strncasecmp (const char *s1, const char *s2, size_t n)
VCOSPRE_ int VCOSPOST_ vcos_vsnprintf (char *buf, size_t buflen, const char *fmt, va_list ap)
VCOSPRE_ int VCOSPOST_ vcos_snprintf (char *buf, size_t buflen, const char *fmt,...)
VCOSPRE_ size_t VCOSPOST_ vcos_safe_vsprintf (char *buf, size_t buflen, size_t offset, const char *fmt, va_list ap)
VCOSPRE_ size_t VCOSPOST_ vcos_safe_sprintf (char *buf, size_t buflen, size_t offset, const char *fmt,...)
VCOSPRE_ size_t VCOSPOST_ vcos_safe_strcpy (char *dst, const char *src, size_t dstlen, size_t offset)
VCOS_STATIC_INLINE int vcos_strlen (const char *s)
VCOS_STATIC_INLINE int vcos_strcmp (const char *s1, const char *s2)
VCOS_STATIC_INLINE int vcos_strncmp (const char *cs, const char *ct, size_t count)
VCOS_STATIC_INLINE char * vcos_strcpy (char *dst, const char *src)
VCOS_STATIC_INLINE char * vcos_strncpy (char *dst, const char *src, size_t count)
VCOS_STATIC_INLINE void * vcos_memcpy (void *dst, const void *src, size_t n)
VCOS_STATIC_INLINE void * vcos_memset (void *p, int c, size_t n)
VCOS_STATIC_INLINE int vcos_memcmp (const void *ptr1, const void *ptr2, size_t count)
Detailed Description
String functions.
Definition in file vcos_string.h.
Macro Definition Documentation
VCOS_SAFE_SPRINTF [1/3]
#define VCOS_SAFE_SPRINTF (buf, offset, ...) vcos_safe_sprintf(buf, sizeof(buf) + ((char (*)[sizeof(buf)])buf - &(buf)), offset, __VA_ARGS__)
VCOS_SAFE_SPRINTF [2/3]
#define VCOS_SAFE_SPRINTF (buf, offset, ...) vcos_safe_sprintf(buf, sizeof(buf) + ((char (*)[sizeof(buf)])buf - &(buf)), offset, __VA_ARGS__)
VCOS_SAFE_SPRINTF [3/3]
#define VCOS_SAFE_SPRINTF (buf, offset, ...) vcos_safe_sprintf(buf, sizeof(buf) + ((char (*)[sizeof(buf)])buf - &(buf)), offset, __VA_ARGS__)
Definition at line 88 of file khrn_misc.h.
VCOS_SAFE_STRCPY [1/3]
#define VCOS_SAFE_STRCPY (dst, src, offset) vcos_safe_strcpy(dst, src, sizeof(dst) + ((char (*)[sizeof(dst)])dst - &(dst)), offset)
VCOS_SAFE_STRCPY [2/3]
#define VCOS_SAFE_STRCPY (dst, src, offset) vcos_safe_strcpy(dst, src, sizeof(dst) + ((char (*)[sizeof(dst)])dst - &(dst)), offset)
VCOS_SAFE_STRCPY [3/3]
#define VCOS_SAFE_STRCPY (dst, src, offset) vcos_safe_strcpy(dst, src, sizeof(dst) + ((char (*)[sizeof(dst)])dst - &(dst)), offset)
Definition at line 99 of file khrn_misc.h.
VCOS_SAFE_VSPRINTF [1/3]
#define VCOS_SAFE_VSPRINTF (buf, offset, fmt, ap) vcos_safe_vsprintf(buf, sizeof(buf) + ((char (*)[sizeof(buf)])buf - &(buf)), offset, fmt, ap)
VCOS_SAFE_VSPRINTF [2/3]
#define VCOS_SAFE_VSPRINTF (buf, offset, fmt, ap) vcos_safe_vsprintf(buf, sizeof(buf) + ((char (*)[sizeof(buf)])buf - &(buf)), offset, fmt, ap)
VCOS_SAFE_VSPRINTF [3/3]
#define VCOS_SAFE_VSPRINTF (buf, offset, fmt, ap) vcos_safe_vsprintf(buf, sizeof(buf) + ((char (*)[sizeof(buf)])buf - &(buf)), offset, fmt, ap)
Definition at line 75 of file khrn_misc.h.
VCOS_STRING_H [1/2]
#define VCOS_STRING_H
VCOS_STRING_H [2/2]
#define VCOS_STRING_H
Function Documentation
vcos_memcmp()
VCOS_STATIC_INLINE int vcos_memcmp (const void * ptr1, const void * ptr2, size_t count)
Definition at line 124 of file vcos_string.h.
 { return memcmp(ptr1, ptr2, count); }
vcos_memcpy()
VCOS_STATIC_INLINE void* vcos_memcpy (void * dst, const void * src, size_t n)
Definition at line 118 of file vcos_string.h.
References VCOS_STATIC_INLINE.
Referenced by vc_cec_param2message(), vc_cec_send_message(), and vc_cec_send_SetOSDString().
 {  memcpy(dst, src, n);  return dst;  }
vcos_memset()
VCOS_STATIC_INLINE void* vcos_memset (void * p, int c, size_t n)
Definition at line 121 of file vcos_string.h.
References VCOS_STATIC_INLINE.
Referenced by vc_cec_param2message(), vc_cec_send_message(), vc_cec_send_SetOSDString(), and vc_vchi_cec_init().
 { return memset(p, c, n); }
vcos_safe_sprintf()
VCOSPRE_ size_t VCOSPOST_ vcos_safe_sprintf (char * buf, size_t buflen, size_t offset, const char * fmt, ...)
Like snprintf, except it places the output at the specified offset. Output is truncated to fit in buflen bytes, and is guaranteed to be NUL-terminated. Returns the string length before/without truncation.
Definition at line 56 of file vcos_generic_safe_string.c.
References NULL, offset, and vcos_vsnprintf().
 {
    size_t space = (offset < buflen) ? (buflen - offset) : 0;
    va_list ap;
    va_start(ap, fmt);
    offset += vcos_vsnprintf(buf ? (buf + offset) : NULL, space, fmt, ap);
    va_end(ap);
    return offset;
 }
vcos_safe_strcpy()
VCOSPRE_ size_t VCOSPOST_ vcos_safe_strcpy (char * dst, const char * src, size_t dstlen, size_t offset)
Copies string src to dst at the specified offset. Output is truncated to fit in dstlen bytes, i.e. the string is at most (buflen - 1) characters long. Unlike strncpy, exactly one NUL is written to dst, which is always NUL-terminated. Returns the string length before/without truncation.
Definition at line 76 of file vcos_generic_safe_string.c.
References offset.
Referenced by main(), mmal_vc_host_log(), mmal_vc_opaque_alloc_desc(), and vc_hostfs_readdir_r().
 {
    if (offset < dstlen)
    {
       const char *p = src;
       char *endp = dst + dstlen -1;
       dst += offset;
       for (; *p!='\0' && dst != endp; dst++, p++)
          *dst = *p;
       *dst = '\0';
    }
    offset += strlen(src);
    return offset;
 }
vcos_safe_vsprintf()
VCOSPRE_ size_t VCOSPOST_ vcos_safe_vsprintf (char * buf, size_t buflen, size_t offset, const char * fmt, va_list ap)
Like vsnprintf, except it places the output at the specified offset. Output is truncated to fit in buflen bytes, and is guaranteed to be NUL-terminated. Returns the string length before/without truncation.
Definition at line 43 of file vcos_generic_safe_string.c.
References NULL, offset, and vcos_vsnprintf().
 {
    size_t space = (offset < buflen) ? (buflen - offset) : 0;
    offset += vcos_vsnprintf(buf ? (buf + offset) : NULL, space, fmt, ap);
    return offset;
 }
vcos_snprintf()
VCOSPRE_ int VCOSPOST_ vcos_snprintf (char * buf, size_t buflen, const char * fmt, ...)
Definition at line 522 of file vcos_pthreads.c.
Referenced by mmal_connection_create(), and vcos_log_dump_mem_impl().
 {
    int ret;
    va_list ap;
    va_start(ap,fmt);
    ret = vsnprintf(buf, buflen, fmt, ap);
    va_end(ap);
    return ret;
 }
vcos_strcasecmp()
VCOS_INLINE_DECL int vcos_strcasecmp (const char * s1, const char * s2)
Case insensitive string comparison.
Referenced by mmal_graph_find_port(), mmal_parse_video_size(), and mmalomx_parameter_extension_index_get().
vcos_strcmp()
VCOS_STATIC_INLINE int vcos_strcmp (const char * s1, const char * s2)
Definition at line 106 of file vcos_string.h.
References VCOS_STATIC_INLINE.
 { return strcmp(s1,s2); }
vcos_strcpy()
VCOS_STATIC_INLINE char* vcos_strcpy (char * dst, const char * src)
Definition at line 112 of file vcos_string.h.
References VCOS_STATIC_INLINE.
 { return strcpy(dst, src); }
vcos_strlen()
VCOS_STATIC_INLINE int vcos_strlen (const char * s)
Definition at line 103 of file vcos_string.h.
References VCOS_STATIC_INLINE.
Referenced by vcos_generic_named_semaphore_create().
 { return (int)strlen(s); }
vcos_strncasecmp()
VCOS_INLINE_DECL int vcos_strncasecmp (const char * s1, const char * s2, size_t n)
Referenced by mmalomx_parameter_extension_index_get().
vcos_strncmp()
VCOS_STATIC_INLINE int vcos_strncmp (const char * cs, const char * ct, size_t count)
Definition at line 109 of file vcos_string.h.
References VCOS_STATIC_INLINE.
 { return strncmp(cs, ct, count); }
vcos_strncpy()
VCOS_STATIC_INLINE char* vcos_strncpy (char * dst, const char * src, size_t count)
Definition at line 115 of file vcos_string.h.
References VCOS_STATIC_INLINE.
 { return strncpy(dst, src, count); }
vcos_vsnprintf()
VCOSPRE_ int VCOSPOST_ vcos_vsnprintf (char * buf, size_t buflen, const char * fmt, va_list ap)
Definition at line 517 of file vcos_pthreads.c.
Referenced by vcos_cmd_vprintf(), vcos_safe_sprintf(), and vcos_safe_vsprintf().
 {
    return vsnprintf( buf, buflen, fmt, ap );
 }