VideoCore Library: TESTER_T Class Reference
TESTER_T Class Reference
Public Member Functions
TESTER_T (int argc, char **argv)
VC_CONTAINER_STATUS_T run ()
Detailed Description
Definition at line 564 of file autotest.cpp.
Constructor & Destructor Documentation
TESTER_T()
TESTER_T::TESTER_T (int argc, char ** argv) inline
Definition at line 568 of file autotest.cpp.
       : configuration(argc, argv)
       , video_stream(std::numeric_limits<STREAM_T>::max())
    {
       // If the configuration said keep going on errors tell the logger.
       if (configuration.errors_not_fatal)
       {
          error_logger.set_errors_not_fatal();
       }
       // Tell it where any -d routed the file summary
       error_logger.set_output(configuration.dump_packets);
    }
Member Function Documentation
run()
VC_CONTAINER_STATUS_T TESTER_T::run () inline
Seek to PTS 0 (this ought to be the beginning)
Definition at line 583 of file autotest.cpp.
References assert(), PACKET_DATA_T::buffer, VC_CONTAINER_PACKET_T::buffer_size, PACKET_DATA_T::crc, crc32buf(), VC_CONTAINER_PACKET_T::data, VC_CONTAINER_PACKET_T::dts, std::ends(), VC_CONTAINER_PACKET_T::flags, VC_CONTAINER_PACKET_T::frame_size, PACKET_DATA_T::info, max, min, VC_CONTAINER_PACKET_T::pts, VC_CONTAINER_PACKET_T::size, status, VC_CONTAINER_PACKET_T::track, VC_CONTAINER_CAPS_CAN_SEEK, VC_CONTAINER_CAPS_FORCE_TRACK, vc_container_close(), VC_CONTAINER_ERROR_EOS, VC_CONTAINER_ERROR_FAILED, VC_CONTAINER_ERROR_UNSUPPORTED_OPERATION, VC_CONTAINER_ES_TYPE_VIDEO, vc_container_log_set_verbosity(), vc_container_open_reader(), VC_CONTAINER_PACKET_FLAG_KEYFRAME, vc_container_read(), VC_CONTAINER_READ_FLAG_FORCE_TRACK, VC_CONTAINER_READ_FLAG_INFO, vc_container_seek(), VC_CONTAINER_SEEK_FLAG_FORWARD, VC_CONTAINER_SEEK_MODE_TIME, and VC_CONTAINER_SUCCESS.
Referenced by main().
    {
       /* Set the verbosity */
       vc_container_log_set_verbosity(0, configuration.verbosity_input);
       // Open the container
       p_ctx = vc_container_open_reader(configuration.source_name.c_str(), &status, 0, 0);
       if(!p_ctx || (status != VC_CONTAINER_SUCCESS))
       {
         error_logger << "error opening file " << configuration.source_name << " Code " << status << std::ends;
       }
       // Find the video stream.
       for(size_t i = 0; i < p_ctx->tracks_num; i++)
       {
          if (p_ctx->tracks[i]->format->es_type == VC_CONTAINER_ES_TYPE_VIDEO)
          {
             if (video_stream == std::numeric_limits<STREAM_T>::max())
             {
                video_stream = i;
             }
             else
             {
                // we've found two video streams. This is not necessarily an error, but it's certainly odd - perhaps it's the angles
                // from a DVD. We don't expect to see it, but report it anyway. Don't stop, just assume that the first one is the one we want.
                error_logger << "Both track " << video_stream << " and " << i << " are marked as video streams" << std::ends;
             }
          }
       }
       if (video_stream == std::numeric_limits<STREAM_T>::max())
       {
          error_logger << "No video track found" << std::ends;
       }
       // Read all the packets sequentially. This will gve us all the metadata of the packets,
       // and (up to configuration.mem_max) will also store the packet data.
       read_sequential();
       // Now we have some packets we can initialise our internal RNG.
       init_crg();
       // Find all the keyframes in the collection we just read.
       find_key_packets();
       // Seeking tests. Only if the container supports it.
       // We do this first, because one of the checks is whether or not the container supports seeking,
       // and we want to be able to seek back between tests.
       if (p_ctx->capabilities & VC_CONTAINER_CAPS_CAN_SEEK)
       {
          PTS_T beginning = 0;
          status = vc_container_seek(p_ctx, &beginning, VC_CONTAINER_SEEK_MODE_TIME, 0);
          if (status != VC_CONTAINER_SUCCESS)
          {
             error_logger << "Container failed to seek to the beginning - status " << status << std::ends;
             // This is fatal.
             exit(status);
          }
          // Ask for info about the first packet
          PACKET_DATA_T actual;
          status = vc_container_read(p_ctx, &actual.info, VC_CONTAINER_READ_FLAG_INFO);
          if (status != VC_CONTAINER_SUCCESS)
          {
             error_logger << "Read info failed after seek to the beginning - status " << status << std::ends;
          }
          else
          {
             PACKET_DATA_T& expected = all_packets.front();
             // Compare some selected data to check that this genuinely is the first packet.
             // We don't actually do a read.
             if ((expected.info.pts != actual.info.pts)
                || (expected.info.dts != actual.info.dts)
                || (expected.info.size != actual.info.size)
                || (expected.info.frame_size != actual.info.frame_size)
                || (expected.info.track != actual.info.track)
                || (expected.info.flags != actual.info.flags))
             {
                // Copy the CRC from the expected value. That will stop compare_packets whinging.
                actual.crc = expected.crc;
                // report the discrepancy
                error_logger << "Seek to time zero did not arrive at beginning: "
                   << compare_packets(expected, actual) << std::ends;
             }
          }
          // Perform seeks to find all the packets that a seek will go to.
          check_indices(0);
          check_indices(VC_CONTAINER_SEEK_FLAG_FORWARD);
          // If it supports forcing then seek to each of those locations, and force read all the tracks.
          if (p_ctx->capabilities & VC_CONTAINER_CAPS_FORCE_TRACK)
          {
             check_seek_then_force(0);
             check_seek_then_force(VC_CONTAINER_SEEK_FLAG_FORWARD);
          }
          seek_randomly(0);
          seek_randomly(VC_CONTAINER_SEEK_FLAG_FORWARD);
          // todo more?
       }
       else
       {
          // The file claims not to support seeking. Perform a seek, just to check this out.
          PTS_T beginning = 0;
          status = vc_container_seek(p_ctx, &beginning, VC_CONTAINER_SEEK_MODE_TIME, 0);
          if (status != VC_CONTAINER_ERROR_UNSUPPORTED_OPERATION)
          {
             error_logger << "Container did not reject seek when its capabilities said it is not supported" << std::ends;
          }
       }
       // If the config didn't ask for this test don't do it.
       if (configuration.packet_buffer_size > 0)
       {
          re_seek_to_beginning();
          // Read through the file, reading the packet in several bites (bite size controlled by -p parameter)
          check_partial_reads();
          // Check forcing (this doesn't require seek)
          if (p_ctx->capabilities & VC_CONTAINER_CAPS_FORCE_TRACK)
          {
             re_seek_to_beginning();
             check_forcing();
          }
       }
       std::cout << "Test Complete" << std::endl;
       // If anything failed then the error logger will replace this error code. So always return 0 from here.
       return VC_CONTAINER_SUCCESS;
    }
The documentation for this class was generated from the following file:
containers/test/autotest.cpp