VideoCore Library: interface/vcos/generic/vcos_init.c File Reference
vcos_init.c File Reference
#include "vcos_deprecated.h"
#include "interface/vcos/vcos.h"
Functions
VCOS_STATUS_T vcos_init (void)
void vcos_deinit (void)
Function Documentation
vcos_deinit()
void vcos_deinit (void)
vcos deinitialization. Call this function when vcos is no longer required, in order to free resources. Calls can be nested within the same process; they are reference counted so that only a call that decrements the reference count to 0 has any effect.
Note
On platforms/toolchains that support it, gcc's destructor attribute or similar is used to invoke this function after exit() or equivalent.
Returns
Status of initialisation.
Definition at line 56 of file vcos_init.c.
References vcos_assert, and vcos_global_lock().
 {
    vcos_global_lock();
    vcos_assert(init_refcount > 0);
    if (init_refcount > 0 && --init_refcount == 0)
       vcos_platform_deinit();
    vcos_global_unlock();
 }
vcos_init()
VCOS_STATUS_T vcos_init (void)
vcos initialization. Call this function before using other vcos functions. Calls can be nested within the same process; they are reference counted so that only a call from uninitialized state has any effect.
Note
On platforms/toolchains that support it, gcc's constructor attribute or similar is used to invoke this function before main() or equivalent.
Returns
Status of initialisation.
Definition at line 42 of file vcos_init.c.
References vcos_global_lock(), and VCOS_SUCCESS.
Referenced by bcm_host_init(), main(), and raspitex_init().
 {
    VCOS_STATUS_T st = VCOS_SUCCESS;
    vcos_global_lock();
    if (init_refcount++ == 0)
       st = vcos_platform_init();
    vcos_global_unlock();
    return st;
 }