VideoCore Library: host_applications/linux/apps/hello_pi/hello_teapot/triangle.c File Reference
triangle.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <assert.h>
#include <unistd.h>
#include "bcm_host.h"
#include "GLES/gl.h"
#include "EGL/egl.h"
#include "EGL/eglext.h"
#include "cube_texture_and_coords.h"
#include "models.h"
#include "triangle.h"
#include <pthread.h>
#include <signal.h>
#include "revision.h"
Classes
struct CUBE_STATE_T
Macros
#define PATH "./"
#define IMAGE_SIZE_WIDTH 1920
#define IMAGE_SIZE_HEIGHT 1080
#define M_PI 3.141592654
Functions
void sig_handler (int signo)
int main ()
Variables
int thread_run
Macro Definition Documentation
IMAGE_SIZE_HEIGHT
#define IMAGE_SIZE_HEIGHT 1080
Definition at line 56 of file triangle.c.
IMAGE_SIZE_WIDTH
#define IMAGE_SIZE_WIDTH 1920
Definition at line 55 of file triangle.c.
M_PI
#define M_PI 3.141592654
Definition at line 59 of file triangle.c.
PATH
#define PATH "./"
Definition at line 53 of file triangle.c.
Function Documentation
main()
int main (void)
Definition at line 455 of file triangle.c.
References bcm_host_init(), get_processor_id(), PROCESSOR_BCM2838, and sig_handler().
 {
    bcm_host_init();
    if (get_processor_id() == PROCESSOR_BCM2838)
    {
       puts("This demo application is not available on the Pi4\n\n");
       exit(0);
    }
    printf("Note: ensure you have sufficient gpu_mem configured\n");
    signal(SIGINT, sig_handler);
    // Clear application state
    memset( state, 0, sizeof( *state ) );
    // Start OGLES
    init_ogl(state);
    // Setup the model world
    init_model_proj(state);
    // initialise the OGLES texture(s)
    init_textures(state);
    //state->model = cube_wavefront();
    state->model = load_wavefront("/opt/vc/src/hello_pi/hello_teapot/teapot.obj.dat", NULL);
    while (!terminate)
    {
       update_model(state);
       redraw_scene(state);
    }
    exit_func();
    return 0;
 }
sig_handler()
void sig_handler (int signo)
Definition at line 447 of file triangle.c.
Referenced by main().
{
    terminate = 1;
 }
Variable Documentation
thread_run
int thread_run
Definition at line 43 of file video.c.