VideoCore Library: interface/vcos/vcos_mutex.h File Reference
vcos_mutex.h File Reference
#include "interface/vcos/vcos_types.h"
#include "vcos.h"
Macros
#define VCOS_MUTEX_H
#define VCOS_MUTEX_H
Functions
VCOS_INLINE_DECL VCOS_STATUS_T vcos_mutex_create (VCOS_MUTEX_T *m, const char *name)
VCOS_INLINE_DECL void vcos_mutex_delete (VCOS_MUTEX_T *m)
VCOS_INLINE_DECL VCOS_STATUS_T vcos_mutex_lock (VCOS_MUTEX_T *m)
Wait to claim the mutex.
VCOS_INLINE_DECL void vcos_mutex_unlock (VCOS_MUTEX_T *m)
VCOS_INLINE_DECL int vcos_mutex_is_locked (VCOS_MUTEX_T *m)
VCOS_INLINE_DECL VCOS_STATUS_T vcos_mutex_trylock (VCOS_MUTEX_T *m)
Detailed Description
Mutex API. Mutexes are not re-entrant, as supporting this adds extra code that slows down clients which have been written sensibly.
See also
vcos_reentrant_mutex.h
Definition in file vcos_mutex.h.
Macro Definition Documentation
VCOS_MUTEX_H [1/2]
#define VCOS_MUTEX_H
VCOS_MUTEX_H [2/2]
#define VCOS_MUTEX_H
Function Documentation
vcos_mutex_create()
VCOS_INLINE_DECL VCOS_STATUS_T vcos_mutex_create (VCOS_MUTEX_T * m, const char * name)
Create a mutex.
Parameters
m Filled in with mutex on return
name A non-null name for the mutex, used for diagnostics.
Returns
VCOS_SUCCESS if mutex was created, or error code.
Referenced by _vcos_named_semaphore_init(), gx_priv_init(), mmal_clock_create(), mmal_component_action_register(), mmal_list_create(), mmal_queue_create(), svp_create(), vc_vchi_cec_init(), vc_vchi_dispmanx_init(), vc_vchi_filesys_init(), vc_vchi_gencmd_init(), vc_vchi_tv_init(), vcos_generic_blockpool_init(), vcos_generic_event_flags_create(), and vcos_platform_init().
vcos_mutex_delete()
VCOS_INLINE_DECL void vcos_mutex_delete (VCOS_MUTEX_T * m)
Delete the mutex.
Referenced by _vcos_named_semaphore_deinit(), gx_priv_destroy(), mmal_component_action_deregister(), mmal_list_destroy(), mmal_port_free(), mmal_queue_create(), mmal_queue_destroy(), mmal_vc_deinit(), OMX_FreeHandle(), svp_destroy(), vcos_cmd_shutdown(), vcos_generic_blockpool_delete(), and vcos_generic_event_flags_delete().
vcos_mutex_is_locked()
VCOS_INLINE_DECL int vcos_mutex_is_locked (VCOS_MUTEX_T * m)
Test if the mutex is already locked.
Returns
1 if mutex is locked, 0 if it is unlocked.
vcos_mutex_lock()
VCOS_INLINE_DECL VCOS_STATUS_T vcos_mutex_lock (VCOS_MUTEX_T * m)
Wait to claim the mutex.
On most platforms this always returns VCOS_SUCCESS, and so would ideally be a void function, however some platforms allow a wait to be interrupted so it remains non-void.
Try to obtain the mutex.
Parameters
m Mutex to wait on
Returns
VCOS_SUCCESS - mutex was taken. VCOS_EAGAIN - could not take mutex.
Referenced by mmal_component_acquire(), mmal_component_action_lock(), mmal_component_disable(), mmal_component_enable(), mmal_list_create(), mmal_port_acquire(), mmal_port_release(), mmal_queue_create(), mmal_queue_put(), mmal_queue_put_back(), mmal_vc_allocate_client_component(), mmal_vc_deinit(), mmal_vc_release_client_component(), mmal_vc_send_message(), mmal_vc_sendwait_message(), OMX_FreeHandle(), OMX_GetHandle(), svp_get_stats(), vc_gpuserv_deinit(), vcos_generic_blockpool_alloc(), vcos_generic_blockpool_available_count(), vcos_generic_blockpool_elem_from_handle(), vcos_generic_blockpool_elem_to_handle(), vcos_generic_blockpool_free(), vcos_generic_blockpool_is_valid_elem(), vcos_generic_blockpool_used_count(), vcos_generic_event_flags_get(), vcos_generic_event_flags_set(), vcos_generic_named_semaphore_create(), vcos_log_unregister(), vcos_msg_peek(), vcos_msg_wait(), vcos_named_semaphore_delete(), vcos_vlog_default_impl(), vcsm_exit(), wfc_client_ipc_release_keep_alive(), and wfc_client_ipc_use_keep_alive().
vcos_mutex_trylock()
VCOS_INLINE_DECL VCOS_STATUS_T vcos_mutex_trylock (VCOS_MUTEX_T * m)
Obtain the mutex if possible.
Parameters
m the mutex to try to obtain
Returns
VCOS_SUCCESS if mutex is successfully obtained, or VCOS_EAGAIN if it is already in use by another thread.
vcos_mutex_unlock()
VCOS_INLINE_DECL void vcos_mutex_unlock (VCOS_MUTEX_T * m)
Release the mutex.
Referenced by mmal_component_acquire(), mmal_component_action_unlock(), mmal_component_disable(), mmal_component_enable(), mmal_list_create(), mmal_port_acquire(), mmal_port_release(), mmal_queue_create(), mmal_queue_put(), mmal_queue_put_back(), mmal_vc_allocate_client_component(), mmal_vc_deinit(), mmal_vc_release_client_component(), mmal_vc_send_message(), svp_get_stats(), vc_gpuserv_deinit(), vcos_generic_blockpool_available_count(), vcos_generic_blockpool_elem_from_handle(), vcos_generic_blockpool_elem_to_handle(), vcos_generic_blockpool_free(), vcos_generic_blockpool_is_valid_elem(), vcos_generic_blockpool_used_count(), vcos_log_unregister(), vcos_msg_peek(), vcos_msg_wait(), and vcos_vlog_default_impl().