VideoCore Library: containers/core/containers_io.c File Reference
containers_io.c File Reference
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include "containers/containers.h"
#include "containers/core/containers_io.h"
#include "containers/core/containers_common.h"
#include "containers/core/containers_utils.h"
#include "containers/core/containers_uri.h"
Classes
struct VC_CONTAINER_IO_PRIVATE_CACHE_T
struct VC_CONTAINER_IO_PRIVATE_T
Macros
#define MAX_NUM_CACHED_AREAS 16
#define MAX_NUM_MEMORY_AREAS 4
#define NUM_TMP_MEMORY_AREAS 2
#define MEM_CACHE_READ_MAX_SIZE (32*1024) /* Needs to be a power of 2 */
#define MEM_CACHE_WRITE_MAX_SIZE (128*1024) /* Needs to be a power of 2 */
#define MEM_CACHE_TMP_MAX_SIZE (32*1024) /* Needs to be a power of 2 */
#define MEM_CACHE_ALIGNMENT (1*1024) /* Needs to be a power of 2 */
#define MEM_CACHE_AREA_READ_MAX_SIZE (4*1024*1024) /* Needs to be a power of 2 */
Typedefs
typedef struct VC_CONTAINER_IO_PRIVATE_CACHE_T VC_CONTAINER_IO_PRIVATE_CACHE_T
typedef struct VC_CONTAINER_IO_PRIVATE_T VC_CONTAINER_IO_PRIVATE_T
Functions
VC_CONTAINER_STATUS_T vc_container_io_file_open (VC_CONTAINER_IO_T *p_ctx, const char *uri, VC_CONTAINER_IO_MODE_T mode)
VC_CONTAINER_STATUS_T vc_container_io_null_open (VC_CONTAINER_IO_T *p_ctx, const char *uri, VC_CONTAINER_IO_MODE_T mode)
VC_CONTAINER_STATUS_T vc_container_io_net_open (VC_CONTAINER_IO_T *p_ctx, const char *uri, VC_CONTAINER_IO_MODE_T mode)
VC_CONTAINER_STATUS_T vc_container_io_pktfile_open (VC_CONTAINER_IO_T *p_ctx, const char *uri, VC_CONTAINER_IO_MODE_T mode)
VC_CONTAINER_STATUS_T vc_container_io_http_open (VC_CONTAINER_IO_T *p_ctx, const char *uri, VC_CONTAINER_IO_MODE_T mode)
VC_CONTAINER_IO_T * vc_container_io_open (const char *uri, VC_CONTAINER_IO_MODE_T mode, VC_CONTAINER_STATUS_T *p_status)
VC_CONTAINER_IO_T * vc_container_io_create (const char *uri, VC_CONTAINER_IO_MODE_T mode, VC_CONTAINER_IO_CAPABILITIES_T capabilities, VC_CONTAINER_STATUS_T *p_status)
VC_CONTAINER_STATUS_T vc_container_io_close (VC_CONTAINER_IO_T *p_ctx)
size_t vc_container_io_peek (VC_CONTAINER_IO_T *p_ctx, void *buffer, size_t size)
size_t vc_container_io_read (VC_CONTAINER_IO_T *p_ctx, void *buffer, size_t size)
size_t vc_container_io_write (VC_CONTAINER_IO_T *p_ctx, const void *buffer, size_t size)
size_t vc_container_io_skip (VC_CONTAINER_IO_T *p_ctx, size_t size)
VC_CONTAINER_STATUS_T vc_container_io_seek (VC_CONTAINER_IO_T *p_ctx, int64_t offset)
VC_CONTAINER_STATUS_T vc_container_io_control_list (VC_CONTAINER_IO_T *context, VC_CONTAINER_CONTROL_T operation, va_list args)
VC_CONTAINER_STATUS_T vc_container_io_control (VC_CONTAINER_IO_T *context, VC_CONTAINER_CONTROL_T operation,...)
size_t vc_container_io_cache (VC_CONTAINER_IO_T *p_ctx, size_t size)
Macro Definition Documentation
MAX_NUM_CACHED_AREAS
#define MAX_NUM_CACHED_AREAS 16
Definition at line 38 of file containers_io.c.
Referenced by vc_container_io_cache().
MAX_NUM_MEMORY_AREAS
#define MAX_NUM_MEMORY_AREAS 4
Definition at line 39 of file containers_io.c.
MEM_CACHE_ALIGNMENT
#define MEM_CACHE_ALIGNMENT (1*1024) /* Needs to be a power of 2 */
Definition at line 44 of file containers_io.c.
MEM_CACHE_AREA_READ_MAX_SIZE
#define MEM_CACHE_AREA_READ_MAX_SIZE (4*1024*1024) /* Needs to be a power of 2 */
Definition at line 45 of file containers_io.c.
Referenced by vc_container_io_cache().
MEM_CACHE_READ_MAX_SIZE
#define MEM_CACHE_READ_MAX_SIZE (32*1024) /* Needs to be a power of 2 */
Definition at line 41 of file containers_io.c.
Referenced by vc_container_io_cache().
MEM_CACHE_TMP_MAX_SIZE
#define MEM_CACHE_TMP_MAX_SIZE (32*1024) /* Needs to be a power of 2 */
Definition at line 43 of file containers_io.c.
MEM_CACHE_WRITE_MAX_SIZE
#define MEM_CACHE_WRITE_MAX_SIZE (128*1024) /* Needs to be a power of 2 */
Definition at line 42 of file containers_io.c.
NUM_TMP_MEMORY_AREAS
#define NUM_TMP_MEMORY_AREAS 2
Definition at line 40 of file containers_io.c.
Typedef Documentation
VC_CONTAINER_IO_PRIVATE_CACHE_T
typedef struct VC_CONTAINER_IO_PRIVATE_CACHE_T VC_CONTAINER_IO_PRIVATE_CACHE_T
VC_CONTAINER_IO_PRIVATE_T
typedef struct VC_CONTAINER_IO_PRIVATE_T VC_CONTAINER_IO_PRIVATE_T
Function Documentation
vc_container_io_file_open()
VC_CONTAINER_STATUS_T vc_container_io_file_open (VC_CONTAINER_IO_T * p_ctx, const char * uri, VC_CONTAINER_IO_MODE_T mode)
Definition at line 106 of file io_file.c.
References error(), VC_CONTAINER_IO_T::module, NULL, VC_CONTAINER_IO_MODULE_T::stream, VC_CONTAINER_IO_T::uri, VC_CONTAINER_IO_T::uri_parts, VC_CONTAINER_ERROR_OUT_OF_MEMORY, VC_CONTAINER_ERROR_URI_NOT_FOUND, VC_CONTAINER_IO_MODE_WRITE, VC_CONTAINER_PARAM_UNUSED, VC_CONTAINER_SUCCESS, and vc_uri_path().
 {
    VC_CONTAINER_STATUS_T status = VC_CONTAINER_SUCCESS;
    VC_CONTAINER_IO_MODULE_T *module = 0;
    const char *psz_mode = mode == VC_CONTAINER_IO_MODE_WRITE ? "wb+" : "rb";
    const char *uri = p_ctx->uri;
    FILE *stream = 0;
    VC_CONTAINER_PARAM_UNUSED(unused);
    if(vc_uri_path(p_ctx->uri_parts))
       uri = vc_uri_path(p_ctx->uri_parts);
    stream = fopen(uri, psz_mode);
    if(!stream) { status = VC_CONTAINER_ERROR_URI_NOT_FOUND; goto error; }
    /* Turn off buffering. The container layer will provide its own cache */
    setvbuf(stream, NULL, _IONBF, 0);
    module = malloc( sizeof(*module) );
    if(!module) { status = VC_CONTAINER_ERROR_OUT_OF_MEMORY; goto error; }
    memset(module, 0, sizeof(*module));
    p_ctx->module = module;
    module->stream = stream;
    p_ctx->pf_close = io_file_close;
    p_ctx->pf_read = io_file_read;
    p_ctx->pf_write = io_file_write;
    p_ctx->pf_seek = io_file_seek;
    if(mode == VC_CONTAINER_IO_MODE_WRITE)
    {
       p_ctx->max_size = (1UL<<31)-1; /* For now limit to 2GB */
    }
    else
    {
       //FIXME: large file support, platform-specific file size
       fseek(p_ctx->module->stream, 0, SEEK_END);
       p_ctx->size = ftell(p_ctx->module->stream);
       fseek(p_ctx->module->stream, 0, SEEK_SET);
    }
    p_ctx->capabilities = VC_CONTAINER_IO_CAPS_NO_CACHING;
    return VC_CONTAINER_SUCCESS;
  error:
    if(stream) fclose(stream);
    return status;
 }
vc_container_io_http_open()
VC_CONTAINER_STATUS_T vc_container_io_http_open (VC_CONTAINER_IO_T * p_ctx, const char * uri, VC_CONTAINER_IO_MODE_T mode)
Definition at line 820 of file io_http.c.
References error(), VC_CONTAINER_IO_MODULE_T::header_list, HEADER_LIST_INITIAL_CAPACITY, HTTP_URI_LENGTH_MAX, VC_CONTAINER_IO_T::module, VC_CONTAINER_IO_T::uri, VC_CONTAINER_IO_T::uri_parts, VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED, VC_CONTAINER_ERROR_OUT_OF_MEMORY, VC_CONTAINER_ERROR_UNSUPPORTED_OPERATION, VC_CONTAINER_ERROR_URI_OPEN_FAILED, VC_CONTAINER_IO_MODE_WRITE, VC_CONTAINER_PARAM_UNUSED, VC_CONTAINER_SUCCESS, vc_containers_list_create(), and vc_uri_scheme().
 {
    VC_CONTAINER_STATUS_T status = VC_CONTAINER_SUCCESS;
    VC_CONTAINER_IO_MODULE_T *module = 0;
    VC_CONTAINER_PARAM_UNUSED(unused);
    /* Check the URI to see if we're dealing with an http stream */
    if (!vc_uri_scheme(p_ctx->uri_parts) ||
        strcasecmp(vc_uri_scheme(p_ctx->uri_parts), "http"))
       return VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED;
    /*
     * Some basic error checking.
     */
    if (mode == VC_CONTAINER_IO_MODE_WRITE)
    {
       status = VC_CONTAINER_ERROR_UNSUPPORTED_OPERATION;
       goto error;
    }
    if (strlen(p_ctx->uri) > HTTP_URI_LENGTH_MAX)
    {
       status = VC_CONTAINER_ERROR_URI_OPEN_FAILED;
       goto error;
    }
    module = calloc(1, sizeof(*module));
    if (!module)
    {
       status = VC_CONTAINER_ERROR_OUT_OF_MEMORY;
       goto error;
    }
    p_ctx->module = module;
    /* header_list will contain pointers into the response_buffer, so take care in re-use */
    module->header_list = vc_containers_list_create(HEADER_LIST_INITIAL_CAPACITY, sizeof(HTTP_HEADER_T),
                                            (VC_CONTAINERS_LIST_COMPARATOR_T)io_http_header_comparator);
    if (!module->header_list)
    {
       status = VC_CONTAINER_ERROR_OUT_OF_MEMORY;
       goto error;
    }
    /*
     * Make sure that we have a port number.
     */
    if (vc_uri_port(p_ctx->uri_parts) == NULL)
       vc_uri_set_port(p_ctx->uri_parts, IO_HTTP_DEFAULT_PORT);
    status = io_http_open_socket(p_ctx);
    if (status != VC_CONTAINER_SUCCESS)
       goto error;
    /*
     * Whoo hoo! Our socket is open. Now let's send a HEAD request.
     */
    status = io_http_head(p_ctx);
    if (status != VC_CONTAINER_SUCCESS)
       goto error;
    p_ctx->pf_close   = io_http_close;
    p_ctx->pf_read    = io_http_read;
    p_ctx->pf_write   = NULL;
    p_ctx->pf_control = io_http_control;
    p_ctx->pf_seek    = io_http_seek;
    p_ctx->capabilities = VC_CONTAINER_IO_CAPS_NO_CACHING;
    p_ctx->capabilities |= VC_CONTAINER_IO_CAPS_SEEK_SLOW;
    return VC_CONTAINER_SUCCESS;
 error:
    io_http_close(p_ctx);
    return status;
 }
vc_container_io_net_open()
VC_CONTAINER_STATUS_T vc_container_io_net_open (VC_CONTAINER_IO_T * p_ctx, const char * uri, VC_CONTAINER_IO_MODE_T mode)
Definition at line 346 of file io_net.c.
References is_udp, status, VC_CONTAINER_PARAM_UNUSED, and VC_CONTAINER_SUCCESS.
 {
    VC_CONTAINER_STATUS_T status = VC_CONTAINER_SUCCESS;
    VC_CONTAINER_IO_MODULE_T *module = 0;
    bool is_udp;
    VC_CONTAINER_PARAM_UNUSED(unused);
    if (!io_net_recognise_scheme(p_ctx->uri, &is_udp))
    { status = VC_CONTAINER_ERROR_URI_NOT_FOUND; goto error; }
    module = (VC_CONTAINER_IO_MODULE_T *)malloc( sizeof(*module) );
    if (!module) { status = VC_CONTAINER_ERROR_OUT_OF_MEMORY; goto error; }
    memset(module, 0, sizeof(*module));
    p_ctx->module = module;
    status = io_net_open_socket(p_ctx, mode, is_udp);
    if (status != VC_CONTAINER_SUCCESS)
       goto error;
    p_ctx->pf_close = io_net_close;
    p_ctx->pf_read = io_net_read;
    p_ctx->pf_write = io_net_write;
    p_ctx->pf_control = io_net_control;
    /* Disable caching, as this will block waiting for enough data to fill the cache or an error */
    p_ctx->capabilities = VC_CONTAINER_IO_CAPS_CANT_SEEK;
    return VC_CONTAINER_SUCCESS;
 error:
    io_net_close(p_ctx);
    return status;
 }
vc_container_io_null_open()
VC_CONTAINER_STATUS_T vc_container_io_null_open (VC_CONTAINER_IO_T * p_ctx, const char * uri, VC_CONTAINER_IO_MODE_T mode)
Definition at line 74 of file io_null.c.
References VC_CONTAINER_IO_T::uri_parts, VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED, VC_CONTAINER_PARAM_UNUSED, and vc_uri_scheme().
 {
    VC_CONTAINER_PARAM_UNUSED(unused);
    VC_CONTAINER_PARAM_UNUSED(mode);
    /* Check the URI */
    if (!vc_uri_scheme(p_ctx->uri_parts) ||
        (strcasecmp(vc_uri_scheme(p_ctx->uri_parts), "null") &&
         strcasecmp(vc_uri_scheme(p_ctx->uri_parts), "null")))
       return VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED;
    p_ctx->pf_close = io_null_close;
    p_ctx->pf_read = io_null_read;
    p_ctx->pf_write = io_null_write;
    p_ctx->pf_seek = io_null_seek;
    return VC_CONTAINER_SUCCESS;
 }
vc_container_io_pktfile_open()
VC_CONTAINER_STATUS_T vc_container_io_pktfile_open (VC_CONTAINER_IO_T * p_ctx, const char * uri, VC_CONTAINER_IO_MODE_T mode)
Definition at line 225 of file io_pktfile.c.
References VC_CONTAINER_IO_MODULE_T::is_native_order, status, VC_CONTAINER_IO_MODULE_T::stream, VC_CONTAINER_PARAM_UNUSED, and VC_CONTAINER_SUCCESS.
 {
    VC_CONTAINER_STATUS_T status = VC_CONTAINER_SUCCESS;
    VC_CONTAINER_IO_MODULE_T *module = 0;
    FILE *stream = 0;
    bool is_native_order = true;
    VC_CONTAINER_PARAM_UNUSED(unused);
    stream = open_file(p_ctx, mode, &status);
    if (status != VC_CONTAINER_SUCCESS) goto error;
    if (mode == VC_CONTAINER_IO_MODE_WRITE)
       status = write_byte_order(stream);
    else
       status = read_byte_order(stream, &is_native_order);
    if (status != VC_CONTAINER_SUCCESS) goto error;
    module = malloc( sizeof(*module) );
    if(!module) { status = VC_CONTAINER_ERROR_OUT_OF_MEMORY; goto error; }
    memset(module, 0, sizeof(*module));
    p_ctx->module = module;
    module->stream = stream;
    module->is_native_order = is_native_order;
    p_ctx->pf_close = io_pktfile_close;
    p_ctx->pf_read = io_pktfile_read;
    p_ctx->pf_write = io_pktfile_write;
    /* Do not allow caching by I/O core, as this will merge packets in the cache. */
    p_ctx->capabilities = VC_CONTAINER_IO_CAPS_CANT_SEEK;
    return VC_CONTAINER_SUCCESS;
 error:
    if(stream) fclose(stream);
    return status;
 }