VideoCore Library: middleware/dlloader/dlfcn.h File Reference
dlfcn.h File Reference
Classes
struct dlsegmentsizedata
Macros
#define RTLD_LAZY 0x00001 /* deferred function binding */
#define RTLD_NOW 0x00002 /* immediate function binding */
#define RTLD_GLOBAL 0x00100 /* export symbols to others */
#define RTLD_LOCAL 0x00000 /* symbols are only available */
Enumerations
enum dl_pmm_flags { DL_PMM_NORMAL = 0, DL_PMM_TEMPORARY = 1, DL_PMM_DEBUGINFO = 2 }
enum dlpoolflags { DL_POOLFLAGS_EXECUTABLE = 1, DL_POOLFLAGS_WRITABLE = 2, DL_POOLFLAGS_TEMPORARY = 4, DL_POOLFLAGS_DEBUGINFO = 8 }
Functions
void dlloader_init (void)
void * dlopen (const char *dllName, int mode)
void * dlopen_at (const char *dllName, void *kept, int keptspace, void *unkept, int unkeptspace)
void * dlopen_pmm (const char *dllName, void *(*pmm_alloc)(void *, unsigned int, unsigned int, const char *, unsigned int), void(*pmm_free)(void *, void *), void *pmm_priv)
int dlclose (void *)
const char * dlerror (void)
void dldone (void *handle)
int dlcheck (const char *pathName)
void * dlshared_vll_load (const char *vll_name, const char **symbols, void *(*pmm_alloc)(void *, unsigned int, unsigned int, const char *, unsigned int), void(*pmm_free)(void *, void *), void *pmm_priv, int *vll_init_required)
void dlshared_vll_init_done (void *vll)
int dlshared_vll_closing (void *vll)
int dlshared_vll_unload (void *vll)
int dlgetsegmentsizes (const char *vll, int *nrows, struct dlsegmentsizedata *segdata)
Variables
void(*)() dlsym (void *, const char *)
void(*)() dlshared_get_vll_symbol (void *vll, const char *symbol)
Macro Definition Documentation
RTLD_GLOBAL
#define RTLD_GLOBAL 0x00100 /* export symbols to others */
Definition at line 65 of file dlfcn.h.
RTLD_LAZY
#define RTLD_LAZY 0x00001 /* deferred function binding */
Definition at line 62 of file dlfcn.h.
Referenced by gpu_fft_get_host_info(), and libgps_load().
RTLD_LOCAL
#define RTLD_LOCAL 0x00000 /* symbols are only available */
Definition at line 66 of file dlfcn.h.
RTLD_NOW
#define RTLD_NOW 0x00002 /* immediate function binding */
Definition at line 63 of file dlfcn.h.
Enumeration Type Documentation
dl_pmm_flags
enum dl_pmm_flags
Enumerator
DL_PMM_NORMAL
DL_PMM_TEMPORARY
DL_PMM_DEBUGINFO
Definition at line 78 of file dlfcn.h.
                   {
    DL_PMM_NORMAL = 0,
    DL_PMM_TEMPORARY = 1,
    DL_PMM_DEBUGINFO = 2,
 };
dlpoolflags
enum dlpoolflags
Enumerator
DL_POOLFLAGS_EXECUTABLE
DL_POOLFLAGS_WRITABLE
DL_POOLFLAGS_TEMPORARY
DL_POOLFLAGS_DEBUGINFO
Definition at line 84 of file dlfcn.h.
                  {
    DL_POOLFLAGS_EXECUTABLE = 1,
    DL_POOLFLAGS_WRITABLE = 2,
    DL_POOLFLAGS_TEMPORARY = 4,
    DL_POOLFLAGS_DEBUGINFO = 8,
 };
Function Documentation
dlcheck()
int dlcheck (const char * pathName)
dlclose()
int dlclose (void *)
Referenced by gpu_fft_get_host_info(), libgps_unload(), and vcos_dlclose().
dldone()
void dldone (void * handle)
dlerror()
const char* dlerror (void)
Referenced by libgps_load(), and vcos_dlerror().
dlgetsegmentsizes()
int dlgetsegmentsizes (const char * vll, int * nrows, struct dlsegmentsizedata * segdata)
dlloader_init()
void dlloader_init (void)
dlopen()
void* dlopen (const char * dllName, int mode)
Referenced by gpu_fft_get_host_info(), libgps_load(), and vcos_dlopen().
dlopen_at()
void* dlopen_at (const char * dllName, void * kept, int keptspace, void * unkept, int unkeptspace)
dlopen_pmm()
void* dlopen_pmm (const char * dllName, void *(*)(void *, unsigned int, unsigned int, const char *, unsigned int) pmm_alloc, void(*)(void *, void *) pmm_free, void * pmm_priv)
dlshared_vll_closing()
int dlshared_vll_closing (void * vll)
dlshared_vll_init_done()
void dlshared_vll_init_done (void * vll)
dlshared_vll_load()
void* dlshared_vll_load (const char * vll_name, const char ** symbols, void *(*)(void *, unsigned int, unsigned int, const char *, unsigned int) pmm_alloc, void(*)(void *, void *) pmm_free, void * pmm_priv, int * vll_init_required)
dlshared_vll_unload()
int dlshared_vll_unload (void * vll)
Variable Documentation
dlshared_get_vll_symbol
void(*)() dlshared_get_vll_symbol(void *vll, const char *symbol)
dlsym
void(*)() dlsym(void *, const char *)
Referenced by gpu_fft_get_host_info().