VideoCore Library: interface/vcos/generic/vcos_mem_from_malloc.c File Reference
vcos_mem_from_malloc.c File Reference
#include "interface/vcos/vcos.h"
#include <stdlib.h>
Classes
struct malloc_header_s
Macros
#define _vcos_platform_malloc malloc
#define _vcos_platform_free free
#define MIN_ALIGN sizeof(MALLOC_HEADER_T)
#define GUARDWORDHEAP 0xa55a5aa5
Typedefs
typedef struct malloc_header_s MALLOC_HEADER_T
Functions
void * vcos_generic_mem_alloc_aligned (VCOS_UNSIGNED size, VCOS_UNSIGNED align, const char *desc)
void * vcos_generic_mem_alloc (VCOS_UNSIGNED size, const char *desc)
void * vcos_generic_mem_calloc (VCOS_UNSIGNED count, VCOS_UNSIGNED sz, const char *desc)
void vcos_generic_mem_free (void *ptr)
Macro Definition Documentation
_vcos_platform_free
#define _vcos_platform_free free
Definition at line 37 of file vcos_mem_from_malloc.c.
Referenced by vcos_generic_mem_free().
_vcos_platform_malloc
#define _vcos_platform_malloc malloc
Definition at line 36 of file vcos_mem_from_malloc.c.
Referenced by vcos_generic_mem_alloc_aligned().
GUARDWORDHEAP
#define GUARDWORDHEAP 0xa55a5aa5
Definition at line 50 of file vcos_mem_from_malloc.c.
Referenced by vcos_generic_mem_alloc_aligned(), and vcos_generic_mem_free().
MIN_ALIGN
#define MIN_ALIGN sizeof(MALLOC_HEADER_T)
Definition at line 48 of file vcos_mem_from_malloc.c.
Referenced by vcos_generic_mem_alloc(), and vcos_generic_mem_calloc().
Typedef Documentation
MALLOC_HEADER_T
typedef struct malloc_header_s MALLOC_HEADER_T
Function Documentation
vcos_generic_mem_alloc()
void* vcos_generic_mem_alloc (VCOS_UNSIGNED size, const char * desc)
Definition at line 73 of file vcos_mem_from_malloc.c.
References MIN_ALIGN, and vcos_generic_mem_alloc_aligned().
 {
    return vcos_generic_mem_alloc_aligned(size,MIN_ALIGN,desc);
 }
vcos_generic_mem_alloc_aligned()
void* vcos_generic_mem_alloc_aligned (VCOS_UNSIGNED size, VCOS_UNSIGNED align, const char * desc)
Definition at line 52 of file vcos_mem_from_malloc.c.
References _vcos_platform_malloc, malloc_header_s::description, malloc_header_s::guardword, GUARDWORDHEAP, NULL, malloc_header_s::ptr, malloc_header_s::size, and VCOS_ALIGN_UP.
Referenced by vcos_generic_mem_alloc(), and vcos_generic_mem_calloc().
 {
    int local_align = align == 0 ? 1 : align;
    int required_size = size + local_align + sizeof(MALLOC_HEADER_T);
    void *ptr = _vcos_platform_malloc(required_size);
    void *ret = NULL;
    MALLOC_HEADER_T *h;
    if (ptr)
    {
       ret = (void *)VCOS_ALIGN_UP(((char *)ptr)+sizeof(MALLOC_HEADER_T), local_align);
       h = ((MALLOC_HEADER_T *)ret)-1;
       h->size = size;
       h->description = desc;
       h->guardword = GUARDWORDHEAP;
       h->ptr = ptr;
    }
    return ret;
 }
vcos_generic_mem_calloc()
void* vcos_generic_mem_calloc (VCOS_UNSIGNED count, VCOS_UNSIGNED sz, const char * desc)
Definition at line 78 of file vcos_mem_from_malloc.c.
References MIN_ALIGN, malloc_header_s::ptr, and vcos_generic_mem_alloc_aligned().
 {
    uint32_t size = count*sz;
    void *ptr = vcos_generic_mem_alloc_aligned(size,MIN_ALIGN,desc);
    if (ptr)
    {
       memset(ptr, 0, size);
    }
    return ptr;
 }
vcos_generic_mem_free()
void vcos_generic_mem_free (void * ptr)
Definition at line 89 of file vcos_mem_from_malloc.c.
References _vcos_platform_free, malloc_header_s::guardword, GUARDWORDHEAP, malloc_header_s::ptr, and vcos_assert.
 {
    MALLOC_HEADER_T *h;
    if (! ptr) return;
    h = ((MALLOC_HEADER_T *)ptr)-1;
    vcos_assert(h->guardword == GUARDWORDHEAP);
    _vcos_platform_free(h->ptr);
 }