VideoCore Library: interface/khronos/include/GLES2/gl2.h File Reference
gl2.h File Reference
#include "gl2platform.h"
Macros
#define GL_ES_VERSION_2_0 1
#define GL_DEPTH_BUFFER_BIT 0x00000100
#define GL_STENCIL_BUFFER_BIT 0x00000400
#define GL_COLOR_BUFFER_BIT 0x00004000
#define GL_FALSE (GLboolean)0
#define GL_TRUE (GLboolean)1
#define GL_POINTS 0x0000
#define GL_LINES 0x0001
#define GL_LINE_LOOP 0x0002
#define GL_LINE_STRIP 0x0003
#define GL_TRIANGLES 0x0004
#define GL_TRIANGLE_STRIP 0x0005
#define GL_TRIANGLE_FAN 0x0006
#define GL_ZERO 0
#define GL_ONE 1
#define GL_SRC_COLOR 0x0300
#define GL_ONE_MINUS_SRC_COLOR 0x0301
#define GL_SRC_ALPHA 0x0302
#define GL_ONE_MINUS_SRC_ALPHA 0x0303
#define GL_DST_ALPHA 0x0304
#define GL_ONE_MINUS_DST_ALPHA 0x0305
#define GL_DST_COLOR 0x0306
#define GL_ONE_MINUS_DST_COLOR 0x0307
#define GL_SRC_ALPHA_SATURATE 0x0308
#define GL_FUNC_ADD 0x8006
#define GL_BLEND_EQUATION 0x8009
#define GL_BLEND_EQUATION_RGB 0x8009 /* same as BLEND_EQUATION */
#define GL_BLEND_EQUATION_ALPHA 0x883D
#define GL_FUNC_SUBTRACT 0x800A
#define GL_FUNC_REVERSE_SUBTRACT 0x800B
#define GL_BLEND_DST_RGB 0x80C8
#define GL_BLEND_SRC_RGB 0x80C9
#define GL_BLEND_DST_ALPHA 0x80CA
#define GL_BLEND_SRC_ALPHA 0x80CB
#define GL_CONSTANT_COLOR 0x8001
#define GL_ONE_MINUS_CONSTANT_COLOR 0x8002
#define GL_CONSTANT_ALPHA 0x8003
#define GL_ONE_MINUS_CONSTANT_ALPHA 0x8004
#define GL_BLEND_COLOR 0x8005
#define GL_ARRAY_BUFFER 0x8892
#define GL_ELEMENT_ARRAY_BUFFER 0x8893
#define GL_ARRAY_BUFFER_BINDING 0x8894
#define GL_ELEMENT_ARRAY_BUFFER_BINDING 0x8895
#define GL_STREAM_DRAW 0x88E0
#define GL_STATIC_DRAW 0x88E4
#define GL_DYNAMIC_DRAW 0x88E8
#define GL_BUFFER_SIZE 0x8764
#define GL_BUFFER_USAGE 0x8765
#define GL_CURRENT_VERTEX_ATTRIB 0x8626
#define GL_FRONT 0x0404
#define GL_BACK 0x0405
#define GL_FRONT_AND_BACK 0x0408
#define GL_TEXTURE_2D 0x0DE1
#define GL_CULL_FACE 0x0B44
#define GL_BLEND 0x0BE2
#define GL_DITHER 0x0BD0
#define GL_STENCIL_TEST 0x0B90
#define GL_DEPTH_TEST 0x0B71
#define GL_SCISSOR_TEST 0x0C11
#define GL_POLYGON_OFFSET_FILL 0x8037
#define GL_SAMPLE_ALPHA_TO_COVERAGE 0x809E
#define GL_SAMPLE_COVERAGE 0x80A0
#define GL_NO_ERROR 0
#define GL_INVALID_ENUM 0x0500
#define GL_INVALID_VALUE 0x0501
#define GL_INVALID_OPERATION 0x0502
#define GL_OUT_OF_MEMORY 0x0505
#define GL_CW 0x0900
#define GL_CCW 0x0901
#define GL_LINE_WIDTH 0x0B21
#define GL_ALIASED_POINT_SIZE_RANGE 0x846D
#define GL_ALIASED_LINE_WIDTH_RANGE 0x846E
#define GL_CULL_FACE_MODE 0x0B45
#define GL_FRONT_FACE 0x0B46
#define GL_DEPTH_RANGE 0x0B70
#define GL_DEPTH_WRITEMASK 0x0B72
#define GL_DEPTH_CLEAR_VALUE 0x0B73
#define GL_DEPTH_FUNC 0x0B74
#define GL_STENCIL_CLEAR_VALUE 0x0B91
#define GL_STENCIL_FUNC 0x0B92
#define GL_STENCIL_FAIL 0x0B94
#define GL_STENCIL_PASS_DEPTH_FAIL 0x0B95
#define GL_STENCIL_PASS_DEPTH_PASS 0x0B96
#define GL_STENCIL_REF 0x0B97
#define GL_STENCIL_VALUE_MASK 0x0B93
#define GL_STENCIL_WRITEMASK 0x0B98
#define GL_STENCIL_BACK_FUNC 0x8800
#define GL_STENCIL_BACK_FAIL 0x8801
#define GL_STENCIL_BACK_PASS_DEPTH_FAIL 0x8802
#define GL_STENCIL_BACK_PASS_DEPTH_PASS 0x8803
#define GL_STENCIL_BACK_REF 0x8CA3
#define GL_STENCIL_BACK_VALUE_MASK 0x8CA4
#define GL_STENCIL_BACK_WRITEMASK 0x8CA5
#define GL_VIEWPORT 0x0BA2
#define GL_SCISSOR_BOX 0x0C10
#define GL_COLOR_CLEAR_VALUE 0x0C22
#define GL_COLOR_WRITEMASK 0x0C23
#define GL_UNPACK_ALIGNMENT 0x0CF5
#define GL_PACK_ALIGNMENT 0x0D05
#define GL_MAX_TEXTURE_SIZE 0x0D33
#define GL_MAX_VIEWPORT_DIMS 0x0D3A
#define GL_SUBPIXEL_BITS 0x0D50
#define GL_RED_BITS 0x0D52
#define GL_GREEN_BITS 0x0D53
#define GL_BLUE_BITS 0x0D54
#define GL_ALPHA_BITS 0x0D55
#define GL_DEPTH_BITS 0x0D56
#define GL_STENCIL_BITS 0x0D57
#define GL_POLYGON_OFFSET_UNITS 0x2A00
#define GL_POLYGON_OFFSET_FACTOR 0x8038
#define GL_TEXTURE_BINDING_2D 0x8069
#define GL_SAMPLE_BUFFERS 0x80A8
#define GL_SAMPLES 0x80A9
#define GL_SAMPLE_COVERAGE_VALUE 0x80AA
#define GL_SAMPLE_COVERAGE_INVERT 0x80AB
#define GL_NUM_COMPRESSED_TEXTURE_FORMATS 0x86A2
#define GL_COMPRESSED_TEXTURE_FORMATS 0x86A3
#define GL_DONT_CARE 0x1100
#define GL_FASTEST 0x1101
#define GL_NICEST 0x1102
#define GL_GENERATE_MIPMAP_HINT 0x8192
#define GL_BYTE 0x1400
#define GL_UNSIGNED_BYTE 0x1401
#define GL_SHORT 0x1402
#define GL_UNSIGNED_SHORT 0x1403
#define GL_INT 0x1404
#define GL_UNSIGNED_INT 0x1405
#define GL_FLOAT 0x1406
#define GL_FIXED 0x140C
#define GL_DEPTH_COMPONENT 0x1902
#define GL_ALPHA 0x1906
#define GL_RGB 0x1907
#define GL_RGBA 0x1908
#define GL_LUMINANCE 0x1909
#define GL_LUMINANCE_ALPHA 0x190A
#define GL_UNSIGNED_SHORT_4_4_4_4 0x8033
#define GL_UNSIGNED_SHORT_5_5_5_1 0x8034
#define GL_UNSIGNED_SHORT_5_6_5 0x8363
#define GL_FRAGMENT_SHADER 0x8B30
#define GL_VERTEX_SHADER 0x8B31
#define GL_MAX_VERTEX_ATTRIBS 0x8869
#define GL_MAX_VERTEX_UNIFORM_VECTORS 0x8DFB
#define GL_MAX_VARYING_VECTORS 0x8DFC
#define GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS 0x8B4D
#define GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS 0x8B4C
#define GL_MAX_TEXTURE_IMAGE_UNITS 0x8872
#define GL_MAX_FRAGMENT_UNIFORM_VECTORS 0x8DFD
#define GL_SHADER_TYPE 0x8B4F
#define GL_DELETE_STATUS 0x8B80
#define GL_LINK_STATUS 0x8B82
#define GL_VALIDATE_STATUS 0x8B83
#define GL_ATTACHED_SHADERS 0x8B85
#define GL_ACTIVE_UNIFORMS 0x8B86
#define GL_ACTIVE_UNIFORM_MAX_LENGTH 0x8B87
#define GL_ACTIVE_ATTRIBUTES 0x8B89
#define GL_ACTIVE_ATTRIBUTE_MAX_LENGTH 0x8B8A
#define GL_SHADING_LANGUAGE_VERSION 0x8B8C
#define GL_CURRENT_PROGRAM 0x8B8D
#define GL_NEVER 0x0200
#define GL_LESS 0x0201
#define GL_EQUAL 0x0202
#define GL_LEQUAL 0x0203
#define GL_GREATER 0x0204
#define GL_NOTEQUAL 0x0205
#define GL_GEQUAL 0x0206
#define GL_ALWAYS 0x0207
#define GL_KEEP 0x1E00
#define GL_REPLACE 0x1E01
#define GL_INCR 0x1E02
#define GL_DECR 0x1E03
#define GL_INVERT 0x150A
#define GL_INCR_WRAP 0x8507
#define GL_DECR_WRAP 0x8508
#define GL_VENDOR 0x1F00
#define GL_RENDERER 0x1F01
#define GL_VERSION 0x1F02
#define GL_EXTENSIONS 0x1F03
#define GL_NEAREST 0x2600
#define GL_LINEAR 0x2601
#define GL_NEAREST_MIPMAP_NEAREST 0x2700
#define GL_LINEAR_MIPMAP_NEAREST 0x2701
#define GL_NEAREST_MIPMAP_LINEAR 0x2702
#define GL_LINEAR_MIPMAP_LINEAR 0x2703
#define GL_TEXTURE_MAG_FILTER 0x2800
#define GL_TEXTURE_MIN_FILTER 0x2801
#define GL_TEXTURE_WRAP_S 0x2802
#define GL_TEXTURE_WRAP_T 0x2803
#define GL_TEXTURE 0x1702
#define GL_TEXTURE_CUBE_MAP 0x8513
#define GL_TEXTURE_BINDING_CUBE_MAP 0x8514
#define GL_TEXTURE_CUBE_MAP_POSITIVE_X 0x8515
#define GL_TEXTURE_CUBE_MAP_NEGATIVE_X 0x8516
#define GL_TEXTURE_CUBE_MAP_POSITIVE_Y 0x8517
#define GL_TEXTURE_CUBE_MAP_NEGATIVE_Y 0x8518
#define GL_TEXTURE_CUBE_MAP_POSITIVE_Z 0x8519
#define GL_TEXTURE_CUBE_MAP_NEGATIVE_Z 0x851A
#define GL_MAX_CUBE_MAP_TEXTURE_SIZE 0x851C
#define GL_TEXTURE0 0x84C0
#define GL_TEXTURE1 0x84C1
#define GL_TEXTURE2 0x84C2
#define GL_TEXTURE3 0x84C3
#define GL_TEXTURE4 0x84C4
#define GL_TEXTURE5 0x84C5
#define GL_TEXTURE6 0x84C6
#define GL_TEXTURE7 0x84C7
#define GL_TEXTURE8 0x84C8
#define GL_TEXTURE9 0x84C9
#define GL_TEXTURE10 0x84CA
#define GL_TEXTURE11 0x84CB
#define GL_TEXTURE12 0x84CC
#define GL_TEXTURE13 0x84CD
#define GL_TEXTURE14 0x84CE
#define GL_TEXTURE15 0x84CF
#define GL_TEXTURE16 0x84D0
#define GL_TEXTURE17 0x84D1
#define GL_TEXTURE18 0x84D2
#define GL_TEXTURE19 0x84D3
#define GL_TEXTURE20 0x84D4
#define GL_TEXTURE21 0x84D5
#define GL_TEXTURE22 0x84D6
#define GL_TEXTURE23 0x84D7
#define GL_TEXTURE24 0x84D8
#define GL_TEXTURE25 0x84D9
#define GL_TEXTURE26 0x84DA
#define GL_TEXTURE27 0x84DB
#define GL_TEXTURE28 0x84DC
#define GL_TEXTURE29 0x84DD
#define GL_TEXTURE30 0x84DE
#define GL_TEXTURE31 0x84DF
#define GL_ACTIVE_TEXTURE 0x84E0
#define GL_REPEAT 0x2901
#define GL_CLAMP_TO_EDGE 0x812F
#define GL_MIRRORED_REPEAT 0x8370
#define GL_FLOAT_VEC2 0x8B50
#define GL_FLOAT_VEC3 0x8B51
#define GL_FLOAT_VEC4 0x8B52
#define GL_INT_VEC2 0x8B53
#define GL_INT_VEC3 0x8B54
#define GL_INT_VEC4 0x8B55
#define GL_BOOL 0x8B56
#define GL_BOOL_VEC2 0x8B57
#define GL_BOOL_VEC3 0x8B58
#define GL_BOOL_VEC4 0x8B59
#define GL_FLOAT_MAT2 0x8B5A
#define GL_FLOAT_MAT3 0x8B5B
#define GL_FLOAT_MAT4 0x8B5C
#define GL_SAMPLER_2D 0x8B5E
#define GL_SAMPLER_CUBE 0x8B60
#define GL_VERTEX_ATTRIB_ARRAY_ENABLED 0x8622
#define GL_VERTEX_ATTRIB_ARRAY_SIZE 0x8623
#define GL_VERTEX_ATTRIB_ARRAY_STRIDE 0x8624
#define GL_VERTEX_ATTRIB_ARRAY_TYPE 0x8625
#define GL_VERTEX_ATTRIB_ARRAY_NORMALIZED 0x886A
#define GL_VERTEX_ATTRIB_ARRAY_POINTER 0x8645
#define GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING 0x889F
#define GL_IMPLEMENTATION_COLOR_READ_TYPE 0x8B9A
#define GL_IMPLEMENTATION_COLOR_READ_FORMAT 0x8B9B
#define GL_COMPILE_STATUS 0x8B81
#define GL_INFO_LOG_LENGTH 0x8B84
#define GL_SHADER_SOURCE_LENGTH 0x8B88
#define GL_SHADER_COMPILER 0x8DFA
#define GL_SHADER_BINARY_FORMATS 0x8DF8
#define GL_NUM_SHADER_BINARY_FORMATS 0x8DF9
#define GL_LOW_FLOAT 0x8DF0
#define GL_MEDIUM_FLOAT 0x8DF1
#define GL_HIGH_FLOAT 0x8DF2
#define GL_LOW_INT 0x8DF3
#define GL_MEDIUM_INT 0x8DF4
#define GL_HIGH_INT 0x8DF5
#define GL_FRAMEBUFFER 0x8D40
#define GL_RENDERBUFFER 0x8D41
#define GL_RGBA4 0x8056
#define GL_RGB5_A1 0x8057
#define GL_RGB565 0x8D62
#define GL_DEPTH_COMPONENT16 0x81A5
#define GL_STENCIL_INDEX 0x1901
#define GL_STENCIL_INDEX8 0x8D48
#define GL_RENDERBUFFER_WIDTH 0x8D42
#define GL_RENDERBUFFER_HEIGHT 0x8D43
#define GL_RENDERBUFFER_INTERNAL_FORMAT 0x8D44
#define GL_RENDERBUFFER_RED_SIZE 0x8D50
#define GL_RENDERBUFFER_GREEN_SIZE 0x8D51
#define GL_RENDERBUFFER_BLUE_SIZE 0x8D52
#define GL_RENDERBUFFER_ALPHA_SIZE 0x8D53
#define GL_RENDERBUFFER_DEPTH_SIZE 0x8D54
#define GL_RENDERBUFFER_STENCIL_SIZE 0x8D55
#define GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE 0x8CD0
#define GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME 0x8CD1
#define GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL 0x8CD2
#define GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE 0x8CD3
#define GL_COLOR_ATTACHMENT0 0x8CE0
#define GL_DEPTH_ATTACHMENT 0x8D00
#define GL_STENCIL_ATTACHMENT 0x8D20
#define GL_NONE 0
#define GL_FRAMEBUFFER_COMPLETE 0x8CD5
#define GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT 0x8CD6
#define GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT 0x8CD7
#define GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS 0x8CD9
#define GL_FRAMEBUFFER_UNSUPPORTED 0x8CDD
#define GL_FRAMEBUFFER_BINDING 0x8CA6
#define GL_RENDERBUFFER_BINDING 0x8CA7
#define GL_MAX_RENDERBUFFER_SIZE 0x84E8
#define GL_INVALID_FRAMEBUFFER_OPERATION 0x0506
Typedefs
typedef void GLvoid
typedef char GLchar
typedef unsigned int GLenum
typedef unsigned char GLboolean
typedef unsigned int GLbitfield
typedef khronos_int8_t GLbyte
typedef short GLshort
typedef int GLint
typedef int GLsizei
typedef khronos_uint8_t GLubyte
typedef unsigned short GLushort
typedef unsigned int GLuint
typedef khronos_float_t GLfloat
typedef khronos_float_t GLclampf
typedef khronos_int32_t GLfixed
typedef khronos_intptr_t GLintptr
typedef khronos_ssize_t GLsizeiptr
Functions
GL_APICALL void GL_APIENTRY glActiveTexture (GLenum texture)
GL_APICALL void GL_APIENTRY glAttachShader (GLuint program, GLuint shader)
GL_APICALL void GL_APIENTRY glBindAttribLocation (GLuint program, GLuint index, const GLchar *name)
GL_APICALL void GL_APIENTRY glBindBuffer (GLenum target, GLuint buffer)
GL_APICALL void GL_APIENTRY glBindFramebuffer (GLenum target, GLuint framebuffer)
GL_APICALL void GL_APIENTRY glBindRenderbuffer (GLenum target, GLuint renderbuffer)
GL_APICALL void GL_APIENTRY glBindTexture (GLenum target, GLuint texture)
GL_APICALL void GL_APIENTRY glBlendColor (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
GL_APICALL void GL_APIENTRY glBlendEquation (GLenum mode)
GL_APICALL void GL_APIENTRY glBlendEquationSeparate (GLenum modeRGB, GLenum modeAlpha)
GL_APICALL void GL_APIENTRY glBlendFunc (GLenum sfactor, GLenum dfactor)
GL_APICALL void GL_APIENTRY glBlendFuncSeparate (GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha)
GL_APICALL void GL_APIENTRY glBufferData (GLenum target, GLsizeiptr size, const GLvoid *data, GLenum usage)
GL_APICALL void GL_APIENTRY glBufferSubData (GLenum target, GLintptr offset, GLsizeiptr size, const GLvoid *data)
GL_APICALL GLenum GL_APIENTRY glCheckFramebufferStatus (GLenum target)
GL_APICALL void GL_APIENTRY glClear (GLbitfield mask)
GL_APICALL void GL_APIENTRY glClearColor (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
GL_APICALL void GL_APIENTRY glClearDepthf (GLclampf depth)
GL_APICALL void GL_APIENTRY glClearStencil (GLint s)
GL_APICALL void GL_APIENTRY glColorMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
GL_APICALL void GL_APIENTRY glCompileShader (GLuint shader)
GL_APICALL void GL_APIENTRY glCompressedTexImage2D (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const GLvoid *data)
GL_APICALL void GL_APIENTRY glCompressedTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const GLvoid *data)
GL_APICALL void GL_APIENTRY glCopyTexImage2D (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border)
GL_APICALL void GL_APIENTRY glCopyTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height)
GL_APICALL GLuint GL_APIENTRY glCreateProgram (void)
GL_APICALL GLuint GL_APIENTRY glCreateShader (GLenum type)
GL_APICALL void GL_APIENTRY glCullFace (GLenum mode)
GL_APICALL void GL_APIENTRY glDeleteBuffers (GLsizei n, const GLuint *buffers)
GL_APICALL void GL_APIENTRY glDeleteFramebuffers (GLsizei n, const GLuint *framebuffers)
GL_APICALL void GL_APIENTRY glDeleteProgram (GLuint program)
GL_APICALL void GL_APIENTRY glDeleteRenderbuffers (GLsizei n, const GLuint *renderbuffers)
GL_APICALL void GL_APIENTRY glDeleteShader (GLuint shader)
GL_APICALL void GL_APIENTRY glDeleteTextures (GLsizei n, const GLuint *textures)
GL_APICALL void GL_APIENTRY glDepthFunc (GLenum func)
GL_APICALL void GL_APIENTRY glDepthMask (GLboolean flag)
GL_APICALL void GL_APIENTRY glDepthRangef (GLclampf zNear, GLclampf zFar)
GL_APICALL void GL_APIENTRY glDetachShader (GLuint program, GLuint shader)
GL_APICALL void GL_APIENTRY glDisable (GLenum cap)
GL_APICALL void GL_APIENTRY glDisableVertexAttribArray (GLuint index)
GL_APICALL void GL_APIENTRY glDrawArrays (GLenum mode, GLint first, GLsizei count)
GL_APICALL void GL_APIENTRY glDrawElements (GLenum mode, GLsizei count, GLenum type, const GLvoid *indices)
GL_APICALL void GL_APIENTRY glEnable (GLenum cap)
GL_APICALL void GL_APIENTRY glEnableVertexAttribArray (GLuint index)
GL_APICALL void GL_APIENTRY glFinish (void)
GL_APICALL void GL_APIENTRY glFlush (void)
GL_APICALL void GL_APIENTRY glFramebufferRenderbuffer (GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer)
GL_APICALL void GL_APIENTRY glFramebufferTexture2D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
GL_APICALL void GL_APIENTRY glFrontFace (GLenum mode)
GL_APICALL void GL_APIENTRY glGenBuffers (GLsizei n, GLuint *buffers)
GL_APICALL void GL_APIENTRY glGenerateMipmap (GLenum target)
GL_APICALL void GL_APIENTRY glGenFramebuffers (GLsizei n, GLuint *framebuffers)
GL_APICALL void GL_APIENTRY glGenRenderbuffers (GLsizei n, GLuint *renderbuffers)
GL_APICALL void GL_APIENTRY glGenTextures (GLsizei n, GLuint *textures)
GL_APICALL void GL_APIENTRY glGetActiveAttrib (GLuint program, GLuint index, GLsizei bufsize, GLsizei *length, GLint *size, GLenum *type, GLchar *name)
GL_APICALL void GL_APIENTRY glGetActiveUniform (GLuint program, GLuint index, GLsizei bufsize, GLsizei *length, GLint *size, GLenum *type, GLchar *name)
GL_APICALL void GL_APIENTRY glGetAttachedShaders (GLuint program, GLsizei maxcount, GLsizei *count, GLuint *shaders)
GL_APICALL int GL_APIENTRY glGetAttribLocation (GLuint program, const GLchar *name)
GL_APICALL void GL_APIENTRY glGetBooleanv (GLenum pname, GLboolean *params)
GL_APICALL void GL_APIENTRY glGetBufferParameteriv (GLenum target, GLenum pname, GLint *params)
GL_APICALL GLenum GL_APIENTRY glGetError (void)
GL_APICALL void GL_APIENTRY glGetFloatv (GLenum pname, GLfloat *params)
GL_APICALL void GL_APIENTRY glGetFramebufferAttachmentParameteriv (GLenum target, GLenum attachment, GLenum pname, GLint *params)
GL_APICALL void GL_APIENTRY glGetIntegerv (GLenum pname, GLint *params)
GL_APICALL void GL_APIENTRY glGetProgramiv (GLuint program, GLenum pname, GLint *params)
GL_APICALL void GL_APIENTRY glGetProgramInfoLog (GLuint program, GLsizei bufsize, GLsizei *length, GLchar *infolog)
GL_APICALL void GL_APIENTRY glGetRenderbufferParameteriv (GLenum target, GLenum pname, GLint *params)
GL_APICALL void GL_APIENTRY glGetShaderiv (GLuint shader, GLenum pname, GLint *params)
GL_APICALL void GL_APIENTRY glGetShaderInfoLog (GLuint shader, GLsizei bufsize, GLsizei *length, GLchar *infolog)
GL_APICALL void GL_APIENTRY glGetShaderPrecisionFormat (GLenum shadertype, GLenum precisiontype, GLint *range, GLint *precision)
GL_APICALL void GL_APIENTRY glGetShaderSource (GLuint shader, GLsizei bufsize, GLsizei *length, GLchar *source)
GL_APICALL const GLubyte *GL_APIENTRY glGetString (GLenum name)
GL_APICALL void GL_APIENTRY glGetTexParameterfv (GLenum target, GLenum pname, GLfloat *params)
GL_APICALL void GL_APIENTRY glGetTexParameteriv (GLenum target, GLenum pname, GLint *params)
GL_APICALL void GL_APIENTRY glGetUniformfv (GLuint program, GLint location, GLfloat *params)
GL_APICALL void GL_APIENTRY glGetUniformiv (GLuint program, GLint location, GLint *params)
GL_APICALL int GL_APIENTRY glGetUniformLocation (GLuint program, const GLchar *name)
GL_APICALL void GL_APIENTRY glGetVertexAttribfv (GLuint index, GLenum pname, GLfloat *params)
GL_APICALL void GL_APIENTRY glGetVertexAttribiv (GLuint index, GLenum pname, GLint *params)
GL_APICALL void GL_APIENTRY glGetVertexAttribPointerv (GLuint index, GLenum pname, GLvoid **pointer)
GL_APICALL void GL_APIENTRY glHint (GLenum target, GLenum mode)
GL_APICALL GLboolean GL_APIENTRY glIsBuffer (GLuint buffer)
GL_APICALL GLboolean GL_APIENTRY glIsEnabled (GLenum cap)
GL_APICALL GLboolean GL_APIENTRY glIsFramebuffer (GLuint framebuffer)
GL_APICALL GLboolean GL_APIENTRY glIsProgram (GLuint program)
GL_APICALL GLboolean GL_APIENTRY glIsRenderbuffer (GLuint renderbuffer)
GL_APICALL GLboolean GL_APIENTRY glIsShader (GLuint shader)
GL_APICALL GLboolean GL_APIENTRY glIsTexture (GLuint texture)
GL_APICALL void GL_APIENTRY glLineWidth (GLfloat width)
GL_APICALL void GL_APIENTRY glLinkProgram (GLuint program)
GL_APICALL void GL_APIENTRY glPixelStorei (GLenum pname, GLint param)
GL_APICALL void GL_APIENTRY glPolygonOffset (GLfloat factor, GLfloat units)
GL_APICALL void GL_APIENTRY glReadPixels (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels)
GL_APICALL void GL_APIENTRY glReleaseShaderCompiler (void)
GL_APICALL void GL_APIENTRY glRenderbufferStorage (GLenum target, GLenum internalformat, GLsizei width, GLsizei height)
GL_APICALL void GL_APIENTRY glSampleCoverage (GLclampf value, GLboolean invert)
GL_APICALL void GL_APIENTRY glScissor (GLint x, GLint y, GLsizei width, GLsizei height)
GL_APICALL void GL_APIENTRY glShaderBinary (GLsizei n, const GLuint *shaders, GLenum binaryformat, const GLvoid *binary, GLsizei length)
GL_APICALL void GL_APIENTRY glShaderSource (GLuint shader, GLsizei count, const GLchar **string, const GLint *length)
GL_APICALL void GL_APIENTRY glStencilFunc (GLenum func, GLint ref, GLuint mask)
GL_APICALL void GL_APIENTRY glStencilFuncSeparate (GLenum face, GLenum func, GLint ref, GLuint mask)
GL_APICALL void GL_APIENTRY glStencilMask (GLuint mask)
GL_APICALL void GL_APIENTRY glStencilMaskSeparate (GLenum face, GLuint mask)
GL_APICALL void GL_APIENTRY glStencilOp (GLenum fail, GLenum zfail, GLenum zpass)
GL_APICALL void GL_APIENTRY glStencilOpSeparate (GLenum face, GLenum fail, GLenum zfail, GLenum zpass)
GL_APICALL void GL_APIENTRY glTexImage2D (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels)
GL_APICALL void GL_APIENTRY glTexParameterf (GLenum target, GLenum pname, GLfloat param)
GL_APICALL void GL_APIENTRY glTexParameterfv (GLenum target, GLenum pname, const GLfloat *params)
GL_APICALL void GL_APIENTRY glTexParameteri (GLenum target, GLenum pname, GLint param)
GL_APICALL void GL_APIENTRY glTexParameteriv (GLenum target, GLenum pname, const GLint *params)
GL_APICALL void GL_APIENTRY glTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels)
GL_APICALL void GL_APIENTRY glUniform1f (GLint location, GLfloat x)
GL_APICALL void GL_APIENTRY glUniform1fv (GLint location, GLsizei count, const GLfloat *v)
GL_APICALL void GL_APIENTRY glUniform1i (GLint location, GLint x)
GL_APICALL void GL_APIENTRY glUniform1iv (GLint location, GLsizei count, const GLint *v)
GL_APICALL void GL_APIENTRY glUniform2f (GLint location, GLfloat x, GLfloat y)
GL_APICALL void GL_APIENTRY glUniform2fv (GLint location, GLsizei count, const GLfloat *v)
GL_APICALL void GL_APIENTRY glUniform2i (GLint location, GLint x, GLint y)
GL_APICALL void GL_APIENTRY glUniform2iv (GLint location, GLsizei count, const GLint *v)
GL_APICALL void GL_APIENTRY glUniform3f (GLint location, GLfloat x, GLfloat y, GLfloat z)
GL_APICALL void GL_APIENTRY glUniform3fv (GLint location, GLsizei count, const GLfloat *v)
GL_APICALL void GL_APIENTRY glUniform3i (GLint location, GLint x, GLint y, GLint z)
GL_APICALL void GL_APIENTRY glUniform3iv (GLint location, GLsizei count, const GLint *v)
GL_APICALL void GL_APIENTRY glUniform4f (GLint location, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
GL_APICALL void GL_APIENTRY glUniform4fv (GLint location, GLsizei count, const GLfloat *v)
GL_APICALL void GL_APIENTRY glUniform4i (GLint location, GLint x, GLint y, GLint z, GLint w)
GL_APICALL void GL_APIENTRY glUniform4iv (GLint location, GLsizei count, const GLint *v)
GL_APICALL void GL_APIENTRY glUniformMatrix2fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
GL_APICALL void GL_APIENTRY glUniformMatrix3fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
GL_APICALL void GL_APIENTRY glUniformMatrix4fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
GL_APICALL void GL_APIENTRY glUseProgram (GLuint program)
GL_APICALL void GL_APIENTRY glValidateProgram (GLuint program)
GL_APICALL void GL_APIENTRY glVertexAttrib1f (GLuint indx, GLfloat x)
GL_APICALL void GL_APIENTRY glVertexAttrib1fv (GLuint indx, const GLfloat *values)
GL_APICALL void GL_APIENTRY glVertexAttrib2f (GLuint indx, GLfloat x, GLfloat y)
GL_APICALL void GL_APIENTRY glVertexAttrib2fv (GLuint indx, const GLfloat *values)
GL_APICALL void GL_APIENTRY glVertexAttrib3f (GLuint indx, GLfloat x, GLfloat y, GLfloat z)
GL_APICALL void GL_APIENTRY glVertexAttrib3fv (GLuint indx, const GLfloat *values)
GL_APICALL void GL_APIENTRY glVertexAttrib4f (GLuint indx, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
GL_APICALL void GL_APIENTRY glVertexAttrib4fv (GLuint indx, const GLfloat *values)
GL_APICALL void GL_APIENTRY glVertexAttribPointer (GLuint indx, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const GLvoid *ptr)
GL_APICALL void GL_APIENTRY glViewport (GLint x, GLint y, GLsizei width, GLsizei height)
Macro Definition Documentation
GL_ACTIVE_ATTRIBUTE_MAX_LENGTH
#define GL_ACTIVE_ATTRIBUTE_MAX_LENGTH 0x8B8A
Definition at line 304 of file gl2.h.
GL_ACTIVE_ATTRIBUTES
#define GL_ACTIVE_ATTRIBUTES 0x8B89
Definition at line 303 of file gl2.h.
GL_ACTIVE_TEXTURE
#define GL_ACTIVE_TEXTURE 0x84E0
Definition at line 399 of file gl2.h.
GL_ACTIVE_UNIFORM_MAX_LENGTH
#define GL_ACTIVE_UNIFORM_MAX_LENGTH 0x8B87
Definition at line 302 of file gl2.h.
GL_ACTIVE_UNIFORMS
#define GL_ACTIVE_UNIFORMS 0x8B86
Definition at line 301 of file gl2.h.
GL_ALIASED_LINE_WIDTH_RANGE
#define GL_ALIASED_LINE_WIDTH_RANGE 0x846E
Definition at line 198 of file gl2.h.
GL_ALIASED_POINT_SIZE_RANGE
#define GL_ALIASED_POINT_SIZE_RANGE 0x846D
Definition at line 197 of file gl2.h.
GL_ALPHA
#define GL_ALPHA 0x1906
Definition at line 274 of file gl2.h.
GL_ALPHA_BITS
#define GL_ALPHA_BITS 0x0D55
Definition at line 233 of file gl2.h.
GL_ALWAYS
#define GL_ALWAYS 0x0207
Definition at line 316 of file gl2.h.
GL_ARRAY_BUFFER
#define GL_ARRAY_BUFFER 0x8892
Definition at line 143 of file gl2.h.
GL_ARRAY_BUFFER_BINDING
#define GL_ARRAY_BUFFER_BINDING 0x8894
Definition at line 145 of file gl2.h.
GL_ATTACHED_SHADERS
#define GL_ATTACHED_SHADERS 0x8B85
Definition at line 300 of file gl2.h.
GL_BACK
#define GL_BACK 0x0405
Definition at line 159 of file gl2.h.
GL_BLEND
#define GL_BLEND 0x0BE2
Definition at line 175 of file gl2.h.
GL_BLEND_COLOR
#define GL_BLEND_COLOR 0x8005
Definition at line 140 of file gl2.h.
GL_BLEND_DST_ALPHA
#define GL_BLEND_DST_ALPHA 0x80CA
Definition at line 134 of file gl2.h.
GL_BLEND_DST_RGB
#define GL_BLEND_DST_RGB 0x80C8
Definition at line 132 of file gl2.h.
GL_BLEND_EQUATION
#define GL_BLEND_EQUATION 0x8009
Definition at line 123 of file gl2.h.
GL_BLEND_EQUATION_ALPHA
#define GL_BLEND_EQUATION_ALPHA 0x883D
Definition at line 125 of file gl2.h.
GL_BLEND_EQUATION_RGB
#define GL_BLEND_EQUATION_RGB 0x8009 /* same as BLEND_EQUATION */
Definition at line 124 of file gl2.h.
GL_BLEND_SRC_ALPHA
#define GL_BLEND_SRC_ALPHA 0x80CB
Definition at line 135 of file gl2.h.
GL_BLEND_SRC_RGB
#define GL_BLEND_SRC_RGB 0x80C9
Definition at line 133 of file gl2.h.
GL_BLUE_BITS
#define GL_BLUE_BITS 0x0D54
Definition at line 232 of file gl2.h.
GL_BOOL
#define GL_BOOL 0x8B56
Definition at line 413 of file gl2.h.
GL_BOOL_VEC2
#define GL_BOOL_VEC2 0x8B57
Definition at line 414 of file gl2.h.
GL_BOOL_VEC3
#define GL_BOOL_VEC3 0x8B58
Definition at line 415 of file gl2.h.
GL_BOOL_VEC4
#define GL_BOOL_VEC4 0x8B59
Definition at line 416 of file gl2.h.
GL_BUFFER_SIZE
#define GL_BUFFER_SIZE 0x8764
Definition at line 152 of file gl2.h.
GL_BUFFER_USAGE
#define GL_BUFFER_USAGE 0x8765
Definition at line 153 of file gl2.h.
GL_BYTE
#define GL_BYTE 0x1400
Definition at line 263 of file gl2.h.
GL_CCW
#define GL_CCW 0x0901
Definition at line 193 of file gl2.h.
GL_CLAMP_TO_EDGE
#define GL_CLAMP_TO_EDGE 0x812F
Definition at line 403 of file gl2.h.
GL_COLOR_ATTACHMENT0
#define GL_COLOR_ATTACHMENT0 0x8CE0
Definition at line 480 of file gl2.h.
GL_COLOR_BUFFER_BIT
#define GL_COLOR_BUFFER_BIT 0x00004000
Definition at line 75 of file gl2.h.
GL_COLOR_CLEAR_VALUE
#define GL_COLOR_CLEAR_VALUE 0x0C22
Definition at line 223 of file gl2.h.
GL_COLOR_WRITEMASK
#define GL_COLOR_WRITEMASK 0x0C23
Definition at line 224 of file gl2.h.
GL_COMPILE_STATUS
#define GL_COMPILE_STATUS 0x8B81
Definition at line 437 of file gl2.h.
Referenced by raspitexutil_build_shader_program().
GL_COMPRESSED_TEXTURE_FORMATS
#define GL_COMPRESSED_TEXTURE_FORMATS 0x86A3
Definition at line 252 of file gl2.h.
GL_CONSTANT_ALPHA
#define GL_CONSTANT_ALPHA 0x8003
Definition at line 138 of file gl2.h.
GL_CONSTANT_COLOR
#define GL_CONSTANT_COLOR 0x8001
Definition at line 136 of file gl2.h.
GL_CULL_FACE
#define GL_CULL_FACE 0x0B44
Definition at line 174 of file gl2.h.
GL_CULL_FACE_MODE
#define GL_CULL_FACE_MODE 0x0B45
Definition at line 199 of file gl2.h.
GL_CURRENT_PROGRAM
#define GL_CURRENT_PROGRAM 0x8B8D
Definition at line 306 of file gl2.h.
GL_CURRENT_VERTEX_ATTRIB
#define GL_CURRENT_VERTEX_ATTRIB 0x8626
Definition at line 155 of file gl2.h.
GL_CW
#define GL_CW 0x0900
Definition at line 192 of file gl2.h.
GL_DECR
#define GL_DECR 0x1E03
Definition at line 323 of file gl2.h.
GL_DECR_WRAP
#define GL_DECR_WRAP 0x8508
Definition at line 326 of file gl2.h.
GL_DELETE_STATUS
#define GL_DELETE_STATUS 0x8B80
Definition at line 297 of file gl2.h.
GL_DEPTH_ATTACHMENT
#define GL_DEPTH_ATTACHMENT 0x8D00
Definition at line 481 of file gl2.h.
GL_DEPTH_BITS
#define GL_DEPTH_BITS 0x0D56
Definition at line 234 of file gl2.h.
GL_DEPTH_BUFFER_BIT
#define GL_DEPTH_BUFFER_BIT 0x00000100
Definition at line 73 of file gl2.h.
GL_DEPTH_CLEAR_VALUE
#define GL_DEPTH_CLEAR_VALUE 0x0B73
Definition at line 203 of file gl2.h.
GL_DEPTH_COMPONENT
#define GL_DEPTH_COMPONENT 0x1902
Definition at line 273 of file gl2.h.
GL_DEPTH_COMPONENT16
#define GL_DEPTH_COMPONENT16 0x81A5
Definition at line 461 of file gl2.h.
GL_DEPTH_FUNC
#define GL_DEPTH_FUNC 0x0B74
Definition at line 204 of file gl2.h.
GL_DEPTH_RANGE
#define GL_DEPTH_RANGE 0x0B70
Definition at line 201 of file gl2.h.
GL_DEPTH_TEST
#define GL_DEPTH_TEST 0x0B71
Definition at line 178 of file gl2.h.
GL_DEPTH_WRITEMASK
#define GL_DEPTH_WRITEMASK 0x0B72
Definition at line 202 of file gl2.h.
GL_DITHER
#define GL_DITHER 0x0BD0
Definition at line 176 of file gl2.h.
GL_DONT_CARE
#define GL_DONT_CARE 0x1100
Definition at line 255 of file gl2.h.
GL_DST_ALPHA
#define GL_DST_ALPHA 0x0304
Definition at line 107 of file gl2.h.
GL_DST_COLOR
#define GL_DST_COLOR 0x0306
Definition at line 113 of file gl2.h.
GL_DYNAMIC_DRAW
#define GL_DYNAMIC_DRAW 0x88E8
Definition at line 150 of file gl2.h.
GL_ELEMENT_ARRAY_BUFFER
#define GL_ELEMENT_ARRAY_BUFFER 0x8893
Definition at line 144 of file gl2.h.
GL_ELEMENT_ARRAY_BUFFER_BINDING
#define GL_ELEMENT_ARRAY_BUFFER_BINDING 0x8895
Definition at line 146 of file gl2.h.
GL_EQUAL
#define GL_EQUAL 0x0202
Definition at line 311 of file gl2.h.
GL_ES_VERSION_2_0
#define GL_ES_VERSION_2_0 1
Definition at line 70 of file gl2.h.
GL_EXTENSIONS
#define GL_EXTENSIONS 0x1F03
Definition at line 332 of file gl2.h.
GL_FALSE
#define GL_FALSE (GLboolean)0
Definition at line 78 of file gl2.h.
GL_FASTEST
#define GL_FASTEST 0x1101
Definition at line 256 of file gl2.h.
GL_FIXED
#define GL_FIXED 0x140C
Definition at line 270 of file gl2.h.
GL_FLOAT
#define GL_FLOAT 0x1406
Definition at line 269 of file gl2.h.
GL_FLOAT_MAT2
#define GL_FLOAT_MAT2 0x8B5A
Definition at line 417 of file gl2.h.
GL_FLOAT_MAT3
#define GL_FLOAT_MAT3 0x8B5B
Definition at line 418 of file gl2.h.
GL_FLOAT_MAT4
#define GL_FLOAT_MAT4 0x8B5C
Definition at line 419 of file gl2.h.
GL_FLOAT_VEC2
#define GL_FLOAT_VEC2 0x8B50
Definition at line 407 of file gl2.h.
GL_FLOAT_VEC3
#define GL_FLOAT_VEC3 0x8B51
Definition at line 408 of file gl2.h.
GL_FLOAT_VEC4
#define GL_FLOAT_VEC4 0x8B52
Definition at line 409 of file gl2.h.
GL_FRAGMENT_SHADER
#define GL_FRAGMENT_SHADER 0x8B30
Definition at line 287 of file gl2.h.
Referenced by raspitexutil_build_shader_program().
GL_FRAMEBUFFER
#define GL_FRAMEBUFFER 0x8D40
Definition at line 455 of file gl2.h.
GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME
#define GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME 0x8CD1
Definition at line 476 of file gl2.h.
GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE
#define GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE 0x8CD0
Definition at line 475 of file gl2.h.
GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE
#define GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE 0x8CD3
Definition at line 478 of file gl2.h.
GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL
#define GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL 0x8CD2
Definition at line 477 of file gl2.h.
GL_FRAMEBUFFER_BINDING
#define GL_FRAMEBUFFER_BINDING 0x8CA6
Definition at line 492 of file gl2.h.
GL_FRAMEBUFFER_COMPLETE
#define GL_FRAMEBUFFER_COMPLETE 0x8CD5
Definition at line 486 of file gl2.h.
GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT
#define GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT 0x8CD6
Definition at line 487 of file gl2.h.
GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS
#define GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS 0x8CD9
Definition at line 489 of file gl2.h.
GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT
#define GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT 0x8CD7
Definition at line 488 of file gl2.h.
GL_FRAMEBUFFER_UNSUPPORTED
#define GL_FRAMEBUFFER_UNSUPPORTED 0x8CDD
Definition at line 490 of file gl2.h.
GL_FRONT
#define GL_FRONT 0x0404
Definition at line 158 of file gl2.h.
GL_FRONT_AND_BACK
#define GL_FRONT_AND_BACK 0x0408
Definition at line 160 of file gl2.h.
GL_FRONT_FACE
#define GL_FRONT_FACE 0x0B46
Definition at line 200 of file gl2.h.
GL_FUNC_ADD
#define GL_FUNC_ADD 0x8006
Definition at line 122 of file gl2.h.
GL_FUNC_REVERSE_SUBTRACT
#define GL_FUNC_REVERSE_SUBTRACT 0x800B
Definition at line 129 of file gl2.h.
GL_FUNC_SUBTRACT
#define GL_FUNC_SUBTRACT 0x800A
Definition at line 128 of file gl2.h.
GL_GENERATE_MIPMAP_HINT
#define GL_GENERATE_MIPMAP_HINT 0x8192
Definition at line 260 of file gl2.h.
GL_GEQUAL
#define GL_GEQUAL 0x0206
Definition at line 315 of file gl2.h.
GL_GREATER
#define GL_GREATER 0x0204
Definition at line 313 of file gl2.h.
GL_GREEN_BITS
#define GL_GREEN_BITS 0x0D53
Definition at line 231 of file gl2.h.
GL_HIGH_FLOAT
#define GL_HIGH_FLOAT 0x8DF2
Definition at line 449 of file gl2.h.
GL_HIGH_INT
#define GL_HIGH_INT 0x8DF5
Definition at line 452 of file gl2.h.
GL_IMPLEMENTATION_COLOR_READ_FORMAT
#define GL_IMPLEMENTATION_COLOR_READ_FORMAT 0x8B9B
Definition at line 434 of file gl2.h.
GL_IMPLEMENTATION_COLOR_READ_TYPE
#define GL_IMPLEMENTATION_COLOR_READ_TYPE 0x8B9A
Definition at line 433 of file gl2.h.
GL_INCR
#define GL_INCR 0x1E02
Definition at line 322 of file gl2.h.
GL_INCR_WRAP
#define GL_INCR_WRAP 0x8507
Definition at line 325 of file gl2.h.
GL_INFO_LOG_LENGTH
#define GL_INFO_LOG_LENGTH 0x8B84
Definition at line 438 of file gl2.h.
GL_INT
#define GL_INT 0x1404
Definition at line 267 of file gl2.h.
GL_INT_VEC2
#define GL_INT_VEC2 0x8B53
Definition at line 410 of file gl2.h.
GL_INT_VEC3
#define GL_INT_VEC3 0x8B54
Definition at line 411 of file gl2.h.
GL_INT_VEC4
#define GL_INT_VEC4 0x8B55
Definition at line 412 of file gl2.h.
GL_INVALID_ENUM
#define GL_INVALID_ENUM 0x0500
Definition at line 186 of file gl2.h.
GL_INVALID_FRAMEBUFFER_OPERATION
#define GL_INVALID_FRAMEBUFFER_OPERATION 0x0506
Definition at line 496 of file gl2.h.
GL_INVALID_OPERATION
#define GL_INVALID_OPERATION 0x0502
Definition at line 188 of file gl2.h.
GL_INVALID_VALUE
#define GL_INVALID_VALUE 0x0501
Definition at line 187 of file gl2.h.
GL_INVERT
#define GL_INVERT 0x150A
Definition at line 324 of file gl2.h.
GL_KEEP
#define GL_KEEP 0x1E00
Definition at line 320 of file gl2.h.
GL_LEQUAL
#define GL_LEQUAL 0x0203
Definition at line 312 of file gl2.h.
GL_LESS
#define GL_LESS 0x0201
Definition at line 310 of file gl2.h.
GL_LINE_LOOP
#define GL_LINE_LOOP 0x0002
Definition at line 84 of file gl2.h.
GL_LINE_STRIP
#define GL_LINE_STRIP 0x0003
Definition at line 85 of file gl2.h.
GL_LINE_WIDTH
#define GL_LINE_WIDTH 0x0B21
Definition at line 196 of file gl2.h.
GL_LINEAR
#define GL_LINEAR 0x2601
Definition at line 336 of file gl2.h.
GL_LINEAR_MIPMAP_LINEAR
#define GL_LINEAR_MIPMAP_LINEAR 0x2703
Definition at line 344 of file gl2.h.
GL_LINEAR_MIPMAP_NEAREST
#define GL_LINEAR_MIPMAP_NEAREST 0x2701
Definition at line 342 of file gl2.h.
GL_LINES
#define GL_LINES 0x0001
Definition at line 83 of file gl2.h.
GL_LINK_STATUS
#define GL_LINK_STATUS 0x8B82
Definition at line 298 of file gl2.h.
Referenced by raspitexutil_build_shader_program().
GL_LOW_FLOAT
#define GL_LOW_FLOAT 0x8DF0
Definition at line 447 of file gl2.h.
GL_LOW_INT
#define GL_LOW_INT 0x8DF3
Definition at line 450 of file gl2.h.
GL_LUMINANCE
#define GL_LUMINANCE 0x1909
Definition at line 277 of file gl2.h.
GL_LUMINANCE_ALPHA
#define GL_LUMINANCE_ALPHA 0x190A
Definition at line 278 of file gl2.h.
GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS
#define GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS 0x8B4D
Definition at line 292 of file gl2.h.
GL_MAX_CUBE_MAP_TEXTURE_SIZE
#define GL_MAX_CUBE_MAP_TEXTURE_SIZE 0x851C
Definition at line 364 of file gl2.h.
GL_MAX_FRAGMENT_UNIFORM_VECTORS
#define GL_MAX_FRAGMENT_UNIFORM_VECTORS 0x8DFD
Definition at line 295 of file gl2.h.
GL_MAX_RENDERBUFFER_SIZE
#define GL_MAX_RENDERBUFFER_SIZE 0x84E8
Definition at line 494 of file gl2.h.
GL_MAX_TEXTURE_IMAGE_UNITS
#define GL_MAX_TEXTURE_IMAGE_UNITS 0x8872
Definition at line 294 of file gl2.h.
GL_MAX_TEXTURE_SIZE
#define GL_MAX_TEXTURE_SIZE 0x0D33
Definition at line 227 of file gl2.h.
GL_MAX_VARYING_VECTORS
#define GL_MAX_VARYING_VECTORS 0x8DFC
Definition at line 291 of file gl2.h.
GL_MAX_VERTEX_ATTRIBS
#define GL_MAX_VERTEX_ATTRIBS 0x8869
Definition at line 289 of file gl2.h.
GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS
#define GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS 0x8B4C
Definition at line 293 of file gl2.h.
GL_MAX_VERTEX_UNIFORM_VECTORS
#define GL_MAX_VERTEX_UNIFORM_VECTORS 0x8DFB
Definition at line 290 of file gl2.h.
GL_MAX_VIEWPORT_DIMS
#define GL_MAX_VIEWPORT_DIMS 0x0D3A
Definition at line 228 of file gl2.h.
GL_MEDIUM_FLOAT
#define GL_MEDIUM_FLOAT 0x8DF1
Definition at line 448 of file gl2.h.
GL_MEDIUM_INT
#define GL_MEDIUM_INT 0x8DF4
Definition at line 451 of file gl2.h.
GL_MIRRORED_REPEAT
#define GL_MIRRORED_REPEAT 0x8370
Definition at line 404 of file gl2.h.
GL_NEAREST
#define GL_NEAREST 0x2600
Definition at line 335 of file gl2.h.
GL_NEAREST_MIPMAP_LINEAR
#define GL_NEAREST_MIPMAP_LINEAR 0x2702
Definition at line 343 of file gl2.h.
GL_NEAREST_MIPMAP_NEAREST
#define GL_NEAREST_MIPMAP_NEAREST 0x2700
Definition at line 341 of file gl2.h.
GL_NEVER
#define GL_NEVER 0x0200
Definition at line 309 of file gl2.h.
GL_NICEST
#define GL_NICEST 0x1102
Definition at line 257 of file gl2.h.
GL_NO_ERROR
#define GL_NO_ERROR 0
Definition at line 185 of file gl2.h.
GL_NONE
#define GL_NONE 0
Definition at line 484 of file gl2.h.
GL_NOTEQUAL
#define GL_NOTEQUAL 0x0205
Definition at line 314 of file gl2.h.
GL_NUM_COMPRESSED_TEXTURE_FORMATS
#define GL_NUM_COMPRESSED_TEXTURE_FORMATS 0x86A2
Definition at line 251 of file gl2.h.
GL_NUM_SHADER_BINARY_FORMATS
#define GL_NUM_SHADER_BINARY_FORMATS 0x8DF9
Definition at line 444 of file gl2.h.
GL_ONE
#define GL_ONE 1
Definition at line 102 of file gl2.h.
GL_ONE_MINUS_CONSTANT_ALPHA
#define GL_ONE_MINUS_CONSTANT_ALPHA 0x8004
Definition at line 139 of file gl2.h.
GL_ONE_MINUS_CONSTANT_COLOR
#define GL_ONE_MINUS_CONSTANT_COLOR 0x8002
Definition at line 137 of file gl2.h.
GL_ONE_MINUS_DST_ALPHA
#define GL_ONE_MINUS_DST_ALPHA 0x0305
Definition at line 108 of file gl2.h.
GL_ONE_MINUS_DST_COLOR
#define GL_ONE_MINUS_DST_COLOR 0x0307
Definition at line 114 of file gl2.h.
GL_ONE_MINUS_SRC_ALPHA
#define GL_ONE_MINUS_SRC_ALPHA 0x0303
Definition at line 106 of file gl2.h.
GL_ONE_MINUS_SRC_COLOR
#define GL_ONE_MINUS_SRC_COLOR 0x0301
Definition at line 104 of file gl2.h.
GL_OUT_OF_MEMORY
#define GL_OUT_OF_MEMORY 0x0505
Definition at line 189 of file gl2.h.
GL_PACK_ALIGNMENT
#define GL_PACK_ALIGNMENT 0x0D05
Definition at line 226 of file gl2.h.
GL_POINTS
#define GL_POINTS 0x0000
Definition at line 82 of file gl2.h.
GL_POLYGON_OFFSET_FACTOR
#define GL_POLYGON_OFFSET_FACTOR 0x8038
Definition at line 238 of file gl2.h.
GL_POLYGON_OFFSET_FILL
#define GL_POLYGON_OFFSET_FILL 0x8037
Definition at line 180 of file gl2.h.
GL_POLYGON_OFFSET_UNITS
#define GL_POLYGON_OFFSET_UNITS 0x2A00
Definition at line 236 of file gl2.h.
GL_RED_BITS
#define GL_RED_BITS 0x0D52
Definition at line 230 of file gl2.h.
GL_RENDERBUFFER
#define GL_RENDERBUFFER 0x8D41
Definition at line 456 of file gl2.h.
GL_RENDERBUFFER_ALPHA_SIZE
#define GL_RENDERBUFFER_ALPHA_SIZE 0x8D53
Definition at line 471 of file gl2.h.
GL_RENDERBUFFER_BINDING
#define GL_RENDERBUFFER_BINDING 0x8CA7
Definition at line 493 of file gl2.h.
GL_RENDERBUFFER_BLUE_SIZE
#define GL_RENDERBUFFER_BLUE_SIZE 0x8D52
Definition at line 470 of file gl2.h.
GL_RENDERBUFFER_DEPTH_SIZE
#define GL_RENDERBUFFER_DEPTH_SIZE 0x8D54
Definition at line 472 of file gl2.h.
GL_RENDERBUFFER_GREEN_SIZE
#define GL_RENDERBUFFER_GREEN_SIZE 0x8D51
Definition at line 469 of file gl2.h.
GL_RENDERBUFFER_HEIGHT
#define GL_RENDERBUFFER_HEIGHT 0x8D43
Definition at line 466 of file gl2.h.
GL_RENDERBUFFER_INTERNAL_FORMAT
#define GL_RENDERBUFFER_INTERNAL_FORMAT 0x8D44
Definition at line 467 of file gl2.h.
GL_RENDERBUFFER_RED_SIZE
#define GL_RENDERBUFFER_RED_SIZE 0x8D50
Definition at line 468 of file gl2.h.
GL_RENDERBUFFER_STENCIL_SIZE
#define GL_RENDERBUFFER_STENCIL_SIZE 0x8D55
Definition at line 473 of file gl2.h.
GL_RENDERBUFFER_WIDTH
#define GL_RENDERBUFFER_WIDTH 0x8D42
Definition at line 465 of file gl2.h.
GL_RENDERER
#define GL_RENDERER 0x1F01
Definition at line 330 of file gl2.h.
GL_REPEAT
#define GL_REPEAT 0x2901
Definition at line 402 of file gl2.h.
GL_REPLACE
#define GL_REPLACE 0x1E01
Definition at line 321 of file gl2.h.
GL_RGB
#define GL_RGB 0x1907
Definition at line 275 of file gl2.h.
GL_RGB565
#define GL_RGB565 0x8D62
Definition at line 460 of file gl2.h.
GL_RGB5_A1
#define GL_RGB5_A1 0x8057
Definition at line 459 of file gl2.h.
GL_RGBA
#define GL_RGBA 0x1908
Definition at line 276 of file gl2.h.
GL_RGBA4
#define GL_RGBA4 0x8056
Definition at line 458 of file gl2.h.
GL_SAMPLE_ALPHA_TO_COVERAGE
#define GL_SAMPLE_ALPHA_TO_COVERAGE 0x809E
Definition at line 181 of file gl2.h.
GL_SAMPLE_BUFFERS
#define GL_SAMPLE_BUFFERS 0x80A8
Definition at line 240 of file gl2.h.
GL_SAMPLE_COVERAGE
#define GL_SAMPLE_COVERAGE 0x80A0
Definition at line 182 of file gl2.h.
GL_SAMPLE_COVERAGE_INVERT
#define GL_SAMPLE_COVERAGE_INVERT 0x80AB
Definition at line 243 of file gl2.h.
GL_SAMPLE_COVERAGE_VALUE
#define GL_SAMPLE_COVERAGE_VALUE 0x80AA
Definition at line 242 of file gl2.h.
GL_SAMPLER_2D
#define GL_SAMPLER_2D 0x8B5E
Definition at line 420 of file gl2.h.
GL_SAMPLER_CUBE
#define GL_SAMPLER_CUBE 0x8B60
Definition at line 421 of file gl2.h.
GL_SAMPLES
#define GL_SAMPLES 0x80A9
Definition at line 241 of file gl2.h.
GL_SCISSOR_BOX
#define GL_SCISSOR_BOX 0x0C10
Definition at line 221 of file gl2.h.
GL_SCISSOR_TEST
#define GL_SCISSOR_TEST 0x0C11
Definition at line 179 of file gl2.h.
GL_SHADER_BINARY_FORMATS
#define GL_SHADER_BINARY_FORMATS 0x8DF8
Definition at line 443 of file gl2.h.
GL_SHADER_COMPILER
#define GL_SHADER_COMPILER 0x8DFA
Definition at line 440 of file gl2.h.
GL_SHADER_SOURCE_LENGTH
#define GL_SHADER_SOURCE_LENGTH 0x8B88
Definition at line 439 of file gl2.h.
GL_SHADER_TYPE
#define GL_SHADER_TYPE 0x8B4F
Definition at line 296 of file gl2.h.
GL_SHADING_LANGUAGE_VERSION
#define GL_SHADING_LANGUAGE_VERSION 0x8B8C
Definition at line 305 of file gl2.h.
GL_SHORT
#define GL_SHORT 0x1402
Definition at line 265 of file gl2.h.
GL_SRC_ALPHA
#define GL_SRC_ALPHA 0x0302
Definition at line 105 of file gl2.h.
GL_SRC_ALPHA_SATURATE
#define GL_SRC_ALPHA_SATURATE 0x0308
Definition at line 115 of file gl2.h.
GL_SRC_COLOR
#define GL_SRC_COLOR 0x0300
Definition at line 103 of file gl2.h.
GL_STATIC_DRAW
#define GL_STATIC_DRAW 0x88E4
Definition at line 149 of file gl2.h.
GL_STENCIL_ATTACHMENT
#define GL_STENCIL_ATTACHMENT 0x8D20
Definition at line 482 of file gl2.h.
GL_STENCIL_BACK_FAIL
#define GL_STENCIL_BACK_FAIL 0x8801
Definition at line 214 of file gl2.h.
GL_STENCIL_BACK_FUNC
#define GL_STENCIL_BACK_FUNC 0x8800
Definition at line 213 of file gl2.h.
GL_STENCIL_BACK_PASS_DEPTH_FAIL
#define GL_STENCIL_BACK_PASS_DEPTH_FAIL 0x8802
Definition at line 215 of file gl2.h.
GL_STENCIL_BACK_PASS_DEPTH_PASS
#define GL_STENCIL_BACK_PASS_DEPTH_PASS 0x8803
Definition at line 216 of file gl2.h.
GL_STENCIL_BACK_REF
#define GL_STENCIL_BACK_REF 0x8CA3
Definition at line 217 of file gl2.h.
GL_STENCIL_BACK_VALUE_MASK
#define GL_STENCIL_BACK_VALUE_MASK 0x8CA4
Definition at line 218 of file gl2.h.
GL_STENCIL_BACK_WRITEMASK
#define GL_STENCIL_BACK_WRITEMASK 0x8CA5
Definition at line 219 of file gl2.h.
GL_STENCIL_BITS
#define GL_STENCIL_BITS 0x0D57
Definition at line 235 of file gl2.h.
GL_STENCIL_BUFFER_BIT
#define GL_STENCIL_BUFFER_BIT 0x00000400
Definition at line 74 of file gl2.h.
GL_STENCIL_CLEAR_VALUE
#define GL_STENCIL_CLEAR_VALUE 0x0B91
Definition at line 205 of file gl2.h.
GL_STENCIL_FAIL
#define GL_STENCIL_FAIL 0x0B94
Definition at line 207 of file gl2.h.
GL_STENCIL_FUNC
#define GL_STENCIL_FUNC 0x0B92
Definition at line 206 of file gl2.h.
GL_STENCIL_INDEX
#define GL_STENCIL_INDEX 0x1901
Definition at line 462 of file gl2.h.
GL_STENCIL_INDEX8
#define GL_STENCIL_INDEX8 0x8D48
Definition at line 463 of file gl2.h.
GL_STENCIL_PASS_DEPTH_FAIL
#define GL_STENCIL_PASS_DEPTH_FAIL 0x0B95
Definition at line 208 of file gl2.h.
GL_STENCIL_PASS_DEPTH_PASS
#define GL_STENCIL_PASS_DEPTH_PASS 0x0B96
Definition at line 209 of file gl2.h.
GL_STENCIL_REF
#define GL_STENCIL_REF 0x0B97
Definition at line 210 of file gl2.h.
GL_STENCIL_TEST
#define GL_STENCIL_TEST 0x0B90
Definition at line 177 of file gl2.h.
GL_STENCIL_VALUE_MASK
#define GL_STENCIL_VALUE_MASK 0x0B93
Definition at line 211 of file gl2.h.
GL_STENCIL_WRITEMASK
#define GL_STENCIL_WRITEMASK 0x0B98
Definition at line 212 of file gl2.h.
GL_STREAM_DRAW
#define GL_STREAM_DRAW 0x88E0
Definition at line 148 of file gl2.h.
GL_SUBPIXEL_BITS
#define GL_SUBPIXEL_BITS 0x0D50
Definition at line 229 of file gl2.h.
GL_TEXTURE
#define GL_TEXTURE 0x1702
Definition at line 354 of file gl2.h.
GL_TEXTURE0
#define GL_TEXTURE0 0x84C0
Definition at line 367 of file gl2.h.
GL_TEXTURE1
#define GL_TEXTURE1 0x84C1
Definition at line 368 of file gl2.h.
GL_TEXTURE10
#define GL_TEXTURE10 0x84CA
Definition at line 377 of file gl2.h.
GL_TEXTURE11
#define GL_TEXTURE11 0x84CB
Definition at line 378 of file gl2.h.
GL_TEXTURE12
#define GL_TEXTURE12 0x84CC
Definition at line 379 of file gl2.h.
GL_TEXTURE13
#define GL_TEXTURE13 0x84CD
Definition at line 380 of file gl2.h.
GL_TEXTURE14
#define GL_TEXTURE14 0x84CE
Definition at line 381 of file gl2.h.
GL_TEXTURE15
#define GL_TEXTURE15 0x84CF
Definition at line 382 of file gl2.h.
GL_TEXTURE16
#define GL_TEXTURE16 0x84D0
Definition at line 383 of file gl2.h.
GL_TEXTURE17
#define GL_TEXTURE17 0x84D1
Definition at line 384 of file gl2.h.
GL_TEXTURE18
#define GL_TEXTURE18 0x84D2
Definition at line 385 of file gl2.h.
GL_TEXTURE19
#define GL_TEXTURE19 0x84D3
Definition at line 386 of file gl2.h.
GL_TEXTURE2
#define GL_TEXTURE2 0x84C2
Definition at line 369 of file gl2.h.
GL_TEXTURE20
#define GL_TEXTURE20 0x84D4
Definition at line 387 of file gl2.h.
GL_TEXTURE21
#define GL_TEXTURE21 0x84D5
Definition at line 388 of file gl2.h.
GL_TEXTURE22
#define GL_TEXTURE22 0x84D6
Definition at line 389 of file gl2.h.
GL_TEXTURE23
#define GL_TEXTURE23 0x84D7
Definition at line 390 of file gl2.h.
GL_TEXTURE24
#define GL_TEXTURE24 0x84D8
Definition at line 391 of file gl2.h.
GL_TEXTURE25
#define GL_TEXTURE25 0x84D9
Definition at line 392 of file gl2.h.
GL_TEXTURE26
#define GL_TEXTURE26 0x84DA
Definition at line 393 of file gl2.h.
GL_TEXTURE27
#define GL_TEXTURE27 0x84DB
Definition at line 394 of file gl2.h.
GL_TEXTURE28
#define GL_TEXTURE28 0x84DC
Definition at line 395 of file gl2.h.
GL_TEXTURE29
#define GL_TEXTURE29 0x84DD
Definition at line 396 of file gl2.h.
GL_TEXTURE3
#define GL_TEXTURE3 0x84C3
Definition at line 370 of file gl2.h.
GL_TEXTURE30
#define GL_TEXTURE30 0x84DE
Definition at line 397 of file gl2.h.
GL_TEXTURE31
#define GL_TEXTURE31 0x84DF
Definition at line 398 of file gl2.h.
GL_TEXTURE4
#define GL_TEXTURE4 0x84C4
Definition at line 371 of file gl2.h.
GL_TEXTURE5
#define GL_TEXTURE5 0x84C5
Definition at line 372 of file gl2.h.
GL_TEXTURE6
#define GL_TEXTURE6 0x84C6
Definition at line 373 of file gl2.h.
GL_TEXTURE7
#define GL_TEXTURE7 0x84C7
Definition at line 374 of file gl2.h.
GL_TEXTURE8
#define GL_TEXTURE8 0x84C8
Definition at line 375 of file gl2.h.
GL_TEXTURE9
#define GL_TEXTURE9 0x84C9
Definition at line 376 of file gl2.h.
GL_TEXTURE_2D
#define GL_TEXTURE_2D 0x0DE1
Definition at line 173 of file gl2.h.
GL_TEXTURE_BINDING_2D
#define GL_TEXTURE_BINDING_2D 0x8069
Definition at line 239 of file gl2.h.
GL_TEXTURE_BINDING_CUBE_MAP
#define GL_TEXTURE_BINDING_CUBE_MAP 0x8514
Definition at line 357 of file gl2.h.
GL_TEXTURE_CUBE_MAP
#define GL_TEXTURE_CUBE_MAP 0x8513
Definition at line 356 of file gl2.h.
GL_TEXTURE_CUBE_MAP_NEGATIVE_X
#define GL_TEXTURE_CUBE_MAP_NEGATIVE_X 0x8516
Definition at line 359 of file gl2.h.
GL_TEXTURE_CUBE_MAP_NEGATIVE_Y
#define GL_TEXTURE_CUBE_MAP_NEGATIVE_Y 0x8518
Definition at line 361 of file gl2.h.
GL_TEXTURE_CUBE_MAP_NEGATIVE_Z
#define GL_TEXTURE_CUBE_MAP_NEGATIVE_Z 0x851A
Definition at line 363 of file gl2.h.
GL_TEXTURE_CUBE_MAP_POSITIVE_X
#define GL_TEXTURE_CUBE_MAP_POSITIVE_X 0x8515
Definition at line 358 of file gl2.h.
GL_TEXTURE_CUBE_MAP_POSITIVE_Y
#define GL_TEXTURE_CUBE_MAP_POSITIVE_Y 0x8517
Definition at line 360 of file gl2.h.
GL_TEXTURE_CUBE_MAP_POSITIVE_Z
#define GL_TEXTURE_CUBE_MAP_POSITIVE_Z 0x8519
Definition at line 362 of file gl2.h.
GL_TEXTURE_MAG_FILTER
#define GL_TEXTURE_MAG_FILTER 0x2800
Definition at line 347 of file gl2.h.
GL_TEXTURE_MIN_FILTER
#define GL_TEXTURE_MIN_FILTER 0x2801
Definition at line 348 of file gl2.h.
GL_TEXTURE_WRAP_S
#define GL_TEXTURE_WRAP_S 0x2802
Definition at line 349 of file gl2.h.
GL_TEXTURE_WRAP_T
#define GL_TEXTURE_WRAP_T 0x2803
Definition at line 350 of file gl2.h.
GL_TRIANGLE_FAN
#define GL_TRIANGLE_FAN 0x0006
Definition at line 88 of file gl2.h.
GL_TRIANGLE_STRIP
#define GL_TRIANGLE_STRIP 0x0005
Definition at line 87 of file gl2.h.
GL_TRIANGLES
#define GL_TRIANGLES 0x0004
Definition at line 86 of file gl2.h.
GL_TRUE
#define GL_TRUE (GLboolean)1
Definition at line 79 of file gl2.h.
GL_UNPACK_ALIGNMENT
#define GL_UNPACK_ALIGNMENT 0x0CF5
Definition at line 225 of file gl2.h.
GL_UNSIGNED_BYTE
#define GL_UNSIGNED_BYTE 0x1401
Definition at line 264 of file gl2.h.
GL_UNSIGNED_INT
#define GL_UNSIGNED_INT 0x1405
Definition at line 268 of file gl2.h.
GL_UNSIGNED_SHORT
#define GL_UNSIGNED_SHORT 0x1403
Definition at line 266 of file gl2.h.
GL_UNSIGNED_SHORT_4_4_4_4
#define GL_UNSIGNED_SHORT_4_4_4_4 0x8033
Definition at line 282 of file gl2.h.
GL_UNSIGNED_SHORT_5_5_5_1
#define GL_UNSIGNED_SHORT_5_5_5_1 0x8034
Definition at line 283 of file gl2.h.
GL_UNSIGNED_SHORT_5_6_5
#define GL_UNSIGNED_SHORT_5_6_5 0x8363
Definition at line 284 of file gl2.h.
GL_VALIDATE_STATUS
#define GL_VALIDATE_STATUS 0x8B83
Definition at line 299 of file gl2.h.
GL_VENDOR
#define GL_VENDOR 0x1F00
Definition at line 329 of file gl2.h.
GL_VERSION
#define GL_VERSION 0x1F02
Definition at line 331 of file gl2.h.
GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING
#define GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING 0x889F
Definition at line 430 of file gl2.h.
GL_VERTEX_ATTRIB_ARRAY_ENABLED
#define GL_VERTEX_ATTRIB_ARRAY_ENABLED 0x8622
Definition at line 424 of file gl2.h.
GL_VERTEX_ATTRIB_ARRAY_NORMALIZED
#define GL_VERTEX_ATTRIB_ARRAY_NORMALIZED 0x886A
Definition at line 428 of file gl2.h.
GL_VERTEX_ATTRIB_ARRAY_POINTER
#define GL_VERTEX_ATTRIB_ARRAY_POINTER 0x8645
Definition at line 429 of file gl2.h.
Referenced by glGetVertexAttribPointerv().
GL_VERTEX_ATTRIB_ARRAY_SIZE
#define GL_VERTEX_ATTRIB_ARRAY_SIZE 0x8623
Definition at line 425 of file gl2.h.
GL_VERTEX_ATTRIB_ARRAY_STRIDE
#define GL_VERTEX_ATTRIB_ARRAY_STRIDE 0x8624
Definition at line 426 of file gl2.h.
GL_VERTEX_ATTRIB_ARRAY_TYPE
#define GL_VERTEX_ATTRIB_ARRAY_TYPE 0x8625
Definition at line 427 of file gl2.h.
GL_VERTEX_SHADER
#define GL_VERTEX_SHADER 0x8B31
Definition at line 288 of file gl2.h.
Referenced by raspitexutil_build_shader_program().
GL_VIEWPORT
#define GL_VIEWPORT 0x0BA2
Definition at line 220 of file gl2.h.
GL_ZERO
#define GL_ZERO 0
Definition at line 101 of file gl2.h.
Typedef Documentation
GLbitfield
typedef unsigned int GLbitfield
Definition at line 52 of file gl2.h.
GLboolean
typedef unsigned char GLboolean
Definition at line 51 of file gl2.h.
GLbyte
typedef khronos_int8_t GLbyte
Definition at line 53 of file gl2.h.
GLchar
typedef char GLchar
Definition at line 49 of file gl2.h.
GLclampf
typedef khronos_float_t GLclampf
Definition at line 61 of file gl2.h.
GLenum
typedef unsigned int GLenum
Definition at line 50 of file gl2.h.
GLfixed
typedef khronos_int32_t GLfixed
Definition at line 62 of file gl2.h.
GLfloat
typedef khronos_float_t GLfloat
Definition at line 60 of file gl2.h.
GLint
typedef int GLint
Definition at line 55 of file gl2.h.
GLintptr
typedef khronos_intptr_t GLintptr
Definition at line 65 of file gl2.h.
GLshort
typedef short GLshort
Definition at line 54 of file gl2.h.
GLsizei
typedef int GLsizei
Definition at line 56 of file gl2.h.
GLsizeiptr
typedef khronos_ssize_t GLsizeiptr
Definition at line 66 of file gl2.h.
GLubyte
typedef khronos_uint8_t GLubyte
Definition at line 57 of file gl2.h.
GLuint
typedef unsigned int GLuint
Definition at line 59 of file gl2.h.
GLushort
typedef unsigned short GLushort
Definition at line 58 of file gl2.h.
GLvoid
typedef void GLvoid
Definition at line 48 of file gl2.h.
Function Documentation
glActiveTexture()
GL_APICALL void GL_APIENTRY glActiveTexture (GLenum texture)
Definition at line 199 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       if (texture >= GL_TEXTURE0 && texture < GL_TEXTURE0 + GL11_CONFIG_MAX_TEXTURE_UNITS)
          state->active_texture.server = texture;
       RPC_CALL1(glActiveTexture_impl,
                 thread,
                 GLACTIVETEXTURE_ID,
                 RPC_ENUM(texture));
    }
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL1(glActiveTexture_impl,
                 thread,
                 GLACTIVETEXTURE_ID,
                 RPC_ENUM(texture));
    }
 }
glAttachShader()
GL_APICALL void GL_APIENTRY glAttachShader (GLuint program, GLuint shader)
Definition at line 246 of file glxx_client.c.
Referenced by raspitexutil_build_shader_program().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL2(glAttachShader_impl_20,
                 thread,
                 GLATTACHSHADER_ID_20,
                 RPC_UINT(program),
                 RPC_UINT(shader));
    }
 }
glBindAttribLocation()
GL_APICALL void GL_APIENTRY glBindAttribLocation (GLuint program, GLuint index, const GLchar * name)
Definition at line 258 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL3_IN_BULK(glBindAttribLocation_impl_20,
                         thread,
                         GLBINDATTRIBLOCATION_ID_20,
                         RPC_UINT(program),
                         RPC_UINT(index),
                         name,
                         strlen(name) + 1);
    }
 }
glBindBuffer()
GL_APICALL void GL_APIENTRY glBindBuffer (GLenum target, GLuint buffer)
Definition at line 272 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if(IS_OPENGLES_11_OR_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       vcos_assert(state != NULL);
       switch (target) {
       case GL_ARRAY_BUFFER:
          state->bound_buffer.array = buffer;
          break;
       case GL_ELEMENT_ARRAY_BUFFER:
          state->bound_buffer.element_array = buffer;
          break;
       default:
          // do nothing, server will signal error
          break;
       }
       RPC_CALL2(glBindBuffer_impl,
                 thread,
                 GLBINDBUFFER_ID,
                 RPC_ENUM(target),
                 RPC_UINT(buffer));
    }
 }
glBindFramebuffer()
GL_APICALL void GL_APIENTRY glBindFramebuffer (GLenum target, GLuint framebuffer)
Definition at line 5300 of file glxx_client.c.
References glxx_client_BindFramebuffer().
 {
    glxx_client_BindFramebuffer(target, framebuffer);
 }
glBindRenderbuffer()
GL_APICALL void GL_APIENTRY glBindRenderbuffer (GLenum target, GLuint renderbuffer)
Definition at line 5158 of file glxx_client.c.
References glxx_client_BindRenderbuffer().
 {
    glxx_client_BindRenderbuffer(target, renderbuffer);
 }
glBindTexture()
GL_APICALL void GL_APIENTRY glBindTexture (GLenum target, GLuint texture)
Definition at line 301 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       vcos_log_trace("[%s] target 0x%x texture %d", __FUNCTION__, target, texture);
       RPC_CALL2(glBindTexture_impl,
                 thread,
                 GLBINDTEXTURE_ID,
                 RPC_ENUM(target),
                 RPC_UINT(texture));
    }
 }
glBlendColor()
GL_APICALL void GL_APIENTRY glBlendColor (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
Definition at line 314 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL4(glBlendColor_impl_20,
                 thread,
                 GLBLENDCOLOR_ID_20,
                 RPC_FLOAT(red),
                 RPC_FLOAT(green),
                 RPC_FLOAT(blue),
                 RPC_FLOAT(alpha));
    }
 }
glBlendEquation()
GL_APICALL void GL_APIENTRY glBlendEquation (GLenum mode)
Definition at line 328 of file glxx_client.c.
References glBlendEquationSeparate().
 {
    glBlendEquationSeparate(mode, mode);
 }
glBlendEquationSeparate()
GL_APICALL void GL_APIENTRY glBlendEquationSeparate (GLenum modeRGB, GLenum modeAlpha)
Definition at line 333 of file glxx_client.c.
Referenced by glBlendEquation().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL2(glBlendEquationSeparate_impl_20,
                 thread,
                 GLBLENDEQUATIONSEPARATE_ID_20,
                 RPC_ENUM(modeRGB),
                 RPC_ENUM(modeAlpha));
    }
 }
glBlendFunc()
GL_APICALL void GL_APIENTRY glBlendFunc (GLenum sfactor, GLenum dfactor)
Definition at line 355 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) set_blend_func(thread, sfactor, dfactor, sfactor, dfactor);
 }
glBlendFuncSeparate()
GL_APICALL void GL_APIENTRY glBlendFuncSeparate (GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha)
Definition at line 361 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) set_blend_func(thread, srcRGB, dstRGB, srcAlpha, dstAlpha);
 }
glBufferData()
GL_APICALL void GL_APIENTRY glBufferData (GLenum target, GLsizeiptr size, const GLvoid * data, GLenum usage)
Definition at line 367 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       GLXX_BUFFER_INFO_T buffer;
       glxx_buffer_info_get(state, target, &buffer);
       if(buffer.id != ~0 && buffer.mapped_pointer != 0)
       {
          /* buffer is mapped */
          set_error(state, GL_INVALID_OPERATION);
       }
       else
       {
          if( ((target == GL_ARRAY_BUFFER && state->bound_buffer.array != 0) ||
               (target == GL_ELEMENT_ARRAY_BUFFER && state->bound_buffer.element_array != 0)) &&
              (usage ==  GL_STATIC_DRAW || usage == GL_DYNAMIC_DRAW || (IS_OPENGLES_20(thread) && usage == GL_STREAM_DRAW)) &&
              size >=0
            )
          {
             /* server call should succeed in setting buffer size unless out of memory */
             /* cache size so we can use it in mapBuffer without a round trip */
             buffer.cached_size = size;
             glxx_buffer_info_set(state, target, &buffer);
          }
          else
          {
             buffer.cached_size = 0;
             glxx_buffer_info_set(state, target, &buffer);
          }
          RPC_CALL4_IN_BULK(glBufferData_impl,
                            thread,
                            GLBUFFERDATA_ID,
                            RPC_ENUM(target),
                            RPC_SIZEIPTR(size),
                            RPC_ENUM(usage),
                            NULL,
                            0);
          if (data) {
             int offset = 0;
             while (size > 0) {
                int32_t batch = _min(KHDISPATCH_WORKSPACE_SIZE, (int32_t) size);
                RPC_CALL4_IN_BULK(glBufferSubData_impl,
                                  thread,
                                  GLBUFFERSUBDATA_ID,
                                  RPC_ENUM(target),
                                  RPC_INTPTR(offset),
                                  RPC_SIZEIPTR(batch),
                                  (char *)data + offset,
                                  (size_t) batch);
                offset += batch;
                size -= batch;
             }
          }
       }
    }
 }
glBufferSubData()
GL_APICALL void GL_APIENTRY glBufferSubData (GLenum target, GLintptr offset, GLsizeiptr size, const GLvoid * data)
Definition at line 433 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       GLXX_BUFFER_INFO_T buffer;
       glxx_buffer_info_get(state, target, &buffer);
       if(buffer.id != ~0 && buffer.mapped_pointer != 0)
       {
          /* buffer is mapped */
          set_error(state, GL_INVALID_OPERATION);
       }
       else
       {
          if (data) {
             int offset = 0;
             while (size > 0) {
                int32_t batch = _min(KHDISPATCH_WORKSPACE_SIZE, (int32_t)size);
                RPC_CALL4_IN_BULK(glBufferSubData_impl,
                                  thread,
                                  GLBUFFERSUBDATA_ID,
                                  RPC_ENUM(target),
                                  RPC_INTPTR(base+offset),
                                  RPC_SIZEIPTR(batch),
                                  (char *)data + offset,
                                  (size_t) batch);
                offset += batch;
                size -= batch;
             }
          }
       }
    }
 }
glCheckFramebufferStatus()
GL_APICALL GLenum GL_APIENTRY glCheckFramebufferStatus (GLenum target)
Definition at line 5373 of file glxx_client.c.
References glxx_client_CheckFramebufferStatus().
 {
    return glxx_client_CheckFramebufferStatus(target);
 }
glClear()
GL_APICALL void GL_APIENTRY glClear (GLbitfield mask)
Definition at line 471 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       //TODO: pixmap behaviour can be better optimized to handle clears
       if (state->render_callback)
          state->render_callback();
       RPC_CALL1(glClear_impl,
                 thread,
                 GLCLEAR_ID,
                 RPC_BITFIELD(mask));
    }
 }
glClearColor()
GL_APICALL void GL_APIENTRY glClearColor (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
Definition at line 488 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL4(glClearColor_impl,
                 thread,
                 GLCLEARCOLOR_ID,
                 RPC_FLOAT(red),
                 RPC_FLOAT(green),
                 RPC_FLOAT(blue),
                 RPC_FLOAT(alpha));
    }
 }
glClearDepthf()
GL_APICALL void GL_APIENTRY glClearDepthf (GLclampf depth)
Definition at line 516 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL1(glClearDepthf_impl,
                 thread,
                 GLCLEARDEPTHF_ID,
                 RPC_FLOAT(depth));
    }
 }
glClearStencil()
GL_APICALL void GL_APIENTRY glClearStencil (GLint s)
Definition at line 538 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL1(glClearStencil_impl,
                 thread,
                 GLCLEARSTENCIL_ID,
                 RPC_INT(s));
    }
 }
glColorMask()
GL_APICALL void GL_APIENTRY glColorMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
Definition at line 623 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL4(glColorMask_impl,
                 thread,
                 GLCOLORMASK_ID,
                 RPC_BOOLEAN(red),
                 RPC_BOOLEAN(green),
                 RPC_BOOLEAN(blue),
                 RPC_BOOLEAN(alpha));
    }
 }
glCompileShader()
GL_APICALL void GL_APIENTRY glCompileShader (GLuint shader)
Definition at line 4901 of file glxx_client.c.
Referenced by raspitexutil_build_shader_program().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL1(glCompileShader_impl_20,
                 thread,
                 GLCOMPILESHADER_ID_20,
                 RPC_UINT(shader));
    }
 }
glCompressedTexImage2D()
GL_APICALL void GL_APIENTRY glCompressedTexImage2D (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const GLvoid * data)
Definition at line 698 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    GLboolean res;
    if (IS_OPENGLES_11_OR_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       switch (internalformat)
       {
          case GL_ETC1_RGB8_OES:
          {
             uint32_t pitch = 2 * ((width + 3) / 4);
             uint32_t lines = pitch ? (uint32_t)(KHDISPATCH_WORKSPACE_SIZE / pitch) : (uint32_t)height;
             res = RPC_BOOLEAN_RES(RPC_CALL8_IN_BULK_RES(glCompressedTexImage2D_impl,
                               thread,
                               GLCOMPRESSEDTEXIMAGE2D_ID,
                               RPC_ENUM  (target),
                               RPC_INT   (level),
                               RPC_ENUM  (internalformat),
                               RPC_SIZEI (width),
                               RPC_SIZEI (height),
                               RPC_INT   (border),
                               RPC_SIZEI (imageSize),
                               NULL,
                               0));
             if (res && data && lines && width && height) {
                int offset = 0;
                while (height > 0) {
                   int32_t batch = (_min(lines, (int32_t)height) + 3) & ~3;
                   RPC_CALL9_IN_BULK(glCompressedTexSubImage2D_impl,
                                     thread,
                                     GLCOMPRESSEDTEXSUBIMAGE2D_ID,
                                     RPC_ENUM(target),
                                     RPC_INT(level),
                                     RPC_INT(0),
                                     RPC_INT(offset),
                                     RPC_SIZEI(width),
                                     RPC_SIZEI(batch),
                                     RPC_ENUM(internalformat),
                                     batch * pitch,
                                     (char *)data + offset * pitch,
                                     batch * pitch);
                   offset += batch;
                   height -= batch;
                }
             }
             break;
          }
          case GL_PALETTE4_RGB8_OES:
          case GL_PALETTE4_RGBA8_OES:
          case GL_PALETTE4_R5_G6_B5_OES:
          case GL_PALETTE4_RGBA4_OES:
          case GL_PALETTE4_RGB5_A1_OES:
          case GL_PALETTE8_RGB8_OES:
          case GL_PALETTE8_RGBA8_OES:
          case GL_PALETTE8_R5_G6_B5_OES:
          case GL_PALETTE8_RGBA4_OES:
          case GL_PALETTE8_RGB5_A1_OES:
          {
             int palette_size = get_palette_size(internalformat);
             level = -level;
             res = RPC_BOOLEAN_RES(RPC_CALL8_IN_BULK_RES(glCompressedTexImage2D_impl,
                               thread,
                               GLCOMPRESSEDTEXIMAGE2D_ID,
                               RPC_ENUM  (target),
                               RPC_INT   (level),
                               RPC_ENUM  (internalformat),
                               RPC_SIZEI (width),
                               RPC_SIZEI (height),
                               RPC_INT   (border),
                               RPC_SIZEI (imageSize),
                               data,
                               palette_size));
             if (res && data && width && height) {
                int offset = palette_size;
                while (offset < imageSize) {
                   int32_t batch = _min(KHDISPATCH_WORKSPACE_SIZE, imageSize - offset);
                   RPC_CALL9_IN_BULK(glCompressedTexSubImage2D_impl,
                                     thread,
                                     GLCOMPRESSEDTEXSUBIMAGE2D_ID,
                                     RPC_ENUM(target),
                                     RPC_INT(level),
                                     RPC_INT(offset - palette_size),
                                     RPC_INT(0),
                                     RPC_SIZEI(width),
                                     RPC_SIZEI(height),
                                     RPC_ENUM(internalformat),
                                     batch,
                                     (char *)data + offset,
                                     batch);
                   offset += batch;
                }
             }
             break;
          }
          default:
             set_error(state, GL_INVALID_ENUM );
             break;
       }
    }
 }
glCompressedTexSubImage2D()
GL_APICALL void GL_APIENTRY glCompressedTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const GLvoid * data)
Definition at line 808 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    UNUSED(target);
    UNUSED(level);
    UNUSED(xoffset);
    UNUSED(yoffset);
    UNUSED(width);
    UNUSED(height);
    UNUSED(imageSize);
    UNUSED(data);
    if (IS_OPENGLES_11_OR_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       switch (format)
       {
       case GL_ETC1_RGB8_OES:
          // Cannot specify subimages of ETC1 textures
          set_error(state, GL_INVALID_OPERATION);
          break;
       case GL_PALETTE4_RGB8_OES:
       case GL_PALETTE4_RGBA8_OES:
       case GL_PALETTE4_R5_G6_B5_OES:
       case GL_PALETTE4_RGBA4_OES:
       case GL_PALETTE4_RGB5_A1_OES:
       case GL_PALETTE8_RGB8_OES:
       case GL_PALETTE8_RGBA8_OES:
       case GL_PALETTE8_R5_G6_B5_OES:
       case GL_PALETTE8_RGBA4_OES:
       case GL_PALETTE8_RGB5_A1_OES:
          // Cannot specify subimages of paletted textures
          set_error(state, GL_INVALID_OPERATION);
          break;
       default:
          // Some format we don't recognise
          set_error(state, GL_INVALID_VALUE);
          break;
       }
    }
 }
glCopyTexImage2D()
GL_APICALL void GL_APIENTRY glCopyTexImage2D (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border)
Definition at line 850 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL8(glCopyTexImage2D_impl,
                 thread,
                 GLCOPYTEXIMAGE2D_ID,
                 RPC_ENUM(target),
                 RPC_INT(level),
                 RPC_ENUM(internalformat),
                 RPC_INT(x),
                 RPC_INT(y),
                 RPC_SIZEI(width),
                 RPC_SIZEI(height),
                 RPC_INT(border));
    }
 }
glCopyTexSubImage2D()
GL_APICALL void GL_APIENTRY glCopyTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height)
Definition at line 868 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL8(glCopyTexSubImage2D_impl,
                 thread,
                 GLCOPYTEXSUBIMAGE2D_ID,
                 RPC_ENUM(target),
                 RPC_INT(level),
                 RPC_INT(xoffset),
                 RPC_INT(yoffset),
                 RPC_INT(x),
                 RPC_INT(y),
                 RPC_SIZEI(width),
                 RPC_SIZEI(height));
    }
 }
glCreateProgram()
GL_APICALL GLuint GL_APIENTRY glCreateProgram (void)
Definition at line 886 of file glxx_client.c.
Referenced by raspitexutil_build_shader_program().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       return RPC_UINT_RES(RPC_CALL0_RES(glCreateProgram_impl_20,
                                         thread,
                                         GLCREATEPROGRAM_ID_20));
    }
    return 0;
 }
glCreateShader()
GL_APICALL GLuint GL_APIENTRY glCreateShader (GLenum type)
Definition at line 898 of file glxx_client.c.
Referenced by raspitexutil_build_shader_program().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       return RPC_UINT_RES(RPC_CALL1_RES(glCreateShader_impl_20,
                                         thread,
                                         GLCREATESHADER_ID_20,
                                         RPC_ENUM(type)));
    }
    return 0;
 }
glCullFace()
GL_APICALL void GL_APIENTRY glCullFace (GLenum mode)
Definition at line 911 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL1(glCullFace_impl,
                 thread,
                 GLCULLFACE_ID,
                 RPC_ENUM(mode));
    }
 }
glDeleteBuffers()
GL_APICALL void GL_APIENTRY glDeleteBuffers (GLsizei n, const GLuint * buffers)
Definition at line 922 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    int offset = 0;
    if (IS_OPENGLES_11_OR_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       int i, j;
       for (i = 0; i < n; i++) {
          GLuint buffer = buffers[i];
          if (state->bound_buffer.array == buffer)
             state->bound_buffer.array = 0;
          if (state->bound_buffer.element_array == buffer)
             state->bound_buffer.element_array = 0;
          for (j = 0; j < GLXX_CONFIG_MAX_VERTEX_ATTRIBS; j++)
             if (state->attrib[j].buffer == buffer)
                state->attrib[j].buffer = 0;
          buffer_info_delete(state, buffer);
       }
    }
    if (IS_OPENGLES_11_OR_20(thread)) {
       do {
          int32_t items = (int32_t)( KHDISPATCH_WORKSPACE_SIZE / sizeof(GLuint) );
          int32_t batch = _min(items, (int32_t) n);
          RPC_CALL2_IN_BULK(glDeleteBuffers_impl,
                            thread,
                            GLDELETEBUFFERS_ID,
                            RPC_SIZEI(batch),
                            buffers + offset,
                            batch > 0 ? batch * sizeof(GLuint) : 0);
          offset += batch;
          n -= batch;
       } while (n > 0);
    }
 }
glDeleteFramebuffers()
GL_APICALL void GL_APIENTRY glDeleteFramebuffers (GLsizei n, const GLuint * framebuffers)
Definition at line 5328 of file glxx_client.c.
References glxx_client_DeleteFramebuffers().
 {
    glxx_client_DeleteFramebuffers(n, framebuffers);
 }
glDeleteProgram()
GL_APICALL void GL_APIENTRY glDeleteProgram (GLuint program)
Definition at line 965 of file glxx_client.c.
Referenced by raspitexutil_build_shader_program().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL1(glDeleteProgram_impl_20,
                 thread,
                 GLDELETEPROGRAM_ID_20,
                 RPC_UINT(program));
    }
 }
glDeleteRenderbuffers()
GL_APICALL void GL_APIENTRY glDeleteRenderbuffers (GLsizei n, const GLuint * renderbuffers)
Definition at line 5187 of file glxx_client.c.
References glxx_client_DeleteRenderbuffers().
 {
    glxx_client_DeleteRenderbuffers(n, renderbuffers);
 }
glDeleteShader()
GL_APICALL void GL_APIENTRY glDeleteShader (GLuint shader)
Definition at line 976 of file glxx_client.c.
Referenced by raspitexutil_build_shader_program().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL1(glDeleteShader_impl_20,
                 thread,
                 GLDELETESHADER_ID_20,
                 RPC_UINT(shader));
    }
 }
glDeleteTextures()
GL_APICALL void GL_APIENTRY glDeleteTextures (GLsizei n, const GLuint * textures)
Definition at line 987 of file glxx_client.c.
Referenced by raspitexutil_gl_term().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    int offset = 0;
    if (IS_OPENGLES_11_OR_20(thread)) {
       do {
          int32_t items = (int32_t)(KHDISPATCH_WORKSPACE_SIZE / sizeof(GLuint));
          int32_t batch = _min(items, (int32_t)n);
          RPC_CALL2_IN_BULK(glDeleteTextures_impl,
                            thread,
                            GLDELETETEXTURES_ID,
                            RPC_SIZEI(batch),
                            textures + offset,
                            batch > 0 ? batch * sizeof(GLuint) : 0);
          offset += batch;
          n -= batch;
       } while (n > 0);
    }
 }
glDepthFunc()
GL_APICALL void GL_APIENTRY glDepthFunc (GLenum func)
Definition at line 1010 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL1(glDepthFunc_impl,
                 thread,
                 GLDEPTHFUNC_ID,
                 RPC_ENUM(func));
    }
 }
glDepthMask()
GL_APICALL void GL_APIENTRY glDepthMask (GLboolean flag)
Definition at line 1021 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL1(glDepthMask_impl,
                 thread,
                 GLDEPTHMASK_ID,
                 RPC_BOOLEAN(flag));
    }
 }
glDepthRangef()
GL_APICALL void GL_APIENTRY glDepthRangef (GLclampf zNear, GLclampf zFar)
Definition at line 1032 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL2(glDepthRangef_impl,
                 thread,
                 GLDEPTHRANGEF_ID,
                 RPC_FLOAT(zNear),
                 RPC_FLOAT(zFar));
    }
 }
glDetachShader()
GL_APICALL void GL_APIENTRY glDetachShader (GLuint program, GLuint shader)
Definition at line 1056 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL2(glDetachShader_impl_20,
                 thread,
                 GLDETACHSHADER_ID_20,
                 RPC_UINT(program),
                 RPC_UINT(shader));
    }
 }
glDisable()
GL_APICALL void GL_APIENTRY glDisable (GLenum cap)
Definition at line 1068 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL1(glDisable_impl,
                thread,
                 GLDISABLE_ID,
                 RPC_ENUM(cap));
    }
 }
glDisableVertexAttribArray()
GL_APICALL void GL_APIENTRY glDisableVertexAttribArray (GLuint index)
Definition at line 1116 of file glxx_client.c.
References GL_FALSE, glintAttribEnable(), and GLXX_API_20.
 {
    glintAttribEnable(GLXX_API_20, index, GL_FALSE);
 }
glDrawArrays()
GL_APICALL void GL_APIENTRY glDrawArrays (GLenum mode, GLint first, GLsizei count)
Definition at line 1336 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       draw_arrays_or_elements(thread, state, mode, count, 0, (void *)first);
    }
 }
glDrawElements()
GL_APICALL void GL_APIENTRY glDrawElements (GLenum mode, GLsizei count, GLenum type, const GLvoid * indices)
Definition at line 1346 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       if (!is_index_type(type)) {
          set_error(state, GL_INVALID_ENUM);
          return;
       }
       if (!is_aligned(type, (size_t)indices)) {
          set_error(state, GL_INVALID_VALUE);
          return;
       }
       draw_arrays_or_elements(thread, state, mode, count, type, indices);
    }
 }
glEnable()
GL_APICALL void GL_APIENTRY glEnable (GLenum cap)
Definition at line 1363 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL1(glEnable_impl,
                 thread,
                 GLENABLE_ID,
                 RPC_ENUM(cap));
    }
 }
glEnableVertexAttribArray()
GL_APICALL void GL_APIENTRY glEnableVertexAttribArray (GLuint index)
Definition at line 1379 of file glxx_client.c.
References GL_TRUE, glintAttribEnable(), and GLXX_API_20.
 {
    glintAttribEnable(GLXX_API_20, index, GL_TRUE);
 }
glFinish()
GL_APICALL void GL_APIENTRY glFinish (void)
Definition at line 1384 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       (void) RPC_UINT_RES(RPC_CALL0_RES(glFinish_impl,
                     thread,
                     GLFINISH_ID));  // Return ignored - read performed to force blocking
       if (state->flush_callback)
          state->flush_callback(true);
    }
 }
glFlush()
GL_APICALL void GL_APIENTRY glFlush (void)
Definition at line 1398 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       RPC_CALL0(glFlush_impl,
                     thread,
                     GLFLUSH_ID);
       if (state->flush_callback)
          state->flush_callback(false);
    }
    //TODO: where exactly should we put RPC_FLUSH? Are there any other functions
    //which need it? (e.g. eglSwapBuffers)
    RPC_FLUSH(thread);
 }
glFramebufferRenderbuffer()
GL_APICALL void GL_APIENTRY glFramebufferRenderbuffer (GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer)
Definition at line 5412 of file glxx_client.c.
References glxx_client_FramebufferRenderbuffer().
 {
    glxx_client_FramebufferRenderbuffer(target, attachment, renderbuffertarget, renderbuffer);
 }
glFramebufferTexture2D()
GL_APICALL void GL_APIENTRY glFramebufferTexture2D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
Definition at line 5393 of file glxx_client.c.
References glxx_client_FramebufferTexture2D().
 {
    glxx_client_FramebufferTexture2D(target, attachment, textarget, texture, level);
 }
glFrontFace()
GL_APICALL void GL_APIENTRY glFrontFace (GLenum mode)
Definition at line 1490 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL1(glFrontFace_impl,
                 thread,
                 GLFRONTFACE_ID,
                 RPC_ENUM(mode));
    }
 }
glGenBuffers()
GL_APICALL void GL_APIENTRY glGenBuffers (GLsizei n, GLuint * buffers)
Definition at line 1533 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       int offset = 0;
       do {
          int32_t items = (int32_t) (KHDISPATCH_WORKSPACE_SIZE / sizeof(GLuint));
          int32_t batch = _min(items, (int32_t) n);
          RPC_CALL2_OUT_BULK(glGenBuffers_impl,
                             thread,
                             GLGENBUFFERS_ID,
                             RPC_SIZEI(batch),
                             (GLuint*)(buffers + offset));
          offset += batch;
          n -= batch;
       } while (n > 0);
    }
 }
glGenerateMipmap()
GL_APICALL void GL_APIENTRY glGenerateMipmap (GLenum target)
Definition at line 5447 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       glxx_client_GenerateMipmap(target);
    }
 }
glGenFramebuffers()
GL_APICALL void GL_APIENTRY glGenFramebuffers (GLsizei n, GLuint * framebuffers)
Definition at line 5355 of file glxx_client.c.
References glxx_client_GenFramebuffers().
 {
    glxx_client_GenFramebuffers(n, framebuffers);
 }
glGenRenderbuffers()
GL_APICALL void GL_APIENTRY glGenRenderbuffers (GLsizei n, GLuint * renderbuffers)
Definition at line 5214 of file glxx_client.c.
References glxx_client_GenRenderbuffers().
 {
    glxx_client_GenRenderbuffers(n, renderbuffers);
 }
glGenTextures()
GL_APICALL void GL_APIENTRY glGenTextures (GLsizei n, GLuint * textures)
Definition at line 1555 of file glxx_client.c.
Referenced by raspitexutil_create_textures().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       int offset = 0;
       do {
          int32_t items = (int32_t) (KHDISPATCH_WORKSPACE_SIZE / sizeof(GLuint));
          int32_t batch = _min(items, (int32_t)n);
          RPC_CALL2_OUT_BULK(glGenTextures_impl,
                             thread,
                             GLGENTEXTURES_ID,
                             RPC_SIZEI(batch),
                             textures + offset);
          offset += batch;
          n -= batch;
       } while (n > 0);
    }
 }
glGetActiveAttrib()
GL_APICALL void GL_APIENTRY glGetActiveAttrib (GLuint program, GLuint index, GLsizei bufsize, GLsizei * length, GLint * size, GLenum * type, GLchar * name)
Definition at line 1577 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
 #ifdef RPC_DIRECT
       RPC_CALL7(glGetActiveAttrib_impl_20, thread, no_id, program, index, bufsize, length, size, type, name);
 #else
       GLuint result[3];
       rpc_begin(thread);
       RPC_CALL4_OUT_CTRL(no_function,
                          thread,
                          GLGETACTIVEATTRIB_ID_20,
                          RPC_UINT(program),
                          RPC_UINT(index),
                          RPC_SIZEI(bufsize),
                          result);
       if (length)
          *length = (GLsizei)result[0];
       if (size)
          *size = (GLint)result[1];
       if (type)
          *type = (GLenum)result[2];
       read_out_bulk(thread, name);
       rpc_end(thread);
 #endif
    }
 }
glGetActiveUniform()
GL_APICALL void GL_APIENTRY glGetActiveUniform (GLuint program, GLuint index, GLsizei bufsize, GLsizei * length, GLint * size, GLenum * type, GLchar * name)
Definition at line 1610 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
 #ifdef RPC_DIRECT
       RPC_CALL7(glGetActiveUniform_impl_20, thread, no_id, program, index, bufsize, length, size, type, name);
 #else
       GLuint result[3];
       rpc_begin(thread);
       RPC_CALL4_OUT_CTRL(no_function,
                          thread,
                          GLGETACTIVEUNIFORM_ID_20,
                          RPC_UINT(program),
                          RPC_UINT(index),
                          RPC_SIZEI(bufsize),
                          result);
       if (length)
          *length = (GLsizei)result[0];
       if (size)
          *size = (GLint)result[1];
       if (type)
          *type = (GLenum)result[2];
       read_out_bulk(thread, name);
       rpc_end(thread);
 #endif
    }
 }
glGetAttachedShaders()
GL_APICALL void GL_APIENTRY glGetAttachedShaders (GLuint program, GLsizei maxcount, GLsizei * count, GLuint * shaders)
Definition at line 1643 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
 #ifdef RPC_DIRECT
    RPC_CALL4(glGetAttachedShaders_impl_20, thread, no_id, program, maxcount, count, shaders);
 #else
    GLuint i;
    GLuint result[3];
    RPC_CALL3_OUT_CTRL(no_function,
                       thread,
                       GLGETATTACHEDSHADERS_ID_20,
                       RPC_UINT(program),
                       RPC_SIZEI(maxcount),
                       result);
    if (count)
       *count = (GLsizei) result[0];
    for (i = 0; i < 2; i++)
       if ((GLuint)maxcount > i && result[0] > i)
          shaders[i] = result[i + 1];
 #endif
    }
 }
glGetAttribLocation()
GL_APICALL int GL_APIENTRY glGetAttribLocation (GLuint program, const GLchar * name)
Definition at line 1671 of file glxx_client.c.
Referenced by raspitexutil_build_shader_program().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       return RPC_INT_RES(RPC_CALL2_IN_BULK_RES(glGetAttribLocation_impl_20,
                                                thread,
                                                GLGETATTRIBLOCATION_ID_20,
                                                RPC_UINT(program),
                                                name,
                                                strlen(name) + 1));
    }
    return 0;
 }
glGetBooleanv()
GL_APICALL void GL_APIENTRY glGetBooleanv (GLenum pname, GLboolean * params)
Definition at line 1970 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       switch (pname) {
       case GL_VERTEX_ARRAY:
       case GL_NORMAL_ARRAY:
       case GL_COLOR_ARRAY:
       case GL_TEXTURE_COORD_ARRAY:
       case GL_POINT_SIZE_ARRAY_OES:
          get_boolean_internal_11(thread, pname, params);
          break;
       case GL_CLIENT_ACTIVE_TEXTURE:
       case GL_VERTEX_ARRAY_SIZE:
       case GL_VERTEX_ARRAY_TYPE:
       case GL_VERTEX_ARRAY_STRIDE:
       case GL_NORMAL_ARRAY_TYPE:
       case GL_NORMAL_ARRAY_STRIDE:
       case GL_COLOR_ARRAY_SIZE:
       case GL_COLOR_ARRAY_TYPE:
       case GL_COLOR_ARRAY_STRIDE:
       case GL_TEXTURE_COORD_ARRAY_SIZE:
       case GL_TEXTURE_COORD_ARRAY_TYPE:
       case GL_TEXTURE_COORD_ARRAY_STRIDE:
       case GL_POINT_SIZE_ARRAY_TYPE_OES:
       case GL_POINT_SIZE_ARRAY_STRIDE_OES:
       case GL_ARRAY_BUFFER_BINDING:
       case GL_ELEMENT_ARRAY_BUFFER_BINDING:
       case GL_VERTEX_ARRAY_BUFFER_BINDING:
       case GL_NORMAL_ARRAY_BUFFER_BINDING:
       case GL_COLOR_ARRAY_BUFFER_BINDING:
       case GL_TEXTURE_COORD_ARRAY_BUFFER_BINDING:
       case GL_POINT_SIZE_ARRAY_BUFFER_BINDING_OES:
       case GL_UNPACK_ALIGNMENT:
       case GL_PACK_ALIGNMENT:
       case GL_IMPLEMENTATION_COLOR_READ_TYPE_OES:
       case GL_IMPLEMENTATION_COLOR_READ_FORMAT_OES:
       {
          GLint temp;
          get_integer_internal_11(thread, pname, &temp);
          params[0] = temp != 0;
          break;
       }
       case GL_CURRENT_TEXTURE_COORDS:
       case GL_CURRENT_COLOR:
       case GL_CURRENT_NORMAL:
       case GL_POINT_SIZE:
       {
          GLfloat temp[4];
          GLuint count = (GLuint) get_float_internal_11(thread, pname, temp);
          GLuint i;
          vcos_assert(count <= 4);
          for (i = 0; i < count; i++)
             params[i] = temp[i] != 0.0f;
          break;
       }
       default:
          RPC_CALL2_OUT_CTRL(glGetBooleanv_impl,
                             thread,
                             GLGETBOOLEANV_ID,
                             RPC_ENUM(pname),
                             params);
          break;
       }
    }
    if (IS_OPENGLES_20(thread)) {
       switch (pname) {
       case GL_UNPACK_ALIGNMENT:
       case GL_PACK_ALIGNMENT:
       {
          GLint temp = 0;
          get_integer_internal_20(thread, pname, &temp);
          params[0] = temp != 0;
          break;
       }
       default:
          RPC_CALL2_OUT_CTRL(glGetBooleanv_impl,
                             thread,
                             GLGETBOOLEANV_ID,
                             RPC_ENUM(pname),
                             params);
          break;
       }
    }
 }
glGetBufferParameteriv()
GL_APICALL void GL_APIENTRY glGetBufferParameteriv (GLenum target, GLenum pname, GLint * params)
Definition at line 2065 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       switch(pname) {
       case GL_BUFFER_ACCESS_OES:
       {
          GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
          if(get_bound_buffer(state, target) != 0)
          {
             params[0] = GL_WRITE_ONLY_OES;
          }
          else
          {
             params[0] = 0;
          }
          break;
       }
       case GL_BUFFER_MAPPED_OES:
       {
          GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
          GLXX_BUFFER_INFO_T buffer;
          glxx_buffer_info_get(state, target, &buffer);
          if(buffer.id != 0 && buffer.mapped_pointer != 0)
          {
             params[0] = GL_TRUE;
          }
          else
          {
             params[0] = GL_FALSE;
          }
          break;
       }
       default:
          RPC_CALL3_OUT_CTRL(glGetBufferParameteriv_impl,
                             thread,
                             GLGETBUFFERPARAMETERIV_ID,
                             RPC_ENUM(target),
                             RPC_ENUM(pname),
                             params);
          if(pname == GL_BUFFER_SIZE)
          {
             GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
             GLXX_BUFFER_INFO_T buffer;
             glxx_buffer_info_get(state, target, &buffer);
             buffer.cached_size = params[0];
             glxx_buffer_info_set(state, target, &buffer);
          }
       }
    }
 }
glGetError()
GL_APICALL GLenum GL_APIENTRY glGetError (void)
Definition at line 2142 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE(); /* Decrements glgeterror_hack variable for every API call made */
    if (IS_OPENGLES_11_OR_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       GLenum result = state->error;
       if ((result == GL_NO_ERROR) && !thread->async_error_notification) {
          /* Don't query the server if our previous API call was glGetError() */
          if (0 == thread->glgeterror_hack ) {
             result = RPC_ENUM_RES(RPC_CALL0_RES(glGetError_impl,
                                                 thread,
                                                 GLGETERROR_ID));
          }
          if(result != GL_NO_ERROR) {
             vcos_log_warn("glGetError 0x%x", result);
             thread->glgeterror_hack = 0;
          } else {
             thread->glgeterror_hack = 2;
          }
       }
       state->error = GL_NO_ERROR;
       return result;
    }
    return 0;
 }
glGetFloatv()
GL_APICALL void GL_APIENTRY glGetFloatv (GLenum pname, GLfloat * params)
Definition at line 2257 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       switch (pname) {
       case GL_VERTEX_ARRAY:
       case GL_NORMAL_ARRAY:
       case GL_COLOR_ARRAY:
       case GL_TEXTURE_COORD_ARRAY:
       case GL_POINT_SIZE_ARRAY_OES:
       {
          GLboolean temp[4];
          GLuint count = (GLuint) get_boolean_internal_11(thread, pname, temp);
          GLuint i;
          vcos_assert(count <= 4);
          for (i = 0; i < count; i++)
             params[i] = temp[i] ? 1.0f : 0.0f;
          break;
       }
       case GL_CURRENT_TEXTURE_COORDS:
       case GL_CURRENT_COLOR:
       case GL_CURRENT_NORMAL:
       case GL_POINT_SIZE:
          get_float_internal_11(thread, pname, params);
          break;
       case GL_CLIENT_ACTIVE_TEXTURE:
       case GL_VERTEX_ARRAY_SIZE:
       case GL_VERTEX_ARRAY_TYPE:
       case GL_VERTEX_ARRAY_STRIDE:
       case GL_NORMAL_ARRAY_TYPE:
       case GL_NORMAL_ARRAY_STRIDE:
       case GL_COLOR_ARRAY_SIZE:
       case GL_COLOR_ARRAY_TYPE:
       case GL_COLOR_ARRAY_STRIDE:
       case GL_TEXTURE_COORD_ARRAY_SIZE:
       case GL_TEXTURE_COORD_ARRAY_TYPE:
       case GL_TEXTURE_COORD_ARRAY_STRIDE:
       case GL_POINT_SIZE_ARRAY_TYPE_OES:
       case GL_POINT_SIZE_ARRAY_STRIDE_OES:
       case GL_ARRAY_BUFFER_BINDING:
       case GL_ELEMENT_ARRAY_BUFFER_BINDING:
       case GL_VERTEX_ARRAY_BUFFER_BINDING:
       case GL_NORMAL_ARRAY_BUFFER_BINDING:
       case GL_COLOR_ARRAY_BUFFER_BINDING:
       case GL_TEXTURE_COORD_ARRAY_BUFFER_BINDING:
       case GL_POINT_SIZE_ARRAY_BUFFER_BINDING_OES:
       case GL_UNPACK_ALIGNMENT:
       case GL_PACK_ALIGNMENT:
       case GL_IMPLEMENTATION_COLOR_READ_TYPE_OES:
       case GL_IMPLEMENTATION_COLOR_READ_FORMAT_OES:
       {
          GLint temp;
          get_integer_internal_11(thread, pname, &temp);
          params[0] = (GLfloat)temp;
          break;
       }
       default:
          RPC_CALL2_OUT_CTRL(glGetFloatv_impl,
                             thread,
                             GLGETFLOATV_ID,
                             RPC_ENUM(pname),
                             params);
          break;
       }
    }
    else if (IS_OPENGLES_20(thread)) {
       switch (pname) {
       case GL_UNPACK_ALIGNMENT:
       case GL_PACK_ALIGNMENT:
       {
          GLint temp = 0;
          get_integer_internal_20(thread, pname, &temp);
          params[0] = (GLfloat)temp;
          break;
       }
       default:
          RPC_CALL2_OUT_CTRL(glGetFloatv_impl,
                             thread,
                             GLGETFLOATV_ID,
                             RPC_ENUM(pname),
                             params);
          break;
       }
    }
 }
glGetFramebufferAttachmentParameteriv()
GL_APICALL void GL_APIENTRY glGetFramebufferAttachmentParameteriv (GLenum target, GLenum attachment, GLenum pname, GLint * params)
Definition at line 5431 of file glxx_client.c.
References glxx_client_GetFramebufferAttachmentParameteriv().
 {
    glxx_client_GetFramebufferAttachmentParameteriv(target, attachment, pname, params);
 }
glGetIntegerv()
GL_APICALL void GL_APIENTRY glGetIntegerv (GLenum pname, GLint * params)
Definition at line 2351 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       switch (pname) {
       case GL_VERTEX_ARRAY:
       case GL_NORMAL_ARRAY:
       case GL_COLOR_ARRAY:
       case GL_TEXTURE_COORD_ARRAY:
       case GL_POINT_SIZE_ARRAY_OES:
       {
          GLboolean temp[4];
          GLuint count = (GLuint) get_boolean_internal_11(thread, pname, temp);
          GLuint i;
          vcos_assert(count <= 4);
          for (i = 0; i < count; i++)
             params[i] = temp[i] ? 1 : 0;
          break;
       }
       case GL_CURRENT_COLOR:
       case GL_CURRENT_NORMAL:
       {
          GLfloat temp[4];
          GLuint count = (GLuint) get_float_internal_11(thread, pname, temp);
          GLuint i;
          vcos_assert(count <= 4);
          for (i = 0; i < count; i++)
             params[i] = (GLint)floor((4294967295.0f * temp[i] - 1.0f) / 2.0f + 0.5f);
          //TODO: that the above is correct wrt table 2.7 in the GL spec
          break;
       }
       case GL_CURRENT_TEXTURE_COORDS:
       case GL_POINT_SIZE:
       {
          GLfloat temp[4];
          GLuint count = (GLuint) get_float_internal_11(thread, pname, temp);
          GLuint i;
          vcos_assert(count <= 4);
          for (i = 0; i < count; i++)
             params[i] = (GLint) float_to_int(temp[i]);
          break;
       }
       case GL_CLIENT_ACTIVE_TEXTURE:
       case GL_VERTEX_ARRAY_SIZE:
       case GL_VERTEX_ARRAY_TYPE:
       case GL_VERTEX_ARRAY_STRIDE:
       case GL_NORMAL_ARRAY_TYPE:
       case GL_NORMAL_ARRAY_STRIDE:
       case GL_COLOR_ARRAY_SIZE:
       case GL_COLOR_ARRAY_TYPE:
       case GL_COLOR_ARRAY_STRIDE:
       case GL_TEXTURE_COORD_ARRAY_SIZE:
       case GL_TEXTURE_COORD_ARRAY_TYPE:
       case GL_TEXTURE_COORD_ARRAY_STRIDE:
       case GL_POINT_SIZE_ARRAY_TYPE_OES:
       case GL_POINT_SIZE_ARRAY_STRIDE_OES:
       case GL_MATRIX_INDEX_ARRAY_SIZE_OES:
       case GL_MATRIX_INDEX_ARRAY_TYPE_OES:
       case GL_MATRIX_INDEX_ARRAY_STRIDE_OES:
       case GL_WEIGHT_ARRAY_SIZE_OES:
       case GL_WEIGHT_ARRAY_TYPE_OES:
       case GL_WEIGHT_ARRAY_STRIDE_OES:
       case GL_ARRAY_BUFFER_BINDING:
       case GL_ELEMENT_ARRAY_BUFFER_BINDING:
       case GL_VERTEX_ARRAY_BUFFER_BINDING:
       case GL_NORMAL_ARRAY_BUFFER_BINDING:
       case GL_COLOR_ARRAY_BUFFER_BINDING:
       case GL_TEXTURE_COORD_ARRAY_BUFFER_BINDING:
       case GL_POINT_SIZE_ARRAY_BUFFER_BINDING_OES:
       case GL_MATRIX_INDEX_ARRAY_BUFFER_BINDING_OES:
       case GL_WEIGHT_ARRAY_BUFFER_BINDING_OES:
       case GL_UNPACK_ALIGNMENT:
       case GL_PACK_ALIGNMENT:
       case GL_IMPLEMENTATION_COLOR_READ_TYPE_OES:
       case GL_IMPLEMENTATION_COLOR_READ_FORMAT_OES:
          get_integer_internal_11(thread, pname, params);
          break;
       default:
          RPC_CALL2_OUT_CTRL(glGetIntegerv_impl,
                             thread,
                             GLGETINTEGERV_ID,
                             RPC_ENUM(pname),
                             params);
          break;
       }
    }
    else if (IS_OPENGLES_20(thread)) {
       switch (pname) {
       case GL_UNPACK_ALIGNMENT:
       case GL_PACK_ALIGNMENT:
          get_integer_internal_20(thread, pname, params);
          break;
       default:
          RPC_CALL2_OUT_CTRL(glGetIntegerv_impl,
                             thread,
                             GLGETINTEGERV_ID,
                             RPC_ENUM(pname),
                             params);
          break;
       }
    }
 }
glGetProgramInfoLog()
GL_APICALL void GL_APIENTRY glGetProgramInfoLog (GLuint program, GLsizei bufsize, GLsizei * length, GLchar * infolog)
Definition at line 2576 of file glxx_client.c.
Referenced by raspitexutil_build_shader_program().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
 #ifdef RPC_DIRECT
       RPC_CALL4(glGetProgramInfoLog_impl_20, thread, no_id, program, bufsize, length, infolog);
 #else
       GLuint result[1];
       rpc_begin(thread);
       RPC_CALL3_OUT_CTRL(no_function,
                          thread,
                          GLGETPROGRAMINFOLOG_ID_20,
                          RPC_UINT(program),
                          RPC_SIZEI(bufsize),
                          result);
       if (length)
          *length = (GLsizei)result[0];
       read_out_bulk(thread, infolog);
       rpc_end(thread);
 #endif
    }
 }
glGetProgramiv()
GL_APICALL void GL_APIENTRY glGetProgramiv (GLuint program, GLenum pname, GLint * params)
Definition at line 2563 of file glxx_client.c.
Referenced by raspitexutil_build_shader_program().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL3_OUT_CTRL(glGetProgramiv_impl_20,
                          thread,
                          GLGETPROGRAMIV_ID_20,
                          RPC_UINT(program),
                          RPC_ENUM(pname),
                          params);
    }
 }
glGetRenderbufferParameteriv()
GL_APICALL void GL_APIENTRY glGetRenderbufferParameteriv (GLenum target, GLenum pname, GLint * params)
Definition at line 5251 of file glxx_client.c.
References glxx_client_GetRenderbufferParameteriv().
 {
    glxx_client_GetRenderbufferParameteriv(target, pname, params);
 }
glGetShaderInfoLog()
GL_APICALL void GL_APIENTRY glGetShaderInfoLog (GLuint shader, GLsizei bufsize, GLsizei * length, GLchar * infolog)
Definition at line 4925 of file glxx_client.c.
Referenced by raspitexutil_build_shader_program().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
 #ifdef RPC_DIRECT
       RPC_CALL4(glGetShaderInfoLog_impl_20, thread, no_id, shader, bufsize, length, infolog);
 #else
       GLuint result[1];
       rpc_begin(thread);
       RPC_CALL3_OUT_CTRL(no_function,
                          thread,
                          GLGETSHADERINFOLOG_ID_20,
                          RPC_UINT(shader),
                          RPC_SIZEI(bufsize),
                          result);
       if (length)
          *length = (GLsizei)result[0];
       read_out_bulk(thread, infolog);
       rpc_end(thread);
 #endif
    }
 }
glGetShaderiv()
GL_APICALL void GL_APIENTRY glGetShaderiv (GLuint shader, GLenum pname, GLint * params)
Definition at line 4912 of file glxx_client.c.
Referenced by raspitexutil_build_shader_program().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL3_OUT_CTRL(glGetShaderiv_impl_20,
                          thread,
                          GLGETSHADERIV_ID_20,
                          RPC_ENUM(shader),
                          RPC_ENUM(pname),
                          params);
    }
 }
glGetShaderPrecisionFormat()
GL_APICALL void GL_APIENTRY glGetShaderPrecisionFormat (GLenum shadertype, GLenum precisiontype, GLint * range, GLint * precision)
Definition at line 5456 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       GLint result[3];
       RPC_CALL3_OUT_CTRL(glGetShaderPrecisionFormat_impl_20,
                          thread,
                          GLGETSHADERPRECISIONFORMAT_ID_20,
                          RPC_ENUM(shadertype),
                          RPC_ENUM(precisiontype),
                          result);
       if (range) {
          range[0] = result[0];
          range[1] = result[1];
       }
       if (precision)
          *precision = result[2];
    }
 }
glGetShaderSource()
GL_APICALL void GL_APIENTRY glGetShaderSource (GLuint shader, GLsizei bufsize, GLsizei * length, GLchar * source)
Definition at line 4953 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
 #ifdef RPC_DIRECT
       RPC_CALL4(glGetShaderSource_impl_20, thread, no_id, shader, bufsize, length, source);
 #else
       GLuint result[1];
       rpc_begin(thread);
       RPC_CALL3_OUT_CTRL(no_function,
                          thread,
                          GLGETSHADERSOURCE_ID_20,
                          RPC_UINT(shader),
                          RPC_SIZEI(bufsize),
                          result);
       if (length)
          *length = (GLsizei)result[0];
       read_out_bulk(thread, source);
       rpc_end(thread);
 #endif
    }
 }
glGetString()
GL_APICALL const GLubyte* GL_APIENTRY glGetString (GLenum name)
Definition at line 2604 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       vcos_assert(state != NULL);
       switch (name) {
       case GL_VENDOR:
 #ifndef NDEBUG
          return (const GLubyte *)"Broadcom DEBUG";
 #else
          return (const GLubyte *)"Broadcom";
 #endif
       case GL_RENDERER:
          return (const GLubyte *)"VideoCore IV HW";
       case GL_VERSION:
          return (const GLubyte *)"OpenGL ES-CM 1.1";
       case GL_EXTENSIONS:
          return (const GLubyte *)"GL_OES_compressed_ETC1_RGB8_texture "
                                  "GL_OES_compressed_paletted_texture "
                                  "GL_OES_texture_npot "  /*TODO is npot right? I can't find it in glext.h */
                                  "GL_OES_EGL_image "
                                  "GL_OES_EGL_image_external "
                                  "GL_EXT_discard_framebuffer "
                                  "GL_OES_query_matrix "
                                  "GL_OES_framebuffer_object "
                                  "GL_OES_rgb8_rgba8 "
                                  "GL_OES_depth24 "
                                  "GL_OES_depth32 "
                                  "GL_OES_stencil8 "
                                  "GL_OES_draw_texture "
                                  "GL_OES_mapbuffer "
 #if GL_EXT_texture_format_BGRA8888
                                  "GL_EXT_texture_format_BGRA8888 "
 #endif
 #if GL_APPLE_rgb_422
                                  "GL_APPLE_rgb_422 "
 #endif
 #if GL_OES_matrix_palette
                                  "GL_OES_matrix_palette "
 #endif
 #ifdef GL_EXT_debug_marker
                                  "GL_EXT_debug_marker "
 #endif
                                  ;
       default:
          set_error(state, GL_INVALID_ENUM);
          return NULL;
       }
    }
    else if (IS_OPENGLES_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       vcos_assert(state != NULL);
       switch (name) {
       case GL_VENDOR:
 #ifndef NDEBUG
          return (const GLubyte *)"Broadcom DEBUG";
 #else
          return (const GLubyte *)"Broadcom";
 #endif
       case GL_RENDERER:
          return (const GLubyte *)"VideoCore IV HW";
       case GL_VERSION:
          return (const GLubyte *)"OpenGL ES 2.0";
       case GL_SHADING_LANGUAGE_VERSION:
          return (const GLubyte *)"OpenGL ES GLSL ES 1.00";
       case GL_EXTENSIONS:
          return (const GLubyte *)"GL_OES_compressed_ETC1_RGB8_texture "
                                  "GL_OES_compressed_paletted_texture "
                                  "GL_OES_texture_npot "
                                  "GL_OES_depth24 "
                                  "GL_OES_vertex_half_float "
                                  "GL_OES_EGL_image "
                                  "GL_OES_EGL_image_external "
                                  "GL_EXT_discard_framebuffer "
                                  "GL_OES_rgb8_rgba8 "
                                  "GL_OES_depth32 "
                                  "GL_OES_mapbuffer "
 #if GL_EXT_texture_format_BGRA8888
                                  "GL_EXT_texture_format_BGRA8888 "
 #endif
 #if GL_APPLE_rgb_422
                                  "GL_APPLE_rgb_422 "
 #endif
 #ifdef GL_EXT_debug_marker
                                  "GL_EXT_debug_marker "
 #endif
                                  ;
       default:
          set_error(state, GL_INVALID_ENUM);
          return NULL;
       }
    }
    return NULL;
 }
glGetTexParameterfv()
GL_APICALL void GL_APIENTRY glGetTexParameterfv (GLenum target, GLenum pname, GLfloat * params)
Definition at line 2757 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL3_OUT_CTRL(glGetTexParameterfv_impl,
                          thread,
                          GLGETTEXPARAMETERFV_ID,
                          RPC_ENUM(target),
                          RPC_ENUM(pname),
                          params);
    }
 }
glGetTexParameteriv()
GL_APICALL void GL_APIENTRY glGetTexParameteriv (GLenum target, GLenum pname, GLint * params)
Definition at line 2744 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL3_OUT_CTRL(glGetTexParameteriv_impl,
                          thread,
                          GLGETTEXPARAMETERIV_ID,
                          RPC_ENUM(target),
                          RPC_ENUM(pname),
                          params);
    }
 }
glGetUniformfv()
GL_APICALL void GL_APIENTRY glGetUniformfv (GLuint program, GLint location, GLfloat * params)
Definition at line 2783 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL3_OUT_CTRL(glGetUniformfv_impl_20,
                          thread,
                          GLGETUNIFORMFV_ID_20,
                          RPC_UINT(program),
                          RPC_INT(location),
                          params);
    }
 }
glGetUniformiv()
GL_APICALL void GL_APIENTRY glGetUniformiv (GLuint program, GLint location, GLint * params)
Definition at line 2796 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL3_OUT_CTRL(glGetUniformiv_impl_20,
                          thread,
                          GLGETUNIFORMIV_ID_20,
                          RPC_UINT(program),
                          RPC_INT(location),
                          params);
    }
 }
glGetUniformLocation()
GL_APICALL int GL_APIENTRY glGetUniformLocation (GLuint program, const GLchar * name)
Definition at line 2809 of file glxx_client.c.
Referenced by raspitexutil_build_shader_program().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       return RPC_INT_RES(RPC_CALL2_IN_BULK_RES(glGetUniformLocation_impl_20,
                                                thread,
                                                GLGETUNIFORMLOCATION_ID_20,
                                                RPC_UINT(program),
                                                name,
                                                strlen(name) + 1));
    }
    return 0;
 }
glGetVertexAttribfv()
GL_APICALL void GL_APIENTRY glGetVertexAttribfv (GLuint index, GLenum pname, GLfloat * params)
Definition at line 2837 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       vcos_assert(state != NULL);
       if (index < GL20_CONFIG_MAX_VERTEX_ATTRIBS)
          switch (pname) {
          case GL_CURRENT_VERTEX_ATTRIB:
             params[0] = state->attrib[index].value[0];
             params[1] = state->attrib[index].value[1];
             params[2] = state->attrib[index].value[2];
             params[3] = state->attrib[index].value[3];
             break;
          //TODO: is this the best way to handle conversions? We duplicate
          //the entire switch statement.
          case GL_VERTEX_ATTRIB_ARRAY_ENABLED:
             params[0] = state->attrib[index].enabled ? 1.0f : 0.0f;
             break;
          case GL_VERTEX_ATTRIB_ARRAY_SIZE:
             params[0] = (GLfloat)state->attrib[index].size;
             break;
          case GL_VERTEX_ATTRIB_ARRAY_STRIDE:
             params[0] = (GLfloat)state->attrib[index].stride;
             break;
          case GL_VERTEX_ATTRIB_ARRAY_TYPE:
             params[0] = (GLfloat)state->attrib[index].type;
             break;
          case GL_VERTEX_ATTRIB_ARRAY_NORMALIZED:
             params[0] = state->attrib[index].normalized ? 1.0f : 0.0f;
             break;
          case GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING:
             params[0] = (GLfloat)state->attrib[index].buffer;
             break;
          default:
             set_error(state, GL_INVALID_ENUM);
             break;
          }
       else
          set_error(state, GL_INVALID_VALUE);
    }
 }
glGetVertexAttribiv()
GL_APICALL void GL_APIENTRY glGetVertexAttribiv (GLuint index, GLenum pname, GLint * params)
Definition at line 2886 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       vcos_assert(state != NULL);
       if (index < GL20_CONFIG_MAX_VERTEX_ATTRIBS)
          switch (pname) {
          case GL_VERTEX_ATTRIB_ARRAY_ENABLED:
             params[0] = (GLint) state->attrib[index].enabled ? GL_TRUE : GL_FALSE;
             break;
          case GL_VERTEX_ATTRIB_ARRAY_SIZE:
             params[0] = (GLint) state->attrib[index].size;
             break;
          case GL_VERTEX_ATTRIB_ARRAY_STRIDE:
             params[0] = (GLint) state->attrib[index].stride;
             break;
          case GL_VERTEX_ATTRIB_ARRAY_TYPE:
             params[0] = (GLint) state->attrib[index].type;
             break;
          case GL_VERTEX_ATTRIB_ARRAY_NORMALIZED:
             params[0] = (GLint) state->attrib[index].normalized ? GL_TRUE : GL_FALSE;
             break;
          case GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING:
             params[0] = (GLint) state->attrib[index].buffer;
             break;
          //TODO: is this the best way to handle conversions? We duplicate
          //the entire switch statement.
          case GL_CURRENT_VERTEX_ATTRIB:
             params[0] = (GLint)state->attrib[index].value[0];
             params[1] = (GLint)state->attrib[index].value[1];
             params[2] = (GLint)state->attrib[index].value[2];
             params[3] = (GLint)state->attrib[index].value[3];
             break;
          default:
             set_error(state, GL_INVALID_ENUM);
             break;
          }
       else
          set_error(state, GL_INVALID_VALUE);
    }
 }
glGetVertexAttribPointerv()
GL_APICALL void GL_APIENTRY glGetVertexAttribPointerv (GLuint index, GLenum pname, GLvoid ** pointer)
Definition at line 2940 of file glxx_client.c.
References GL_INVALID_ENUM, GL_VERTEX_ATTRIB_ARRAY_POINTER, glintAttribGetPointer(), GLXX_API_20, glxx_set_error_api(), and NULL.
 {
    void *result = NULL;
    if (pname == GL_VERTEX_ATTRIB_ARRAY_POINTER)
       result = glintAttribGetPointer(GLXX_API_20, index);
    else
       glxx_set_error_api(GLXX_API_20, GL_INVALID_ENUM);
    if (result != NULL)
       *pointer = result;
 }
glHint()
GL_APICALL void GL_APIENTRY glHint (GLenum target, GLenum mode)
Definition at line 2953 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL2(glHint_impl,
                 thread,
                 GLHINT_ID,
                 RPC_ENUM(target),
                 RPC_ENUM(mode));
    }
 }
glIsBuffer()
GL_APICALL GLboolean GL_APIENTRY glIsBuffer (GLuint buffer)
Definition at line 2965 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       return RPC_BOOLEAN_RES(RPC_CALL1_RES(glIsBuffer_impl,
                                            thread,
                                            GLISBUFFER_ID,
                                            RPC_UINT(buffer)));
    }
    return 0;
 }
glIsEnabled()
GL_APICALL GLboolean GL_APIENTRY glIsEnabled (GLenum cap)
Definition at line 2978 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       switch (cap) {
       case GL_VERTEX_ARRAY:
       case GL_NORMAL_ARRAY:
       case GL_COLOR_ARRAY:
       case GL_POINT_SIZE_ARRAY_OES:
       case GL_TEXTURE_COORD_ARRAY:
       case GL_MATRIX_INDEX_ARRAY_OES:
       case GL_WEIGHT_ARRAY_OES:
       {
          GLboolean temp = 0;
          GLuint count = (GLuint) get_boolean_internal_11(thread, cap, &temp);
          UNUSED_NDEBUG(count);
          vcos_assert(count == 1);
          return temp;
       }
       default:
          return RPC_BOOLEAN_RES(RPC_CALL1_RES(glIsEnabled_impl,
                                               thread,
                                               GLISENABLED_ID,
                                               RPC_ENUM(cap)));
       }
    }
    else if (IS_OPENGLES_20(thread)) {
       return RPC_BOOLEAN_RES(RPC_CALL1_RES(glIsEnabled_impl,
                                            thread,
                                            GLISENABLED_ID,
                                            RPC_ENUM(cap)));
    }
    return 0;
 }
glIsFramebuffer()
GL_APICALL GLboolean GL_APIENTRY glIsFramebuffer (GLuint framebuffer)
Definition at line 5269 of file glxx_client.c.
References glxx_client_IsFramebuffer().
 {
    return glxx_client_IsFramebuffer(framebuffer);
 }
glIsProgram()
GL_APICALL GLboolean GL_APIENTRY glIsProgram (GLuint program)
Definition at line 3015 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       return RPC_BOOLEAN_RES(RPC_CALL1_RES(glIsProgram_impl_20,
                                            thread,
                                            GLISPROGRAM_ID_20,
                                            RPC_UINT(program)));
    }
    return 0;
 }
glIsRenderbuffer()
GL_APICALL GLboolean GL_APIENTRY glIsRenderbuffer (GLuint renderbuffer)
Definition at line 5141 of file glxx_client.c.
References glxx_client_IsRenderbuffer().
 {
    return glxx_client_IsRenderbuffer(renderbuffer);
 }
glIsShader()
GL_APICALL GLboolean GL_APIENTRY glIsShader (GLuint shader)
Definition at line 3028 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       return RPC_BOOLEAN_RES(RPC_CALL1_RES(glIsShader_impl_20,
                                            thread,
                                            GLISSHADER_ID_20,
                                            RPC_UINT(shader)));
    }
    return 0;
 }
glIsTexture()
GL_APICALL GLboolean GL_APIENTRY glIsTexture (GLuint texture)
Definition at line 3041 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       return RPC_BOOLEAN_RES(RPC_CALL1_RES(glIsTexture_impl,
                                            thread,
                                            GLISTEXTURE_ID,
                                            RPC_UINT(texture)));
    }
    return 0;
 }
glLineWidth()
GL_APICALL void GL_APIENTRY glLineWidth (GLfloat width)
Definition at line 3209 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL1(glLineWidth_impl,
                 thread,
                 GLLINEWIDTH_ID,
                 RPC_FLOAT(width));
    }
 }
glLinkProgram()
GL_APICALL void GL_APIENTRY glLinkProgram (GLuint program)
Definition at line 3231 of file glxx_client.c.
Referenced by raspitexutil_build_shader_program().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL1(glLinkProgram_impl_20,
                thread,
                GLLINKPROGRAM_ID_20,
                RPC_UINT(program));
    }
 }
glPixelStorei()
GL_APICALL void GL_APIENTRY glPixelStorei (GLenum pname, GLint param)
Definition at line 3487 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       if (is_alignment(param)) {
          GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
          vcos_assert(state != NULL);
          switch (pname) {
          case GL_PACK_ALIGNMENT:
             state->alignment.pack = param;
             break;
          case GL_UNPACK_ALIGNMENT:
             state->alignment.unpack = param;
             break;
          }
       }
    }
 }
glPolygonOffset()
GL_APICALL void GL_APIENTRY glPolygonOffset (GLfloat factor, GLfloat units)
Definition at line 3598 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL2(glPolygonOffset_impl,
                 thread,
                 GLPOLYGONOFFSET_ID,
                 RPC_FLOAT(factor),
                 RPC_FLOAT(units));
    }
 }
glReadPixels()
GL_APICALL void GL_APIENTRY glReadPixels (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid * pixels)
Definition at line 3763 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       uint32_t pitch = get_pitch( (uint32_t)width, format, type, (uint32_t) state->alignment.pack);
       uint32_t lines = pitch ? (uint32_t) (KHDISPATCH_WORKSPACE_SIZE / pitch) : (uint32_t)height;
       if (pixels && lines) {
          int offset = 0;
          while (height > 0) {
             int32_t batch = _min(lines, (int32_t) height);
             RPC_CALL8_OUT_BULK(glReadPixels_impl,
                                thread,
                                GLREADPIXELS_ID,
                                RPC_INT(x),
                                RPC_INT(y + offset),
                                RPC_SIZEI(width),
                                RPC_SIZEI(batch),
                                RPC_ENUM(format),
                                RPC_ENUM(type),
                                RPC_INT(state->alignment.pack),
                                (char *)pixels + offset * pitch);
             offset += batch;
             height -= batch;
          }
       }
       // We do not call flush_callback as the spec does not imply a full flush
       // at this point (I think).
    }
 }
glReleaseShaderCompiler()
GL_APICALL void GL_APIENTRY glReleaseShaderCompiler (void)
Definition at line 4981 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
    }
 }
glRenderbufferStorage()
GL_APICALL void GL_APIENTRY glRenderbufferStorage (GLenum target, GLenum internalformat, GLsizei width, GLsizei height)
Definition at line 5233 of file glxx_client.c.
References glxx_client_RenderbufferStorage().
 {
    glxx_client_RenderbufferStorage(target, internalformat, width, height);
 }
glSampleCoverage()
GL_APICALL void GL_APIENTRY glSampleCoverage (GLclampf value, GLboolean invert)
Definition at line 3828 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL2(glSampleCoverage_impl,
                 thread,
                 GLSAMPLECOVERAGE_ID,
                 RPC_FLOAT(value),
                 RPC_BOOLEAN(invert));
    }
 }
glScissor()
GL_APICALL void GL_APIENTRY glScissor (GLint x, GLint y, GLsizei width, GLsizei height)
Definition at line 3878 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL4(glScissor_impl,
                 thread,
                 GLSCISSOR_ID,
                 RPC_INT(x),
                 RPC_INT(y),
                 RPC_SIZEI(width),
                 RPC_SIZEI(height));
    }
 }
glShaderBinary()
GL_APICALL void GL_APIENTRY glShaderBinary (GLsizei n, const GLuint * shaders, GLenum binaryformat, const GLvoid * binary, GLsizei length)
Definition at line 4988 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    UNUSED(n);
    UNUSED(shaders);
    UNUSED(binaryformat);
    UNUSED(binary);
    UNUSED(length);
    if (IS_OPENGLES_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       set_error(state, GL_INVALID_ENUM);
    }
 }
glShaderSource()
GL_APICALL void GL_APIENTRY glShaderSource (GLuint shader, GLsizei count, const GLchar ** string, const GLint * length)
Definition at line 5003 of file glxx_client.c.
Referenced by raspitexutil_build_shader_program().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
 #ifdef RPC_DIRECT
       RPC_CALL4(glShaderSource_impl_20, thread, no_id, shader,
                              count,
                              string,
                              length);
 #else
       /*
          calculate total workspace required for string, length and source
       */
 #ifdef __SYMBIAN32__
       int total = (int)(rpc_pad_bulk(count * 4) + rpc_pad_bulk(count * 4));
       int i;
       for (i = 0; i < count; i++) {
          if (!length || length[i] < 0)
             total += rpc_pad_bulk(string[i] ? (int)strlen(string[i]) + 1 : 1);
          else
             total += rpc_pad_bulk(length[i]);
       }
       rpc_begin(thread);
       // Assume worst-case (need to compute and send all lengths) - include
       // the 5 words we're sending in the RPC_CALL4() (do we need to do this?)
       //
       rpc_send_ctrl_begin(thread, (count + 5) * sizeof(GLint) );
       RPC_CALL4(no_function,
                 thread,
                 GLSHADERSOURCE_ID_20,
                 RPC_UINT(shader),
                 RPC_SIZEI(count),
                 RPC_INT(total),
                 RPC_BOOLEAN(length ? 1 : 0));
       if (length)
          rpc_send_bulk(thread, length, count * sizeof(GLint));
 //Send all lengths before the first bulk transfer of a line of source code
 //NB this is a temporary fix until issues, with our bulk transfers and the
 //rpc assumptions, have been resolved
 //NB assumes that the line count numbers all fit in the merge buffer
 //which is why a more permanent fix is needed
       for (i = 0; i < count; i++) {
          GLint len;
          if (!length || length[i] < 0) {
             len = string[i] ? (GLint) strlen(string[i]) + 1 : 1;
 //            rpc_send_bulk(&len, sizeof(GLint)); /* todo: this now violates the semantics of rpc_send_bulk. todo: check for other violations in GL */
             rpc_send_ctrl_write(thread, (uint32_t *)&len, sizeof(GLint));
          }
       }
       rpc_send_ctrl_end(thread);  //no more ctrl data to send
       for (i = 0; i < count; i++) {
          GLint len;
          if (!length || length[i] < 0) {
             len = string[i] ? strlen(string[i]) + 1 : 1;
          } else
             len = length[i];
          /* TODO: we currently treat null strings as empty strings
           * But we shouldn't need to deal with them (VND-116)
           */
          rpc_send_bulk(thread, string[i] ? string[i] : "", (uint32_t)len);
       }
       rpc_end(thread);
 #else
       CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
       int total = (int)(rpc_pad_bulk(count * 4) + rpc_pad_bulk(count * 4) + rpc_pad_bulk(sizeof(GLint)));
       int i;
       for (i = 0; i < count; i++)
          if (!length || length[i] < 0)
             total += rpc_pad_bulk(string[i] ? (int)strlen(string[i]) + 1 : 1);
          else
             total += rpc_pad_bulk(length[i]);
       rpc_begin(thread);
       RPC_CALL4(no_function,
                 thread,
                 GLSHADERSOURCE_ID_20,
                 RPC_UINT(shader),
                 RPC_SIZEI(count),
                 RPC_INT(total),
                 RPC_BOOLEAN(length ? 1 : 0));
       if (length)
          rpc_send_bulk(thread, length, count * sizeof(GLint));
       for (i = 0; i < count; i++) {
          GLint len;
          if (!length || length[i] < 0) {
             len = string[i] ? (GLint) strlen(string[i]) + 1 : 1;
             rpc_send_bulk(thread, &len, sizeof(GLint)); /* todo: this now violates the semantics of rpc_send_bulk. todo: check for other violations in GL */
          } else
             len = length[i];
          /* TODO: we currently treat null strings as empty strings
           * But we shouldn't need to deal with them (VND-116)
           */
          rpc_send_bulk(thread, string[i] ? string[i] : "", (uint32_t)len);
       }
       rpc_end(thread);
 #endif
 #endif
    }
 }
glStencilFunc()
GL_APICALL void GL_APIENTRY glStencilFunc (GLenum func, GLint ref, GLuint mask)
Definition at line 3913 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) set_stencil_func(thread, GL_FRONT_AND_BACK, func, ref, mask);
 }
glStencilFuncSeparate()
GL_APICALL void GL_APIENTRY glStencilFuncSeparate (GLenum face, GLenum func, GLint ref, GLuint mask)
Definition at line 3919 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) set_stencil_func(thread, face, func, ref, mask);
 }
glStencilMask()
GL_APICALL void GL_APIENTRY glStencilMask (GLuint mask)
Definition at line 3933 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) set_stencil_mask(thread, GL_FRONT_AND_BACK, mask);
 }
glStencilMaskSeparate()
GL_APICALL void GL_APIENTRY glStencilMaskSeparate (GLenum face, GLuint mask)
Definition at line 3939 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) set_stencil_mask(thread, face, mask);
 }
glStencilOp()
GL_APICALL void GL_APIENTRY glStencilOp (GLenum fail, GLenum zfail, GLenum zpass)
Definition at line 3955 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) set_stencil_op(thread, GL_FRONT_AND_BACK, fail, zfail, zpass);
 }
glStencilOpSeparate()
GL_APICALL void GL_APIENTRY glStencilOpSeparate (GLenum face, GLenum fail, GLenum zfail, GLenum zpass)
Definition at line 3961 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) set_stencil_op(thread, face, fail, zfail, zpass);
 }
glTexImage2D()
GL_APICALL void GL_APIENTRY glTexImage2D (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid * pixels)
Definition at line 4152 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    GLboolean res;
    if (IS_OPENGLES_11_OR_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       uint32_t pitch = get_pitch( (uint32_t)width, format, type, (uint32_t)state->alignment.unpack);
       uint32_t lines = pitch ? (uint32_t)(KHDISPATCH_WORKSPACE_SIZE / pitch) : (uint32_t)height;
       res = RPC_BOOLEAN_RES(RPC_CALL10_IN_BULK_RES(glTexImage2D_impl,
                         thread,
                         GLTEXIMAGE2D_ID,
                         RPC_ENUM(target),
                         RPC_INT(level),
                         RPC_ENUM(internalformat),
                         RPC_SIZEI(width),
                         RPC_SIZEI(height),
                         RPC_INT(border),
                         RPC_ENUM(format),
                         RPC_ENUM(type),
                         RPC_INT(state->alignment.unpack),
                         NULL,
                         0));
       if (res && pixels && lines) {
          int offset = 0;
          while (height > 0) {
             int32_t batch = _min(lines, (int32_t)height);
             RPC_CALL10_IN_BULK(glTexSubImage2D_impl,
                               thread,
                               GLTEXSUBIMAGE2D_ID,
                               RPC_ENUM(target),
                               RPC_INT(level),
                               RPC_INT(0),
                               RPC_INT(offset),
                               RPC_SIZEI(width),
                               RPC_SIZEI(batch),
                               RPC_ENUM(format),
                               RPC_ENUM(type),
                               RPC_INT(state->alignment.unpack),
                               (char *)pixels + offset * pitch,
                               batch * pitch);
             offset += batch;
             height -= batch;
          }
       }
    }
 }
glTexParameterf()
GL_APICALL void GL_APIENTRY glTexParameterf (GLenum target, GLenum pname, GLfloat param)
Definition at line 4218 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL3(glTexParameterf_impl,
                 thread,
                 GLTEXPARAMETERF_ID,
                 RPC_ENUM(target),
                 RPC_ENUM(pname),
                 RPC_FLOAT(param));
    }
 }
glTexParameterfv()
GL_APICALL void GL_APIENTRY glTexParameterfv (GLenum target, GLenum pname, const GLfloat * params)
Definition at line 4280 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    /*
       the only supported texture params are
       TEXTURE_MIN_FILTER
       TEXTURE_MAG_FILTER
       TEXTURE_WRAP_S
       TEXTURE_WRAP_T
       each of which takes a single argument
       and for 1.1
       TEXTURE_CROP_RECT_OES
       which takes 4 ints
    */
    if (IS_OPENGLES_11(thread)) {
       if(pname != GL_TEXTURE_CROP_RECT_OES) {
          glTexParameterf(target, pname, params[0]);
       }
       else {
          RPC_CALL3_IN_CTRL(glTexParameterfv_impl,
                 thread,
                 GLTEXPARAMETERFV_ID,
                 RPC_ENUM(target),
                 RPC_ENUM(pname),
                 params,
                 4 * sizeof(GLfloat));
       }
    }
    else if(IS_OPENGLES_20(thread))
       glTexParameterf(target, pname, params[0]);
 }
glTexParameteri()
GL_APICALL void GL_APIENTRY glTexParameteri (GLenum target, GLenum pname, GLint param)
Definition at line 4205 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL3(glTexParameteri_impl,
                 thread,
                 GLTEXPARAMETERI_ID,
                 RPC_ENUM(target),
                 RPC_ENUM(pname),
                 RPC_INT(param));
    }
 }
glTexParameteriv()
GL_APICALL void GL_APIENTRY glTexParameteriv (GLenum target, GLenum pname, const GLint * params)
Definition at line 4244 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    /*
       the only supported texture params are
       TEXTURE_MIN_FILTER
       TEXTURE_MAG_FILTER
       TEXTURE_WRAP_S
       TEXTURE_WRAP_T
       each of which takes a single argument
       and for 1.1
       TEXTURE_CROP_RECT_OES
       which takes 4 ints
    */
    if (IS_OPENGLES_11(thread)) {
       if(pname != GL_TEXTURE_CROP_RECT_OES) {
          glTexParameteri(target, pname, params[0]);
       }
       else {
          RPC_CALL3_IN_CTRL(glTexParameteriv_impl,
                 thread,
                 GLTEXPARAMETERIV_ID,
                 RPC_ENUM(target),
                 RPC_ENUM(pname),
                 params,
                 4 * sizeof(GLint));
       }
    }
    else if(IS_OPENGLES_20(thread))
       glTexParameteri(target, pname, params[0]);
 }
glTexSubImage2D()
GL_APICALL void GL_APIENTRY glTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * pixels)
Definition at line 4352 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       uint32_t pitch = get_pitch( (uint32_t)width, format, type, (uint32_t)state->alignment.unpack);
       uint32_t lines = pitch ? (uint32_t)(KHDISPATCH_WORKSPACE_SIZE / pitch) : (uint32_t)height;
       if (pixels && lines) {
          int offset = 0;
          while (height > 0) {
             int32_t batch = _min(lines, (int32_t)height);
             RPC_CALL10_IN_BULK(glTexSubImage2D_impl,
                               thread,
                               GLTEXSUBIMAGE2D_ID,
                               RPC_ENUM(target),
                               RPC_INT(level),
                               RPC_INT(xoffset),
                               RPC_INT(yoffset+offset),
                               RPC_SIZEI(width),
                               RPC_SIZEI(batch),
                               RPC_ENUM(format),
                               RPC_ENUM(type),
                               RPC_INT(state->alignment.unpack),
                               (char *)pixels + offset * pitch,
                               batch * pitch);
             offset += batch;
             height -= batch;
          }
       }
    }
 }
glUniform1f()
GL_APICALL void GL_APIENTRY glUniform1f (GLint location, GLfloat x)
Definition at line 4491 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL2(glUniform1f_impl_20,
                 thread,
                 GLUNIFORM1F_ID_20,
                 RPC_INT(location),
                 RPC_FLOAT(x));
    }
 }
glUniform1fv()
GL_APICALL void GL_APIENTRY glUniform1fv (GLint location, GLsizei count, const GLfloat * v)
Definition at line 4624 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       int size = clamp_uniform_size( (int)(count * 1 * sizeof(GLfloat)));
       RPC_CALL4_IN_CTRL(glUniform1fv_impl_20,
                         thread,
                         GLUNIFORM1FV_ID_20,
                         RPC_INT(location),
                         RPC_SIZEI(count),
                         RPC_INT(size),
                         v,
                         (size_t)size);
    }
 }
glUniform1i()
GL_APICALL void GL_APIENTRY glUniform1i (GLint location, GLint x)
Definition at line 4437 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL2(glUniform1i_impl_20,
                 thread,
                 GLUNIFORM1I_ID_20,
                 RPC_INT(location),
                 RPC_INT(x));
    }
 }
glUniform1iv()
GL_APICALL void GL_APIENTRY glUniform1iv (GLint location, GLsizei count, const GLint * v)
Definition at line 4556 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       int size = clamp_uniform_size( (int)(count * 1 * sizeof(GLint)));
       RPC_CALL4_IN_CTRL(glUniform1iv_impl_20,
                         thread,
                         GLUNIFORM1IV_ID_20,
                         RPC_INT(location),
                         RPC_SIZEI(count),
                         RPC_INT(size),
                         v,
                         (size_t)size);
    }
 }
glUniform2f()
GL_APICALL void GL_APIENTRY glUniform2f (GLint location, GLfloat x, GLfloat y)
Definition at line 4503 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL3(glUniform2f_impl_20,
                 thread,
                 GLUNIFORM2F_ID_20,
                 RPC_INT(location),
                 RPC_FLOAT(x),
                 RPC_FLOAT(y));
    }
 }
glUniform2fv()
GL_APICALL void GL_APIENTRY glUniform2fv (GLint location, GLsizei count, const GLfloat * v)
Definition at line 4641 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       int size = clamp_uniform_size( (int)(count * 2 * sizeof(GLfloat)));
       RPC_CALL4_IN_CTRL(glUniform2fv_impl_20,
                         thread,
                         GLUNIFORM2FV_ID_20,
                         RPC_INT(location),
                         RPC_SIZEI(count),
                         RPC_INT(size),
                         v,
                         (size_t)size);
    }
 }
glUniform2i()
GL_APICALL void GL_APIENTRY glUniform2i (GLint location, GLint x, GLint y)
Definition at line 4449 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL3(glUniform2i_impl_20,
                 thread,
                 GLUNIFORM2I_ID_20,
                 RPC_INT(location),
                 RPC_INT(x),
                 RPC_INT(y));
    }
 }
glUniform2iv()
GL_APICALL void GL_APIENTRY glUniform2iv (GLint location, GLsizei count, const GLint * v)
Definition at line 4573 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       int size = clamp_uniform_size( (int)(count * 2 * sizeof(GLint)));
       RPC_CALL4_IN_CTRL(glUniform2iv_impl_20,
                         thread,
                         GLUNIFORM2IV_ID_20,
                         RPC_INT(location),
                         RPC_SIZEI(count),
                         RPC_INT(size),
                         v,
                         (size_t)size);
    }
 }
glUniform3f()
GL_APICALL void GL_APIENTRY glUniform3f (GLint location, GLfloat x, GLfloat y, GLfloat z)
Definition at line 4516 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL4(glUniform3f_impl_20,
                 thread,
                 GLUNIFORM3F_ID_20,
                 RPC_INT(location),
                 RPC_FLOAT(x),
                 RPC_FLOAT(y),
                 RPC_FLOAT(z));
    }
 }
glUniform3fv()
GL_APICALL void GL_APIENTRY glUniform3fv (GLint location, GLsizei count, const GLfloat * v)
Definition at line 4658 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       int size = clamp_uniform_size( (int)(count * 3 * sizeof(GLfloat)));
       RPC_CALL4_IN_CTRL(glUniform3fv_impl_20,
                         thread,
                         GLUNIFORM3FV_ID_20,
                         RPC_INT(location),
                         RPC_SIZEI(count),
                         RPC_INT(size),
                         v,
                         (size_t)size);
    }
 }
glUniform3i()
GL_APICALL void GL_APIENTRY glUniform3i (GLint location, GLint x, GLint y, GLint z)
Definition at line 4462 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL4(glUniform3i_impl_20,
                 thread,
                 GLUNIFORM3I_ID_20,
                 RPC_INT(location),
                 RPC_INT(x),
                 RPC_INT(y),
                 RPC_INT(z));
    }
 }
glUniform3iv()
GL_APICALL void GL_APIENTRY glUniform3iv (GLint location, GLsizei count, const GLint * v)
Definition at line 4590 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       int size = clamp_uniform_size( (int)(count * 3 * sizeof(GLint)));
       RPC_CALL4_IN_CTRL(glUniform3iv_impl_20,
                         thread,
                         GLUNIFORM3IV_ID_20,
                         RPC_INT(location),
                         RPC_SIZEI(count),
                         RPC_INT(size),
                         v,
                         (size_t)size);
    }
 }
glUniform4f()
GL_APICALL void GL_APIENTRY glUniform4f (GLint location, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
Definition at line 4530 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL5(glUniform4f_impl_20,
                 thread,
                 GLUNIFORM4F_ID_20,
                 RPC_INT(location),
                 RPC_FLOAT(x),
                 RPC_FLOAT(y),
                 RPC_FLOAT(z),
                 RPC_FLOAT(w));
    }
 }
glUniform4fv()
GL_APICALL void GL_APIENTRY glUniform4fv (GLint location, GLsizei count, const GLfloat * v)
Definition at line 4675 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       int size = clamp_uniform_size( (int)(count * 4 * sizeof(GLfloat)));
       RPC_CALL4_IN_CTRL(glUniform4fv_impl_20,
                         thread,
                         GLUNIFORM4FV_ID_20,
                         RPC_INT(location),
                         RPC_SIZEI(count),
                         RPC_INT(size),
                         v,
                         (size_t)size);
    }
 }
glUniform4i()
GL_APICALL void GL_APIENTRY glUniform4i (GLint location, GLint x, GLint y, GLint z, GLint w)
Definition at line 4476 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL5(glUniform4i_impl_20,
                 thread,
                 GLUNIFORM4I_ID_20,
                 RPC_INT(location),
                 RPC_INT(x),
                 RPC_INT(y),
                 RPC_INT(z),
                 RPC_INT(w));
    }
 }
glUniform4iv()
GL_APICALL void GL_APIENTRY glUniform4iv (GLint location, GLsizei count, const GLint * v)
Definition at line 4607 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       int size = clamp_uniform_size( (int)(count * 4 * sizeof(GLint)));
       RPC_CALL4_IN_CTRL(glUniform4iv_impl_20,
                         thread,
                         GLUNIFORM4IV_ID_20,
                         RPC_INT(location),
                         RPC_SIZEI(count),
                         RPC_INT(size),
                         v,
                         (size_t)size);
    }
 }
glUniformMatrix2fv()
GL_APICALL void GL_APIENTRY glUniformMatrix2fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat * value)
Definition at line 4697 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       int size = clamp_uniform_size( (int)(count * 2 * 2 * sizeof(GLfloat)));
       RPC_CALL5_IN_CTRL(glUniformMatrix2fv_impl_20,
                         thread,
                         GLUNIFORMMATRIX2FV_ID_20,
                         RPC_INT(location),
                         RPC_SIZEI(count),
                         RPC_BOOLEAN(transpose),
                         RPC_INT(size),
                         value,
                         (size_t)size);
    }
 }
glUniformMatrix3fv()
GL_APICALL void GL_APIENTRY glUniformMatrix3fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat * value)
Definition at line 4715 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       int size = clamp_uniform_size( (int)(count * 3 * 3 * sizeof(GLfloat)));
       RPC_CALL5_IN_CTRL(glUniformMatrix3fv_impl_20,
                         thread,
                         GLUNIFORMMATRIX3FV_ID_20,
                         RPC_INT(location),
                         RPC_SIZEI(count),
                         RPC_BOOLEAN(transpose),
                         RPC_INT(size),
                         value,
                         (size_t)size);
    }
 }
glUniformMatrix4fv()
GL_APICALL void GL_APIENTRY glUniformMatrix4fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat * value)
Definition at line 4733 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       int size = clamp_uniform_size( (int)(count * 4 * 4 * sizeof(GLfloat)));
       RPC_CALL5_IN_CTRL(glUniformMatrix4fv_impl_20,
                         thread,
                         GLUNIFORMMATRIX4FV_ID_20,
                         RPC_INT(location),
                         RPC_SIZEI(count),
                         RPC_BOOLEAN(transpose),
                         RPC_INT(size),
                         value,
                         (size_t)size);
    }
 }
glUseProgram()
GL_APICALL void GL_APIENTRY glUseProgram (GLuint program)
Definition at line 4751 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL1(glUseProgram_impl_20,
                 thread,
                 GLUSEPROGRAM_ID_20,
                 RPC_UINT(program));
    }
 }
glValidateProgram()
GL_APICALL void GL_APIENTRY glValidateProgram (GLuint program)
Definition at line 4762 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL1(glValidateProgram_impl_20,
                 thread,
                 GLVALIDATEPROGRAM_ID_20,
                 RPC_UINT(program));
    }
 }
glVertexAttrib1f()
GL_APICALL void GL_APIENTRY glVertexAttrib1f (GLuint indx, GLfloat x)
Definition at line 4773 of file glxx_client.c.
References glintAttrib(), and GLXX_API_20.
 {
    glintAttrib(GLXX_API_20, indx, x, 0.0f, 0.0f, 1.0f);
 }
glVertexAttrib1fv()
GL_APICALL void GL_APIENTRY glVertexAttrib1fv (GLuint indx, const GLfloat * values)
Definition at line 4793 of file glxx_client.c.
References glintAttrib(), and GLXX_API_20.
 {
    glintAttrib(GLXX_API_20, indx, values[0], 0.0f, 0.0f, 1.0f);
 }
glVertexAttrib2f()
GL_APICALL void GL_APIENTRY glVertexAttrib2f (GLuint indx, GLfloat x, GLfloat y)
Definition at line 4778 of file glxx_client.c.
References glintAttrib(), and GLXX_API_20.
 {
    glintAttrib(GLXX_API_20, indx, x, y, 0.0f, 1.0f);
 }
glVertexAttrib2fv()
GL_APICALL void GL_APIENTRY glVertexAttrib2fv (GLuint indx, const GLfloat * values)
Definition at line 4798 of file glxx_client.c.
References glintAttrib(), and GLXX_API_20.
 {
    glintAttrib(GLXX_API_20, indx, values[0], values[1], 0.0f, 1.0f);
 }
glVertexAttrib3f()
GL_APICALL void GL_APIENTRY glVertexAttrib3f (GLuint indx, GLfloat x, GLfloat y, GLfloat z)
Definition at line 4783 of file glxx_client.c.
References glintAttrib(), and GLXX_API_20.
 {
    glintAttrib(GLXX_API_20, indx, x, y, z, 1.0f);
 }
glVertexAttrib3fv()
GL_APICALL void GL_APIENTRY glVertexAttrib3fv (GLuint indx, const GLfloat * values)
Definition at line 4803 of file glxx_client.c.
References glintAttrib(), and GLXX_API_20.
 {
    glintAttrib(GLXX_API_20, indx, values[0], values[1], values[2], 1.0f);
 }
glVertexAttrib4f()
GL_APICALL void GL_APIENTRY glVertexAttrib4f (GLuint indx, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
Definition at line 4788 of file glxx_client.c.
References glintAttrib(), and GLXX_API_20.
 {
    glintAttrib(GLXX_API_20, indx, x, y, z, w);
 }
glVertexAttrib4fv()
GL_APICALL void GL_APIENTRY glVertexAttrib4fv (GLuint indx, const GLfloat * values)
Definition at line 4808 of file glxx_client.c.
References glintAttrib(), and GLXX_API_20.
 {
    glintAttrib(GLXX_API_20, indx, values[0], values[1], values[2], values[3]);
 }
glVertexAttribPointer()
GL_APICALL void GL_APIENTRY glVertexAttribPointer (GLuint indx, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const GLvoid * ptr)
Definition at line 4829 of file glxx_client.c.
 {
    if (is_vertex_attrib_size(size) && stride >= 0) {
       if (is_vertex_attrib_type(type) || type == GL_HALF_FLOAT_OES) {
          glintAttribPointer(GLXX_API_20, indx, size, type, normalized, stride, ptr);
       } else
          glxx_set_error_api(GLXX_API_20, GL_INVALID_ENUM);
    } else
       glxx_set_error_api(GLXX_API_20, GL_INVALID_VALUE);
 }
glViewport()
GL_APICALL void GL_APIENTRY glViewport (GLint x, GLint y, GLsizei width, GLsizei height)
Definition at line 4866 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL4(glViewport_impl,
                 thread,
                 GLVIEWPORT_ID,
                 RPC_INT(x),
                 RPC_INT(y),
                 RPC_SIZEI(width),
                 RPC_SIZEI(height));
    }
 }