VideoCore Library: interface/mmal/test/examples/example_graph.c File Reference
example_graph.c File Reference
#include "bcm_host.h"
#include "mmal.h"
#include "util/mmal_graph.h"
#include "util/mmal_default_components.h"
#include "util/mmal_util_params.h"
#include <stdio.h>
Macros
#define CHECK_STATUS(status, msg) if (status != MMAL_SUCCESS) { fprintf(stderr, msg"\n"); goto error; }
Functions
int main (int argc, char **argv)
Macro Definition Documentation
CHECK_STATUS
#define CHECK_STATUS (status, msg) if (status != MMAL_SUCCESS) { fprintf(stderr, msg"\n"); goto error; }
Definition at line 35 of file example_graph.c.
Referenced by main().
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 37 of file example_graph.c.
References bcm_host_init(), CHECK_STATUS, MMAL_COMPONENT_T::control, error(), MMAL_COMPONENT_DEFAULT_CONTAINER_READER, MMAL_COMPONENT_DEFAULT_VIDEO_DECODER, MMAL_COMPONENT_DEFAULT_VIDEO_RENDERER, mmal_component_release(), mmal_graph_create(), mmal_graph_destroy(), mmal_graph_disable(), mmal_graph_enable(), mmal_graph_new_component(), mmal_graph_new_connection(), MMAL_SUCCESS, mmal_util_port_set_uri(), NULL, MMAL_COMPONENT_T::output, and status.
 {
    MMAL_STATUS_T status;
    MMAL_GRAPH_T *graph = 0;
    MMAL_COMPONENT_T *reader = 0, *decoder = 0, *renderer = 0;
    if (argc < 2)
    {
       fprintf(stderr, "invalid arguments\n");
       return -1;
    }
    bcm_host_init();
    /* Create the graph */
    status = mmal_graph_create(&graph, 0);
    CHECK_STATUS(status, "failed to create graph");
    /* Add the components */
    status = mmal_graph_new_component(graph, MMAL_COMPONENT_DEFAULT_CONTAINER_READER, &reader);
    CHECK_STATUS(status, "failed to create reader");
    status = mmal_graph_new_component(graph, MMAL_COMPONENT_DEFAULT_VIDEO_DECODER, &decoder);
    CHECK_STATUS(status, "failed to create decoder");
    status = mmal_graph_new_component(graph, MMAL_COMPONENT_DEFAULT_VIDEO_RENDERER, &renderer);
    CHECK_STATUS(status, "failed to create renderer");
    /* Configure the reader using the given URI */
    status = mmal_util_port_set_uri(reader->control, argv[1]);
    CHECK_STATUS(status, "failed to set uri");
    /* connect them up - this propagates port settings from outputs to inputs */
    status = mmal_graph_new_connection(graph, reader->output[0], decoder->input[0], 0, NULL);
    CHECK_STATUS(status, "failed to connect reader to decoder");
    status = mmal_graph_new_connection(graph, decoder->output[0], renderer->input[0], 0, NULL);
    CHECK_STATUS(status, "failed to connect decoder to renderer");
    /* Start playback */
    fprintf(stderr, "start playback\n");
    status = mmal_graph_enable(graph, NULL, NULL);
    CHECK_STATUS(status, "failed to enable graph");
    sleep(5);
    /* Stop everything */
    fprintf(stderr, "stop playback\n");
    mmal_graph_disable(graph);
  error:
    /* Cleanup everything */
    if (reader)
       mmal_component_release(reader);
    if (decoder)
       mmal_component_release(decoder);
    if (renderer)
       mmal_component_release(renderer);
    if (graph)
       mmal_graph_destroy(graph);
    return status == MMAL_SUCCESS ? 0 : -1;
 }