VideoCore Library: Generic Linked List
Generic Linked List
Classes
struct MMAL_LIST_ELEMENT_T
struct MMAL_LIST_T
Typedefs
typedef struct MMAL_LIST_ELEMENT_T MMAL_LIST_ELEMENT_T
typedef struct MMAL_LIST_T MMAL_LIST_T
typedef int(* MMAL_LIST_COMPARE_T) (MMAL_LIST_ELEMENT_T *lhs, MMAL_LIST_ELEMENT_T *rhs)
Functions
MMAL_LIST_T * mmal_list_create (void)
void mmal_list_destroy (MMAL_LIST_T *list)
MMAL_LIST_ELEMENT_T * mmal_list_pop_back (MMAL_LIST_T *list)
MMAL_LIST_ELEMENT_T * mmal_list_pop_front (MMAL_LIST_T *list)
void mmal_list_push_front (MMAL_LIST_T *list, MMAL_LIST_ELEMENT_T *element)
void mmal_list_push_back (MMAL_LIST_T *list, MMAL_LIST_ELEMENT_T *element)
void mmal_list_insert (MMAL_LIST_T *list, MMAL_LIST_ELEMENT_T *element, MMAL_LIST_COMPARE_T compare)
Detailed Description
This provides a thread-safe implementation of a linked list which can be used with any data type.
Typedef Documentation
MMAL_LIST_COMPARE_T
typedef int(* MMAL_LIST_COMPARE_T) (MMAL_LIST_ELEMENT_T *lhs, MMAL_LIST_ELEMENT_T *rhs)
List comparison function. This is supplied by a client when inserting an element in the middle of the list. The list will always insert a smaller element in front of a larger element.
Returns
TRUE: lhs < rhs FALSE: lhs >= rhs
Definition at line 108 of file mmal_list.h.
MMAL_LIST_ELEMENT_T
typedef struct MMAL_LIST_ELEMENT_T MMAL_LIST_ELEMENT_T
Single element in the list
MMAL_LIST_T
typedef struct MMAL_LIST_T MMAL_LIST_T
Linked list type. Clients shouldn't modify this directly. Use the provided API functions to add new elements. The public members are only for debug purposes.
Function Documentation
mmal_list_create()
MMAL_LIST_T* mmal_list_create (void)
Create a new linked list.
Returns
Pointer to new queue (NULL on failure).
Definition at line 53 of file mmal_list.c.
References error(), NULL, vcos_free(), vcos_malloc(), vcos_mutex_create(), vcos_mutex_lock(), vcos_mutex_unlock(), and VCOS_SUCCESS.
 {
    MMAL_LIST_PRIVATE_T *private;
    private = vcos_malloc(sizeof(MMAL_LIST_PRIVATE_T), "mmal-list");
    if (private == NULL)
       goto error;
    if (vcos_mutex_create(&private->lock, "mmal-list lock") != VCOS_SUCCESS)
       goto error;
    /* lock to keep coverity happy */
    vcos_mutex_lock(&private->lock);
    private->list.first = NULL;
    private->list.last = NULL;
    private->list.length = 0;
    vcos_mutex_unlock(&private->lock);
    return &private->list;
 error:
    vcos_free(private);
    return NULL;
 }
mmal_list_destroy()
void mmal_list_destroy (MMAL_LIST_T * list)
Destroy a linked list.
Parameters
list List to destroy
Definition at line 79 of file mmal_list.c.
References vcos_free(), and vcos_mutex_delete().
 {
    MMAL_LIST_PRIVATE_T *private = (MMAL_LIST_PRIVATE_T*)list;
    vcos_mutex_delete(&private->lock);
    vcos_free(private);
 }
mmal_list_insert()
void mmal_list_insert (MMAL_LIST_T * list, MMAL_LIST_ELEMENT_T * element, MMAL_LIST_COMPARE_T compare)
Insert an element into the list. The location where the element is inserted is determined using the supplied comparison function. Smaller elements are inserted in front of larger elements.
Parameters
list List to add to
element The element to insert
compare Comparison function supplied by the client
Definition at line 182 of file mmal_list.c.
 {
    MMAL_LIST_ELEMENT_T *cur;
    mmal_list_lock(list);
    if (list->first == NULL)
    {
       /* List empty */
       mmal_list_unlock(list);
       mmal_list_push_front(list, element);
       return;
    }
    cur = list->first;
    while (cur)
    {
       if (compare(element, cur))
       {
          /* Slot found! */
          list->length++;
          if (cur == list->first)
             list->first = element;
          else
             cur->prev->next = element;
          element->prev = cur->prev;
          element->next = cur;
          cur->prev = element;
          mmal_list_unlock(list);
          return;
       }
       cur = cur->next;
    }
    /* If we get here, none of the existing elements are greater
     * than the new on, so just add it to the back of the list */
    mmal_list_unlock(list);
    mmal_list_push_back(list, element);
 }
mmal_list_pop_back()
MMAL_LIST_ELEMENT_T* mmal_list_pop_back (MMAL_LIST_T * list)
Remove the last element in the list.
Parameters
list List to remove from
Returns
Pointer to the last element (or NULL if empty)
Definition at line 88 of file mmal_list.c.
 {
    MMAL_LIST_ELEMENT_T *element;
    mmal_list_lock(list);
    element = list->last;
    if (element != NULL)
    {
       list->length--;
       list->last = element->prev;
       if (list->last)
          list->last->next = NULL;
       else
          list->first = NULL; /* list is now empty */
       element->prev = NULL;
       element->next = NULL;
    }
    mmal_list_unlock(list);
    return element;
 }
mmal_list_pop_front()
MMAL_LIST_ELEMENT_T* mmal_list_pop_front (MMAL_LIST_T * list)
Remove the first element in the list.
Parameters
list List to remove from
Returns
Pointer to the first element (or NULL if empty)
Definition at line 115 of file mmal_list.c.
 {
    MMAL_LIST_ELEMENT_T *element;
    mmal_list_lock(list);
    element = list->first;
    if (element != NULL)
    {
       list->length--;
       list->first = element->next;
       if (list->first)
          list->first->prev = NULL;
       else
          list->last = NULL; /* list is now empty */
       element->prev = NULL;
       element->next = NULL;
    }
    mmal_list_unlock(list);
    return element;
 }
mmal_list_push_back()
void mmal_list_push_back (MMAL_LIST_T * list, MMAL_LIST_ELEMENT_T * element)
Add an element to the back of the list.
Parameters
list List to add to
element The element to add
Definition at line 162 of file mmal_list.c.
 {
    mmal_list_lock(list);
    list->length++;
    element->next = NULL;
    element->prev = list->last;
    if (list->last)
       list->last->next = element;
    else
       list->first = element; /* list was empty */
    list->last = element;
    mmal_list_unlock(list);
 }
mmal_list_push_front()
void mmal_list_push_front (MMAL_LIST_T * list, MMAL_LIST_ELEMENT_T * element)
Add an element to the front of the list.
Parameters
list List to add to
element The element to add
Definition at line 142 of file mmal_list.c.
 {
    mmal_list_lock(list);
    list->length++;
    element->prev = NULL;
    element->next = list->first;
    if (list->first)
       list->first->prev = element;
    else
       list->last = element; /* list was empty */
    list->first = element;
    mmal_list_unlock(list);
 }