VideoCore Library: interface/vmcs_host/vcilcs_common.h File Reference
vcilcs_common.h File Reference
Classes
struct VC_PRIVATE_PORT_T
struct _VC_PRIVATE_COMPONENT_T
struct ILCS_COMMON_T
Typedefs
typedef struct _VC_PRIVATE_COMPONENT_T VC_PRIVATE_COMPONENT_T
Functions
VCHPRE_ void VCHPOST_ vcilcs_config (ILCS_CONFIG_T *config)
VCHPRE_ void VCHPOST_ vcil_in_get_state (ILCS_COMMON_T *st, void *call, int clen, void *resp, int *rlen)
VCHPRE_ void VCHPOST_ vcil_in_get_parameter (ILCS_COMMON_T *st, void *call, int clen, void *resp, int *rlen)
VCHPRE_ void VCHPOST_ vcil_in_set_parameter (ILCS_COMMON_T *st, void *call, int clen, void *resp, int *rlen)
VCHPRE_ void VCHPOST_ vcil_in_get_config (ILCS_COMMON_T *st, void *call, int clen, void *resp, int *rlen)
VCHPRE_ void VCHPOST_ vcil_in_set_config (ILCS_COMMON_T *st, void *call, int clen, void *resp, int *rlen)
VCHPRE_ void VCHPOST_ vcil_in_use_buffer (ILCS_COMMON_T *st, void *call, int clen, void *resp, int *rlen)
VCHPRE_ void VCHPOST_ vcil_in_free_buffer (ILCS_COMMON_T *st, void *call, int clen, void *resp, int *rlen)
VCHPRE_ void VCHPOST_ vcil_in_empty_this_buffer (ILCS_COMMON_T *st, void *call, int clen, void *resp, int *rlen)
VCHPRE_ void VCHPOST_ vcil_in_fill_this_buffer (ILCS_COMMON_T *st, void *call, int clen, void *resp, int *rlen)
VCHPRE_ void VCHPOST_ vcil_in_get_component_version (ILCS_COMMON_T *st, void *call, int clen, void *resp, int *rlen)
VCHPRE_ void VCHPOST_ vcil_in_get_extension_index (ILCS_COMMON_T *st, void *call, int clen, void *resp, int *rlen)
VCHPRE_ void VCHPOST_ vcil_in_component_role_enum (ILCS_COMMON_T *st, void *call, int clen, void *resp, int *rlen)
VCHPRE_ void VCHPOST_ vcil_out_event_handler (ILCS_COMMON_T *st, void *call, int clen, void *resp, int *rlen)
VCHPRE_ void VCHPOST_ vcil_out_empty_buffer_done (ILCS_COMMON_T *st, void *call, int clen, void *resp, int *rlen)
VCHPRE_ void VCHPOST_ vcil_out_fill_buffer_done (ILCS_COMMON_T *st, void *call, int clen, void *resp, int *rlen)
VCHPRE_ OMX_ERRORTYPE VCHPOST_ vcil_out_get_debug_information (ILCS_COMMON_T *st, OMX_STRING debugInfo, OMX_S32 *pLen)
VCHPRE_ OMX_ERRORTYPE VCHPOST_ vcil_out_create_component (ILCS_COMMON_T *st, OMX_HANDLETYPE hComponent, OMX_STRING component_name)
VCHPRE_ OMX_ERRORTYPE VCHPOST_ vcil_out_component_name_enum (ILCS_COMMON_T *st, OMX_STRING cComponentName, OMX_U32 nNameLength, OMX_U32 nIndex)
Typedef Documentation
VC_PRIVATE_COMPONENT_T
typedef struct _VC_PRIVATE_COMPONENT_T VC_PRIVATE_COMPONENT_T
Definition at line 47 of file vcilcs_common.h.
Function Documentation
vcil_in_component_role_enum()
VCHPRE_ void VCHPOST_ vcil_in_component_role_enum (ILCS_COMMON_T * st, void * call, int clen, void * resp, int * rlen)
vcil_in_empty_this_buffer()
VCHPRE_ void VCHPOST_ vcil_in_empty_this_buffer (ILCS_COMMON_T * st, void * call, int clen, void * resp, int * rlen)
Definition at line 203 of file vcilcs_in.c.
References IL_RESPONSE_HEADER_T::func, IL_EMPTY_THIS_BUFFER, ILCS_COMMON_T::ilcs, ilcs_receive_buffer(), and vc_assert.
 {
    IL_RESPONSE_HEADER_T *ret = resp;
    OMX_COMPONENTTYPE *pComp;
    OMX_BUFFERHEADERTYPE *pHeader;
    pHeader = ilcs_receive_buffer(st->ilcs, call, clen, &pComp);
    *rlen = sizeof(IL_RESPONSE_HEADER_T);
    ret->func = IL_EMPTY_THIS_BUFFER;
    if(pHeader)
    {
       vc_assert(is_valid_hostside_buffer(pHeader));
       ret->err = pComp->EmptyThisBuffer(pComp, pHeader);
    }
    else
       ret->err = OMX_ErrorHardware;
 }
vcil_in_fill_this_buffer()
VCHPRE_ void VCHPOST_ vcil_in_fill_this_buffer (ILCS_COMMON_T * st, void * call, int clen, void * resp, int * rlen)
Definition at line 223 of file vcilcs_in.c.
References IL_PASS_BUFFER_EXECUTE_T::bufferHeader, OMX_BUFFERHEADERTYPE::pAppPrivate, OMX_BUFFERHEADERTYPE::pBuffer, OMX_BUFFERHEADERTYPE::pInputPortPrivate, OMX_BUFFERHEADERTYPE::pOutputPortPrivate, OMX_BUFFERHEADERTYPE::pPlatformPrivate, IL_PASS_BUFFER_EXECUTE_T::reference, and vc_assert.
 {
    IL_PASS_BUFFER_EXECUTE_T *exe = call;
    IL_RESPONSE_HEADER_T *ret = resp;
    OMX_COMPONENTTYPE *pComp = exe->reference;
    OMX_BUFFERHEADERTYPE *pHeader = exe->bufferHeader.pOutputPortPrivate;
    OMX_U8 *pBuffer = pHeader->pBuffer;
    OMX_PTR *pAppPrivate = pHeader->pAppPrivate;
    OMX_PTR *pPlatformPrivate = pHeader->pPlatformPrivate;
    OMX_PTR *pInputPortPrivate = pHeader->pInputPortPrivate;
    OMX_PTR *pOutputPortPrivate = pHeader->pOutputPortPrivate;
    vc_assert(pHeader);
    memcpy(pHeader, &exe->bufferHeader, sizeof(OMX_BUFFERHEADERTYPE));
    pHeader->pBuffer = pBuffer;
    pHeader->pAppPrivate = pAppPrivate;
    pHeader->pPlatformPrivate = pPlatformPrivate;
    pHeader->pInputPortPrivate = pInputPortPrivate;
    pHeader->pOutputPortPrivate = pOutputPortPrivate;
    vc_assert(is_valid_hostside_buffer(pHeader));
    *rlen = sizeof(IL_RESPONSE_HEADER_T);
    ret->func = IL_FILL_THIS_BUFFER;
    ret->err = pComp->FillThisBuffer(pComp, pHeader);
 }
vcil_in_free_buffer()
VCHPRE_ void VCHPOST_ vcil_in_free_buffer (ILCS_COMMON_T * st, void * call, int clen, void * resp, int * rlen)
Definition at line 174 of file vcilcs_in.c.
References OMX_PARAM_PORTDEFINITIONTYPE::eDir, IL_RESPONSE_HEADER_T::err, error(), OMX_COMPONENTTYPE::FreeBuffer, IL_RESPONSE_HEADER_T::func, OMX_COMPONENTTYPE::GetParameter, IL_FREE_BUFFER, IL_FREE_BUFFER_EXECUTE_T::inputPrivate, OMX_PARAM_PORTDEFINITIONTYPE::nPortIndex, OMX_PARAM_PORTDEFINITIONTYPE::nSize, OMX_PARAM_PORTDEFINITIONTYPE::nVersion, OMX_VERSIONTYPE::nVersion, OMX_DirInput, OMX_ErrorNone, OMX_IndexParamPortDefinition, OMX_VERSION, IL_FREE_BUFFER_EXECUTE_T::outputPrivate, OMX_BUFFERHEADERTYPE::pBuffer, IL_FREE_BUFFER_EXECUTE_T::port, IL_FREE_BUFFER_EXECUTE_T::reference, vc_assert, and vcos_free().
 {
    IL_FREE_BUFFER_EXECUTE_T *exe = call;
    IL_RESPONSE_HEADER_T *ret = resp;
    OMX_COMPONENTTYPE *pComp = exe->reference;
    OMX_BUFFERHEADERTYPE *pHeader;
    OMX_U8 *buffer;
    OMX_PARAM_PORTDEFINITIONTYPE def;
    OMX_ERRORTYPE error;
    def.nSize = sizeof(OMX_PARAM_PORTDEFINITIONTYPE);
    def.nVersion.nVersion = OMX_VERSION;
    def.nPortIndex = exe->port;
    error = pComp->GetParameter(pComp, OMX_IndexParamPortDefinition, &def);
    vc_assert(error == OMX_ErrorNone);
    if (def.eDir == OMX_DirInput)
       pHeader = exe->inputPrivate;
    else
       pHeader = exe->outputPrivate;
    buffer = pHeader->pBuffer;
    *rlen = sizeof(IL_RESPONSE_HEADER_T);
    ret->func = IL_FREE_BUFFER;
    ret->err = pComp->FreeBuffer(pComp, exe->port, pHeader);
    if (ret->err == OMX_ErrorNone)
       vcos_free(buffer);
 }
vcil_in_get_component_version()
VCHPRE_ void VCHPOST_ vcil_in_get_component_version (ILCS_COMMON_T * st, void * call, int clen, void * resp, int * rlen)
Definition at line 251 of file vcilcs_in.c.
References IL_GET_VERSION_RESPONSE_T::component_version, IL_GET_VERSION_RESPONSE_T::err, IL_GET_VERSION_RESPONSE_T::func, OMX_COMPONENTTYPE::GetComponentVersion, IL_GET_COMPONENT_VERSION, IL_GET_VERSION_RESPONSE_T::name, IL_EXECUTE_HEADER_T::reference, IL_GET_VERSION_RESPONSE_T::spec_version, and IL_GET_VERSION_RESPONSE_T::uuid.
 {
    IL_EXECUTE_HEADER_T *exe = call;
    IL_GET_VERSION_RESPONSE_T *ret = resp;
    OMX_COMPONENTTYPE *pComp = exe->reference;
    *rlen = sizeof(IL_GET_VERSION_RESPONSE_T);
    ret->func = IL_GET_COMPONENT_VERSION;
    ret->err = pComp->GetComponentVersion(pComp, ret->name, &ret->component_version, &ret->spec_version, &ret->uuid);
 }
vcil_in_get_config()
VCHPRE_ void VCHPOST_ vcil_in_get_config (ILCS_COMMON_T * st, void * call, int clen, void * resp, int * rlen)
Definition at line 95 of file vcilcs_in.c.
References IL_GET_RESPONSE_T::err, IL_GET_RESPONSE_T::func, OMX_COMPONENTTYPE::GetConfig, IL_GET_CONFIG, IL_GET_RESPONSE_HEADER_SIZE, IL_GET_EXECUTE_T::index, OMX_ErrorHardware, IL_GET_EXECUTE_T::param, IL_GET_RESPONSE_T::param, IL_GET_EXECUTE_T::reference, and VC_ILCS_MAX_PARAM_SIZE.
 {
    IL_GET_EXECUTE_T *exe = call;
    IL_GET_RESPONSE_T *ret = resp;
    OMX_COMPONENTTYPE *pComp  = exe->reference;
    OMX_U32 size = *((OMX_U32 *) (&exe->param));
    ret->func = IL_GET_CONFIG;
    if(size > VC_ILCS_MAX_PARAM_SIZE)
    {
       *rlen = IL_GET_RESPONSE_HEADER_SIZE;
       ret->err = OMX_ErrorHardware;
    }
    else
    {
       *rlen = size + IL_GET_RESPONSE_HEADER_SIZE;
       ret->func = IL_GET_CONFIG;
       ret->err = pComp->GetConfig(pComp, exe->index, exe->param);
       memcpy(ret->param, exe->param, size);
    }
 }
vcil_in_get_extension_index()
VCHPRE_ void VCHPOST_ vcil_in_get_extension_index (ILCS_COMMON_T * st, void * call, int clen, void * resp, int * rlen)
Definition at line 262 of file vcilcs_in.c.
References IL_GET_EXTENSION_RESPONSE_T::err, IL_GET_EXTENSION_RESPONSE_T::func, OMX_COMPONENTTYPE::GetExtensionIndex, IL_GET_EXTENSION_INDEX, IL_GET_EXTENSION_RESPONSE_T::index, IL_GET_EXTENSION_EXECUTE_T::name, and IL_GET_EXTENSION_EXECUTE_T::reference.
 {
    IL_GET_EXTENSION_EXECUTE_T *exe = call;
    IL_GET_EXTENSION_RESPONSE_T *ret = resp;
    OMX_COMPONENTTYPE *pComp = exe->reference;
    *rlen = sizeof(IL_GET_EXTENSION_RESPONSE_T);
    ret->func = IL_GET_EXTENSION_INDEX;
    ret->err = pComp->GetExtensionIndex(pComp, exe->name, &ret->index);
 }
vcil_in_get_parameter()
VCHPRE_ void VCHPOST_ vcil_in_get_parameter (ILCS_COMMON_T * st, void * call, int clen, void * resp, int * rlen)
Definition at line 62 of file vcilcs_in.c.
References IL_GET_RESPONSE_T::err, IL_GET_RESPONSE_T::func, OMX_COMPONENTTYPE::GetParameter, IL_GET_PARAMETER, IL_GET_RESPONSE_HEADER_SIZE, IL_GET_EXECUTE_T::index, OMX_ErrorHardware, IL_GET_EXECUTE_T::param, IL_GET_RESPONSE_T::param, IL_GET_EXECUTE_T::reference, and VC_ILCS_MAX_PARAM_SIZE.
 {
    IL_GET_EXECUTE_T *exe = call;
    IL_GET_RESPONSE_T *ret = resp;
    OMX_COMPONENTTYPE *pComp  = exe->reference;
    OMX_U32 size = *((OMX_U32 *) (&exe->param));
    ret->func = IL_GET_PARAMETER;
    if(size > VC_ILCS_MAX_PARAM_SIZE)
    {
       *rlen = IL_GET_RESPONSE_HEADER_SIZE;
       ret->err = OMX_ErrorHardware;
    }
    else
    {
       *rlen = size + IL_GET_RESPONSE_HEADER_SIZE;
       ret->err = pComp->GetParameter(pComp, exe->index, exe->param);
       memcpy(ret->param, exe->param, size);
    }
 }
vcil_in_get_state()
VCHPRE_ void VCHPOST_ vcil_in_get_state (ILCS_COMMON_T * st, void * call, int clen, void * resp, int * rlen)
Definition at line 51 of file vcilcs_in.c.
References IL_GET_STATE_RESPONSE_T::err, IL_GET_STATE_RESPONSE_T::func, OMX_COMPONENTTYPE::GetState, IL_GET_STATE, IL_EXECUTE_HEADER_T::reference, and IL_GET_STATE_RESPONSE_T::state.
 {
    IL_EXECUTE_HEADER_T *exe = call;
    IL_GET_STATE_RESPONSE_T *ret = resp;
    OMX_COMPONENTTYPE *pComp = exe->reference;
    *rlen = sizeof(IL_GET_STATE_RESPONSE_T);
    ret->func = IL_GET_STATE;
    ret->err = pComp->GetState(pComp, &ret->state);
 }
vcil_in_set_config()
VCHPRE_ void VCHPOST_ vcil_in_set_config (ILCS_COMMON_T * st, void * call, int clen, void * resp, int * rlen)
Definition at line 118 of file vcilcs_in.c.
References IL_RESPONSE_HEADER_T::err, IL_RESPONSE_HEADER_T::func, IL_SET_CONFIG, IL_SET_EXECUTE_T::index, IL_SET_EXECUTE_T::param, IL_SET_EXECUTE_T::reference, and OMX_COMPONENTTYPE::SetConfig.
 {
    IL_SET_EXECUTE_T *exe = call;
    IL_RESPONSE_HEADER_T *ret = resp;
    OMX_COMPONENTTYPE *pComp  = exe->reference;
    *rlen = sizeof(IL_RESPONSE_HEADER_T);
    ret->func = IL_SET_CONFIG;
    ret->err = pComp->SetConfig(pComp, exe->index, exe->param);
 }
vcil_in_set_parameter()
VCHPRE_ void VCHPOST_ vcil_in_set_parameter (ILCS_COMMON_T * st, void * call, int clen, void * resp, int * rlen)
Definition at line 84 of file vcilcs_in.c.
References IL_RESPONSE_HEADER_T::err, IL_RESPONSE_HEADER_T::func, IL_SET_PARAMETER, IL_SET_EXECUTE_T::index, IL_SET_EXECUTE_T::param, IL_SET_EXECUTE_T::reference, and OMX_COMPONENTTYPE::SetParameter.
 {
    IL_SET_EXECUTE_T *exe = call;
    IL_RESPONSE_HEADER_T *ret = resp;
    OMX_COMPONENTTYPE *pComp  = exe->reference;
    *rlen = sizeof(IL_RESPONSE_HEADER_T);
    ret->func = IL_SET_PARAMETER;
    ret->err = pComp->SetParameter(pComp, exe->index, exe->param);
 }
vcil_in_use_buffer()
VCHPRE_ void VCHPOST_ vcil_in_use_buffer (ILCS_COMMON_T * st, void * call, int clen, void * resp, int * rlen)
Definition at line 129 of file vcilcs_in.c.
References IL_ADD_BUFFER_RESPONSE_T::bufferHeader, IL_ADD_BUFFER_EXECUTE_T::bufferReference, OMX_PARAM_PORTDEFINITIONTYPE::eDir, IL_ADD_BUFFER_RESPONSE_T::err, error(), IL_ADD_BUFFER_RESPONSE_T::func, OMX_COMPONENTTYPE::GetParameter, IL_USE_BUFFER, OMX_PARAM_PORTDEFINITIONTYPE::nPortIndex, OMX_PARAM_PORTDEFINITIONTYPE::nSize, OMX_PARAM_PORTDEFINITIONTYPE::nVersion, OMX_VERSIONTYPE::nVersion, OMX_DirInput, OMX_ErrorInsufficientResources, OMX_ErrorNone, OMX_IndexParamPortDefinition, OMX_VERSION, OMX_BUFFERHEADERTYPE::pInputPortPrivate, IL_ADD_BUFFER_EXECUTE_T::port, OMX_BUFFERHEADERTYPE::pOutputPortPrivate, IL_ADD_BUFFER_EXECUTE_T::reference, IL_ADD_BUFFER_RESPONSE_T::reference, IL_ADD_BUFFER_EXECUTE_T::size, OMX_COMPONENTTYPE::UseBuffer, vc_assert, vcos_free(), and vcos_malloc_aligned().
 {
    IL_ADD_BUFFER_EXECUTE_T *exe = call;
    IL_ADD_BUFFER_RESPONSE_T *ret = resp;
    OMX_COMPONENTTYPE *pComp = exe->reference;
    OMX_U8 *buffer;
    OMX_BUFFERHEADERTYPE *bufferHeader;
    *rlen = sizeof(IL_ADD_BUFFER_RESPONSE_T);
    buffer = vcos_malloc_aligned(exe->size, 32, "vcin mapping buffer"); // 32-byte aligned
    if (!buffer)
    {
       ret->err = OMX_ErrorInsufficientResources;
       return;
    }
    //OMX_OSAL_Trace(OMX_OSAL_TRACE_COMPONENT, "hostcomp: use buffer(%p)\n", buffer);
    ret->func = IL_USE_BUFFER;
    ret->err = pComp->UseBuffer(pComp, &bufferHeader, exe->port, exe->bufferReference, exe->size, buffer);
    if (ret->err == OMX_ErrorNone)
    {
       // we're going to pass this buffer to VC
       // initialise our private field in their copy with the host buffer reference
       OMX_PARAM_PORTDEFINITIONTYPE def;
       OMX_ERRORTYPE error;
       def.nSize = sizeof(OMX_PARAM_PORTDEFINITIONTYPE);
       def.nVersion.nVersion = OMX_VERSION;
       def.nPortIndex = exe->port;
       error = pComp->GetParameter(pComp, OMX_IndexParamPortDefinition, &def);
       vc_assert(error == OMX_ErrorNone);
       ret->reference = bufferHeader;
       memcpy(&ret->bufferHeader, bufferHeader, sizeof(OMX_BUFFERHEADERTYPE));
       if (def.eDir == OMX_DirInput)
          ret->bufferHeader.pInputPortPrivate = bufferHeader;
       else
          ret->bufferHeader.pOutputPortPrivate = bufferHeader;
    }
    else
       vcos_free(buffer);
 }
vcil_out_component_name_enum()
VCHPRE_ OMX_ERRORTYPE VCHPOST_ vcil_out_component_name_enum (ILCS_COMMON_T * st, OMX_STRING cComponentName, OMX_U32 nNameLength, OMX_U32 nIndex)
Definition at line 724 of file vcilcs_out.c.
References IL_COMPONENT_NAME_ENUM_RESPONSE_T::err, IL_COMPONENT_NAME_ENUM, ILCS_COMMON_T::ilcs, ilcs_execute_function(), IL_COMPONENT_NAME_ENUM_EXECUTE_T::index, IL_COMPONENT_NAME_ENUM_RESPONSE_T::name, and OMX_ErrorHardware.
Referenced by OMX_ComponentNameEnum().
 {
    IL_COMPONENT_NAME_ENUM_EXECUTE_T exe;
    IL_COMPONENT_NAME_ENUM_RESPONSE_T resp;
    int rlen = sizeof(resp);
    exe.index = nIndex;
    if(ilcs_execute_function(st->ilcs, IL_COMPONENT_NAME_ENUM, &exe, sizeof(exe), &resp, &rlen) < 0 || rlen != sizeof(resp))
       return OMX_ErrorHardware;
    if (sizeof(resp.name) < nNameLength)
       nNameLength = sizeof(resp.name);
    strncpy((char *)cComponentName, (char *) resp.name, nNameLength);
    cComponentName[127] = 0;
    return resp.err;
 }
vcil_out_create_component()
VCHPRE_ OMX_ERRORTYPE VCHPOST_ vcil_out_create_component (ILCS_COMMON_T * st, OMX_HANDLETYPE hComponent, OMX_STRING component_name)
Definition at line 756 of file vcilcs_out.c.
References _VC_PRIVATE_COMPONENT_T::comp, ILCS_COMMON_T::component_list, ILCS_COMMON_T::component_lock, VC_PRIVATE_PORT_T::dir, IL_CREATE_COMPONENT_RESPONSE_T::err, OMX_COMPONENTTYPE::GetComponentVersion, IL_COMPONENT_DEINIT, IL_CREATE_COMPONENT, IL_GET_EXECUTE_HEADER_SIZE, IL_GET_PARAMETER, ILCS_COMMON_T::ilcs, ilcs_execute_function(), IL_GET_EXECUTE_T::index, IL_CREATE_COMPONENT_EXECUTE_T::mark, IL_CREATE_COMPONENT_EXECUTE_T::name, _VC_PRIVATE_COMPONENT_T::next, OMX_PARAM_PORTSUMMARYTYPE::nSize, _VC_PRIVATE_COMPONENT_T::numPorts, IL_CREATE_COMPONENT_RESPONSE_T::numPorts, OMX_PARAM_PORTSUMMARYTYPE::nVersion, OMX_VERSIONTYPE::nVersion, OMX_DirInput, OMX_DirOutput, OMX_ErrorHardware, OMX_ErrorInsufficientResources, OMX_ErrorInvalidComponent, OMX_ErrorNone, OMX_IndexParamPortSummary, OMX_VERSION, OMX_COMPONENTTYPE::pApplicationPrivate, IL_GET_EXECUTE_T::param, IL_GET_RESPONSE_T::param, OMX_COMPONENTTYPE::pComponentPrivate, VC_PRIVATE_PORT_T::port, _VC_PRIVATE_COMPONENT_T::port, OMX_PARAM_PORTSUMMARYTYPE::portDir, IL_CREATE_COMPONENT_RESPONSE_T::portDir, OMX_PARAM_PORTSUMMARYTYPE::portIndex, IL_CREATE_COMPONENT_RESPONSE_T::portIndex, _VC_PRIVATE_COMPONENT_T::reference, IL_EXECUTE_HEADER_T::reference, IL_CREATE_COMPONENT_RESPONSE_T::reference, IL_GET_EXECUTE_T::reference, OMX_PARAM_PORTSUMMARYTYPE::reqSet, vcos_malloc(), vcos_semaphore_post(), and vcos_semaphore_wait().
Referenced by OMX_GetHandle().
 {
    OMX_COMPONENTTYPE *pComp = (OMX_COMPONENTTYPE *) hComponent;
    IL_CREATE_COMPONENT_EXECUTE_T exe;
    IL_CREATE_COMPONENT_RESPONSE_T resp;
    VC_PRIVATE_COMPONENT_T *comp;
    OMX_U32 i;
    int rlen = sizeof(resp);
    if (strlen(component_name) >= sizeof(exe.name))
       return OMX_ErrorInvalidComponent;
    strcpy(exe.name, component_name);
    exe.mark = pComp;
    if(ilcs_execute_function(st->ilcs, IL_CREATE_COMPONENT, &exe, sizeof(exe), &resp, &rlen) < 0 || rlen != sizeof(resp))
       return OMX_ErrorHardware;
    if (resp.err != OMX_ErrorNone)
       return resp.err;
    comp = vcos_malloc(sizeof(VC_PRIVATE_COMPONENT_T) + (sizeof(VC_PRIVATE_PORT_T) * resp.numPorts), "ILCS Host Comp");
    if (!comp)
    {
       IL_EXECUTE_HEADER_T dexe;
       IL_RESPONSE_HEADER_T dresp;
       int dlen = sizeof(dresp);
       dexe.reference = resp.reference;
       ilcs_execute_function(st->ilcs, IL_COMPONENT_DEINIT, &dexe, sizeof(dexe), &dresp, &dlen);
       return OMX_ErrorInsufficientResources;
    }
    memset(comp, 0, sizeof(VC_PRIVATE_COMPONENT_T) + (sizeof(VC_PRIVATE_PORT_T) * resp.numPorts));
    comp->reference = resp.reference;
    comp->comp = pComp;
    comp->numPorts = resp.numPorts;
    comp->port = (VC_PRIVATE_PORT_T *) ((unsigned char *) comp + sizeof(VC_PRIVATE_COMPONENT_T));
    for (i=0; i<comp->numPorts; i++)
    {
       if (i && !(i&0x1f))
       {
          IL_GET_EXECUTE_T gexe;
          IL_GET_RESPONSE_T gresp;
          OMX_PARAM_PORTSUMMARYTYPE *summary;
          int glen = sizeof(gresp);
          gexe.reference = comp->reference;
          gexe.index = OMX_IndexParamPortSummary;
          summary = (OMX_PARAM_PORTSUMMARYTYPE *) &gexe.param;
          summary->nSize = sizeof(OMX_PARAM_PORTSUMMARYTYPE);
          summary->nVersion.nVersion = OMX_VERSION;
          summary->reqSet = i>>5;
          ilcs_execute_function(st->ilcs, IL_GET_PARAMETER, &gexe,
                                sizeof(OMX_PARAM_PORTSUMMARYTYPE)+IL_GET_EXECUTE_HEADER_SIZE,
                                &gresp, &glen);
          summary = (OMX_PARAM_PORTSUMMARYTYPE *) &gresp.param;
          resp.portDir = summary->portDir;
          memcpy(resp.portIndex, summary->portIndex, sizeof(OMX_U32) * 32);
       }
       comp->port[i].port = resp.portIndex[i&0x1f];
       comp->port[i].dir = ((resp.portDir >> (i&0x1f)) & 1) ? OMX_DirOutput : OMX_DirInput;
    }
    vcos_semaphore_wait(&st->component_lock);
    // insert into head of list
    comp->next = st->component_list;
    st->component_list = comp;
    vcos_semaphore_post(&st->component_lock);
    pComp->pComponentPrivate = comp;
    pComp->pApplicationPrivate = st;
    pComp->GetComponentVersion = vcil_out_GetComponentVersion;
    pComp->ComponentDeInit = vcil_out_ComponentDeInit;
    pComp->SetCallbacks = vcil_out_SetCallbacks;
    pComp->GetState = vcil_out_GetState;
    pComp->GetParameter = vcil_out_GetParameter;
    pComp->SetParameter = vcil_out_SetParameter;
    pComp->GetConfig = vcil_out_GetConfig;
    pComp->SetConfig = vcil_out_SetConfig;
    pComp->SendCommand = vcil_out_SendCommand;
    pComp->UseBuffer = vcil_out_UseBuffer;
    pComp->AllocateBuffer = vcil_out_AllocateBuffer;
    pComp->FreeBuffer = vcil_out_FreeBuffer;
    pComp->EmptyThisBuffer = vcil_out_EmptyThisBuffer;
    pComp->FillThisBuffer = vcil_out_FillThisBuffer;
    pComp->ComponentTunnelRequest = vcil_out_ComponentTunnelRequest;
    pComp->GetExtensionIndex = vcil_out_GetExtensionIndex;
    pComp->UseEGLImage = vcil_out_UseEGLImage;
    pComp->ComponentRoleEnum = vcil_out_ComponentRoleEnum;
    return resp.err;
 }
vcil_out_empty_buffer_done()
VCHPRE_ void VCHPOST_ vcil_out_empty_buffer_done (ILCS_COMMON_T * st, void * call, int clen, void * resp, int * rlen)
Definition at line 873 of file vcilcs_out.c.
References IL_PASS_BUFFER_EXECUTE_T::bufferHeader, _VC_PRIVATE_COMPONENT_T::callback_state, _VC_PRIVATE_COMPONENT_T::callbacks, OMX_CALLBACKTYPE::EmptyBufferDone, OMX_BUFFERHEADERTYPE::pAppPrivate, OMX_BUFFERHEADERTYPE::pBuffer, OMX_COMPONENTTYPE::pComponentPrivate, OMX_BUFFERHEADERTYPE::pInputPortPrivate, OMX_BUFFERHEADERTYPE::pOutputPortPrivate, OMX_BUFFERHEADERTYPE::pPlatformPrivate, IL_PASS_BUFFER_EXECUTE_T::reference, and vcos_assert.
 {
    IL_PASS_BUFFER_EXECUTE_T *exe = call;
    OMX_COMPONENTTYPE *pComp = exe->reference;
    VC_PRIVATE_COMPONENT_T *comp = (VC_PRIVATE_COMPONENT_T *) pComp->pComponentPrivate;
    OMX_BUFFERHEADERTYPE *pHeader = exe->bufferHeader.pOutputPortPrivate;
    OMX_U8 *pBuffer = pHeader->pBuffer;
    OMX_PTR *pAppPrivate = pHeader->pAppPrivate;
    OMX_PTR *pPlatformPrivate = pHeader->pPlatformPrivate;
    OMX_PTR *pInputPortPrivate = pHeader->pInputPortPrivate;
    OMX_PTR *pOutputPortPrivate = pHeader->pOutputPortPrivate;
    memcpy(pHeader, &exe->bufferHeader, sizeof(OMX_BUFFERHEADERTYPE));
    pHeader->pBuffer = pBuffer;
    pHeader->pAppPrivate = pAppPrivate;
    pHeader->pPlatformPrivate = pPlatformPrivate;
    pHeader->pInputPortPrivate = pInputPortPrivate;
    pHeader->pOutputPortPrivate = pOutputPortPrivate;
    *rlen = 0;
    vcos_assert(comp->callbacks.EmptyBufferDone);
    comp->callbacks.EmptyBufferDone(pComp, comp->callback_state, pHeader);
 }
vcil_out_event_handler()
VCHPRE_ void VCHPOST_ vcil_out_event_handler (ILCS_COMMON_T * st, void * call, int clen, void * resp, int * rlen)
Definition at line 860 of file vcilcs_out.c.
References _VC_PRIVATE_COMPONENT_T::callback_state, _VC_PRIVATE_COMPONENT_T::callbacks, IL_EVENT_HANDLER_EXECUTE_T::data1, IL_EVENT_HANDLER_EXECUTE_T::data2, IL_EVENT_HANDLER_EXECUTE_T::event, IL_EVENT_HANDLER_EXECUTE_T::eventdata, OMX_CALLBACKTYPE::EventHandler, OMX_COMPONENTTYPE::pComponentPrivate, IL_EVENT_HANDLER_EXECUTE_T::reference, and vcos_assert.
 {
    IL_EVENT_HANDLER_EXECUTE_T *exe = call;
    OMX_COMPONENTTYPE *pComp = exe->reference;
    VC_PRIVATE_COMPONENT_T *comp = (VC_PRIVATE_COMPONENT_T *) pComp->pComponentPrivate;
    *rlen = 0;
    vcos_assert(comp->callbacks.EventHandler);
    comp->callbacks.EventHandler(pComp, comp->callback_state, exe->event, exe->data1, exe->data2, exe->eventdata);
 }
vcil_out_fill_buffer_done()
VCHPRE_ void VCHPOST_ vcil_out_fill_buffer_done (ILCS_COMMON_T * st, void * call, int clen, void * resp, int * rlen)
Definition at line 901 of file vcilcs_out.c.
References _VC_PRIVATE_COMPONENT_T::callback_state, _VC_PRIVATE_COMPONENT_T::callbacks, OMX_CALLBACKTYPE::FillBufferDone, ILCS_COMMON_T::ilcs, ilcs_receive_buffer(), OMX_COMPONENTTYPE::pComponentPrivate, and vc_assert.
 {
    OMX_COMPONENTTYPE *pComp;
    VC_PRIVATE_COMPONENT_T *comp;
    OMX_BUFFERHEADERTYPE *pHeader;
    pHeader = ilcs_receive_buffer(st->ilcs, call, clen, &pComp);
    *rlen = 0;
    if(pHeader)
    {
       comp = (VC_PRIVATE_COMPONENT_T *) pComp->pComponentPrivate;
       vc_assert(comp->callbacks.FillBufferDone);
       comp->callbacks.FillBufferDone(pComp, comp->callback_state, pHeader);
    }
 }
vcil_out_get_debug_information()
VCHPRE_ OMX_ERRORTYPE VCHPOST_ vcil_out_get_debug_information (ILCS_COMMON_T * st, OMX_STRING debugInfo, OMX_S32 * pLen)
Definition at line 743 of file vcilcs_out.c.
References IL_GET_DEBUG_INFORMATION, ILCS_COMMON_T::ilcs, ilcs_execute_function(), IL_GET_DEBUG_INFORMATION_EXECUTE_T::len, OMX_ErrorHardware, and OMX_ErrorNone.
Referenced by OMX_GetDebugInformation().
 {
    IL_GET_DEBUG_INFORMATION_EXECUTE_T exe;
    exe.len = *pLen;
    if(ilcs_execute_function(st->ilcs, IL_GET_DEBUG_INFORMATION, &exe, sizeof(exe), debugInfo, (int *) pLen) < 0)
       return OMX_ErrorHardware;
    return OMX_ErrorNone;
 }
vcilcs_config()
VCHPRE_ void VCHPOST_ vcilcs_config (ILCS_CONFIG_T * config)
Definition at line 113 of file vcilcs_common.c.
References ILCS_CONFIG_T::fns.
 {
    config->fns = vcilcs_fns;
    config->ilcs_common_init = vcilcs_common_init;
    config->ilcs_common_deinit = vcilcs_common_deinit;
    config->ilcs_thread_init = vcilcs_thread_init;
    config->ilcs_mem_lock = vcilcs_mem_lock;
    config->ilcs_mem_unlock = vcilcs_mem_unlock;
 }