VideoCore Library: interface/mmal/openmaxil/mmalomx_registry.h File Reference
mmalomx_registry.h File Reference
Macros
#define MMALOMX_COMPONENT_PREFIX "OMX.brcm."
Functions
int mmalomx_registry_find_component (const char *name)
const char * mmalomx_registry_component_mmal (int id)
MMALOMX_ROLE_T mmalomx_registry_component_roles (int id, unsigned int index)
MMAL_BOOL_T mmalomx_registry_component_supports_role (int id, MMALOMX_ROLE_T role)
const char * mmalomx_registry_component_name (int index, const char **prefix)
Detailed Description
OpenMAX IL adaptation layer for MMAL - Registry of components
Definition in file mmalomx_registry.h.
Macro Definition Documentation
MMALOMX_COMPONENT_PREFIX
#define MMALOMX_COMPONENT_PREFIX "OMX.brcm."
Definition at line 32 of file mmalomx_registry.h.
Referenced by mmalomx_parameter_extension_index_get().
Function Documentation
mmalomx_registry_component_mmal()
const char* mmalomx_registry_component_mmal (int id)
Definition at line 110 of file mmalomx_registry.c.
References MMAL_COUNTOF.
Referenced by OMX_GetHandle().
 {
    if (id >= (int)MMAL_COUNTOF(mmalomx_components) || id < 0)
       id = MMAL_COUNTOF(mmalomx_components) - 1;
    return mmalomx_components[id].mmal;
 }
mmalomx_registry_component_name()
const char* mmalomx_registry_component_name (int index, const char ** prefix)
Definition at line 146 of file mmalomx_registry.c.
References MMAL_COUNTOF.
Referenced by OMX_ComponentNameEnum().
 {
    if (id >= (int)MMAL_COUNTOF(mmalomx_components) || id < 0)
       id = MMAL_COUNTOF(mmalomx_components) - 1;
    if (prefix)
    {
       *prefix = mmalomx_components[id].omx_prefix;
       if (!*prefix)
          *prefix = MMALOMX_COMPONENT_PREFIX;
    }
    return mmalomx_components[id].omx;
 }
mmalomx_registry_component_roles()
MMALOMX_ROLE_T mmalomx_registry_component_roles (int id, unsigned int index)
Definition at line 118 of file mmalomx_registry.c.
References MMAL_COUNTOF.
Referenced by OMX_GetRolesOfComponent().
 {
    unsigned int i;
    if (id >= (int)MMAL_COUNTOF(mmalomx_components) || id < 0)
       id = MMAL_COUNTOF(mmalomx_components) - 1;
    for (i = 0; i < index; i++)
       if (mmalomx_components[id].roles[i] == MMALOMX_ROLE_UNDEFINED)
          break;
    return mmalomx_components[id].roles[i];
 }
mmalomx_registry_component_supports_role()
MMAL_BOOL_T mmalomx_registry_component_supports_role (int id, MMALOMX_ROLE_T role)
Definition at line 132 of file mmalomx_registry.c.
References MMAL_COUNTOF.
Referenced by mmalomx_role_set().
 {
    unsigned int i;
    if (id >= (int)MMAL_COUNTOF(mmalomx_components) || id < 0)
       id = MMAL_COUNTOF(mmalomx_components) - 1;
    for (i = 0; mmalomx_components[id].roles[i] != MMALOMX_ROLE_UNDEFINED; i++)
       if (mmalomx_components[id].roles[i] == role)
          return MMAL_TRUE;
    return MMAL_FALSE;
 }
mmalomx_registry_find_component()
int mmalomx_registry_find_component (const char * name)
Definition at line 87 of file mmalomx_registry.c.
Referenced by OMX_GetHandle(), and OMX_GetRolesOfComponent().
 {
    int i, prefix_size;
    const char *prefix;
    for (i = 0; mmalomx_components[i].omx; i++)
    {
       /* Check the prefix first */
       prefix = mmalomx_components[i].omx_prefix;
       if (!prefix)
          prefix = MMALOMX_COMPONENT_PREFIX;
       prefix_size = strlen(prefix);
       if (strncmp(name, prefix, prefix_size))
          continue;
       /* Check the rest of the name */
       if (!strcmp(name + prefix_size, mmalomx_components[i].omx))
          break;
    }
    return mmalomx_components[i].mmal ? i : -1;
 }