VideoCore Library: Buffer headers
Buffer headers
Classes
struct MMAL_BUFFER_HEADER_VIDEO_SPECIFIC_T
union MMAL_BUFFER_HEADER_TYPE_SPECIFIC_T
struct MMAL_BUFFER_HEADER_T
Typedefs
typedef struct MMAL_BUFFER_HEADER_T MMAL_BUFFER_HEADER_T
typedef MMAL_BOOL_T(* MMAL_BH_PRE_RELEASE_CB_T) (MMAL_BUFFER_HEADER_T *header, void *userdata)
Functions
void mmal_buffer_header_acquire (MMAL_BUFFER_HEADER_T *header)
void mmal_buffer_header_reset (MMAL_BUFFER_HEADER_T *header)
void mmal_buffer_header_release (MMAL_BUFFER_HEADER_T *header)
void mmal_buffer_header_release_continue (MMAL_BUFFER_HEADER_T *header)
void mmal_buffer_header_pre_release_cb_set (MMAL_BUFFER_HEADER_T *header, MMAL_BH_PRE_RELEASE_CB_T cb, void *userdata)
MMAL_STATUS_T mmal_buffer_header_replicate (MMAL_BUFFER_HEADER_T *dest, MMAL_BUFFER_HEADER_T *src)
MMAL_STATUS_T mmal_buffer_header_mem_lock (MMAL_BUFFER_HEADER_T *header)
void mmal_buffer_header_mem_unlock (MMAL_BUFFER_HEADER_T *header)
Buffer header flags
The following flags describe properties of a buffer header
#define MMAL_BUFFER_HEADER_FLAG_EOS (1<<0)
#define MMAL_BUFFER_HEADER_FLAG_FRAME_START (1<<1)
#define MMAL_BUFFER_HEADER_FLAG_FRAME_END (1<<2)
#define MMAL_BUFFER_HEADER_FLAG_FRAME (MMAL_BUFFER_HEADER_FLAG_FRAME_START|MMAL_BUFFER_HEADER_FLAG_FRAME_END)
#define MMAL_BUFFER_HEADER_FLAG_KEYFRAME (1<<3)
#define MMAL_BUFFER_HEADER_FLAG_DISCONTINUITY (1<<4)
#define MMAL_BUFFER_HEADER_FLAG_CONFIG (1<<5)
#define MMAL_BUFFER_HEADER_FLAG_ENCRYPTED (1<<6)
#define MMAL_BUFFER_HEADER_FLAG_CODECSIDEINFO (1<<7)
#define MMAL_BUFFER_HEADER_FLAGS_SNAPSHOT (1<<8)
#define MMAL_BUFFER_HEADER_FLAG_CORRUPTED (1<<9)
#define MMAL_BUFFER_HEADER_FLAG_TRANSMISSION_FAILED (1<<10)
#define MMAL_BUFFER_HEADER_FLAG_DECODEONLY (1<<11)
#define MMAL_BUFFER_HEADER_FLAG_NAL_END (1<<12)
#define MMAL_BUFFER_HEADER_FLAG_USER0 (1<<28)
#define MMAL_BUFFER_HEADER_FLAG_USER1 (1<<29)
#define MMAL_BUFFER_HEADER_FLAG_USER2 (1<<30)
#define MMAL_BUFFER_HEADER_FLAG_USER3 (1<<31)
Video buffer header flags
The following flags describe properties of a video buffer header. As there is no collision with the MMAL_BUFFER_HEADER_FLAGS_ defines, these flags will also be present in the MMAL_BUFFER_HEADER_T flags field.
#define MMAL_BUFFER_HEADER_FLAG_FORMAT_SPECIFIC_START_BIT 16
#define MMAL_BUFFER_HEADER_FLAG_FORMAT_SPECIFIC_START (1<<MMAL_BUFFER_HEADER_FLAG_FORMAT_SPECIFIC_START_BIT)
#define MMAL_BUFFER_HEADER_VIDEO_FLAG_INTERLACED (MMAL_BUFFER_HEADER_FLAG_FORMAT_SPECIFIC_START<<0)
#define MMAL_BUFFER_HEADER_VIDEO_FLAG_TOP_FIELD_FIRST (MMAL_BUFFER_HEADER_FLAG_FORMAT_SPECIFIC_START<<1)
#define MMAL_BUFFER_HEADER_VIDEO_FLAG_DISPLAY_EXTERNAL (MMAL_BUFFER_HEADER_FLAG_FORMAT_SPECIFIC_START<<3)
#define MMAL_BUFFER_HEADER_VIDEO_FLAG_PROTECTED (MMAL_BUFFER_HEADER_FLAG_FORMAT_SPECIFIC_START<<4)
#define MMAL_BUFFER_HEADER_VIDEO_FLAG_COLUMN_LOG2_SHIFT (MMAL_BUFFER_HEADER_FLAG_FORMAT_SPECIFIC_START_BIT+8)
#define MMAL_BUFFER_HEADER_VIDEO_FLAG_COLUMN_LOG2_MASK (0xF<<MMAL_BUFFER_HEADER_VIDEO_FLAG_COLUMN_LOG2_SHIFT)
Detailed Description
Definition of a buffer header and its associated API. Buffer headers are the basic element used to pass data and information between different parts of the system. They are passed to components via ports and sent back to the client using a callback mechanism.
Macro Definition Documentation
MMAL_BUFFER_HEADER_FLAG_CODECSIDEINFO
#define MMAL_BUFFER_HEADER_FLAG_CODECSIDEINFO (1<<7)
Signals a buffer containing side information
Definition at line 124 of file mmal_buffer.h.
Referenced by mmalil_buffer_flags_to_mmal(), and mmalil_buffer_flags_to_omx().
MMAL_BUFFER_HEADER_FLAG_CONFIG
#define MMAL_BUFFER_HEADER_FLAG_CONFIG (1<<5)
Signals a buffer containing some kind of config data for the component (e.g. codec config data)
Definition at line 120 of file mmal_buffer.h.
Referenced by mmalil_buffer_flags_to_mmal(), and mmalil_buffer_flags_to_omx().
MMAL_BUFFER_HEADER_FLAG_CORRUPTED
#define MMAL_BUFFER_HEADER_FLAG_CORRUPTED (1<<9)
Signals a buffer which contains data known to be corrupted
Definition at line 128 of file mmal_buffer.h.
Referenced by mmalil_buffer_flags_to_mmal(), and mmalil_buffer_flags_to_omx().
MMAL_BUFFER_HEADER_FLAG_DECODEONLY
#define MMAL_BUFFER_HEADER_FLAG_DECODEONLY (1<<11)
Signals the output buffer won't be used, just update reference frames
Definition at line 132 of file mmal_buffer.h.
Referenced by mmalil_buffer_flags_to_mmal(), and mmalil_buffer_flags_to_omx().
MMAL_BUFFER_HEADER_FLAG_DISCONTINUITY
#define MMAL_BUFFER_HEADER_FLAG_DISCONTINUITY (1<<4)
Signals a discontinuity in the stream of data (e.g. after a seek). Can be used for instance by a decoder to reset its state
Definition at line 117 of file mmal_buffer.h.
Referenced by mmalil_buffer_flags_to_mmal(), and mmalil_buffer_flags_to_omx().
MMAL_BUFFER_HEADER_FLAG_ENCRYPTED
#define MMAL_BUFFER_HEADER_FLAG_ENCRYPTED (1<<6)
Signals an encrypted payload
Definition at line 122 of file mmal_buffer.h.
MMAL_BUFFER_HEADER_FLAG_EOS
#define MMAL_BUFFER_HEADER_FLAG_EOS (1<<0)
Signals that the current payload is the end of the stream of data
Definition at line 106 of file mmal_buffer.h.
Referenced by mmal_encode_test(), mmalil_buffer_flags_to_mmal(), and mmalil_buffer_flags_to_omx().
MMAL_BUFFER_HEADER_FLAG_FORMAT_SPECIFIC_START
#define MMAL_BUFFER_HEADER_FLAG_FORMAT_SPECIFIC_START (1<<MMAL_BUFFER_HEADER_FLAG_FORMAT_SPECIFIC_START_BIT)
Definition at line 149 of file mmal_buffer.h.
MMAL_BUFFER_HEADER_FLAG_FORMAT_SPECIFIC_START_BIT
#define MMAL_BUFFER_HEADER_FLAG_FORMAT_SPECIFIC_START_BIT 16
Definition at line 148 of file mmal_buffer.h.
MMAL_BUFFER_HEADER_FLAG_FRAME
#define MMAL_BUFFER_HEADER_FLAG_FRAME (MMAL_BUFFER_HEADER_FLAG_FRAME_START|MMAL_BUFFER_HEADER_FLAG_FRAME_END)
Signals that the current payload contains only complete frames (1 or more)
Definition at line 112 of file mmal_buffer.h.
MMAL_BUFFER_HEADER_FLAG_FRAME_END
#define MMAL_BUFFER_HEADER_FLAG_FRAME_END (1<<2)
Signals that the end of the current payload ends a frame
Definition at line 110 of file mmal_buffer.h.
Referenced by mmalil_buffer_flags_to_mmal(), and mmalil_buffer_flags_to_omx().
MMAL_BUFFER_HEADER_FLAG_FRAME_START
#define MMAL_BUFFER_HEADER_FLAG_FRAME_START (1<<1)
Signals that the start of the current payload starts a frame
Definition at line 108 of file mmal_buffer.h.
MMAL_BUFFER_HEADER_FLAG_KEYFRAME
#define MMAL_BUFFER_HEADER_FLAG_KEYFRAME (1<<3)
Signals that the current payload is a keyframe (i.e. self decodable)
Definition at line 114 of file mmal_buffer.h.
Referenced by mmalil_buffer_flags_to_mmal(), and mmalil_buffer_flags_to_omx().
MMAL_BUFFER_HEADER_FLAG_NAL_END
#define MMAL_BUFFER_HEADER_FLAG_NAL_END (1<<12)
Signals that the end of the current payload ends a NAL
Definition at line 134 of file mmal_buffer.h.
Referenced by mmalil_buffer_flags_to_mmal(), and mmalil_buffer_flags_to_omx().
MMAL_BUFFER_HEADER_FLAG_TRANSMISSION_FAILED
#define MMAL_BUFFER_HEADER_FLAG_TRANSMISSION_FAILED (1<<10)
Signals that a buffer failed to be transmitted
Definition at line 130 of file mmal_buffer.h.
MMAL_BUFFER_HEADER_FLAG_USER0
#define MMAL_BUFFER_HEADER_FLAG_USER0 (1<<28)
User flags - can be passed in and will get returned
Definition at line 136 of file mmal_buffer.h.
Referenced by mmalil_buffer_flags_to_mmal(), and mmalil_buffer_flags_to_omx().
MMAL_BUFFER_HEADER_FLAG_USER1
#define MMAL_BUFFER_HEADER_FLAG_USER1 (1<<29)
Definition at line 137 of file mmal_buffer.h.
Referenced by mmalil_buffer_flags_to_mmal(), and mmalil_buffer_flags_to_omx().
MMAL_BUFFER_HEADER_FLAG_USER2
#define MMAL_BUFFER_HEADER_FLAG_USER2 (1<<30)
Definition at line 138 of file mmal_buffer.h.
Referenced by mmalil_buffer_flags_to_mmal(), and mmalil_buffer_flags_to_omx().
MMAL_BUFFER_HEADER_FLAG_USER3
#define MMAL_BUFFER_HEADER_FLAG_USER3 (1<<31)
Definition at line 139 of file mmal_buffer.h.
Referenced by mmalil_buffer_flags_to_mmal(), and mmalil_buffer_flags_to_omx().
MMAL_BUFFER_HEADER_FLAGS_SNAPSHOT
#define MMAL_BUFFER_HEADER_FLAGS_SNAPSHOT (1<<8)
Signals a buffer which is the snapshot/postview image from a stills capture
Definition at line 126 of file mmal_buffer.h.
Referenced by mmalil_buffer_flags_to_mmal(), and mmalil_buffer_flags_to_omx().
MMAL_BUFFER_HEADER_VIDEO_FLAG_COLUMN_LOG2_MASK
#define MMAL_BUFFER_HEADER_VIDEO_FLAG_COLUMN_LOG2_MASK (0xF<<MMAL_BUFFER_HEADER_VIDEO_FLAG_COLUMN_LOG2_SHIFT)
Definition at line 163 of file mmal_buffer.h.
MMAL_BUFFER_HEADER_VIDEO_FLAG_COLUMN_LOG2_SHIFT
#define MMAL_BUFFER_HEADER_VIDEO_FLAG_COLUMN_LOG2_SHIFT (MMAL_BUFFER_HEADER_FLAG_FORMAT_SPECIFIC_START_BIT+8)
27-24: If non-zero it signals the video frame is encoded in column mode, with a column width equal to 2^<masked value>="">. Zero is raster order.
Definition at line 162 of file mmal_buffer.h.
MMAL_BUFFER_HEADER_VIDEO_FLAG_DISPLAY_EXTERNAL
#define MMAL_BUFFER_HEADER_VIDEO_FLAG_DISPLAY_EXTERNAL (MMAL_BUFFER_HEADER_FLAG_FORMAT_SPECIFIC_START<<3)
19: Signals that the buffer should be displayed on external display if attached.
Definition at line 156 of file mmal_buffer.h.
MMAL_BUFFER_HEADER_VIDEO_FLAG_INTERLACED
#define MMAL_BUFFER_HEADER_VIDEO_FLAG_INTERLACED (MMAL_BUFFER_HEADER_FLAG_FORMAT_SPECIFIC_START<<0)
16: Signals an interlaced video frame
Definition at line 152 of file mmal_buffer.h.
Referenced by mmalil_buffer_flags_to_mmal(), mmalil_buffer_flags_to_omx(), mmalil_video_buffer_flags_to_mmal(), and mmalil_video_buffer_flags_to_omx().
MMAL_BUFFER_HEADER_VIDEO_FLAG_PROTECTED
#define MMAL_BUFFER_HEADER_VIDEO_FLAG_PROTECTED (MMAL_BUFFER_HEADER_FLAG_FORMAT_SPECIFIC_START<<4)
20: Signals that contents of the buffer requires copy protection.
Definition at line 158 of file mmal_buffer.h.
MMAL_BUFFER_HEADER_VIDEO_FLAG_TOP_FIELD_FIRST
#define MMAL_BUFFER_HEADER_VIDEO_FLAG_TOP_FIELD_FIRST (MMAL_BUFFER_HEADER_FLAG_FORMAT_SPECIFIC_START<<1)
17: Signals that the top field of the current interlaced frame should be displayed first
Definition at line 154 of file mmal_buffer.h.
Referenced by mmalil_buffer_flags_to_mmal(), mmalil_buffer_flags_to_omx(), mmalil_video_buffer_flags_to_mmal(), and mmalil_video_buffer_flags_to_omx().
Typedef Documentation
MMAL_BH_PRE_RELEASE_CB_T
typedef MMAL_BOOL_T(* MMAL_BH_PRE_RELEASE_CB_T) (MMAL_BUFFER_HEADER_T *header, void *userdata)
Buffer header pre-release callback. The callback is invoked just before a buffer is released back into a pool. This is used by clients who need to trigger additional actions before the buffer can finally be released (e.g. wait for a bulk transfer to complete).
The callback should return TRUE if the buffer release need to be post-poned.
Parameters
header buffer header about to be released
userdata user-specific data
Returns
TRUE if the buffer should not be released
Definition at line 217 of file mmal_buffer.h.
MMAL_BUFFER_HEADER_T
typedef struct MMAL_BUFFER_HEADER_T MMAL_BUFFER_HEADER_T
Definition of the buffer header structure. A buffer header does not directly carry the data to be passed to a component but instead it references the actual data using a pointer (and an associated length). It also contains an internal area which can be used to store command to be associated with the external data.
Function Documentation
mmal_buffer_header_acquire()
void mmal_buffer_header_acquire (MMAL_BUFFER_HEADER_T * header)
Acquire a buffer header. Acquiring a buffer header increases a reference counter on it and makes sure that the buffer header won't be recycled until all the references to it are gone. This is useful for instance if a component needs to return a buffer header but still needs access to it for some internal processing (e.g. reference frames in video codecs).
Parameters
header buffer header to acquire
Acquire a buffer header
Definition at line 38 of file mmal_buffer.c.
References LOG_TRACE, MMAL_BUFFER_HEADER_T::priv, and MMAL_BUFFER_HEADER_PRIVATE_T::refcount.
Referenced by mmal_buffer_header_replicate(), and mmal_connection_event_format_changed().
 {
 #ifdef ENABLE_MMAL_EXTRA_LOGGING
    LOG_TRACE("%p (%i)", header, (int)header->priv->refcount+1);
 #endif
    header->priv->refcount++;
 }
mmal_buffer_header_mem_lock()
MMAL_STATUS_T mmal_buffer_header_mem_lock (MMAL_BUFFER_HEADER_T * header)
Lock the data buffer contained in the buffer header in memory. This call does nothing on all platforms except VideoCore where it is needed to pin a buffer in memory before any access to it.
Parameters
header buffer header to lock
Lock the data buffer contained in the buffer header
Definition at line 157 of file mmal_buffer.c.
References MMAL_BUFFER_HEADER_T::data, mem_lock(), MMAL_EINVAL, MMAL_PARAM_UNUSED, MMAL_SUCCESS, MMAL_BUFFER_HEADER_PRIVATE_T::payload_handle, and MMAL_BUFFER_HEADER_T::priv.
 {
 #ifdef __VIDEOCORE__
    uint8_t *data = mem_lock((MEM_HANDLE_T)header->data);
    if (!data)
       return MMAL_EINVAL;
    header->priv->payload_handle = (void *)header->data;
    header->data = data;
 #else
    MMAL_PARAM_UNUSED(header);
 #endif
    return MMAL_SUCCESS;
 }
mmal_buffer_header_mem_unlock()
void mmal_buffer_header_mem_unlock (MMAL_BUFFER_HEADER_T * header)
Unlock the data buffer contained in the buffer header. This call does nothing on all platforms except VideoCore where it is needed to un-pin a buffer in memory after any access to it.
Parameters
header buffer header to unlock
Unlock the data buffer contained in the buffer header
Definition at line 173 of file mmal_buffer.c.
References MMAL_BUFFER_HEADER_T::data, mem_unlock(), MMAL_PARAM_UNUSED, MMAL_BUFFER_HEADER_PRIVATE_T::payload_handle, and MMAL_BUFFER_HEADER_T::priv.
 {
 #ifdef __VIDEOCORE__
    mem_unlock((MEM_HANDLE_T)header->priv->payload_handle);
    header->data = header->priv->payload_handle;
 #else
    MMAL_PARAM_UNUSED(header);
 #endif
 }
mmal_buffer_header_pre_release_cb_set()
void mmal_buffer_header_pre_release_cb_set (MMAL_BUFFER_HEADER_T * header, MMAL_BH_PRE_RELEASE_CB_T cb, void * userdata)
Set a buffer header pre-release callback. If the callback is NULL, the buffer will be released back into the pool immediately as usual.
Parameters
header buffer header to associate callback with
cb pre-release callback to invoke
userdata user-specific data
Set a pre-release callback for a buffer header
Definition at line 184 of file mmal_buffer.c.
References MMAL_BUFFER_HEADER_PRIVATE_T::pf_pre_release, MMAL_BUFFER_HEADER_PRIVATE_T::pre_release_userdata, and MMAL_BUFFER_HEADER_T::priv.
Referenced by mmal_pool_pre_release_callback_set().
 {
    header->priv->pf_pre_release = cb;
    header->priv->pre_release_userdata = userdata;
 }
mmal_buffer_header_release()
void mmal_buffer_header_release (MMAL_BUFFER_HEADER_T * header)
Release a buffer header. Releasing a buffer header will decrease its reference counter and when no more references are left, the buffer header will be recycled by calling its 'release' callback function.
If a pre-release callback is set (MMAL_BH_PRE_RELEASE_CB_T), this will be invoked before calling the buffer's release callback and potentially postpone buffer recycling. Once pre-release is complete the buffer header is recycled with mmal_buffer_header_release_continue.
Parameters
header buffer header to release
Release a buffer header
Definition at line 57 of file mmal_buffer.c.
References LOG_TRACE, mmal_buffer_header_release_continue(), MMAL_BUFFER_HEADER_PRIVATE_T::pf_pre_release, MMAL_BUFFER_HEADER_PRIVATE_T::pre_release_userdata, MMAL_BUFFER_HEADER_T::priv, and MMAL_BUFFER_HEADER_PRIVATE_T::refcount.
Referenced by default_camera_control_callback(), mmal_buffer_header_release_continue(), mmal_connection_disable(), mmal_connection_event_format_changed(), mmal_event_forward(), mmal_port_event_get(), mmal_port_event_send(), mmal_wrapper_port_disable(), and mmalomx_command_dequeue().
 {
 #ifdef ENABLE_MMAL_EXTRA_LOGGING
    LOG_TRACE("%p (%i)", header, (int)header->priv->refcount-1);
 #endif
    if(--header->priv->refcount != 0)
       return;
    if (header->priv->pf_pre_release)
    {
       if (header->priv->pf_pre_release(header, header->priv->pre_release_userdata))
          return; /* delay releasing the buffer */
    }
    mmal_buffer_header_release_continue(header);
 }
mmal_buffer_header_release_continue()
void mmal_buffer_header_release_continue (MMAL_BUFFER_HEADER_T * header)
Continue the buffer header release process. This should be called to complete buffer header recycling once all pre-release activity has been completed.
Parameters
header buffer header to release
Finalise buffer release following a pre-release event
Definition at line 75 of file mmal_buffer.c.
References mmal_buffer_header_release(), mmal_buffer_header_reset(), MMAL_BUFFER_HEADER_PRIVATE_T::pf_release, MMAL_BUFFER_HEADER_T::priv, and MMAL_BUFFER_HEADER_PRIVATE_T::reference.
Referenced by mmal_buffer_header_release().
 {
    mmal_buffer_header_reset(header);
    if (header->priv->reference)
       mmal_buffer_header_release(header->priv->reference);
    header->priv->reference = 0;
    header->priv->pf_release(header);
 }
mmal_buffer_header_replicate()
MMAL_STATUS_T mmal_buffer_header_replicate (MMAL_BUFFER_HEADER_T * dest, MMAL_BUFFER_HEADER_T * src)
Replicate a buffer header into another one. Replicating a buffer header will not only do an exact copy of all the public fields of the buffer header (including data and alloc_size), but it will also acquire a reference to the source buffer header which will only be released once the replicate has been released.
Parameters
dest buffer header into which to replicate
src buffer header to use as the source for the replication
Returns
MMAL_SUCCESS on success
Replicate a buffer header
Definition at line 85 of file mmal_buffer.c.
References MMAL_BUFFER_HEADER_T::alloc_size, MMAL_BUFFER_HEADER_T::cmd, MMAL_BUFFER_HEADER_T::data, MMAL_BUFFER_HEADER_T::dts, MMAL_BUFFER_HEADER_T::flags, MMAL_BUFFER_HEADER_T::length, LOG_TRACE, mmal_buffer_header_acquire(), MMAL_EINVAL, MMAL_SUCCESS, MMAL_BUFFER_HEADER_T::offset, MMAL_BUFFER_HEADER_T::priv, MMAL_BUFFER_HEADER_T::pts, MMAL_BUFFER_HEADER_PRIVATE_T::reference, and MMAL_BUFFER_HEADER_T::type.
 {
 #ifdef ENABLE_MMAL_EXTRA_LOGGING
    LOG_TRACE("dest: %p src: %p", dest, src);
 #endif
    if (!dest || !src || dest->priv->reference)
       return MMAL_EINVAL;
    mmal_buffer_header_acquire(src);
    dest->priv->reference = src;
    /* Copy all the relevant fields */
    dest->cmd        = src->cmd;
    dest->alloc_size = src->alloc_size;
    dest->data       = src->data;
    dest->offset     = src->offset;
    dest->length     = src->length;
    dest->flags      = src->flags;
    dest->pts        = src->pts;
    dest->dts        = src->dts;
    *dest->type      = *src->type;
    return MMAL_SUCCESS;
 }
mmal_buffer_header_reset()
void mmal_buffer_header_reset (MMAL_BUFFER_HEADER_T * header)
Reset a buffer header. Resets all header variables to default values.
Parameters
header buffer header to reset
Reset a buffer header
Definition at line 47 of file mmal_buffer.c.
References MMAL_BUFFER_HEADER_T::dts, MMAL_BUFFER_HEADER_T::flags, MMAL_BUFFER_HEADER_T::length, MMAL_TIME_UNKNOWN, MMAL_BUFFER_HEADER_T::offset, and MMAL_BUFFER_HEADER_T::pts.
Referenced by mmal_buffer_header_release_continue().
 {
    header->length = 0;
    header->offset = 0;
    header->flags = 0;
    header->pts = MMAL_TIME_UNKNOWN;
    header->dts = MMAL_TIME_UNKNOWN;
 }