VideoCore Library: containers/io/io_http.c File Reference
io_http.c File Reference
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <ctype.h>
#include "containers/containers.h"
#include "containers/core/containers_common.h"
#include "containers/core/containers_io.h"
#include "containers/core/containers_uri.h"
#include "containers/core/containers_logging.h"
#include "containers/core/containers_list.h"
#include "containers/core/containers_utils.h"
#include "containers/net/net_sockets.h"
Classes
struct http_header_tag
struct VC_CONTAINER_IO_MODULE_T
Macros
#define ENABLE_HTTP_EXTRA_LOGGING 0
#define IO_HTTP_DEFAULT_PORT "80"
#define COMMS_BUFFER_SIZE 4000
#define HTTP_URI_LENGTH_MAX 1024
#define HEADER_LIST_INITIAL_CAPACITY 16
#define HTTP_REQUEST_LINE_FORMAT "%s %s HTTP/1.1\r\nHost: %s\r\n"
#define HTTP_RANGE_REQUEST "Range: bytes=%"PRId64"-%"PRId64"\r\n"
#define TRAILING_HEADERS_FORMAT "User-Agent: Broadcom/1.0\r\n\r\n"
#define HTTP_MAJOR_VERSION 1
#define HTTP_MINOR_VERSION 1
#define HTTP_STATUS_OK 200
#define HTTP_STATUS_PARTIAL_CONTENT 206
HTTP methods, used as the first item in the request line
#define GET_METHOD "GET"
#define HEAD_METHOD "HEAD"
Names of headers used by the code
#define CONTENT_LENGTH_NAME "Content-Length"
#define CONTENT_BASE_NAME "Content-Base"
#define CONTENT_LOCATION_NAME "Content-Location"
#define ACCEPT_RANGES_NAME "Accept-Ranges"
#define CONNECTION_NAME "Connection"
Typedefs
typedef struct http_header_tag HTTP_HEADER_T
typedef struct VC_CONTAINER_IO_MODULE_T VC_CONTAINER_IO_MODULE_T
Functions
VC_CONTAINER_STATUS_T vc_container_io_http_open (VC_CONTAINER_IO_T *, const char *, VC_CONTAINER_IO_MODE_T)
Macro Definition Documentation
ACCEPT_RANGES_NAME
#define ACCEPT_RANGES_NAME "Accept-Ranges"
Definition at line 82 of file io_http.c.
COMMS_BUFFER_SIZE
#define COMMS_BUFFER_SIZE 4000
Space for sending requests and receiving responses
Definition at line 52 of file io_http.c.
CONNECTION_NAME
#define CONNECTION_NAME "Connection"
Definition at line 83 of file io_http.c.
CONTENT_BASE_NAME
#define CONTENT_BASE_NAME "Content-Base"
Definition at line 80 of file io_http.c.
CONTENT_LENGTH_NAME
#define CONTENT_LENGTH_NAME "Content-Length"
Definition at line 79 of file io_http.c.
CONTENT_LOCATION_NAME
#define CONTENT_LOCATION_NAME "Content-Location"
Definition at line 81 of file io_http.c.
ENABLE_HTTP_EXTRA_LOGGING
#define ENABLE_HTTP_EXTRA_LOGGING 0
Definition at line 43 of file io_http.c.
GET_METHOD
#define GET_METHOD "GET"
Definition at line 73 of file io_http.c.
HEAD_METHOD
#define HEAD_METHOD "HEAD"
Definition at line 74 of file io_http.c.
HEADER_LIST_INITIAL_CAPACITY
#define HEADER_LIST_INITIAL_CAPACITY 16
Initial capacity of header list
Definition at line 59 of file io_http.c.
Referenced by vc_container_io_http_open().
HTTP_MAJOR_VERSION
#define HTTP_MAJOR_VERSION 1
Supported HTTP major version number
Definition at line 87 of file io_http.c.
HTTP_MINOR_VERSION
#define HTTP_MINOR_VERSION 1
Supported HTTP minor version number
Definition at line 89 of file io_http.c.
HTTP_RANGE_REQUEST
#define HTTP_RANGE_REQUEST "Range: bytes=%"PRId64"-%"PRId64"\r\n"
Format of a range request
Definition at line 65 of file io_http.c.
HTTP_REQUEST_LINE_FORMAT
#define HTTP_REQUEST_LINE_FORMAT "%s %s HTTP/1.1\r\nHost: %s\r\n"
Format of the first line of an HTTP request
Definition at line 62 of file io_http.c.
HTTP_STATUS_OK
#define HTTP_STATUS_OK 200
Lowest successful status code value
Definition at line 92 of file io_http.c.
HTTP_STATUS_PARTIAL_CONTENT
#define HTTP_STATUS_PARTIAL_CONTENT 206
Definition at line 93 of file io_http.c.
HTTP_URI_LENGTH_MAX
#define HTTP_URI_LENGTH_MAX 1024
Largest allowed HTTP URI. Must be substantially smaller than COMMS_BUFFER_SIZE to allow for the headers that may be sent.
Definition at line 56 of file io_http.c.
Referenced by vc_container_io_http_open().
IO_HTTP_DEFAULT_PORT
#define IO_HTTP_DEFAULT_PORT "80"
Definition at line 49 of file io_http.c.
TRAILING_HEADERS_FORMAT
#define TRAILING_HEADERS_FORMAT "User-Agent: Broadcom/1.0\r\n\r\n"
Format string for common headers used with all request methods. Note: includes double new line to terminate headers
Definition at line 69 of file io_http.c.
Typedef Documentation
HTTP_HEADER_T
typedef struct http_header_tag HTTP_HEADER_T
VC_CONTAINER_IO_MODULE_T
typedef struct VC_CONTAINER_IO_MODULE_T VC_CONTAINER_IO_MODULE_T
Function Documentation
vc_container_io_http_open()
VC_CONTAINER_STATUS_T vc_container_io_http_open (VC_CONTAINER_IO_T * p_ctx, const char * unused, VC_CONTAINER_IO_MODE_T mode)
Definition at line 820 of file io_http.c.
References error(), VC_CONTAINER_IO_MODULE_T::header_list, HEADER_LIST_INITIAL_CAPACITY, HTTP_URI_LENGTH_MAX, VC_CONTAINER_IO_T::module, VC_CONTAINER_IO_T::uri, VC_CONTAINER_IO_T::uri_parts, VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED, VC_CONTAINER_ERROR_OUT_OF_MEMORY, VC_CONTAINER_ERROR_UNSUPPORTED_OPERATION, VC_CONTAINER_ERROR_URI_OPEN_FAILED, VC_CONTAINER_IO_MODE_WRITE, VC_CONTAINER_PARAM_UNUSED, VC_CONTAINER_SUCCESS, vc_containers_list_create(), and vc_uri_scheme().
 {
    VC_CONTAINER_STATUS_T status = VC_CONTAINER_SUCCESS;
    VC_CONTAINER_IO_MODULE_T *module = 0;
    VC_CONTAINER_PARAM_UNUSED(unused);
    /* Check the URI to see if we're dealing with an http stream */
    if (!vc_uri_scheme(p_ctx->uri_parts) ||
        strcasecmp(vc_uri_scheme(p_ctx->uri_parts), "http"))
       return VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED;
    /*
     * Some basic error checking.
     */
    if (mode == VC_CONTAINER_IO_MODE_WRITE)
    {
       status = VC_CONTAINER_ERROR_UNSUPPORTED_OPERATION;
       goto error;
    }
    if (strlen(p_ctx->uri) > HTTP_URI_LENGTH_MAX)
    {
       status = VC_CONTAINER_ERROR_URI_OPEN_FAILED;
       goto error;
    }
    module = calloc(1, sizeof(*module));
    if (!module)
    {
       status = VC_CONTAINER_ERROR_OUT_OF_MEMORY;
       goto error;
    }
    p_ctx->module = module;
    /* header_list will contain pointers into the response_buffer, so take care in re-use */
    module->header_list = vc_containers_list_create(HEADER_LIST_INITIAL_CAPACITY, sizeof(HTTP_HEADER_T),
                                            (VC_CONTAINERS_LIST_COMPARATOR_T)io_http_header_comparator);
    if (!module->header_list)
    {
       status = VC_CONTAINER_ERROR_OUT_OF_MEMORY;
       goto error;
    }
    /*
     * Make sure that we have a port number.
     */
    if (vc_uri_port(p_ctx->uri_parts) == NULL)
       vc_uri_set_port(p_ctx->uri_parts, IO_HTTP_DEFAULT_PORT);
    status = io_http_open_socket(p_ctx);
    if (status != VC_CONTAINER_SUCCESS)
       goto error;
    /*
     * Whoo hoo! Our socket is open. Now let's send a HEAD request.
     */
    status = io_http_head(p_ctx);
    if (status != VC_CONTAINER_SUCCESS)
       goto error;
    p_ctx->pf_close   = io_http_close;
    p_ctx->pf_read    = io_http_read;
    p_ctx->pf_write   = NULL;
    p_ctx->pf_control = io_http_control;
    p_ctx->pf_seek    = io_http_seek;
    p_ctx->capabilities = VC_CONTAINER_IO_CAPS_NO_CACHING;
    p_ctx->capabilities |= VC_CONTAINER_IO_CAPS_SEEK_SLOW;
    return VC_CONTAINER_SUCCESS;
 error:
    io_http_close(p_ctx);
    return status;
 }