VideoCore Library: interface/mmal/openmaxil/mmalomx_commands.c File Reference
mmalomx_commands.c File Reference
#include "mmalomx.h"
#include "mmalomx_commands.h"
#include "mmalomx_buffer.h"
#include "mmalomx_logging.h"
Classes
struct MMALOMX_STATE_TRANSITION_T
Functions
void mmalomx_commands_actions_check (MMALOMX_COMPONENT_T *component)
void mmalomx_commands_actions_signal (MMALOMX_COMPONENT_T *component)
OMX_ERRORTYPE mmalomx_command_state_set (OMX_HANDLETYPE hComponent, OMX_STATETYPE state)
OMX_ERRORTYPE mmalomx_command_port_mark (OMX_HANDLETYPE hComponent, OMX_U32 nPortIndex, OMX_PTR *pCmdData)
OMX_ERRORTYPE mmalomx_command_port_flush (OMX_HANDLETYPE hComponent, OMX_U32 nPortIndex)
OMX_ERRORTYPE mmalomx_command_port_enable (OMX_HANDLETYPE hComponent, OMX_U32 nPortIndex)
OMX_ERRORTYPE mmalomx_command_port_disable (OMX_HANDLETYPE hComponent, OMX_U32 nPortIndex)
OMX_ERRORTYPE mmalomx_command_queue (MMALOMX_COMPONENT_T *component, OMX_U32 arg1, OMX_U32 arg2)
OMX_ERRORTYPE mmalomx_command_dequeue (MMALOMX_COMPONENT_T *component, OMX_U32 *arg1, OMX_U32 *arg2)
void mmalomx_commands_actions_next (MMALOMX_COMPONENT_T *component)
Variables
MMALOMX_STATE_TRANSITION_T state_transition_table []
Function Documentation
mmalomx_command_dequeue()
OMX_ERRORTYPE mmalomx_command_dequeue (MMALOMX_COMPONENT_T * component, OMX_U32 * arg1, OMX_U32 * arg2)
Definition at line 410 of file mmalomx_commands.c.
References MMAL_BUFFER_HEADER_T::cmd, MMALOMX_COMPONENT_T::cmd_queue, mmal_buffer_header_release(), mmal_queue_get(), MMAL_BUFFER_HEADER_T::offset, OMX_ErrorNoMore, and OMX_ErrorNone.
Referenced by mmalomx_commands_actions_next().
 {
    MMAL_BUFFER_HEADER_T *cmd = mmal_queue_get(component->cmd_queue);
    if (!cmd)
       return OMX_ErrorNoMore;
    *arg1 = cmd->cmd;
    *arg2 = cmd->offset;
    mmal_buffer_header_release(cmd);
    return OMX_ErrorNone;
 }
mmalomx_command_port_disable()
OMX_ERRORTYPE mmalomx_command_port_disable (OMX_HANDLETYPE hComponent, OMX_U32 nPortIndex)
Definition at line 360 of file mmalomx_commands.c.
References MMALOMX_PORT_T::actions, MMALOMX_COMPONENT_T::cmd_thread_used, MMALOMX_PORT_T::enabled, MMAL_FALSE, MMALOMX_ACTION_CHECK_DEALLOCATED, MMALOMX_ACTION_CHECK_FLUSHED, MMALOMX_ACTION_DISABLE, MMALOMX_ACTION_FLUSH, MMALOMX_ACTION_NOTIFY_DISABLE, mmalomx_callback_event_handler(), mmalomx_commands_actions_check(), MMALOMX_LOCK_PORT, MMALOMX_UNLOCK_PORT, NULL, OMX_CommandPortDisable, OMX_ErrorNone, OMX_EventCmdComplete, OMX_StateLoaded, OMX_StateWaitForResources, MMALOMX_COMPONENT_T::ports, and MMALOMX_COMPONENT_T::state.
Referenced by mmalomx_commands_actions_next().
 {
    MMALOMX_COMPONENT_T *component = (MMALOMX_COMPONENT_T *)hComponent;
    component->ports[nPortIndex].enabled = MMAL_FALSE;
    if (component->state == OMX_StateLoaded ||
        component->state == OMX_StateWaitForResources)
    {
       mmalomx_callback_event_handler(component, OMX_EventCmdComplete, OMX_CommandPortDisable, nPortIndex, NULL);
       return OMX_ErrorNone;
    }
    MMALOMX_LOCK_PORT(component, &component->ports[nPortIndex]);
    component->ports[nPortIndex].actions =
       MMALOMX_ACTION_DISABLE|MMALOMX_ACTION_CHECK_DEALLOCATED|MMALOMX_ACTION_NOTIFY_DISABLE;
    if (component->cmd_thread_used)
       component->ports[nPortIndex].actions |=
          MMALOMX_ACTION_FLUSH|MMALOMX_ACTION_CHECK_FLUSHED;
    MMALOMX_UNLOCK_PORT(component, &component->ports[nPortIndex]);
    mmalomx_commands_actions_check(component);
    return OMX_ErrorNone;
 }
mmalomx_command_port_enable()
OMX_ERRORTYPE mmalomx_command_port_enable (OMX_HANDLETYPE hComponent, OMX_U32 nPortIndex)
Definition at line 335 of file mmalomx_commands.c.
References MMALOMX_PORT_T::actions, MMALOMX_PORT_T::enabled, MMAL_TRUE, MMALOMX_ACTION_CHECK_ALLOCATED, MMALOMX_ACTION_ENABLE, MMALOMX_ACTION_NOTIFY_ENABLE, mmalomx_callback_event_handler(), mmalomx_commands_actions_check(), MMALOMX_LOCK_PORT, MMALOMX_UNLOCK_PORT, NULL, OMX_CommandPortEnable, OMX_ErrorNone, OMX_EventCmdComplete, OMX_StateLoaded, OMX_StateWaitForResources, MMALOMX_COMPONENT_T::ports, and MMALOMX_COMPONENT_T::state.
Referenced by mmalomx_commands_actions_next().
 {
    MMALOMX_COMPONENT_T *component = (MMALOMX_COMPONENT_T *)hComponent;
    component->ports[nPortIndex].enabled = MMAL_TRUE;
    if (component->state == OMX_StateLoaded ||
        component->state == OMX_StateWaitForResources)
    {
       mmalomx_callback_event_handler(component, OMX_EventCmdComplete, OMX_CommandPortEnable, nPortIndex, NULL);
       return OMX_ErrorNone;
    }
    MMALOMX_LOCK_PORT(component, &component->ports[nPortIndex]);
    component->ports[nPortIndex].actions =
       MMALOMX_ACTION_CHECK_ALLOCATED|MMALOMX_ACTION_ENABLE|MMALOMX_ACTION_NOTIFY_ENABLE;
    MMALOMX_UNLOCK_PORT(component, &component->ports[nPortIndex]);
    mmalomx_commands_actions_check(component);
    return OMX_ErrorNone;
 }
mmalomx_command_port_flush()
OMX_ERRORTYPE mmalomx_command_port_flush (OMX_HANDLETYPE hComponent, OMX_U32 nPortIndex)
Definition at line 318 of file mmalomx_commands.c.
References MMALOMX_PORT_T::actions, MMALOMX_ACTION_CHECK_FLUSHED, MMALOMX_ACTION_FLUSH, MMALOMX_ACTION_NOTIFY_FLUSH, mmalomx_commands_actions_check(), MMALOMX_LOCK_PORT, MMALOMX_UNLOCK_PORT, OMX_ErrorNone, and MMALOMX_COMPONENT_T::ports.
Referenced by mmalomx_commands_actions_next().
 {
    MMALOMX_COMPONENT_T *component = (MMALOMX_COMPONENT_T *)hComponent;
    MMALOMX_LOCK_PORT(component, &component->ports[nPortIndex]);
    component->ports[nPortIndex].actions =
       MMALOMX_ACTION_FLUSH|MMALOMX_ACTION_CHECK_FLUSHED|MMALOMX_ACTION_NOTIFY_FLUSH;
    MMALOMX_UNLOCK_PORT(component, &component->ports[nPortIndex]);
    mmalomx_commands_actions_check(component);
    return OMX_ErrorNone;
 }
mmalomx_command_port_mark()
OMX_ERRORTYPE mmalomx_command_port_mark (OMX_HANDLETYPE hComponent, OMX_U32 nPortIndex, OMX_PTR * pCmdData)
Definition at line 295 of file mmalomx_commands.c.
References MMALOMX_PORT_T::marks, MMALOMX_PORT_T::marks_first, MMALOMX_PORT_T::marks_num, MAX_MARKS_NUM, OMX_ErrorBadPortIndex, OMX_ErrorInsufficientResources, OMX_ErrorNone, MMAL_COMPONENT_T::port, MMALOMX_COMPONENT_T::ports, and MMALOMX_COMPONENT_T::ports_num.
 {
    MMALOMX_COMPONENT_T *component = (MMALOMX_COMPONENT_T *)hComponent;
    OMX_MARKTYPE *mark = (OMX_MARKTYPE *)pCmdData;
    MMALOMX_PORT_T *port;
    if (nPortIndex >= component->ports_num)
       return OMX_ErrorBadPortIndex;
    port = &component->ports[nPortIndex];
    if (port->marks_num == MAX_MARKS_NUM)
       return OMX_ErrorInsufficientResources;
    port->marks[(port->marks_first + port->marks_num) % MAX_MARKS_NUM] = *mark;
    port->marks_num++;
    return OMX_ErrorNone;
 }
mmalomx_command_queue()
OMX_ERRORTYPE mmalomx_command_queue (MMALOMX_COMPONENT_T * component, OMX_U32 arg1, OMX_U32 arg2)
Definition at line 388 of file mmalomx_commands.c.
References MMAL_BUFFER_HEADER_T::cmd, MMALOMX_COMPONENT_T::cmd_pool, MMALOMX_COMPONENT_T::cmd_queue, LOG_ERROR, mmal_queue_get(), mmal_queue_put(), mmalomx_commands_actions_signal(), MMAL_BUFFER_HEADER_T::offset, OMX_ErrorInsufficientResources, OMX_ErrorNone, MMAL_POOL_T::queue, and vcos_verify.
 {
    MMAL_BUFFER_HEADER_T *cmd = mmal_queue_get(component->cmd_pool->queue);
    if (!vcos_verify(cmd))
    {
       LOG_ERROR("command queue too small");
       return OMX_ErrorInsufficientResources;
    }
    cmd->cmd = arg1;
    cmd->offset = arg2;
    mmal_queue_put(component->cmd_queue, cmd);
    mmalomx_commands_actions_signal(component);
    return OMX_ErrorNone;
 }
mmalomx_command_state_set()
OMX_ERRORTYPE mmalomx_command_state_set (OMX_HANDLETYPE hComponent, OMX_STATETYPE state)
Definition at line 218 of file mmalomx_commands.c.
Referenced by mmalomx_commands_actions_next().
 {
    MMALOMX_COMPONENT_T *component = (MMALOMX_COMPONENT_T *)hComponent;
    unsigned int i, transition;
    if (component->state == state)
    {
       mmalomx_callback_event_handler(component, OMX_EventError, OMX_ErrorSameState, 0, NULL);
       return OMX_ErrorNone;
    }
    /* We're asked to transition to StateInvalid */
    if (state == OMX_StateInvalid)
    {
       component->state = state;
       mmalomx_callback_event_handler(component, OMX_EventError, OMX_ErrorInvalidState, 0, NULL);
       return OMX_ErrorNone;
    }
    /* Commands are being queued so we should never get into that state */
    vcos_assert(!component->state_transition);
    /* Check the transition is valid */
    transition = mmalomx_state_transition_get(component->state, state);
    if (!transition)
    {
       mmalomx_callback_event_handler(component, OMX_EventError, OMX_ErrorIncorrectStateTransition, 0, NULL);
       return OMX_ErrorNone;
    }
    /* Special case for transition in and out of Executing */
    if (state == OMX_StateExecuting || component->state == OMX_StateExecuting)
    {
       MMAL_STATUS_T status;
       if (state == OMX_StateExecuting)
          status = mmal_component_enable(component->mmal);
       else
          status = mmal_component_disable(component->mmal);
       if (status != MMAL_SUCCESS)
       {
          LOG_ERROR("could not %s %s", state == OMX_StateExecuting ? "enable" : "disable", component->name);
          mmalomx_callback_event_handler(component, OMX_EventError, mmalil_error_to_omx(status), 0, NULL);
          return OMX_ErrorNone;
       }
    }
    MMALOMX_LOCK(component);
    component->state_transition = transition;
    for (i = 0; i < component->ports_num; i++)
    {
       if (!component->ports[i].enabled)
          continue;
       MMALOMX_LOCK_PORT(component, component->ports + i);
       component->ports[i].actions = state_transition_table[transition].actions;
       /* If we're transitionning from Idle to Loaded we'd rather do a flush first
        * to avoid the cmd thread to block for too long (mmal_disable is a
        * blocking call). */
       if (state_transition_table[transition].state == OMX_StateIdle &&
           state_transition_table[transition].request == OMX_StateLoaded &&
           component->cmd_thread_used)
          component->ports[i].actions |= MMALOMX_ACTION_FLUSH|MMALOMX_ACTION_CHECK_FLUSHED;
       MMALOMX_UNLOCK_PORT(component, component->ports + i);
    }
    MMALOMX_UNLOCK(component);
    mmalomx_commands_actions_check(component);
    return OMX_ErrorNone;
 }
mmalomx_commands_actions_check()
void mmalomx_commands_actions_check (MMALOMX_COMPONENT_T * component)
Definition at line 175 of file mmalomx_commands.c.
References MMALOMX_COMPONENT_T::ports_num.
Referenced by mmalomx_command_port_disable(), mmalomx_command_port_enable(), mmalomx_command_port_flush(), and mmalomx_commands_actions_signal().
 {
    uint32_t actions_left = 0;
    unsigned int i;
    for (i = 0; i < component->ports_num; i++)
       mmalomx_commands_check_port_actions(component, &component->ports[i]);
    MMALOMX_LOCK(component);
    for (i = 0; i < component->ports_num; i++)
       actions_left |= component->ports[i].actions;
    if (!actions_left && component->state_transition)
    {
       component->state = state_transition_table[component->state_transition].request;
       component->state_transition = 0;
       actions_left = MMALOMX_ACTION_NOTIFY_STATE;
    }
    MMALOMX_UNLOCK(component);
    if (actions_left == MMALOMX_ACTION_NOTIFY_STATE)
    {
       mmalomx_callback_event_handler(component, OMX_EventCmdComplete,
          OMX_CommandStateSet, component->state, NULL);
       actions_left = 0;
    }
    /* If we're not currently processing a command, we can start processing
     * the next one. */
    if (!actions_left)
       mmalomx_commands_actions_next(component);
 }
mmalomx_commands_actions_next()
void mmalomx_commands_actions_next (MMALOMX_COMPONENT_T * component)
Definition at line 425 of file mmalomx_commands.c.
References mmalomx_command_dequeue(), mmalomx_command_port_disable(), mmalomx_command_port_enable(), mmalomx_command_port_flush(), mmalomx_command_state_set(), MMALOMX_COMPONENT_T::omx, OMX_ALL, OMX_CommandFlush, OMX_CommandPortDisable, OMX_CommandPortEnable, OMX_CommandStateSet, OMX_ErrorNone, MMALOMX_COMPONENT_T::ports_num, and status.
 {
    OMX_ERRORTYPE status = OMX_ErrorNone;
    OMX_COMMANDTYPE cmd;
    OMX_U32 arg1, arg2, nParam1;
    unsigned int i;
    status = mmalomx_command_dequeue(component, &arg1, &arg2);
    if (status != OMX_ErrorNone)
       return;
    cmd = (OMX_COMMANDTYPE)arg1;
    nParam1 = arg2;
    if (cmd == OMX_CommandStateSet)
    {
       mmalomx_command_state_set((OMX_HANDLETYPE)&component->omx, nParam1);
    }
    else if (cmd == OMX_CommandFlush)
    {
       for (i = 0; i < component->ports_num; i++)
          if (i == nParam1 || nParam1 == OMX_ALL)
             mmalomx_command_port_flush((OMX_HANDLETYPE)&component->omx, i);
    }
    else if (cmd == OMX_CommandPortEnable)
    {
       for (i = 0; i < component->ports_num; i++)
          if (i == nParam1 || nParam1 == OMX_ALL)
             mmalomx_command_port_enable((OMX_HANDLETYPE)&component->omx, i);
    }
    else if (cmd == OMX_CommandPortDisable)
    {
       for (i = 0; i < component->ports_num; i++)
          if (i == nParam1 || nParam1 == OMX_ALL)
             mmalomx_command_port_disable((OMX_HANDLETYPE)&component->omx, i);
    }
 }
mmalomx_commands_actions_signal()
void mmalomx_commands_actions_signal (MMALOMX_COMPONENT_T * component)
Definition at line 209 of file mmalomx_commands.c.
References MMALOMX_COMPONENT_T::cmd_sema, MMALOMX_COMPONENT_T::cmd_thread_used, mmalomx_commands_actions_check(), and vcos_semaphore_post().
Referenced by mmalomx_command_queue().
 {
    if (component->cmd_thread_used)
       vcos_semaphore_post(&component->cmd_sema);
    else
       mmalomx_commands_actions_check(component);
 }
Variable Documentation
state_transition_table
MMALOMX_STATE_TRANSITION_T state_transition_table[]
Initial value:
=
{
  {OMX_StateInvalid, OMX_StateInvalid, 0},
  {OMX_StateLoaded, OMX_StateIdle, MMALOMX_ACTION_CHECK_ALLOCATED|MMALOMX_ACTION_ENABLE},
  {OMX_StateLoaded, OMX_StateWaitForResources, 0},
  {OMX_StateWaitForResources, OMX_StateLoaded, 0},
  {OMX_StateWaitForResources, OMX_StateIdle, MMALOMX_ACTION_CHECK_ALLOCATED|MMALOMX_ACTION_ENABLE},
  {OMX_StateIdle, OMX_StateLoaded, MMALOMX_ACTION_CHECK_DEALLOCATED|MMALOMX_ACTION_DISABLE},
  {OMX_StateIdle, OMX_StateExecuting, 0},
  {OMX_StateIdle, OMX_StatePause, 0},
  {OMX_StateExecuting, OMX_StateIdle, MMALOMX_ACTION_FLUSH|MMALOMX_ACTION_CHECK_FLUSHED},
  {OMX_StateExecuting, OMX_StatePause, 0},
  {OMX_StatePause, OMX_StateIdle, 0},
  {OMX_StatePause, OMX_StateExecuting, 0},
  {OMX_StateMax, OMX_StateMax, 0}
}
Definition at line 39 of file mmalomx_commands.c.