VideoCore Library: Utility functions
Utility functions
Modules
utility
Port connection utility
Graph Utility
MMAL to OMX IL conversion utilities
Rational Utility Functions
Macros
#define MMAL_OFFSET(TYPE, FIELD) ((size_t)((uint8_t *)&((TYPE*)0)->FIELD - (uint8_t *)0))
Functions
const char * mmal_status_to_string (MMAL_STATUS_T status)
uint32_t mmal_encoding_stride_to_width (uint32_t encoding, uint32_t stride)
uint32_t mmal_encoding_width_to_stride (uint32_t encoding, uint32_t width)
uint32_t mmal_encoding_get_slice_variant (uint32_t encoding)
const char * mmal_port_type_to_string (MMAL_PORT_TYPE_T type)
MMAL_PARAMETER_HEADER_T * mmal_port_parameter_alloc_get (MMAL_PORT_T *port, uint32_t id, uint32_t size, MMAL_STATUS_T *status)
void mmal_port_parameter_free (MMAL_PARAMETER_HEADER_T *param)
void mmal_buffer_header_copy_header (MMAL_BUFFER_HEADER_T *dest, const MMAL_BUFFER_HEADER_T *src)
MMAL_POOL_T * mmal_port_pool_create (MMAL_PORT_T *port, unsigned int headers, uint32_t payload_size)
void mmal_port_pool_destroy (MMAL_PORT_T *port, MMAL_POOL_T *pool)
void mmal_log_dump_port (MMAL_PORT_T *port)
void mmal_log_dump_format (MMAL_ES_FORMAT_T *format)
MMAL_PORT_T * mmal_util_get_port (MMAL_COMPONENT_T *comp, MMAL_PORT_TYPE_T type, unsigned index)
char * mmal_4cc_to_string (char *buf, size_t len, uint32_t fourcc)
int mmal_util_rgb_order_fixed (MMAL_PORT_T *port)
Detailed Description
The utility functions provide helpers for common functionality that is not part of the core MMAL API.
Macro Definition Documentation
MMAL_OFFSET
#define MMAL_OFFSET (TYPE, FIELD) ((size_t)((uint8_t *)&((TYPE*)0)->FIELD - (uint8_t *)0))
Offset in bytes of FIELD in TYPE.
Definition at line 40 of file mmal_util.h.
Function Documentation
mmal_4cc_to_string()
char* mmal_4cc_to_string (char * buf, size_t len, uint32_t fourcc)
Convert a 4cc into a string.
Parameters
buf Destination for result
len Size of result buffer
fourcc 4cc to be converted
Returns
converted string (buf)
Definition at line 411 of file mmal_util.c.
References vcos_assert.
 {
    char *src = (char*)&fourcc;
    vcos_assert(len >= 5);
    if (len < 5)
    {
       buf[0] = '\0';
    }
    else if (fourcc)
    {
       memcpy(buf, src, 4);
       buf[4] = '\0';
    }
    else
    {
       snprintf(buf, len, "<0>");
    }
    return buf;
 }
mmal_buffer_header_copy_header()
void mmal_buffer_header_copy_header (MMAL_BUFFER_HEADER_T * dest, const MMAL_BUFFER_HEADER_T * src)
Copy buffer header metadata from source to destination.
Parameters
dest The destination buffer header.
src The source buffer header.
Copy buffer header metadata from source to dest
Definition at line 268 of file mmal_util.c.
References MMAL_BUFFER_HEADER_T::cmd, MMAL_BUFFER_HEADER_T::dts, MMAL_BUFFER_HEADER_T::flags, MMAL_BUFFER_HEADER_T::length, MMAL_BUFFER_HEADER_T::offset, MMAL_BUFFER_HEADER_T::pts, and MMAL_BUFFER_HEADER_T::type.
 {
    dest->cmd    = src->cmd;
    dest->offset = src->offset;
    dest->length = src->length;
    dest->flags  = src->flags;
    dest->pts    = src->pts;
    dest->dts    = src->dts;
    *dest->type = *src->type;
 }
mmal_encoding_get_slice_variant()
uint32_t mmal_encoding_get_slice_variant (uint32_t encoding)
Return the 16 line high sliced version of a given pixel encoding
Parameters
encoding The pixel encoding (such as one of the pre-defined encodings)
Returns
The sliced equivalent, or MMAL_ENCODING_UNKNOWN if not supported.
Definition at line 188 of file mmal_util.c.
 {
    unsigned int i;
    for(i = 0; slice_equivalents[i].encoding != MMAL_ENCODING_UNKNOWN; i++)
       if(slice_equivalents[i].encoding == encoding) break;
    return slice_equivalents[i].sliced_encoding;
 }
mmal_encoding_stride_to_width()
uint32_t mmal_encoding_stride_to_width (uint32_t encoding, uint32_t stride)
Convert stride to pixel width for a given pixel encoding.
Parameters
encoding The pixel encoding (such as one of the pre-defined encodings)
stride The stride in bytes.
Returns
The width in pixels.
Definition at line 162 of file mmal_util.c.
 {
    unsigned int i;
    for(i = 0; pixel_pitch[i].encoding != MMAL_ENCODING_UNKNOWN; i++)
       if(pixel_pitch[i].encoding == encoding) break;
    if(pixel_pitch[i].encoding == MMAL_ENCODING_UNKNOWN)
       return 0;
    return pixel_pitch[i].pitch_den * stride / pixel_pitch[i].pitch_num;
 }
mmal_encoding_width_to_stride()
uint32_t mmal_encoding_width_to_stride (uint32_t encoding, uint32_t width)
Convert pixel width to stride for a given pixel encoding
Parameters
encoding The pixel encoding (such as one of the pre-defined encodings)
width The width in pixels.
Returns
The stride in bytes.
Definition at line 175 of file mmal_util.c.
 {
    unsigned int i;
    for(i = 0; pixel_pitch[i].encoding != MMAL_ENCODING_UNKNOWN; i++)
       if(pixel_pitch[i].encoding == encoding) break;
    if(pixel_pitch[i].encoding == MMAL_ENCODING_UNKNOWN)
       return 0;
    return VCOS_ALIGN_UP(pixel_pitch[i].pitch_num * width / pixel_pitch[i].pitch_den, pixel_pitch[i].alignment);
 }
mmal_log_dump_format()
void mmal_log_dump_format (MMAL_ES_FORMAT_T * format)
Log the content of a MMAL_ES_FORMAT_T structure.
Parameters
format Pointer to the format to dump.
Definition at line 329 of file mmal_util.c.
References MMAL_ES_SPECIFIC_FORMAT_T::audio, MMAL_ES_FORMAT_T::bitrate, MMAL_AUDIO_FORMAT_T::bits_per_sample, MMAL_AUDIO_FORMAT_T::block_align, MMAL_AUDIO_FORMAT_T::channels, MMAL_VIDEO_FORMAT_T::crop, MMAL_RATIONAL_T::den, MMAL_ES_FORMAT_T::encoding, MMAL_ES_FORMAT_T::es, MMAL_ES_FORMAT_T::extradata, MMAL_ES_FORMAT_T::extradata_size, MMAL_ES_FORMAT_T::flags, MMAL_VIDEO_FORMAT_T::frame_rate, MMAL_VIDEO_FORMAT_T::height, MMAL_RECT_T::height, LOG_DEBUG, MMAL_ES_FORMAT_FLAG_FRAMED, MMAL_ES_TYPE_AUDIO, MMAL_ES_TYPE_SUBPICTURE, MMAL_ES_TYPE_VIDEO, MMAL_RATIONAL_T::num, MMAL_VIDEO_FORMAT_T::par, MMAL_AUDIO_FORMAT_T::sample_rate, MMAL_ES_FORMAT_T::type, MMAL_ES_SPECIFIC_FORMAT_T::video, MMAL_VIDEO_FORMAT_T::width, MMAL_RECT_T::width, MMAL_RECT_T::x, and MMAL_RECT_T::y.
Referenced by mmal_log_dump_port().
 {
    const char *name_type;
    if (!format)
       return;
    switch(format->type)
    {
    case MMAL_ES_TYPE_AUDIO: name_type = "audio"; break;
    case MMAL_ES_TYPE_VIDEO: name_type = "video"; break;
    case MMAL_ES_TYPE_SUBPICTURE: name_type = "subpicture"; break;
    default: name_type = "unknown"; break;
    }
    LOG_DEBUG("type: %s, fourcc: %4.4s", name_type, (char *)&format->encoding);
    LOG_DEBUG(" bitrate: %i, framed: %i", format->bitrate,
             !!(format->flags & MMAL_ES_FORMAT_FLAG_FRAMED));
    LOG_DEBUG(" extra data: %i, %p", format->extradata_size, format->extradata);
    switch(format->type)
    {
    case MMAL_ES_TYPE_AUDIO:
       LOG_DEBUG(" samplerate: %i, channels: %i, bps: %i, block align: %i",
                format->es->audio.sample_rate, format->es->audio.channels,
                format->es->audio.bits_per_sample, format->es->audio.block_align);
       break;
    case MMAL_ES_TYPE_VIDEO:
       LOG_DEBUG(" width: %i, height: %i, (%i,%i,%i,%i)",
                format->es->video.width, format->es->video.height,
                format->es->video.crop.x, format->es->video.crop.y,
                format->es->video.crop.width, format->es->video.crop.height);
       LOG_DEBUG(" pixel aspect ratio: %i/%i, frame rate: %i/%i",
                format->es->video.par.num, format->es->video.par.den,
                format->es->video.frame_rate.num, format->es->video.frame_rate.den);
       break;
    case MMAL_ES_TYPE_SUBPICTURE:
       break;
    default: break;
    }
 }
mmal_log_dump_port()
void mmal_log_dump_port (MMAL_PORT_T * port)
Log the content of a MMAL_PORT_T structure.
Parameters
port Pointer to the port to dump.
Definition at line 313 of file mmal_util.c.
References MMAL_PORT_T::buffer_alignment_min, MMAL_PORT_T::buffer_num, MMAL_PORT_T::buffer_num_min, MMAL_PORT_T::buffer_num_recommended, MMAL_PORT_T::buffer_size, MMAL_PORT_T::buffer_size_min, MMAL_PORT_T::buffer_size_recommended, MMAL_PORT_T::format, LOG_DEBUG, mmal_log_dump_format(), and MMAL_PORT_T::name.
 {
    if (!port)
       return;
    LOG_DEBUG("%s(%p)", port->name, port);
    mmal_log_dump_format(port->format);
    LOG_DEBUG(" buffers num: %i(opt %i, min %i), size: %i(opt %i, min: %i), align: %i",
             port->buffer_num, port->buffer_num_recommended, port->buffer_num_min,
             port->buffer_size, port->buffer_size_recommended, port->buffer_size_min,
             port->buffer_alignment_min);
 }
mmal_port_parameter_alloc_get()
MMAL_PARAMETER_HEADER_T* mmal_port_parameter_alloc_get (MMAL_PORT_T * port, uint32_t id, uint32_t size, MMAL_STATUS_T * status)
Get a parameter from a port allocating the required amount of memory for the parameter (i.e. for variable length parameters like URI or arrays). The size field will be set on output to the actual size of the parameter allocated and retrieved.
The pointer returned must be released by a call to mmal_port_parameter_free().
Parameters
port port to send request to
id parameter id
size initial size hint for allocation (can be 0)
status status of the parameter get operation (can be 0)
Returns
pointer to the header of the parameter or NULL on failure.
Definition at line 214 of file mmal_util.c.
References error(), MMAL_PARAMETER_HEADER_T::id, MMAL_ENOMEM, MMAL_ENOSPC, MMAL_ENOSYS, mmal_port_parameter_get(), MMAL_SUCCESS, NULL, MMAL_PARAMETER_HEADER_T::size, status, vcos_calloc(), and vcos_free().
 {
    MMAL_PARAMETER_HEADER_T *param = NULL;
    MMAL_STATUS_T status = MMAL_ENOSYS;
    if (size < sizeof(MMAL_PARAMETER_HEADER_T))
       size = sizeof(MMAL_PARAMETER_HEADER_T);
    if ((param = vcos_calloc(1, size, "mmal_port_param_get")) == NULL)
    {
       status = MMAL_ENOMEM;
       goto error;
    }
    param->id = id;
    param->size = size;
    if ((status = mmal_port_parameter_get(port, param)) == MMAL_ENOSPC)
    {
       /* We need to reallocate to get enough space for all parameter data */
       size = param->size;
       vcos_free(param);
       if ((param = vcos_calloc(1, size, "mmal_port_param_get")) == NULL)
       {
          status = MMAL_ENOMEM;
          goto error;
       }
       /* Now retrieve it again */
       param->id = id;
       param->size = size;
       status = mmal_port_parameter_get(port, param);
    }
    if (status != MMAL_SUCCESS)
       goto error;
 end:
    if (p_status) *p_status = status;
    return param;
 error:
    if (param) vcos_free(param);
    param = NULL;
    goto end;
 }
mmal_port_parameter_free()
void mmal_port_parameter_free (MMAL_PARAMETER_HEADER_T * param)
Free a parameter structure previously allocated via mmal_port_parameter_alloc_get().
Parameters
param pointer to header of the parameter
Definition at line 261 of file mmal_util.c.
References vcos_free().
 {
    vcos_free(param);
 }
mmal_port_pool_create()
MMAL_POOL_T* mmal_port_pool_create (MMAL_PORT_T * port, unsigned int headers, uint32_t payload_size)
Create a pool of MMAL_BUFFER_HEADER_T associated with a specific port. This allows a client to allocate memory for the payload buffers based on the preferences of a port. This for instance will allow the port to allocate memory which can be shared between the host processor and videocore. After allocation, all allocated buffer headers will have been added to the queue.
It is valid to create a pool with no buffer headers, or with zero size payload buffers. The mmal_pool_resize() function can be used to increase or decrease the number of buffer headers, or the size of the payload buffers, after creation of the pool.
Parameters
port Port responsible for creating the pool.
headers Number of buffers which will be allocated with the pool.
payload_size Size of the payload buffer which will be allocated in each of the buffer headers.
Returns
Pointer to the newly created pool or NULL on failure.
Create a pool of MMAL_BUFFER_HEADER_T
Definition at line 280 of file mmal_util.c.
References MMAL_PORT_T::component, MMAL_PORT_T::index, LOG_TRACE, mmal_pool_create_with_allocator(), mmal_port_payload_alloc(), mmal_port_payload_free(), MMAL_COMPONENT_T::name, NULL, MMAL_PORT_T::priv, and MMAL_PORT_T::type.
Referenced by mmal_connection_create(), mmal_wrapper_create(), and raspitex_configure_preview_port().
 {
    if (!port || !port->priv)
       return NULL;
    LOG_TRACE("%s(%i:%i) port %p, headers %u, size %i", port->component->name,
              (int)port->type, (int)port->index, port, headers, (int)payload_size);
    /* Create a pool and ask the port for some memory */
    return mmal_pool_create_with_allocator(headers, payload_size, (void *)port,
                                           (mmal_pool_allocator_alloc_t)mmal_port_payload_alloc,
                                           (mmal_pool_allocator_free_t)mmal_port_payload_free);
 }
mmal_port_pool_destroy()
void mmal_port_pool_destroy (MMAL_PORT_T * port, MMAL_POOL_T * pool)
Destroy a pool of MMAL_BUFFER_HEADER_T associated with a specific port. This will also deallocate all of the memory which was allocated when creating or resizing the pool.
Parameters
port Pointer to the port responsible for creating the pool.
pool Pointer to the pool to be destroyed.
Destroy a pool of MMAL_BUFFER_HEADER_T
Definition at line 295 of file mmal_util.c.
References MMAL_PORT_T::component, MMAL_PORT_T::index, MMAL_PORT_T::is_enabled, LOG_ERROR, LOG_TRACE, mmal_pool_destroy(), mmal_port_disable(), MMAL_COMPONENT_T::name, MMAL_PORT_T::priv, MMAL_PORT_T::type, and vcos_verify.
 {
    if (!port || !port->priv || !pool)
       return;
    LOG_TRACE("%s(%i:%i) port %p, pool %p", port->component->name,
              (int)port->type, (int)port->index, port, pool);
    if (!vcos_verify(!port->is_enabled))
    {
       LOG_ERROR("port %p, pool %p destroyed while port enabled", port, pool);
       mmal_port_disable(port);
    }
    mmal_pool_destroy(pool);
 }
mmal_port_type_to_string()
const char* mmal_port_type_to_string (MMAL_PORT_TYPE_T type)
Convert a port type to a string.
Parameters
type The MMAL port type.
Returns
A NULL-terminated string describing the port type.
Definition at line 198 of file mmal_util.c.
References MMAL_PORT_TYPE_CLOCK, MMAL_PORT_TYPE_CONTROL, MMAL_PORT_TYPE_INPUT, MMAL_PORT_TYPE_OUTPUT, and str.
Referenced by mmal_connection_create().
 {
    const char *str;
    switch (type)
    {
    case MMAL_PORT_TYPE_INPUT:   str = "in";  break;
    case MMAL_PORT_TYPE_OUTPUT:  str = "out"; break;
    case MMAL_PORT_TYPE_CLOCK:   str = "clk"; break;
    case MMAL_PORT_TYPE_CONTROL: str = "ctr"; break;
    default:                     str = "invalid"; break;
    }
    return str;
 }
mmal_status_to_string()
const char* mmal_status_to_string (MMAL_STATUS_T status)
Convert a status to a statically-allocated string.
Parameters
status The MMAL status code.
Returns
A C string describing the status code.
Definition at line 56 of file mmal_util.c.
Referenced by mmal_port_send_buffer().
 {
    unsigned i;
    for (i=0; status_to_string_map[i].str; i++)
       if (status_to_string_map[i].status == status)
          break;
    return status_to_string_map[i].str ? status_to_string_map[i].str : "UNKNOWN";
 }
mmal_util_get_port()
MMAL_PORT_T* mmal_util_get_port (MMAL_COMPONENT_T * comp, MMAL_PORT_TYPE_T type, unsigned index)
Return the nth port.
Parameters
comp component to query
index port index
type port type
Returns
port or NULL if not found
Definition at line 373 of file mmal_util.c.
References MMAL_COMPONENT_T::clock, MMAL_COMPONENT_T::clock_num, MMAL_COMPONENT_T::control, index, MMAL_COMPONENT_T::input, MMAL_COMPONENT_T::input_num, MMAL_PORT_TYPE_CLOCK, MMAL_PORT_TYPE_CONTROL, MMAL_PORT_TYPE_INPUT, MMAL_PORT_TYPE_OUTPUT, NULL, MMAL_COMPONENT_T::output, MMAL_COMPONENT_T::output_num, and vcos_assert.
 {
    unsigned num;
    MMAL_PORT_T **list;
    switch (type)
    {
    case MMAL_PORT_TYPE_INPUT:
       num = comp->input_num;
       list = comp->input;
       break;
    case MMAL_PORT_TYPE_OUTPUT:
       num = comp->output_num;
       list = comp->output;
       break;
    case MMAL_PORT_TYPE_CLOCK:
       num = comp->clock_num;
       list = comp->clock;
       break;
    case MMAL_PORT_TYPE_CONTROL:
       num = 1;
       list = &comp->control;
       break;
    default:
       vcos_assert(0);
       return NULL;
    }
    if (index < num)
       /* coverity[ptr_arith] num is 1 here */
       return list[index];
    else
       return NULL;
 }
mmal_util_rgb_order_fixed()
int mmal_util_rgb_order_fixed (MMAL_PORT_T * port)
On FW prior to June 2016, camera and video_splitter had BGR24 and RGB24 support reversed. This is now fixed, and this function will return whether the FW has the fix or not.
Parameters
port MMAL port to check (on camera or video_splitter)
Returns
0 if old firmware, 1 if new.
Definition at line 438 of file mmal_util.c.
References MMAL_SUPPORTED_ENCODINGS_T::encodings, MMAL_SUPPORTED_ENCODINGS_T::header, MAX_ENCODINGS_NUM, MMAL_ENCODING_BGR24, MMAL_ENCODING_RGB24, MMAL_ENOSPC, MMAL_PARAMETER_SUPPORTED_ENCODINGS, mmal_port_parameter_get(), MMAL_SUCCESS, and MMAL_PARAMETER_HEADER_T::size.
 {
    int new_fw = 0;
    MMAL_STATUS_T ret;
    //Firmware support of RGB24 vs BGR24 colour ordering from camera
    //and video splitter components has been corrected as of June 2016.
    //New firmwares always report MMAL_ENCODING_RGB24 before BGR24, and
    //that is the format we want.
    //Old firmware reported BGR24 first, and also returned an error on
    //the still port on querying MMAL_PARAMETER_SUPPORTED_ENCODINGS.
    MMAL_SUPPORTED_ENCODINGS_T sup_encodings = {{MMAL_PARAMETER_SUPPORTED_ENCODINGS, sizeof(sup_encodings)}, {0}};
    ret = mmal_port_parameter_get(port, &sup_encodings.header);
    if (ret == MMAL_SUCCESS || ret == MMAL_ENOSPC)
    {
       //Allow ENOSPC error and hope that the desired formats are in the first
       //MAX_ENCODINGS_NUM entries.
       int i;
       int num_encodings = (sup_encodings.header.size - sizeof(sup_encodings.header)) /
           sizeof(sup_encodings.encodings[0]);
       if(num_encodings > MAX_ENCODINGS_NUM)
          num_encodings = MAX_ENCODINGS_NUM;
       for (i=0; i<num_encodings; i++)
       {
          if (sup_encodings.encodings[i] == MMAL_ENCODING_BGR24)
          {
             //Found BGR24 first - old firmware.
             break;
          }
          if (sup_encodings.encodings[i] == MMAL_ENCODING_RGB24)
          {
             //Found RGB24 first - new firmware, so use RGB24.
             new_fw = 1;
          }
       }
    }
    return new_fw;
 }