VideoCore Library: interface/khronos/wf/wfc_server_api.h File Reference
wfc_server_api.h File Reference
#include "interface/vcos/vcos.h"
#include "interface/vcos/vcos_stdbool.h"
#include "interface/khronos/include/WF/wfc.h"
#include "interface/khronos/wf/wfc_int.h"
#include "interface/khronos/include/EGL/eglext.h"
Classes
struct WFC_STREAM_INFO_T
Macros
#define WFC_SERVER_STREAM_RECTS_SIZE 8
Typedefs
typedef void(* WFC_CALLBACK_T) (void *cb_data)
typedef struct WFC_STREAM_INFO_T WFC_STREAM_INFO_T
Enumerations
enum WFC_SERVER_COMMIT_FLAGS_T { WFC_SERVER_COMMIT_WAIT = 1, WFC_SERVER_COMMIT_COMPOSE = 2 }
Functions
VCOS_STATUS_T wfc_server_connect (void)
void wfc_server_disconnect (void)
void wfc_server_use_keep_alive (void)
void wfc_server_release_keep_alive (void)
uint32_t wfc_server_create_context (WFCContext context, uint32_t context_type, uint32_t screen_or_stream_num, uint32_t pid_lo, uint32_t pid_hi)
void wfc_server_destroy_context (WFCContext ctx)
uint32_t wfc_server_commit_scene (WFCContext ctx, const WFC_SCENE_T *scene, uint32_t flags, WFC_CALLBACK_T scene_taken_cb, void *scene_taken_data)
void wfc_server_activate (WFCContext ctx)
void wfc_server_deactivate (WFCContext ctx)
void wfc_server_set_deferral_stream (WFCContext ctx, WFCNativeStreamType stream)
WFCNativeStreamType wfc_server_stream_create (WFCNativeStreamType stream, uint32_t flags, uint32_t pid_lo, uint32_t pid_hi)
WFCNativeStreamType wfc_server_stream_create_info (WFCNativeStreamType stream, const WFC_STREAM_INFO_T *info, uint32_t pid_lo, uint32_t pid_hi)
void wfc_server_stream_destroy (WFCNativeStreamType stream, uint32_t pid_lo, uint32_t pid_hi)
void wfc_server_stream_on_rects_change (WFCNativeStreamType stream, WFC_CALLBACK_T rects_change_cb, void *rects_change_data)
uint32_t wfc_server_stream_get_rects (WFCNativeStreamType stream, int32_t rects[WFC_SERVER_STREAM_RECTS_SIZE])
bool wfc_server_stream_is_in_use (WFCNativeStreamType stream)
bool wfc_server_stream_allocate_images (WFCNativeStreamType stream, uint32_t width, uint32_t height, uint32_t nbufs)
void wfc_server_stream_signal_eglimage_data (WFCNativeStreamType stream, uint32_t ustorage, uint32_t width, uint32_t height, uint32_t stride, uint32_t offset, uint32_t format, uint32_t flags, bool flip)
void wfc_server_stream_signal_mm_image_data (WFCNativeStreamType stream, uint32_t image_handle)
void wfc_server_stream_signal_raw_pixels (WFCNativeStreamType stream, uint32_t handle, uint32_t format, uint32_t width, uint32_t height, uint32_t pitch, uint32_t vpitch)
void wfc_server_stream_signal_image (WFCNativeStreamType stream, const WFC_STREAM_IMAGE_T *image)
void wfc_server_stream_register (WFCNativeStreamType stream, uint32_t pid_lo, uint32_t pid_hi)
void wfc_server_stream_unregister (WFCNativeStreamType stream, uint32_t pid_lo, uint32_t pid_hi)
uint32_t wfc_server_stream_get_info (WFCNativeStreamType stream, WFC_STREAM_INFO_T *info)
void wfc_server_stream_on_image_available (WFCNativeStreamType stream, WFC_CALLBACK_T image_available_cb, void *image_available_data)
Macro Definition Documentation
WFC_SERVER_STREAM_RECTS_SIZE
#define WFC_SERVER_STREAM_RECTS_SIZE 8
Get destination and source rectangles, following request from server
Parameters
stream The client stream identifier.
rects The rectangle data is written here.
Returns
VCOS_SUCCESS if successful, or an error code if not.
Definition at line 198 of file wfc_server_api.h.
Typedef Documentation
WFC_CALLBACK_T
typedef void(* WFC_CALLBACK_T) (void *cb_data)
Defining WFC_FULL_LOGGING will enable trace level logging across all WFC components. #define WFC_FULL_LOGGING General purpose callback function. Note: callbacks are often made on a thread other than the original function's.
Parameters
cb_data Callback additional data.
Definition at line 47 of file wfc_server_api.h.
WFC_STREAM_INFO_T
typedef struct WFC_STREAM_INFO_T WFC_STREAM_INFO_T
Extensible stream information block, supplied during creation and retrievable using wfc_server_stream_get_info.
Enumeration Type Documentation
WFC_SERVER_COMMIT_FLAGS_T
enum WFC_SERVER_COMMIT_FLAGS_T
Flags to be passed to wfc_server_commit_scene. A bitwise combination of flags may be passed in to control behaviour.
Enumerator
WFC_SERVER_COMMIT_WAIT
Wait for scene to be committed.
WFC_SERVER_COMMIT_COMPOSE
Trigger composition
Definition at line 104 of file wfc_server_api.h.
 {
    WFC_SERVER_COMMIT_WAIT     = 1,
    WFC_SERVER_COMMIT_COMPOSE  = 2,
 } WFC_SERVER_COMMIT_FLAGS_T;
Function Documentation
wfc_server_activate()
void wfc_server_activate (WFCContext ctx)
Activate a context. While a context is active, it will be automatically composed when any of the streams in its current scene are updated.
Parameters
context The client context identifier.
Definition at line 222 of file wfc_client_server_api.c.
 {
    VCOS_STATUS_T status;
    vcos_log_trace("%s: context 0x%x", VCOS_FUNCTION, context);
    status = wfc_client_server_api_send_context(WFC_IPC_MSG_ACTIVATE, context);
    vcos_assert(status == VCOS_SUCCESS);
 }
wfc_server_commit_scene()
uint32_t wfc_server_commit_scene (WFCContext ctx, const WFC_SCENE_T * scene, uint32_t flags, WFC_CALLBACK_T scene_taken_cb, void * scene_taken_data)
Commit a scene in the context. If the WAIT flag is set, a callback must be given and shall be called once a new scene can be given. If the COMPOSE flag is set, the newly committed scene shall be composed as soon as possible (subject to presence of a deferral stream).
Parameters
context The client context identifier.
scene The scene to be composed.
flags Combination of WFC_SERVER_COMMIT_FLAGS_T values, or 0.
scene_taken_cb Called when scene has been taken, generally on a different thread, or zero for no callback.
scene_taken_data Passed to scene_taken_cb.
Returns
VCOS_SUCCESS if successful, VCOS_EAGAIN if the scene cannot be taken immediately and the wait flag is false.
Definition at line 175 of file wfc_client_server_api.c.
 {
    WFC_IPC_MSG_COMMIT_SCENE_T msg;
    VCOS_STATUS_T status = VCOS_SUCCESS;
    uint32_t result = VCOS_ENOSYS;
    size_t result_len = sizeof(result);
    uint32_t i;
    vcos_log_trace("%s: context 0x%x commit %u elements %u flags 0x%x",
          VCOS_FUNCTION, context, scene->commit_count, scene->element_count, flags);
    for (i = 0; i < scene->element_count; i++)
    {
       vcos_log_trace("%s: element[%u] stream 0x%x", VCOS_FUNCTION, i, scene->elements[i].source_stream);
    }
    msg.header.type = WFC_IPC_MSG_COMMIT_SCENE;
    msg.context = context;
    msg.flags = flags;
    msg.scene_taken_cb.ptr = scene_taken_cb;
    msg.scene_taken_data.ptr = scene_taken_data;
    memcpy(&msg.scene, scene, sizeof(*scene));
    if (flags & WFC_SERVER_COMMIT_WAIT)
    {
       /* Caller will wait for callback, call cannot fail */
       vcos_assert(scene_taken_cb != NULL);
       vcos_assert(scene_taken_data != NULL);
    }
    else
    {
       /* Caller will not wait for callback, so need to at least wait for result. */
       vcos_assert(scene_taken_cb == NULL);
       vcos_assert(scene_taken_data == NULL);
    }
    status = wfc_client_ipc_sendwait(&msg.header, sizeof(msg), &result, &result_len);
    /* Override the result if the status was an error */
    if (status != VCOS_SUCCESS)
       result = status;
    return result;
 }
wfc_server_connect()
VCOS_STATUS_T wfc_server_connect (void)
Create a connection to the server, as necessary. If this fails, no other server functions should be called. If it succeeds, there must be one call to wfc_server_disconnect() when use of the server has ended.
Returns
VCOS_SUCCESS or a failure code.
Definition at line 85 of file wfc_client_server_api.c.
References status, VCOS_FUNCTION, VCOS_LOG_CATEGORY, vcos_log_register(), vcos_log_set_level(), vcos_log_unregister(), VCOS_SUCCESS, wfc_client_ipc_init(), and WFC_CLIENT_SERVER_API_LOGLEVEL.
Referenced by wfc_stream_register().
 {
    VCOS_STATUS_T status;
    vcos_log_set_level(VCOS_LOG_CATEGORY, WFC_CLIENT_SERVER_API_LOGLEVEL);
    vcos_log_register("wfccsapi", VCOS_LOG_CATEGORY);
    status = wfc_client_ipc_init();
    vcos_log_trace("%s: result %d", VCOS_FUNCTION, status);
    if (status != VCOS_SUCCESS)
    {
       vcos_log_unregister(VCOS_LOG_CATEGORY);
    }
    return status;
 }
wfc_server_create_context()
uint32_t wfc_server_create_context (WFCContext context, uint32_t context_type, uint32_t screen_or_stream_num, uint32_t pid_lo, uint32_t pid_hi)
Create a new on- or off-screen context for composition. The type of the context is either WFC_CONTEXT_TYPE_ON_SCREEN or WFC_CONTEXT_TYPE_OFF_SCREEN.
Parameters
context The client context identifier.
context_type The type of the context.
screen_or_stream_num The screen number for and on-screen context, or the target client stream identifier for an off-screen context.
pid_lo The low 32-bits of the owning client process identifier.
pid_hi The high 32-bits of the owning client process identifier.
Returns
Zero on failure, or the width and height of the context in pixels, packed in the top and bottom 16 bits, respectively.
Definition at line 132 of file wfc_client_server_api.c.
 {
    WFC_IPC_MSG_CREATE_CONTEXT_T msg;
    VCOS_STATUS_T status;
    uint32_t result = -1;
    size_t result_len = sizeof(result);
    vcos_log_trace("%s: context 0x%x type 0x%x num 0x%x pid 0x%x%08x", VCOS_FUNCTION,
          context, context_type, screen_or_stream_num, pid_hi, pid_lo);
    msg.header.type = WFC_IPC_MSG_CREATE_CONTEXT;
    msg.context = context;
    msg.context_type = context_type;
    msg.screen_or_stream_num = screen_or_stream_num;
    msg.pid_lo = pid_lo;
    msg.pid_hi = pid_hi;
    status = wfc_client_ipc_sendwait(&msg.header, sizeof(msg), &result, &result_len);
    vcos_log_trace("%s: status 0x%x, result 0x%x", VCOS_FUNCTION, status, result);
    if (status != VCOS_SUCCESS)
       result = -1;
    return result;
 }
wfc_server_deactivate()
void wfc_server_deactivate (WFCContext ctx)
Deactivate a context.
Parameters
context The client context identifier.
Definition at line 235 of file wfc_client_server_api.c.
 {
    VCOS_STATUS_T status;
    vcos_log_trace("%s: context 0x%x", VCOS_FUNCTION, context);
    status = wfc_client_server_api_send_context(WFC_IPC_MSG_DEACTIVATE, context);
    vcos_assert(status == VCOS_SUCCESS);
 }
wfc_server_destroy_context()
void wfc_server_destroy_context (WFCContext ctx)
Destroy a context.
Parameters
context The client context identifier.
Definition at line 162 of file wfc_client_server_api.c.
 {
    VCOS_STATUS_T status;
    vcos_log_trace("%s: context 0x%x", VCOS_FUNCTION, context);
    status = wfc_client_server_api_send_context(WFC_IPC_MSG_DESTROY_CONTEXT, context);
    vcos_assert(status == VCOS_SUCCESS);
 }
wfc_server_disconnect()
void wfc_server_disconnect (void)
Destroy a connection to the server. This must be called once and only once for each successful call to wfc_server_connect().
Definition at line 106 of file wfc_client_server_api.c.
References VCOS_FUNCTION, VCOS_LOG_CATEGORY, vcos_log_unregister(), and wfc_client_ipc_deinit().
 {
    vcos_log_trace("%s: called", VCOS_FUNCTION);
    if (wfc_client_ipc_deinit())
    {
       vcos_log_unregister(VCOS_LOG_CATEGORY);
    }
 }
wfc_server_release_keep_alive()
void wfc_server_release_keep_alive (void)
Drop the keep alive count by one. If it reaches zero, the VideoCore may be suspended.
Definition at line 125 of file wfc_client_server_api.c.
References wfc_client_ipc_release_keep_alive().
 {
    wfc_client_ipc_release_keep_alive();
 }
wfc_server_set_deferral_stream()
void wfc_server_set_deferral_stream (WFCContext ctx, WFCNativeStreamType stream)
Set the deferral stream for a context. When a deferral stream is set on a context and a new scene is given for that context, composition is deferred until the stream is updated.
Parameters
context The client context identifier.
stream The deferral stream, or WFC_INVALID_HANDLE for none.
Definition at line 248 of file wfc_client_server_api.c.
 {
    WFC_IPC_MSG_SET_DEFERRAL_STREAM_T msg;
    VCOS_STATUS_T status;
    vcos_log_trace("%s: context 0x%x stream 0x%x", VCOS_FUNCTION, context, stream);
    msg.header.type = WFC_IPC_MSG_SET_DEFERRAL_STREAM;
    msg.context = context;
    msg.stream = stream;
    status = wfc_client_ipc_send(&msg.header, sizeof(msg));
    vcos_assert(status == VCOS_SUCCESS);
 }
wfc_server_stream_allocate_images()
bool wfc_server_stream_allocate_images (WFCNativeStreamType stream, uint32_t width, uint32_t height, uint32_t nbufs)
Allocate images in the stream into which an off-screen context can write composited output.
Parameters
stream The client stream identifier.
width The width of the images, in pixels.
height The height of the images, in pixels.
nbufs The number of images to allocate in the stream.
Returns
True on success, false on failure.
Definition at line 435 of file wfc_client_server_api.c.
References WFC_IPC_MSG_SS_ALLOCATE_IMAGES_T::header, WFC_IPC_MSG_SS_ALLOCATE_IMAGES_T::height, WFC_IPC_MSG_SS_ALLOCATE_IMAGES_T::nbufs, status, WFC_IPC_MSG_SS_ALLOCATE_IMAGES_T::stream, WFC_IPC_MSG_HEADER_T::type, VCOS_FUNCTION, VCOS_SUCCESS, wfc_client_ipc_sendwait(), WFC_IPC_MSG_SS_ALLOCATE_IMAGES, and WFC_IPC_MSG_SS_ALLOCATE_IMAGES_T::width.
 {
    WFC_IPC_MSG_SS_ALLOCATE_IMAGES_T msg;
    VCOS_STATUS_T status;
    uint32_t result = 0;
    size_t result_len = sizeof(result);
    vcos_log_trace("%s: stream 0x%x width %u height %u nbufs %u", VCOS_FUNCTION, stream, width, height, nbufs);
    msg.header.type = WFC_IPC_MSG_SS_ALLOCATE_IMAGES;
    msg.stream = stream;
    msg.width = width;
    msg.height = height;
    msg.nbufs = nbufs;
    status = wfc_client_ipc_sendwait(&msg.header, sizeof(msg), &result, &result_len);
    vcos_log_trace("%s: status 0x%x result %u", VCOS_FUNCTION, status, result);
    if (status != VCOS_SUCCESS)
       result = 0;
    return result;
 }
wfc_server_stream_create()
WFCNativeStreamType wfc_server_stream_create (WFCNativeStreamType stream, uint32_t flags, uint32_t pid_lo, uint32_t pid_hi)
Create a stream and its buffers, for supplying pixel data to one or more elements, and optionally for storing the output of off-screen composition.
Parameters
stream The client stream identifier.
flags Stream flags.
pid_lo The low 32-bits of the owning client process identifier.
pid_hi The high 32-bits of the owning client process identifier.
Returns
The client stream identifier on success, or WFC_INVALID_HANDLE on error.
Definition at line 266 of file wfc_client_server_api.c.
References WFC_STREAM_INFO_T::flags, WFC_IPC_MSG_SS_CREATE_INFO_T::header, WFC_IPC_MSG_SS_CREATE_INFO_T::info, WFC_IPC_MSG_SS_CREATE_INFO_T::pid_hi, WFC_IPC_MSG_SS_CREATE_INFO_T::pid_lo, WFC_STREAM_INFO_T::size, status, WFC_IPC_MSG_SS_CREATE_INFO_T::stream, WFC_IPC_MSG_HEADER_T::type, VCOS_FUNCTION, VCOS_SUCCESS, wfc_client_ipc_sendwait(), WFC_INVALID_HANDLE, and WFC_IPC_MSG_SS_CREATE_INFO.
 {
    WFC_IPC_MSG_SS_CREATE_INFO_T msg;
    VCOS_STATUS_T status;
    WFCNativeStreamType result = WFC_INVALID_HANDLE;
    size_t result_len = sizeof(result);
    vcos_log_trace("%s: stream 0x%x flags 0x%x pid 0x%x%08x", VCOS_FUNCTION, stream, flags, pid_hi, pid_lo);
    msg.header.type = WFC_IPC_MSG_SS_CREATE_INFO;
    msg.stream = stream;
    memset(&msg.info, 0, sizeof(msg.info));
    msg.info.size = sizeof(msg.info);
    msg.info.flags = flags;
    msg.pid_lo = pid_lo;
    msg.pid_hi = pid_hi;
    status = wfc_client_ipc_sendwait(&msg.header, sizeof(msg), &result, &result_len);
    vcos_log_trace("%s: status 0x%x, result 0x%x", VCOS_FUNCTION, status, result);
    if (status != VCOS_SUCCESS)
       result = WFC_INVALID_HANDLE;
    return result;
 }
wfc_server_stream_create_info()
WFCNativeStreamType wfc_server_stream_create_info (WFCNativeStreamType stream, const WFC_STREAM_INFO_T * info, uint32_t pid_lo, uint32_t pid_hi)
Create a stream and its buffers, for supplying pixel data to one or more elements, and optionally for storing the output of off-screen composition.
Parameters
stream The client stream identifier.
info Stream configuration.
pid_lo The low 32-bits of the owning client process identifier.
pid_hi The high 32-bits of the owning client process identifier.
Returns
The client stream identifier on success, or WFC_INVALID_HANDLE on error.
Definition at line 295 of file wfc_client_server_api.c.
References WFC_STREAM_INFO_T::flags, WFC_IPC_MSG_SS_CREATE_INFO_T::header, WFC_IPC_MSG_SS_CREATE_INFO_T::info, WFC_IPC_MSG_SS_CREATE_INFO_T::pid_hi, WFC_IPC_MSG_SS_CREATE_INFO_T::pid_lo, WFC_STREAM_INFO_T::size, status, WFC_IPC_MSG_SS_CREATE_INFO_T::stream, WFC_IPC_MSG_HEADER_T::type, VCOS_FUNCTION, vcos_min, VCOS_SUCCESS, wfc_client_ipc_sendwait(), WFC_INVALID_HANDLE, and WFC_IPC_MSG_SS_CREATE_INFO.
 {
    WFC_IPC_MSG_SS_CREATE_INFO_T msg;
    uint32_t copy_size;
    VCOS_STATUS_T status;
    WFCNativeStreamType result = WFC_INVALID_HANDLE;
    size_t result_len = sizeof(result);
    if (!info)
    {
       vcos_log_error("%s: NULL info pointer passed", VCOS_FUNCTION);
       return WFC_INVALID_HANDLE;
    }
    if (info->size < sizeof(uint32_t))
    {
       vcos_log_error("%s: invalid info pointer passed (size:%u)", VCOS_FUNCTION, info->size);
       return WFC_INVALID_HANDLE;
    }
    vcos_log_trace("%s: stream 0x%x flags 0x%x pid 0x%x%08x", VCOS_FUNCTION, stream, info->flags, pid_hi, pid_lo);
    msg.header.type = WFC_IPC_MSG_SS_CREATE_INFO;
    msg.stream = stream;
    copy_size = vcos_min(info->size, sizeof(msg.info));
    memcpy(&msg.info, info, copy_size);
    msg.info.size = copy_size;
    msg.pid_lo = pid_lo;
    msg.pid_hi = pid_hi;
    status = wfc_client_ipc_sendwait(&msg.header, sizeof(msg), &result, &result_len);
    vcos_log_trace("%s: status 0x%x, result 0x%x", VCOS_FUNCTION, status, result);
    if (status != VCOS_SUCCESS)
       result = WFC_INVALID_HANDLE;
    return result;
 }
wfc_server_stream_destroy()
void wfc_server_stream_destroy (WFCNativeStreamType stream, uint32_t pid_lo, uint32_t pid_hi)
Destroy a stream.
Parameters
stream The client stream identifier.
pid_lo The low 32-bits of the owning client process identifier.
pid_hi The high 32-bits of the owning client process identifier.
Definition at line 337 of file wfc_client_server_api.c.
References WFC_IPC_MSG_SS_DESTROY_T::header, WFC_IPC_MSG_SS_DESTROY_T::pid_hi, WFC_IPC_MSG_SS_DESTROY_T::pid_lo, status, WFC_IPC_MSG_SS_DESTROY_T::stream, WFC_IPC_MSG_HEADER_T::type, vcos_assert, VCOS_FUNCTION, VCOS_SUCCESS, wfc_client_ipc_send(), and WFC_IPC_MSG_SS_DESTROY.
 {
    WFC_IPC_MSG_SS_DESTROY_T msg;
    VCOS_STATUS_T status;
    vcos_log_trace("%s: stream 0x%x", VCOS_FUNCTION, stream);
    msg.header.type = WFC_IPC_MSG_SS_DESTROY;
    msg.stream = stream;
    msg.pid_lo = pid_lo;
    msg.pid_hi = pid_hi;
    status = wfc_client_ipc_send(&msg.header, sizeof(msg));
    vcos_assert(status == VCOS_SUCCESS);
 }
wfc_server_stream_get_info()
uint32_t wfc_server_stream_get_info (WFCNativeStreamType stream, WFC_STREAM_INFO_T * info)
Retrieve the stream configuration information, if available.
Parameters
stream The client stream identifier.
info Address of block to receive the information on success.
Returns
VCOS_SUCCESS if successful, or an error code if not.
Definition at line 605 of file wfc_client_server_api.c.
References WFC_STREAM_INFO_T::size, status, VCOS_FUNCTION, and WFC_INVALID_HANDLE.
Referenced by wfc_stream_register().
 {
    uint32_t result;
    VCOS_STATUS_T status;
    WFC_IPC_MSG_SS_GET_INFO_T reply;
    size_t info_len = sizeof(reply) - sizeof(WFC_IPC_MSG_HEADER_T);
    if (!info)
    {
       vcos_log_error("%s: NULL info pointer passed", VCOS_FUNCTION);
       return WFC_INVALID_HANDLE;
    }
    if (info->size < sizeof(uint32_t))
    {
       vcos_log_error("%s: invalid info pointer passed (size:%u)", VCOS_FUNCTION, info->size);
       return WFC_INVALID_HANDLE;
    }
    vcos_log_trace("%s: stream 0x%x", VCOS_FUNCTION, stream);
    memset(&reply, 0, sizeof(reply));
    status = wfc_client_server_api_sendwait_stream(WFC_IPC_MSG_SS_GET_INFO, stream, &reply.result, &info_len);
    if (status == VCOS_SUCCESS)
    {
       result = reply.result;
       if (result == VCOS_SUCCESS)
       {
          uint32_t copy_size = vcos_min(info->size, reply.info.size);
          memcpy(info, &reply.info, copy_size);
          info->size = copy_size;
          vcos_log_trace("%s: copied %u bytes", VCOS_FUNCTION, copy_size);
       }
       else
       {
          vcos_log_error("%s: result %d", VCOS_FUNCTION, result);
       }
    }
    else
    {
       vcos_log_error("%s: send msg status %d", VCOS_FUNCTION, status);
       result = status;
    }
    return result;
 }
wfc_server_stream_get_rects()
uint32_t wfc_server_stream_get_rects (WFCNativeStreamType stream, int32_t rects[WFC_SERVER_STREAM_RECTS_SIZE])
Definition at line 378 of file wfc_client_server_api.c.
References status, and VCOS_FUNCTION.
 {
    uint32_t result;
    VCOS_STATUS_T status;
    WFC_IPC_MSG_SS_GET_RECTS_T reply;
    size_t rects_len = sizeof(reply) - sizeof(WFC_IPC_MSG_HEADER_T);
    vcos_log_trace("%s: stream 0x%x", VCOS_FUNCTION, stream);
    memset(&reply, 0, sizeof(reply));
    status = wfc_client_server_api_sendwait_stream(WFC_IPC_MSG_SS_GET_RECTS, stream, &reply.result, &rects_len);
    if (status == VCOS_SUCCESS)
    {
       result = reply.result;
       if (result == VCOS_SUCCESS)
       {
          memcpy(rects, reply.rects, WFC_SERVER_STREAM_RECTS_SIZE * sizeof(*rects));
          vcos_log_trace("%s: rects (%d,%d,%d,%d) (%d,%d,%d,%d)", VCOS_FUNCTION,
                rects[0], rects[1], rects[2], rects[3], rects[4], rects[5], rects[6], rects[7]);
       }
       else
       {
          vcos_log_error("%s: result %d", VCOS_FUNCTION, result);
       }
    }
    else
    {
       vcos_log_error("%s: send msg status %d", VCOS_FUNCTION, status);
       result = status;
    }
    return result;
 }
wfc_server_stream_is_in_use()
bool wfc_server_stream_is_in_use (WFCNativeStreamType stream)
Returns true if given stream number is currently in use.
Parameters
stream The client stream identifier.
Returns
True if the client stream identifier is already in use, false if not.
Definition at line 415 of file wfc_client_server_api.c.
References status, and VCOS_FUNCTION.
 {
    VCOS_STATUS_T status;
    uint32_t result = 0;
    size_t result_len = sizeof(result);
    vcos_log_trace("%s: stream 0x%x", VCOS_FUNCTION, stream);
    status = wfc_client_server_api_sendwait_stream(WFC_IPC_MSG_SS_IS_IN_USE, stream, &result, &result_len);
    vcos_log_trace("%s: status 0x%x, result %u", VCOS_FUNCTION, status, result);
    if (status != VCOS_SUCCESS)
       result = 0;
    return result != 0;
 }
wfc_server_stream_on_image_available()
void wfc_server_stream_on_image_available (WFCNativeStreamType stream, WFC_CALLBACK_T image_available_cb, void * image_available_data)
Set callback for when there is an image available. The stream must have been created with either the WFC_STREAM_FLAGS_EGL or WFC_STREAM_FLAGS_BUF_AVAIL flags set.
Parameters
stream The client stream identifier.
image_available_cb Called when there is an image available.
image_available_data Passed to the callback.
Definition at line 655 of file wfc_client_server_api.c.
References WFC_IPC_MSG_SS_ON_IMAGE_AVAILABLE_T::header, WFC_IPC_MSG_SS_ON_IMAGE_AVAILABLE_T::image_available_cb, WFC_IPC_MSG_SS_ON_IMAGE_AVAILABLE_T::image_available_data, status, WFC_IPC_MSG_SS_ON_IMAGE_AVAILABLE_T::stream, WFC_IPC_MSG_HEADER_T::type, VCOS_FUNCTION, VCOS_SUCCESS, vcos_verify, wfc_client_ipc_send(), and WFC_IPC_MSG_SS_ON_IMAGE_AVAILABLE.
 {
    WFC_IPC_MSG_SS_ON_IMAGE_AVAILABLE_T msg;
    VCOS_STATUS_T status;
    vcos_log_trace("%s: stream 0x%x cb %p data %p", VCOS_FUNCTION, stream, image_available_cb, image_available_data);
    msg.header.type = WFC_IPC_MSG_SS_ON_IMAGE_AVAILABLE;
    msg.stream = stream;
    msg.image_available_cb.ptr = image_available_cb;
    msg.image_available_data.ptr = image_available_data;
    status = wfc_client_ipc_send(&msg.header, sizeof(msg));
    if (!vcos_verify(status == VCOS_SUCCESS))
    {
       (*image_available_cb)(image_available_data);
    }
 }
wfc_server_stream_on_rects_change()
void wfc_server_stream_on_rects_change (WFCNativeStreamType stream, WFC_CALLBACK_T rects_change_cb, void * rects_change_data)
Set callback for when src/dest rectangles are updated.
Parameters
stream The client stream identifier.
rects_change_cb Called when either src or dest rectangles have been updated.
rects_change_data Passed to the callback.
Returns
VCOS_SUCCESS if successful, or an error code if not.
Definition at line 356 of file wfc_client_server_api.c.
References WFC_IPC_MSG_SS_ON_RECTS_CHANGE_T::header, WFC_IPC_MSG_SS_ON_RECTS_CHANGE_T::rects_change_cb, WFC_IPC_MSG_SS_ON_RECTS_CHANGE_T::rects_change_data, status, WFC_IPC_MSG_SS_ON_RECTS_CHANGE_T::stream, WFC_IPC_MSG_HEADER_T::type, VCOS_FUNCTION, VCOS_SUCCESS, vcos_verify, wfc_client_ipc_send(), and WFC_IPC_MSG_SS_ON_RECTS_CHANGE.
 {
    WFC_IPC_MSG_SS_ON_RECTS_CHANGE_T msg;
    VCOS_STATUS_T status;
    vcos_log_trace("%s: stream 0x%x cb %p data %p", VCOS_FUNCTION, stream, rects_change_cb, rects_change_data);
    msg.header.type = WFC_IPC_MSG_SS_ON_RECTS_CHANGE;
    msg.stream = stream;
    msg.rects_change_cb.ptr = rects_change_cb;
    msg.rects_change_data.ptr = rects_change_data;
    status = wfc_client_ipc_send(&msg.header, sizeof(msg));
    if (!vcos_verify(status == VCOS_SUCCESS))
    {
       (*rects_change_cb)(rects_change_data);
    }
 }
wfc_server_stream_register()
void wfc_server_stream_register (WFCNativeStreamType stream, uint32_t pid_lo, uint32_t pid_hi)
Register a stream as in use by a given process.
Parameters
stream The client stream identifier.
pid_lo The low 32-bits of the process ID.
pid_hi The high 32-bits of the process ID.
Definition at line 567 of file wfc_client_server_api.c.
References WFC_IPC_MSG_SS_REGISTER_T::header, WFC_IPC_MSG_SS_REGISTER_T::pid_hi, WFC_IPC_MSG_SS_REGISTER_T::pid_lo, status, WFC_IPC_MSG_SS_REGISTER_T::stream, WFC_IPC_MSG_HEADER_T::type, vcos_assert, VCOS_FUNCTION, VCOS_SUCCESS, wfc_client_ipc_send(), and WFC_IPC_MSG_SS_REGISTER.
 {
    WFC_IPC_MSG_SS_REGISTER_T msg;
    VCOS_STATUS_T status;
    vcos_log_trace("%s: stream 0x%x pid 0x%x%08x", VCOS_FUNCTION, stream, pid_hi, pid_lo);
    msg.header.type = WFC_IPC_MSG_SS_REGISTER;
    msg.stream = stream;
    msg.pid_lo = pid_lo;
    msg.pid_hi = pid_hi;
    status = wfc_client_ipc_send(&msg.header, sizeof(msg));
    vcos_assert(status == VCOS_SUCCESS);
 }
wfc_server_stream_signal_eglimage_data()
void wfc_server_stream_signal_eglimage_data (WFCNativeStreamType stream, uint32_t ustorage, uint32_t width, uint32_t height, uint32_t stride, uint32_t offset, uint32_t format, uint32_t flags, bool flip)
Signal that the given EGLImageKHR is the new front image for the stream.
Parameters
stream The client stream identifier.
ustorage The innards of KHRN_IMAGE_T
width etc..
height etc...
stride
offset
format
flags
flip
Definition at line 462 of file wfc_client_server_api.c.
References WFC_IPC_MSG_SS_SIGNAL_EGLIMAGE_DATA_T::flags, WFC_IPC_MSG_SS_SIGNAL_EGLIMAGE_DATA_T::flip, WFC_IPC_MSG_SS_SIGNAL_EGLIMAGE_DATA_T::format, WFC_IPC_MSG_SS_SIGNAL_EGLIMAGE_DATA_T::header, WFC_IPC_MSG_SS_SIGNAL_EGLIMAGE_DATA_T::height, offset, WFC_IPC_MSG_SS_SIGNAL_EGLIMAGE_DATA_T::offset, status, WFC_IPC_MSG_SS_SIGNAL_EGLIMAGE_DATA_T::stream, WFC_IPC_MSG_SS_SIGNAL_EGLIMAGE_DATA_T::stride, WFC_IPC_MSG_HEADER_T::type, WFC_IPC_MSG_SS_SIGNAL_EGLIMAGE_DATA_T::ustorage, vcos_assert, VCOS_FUNCTION, VCOS_SUCCESS, wfc_client_ipc_send(), WFC_IPC_MSG_SS_SIGNAL_EGLIMAGE_DATA, and WFC_IPC_MSG_SS_SIGNAL_EGLIMAGE_DATA_T::width.
 {
    WFC_IPC_MSG_SS_SIGNAL_EGLIMAGE_DATA_T msg;
    VCOS_STATUS_T status;
    memset(&msg, 0, sizeof msg);
    msg.header.type = WFC_IPC_MSG_SS_SIGNAL_EGLIMAGE_DATA;
    msg.stream = stream;
    msg.ustorage = ustorage;
    msg.width = width;
    msg.height = height;
    msg.stride = stride;
    msg.offset = offset;
    msg.format = format;
    msg.flags = flags;
    msg.flip = flip;
    vcos_log_trace("%s: stream 0x%x image storage 0x%x",
          VCOS_FUNCTION, stream, ustorage);
    status = wfc_client_ipc_send(&msg.header, sizeof(msg));
    vcos_assert(status == VCOS_SUCCESS);
 }
wfc_server_stream_signal_image()
void wfc_server_stream_signal_image (WFCNativeStreamType stream, const WFC_STREAM_IMAGE_T * image)
Signal that the given image is the new front image for the stream.
The type of each image the stream must be the same e.g. it is not permitted to mix opaque and raw pixel multimedia images within the same stream.
Parameters
stream The client stream identifier.
image Structure describing the image.
Definition at line 534 of file wfc_client_server_api.c.
References WFC_STREAM_IMAGE_T::format, WFC_STREAM_IMAGE_T::handle, WFC_IPC_MSG_SS_SIGNAL_IMAGE_T::header, WFC_STREAM_IMAGE_T::height, WFC_IPC_MSG_SS_SIGNAL_IMAGE_T::image, WFC_STREAM_IMAGE_T::length, WFC_STREAM_IMAGE_T::pitch, WFC_STREAM_IMAGE_T::protection, status, WFC_IPC_MSG_SS_SIGNAL_IMAGE_T::stream, WFC_IPC_MSG_HEADER_T::type, WFC_STREAM_IMAGE_T::type, vcos_assert, VCOS_FUNCTION, VCOS_SUCCESS, vcos_verify, WFC_STREAM_IMAGE_T::vpitch, wfc_client_ipc_send(), WFC_IPC_MSG_SS_SIGNAL_IMAGE, and WFC_STREAM_IMAGE_T::width.
Referenced by wfc_stream_signal_image().
 {
    WFC_IPC_MSG_SS_SIGNAL_IMAGE_T msg;
    VCOS_STATUS_T status;
    vcos_log_trace("%s: stream 0x%x type 0x%x handle 0x%x "
          " format 0x%x protection 0x%x width %u height %u "
          " pitch %u vpitch %u",
          VCOS_FUNCTION, stream, image->type, image->handle,
          image->format, image->protection, image->width, image->height,
          image->pitch, image->vpitch);
    msg.header.type = WFC_IPC_MSG_SS_SIGNAL_IMAGE;
    msg.stream = stream;
    if vcos_verify(image->length <= sizeof(msg.image))
    {
       msg.image = *image;
    }
    else
    {
       /* Client is newer than VC ? */
       memcpy(&msg.image, image, sizeof(msg.image));
       msg.image.length = sizeof(msg.image);
    }
    status = wfc_client_ipc_send(&msg.header, sizeof(msg));
    vcos_assert(status == VCOS_SUCCESS);
 }
wfc_server_stream_signal_mm_image_data()
void wfc_server_stream_signal_mm_image_data (WFCNativeStreamType stream, uint32_t image_handle)
Signal that the given multimedia image handle is the new front image for the stream.
Parameters
stream The client stream identifier.
image_handle The new front image for the stream.
Definition at line 491 of file wfc_client_server_api.c.
References WFC_IPC_MSG_SS_SIGNAL_MM_IMAGE_DATA_T::header, WFC_IPC_MSG_SS_SIGNAL_MM_IMAGE_DATA_T::image_handle, status, WFC_IPC_MSG_SS_SIGNAL_MM_IMAGE_DATA_T::stream, WFC_IPC_MSG_HEADER_T::type, vcos_assert, VCOS_FUNCTION, VCOS_SUCCESS, wfc_client_ipc_send(), and WFC_IPC_MSG_SS_SIGNAL_MM_IMAGE_DATA.
Referenced by wfc_stream_signal_mm_image_data().
 {
    WFC_IPC_MSG_SS_SIGNAL_MM_IMAGE_DATA_T msg;
    VCOS_STATUS_T status;
    vcos_log_trace("%s: stream 0x%x image 0x%x", VCOS_FUNCTION, stream, image_handle);
    msg.header.type = WFC_IPC_MSG_SS_SIGNAL_MM_IMAGE_DATA;
    msg.stream = stream;
    msg.image_handle = image_handle;
    status = wfc_client_ipc_send(&msg.header, sizeof(msg));
    vcos_assert(status == VCOS_SUCCESS);
 }
wfc_server_stream_signal_raw_pixels()
void wfc_server_stream_signal_raw_pixels (WFCNativeStreamType stream, uint32_t handle, uint32_t format, uint32_t width, uint32_t height, uint32_t pitch, uint32_t vpitch)
Signal that a raw image memhandle is the new front image for the stream.
Parameters
stream The client stream identifier.
handle The new front image memhandle for the stream.
format The image format. See WFC_PIXEL_FORMAT_T for supported formats.
width The image width, in pixels.
height The image height, in pixels.
pitch The image pitch, in bytes.
vpitch The image vertical pitch, in pixels.
Definition at line 509 of file wfc_client_server_api.c.
References WFC_IPC_MSG_SS_SIGNAL_RAW_PIXELS_T::format, WFC_IPC_MSG_SS_SIGNAL_RAW_PIXELS_T::handle, WFC_IPC_MSG_SS_SIGNAL_RAW_PIXELS_T::header, WFC_IPC_MSG_SS_SIGNAL_RAW_PIXELS_T::height, WFC_IPC_MSG_SS_SIGNAL_RAW_PIXELS_T::pitch, status, WFC_IPC_MSG_SS_SIGNAL_RAW_PIXELS_T::stream, WFC_IPC_MSG_HEADER_T::type, vcos_assert, VCOS_FUNCTION, VCOS_SUCCESS, WFC_IPC_MSG_SS_SIGNAL_RAW_PIXELS_T::vpitch, wfc_client_ipc_send(), WFC_IPC_MSG_SS_SIGNAL_RAW_PIXELS, and WFC_IPC_MSG_SS_SIGNAL_RAW_PIXELS_T::width.
Referenced by wfc_stream_signal_raw_pixels().
 {
    WFC_IPC_MSG_SS_SIGNAL_RAW_PIXELS_T msg;
    VCOS_STATUS_T status;
    vcos_log_trace("%s: stream 0x%x image 0x%x format 0x%x width %u height %u"
          " pitch %u vpitch %u",
          VCOS_FUNCTION, stream, handle, format, width, height, pitch, vpitch);
    msg.header.type = WFC_IPC_MSG_SS_SIGNAL_RAW_PIXELS;
    msg.stream = stream;
    msg.handle = handle;
    msg.format = format;
    msg.width = width;
    msg.height = height;
    msg.pitch = pitch;
    msg.vpitch = vpitch;
    status = wfc_client_ipc_send(&msg.header, sizeof(msg));
    vcos_assert(status == VCOS_SUCCESS);
 }
wfc_server_stream_unregister()
void wfc_server_stream_unregister (WFCNativeStreamType stream, uint32_t pid_lo, uint32_t pid_hi)
Unregister a stream as in use by a given process.
Parameters
stream The client stream identifier.
pid_lo The low 32-bits of the process ID.
pid_hi The high 32-bits of the process ID.
Definition at line 586 of file wfc_client_server_api.c.
References WFC_IPC_MSG_SS_UNREGISTER_T::header, WFC_IPC_MSG_SS_UNREGISTER_T::pid_hi, WFC_IPC_MSG_SS_UNREGISTER_T::pid_lo, status, WFC_IPC_MSG_SS_UNREGISTER_T::stream, WFC_IPC_MSG_HEADER_T::type, vcos_assert, VCOS_FUNCTION, VCOS_SUCCESS, wfc_client_ipc_send(), and WFC_IPC_MSG_SS_UNREGISTER.
 {
    WFC_IPC_MSG_SS_UNREGISTER_T msg;
    VCOS_STATUS_T status;
    vcos_log_trace("%s: stream 0x%x pid 0x%x%08x", VCOS_FUNCTION, stream, pid_hi, pid_lo);
    msg.header.type = WFC_IPC_MSG_SS_UNREGISTER;
    msg.stream = stream;
    msg.pid_lo = pid_lo;
    msg.pid_hi = pid_hi;
    status = wfc_client_ipc_send(&msg.header, sizeof(msg));
    vcos_assert(status == VCOS_SUCCESS);
 }
wfc_server_use_keep_alive()
void wfc_server_use_keep_alive (void)
Increase the keep alive count by one. If it rises from zero, the VideoCore will be prevented from being suspended.
Definition at line 118 of file wfc_client_server_api.c.
References wfc_client_ipc_use_keep_alive().
 {
    wfc_client_ipc_use_keep_alive();
 }