VideoCore Library: containers/core/containers_writer_utils.h File Reference
containers_writer_utils.h File Reference
#include "containers/containers.h"
#include "containers/containers_codecs.h"
#include "containers/core/containers_io_helpers.h"
Classes
struct VC_CONTAINER_WRITER_EXTRAIO_T
Typedefs
typedef struct VC_CONTAINER_WRITER_EXTRAIO_T VC_CONTAINER_WRITER_EXTRAIO_T
Functions
STATIC_INLINE VC_CONTAINER_STATUS_T vc_container_write_waveformatex (VC_CONTAINER_T *p_ctx, VC_CONTAINER_ES_FORMAT_T *format)
STATIC_INLINE VC_CONTAINER_STATUS_T vc_container_write_bitmapinfoheader (VC_CONTAINER_T *p_ctx, VC_CONTAINER_ES_FORMAT_T *format)
VC_CONTAINER_STATUS_T vc_container_writer_extraio_create_null (VC_CONTAINER_T *context, VC_CONTAINER_WRITER_EXTRAIO_T *null)
VC_CONTAINER_STATUS_T vc_container_writer_extraio_create_temp (VC_CONTAINER_T *context, VC_CONTAINER_WRITER_EXTRAIO_T *null)
VC_CONTAINER_STATUS_T vc_container_writer_extraio_delete (VC_CONTAINER_T *context, VC_CONTAINER_WRITER_EXTRAIO_T *null)
int64_t vc_container_writer_extraio_enable (VC_CONTAINER_T *context, VC_CONTAINER_WRITER_EXTRAIO_T *null)
int64_t vc_container_writer_extraio_disable (VC_CONTAINER_T *context, VC_CONTAINER_WRITER_EXTRAIO_T *null)
Detailed Description
Helper functions and macros for container writers
Definition in file containers_writer_utils.h.
Typedef Documentation
VC_CONTAINER_WRITER_EXTRAIO_T
typedef struct VC_CONTAINER_WRITER_EXTRAIO_T VC_CONTAINER_WRITER_EXTRAIO_T
Function Documentation
vc_container_write_bitmapinfoheader()
STATIC_INLINE VC_CONTAINER_STATUS_T vc_container_write_bitmapinfoheader (VC_CONTAINER_T * p_ctx, VC_CONTAINER_ES_FORMAT_T * format)
Definition at line 58 of file containers_writer_utils.h.
References VC_CONTAINER_ES_FORMAT_T::codec, codec_to_vfw_fourcc(), VC_CONTAINER_ES_FORMAT_T::extradata, VC_CONTAINER_ES_FORMAT_T::extradata_size, fourcc, VC_CONTAINER_VIDEO_FORMAT_T::height, LOG_FORMAT, STREAM_STATUS, VC_CONTAINER_ES_FORMAT_T::type, VC_CONTAINER_ES_SPECIFIC_FORMAT_T::video, VC_CONTAINER_VIDEO_FORMAT_T::width, WRITE_BYTES, WRITE_U16, and WRITE_U32.
 {
    VC_CONTAINER_FOURCC_T fourcc;
    /* Write bitmapinfoheader structure */
    WRITE_U32(p_ctx, 40, "Format Data Size");
    WRITE_U32(p_ctx, format->type->video.width, "Image Width");
    WRITE_U32(p_ctx, format->type->video.height, "Image Height");
    WRITE_U16(p_ctx, 0, "Reserved");
    WRITE_U16(p_ctx, 0, "Bits Per Pixel Count");
    fourcc = codec_to_vfw_fourcc(format->codec);
    WRITE_BYTES(p_ctx, (char *)&fourcc, 4); /* Compression ID */
    LOG_FORMAT(p_ctx, "Compression ID: %4.4s", (char *)&fourcc);
    WRITE_U32(p_ctx, 0, "Image Size");
    WRITE_U32(p_ctx, 0, "Horizontal Pixels Per Meter");
    WRITE_U32(p_ctx, 0, "Vertical Pixels Per Meter");
    WRITE_U32(p_ctx, 0, "Colors Used Count");
    WRITE_U32(p_ctx, 0, "Important Colors Count");
    WRITE_BYTES(p_ctx, format->extradata, format->extradata_size);
    return STREAM_STATUS(p_ctx);
 }
vc_container_write_waveformatex()
STATIC_INLINE VC_CONTAINER_STATUS_T vc_container_write_waveformatex (VC_CONTAINER_T * p_ctx, VC_CONTAINER_ES_FORMAT_T * format)
Definition at line 42 of file containers_writer_utils.h.
References VC_CONTAINER_ES_SPECIFIC_FORMAT_T::audio, VC_CONTAINER_ES_FORMAT_T::bitrate, VC_CONTAINER_AUDIO_FORMAT_T::bits_per_sample, VC_CONTAINER_AUDIO_FORMAT_T::block_align, VC_CONTAINER_AUDIO_FORMAT_T::channels, VC_CONTAINER_ES_FORMAT_T::codec, codec_to_waveformat(), VC_CONTAINER_ES_FORMAT_T::extradata, VC_CONTAINER_ES_FORMAT_T::extradata_size, VC_CONTAINER_AUDIO_FORMAT_T::sample_rate, STREAM_STATUS, VC_CONTAINER_ES_FORMAT_T::type, WRITE_BYTES, WRITE_U16, and WRITE_U32.
 {
    /* Write waveformatex structure */
    WRITE_U16(p_ctx, codec_to_waveformat(format->codec), "Codec ID");
    WRITE_U16(p_ctx, format->type->audio.channels, "Number of Channels");
    WRITE_U32(p_ctx, format->type->audio.sample_rate, "Samples per Second");
    WRITE_U32(p_ctx, format->bitrate >> 3, "Average Number of Bytes Per Second");
    WRITE_U16(p_ctx, format->type->audio.block_align, "Block Alignment");
    WRITE_U16(p_ctx, format->type->audio.bits_per_sample, "Bits Per Sample");
    WRITE_U16(p_ctx, format->extradata_size, "Codec Specific Data Size");
    WRITE_BYTES(p_ctx, format->extradata, format->extradata_size);
    return STREAM_STATUS(p_ctx);
 }
vc_container_writer_extraio_create_null()
VC_CONTAINER_STATUS_T vc_container_writer_extraio_create_null (VC_CONTAINER_T * context, VC_CONTAINER_WRITER_EXTRAIO_T * null)
Definition at line 53 of file containers_writer_utils.c.
Referenced by asf_writer_open(), avi_writer_open(), and mp4_writer_open().
 {
    return vc_container_writer_extraio_create(context, "null://", extraio);
 }
vc_container_writer_extraio_create_temp()
VC_CONTAINER_STATUS_T vc_container_writer_extraio_create_temp (VC_CONTAINER_T * context, VC_CONTAINER_WRITER_EXTRAIO_T * null)
Definition at line 59 of file containers_writer_utils.c.
Referenced by avi_writer_open(), and mp4_writer_open().
 {
    VC_CONTAINER_STATUS_T status = VC_CONTAINER_SUCCESS;
    unsigned int length = strlen(context->priv->io->uri) + 5;
    char *uri = malloc(length);
    if(!uri) return VC_CONTAINER_ERROR_OUT_OF_MEMORY;
    snprintf(uri, length, "%s.tmp", context->priv->io->uri);
    status = vc_container_writer_extraio_create(context, uri, extraio);
    free(uri);
    extraio->temp = true;
    if(status == VC_CONTAINER_SUCCESS && !context->priv->tmp_io)
       context->priv->tmp_io = extraio->io;
    return status;
 }
vc_container_writer_extraio_delete()
VC_CONTAINER_STATUS_T vc_container_writer_extraio_delete (VC_CONTAINER_T * context, VC_CONTAINER_WRITER_EXTRAIO_T * null)
Definition at line 78 of file containers_writer_utils.c.
 {
    VC_CONTAINER_STATUS_T status;
    char *uri = extraio->temp ? vcos_strdup(extraio->io->uri) : 0;
    while(extraio->refcount) vc_container_writer_extraio_disable(context, extraio);
    status = vc_container_io_close( extraio->io );
    /* coverity[check_return] On failure the worst case is a file or directory is not removed */
    if(uri) remove(uri);
    if(uri) free(uri);
    if(context->priv->tmp_io == extraio->io)
       context->priv->tmp_io = 0;
    return status;
 }
vc_container_writer_extraio_disable()
int64_t vc_container_writer_extraio_disable (VC_CONTAINER_T * context, VC_CONTAINER_WRITER_EXTRAIO_T * null)
Definition at line 112 of file containers_writer_utils.c.
 {
    VC_CONTAINER_IO_T *tmp;
    if(extraio->refcount)
    {
       extraio->refcount--;
       if(!extraio->refcount)
       {
          tmp = context->priv->io;
          context->priv->io = extraio->io;
          extraio->io = tmp;
       }
    }
    return extraio->refcount;
 }
vc_container_writer_extraio_enable()
int64_t vc_container_writer_extraio_enable (VC_CONTAINER_T * context, VC_CONTAINER_WRITER_EXTRAIO_T * null)
Definition at line 97 of file containers_writer_utils.c.
 {
    VC_CONTAINER_IO_T *tmp;
    if(!extraio->refcount)
    {
       vc_container_io_seek(extraio->io, INT64_C(0));
       tmp = context->priv->io;
       context->priv->io = extraio->io;
       extraio->io = tmp;
    }
    return extraio->refcount++;
 }