VideoCore Library: interface/khronos/vg/vg_client.h File Reference
vg_client.h File Reference
#include "interface/khronos/common/khrn_client.h"
#include "interface/khronos/common/khrn_client_platform.h"
#include "interface/khronos/common/khrn_client_pointermap.h"
#include "interface/khronos/common/khrn_client_vector.h"
#include "interface/khronos/egl/egl_client_context.h"
#include "interface/khronos/include/EGL/egl.h"
#include "interface/khronos/include/EGL/eglext.h"
#include "interface/khronos/include/VG/openvg.h"
#include "interface/khronos/vg/vg_int_config.h"
#include "interface/khronos/vg/vg_int.h"
#include "interface/khronos/vg/vg_int_mat3x3.h"
Classes
struct VG_CLIENT_FONT_T
struct VG_CLIENT_IMAGE_T
struct VG_CLIENT_MASK_LAYER_T
struct VG_CLIENT_PAINT_GRADIENT_T
struct VG_CLIENT_PAINT_T
struct VG_CLIENT_PATH_T
struct VG_CLIENT_SHARED_STATE_T
struct VG_MAT3X3_SYNC_T
struct VG_CLIENT_STATE_T
Macros
#define VG_CLIENT_STEMS_COUNT_MAX 64
#define VG_GET_CLIENT_STATE(thread) vg_get_client_state(thread)
Typedefs
typedef void(* VG_RENDER_CALLBACK_T) (void)
typedef void(* VG_FLUSH_CALLBACK_T) (bool wait)
Functions
VG_CLIENT_SHARED_STATE_T * vg_client_shared_state_alloc (void)
void vg_client_shared_state_free (VG_CLIENT_SHARED_STATE_T *shared_state)
VG_CLIENT_STATE_T * vg_client_state_alloc (VG_CLIENT_SHARED_STATE_T *shared_state)
void vg_client_state_free (VG_CLIENT_STATE_T *state)
Macro Definition Documentation
VG_CLIENT_STEMS_COUNT_MAX
#define VG_CLIENT_STEMS_COUNT_MAX 64
Definition at line 55 of file vg_client.h.
VG_GET_CLIENT_STATE
#define VG_GET_CLIENT_STATE (thread) vg_get_client_state(thread)
Definition at line 227 of file vg_client.h.
Referenced by vgGetVectorSize().
Typedef Documentation
VG_FLUSH_CALLBACK_T
typedef void(* VG_FLUSH_CALLBACK_T) (bool wait)
Definition at line 152 of file vg_client.h.
VG_RENDER_CALLBACK_T
typedef void(* VG_RENDER_CALLBACK_T) (void)
Definition at line 145 of file vg_client.h.
Function Documentation
vg_client_shared_state_alloc()
VG_CLIENT_SHARED_STATE_T* vg_client_shared_state_alloc (void)
Definition at line 88 of file vg_client.c.
References KHR_SUCCESS, khrn_platform_free(), khrn_platform_malloc(), VG_CLIENT_SHARED_STATE_T::mutex, NULL, VG_CLIENT_SHARED_STATE_T::objects, platform_mutex_create(), platform_mutex_destroy(), VG_CLIENT_SHARED_STATE_T::ref_count, status, and VG_CLIENT_SHARED_STATE_T::stems_count.
 {
    VG_CLIENT_SHARED_STATE_T *shared_state;
    KHR_STATUS_T status;
    shared_state = (VG_CLIENT_SHARED_STATE_T *)khrn_platform_malloc(sizeof(VG_CLIENT_SHARED_STATE_T), "VG_CLIENT_SHARED_STATE_T");
    if (!shared_state) {
       return NULL;
    }
    status = platform_mutex_create(&shared_state->mutex);
    if (status != KHR_SUCCESS) {
       khrn_platform_free(shared_state);
       return NULL;
    }
    if (!khrn_pointer_map_init(&shared_state->objects, 128)) {
       platform_mutex_destroy(&shared_state->mutex);
       khrn_platform_free(shared_state);
       return NULL;
    }
    shared_state->ref_count = 1;
    shared_state->stems_count = 0;
    return shared_state;
 }
vg_client_shared_state_free()
void vg_client_shared_state_free (VG_CLIENT_SHARED_STATE_T * shared_state)
Definition at line 127 of file vg_client.c.
References VG_CLIENT_SHARED_STATE_T::objects, VG_CLIENT_SHARED_STATE_T::ref_count, and vcos_assert.
 {
    vcos_assert(shared_state->ref_count == 0);
    khrn_pointer_map_iterate(&shared_state->objects, object_free_callback, NULL);
    khrn_pointer_map_term(&shared_state->objects);
    platform_mutex_destroy(&shared_state->mutex);
    khrn_platform_free(shared_state);
 }
vg_client_state_alloc()
VG_CLIENT_STATE_T* vg_client_state_alloc (VG_CLIENT_SHARED_STATE_T * shared_state)
Definition at line 140 of file vg_client.c.
 {
    VGuint i;
    VG_CLIENT_STATE_T *state = (VG_CLIENT_STATE_T *)khrn_platform_malloc(sizeof(VG_CLIENT_STATE_T), "VG_CLIENT_STATE_T");
    if (!state) {
       return NULL;
    }
    vg_client_shared_state_acquire(shared_state);
    state->shared_state = shared_state;
    state->render_callback = NULL;
    state->flush_callback = NULL;
    state->matrix_mode = VG_MATRIX_PATH_USER_TO_SURFACE;
    for (i = 0; i != ARR_COUNT(state->matrices); ++i) {
       vg_mat3x3_set_identity(&state->matrices[i].client);
       vg_mat3x3_set_identity(&state->matrices[i].server);
    }
    state->fill_rule = VG_EVEN_ODD;
    state->stroke_line_width = 1.0f;
    state->stroke_cap_style = VG_CAP_BUTT;
    state->stroke_join_style = VG_JOIN_MITER;
    state->stroke_miter_limit = 4.0f;
    state->stroke_dash_pattern_count = 0;
    state->stroke_dash_phase = 0.0f;
    state->stroke_dash_phase_reset = false;
    state->image_quality = VG_IMAGE_QUALITY_FASTER;
    state->image_mode = VG_DRAW_IMAGE_NORMAL;
    state->scissoring = false;
    state->scissor_rects_count = 0;
    state->rendering_quality = VG_RENDERING_QUALITY_BETTER;
    state->fill_paint = VG_INVALID_HANDLE;
    state->stroke_paint = VG_INVALID_HANDLE;
    state->tile_fill_color[0] = 0.0f;
    state->tile_fill_color[1] = 0.0f;
    state->tile_fill_color[2] = 0.0f;
    state->tile_fill_color[3] = 0.0f;
    state->clear_color[0] = 0.0f;
    state->clear_color[1] = 0.0f;
    state->clear_color[2] = 0.0f;
    state->clear_color[3] = 0.0f;
    state->color_transform = false;
    state->color_transform_values[0] = 1.0f;
    state->color_transform_values[1] = 1.0f;
    state->color_transform_values[2] = 1.0f;
    state->color_transform_values[3] = 1.0f;
    state->color_transform_values[4] = 0.0f;
    state->color_transform_values[5] = 0.0f;
    state->color_transform_values[6] = 0.0f;
    state->color_transform_values[7] = 0.0f;
    state->blend_mode = VG_BLEND_SRC_OVER;
    state->masking = false;
    state->filter_format_linear = false;
    state->filter_format_pre = false;
    state->filter_channel_mask = VG_RED | VG_GREEN | VG_BLUE | VG_ALPHA;
    state->pixel_layout = VG_PIXEL_LAYOUT_UNKNOWN;
    return state;
 }
vg_client_state_free()
void vg_client_state_free (VG_CLIENT_STATE_T * state)
Definition at line 210 of file vg_client.c.
 {
    vg_client_shared_state_release(state->shared_state);
    khrn_platform_free(state);
 }