VideoCore Library: containers/mpeg/ps_reader.c File Reference
ps_reader.c File Reference
#include <stdlib.h>
#include <string.h>
#include "containers/core/containers_bits.h"
#include "containers/core/containers_private.h"
#include "containers/core/containers_io_helpers.h"
#include "containers/core/containers_utils.h"
#include "containers/core/containers_logging.h"
Classes
struct VC_CONTAINER_TRACK_MODULE_T
struct VC_CONTAINER_MODULE_T
Macros
#define CONTAINER_IS_BIG_ENDIAN
#define CONTAINER_HELPER_LOG_INDENT(a) (2*(a)->priv->module->level)
#define PS_TRACKS_MAX 2
#define PS_EXTRADATA_MAX 256
#define PS_SYNC_FAIL_MAX
#define PS_PACK_SCAN_MAX 128
#define PS_PACK_SEARCH_MAX 64
Typedefs
typedef struct VC_CONTAINER_TRACK_MODULE_T VC_CONTAINER_TRACK_MODULE_T
typedef struct VC_CONTAINER_MODULE_T VC_CONTAINER_MODULE_T
Functions
VC_CONTAINER_STATUS_T ps_reader_open (VC_CONTAINER_T *)
STATIC_INLINE VC_CONTAINER_STATUS_T ps_find_start_code (VC_CONTAINER_T *ctx, uint8_t *buffer)
STATIC_INLINE VC_CONTAINER_STATUS_T ps_find_pes_packet (VC_CONTAINER_T *ctx)
Macro Definition Documentation
CONTAINER_HELPER_LOG_INDENT
#define CONTAINER_HELPER_LOG_INDENT (a) (2*(a)->priv->module->level)
Definition at line 39 of file ps_reader.c.
CONTAINER_IS_BIG_ENDIAN
#define CONTAINER_IS_BIG_ENDIAN
Definition at line 30 of file ps_reader.c.
PS_EXTRADATA_MAX
#define PS_EXTRADATA_MAX 256
Definition at line 45 of file ps_reader.c.
PS_PACK_SCAN_MAX
#define PS_PACK_SCAN_MAX 128
Maximum number of pack/packet start codes scanned when searching for tracks at open time or when resyncing.
Definition at line 53 of file ps_reader.c.
Referenced by ps_find_pes_packet(), and ps_reader_open().
PS_PACK_SEARCH_MAX
#define PS_PACK_SEARCH_MAX 64
PS_SYNC_FAIL_MAX
#define PS_SYNC_FAIL_MAX
Value:
65536
Definition at line 47 of file ps_reader.c.
Referenced by ps_find_start_code().
PS_TRACKS_MAX
#define PS_TRACKS_MAX 2
Definition at line 44 of file ps_reader.c.
Typedef Documentation
VC_CONTAINER_MODULE_T
typedef struct VC_CONTAINER_MODULE_T VC_CONTAINER_MODULE_T
VC_CONTAINER_TRACK_MODULE_T
typedef struct VC_CONTAINER_TRACK_MODULE_T VC_CONTAINER_TRACK_MODULE_T
Function Documentation
ps_find_pes_packet()
STATIC_INLINE VC_CONTAINER_STATUS_T ps_find_pes_packet (VC_CONTAINER_T * ctx)
Definition at line 956 of file ps_reader.c.
References VC_CONTAINER_PRIVATE_T::module, VC_CONTAINER_MODULE_T::packet_data_size, VC_CONTAINER_T::priv, ps_find_start_code(), PS_PACK_SCAN_MAX, status, and VC_CONTAINER_SUCCESS.
 {
    VC_CONTAINER_STATUS_T status;
    VC_CONTAINER_MODULE_T *module = ctx->priv->module;
    uint8_t buffer[4];
    unsigned int i;
    module->packet_data_size = 0;
    for (i = 0; i != PS_PACK_SCAN_MAX; ++i)
    {
       if((status = ps_find_start_code(ctx, buffer)) != VC_CONTAINER_SUCCESS)
          break;
       if (buffer[3] == 0xBA && ((status = ps_read_pack_header(ctx)) != VC_CONTAINER_SUCCESS))
          continue; /* pack start code but parsing failed, goto resync */
       if ((status = ps_read_pes_packet(ctx)) == VC_CONTAINER_SUCCESS)
          break;
    }
    return status;
 }
ps_find_start_code()
STATIC_INLINE VC_CONTAINER_STATUS_T ps_find_start_code (VC_CONTAINER_T * ctx, uint8_t * buffer)
Definition at line 171 of file ps_reader.c.
References PEEK_BYTES, PS_SYNC_FAIL_MAX, SKIP_BYTES, VC_CONTAINER_ERROR_EOS, VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED, and VC_CONTAINER_SUCCESS.
Referenced by ps_find_pes_packet(), and ps_reader_open().
 {
    unsigned int i;
    /* Scan for a pack or PES packet start code prefix */
    for (i = 0; i < PS_SYNC_FAIL_MAX; ++i)
    {
       if(PEEK_BYTES(ctx, buffer, 4) < 4)
          return VC_CONTAINER_ERROR_EOS;
       if(buffer[0] == 0x0 && buffer[1] == 0x0 && buffer[2] == 0x1 && buffer[3] >= 0xB9)
          break;
       if (SKIP_BYTES(ctx, 1) != 1)
          return VC_CONTAINER_ERROR_EOS;
    }
    if(i == PS_SYNC_FAIL_MAX) /* We didn't find a valid pack or PES packet */
       return VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED;
    if (buffer[3] == 0xB9) /* MPEG_program_end_code */
       return VC_CONTAINER_ERROR_EOS;
    return VC_CONTAINER_SUCCESS;
 }
ps_reader_open()
VC_CONTAINER_STATUS_T ps_reader_open (VC_CONTAINER_T * ctx)
Definition at line 1118 of file ps_reader.c.
References VC_CONTAINER_MODULE_T::data_offset, error(), extension, LOG_DEBUG, LOG_FORMAT, VC_CONTAINER_PRIVATE_T::module, VC_CONTAINER_T::priv, ps_find_start_code(), PS_PACK_SCAN_MAX, VC_CONTAINER_MODULE_T::scr, VC_CONTAINER_MODULE_T::scr_offset, VC_CONTAINER_MODULE_T::searching_tracks, status, STREAM_POSITION, VC_CONTAINER_MODULE_T::tracks, VC_CONTAINER_T::tracks, VC_CONTAINER_PRIVATE_T::uri, VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED, VC_CONTAINER_ERROR_OUT_OF_MEMORY, VC_CONTAINER_SUCCESS, VC_CONTAINER_TIME_UNKNOWN, vc_uri_find_query(), and vc_uri_path_extension().
 {
    const char *extension = vc_uri_path_extension(ctx->priv->uri);
    VC_CONTAINER_MODULE_T *module = 0;
    VC_CONTAINER_STATUS_T status = VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED;
    uint8_t buffer[4];
    unsigned int i;
    /* Check if the user has specified a container */
    vc_uri_find_query(ctx->priv->uri, 0, "container", &extension);
    /* Since MPEG is difficult to auto-detect, we use the extension as
       part of the autodetection */
    if(!extension)
       return VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED;
    if(strcasecmp(extension, "ps") && strcasecmp(extension, "vob") &&
       strcasecmp(extension, "mpg") && strcasecmp(extension, "mp2") &&
       strcasecmp(extension, "mp3") && strcasecmp(extension, "mpeg"))
       return VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED;
    if((status = ps_find_start_code(ctx, buffer)) != VC_CONTAINER_SUCCESS)
       return VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED;  /* We didn't find a valid pack or PES packet  */
    LOG_DEBUG(ctx, "using ps reader");
    /* We are probably dealing with a PS file */
    LOG_FORMAT(ctx, "MPEG PS reader, found start code: 0x%02x%02x%02x%02x",
       buffer[0], buffer[1], buffer[2], buffer[3]);
    /* Need to allocate context before searching for streams */
    module = malloc(sizeof(*module));
    if(!module) { status = VC_CONTAINER_ERROR_OUT_OF_MEMORY; goto error; }
    memset(module, 0, sizeof(*module));
    ctx->priv->module = module;
    ctx->tracks = module->tracks;
    /* Store offset so we can get back to what we consider the first pack or
       packet */
    module->data_offset = STREAM_POSITION(ctx);
    /* Search for tracks, reset time reference and calculation state first */
    ctx->priv->module->scr_offset = ctx->priv->module->scr = VC_CONTAINER_TIME_UNKNOWN;
    ctx->priv->module->searching_tracks = true;
    for (i = 0; i != PS_PACK_SCAN_MAX; ++i)
    {
       if (buffer[3] == 0xBA && (ps_read_pack_header(ctx) != VC_CONTAINER_SUCCESS))
          goto resync;
       if (ps_read_pes_packet(ctx) == VC_CONTAINER_SUCCESS)
          continue;
 resync:
       LOG_DEBUG(ctx, "Lost sync, scanning for start code");
       if((status = ps_find_start_code(ctx, buffer)) != VC_CONTAINER_SUCCESS)
          return VC_CONTAINER_ERROR_CORRUPTED;
       LOG_DEBUG(ctx, "MPEG PS reader, found start code: 0x%"PRIx64" (%"PRId64"): 0x%02x%02x%02x%02x",
          STREAM_POSITION(ctx), STREAM_POSITION(ctx), buffer[0], buffer[1], buffer[2], buffer[3]);
    }
    /* Seek back to the start of data */
    SEEK(ctx, module->data_offset);
    /* Bail out if we didn't find any tracks */
    if(!ctx->tracks_num)
    {
       status = VC_CONTAINER_ERROR_NO_TRACK_AVAILABLE;
       goto error;
    }
    /* Set data size (necessary for seeking) */
    module->data_size = MAX(ctx->priv->io->size - module->data_offset, INT64_C(0));
    /* Estimate data rate (necessary for seeking) */
    if(STREAM_SEEKABLE(ctx))
    {
       /* Estimate data rate by jumping in the stream */
       #define PS_PACK_SEARCH_MAX 64
       uint64_t position = module->data_offset;
       for (i = 0; i != PS_PACK_SEARCH_MAX; ++i)
       {
          position += (module->data_size / (PS_PACK_SEARCH_MAX + 1));
          SEEK(ctx, position);
          for(;;)
          {
             if(ps_find_start_code(ctx, buffer) != VC_CONTAINER_SUCCESS)
                break;
             if (buffer[3] == 0xBA)
             {
                if (ps_read_pack_header(ctx) == VC_CONTAINER_SUCCESS)
                   break;
             }
             else
             {
                /* Skip PES packet */
                unsigned length;
                SKIP_U32(ctx, "PES packet startcode");
                length = READ_U16(ctx, "PES packet length");
                SKIP_BYTES(ctx, length);
             }
          }
       }
       ctx->duration = (INT64_C(1000000) * module->data_size) / (module->data_rate);
       if (module->scr > module->scr_offset)
       {
          int64_t delta = (module->scr - module->scr_offset) / INT64_C(27);
          if (delta > ctx->duration)
             ctx->duration = delta;
       }
       /* Seek back to the start of data */
       SEEK(ctx, module->data_offset);
    }
    else
    {
       /* For most files, program_mux_rate is not reliable at all */
       ctx->duration = (INT64_C(100000) * module->data_size) / (INT64_C(5) * module->mux_rate);
    }
    /* Reset time reference and calculation state, we're now ready to read data */
    module->scr = VC_CONTAINER_TIME_UNKNOWN;
    module->scr_bias = VC_CONTAINER_TIME_UNKNOWN;
    ctx->priv->module->searching_tracks = false;
    if(STREAM_SEEKABLE(ctx)) ctx->capabilities |= VC_CONTAINER_CAPS_CAN_SEEK;
    ctx->priv->pf_close = ps_reader_close;
    ctx->priv->pf_read = ps_reader_read;
    ctx->priv->pf_seek = ps_reader_seek;
    return STREAM_STATUS(ctx);
  error:
    LOG_DEBUG(ctx, "ps: error opening stream (%i)", status);
    if(module) ps_reader_close(ctx);
    return status;
 }