VideoCore Library: host_applications/linux/apps/raspicam/RaspiCLI.c File Reference
RaspiCLI.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <memory.h>
#include "interface/vcos/vcos.h"
#include "RaspiCLI.h"
Functions
int raspicli_get_command_id (const COMMAND_LIST *commands, const int num_commands, const char *arg, int *num_parameters)
void raspicli_display_help (const COMMAND_LIST *commands, const int num_commands)
int raspicli_map_xref (const char *str, const XREF_T *map, int num_refs)
const char * raspicli_unmap_xref (const int en, XREF_T *map, int num_refs)
Detailed Description
Code for handling command line parameters
Date
4th March 2013 : James Hughes
Description
Some functions/structures for command line parameter parsing
Definition in file RaspiCLI.c.
Function Documentation
raspicli_display_help()
void raspicli_display_help (const COMMAND_LIST * commands, const int num_commands)
Display the list of commands in help format
Parameters
commands Array of command to check
num_command Number of commands in the arry
Definition at line 98 of file RaspiCLI.c.
References vcos_assert.
Referenced by raspicamcontrol_display_help(), raspicommonsettings_display_help(), raspipreview_display_help(), and raspitex_display_help().
 {
    int i;
    vcos_assert(commands);
    if (!commands)
       return;
    for (i = 0; i < num_commands; i++)
    {
       fprintf(stdout, "-%s, -%s\t: %s\n", commands[i].abbrev,
               commands[i].command, commands[i].help);
    }
 }
raspicli_get_command_id()
int raspicli_get_command_id (const COMMAND_LIST * commands, const int num_commands, const char * arg, int * num_parameters)
Convert a string from command line to a comand_id from the list
Parameters
commands Array of command to check
num_command Number of commands in the array
arg String to search for in the list
num_parameters Returns the number of parameters used by the command
Returns
command ID if found, -1 if not found
Definition at line 62 of file RaspiCLI.c.
References COMMAND_LIST::id, COMMAND_LIST::num_parameters, and vcos_assert.
Referenced by raspicamcontrol_parse_cmdline(), and raspipreview_parse_cmdline().
 {
    int command_id = -1;
    int j;
    vcos_assert(commands);
    vcos_assert(num_parameters);
    vcos_assert(arg);
    if (!commands || !num_parameters || !arg)
       return -1;
    for (j = 0; j < num_commands; j++)
    {
       if (!strcmp(arg, commands[j].command) ||
             !strcmp(arg, commands[j].abbrev))
       {
          // match
          command_id = commands[j].id;
          *num_parameters = commands[j].num_parameters;
          break;
       }
    }
    return command_id;
 }
raspicli_map_xref()
int raspicli_map_xref (const char * str, const XREF_T * map, int num_refs)
Function to take a string, a mapping, and return the int equivalent
Parameters
str Incoming string to match
map Mapping data
num_refs The number of items in the mapping data
Returns
The integer match for the string, or -1 if no match
Definition at line 122 of file RaspiCLI.c.
References xref_t::mmal_mode.
Referenced by imagefx_mode_from_string().
 {
    int i;
    for (i=0; i<num_refs; i++)
    {
       if (!strcasecmp(str, map[i].mode))
       {
          return map[i].mmal_mode;
       }
    }
    return -1;
 }
raspicli_unmap_xref()
const char* raspicli_unmap_xref (const int en, XREF_T * map, int num_refs)
Function to take a mmal enum (as int) and return the string equivalent
Parameters
en Incoming int to match
map Mapping data
num_refs The number of items in the mapping data
Returns
const pointer to string, or NULL if no match
Definition at line 143 of file RaspiCLI.c.
References xref_t::mode, and NULL.
Referenced by raspicamcontrol_dump_parameters().
 {
    int i;
    for (i=0; i<num_refs; i++)
    {
       if (en == map[i].mmal_mode)
       {
          return map[i].mode;
       }
    }
    return NULL;
 }