VideoCore Library: Graph Utility
Graph Utility
Utility functions
Classes
struct MMAL_GRAPH_T
Typedefs
typedef struct MMAL_GRAPH_T MMAL_GRAPH_T
typedef void(* MMAL_GRAPH_EVENT_CB) (MMAL_GRAPH_T *graph, MMAL_PORT_T *port, MMAL_BUFFER_HEADER_T *buffer, void *cb_data)
Enumerations
enum MMAL_GRAPH_TOPOLOGY_T { MMAL_GRAPH_TOPOLOGY_ALL = 0, MMAL_GRAPH_TOPOLOGY_STRAIGHT, MMAL_GRAPH_TOPOLOGY_CUSTOM, MMAL_GRAPH_TOPOLOGY_MAX }
Functions
MMAL_STATUS_T mmal_graph_create (MMAL_GRAPH_T **graph, unsigned int userdata_size)
MMAL_STATUS_T mmal_graph_add_component (MMAL_GRAPH_T *graph, MMAL_COMPONENT_T *component)
MMAL_STATUS_T mmal_graph_component_topology (MMAL_GRAPH_T *graph, MMAL_COMPONENT_T *component, MMAL_GRAPH_TOPOLOGY_T topology, int8_t *input, unsigned int input_num, int8_t *output, unsigned int output_num)
MMAL_STATUS_T mmal_graph_add_port (MMAL_GRAPH_T *graph, MMAL_PORT_T *port)
MMAL_STATUS_T mmal_graph_add_connection (MMAL_GRAPH_T *graph, MMAL_CONNECTION_T *connection)
MMAL_STATUS_T mmal_graph_new_component (MMAL_GRAPH_T *graph, const char *name, MMAL_COMPONENT_T **component)
MMAL_STATUS_T mmal_graph_new_connection (MMAL_GRAPH_T *graph, MMAL_PORT_T *out, MMAL_PORT_T *in, uint32_t flags, MMAL_CONNECTION_T **connection)
MMAL_STATUS_T mmal_graph_enable (MMAL_GRAPH_T *graph, MMAL_GRAPH_EVENT_CB cb, void *cb_data)
MMAL_STATUS_T mmal_graph_disable (MMAL_GRAPH_T *graph)
MMAL_PORT_T * mmal_graph_find_port (MMAL_GRAPH_T *graph, const char *name, MMAL_PORT_TYPE_T type, unsigned index)
MMAL_STATUS_T mmal_graph_build (MMAL_GRAPH_T *ctx, const char *name, MMAL_COMPONENT_T **component)
MMAL_STATUS_T mmal_graph_component_constructor (const char *name, MMAL_COMPONENT_T *component)
MMAL_STATUS_T mmal_graph_destroy (MMAL_GRAPH_T *ctx)
Detailed Description
The graph utility functions allows one to easily create graphs of MMAL components.
Typedef Documentation
MMAL_GRAPH_EVENT_CB
typedef void(* MMAL_GRAPH_EVENT_CB) (MMAL_GRAPH_T *graph, MMAL_PORT_T *port, MMAL_BUFFER_HEADER_T *buffer, void *cb_data)
Definition of the callback used by a graph to send events to the client.
Parameters
graph the graph sending the event
port the port which generated the event
buffer the buffer header containing the event data
cb_data data passed back to the client when the callback is invoked
Definition at line 181 of file mmal_graph.h.
MMAL_GRAPH_T
typedef struct MMAL_GRAPH_T MMAL_GRAPH_T
Structure describing a graph
Enumeration Type Documentation
MMAL_GRAPH_TOPOLOGY_T
enum MMAL_GRAPH_TOPOLOGY_T
List of topology types
Enumerator
MMAL_GRAPH_TOPOLOGY_ALL
All input ports and output ports are linked
MMAL_GRAPH_TOPOLOGY_STRAIGHT
Input ports and output ports of the same index are linked
MMAL_GRAPH_TOPOLOGY_CUSTOM
Custom defined topology
MMAL_GRAPH_TOPOLOGY_MAX
Definition at line 45 of file mmal_graph.h.
 {
    MMAL_GRAPH_TOPOLOGY_ALL = 0,
    MMAL_GRAPH_TOPOLOGY_STRAIGHT,
    MMAL_GRAPH_TOPOLOGY_CUSTOM,
    MMAL_GRAPH_TOPOLOGY_MAX
 } MMAL_GRAPH_TOPOLOGY_T;
Function Documentation
mmal_graph_add_component()
MMAL_STATUS_T mmal_graph_add_component (MMAL_GRAPH_T * graph, MMAL_COMPONENT_T * component)
Add a component to a graph. Allows the client to add a component to the graph.
Parameters
graph instance of the graph
component component to add to a graph
Returns
MMAL_SUCCESS on success
Definition at line 198 of file mmal_graph.c.
References MMAL_COMPONENT_MODULE_T::component, GRAPH_CONNECTIONS_MAX, LOG_ERROR, LOG_TRACE, mmal_component_acquire(), MMAL_EINVAL, MMAL_ENOSPC, MMAL_SUCCESS, and MMAL_COMPONENT_T::name.
 {
    MMAL_GRAPH_PRIVATE_T *private = (MMAL_GRAPH_PRIVATE_T *)graph;
    LOG_TRACE("graph: %p, component: %s(%p)", graph, component ? component->name: 0, component);
    if (!component)
       return MMAL_EINVAL;
    if (private->component_num >= GRAPH_CONNECTIONS_MAX)
    {
       LOG_ERROR("no space for component %s", component->name);
       return MMAL_ENOSPC;
    }
    mmal_component_acquire(component);
    private->component[private->component_num++] = component;
    return MMAL_SUCCESS;
 }
mmal_graph_add_connection()
MMAL_STATUS_T mmal_graph_add_connection (MMAL_GRAPH_T * graph, MMAL_CONNECTION_T * connection)
Add a connection to a graph. Allows the client to add an internal connection to a graph.
Parameters
graph instance of the graph
connection connection to add to the graph
Returns
MMAL_SUCCESS on success
Definition at line 250 of file mmal_graph.c.
References GRAPH_CONNECTIONS_MAX, LOG_ERROR, LOG_TRACE, mmal_connection_acquire(), MMAL_EINVAL, MMAL_ENOSPC, MMAL_SUCCESS, and MMAL_CONNECTION_T::name.
 {
    MMAL_GRAPH_PRIVATE_T *private = (MMAL_GRAPH_PRIVATE_T *)graph;
    LOG_TRACE("graph: %p, connection: %s(%p)", graph, cx ? cx->name: 0, cx);
    if (!cx)
       return MMAL_EINVAL;
    if (private->connection_num >= GRAPH_CONNECTIONS_MAX)
    {
       LOG_ERROR("no space for connection %s", cx->name);
       return MMAL_ENOSPC;
    }
    mmal_connection_acquire(cx);
    private->connection[private->connection_num++] = cx;
    return MMAL_SUCCESS;
 }
mmal_graph_add_port()
MMAL_STATUS_T mmal_graph_add_port (MMAL_GRAPH_T * graph, MMAL_PORT_T * port)
Add a port to a graph. Allows the client to add an input or output port to a graph. The given port will effectively become an end point for the graph.
Parameters
graph instance of the graph
port port to add to the graph
Returns
MMAL_SUCCESS on success
Definition at line 271 of file mmal_graph.c.
References GRAPH_CONNECTIONS_MAX, LOG_ERROR, LOG_TRACE, MMAL_EINVAL, MMAL_ENOSPC, MMAL_PORT_TYPE_CLOCK, MMAL_PORT_TYPE_INPUT, MMAL_PORT_TYPE_OUTPUT, MMAL_SUCCESS, MMAL_PORT_T::name, and MMAL_PORT_T::type.
 {
    MMAL_GRAPH_PRIVATE_T *private = (MMAL_GRAPH_PRIVATE_T *)graph;
    MMAL_PORT_T **list;
    unsigned int *list_num;
    LOG_TRACE("graph: %p, port: %s(%p)", graph, port ? port->name: 0, port);
    if (!port)
       return MMAL_EINVAL;
    switch (port->type)
    {
    case MMAL_PORT_TYPE_INPUT:
       list = private->input;
       list_num = &private->input_num;
       break;
    case MMAL_PORT_TYPE_OUTPUT:
       list = private->output;
       list_num = &private->output_num;
       break;
    case MMAL_PORT_TYPE_CLOCK:
       list = private->clock;
       list_num = &private->clock_num;
       break;
    default:
       return MMAL_EINVAL;
    }
    if (*list_num >= GRAPH_CONNECTIONS_MAX)
    {
       LOG_ERROR("no space for port %s", port->name);
       return MMAL_ENOSPC;
    }
    list[(*list_num)++] = port;
    return MMAL_SUCCESS;
 }
mmal_graph_build()
MMAL_STATUS_T mmal_graph_build (MMAL_GRAPH_T * ctx, const char * name, MMAL_COMPONENT_T ** component)
Create an instance of a component from a graph. The newly created component will expose input and output ports to the client. Not that all the exposed ports will be in a disabled state by default.
Parameters
graph graph to create the component from
name name of the component to create
component returned component
Returns
MMAL_SUCCESS on success
Definition at line 455 of file mmal_graph.c.
References LOG_TRACE, and mmal_component_create_with_constructor().
 {
    LOG_TRACE("graph: %p, name: %s, component: %p", graph, name, component);
    return mmal_component_create_with_constructor(name, mmal_component_create_from_graph,
       (MMAL_GRAPH_PRIVATE_T *)graph, component);
 }
mmal_graph_component_constructor()
MMAL_STATUS_T mmal_graph_component_constructor (const char * name, MMAL_COMPONENT_T * component)
Component constructor for a graph. FIXME: private function
Parameters
name name of the component to create
component component
Returns
MMAL_SUCCESS on success
Definition at line 464 of file mmal_graph.c.
References LOG_TRACE.
 {
    LOG_TRACE("name: %s, component: %p", name, component);
    return mmal_component_create_from_graph(name, component);
 }
mmal_graph_component_topology()
MMAL_STATUS_T mmal_graph_component_topology (MMAL_GRAPH_T * graph, MMAL_COMPONENT_T * component, MMAL_GRAPH_TOPOLOGY_T topology, int8_t * input, unsigned int input_num, int8_t * output, unsigned int output_num)
Describe the topology of the ports of a component. Allows the client to describe the topology of a component. This information is used by the graph to choose which action to perform when enabling / disabling / committing / flushing a port exposed by the graph. Note that by default the topology of a component is set to MMAL_GRAPH_TOPOLOGY_ALL.
Parameters
graph instance of the graph
component component to describe
topology type of topology used by this component
input output index (or -1 if sink) linked to each input port
input_num number of indexes in the input list
output input index (or -1 if source) linked to each output port
output_num number of indexes in the output list
Returns
MMAL_SUCCESS on success
Definition at line 220 of file mmal_graph.c.
References LOG_TRACE, MMAL_EINVAL, MMAL_ENOSYS, MMAL_GRAPH_TOPOLOGY_STRAIGHT, MMAL_PARAM_UNUSED, MMAL_SUCCESS, MMAL_COMPONENT_T::name, and MMAL_COMPONENT_MODULE_T::topology.
 {
    MMAL_GRAPH_PRIVATE_T *private = (MMAL_GRAPH_PRIVATE_T *)graph;
    MMAL_PARAM_UNUSED(input); MMAL_PARAM_UNUSED(input_num);
    MMAL_PARAM_UNUSED(output); MMAL_PARAM_UNUSED(output_num);
    unsigned int i;
    LOG_TRACE("graph: %p, component: %s(%p)", graph, component ? component->name: 0, component);
    if (!component)
       return MMAL_EINVAL;
    for (i = 0; i < private->component_num; i++)
       if (component == private->component[i])
          break;
    if (i == private->component_num)
       return MMAL_EINVAL; /* Component not found */
    if (topology > MMAL_GRAPH_TOPOLOGY_STRAIGHT)
       return MMAL_ENOSYS; /* Currently not supported */
    private->topology[i] = topology;
    return MMAL_SUCCESS;
 }
mmal_graph_create()
MMAL_STATUS_T mmal_graph_create (MMAL_GRAPH_T ** graph, unsigned int userdata_size)
Create an instance of a graph. The newly created graph will need to be populated by the client.
Parameters
graph returned graph
userdata_size size to be allocated for the userdata field
Returns
MMAL_SUCCESS on success
Definition at line 143 of file mmal_graph.c.
References LOG_ERROR, LOG_TRACE, MMAL_EINVAL, MMAL_ENOMEM, MMAL_ENOSPC, MMAL_SUCCESS, MMAL_GRAPH_T::userdata, vcos_calloc(), vcos_free(), vcos_semaphore_create(), and VCOS_SUCCESS.
Referenced by main().
 {
    MMAL_GRAPH_PRIVATE_T *private;
    LOG_TRACE("graph %p, userdata_size %u", graph, userdata_size);
    /* Sanity checking */
    if (!graph)
       return MMAL_EINVAL;
    private = vcos_calloc(1, sizeof(MMAL_GRAPH_PRIVATE_T) + userdata_size, "mmal connection graph");
    if (!private)
       return MMAL_ENOMEM;
    *graph = &private->graph;
    if (userdata_size)
       (*graph)->userdata = (struct MMAL_GRAPH_USERDATA_T *)&private[1];
    if (vcos_semaphore_create(&private->sema, "mmal graph sema", 0) != VCOS_SUCCESS)
    {
       LOG_ERROR("failed to create semaphore %p", graph);
       vcos_free(private);
       return MMAL_ENOSPC;
    }
    return MMAL_SUCCESS;
 }
mmal_graph_destroy()
MMAL_STATUS_T mmal_graph_destroy (MMAL_GRAPH_T * ctx)
Destroy a previously created graph
Parameters
graph graph to destroy
Returns
MMAL_SUCCESS on success
Definition at line 171 of file mmal_graph.c.
References LOG_TRACE, mmal_component_release(), mmal_connection_release(), MMAL_EINVAL, MMAL_SUCCESS, MMAL_GRAPH_T::pf_destroy, vcos_free(), and vcos_semaphore_delete().
Referenced by main().
 {
    unsigned i;
    MMAL_GRAPH_PRIVATE_T *private = (MMAL_GRAPH_PRIVATE_T *)graph;
    if (!graph)
       return MMAL_EINVAL;
    LOG_TRACE("%p", graph);
    /* Notify client of destruction */
    if (graph->pf_destroy)
       graph->pf_destroy(graph);
    for (i = 0; i < private->connection_num; i++)
       mmal_connection_release(private->connection[i]);
    for (i = 0; i < private->component_num; i++)
       mmal_component_release(private->component[i]);
    vcos_semaphore_delete(&private->sema);
    vcos_free(graph);
    return MMAL_SUCCESS;
 }
mmal_graph_disable()
MMAL_STATUS_T mmal_graph_disable (MMAL_GRAPH_T * graph)
Definition at line 433 of file mmal_graph.c.
References LOG_TRACE, MMAL_SUCCESS, and MMAL_COMPONENT_MODULE_T::status.
Referenced by main().
 {
    MMAL_GRAPH_PRIVATE_T *private = (MMAL_GRAPH_PRIVATE_T *)graph;
    MMAL_STATUS_T status = MMAL_SUCCESS;
    unsigned int i;
    LOG_TRACE("graph: %p", graph);
    graph_stop_worker_thread(private);
    /* Disable all our connections */
    for (i = 0; i < private->connection_num; i++)
    {
       status = mmal_connection_disable(private->connection[i]);
       if (status != MMAL_SUCCESS)
          break;
    }
    return status;
 }
mmal_graph_enable()
MMAL_STATUS_T mmal_graph_enable (MMAL_GRAPH_T * graph, MMAL_GRAPH_EVENT_CB cb, void * cb_data)
Enable the graph and start processing.
Parameters
graph the graph to enable
cb the callback to invoke when an event occurs on any of the internal control ports
cb_data data passed back to the client when the callback is invoked
Returns
MMAL_SUCCESS on success
Definition at line 383 of file mmal_graph.c.
References LOG_TRACE, MMAL_SUCCESS, NULL, MMAL_COMPONENT_MODULE_T::status, and vcos_thread_create().
Referenced by main().
 {
    MMAL_GRAPH_PRIVATE_T *private = (MMAL_GRAPH_PRIVATE_T *)graph;
    MMAL_STATUS_T status = MMAL_SUCCESS;
    unsigned int i;
    LOG_TRACE("graph: %p", graph);
    if (vcos_thread_create(&private->thread, "mmal graph thread", NULL,
                           graph_worker_thread, private) != VCOS_SUCCESS)
    {
       LOG_ERROR("failed to create worker thread %p", graph);
       return MMAL_ENOSPC;
    }
    private->event_cb = cb;
    private->event_cb_data = cb_data;
    /* Enable all control ports */
    for (i = 0; i < private->component_num; i++)
    {
       private->component[i]->control->userdata = (void *)private;
       status = mmal_port_enable(private->component[i]->control, graph_control_cb);
       if (status != MMAL_SUCCESS)
          LOG_ERROR("could not enable port %s", private->component[i]->control->name);
    }
    /* Enable all our connections */
    for (i = 0; i < private->connection_num; i++)
    {
       MMAL_CONNECTION_T *cx = private->connection[i];
       cx->callback = graph_connection_cb;
       cx->user_data = private;
       status = mmal_connection_enable(cx);
       if (status != MMAL_SUCCESS)
          goto error;
    }
    /* Trigger the worker thread to populate the output ports with empty buffers */
    vcos_semaphore_post(&private->sema);
    return status;
  error:
    graph_stop_worker_thread(private);
    return status;
 }
mmal_graph_find_port()
MMAL_PORT_T* mmal_graph_find_port (MMAL_GRAPH_T * graph, const char * name, MMAL_PORT_TYPE_T type, unsigned index)
Find a port in the graph.
Parameters
graph graph instance
name name of the component of interest
type type of port (in/out)
index which port index within the component
Returns
port, or NULL if not found
Definition at line 1517 of file mmal_graph.c.
References MMAL_COMPONENT_T::clock, MMAL_COMPONENT_T::clock_num, MMAL_COMPONENT_T::control, index, MMAL_COMPONENT_T::input, MMAL_COMPONENT_T::input_num, LOG_INFO, MMAL_PORT_TYPE_CLOCK, MMAL_PORT_TYPE_CONTROL, MMAL_PORT_TYPE_INPUT, MMAL_PORT_TYPE_OUTPUT, MMAL_COMPONENT_T::name, NULL, MMAL_COMPONENT_T::output, MMAL_COMPONENT_T::output_num, MMAL_COMPONENT_MODULE_T::ports, vcos_assert, and vcos_strcasecmp().
 {
    unsigned i;
    MMAL_GRAPH_PRIVATE_T *private = (MMAL_GRAPH_PRIVATE_T *)graph;
    for (i=0; i<private->component_num; i++)
    {
       MMAL_COMPONENT_T *comp = private->component[i];
       if (vcos_strcasecmp(name, comp->name) == 0)
       {
          unsigned num;
          MMAL_PORT_T **ports;
          if (type == MMAL_PORT_TYPE_INPUT) {
             num = comp->input_num;
             ports = comp->input;
          }
          else if (type == MMAL_PORT_TYPE_OUTPUT) {
             num = comp->output_num;
             ports = comp->output;
          }
          else if (type == MMAL_PORT_TYPE_CLOCK) {
             num = comp->clock_num;
             ports = comp->clock;
          }
          else if (type == MMAL_PORT_TYPE_CONTROL) {
             num = 1;
             ports = &comp->control;
          }
          else {
             vcos_assert(0);
             return NULL;
          }
          if (index < num)
          {
             /* coverity[ptr_arith] num is 1 at this point */
             return ports[index];
          }
       }
    }
    LOG_INFO("port %s:%d not found", name, index);
    return NULL;
 }
mmal_graph_new_component()
MMAL_STATUS_T mmal_graph_new_component (MMAL_GRAPH_T * graph, const char * name, MMAL_COMPONENT_T ** component)
Create a new component and add it to a graph. Allows the client to create and add a component to the graph.
Parameters
graph instance of the graph
name name of the component to create
component if not NULL, will contain a pointer to the created component
Returns
MMAL_SUCCESS on success
Definition at line 311 of file mmal_graph.c.
References GRAPH_CONNECTIONS_MAX, LOG_ERROR, LOG_TRACE, mmal_component_acquire(), mmal_component_create(), MMAL_ENOSPC, MMAL_SUCCESS, and MMAL_COMPONENT_MODULE_T::status.
Referenced by main().
 {
    MMAL_GRAPH_PRIVATE_T *private = (MMAL_GRAPH_PRIVATE_T *)graph;
    MMAL_COMPONENT_T *comp;
    MMAL_STATUS_T status;
    LOG_TRACE("graph: %p, name: %s, component: %p", graph, name, component);
    if (private->component_num >= GRAPH_CONNECTIONS_MAX)
    {
       LOG_ERROR("no space for component %s", name);
       return MMAL_ENOSPC;
    }
    status = mmal_component_create(name, &comp);
    if (status != MMAL_SUCCESS)
    {
       LOG_ERROR("could not create component %s (%i)", name, status);
       return status;
    }
    private->component[private->component_num++] = comp;
    if (component)
    {
       mmal_component_acquire(comp);
       *component = comp;
    }
    return MMAL_SUCCESS;
 }
mmal_graph_new_connection()
MMAL_STATUS_T mmal_graph_new_connection (MMAL_GRAPH_T * graph, MMAL_PORT_T * out, MMAL_PORT_T * in, uint32_t flags, MMAL_CONNECTION_T ** connection)
Create and add a connection to a graph. Allows the client to create and add an internal connection to a graph.
Parameters
graph instance of the graph
out the output port to use for the connection
in the input port to use for the connection
flags the flags specifying which type of connection should be created
connection if not NULL, will contain a pointer to the created connection
Returns
MMAL_SUCCESS on success
Definition at line 344 of file mmal_graph.c.
References GRAPH_CONNECTIONS_MAX, LOG_ERROR, LOG_TRACE, mmal_connection_acquire(), mmal_connection_create(), MMAL_EINVAL, MMAL_ENOSPC, MMAL_PORT_TYPE_CLOCK, MMAL_PORT_TYPE_INPUT, MMAL_PORT_TYPE_OUTPUT, MMAL_SUCCESS, MMAL_PORT_T::name, MMAL_COMPONENT_MODULE_T::status, and MMAL_PORT_T::type.
Referenced by main().
 {
    MMAL_GRAPH_PRIVATE_T *private = (MMAL_GRAPH_PRIVATE_T *)graph;
    MMAL_CONNECTION_T *cx;
    MMAL_STATUS_T status;
    if (!out || !in)
       return MMAL_EINVAL;
    if (out->type == MMAL_PORT_TYPE_CLOCK && in->type != MMAL_PORT_TYPE_CLOCK)
       return MMAL_EINVAL;
    if (out->type != MMAL_PORT_TYPE_CLOCK &&
        (out->type != MMAL_PORT_TYPE_OUTPUT || in->type != MMAL_PORT_TYPE_INPUT))
       return MMAL_EINVAL;
    LOG_TRACE("graph: %p, out: %s(%p), in: %s(%p), flags %x, connection: %p",
              graph, out->name, out, in->name, in, (int)flags, connection);
    if (private->connection_num >= GRAPH_CONNECTIONS_MAX)
    {
       LOG_ERROR("no space for connection %s/%s", out->name, in->name);
       return MMAL_ENOSPC;
    }
    status = mmal_connection_create(&cx, out, in, flags);
    if (status != MMAL_SUCCESS)
       return status;
    private->connection[private->connection_num++] = cx;
    if (connection)
    {
       mmal_connection_acquire(cx);
       *connection = cx;
    }
    return MMAL_SUCCESS;
 }