VideoCore Library: utility
utility
Utility functions
Classes
struct MMAL_WRAPPER_T
Typedefs
typedef struct MMAL_WRAPPER_T MMAL_WRAPPER_T
typedef void(* MMAL_WRAPPER_CALLBACK_T) (MMAL_WRAPPER_T *wrapper)
Functions
MMAL_STATUS_T mmal_wrapper_create (MMAL_WRAPPER_T **wrapper, const char *name)
MMAL_STATUS_T mmal_wrapper_port_enable (MMAL_PORT_T *port, uint32_t flags)
MMAL_STATUS_T mmal_wrapper_port_disable (MMAL_PORT_T *port)
MMAL_STATUS_T mmal_wrapper_buffer_get_empty (MMAL_PORT_T *port, MMAL_BUFFER_HEADER_T **buffer, uint32_t flags)
MMAL_STATUS_T mmal_wrapper_buffer_get_full (MMAL_PORT_T *port, MMAL_BUFFER_HEADER_T **buffer, uint32_t flags)
MMAL_STATUS_T mmal_wrapper_cancel (MMAL_WRAPPER_T *wrapper)
MMAL_STATUS_T mmal_wrapper_destroy (MMAL_WRAPPER_T *wrapper)
MMAL wrapper flags
#define MMAL_WRAPPER_FLAG_WAIT 1
#define MMAL_WRAPPER_FLAG_PAYLOAD_ALLOCATE 2
#define MMAL_WRAPPER_FLAG_PAYLOAD_USE_SHARED_MEMORY 4
Detailed Description
The component wrapper utility functions can be used in place of common sequences of calls to the MMAL API in order to control a standalone component. It hides some of the complexity in using standalone components behind a fully synchronous interface.
Macro Definition Documentation
MMAL_WRAPPER_FLAG_PAYLOAD_ALLOCATE
#define MMAL_WRAPPER_FLAG_PAYLOAD_ALLOCATE 2
The pool for the port should allocate memory for the payloads
Definition at line 98 of file mmal_component_wrapper.h.
Referenced by mmal_encode_test(), and mmal_wrapper_port_enable().
MMAL_WRAPPER_FLAG_PAYLOAD_USE_SHARED_MEMORY
#define MMAL_WRAPPER_FLAG_PAYLOAD_USE_SHARED_MEMORY 4
The port will use shared memory payloads
Definition at line 100 of file mmal_component_wrapper.h.
Referenced by mmal_wrapper_port_enable().
MMAL_WRAPPER_FLAG_WAIT
#define MMAL_WRAPPER_FLAG_WAIT 1
The operation should be blocking
Definition at line 96 of file mmal_component_wrapper.h.
Referenced by mmal_wrapper_buffer_get_empty(), and mmal_wrapper_buffer_get_full().
Typedef Documentation
MMAL_WRAPPER_CALLBACK_T
typedef void(* MMAL_WRAPPER_CALLBACK_T) (MMAL_WRAPPER_T *wrapper)
Definition of the callback used by a wrapper to signal back to the client that a buffer header is available either in the pool or in the output queue.
Parameters
wrapper Pointer to the wrapper
Definition at line 52 of file mmal_component_wrapper.h.
MMAL_WRAPPER_T
typedef struct MMAL_WRAPPER_T MMAL_WRAPPER_T
Forward type definition for a wrapper
Definition at line 45 of file mmal_component_wrapper.h.
Function Documentation
mmal_wrapper_buffer_get_empty()
MMAL_STATUS_T mmal_wrapper_buffer_get_empty (MMAL_PORT_T * port, MMAL_BUFFER_HEADER_T ** buffer, uint32_t flags)
Wait for an empty buffer to be available on a port.
Parameters
port port to get an empty buffer from
buffer points to the retreived buffer on return
flags specify MMAL_WRAPPER_FLAG_WAIT for a blocking operation
Returns
MMAL_SUCCESS on success.
Wait for an empty buffer to be available on a port
Definition at line 319 of file mmal_component_wrapper.c.
References MMAL_PORT_T::index, LOG_TRACE, MMAL_EAGAIN, MMAL_EINVAL, MMAL_PORT_TYPE_INPUT, MMAL_PORT_TYPE_OUTPUT, mmal_queue_get(), MMAL_SUCCESS, MMAL_WRAPPER_FLAG_WAIT, MMAL_PORT_T::name, NULL, MMAL_POOL_T::queue, MMAL_PORT_T::type, MMAL_PORT_T::userdata, and vcos_semaphore_wait().
Referenced by mmal_encode_test().
 {
    MMAL_WRAPPER_PRIVATE_T *private = (MMAL_WRAPPER_PRIVATE_T *)port->userdata;
    MMAL_WRAPPER_T *wrapper = &private->wrapper;
    MMAL_POOL_T *pool;
    LOG_TRACE("%p, %s", wrapper, port->name);
    if (!buffer || (port->type != MMAL_PORT_TYPE_INPUT && port->type != MMAL_PORT_TYPE_OUTPUT))
       return MMAL_EINVAL;
    pool = port->type == MMAL_PORT_TYPE_INPUT ?
       wrapper->input_pool[port->index] : wrapper->output_pool[port->index];
    while (wrapper->status == MMAL_SUCCESS &&
           (*buffer = mmal_queue_get(pool->queue)) == NULL)
    {
       if (!(flags & MMAL_WRAPPER_FLAG_WAIT))
          break;
       vcos_semaphore_wait(&private->sema);
    }
    return wrapper->status == MMAL_SUCCESS && !*buffer ? MMAL_EAGAIN : wrapper->status;
 }
mmal_wrapper_buffer_get_full()
MMAL_STATUS_T mmal_wrapper_buffer_get_full (MMAL_PORT_T * port, MMAL_BUFFER_HEADER_T ** buffer, uint32_t flags)
Wait for a full buffer to be available on a port.
Parameters
port port to get a full buffer from
buffer points to the retreived buffer on return
flags specify MMAL_WRAPPER_FLAG_WAIT for a blocking operation
Returns
MMAL_SUCCESS on success.
Wait for a full buffer to be available on a port
Definition at line 346 of file mmal_component_wrapper.c.
References MMAL_PORT_T::index, LOG_TRACE, MMAL_EAGAIN, MMAL_EINVAL, MMAL_PORT_TYPE_OUTPUT, mmal_queue_get(), MMAL_SUCCESS, MMAL_WRAPPER_FLAG_WAIT, MMAL_PORT_T::name, NULL, MMAL_PORT_T::type, MMAL_PORT_T::userdata, and vcos_semaphore_wait().
Referenced by mmal_encode_test().
 {
    MMAL_WRAPPER_PRIVATE_T *private = (MMAL_WRAPPER_PRIVATE_T *)port->userdata;
    MMAL_WRAPPER_T *wrapper = &private->wrapper;
    MMAL_QUEUE_T *queue;
    LOG_TRACE("%p, %s", wrapper, port->name);
    if (!buffer || port->type != MMAL_PORT_TYPE_OUTPUT)
       return MMAL_EINVAL;
    queue = wrapper->output_queue[port->index];
    while (wrapper->status == MMAL_SUCCESS &&
           (*buffer = mmal_queue_get(queue)) == NULL)
    {
       if (!(flags & MMAL_WRAPPER_FLAG_WAIT))
          break;
       vcos_semaphore_wait(&private->sema);
    }
    return wrapper->status == MMAL_SUCCESS && !*buffer ? MMAL_EAGAIN : wrapper->status;
 }
mmal_wrapper_cancel()
MMAL_STATUS_T mmal_wrapper_cancel (MMAL_WRAPPER_T * wrapper)
Cancel any ongoing blocking operation on a component wrapper.
Parameters
wrapper The wrapper on which to cancel operations.
Returns
MMAL_SUCCESS on success.
mmal_wrapper_create()
MMAL_STATUS_T mmal_wrapper_create (MMAL_WRAPPER_T ** wrapper, const char * name)
Create a wrapper around a component. The wrapper shall include a pool of buffer headers for each port. The pools will be suitable for the current format of its associated port.
Parameters
wrapper The address of a wrapper pointer that will be set to point to the created wrapper.
name The name of the component to create.
Returns
MMAL_SUCCESS on success.
Definition at line 133 of file mmal_component_wrapper.c.
References MMAL_WRAPPER_T::component, MMAL_WRAPPER_T::control, MMAL_COMPONENT_T::control, error(), MMAL_WRAPPER_T::input, MMAL_COMPONENT_T::input, MMAL_WRAPPER_T::input_num, MMAL_COMPONENT_T::input_num, MMAL_WRAPPER_T::input_pool, LOG_TRACE, mmal_component_create(), mmal_component_destroy(), MMAL_EINVAL, MMAL_ENOMEM, mmal_pool_callback_set(), mmal_port_pool_create(), MMAL_SUCCESS, MMAL_WRAPPER_T::output, MMAL_COMPONENT_T::output, MMAL_WRAPPER_T::output_num, MMAL_COMPONENT_T::output_num, MMAL_WRAPPER_T::output_pool, MMAL_WRAPPER_T::output_queue, status, vcos_calloc(), vcos_free(), vcos_getmicrosecs(), vcos_semaphore_create(), and VCOS_SUCCESS.
 {
    MMAL_STATUS_T status;
    MMAL_COMPONENT_T *component;
    MMAL_WRAPPER_PRIVATE_T *private;
    MMAL_WRAPPER_T *wrapper;
    int64_t start_time;
    unsigned int i, extra_size;
    LOG_TRACE("wrapper %p, name %s", ctx, name);
    /* Sanity checking */
    if (!ctx || !name)
       return MMAL_EINVAL;
    start_time = vcos_getmicrosecs();
    status = mmal_component_create(name, &component);
    if (status != MMAL_SUCCESS)
       return status;
    extra_size = (component->input_num * sizeof(MMAL_POOL_T*)) + (component->output_num * (sizeof(MMAL_POOL_T*) + sizeof(MMAL_QUEUE_T*)));
    private = vcos_calloc(1, sizeof(*private) + extra_size, "mmal wrapper");
    if (!private)
    {
       mmal_component_destroy(component);
       return MMAL_ENOMEM;
    }
    if (vcos_semaphore_create(&private->sema, "mmal wrapper", 0) != VCOS_SUCCESS)
    {
       mmal_component_destroy(component);
       vcos_free(private);
       return MMAL_ENOMEM;
    }
    wrapper = &private->wrapper;
    wrapper->component = component;
    wrapper->control = component->control;
    wrapper->input_num = component->input_num;
    wrapper->input = component->input;
    wrapper->output_num = component->output_num;
    wrapper->output = component->output;
    wrapper->input_pool = (MMAL_POOL_T **)&private[1];
    wrapper->output_pool = (MMAL_POOL_T **)&wrapper->input_pool[component->input_num];
    wrapper->output_queue = (MMAL_QUEUE_T **)&wrapper->output_pool[component->output_num];
    /* Create our pools and queues */
    for (i = 0; i < wrapper->input_num; i++)
    {
       wrapper->input_pool[i] = mmal_port_pool_create(wrapper->input[i], 0, 0);
       if (!wrapper->input_pool[i])
          goto error;
       mmal_pool_callback_set(wrapper->input_pool[i], mmal_wrapper_bh_release_cb, (void *)wrapper);
       wrapper->input[i]->userdata = (void *)wrapper;
    }
    for (i = 0; i < wrapper->output_num; i++)
    {
       wrapper->output_pool[i] = mmal_port_pool_create(wrapper->output[i], 0, 0);
       wrapper->output_queue[i] = mmal_queue_create();
       if (!wrapper->output_pool[i] || !wrapper->output_queue[i])
          goto error;
       mmal_pool_callback_set(wrapper->output_pool[i], mmal_wrapper_bh_release_cb, (void *)wrapper);
       wrapper->output[i]->userdata = (void *)wrapper;
    }
    /* Setup control port */
    wrapper->control->userdata = (void *)wrapper;
    status = mmal_port_enable(wrapper->control, mmal_wrapper_control_cb);
    if (status != MMAL_SUCCESS)
       goto error;
    wrapper->time_setup = vcos_getmicrosecs() - start_time;
    *ctx = wrapper;
    return MMAL_SUCCESS;
  error:
    mmal_wrapper_destroy(wrapper);
    return status == MMAL_SUCCESS ? MMAL_ENOMEM : status;
 }
mmal_wrapper_destroy()
MMAL_STATUS_T mmal_wrapper_destroy (MMAL_WRAPPER_T * wrapper)
Destroy a wrapper. Destroys a component wrapper and any resources it owns.
Parameters
wrapper The wrapper to be destroyed.
Returns
MMAL_SUCCESS on success.
Definition at line 103 of file mmal_component_wrapper.c.
References MMAL_WRAPPER_T::component, MMAL_WRAPPER_T::input_num, MMAL_WRAPPER_T::input_pool, LOG_TRACE, mmal_component_destroy(), mmal_pool_destroy(), mmal_queue_destroy(), MMAL_SUCCESS, MMAL_COMPONENT_T::name, MMAL_WRAPPER_T::output_num, MMAL_WRAPPER_T::output_pool, MMAL_WRAPPER_T::output_queue, vcos_free(), and vcos_semaphore_delete().
 {
    MMAL_WRAPPER_PRIVATE_T *private = (MMAL_WRAPPER_PRIVATE_T *)wrapper;
    unsigned int i;
    LOG_TRACE("%p, %s", wrapper, wrapper->component->name);
    /* Cleanup resources */
    mmal_component_destroy(wrapper->component);
    for (i = 0; i < wrapper->input_num; i++)
    {
       if (wrapper->input_pool[i])
          mmal_pool_destroy(wrapper->input_pool[i]);
    }
    for (i = 0; i < wrapper->output_num; i++)
    {
       if (wrapper->output_pool[i])
          mmal_pool_destroy(wrapper->output_pool[i]);
       if (wrapper->output_queue[i])
          mmal_queue_destroy(wrapper->output_queue[i]);
    }
    vcos_semaphore_delete(&private->sema);
    vcos_free(private);
    return MMAL_SUCCESS;
 }
mmal_wrapper_port_disable()
MMAL_STATUS_T mmal_wrapper_port_disable (MMAL_PORT_T * port)
Disable a port on a component wrapper.
Parameters
port port to disable
Returns
MMAL_SUCCESS on success.
Definition at line 275 of file mmal_component_wrapper.c.
References MMAL_POOL_T::headers_num, MMAL_PORT_T::index, MMAL_PORT_T::is_enabled, LOG_ERROR, LOG_TRACE, mmal_buffer_header_release(), MMAL_EINVAL, mmal_port_disable(), MMAL_PORT_TYPE_INPUT, MMAL_PORT_TYPE_OUTPUT, mmal_queue_get(), mmal_queue_length(), MMAL_SUCCESS, MMAL_PORT_T::name, NULL, MMAL_POOL_T::queue, status, MMAL_PORT_T::type, MMAL_PORT_T::userdata, vcos_getmicrosecs(), and vcos_verify.
Referenced by mmal_encode_test().
 {
    MMAL_WRAPPER_PRIVATE_T *private = (MMAL_WRAPPER_PRIVATE_T *)port->userdata;
    MMAL_WRAPPER_T *wrapper = &private->wrapper;
    int64_t start_time = vcos_getmicrosecs();
    MMAL_STATUS_T status;
    LOG_TRACE("%p, %s", wrapper, port->name);
    if (port->type != MMAL_PORT_TYPE_INPUT && port->type != MMAL_PORT_TYPE_OUTPUT)
       return MMAL_EINVAL;
    if (!port->is_enabled)
       return MMAL_SUCCESS;
    /* Disable port */
    status = mmal_port_disable(port);
    if (status != MMAL_SUCCESS)
    {
       LOG_ERROR("could not disable port");
       return status;
    }
    /* Flush the queue */
    if (port->type == MMAL_PORT_TYPE_OUTPUT)
    {
       MMAL_POOL_T *pool = wrapper->output_pool[port->index];
       MMAL_QUEUE_T *queue = wrapper->output_queue[port->index];
       MMAL_BUFFER_HEADER_T *buffer;
       while ((buffer = mmal_queue_get(queue)) != NULL)
          mmal_buffer_header_release(buffer);
       if ( !vcos_verify(mmal_queue_length(pool->queue) == pool->headers_num) )
       {
          LOG_ERROR("coul dnot release all buffers");
       }
    }
    wrapper->time_disable = vcos_getmicrosecs() - start_time;
    return status;
 }
mmal_wrapper_port_enable()
MMAL_STATUS_T mmal_wrapper_port_enable (MMAL_PORT_T * port, uint32_t flags)
Enable a port on a component wrapper.
Parameters
port port to enable
flags used to specify payload allocation flags for the pool
Returns
MMAL_SUCCESS on success.
Definition at line 217 of file mmal_component_wrapper.c.
References MMAL_PORT_T::buffer_num, MMAL_PORT_T::buffer_size, MMAL_PARAMETER_BOOLEAN_T::hdr, MMAL_PORT_T::index, MMAL_PORT_T::is_enabled, LOG_ERROR, LOG_TRACE, MMAL_EINVAL, MMAL_ENOSYS, MMAL_PARAMETER_ZERO_COPY, mmal_pool_resize(), mmal_port_enable(), mmal_port_parameter_set(), MMAL_PORT_TYPE_INPUT, MMAL_PORT_TYPE_OUTPUT, MMAL_SUCCESS, MMAL_WRAPPER_FLAG_PAYLOAD_ALLOCATE, MMAL_WRAPPER_FLAG_PAYLOAD_USE_SHARED_MEMORY, MMAL_PORT_T::name, status, MMAL_PORT_T::type, MMAL_PORT_T::userdata, and vcos_getmicrosecs().
Referenced by mmal_encode_test().
 {
    MMAL_WRAPPER_PRIVATE_T *private = (MMAL_WRAPPER_PRIVATE_T *)port->userdata;
    MMAL_WRAPPER_T *wrapper = &private->wrapper;
    int64_t start_time = vcos_getmicrosecs();
    uint32_t buffer_size;
    MMAL_STATUS_T status;
    MMAL_POOL_T *pool;
    LOG_TRACE("%p, %s", wrapper, port->name);
    if (port->type != MMAL_PORT_TYPE_INPUT && port->type != MMAL_PORT_TYPE_OUTPUT)
       return MMAL_EINVAL;
    if (port->is_enabled)
       return MMAL_SUCCESS;
    pool = port->type == MMAL_PORT_TYPE_INPUT ?
       wrapper->input_pool[port->index] : wrapper->output_pool[port->index];
    buffer_size = (flags & MMAL_WRAPPER_FLAG_PAYLOAD_ALLOCATE) ? port->buffer_size : 0;
    /* FIXME: we don't support switching between shared and non-shared memory.
     * We would need to save the flag and force a pool resize when switching. */
    if (flags & MMAL_WRAPPER_FLAG_PAYLOAD_USE_SHARED_MEMORY)
    {
       MMAL_PARAMETER_BOOLEAN_T param_zc =
          {{MMAL_PARAMETER_ZERO_COPY, sizeof(MMAL_PARAMETER_BOOLEAN_T)}, 1};
       status = mmal_port_parameter_set(port, &param_zc.hdr);
       if (status != MMAL_SUCCESS && status != MMAL_ENOSYS)
       {
          LOG_ERROR("failed to set zero copy on %s", port->name);
          return status;
       }
    }
    /* Resize the pool */
    status = mmal_pool_resize(pool, port->buffer_num, buffer_size);
    if (status != MMAL_SUCCESS)
    {
       LOG_ERROR("could not resize pool (%i/%i)", (int)port->buffer_num, (int)buffer_size);
       return status;
    }
    /* Enable port. The callback specified here is the function which
     * will be called when a buffer header comes back to the port. */
    status = mmal_port_enable(port, port->type == MMAL_PORT_TYPE_INPUT ?
                              mmal_wrapper_bh_in_cb : mmal_wrapper_bh_out_cb);
    if (status != MMAL_SUCCESS)
    {
       LOG_ERROR("could not enable port");
       return status;
    }
    wrapper->time_enable += vcos_getmicrosecs() - start_time;
    return MMAL_SUCCESS;
 }