VideoCore Library: host_applications/linux/apps/hello_pi/hello_audio/audio.c File Reference
audio.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <assert.h>
#include <unistd.h>
#include <semaphore.h>
#include "bcm_host.h"
#include "ilclient.h"
Classes
struct AUDIOPLAY_STATE_T
Macros
#define N_WAVE 1024 /* dimension of Sinewave[] */
#define PI (1<<16>>1)
#define SIN(x) Sinewave[((x)>>6) & (N_WAVE-1)]
#define COS(x) SIN((x)+(PI>>1))
#define OUT_CHANNELS(num_channels) ((num_channels) > 4 ? 8: (num_channels) > 2 ? 4: (num_channels))
#define countof(arr) (sizeof(arr) / sizeof(arr[0]))
#define BUFFER_SIZE_SAMPLES 1024
#define CTTW_SLEEP_TIME 10
#define MIN_LATENCY_TIME 20
Typedefs
typedef int int32_t
Functions
int32_t audioplay_create (AUDIOPLAY_STATE_T **handle, uint32_t sample_rate, uint32_t num_channels, uint32_t bit_depth, uint32_t num_buffers, uint32_t buffer_size)
int32_t audioplay_delete (AUDIOPLAY_STATE_T *st)
uint8_t * audioplay_get_buffer (AUDIOPLAY_STATE_T *st)
int32_t audioplay_play_buffer (AUDIOPLAY_STATE_T *st, uint8_t *buffer, uint32_t length)
int32_t audioplay_set_dest (AUDIOPLAY_STATE_T *st, const char *name)
uint32_t audioplay_get_latency (AUDIOPLAY_STATE_T *st)
void play_api_test (int samplerate, int bitdepth, int nchannels, int dest)
int main (int argc, char **argv)
Variables
short Sinewave []
Macro Definition Documentation
BUFFER_SIZE_SAMPLES
#define BUFFER_SIZE_SAMPLES 1024
Definition at line 51 of file audio.c.
Referenced by play_api_test().
COS
#define COS (x) SIN((x)+(PI>>1))
Definition at line 43 of file audio.c.
countof
#define countof (arr) (sizeof(arr) / sizeof(arr[0]))
Definition at line 48 of file audio.c.
CTTW_SLEEP_TIME
#define CTTW_SLEEP_TIME 10
Definition at line 337 of file audio.c.
MIN_LATENCY_TIME
#define MIN_LATENCY_TIME 20
Definition at line 338 of file audio.c.
N_WAVE
#define N_WAVE 1024 /* dimension of Sinewave[] */
Definition at line 40 of file audio.c.
OUT_CHANNELS
#define OUT_CHANNELS (num_channels) ((num_channels) > 4 ? 8: (num_channels) > 2 ? 4: (num_channels))
Definition at line 44 of file audio.c.
Referenced by audioplay_create(), and play_api_test().
PI
#define PI (1<<16>>1)
Definition at line 41 of file audio.c.
SIN
#define SIN (x) Sinewave[((x)>>6) & (N_WAVE-1)]
Definition at line 42 of file audio.c.
Typedef Documentation
int32_t
typedef int int32_t
Definition at line 53 of file audio.c.
Function Documentation
audioplay_create()
int32_t audioplay_create (AUDIOPLAY_STATE_T ** handle, uint32_t sample_rate, uint32_t num_channels, uint32_t bit_depth, uint32_t num_buffers, uint32_t buffer_size)
The audioplay_create() function creates the audioplay object.
Parameters
handle On success, this is filled in with a handle to use in other API functions.
sample_rate The sample rate, in samples per second, for the PCM data. This shall be between 8000 and 96000.
num_channels The number of channels for the PCM data. Must be 1, 2, 4, or 8. Channels must be sent interleaved.
bit_depth The bitdepth per channel per sample. Must be 16 or 32.
num_buffers The number of buffers that will be created to write PCM samples into.
buffer_size The size in bytes of each buffer that will be used to write PCM samples into. Note that small buffers of less than a few Kb in size may be faster than larger buffers, although this is platform dependent.
Returns
0 on success, -1 on failure.
Definition at line 71 of file audio.c.
References assert(), AUDIOPLAY_STATE_T::bytes_per_sample, AUDIOPLAY_STATE_T::client, error(), ilclient_init(), ilclient_set_empty_buffer_done_callback(), NULL, AUDIOPLAY_STATE_T::num_buffers, OUT_CHANNELS, and AUDIOPLAY_STATE_T::sema.
Referenced by play_api_test().
 {
    uint32_t bytes_per_sample = (bit_depth * OUT_CHANNELS(num_channels)) >> 3;
    int32_t ret = -1;
    *handle = NULL;
    // basic sanity check on arguments
    if(sample_rate >= 8000 && sample_rate <= 192000 &&
       (num_channels >= 1 && num_channels <= 8) &&
       (bit_depth == 16 || bit_depth == 32) &&
       num_buffers > 0 &&
       buffer_size >= bytes_per_sample)
    {
       // buffer lengths must be 16 byte aligned for VCHI
       int size = (buffer_size + 15) & ~15;
       AUDIOPLAY_STATE_T *st;
       // buffer offsets must also be 16 byte aligned for VCHI
       st = calloc(1, sizeof(AUDIOPLAY_STATE_T));
       if(st)
       {
          OMX_ERRORTYPE error;
          OMX_PARAM_PORTDEFINITIONTYPE param;
          OMX_AUDIO_PARAM_PCMMODETYPE pcm;
          int32_t s;
          ret = 0;
          *handle = st;
          // create and start up everything
          s = sem_init(&st->sema, 0, 1);
          assert(s == 0);
          st->bytes_per_sample = bytes_per_sample;
          st->num_buffers = num_buffers;
          st->client = ilclient_init();
          assert(st->client != NULL);
          ilclient_set_empty_buffer_done_callback(st->client, input_buffer_callback, st);
          error = OMX_Init();
          assert(error == OMX_ErrorNone);
          ilclient_create_component(st->client, &st->audio_render, "audio_render", ILCLIENT_ENABLE_INPUT_BUFFERS | ILCLIENT_DISABLE_ALL_PORTS);
          assert(st->audio_render != NULL);
          st->list[0] = st->audio_render;
          // set up the number/size of buffers
          memset(&param, 0, sizeof(OMX_PARAM_PORTDEFINITIONTYPE));
          param.nSize = sizeof(OMX_PARAM_PORTDEFINITIONTYPE);
          param.nVersion.nVersion = OMX_VERSION;
          param.nPortIndex = 100;
          error = OMX_GetParameter(ILC_GET_HANDLE(st->audio_render), OMX_IndexParamPortDefinition, &param);
          assert(error == OMX_ErrorNone);
          param.nBufferSize = size;
          param.nBufferCountActual = num_buffers;
          error = OMX_SetParameter(ILC_GET_HANDLE(st->audio_render), OMX_IndexParamPortDefinition, &param);
          assert(error == OMX_ErrorNone);
          // set the pcm parameters
          memset(&pcm, 0, sizeof(OMX_AUDIO_PARAM_PCMMODETYPE));
          pcm.nSize = sizeof(OMX_AUDIO_PARAM_PCMMODETYPE);
          pcm.nVersion.nVersion = OMX_VERSION;
          pcm.nPortIndex = 100;
          pcm.nChannels = OUT_CHANNELS(num_channels);
          pcm.eNumData = OMX_NumericalDataSigned;
          pcm.eEndian = OMX_EndianLittle;
          pcm.nSamplingRate = sample_rate;
          pcm.bInterleaved = OMX_TRUE;
          pcm.nBitPerSample = bit_depth;
          pcm.ePCMMode = OMX_AUDIO_PCMModeLinear;
          switch(num_channels) {
          case 1:
             pcm.eChannelMapping[0] = OMX_AUDIO_ChannelCF;
             break;
          case 3:
             pcm.eChannelMapping[2] = OMX_AUDIO_ChannelCF;
             pcm.eChannelMapping[1] = OMX_AUDIO_ChannelRF;
             pcm.eChannelMapping[0] = OMX_AUDIO_ChannelLF;
             break;
          case 8:
             pcm.eChannelMapping[7] = OMX_AUDIO_ChannelRS;
          case 7:
             pcm.eChannelMapping[6] = OMX_AUDIO_ChannelLS;
          case 6:
             pcm.eChannelMapping[5] = OMX_AUDIO_ChannelRR;
          case 5:
             pcm.eChannelMapping[4] = OMX_AUDIO_ChannelLR;
          case 4:
             pcm.eChannelMapping[3] = OMX_AUDIO_ChannelLFE;
             pcm.eChannelMapping[2] = OMX_AUDIO_ChannelCF;
          case 2:
             pcm.eChannelMapping[1] = OMX_AUDIO_ChannelRF;
             pcm.eChannelMapping[0] = OMX_AUDIO_ChannelLF;
             break;
          }
          error = OMX_SetParameter(ILC_GET_HANDLE(st->audio_render), OMX_IndexParamAudioPcm, &pcm);
          assert(error == OMX_ErrorNone);
          ilclient_change_component_state(st->audio_render, OMX_StateIdle);
          if(ilclient_enable_port_buffers(st->audio_render, 100, NULL, NULL, NULL) < 0)
          {
             // error
             ilclient_change_component_state(st->audio_render, OMX_StateLoaded);
             ilclient_cleanup_components(st->list);
             error = OMX_Deinit();
             assert(error == OMX_ErrorNone);
             ilclient_destroy(st->client);
             sem_destroy(&st->sema);
             free(st);
             *handle = NULL;
             return -1;
          }
          ilclient_change_component_state(st->audio_render, OMX_StateExecuting);
       }
    }
    return ret;
 }
audioplay_delete()
int32_t audioplay_delete (AUDIOPLAY_STATE_T * handle)
The audioplay_delete() function deletes the audioplay object.
Parameters
handle Must be a handle previously created by audioplay_create(). After calling this function that handle is no longer valid. Any buffers provided by audioplay_get_buffer() are also no longer valid and must not be referenced.
Returns
0 on success, -1 on failure.
Definition at line 209 of file audio.c.
References assert(), AUDIOPLAY_STATE_T::audio_render, AUDIOPLAY_STATE_T::client, error(), ILC_GET_HANDLE, ilclient_change_component_state(), ilclient_cleanup_components(), ilclient_destroy(), ilclient_disable_port_buffers(), AUDIOPLAY_STATE_T::list, NULL, OMX_CommandStateSet, OMX_Deinit(), OMX_ErrorNone, OMX_SendCommand, OMX_StateIdle, OMX_StateLoaded, AUDIOPLAY_STATE_T::sema, and AUDIOPLAY_STATE_T::user_buffer_list.
 {
    OMX_ERRORTYPE error;
    ilclient_change_component_state(st->audio_render, OMX_StateIdle);
    error = OMX_SendCommand(ILC_GET_HANDLE(st->audio_render), OMX_CommandStateSet, OMX_StateLoaded, NULL);
    assert(error == OMX_ErrorNone);
    ilclient_disable_port_buffers(st->audio_render, 100, st->user_buffer_list, NULL, NULL);
    ilclient_change_component_state(st->audio_render, OMX_StateLoaded);
    ilclient_cleanup_components(st->list);
    error = OMX_Deinit();
    assert(error == OMX_ErrorNone);
    ilclient_destroy(st->client);
    sem_destroy(&st->sema);
    free(st);
    return 0;
 }
audioplay_get_buffer()
uint8_t* audioplay_get_buffer (AUDIOPLAY_STATE_T * handle)
The audioplay_get_buffer() function requests an empty buffer. Any buffer returned will have the valid size indicated in the call to audioplay_create().
Parameters
handle Must be a handle previously created by audioplay_create().
Returns
A pointer to an available buffer. If no buffers are available, then NULL will be returned.
Definition at line 233 of file audio.c.
References AUDIOPLAY_STATE_T::audio_render, ilclient_get_input_buffer(), NULL, OMX_BUFFERHEADERTYPE::pAppPrivate, OMX_BUFFERHEADERTYPE::pBuffer, AUDIOPLAY_STATE_T::sema, and AUDIOPLAY_STATE_T::user_buffer_list.
 {
    OMX_BUFFERHEADERTYPE *hdr = NULL;
    hdr = ilclient_get_input_buffer(st->audio_render, 100, 0);
    if(hdr)
    {
       // put on the user list
       sem_wait(&st->sema);
       hdr->pAppPrivate = st->user_buffer_list;
       st->user_buffer_list = hdr;
       sem_post(&st->sema);
    }
    return hdr ? hdr->pBuffer : NULL;
 }
audioplay_get_latency()
uint32_t audioplay_get_latency (AUDIOPLAY_STATE_T * handle)
The audioplay_get_latency() requests the current audio playout buffer size in samples, which is the latency until the next sample supplied is to be rendered.
Parameters
handle Must be a handle previously created by audioplay_create().
Returns
Number of samples currently buffered.
Definition at line 321 of file audio.c.
References assert(), AUDIOPLAY_STATE_T::audio_render, error(), ILC_GET_HANDLE, OMX_PARAM_U32TYPE::nPortIndex, OMX_PARAM_U32TYPE::nSize, OMX_PARAM_U32TYPE::nU32, OMX_PARAM_U32TYPE::nVersion, OMX_VERSIONTYPE::nVersion, OMX_ErrorNone, OMX_GetConfig, OMX_IndexConfigAudioRenderingLatency, and OMX_VERSION.
 {
    OMX_PARAM_U32TYPE param;
    OMX_ERRORTYPE error;
    memset(&param, 0, sizeof(OMX_PARAM_U32TYPE));
    param.nSize = sizeof(OMX_PARAM_U32TYPE);
    param.nVersion.nVersion = OMX_VERSION;
    param.nPortIndex = 100;
    error = OMX_GetConfig(ILC_GET_HANDLE(st->audio_render), OMX_IndexConfigAudioRenderingLatency, &param);
    assert(error == OMX_ErrorNone);
    return param.nU32;
 }
audioplay_play_buffer()
int32_t audioplay_play_buffer (AUDIOPLAY_STATE_T * handle, uint8_t * buffer, uint32_t length)
The audioplay_play_buffer() sends a buffer containing raw samples to be rendered.
Parameters
handle Must be a handle previously created by audioplay_create().
buffer Must be a pointer previously returned by audioplay_get_buffer(). After calling this function the buffer pointer must not be referenced until returned again by another call to audioplay_get_buffer().
length Length in bytes of valid data. Must be a whole number of samples, ie a multiple of (num_channels*bit_depth/8).
Returns
0 on success, -1 on failure
Definition at line 253 of file audio.c.
References assert(), AUDIOPLAY_STATE_T::audio_render, AUDIOPLAY_STATE_T::bytes_per_sample, error(), ILC_GET_HANDLE, OMX_BUFFERHEADERTYPE::nAllocLen, OMX_BUFFERHEADERTYPE::nFilledLen, OMX_BUFFERHEADERTYPE::nOffset, NULL, OMX_EmptyThisBuffer, OMX_ErrorNone, OMX_BUFFERHEADERTYPE::pAppPrivate, OMX_BUFFERHEADERTYPE::pBuffer, AUDIOPLAY_STATE_T::sema, and AUDIOPLAY_STATE_T::user_buffer_list.
 {
    OMX_BUFFERHEADERTYPE *hdr = NULL, *prev = NULL;
    int32_t ret = -1;
    if(length % st->bytes_per_sample)
       return ret;
    sem_wait(&st->sema);
    // search through user list for the right buffer header
    hdr = st->user_buffer_list;
    while(hdr != NULL && hdr->pBuffer != buffer && hdr->nAllocLen < length)
    {
       prev = hdr;
       hdr = hdr->pAppPrivate;
    }
    if(hdr) // we found it, remove from list
    {
       ret = 0;
       if(prev)
          prev->pAppPrivate = hdr->pAppPrivate;
       else
          st->user_buffer_list = hdr->pAppPrivate;
    }
    sem_post(&st->sema);
    if(hdr)
    {
       OMX_ERRORTYPE error;
       hdr->pAppPrivate = NULL;
       hdr->nOffset = 0;
       hdr->nFilledLen = length;
       error = OMX_EmptyThisBuffer(ILC_GET_HANDLE(st->audio_render), hdr);
       assert(error == OMX_ErrorNone);
    }
    return ret;
 }
audioplay_set_dest()
int32_t audioplay_set_dest (AUDIOPLAY_STATE_T * st, const char * name)
Definition at line 299 of file audio.c.
References assert(), AUDIOPLAY_STATE_T::audio_render, error(), ILC_GET_HANDLE, OMX_CONFIG_BRCMAUDIODESTINATIONTYPE::nSize, OMX_VERSIONTYPE::nVersion, OMX_CONFIG_BRCMAUDIODESTINATIONTYPE::nVersion, OMX_ErrorNone, OMX_IndexConfigBrcmAudioDestination, OMX_SetConfig, OMX_VERSION, and OMX_CONFIG_BRCMAUDIODESTINATIONTYPE::sName.
Referenced by play_api_test().
 {
    int32_t success = -1;
    OMX_CONFIG_BRCMAUDIODESTINATIONTYPE ar_dest;
    if (name && strlen(name) < sizeof(ar_dest.sName))
    {
       OMX_ERRORTYPE error;
       memset(&ar_dest, 0, sizeof(ar_dest));
       ar_dest.nSize = sizeof(OMX_CONFIG_BRCMAUDIODESTINATIONTYPE);
       ar_dest.nVersion.nVersion = OMX_VERSION;
       strcpy((char *)ar_dest.sName, name);
       error = OMX_SetConfig(ILC_GET_HANDLE(st->audio_render), OMX_IndexConfigBrcmAudioDestination, &ar_dest);
       assert(error == OMX_ErrorNone);
       success = 0;
    }
    return success;
 }
main()
int main (int argc, char ** argv)
Definition at line 402 of file audio.c.
 {
    // 0=headphones, 1=hdmi
    int audio_dest = 0;
    // audio sample rate in Hz
    int samplerate = 48000;
    // numnber of audio channels
    int channels = 2;
    // number of bits per sample
    int bitdepth = 16;
    bcm_host_init();
    if (argc > 1)
       audio_dest = atoi(argv[1]);
    if (argc > 2)
       channels = atoi(argv[2]);
    if (argc > 3)
       samplerate = atoi(argv[3]);
    printf("Outputting audio to %s\n", audio_dest==0 ? "analogue":"hdmi");
    play_api_test(samplerate, bitdepth, channels, audio_dest);
    return 0;
 }
play_api_test()
void play_api_test (int samplerate, int bitdepth, int nchannels, int dest)
Definition at line 341 of file audio.c.
References assert(), audioplay_create(), audioplay_set_dest(), BUFFER_SIZE_SAMPLES, and OUT_CHANNELS.
 {
    AUDIOPLAY_STATE_T *st;
    int32_t ret;
    unsigned int i, j, n;
    int phase = 0;
    int inc = 256<<16;
    int dinc = 0;
    int buffer_size = (BUFFER_SIZE_SAMPLES * bitdepth * OUT_CHANNELS(nchannels))>>3;
    assert(dest == 0 || dest == 1);
    ret = audioplay_create(&st, samplerate, nchannels, bitdepth, 10, buffer_size);
    assert(ret == 0);
    ret = audioplay_set_dest(st, audio_dest[dest]);
    assert(ret == 0);
    // iterate for 5 seconds worth of packets
    for (n=0; n<((samplerate * 1000)/ BUFFER_SIZE_SAMPLES); n++)
    {
       uint8_t *buf;
       int16_t *p;
       uint32_t latency;
       while((buf = audioplay_get_buffer(st)) == NULL)
          usleep(10*1000);
       p = (int16_t *) buf;
       // fill the buffer
       for (i=0; i<BUFFER_SIZE_SAMPLES; i++)
       {
          int16_t val = SIN(phase);
          phase += inc>>16;
          inc += dinc;
          if (inc>>16 < 512)
             dinc++;
          else
             dinc--;
          for(j=0; j<OUT_CHANNELS(nchannels); j++)
          {
             if (bitdepth == 32)
                *p++ = 0;
             *p++ = val;
          }
       }
       // try and wait for a minimum latency time (in ms) before
       // sending the next packet
       while((latency = audioplay_get_latency(st)) > (samplerate * (MIN_LATENCY_TIME + CTTW_SLEEP_TIME) / 1000))
          usleep(CTTW_SLEEP_TIME*1000);
       ret = audioplay_play_buffer(st, buf, buffer_size);
       assert(ret == 0);
    }
    audioplay_delete(st);
 }
Variable Documentation
Sinewave
short Sinewave[]
Definition at line 30 of file sinewave.c.