VideoCore Library: interface/vcos/user_nodefs.h File Reference
user_nodefs.h File Reference
Functions
void assert (int cond)
Function Documentation
assert()
void assert (int cond)
Referenced by audioplay_create(), audioplay_delete(), audioplay_get_latency(), audioplay_play_buffer(), audioplay_set_dest(), deinit(), egl_gce_win_change_image(), ilclient_suggest_bufsize(), init(), main(), platform_destroy_winhandle(), platform_maybe_free_process(), platform_retrieve_pixmap_completed(), platform_send_pixmap_completed(), play_api_test(), PS_construct(), PS_destruct(), PS_render(), render(), TESTER_T::run(), vc_gencmd_init(), vc_hostfs_init(), and vgft_font_convert_glyphs().