VideoCore Library: interface/vmcs_host/vcgencmd.h File Reference
vcgencmd.h File Reference
#include "vchost_platform_config.h"
#include "interface/vchi/vchi.h"
Functions
VCHPRE_ void VCHPOST_ vc_vchi_gencmd_init (VCHI_INSTANCE_T initialise_instance, VCHI_CONNECTION_T **connections, uint32_t num_connections)
VCHPRE_ int VCHPOST_ vc_gencmd_init (void)
VCHPRE_ void VCHPOST_ vc_gencmd_stop (void)
VCHPRE_ int VCHPOST_ vc_gencmd_inum (void)
VCHPRE_ int VCHPOST_ vc_gencmd_send (const char *format,...)
VCHPRE_ int VCHPOST_ vc_gencmd_read_response (char *response, int maxlen)
VCHPRE_ int VCHPOST_ vc_gencmd (char *response, int maxlen, const char *format,...)
VCHPRE_ int VCHPOST_ vc_gencmd_read_response_partial (char *response, int nbytes)
VCHPRE_ int VCHPOST_ vc_gencmd_close_response_partial (void)
VCHPRE_ int VCHPOST_ vc_gencmd_read_partial_state (void)
VCHPRE_ int VCHPOST_ vc_gencmd_string_property (char *text, const char *property, char **value, int *length)
VCHPRE_ int VCHPOST_ vc_gencmd_number_property (char *text, const char *property, int *number)
VCHPRE_ int VCHPOST_ vc_gencmd_until (char *cmd, const char *property, char *value, const char *error_string, int timeout)
Function Documentation
vc_gencmd()
VCHPRE_ int VCHPOST_ vc_gencmd (char * response, int maxlen, const char * format, ...)
Definition at line 363 of file vc_vchi_gencmd.c.
References release_gencmd_service(), use_gencmd_service(), vc_gencmd_read_response(), and vc_gencmd_send_list().
Referenced by vc_gencmd_until().
{
    va_list args;
    int ret = -1;
    use_gencmd_service();
    va_start(args, format);
    ret = vc_gencmd_send_list(format, args);
    va_end (args);
    if (ret >= 0) {
       ret = vc_gencmd_read_response(response, maxlen);
    }
    release_gencmd_service();
    return ret;
 }
vc_gencmd_close_response_partial()
VCHPRE_ int VCHPOST_ vc_gencmd_close_response_partial (void)
vc_gencmd_init()
VCHPRE_ int VCHPOST_ vc_gencmd_init (void)
Definition at line 106 of file vc_vchi_gencmd.c.
References assert().
                      {
    assert(0);
    return 0;
 }
vc_gencmd_inum()
VCHPRE_ int VCHPOST_ vc_gencmd_inum (void)
vc_gencmd_number_property()
VCHPRE_ int VCHPOST_ vc_gencmd_number_property (char * text, const char * property, int * number)
Definition at line 468 of file vc_vchi_gencmd.c.
References vc_gencmd_string_property().
{
    char *value, temp;
    int length, retval;
    if (vc_gencmd_string_property(text, property, &value, &length) == 0)
       return 0;
    temp = value[length];
    value[length] = 0;
    /* coverity[secure_coding] - this is not insecure */
    retval = sscanf(value, "0x%x", (unsigned int*)number);
    if (retval != 1)
       /* coverity[secure_coding] - this is not insecure */
       retval = sscanf(value, "%d", number);
    value[length] = temp;
    return retval;
 }
vc_gencmd_read_partial_state()
VCHPRE_ int VCHPOST_ vc_gencmd_read_partial_state (void)
vc_gencmd_read_response()
VCHPRE_ int VCHPOST_ vc_gencmd_read_response (char * response, int maxlen)
Definition at line 306 of file vc_vchi_gencmd.c.
Referenced by main(), and vc_gencmd().
{
    int i = 0;
    int success = -1;
    int ret_code = 0;
    int32_t sem_ok = 0;
    if(lock_obtain() == 0)
    {
       //Note this will ALWAYS reset response buffer and overwrite any partially read responses
       use_gencmd_service();
       do {
          //TODO : we need to deal with messages coming through on more than one connections properly
          //At the moment it will always try to read the first connection if there is something there
          for(i = 0; i < gencmd_client.num_connections; i++) {
             //Check if there is something in the queue, if so return immediately
             //otherwise wait for the event and read again
             success = (int) vchi_msg_dequeue( gencmd_client.open_handle[i], gencmd_client.response_buffer,
                                               sizeof(gencmd_client.response_buffer), &gencmd_client.response_length, VCHI_FLAGS_NONE);
             if(success == 0) {
                ret_code = VC_VTOH32( *(int *)gencmd_client.response_buffer );
                break;
             } else {
                gencmd_client.response_length = 0;
             }
          }
       } while(!gencmd_client.response_length && vcos_event_wait(&gencmd_client.message_available_event) == VCOS_SUCCESS);
       if(gencmd_client.response_length && sem_ok == 0) {
          gencmd_client.response_length -= sizeof(int); //first word is error code
          memcpy(response, gencmd_client.response_buffer+sizeof(int), (size_t) vcos_min((int)gencmd_client.response_length, (int)maxlen));
       }
       release_gencmd_service();
       lock_release();
    }
    // If we read anything, return the VideoCore code. Error codes < 0 mean we failed to
    // read anything...
    //How do we let the caller know the response code of gencmd?
    //return ret_code;
    return success;
 }
vc_gencmd_read_response_partial()
VCHPRE_ int VCHPOST_ vc_gencmd_read_response_partial (char * response, int nbytes)
vc_gencmd_send()
VCHPRE_ int VCHPOST_ vc_gencmd_send (const char * format, ...)
Definition at line 282 of file vc_vchi_gencmd.c.
References vc_gencmd_send_list().
Referenced by main().
 {
    va_list a;
    int     rv;
    va_start ( a, format );
    rv = vc_gencmd_send_list( format, a );
    va_end ( a );
    return rv;
 }
vc_gencmd_stop()
VCHPRE_ void VCHPOST_ vc_gencmd_stop (void)
Definition at line 210 of file vc_vchi_gencmd.c.
References GENCMD_SERVICE_T::initialised.
Referenced by main().
{
    // Assume a "power down" gencmd has been sent and the lock is held. There will
    // be no response so this should be called instead.
    int32_t success,i;
    if (!gencmd_client.initialised)
       return;
    if(lock_obtain() == 0)
    {
       use_gencmd_service();
       for(i = 0; i< (int32_t)gencmd_client.num_connections; i++) {
          success = vchi_service_close( gencmd_client.open_handle[i]);
          assert(success == 0);
       }
       gencmd_client.initialised = 0;
       lock_release();
       vcos_mutex_delete(&gencmd_client.lock);
       vcos_event_delete(&gencmd_client.message_available_event);
    }
 }
vc_gencmd_string_property()
VCHPRE_ int VCHPOST_ vc_gencmd_string_property (char * text, const char * property, char ** value, int * length)
Definition at line 400 of file vc_vchi_gencmd.c.
Referenced by vc_gencmd_number_property(), and vc_gencmd_until().
{
 #define READING_PROPERTY 0
 #define READING_VALUE 1
 #define READING_VALUE_QUOTED 2
    int state = READING_PROPERTY;
    int delimiter = 1, match = 0, len = (int)strlen(property);
    char *prop_start=text, *value_start=text;
    for (; *text; text++) {
       int ch = *text;
       switch (state) {
       case READING_PROPERTY:
          if (delimiter) prop_start = text;
          if (isspace(ch)) delimiter = 1;
          else if (ch == '=') {
             delimiter = 1;
             match = (text-prop_start==len && strncmp(prop_start, property, (size_t)(text-prop_start))==0);
             state = READING_VALUE;
          }
          else delimiter = 0;
          break;
       case READING_VALUE:
          if (delimiter) value_start = text;
          if (isspace(ch)) {
             if (match) goto success;
             delimiter = 1;
             state = READING_PROPERTY;
          }
          else if (delimiter && ch == '"') {
             delimiter = 1;
             state = READING_VALUE_QUOTED;
          }
          else delimiter = 0;
          break;
       case READING_VALUE_QUOTED:
          if (delimiter) value_start = text;
          if (ch == '"') {
             if (match) goto success;
             delimiter = 1;
             state = READING_PROPERTY;
          }
          else delimiter = 0;
          break;
       }
    }
    if (match) goto success;
    return 0;
 success:
    *value = value_start;
    *length = text - value_start;
    return 1;
 }
vc_gencmd_until()
VCHPRE_ int VCHPOST_ vc_gencmd_until (char * cmd, const char * property, char * value, const char * error_string, int timeout)
Definition at line 504 of file vc_vchi_gencmd.c.
References release_gencmd_service(), use_gencmd_service(), vc_gencmd(), vc_gencmd_string_property(), and vcos_sleep().
{
    char response[128];
    int length;
    char *ret_value;
    int ret = 1;
    use_gencmd_service();
    for (;timeout > 0; timeout -= 10) {
       vc_gencmd(response, (int)sizeof(response), cmd);
       if (strstr(response,error_string)) {
          ret = 1;
          break;
       }
       else if (vc_gencmd_string_property(response, property, &ret_value, &length) &&
                strncmp(value,ret_value,(size_t)length)==0) {
          ret = 0;
          break;
       }
       vcos_sleep(10);
    }
    release_gencmd_service();
    return ret;
 }
vc_vchi_gencmd_init()
VCHPRE_ void VCHPOST_ vc_vchi_gencmd_init (VCHI_INSTANCE_T initialise_instance, VCHI_CONNECTION_T ** connections, uint32_t num_connections)
Definition at line 126 of file vc_vchi_gencmd.c.
References GENCMD_SERVICE_T::initialised, GENCMD_SERVICE_T::lock, MAKE_FOURCC, GENCMD_SERVICE_T::message_available_event, GENCMD_SERVICE_T::num_connections, status, VC_GENCMD_VER, VCHI_VERSION, vcos_assert, vcos_event_create(), vcos_mutex_create(), and VCOS_SUCCESS.
Referenced by main().
 {
    VCOS_STATUS_T status;
    int32_t success;
    int i;
    if (gencmd_client.initialised)
      return;
    // record the number of connections
    memset( &gencmd_client, 0, sizeof(GENCMD_SERVICE_T) );
    gencmd_client.num_connections = (int) num_connections;
    status = vcos_mutex_create(&gencmd_client.lock, "HGencmd");
    vcos_assert(status == VCOS_SUCCESS);
    status = vcos_event_create(&gencmd_client.message_available_event, "HGencmd");
    vcos_assert(status == VCOS_SUCCESS);
    for (i=0; i<gencmd_client.num_connections; i++) {
       // Create a 'LONG' service on the each of the connections
       SERVICE_CREATION_T gencmd_parameters = { VCHI_VERSION(VC_GENCMD_VER),
                                                MAKE_FOURCC("GCMD"),      // 4cc service code
                                                connections[i],           // passed in fn ptrs
                                                0,                        // tx fifo size (unused)
                                                0,                        // tx fifo size (unused)
                                                &gencmd_callback,         // service callback
                                                &gencmd_client.message_available_event, // callback parameter
                                                VC_FALSE,                 // want_unaligned_bulk_rx
                                                VC_FALSE,                 // want_unaligned_bulk_tx
                                                VC_FALSE                  // want_crc
                                                };
       success = vchi_service_open( initialise_instance, &gencmd_parameters, &gencmd_client.open_handle[i] );
       assert( success == 0 );
    }
    gencmd_client.initialised = 1;
    release_gencmd_service();
 }