VideoCore Library: containers/core/containers_writer_utils.c File Reference
containers_writer_utils.c File Reference
#include <stdlib.h>
#include <string.h>
#include "containers/containers.h"
#include "containers/core/containers_private.h"
#include "containers/core/containers_utils.h"
#include "containers/core/containers_writer_utils.h"
#include "vcos.h"
#include <stdio.h>
Functions
VC_CONTAINER_STATUS_T vc_container_writer_extraio_create_null (VC_CONTAINER_T *context, VC_CONTAINER_WRITER_EXTRAIO_T *extraio)
VC_CONTAINER_STATUS_T vc_container_writer_extraio_create_temp (VC_CONTAINER_T *context, VC_CONTAINER_WRITER_EXTRAIO_T *extraio)
VC_CONTAINER_STATUS_T vc_container_writer_extraio_delete (VC_CONTAINER_T *context, VC_CONTAINER_WRITER_EXTRAIO_T *extraio)
int64_t vc_container_writer_extraio_enable (VC_CONTAINER_T *context, VC_CONTAINER_WRITER_EXTRAIO_T *extraio)
int64_t vc_container_writer_extraio_disable (VC_CONTAINER_T *context, VC_CONTAINER_WRITER_EXTRAIO_T *extraio)
Function Documentation
vc_container_writer_extraio_create_null()
VC_CONTAINER_STATUS_T vc_container_writer_extraio_create_null (VC_CONTAINER_T * context, VC_CONTAINER_WRITER_EXTRAIO_T * extraio)
Definition at line 53 of file containers_writer_utils.c.
Referenced by asf_writer_open(), avi_writer_open(), and mp4_writer_open().
 {
    return vc_container_writer_extraio_create(context, "null://", extraio);
 }
vc_container_writer_extraio_create_temp()
VC_CONTAINER_STATUS_T vc_container_writer_extraio_create_temp (VC_CONTAINER_T * context, VC_CONTAINER_WRITER_EXTRAIO_T * extraio)
Definition at line 59 of file containers_writer_utils.c.
Referenced by avi_writer_open(), and mp4_writer_open().
 {
    VC_CONTAINER_STATUS_T status = VC_CONTAINER_SUCCESS;
    unsigned int length = strlen(context->priv->io->uri) + 5;
    char *uri = malloc(length);
    if(!uri) return VC_CONTAINER_ERROR_OUT_OF_MEMORY;
    snprintf(uri, length, "%s.tmp", context->priv->io->uri);
    status = vc_container_writer_extraio_create(context, uri, extraio);
    free(uri);
    extraio->temp = true;
    if(status == VC_CONTAINER_SUCCESS && !context->priv->tmp_io)
       context->priv->tmp_io = extraio->io;
    return status;
 }
vc_container_writer_extraio_delete()
VC_CONTAINER_STATUS_T vc_container_writer_extraio_delete (VC_CONTAINER_T * context, VC_CONTAINER_WRITER_EXTRAIO_T * extraio)
Definition at line 78 of file containers_writer_utils.c.
 {
    VC_CONTAINER_STATUS_T status;
    char *uri = extraio->temp ? vcos_strdup(extraio->io->uri) : 0;
    while(extraio->refcount) vc_container_writer_extraio_disable(context, extraio);
    status = vc_container_io_close( extraio->io );
    /* coverity[check_return] On failure the worst case is a file or directory is not removed */
    if(uri) remove(uri);
    if(uri) free(uri);
    if(context->priv->tmp_io == extraio->io)
       context->priv->tmp_io = 0;
    return status;
 }
vc_container_writer_extraio_disable()
int64_t vc_container_writer_extraio_disable (VC_CONTAINER_T * context, VC_CONTAINER_WRITER_EXTRAIO_T * extraio)
Definition at line 112 of file containers_writer_utils.c.
 {
    VC_CONTAINER_IO_T *tmp;
    if(extraio->refcount)
    {
       extraio->refcount--;
       if(!extraio->refcount)
       {
          tmp = context->priv->io;
          context->priv->io = extraio->io;
          extraio->io = tmp;
       }
    }
    return extraio->refcount;
 }
vc_container_writer_extraio_enable()
int64_t vc_container_writer_extraio_enable (VC_CONTAINER_T * context, VC_CONTAINER_WRITER_EXTRAIO_T * extraio)
Definition at line 97 of file containers_writer_utils.c.
 {
    VC_CONTAINER_IO_T *tmp;
    if(!extraio->refcount)
    {
       vc_container_io_seek(extraio->io, INT64_C(0));
       tmp = context->priv->io;
       context->priv->io = extraio->io;
       extraio->io = tmp;
    }
    return extraio->refcount++;
 }