VideoCore Library: containers/core/containers_bytestream.h File Reference
containers_bytestream.h File Reference
Classes
struct VC_CONTAINER_BYTESTREAM_T
Typedefs
typedef struct VC_CONTAINER_BYTESTREAM_T VC_CONTAINER_BYTESTREAM_T
Functions
STATIC_INLINE void bytestream_init (VC_CONTAINER_BYTESTREAM_T *stream)
STATIC_INLINE void bytestream_push (VC_CONTAINER_BYTESTREAM_T *stream, VC_CONTAINER_PACKET_T *packet)
STATIC_INLINE VC_CONTAINER_PACKET_T * bytestream_pop (VC_CONTAINER_BYTESTREAM_T *stream)
STATIC_INLINE VC_CONTAINER_PACKET_T * bytestream_get_packet (VC_CONTAINER_BYTESTREAM_T *stream, size_t *offset)
STATIC_INLINE bool bytestream_skip_packet (VC_CONTAINER_BYTESTREAM_T *stream)
STATIC_INLINE void bytestream_get_timestamps (VC_CONTAINER_BYTESTREAM_T *stream, int64_t *pts, int64_t *dts, bool b_same)
STATIC_INLINE void bytestream_get_timestamps_and_offset (VC_CONTAINER_BYTESTREAM_T *stream, int64_t *pts, int64_t *dts, size_t *offset, bool b_same)
STATIC_INLINE size_t bytestream_size (VC_CONTAINER_BYTESTREAM_T *stream)
STATIC_INLINE VC_CONTAINER_STATUS_T bytestream_skip (VC_CONTAINER_BYTESTREAM_T *stream, size_t size)
STATIC_INLINE VC_CONTAINER_STATUS_T bytestream_get (VC_CONTAINER_BYTESTREAM_T *stream, uint8_t *data, size_t size)
STATIC_INLINE VC_CONTAINER_STATUS_T bytestream_peek (VC_CONTAINER_BYTESTREAM_T *stream, uint8_t *data, size_t size)
STATIC_INLINE VC_CONTAINER_STATUS_T bytestream_peek_at (VC_CONTAINER_BYTESTREAM_T *stream, size_t peek_offset, uint8_t *data, size_t size)
STATIC_INLINE VC_CONTAINER_STATUS_T bytestream_skip_byte (VC_CONTAINER_BYTESTREAM_T *stream)
STATIC_INLINE VC_CONTAINER_STATUS_T packet_peek_byte (VC_CONTAINER_BYTESTREAM_T *stream, uint8_t *data)
STATIC_INLINE VC_CONTAINER_STATUS_T packet_get_byte (VC_CONTAINER_BYTESTREAM_T *stream, uint8_t *data)
STATIC_INLINE VC_CONTAINER_STATUS_T bytestream_find_startcode (VC_CONTAINER_BYTESTREAM_T *stream, size_t *search_offset, const uint8_t *startcode, unsigned int length)
Detailed Description
Utility functions to provide a byte stream out of a list of container packets
Definition in file containers_bytestream.h.
Typedef Documentation
VC_CONTAINER_BYTESTREAM_T
typedef struct VC_CONTAINER_BYTESTREAM_T VC_CONTAINER_BYTESTREAM_T
Function Documentation
bytestream_find_startcode()
STATIC_INLINE VC_CONTAINER_STATUS_T bytestream_find_startcode (VC_CONTAINER_BYTESTREAM_T * stream, size_t * search_offset, const uint8_t * startcode, unsigned int length)
Definition at line 329 of file containers_bytestream.h.
References VC_CONTAINER_BYTESTREAM_T::bytes, VC_CONTAINER_BYTESTREAM_T::current, VC_CONTAINER_BYTESTREAM_T::current_offset, VC_CONTAINER_PACKET_T::data, VC_CONTAINER_PACKET_T::next, NULL, VC_CONTAINER_BYTESTREAM_T::offset, VC_CONTAINER_PACKET_T::size, VC_CONTAINER_ERROR_EOS, and VC_CONTAINER_SUCCESS.
 {
    VC_CONTAINER_PACKET_T *packet, *backup_packet = NULL;
    size_t position, start_offset = position = *search_offset;
    size_t offset, backup_offset = 0;
    unsigned int match = 0;
    if( stream->bytes - stream->current_offset - stream->offset < start_offset + length )
       return VC_CONTAINER_ERROR_EOS; /* Not enough data */
    /* Find the right place */
    for( packet = stream->current, offset = stream->offset;
         packet != NULL; packet = packet->next, offset = 0 )
    {
       if( packet->size - offset > start_offset)
          break;
       start_offset -= (packet->size - offset);
    }
    /* Start the search for the start code.
     * To make things simple we try to find a match one byte at a time. */
    for( offset += start_offset;
         packet != NULL; packet = packet->next, offset = 0 )
    {
       for( ; offset < packet->size; offset++ )
       {
          if( packet->data[offset] != startcode[match] )
          {
             if ( match ) /* False positive */
             {
                packet = backup_packet;
                offset = backup_offset;
                match = 0;
             }
             position++;
             continue;
          }
          /* We've got a match */
          if( !match++ )
          {
             backup_packet = packet;
             backup_offset = offset;
          }
          if( match == length )
          {
             /* We have the full start code it */
             *search_offset = position;
             return VC_CONTAINER_SUCCESS;
          }
       }
    }
    *search_offset = position;
    return VC_CONTAINER_ERROR_EOS; /* No luck in finding the start code */
 }
bytestream_get()
STATIC_INLINE VC_CONTAINER_STATUS_T bytestream_get (VC_CONTAINER_BYTESTREAM_T * stream, uint8_t * data, size_t size)
Definition at line 181 of file containers_bytestream.h.
References VC_CONTAINER_BYTESTREAM_T::bytes, VC_CONTAINER_BYTESTREAM_T::current, VC_CONTAINER_BYTESTREAM_T::current_offset, VC_CONTAINER_PACKET_T::data, VC_CONTAINER_PACKET_T::next, VC_CONTAINER_BYTESTREAM_T::offset, VC_CONTAINER_PACKET_T::size, VC_CONTAINER_ERROR_EOS, and VC_CONTAINER_SUCCESS.
Referenced by packet_get_byte().
 {
    VC_CONTAINER_PACKET_T *packet;
    size_t offset, bytes = 0, copy;
    if( !size )
       return VC_CONTAINER_SUCCESS; /* Nothing to do */
    if( stream->bytes - stream->current_offset - stream->offset < size )
       return VC_CONTAINER_ERROR_EOS; /* Not enough data */
    for( packet = stream->current, offset = stream->offset; ;
         packet = packet->next, offset = 0 )
    {
       if( packet->size - offset >= size)
          break;
       copy = packet->size - offset;
       memcpy( data, packet->data + offset, copy );
       bytes += copy;
       data += copy;
       size -= copy;
    }
    memcpy( data, packet->data + offset, size );
    stream->current = packet;
    stream->current_offset += stream->offset - offset + bytes;
    stream->offset = offset + size;
    return VC_CONTAINER_SUCCESS;
 }
bytestream_get_packet()
STATIC_INLINE VC_CONTAINER_PACKET_T* bytestream_get_packet (VC_CONTAINER_BYTESTREAM_T * stream, size_t * offset)
Definition at line 81 of file containers_bytestream.h.
References VC_CONTAINER_BYTESTREAM_T::current, VC_CONTAINER_PACKET_T::next, VC_CONTAINER_BYTESTREAM_T::offset, and VC_CONTAINER_PACKET_T::size.
Referenced by bytestream_get_timestamps(), and bytestream_get_timestamps_and_offset().
 {
    VC_CONTAINER_PACKET_T *packet = stream->current;
    size_t off = stream->offset;
    while(packet && packet->size == off)
    {
       packet = packet->next;
       off = 0;
    }
    if (offset)
       *offset = off;
    return packet;
 }
bytestream_get_timestamps()
STATIC_INLINE void bytestream_get_timestamps (VC_CONTAINER_BYTESTREAM_T * stream, int64_t * pts, int64_t * dts, bool b_same)
Definition at line 112 of file containers_bytestream.h.
References bytestream_get_packet(), VC_CONTAINER_PACKET_T::dts, VC_CONTAINER_PACKET_T::pts, and VC_CONTAINER_TIME_UNKNOWN.
 {
    VC_CONTAINER_PACKET_T *packet = bytestream_get_packet( stream, 0 );
    if(packet)
    {
       if(b_same && packet->pts == VC_CONTAINER_TIME_UNKNOWN) packet->pts = packet->dts;
       if(pts) *pts = packet->pts;
       if(dts) *dts = packet->dts;
       packet->pts = packet->dts = VC_CONTAINER_TIME_UNKNOWN;
       return;
    }
    if(pts) *pts = VC_CONTAINER_TIME_UNKNOWN;
    if(dts) *dts = VC_CONTAINER_TIME_UNKNOWN;
 }
bytestream_get_timestamps_and_offset()
STATIC_INLINE void bytestream_get_timestamps_and_offset (VC_CONTAINER_BYTESTREAM_T * stream, int64_t * pts, int64_t * dts, size_t * offset, bool b_same)
Definition at line 130 of file containers_bytestream.h.
References bytestream_get_packet(), VC_CONTAINER_PACKET_T::dts, VC_CONTAINER_PACKET_T::pts, and VC_CONTAINER_TIME_UNKNOWN.
 {
    VC_CONTAINER_PACKET_T *packet = bytestream_get_packet( stream, offset );
    if(packet)
    {
       if(b_same && packet->pts == VC_CONTAINER_TIME_UNKNOWN) packet->pts = packet->dts;
       if(pts) *pts = packet->pts;
       if(dts) *dts = packet->dts;
       packet->pts = packet->dts = VC_CONTAINER_TIME_UNKNOWN;
       return;
    }
    if(pts) *pts = VC_CONTAINER_TIME_UNKNOWN;
    if(dts) *dts = VC_CONTAINER_TIME_UNKNOWN;
 }
bytestream_init()
STATIC_INLINE void bytestream_init (VC_CONTAINER_BYTESTREAM_T * stream)
Definition at line 48 of file containers_bytestream.h.
References VC_CONTAINER_BYTESTREAM_T::bytes, VC_CONTAINER_BYTESTREAM_T::current, VC_CONTAINER_BYTESTREAM_T::current_offset, VC_CONTAINER_BYTESTREAM_T::first, VC_CONTAINER_BYTESTREAM_T::last, NULL, and VC_CONTAINER_BYTESTREAM_T::offset.
Referenced by vc_packetizer_open().
 {
    stream->first = stream->current = NULL;
    stream->last = &stream->first;
    stream->offset = stream->current_offset = stream->bytes = 0;
 }
bytestream_peek()
STATIC_INLINE VC_CONTAINER_STATUS_T bytestream_peek (VC_CONTAINER_BYTESTREAM_T * stream, uint8_t * data, size_t size)
Definition at line 211 of file containers_bytestream.h.
References VC_CONTAINER_BYTESTREAM_T::bytes, VC_CONTAINER_BYTESTREAM_T::current, VC_CONTAINER_BYTESTREAM_T::current_offset, VC_CONTAINER_PACKET_T::data, VC_CONTAINER_PACKET_T::next, VC_CONTAINER_BYTESTREAM_T::offset, VC_CONTAINER_PACKET_T::size, VC_CONTAINER_ERROR_EOS, and VC_CONTAINER_SUCCESS.
Referenced by packet_peek_byte().
 {
    VC_CONTAINER_PACKET_T *packet;
    size_t offset, copy;
    if( !size )
       return VC_CONTAINER_SUCCESS; /* Nothing to do */
    if( stream->bytes - stream->current_offset - stream->offset < size )
       return VC_CONTAINER_ERROR_EOS; /* Not enough data */
    for( packet = stream->current, offset = stream->offset; ;
         packet = packet->next, offset = 0 )
    {
       if( packet->size - offset >= size)
          break;
       copy = packet->size - offset;
       memcpy( data, packet->data + offset, copy );
       data += copy;
       size -= copy;
    }
    memcpy( data, packet->data + offset, size );
    return VC_CONTAINER_SUCCESS;
 }
bytestream_peek_at()
STATIC_INLINE VC_CONTAINER_STATUS_T bytestream_peek_at (VC_CONTAINER_BYTESTREAM_T * stream, size_t peek_offset, uint8_t * data, size_t size)
Definition at line 237 of file containers_bytestream.h.
References VC_CONTAINER_BYTESTREAM_T::bytes, VC_CONTAINER_BYTESTREAM_T::current, VC_CONTAINER_BYTESTREAM_T::current_offset, VC_CONTAINER_PACKET_T::data, VC_CONTAINER_PACKET_T::next, VC_CONTAINER_BYTESTREAM_T::offset, VC_CONTAINER_PACKET_T::size, VC_CONTAINER_ERROR_EOS, and VC_CONTAINER_SUCCESS.
 {
    VC_CONTAINER_PACKET_T *packet;
    size_t copy;
    if( !size )
       return VC_CONTAINER_SUCCESS; /* Nothing to do */
    if( stream->bytes - stream->current_offset - stream->offset < peek_offset + size )
       return VC_CONTAINER_ERROR_EOS; /* Not enough data */
    peek_offset += stream->offset;
    /* Find the right place */
    for( packet = stream->current; ; packet = packet->next )
    {
       if( packet->size > peek_offset )
          break;
       peek_offset -= packet->size;
    }
    /* Copy the data */
    for( ; ; packet = packet->next, peek_offset = 0 )
    {
       if( packet->size - peek_offset >= size)
          break;
       copy = packet->size - peek_offset;
       memcpy( data, packet->data + peek_offset, copy );
       data += copy;
       size -= copy;
    }
    memcpy( data, packet->data + peek_offset, size );
    return VC_CONTAINER_SUCCESS;
 }
bytestream_pop()
STATIC_INLINE VC_CONTAINER_PACKET_T* bytestream_pop (VC_CONTAINER_BYTESTREAM_T * stream)
Definition at line 65 of file containers_bytestream.h.
References VC_CONTAINER_BYTESTREAM_T::bytes, VC_CONTAINER_BYTESTREAM_T::current, VC_CONTAINER_BYTESTREAM_T::current_offset, VC_CONTAINER_BYTESTREAM_T::first, VC_CONTAINER_BYTESTREAM_T::last, VC_CONTAINER_PACKET_T::next, NULL, VC_CONTAINER_PACKET_T::size, and vc_container_assert.
Referenced by vc_packetizer_pop().
 {
    VC_CONTAINER_PACKET_T *packet = stream->first;
    if( stream->current == packet )
       return NULL;
    vc_container_assert(packet);
    stream->bytes -= packet->size;
    stream->current_offset -= packet->size;
    stream->first = packet->next;
    if( !stream->first )
       stream->last = &stream->first;
    return packet;
 }
bytestream_push()
STATIC_INLINE void bytestream_push (VC_CONTAINER_BYTESTREAM_T * stream, VC_CONTAINER_PACKET_T * packet)
Definition at line 55 of file containers_bytestream.h.
References VC_CONTAINER_BYTESTREAM_T::bytes, VC_CONTAINER_BYTESTREAM_T::current, VC_CONTAINER_BYTESTREAM_T::last, VC_CONTAINER_PACKET_T::next, NULL, and VC_CONTAINER_PACKET_T::size.
Referenced by vc_packetizer_push().
 {
    *stream->last = packet;
    stream->last = &packet->next;
    packet->next = NULL;
    if( !stream->current ) stream->current = packet;
    stream->bytes += packet->size;
 }
bytestream_size()
STATIC_INLINE size_t bytestream_size (VC_CONTAINER_BYTESTREAM_T * stream)
Definition at line 149 of file containers_bytestream.h.
References VC_CONTAINER_BYTESTREAM_T::bytes, VC_CONTAINER_BYTESTREAM_T::current_offset, and VC_CONTAINER_BYTESTREAM_T::offset.
 {
    return stream->bytes - stream->current_offset - stream->offset;
 }
bytestream_skip()
STATIC_INLINE VC_CONTAINER_STATUS_T bytestream_skip (VC_CONTAINER_BYTESTREAM_T * stream, size_t size)
Definition at line 154 of file containers_bytestream.h.
References VC_CONTAINER_BYTESTREAM_T::bytes, VC_CONTAINER_BYTESTREAM_T::current, VC_CONTAINER_BYTESTREAM_T::current_offset, VC_CONTAINER_PACKET_T::next, VC_CONTAINER_BYTESTREAM_T::offset, VC_CONTAINER_PACKET_T::size, VC_CONTAINER_ERROR_EOS, and VC_CONTAINER_SUCCESS.
Referenced by bytestream_skip_byte(), and vc_packetizer_reset().
 {
    VC_CONTAINER_PACKET_T *packet;
    size_t offset, bytes = 0, skip;
    if( !size )
       return VC_CONTAINER_SUCCESS; /* Nothing to do */
    if( stream->bytes - stream->current_offset - stream->offset < size )
       return VC_CONTAINER_ERROR_EOS; /* Not enough data */
    for( packet = stream->current, offset = stream->offset; ;
         packet = packet->next, offset = 0 )
    {
       if( packet->size - offset >= size)
          break;
       skip = packet->size - offset;
       bytes += skip;
       size -= skip;
    }
    stream->current = packet;
    stream->current_offset += stream->offset - offset + bytes;
    stream->offset = offset + size;
    return VC_CONTAINER_SUCCESS;
 }
bytestream_skip_byte()
STATIC_INLINE VC_CONTAINER_STATUS_T bytestream_skip_byte (VC_CONTAINER_BYTESTREAM_T * stream)
Definition at line 275 of file containers_bytestream.h.
References bytestream_skip(), VC_CONTAINER_BYTESTREAM_T::current, VC_CONTAINER_BYTESTREAM_T::offset, VC_CONTAINER_PACKET_T::size, VC_CONTAINER_ERROR_EOS, and VC_CONTAINER_SUCCESS.
 {
    VC_CONTAINER_PACKET_T *packet = stream->current;
    if( !packet )
       return VC_CONTAINER_ERROR_EOS;
    /* Fast path first */
    if( packet->size - stream->offset )
    {
       stream->offset++;
       return VC_CONTAINER_SUCCESS;
    }
    return bytestream_skip( stream, 1 );
 }
bytestream_skip_packet()
STATIC_INLINE bool bytestream_skip_packet (VC_CONTAINER_BYTESTREAM_T * stream)
Definition at line 98 of file containers_bytestream.h.
References VC_CONTAINER_BYTESTREAM_T::current, VC_CONTAINER_BYTESTREAM_T::current_offset, VC_CONTAINER_PACKET_T::next, VC_CONTAINER_BYTESTREAM_T::offset, and VC_CONTAINER_PACKET_T::size.
 {
    VC_CONTAINER_PACKET_T *packet = stream->current;
    if( packet )
    {
       stream->current = packet->next;
       stream->current_offset += (packet->size - stream->offset);
       stream->offset = 0;
    }
    return !!packet;
 }
packet_get_byte()
STATIC_INLINE VC_CONTAINER_STATUS_T packet_get_byte (VC_CONTAINER_BYTESTREAM_T * stream, uint8_t * data)
Definition at line 310 of file containers_bytestream.h.
References bytestream_get(), VC_CONTAINER_BYTESTREAM_T::current, VC_CONTAINER_PACKET_T::data, VC_CONTAINER_BYTESTREAM_T::offset, VC_CONTAINER_PACKET_T::size, VC_CONTAINER_ERROR_EOS, and VC_CONTAINER_SUCCESS.
 {
    VC_CONTAINER_PACKET_T *packet = stream->current;
    if( !packet )
       return VC_CONTAINER_ERROR_EOS;
    /* Fast path first */
    if( packet->size - stream->offset )
    {
       *data = packet->data[stream->offset];
       stream->offset++;
       return VC_CONTAINER_SUCCESS;
    }
    return bytestream_get( stream, data, 1 );
 }
packet_peek_byte()
STATIC_INLINE VC_CONTAINER_STATUS_T packet_peek_byte (VC_CONTAINER_BYTESTREAM_T * stream, uint8_t * data)
Definition at line 292 of file containers_bytestream.h.
References bytestream_peek(), VC_CONTAINER_BYTESTREAM_T::current, VC_CONTAINER_PACKET_T::data, VC_CONTAINER_BYTESTREAM_T::offset, VC_CONTAINER_PACKET_T::size, VC_CONTAINER_ERROR_EOS, and VC_CONTAINER_SUCCESS.
 {
    VC_CONTAINER_PACKET_T *packet = stream->current;
    if( !packet )
       return VC_CONTAINER_ERROR_EOS;
    /* Fast path first */
    if( packet->size - stream->offset )
    {
       *data = packet->data[stream->offset];
       return VC_CONTAINER_SUCCESS;
    }
    return bytestream_peek( stream, data, 1 );
 }