VideoCore Library: interface/vmcs_host/vcfilesys.h File Reference
vcfilesys.h File Reference
#include "vchost_platform_config.h"
#include "vcfilesys_defs.h"
#include "vc_fileservice_defs.h"
Macros
#define FILESYS_DIR_DEFINED
Typedefs
typedef struct DIR_tag DIR
Functions
VCHPRE_ int VCHPOST_ vc_filesys_init (void)
VCHPRE_ void VCHPOST_ vc_filesys_stop (void)
VCHPRE_ int VCHPOST_ vc_filesys_inum (void)
VCHPRE_ int VCHPOST_ vc_filesys_close (int fildes)
VCHPRE_ long VCHPOST_ vc_filesys_lseek (int fildes, long offset, int whence)
VCHPRE_ int64_t VCHPOST_ vc_filesys_lseek64 (int fildes, int64_t offset, int whence)
VCHPRE_ int VCHPOST_ vc_filesys_open (const char *path, int vc_oflag)
VCHPRE_ int VCHPOST_ vc_filesys_read (int fildes, void *buf, unsigned int nbyte)
VCHPRE_ int VCHPOST_ vc_filesys_write (int fildes, const void *buf, unsigned int nbyte)
VCHPRE_ int VCHPOST_ vc_filesys_mount (const char *device, const char *mountpoint, const char *options)
VCHPRE_ int VCHPOST_ vc_filesys_umount (const char *mountpoint)
VCHPRE_ int VCHPOST_ vc_filesys_closedir (void *dhandle)
VCHPRE_ int VCHPOST_ vc_filesys_format (const char *path)
VCHPRE_ int VCHPOST_ vc_filesys_freespace (const char *path)
VCHPRE_ int64_t VCHPOST_ vc_filesys_freespace64 (const char *path)
VCHPRE_ int VCHPOST_ vc_filesys_get_attr (const char *path, fattributes_t *attr)
VCHPRE_ int VCHPOST_ vc_filesys_mkdir (const char *path)
VCHPRE_ void *VCHPOST_ vc_filesys_opendir (const char *dirname)
VCHPRE_ struct dirent *VCHPOST_ vc_filesys_readdir_r (void *dhandle, struct dirent *result)
VCHPRE_ int VCHPOST_ vc_filesys_remove (const char *path)
VCHPRE_ int VCHPOST_ vc_filesys_rename (const char *oldfile, const char *newfile)
VCHPRE_ int VCHPOST_ vc_filesys_reset (void)
VCHPRE_ int VCHPOST_ vc_filesys_set_attr (const char *path, fattributes_t attr)
VCHPRE_ int VCHPOST_ vc_filesys_setend (int fildes)
VCHPRE_ int VCHPOST_ vc_filesys_poll_message_fifo (void)
VCHPRE_ void *VCHPOST_ vc_filesys_read_event (void)
VCHPRE_ void VCHPOST_ vc_filesys_sendreset (void)
VCHPRE_ int VCHPOST_ vc_filesys_errno (void)
VCHPRE_ void VCHPOST_ vc_filesys_scandisk (const char *path)
VCHPRE_ int VCHPOST_ vc_filesys_chkdsk (const char *path, int fix_errors)
VCHPRE_ int VCHPOST_ vc_filesys_diskwritable (const char *path)
VCHPRE_ int VCHPOST_ vc_filesys_fstype (const char *path)
VCHPRE_ int VCHPOST_ vc_filesys_totalspace (const char *path)
VCHPRE_ int64_t VCHPOST_ vc_filesys_totalspace64 (const char *path)
VCHPRE_ int VCHPOST_ vc_filesys_open_disk_raw (const char *path)
VCHPRE_ int VCHPOST_ vc_filesys_close_disk_raw (const char *path)
VCHPRE_ int VCHPOST_ vc_filesys_open_disk (const char *path)
VCHPRE_ int VCHPOST_ vc_filesys_close_disk (const char *path)
VCHPRE_ int VCHPOST_ vc_filesys_numsectors (const char *path)
VCHPRE_ int64_t VCHPOST_ vc_filesys_numsectors64 (const char *path)
VCHPRE_ int VCHPOST_ vc_filesys_read_sectors_begin (const char *path, uint32_t sector, uint32_t count)
VCHPRE_ int VCHPOST_ vc_filesys_read_sector (char *buf)
VCHPRE_ int VCHPOST_ vc_filesys_read_sectors_end (uint32_t *sectors_read)
VCHPRE_ int VCHPOST_ vc_filesys_write_sectors_begin (const char *path, uint32_t sector, uint32_t count)
VCHPRE_ int VCHPOST_ vc_filesys_write_sector (const char *buf)
VCHPRE_ int VCHPOST_ vc_filesys_write_sectors_end (uint32_t *sectors_written)
Macro Definition Documentation
FILESYS_DIR_DEFINED
#define FILESYS_DIR_DEFINED
Definition at line 36 of file vcfilesys.h.
Typedef Documentation
DIR
typedef struct DIR_tag DIR
Definition at line 37 of file vcfilesys.h.
Function Documentation
vc_filesys_chkdsk()
VCHPRE_ int VCHPOST_ vc_filesys_chkdsk (const char * path, int fix_errors)
Definition at line 1352 of file vc_vchi_filesys.c.
 {
    return vc_filesys_single_string(fix_errors, path, VC_FILESYS_CHKDSK, 1);
 }
vc_filesys_close()
VCHPRE_ int VCHPOST_ vc_filesys_close (int fildes)
Definition at line 408 of file vc_vchi_filesys.c.
Referenced by vc_filesys_size().
 {
    return vc_filesys_single_param((uint32_t) fildes, VC_FILESYS_CLOSE);
 }
vc_filesys_close_disk()
VCHPRE_ int VCHPOST_ vc_filesys_close_disk (const char * path)
Definition at line 1561 of file vc_vchi_filesys.c.
 {
    return vc_filesys_single_string(0, path, VC_FILESYS_CLOSE_DISK, 1);
 }
vc_filesys_close_disk_raw()
VCHPRE_ int VCHPOST_ vc_filesys_close_disk_raw (const char * path)
Definition at line 1520 of file vc_vchi_filesys.c.
 {
    return vc_filesys_single_string(0, path, VC_FILESYS_CLOSE_DISK_RAW, 1);
 }
vc_filesys_closedir()
VCHPRE_ int VCHPOST_ vc_filesys_closedir (void * dhandle)
Definition at line 910 of file vc_vchi_filesys.c.
 {
    return vc_filesys_single_param((uint32_t)dhandle, VC_FILESYS_CLOSEDIR);
 }
vc_filesys_diskwritable()
VCHPRE_ int VCHPOST_ vc_filesys_diskwritable (const char * path)
Definition at line 1460 of file vc_vchi_filesys.c.
 {
    return vc_filesys_single_string(0, path, VC_FILESYS_DISKWRITABLE, 1);
 }
vc_filesys_errno()
VCHPRE_ int VCHPOST_ vc_filesys_errno (void)
Definition at line 1756 of file vc_vchi_filesys.c.
References FILESYS_SERVICE_T::err_no.
 {
    return (int) vc_filesys_client.err_no;
 }
vc_filesys_format()
VCHPRE_ int VCHPOST_ vc_filesys_format (const char * path)
Definition at line 931 of file vc_vchi_filesys.c.
 {
    return vc_filesys_single_string(0, path, VC_FILESYS_FORMAT, 0);
 }
vc_filesys_freespace()
VCHPRE_ int VCHPOST_ vc_filesys_freespace (const char * path)
Definition at line 953 of file vc_vchi_filesys.c.
 {
    return vc_filesys_single_string(0, path, VC_FILESYS_FREESPACE, 1);
 }
vc_filesys_freespace64()
VCHPRE_ int64_t VCHPOST_ vc_filesys_freespace64 (const char * path)
Definition at line 975 of file vc_vchi_filesys.c.
 {
    int64_t freespace = -1LL;
    if(lock_obtain() == 0)
    {
       strncpy((char *)vc_filesys_client.fileserv_msg.data, path, FS_MAX_PATH);
       if (vchi_msg_stub(&vc_filesys_client.fileserv_msg, VC_FILESYS_FREESPACE64,
                         (int)(16+strlen((char *)vc_filesys_client.fileserv_msg.data)+1)) == FILESERV_RESP_OK)
       {
          freespace = vc_filesys_client.fileserv_msg.params[0];
          freespace += (int64_t)vc_filesys_client.fileserv_msg.params[1] << 32;
       }
       lock_release();
    }
    return freespace;
 }
vc_filesys_fstype()
VCHPRE_ int VCHPOST_ vc_filesys_fstype (const char * path)
Definition at line 1480 of file vc_vchi_filesys.c.
 {
    return vc_filesys_single_string(0, path, VC_FILESYS_FSTYPE, 1);
 }
vc_filesys_get_attr()
VCHPRE_ int VCHPOST_ vc_filesys_get_attr (const char * path, fattributes_t * attr)
Definition at line 1012 of file vc_vchi_filesys.c.
 {
    int success = -1;
    if(lock_obtain() == 0)
    {
       strncpy((char *)vc_filesys_client.fileserv_msg.data, path, FS_MAX_PATH);
       if (vchi_msg_stub(&vc_filesys_client.fileserv_msg, VC_FILESYS_GET_ATTR,
                         (int)(16+strlen((char *)vc_filesys_client.fileserv_msg.data)+1)) == FILESERV_RESP_OK)
       {
          success = 0;
          *attr = (fattributes_t) vc_filesys_client.fileserv_msg.params[0];
       }
       lock_release();
    }
    return success;
 }
vc_filesys_init()
VCHPRE_ int VCHPOST_ vc_filesys_init (void)
vc_filesys_inum()
VCHPRE_ int VCHPOST_ vc_filesys_inum (void)
vc_filesys_lseek()
VCHPRE_ long VCHPOST_ vc_filesys_lseek (int fildes, long offset, int whence)
Definition at line 429 of file vc_vchi_filesys.c.
Referenced by vc_filesys_size().
 {
    long set = -1;
    if(lock_obtain() == 0)
    {
       vc_filesys_client.fileserv_msg.params[0] = (uint32_t) fildes;
       vc_filesys_client.fileserv_msg.params[1] = (uint32_t) offset;
       vc_filesys_client.fileserv_msg.params[2] = (uint32_t) whence;
       if (vchi_msg_stub(&vc_filesys_client.fileserv_msg, VC_FILESYS_LSEEK, 12) == FILESERV_RESP_OK)
          set = (long) vc_filesys_client.fileserv_msg.params[0];
       lock_release();
    }
    return set;
 }
vc_filesys_lseek64()
VCHPRE_ int64_t VCHPOST_ vc_filesys_lseek64 (int fildes, int64_t offset, int whence)
Definition at line 463 of file vc_vchi_filesys.c.
 {
    int64_t set = -1;
    if(lock_obtain() == 0)
    {
       vc_filesys_client.fileserv_msg.params[0] = (uint32_t) fildes;
       vc_filesys_client.fileserv_msg.params[1] = (uint32_t) offset;        // LSB
       vc_filesys_client.fileserv_msg.params[2] = (uint32_t)(offset >> 32); // MSB
       vc_filesys_client.fileserv_msg.params[3] = (uint32_t) whence;
       if (vchi_msg_stub(&vc_filesys_client.fileserv_msg, VC_FILESYS_LSEEK64, 16) == FILESERV_RESP_OK)
       {
          set = vc_filesys_client.fileserv_msg.params[0];
          set += (int64_t)vc_filesys_client.fileserv_msg.params[1] << 32;
       }
       lock_release();
    }
    return set;
 }
vc_filesys_mkdir()
VCHPRE_ int VCHPOST_ vc_filesys_mkdir (const char * path)
Definition at line 1088 of file vc_vchi_filesys.c.
 {
    return vc_filesys_single_string(0, path, VC_FILESYS_MKDIR, 0);
 }
vc_filesys_mount()
VCHPRE_ int VCHPOST_ vc_filesys_mount (const char * device, const char * mountpoint, const char * options)
Definition at line 500 of file vc_vchi_filesys.c.
 {
    int set = -1, len;
    int a = strlen(device);
    int b = strlen(mountpoint);
    int c = strlen(options);
    if(a + b + c + 3 < FILESERV_MAX_DATA && lock_obtain() == 0)
    {
       char *str = (char *) vc_filesys_client.fileserv_msg.data;
       memcpy(str, device, a);
       str[a] = 0;
       memcpy(str+a+1, mountpoint, b);
       str[a+1+b] = 0;
       memcpy(str+a+b+2, options, c);
       str[a+b+c+2] = 0;
       len = a + b + c + 3 + (int)(((FILESERV_MSG_T *)0)->data);
       len = ((len + (VCHI_BULK_GRANULARITY-1)) & ~(VCHI_BULK_GRANULARITY-1)) + VCHI_BULK_GRANULARITY;
       if (vchi_msg_stub(&vc_filesys_client.fileserv_msg, VC_FILESYS_MOUNT, len) == FILESERV_RESP_OK)
          set = (int) vc_filesys_client.fileserv_msg.params[0];
       lock_release();
    }
    return set;
 }
vc_filesys_numsectors()
VCHPRE_ int VCHPOST_ vc_filesys_numsectors (const char * path)
Definition at line 1581 of file vc_vchi_filesys.c.
 {
    return vc_filesys_single_string(0, path, VC_FILESYS_NUMSECTORS, 1);
 }
vc_filesys_numsectors64()
VCHPRE_ int64_t VCHPOST_ vc_filesys_numsectors64 (const char * path)
vc_filesys_open()
VCHPRE_ int VCHPOST_ vc_filesys_open (const char * path, int vc_oflag)
Definition at line 564 of file vc_vchi_filesys.c.
Referenced by vc_filesys_size().
 {
    return vc_filesys_single_string((uint32_t) vc_oflag, path, VC_FILESYS_OPEN, 1);
 }
vc_filesys_open_disk()
VCHPRE_ int VCHPOST_ vc_filesys_open_disk (const char * path)
Definition at line 1541 of file vc_vchi_filesys.c.
 {
    return vc_filesys_single_string(0, path, VC_FILESYS_OPEN_DISK, 1);
 }
vc_filesys_open_disk_raw()
VCHPRE_ int VCHPOST_ vc_filesys_open_disk_raw (const char * path)
Definition at line 1500 of file vc_vchi_filesys.c.
 {
    return vc_filesys_single_string(0, path, VC_FILESYS_OPEN_DISK_RAW, 1);
 }
vc_filesys_opendir()
VCHPRE_ void* VCHPOST_ vc_filesys_opendir (const char * dirname)
Definition at line 1109 of file vc_vchi_filesys.c.
 {
    return (void *) vc_filesys_single_string(0, dirname, VC_FILESYS_OPENDIR, 1);
 }
vc_filesys_poll_message_fifo()
VCHPRE_ int VCHPOST_ vc_filesys_poll_message_fifo (void)
vc_filesys_read()
VCHPRE_ int VCHPOST_ vc_filesys_read (int fildes, void * buf, unsigned int nbyte)
Definition at line 688 of file vc_vchi_filesys.c.
 {
    int bulk_bytes = 0;
    int actual_read = 0;
    int total_byte = 0;
    uint8_t* ptr = (uint8_t*)buf;
    if (nbyte == 0) {
       return 0;
    }
    if(lock_obtain() == 0)
    {
       do {
          bulk_bytes = nbyte > FILESERV_MAX_BULK ? FILESERV_MAX_BULK : nbyte;
          //we overwrite the response here so fill in data again
          vc_filesys_client.fileserv_msg.params[0] = (uint32_t)fildes;
          vc_filesys_client.fileserv_msg.params[1] = 0xffffffffU;        // offset: use -1 to indicate no offset
          actual_read = vc_vchi_msg_bulk_read(&vc_filesys_client.fileserv_msg , VC_FILESYS_READ, (uint32_t)bulk_bytes, (uint8_t*)ptr);
          if(bulk_bytes != actual_read) {
             if(actual_read < 0)
                total_byte = -1;
             else
                total_byte += actual_read;
             //exit loop
             break;
          }
          ptr+=bulk_bytes;
          nbyte -= actual_read;
          total_byte += actual_read;
       }while(nbyte > 0);
       lock_release();
    }
    return total_byte;
 }
vc_filesys_read_event()
VCHPRE_ void* VCHPOST_ vc_filesys_read_event (void)
vc_filesys_read_sector()
VCHPRE_ int VCHPOST_ vc_filesys_read_sector (char * buf)
vc_filesys_read_sectors_begin()
VCHPRE_ int VCHPOST_ vc_filesys_read_sectors_begin (const char * path, uint32_t sector, uint32_t count)
vc_filesys_read_sectors_end()
VCHPRE_ int VCHPOST_ vc_filesys_read_sectors_end (uint32_t * sectors_read)
vc_filesys_readdir_r()
VCHPRE_ struct dirent* VCHPOST_ vc_filesys_readdir_r (void * dhandle, struct dirent * result)
Definition at line 1176 of file vc_vchi_filesys.c.
References NULL.
 {
    struct dirent *ret = NULL;
    if(lock_obtain() == 0)
    {
       vc_filesys_client.fileserv_msg.params[0] = (uint32_t)dhandle;
       if (vchi_msg_stub(&vc_filesys_client.fileserv_msg, VC_FILESYS_READDIR, 4) == FILESERV_RESP_OK)
       {
          fs_host_direntbytestream_interp(result, (void *)vc_filesys_client.fileserv_msg.data);
          ret = result;
       }
       lock_release();
    }
    return ret;
 }
vc_filesys_remove()
VCHPRE_ int VCHPOST_ vc_filesys_remove (const char * path)
Definition at line 1212 of file vc_vchi_filesys.c.
 {
    return vc_filesys_single_string(0, path, VC_FILESYS_REMOVE, 0);
 }
vc_filesys_rename()
VCHPRE_ int VCHPOST_ vc_filesys_rename (const char * oldfile, const char * newfile)
Definition at line 1234 of file vc_vchi_filesys.c.
References FS_MAX_PATH.
 {
    int a, b, success = -1;
    // Ensure the pathnames aren't too long
    if ((a = strlen(oldfile)) < FS_MAX_PATH && (b = strlen(newfile)) < FS_MAX_PATH && lock_obtain() == 0)
    {
       strncpy((char *)vc_filesys_client.fileserv_msg.data, oldfile, FS_MAX_PATH);
       strncpy((char *)&vc_filesys_client.fileserv_msg.data[a+1], newfile, FS_MAX_PATH);
       if (vchi_msg_stub(&vc_filesys_client.fileserv_msg, VC_FILESYS_RENAME, 16+a+1+b+1) == FILESERV_RESP_OK)
          success = 0;
       lock_release();
    }
    return success;
 }
vc_filesys_reset()
VCHPRE_ int VCHPOST_ vc_filesys_reset (void)
Definition at line 1269 of file vc_vchi_filesys.c.
 {
    return vc_filesys_single_param(0, VC_FILESYS_RESET);
 }
vc_filesys_scandisk()
VCHPRE_ void VCHPOST_ vc_filesys_scandisk (const char * path)
Definition at line 1332 of file vc_vchi_filesys.c.
 {
    vc_filesys_single_string(0, path, VC_FILESYS_SCANDISK, 0);
    return;
 }
vc_filesys_sendreset()
VCHPRE_ void VCHPOST_ vc_filesys_sendreset (void)
Definition at line 2506 of file vc_vchi_filesys.c.
 {
    //TODO
 }
vc_filesys_set_attr()
VCHPRE_ int VCHPOST_ vc_filesys_set_attr (const char * path, fattributes_t attr)
Definition at line 1290 of file vc_vchi_filesys.c.
 {
    return vc_filesys_single_string((uint32_t) attr, path, VC_FILESYS_SET_ATTR, 0);
 }
vc_filesys_setend()
VCHPRE_ int VCHPOST_ vc_filesys_setend (int fildes)
Definition at line 1311 of file vc_vchi_filesys.c.
 {
    return vc_filesys_single_param((uint32_t) fildes, VC_FILESYS_SETEND);
 }
vc_filesys_stop()
VCHPRE_ void VCHPOST_ vc_filesys_stop (void)
Definition at line 301 of file vc_vchi_filesys.c.
 {
    int32_t result;
    void *dummy;
    if(lock_obtain() != 0)
       return;
    result = vchi_service_close(vc_filesys_client.open_handle);
    vcos_assert(result == 0);
    vc_filesys_client.initialised = 0;
    vcos_event_signal(&vc_filesys_client.filesys_msg_avail);
    vcos_thread_join(&vc_filesys_client.filesys_thread, &dummy);
    vcos_event_delete(&vc_filesys_client.filesys_msg_avail);
    vcos_event_delete(&vc_filesys_client.response_event);
    vcos_mutex_delete(&vc_filesys_client.filesys_lock);
    if(vc_filesys_client.bulk_buffer)
       vcos_free(vc_filesys_client.bulk_buffer);
 }
vc_filesys_totalspace()
VCHPRE_ int VCHPOST_ vc_filesys_totalspace (const char * path)
Definition at line 1401 of file vc_vchi_filesys.c.
 {
    return vc_filesys_single_string(0, path, VC_FILESYS_TOTALSPACE, 1);
 }
vc_filesys_totalspace64()
VCHPRE_ int64_t VCHPOST_ vc_filesys_totalspace64 (const char * path)
Definition at line 1423 of file vc_vchi_filesys.c.
 {
    int64_t totalspace = -1LL;
    if(lock_obtain() == 0)
    {
       strncpy((char *)vc_filesys_client.fileserv_msg.data, path, FS_MAX_PATH);
       if (vchi_msg_stub(&vc_filesys_client.fileserv_msg, VC_FILESYS_TOTALSPACE64,
                         (int)(16+strlen((char *)vc_filesys_client.fileserv_msg.data)+1)) == FILESERV_RESP_OK)
       {
          totalspace = vc_filesys_client.fileserv_msg.params[0];
          totalspace += (int64_t)vc_filesys_client.fileserv_msg.params[1] << 32;
       }
       lock_release();
    }
    return totalspace;
 }
vc_filesys_umount()
VCHPRE_ int VCHPOST_ vc_filesys_umount (const char * mountpoint)
Definition at line 544 of file vc_vchi_filesys.c.
 {
    return vc_filesys_single_string(0, mountpoint, VC_FILESYS_UMOUNT, 1);
 }
vc_filesys_write()
VCHPRE_ int VCHPOST_ vc_filesys_write (int fildes, const void * buf, unsigned int nbyte)
Definition at line 849 of file vc_vchi_filesys.c.
 {
    int num_wrt = 0;
    int bulk_bytes = 0;
    int actual_written = 0;
    uint8_t *ptr = (uint8_t*) buf;
    if (nbyte == 0) {
       return 0;
    }
    if(lock_obtain() == 0)
    {
       //will split the read into 4K chunks based on vc fwrite buffer size array size
       //we will make this more dynamic later
       do {
          bulk_bytes = nbyte > FILESERV_MAX_BULK ? FILESERV_MAX_BULK : nbyte;
          //we overwrite the response here so fill in data again
          vc_filesys_client.fileserv_msg.params[0] = (uint32_t)fildes;
          vc_filesys_client.fileserv_msg.params[1] = 0xffffffffU;        // offset: use -1 to indicate no offset
          actual_written = vc_vchi_msg_bulk_write(&vc_filesys_client.fileserv_msg , VC_FILESYS_WRITE, (uint32_t)bulk_bytes, (uint8_t*)ptr);
          if(bulk_bytes != actual_written) {
             if(actual_written < 0)
                num_wrt = -1;
             else
                num_wrt += actual_written;
             break;
          }
          ptr+=bulk_bytes;
          nbyte -= actual_written;
          num_wrt += actual_written;
       }while(nbyte > 0);
       lock_release();
    }
    return num_wrt;
 }
vc_filesys_write_sector()
VCHPRE_ int VCHPOST_ vc_filesys_write_sector (const char * buf)
vc_filesys_write_sectors_begin()
VCHPRE_ int VCHPOST_ vc_filesys_write_sectors_begin (const char * path, uint32_t sector, uint32_t count)
vc_filesys_write_sectors_end()
VCHPRE_ int VCHPOST_ vc_filesys_write_sectors_end (uint32_t * sectors_written)