VideoCore Library: host_applications/linux/apps/raspicam/RaspiPreview.h File Reference
RaspiPreview.h File Reference
Classes
struct RASPIPREVIEW_PARAMETERS
Macros
#define PREVIEW_LAYER 2
Layer that preview window should be displayed on.
#define PREVIEW_FRAME_RATE_NUM 0
#define PREVIEW_FRAME_RATE_DEN 1
#define FULL_RES_PREVIEW_FRAME_RATE_NUM 0
#define FULL_RES_PREVIEW_FRAME_RATE_DEN 1
#define FULL_FOV_PREVIEW_16x9_X 1280
#define FULL_FOV_PREVIEW_16x9_Y 720
#define FULL_FOV_PREVIEW_4x3_X 1296
#define FULL_FOV_PREVIEW_4x3_Y 972
#define FULL_FOV_PREVIEW_FRAME_RATE_NUM 0
#define FULL_FOV_PREVIEW_FRAME_RATE_DEN 1
Functions
MMAL_STATUS_T raspipreview_create (RASPIPREVIEW_PARAMETERS *state)
void raspipreview_destroy (RASPIPREVIEW_PARAMETERS *state)
void raspipreview_set_defaults (RASPIPREVIEW_PARAMETERS *state)
void raspipreview_dump_parameters (RASPIPREVIEW_PARAMETERS *state)
int raspipreview_parse_cmdline (RASPIPREVIEW_PARAMETERS *params, const char *arg1, const char *arg2)
void raspipreview_display_help ()
Macro Definition Documentation
FULL_FOV_PREVIEW_16x9_X
#define FULL_FOV_PREVIEW_16x9_X 1280
Definition at line 42 of file RaspiPreview.h.
FULL_FOV_PREVIEW_16x9_Y
#define FULL_FOV_PREVIEW_16x9_Y 720
Definition at line 43 of file RaspiPreview.h.
FULL_FOV_PREVIEW_4x3_X
#define FULL_FOV_PREVIEW_4x3_X 1296
Definition at line 45 of file RaspiPreview.h.
FULL_FOV_PREVIEW_4x3_Y
#define FULL_FOV_PREVIEW_4x3_Y 972
Definition at line 46 of file RaspiPreview.h.
FULL_FOV_PREVIEW_FRAME_RATE_DEN
#define FULL_FOV_PREVIEW_FRAME_RATE_DEN 1
Definition at line 49 of file RaspiPreview.h.
FULL_FOV_PREVIEW_FRAME_RATE_NUM
#define FULL_FOV_PREVIEW_FRAME_RATE_NUM 0
Definition at line 48 of file RaspiPreview.h.
FULL_RES_PREVIEW_FRAME_RATE_DEN
#define FULL_RES_PREVIEW_FRAME_RATE_DEN 1
Definition at line 40 of file RaspiPreview.h.
FULL_RES_PREVIEW_FRAME_RATE_NUM
#define FULL_RES_PREVIEW_FRAME_RATE_NUM 0
Definition at line 39 of file RaspiPreview.h.
PREVIEW_FRAME_RATE_DEN
#define PREVIEW_FRAME_RATE_DEN 1
Definition at line 37 of file RaspiPreview.h.
PREVIEW_FRAME_RATE_NUM
#define PREVIEW_FRAME_RATE_NUM 0
Definition at line 36 of file RaspiPreview.h.
PREVIEW_LAYER
#define PREVIEW_LAYER 2
Layer that preview window should be displayed on.
Definition at line 33 of file RaspiPreview.h.
Function Documentation
raspipreview_create()
MMAL_STATUS_T raspipreview_create (RASPIPREVIEW_PARAMETERS * state)
Create the preview component, set up its ports
Parameters
state Pointer to state control struct
Returns
MMAL_SUCCESS if all OK, something else otherwise
Definition at line 75 of file RaspiPreview.c.
 {
    MMAL_COMPONENT_T *preview = 0;
    MMAL_PORT_T *preview_port = NULL;
    MMAL_STATUS_T status;
    if (!state->wantPreview)
    {
       // No preview required, so create a null sink component to take its place
       status = mmal_component_create("vc.null_sink", &preview);
       if (status != MMAL_SUCCESS)
       {
          vcos_log_error("Unable to create null sink component");
          goto error;
       }
    }
    else
    {
       status = mmal_component_create(MMAL_COMPONENT_DEFAULT_VIDEO_RENDERER,
                                      &preview);
       if (status != MMAL_SUCCESS)
       {
          vcos_log_error("Unable to create preview component");
          goto error;
       }
       if (!preview->input_num)
       {
          status = MMAL_ENOSYS;
          vcos_log_error("No input ports found on component");
          goto error;
       }
       preview_port = preview->input[0];
       MMAL_DISPLAYREGION_T param;
       param.hdr.id = MMAL_PARAMETER_DISPLAYREGION;
       param.hdr.size = sizeof(MMAL_DISPLAYREGION_T);
       param.set = MMAL_DISPLAY_SET_LAYER;
       param.layer = PREVIEW_LAYER;
       param.set |= MMAL_DISPLAY_SET_ALPHA;
       param.alpha = state->opacity;
       if (state->wantFullScreenPreview)
       {
          param.set |= MMAL_DISPLAY_SET_FULLSCREEN;
          param.fullscreen = 1;
       }
       else
       {
          param.set |= (MMAL_DISPLAY_SET_DEST_RECT | MMAL_DISPLAY_SET_FULLSCREEN);
          param.fullscreen = 0;
          param.dest_rect = state->previewWindow;
       }
       if (state->display_num >= 0)
       {
          param.set |= MMAL_DISPLAY_SET_NUM;
          param.display_num = state->display_num;
       }
       status = mmal_port_parameter_set(preview_port, &param.hdr);
       if (status != MMAL_SUCCESS && status != MMAL_ENOSYS)
       {
          vcos_log_error("unable to set preview port parameters (%u)", status);
          goto error;
       }
    }
    /* Enable component */
    status = mmal_component_enable(preview);
    if (status != MMAL_SUCCESS)
    {
       vcos_log_error("Unable to enable preview/null sink component (%u)", status);
       goto error;
    }
    state->preview_component = preview;
    return status;
 error:
    if (preview)
       mmal_component_destroy(preview);
    return status;
 }
raspipreview_destroy()
void raspipreview_destroy (RASPIPREVIEW_PARAMETERS * state)
Destroy the preview component
Parameters
state Pointer to state control struct
Definition at line 177 of file RaspiPreview.c.
 {
    if (state->preview_component)
    {
       mmal_component_destroy(state->preview_component);
       state->preview_component = NULL;
    }
 }
raspipreview_display_help()
void raspipreview_display_help ()
Display help for command line options
Definition at line 296 of file RaspiPreview.c.
References raspicli_display_help().
Referenced by display_valid_parameters().
 {
    fprintf(stdout, "\nPreview parameter commands\n\n");
    raspicli_display_help(cmdline_commands, cmdline_commands_size);
 }
raspipreview_dump_parameters()
void raspipreview_dump_parameters (RASPIPREVIEW_PARAMETERS * state)
Dump parameters as human readable to stdout
Parameters
state Pointer to parameter block
Definition at line 211 of file RaspiPreview.c.
 {
    fprintf(stderr, "Preview %s, Full screen %s\n", state->wantPreview ? "Yes" : "No",
            state->wantFullScreenPreview ? "Yes" : "No");
    fprintf(stderr, "Preview window %d,%d,%d,%d\nOpacity %d\n", state->previewWindow.x,
            state->previewWindow.y, state->previewWindow.width,
            state->previewWindow.height, state->opacity);
 };
raspipreview_parse_cmdline()
int raspipreview_parse_cmdline (RASPIPREVIEW_PARAMETERS * params, const char * arg1, const char * arg2)
Parse a possible command pair - command and parameter
Parameters
arg1 Command
arg2 Parameter (could be NULL)
Returns
How many parameters were used, 0,1,2
Definition at line 227 of file RaspiPreview.c.
References raspicli_get_command_id(), and used.
 {
    int command_id, used = 0, num_parameters;
    if (!arg1)
       return 0;
    command_id = raspicli_get_command_id(cmdline_commands, cmdline_commands_size, arg1, &num_parameters);
    // If invalid command, or we are missing a parameter, drop out
    if (command_id==-1 || (command_id != -1 && num_parameters > 0 && arg2 == NULL))
       return 0;
    switch (command_id)
    {
    case CommandPreview: // Preview window
    {
       int tmp;
       params->wantPreview = 1;
       tmp = sscanf(arg2, "%d,%d,%d,%d",
                    &params->previewWindow.x, &params->previewWindow.y,
                    &params->previewWindow.width, &params->previewWindow.height);
       // Failed to get any window parameters, so revert to full screen
       if (tmp == 0)
          params->wantFullScreenPreview = 1;
       else
          params->wantFullScreenPreview = 0;
       used = 2;
       break;
    }
    case CommandFullScreen: // Want full screen preview mode (overrides display rect)
       params->wantPreview = 1;
       params->wantFullScreenPreview = 1;
       used = 1;
       break;
    case CommandOpacity: // Define preview window opacity
       if (sscanf(arg2, "%u", &params->opacity) != 1)
          params->opacity = 255;
       else
          used = 2;
       break;
    case CommandDisablePreview: // Turn off preview output
       params->wantPreview = 0;
       used = 1;
       break;
    case CommandDisplayNum:
       if (sscanf(arg2, "%d", &params->display_num) != 1)
          params->display_num = -1;
       else
          used = 2;
       break;
    }
    return used;
 }
raspipreview_set_defaults()
void raspipreview_set_defaults (RASPIPREVIEW_PARAMETERS * state)
Assign set of default parameters to the passed in parameter block
Parameters
state Pointer to parameter block
Definition at line 192 of file RaspiPreview.c.
 {
    state->wantPreview = 1;
    state->wantFullScreenPreview = 1;
    state->opacity = 255;
    state->previewWindow.x = 0;
    state->previewWindow.y = 0;
    state->previewWindow.width = 1024;
    state->previewWindow.height = 768;
    state->preview_component = NULL;
    state->display_num = -1;
 }