VideoCore Library: Queues of buffer headers
Queues of buffer headers
Typedefs
typedef struct MMAL_QUEUE_T MMAL_QUEUE_T
Functions
MMAL_QUEUE_T * mmal_queue_create (void)
void mmal_queue_put (MMAL_QUEUE_T *queue, MMAL_BUFFER_HEADER_T *buffer)
void mmal_queue_put_back (MMAL_QUEUE_T *queue, MMAL_BUFFER_HEADER_T *buffer)
MMAL_BUFFER_HEADER_T * mmal_queue_get (MMAL_QUEUE_T *queue)
MMAL_BUFFER_HEADER_T * mmal_queue_wait (MMAL_QUEUE_T *queue)
MMAL_BUFFER_HEADER_T * mmal_queue_timedwait (MMAL_QUEUE_T *queue, VCOS_UNSIGNED timeout)
unsigned int mmal_queue_length (MMAL_QUEUE_T *queue)
void mmal_queue_destroy (MMAL_QUEUE_T *queue)
Detailed Description
This provides a thread-safe implementation of a queue of buffer headers (MMAL_BUFFER_HEADER_T). The queue works in a first-in, first-out basis so the buffer headers will be dequeued in the order they have been queued.
Typedef Documentation
MMAL_QUEUE_T
typedef struct MMAL_QUEUE_T MMAL_QUEUE_T
Definition at line 43 of file mmal_queue.h.
Function Documentation
mmal_queue_create()
MMAL_QUEUE_T* mmal_queue_create (void)
Create a queue of MMAL_BUFFER_HEADER_T
Returns
Pointer to the newly created queue or NULL on failure.
Create a QUEUE of MMAL_BUFFER_HEADER_T
Definition at line 59 of file mmal_queue.c.
References MMAL_QUEUE_T::first, MMAL_QUEUE_T::last, MMAL_QUEUE_T::length, MMAL_QUEUE_T::lock, mmal_queue_sanity_check, NULL, MMAL_QUEUE_T::semaphore, vcos_free(), vcos_malloc(), vcos_mutex_create(), vcos_mutex_delete(), vcos_mutex_lock(), vcos_mutex_unlock(), vcos_semaphore_create(), and VCOS_SUCCESS.
Referenced by mmal_pool_create_with_allocator(), and raspitex_configure_preview_port().
 {
    MMAL_QUEUE_T *queue;
    queue = vcos_malloc(sizeof(*queue), "MMAL queue");
    if(!queue) return 0;
    if(vcos_mutex_create(&queue->lock, "MMAL queue lock") != VCOS_SUCCESS )
    {
       vcos_free(queue);
       return 0;
    }
    if(vcos_semaphore_create(&queue->semaphore, "MMAL queue sema", 0) != VCOS_SUCCESS )
    {
       vcos_mutex_delete(&queue->lock);
       vcos_free(queue);
       return 0;
    }
    /* gratuitous lock for coverity */ vcos_mutex_lock(&queue->lock);
    queue->length = 0;
    queue->first = 0;
    queue->last = &queue->first;
    mmal_queue_sanity_check(queue, NULL);
    /* gratuitous unlock for coverity */ vcos_mutex_unlock(&queue->lock);
    return queue;
 }
mmal_queue_destroy()
void mmal_queue_destroy (MMAL_QUEUE_T * queue)
Destroy a queue of MMAL_BUFFER_HEADER_T.
Parameters
queue Pointer to a queue
Destroy a queue of MMAL_BUFFER_HEADER_T
Definition at line 192 of file mmal_queue.c.
References MMAL_QUEUE_T::lock, MMAL_QUEUE_T::semaphore, vcos_free(), vcos_mutex_delete(), and vcos_semaphore_delete().
Referenced by mmal_pool_create_with_allocator(), mmal_pool_destroy(), mmal_wrapper_destroy(), OMX_FreeHandle(), raspitex_destroy(), and svp_destroy().
 {
    if(!queue) return;
    vcos_mutex_delete(&queue->lock);
    vcos_semaphore_delete(&queue->semaphore);
    vcos_free(queue);
 }
mmal_queue_get()
MMAL_BUFFER_HEADER_T* mmal_queue_get (MMAL_QUEUE_T * queue)
Get a MMAL_BUFFER_HEADER_T from a queue
Parameters
queue Pointer to a queue
Returns
pointer to the next MMAL_BUFFER_HEADER_T or NULL if the queue is empty.
Get a MMAL_BUFFER_HEADER_T from a QUEUE.
Definition at line 150 of file mmal_queue.c.
References NULL, MMAL_QUEUE_T::semaphore, vcos_assert, vcos_semaphore_trywait(), and VCOS_SUCCESS.
Referenced by mmal_connection_disable(), mmal_pool_resize(), mmal_port_event_get(), mmal_wrapper_buffer_get_empty(), mmal_wrapper_buffer_get_full(), mmal_wrapper_port_disable(), mmalomx_buffer_send(), mmalomx_command_dequeue(), mmalomx_command_queue(), and mmalplay_play().
 {
    vcos_assert(queue);
    if(!queue) return 0;
    if(vcos_semaphore_trywait(&queue->semaphore) != VCOS_SUCCESS)
        return NULL;
    return mmal_queue_get_core(queue);
 }
mmal_queue_length()
unsigned int mmal_queue_length (MMAL_QUEUE_T * queue)
Get the number of MMAL_BUFFER_HEADER_T currently in a queue.
Parameters
queue Pointer to a queue
Returns
length (in elements) of the queue.
Get the number of MMAL_BUFFER_HEADER_T currently in a QUEUE
Definition at line 184 of file mmal_queue.c.
References MMAL_QUEUE_T::length.
Referenced by mmal_connection_disable(), and mmal_wrapper_port_disable().
 {
     if(!queue) return 0;
     return queue->length;
 }
mmal_queue_put()
void mmal_queue_put (MMAL_QUEUE_T * queue, MMAL_BUFFER_HEADER_T * buffer)
Put a MMAL_BUFFER_HEADER_T into a queue
Parameters
queue Pointer to a queue
buffer Pointer to the MMAL_BUFFER_HEADER_T to add to the queue
Put a MMAL_BUFFER_HEADER_T into a QUEUE
Definition at line 90 of file mmal_queue.c.
References MMAL_QUEUE_T::last, MMAL_QUEUE_T::length, MMAL_QUEUE_T::lock, mmal_queue_sanity_check, MMAL_BUFFER_HEADER_T::next, MMAL_QUEUE_T::semaphore, vcos_assert, vcos_mutex_lock(), vcos_mutex_unlock(), and vcos_semaphore_post().
Referenced by mmalomx_command_queue().
 {
    vcos_assert(queue && buffer);
    if(!queue || !buffer) return;
    vcos_mutex_lock(&queue->lock);
    mmal_queue_sanity_check(queue, buffer);
    queue->length++;
    *queue->last = buffer;
    buffer->next = 0;
    queue->last = &buffer->next;
    // There is a possible advantage to putting the semaphore_post outside
    // the lock as that would avoid the case where we set the semaphore, causing
    // a task switch to a waiting get thread which then blocks because we still
    // have the lock.  However this allows a race condition if we have (legit) code
    // of the (simplified) form:
    // if (mmal_queue_length(q) > 0) b = mmal_queue_get(q);
    // where the _get should always succeed
    // This has an easy fix if we have a fn that returns the count in a semaphore
    // but by not all OSs support that (e.g. Win32)
    vcos_semaphore_post(&queue->semaphore);
    vcos_mutex_unlock(&queue->lock);
 }
mmal_queue_put_back()
void mmal_queue_put_back (MMAL_QUEUE_T * queue, MMAL_BUFFER_HEADER_T * buffer)
Put a MMAL_BUFFER_HEADER_T back at the start of a queue. This is used when a buffer header was removed from the queue but not fully processed and needs to be put back where it was originally taken.
Parameters
queue Pointer to a queue
buffer Pointer to the MMAL_BUFFER_HEADER_T to add to the queue
Put a MMAL_BUFFER_HEADER_T back at the start of a QUEUE.
Definition at line 115 of file mmal_queue.c.
References MMAL_QUEUE_T::first, MMAL_QUEUE_T::last, MMAL_QUEUE_T::length, MMAL_QUEUE_T::lock, mmal_queue_sanity_check, MMAL_BUFFER_HEADER_T::next, MMAL_QUEUE_T::semaphore, vcos_mutex_lock(), vcos_mutex_unlock(), and vcos_semaphore_post().
Referenced by mmalomx_buffer_send().
 {
    if(!queue || !buffer) return;
    vcos_mutex_lock(&queue->lock);
    mmal_queue_sanity_check(queue, buffer);
    queue->length++;
    buffer->next = queue->first;
    queue->first = buffer;
    if(queue->last == &queue->first) queue->last = &buffer->next;
    vcos_semaphore_post(&queue->semaphore);
    vcos_mutex_unlock(&queue->lock);
 }
mmal_queue_timedwait()
MMAL_BUFFER_HEADER_T* mmal_queue_timedwait (MMAL_QUEUE_T * queue, VCOS_UNSIGNED timeout)
Wait for a MMAL_BUFFER_HEADER_T from a queue, up to a given timeout. This is the same as a wait, except that it will abort in case of timeout.
Parameters
queue Pointer to a queue
timeout Number of milliseconds to wait before returning if the semaphore can't be acquired.
Returns
pointer to the next MMAL_BUFFER_HEADER_T.
Definition at line 172 of file mmal_queue.c.
References NULL, MMAL_QUEUE_T::semaphore, vcos_semaphore_wait_timeout(), and VCOS_SUCCESS.
 {
     if (!queue)
         return NULL;
     if (vcos_semaphore_wait_timeout(&queue->semaphore, timeout) != VCOS_SUCCESS)
         return NULL;
     return mmal_queue_get_core(queue);
 }
mmal_queue_wait()
MMAL_BUFFER_HEADER_T* mmal_queue_wait (MMAL_QUEUE_T * queue)
Wait for a MMAL_BUFFER_HEADER_T from a queue. This is the same as a get except that this will block until a buffer header is available.
Parameters
queue Pointer to a queue
Returns
pointer to the next MMAL_BUFFER_HEADER_T.
Wait for a MMAL_BUFFER_HEADER_T from a QUEUE.
Definition at line 162 of file mmal_queue.c.
References NULL, MMAL_QUEUE_T::semaphore, vcos_semaphore_wait(), and VCOS_SUCCESS.
 {
     if(!queue) return 0;
    if (vcos_semaphore_wait(&queue->semaphore) != VCOS_SUCCESS)
        return NULL;
    return mmal_queue_get_core(queue);
 }