VideoCore Library: interface/mmal/util/mmal_util_params.h File Reference
mmal_util_params.h File Reference
#include "interface/mmal/mmal.h"
Functions
MMAL_STATUS_T mmal_port_parameter_set_boolean (MMAL_PORT_T *port, uint32_t id, MMAL_BOOL_T value)
MMAL_STATUS_T mmal_port_parameter_get_boolean (MMAL_PORT_T *port, uint32_t id, MMAL_BOOL_T *value)
MMAL_STATUS_T mmal_port_parameter_set_uint64 (MMAL_PORT_T *port, uint32_t id, uint64_t value)
MMAL_STATUS_T mmal_port_parameter_get_uint64 (MMAL_PORT_T *port, uint32_t id, uint64_t *value)
MMAL_STATUS_T mmal_port_parameter_set_int64 (MMAL_PORT_T *port, uint32_t id, int64_t value)
MMAL_STATUS_T mmal_port_parameter_get_int64 (MMAL_PORT_T *port, uint32_t id, int64_t *value)
MMAL_STATUS_T mmal_port_parameter_set_uint32 (MMAL_PORT_T *port, uint32_t id, uint32_t value)
MMAL_STATUS_T mmal_port_parameter_get_uint32 (MMAL_PORT_T *port, uint32_t id, uint32_t *value)
MMAL_STATUS_T mmal_port_parameter_set_int32 (MMAL_PORT_T *port, uint32_t id, int32_t value)
MMAL_STATUS_T mmal_port_parameter_get_int32 (MMAL_PORT_T *port, uint32_t id, int32_t *value)
MMAL_STATUS_T mmal_port_parameter_set_rational (MMAL_PORT_T *port, uint32_t id, MMAL_RATIONAL_T value)
MMAL_STATUS_T mmal_port_parameter_get_rational (MMAL_PORT_T *port, uint32_t id, MMAL_RATIONAL_T *value)
MMAL_STATUS_T mmal_port_parameter_set_string (MMAL_PORT_T *port, uint32_t id, const char *value)
MMAL_STATUS_T mmal_port_parameter_set_bytes (MMAL_PORT_T *port, uint32_t id, const uint8_t *data, unsigned int size)
MMAL_STATUS_T mmal_util_port_set_uri (MMAL_PORT_T *port, const char *uri)
MMAL_STATUS_T mmal_util_set_display_region (MMAL_PORT_T *port, MMAL_DISPLAYREGION_T *region)
MMAL_STATUS_T mmal_util_camera_use_stc_timestamp (MMAL_PORT_T *port, MMAL_CAMERA_STC_MODE_T mode)
MMAL_STATUS_T mmal_util_get_core_port_stats (MMAL_PORT_T *port, MMAL_CORE_STATS_DIR dir, MMAL_BOOL_T reset, MMAL_CORE_STATISTICS_T *stats)
Detailed Description
Utility functions to set some common parameters.
Definition in file mmal_util_params.h.
Function Documentation
mmal_port_parameter_get_boolean()
MMAL_STATUS_T mmal_port_parameter_get_boolean (MMAL_PORT_T * port, uint32_t id, MMAL_BOOL_T * value)
Helper function to get the value of a boolean parameter.
Parameters
port port on which to get the parameter
id parameter id
value pointer to where the value will be returned
Returns
MMAL_SUCCESS or error
Helper function to get the value of a boolean parameter
Definition at line 38 of file mmal_util_params.c.
References MMAL_PARAMETER_BOOLEAN_T::enable, MMAL_PARAMETER_BOOLEAN_T::hdr, mmal_port_parameter_get(), MMAL_SUCCESS, and status.
 {
    MMAL_PARAMETER_BOOLEAN_T param = {{id, sizeof(param)}, 0};
    // coverity[overrun-buffer-val] Structure accessed correctly via size field
    MMAL_STATUS_T status = mmal_port_parameter_get(port, &param.hdr);
    if (status == MMAL_SUCCESS)
       *value = param.enable;
    return status;
 }
mmal_port_parameter_get_int32()
MMAL_STATUS_T mmal_port_parameter_get_int32 (MMAL_PORT_T * port, uint32_t id, int32_t * value)
Helper function to get the value of a 32 bits signed integer parameter.
Parameters
port port on which to get the parameter
id parameter id
value pointer to where the value will be returned
Returns
MMAL_SUCCESS or error
Helper function to get the value of a 32 bits signed integer parameter
Definition at line 110 of file mmal_util_params.c.
References MMAL_PARAMETER_INT32_T::hdr, mmal_port_parameter_get(), MMAL_SUCCESS, status, and MMAL_PARAMETER_INT32_T::value.
 {
    MMAL_PARAMETER_INT32_T param = {{id, sizeof(param)}, 0};
    // coverity[overrun-buffer-val] Structure accessed correctly via size field
    MMAL_STATUS_T status = mmal_port_parameter_get(port, &param.hdr);
    if (status == MMAL_SUCCESS)
       *value = param.value;
    return status;
 }
mmal_port_parameter_get_int64()
MMAL_STATUS_T mmal_port_parameter_get_int64 (MMAL_PORT_T * port, uint32_t id, int64_t * value)
Helper function to get the value of a 64 bits signed integer parameter.
Parameters
port port on which to get the parameter
id parameter id
value pointer to where the value will be returned
Returns
MMAL_SUCCESS or error
Helper function to get the value of a 64 bits signed integer parameter
Definition at line 74 of file mmal_util_params.c.
References MMAL_PARAMETER_INT64_T::hdr, mmal_port_parameter_get(), MMAL_SUCCESS, status, and MMAL_PARAMETER_INT64_T::value.
 {
    MMAL_PARAMETER_INT64_T param = {{id, sizeof(param)}, 0LL};
    // coverity[overrun-buffer-val] Structure accessed correctly via size field
    MMAL_STATUS_T status = mmal_port_parameter_get(port, &param.hdr);
    if (status == MMAL_SUCCESS)
       *value = param.value;
    return status;
 }
mmal_port_parameter_get_rational()
MMAL_STATUS_T mmal_port_parameter_get_rational (MMAL_PORT_T * port, uint32_t id, MMAL_RATIONAL_T * value)
Helper function to get the value of a rational parameter.
Parameters
port port on which to get the parameter
id parameter id
value pointer to where the value will be returned
Returns
MMAL_SUCCESS or error
Helper function to get the value of a rational parameter
Definition at line 128 of file mmal_util_params.c.
References MMAL_PARAMETER_RATIONAL_T::hdr, mmal_port_parameter_get(), MMAL_SUCCESS, status, and MMAL_PARAMETER_RATIONAL_T::value.
 {
    MMAL_PARAMETER_RATIONAL_T param = {{id, sizeof(param)}, {0,0}};
    // coverity[overrun-buffer-val] Structure accessed correctly via size field
    MMAL_STATUS_T status = mmal_port_parameter_get(port, &param.hdr);
    if (status == MMAL_SUCCESS)
       *value = param.value;
    return status;
 }
mmal_port_parameter_get_uint32()
MMAL_STATUS_T mmal_port_parameter_get_uint32 (MMAL_PORT_T * port, uint32_t id, uint32_t * value)
Helper function to get the value of a 32 bits unsigned integer parameter.
Parameters
port port on which to get the parameter
id parameter id
value pointer to where the value will be returned
Returns
MMAL_SUCCESS or error
Helper function to get the value of a 32 bits unsigned integer parameter
Definition at line 92 of file mmal_util_params.c.
References MMAL_PARAMETER_UINT32_T::hdr, mmal_port_parameter_get(), MMAL_SUCCESS, status, and MMAL_PARAMETER_UINT32_T::value.
 {
    MMAL_PARAMETER_UINT32_T param = {{id, sizeof(param)}, 0};
    // coverity[overrun-buffer-val] Structure accessed correctly via size field
    MMAL_STATUS_T status = mmal_port_parameter_get(port, &param.hdr);
    if (status == MMAL_SUCCESS)
       *value = param.value;
    return status;
 }
mmal_port_parameter_get_uint64()
MMAL_STATUS_T mmal_port_parameter_get_uint64 (MMAL_PORT_T * port, uint32_t id, uint64_t * value)
Helper function to get the value of a 64 bits unsigned integer parameter.
Parameters
port port on which to get the parameter
id parameter id
value pointer to where the value will be returned
Returns
MMAL_SUCCESS or error
Helper function to get the value of a 64 bits unsigned integer parameter
Definition at line 56 of file mmal_util_params.c.
References MMAL_PARAMETER_UINT64_T::hdr, mmal_port_parameter_get(), MMAL_SUCCESS, status, and MMAL_PARAMETER_UINT64_T::value.
 {
    MMAL_PARAMETER_UINT64_T param = {{id, sizeof(param)}, 0LL};
    // coverity[overrun-buffer-val] Structure accessed correctly via size field
    MMAL_STATUS_T status = mmal_port_parameter_get(port, &param.hdr);
    if (status == MMAL_SUCCESS)
       *value = param.value;
    return status;
 }
mmal_port_parameter_set_boolean()
MMAL_STATUS_T mmal_port_parameter_set_boolean (MMAL_PORT_T * port, uint32_t id, MMAL_BOOL_T value)
Helper function to set the value of a boolean parameter.
Parameters
port port on which to set the parameter
id parameter id
value value to set the parameter to
Returns
MMAL_SUCCESS or error
Helper function to set the value of a boolean parameter
Definition at line 31 of file mmal_util_params.c.
References MMAL_PARAMETER_BOOLEAN_T::hdr, and mmal_port_parameter_set().
Referenced by mmalplay_play(), raspicamcontrol_set_stats_pass(), raspicamcontrol_set_video_stabilisation(), and raspitex_configure_preview_port().
 {
    MMAL_PARAMETER_BOOLEAN_T param = {{id, sizeof(param)}, value};
    return mmal_port_parameter_set(port, &param.hdr);
 }
mmal_port_parameter_set_bytes()
MMAL_STATUS_T mmal_port_parameter_set_bytes (MMAL_PORT_T * port, uint32_t id, const uint8_t * data, unsigned int size)
Helper function to set the value of an array of bytes parameter.
Parameters
port port on which to set the parameter
id parameter id
data pointer to the array of bytes
size size of the array of bytes
Returns
MMAL_SUCCESS or error
Helper function to set the value of an array of bytes parameter
Definition at line 164 of file mmal_util_params.c.
References MMAL_PARAMETER_BYTES_T::data, MMAL_PARAMETER_BYTES_T::hdr, MMAL_PARAMETER_HEADER_T::id, MMAL_ENOMEM, mmal_port_parameter_set(), MMAL_PARAMETER_HEADER_T::size, and status.
 {
    MMAL_PARAMETER_BYTES_T *param = 0;
    MMAL_STATUS_T status;
    size_t param_size = sizeof(param->hdr) + size;
    param = calloc(1, param_size);
    if (!param)
       return MMAL_ENOMEM;
    param->hdr.id = id;
    param->hdr.size = param_size;
    memcpy(param->data, data, size);
    status = mmal_port_parameter_set(port, &param->hdr);
    free(param);
    return status;
 }
mmal_port_parameter_set_int32()
MMAL_STATUS_T mmal_port_parameter_set_int32 (MMAL_PORT_T * port, uint32_t id, int32_t value)
Helper function to set the value of a 32 bits signed integer parameter.
Parameters
port port on which to set the parameter
id parameter id
value value to set the parameter to
Returns
MMAL_SUCCESS or error
Helper function to set the value of a 32 bits signed integer parameter
Definition at line 103 of file mmal_util_params.c.
References MMAL_PARAMETER_INT32_T::hdr, and mmal_port_parameter_set().
Referenced by raspicamcontrol_set_exposure_compensation(), and raspicamcontrol_set_rotation().
 {
    MMAL_PARAMETER_INT32_T param = {{id, sizeof(param)}, value};
    return mmal_port_parameter_set(port, &param.hdr);
 }
mmal_port_parameter_set_int64()
MMAL_STATUS_T mmal_port_parameter_set_int64 (MMAL_PORT_T * port, uint32_t id, int64_t value)
Helper function to set the value of a 64 bits signed integer parameter.
Parameters
port port on which to set the parameter
id parameter id
value value to set the parameter to
Returns
MMAL_SUCCESS or error
Helper function to set the value of a 64 bits signed integer parameter
Definition at line 67 of file mmal_util_params.c.
References MMAL_PARAMETER_INT64_T::hdr, and mmal_port_parameter_set().
 {
    MMAL_PARAMETER_INT64_T param = {{id, sizeof(param)}, value};
    return mmal_port_parameter_set(port, &param.hdr);
 }
mmal_port_parameter_set_rational()
MMAL_STATUS_T mmal_port_parameter_set_rational (MMAL_PORT_T * port, uint32_t id, MMAL_RATIONAL_T value)
Helper function to set the value of a rational parameter.
Parameters
port port on which to set the parameter
id parameter id
value value to set the parameter to
Returns
MMAL_SUCCESS or error
Helper function to set the value of a rational parameter
Definition at line 121 of file mmal_util_params.c.
References MMAL_RATIONAL_T::den, MMAL_PARAMETER_RATIONAL_T::hdr, mmal_port_parameter_set(), and MMAL_RATIONAL_T::num.
Referenced by raspicamcontrol_set_brightness(), raspicamcontrol_set_contrast(), raspicamcontrol_set_gains(), raspicamcontrol_set_saturation(), and raspicamcontrol_set_sharpness().
 {
    MMAL_PARAMETER_RATIONAL_T param = {{id, sizeof(param)}, {value.num, value.den}};
    return mmal_port_parameter_set(port, &param.hdr);
 }
mmal_port_parameter_set_string()
MMAL_STATUS_T mmal_port_parameter_set_string (MMAL_PORT_T * port, uint32_t id, const char * value)
Helper function to set the value of a string parameter.
Parameters
port port on which to set the parameter
id parameter id
value null-terminated string value
Returns
MMAL_SUCCESS or error
Helper function to set the value of a string parameter
Definition at line 139 of file mmal_util_params.c.
References MMAL_PARAMETER_STRING_T::hdr, MMAL_PARAMETER_HEADER_T::id, MMAL_ENOMEM, mmal_port_parameter_set(), MMAL_PARAMETER_HEADER_T::size, status, and MMAL_PARAMETER_STRING_T::str.
Referenced by mmal_util_port_set_uri().
 {
    MMAL_PARAMETER_STRING_T *param = 0;
    MMAL_STATUS_T status;
    size_t param_size = sizeof(param->hdr) + strlen(value) + 1;
    param = calloc(1, param_size);
    if (!param)
       return MMAL_ENOMEM;
    param->hdr.id = id;
    param->hdr.size = param_size;
    memcpy(param->str, value, strlen(value)+1);
    status = mmal_port_parameter_set(port, &param->hdr);
    free(param);
    return status;
 }
mmal_port_parameter_set_uint32()
MMAL_STATUS_T mmal_port_parameter_set_uint32 (MMAL_PORT_T * port, uint32_t id, uint32_t value)
Helper function to set the value of a 32 bits unsigned integer parameter.
Parameters
port port on which to set the parameter
id parameter id
value value to set the parameter to
Returns
MMAL_SUCCESS or error
Helper function to set the value of a 32 bits unsigned integer parameter
Definition at line 85 of file mmal_util_params.c.
References MMAL_PARAMETER_UINT32_T::hdr, and mmal_port_parameter_set().
Referenced by mmal_encode_test(), raspicamcontrol_set_ISO(), and raspicamcontrol_set_shutter_speed().
 {
    MMAL_PARAMETER_UINT32_T param = {{id, sizeof(param)}, value};
    return mmal_port_parameter_set(port, &param.hdr);
 }
mmal_port_parameter_set_uint64()
MMAL_STATUS_T mmal_port_parameter_set_uint64 (MMAL_PORT_T * port, uint32_t id, uint64_t value)
Helper function to set the value of a 64 bits unsigned integer parameter.
Parameters
port port on which to set the parameter
id parameter id
value value to set the parameter to
Returns
MMAL_SUCCESS or error
Helper function to set the value of a 64 bits unsigned integer parameter
Definition at line 49 of file mmal_util_params.c.
References MMAL_PARAMETER_UINT64_T::hdr, and mmal_port_parameter_set().
 {
    MMAL_PARAMETER_UINT64_T param = {{id, sizeof(param)}, value};
    return mmal_port_parameter_set(port, &param.hdr);
 }
mmal_util_camera_use_stc_timestamp()
MMAL_STATUS_T mmal_util_camera_use_stc_timestamp (MMAL_PORT_T * port, MMAL_CAMERA_STC_MODE_T mode)
Tell the camera to use the STC for timestamps rather than the clock.
Parameters
port port to configure
mode STC mode to use
Returns
MMAL_SUCCESS or error
Definition at line 198 of file mmal_util_params.c.
References MMAL_PARAMETER_CAMERA_STC_MODE_T::hdr, MMAL_PARAMETER_USE_STC, and mmal_port_parameter_set().
 {
    MMAL_PARAMETER_CAMERA_STC_MODE_T param =
       {{MMAL_PARAMETER_USE_STC, sizeof(MMAL_PARAMETER_CAMERA_STC_MODE_T)},mode};
    return mmal_port_parameter_set(port, &param.hdr);
 }
mmal_util_get_core_port_stats()
MMAL_STATUS_T mmal_util_get_core_port_stats (MMAL_PORT_T * port, MMAL_CORE_STATS_DIR dir, MMAL_BOOL_T reset, MMAL_CORE_STATISTICS_T * stats)
Get the MMAL core statistics for a given port.
Parameters
port port to query
dir port direction
reset reset the stats as well
stats filled in with results
Returns
MMAL_SUCCESS or error
Definition at line 205 of file mmal_util_params.c.
References MMAL_PARAMETER_CORE_STATISTICS_T::dir, MMAL_PARAMETER_CORE_STATISTICS_T::hdr, MMAL_PARAMETER_HEADER_T::id, MMAL_PARAMETER_CORE_STATISTICS, mmal_port_parameter_get(), MMAL_SUCCESS, MMAL_PARAMETER_CORE_STATISTICS_T::reset, MMAL_PARAMETER_HEADER_T::size, and MMAL_PARAMETER_CORE_STATISTICS_T::stats.
 {
    MMAL_PARAMETER_CORE_STATISTICS_T param;
    MMAL_STATUS_T ret;
    memset(&param, 0, sizeof(param));
    param.hdr.id = MMAL_PARAMETER_CORE_STATISTICS;
    param.hdr.size = sizeof(param);
    param.dir = dir;
    param.reset = reset;
    // coverity[overrun-buffer-val] Structure accessed correctly via size field
    ret = mmal_port_parameter_get(port, &param.hdr);
    if (ret == MMAL_SUCCESS)
       *stats = param.stats;
    return ret;
 }
mmal_util_port_set_uri()
MMAL_STATUS_T mmal_util_port_set_uri (MMAL_PORT_T * port, const char * uri)
Helper function to set a MMAL_PARAMETER_URI_T parameter on a port.
Parameters
port port on which to set the parameter
uri URI string
Returns
MMAL_SUCCESS or error
Helper function to set a MMAL_PARAMETER_URI_T parameter on a port
Definition at line 158 of file mmal_util_params.c.
References MMAL_PARAMETER_URI, and mmal_port_parameter_set_string().
Referenced by main().
 {
    return mmal_port_parameter_set_string(port, MMAL_PARAMETER_URI, uri);
 }
mmal_util_set_display_region()
MMAL_STATUS_T mmal_util_set_display_region (MMAL_PORT_T * port, MMAL_DISPLAYREGION_T * region)
Set the display region.
Parameters
port port to configure
region region
Returns
MMAL_SUCCESS or error
Definition at line 190 of file mmal_util_params.c.
References MMAL_PARAMETER_DISPLAYREGION, and mmal_port_parameter_set().
 {
    region->hdr.id = MMAL_PARAMETER_DISPLAYREGION;
    region->hdr.size = sizeof(*region);
    return mmal_port_parameter_set(port, &region->hdr);
 }