VideoCore Library: interface/khronos/include/GLES/glext.h File Reference
glext.h File Reference
Macros
#define GL_GLEXT_PROTOTYPES
#define GL_APIENTRYP GL_APIENTRY*
#define GL_BLEND_EQUATION_RGB_OES 0x8009
#define GL_BLEND_EQUATION_ALPHA_OES 0x883D
#define GL_BLEND_DST_RGB_OES 0x80C8
#define GL_BLEND_SRC_RGB_OES 0x80C9
#define GL_BLEND_DST_ALPHA_OES 0x80CA
#define GL_BLEND_SRC_ALPHA_OES 0x80CB
#define GL_BLEND_EQUATION_OES 0x8009
#define GL_FUNC_ADD_OES 0x8006
#define GL_FUNC_SUBTRACT_OES 0x800A
#define GL_FUNC_REVERSE_SUBTRACT_OES 0x800B
#define GL_ETC1_RGB8_OES 0x8D64
#define GL_DEPTH_COMPONENT24_OES 0x81A6
#define GL_DEPTH_COMPONENT32_OES 0x81A7
#define GL_TEXTURE_CROP_RECT_OES 0x8B9D
#define GL_TEXTURE_EXTERNAL_OES 0x8D65
#define GL_TEXTURE_BINDING_EXTERNAL_OES 0x8D67
#define GL_REQUIRED_TEXTURE_IMAGE_UNITS_OES 0x8D68
#define GL_UNSIGNED_INT 0x1405
#define GL_FIXED_OES 0x140C
#define GL_NONE_OES 0
#define GL_FRAMEBUFFER_OES 0x8D40
#define GL_RENDERBUFFER_OES 0x8D41
#define GL_RGBA4_OES 0x8056
#define GL_RGB5_A1_OES 0x8057
#define GL_RGB565_OES 0x8D62
#define GL_DEPTH_COMPONENT16_OES 0x81A5
#define GL_RENDERBUFFER_WIDTH_OES 0x8D42
#define GL_RENDERBUFFER_HEIGHT_OES 0x8D43
#define GL_RENDERBUFFER_INTERNAL_FORMAT_OES 0x8D44
#define GL_RENDERBUFFER_RED_SIZE_OES 0x8D50
#define GL_RENDERBUFFER_GREEN_SIZE_OES 0x8D51
#define GL_RENDERBUFFER_BLUE_SIZE_OES 0x8D52
#define GL_RENDERBUFFER_ALPHA_SIZE_OES 0x8D53
#define GL_RENDERBUFFER_DEPTH_SIZE_OES 0x8D54
#define GL_RENDERBUFFER_STENCIL_SIZE_OES 0x8D55
#define GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE_OES 0x8CD0
#define GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME_OES 0x8CD1
#define GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL_OES 0x8CD2
#define GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE_OES 0x8CD3
#define GL_COLOR_ATTACHMENT0_OES 0x8CE0
#define GL_DEPTH_ATTACHMENT_OES 0x8D00
#define GL_STENCIL_ATTACHMENT_OES 0x8D20
#define GL_FRAMEBUFFER_COMPLETE_OES 0x8CD5
#define GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT_OES 0x8CD6
#define GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT_OES 0x8CD7
#define GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS_OES 0x8CD9
#define GL_FRAMEBUFFER_INCOMPLETE_FORMATS_OES 0x8CDA
#define GL_FRAMEBUFFER_UNSUPPORTED_OES 0x8CDD
#define GL_FRAMEBUFFER_BINDING_OES 0x8CA6
#define GL_RENDERBUFFER_BINDING_OES 0x8CA7
#define GL_MAX_RENDERBUFFER_SIZE_OES 0x84E8
#define GL_INVALID_FRAMEBUFFER_OPERATION_OES 0x0506
#define GL_WRITE_ONLY_OES 0x88B9
#define GL_BUFFER_ACCESS_OES 0x88BB
#define GL_BUFFER_MAPPED_OES 0x88BC
#define GL_BUFFER_MAP_POINTER_OES 0x88BD
#define GL_MODELVIEW_MATRIX_FLOAT_AS_INT_BITS_OES 0x898D
#define GL_PROJECTION_MATRIX_FLOAT_AS_INT_BITS_OES 0x898E
#define GL_TEXTURE_MATRIX_FLOAT_AS_INT_BITS_OES 0x898F
#define GL_MAX_VERTEX_UNITS_OES 0x86A4
#define GL_MAX_PALETTE_MATRICES_OES 0x8842
#define GL_MATRIX_PALETTE_OES 0x8840
#define GL_MATRIX_INDEX_ARRAY_OES 0x8844
#define GL_WEIGHT_ARRAY_OES 0x86AD
#define GL_CURRENT_PALETTE_MATRIX_OES 0x8843
#define GL_MATRIX_INDEX_ARRAY_SIZE_OES 0x8846
#define GL_MATRIX_INDEX_ARRAY_TYPE_OES 0x8847
#define GL_MATRIX_INDEX_ARRAY_STRIDE_OES 0x8848
#define GL_MATRIX_INDEX_ARRAY_POINTER_OES 0x8849
#define GL_MATRIX_INDEX_ARRAY_BUFFER_BINDING_OES 0x8B9E
#define GL_WEIGHT_ARRAY_SIZE_OES 0x86AB
#define GL_WEIGHT_ARRAY_TYPE_OES 0x86A9
#define GL_WEIGHT_ARRAY_STRIDE_OES 0x86AA
#define GL_WEIGHT_ARRAY_POINTER_OES 0x86AC
#define GL_WEIGHT_ARRAY_BUFFER_BINDING_OES 0x889E
#define GL_DEPTH_STENCIL_OES 0x84F9
#define GL_UNSIGNED_INT_24_8_OES 0x84FA
#define GL_DEPTH24_STENCIL8_OES 0x88F0
#define GL_RGB8_OES 0x8051
#define GL_RGBA8_OES 0x8058
#define GL_STENCIL_INDEX1_OES 0x8D46
#define GL_STENCIL_INDEX4_OES 0x8D47
#define GL_STENCIL_INDEX8_OES 0x8D48
#define GL_INCR_WRAP_OES 0x8507
#define GL_DECR_WRAP_OES 0x8508
#define GL_NORMAL_MAP_OES 0x8511
#define GL_REFLECTION_MAP_OES 0x8512
#define GL_TEXTURE_CUBE_MAP_OES 0x8513
#define GL_TEXTURE_BINDING_CUBE_MAP_OES 0x8514
#define GL_TEXTURE_CUBE_MAP_POSITIVE_X_OES 0x8515
#define GL_TEXTURE_CUBE_MAP_NEGATIVE_X_OES 0x8516
#define GL_TEXTURE_CUBE_MAP_POSITIVE_Y_OES 0x8517
#define GL_TEXTURE_CUBE_MAP_NEGATIVE_Y_OES 0x8518
#define GL_TEXTURE_CUBE_MAP_POSITIVE_Z_OES 0x8519
#define GL_TEXTURE_CUBE_MAP_NEGATIVE_Z_OES 0x851A
#define GL_MAX_CUBE_MAP_TEXTURE_SIZE_OES 0x851C
#define GL_TEXTURE_GEN_MODE_OES 0x2500
#define GL_TEXTURE_GEN_STR_OES 0x8D60
#define GL_MIRRORED_REPEAT_OES 0x8370
#define GL_VERTEX_ARRAY_BINDING_OES 0x85B5
#define GL_3DC_X_AMD 0x87F9
#define GL_3DC_XY_AMD 0x87FA
#define GL_ATC_RGB_AMD 0x8C92
#define GL_ATC_RGBA_EXPLICIT_ALPHA_AMD 0x8C93
#define GL_ATC_RGBA_INTERPOLATED_ALPHA_AMD 0x87EE
#define GL_RENDERBUFFER_SAMPLES_APPLE 0x8CAB
#define GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE_APPLE 0x8D56
#define GL_MAX_SAMPLES_APPLE 0x8D57
#define GL_READ_FRAMEBUFFER_APPLE 0x8CA8
#define GL_DRAW_FRAMEBUFFER_APPLE 0x8CA9
#define GL_DRAW_FRAMEBUFFER_BINDING_APPLE 0x8CA6
#define GL_READ_FRAMEBUFFER_BINDING_APPLE 0x8CAA
#define GL_BGRA_EXT 0x80E1
#define GL_TEXTURE_MAX_LEVEL_APPLE 0x813D
#define GL_APPLE_rgb_422 1
#define GL_RGB_422_APPLE 0x8A1F
#define GL_UNSIGNED_SHORT_8_8_APPLE 0x85BA
#define GL_UNSIGNED_SHORT_8_8_REV_APPLE 0x85BB
#define GL_MIN_EXT 0x8007
#define GL_MAX_EXT 0x8008
#define GL_COLOR_EXT 0x1800
#define GL_DEPTH_EXT 0x1801
#define GL_STENCIL_EXT 0x1802
#define GL_BGRA_EXT 0x80E1
#define GL_UNSIGNED_SHORT_4_4_4_4_REV_EXT 0x8365
#define GL_UNSIGNED_SHORT_1_5_5_5_REV_EXT 0x8366
#define GL_TEXTURE_MAX_ANISOTROPY_EXT 0x84FE
#define GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT 0x84FF
#define GL_BGRA_EXT 0x80E1
#define GL_RGBX_BRCM 0x80EE
#define GL_MAX_TEXTURE_LOD_BIAS_EXT 0x84FD
#define GL_TEXTURE_FILTER_CONTROL_EXT 0x8500
#define GL_TEXTURE_LOD_BIAS_EXT 0x8501
#define GL_BGRA_IMG 0x80E1
#define GL_UNSIGNED_SHORT_4_4_4_4_REV_IMG 0x8365
#define GL_COMPRESSED_RGB_PVRTC_4BPPV1_IMG 0x8C00
#define GL_COMPRESSED_RGB_PVRTC_2BPPV1_IMG 0x8C01
#define GL_COMPRESSED_RGBA_PVRTC_4BPPV1_IMG 0x8C02
#define GL_COMPRESSED_RGBA_PVRTC_2BPPV1_IMG 0x8C03
#define GL_MODULATE_COLOR_IMG 0x8C04
#define GL_RECIP_ADD_SIGNED_ALPHA_IMG 0x8C05
#define GL_TEXTURE_ALPHA_MODULATE_IMG 0x8C06
#define GL_FACTOR_ALPHA_MODULATE_IMG 0x8C07
#define GL_FRAGMENT_ALPHA_MODULATE_IMG 0x8C08
#define GL_ADD_BLEND_IMG 0x8C09
#define GL_DOT3_RGBA_IMG 0x86AF
#define GL_CLIP_PLANE0_IMG 0x3000
#define GL_CLIP_PLANE1_IMG 0x3001
#define GL_CLIP_PLANE2_IMG 0x3002
#define GL_CLIP_PLANE3_IMG 0x3003
#define GL_CLIP_PLANE4_IMG 0x3004
#define GL_CLIP_PLANE5_IMG 0x3005
#define GL_MAX_CLIP_PLANES_IMG 0x0D32
#define GL_RENDERBUFFER_SAMPLES_IMG 0x9133
#define GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE_IMG 0x9134
#define GL_MAX_SAMPLES_IMG 0x9135
#define GL_TEXTURE_SAMPLES_IMG 0x9136
#define GL_ALL_COMPLETED_NV 0x84F2
#define GL_FENCE_STATUS_NV 0x84F3
#define GL_FENCE_CONDITION_NV 0x84F4
#define GL_TEXTURE_WIDTH_QCOM 0x8BD2
#define GL_TEXTURE_HEIGHT_QCOM 0x8BD3
#define GL_TEXTURE_DEPTH_QCOM 0x8BD4
#define GL_TEXTURE_INTERNAL_FORMAT_QCOM 0x8BD5
#define GL_TEXTURE_FORMAT_QCOM 0x8BD6
#define GL_TEXTURE_TYPE_QCOM 0x8BD7
#define GL_TEXTURE_IMAGE_VALID_QCOM 0x8BD8
#define GL_TEXTURE_NUM_LEVELS_QCOM 0x8BD9
#define GL_TEXTURE_TARGET_QCOM 0x8BDA
#define GL_TEXTURE_OBJECT_VALID_QCOM 0x8BDB
#define GL_STATE_RESTORE 0x8BDC
#define GL_PERFMON_GLOBAL_MODE_QCOM 0x8FA0
#define GL_WRITEONLY_RENDERING_QCOM 0x8823
#define GL_COLOR_BUFFER_BIT0_QCOM 0x00000001
#define GL_COLOR_BUFFER_BIT1_QCOM 0x00000002
#define GL_COLOR_BUFFER_BIT2_QCOM 0x00000004
#define GL_COLOR_BUFFER_BIT3_QCOM 0x00000008
#define GL_COLOR_BUFFER_BIT4_QCOM 0x00000010
#define GL_COLOR_BUFFER_BIT5_QCOM 0x00000020
#define GL_COLOR_BUFFER_BIT6_QCOM 0x00000040
#define GL_COLOR_BUFFER_BIT7_QCOM 0x00000080
#define GL_DEPTH_BUFFER_BIT0_QCOM 0x00000100
#define GL_DEPTH_BUFFER_BIT1_QCOM 0x00000200
#define GL_DEPTH_BUFFER_BIT2_QCOM 0x00000400
#define GL_DEPTH_BUFFER_BIT3_QCOM 0x00000800
#define GL_DEPTH_BUFFER_BIT4_QCOM 0x00001000
#define GL_DEPTH_BUFFER_BIT5_QCOM 0x00002000
#define GL_DEPTH_BUFFER_BIT6_QCOM 0x00004000
#define GL_DEPTH_BUFFER_BIT7_QCOM 0x00008000
#define GL_STENCIL_BUFFER_BIT0_QCOM 0x00010000
#define GL_STENCIL_BUFFER_BIT1_QCOM 0x00020000
#define GL_STENCIL_BUFFER_BIT2_QCOM 0x00040000
#define GL_STENCIL_BUFFER_BIT3_QCOM 0x00080000
#define GL_STENCIL_BUFFER_BIT4_QCOM 0x00100000
#define GL_STENCIL_BUFFER_BIT5_QCOM 0x00200000
#define GL_STENCIL_BUFFER_BIT6_QCOM 0x00400000
#define GL_STENCIL_BUFFER_BIT7_QCOM 0x00800000
#define GL_MULTISAMPLE_BUFFER_BIT0_QCOM 0x01000000
#define GL_MULTISAMPLE_BUFFER_BIT1_QCOM 0x02000000
#define GL_MULTISAMPLE_BUFFER_BIT2_QCOM 0x04000000
#define GL_MULTISAMPLE_BUFFER_BIT3_QCOM 0x08000000
#define GL_MULTISAMPLE_BUFFER_BIT4_QCOM 0x10000000
#define GL_MULTISAMPLE_BUFFER_BIT5_QCOM 0x20000000
#define GL_MULTISAMPLE_BUFFER_BIT6_QCOM 0x40000000
#define GL_MULTISAMPLE_BUFFER_BIT7_QCOM 0x80000000
#define GL_SIDE_BY_SIDE_STEREO_HINT_BRCM 0x8193 /* GET AN OFFICIAL ENUM */
#define GL_OES_blend_equation_separate 0
#define GL_OES_blend_func_separate 0
#define GL_OES_blend_subtract 0
#define GL_OES_byte_coordinates 0
#define GL_OES_compressed_ETC1_RGB8_texture 1
#define GL_OES_depth24 0
#define GL_OES_depth32 0
#define GL_OES_draw_texture 1
#define GL_OES_EGL_image 1
#define GL_OES_EGL_image_external 1
#define GL_OES_element_index_uint 0
#define GL_OES_extended_matrix_palette 0
#define GL_OES_fbo_render_mipmap 0
#define GL_OES_fixed_point 0
#define GL_OES_framebuffer_object 1
#define GL_OES_mapbuffer 1
#define GL_OES_matrix_get 0
#define GL_OES_matrix_palette 1
#define GL_OES_packed_depth_stencil 0
#define GL_OES_query_matrix 1
#define GL_OES_rgb8_rgba8 1
#define GL_OES_single_precision 0
#define GL_OES_stencil1 0
#define GL_OES_stencil4 0
#define GL_OES_stencil8 1
#define GL_OES_stencil_wrap 0
#define GL_OES_texture_cube_map 0
#define GL_OES_texture_env_crossbar 0
#define GL_OES_texture_mirrored_repeat 0
#define GL_OES_vertex_array_object 0
#define GL_AMD_compressed_3DC_texture 0
#define GL_AMD_compressed_ATC_texture 0
#define GL_APPLE_texture_2D_limited_npot 0
#define GL_APPLE_framebuffer_multisample 0
#define GL_APPLE_texture_format_BGRA8888 0
#define GL_APPLE_texture_max_level 0
#define GL_ARM_rgba8 0
#define GL_EXT_blend_minmax 0
#define GL_EXT_discard_framebuffer 0
#define GL_EXT_debug_marker 1
#define GL_EXT_multi_draw_arrays 0
#define GL_EXT_read_format_bgra 0
#define GL_EXT_texture_filter_anisotropic 0
#define GL_EXT_texture_format_BGRA8888 1
#define GL_texture_format_RGBX8888_BRCM 1
#define GL_EXT_texture_lod_bias 0
#define GL_IMG_read_format 0
#define GL_IMG_texture_compression_pvrtc 0
#define GL_IMG_texture_env_enhanced_fixed_function 0
#define GL_IMG_user_clip_plane 0
#define GL_IMG_multisampled_render_to_texture 0
#define GL_NV_fence 0
#define GL_QCOM_driver_control 0
#define GL_QCOM_extended_get 0
#define GL_QCOM_extended_get2 0
#define GL_QCOM_perfmon_global_mode 0
#define GL_QCOM_writeonly_rendering 0
#define GL_QCOM_tiled_rendering 0
#define GL_BRCM_side_by_side_stero_hint 1
Typedefs
typedef void * GLeglImageOES
typedef GLenum modeAlpha
typedef GLenum dstRGB
typedef GLenum GLenum srcAlpha
typedef GLenum GLenum GLenum dstAlpha
typedef GLshort y
typedef GLshort GLshort z
typedef GLshort GLshort GLshort width
typedef GLshort GLshort GLshort GLshort height
typedef GLeglImageOES image
typedef GLclampx ref
typedef GLclampx green
typedef GLclampx GLclampx blue
typedef GLclampx GLclampx GLclampx alpha
typedef const GLfixed * equation
typedef GLclampx zFar
typedef GLfixed param
typedef const GLfixed * params
typedef GLfixed right
typedef GLfixed GLfixed bottom
typedef GLfixed GLfixed GLfixed top
typedef GLfixed GLfixed GLfixed GLfixed zNear
typedef GLfixed eqn[4]
typedef GLenum pname
typedef GLfixed s
typedef GLfixed GLfixed t
typedef GLfixed GLfixed GLfixed r
typedef GLfixed GLfixed GLfixed GLfixed q
typedef GLfixed ny
typedef GLfixed GLfixed nz
typedef GLfixed units
typedef GLfixed x
typedef GLboolean invert
typedef GLuint renderbuffer
typedef const GLuint * renderbuffers
typedef GLenum internalformat
typedef GLuint framebuffer
typedef const GLuint * framebuffers
typedef GLenum attachment
typedef GLenum GLenum renderbuffertarget
typedef GLenum GLenum textarget
typedef GLenum GLenum GLuint texture
typedef GLenum GLenum GLuint GLint level
typedef void *GL_APIENTRYP PFNGLMAPBUFFEROESPROC(GLenum target, GLenum access)
typedef GLenum type
typedef GLenum GLsizei stride
typedef GLenum GLsizei const GLvoid * pointer
typedef GLint exponent[16]
typedef const GLuint * arrays
typedef GLsizei samples
typedef GLsizei numAttachments
typedef GLsizei const GLenum * attachments
typedef const GLchar * marker
typedef GLint * first
typedef GLint GLsizei * count
typedef GLint GLsizei GLsizei primcount
typedef const GLsizei GLenum const GLvoid ** indices
typedef const GLuint * fences
typedef GLenum condition
typedef GLsizei size
typedef GLsizei GLuint * driverControls
typedef GLsizei bufSize
typedef GLsizei GLsizei * length
typedef GLsizei GLsizei GLchar * driverControlString
typedef GLint maxTextures
typedef GLint GLint * numTextures
typedef GLint maxBuffers
typedef GLint GLint * numBuffers
typedef GLint maxRenderbuffers
typedef GLint GLint * numRenderbuffers
typedef GLint maxFramebuffers
typedef GLint GLint * numFramebuffers
typedef GLenum face
typedef GLint GLint xoffset
typedef GLint GLint GLint yoffset
typedef GLint GLint GLint GLint zoffset
typedef GLint GLint GLint GLint GLsizei GLsizei GLsizei depth
typedef GLint GLint GLint GLint GLsizei GLsizei GLsizei GLenum format
typedef GLint GLint GLint GLint GLsizei GLsizei GLsizei GLenum GLenum GLvoid * texels
typedef GLint maxShaders
typedef GLint GLint * numShaders
typedef GLint maxPrograms
typedef GLint GLint * numPrograms
typedef GLenum shadertype
typedef GLenum GLchar * source
typedef GLuint GLuint GLuint GLbitfield preserveMask
Functions
GL_API void GL_APIENTRY glBlendEquationSeparateOES (GLenum modeRGB, GLenum modeAlpha)
typedef void (GL_APIENTRYP PFNGLBLENDEQUATIONSEPARATEOESPROC)(GLenum modeRGB
GL_API void GL_APIENTRY glBlendFuncSeparateOES (GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha)
GL_API void GL_APIENTRY glBlendEquationOES (GLenum mode)
GL_API void GL_APIENTRY glDrawTexsOES (GLshort x, GLshort y, GLshort z, GLshort width, GLshort height)
GL_API void GL_APIENTRY glDrawTexiOES (GLint x, GLint y, GLint z, GLint width, GLint height)
GL_API void GL_APIENTRY glDrawTexxOES (GLfixed x, GLfixed y, GLfixed z, GLfixed width, GLfixed height)
GL_API void GL_APIENTRY glDrawTexsvOES (const GLshort *coords)
GL_API void GL_APIENTRY glDrawTexivOES (const GLint *coords)
GL_API void GL_APIENTRY glDrawTexxvOES (const GLfixed *coords)
GL_API void GL_APIENTRY glDrawTexfOES (GLfloat x, GLfloat y, GLfloat z, GLfloat width, GLfloat height)
GL_API void GL_APIENTRY glDrawTexfvOES (const GLfloat *coords)
GL_API void GL_APIENTRY glEGLImageTargetTexture2DOES (GLenum target, GLeglImageOES image)
GL_API void GL_APIENTRY glEGLImageTargetRenderbufferStorageOES (GLenum target, GLeglImageOES image)
GL_API void GL_APIENTRY glAlphaFuncxOES (GLenum func, GLclampx ref)
GL_API void GL_APIENTRY glClearColorxOES (GLclampx red, GLclampx green, GLclampx blue, GLclampx alpha)
GL_API void GL_APIENTRY glClearDepthxOES (GLclampx depth)
GL_API void GL_APIENTRY glClipPlanexOES (GLenum plane, const GLfixed *equation)
GL_API void GL_APIENTRY glColor4xOES (GLfixed red, GLfixed green, GLfixed blue, GLfixed alpha)
GL_API void GL_APIENTRY glDepthRangexOES (GLclampx zNear, GLclampx zFar)
GL_API void GL_APIENTRY glFogxOES (GLenum pname, GLfixed param)
GL_API void GL_APIENTRY glFogxvOES (GLenum pname, const GLfixed *params)
GL_API void GL_APIENTRY glFrustumxOES (GLfixed left, GLfixed right, GLfixed bottom, GLfixed top, GLfixed zNear, GLfixed zFar)
GL_API void GL_APIENTRY glGetClipPlanexOES (GLenum pname, GLfixed eqn[4])
GL_API void GL_APIENTRY glGetFixedvOES (GLenum pname, GLfixed *params)
GL_API void GL_APIENTRY glGetLightxvOES (GLenum light, GLenum pname, GLfixed *params)
GL_API void GL_APIENTRY glGetMaterialxvOES (GLenum face, GLenum pname, GLfixed *params)
GL_API void GL_APIENTRY glGetTexEnvxvOES (GLenum env, GLenum pname, GLfixed *params)
GL_API void GL_APIENTRY glGetTexParameterxvOES (GLenum target, GLenum pname, GLfixed *params)
GL_API void GL_APIENTRY glLightModelxOES (GLenum pname, GLfixed param)
GL_API void GL_APIENTRY glLightModelxvOES (GLenum pname, const GLfixed *params)
GL_API void GL_APIENTRY glLightxOES (GLenum light, GLenum pname, GLfixed param)
GL_API void GL_APIENTRY glLightxvOES (GLenum light, GLenum pname, const GLfixed *params)
GL_API void GL_APIENTRY glLineWidthxOES (GLfixed width)
GL_API void GL_APIENTRY glLoadMatrixxOES (const GLfixed *m)
GL_API void GL_APIENTRY glMaterialxOES (GLenum face, GLenum pname, GLfixed param)
GL_API void GL_APIENTRY glMaterialxvOES (GLenum face, GLenum pname, const GLfixed *params)
GL_API void GL_APIENTRY glMultMatrixxOES (const GLfixed *m)
GL_API void GL_APIENTRY glMultiTexCoord4xOES (GLenum target, GLfixed s, GLfixed t, GLfixed r, GLfixed q)
GL_API void GL_APIENTRY glNormal3xOES (GLfixed nx, GLfixed ny, GLfixed nz)
GL_API void GL_APIENTRY glOrthoxOES (GLfixed left, GLfixed right, GLfixed bottom, GLfixed top, GLfixed zNear, GLfixed zFar)
GL_API void GL_APIENTRY glPointParameterxOES (GLenum pname, GLfixed param)
GL_API void GL_APIENTRY glPointParameterxvOES (GLenum pname, const GLfixed *params)
GL_API void GL_APIENTRY glPointSizexOES (GLfixed size)
GL_API void GL_APIENTRY glPolygonOffsetxOES (GLfixed factor, GLfixed units)
GL_API void GL_APIENTRY glRotatexOES (GLfixed angle, GLfixed x, GLfixed y, GLfixed z)
GL_API void GL_APIENTRY glSampleCoveragexOES (GLclampx value, GLboolean invert)
GL_API void GL_APIENTRY glScalexOES (GLfixed x, GLfixed y, GLfixed z)
GL_API void GL_APIENTRY glTexEnvxOES (GLenum target, GLenum pname, GLfixed param)
GL_API void GL_APIENTRY glTexEnvxvOES (GLenum target, GLenum pname, const GLfixed *params)
GL_API void GL_APIENTRY glTexParameterxOES (GLenum target, GLenum pname, GLfixed param)
GL_API void GL_APIENTRY glTexParameterxvOES (GLenum target, GLenum pname, const GLfixed *params)
GL_API void GL_APIENTRY glTranslatexOES (GLfixed x, GLfixed y, GLfixed z)
GL_API GLboolean GL_APIENTRY glIsRenderbufferOES (GLuint renderbuffer)
GL_API void GL_APIENTRY glBindRenderbufferOES (GLenum target, GLuint renderbuffer)
GL_API void GL_APIENTRY glDeleteRenderbuffersOES (GLsizei n, const GLuint *renderbuffers)
GL_API void GL_APIENTRY glGenRenderbuffersOES (GLsizei n, GLuint *renderbuffers)
GL_API void GL_APIENTRY glRenderbufferStorageOES (GLenum target, GLenum internalformat, GLsizei width, GLsizei height)
GL_API void GL_APIENTRY glGetRenderbufferParameterivOES (GLenum target, GLenum pname, GLint *params)
GL_API GLboolean GL_APIENTRY glIsFramebufferOES (GLuint framebuffer)
GL_API void GL_APIENTRY glBindFramebufferOES (GLenum target, GLuint framebuffer)
GL_API void GL_APIENTRY glDeleteFramebuffersOES (GLsizei n, const GLuint *framebuffers)
GL_API void GL_APIENTRY glGenFramebuffersOES (GLsizei n, GLuint *framebuffers)
GL_API GLenum GL_APIENTRY glCheckFramebufferStatusOES (GLenum target)
GL_API void GL_APIENTRY glFramebufferRenderbufferOES (GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer)
GL_API void GL_APIENTRY glFramebufferTexture2DOES (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
GL_API void GL_APIENTRY glGetFramebufferAttachmentParameterivOES (GLenum target, GLenum attachment, GLenum pname, GLint *params)
GL_API void GL_APIENTRY glGenerateMipmapOES (GLenum target)
typedef GLboolean (GL_APIENTRYP PFNGLISRENDERBUFFEROESPROC)(GLuint renderbuffer)
typedef GLenum (GL_APIENTRYP PFNGLCHECKFRAMEBUFFERSTATUSOESPROC)(GLenum target)
GL_API void *GL_APIENTRY glMapBufferOES (GLenum target, GLenum access)
GL_API GLboolean GL_APIENTRY glUnmapBufferOES (GLenum target)
GL_API void GL_APIENTRY glGetBufferPointervOES (GLenum target, GLenum pname, GLvoid **params)
GL_API void GL_APIENTRY glCurrentPaletteMatrixOES (GLuint matrixpaletteindex)
GL_API void GL_APIENTRY glLoadPaletteFromModelViewMatrixOES (void)
GL_API void GL_APIENTRY glMatrixIndexPointerOES (GLint size, GLenum type, GLsizei stride, const GLvoid *pointer)
GL_API void GL_APIENTRY glWeightPointerOES (GLint size, GLenum type, GLsizei stride, const GLvoid *pointer)
GL_API GLbitfield GL_APIENTRY glQueryMatrixxOES (GLfixed mantissa[16], GLint exponent[16])
typedef GLbitfield (GL_APIENTRYP PFNGLQUERYMATRIXXOESPROC)(GLfixed mantissa[16]
GL_API void GL_APIENTRY glDepthRangefOES (GLclampf zNear, GLclampf zFar)
GL_API void GL_APIENTRY glFrustumfOES (GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar)
GL_API void GL_APIENTRY glOrthofOES (GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar)
GL_API void GL_APIENTRY glClipPlanefOES (GLenum plane, const GLfloat *equation)
GL_API void GL_APIENTRY glGetClipPlanefOES (GLenum pname, GLfloat eqn[4])
GL_API void GL_APIENTRY glClearDepthfOES (GLclampf depth)
GL_API void GL_APIENTRY glTexGenfOES (GLenum coord, GLenum pname, GLfloat param)
GL_API void GL_APIENTRY glTexGenfvOES (GLenum coord, GLenum pname, const GLfloat *params)
GL_API void GL_APIENTRY glTexGeniOES (GLenum coord, GLenum pname, GLint param)
GL_API void GL_APIENTRY glTexGenivOES (GLenum coord, GLenum pname, const GLint *params)
GL_API void GL_APIENTRY glTexGenxOES (GLenum coord, GLenum pname, GLfixed param)
GL_API void GL_APIENTRY glTexGenxvOES (GLenum coord, GLenum pname, const GLfixed *params)
GL_API void GL_APIENTRY glGetTexGenfvOES (GLenum coord, GLenum pname, GLfloat *params)
GL_API void GL_APIENTRY glGetTexGenivOES (GLenum coord, GLenum pname, GLint *params)
GL_API void GL_APIENTRY glGetTexGenxvOES (GLenum coord, GLenum pname, GLfixed *params)
GL_API void GL_APIENTRY glBindVertexArrayOES (GLuint array)
GL_API void GL_APIENTRY glDeleteVertexArraysOES (GLsizei n, const GLuint *arrays)
GL_API void GL_APIENTRY glGenVertexArraysOES (GLsizei n, GLuint *arrays)
GL_API GLboolean GL_APIENTRY glIsVertexArrayOES (GLuint array)
GL_API void GL_APIENTRY glRenderbufferStorageMultisampleAPPLE (GLenum, GLsizei, GLenum, GLsizei, GLsizei)
GL_API void GL_APIENTRY glResolveMultisampleFramebufferAPPLE (void)
GL_API void GL_APIENTRY glDiscardFramebufferEXT (GLenum target, GLsizei numAttachments, const GLenum *attachments)
GL_API void GL_APIENTRY glInsertEventMarkerEXT (GLsizei length, const GLchar *marker)
GL_API void GL_APIENTRY glPushGroupMarkerEXT (GLsizei length, const GLchar *marker)
GL_API void GL_APIENTRY glPopGroupMarkerEXT (void)
GL_API void GL_APIENTRY glMultiDrawArraysEXT (GLenum, GLint *, GLsizei *, GLsizei)
GL_API void GL_APIENTRY glMultiDrawElementsEXT (GLenum, const GLsizei *, GLenum, const GLvoid **, GLsizei)
GL_API void GL_APIENTRY glClipPlanefIMG (GLenum, const GLfloat *)
GL_API void GL_APIENTRY glClipPlanexIMG (GLenum, const GLfixed *)
GL_API void GL_APIENTRY glRenderbufferStorageMultisampleIMG (GLenum, GLsizei, GLenum, GLsizei, GLsizei)
GL_API void GL_APIENTRY glFramebufferTexture2DMultisampleIMG (GLenum, GLenum, GLenum, GLuint, GLint, GLsizei)
GL_API void GL_APIENTRY glDeleteFencesNV (GLsizei, const GLuint *)
GL_API void GL_APIENTRY glGenFencesNV (GLsizei, GLuint *)
GL_API GLboolean GL_APIENTRY glIsFenceNV (GLuint)
GL_API GLboolean GL_APIENTRY glTestFenceNV (GLuint)
GL_API void GL_APIENTRY glGetFenceivNV (GLuint, GLenum, GLint *)
GL_API void GL_APIENTRY glFinishFenceNV (GLuint)
GL_API void GL_APIENTRY glSetFenceNV (GLuint, GLenum)
GL_API void GL_APIENTRY glGetDriverControlsQCOM (GLint *num, GLsizei size, GLuint *driverControls)
GL_API void GL_APIENTRY glGetDriverControlStringQCOM (GLuint driverControl, GLsizei bufSize, GLsizei *length, GLchar *driverControlString)
GL_API void GL_APIENTRY glEnableDriverControlQCOM (GLuint driverControl)
GL_API void GL_APIENTRY glDisableDriverControlQCOM (GLuint driverControl)
GL_API void GL_APIENTRY glExtGetTexturesQCOM (GLuint *textures, GLint maxTextures, GLint *numTextures)
GL_API void GL_APIENTRY glExtGetBuffersQCOM (GLuint *buffers, GLint maxBuffers, GLint *numBuffers)
GL_API void GL_APIENTRY glExtGetRenderbuffersQCOM (GLuint *renderbuffers, GLint maxRenderbuffers, GLint *numRenderbuffers)
GL_API void GL_APIENTRY glExtGetFramebuffersQCOM (GLuint *framebuffers, GLint maxFramebuffers, GLint *numFramebuffers)
GL_API void GL_APIENTRY glExtGetTexLevelParameterivQCOM (GLuint texture, GLenum face, GLint level, GLenum pname, GLint *params)
GL_API void GL_APIENTRY glExtTexObjectStateOverrideiQCOM (GLenum target, GLenum pname, GLint param)
GL_API void GL_APIENTRY glExtGetTexSubImageQCOM (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, GLvoid *texels)
GL_API void GL_APIENTRY glExtGetBufferPointervQCOM (GLenum target, GLvoid **params)
GL_API void GL_APIENTRY glExtGetShadersQCOM (GLuint *shaders, GLint maxShaders, GLint *numShaders)
GL_API void GL_APIENTRY glExtGetProgramsQCOM (GLuint *programs, GLint maxPrograms, GLint *numPrograms)
GL_API GLboolean GL_APIENTRY glExtIsProgramBinaryQCOM (GLuint program)
GL_API void GL_APIENTRY glExtGetProgramBinarySourceQCOM (GLuint program, GLenum shadertype, GLchar *source, GLint *length)
GL_API void GL_APIENTRY glStartTilingQCOM (GLuint x, GLuint y, GLuint width, GLuint height, GLbitfield preserveMask)
GL_API void GL_APIENTRY glEndTilingQCOM (GLbitfield preserveMask)
Macro Definition Documentation
GL_3DC_X_AMD
#define GL_3DC_X_AMD 0x87F9
Definition at line 259 of file glext.h.
GL_3DC_XY_AMD
#define GL_3DC_XY_AMD 0x87FA
Definition at line 260 of file glext.h.
GL_ADD_BLEND_IMG
#define GL_ADD_BLEND_IMG 0x8C09
Definition at line 386 of file glext.h.
GL_ALL_COMPLETED_NV
#define GL_ALL_COMPLETED_NV 0x84F2
Definition at line 415 of file glext.h.
GL_AMD_compressed_3DC_texture
#define GL_AMD_compressed_3DC_texture 0
Definition at line 878 of file glext.h.
GL_AMD_compressed_ATC_texture
#define GL_AMD_compressed_ATC_texture 0
Definition at line 883 of file glext.h.
GL_APIENTRYP
#define GL_APIENTRYP GL_APIENTRY*
Definition at line 47 of file glext.h.
GL_APPLE_framebuffer_multisample
#define GL_APPLE_framebuffer_multisample 0
Definition at line 897 of file glext.h.
GL_APPLE_rgb_422
#define GL_APPLE_rgb_422 1
Definition at line 300 of file glext.h.
GL_APPLE_texture_2D_limited_npot
#define GL_APPLE_texture_2D_limited_npot 0
Definition at line 892 of file glext.h.
GL_APPLE_texture_format_BGRA8888
#define GL_APPLE_texture_format_BGRA8888 0
Definition at line 908 of file glext.h.
GL_APPLE_texture_max_level
#define GL_APPLE_texture_max_level 0
Definition at line 913 of file glext.h.
GL_ARM_rgba8
#define GL_ARM_rgba8 0
Definition at line 922 of file glext.h.
GL_ATC_RGB_AMD
#define GL_ATC_RGB_AMD 0x8C92
Definition at line 265 of file glext.h.
GL_ATC_RGBA_EXPLICIT_ALPHA_AMD
#define GL_ATC_RGBA_EXPLICIT_ALPHA_AMD 0x8C93
Definition at line 266 of file glext.h.
GL_ATC_RGBA_INTERPOLATED_ALPHA_AMD
#define GL_ATC_RGBA_INTERPOLATED_ALPHA_AMD 0x87EE
Definition at line 267 of file glext.h.
GL_BGRA_EXT [1/3]
#define GL_BGRA_EXT 0x80E1
Definition at line 347 of file glext.h.
GL_BGRA_EXT [2/3]
#define GL_BGRA_EXT 0x80E1
Definition at line 347 of file glext.h.
GL_BGRA_EXT [3/3]
#define GL_BGRA_EXT 0x80E1
Definition at line 347 of file glext.h.
GL_BGRA_IMG
#define GL_BGRA_IMG 0x80E1
Definition at line 367 of file glext.h.
GL_BLEND_DST_ALPHA_OES
#define GL_BLEND_DST_ALPHA_OES 0x80CA
Definition at line 65 of file glext.h.
GL_BLEND_DST_RGB_OES
#define GL_BLEND_DST_RGB_OES 0x80C8
Definition at line 63 of file glext.h.
GL_BLEND_EQUATION_ALPHA_OES
#define GL_BLEND_EQUATION_ALPHA_OES 0x883D
Definition at line 58 of file glext.h.
GL_BLEND_EQUATION_OES
#define GL_BLEND_EQUATION_OES 0x8009
Definition at line 71 of file glext.h.
GL_BLEND_EQUATION_RGB_OES
#define GL_BLEND_EQUATION_RGB_OES 0x8009
Definition at line 57 of file glext.h.
GL_BLEND_SRC_ALPHA_OES
#define GL_BLEND_SRC_ALPHA_OES 0x80CB
Definition at line 66 of file glext.h.
GL_BLEND_SRC_RGB_OES
#define GL_BLEND_SRC_RGB_OES 0x80C9
Definition at line 64 of file glext.h.
GL_BRCM_side_by_side_stero_hint
#define GL_BRCM_side_by_side_stero_hint 1
Definition at line 1140 of file glext.h.
GL_BUFFER_ACCESS_OES
#define GL_BUFFER_ACCESS_OES 0x88BB
Definition at line 160 of file glext.h.
GL_BUFFER_MAP_POINTER_OES
#define GL_BUFFER_MAP_POINTER_OES 0x88BD
Definition at line 162 of file glext.h.
GL_BUFFER_MAPPED_OES
#define GL_BUFFER_MAPPED_OES 0x88BC
Definition at line 161 of file glext.h.
GL_CLIP_PLANE0_IMG
#define GL_CLIP_PLANE0_IMG 0x3000
Definition at line 392 of file glext.h.
GL_CLIP_PLANE1_IMG
#define GL_CLIP_PLANE1_IMG 0x3001
Definition at line 393 of file glext.h.
GL_CLIP_PLANE2_IMG
#define GL_CLIP_PLANE2_IMG 0x3002
Definition at line 394 of file glext.h.
GL_CLIP_PLANE3_IMG
#define GL_CLIP_PLANE3_IMG 0x3003
Definition at line 395 of file glext.h.
GL_CLIP_PLANE4_IMG
#define GL_CLIP_PLANE4_IMG 0x3004
Definition at line 396 of file glext.h.
GL_CLIP_PLANE5_IMG
#define GL_CLIP_PLANE5_IMG 0x3005
Definition at line 397 of file glext.h.
GL_COLOR_ATTACHMENT0_OES
#define GL_COLOR_ATTACHMENT0_OES 0x8CE0
Definition at line 142 of file glext.h.
GL_COLOR_BUFFER_BIT0_QCOM
#define GL_COLOR_BUFFER_BIT0_QCOM 0x00000001
Definition at line 457 of file glext.h.
GL_COLOR_BUFFER_BIT1_QCOM
#define GL_COLOR_BUFFER_BIT1_QCOM 0x00000002
Definition at line 458 of file glext.h.
GL_COLOR_BUFFER_BIT2_QCOM
#define GL_COLOR_BUFFER_BIT2_QCOM 0x00000004
Definition at line 459 of file glext.h.
GL_COLOR_BUFFER_BIT3_QCOM
#define GL_COLOR_BUFFER_BIT3_QCOM 0x00000008
Definition at line 460 of file glext.h.
GL_COLOR_BUFFER_BIT4_QCOM
#define GL_COLOR_BUFFER_BIT4_QCOM 0x00000010
Definition at line 461 of file glext.h.
GL_COLOR_BUFFER_BIT5_QCOM
#define GL_COLOR_BUFFER_BIT5_QCOM 0x00000020
Definition at line 462 of file glext.h.
GL_COLOR_BUFFER_BIT6_QCOM
#define GL_COLOR_BUFFER_BIT6_QCOM 0x00000040
Definition at line 463 of file glext.h.
GL_COLOR_BUFFER_BIT7_QCOM
#define GL_COLOR_BUFFER_BIT7_QCOM 0x00000080
Definition at line 464 of file glext.h.
GL_COLOR_EXT
#define GL_COLOR_EXT 0x1800
Definition at line 324 of file glext.h.
GL_COMPRESSED_RGB_PVRTC_2BPPV1_IMG
#define GL_COMPRESSED_RGB_PVRTC_2BPPV1_IMG 0x8C01
Definition at line 374 of file glext.h.
GL_COMPRESSED_RGB_PVRTC_4BPPV1_IMG
#define GL_COMPRESSED_RGB_PVRTC_4BPPV1_IMG 0x8C00
Definition at line 373 of file glext.h.
GL_COMPRESSED_RGBA_PVRTC_2BPPV1_IMG
#define GL_COMPRESSED_RGBA_PVRTC_2BPPV1_IMG 0x8C03
Definition at line 376 of file glext.h.
GL_COMPRESSED_RGBA_PVRTC_4BPPV1_IMG
#define GL_COMPRESSED_RGBA_PVRTC_4BPPV1_IMG 0x8C02
Definition at line 375 of file glext.h.
GL_CURRENT_PALETTE_MATRIX_OES
#define GL_CURRENT_PALETTE_MATRIX_OES 0x8843
Definition at line 179 of file glext.h.
GL_DECR_WRAP_OES
#define GL_DECR_WRAP_OES 0x8508
Definition at line 223 of file glext.h.
GL_DEPTH24_STENCIL8_OES
#define GL_DEPTH24_STENCIL8_OES 0x88F0
Definition at line 196 of file glext.h.
GL_DEPTH_ATTACHMENT_OES
#define GL_DEPTH_ATTACHMENT_OES 0x8D00
Definition at line 143 of file glext.h.
GL_DEPTH_BUFFER_BIT0_QCOM
#define GL_DEPTH_BUFFER_BIT0_QCOM 0x00000100
Definition at line 465 of file glext.h.
GL_DEPTH_BUFFER_BIT1_QCOM
#define GL_DEPTH_BUFFER_BIT1_QCOM 0x00000200
Definition at line 466 of file glext.h.
GL_DEPTH_BUFFER_BIT2_QCOM
#define GL_DEPTH_BUFFER_BIT2_QCOM 0x00000400
Definition at line 467 of file glext.h.
GL_DEPTH_BUFFER_BIT3_QCOM
#define GL_DEPTH_BUFFER_BIT3_QCOM 0x00000800
Definition at line 468 of file glext.h.
GL_DEPTH_BUFFER_BIT4_QCOM
#define GL_DEPTH_BUFFER_BIT4_QCOM 0x00001000
Definition at line 469 of file glext.h.
GL_DEPTH_BUFFER_BIT5_QCOM
#define GL_DEPTH_BUFFER_BIT5_QCOM 0x00002000
Definition at line 470 of file glext.h.
GL_DEPTH_BUFFER_BIT6_QCOM
#define GL_DEPTH_BUFFER_BIT6_QCOM 0x00004000
Definition at line 471 of file glext.h.
GL_DEPTH_BUFFER_BIT7_QCOM
#define GL_DEPTH_BUFFER_BIT7_QCOM 0x00008000
Definition at line 472 of file glext.h.
GL_DEPTH_COMPONENT16_OES
#define GL_DEPTH_COMPONENT16_OES 0x81A5
Definition at line 128 of file glext.h.
GL_DEPTH_COMPONENT24_OES
#define GL_DEPTH_COMPONENT24_OES 0x81A6
Definition at line 84 of file glext.h.
GL_DEPTH_COMPONENT32_OES
#define GL_DEPTH_COMPONENT32_OES 0x81A7
Definition at line 89 of file glext.h.
GL_DEPTH_EXT
#define GL_DEPTH_EXT 0x1801
Definition at line 325 of file glext.h.
GL_DEPTH_STENCIL_OES
#define GL_DEPTH_STENCIL_OES 0x84F9
Definition at line 194 of file glext.h.
GL_DOT3_RGBA_IMG
#define GL_DOT3_RGBA_IMG 0x86AF
Definition at line 387 of file glext.h.
GL_DRAW_FRAMEBUFFER_APPLE
#define GL_DRAW_FRAMEBUFFER_APPLE 0x8CA9
Definition at line 283 of file glext.h.
GL_DRAW_FRAMEBUFFER_BINDING_APPLE
#define GL_DRAW_FRAMEBUFFER_BINDING_APPLE 0x8CA6
Definition at line 284 of file glext.h.
GL_ETC1_RGB8_OES
#define GL_ETC1_RGB8_OES 0x8D64
Definition at line 79 of file glext.h.
GL_EXT_blend_minmax
#define GL_EXT_blend_minmax 0
Definition at line 931 of file glext.h.
GL_EXT_debug_marker
#define GL_EXT_debug_marker 1
Definition at line 945 of file glext.h.
GL_EXT_discard_framebuffer
#define GL_EXT_discard_framebuffer 0
Definition at line 936 of file glext.h.
GL_EXT_multi_draw_arrays
#define GL_EXT_multi_draw_arrays 0
Definition at line 958 of file glext.h.
GL_EXT_read_format_bgra
#define GL_EXT_read_format_bgra 0
Definition at line 969 of file glext.h.
GL_EXT_texture_filter_anisotropic
#define GL_EXT_texture_filter_anisotropic 0
Definition at line 974 of file glext.h.
GL_EXT_texture_format_BGRA8888
#define GL_EXT_texture_format_BGRA8888 1
Definition at line 979 of file glext.h.
GL_EXT_texture_lod_bias
#define GL_EXT_texture_lod_bias 0
Definition at line 988 of file glext.h.
GL_FACTOR_ALPHA_MODULATE_IMG
#define GL_FACTOR_ALPHA_MODULATE_IMG 0x8C07
Definition at line 384 of file glext.h.
GL_FENCE_CONDITION_NV
#define GL_FENCE_CONDITION_NV 0x84F4
Definition at line 417 of file glext.h.
GL_FENCE_STATUS_NV
#define GL_FENCE_STATUS_NV 0x84F3
Definition at line 416 of file glext.h.
GL_FIXED_OES
#define GL_FIXED_OES 0x140C
Definition at line 117 of file glext.h.
GL_FRAGMENT_ALPHA_MODULATE_IMG
#define GL_FRAGMENT_ALPHA_MODULATE_IMG 0x8C08
Definition at line 385 of file glext.h.
GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME_OES
#define GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME_OES 0x8CD1
Definition at line 139 of file glext.h.
GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE_OES
#define GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE_OES 0x8CD0
Definition at line 138 of file glext.h.
GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE_OES
#define GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE_OES 0x8CD3
Definition at line 141 of file glext.h.
GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL_OES
#define GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL_OES 0x8CD2
Definition at line 140 of file glext.h.
GL_FRAMEBUFFER_BINDING_OES
#define GL_FRAMEBUFFER_BINDING_OES 0x8CA6
Definition at line 151 of file glext.h.
GL_FRAMEBUFFER_COMPLETE_OES
#define GL_FRAMEBUFFER_COMPLETE_OES 0x8CD5
Definition at line 145 of file glext.h.
GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT_OES
#define GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT_OES 0x8CD6
Definition at line 146 of file glext.h.
GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS_OES
#define GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS_OES 0x8CD9
Definition at line 148 of file glext.h.
GL_FRAMEBUFFER_INCOMPLETE_FORMATS_OES
#define GL_FRAMEBUFFER_INCOMPLETE_FORMATS_OES 0x8CDA
Definition at line 149 of file glext.h.
GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT_OES
#define GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT_OES 0x8CD7
Definition at line 147 of file glext.h.
GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE_APPLE
#define GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE_APPLE 0x8D56
Definition at line 280 of file glext.h.
GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE_IMG
#define GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE_IMG 0x9134
Definition at line 404 of file glext.h.
GL_FRAMEBUFFER_OES
#define GL_FRAMEBUFFER_OES 0x8D40
Definition at line 123 of file glext.h.
GL_FRAMEBUFFER_UNSUPPORTED_OES
#define GL_FRAMEBUFFER_UNSUPPORTED_OES 0x8CDD
Definition at line 150 of file glext.h.
GL_FUNC_ADD_OES
#define GL_FUNC_ADD_OES 0x8006
Definition at line 72 of file glext.h.
GL_FUNC_REVERSE_SUBTRACT_OES
#define GL_FUNC_REVERSE_SUBTRACT_OES 0x800B
Definition at line 74 of file glext.h.
GL_FUNC_SUBTRACT_OES
#define GL_FUNC_SUBTRACT_OES 0x800A
Definition at line 73 of file glext.h.
GL_GLEXT_PROTOTYPES
#define GL_GLEXT_PROTOTYPES
Definition at line 38 of file glext.h.
GL_IMG_multisampled_render_to_texture
#define GL_IMG_multisampled_render_to_texture 0
Definition at line 1023 of file glext.h.
GL_IMG_read_format
#define GL_IMG_read_format 0
Definition at line 997 of file glext.h.
GL_IMG_texture_compression_pvrtc
#define GL_IMG_texture_compression_pvrtc 0
Definition at line 1002 of file glext.h.
GL_IMG_texture_env_enhanced_fixed_function
#define GL_IMG_texture_env_enhanced_fixed_function 0
Definition at line 1007 of file glext.h.
GL_IMG_user_clip_plane
#define GL_IMG_user_clip_plane 0
Definition at line 1012 of file glext.h.
GL_INCR_WRAP_OES
#define GL_INCR_WRAP_OES 0x8507
Definition at line 222 of file glext.h.
GL_INVALID_FRAMEBUFFER_OPERATION_OES
#define GL_INVALID_FRAMEBUFFER_OPERATION_OES 0x0506
Definition at line 154 of file glext.h.
GL_MATRIX_INDEX_ARRAY_BUFFER_BINDING_OES
#define GL_MATRIX_INDEX_ARRAY_BUFFER_BINDING_OES 0x8B9E
Definition at line 184 of file glext.h.
GL_MATRIX_INDEX_ARRAY_OES
#define GL_MATRIX_INDEX_ARRAY_OES 0x8844
Definition at line 177 of file glext.h.
GL_MATRIX_INDEX_ARRAY_POINTER_OES
#define GL_MATRIX_INDEX_ARRAY_POINTER_OES 0x8849
Definition at line 183 of file glext.h.
Referenced by glGetPointerv().
GL_MATRIX_INDEX_ARRAY_SIZE_OES
#define GL_MATRIX_INDEX_ARRAY_SIZE_OES 0x8846
Definition at line 180 of file glext.h.
GL_MATRIX_INDEX_ARRAY_STRIDE_OES
#define GL_MATRIX_INDEX_ARRAY_STRIDE_OES 0x8848
Definition at line 182 of file glext.h.
GL_MATRIX_INDEX_ARRAY_TYPE_OES
#define GL_MATRIX_INDEX_ARRAY_TYPE_OES 0x8847
Definition at line 181 of file glext.h.
GL_MATRIX_PALETTE_OES
#define GL_MATRIX_PALETTE_OES 0x8840
Definition at line 176 of file glext.h.
GL_MAX_CLIP_PLANES_IMG
#define GL_MAX_CLIP_PLANES_IMG 0x0D32
Definition at line 398 of file glext.h.
GL_MAX_CUBE_MAP_TEXTURE_SIZE_OES
#define GL_MAX_CUBE_MAP_TEXTURE_SIZE_OES 0x851C
Definition at line 238 of file glext.h.
GL_MAX_EXT
#define GL_MAX_EXT 0x8008
Definition at line 319 of file glext.h.
GL_MAX_PALETTE_MATRICES_OES
#define GL_MAX_PALETTE_MATRICES_OES 0x8842
Definition at line 175 of file glext.h.
GL_MAX_RENDERBUFFER_SIZE_OES
#define GL_MAX_RENDERBUFFER_SIZE_OES 0x84E8
Definition at line 153 of file glext.h.
GL_MAX_SAMPLES_APPLE
#define GL_MAX_SAMPLES_APPLE 0x8D57
Definition at line 281 of file glext.h.
GL_MAX_SAMPLES_IMG
#define GL_MAX_SAMPLES_IMG 0x9135
Definition at line 405 of file glext.h.
GL_MAX_TEXTURE_LOD_BIAS_EXT
#define GL_MAX_TEXTURE_LOD_BIAS_EXT 0x84FD
Definition at line 356 of file glext.h.
GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT
#define GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT 0x84FF
Definition at line 342 of file glext.h.
GL_MAX_VERTEX_UNITS_OES
#define GL_MAX_VERTEX_UNITS_OES 0x86A4
Definition at line 174 of file glext.h.
GL_MIN_EXT
#define GL_MIN_EXT 0x8007
Definition at line 318 of file glext.h.
GL_MIRRORED_REPEAT_OES
#define GL_MIRRORED_REPEAT_OES 0x8370
Definition at line 245 of file glext.h.
GL_MODELVIEW_MATRIX_FLOAT_AS_INT_BITS_OES
#define GL_MODELVIEW_MATRIX_FLOAT_AS_INT_BITS_OES 0x898D
Definition at line 167 of file glext.h.
GL_MODULATE_COLOR_IMG
#define GL_MODULATE_COLOR_IMG 0x8C04
Definition at line 381 of file glext.h.
GL_MULTISAMPLE_BUFFER_BIT0_QCOM
#define GL_MULTISAMPLE_BUFFER_BIT0_QCOM 0x01000000
Definition at line 481 of file glext.h.
GL_MULTISAMPLE_BUFFER_BIT1_QCOM
#define GL_MULTISAMPLE_BUFFER_BIT1_QCOM 0x02000000
Definition at line 482 of file glext.h.
GL_MULTISAMPLE_BUFFER_BIT2_QCOM
#define GL_MULTISAMPLE_BUFFER_BIT2_QCOM 0x04000000
Definition at line 483 of file glext.h.
GL_MULTISAMPLE_BUFFER_BIT3_QCOM
#define GL_MULTISAMPLE_BUFFER_BIT3_QCOM 0x08000000
Definition at line 484 of file glext.h.
GL_MULTISAMPLE_BUFFER_BIT4_QCOM
#define GL_MULTISAMPLE_BUFFER_BIT4_QCOM 0x10000000
Definition at line 485 of file glext.h.
GL_MULTISAMPLE_BUFFER_BIT5_QCOM
#define GL_MULTISAMPLE_BUFFER_BIT5_QCOM 0x20000000
Definition at line 486 of file glext.h.
GL_MULTISAMPLE_BUFFER_BIT6_QCOM
#define GL_MULTISAMPLE_BUFFER_BIT6_QCOM 0x40000000
Definition at line 487 of file glext.h.
GL_MULTISAMPLE_BUFFER_BIT7_QCOM
#define GL_MULTISAMPLE_BUFFER_BIT7_QCOM 0x80000000
Definition at line 488 of file glext.h.
GL_NONE_OES
#define GL_NONE_OES 0
Definition at line 122 of file glext.h.
GL_NORMAL_MAP_OES
#define GL_NORMAL_MAP_OES 0x8511
Definition at line 228 of file glext.h.
GL_NV_fence
#define GL_NV_fence 0
Definition at line 1038 of file glext.h.
GL_OES_blend_equation_separate
#define GL_OES_blend_equation_separate 0
Definition at line 509 of file glext.h.
GL_OES_blend_func_separate
#define GL_OES_blend_func_separate 0
Definition at line 518 of file glext.h.
GL_OES_blend_subtract
#define GL_OES_blend_subtract 0
Definition at line 527 of file glext.h.
GL_OES_byte_coordinates
#define GL_OES_byte_coordinates 0
Definition at line 536 of file glext.h.
GL_OES_compressed_ETC1_RGB8_texture
#define GL_OES_compressed_ETC1_RGB8_texture 1
Definition at line 541 of file glext.h.
GL_OES_depth24
#define GL_OES_depth24 0
Definition at line 546 of file glext.h.
GL_OES_depth32
#define GL_OES_depth32 0
Definition at line 551 of file glext.h.
GL_OES_draw_texture
#define GL_OES_draw_texture 1
Definition at line 556 of file glext.h.
GL_OES_EGL_image
#define GL_OES_EGL_image 1
Definition at line 579 of file glext.h.
GL_OES_EGL_image_external
#define GL_OES_EGL_image_external 1
Definition at line 590 of file glext.h.
GL_OES_element_index_uint
#define GL_OES_element_index_uint 0
Definition at line 596 of file glext.h.
GL_OES_extended_matrix_palette
#define GL_OES_extended_matrix_palette 0
Definition at line 601 of file glext.h.
GL_OES_fbo_render_mipmap
#define GL_OES_fbo_render_mipmap 0
Definition at line 606 of file glext.h.
GL_OES_fixed_point
#define GL_OES_fixed_point 0
Definition at line 611 of file glext.h.
GL_OES_framebuffer_object
#define GL_OES_framebuffer_object 1
Definition at line 696 of file glext.h.
GL_OES_mapbuffer
#define GL_OES_mapbuffer 1
Definition at line 733 of file glext.h.
GL_OES_matrix_get
#define GL_OES_matrix_get 0
Definition at line 746 of file glext.h.
GL_OES_matrix_palette
#define GL_OES_matrix_palette 1
Definition at line 751 of file glext.h.
GL_OES_packed_depth_stencil
#define GL_OES_packed_depth_stencil 0
Definition at line 766 of file glext.h.
GL_OES_query_matrix
#define GL_OES_query_matrix 1
Definition at line 771 of file glext.h.
GL_OES_rgb8_rgba8
#define GL_OES_rgb8_rgba8 1
Definition at line 780 of file glext.h.
GL_OES_single_precision
#define GL_OES_single_precision 0
Definition at line 785 of file glext.h.
GL_OES_stencil1
#define GL_OES_stencil1 0
Definition at line 804 of file glext.h.
GL_OES_stencil4
#define GL_OES_stencil4 0
Definition at line 809 of file glext.h.
GL_OES_stencil8
#define GL_OES_stencil8 1
Definition at line 814 of file glext.h.
GL_OES_stencil_wrap
#define GL_OES_stencil_wrap 0
Definition at line 819 of file glext.h.
GL_OES_texture_cube_map
#define GL_OES_texture_cube_map 0
Definition at line 824 of file glext.h.
GL_OES_texture_env_crossbar
#define GL_OES_texture_env_crossbar 0
Definition at line 849 of file glext.h.
GL_OES_texture_mirrored_repeat
#define GL_OES_texture_mirrored_repeat 0
Definition at line 854 of file glext.h.
GL_OES_vertex_array_object
#define GL_OES_vertex_array_object 0
Definition at line 859 of file glext.h.
GL_PERFMON_GLOBAL_MODE_QCOM
#define GL_PERFMON_GLOBAL_MODE_QCOM 0x8FA0
Definition at line 447 of file glext.h.
GL_PROJECTION_MATRIX_FLOAT_AS_INT_BITS_OES
#define GL_PROJECTION_MATRIX_FLOAT_AS_INT_BITS_OES 0x898E
Definition at line 168 of file glext.h.
GL_QCOM_driver_control
#define GL_QCOM_driver_control 0
Definition at line 1063 of file glext.h.
GL_QCOM_extended_get
#define GL_QCOM_extended_get 0
Definition at line 1078 of file glext.h.
GL_QCOM_extended_get2
#define GL_QCOM_extended_get2 0
Definition at line 1101 of file glext.h.
GL_QCOM_perfmon_global_mode
#define GL_QCOM_perfmon_global_mode 0
Definition at line 1116 of file glext.h.
GL_QCOM_tiled_rendering
#define GL_QCOM_tiled_rendering 0
Definition at line 1126 of file glext.h.
GL_QCOM_writeonly_rendering
#define GL_QCOM_writeonly_rendering 0
Definition at line 1121 of file glext.h.
GL_READ_FRAMEBUFFER_APPLE
#define GL_READ_FRAMEBUFFER_APPLE 0x8CA8
Definition at line 282 of file glext.h.
GL_READ_FRAMEBUFFER_BINDING_APPLE
#define GL_READ_FRAMEBUFFER_BINDING_APPLE 0x8CAA
Definition at line 285 of file glext.h.
GL_RECIP_ADD_SIGNED_ALPHA_IMG
#define GL_RECIP_ADD_SIGNED_ALPHA_IMG 0x8C05
Definition at line 382 of file glext.h.
GL_REFLECTION_MAP_OES
#define GL_REFLECTION_MAP_OES 0x8512
Definition at line 229 of file glext.h.
GL_RENDERBUFFER_ALPHA_SIZE_OES
#define GL_RENDERBUFFER_ALPHA_SIZE_OES 0x8D53
Definition at line 135 of file glext.h.
GL_RENDERBUFFER_BINDING_OES
#define GL_RENDERBUFFER_BINDING_OES 0x8CA7
Definition at line 152 of file glext.h.
GL_RENDERBUFFER_BLUE_SIZE_OES
#define GL_RENDERBUFFER_BLUE_SIZE_OES 0x8D52
Definition at line 134 of file glext.h.
GL_RENDERBUFFER_DEPTH_SIZE_OES
#define GL_RENDERBUFFER_DEPTH_SIZE_OES 0x8D54
Definition at line 136 of file glext.h.
GL_RENDERBUFFER_GREEN_SIZE_OES
#define GL_RENDERBUFFER_GREEN_SIZE_OES 0x8D51
Definition at line 133 of file glext.h.
GL_RENDERBUFFER_HEIGHT_OES
#define GL_RENDERBUFFER_HEIGHT_OES 0x8D43
Definition at line 130 of file glext.h.
GL_RENDERBUFFER_INTERNAL_FORMAT_OES
#define GL_RENDERBUFFER_INTERNAL_FORMAT_OES 0x8D44
Definition at line 131 of file glext.h.
GL_RENDERBUFFER_OES
#define GL_RENDERBUFFER_OES 0x8D41
Definition at line 124 of file glext.h.
GL_RENDERBUFFER_RED_SIZE_OES
#define GL_RENDERBUFFER_RED_SIZE_OES 0x8D50
Definition at line 132 of file glext.h.
GL_RENDERBUFFER_SAMPLES_APPLE
#define GL_RENDERBUFFER_SAMPLES_APPLE 0x8CAB
Definition at line 279 of file glext.h.
GL_RENDERBUFFER_SAMPLES_IMG
#define GL_RENDERBUFFER_SAMPLES_IMG 0x9133
Definition at line 403 of file glext.h.
GL_RENDERBUFFER_STENCIL_SIZE_OES
#define GL_RENDERBUFFER_STENCIL_SIZE_OES 0x8D55
Definition at line 137 of file glext.h.
GL_RENDERBUFFER_WIDTH_OES
#define GL_RENDERBUFFER_WIDTH_OES 0x8D42
Definition at line 129 of file glext.h.
GL_REQUIRED_TEXTURE_IMAGE_UNITS_OES
#define GL_REQUIRED_TEXTURE_IMAGE_UNITS_OES 0x8D68
Definition at line 107 of file glext.h.
GL_RGB565_OES
#define GL_RGB565_OES 0x8D62
Definition at line 127 of file glext.h.
GL_RGB5_A1_OES
#define GL_RGB5_A1_OES 0x8057
Definition at line 126 of file glext.h.
GL_RGB8_OES
#define GL_RGB8_OES 0x8051
Definition at line 201 of file glext.h.
GL_RGB_422_APPLE
#define GL_RGB_422_APPLE 0x8A1F
Definition at line 301 of file glext.h.
GL_RGBA4_OES
#define GL_RGBA4_OES 0x8056
Definition at line 125 of file glext.h.
GL_RGBA8_OES
#define GL_RGBA8_OES 0x8058
Definition at line 202 of file glext.h.
GL_RGBX_BRCM
#define GL_RGBX_BRCM 0x80EE
Definition at line 351 of file glext.h.
GL_SIDE_BY_SIDE_STEREO_HINT_BRCM
#define GL_SIDE_BY_SIDE_STEREO_HINT_BRCM 0x8193 /* GET AN OFFICIAL ENUM */
Definition at line 496 of file glext.h.
GL_STATE_RESTORE
#define GL_STATE_RESTORE 0x8BDC
Definition at line 439 of file glext.h.
GL_STENCIL_ATTACHMENT_OES
#define GL_STENCIL_ATTACHMENT_OES 0x8D20
Definition at line 144 of file glext.h.
GL_STENCIL_BUFFER_BIT0_QCOM
#define GL_STENCIL_BUFFER_BIT0_QCOM 0x00010000
Definition at line 473 of file glext.h.
GL_STENCIL_BUFFER_BIT1_QCOM
#define GL_STENCIL_BUFFER_BIT1_QCOM 0x00020000
Definition at line 474 of file glext.h.
GL_STENCIL_BUFFER_BIT2_QCOM
#define GL_STENCIL_BUFFER_BIT2_QCOM 0x00040000
Definition at line 475 of file glext.h.
GL_STENCIL_BUFFER_BIT3_QCOM
#define GL_STENCIL_BUFFER_BIT3_QCOM 0x00080000
Definition at line 476 of file glext.h.
GL_STENCIL_BUFFER_BIT4_QCOM
#define GL_STENCIL_BUFFER_BIT4_QCOM 0x00100000
Definition at line 477 of file glext.h.
GL_STENCIL_BUFFER_BIT5_QCOM
#define GL_STENCIL_BUFFER_BIT5_QCOM 0x00200000
Definition at line 478 of file glext.h.
GL_STENCIL_BUFFER_BIT6_QCOM
#define GL_STENCIL_BUFFER_BIT6_QCOM 0x00400000
Definition at line 479 of file glext.h.
GL_STENCIL_BUFFER_BIT7_QCOM
#define GL_STENCIL_BUFFER_BIT7_QCOM 0x00800000
Definition at line 480 of file glext.h.
GL_STENCIL_EXT
#define GL_STENCIL_EXT 0x1802
Definition at line 326 of file glext.h.
GL_STENCIL_INDEX1_OES
#define GL_STENCIL_INDEX1_OES 0x8D46
Definition at line 207 of file glext.h.
GL_STENCIL_INDEX4_OES
#define GL_STENCIL_INDEX4_OES 0x8D47
Definition at line 212 of file glext.h.
GL_STENCIL_INDEX8_OES
#define GL_STENCIL_INDEX8_OES 0x8D48
Definition at line 217 of file glext.h.
GL_TEXTURE_ALPHA_MODULATE_IMG
#define GL_TEXTURE_ALPHA_MODULATE_IMG 0x8C06
Definition at line 383 of file glext.h.
GL_TEXTURE_BINDING_CUBE_MAP_OES
#define GL_TEXTURE_BINDING_CUBE_MAP_OES 0x8514
Definition at line 231 of file glext.h.
GL_TEXTURE_BINDING_EXTERNAL_OES
#define GL_TEXTURE_BINDING_EXTERNAL_OES 0x8D67
Definition at line 106 of file glext.h.
GL_TEXTURE_CROP_RECT_OES
#define GL_TEXTURE_CROP_RECT_OES 0x8B9D
Definition at line 94 of file glext.h.
GL_TEXTURE_CUBE_MAP_NEGATIVE_X_OES
#define GL_TEXTURE_CUBE_MAP_NEGATIVE_X_OES 0x8516
Definition at line 233 of file glext.h.
GL_TEXTURE_CUBE_MAP_NEGATIVE_Y_OES
#define GL_TEXTURE_CUBE_MAP_NEGATIVE_Y_OES 0x8518
Definition at line 235 of file glext.h.
GL_TEXTURE_CUBE_MAP_NEGATIVE_Z_OES
#define GL_TEXTURE_CUBE_MAP_NEGATIVE_Z_OES 0x851A
Definition at line 237 of file glext.h.
GL_TEXTURE_CUBE_MAP_OES
#define GL_TEXTURE_CUBE_MAP_OES 0x8513
Definition at line 230 of file glext.h.
GL_TEXTURE_CUBE_MAP_POSITIVE_X_OES
#define GL_TEXTURE_CUBE_MAP_POSITIVE_X_OES 0x8515
Definition at line 232 of file glext.h.
GL_TEXTURE_CUBE_MAP_POSITIVE_Y_OES
#define GL_TEXTURE_CUBE_MAP_POSITIVE_Y_OES 0x8517
Definition at line 234 of file glext.h.
GL_TEXTURE_CUBE_MAP_POSITIVE_Z_OES
#define GL_TEXTURE_CUBE_MAP_POSITIVE_Z_OES 0x8519
Definition at line 236 of file glext.h.
GL_TEXTURE_DEPTH_QCOM
#define GL_TEXTURE_DEPTH_QCOM 0x8BD4
Definition at line 431 of file glext.h.
GL_TEXTURE_EXTERNAL_OES
#define GL_TEXTURE_EXTERNAL_OES 0x8D65
Definition at line 105 of file glext.h.
GL_TEXTURE_FILTER_CONTROL_EXT
#define GL_TEXTURE_FILTER_CONTROL_EXT 0x8500
Definition at line 357 of file glext.h.
GL_TEXTURE_FORMAT_QCOM
#define GL_TEXTURE_FORMAT_QCOM 0x8BD6
Definition at line 433 of file glext.h.
GL_texture_format_RGBX8888_BRCM
#define GL_texture_format_RGBX8888_BRCM 1
Definition at line 983 of file glext.h.
GL_TEXTURE_GEN_MODE_OES
#define GL_TEXTURE_GEN_MODE_OES 0x2500
Definition at line 239 of file glext.h.
GL_TEXTURE_GEN_STR_OES
#define GL_TEXTURE_GEN_STR_OES 0x8D60
Definition at line 240 of file glext.h.
GL_TEXTURE_HEIGHT_QCOM
#define GL_TEXTURE_HEIGHT_QCOM 0x8BD3
Definition at line 430 of file glext.h.
GL_TEXTURE_IMAGE_VALID_QCOM
#define GL_TEXTURE_IMAGE_VALID_QCOM 0x8BD8
Definition at line 435 of file glext.h.
GL_TEXTURE_INTERNAL_FORMAT_QCOM
#define GL_TEXTURE_INTERNAL_FORMAT_QCOM 0x8BD5
Definition at line 432 of file glext.h.
GL_TEXTURE_LOD_BIAS_EXT
#define GL_TEXTURE_LOD_BIAS_EXT 0x8501
Definition at line 358 of file glext.h.
GL_TEXTURE_MATRIX_FLOAT_AS_INT_BITS_OES
#define GL_TEXTURE_MATRIX_FLOAT_AS_INT_BITS_OES 0x898F
Definition at line 169 of file glext.h.
GL_TEXTURE_MAX_ANISOTROPY_EXT
#define GL_TEXTURE_MAX_ANISOTROPY_EXT 0x84FE
Definition at line 341 of file glext.h.
GL_TEXTURE_MAX_LEVEL_APPLE
#define GL_TEXTURE_MAX_LEVEL_APPLE 0x813D
Definition at line 295 of file glext.h.
GL_TEXTURE_NUM_LEVELS_QCOM
#define GL_TEXTURE_NUM_LEVELS_QCOM 0x8BD9
Definition at line 436 of file glext.h.
GL_TEXTURE_OBJECT_VALID_QCOM
#define GL_TEXTURE_OBJECT_VALID_QCOM 0x8BDB
Definition at line 438 of file glext.h.
GL_TEXTURE_SAMPLES_IMG
#define GL_TEXTURE_SAMPLES_IMG 0x9136
Definition at line 406 of file glext.h.
GL_TEXTURE_TARGET_QCOM
#define GL_TEXTURE_TARGET_QCOM 0x8BDA
Definition at line 437 of file glext.h.
GL_TEXTURE_TYPE_QCOM
#define GL_TEXTURE_TYPE_QCOM 0x8BD7
Definition at line 434 of file glext.h.
GL_TEXTURE_WIDTH_QCOM
#define GL_TEXTURE_WIDTH_QCOM 0x8BD2
Definition at line 429 of file glext.h.
GL_UNSIGNED_INT
#define GL_UNSIGNED_INT 0x1405
Definition at line 112 of file glext.h.
GL_UNSIGNED_INT_24_8_OES
#define GL_UNSIGNED_INT_24_8_OES 0x84FA
Definition at line 195 of file glext.h.
GL_UNSIGNED_SHORT_1_5_5_5_REV_EXT
#define GL_UNSIGNED_SHORT_1_5_5_5_REV_EXT 0x8366
Definition at line 336 of file glext.h.
GL_UNSIGNED_SHORT_4_4_4_4_REV_EXT
#define GL_UNSIGNED_SHORT_4_4_4_4_REV_EXT 0x8365
Definition at line 335 of file glext.h.
GL_UNSIGNED_SHORT_4_4_4_4_REV_IMG
#define GL_UNSIGNED_SHORT_4_4_4_4_REV_IMG 0x8365
Definition at line 368 of file glext.h.
GL_UNSIGNED_SHORT_8_8_APPLE
#define GL_UNSIGNED_SHORT_8_8_APPLE 0x85BA
Definition at line 302 of file glext.h.
GL_UNSIGNED_SHORT_8_8_REV_APPLE
#define GL_UNSIGNED_SHORT_8_8_REV_APPLE 0x85BB
Definition at line 303 of file glext.h.
GL_VERTEX_ARRAY_BINDING_OES
#define GL_VERTEX_ARRAY_BINDING_OES 0x85B5
Definition at line 250 of file glext.h.
GL_WEIGHT_ARRAY_BUFFER_BINDING_OES
#define GL_WEIGHT_ARRAY_BUFFER_BINDING_OES 0x889E
Definition at line 189 of file glext.h.
GL_WEIGHT_ARRAY_OES
#define GL_WEIGHT_ARRAY_OES 0x86AD
Definition at line 178 of file glext.h.
GL_WEIGHT_ARRAY_POINTER_OES
#define GL_WEIGHT_ARRAY_POINTER_OES 0x86AC
Definition at line 188 of file glext.h.
Referenced by glGetPointerv().
GL_WEIGHT_ARRAY_SIZE_OES
#define GL_WEIGHT_ARRAY_SIZE_OES 0x86AB
Definition at line 185 of file glext.h.
GL_WEIGHT_ARRAY_STRIDE_OES
#define GL_WEIGHT_ARRAY_STRIDE_OES 0x86AA
Definition at line 187 of file glext.h.
GL_WEIGHT_ARRAY_TYPE_OES
#define GL_WEIGHT_ARRAY_TYPE_OES 0x86A9
Definition at line 186 of file glext.h.
GL_WRITE_ONLY_OES
#define GL_WRITE_ONLY_OES 0x88B9
Definition at line 159 of file glext.h.
GL_WRITEONLY_RENDERING_QCOM
#define GL_WRITEONLY_RENDERING_QCOM 0x8823
Definition at line 452 of file glext.h.
Typedef Documentation
alpha
typedef GLfixed GLfixed GLfixed alpha
Definition at line 654 of file glext.h.
arrays
typedef GLuint * arrays
Definition at line 867 of file glext.h.
attachment
typedef GLenum attachment
Definition at line 725 of file glext.h.
attachments
typedef GLsizei const GLenum* attachments
Definition at line 940 of file glext.h.
blue
typedef GLfixed GLfixed blue
Definition at line 654 of file glext.h.
bottom
typedef GLfloat GLfloat bottom
Definition at line 661 of file glext.h.
bufSize
typedef GLsizei bufSize
Definition at line 1071 of file glext.h.
condition
typedef GLenum condition
Definition at line 1054 of file glext.h.
count
typedef const GLsizei * count
Definition at line 963 of file glext.h.
depth
typedef GLint GLint GLint GLint GLsizei GLsizei GLsizei depth
Definition at line 1095 of file glext.h.
driverControls
typedef GLsizei GLuint* driverControls
Definition at line 1070 of file glext.h.
driverControlString
typedef GLsizei GLsizei GLchar* driverControlString
Definition at line 1071 of file glext.h.
dstAlpha
typedef GLenum GLenum GLenum dstAlpha
Definition at line 522 of file glext.h.
dstRGB
typedef GLenum dstRGB
Definition at line 522 of file glext.h.
eqn
typedef const GLfixed * eqn
Definition at line 662 of file glext.h.
equation
typedef const GLfloat * equation
Definition at line 656 of file glext.h.
exponent
typedef GLint exponent[16]
Definition at line 775 of file glext.h.
face
GLclampf depth GLboolean GLboolean GLboolean GLboolean alpha GLenum func GLclampf GLclampf zFar GLenum cap GLfloat width GLclampf GLboolean invert GLenum GLenum GLint GLuint mask GLenum face
Definition at line 1093 of file glext.h.
fences
typedef GLuint * fences
Definition at line 1048 of file glext.h.
first
typedef GLint* first
Definition at line 963 of file glext.h.
format
typedef GLint GLint GLint GLint GLsizei GLsizei GLsizei GLenum format
Definition at line 1095 of file glext.h.
framebuffer
typedef GLuint framebuffer
Definition at line 721 of file glext.h.
framebuffers
typedef GLuint * framebuffers
Definition at line 722 of file glext.h.
GLeglImageOES
typedef void* GLeglImageOES
Definition at line 99 of file glext.h.
green
typedef GLfixed green
Definition at line 654 of file glext.h.
height
typedef GLuint GLuint GLuint height
Definition at line 567 of file glext.h.
image
typedef GLeglImageOES image
Definition at line 584 of file glext.h.
indices
typedef const GLsizei GLenum const GLvoid* * indices
Definition at line 964 of file glext.h.
internalformat
typedef GLsizei GLenum internalformat
Definition at line 718 of file glext.h.
invert
typedef GLboolean invert
Definition at line 685 of file glext.h.
length
typedef GLenum GLchar GLint* length
Definition at line 1071 of file glext.h.
level
typedef GLint level
Definition at line 726 of file glext.h.
marker
typedef const GLchar * marker
Definition at line 951 of file glext.h.
maxBuffers
typedef GLint maxBuffers
Definition at line 1090 of file glext.h.
maxFramebuffers
typedef GLint maxFramebuffers
Definition at line 1092 of file glext.h.
maxPrograms
typedef GLint maxPrograms
Definition at line 1109 of file glext.h.
maxRenderbuffers
typedef GLint maxRenderbuffers
Definition at line 1091 of file glext.h.
maxShaders
typedef GLint maxShaders
Definition at line 1108 of file glext.h.
maxTextures
typedef GLint maxTextures
Definition at line 1089 of file glext.h.
modeAlpha
typedef GLenum modeAlpha
Definition at line 513 of file glext.h.
numAttachments
typedef GLsizei numAttachments
Definition at line 940 of file glext.h.
numBuffers
typedef GLint GLint* numBuffers
Definition at line 1090 of file glext.h.
numFramebuffers
typedef GLint GLint* numFramebuffers
Definition at line 1092 of file glext.h.
numPrograms
typedef GLint GLint* numPrograms
Definition at line 1109 of file glext.h.
numRenderbuffers
typedef GLint GLint* numRenderbuffers
Definition at line 1091 of file glext.h.
numShaders
typedef GLint GLint* numShaders
Definition at line 1108 of file glext.h.
numTextures
typedef GLint GLint* numTextures
Definition at line 1089 of file glext.h.
ny
typedef GLfixed ny
Definition at line 678 of file glext.h.
nz
typedef GLfixed GLfixed nz
Definition at line 678 of file glext.h.
param
typedef GLenum GLint param
Definition at line 659 of file glext.h.
params
typedef GLvoid ** params
Definition at line 660 of file glext.h.
PFNGLMAPBUFFEROESPROC
typedef void* GL_APIENTRYP PFNGLMAPBUFFEROESPROC(GLenum target, GLenum access)
Definition at line 739 of file glext.h.
pname
typedef GLenum pname
Definition at line 664 of file glext.h.
pointer
typedef GLenum GLsizei const GLvoid * pointer
Definition at line 760 of file glext.h.
preserveMask
typedef GLuint GLuint GLuint GLbitfield preserveMask
Definition at line 1131 of file glext.h.
primcount
typedef const GLsizei GLenum const GLvoid GLsizei primcount
Definition at line 963 of file glext.h.
q
typedef GLfixed GLfixed GLfixed GLfixed q
Definition at line 677 of file glext.h.
r
typedef GLfixed GLfixed GLfixed r
Definition at line 677 of file glext.h.
ref
typedef GLclampx ref
Definition at line 653 of file glext.h.
renderbuffer
typedef GLenum GLenum GLuint renderbuffer
Definition at line 715 of file glext.h.
renderbuffers
typedef GLuint * renderbuffers
Definition at line 716 of file glext.h.
renderbuffertarget
typedef GLenum GLenum renderbuffertarget
Definition at line 725 of file glext.h.
right
typedef GLfloat right
Definition at line 661 of file glext.h.
s
typedef GLfixed s
Definition at line 677 of file glext.h.
samples
typedef GLenum GLenum GLuint GLint GLsizei samples
Definition at line 902 of file glext.h.
shadertype
typedef GLenum shadertype
Definition at line 1111 of file glext.h.
size
typedef GLsizei size
Definition at line 1070 of file glext.h.
source
typedef GLenum GLchar* source
Definition at line 1111 of file glext.h.
srcAlpha
typedef GLenum GLenum srcAlpha
Definition at line 522 of file glext.h.
stride
typedef GLenum GLsizei stride
Definition at line 760 of file glext.h.
t
typedef GLfixed GLfixed t
Definition at line 677 of file glext.h.
texels
typedef GLint GLint GLint GLint GLsizei GLsizei GLsizei GLenum GLenum GLvoid* texels
Definition at line 1095 of file glext.h.
textarget
typedef GLenum GLenum textarget
Definition at line 726 of file glext.h.
texture
typedef GLenum GLenum GLuint texture
Definition at line 726 of file glext.h.
top
typedef GLfloat GLfloat GLfloat top
Definition at line 661 of file glext.h.
type
typedef GLint GLint GLint GLint GLsizei GLsizei GLsizei GLenum GLenum type
Definition at line 760 of file glext.h.
units
typedef GLfixed units
Definition at line 683 of file glext.h.
width
typedef GLuint GLuint width
Definition at line 567 of file glext.h.
x
typedef GLfixed x
Definition at line 684 of file glext.h.
xoffset
typedef GLint GLint xoffset
Definition at line 1095 of file glext.h.
y
typedef GLuint y
Definition at line 567 of file glext.h.
yoffset
typedef GLint GLint GLint yoffset
Definition at line 1095 of file glext.h.
z
typedef GLfixed GLfixed z
Definition at line 567 of file glext.h.
zFar
typedef GLfloat GLfloat GLfloat GLfloat GLfloat zFar
Definition at line 658 of file glext.h.
zNear
typedef GLfloat GLfloat GLfloat GLfloat zNear
Definition at line 661 of file glext.h.
zoffset
typedef GLint GLint GLint GLint zoffset
Definition at line 1095 of file glext.h.
Function Documentation
glAlphaFuncxOES()
GL_API void GL_APIENTRY glAlphaFuncxOES (GLenum func, GLclampx ref)
glBindFramebufferOES()
GL_API void GL_APIENTRY glBindFramebufferOES (GLenum target, GLuint framebuffer)
Definition at line 96 of file gl_oes_framebuffer_object.c.
References glxx_client_BindFramebuffer().
 {
    glxx_client_BindFramebuffer(target, framebuffer);
 }
glBindRenderbufferOES()
GL_API void GL_APIENTRY glBindRenderbufferOES (GLenum target, GLuint renderbuffer)
Definition at line 66 of file gl_oes_framebuffer_object.c.
References glxx_client_BindRenderbuffer().
 {
    glxx_client_BindRenderbuffer(target, renderbuffer);
 }
glBindVertexArrayOES()
GL_API void GL_APIENTRY glBindVertexArrayOES (GLuint array)
GLbitfield()
typedef GLbitfield (GL_APIENTRYP PFNGLQUERYMATRIXXOESPROC)
glBlendEquationOES()
GL_API void GL_APIENTRY glBlendEquationOES (GLenum mode)
glBlendEquationSeparateOES()
GL_API void GL_APIENTRY glBlendEquationSeparateOES (GLenum modeRGB, GLenum modeAlpha)
glBlendFuncSeparateOES()
GL_API void GL_APIENTRY glBlendFuncSeparateOES (GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha)
GLboolean()
typedef GLboolean (GL_APIENTRYP PFNGLISRENDERBUFFEROESPROC)
glCheckFramebufferStatusOES()
GL_API GLenum GL_APIENTRY glCheckFramebufferStatusOES (GLenum target)
Definition at line 111 of file gl_oes_framebuffer_object.c.
References glxx_client_CheckFramebufferStatus().
 {
    return glxx_client_CheckFramebufferStatus(target);
 }
glClearColorxOES()
GL_API void GL_APIENTRY glClearColorxOES (GLclampx red, GLclampx green, GLclampx blue, GLclampx alpha)
glClearDepthfOES()
GL_API void GL_APIENTRY glClearDepthfOES (GLclampf depth)
glClearDepthxOES()
GL_API void GL_APIENTRY glClearDepthxOES (GLclampx depth)
glClipPlanefIMG()
GL_API void GL_APIENTRY glClipPlanefIMG (GLenum , const GLfloat *)
glClipPlanefOES()
GL_API void GL_APIENTRY glClipPlanefOES (GLenum plane, const GLfloat * equation)
glClipPlanexIMG()
GL_API void GL_APIENTRY glClipPlanexIMG (GLenum , const GLfixed *)
glClipPlanexOES()
GL_API void GL_APIENTRY glClipPlanexOES (GLenum plane, const GLfixed * equation)
glColor4xOES()
GL_API void GL_APIENTRY glColor4xOES (GLfixed red, GLfixed green, GLfixed blue, GLfixed alpha)
glCurrentPaletteMatrixOES()
GL_API void GL_APIENTRY glCurrentPaletteMatrixOES (GLuint matrixpaletteindex)
glDeleteFencesNV()
GL_API void GL_APIENTRY glDeleteFencesNV (GLsizei , const GLuint *)
glDeleteFramebuffersOES()
GL_API void GL_APIENTRY glDeleteFramebuffersOES (GLsizei n, const GLuint * framebuffers)
Definition at line 101 of file gl_oes_framebuffer_object.c.
References glxx_client_DeleteFramebuffers().
 {
    glxx_client_DeleteFramebuffers(n, framebuffers);
 }
glDeleteRenderbuffersOES()
GL_API void GL_APIENTRY glDeleteRenderbuffersOES (GLsizei n, const GLuint * renderbuffers)
Definition at line 71 of file gl_oes_framebuffer_object.c.
References glxx_client_DeleteRenderbuffers().
 {
    glxx_client_DeleteRenderbuffers(n, renderbuffers);
 }
glDeleteVertexArraysOES()
GL_API void GL_APIENTRY glDeleteVertexArraysOES (GLsizei n, const GLuint * arrays)
glDepthRangefOES()
GL_API void GL_APIENTRY glDepthRangefOES (GLclampf zNear, GLclampf zFar)
glDepthRangexOES()
GL_API void GL_APIENTRY glDepthRangexOES (GLclampx zNear, GLclampx zFar)
glDisableDriverControlQCOM()
GL_API void GL_APIENTRY glDisableDriverControlQCOM (GLuint driverControl)
glDiscardFramebufferEXT()
GL_API void GL_APIENTRY glDiscardFramebufferEXT (GLenum target, GLsizei numAttachments, const GLenum * attachments)
Definition at line 5478 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread))
    {
       RPC_CALL3_IN_CTRL(glDiscardFramebufferEXT_impl,
                 thread,
                 GLDISCARDFRAMEBUFFEREXT_ID,
                 RPC_ENUM(target),
                 RPC_SIZEI(numAttachments),
                 attachments,
                 numAttachments * sizeof(GLenum));
    }
 }
glDrawTexfOES()
GL_API void GL_APIENTRY glDrawTexfOES (GLfloat x, GLfloat y, GLfloat z, GLfloat width, GLfloat height)
Definition at line 77 of file gl_oes_draw_texture_client.c.
Referenced by glDrawTexiOES(), glDrawTexsOES(), and glDrawTexxOES().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL5(glDrawTexfOES_impl_11,
                 thread,
                 GLDRAWTEXFOES_ID_11,
                 RPC_FLOAT(x),
                 RPC_FLOAT(y),
                 RPC_FLOAT(z),
                 RPC_FLOAT(width),
                 RPC_FLOAT(height));
    }
 }
glDrawTexfvOES()
GL_API void GL_APIENTRY glDrawTexfvOES (const GLfloat * coords)
Definition at line 92 of file gl_oes_draw_texture_client.c.
 {
    glDrawTexfOES((GLfloat)coords[0],(GLfloat)coords[1],(GLfloat)coords[2], (GLfloat)coords[3],(GLfloat)coords[4]);
 }
glDrawTexiOES()
GL_API void GL_APIENTRY glDrawTexiOES (GLint x, GLint y, GLint z, GLint width, GLint height)
Definition at line 52 of file gl_oes_draw_texture_client.c.
References glDrawTexfOES().
 {
    glDrawTexfOES((GLfloat)x,(GLfloat)y,(GLfloat)x, (GLfloat)width,(GLfloat)height);
 }
glDrawTexivOES()
GL_API void GL_APIENTRY glDrawTexivOES (const GLint * coords)
Definition at line 67 of file gl_oes_draw_texture_client.c.
 {
    glDrawTexfOES((GLfloat)coords[0],(GLfloat)coords[1],(GLfloat)coords[2], (GLfloat)coords[3],(GLfloat)coords[4]);
 }
glDrawTexsOES()
GL_API void GL_APIENTRY glDrawTexsOES (GLshort x, GLshort y, GLshort z, GLshort width, GLshort height)
Definition at line 47 of file gl_oes_draw_texture_client.c.
References glDrawTexfOES().
 {
    glDrawTexfOES((GLfloat)x,(GLfloat)y,(GLfloat)x, (GLfloat)width,(GLfloat)height);
 }
glDrawTexsvOES()
GL_API void GL_APIENTRY glDrawTexsvOES (const GLshort * coords)
Definition at line 62 of file gl_oes_draw_texture_client.c.
 {
    glDrawTexfOES((GLfloat)coords[0],(GLfloat)coords[1],(GLfloat)coords[2], (GLfloat)coords[3],(GLfloat)coords[4]);
 }
glDrawTexxOES()
GL_API void GL_APIENTRY glDrawTexxOES (GLfixed x, GLfixed y, GLfixed z, GLfixed width, GLfixed height)
Definition at line 57 of file gl_oes_draw_texture_client.c.
References glDrawTexfOES().
 {
    glDrawTexfOES(fixed_to_float(x), fixed_to_float(y), fixed_to_float(x), fixed_to_float(width), fixed_to_float(height));
 }
glDrawTexxvOES()
GL_API void GL_APIENTRY glDrawTexxvOES (const GLfixed * coords)
Definition at line 72 of file gl_oes_draw_texture_client.c.
 {
    glDrawTexfOES(fixed_to_float(coords[0]), fixed_to_float(coords[1]), fixed_to_float(coords[2]), fixed_to_float(coords[3]), fixed_to_float(coords[4]));
 }
glEGLImageTargetRenderbufferStorageOES()
GL_API void GL_APIENTRY glEGLImageTargetRenderbufferStorageOES (GLenum target, GLeglImageOES image)
Definition at line 117 of file gl_oes_egl_image_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       /* OES_framebuffer_object not supported for GLES1.1 */
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       if (state->error == GL_NO_ERROR)
          state->error = GL_INVALID_OPERATION;
    }
    else if (IS_OPENGLES_20(thread)) {
 #if EGL_BRCM_global_image
       if ((uintptr_t)image & (1u << 31)) {
          GLuint global_image_id[2];
          if (check_global_image_egl_image(global_image_id, image, thread, true)) {
             RPC_CALL3(glGlobalImageRenderbufferStorageOES_impl_20,
                       thread,
                       GLGLOBALIMAGERENDERBUFFERSTORAGEOES_ID_20,
                       RPC_ENUM(target),
                       RPC_UINT(global_image_id[0]),
                       RPC_UINT(global_image_id[1]));
          } else {
             set_error(GLXX_GET_CLIENT_STATE(thread), GL_INVALID_VALUE);
          }
       } else {
 #endif
          RPC_CALL2(glEGLImageTargetRenderbufferStorageOES_impl_20,
                    thread,
                    GLEGLIMAGETARGETRENDERBUFFERSTORAGEOES_ID_20,
                    RPC_ENUM(target),
                    RPC_EGLID(image));
 #if EGL_BRCM_global_image
       }
 #endif
    }
 }
glEGLImageTargetTexture2DOES()
GL_API void GL_APIENTRY glEGLImageTargetTexture2DOES (GLenum target, GLeglImageOES image)
Definition at line 85 of file gl_oes_egl_image_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
 #if EGL_BRCM_global_image
       if ((uintptr_t)image & (1u << 31)) {
          GLuint global_image_id[2];
          if (check_global_image_egl_image(global_image_id, image, thread, false)) {
             RPC_CALL3(glGlobalImageTexture2DOES_impl,
                       thread,
                       GLGLOBALIMAGETEXTURE2DOES_ID,
                       RPC_ENUM(target),
                       RPC_UINT(global_image_id[0]),
                       RPC_UINT(global_image_id[1]));
          } else {
             set_error(GLXX_GET_CLIENT_STATE(thread), GL_INVALID_VALUE);
          }
       } else {
 #endif
          RPC_CALL2(glEGLImageTargetTexture2DOES_impl,
                    thread,
                    GLEGLIMAGETARGETTEXTURE2DOES_ID,
                    RPC_ENUM(target),
                    RPC_EGLID(image));
          RPC_FLUSH(thread);
 #if EGL_BRCM_global_image
       }
 #endif
    }
 }
glEnableDriverControlQCOM()
GL_API void GL_APIENTRY glEnableDriverControlQCOM (GLuint driverControl)
glEndTilingQCOM()
GL_API void GL_APIENTRY glEndTilingQCOM (GLbitfield preserveMask)
GLenum()
typedef GLenum (GL_APIENTRYP PFNGLCHECKFRAMEBUFFERSTATUSOESPROC)
glExtGetBufferPointervQCOM()
GL_API void GL_APIENTRY glExtGetBufferPointervQCOM (GLenum target, GLvoid ** params)
glExtGetBuffersQCOM()
GL_API void GL_APIENTRY glExtGetBuffersQCOM (GLuint * buffers, GLint maxBuffers, GLint * numBuffers)
glExtGetFramebuffersQCOM()
GL_API void GL_APIENTRY glExtGetFramebuffersQCOM (GLuint * framebuffers, GLint maxFramebuffers, GLint * numFramebuffers)
glExtGetProgramBinarySourceQCOM()
GL_API void GL_APIENTRY glExtGetProgramBinarySourceQCOM (GLuint program, GLenum shadertype, GLchar * source, GLint * length)
glExtGetProgramsQCOM()
GL_API void GL_APIENTRY glExtGetProgramsQCOM (GLuint * programs, GLint maxPrograms, GLint * numPrograms)
glExtGetRenderbuffersQCOM()
GL_API void GL_APIENTRY glExtGetRenderbuffersQCOM (GLuint * renderbuffers, GLint maxRenderbuffers, GLint * numRenderbuffers)
glExtGetShadersQCOM()
GL_API void GL_APIENTRY glExtGetShadersQCOM (GLuint * shaders, GLint maxShaders, GLint * numShaders)
glExtGetTexLevelParameterivQCOM()
GL_API void GL_APIENTRY glExtGetTexLevelParameterivQCOM (GLuint texture, GLenum face, GLint level, GLenum pname, GLint * params)
glExtGetTexSubImageQCOM()
GL_API void GL_APIENTRY glExtGetTexSubImageQCOM (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, GLvoid * texels)
glExtGetTexturesQCOM()
GL_API void GL_APIENTRY glExtGetTexturesQCOM (GLuint * textures, GLint maxTextures, GLint * numTextures)
glExtIsProgramBinaryQCOM()
GL_API GLboolean GL_APIENTRY glExtIsProgramBinaryQCOM (GLuint program)
glExtTexObjectStateOverrideiQCOM()
GL_API void GL_APIENTRY glExtTexObjectStateOverrideiQCOM (GLenum target, GLenum pname, GLint param)
glFinishFenceNV()
GL_API void GL_APIENTRY glFinishFenceNV (GLuint)
glFogxOES()
GL_API void GL_APIENTRY glFogxOES (GLenum pname, GLfixed param)
glFogxvOES()
GL_API void GL_APIENTRY glFogxvOES (GLenum pname, const GLfixed * params)
glFramebufferRenderbufferOES()
GL_API void GL_APIENTRY glFramebufferRenderbufferOES (GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer)
Definition at line 116 of file gl_oes_framebuffer_object.c.
References glxx_client_FramebufferRenderbuffer().
 {
    glxx_client_FramebufferRenderbuffer(target, attachment, renderbuffertarget, renderbuffer);
 }
glFramebufferTexture2DMultisampleIMG()
GL_API void GL_APIENTRY glFramebufferTexture2DMultisampleIMG (GLenum , GLenum , GLenum , GLuint , GLint , GLsizei)
glFramebufferTexture2DOES()
GL_API void GL_APIENTRY glFramebufferTexture2DOES (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
Definition at line 121 of file gl_oes_framebuffer_object.c.
References glxx_client_FramebufferTexture2D().
 {
    glxx_client_FramebufferTexture2D(target, attachment, textarget, texture, level);
 }
glFrustumfOES()
GL_API void GL_APIENTRY glFrustumfOES (GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar)
glFrustumxOES()
GL_API void GL_APIENTRY glFrustumxOES (GLfixed left, GLfixed right, GLfixed bottom, GLfixed top, GLfixed zNear, GLfixed zFar)
glGenerateMipmapOES()
GL_API void GL_APIENTRY glGenerateMipmapOES (GLenum target)
Definition at line 131 of file gl_oes_framebuffer_object.c.
References glxx_client_GenerateMipmap().
 {
    glxx_client_GenerateMipmap(target);
 }
glGenFencesNV()
GL_API void GL_APIENTRY glGenFencesNV (GLsizei , GLuint *)
glGenFramebuffersOES()
GL_API void GL_APIENTRY glGenFramebuffersOES (GLsizei n, GLuint * framebuffers)
Definition at line 106 of file gl_oes_framebuffer_object.c.
References glxx_client_GenFramebuffers().
 {
    glxx_client_GenFramebuffers(n, framebuffers);
 }
glGenRenderbuffersOES()
GL_API void GL_APIENTRY glGenRenderbuffersOES (GLsizei n, GLuint * renderbuffers)
Definition at line 76 of file gl_oes_framebuffer_object.c.
References glxx_client_GenRenderbuffers().
 {
    glxx_client_GenRenderbuffers(n, renderbuffers);
 }
glGenVertexArraysOES()
GL_API void GL_APIENTRY glGenVertexArraysOES (GLsizei n, GLuint * arrays)
glGetBufferPointervOES()
GL_API void GL_APIENTRY glGetBufferPointervOES (GLenum target, GLenum pname, GLvoid ** params)
Definition at line 157 of file gl_oes_map_buffer.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    params[0] = (void *)0;
    if (IS_OPENGLES_11_OR_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       if(target != GL_ARRAY_BUFFER && target != GL_ELEMENT_ARRAY_BUFFER)
       {
          glxx_set_error(state, GL_INVALID_ENUM);
       }
       else if(pname != GL_BUFFER_MAP_POINTER_OES)
       {
          glxx_set_error(state, GL_INVALID_ENUM);
       }
       else
       {
          GLXX_BUFFER_INFO_T buffer;
          glxx_buffer_info_get(state, target, &buffer);
          if(buffer.id !=0)
          {
             params[0] = (void *)buffer.mapped_pointer;
          }
       }
    }
    /*
       RPC_CALL3_OUT_CTRL(glGetBufferPointervOES_impl,
                          thread,
                          GLGETBUFFERPOINTERVOES_ID,
                          RPC_ENUM(target),
                          RPC_ENUM(pname),
                          params);
    */
 }
glGetClipPlanefOES()
GL_API void GL_APIENTRY glGetClipPlanefOES (GLenum pname, GLfloat eqn[4])
glGetClipPlanexOES()
GL_API void GL_APIENTRY glGetClipPlanexOES (GLenum pname, GLfixed eqn[4])
glGetDriverControlsQCOM()
GL_API void GL_APIENTRY glGetDriverControlsQCOM (GLint * num, GLsizei size, GLuint * driverControls)
glGetDriverControlStringQCOM()
GL_API void GL_APIENTRY glGetDriverControlStringQCOM (GLuint driverControl, GLsizei bufSize, GLsizei * length, GLchar * driverControlString)
glGetFenceivNV()
GL_API void GL_APIENTRY glGetFenceivNV (GLuint , GLenum , GLint *)
glGetFixedvOES()
GL_API void GL_APIENTRY glGetFixedvOES (GLenum pname, GLfixed * params)
glGetFramebufferAttachmentParameterivOES()
GL_API void GL_APIENTRY glGetFramebufferAttachmentParameterivOES (GLenum target, GLenum attachment, GLenum pname, GLint * params)
Definition at line 126 of file gl_oes_framebuffer_object.c.
References glxx_client_GetFramebufferAttachmentParameteriv().
 {
    glxx_client_GetFramebufferAttachmentParameteriv(target, attachment, pname, params);
 }
glGetLightxvOES()
GL_API void GL_APIENTRY glGetLightxvOES (GLenum light, GLenum pname, GLfixed * params)
glGetMaterialxvOES()
GL_API void GL_APIENTRY glGetMaterialxvOES (GLenum face, GLenum pname, GLfixed * params)
glGetRenderbufferParameterivOES()
GL_API void GL_APIENTRY glGetRenderbufferParameterivOES (GLenum target, GLenum pname, GLint * params)
Definition at line 86 of file gl_oes_framebuffer_object.c.
References glxx_client_GetRenderbufferParameteriv().
 {
    glxx_client_GetRenderbufferParameteriv(target, pname, params);
 }
glGetTexEnvxvOES()
GL_API void GL_APIENTRY glGetTexEnvxvOES (GLenum env, GLenum pname, GLfixed * params)
glGetTexGenfvOES()
GL_API void GL_APIENTRY glGetTexGenfvOES (GLenum coord, GLenum pname, GLfloat * params)
glGetTexGenivOES()
GL_API void GL_APIENTRY glGetTexGenivOES (GLenum coord, GLenum pname, GLint * params)
glGetTexGenxvOES()
GL_API void GL_APIENTRY glGetTexGenxvOES (GLenum coord, GLenum pname, GLfixed * params)
glGetTexParameterxvOES()
GL_API void GL_APIENTRY glGetTexParameterxvOES (GLenum target, GLenum pname, GLfixed * params)
glInsertEventMarkerEXT()
GL_API void GL_APIENTRY glInsertEventMarkerEXT (GLsizei length, const GLchar * marker)
Definition at line 45 of file ext_gl_debug_marker.c.
 {
    /* Do nothing.
       When SpyHook is enabled, it will trap this function and pass to SpyTool.
       That's all that is needed
    */
    UNUSED(length);
    UNUSED(marker);
 }
glIsFenceNV()
GL_API GLboolean GL_APIENTRY glIsFenceNV (GLuint)
glIsFramebufferOES()
GL_API GLboolean GL_APIENTRY glIsFramebufferOES (GLuint framebuffer)
Definition at line 91 of file gl_oes_framebuffer_object.c.
References glxx_client_IsFramebuffer().
 {
    return glxx_client_IsFramebuffer(framebuffer);
 }
glIsRenderbufferOES()
GL_API GLboolean GL_APIENTRY glIsRenderbufferOES (GLuint renderbuffer)
Definition at line 61 of file gl_oes_framebuffer_object.c.
References glxx_client_IsRenderbuffer().
 {
    return glxx_client_IsRenderbuffer(renderbuffer);
 }
glIsVertexArrayOES()
GL_API GLboolean GL_APIENTRY glIsVertexArrayOES (GLuint array)
glLightModelxOES()
GL_API void GL_APIENTRY glLightModelxOES (GLenum pname, GLfixed param)
glLightModelxvOES()
GL_API void GL_APIENTRY glLightModelxvOES (GLenum pname, const GLfixed * params)
glLightxOES()
GL_API void GL_APIENTRY glLightxOES (GLenum light, GLenum pname, GLfixed param)
glLightxvOES()
GL_API void GL_APIENTRY glLightxvOES (GLenum light, GLenum pname, const GLfixed * params)
glLineWidthxOES()
GL_API void GL_APIENTRY glLineWidthxOES (GLfixed width)
glLoadMatrixxOES()
GL_API void GL_APIENTRY glLoadMatrixxOES (const GLfixed * m)
glLoadPaletteFromModelViewMatrixOES()
GL_API void GL_APIENTRY glLoadPaletteFromModelViewMatrixOES (void)
glMapBufferOES()
GL_API void* GL_APIENTRY glMapBufferOES (GLenum target, GLenum access)
Definition at line 45 of file gl_oes_map_buffer.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    void *pointer = 0;
    if (IS_OPENGLES_11_OR_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       if(target != GL_ARRAY_BUFFER && target != GL_ELEMENT_ARRAY_BUFFER)
       {
          glxx_set_error(state, GL_INVALID_ENUM);
       }
       else if(access != GL_WRITE_ONLY_OES)
       {
          glxx_set_error(state, GL_INVALID_ENUM);
       }
       else
       {
          GLXX_BUFFER_INFO_T buffer;
          glxx_buffer_info_get(state, target, &buffer);
          if(buffer.id !=0 && buffer.cached_size > 0)
          {
             if(buffer.mapped_pointer != 0)
             {
                /* already mapped */
                glxx_set_error(state, GL_INVALID_OPERATION);
             }
             else
             {
                pointer = khrn_platform_malloc(buffer.cached_size,"glxx_mapped_buffer");
                if(pointer != 0)
                {
                   buffer.mapped_pointer = pointer;
                   buffer.mapped_size = buffer.cached_size;
                }
                else
                {
                   buffer.mapped_pointer = 0;
                   buffer.mapped_size = 0;
                   glxx_set_error(state, GL_OUT_OF_MEMORY);
                }
                glxx_buffer_info_set(state, target, &buffer);
             }
          }
          else
          {
             glxx_set_error(state, GL_INVALID_OPERATION);
          }
       }
    }
    /*
    RPC_CALL3_OUT_CTRL(glMapBufferOES_impl,
                       thread,
                       GLMAPBUFFEROES_ID,
                       RPC_ENUM(target),
                       RPC_ENUM(access),
                       &pointer);
    */
    return pointer;
 }
glMaterialxOES()
GL_API void GL_APIENTRY glMaterialxOES (GLenum face, GLenum pname, GLfixed param)
glMaterialxvOES()
GL_API void GL_APIENTRY glMaterialxvOES (GLenum face, GLenum pname, const GLfixed * params)
glMatrixIndexPointerOES()
GL_API void GL_APIENTRY glMatrixIndexPointerOES (GLint size, GLenum type, GLsizei stride, const GLvoid * pointer)
glMultiDrawArraysEXT()
GL_API void GL_APIENTRY glMultiDrawArraysEXT (GLenum , GLint * , GLsizei * , GLsizei)
glMultiDrawElementsEXT()
GL_API void GL_APIENTRY glMultiDrawElementsEXT (GLenum , const GLsizei * , GLenum , const GLvoid ** , GLsizei)
glMultiTexCoord4xOES()
GL_API void GL_APIENTRY glMultiTexCoord4xOES (GLenum target, GLfixed s, GLfixed t, GLfixed r, GLfixed q)
glMultMatrixxOES()
GL_API void GL_APIENTRY glMultMatrixxOES (const GLfixed * m)
glNormal3xOES()
GL_API void GL_APIENTRY glNormal3xOES (GLfixed nx, GLfixed ny, GLfixed nz)
glOrthofOES()
GL_API void GL_APIENTRY glOrthofOES (GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar)
glOrthoxOES()
GL_API void GL_APIENTRY glOrthoxOES (GLfixed left, GLfixed right, GLfixed bottom, GLfixed top, GLfixed zNear, GLfixed zFar)
glPointParameterxOES()
GL_API void GL_APIENTRY glPointParameterxOES (GLenum pname, GLfixed param)
glPointParameterxvOES()
GL_API void GL_APIENTRY glPointParameterxvOES (GLenum pname, const GLfixed * params)
glPointSizexOES()
GL_API void GL_APIENTRY glPointSizexOES (GLfixed size)
glPolygonOffsetxOES()
GL_API void GL_APIENTRY glPolygonOffsetxOES (GLfixed factor, GLfixed units)
glPopGroupMarkerEXT()
GL_API void GL_APIENTRY glPopGroupMarkerEXT (void)
Definition at line 65 of file ext_gl_debug_marker.c.
 {
    /* Do nothing.
       When SpyHook is enabled, it will trap this function and pass to SpyTool.
       That's all that is needed
    */
 }
glPushGroupMarkerEXT()
GL_API void GL_APIENTRY glPushGroupMarkerEXT (GLsizei length, const GLchar * marker)
Definition at line 55 of file ext_gl_debug_marker.c.
 {
    /* Do nothing.
       When SpyHook is enabled, it will trap this function and pass to SpyTool.
       That's all that is needed
    */
    UNUSED(length);
    UNUSED(marker);
 }
glQueryMatrixxOES()
GL_API GLbitfield GL_APIENTRY glQueryMatrixxOES (GLfixed mantissa[16], GLint exponent[16])
Definition at line 43 of file gl_oes_query_matrix_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       int i;
       RPC_CALL1_OUT_CTRL(glQueryMatrixxOES_impl_11,
                             thread,
                             GLQUERYMATRIXXOES_ID_11,
                             mantissa);
       for(i=0;i<16;i++)
          exponent[i] = 0;
       return 0;
    }
    return 0xff; /* all components invalid */
 }
glRenderbufferStorageMultisampleAPPLE()
GL_API void GL_APIENTRY glRenderbufferStorageMultisampleAPPLE (GLenum , GLsizei , GLenum , GLsizei , GLsizei)
glRenderbufferStorageMultisampleIMG()
GL_API void GL_APIENTRY glRenderbufferStorageMultisampleIMG (GLenum , GLsizei , GLenum , GLsizei , GLsizei)
glRenderbufferStorageOES()
GL_API void GL_APIENTRY glRenderbufferStorageOES (GLenum target, GLenum internalformat, GLsizei width, GLsizei height)
Definition at line 81 of file gl_oes_framebuffer_object.c.
References glxx_client_RenderbufferStorage().
 {
    glxx_client_RenderbufferStorage(target, internalformat, width, height);
 }
glResolveMultisampleFramebufferAPPLE()
GL_API void GL_APIENTRY glResolveMultisampleFramebufferAPPLE (void)
glRotatexOES()
GL_API void GL_APIENTRY glRotatexOES (GLfixed angle, GLfixed x, GLfixed y, GLfixed z)
glSampleCoveragexOES()
GL_API void GL_APIENTRY glSampleCoveragexOES (GLclampx value, GLboolean invert)
glScalexOES()
GL_API void GL_APIENTRY glScalexOES (GLfixed x, GLfixed y, GLfixed z)
glSetFenceNV()
GL_API void GL_APIENTRY glSetFenceNV (GLuint , GLenum)
glStartTilingQCOM()
GL_API void GL_APIENTRY glStartTilingQCOM (GLuint x, GLuint y, GLuint width, GLuint height, GLbitfield preserveMask)
glTestFenceNV()
GL_API GLboolean GL_APIENTRY glTestFenceNV (GLuint)
glTexEnvxOES()
GL_API void GL_APIENTRY glTexEnvxOES (GLenum target, GLenum pname, GLfixed param)
glTexEnvxvOES()
GL_API void GL_APIENTRY glTexEnvxvOES (GLenum target, GLenum pname, const GLfixed * params)
glTexGenfOES()
GL_API void GL_APIENTRY glTexGenfOES (GLenum coord, GLenum pname, GLfloat param)
glTexGenfvOES()
GL_API void GL_APIENTRY glTexGenfvOES (GLenum coord, GLenum pname, const GLfloat * params)
glTexGeniOES()
GL_API void GL_APIENTRY glTexGeniOES (GLenum coord, GLenum pname, GLint param)
glTexGenivOES()
GL_API void GL_APIENTRY glTexGenivOES (GLenum coord, GLenum pname, const GLint * params)
glTexGenxOES()
GL_API void GL_APIENTRY glTexGenxOES (GLenum coord, GLenum pname, GLfixed param)
glTexGenxvOES()
GL_API void GL_APIENTRY glTexGenxvOES (GLenum coord, GLenum pname, const GLfixed * params)
glTexParameterxOES()
GL_API void GL_APIENTRY glTexParameterxOES (GLenum target, GLenum pname, GLfixed param)
glTexParameterxvOES()
GL_API void GL_APIENTRY glTexParameterxvOES (GLenum target, GLenum pname, const GLfixed * params)
glTranslatexOES()
GL_API void GL_APIENTRY glTranslatexOES (GLfixed x, GLfixed y, GLfixed z)
glUnmapBufferOES()
GL_API GLboolean GL_APIENTRY glUnmapBufferOES (GLenum target)
Definition at line 110 of file gl_oes_map_buffer.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    GLboolean success = GL_FALSE;
    if (IS_OPENGLES_11_OR_20(thread)) {
       //use buffer sub data to flush through
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       if(target != GL_ARRAY_BUFFER && target != GL_ELEMENT_ARRAY_BUFFER)
       {
          glxx_set_error(state, GL_INVALID_ENUM);
       }
       else
       {
          GLXX_BUFFER_INFO_T buffer;
          glxx_buffer_info_get(state, target, &buffer);
          if(buffer.id !=0)
          {
             if(buffer.mapped_pointer)
             {
                void * p = buffer.mapped_pointer;
                GLsizeiptr size = buffer.mapped_size;
                buffer.mapped_pointer = 0;
                buffer.mapped_size = 0;
                glxx_buffer_info_set(state, target, &buffer);
                glBufferSubData (target, 0, size, p);
                khrn_platform_free(p);
             }
          }
       }
    }
    /*
    if (IS_OPENGLES_11_OR_20(thread)) {
       success = RPC_BOOLEAN_RES(RPC_CALL1_RES(glUnmapBufferOES_impl,
                          thread,
                          GLUNMAPBUFFEROES_ID,
                          RPC_ENUM(target)));
    */
    return success;
 }
glWeightPointerOES()
GL_API void GL_APIENTRY glWeightPointerOES (GLint size, GLenum type, GLsizei stride, const GLvoid * pointer)
void()
typedef void (GL_APIENTRYP PFNGLBLENDEQUATIONSEPARATEOESPROC)