VideoCore Library: Ports
Ports
Classes
struct MMAL_PORT_T
Typedefs
typedef struct MMAL_PORT_T MMAL_PORT_T
typedef void(* MMAL_PORT_BH_CB_T) (MMAL_PORT_T *port, MMAL_BUFFER_HEADER_T *buffer)
Enumerations
enum MMAL_PORT_TYPE_T {
MMAL_PORT_TYPE_UNKNOWN = 0, MMAL_PORT_TYPE_CONTROL, MMAL_PORT_TYPE_INPUT, MMAL_PORT_TYPE_OUTPUT,
MMAL_PORT_TYPE_CLOCK, MMAL_PORT_TYPE_INVALID = 0xffffffff
}
Functions
MMAL_STATUS_T mmal_port_format_commit (MMAL_PORT_T *port)
MMAL_STATUS_T mmal_port_enable (MMAL_PORT_T *port, MMAL_PORT_BH_CB_T cb)
MMAL_STATUS_T mmal_port_disable (MMAL_PORT_T *port)
MMAL_STATUS_T mmal_port_flush (MMAL_PORT_T *port)
MMAL_STATUS_T mmal_port_parameter_set (MMAL_PORT_T *port, const MMAL_PARAMETER_HEADER_T *param)
MMAL_STATUS_T mmal_port_parameter_get (MMAL_PORT_T *port, MMAL_PARAMETER_HEADER_T *param)
MMAL_STATUS_T mmal_port_send_buffer (MMAL_PORT_T *port, MMAL_BUFFER_HEADER_T *buffer)
MMAL_STATUS_T mmal_port_connect (MMAL_PORT_T *port, MMAL_PORT_T *other_port)
MMAL_STATUS_T mmal_port_disconnect (MMAL_PORT_T *port)
uint8_t * mmal_port_payload_alloc (MMAL_PORT_T *port, uint32_t payload_size)
void mmal_port_payload_free (MMAL_PORT_T *port, uint8_t *payload)
MMAL_STATUS_T mmal_port_event_get (MMAL_PORT_T *port, MMAL_BUFFER_HEADER_T **buffer, uint32_t event)
Port capabilities
The following flags describe the capabilities advertised by a port
#define MMAL_PORT_CAPABILITY_PASSTHROUGH 0x01
#define MMAL_PORT_CAPABILITY_ALLOCATION 0x02
#define MMAL_PORT_CAPABILITY_SUPPORTS_EVENT_FORMAT_CHANGE 0x04
Detailed Description
Definition of a MMAL port and its associated API
Macro Definition Documentation
MMAL_PORT_CAPABILITY_ALLOCATION
#define MMAL_PORT_CAPABILITY_ALLOCATION 0x02
The port wants to allocate the buffer payloads. This signals a preference that payload allocation should be done on this port for efficiency reasons.
Definition at line 64 of file mmal_port.h.
Referenced by mmal_connection_create().
MMAL_PORT_CAPABILITY_PASSTHROUGH
#define MMAL_PORT_CAPABILITY_PASSTHROUGH 0x01
The port is pass-through and doesn't need buffer headers allocated
Definition at line 61 of file mmal_port.h.
Referenced by mmal_connection_create(), mmal_connection_enable(), and mmal_port_send_buffer().
MMAL_PORT_CAPABILITY_SUPPORTS_EVENT_FORMAT_CHANGE
#define MMAL_PORT_CAPABILITY_SUPPORTS_EVENT_FORMAT_CHANGE 0x04
The port supports format change events. This applies to input ports and is used to let the client know whether the port supports being reconfigured via a format change event (i.e. without having to disable the port).
Definition at line 68 of file mmal_port.h.
Referenced by mmal_connection_event_format_changed().
Typedef Documentation
MMAL_PORT_BH_CB_T
typedef void(* MMAL_PORT_BH_CB_T) (MMAL_PORT_T *port, MMAL_BUFFER_HEADER_T *buffer)
Definition of the callback used by a port to send a MMAL_BUFFER_HEADER_T back to the user.
Parameters
port The port sending the buffer header.
buffer The buffer header being sent.
Definition at line 132 of file mmal_port.h.
MMAL_PORT_T
typedef struct MMAL_PORT_T MMAL_PORT_T
Definition of a port. A port is the entity that is exposed by components to receive or transmit buffer headers (MMAL_BUFFER_HEADER_T). A port is defined by its MMAL_ES_FORMAT_T.
It may be possible to override the buffer requirements of a port by using the MMAL_PARAMETER_BUFFER_REQUIREMENTS parameter.
Enumeration Type Documentation
MMAL_PORT_TYPE_T
enum MMAL_PORT_TYPE_T
List of port types
Enumerator
MMAL_PORT_TYPE_UNKNOWN
Unknown port type
MMAL_PORT_TYPE_CONTROL
Control port
MMAL_PORT_TYPE_INPUT
Input port
MMAL_PORT_TYPE_OUTPUT
Output port
MMAL_PORT_TYPE_CLOCK
Clock port
MMAL_PORT_TYPE_INVALID
Dummy value to force 32bit enum
Definition at line 45 of file mmal_port.h.
 {
    MMAL_PORT_TYPE_UNKNOWN = 0,
    MMAL_PORT_TYPE_CONTROL,
    MMAL_PORT_TYPE_INPUT,
    MMAL_PORT_TYPE_OUTPUT,
    MMAL_PORT_TYPE_CLOCK,
    MMAL_PORT_TYPE_INVALID = 0xffffffff
 } MMAL_PORT_TYPE_T;
Function Documentation
mmal_port_connect()
MMAL_STATUS_T mmal_port_connect (MMAL_PORT_T * port, MMAL_PORT_T * other_port)
Connect an output port to an input port.
When connected and enabled, buffers will automatically progress from the output port to the input port when they become available, and released back to the output port when no longer required by the input port.
Ports can be given either way around, but one must be an output port and the other must be an input port. Neither can be connected or enabled already. The format of the output port will be applied to the input port on connection.
Parameters
port One of the ports to connect.
other_port The other port to connect.
Returns
MMAL_SUCCESS on success.
Connect an output port to an input port.
Definition at line 935 of file mmal_port.c.
References MMAL_PORT_PRIVATE_CORE_T::connected_port, MMAL_PORT_PRIVATE_T::core, MMAL_PORT_PRIVATE_CORE_T::core_owns_connection, MMAL_PORT_T::is_enabled, LOCK_CONNECTION, LOG_ERROR, LOG_TRACE, MMAL_EINVAL, MMAL_EISCONN, MMAL_ENOSYS, MMAL_PORT_TYPE_CLOCK, MMAL_PORT_TYPE_OUTPUT, MMAL_SUCCESS, MMAL_PORT_T::name, NULL, MMAL_PORT_PRIVATE_T::pf_connect, MMAL_PORT_MODULE_T::port, MMAL_PORT_T::priv, status, MMAL_PORT_T::type, and UNLOCK_CONNECTION.
Referenced by mmal_connection_create().
 {
    MMAL_PORT_PRIVATE_CORE_T* core;
    MMAL_PORT_PRIVATE_CORE_T* other_core;
    MMAL_STATUS_T status = MMAL_SUCCESS;
    MMAL_PORT_T* output_port = NULL;
    if (!port || !port->priv || !other_port || !other_port->priv)
    {
       LOG_ERROR("invalid port");
       return MMAL_EINVAL;
    }
    if ((port->type == MMAL_PORT_TYPE_CLOCK) && (port->type != other_port->type))
    {
       LOG_ERROR("invalid port connection");
       return MMAL_EINVAL;
    }
    LOG_TRACE("connecting %s(%p) to %s(%p)", port->name, port, other_port->name, other_port);
    if (!port->priv->pf_connect || !other_port->priv->pf_connect)
    {
       LOG_ERROR("at least one pf_connect is NULL");
       return MMAL_ENOSYS;
    }
    core = port->priv->core;
    other_core = other_port->priv->core;
    LOCK_CONNECTION(port);
    if (core->connected_port)
    {
       LOG_ERROR("port %p is already connected", port);
       UNLOCK_CONNECTION(port);
       return MMAL_EISCONN;
    }
    if (port->is_enabled)
    {
       LOG_ERROR("port %p should not be enabled", port);
       UNLOCK_CONNECTION(port);
       return MMAL_EINVAL;
    }
    LOCK_CONNECTION(other_port);
    if (other_core->connected_port)
    {
       LOG_ERROR("port %p is already connected", other_port);
       status = MMAL_EISCONN;
       goto finish;
    }
    if (other_port->is_enabled)
    {
       LOG_ERROR("port %p should not be enabled", other_port);
       status = MMAL_EINVAL;
       goto finish;
    }
    core->connected_port = other_port;
    other_core->connected_port = port;
    core->core_owns_connection = 0;
    other_core->core_owns_connection = 0;
    /* Check to see if the port will manage the connection on its own. If not then the core
     * will manage it. */
    output_port = port->type == MMAL_PORT_TYPE_OUTPUT ? port : other_port;
    if (output_port->priv->pf_connect(port, other_port) == MMAL_SUCCESS)
       goto finish;
    core->core_owns_connection = 1;
    other_core->core_owns_connection = 1;
 finish:
    UNLOCK_CONNECTION(other_port);
    UNLOCK_CONNECTION(port);
    return status;
 }
mmal_port_disable()
MMAL_STATUS_T mmal_port_disable (MMAL_PORT_T * port)
Disable processing on a port
Disabling a port will stop all processing on this port and return all (non-processed) buffer headers to the client.
If this is a connected output port, the input port to which it is connected shall also be disabled. Any buffer pool shall be released.
Parameters
port port to disable
Returns
MMAL_SUCCESS on success
Disable processing on a port
Definition at line 575 of file mmal_port.c.
References MMAL_PORT_T::component, MMAL_PORT_PRIVATE_CORE_T::connected_port, MMAL_PORT_PRIVATE_T::core, MMAL_PORT_T::index, MMAL_PORT_T::is_enabled, LOCK_CONNECTION, LOG_ERROR, LOG_TRACE, MMAL_EINVAL, MMAL_ENOSYS, MMAL_PORT_TYPE_INPUT, MMAL_COMPONENT_T::name, MMAL_PORT_T::name, MMAL_PORT_PRIVATE_T::pf_disable, MMAL_PORT_T::priv, status, MMAL_PORT_T::type, and UNLOCK_CONNECTION.
Referenced by check_disable_port(), mmal_connection_disable(), mmal_port_pool_destroy(), and mmal_wrapper_port_disable().
 {
    MMAL_STATUS_T status;
    MMAL_PORT_T *connected_port;
    MMAL_PORT_PRIVATE_CORE_T *core;
    if (!port || !port->priv)
       return MMAL_EINVAL;
    LOG_TRACE("%s(%i:%i) port %p", port->component->name,
              (int)port->type, (int)port->index, port);
    if (!port->priv->pf_disable)
       return MMAL_ENOSYS;
    core = port->priv->core;
    LOCK_CONNECTION(port);
    connected_port = core->connected_port;
    /* Sanity checking */
    if (!port->is_enabled)
    {
       UNLOCK_CONNECTION(port);
       LOG_ERROR("port %s(%p) is not enabled", port->name, port);
       return MMAL_EINVAL;
    }
    if (connected_port)
       LOCK_CONNECTION(connected_port);
    /* Disable the output port of a connection first */
    if (connected_port && connected_port->type != MMAL_PORT_TYPE_INPUT)
    {
       status = mmal_port_disable_internal(connected_port);
       if (status != MMAL_SUCCESS)
       {
          LOG_ERROR("failed to disable connected port (%s)%p (%s)", connected_port->name,
             connected_port, mmal_status_to_string(status));
          goto end;
       }
    }
    status = mmal_port_disable_internal(port);
    if (status != MMAL_SUCCESS)
    {
       LOG_ERROR("failed to disable port (%s)%p", port->name, port);
       goto end;
    }
    /* Disable the input port of a connection last */
    if (connected_port && connected_port->type == MMAL_PORT_TYPE_INPUT)
    {
       status = mmal_port_disable_internal(connected_port);
       if (status != MMAL_SUCCESS)
       {
          LOG_ERROR("failed to disable connected port (%s)%p (%s)", connected_port->name,
             connected_port, mmal_status_to_string(status));
          goto end;
       }
    }
    if (connected_port)
    {
       status = mmal_port_connection_disable(port, connected_port);
       if (status != MMAL_SUCCESS)
          LOG_ERROR("failed to disable connection (%s)%p (%s)", port->name,
             port, mmal_status_to_string(status));
    }
 end:
    if (connected_port)
       UNLOCK_CONNECTION(connected_port);
    UNLOCK_CONNECTION(port);
    return status;
 }
mmal_port_disconnect()
MMAL_STATUS_T mmal_port_disconnect (MMAL_PORT_T * port)
Disconnect a connected port.
If the port is not connected, an error will be returned. Otherwise, if the ports are enabled, they will be disabled and any buffer pool created will be freed.
Parameters
port The ports to disconnect.
Returns
MMAL_SUCCESS on success.
Disconnect a connected port.
Definition at line 1016 of file mmal_port.c.
References MMAL_PORT_PRIVATE_CORE_T::connected_port, MMAL_PORT_PRIVATE_T::core, MMAL_PORT_T::is_enabled, LOCK_CONNECTION, LOG_DEBUG, LOG_ERROR, LOG_TRACE, MMAL_EINVAL, MMAL_ENOTCONN, MMAL_PORT_TYPE_INPUT, MMAL_PORT_TYPE_OUTPUT, MMAL_SUCCESS, MMAL_PORT_T::name, MMAL_PORT_MODULE_T::port, MMAL_PORT_T::priv, status, MMAL_PORT_T::type, and UNLOCK_CONNECTION.
 {
    MMAL_PORT_PRIVATE_CORE_T* core;
    MMAL_PORT_T* other_port;
    MMAL_STATUS_T status = MMAL_SUCCESS;
    if (!port || !port->priv)
    {
       LOG_ERROR("invalid port");
       return MMAL_EINVAL;
    }
    LOG_TRACE("%s(%p)", port->name, port);
    LOCK_CONNECTION(port);
    core = port->priv->core;
    other_port = core->connected_port;
    if (!other_port)
    {
       UNLOCK_CONNECTION(port);
       LOG_DEBUG("%s(%p) is not connected", port->name, port);
       return MMAL_ENOTCONN;
    }
    LOCK_CONNECTION(other_port);
    /* Make sure the connection is disabled first */
    if (port->is_enabled)
    {
       MMAL_PORT_T *output = port->type == MMAL_PORT_TYPE_OUTPUT ? port : other_port;
       MMAL_PORT_T *input = other_port->type == MMAL_PORT_TYPE_INPUT ? other_port : port;
       status = mmal_port_disable_internal(output);
       if (status != MMAL_SUCCESS)
       {
          LOG_ERROR("failed to disable port (%s)%p", port->name, port);
          goto end;
       }
       status = mmal_port_disable_internal(input);
       if (status != MMAL_SUCCESS)
       {
          LOG_ERROR("failed to disable port (%s)%p", port->name, port);
          goto end;
       }
       status = mmal_port_connection_disable(port, other_port);
    }
    if (!core->core_owns_connection)
    {
       status = port->priv->pf_connect(port, NULL);
       if (status != MMAL_SUCCESS)
       {
          LOG_ERROR("disconnection of %s(%p) failed (%i)", port->name, port, status);
          goto end;
       }
    }
    core->connected_port = NULL;
    other_port->priv->core->connected_port = NULL;
 end:
    UNLOCK_CONNECTION(other_port);
    UNLOCK_CONNECTION(port);
    return status;
 }
mmal_port_enable()
MMAL_STATUS_T mmal_port_enable (MMAL_PORT_T * port, MMAL_PORT_BH_CB_T cb)
Enable processing on a port
If this port is connected to another, the given callback must be NULL, while for a disconnected port, the callback must be non-NULL.
If this is a connected output port and is successfully enabled:
The port shall be populated with a pool of buffers, allocated as required, according to the buffer_num and buffer_size values.
The input port to which it is connected shall be set to the same buffer configuration and then be enabled. Should that fail, the original port shall be disabled.
Parameters
port port to enable
cb callback use by the port to send a MMAL_BUFFER_HEADER_T back
Returns
MMAL_SUCCESS on success
Enable processing on a port
Definition at line 351 of file mmal_port.c.
References MMAL_PORT_T::buffer_num, MMAL_PORT_T::buffer_num_min, MMAL_PORT_T::buffer_num_recommended, MMAL_PORT_T::buffer_size, MMAL_PORT_T::buffer_size_min, MMAL_PORT_T::buffer_size_recommended, MMAL_PORT_PRIVATE_CORE_T::connected_port, MMAL_PORT_PRIVATE_T::core, MMAL_PORT_T::is_enabled, LOCK_CONNECTION, LOG_ERROR, LOG_TRACE, MMAL_EINVAL, MMAL_ENOSYS, MMAL_PORT_T::name, MMAL_PORT_PRIVATE_T::pf_enable, MMAL_PORT_T::priv, status, and UNLOCK_CONNECTION.
Referenced by mmal_connection_enable(), mmal_wrapper_port_enable(), OMX_GetHandle(), and raspitex_configure_preview_port().
 {
    MMAL_STATUS_T status;
    MMAL_PORT_T *connected_port;
    MMAL_PORT_PRIVATE_CORE_T *core;
    if (!port || !port->priv)
       return MMAL_EINVAL;
    LOG_TRACE("%s port %p, cb %p, buffers (%i/%i/%i,%i/%i/%i)",
              port->name, port, cb,
              (int)port->buffer_num, (int)port->buffer_num_recommended, (int)port->buffer_num_min,
              (int)port->buffer_size, (int)port->buffer_size_recommended, (int)port->buffer_size_min);
    if (!port->priv->pf_enable)
       return MMAL_ENOSYS;
    core = port->priv->core;
    LOCK_CONNECTION(port);
    connected_port = core->connected_port;
    /* Sanity checking */
    if (port->is_enabled)
    {
       UNLOCK_CONNECTION(port);
       LOG_ERROR("%s(%p) already enabled", port->name, port);
       return MMAL_EINVAL;
    }
    if (connected_port && cb) /* Callback must be NULL for connected ports */
    {
       UNLOCK_CONNECTION(port);
       LOG_ERROR("callback (%p) not allowed for connected port (%s)%p",
          cb, port->name, connected_port);
       return MMAL_EINVAL;
    }
    /* Start by preparing the port connection so that everything is ready for when
     * both ports are enabled */
    if (connected_port)
    {
       LOCK_CONNECTION(connected_port);
       status = mmal_port_connection_enable(port, connected_port);
       if (status != MMAL_SUCCESS)
       {
          UNLOCK_CONNECTION(connected_port);
          UNLOCK_CONNECTION(port);
          return status;
       }
       cb = connected_port->type == MMAL_PORT_TYPE_INPUT ?
          mmal_port_connected_output_cb : mmal_port_connected_input_cb;
    }
    /* Enable the input port of a connection first */
    if (connected_port && connected_port->type == MMAL_PORT_TYPE_INPUT)
    {
       status = mmal_port_enable_internal(connected_port, mmal_port_connected_input_cb);
       if (status != MMAL_SUCCESS)
       {
          LOG_ERROR("failed to enable connected port (%s)%p (%s)", connected_port->name,
             connected_port, mmal_status_to_string(status));
          goto error;
       }
    }
    status = mmal_port_enable_internal(port, cb);
    if (status != MMAL_SUCCESS)
    {
       LOG_ERROR("failed to enable port %s(%p) (%s)", port->name, port,
          mmal_status_to_string(status));
       goto error;
    }
    /* Enable the output port of a connection last */
    if (connected_port && connected_port->type != MMAL_PORT_TYPE_INPUT)
    {
       status = mmal_port_enable_internal(connected_port, mmal_port_connected_output_cb);
       if (status != MMAL_SUCCESS)
       {
          LOG_ERROR("failed to enable connected port (%s)%p (%s)", connected_port->name,
             connected_port, mmal_status_to_string(status));
          goto error;
       }
    }
    /* Kick off the connection */
    if (connected_port && core->core_owns_connection)
    {
       status = mmal_port_connection_start(port, connected_port);
       if (status != MMAL_SUCCESS)
       {
          LOG_ERROR("failed to start connection (%s)%p (%s)", port->name,
             port, mmal_status_to_string(status));
          goto error;
       }
    }
    if (connected_port)
       UNLOCK_CONNECTION(connected_port);
    UNLOCK_CONNECTION(port);
    return MMAL_SUCCESS;
 error:
    if (connected_port && connected_port->is_enabled)
       mmal_port_disable_internal(connected_port);
    if (port->is_enabled)
       mmal_port_disable_internal(port);
    if (connected_port)
       mmal_port_connection_disable(port, connected_port);
    if (connected_port)
       UNLOCK_CONNECTION(connected_port);
    UNLOCK_CONNECTION(port);
    return status;
 }
mmal_port_event_get()
MMAL_STATUS_T mmal_port_event_get (MMAL_PORT_T * port, MMAL_BUFFER_HEADER_T ** buffer, uint32_t event)
Get an empty event buffer header from a port
Parameters
port The port from which to get the event buffer header.
buffer The address of a buffer header pointer, which will be set on return.
event The specific event FourCC required. See the pre-defined events.
Returns
MMAL_SUCCESS on success
Definition at line 1150 of file mmal_port.c.
References MMAL_PORT_T::component, error(), MMAL_COMPONENT_PRIVATE_T::event_pool, MMAL_PORT_T::index, LOG_ERROR, LOG_TRACE, mmal_buffer_header_release(), MMAL_EINVAL, MMAL_ENOSPC, MMAL_EVENT_FORMAT_CHANGED, mmal_queue_get(), MMAL_SUCCESS, MMAL_COMPONENT_T::name, NULL, MMAL_COMPONENT_T::priv, MMAL_PORT_T::priv, MMAL_POOL_T::queue, and MMAL_PORT_T::type.
Referenced by mmal_event_eos_send(), mmal_event_error_send(), and mmal_event_forward().
 {
    if (!port || !port->priv || !buffer)
       return MMAL_EINVAL;
    LOG_TRACE("%s(%i:%i) port %p, event %4.4s", port->component->name,
              (int)port->type, (int)port->index, port, (char *)&event);
    /* Get an event buffer from our event pool */
    *buffer = mmal_queue_get(port->component->priv->event_pool->queue);
    if (!*buffer)
    {
       LOG_ERROR("%s(%i:%i) port %p, no event buffer left for %4.4s", port->component->name,
                 (int)port->type, (int)port->index, port, (char *)&event);
       return MMAL_ENOSPC;
    }
    (*buffer)->cmd = event;
    (*buffer)->length = 0;
    /* Special case for the FORMAT_CHANGED event. We need to properly initialise the event
     * buffer so that it contains an initialised MMAL_ES_FORMAT_T structure. */
    if (event == MMAL_EVENT_FORMAT_CHANGED)
    {
       uint32_t size = sizeof(MMAL_EVENT_FORMAT_CHANGED_T);
       size += sizeof(MMAL_ES_FORMAT_T) + sizeof(MMAL_ES_SPECIFIC_FORMAT_T);
       if ((*buffer)->alloc_size < size)
       {
          LOG_ERROR("%s(%i:%i) port %p, event buffer for %4.4s is too small (%i/%i)",
                    port->component->name, (int)port->type, (int)port->index, port,
                    (char *)&event, (int)(*buffer)->alloc_size, (int)size);
          goto error;
       }
       memset((*buffer)->data, 0, size);
       (*buffer)->length = size;
    }
    return MMAL_SUCCESS;
 error:
    if (*buffer)
       mmal_buffer_header_release(*buffer);
    *buffer = NULL;
    return MMAL_ENOSPC;
 }
mmal_port_flush()
MMAL_STATUS_T mmal_port_flush (MMAL_PORT_T * port)
Ask a port to release all the buffer headers it currently has.
Flushing a port will ask the port to send all the buffer headers it currently has to the client. Flushing is an asynchronous request and the flush call will return before all the buffer headers are returned to the client. It is up to the client to keep a count on the buffer headers to know when the flush operation has completed. It is also important to note that flushing will also reset the state of the port and any processing which was buffered by the port will be lost.
Attention
Flushing a connected port behaviour TBD.
Parameters
port The port to flush.
Returns
MMAL_SUCCESS on success
Flush a port
Definition at line 783 of file mmal_port.c.
References MMAL_PORT_T::component, MMAL_PORT_PRIVATE_T::core, MMAL_PORT_T::index, MMAL_PORT_T::is_enabled, LOCK_SENDING, LOG_TRACE, mmal_component_action_lock(), mmal_component_action_unlock(), MMAL_EINVAL, MMAL_ENOSYS, mmal_port_buffer_header_callback(), MMAL_SUCCESS, MMAL_COMPONENT_T::name, MMAL_BUFFER_HEADER_T::next, MMAL_PORT_PRIVATE_T::pf_flush, MMAL_PORT_T::priv, MMAL_PORT_PRIVATE_CORE_T::queue_first, MMAL_PORT_PRIVATE_CORE_T::queue_last, status, MMAL_PORT_T::type, and UNLOCK_SENDING.
 {
    MMAL_BUFFER_HEADER_T *buffer = 0;
    MMAL_STATUS_T status;
    if (!port || !port->priv)
       return MMAL_EINVAL;
    LOG_TRACE("%s(%i:%i) port %p", port->component->name,
              (int)port->type, (int)port->index, port);
    if (!port->priv->pf_flush)
       return MMAL_ENOSYS;
    /* N.B. must take action lock *before* sending lock */
    mmal_component_action_lock(port->component);
    LOCK_SENDING(port);
    if (!port->is_enabled)
    {
       UNLOCK_SENDING(port);
       mmal_component_action_unlock(port->component);
       return MMAL_SUCCESS;
    }
    status = port->priv->pf_flush(port);
    if (status == MMAL_SUCCESS)
    {
       /* Flush our internal queue */
       buffer = port->priv->core->queue_first;
       port->priv->core->queue_first = 0;
       port->priv->core->queue_last = &port->priv->core->queue_first;
    }
    UNLOCK_SENDING(port);
    mmal_component_action_unlock(port->component);
    while (buffer)
    {
       MMAL_BUFFER_HEADER_T *next = buffer->next;
       mmal_port_buffer_header_callback(port, buffer);
       buffer = next;
    }
    return status;
 }
mmal_port_format_commit()
MMAL_STATUS_T mmal_port_format_commit (MMAL_PORT_T * port)
Commit format changes on a port.
Parameters
port The port for which format changes are to be committed.
Returns
MMAL_SUCCESS on success
Set format of a port
Definition at line 288 of file mmal_port.c.
References MMAL_PORT_T::component, MMAL_PORT_PRIVATE_T::core, MMAL_ES_FORMAT_T::encoding, MMAL_PORT_T::format, MMAL_PORT_PRIVATE_CORE_T::format_ptr_copy, MMAL_PORT_T::index, LOCK_PORT, LOG_ERROR, LOG_TRACE, MMAL_EFAULT, MMAL_EINVAL, MMAL_ENOSYS, MMAL_COMPONENT_T::name, MMAL_PORT_T::name, NULL, MMAL_PORT_PRIVATE_T::pf_set_format, MMAL_PORT_T::priv, status, MMAL_PORT_T::type, and MMAL_ES_FORMAT_T::type.
Referenced by mmal_connection_create(), mmal_connection_event_format_changed(), mmal_encode_test(), and raspitex_configure_preview_port().
 {
    MMAL_STATUS_T status;
    char encoding_string[16];
    if (!port || !port->priv)
    {
       LOG_ERROR("invalid port (%p/%p)", port, port ? port->priv : NULL);
       return MMAL_EINVAL;
    }
    if (port->format != port->priv->core->format_ptr_copy)
    {
       LOG_ERROR("%s: port format has been overwritten, resetting %p to %p",
             port->name, port->format, port->priv->core->format_ptr_copy);
       port->format = port->priv->core->format_ptr_copy;
       return MMAL_EFAULT;
    }
    if (port->format->encoding == 0)
       snprintf(encoding_string, sizeof(encoding_string), "<NO-FORMAT>");
    else
       snprintf(encoding_string, sizeof(encoding_string), "%4.4s", (char*)&port->format->encoding);
    LOG_TRACE("%s(%i:%i) port %p format %i:%s",
              port->component->name, (int)port->type, (int)port->index, port,
              (int)port->format->type, encoding_string);
    if (!port->priv->pf_set_format)
    {
       LOG_ERROR("%s: no component implementation", port->name);
       return MMAL_ENOSYS;
    }
    LOCK_PORT(port);
    status = port->priv->pf_set_format(port);
    mmal_port_name_update(port);
    /* Make sure the buffer size / num are sensible */
    if (port->buffer_size < port->buffer_size_min)
       port->buffer_size = port->buffer_size_min;
    if (port->buffer_num < port->buffer_num_min)
       port->buffer_num = port->buffer_num_min;
    /* The output port settings might have changed */
    if (port->type == MMAL_PORT_TYPE_INPUT)
    {
       MMAL_PORT_T **ports = port->component->output;
       unsigned int i;
       for (i = 0; i < port->component->output_num; i++)
       {
          if (ports[i]->buffer_size < ports[i]->buffer_size_min)
             ports[i]->buffer_size = ports[i]->buffer_size_min;
          if (ports[i]->buffer_num < ports[i]->buffer_num_min)
             ports[i]->buffer_num = ports[i]->buffer_num_min;
       }
    }
    UNLOCK_PORT(port);
    return status;
 }
mmal_port_parameter_get()
MMAL_STATUS_T mmal_port_parameter_get (MMAL_PORT_T * port, MMAL_PARAMETER_HEADER_T * param)
Get a parameter from a port. The size field must be set on input to the maximum size of the parameter (including the header) and will be set on output to the actual size of the parameter retrieved.
Note
If MMAL_ENOSPC is returned, the parameter is larger than the size given. The given parameter will have been filled up to its size and then the size field set to the full parameter's size. This can be used to resize the parameter buffer so that a second call should succeed.
Parameters
port The port to which the request is sent.
param The pointer to the header of the parameter to get.
Returns
MMAL_SUCCESS on success
Definition at line 868 of file mmal_port.c.
References MMAL_PORT_T::component, MMAL_PARAMETER_HEADER_T::id, MMAL_PORT_T::index, LOCK_PORT, LOG_TRACE, MMAL_EINVAL, MMAL_ENOSYS, MMAL_COMPONENT_T::name, MMAL_PORT_PRIVATE_T::pf_parameter_get, MMAL_PORT_T::priv, MMAL_PARAMETER_HEADER_T::size, status, and MMAL_PORT_T::type.
Referenced by get_sensor_defaults(), mmal_port_parameter_alloc_get(), mmal_port_parameter_get_boolean(), mmal_port_parameter_get_int32(), mmal_port_parameter_get_int64(), mmal_port_parameter_get_rational(), mmal_port_parameter_get_uint32(), mmal_port_parameter_get_uint64(), mmal_util_get_core_port_stats(), mmal_util_rgb_order_fixed(), and raspicamcontrol_zoom_in_zoom_out().
 {
    MMAL_STATUS_T status = MMAL_ENOSYS;
    if (!port || !port->priv)
       return MMAL_EINVAL;
    LOG_TRACE("%s(%i:%i) port %p, param %p (%x,%i)", port->component->name,
              (int)port->type, (int)port->index, port,
              param, param ? param->id : 0, param ? (int)param->size : 0);
    if (!param)
       return MMAL_EINVAL;
    LOCK_PORT(port);
    if (port->priv->pf_parameter_get)
       status = port->priv->pf_parameter_get(port, param);
    if (status == MMAL_ENOSYS)
    {
       /* is this a core parameter? */
       status = mmal_port_private_parameter_get(port, param);
    }
    UNLOCK_PORT(port);
    return status;
 }
mmal_port_parameter_set()
MMAL_STATUS_T mmal_port_parameter_set (MMAL_PORT_T * port, const MMAL_PARAMETER_HEADER_T * param)
Set a parameter on a port.
Parameters
port The port to which the request is sent.
param The pointer to the header of the parameter to set.
Returns
MMAL_SUCCESS on success
Definition at line 830 of file mmal_port.c.
References MMAL_PORT_T::component, MMAL_PARAMETER_HEADER_T::id, MMAL_PORT_T::index, LOCK_PORT, LOG_ERROR, LOG_TRACE, MMAL_EINVAL, MMAL_ENOSYS, MMAL_COMPONENT_T::name, MMAL_PORT_PRIVATE_T::pf_parameter_set, MMAL_PORT_T::priv, MMAL_PARAMETER_HEADER_T::size, status, and MMAL_PORT_T::type.
Referenced by mmal_connection_create(), mmal_port_parameter_set_boolean(), mmal_port_parameter_set_bytes(), mmal_port_parameter_set_int32(), mmal_port_parameter_set_int64(), mmal_port_parameter_set_rational(), mmal_port_parameter_set_string(), mmal_port_parameter_set_uint32(), mmal_port_parameter_set_uint64(), mmal_util_camera_use_stc_timestamp(), mmal_util_set_display_region(), mmal_wrapper_port_enable(), raspicamcontrol_set_all_parameters(), raspicamcontrol_set_annotate(), raspicamcontrol_set_awb_gains(), raspicamcontrol_set_awb_mode(), raspicamcontrol_set_colourFX(), raspicamcontrol_set_DRC(), raspicamcontrol_set_exposure_mode(), raspicamcontrol_set_flicker_avoid_mode(), raspicamcontrol_set_flips(), raspicamcontrol_set_imageFX(), raspicamcontrol_set_metering_mode(), raspicamcontrol_set_ROI(), raspicamcontrol_set_stereo_mode(), and raspicamcontrol_zoom_in_zoom_out().
 {
    MMAL_STATUS_T status = MMAL_ENOSYS;
    if (!port)
    {
       LOG_ERROR("no port");
       return MMAL_EINVAL;
    }
    if (!param)
    {
       LOG_ERROR("param not supplied");
       return MMAL_EINVAL;
    }
    if (!port->priv)
    {
       LOG_ERROR("port not configured");
       return MMAL_EINVAL;
    }
    LOG_TRACE("%s(%i:%i) port %p, param %p (%x,%i)", port->component->name,
              (int)port->type, (int)port->index, port,
              param, param ? param->id : 0, param ? (int)param->size : 0);
    LOCK_PORT(port);
    if (port->priv->pf_parameter_set)
       status = port->priv->pf_parameter_set(port, param);
    if (status == MMAL_ENOSYS)
    {
       /* is this a core parameter? */
       status = mmal_port_private_parameter_set(port, param);
    }
    UNLOCK_PORT(port);
    return status;
 }
mmal_port_payload_alloc()
uint8_t* mmal_port_payload_alloc (MMAL_PORT_T * port, uint32_t payload_size)
Allocate a payload buffer. This allows a client to allocate memory for a payload buffer based on the preferences of a port. This for instance will allow the port to allocate memory which can be shared between the host processor and videocore.
See mmal_pool_create_with_allocator().
Parameters
port Port responsible for allocating the memory.
payload_size Size of the payload buffer which will be allocated.
Returns
Pointer to the allocated memory.
Allocate a payload buffer
Definition at line 1085 of file mmal_port.c.
References MMAL_PORT_T::component, MMAL_PORT_T::index, LOCK_PORT, LOG_TRACE, mem, mem_alloc, MEM_FLAG_DIRECT, mmal_port_acquire(), MMAL_COMPONENT_T::name, MMAL_PORT_T::name, NULL, MMAL_PORT_PRIVATE_T::pf_payload_alloc, MMAL_PORT_T::priv, MMAL_PORT_T::type, UNLOCK_PORT, and vcos_malloc().
Referenced by mmal_port_pool_create().
 {
    uint8_t *mem;
    if (!port || !port->priv)
       return NULL;
    LOG_TRACE("%s(%i:%i) port %p, size %i", port->component->name,
              (int)port->type, (int)port->index, port, (int)payload_size);
    if (!payload_size)
       return NULL;
    /* TODO: keep track of the allocs so we can free them when the component is destroyed */
    if (!port->priv->pf_payload_alloc)
    {
       /* Revert to using the heap */
 #ifdef _VIDEOCORE
       mem = (void *)mem_alloc(payload_size, 32, MEM_FLAG_DIRECT, port->name);
 #else
       mem = vcos_malloc(payload_size, "mmal payload");
 #endif
       goto end;
    }
    LOCK_PORT(port);
    mem = port->priv->pf_payload_alloc(port, payload_size);
    UNLOCK_PORT(port);
  end:
    /* Acquire the port if the allocation was successful.
     * This will ensure that the component is not destroyed until the payload has been freed. */
    if (mem)
       mmal_port_acquire(port);
    return mem;
 }
mmal_port_payload_free()
void mmal_port_payload_free (MMAL_PORT_T * port, uint8_t * payload)
Free a payload buffer. This allows a client to free memory allocated by a previous call to mmal_port_payload_alloc.
See mmal_pool_create_with_allocator().
Parameters
port Port responsible for allocating the memory.
payload Pointer to the memory to free.
Free a payload buffer
Definition at line 1124 of file mmal_port.c.
References MMAL_PORT_T::component, MMAL_PORT_T::index, LOCK_PORT, LOG_TRACE, mem_release(), mmal_port_release(), MMAL_COMPONENT_T::name, MMAL_PORT_PRIVATE_T::pf_payload_alloc, MMAL_PORT_PRIVATE_T::pf_payload_free, MMAL_PORT_T::priv, MMAL_PORT_T::type, UNLOCK_PORT, and vcos_free().
Referenced by mmal_port_pool_create().
 {
    if (!port || !port->priv)
       return;
    LOG_TRACE("%s(%i:%i) port %p, payload %p", port->component->name,
              (int)port->type, (int)port->index, port, payload);
    if (!port->priv->pf_payload_alloc)
    {
       /* Revert to using the heap */
 #ifdef _VIDEOCORE
       mem_release((MEM_HANDLE_T)payload);
 #else
       vcos_free(payload);
 #endif
       mmal_port_release(port);
       return;
    }
    LOCK_PORT(port);
    port->priv->pf_payload_free(port, payload);
    UNLOCK_PORT(port);
    mmal_port_release(port);
 }
mmal_port_send_buffer()
MMAL_STATUS_T mmal_port_send_buffer (MMAL_PORT_T * port, MMAL_BUFFER_HEADER_T * buffer)
Send a buffer header to a port.
Parameters
port The port to which the buffer header is to be sent.
buffer The buffer header to send.
Returns
MMAL_SUCCESS on success
Send a buffer header to a port
Definition at line 709 of file mmal_port.c.
References MMAL_BUFFER_HEADER_T::alloc_size, MMAL_PORT_T::capabilities, MMAL_PORT_T::component, MMAL_PORT_PRIVATE_T::core, MMAL_BUFFER_HEADER_T::data, IN_TRANSIT_DECREMENT, IN_TRANSIT_INCREMENT, MMAL_PORT_T::index, MMAL_PORT_T::is_enabled, MMAL_PORT_PRIVATE_CORE_T::is_paused, MMAL_BUFFER_HEADER_T::length, LOCK_SENDING, LOG_DEBUG, LOG_ERROR, LOG_TRACE, MMAL_EINVAL, MMAL_ENOSYS, MMAL_PORT_CAPABILITY_PASSTHROUGH, MMAL_PORT_TYPE_OUTPUT, mmal_status_to_string(), MMAL_SUCCESS, MMAL_COMPONENT_T::name, MMAL_PORT_T::name, MMAL_BUFFER_HEADER_T::next, NULL, MMAL_BUFFER_HEADER_T::offset, MMAL_PORT_PRIVATE_T::pf_send, MMAL_PORT_T::priv, MMAL_PORT_PRIVATE_CORE_T::queue_last, status, MMAL_PORT_T::type, and UNLOCK_SENDING.
Referenced by mmal_connection_event_format_changed(), mmal_encode_test(), and mmalomx_buffer_send().
 {
    MMAL_STATUS_T status = MMAL_SUCCESS;
    if (!port || !port->priv)
    {
       LOG_ERROR("invalid port");
       return MMAL_EINVAL;
    }
 #ifdef ENABLE_MMAL_EXTRA_LOGGING
    LOG_TRACE("%s(%i:%i) port %p, buffer %p (%p,%i,%i)",
              port->component->name, (int)port->type, (int)port->index, port, buffer,
              buffer ? buffer->data: 0, buffer ? (int)buffer->offset : 0,
              buffer ? (int)buffer->length : 0);
 #endif
    if (buffer->alloc_size && !buffer->data &&
        !(port->capabilities & MMAL_PORT_CAPABILITY_PASSTHROUGH))
    {
       LOG_ERROR("%s(%p) received invalid buffer header", port->name, port);
       return MMAL_EINVAL;
    }
    if (!port->priv->pf_send)
       return MMAL_ENOSYS;
    LOCK_SENDING(port);
    if (!port->is_enabled)
    {
       UNLOCK_SENDING(port);
       return MMAL_EINVAL;
    }
    if (port->type == MMAL_PORT_TYPE_OUTPUT && buffer->length)
    {
       LOG_DEBUG("given an output buffer with length != 0");
       buffer->length = 0;
    }
    /* coverity[lock] transit_sema is used for signalling, and is not a lock */
    /* coverity[lock_order] since transit_sema is not a lock, there is no ordering conflict */
    IN_TRANSIT_INCREMENT(port);
    if (port->priv->core->is_paused)
    {
       /* Add buffer to our internal queue */
       buffer->next = NULL;
       *port->priv->core->queue_last = buffer;
       port->priv->core->queue_last = &buffer->next;
    }
    else
    {
       /* Send buffer to component */
       status = port->priv->pf_send(port, buffer);
    }
    if (status != MMAL_SUCCESS)
    {
       IN_TRANSIT_DECREMENT(port);
       LOG_ERROR("%s: send failed: %s", port->name, mmal_status_to_string(status));
    }
    else
    {
       mmal_port_update_port_stats(port, MMAL_CORE_STATS_RX);
    }
    UNLOCK_SENDING(port);
    return status;
 }