VideoCore Library: containers/net/net_sockets_null.c File Reference
net_sockets_null.c File Reference
#include "net_sockets.h"
#include "containers/core/containers_common.h"
Classes
struct vc_container_net_tag
Functions
VC_CONTAINER_NET_T * vc_container_net_open (const char *address, const char *port, vc_container_net_open_flags_t flags, vc_container_net_status_t *p_status)
vc_container_net_status_t vc_container_net_close (VC_CONTAINER_NET_T *p_ctx)
vc_container_net_status_t vc_container_net_status (VC_CONTAINER_NET_T *p_ctx)
size_t vc_container_net_read (VC_CONTAINER_NET_T *p_ctx, void *buffer, size_t size)
size_t vc_container_net_write (VC_CONTAINER_NET_T *p_ctx, const void *buffer, size_t size)
vc_container_net_status_t vc_container_net_listen (VC_CONTAINER_NET_T *p_ctx, uint32_t maximum_connections)
vc_container_net_status_t vc_container_net_accept (VC_CONTAINER_NET_T *p_server_ctx, VC_CONTAINER_NET_T **pp_client_ctx)
bool vc_container_net_is_data_available (VC_CONTAINER_NET_T *p_ctx)
size_t vc_container_net_maximum_datagram_size (VC_CONTAINER_NET_T *p_ctx)
vc_container_net_status_t vc_container_net_get_client_name (VC_CONTAINER_NET_T *p_ctx, char *name, size_t name_len)
vc_container_net_status_t vc_container_net_get_client_port (VC_CONTAINER_NET_T *p_ctx, unsigned short *port)
vc_container_net_status_t vc_container_net_control (VC_CONTAINER_NET_T *p_ctx, vc_container_net_control_t operation, va_list args)
uint32_t vc_container_net_to_host (uint32_t value)
uint32_t vc_container_net_from_host (uint32_t value)
uint16_t vc_container_net_to_host_16 (uint16_t value)
uint16_t vc_container_net_from_host_16 (uint16_t value)
Function Documentation
vc_container_net_accept()
vc_container_net_status_t vc_container_net_accept (VC_CONTAINER_NET_T * p_server_ctx, VC_CONTAINER_NET_T ** pp_client_ctx)
Accept a client connection on a listening stream server socket. Attempting to use this on anything other than a listening stream server socket shall trigger an error. When a client connection is made, the new instance representing it is returned via pp_client_ctx.
Parameters
p_server ctx The server socket instance.
pp_client_ctx The address where the pointer to the new client's socket instance is written.
Returns
The status of the socket.
Definition at line 98 of file net_sockets_null.c.
References VC_CONTAINER_NET_ERROR_INVALID_SOCKET, and VC_CONTAINER_PARAM_UNUSED.
Referenced by main().
 {
    VC_CONTAINER_PARAM_UNUSED(p_server_ctx);
    VC_CONTAINER_PARAM_UNUSED(pp_client_ctx);
    return VC_CONTAINER_NET_ERROR_INVALID_SOCKET;
 }
vc_container_net_close()
vc_container_net_status_t vc_container_net_close (VC_CONTAINER_NET_T * p_ctx)
Closes a network socket instance. The p_ctx pointer must not be used after it has been closed.
Parameters
p_ctx The socket instance to close.
Returns
The status code for closing the socket.
Definition at line 53 of file net_sockets_null.c.
References VC_CONTAINER_NET_ERROR_INVALID_SOCKET, and VC_CONTAINER_PARAM_UNUSED.
Referenced by main().
 {
    VC_CONTAINER_PARAM_UNUSED(p_ctx);
    return VC_CONTAINER_NET_ERROR_INVALID_SOCKET;
 }
vc_container_net_control()
vc_container_net_status_t vc_container_net_control (VC_CONTAINER_NET_T * p_ctx, vc_container_net_control_t operation, va_list args)
Perform a control operation on the socket. See vc_container_net_control_t for more details.
Parameters
p_ctx The socket instance.
operation The control operation to perform.
args Variable list of additional arguments to the operation.
Returns
The status of the socket.
Definition at line 142 of file net_sockets_null.c.
References VC_CONTAINER_NET_ERROR_NOT_ALLOWED, and VC_CONTAINER_PARAM_UNUSED.
 {
    VC_CONTAINER_PARAM_UNUSED(p_ctx);
    VC_CONTAINER_PARAM_UNUSED(operation);
    VC_CONTAINER_PARAM_UNUSED(args);
    return VC_CONTAINER_NET_ERROR_NOT_ALLOWED;
 }
vc_container_net_from_host()
uint32_t vc_container_net_from_host (uint32_t value)
Convert a 32-bit unsigned value from host order to network order (big endian).
Parameters
value The value to be converted.
Returns
The converted value.
Definition at line 160 of file net_sockets_null.c.
 {
    return value;
 }
vc_container_net_from_host_16()
uint16_t vc_container_net_from_host_16 (uint16_t value)
Convert a 16-bit unsigned value from host order to network order (big endian).
Parameters
value The value to be converted.
Returns
The converted value.
Definition at line 172 of file net_sockets_null.c.
 {
    return value;
 }
vc_container_net_get_client_name()
vc_container_net_status_t vc_container_net_get_client_name (VC_CONTAINER_NET_T * p_ctx, char * name, size_t name_len)
Get the DNS name or IP address of a stream server client, if connected. The length of the name will be limited by name_len, taking into account a terminating NUL character. Calling this function on a non-stream server instance, or one that is not connected to a client, will result in an error status.
Parameters
p_ctx The socket instance.
name Pointer where the name should be written.
name_len Maximum number of characters to write to name.
Returns
The status of the socket.
Definition at line 123 of file net_sockets_null.c.
References VC_CONTAINER_NET_ERROR_INVALID_SOCKET, and VC_CONTAINER_PARAM_UNUSED.
Referenced by main().
 {
    VC_CONTAINER_PARAM_UNUSED(p_ctx);
    VC_CONTAINER_PARAM_UNUSED(name);
    VC_CONTAINER_PARAM_UNUSED(name_len);
    return VC_CONTAINER_NET_ERROR_INVALID_SOCKET;
 }
vc_container_net_get_client_port()
vc_container_net_status_t vc_container_net_get_client_port (VC_CONTAINER_NET_T * p_ctx, unsigned short * port)
Get the port of a stream server client, if connected. The port is written to the address in host order. Calling this function on a non-stream server instance, or one that is not connected to a client, will result in an error status.
Parameters
p_ctx The socket instance.
port Pointer where the port should be written.
Returns
The status of the socket.
Definition at line 133 of file net_sockets_null.c.
References VC_CONTAINER_NET_ERROR_INVALID_SOCKET, and VC_CONTAINER_PARAM_UNUSED.
Referenced by main().
 {
    VC_CONTAINER_PARAM_UNUSED(p_ctx);
    VC_CONTAINER_PARAM_UNUSED(port);
    return VC_CONTAINER_NET_ERROR_INVALID_SOCKET;
 }
vc_container_net_is_data_available()
bool vc_container_net_is_data_available (VC_CONTAINER_NET_T * p_ctx)
Non-blocking check for data being available to read. If an error occurs, the function will return false and the error can be obtained using socket_status().
Parameters
p_ctx The socket instance.
Returns
True if there is data available to read immediately.
Definition at line 107 of file net_sockets_null.c.
References VC_CONTAINER_PARAM_UNUSED.
 {
    VC_CONTAINER_PARAM_UNUSED(p_ctx);
    return false;
 }
vc_container_net_listen()
vc_container_net_status_t vc_container_net_listen (VC_CONTAINER_NET_T * p_ctx, uint32_t maximum_connections)
Start a stream server socket listening for connections from clients. Attempting to use this on anything other than a stream server socket shall trigger an error.
Parameters
p_ctx The socket instance.
maximum_connections The maximum number of queued connections to allow.
Returns
The status of the socket.
Definition at line 89 of file net_sockets_null.c.
References VC_CONTAINER_NET_ERROR_INVALID_SOCKET, and VC_CONTAINER_PARAM_UNUSED.
Referenced by main().
 {
    VC_CONTAINER_PARAM_UNUSED(p_ctx);
    VC_CONTAINER_PARAM_UNUSED(maximum_connections);
    return VC_CONTAINER_NET_ERROR_INVALID_SOCKET;
 }
vc_container_net_maximum_datagram_size()
size_t vc_container_net_maximum_datagram_size (VC_CONTAINER_NET_T * p_ctx)
Returns the maximum size of a datagram in bytes, for sending or receiving. The limit for reading from or writing to stream sockets will generally be greater than this value, although the call can also be made on such sockets.
Parameters
p_ctx The socket instance.
Returns
The maximum size of a datagram in bytes.
Definition at line 115 of file net_sockets_null.c.
References VC_CONTAINER_PARAM_UNUSED.
Referenced by main().
 {
    VC_CONTAINER_PARAM_UNUSED(p_ctx);
    return 0;
 }
vc_container_net_open()
VC_CONTAINER_NET_T* vc_container_net_open (const char * address, const char * port, vc_container_net_open_flags_t flags, vc_container_net_status_t * p_status)
Opens a network socket instance. The network address can be a host name, dotted IP4, hex IP6 address or NULL. Passing NULL signifies the socket is either to be used as a datagram receiver or a stream server, depending on the flags. VC_CONTAINER_NET_OPEN_FLAG_STREAM will open the socket for connected streaming. The default is to use connectionless datagrams. VC_CONTAINER_NET_OPEN_FLAG_FORCE_IP4 will force the use of IPv4 addressing or fail to open the socket. The default is to pick the first available. VC_CONTAINER_NET_OPEN_FLAG_FORCE_IP6 will force the use of IPv6 addressing or fail to open the socket. The default is to pick the first available. VC_CONTAINER_NET_OPEN_FLAG_IP4_BROADCAST will use IPv4 broadcast addressing for a datagram sender. Use with an IPv6 address, stream socket or datagram receiver will raise an error. If the p_status parameter is not NULL, the status code will be written to it to indicate the reason for failure, or VC_CONTAINER_NET_SUCCESS on success. Sockets shall be bound and connected as necessary. Stream server sockets shall further need to have vc_container_net_listen and vc_container_net_accept called on them before data can be transferred.
Parameters
address Network address or NULL.
port Network port or well-known name. This is the local port for receivers/servers.
flags Flags controlling socket type.
p_status Optional pointer to variable to receive status of operation.
Returns
The socket instance or NULL on error.
Definition at line 39 of file net_sockets_null.c.
References NULL, VC_CONTAINER_NET_ERROR_NOT_ALLOWED, and VC_CONTAINER_PARAM_UNUSED.
Referenced by main().
 {
    VC_CONTAINER_PARAM_UNUSED(address);
    VC_CONTAINER_PARAM_UNUSED(port);
    VC_CONTAINER_PARAM_UNUSED(flags);
    if (p_status)
       *p_status = VC_CONTAINER_NET_ERROR_NOT_ALLOWED;
    return NULL;
 }
vc_container_net_read()
size_t vc_container_net_read (VC_CONTAINER_NET_T * p_ctx, void * buffer, size_t size)
Read data from the socket. The function will read up to the requested number of bytes into the buffer. If there is no data immediately available to read, the function will block until data arrives, an error occurs or the timeout is reached (if set). When the function returns zero, the socket may have been closed, an error may have occurred, a zero length datagram received, or the timeout reached. Check vc_container_net_status() to differentiate. Attempting to read on a datagram sender socket will trigger an error.
Parameters
p_ctx The socket instance.
buffer The buffer into which bytes will be read.
size The maximum number of bytes to read.
Returns
The number of bytes actually read.
Definition at line 69 of file net_sockets_null.c.
References VC_CONTAINER_PARAM_UNUSED.
Referenced by main().
 {
    VC_CONTAINER_PARAM_UNUSED(p_ctx);
    VC_CONTAINER_PARAM_UNUSED(buffer);
    VC_CONTAINER_PARAM_UNUSED(size);
    return 0;
 }
vc_container_net_status()
vc_container_net_status_t vc_container_net_status (VC_CONTAINER_NET_T * p_ctx)
Query the latest status of the socket.
Parameters
p_ctx The socket instance.
Returns
The status of the socket.
Definition at line 61 of file net_sockets_null.c.
References VC_CONTAINER_NET_ERROR_INVALID_SOCKET, and VC_CONTAINER_PARAM_UNUSED.
Referenced by main().
 {
    VC_CONTAINER_PARAM_UNUSED(p_ctx);
    return VC_CONTAINER_NET_ERROR_INVALID_SOCKET;
 }
vc_container_net_to_host()
uint32_t vc_container_net_to_host (uint32_t value)
Convert a 32-bit unsigned value from network order (big endian) to host order.
Parameters
value The value to be converted.
Returns
The converted value.
Definition at line 154 of file net_sockets_null.c.
 {
    return value;
 }
vc_container_net_to_host_16()
uint16_t vc_container_net_to_host_16 (uint16_t value)
Convert a 16-bit unsigned value from network order (big endian) to host order.
Parameters
value The value to be converted.
Returns
The converted value.
Definition at line 166 of file net_sockets_null.c.
 {
    return value;
 }
vc_container_net_write()
size_t vc_container_net_write (VC_CONTAINER_NET_T * p_ctx, const void * buffer, size_t size)
Write data to the socket. If the socket cannot send the requested number of bytes in one go, the function will return a value smaller than size. Attempting to write on a datagram receiver socket will trigger an error.
Parameters
p_ctx The socket instance.
buffer The buffer from which bytes will be written.
size The maximum number of bytes to write.
Returns
The number of bytes actually written.
Definition at line 79 of file net_sockets_null.c.
References VC_CONTAINER_PARAM_UNUSED.
Referenced by main().
 {
    VC_CONTAINER_PARAM_UNUSED(p_ctx);
    VC_CONTAINER_PARAM_UNUSED(buffer);
    VC_CONTAINER_PARAM_UNUSED(size);
    return 0;
 }