VideoCore Library: interface/vcos/vcos_thread_attr.h File Reference
vcos_thread_attr.h File Reference
Macros
#define VCOS_THREAD_ATTR_H
#define VCOS_THREAD_ATTR_H
Functions
VCOSPRE_ void VCOSPOST_ vcos_thread_attr_init (VCOS_THREAD_ATTR_T *attrs)
VCOS_INLINE_DECL void vcos_thread_attr_setstacksize (VCOS_THREAD_ATTR_T *attrs, VCOS_UNSIGNED sz)
VCOS_INLINE_DECL void vcos_thread_attr_setpriority (VCOS_THREAD_ATTR_T *attrs, VCOS_UNSIGNED pri)
VCOS_INLINE_DECL void vcos_thread_attr_setaffinity (VCOS_THREAD_ATTR_T *attrs, VCOS_UNSIGNED aff)
VCOS_INLINE_DECL void vcos_thread_attr_settimeslice (VCOS_THREAD_ATTR_T *attrs, VCOS_UNSIGNED ts)
VCOS_INLINE_DECL void _vcos_thread_attr_setlegacyapi (VCOS_THREAD_ATTR_T *attrs, VCOS_UNSIGNED legacy)
VCOS_INLINE_DECL void vcos_thread_attr_setautostart (VCOS_THREAD_ATTR_T *attrs, VCOS_UNSIGNED autostart)
Detailed Description
Attributes for thread creation.
Definition in file vcos_thread_attr.h.
Macro Definition Documentation
VCOS_THREAD_ATTR_H [1/2]
#define VCOS_THREAD_ATTR_H
VCOS_THREAD_ATTR_H [2/2]
#define VCOS_THREAD_ATTR_H
Function Documentation
_vcos_thread_attr_setlegacyapi()
VCOS_INLINE_DECL void _vcos_thread_attr_setlegacyapi (VCOS_THREAD_ATTR_T * attrs, VCOS_UNSIGNED legacy)
The thread entry function takes (argc,argv), as per Nucleus, with argc being 0. This may be withdrawn in a future release and should not be used in new code.
vcos_thread_attr_init()
VCOSPRE_ void VCOSPOST_ vcos_thread_attr_init (VCOS_THREAD_ATTR_T * attrs)
Initialize thread attribute struct. This call does not allocate memory, and so cannot fail.
Definition at line 455 of file vcos_pthreads.c.
Referenced by mmal_component_action_register(), and vcos_thread_create_classic().
 {
    *attrs = default_attrs;
 }
vcos_thread_attr_setaffinity()
VCOS_INLINE_DECL void vcos_thread_attr_setaffinity (VCOS_THREAD_ATTR_T * attrs, VCOS_UNSIGNED aff)
Set the task cpu affinity. If not set, the default will be used.
Referenced by vcos_thread_create_classic().
vcos_thread_attr_setautostart()
VCOS_INLINE_DECL void vcos_thread_attr_setautostart (VCOS_THREAD_ATTR_T * attrs, VCOS_UNSIGNED autostart)
vcos_thread_attr_setpriority()
VCOS_INLINE_DECL void vcos_thread_attr_setpriority (VCOS_THREAD_ATTR_T * attrs, VCOS_UNSIGNED pri)
Set the task priority. If not set, a default value will be used.
Referenced by mmal_component_action_register(), and vcos_thread_create_classic().
vcos_thread_attr_setstacksize()
VCOS_INLINE_DECL void vcos_thread_attr_setstacksize (VCOS_THREAD_ATTR_T * attrs, VCOS_UNSIGNED sz)
Set the stack address and size. If not set, a stack will be allocated automatically.
This can only be set on some platforms. It will always be possible to set the stack address on VideoCore, but on host platforms, support may well not be available.Set the stack size. If not set, a default size will be used. Attempting to call this after having set the stack location with vcos_thread_attr_setstack() will result in undefined behaviour.
Referenced by vcos_thread_create_classic().
vcos_thread_attr_settimeslice()
VCOS_INLINE_DECL void vcos_thread_attr_settimeslice (VCOS_THREAD_ATTR_T * attrs, VCOS_UNSIGNED ts)
Set the timeslice. If not set the default will be used.