VideoCore Library: interface/vcos/vcos_logging.h File Reference
vcos_logging.h File Reference
#include <stdarg.h>
#include "interface/vcos/vcos_types.h"
#include "vcos.h"
#include "vcos_logging_control.h"
Classes
struct VCOS_LOG_CAT_T
Macros
#define VCOS_LOGGING_H
#define VCOS_LOG_INIT(n, l) { l, n, 0, {0}, 0, 0 }
#define vcos_log_dump_mem(cat, label, addr, voidMem, numBytes) do { if (vcos_is_log_enabled(cat,VCOS_LOG_TRACE)) vcos_log_dump_mem_impl(cat,label,addr,voidMem,numBytes); } while (0)
#define vcos_log_platform_init() (void)0
#define vcos_log_platform_register(category) (void)0
#define vcos_log_platform_unregister(category) (void)0
#define VCOS_LOG_DFLT_CATEGORY vcos_log_get_default_category()
#define _VCOS_LEVEL(x) (x)
#define vcos_is_log_enabled(cat, _level) (_VCOS_LEVEL((cat)->level) >= _VCOS_LEVEL(_level))
#define VCOS_LOG_INIT(n, l) { l, n, 0, {0}, 0, 0 }
#define vcos_log_dump_mem(cat, label, addr, voidMem, numBytes) do { if (vcos_is_log_enabled(cat,VCOS_LOG_TRACE)) vcos_log_dump_mem_impl(cat,label,addr,voidMem,numBytes); } while (0)
#define vcos_log_platform_init() (void)0
#define vcos_log_platform_register(category) (void)0
#define vcos_log_platform_unregister(category) (void)0
#define VCOS_LOG_DFLT_CATEGORY vcos_log_get_default_category()
#define _VCOS_LEVEL(x) (x)
#define vcos_is_log_enabled(cat, _level) (_VCOS_LEVEL((cat)->level) >= _VCOS_LEVEL(_level))
#define VCOS_LOGGING_H
#define VCOS_LOG_INIT(n, l) { l, n, 0, {0}, 0, 0 }
#define vcos_log_dump_mem(cat, label, addr, voidMem, numBytes) do { if (vcos_is_log_enabled(cat,VCOS_LOG_TRACE)) vcos_log_dump_mem_impl(cat,label,addr,voidMem,numBytes); } while (0)
#define vcos_log_platform_init() (void)0
#define vcos_log_platform_register(category) (void)0
#define vcos_log_platform_unregister(category) (void)0
#define VCOS_LOG_DFLT_CATEGORY vcos_log_get_default_category()
#define _VCOS_LEVEL(x) (x)
#define vcos_is_log_enabled(cat, _level) (_VCOS_LEVEL((cat)->level) >= _VCOS_LEVEL(_level))
Typedefs
typedef enum VCOS_LOG_LEVEL_T VCOS_LOG_LEVEL_T
typedef struct VCOS_LOG_CAT_T VCOS_LOG_CAT_T
typedef void(* VCOS_VLOG_IMPL_FUNC_T) (const VCOS_LOG_CAT_T *cat, VCOS_LOG_LEVEL_T _level, const char *fmt, va_list args)
Enumerations
enum VCOS_LOG_LEVEL_T {
VCOS_LOG_UNINITIALIZED = 0, VCOS_LOG_NEVER, VCOS_LOG_ERROR, VCOS_LOG_WARN,
VCOS_LOG_INFO, VCOS_LOG_TRACE
}
Functions
VCOSPRE_ const char *VCOSPOST_ vcos_log_level_to_string (VCOS_LOG_LEVEL_T level)
VCOSPRE_ VCOS_STATUS_T VCOSPOST_ vcos_string_to_log_level (const char *str, VCOS_LOG_LEVEL_T *level)
VCOSPRE_ void VCOSPOST_ vcos_log_impl (const VCOS_LOG_CAT_T *cat, VCOS_LOG_LEVEL_T _level, const char *fmt,...) VCOS_FORMAT_ATTR_(printf
VCOSPRE_ void VCOSPOST_ VCOSPRE_ void VCOSPOST_ vcos_vlog_impl (const VCOS_LOG_CAT_T *cat, VCOS_LOG_LEVEL_T _level, const char *fmt, va_list args) VCOS_FORMAT_ATTR_(printf
VCOSPRE_ void VCOSPOST_ VCOSPRE_ void VCOSPOST_ VCOSPRE_ void VCOSPOST_ vcos_set_vlog_impl (VCOS_VLOG_IMPL_FUNC_T vlog_impl_func)
VCOSPRE_ void VCOSPOST_ vcos_vlog_default_impl (const VCOS_LOG_CAT_T *cat, VCOS_LOG_LEVEL_T _level, const char *fmt, va_list args) VCOS_FORMAT_ATTR_(printf
VCOSPRE_ void VCOSPOST_ VCOSPRE_ void VCOSPOST_ vcos_logging_init (void)
VCOSPRE_ void VCOSPOST_ vcos_log_register (const char *name, VCOS_LOG_CAT_T *category)
VCOSPRE_ void VCOSPOST_ vcos_log_unregister (VCOS_LOG_CAT_T *category)
VCOSPRE_ const VCOS_LOG_CAT_T *VCOSPOST_ vcos_log_get_default_category (void)
VCOSPRE_ void VCOSPOST_ vcos_set_log_options (const char *opt)
VCOS_STATIC_INLINE void vcos_log_set_level (VCOS_LOG_CAT_T *category, VCOS_LOG_LEVEL_T level)
VCOSPRE_ void VCOSPOST_ vcos_log_set_level_all (char *levels)
void vcos_log_dump_mem_impl (const VCOS_LOG_CAT_T *cat, const char *label, uint32_t addr, const void *voidMem, size_t numBytes)
Detailed Description
Logging support
This provides categorised logging. Clients register a category, and then get a number of logging levels for that category.
The logging level flag is tested using a flag before the function call, which makes logging very fast when disabled - there is no function call overhead just to find out that this log message is disabled.
VCOS_LOG_CATEGORY
As a convenience, clients define VCOS_LOG_CATEGORY to point to their category; the various vcos_log_xxx() macros then expand to use this.
e.g.
#define VCOS_LOG_CATEGORY (&my_category)
#include <interface/vcos/vcos.h>
VCOS_LOG_CAT_T my_category;
....
vcos_log_trace("Stuff happened: %d", n_stuff);
Definition in file vcos_logging.h.
Macro Definition Documentation
_VCOS_LEVEL [1/3]
#define _VCOS_LEVEL (x) (x)
_VCOS_LEVEL [2/3]
#define _VCOS_LEVEL (x) (x)
Definition at line 226 of file khrn_misc.h.
_VCOS_LEVEL [3/3]
#define _VCOS_LEVEL (x) (x)
vcos_is_log_enabled [1/3]
#define vcos_is_log_enabled (cat, _level) (_VCOS_LEVEL((cat)->level) >= _VCOS_LEVEL(_level))
vcos_is_log_enabled [2/3]
#define vcos_is_log_enabled (cat, _level) (_VCOS_LEVEL((cat)->level) >= _VCOS_LEVEL(_level))
Definition at line 228 of file khrn_misc.h.
vcos_is_log_enabled [3/3]
#define vcos_is_log_enabled (cat, _level) (_VCOS_LEVEL((cat)->level) >= _VCOS_LEVEL(_level))
VCOS_LOG_DFLT_CATEGORY [1/3]
#define VCOS_LOG_DFLT_CATEGORY vcos_log_get_default_category()
VCOS_LOG_DFLT_CATEGORY [2/3]
#define VCOS_LOG_DFLT_CATEGORY vcos_log_get_default_category()
VCOS_LOG_DFLT_CATEGORY [3/3]
#define VCOS_LOG_DFLT_CATEGORY vcos_log_get_default_category()
Definition at line 224 of file khrn_misc.h.
vcos_log_dump_mem [1/3]
#define vcos_log_dump_mem (cat, label, addr, voidMem, numBytes) do { if (vcos_is_log_enabled(cat,VCOS_LOG_TRACE)) vcos_log_dump_mem_impl(cat,label,addr,voidMem,numBytes); } while (0)
Definition at line 194 of file khrn_misc.h.
vcos_log_dump_mem [2/3]
#define vcos_log_dump_mem (cat, label, addr, voidMem, numBytes) do { if (vcos_is_log_enabled(cat,VCOS_LOG_TRACE)) vcos_log_dump_mem_impl(cat,label,addr,voidMem,numBytes); } while (0)
vcos_log_dump_mem [3/3]
#define vcos_log_dump_mem (cat, label, addr, voidMem, numBytes) do { if (vcos_is_log_enabled(cat,VCOS_LOG_TRACE)) vcos_log_dump_mem_impl(cat,label,addr,voidMem,numBytes); } while (0)
VCOS_LOG_INIT [1/3]
#define VCOS_LOG_INIT (n, l) { l, n, 0, {0}, 0, 0 }
VCOS_LOG_INIT [2/3]
#define VCOS_LOG_INIT (n, l) { l, n, 0, {0}, 0, 0 }
Initialize a logging category without going through vcos_log_register().
This is useful for the case where there is no obvious point to do the registration (no initialization function for the module). However, it means that your logging category is not registered, so cannot be easily changed at run-time.
Definition at line 98 of file khrn_misc.h.
VCOS_LOG_INIT [3/3]
#define VCOS_LOG_INIT (n, l) { l, n, 0, {0}, 0, 0 }
vcos_log_platform_init [1/3]
#define vcos_log_platform_init () (void)0
vcos_log_platform_init [2/3]
#define vcos_log_platform_init () (void)0
vcos_log_platform_init [3/3]
#define vcos_log_platform_init () (void)0
Definition at line 206 of file khrn_misc.h.
vcos_log_platform_register [1/3]
#define vcos_log_platform_register (category) (void)0
Definition at line 210 of file khrn_misc.h.
vcos_log_platform_register [2/3]
#define vcos_log_platform_register (category) (void)0
vcos_log_platform_register [3/3]
#define vcos_log_platform_register (category) (void)0
vcos_log_platform_unregister [1/3]
#define vcos_log_platform_unregister (category) (void)0
vcos_log_platform_unregister [2/3]
#define vcos_log_platform_unregister (category) (void)0
Referenced by vcos_log_unregister().
vcos_log_platform_unregister [3/3]
#define vcos_log_platform_unregister (category) (void)0
Definition at line 214 of file khrn_misc.h.
VCOS_LOGGING_H [1/2]
#define VCOS_LOGGING_H
VCOS_LOGGING_H [2/2]
#define VCOS_LOGGING_H
Typedef Documentation
VCOS_LOG_CAT_T
typedef struct VCOS_LOG_CAT_T VCOS_LOG_CAT_T
A registered logging category.
VCOS_LOG_LEVEL_T
typedef enum VCOS_LOG_LEVEL_T VCOS_LOG_LEVEL_T
Logging levels
VCOS_VLOG_IMPL_FUNC_T
typedef void(* VCOS_VLOG_IMPL_FUNC_T) (const VCOS_LOG_CAT_T *cat, VCOS_LOG_LEVEL_T _level, const char *fmt, va_list args)
Definition at line 114 of file vcos_logging.h.
Enumeration Type Documentation
VCOS_LOG_LEVEL_T
enum VCOS_LOG_LEVEL_T
Logging levels
Enumerator
VCOS_LOG_UNINITIALIZED
VCOS_LOG_NEVER
VCOS_LOG_ERROR
VCOS_LOG_WARN
VCOS_LOG_INFO
VCOS_LOG_TRACE
Definition at line 80 of file vcos_logging.h.
 {
    VCOS_LOG_UNINITIALIZED   = 0,
    VCOS_LOG_NEVER,
    VCOS_LOG_ERROR,
    VCOS_LOG_WARN,
    VCOS_LOG_INFO,
    VCOS_LOG_TRACE,
 } VCOS_LOG_LEVEL_T;
Function Documentation
vcos_log_dump_mem_impl()
void vcos_log_dump_mem_impl (const VCOS_LOG_CAT_T * cat, const char * label, uint32_t addr, const void * voidMem, size_t numBytes)
Definition at line 488 of file vcos_logcat.c.
References mem, NULL, offset, vcos_log_impl(), VCOS_LOG_INFO, and vcos_snprintf().
Referenced by vcos_log_set_level().
 {
    const uint8_t  *mem = (const uint8_t *)voidMem;
    size_t          offset;
    char            lineBuf[ 100 ];
    char           *s;
    while ( numBytes > 0 )
    {
        s = lineBuf;
        for ( offset = 0; offset < 16; offset++ )
        {
            if ( offset < numBytes )
            {
                s += vcos_snprintf( s, 4, "%02x ", mem[ offset ]);
            }
            else
            {
                s += vcos_snprintf( s, 4, "   " );
            }
        }
        for ( offset = 0; offset < 16; offset++ )
        {
            if ( offset < numBytes )
            {
                uint8_t ch = mem[ offset ];
                if (( ch < ' ' ) || ( ch > '~' ))
                {
                    ch = '.';
                }
                *s++ = (char)ch;
            }
        }
        *s++ = '\0';
        if (( label != NULL ) && ( *label != '\0' ))
        {
           vcos_log_impl( cat, VCOS_LOG_INFO, "%s: %08" PRIx32 ": %s", label, addr, lineBuf );
        }
        else
        {
           vcos_log_impl( cat, VCOS_LOG_INFO, "%08" PRIx32 ": %s", addr, lineBuf );
        }
        addr += 16;
        mem += 16;
        if ( numBytes > 16 )
        {
            numBytes -= 16;
        }
        else
        {
            numBytes = 0;
        }
    }
 }
vcos_log_get_default_category()
VCOSPRE_ const VCOS_LOG_CAT_T* VCOSPOST_ vcos_log_get_default_category (void)
Return a default logging category, for people too lazy to create their own.
Using the default category will be slow (there's an extra function call overhead). Don't do this in normal code.
Definition at line 478 of file vcos_logcat.c.
 {
    return &dflt_log_category;
 }
vcos_log_impl()
VCOSPRE_ void VCOSPOST_ vcos_log_impl (const VCOS_LOG_CAT_T * cat, VCOS_LOG_LEVEL_T _level, const char * fmt, ...)
Log a message. Basic API. Normal code should not use this. The platform needs to implement this function.
vcos_log_level_to_string()
VCOSPRE_ const char* VCOSPOST_ vcos_log_level_to_string (VCOS_LOG_LEVEL_T level)
Convert a VCOS_LOG_LEVEL_T into a printable string. The platform needs to implement this function.
Definition at line 320 of file vcos_logcat.c.
References VCOS_LOG_ERROR, VCOS_LOG_INFO, VCOS_LOG_NEVER, VCOS_LOG_TRACE, VCOS_LOG_UNINITIALIZED, and VCOS_LOG_WARN.
 {
    switch (level)
    {
       case VCOS_LOG_UNINITIALIZED:  return "uninit";
       case VCOS_LOG_NEVER:          return "never";
       case VCOS_LOG_ERROR:          return "error";
       case VCOS_LOG_WARN:           return "warn";
       case VCOS_LOG_INFO:           return "info";
       case VCOS_LOG_TRACE:          return "trace";
    }
    return "???";
 }
vcos_log_register()
VCOSPRE_ void VCOSPOST_ vcos_log_register (const char * name, VCOS_LOG_CAT_T * category)
Register a logging category.
Parameters
name the name of this category.
category the category to register.
Definition at line 373 of file vcos_logcat.c.
References VCOS_LOG_CAT_T::flags, VCOS_LOG_CAT_T::level, name, VCOS_LOG_CAT_T::name, VCOS_LOG_ERROR, VCOS_LOG_UNINITIALIZED, and VCOS_LOG_CAT_T::want_prefix.
Referenced by ilclient_init(), main(), OpenVideoCoreMemoryFileWithOffset(), raspitex_init(), vc_hostfs_init(), vc_vchi_tv_init(), and wfc_server_connect().
 {
    const char *env;
    VCOS_LOG_CAT_T *i;
    category->name  = name;
    if ( category->level == VCOS_LOG_UNINITIALIZED )
    {
       category->level = VCOS_LOG_ERROR;
    }
    category->flags.want_prefix = (category != &dflt_log_category );
    vcos_mutex_lock(&lock);
    /* is it already registered? */
    for (i = vcos_logging_categories; i ; i = i->next )
    {
       if (i == category)
       {
          i->refcount++;
          break;
       }
    }
    if (!i)
    {
       /* not yet registered */
       category->next = vcos_logging_categories;
       vcos_logging_categories = category;
       category->refcount++;
       vcos_log_platform_register(category);
    }
    vcos_mutex_unlock(&lock);
    /* Check to see if this log level has been enabled. Look for
     * (<category:level>,)*
     *
     * VC_LOGLEVEL=ilcs:info,vchiq:warn
     */
    env = _VCOS_LOG_LEVEL();
    if (env && env[0])
    {
       do
       {
          char env_name[64];
          VCOS_LOG_LEVEL_T level;
          if (read_tok(env_name, sizeof(env_name), &env, ':') &&
              read_level(&level, &env, ','))
          {
             if (strcmp(env_name, name) == 0 || strcmp(env_name, "*") == 0)
             {
                // we could match both * and env_name, so make sure * comes
                // first in the logging_level string
                category->level = level;
             }
          }
          else
          {
             if (!warned_loglevel)
             {
                 vcos_log("VC_LOGLEVEL format invalid at %s\n", env);
                 warned_loglevel = 1;
             }
             return;
          }
       } while (env[0] != '\0');
    }
    vcos_log_info( "Registered log category '%s' with level %s",
                   category->name,
                   vcos_log_level_to_string( category->level ));
 }
vcos_log_set_level()
VCOS_STATIC_INLINE void vcos_log_set_level (VCOS_LOG_CAT_T * category, VCOS_LOG_LEVEL_T level)
Set the logging level for a category at run time. Without this, the level will be that set by vcos_log_register from a platform-specific source.
Parameters
category the category to modify.
level the new logging level for this category.
Definition at line 180 of file vcos_logging.h.
References VCOS_LOG_CAT_T::level, vcos_log_dump_mem_impl(), vcos_log_set_level_all(), VCOSPOST_, and VCOSPRE_.
Referenced by ilclient_init(), mmal_logging_init(), mmalomx_logging_init(), raspitex_init(), vc_vchi_tv_init(), and wfc_server_connect().
 {
    category->level = level;
 }
vcos_log_set_level_all()
VCOSPRE_ void VCOSPOST_ vcos_log_set_level_all (char * levels)
Set the logging levels for many categories at once.
Set lots of categorys from a string cat:lev,cat:lev This can be used at startup time to set a bunch of category levels from a single string. Used with C(vcos_logging_level)
Referenced by vcos_log_set_level().
vcos_log_unregister()
VCOSPRE_ void VCOSPOST_ vcos_log_unregister (VCOS_LOG_CAT_T * category)
Unregister a logging category.
Definition at line 449 of file vcos_logcat.c.
References VCOS_LOG_CAT_T::next, NULL, VCOS_LOG_CAT_T::refcount, vcos_assert, vcos_log_platform_unregister, vcos_logging_categories, vcos_mutex_lock(), and vcos_mutex_unlock().
Referenced by ilclient_destroy(), vc_hostfs_exit(), wfc_server_connect(), and wfc_server_disconnect().
 {
    VCOS_LOG_CAT_T **pcat;
    vcos_mutex_lock(&lock);
    category->refcount--;
    if (category->refcount == 0)
    {
       pcat = &vcos_logging_categories;
       while (*pcat != category)
       {
          if (!*pcat)
             break;   /* possibly deregistered twice? */
          if ((*pcat)->next == NULL)
          {
             vcos_assert(0); /* already removed! */
             vcos_mutex_unlock(&lock);
             return;
          }
          pcat = &(*pcat)->next;
       }
       if (*pcat)
          *pcat = category->next;
       vcos_log_platform_unregister(category);
    }
    vcos_mutex_unlock(&lock);
 }
vcos_logging_init()
VCOSPRE_ void VCOSPOST_ VCOSPRE_ void VCOSPOST_ vcos_logging_init (void)
Definition at line 261 of file vcos_logcat.c.
 {
    if (inited)
    {
       /* FIXME: should print a warning or something here */
       return;
    }
    vcos_mutex_create(&lock, "vcos_log");
    vcos_log_platform_init();
    vcos_log_register("default", &dflt_log_category);
 #if VCOS_WANT_LOG_CMD
    vcos_cmd_register( &cmd_log );
 #endif
    vcos_assert(!inited);
    inited = 1;
 }
vcos_set_log_options()
VCOSPRE_ void VCOSPOST_ vcos_set_log_options (const char * opt)
Definition at line 483 of file vcos_logcat.c.
References void().
 {
    (void)opt;
 }
vcos_set_vlog_impl()
VCOSPRE_ void VCOSPOST_ VCOSPRE_ void VCOSPOST_ VCOSPRE_ void VCOSPOST_ vcos_set_vlog_impl (VCOS_VLOG_IMPL_FUNC_T vlog_impl_func)
Set the function which does the actual logging output. Passing in NULL causes the default logging function to be used.
Definition at line 566 of file vcos_logcat.c.
References NULL.
 {
    if ( vlog_impl_func == NULL )
    {
       vcos_vlog_impl_func = vcos_vlog_default_impl;
    }
    else
    {
       vcos_vlog_impl_func = vlog_impl_func;
    }
 }
vcos_string_to_log_level()
VCOSPRE_ VCOS_STATUS_T VCOSPOST_ vcos_string_to_log_level (const char * str, VCOS_LOG_LEVEL_T * level)
Convert a string into a VCOS_LOG_LEVEL_T The platform needs to implement this function.
Definition at line 334 of file vcos_logcat.c.
References VCOS_EINVAL, VCOS_LOG_ERROR, VCOS_LOG_INFO, VCOS_LOG_NEVER, VCOS_LOG_TRACE, VCOS_LOG_WARN, and VCOS_SUCCESS.
 {
    if (strcmp(str,"error") == 0)
       *level = VCOS_LOG_ERROR;
    else if (strcmp(str,"never") == 0)
       *level = VCOS_LOG_NEVER;
    else if (strcmp(str,"warn") == 0)
       *level = VCOS_LOG_WARN;
    else if (strcmp(str,"warning") == 0)
       *level = VCOS_LOG_WARN;
    else if (strcmp(str,"info") == 0)
       *level = VCOS_LOG_INFO;
    else if (strcmp(str,"trace") == 0)
       *level = VCOS_LOG_TRACE;
    else
       return VCOS_EINVAL;
    return VCOS_SUCCESS;
 }
vcos_vlog_default_impl()
VCOSPRE_ void VCOSPOST_ vcos_vlog_default_impl (const VCOS_LOG_CAT_T * cat, VCOS_LOG_LEVEL_T _level, const char * fmt, va_list args)
The default logging function, which is provided by each platform.
vcos_vlog_impl()
VCOSPRE_ void VCOSPOST_ VCOSPRE_ void VCOSPOST_ vcos_vlog_impl (const VCOS_LOG_CAT_T * cat, VCOS_LOG_LEVEL_T _level, const char * fmt, va_list args)
Log a message using a varargs parameter list. Normal code should not use this.