VideoCore Library: interface/khronos/common/khrn_client_vector.c File Reference
khrn_client_vector.c File Reference
#include "interface/khronos/common/khrn_int_common.h"
#include "interface/khronos/common/khrn_client_platform.h"
#include "interface/khronos/common/khrn_client_vector.h"
#include <stdlib.h>
#include <string.h>
Functions
void khrn_vector_init (KHRN_VECTOR_T *vector, uint32_t capacity)
void khrn_vector_term (KHRN_VECTOR_T *vector)
bool khrn_vector_extend (KHRN_VECTOR_T *vector, uint32_t size)
void khrn_vector_clear (KHRN_VECTOR_T *vector)
Function Documentation
khrn_vector_clear()
void khrn_vector_clear (KHRN_VECTOR_T * vector)
Definition at line 74 of file khrn_client_vector.c.
References KHRN_VECTOR_T::capacity, KHRN_VECTOR_T::data, khrn_platform_free(), NULL, and KHRN_VECTOR_T::size.
 {
    if (vector->data) {
       khrn_platform_free(vector->data);
    }
    vector->data = NULL;
    vector->capacity = 0;
    vector->size = 0;
 }
khrn_vector_extend()
bool khrn_vector_extend (KHRN_VECTOR_T * vector, uint32_t size)
Definition at line 50 of file khrn_client_vector.c.
References _max, KHRN_VECTOR_T::capacity, KHRN_VECTOR_T::data, khrn_platform_free(), khrn_platform_malloc(), and KHRN_VECTOR_T::size.
 {
    uint32_t req_capacity = vector->size + size;
    if (req_capacity > vector->capacity) {
       uint32_t new_capacity = _max(vector->capacity + (vector->capacity >> 1), req_capacity);
       void *new_data = khrn_platform_malloc(new_capacity, "KHRN_VECTOR_T.data");
       if (!new_data) {
          new_capacity = req_capacity;
          new_data = khrn_platform_malloc(new_capacity, "KHRN_VECTOR_T.data");
          if (!new_data) {
             return false;
          }
       }
       if (vector->data) {
          memcpy(new_data, vector->data, vector->size);
          khrn_platform_free(vector->data);
       }
       vector->data = new_data;
       vector->capacity = new_capacity;
    }
    vector->size += size;
    return true;
 }
khrn_vector_init()
void khrn_vector_init (KHRN_VECTOR_T * vector, uint32_t capacity)
Definition at line 36 of file khrn_client_vector.c.
References KHRN_VECTOR_T::capacity, KHRN_VECTOR_T::data, khrn_platform_malloc(), NULL, and KHRN_VECTOR_T::size.
 {
    vector->data = (capacity == 0) ? NULL : khrn_platform_malloc(capacity, "KHRN_VECTOR_T.data");
    vector->capacity = vector->data ? capacity : 0;
    vector->size = 0;
 }
khrn_vector_term()
void khrn_vector_term (KHRN_VECTOR_T * vector)
Definition at line 43 of file khrn_client_vector.c.
References KHRN_VECTOR_T::data, and khrn_platform_free().
 {
    if (vector->data) {
       khrn_platform_free(vector->data);
    }
 }