VideoCore Library: interface/vchiq_arm/vchiq_lib.c File Reference
vchiq_lib.c File Reference
#include <unistd.h>
#include <fcntl.h>
#include <sys/ioctl.h>
#include <stdio.h>
#include "vchiq.h"
#include "vchiq_cfg.h"
#include "vchiq_ioctl.h"
#include "interface/vchi/vchi.h"
#include "interface/vchi/common/endian.h"
#include "interface/vcos/vcos.h"
Classes
struct vchiq_service_struct
struct vchiq_instance_struct
Macros
#define IS_POWER_2(x) ((x & (x - 1)) == 0)
#define VCHIQ_MAX_INSTANCE_SERVICES 32
#define MSGBUF_SIZE (VCHIQ_MAX_MSG_SIZE + sizeof(VCHIQ_HEADER_T))
#define RETRY(r, x) do { r = x; } while ((r == -1) && (errno == EINTR))
#define VCOS_LOG_CATEGORY (&vchiq_lib_log_category)
Typedefs
typedef struct vchiq_service_struct VCHIQ_SERVICE_T
typedef struct vchiq_service_struct VCHI_SERVICE_T
typedef struct vchiq_instance_struct VCHI_STATE_T
Functions
vcos_static_assert (IS_POWER_2(VCHIQ_MAX_INSTANCE_SERVICES))
VCHIQ_STATUS_T vchiq_initialise_fd (VCHIQ_INSTANCE_T *pinstance, int dev_vchiq_fd)
VCHIQ_STATUS_T vchiq_initialise (VCHIQ_INSTANCE_T *pinstance)
VCHIQ_STATUS_T vchiq_shutdown (VCHIQ_INSTANCE_T instance)
VCHIQ_STATUS_T vchiq_connect (VCHIQ_INSTANCE_T instance)
VCHIQ_STATUS_T vchiq_add_service (VCHIQ_INSTANCE_T instance, const VCHIQ_SERVICE_PARAMS_T *params, VCHIQ_SERVICE_HANDLE_T *phandle)
VCHIQ_STATUS_T vchiq_open_service (VCHIQ_INSTANCE_T instance, const VCHIQ_SERVICE_PARAMS_T *params, VCHIQ_SERVICE_HANDLE_T *phandle)
VCHIQ_STATUS_T vchiq_close_service (VCHIQ_SERVICE_HANDLE_T handle)
VCHIQ_STATUS_T vchiq_remove_service (VCHIQ_SERVICE_HANDLE_T handle)
VCHIQ_STATUS_T vchiq_queue_message (VCHIQ_SERVICE_HANDLE_T handle, const VCHIQ_ELEMENT_T *elements, int count)
void vchiq_release_message (VCHIQ_SERVICE_HANDLE_T handle, VCHIQ_HEADER_T *header)
VCHIQ_STATUS_T vchiq_queue_bulk_transmit (VCHIQ_SERVICE_HANDLE_T handle, const void *data, int size, void *userdata)
VCHIQ_STATUS_T vchiq_queue_bulk_receive (VCHIQ_SERVICE_HANDLE_T handle, void *data, int size, void *userdata)
VCHIQ_STATUS_T vchiq_queue_bulk_transmit_handle (VCHIQ_SERVICE_HANDLE_T handle, VCHI_MEM_HANDLE_T memhandle, const void *offset, int size, void *userdata)
VCHIQ_STATUS_T vchiq_queue_bulk_receive_handle (VCHIQ_SERVICE_HANDLE_T handle, VCHI_MEM_HANDLE_T memhandle, void *offset, int size, void *userdata)
VCHIQ_STATUS_T vchiq_bulk_transmit (VCHIQ_SERVICE_HANDLE_T handle, const void *data, int size, void *userdata, VCHIQ_BULK_MODE_T mode)
VCHIQ_STATUS_T vchiq_bulk_receive (VCHIQ_SERVICE_HANDLE_T handle, void *data, int size, void *userdata, VCHIQ_BULK_MODE_T mode)
VCHIQ_STATUS_T vchiq_bulk_transmit_handle (VCHIQ_SERVICE_HANDLE_T handle, VCHI_MEM_HANDLE_T memhandle, const void *offset, int size, void *userdata, VCHIQ_BULK_MODE_T mode)
VCHIQ_STATUS_T vchiq_bulk_receive_handle (VCHIQ_SERVICE_HANDLE_T handle, VCHI_MEM_HANDLE_T memhandle, void *offset, int size, void *userdata, VCHIQ_BULK_MODE_T mode, int(*copy_pagelist)())
int vchiq_get_client_id (VCHIQ_SERVICE_HANDLE_T handle)
void * vchiq_get_service_userdata (VCHIQ_SERVICE_HANDLE_T handle)
int vchiq_get_service_fourcc (VCHIQ_SERVICE_HANDLE_T handle)
VCHIQ_STATUS_T vchiq_get_config (VCHIQ_INSTANCE_T instance, int config_size, VCHIQ_CONFIG_T *pconfig)
int32_t vchiq_use_service (const VCHIQ_SERVICE_HANDLE_T handle)
int32_t vchiq_release_service (const VCHIQ_SERVICE_HANDLE_T handle)
VCHIQ_STATUS_T vchiq_set_service_option (VCHIQ_SERVICE_HANDLE_T handle, VCHIQ_SERVICE_OPTION_T option, int value)
const VCHI_MESSAGE_DRIVER_T * vchi_mphi_message_driver_func_table (void)
const VCHI_CONNECTION_API_T * single_get_func_table (void)
VCHI_CONNECTION_T * vchi_create_connection (const VCHI_CONNECTION_API_T *function_table, const VCHI_MESSAGE_DRIVER_T *low_level)
int32_t vchi_msg_peek (VCHI_SERVICE_HANDLE_T handle, void **data, uint32_t *msg_size, VCHI_FLAGS_T flags)
int32_t vchi_msg_remove (VCHI_SERVICE_HANDLE_T handle)
int32_t vchi_msg_queue (VCHI_SERVICE_HANDLE_T handle, const void *data, uint32_t data_size, VCHI_FLAGS_T flags, void *msg_handle)
int32_t vchi_bulk_queue_receive (VCHI_SERVICE_HANDLE_T handle, void *data_dst, uint32_t data_size, VCHI_FLAGS_T flags, void *bulk_handle)
int32_t vchi_bulk_queue_transmit (VCHI_SERVICE_HANDLE_T handle, const void *data_src, uint32_t data_size, VCHI_FLAGS_T flags, void *bulk_handle)
int32_t vchi_msg_dequeue (VCHI_SERVICE_HANDLE_T handle, void *data, uint32_t max_data_size_to_read, uint32_t *actual_msg_size, VCHI_FLAGS_T flags)
vcos_static_assert (sizeof(VCHI_MSG_VECTOR_T)==sizeof(VCHIQ_ELEMENT_T))
vcos_static_assert (offsetof(VCHI_MSG_VECTOR_T, vec_base)==offsetof(VCHIQ_ELEMENT_T, data))
vcos_static_assert (offsetof(VCHI_MSG_VECTOR_T, vec_len)==offsetof(VCHIQ_ELEMENT_T, size))
int32_t vchi_msg_queuev (VCHI_SERVICE_HANDLE_T handle, VCHI_MSG_VECTOR_T *vector, uint32_t count, VCHI_FLAGS_T flags, void *msg_handle)
int32_t vchi_held_msg_release (VCHI_HELD_MSG_T *message)
int32_t vchi_msg_hold (VCHI_SERVICE_HANDLE_T handle, void **data, uint32_t *msg_size, VCHI_FLAGS_T flags, VCHI_HELD_MSG_T *message_handle)
int32_t vchi_initialise (VCHI_INSTANCE_T *instance_handle)
int32_t vchi_connect (VCHI_CONNECTION_T **connections, const uint32_t num_connections, VCHI_INSTANCE_T instance_handle)
int32_t vchi_disconnect (VCHI_INSTANCE_T instance_handle)
int32_t vchi_service_open (VCHI_INSTANCE_T instance_handle, SERVICE_CREATION_T *setup, VCHI_SERVICE_HANDLE_T *handle)
int32_t vchi_service_create (VCHI_INSTANCE_T instance_handle, SERVICE_CREATION_T *setup, VCHI_SERVICE_HANDLE_T *handle)
int32_t vchi_service_close (const VCHI_SERVICE_HANDLE_T handle)
int32_t vchi_service_destroy (const VCHI_SERVICE_HANDLE_T handle)
uint32_t vchi_readbuf_uint32 (const void *_ptr)
void vchi_writebuf_uint32 (void *_ptr, uint32_t value)
uint16_t vchi_readbuf_uint16 (const void *_ptr)
void vchi_writebuf_uint16 (void *_ptr, uint16_t value)
int32_t vchi_service_use (const VCHI_SERVICE_HANDLE_T handle)
int32_t vchi_service_release (const VCHI_SERVICE_HANDLE_T handle)
int32_t vchi_service_set_option (const VCHI_SERVICE_HANDLE_T handle, VCHI_SERVICE_OPTION_T option, int value)
VCHIQ_STATUS_T vchiq_dump_phys_mem (VCHIQ_SERVICE_HANDLE_T handle, void *ptr, size_t num_bytes)
Variables
struct vchiq_instance_struct vchiq_instance
Macro Definition Documentation
IS_POWER_2
#define IS_POWER_2 (x) ((x & (x - 1)) == 0)
Definition at line 40 of file vchiq_lib.c.
MSGBUF_SIZE
#define MSGBUF_SIZE (VCHIQ_MAX_MSG_SIZE + sizeof(VCHIQ_HEADER_T))
Definition at line 42 of file vchiq_lib.c.
RETRY
#define RETRY (r, x) do { r = x; } while ((r == -1) && (errno == EINTR))
Definition at line 44 of file vchiq_lib.c.
Referenced by vchiq_dump_phys_mem().
VCHIQ_MAX_INSTANCE_SERVICES
#define VCHIQ_MAX_INSTANCE_SERVICES 32
Definition at line 41 of file vchiq_lib.c.
VCOS_LOG_CATEGORY
#define VCOS_LOG_CATEGORY (&vchiq_lib_log_category)
Definition at line 46 of file vchiq_lib.c.
Typedef Documentation
VCHI_SERVICE_T
typedef struct vchiq_service_struct VCHI_SERVICE_T
Definition at line 61 of file vchiq_lib.c.
VCHI_STATE_T
typedef struct vchiq_instance_struct VCHI_STATE_T
Definition at line 75 of file vchiq_lib.c.
VCHIQ_SERVICE_T
typedef struct vchiq_service_struct VCHIQ_SERVICE_T
Function Documentation
single_get_func_table()
const VCHI_CONNECTION_API_T* single_get_func_table (void)
Definition at line 672 of file vchiq_lib.c.
References NULL.
 {
    return NULL;
 }
vchi_bulk_queue_receive()
int32_t vchi_bulk_queue_receive (VCHI_SERVICE_HANDLE_T handle, void * data_dst, uint32_t data_size, VCHI_FLAGS_T flags, void * bulk_handle)
Definition at line 806 of file vchiq_lib.c.
 {
    VCHI_SERVICE_T *service = find_service_by_handle(handle);
    VCHIQ_QUEUE_BULK_TRANSFER_T args;
    int ret;
    if (!service)
       return VCHIQ_ERROR;
    switch ((int)flags) {
    case VCHI_FLAGS_CALLBACK_WHEN_OP_COMPLETE | VCHI_FLAGS_BLOCK_UNTIL_QUEUED:
       args.mode = VCHIQ_BULK_MODE_CALLBACK;
       break;
    case VCHI_FLAGS_BLOCK_UNTIL_OP_COMPLETE:
       args.mode = VCHIQ_BULK_MODE_BLOCKING;
       break;
    case VCHI_FLAGS_BLOCK_UNTIL_QUEUED:
    case VCHI_FLAGS_NONE:
       args.mode = VCHIQ_BULK_MODE_NOCALLBACK;
       break;
    default:
       vcos_assert(0);
       break;
    }
    args.handle = service->handle;
    args.data = data_dst;
    args.size = data_size;
    args.userdata = bulk_handle;
    RETRY(ret, ioctl(service->fd, VCHIQ_IOC_QUEUE_BULK_RECEIVE, &args));
    return ret;
 }
vchi_bulk_queue_transmit()
int32_t vchi_bulk_queue_transmit (VCHI_SERVICE_HANDLE_T handle, const void * data_src, uint32_t data_size, VCHI_FLAGS_T flags, void * bulk_handle)
Definition at line 859 of file vchiq_lib.c.
 {
    VCHI_SERVICE_T *service = find_service_by_handle(handle);
    VCHIQ_QUEUE_BULK_TRANSFER_T args;
    int ret;
    if (!service)
       return VCHIQ_ERROR;
    switch ((int)flags) {
    case VCHI_FLAGS_CALLBACK_WHEN_OP_COMPLETE | VCHI_FLAGS_BLOCK_UNTIL_QUEUED:
       args.mode = VCHIQ_BULK_MODE_CALLBACK;
       break;
    case VCHI_FLAGS_BLOCK_UNTIL_DATA_READ:
    case VCHI_FLAGS_BLOCK_UNTIL_OP_COMPLETE:
       args.mode = VCHIQ_BULK_MODE_BLOCKING;
       break;
    case VCHI_FLAGS_BLOCK_UNTIL_QUEUED:
    case VCHI_FLAGS_NONE:
       args.mode = VCHIQ_BULK_MODE_NOCALLBACK;
       break;
    default:
       vcos_assert(0);
       break;
    }
    args.handle = service->handle;
    args.data = (void *)data_src;
    args.size = data_size;
    args.userdata = bulk_handle;
    RETRY(ret, ioctl(service->fd, VCHIQ_IOC_QUEUE_BULK_TRANSMIT, &args));
    return ret;
 }
vchi_connect()
int32_t vchi_connect (VCHI_CONNECTION_T ** connections, const uint32_t num_connections, VCHI_INSTANCE_T instance_handle)
Definition at line 1121 of file vchiq_lib.c.
References status, vchiq_connect(), VCHIQ_SUCCESS, and vcos_unused.
Referenced by main().
 {
    VCHIQ_STATUS_T status;
    vcos_unused(connections);
    vcos_unused(num_connections);
    status = vchiq_connect((VCHIQ_INSTANCE_T)instance_handle);
    return (status == VCHIQ_SUCCESS) ? 0 : -1;
 }
vchi_create_connection()
VCHI_CONNECTION_T* vchi_create_connection (const VCHI_CONNECTION_API_T * function_table, const VCHI_MESSAGE_DRIVER_T * low_level)
Definition at line 678 of file vchiq_lib.c.
References NULL, and vcos_unused.
 {
    vcos_unused(function_table);
    vcos_unused(low_level);
    return NULL;
 }
vchi_disconnect()
int32_t vchi_disconnect (VCHI_INSTANCE_T instance_handle)
Definition at line 1148 of file vchiq_lib.c.
References status, vchiq_shutdown(), and VCHIQ_SUCCESS.
Referenced by main().
 {
    VCHIQ_STATUS_T status;
    status = vchiq_shutdown((VCHIQ_INSTANCE_T)instance_handle);
    return (status == VCHIQ_SUCCESS) ? 0 : -1;
 }
vchi_held_msg_release()
int32_t vchi_held_msg_release (VCHI_HELD_MSG_T * message)
Definition at line 1020 of file vchiq_lib.c.
References VCHI_HELD_MSG_T::message, and VCHI_HELD_MSG_T::service.
 {
    int ret = -1;
    if (message && message->message && !message->service)
    {
       free_msgbuf(message->message);
       ret = 0;
    }
    return ret;
 }
vchi_initialise()
int32_t vchi_initialise (VCHI_INSTANCE_T * instance_handle)
Definition at line 1094 of file vchiq_lib.c.
Referenced by bcm_host_init(), and main().
 {
    VCHIQ_INSTANCE_T instance;
    instance = vchiq_lib_init(-1);
    vcos_log_trace( "%s: returning instance handle %p", __func__, instance );
    *instance_handle = (VCHI_INSTANCE_T)instance;
    return (instance != NULL) ? 0 : -1;
 }
vchi_mphi_message_driver_func_table()
const VCHI_MESSAGE_DRIVER_T* vchi_mphi_message_driver_func_table (void)
Definition at line 663 of file vchiq_lib.c.
References NULL.
 {
    return NULL;
 }
vchi_msg_dequeue()
int32_t vchi_msg_dequeue (VCHI_SERVICE_HANDLE_T handle, void * data, uint32_t max_data_size_to_read, uint32_t * actual_msg_size, VCHI_FLAGS_T flags)
Definition at line 913 of file vchiq_lib.c.
 {
    VCHI_SERVICE_T *service = find_service_by_handle(handle);
    VCHIQ_DEQUEUE_MESSAGE_T args;
    int ret;
    vcos_assert(flags == VCHI_FLAGS_NONE || flags == VCHI_FLAGS_BLOCK_UNTIL_OP_COMPLETE);
    if (!service)
       return VCHIQ_ERROR;
    if (service->peek_size >= 0)
    {
       vcos_log_error("vchi_msg_dequeue -> using peek buffer\n");
       if ((uint32_t)service->peek_size <= max_data_size_to_read)
       {
          memcpy(data, service->peek_buf, service->peek_size);
          *actual_msg_size = service->peek_size;
          /* Invalidate the peek data, but retain the buffer */
          service->peek_size = -1;
          ret = 0;
       }
       else
       {
          ret = -1;
       }
    }
    else
    {
       args.handle = service->handle;
       args.blocking = (flags == VCHI_FLAGS_BLOCK_UNTIL_OP_COMPLETE);
       args.bufsize = max_data_size_to_read;
       args.buf = data;
       RETRY(ret, ioctl(service->fd, VCHIQ_IOC_DEQUEUE_MESSAGE, &args));
       if (ret >= 0)
       {
          *actual_msg_size = ret;
          ret = 0;
       }
    }
    if ((ret < 0) && (errno != EWOULDBLOCK))
       fprintf(stderr, "vchi_msg_dequeue -> %d(%d)\n", ret, errno);
    return ret;
 }
vchi_msg_hold()
int32_t vchi_msg_hold (VCHI_SERVICE_HANDLE_T handle, void ** data, uint32_t * msg_size, VCHI_FLAGS_T flags, VCHI_HELD_MSG_T * message_handle)
Definition at line 1050 of file vchiq_lib.c.
 {
    VCHI_SERVICE_T *service = find_service_by_handle(handle);
    int ret;
    if (!service)
       return VCHIQ_ERROR;
    ret = fill_peek_buf(service, flags);
    if (ret == 0)
    {
       *data = service->peek_buf;
       *msg_size = service->peek_size;
       message_handle->message = service->peek_buf;
       message_handle->service = NULL;
       service->peek_size = -1;
       service->peek_buf = NULL;
    }
    return 0;
 }
vchi_msg_peek()
int32_t vchi_msg_peek (VCHI_SERVICE_HANDLE_T handle, void ** data, uint32_t * msg_size, VCHI_FLAGS_T flags)
Definition at line 702 of file vchiq_lib.c.
 {
    VCHI_SERVICE_T *service = find_service_by_handle(handle);
    int ret;
    if (!service)
       return VCHIQ_ERROR;
    ret = fill_peek_buf(service, flags);
    if (ret == 0)
    {
       *data = service->peek_buf;
       *msg_size = service->peek_size;
    }
    return ret;
 }
vchi_msg_queue()
int32_t vchi_msg_queue (VCHI_SERVICE_HANDLE_T handle, const void * data, uint32_t data_size, VCHI_FLAGS_T flags, void * msg_handle)
Definition at line 766 of file vchiq_lib.c.
 {
    VCHI_SERVICE_T *service = find_service_by_handle(handle);
    VCHIQ_QUEUE_MESSAGE_T args;
    VCHIQ_ELEMENT_T element = {data, data_size};
    int ret;
    vcos_unused(msg_handle);
    vcos_assert(flags == VCHI_FLAGS_BLOCK_UNTIL_QUEUED);
    if (!service)
       return VCHIQ_ERROR;
    args.handle = service->handle;
    args.elements = &element;
    args.count = 1;
    RETRY(ret, ioctl(service->fd, VCHIQ_IOC_QUEUE_MESSAGE, &args));
    return ret;
 }
vchi_msg_queuev()
int32_t vchi_msg_queuev (VCHI_SERVICE_HANDLE_T handle, VCHI_MSG_VECTOR_T * vector, uint32_t count, VCHI_FLAGS_T flags, void * msg_handle)
Definition at line 984 of file vchiq_lib.c.
 {
    VCHI_SERVICE_T *service = find_service_by_handle(handle);
    VCHIQ_QUEUE_MESSAGE_T args;
    int ret;
    vcos_unused(msg_handle);
    vcos_assert(flags == VCHI_FLAGS_BLOCK_UNTIL_QUEUED);
    if (!service)
       return VCHIQ_ERROR;
    args.handle = service->handle;
    args.elements = (const VCHIQ_ELEMENT_T *)vector;
    args.count = count;
    RETRY(ret, ioctl(service->fd, VCHIQ_IOC_QUEUE_MESSAGE, &args));
    return ret;
 }
vchi_msg_remove()
int32_t vchi_msg_remove (VCHI_SERVICE_HANDLE_T handle)
Definition at line 735 of file vchiq_lib.c.
 {
    VCHI_SERVICE_T *service = find_service_by_handle(handle);
    if (!service)
       return VCHIQ_ERROR;
    /* Why would you call vchi_msg_remove without calling vchi_msg_peek first? */
    vcos_assert(service->peek_size >= 0);
    /* Invalidate the content but reuse the buffer */
    service->peek_size = -1;
    return 0;
 }
vchi_readbuf_uint16()
uint16_t vchi_readbuf_uint16 (const void * _ptr)
Definition at line 1279 of file vchiq_lib.c.
 {
    const unsigned char *ptr = _ptr;
    return ptr[0] | (ptr[1] << 8);
 }
vchi_readbuf_uint32()
uint32_t vchi_readbuf_uint32 (const void * _ptr)
Definition at line 1254 of file vchiq_lib.c.
 {
    const unsigned char *ptr = _ptr;
    return ptr[0] | (ptr[1] << 8) | (ptr[2] << 16) | (ptr[3] << 24);
 }
vchi_service_close()
int32_t vchi_service_close (const VCHI_SERVICE_HANDLE_T handle)
Definition at line 1217 of file vchiq_lib.c.
Referenced by vc_gpuserv_deinit().
 {
    VCHI_SERVICE_T *service = find_service_by_handle(handle);
    int ret;
    if (!service)
       return VCHIQ_ERROR;
    RETRY(ret,ioctl(service->fd, VCHIQ_IOC_CLOSE_SERVICE, service->handle));
    if (service->is_client)
       service->lib_handle = VCHIQ_SERVICE_HANDLE_INVALID;
    return ret;
 }
vchi_service_create()
int32_t vchi_service_create (VCHI_INSTANCE_T instance_handle, SERVICE_CREATION_T * setup, VCHI_SERVICE_HANDLE_T * handle)
open
Definition at line 1195 of file vchiq_lib.c.
References SERVICE_CREATION_T::callback_param, vchiq_service_params_struct::fourcc, SERVICE_CREATION_T::service_id, status, vchiq_service_params_struct::userdata, VCHI_VERSION_T::version, vchiq_service_params_struct::version, SERVICE_CREATION_T::version, VCHI_VERSION_T::version_min, and vchiq_service_params_struct::version_min.
 {
    VCHIQ_SERVICE_PARAMS_T params;
    VCHIQ_STATUS_T status;
    memset(&params, 0, sizeof(params));
    params.fourcc = setup->service_id;
    params.userdata = setup->callback_param;
    params.version = (short)setup->version.version;
    params.version_min = (short)setup->version.version_min;
    status = create_service((VCHIQ_INSTANCE_T)instance_handle,
       &params,
       setup->callback,
       0,
       (VCHIQ_SERVICE_HANDLE_T *)handle);
    return (status == VCHIQ_SUCCESS) ? 0 : -1;
 }
vchi_service_destroy()
int32_t vchi_service_destroy (const VCHI_SERVICE_HANDLE_T handle)
Definition at line 1234 of file vchiq_lib.c.
 {
    VCHI_SERVICE_T *service = find_service_by_handle(handle);
    int ret;
    if (!service)
       return VCHIQ_ERROR;
    RETRY(ret,ioctl(service->fd, VCHIQ_IOC_REMOVE_SERVICE, service->handle));
    service->lib_handle = VCHIQ_SERVICE_HANDLE_INVALID;
    return ret;
 }
vchi_service_open()
int32_t vchi_service_open (VCHI_INSTANCE_T instance_handle, SERVICE_CREATION_T * setup, VCHI_SERVICE_HANDLE_T * handle)
Definition at line 1172 of file vchiq_lib.c.
References SERVICE_CREATION_T::callback_param, vchiq_service_params_struct::fourcc, SERVICE_CREATION_T::service_id, status, vchiq_service_params_struct::userdata, VCHI_VERSION_T::version, vchiq_service_params_struct::version, SERVICE_CREATION_T::version, VCHI_VERSION_T::version_min, and vchiq_service_params_struct::version_min.
 {
    VCHIQ_SERVICE_PARAMS_T params;
    VCHIQ_STATUS_T status;
    memset(&params, 0, sizeof(params));
    params.fourcc = setup->service_id;
    params.userdata = setup->callback_param;
    params.version = (short)setup->version.version;
    params.version_min = (short)setup->version.version_min;
    status = create_service((VCHIQ_INSTANCE_T)instance_handle,
       &params,
       setup->callback,
       1/*open*/,
       (VCHIQ_SERVICE_HANDLE_T *)handle);
    return (status == VCHIQ_SUCCESS) ? 0 : -1;
 }
vchi_service_release()
int32_t vchi_service_release (const VCHI_SERVICE_HANDLE_T handle)
Definition at line 1330 of file vchiq_lib.c.
Referenced by release_gencmd_service().
 {
    VCHI_SERVICE_T *service = find_service_by_handle(handle);
    int ret;
    if (!service)
       return VCHIQ_ERROR;
    RETRY(ret,ioctl(service->fd, VCHIQ_IOC_RELEASE_SERVICE, service->handle));
    return ret;
 }
vchi_service_set_option()
int32_t vchi_service_set_option (const VCHI_SERVICE_HANDLE_T handle, VCHI_SERVICE_OPTION_T option, int value)
Definition at line 1354 of file vchiq_lib.c.
 {
    VCHIQ_SET_SERVICE_OPTION_T args;
    VCHI_SERVICE_T *service = find_service_by_handle(handle);
    int ret;
    switch (option)
    {
    case VCHI_SERVICE_OPTION_TRACE:
       args.option = VCHIQ_SERVICE_OPTION_TRACE;
       break;
    default:
       service = NULL;
       break;
    }
    if (!service)
       return VCHIQ_ERROR;
    args.handle = service->handle;
    args.value  = value;
    RETRY(ret, ioctl(service->fd, VCHIQ_IOC_SET_SERVICE_OPTION, &args));
    return ret;
 }
vchi_service_use()
int32_t vchi_service_use (const VCHI_SERVICE_HANDLE_T handle)
Definition at line 1308 of file vchiq_lib.c.
Referenced by use_gencmd_service(), vc_dispmanx_update_submit(), vc_tv_hdmi_ddc_read_id(), vc_tv_hdmi_get_supported_modes_new_id(), and VCOS_DEPRECATED().
 {
    VCHI_SERVICE_T *service = find_service_by_handle(handle);
    int ret;
    if (!service)
       return VCHIQ_ERROR;
    RETRY(ret,ioctl(service->fd, VCHIQ_IOC_USE_SERVICE, service->handle));
    return ret;
 }
vchi_writebuf_uint16()
void vchi_writebuf_uint16 (void * _ptr, uint16_t value)
Definition at line 1290 of file vchiq_lib.c.
 {
    unsigned char *ptr = _ptr;
    ptr[0] = (value >> 0)  & 0xFF;
    ptr[1] = (value >> 8)  & 0xFF;
 }
vchi_writebuf_uint32()
void vchi_writebuf_uint32 (void * _ptr, uint32_t value)
Definition at line 1265 of file vchiq_lib.c.
 {
    unsigned char *ptr = _ptr;
    ptr[0] = (unsigned char)((value >> 0)  & 0xFF);
    ptr[1] = (unsigned char)((value >> 8)  & 0xFF);
    ptr[2] = (unsigned char)((value >> 16) & 0xFF);
    ptr[3] = (unsigned char)((value >> 24) & 0xFF);
 }
vchiq_add_service()
VCHIQ_STATUS_T vchiq_add_service (VCHIQ_INSTANCE_T instance, const VCHIQ_SERVICE_PARAMS_T * params, VCHIQ_SERVICE_HANDLE_T * phandle)
open
Definition at line 269 of file vchiq_lib.c.
References vchiq_service_params_struct::callback, vchiq_service_params_struct::fourcc, status, and VCHIQ_ERROR.
 {
    VCHIQ_STATUS_T status;
    vcos_log_trace( "%s called fourcc = 0x%08x (%c%c%c%c)",
                    __func__,
                    params->fourcc,
                    (params->fourcc >> 24) & 0xff,
                    (params->fourcc >> 16) & 0xff,
                    (params->fourcc >>  8) & 0xff,
                    (params->fourcc      ) & 0xff );
    if (!params->callback)
       return VCHIQ_ERROR;
    if (!is_valid_instance(instance))
       return VCHIQ_ERROR;
    status = create_service(instance,
       params,
       NULL/*vchi_callback*/,
       0,
       phandle);
    vcos_log_trace( "%s returning service handle = 0x%08x", __func__, (uint32_t)*phandle );
    return status;
 }
vchiq_bulk_receive()
VCHIQ_STATUS_T vchiq_bulk_receive (VCHIQ_SERVICE_HANDLE_T handle, void * data, int size, void * userdata, VCHIQ_BULK_MODE_T mode)
Definition at line 511 of file vchiq_lib.c.
References NULL, VCHI_MEM_HANDLE_INVALID, and vchiq_bulk_receive_handle().
 {
    return vchiq_bulk_receive_handle(handle, VCHI_MEM_HANDLE_INVALID, data, size, userdata, mode, NULL);
 }
vchiq_bulk_receive_handle()
VCHIQ_STATUS_T vchiq_bulk_receive_handle (VCHIQ_SERVICE_HANDLE_T handle, VCHI_MEM_HANDLE_T memhandle, void * offset, int size, void * userdata, VCHIQ_BULK_MODE_T mode, int(*)() copy_pagelist)
Definition at line 534 of file vchiq_lib.c.
Referenced by vchiq_bulk_receive().
 {
    VCHIQ_SERVICE_T *service = find_service_by_handle(handle);
    VCHIQ_QUEUE_BULK_TRANSFER_T args;
    int ret;
    vcos_assert(memhandle == VCHI_MEM_HANDLE_INVALID);
    vcos_log_trace( "%s called service handle = 0x%08x", __func__, (uint32_t)handle );
    if (!service)
       return VCHIQ_ERROR;
    args.handle = service->handle;
    args.data = offset;
    args.size = size;
    args.userdata = userdata;
    args.mode = mode;
    RETRY(ret, ioctl(service->fd, VCHIQ_IOC_QUEUE_BULK_RECEIVE, &args));
    return (ret >= 0) ? VCHIQ_SUCCESS : VCHIQ_ERROR;
 }
vchiq_bulk_transmit()
VCHIQ_STATUS_T vchiq_bulk_transmit (VCHIQ_SERVICE_HANDLE_T handle, const void * data, int size, void * userdata, VCHIQ_BULK_MODE_T mode)
Definition at line 485 of file vchiq_lib.c.
Referenced by vchiq_bulk_transmit_handle().
 {
    VCHIQ_SERVICE_T *service = find_service_by_handle(handle);
    VCHIQ_QUEUE_BULK_TRANSFER_T args;
    int ret;
    vcos_log_trace( "%s called service handle = 0x%08x", __func__, (uint32_t)handle );
    if (!service)
       return VCHIQ_ERROR;
    args.handle = service->handle;
    args.data = (void *)data;
    args.size = size;
    args.userdata = userdata;
    args.mode = mode;
    RETRY(ret, ioctl(service->fd, VCHIQ_IOC_QUEUE_BULK_TRANSMIT, &args));
    return (ret >= 0) ? VCHIQ_SUCCESS : VCHIQ_ERROR;
 }
vchiq_bulk_transmit_handle()
VCHIQ_STATUS_T vchiq_bulk_transmit_handle (VCHIQ_SERVICE_HANDLE_T handle, VCHI_MEM_HANDLE_T memhandle, const void * offset, int size, void * userdata, VCHIQ_BULK_MODE_T mode)
Definition at line 521 of file vchiq_lib.c.
References VCHI_MEM_HANDLE_INVALID, vchiq_bulk_transmit(), and vcos_assert.
 {
    vcos_assert(memhandle == VCHI_MEM_HANDLE_INVALID);
    return vchiq_bulk_transmit(handle, offset, size, userdata, mode);
 }
vchiq_close_service()
VCHIQ_STATUS_T vchiq_close_service (VCHIQ_SERVICE_HANDLE_T handle)
Definition at line 333 of file vchiq_lib.c.
 {
    VCHIQ_SERVICE_T *service = find_service_by_handle(handle);
    int ret;
    vcos_log_trace( "%s called service handle = 0x%08x", __func__, (uint32_t)handle );
    if (!service)
       return VCHIQ_ERROR;
    RETRY(ret,ioctl(service->fd, VCHIQ_IOC_CLOSE_SERVICE, service->handle));
    if (service->is_client)
       service->lib_handle = VCHIQ_SERVICE_HANDLE_INVALID;
    if (ret != 0)
       return VCHIQ_ERROR;
    return VCHIQ_SUCCESS;
 }
vchiq_connect()
VCHIQ_STATUS_T vchiq_connect (VCHIQ_INSTANCE_T instance)
Definition at line 230 of file vchiq_lib.c.
References status, and VCHIQ_SUCCESS.
Referenced by vc_vchi_khronos_init(), and vchi_connect().
 {
    VCHIQ_STATUS_T status = VCHIQ_SUCCESS;
    VCOS_THREAD_ATTR_T attrs;
    int ret;
    vcos_log_trace( "%s called", __func__ );
    if (!is_valid_instance(instance))
       return VCHIQ_ERROR;
    vcos_mutex_lock(&instance->mutex);
    if (instance->connected)
       goto out;
    ret = ioctl(instance->fd, VCHIQ_IOC_CONNECT, 0);
    if (ret != 0)
    {
       status = VCHIQ_ERROR;
       goto out;
    }
    vcos_thread_attr_init(&attrs);
    if (vcos_thread_create(&instance->completion_thread, "VCHIQ completion",
                           &attrs, completion_thread, instance) != VCOS_SUCCESS)
    {
       status = VCHIQ_ERROR;
       goto out;
    }
    instance->connected = 1;
 out:
    vcos_mutex_unlock(&instance->mutex);
    return status;
 }
vchiq_dump_phys_mem()
VCHIQ_STATUS_T vchiq_dump_phys_mem (VCHIQ_SERVICE_HANDLE_T handle, void * ptr, size_t num_bytes)
Definition at line 1395 of file vchiq_lib.c.
References vchiq_service_struct::fd, VCHIQ_DUMP_MEM_T::num_bytes, RETRY, VCHIQ_ERROR, VCHIQ_IOC_DUMP_PHYS_MEM, VCHIQ_SUCCESS, and VCHIQ_DUMP_MEM_T::virt_addr.
 {
    VCHIQ_SERVICE_T *service = (VCHIQ_SERVICE_T *)handle;
    VCHIQ_DUMP_MEM_T  dump_mem;
    int ret;
    if (!service)
       return VCHIQ_ERROR;
    dump_mem.virt_addr = ptr;
    dump_mem.num_bytes = num_bytes;
    RETRY(ret,ioctl(service->fd, VCHIQ_IOC_DUMP_PHYS_MEM, &dump_mem));
    return (ret >= 0) ? VCHIQ_SUCCESS : VCHIQ_ERROR;
 }
vchiq_get_client_id()
int vchiq_get_client_id (VCHIQ_SERVICE_HANDLE_T handle)
Definition at line 564 of file vchiq_lib.c.
Referenced by khan_callback(), and rpc_get_client_id().
 {
    VCHIQ_SERVICE_T *service = find_service_by_handle(handle);
    if (!service)
       return VCHIQ_ERROR;
    return ioctl(service->fd, VCHIQ_IOC_GET_CLIENT_ID, service->handle);
 }
vchiq_get_config()
VCHIQ_STATUS_T vchiq_get_config (VCHIQ_INSTANCE_T instance, int config_size, VCHIQ_CONFIG_T * pconfig)
Definition at line 591 of file vchiq_lib.c.
 {
    VCHIQ_GET_CONFIG_T args;
    int ret;
    if (!is_valid_instance(instance))
       return VCHIQ_ERROR;
    args.config_size = config_size;
    args.pconfig = pconfig;
    RETRY(ret, ioctl(instance->fd, VCHIQ_IOC_GET_CONFIG, &args));
    return (ret >= 0) ? VCHIQ_SUCCESS : VCHIQ_ERROR;
 }
vchiq_get_service_fourcc()
int vchiq_get_service_fourcc (VCHIQ_SERVICE_HANDLE_T handle)
Definition at line 583 of file vchiq_lib.c.
 {
    VCHIQ_SERVICE_T *service = find_service_by_handle(handle);
    return service ? service->base.fourcc : 0;
 }
vchiq_get_service_userdata()
void* vchiq_get_service_userdata (VCHIQ_SERVICE_HANDLE_T handle)
Definition at line 575 of file vchiq_lib.c.
 {
    VCHIQ_SERVICE_T *service = find_service_by_handle(handle);
    return service ? service->base.userdata : NULL;
 }
vchiq_initialise()
VCHIQ_STATUS_T vchiq_initialise (VCHIQ_INSTANCE_T * pinstance)
Definition at line 161 of file vchiq_lib.c.
References vchiq_initialise_fd().
Referenced by bcm_host_init(), and vc_vchi_khronos_init().
 {
    return vchiq_initialise_fd(pinstance, -1);
 }
vchiq_initialise_fd()
VCHIQ_STATUS_T vchiq_initialise_fd (VCHIQ_INSTANCE_T * pinstance, int dev_vchiq_fd)
Definition at line 147 of file vchiq_lib.c.
Referenced by vchiq_initialise().
 {
    VCHIQ_INSTANCE_T instance;
    instance = vchiq_lib_init(dev_vchiq_fd);
    vcos_log_trace( "%s: returning instance handle %p", __func__, instance );
    *pinstance = instance;
    return (instance != NULL) ? VCHIQ_SUCCESS : VCHIQ_ERROR;
 }
vchiq_open_service()
VCHIQ_STATUS_T vchiq_open_service (VCHIQ_INSTANCE_T instance, const VCHIQ_SERVICE_PARAMS_T * params, VCHIQ_SERVICE_HANDLE_T * phandle)
Definition at line 301 of file vchiq_lib.c.
References vchiq_service_params_struct::callback, vchiq_service_params_struct::fourcc, status, and VCHIQ_ERROR.
Referenced by vc_vchi_khronos_init().
 {
    VCHIQ_STATUS_T status;
    vcos_log_trace( "%s called fourcc = 0x%08x (%c%c%c%c)",
                    __func__,
                    params->fourcc,
                    (params->fourcc >> 24) & 0xff,
                    (params->fourcc >> 16) & 0xff,
                    (params->fourcc >>  8) & 0xff,
                    (params->fourcc      ) & 0xff );
    if (!params->callback)
       return VCHIQ_ERROR;
    if (!is_valid_instance(instance))
       return VCHIQ_ERROR;
    status = create_service(instance,
       params,
       NULL/*vchi_callback*/,
       1/*open*/,
       phandle);
    vcos_log_trace( "%s returning service handle = 0x%08x", __func__, (uint32_t)*phandle );
    return status;
 }
vchiq_queue_bulk_receive()
VCHIQ_STATUS_T vchiq_queue_bulk_receive (VCHIQ_SERVICE_HANDLE_T handle, void * data, int size, void * userdata)
Definition at line 432 of file vchiq_lib.c.
Referenced by ilcs_receive_buffer(), and vchiq_queue_bulk_receive_handle().
 {
    VCHIQ_SERVICE_T *service = find_service_by_handle(handle);
    VCHIQ_QUEUE_BULK_TRANSFER_T args;
    int ret;
    vcos_log_trace( "%s called service handle = 0x%08x", __func__, (uint32_t)handle );
    if (!service)
       return VCHIQ_ERROR;
    args.handle = service->handle;
    args.data = data;
    args.size = size;
    args.userdata = userdata;
    args.mode = VCHIQ_BULK_MODE_CALLBACK;
    RETRY(ret, ioctl(service->fd, VCHIQ_IOC_QUEUE_BULK_RECEIVE, &args));
    return (ret >= 0) ? VCHIQ_SUCCESS : VCHIQ_ERROR;
 }
vchiq_queue_bulk_receive_handle()
VCHIQ_STATUS_T vchiq_queue_bulk_receive_handle (VCHIQ_SERVICE_HANDLE_T handle, VCHI_MEM_HANDLE_T memhandle, void * offset, int size, void * userdata)
Definition at line 471 of file vchiq_lib.c.
References VCHI_MEM_HANDLE_INVALID, vchiq_queue_bulk_receive(), and vcos_assert.
Referenced by ilcs_receive_buffer().
 {
    vcos_assert(memhandle == VCHI_MEM_HANDLE_INVALID);
    vcos_log_trace( "%s called service handle = 0x%08x", __func__, (uint32_t)handle );
    return vchiq_queue_bulk_receive(handle, offset, size, userdata);
 }
vchiq_queue_bulk_transmit()
VCHIQ_STATUS_T vchiq_queue_bulk_transmit (VCHIQ_SERVICE_HANDLE_T handle, const void * data, int size, void * userdata)
Definition at line 407 of file vchiq_lib.c.
Referenced by mmal_vc_send_message(), and vchiq_queue_bulk_transmit_handle().
 {
    VCHIQ_SERVICE_T *service = find_service_by_handle(handle);
    VCHIQ_QUEUE_BULK_TRANSFER_T args;
    int ret;
    vcos_log_trace( "%s called service handle = 0x%08x", __func__, (uint32_t)handle );
    if (!service)
       return VCHIQ_ERROR;
    args.handle = service->handle;
    args.data = (void *)data;
    args.size = size;
    args.userdata = userdata;
    args.mode = VCHIQ_BULK_MODE_CALLBACK;
    RETRY(ret, ioctl(service->fd, VCHIQ_IOC_QUEUE_BULK_TRANSMIT, &args));
    return (ret >= 0) ? VCHIQ_SUCCESS : VCHIQ_ERROR;
 }
vchiq_queue_bulk_transmit_handle()
VCHIQ_STATUS_T vchiq_queue_bulk_transmit_handle (VCHIQ_SERVICE_HANDLE_T handle, VCHI_MEM_HANDLE_T memhandle, const void * offset, int size, void * userdata)
Definition at line 457 of file vchiq_lib.c.
References VCHI_MEM_HANDLE_INVALID, vchiq_queue_bulk_transmit(), and vcos_assert.
 {
    vcos_assert(memhandle == VCHI_MEM_HANDLE_INVALID);
    vcos_log_trace( "%s called service handle = 0x%08x", __func__, (uint32_t)handle );
    return vchiq_queue_bulk_transmit(handle, offset, size, userdata);
 }
vchiq_queue_message()
VCHIQ_STATUS_T vchiq_queue_message (VCHIQ_SERVICE_HANDLE_T handle, const VCHIQ_ELEMENT_T * elements, int count)
Definition at line 376 of file vchiq_lib.c.
Referenced by mmal_vc_send_message(), and vc_gpuserv_execute_code().
 {
    VCHIQ_SERVICE_T *service = find_service_by_handle(handle);
    VCHIQ_QUEUE_MESSAGE_T args;
    int ret;
    vcos_log_trace( "%s called service handle = 0x%08x", __func__, (uint32_t)handle );
    if (!service)
       return VCHIQ_ERROR;
    args.handle = service->handle;
    args.elements = elements;
    args.count = count;
    RETRY(ret, ioctl(service->fd, VCHIQ_IOC_QUEUE_MESSAGE, &args));
    return (ret >= 0) ? VCHIQ_SUCCESS : VCHIQ_ERROR;
 }
vchiq_release_message()
void vchiq_release_message (VCHIQ_SERVICE_HANDLE_T handle, VCHIQ_HEADER_T * header)
Definition at line 398 of file vchiq_lib.c.
 {
    vcos_log_trace( "%s handle=%08x, header=%x", __func__, (uint32_t)handle, (uint32_t)header );
    free_msgbuf(header);
 }
vchiq_release_service()
int32_t vchiq_release_service (const VCHIQ_SERVICE_HANDLE_T handle)
Definition at line 623 of file vchiq_lib.c.
 {
    VCHIQ_SERVICE_T *service = find_service_by_handle(handle);
    int ret;
    if (!service)
       return VCHIQ_ERROR;
    RETRY(ret,ioctl(service->fd, VCHIQ_IOC_RELEASE_SERVICE, service->handle));
    return ret;
 }
vchiq_remove_service()
VCHIQ_STATUS_T vchiq_remove_service (VCHIQ_SERVICE_HANDLE_T handle)
Definition at line 355 of file vchiq_lib.c.
 {
    VCHIQ_SERVICE_T *service = find_service_by_handle(handle);
    int ret;
    vcos_log_trace( "%s called service handle = 0x%08x", __func__, (uint32_t)handle );
    if (!service)
       return VCHIQ_ERROR;
    RETRY(ret,ioctl(service->fd, VCHIQ_IOC_REMOVE_SERVICE, service->handle));
    service->lib_handle = VCHIQ_SERVICE_HANDLE_INVALID;
    if (ret != 0)
       return VCHIQ_ERROR;
    return VCHIQ_SUCCESS;
 }
vchiq_set_service_option()
VCHIQ_STATUS_T vchiq_set_service_option (VCHIQ_SERVICE_HANDLE_T handle, VCHIQ_SERVICE_OPTION_T option, int value)
Definition at line 636 of file vchiq_lib.c.
 {
    VCHIQ_SET_SERVICE_OPTION_T args;
    VCHIQ_SERVICE_T *service = find_service_by_handle(handle);
    int ret;
    if (!service)
       return VCHIQ_ERROR;
    args.handle = service->handle;
    args.option = option;
    args.value  = value;
    RETRY(ret, ioctl(service->fd, VCHIQ_IOC_SET_SERVICE_OPTION, &args));
    return (ret >= 0) ? VCHIQ_SUCCESS : VCHIQ_ERROR;
 }
vchiq_shutdown()
VCHIQ_STATUS_T vchiq_shutdown (VCHIQ_INSTANCE_T instance)
Definition at line 167 of file vchiq_lib.c.
Referenced by vchi_disconnect().
 {
    vcos_log_trace( "%s called", __func__ );
    if (!is_valid_instance(instance))
       return VCHIQ_ERROR;
    vcos_mutex_lock(&instance->mutex);
    if (instance->initialised == 1)
    {
       int i;
       instance->initialised = -1; /* Enter limbo */
       /* Remove all services */
       for (i = 0; i < instance->used_services; i++)
       {
          if (instance->services[i].lib_handle != VCHIQ_SERVICE_HANDLE_INVALID)
          {
             vchiq_remove_service(instance->services[i].lib_handle);
             instance->services[i].lib_handle = VCHIQ_SERVICE_HANDLE_INVALID;
          }
       }
       if (instance->connected)
       {
          int ret;
          RETRY(ret, ioctl(instance->fd, VCHIQ_IOC_SHUTDOWN, 0));
          vcos_assert(ret == 0);
          vcos_thread_join(&instance->completion_thread, NULL);
          instance->connected = 0;
       }
       close(instance->fd);
       instance->fd = -1;
    }
    else if (instance->initialised > 1)
    {
       instance->initialised--;
    }
    vcos_mutex_unlock(&instance->mutex);
    vcos_global_lock();
    if (instance->initialised == -1)
    {
       vcos_mutex_delete(&instance->mutex);
       instance->initialised = 0;
    }
    vcos_global_unlock();
    vcos_log_trace( "%s returning", __func__ );
    vcos_log_unregister(&vchiq_lib_log_category);
    return VCHIQ_SUCCESS;
 }
vchiq_use_service()
int32_t vchiq_use_service (const VCHIQ_SERVICE_HANDLE_T handle)
Definition at line 610 of file vchiq_lib.c.
 {
    VCHIQ_SERVICE_T *service = find_service_by_handle(handle);
    int ret;
    if (!service)
       return VCHIQ_ERROR;
    RETRY(ret,ioctl(service->fd, VCHIQ_IOC_USE_SERVICE, service->handle));
    return ret;
 }
vcos_static_assert() [1/4]
vcos_static_assert (IS_POWER_2(VCHIQ_MAX_INSTANCE_SERVICES))
vcos_static_assert() [2/4]
vcos_static_assert (sizeof(VCHI_MSG_VECTOR_T) = =sizeof(VCHIQ_ELEMENT_T))
vcos_static_assert() [3/4]
vcos_static_assert (offsetof(VCHI_MSG_VECTOR_T, vec_base) = =offsetof(VCHIQ_ELEMENT_T, data))
vcos_static_assert() [4/4]
vcos_static_assert (offsetof(VCHI_MSG_VECTOR_T, vec_len) = =offsetof(VCHIQ_ELEMENT_T, size))
Variable Documentation
vchiq_instance
struct vchiq_instance_struct vchiq_instance
Referenced by bcm_host_init().