VideoCore Library: interface/vcos/pthreads/vcos_dlfcn.c File Reference
vcos_dlfcn.c File Reference
#include "interface/vcos/vcos.h"
#include "interface/vcos/vcos_dlfcn.h"
#include <dlfcn.h>
Functions
void * vcos_dlopen (const char *name, int mode)
int vcos_dlclose (void *handle)
int vcos_dlerror (int *err, char *buf, size_t buflen)
Variables
void(*)(void) vcos_dlsym (void *handle, const char *name)
Function Documentation
vcos_dlclose()
int vcos_dlclose (void * handle)
Close a library
Parameters
handle Handle to close
Definition at line 43 of file vcos_dlfcn.c.
References dlclose().
 {
    return dlclose(handle);
 }
vcos_dlerror()
int vcos_dlerror (int * err, char * buf, size_t buflen)
Return error message from library.
Parameters
err On return, set to non-zero if an error has occurred
buf Buffer to write error to
len Size of buffer (including terminating NUL).
Definition at line 48 of file vcos_dlfcn.c.
References dlerror(), and vcos_assert.
 {
    /* not really threadsafe! */
    const char *errmsg = dlerror();
    vcos_assert(buflen > 0);
    if (errmsg)
    {
       *err = -1;
       strncpy(buf, errmsg, buflen);
       buf[buflen-1] = '\0';
    }
    else
    {
       *err = 0;
       buf[0] = '\0';
    }
    return 0;
 }
vcos_dlopen()
void* vcos_dlopen (const char * name, int mode)
Open a dynamic library.
Parameters
name name of the library
mode Load lazily or immediately (VCOS_DL_LAZY, VCOS_DL_NOW, VCOS_DL_LOCAL, VCOS_DL_GLOBAL).
Returns
A handle for use in subsequent calls.
Definition at line 33 of file vcos_dlfcn.c.
References dlopen().
 {
    return dlopen(name, mode);
 }
Variable Documentation
vcos_dlsym
void(*)(void) vcos_dlsym(void *handle, const char *name)
Definition at line 38 of file vcos_dlfcn.c.
 {
    return dlsym(handle, name);
 }