VideoCore Library: containers/core/containers_logging.c File Reference
containers_logging.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include "containers/containers.h"
#include "containers/core/containers_private.h"
#include "containers/core/containers_logging.h"
#include "vcos.h"
Functions
void vc_container_log_set_default_verbosity (uint32_t mask)
uint32_t vc_container_log_get_default_verbosity (void)
void vc_container_log_set_verbosity (VC_CONTAINER_T *ctx, uint32_t mask)
void vc_container_log (VC_CONTAINER_T *ctx, VC_CONTAINER_LOG_TYPE_T type, const char *format,...)
void vc_container_log_vargs (VC_CONTAINER_T *ctx, VC_CONTAINER_LOG_TYPE_T type, const char *format, va_list args)
Function Documentation
vc_container_log()
void vc_container_log (VC_CONTAINER_T * ctx, VC_CONTAINER_LOG_TYPE_T type, const char * format, ...)
Definition at line 66 of file containers_logging.c.
Referenced by vc_container_bits_read_s32_exp_golomb(), and vc_container_helper_format_debug().
 {
    uint32_t verbosity = ctx ? ctx->priv->verbosity : verbosity_mask;
    va_list args;
    // Optimise out the call to vc_container_log_vargs etc. when it won't do anything.
    if(!(type & verbosity)) return;
    va_start( args, format );
    vc_container_log_vargs(ctx, type, format, args);
    va_end( args );
 }
vc_container_log_get_default_verbosity()
uint32_t vc_container_log_get_default_verbosity (void)
Definition at line 55 of file containers_logging.c.
Referenced by vc_container_open_reader_with_io(), and vc_container_open_writer().
 {
    return default_verbosity_mask;
 }
vc_container_log_set_default_verbosity()
void vc_container_log_set_default_verbosity (uint32_t mask)
Definition at line 50 of file containers_logging.c.
 {
    default_verbosity_mask = mask;
 }
vc_container_log_set_verbosity()
void vc_container_log_set_verbosity (VC_CONTAINER_T * ctx, uint32_t mask)
Definition at line 60 of file containers_logging.c.
Referenced by TESTER_T::run().
 {
    if(!ctx) verbosity_mask = mask;
    else ctx->priv->verbosity = mask;
 }
vc_container_log_vargs()
void vc_container_log_vargs (VC_CONTAINER_T * ctx, VC_CONTAINER_LOG_TYPE_T type, const char * format, va_list args)
Definition at line 79 of file containers_logging.c.
 {
    uint32_t verbosity = ctx ? ctx->priv->verbosity : verbosity_mask;
    // If the verbosity is such that the type doesn't need logging quit now.
    if(!(type & verbosity)) return;
 #ifdef __ANDROID__
    {
       // Default to Android's "verbose" level (doesn't usually come out)
       android_LogPriority logLevel = ANDROID_LOG_VERBOSE;
       // Where type suggest a higher level is required update logLevel.
       // (Usually type contains only 1 bit as set by the LOG_DEBUG, LOG_ERROR or LOG_INFO macros)
       if (type & VC_CONTAINER_LOG_ERROR)
          logLevel = ANDROID_LOG_ERROR;
       else if (type & VC_CONTAINER_LOG_INFO)
          logLevel = ANDROID_LOG_INFO;
       else if (type & VC_CONTAINER_LOG_DEBUG)
          logLevel = ANDROID_LOG_DEBUG;
       // Actually put the message out.
       LOG_PRI_VA(logLevel, LOG_TAG, format, args);
    }
 #else
 #ifndef ENABLE_CONTAINERS_STANDALONE
    vcos_vlog(format, args);
 #else
    vprintf(format, args); printf("\n");
    fflush(0);
 #endif
 #endif
 }