VideoCore Library: host_applications/vmcs/test_apps/mmalplay/mmalplay.c File Reference
mmalplay.c File Reference
#include <stdlib.h>
#include <limits.h>
#include <stdio.h>
#include <string.h>
#include <signal.h>
#include "mmalplay.h"
#include "interface/mmal/mmal_logging.h"
#include "interface/mmal/mmal_encodings.h"
#include "interface/mmal/util/mmal_util.h"
Classes
struct FILE_PLAY_INFO_T
Macros
#define URI_FOR_THREAD_NAME_MAX 16
#define THREAD_PREFIX "mmal:"
#define VERSION "0.9"
#define FILE_PLAY_MAX 16
Functions
void test_signal_handler (int signum)
int main (int argc, const char **argv)
Macro Definition Documentation
FILE_PLAY_MAX
#define FILE_PLAY_MAX 16
Definition at line 56 of file mmalplay.c.
THREAD_PREFIX
#define THREAD_PREFIX "mmal:"
Definition at line 39 of file mmalplay.c.
URI_FOR_THREAD_NAME_MAX
#define URI_FOR_THREAD_NAME_MAX 16
Definition at line 38 of file mmalplay.c.
VERSION
#define VERSION "0.9"
Definition at line 40 of file mmalplay.c.
Function Documentation
main()
int main (int argc, const char ** argv)
Definition at line 68 of file mmalplay.c.
References test_signal_handler(), and vcos_init().
 {
    VCOS_THREAD_ATTR_T attrs;
    int i;
    vcos_init();
    signal(SIGINT, test_signal_handler);
    /* coverity[tainted_data] Ignore unnecessary warning about an attacker
     * being able to pass an arbitrarily long "-vvvvv..." argument */
    if (test_parse_cmdline(argc, argv))
       return -1;
    if (verbosity--)
    {
       static char value[512];
       const char *levels[] = {"warn", "info", "trace"};
       char *env = getenv("VC_LOGLEVEL");
       if (verbosity >= MMAL_COUNTOF(levels)) verbosity = MMAL_COUNTOF(levels) - 1;
       snprintf(value, sizeof(value)-1, "mmalplay:%s,mmal:%s,%s",
                levels[verbosity], levels[verbosity], env ? env : "");
       setenv("VC_LOGLEVEL", value, 1);
    }
    vcos_log_register("mmalplay", VCOS_LOG_CATEGORY);
    LOG_INFO("MMAL Video Playback Test App");
    vcos_thread_attr_init(&attrs);
    for (i = 0; i < play_info_count; i++)
    {
       const char *uri = play_info[i].uri;
       memcpy(play_info[i].name, THREAD_PREFIX, sizeof(THREAD_PREFIX));
       if (strlen(uri) >= URI_FOR_THREAD_NAME_MAX)
          uri += strlen(uri) - URI_FOR_THREAD_NAME_MAX;
       strncat(play_info[i].name, uri, URI_FOR_THREAD_NAME_MAX);
       vcos_mutex_create(&play_info[i].lock, "mmalplay");
       play_info[i].options.render_layer = i;
       if (vcos_thread_create(&play_info[i].thread, play_info[i].name, &attrs, mmal_playback, &play_info[i]) != VCOS_SUCCESS)
       {
          LOG_ERROR("Thread creation failure for URI %s", play_info[i].uri);
          return -2;
       }
    }
    if (sleepy_time != 0)
    {
       sleep(sleepy_time);
       for (i = 0; i < play_info_count; i++)
       {
          vcos_mutex_lock(&play_info[i].lock);
          if (play_info[i].ctx)
             mmalplay_stop(play_info[i].ctx);
          vcos_mutex_unlock(&play_info[i].lock);
       }
    }
    LOG_TRACE("Waiting for threads to terminate");
    for (i = 0; i < play_info_count; i++)
    {
       vcos_thread_join(&play_info[i].thread, NULL);
       LOG_TRACE("Joined thread %d (%i)", i, play_info[i].status);
    }
    LOG_TRACE("Completed");
    /* Check for errors */
    for (i = 0; i < play_info_count; i++)
    {
       if (!play_info[i].status)
          continue;
       LOG_ERROR("Playback of %s failed (%i, %s)", play_info[i].uri,
                 play_info[i].status,
                 mmal_status_to_string(play_info[i].status));
       fprintf(stderr, "playback of %s failed (%i, %s)\n", play_info[i].uri,
               play_info[i].status,
               mmal_status_to_string(play_info[i].status));
       return play_info[i].status;
    }
    return 0;
 }
test_signal_handler()
void test_signal_handler (int signum)
Definition at line 197 of file mmalplay.c.
Referenced by main().
 {
    static MMAL_BOOL_T stopped_already = 0;
    int i;
    MMAL_PARAM_UNUSED(signum);
    if (stopped_already)
    {
       LOG_ERROR("Killing program");
       exit(255);
    }
    stopped_already = 1;
    LOG_ERROR("BYE");
    for (i = 0; i < play_info_count; i++)
    {
       vcos_mutex_lock(&play_info[i].lock);
       if (play_info[i].ctx)
          mmalplay_stop(play_info[i].ctx);
       vcos_mutex_unlock(&play_info[i].lock);
    }
 }