VideoCore Library: interface/khronos/common/khrn_client_platform.h File Reference
khrn_client_platform.h File Reference
#include "interface/khronos/include/EGL/egl.h"
#include "interface/khronos/include/EGL/eglext.h"
#include "interface/khronos/common/khrn_int_common.h"
#include "interface/khronos/common/khrn_int_image.h"
#include "interface/khronos/egl/egl_int.h"
#include <stdlib.h>
#include "interface/khronos/common/vcos/khrn_client_platform_filler_vcos.h"
#include "interface/khronos/include/WF/wfc.h"
Classes
struct WFC_BOUNCE_DATA_T
Macros
#define PLATFORM_WIN_NONE ((uint32_t)0xffffffff)
Functions
void platform_hint_thread_finished (void)
void * khrn_platform_malloc (size_t size, const char *desc)
void khrn_platform_free (void *v)
void khrn_platform_maybe_free_process (void)
uint64_t khronos_platform_get_process_id (void)
uint32_t platform_get_handle (EGLDisplay dpy, EGLNativeWindowType win)
void platform_get_dimensions (EGLDisplay dpy, EGLNativeWindowType win, uint32_t *width, uint32_t *height, uint32_t *swapchain_count)
void platform_surface_update (uint32_t handle)
bool platform_get_pixmap_info (EGLNativePixmapType pixmap, KHRN_IMAGE_WRAP_T *image)
void platform_get_pixmap_server_handle (EGLNativePixmapType pixmap, uint32_t *handle)
void platform_wait_EGL (uint32_t handle)
void platform_retrieve_pixmap_completed (EGLNativePixmapType pixmap)
void platform_send_pixmap_completed (EGLNativePixmapType pixmap)
bool platform_match_pixmap_api_support (EGLNativePixmapType pixmap, uint32_t api_support)
uint32_t platform_memcmp (const void *aLeft, const void *aRight, size_t aLen)
void platform_memcpy (void *aTrg, const void *aSrc, size_t aLength)
void platform_client_lock (void)
void platform_client_release (void)
void platform_init_rpc (struct CLIENT_THREAD_STATE *state)
void platform_term_rpc (struct CLIENT_THREAD_STATE *state)
void platform_maybe_free_process (void)
void platform_destroy_winhandle (void *a, uint32_t b)
uint32_t platform_get_color_format (uint32_t format)
void egl_gce_win_change_image (void)
EGLDisplay khrn_platform_set_display_id (EGLNativeDisplayType display_id)
uint32_t khrn_platform_get_window_position (EGLNativeWindowType win)
void khrn_platform_release_pixmap_info (EGLNativePixmapType pixmap, KHRN_IMAGE_WRAP_T *image)
void khrn_platform_bind_pixmap_to_egl_image (EGLNativePixmapType pixmap, EGLImageKHR egl_image, bool send)
void khrn_platform_unbind_pixmap_from_egl_image (EGLImageKHR egl_image)
void platform_dequeue (EGLDisplay dpy, EGLNativeWindowType window)
void * platform_wfc_bounce_thread (void *param)
Macro Definition Documentation
PLATFORM_WIN_NONE
#define PLATFORM_WIN_NONE ((uint32_t)0xffffffff)
Definition at line 134 of file khrn_client_platform.h.
Function Documentation
egl_gce_win_change_image()
void egl_gce_win_change_image (void)
Definition at line 390 of file khrn_client_platform_linux.c.
References assert().
 {
    assert(0);
 }
khrn_platform_bind_pixmap_to_egl_image()
void khrn_platform_bind_pixmap_to_egl_image (EGLNativePixmapType pixmap, EGLImageKHR egl_image, bool send)
Definition at line 688 of file khrn_client_platform_linux.c.
References NUM_PIXMAP_BINDINGS.
 {
    int i;
    for (i = 0; i < NUM_PIXMAP_BINDINGS; i++)
    {
       if (!pixmap_binding[i].used)
       {
          vcos_log_trace("khrn_platform_bind_pixmap_to_egl_image %d", i);
          pixmap_binding[i].used = true;
          pixmap_binding[i].pixmap = pixmap;
          pixmap_binding[i].egl_image = egl_image;
          pixmap_binding[i].send = send;
          if(send)
             send_bound_pixmap(i);
          return;
       }
    }
    vcos_assert(0);  /* Not enough NUM_PIXMAP_BINDINGS? */
 }
khrn_platform_free()
void khrn_platform_free (void * v)
Free memory
Parameters
v Pointer to memory area to free
Definition at line 156 of file khrn_client_platform_linux.c.
References ABGR_8888_RSO, ARGB_8888_RSO, KHRN_IMAGE_WRAP_T::aux, BGR_888_RSO, KHRN_IMAGE_WRAP_T::format, KHRN_IMAGE_WRAP_T::height, IMAGE_FORMAT_INVALID, NULL, pixmap, platform_get_pixmap_info(), RGB_565_RSO, KHRN_IMAGE_WRAP_T::storage, KHRN_IMAGE_WRAP_T::stride, vcos_free(), and KHRN_IMAGE_WRAP_T::width.
Referenced by egl_context_maybe_free(), khrn_cache_term(), khrn_vector_clear(), khrn_vector_extend(), khrn_vector_term(), and vg_client_shared_state_alloc().
 {
    if (v)
    {
       vcos_free(v);
    }
 }
khrn_platform_get_window_position()
uint32_t khrn_platform_get_window_position (EGLNativeWindowType win)
Definition at line 610 of file khrn_client_platform_linux.c.
Referenced by khrn_platform_set_display_id().
 {
    return xxx_position;
 }
khrn_platform_malloc()
void* khrn_platform_malloc (size_t size, const char * name)
Allocate memory
Parameters
size Size in bytes of memory block to allocate
Returns
pointer to memory block
Definition at line 146 of file khrn_client_platform_linux.c.
References vcos_malloc().
Referenced by khrn_vector_extend(), khrn_vector_init(), and vg_client_shared_state_alloc().
 {
    return vcos_malloc(size, name);
 }
khrn_platform_maybe_free_process()
void khrn_platform_maybe_free_process (void)
khrn_platform_release_pixmap_info()
void khrn_platform_release_pixmap_info (EGLNativePixmapType pixmap, KHRN_IMAGE_WRAP_T * image)
Definition at line 295 of file khrn_client_platform_linux.c.
Referenced by egl_config_check_attribs(), and egl_config_filter().
 {
    /* Nothing to do */
 }
khrn_platform_set_display_id()
EGLDisplay khrn_platform_set_display_id (EGLNativeDisplayType display_id)
Definition at line 467 of file khrn_client_platform_linux.c.
References EGL_DEFAULT_DISPLAY, EGL_NO_DISPLAY, and khrn_platform_get_window_position().
Referenced by platform_memcpy().
 {
    if (display_id == EGL_DEFAULT_DISPLAY)
       return (EGLDisplay)1;
    else
       return EGL_NO_DISPLAY;
 }
khrn_platform_unbind_pixmap_from_egl_image()
void khrn_platform_unbind_pixmap_from_egl_image (EGLImageKHR egl_image)
Definition at line 710 of file khrn_client_platform_linux.c.
References NUM_PIXMAP_BINDINGS.
 {
    int i;
    for (i = 0; i < NUM_PIXMAP_BINDINGS; i++)
    {
       if (pixmap_binding[i].used && pixmap_binding[i].egl_image == egl_image)
       {
          pixmap_binding[i].used = false;
       }
    }
 }
khronos_platform_get_process_id()
uint64_t khronos_platform_get_process_id (void)
Definition at line 78 of file khrn_client_platform_linux.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    return rpc_get_client_id(thread);
 }
platform_client_lock()
void platform_client_lock (void)
Definition at line 351 of file khrn_client_platform_linux.c.
References client_mutex, and platform_mutex_acquire().
 {
    platform_mutex_acquire(&client_mutex);
 }
platform_client_release()
void platform_client_release (void)
Definition at line 356 of file khrn_client_platform_linux.c.
References client_mutex, and platform_mutex_release().
 {
    platform_mutex_release(&client_mutex);
 }
platform_dequeue()
void platform_dequeue (EGLDisplay dpy, EGLNativeWindowType window)
Definition at line 829 of file khrn_client_platform_linux.c.
 {}
platform_destroy_winhandle()
void platform_destroy_winhandle (void * a, uint32_t b)
Definition at line 376 of file khrn_client_platform_linux.c.
References assert().
 {
    assert(1);
 }
platform_get_color_format()
uint32_t platform_get_color_format (uint32_t format)
Definition at line 828 of file khrn_client_platform_linux.c.
 { return format; }
platform_get_dimensions()
void platform_get_dimensions (EGLDisplay dpy, EGLNativeWindowType win, uint32_t * width, uint32_t * height, uint32_t * swapchain_count)
Definition at line 67 of file khrn_client_platform_openwfc.c.
Referenced by platform_memcpy().
 {
    EGL_DISPMANX_WINDOW_T *dwin = check_default(win);
    *width =  dwin->width;
    *height = dwin->height;
    *swapchain_count = 0;
 }
platform_get_handle()
uint32_t platform_get_handle (EGLDisplay dpy, EGLNativeWindowType win)
Definition at line 59 of file khrn_client_platform_openwfc.c.
Referenced by platform_memcpy().
 {
    EGL_DISPMANX_WINDOW_T *dwin = check_default(win);
    return dwin->element;  /* same handles used on host and videocore sides */
 }
platform_get_pixmap_info()
bool platform_get_pixmap_info (EGLNativePixmapType pixmap, KHRN_IMAGE_WRAP_T * image)
Definition at line 282 of file khrn_client_platform_linux.c.
References KHRN_IMAGE_WRAP_T::format.
Referenced by egl_config_check_attribs(), egl_config_filter(), and khrn_platform_free().
 {
    image->format = convert_format(((uint32_t *)pixmap)[4]);
    image->width = ((uint32_t *)pixmap)[2];
    image->height = ((uint32_t *)pixmap)[3];
    /* can't actually access data */
    image->stride = 0;
    image->aux = 0;
    image->storage = 0;
    return image->format != 0;
 }
platform_get_pixmap_server_handle()
void platform_get_pixmap_server_handle (EGLNativePixmapType pixmap, uint32_t * handle)
Definition at line 301 of file khrn_client_platform_linux.c.
 {
    handle[0] = ((uint32_t *)pixmap)[0];
    handle[1] = ((uint32_t *)pixmap)[1];
 }
platform_hint_thread_finished()
void platform_hint_thread_finished (void)
Definition at line 126 of file khrn_client_platform_linux.c.
 {
    /*
       todo: should we do this:
       vcos_thread_deregister_at_exit(client_thread_detach);
       client_thread_detach();
       here?
    */
 }
platform_init_rpc()
void platform_init_rpc (struct CLIENT_THREAD_STATE * state)
Definition at line 361 of file khrn_client_platform_linux.c.
 {
    assert(1);
 }
platform_match_pixmap_api_support()
bool platform_match_pixmap_api_support (EGLNativePixmapType pixmap, uint32_t api_support)
Definition at line 307 of file khrn_client_platform_linux.c.
References EGL_OPENGL_BIT, EGL_OPENGL_ES2_BIT, EGL_OPENGL_ES_BIT, EGL_OPENVG_BIT, EGL_PIXEL_FORMAT_GLES2_TEXTURE_BRCM, EGL_PIXEL_FORMAT_GLES_TEXTURE_BRCM, EGL_PIXEL_FORMAT_RENDER_GL_BRCM, EGL_PIXEL_FORMAT_RENDER_GLES2_BRCM, EGL_PIXEL_FORMAT_RENDER_GLES_BRCM, EGL_PIXEL_FORMAT_RENDER_VG_BRCM, EGL_PIXEL_FORMAT_VG_IMAGE_BRCM, error(), pixmap, and verify.
Referenced by egl_config_filter().
 {
    return
       (!(api_support & EGL_OPENGL_BIT) || (((uint32_t *)pixmap)[4] & EGL_PIXEL_FORMAT_RENDER_GL_BRCM)) &&
       (!(api_support & EGL_OPENGL_ES_BIT) || (((uint32_t *)pixmap)[4] & EGL_PIXEL_FORMAT_RENDER_GLES_BRCM)) &&
       (!(api_support & EGL_OPENGL_ES2_BIT) || (((uint32_t *)pixmap)[4] & EGL_PIXEL_FORMAT_RENDER_GLES2_BRCM)) &&
       (!(api_support & EGL_OPENVG_BIT) || (((uint32_t *)pixmap)[4] & EGL_PIXEL_FORMAT_RENDER_VG_BRCM));
 }
platform_maybe_free_process()
void platform_maybe_free_process (void)
Definition at line 371 of file khrn_client_platform_linux.c.
References assert().
 {
    assert(1);
 }
platform_memcmp()
uint32_t platform_memcmp (const void * aLeft, const void * aRight, size_t aLen)
Definition at line 405 of file khrn_client_platform_linux.c.
 {
    return memcmp(aLeft, aRight, aLen);
 }
platform_memcpy()
void platform_memcpy (void * aTrg, const void * aSrc, size_t aLength)
Definition at line 410 of file khrn_client_platform_linux.c.
References CHROMA_KEY_565, EGL_NO_DISPLAY, khrn_platform_set_display_id(), NULL, platform_get_dimensions(), and platform_get_handle().
 {
    memcpy(aTrg, aSrc, aLength);
 }
platform_retrieve_pixmap_completed()
void platform_retrieve_pixmap_completed (EGLNativePixmapType pixmap)
Definition at line 395 of file khrn_client_platform_linux.c.
References assert().
 {
    assert(0);
 }
platform_send_pixmap_completed()
void platform_send_pixmap_completed (EGLNativePixmapType pixmap)
Definition at line 400 of file khrn_client_platform_linux.c.
References assert().
 {
    assert(0);
 }
platform_surface_update()
void platform_surface_update (uint32_t handle)
Definition at line 381 of file khrn_client_platform_linux.c.
 {
    /*
    XXX This seems as good a place as any to do the client side pixmap hack.
    (called from eglSwapBuffers)
    */
    send_bound_pixmaps();
 }
platform_term_rpc()
void platform_term_rpc (struct CLIENT_THREAD_STATE * state)
Definition at line 366 of file khrn_client_platform_linux.c.
 {
    assert(1);
 }
platform_wait_EGL()
void platform_wait_EGL (uint32_t handle)
platform_wfc_bounce_thread()
void* platform_wfc_bounce_thread (void * param)
Definition at line 81 of file khrn_client_platform_openwfc.c.
References WFC_BOUNCE_DATA_T::context, WFC_BOUNCE_DATA_T::dest_height, WFC_BOUNCE_DATA_T::dest_width, WFC_BOUNCE_DATA_T::device, WFC_BOUNCE_DATA_T::element, NO_ATTRIBUTES, NULL, NUM_OF_ELEMENTS, WFC_BOUNCE_DATA_T::num_of_elements, WFC_BOUNCE_DATA_T::source, WFC_BOUNCE_DATA_T::src_height, WFC_BOUNCE_DATA_T::src_width, WFC_BOUNCE_DATA_T::src_x, WFC_BOUNCE_DATA_T::src_y, WFC_BOUNCE_DATA_T::stop_bouncing, vcos_assert, vcos_sleep(), vcos_verify, WFC_CONTEXT_BG_COLOR, WFC_CONTEXT_TARGET_HEIGHT, WFC_CONTEXT_TARGET_WIDTH, WFC_ELEMENT_DESTINATION_RECTANGLE, WFC_ELEMENT_GLOBAL_ALPHA, WFC_ELEMENT_SOURCE, WFC_ELEMENT_SOURCE_RECTANGLE, WFC_ELEMENT_TRANSPARENCY_TYPES, WFC_ERROR_NONE, WFC_INVALID_HANDLE, WFC_RECT_HEIGHT, WFC_RECT_SIZE, WFC_RECT_WIDTH, WFC_RECT_X, WFC_RECT_Y, WFC_TRANSPARENCY_ELEMENT_GLOBAL_ALPHA, WFC_TRUE, wfcCommit(), wfcCreateElement(), wfcDestroyElement(), wfcGetContextAttribi(), wfcGetError(), wfcInsertElement(), wfcSetContextAttribi(), wfcSetElementAttribf(), wfcSetElementAttribi(), and wfcSetElementAttribiv().
 {
    WFC_BOUNCE_DATA_T *bounce_data = (WFC_BOUNCE_DATA_T *) param;
    uint32_t i;
    int32_t xstep[NUM_OF_ELEMENTS], ystep[NUM_OF_ELEMENTS];
    WFCint dest_rect[NUM_OF_ELEMENTS][WFC_RECT_SIZE];
    WFCint src_rect[WFC_RECT_SIZE];
    WFCElement element_local[NUM_OF_ELEMENTS];
    uint32_t num_of_elements = NUM_OF_ELEMENTS;
    WFCElement *element = element_local;
    // Get context (i.e. screen) dimensions.
    int32_t ctx_width;
    int32_t ctx_height;
    int32_t dest_width, dest_height;
    int32_t x, y;
    bool use_local_elements = (bounce_data->num_of_elements == 0);
    if(!use_local_elements)
    {
       vcos_assert(bounce_data->num_of_elements <= NUM_OF_ELEMENTS);
       vcos_assert(bounce_data->element != NULL);
       num_of_elements = bounce_data->num_of_elements;
       element = bounce_data->element;
    } // if
    // Initialise values
    ctx_width = wfcGetContextAttribi(bounce_data->device,
       bounce_data->context, WFC_CONTEXT_TARGET_WIDTH);
    ctx_height = wfcGetContextAttribi(bounce_data->device,
       bounce_data->context, WFC_CONTEXT_TARGET_HEIGHT);
    // Change background colour
    wfcSetContextAttribi(bounce_data->device,
       bounce_data->context, WFC_CONTEXT_BG_COLOR, 0x0000FFFF);
    float scale = 0.4;
    if(num_of_elements == 1)
       {scale = 0.75;}
    dest_width = bounce_data->dest_width * scale;
    dest_height = bounce_data->dest_height * scale;
    // Define source rectangle
    src_rect[WFC_RECT_X] = bounce_data->src_x;
    src_rect[WFC_RECT_Y] = bounce_data->src_y;
    src_rect[WFC_RECT_WIDTH] = bounce_data->src_width;
    src_rect[WFC_RECT_HEIGHT] = bounce_data->src_height;
    for(i = 0; i < num_of_elements; i++)
    {
       if(use_local_elements)
       {
          // Create and set up element
          element[i] = wfcCreateElement(bounce_data->device,
             bounce_data->context, NO_ATTRIBUTES);
          vcos_assert(element[i] != WFC_INVALID_HANDLE);
          wfcInsertElement(bounce_data->device, element[i], WFC_INVALID_HANDLE);
          if(vcos_verify(wfcGetError(bounce_data->device) == WFC_ERROR_NONE)) {};
       } // if
       else
       {
          // Element created in calling app, so use that
          element[i] = bounce_data->element[i];
       } // else
       wfcSetElementAttribiv(bounce_data->device, element[i],
          WFC_ELEMENT_SOURCE_RECTANGLE, WFC_RECT_SIZE, src_rect);
       // Attach existing source
       wfcSetElementAttribi(bounce_data->device, element[i],
          WFC_ELEMENT_SOURCE, bounce_data->source);
       if(num_of_elements > 1)
       {
          wfcSetElementAttribi(bounce_data->device, element[i],
             WFC_ELEMENT_TRANSPARENCY_TYPES, WFC_TRANSPARENCY_ELEMENT_GLOBAL_ALPHA);
          wfcSetElementAttribf(bounce_data->device, element[i],
             WFC_ELEMENT_GLOBAL_ALPHA, 0.75);
       } // if
       // Define initial destination rectangle
       dest_rect[i][WFC_RECT_X] = i * 100;
       dest_rect[i][WFC_RECT_Y] = i * 10;
       dest_rect[i][WFC_RECT_WIDTH] = dest_width;
       dest_rect[i][WFC_RECT_HEIGHT] = dest_height;
       wfcSetElementAttribiv(bounce_data->device, element[i],
          WFC_ELEMENT_DESTINATION_RECTANGLE, WFC_RECT_SIZE, dest_rect[i]);
       xstep[i] = (i + 1) * 2;
       ystep[i] = (i + 1) * 2;
    } // for
    while(!bounce_data->stop_bouncing)
    {
       for(i = 0; i < num_of_elements; i++)
       {
          // Compute new x and y values.
          x = dest_rect[i][WFC_RECT_X];
          y = dest_rect[i][WFC_RECT_Y];
          x += xstep[i];
          if(x + dest_width >= ctx_width)
             {x = ctx_width - dest_width - 1; xstep[i] *= -1;}
          else if(x < 0)
             {x = 0; xstep[i] *= -1;}
          y += ystep[i];
          if(y + dest_height >= ctx_height)
             {y = ctx_height - dest_height - 1; ystep[i] *= -1;}
          else if(y < 0)
             {y = 0; ystep[i] *= -1;}
          dest_rect[i][WFC_RECT_X] = x;
          dest_rect[i][WFC_RECT_Y] = y;
          // Set updated destination rectangle
          wfcSetElementAttribiv(bounce_data->device, element[i],
             WFC_ELEMENT_DESTINATION_RECTANGLE, WFC_RECT_SIZE, dest_rect[i]);
       } // for
       wfcCommit(bounce_data->device, bounce_data->context, WFC_TRUE);
       vcos_sleep(30);
    } // while
    // Remove elements
    if(use_local_elements)
    {
       for(i = 0; i < num_of_elements; i++)
       {
          wfcDestroyElement(bounce_data->device, element[i]);
       } // for
    } // if
    // Change background colour
    wfcSetContextAttribi(bounce_data->device,
       bounce_data->context, WFC_CONTEXT_BG_COLOR, 0xFF0000FF);
    wfcCommit(bounce_data->device, bounce_data->context, WFC_TRUE);
    return NULL;
 } // platform_bounce_thread