VideoCore Library: host_applications/linux/apps/hello_pi/hello_jpeg/jpeg.h File Reference
jpeg.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include "bcm_host.h"
#include "ilclient.h"
Macros
#define OMXJPEG_OK 0
#define OMXJPEG_ERROR_ILCLIENT_INIT -1024
#define OMXJPEG_ERROR_OMX_INIT -1025
#define OMXJPEG_ERROR_MEMORY -1026
#define OMXJPEG_ERROR_CREATING_COMP -1027
#define OMXJPEG_ERROR_WRONG_NO_PORTS -1028
#define OMXJPEG_ERROR_EXECUTING -1029
#define OMXJPEG_ERROR_NOSETTINGS -1030
Typedefs
typedef struct _OPENMAX_JPEG_DECODER OPENMAX_JPEG_DECODER
Functions
int setupOpenMaxJpegDecoder (OPENMAX_JPEG_DECODER **decoder)
int decodeImage (OPENMAX_JPEG_DECODER *decoder, char *sourceImage, size_t imageSize)
void cleanup (OPENMAX_JPEG_DECODER *decoder)
Macro Definition Documentation
OMXJPEG_ERROR_CREATING_COMP
#define OMXJPEG_ERROR_CREATING_COMP -1027
Definition at line 50 of file jpeg.h.
Referenced by prepareImageDecoder(), and prepareResizer().
OMXJPEG_ERROR_EXECUTING
#define OMXJPEG_ERROR_EXECUTING -1029
Definition at line 52 of file jpeg.h.
Referenced by startupImageDecoder().
OMXJPEG_ERROR_ILCLIENT_INIT
#define OMXJPEG_ERROR_ILCLIENT_INIT -1024
Definition at line 47 of file jpeg.h.
OMXJPEG_ERROR_MEMORY
#define OMXJPEG_ERROR_MEMORY -1026
Definition at line 49 of file jpeg.h.
Referenced by decodeImage(), portSettingsChanged(), prepareImageDecoder(), prepareResizer(), setupOpenMaxJpegDecoder(), and startupImageDecoder().
OMXJPEG_ERROR_NOSETTINGS
#define OMXJPEG_ERROR_NOSETTINGS -1030
Definition at line 53 of file jpeg.h.
OMXJPEG_ERROR_OMX_INIT
#define OMXJPEG_ERROR_OMX_INIT -1025
Definition at line 48 of file jpeg.h.
OMXJPEG_ERROR_WRONG_NO_PORTS
#define OMXJPEG_ERROR_WRONG_NO_PORTS -1028
Definition at line 51 of file jpeg.h.
Referenced by prepareImageDecoder(), and prepareResizer().
OMXJPEG_OK
#define OMXJPEG_OK 0
Definition at line 46 of file jpeg.h.
Referenced by decodeImage(), portSettingsChanged(), portSettingsChangedAgain(), prepareImageDecoder(), prepareResizer(), and startupImageDecoder().
Typedef Documentation
OPENMAX_JPEG_DECODER
typedef struct _OPENMAX_JPEG_DECODER OPENMAX_JPEG_DECODER
Definition at line 55 of file jpeg.h.
Function Documentation
cleanup()
void cleanup (OPENMAX_JPEG_DECODER * decoder)
Definition at line 569 of file jpeg.c.
References _OPENMAX_JPEG_DECODER::client, _COMPONENT_DETAILS::component, _COMPONENT_DETAILS::handle, ilclient_change_component_state(), ilclient_destroy(), ilclient_wait_for_event(), _OPENMAX_JPEG_DECODER::imageDecoder, _OPENMAX_JPEG_DECODER::imageResizer, _COMPONENT_DETAILS::inPort, _OPENMAX_JPEG_DECODER::inputBufferHeaderCount, NULL, OMX_CommandFlush, OMX_CommandPortDisable, OMX_CommandStateSet, OMX_Deinit(), OMX_EventCmdComplete, OMX_FreeBuffer, OMX_SendCommand, OMX_SetupTunnel(), OMX_StateIdle, OMX_StateLoaded, _COMPONENT_DETAILS::outPort, _OPENMAX_JPEG_DECODER::pOutputBufferHeader, _OPENMAX_JPEG_DECODER::ppInputBufferHeader, and TIMEOUT_MS.
Referenced by main().
 {
     // flush everything through
     OMX_SendCommand(decoder->imageDecoder->handle,
             OMX_CommandFlush, decoder->imageDecoder->outPort,
             NULL);
     ilclient_wait_for_event(decoder->imageDecoder->component,
                 OMX_EventCmdComplete, OMX_CommandFlush, 0,
                 decoder->imageDecoder->outPort, 0, 0,
                 TIMEOUT_MS);
     OMX_SendCommand(decoder->imageResizer->handle, OMX_CommandFlush,
             decoder->imageResizer->inPort, NULL);
     ilclient_wait_for_event(decoder->imageResizer->component,
                 OMX_EventCmdComplete, OMX_CommandFlush, 0,
                 decoder->imageResizer->inPort, 1, 0,
                 TIMEOUT_MS);
     OMX_SendCommand(decoder->imageDecoder->handle, OMX_CommandPortDisable,
             decoder->imageDecoder->inPort, NULL);
     int             i = 0;
     for (i = 0; i < decoder->inputBufferHeaderCount; i++) {
     OMX_BUFFERHEADERTYPE *vpBufHeader =
         decoder->ppInputBufferHeader[i];
     OMX_FreeBuffer(decoder->imageDecoder->handle,
                decoder->imageDecoder->inPort, vpBufHeader);
     }
     ilclient_wait_for_event(decoder->imageDecoder->component,
                 OMX_EventCmdComplete, OMX_CommandPortDisable,
                 0, decoder->imageDecoder->inPort, 0, 0,
                 TIMEOUT_MS);
     OMX_SendCommand(decoder->imageResizer->handle, OMX_CommandPortDisable,
             decoder->imageResizer->outPort, NULL);
     OMX_FreeBuffer(decoder->imageResizer->handle,
            decoder->imageResizer->outPort,
            decoder->pOutputBufferHeader);
     ilclient_wait_for_event(decoder->imageResizer->component,
                 OMX_EventCmdComplete, OMX_CommandPortDisable,
                 0, decoder->imageResizer->outPort, 0, 0,
                 TIMEOUT_MS);
     OMX_SendCommand(decoder->imageDecoder->handle, OMX_CommandPortDisable,
             decoder->imageDecoder->outPort, NULL);
     ilclient_wait_for_event(decoder->imageDecoder->component,
                 OMX_EventCmdComplete, OMX_CommandPortDisable,
                 0, decoder->imageDecoder->outPort, 0, 0,
                 TIMEOUT_MS);
     OMX_SendCommand(decoder->imageResizer->handle, OMX_CommandPortDisable,
             decoder->imageResizer->inPort, NULL);
     ilclient_wait_for_event(decoder->imageResizer->component,
                 OMX_EventCmdComplete, OMX_CommandPortDisable,
                 0, decoder->imageResizer->inPort, 0, 0,
                 TIMEOUT_MS);
     OMX_SetupTunnel(decoder->imageDecoder->handle,
             decoder->imageDecoder->outPort, NULL, 0);
     OMX_SetupTunnel(decoder->imageResizer->handle,
             decoder->imageResizer->inPort, NULL, 0);
     ilclient_change_component_state(decoder->imageDecoder->component,
                     OMX_StateIdle);
     ilclient_change_component_state(decoder->imageResizer->component,
                     OMX_StateIdle);
     ilclient_wait_for_event(decoder->imageDecoder->component,
                 OMX_EventCmdComplete, OMX_CommandStateSet, 0,
                 OMX_StateIdle, 0, 0, TIMEOUT_MS);
     ilclient_wait_for_event(decoder->imageResizer->component,
                 OMX_EventCmdComplete, OMX_CommandStateSet, 0,
                 OMX_StateIdle, 0, 0, TIMEOUT_MS);
     ilclient_change_component_state(decoder->imageDecoder->component,
                     OMX_StateLoaded);
     ilclient_change_component_state(decoder->imageResizer->component,
                     OMX_StateLoaded);
     ilclient_wait_for_event(decoder->imageDecoder->component,
                 OMX_EventCmdComplete, OMX_CommandStateSet, 0,
                 OMX_StateLoaded, 0, 0, TIMEOUT_MS);
     ilclient_wait_for_event(decoder->imageResizer->component,
                 OMX_EventCmdComplete, OMX_CommandStateSet, 0,
                 OMX_StateLoaded, 0, 0, TIMEOUT_MS);
     OMX_Deinit();
     if (decoder->client != NULL) {
     ilclient_destroy(decoder->client);
     }
 }
decodeImage()
int decodeImage (OPENMAX_JPEG_DECODER * decoder, char * sourceImage, size_t imageSize)
Definition at line 442 of file jpeg.c.
References bufferIndex, _COMPONENT_DETAILS::component, _COMPONENT_DETAILS::handle, ilclient_remove_event(), ilclient_wait_for_event(), _OPENMAX_JPEG_DECODER::imageDecoder, _OPENMAX_JPEG_DECODER::imageResizer, _OPENMAX_JPEG_DECODER::inputBufferHeaderCount, OMX_BUFFERHEADERTYPE::nAllocLen, OMX_BUFFERHEADERTYPE::nFilledLen, OMX_BUFFERHEADERTYPE::nFlags, OMX_BUFFERHEADERTYPE::nOffset, NULL, OMX_BUFFERFLAG_EOS, OMX_EmptyThisBuffer, OMX_ErrorNone, OMX_EventBufferFlag, OMX_EventPortSettingsChanged, OMX_FillThisBuffer, OMXJPEG_ERROR_MEMORY, OMXJPEG_OK, _COMPONENT_DETAILS::outPort, OMX_BUFFERHEADERTYPE::pBuffer, portSettingsChanged(), portSettingsChangedAgain(), _OPENMAX_JPEG_DECODER::pOutputBufferHeader, and _OPENMAX_JPEG_DECODER::ppInputBufferHeader.
Referenced by main().
 {
     char           *sourceOffset = sourceImage; // we store a separate
                         // buffer ot image so we
                         // can offset it
     size_t          toread = 0; // bytes left to read from buffer
     toread += imageSize;
     int             bFilled = 0;    // have we filled our output
                     // buffer
     bufferIndex = 0;
     while (toread > 0) {
     // get next buffer from array
     OMX_BUFFERHEADERTYPE *pBufHeader =
         decoder->ppInputBufferHeader[bufferIndex];
     // step index and reset to 0 if required
     bufferIndex++;
     if (bufferIndex >= decoder->inputBufferHeaderCount)
         bufferIndex = 0;
     // work out the next chunk to load into the decoder
     if (toread > pBufHeader->nAllocLen)
         pBufHeader->nFilledLen = pBufHeader->nAllocLen;
     else
         pBufHeader->nFilledLen = toread;
     toread = toread - pBufHeader->nFilledLen;
     // pass the bytes to the buffer
     memcpy(pBufHeader->pBuffer, sourceOffset, pBufHeader->nFilledLen);
     // update the buffer pointer and set the input flags
     sourceOffset = sourceOffset + pBufHeader->nFilledLen;
     pBufHeader->nOffset = 0;
     pBufHeader->nFlags = 0;
     if (toread <= 0) {
         pBufHeader->nFlags = OMX_BUFFERFLAG_EOS;
     }
     // empty the current buffer
     int             ret =
         OMX_EmptyThisBuffer(decoder->imageDecoder->handle,
                 pBufHeader);
     if (ret != OMX_ErrorNone) {
         perror("Empty input buffer");
         fprintf(stderr, "return code %x\n", ret);
         return OMXJPEG_ERROR_MEMORY;
     }
     // wait for buffer to empty or port changed event
     int             done = 0;
     while ((done == 0) && (decoder->pOutputBufferHeader == NULL)) {
         if (decoder->pOutputBufferHeader == NULL) {
         ret =
             ilclient_wait_for_event
             (decoder->imageDecoder->component,
              OMX_EventPortSettingsChanged,
              decoder->imageDecoder->outPort, 0, 0, 1, 0, 5);
         if (ret == 0) {
             ret = portSettingsChanged(decoder);
             if (ret != OMXJPEG_OK)
             return ret;
         }
         } else {
         ret =
             ilclient_remove_event(decoder->imageDecoder->component,
                       OMX_EventPortSettingsChanged,
                       decoder->imageDecoder->outPort,
                       0, 0, 1);
         if (ret == 0)
             portSettingsChangedAgain(decoder);
         }
         // check to see if buffer is now empty
         if (pBufHeader->nFilledLen == 0)
         done = 1;
         if ((done == 0)
         || (decoder->pOutputBufferHeader == NULL))
         sleep(1);
     }
     // fill the buffer if we have created the buffer
     if ((bFilled == 0) && (decoder->pOutputBufferHeader != NULL)) {
         ret = OMX_FillThisBuffer(decoder->imageResizer->handle,
                      decoder->pOutputBufferHeader);
         if (ret != OMX_ErrorNone) {
         perror("Filling output buffer");
         fprintf(stderr, "Error code %x\n", ret);
         return OMXJPEG_ERROR_MEMORY;
         }
         bFilled = 1;
     }
     }
     // wait for buffer to fill
     /*
      * while(pBufHeader->nFilledLen == 0) { sleep(5); }
      */
     // wait for end of stream events
     int             ret =
     ilclient_wait_for_event(decoder->imageDecoder->component,
                 OMX_EventBufferFlag,
                 decoder->imageDecoder->outPort, 1,
                 OMX_BUFFERFLAG_EOS, 1,
                 0, 2);
     if (ret != 0) {
     fprintf(stderr, "No EOS event on image decoder %d\n", ret);
     }
     ret = ilclient_wait_for_event(decoder->imageResizer->component,
                   OMX_EventBufferFlag,
                   decoder->imageResizer->outPort, 1,
                   OMX_BUFFERFLAG_EOS, 1, 0, 2);
     if (ret != 0) {
     fprintf(stderr, "No EOS event on image resizer %d\n", ret);
     }
     return OMXJPEG_OK;
 }
setupOpenMaxJpegDecoder()
int setupOpenMaxJpegDecoder (OPENMAX_JPEG_DECODER ** decoder)
Definition at line 404 of file jpeg.c.
References NULL, and OMXJPEG_ERROR_MEMORY.
Referenced by main().
 {
     *pDecoder = malloc(sizeof(OPENMAX_JPEG_DECODER));
     if (pDecoder[0] == NULL) {
     perror("malloc decoder");
     return OMXJPEG_ERROR_MEMORY;
     }
     memset(*pDecoder, 0, sizeof(OPENMAX_JPEG_DECODER));
     if ((pDecoder[0]->client = ilclient_init()) == NULL) {
     perror("ilclient_init");
     return OMXJPEG_ERROR_ILCLIENT_INIT;
     }
     if (OMX_Init() != OMX_ErrorNone) {
     ilclient_destroy(pDecoder[0]->client);
     perror("OMX_Init");
     return OMXJPEG_ERROR_OMX_INIT;
     }
     // prepare the image decoder
     int             ret = prepareImageDecoder(pDecoder[0]);
     if (ret != OMXJPEG_OK)
     return ret;
     ret = prepareResizer(pDecoder[0]);
     if (ret != OMXJPEG_OK)
     return ret;
     ret = startupImageDecoder(pDecoder[0]);
     if (ret != OMXJPEG_OK)
     return ret;
     return OMXJPEG_OK;
 }