VideoCore Library: containers/core/containers_time.h File Reference
containers_time.h File Reference
Classes
struct VC_CONTAINER_TIME_T
Typedefs
typedef struct VC_CONTAINER_TIME_T VC_CONTAINER_TIME_T
Functions
STATIC_INLINE void vc_container_time_init (VC_CONTAINER_TIME_T *time, uint32_t time_base)
STATIC_INLINE int64_t vc_container_time_get (VC_CONTAINER_TIME_T *time)
STATIC_INLINE void vc_container_time_set_samplerate (VC_CONTAINER_TIME_T *time, uint32_t samplerate_num, uint32_t samplerate_den)
STATIC_INLINE void vc_container_time_set (VC_CONTAINER_TIME_T *time, int64_t new_time)
STATIC_INLINE int64_t vc_container_time_add (VC_CONTAINER_TIME_T *time, uint32_t samples)
Detailed Description
Utility functions to help with timestamping of elementary stream frames
Definition in file containers_time.h.
Typedef Documentation
VC_CONTAINER_TIME_T
typedef struct VC_CONTAINER_TIME_T VC_CONTAINER_TIME_T
Function Documentation
vc_container_time_add()
STATIC_INLINE int64_t vc_container_time_add (VC_CONTAINER_TIME_T * time, uint32_t samples)
Definition at line 89 of file containers_time.h.
References VC_CONTAINER_TIME_T::remainder, VC_CONTAINER_TIME_T::samplerate_den, VC_CONTAINER_TIME_T::samplerate_num, VC_CONTAINER_TIME_T::time, VC_CONTAINER_TIME_T::time_base, vc_container_time_get(), and VC_CONTAINER_TIME_UNKNOWN.
 {
    uint32_t increment;
    if (time->time == VC_CONTAINER_TIME_UNKNOWN || !time->samplerate_num || !time->samplerate_den)
       return VC_CONTAINER_TIME_UNKNOWN;
    samples += time->remainder;
    increment = samples * time->samplerate_den / time->samplerate_num;
    time->time += increment * time->time_base;
    time->remainder = samples - increment * time->samplerate_num / time->samplerate_den;
    return vc_container_time_get(time);
 }
vc_container_time_get()
STATIC_INLINE int64_t vc_container_time_get (VC_CONTAINER_TIME_T * time)
Definition at line 57 of file containers_time.h.
References VC_CONTAINER_TIME_T::remainder, VC_CONTAINER_TIME_T::samplerate_den, VC_CONTAINER_TIME_T::samplerate_num, VC_CONTAINER_TIME_T::time, VC_CONTAINER_TIME_T::time_base, and VC_CONTAINER_TIME_UNKNOWN.
Referenced by vc_container_time_add(), and vc_container_time_set_samplerate().
 {
    if (time->time == VC_CONTAINER_TIME_UNKNOWN || !time->samplerate_num || !time->samplerate_den)
       return VC_CONTAINER_TIME_UNKNOWN;
    return time->time + time->remainder * (int64_t)time->time_base * time->samplerate_den / time->samplerate_num;
 }
vc_container_time_init()
STATIC_INLINE void vc_container_time_init (VC_CONTAINER_TIME_T * time, uint32_t time_base)
Definition at line 47 of file containers_time.h.
References VC_CONTAINER_TIME_T::remainder, VC_CONTAINER_TIME_T::samplerate_den, VC_CONTAINER_TIME_T::samplerate_num, VC_CONTAINER_TIME_T::time, VC_CONTAINER_TIME_T::time_base, and VC_CONTAINER_TIME_UNKNOWN.
Referenced by vc_packetizer_open().
 {
    time->samplerate_num = 0;
    time->samplerate_den = 0;
    time->remainder = 0;
    time->time_base = time_base;
    time->time = VC_CONTAINER_TIME_UNKNOWN;
 }
vc_container_time_set()
STATIC_INLINE void vc_container_time_set (VC_CONTAINER_TIME_T * time, int64_t new_time)
Definition at line 80 of file containers_time.h.
References VC_CONTAINER_TIME_T::remainder, VC_CONTAINER_TIME_T::time, and VC_CONTAINER_TIME_UNKNOWN.
 {
    if (new_time == VC_CONTAINER_TIME_UNKNOWN)
       return;
    time->remainder = 0;
    time->time = new_time;
 }
vc_container_time_set_samplerate()
STATIC_INLINE void vc_container_time_set_samplerate (VC_CONTAINER_TIME_T * time, uint32_t samplerate_num, uint32_t samplerate_den)
Definition at line 65 of file containers_time.h.
References VC_CONTAINER_TIME_T::remainder, VC_CONTAINER_TIME_T::samplerate_den, VC_CONTAINER_TIME_T::samplerate_num, VC_CONTAINER_TIME_T::time, and vc_container_time_get().
Referenced by pcm_packetizer_open().
 {
    if(time->samplerate_num == samplerate_num &&
       time->samplerate_den == samplerate_den)
       return;
    /* We're changing samplerate, we need to reset our remainder */
    if(time->remainder)
       time->time = vc_container_time_get( time );
    time->remainder = 0;
    time->samplerate_num = samplerate_num;
    time->samplerate_den = samplerate_den;
 }