VideoCore Library: Pools of buffer headers
Pools of buffer headers
Classes
struct MMAL_POOL_T
Typedefs
typedef struct MMAL_POOL_T MMAL_POOL_T
typedef void *(* mmal_pool_allocator_alloc_t) (void *context, uint32_t size)
typedef void(* mmal_pool_allocator_free_t) (void *context, void *mem)
typedef MMAL_BOOL_T(* MMAL_POOL_BH_CB_T) (MMAL_POOL_T *pool, MMAL_BUFFER_HEADER_T *buffer, void *userdata)
Functions
MMAL_POOL_T * mmal_pool_create (unsigned int headers, uint32_t payload_size)
MMAL_POOL_T * mmal_pool_create_with_allocator (unsigned int headers, uint32_t payload_size, void *allocator_context, mmal_pool_allocator_alloc_t allocator_alloc, mmal_pool_allocator_free_t allocator_free)
void mmal_pool_destroy (MMAL_POOL_T *pool)
MMAL_STATUS_T mmal_pool_resize (MMAL_POOL_T *pool, unsigned int headers, uint32_t payload_size)
void mmal_pool_callback_set (MMAL_POOL_T *pool, MMAL_POOL_BH_CB_T cb, void *userdata)
void mmal_pool_pre_release_callback_set (MMAL_POOL_T *pool, MMAL_BH_PRE_RELEASE_CB_T cb, void *userdata)
Detailed Description
A pool of buffer headers is composed of a queue (MMAL_QUEUE_T) and a user specified number of buffer headers (MMAL_BUFFER_HEADER_T).
Typedef Documentation
mmal_pool_allocator_alloc_t
typedef void*(* mmal_pool_allocator_alloc_t) (void *context, uint32_t size)
Allocator alloc prototype
Parameters
context The context pointer passed in on pool creation.
size The size of the allocation required, in bytes.
Returns
The pointer to the newly allocated memory, or NULL on failure.
Definition at line 56 of file mmal_pool.h.
mmal_pool_allocator_free_t
typedef void(* mmal_pool_allocator_free_t) (void *context, void *mem)
Allocator free prototype
Parameters
context The context pointer passed in on pool creation.
mem The pointer to the memory to be released.
Definition at line 62 of file mmal_pool.h.
MMAL_POOL_BH_CB_T
typedef MMAL_BOOL_T(* MMAL_POOL_BH_CB_T) (MMAL_POOL_T *pool, MMAL_BUFFER_HEADER_T *buffer, void *userdata)
Definition of the callback used by a pool to signal back to the user that a buffer header has been released back to the pool.
Parameters
pool Pointer to the pool
buffer Buffer header just released
userdata User specific data passed in when setting the callback
Returns
True to have the buffer header put back in the pool's queue, false if the buffer header has been taken within the callback.
Definition at line 140 of file mmal_pool.h.
MMAL_POOL_T
typedef struct MMAL_POOL_T MMAL_POOL_T
Definition of a pool
Function Documentation
mmal_pool_callback_set()
void mmal_pool_callback_set (MMAL_POOL_T * pool, MMAL_POOL_BH_CB_T cb, void * userdata)
Set a buffer header release callback to the pool. Each time a buffer header is released to the pool, the callback will be triggered.
Parameters
pool Pointer to a pool
cb Callback function
userdata User specific data which will be passed with each callback
Set a buffer header release callback to the pool
Definition at line 283 of file mmal_pool.c.
References MMAL_POOL_PRIVATE_T::cb, and MMAL_POOL_PRIVATE_T::userdata.
Referenced by mmal_connection_create(), and mmal_wrapper_create().
 {
    MMAL_POOL_PRIVATE_T *private = (MMAL_POOL_PRIVATE_T *)pool;
    private->cb = cb;
    private->userdata = userdata;
 }
mmal_pool_create()
MMAL_POOL_T* mmal_pool_create (unsigned int headers, uint32_t payload_size)
Create a pool of MMAL_BUFFER_HEADER_T. After allocation, all allocated buffer headers will have been added to the queue.
It is valid to create a pool with no buffer headers, or with zero size payload buffers. The mmal_pool_resize() function can be used to increase or decrease the number of buffer headers, or the size of the payload buffers, after creation of the pool.
The payload buffers may also be allocated independently by the client, and assigned to the buffer headers, but it will be the responsibility of the client to deal with resizing and releasing the memory. It is recommended that mmal_pool_create_with_allocator() is used in this case, supplying allocator function pointers that will be used as necessary by MMAL.
Parameters
headers Number of buffer headers to be allocated with the pool.
payload_size Size of the payload buffer that will be allocated in each of the buffer headers.
Returns
Pointer to the newly created pool or NULL on failure.
Create a pool of MMAL_BUFFER_HEADER_T
Definition at line 120 of file mmal_pool.c.
References mmal_pool_create_with_allocator(), and NULL.
 {
    return mmal_pool_create_with_allocator(headers, payload_size, NULL,
              mmal_pool_allocator_default_alloc, mmal_pool_allocator_default_free);
 }
mmal_pool_create_with_allocator()
MMAL_POOL_T* mmal_pool_create_with_allocator (unsigned int headers, uint32_t payload_size, void * allocator_context, mmal_pool_allocator_alloc_t allocator_alloc, mmal_pool_allocator_free_t allocator_free)
Create a pool of MMAL_BUFFER_HEADER_T. After allocation, all allocated buffer headers will have been added to the queue.
It is valid to create a pool with no buffer headers, or with zero size payload buffers. The mmal_pool_resize() function can be used to increase or decrease the number of buffer headers, or the size of the payload buffers, after creation of the pool. The allocators passed during creation shall be used when resizing the payload buffers.
Parameters
headers Number of buffer headers to be allocated with the pool.
payload_size Size of the payload buffer that will be allocated in each of the buffer headers.
allocator_context Pointer to the context of the allocator.
allocator_alloc Function pointer for the alloc call of the allocator.
allocator_free Function pointer for the free call of the allocator.
Returns
Pointer to the newly created pool or NULL on failure.
Create a pool of MMAL_BUFFER_HEADER_T
Definition at line 127 of file mmal_pool.c.
References ALIGN, MMAL_POOL_T::header, MMAL_POOL_PRIVATE_T::header_size, LOG_ERROR, LOG_TRACE, mmal_buffer_header_size(), mmal_queue_create(), mmal_queue_destroy(), NULL, MMAL_POOL_PRIVATE_T::payload_size, MMAL_POOL_PRIVATE_T::pool, MMAL_POOL_T::queue, ROUND_UP, vcos_calloc(), and vcos_free().
Referenced by mmal_pool_create(), and mmal_port_pool_create().
 {
    unsigned int i, headers_array_size, header_size, pool_size;
    MMAL_POOL_PRIVATE_T *private;
    MMAL_BUFFER_HEADER_T **array;
    MMAL_POOL_T *pool;
    MMAL_QUEUE_T *queue;
    queue = mmal_queue_create();
    if (!queue)
    {
       LOG_ERROR("failed to create queue");
       return NULL;
    }
    /* Calculate how much memory we need */
    pool_size = ROUND_UP(sizeof(MMAL_POOL_PRIVATE_T),ALIGN);
    headers_array_size = ROUND_UP(sizeof(void *)*headers,ALIGN);
    header_size = ROUND_UP(mmal_buffer_header_size(0),ALIGN);
    LOG_TRACE("allocating %u + %u + %u * %u bytes for pool",
              pool_size, headers_array_size, header_size, headers);
    private = vcos_calloc(pool_size, 1, "MMAL pool");
    array = vcos_calloc(headers_array_size + header_size * headers, 1, "MMAL buffer headers");
    if (!private || !array)
    {
       LOG_ERROR("failed to allocate pool");
       if (private) vcos_free(private);
       if (array) vcos_free(array);
       mmal_queue_destroy(queue);
       return NULL;
    }
    pool = &private->pool;
    pool->queue = queue;
    pool->header = (MMAL_BUFFER_HEADER_T **)array;
    private->header_size = header_size;
    private->payload_size = payload_size;
    private->headers_alloc_num = headers;
    /* Use default allocators if none has been specified by client */
    if (!allocator_alloc || !allocator_free)
    {
       allocator_alloc = mmal_pool_allocator_default_alloc;
       allocator_free = mmal_pool_allocator_default_free;
       allocator_context = NULL;
    }
    /* Keep reference to the allocator to allow resizing the payloads at a later point */
    private->allocator_alloc = allocator_alloc;
    private->allocator_free = allocator_free;
    private->allocator_context = allocator_context;
    if (mmal_pool_initialise_buffer_headers(pool, headers, 1) != MMAL_SUCCESS)
    {
       mmal_pool_destroy(pool);
       return NULL;
    }
    /* Add all the headers to the queue */
    for (i = 0; i < pool->headers_num; i++)
       mmal_queue_put(queue, pool->header[i]);
    return pool;
 }
mmal_pool_destroy()
void mmal_pool_destroy (MMAL_POOL_T * pool)
Destroy a pool of MMAL_BUFFER_HEADER_T. This will also deallocate all of the memory which was allocated when creating or resizing the pool.
If payload buffers have been allocated independently by the client, they should be released prior to calling this function. If the client provided allocator functions, the allocator_free function shall be called for each payload buffer.
Parameters
pool Pointer to a pool
Destroy a pool of MMAL_BUFFER_HEADER_T
Definition at line 195 of file mmal_pool.c.
References MMAL_POOL_T::header, MMAL_POOL_T::headers_num, mmal_queue_destroy(), MMAL_BUFFER_HEADER_PRIVATE_T::payload, MMAL_BUFFER_HEADER_PRIVATE_T::payload_context, MMAL_BUFFER_HEADER_PRIVATE_T::payload_size, MMAL_BUFFER_HEADER_PRIVATE_T::pf_payload_free, MMAL_BUFFER_HEADER_T::priv, MMAL_POOL_T::queue, and vcos_free().
Referenced by mmal_port_pool_destroy(), mmal_wrapper_destroy(), OMX_FreeHandle(), raspitex_destroy(), and svp_destroy().
 {
    unsigned int i;
    if (!pool)
       return;
    /* If the payload_size is non-zero then the buffer header payload
     * must be freed. Otherwise it is the caller's responsibility. */
    for (i = 0; i < pool->headers_num; ++i)
    {
       MMAL_BUFFER_HEADER_PRIVATE_T* priv = pool->header[i]->priv;
       if (priv->pf_payload_free && priv->payload && priv->payload_size)
          priv->pf_payload_free(priv->payload_context, priv->payload);
    }
    if (pool->header)
       vcos_free(pool->header);
    if(pool->queue) mmal_queue_destroy(pool->queue);
    vcos_free(pool);
 }
mmal_pool_pre_release_callback_set()
void mmal_pool_pre_release_callback_set (MMAL_POOL_T * pool, MMAL_BH_PRE_RELEASE_CB_T cb, void * userdata)
Set a pre-release callback for all buffer headers in the pool. Each time a buffer header is about to be released to the pool, the callback will be triggered.
Parameters
pool Pointer to the pool
cb Pre-release callback function
userdata User-specific data passed back with each callback
Definition at line 291 of file mmal_pool.c.
References ALIGN, MMAL_POOL_T::header, MMAL_POOL_T::headers_num, mmal_buffer_header_pre_release_cb_set(), and ROUND_UP.
 {
    unsigned int i;
    MMAL_POOL_PRIVATE_T *private = (MMAL_POOL_PRIVATE_T *)pool;
    MMAL_BUFFER_HEADER_T *header =
          (MMAL_BUFFER_HEADER_T*)((uint8_t*)pool->header + ROUND_UP(sizeof(void*)*pool->headers_num,ALIGN));
    for (i = 0; i < pool->headers_num; ++i)
    {
       mmal_buffer_header_pre_release_cb_set(header, cb, userdata);
       header = (MMAL_BUFFER_HEADER_T *)((uint8_t*)header + private->header_size);
    }
 }
mmal_pool_resize()
MMAL_STATUS_T mmal_pool_resize (MMAL_POOL_T * pool, unsigned int headers, uint32_t payload_size)
Resize a pool of MMAL_BUFFER_HEADER_T. This allows modifying either the number of allocated buffers, the payload size or both at the same time.
Parameters
pool Pointer to the pool
headers New number of buffer headers to be allocated in the pool. It is not valid to pass zero for the number of buffers.
payload_size Size of the payload buffer that will be allocated in each of the buffer headers. If this is set to 0, all payload buffers shall be released.
Returns
MMAL_SUCCESS or an error on failure.
Resize a pool of MMAL_BUFFER_HEADER_T
Definition at line 220 of file mmal_pool.c.
References MMAL_POOL_T::headers_num, MMAL_EINVAL, mmal_queue_get(), MMAL_SUCCESS, and MMAL_POOL_T::queue.
Referenced by mmal_connection_enable(), and mmal_wrapper_port_enable().
 {
    MMAL_POOL_PRIVATE_T *private = (MMAL_POOL_PRIVATE_T *)pool;
    unsigned int i;
    if (!private || !headers)
       return MMAL_EINVAL;
    /* Check if anything needs to be done */
    if (headers == pool->headers_num && payload_size == private->payload_size)
       return MMAL_SUCCESS;
    /* Remove all the headers from the queue */
    for (i = 0; i < pool->headers_num; i++)
       mmal_queue_get(pool->queue);
    /* Start by freeing the current payloads */
    private->payload_size = 0;
    mmal_pool_initialise_buffer_headers(pool, pool->headers_num, 0);
    pool->headers_num = 0;
    /* Check if we need to reallocate the buffer headers themselves */
    if (headers > private->headers_alloc_num)
    {
       private->headers_alloc_num = 0;
       if (pool->header)
          vcos_free(pool->header);
       pool->header =
          vcos_calloc(private->header_size * headers + ROUND_UP(sizeof(void *)*headers,ALIGN),
                      1, "MMAL buffer headers");
       if (!pool->header)
          return MMAL_ENOMEM;
       private->headers_alloc_num = headers;
    }
    /* Allocate the new payloads */
    private->payload_size = payload_size;
    mmal_pool_initialise_buffer_headers(pool, headers, 1);
    /* Add all the headers to the queue */
    for (i = 0; i < pool->headers_num; i++)
       mmal_queue_put(pool->queue, pool->header[i]);
    return MMAL_SUCCESS;
 }