VideoCore Library: host_applications/linux/apps/hello_pi/libs/vgfont/graphics_x_private.h File Reference
graphics_x_private.h File Reference
#include "EGL/egl.h"
#include "EGL/eglext.h"
#include "VG/openvg.h"
#include "VG/vgu.h"
#include "vgfont.h"
#include "bcm_host.h"
Classes
struct GX_NATIVE_WINDOW_T
struct GX_PAINT_T
struct GX_DISPLAY_T
struct GX_DISPLAY_T
struct GRAPHICS_RESOURCE_HANDLE_TABLE_T
struct GX_CLIENT_STATE_T
Macros
#define VCOS_LOG_CATEGORY (&gx_log_cat)
#define LOG_ERR(fmt, arg...) vcos_log_error("%s:%d " fmt, __func__, __LINE__, ##arg)
#define GX_ERROR(format, arg...) if (1) {} else printf(format "\n", ##arg)
#define GX_LOG(format, arg...) if (1) {} else printf(format "\n", ##arg)
#define GX_TRACE(format, arg...) if (1) {} else printf(format "\n", ##arg)
#define RES_MAGIC ('G'<<24|'X'<<16|'R'<<8|'S'<<0)
#define GX_PRIV_FLAG_FLIP (1<<0)
Typedefs
typedef struct GX_CLIENT_STATE_T GX_CLIENT_STATE_T
typedef struct GRAPHICS_RESOURCE_HANDLE_TABLE_T GRAPHICS_RESOURCE_HANDLE_TABLE_T
Enumerations
enum GX_RASTER_ORDER_T { GX_TOP_BOTTOM, GX_BOTTOM_TOP }
enum GX_RES_TYPE { GX_WINDOW, GX_PIXMAP, GX_PBUFFER }
Functions
void gx_priv_init (void)
void gx_priv_destroy (void)
void gx_priv_colour_to_paint (uint32_t col, VGfloat *rgba)
void gx_priv_save (GX_CLIENT_STATE_T *state, GRAPHICS_RESOURCE_HANDLE res)
void gx_priv_restore (GX_CLIENT_STATE_T *state)
int gx_priv_create_native_window (uint32_t screen_id, uint32_t w, uint32_t h, GRAPHICS_RESOURCE_TYPE_T type, GX_NATIVE_WINDOW_T *win, void **cookie)
void gx_priv_destroy_native_window (GRAPHICS_RESOURCE_HANDLE_TABLE_T *res)
VCOS_STATUS_T gx_priv_font_init (const char *font_dir)
void gx_priv_font_term (void)
VCOS_STATUS_T gx_priv_resource_fill (GRAPHICS_RESOURCE_HANDLE res, uint32_t x, uint32_t y, uint32_t width, uint32_t height, uint32_t fill_colour)
VCOS_STATUS_T gx_priv_render_text (GX_DISPLAY_T *disp, GRAPHICS_RESOURCE_HANDLE res, int32_t x, int32_t y, uint32_t width, uint32_t height, uint32_t fg_colour, uint32_t bg_colour, const char *text, uint32_t text_length, uint32_t text_size)
void gx_priv_flush (GRAPHICS_RESOURCE_HANDLE res)
void gx_priv_finish_native_window (GRAPHICS_RESOURCE_HANDLE_TABLE_T *res, void *cookie)
void gx_font_cache_flush (void)
int gx_priv_read_bmp (const char *file_name, uint32_t *width, uint32_t *height, uint32_t *pitch_bytes, GRAPHICS_RESOURCE_TYPE_T *restype, VGImageFormat *vg_format, uint32_t *flags, uint32_t *image_data_size, void **pimage_data)
int gx_priv_read_tga (const char *file_name, uint32_t *width, uint32_t *height, uint32_t *pitch_bytes, GRAPHICS_RESOURCE_TYPE_T *restype, VGImageFormat *vg_format, uint32_t *flags, uint32_t *image_data_size, void **pimage_data)
Variables
VCOS_LOG_CAT_T gx_log_cat
Macro Definition Documentation
GX_ERROR
#define GX_ERROR (format, arg...) if (1) {} else printf(format "\n", ##arg)
Definition at line 47 of file graphics_x_private.h.
Referenced by graphics_resource_set_alpha_per_colour().
GX_LOG
#define GX_LOG (format, arg...) if (1) {} else printf(format "\n", ##arg)
Definition at line 48 of file graphics_x_private.h.
Referenced by graphics_bitblt(), gx_create_pbuffer(), gx_priv_get_pixels(), and gx_priv_resource_fill().
GX_PRIV_FLAG_FLIP
#define GX_PRIV_FLAG_FLIP (1<<0)
Definition at line 80 of file graphics_x_private.h.
GX_TRACE
#define GX_TRACE (format, arg...) if (1) {} else printf(format "\n", ##arg)
Definition at line 49 of file graphics_x_private.h.
Referenced by graphics_delete_resource(), and gx_priv_get_pixels().
LOG_ERR
#define LOG_ERR (fmt, arg...) vcos_log_error("%s:%d " fmt, __func__, __LINE__, ##arg)
Definition at line 45 of file graphics_x_private.h.
RES_MAGIC
#define RES_MAGIC ('G'<<24|'X'<<16|'R'<<8|'S'<<0)
Definition at line 79 of file graphics_x_private.h.
Referenced by graphics_delete_resource(), and graphics_display_resource().
VCOS_LOG_CATEGORY
#define VCOS_LOG_CATEGORY (&gx_log_cat)
Definition at line 33 of file graphics_x_private.h.
Typedef Documentation
GRAPHICS_RESOURCE_HANDLE_TABLE_T
typedef struct GRAPHICS_RESOURCE_HANDLE_TABLE_T GRAPHICS_RESOURCE_HANDLE_TABLE_T
Structure encapsulating the per-surface state.
GX_CLIENT_STATE_T
typedef struct GX_CLIENT_STATE_T GX_CLIENT_STATE_T
Definition at line 64 of file graphics_x_private.h.
Enumeration Type Documentation
GX_RASTER_ORDER_T
enum GX_RASTER_ORDER_T
Enumerator
GX_TOP_BOTTOM
GX_BOTTOM_TOP
Definition at line 56 of file graphics_x_private.h.
 {
    GX_TOP_BOTTOM,
    GX_BOTTOM_TOP,
 } GX_RASTER_ORDER_T;
GX_RES_TYPE
enum GX_RES_TYPE
Enumerator
GX_WINDOW
GX_PIXMAP
GX_PBUFFER
Definition at line 74 of file graphics_x_private.h.
 {
    GX_WINDOW, GX_PIXMAP, GX_PBUFFER
 } GX_RES_TYPE;
Function Documentation
gx_font_cache_flush()
void gx_font_cache_flush (void)
Flush font cache.
Definition at line 317 of file font.c.
References gx_font_cache_entry_t::font, gx_font_cache_entry_t::next, NULL, vcos_free(), and vgft_font_term().
Referenced by gx_priv_font_term().
 {
    while (fonts != NULL)
    {
       struct gx_font_cache_entry_t *next = fonts->next;
       vgft_font_term(&fonts->font);
       vcos_free(fonts);
       fonts = next;
    }
 }
gx_priv_colour_to_paint()
void gx_priv_colour_to_paint (uint32_t col, VGfloat * rgba)
add documentation
Parameters
col colour
rgba OpenVG paint colour
Map a colour, which the client will have supplied in RGB888.
Definition at line 641 of file graphics.c.
References ALPHA_888_MASK, B_888_MASK, G_888_MASK, and R_888_MASK.
Referenced by gx_convert_colour(), gx_create_gradient(), and gx_priv_resource_fill().
 {
    // with OpenVG we use RGB order.
    rgba[0] = ((VGfloat)((col & R_888_MASK) >> 16 )) / 0xff;
    rgba[1] = ((VGfloat)((col & G_888_MASK) >> 8 )) / 0xff;
    rgba[2] = ((VGfloat)((col & B_888_MASK) >> 0 )) / 0xff;
    rgba[3] = ((VGfloat)((col & ALPHA_888_MASK) >> 24)) / 0xff;
 }
gx_priv_create_native_window()
int gx_priv_create_native_window (uint32_t screen_id, uint32_t w, uint32_t h, GRAPHICS_RESOURCE_TYPE_T type, GX_NATIVE_WINDOW_T * win, void ** cookie)
Create a native window for a surface.
Parameters
screen_id
w width of the window
h height of the window
type color/raster format of the resource
win upon successful return, holds a handle to the native window
cookie
Returns
VCOS_SUCCESS on success, or error code.
Definition at line 1286 of file graphics.c.
References NULL.
 {
    int rc;
    DISPMANX_DISPLAY_HANDLE_T dispmanx_display;
    VC_RECT_T dst_rect;
    VC_RECT_T src_rect;
    DISPMANX_UPDATE_HANDLE_T current_update;
    *cookie = NULL;
    rc = gx_priv_open_screen(screen_id, &dispmanx_display);
    if (rc < 0)
    {
       GX_LOG("Could not open display %d", screen_id);
       goto fail_screen;
    }
    current_update = vc_dispmanx_update_start(0);
    if (!current_update)
    {
       GX_LOG("Could not start update on screen %d", screen_id);
       goto fail_update;
    }
    src_rect.x = src_rect.y = 0;
    src_rect.width = w << 16;
    src_rect.height = h << 16;
    dst_rect.x = dst_rect.y = 0;
    dst_rect.width = dst_rect.height = 1;
    win->egl_win.width = w;
    win->egl_win.height = h;
    VC_DISPMANX_ALPHA_T alpha;
    memset(&alpha, 0x0, sizeof(VC_DISPMANX_ALPHA_T));
    alpha.flags = DISPMANX_FLAGS_ALPHA_FROM_SOURCE;
    DISPMANX_CLAMP_T clamp;
    memset(&clamp, 0x0, sizeof(DISPMANX_CLAMP_T));
    win->egl_win.element = vc_dispmanx_element_add(current_update, dispmanx_display,
       0 /* layer */, &dst_rect,
       0 /* src */, &src_rect,
       DISPMANX_PROTECTION_NONE,
       &alpha /* alpha */,
       &clamp /* clamp */,
       0 /* transform */);
    if ( !win->egl_win.element )
    {
       GX_LOG("Could not add element %dx%d",w,h);
       vc_dispmanx_update_submit_sync(current_update);
       rc = -1;
    }
    // have to pass back the update so it can be completed *After* the
    // window has been initialised (filled with background colour).
    *cookie = (void*)current_update;
    return 0;
 fail_update:
    gx_priv_release_screen(screen_id);
 fail_screen:
    return rc;
 }
gx_priv_destroy()
void gx_priv_destroy (void)
add documentation
Definition at line 1232 of file graphics.c.
References gx_priv_state_t::lock, and vcos_mutex_delete().
 {
    vcos_mutex_delete(&gx.lock);
 }
gx_priv_destroy_native_window()
void gx_priv_destroy_native_window (GRAPHICS_RESOURCE_HANDLE_TABLE_T * res)
Destroy native window bound to surface.
Parameters
res Handle to surface.
Definition at line 1363 of file graphics.c.
References GX_NATIVE_WINDOW_T::egl_win, EGL_DISPMANX_WINDOW_T::element, GRAPHICS_RESOURCE_HANDLE_TABLE_T::native_window, GRAPHICS_RESOURCE_HANDLE_TABLE_T::u, vc_dispmanx_element_remove(), vc_dispmanx_update_start(), vc_dispmanx_update_submit_sync(), and vcos_assert.
Referenced by graphics_delete_resource().
 {
    DISPMANX_UPDATE_HANDLE_T current_update;
    if((current_update = vc_dispmanx_update_start(0)) != 0)
    {
       int ret = vc_dispmanx_element_remove(current_update, res->u.native_window.egl_win.element);
       vcos_assert(ret == 0);
       ret = vc_dispmanx_update_submit_sync(current_update);
       vcos_assert(ret == 0);
    }
    gx_priv_release_screen(res->screen_id);
 }
gx_priv_finish_native_window()
void gx_priv_finish_native_window (GRAPHICS_RESOURCE_HANDLE_TABLE_T * res, void * cookie)
Called after the EGL/VG initialisation of a window has completed following its creation.
Parameters
res ???
cookie ???
Definition at line 1356 of file graphics.c.
References vc_dispmanx_update_submit_sync().
 {
    vc_dispmanx_update_submit_sync((DISPMANX_UPDATE_HANDLE_T)current_update);
 }
gx_priv_flush()
void gx_priv_flush (GRAPHICS_RESOURCE_HANDLE res)
Flush a surface.
Parameters
res Handle to surface.
Definition at line 630 of file graphics.c.
References GX_DISPLAY_T::disp, eglSwapBuffers(), GRAPHICS_RESOURCE_HANDLE_TABLE_T::surface, and vcos_assert.
Referenced by graphics_update_displayed_resource().
 {
    EGLBoolean result;
    result = eglSwapBuffers(display.disp, res->surface);
    vcos_assert(result);
 }
gx_priv_font_init()
VCOS_STATUS_T gx_priv_font_init (const char * font_dir)
Initialise font from the given directory.
Parameters
font_dir path to font
only supports Vera.tff at the moment?
Returns
VCOS_SUCCESS on success, or error code.
Definition at line 85 of file font.c.
References len, VCOS_ENOMEM, and vgft_init().
 {
    VCOS_STATUS_T ret;
    size_t len;
    int rc;
    if (vgft_init())
    {
       ret = VCOS_ENOMEM;
       goto fail_init;
    }
    int fd = -1;
    // search for the font
    sprintf(fname, "%s/%s", font_dir, default_font.file);
    fd = open(fname, O_RDONLY);
    if (fd < 0)
    {
       GX_ERROR("Could not open font file '%s'", default_font.file);
       ret = VCOS_ENOENT;
       goto fail_open;
    }
    len = lseek(fd, 0, SEEK_END);
    lseek(fd, 0, SEEK_SET);
    default_font.mem = vcos_malloc(len, default_font.file);
    if (!default_font.mem)
    {
       GX_ERROR("No memory for font %s", fname);
       ret = VCOS_ENOMEM;
       goto fail_mem;
    }
    rc = read(fd, default_font.mem, len);
    if (rc != len)
    {
       GX_ERROR("Could not read font %s", fname);
       ret = VCOS_EINVAL;
       goto fail_rd;
    }
    default_font.len = len;
    close(fd);
    GX_TRACE("Opened font file '%s'", fname);
    inited = 1;
    return VCOS_SUCCESS;
 fail_rd:
    vcos_free(default_font.mem);
 fail_mem:
    if (fd >= 0) close(fd);
 fail_open:
    vgft_term();
 fail_init:
    return ret;
 }
gx_priv_font_term()
void gx_priv_font_term (void)
add documentation
Definition at line 144 of file font.c.
References gx_font_cache_flush(), vcos_free(), and vgft_term().
 {
    gx_font_cache_flush();
    vgft_term();
    vcos_free(default_font.mem);
 }
gx_priv_init()
void gx_priv_init (void)
add documentation
Definition at line 1227 of file graphics.c.
References gx_priv_state_t::lock, NULL, and vcos_mutex_create().
 {
    vcos_mutex_create(&gx.lock,NULL);
 }
gx_priv_read_bmp()
int gx_priv_read_bmp (const char * file_name, uint32_t * width, uint32_t * height, uint32_t * pitch_bytes, GRAPHICS_RESOURCE_TYPE_T * restype, VGImageFormat * vg_format, uint32_t * flags, uint32_t * image_data_size, void ** pimage_data)
Read a bitmap (.BMP) image from the given file.
Parameters
filename filename (must not be NULL).
width holds the width of the image upon return.
height holds the height of the image upon return.
pitch_bytes holds the pitch of the image data (in bytes) upon return.
restype holds the type of the image upon return.
vg_format holds the OpenVG image format upon return.
flags holds flags describing image properties upon return.
image_data_size holds size of the image data upon return.
pimage_data holds the image data buffer upon return (must not be NULL), the caller is responsible for releasing the buffer afterwards.
Returns
0 if success, non-zero otherwise (in which case the output parameters may be invalid).
gx_priv_read_tga()
int gx_priv_read_tga (const char * file_name, uint32_t * width, uint32_t * height, uint32_t * pitch_bytes, GRAPHICS_RESOURCE_TYPE_T * restype, VGImageFormat * vg_format, uint32_t * flags, uint32_t * image_data_size, void ** pimage_data)
Read a Targa (.TGA) image from the given file.
Parameters
filename filename (must not be NULL).
width holds the width of the image upon return.
height holds the height of the image upon return.
pitch_bytes holds the pitch of the image data (in bytes) upon return.
restype holds the type of the image upon return.
vg_format holds the OpenVG image format upon return.
flags holds flags describing image properties upon return.
image_data_size holds size of the image data upon return.
pimage_data holds the image data buffer upon return (must not be NULL), the caller is responsible for releasing the memory afterwards.
Returns
0 if success, non-zero otherwise (in which case the output parameters. may be invalid).
gx_priv_render_text()
VCOS_STATUS_T gx_priv_render_text (GX_DISPLAY_T * disp, GRAPHICS_RESOURCE_HANDLE res, int32_t x, int32_t y, uint32_t width, uint32_t height, uint32_t fg_colour, uint32_t bg_colour, const char * text, uint32_t text_length, uint32_t text_size)
Render text into a surface
Parameters
disp Handle to display.
res Handle to surface.
x x-offset
y y-offset
width bounding rectangle width
height bounding rectangle height
fg_colour foreground color
bg_colour background color
text text to render
text_length length of text
text_size size of text
Render text.
FIXME: Not at all optimal - re-renders each time. FIXME: Not UTF-8 aware FIXME: better caching
Definition at line 157 of file font.c.
References gx_font_cache_entry_t::font, status, vcos_demand, and VCOS_SUCCESS.
Referenced by graphics_resource_render_text_ext().
 {
    VGfloat vg_colour[4];
    VGFT_FONT_T *font;
    VGPaint fg;
    GX_CLIENT_STATE_T save;
    VCOS_STATUS_T status = VCOS_SUCCESS;
    int clip = 1;
    vcos_demand(inited); // has gx_font_init() been called?
    gx_priv_save(&save, res);
    if (width == GRAPHICS_RESOURCE_WIDTH &&
        height == GRAPHICS_RESOURCE_HEIGHT)
    {
       clip = 0;
    }
    width = (width == GRAPHICS_RESOURCE_WIDTH) ? res->width : width;
    height = (height == GRAPHICS_RESOURCE_HEIGHT) ? res->height : height;
    font = find_font(text, text_size);
    if (!font)
    {
       status = VCOS_ENOMEM;
       goto finish;
    }
    // setup the clipping rectangle
    if (clip)
    {
       VGint coords[] = {x,y,width,height};
       vgSeti(VG_SCISSORING, VG_TRUE);
       vgSetiv(VG_SCISSOR_RECTS, 4, coords);
    }
    // setup the background colour if needed
    if (bg_colour != GRAPHICS_TRANSPARENT_COLOUR)
    {
       int err;
       VGfloat rendered_w, rendered_h;
       VGfloat vg_bg_colour[4];
       // setup the background colour...
       gx_priv_colour_to_paint(bg_colour, vg_bg_colour);
       vgSetfv(VG_CLEAR_COLOR, 4, vg_bg_colour);
       // fill in a rectangle...
       vgft_get_text_extents(font, text, text_length, (VGfloat)x, (VGfloat)y, &rendered_w, &rendered_h);
       if ( ( 0 < (VGint)rendered_w ) && ( 0 < (VGint)rendered_h ) )
       {
          // Have to compensate for the messed up y position of multiline text.
          VGfloat offset = vgft_first_line_y_offset(font);
          int32_t bottom = y + offset - rendered_h;
          vgClear(x, bottom, (VGint)rendered_w, (VGint)rendered_h);
          err = vgGetError();
          if (err)
          {
             GX_LOG("Error %d clearing bg text %d %d %g %g",
                    err, x, y, rendered_w, rendered_h);
             vcos_assert(0);
          } // if
       } // if
    } // if
    // setup the foreground colour
    fg = vgCreatePaint();
    if (!fg)
    {
       status = VCOS_ENOMEM;
       goto finish;
    }
    // draw the foreground text
    vgSetParameteri(fg, VG_PAINT_TYPE, VG_PAINT_TYPE_COLOR);
    gx_priv_colour_to_paint(fg_colour, vg_colour);
    vgSetParameterfv(fg, VG_PAINT_COLOR, 4, vg_colour);
    vgSetPaint(fg, VG_FILL_PATH);
    vgft_font_draw(font, (VGfloat)x, (VGfloat)y, text, text_length, VG_FILL_PATH);
    vgDestroyPaint(fg);
    vcos_assert(vgGetError() == 0);
    vgSeti(VG_SCISSORING, VG_FALSE);
 finish:
    gx_priv_restore(&save);
    return status;
 }
gx_priv_resource_fill()
VCOS_STATUS_T gx_priv_resource_fill (GRAPHICS_RESOURCE_HANDLE res, uint32_t x, uint32_t y, uint32_t width, uint32_t height, uint32_t fill_colour)
Fill an area of a surface with a single colour.
Parameters
res Handle to surface.
x x-offset of area to fill
y y-offset of area to fill
width width of area to fill
height height of area to fill
fill_colour fill colour
Fill an area of a surface with a fixed colour.
Definition at line 652 of file graphics.c.
References GX_LOG, gx_priv_colour_to_paint(), vcos_assert, VCOS_SUCCESS, VG_CLEAR_COLOR, VG_FALSE, VG_SCISSORING, vgClear(), vgGetError(), vgSetfv(), and vgSeti().
Referenced by graphics_resource_fill().
 {
    VGfloat vg_clear_colour[4];
    gx_priv_colour_to_paint(fill_colour, vg_clear_colour);
    vgSeti(VG_SCISSORING, VG_FALSE);
    vgSetfv(VG_CLEAR_COLOR, 4, vg_clear_colour);
    vgClear(x, y, width, height);
    int err = vgGetError();
    if (err)
    {
       GX_LOG("vg error %x filling area", err);
       vcos_assert(0);
    }
    return VCOS_SUCCESS;
 }
gx_priv_restore()
void gx_priv_restore (GX_CLIENT_STATE_T * state)
Restore current EGL client state.
Parameters
state the EGL client state to restore.
Definition at line 255 of file graphics.c.
Referenced by graphics_bitblt(), graphics_delete_resource(), graphics_resource_fill(), graphics_update_displayed_resource(), gx_create_gradient(), gx_destroy_paint(), gx_fill_gradient(), gx_get_pixels(), gx_get_pixels_in_raster_order(), gx_render_arrowhead(), and gx_unbind_vg().
 {
    EGLBoolean egl_result;
    GX_TRACE("gx_priv_restore: eglMakeCurrent: %s, res %x draw_surface %x, surface %x, cxt %x", vcos_thread_get_name(vcos_thread_current()),
       (uint32_t)state->res, (uint32_t)state->draw_surface, (uint32_t)state->read_surface, (uint32_t)state->context);
    // disconnect our thread from this context, so we other threads can use it via
    // this API
    egl_result = eglMakeCurrent(display.disp, EGL_NO_SURFACE, EGL_NO_SURFACE, EGL_NO_CONTEXT);
    vcos_assert(egl_result);
    // now return to the client's API binding
    egl_result = eglBindAPI(state->api);
    vcos_assert(egl_result);
    egl_result = eglMakeCurrent(display.disp, state->draw_surface, state->read_surface, state->context);
    vcos_assert(egl_result);
    if (state->res) state->res->context_bound = 0;
    vcos_mutex_unlock(&lock);
 }
gx_priv_save()
void gx_priv_save (GX_CLIENT_STATE_T * state, GRAPHICS_RESOURCE_HANDLE res)
Save current EGL client state.
Parameters
state upon return, holds the saved EGL client state.
res handle to the surface the EGL client state belongs to (may be NULL).
Definition at line 222 of file graphics.c.
Referenced by graphics_bitblt(), graphics_delete_resource(), graphics_resource_fill(), graphics_resource_text_dimensions_ext(), graphics_update_displayed_resource(), gx_bind_vg(), gx_create_gradient(), gx_destroy_paint(), gx_fill_gradient(), gx_get_pixels(), gx_get_pixels_in_raster_order(), gx_graphics_init(), and gx_render_arrowhead().
 {
    EGLBoolean egl_result;
    vcos_assert(res == NULL || (res->magic == RES_MAGIC));
    vcos_assert(res == NULL || !res->context_bound);
    state->context      = eglGetCurrentContext();
    state->api          = eglQueryAPI();
    state->read_surface = eglGetCurrentSurface(EGL_READ);
    state->draw_surface = eglGetCurrentSurface(EGL_DRAW);
    state->res = res;
    vcos_assert(state->api); // should never be anything other than VG or GL
    vcos_mutex_lock(&lock);
    egl_result = eglBindAPI(EGL_OPENVG_API);
    vcos_assert(egl_result);
    if (res)
    {
       GX_TRACE("gx_priv_save: eglMakeCurrent: %s, res %x surface %x, cxt %x", vcos_thread_get_name(vcos_thread_current()),
          (uint32_t)res, (uint32_t)res->surface, (uint32_t)res->context);
       egl_result = eglMakeCurrent(display.disp, res->surface,
                                   res->surface, res->context);
       vcos_assert(egl_result);
       res->context_bound = 1;
    }
 }
Variable Documentation
gx_log_cat
VCOS_LOG_CAT_T gx_log_cat
Definition at line 283 of file graphics.c.