VideoCore Library: interface/vmcs_host/vcilcs.h File Reference
vcilcs.h File Reference
#include "interface/vmcs_host/khronos/IL/OMX_Component.h"
#include "interface/vmcs_host/vc_ilcs_defs.h"
Classes
struct ILCS_CONFIG_T
Macros
#define ILCS_ALIGN 16
#define ILCS_ROUND_UP(x) ((((unsigned long)(x))+ILCS_ALIGN-1) & ~(ILCS_ALIGN-1))
#define ILCS_ROUND_DOWN(x) (((unsigned long)(x)) & ~(ILCS_ALIGN-1))
#define ILCS_ALIGNED(x) (((unsigned long)(x) & (ILCS_ALIGN-1)) == 0)
Typedefs
typedef struct ILCS_SERVICE_T ILCS_SERVICE_T
typedef struct ILCS_COMMON_T ILCS_COMMON_T
typedef void(* IL_FN_T) (ILCS_COMMON_T *st, void *call, int clen, void *resp, int *rlen)
Functions
VCHPRE_ ILCS_SERVICE_T VCHPOST_ * ilcs_init (VCHIQ_STATE_T *state, void **connection, ILCS_CONFIG_T *config, int use_memmgr)
VCHPRE_ void VCHPOST_ ilcs_deinit (ILCS_SERVICE_T *ilcs)
VCHPRE_ int VCHPOST_ ilcs_thread_current (void *param)
VCHPRE_ ILCS_COMMON_T * ilcs_get_common (ILCS_SERVICE_T *ilcs)
VCHPRE_ int VCHPOST_ ilcs_execute_function (ILCS_SERVICE_T *ilcs, IL_FUNCTION_T func, void *data, int len, void *resp, int *rlen)
VCHPRE_ OMX_ERRORTYPE VCHPOST_ ilcs_pass_buffer (ILCS_SERVICE_T *ilcs, IL_FUNCTION_T func, void *reference, OMX_BUFFERHEADERTYPE *pBuffer)
VCHPRE_ OMX_BUFFERHEADERTYPE *VCHPOST_ ilcs_receive_buffer (ILCS_SERVICE_T *ilcs, void *call, int clen, OMX_COMPONENTTYPE **pComp)
Macro Definition Documentation
ILCS_ALIGN
#define ILCS_ALIGN 16
Definition at line 75 of file vcilcs.h.
ILCS_ALIGNED
#define ILCS_ALIGNED (x) (((unsigned long)(x) & (ILCS_ALIGN-1)) == 0)
Definition at line 79 of file vcilcs.h.
ILCS_ROUND_DOWN
#define ILCS_ROUND_DOWN (x) (((unsigned long)(x)) & ~(ILCS_ALIGN-1))
Definition at line 78 of file vcilcs.h.
Referenced by ilcs_pass_buffer().
ILCS_ROUND_UP
#define ILCS_ROUND_UP (x) ((((unsigned long)(x))+ILCS_ALIGN-1) & ~(ILCS_ALIGN-1))
Definition at line 77 of file vcilcs.h.
Referenced by ilcs_pass_buffer().
Typedef Documentation
IL_FN_T
typedef void(* IL_FN_T) (ILCS_COMMON_T *st, void *call, int clen, void *resp, int *rlen)
Definition at line 42 of file vcilcs.h.
ILCS_COMMON_T
typedef struct ILCS_COMMON_T ILCS_COMMON_T
Definition at line 40 of file vcilcs.h.
ILCS_SERVICE_T
typedef struct ILCS_SERVICE_T ILCS_SERVICE_T
Definition at line 37 of file vcilcs.h.
Function Documentation
ilcs_deinit()
VCHPRE_ void VCHPOST_ ilcs_deinit (ILCS_SERVICE_T * ilcs)
Definition at line 300 of file vcilcs.c.
References DEINIT_CALLED, and ILCS_SERVICE_T::kill_service.
 {
    void *data;
    st->kill_service = DEINIT_CALLED;
    ilcs_send_quit(st);
    vcos_thread_join(&st->thread, &data);
    vcos_free(st);
 }
ilcs_execute_function()
VCHPRE_ int VCHPOST_ ilcs_execute_function (ILCS_SERVICE_T * ilcs, IL_FUNCTION_T func, void * data, int len, void * resp, int * rlen)
Definition at line 831 of file vcilcs.c.
Referenced by vcil_out_component_name_enum(), vcil_out_create_component(), and vcil_out_get_debug_information().
 {
    return ilcs_execute_function_ex(st, func, data, len, NULL, 0, VCHI_MEM_HANDLE_INVALID, 0, 0, resp, rlen);
 }
ilcs_get_common()
VCHPRE_ ILCS_COMMON_T* ilcs_get_common (ILCS_SERVICE_T * ilcs)
Definition at line 324 of file vcilcs.c.
References ILCS_SERVICE_T::ilcs_common.
Referenced by OMX_ComponentNameEnum(), OMX_GetDebugInformation(), and OMX_GetHandle().
 {
    return st->ilcs_common;
 }
ilcs_init()
VCHPRE_ ILCS_SERVICE_T VCHPOST_* ilcs_init (VCHIQ_STATE_T * state, void ** connection, ILCS_CONFIG_T * config, int use_memmgr)
Definition at line 138 of file vcilcs.c.
References ILCS_SERVICE_T::vchiq, and vcos_malloc().
 {
    int32_t i;
    VCOS_THREAD_ATTR_T thread_attrs;
    ILCS_SERVICE_T *st;
    VCHIQ_SERVICE_PARAMS_T params;
    st = vcos_malloc(sizeof(ILCS_SERVICE_T), "ILCS State");
    if(!st)
       goto fail_alloc;
    memset(st, 0, sizeof(ILCS_SERVICE_T));
    st->vchiq = state;
    st->fourcc = VCHIQ_MAKE_FOURCC('I', 'L', 'C', 'S');
    st->config = *config;
    // setting this to true implies we have relocatable handles as
    // buffer pointers, otherwise we interpret them to be real pointers
    st->use_memmgr = use_memmgr;
    // create semaphore for protecting wait/xid structures
    if(vcos_mutex_create(&st->wait_mtx, "ILCS") != VCOS_SUCCESS)
       goto fail_all;
    // create smaphore for control+bulk protection
    if(vcos_semaphore_create(&st->send_sem, "ILCS", 1) != VCOS_SUCCESS)
       goto fail_send_sem;
    // create event group for signalling when a waiting slot becomes free
    if(vcos_event_create(&st->wait_event, "ILCS") != VCOS_SUCCESS)
       goto fail_wait_event;
    for(i=0; i<ILCS_MAX_WAITING; i++)
       if(vcos_event_create(&st->wait[i].event, "ILCS") != VCOS_SUCCESS)
       {
          while(--i >= 0)
             vcos_event_delete(&st->wait[i].event);
          goto fail_wait_events;
       }
    if(vcos_timer_create(&st->timer, "ILCS", ilcs_timer, st) != VCOS_SUCCESS)
       goto fail_timer;
    // create the queue of incoming messages
    if(!vchiu_queue_init(&st->queue, 256))
       goto fail_queue;
    // create the bulk receive event
    if(vcos_event_create(&st->bulk_rx, "ILCS") != VCOS_SUCCESS)
       goto fail_bulk_event;
    // create an 'ILCS' service
 #ifdef USE_VCHIQ_ARM
    /* VCHIQ_ARM distinguishes between servers and clients. Use use_memmgr
       parameter to detect usage by the client.
     */
    memset(&params,0,sizeof(params));
    params.fourcc = st->fourcc;
    params.callback = ilcs_callback;
    params.userdata = st;
    params.version = VC_ILCS_VERSION;
    params.version_min = VC_ILCS_VERSION;
    if (use_memmgr == 0)
    {
       // Host side, which will connect to a listening VideoCore side
       if (vchiq_open_service(st->vchiq, &params, &st->service) != VCHIQ_SUCCESS)
          goto fail_service;
    }
    else
    {
       // VideoCore side, a listening service not connected
       if (vchiq_add_service(st->vchiq, &params, &st->service) != VCHIQ_SUCCESS)
          goto fail_service;
       // On VC shutdown we defer calling vchiq_remove_service until after the callback has
       // returned, so we require not to have the autoclose behaviour
       vchiq_set_service_option(st->service, VCHIQ_SERVICE_OPTION_AUTOCLOSE, 0);
    }
 #else
 #ifdef USE_VCHI
    if(!vchiq_wrapper_add_service(st->vchiq, connection, st->fourcc, ilcs_callback, st))
       goto fail_service;
 #else
    if(!vchiq_add_service(st->vchiq, st->fourcc, ilcs_callback, st))
       goto fail_service;
 #endif
 #endif
    if((st->ilcs_common = st->config.ilcs_common_init(st)) == NULL)
       goto fail_ilcs_common;
    vcos_thread_attr_init(&thread_attrs);
    vcos_thread_attr_setstacksize(&thread_attrs, 4096);
    snprintf(st->name, sizeof(st->name), "ILCS_%s", use_memmgr ? "VC" : "HOST");
    if(vcos_thread_create(&st->thread, st->name, &thread_attrs, ilcs_task, st) != VCOS_SUCCESS)
       goto fail_thread;
    return st;
  fail_thread:
    st->config.ilcs_common_deinit(st->ilcs_common);
  fail_ilcs_common:
 #ifdef USE_VCHIQ_ARM
    vchiq_remove_service(st->service);
 #endif
  fail_service:
    vcos_event_delete(&st->bulk_rx);
  fail_bulk_event:
    vchiu_queue_delete(&st->queue);
  fail_queue:
    vcos_timer_delete(&st->timer);
  fail_timer:
    for(i=0; i<ILCS_MAX_WAITING; i++)
       vcos_event_delete(&st->wait[i].event);
  fail_wait_events:
    vcos_event_delete(&st->wait_event);
  fail_wait_event:
    vcos_semaphore_delete(&st->send_sem);
  fail_send_sem:
    vcos_mutex_delete(&st->wait_mtx);
  fail_all:
    vcos_free(st);
  fail_alloc:
    return NULL;
 }
ilcs_pass_buffer()
VCHPRE_ OMX_ERRORTYPE VCHPOST_ ilcs_pass_buffer (ILCS_SERVICE_T * ilcs, IL_FUNCTION_T func, void * reference, OMX_BUFFERHEADERTYPE * pBuffer)
Definition at line 840 of file vcilcs.c.
References IL_PASS_BUFFER_EXECUTE_T::bufferHeader, IL_PASS_BUFFER_EXECUTE_T::bufferLen, ILCS_SERVICE_T::config, IL_BUFFER_BULK_T::header, IL_BUFFER_BULK_T::headerlen, IL_BUFFER_BULK, IL_BUFFER_INLINE, IL_BUFFER_NONE, IL_EMPTY_THIS_BUFFER, IL_FILL_THIS_BUFFER, ILCS_CONFIG_T::ilcs_mem_lock, ILCS_CONFIG_T::ilcs_mem_unlock, ILCS_ROUND_DOWN, ILCS_ROUND_UP, ILCS_SERVICE_T::kill_service, IL_PASS_BUFFER_EXECUTE_T::method, OMX_BUFFERHEADERTYPE::nAllocLen, OMX_BUFFERHEADERTYPE::nFilledLen, OMX_BUFFERHEADERTYPE::nFlags, OMX_BUFFERHEADERTYPE::nOffset, NULL, OMX_BUFFERFLAG_EXTRADATA, OMX_ErrorBadParameter, OMX_ErrorHardware, OMX_ErrorIncorrectStateOperation, OMX_ExtraDataNone, OMX_FALSE, OMX_TRUE, OMX_BUFFERHEADERTYPE::pBuffer, OMX_BUFFERHEADERTYPE::pInputPortPrivate, OMX_BUFFERHEADERTYPE::pOutputPortPrivate, IL_PASS_BUFFER_EXECUTE_T::reference, IL_BUFFER_BULK_T::trailer, IL_BUFFER_BULK_T::trailerlen, ILCS_SERVICE_T::use_memmgr, VC_ILCS_MAX_INLINE, and VCHI_MEM_HANDLE_INVALID.
 {
    IL_PASS_BUFFER_EXECUTE_T exe;
    IL_BUFFER_BULK_T fixup;
    IL_RESPONSE_HEADER_T resp;
    VCHI_MEM_HANDLE_T mem_handle = VCHI_MEM_HANDLE_INVALID;
    void *ret = NULL, *data2 = NULL, *bulk_offset = NULL;
    int len2 = 0, bulk_len = 0;
    OMX_U8 *ptr = NULL;
    int rlen = sizeof(resp);
    if(st->kill_service)
       return OMX_ErrorHardware;
    if((func == IL_EMPTY_THIS_BUFFER && pBuffer->pInputPortPrivate == NULL) ||
       (func == IL_FILL_THIS_BUFFER && pBuffer->pOutputPortPrivate == NULL))
    {
       // return this to pass conformance
       // the actual error is using a buffer that hasn't be registered with usebuffer/allocatebuffer
       return OMX_ErrorIncorrectStateOperation;
    }
    if((pBuffer->nFlags & OMX_BUFFERFLAG_EXTRADATA) || pBuffer->nFilledLen)
       ptr = st->config.ilcs_mem_lock(pBuffer) + pBuffer->nOffset;
    exe.reference = reference;
    memcpy(&exe.bufferHeader, pBuffer, sizeof(OMX_BUFFERHEADERTYPE));
    exe.bufferLen = pBuffer->nFilledLen;
    if(pBuffer->nFlags & OMX_BUFFERFLAG_EXTRADATA)
    {
       // walk down extra-data's appended to the buffer data to work out their length
       OMX_U8 *end = ptr + pBuffer->nAllocLen - pBuffer->nOffset;
       OMX_OTHER_EXTRADATATYPE *extra =
          (OMX_OTHER_EXTRADATATYPE *) (((uint32_t) (ptr + pBuffer->nFilledLen + 3)) & ~3);
       OMX_BOOL b_corrupt = OMX_FALSE;
       OMX_EXTRADATATYPE extra_type;
       do
       {
          // sanity check the extra data before doing anything with it
          if(((uint8_t *)extra) + sizeof(OMX_OTHER_EXTRADATATYPE) > end ||
             ((uint8_t *)extra) + extra->nSize > end ||
             extra->nSize < sizeof(OMX_OTHER_EXTRADATATYPE) ||
             (extra->nSize & 3))
          {
             // shouldn't happen. probably a problem with the component
             b_corrupt = OMX_TRUE;
             break;
          }
          extra_type = extra->eType;
          extra = (OMX_OTHER_EXTRADATATYPE *) (((uint8_t *) extra) + extra->nSize);
       }
       while(extra_type != OMX_ExtraDataNone);
       // if corrupt then drop the extra data since we can't do anything with it
       if(b_corrupt)
          pBuffer->nFlags &= ~OMX_BUFFERFLAG_EXTRADATA;
       else
          exe.bufferLen = ((uint8_t *) extra) - ptr;
    }
    // check that the buffer fits in the allocated region
    if(exe.bufferLen + pBuffer->nOffset > pBuffer->nAllocLen)
    {
       if(ptr != NULL)
          st->config.ilcs_mem_unlock(pBuffer);
       return OMX_ErrorBadParameter;
    }
    if(exe.bufferLen)
    {
       if(exe.bufferLen + sizeof(IL_PASS_BUFFER_EXECUTE_T) <= VC_ILCS_MAX_INLINE)
       {
          // Pass the data in the message itself, and avoid doing a bulk transfer at all...
          exe.method = IL_BUFFER_INLINE;
          data2 = ptr;
          len2 = exe.bufferLen;
       }
       else
       {
          // Pass the misaligned area at the start at end inline within the
          // message, and the bulk of the message using a separate bulk
          // transfer
          const uint8_t *start = ptr;
          const uint8_t *end   = start + exe.bufferLen;
          const uint8_t *round_start = (const OMX_U8*)ILCS_ROUND_UP(start);
          const uint8_t *round_end   = (const OMX_U8*)ILCS_ROUND_DOWN(end);
          exe.method = IL_BUFFER_BULK;
          if(st->use_memmgr)
          {
             bulk_offset = (void *) (round_start-(ptr-pBuffer->nOffset));
             mem_handle = (VCHI_MEM_HANDLE_T) pBuffer->pBuffer;
          }
          else
             bulk_offset = (void *) round_start;
          bulk_len = round_end-round_start;
          if((fixup.headerlen = round_start - start) > 0)
             memcpy(fixup.header, start, fixup.headerlen);
          if((fixup.trailerlen = end - round_end) > 0)
             memcpy(fixup.trailer, round_end, fixup.trailerlen);
          data2 = &fixup;
          len2 = sizeof(fixup);
       }
    }
    else
    {
       exe.method = IL_BUFFER_NONE;
    }
    // when used for callbacks to client, no need for response
    // so only set ret when use component to component
    if(func == IL_EMPTY_THIS_BUFFER || func == IL_FILL_THIS_BUFFER)
       ret = &resp;
    if(ilcs_execute_function_ex(st, func, &exe, sizeof(IL_PASS_BUFFER_EXECUTE_T),
                                data2, len2, mem_handle, bulk_offset, bulk_len, ret, &rlen) < 0 || rlen != sizeof(resp))
    {
       ret = &resp;
       resp.err = OMX_ErrorHardware;
    }
    if(ptr != NULL)
       st->config.ilcs_mem_unlock(pBuffer);
    return ret ? resp.err : OMX_ErrorNone;
 }
ilcs_receive_buffer()
VCHPRE_ OMX_BUFFERHEADERTYPE* VCHPOST_ ilcs_receive_buffer (ILCS_SERVICE_T * ilcs, void * call, int clen, OMX_COMPONENTTYPE ** pComp)
Definition at line 983 of file vcilcs.c.
References IL_BUFFER_INLINE_T::buffer, IL_PASS_BUFFER_EXECUTE_T::bufferHeader, IL_PASS_BUFFER_EXECUTE_T::bufferLen, ILCS_SERVICE_T::bulk_rx, ILCS_SERVICE_T::config, ILCS_SERVICE_T::fourcc, IL_BUFFER_BULK_T::header, IL_BUFFER_BULK_T::headerlen, IL_BUFFER_BULK, IL_BUFFER_INLINE, IL_BUFFER_NONE, ILCS_CONFIG_T::ilcs_mem_lock, ILCS_CONFIG_T::ilcs_mem_unlock, ILCS_SERVICE_T::kill_service, IL_PASS_BUFFER_EXECUTE_T::method, OMX_BUFFERHEADERTYPE::nFilledLen, OMX_BUFFERHEADERTYPE::nFlags, OMX_BUFFERHEADERTYPE::nOffset, NULL, OMX_BUFFERHEADERTYPE::pAppPrivate, OMX_BUFFERHEADERTYPE::pBuffer, OMX_BUFFERHEADERTYPE::pInputPortPrivate, OMX_BUFFERHEADERTYPE::pOutputPortPrivate, OMX_BUFFERHEADERTYPE::pPlatformPrivate, IL_PASS_BUFFER_EXECUTE_T::reference, IL_BUFFER_BULK_T::trailer, IL_BUFFER_BULK_T::trailerlen, ILCS_SERVICE_T::use_memmgr, VCHI_MEM_HANDLE_INVALID, ILCS_SERVICE_T::vchiq, vchiq_queue_bulk_receive(), vchiq_queue_bulk_receive_handle(), vcos_assert, and vcos_event_wait().
Referenced by vcil_in_empty_this_buffer(), and vcil_out_fill_buffer_done().
 {
    IL_PASS_BUFFER_EXECUTE_T *exe = call;
    OMX_BUFFERHEADERTYPE *pHeader = exe->bufferHeader.pInputPortPrivate;
    OMX_U8 *dest, *pBuffer = pHeader->pBuffer;
    OMX_PTR *pAppPrivate = pHeader->pAppPrivate;
    OMX_PTR *pPlatformPrivate = pHeader->pPlatformPrivate;
    OMX_PTR *pInputPortPrivate = pHeader->pInputPortPrivate;
    OMX_PTR *pOutputPortPrivate = pHeader->pOutputPortPrivate;
    if(st->kill_service)
       return NULL;
    vcos_assert(pHeader);
    memcpy(pHeader, &exe->bufferHeader, sizeof(OMX_BUFFERHEADERTYPE));
    *pComp = exe->reference;
    pHeader->pBuffer = pBuffer;
    pHeader->pAppPrivate = pAppPrivate;
    pHeader->pPlatformPrivate = pPlatformPrivate;
    pHeader->pInputPortPrivate = pInputPortPrivate;
    pHeader->pOutputPortPrivate = pOutputPortPrivate;
    dest = st->config.ilcs_mem_lock(pHeader) + pHeader->nOffset;
    if(exe->method == IL_BUFFER_BULK)
    {
       IL_BUFFER_BULK_T *fixup = (IL_BUFFER_BULK_T *) (exe+1);
       VCHI_MEM_HANDLE_T mem_handle = VCHI_MEM_HANDLE_INVALID;
       void *bulk_offset;
       int32_t bulk_len = exe->bufferLen - fixup->headerlen - fixup->trailerlen;
       vcos_assert(clen == sizeof(IL_PASS_BUFFER_EXECUTE_T) + sizeof(IL_BUFFER_BULK_T));
       if(st->use_memmgr)
       {
          mem_handle = (VCHI_MEM_HANDLE_T) pBuffer;
          bulk_offset = (void*)(pHeader->nOffset + fixup->headerlen);
       }
       else
          bulk_offset = dest + fixup->headerlen;
 #ifdef USE_VCHIQ_ARM
       vchiq_queue_bulk_receive_handle(st->service, mem_handle, bulk_offset, bulk_len, NULL);
 #else
       vchiq_queue_bulk_receive(st->vchiq, st->fourcc, mem_handle, bulk_offset, bulk_len, NULL);
 #endif
       vcos_event_wait(&st->bulk_rx);
       if(st->kill_service)
       {
          // the bulk receive was aborted, and we're about the quit, however this function
          // being called means the buffer header control message made it across, so we
          // need to think that this buffer is on VideoCore.  So pretend this is all okay,
          // but zero the buffer contents so we don't process bad data
          pHeader->nFilledLen = 0;
          pHeader->nFlags = 0;
       }
       else if(fixup->headerlen || fixup->trailerlen)
       {
          uint8_t *end = dest + exe->bufferLen;
          if(fixup->headerlen)
             memcpy(dest, fixup->header, fixup->headerlen);
          if(fixup->trailerlen)
             memcpy(end-fixup->trailerlen, fixup->trailer, fixup->trailerlen);
       }
    }
    else if(exe->method == IL_BUFFER_INLINE)
    {
       IL_BUFFER_INLINE_T *buffer = (IL_BUFFER_INLINE_T *) (exe+1);
       vcos_assert(clen == sizeof(IL_PASS_BUFFER_EXECUTE_T) + exe->bufferLen);
       memcpy(dest, buffer->buffer, exe->bufferLen);
    }
    else if(exe->method == IL_BUFFER_NONE)
    {
       vcos_assert(clen == sizeof(IL_PASS_BUFFER_EXECUTE_T));
    }
    else
    {
       vcos_assert(0);
    }
    st->config.ilcs_mem_unlock(pHeader);
    return pHeader;
 }
ilcs_thread_current()
VCHPRE_ int VCHPOST_ ilcs_thread_current (void * param)
Definition at line 333 of file vcilcs.c.
References ILCS_SERVICE_T::thread, and vcos_thread_current().
 {
    ILCS_SERVICE_T *st = (ILCS_SERVICE_T *) param;
    return vcos_thread_current() == &st->thread;
 }