// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/models2.proto

#include "proto/models2.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace FCWS {
class ParaDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Para>
      _instance;
} _Para_default_instance_;
class PositionDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Position>
      _instance;
} _Position_default_instance_;
class Vehicle_ModelDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Vehicle_Model>
      _instance;
} _Vehicle_Model_default_instance_;
class ModelsDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Models>
      _instance;
} _Models_default_instance_;
}  // namespace FCWS
namespace protobuf_proto_2fmodels2_2eproto {
void InitDefaultsParaImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::FCWS::_Para_default_instance_;
    new (ptr) ::FCWS::Para();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::FCWS::Para::InitAsDefaultInstance();
}

void InitDefaultsPara() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsParaImpl);
}

void InitDefaultsPositionImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_proto_2fmodels2_2eproto::InitDefaultsPara();
  {
    void* ptr = &::FCWS::_Position_default_instance_;
    new (ptr) ::FCWS::Position();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::FCWS::Position::InitAsDefaultInstance();
}

void InitDefaultsPosition() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsPositionImpl);
}

void InitDefaultsVehicle_ModelImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_proto_2fmodels2_2eproto::InitDefaultsPosition();
  {
    void* ptr = &::FCWS::_Vehicle_Model_default_instance_;
    new (ptr) ::FCWS::Vehicle_Model();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::FCWS::Vehicle_Model::InitAsDefaultInstance();
}

void InitDefaultsVehicle_Model() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsVehicle_ModelImpl);
}

void InitDefaultsModelsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_proto_2fmodels2_2eproto::InitDefaultsVehicle_Model();
  {
    void* ptr = &::FCWS::_Models_default_instance_;
    new (ptr) ::FCWS::Models();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::FCWS::Models::InitAsDefaultInstance();
}

void InitDefaultsModels() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsModelsImpl);
}

::google::protobuf::Metadata file_level_metadata[4];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[3];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::FCWS::Para, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::FCWS::Para, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::FCWS::Para, para_type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::FCWS::Para, rows_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::FCWS::Para, cols_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::FCWS::Para, data_),
  0,
  1,
  2,
  ~0u,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::FCWS::Position, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::FCWS::Position, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::FCWS::Position, pos_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::FCWS::Position, para_),
  0,
  ~0u,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::FCWS::Vehicle_Model, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::FCWS::Vehicle_Model, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::FCWS::Vehicle_Model, type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::FCWS::Vehicle_Model, position_),
  0,
  ~0u,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::FCWS::Models, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::FCWS::Models, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::FCWS::Models, vm_),
  ~0u,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 9, sizeof(::FCWS::Para)},
  { 13, 20, sizeof(::FCWS::Position)},
  { 22, 29, sizeof(::FCWS::Vehicle_Model)},
  { 31, 37, sizeof(::FCWS::Models)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::FCWS::_Para_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::FCWS::_Position_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::FCWS::_Vehicle_Model_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::FCWS::_Models_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "proto/models2.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 4);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\023proto/models2.proto\022\004FCWS\"\202\001\n\004Para\022(\n\t"
      "para_type\030\001 \002(\0162\017.FCWS.Para.Type:\004None\022\014"
      "\n\004rows\030\002 \002(\005\022\014\n\004cols\030\003 \002(\005\022\020\n\004data\030\004 \003(\001"
      "B\002\020\001\"\"\n\004Type\022\010\n\004None\020\000\022\007\n\003PCA\020\001\022\007\n\003ICA\020\002"
      "\"r\n\010Position\022&\n\003pos\030\001 \002(\0162\023.FCWS.Positio"
      "n.Type:\004LEFT\022\030\n\004para\030\002 \003(\0132\n.FCWS.Para\"$"
      "\n\004Type\022\010\n\004LEFT\020\000\022\t\n\005RIGHT\020\001\022\007\n\003TOP\020\002\"\310\001\n"
      "\rVehicle_Model\0222\n\004type\030\001 \002(\0162\030.FCWS.Vehi"
      "cle_Model.Type:\nNotVehicle\022 \n\010position\030\002"
      " \003(\0132\016.FCWS.Position\"a\n\004Type\022\027\n\nNotVehic"
      "le\020\377\377\377\377\377\377\377\377\377\001\022\013\n\007Compact\020\000\022\013\n\007Midsize\020\001\022"
      "\t\n\005Large\020\002\022\007\n\003SUV\020\003\022\007\n\003BUS\020\004\022\t\n\005TRUCK\020\005\""
      ")\n\006Models\022\037\n\002vm\030\001 \003(\0132\023.FCWS.Vehicle_Mod"
      "el"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 522);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "proto/models2.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_proto_2fmodels2_2eproto
namespace FCWS {
const ::google::protobuf::EnumDescriptor* Para_Type_descriptor() {
  protobuf_proto_2fmodels2_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_proto_2fmodels2_2eproto::file_level_enum_descriptors[0];
}
bool Para_Type_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const Para_Type Para::None;
const Para_Type Para::PCA;
const Para_Type Para::ICA;
const Para_Type Para::Type_MIN;
const Para_Type Para::Type_MAX;
const int Para::Type_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
const ::google::protobuf::EnumDescriptor* Position_Type_descriptor() {
  protobuf_proto_2fmodels2_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_proto_2fmodels2_2eproto::file_level_enum_descriptors[1];
}
bool Position_Type_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const Position_Type Position::LEFT;
const Position_Type Position::RIGHT;
const Position_Type Position::TOP;
const Position_Type Position::Type_MIN;
const Position_Type Position::Type_MAX;
const int Position::Type_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
const ::google::protobuf::EnumDescriptor* Vehicle_Model_Type_descriptor() {
  protobuf_proto_2fmodels2_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_proto_2fmodels2_2eproto::file_level_enum_descriptors[2];
}
bool Vehicle_Model_Type_IsValid(int value) {
  switch (value) {
    case -1:
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const Vehicle_Model_Type Vehicle_Model::NotVehicle;
const Vehicle_Model_Type Vehicle_Model::Compact;
const Vehicle_Model_Type Vehicle_Model::Midsize;
const Vehicle_Model_Type Vehicle_Model::Large;
const Vehicle_Model_Type Vehicle_Model::SUV;
const Vehicle_Model_Type Vehicle_Model::BUS;
const Vehicle_Model_Type Vehicle_Model::TRUCK;
const Vehicle_Model_Type Vehicle_Model::Type_MIN;
const Vehicle_Model_Type Vehicle_Model::Type_MAX;
const int Vehicle_Model::Type_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

void Para::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Para::kParaTypeFieldNumber;
const int Para::kRowsFieldNumber;
const int Para::kColsFieldNumber;
const int Para::kDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Para::Para()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_proto_2fmodels2_2eproto::InitDefaultsPara();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:FCWS.Para)
}
Para::Para(const Para& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      data_(from.data_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&para_type_, &from.para_type_,
    static_cast<size_t>(reinterpret_cast<char*>(&cols_) -
    reinterpret_cast<char*>(&para_type_)) + sizeof(cols_));
  // @@protoc_insertion_point(copy_constructor:FCWS.Para)
}

void Para::SharedCtor() {
  _cached_size_ = 0;
  ::memset(&para_type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&cols_) -
      reinterpret_cast<char*>(&para_type_)) + sizeof(cols_));
}

Para::~Para() {
  // @@protoc_insertion_point(destructor:FCWS.Para)
  SharedDtor();
}

void Para::SharedDtor() {
}

void Para::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Para::descriptor() {
  ::protobuf_proto_2fmodels2_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proto_2fmodels2_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Para& Para::default_instance() {
  ::protobuf_proto_2fmodels2_2eproto::InitDefaultsPara();
  return *internal_default_instance();
}


void Para::Clear() {
// @@protoc_insertion_point(message_clear_start:FCWS.Para)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  data_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 7u) {
    ::memset(&para_type_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&cols_) -
        reinterpret_cast<char*>(&para_type_)) + sizeof(cols_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool Para::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:FCWS.Para)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .FCWS.Para.Type para_type = 1 [default = None];
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::FCWS::Para_Type_IsValid(value)) {
            set_para_type(static_cast< ::FCWS::Para_Type >(value));
          } else {
            mutable_unknown_fields()->AddVarint(
                1, static_cast< ::google::protobuf::uint64>(value));
          }
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required int32 rows = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          set_has_rows();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &rows_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required int32 cols = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          set_has_cols();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &cols_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated double data = 4 [packed = true];
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, this->mutable_data())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(33u /* 33 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 1, 34u, input, this->mutable_data())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:FCWS.Para)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:FCWS.Para)
  return false;
#undef DO_
}

void Para::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:FCWS.Para)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .FCWS.Para.Type para_type = 1 [default = None];
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->para_type(), output);
  }

  // required int32 rows = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->rows(), output);
  }

  // required int32 cols = 3;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->cols(), output);
  }

  // repeated double data = 4 [packed = true];
  if (this->data_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(4, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _data_cached_byte_size_));
    ::google::protobuf::internal::WireFormatLite::WriteDoubleArray(
      this->data().data(), this->data_size(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:FCWS.Para)
}

::google::protobuf::uint8* Para::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:FCWS.Para)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .FCWS.Para.Type para_type = 1 [default = None];
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->para_type(), target);
  }

  // required int32 rows = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->rows(), target);
  }

  // required int32 cols = 3;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->cols(), target);
  }

  // repeated double data = 4 [packed = true];
  if (this->data_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      4,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::int32>(
            _data_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteDoubleNoTagToArray(this->data_, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:FCWS.Para)
  return target;
}

size_t Para::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:FCWS.Para)
  size_t total_size = 0;

  if (has_para_type()) {
    // required .FCWS.Para.Type para_type = 1 [default = None];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->para_type());
  }

  if (has_rows()) {
    // required int32 rows = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->rows());
  }

  if (has_cols()) {
    // required int32 cols = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->cols());
  }

  return total_size;
}
size_t Para::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:FCWS.Para)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (((_has_bits_[0] & 0x00000007) ^ 0x00000007) == 0) {  // All required fields are present.
    // required .FCWS.Para.Type para_type = 1 [default = None];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->para_type());

    // required int32 rows = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->rows());

    // required int32 cols = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->cols());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  // repeated double data = 4 [packed = true];
  {
    unsigned int count = static_cast<unsigned int>(this->data_size());
    size_t data_size = 8UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _data_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Para::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:FCWS.Para)
  GOOGLE_DCHECK_NE(&from, this);
  const Para* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Para>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:FCWS.Para)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:FCWS.Para)
    MergeFrom(*source);
  }
}

void Para::MergeFrom(const Para& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:FCWS.Para)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  data_.MergeFrom(from.data_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 7u) {
    if (cached_has_bits & 0x00000001u) {
      para_type_ = from.para_type_;
    }
    if (cached_has_bits & 0x00000002u) {
      rows_ = from.rows_;
    }
    if (cached_has_bits & 0x00000004u) {
      cols_ = from.cols_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void Para::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:FCWS.Para)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Para::CopyFrom(const Para& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:FCWS.Para)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Para::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;
  return true;
}

void Para::Swap(Para* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Para::InternalSwap(Para* other) {
  using std::swap;
  data_.InternalSwap(&other->data_);
  swap(para_type_, other->para_type_);
  swap(rows_, other->rows_);
  swap(cols_, other->cols_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Para::GetMetadata() const {
  protobuf_proto_2fmodels2_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proto_2fmodels2_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Position::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Position::kPosFieldNumber;
const int Position::kParaFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Position::Position()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_proto_2fmodels2_2eproto::InitDefaultsPosition();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:FCWS.Position)
}
Position::Position(const Position& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      para_(from.para_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  pos_ = from.pos_;
  // @@protoc_insertion_point(copy_constructor:FCWS.Position)
}

void Position::SharedCtor() {
  _cached_size_ = 0;
  pos_ = 0;
}

Position::~Position() {
  // @@protoc_insertion_point(destructor:FCWS.Position)
  SharedDtor();
}

void Position::SharedDtor() {
}

void Position::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Position::descriptor() {
  ::protobuf_proto_2fmodels2_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proto_2fmodels2_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Position& Position::default_instance() {
  ::protobuf_proto_2fmodels2_2eproto::InitDefaultsPosition();
  return *internal_default_instance();
}


void Position::Clear() {
// @@protoc_insertion_point(message_clear_start:FCWS.Position)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  para_.Clear();
  pos_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool Position::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:FCWS.Position)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .FCWS.Position.Type pos = 1 [default = LEFT];
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::FCWS::Position_Type_IsValid(value)) {
            set_pos(static_cast< ::FCWS::Position_Type >(value));
          } else {
            mutable_unknown_fields()->AddVarint(
                1, static_cast< ::google::protobuf::uint64>(value));
          }
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .FCWS.Para para = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_para()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:FCWS.Position)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:FCWS.Position)
  return false;
#undef DO_
}

void Position::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:FCWS.Position)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .FCWS.Position.Type pos = 1 [default = LEFT];
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->pos(), output);
  }

  // repeated .FCWS.Para para = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->para_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2,
      this->para(static_cast<int>(i)),
      output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:FCWS.Position)
}

::google::protobuf::uint8* Position::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:FCWS.Position)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .FCWS.Position.Type pos = 1 [default = LEFT];
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->pos(), target);
  }

  // repeated .FCWS.Para para = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->para_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->para(static_cast<int>(i)), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:FCWS.Position)
  return target;
}

size_t Position::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:FCWS.Position)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // required .FCWS.Position.Type pos = 1 [default = LEFT];
  if (has_pos()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->pos());
  }
  // repeated .FCWS.Para para = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->para_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->para(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Position::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:FCWS.Position)
  GOOGLE_DCHECK_NE(&from, this);
  const Position* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Position>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:FCWS.Position)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:FCWS.Position)
    MergeFrom(*source);
  }
}

void Position::MergeFrom(const Position& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:FCWS.Position)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  para_.MergeFrom(from.para_);
  if (from.has_pos()) {
    set_pos(from.pos());
  }
}

void Position::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:FCWS.Position)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Position::CopyFrom(const Position& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:FCWS.Position)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Position::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->para())) return false;
  return true;
}

void Position::Swap(Position* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Position::InternalSwap(Position* other) {
  using std::swap;
  CastToBase(&para_)->InternalSwap(CastToBase(&other->para_));
  swap(pos_, other->pos_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Position::GetMetadata() const {
  protobuf_proto_2fmodels2_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proto_2fmodels2_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Vehicle_Model::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Vehicle_Model::kTypeFieldNumber;
const int Vehicle_Model::kPositionFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Vehicle_Model::Vehicle_Model()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_proto_2fmodels2_2eproto::InitDefaultsVehicle_Model();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:FCWS.Vehicle_Model)
}
Vehicle_Model::Vehicle_Model(const Vehicle_Model& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      position_(from.position_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  type_ = from.type_;
  // @@protoc_insertion_point(copy_constructor:FCWS.Vehicle_Model)
}

void Vehicle_Model::SharedCtor() {
  _cached_size_ = 0;
  type_ = -1;
}

Vehicle_Model::~Vehicle_Model() {
  // @@protoc_insertion_point(destructor:FCWS.Vehicle_Model)
  SharedDtor();
}

void Vehicle_Model::SharedDtor() {
}

void Vehicle_Model::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Vehicle_Model::descriptor() {
  ::protobuf_proto_2fmodels2_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proto_2fmodels2_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Vehicle_Model& Vehicle_Model::default_instance() {
  ::protobuf_proto_2fmodels2_2eproto::InitDefaultsVehicle_Model();
  return *internal_default_instance();
}


void Vehicle_Model::Clear() {
// @@protoc_insertion_point(message_clear_start:FCWS.Vehicle_Model)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  position_.Clear();
  type_ = -1;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool Vehicle_Model::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:FCWS.Vehicle_Model)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .FCWS.Vehicle_Model.Type type = 1 [default = NotVehicle];
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::FCWS::Vehicle_Model_Type_IsValid(value)) {
            set_type(static_cast< ::FCWS::Vehicle_Model_Type >(value));
          } else {
            mutable_unknown_fields()->AddVarint(
                1, static_cast< ::google::protobuf::uint64>(value));
          }
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .FCWS.Position position = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_position()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:FCWS.Vehicle_Model)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:FCWS.Vehicle_Model)
  return false;
#undef DO_
}

void Vehicle_Model::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:FCWS.Vehicle_Model)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .FCWS.Vehicle_Model.Type type = 1 [default = NotVehicle];
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }

  // repeated .FCWS.Position position = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->position_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2,
      this->position(static_cast<int>(i)),
      output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:FCWS.Vehicle_Model)
}

::google::protobuf::uint8* Vehicle_Model::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:FCWS.Vehicle_Model)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .FCWS.Vehicle_Model.Type type = 1 [default = NotVehicle];
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->type(), target);
  }

  // repeated .FCWS.Position position = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->position_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->position(static_cast<int>(i)), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:FCWS.Vehicle_Model)
  return target;
}

size_t Vehicle_Model::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:FCWS.Vehicle_Model)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // required .FCWS.Vehicle_Model.Type type = 1 [default = NotVehicle];
  if (has_type()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
  }
  // repeated .FCWS.Position position = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->position_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->position(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Vehicle_Model::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:FCWS.Vehicle_Model)
  GOOGLE_DCHECK_NE(&from, this);
  const Vehicle_Model* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Vehicle_Model>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:FCWS.Vehicle_Model)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:FCWS.Vehicle_Model)
    MergeFrom(*source);
  }
}

void Vehicle_Model::MergeFrom(const Vehicle_Model& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:FCWS.Vehicle_Model)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  position_.MergeFrom(from.position_);
  if (from.has_type()) {
    set_type(from.type());
  }
}

void Vehicle_Model::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:FCWS.Vehicle_Model)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Vehicle_Model::CopyFrom(const Vehicle_Model& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:FCWS.Vehicle_Model)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Vehicle_Model::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->position())) return false;
  return true;
}

void Vehicle_Model::Swap(Vehicle_Model* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Vehicle_Model::InternalSwap(Vehicle_Model* other) {
  using std::swap;
  CastToBase(&position_)->InternalSwap(CastToBase(&other->position_));
  swap(type_, other->type_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Vehicle_Model::GetMetadata() const {
  protobuf_proto_2fmodels2_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proto_2fmodels2_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Models::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Models::kVmFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Models::Models()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_proto_2fmodels2_2eproto::InitDefaultsModels();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:FCWS.Models)
}
Models::Models(const Models& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      vm_(from.vm_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:FCWS.Models)
}

void Models::SharedCtor() {
  _cached_size_ = 0;
}

Models::~Models() {
  // @@protoc_insertion_point(destructor:FCWS.Models)
  SharedDtor();
}

void Models::SharedDtor() {
}

void Models::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Models::descriptor() {
  ::protobuf_proto_2fmodels2_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proto_2fmodels2_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Models& Models::default_instance() {
  ::protobuf_proto_2fmodels2_2eproto::InitDefaultsModels();
  return *internal_default_instance();
}


void Models::Clear() {
// @@protoc_insertion_point(message_clear_start:FCWS.Models)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  vm_.Clear();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool Models::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:FCWS.Models)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .FCWS.Vehicle_Model vm = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_vm()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:FCWS.Models)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:FCWS.Models)
  return false;
#undef DO_
}

void Models::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:FCWS.Models)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .FCWS.Vehicle_Model vm = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->vm_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->vm(static_cast<int>(i)),
      output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:FCWS.Models)
}

::google::protobuf::uint8* Models::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:FCWS.Models)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .FCWS.Vehicle_Model vm = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->vm_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->vm(static_cast<int>(i)), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:FCWS.Models)
  return target;
}

size_t Models::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:FCWS.Models)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // repeated .FCWS.Vehicle_Model vm = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->vm_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->vm(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Models::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:FCWS.Models)
  GOOGLE_DCHECK_NE(&from, this);
  const Models* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Models>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:FCWS.Models)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:FCWS.Models)
    MergeFrom(*source);
  }
}

void Models::MergeFrom(const Models& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:FCWS.Models)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  vm_.MergeFrom(from.vm_);
}

void Models::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:FCWS.Models)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Models::CopyFrom(const Models& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:FCWS.Models)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Models::IsInitialized() const {
  if (!::google::protobuf::internal::AllAreInitialized(this->vm())) return false;
  return true;
}

void Models::Swap(Models* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Models::InternalSwap(Models* other) {
  using std::swap;
  CastToBase(&vm_)->InternalSwap(CastToBase(&other->vm_));
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Models::GetMetadata() const {
  protobuf_proto_2fmodels2_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proto_2fmodels2_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace FCWS
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::FCWS::Para* Arena::Create< ::FCWS::Para >(Arena* arena) {
  return Arena::CreateInternal< ::FCWS::Para >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::FCWS::Position* Arena::Create< ::FCWS::Position >(Arena* arena) {
  return Arena::CreateInternal< ::FCWS::Position >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::FCWS::Vehicle_Model* Arena::Create< ::FCWS::Vehicle_Model >(Arena* arena) {
  return Arena::CreateInternal< ::FCWS::Vehicle_Model >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::FCWS::Models* Arena::Create< ::FCWS::Models >(Arena* arena) {
  return Arena::CreateInternal< ::FCWS::Models >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
