VideoCore Library: containers/binary/binary_reader.c File Reference
binary_reader.c File Reference
#include <stdlib.h>
#include <string.h>
#include "containers/core/containers_private.h"
#include "containers/core/containers_io_helpers.h"
#include "containers/core/containers_utils.h"
#include "containers/core/containers_logging.h"
Classes
struct VC_CONTAINER_MODULE_T
Macros
#define DEFAULT_BLOCK_SIZE (1024*16)
#define DEFAULT_JPEG_BLOCK_SIZE (1024*80)
Typedefs
typedef struct VC_CONTAINER_MODULE_T VC_CONTAINER_MODULE_T
Functions
VC_CONTAINER_STATUS_T binary_reader_open (VC_CONTAINER_T *)
Macro Definition Documentation
DEFAULT_BLOCK_SIZE
#define DEFAULT_BLOCK_SIZE (1024*16)
Definition at line 38 of file binary_reader.c.
DEFAULT_JPEG_BLOCK_SIZE
#define DEFAULT_JPEG_BLOCK_SIZE (1024*80)
Definition at line 40 of file binary_reader.c.
Typedef Documentation
VC_CONTAINER_MODULE_T
typedef struct VC_CONTAINER_MODULE_T VC_CONTAINER_MODULE_T
Function Documentation
binary_reader_open()
VC_CONTAINER_STATUS_T binary_reader_open (VC_CONTAINER_T * p_ctx)
Definition at line 190 of file binary_reader.c.
References codec, extension, VC_CONTAINER_T::priv, VC_CONTAINER_MODULE_T::status, VC_CONTAINER_PRIVATE_T::uri, VC_CONTAINER_ERROR_FORMAT_INVALID, VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED, vc_uri_find_query(), vc_uri_path(), and vc_uri_path_extension().
 {
    const char *extension = vc_uri_path_extension(p_ctx->priv->uri);
    VC_CONTAINER_MODULE_T *module = 0;
    VC_CONTAINER_STATUS_T status = VC_CONTAINER_ERROR_FORMAT_INVALID;
    VC_CONTAINER_ES_TYPE_T es_type = 0;
    VC_CONTAINER_FOURCC_T codec = 0;
    unsigned int i;
    /* Check if the user has specified a container */
    vc_uri_find_query(p_ctx->priv->uri, 0, "container", &extension);
    /* Check if the extension is supported */
    if(!extension || !vc_uri_path(p_ctx->priv->uri))
       return VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED;
    for(i = 0; extension_to_format_table[i].ext; i++)
    {
       if(strcasecmp(extension, extension_to_format_table[i].ext))
          continue;
       es_type = extension_to_format_table[i].type;
       codec = extension_to_format_table[i].codec;
       break;
    }
    if(!extension_to_format_table[i].ext) return VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED;
    /* If this a .bin file we look in our bin list */
    for(i = 0; !codec && bin_extension_to_format_table[i].ext; i++)
    {
       if(!strstr(vc_uri_path(p_ctx->priv->uri), bin_extension_to_format_table[i].ext) &&
          !strstr(extension, bin_extension_to_format_table[i].ext))
          continue;
       es_type = bin_extension_to_format_table[i].type;
       codec = bin_extension_to_format_table[i].codec;
       break;
    }
    if(!codec) return VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED;
    /* Allocate our context */
    module = malloc(sizeof(*module));
    if(!module) { status = VC_CONTAINER_ERROR_OUT_OF_MEMORY; goto error; }
    memset(module, 0, sizeof(*module));
    p_ctx->priv->module = module;
    p_ctx->tracks_num = 1;
    p_ctx->tracks = &module->track;
    p_ctx->tracks[0] = vc_container_allocate_track(p_ctx, 0);
    if(!p_ctx->tracks[0]) return VC_CONTAINER_ERROR_OUT_OF_MEMORY;
    p_ctx->tracks[0]->format->es_type = es_type;
    p_ctx->tracks[0]->format->codec = codec;
    p_ctx->tracks[0]->is_enabled = true;
    module->default_block_size = DEFAULT_BLOCK_SIZE;
    if(codec == VC_CONTAINER_CODEC_JPEG)
       module->default_block_size = DEFAULT_JPEG_BLOCK_SIZE;
    module->block_size = module->default_block_size;
    module->init = 1;
    /*
     *  We now have all the information we really need to start playing the stream
     */
    p_ctx->priv->pf_close = binary_reader_close;
    p_ctx->priv->pf_read = binary_reader_read;
    p_ctx->priv->pf_seek = binary_reader_seek;
    return VC_CONTAINER_SUCCESS;
  error:
    LOG_DEBUG(p_ctx, "binary: error opening stream (%i)", status);
    return status;
 }
Variable Documentation
codec
VC_CONTAINER_FOURCC_T codec
Definition at line 60 of file binary_reader.c.
Referenced by binary_reader_open(), flv_reader_open(), and wav_reader_open().
ext
const char* ext
Definition at line 58 of file binary_reader.c.
type
VC_CONTAINER_ES_TYPE_T type
Definition at line 59 of file binary_reader.c.