VideoCore Library: host_applications/linux/apps/raspicam/RaspiStillYUV.c File Reference
RaspiStillYUV.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <memory.h>
#include <sysexits.h>
#include <unistd.h>
#include <errno.h>
#include "bcm_host.h"
#include "interface/vcos/vcos.h"
#include "interface/mmal/mmal.h"
#include "interface/mmal/mmal_logging.h"
#include "interface/mmal/mmal_buffer.h"
#include "interface/mmal/util/mmal_util.h"
#include "interface/mmal/util/mmal_util_params.h"
#include "interface/mmal/util/mmal_default_components.h"
#include "interface/mmal/util/mmal_connection.h"
#include "RaspiCamControl.h"
#include "RaspiPreview.h"
#include "RaspiCLI.h"
#include "RaspiCommonSettings.h"
#include "RaspiHelpers.h"
#include "RaspiGPS.h"
#include <semaphore.h>
Classes
struct RASPISTILLYUV_STATE
struct PORT_USERDATA
Macros
#define _GNU_SOURCE
#define MMAL_CAMERA_PREVIEW_PORT 0
#define MMAL_CAMERA_VIDEO_PORT 1
#define MMAL_CAMERA_CAPTURE_PORT 2
#define STILLS_FRAME_RATE_NUM 0
#define STILLS_FRAME_RATE_DEN 1
#define VIDEO_OUTPUT_BUFFERS_NUM 3
Video render needs at least 2 buffers.
#define CAMERA_SETTLE_TIME 1000
Enumerations
enum {
FRAME_NEXT_SINGLE, FRAME_NEXT_TIMELAPSE, FRAME_NEXT_KEYPRESS, FRAME_NEXT_FOREVER,
FRAME_NEXT_GPIO, FRAME_NEXT_SIGNAL, FRAME_NEXT_IMMEDIATELY
}
Frame advance method.
enum {
CommandTimeout, CommandTimelapse, CommandUseRGB, CommandFullResPreview,
CommandLink, CommandKeypress, CommandSignal, CommandBurstMode,
CommandOnlyLuma, CommandUseBGR
}
Comamnd ID's and Structure defining our command line options.
Functions
int mmal_status_to_int (MMAL_STATUS_T status)
MMAL_STATUS_T create_filenames (char **finalName, char **tempName, char *pattern, int frame)
int main (int argc, const char **argv)
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 49 of file RaspiStillYUV.c.
CAMERA_SETTLE_TIME
#define CAMERA_SETTLE_TIME 1000
Definition at line 107 of file RaspiStillYUV.c.
MMAL_CAMERA_CAPTURE_PORT
#define MMAL_CAMERA_CAPTURE_PORT 2
Definition at line 84 of file RaspiStillYUV.c.
MMAL_CAMERA_PREVIEW_PORT
#define MMAL_CAMERA_PREVIEW_PORT 0
Definition at line 82 of file RaspiStillYUV.c.
MMAL_CAMERA_VIDEO_PORT
#define MMAL_CAMERA_VIDEO_PORT 1
Definition at line 83 of file RaspiStillYUV.c.
STILLS_FRAME_RATE_DEN
#define STILLS_FRAME_RATE_DEN 1
Definition at line 90 of file RaspiStillYUV.c.
STILLS_FRAME_RATE_NUM
#define STILLS_FRAME_RATE_NUM 0
Definition at line 89 of file RaspiStillYUV.c.
VIDEO_OUTPUT_BUFFERS_NUM
#define VIDEO_OUTPUT_BUFFERS_NUM 3
Video render needs at least 2 buffers.
Definition at line 93 of file RaspiStillYUV.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Frame advance method.
Enumerator
FRAME_NEXT_SINGLE
FRAME_NEXT_TIMELAPSE
FRAME_NEXT_KEYPRESS
FRAME_NEXT_FOREVER
FRAME_NEXT_GPIO
FRAME_NEXT_SIGNAL
FRAME_NEXT_IMMEDIATELY
Definition at line 96 of file RaspiStillYUV.c.
 {
    FRAME_NEXT_SINGLE,
    FRAME_NEXT_TIMELAPSE,
    FRAME_NEXT_KEYPRESS,
    FRAME_NEXT_FOREVER,
    FRAME_NEXT_GPIO,
    FRAME_NEXT_SIGNAL,
    FRAME_NEXT_IMMEDIATELY
 };
anonymous enum
anonymous enum
Comamnd ID's and Structure defining our command line options.
Enumerator
CommandTimeout
CommandTimelapse
CommandUseRGB
CommandFullResPreview
CommandLink
CommandKeypress
CommandSignal
CommandBurstMode
CommandOnlyLuma
CommandUseBGR
Definition at line 145 of file RaspiStillYUV.c.
 {
    CommandTimeout,
    CommandTimelapse,
    CommandUseRGB,
    CommandFullResPreview,
    CommandLink,
    CommandKeypress,
    CommandSignal,
    CommandBurstMode,
    CommandOnlyLuma,
    CommandUseBGR
 };
Function Documentation
create_filenames()
MMAL_STATUS_T create_filenames (char ** finalName, char ** tempName, char * pattern, int frame)
Allocates and generates a filename based on the user-supplied pattern and the frame number. On successful return, finalName and tempName point to malloc()ed strings which must be freed externally. (On failure, returns nulls that don't need free()ing.)
Parameters
finalName pointer receives an
pattern sprintf pattern with d to be replaced by frame
frame for timelapse, the frame number
Returns
Returns a MMAL_STATUS_T giving result of operation
Definition at line 832 of file RaspiStillYUV.c.
References MMAL_ENOMEM, MMAL_SUCCESS, and NULL.
 {
    *finalName = NULL;
    *tempName = NULL;
    if (0 > asprintf(finalName, pattern, frame) ||
          0 > asprintf(tempName, "%s~", *finalName))
    {
       if (*finalName != NULL)
       {
          free(*finalName);
       }
       return MMAL_ENOMEM;    // It may be some other error, but it is not worth getting it right
    }
    return MMAL_SUCCESS;
 }
main()
int main (int argc, const char ** argv)
main
Definition at line 1056 of file RaspiStillYUV.c.
 {
    // Our main data storage vessel..
    RASPISTILLYUV_STATE state;
    int exit_code = EX_OK;
    MMAL_STATUS_T status = MMAL_SUCCESS;
    MMAL_PORT_T *camera_preview_port = NULL;
    MMAL_PORT_T *camera_video_port = NULL;
    MMAL_PORT_T *camera_still_port = NULL;
    MMAL_PORT_T *preview_input_port = NULL;
    FILE *output_file = NULL;
    bcm_host_init();
    // Register our application with the logging system
    vcos_log_register("RaspiStill", VCOS_LOG_CATEGORY);
    signal(SIGINT, default_signal_handler);
    // Disable USR1 for the moment - may be reenabled if go in to signal capture mode
    signal(SIGUSR1, SIG_IGN);
    set_app_name(argv[0]);
    // Do we have any parameters
    if (argc == 1)
    {
       display_valid_parameters(basename(argv[0]), &application_help_message);
       exit(EX_USAGE);
    }
    default_status(&state);
    // Parse the command line and put options in to our status structure
    if (parse_cmdline(argc, argv, &state))
    {
       status = -1;
       exit(EX_USAGE);
    }
    if (state.timeout == -1)
       state.timeout = 5000;
    if (state.common_settings.gps)
       if (raspi_gps_setup(state.common_settings.verbose))
          state.common_settings.gps = false;
    // Setup for sensor specific parameters
    get_sensor_defaults(state.common_settings.cameraNum, state.common_settings.camera_name,
                        &state.common_settings.width, &state.common_settings.height);
    if (state.common_settings.verbose)
    {
       print_app_details(stderr);
       dump_status(&state);
    }
    // OK, we have a nice set of parameters. Now set up our components
    // We have two components. Camera and Preview
    // Camera is different in stills/video, but preview
    // is the same so handed off to a separate module
    if ((status = create_camera_component(&state)) != MMAL_SUCCESS)
    {
       vcos_log_error("%s: Failed to create camera component", __func__);
       exit_code = EX_SOFTWARE;
    }
    else if ((status = raspipreview_create(&state.preview_parameters)) != MMAL_SUCCESS)
    {
       vcos_log_error("%s: Failed to create preview component", __func__);
       destroy_camera_component(&state);
       exit_code = EX_SOFTWARE;
    }
    else
    {
       PORT_USERDATA callback_data;
       if (state.common_settings.verbose)
          fprintf(stderr, "Starting component connection stage\n");
       camera_preview_port = state.camera_component->output[MMAL_CAMERA_PREVIEW_PORT];
       camera_video_port   = state.camera_component->output[MMAL_CAMERA_VIDEO_PORT];
       camera_still_port   = state.camera_component->output[MMAL_CAMERA_CAPTURE_PORT];
       // Note we are lucky that the preview and null sink components use the same input port
       // so we can simple do this without conditionals
       preview_input_port  = state.preview_parameters.preview_component->input[0];
       // Connect camera to preview (which might be a null_sink if no preview required)
       status = connect_ports(camera_preview_port, preview_input_port, &state.preview_connection);
       if (status == MMAL_SUCCESS)
       {
          VCOS_STATUS_T vcos_status;
          // Set up our userdata - this is passed though to the callback where we need the information.
          // Null until we open our filename
          callback_data.file_handle = NULL;
          callback_data.pstate = &state;
          vcos_status = vcos_semaphore_create(&callback_data.complete_semaphore, "RaspiStill-sem", 0);
          vcos_assert(vcos_status == VCOS_SUCCESS);
          camera_still_port->userdata = (struct MMAL_PORT_USERDATA_T *)&callback_data;
          if (state.common_settings.verbose)
             fprintf(stderr, "Enabling camera still output port\n");
          // Enable the camera still output port and tell it its callback function
          status = mmal_port_enable(camera_still_port, camera_buffer_callback);
          if (status != MMAL_SUCCESS)
          {
             vcos_log_error("Failed to setup camera output");
             goto error;
          }
          if (state.common_settings.verbose)
             fprintf(stderr, "Starting video preview\n");
          int frame, keep_looping = 1;
          FILE *output_file = NULL;
          char *use_filename = NULL;      // Temporary filename while image being written
          char *final_filename = NULL;    // Name that file gets once writing complete
          frame = 0;
          while (keep_looping)
          {
             keep_looping = wait_for_next_frame(&state, &frame);
             // Open the file
             if (state.common_settings.filename)
             {
                if (state.common_settings.filename[0] == '-')
                {
                   output_file = stdout;
                   // Ensure we don't upset the output stream with diagnostics/info
                   state.common_settings.verbose = 0;
                }
                else
                {
                   vcos_assert(use_filename == NULL && final_filename == NULL);
                   status = create_filenames(&final_filename, &use_filename, state.common_settings.filename, frame);
                   if (status  != MMAL_SUCCESS)
                   {
                      vcos_log_error("Unable to create filenames");
                      goto error;
                   }
                   if (state.common_settings.verbose)
                      fprintf(stderr, "Opening output file %s\n", final_filename);
                   // Technically it is opening the temp~ filename which will be ranamed to the final filename
                   output_file = fopen(use_filename, "wb");
                   if (!output_file)
                   {
                      // Notify user, carry on but discarding encoded output buffers
                      vcos_log_error("%s: Error opening output file: %s\nNo output file will be generated\n", __func__, use_filename);
                   }
                }
                callback_data.file_handle = output_file;
             }
             if (output_file)
             {
                int num, q;
                // There is a possibility that shutter needs to be set each loop.
                if (mmal_status_to_int(mmal_port_parameter_set_uint32(state.camera_component->control, MMAL_PARAMETER_SHUTTER_SPEED, state.camera_parameters.shutter_speed) != MMAL_SUCCESS))
                   vcos_log_error("Unable to set shutter speed");
                // Send all the buffers to the camera output port
                num = mmal_queue_length(state.camera_pool->queue);
                for (q=0; q<num; q++)
                {
                   MMAL_BUFFER_HEADER_T *buffer = mmal_queue_get(state.camera_pool->queue);
                   if (!buffer)
                      vcos_log_error("Unable to get a required buffer %d from pool queue", q);
                   if (mmal_port_send_buffer(camera_still_port, buffer)!= MMAL_SUCCESS)
                      vcos_log_error("Unable to send a buffer to camera output port (%d)", q);
                }
                if (state.burstCaptureMode && frame==1)
                {
                   mmal_port_parameter_set_boolean(state.camera_component->control,  MMAL_PARAMETER_CAMERA_BURST_CAPTURE, 1);
                }
                if(state.camera_parameters.enable_annotate)
                {
                   if ((state.camera_parameters.enable_annotate & ANNOTATE_APP_TEXT) && state.common_settings.gps)
                   {
                      char *text = raspi_gps_location_string();
                      raspicamcontrol_set_annotate(state.camera_component, state.camera_parameters.enable_annotate,
                                                   text,
                                                   state.camera_parameters.annotate_text_size,
                                                   state.camera_parameters.annotate_text_colour,
                                                   state.camera_parameters.annotate_bg_colour,
                                                   state.camera_parameters.annotate_justify,
                                                   state.camera_parameters.annotate_x,
                                                   state.camera_parameters.annotate_y
                                                  );
                      free(text);
                   }
                   else
                      raspicamcontrol_set_annotate(state.camera_component, state.camera_parameters.enable_annotate,
                                                   state.camera_parameters.annotate_string,
                                                   state.camera_parameters.annotate_text_size,
                                                   state.camera_parameters.annotate_text_colour,
                                                   state.camera_parameters.annotate_bg_colour,
                                                   state.camera_parameters.annotate_justify,
                                                   state.camera_parameters.annotate_x,
                                                   state.camera_parameters.annotate_y
                                                  );
                }
                if (state.common_settings.verbose)
                   fprintf(stderr, "Starting capture %d\n", frame);
                if (mmal_port_parameter_set_boolean(camera_still_port, MMAL_PARAMETER_CAPTURE, 1) != MMAL_SUCCESS)
                {
                   vcos_log_error("%s: Failed to start capture", __func__);
                }
                else
                {
                   // Wait for capture to complete
                   // For some reason using vcos_semaphore_wait_timeout sometimes returns immediately with bad parameter error
                   // even though it appears to be all correct, so reverting to untimed one until figure out why its erratic
                   vcos_semaphore_wait(&callback_data.complete_semaphore);
                   if (state.common_settings.verbose)
                      fprintf(stderr, "Finished capture %d\n", frame);
                }
                // Ensure we don't die if get callback with no open file
                callback_data.file_handle = NULL;
                if (output_file != stdout)
                {
                   rename_file(&state, output_file, final_filename, use_filename, frame);
                }
                else
                {
                   fflush(output_file);
                }
             }
             if (use_filename)
             {
                free(use_filename);
                use_filename = NULL;
             }
             if (final_filename)
             {
                free(final_filename);
                final_filename = NULL;
             }
          } // end for (frame)
          vcos_semaphore_delete(&callback_data.complete_semaphore);
       }
       else
       {
          mmal_status_to_int(status);
          vcos_log_error("%s: Failed to connect camera to preview", __func__);
       }
 error:
       mmal_status_to_int(status);
       if (state.common_settings.verbose)
          fprintf(stderr, "Closing down\n");
       if (output_file)
          fclose(output_file);
       // Disable all our ports that are not handled by connections
       check_disable_port(camera_video_port);
       if (state.preview_connection)
          mmal_connection_destroy(state.preview_connection);
       /* Disable components */
       if (state.preview_parameters.preview_component)
          mmal_component_disable(state.preview_parameters.preview_component);
       if (state.camera_component)
          mmal_component_disable(state.camera_component);
       raspipreview_destroy(&state.preview_parameters);
       destroy_camera_component(&state);
       if (state.common_settings.gps)
          raspi_gps_shutdown(state.common_settings.verbose);
       if (state.common_settings.verbose)
          fprintf(stderr, "Close down completed, all components disconnected, disabled and destroyed\n\n");
    }
    if (status != MMAL_SUCCESS)
       raspicamcontrol_check_configuration(128);
    return exit_code;
 }
mmal_status_to_int()
int mmal_status_to_int (MMAL_STATUS_T status)
Convert a MMAL status return value to a simple boolean of success ALso displays a fault if code is not success
Parameters
status The error code to convert
Returns
0 if status is success, 1 otherwise
Definition at line 222 of file RaspiHelpers.c.
References MMAL_EAGAIN, MMAL_ECONFIG, MMAL_ECORRUPT, MMAL_EFAULT, MMAL_EINVAL, MMAL_EIO, MMAL_EISCONN, MMAL_ENOENT, MMAL_ENOMEM, MMAL_ENOSPC, MMAL_ENOSYS, MMAL_ENOTCONN, MMAL_ENOTREADY, MMAL_ENXIO, MMAL_ESPIPE, and MMAL_SUCCESS.
Referenced by raspicamcontrol_set_annotate(), raspicamcontrol_set_awb_gains(), raspicamcontrol_set_awb_mode(), raspicamcontrol_set_brightness(), raspicamcontrol_set_colourFX(), raspicamcontrol_set_contrast(), raspicamcontrol_set_DRC(), raspicamcontrol_set_exposure_compensation(), raspicamcontrol_set_exposure_mode(), raspicamcontrol_set_flicker_avoid_mode(), raspicamcontrol_set_flips(), raspicamcontrol_set_gains(), raspicamcontrol_set_imageFX(), raspicamcontrol_set_ISO(), raspicamcontrol_set_metering_mode(), raspicamcontrol_set_ROI(), raspicamcontrol_set_rotation(), raspicamcontrol_set_saturation(), raspicamcontrol_set_sharpness(), raspicamcontrol_set_shutter_speed(), raspicamcontrol_set_stats_pass(), raspicamcontrol_set_stereo_mode(), raspicamcontrol_set_video_stabilisation(), and raspicamcontrol_zoom_in_zoom_out().
 {
    if (status == MMAL_SUCCESS)
       return 0;
    else
    {
       switch (status)
       {
       case MMAL_ENOMEM :
          vcos_log_error("Out of memory");
          break;
       case MMAL_ENOSPC :
          vcos_log_error("Out of resources (other than memory)");
          break;
       case MMAL_EINVAL:
          vcos_log_error("Argument is invalid");
          break;
       case MMAL_ENOSYS :
          vcos_log_error("Function not implemented");
          break;
       case MMAL_ENOENT :
          vcos_log_error("No such file or directory");
          break;
       case MMAL_ENXIO :
          vcos_log_error("No such device or address");
          break;
       case MMAL_EIO :
          vcos_log_error("I/O error");
          break;
       case MMAL_ESPIPE :
          vcos_log_error("Illegal seek");
          break;
       case MMAL_ECORRUPT :
          vcos_log_error("Data is corrupt \attention FIXME: not POSIX");
          break;
       case MMAL_ENOTREADY :
          vcos_log_error("Component is not ready \attention FIXME: not POSIX");
          break;
       case MMAL_ECONFIG :
          vcos_log_error("Component is not configured \attention FIXME: not POSIX");
          break;
       case MMAL_EISCONN :
          vcos_log_error("Port is already connected ");
          break;
       case MMAL_ENOTCONN :
          vcos_log_error("Port is disconnected");
          break;
       case MMAL_EAGAIN :
          vcos_log_error("Resource temporarily unavailable. Try again later");
          break;
       case MMAL_EFAULT :
          vcos_log_error("Bad address");
          break;
       default :
          vcos_log_error("Unknown status error");
          break;
       }
       return 1;
    }
 }
Variable Documentation
description
char* description
Definition at line 177 of file RaspiStillYUV.c.
nextFrameMethod
int nextFrameMethod
Definition at line 178 of file RaspiStillYUV.c.