VideoCore Library: containers/core/containers_list.h File Reference
containers_list.h File Reference
#include "containers/containers.h"
Classes
struct vc_containers_list_tag
Macros
#define VC_CONTAINERS_STATIC_LIST(L, A, C) static VC_CONTAINERS_LIST_T L = { countof(A), 0, sizeof(*(A)), (VC_CONTAINERS_LIST_COMPARATOR_T)(C), A }
Typedefs
typedef int(* VC_CONTAINERS_LIST_COMPARATOR_T) (const void *a, const void *b)
typedef struct vc_containers_list_tag VC_CONTAINERS_LIST_T
Functions
VC_CONTAINERS_LIST_T * vc_containers_list_create (uint32_t capacity, size_t entry_size, VC_CONTAINERS_LIST_COMPARATOR_T comparator)
void vc_containers_list_destroy (VC_CONTAINERS_LIST_T *list)
void vc_containers_list_reset (VC_CONTAINERS_LIST_T *list)
bool vc_containers_list_insert (VC_CONTAINERS_LIST_T *list, void *new_entry, bool allow_duplicates)
bool vc_containers_list_find_entry (const VC_CONTAINERS_LIST_T *list, void *entry)
void vc_containers_list_validate (const VC_CONTAINERS_LIST_T *list)
Macro Definition Documentation
VC_CONTAINERS_STATIC_LIST
#define VC_CONTAINERS_STATIC_LIST (L, A, C) static VC_CONTAINERS_LIST_T L = { countof(A), 0, sizeof(*(A)), (VC_CONTAINERS_LIST_COMPARATOR_T)(C), A }
Macro to generate a static, read-only list from an array and comparator
Definition at line 50 of file containers_list.h.
Typedef Documentation
VC_CONTAINERS_LIST_COMPARATOR_T
typedef int(* VC_CONTAINERS_LIST_COMPARATOR_T) (const void *a, const void *b)
List entry comparison prototype. Returns zero if items at a and b match, positive if a is "bigger" than b and negative if a is "smaller" than b.
Definition at line 36 of file containers_list.h.
VC_CONTAINERS_LIST_T
typedef struct vc_containers_list_tag VC_CONTAINERS_LIST_T
Sorted list type. Storage type providing efficient insertion and search via binary sub-division.
Function Documentation
vc_containers_list_create()
VC_CONTAINERS_LIST_T* vc_containers_list_create (uint32_t capacity, size_t entry_size, VC_CONTAINERS_LIST_COMPARATOR_T comparator)
Create an empty list. The list is created based on the details provided, minimum capacity one entry.
Parameters
The initial capacity in entries.
entry_size The size of each entry, in bytes.
comparator A function for comparing two entries.
Returns
The new list or NULL.
Definition at line 95 of file containers_list.c.
References vc_containers_list_tag::capacity, vc_containers_list_tag::comparator, vc_containers_list_tag::entries, vc_containers_list_tag::entry_size, NULL, and vc_containers_list_tag::size.
Referenced by rtsp_reader_open(), and vc_container_io_http_open().
 {
    VC_CONTAINERS_LIST_T *list;
    list = (VC_CONTAINERS_LIST_T *)malloc(sizeof(VC_CONTAINERS_LIST_T));
    if (!list)
       return NULL;
    /* Ensure non-zero capacity, as that signifies a read-only list */
    if (!capacity) capacity = 1;
    list->entries = malloc(capacity * entry_size);
    if (!list->entries)
    {
       free(list);
       return NULL;
    }
    list->size = 0;
    list->capacity = capacity;
    list->entry_size = entry_size;
    list->comparator = comparator;
    return list;
 }
vc_containers_list_destroy()
void vc_containers_list_destroy (VC_CONTAINERS_LIST_T * list)
Destroy a list. Has no effect on a static list.
Parameters
list The list to be destroyed.
Definition at line 124 of file containers_list.c.
References vc_containers_list_tag::capacity, and vc_containers_list_tag::entries.
 {
    /* Avoid trying to destroy read-only lists */
    if (list && list->capacity)
    {
       if (list->entries)
          free(list->entries);
       free(list);
    }
 }
vc_containers_list_find_entry()
bool vc_containers_list_find_entry (const VC_CONTAINERS_LIST_T * list, void * entry)
Find an entry in the list and fill in the result. Searches for an entry in the list using the comparator and if found overwrites the one passed in with the one found.
Parameters
list The list to search.
entry An entry with enough defined to find it in the list, filled in with the rest if found.
Returns
True if found, false if not.
Definition at line 186 of file containers_list.c.
References index.
Referenced by rtp_get_parameter_u32(), and rtp_get_parameter_x32().
 {
    uint32_t index;
    size_t entry_size;
    if (!vc_containers_list_find_index(list, entry, &index))
       return false;
    entry_size = list->entry_size;
    memcpy(entry, (const char *)list->entries + entry_size * index, entry_size);
    return true;
 }
vc_containers_list_insert()
bool vc_containers_list_insert (VC_CONTAINERS_LIST_T * list, void * new_entry, bool allow_duplicates)
Insert an entry into the list.
Parameters
list The list.
new_entry The new entry to be inserted.
allow_duplicates Determines whether to insert or overwrite if there is an existing matching entry.
Returns
True if the entry has successfully been inserted, false if the list needed to be enlarged and the memory allocation failed.
Definition at line 144 of file containers_list.c.
References vc_containers_list_tag::capacity, and vc_containers_list_tag::entry_size.
 {
    uint32_t insert_idx;
    char *insert_ptr;
    size_t entry_size;
    bool match;
    if (!list || !list->capacity) return false;
    entry_size = list->entry_size;
    match = vc_containers_list_find_index(list, new_entry, &insert_idx);
    insert_ptr = (char *)list->entries + entry_size * insert_idx;
    if (!match || allow_duplicates)
    {
       /* Ensure there is space for the new entry */
       if (list->size == list->capacity)
       {
          void *new_entries = realloc(list->entries, (list->size + 1) * entry_size);
          if (!new_entries)
             return false;
          list->entries = new_entries;
          list->capacity++;
       }
       /* Move up anything above the insertion point */
       if (insert_idx < list->size)
          memmove(insert_ptr + entry_size, insert_ptr, (list->size - insert_idx) * entry_size);
       list->size++;
    }
    /* Copy in the new entry (overwriting the old one if necessary) */
    memcpy(insert_ptr, new_entry, list->entry_size);
    return true;
 }
vc_containers_list_reset()
void vc_containers_list_reset (VC_CONTAINERS_LIST_T * list)
Reset a list to be empty. Has no effect on a static list.
Parameters
list The list to be reset.
Definition at line 136 of file containers_list.c.
References vc_containers_list_tag::capacity, and vc_containers_list_tag::size.
 {
    /* Avoid trying to reset read-only lists */
    if (list && list->capacity)
       list->size = 0;
 }
vc_containers_list_validate()
void vc_containers_list_validate (const VC_CONTAINERS_LIST_T * list)
Validates a list pointer. Fields and contents of a list are checked and asserted to be correct. With a large list this may be slow, so it is recommended only to call this in debug builds.
Parameters
list The list to be validated.
Definition at line 202 of file containers_list.c.
References vc_containers_list_tag::capacity, vc_containers_list_tag::comparator, vc_containers_list_tag::entries, vc_containers_list_tag::entry_size, vc_containers_list_tag::size, and vc_container_assert.
 {
    uint32_t ii, entry_size;
    const uint8_t *entry_ptr;
    vc_container_assert(list);
    vc_container_assert(!list->capacity || list->size <= list->capacity);
    vc_container_assert(list->entry_size);
    vc_container_assert(list->comparator);
    vc_container_assert(list->entries);
    /* Check all entries are in sorted order */
    entry_ptr = (const uint8_t *)list->entries;
    entry_size = list->entry_size;
    for (ii = 1; ii < list->size; ii++)
    {
       vc_container_assert(list->comparator(entry_ptr, entry_ptr + entry_size) <= 0);
       entry_ptr += entry_size;
    }
 }