VideoCore Library: opensrc/helpers/libfdt/fdt_empty_tree.c File Reference
fdt_empty_tree.c File Reference
#include "libfdt_env.h"
#include <fdt.h>
#include <libfdt.h>
#include "libfdt_internal.h"
Functions
int fdt_create_empty_tree (void *buf, int bufsize)
Function Documentation
fdt_create_empty_tree()
int fdt_create_empty_tree (void * buf, int bufsize)
Definition at line 13 of file fdt_empty_tree.c.
References fdt_begin_node(), fdt_create(), fdt_end_node(), fdt_finish(), fdt_finish_reservemap(), and fdt_open_into().
Referenced by dtoverlay_create_dtb().
 {
     int err;
     err = fdt_create(buf, bufsize);
     if (err)
         return err;
     err = fdt_finish_reservemap(buf);
     if (err)
         return err;
     err = fdt_begin_node(buf, "");
     if (err)
         return err;
     err =  fdt_end_node(buf);
     if (err)
         return err;
     err = fdt_finish(buf);
     if (err)
         return err;
     return fdt_open_into(buf, buf, bufsize);
 }