VideoCore Library: OMX_COMPONENTTYPE Struct Reference
OMX_COMPONENTTYPE Struct Reference
OpenMAX IL component
#include <OMX_Component.h>
Public Attributes
OMX_U32 nSize
OMX_VERSIONTYPE nVersion
OMX_PTR pComponentPrivate
OMX_PTR pApplicationPrivate
OMX_ERRORTYPE(* GetComponentVersion)(OMX_IN OMX_HANDLETYPE hComponent, OMX_OUT OMX_STRING pComponentName, OMX_OUT OMX_VERSIONTYPE *pComponentVersion, OMX_OUT OMX_VERSIONTYPE *pSpecVersion, OMX_OUT OMX_UUIDTYPE *pComponentUUID)
OMX_ERRORTYPE(* SendCommand)(OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_COMMANDTYPE Cmd, OMX_IN OMX_U32 nParam1, OMX_IN OMX_PTR pCmdData)
OMX_ERRORTYPE(* GetParameter)(OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_INDEXTYPE nParamIndex, OMX_INOUT OMX_PTR pComponentParameterStructure)
OMX_ERRORTYPE(* SetParameter)(OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_INDEXTYPE nIndex, OMX_IN OMX_PTR pComponentParameterStructure)
OMX_ERRORTYPE(* GetConfig)(OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_INDEXTYPE nIndex, OMX_INOUT OMX_PTR pComponentConfigStructure)
OMX_ERRORTYPE(* SetConfig)(OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_INDEXTYPE nIndex, OMX_IN OMX_PTR pComponentConfigStructure)
OMX_ERRORTYPE(* GetExtensionIndex)(OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_STRING cParameterName, OMX_OUT OMX_INDEXTYPE *pIndexType)
OMX_ERRORTYPE(* GetState)(OMX_IN OMX_HANDLETYPE hComponent, OMX_OUT OMX_STATETYPE *pState)
OMX_ERRORTYPE(* ComponentTunnelRequest)(OMX_IN OMX_HANDLETYPE hComp, OMX_IN OMX_U32 nPort, OMX_IN OMX_HANDLETYPE hTunneledComp, OMX_IN OMX_U32 nTunneledPort, OMX_INOUT OMX_TUNNELSETUPTYPE *pTunnelSetup)
OMX_ERRORTYPE(* UseBuffer)(OMX_IN OMX_HANDLETYPE hComponent, OMX_INOUT OMX_BUFFERHEADERTYPE **ppBufferHdr, OMX_IN OMX_U32 nPortIndex, OMX_IN OMX_PTR pAppPrivate, OMX_IN OMX_U32 nSizeBytes, OMX_IN OMX_U8 *pBuffer)
OMX_ERRORTYPE(* AllocateBuffer)(OMX_IN OMX_HANDLETYPE hComponent, OMX_INOUT OMX_BUFFERHEADERTYPE **ppBuffer, OMX_IN OMX_U32 nPortIndex, OMX_IN OMX_PTR pAppPrivate, OMX_IN OMX_U32 nSizeBytes)
OMX_ERRORTYPE(* FreeBuffer)(OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_U32 nPortIndex, OMX_IN OMX_BUFFERHEADERTYPE *pBuffer)
OMX_ERRORTYPE(* EmptyThisBuffer)(OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_BUFFERHEADERTYPE *pBuffer)
OMX_ERRORTYPE(* FillThisBuffer)(OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_BUFFERHEADERTYPE *pBuffer)
OMX_ERRORTYPE(* SetCallbacks)(OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_CALLBACKTYPE *pCallbacks, OMX_IN OMX_PTR pAppData)
OMX_ERRORTYPE(* ComponentDeInit)(OMX_IN OMX_HANDLETYPE hComponent)
OMX_ERRORTYPE(* UseEGLImage)(OMX_IN OMX_HANDLETYPE hComponent, OMX_INOUT OMX_BUFFERHEADERTYPE **ppBufferHdr, OMX_IN OMX_U32 nPortIndex, OMX_IN OMX_PTR pAppPrivate, OMX_IN void *eglImage)
OMX_ERRORTYPE(* ComponentRoleEnum)(OMX_IN OMX_HANDLETYPE hComponent, OMX_OUT OMX_U8 *cRole, OMX_IN OMX_U32 nIndex)
Detailed Description
The OMX_HANDLETYPE structure defines the component handle. The component handle is used to access all of the component's public methods and also contains pointers to the component's private data area. The component handle is initialized by the OMX core (with help from the component) during the process of loading the component. After the component is successfully loaded, the application can safely access any of the component's public functions (although some may return an error because the state is inappropriate for the access).
Definition at line 307 of file OMX_Component.h.
Member Data Documentation
ComponentDeInit
OMX_ERRORTYPE(* OMX_COMPONENTTYPE::ComponentDeInit) (OMX_IN OMX_HANDLETYPE hComponent)
ComponentDeInit method is used to deinitialize the component providing a means to free any resources allocated at component initialization. NOTE: After this call the component handle is not valid for further use.
Parameters
[in] hComponent Handle of the component to be accessed. This is the component handle returned by the call to the GetHandle function.
Returns
OMX_ERRORTYPE If the command successfully executes, the return code will be OMX_ErrorNone. Otherwise the appropriate OMX error will be returned.
Definition at line 556 of file OMX_Component.h.
Referenced by OMX_FreeHandle(), and OMX_GetHandle().
ComponentRoleEnum
OMX_ERRORTYPE(* OMX_COMPONENTTYPE::ComponentRoleEnum) (OMX_IN OMX_HANDLETYPE hComponent, OMX_OUT OMX_U8 *cRole, OMX_IN OMX_U32 nIndex)
Definition at line 567 of file OMX_Component.h.
Referenced by OMX_GetComponentsOfRole().
GetComponentVersion
OMX_ERRORTYPE(* OMX_COMPONENTTYPE::GetComponentVersion) (OMX_IN OMX_HANDLETYPE hComponent, OMX_OUT OMX_STRING pComponentName, OMX_OUT OMX_VERSIONTYPE *pComponentVersion, OMX_OUT OMX_VERSIONTYPE *pSpecVersion, OMX_OUT OMX_UUIDTYPE *pComponentUUID)
refer to OMX_GetComponentVersion in OMX_core.h or the OMX IL specification for details on the GetComponentVersion method.
Definition at line 337 of file OMX_Component.h.
Referenced by vcil_in_get_component_version(), and vcil_out_create_component().
GetConfig
OMX_ERRORTYPE(* OMX_COMPONENTTYPE::GetConfig) (OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_INDEXTYPE nIndex, OMX_INOUT OMX_PTR pComponentConfigStructure)
refer to OMX_GetConfig in OMX_core.h or the OMX IL specification for details on the GetConfig method.
Definition at line 374 of file OMX_Component.h.
Referenced by vcil_in_get_config().
GetExtensionIndex
OMX_ERRORTYPE(* OMX_COMPONENTTYPE::GetExtensionIndex) (OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_STRING cParameterName, OMX_OUT OMX_INDEXTYPE *pIndexType)
refer to OMX_GetExtensionIndex in OMX_core.h or the OMX IL specification for details on the GetExtensionIndex method.
Definition at line 392 of file OMX_Component.h.
Referenced by vcil_in_get_extension_index().
GetParameter
OMX_ERRORTYPE(* OMX_COMPONENTTYPE::GetParameter) (OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_INDEXTYPE nParamIndex, OMX_INOUT OMX_PTR pComponentParameterStructure)
refer to OMX_GetParameter in OMX_core.h or the OMX IL specification for details on the GetParameter method.
Definition at line 356 of file OMX_Component.h.
Referenced by vcil_in_free_buffer(), vcil_in_get_parameter(), and vcil_in_use_buffer().
GetState
OMX_ERRORTYPE(* OMX_COMPONENTTYPE::GetState) (OMX_IN OMX_HANDLETYPE hComponent, OMX_OUT OMX_STATETYPE *pState)
refer to OMX_GetState in OMX_core.h or the OMX IL specification for details on the GetState method.
Definition at line 401 of file OMX_Component.h.
Referenced by vcil_in_get_state().
nSize
OMX_U32 OMX_COMPONENTTYPE::nSize
The size of this structure, in bytes. It is the responsibility of the allocator of this structure to fill in this value. Since this structure is allocated by the GetHandle function, this function will fill in this value.
Definition at line 313 of file OMX_Component.h.
Referenced by OMX_GetHandle().
nVersion
OMX_VERSIONTYPE OMX_COMPONENTTYPE::nVersion
nVersion is the version of the OMX specification that the structure is built against. It is the responsibility of the creator of this structure to initialize this value and every user of this structure should verify that it knows how to use the exact version of this structure found herein.
Definition at line 320 of file OMX_Component.h.
Referenced by OMX_GetHandle().
pApplicationPrivate
OMX_PTR OMX_COMPONENTTYPE::pApplicationPrivate
pApplicationPrivate is a pointer that is a parameter to the OMX_GetHandle method, and contains an application private value provided by the IL client. This application private data is returned to the IL Client by OMX in all callbacks
Definition at line 332 of file OMX_Component.h.
Referenced by OMX_FreeHandle(), and vcil_out_create_component().
pComponentPrivate
OMX_PTR OMX_COMPONENTTYPE::pComponentPrivate
pComponentPrivate is a pointer to the component private data area. This member is allocated and initialized by the component when the component is first loaded. The application should not access this data area.
Definition at line 326 of file OMX_Component.h.
Referenced by vcil_out_create_component(), vcil_out_empty_buffer_done(), vcil_out_event_handler(), and vcil_out_fill_buffer_done().
SendCommand
OMX_ERRORTYPE(* OMX_COMPONENTTYPE::SendCommand) (OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_COMMANDTYPE Cmd, OMX_IN OMX_U32 nParam1, OMX_IN OMX_PTR pCmdData)
refer to OMX_SendCommand in OMX_core.h or the OMX IL specification for details on the SendCommand method.
Definition at line 347 of file OMX_Component.h.
SetCallbacks
OMX_ERRORTYPE(* OMX_COMPONENTTYPE::SetCallbacks) (OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_CALLBACKTYPE *pCallbacks, OMX_IN OMX_PTR pAppData)
The SetCallbacks method is used by the core to specify the callback structure from the application to the component. This is a blocking call. The component will return from this call within 5 msec.
Parameters
[in] hComponent Handle of the component to be accessed. This is the component handle returned by the call to the GetHandle function.
[in] pCallbacks pointer to an OMX_CALLBACKTYPE structure used to provide the callback information to the component
[in] pAppData pointer to an application defined value. It is anticipated that the application will pass a pointer to a data structure or a "this pointer" in this area to allow the callback (in the application) to determine the context of the call
Returns
OMX_ERRORTYPE If the command successfully executes, the return code will be OMX_ErrorNone. Otherwise the appropriate OMX error will be returned.
Definition at line 540 of file OMX_Component.h.
Referenced by OMX_GetHandle().
SetConfig
OMX_ERRORTYPE(* OMX_COMPONENTTYPE::SetConfig) (OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_INDEXTYPE nIndex, OMX_IN OMX_PTR pComponentConfigStructure)
refer to OMX_SetConfig in OMX_core.h or the OMX IL specification for details on the SetConfig method.
Definition at line 383 of file OMX_Component.h.
Referenced by vcil_in_set_config().
SetParameter
OMX_ERRORTYPE(* OMX_COMPONENTTYPE::SetParameter) (OMX_IN OMX_HANDLETYPE hComponent, OMX_IN OMX_INDEXTYPE nIndex, OMX_IN OMX_PTR pComponentParameterStructure)
refer to OMX_SetParameter in OMX_core.h or the OMX IL specification for details on the SetParameter method.
Definition at line 365 of file OMX_Component.h.
Referenced by vcil_in_set_parameter().
The documentation for this struct was generated from the following file:
interface/vmcs_host/khronos/IL/OMX_Component.h