VideoCore Library: interface/vcos/vcos_thread.h File Reference
vcos_thread.h File Reference
#include "interface/vcos/vcos_types.h"
#include "vcos.h"
Macros
#define VCOS_THREAD_H
#define VCOS_AFFINITY_CPU0 _VCOS_AFFINITY_CPU0
#define VCOS_AFFINITY_CPU1 _VCOS_AFFINITY_CPU1
#define VCOS_AFFINITY_MASK _VCOS_AFFINITY_MASK
#define VCOS_AFFINITY_DEFAULT _VCOS_AFFINITY_DEFAULT
#define VCOS_AFFINITY_THISCPU _VCOS_AFFINITY_THISCPU
#define vcos_get_ms() (vcos_getmicrosecs()/1000)
#define VCOS_AFFINITY_CPU0 _VCOS_AFFINITY_CPU0
#define VCOS_AFFINITY_CPU1 _VCOS_AFFINITY_CPU1
#define VCOS_AFFINITY_MASK _VCOS_AFFINITY_MASK
#define VCOS_AFFINITY_DEFAULT _VCOS_AFFINITY_DEFAULT
#define VCOS_AFFINITY_THISCPU _VCOS_AFFINITY_THISCPU
#define vcos_get_ms() (vcos_getmicrosecs()/1000)
#define VCOS_THREAD_H
#define VCOS_AFFINITY_CPU0 _VCOS_AFFINITY_CPU0
#define VCOS_AFFINITY_CPU1 _VCOS_AFFINITY_CPU1
#define VCOS_AFFINITY_MASK _VCOS_AFFINITY_MASK
#define VCOS_AFFINITY_DEFAULT _VCOS_AFFINITY_DEFAULT
#define VCOS_AFFINITY_THISCPU _VCOS_AFFINITY_THISCPU
#define vcos_get_ms() (vcos_getmicrosecs()/1000)
Functions
VCOSPRE_ int VCOSPOST_ vcos_have_rtos (void)
VCOSPRE_ VCOS_STATUS_T VCOSPOST_ vcos_thread_create (VCOS_THREAD_T *thread, const char *name, VCOS_THREAD_ATTR_T *attrs, VCOS_THREAD_ENTRY_FN_T entry, void *arg)
VCOSPRE_ void VCOSPOST_ vcos_thread_exit (void *data)
VCOSPRE_ void VCOSPOST_ vcos_thread_join (VCOS_THREAD_T *thread, void **pData)
VCOSPRE_ VCOS_STATUS_T VCOSPOST_ vcos_thread_create_classic (VCOS_THREAD_T *thread, const char *name, void *(*entry)(void *arg), void *arg, void *stack, VCOS_UNSIGNED stacksz, VCOS_UNSIGNED priaff, VCOS_UNSIGNED timeslice, VCOS_UNSIGNED autostart)
Create a thread using an API similar to the one "traditionally" used under Nucleus.
VCOS_INLINE_DECL void vcos_thread_set_priority (VCOS_THREAD_T *thread, VCOS_UNSIGNED pri)
Set a thread's priority.
VCOS_INLINE_DECL VCOS_THREAD_T * vcos_thread_current (void)
Return the currently executing thread.
VCOS_INLINE_DECL VCOS_UNSIGNED vcos_thread_get_priority (VCOS_THREAD_T *thread)
Return the thread's priority.
VCOS_INLINE_DECL VCOS_UNSIGNED vcos_thread_get_affinity (VCOS_THREAD_T *thread)
Return the thread's cpu affinity.
VCOS_INLINE_DECL void vcos_thread_set_affinity (VCOS_THREAD_T *thread, VCOS_UNSIGNED affinity)
Set the thread's cpu affinity.
VCOS_INLINE_DECL int vcos_in_interrupt (void)
Query whether we are in an interrupt.
VCOS_INLINE_DECL void vcos_sleep (uint32_t ms)
Sleep a while.
VCOS_INLINE_DECL uint32_t vcos_getmicrosecs (void)
Return the value of the hardware microsecond counter.
VCOS_INLINE_DECL uint64_t vcos_getmicrosecs64 (void)
VCOS_INLINE_DECL VCOS_UNSIGNED vcos_process_id_current (void)
Return a unique identifier for the current process.
VCOS_INLINE_DECL void vcos_thread_relinquish (void)
VCOSPRE_ const char *VCOSPOST_ vcos_thread_get_name (const VCOS_THREAD_T *thread)
VCOS_INLINE_DECL VCOS_UNSIGNED vcos_change_preemption (VCOS_UNSIGNED pe)
VCOS_INLINE_DECL int vcos_thread_running (VCOS_THREAD_T *thread)
VCOS_INLINE_DECL void vcos_thread_resume (VCOS_THREAD_T *thread)
void _vcos_task_timer_set (void(*pfn)(void *), void *, VCOS_UNSIGNED ms)
void _vcos_task_timer_cancel (void)
Detailed Description
Threads
Under Nucleus, a thread is created by NU_Create_Task, passing in the stack and various other parameters. To stop the thread, NU_Terminate_Thread() and NU_Delete_Thread() are called.
Unfortunately it's not possible to emulate this API under some fairly common operating systems. Under Windows you can't pass in the stack, and you can't safely terminate a thread.
Therefore, an API which is similar to the pthreads API is used instead. This API can (mostly) be emulated under all interesting operating systems.
Obviously this makes the code somewhat more complicated on VideoCore than it would otherwise be - we end up with an extra mutex per thread, and some code that waits for it. The benefit is that we have a single way of creating threads that works consistently on all platforms (apart from stack supplying).
Stack
It's still not possible to pass in the stack address, but this can be made much more obvious in the API: the relevant function is missing and the CPP symbol VCOS_CAN_SET_STACK_ADDR is zero rather than one.
Creating a thread
The simplest way to create a thread is with vcos_thread_create() passing in a NULL thread parameter argument. To wait for the thread to exit, call vcos_thread_join().
Backward compatibility
To ease migration, a "classic" thread creation API is provided for code that used to make use of Nucleus, vcos_thread_create_classic(). The arguments are not exactly the same, as the PREEMPT parameter is dropped.
Definition in file vcos_thread.h.
Macro Definition Documentation
VCOS_AFFINITY_CPU0 [1/3]
#define VCOS_AFFINITY_CPU0 _VCOS_AFFINITY_CPU0
VCOS_AFFINITY_CPU0 [2/3]
#define VCOS_AFFINITY_CPU0 _VCOS_AFFINITY_CPU0
Definition at line 83 of file khrn_misc.h.
VCOS_AFFINITY_CPU0 [3/3]
#define VCOS_AFFINITY_CPU0 _VCOS_AFFINITY_CPU0
VCOS_AFFINITY_CPU1 [1/3]
#define VCOS_AFFINITY_CPU1 _VCOS_AFFINITY_CPU1
Definition at line 84 of file khrn_misc.h.
VCOS_AFFINITY_CPU1 [2/3]
#define VCOS_AFFINITY_CPU1 _VCOS_AFFINITY_CPU1
VCOS_AFFINITY_CPU1 [3/3]
#define VCOS_AFFINITY_CPU1 _VCOS_AFFINITY_CPU1
VCOS_AFFINITY_DEFAULT [1/3]
#define VCOS_AFFINITY_DEFAULT _VCOS_AFFINITY_DEFAULT
VCOS_AFFINITY_DEFAULT [2/3]
#define VCOS_AFFINITY_DEFAULT _VCOS_AFFINITY_DEFAULT
VCOS_AFFINITY_DEFAULT [3/3]
#define VCOS_AFFINITY_DEFAULT _VCOS_AFFINITY_DEFAULT
Definition at line 86 of file khrn_misc.h.
VCOS_AFFINITY_MASK [1/3]
#define VCOS_AFFINITY_MASK _VCOS_AFFINITY_MASK
VCOS_AFFINITY_MASK [2/3]
#define VCOS_AFFINITY_MASK _VCOS_AFFINITY_MASK
Definition at line 85 of file khrn_misc.h.
VCOS_AFFINITY_MASK [3/3]
#define VCOS_AFFINITY_MASK _VCOS_AFFINITY_MASK
VCOS_AFFINITY_THISCPU [1/3]
#define VCOS_AFFINITY_THISCPU _VCOS_AFFINITY_THISCPU
VCOS_AFFINITY_THISCPU [2/3]
#define VCOS_AFFINITY_THISCPU _VCOS_AFFINITY_THISCPU
Definition at line 87 of file khrn_misc.h.
VCOS_AFFINITY_THISCPU [3/3]
#define VCOS_AFFINITY_THISCPU _VCOS_AFFINITY_THISCPU
vcos_get_ms [1/3]
#define vcos_get_ms () (vcos_getmicrosecs()/1000)
Definition at line 223 of file khrn_misc.h.
vcos_get_ms [2/3]
#define vcos_get_ms () (vcos_getmicrosecs()/1000)
vcos_get_ms [3/3]
#define vcos_get_ms () (vcos_getmicrosecs()/1000)
VCOS_THREAD_H [1/2]
#define VCOS_THREAD_H
VCOS_THREAD_H [2/2]
#define VCOS_THREAD_H
Function Documentation
_vcos_task_timer_cancel()
void _vcos_task_timer_cancel (void)
Definition at line 506 of file vcos_pthreads.c.
References NULL, VCOS_THREAD_T::orig_task_timer_expiration_routine, VCOS_THREAD_T::task_timer, VCOS_THREAD_T::task_timer_created, vcos_thread_current(), and vcos_timer_cancel().
 {
    VCOS_THREAD_T *thread = vcos_thread_current();
    if (thread == NULL || !thread->task_timer_created)
      return;
    vcos_timer_cancel(&thread->task_timer);
    thread->orig_task_timer_expiration_routine = NULL;
 }
_vcos_task_timer_set()
void _vcos_task_timer_set (void(*)(void *) pfn, void * , VCOS_UNSIGNED ms)
Definition at line 482 of file vcos_pthreads.c.
References NULL, VCOS_THREAD_T::orig_task_timer_expiration_routine, VCOS_THREAD_T::task_timer, VCOS_THREAD_T::task_timer_created, vcos_assert, vcos_thread_current(), and vcos_timer_create().
Referenced by vcos_generic_event_flags_get().
 {
    VCOS_THREAD_T *thread = vcos_thread_current();
    if (thread == NULL)
       return;
    vcos_assert(thread->orig_task_timer_expiration_routine == NULL);
    if (!thread->task_timer_created)
    {
       VCOS_STATUS_T st = vcos_timer_create(&thread->task_timer, NULL,
                                 _task_timer_expiration_routine, thread);
       (void)st;
       vcos_assert(st == VCOS_SUCCESS);
       thread->task_timer_created = 1;
    }
    thread->orig_task_timer_expiration_routine = pfn;
    thread->orig_task_timer_context = cxt;
    vcos_timer_set(&thread->task_timer, ms);
 }
vcos_change_preemption()
VCOS_INLINE_DECL VCOS_UNSIGNED vcos_change_preemption (VCOS_UNSIGNED pe)
Change preemption. This is almost certainly not what you want, as it won't work reliably in a multicore system: although you can affect the preemption on this core, you won't affect what's happening on the other core(s).
It's mainly here to ease migration. If you're using it in new code, you probably need to think again.
Parameters
pe New preemption, VCOS_PREEMPT or VCOS_NO_PREEMPT
Returns
Old value of preemption.
vcos_getmicrosecs()
VCOS_INLINE_DECL uint32_t vcos_getmicrosecs (void)
Return the value of the hardware microsecond counter.
Referenced by mmal_clock_media_time_set(), mmal_connection_create(), mmal_connection_disable(), mmal_connection_enable(), mmal_wrapper_create(), mmal_wrapper_port_disable(), mmal_wrapper_port_enable(), mmalplay_destroy(), and mmalplay_play().
vcos_getmicrosecs64()
VCOS_INLINE_DECL uint64_t vcos_getmicrosecs64 (void)
vcos_have_rtos()
VCOSPRE_ int VCOSPOST_ vcos_have_rtos (void)
Report whether or not we have an RTOS at all, and hence the ability to create threads.
Definition at line 532 of file vcos_pthreads.c.
 {
    return 1;
 }
vcos_in_interrupt()
VCOS_INLINE_DECL int vcos_in_interrupt (void)
Query whether we are in an interrupt.
Returns
1 if in interrupt context.
vcos_process_id_current()
VCOS_INLINE_DECL VCOS_UNSIGNED vcos_process_id_current (void)
Return a unique identifier for the current process.
Referenced by _vcos_log_platform_init(), wfc_stream_register(), and wfc_stream_unregister().
vcos_sleep()
VCOS_INLINE_DECL void vcos_sleep (uint32_t ms)
Sleep a while.
Parameters
ms Number of milliseconds to sleep for
This may actually sleep a whole number of ticks.
Referenced by platform_wfc_bounce_thread(), and vc_gencmd_until().
vcos_thread_create()
VCOSPRE_ VCOS_STATUS_T VCOSPOST_ vcos_thread_create (VCOS_THREAD_T * thread, const char * name, VCOS_THREAD_ATTR_T * attrs, VCOS_THREAD_ENTRY_FN_T entry, void * arg)
Create a thread. It must be cleaned up by calling vcos_thread_join().
Parameters
thread Filled in on return with thread
name A name for the thread. May be the empty string.
attrs Attributes; default attributes will be used if this is NULL.
entry Entry point.
arg Argument passed to the entry point.
Definition at line 165 of file vcos_pthreads.c.
Referenced by mmal_component_action_register(), mmal_graph_enable(), raspitex_start(), and vcos_thread_create_classic().
 {
    VCOS_STATUS_T st;
    pthread_attr_t pt_attrs;
    VCOS_THREAD_ATTR_T *local_attrs = attrs ? attrs : &default_attrs;
    int rc;
    vcos_assert(thread);
    memset(thread, 0, sizeof(VCOS_THREAD_T));
    rc = pthread_attr_init(&pt_attrs);
    if (rc < 0)
       return VCOS_ENOMEM;
    st = vcos_semaphore_create(&thread->suspend, NULL, 0);
    if (st != VCOS_SUCCESS)
    {
       pthread_attr_destroy(&pt_attrs);
       return st;
    }
    pthread_attr_setstacksize(&pt_attrs, local_attrs->ta_stacksz);
 #if VCOS_CAN_SET_STACK_ADDR
    if (local_attrs->ta_stackaddr)
    {
       pthread_attr_setstackaddr(&pt_attrs, local_attrs->ta_stackaddr);
    }
 #else
    vcos_demand(local_attrs->ta_stackaddr == 0);
 #endif
    /* pthread_attr_setpriority(&pt_attrs, local_attrs->ta_priority); */
    vcos_assert(local_attrs->ta_stackaddr == 0); /* Not possible */
    thread->entry = entry;
    thread->arg = arg;
    thread->legacy = local_attrs->legacy;
    strncpy(thread->name, name, sizeof(thread->name));
    thread->name[sizeof(thread->name)-1] = '\0';
    memset(thread->at_exit, 0, sizeof(thread->at_exit));
    rc = pthread_create(&thread->thread, &pt_attrs, vcos_thread_entry, thread);
    pthread_attr_destroy(&pt_attrs);
    if (rc < 0)
    {
       vcos_semaphore_delete(&thread->suspend);
       return VCOS_ENOMEM;
    }
    else
    {
       return VCOS_SUCCESS;
    }
 }
vcos_thread_create_classic()
VCOSPRE_ VCOS_STATUS_T VCOSPOST_ vcos_thread_create_classic (VCOS_THREAD_T * thread, const char * name, void *(*)(void *arg) entry, void * arg, void * stack, VCOS_UNSIGNED stacksz, VCOS_UNSIGNED priaff, VCOS_UNSIGNED timeslice, VCOS_UNSIGNED autostart)
Create a thread using an API similar to the one "traditionally" used under Nucleus.
This creates a thread which must be cleaned up by calling vcos_thread_join(). The thread cannot be simply terminated (as in Nucleus and ThreadX) as thread termination is not universally supported.
Parameters
thread Filled in with thread instance
name An optional name for the thread. NULL or "" may be used (but a name will aid in debugging).
entry Entry point
arg A single argument passed to the entry point function
stack Pointer to stack address
stacksz Size of stack in bytes
priaff Priority of task, between VCOS_PRI_LOW and VCOS_PRI_HIGH, ORed with the CPU affinity
autostart If non-zero the thread will start immediately.
timeslice Timeslice (system ticks) for this thread.
See also
vcos_thread_terminate vcos_thread_delete
Definition at line 234 of file vcos_pthreads.c.
References _VCOS_AFFINITY_MASK, VCOS_CAN_SET_STACK_ADDR, vcos_thread_attr_init(), vcos_thread_attr_setaffinity(), vcos_thread_attr_setpriority(), vcos_thread_attr_setstacksize(), vcos_thread_create(), and void().
 {
    VCOS_THREAD_ATTR_T attrs;
    vcos_thread_attr_init(&attrs);
    vcos_thread_attr_setstacksize(&attrs, stacksz);
    vcos_thread_attr_setpriority(&attrs, priaff & ~_VCOS_AFFINITY_MASK);
    vcos_thread_attr_setaffinity(&attrs, priaff & _VCOS_AFFINITY_MASK);
    (void)timeslice;
    (void)autostart;
    if (VCOS_CAN_SET_STACK_ADDR)
    {
       vcos_thread_attr_setstack(&attrs, stack, stacksz);
    }
    return vcos_thread_create(thread, name, &attrs, entry, arg);
 }
vcos_thread_current()
VCOS_INLINE_DECL VCOS_THREAD_T* vcos_thread_current (void)
Return the currently executing thread.
Referenced by _vcos_task_timer_cancel(), _vcos_task_timer_set(), ilcs_thread_current(), vc_hostfs_init(), vcos_generic_event_flags_get(), vcos_thread_at_exit(), and vcos_thread_exit().
vcos_thread_exit()
VCOSPRE_ void VCOSPOST_ vcos_thread_exit (void * data)
Exit the thread from within the thread function itself. Resources must still be cleaned up via a call to thread_join().
The thread can also be terminated by simply exiting the thread function.
Parameters
data Data passed to thread_join. May be NULL.
Definition at line 441 of file vcos_pthreads.c.
References VCOS_THREAD_T::dummy, NULL, vcos_free(), and vcos_thread_current().
 {
    VCOS_THREAD_T *thread = vcos_thread_current();
    if ( thread && thread->dummy )
    {
       vcos_free ( (void*) thread );
       thread = NULL;
    }
    pthread_exit(arg);
 }
vcos_thread_get_affinity()
VCOS_INLINE_DECL VCOS_UNSIGNED vcos_thread_get_affinity (VCOS_THREAD_T * thread)
Return the thread's cpu affinity.
vcos_thread_get_name()
VCOSPRE_ const char* VCOSPOST_ vcos_thread_get_name (const VCOS_THREAD_T * thread)
Return the name of the given thread.
Definition at line 537 of file vcos_pthreads.c.
References __attribute__(), VCOS_THREAD_T::name, and vcos_backtrace_self().
Referenced by vc_hostfs_init().
 {
    return thread->name;
 }
vcos_thread_get_priority()
VCOS_INLINE_DECL VCOS_UNSIGNED vcos_thread_get_priority (VCOS_THREAD_T * thread)
Return the thread's priority.
vcos_thread_join()
VCOSPRE_ void VCOSPOST_ vcos_thread_join (VCOS_THREAD_T * thread, void ** pData)
Wait for a thread to terminate and then clean up its resources.
Parameters
thread Thread to wait for
pData Updated to point at data provided in vcos_thread_exit or exit code of thread function.
Definition at line 227 of file vcos_pthreads.c.
References VCOS_THREAD_T::thread.
Referenced by mmal_component_action_deregister(), OMX_FreeHandle(), and raspitex_stop().
 {
    pthread_join(thread->thread, pData);
    vcos_thread_cleanup(thread);
 }
vcos_thread_relinquish()
VCOS_INLINE_DECL void vcos_thread_relinquish (void)
Relinquish this time slice.
vcos_thread_resume()
VCOS_INLINE_DECL void vcos_thread_resume (VCOS_THREAD_T * thread)
Resume a thread.
Parameters
thread thread to resume
vcos_thread_running()
VCOS_INLINE_DECL int vcos_thread_running (VCOS_THREAD_T * thread)
Is a thread still running, or has it exited?
Note: this exists for some fairly scary code in the video codec tests. Don't try to use it for anything else, as it may well not do what you expect.
Parameters
thread thread to query
Returns
non-zero if thread is running, or zero if it has exited.
vcos_thread_set_affinity()
VCOS_INLINE_DECL void vcos_thread_set_affinity (VCOS_THREAD_T * thread, VCOS_UNSIGNED affinity)
Set the thread's cpu affinity.
vcos_thread_set_priority()
VCOS_INLINE_DECL void vcos_thread_set_priority (VCOS_THREAD_T * thread, VCOS_UNSIGNED pri)
Set a thread's priority.
Set the priority for a thread.
Parameters
thread The thread
pri Thread priority in VCOS_PRI_MASK bits; affinity in VCOS_AFFINITY_MASK bits.