VideoCore Library: interface/khronos/egl/egl_client_cr.c File Reference
egl_client_cr.c File Reference
Functions
EGLAPI EGLint EGLAPIENTRY eglGetError (void)
EGLAPI EGLDisplay EGLAPIENTRY eglGetDisplay (EGLNativeDisplayType display_id)
EGLAPI EGLBoolean EGLAPIENTRY eglGetConfigs (EGLDisplay dpy, EGLConfig *configs, EGLint config_size, EGLint *num_config)
EGLAPI EGLBoolean EGLAPIENTRY eglChooseConfig (EGLDisplay dpy, const EGLint *attrib_list, EGLConfig *configs, EGLint config_size, EGLint *num_config)
EGLAPI EGLBoolean EGLAPIENTRY eglGetConfigAttrib (EGLDisplay dpy, EGLConfig config, EGLint attribute, EGLint *value)
Function Documentation
eglChooseConfig()
EGLAPI EGLBoolean EGLAPIENTRY eglChooseConfig (EGLDisplay dpy, const EGLint * attrib_list, EGLConfig * configs, EGLint config_size, EGLint * num_config)
Definition at line 474 of file egl_client_cr.c.
Referenced by init().
 {
    return choose_config(dpy, attrib_list, configs, config_size, num_config, false);
 }
eglGetConfigAttrib()
EGLAPI EGLBoolean EGLAPIENTRY eglGetConfigAttrib (EGLDisplay dpy, EGLConfig config, EGLint attribute, EGLint * value)
Definition at line 552 of file egl_client_cr.c.
 {
    CLIENT_THREAD_STATE_T *thread;
    CLIENT_PROCESS_STATE_T *process;
    EGLBoolean result;
    if (CLIENT_LOCK_AND_GET_STATES(dpy, &thread, &process))
    {
       if (!value) {
          thread->error = EGL_BAD_PARAMETER;
          result = EGL_FALSE;
       } else if (egl_config_to_id(config) < 0 || egl_config_to_id(config) >= EGL_MAX_CONFIGS) {
          thread->error = EGL_BAD_CONFIG;
          result = EGL_FALSE;
       } else if (!egl_config_get_attrib(egl_config_to_id(config), attribute, value)) {
          thread->error = EGL_BAD_ATTRIBUTE;
          result = EGL_FALSE;
       } else {
          thread->error = EGL_SUCCESS;
          result = EGL_TRUE;
       }
       CLIENT_UNLOCK();
    }
    else
       result = EGL_FALSE;
    return result;
 }
eglGetConfigs()
EGLAPI EGLBoolean EGLAPIENTRY eglGetConfigs (EGLDisplay dpy, EGLConfig * configs, EGLint config_size, EGLint * num_config)
Definition at line 235 of file egl_client_cr.c.
 {
    CLIENT_THREAD_STATE_T *thread;
    CLIENT_PROCESS_STATE_T *process;
    EGLBoolean result;
    if (CLIENT_LOCK_AND_GET_STATES(dpy, &thread, &process))
    {
       if (!num_config) {
          thread->error = EGL_BAD_PARAMETER;
          result = EGL_FALSE;
       } else if (!configs) {
          thread->error = EGL_SUCCESS;
          *num_config = EGL_MAX_CONFIGS;
          result = EGL_TRUE;
       } else {
          int i;
          for (i = 0; i < EGL_MAX_CONFIGS && i < config_size; i++)
             configs[i] = egl_config_from_id(i);
          thread->error = EGL_SUCCESS;
          *num_config = i;
          result = EGL_TRUE;
       }
       CLIENT_UNLOCK();
    }
    else
       result = EGL_FALSE;
    return result;
 }
eglGetDisplay()
EGLAPI EGLDisplay EGLAPIENTRY eglGetDisplay (EGLNativeDisplayType display_id)
Definition at line 170 of file egl_client_cr.c.
Referenced by init().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_CHECK_THREAD_STATE();
    if (thread)
       thread->error = EGL_SUCCESS;
    return khrn_platform_set_display_id(display_id);
 }
eglGetError()
EGLAPI EGLint EGLAPIENTRY eglGetError (void)
Definition at line 110 of file egl_client_cr.c.
Referenced by deinit(), init(), and render().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_CHECK_THREAD_STATE();
    if (thread)
    {
       EGLint result;
       vcos_assert( thread != NULL );
       result = thread->error;
       thread->error = EGL_SUCCESS;
       return result;
    }
    else
       return EGL_SUCCESS;
 }