VideoCore Library: interface/mmal/core/mmal_component_private.h File Reference
mmal_component_private.h File Reference
#include "mmal.h"
#include "mmal_component.h"
Classes
struct MMAL_COMPONENT_PRIVATE_T
Macros
#define MMAL_VIDEO_DECODE "video_decode"
#define MMAL_VIDEO_ENCODE "video_encode"
#define MMAL_VIDEO_RENDER "video_render"
#define MMAL_AUDIO_DECODE "audio_decode"
#define MMAL_AUDIO_ENCODE "audio_encode"
#define MMAL_AUDIO_RENDER "audio_render"
#define MMAL_CAMERA "camera"
#define MMAL_CONSTRUCTOR(func) void func(void)
#define MMAL_DESTRUCTOR(func) void func(void)
Typedefs
typedef MMAL_STATUS_T(* MMAL_COMPONENT_SUPPLIER_FUNCTION_T) (const char *name, MMAL_COMPONENT_T *component)
Functions
MMAL_STATUS_T mmal_component_parameter_set (MMAL_PORT_T *control_port, const MMAL_PARAMETER_HEADER_T *param)
MMAL_STATUS_T mmal_component_parameter_get (MMAL_PORT_T *control_port, MMAL_PARAMETER_HEADER_T *param)
MMAL_STATUS_T mmal_component_action_register (MMAL_COMPONENT_T *component, void(*pf_action)(MMAL_COMPONENT_T *))
MMAL_STATUS_T mmal_component_action_deregister (MMAL_COMPONENT_T *component)
MMAL_STATUS_T mmal_component_action_trigger (MMAL_COMPONENT_T *component)
MMAL_STATUS_T mmal_component_action_lock (MMAL_COMPONENT_T *component)
MMAL_STATUS_T mmal_component_action_unlock (MMAL_COMPONENT_T *component)
MMAL_STATUS_T mmal_component_create_with_constructor (const char *name, MMAL_STATUS_T(*constructor)(const char *name, MMAL_COMPONENT_T *), struct MMAL_COMPONENT_MODULE_T *constructor_private, MMAL_COMPONENT_T **component)
void mmal_component_supplier_register (const char *prefix, MMAL_COMPONENT_SUPPLIER_FUNCTION_T create_fn)
Macro Definition Documentation
MMAL_AUDIO_DECODE
#define MMAL_AUDIO_DECODE "audio_decode"
Definition at line 38 of file mmal_component_private.h.
MMAL_AUDIO_ENCODE
#define MMAL_AUDIO_ENCODE "audio_encode"
Definition at line 39 of file mmal_component_private.h.
MMAL_AUDIO_RENDER
#define MMAL_AUDIO_RENDER "audio_render"
Definition at line 40 of file mmal_component_private.h.
MMAL_CAMERA
#define MMAL_CAMERA "camera"
Definition at line 41 of file mmal_component_private.h.
MMAL_CONSTRUCTOR
#define MMAL_CONSTRUCTOR (func) void func(void)
Definition at line 47 of file mmal_component_private.h.
MMAL_DESTRUCTOR
#define MMAL_DESTRUCTOR (func) void func(void)
Definition at line 48 of file mmal_component_private.h.
MMAL_VIDEO_DECODE
#define MMAL_VIDEO_DECODE "video_decode"
Definition at line 35 of file mmal_component_private.h.
MMAL_VIDEO_ENCODE
#define MMAL_VIDEO_ENCODE "video_encode"
Definition at line 36 of file mmal_component_private.h.
MMAL_VIDEO_RENDER
#define MMAL_VIDEO_RENDER "video_render"
Definition at line 37 of file mmal_component_private.h.
Typedef Documentation
MMAL_COMPONENT_SUPPLIER_FUNCTION_T
typedef MMAL_STATUS_T(* MMAL_COMPONENT_SUPPLIER_FUNCTION_T) (const char *name, MMAL_COMPONENT_T *component)
Prototype used by components to register themselves to the supplier.
Definition at line 139 of file mmal_component_private.h.
Function Documentation
mmal_component_action_deregister()
MMAL_STATUS_T mmal_component_action_deregister (MMAL_COMPONENT_T * component)
De-registers the current action registered with the core.
Parameters
component component de-registering the action.
Returns
MMAL_SUCCESS or another status on error.
De-registers the current action with the core
Definition at line 609 of file mmal_component.c.
References MMAL_EINVAL, MMAL_SUCCESS, NULL, MMAL_COMPONENT_T::priv, vcos_event_delete(), vcos_event_signal(), vcos_mutex_delete(), and vcos_thread_join().
 {
    MMAL_COMPONENT_CORE_PRIVATE_T *private = (MMAL_COMPONENT_CORE_PRIVATE_T *)component->priv;
    if (!private->pf_action)
       return MMAL_EINVAL;
    private->action_quit = 1;
    vcos_event_signal(&private->action_event);
    vcos_thread_join(&private->action_thread, NULL);
    vcos_event_delete(&private->action_event);
    vcos_mutex_delete(&private->action_mutex);
    private->pf_action = NULL;
    private->action_quit = 0;
    return MMAL_SUCCESS;
 }
mmal_component_action_lock()
MMAL_STATUS_T mmal_component_action_lock (MMAL_COMPONENT_T * component)
Lock an action to prevent it from running. Allows a component to make sure no action is running while the lock is taken.
Parameters
component component.
Returns
MMAL_SUCCESS or another status on error.
Lock an action to prevent it from running
Definition at line 639 of file mmal_component.c.
References MMAL_EINVAL, MMAL_SUCCESS, MMAL_COMPONENT_T::priv, and vcos_mutex_lock().
Referenced by mmal_port_flush().
 {
    MMAL_COMPONENT_CORE_PRIVATE_T *private = (MMAL_COMPONENT_CORE_PRIVATE_T *)component->priv;
    if (!private->pf_action)
       return MMAL_EINVAL;
    vcos_mutex_lock(&private->action_mutex);
    return MMAL_SUCCESS;
 }
mmal_component_action_register()
MMAL_STATUS_T mmal_component_action_register (MMAL_COMPONENT_T * component, void(*)(MMAL_COMPONENT_T *) pf_action)
Registers an action with the core. The MMAL core allows components to register an action which will be run from a separate thread context when the action is explicitly triggered by the component.
Parameters
component component registering the action.
action action to register.
Returns
MMAL_SUCCESS or another status on error.
Registers an action with the core
Definition at line 571 of file mmal_component.c.
References MMAL_EINVAL, MMAL_ENOMEM, MMAL_COMPONENT_T::name, MMAL_COMPONENT_T::priv, vcos_event_create(), vcos_event_delete(), vcos_mutex_create(), VCOS_SUCCESS, vcos_thread_attr_init(), vcos_thread_attr_setpriority(), and vcos_thread_create().
 {
    MMAL_COMPONENT_CORE_PRIVATE_T *private = (MMAL_COMPONENT_CORE_PRIVATE_T *)component->priv;
    VCOS_THREAD_ATTR_T attrs;
    VCOS_STATUS_T status;
    if (private->pf_action)
       return MMAL_EINVAL;
    status = vcos_event_create(&private->action_event, component->name);
    if (status != VCOS_SUCCESS)
       return MMAL_ENOMEM;
    status = vcos_mutex_create(&private->action_mutex, component->name);
    if (status != VCOS_SUCCESS)
    {
       vcos_event_delete(&private->action_event);
       return MMAL_ENOMEM;
    }
    vcos_thread_attr_init(&attrs);
    vcos_thread_attr_setpriority(&attrs,
                                 private->private.priority);
    status = vcos_thread_create(&private->action_thread, component->name, &attrs,
                                mmal_component_action_thread_func, component);
    if (status != VCOS_SUCCESS)
    {
       vcos_mutex_delete(&private->action_mutex);
       vcos_event_delete(&private->action_event);
       return MMAL_ENOMEM;
    }
    private->pf_action = pf_action;
    return MMAL_SUCCESS;
 }
mmal_component_action_trigger()
MMAL_STATUS_T mmal_component_action_trigger (MMAL_COMPONENT_T * component)
Triggers a registered action. Explicitly triggers an action registered by a component.
Parameters
component component on which to trigger the action.
Returns
MMAL_SUCCESS or another status on error.
Triggers a registered action
Definition at line 627 of file mmal_component.c.
References MMAL_EINVAL, MMAL_SUCCESS, MMAL_COMPONENT_T::priv, and vcos_event_signal().
Referenced by AmcHandler::onMessageReceived().
 {
    MMAL_COMPONENT_CORE_PRIVATE_T *private = (MMAL_COMPONENT_CORE_PRIVATE_T *)component->priv;
    if (!private->pf_action)
       return MMAL_EINVAL;
    vcos_event_signal(&private->action_event);
    return MMAL_SUCCESS;
 }
mmal_component_action_unlock()
MMAL_STATUS_T mmal_component_action_unlock (MMAL_COMPONENT_T * component)
Unlock an action to allow it to run again.
Parameters
component component.
Returns
MMAL_SUCCESS or another status on error.
Unlock an action to allow it to run again
Definition at line 651 of file mmal_component.c.
References MMAL_EINVAL, MMAL_SUCCESS, MMAL_COMPONENT_T::priv, and vcos_mutex_unlock().
Referenced by mmal_port_flush().
 {
    MMAL_COMPONENT_CORE_PRIVATE_T *private = (MMAL_COMPONENT_CORE_PRIVATE_T *)component->priv;
    if (!private->pf_action)
       return MMAL_EINVAL;
    vcos_mutex_unlock(&private->action_mutex);
    return MMAL_SUCCESS;
 }
mmal_component_create_with_constructor()
MMAL_STATUS_T mmal_component_create_with_constructor (const char * name, MMAL_STATUS_T(*)(const char *name, MMAL_COMPONENT_T *) constructor, struct MMAL_COMPONENT_MODULE_T * constructor_private, MMAL_COMPONENT_T ** component)
Create an instance of a component given a constructor for the component. This allows the creation of client-side components which haven't been registered with the core. See mmal_component_create for the public interface used to create components.
Parameters
name name assigned to the component by the client
constructor constructor function for the component
constructor_private private data for the constructor
component returned component
Returns
MMAL_SUCCESS on success
Create an instance of a component
Definition at line 222 of file mmal_component.c.
References LOG_TRACE.
Referenced by mmal_graph_build().
 {
    LOG_TRACE("%s", name);
    return mmal_component_create_core(name, constructor, constructor_private, component);
 }
mmal_component_parameter_get()
MMAL_STATUS_T mmal_component_parameter_get (MMAL_PORT_T * control_port, MMAL_PARAMETER_HEADER_T * param)
Get a generic component control parameter.
Parameters
contorl_port control port of component from which to get the parameter.
param parameter to be retrieved.
Returns
MMAL_SUCCESS or another status on error.
Definition at line 475 of file mmal_component.c.
References MMAL_PARAMETER_HEADER_T::id, LOG_ERROR, MMAL_ENOSYS, and void().
 {
    (void)control_port;
    (void)param;
    /* No generic component control parameters */
    LOG_ERROR("parameter id 0x%08x not supported", param->id);
    return MMAL_ENOSYS;
 }
mmal_component_parameter_set()
MMAL_STATUS_T mmal_component_parameter_set (MMAL_PORT_T * control_port, const MMAL_PARAMETER_HEADER_T * param)
Set a generic component control parameter.
Parameters
control_port control port of component on which to set the parameter.
param parameter to be set.
Returns
MMAL_SUCCESS or another status on error.
Definition at line 465 of file mmal_component.c.
References MMAL_PARAMETER_HEADER_T::id, LOG_ERROR, MMAL_ENOSYS, and void().
 {
    (void)control_port;
    (void)param;
    /* No generic component control parameters */
    LOG_ERROR("parameter id 0x%08x not supported", param->id);
    return MMAL_ENOSYS;
 }
mmal_component_supplier_register()
void mmal_component_supplier_register (const char * prefix, MMAL_COMPONENT_SUPPLIER_FUNCTION_T create_fn)
Register a component with the mmal component supplier.
Parameters
prefix prefix for this supplier, e.g. "VC"
create_fn function which will instantiate a component given a name.
Definition at line 746 of file mmal_component.c.
References MMAL_COMPONENT_SUPPLIER_T::create, LOG_TRACE, MMAL_COMPONENT_SUPPLIER_T::next, NULL, MMAL_COMPONENT_SUPPLIER_T::prefix, SUPPLIER_PREFIX_LEN, vcos_calloc(), and vcos_verify.
Referenced by mmal_register_component_aaf_audio(), mmal_register_component_aggregator(), mmal_register_component_android_media_codec(), mmal_register_component_artificial_camera(), mmal_register_component_avcodec(), mmal_register_component_avcodec_audio(), mmal_register_component_clock(), mmal_register_component_container_reader(), mmal_register_component_container_writer(), mmal_register_component_copy(), mmal_register_component_null_sink(), mmal_register_component_passthrough(), mmal_register_component_scheduler(), mmal_register_component_sdl(), mmal_register_component_sdl_audio(), mmal_register_component_spdif(), mmal_register_component_splitter(), and mmal_register_component_videocore().
 {
    MMAL_COMPONENT_SUPPLIER_T *supplier = vcos_calloc(1,sizeof(*supplier),NULL);
    LOG_TRACE("prefix %s fn %p", (prefix ? prefix : "NULL"), create_fn);
    if (vcos_verify(supplier))
    {
       supplier->create = create_fn;
       strncpy(supplier->prefix, prefix, SUPPLIER_PREFIX_LEN);
       supplier->prefix[SUPPLIER_PREFIX_LEN-1] = '\0';
       supplier->next = suppliers;
       suppliers = supplier;
    }
    else
    {
       LOG_ERROR("no memory for supplier registry entry");
    }
 }