VideoCore Library: interface/vcos/generic/vcos_generic_event_flags.h File Reference
vcos_generic_event_flags.h File Reference
#include "interface/vcos/vcos_types.h"
Classes
struct VCOS_EVENT_FLAGS_T
Macros
#define VCOS_OR 1
#define VCOS_AND 2
#define VCOS_CONSUME 4
#define VCOS_OR_CONSUME (VCOS_OR | VCOS_CONSUME)
#define VCOS_AND_CONSUME (VCOS_AND | VCOS_CONSUME)
#define VCOS_EVENT_FLAG_OP_MASK (VCOS_OR|VCOS_AND)
Typedefs
typedef struct VCOS_EVENT_FLAGS_T VCOS_EVENT_FLAGS_T
Functions
VCOSPRE_ VCOS_STATUS_T VCOSPOST_ vcos_generic_event_flags_create (VCOS_EVENT_FLAGS_T *flags, const char *name)
VCOSPRE_ void VCOSPOST_ vcos_generic_event_flags_set (VCOS_EVENT_FLAGS_T *flags, VCOS_UNSIGNED events, VCOS_OPTION op)
VCOSPRE_ void VCOSPOST_ vcos_generic_event_flags_delete (VCOS_EVENT_FLAGS_T *)
VCOSPRE_ VCOS_STATUS_T VCOSPOST_ vcos_generic_event_flags_get (VCOS_EVENT_FLAGS_T *flags, VCOS_UNSIGNED requested_events, VCOS_OPTION op, VCOS_UNSIGNED suspend, VCOS_UNSIGNED *retrieved_events)
Detailed Description
This provides event flags (as per Nucleus Event Groups) based on a mutex, a semaphore (per waiting thread) and a timer (per waiting thread).
The data structure is a 32 bit unsigned int (the current set of flags) and a linked list of clients waiting to be 'satisfied'.
The mutex merely locks access to the data structure. If a client calls vcos_event_flags_get() and the requested bits are not already present, it then sleeps on its per-thread semaphore after adding this semaphore to the queue waiting. It also sets up a timer.
The per-thread semaphore and timer are actually stored in the thread context (joinable thread). In future it may become necessary to support non-VCOS threads by using thread local storage to create these objects and associate them with the thread.
Definition in file vcos_generic_event_flags.h.
Macro Definition Documentation
VCOS_AND
#define VCOS_AND 2
Definition at line 76 of file vcos_generic_event_flags.h.
Referenced by vcos_generic_event_flags_get(), and vcos_generic_event_flags_set().
VCOS_AND_CONSUME
#define VCOS_AND_CONSUME (VCOS_AND | VCOS_CONSUME)
Definition at line 79 of file vcos_generic_event_flags.h.
VCOS_CONSUME
#define VCOS_CONSUME 4
Definition at line 77 of file vcos_generic_event_flags.h.
Referenced by vcos_generic_event_flags_get(), and vcos_generic_event_flags_set().
VCOS_EVENT_FLAG_OP_MASK
#define VCOS_EVENT_FLAG_OP_MASK (VCOS_OR|VCOS_AND)
Definition at line 80 of file vcos_generic_event_flags.h.
Referenced by vcos_generic_event_flags_get().
VCOS_OR
#define VCOS_OR 1
Definition at line 75 of file vcos_generic_event_flags.h.
Referenced by vcos_generic_event_flags_get(), and vcos_generic_event_flags_set().
VCOS_OR_CONSUME
#define VCOS_OR_CONSUME (VCOS_OR | VCOS_CONSUME)
Definition at line 78 of file vcos_generic_event_flags.h.
Referenced by ilclient_disable_port_buffers(), ilclient_get_input_buffer(), and ilclient_get_output_buffer().
Typedef Documentation
VCOS_EVENT_FLAGS_T
typedef struct VCOS_EVENT_FLAGS_T VCOS_EVENT_FLAGS_T
Function Documentation
vcos_generic_event_flags_create()
VCOSPRE_ VCOS_STATUS_T VCOSPOST_ vcos_generic_event_flags_create (VCOS_EVENT_FLAGS_T * flags, const char * name)
Definition at line 56 of file vcos_generic_event_flags.c.
References VCOS_EVENT_FLAGS_T::events, VCOS_EVENT_FLAGS_T::head, VCOS_EVENT_FLAGS_T::lock, VCOS_EVENT_FLAGS_T::tail, vcos_mutex_create(), VCOS_SUCCESS, and VCOS_EVENT_FLAGS_T::waiters.
 {
    VCOS_STATUS_T rc;
    if ((rc=vcos_mutex_create(&flags->lock, name)) != VCOS_SUCCESS)
    {
       return rc;
    }
    flags->events = 0;
    flags->waiters.head = flags->waiters.tail = 0;
    return rc;
 }
vcos_generic_event_flags_delete()
VCOSPRE_ void VCOSPOST_ vcos_generic_event_flags_delete (VCOS_EVENT_FLAGS_T *)
Definition at line 150 of file vcos_generic_event_flags.c.
References VCOS_EVENT_FLAGS_T::lock, and vcos_mutex_delete().
 {
    vcos_mutex_delete(&flags->lock);
 }
vcos_generic_event_flags_get()
VCOSPRE_ VCOS_STATUS_T VCOSPOST_ vcos_generic_event_flags_get (VCOS_EVENT_FLAGS_T * flags, VCOS_UNSIGNED requested_events, VCOS_OPTION op, VCOS_UNSIGNED suspend, VCOS_UNSIGNED * retrieved_events)
Definition at line 155 of file vcos_generic_event_flags.c.
References _vcos_task_timer_set(), VCOS_EVENT_WAITER_T::actual_events, VCOS_EVENT_FLAGS_T::events, VCOS_EVENT_WAITER_T::flags, VCOS_EVENT_FLAGS_T::lock, VCOS_EVENT_WAITER_T::next, VCOS_EVENT_WAITER_T::op, VCOS_EVENT_WAITER_T::requested_events, VCOS_EVENT_WAITER_T::return_status, VCOS_EVENT_WAITER_T::thread, VCOS_AND, vcos_assert, VCOS_CONSUME, VCOS_EAGAIN, VCOS_EINVAL, VCOS_EVENT_FLAG_OP_MASK, vcos_mutex_lock(), VCOS_OR, VCOS_QUEUE_APPEND_TAIL, VCOS_SUCCESS, vcos_thread_current(), and VCOS_EVENT_FLAGS_T::waiters.
 {
    VCOS_EVENT_WAITER_T waitreq;
    VCOS_STATUS_T rc = VCOS_EAGAIN;
    int satisfied = 0;
    vcos_assert(flags);
    /* default retrieved bits to 0 */
    *retrieved_bits = 0;
    vcos_mutex_lock(&flags->lock);
    switch (op & VCOS_EVENT_FLAG_OP_MASK)
    {
    case VCOS_AND:
       if ((flags->events & bitmask) == bitmask)
       {
          *retrieved_bits = flags->events;
          rc = VCOS_SUCCESS;
          satisfied = 1;
          if (op & VCOS_CONSUME)
             flags->events &= ~bitmask;
       }
       break;
    case VCOS_OR:
       if (flags->events & bitmask)
       {
          *retrieved_bits = flags->events;
          rc = VCOS_SUCCESS;
          satisfied = 1;
          if (op & VCOS_CONSUME)
             flags->events &= ~bitmask;
       }
       break;
    default:
       vcos_assert(0);
       rc = VCOS_EINVAL;
       break;
    }
    if (!satisfied && suspend)
    {
       /* Have to go to sleep.
        *
        * Append to tail so we get FIFO ordering.
        */
       waitreq.requested_events = bitmask;
       waitreq.op = op;
       waitreq.return_status = VCOS_EAGAIN;
       waitreq.flags = flags;
       waitreq.actual_events = 0;
       waitreq.thread = vcos_thread_current();
       waitreq.next = 0;
       vcos_assert(waitreq.thread != (VCOS_THREAD_T*)-1);
       VCOS_QUEUE_APPEND_TAIL(&flags->waiters, &waitreq);
       if (suspend != (VCOS_UNSIGNED)-1)
          _vcos_task_timer_set(event_flags_timer_expired, &waitreq, suspend);
       vcos_mutex_unlock(&flags->lock);
       /* go to sleep and wait to be signalled or timeout */
       _vcos_thread_sem_wait();
       *retrieved_bits = waitreq.actual_events;
       rc = waitreq.return_status;
       /* cancel the timer - do not do this while holding the mutex as it
        * might be waiting for the timeout function to complete, which will
        * try to take the mutex.
        */
       if (suspend != (VCOS_UNSIGNED)-1)
          _vcos_task_timer_cancel();
    }
    else
    {
       vcos_mutex_unlock(&flags->lock);
    }
    return rc;
 }
vcos_generic_event_flags_set()
VCOSPRE_ void VCOSPOST_ vcos_generic_event_flags_set (VCOS_EVENT_FLAGS_T * flags, VCOS_UNSIGNED events, VCOS_OPTION op)
Definition at line 69 of file vcos_generic_event_flags.c.
References VCOS_EVENT_FLAGS_T::events, VCOS_EVENT_FLAGS_T::head, VCOS_EVENT_FLAGS_T::lock, VCOS_EVENT_WAITER_T::next, NULL, VCOS_EVENT_WAITER_T::op, VCOS_EVENT_WAITER_T::requested_events, VCOS_EVENT_FLAGS_T::tail, VCOS_AND, vcos_assert, VCOS_CONSUME, vcos_mutex_lock(), VCOS_OR, and VCOS_EVENT_FLAGS_T::waiters.
 {
    vcos_assert(flags);
    vcos_mutex_lock(&flags->lock);
    if (op == VCOS_OR)
    {
       flags->events |= bitmask;
    }
    else if (op == VCOS_AND)
    {
       flags->events &= bitmask;
    }
    else
    {
       vcos_assert(0);
    }
    /* Now wake up any threads that have now become signalled. */
    if (flags->waiters.head != NULL)
    {
       VCOS_UNSIGNED consumed_events = 0;
       VCOS_EVENT_WAITER_T **pcurrent_waiter = &flags->waiters.head;
       VCOS_EVENT_WAITER_T *prev_waiter = NULL;
       /* Walk the chain of tasks suspend on this event flag group to determine
        * if any of their requests can be satisfied.
        */
       while ((*pcurrent_waiter) != NULL)
       {
          VCOS_EVENT_WAITER_T *curr_waiter = *pcurrent_waiter;
          /* Determine if this request has been satisfied */
          /* First, find the event flags in common. */
          VCOS_UNSIGNED waiter_satisfied = flags->events & curr_waiter->requested_events;
          /* Second, determine if all the event flags must match */
          if (curr_waiter->op & VCOS_AND)
          {
             /* All requested events must be present */
             waiter_satisfied = (waiter_satisfied == curr_waiter->requested_events);
          }
          /* Wake this one up? */
          if (waiter_satisfied)
          {
             if (curr_waiter->op & VCOS_CONSUME)
             {
                consumed_events |= curr_waiter->requested_events;
             }
             /* remove this block from the list, taking care at the end */
             *pcurrent_waiter = curr_waiter->next;
             if (curr_waiter->next == NULL)
                flags->waiters.tail = prev_waiter;
             vcos_assert(waiter_list_valid(flags));
             curr_waiter->return_status = VCOS_SUCCESS;
             curr_waiter->actual_events = flags->events;
             _vcos_thread_sem_post(curr_waiter->thread);
          }
          else
          {
             /* move to next element in the list */
             prev_waiter = *pcurrent_waiter;
             pcurrent_waiter = &(curr_waiter->next);
          }
       }
       flags->events &= ~consumed_events;
    }
    vcos_mutex_unlock(&flags->lock);
 }