VideoCore Library: containers/rtp/rtp_reader.c File Reference
rtp_reader.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "containers/core/containers_private.h"
#include "containers/core/containers_io_helpers.h"
#include "containers/core/containers_utils.h"
#include "containers/core/containers_uri.h"
#include "containers/core/containers_logging.h"
#include "containers/core/containers_bits.h"
#include "containers/core/containers_list.h"
#include "rtp_priv.h"
#include "rtp_mpeg4.h"
#include "rtp_h264.h"
Classes
struct audio_payload_type_data_tag
struct video_payload_type_data_tag
struct mime_type_data_tag
struct VC_CONTAINER_MODULE_T
Macros
#define CONTAINER_IS_BIG_ENDIAN
#define CONTAINER_HELPER_LOG_INDENT(a) 0
#define MAXIMUM_PACKET_SIZE 2048
#define MAX_DROPOUT 3000
#define MAX_MISORDER 0
#define MIN_SEQUENTIAL 2
#define RTP_SCHEME "rtp:"
#define RTP_PKT_SCHEME "rtppkt:"
#define UNSUPPORTED_CODEC VC_FOURCC(0,0,0,0)
#define IS_STATIC_AUDIO_TYPE(PT) ((PT) < countof(static_audio_payload_types))
#define FIRST_STATIC_VIDEO_TYPE 24
#define IS_STATIC_VIDEO_TYPE(PT)
#define IS_DYNAMIC_TYPE(PT) ((PT) >= 96 && (PT) < 128)
#define RTP_SEQ_MOD (1 << 16)
#define STATIC_VIDEO_TIMESTAMP_CLOCK 90000
#define MICROSECONDS_PER_SECOND 1000000
RTP URI parameter names
#define PAYLOAD_TYPE_NAME "rtppt"
#define MIME_TYPE_NAME "mime-type"
#define CHANNELS_NAME "channels"
#define RATE_NAME "rate"
#define SSRC_NAME "ssrc"
#define SEQ_NAME "seq"
Typedefs
typedef struct audio_payload_type_data_tag AUDIO_PAYLOAD_TYPE_DATA_T
typedef struct video_payload_type_data_tag VIDEO_PAYLOAD_TYPE_DATA_T
typedef struct mime_type_data_tag MIME_TYPE_DATA_T
typedef struct VC_CONTAINER_MODULE_T VC_CONTAINER_MODULE_T
Functions
VC_CONTAINERS_STATIC_LIST (dynamic_mime, dynamic_mime_details, mime_type_data_comparator)
VC_CONTAINER_STATUS_T rtp_reader_open (VC_CONTAINER_T *)
bool rtp_get_parameter_u32 (const VC_CONTAINERS_LIST_T *param_list, const char *name, uint32_t *value)
bool rtp_get_parameter_x32 (const VC_CONTAINERS_LIST_T *param_list, const char *name, uint32_t *value)
MIME type parameter handlers
Function prototypes for payload parameter handlers
MIME type payload handlers
Macro Definition Documentation
CHANNELS_NAME
#define CHANNELS_NAME "channels"
Definition at line 80 of file rtp_reader.c.
CONTAINER_HELPER_LOG_INDENT
#define CONTAINER_HELPER_LOG_INDENT (a) 0
Definition at line 34 of file rtp_reader.c.
CONTAINER_IS_BIG_ENDIAN
#define CONTAINER_IS_BIG_ENDIAN
Definition at line 31 of file rtp_reader.c.
FIRST_STATIC_VIDEO_TYPE
#define FIRST_STATIC_VIDEO_TYPE 24
Payload type number for the first static video type
Definition at line 93 of file rtp_reader.c.
IS_DYNAMIC_TYPE
#define IS_DYNAMIC_TYPE (PT) ((PT) >= 96 && (PT) < 128)
Evaluates to true if the given payload type is in the dynamic range.
Definition at line 99 of file rtp_reader.c.
IS_STATIC_AUDIO_TYPE
#define IS_STATIC_AUDIO_TYPE (PT) ((PT) < countof(static_audio_payload_types))
Evaluates to true if the given payload type is in the supported static audio range.
Definition at line 90 of file rtp_reader.c.
IS_STATIC_VIDEO_TYPE
#define IS_STATIC_VIDEO_TYPE (PT)
Value:
((PT) >= FIRST_STATIC_VIDEO_TYPE && \
                                        (PT) < (FIRST_STATIC_VIDEO_TYPE + countof(static_video_payload_types)))
Evaluates to true if the given payload type is in the supported static video range.
Definition at line 95 of file rtp_reader.c.
MAX_DROPOUT
#define MAX_DROPOUT 3000
Maximum number of RTP packets that can be missed without restarting.
Definition at line 60 of file rtp_reader.c.
MAX_MISORDER
#define MAX_MISORDER 0
Maximum number of out of sequence RTP packets that are accepted.
Definition at line 62 of file rtp_reader.c.
MAXIMUM_PACKET_SIZE
#define MAXIMUM_PACKET_SIZE 2048
Maximum size of an RTP packet
Definition at line 57 of file rtp_reader.c.
MICROSECONDS_PER_SECOND
#define MICROSECONDS_PER_SECOND 1000000
Number of microseconds in a second, used to convert RTP timestamps to microseconds
Definition at line 108 of file rtp_reader.c.
MIME_TYPE_NAME
#define MIME_TYPE_NAME "mime-type"
Definition at line 79 of file rtp_reader.c.
MIN_SEQUENTIAL
#define MIN_SEQUENTIAL 2
Minimum number of sequential packets required for an acceptable connection when restarting.
Definition at line 65 of file rtp_reader.c.
PAYLOAD_TYPE_NAME
#define PAYLOAD_TYPE_NAME "rtppt"
Definition at line 78 of file rtp_reader.c.
RATE_NAME
#define RATE_NAME "rate"
Definition at line 81 of file rtp_reader.c.
RTP_PKT_SCHEME
#define RTP_PKT_SCHEME "rtppkt:"
The RTP PKT scheme is used with test pkt files
Definition at line 74 of file rtp_reader.c.
Referenced by rtp_reader_open().
RTP_SCHEME
#define RTP_SCHEME "rtp:"
Definition at line 71 of file rtp_reader.c.
Referenced by rtp_reader_open().
RTP_SEQ_MOD
#define RTP_SEQ_MOD (1 << 16)
All sequence numbers are modulo this value.
Definition at line 102 of file rtp_reader.c.
SEQ_NAME
#define SEQ_NAME "seq"
Definition at line 83 of file rtp_reader.c.
SSRC_NAME
#define SSRC_NAME "ssrc"
Definition at line 82 of file rtp_reader.c.
STATIC_VIDEO_TIMESTAMP_CLOCK
#define STATIC_VIDEO_TIMESTAMP_CLOCK 90000
All the static video payload types use a 90kHz timestamp clock
Definition at line 105 of file rtp_reader.c.
UNSUPPORTED_CODEC
#define UNSUPPORTED_CODEC VC_FOURCC(0,0,0,0)
A sentinel codec that is not supported
Definition at line 87 of file rtp_reader.c.
Typedef Documentation
AUDIO_PAYLOAD_TYPE_DATA_T
typedef struct audio_payload_type_data_tag AUDIO_PAYLOAD_TYPE_DATA_T
Static audio payload type data
MIME_TYPE_DATA_T
typedef struct mime_type_data_tag MIME_TYPE_DATA_T
MIME type details
VC_CONTAINER_MODULE_T
typedef struct VC_CONTAINER_MODULE_T VC_CONTAINER_MODULE_T
RTP reader data.
VIDEO_PAYLOAD_TYPE_DATA_T
typedef struct video_payload_type_data_tag VIDEO_PAYLOAD_TYPE_DATA_T
Static video payload type data
Function Documentation
rtp_get_parameter_u32()
bool rtp_get_parameter_u32 (const VC_CONTAINERS_LIST_T * param_list, const char * name, uint32_t * value)
Gets the value of a parameter as an unsigned 32-bit decimal integer.
Parameters
param_list The URI parameter list.
name The name of the parameter.
value Pointer to the variable to receive the value.
Returns
True if the parameter value was read and stored correctly, false otherwise.
Definition at line 837 of file rtp_reader.c.
References parameter_tag::name, name, parameter_tag::value, and vc_containers_list_find_entry().
 {
    PARAMETER_T param;
    param.name = name;
    if (vc_containers_list_find_entry(param_list, &param) && param.value)
    {
       char *end;
       *value = strtoul(param.value, &end, 10);
       return (end != param.value) && (*end == '\0');
    }
    return false;
 }
rtp_get_parameter_x32()
bool rtp_get_parameter_x32 (const VC_CONTAINERS_LIST_T * param_list, const char * name, uint32_t * value)
Gets the value of a parameter as an unsigned 32-bit hexadecimal integer.
Parameters
param_list The URI parameter list.
name The name of the parameter.
value Pointer to the variable to receive the value.
Returns
True if the parameter value was read and stored correctly, false otherwise.
Definition at line 864 of file rtp_reader.c.
References parameter_tag::name, name, parameter_tag::value, and vc_containers_list_find_entry().
 {
    PARAMETER_T param;
    param.name = name;
    if (vc_containers_list_find_entry(param_list, &param) && param.value)
    {
       char *end;
       *value = strtoul(param.value, &end, 16);
       return (end != param.value) && (*end == '\0');
    }
    return false;
 }
rtp_reader_open()
VC_CONTAINER_STATUS_T rtp_reader_open (VC_CONTAINER_T * p_ctx)
Open the container. Uses the I/O URI and/or data to configure the container.
Parameters
p_ctx The reader context.
Returns
The resulting status of the function.
Definition at line 1063 of file rtp_reader.c.
References NULL, VC_CONTAINER_T::priv, RTP_PKT_SCHEME, RTP_SCHEME, VC_CONTAINER_PRIVATE_T::uri, VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED, VC_CONTAINER_SUCCESS, and vc_uri_scheme().
 {
    VC_CONTAINER_MODULE_T *module = 0;
    VC_CONTAINER_TRACK_T *track = 0;
    VC_CONTAINER_TRACK_MODULE_T *t_module = 0;
    VC_CONTAINER_STATUS_T status = VC_CONTAINER_SUCCESS;
    VC_CONTAINERS_LIST_T *parameters = NULL;
    uint32_t payload_type;
    uint32_t initial_seq_num;
    /* Check the URI scheme looks valid */
    if (!vc_uri_scheme(p_ctx->priv->uri) ||
        (strcasecmp(vc_uri_scheme(p_ctx->priv->uri), RTP_SCHEME) &&
         strcasecmp(vc_uri_scheme(p_ctx->priv->uri), RTP_PKT_SCHEME)))
       return VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED;
    /* Make the query/parameter list more easily searchable */
    parameters = fill_parameter_list(p_ctx->priv->uri);
    if (!parameters) { status = VC_CONTAINER_ERROR_OUT_OF_MEMORY; goto error; }
    /* Payload type parameter is mandatory and must fit in 7 bits */
    if (!rtp_get_parameter_u32(parameters, PAYLOAD_TYPE_NAME, &payload_type) || payload_type > 127)
    {
       status = VC_CONTAINER_ERROR_FORMAT_INVALID;
       goto error;
    }
    /* Allocate our context */
    module = (VC_CONTAINER_MODULE_T *)malloc(sizeof(VC_CONTAINER_MODULE_T));
    if (!module) { status = VC_CONTAINER_ERROR_OUT_OF_MEMORY; goto error; }
    memset(module, 0, sizeof(*module));
    p_ctx->priv->module = module;
    p_ctx->tracks = &module->track;
    /* Allocate the track, including space for reading an RTP packet on the end */
    track = vc_container_allocate_track(p_ctx, sizeof(VC_CONTAINER_TRACK_MODULE_T) + MAXIMUM_PACKET_SIZE);
    if (!track)
    {
       status = VC_CONTAINER_ERROR_OUT_OF_MEMORY;
       goto error;
    }
    module->track = track;
    p_ctx->tracks_num = 1;
    t_module = track->priv->module;
    /* Initialise the track data */
    t_module->buffer = (uint8_t *)(t_module + 1);
    status = decode_payload_type(p_ctx, track, parameters, payload_type);
    if (status != VC_CONTAINER_SUCCESS)
       goto error;
    vc_container_assert(t_module->timestamp_clock != 0);
    /* Default to a generic, unstructured payload handler */
    if (!t_module->payload_handler)
       t_module->payload_handler = generic_payload_handler;
    if (rtp_get_parameter_x32(parameters, SSRC_NAME, &t_module->expected_ssrc))
       SET_BIT(t_module->flags, TRACK_SSRC_SET);
    t_module->probation = MIN_SEQUENTIAL;
    if (rtp_get_parameter_u32(parameters, SEQ_NAME, &initial_seq_num))
    {
       /* If an initial sequence number is provided, avoid probation period */
       t_module->max_seq_num = (uint16_t)initial_seq_num;
       t_module->probation = 0;
    }
    track->is_enabled = true;
    vc_containers_list_destroy(parameters);
    p_ctx->priv->pf_close = rtp_reader_close;
    p_ctx->priv->pf_read = rtp_reader_read;
    p_ctx->priv->pf_seek = rtp_reader_seek;
    p_ctx->priv->pf_control = rtp_reader_control;
    return VC_CONTAINER_SUCCESS;
 error:
    if (parameters) vc_containers_list_destroy(parameters);
    if(status == VC_CONTAINER_SUCCESS || status == VC_CONTAINER_ERROR_EOS)
       status = VC_CONTAINER_ERROR_FORMAT_INVALID;
    LOG_DEBUG(p_ctx, "error opening RTP (%i)", status);
    rtp_reader_close(p_ctx);
    return status;
 }
VC_CONTAINERS_STATIC_LIST()
VC_CONTAINERS_STATIC_LIST (dynamic_mime , dynamic_mime_details , mime_type_data_comparator)
Sorted list of dynamic MIME type details