VideoCore Library: interface/mmal/vc/mmal_vc_api.h File Reference
mmal_vc_api.h File Reference
#include "interface/mmal/mmal_types.h"
#include "interface/mmal/mmal_parameters.h"
#include "interface/mmal/mmal_port.h"
Classes
struct MMAL_VC_COMP_STATS_T
struct MMAL_VC_STATS_T
struct MMAL_VC_STATS_T::service
struct MMAL_VC_STATS_T::commands
struct MMAL_VC_HOST_LOG_T
Macros
#define MMAL_DEV_VCHIQ_PATH "/dev/vchiq"
#define MMAL_DEV_VCHIQ_MODE O_RDWR
#define MMAL_VC_API_HAVE_HOST_LOG
Typedefs
typedef struct MMAL_VC_STATS_T MMAL_VC_STATS_T
typedef struct MMAL_VC_HOST_LOG_T MMAL_VC_HOST_LOG_T
Enumerations
enum MMAL_STATS_COMP_STATE_T {
MMAL_STATS_COMP_IDLE, MMAL_STATS_COMP_CREATED, MMAL_STATS_COMP_DESTROYING, MMAL_STATS_COMP_DESTROYED,
MMAL_STATS_COMP_UNUSED = 0xffffffff
}
enum MMAL_STATS_RESULT_T { MMAL_STATS_FOUND, MMAL_STATS_COMPONENT_NOT_FOUND, MMAL_STATS_PORT_NOT_FOUND, MMAL_STATS_INVALID = 0x7fffffff }
enum MMAL_VC_COMPACT_MODE_T {
MMAL_VC_COMPACT_NONE = 0, MMAL_VC_COMPACT_NORMAL = 1, MMAL_VC_COMPACT_DISCARD = 2, MMAL_VC_COMPACT_AGGRESSIVE = 4,
MMAL_VC_COMPACT_SHUFFLE = 0x80, MMAL_VC_COMPACT_ALL = MMAL_VC_COMPACT_NORMAL | MMAL_VC_COMPACT_DISCARD | MMAL_VC_COMPACT_AGGRESSIVE
}
Functions
MMAL_STATUS_T mmal_vc_init (void)
MMAL_STATUS_T mmal_vc_init_fd (int dev_vchiq_fd)
void mmal_vc_deinit (void)
MMAL_STATUS_T mmal_vc_use (void)
MMAL_STATUS_T mmal_vc_release (void)
MMAL_STATUS_T mmal_vc_get_version (uint32_t *major, uint32_t *minor, uint32_t *minimum)
MMAL_STATUS_T mmal_vc_get_stats (MMAL_VC_STATS_T *stats, int reset)
MMAL_STATUS_T mmal_vc_get_core_stats (MMAL_CORE_STATISTICS_T *stats, MMAL_STATS_RESULT_T *result, char *name, size_t namelen, MMAL_PORT_TYPE_T type, unsigned component, unsigned port, MMAL_CORE_STATS_DIR dir, MMAL_BOOL_T reset)
MMAL_STATUS_T mmal_vc_host_log (const char *msg)
MMAL_STATUS_T mmal_vc_consume_mem (size_t size, uint32_t *handle)
MMAL_STATUS_T mmal_vc_compact (MMAL_VC_COMPACT_MODE_T mode, uint32_t *duration)
MMAL_STATUS_T mmal_vc_lmk (uint32_t alloc_size)
Detailed Description
Public API for MMAL VC client. Most functionality is exposed via MMAL itself.
Definition in file mmal_vc_api.h.
Macro Definition Documentation
MMAL_DEV_VCHIQ_MODE
#define MMAL_DEV_VCHIQ_MODE O_RDWR
Definition at line 150 of file mmal_vc_api.h.
MMAL_DEV_VCHIQ_PATH
#define MMAL_DEV_VCHIQ_PATH "/dev/vchiq"
Definition at line 149 of file mmal_vc_api.h.
MMAL_VC_API_HAVE_HOST_LOG
#define MMAL_VC_API_HAVE_HOST_LOG
Definition at line 195 of file mmal_vc_api.h.
Typedef Documentation
MMAL_VC_HOST_LOG_T
typedef struct MMAL_VC_HOST_LOG_T MMAL_VC_HOST_LOG_T
Definition at line 136 of file mmal_vc_api.h.
MMAL_VC_STATS_T
typedef struct MMAL_VC_STATS_T MMAL_VC_STATS_T
Definition at line 121 of file mmal_vc_api.h.
Enumeration Type Documentation
MMAL_STATS_COMP_STATE_T
enum MMAL_STATS_COMP_STATE_T
State of components created by the VC adaptation layer, used for statistics reporting.
Enumerator
MMAL_STATS_COMP_IDLE
MMAL_STATS_COMP_CREATED
MMAL_STATS_COMP_DESTROYING
MMAL_STATS_COMP_DESTROYED
MMAL_STATS_COMP_UNUSED
Definition at line 48 of file mmal_vc_api.h.
              {
    MMAL_STATS_COMP_IDLE,
    MMAL_STATS_COMP_CREATED,
    MMAL_STATS_COMP_DESTROYING,
    MMAL_STATS_COMP_DESTROYED,
    MMAL_STATS_COMP_UNUSED = 0xffffffff /* force 32bit */
 } MMAL_STATS_COMP_STATE_T;
MMAL_STATS_RESULT_T
enum MMAL_STATS_RESULT_T
Status from querying MMAL core statistics.
Enumerator
MMAL_STATS_FOUND
MMAL_STATS_COMPONENT_NOT_FOUND
MMAL_STATS_PORT_NOT_FOUND
MMAL_STATS_INVALID
Definition at line 140 of file mmal_vc_api.h.
 {
    MMAL_STATS_FOUND,
    MMAL_STATS_COMPONENT_NOT_FOUND,
    MMAL_STATS_PORT_NOT_FOUND,
    MMAL_STATS_INVALID = 0x7fffffff
 } MMAL_STATS_RESULT_T;
MMAL_VC_COMPACT_MODE_T
enum MMAL_VC_COMPACT_MODE_T
Enumerator
MMAL_VC_COMPACT_NONE
MMAL_VC_COMPACT_NORMAL
MMAL_VC_COMPACT_DISCARD
MMAL_VC_COMPACT_AGGRESSIVE
MMAL_VC_COMPACT_SHUFFLE
MMAL_VC_COMPACT_ALL
Definition at line 216 of file mmal_vc_api.h.
 {
    MMAL_VC_COMPACT_NONE       = 0,
    MMAL_VC_COMPACT_NORMAL     = 1,
    MMAL_VC_COMPACT_DISCARD    = 2,
    MMAL_VC_COMPACT_AGGRESSIVE = 4,
    MMAL_VC_COMPACT_SHUFFLE    = 0x80,
    MMAL_VC_COMPACT_ALL        = MMAL_VC_COMPACT_NORMAL | MMAL_VC_COMPACT_DISCARD | MMAL_VC_COMPACT_AGGRESSIVE,
 } MMAL_VC_COMPACT_MODE_T;
Function Documentation
mmal_vc_compact()
MMAL_STATUS_T mmal_vc_compact (MMAL_VC_COMPACT_MODE_T mode, uint32_t * duration)
Trigger relocatable heap compaction.
Definition at line 844 of file mmal_vc_api.c.
References mmal_worker_compact::duration, mmal_worker_compact::header, len, MMAL_FALSE, MMAL_SUCCESS, mmal_vc_get_client(), mmal_vc_sendwait_message(), MMAL_WORKER_COMPACT, mmal_worker_compact::mode, status, mmal_worker_compact::status, and vcos_assert.
 {
    MMAL_STATUS_T status;
    mmal_worker_compact req;
    mmal_worker_compact reply;
    size_t len = sizeof(reply);
    req.mode = (uint32_t)mode;
    status = mmal_vc_sendwait_message(mmal_vc_get_client(),
                                      &req.header, sizeof(req),
                                      MMAL_WORKER_COMPACT,
                                      &reply, &len, MMAL_FALSE);
    if (status == MMAL_SUCCESS)
    {
       vcos_assert(len == sizeof(reply));
       status = reply.status;
       *duration = reply.duration;
    }
    return status;
 }
mmal_vc_consume_mem()
MMAL_STATUS_T mmal_vc_consume_mem (size_t size, uint32_t * handle)
Consumes memory in the relocatable heap.
The existing reserved memory is freed first then the new chunk is allocated. If zero is specified for the size then the previously reserved memory is freed and no allocation occurs.
At startup no memory is reserved.
Parameters
size Size of memory to consume in bytes.
handle Set to the mem handle for the reserved memory or zero if no memory was allocated.
Returns
MMAL_SUCCESS if memory was reserved (or size zero requested), MMAL_ENOSPC if the allocation failed or MMAL_ENOSYS if the API is not supported e.g in release mode VC images.
Definition at line 822 of file mmal_vc_api.c.
References mmal_worker_consume_mem::handle, mmal_worker_consume_mem::header, len, MMAL_FALSE, MMAL_SUCCESS, mmal_vc_get_client(), mmal_vc_sendwait_message(), MMAL_WORKER_CONSUME_MEM, mmal_worker_consume_mem::size, status, mmal_worker_consume_mem::status, and vcos_assert.
 {
    MMAL_STATUS_T status;
    mmal_worker_consume_mem req;
    mmal_worker_consume_mem reply;
    size_t len = sizeof(reply);
    req.size = (uint32_t) size;
    status = mmal_vc_sendwait_message(mmal_vc_get_client(),
                                      &req.header, sizeof(req),
                                      MMAL_WORKER_CONSUME_MEM,
                                      &reply, &len, MMAL_FALSE);
    if (status == MMAL_SUCCESS)
    {
       vcos_assert(len == sizeof(reply));
       status = reply.status;
       *handle = reply.handle;
    }
    return status;
 }
mmal_vc_deinit()
void mmal_vc_deinit (void)
Definition at line 1028 of file mmal_vc_client.c.
References MMAL_CLIENT_T::bulk_lock, MMAL_CLIENT_T::lock, MMAL_CLIENT_T::refcount, vcos_mutex_delete(), vcos_mutex_lock(), and vcos_mutex_unlock().
Referenced by mmal_vc_drm_get_lhs32(), and mmal_vc_drm_get_time().
 {
    int count;
    vcos_mutex_lock(&client.lock);
    count = --client.refcount;
    if (count != 0)
    {
       /* Still in use so don't do anything */
       vcos_mutex_unlock(&client.lock);
       return;
    }
    vcos_mutex_delete(&client.bulk_lock);
    destroy_waitpool(&client.waitpool);
    vchiq_close_service(client.service);
    vchiq_shutdown(mmal_vchiq_instance);
    vcos_log_unregister(VCOS_LOG_CATEGORY);
    client.service = VCHIQ_SERVICE_HANDLE_INVALID;
    client.inited = 0;
    vcos_mutex_unlock(&client.lock);
 }
mmal_vc_get_core_stats()
MMAL_STATUS_T mmal_vc_get_core_stats (MMAL_CORE_STATISTICS_T * stats, MMAL_STATS_RESULT_T * result, char * name, size_t namelen, MMAL_PORT_TYPE_T type, unsigned component, unsigned port, MMAL_CORE_STATS_DIR dir, MMAL_BOOL_T reset)
Return the MMAL core statistics for a given component/port.
Parameters
stats Updated with given port statistics
result Whether the port/component was found
name Filled in with the name of the port
namelen Length of name
component Which component (indexed from zero)
port_type Which type of port
port Which port (index from zero)
reset Reset the stats.
Definition at line 906 of file mmal_vc_api.c.
References mmal_worker_get_core_stats_for_port::component_index, mmal_worker_get_core_stats_for_port_reply::component_name, mmal_worker_get_core_stats_for_port::dir, mmal_worker_get_core_stats_for_port::header, len, MMAL_FALSE, MMAL_SUCCESS, mmal_vc_get_client(), mmal_vc_sendwait_message(), MMAL_WORKER_GET_CORE_STATS_FOR_PORT, mmal_worker_get_core_stats_for_port::port_index, mmal_worker_get_core_stats_for_port::reset, mmal_worker_get_core_stats_for_port_reply::result, mmal_worker_get_core_stats_for_port_reply::stats, status, mmal_worker_get_core_stats_for_port::type, and vcos_assert.
 {
    mmal_worker_get_core_stats_for_port req;
    mmal_worker_get_core_stats_for_port_reply reply;
    MMAL_STATUS_T status;
    size_t len = sizeof(reply);
    req.component_index = component_index;
    req.port_index = port_index;
    req.type = type;
    req.reset = reset;
    req.dir = dir;
    status = mmal_vc_sendwait_message(mmal_vc_get_client(),
                                      &req.header, sizeof(req),
                                      MMAL_WORKER_GET_CORE_STATS_FOR_PORT,
                                      &reply, &len, MMAL_FALSE);
    if (status == MMAL_SUCCESS)
    {
       vcos_assert(len == sizeof(reply));
       *stats = reply.stats;
       *result = reply.result;
       strncpy(name, reply.component_name, namelen);
       name[namelen-1] = '\0';
    }
    return status;
 }
mmal_vc_get_stats()
MMAL_STATUS_T mmal_vc_get_stats (MMAL_VC_STATS_T * stats, int reset)
Definition at line 121 of file mmal_vc_api.c.
References mmal_worker_stats::header, len, MMAL_FALSE, MMAL_SUCCESS, mmal_vc_get_client(), mmal_vc_sendwait_message(), MMAL_WORKER_GET_STATS, mmal_worker_stats::reset, mmal_worker_stats::stats, status, and vcos_assert.
 {
    mmal_worker_stats msg;
    size_t len = sizeof(msg);
    msg.reset = reset;
    MMAL_STATUS_T status = mmal_vc_sendwait_message(mmal_vc_get_client(),
                                                    &msg.header, sizeof(msg),
                                                    MMAL_WORKER_GET_STATS,
                                                    &msg, &len, MMAL_FALSE);
    if (status == MMAL_SUCCESS)
    {
       vcos_assert(len == sizeof(msg));
       *stats = msg.stats;
    }
    return status;
 }
mmal_vc_get_version()
MMAL_STATUS_T mmal_vc_get_version (uint32_t * major, uint32_t * minor, uint32_t * minimum)
Definition at line 99 of file mmal_vc_api.c.
References mmal_worker_version::header, len, mmal_worker_version::major, mmal_worker_version::minimum, mmal_worker_version::minor, MMAL_EINVAL, MMAL_FALSE, MMAL_SUCCESS, mmal_vc_get_client(), mmal_vc_sendwait_message(), MMAL_WORKER_GET_VERSION, status, and vcos_verify.
 {
    mmal_worker_version msg;
    size_t len = sizeof(msg);
    MMAL_STATUS_T status;
    status = mmal_vc_sendwait_message(mmal_vc_get_client(), &msg.header, sizeof(msg),
                                      MMAL_WORKER_GET_VERSION, &msg, &len, MMAL_FALSE);
    if (status != MMAL_SUCCESS)
       return status;
    if (!vcos_verify(len == sizeof(msg)))
       return MMAL_EINVAL;
    *major = msg.major;
    *minor = msg.minor;
    *minimum = msg.minimum;
    return MMAL_SUCCESS;
 }
mmal_vc_host_log()
MMAL_STATUS_T mmal_vc_host_log (const char * msg)
Stores an arbitrary text message in a circular buffer inside the MMAL VC server. The purpose of this message is to log high level events from the host in order to diagnose problems that require multiple actions to reproduce. e.g. taking multiple pictures with different settings.
Parameters
msg The message text.
Returns
MMAL_SUCCESS if the message was logged or MMAL_ENOSYS if the API if not supported.
Definition at line 881 of file mmal_vc_api.c.
References mmal_worker_host_log::header, MMAL_EINVAL, MMAL_FALSE, MMAL_SUCCESS, mmal_vc_get_client(), mmal_vc_sendwait_message(), MMAL_WORKER_HOST_LOG, mmal_worker_host_log::msg, status, mmal_worker_reply::status, vcos_assert, vcos_min, and vcos_safe_strcpy().
 {
    MMAL_STATUS_T status = MMAL_EINVAL;
    if (msg)
    {
       mmal_worker_host_log req;
       mmal_worker_reply reply;
       size_t replylen = sizeof(reply);
       size_t msg_len = vcos_safe_strcpy(req.msg, msg, sizeof(req.msg), 0);
       /* Reduce the length if it is shorter than the max message length */
       status = mmal_vc_sendwait_message(mmal_vc_get_client(), &req.header,
             sizeof(req) - sizeof(req.msg) + vcos_min(sizeof(req.msg), msg_len + 1),
             MMAL_WORKER_HOST_LOG,
             &reply, &replylen, MMAL_FALSE);
       if (status == MMAL_SUCCESS)
       {
          vcos_assert(replylen == sizeof(reply));
          status = reply.status;
       }
    }
    return status;
 }
mmal_vc_init()
MMAL_STATUS_T mmal_vc_init (void)
Definition at line 1023 of file mmal_vc_client.c.
References mmal_vc_init_fd().
Referenced by mmal_vc_drm_get_lhs32(), and mmal_vc_drm_get_time().
 {
    return mmal_vc_init_fd(-1);
 }
mmal_vc_init_fd()
MMAL_STATUS_T mmal_vc_init_fd (int dev_vchiq_fd)
Definition at line 924 of file mmal_vc_client.c.
References MMAL_EIO, status, and vcos_once().
Referenced by mmal_vc_init().
 {
    VCHIQ_SERVICE_PARAMS_T vchiq_params;
    MMAL_BOOL_T vchiq_initialised = 0, waitpool_initialised = 0;
    MMAL_BOOL_T service_initialised = 0;
    MMAL_STATUS_T status = MMAL_EIO;
    VCHIQ_STATUS_T vchiq_status;
    int count;
    vcos_once(&once, init_once);
    vcos_mutex_lock(&client.lock);
    count = client.refcount++;
    if (count > 0)
    {
       /* Already initialised so nothing to do */
       vcos_mutex_unlock(&client.lock);
       return MMAL_SUCCESS;
    }
    vcos_log_register("mmalipc", VCOS_LOG_CATEGORY);
    /* Initialise a VCHIQ instance */
    vchiq_status = vchiq_initialise_fd(&mmal_vchiq_instance, dev_vchiq_fd);
    if (vchiq_status != VCHIQ_SUCCESS)
    {
       LOG_ERROR("failed to initialise vchiq");
       status = MMAL_EIO;
       goto error;
    }
    vchiq_initialised = 1;
    vchiq_status = vchiq_connect(mmal_vchiq_instance);
    if (vchiq_status != VCHIQ_SUCCESS)
    {
       LOG_ERROR("failed to connect to vchiq");
       status = MMAL_EIO;
       goto error;
    }
    memset(&vchiq_params,0,sizeof(vchiq_params));
    vchiq_params.fourcc = MMAL_CONTROL_FOURCC();
    vchiq_params.callback = mmal_vc_vchiq_callback;
    vchiq_params.userdata = &client;
    vchiq_params.version = WORKER_VER_MAJOR;
    vchiq_params.version_min = WORKER_VER_MINIMUM;
    vchiq_status = vchiq_open_service(mmal_vchiq_instance, &vchiq_params, &client.service);
    if (vchiq_status != VCHIQ_SUCCESS)
    {
       LOG_ERROR("could not open vchiq service");
       status = MMAL_EIO;
       goto error;
    }
    client.usecount = 1; /* usecount set to 1 by the open call. */
    service_initialised = 1;
    status = create_waitpool(&client.waitpool);
    if (status != MMAL_SUCCESS)
    {
       LOG_ERROR("could not create wait pool");
       goto error;
    }
    waitpool_initialised = 1;
    if (vcos_mutex_create(&client.bulk_lock, "mmal client bulk lock") != VCOS_SUCCESS)
    {
       LOG_ERROR("could not create bulk lock");
       status = MMAL_ENOSPC;
       goto error;
    }
    client.inited = 1;
    vcos_mutex_unlock(&client.lock);
    /* assume we're not using VC immediately.  Do this outside the lock */
    mmal_vc_release();
    return MMAL_SUCCESS;
  error:
    if (waitpool_initialised)
       destroy_waitpool(&client.waitpool);
    if (service_initialised)
    {
       client.usecount = 0;
       vchiq_close_service(client.service);
    }
    if (vchiq_initialised)
       vchiq_shutdown(mmal_vchiq_instance);
    vcos_log_unregister(VCOS_LOG_CATEGORY);
    client.refcount--;
    vcos_mutex_unlock(&client.lock);
    return status;
 }
mmal_vc_lmk()
MMAL_STATUS_T mmal_vc_lmk (uint32_t alloc_size)
Trigger LMK action from VC, for diagnostics.
Definition at line 865 of file mmal_vc_api.c.
References mmal_worker_lmk::alloc_size, mmal_worker_lmk::header, len, MMAL_FALSE, mmal_vc_get_client(), mmal_vc_sendwait_message(), MMAL_WORKER_LMK, and status.
 {
    MMAL_STATUS_T status;
    mmal_worker_lmk req;
    mmal_worker_lmk reply;
    size_t len = sizeof(reply);
    req.alloc_size = alloc_size;
    status = mmal_vc_sendwait_message(mmal_vc_get_client(),
                                      &req.header, sizeof(req),
                                      MMAL_WORKER_LMK,
                                      &reply, &len, MMAL_FALSE);
    return status;
 }
mmal_vc_release()
MMAL_STATUS_T mmal_vc_release (void)
Definition at line 916 of file mmal_vc_client.c.
References MMAL_CLIENT_T::inited, MMAL_ENOTCONN, and status.
 {
    MMAL_STATUS_T status = MMAL_ENOTCONN;
    if(client.inited)
       status = mmal_vc_release_internal(&client);
    return status;
 }
mmal_vc_use()
MMAL_STATUS_T mmal_vc_use (void)
Definition at line 908 of file mmal_vc_client.c.
References MMAL_CLIENT_T::inited, MMAL_ENOTCONN, and status.
 {
    MMAL_STATUS_T status = MMAL_ENOTCONN;
    if(client.inited)
       status = mmal_vc_use_internal(&client);
    return status;
 }