VideoCore Library: containers/core/containers_loader.h File Reference
containers_loader.h File Reference
Functions
VC_CONTAINER_STATUS_T vc_container_load_reader (VC_CONTAINER_T *p_ctx, const char *fileext)
VC_CONTAINER_STATUS_T vc_container_load_writer (VC_CONTAINER_T *p_ctx, const char *fileext)
void vc_container_unload (VC_CONTAINER_T *p_ctx)
Function Documentation
vc_container_load_reader()
VC_CONTAINER_STATUS_T vc_container_load_reader (VC_CONTAINER_T * p_ctx, const char * fileext)
Find and attempt to load & open reader, 'fileext' is a hint that can be used to speed up loading.
Definition at line 172 of file containers_loader.c.
References func, VC_CONTAINER_PRIVATE_T::module_handle, name, NULL, offset, VC_CONTAINER_T::priv, status, and vc_container_assert.
Referenced by vc_container_open_reader_with_io().
 {
    const char *name;
    void *handle = NULL;
    VC_CONTAINER_READER_OPEN_FUNC_T func;
    VC_CONTAINER_STATUS_T status;
    unsigned int i;
    int64_t offset;
    vc_container_assert(p_ctx && !p_ctx->priv->module_handle);
    /* FIXME: the missing part here is code that reads a configuration or
       searches the filesystem for container libraries. Instead, we currently
       rely on static arrays i.e. 'readers', 'writers', etc. */
    /* Before trying proper container readers, iterate through metadata
       readers to parse tags concatenated to start/end of stream */
    for(i = 0; metadata_readers[i]; i++)
    {
       if ((func = load_metadata_reader(&handle, metadata_readers[i])) != NULL)
       {
          status = (*func)(p_ctx);
          if(!status && p_ctx->priv->pf_close) p_ctx->priv->pf_close(p_ctx);
          reset_context(p_ctx);
          unload_library(handle);
          if(status == VC_CONTAINER_SUCCESS) break;
          if (status != VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED) goto error;
       }
    }
    /* Store the current position, in case any containers don't leave the stream
       at the start, and the IO layer can cope with the seek */
    offset = p_ctx->priv->io->offset;
    /* Now move to containers, try to find a readers using the file extension to name
       mapping first */
    if (fileext && (name = container_for_fileext(fileext)) != NULL && (func = load_reader(&handle, name)) != NULL)
    {
       status = (*func)(p_ctx);
       if(status == VC_CONTAINER_SUCCESS) goto success;
       unload_library(handle);
       if (status != VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED) goto error;
    }
    /* If there was no suitable mapping, iterate through all readers. */
    for(i = 0; readers[i]; i++)
    {
       if ((func = load_reader(&handle, readers[i])) != NULL)
       {
          if(vc_container_io_seek(p_ctx->priv->io, offset) != VC_CONTAINER_SUCCESS)
          {
             unload_library(handle);
             goto error;
          }
          status = (*func)(p_ctx);
          if(status == VC_CONTAINER_SUCCESS) goto success;
          reset_context(p_ctx);
          unload_library(handle);
          if (status != VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED) goto error;
       }
    }
  error:
    return VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED;
  success:
    p_ctx->priv->module_handle = handle;
    return VC_CONTAINER_SUCCESS;
 }
vc_container_load_writer()
VC_CONTAINER_STATUS_T vc_container_load_writer (VC_CONTAINER_T * p_ctx, const char * fileext)
Find and attempt to load & open writer, 'fileext' is a hint used to help in selecting the appropriate container format.
Definition at line 244 of file containers_loader.c.
References func, VC_CONTAINER_PRIVATE_T::module_handle, name, NULL, VC_CONTAINER_T::priv, status, vc_container_assert, and VC_CONTAINER_ERROR_FAILED.
Referenced by vc_container_open_writer().
 {
    const char *name;
    void *handle = NULL;
    VC_CONTAINER_WRITER_OPEN_FUNC_T func;
    VC_CONTAINER_STATUS_T status = VC_CONTAINER_ERROR_FAILED;
    unsigned int i;
    vc_container_assert(p_ctx && !p_ctx->priv->module_handle);
    /* Do we have a container mapping for this file extension? */
    if ((name = container_for_fileext(fileext)) != NULL && (func = load_writer(&handle, name)) != NULL)
    {
       status = (*func)(p_ctx);
       if(status == VC_CONTAINER_SUCCESS) goto success;
       unload_library(handle);
       if (status != VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED) goto error;
    }
    /* If there was no suitable mapping, iterate through all writers. */
    for(i = 0; writers[i]; i++)
    {
       if ((func = load_writer(&handle, writers[i])) != NULL)
       {
          status = (*func)(p_ctx);
          if(status == VC_CONTAINER_SUCCESS) goto success;
          unload_library(handle);
          if (status != VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED) goto error;
       }
    }
  error:
    return VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED;
  success:
    p_ctx->priv->module_handle = handle;
    return status;
 }
vc_container_unload()
void vc_container_unload (VC_CONTAINER_T * p_ctx)
Definition at line 284 of file containers_loader.c.
References VC_CONTAINER_PRIVATE_T::module_handle, and VC_CONTAINER_T::priv.
Referenced by vc_container_close().
 {
    if (p_ctx->priv->module_handle)
    {
       unload_library(p_ctx->priv->module_handle);
       p_ctx->priv->module_handle = NULL;
    }
 }