VideoCore Library: interface/mmal/core/mmal_port_private.h File Reference
mmal_port_private.h File Reference
#include "interface/mmal/mmal.h"
#include "interface/mmal/mmal_clock.h"
#include "interface/mmal/core/mmal_events_private.h"
Classes
struct MMAL_PORT_PRIVATE_T
Typedefs
typedef struct MMAL_PORT_PRIVATE_T MMAL_PORT_PRIVATE_T
typedef void(* MMAL_PORT_CLOCK_EVENT_CB) (MMAL_PORT_T *port, const MMAL_CLOCK_EVENT_T *event)
typedef void(* MMAL_PORT_CLOCK_REQUEST_CB) (MMAL_PORT_T *port, int64_t media_time, void *cb_data)
Functions
void mmal_port_buffer_header_callback (MMAL_PORT_T *port, MMAL_BUFFER_HEADER_T *buffer)
void mmal_port_event_send (MMAL_PORT_T *port, MMAL_BUFFER_HEADER_T *buffer)
MMAL_PORT_T * mmal_port_alloc (MMAL_COMPONENT_T *, MMAL_PORT_TYPE_T type, unsigned int extra_size)
void mmal_port_free (MMAL_PORT_T *port)
MMAL_PORT_T ** mmal_ports_alloc (MMAL_COMPONENT_T *, unsigned int ports_num, MMAL_PORT_TYPE_T type, unsigned int extra_size)
void mmal_ports_free (MMAL_PORT_T **ports, unsigned int ports_num)
void mmal_port_acquire (MMAL_PORT_T *port)
MMAL_STATUS_T mmal_port_release (MMAL_PORT_T *port)
MMAL_STATUS_T mmal_port_pause (MMAL_PORT_T *port, MMAL_BOOL_T pause)
MMAL_BOOL_T mmal_port_is_connected (MMAL_PORT_T *port)
MMAL_PORT_T * mmal_port_clock_alloc (MMAL_COMPONENT_T *component, unsigned int extra_size, MMAL_PORT_CLOCK_EVENT_CB event_cb)
void mmal_port_clock_free (MMAL_PORT_T *port)
MMAL_PORT_T ** mmal_ports_clock_alloc (MMAL_COMPONENT_T *component, unsigned int ports_num, unsigned int extra_size, MMAL_PORT_CLOCK_EVENT_CB event_cb)
void mmal_ports_clock_free (MMAL_PORT_T **ports, unsigned int ports_num)
MMAL_STATUS_T mmal_port_clock_request_add (MMAL_PORT_T *port, int64_t media_time, MMAL_PORT_CLOCK_REQUEST_CB cb, void *cb_data)
MMAL_STATUS_T mmal_port_clock_request_flush (MMAL_PORT_T *port)
MMAL_STATUS_T mmal_port_clock_reference_set (MMAL_PORT_T *port, MMAL_BOOL_T reference)
MMAL_BOOL_T mmal_port_clock_reference_get (MMAL_PORT_T *port)
MMAL_STATUS_T mmal_port_clock_active_set (MMAL_PORT_T *port, MMAL_BOOL_T active)
MMAL_BOOL_T mmal_port_clock_active_get (MMAL_PORT_T *port)
MMAL_STATUS_T mmal_port_clock_scale_set (MMAL_PORT_T *port, MMAL_RATIONAL_T scale)
MMAL_RATIONAL_T mmal_port_clock_scale_get (MMAL_PORT_T *port)
MMAL_STATUS_T mmal_port_clock_media_time_set (MMAL_PORT_T *port, int64_t media_time)
int64_t mmal_port_clock_media_time_get (MMAL_PORT_T *port)
MMAL_STATUS_T mmal_port_clock_update_threshold_set (MMAL_PORT_T *port, const MMAL_CLOCK_UPDATE_THRESHOLD_T *threshold)
MMAL_STATUS_T mmal_port_clock_update_threshold_get (MMAL_PORT_T *port, MMAL_CLOCK_UPDATE_THRESHOLD_T *threshold)
MMAL_STATUS_T mmal_port_clock_discont_threshold_set (MMAL_PORT_T *port, const MMAL_CLOCK_DISCONT_THRESHOLD_T *threshold)
MMAL_STATUS_T mmal_port_clock_discont_threshold_get (MMAL_PORT_T *port, MMAL_CLOCK_DISCONT_THRESHOLD_T *threshold)
MMAL_STATUS_T mmal_port_clock_request_threshold_set (MMAL_PORT_T *port, const MMAL_CLOCK_REQUEST_THRESHOLD_T *threshold)
MMAL_STATUS_T mmal_port_clock_request_threshold_get (MMAL_PORT_T *port, MMAL_CLOCK_REQUEST_THRESHOLD_T *threshold)
void mmal_port_clock_input_buffer_info (MMAL_PORT_T *port, const MMAL_CLOCK_BUFFER_INFO_T *info)
void mmal_port_clock_output_buffer_info (MMAL_PORT_T *port, const MMAL_CLOCK_BUFFER_INFO_T *info)
Typedef Documentation
MMAL_PORT_CLOCK_EVENT_CB
typedef void(* MMAL_PORT_CLOCK_EVENT_CB) (MMAL_PORT_T *port, const MMAL_CLOCK_EVENT_T *event)
Definition of a clock port event callback. Used to inform the client of a clock event that has occurred.
Parameters
port The clock port where the event occurred
event The event that has occurred
Definition at line 103 of file mmal_port_private.h.
MMAL_PORT_CLOCK_REQUEST_CB
typedef void(* MMAL_PORT_CLOCK_REQUEST_CB) (MMAL_PORT_T *port, int64_t media_time, void *cb_data)
Definition of a clock port request callback. This is invoked when the media-time requested by the client is reached.
Parameters
port The clock port which serviced the request
media_time The current media-time
cb_data Client-supplied data
Definition at line 148 of file mmal_port_private.h.
MMAL_PORT_PRIVATE_T
typedef struct MMAL_PORT_PRIVATE_T MMAL_PORT_PRIVATE_T
Definition of a port.
Function Documentation
mmal_port_acquire()
void mmal_port_acquire (MMAL_PORT_T * port)
Acquire a reference on a port
Definition at line 503 of file mmal_component.c.
References MMAL_PORT_T::component, LOG_TRACE, MMAL_PORT_T::name, MMAL_COMPONENT_T::priv, MMAL_COMPONENT_PRIVATE_T::refcount_ports, vcos_mutex_lock(), and vcos_mutex_unlock().
Referenced by mmal_port_payload_alloc().
 {
    MMAL_COMPONENT_T *component = port->component;
    MMAL_COMPONENT_CORE_PRIVATE_T *private = (MMAL_COMPONENT_CORE_PRIVATE_T *)component->priv;
    LOG_TRACE("port %s(%p), refcount %i", port->name, port,
              component->priv->refcount_ports);
    vcos_mutex_lock(&private->lock);
    component->priv->refcount_ports++;
    vcos_mutex_unlock(&private->lock);
 }
mmal_port_alloc()
MMAL_PORT_T* mmal_port_alloc (MMAL_COMPONENT_T * component, MMAL_PORT_TYPE_T type, unsigned int extra_size)
Allocate a port structure
Definition at line 158 of file mmal_port.c.
References MMAL_PORT_T::component, MMAL_PORT_PRIVATE_T::core, MMAL_PORT_PRIVATE_CORE_T::lock, LOG_ERROR, LOG_TRACE, MMAL_PORT_PRIVATE_T::module, MMAL_COMPONENT_T::name, MMAL_PORT_T::name, MMAL_PORT_PRIVATE_CORE_T::name, MMAL_PORT_PRIVATE_CORE_T::name_size, PORT_NAME_FORMAT, MMAL_PORT_T::priv, MMAL_PORT_T::type, and vcos_calloc().
Referenced by mmal_port_clock_alloc(), and mmal_ports_alloc().
 {
    MMAL_PORT_T *port;
    MMAL_PORT_PRIVATE_CORE_T *core;
    unsigned int name_size = strlen(component->name) + sizeof(PORT_NAME_FORMAT);
    unsigned int size = sizeof(*port) + sizeof(MMAL_PORT_PRIVATE_T) +
       sizeof(MMAL_PORT_PRIVATE_CORE_T) + name_size + extra_size;
    MMAL_BOOL_T lock = 0, lock_send = 0, lock_transit = 0, sema_transit = 0;
    MMAL_BOOL_T lock_stats = 0, lock_connection = 0;
    LOG_TRACE("component:%s type:%u extra:%u", component->name, type, extra_size);
    port = vcos_calloc(1, size, "mmal port");
    if (!port)
    {
       LOG_ERROR("failed to allocate port, size %u", size);
       return 0;
    }
    port->type = type;
    port->priv = (MMAL_PORT_PRIVATE_T *)(port+1);
    port->priv->core = core = (MMAL_PORT_PRIVATE_CORE_T *)(port->priv+1);
    if (extra_size)
       port->priv->module = (struct MMAL_PORT_MODULE_T *)(port->priv->core+1);
    port->component = component;
    port->name = core->name = ((char *)(port->priv->core+1)) + extra_size;
    core->name_size = name_size;
    mmal_port_name_update(port);
    core->queue_last = &core->queue_first;
    port->priv->pf_connect = mmal_port_connect_default;
    lock = vcos_mutex_create(&port->priv->core->lock, "mmal port lock") == VCOS_SUCCESS;
    lock_send = vcos_mutex_create(&port->priv->core->send_lock, "mmal port send lock") == VCOS_SUCCESS;
    lock_transit = vcos_mutex_create(&port->priv->core->transit_lock, "mmal port transit lock") == VCOS_SUCCESS;
    sema_transit = vcos_semaphore_create(&port->priv->core->transit_sema, "mmal port transit sema", 1) == VCOS_SUCCESS;
    lock_stats = vcos_mutex_create(&port->priv->core->stats_lock, "mmal stats lock") == VCOS_SUCCESS;
    lock_connection = vcos_mutex_create(&port->priv->core->connection_lock, "mmal connection lock") == VCOS_SUCCESS;
    if (!lock || !lock_send || !lock_transit || !sema_transit || !lock_stats || !lock_connection)
    {
       LOG_ERROR("%s: failed to create sync objects (%u,%u,%u,%u,%u,%u)",
             port->name, lock, lock_send, lock_transit, sema_transit, lock_stats, lock_connection);
       goto error;
    }
    port->format = mmal_format_alloc();
    if (!port->format)
    {
       LOG_ERROR("%s: failed to allocate format object", port->name);
       goto error;
    }
    port->priv->core->format_ptr_copy = port->format;
    LOG_TRACE("%s: created at %p", port->name, port);
    return port;
  error:
    if (lock) vcos_mutex_delete(&port->priv->core->lock);
    if (lock_send) vcos_mutex_delete(&port->priv->core->send_lock);
    if (lock_transit) vcos_mutex_delete(&port->priv->core->transit_lock);
    if (sema_transit) vcos_semaphore_delete(&port->priv->core->transit_sema);
    if (lock_stats) vcos_mutex_delete(&port->priv->core->stats_lock);
    if (lock_connection) vcos_mutex_delete(&port->priv->core->connection_lock);
    if (port->format) mmal_format_free(port->format);
    vcos_free(port);
    return 0;
 }
mmal_port_buffer_header_callback()
void mmal_port_buffer_header_callback (MMAL_PORT_T * port, MMAL_BUFFER_HEADER_T * buffer)
Callback called by components when a MMAL_BUFFER_HEADER_T needs to be sent back to the user
Buffer header callback.
Definition at line 897 of file mmal_port.c.
References MMAL_BUFFER_HEADER_T::cmd, MMAL_PORT_T::component, MMAL_BUFFER_HEADER_T::data, IN_TRANSIT_COUNT, MMAL_PORT_T::index, MMAL_BUFFER_HEADER_T::length, LOG_ERROR, LOG_TRACE, MMAL_COLLECT_PORT_STATS_ENABLED, MMAL_COMPONENT_T::name, MMAL_PORT_T::name, MMAL_BUFFER_HEADER_T::offset, MMAL_PORT_T::type, and vcos_verify.
Referenced by mmal_port_flush().
 {
 #ifdef ENABLE_MMAL_EXTRA_LOGGING
    LOG_TRACE("%s(%i:%i) port %p, buffer %p (%i,%p,%i,%i)",
              port->component->name, (int)port->type, (int)port->index, port, buffer,
              buffer ? (int)buffer->cmd : 0, buffer ? buffer->data : 0,
              buffer ? (int)buffer->offset : 0, buffer ? (int)buffer->length : 0);
 #endif
    if (!vcos_verify(IN_TRANSIT_COUNT(port) >= 0))
       LOG_ERROR("%s: buffer headers in transit < 0 (%d)", port->name, (int)IN_TRANSIT_COUNT(port));
    if (MMAL_COLLECT_PORT_STATS_ENABLED)
    {
       mmal_port_update_port_stats(port, MMAL_CORE_STATS_TX);
    }
    port->priv->core->buffer_header_callback(port, buffer);
    IN_TRANSIT_DECREMENT(port);
 }
mmal_port_clock_active_get()
MMAL_BOOL_T mmal_port_clock_active_get (MMAL_PORT_T * port)
Definition at line 671 of file mmal_port_clock.c.
References MMAL_PORT_CLOCK_T::clock, MMAL_PORT_PRIVATE_T::clock, mmal_clock_is_active(), and MMAL_PORT_T::priv.
 {
    return mmal_clock_is_active(port->priv->clock->clock);
 }
mmal_port_clock_active_set()
MMAL_STATUS_T mmal_port_clock_active_set (MMAL_PORT_T * port, MMAL_BOOL_T active)
Get/set the clock port's active state
Definition at line 656 of file mmal_port_clock.c.
References MMAL_PORT_CLOCK_T::clock, MMAL_PORT_PRIVATE_T::clock, MMAL_PORT_CLOCK_T::is_reference, mmal_clock_active_set(), MMAL_SUCCESS, MMAL_PORT_T::priv, and status.
 {
    MMAL_STATUS_T status;
    status = mmal_clock_active_set(port->priv->clock->clock, active);
    if (status != MMAL_SUCCESS)
       return status;
    if (port->priv->clock->is_reference)
       status = mmal_port_clock_forward_active_state(port, active);
    return status;
 }
mmal_port_clock_alloc()
MMAL_PORT_T* mmal_port_clock_alloc (MMAL_COMPONENT_T * component, unsigned int extra_size, MMAL_PORT_CLOCK_EVENT_CB event_cb)
Allocate a clock port.
Parameters
component The component requesting the alloc
extra_size Size of the port module
event_cb Clock event callback
Returns
Pointer to new clock port or NULL on failure.
Definition at line 563 of file mmal_port_clock.c.
References mmal_port_alloc(), MMAL_PORT_TYPE_CLOCK, and NULL.
 {
    MMAL_PORT_T *port;
    port = mmal_port_alloc(component, MMAL_PORT_TYPE_CLOCK,
                           extra_size + sizeof(MMAL_PORT_CLOCK_T));
    if (!port)
       return NULL;
    if (mmal_port_clock_setup(port, extra_size, event_cb) != MMAL_SUCCESS)
    {
       mmal_port_free(port);
       return NULL;
    }
    return port;
 }
mmal_port_clock_discont_threshold_get()
MMAL_STATUS_T mmal_port_clock_discont_threshold_get (MMAL_PORT_T * port, MMAL_CLOCK_DISCONT_THRESHOLD_T * threshold)
Definition at line 761 of file mmal_port_clock.c.
References MMAL_PORT_CLOCK_T::clock, MMAL_PORT_PRIVATE_T::clock, mmal_clock_discont_threshold_get(), and MMAL_PORT_T::priv.
 {
    return mmal_clock_discont_threshold_get(port->priv->clock->clock, threshold);
 }
mmal_port_clock_discont_threshold_set()
MMAL_STATUS_T mmal_port_clock_discont_threshold_set (MMAL_PORT_T * port, const MMAL_CLOCK_DISCONT_THRESHOLD_T * threshold)
Get/set the clock port's discontinuity threshold
Definition at line 745 of file mmal_port_clock.c.
References MMAL_PORT_CLOCK_T::clock, MMAL_PORT_PRIVATE_T::clock, MMAL_PORT_CLOCK_T::is_reference, mmal_clock_discont_threshold_set(), MMAL_SUCCESS, MMAL_PORT_T::priv, and status.
 {
    MMAL_STATUS_T status;
    status = mmal_clock_discont_threshold_set(port->priv->clock->clock, threshold);
    if (status != MMAL_SUCCESS)
       return status;
    if (port->priv->clock->is_reference)
       status = mmal_port_clock_forward_discont_threshold(port, threshold);
    return status;
 }
mmal_port_clock_free()
void mmal_port_clock_free (MMAL_PORT_T * port)
Free a clock port.
Parameters
port The clock port to free
Definition at line 583 of file mmal_port_clock.c.
Referenced by mmal_ports_clock_free().
 {
    mmal_port_clock_teardown(port);
    mmal_port_free(port);
 }
mmal_port_clock_input_buffer_info()
void mmal_port_clock_input_buffer_info (MMAL_PORT_T * port, const MMAL_CLOCK_BUFFER_INFO_T * info)
Provide information regarding a buffer received on the component's input/output port
Definition at line 791 of file mmal_port_clock.c.
References MMAL_PORT_CLOCK_T::buffer_info_reporting, MMAL_PORT_PRIVATE_T::clock, and MMAL_PORT_T::priv.
 {
    if (port->priv->clock->buffer_info_reporting)
       mmal_port_clock_forward_input_buffer_info(port, info);
 }
mmal_port_clock_media_time_get()
int64_t mmal_port_clock_media_time_get (MMAL_PORT_T * port)
Definition at line 716 of file mmal_port_clock.c.
References MMAL_PORT_CLOCK_T::clock, MMAL_PORT_PRIVATE_T::clock, mmal_clock_media_time_get(), and MMAL_PORT_T::priv.
 {
    return mmal_clock_media_time_get(port->priv->clock->clock);
 }
mmal_port_clock_media_time_set()
MMAL_STATUS_T mmal_port_clock_media_time_set (MMAL_PORT_T * port, int64_t media_time)
Get/set the clock port's media-time
Definition at line 698 of file mmal_port_clock.c.
References MMAL_PORT_CLOCK_T::clock, MMAL_PORT_PRIVATE_T::clock, MMAL_PORT_CLOCK_T::is_reference, LOG_DEBUG, mmal_clock_media_time_set(), MMAL_SUCCESS, MMAL_PORT_T::priv, and status.
 {
    MMAL_STATUS_T status;
    status = mmal_clock_media_time_set(port->priv->clock->clock, media_time);
    if (status != MMAL_SUCCESS)
    {
       LOG_DEBUG("clock media-time update ignored");
       return status;
    }
    if (port->priv->clock->is_reference)
       status = mmal_port_clock_forward_media_time(port, media_time);
    return status;
 }
mmal_port_clock_output_buffer_info()
void mmal_port_clock_output_buffer_info (MMAL_PORT_T * port, const MMAL_CLOCK_BUFFER_INFO_T * info)
Definition at line 798 of file mmal_port_clock.c.
References MMAL_PORT_CLOCK_T::buffer_info_reporting, MMAL_PORT_PRIVATE_T::clock, and MMAL_PORT_T::priv.
 {
    if (port->priv->clock->buffer_info_reporting)
       mmal_port_clock_forward_output_buffer_info(port, info);
 }
mmal_port_clock_reference_get()
MMAL_BOOL_T mmal_port_clock_reference_get (MMAL_PORT_T * port)
Definition at line 650 of file mmal_port_clock.c.
References MMAL_PORT_PRIVATE_T::clock, MMAL_PORT_CLOCK_T::is_reference, and MMAL_PORT_T::priv.
 {
    return port->priv->clock->is_reference;
 }
mmal_port_clock_reference_set()
MMAL_STATUS_T mmal_port_clock_reference_set (MMAL_PORT_T * port, MMAL_BOOL_T reference)
Get/set the clock port's reference state
Definition at line 643 of file mmal_port_clock.c.
References MMAL_PORT_PRIVATE_T::clock, MMAL_PORT_CLOCK_T::is_reference, MMAL_SUCCESS, and MMAL_PORT_T::priv.
 {
    port->priv->clock->is_reference = reference;
    return MMAL_SUCCESS;
 }
mmal_port_clock_request_add()
MMAL_STATUS_T mmal_port_clock_request_add (MMAL_PORT_T * port, int64_t media_time, MMAL_PORT_CLOCK_REQUEST_CB cb, void * cb_data)
Register a request with the clock port. When the specified media-time is reached, the clock port will invoke the supplied callback.
Parameters
port The clock port
media_time The media-time at which the callback should be invoked (microseconds)
cb Callback to invoke
cb_data Client-supplied callback data
Returns
MMAL_SUCCESS on success
Definition at line 629 of file mmal_port_clock.c.
References MMAL_PORT_CLOCK_T::clock, MMAL_PORT_PRIVATE_T::clock, mmal_clock_request_add(), and MMAL_PORT_T::priv.
 {
    return mmal_clock_request_add(port->priv->clock->clock, media_time,
                                  mmal_port_clock_request_cb, cb_data, (MMAL_CLOCK_VOID_FP)cb);
 }
mmal_port_clock_request_flush()
MMAL_STATUS_T mmal_port_clock_request_flush (MMAL_PORT_T * port)
Remove all previously registered clock port requests.
Parameters
port The clock port
Returns
MMAL_SUCCESS on success
Definition at line 637 of file mmal_port_clock.c.
References MMAL_PORT_CLOCK_T::clock, MMAL_PORT_PRIVATE_T::clock, mmal_clock_request_flush(), and MMAL_PORT_T::priv.
 {
    return mmal_clock_request_flush(port->priv->clock->clock);
 }
mmal_port_clock_request_threshold_get()
MMAL_STATUS_T mmal_port_clock_request_threshold_get (MMAL_PORT_T * port, MMAL_CLOCK_REQUEST_THRESHOLD_T * threshold)
Definition at line 784 of file mmal_port_clock.c.
References MMAL_PORT_CLOCK_T::clock, MMAL_PORT_PRIVATE_T::clock, mmal_clock_request_threshold_get(), and MMAL_PORT_T::priv.
 {
    return mmal_clock_request_threshold_get(port->priv->clock->clock, threshold);
 }
mmal_port_clock_request_threshold_set()
MMAL_STATUS_T mmal_port_clock_request_threshold_set (MMAL_PORT_T * port, const MMAL_CLOCK_REQUEST_THRESHOLD_T * threshold)
Get/set the clock port's request threshold
Definition at line 768 of file mmal_port_clock.c.
References MMAL_PORT_CLOCK_T::clock, MMAL_PORT_PRIVATE_T::clock, MMAL_PORT_CLOCK_T::is_reference, mmal_clock_request_threshold_set(), MMAL_SUCCESS, MMAL_PORT_T::priv, and status.
 {
    MMAL_STATUS_T status;
    status = mmal_clock_request_threshold_set(port->priv->clock->clock, threshold);
    if (status != MMAL_SUCCESS)
       return status;
    if (port->priv->clock->is_reference)
       status = mmal_port_clock_forward_request_threshold(port, threshold);
    return status;
 }
mmal_port_clock_scale_get()
MMAL_RATIONAL_T mmal_port_clock_scale_get (MMAL_PORT_T * port)
Definition at line 692 of file mmal_port_clock.c.
References MMAL_PORT_CLOCK_T::clock, MMAL_PORT_PRIVATE_T::clock, mmal_clock_scale_get(), and MMAL_PORT_T::priv.
 {
    return mmal_clock_scale_get(port->priv->clock->clock);
 }
mmal_port_clock_scale_set()
MMAL_STATUS_T mmal_port_clock_scale_set (MMAL_PORT_T * port, MMAL_RATIONAL_T scale)
Get/set the clock port's scale
Definition at line 677 of file mmal_port_clock.c.
References MMAL_PORT_CLOCK_T::clock, MMAL_PORT_PRIVATE_T::clock, MMAL_PORT_CLOCK_T::is_reference, mmal_clock_scale_set(), MMAL_SUCCESS, MMAL_PORT_T::priv, and status.
 {
    MMAL_STATUS_T status;
    status = mmal_clock_scale_set(port->priv->clock->clock, scale);
    if (status != MMAL_SUCCESS)
       return status;
    if (port->priv->clock->is_reference)
       status = mmal_port_clock_forward_scale(port, scale);
    return status;
 }
mmal_port_clock_update_threshold_get()
MMAL_STATUS_T mmal_port_clock_update_threshold_get (MMAL_PORT_T * port, MMAL_CLOCK_UPDATE_THRESHOLD_T * threshold)
Definition at line 738 of file mmal_port_clock.c.
References MMAL_PORT_CLOCK_T::clock, MMAL_PORT_PRIVATE_T::clock, mmal_clock_update_threshold_get(), and MMAL_PORT_T::priv.
 {
    return mmal_clock_update_threshold_get(port->priv->clock->clock, threshold);
 }
mmal_port_clock_update_threshold_set()
MMAL_STATUS_T mmal_port_clock_update_threshold_set (MMAL_PORT_T * port, const MMAL_CLOCK_UPDATE_THRESHOLD_T * threshold)
Get/set the clock port's update threshold
Definition at line 722 of file mmal_port_clock.c.
References MMAL_PORT_CLOCK_T::clock, MMAL_PORT_PRIVATE_T::clock, MMAL_PORT_CLOCK_T::is_reference, mmal_clock_update_threshold_set(), MMAL_SUCCESS, MMAL_PORT_T::priv, and status.
 {
    MMAL_STATUS_T status;
    status = mmal_clock_update_threshold_set(port->priv->clock->clock, threshold);
    if (status != MMAL_SUCCESS)
       return status;
    if (port->priv->clock->is_reference)
       status = mmal_port_clock_forward_update_threshold(port, threshold);
    return status;
 }
mmal_port_event_send()
void mmal_port_event_send (MMAL_PORT_T * port, MMAL_BUFFER_HEADER_T * buffer)
Callback called by components when an event MMAL_BUFFER_HEADER_T needs to be sent to the user. Events differ from ordinary buffer headers because they originate from the component and do not return data from the client to the component.
Event callback
Definition at line 920 of file mmal_port.c.
References MMAL_PORT_PRIVATE_CORE_T::buffer_header_callback, MMAL_PORT_PRIVATE_T::core, MMAL_PORT_T::index, LOG_ERROR, mmal_buffer_header_release(), MMAL_PORT_T::priv, and MMAL_PORT_T::type.
Referenced by mmal_event_eos_send(), mmal_event_error_send(), and mmal_event_forward().
 {
    if (port->priv->core->buffer_header_callback)
    {
       port->priv->core->buffer_header_callback(port, buffer);
    }
    else
    {
       LOG_ERROR("event lost on port %i,%i (buffer header callback not defined)",
                 (int)port->type, (int)port->index);
       mmal_buffer_header_release(buffer);
    }
 }
mmal_port_free()
void mmal_port_free (MMAL_PORT_T * port)
Free a port structure
Definition at line 228 of file mmal_port.c.
References MMAL_PORT_PRIVATE_CORE_T::connection_lock, MMAL_PORT_PRIVATE_T::core, MMAL_PORT_T::format, MMAL_PORT_PRIVATE_CORE_T::format_ptr_copy, MMAL_PORT_PRIVATE_CORE_T::lock, LOG_TRACE, mmal_format_free(), MMAL_PORT_T::name, MMAL_PORT_T::priv, MMAL_PORT_PRIVATE_CORE_T::send_lock, MMAL_PORT_PRIVATE_CORE_T::stats_lock, MMAL_PORT_PRIVATE_CORE_T::transit_lock, MMAL_PORT_PRIVATE_CORE_T::transit_sema, vcos_assert, vcos_free(), vcos_mutex_delete(), and vcos_semaphore_delete().
Referenced by mmal_ports_free().
 {
    LOG_TRACE("%s at %p", port ? port->name : "<invalid>", port);
    if (!port)
       return;
    vcos_assert(port->format == port->priv->core->format_ptr_copy);
    mmal_format_free(port->priv->core->format_ptr_copy);
    vcos_mutex_delete(&port->priv->core->connection_lock);
    vcos_mutex_delete(&port->priv->core->stats_lock);
    vcos_semaphore_delete(&port->priv->core->transit_sema);
    vcos_mutex_delete(&port->priv->core->transit_lock);
    vcos_mutex_delete(&port->priv->core->send_lock);
    vcos_mutex_delete(&port->priv->core->lock);
    vcos_free(port);
 }
mmal_port_is_connected()
MMAL_BOOL_T mmal_port_is_connected (MMAL_PORT_T * port)
Returns whether a port is connected or not
Definition at line 1506 of file mmal_port.c.
References MMAL_PORT_PRIVATE_CORE_T::connected_port, MMAL_PORT_PRIVATE_T::core, and MMAL_PORT_T::priv.
 {
    return !!port->priv->core->connected_port;
 }
mmal_port_pause()
MMAL_STATUS_T mmal_port_pause (MMAL_PORT_T * port, MMAL_BOOL_T pause)
Pause processing on a port
Definition at line 1464 of file mmal_port.c.
References MMAL_PORT_PRIVATE_T::core, MMAL_PORT_T::is_enabled, MMAL_PORT_PRIVATE_CORE_T::is_paused, LOCK_SENDING, MMAL_SUCCESS, MMAL_BUFFER_HEADER_T::next, MMAL_PORT_PRIVATE_T::pf_send, MMAL_PORT_T::priv, MMAL_PORT_PRIVATE_CORE_T::queue_first, MMAL_PORT_PRIVATE_CORE_T::queue_last, status, and UNLOCK_SENDING.
Referenced by mmal_component_disable(), and mmal_component_enable().
 {
    MMAL_STATUS_T status = MMAL_SUCCESS;
    LOCK_SENDING(port);
    /* When resuming from pause, we send all our queued buffers to the port */
    if (!pause && port->is_enabled)
    {
       MMAL_BUFFER_HEADER_T *buffer = port->priv->core->queue_first;
       while (buffer)
       {
          MMAL_BUFFER_HEADER_T *next = buffer->next;
          status = port->priv->pf_send(port, buffer);
          if (status != MMAL_SUCCESS)
          {
             buffer->next = next;
             break;
          }
          buffer = next;
       }
       /* If for some reason we could not send one of the buffers, we just
        * leave all the buffers in our internal queue and return an error. */
       if (status != MMAL_SUCCESS)
       {
          port->priv->core->queue_first = buffer;
       }
       else
       {
          port->priv->core->queue_first = 0;
          port->priv->core->queue_last = &port->priv->core->queue_first;
       }
    }
    if (status == MMAL_SUCCESS)
       port->priv->core->is_paused = pause;
    UNLOCK_SENDING(port);
    return status;
 }
mmal_port_release()
MMAL_STATUS_T mmal_port_release (MMAL_PORT_T * port)
Release a reference on a port
Definition at line 517 of file mmal_component.c.
References MMAL_PORT_T::component, LOG_TRACE, MMAL_EINVAL, MMAL_SUCCESS, MMAL_PORT_T::name, MMAL_COMPONENT_T::priv, MMAL_COMPONENT_PRIVATE_T::refcount, MMAL_COMPONENT_PRIVATE_T::refcount_ports, vcos_mutex_lock(), vcos_mutex_unlock(), and vcos_verify.
Referenced by mmal_port_payload_free().
 {
    MMAL_COMPONENT_T *component = port->component;
    MMAL_COMPONENT_CORE_PRIVATE_T *private = (MMAL_COMPONENT_CORE_PRIVATE_T *)component->priv;
    LOG_TRACE("port %s(%p), refcount %i", port->name, port,
              component->priv->refcount_ports);
    /* Sanity check the refcount */
    if (!vcos_verify(component->priv->refcount_ports > 0))
       return MMAL_EINVAL;
    vcos_mutex_lock(&private->lock);
    if (--component->priv->refcount_ports ||
        component->priv->refcount || private->destruction_pending)
    {
       vcos_mutex_unlock(&private->lock);
       return MMAL_SUCCESS;
    }
    vcos_mutex_unlock(&private->lock);
    return mmal_component_destroy_internal(component);
 }
mmal_ports_alloc()
MMAL_PORT_T** mmal_ports_alloc (MMAL_COMPONENT_T * component, unsigned int ports_num, MMAL_PORT_TYPE_T type, unsigned int extra_size)
Allocate an array of ports
Definition at line 247 of file mmal_port.c.
References MMAL_PORT_T::index, mmal_port_alloc(), and vcos_calloc().
Referenced by mmal_ports_clock_alloc().
 {
    MMAL_PORT_T **ports;
    unsigned int i;
    ports = vcos_calloc(1, sizeof(MMAL_PORT_T *) * ports_num, "mmal ports");
    if (!ports)
       return 0;
    for (i = 0; i < ports_num; i++)
    {
       ports[i] = mmal_port_alloc(component, type, extra_size);
       if (!ports[i])
          break;
       ports[i]->index = i;
       mmal_port_name_update(ports[i]);
    }
    if (i != ports_num)
    {
       for (ports_num = i, i = 0; i < ports_num; i++)
          mmal_port_free(ports[i]);
       vcos_free(ports);
       return 0;
    }
    return ports;
 }
mmal_ports_clock_alloc()
MMAL_PORT_T** mmal_ports_clock_alloc (MMAL_COMPONENT_T * component, unsigned int ports_num, unsigned int extra_size, MMAL_PORT_CLOCK_EVENT_CB event_cb)
Allocate an array of clock ports.
Parameters
component The component requesting the alloc
ports_num Number of ports to allocate
extra_size Size of the port module
event_cb Clock event callback
Returns
Pointer to a new array of clock ports or NULL on failure.
Definition at line 590 of file mmal_port_clock.c.
References MMAL_PORT_TYPE_CLOCK, mmal_ports_alloc(), and NULL.
 {
    unsigned int i;
    MMAL_PORT_T **ports;
    ports = mmal_ports_alloc(component, ports_num, MMAL_PORT_TYPE_CLOCK,
                             extra_size + sizeof(MMAL_PORT_CLOCK_T));
    if (!ports)
       return NULL;
    for (i = 0; i < ports_num; i++)
    {
       if (mmal_port_clock_setup(ports[i], extra_size, event_cb) != MMAL_SUCCESS)
          break;
    }
    if (i != ports_num)
    {
       for (ports_num = i, i = 0; i < ports_num; i++)
          mmal_port_clock_free(ports[i]);
       vcos_free(ports);
       return NULL;
    }
    return ports;
 }
mmal_ports_clock_free()
void mmal_ports_clock_free (MMAL_PORT_T ** ports, unsigned int ports_num)
Free an array of clock ports.
Parameters
ports The clock ports to free
ports_num Number of ports to free
Definition at line 619 of file mmal_port_clock.c.
References mmal_port_clock_free(), and vcos_free().
 {
    unsigned int i;
    for (i = 0; i < ports_num; i++)
       mmal_port_clock_free(ports[i]);
    vcos_free(ports);
 }
mmal_ports_free()
void mmal_ports_free (MMAL_PORT_T ** ports, unsigned int ports_num)
Free an array of ports
Definition at line 278 of file mmal_port.c.
References mmal_port_free(), and vcos_free().
 {
    unsigned int i;
    for (i = 0; i < ports_num; i++)
       mmal_port_free(ports[i]);
    vcos_free(ports);
 }