VideoCore Library: interface/mmal/vc/mmal_vc_opaque_alloc.c File Reference
mmal_vc_opaque_alloc.c File Reference
#include "interface/mmal/vc/mmal_vc_opaque_alloc.h"
#include "mmal_vc_msgs.h"
#include "mmal_vc_client_priv.h"
Functions
MMAL_OPAQUE_IMAGE_HANDLE_T mmal_vc_opaque_alloc_desc (const char *description)
MMAL_OPAQUE_IMAGE_HANDLE_T mmal_vc_opaque_alloc (void)
MMAL_STATUS_T mmal_vc_opaque_acquire (unsigned int handle)
MMAL_STATUS_T mmal_vc_opaque_release (unsigned int handle)
Function Documentation
mmal_vc_opaque_acquire()
MMAL_STATUS_T mmal_vc_opaque_acquire (unsigned int handle)
Definition at line 56 of file mmal_vc_opaque_alloc.c.
References mmal_worker_opaque_allocator::handle, mmal_worker_opaque_allocator::header, len, MMAL_FALSE, MMAL_SUCCESS, mmal_vc_get_client(), mmal_vc_sendwait_message(), MMAL_WORKER_OPAQUE_ALLOCATOR, MMAL_WORKER_OPAQUE_MEM_ACQUIRE, mmal_worker_opaque_allocator::op, and mmal_worker_opaque_allocator::status.
 {
    MMAL_STATUS_T ret;
    mmal_worker_opaque_allocator msg;
    size_t len = sizeof(msg);
    msg.handle = handle;
    msg.op = MMAL_WORKER_OPAQUE_MEM_ACQUIRE;
    ret = mmal_vc_sendwait_message(mmal_vc_get_client(),
                                   &msg.header, sizeof(msg),
                                   MMAL_WORKER_OPAQUE_ALLOCATOR,
                                   &msg, &len, MMAL_FALSE);
    if (ret == MMAL_SUCCESS)
       ret = msg.status;
    return ret;
 }
mmal_vc_opaque_alloc()
MMAL_OPAQUE_IMAGE_HANDLE_T mmal_vc_opaque_alloc (void)
Allocate an opaque image on VideoCore.
Returns
allocated handle, or zero if allocation failed.
Definition at line 51 of file mmal_vc_opaque_alloc.c.
References mmal_vc_opaque_alloc_desc().
 {
    return mmal_vc_opaque_alloc_desc("?");
 }
mmal_vc_opaque_alloc_desc()
MMAL_OPAQUE_IMAGE_HANDLE_T mmal_vc_opaque_alloc_desc (const char * description)
Allocate an opaque image on VideoCore, providing a description.
Returns
allocated handle, or zero if allocation failed.
Definition at line 32 of file mmal_vc_opaque_alloc.c.
References mmal_worker_opaque_allocator::description, mmal_worker_opaque_allocator::handle, mmal_worker_opaque_allocator::header, len, MMAL_FALSE, MMAL_SUCCESS, mmal_vc_get_client(), mmal_vc_sendwait_message(), MMAL_WORKER_OPAQUE_ALLOCATOR_DESC, MMAL_WORKER_OPAQUE_MEM_ALLOC, mmal_worker_opaque_allocator::op, and vcos_safe_strcpy().
Referenced by mmal_vc_opaque_alloc().
 {
    MMAL_STATUS_T ret;
    MMAL_OPAQUE_IMAGE_HANDLE_T h = 0;
    mmal_worker_opaque_allocator msg;
    size_t len = sizeof(msg);
    msg.op = MMAL_WORKER_OPAQUE_MEM_ALLOC;
    vcos_safe_strcpy(msg.description, description, sizeof(msg.description), 0);
    ret = mmal_vc_sendwait_message(mmal_vc_get_client(),
                                   &msg.header, sizeof(msg),
                                   MMAL_WORKER_OPAQUE_ALLOCATOR_DESC,
                                   &msg, &len, MMAL_FALSE);
    if (ret == MMAL_SUCCESS)
    {
       h = msg.handle;
    }
    return h;
 }
mmal_vc_opaque_release()
MMAL_STATUS_T mmal_vc_opaque_release (unsigned int handle)
Definition at line 72 of file mmal_vc_opaque_alloc.c.
References mmal_worker_opaque_allocator::handle, mmal_worker_opaque_allocator::header, len, MMAL_FALSE, MMAL_SUCCESS, mmal_vc_get_client(), mmal_vc_sendwait_message(), MMAL_WORKER_OPAQUE_ALLOCATOR, MMAL_WORKER_OPAQUE_MEM_RELEASE, mmal_worker_opaque_allocator::op, and mmal_worker_opaque_allocator::status.
 {
    MMAL_STATUS_T ret;
    mmal_worker_opaque_allocator msg;
    size_t len = sizeof(msg);
    msg.handle = handle;
    msg.op = MMAL_WORKER_OPAQUE_MEM_RELEASE;
    ret = mmal_vc_sendwait_message(mmal_vc_get_client(),
                                   &msg.header, sizeof(msg),
                                   MMAL_WORKER_OPAQUE_ALLOCATOR,
                                   &msg, &len, MMAL_FALSE);
    if (ret == MMAL_SUCCESS)
       ret = msg.status;
    return ret;
 }