VideoCore Library: containers/raw/raw_video_reader.c File Reference
raw_video_reader.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "containers/core/containers_private.h"
#include "containers/core/containers_io_helpers.h"
#include "containers/core/containers_utils.h"
#include "containers/core/containers_logging.h"
#include "raw_video_common.h"
Classes
struct VC_CONTAINER_MODULE_T
Macros
#define FILE_HEADER_SIZE_MAX 1024
#define FRAME_HEADER_SIZE_MAX 256
#define OPTION_SIZE_MAX 32
Typedefs
typedef struct VC_CONTAINER_MODULE_T VC_CONTAINER_MODULE_T
Functions
VC_CONTAINER_STATUS_T rawvideo_reader_open (VC_CONTAINER_T *)
Macro Definition Documentation
FILE_HEADER_SIZE_MAX
#define FILE_HEADER_SIZE_MAX 1024
Definition at line 41 of file raw_video_reader.c.
FRAME_HEADER_SIZE_MAX
#define FRAME_HEADER_SIZE_MAX 256
Definition at line 42 of file raw_video_reader.c.
OPTION_SIZE_MAX
#define OPTION_SIZE_MAX 32
Definition at line 43 of file raw_video_reader.c.
Typedef Documentation
VC_CONTAINER_MODULE_T
typedef struct VC_CONTAINER_MODULE_T VC_CONTAINER_MODULE_T
Function Documentation
rawvideo_reader_open()
VC_CONTAINER_STATUS_T rawvideo_reader_open (VC_CONTAINER_T * ctx)
Definition at line 360 of file raw_video_reader.c.
References error(), VC_CONTAINER_ES_FORMAT_T::es_type, extension, VC_CONTAINER_TRACK_T::format, VC_CONTAINER_VIDEO_FORMAT_T::frame_rate_den, VC_CONTAINER_VIDEO_FORMAT_T::frame_rate_num, VC_CONTAINER_TRACK_T::is_enabled, LOG_DEBUG, VC_CONTAINER_PRIVATE_T::module, VC_CONTAINER_VIDEO_FORMAT_T::par_den, VC_CONTAINER_VIDEO_FORMAT_T::par_num, PEEK_BYTES, VC_CONTAINER_T::priv, VC_CONTAINER_MODULE_T::status, VC_CONTAINER_MODULE_T::track, VC_CONTAINER_T::tracks, VC_CONTAINER_T::tracks_num, VC_CONTAINER_ES_FORMAT_T::type, VC_CONTAINER_PRIVATE_T::uri, vc_container_allocate_track(), VC_CONTAINER_ERROR_FORMAT_INVALID, VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED, VC_CONTAINER_ERROR_OUT_OF_MEMORY, VC_CONTAINER_ES_TYPE_VIDEO, vc_uri_find_query(), vc_uri_path_extension(), VC_CONTAINER_ES_SPECIFIC_FORMAT_T::video, and VC_CONTAINER_MODULE_T::yuv4mpeg2.
 {
    VC_CONTAINER_STATUS_T status = VC_CONTAINER_ERROR_FORMAT_INVALID;
    const char *extension = vc_uri_path_extension(ctx->priv->uri);
    VC_CONTAINER_MODULE_T *module = 0;
    bool yuv4mpeg2 = false;
    uint8_t h[10];
    /* Check if the user has specified a container */
    vc_uri_find_query(ctx->priv->uri, 0, "container", &extension);
    /* Check for the YUV4MPEG2 signature */
    if (PEEK_BYTES(ctx, h, sizeof(h)) != sizeof(h))
       return VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED;
    if (!memcmp(h, "YUV4MPEG2 ", sizeof(h)))
       yuv4mpeg2 = true;
    /* Or check if the extension is supported */
    if (!yuv4mpeg2 &&
        !(extension && !strcasecmp(extension, "yuv")))
       return VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED;
    LOG_DEBUG(ctx, "using raw video reader");
    /* Allocate our context */
    module = malloc(sizeof(*module));
    if (!module) return VC_CONTAINER_ERROR_OUT_OF_MEMORY;
    memset(module, 0, sizeof(*module));
    ctx->priv->module = module;
    ctx->tracks_num = 1;
    ctx->tracks = &module->track;
    ctx->tracks[0] = vc_container_allocate_track(ctx, 0);
    if (!ctx->tracks[0])
    {
       status = VC_CONTAINER_ERROR_OUT_OF_MEMORY;
       goto error;
    }
    ctx->tracks[0]->format->es_type = VC_CONTAINER_ES_TYPE_VIDEO;
    ctx->tracks[0]->is_enabled = true;
    ctx->tracks[0]->format->type->video.frame_rate_num = 25;
    ctx->tracks[0]->format->type->video.frame_rate_den = 1;
    ctx->tracks[0]->format->type->video.par_num = 1;
    ctx->tracks[0]->format->type->video.par_den = 1;
    if (yuv4mpeg2)
    {
       status = read_yuv4mpeg2_file_header(ctx);
       if (status != VC_CONTAINER_SUCCESS)
          goto error;
       module->data_offset = STREAM_POSITION(ctx);
       status = read_yuv4mpeg2_frame_header(ctx);
       if (status != VC_CONTAINER_SUCCESS)
          goto error;
       module->frame_header = true;
    }
    else
    {
       VC_CONTAINER_FOURCC_T codec;
       unsigned int width, height, fr_num, fr_den, block_size;
       status = rawvideo_parse_uri(ctx, &codec, &width, &height,
          &fr_num, &fr_den, &block_size);
       if (status != VC_CONTAINER_SUCCESS)
          goto error;
       ctx->tracks[0]->format->codec = codec;
       ctx->tracks[0]->format->type->video.width = width;
       ctx->tracks[0]->format->type->video.height = height;
       if (fr_num && fr_den)
       {
          ctx->tracks[0]->format->type->video.frame_rate_num = fr_num;
          ctx->tracks[0]->format->type->video.frame_rate_den = fr_den;
       }
       module->block_size = block_size;
    }
    /*
     *  We now have all the information we really need to start playing the stream
     */
    LOG_INFO(ctx, "rawvideo %4.4s/%ix%i/fps:%i:%i/size:%i",
       (char *)&ctx->tracks[0]->format->codec,
       ctx->tracks[0]->format->type->video.width,
       ctx->tracks[0]->format->type->video.height,
       ctx->tracks[0]->format->type->video.frame_rate_num,
       ctx->tracks[0]->format->type->video.frame_rate_den, module->block_size);
    ctx->priv->pf_close = rawvideo_reader_close;
    ctx->priv->pf_read = rawvideo_reader_read;
    ctx->priv->pf_seek = rawvideo_reader_seek;
    module->yuv4mpeg2 = yuv4mpeg2;
    return VC_CONTAINER_SUCCESS;
  error:
    LOG_DEBUG(ctx, "rawvideo: error opening stream (%i)", status);
    rawvideo_reader_close(ctx);
    return status;
 }