VideoCore Library: containers/raw/raw_video_writer.c File Reference
raw_video_writer.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include "containers/core/containers_private.h"
#include "containers/core/containers_io_helpers.h"
#include "containers/core/containers_utils.h"
#include "containers/core/containers_logging.h"
#include "raw_video_common.h"
Classes
struct VC_CONTAINER_MODULE_T
Typedefs
typedef struct VC_CONTAINER_MODULE_T VC_CONTAINER_MODULE_T
Functions
VC_CONTAINER_STATUS_T rawvideo_writer_open (VC_CONTAINER_T *)
Typedef Documentation
VC_CONTAINER_MODULE_T
typedef struct VC_CONTAINER_MODULE_T VC_CONTAINER_MODULE_T
Function Documentation
rawvideo_writer_open()
VC_CONTAINER_STATUS_T rawvideo_writer_open (VC_CONTAINER_T * ctx)
Definition at line 220 of file raw_video_writer.c.
References error(), extension, LOG_DEBUG, VC_CONTAINER_PRIVATE_T::module, VC_CONTAINER_PRIVATE_T::pf_close, VC_CONTAINER_T::priv, VC_CONTAINER_MODULE_T::track, VC_CONTAINER_T::tracks, VC_CONTAINER_PRIVATE_T::uri, VC_CONTAINER_ERROR_FORMAT_INVALID, VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED, VC_CONTAINER_ERROR_OUT_OF_MEMORY, vc_uri_find_query(), vc_uri_path_extension(), and VC_CONTAINER_MODULE_T::yuv4mpeg2.
 {
    VC_CONTAINER_STATUS_T status = VC_CONTAINER_ERROR_FORMAT_INVALID;
    const char *extension = vc_uri_path_extension(ctx->priv->uri);
    VC_CONTAINER_MODULE_T *module;
    bool yuv4mpeg2 = false;
    /* Check if the user has specified a container */
    vc_uri_find_query(ctx->priv->uri, 0, "container", &extension);
    /* Check we're the right writer for this */
    if(!extension)
       return VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED;
    if(!strcasecmp(extension, "y4m") || !strcasecmp(extension, "yuv4mpeg2"))
       yuv4mpeg2 = true;
    if(!yuv4mpeg2 && strcasecmp(extension, "yuv"))
       return VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED;
    LOG_DEBUG(ctx, "using rawvideo writer");
    /* Allocate our context */
    module = malloc(sizeof(*module));
    if (!module) { status = VC_CONTAINER_ERROR_OUT_OF_MEMORY; goto error; }
    memset(module, 0, sizeof(*module));
    ctx->priv->module = module;
    ctx->tracks = &module->track;
    module->yuv4mpeg2 = yuv4mpeg2;
    ctx->priv->pf_close = rawvideo_writer_close;
    ctx->priv->pf_write = rawvideo_writer_write;
    ctx->priv->pf_control = rawvideo_writer_control;
    return VC_CONTAINER_SUCCESS;
  error:
    LOG_DEBUG(ctx, "rawvideo: error opening stream (%i)", status);
    return status;
 }