VideoCore Library: containers/rtsp/rtsp_reader.c File Reference
rtsp_reader.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include "containers/core/containers_private.h"
#include "containers/core/containers_io_helpers.h"
#include "containers/core/containers_utils.h"
#include "containers/core/containers_logging.h"
#include "containers/core/containers_list.h"
#include "containers/core/containers_uri.h"
Classes
struct rtsp_header_tag
struct VC_CONTAINER_TRACK_MODULE_T
struct VC_CONTAINER_MODULE_T
Macros
#define CONTAINER_IS_BIG_ENDIAN
#define CONTAINER_HELPER_LOG_INDENT(a) 0
#define RTSP_TRACKS_MAX 4
#define COMMS_BUFFER_SIZE 2048
#define RTSP_URI_LENGTH_MAX 1024
#define SESSION_HEADER_LENGTH_MAX 100
#define DATA_UNAVAILABLE_READ_TIMEOUT_MS 1
#define UDP_READ_BUFFER_SIZE 520000
#define DYNAMIC_PORT_ATTEMPTS_MAX 16
#define RTSP_SCHEME "rtsp:"
#define RTP_SCHEME "rtp"
#define RTSP_PKT_SCHEME "rtsppkt:"
#define RTSP_NETWORK_URI_START "rtsp://"
#define RTSP_NETWORK_URI_START_LENGTH (sizeof(RTSP_NETWORK_URI_START)-1)
#define HEADER_LIST_INITIAL_CAPACITY 16
#define RTSP_REQUEST_LINE_FORMAT "%s %s RTSP/1.0\r\n"
#define TRAILING_HEADERS_FORMAT "CSeq: %u\r\nConnection: Keep-Alive\r\nUser-Agent: Broadcom/1.0\r\n\r\n"
#define TRANSPORT_HEADER_FORMAT "Transport: RTP/AVP;unicast;client_port=%hu-%hu;mode=play\r\n"
#define SESSION_HEADER_FORMAT "Session: %s\r\n"
#define RTSP_MAJOR_VERSION 1
#define RTSP_MINOR_VERSION 0
#define RTSP_STATUS_OK 200
#define RTSP_STATUS_MULTIPLE_CHOICES 300
#define PORT_BUFFER_SIZE 6
#define FIRST_DYNAMIC_PORT 0xC000
#define LAST_DYNAMIC_PORT 0xFFF0
#define RTP_PATH_EXTENSION_FORMAT ".t%u.pkt"
#define RTP_PATH_EXTRA 17
#define MAXIMUM_INT64 (int64_t)((1ULL << 63) - 1)
RTSP methods, used as the first item in the request line
#define DESCRIBE_METHOD "DESCRIBE"
#define SETUP_METHOD "SETUP"
#define PLAY_METHOD "PLAY"
#define TEARDOWN_METHOD "TEARDOWN"
Names of headers used by the code
#define CONTENT_PSEUDOHEADER_NAME ":"
#define CONTENT_LENGTH_NAME "Content-Length"
#define CONTENT_BASE_NAME "Content-Base"
#define CONTENT_LOCATION_NAME "Content-Location"
#define RTP_INFO_NAME "RTP-Info"
#define SESSION_NAME "Session"
RTP URI parameter names
#define PAYLOAD_TYPE_NAME "rtppt"
#define MIME_TYPE_NAME "mime-type"
#define SAMPLE_RATE_NAME "rate"
#define CHANNELS_NAME "channels"
Typedefs
typedef int(* PARSE_IS_DELIMITER_FN_T) (int char_to_test)
typedef struct rtsp_header_tag RTSP_HEADER_T
typedef struct VC_CONTAINER_TRACK_MODULE_T VC_CONTAINER_TRACK_MODULE_T
typedef struct VC_CONTAINER_MODULE_T VC_CONTAINER_MODULE_T
Functions
VC_CONTAINER_STATUS_T rtsp_reader_open (VC_CONTAINER_T *)
Macro Definition Documentation
CHANNELS_NAME
#define CHANNELS_NAME "channels"
Definition at line 145 of file rtsp_reader.c.
COMMS_BUFFER_SIZE
#define COMMS_BUFFER_SIZE 2048
Space for sending requests and receiving responses
Definition at line 51 of file rtsp_reader.c.
CONTAINER_HELPER_LOG_INDENT
#define CONTAINER_HELPER_LOG_INDENT (a) 0
Definition at line 35 of file rtsp_reader.c.
CONTAINER_IS_BIG_ENDIAN
#define CONTAINER_IS_BIG_ENDIAN
Definition at line 32 of file rtsp_reader.c.
CONTENT_BASE_NAME
#define CONTENT_BASE_NAME "Content-Base"
Definition at line 112 of file rtsp_reader.c.
CONTENT_LENGTH_NAME
#define CONTENT_LENGTH_NAME "Content-Length"
Definition at line 111 of file rtsp_reader.c.
CONTENT_LOCATION_NAME
#define CONTENT_LOCATION_NAME "Content-Location"
Definition at line 113 of file rtsp_reader.c.
CONTENT_PSEUDOHEADER_NAME
#define CONTENT_PSEUDOHEADER_NAME ":"
Definition at line 110 of file rtsp_reader.c.
DATA_UNAVAILABLE_READ_TIMEOUT_MS
#define DATA_UNAVAILABLE_READ_TIMEOUT_MS 1
Number of milliseconds to block trying to read from the RTSP stream when no data is available from any of the tracks
Definition at line 63 of file rtsp_reader.c.
DESCRIBE_METHOD
#define DESCRIBE_METHOD "DESCRIBE"
Definition at line 102 of file rtsp_reader.c.
DYNAMIC_PORT_ATTEMPTS_MAX
#define DYNAMIC_PORT_ATTEMPTS_MAX 16
Definition at line 69 of file rtsp_reader.c.
FIRST_DYNAMIC_PORT
#define FIRST_DYNAMIC_PORT 0xC000
Start of private / dynamic port region
Definition at line 131 of file rtsp_reader.c.
Referenced by rtsp_reader_open().
HEADER_LIST_INITIAL_CAPACITY
#define HEADER_LIST_INITIAL_CAPACITY 16
Initial capacity of header list
Definition at line 85 of file rtsp_reader.c.
Referenced by rtsp_reader_open().
LAST_DYNAMIC_PORT
#define LAST_DYNAMIC_PORT 0xFFF0
End of private / dynamic port region
Definition at line 133 of file rtsp_reader.c.
MAXIMUM_INT64
#define MAXIMUM_INT64 (int64_t)((1ULL << 63) - 1)
Largest signed 64-bit integer
Definition at line 149 of file rtsp_reader.c.
MIME_TYPE_NAME
#define MIME_TYPE_NAME "mime-type"
Definition at line 143 of file rtsp_reader.c.
PAYLOAD_TYPE_NAME
#define PAYLOAD_TYPE_NAME "rtppt"
Definition at line 142 of file rtsp_reader.c.
PLAY_METHOD
#define PLAY_METHOD "PLAY"
Definition at line 104 of file rtsp_reader.c.
PORT_BUFFER_SIZE
#define PORT_BUFFER_SIZE 6
Maximum size of a decimal string representation of a uint16_t, plus NUL
Definition at line 129 of file rtsp_reader.c.
RTP_INFO_NAME
#define RTP_INFO_NAME "RTP-Info"
Definition at line 114 of file rtsp_reader.c.
RTP_PATH_EXTENSION_FORMAT
#define RTP_PATH_EXTENSION_FORMAT ".t%u.pkt"
Format of RTP track file extension
Definition at line 136 of file rtsp_reader.c.
RTP_PATH_EXTRA
#define RTP_PATH_EXTRA 17
Extra space need for creating an RTP track file name from an RTSP URI path
Definition at line 138 of file rtsp_reader.c.
RTP_SCHEME
#define RTP_SCHEME "rtp"
Definition at line 76 of file rtsp_reader.c.
RTSP_MAJOR_VERSION
#define RTSP_MAJOR_VERSION 1
Supported RTSP major version number
Definition at line 119 of file rtsp_reader.c.
RTSP_MINOR_VERSION
#define RTSP_MINOR_VERSION 0
Supported RTSP minor version number
Definition at line 121 of file rtsp_reader.c.
RTSP_NETWORK_URI_START
#define RTSP_NETWORK_URI_START "rtsp://"
Definition at line 81 of file rtsp_reader.c.
Referenced by rtsp_reader_open().
RTSP_NETWORK_URI_START_LENGTH
#define RTSP_NETWORK_URI_START_LENGTH (sizeof(RTSP_NETWORK_URI_START)-1)
Definition at line 82 of file rtsp_reader.c.
Referenced by rtsp_reader_open().
RTSP_PKT_SCHEME
#define RTSP_PKT_SCHEME "rtsppkt:"
The RTSP PKT scheme is used with test pkt files
Definition at line 79 of file rtsp_reader.c.
Referenced by rtsp_reader_open().
RTSP_REQUEST_LINE_FORMAT
#define RTSP_REQUEST_LINE_FORMAT "%s %s RTSP/1.0\r\n"
Format of the first line of an RTSP request
Definition at line 88 of file rtsp_reader.c.
RTSP_SCHEME
#define RTSP_SCHEME "rtsp:"
Definition at line 75 of file rtsp_reader.c.
Referenced by rtsp_reader_open().
RTSP_STATUS_MULTIPLE_CHOICES
#define RTSP_STATUS_MULTIPLE_CHOICES 300
Next failure status code after the set of successful ones
Definition at line 126 of file rtsp_reader.c.
RTSP_STATUS_OK
#define RTSP_STATUS_OK 200
Lowest successful status code value
Definition at line 124 of file rtsp_reader.c.
RTSP_TRACKS_MAX
#define RTSP_TRACKS_MAX 4
Maximum number of tracks allowed in an RTSP reader
Definition at line 48 of file rtsp_reader.c.
RTSP_URI_LENGTH_MAX
#define RTSP_URI_LENGTH_MAX 1024
Largest allowed RTSP URI. Must be substantially smaller than COMMS_BUFFER_SIZE to allow for the headers that may be sent.
Definition at line 55 of file rtsp_reader.c.
SAMPLE_RATE_NAME
#define SAMPLE_RATE_NAME "rate"
Definition at line 144 of file rtsp_reader.c.
SESSION_HEADER_FORMAT
#define SESSION_HEADER_FORMAT "Session: %s\r\n"
Format for including Session: header.
Definition at line 98 of file rtsp_reader.c.
SESSION_HEADER_LENGTH_MAX
#define SESSION_HEADER_LENGTH_MAX 100
Maximum allowed length for the Session: header recevied in a SETUP response, This is to ensure comms buffer is not overflowed.
Definition at line 59 of file rtsp_reader.c.
SESSION_NAME
#define SESSION_NAME "Session"
Definition at line 115 of file rtsp_reader.c.
SETUP_METHOD
#define SETUP_METHOD "SETUP"
Definition at line 103 of file rtsp_reader.c.
TEARDOWN_METHOD
#define TEARDOWN_METHOD "TEARDOWN"
Definition at line 105 of file rtsp_reader.c.
TRAILING_HEADERS_FORMAT
#define TRAILING_HEADERS_FORMAT "CSeq: %u\r\nConnection: Keep-Alive\r\nUser-Agent: Broadcom/1.0\r\n\r\n"
Format string for common headers used with all request methods. Note: includes double new line to terminate headers
Definition at line 92 of file rtsp_reader.c.
TRANSPORT_HEADER_FORMAT
#define TRANSPORT_HEADER_FORMAT "Transport: RTP/AVP;unicast;client_port=%hu-%hu;mode=play\r\n"
Format for the Transport: header
Definition at line 95 of file rtsp_reader.c.
UDP_READ_BUFFER_SIZE
#define UDP_READ_BUFFER_SIZE 520000
Size of buffer for each track to use when receiving packets
Definition at line 66 of file rtsp_reader.c.
Typedef Documentation
PARSE_IS_DELIMITER_FN_T
typedef int(* PARSE_IS_DELIMITER_FN_T) (int char_to_test)
Definition at line 155 of file rtsp_reader.c.
RTSP_HEADER_T
typedef struct rtsp_header_tag RTSP_HEADER_T
VC_CONTAINER_MODULE_T
typedef struct VC_CONTAINER_MODULE_T VC_CONTAINER_MODULE_T
VC_CONTAINER_TRACK_MODULE_T
typedef struct VC_CONTAINER_TRACK_MODULE_T VC_CONTAINER_TRACK_MODULE_T
Function Documentation
rtsp_reader_open()
VC_CONTAINER_STATUS_T rtsp_reader_open (VC_CONTAINER_T * p_ctx)
Open the container. Uses the I/O URI and/or data to configure the container.
Parameters
p_ctx The reader context.
Returns
The resulting status of the function.
Definition at line 1917 of file rtsp_reader.c.
References VC_CONTAINER_MODULE_T::comms_buffer, VC_CONTAINER_MODULE_T::cseq_value, error(), FIRST_DYNAMIC_PORT, VC_CONTAINER_MODULE_T::header_list, HEADER_LIST_INITIAL_CAPACITY, VC_CONTAINER_PRIVATE_T::io, VC_CONTAINER_PRIVATE_T::module, VC_CONTAINER_MODULE_T::next_rtp_port, NULL, VC_CONTAINER_T::priv, RTSP_NETWORK_URI_START, RTSP_NETWORK_URI_START_LENGTH, RTSP_PKT_SCHEME, RTSP_SCHEME, VC_CONTAINER_MODULE_T::tracks, VC_CONTAINER_T::tracks, VC_CONTAINER_IO_T::uri, VC_CONTAINER_PRIVATE_T::uri, VC_CONTAINER_MODULE_T::uri_has_network_info, VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED, VC_CONTAINER_ERROR_OUT_OF_MEMORY, VC_CONTAINER_SUCCESS, vc_containers_list_create(), and vc_uri_scheme().
 {
    VC_CONTAINER_MODULE_T *module = 0;
    VC_CONTAINER_STATUS_T status = VC_CONTAINER_SUCCESS;
    uint32_t ii;
    /* Check the URI scheme looks valid */
    if (!vc_uri_scheme(p_ctx->priv->uri) ||
        (strcasecmp(vc_uri_scheme(p_ctx->priv->uri), RTSP_SCHEME) &&
         strcasecmp(vc_uri_scheme(p_ctx->priv->uri), RTSP_PKT_SCHEME)))
       return VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED;
    /* Allocate our context */
    if ((module = (VC_CONTAINER_MODULE_T *)malloc(sizeof(VC_CONTAINER_MODULE_T))) == NULL)
    {
       status = VC_CONTAINER_ERROR_OUT_OF_MEMORY;
       goto error;
    }
    memset(module, 0, sizeof(*module));
    p_ctx->priv->module = module;
    p_ctx->tracks = module->tracks;
    module->next_rtp_port = FIRST_DYNAMIC_PORT;
    module->cseq_value = 0;
    module->uri_has_network_info =
          (strncasecmp(p_ctx->priv->io->uri, RTSP_NETWORK_URI_START, RTSP_NETWORK_URI_START_LENGTH) == 0);
    module->comms_buffer = (char *)calloc(1, COMMS_BUFFER_SIZE+1);
    if (!module->comms_buffer) { status = VC_CONTAINER_ERROR_OUT_OF_MEMORY; goto error; }
    /* header_list will contain pointers into the response_buffer, so take care in re-use */
    module->header_list = vc_containers_list_create(HEADER_LIST_INITIAL_CAPACITY, sizeof(RTSP_HEADER_T),
          (VC_CONTAINERS_LIST_COMPARATOR_T)rtsp_header_comparator);
    if (!module->header_list) { status = VC_CONTAINER_ERROR_OUT_OF_MEMORY; goto error; }
    status = rtsp_describe(p_ctx);
    for (ii = 0; status == VC_CONTAINER_SUCCESS && ii < p_ctx->tracks_num; ii++)
       status = rtsp_setup(p_ctx, p_ctx->tracks[ii]->priv->module);
    for (ii = 0; status == VC_CONTAINER_SUCCESS && ii < p_ctx->tracks_num; ii++)
       status = rtsp_play(p_ctx, p_ctx->tracks[ii]->priv->module);
    if (status != VC_CONTAINER_SUCCESS)
       goto error;
    /* Set the RTSP stream to block briefly, to allow polling for closure as well as to avoid spinning CPU */
    vc_container_control(p_ctx, VC_CONTAINER_CONTROL_IO_SET_READ_TIMEOUT_MS, DATA_UNAVAILABLE_READ_TIMEOUT_MS);
    p_ctx->priv->pf_close = rtsp_reader_close;
    p_ctx->priv->pf_read = rtsp_reader_read;
    p_ctx->priv->pf_seek = rtsp_reader_seek;
    if(STREAM_STATUS(p_ctx) != VC_CONTAINER_SUCCESS) goto error;
    return VC_CONTAINER_SUCCESS;
 error:
    if(status == VC_CONTAINER_SUCCESS || status == VC_CONTAINER_ERROR_EOS)
       status = VC_CONTAINER_ERROR_FORMAT_INVALID;
    LOG_DEBUG(p_ctx, "error opening RTSP stream (%i)", status);
    rtsp_reader_close(p_ctx);
    return status;
 }