VideoCore Library: interface/khronos/glxx/glxx_client.c File Reference
glxx_client.c File Reference
#include "interface/khronos/common/khrn_client_mangle.h"
#include "interface/khronos/common/khrn_int_common.h"
#include "interface/khronos/common/khrn_options.h"
#include "interface/khronos/glxx/glxx_client.h"
#include "interface/khronos/glxx/gl11_int_config.h"
#include "interface/khronos/include/GLES/glext.h"
#include "interface/khronos/include/GLES2/gl2ext.h"
#include "interface/khronos/common/khrn_client_rpc.h"
#include "interface/khronos/common/khrn_int_util.h"
#include <string.h>
#include <stdlib.h>
#include <math.h>
Classes
struct MERGE_INFO
Macros
#define VCOS_LOG_CATEGORY (&gl_client_log)
#define SET_SERIALIZED_ATTRIB(target, b, x, k)
#define SERIALIZE_ATTRIB(b, x, k)
#define SET_SERIALIZED_ATTRIB_VALUE(target, x)
#define SERIALIZE_ATTRIB_VALUE(x)
#define set_error(a, b) set_error_ex(a, b, __func__)
#define MAX_UNIFORM_SIZE 2048
Typedefs
typedef struct MERGE_INFO MERGE_INFO_T
Functions
void glxx_set_error (GLXX_CLIENT_STATE_T *state, GLenum error)
void glxx_set_error_api (uint32_t api, GLenum error)
void glxx_buffer_info_set (GLXX_CLIENT_STATE_T *state, GLenum target, GLXX_BUFFER_INFO_T *buffer_info)
void glxx_buffer_info_get (GLXX_CLIENT_STATE_T *state, GLenum target, GLXX_BUFFER_INFO_T *buffer_info)
GL_API void GL_APIENTRY glActiveTexture (GLenum texture)
GL_API void GL_APIENTRY glAlphaFunc (GLenum func, GLclampf ref)
GL_API void GL_APIENTRY glAlphaFuncx (GLenum func, GLclampx ref)
GL_API void GL_APIENTRY glAttachShader (GLuint program, GLuint shader)
GL_API void GL_APIENTRY glBindAttribLocation (GLuint program, GLuint index, const char *name)
GL_API void GL_APIENTRY glBindBuffer (GLenum target, GLuint buffer)
GL_API void GL_APIENTRY glBindTexture (GLenum target, GLuint texture)
GL_API void GL_APIENTRY glBlendColor (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
GL_API void GL_APIENTRY glBlendEquation (GLenum mode)
GL_API void GL_APIENTRY glBlendEquationSeparate (GLenum modeRGB, GLenum modeAlpha)
GL_API void GL_APIENTRY glBlendFunc (GLenum sfactor, GLenum dfactor)
GL_API void GL_APIENTRY glBlendFuncSeparate (GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha)
GL_API void GL_APIENTRY glBufferData (GLenum target, GLsizeiptr size, const GLvoid *data, GLenum usage)
GL_API void GL_APIENTRY glBufferSubData (GLenum target, GLintptr base, GLsizeiptr size, const GLvoid *data)
GL_API void GL_APIENTRY glClear (GLbitfield mask)
GL_API void GL_APIENTRY glClearColor (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
GL_API void GL_APIENTRY glClearColorx (GLclampx red, GLclampx green, GLclampx blue, GLclampx alpha)
GL_API void GL_APIENTRY glClearDepthf (GLclampf depth)
GL_API void GL_APIENTRY glClearDepthx (GLclampx depth)
GL_API void GL_APIENTRY glClearStencil (GLint s)
GL_API void GL_APIENTRY glClientActiveTexture (GLenum texture)
GL_API void GL_APIENTRY glClipPlanef (GLenum plane, const GLfloat *equation)
GL_API void GL_APIENTRY glClipPlanex (GLenum plane, const GLfixed *equation)
GL_API void GL_APIENTRY glColor4f (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha)
GL_API void GL_APIENTRY glColor4ub (GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha)
GL_API void GL_APIENTRY glColor4x (GLfixed red, GLfixed green, GLfixed blue, GLfixed alpha)
GL_API void GL_APIENTRY glColorMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
GL_API void GL_APIENTRY glColorPointer (GLint size, GLenum type, GLsizei stride, const GLvoid *pointer)
GL_API void GL_APIENTRY glCompressedTexImage2D (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const GLvoid *data)
GL_API void GL_APIENTRY glCompressedTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const GLvoid *data)
GL_API void GL_APIENTRY glCopyTexImage2D (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border)
GL_API void GL_APIENTRY glCopyTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height)
GL_API GLuint GL_APIENTRY glCreateProgram (void)
GL_API GLuint GL_APIENTRY glCreateShader (GLenum type)
GL_API void GL_APIENTRY glCullFace (GLenum mode)
GL_API void GL_APIENTRY glDeleteBuffers (GLsizei n, const GLuint *buffers)
GL_API void GL_APIENTRY glDeleteProgram (GLuint program)
GL_API void GL_APIENTRY glDeleteShader (GLuint shader)
GL_API void GL_APIENTRY glDeleteTextures (GLsizei n, const GLuint *textures)
GL_API void GL_APIENTRY glDepthFunc (GLenum func)
GL_API void GL_APIENTRY glDepthMask (GLboolean flag)
GL_API void GL_APIENTRY glDepthRangef (GLclampf zNear, GLclampf zFar)
GL_API void GL_APIENTRY glDepthRangex (GLclampx zNear, GLclampx zFar)
GL_API void GL_APIENTRY glDetachShader (GLuint program, GLuint shader)
GL_API void GL_APIENTRY glDisable (GLenum cap)
GL_API void GL_APIENTRY glDisableClientState (GLenum array)
GL_APICALL void GL_APIENTRY glDisableVertexAttribArray (GLuint index)
GL_API void GL_APIENTRY glDrawArrays (GLenum mode, GLint first, GLsizei count)
GL_API void GL_APIENTRY glDrawElements (GLenum mode, GLsizei count, GLenum type, const GLvoid *indices)
GL_API void GL_APIENTRY glEnable (GLenum cap)
GL_API void GL_APIENTRY glEnableClientState (GLenum array)
GL_APICALL void GL_APIENTRY glEnableVertexAttribArray (GLuint index)
GL_API void GL_APIENTRY glFinish (void)
GL_API void GL_APIENTRY glFlush (void)
GL_API void GL_APIENTRY glFogf (GLenum pname, GLfloat param)
GL_API void GL_APIENTRY glFogfv (GLenum pname, const GLfloat *params)
GL_API void GL_APIENTRY glFogx (GLenum pname, GLfixed param)
GL_API void GL_APIENTRY glFogxv (GLenum pname, const GLfixed *params)
GL_API void GL_APIENTRY glFrontFace (GLenum mode)
GL_API void GL_APIENTRY glFrustumf (GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar)
GL_API void GL_APIENTRY glFrustumx (GLfixed left, GLfixed right, GLfixed bottom, GLfixed top, GLfixed zNear, GLfixed zFar)
GL_API void GL_APIENTRY glGenBuffers (GLsizei n, GLuint *buffers)
GL_API void GL_APIENTRY glGenTextures (GLsizei n, GLuint *textures)
GL_APICALL void GL_APIENTRY glGetActiveAttrib (GLuint program, GLuint index, GLsizei bufsize, GLsizei *length, GLint *size, GLenum *type, char *name)
GL_APICALL void GL_APIENTRY glGetActiveUniform (GLuint program, GLuint index, GLsizei bufsize, GLsizei *length, GLint *size, GLenum *type, char *name)
GL_APICALL void GL_APIENTRY glGetAttachedShaders (GLuint program, GLsizei maxcount, GLsizei *count, GLuint *shaders)
GL_APICALL int GL_APIENTRY glGetAttribLocation (GLuint program, const char *name)
GL_API void GL_APIENTRY glGetBooleanv (GLenum pname, GLboolean *params)
GL_API void GL_APIENTRY glGetBufferParameteriv (GLenum target, GLenum pname, GLint *params)
GL_API void GL_APIENTRY glGetClipPlanef (GLenum pname, GLfloat eqn[4])
GL_API void GL_APIENTRY glGetClipPlanex (GLenum pname, GLfixed eqn[4])
GL_API GLenum GL_APIENTRY glGetError (void)
GL_API void GL_APIENTRY glGetFixedv (GLenum pname, GLfixed *params)
GL_API void GL_APIENTRY glGetFloatv (GLenum pname, GLfloat *params)
GL_API void GL_APIENTRY glGetIntegerv (GLenum pname, GLint *params)
GL_API void GL_APIENTRY glGetLightfv (GLenum light, GLenum pname, GLfloat *params)
GL_API void GL_APIENTRY glGetLightxv (GLenum light, GLenum pname, GLfixed *params)
GL_API void GL_APIENTRY glGetMaterialfv (GLenum face, GLenum pname, GLfloat *params)
GL_API void GL_APIENTRY glGetMaterialxv (GLenum face, GLenum pname, GLfixed *params)
GL_API void GL_APIENTRY glGetPointerv (GLenum pname, GLvoid **params)
GL_APICALL void GL_APIENTRY glGetProgramiv (GLuint program, GLenum pname, GLint *params)
GL_APICALL void GL_APIENTRY glGetProgramInfoLog (GLuint program, GLsizei bufsize, GLsizei *length, char *infolog)
GL_API const GLubyte *GL_APIENTRY glGetString (GLenum name)
GL_API void GL_APIENTRY glGetTexEnviv (GLenum env, GLenum pname, GLint *params)
GL_API void GL_APIENTRY glGetTexEnvfv (GLenum env, GLenum pname, GLfloat *params)
GL_API void GL_APIENTRY glGetTexEnvxv (GLenum env, GLenum pname, GLfixed *params)
GL_API void GL_APIENTRY glGetTexParameteriv (GLenum target, GLenum pname, GLint *params)
GL_API void GL_APIENTRY glGetTexParameterfv (GLenum target, GLenum pname, GLfloat *params)
GL_API void GL_APIENTRY glGetTexParameterxv (GLenum target, GLenum pname, GLfixed *params)
GL_APICALL void GL_APIENTRY glGetUniformfv (GLuint program, GLint location, GLfloat *params)
GL_APICALL void GL_APIENTRY glGetUniformiv (GLuint program, GLint location, GLint *params)
GL_APICALL int GL_APIENTRY glGetUniformLocation (GLuint program, const char *name)
GL_APICALL void GL_APIENTRY glGetVertexAttribfv (GLuint index, GLenum pname, GLfloat *params)
GL_APICALL void GL_APIENTRY glGetVertexAttribiv (GLuint index, GLenum pname, GLint *params)
GL_APICALL void GL_APIENTRY glGetVertexAttribPointerv (GLuint index, GLenum pname, void **pointer)
GL_API void GL_APIENTRY glHint (GLenum target, GLenum mode)
GL_API GLboolean GL_APIENTRY glIsBuffer (GLuint buffer)
GL_API GLboolean GL_APIENTRY glIsEnabled (GLenum cap)
GL_API GLboolean GL_APIENTRY glIsProgram (GLuint program)
GL_API GLboolean GL_APIENTRY glIsShader (GLuint shader)
GL_API GLboolean GL_APIENTRY glIsTexture (GLuint texture)
GL_API void GL_APIENTRY glLightModelf (GLenum pname, GLfloat param)
GL_API void GL_APIENTRY glLightModelfv (GLenum pname, const GLfloat *params)
GL_API void GL_APIENTRY glLightModelx (GLenum pname, GLfixed param)
GL_API void GL_APIENTRY glLightModelxv (GLenum pname, const GLfixed *params)
GL_API void GL_APIENTRY glLightf (GLenum light, GLenum pname, GLfloat param)
GL_API void GL_APIENTRY glLightfv (GLenum light, GLenum pname, const GLfloat *params)
GL_API void GL_APIENTRY glLightx (GLenum light, GLenum pname, GLfixed param)
GL_API void GL_APIENTRY glLightxv (GLenum light, GLenum pname, const GLfixed *params)
GL_API void GL_APIENTRY glLineWidth (GLfloat width)
GL_API void GL_APIENTRY glLineWidthx (GLfixed width)
GL_API void GL_APIENTRY glLinkProgram (GLuint program)
GL_API void GL_APIENTRY glLoadIdentity (void)
GL_API void GL_APIENTRY glLoadMatrixf (const GLfloat *m)
GL_API void GL_APIENTRY glLoadMatrixx (const GLfixed *m)
GL_API void GL_APIENTRY glLogicOp (GLenum opcode)
GL_API void GL_APIENTRY glMaterialf (GLenum face, GLenum pname, GLfloat param)
GL_API void GL_APIENTRY glMaterialfv (GLenum face, GLenum pname, const GLfloat *params)
GL_API void GL_APIENTRY glMaterialx (GLenum face, GLenum pname, GLfixed param)
GL_API void GL_APIENTRY glMaterialxv (GLenum face, GLenum pname, const GLfixed *params)
GL_API void GL_APIENTRY glMatrixMode (GLenum mode)
GL_API void GL_APIENTRY glMultMatrixf (const GLfloat *m)
GL_API void GL_APIENTRY glMultMatrixx (const GLfixed *m)
GL_API void GL_APIENTRY glMultiTexCoord4f (GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q)
GL_API void GL_APIENTRY glMultiTexCoord4x (GLenum target, GLfixed s, GLfixed t, GLfixed r, GLfixed q)
GL_API void GL_APIENTRY glNormal3f (GLfloat nx, GLfloat ny, GLfloat nz)
GL_API void GL_APIENTRY glNormal3x (GLfixed nx, GLfixed ny, GLfixed nz)
GL_API void GL_APIENTRY glNormalPointer (GLenum type, GLsizei stride, const GLvoid *pointer)
GL_API void GL_APIENTRY glOrthof (GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar)
GL_API void GL_APIENTRY glOrthox (GLfixed left, GLfixed right, GLfixed bottom, GLfixed top, GLfixed zNear, GLfixed zFar)
GL_API void GL_APIENTRY glPixelStorei (GLenum pname, GLint param)
GL_API void GL_APIENTRY glPointParameterf (GLenum pname, GLfloat param)
GL_API void GL_APIENTRY glPointParameterfv (GLenum pname, const GLfloat *params)
GL_API void GL_APIENTRY glPointParameterx (GLenum pname, GLfixed param)
GL_API void GL_APIENTRY glPointParameterxv (GLenum pname, const GLfixed *params)
GL_API void GL_APIENTRY glPointSize (GLfloat size)
GL_API void GL_APIENTRY glPointSizex (GLfixed size)
GL_API void GL_APIENTRY glPolygonOffset (GLfloat factor, GLfloat units)
GL_API void GL_APIENTRY glPolygonOffsetx (GLfixed factor, GLfixed units)
GL_API void GL_APIENTRY glPopMatrix (void)
GL_API void GL_APIENTRY glPushMatrix (void)
GL_API void GL_APIENTRY glReadPixels (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels)
GL_API void GL_APIENTRY glRotatef (GLfloat angle, GLfloat x, GLfloat y, GLfloat z)
GL_API void GL_APIENTRY glRotatex (GLfixed angle, GLfixed x, GLfixed y, GLfixed z)
GL_API void GL_APIENTRY glSampleCoverage (GLclampf value, GLboolean invert)
GL_API void GL_APIENTRY glSampleCoveragex (GLclampx value, GLboolean invert)
GL_API void GL_APIENTRY glScalef (GLfloat x, GLfloat y, GLfloat z)
GL_API void GL_APIENTRY glScalex (GLfixed x, GLfixed y, GLfixed z)
GL_API void GL_APIENTRY glScissor (GLint x, GLint y, GLsizei width, GLsizei height)
GL_API void GL_APIENTRY glShadeModel (GLenum mode)
GL_API void GL_APIENTRY glStencilFunc (GLenum func, GLint ref, GLuint mask)
GL_API void GL_APIENTRY glStencilFuncSeparate (GLenum face, GLenum func, GLint ref, GLuint mask)
GL_API void GL_APIENTRY glStencilMask (GLuint mask)
GL_API void GL_APIENTRY glStencilMaskSeparate (GLenum face, GLuint mask)
GL_API void GL_APIENTRY glStencilOp (GLenum fail, GLenum zfail, GLenum zpass)
GL_API void GL_APIENTRY glStencilOpSeparate (GLenum face, GLenum fail, GLenum zfail, GLenum zpass)
GL_API void GL_APIENTRY glTexCoordPointer (GLint size, GLenum type, GLsizei stride, const GLvoid *pointer)
GL_API void GL_APIENTRY glTexEnvi (GLenum target, GLenum pname, GLint param)
GL_API void GL_APIENTRY glTexEnviv (GLenum target, GLenum pname, const GLint *params)
GL_API void GL_APIENTRY glTexEnvf (GLenum target, GLenum pname, GLfloat param)
GL_API void GL_APIENTRY glTexEnvfv (GLenum target, GLenum pname, const GLfloat *params)
GL_API void GL_APIENTRY glTexEnvx (GLenum target, GLenum pname, GLfixed param)
GL_API void GL_APIENTRY glTexEnvxv (GLenum target, GLenum pname, const GLfixed *params)
GL_API void GL_APIENTRY glTexImage2D (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels)
GL_API void GL_APIENTRY glTexParameteri (GLenum target, GLenum pname, GLint param)
GL_API void GL_APIENTRY glTexParameterf (GLenum target, GLenum pname, GLfloat param)
GL_API void GL_APIENTRY glTexParameterx (GLenum target, GLenum pname, GLfixed param)
GL_API void GL_APIENTRY glTexParameteriv (GLenum target, GLenum pname, const GLint *params)
GL_API void GL_APIENTRY glTexParameterfv (GLenum target, GLenum pname, const GLfloat *params)
GL_API void GL_APIENTRY glTexParameterxv (GLenum target, GLenum pname, const GLfixed *params)
GL_API void GL_APIENTRY glTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels)
GL_API void GL_APIENTRY texSubImage2DAsync (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLint hpixels)
GL_API void GL_APIENTRY glTranslatef (GLfloat x, GLfloat y, GLfloat z)
GL_API void GL_APIENTRY glTranslatex (GLfixed x, GLfixed y, GLfixed z)
GL_API void GL_APIENTRY glUniform1i (GLint location, GLint x)
GL_API void GL_APIENTRY glUniform2i (GLint location, GLint x, GLint y)
GL_API void GL_APIENTRY glUniform3i (GLint location, GLint x, GLint y, GLint z)
GL_API void GL_APIENTRY glUniform4i (GLint location, GLint x, GLint y, GLint z, GLint w)
GL_API void GL_APIENTRY glUniform1f (GLint location, GLfloat x)
GL_API void GL_APIENTRY glUniform2f (GLint location, GLfloat x, GLfloat y)
GL_API void GL_APIENTRY glUniform3f (GLint location, GLfloat x, GLfloat y, GLfloat z)
GL_API void GL_APIENTRY glUniform4f (GLint location, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
GL_API void GL_APIENTRY glUniform1iv (GLint location, GLsizei count, const GLint *v)
GL_API void GL_APIENTRY glUniform2iv (GLint location, GLsizei count, const GLint *v)
GL_API void GL_APIENTRY glUniform3iv (GLint location, GLsizei count, const GLint *v)
GL_API void GL_APIENTRY glUniform4iv (GLint location, GLsizei count, const GLint *v)
GL_API void GL_APIENTRY glUniform1fv (GLint location, GLsizei count, const GLfloat *v)
GL_API void GL_APIENTRY glUniform2fv (GLint location, GLsizei count, const GLfloat *v)
GL_API void GL_APIENTRY glUniform3fv (GLint location, GLsizei count, const GLfloat *v)
GL_API void GL_APIENTRY glUniform4fv (GLint location, GLsizei count, const GLfloat *v)
GL_API void GL_APIENTRY glUniformMatrix2fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
GL_API void GL_APIENTRY glUniformMatrix3fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
GL_API void GL_APIENTRY glUniformMatrix4fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
GL_API void GL_APIENTRY glUseProgram (GLuint program)
GL_API void GL_APIENTRY glValidateProgram (GLuint program)
GL_APICALL void GL_APIENTRY glVertexAttrib1f (GLuint indx, GLfloat x)
GL_APICALL void GL_APIENTRY glVertexAttrib2f (GLuint indx, GLfloat x, GLfloat y)
GL_APICALL void GL_APIENTRY glVertexAttrib3f (GLuint indx, GLfloat x, GLfloat y, GLfloat z)
GL_APICALL void GL_APIENTRY glVertexAttrib4f (GLuint indx, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
GL_APICALL void GL_APIENTRY glVertexAttrib1fv (GLuint indx, const GLfloat *values)
GL_APICALL void GL_APIENTRY glVertexAttrib2fv (GLuint indx, const GLfloat *values)
GL_APICALL void GL_APIENTRY glVertexAttrib3fv (GLuint indx, const GLfloat *values)
GL_APICALL void GL_APIENTRY glVertexAttrib4fv (GLuint indx, const GLfloat *values)
GL_APICALL void GL_APIENTRY glVertexAttribPointer (GLuint indx, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void *ptr)
GL_API void GL_APIENTRY glVertexPointer (GLint size, GLenum type, GLsizei stride, const GLvoid *pointer)
GL_API void GL_APIENTRY glViewport (GLint x, GLint y, GLsizei width, GLsizei height)
GL_API void GL_APIENTRY glPointSizePointerOES (GLenum type, GLsizei stride, const GLvoid *pointer)
GL_APICALL void GL_APIENTRY glCompileShader (GLuint shader)
GL_APICALL void GL_APIENTRY glGetShaderiv (GLuint shader, GLenum pname, GLint *params)
GL_APICALL void GL_APIENTRY glGetShaderInfoLog (GLuint shader, GLsizei bufsize, GLsizei *length, char *infolog)
GL_APICALL void GL_APIENTRY glGetShaderSource (GLuint shader, GLsizei bufsize, GLsizei *length, char *source)
GL_APICALL void GL_APIENTRY glReleaseShaderCompiler (void)
GL_APICALL void GL_APIENTRY glShaderBinary (GLint n, const GLuint *shaders, GLenum binaryformat, const void *binary, GLint length)
GL_APICALL void GL_APIENTRY glShaderSource (GLuint shader, GLsizei count, const char **string, const GLint *length)
GLboolean glxx_client_IsRenderbuffer (GLuint renderbuffer)
GL_APICALL GLboolean GL_APIENTRY glIsRenderbuffer (GLuint renderbuffer)
void glxx_client_BindRenderbuffer (GLenum target, GLuint renderbuffer)
GL_APICALL void GL_APIENTRY glBindRenderbuffer (GLenum target, GLuint renderbuffer)
void glxx_client_DeleteRenderbuffers (GLsizei n, const GLuint *renderbuffers)
GL_APICALL void GL_APIENTRY glDeleteRenderbuffers (GLsizei n, const GLuint *renderbuffers)
void glxx_client_GenRenderbuffers (GLsizei n, GLuint *renderbuffers)
GL_APICALL void GL_APIENTRY glGenRenderbuffers (GLsizei n, GLuint *renderbuffers)
void glxx_client_RenderbufferStorage (GLenum target, GLenum internalformat, GLsizei width, GLsizei height)
GL_APICALL void GL_APIENTRY glRenderbufferStorage (GLenum target, GLenum internalformat, GLsizei width, GLsizei height)
void glxx_client_GetRenderbufferParameteriv (GLenum target, GLenum pname, GLint *params)
GL_APICALL void GL_APIENTRY glGetRenderbufferParameteriv (GLenum target, GLenum pname, GLint *params)
GLboolean glxx_client_IsFramebuffer (GLuint framebuffer)
GL_APICALL GLboolean GL_APIENTRY glIsFramebuffer (GLuint framebuffer)
void glxx_client_BindFramebuffer (GLenum target, GLuint framebuffer)
GL_APICALL void GL_APIENTRY glBindFramebuffer (GLenum target, GLuint framebuffer)
void glxx_client_DeleteFramebuffers (GLsizei n, const GLuint *framebuffers)
GL_APICALL void GL_APIENTRY glDeleteFramebuffers (GLsizei n, const GLuint *framebuffers)
void glxx_client_GenFramebuffers (GLsizei n, GLuint *framebuffers)
GL_APICALL void GL_APIENTRY glGenFramebuffers (GLsizei n, GLuint *framebuffers)
GLenum glxx_client_CheckFramebufferStatus (GLenum target)
GL_APICALL GLenum GL_APIENTRY glCheckFramebufferStatus (GLenum target)
void glxx_client_FramebufferTexture2D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
GL_APICALL void GL_APIENTRY glFramebufferTexture2D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
void glxx_client_FramebufferRenderbuffer (GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer)
GL_APICALL void GL_APIENTRY glFramebufferRenderbuffer (GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer)
void glxx_client_GetFramebufferAttachmentParameteriv (GLenum target, GLenum attachment, GLenum pname, GLint *params)
GL_APICALL void GL_APIENTRY glGetFramebufferAttachmentParameteriv (GLenum target, GLenum attachment, GLenum pname, GLint *params)
void glxx_client_GenerateMipmap (GLenum target)
GL_APICALL void GL_APIENTRY glGenerateMipmap (GLenum target)
GL_APICALL void GL_APIENTRY glGetShaderPrecisionFormat (GLenum shadertype, GLenum precisiontype, GLint *range, GLint *precision)
GL_APICALL void GL_APIENTRY glDiscardFramebufferEXT (GLenum target, GLsizei numAttachments, const GLenum *attachments)
int gl11_client_state_init (GLXX_CLIENT_STATE_T *state)
int gl20_client_state_init (GLXX_CLIENT_STATE_T *state)
void glxx_client_state_free (GLXX_CLIENT_STATE_T *state)
void glintAttribPointer (uint32_t api, uint32_t indx, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const GLvoid *ptr)
void glintAttrib (uint32_t api, uint32_t indx, float x, float y, float z, float w)
void glintColor (float x, float y, float z, float w)
void glintAttribEnable (uint32_t api, uint32_t indx, bool enabled)
void * glintAttribGetPointer (uint32_t api, uint32_t indx)
GL_API void GL_APIENTRY glTexImage3DOES (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid *pixels)
GL_API void GL_APIENTRY glTexSubImage3DOES (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid *pixels)
Variables
VCOS_LOG_CAT_T gl_client_log = VCOS_LOG_INIT("gl_client", VCOS_LOG_WARN)
Macro Definition Documentation
MAX_UNIFORM_SIZE
#define MAX_UNIFORM_SIZE 2048
Definition at line 4549 of file glxx_client.c.
SERIALIZE_ATTRIB
#define SERIALIZE_ATTRIB (b, x, k)
Value:
RPC_INT((x).size), \
                              RPC_ENUM((x).type), \
                              RPC_BOOLEAN((x).normalized), \
                              RPC_SIZEI((x).stride), \
                              RPC_UINT((b ? (uint32_t)(k + offsetof(CACHE_ENTRY_T, data)) : (uint32_t)(uintptr_t)(x).pointer)), \
                              RPC_UINT((x).buffer)
Definition at line 82 of file glxx_client.c.
SERIALIZE_ATTRIB_VALUE
#define SERIALIZE_ATTRIB_VALUE (x)
Value:
RPC_FLOAT((x).value[0]), \
                                  RPC_FLOAT((x).value[1]), \
                                  RPC_FLOAT((x).value[2]), \
                                  RPC_FLOAT((x).value[3])
Definition at line 94 of file glxx_client.c.
set_error
#define set_error (a, b) set_error_ex(a, b, __func__)
Definition at line 113 of file glxx_client.c.
Referenced by glxx_set_error().
SET_SERIALIZED_ATTRIB
#define SET_SERIALIZED_ATTRIB (target, b, x, k)
Value:
{ (target)[0] = RPC_INT((x).size); \
                                                 (target)[1] = RPC_ENUM((x).type); \
                                                 (target)[2] = RPC_BOOLEAN((x).normalized), \
                                                 (target)[3] = RPC_SIZEI((x).stride); \
                                                 (target)[4] = RPC_UINT((b ? (uint32_t)(k + offsetof(CACHE_ENTRY_T, data)) : (uint32_t)(uintptr_t)(x).pointer)); \
                                                 (target)[5] = RPC_UINT((x).buffer); }
Definition at line 75 of file glxx_client.c.
SET_SERIALIZED_ATTRIB_VALUE
#define SET_SERIALIZED_ATTRIB_VALUE (target, x)
Value:
{ target[0] = RPC_FLOAT((x).value[0]); \
                                                target[1] = RPC_FLOAT((x).value[1]); \
                                                target[2] = RPC_FLOAT((x).value[2]); \
                                                target[3] = RPC_FLOAT((x).value[3]); }
Definition at line 89 of file glxx_client.c.
VCOS_LOG_CATEGORY
#define VCOS_LOG_CATEGORY (&gl_client_log)
Definition at line 27 of file glxx_client.c.
Typedef Documentation
MERGE_INFO_T
typedef struct MERGE_INFO MERGE_INFO_T
Function Documentation
gl11_client_state_init()
int gl11_client_state_init (GLXX_CLIENT_STATE_T * state)
Definition at line 5527 of file glxx_client.c.
References OPENGL_ES_11, and GLXX_CLIENT_STATE_T::type.
 {
    state->type = OPENGL_ES_11;
    //perform common initialisation
    glxx_client_state_init(state);
    //gl2.0 specific
    state->active_texture.client = GL_TEXTURE0;
    state->active_texture.server = GL_TEXTURE0;
    gl11_attrib_init(state->attrib);
 #ifdef GLXX_NO_VERTEX_CACHE
    return 1;
 #else
    return khrn_cache_init(&state->cache);
 #endif
 }
gl20_client_state_init()
int gl20_client_state_init (GLXX_CLIENT_STATE_T * state)
Definition at line 5547 of file glxx_client.c.
References OPENGL_ES_20, and GLXX_CLIENT_STATE_T::type.
 {
    state->type = OPENGL_ES_20;
    //perform common initialisation
    glxx_client_state_init(state);
    //gl2.0 specific
    state->default_framebuffer = true;
    gl20_attrib_init(state->attrib);
 #ifdef GLXX_NO_VERTEX_CACHE
    return 1;
 #else
    return khrn_cache_init(&state->cache);
 #endif
 }
glActiveTexture()
GL_API void GL_APIENTRY glActiveTexture (GLenum texture)
Definition at line 199 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       if (texture >= GL_TEXTURE0 && texture < GL_TEXTURE0 + GL11_CONFIG_MAX_TEXTURE_UNITS)
          state->active_texture.server = texture;
       RPC_CALL1(glActiveTexture_impl,
                 thread,
                 GLACTIVETEXTURE_ID,
                 RPC_ENUM(texture));
    }
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL1(glActiveTexture_impl,
                 thread,
                 GLACTIVETEXTURE_ID,
                 RPC_ENUM(texture));
    }
 }
glAlphaFunc()
GL_API void GL_APIENTRY glAlphaFunc (GLenum func, GLclampf ref)
Definition at line 222 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL2(glAlphaFunc_impl_11,
                 thread,
                 GLALPHAFUNC_ID_11,
                 RPC_ENUM(func),
                 RPC_FLOAT(ref));
    }
 }
glAlphaFuncx()
GL_API void GL_APIENTRY glAlphaFuncx (GLenum func, GLclampx ref)
Definition at line 234 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL2(glAlphaFuncx_impl_11,
                 thread,
                 GLALPHAFUNCX_ID_11,
                 RPC_ENUM(func),
                 RPC_FIXED(ref));
    }
 }
glAttachShader()
GL_API void GL_APIENTRY glAttachShader (GLuint program, GLuint shader)
Definition at line 246 of file glxx_client.c.
Referenced by raspitexutil_build_shader_program().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL2(glAttachShader_impl_20,
                 thread,
                 GLATTACHSHADER_ID_20,
                 RPC_UINT(program),
                 RPC_UINT(shader));
    }
 }
glBindAttribLocation()
GL_API void GL_APIENTRY glBindAttribLocation (GLuint program, GLuint index, const char * name)
Definition at line 258 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL3_IN_BULK(glBindAttribLocation_impl_20,
                         thread,
                         GLBINDATTRIBLOCATION_ID_20,
                         RPC_UINT(program),
                         RPC_UINT(index),
                         name,
                         strlen(name) + 1);
    }
 }
glBindBuffer()
GL_API void GL_APIENTRY glBindBuffer (GLenum target, GLuint buffer)
Definition at line 272 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if(IS_OPENGLES_11_OR_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       vcos_assert(state != NULL);
       switch (target) {
       case GL_ARRAY_BUFFER:
          state->bound_buffer.array = buffer;
          break;
       case GL_ELEMENT_ARRAY_BUFFER:
          state->bound_buffer.element_array = buffer;
          break;
       default:
          // do nothing, server will signal error
          break;
       }
       RPC_CALL2(glBindBuffer_impl,
                 thread,
                 GLBINDBUFFER_ID,
                 RPC_ENUM(target),
                 RPC_UINT(buffer));
    }
 }
glBindFramebuffer()
GL_APICALL void GL_APIENTRY glBindFramebuffer (GLenum target, GLuint framebuffer)
Definition at line 5300 of file glxx_client.c.
References glxx_client_BindFramebuffer().
 {
    glxx_client_BindFramebuffer(target, framebuffer);
 }
glBindRenderbuffer()
GL_APICALL void GL_APIENTRY glBindRenderbuffer (GLenum target, GLuint renderbuffer)
Definition at line 5158 of file glxx_client.c.
References glxx_client_BindRenderbuffer().
 {
    glxx_client_BindRenderbuffer(target, renderbuffer);
 }
glBindTexture()
GL_API void GL_APIENTRY glBindTexture (GLenum target, GLuint texture)
Definition at line 301 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       vcos_log_trace("[%s] target 0x%x texture %d", __FUNCTION__, target, texture);
       RPC_CALL2(glBindTexture_impl,
                 thread,
                 GLBINDTEXTURE_ID,
                 RPC_ENUM(target),
                 RPC_UINT(texture));
    }
 }
glBlendColor()
GL_API void GL_APIENTRY glBlendColor (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
Definition at line 314 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL4(glBlendColor_impl_20,
                 thread,
                 GLBLENDCOLOR_ID_20,
                 RPC_FLOAT(red),
                 RPC_FLOAT(green),
                 RPC_FLOAT(blue),
                 RPC_FLOAT(alpha));
    }
 }
glBlendEquation()
GL_API void GL_APIENTRY glBlendEquation (GLenum mode)
Definition at line 328 of file glxx_client.c.
References glBlendEquationSeparate().
 {
    glBlendEquationSeparate(mode, mode);
 }
glBlendEquationSeparate()
GL_API void GL_APIENTRY glBlendEquationSeparate (GLenum modeRGB, GLenum modeAlpha)
Definition at line 333 of file glxx_client.c.
Referenced by glBlendEquation().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL2(glBlendEquationSeparate_impl_20,
                 thread,
                 GLBLENDEQUATIONSEPARATE_ID_20,
                 RPC_ENUM(modeRGB),
                 RPC_ENUM(modeAlpha));
    }
 }
glBlendFunc()
GL_API void GL_APIENTRY glBlendFunc (GLenum sfactor, GLenum dfactor)
Definition at line 355 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) set_blend_func(thread, sfactor, dfactor, sfactor, dfactor);
 }
glBlendFuncSeparate()
GL_API void GL_APIENTRY glBlendFuncSeparate (GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha)
Definition at line 361 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) set_blend_func(thread, srcRGB, dstRGB, srcAlpha, dstAlpha);
 }
glBufferData()
GL_API void GL_APIENTRY glBufferData (GLenum target, GLsizeiptr size, const GLvoid * data, GLenum usage)
Definition at line 367 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       GLXX_BUFFER_INFO_T buffer;
       glxx_buffer_info_get(state, target, &buffer);
       if(buffer.id != ~0 && buffer.mapped_pointer != 0)
       {
          /* buffer is mapped */
          set_error(state, GL_INVALID_OPERATION);
       }
       else
       {
          if( ((target == GL_ARRAY_BUFFER && state->bound_buffer.array != 0) ||
               (target == GL_ELEMENT_ARRAY_BUFFER && state->bound_buffer.element_array != 0)) &&
              (usage ==  GL_STATIC_DRAW || usage == GL_DYNAMIC_DRAW || (IS_OPENGLES_20(thread) && usage == GL_STREAM_DRAW)) &&
              size >=0
            )
          {
             /* server call should succeed in setting buffer size unless out of memory */
             /* cache size so we can use it in mapBuffer without a round trip */
             buffer.cached_size = size;
             glxx_buffer_info_set(state, target, &buffer);
          }
          else
          {
             buffer.cached_size = 0;
             glxx_buffer_info_set(state, target, &buffer);
          }
          RPC_CALL4_IN_BULK(glBufferData_impl,
                            thread,
                            GLBUFFERDATA_ID,
                            RPC_ENUM(target),
                            RPC_SIZEIPTR(size),
                            RPC_ENUM(usage),
                            NULL,
                            0);
          if (data) {
             int offset = 0;
             while (size > 0) {
                int32_t batch = _min(KHDISPATCH_WORKSPACE_SIZE, (int32_t) size);
                RPC_CALL4_IN_BULK(glBufferSubData_impl,
                                  thread,
                                  GLBUFFERSUBDATA_ID,
                                  RPC_ENUM(target),
                                  RPC_INTPTR(offset),
                                  RPC_SIZEIPTR(batch),
                                  (char *)data + offset,
                                  (size_t) batch);
                offset += batch;
                size -= batch;
             }
          }
       }
    }
 }
glBufferSubData()
GL_API void GL_APIENTRY glBufferSubData (GLenum target, GLintptr base, GLsizeiptr size, const GLvoid * data)
Definition at line 433 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       GLXX_BUFFER_INFO_T buffer;
       glxx_buffer_info_get(state, target, &buffer);
       if(buffer.id != ~0 && buffer.mapped_pointer != 0)
       {
          /* buffer is mapped */
          set_error(state, GL_INVALID_OPERATION);
       }
       else
       {
          if (data) {
             int offset = 0;
             while (size > 0) {
                int32_t batch = _min(KHDISPATCH_WORKSPACE_SIZE, (int32_t)size);
                RPC_CALL4_IN_BULK(glBufferSubData_impl,
                                  thread,
                                  GLBUFFERSUBDATA_ID,
                                  RPC_ENUM(target),
                                  RPC_INTPTR(base+offset),
                                  RPC_SIZEIPTR(batch),
                                  (char *)data + offset,
                                  (size_t) batch);
                offset += batch;
                size -= batch;
             }
          }
       }
    }
 }
glCheckFramebufferStatus()
GL_APICALL GLenum GL_APIENTRY glCheckFramebufferStatus (GLenum target)
Definition at line 5373 of file glxx_client.c.
References glxx_client_CheckFramebufferStatus().
 {
    return glxx_client_CheckFramebufferStatus(target);
 }
glClear()
GL_API void GL_APIENTRY glClear (GLbitfield mask)
Definition at line 471 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       //TODO: pixmap behaviour can be better optimized to handle clears
       if (state->render_callback)
          state->render_callback();
       RPC_CALL1(glClear_impl,
                 thread,
                 GLCLEAR_ID,
                 RPC_BITFIELD(mask));
    }
 }
glClearColor()
GL_API void GL_APIENTRY glClearColor (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
Definition at line 488 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL4(glClearColor_impl,
                 thread,
                 GLCLEARCOLOR_ID,
                 RPC_FLOAT(red),
                 RPC_FLOAT(green),
                 RPC_FLOAT(blue),
                 RPC_FLOAT(alpha));
    }
 }
glClearColorx()
GL_API void GL_APIENTRY glClearColorx (GLclampx red, GLclampx green, GLclampx blue, GLclampx alpha)
Definition at line 502 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL4(glClearColorx_impl_11,
                 thread,
                 GLCLEARCOLORX_ID_11,
                 RPC_FIXED(red),
                 RPC_FIXED(green),
                 RPC_FIXED(blue),
                 RPC_FIXED(alpha));
    }
 }
glClearDepthf()
GL_API void GL_APIENTRY glClearDepthf (GLclampf depth)
Definition at line 516 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL1(glClearDepthf_impl,
                 thread,
                 GLCLEARDEPTHF_ID,
                 RPC_FLOAT(depth));
    }
 }
glClearDepthx()
GL_API void GL_APIENTRY glClearDepthx (GLclampx depth)
Definition at line 527 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL1(glClearDepthx_impl_11,
                 thread,
                 GLCLEARDEPTHX_ID_11,
                 RPC_FIXED(depth));
    }
 }
glClearStencil()
GL_API void GL_APIENTRY glClearStencil (GLint s)
Definition at line 538 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL1(glClearStencil_impl,
                 thread,
                 GLCLEARSTENCIL_ID,
                 RPC_INT(s));
    }
 }
glClientActiveTexture()
GL_API void GL_APIENTRY glClientActiveTexture (GLenum texture)
Definition at line 549 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       vcos_assert(state != NULL);
       if (texture >= GL_TEXTURE0 && texture < GL_TEXTURE0 + GL11_CONFIG_MAX_TEXTURE_UNITS)
       {
          state->active_texture.client = texture;
          RPC_CALL1(glClientActiveTexture_impl_11,
                 thread,
                 GLCLIENTACTIVETEXTURE_ID_11,
                 RPC_ENUM(texture));
       }
       else
          set_error(state, GL_INVALID_ENUM);
    }
 }
glClipPlanef()
GL_API void GL_APIENTRY glClipPlanef (GLenum plane, const GLfloat * equation)
Definition at line 570 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL2_IN_CTRL(glClipPlanef_impl_11,
                         thread,
                         GLCLIPPLANEF_ID_11,
                         RPC_ENUM(plane),
                         equation,
                         4 * sizeof(GLfloat));
    }
 }
glClipPlanex()
GL_API void GL_APIENTRY glClipPlanex (GLenum plane, const GLfixed * equation)
Definition at line 583 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL2_IN_CTRL(glClipPlanex_impl_11,
                         thread,
                         GLCLIPPLANEX_ID_11,
                         RPC_ENUM(plane),
                         equation,
                         4 * sizeof(GLfixed));
    }
 }
glColor4f()
GL_API void GL_APIENTRY glColor4f (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha)
Definition at line 596 of file glxx_client.c.
References glintColor().
 {
    glintColor(
       clampf(red, 0.0f, 1.0f),
       clampf(green, 0.0f, 1.0f),
       clampf(blue, 0.0f, 1.0f),
       clampf(alpha, 0.0f, 1.0f));
 }
glColor4ub()
GL_API void GL_APIENTRY glColor4ub (GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha)
Definition at line 605 of file glxx_client.c.
References glintColor().
 {
    glintColor(
       (float)red / 255.0f,
       (float)green / 255.0f,
       (float)blue / 255.0f,
       (float)alpha / 255.0f);
 }
glColor4x()
GL_API void GL_APIENTRY glColor4x (GLfixed red, GLfixed green, GLfixed blue, GLfixed alpha)
Definition at line 614 of file glxx_client.c.
References glintColor().
 {
    glintColor(
       clampf(fixed_to_float(red), 0.0f, 1.0f),
       clampf(fixed_to_float(green), 0.0f, 1.0f),
       clampf(fixed_to_float(blue), 0.0f, 1.0f),
       clampf(fixed_to_float(alpha), 0.0f, 1.0f));
 }
glColorMask()
GL_API void GL_APIENTRY glColorMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
Definition at line 623 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL4(glColorMask_impl,
                 thread,
                 GLCOLORMASK_ID,
                 RPC_BOOLEAN(red),
                 RPC_BOOLEAN(green),
                 RPC_BOOLEAN(blue),
                 RPC_BOOLEAN(alpha));
    }
 }
glColorPointer()
GL_API void GL_APIENTRY glColorPointer (GLint size, GLenum type, GLsizei stride, const GLvoid * pointer)
Definition at line 667 of file glxx_client.c.
 {
    if (is_color_type(type)) {
       if (is_color_size(size) && is_aligned(type, (size_t)pointer) && is_aligned(type, (size_t)stride) && stride >= 0) {
          glintAttribPointer(GLXX_API_11, GL11_IX_COLOR, size, type, GL_TRUE, stride, pointer);
       } else
          glxx_set_error_api(GLXX_API_11, GL_INVALID_VALUE);
    } else
       glxx_set_error_api(GLXX_API_11, GL_INVALID_ENUM);
 }
glCompileShader()
GL_APICALL void GL_APIENTRY glCompileShader (GLuint shader)
Definition at line 4901 of file glxx_client.c.
Referenced by raspitexutil_build_shader_program().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL1(glCompileShader_impl_20,
                 thread,
                 GLCOMPILESHADER_ID_20,
                 RPC_UINT(shader));
    }
 }
glCompressedTexImage2D()
GL_API void GL_APIENTRY glCompressedTexImage2D (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const GLvoid * data)
Definition at line 698 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    GLboolean res;
    if (IS_OPENGLES_11_OR_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       switch (internalformat)
       {
          case GL_ETC1_RGB8_OES:
          {
             uint32_t pitch = 2 * ((width + 3) / 4);
             uint32_t lines = pitch ? (uint32_t)(KHDISPATCH_WORKSPACE_SIZE / pitch) : (uint32_t)height;
             res = RPC_BOOLEAN_RES(RPC_CALL8_IN_BULK_RES(glCompressedTexImage2D_impl,
                               thread,
                               GLCOMPRESSEDTEXIMAGE2D_ID,
                               RPC_ENUM  (target),
                               RPC_INT   (level),
                               RPC_ENUM  (internalformat),
                               RPC_SIZEI (width),
                               RPC_SIZEI (height),
                               RPC_INT   (border),
                               RPC_SIZEI (imageSize),
                               NULL,
                               0));
             if (res && data && lines && width && height) {
                int offset = 0;
                while (height > 0) {
                   int32_t batch = (_min(lines, (int32_t)height) + 3) & ~3;
                   RPC_CALL9_IN_BULK(glCompressedTexSubImage2D_impl,
                                     thread,
                                     GLCOMPRESSEDTEXSUBIMAGE2D_ID,
                                     RPC_ENUM(target),
                                     RPC_INT(level),
                                     RPC_INT(0),
                                     RPC_INT(offset),
                                     RPC_SIZEI(width),
                                     RPC_SIZEI(batch),
                                     RPC_ENUM(internalformat),
                                     batch * pitch,
                                     (char *)data + offset * pitch,
                                     batch * pitch);
                   offset += batch;
                   height -= batch;
                }
             }
             break;
          }
          case GL_PALETTE4_RGB8_OES:
          case GL_PALETTE4_RGBA8_OES:
          case GL_PALETTE4_R5_G6_B5_OES:
          case GL_PALETTE4_RGBA4_OES:
          case GL_PALETTE4_RGB5_A1_OES:
          case GL_PALETTE8_RGB8_OES:
          case GL_PALETTE8_RGBA8_OES:
          case GL_PALETTE8_R5_G6_B5_OES:
          case GL_PALETTE8_RGBA4_OES:
          case GL_PALETTE8_RGB5_A1_OES:
          {
             int palette_size = get_palette_size(internalformat);
             level = -level;
             res = RPC_BOOLEAN_RES(RPC_CALL8_IN_BULK_RES(glCompressedTexImage2D_impl,
                               thread,
                               GLCOMPRESSEDTEXIMAGE2D_ID,
                               RPC_ENUM  (target),
                               RPC_INT   (level),
                               RPC_ENUM  (internalformat),
                               RPC_SIZEI (width),
                               RPC_SIZEI (height),
                               RPC_INT   (border),
                               RPC_SIZEI (imageSize),
                               data,
                               palette_size));
             if (res && data && width && height) {
                int offset = palette_size;
                while (offset < imageSize) {
                   int32_t batch = _min(KHDISPATCH_WORKSPACE_SIZE, imageSize - offset);
                   RPC_CALL9_IN_BULK(glCompressedTexSubImage2D_impl,
                                     thread,
                                     GLCOMPRESSEDTEXSUBIMAGE2D_ID,
                                     RPC_ENUM(target),
                                     RPC_INT(level),
                                     RPC_INT(offset - palette_size),
                                     RPC_INT(0),
                                     RPC_SIZEI(width),
                                     RPC_SIZEI(height),
                                     RPC_ENUM(internalformat),
                                     batch,
                                     (char *)data + offset,
                                     batch);
                   offset += batch;
                }
             }
             break;
          }
          default:
             set_error(state, GL_INVALID_ENUM );
             break;
       }
    }
 }
glCompressedTexSubImage2D()
GL_API void GL_APIENTRY glCompressedTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const GLvoid * data)
Definition at line 808 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    UNUSED(target);
    UNUSED(level);
    UNUSED(xoffset);
    UNUSED(yoffset);
    UNUSED(width);
    UNUSED(height);
    UNUSED(imageSize);
    UNUSED(data);
    if (IS_OPENGLES_11_OR_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       switch (format)
       {
       case GL_ETC1_RGB8_OES:
          // Cannot specify subimages of ETC1 textures
          set_error(state, GL_INVALID_OPERATION);
          break;
       case GL_PALETTE4_RGB8_OES:
       case GL_PALETTE4_RGBA8_OES:
       case GL_PALETTE4_R5_G6_B5_OES:
       case GL_PALETTE4_RGBA4_OES:
       case GL_PALETTE4_RGB5_A1_OES:
       case GL_PALETTE8_RGB8_OES:
       case GL_PALETTE8_RGBA8_OES:
       case GL_PALETTE8_R5_G6_B5_OES:
       case GL_PALETTE8_RGBA4_OES:
       case GL_PALETTE8_RGB5_A1_OES:
          // Cannot specify subimages of paletted textures
          set_error(state, GL_INVALID_OPERATION);
          break;
       default:
          // Some format we don't recognise
          set_error(state, GL_INVALID_VALUE);
          break;
       }
    }
 }
glCopyTexImage2D()
GL_API void GL_APIENTRY glCopyTexImage2D (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border)
Definition at line 850 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL8(glCopyTexImage2D_impl,
                 thread,
                 GLCOPYTEXIMAGE2D_ID,
                 RPC_ENUM(target),
                 RPC_INT(level),
                 RPC_ENUM(internalformat),
                 RPC_INT(x),
                 RPC_INT(y),
                 RPC_SIZEI(width),
                 RPC_SIZEI(height),
                 RPC_INT(border));
    }
 }
glCopyTexSubImage2D()
GL_API void GL_APIENTRY glCopyTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height)
Definition at line 868 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL8(glCopyTexSubImage2D_impl,
                 thread,
                 GLCOPYTEXSUBIMAGE2D_ID,
                 RPC_ENUM(target),
                 RPC_INT(level),
                 RPC_INT(xoffset),
                 RPC_INT(yoffset),
                 RPC_INT(x),
                 RPC_INT(y),
                 RPC_SIZEI(width),
                 RPC_SIZEI(height));
    }
 }
glCreateProgram()
GL_API GLuint GL_APIENTRY glCreateProgram (void)
Definition at line 886 of file glxx_client.c.
Referenced by raspitexutil_build_shader_program().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       return RPC_UINT_RES(RPC_CALL0_RES(glCreateProgram_impl_20,
                                         thread,
                                         GLCREATEPROGRAM_ID_20));
    }
    return 0;
 }
glCreateShader()
GL_API GLuint GL_APIENTRY glCreateShader (GLenum type)
Definition at line 898 of file glxx_client.c.
Referenced by raspitexutil_build_shader_program().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       return RPC_UINT_RES(RPC_CALL1_RES(glCreateShader_impl_20,
                                         thread,
                                         GLCREATESHADER_ID_20,
                                         RPC_ENUM(type)));
    }
    return 0;
 }
glCullFace()
GL_API void GL_APIENTRY glCullFace (GLenum mode)
Definition at line 911 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL1(glCullFace_impl,
                 thread,
                 GLCULLFACE_ID,
                 RPC_ENUM(mode));
    }
 }
glDeleteBuffers()
GL_API void GL_APIENTRY glDeleteBuffers (GLsizei n, const GLuint * buffers)
Definition at line 922 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    int offset = 0;
    if (IS_OPENGLES_11_OR_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       int i, j;
       for (i = 0; i < n; i++) {
          GLuint buffer = buffers[i];
          if (state->bound_buffer.array == buffer)
             state->bound_buffer.array = 0;
          if (state->bound_buffer.element_array == buffer)
             state->bound_buffer.element_array = 0;
          for (j = 0; j < GLXX_CONFIG_MAX_VERTEX_ATTRIBS; j++)
             if (state->attrib[j].buffer == buffer)
                state->attrib[j].buffer = 0;
          buffer_info_delete(state, buffer);
       }
    }
    if (IS_OPENGLES_11_OR_20(thread)) {
       do {
          int32_t items = (int32_t)( KHDISPATCH_WORKSPACE_SIZE / sizeof(GLuint) );
          int32_t batch = _min(items, (int32_t) n);
          RPC_CALL2_IN_BULK(glDeleteBuffers_impl,
                            thread,
                            GLDELETEBUFFERS_ID,
                            RPC_SIZEI(batch),
                            buffers + offset,
                            batch > 0 ? batch * sizeof(GLuint) : 0);
          offset += batch;
          n -= batch;
       } while (n > 0);
    }
 }
glDeleteFramebuffers()
GL_APICALL void GL_APIENTRY glDeleteFramebuffers (GLsizei n, const GLuint * framebuffers)
Definition at line 5328 of file glxx_client.c.
References glxx_client_DeleteFramebuffers().
 {
    glxx_client_DeleteFramebuffers(n, framebuffers);
 }
glDeleteProgram()
GL_API void GL_APIENTRY glDeleteProgram (GLuint program)
Definition at line 965 of file glxx_client.c.
Referenced by raspitexutil_build_shader_program().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL1(glDeleteProgram_impl_20,
                 thread,
                 GLDELETEPROGRAM_ID_20,
                 RPC_UINT(program));
    }
 }
glDeleteRenderbuffers()
GL_APICALL void GL_APIENTRY glDeleteRenderbuffers (GLsizei n, const GLuint * renderbuffers)
Definition at line 5187 of file glxx_client.c.
References glxx_client_DeleteRenderbuffers().
 {
    glxx_client_DeleteRenderbuffers(n, renderbuffers);
 }
glDeleteShader()
GL_API void GL_APIENTRY glDeleteShader (GLuint shader)
Definition at line 976 of file glxx_client.c.
Referenced by raspitexutil_build_shader_program().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL1(glDeleteShader_impl_20,
                 thread,
                 GLDELETESHADER_ID_20,
                 RPC_UINT(shader));
    }
 }
glDeleteTextures()
GL_API void GL_APIENTRY glDeleteTextures (GLsizei n, const GLuint * textures)
Definition at line 987 of file glxx_client.c.
Referenced by raspitexutil_gl_term().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    int offset = 0;
    if (IS_OPENGLES_11_OR_20(thread)) {
       do {
          int32_t items = (int32_t)(KHDISPATCH_WORKSPACE_SIZE / sizeof(GLuint));
          int32_t batch = _min(items, (int32_t)n);
          RPC_CALL2_IN_BULK(glDeleteTextures_impl,
                            thread,
                            GLDELETETEXTURES_ID,
                            RPC_SIZEI(batch),
                            textures + offset,
                            batch > 0 ? batch * sizeof(GLuint) : 0);
          offset += batch;
          n -= batch;
       } while (n > 0);
    }
 }
glDepthFunc()
GL_API void GL_APIENTRY glDepthFunc (GLenum func)
Definition at line 1010 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL1(glDepthFunc_impl,
                 thread,
                 GLDEPTHFUNC_ID,
                 RPC_ENUM(func));
    }
 }
glDepthMask()
GL_API void GL_APIENTRY glDepthMask (GLboolean flag)
Definition at line 1021 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL1(glDepthMask_impl,
                 thread,
                 GLDEPTHMASK_ID,
                 RPC_BOOLEAN(flag));
    }
 }
glDepthRangef()
GL_API void GL_APIENTRY glDepthRangef (GLclampf zNear, GLclampf zFar)
Definition at line 1032 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL2(glDepthRangef_impl,
                 thread,
                 GLDEPTHRANGEF_ID,
                 RPC_FLOAT(zNear),
                 RPC_FLOAT(zFar));
    }
 }
glDepthRangex()
GL_API void GL_APIENTRY glDepthRangex (GLclampx zNear, GLclampx zFar)
Definition at line 1044 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL2(glDepthRangex_impl_11,
                 thread,
                 GLDEPTHRANGEX_ID_11,
                 RPC_FIXED(zNear),
                 RPC_FIXED(zFar));
    }
 }
glDetachShader()
GL_API void GL_APIENTRY glDetachShader (GLuint program, GLuint shader)
Definition at line 1056 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL2(glDetachShader_impl_20,
                 thread,
                 GLDETACHSHADER_ID_20,
                 RPC_UINT(program),
                 RPC_UINT(shader));
    }
 }
glDisable()
GL_API void GL_APIENTRY glDisable (GLenum cap)
Definition at line 1068 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL1(glDisable_impl,
                thread,
                 GLDISABLE_ID,
                 RPC_ENUM(cap));
    }
 }
glDisableClientState()
GL_API void GL_APIENTRY glDisableClientState (GLenum array)
Definition at line 1111 of file glxx_client.c.
 {
    set_enabled_11(array, GL_FALSE);
 }
glDisableVertexAttribArray()
GL_APICALL void GL_APIENTRY glDisableVertexAttribArray (GLuint index)
Definition at line 1116 of file glxx_client.c.
References GL_FALSE, glintAttribEnable(), and GLXX_API_20.
 {
    glintAttribEnable(GLXX_API_20, index, GL_FALSE);
 }
glDiscardFramebufferEXT()
GL_APICALL void GL_APIENTRY glDiscardFramebufferEXT (GLenum target, GLsizei numAttachments, const GLenum * attachments)
Definition at line 5478 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread))
    {
       RPC_CALL3_IN_CTRL(glDiscardFramebufferEXT_impl,
                 thread,
                 GLDISCARDFRAMEBUFFEREXT_ID,
                 RPC_ENUM(target),
                 RPC_SIZEI(numAttachments),
                 attachments,
                 numAttachments * sizeof(GLenum));
    }
 }
glDrawArrays()
GL_API void GL_APIENTRY glDrawArrays (GLenum mode, GLint first, GLsizei count)
Definition at line 1336 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       draw_arrays_or_elements(thread, state, mode, count, 0, (void *)first);
    }
 }
glDrawElements()
GL_API void GL_APIENTRY glDrawElements (GLenum mode, GLsizei count, GLenum type, const GLvoid * indices)
Definition at line 1346 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       if (!is_index_type(type)) {
          set_error(state, GL_INVALID_ENUM);
          return;
       }
       if (!is_aligned(type, (size_t)indices)) {
          set_error(state, GL_INVALID_VALUE);
          return;
       }
       draw_arrays_or_elements(thread, state, mode, count, type, indices);
    }
 }
glEnable()
GL_API void GL_APIENTRY glEnable (GLenum cap)
Definition at line 1363 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL1(glEnable_impl,
                 thread,
                 GLENABLE_ID,
                 RPC_ENUM(cap));
    }
 }
glEnableClientState()
GL_API void GL_APIENTRY glEnableClientState (GLenum array)
Definition at line 1374 of file glxx_client.c.
 {
    set_enabled_11(array, GL_TRUE);
 }
glEnableVertexAttribArray()
GL_APICALL void GL_APIENTRY glEnableVertexAttribArray (GLuint index)
Definition at line 1379 of file glxx_client.c.
References GL_TRUE, glintAttribEnable(), and GLXX_API_20.
 {
    glintAttribEnable(GLXX_API_20, index, GL_TRUE);
 }
glFinish()
GL_API void GL_APIENTRY glFinish (void)
Definition at line 1384 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       (void) RPC_UINT_RES(RPC_CALL0_RES(glFinish_impl,
                     thread,
                     GLFINISH_ID));  // Return ignored - read performed to force blocking
       if (state->flush_callback)
          state->flush_callback(true);
    }
 }
glFlush()
GL_API void GL_APIENTRY glFlush (void)
Definition at line 1398 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       RPC_CALL0(glFlush_impl,
                     thread,
                     GLFLUSH_ID);
       if (state->flush_callback)
          state->flush_callback(false);
    }
    //TODO: where exactly should we put RPC_FLUSH? Are there any other functions
    //which need it? (e.g. eglSwapBuffers)
    RPC_FLUSH(thread);
 }
glFogf()
GL_API void GL_APIENTRY glFogf (GLenum pname, GLfloat param)
Definition at line 1416 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL2(glFogf_impl_11,
                 thread,
                 GLFOGF_ID_11,
                 RPC_ENUM(pname),
                 RPC_FLOAT(param));
    }
 }
glFogfv()
GL_API void GL_APIENTRY glFogfv (GLenum pname, const GLfloat * params)
Definition at line 1428 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       /*
          the only supported fog params are
          FOG_MODE (1)
          FOG_DENSITY (1)
          FOG_START (1)
          FOG_END (1)
          FOG_COLOR (4)
          so we need to transmit 4 words of parameter data
       */
       RPC_CALL2_IN_CTRL(glFogfv_impl_11,
                         thread,
                         GLFOGFV_ID_11,
                         RPC_ENUM(pname),
                         params,
                         4 * sizeof(GLfloat));
    }
 }
glFogx()
GL_API void GL_APIENTRY glFogx (GLenum pname, GLfixed param)
Definition at line 1453 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL2(glFogx_impl_11,
                thread,
                GLFOGX_ID_11,
                RPC_ENUM(pname),
                RPC_FIXED(param));
    }
 }
glFogxv()
GL_API void GL_APIENTRY glFogxv (GLenum pname, const GLfixed * params)
Definition at line 1465 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       /*
          the only supported fog params are
          FOG_MODE (1)
          FOG_DENSITY (1)
          FOG_START (1)
          FOG_END (1)
          FOG_COLOR (4)
          so we need to transmit 4 words of parameter data
       */
       RPC_CALL2_IN_CTRL(glFogxv_impl_11,
                         thread,
                         GLFOGXV_ID_11,
                         RPC_ENUM(pname),
                         params,
                         4 * sizeof(GLfixed));
    }
 }
glFramebufferRenderbuffer()
GL_APICALL void GL_APIENTRY glFramebufferRenderbuffer (GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer)
Definition at line 5412 of file glxx_client.c.
References glxx_client_FramebufferRenderbuffer().
 {
    glxx_client_FramebufferRenderbuffer(target, attachment, renderbuffertarget, renderbuffer);
 }
glFramebufferTexture2D()
GL_APICALL void GL_APIENTRY glFramebufferTexture2D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
Definition at line 5393 of file glxx_client.c.
References glxx_client_FramebufferTexture2D().
 {
    glxx_client_FramebufferTexture2D(target, attachment, textarget, texture, level);
 }
glFrontFace()
GL_API void GL_APIENTRY glFrontFace (GLenum mode)
Definition at line 1490 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL1(glFrontFace_impl,
                 thread,
                 GLFRONTFACE_ID,
                 RPC_ENUM(mode));
    }
 }
glFrustumf()
GL_API void GL_APIENTRY glFrustumf (GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar)
Definition at line 1501 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL6(glFrustumf_impl_11,
                 thread,
                 GLFRUSTUMF_ID_11,
                 RPC_FLOAT(left),
                 RPC_FLOAT(right),
                 RPC_FLOAT(bottom),
                 RPC_FLOAT(top),
                 RPC_FLOAT(zNear),
                 RPC_FLOAT(zFar));
    }
 }
glFrustumx()
GL_API void GL_APIENTRY glFrustumx (GLfixed left, GLfixed right, GLfixed bottom, GLfixed top, GLfixed zNear, GLfixed zFar)
Definition at line 1517 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL6(glFrustumx_impl_11,
                 thread,
                 GLFRUSTUMX_ID_11,
                 RPC_FIXED(left),
                 RPC_FIXED(right),
                 RPC_FIXED(bottom),
                 RPC_FIXED(top),
                 RPC_FIXED(zNear),
                 RPC_FIXED(zFar));
    }
 }
glGenBuffers()
GL_API void GL_APIENTRY glGenBuffers (GLsizei n, GLuint * buffers)
Definition at line 1533 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       int offset = 0;
       do {
          int32_t items = (int32_t) (KHDISPATCH_WORKSPACE_SIZE / sizeof(GLuint));
          int32_t batch = _min(items, (int32_t) n);
          RPC_CALL2_OUT_BULK(glGenBuffers_impl,
                             thread,
                             GLGENBUFFERS_ID,
                             RPC_SIZEI(batch),
                             (GLuint*)(buffers + offset));
          offset += batch;
          n -= batch;
       } while (n > 0);
    }
 }
glGenerateMipmap()
GL_APICALL void GL_APIENTRY glGenerateMipmap (GLenum target)
Definition at line 5447 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       glxx_client_GenerateMipmap(target);
    }
 }
glGenFramebuffers()
GL_APICALL void GL_APIENTRY glGenFramebuffers (GLsizei n, GLuint * framebuffers)
Definition at line 5355 of file glxx_client.c.
References glxx_client_GenFramebuffers().
 {
    glxx_client_GenFramebuffers(n, framebuffers);
 }
glGenRenderbuffers()
GL_APICALL void GL_APIENTRY glGenRenderbuffers (GLsizei n, GLuint * renderbuffers)
Definition at line 5214 of file glxx_client.c.
References glxx_client_GenRenderbuffers().
 {
    glxx_client_GenRenderbuffers(n, renderbuffers);
 }
glGenTextures()
GL_API void GL_APIENTRY glGenTextures (GLsizei n, GLuint * textures)
Definition at line 1555 of file glxx_client.c.
Referenced by raspitexutil_create_textures().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       int offset = 0;
       do {
          int32_t items = (int32_t) (KHDISPATCH_WORKSPACE_SIZE / sizeof(GLuint));
          int32_t batch = _min(items, (int32_t)n);
          RPC_CALL2_OUT_BULK(glGenTextures_impl,
                             thread,
                             GLGENTEXTURES_ID,
                             RPC_SIZEI(batch),
                             textures + offset);
          offset += batch;
          n -= batch;
       } while (n > 0);
    }
 }
glGetActiveAttrib()
GL_APICALL void GL_APIENTRY glGetActiveAttrib (GLuint program, GLuint index, GLsizei bufsize, GLsizei * length, GLint * size, GLenum * type, char * name)
Definition at line 1577 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
 #ifdef RPC_DIRECT
       RPC_CALL7(glGetActiveAttrib_impl_20, thread, no_id, program, index, bufsize, length, size, type, name);
 #else
       GLuint result[3];
       rpc_begin(thread);
       RPC_CALL4_OUT_CTRL(no_function,
                          thread,
                          GLGETACTIVEATTRIB_ID_20,
                          RPC_UINT(program),
                          RPC_UINT(index),
                          RPC_SIZEI(bufsize),
                          result);
       if (length)
          *length = (GLsizei)result[0];
       if (size)
          *size = (GLint)result[1];
       if (type)
          *type = (GLenum)result[2];
       read_out_bulk(thread, name);
       rpc_end(thread);
 #endif
    }
 }
glGetActiveUniform()
GL_APICALL void GL_APIENTRY glGetActiveUniform (GLuint program, GLuint index, GLsizei bufsize, GLsizei * length, GLint * size, GLenum * type, char * name)
Definition at line 1610 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
 #ifdef RPC_DIRECT
       RPC_CALL7(glGetActiveUniform_impl_20, thread, no_id, program, index, bufsize, length, size, type, name);
 #else
       GLuint result[3];
       rpc_begin(thread);
       RPC_CALL4_OUT_CTRL(no_function,
                          thread,
                          GLGETACTIVEUNIFORM_ID_20,
                          RPC_UINT(program),
                          RPC_UINT(index),
                          RPC_SIZEI(bufsize),
                          result);
       if (length)
          *length = (GLsizei)result[0];
       if (size)
          *size = (GLint)result[1];
       if (type)
          *type = (GLenum)result[2];
       read_out_bulk(thread, name);
       rpc_end(thread);
 #endif
    }
 }
glGetAttachedShaders()
GL_APICALL void GL_APIENTRY glGetAttachedShaders (GLuint program, GLsizei maxcount, GLsizei * count, GLuint * shaders)
Definition at line 1643 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
 #ifdef RPC_DIRECT
    RPC_CALL4(glGetAttachedShaders_impl_20, thread, no_id, program, maxcount, count, shaders);
 #else
    GLuint i;
    GLuint result[3];
    RPC_CALL3_OUT_CTRL(no_function,
                       thread,
                       GLGETATTACHEDSHADERS_ID_20,
                       RPC_UINT(program),
                       RPC_SIZEI(maxcount),
                       result);
    if (count)
       *count = (GLsizei) result[0];
    for (i = 0; i < 2; i++)
       if ((GLuint)maxcount > i && result[0] > i)
          shaders[i] = result[i + 1];
 #endif
    }
 }
glGetAttribLocation()
GL_APICALL int GL_APIENTRY glGetAttribLocation (GLuint program, const char * name)
Definition at line 1671 of file glxx_client.c.
Referenced by raspitexutil_build_shader_program().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       return RPC_INT_RES(RPC_CALL2_IN_BULK_RES(glGetAttribLocation_impl_20,
                                                thread,
                                                GLGETATTRIBLOCATION_ID_20,
                                                RPC_UINT(program),
                                                name,
                                                strlen(name) + 1));
    }
    return 0;
 }
glGetBooleanv()
GL_API void GL_APIENTRY glGetBooleanv (GLenum pname, GLboolean * params)
Definition at line 1970 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       switch (pname) {
       case GL_VERTEX_ARRAY:
       case GL_NORMAL_ARRAY:
       case GL_COLOR_ARRAY:
       case GL_TEXTURE_COORD_ARRAY:
       case GL_POINT_SIZE_ARRAY_OES:
          get_boolean_internal_11(thread, pname, params);
          break;
       case GL_CLIENT_ACTIVE_TEXTURE:
       case GL_VERTEX_ARRAY_SIZE:
       case GL_VERTEX_ARRAY_TYPE:
       case GL_VERTEX_ARRAY_STRIDE:
       case GL_NORMAL_ARRAY_TYPE:
       case GL_NORMAL_ARRAY_STRIDE:
       case GL_COLOR_ARRAY_SIZE:
       case GL_COLOR_ARRAY_TYPE:
       case GL_COLOR_ARRAY_STRIDE:
       case GL_TEXTURE_COORD_ARRAY_SIZE:
       case GL_TEXTURE_COORD_ARRAY_TYPE:
       case GL_TEXTURE_COORD_ARRAY_STRIDE:
       case GL_POINT_SIZE_ARRAY_TYPE_OES:
       case GL_POINT_SIZE_ARRAY_STRIDE_OES:
       case GL_ARRAY_BUFFER_BINDING:
       case GL_ELEMENT_ARRAY_BUFFER_BINDING:
       case GL_VERTEX_ARRAY_BUFFER_BINDING:
       case GL_NORMAL_ARRAY_BUFFER_BINDING:
       case GL_COLOR_ARRAY_BUFFER_BINDING:
       case GL_TEXTURE_COORD_ARRAY_BUFFER_BINDING:
       case GL_POINT_SIZE_ARRAY_BUFFER_BINDING_OES:
       case GL_UNPACK_ALIGNMENT:
       case GL_PACK_ALIGNMENT:
       case GL_IMPLEMENTATION_COLOR_READ_TYPE_OES:
       case GL_IMPLEMENTATION_COLOR_READ_FORMAT_OES:
       {
          GLint temp;
          get_integer_internal_11(thread, pname, &temp);
          params[0] = temp != 0;
          break;
       }
       case GL_CURRENT_TEXTURE_COORDS:
       case GL_CURRENT_COLOR:
       case GL_CURRENT_NORMAL:
       case GL_POINT_SIZE:
       {
          GLfloat temp[4];
          GLuint count = (GLuint) get_float_internal_11(thread, pname, temp);
          GLuint i;
          vcos_assert(count <= 4);
          for (i = 0; i < count; i++)
             params[i] = temp[i] != 0.0f;
          break;
       }
       default:
          RPC_CALL2_OUT_CTRL(glGetBooleanv_impl,
                             thread,
                             GLGETBOOLEANV_ID,
                             RPC_ENUM(pname),
                             params);
          break;
       }
    }
    if (IS_OPENGLES_20(thread)) {
       switch (pname) {
       case GL_UNPACK_ALIGNMENT:
       case GL_PACK_ALIGNMENT:
       {
          GLint temp = 0;
          get_integer_internal_20(thread, pname, &temp);
          params[0] = temp != 0;
          break;
       }
       default:
          RPC_CALL2_OUT_CTRL(glGetBooleanv_impl,
                             thread,
                             GLGETBOOLEANV_ID,
                             RPC_ENUM(pname),
                             params);
          break;
       }
    }
 }
glGetBufferParameteriv()
GL_API void GL_APIENTRY glGetBufferParameteriv (GLenum target, GLenum pname, GLint * params)
Definition at line 2065 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       switch(pname) {
       case GL_BUFFER_ACCESS_OES:
       {
          GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
          if(get_bound_buffer(state, target) != 0)
          {
             params[0] = GL_WRITE_ONLY_OES;
          }
          else
          {
             params[0] = 0;
          }
          break;
       }
       case GL_BUFFER_MAPPED_OES:
       {
          GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
          GLXX_BUFFER_INFO_T buffer;
          glxx_buffer_info_get(state, target, &buffer);
          if(buffer.id != 0 && buffer.mapped_pointer != 0)
          {
             params[0] = GL_TRUE;
          }
          else
          {
             params[0] = GL_FALSE;
          }
          break;
       }
       default:
          RPC_CALL3_OUT_CTRL(glGetBufferParameteriv_impl,
                             thread,
                             GLGETBUFFERPARAMETERIV_ID,
                             RPC_ENUM(target),
                             RPC_ENUM(pname),
                             params);
          if(pname == GL_BUFFER_SIZE)
          {
             GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
             GLXX_BUFFER_INFO_T buffer;
             glxx_buffer_info_get(state, target, &buffer);
             buffer.cached_size = params[0];
             glxx_buffer_info_set(state, target, &buffer);
          }
       }
    }
 }
glGetClipPlanef()
GL_API void GL_APIENTRY glGetClipPlanef (GLenum pname, GLfloat eqn[4])
Definition at line 2118 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL2_OUT_CTRL(glGetClipPlanef_impl_11,
                          thread,
                          GLGETCLIPPLANEF_ID_11,
                          RPC_ENUM(pname),
                          eqn);
    }
 }
glGetClipPlanex()
GL_API void GL_APIENTRY glGetClipPlanex (GLenum pname, GLfixed eqn[4])
Definition at line 2130 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL2_OUT_CTRL(glGetClipPlanex_impl_11,
                          thread,
                          GLGETCLIPPLANEX_ID_11,
                          RPC_ENUM(pname),
                          eqn);
    }
 }
glGetError()
GL_API GLenum GL_APIENTRY glGetError (void)
Definition at line 2142 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE(); /* Decrements glgeterror_hack variable for every API call made */
    if (IS_OPENGLES_11_OR_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       GLenum result = state->error;
       if ((result == GL_NO_ERROR) && !thread->async_error_notification) {
          /* Don't query the server if our previous API call was glGetError() */
          if (0 == thread->glgeterror_hack ) {
             result = RPC_ENUM_RES(RPC_CALL0_RES(glGetError_impl,
                                                 thread,
                                                 GLGETERROR_ID));
          }
          if(result != GL_NO_ERROR) {
             vcos_log_warn("glGetError 0x%x", result);
             thread->glgeterror_hack = 0;
          } else {
             thread->glgeterror_hack = 2;
          }
       }
       state->error = GL_NO_ERROR;
       return result;
    }
    return 0;
 }
glGetFixedv()
GL_API void GL_APIENTRY glGetFixedv (GLenum pname, GLfixed * params)
Definition at line 2173 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       switch (pname) {
       case GL_VERTEX_ARRAY:
       case GL_NORMAL_ARRAY:
       case GL_COLOR_ARRAY:
       case GL_TEXTURE_COORD_ARRAY:
       case GL_POINT_SIZE_ARRAY_OES:
       {
          GLboolean temp[4];
          int count = get_boolean_internal_11(thread, pname, temp);
          int i;
          vcos_assert(count <= 4);
          for (i = 0; i < count; i++)
             params[i] = temp[i] ? (GLfixed)float_to_fixed(1.0f) : (GLfixed)float_to_fixed(0.0f);
          break;
       }
       case GL_CURRENT_TEXTURE_COORDS:
       case GL_CURRENT_COLOR:
       case GL_CURRENT_NORMAL:
       case GL_POINT_SIZE:
       {
          GLfloat temp[4];
          int count = get_float_internal_11(thread, pname, temp);
          int i;
          vcos_assert(count <= 4);
          for (i = 0; i < count; i++)
             params[i] = (GLfixed) float_to_fixed(temp[i]);
          break;
       }
       case GL_CLIENT_ACTIVE_TEXTURE:
       case GL_VERTEX_ARRAY_SIZE:
       case GL_VERTEX_ARRAY_TYPE:
       case GL_VERTEX_ARRAY_STRIDE:
       case GL_NORMAL_ARRAY_TYPE:
       case GL_NORMAL_ARRAY_STRIDE:
       case GL_COLOR_ARRAY_SIZE:
       case GL_COLOR_ARRAY_TYPE:
       case GL_COLOR_ARRAY_STRIDE:
       case GL_TEXTURE_COORD_ARRAY_SIZE:
       case GL_TEXTURE_COORD_ARRAY_TYPE:
       case GL_TEXTURE_COORD_ARRAY_STRIDE:
       case GL_POINT_SIZE_ARRAY_TYPE_OES:
       case GL_POINT_SIZE_ARRAY_STRIDE_OES:
       case GL_ARRAY_BUFFER_BINDING:
       case GL_ELEMENT_ARRAY_BUFFER_BINDING:
       case GL_VERTEX_ARRAY_BUFFER_BINDING:
       case GL_NORMAL_ARRAY_BUFFER_BINDING:
       case GL_COLOR_ARRAY_BUFFER_BINDING:
       case GL_TEXTURE_COORD_ARRAY_BUFFER_BINDING:
       case GL_POINT_SIZE_ARRAY_BUFFER_BINDING_OES:
       case GL_UNPACK_ALIGNMENT:
       case GL_PACK_ALIGNMENT:
       case GL_IMPLEMENTATION_COLOR_READ_TYPE_OES:
       case GL_IMPLEMENTATION_COLOR_READ_FORMAT_OES:
       {
          GLint temp;
          get_integer_internal_11(thread, pname, &temp);
          params[0] = (GLfixed) float_to_fixed((GLfloat)temp);
          break;
       }
       default:
          RPC_CALL2_OUT_CTRL(glGetFixedv_impl_11,
                             thread,
                             GLGETFIXEDV_ID_11,
                             RPC_ENUM(pname),
                             params);
          break;
       }
    }
 }
glGetFloatv()
GL_API void GL_APIENTRY glGetFloatv (GLenum pname, GLfloat * params)
Definition at line 2257 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       switch (pname) {
       case GL_VERTEX_ARRAY:
       case GL_NORMAL_ARRAY:
       case GL_COLOR_ARRAY:
       case GL_TEXTURE_COORD_ARRAY:
       case GL_POINT_SIZE_ARRAY_OES:
       {
          GLboolean temp[4];
          GLuint count = (GLuint) get_boolean_internal_11(thread, pname, temp);
          GLuint i;
          vcos_assert(count <= 4);
          for (i = 0; i < count; i++)
             params[i] = temp[i] ? 1.0f : 0.0f;
          break;
       }
       case GL_CURRENT_TEXTURE_COORDS:
       case GL_CURRENT_COLOR:
       case GL_CURRENT_NORMAL:
       case GL_POINT_SIZE:
          get_float_internal_11(thread, pname, params);
          break;
       case GL_CLIENT_ACTIVE_TEXTURE:
       case GL_VERTEX_ARRAY_SIZE:
       case GL_VERTEX_ARRAY_TYPE:
       case GL_VERTEX_ARRAY_STRIDE:
       case GL_NORMAL_ARRAY_TYPE:
       case GL_NORMAL_ARRAY_STRIDE:
       case GL_COLOR_ARRAY_SIZE:
       case GL_COLOR_ARRAY_TYPE:
       case GL_COLOR_ARRAY_STRIDE:
       case GL_TEXTURE_COORD_ARRAY_SIZE:
       case GL_TEXTURE_COORD_ARRAY_TYPE:
       case GL_TEXTURE_COORD_ARRAY_STRIDE:
       case GL_POINT_SIZE_ARRAY_TYPE_OES:
       case GL_POINT_SIZE_ARRAY_STRIDE_OES:
       case GL_ARRAY_BUFFER_BINDING:
       case GL_ELEMENT_ARRAY_BUFFER_BINDING:
       case GL_VERTEX_ARRAY_BUFFER_BINDING:
       case GL_NORMAL_ARRAY_BUFFER_BINDING:
       case GL_COLOR_ARRAY_BUFFER_BINDING:
       case GL_TEXTURE_COORD_ARRAY_BUFFER_BINDING:
       case GL_POINT_SIZE_ARRAY_BUFFER_BINDING_OES:
       case GL_UNPACK_ALIGNMENT:
       case GL_PACK_ALIGNMENT:
       case GL_IMPLEMENTATION_COLOR_READ_TYPE_OES:
       case GL_IMPLEMENTATION_COLOR_READ_FORMAT_OES:
       {
          GLint temp;
          get_integer_internal_11(thread, pname, &temp);
          params[0] = (GLfloat)temp;
          break;
       }
       default:
          RPC_CALL2_OUT_CTRL(glGetFloatv_impl,
                             thread,
                             GLGETFLOATV_ID,
                             RPC_ENUM(pname),
                             params);
          break;
       }
    }
    else if (IS_OPENGLES_20(thread)) {
       switch (pname) {
       case GL_UNPACK_ALIGNMENT:
       case GL_PACK_ALIGNMENT:
       {
          GLint temp = 0;
          get_integer_internal_20(thread, pname, &temp);
          params[0] = (GLfloat)temp;
          break;
       }
       default:
          RPC_CALL2_OUT_CTRL(glGetFloatv_impl,
                             thread,
                             GLGETFLOATV_ID,
                             RPC_ENUM(pname),
                             params);
          break;
       }
    }
 }
glGetFramebufferAttachmentParameteriv()
GL_APICALL void GL_APIENTRY glGetFramebufferAttachmentParameteriv (GLenum target, GLenum attachment, GLenum pname, GLint * params)
Definition at line 5431 of file glxx_client.c.
References glxx_client_GetFramebufferAttachmentParameteriv().
 {
    glxx_client_GetFramebufferAttachmentParameteriv(target, attachment, pname, params);
 }
glGetIntegerv()
GL_API void GL_APIENTRY glGetIntegerv (GLenum pname, GLint * params)
Definition at line 2351 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       switch (pname) {
       case GL_VERTEX_ARRAY:
       case GL_NORMAL_ARRAY:
       case GL_COLOR_ARRAY:
       case GL_TEXTURE_COORD_ARRAY:
       case GL_POINT_SIZE_ARRAY_OES:
       {
          GLboolean temp[4];
          GLuint count = (GLuint) get_boolean_internal_11(thread, pname, temp);
          GLuint i;
          vcos_assert(count <= 4);
          for (i = 0; i < count; i++)
             params[i] = temp[i] ? 1 : 0;
          break;
       }
       case GL_CURRENT_COLOR:
       case GL_CURRENT_NORMAL:
       {
          GLfloat temp[4];
          GLuint count = (GLuint) get_float_internal_11(thread, pname, temp);
          GLuint i;
          vcos_assert(count <= 4);
          for (i = 0; i < count; i++)
             params[i] = (GLint)floor((4294967295.0f * temp[i] - 1.0f) / 2.0f + 0.5f);
          //TODO: that the above is correct wrt table 2.7 in the GL spec
          break;
       }
       case GL_CURRENT_TEXTURE_COORDS:
       case GL_POINT_SIZE:
       {
          GLfloat temp[4];
          GLuint count = (GLuint) get_float_internal_11(thread, pname, temp);
          GLuint i;
          vcos_assert(count <= 4);
          for (i = 0; i < count; i++)
             params[i] = (GLint) float_to_int(temp[i]);
          break;
       }
       case GL_CLIENT_ACTIVE_TEXTURE:
       case GL_VERTEX_ARRAY_SIZE:
       case GL_VERTEX_ARRAY_TYPE:
       case GL_VERTEX_ARRAY_STRIDE:
       case GL_NORMAL_ARRAY_TYPE:
       case GL_NORMAL_ARRAY_STRIDE:
       case GL_COLOR_ARRAY_SIZE:
       case GL_COLOR_ARRAY_TYPE:
       case GL_COLOR_ARRAY_STRIDE:
       case GL_TEXTURE_COORD_ARRAY_SIZE:
       case GL_TEXTURE_COORD_ARRAY_TYPE:
       case GL_TEXTURE_COORD_ARRAY_STRIDE:
       case GL_POINT_SIZE_ARRAY_TYPE_OES:
       case GL_POINT_SIZE_ARRAY_STRIDE_OES:
       case GL_MATRIX_INDEX_ARRAY_SIZE_OES:
       case GL_MATRIX_INDEX_ARRAY_TYPE_OES:
       case GL_MATRIX_INDEX_ARRAY_STRIDE_OES:
       case GL_WEIGHT_ARRAY_SIZE_OES:
       case GL_WEIGHT_ARRAY_TYPE_OES:
       case GL_WEIGHT_ARRAY_STRIDE_OES:
       case GL_ARRAY_BUFFER_BINDING:
       case GL_ELEMENT_ARRAY_BUFFER_BINDING:
       case GL_VERTEX_ARRAY_BUFFER_BINDING:
       case GL_NORMAL_ARRAY_BUFFER_BINDING:
       case GL_COLOR_ARRAY_BUFFER_BINDING:
       case GL_TEXTURE_COORD_ARRAY_BUFFER_BINDING:
       case GL_POINT_SIZE_ARRAY_BUFFER_BINDING_OES:
       case GL_MATRIX_INDEX_ARRAY_BUFFER_BINDING_OES:
       case GL_WEIGHT_ARRAY_BUFFER_BINDING_OES:
       case GL_UNPACK_ALIGNMENT:
       case GL_PACK_ALIGNMENT:
       case GL_IMPLEMENTATION_COLOR_READ_TYPE_OES:
       case GL_IMPLEMENTATION_COLOR_READ_FORMAT_OES:
          get_integer_internal_11(thread, pname, params);
          break;
       default:
          RPC_CALL2_OUT_CTRL(glGetIntegerv_impl,
                             thread,
                             GLGETINTEGERV_ID,
                             RPC_ENUM(pname),
                             params);
          break;
       }
    }
    else if (IS_OPENGLES_20(thread)) {
       switch (pname) {
       case GL_UNPACK_ALIGNMENT:
       case GL_PACK_ALIGNMENT:
          get_integer_internal_20(thread, pname, params);
          break;
       default:
          RPC_CALL2_OUT_CTRL(glGetIntegerv_impl,
                             thread,
                             GLGETINTEGERV_ID,
                             RPC_ENUM(pname),
                             params);
          break;
       }
    }
 }
glGetLightfv()
GL_API void GL_APIENTRY glGetLightfv (GLenum light, GLenum pname, GLfloat * params)
Definition at line 2464 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL3_OUT_CTRL(glGetLightfv_impl_11,
                          thread,
                          GLGETLIGHTFV_ID_11,
                          RPC_ENUM(light),
                          RPC_ENUM(pname),
                          params);
    }
 }
glGetLightxv()
GL_API void GL_APIENTRY glGetLightxv (GLenum light, GLenum pname, GLfixed * params)
Definition at line 2477 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL3_OUT_CTRL(glGetLightxv_impl_11,
                          thread,
                          GLGETLIGHTXV_ID_11,
                          RPC_ENUM(light),
                          RPC_ENUM(pname),
                          params);
    }
 }
glGetMaterialfv()
GL_API void GL_APIENTRY glGetMaterialfv (GLenum face, GLenum pname, GLfloat * params)
Definition at line 2490 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL3_OUT_CTRL(glGetMaterialfv_impl_11,
                          thread,
                          GLGETMATERIALFV_ID_11,
                          RPC_ENUM(face),
                          RPC_ENUM(pname),
                          params);
    }
 }
glGetMaterialxv()
GL_API void GL_APIENTRY glGetMaterialxv (GLenum face, GLenum pname, GLfixed * params)
Definition at line 2503 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL3_OUT_CTRL(glGetMaterialxv_impl_11,
                          thread,
                          GLGETMATERIALXV_ID_11,
                          RPC_ENUM(face),
                          RPC_ENUM(pname),
                          params);
    }
 }
glGetPointerv()
GL_API void GL_APIENTRY glGetPointerv (GLenum pname, GLvoid ** params)
Definition at line 2526 of file glxx_client.c.
References GL11_IX_CLIENT_ACTIVE_TEXTURE, GL11_IX_COLOR, GL11_IX_MATRIX_INDEX, GL11_IX_MATRIX_WEIGHT, GL11_IX_NORMAL, GL11_IX_POINT_SIZE, GL11_IX_VERTEX, GL_COLOR_ARRAY_POINTER, GL_INVALID_ENUM, GL_MATRIX_INDEX_ARRAY_POINTER_OES, GL_NORMAL_ARRAY_POINTER, GL_POINT_SIZE_ARRAY_POINTER_OES, GL_TEXTURE_COORD_ARRAY_POINTER, GL_VERTEX_ARRAY_POINTER, GL_WEIGHT_ARRAY_POINTER_OES, glintAttribGetPointer(), GLXX_API_11, glxx_set_error_api(), and NULL.
 {
    void *result = NULL;
    switch (pname) {
    case GL_VERTEX_ARRAY_POINTER:
       result = glintAttribGetPointer(GLXX_API_11, GL11_IX_VERTEX);
       break;
    case GL_NORMAL_ARRAY_POINTER:
       result = glintAttribGetPointer(GLXX_API_11, GL11_IX_NORMAL);
       break;
    case GL_COLOR_ARRAY_POINTER:
       result = glintAttribGetPointer(GLXX_API_11, GL11_IX_COLOR);
       break;
    case GL_TEXTURE_COORD_ARRAY_POINTER:
       result = glintAttribGetPointer(GLXX_API_11, GL11_IX_CLIENT_ACTIVE_TEXTURE);
       break;
    case GL_POINT_SIZE_ARRAY_POINTER_OES:
       result = glintAttribGetPointer(GLXX_API_11, GL11_IX_POINT_SIZE);
       break;
 #if GL_OES_matrix_palette
    case GL_MATRIX_INDEX_ARRAY_POINTER_OES:
       result = glintAttribGetPointer(GLXX_API_11, GL11_IX_MATRIX_INDEX);
       break;
    case GL_WEIGHT_ARRAY_POINTER_OES:
       result = glintAttribGetPointer(GLXX_API_11, GL11_IX_MATRIX_WEIGHT);
       break;
 #endif
    default:
       glxx_set_error_api(GLXX_API_11, GL_INVALID_ENUM);
       break;
    }
    if (result != NULL)
       params[0] = result;
 }
glGetProgramInfoLog()
GL_APICALL void GL_APIENTRY glGetProgramInfoLog (GLuint program, GLsizei bufsize, GLsizei * length, char * infolog)
Definition at line 2576 of file glxx_client.c.
Referenced by raspitexutil_build_shader_program().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
 #ifdef RPC_DIRECT
       RPC_CALL4(glGetProgramInfoLog_impl_20, thread, no_id, program, bufsize, length, infolog);
 #else
       GLuint result[1];
       rpc_begin(thread);
       RPC_CALL3_OUT_CTRL(no_function,
                          thread,
                          GLGETPROGRAMINFOLOG_ID_20,
                          RPC_UINT(program),
                          RPC_SIZEI(bufsize),
                          result);
       if (length)
          *length = (GLsizei)result[0];
       read_out_bulk(thread, infolog);
       rpc_end(thread);
 #endif
    }
 }
glGetProgramiv()
GL_APICALL void GL_APIENTRY glGetProgramiv (GLuint program, GLenum pname, GLint * params)
Definition at line 2563 of file glxx_client.c.
Referenced by raspitexutil_build_shader_program().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL3_OUT_CTRL(glGetProgramiv_impl_20,
                          thread,
                          GLGETPROGRAMIV_ID_20,
                          RPC_UINT(program),
                          RPC_ENUM(pname),
                          params);
    }
 }
glGetRenderbufferParameteriv()
GL_APICALL void GL_APIENTRY glGetRenderbufferParameteriv (GLenum target, GLenum pname, GLint * params)
Definition at line 5251 of file glxx_client.c.
References glxx_client_GetRenderbufferParameteriv().
 {
    glxx_client_GetRenderbufferParameteriv(target, pname, params);
 }
glGetShaderInfoLog()
GL_APICALL void GL_APIENTRY glGetShaderInfoLog (GLuint shader, GLsizei bufsize, GLsizei * length, char * infolog)
Definition at line 4925 of file glxx_client.c.
Referenced by raspitexutil_build_shader_program().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
 #ifdef RPC_DIRECT
       RPC_CALL4(glGetShaderInfoLog_impl_20, thread, no_id, shader, bufsize, length, infolog);
 #else
       GLuint result[1];
       rpc_begin(thread);
       RPC_CALL3_OUT_CTRL(no_function,
                          thread,
                          GLGETSHADERINFOLOG_ID_20,
                          RPC_UINT(shader),
                          RPC_SIZEI(bufsize),
                          result);
       if (length)
          *length = (GLsizei)result[0];
       read_out_bulk(thread, infolog);
       rpc_end(thread);
 #endif
    }
 }
glGetShaderiv()
GL_APICALL void GL_APIENTRY glGetShaderiv (GLuint shader, GLenum pname, GLint * params)
Definition at line 4912 of file glxx_client.c.
Referenced by raspitexutil_build_shader_program().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL3_OUT_CTRL(glGetShaderiv_impl_20,
                          thread,
                          GLGETSHADERIV_ID_20,
                          RPC_ENUM(shader),
                          RPC_ENUM(pname),
                          params);
    }
 }
glGetShaderPrecisionFormat()
GL_APICALL void GL_APIENTRY glGetShaderPrecisionFormat (GLenum shadertype, GLenum precisiontype, GLint * range, GLint * precision)
Definition at line 5456 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       GLint result[3];
       RPC_CALL3_OUT_CTRL(glGetShaderPrecisionFormat_impl_20,
                          thread,
                          GLGETSHADERPRECISIONFORMAT_ID_20,
                          RPC_ENUM(shadertype),
                          RPC_ENUM(precisiontype),
                          result);
       if (range) {
          range[0] = result[0];
          range[1] = result[1];
       }
       if (precision)
          *precision = result[2];
    }
 }
glGetShaderSource()
GL_APICALL void GL_APIENTRY glGetShaderSource (GLuint shader, GLsizei bufsize, GLsizei * length, char * source)
Definition at line 4953 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
 #ifdef RPC_DIRECT
       RPC_CALL4(glGetShaderSource_impl_20, thread, no_id, shader, bufsize, length, source);
 #else
       GLuint result[1];
       rpc_begin(thread);
       RPC_CALL3_OUT_CTRL(no_function,
                          thread,
                          GLGETSHADERSOURCE_ID_20,
                          RPC_UINT(shader),
                          RPC_SIZEI(bufsize),
                          result);
       if (length)
          *length = (GLsizei)result[0];
       read_out_bulk(thread, source);
       rpc_end(thread);
 #endif
    }
 }
glGetString()
GL_API const GLubyte* GL_APIENTRY glGetString (GLenum name)
Definition at line 2604 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       vcos_assert(state != NULL);
       switch (name) {
       case GL_VENDOR:
 #ifndef NDEBUG
          return (const GLubyte *)"Broadcom DEBUG";
 #else
          return (const GLubyte *)"Broadcom";
 #endif
       case GL_RENDERER:
          return (const GLubyte *)"VideoCore IV HW";
       case GL_VERSION:
          return (const GLubyte *)"OpenGL ES-CM 1.1";
       case GL_EXTENSIONS:
          return (const GLubyte *)"GL_OES_compressed_ETC1_RGB8_texture "
                                  "GL_OES_compressed_paletted_texture "
                                  "GL_OES_texture_npot "  /*TODO is npot right? I can't find it in glext.h */
                                  "GL_OES_EGL_image "
                                  "GL_OES_EGL_image_external "
                                  "GL_EXT_discard_framebuffer "
                                  "GL_OES_query_matrix "
                                  "GL_OES_framebuffer_object "
                                  "GL_OES_rgb8_rgba8 "
                                  "GL_OES_depth24 "
                                  "GL_OES_depth32 "
                                  "GL_OES_stencil8 "
                                  "GL_OES_draw_texture "
                                  "GL_OES_mapbuffer "
 #if GL_EXT_texture_format_BGRA8888
                                  "GL_EXT_texture_format_BGRA8888 "
 #endif
 #if GL_APPLE_rgb_422
                                  "GL_APPLE_rgb_422 "
 #endif
 #if GL_OES_matrix_palette
                                  "GL_OES_matrix_palette "
 #endif
 #ifdef GL_EXT_debug_marker
                                  "GL_EXT_debug_marker "
 #endif
                                  ;
       default:
          set_error(state, GL_INVALID_ENUM);
          return NULL;
       }
    }
    else if (IS_OPENGLES_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       vcos_assert(state != NULL);
       switch (name) {
       case GL_VENDOR:
 #ifndef NDEBUG
          return (const GLubyte *)"Broadcom DEBUG";
 #else
          return (const GLubyte *)"Broadcom";
 #endif
       case GL_RENDERER:
          return (const GLubyte *)"VideoCore IV HW";
       case GL_VERSION:
          return (const GLubyte *)"OpenGL ES 2.0";
       case GL_SHADING_LANGUAGE_VERSION:
          return (const GLubyte *)"OpenGL ES GLSL ES 1.00";
       case GL_EXTENSIONS:
          return (const GLubyte *)"GL_OES_compressed_ETC1_RGB8_texture "
                                  "GL_OES_compressed_paletted_texture "
                                  "GL_OES_texture_npot "
                                  "GL_OES_depth24 "
                                  "GL_OES_vertex_half_float "
                                  "GL_OES_EGL_image "
                                  "GL_OES_EGL_image_external "
                                  "GL_EXT_discard_framebuffer "
                                  "GL_OES_rgb8_rgba8 "
                                  "GL_OES_depth32 "
                                  "GL_OES_mapbuffer "
 #if GL_EXT_texture_format_BGRA8888
                                  "GL_EXT_texture_format_BGRA8888 "
 #endif
 #if GL_APPLE_rgb_422
                                  "GL_APPLE_rgb_422 "
 #endif
 #ifdef GL_EXT_debug_marker
                                  "GL_EXT_debug_marker "
 #endif
                                  ;
       default:
          set_error(state, GL_INVALID_ENUM);
          return NULL;
       }
    }
    return NULL;
 }
glGetTexEnvfv()
GL_API void GL_APIENTRY glGetTexEnvfv (GLenum env, GLenum pname, GLfloat * params)
Definition at line 2718 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL3_OUT_CTRL(glGetTexEnvfv_impl_11,
                          thread,
                          GLGETTEXENVFV_ID_11,
                          RPC_ENUM(env),
                          RPC_ENUM(pname),
                          params);
    }
 }
glGetTexEnviv()
GL_API void GL_APIENTRY glGetTexEnviv (GLenum env, GLenum pname, GLint * params)
Definition at line 2705 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL3_OUT_CTRL(glGetTexEnviv_impl_11,
                          thread,
                          GLGETTEXENVIV_ID_11,
                          RPC_ENUM(env),
                          RPC_ENUM(pname),
                          params);
    }
 }
glGetTexEnvxv()
GL_API void GL_APIENTRY glGetTexEnvxv (GLenum env, GLenum pname, GLfixed * params)
Definition at line 2731 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL3_OUT_CTRL(glGetTexEnvxv_impl_11,
                          thread,
                          GLGETTEXENVXV_ID_11,
                          RPC_ENUM(env),
                          RPC_ENUM(pname),
                          params);
    }
 }
glGetTexParameterfv()
GL_API void GL_APIENTRY glGetTexParameterfv (GLenum target, GLenum pname, GLfloat * params)
Definition at line 2757 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL3_OUT_CTRL(glGetTexParameterfv_impl,
                          thread,
                          GLGETTEXPARAMETERFV_ID,
                          RPC_ENUM(target),
                          RPC_ENUM(pname),
                          params);
    }
 }
glGetTexParameteriv()
GL_API void GL_APIENTRY glGetTexParameteriv (GLenum target, GLenum pname, GLint * params)
Definition at line 2744 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL3_OUT_CTRL(glGetTexParameteriv_impl,
                          thread,
                          GLGETTEXPARAMETERIV_ID,
                          RPC_ENUM(target),
                          RPC_ENUM(pname),
                          params);
    }
 }
glGetTexParameterxv()
GL_API void GL_APIENTRY glGetTexParameterxv (GLenum target, GLenum pname, GLfixed * params)
Definition at line 2770 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL3_OUT_CTRL(glGetTexParameterxv_impl_11,
                          thread,
                          GLGETTEXPARAMETERXV_ID_11,
                          RPC_ENUM(target),
                          RPC_ENUM(pname),
                          params);
    }
 }
glGetUniformfv()
GL_APICALL void GL_APIENTRY glGetUniformfv (GLuint program, GLint location, GLfloat * params)
Definition at line 2783 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL3_OUT_CTRL(glGetUniformfv_impl_20,
                          thread,
                          GLGETUNIFORMFV_ID_20,
                          RPC_UINT(program),
                          RPC_INT(location),
                          params);
    }
 }
glGetUniformiv()
GL_APICALL void GL_APIENTRY glGetUniformiv (GLuint program, GLint location, GLint * params)
Definition at line 2796 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL3_OUT_CTRL(glGetUniformiv_impl_20,
                          thread,
                          GLGETUNIFORMIV_ID_20,
                          RPC_UINT(program),
                          RPC_INT(location),
                          params);
    }
 }
glGetUniformLocation()
GL_APICALL int GL_APIENTRY glGetUniformLocation (GLuint program, const char * name)
Definition at line 2809 of file glxx_client.c.
Referenced by raspitexutil_build_shader_program().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       return RPC_INT_RES(RPC_CALL2_IN_BULK_RES(glGetUniformLocation_impl_20,
                                                thread,
                                                GLGETUNIFORMLOCATION_ID_20,
                                                RPC_UINT(program),
                                                name,
                                                strlen(name) + 1));
    }
    return 0;
 }
glGetVertexAttribfv()
GL_APICALL void GL_APIENTRY glGetVertexAttribfv (GLuint index, GLenum pname, GLfloat * params)
Definition at line 2837 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       vcos_assert(state != NULL);
       if (index < GL20_CONFIG_MAX_VERTEX_ATTRIBS)
          switch (pname) {
          case GL_CURRENT_VERTEX_ATTRIB:
             params[0] = state->attrib[index].value[0];
             params[1] = state->attrib[index].value[1];
             params[2] = state->attrib[index].value[2];
             params[3] = state->attrib[index].value[3];
             break;
          //TODO: is this the best way to handle conversions? We duplicate
          //the entire switch statement.
          case GL_VERTEX_ATTRIB_ARRAY_ENABLED:
             params[0] = state->attrib[index].enabled ? 1.0f : 0.0f;
             break;
          case GL_VERTEX_ATTRIB_ARRAY_SIZE:
             params[0] = (GLfloat)state->attrib[index].size;
             break;
          case GL_VERTEX_ATTRIB_ARRAY_STRIDE:
             params[0] = (GLfloat)state->attrib[index].stride;
             break;
          case GL_VERTEX_ATTRIB_ARRAY_TYPE:
             params[0] = (GLfloat)state->attrib[index].type;
             break;
          case GL_VERTEX_ATTRIB_ARRAY_NORMALIZED:
             params[0] = state->attrib[index].normalized ? 1.0f : 0.0f;
             break;
          case GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING:
             params[0] = (GLfloat)state->attrib[index].buffer;
             break;
          default:
             set_error(state, GL_INVALID_ENUM);
             break;
          }
       else
          set_error(state, GL_INVALID_VALUE);
    }
 }
glGetVertexAttribiv()
GL_APICALL void GL_APIENTRY glGetVertexAttribiv (GLuint index, GLenum pname, GLint * params)
Definition at line 2886 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       vcos_assert(state != NULL);
       if (index < GL20_CONFIG_MAX_VERTEX_ATTRIBS)
          switch (pname) {
          case GL_VERTEX_ATTRIB_ARRAY_ENABLED:
             params[0] = (GLint) state->attrib[index].enabled ? GL_TRUE : GL_FALSE;
             break;
          case GL_VERTEX_ATTRIB_ARRAY_SIZE:
             params[0] = (GLint) state->attrib[index].size;
             break;
          case GL_VERTEX_ATTRIB_ARRAY_STRIDE:
             params[0] = (GLint) state->attrib[index].stride;
             break;
          case GL_VERTEX_ATTRIB_ARRAY_TYPE:
             params[0] = (GLint) state->attrib[index].type;
             break;
          case GL_VERTEX_ATTRIB_ARRAY_NORMALIZED:
             params[0] = (GLint) state->attrib[index].normalized ? GL_TRUE : GL_FALSE;
             break;
          case GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING:
             params[0] = (GLint) state->attrib[index].buffer;
             break;
          //TODO: is this the best way to handle conversions? We duplicate
          //the entire switch statement.
          case GL_CURRENT_VERTEX_ATTRIB:
             params[0] = (GLint)state->attrib[index].value[0];
             params[1] = (GLint)state->attrib[index].value[1];
             params[2] = (GLint)state->attrib[index].value[2];
             params[3] = (GLint)state->attrib[index].value[3];
             break;
          default:
             set_error(state, GL_INVALID_ENUM);
             break;
          }
       else
          set_error(state, GL_INVALID_VALUE);
    }
 }
glGetVertexAttribPointerv()
GL_APICALL void GL_APIENTRY glGetVertexAttribPointerv (GLuint index, GLenum pname, void ** pointer)
Definition at line 2940 of file glxx_client.c.
References GL_INVALID_ENUM, GL_VERTEX_ATTRIB_ARRAY_POINTER, glintAttribGetPointer(), GLXX_API_20, glxx_set_error_api(), and NULL.
 {
    void *result = NULL;
    if (pname == GL_VERTEX_ATTRIB_ARRAY_POINTER)
       result = glintAttribGetPointer(GLXX_API_20, index);
    else
       glxx_set_error_api(GLXX_API_20, GL_INVALID_ENUM);
    if (result != NULL)
       *pointer = result;
 }
glHint()
GL_API void GL_APIENTRY glHint (GLenum target, GLenum mode)
Definition at line 2953 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL2(glHint_impl,
                 thread,
                 GLHINT_ID,
                 RPC_ENUM(target),
                 RPC_ENUM(mode));
    }
 }
glintAttrib()
void glintAttrib (uint32_t api, uint32_t indx, float x, float y, float z, float w)
Definition at line 5639 of file glxx_client.c.
Referenced by glMultiTexCoord4f(), glMultiTexCoord4x(), glNormal3f(), glNormal3x(), glPointSizex(), glVertexAttrib1f(), glVertexAttrib1fv(), glVertexAttrib2f(), glVertexAttrib2fv(), glVertexAttrib3f(), glVertexAttrib3fv(), glVertexAttrib4f(), and glVertexAttrib4fv().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_API(thread, api))
    {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       if (attrib_translate(state, &indx))
       {
          vcos_assert(indx < GLXX_CONFIG_MAX_VERTEX_ATTRIBS);
          state->attrib[indx].value[0] = x;
          state->attrib[indx].value[1] = y;
          state->attrib[indx].value[2] = z;
          state->attrib[indx].value[3] = w;
          RPC_CALL6(glintAttrib_impl,
                    thread,
                    GLINTATTRIB_ID,
                    RPC_UINT(api),
                    RPC_UINT(indx),
                    RPC_FLOAT(x),
                    RPC_FLOAT(y),
                    RPC_FLOAT(z),
                    RPC_FLOAT(w));
       }
    }
 }
glintAttribEnable()
void glintAttribEnable (uint32_t api, uint32_t indx, bool enabled)
Definition at line 5692 of file glxx_client.c.
Referenced by glDisableVertexAttribArray(), and glEnableVertexAttribArray().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_API(thread, api))
    {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       if (attrib_translate(state, &indx))
       {
          state->attrib[indx].enabled = enabled;
          RPC_CALL3(glintAttribEnable_impl,
                    thread,
                    GLINTATTRIBENABLE_ID,
                    RPC_UINT(api),
                    RPC_UINT(indx),
                    RPC_BOOLEAN(enabled));
       }
    }
 }
glintAttribGetPointer()
void* glintAttribGetPointer (uint32_t api, uint32_t indx)
Definition at line 5712 of file glxx_client.c.
Referenced by glGetPointerv(), and glGetVertexAttribPointerv().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_API(thread, api))
    {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       if (attrib_translate(state, &indx))
          return (void *)state->attrib[indx].pointer;
    }
    return NULL;
 }
glintAttribPointer()
void glintAttribPointer (uint32_t api, uint32_t indx, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const GLvoid * ptr)
Definition at line 5610 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_API(thread, api))
    {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       if (attrib_translate(state, &indx))
       {
          state->attrib[indx].size = size;
          state->attrib[indx].type = type;
          state->attrib[indx].normalized = normalized;
          state->attrib[indx].stride = stride;
          state->attrib[indx].pointer = ptr;
          state->attrib[indx].buffer = state->bound_buffer.array;
          RPC_CALL7(glintAttribPointer_impl,
                    thread,
                    GLINTATTRIBPOINTER_ID,
                    RPC_UINT(api),
                    RPC_UINT(indx),
                    RPC_INT(size),
                    RPC_ENUM(type),
                    RPC_BOOLEAN(normalized),
                    RPC_SIZEI(stride),
                    RPC_INTPTR((GLintptr)ptr));
       }
    }
 }
glintColor()
void glintColor (float x, float y, float z, float w)
Definition at line 5670 of file glxx_client.c.
Referenced by glColor4f(), glColor4ub(), and glColor4x().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread))
    {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       state->attrib[GL11_IX_COLOR].value[0] = x;
       state->attrib[GL11_IX_COLOR].value[1] = y;
       state->attrib[GL11_IX_COLOR].value[2] = z;
       state->attrib[GL11_IX_COLOR].value[3] = w;
       RPC_CALL4(glintColor_impl_11,
                 thread,
                 GLINTCOLOR_ID_11,
                 RPC_FLOAT(x),
                 RPC_FLOAT(y),
                 RPC_FLOAT(z),
                 RPC_FLOAT(w));
    }
 }
glIsBuffer()
GL_API GLboolean GL_APIENTRY glIsBuffer (GLuint buffer)
Definition at line 2965 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       return RPC_BOOLEAN_RES(RPC_CALL1_RES(glIsBuffer_impl,
                                            thread,
                                            GLISBUFFER_ID,
                                            RPC_UINT(buffer)));
    }
    return 0;
 }
glIsEnabled()
GL_API GLboolean GL_APIENTRY glIsEnabled (GLenum cap)
Definition at line 2978 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       switch (cap) {
       case GL_VERTEX_ARRAY:
       case GL_NORMAL_ARRAY:
       case GL_COLOR_ARRAY:
       case GL_POINT_SIZE_ARRAY_OES:
       case GL_TEXTURE_COORD_ARRAY:
       case GL_MATRIX_INDEX_ARRAY_OES:
       case GL_WEIGHT_ARRAY_OES:
       {
          GLboolean temp = 0;
          GLuint count = (GLuint) get_boolean_internal_11(thread, cap, &temp);
          UNUSED_NDEBUG(count);
          vcos_assert(count == 1);
          return temp;
       }
       default:
          return RPC_BOOLEAN_RES(RPC_CALL1_RES(glIsEnabled_impl,
                                               thread,
                                               GLISENABLED_ID,
                                               RPC_ENUM(cap)));
       }
    }
    else if (IS_OPENGLES_20(thread)) {
       return RPC_BOOLEAN_RES(RPC_CALL1_RES(glIsEnabled_impl,
                                            thread,
                                            GLISENABLED_ID,
                                            RPC_ENUM(cap)));
    }
    return 0;
 }
glIsFramebuffer()
GL_APICALL GLboolean GL_APIENTRY glIsFramebuffer (GLuint framebuffer)
Definition at line 5269 of file glxx_client.c.
References glxx_client_IsFramebuffer().
 {
    return glxx_client_IsFramebuffer(framebuffer);
 }
glIsProgram()
GL_API GLboolean GL_APIENTRY glIsProgram (GLuint program)
Definition at line 3015 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       return RPC_BOOLEAN_RES(RPC_CALL1_RES(glIsProgram_impl_20,
                                            thread,
                                            GLISPROGRAM_ID_20,
                                            RPC_UINT(program)));
    }
    return 0;
 }
glIsRenderbuffer()
GL_APICALL GLboolean GL_APIENTRY glIsRenderbuffer (GLuint renderbuffer)
Definition at line 5141 of file glxx_client.c.
References glxx_client_IsRenderbuffer().
 {
    return glxx_client_IsRenderbuffer(renderbuffer);
 }
glIsShader()
GL_API GLboolean GL_APIENTRY glIsShader (GLuint shader)
Definition at line 3028 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       return RPC_BOOLEAN_RES(RPC_CALL1_RES(glIsShader_impl_20,
                                            thread,
                                            GLISSHADER_ID_20,
                                            RPC_UINT(shader)));
    }
    return 0;
 }
glIsTexture()
GL_API GLboolean GL_APIENTRY glIsTexture (GLuint texture)
Definition at line 3041 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       return RPC_BOOLEAN_RES(RPC_CALL1_RES(glIsTexture_impl,
                                            thread,
                                            GLISTEXTURE_ID,
                                            RPC_UINT(texture)));
    }
    return 0;
 }
glLightf()
GL_API void GL_APIENTRY glLightf (GLenum light, GLenum pname, GLfloat param)
Definition at line 3121 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL3(glLightf_impl_11,
                 thread,
                 GLLIGHTF_ID_11,
                 RPC_ENUM(light),
                 RPC_ENUM(pname),
                 RPC_FLOAT(param));
    }
 }
glLightfv()
GL_API void GL_APIENTRY glLightfv (GLenum light, GLenum pname, const GLfloat * params)
Definition at line 3134 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       /*
          the only supported light params are
          AMBIENT (4)
          DIFFUSE (4)
          SPECULAR (4)
          POSITION (4)
          SPOT_DIRECTION (3)
          SPOT_EXPONENT (1)
          SPOT_CUTOFF (1)
          CONSTANT_ATTENUATION (1)
          LINEAR_ATTENUATION (1)
          QUADRATIC_ATTENUATION (1)
          so we need to transmit 4 words of parameter data
       */
       RPC_CALL3_IN_CTRL(glLightfv_impl_11,
                         thread,
                         GLLIGHTFV_ID_11,
                         RPC_ENUM(light),
                         RPC_ENUM(pname),
                         params,
                         4 * sizeof(GLfloat));
    }
 }
glLightModelf()
GL_API void GL_APIENTRY glLightModelf (GLenum pname, GLfloat param)
Definition at line 3053 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL2(glLightModelf_impl_11,
                 thread,
                 GLLIGHTMODELF_ID_11,
                 RPC_ENUM(pname),
                 RPC_FLOAT(param));
    }
 }
glLightModelfv()
GL_API void GL_APIENTRY glLightModelfv (GLenum pname, const GLfloat * params)
Definition at line 3065 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       /*
          the only supported lighting model params are
          LIGHT_MODEL_AMBIENT (4)
          LIGHT_MODEL_TWO_SIDE (1)
          so we need to transmit 4 words of parameter data
       */
       RPC_CALL2_IN_CTRL(glLightModelfv_impl_11,
                         thread,
                         GLLIGHTMODELFV_ID_11,
                         RPC_ENUM(pname),
                         params,
                         4 * sizeof(GLfloat));
    }
 }
glLightModelx()
GL_API void GL_APIENTRY glLightModelx (GLenum pname, GLfixed param)
Definition at line 3087 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL2(glLightModelx_impl_11,
                 thread,
                 GLLIGHTMODELX_ID_11,
                 RPC_ENUM(pname),
                 RPC_FIXED(param));
    }
 }
glLightModelxv()
GL_API void GL_APIENTRY glLightModelxv (GLenum pname, const GLfixed * params)
Definition at line 3099 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       /*
          the only supported lighting model params are
          LIGHT_MODEL_AMBIENT (4)
          LIGHT_MODEL_TWO_SIDE (1)
          so we need to transmit 4 words of parameter data
       */
       RPC_CALL2_IN_CTRL(glLightModelxv_impl_11,
                         thread,
                         GLLIGHTMODELXV_ID_11,
                         RPC_ENUM(pname),
                         params,
                         4 * sizeof(GLfixed));
    }
 }
glLightx()
GL_API void GL_APIENTRY glLightx (GLenum light, GLenum pname, GLfixed param)
Definition at line 3165 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL3(glLightx_impl_11,
                 thread,
                 GLLIGHTX_ID_11,
                 RPC_ENUM(light),
                 RPC_ENUM(pname),
                 RPC_FIXED(param));
    }
 }
glLightxv()
GL_API void GL_APIENTRY glLightxv (GLenum light, GLenum pname, const GLfixed * params)
Definition at line 3178 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       /*
          the only supported light params are
          AMBIENT (4)
          DIFFUSE (4)
          SPECULAR (4)
          POSITION (4)
          SPOT_DIRECTION (3)
          SPOT_EXPONENT (1)
          SPOT_CUTOFF (1)
          CONSTANT_ATTENUATION (1)
          LINEAR_ATTENUATION (1)
          QUADRATIC_ATTENUATION (1)
          so we need to transmit 4 words of parameter data
       */
       RPC_CALL3_IN_CTRL(glLightxv_impl_11,
                         thread,
                         GLLIGHTXV_ID_11,
                         RPC_ENUM(light),
                         RPC_ENUM(pname),
                         params,
                         4 * sizeof(GLfixed));
    }
 }
glLineWidth()
GL_API void GL_APIENTRY glLineWidth (GLfloat width)
Definition at line 3209 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL1(glLineWidth_impl,
                 thread,
                 GLLINEWIDTH_ID,
                 RPC_FLOAT(width));
    }
 }
glLineWidthx()
GL_API void GL_APIENTRY glLineWidthx (GLfixed width)
Definition at line 3220 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL1(glLineWidthx_impl_11,
                 thread,
                 GLLINEWIDTHX_ID_11,
                 RPC_FIXED(width));
    }
 }
glLinkProgram()
GL_API void GL_APIENTRY glLinkProgram (GLuint program)
Definition at line 3231 of file glxx_client.c.
Referenced by raspitexutil_build_shader_program().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL1(glLinkProgram_impl_20,
                thread,
                GLLINKPROGRAM_ID_20,
                RPC_UINT(program));
    }
 }
glLoadIdentity()
GL_API void GL_APIENTRY glLoadIdentity (void)
Definition at line 3242 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL0(glLoadIdentity_impl_11,
                 thread,
                 GLLOADIDENTITY_ID_11);
    }
 }
glLoadMatrixf()
GL_API void GL_APIENTRY glLoadMatrixf (const GLfloat * m)
Definition at line 3252 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL1_IN_CTRL(glLoadMatrixf_impl_11,
                        thread,
                        GLLOADMATRIXF_ID_11,
                        m,
                        16 * sizeof(GLfloat));
    }
 }
glLoadMatrixx()
GL_API void GL_APIENTRY glLoadMatrixx (const GLfixed * m)
Definition at line 3264 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL1_IN_CTRL(glLoadMatrixx_impl_11,
                         thread,
                         GLLOADMATRIXX_ID_11,
                         m,
                         16 * sizeof(GLfixed));
    }
 }
glLogicOp()
GL_API void GL_APIENTRY glLogicOp (GLenum opcode)
Definition at line 3276 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL1(glLogicOp_impl_11,
                 thread,
                 GLLOGICOP_ID_11,
                 RPC_ENUM(opcode));
    }
 }
glMaterialf()
GL_API void GL_APIENTRY glMaterialf (GLenum face, GLenum pname, GLfloat param)
Definition at line 3287 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL3(glMaterialf_impl_11,
                 thread,
                 GLMATERIALF_ID_11,
                 RPC_ENUM(face),
                 RPC_ENUM(pname),
                 RPC_FLOAT(param));
    }
 }
glMaterialfv()
GL_API void GL_APIENTRY glMaterialfv (GLenum face, GLenum pname, const GLfloat * params)
Definition at line 3300 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       /*
          the only supported material params are
          AMBIENT (4)
          DIFFUSE (4)
          SPECULAR (4)
          EMISSION (4)
          SHININESS (1)
          so we need to transmit 4 words of parameter data
       */
       RPC_CALL3_IN_CTRL(glMaterialfv_impl_11,
                         thread,
                         GLMATERIALFV_ID_11,
                         RPC_ENUM(face),
                         RPC_ENUM(pname),
                         params,
                         4 * sizeof(GLfloat));
    }
 }
glMaterialx()
GL_API void GL_APIENTRY glMaterialx (GLenum face, GLenum pname, GLfixed param)
Definition at line 3326 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL3(glMaterialx_impl_11,
                 thread,
                 GLMATERIALX_ID_11,
                 RPC_ENUM(face),
                 RPC_ENUM(pname),
                 RPC_FIXED(param));
    }
 }
glMaterialxv()
GL_API void GL_APIENTRY glMaterialxv (GLenum face, GLenum pname, const GLfixed * params)
Definition at line 3339 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       /*
          the only supported material params are
          AMBIENT (4)
          DIFFUSE (4)
          SPECULAR (4)
          EMISSION (4)
          SHININESS (1)
          so we need to transmit 4 words of parameter data
       */
       RPC_CALL3_IN_CTRL(glMaterialxv_impl_11,
                         thread,
                         GLMATERIALXV_ID_11,
                         RPC_ENUM(face),
                         RPC_ENUM(pname),
                         params,
                         4 * sizeof(GLfixed));
    }
 }
glMatrixMode()
GL_API void GL_APIENTRY glMatrixMode (GLenum mode)
Definition at line 3365 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL1(glMatrixMode_impl_11,
                 thread,
                 GLMATRIXMODE_ID_11,
                 RPC_ENUM(mode));
    }
 }
glMultiTexCoord4f()
GL_API void GL_APIENTRY glMultiTexCoord4f (GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q)
Definition at line 3400 of file glxx_client.c.
References GL11_CONFIG_MAX_TEXTURE_UNITS, GL11_IX_TEXTURE_COORD, GL_INVALID_ENUM, GL_TEXTURE0, glintAttrib(), GLXX_API_11, and glxx_set_error_api().
 {
    if (target >= GL_TEXTURE0 && target < GL_TEXTURE0 + GL11_CONFIG_MAX_TEXTURE_UNITS) {
       uint32_t indx = GL11_IX_TEXTURE_COORD + target - GL_TEXTURE0;
       glintAttrib(GLXX_API_11, indx, s, t, r, q);
    } else
       glxx_set_error_api(GLXX_API_11, GL_INVALID_ENUM);
 }
glMultiTexCoord4x()
GL_API void GL_APIENTRY glMultiTexCoord4x (GLenum target, GLfixed s, GLfixed t, GLfixed r, GLfixed q)
Definition at line 3409 of file glxx_client.c.
References GL11_CONFIG_MAX_TEXTURE_UNITS, GL11_IX_TEXTURE_COORD, GL_TEXTURE0, glintAttrib(), and GLXX_API_11.
 {
    if (target >= GL_TEXTURE0 && target < GL_TEXTURE0 + GL11_CONFIG_MAX_TEXTURE_UNITS) {
       uint32_t indx = GL11_IX_TEXTURE_COORD + target - GL_TEXTURE0;
       glintAttrib(GLXX_API_11, indx, fixed_to_float(s), fixed_to_float(t), fixed_to_float(r), fixed_to_float(q));
    } else
       glxx_set_error_api(GLXX_API_11, GL_INVALID_ENUM);
 }
glMultMatrixf()
GL_API void GL_APIENTRY glMultMatrixf (const GLfloat * m)
Definition at line 3376 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL1_IN_CTRL(glMultMatrixf_impl_11,
                         thread,
                         GLMULTMATRIXF_ID_11,
                         m,
                         16 * sizeof(GLfloat));
    }
 }
glMultMatrixx()
GL_API void GL_APIENTRY glMultMatrixx (const GLfixed * m)
Definition at line 3388 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL1_IN_CTRL(glMultMatrixx_impl_11,
                         thread,
                         GLMULTMATRIXX_ID_11,
                         m,
                         16 * sizeof(GLfixed));
    }
 }
glNormal3f()
GL_API void GL_APIENTRY glNormal3f (GLfloat nx, GLfloat ny, GLfloat nz)
Definition at line 3418 of file glxx_client.c.
References GL11_IX_NORMAL, glintAttrib(), and GLXX_API_11.
 {
    glintAttrib(GLXX_API_11, GL11_IX_NORMAL, nx, ny, nz, 0.0f);
 }
glNormal3x()
GL_API void GL_APIENTRY glNormal3x (GLfixed nx, GLfixed ny, GLfixed nz)
Definition at line 3423 of file glxx_client.c.
References GL11_IX_NORMAL, glintAttrib(), and GLXX_API_11.
 {
    glintAttrib(GLXX_API_11, GL11_IX_NORMAL, fixed_to_float(nx), fixed_to_float(ny), fixed_to_float(nz), 0.0f);
 }
glNormalPointer()
GL_API void GL_APIENTRY glNormalPointer (GLenum type, GLsizei stride, const GLvoid * pointer)
Definition at line 3436 of file glxx_client.c.
 {
    if (is_normal_type(type)) {
       if (is_aligned(type, (size_t)pointer) && is_aligned(type, (size_t)stride) && stride >= 0) {
          glintAttribPointer(GLXX_API_11, GL11_IX_NORMAL, 3, type, GL_TRUE, stride, pointer);
       } else
          glxx_set_error_api(GLXX_API_11, GL_INVALID_VALUE);
    } else
       glxx_set_error_api(GLXX_API_11, GL_INVALID_ENUM);
 }
glOrthof()
GL_API void GL_APIENTRY glOrthof (GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar)
Definition at line 3447 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL6(glOrthof_impl_11,
                 thread,
                 GLORTHOF_ID_11,
                 RPC_FLOAT(left),
                 RPC_FLOAT(right),
                 RPC_FLOAT(bottom),
                 RPC_FLOAT(top),
                 RPC_FLOAT(zNear),
                 RPC_FLOAT(zFar));
    }
 }
glOrthox()
GL_API void GL_APIENTRY glOrthox (GLfixed left, GLfixed right, GLfixed bottom, GLfixed top, GLfixed zNear, GLfixed zFar)
Definition at line 3463 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL6(glOrthox_impl_11,
                 thread,
                 GLORTHOX_ID_11,
                 RPC_FIXED(left),
                 RPC_FIXED(right),
                 RPC_FIXED(bottom),
                 RPC_FIXED(top),
                 RPC_FIXED(zNear),
                 RPC_FIXED(zFar));
    }
 }
glPixelStorei()
GL_API void GL_APIENTRY glPixelStorei (GLenum pname, GLint param)
Definition at line 3487 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       if (is_alignment(param)) {
          GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
          vcos_assert(state != NULL);
          switch (pname) {
          case GL_PACK_ALIGNMENT:
             state->alignment.pack = param;
             break;
          case GL_UNPACK_ALIGNMENT:
             state->alignment.unpack = param;
             break;
          }
       }
    }
 }
glPointParameterf()
GL_API void GL_APIENTRY glPointParameterf (GLenum pname, GLfloat param)
Definition at line 3508 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL2(glPointParameterf_impl_11,
                 thread,
                 GLPOINTPARAMETERF_ID_11,
                 RPC_ENUM(pname),
                 RPC_FLOAT(param));
    }
 }
glPointParameterfv()
GL_API void GL_APIENTRY glPointParameterfv (GLenum pname, const GLfloat * params)
Definition at line 3520 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       /*
          the only supported material params are
          POINT_SIZE_MIN (1)
          POINT_SIZE_MAX (1)
          POINT_FADE_THRESHOLD_SIZE (1)
          POINT_DISTANCE_ATTENUATION (3)
          so we need to transmit 3 words of parameter data
       */
       RPC_CALL2_IN_CTRL(glPointParameterfv_impl_11,
                         thread,
                         GLPOINTPARAMETERFV_ID_11,
                         RPC_ENUM(pname),
                         params,
                         3 * sizeof(GLfloat));
    }
 }
glPointParameterx()
GL_API void GL_APIENTRY glPointParameterx (GLenum pname, GLfixed param)
Definition at line 3544 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL2(glPointParameterx_impl_11,
                 thread,
                 GLPOINTPARAMETERX_ID_11,
                 RPC_ENUM(pname),
                 RPC_FIXED(param));
    }
 }
glPointParameterxv()
GL_API void GL_APIENTRY glPointParameterxv (GLenum pname, const GLfixed * params)
Definition at line 3556 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       /*
          the only supported material params are
          POINT_SIZE_MIN (1)
          POINT_SIZE_MAX (1)
          POINT_FADE_THRESHOLD_SIZE (1)
          POINT_DISTANCE_ATTENUATION (3)
          so we need to transmit 3 words of parameter data
       */
       RPC_CALL2_IN_CTRL(glPointParameterxv_impl_11,
                         thread,
                         GLPOINTPARAMETERXV_ID_11,
                         RPC_ENUM(pname),
                         params,
                         3 * sizeof(GLfixed));
    }
 }
glPointSize()
GL_API void GL_APIENTRY glPointSize (GLfloat size)
Definition at line 3580 of file glxx_client.c.
 {
    size = clean_float(size);
    if (size > 0.0f)
       glintAttrib(GLXX_API_11, GL11_IX_POINT_SIZE, size, 0.0f, 0.0f, 0.0f);
    else
       glxx_set_error_api(GLXX_API_11, GL_INVALID_VALUE);
 }
glPointSizePointerOES()
GL_API void GL_APIENTRY glPointSizePointerOES (GLenum type, GLsizei stride, const GLvoid * pointer)
Definition at line 4889 of file glxx_client.c.
 {
    if (is_point_size_type(type)) {
       if (is_aligned(type, (size_t)pointer) && is_aligned(type, (size_t)stride) && stride >= 0) {
          glintAttribPointer(GLXX_API_11, GL11_IX_POINT_SIZE, 1, type, GL_FALSE, stride, pointer);
       } else
          glxx_set_error_api(GLXX_API_11, GL_INVALID_VALUE);
    } else
       glxx_set_error_api(GLXX_API_11, GL_INVALID_ENUM);
 }
glPointSizex()
GL_API void GL_APIENTRY glPointSizex (GLfixed size)
Definition at line 3590 of file glxx_client.c.
References GL11_IX_POINT_SIZE, glintAttrib(), and GLXX_API_11.
 {
    if (size > 0)
       glintAttrib(GLXX_API_11, GL11_IX_POINT_SIZE, fixed_to_float(size), 0.0f, 0.0f, 0.0f);
    else
       glxx_set_error_api(GLXX_API_11, GL_INVALID_VALUE);
 }
glPolygonOffset()
GL_API void GL_APIENTRY glPolygonOffset (GLfloat factor, GLfloat units)
Definition at line 3598 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL2(glPolygonOffset_impl,
                 thread,
                 GLPOLYGONOFFSET_ID,
                 RPC_FLOAT(factor),
                 RPC_FLOAT(units));
    }
 }
glPolygonOffsetx()
GL_API void GL_APIENTRY glPolygonOffsetx (GLfixed factor, GLfixed units)
Definition at line 3610 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL2(glPolygonOffsetx_impl_11,
                 thread,
                 GLPOLYGONOFFSETX_ID_11,
                 RPC_FIXED(factor),
                 RPC_FIXED(units));
    }
 }
glPopMatrix()
GL_API void GL_APIENTRY glPopMatrix (void)
Definition at line 3622 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL0(glPopMatrix_impl_11,
                 thread,
                 GLPOPMATRIX_ID_11);
    }
 }
glPushMatrix()
GL_API void GL_APIENTRY glPushMatrix (void)
Definition at line 3632 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL0(glPushMatrix_impl_11,
                 thread,
                 GLPUSHMATRIX_ID_11);
    }
 }
glReadPixels()
GL_API void GL_APIENTRY glReadPixels (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid * pixels)
Definition at line 3763 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       uint32_t pitch = get_pitch( (uint32_t)width, format, type, (uint32_t) state->alignment.pack);
       uint32_t lines = pitch ? (uint32_t) (KHDISPATCH_WORKSPACE_SIZE / pitch) : (uint32_t)height;
       if (pixels && lines) {
          int offset = 0;
          while (height > 0) {
             int32_t batch = _min(lines, (int32_t) height);
             RPC_CALL8_OUT_BULK(glReadPixels_impl,
                                thread,
                                GLREADPIXELS_ID,
                                RPC_INT(x),
                                RPC_INT(y + offset),
                                RPC_SIZEI(width),
                                RPC_SIZEI(batch),
                                RPC_ENUM(format),
                                RPC_ENUM(type),
                                RPC_INT(state->alignment.pack),
                                (char *)pixels + offset * pitch);
             offset += batch;
             height -= batch;
          }
       }
       // We do not call flush_callback as the spec does not imply a full flush
       // at this point (I think).
    }
 }
glReleaseShaderCompiler()
GL_APICALL void GL_APIENTRY glReleaseShaderCompiler (void)
Definition at line 4981 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
    }
 }
glRenderbufferStorage()
GL_APICALL void GL_APIENTRY glRenderbufferStorage (GLenum target, GLenum internalformat, GLsizei width, GLsizei height)
Definition at line 5233 of file glxx_client.c.
References glxx_client_RenderbufferStorage().
 {
    glxx_client_RenderbufferStorage(target, internalformat, width, height);
 }
glRotatef()
GL_API void GL_APIENTRY glRotatef (GLfloat angle, GLfloat x, GLfloat y, GLfloat z)
Definition at line 3800 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL4(glRotatef_impl_11,
                 thread,
                 GLROTATEF_ID_11,
                 RPC_FLOAT(angle),
                 RPC_FLOAT(x),
                 RPC_FLOAT(y),
                 RPC_FLOAT(z));
    }
 }
glRotatex()
GL_API void GL_APIENTRY glRotatex (GLfixed angle, GLfixed x, GLfixed y, GLfixed z)
Definition at line 3814 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL4(glRotatex_impl_11,
                 thread,
                 GLROTATEX_ID_11,
                 RPC_FIXED(angle),
                 RPC_FIXED(x),
                 RPC_FIXED(y),
                 RPC_FIXED(z));
    }
 }
glSampleCoverage()
GL_API void GL_APIENTRY glSampleCoverage (GLclampf value, GLboolean invert)
Definition at line 3828 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL2(glSampleCoverage_impl,
                 thread,
                 GLSAMPLECOVERAGE_ID,
                 RPC_FLOAT(value),
                 RPC_BOOLEAN(invert));
    }
 }
glSampleCoveragex()
GL_API void GL_APIENTRY glSampleCoveragex (GLclampx value, GLboolean invert)
Definition at line 3840 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL2(glSampleCoveragex_impl_11,
                 thread,
                 GLSAMPLECOVERAGEX_ID_11,
                 RPC_FIXED(value),
                 RPC_BOOLEAN(invert));
    }
 }
glScalef()
GL_API void GL_APIENTRY glScalef (GLfloat x, GLfloat y, GLfloat z)
Definition at line 3852 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL3(glScalef_impl_11,
                 thread,
                 GLSCALEF_ID_11,
                 RPC_FLOAT(x),
                 RPC_FLOAT(y),
                 RPC_FLOAT(z));
    }
 }
glScalex()
GL_API void GL_APIENTRY glScalex (GLfixed x, GLfixed y, GLfixed z)
Definition at line 3865 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL3(glScalex_impl_11,
                 thread,
                 GLSCALEX_ID_11,
                 RPC_FIXED(x),
                 RPC_FIXED(y),
                 RPC_FIXED(z));
    }
 }
glScissor()
GL_API void GL_APIENTRY glScissor (GLint x, GLint y, GLsizei width, GLsizei height)
Definition at line 3878 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL4(glScissor_impl,
                 thread,
                 GLSCISSOR_ID,
                 RPC_INT(x),
                 RPC_INT(y),
                 RPC_SIZEI(width),
                 RPC_SIZEI(height));
    }
 }
glShadeModel()
GL_API void GL_APIENTRY glShadeModel (GLenum mode)
Definition at line 3892 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL1(glShadeModel_impl_11,
                 thread,
                 GLSHADEMODEL_ID_11,
                 RPC_ENUM(mode));
    }
 }
glShaderBinary()
GL_APICALL void GL_APIENTRY glShaderBinary (GLint n, const GLuint * shaders, GLenum binaryformat, const void * binary, GLint length)
Definition at line 4988 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    UNUSED(n);
    UNUSED(shaders);
    UNUSED(binaryformat);
    UNUSED(binary);
    UNUSED(length);
    if (IS_OPENGLES_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       set_error(state, GL_INVALID_ENUM);
    }
 }
glShaderSource()
GL_APICALL void GL_APIENTRY glShaderSource (GLuint shader, GLsizei count, const char ** string, const GLint * length)
Definition at line 5003 of file glxx_client.c.
Referenced by raspitexutil_build_shader_program().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
 #ifdef RPC_DIRECT
       RPC_CALL4(glShaderSource_impl_20, thread, no_id, shader,
                              count,
                              string,
                              length);
 #else
       /*
          calculate total workspace required for string, length and source
       */
 #ifdef __SYMBIAN32__
       int total = (int)(rpc_pad_bulk(count * 4) + rpc_pad_bulk(count * 4));
       int i;
       for (i = 0; i < count; i++) {
          if (!length || length[i] < 0)
             total += rpc_pad_bulk(string[i] ? (int)strlen(string[i]) + 1 : 1);
          else
             total += rpc_pad_bulk(length[i]);
       }
       rpc_begin(thread);
       // Assume worst-case (need to compute and send all lengths) - include
       // the 5 words we're sending in the RPC_CALL4() (do we need to do this?)
       //
       rpc_send_ctrl_begin(thread, (count + 5) * sizeof(GLint) );
       RPC_CALL4(no_function,
                 thread,
                 GLSHADERSOURCE_ID_20,
                 RPC_UINT(shader),
                 RPC_SIZEI(count),
                 RPC_INT(total),
                 RPC_BOOLEAN(length ? 1 : 0));
       if (length)
          rpc_send_bulk(thread, length, count * sizeof(GLint));
 //Send all lengths before the first bulk transfer of a line of source code
 //NB this is a temporary fix until issues, with our bulk transfers and the
 //rpc assumptions, have been resolved
 //NB assumes that the line count numbers all fit in the merge buffer
 //which is why a more permanent fix is needed
       for (i = 0; i < count; i++) {
          GLint len;
          if (!length || length[i] < 0) {
             len = string[i] ? (GLint) strlen(string[i]) + 1 : 1;
 //            rpc_send_bulk(&len, sizeof(GLint)); /* todo: this now violates the semantics of rpc_send_bulk. todo: check for other violations in GL */
             rpc_send_ctrl_write(thread, (uint32_t *)&len, sizeof(GLint));
          }
       }
       rpc_send_ctrl_end(thread);  //no more ctrl data to send
       for (i = 0; i < count; i++) {
          GLint len;
          if (!length || length[i] < 0) {
             len = string[i] ? strlen(string[i]) + 1 : 1;
          } else
             len = length[i];
          /* TODO: we currently treat null strings as empty strings
           * But we shouldn't need to deal with them (VND-116)
           */
          rpc_send_bulk(thread, string[i] ? string[i] : "", (uint32_t)len);
       }
       rpc_end(thread);
 #else
       CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
       int total = (int)(rpc_pad_bulk(count * 4) + rpc_pad_bulk(count * 4) + rpc_pad_bulk(sizeof(GLint)));
       int i;
       for (i = 0; i < count; i++)
          if (!length || length[i] < 0)
             total += rpc_pad_bulk(string[i] ? (int)strlen(string[i]) + 1 : 1);
          else
             total += rpc_pad_bulk(length[i]);
       rpc_begin(thread);
       RPC_CALL4(no_function,
                 thread,
                 GLSHADERSOURCE_ID_20,
                 RPC_UINT(shader),
                 RPC_SIZEI(count),
                 RPC_INT(total),
                 RPC_BOOLEAN(length ? 1 : 0));
       if (length)
          rpc_send_bulk(thread, length, count * sizeof(GLint));
       for (i = 0; i < count; i++) {
          GLint len;
          if (!length || length[i] < 0) {
             len = string[i] ? (GLint) strlen(string[i]) + 1 : 1;
             rpc_send_bulk(thread, &len, sizeof(GLint)); /* todo: this now violates the semantics of rpc_send_bulk. todo: check for other violations in GL */
          } else
             len = length[i];
          /* TODO: we currently treat null strings as empty strings
           * But we shouldn't need to deal with them (VND-116)
           */
          rpc_send_bulk(thread, string[i] ? string[i] : "", (uint32_t)len);
       }
       rpc_end(thread);
 #endif
 #endif
    }
 }
glStencilFunc()
GL_API void GL_APIENTRY glStencilFunc (GLenum func, GLint ref, GLuint mask)
Definition at line 3913 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) set_stencil_func(thread, GL_FRONT_AND_BACK, func, ref, mask);
 }
glStencilFuncSeparate()
GL_API void GL_APIENTRY glStencilFuncSeparate (GLenum face, GLenum func, GLint ref, GLuint mask)
Definition at line 3919 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) set_stencil_func(thread, face, func, ref, mask);
 }
glStencilMask()
GL_API void GL_APIENTRY glStencilMask (GLuint mask)
Definition at line 3933 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) set_stencil_mask(thread, GL_FRONT_AND_BACK, mask);
 }
glStencilMaskSeparate()
GL_API void GL_APIENTRY glStencilMaskSeparate (GLenum face, GLuint mask)
Definition at line 3939 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) set_stencil_mask(thread, face, mask);
 }
glStencilOp()
GL_API void GL_APIENTRY glStencilOp (GLenum fail, GLenum zfail, GLenum zpass)
Definition at line 3955 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) set_stencil_op(thread, GL_FRONT_AND_BACK, fail, zfail, zpass);
 }
glStencilOpSeparate()
GL_API void GL_APIENTRY glStencilOpSeparate (GLenum face, GLenum fail, GLenum zfail, GLenum zpass)
Definition at line 3961 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) set_stencil_op(thread, face, fail, zfail, zpass);
 }
glTexCoordPointer()
GL_API void GL_APIENTRY glTexCoordPointer (GLint size, GLenum type, GLsizei stride, const GLvoid * pointer)
Definition at line 3982 of file glxx_client.c.
 {
    if (is_texture_coord_type(type)) {
       if (is_texture_coord_size(size) && is_aligned(type, (size_t)pointer) && is_aligned(type, (size_t)stride) && stride >= 0) {
          glintAttribPointer(GLXX_API_11, GL11_IX_CLIENT_ACTIVE_TEXTURE, size, type, GL_FALSE, stride, pointer);
       } else
          glxx_set_error_api(GLXX_API_11, GL_INVALID_VALUE);
    } else
       glxx_set_error_api(GLXX_API_11, GL_INVALID_ENUM);
 }
glTexEnvf()
GL_API void GL_APIENTRY glTexEnvf (GLenum target, GLenum pname, GLfloat param)
Definition at line 4046 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL3(glTexEnvf_impl_11,
                 thread,
                 GLTEXENVF_ID_11,
                 RPC_ENUM(target),
                 RPC_ENUM(pname),
                 RPC_FLOAT(param));
    }
 }
glTexEnvfv()
GL_API void GL_APIENTRY glTexEnvfv (GLenum target, GLenum pname, const GLfloat * params)
Definition at line 4059 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       /*
          the only supported texture environment params are
          COORD_REPLACE_OES (1)
          TEXTURE_ENV_MODE (1)
          TEXTURE_ENV_COLOR (4)
          COMBINE_RGB (1)
          RGB_SCALE (1)
          SRC0_RGB (1)
          SRC1_RGB (1)
          SRC2_RGB (1)
          OPERAND0_RGB (1)
          OPERAND1_RGB (1)
          OPERAND2_RGB (1)
          COMBINE_ALPHA (1)
          ALPHA_SCALE (1)
          SRC0_ALPHA (1)
          SRC1_ALPHA (1)
          SRC2_ALPHA (1)
          OPERAND0_ALPHA (1)
          OPERAND1_ALPHA (1)
          OPERAND2_ALPHA (1)
          so we need to transmit 4 words of parameter data
       */
       RPC_CALL3_IN_CTRL(glTexEnvfv_impl_11,
                         thread,
                         GLTEXENVFV_ID_11,
                         RPC_ENUM(target),
                         RPC_ENUM(pname),
                         params,
                         4 * sizeof(GLfloat));
    }
 }
glTexEnvi()
GL_API void GL_APIENTRY glTexEnvi (GLenum target, GLenum pname, GLint param)
Definition at line 3993 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL3(glTexEnvi_impl_11,
                 thread,
                 GLTEXENVI_ID_11,
                 RPC_ENUM(target),
                 RPC_ENUM(pname),
                 RPC_INT(param));
    }
 }
glTexEnviv()
GL_API void GL_APIENTRY glTexEnviv (GLenum target, GLenum pname, const GLint * params)
Definition at line 4006 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       /*
          the only supported texture environment params are
          COORD_REPLACE_OES (1)
          TEXTURE_ENV_MODE (1)
          TEXTURE_ENV_COLOR (4)
          COMBINE_RGB (1)
          RGB_SCALE (1)
          SRC0_RGB (1)
          SRC1_RGB (1)
          SRC2_RGB (1)
          OPERAND0_RGB (1)
          OPERAND1_RGB (1)
          OPERAND2_RGB (1)
          COMBINE_ALPHA (1)
          ALPHA_SCALE (1)
          SRC0_ALPHA (1)
          SRC1_ALPHA (1)
          SRC2_ALPHA (1)
          OPERAND0_ALPHA (1)
          OPERAND1_ALPHA (1)
          OPERAND2_ALPHA (1)
          so we need to transmit 4 words of parameter data
       */
       RPC_CALL3_IN_CTRL(glTexEnviv_impl_11,
                         thread,
                         GLTEXENVIV_ID_11,
                         RPC_ENUM(target),
                         RPC_ENUM(pname),
                         params,
                         4 * sizeof(GLint));
    }
 }
glTexEnvx()
GL_API void GL_APIENTRY glTexEnvx (GLenum target, GLenum pname, GLfixed param)
Definition at line 4099 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL3(glTexEnvx_impl_11,
                 thread,
                 GLTEXENVX_ID_11,
                 RPC_ENUM(target),
                 RPC_ENUM(pname),
                 RPC_FIXED(param));
    }
 }
glTexEnvxv()
GL_API void GL_APIENTRY glTexEnvxv (GLenum target, GLenum pname, const GLfixed * params)
Definition at line 4112 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       /*
          the only supported texture environment params are
          COORD_REPLACE_OES (1)
          TEXTURE_ENV_MODE (1)
          TEXTURE_ENV_COLOR (4)
          COMBINE_RGB (1)
          RGB_SCALE (1)
          SRC0_RGB (1)
          SRC1_RGB (1)
          SRC2_RGB (1)
          OPERAND0_RGB (1)
          OPERAND1_RGB (1)
          OPERAND2_RGB (1)
          COMBINE_ALPHA (1)
          ALPHA_SCALE (1)
          SRC0_ALPHA (1)
          SRC1_ALPHA (1)
          SRC2_ALPHA (1)
          OPERAND0_ALPHA (1)
          OPERAND1_ALPHA (1)
          OPERAND2_ALPHA (1)
          so we need to transmit 4 words of parameter data
       */
       RPC_CALL3_IN_CTRL(glTexEnvxv_impl_11,
                         thread,
                         GLTEXENVXV_ID_11,
                         RPC_ENUM(target),
                         RPC_ENUM(pname),
                         params,
                         4 * sizeof(GLfixed));
    }
 }
glTexImage2D()
GL_API void GL_APIENTRY glTexImage2D (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid * pixels)
Definition at line 4152 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    GLboolean res;
    if (IS_OPENGLES_11_OR_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       uint32_t pitch = get_pitch( (uint32_t)width, format, type, (uint32_t)state->alignment.unpack);
       uint32_t lines = pitch ? (uint32_t)(KHDISPATCH_WORKSPACE_SIZE / pitch) : (uint32_t)height;
       res = RPC_BOOLEAN_RES(RPC_CALL10_IN_BULK_RES(glTexImage2D_impl,
                         thread,
                         GLTEXIMAGE2D_ID,
                         RPC_ENUM(target),
                         RPC_INT(level),
                         RPC_ENUM(internalformat),
                         RPC_SIZEI(width),
                         RPC_SIZEI(height),
                         RPC_INT(border),
                         RPC_ENUM(format),
                         RPC_ENUM(type),
                         RPC_INT(state->alignment.unpack),
                         NULL,
                         0));
       if (res && pixels && lines) {
          int offset = 0;
          while (height > 0) {
             int32_t batch = _min(lines, (int32_t)height);
             RPC_CALL10_IN_BULK(glTexSubImage2D_impl,
                               thread,
                               GLTEXSUBIMAGE2D_ID,
                               RPC_ENUM(target),
                               RPC_INT(level),
                               RPC_INT(0),
                               RPC_INT(offset),
                               RPC_SIZEI(width),
                               RPC_SIZEI(batch),
                               RPC_ENUM(format),
                               RPC_ENUM(type),
                               RPC_INT(state->alignment.unpack),
                               (char *)pixels + offset * pitch,
                               batch * pitch);
             offset += batch;
             height -= batch;
          }
       }
    }
 }
glTexImage3DOES()
GL_API void GL_APIENTRY glTexImage3DOES (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid * pixels)
Definition at line 5729 of file glxx_client.c.
References UNUSED.
 { UNUSED(target); UNUSED(level); UNUSED(internalformat); UNUSED(width); UNUSED(height); UNUSED(depth); UNUSED(border); UNUSED(format); UNUSED(type); UNUSED(pixels); }
glTexParameterf()
GL_API void GL_APIENTRY glTexParameterf (GLenum target, GLenum pname, GLfloat param)
Definition at line 4218 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL3(glTexParameterf_impl,
                 thread,
                 GLTEXPARAMETERF_ID,
                 RPC_ENUM(target),
                 RPC_ENUM(pname),
                 RPC_FLOAT(param));
    }
 }
glTexParameterfv()
GL_API void GL_APIENTRY glTexParameterfv (GLenum target, GLenum pname, const GLfloat * params)
Definition at line 4280 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    /*
       the only supported texture params are
       TEXTURE_MIN_FILTER
       TEXTURE_MAG_FILTER
       TEXTURE_WRAP_S
       TEXTURE_WRAP_T
       each of which takes a single argument
       and for 1.1
       TEXTURE_CROP_RECT_OES
       which takes 4 ints
    */
    if (IS_OPENGLES_11(thread)) {
       if(pname != GL_TEXTURE_CROP_RECT_OES) {
          glTexParameterf(target, pname, params[0]);
       }
       else {
          RPC_CALL3_IN_CTRL(glTexParameterfv_impl,
                 thread,
                 GLTEXPARAMETERFV_ID,
                 RPC_ENUM(target),
                 RPC_ENUM(pname),
                 params,
                 4 * sizeof(GLfloat));
       }
    }
    else if(IS_OPENGLES_20(thread))
       glTexParameterf(target, pname, params[0]);
 }
glTexParameteri()
GL_API void GL_APIENTRY glTexParameteri (GLenum target, GLenum pname, GLint param)
Definition at line 4205 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL3(glTexParameteri_impl,
                 thread,
                 GLTEXPARAMETERI_ID,
                 RPC_ENUM(target),
                 RPC_ENUM(pname),
                 RPC_INT(param));
    }
 }
glTexParameteriv()
GL_API void GL_APIENTRY glTexParameteriv (GLenum target, GLenum pname, const GLint * params)
Definition at line 4244 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    /*
       the only supported texture params are
       TEXTURE_MIN_FILTER
       TEXTURE_MAG_FILTER
       TEXTURE_WRAP_S
       TEXTURE_WRAP_T
       each of which takes a single argument
       and for 1.1
       TEXTURE_CROP_RECT_OES
       which takes 4 ints
    */
    if (IS_OPENGLES_11(thread)) {
       if(pname != GL_TEXTURE_CROP_RECT_OES) {
          glTexParameteri(target, pname, params[0]);
       }
       else {
          RPC_CALL3_IN_CTRL(glTexParameteriv_impl,
                 thread,
                 GLTEXPARAMETERIV_ID,
                 RPC_ENUM(target),
                 RPC_ENUM(pname),
                 params,
                 4 * sizeof(GLint));
       }
    }
    else if(IS_OPENGLES_20(thread))
       glTexParameteri(target, pname, params[0]);
 }
glTexParameterx()
GL_API void GL_APIENTRY glTexParameterx (GLenum target, GLenum pname, GLfixed param)
Definition at line 4231 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL3(glTexParameterx_impl_11,
                 thread,
                 GLTEXPARAMETERX_ID_11,
                 RPC_ENUM(target),
                 RPC_ENUM(pname),
                 RPC_FIXED(param));
    }
 }
glTexParameterxv()
GL_API void GL_APIENTRY glTexParameterxv (GLenum target, GLenum pname, const GLfixed * params)
Definition at line 4316 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    /*
       the only supported texture params are
       TEXTURE_MIN_FILTER
       TEXTURE_MAG_FILTER
       TEXTURE_WRAP_S
       TEXTURE_WRAP_T
       each of which takes a single argument
       and for 1.1
       TEXTURE_CROP_RECT_OES
       which takes 4 ints
    */
    if (IS_OPENGLES_11(thread)) {
       if(pname != GL_TEXTURE_CROP_RECT_OES) {
          glTexParameterx(target, pname, params[0]);
       }
       else {
          RPC_CALL3_IN_CTRL(glTexParameterxv_impl_11,
                 thread,
                 GLTEXPARAMETERXV_ID_11,
                 RPC_ENUM(target),
                 RPC_ENUM(pname),
                 params,
                 4 * sizeof(GLfixed));
       }
    }
    else if(IS_OPENGLES_20(thread))
       glTexParameterx(target, pname, params[0]);
 }
glTexSubImage2D()
GL_API void GL_APIENTRY glTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * pixels)
Definition at line 4352 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       uint32_t pitch = get_pitch( (uint32_t)width, format, type, (uint32_t)state->alignment.unpack);
       uint32_t lines = pitch ? (uint32_t)(KHDISPATCH_WORKSPACE_SIZE / pitch) : (uint32_t)height;
       if (pixels && lines) {
          int offset = 0;
          while (height > 0) {
             int32_t batch = _min(lines, (int32_t)height);
             RPC_CALL10_IN_BULK(glTexSubImage2D_impl,
                               thread,
                               GLTEXSUBIMAGE2D_ID,
                               RPC_ENUM(target),
                               RPC_INT(level),
                               RPC_INT(xoffset),
                               RPC_INT(yoffset+offset),
                               RPC_SIZEI(width),
                               RPC_SIZEI(batch),
                               RPC_ENUM(format),
                               RPC_ENUM(type),
                               RPC_INT(state->alignment.unpack),
                               (char *)pixels + offset * pitch,
                               batch * pitch);
             offset += batch;
             height -= batch;
          }
       }
    }
 }
glTexSubImage3DOES()
GL_API void GL_APIENTRY glTexSubImage3DOES (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid * pixels)
Definition at line 5730 of file glxx_client.c.
References UNUSED.
 { UNUSED(target); UNUSED(level); UNUSED(xoffset); UNUSED(yoffset); UNUSED(zoffset); UNUSED(width); UNUSED(height); UNUSED(depth); UNUSED(format); UNUSED(type); UNUSED(pixels); }
glTranslatef()
GL_API void GL_APIENTRY glTranslatef (GLfloat x, GLfloat y, GLfloat z)
Definition at line 4411 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL3(glTranslatef_impl_11,
                 thread,
                 GLTRANSLATEF_ID_11,
                 RPC_FLOAT(x),
                 RPC_FLOAT(y),
                 RPC_FLOAT(z));
    }
 }
glTranslatex()
GL_API void GL_APIENTRY glTranslatex (GLfixed x, GLfixed y, GLfixed z)
Definition at line 4424 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL3(glTranslatex_impl_11,
                 thread,
                 GLTRANSLATEX_ID_11,
                 RPC_FIXED(x),
                 RPC_FIXED(y),
                 RPC_FIXED(z));
    }
 }
glUniform1f()
GL_API void GL_APIENTRY glUniform1f (GLint location, GLfloat x)
Definition at line 4491 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL2(glUniform1f_impl_20,
                 thread,
                 GLUNIFORM1F_ID_20,
                 RPC_INT(location),
                 RPC_FLOAT(x));
    }
 }
glUniform1fv()
GL_API void GL_APIENTRY glUniform1fv (GLint location, GLsizei count, const GLfloat * v)
Definition at line 4624 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       int size = clamp_uniform_size( (int)(count * 1 * sizeof(GLfloat)));
       RPC_CALL4_IN_CTRL(glUniform1fv_impl_20,
                         thread,
                         GLUNIFORM1FV_ID_20,
                         RPC_INT(location),
                         RPC_SIZEI(count),
                         RPC_INT(size),
                         v,
                         (size_t)size);
    }
 }
glUniform1i()
GL_API void GL_APIENTRY glUniform1i (GLint location, GLint x)
Definition at line 4437 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL2(glUniform1i_impl_20,
                 thread,
                 GLUNIFORM1I_ID_20,
                 RPC_INT(location),
                 RPC_INT(x));
    }
 }
glUniform1iv()
GL_API void GL_APIENTRY glUniform1iv (GLint location, GLsizei count, const GLint * v)
Definition at line 4556 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       int size = clamp_uniform_size( (int)(count * 1 * sizeof(GLint)));
       RPC_CALL4_IN_CTRL(glUniform1iv_impl_20,
                         thread,
                         GLUNIFORM1IV_ID_20,
                         RPC_INT(location),
                         RPC_SIZEI(count),
                         RPC_INT(size),
                         v,
                         (size_t)size);
    }
 }
glUniform2f()
GL_API void GL_APIENTRY glUniform2f (GLint location, GLfloat x, GLfloat y)
Definition at line 4503 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL3(glUniform2f_impl_20,
                 thread,
                 GLUNIFORM2F_ID_20,
                 RPC_INT(location),
                 RPC_FLOAT(x),
                 RPC_FLOAT(y));
    }
 }
glUniform2fv()
GL_API void GL_APIENTRY glUniform2fv (GLint location, GLsizei count, const GLfloat * v)
Definition at line 4641 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       int size = clamp_uniform_size( (int)(count * 2 * sizeof(GLfloat)));
       RPC_CALL4_IN_CTRL(glUniform2fv_impl_20,
                         thread,
                         GLUNIFORM2FV_ID_20,
                         RPC_INT(location),
                         RPC_SIZEI(count),
                         RPC_INT(size),
                         v,
                         (size_t)size);
    }
 }
glUniform2i()
GL_API void GL_APIENTRY glUniform2i (GLint location, GLint x, GLint y)
Definition at line 4449 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL3(glUniform2i_impl_20,
                 thread,
                 GLUNIFORM2I_ID_20,
                 RPC_INT(location),
                 RPC_INT(x),
                 RPC_INT(y));
    }
 }
glUniform2iv()
GL_API void GL_APIENTRY glUniform2iv (GLint location, GLsizei count, const GLint * v)
Definition at line 4573 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       int size = clamp_uniform_size( (int)(count * 2 * sizeof(GLint)));
       RPC_CALL4_IN_CTRL(glUniform2iv_impl_20,
                         thread,
                         GLUNIFORM2IV_ID_20,
                         RPC_INT(location),
                         RPC_SIZEI(count),
                         RPC_INT(size),
                         v,
                         (size_t)size);
    }
 }
glUniform3f()
GL_API void GL_APIENTRY glUniform3f (GLint location, GLfloat x, GLfloat y, GLfloat z)
Definition at line 4516 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL4(glUniform3f_impl_20,
                 thread,
                 GLUNIFORM3F_ID_20,
                 RPC_INT(location),
                 RPC_FLOAT(x),
                 RPC_FLOAT(y),
                 RPC_FLOAT(z));
    }
 }
glUniform3fv()
GL_API void GL_APIENTRY glUniform3fv (GLint location, GLsizei count, const GLfloat * v)
Definition at line 4658 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       int size = clamp_uniform_size( (int)(count * 3 * sizeof(GLfloat)));
       RPC_CALL4_IN_CTRL(glUniform3fv_impl_20,
                         thread,
                         GLUNIFORM3FV_ID_20,
                         RPC_INT(location),
                         RPC_SIZEI(count),
                         RPC_INT(size),
                         v,
                         (size_t)size);
    }
 }
glUniform3i()
GL_API void GL_APIENTRY glUniform3i (GLint location, GLint x, GLint y, GLint z)
Definition at line 4462 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL4(glUniform3i_impl_20,
                 thread,
                 GLUNIFORM3I_ID_20,
                 RPC_INT(location),
                 RPC_INT(x),
                 RPC_INT(y),
                 RPC_INT(z));
    }
 }
glUniform3iv()
GL_API void GL_APIENTRY glUniform3iv (GLint location, GLsizei count, const GLint * v)
Definition at line 4590 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       int size = clamp_uniform_size( (int)(count * 3 * sizeof(GLint)));
       RPC_CALL4_IN_CTRL(glUniform3iv_impl_20,
                         thread,
                         GLUNIFORM3IV_ID_20,
                         RPC_INT(location),
                         RPC_SIZEI(count),
                         RPC_INT(size),
                         v,
                         (size_t)size);
    }
 }
glUniform4f()
GL_API void GL_APIENTRY glUniform4f (GLint location, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
Definition at line 4530 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL5(glUniform4f_impl_20,
                 thread,
                 GLUNIFORM4F_ID_20,
                 RPC_INT(location),
                 RPC_FLOAT(x),
                 RPC_FLOAT(y),
                 RPC_FLOAT(z),
                 RPC_FLOAT(w));
    }
 }
glUniform4fv()
GL_API void GL_APIENTRY glUniform4fv (GLint location, GLsizei count, const GLfloat * v)
Definition at line 4675 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       int size = clamp_uniform_size( (int)(count * 4 * sizeof(GLfloat)));
       RPC_CALL4_IN_CTRL(glUniform4fv_impl_20,
                         thread,
                         GLUNIFORM4FV_ID_20,
                         RPC_INT(location),
                         RPC_SIZEI(count),
                         RPC_INT(size),
                         v,
                         (size_t)size);
    }
 }
glUniform4i()
GL_API void GL_APIENTRY glUniform4i (GLint location, GLint x, GLint y, GLint z, GLint w)
Definition at line 4476 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL5(glUniform4i_impl_20,
                 thread,
                 GLUNIFORM4I_ID_20,
                 RPC_INT(location),
                 RPC_INT(x),
                 RPC_INT(y),
                 RPC_INT(z),
                 RPC_INT(w));
    }
 }
glUniform4iv()
GL_API void GL_APIENTRY glUniform4iv (GLint location, GLsizei count, const GLint * v)
Definition at line 4607 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       int size = clamp_uniform_size( (int)(count * 4 * sizeof(GLint)));
       RPC_CALL4_IN_CTRL(glUniform4iv_impl_20,
                         thread,
                         GLUNIFORM4IV_ID_20,
                         RPC_INT(location),
                         RPC_SIZEI(count),
                         RPC_INT(size),
                         v,
                         (size_t)size);
    }
 }
glUniformMatrix2fv()
GL_API void GL_APIENTRY glUniformMatrix2fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat * value)
Definition at line 4697 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       int size = clamp_uniform_size( (int)(count * 2 * 2 * sizeof(GLfloat)));
       RPC_CALL5_IN_CTRL(glUniformMatrix2fv_impl_20,
                         thread,
                         GLUNIFORMMATRIX2FV_ID_20,
                         RPC_INT(location),
                         RPC_SIZEI(count),
                         RPC_BOOLEAN(transpose),
                         RPC_INT(size),
                         value,
                         (size_t)size);
    }
 }
glUniformMatrix3fv()
GL_API void GL_APIENTRY glUniformMatrix3fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat * value)
Definition at line 4715 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       int size = clamp_uniform_size( (int)(count * 3 * 3 * sizeof(GLfloat)));
       RPC_CALL5_IN_CTRL(glUniformMatrix3fv_impl_20,
                         thread,
                         GLUNIFORMMATRIX3FV_ID_20,
                         RPC_INT(location),
                         RPC_SIZEI(count),
                         RPC_BOOLEAN(transpose),
                         RPC_INT(size),
                         value,
                         (size_t)size);
    }
 }
glUniformMatrix4fv()
GL_API void GL_APIENTRY glUniformMatrix4fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat * value)
Definition at line 4733 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       int size = clamp_uniform_size( (int)(count * 4 * 4 * sizeof(GLfloat)));
       RPC_CALL5_IN_CTRL(glUniformMatrix4fv_impl_20,
                         thread,
                         GLUNIFORMMATRIX4FV_ID_20,
                         RPC_INT(location),
                         RPC_SIZEI(count),
                         RPC_BOOLEAN(transpose),
                         RPC_INT(size),
                         value,
                         (size_t)size);
    }
 }
glUseProgram()
GL_API void GL_APIENTRY glUseProgram (GLuint program)
Definition at line 4751 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL1(glUseProgram_impl_20,
                 thread,
                 GLUSEPROGRAM_ID_20,
                 RPC_UINT(program));
    }
 }
glValidateProgram()
GL_API void GL_APIENTRY glValidateProgram (GLuint program)
Definition at line 4762 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_20(thread)) {
       RPC_CALL1(glValidateProgram_impl_20,
                 thread,
                 GLVALIDATEPROGRAM_ID_20,
                 RPC_UINT(program));
    }
 }
glVertexAttrib1f()
GL_APICALL void GL_APIENTRY glVertexAttrib1f (GLuint indx, GLfloat x)
Definition at line 4773 of file glxx_client.c.
References glintAttrib(), and GLXX_API_20.
 {
    glintAttrib(GLXX_API_20, indx, x, 0.0f, 0.0f, 1.0f);
 }
glVertexAttrib1fv()
GL_APICALL void GL_APIENTRY glVertexAttrib1fv (GLuint indx, const GLfloat * values)
Definition at line 4793 of file glxx_client.c.
References glintAttrib(), and GLXX_API_20.
 {
    glintAttrib(GLXX_API_20, indx, values[0], 0.0f, 0.0f, 1.0f);
 }
glVertexAttrib2f()
GL_APICALL void GL_APIENTRY glVertexAttrib2f (GLuint indx, GLfloat x, GLfloat y)
Definition at line 4778 of file glxx_client.c.
References glintAttrib(), and GLXX_API_20.
 {
    glintAttrib(GLXX_API_20, indx, x, y, 0.0f, 1.0f);
 }
glVertexAttrib2fv()
GL_APICALL void GL_APIENTRY glVertexAttrib2fv (GLuint indx, const GLfloat * values)
Definition at line 4798 of file glxx_client.c.
References glintAttrib(), and GLXX_API_20.
 {
    glintAttrib(GLXX_API_20, indx, values[0], values[1], 0.0f, 1.0f);
 }
glVertexAttrib3f()
GL_APICALL void GL_APIENTRY glVertexAttrib3f (GLuint indx, GLfloat x, GLfloat y, GLfloat z)
Definition at line 4783 of file glxx_client.c.
References glintAttrib(), and GLXX_API_20.
 {
    glintAttrib(GLXX_API_20, indx, x, y, z, 1.0f);
 }
glVertexAttrib3fv()
GL_APICALL void GL_APIENTRY glVertexAttrib3fv (GLuint indx, const GLfloat * values)
Definition at line 4803 of file glxx_client.c.
References glintAttrib(), and GLXX_API_20.
 {
    glintAttrib(GLXX_API_20, indx, values[0], values[1], values[2], 1.0f);
 }
glVertexAttrib4f()
GL_APICALL void GL_APIENTRY glVertexAttrib4f (GLuint indx, GLfloat x, GLfloat y, GLfloat z, GLfloat w)
Definition at line 4788 of file glxx_client.c.
References glintAttrib(), and GLXX_API_20.
 {
    glintAttrib(GLXX_API_20, indx, x, y, z, w);
 }
glVertexAttrib4fv()
GL_APICALL void GL_APIENTRY glVertexAttrib4fv (GLuint indx, const GLfloat * values)
Definition at line 4808 of file glxx_client.c.
References glintAttrib(), and GLXX_API_20.
 {
    glintAttrib(GLXX_API_20, indx, values[0], values[1], values[2], values[3]);
 }
glVertexAttribPointer()
GL_APICALL void GL_APIENTRY glVertexAttribPointer (GLuint indx, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void * ptr)
Definition at line 4829 of file glxx_client.c.
 {
    if (is_vertex_attrib_size(size) && stride >= 0) {
       if (is_vertex_attrib_type(type) || type == GL_HALF_FLOAT_OES) {
          glintAttribPointer(GLXX_API_20, indx, size, type, normalized, stride, ptr);
       } else
          glxx_set_error_api(GLXX_API_20, GL_INVALID_ENUM);
    } else
       glxx_set_error_api(GLXX_API_20, GL_INVALID_VALUE);
 }
glVertexPointer()
GL_API void GL_APIENTRY glVertexPointer (GLint size, GLenum type, GLsizei stride, const GLvoid * pointer)
Definition at line 4855 of file glxx_client.c.
 {
    if (is_vertex_type(type)) {
       if (is_vertex_size(size) && is_aligned(type, (size_t)pointer) && is_aligned(type, (size_t)stride) && stride >= 0) {
          glintAttribPointer(GLXX_API_11, GL11_IX_VERTEX, size, type, GL_FALSE, stride, pointer);
       } else
          glxx_set_error_api(GLXX_API_11, GL_INVALID_VALUE);
    } else
       glxx_set_error_api(GLXX_API_11, GL_INVALID_ENUM);
 }
glViewport()
GL_API void GL_APIENTRY glViewport (GLint x, GLint y, GLsizei width, GLsizei height)
Definition at line 4866 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL4(glViewport_impl,
                 thread,
                 GLVIEWPORT_ID,
                 RPC_INT(x),
                 RPC_INT(y),
                 RPC_SIZEI(width),
                 RPC_SIZEI(height));
    }
 }
glxx_buffer_info_get()
void glxx_buffer_info_get (GLXX_CLIENT_STATE_T * state, GLenum target, GLXX_BUFFER_INFO_T * buffer_info)
Definition at line 173 of file glxx_client.c.
 {
    GLuint buffer = get_bound_buffer(state, target);
    memset(buffer_info,0,sizeof(GLXX_BUFFER_INFO_T));
    buffer_info->id = 0;
    if(buffer != 0)
    {
       GLXX_BUFFER_INFO_T *stored = khrn_pointer_map_lookup(&state->buffers, buffer);
       if(stored)
          *buffer_info = *stored;
    }
 }
glxx_buffer_info_set()
void glxx_buffer_info_set (GLXX_CLIENT_STATE_T * state, GLenum target, GLXX_BUFFER_INFO_T * buffer_info)
Definition at line 155 of file glxx_client.c.
 {
    GLuint buffer = get_bound_buffer(state, target);
    if(buffer != 0)
    {
       GLXX_BUFFER_INFO_T *stored = khrn_pointer_map_lookup(&state->buffers, buffer);
       if(!stored)
       {
          stored = khrn_platform_malloc(sizeof(GLXX_BUFFER_INFO_T), "GLXX_BUFFER_INFO_T");
          khrn_pointer_map_insert(&state->buffers, buffer, stored);
       }
       buffer_info->id = buffer;
       //copy into stored
       *stored = *buffer_info;
    }
 }
glxx_client_BindFramebuffer()
void glxx_client_BindFramebuffer (GLenum target, GLuint framebuffer)
Definition at line 5284 of file glxx_client.c.
Referenced by glBindFramebuffer(), and glBindFramebufferOES().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       RPC_CALL2(glBindFramebuffer_impl,
                 thread,
                 GLBINDFRAMEBUFFER_ID,
                 RPC_ENUM(target),
                 RPC_UINT(framebuffer));
       //TODO: this may be set incorrectly if there's an error
       state->default_framebuffer = (framebuffer == 0);
    }
 }
glxx_client_BindRenderbuffer()
void glxx_client_BindRenderbuffer (GLenum target, GLuint renderbuffer)
Definition at line 5146 of file glxx_client.c.
Referenced by glBindRenderbuffer(), and glBindRenderbufferOES().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL2(glBindRenderbuffer_impl,
                 thread,
                 GLBINDRENDERBUFFER_ID,
                 RPC_ENUM(target),
                 RPC_UINT(renderbuffer));
    }
 }
glxx_client_CheckFramebufferStatus()
GLenum glxx_client_CheckFramebufferStatus (GLenum target)
Definition at line 5360 of file glxx_client.c.
Referenced by glCheckFramebufferStatus(), and glCheckFramebufferStatusOES().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       return RPC_ENUM_RES(RPC_CALL1_RES(glCheckFramebufferStatus_impl,
                            thread,
                            GLCHECKFRAMEBUFFERSTATUS_ID,
                            RPC_ENUM(target)));
    }
    return GL_NONE;
 }
glxx_client_DeleteFramebuffers()
void glxx_client_DeleteFramebuffers (GLsizei n, const GLuint * framebuffers)
Definition at line 5305 of file glxx_client.c.
Referenced by glDeleteFramebuffers(), and glDeleteFramebuffersOES().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    int offset = 0;
    do {
       int32_t items = (int32_t)(KHDISPATCH_WORKSPACE_SIZE / sizeof(GLuint));
       int32_t batch = _min(items, (int32_t)n);
       if (IS_OPENGLES_11_OR_20(thread)) {
          RPC_CALL2_IN_BULK(glDeleteFramebuffers_impl,
                            thread,
                            GLDELETEFRAMEBUFFERS_ID,
                            RPC_SIZEI(batch),
                            framebuffers + offset,
                            batch > 0 ? batch * sizeof(GLuint) : 0);
       }
       offset += batch;
       n -= batch;
    } while (n > 0);
 }
glxx_client_DeleteRenderbuffers()
void glxx_client_DeleteRenderbuffers (GLsizei n, const GLuint * renderbuffers)
Definition at line 5164 of file glxx_client.c.
Referenced by glDeleteRenderbuffers(), and glDeleteRenderbuffersOES().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    int offset = 0;
    do {
       int32_t items = (int32_t) (KHDISPATCH_WORKSPACE_SIZE / sizeof(GLuint));
       int32_t batch = _min(items, (int32_t)n);
       if (IS_OPENGLES_11_OR_20(thread)) {
          RPC_CALL2_IN_BULK(glDeleteRenderbuffers_impl,
                            thread,
                            GLDELETERENDERBUFFERS_ID,
                            RPC_SIZEI(batch),
                            renderbuffers + offset,
                            batch > 0 ? batch * sizeof(GLuint) : 0);
       }
       offset += batch;
       n -= batch;
    } while (n > 0);
 }
glxx_client_FramebufferRenderbuffer()
void glxx_client_FramebufferRenderbuffer (GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer)
Definition at line 5398 of file glxx_client.c.
Referenced by glFramebufferRenderbuffer(), and glFramebufferRenderbufferOES().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL4(glFramebufferRenderbuffer_impl,
                 thread,
                 GLFRAMEBUFFERRENDERBUFFER_ID,
                 RPC_ENUM(target),
                 RPC_ENUM(attachment),
                 RPC_ENUM(renderbuffertarget),
                 RPC_UINT(renderbuffer));
    }
 }
glxx_client_FramebufferTexture2D()
void glxx_client_FramebufferTexture2D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
Definition at line 5378 of file glxx_client.c.
Referenced by glFramebufferTexture2D(), and glFramebufferTexture2DOES().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL5(glFramebufferTexture2D_impl,
                 thread,
                 GLFRAMEBUFFERTEXTURE2D_ID,
                 RPC_ENUM(target),
                 RPC_ENUM(attachment),
                 RPC_ENUM(textarget),
                 RPC_UINT(texture),
                 RPC_INT(level));
    }
 }
glxx_client_GenerateMipmap()
void glxx_client_GenerateMipmap (GLenum target)
Definition at line 5436 of file glxx_client.c.
Referenced by glGenerateMipmapOES().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL1(glGenerateMipmap_impl,
                 thread,
                 GLGENERATEMIPMAP_ID,
                 RPC_ENUM(target));
    }
 }
glxx_client_GenFramebuffers()
void glxx_client_GenFramebuffers (GLsizei n, GLuint * framebuffers)
Definition at line 5333 of file glxx_client.c.
Referenced by glGenFramebuffers(), and glGenFramebuffersOES().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    int offset = 0;
    do {
       int32_t items = (int32_t)(KHDISPATCH_WORKSPACE_SIZE / sizeof(GLuint));
       int32_t batch = _min(items, (int32_t)n);
       if (IS_OPENGLES_11_OR_20(thread)) {
          RPC_CALL2_OUT_BULK(glGenFramebuffers_impl,
                             thread,
                             GLGENFRAMEBUFFERS_ID,
                             RPC_SIZEI(batch),
                             framebuffers + offset);
       }
       offset += batch;
       n -= batch;
    } while (n > 0);
 }
glxx_client_GenRenderbuffers()
void glxx_client_GenRenderbuffers (GLsizei n, GLuint * renderbuffers)
Definition at line 5192 of file glxx_client.c.
Referenced by glGenRenderbuffers(), and glGenRenderbuffersOES().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    int offset = 0;
    do {
       int32_t items = (int32_t)(KHDISPATCH_WORKSPACE_SIZE / sizeof(GLuint));
       int32_t batch = _min(items, (int32_t)n);
       if (IS_OPENGLES_11_OR_20(thread)) {
          RPC_CALL2_OUT_BULK(glGenRenderbuffers_impl,
                             thread,
                             GLGENRENDERBUFFERS_ID,
                             RPC_SIZEI(batch),
                             renderbuffers + offset);
       }
       offset += batch;
       n -= batch;
    } while (n > 0);
 }
glxx_client_GetFramebufferAttachmentParameteriv()
void glxx_client_GetFramebufferAttachmentParameteriv (GLenum target, GLenum attachment, GLenum pname, GLint * params)
Definition at line 5417 of file glxx_client.c.
Referenced by glGetFramebufferAttachmentParameteriv(), and glGetFramebufferAttachmentParameterivOES().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL4_OUT_CTRL(glGetFramebufferAttachmentParameteriv_impl,
                          thread,
                          GLGETFRAMEBUFFERATTACHMENTPARAMETERIV_ID,
                          RPC_ENUM(target),
                          RPC_ENUM(attachment),
                          RPC_ENUM(pname),
                          params);
    }
 }
glxx_client_GetRenderbufferParameteriv()
void glxx_client_GetRenderbufferParameteriv (GLenum target, GLenum pname, GLint * params)
Definition at line 5238 of file glxx_client.c.
Referenced by glGetRenderbufferParameteriv(), and glGetRenderbufferParameterivOES().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL3_OUT_CTRL(glGetRenderbufferParameteriv_impl,
                          thread,
                          GLGETRENDERBUFFERPARAMETERIV_ID,
                          RPC_ENUM(target),
                          RPC_ENUM(pname),
                          params);
    }
 }
glxx_client_IsFramebuffer()
GLboolean glxx_client_IsFramebuffer (GLuint framebuffer)
Definition at line 5256 of file glxx_client.c.
Referenced by glIsFramebuffer(), and glIsFramebufferOES().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       return RPC_BOOLEAN_RES(RPC_CALL1_RES(glIsFramebuffer_impl,
                                            thread,
                                            GLISFRAMEBUFFER_ID,
                                            RPC_UINT(framebuffer)));
    }
    return 0;
 }
glxx_client_IsRenderbuffer()
GLboolean glxx_client_IsRenderbuffer (GLuint renderbuffer)
Definition at line 5127 of file glxx_client.c.
Referenced by glIsRenderbuffer(), and glIsRenderbufferOES().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       return RPC_BOOLEAN_RES(RPC_CALL1_RES(glIsRenderbuffer_impl,
                                            thread,
                                            GLISRENDERBUFFER_ID,
                                            RPC_UINT(renderbuffer)));
    }
    return 0;
 }
glxx_client_RenderbufferStorage()
void glxx_client_RenderbufferStorage (GLenum target, GLenum internalformat, GLsizei width, GLsizei height)
Definition at line 5219 of file glxx_client.c.
Referenced by glRenderbufferStorage(), and glRenderbufferStorageOES().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       RPC_CALL4(glRenderbufferStorage_impl,
                 thread,
                 GLRENDERBUFFERSTORAGE_ID,
                 RPC_ENUM(target),
                 RPC_ENUM(internalformat),
                 RPC_SIZEI(width),
                 RPC_SIZEI(height));
    }
 }
glxx_client_state_free()
void glxx_client_state_free (GLXX_CLIENT_STATE_T * state)
Definition at line 5574 of file glxx_client.c.
References GLXX_CLIENT_STATE_T::buffers.
 {
    khrn_pointer_map_iterate(&state->buffers, callback_delete_buffer_info, NULL);
    khrn_pointer_map_term(&state->buffers);
 #ifndef GLXX_NO_VERTEX_CACHE
    khrn_cache_term(&state->cache);
 #endif
    khrn_platform_free(state);
 }
glxx_set_error()
void glxx_set_error (GLXX_CLIENT_STATE_T * state, GLenum error)
Definition at line 116 of file glxx_client.c.
References set_error.
 {
    set_error(state,error);
 }
glxx_set_error_api()
void glxx_set_error_api (uint32_t api, GLenum error)
Definition at line 121 of file glxx_client.c.
Referenced by glGetPointerv(), glGetVertexAttribPointerv(), and glMultiTexCoord4f().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_API(thread, api))
    {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       glxx_set_error(state, error);
    }
 }
texSubImage2DAsync()
GL_API void GL_APIENTRY texSubImage2DAsync (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLint hpixels)
Definition at line 4389 of file glxx_client.c.
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11_OR_20(thread)) {
       GLXX_CLIENT_STATE_T *state = GLXX_GET_CLIENT_STATE(thread);
       RPC_CALL10(texSubImage2DAsync_impl,
                         thread,
                         TEXSUBIMAGE2DASYNC_ID,
                         RPC_ENUM(target),
                         RPC_INT(level),
                         RPC_INT(xoffset),
                         RPC_INT(yoffset),
                         RPC_SIZEI(width),
                         RPC_SIZEI(height),
                         RPC_ENUM(format),
                         RPC_ENUM(type),
                         RPC_INT(state->alignment.unpack),
                         RPC_INT(hpixels));
    }
 }
Variable Documentation
gl_client_log
VCOS_LOG_CAT_T gl_client_log = VCOS_LOG_INIT("gl_client", VCOS_LOG_WARN)
Definition at line 61 of file glxx_client.c.