VideoCore Library: interface/vmcs_host/vc_vchi_tvservice.c File Reference
vc_vchi_tvservice.c File Reference
#include <string.h>
#include "interface/vcos/vcos.h"
#include "vchost_platform_config.h"
#include "vchost.h"
#include "interface/vchi/vchi.h"
#include "interface/vchi/common/endian.h"
#include "interface/vchi/message_drivers/message.h"
#include "vc_tvservice.h"
#include "vc_dispmanx_types.h"
Classes
struct TVSERVICE_HOST_CALLBACK_T
struct TVSERVICE_MODE_CACHE_T
struct TVSERVICE_HOST_STATE_T
Macros
#define _min(x, y) (((x) <= (y))? (x) : (y))
#define _max(x, y) (((x) >= (y))? (x) : (y))
#define INVALID_DISPLAY_ID 65536
#define VCOS_LOG_CATEGORY (&tvservice_log_category)
Functions
VCHPRE_ int VCHPOST_ vc_vchi_tv_init (VCHI_INSTANCE_T initialise_instance, VCHI_CONNECTION_T **connections, uint32_t num_connections)
VCHPRE_ void VCHPOST_ vc_vchi_tv_stop (void)
VCHPRE_ void VCHPOST_ vc_tv_register_callback (TVSERVICE_CALLBACK_T callback, void *callback_data)
VCHPRE_ void VCHPOST_ vc_tv_unregister_callback (TVSERVICE_CALLBACK_T callback)
VCHPRE_ void VCHPOST_ vc_tv_unregister_callback_full (TVSERVICE_CALLBACK_T callback, void *callback_data)
VCHPRE_ int VCHPOST_ vc_tv_get_state_id (uint32_t display_id, TV_GET_STATE_RESP_T *tvstate)
VCHPRE_ int VCHPOST_ vc_tv_get_state (TV_GET_STATE_RESP_T *tvstate)
VCHPRE_ int VCHPOST_ vc_tv_get_display_state_id (uint32_t display_id, TV_DISPLAY_STATE_T *tvstate)
VCHPRE_ int VCHPOST_ vc_tv_get_display_state (TV_DISPLAY_STATE_T *tvstate)
VCHPRE_ int VCHPOST_ vc_tv_hdmi_power_on_preferred_id (uint32_t display_id)
VCHPRE_ int VCHPOST_ vc_tv_hdmi_power_on_preferred_3d_id (uint32_t display_id)
VCHPRE_ int VCHPOST_ vc_tv_hdmi_power_on_preferred ()
VCHPRE_ int VCHPOST_ vc_tv_hdmi_power_on_preferred_3d ()
VCHPRE_ int VCHPOST_ vc_tv_hdmi_power_on_best_id (uint32_t display_id, uint32_t width, uint32_t height, uint32_t frame_rate, HDMI_INTERLACED_T scan_mode, EDID_MODE_MATCH_FLAG_T match_flags)
VCHPRE_ int VCHPOST_ vc_tv_hdmi_power_on_best_3d_id (uint32_t display_id, uint32_t width, uint32_t height, uint32_t frame_rate, HDMI_INTERLACED_T scan_mode, EDID_MODE_MATCH_FLAG_T match_flags)
VCHPRE_ int VCHPOST_ vc_tv_hdmi_power_on_best (uint32_t width, uint32_t height, uint32_t frame_rate, HDMI_INTERLACED_T scan_mode, EDID_MODE_MATCH_FLAG_T match_flags)
VCHPRE_ int VCHPOST_ vc_tv_hdmi_power_on_best_3d (uint32_t width, uint32_t height, uint32_t frame_rate, HDMI_INTERLACED_T scan_mode, EDID_MODE_MATCH_FLAG_T match_flags)
VCHPRE_ int VCHPOST_ vc_tv_hdmi_power_on_explicit_new_id (uint32_t display_id, HDMI_MODE_T mode, HDMI_RES_GROUP_T group, uint32_t code)
VCHPRE_ int VCHPOST_ vc_tv_hdmi_power_on_explicit_new (HDMI_MODE_T mode, HDMI_RES_GROUP_T group, uint32_t code)
VCHPRE_ int VCHPOST_ vc_tv_sdtv_power_on_id (uint32_t display_id, SDTV_MODE_T mode, SDTV_OPTIONS_T *options)
VCHPRE_ int VCHPOST_ vc_tv_sdtv_power_on (SDTV_MODE_T mode, SDTV_OPTIONS_T *options)
VCHPRE_ int VCHPOST_ vc_tv_power_off_id (uint32_t display_id)
VCHPRE_ int VCHPOST_ vc_tv_power_off (void)
VCHPRE_ int VCHPOST_ vc_tv_hdmi_get_supported_modes_new_id (uint32_t display_id, HDMI_RES_GROUP_T group, TV_SUPPORTED_MODE_NEW_T *supported_modes, uint32_t max_supported_modes, HDMI_RES_GROUP_T *preferred_group, uint32_t *preferred_mode)
VCHPRE_ int VCHPOST_ vc_tv_hdmi_get_supported_modes_new (HDMI_RES_GROUP_T group, TV_SUPPORTED_MODE_NEW_T *supported_modes, uint32_t max_supported_modes, HDMI_RES_GROUP_T *preferred_group, uint32_t *preferred_mode)
VCHPRE_ int VCHPOST_ vc_tv_hdmi_mode_supported_id (uint32_t display_id, HDMI_RES_GROUP_T group, uint32_t mode)
VCHPRE_ int VCHPOST_ vc_tv_hdmi_mode_supported (HDMI_RES_GROUP_T group, uint32_t mode)
VCHPRE_ int VCHPOST_ vc_tv_hdmi_audio_supported_id (uint32_t display_id, uint32_t audio_format, uint32_t num_channels, EDID_AudioSampleRate fs, uint32_t bitrate)
VCHPRE_ int VCHPOST_ vc_tv_hdmi_audio_supported (uint32_t audio_format, uint32_t num_channels, EDID_AudioSampleRate fs, uint32_t bitrate)
VCHPRE_ int VCHPOST_ vc_tv_enable_copyprotect_id (uint32_t display_id, uint32_t cp_mode, uint32_t timeout)
VCHPRE_ int VCHPOST_ vc_tv_enable_copyprotect (uint32_t cp_mode, uint32_t timeout)
VCHPRE_ int VCHPOST_ vc_tv_disable_copyprotect_id (uint32_t display_id)
VCHPRE_ int VCHPOST_ vc_tv_disable_copyprotect (void)
VCHPRE_ int VCHPOST_ vc_tv_show_info_id (uint32_t display_id, uint32_t show)
VCHPRE_ int VCHPOST_ vc_tv_show_info (uint32_t show)
VCHPRE_ int VCHPOST_ vc_tv_hdmi_get_av_latency_id (uint32_t display_id)
VCHPRE_ int VCHPOST_ vc_tv_hdmi_get_av_latency (void)
VCHPRE_ int VCHPOST_ vc_tv_hdmi_set_hdcp_key_id (uint32_t display_id, const uint8_t *key)
VCHPRE_ int VCHPOST_ vc_tv_hdmi_set_hdcp_key (const uint8_t *key)
VCHPRE_ int VCHPOST_ vc_tv_hdmi_set_hdcp_revoked_list_id (uint32_t display_id, const uint8_t *list, uint32_t num_keys)
VCHPRE_ int VCHPOST_ vc_tv_hdmi_set_hdcp_revoked_list (const uint8_t *list, uint32_t num_keys)
VCHPRE_ int VCHPOST_ vc_tv_hdmi_set_spd_id (uint32_t display_id, const char *manufacturer, const char *description, HDMI_SPD_TYPE_CODE_T type)
VCHPRE_ int VCHPOST_ vc_tv_hdmi_set_spd (const char *manufacturer, const char *description, HDMI_SPD_TYPE_CODE_T type)
VCHPRE_ int VCHPOST_ vc_tv_hdmi_set_display_options_id (uint32_t display_id, HDMI_ASPECT_T aspect, uint32_t left_bar_width, uint32_t right_bar_width, uint32_t top_bar_height, uint32_t bottom_bar_height, uint32_t overscan_flags)
VCHPRE_ int VCHPOST_ vc_tv_hdmi_set_display_options (HDMI_ASPECT_T aspect, uint32_t left_bar_width, uint32_t right_bar_width, uint32_t top_bar_height, uint32_t bottom_bar_height, uint32_t overscan_flags)
VCHPRE_ int VCHPOST_ vc_tv_test_mode_start_id (uint32_t display_id, uint32_t colour, TV_TEST_MODE_T test_mode)
VCHPRE_ int VCHPOST_ vc_tv_test_mode_start (uint32_t colour, TV_TEST_MODE_T test_mode)
VCHPRE_ int VCHPOST_ vc_tv_test_mode_stop_id (uint32_t display_id)
VCHPRE_ int VCHPOST_ vc_tv_test_mode_stop (void)
VCHPRE_ int VCHPOST_ vc_tv_hdmi_ddc_read_id (uint32_t display_id, uint32_t offset, uint32_t length, uint8_t *buffer)
VCHPRE_ int VCHPOST_ vc_tv_hdmi_ddc_read (uint32_t offset, uint32_t length, uint8_t *buffer)
VCHPRE_ int VCHPOST_ vc_tv_hdmi_set_attached_id (uint32_t display_id, uint32_t attached)
VCHPRE_ int VCHPOST_ vc_tv_hdmi_set_attached (uint32_t attached)
VCHPRE_ int VCHPOST_ vc_tv_hdmi_set_property_id (uint32_t display_id, const HDMI_PROPERTY_PARAM_T *property)
VCHPRE_ int VCHPOST_ vc_tv_hdmi_set_property (const HDMI_PROPERTY_PARAM_T *property)
VCHPRE_ int VCHPOST_ vc_tv_hdmi_get_property_id (uint32_t display_id, HDMI_PROPERTY_PARAM_T *property)
VCHPRE_ int VCHPOST_ vc_tv_hdmi_get_property (HDMI_PROPERTY_PARAM_T *property)
VCHPRE_ const char * vc_tv_notification_name (VC_HDMI_NOTIFY_T reason)
VCHPRE_ int VCHPOST_ vc_tv_hdmi_get_supported_modes_id (uint32_t display_id, HDMI_RES_GROUP_T group, TV_SUPPORTED_MODE_T *supported_modes_deprecated, uint32_t max_supported_modes, HDMI_RES_GROUP_T *preferred_group, uint32_t *preferred_mode)
VCHPRE_ int VCHPOST_ vc_tv_hdmi_get_supported_modes (HDMI_RES_GROUP_T group, TV_SUPPORTED_MODE_T *supported_modes_deprecated, uint32_t max_supported_modes, HDMI_RES_GROUP_T *preferred_group, uint32_t *preferred_mode)
VCHPRE_ int VCHPOST_ vc_tv_get_device_id_id (uint32_t display_id, TV_DEVICE_ID_T *id)
VCHPRE_ int VCHPOST_ vc_tv_get_device_id (TV_DEVICE_ID_T *id)
VCHPRE_ int VCHPOST_ vc_tv_hdmi_power_on_explicit_id (uint32_t display_id, HDMI_MODE_T mode, HDMI_RES_GROUP_T group, uint32_t code)
VCHPRE_ int VCHPOST_ vc_tv_hdmi_power_on_explicit (HDMI_MODE_T mode, HDMI_RES_GROUP_T group, uint32_t code)
VCHPRE_ int VCHPOST_ vc_tv_get_attached_devices (TV_ATTACHED_DEVICES_T *devices)
Macro Definition Documentation
_max
#define _max (x, y) (((x) >= (y))? (x) : (y))
Definition at line 50 of file vc_vchi_tvservice.c.
_min
#define _min (x, y) (((x) <= (y))? (x) : (y))
Definition at line 47 of file vc_vchi_tvservice.c.
INVALID_DISPLAY_ID
#define INVALID_DISPLAY_ID 65536
Definition at line 54 of file vc_vchi_tvservice.c.
VCOS_LOG_CATEGORY
#define VCOS_LOG_CATEGORY (&tvservice_log_category)
Definition at line 117 of file vc_vchi_tvservice.c.
Referenced by vc_vchi_tv_init().
Function Documentation
vc_tv_disable_copyprotect()
VCHPRE_ int VCHPOST_ vc_tv_disable_copyprotect (void)
Use vc_tv_disable_copyprotect to turn off copy protection
Parameters
none 0 means success, additional result via callback
Definition at line 1480 of file vc_vchi_tvservice.c.
References vc_tv_disable_copyprotect_id().
{
    return vc_tv_disable_copyprotect_id(default_display_number);
 }
vc_tv_disable_copyprotect_id()
VCHPRE_ int VCHPOST_ vc_tv_disable_copyprotect_id (uint32_t display_id)
Definition at line 1475 of file vc_vchi_tvservice.c.
References VCOS_FUNCTION.
Referenced by vc_tv_disable_copyprotect().
{
    vcos_log_trace("[%s]", VCOS_FUNCTION);
    return tvservice_send_command( VC_TV_DISABLE_COPY_PROTECT, display_id, NULL, 0, 1);
 }
vc_tv_enable_copyprotect()
VCHPRE_ int VCHPOST_ vc_tv_enable_copyprotect (uint32_t cp_mode, uint32_t timeout)
Use vc_tv_enable_copyprotect to turn on copy protection. For HDMI, only HDMI_CP_HDCP is recognised. For SDTV, use one of the values in SDTV_CP_MODE_T
Parameters
copy protect mode
time out in milliseconds (only applicable to HDMI)
Returns
0 means success, additional result via callback
Definition at line 1460 of file vc_vchi_tvservice.c.
References vc_tv_enable_copyprotect_id().
{
    return vc_tv_enable_copyprotect_id(default_display_number, cp_mode, timeout);
 }
vc_tv_enable_copyprotect_id()
VCHPRE_ int VCHPOST_ vc_tv_enable_copyprotect_id (uint32_t display_id, uint32_t cp_mode, uint32_t timeout)
Definition at line 1454 of file vc_vchi_tvservice.c.
References VC_HTOV32, and VCOS_FUNCTION.
Referenced by vc_tv_enable_copyprotect().
{
    TV_ENABLE_COPY_PROTECT_PARAM_T param = {VC_HTOV32(cp_mode), VC_HTOV32(timeout)};
    vcos_log_trace("[%s]", VCOS_FUNCTION);
    return tvservice_send_command( VC_TV_ENABLE_COPY_PROTECT, display_id, &param, sizeof(TV_ENABLE_COPY_PROTECT_PARAM_T), 1);
 }
vc_tv_get_attached_devices()
VCHPRE_ int VCHPOST_ vc_tv_get_attached_devices (TV_ATTACHED_DEVICES_T * devices)
Get list of attached devices
Parameters
pointer to attached devices struc
Returns
zero if successful, non-zero if failed.
Definition at line 1908 of file vc_vchi_tvservice.c.
 {
    memset(devices, 0, sizeof(*devices));
    return tvservice_send_command_reply(VC_TV_GET_ATTACHED_DEVICES, INVALID_DISPLAY_ID, NULL, 0,
                                        devices, sizeof(*devices));
 }
vc_tv_get_device_id()
VCHPRE_ int VCHPOST_ vc_tv_get_device_id (TV_DEVICE_ID_T * id)
Get the unique device ID from the EDID
Parameters
pointer to device ID struct
Returns
zero if successful, non-zero if failed.
Definition at line 1887 of file vc_vchi_tvservice.c.
References vc_tv_get_device_id_id().
{
    return vc_tv_get_device_id_id(default_display_number, id);
 }
vc_tv_get_device_id_id()
VCHPRE_ int VCHPOST_ vc_tv_get_device_id_id (uint32_t display_id, TV_DEVICE_ID_T * id)
Get the unique device ID from the EDID
Parameters
pointer to device ID struct
Returns
zero if successful, non-zero if failed.
Definition at line 1870 of file vc_vchi_tvservice.c.
References vcos_verify.
Referenced by vc_tv_get_device_id().
{
    int ret = -1;
    TV_DEVICE_ID_T param;
    memset(&param, 0, sizeof(TV_DEVICE_ID_T));
    if(vcos_verify(id)) {
       if((ret = tvservice_send_command_reply( VC_TV_GET_DEVICE_ID, display_id, NULL, 0,
                                               &param, sizeof(param))) == VC_HDMI_SUCCESS) {
          memcpy(id, &param, sizeof(TV_DEVICE_ID_T));
       } else {
          id->vendor[0] = '\0';
          id->monitor_name[0] = '\0';
          id->serial_num = 0;
       }
    }
    return ret;
 }
vc_tv_get_display_state()
VCHPRE_ int VCHPOST_ vc_tv_get_display_state (TV_DISPLAY_STATE_T * tvstate)
vc_tv_get_display_state is used to obtain the current TV display state. This function supersedes vc_tv_get_state (which is only kept for backward compatibility. Host applications should call this function right after registering a callback in case any notifications are missed.
Parameters
pointer to TV_DISPLAY_STATE_T
Returns
zero if the command is sent successfully, non zero otherwise If the command fails to be sent, passed in state is unchanged
Definition at line 1049 of file vc_vchi_tvservice.c.
References vc_tv_get_display_state_id().
{
    return vc_tv_get_display_state_id(default_display_number, tvstate);
 }
vc_tv_get_display_state_id()
VCHPRE_ int VCHPOST_ vc_tv_get_display_state_id (uint32_t display_id, TV_DISPLAY_STATE_T * tvstate)
Definition at line 1038 of file vc_vchi_tvservice.c.
References VCOS_FUNCTION, and vcos_verify.
Referenced by vc_tv_get_display_state().
{
    int success = -1;
    vcos_log_trace("[%s]", VCOS_FUNCTION);
    if(vcos_verify(tvstate)) {
       success = tvservice_send_command_reply( VC_TV_GET_DISPLAY_STATE, display_id, NULL, 0,
                                               tvstate, sizeof(TV_DISPLAY_STATE_T));
    }
    return success;
 }
vc_tv_get_state()
VCHPRE_ int VCHPOST_ vc_tv_get_state (TV_GET_STATE_RESP_T * tvstate)
In the following API any functions applying to HDMI only will have hdmi_ in the name, ditto for SDTV only will have sdtv_ in the name, Otherwise the function applies to both SDTV and HDMI (e.g. power off) vc_tv_get_state is used to obtain the current TV state. Host applications should call this function right after registering a callback in case any notifications are missed.
Now deprecated - use vc_tv_get_display_state instead
Parameters
pointer to TV_GET_STATE_RESP_T
Returns
zero if the command is sent successfully, non zero otherwise If the command fails to be sent, passed in state is unchanged
Definition at line 1021 of file vc_vchi_tvservice.c.
References vc_tv_get_state_id().
 {
    return vc_tv_get_state_id(default_display_number, tvstate);
 }
vc_tv_get_state_id()
VCHPRE_ int VCHPOST_ vc_tv_get_state_id (uint32_t display_id, TV_GET_STATE_RESP_T * tvstate)
Definition at line 1003 of file vc_vchi_tvservice.c.
References VCOS_FUNCTION, and vcos_verify.
Referenced by vc_tv_get_state().
{
    int success = -1;
    vcos_log_trace("[%s]", VCOS_FUNCTION);
    if(vcos_verify(tvstate)) {
       success = tvservice_send_command_reply( VC_TV_GET_STATE, display_id, NULL, 0,
                                               tvstate, sizeof(*tvstate));
       if(success == 0) {
          tvstate->state = VC_VTOH32(tvstate->state);
          tvstate->width = VC_VTOH32(tvstate->width);
          tvstate->height = VC_VTOH32(tvstate->height);
          tvstate->frame_rate = VC_VTOH16(tvstate->frame_rate);
          tvstate->scan_mode = VC_VTOH16(tvstate->scan_mode);
       }
    }
    return success;
 }
vc_tv_hdmi_audio_supported()
VCHPRE_ int VCHPOST_ vc_tv_hdmi_audio_supported (uint32_t audio_format, uint32_t num_channels, EDID_AudioSampleRate fs, uint32_t bitrate)
vc_tv_hdmi_audio_supported is used to query whether a particular audio format is supported. By default a device has to support 16-bit stereo PCM at 32/44.1/48 kHz if audio is supported at all. Support of other audio formats allow SPDIF to be used. A return value of zero means the audio format is completely supported. Any non-zero values are interpreted as bit mask (EDID_AUDIO_SUPPORT_FLAG_T). For example, if EDID_AUDIO_NO_SUPPORT is set, the audio format is not supported. If EDID_AUDIO_CHAN_UNSUPPORTED is set, the max no. of channels has exceeded.
Parameters
audio format supplied as (EDID_AudioFormat + EDID_AudioCodingExtension)
no. of channels (1-8)
sample rate EDID_AudioSampleRate but NOT "refer to header"
bit rate (or sample size if pcm) use EDID_AudioSampleSize as sample size argument
Returns
: single value return interpreted as flags in EDID_AUDIO_SUPPORT_FLAG_T
Definition at line 1437 of file vc_vchi_tvservice.c.
References vc_tv_hdmi_audio_supported_id().
{
    return vc_tv_hdmi_audio_supported_id(default_display_number, audio_format, num_channels,
                                      fs, bitrate);
 }
vc_tv_hdmi_audio_supported_id()
VCHPRE_ int VCHPOST_ vc_tv_hdmi_audio_supported_id (uint32_t display_id, uint32_t audio_format, uint32_t num_channels, EDID_AudioSampleRate fs, uint32_t bitrate)
Definition at line 1422 of file vc_vchi_tvservice.c.
References EDID_AudioSampleRate_eReferToHeader, VC_HTOV32, VCOS_FUNCTION, and vcos_verify.
Referenced by vc_tv_hdmi_audio_supported().
{
    TV_QUERY_AUDIO_SUPPORT_PARAM_T param = { VC_HTOV32(audio_format),
                                             VC_HTOV32(num_channels),
                                             VC_HTOV32(fs),
                                             VC_HTOV32(bitrate) };
    vcos_log_trace("[%s]", VCOS_FUNCTION);
    if(!vcos_verify(num_channels > 0 && num_channels <= 8 && fs != EDID_AudioSampleRate_eReferToHeader))
       return -1;
    return tvservice_send_command( VC_TV_QUERY_AUDIO_SUPPORT, display_id, &param, sizeof(TV_QUERY_AUDIO_SUPPORT_PARAM_T), 1);
 }
vc_tv_hdmi_ddc_read()
VCHPRE_ int VCHPOST_ vc_tv_hdmi_ddc_read (uint32_t offset, uint32_t length, uint8_t * buffer)
vc_tv_hdmi_ddc_read allows an host application to read EDID with DDC protocol.
Parameters
offset
length to read (this is typically 128 bytes to coincide with EDID block size)
pointer to buffer, must be 16 byte aligned
Returns
length of data read (so zero means error) and the buffer will be filled only if there is no error
Definition at line 1734 of file vc_vchi_tvservice.c.
References vc_tv_hdmi_ddc_read_id().
{
    return vc_tv_hdmi_ddc_read_id(default_display_number, offset, length, buffer);
 }
vc_tv_hdmi_ddc_read_id()
VCHPRE_ int VCHPOST_ vc_tv_hdmi_ddc_read_id (uint32_t display_id, uint32_t offset, uint32_t length, uint8_t * buffer)
Definition at line 1715 of file vc_vchi_tvservice.c.
References TVSERVICE_HOST_STATE_T::client_handle, VC_HTOV32, vchi_service_use(), and VCOS_FUNCTION.
Referenced by vc_tv_hdmi_ddc_read().
{
    int success;
    TV_DDC_READ_PARAM_T param = {VC_HTOV32(offset), VC_HTOV32(length)};
    vcos_log_trace("[%s]", VCOS_FUNCTION);
    /*if(!vcos_verify(buffer && (((uint32_t) buffer) % 16) == 0))
       return -1;*/
    vchi_service_use(tvservice_client.client_handle[0]);
    success = tvservice_send_command( VC_TV_DDC_READ, display_id, &param, sizeof(TV_DDC_READ_PARAM_T), 1);
    if(success == 0) {
       success = tvservice_wait_for_bulk_receive(buffer, length);
    }
    vchi_service_release(tvservice_client.client_handle[0]);
    return (success == 0)? length : 0; //Either return the whole block or nothing
 }
vc_tv_hdmi_get_av_latency()
VCHPRE_ int VCHPOST_ vc_tv_hdmi_get_av_latency (void)
vc_tv_hdmi_get_av_latency is used to get the AV latency (in ms) for HDMI (lipsync), only valid if HDMI is currently powered on, otherwise you get zero. The latency is defined as the relative delay of the video stream to the audio stream
Parameters
none
Returns
latency (zero if error or latency is not defined), < 0 if failed to send command)
Definition at line 1523 of file vc_vchi_tvservice.c.
References vc_tv_hdmi_get_av_latency_id().
{
    return vc_tv_hdmi_get_av_latency_id(default_display_number);
 }
vc_tv_hdmi_get_av_latency_id()
VCHPRE_ int VCHPOST_ vc_tv_hdmi_get_av_latency_id (uint32_t display_id)
Definition at line 1517 of file vc_vchi_tvservice.c.
References VCOS_FUNCTION.
Referenced by vc_tv_hdmi_get_av_latency().
{
    vcos_log_trace("[%s]", VCOS_FUNCTION);
    return tvservice_send_command( VC_TV_GET_AV_LATENCY, display_id, NULL, 0, 1);
 }
vc_tv_hdmi_get_property()
VCHPRE_ int VCHPOST_ vc_tv_hdmi_get_property (HDMI_PROPERTY_PARAM_T * property)
Gets the current value of an HDMI property.
Parameters
property [in/out]
Returns
zero if success (param1/param2 will be set), non-zero otherwise (param1/param2 will not be set)
Definition at line 1788 of file vc_vchi_tvservice.c.
References vc_tv_hdmi_get_property_id().
{
    return vc_tv_hdmi_get_property_id(default_display_number, property);
 }
vc_tv_hdmi_get_property_id()
VCHPRE_ int VCHPOST_ vc_tv_hdmi_get_property_id (uint32_t display_id, HDMI_PROPERTY_PARAM_T * property)
Gets a property from HDMI
Definition at line 1772 of file vc_vchi_tvservice.c.
References HDMI_PROPERTY_MAX, HDMI_PROPERTY_PARAM_T::param1, HDMI_PROPERTY_PARAM_T::param2, HDMI_PROPERTY_PARAM_T::property, VCOS_FUNCTION, and vcos_verify.
Referenced by vc_tv_hdmi_get_property().
{
    int ret = -1;
    if(vcos_verify(property)) {
       TV_GET_PROP_PARAM_T param = {0, {HDMI_PROPERTY_MAX, 0, 0}};
       uint32_t prop = (uint32_t) property->property;
       property->param1 = property->param2 = 0;
       vcos_log_trace("[%s] property:%d", VCOS_FUNCTION, property->property);
       if((ret = tvservice_send_command_reply( VC_TV_GET_PROP, display_id, &prop, sizeof(prop),
                                               &param, sizeof(param))) == VC_HDMI_SUCCESS) {
          property->param1 = param.property.param1;
          property->param2 = param.property.param2;
       }
    }
    return ret;
 }
vc_tv_hdmi_get_supported_modes()
VCHPRE_ int VCHPOST_ vc_tv_hdmi_get_supported_modes (HDMI_RES_GROUP_T group, TV_SUPPORTED_MODE_T * supported_modes_deprecated, uint32_t max_supported_modes, HDMI_RES_GROUP_T * preferred_group, uint32_t * preferred_mode)
Definition at line 1853 of file vc_vchi_tvservice.c.
References vc_tv_hdmi_get_supported_modes_id().
{
       return vc_tv_hdmi_get_supported_modes_id(default_display_number, group,
                                                supported_modes_deprecated,
                                                max_supported_modes,
                                                preferred_group,
                                                preferred_mode);
 }
vc_tv_hdmi_get_supported_modes_id()
VCHPRE_ int VCHPOST_ vc_tv_hdmi_get_supported_modes_id (uint32_t display_id, HDMI_RES_GROUP_T group, TV_SUPPORTED_MODE_T * supported_modes_deprecated, uint32_t max_supported_modes, HDMI_RES_GROUP_T * preferred_group, uint32_t * preferred_mode)
Definition at line 1826 of file vc_vchi_tvservice.c.
References TV_SUPPORTED_MODE_NEW_T::code, TV_SUPPORTED_MODE_T::code, TV_SUPPORTED_MODE_NEW_T::frame_rate, TV_SUPPORTED_MODE_T::frame_rate, HDMI_3D_STRUCT_SIDE_BY_SIDE_HALF_HORIZONTAL, HDMI_RES_GROUP_CEA, TV_SUPPORTED_MODE_NEW_T::height, TV_SUPPORTED_MODE_T::height, TV_SUPPORTED_MODE_NEW_T::native, TV_SUPPORTED_MODE_T::native, TV_SUPPORTED_MODE_NEW_T::scan_mode, TV_SUPPORTED_MODE_T::scan_mode, TV_SUPPORTED_MODE_NEW_T::struct_3d_mask, vc_tv_hdmi_get_supported_modes_new_id(), TV_SUPPORTED_MODE_NEW_T::width, and TV_SUPPORTED_MODE_T::width.
Referenced by vc_tv_hdmi_get_supported_modes().
{
    TV_SUPPORTED_MODE_NEW_T *supported_modes_new = malloc(max_supported_modes * sizeof *supported_modes_new);
    int modes_copied = vc_tv_hdmi_get_supported_modes_new_id(display_id, group==3 ? HDMI_RES_GROUP_CEA:group, supported_modes_new, max_supported_modes, preferred_group, preferred_mode);
    int i, j=0;
    for (i=0; i<modes_copied; i++) {
       TV_SUPPORTED_MODE_T *q = supported_modes_deprecated + j;
       TV_SUPPORTED_MODE_NEW_T *p = supported_modes_new + i;
       if (group != 3 || (p->struct_3d_mask & HDMI_3D_STRUCT_SIDE_BY_SIDE_HALF_HORIZONTAL)) {
          q->scan_mode = p->scan_mode;
          q->native = p->native;
          q->code = p->code;
          q->frame_rate = p->frame_rate;
          q->width = p->width;
          q->height = p->height;
          j++;
       }
    }
    free(supported_modes_new);
    return 0;
 }
vc_tv_hdmi_get_supported_modes_new()
VCHPRE_ int VCHPOST_ vc_tv_hdmi_get_supported_modes_new (HDMI_RES_GROUP_T group, TV_SUPPORTED_MODE_NEW_T * supported_modes, uint32_t max_supported_modes, HDMI_RES_GROUP_T * preferred_group, uint32_t * preferred_mode)
vc_tv_hdmi_get_supported_modes is used to get a list of supported modes for a particular standard (CEA/DMT/CEA3D). Prefer resolution (group and mode) is also returned, if needed. If there are more modes supported than the size of the array supply, only the array will be filled.
Parameters
group(HDMI_RES_GROUP_CEA/HDMI_RES_GROUP_DMT)
array of TV_SUPPORT_MODE_T struct
length of array above (in elements, not bytes)
to preferred group (can be NULL)
to prefer mode code (can be NULL)
Returns
the number of modes actually written in the array, zero means no modes (no EDID or cable unplugged)
Definition at line 1369 of file vc_vchi_tvservice.c.
References vc_tv_hdmi_get_supported_modes_new_id().
{
    return vc_tv_hdmi_get_supported_modes_new_id(default_display_number,
                                                 group,
                                                 supported_modes,
                                                 max_supported_modes,
                                                 preferred_group,
                                                 preferred_mode);
 }
vc_tv_hdmi_get_supported_modes_new_id()
VCHPRE_ int VCHPOST_ vc_tv_hdmi_get_supported_modes_new_id (uint32_t display_id, HDMI_RES_GROUP_T group, TV_SUPPORTED_MODE_NEW_T * supported_modes, uint32_t max_supported_modes, HDMI_RES_GROUP_T * preferred_group, uint32_t * preferred_mode)
Definition at line 1259 of file vc_vchi_tvservice.c.
References TVSERVICE_HOST_STATE_T::cea_cache, TVSERVICE_HOST_STATE_T::client_handle, TVSERVICE_HOST_STATE_T::dmt_cache, error(), HDMI_RES_GROUP_CEA, HDMI_RES_GROUP_DMT, TVSERVICE_MODE_CACHE_T::is_valid, NULL, vchi_service_use(), and VCOS_FUNCTION.
Referenced by vc_tv_hdmi_get_supported_modes_id(), and vc_tv_hdmi_get_supported_modes_new().
{
    uint32_t param[2] = {(uint32_t) group, 0};
    TV_QUERY_SUPPORTED_MODES_RESP_T response;
    TVSERVICE_MODE_CACHE_T *cache = NULL;
    int error = -1;
    int modes_copied = 0;
    vcos_log_trace("[%s]", VCOS_FUNCTION);
    switch(group) {
       case HDMI_RES_GROUP_DMT:
          cache = &tvservice_client.dmt_cache;
          break;
       case HDMI_RES_GROUP_CEA:
          cache = &tvservice_client.cea_cache;
          break;
       default:
          vcos_log_error("Invalid group %d in [%s]", group, VCOS_FUNCTION);
          return -1;
    }
    vcos_log_trace("[%s] group %d cache valid %d",
                   VCOS_FUNCTION, group, cache->is_valid);
    memset(&response, 0, sizeof(response));
    if(!cache->is_valid) {
       vchi_service_use(tvservice_client.client_handle[0]);
       if((error = tvservice_send_command_reply(VC_TV_QUERY_SUPPORTED_MODES, display_id, &param[0], sizeof(uint32_t),
                                                &response, sizeof(response))) == VC_HDMI_SUCCESS) {
          //First ask how many modes there are, if the current table is big enough to hold
          //all the modes, just copy over, otherwise allocate a new table
          if(response.num_supported_modes) {
             if(cache->max_modes < response.num_supported_modes) {
                cache->max_modes = response.num_supported_modes;
                if(cache->modes) {
                   vcos_free(cache->modes);
                   cache->modes = NULL;
                }
             } else {
                vcos_assert(cache->modes);
                memset(cache->modes, 0, cache->max_modes * sizeof(TV_SUPPORTED_MODE_NEW_T));
             }
             if(cache->modes == NULL) {
                cache->modes = vcos_calloc(cache->max_modes, sizeof(TV_SUPPORTED_MODE_NEW_T), "cached modes");
             }
             if(vcos_verify(cache->modes)) {
                //If we have successfully allocated the table, send
                //another request to actually download the modes from Videocore
                param[1] = response.num_supported_modes;
                if((error = tvservice_send_command_reply(VC_TV_QUERY_SUPPORTED_MODES_ACTUAL, display_id, param, sizeof(param),
                                                         &response, sizeof(response))) == VC_HDMI_SUCCESS) {
                   //The response comes back may indicate a different number of modes to param[1].
                   //This happens if a new EDID was read in between the two requests (should be rare),
                   //in which case we just download as many as VC says will be sent
                   cache->num_modes = response.num_supported_modes;
                   vcos_assert(response.num_supported_modes <= param[1]); //VC will not return more than what we have allocated
                   if(cache->num_modes) {
                      error = tvservice_wait_for_bulk_receive(cache->modes, cache->num_modes * sizeof(TV_SUPPORTED_MODE_NEW_T));
                      if(error)
                         vcos_log_error("Failed to download %s cache in [%s]", HDMI_RES_GROUP_NAME(group), VCOS_FUNCTION);
                   } else {
                      vcos_log_error("First query of supported modes indicated there are %d, but now there are none, has the TV been unplugged? [%s]",
                                     param[1], VCOS_FUNCTION);
                   }
                } else {
                   vcos_log_error("Failed to request %s cache in [%s]", HDMI_RES_GROUP_NAME(group), VCOS_FUNCTION);
                }
             } else {
                //If we failed to allocate memory, the request stops here
                vcos_log_error("Failed to allocate memory for %s cache in [%s]", HDMI_RES_GROUP_NAME(group), VCOS_FUNCTION);
             }
          } else {
             //The request also terminates if there are no supported modes reported
             vcos_log_trace("No supported modes returned for group %s in [%s]", HDMI_RES_GROUP_NAME(group), VCOS_FUNCTION);
          }
       } else {
          vcos_log_error("Failed to query supported modes for group %s in [%s]", HDMI_RES_GROUP_NAME(group), VCOS_FUNCTION);
       }
       vchi_service_release(tvservice_client.client_handle[0]);
       if(!error) {
          cache->is_valid = 1;
          vcos_log_trace("[%s] cached %d %s resolutions", VCOS_FUNCTION, response.num_supported_modes, HDMI_RES_GROUP_NAME(group));
          tvservice_client.hdmi_preferred_group = response.preferred_group;
          tvservice_client.hdmi_preferred_mode  = response.preferred_mode;
       }
    }
    if(cache->is_valid) {
       if(supported_modes && max_supported_modes) {
          modes_copied = _min(max_supported_modes, cache->num_modes);
          memcpy(supported_modes, cache->modes, modes_copied*sizeof(TV_SUPPORTED_MODE_NEW_T));
       } else {
          //If we pass in a null pointer, return the size of table instead
          modes_copied = cache->num_modes;
       }
    }
    if(preferred_group && preferred_mode) {
       *preferred_group = tvservice_client.hdmi_preferred_group;
       *preferred_mode = tvservice_client.hdmi_preferred_mode;
    }
    return modes_copied; //If there was an error, this will be zero
 }
vc_tv_hdmi_mode_supported()
VCHPRE_ int VCHPOST_ vc_tv_hdmi_mode_supported (HDMI_RES_GROUP_T group, uint32_t mode)
vc_tv_hdmi_mode_supported is used to query whether a particular mode is supported or not.
Parameters
resolution standard (HDMI_RES_GROUP_CEA/HDMI_RES_GROUP_DMT)
mode code
Returns
> 0 means supported, 0 means unsupported, < 0 means error
Definition at line 1401 of file vc_vchi_tvservice.c.
References vc_tv_hdmi_mode_supported_id().
{
    return vc_tv_hdmi_mode_supported_id(default_display_number, group, mode);
 }
vc_tv_hdmi_mode_supported_id()
VCHPRE_ int VCHPOST_ vc_tv_hdmi_mode_supported_id (uint32_t display_id, HDMI_RES_GROUP_T group, uint32_t mode)
Definition at line 1393 of file vc_vchi_tvservice.c.
References VCOS_FUNCTION.
Referenced by vc_tv_hdmi_mode_supported().
{
    TV_QUERY_MODE_SUPPORT_PARAM_T param = {group, mode};
    vcos_log_trace("[%s]", VCOS_FUNCTION);
    return tvservice_send_command( VC_TV_QUERY_MODE_SUPPORT, display_id, &param, sizeof(TV_QUERY_MODE_SUPPORT_PARAM_T), 1);
 }
vc_tv_hdmi_power_on_best()
VCHPRE_ int VCHPOST_ vc_tv_hdmi_power_on_best (uint32_t width, uint32_t height, uint32_t frame_rate, HDMI_INTERLACED_T scan_mode, EDID_MODE_MATCH_FLAG_T match_flags)
Use vc_tv_hdmi_power_on_best to power on HDMI at best matched resolution based on passed in parameters. Use HDMI_MODE_MATCH_FRAMERATE if you want to match the frame rate; use HDMI_MODE_MATCH_RESOLUTION if you want to match on screen size; add HDMI_MODE_MATCH_SCANMODE if you want to force interlaced/progressive mode. If no matching mode is found, the native resolution will be used instead.
Parameters
width is the desired minimum screen width
height is the desired minimum screen height
rate is the desired frame rate
scan_mode (HDMI_NONINTERLACED / HDMI_INTERLACED) is the desired scan mode
match flags is the matching flag EDID_MODE_MATCH_FLAG_T
Returns
same as vc_tv_hdmi_power_on_preferred
Definition at line 1143 of file vc_vchi_tvservice.c.
References VCOS_FUNCTION.
{
    vcos_log_trace("[%s]", VCOS_FUNCTION);
    return vc_tv_hdmi_power_on_best_actual(default_display_number, width, height, frame_rate, scan_mode, match_flags, 0);
 }
vc_tv_hdmi_power_on_best_3d()
VCHPRE_ int VCHPOST_ vc_tv_hdmi_power_on_best_3d (uint32_t width, uint32_t height, uint32_t frame_rate, HDMI_INTERLACED_T scan_mode, EDID_MODE_MATCH_FLAG_T match_flags)
Same as above, but tell the TV to enter 3D mode. The TV will go to 2D mode if no suitable 3D mode can be found.
Definition at line 1149 of file vc_vchi_tvservice.c.
References VCOS_FUNCTION.
{
    vcos_log_trace("[%s]", VCOS_FUNCTION);
    return vc_tv_hdmi_power_on_best_actual(default_display_number, width, height, frame_rate, scan_mode, match_flags, 1);
 }
vc_tv_hdmi_power_on_best_3d_id()
VCHPRE_ int VCHPOST_ vc_tv_hdmi_power_on_best_3d_id (uint32_t display_id, uint32_t width, uint32_t height, uint32_t frame_rate, HDMI_INTERLACED_T scan_mode, EDID_MODE_MATCH_FLAG_T match_flags)
Definition at line 1136 of file vc_vchi_tvservice.c.
References VCOS_FUNCTION.
{
    vcos_log_trace("[%s]", VCOS_FUNCTION);
    return vc_tv_hdmi_power_on_best_actual(display_id, width, height, frame_rate, scan_mode, match_flags, 1);
 }
vc_tv_hdmi_power_on_best_id()
VCHPRE_ int VCHPOST_ vc_tv_hdmi_power_on_best_id (uint32_t display_id, uint32_t width, uint32_t height, uint32_t frame_rate, HDMI_INTERLACED_T scan_mode, EDID_MODE_MATCH_FLAG_T match_flags)
Definition at line 1129 of file vc_vchi_tvservice.c.
References VCOS_FUNCTION.
{
    vcos_log_trace("[%s]", VCOS_FUNCTION);
    return vc_tv_hdmi_power_on_best_actual(display_id, width, height, frame_rate, scan_mode, match_flags, 0);
 }
vc_tv_hdmi_power_on_explicit()
VCHPRE_ int VCHPOST_ vc_tv_hdmi_power_on_explicit (HDMI_MODE_T mode, HDMI_RES_GROUP_T group, uint32_t code)
Definition at line 1904 of file vc_vchi_tvservice.c.
References vc_tv_hdmi_power_on_explicit_id().
{
    return vc_tv_hdmi_power_on_explicit_id(default_display_number, mode, group, code);
 }
vc_tv_hdmi_power_on_explicit_id()
VCHPRE_ int VCHPOST_ vc_tv_hdmi_power_on_explicit_id (uint32_t display_id, HDMI_MODE_T mode, HDMI_RES_GROUP_T group, uint32_t code)
Definition at line 1892 of file vc_vchi_tvservice.c.
References HDMI_PROPERTY_3D_STRUCTURE, HDMI_RES_GROUP_CEA, HDMI_RES_GROUP_CEA_3D, HDMI_PROPERTY_PARAM_T::property, vc_tv_hdmi_power_on_explicit_new_id(), and vc_tv_hdmi_set_property_id().
Referenced by vc_tv_hdmi_power_on_explicit().
{
    if (group == HDMI_RES_GROUP_CEA_3D) {
       HDMI_PROPERTY_PARAM_T property;
       property.property = HDMI_PROPERTY_3D_STRUCTURE;
       property.param1 = HDMI_RES_GROUP_CEA;
       property.param2 = 0;
       vc_tv_hdmi_set_property_id(display_id, &property);
       group = HDMI_RES_GROUP_CEA;
    }
    return vc_tv_hdmi_power_on_explicit_new_id(display_id, mode, group, code);
 }
vc_tv_hdmi_power_on_explicit_new()
VCHPRE_ int VCHPOST_ vc_tv_hdmi_power_on_explicit_new (HDMI_MODE_T mode, HDMI_RES_GROUP_T group, uint32_t code)
Use vc_tv_hdmi_power_on_explicit if you want full control over what mode the TV is driven. This function is used, for example, when the host has the EDID and HDMI middleware does not know. If HDMI middleware has knowledge of EDID, the passed in mode is still subject to TV's supported modes
Parameters
mode (HDMI_MODE_HDMI/HDMI_MODE_DVI/HDMI_MODE_3D)
group (HDMI_RES_GROUP_CEA/HDMI_RES_GROUP_DMT)
code either HDMI_CEA_RES_CODE_T or HDMI_DMT_RES_CODE_T
Returns
same as vc_tv_hdmi_power_on_preferred
Definition at line 1186 of file vc_vchi_tvservice.c.
References vc_tv_hdmi_power_on_explicit_new_id().
{
    return vc_tv_hdmi_power_on_explicit_new_id(default_display_number, mode, group, code);
 }
vc_tv_hdmi_power_on_explicit_new_id()
VCHPRE_ int VCHPOST_ vc_tv_hdmi_power_on_explicit_new_id (uint32_t display_id, HDMI_MODE_T mode, HDMI_RES_GROUP_T group, uint32_t code)
Definition at line 1172 of file vc_vchi_tvservice.c.
References code, TV_HDMI_ON_EXPLICIT_PARAM_T::group, TV_HDMI_ON_EXPLICIT_PARAM_T::hdmi_mode, TV_HDMI_ON_EXPLICIT_PARAM_T::mode, and VCOS_FUNCTION.
Referenced by vc_tv_hdmi_power_on_explicit_id(), and vc_tv_hdmi_power_on_explicit_new().
{
    TV_HDMI_ON_EXPLICIT_PARAM_T param;
    int success;
    vcos_log_trace("[%s] mode %d group %d code %d", VCOS_FUNCTION,
          mode, group, code);
    param.hdmi_mode = mode;
    param.group = group;
    param.mode = code;
    success = tvservice_send_command( VC_TV_HDMI_ON_EXPLICIT, display_id, &param, sizeof(TV_HDMI_ON_EXPLICIT_PARAM_T), 1);
    return success;
 }
vc_tv_hdmi_power_on_preferred()
VCHPRE_ int VCHPOST_ vc_tv_hdmi_power_on_preferred (void)
Use vc_tv_hdmi_power_on_preferred if you don't care what resolutions a TV supports and just want to turn on its native resolution. Analogue TV will be powered down if on (same for the following two HDMI power on functions.) If power on is successful, a host application must wait for the power on complete callback before attempting to open the display.
Parameters
none
Returns
single value interpreted as HDMI_RESULT_T (zero means success) if successful, there will be a callback when the power on is complete
Definition at line 1088 of file vc_vchi_tvservice.c.
{
    return vc_tv_hdmi_power_on_preferred_actual(default_display_number, 0);
 }
vc_tv_hdmi_power_on_preferred_3d()
VCHPRE_ int VCHPOST_ vc_tv_hdmi_power_on_preferred_3d (void)
Same as above, but tell the TV to enter 3D mode. The TV will go to 2D mode if the preferred mode doesn't support 3D.
Definition at line 1092 of file vc_vchi_tvservice.c.
{
    return vc_tv_hdmi_power_on_preferred_actual(default_display_number, 1);
 }
vc_tv_hdmi_power_on_preferred_3d_id()
VCHPRE_ int VCHPOST_ vc_tv_hdmi_power_on_preferred_3d_id (uint32_t display_id)
Definition at line 1084 of file vc_vchi_tvservice.c.
{
    return vc_tv_hdmi_power_on_preferred_actual(display_id, 1);
 }
vc_tv_hdmi_power_on_preferred_id()
VCHPRE_ int VCHPOST_ vc_tv_hdmi_power_on_preferred_id (uint32_t display_id)
Definition at line 1080 of file vc_vchi_tvservice.c.
{
    return vc_tv_hdmi_power_on_preferred_actual(display_id, 0);
 }
vc_tv_hdmi_set_attached()
VCHPRE_ int VCHPOST_ vc_tv_hdmi_set_attached (uint32_t attached)
Sets the TV state to attached. Required when hotplug interrupt is not handled by VideoCore.
Parameters
attached non-zero if the TV is attached or zero for unplugged.
Definition at line 1748 of file vc_vchi_tvservice.c.
References vc_tv_hdmi_set_attached_id().
{
    return vc_tv_hdmi_set_attached_id(default_display_number, attached);
 }
vc_tv_hdmi_set_attached_id()
VCHPRE_ int VCHPOST_ vc_tv_hdmi_set_attached_id (uint32_t display_id, uint32_t attached)
Sets whether the TV is attached or unplugged. Required when hotplug interrupt is not handled by VideoCore.
Definition at line 1742 of file vc_vchi_tvservice.c.
References VCOS_FUNCTION.
Referenced by vc_tv_hdmi_set_attached().
 {
    vcos_log_trace("[%s] attached %d", VCOS_FUNCTION, attached);
    return tvservice_send_command(VC_TV_SET_ATTACHED, display_id, &attached, sizeof(uint32_t), 0);
 }
vc_tv_hdmi_set_display_options()
VCHPRE_ int VCHPOST_ vc_tv_hdmi_set_display_options (HDMI_ASPECT_T aspect, uint32_t left_bar_width, uint32_t right_bar_width, uint32_t top_bar_height, uint32_t bottom_bar_height, uint32_t overscan_flags)
vc_tv_hdmi_set_display_options is used to set the active area for HDMI (bar width/height should be set to zero if absent) This information is conveyed in AVI infoframe.
Parameters
aspect ratio HDMI_ASPECT_T
left bar width
right bar width
top bar height
bottom bar height
Returns
whether command was sent successfully (zero means success)
Definition at line 1651 of file vc_vchi_tvservice.c.
References vc_tv_hdmi_set_display_options_id().
{
       return vc_tv_hdmi_set_display_options_id(default_display_number, aspect,
                                             left_bar_width, right_bar_width,
                                             top_bar_height, bottom_bar_height,
                                             overscan_flags);
 }
vc_tv_hdmi_set_display_options_id()
VCHPRE_ int VCHPOST_ vc_tv_hdmi_set_display_options_id (uint32_t display_id, HDMI_ASPECT_T aspect, uint32_t left_bar_width, uint32_t right_bar_width, uint32_t top_bar_height, uint32_t bottom_bar_height, uint32_t overscan_flags)
Definition at line 1632 of file vc_vchi_tvservice.c.
References TV_SET_DISPLAY_OPTIONS_PARAM_T::aspect, TV_SET_DISPLAY_OPTIONS_PARAM_T::bottom_bar_height, TV_SET_DISPLAY_OPTIONS_PARAM_T::horizontal_bar_present, TV_SET_DISPLAY_OPTIONS_PARAM_T::left_bar_width, TV_SET_DISPLAY_OPTIONS_PARAM_T::overscan_flags, TV_SET_DISPLAY_OPTIONS_PARAM_T::right_bar_width, TV_SET_DISPLAY_OPTIONS_PARAM_T::top_bar_height, VC_FALSE, VC_HTOV32, VC_TRUE, VCOS_FUNCTION, and TV_SET_DISPLAY_OPTIONS_PARAM_T::vertical_bar_present.
Referenced by vc_tv_hdmi_set_display_options().
{
    TV_SET_DISPLAY_OPTIONS_PARAM_T param;
    vcos_log_trace("[%s]", VCOS_FUNCTION);
    param.aspect = VC_HTOV32(aspect);
    param.vertical_bar_present = VC_HTOV32((left_bar_width || right_bar_width)? VC_TRUE : VC_FALSE);
    param.left_bar_width = VC_HTOV32(left_bar_width);
    param.right_bar_width = VC_HTOV32(right_bar_width);
    param.horizontal_bar_present = VC_HTOV32((top_bar_height || bottom_bar_height)? VC_TRUE : VC_FALSE);
    param.top_bar_height = VC_HTOV32(top_bar_height);
    param.bottom_bar_height = VC_HTOV32(bottom_bar_height);
    param.overscan_flags = VC_HTOV32(overscan_flags);
    return tvservice_send_command( VC_TV_SET_DISPLAY_OPTIONS, display_id, &param, sizeof(TV_SET_DISPLAY_OPTIONS_PARAM_T), 0);
 }
vc_tv_hdmi_set_hdcp_key()
VCHPRE_ int VCHPOST_ vc_tv_hdmi_set_hdcp_key (const uint8_t * key)
Use vc_tv_hdmi_set_hdcp_key to download HDCP key to HDCP middleware
Parameters
AES encrypted key block (328 bytes)
Returns
single value return indicating queued status Callback indicates the validity of key
Definition at line 1550 of file vc_vchi_tvservice.c.
References vc_tv_hdmi_set_hdcp_key_id().
{
    return vc_tv_hdmi_set_hdcp_key_id(default_display_number, key);
 }
vc_tv_hdmi_set_hdcp_key_id()
VCHPRE_ int VCHPOST_ vc_tv_hdmi_set_hdcp_key_id (uint32_t display_id, const uint8_t * key)
Definition at line 1540 of file vc_vchi_tvservice.c.
References HDCP_KEY_BLOCK_SIZE, TV_HDCP_SET_KEY_PARAM_T::key, VCOS_FUNCTION, and vcos_verify.
Referenced by vc_tv_hdmi_set_hdcp_key().
{
    TV_HDCP_SET_KEY_PARAM_T param;
    vcos_log_trace("[%s]", VCOS_FUNCTION);
    if(!vcos_verify(key))
       return -1;
    memcpy(param.key, key, HDCP_KEY_BLOCK_SIZE);
    return tvservice_send_command( VC_TV_HDCP_SET_KEY, display_id, &param, sizeof(param), 0);
 }
vc_tv_hdmi_set_hdcp_revoked_list()
VCHPRE_ int VCHPOST_ vc_tv_hdmi_set_hdcp_revoked_list (const uint8_t * list, uint32_t num_keys)
Use vc_tv_hdmi_set_hdcp_revoked_list to download SRM revoked list
Parameters
list
size of list (no. of keys)
Returns
single value return indicating queued status Callback indicates the number of keys set (zero if failed, unless you are clearing the list)
Definition at line 1589 of file vc_vchi_tvservice.c.
References vc_tv_hdmi_set_hdcp_revoked_list_id().
{
    return vc_tv_hdmi_set_hdcp_revoked_list_id(default_display_number, list, num_keys);
 }
vc_tv_hdmi_set_hdcp_revoked_list_id()
VCHPRE_ int VCHPOST_ vc_tv_hdmi_set_hdcp_revoked_list_id (uint32_t display_id, const uint8_t * list, uint32_t num_keys)
Definition at line 1567 of file vc_vchi_tvservice.c.
References VC_HTOV32.
Referenced by vc_tv_hdmi_set_hdcp_revoked_list().
{
    TV_HDCP_SET_SRM_PARAM_T param = {VC_HTOV32(num_keys)};
    int success = tvservice_send_command( VC_TV_HDCP_SET_SRM, display_id, &param, sizeof(TV_HDCP_SET_SRM_PARAM_T), 0);
    vcos_log_trace("[%s]", VCOS_FUNCTION);
    if(success == 0 && num_keys && list) { //Set num_keys to zero if we are clearing the list
       //Sent the command, now download the list
       if(tvservice_lock_obtain() == 0)
       {
          success = vchi_bulk_queue_transmit( tvservice_client.client_handle[0],
                                              list,
                                              num_keys * HDCP_KSV_LENGTH,
                                              VCHI_FLAGS_BLOCK_UNTIL_QUEUED,
                                              0 );
          tvservice_lock_release();
       }
       else
          success = -1;
    }
    return success;
 }
vc_tv_hdmi_set_property()
VCHPRE_ int VCHPOST_ vc_tv_hdmi_set_property (const HDMI_PROPERTY_PARAM_T * property)
Sets one of the HDMI properties. HDMI properties persist between HDMI power on/off
Parameters
property [in]
Returns
zero if successful, non-zero otherwise
Definition at line 1765 of file vc_vchi_tvservice.c.
References vc_tv_hdmi_set_property_id().
{
    return vc_tv_hdmi_set_property_id(default_display_number, property);
 }
vc_tv_hdmi_set_property_id()
VCHPRE_ int VCHPOST_ vc_tv_hdmi_set_property_id (uint32_t display_id, const HDMI_PROPERTY_PARAM_T * property)
Sets a property in HDMI output
Definition at line 1755 of file vc_vchi_tvservice.c.
References HDMI_PROPERTY_PARAM_T::param1, HDMI_PROPERTY_PARAM_T::param2, HDMI_PROPERTY_PARAM_T::property, VCOS_FUNCTION, and vcos_verify.
Referenced by vc_tv_hdmi_power_on_explicit_id(), and vc_tv_hdmi_set_property().
{
    HDMI_PROPERTY_PARAM_T _property;
    if(vcos_verify(property)) {
       memcpy(&_property, property, sizeof(_property));
       vcos_log_trace("[%s] property:%d values:%d,%d", VCOS_FUNCTION, property->property, property->param1, property->param2);
       return tvservice_send_command(VC_TV_SET_PROP, display_id, &_property, sizeof(_property), 1);
    }
    return -1;
 }
vc_tv_hdmi_set_spd()
VCHPRE_ int VCHPOST_ vc_tv_hdmi_set_spd (const char * manufacturer, const char * description, HDMI_SPD_TYPE_CODE_T type)
vc_tv_hdmi_set_spd is used to set the SPD infoframe.
Parameters
manufacturer (max. 8 characters)
description (max. 16 characters)
product type HDMI_SPD_TYPE_CODE_T
Returns
whether command was sent successfully (zero means success)
Definition at line 1617 of file vc_vchi_tvservice.c.
References vc_tv_hdmi_set_spd_id().
{
    return vc_tv_hdmi_set_spd_id(default_display_number, manufacturer, description, type);
 }
vc_tv_hdmi_set_spd_id()
VCHPRE_ int VCHPOST_ vc_tv_hdmi_set_spd_id (uint32_t display_id, const char * manufacturer, const char * description, HDMI_SPD_TYPE_CODE_T type)
Definition at line 1604 of file vc_vchi_tvservice.c.
References TV_SET_SPD_PARAM_T::description, TV_SET_SPD_PARAM_T::manufacturer, TV_SPD_DESC_LEN, TV_SPD_NAME_LEN, TV_SET_SPD_PARAM_T::type, VC_HTOV32, VCOS_FUNCTION, and vcos_verify.
Referenced by vc_tv_hdmi_set_spd().
{
    TV_SET_SPD_PARAM_T param;
    vcos_log_trace("[%s]", VCOS_FUNCTION);
    if(!vcos_verify(manufacturer && description))
       return -1;
    memcpy(param.manufacturer, manufacturer, TV_SPD_NAME_LEN);
    memcpy(param.description, description, TV_SPD_DESC_LEN);
    param.type = VC_HTOV32(type);
    return tvservice_send_command( VC_TV_SET_SPD, display_id, &param, sizeof(TV_SET_SPD_PARAM_T), 0);
 }
vc_tv_notification_name()
VCHPRE_ const char* vc_tv_notification_name (VC_HDMI_NOTIFY_T reason)
Converts the notification reason to a string.
Parameters
reason is the notification reason
Returns
The notification reason as a string.
Definition at line 1798 of file vc_vchi_tvservice.c.
References VC_HDMI_ATTACHED, VC_HDMI_CHANGING_MODE, VC_HDMI_DVI, VC_HDMI_HDCP_AUTH, VC_HDMI_HDCP_KEY_DOWNLOAD, VC_HDMI_HDCP_SRM_DOWNLOAD, VC_HDMI_HDCP_UNAUTH, VC_HDMI_HDMI, and VC_HDMI_UNPLUGGED.
 {
    switch (reason)
    {
       case VC_HDMI_UNPLUGGED:
          return "VC_HDMI_UNPLUGGED";
       case VC_HDMI_ATTACHED:
          return "VC_HDMI_ATTACHED";
       case VC_HDMI_DVI:
          return "VC_HDMI_DVI";
       case VC_HDMI_HDMI:
          return "VC_HDMI_HDMI";
       case VC_HDMI_HDCP_UNAUTH:
          return "VC_HDMI_HDCP_UNAUTH";
       case VC_HDMI_HDCP_AUTH:
          return "VC_HDMI_HDCP_AUTH";
       case VC_HDMI_HDCP_KEY_DOWNLOAD:
          return "VC_HDMI_HDCP_KEY_DOWNLOAD";
       case VC_HDMI_HDCP_SRM_DOWNLOAD:
          return "VC_HDMI_HDCP_SRM_DOWNLOAD";
       case VC_HDMI_CHANGING_MODE:
          return "VC_HDMI_CHANGING_MODE";
       default:
          return "VC_HDMI_UNKNOWN";
    }
 }
vc_tv_power_off()
VCHPRE_ int VCHPOST_ vc_tv_power_off (void)
vc_tv_power_off is used to turn off either analogue or HDMI output. If HDMI is powered down, there will be a callback with reason UNPLUGGED (if no cable is attached) or STANDBY (if a cable is attached)
Parameters
none
Returns
whether command is succcessfully sent
Definition at line 1235 of file vc_vchi_tvservice.c.
References vc_tv_power_off_id().
{
    return vc_tv_power_off_id(default_display_number);
 }
vc_tv_power_off_id()
VCHPRE_ int VCHPOST_ vc_tv_power_off_id (uint32_t display_id)
Definition at line 1230 of file vc_vchi_tvservice.c.
References VCOS_FUNCTION.
Referenced by vc_tv_power_off().
{
    vcos_log_trace("[%s]", VCOS_FUNCTION);
    return tvservice_send_command( VC_TV_OFF, display_id, NULL, 0, 0);
 }
vc_tv_register_callback()
VCHPRE_ void VCHPOST_ vc_tv_register_callback (TVSERVICE_CALLBACK_T callback, void * callback_data)
Host applications should call vc_tv_register_callback at the beginning to register a callback function to handle all notifications. See TVSERVICE_CALLBACK_T
Parameters
callback function
callback_data is the context to be passed when function is called
Returns
void
Definition at line 443 of file vc_vchi_tvservice.c.
{
    vcos_assert_msg(callback != NULL, "Use vc_tv_unregister_callback() to remove a callback");
    vcos_log_trace("[%s]", VCOS_FUNCTION);
    if(tvservice_lock_obtain() == 0)
    {
       uint32_t done = 0;
       uint32_t i;
       for(i = 0; (i < TVSERVICE_MAX_CALLBACKS) && !done; i++)
       {
          if(tvservice_client.callbacks[i].notify_fn == NULL)
          {
             tvservice_client.callbacks[i].notify_fn = callback;
             tvservice_client.callbacks[i].notify_data = callback_data;
             done = 1;
          } // if
       } // for
       vcos_assert(done);
       tvservice_lock_release();
    }
 }
vc_tv_sdtv_power_on()
VCHPRE_ int VCHPOST_ vc_tv_sdtv_power_on (SDTV_MODE_T mode, SDTV_OPTIONS_T * options)
vc_tv_sdtv_power_on is used to turn on analogue TV. HDMI will automatically be powered off if on.
Parameters
SDTV mode SDTV_MODE_T
options SDTV_OPTIONS_T
Returns
single value (zero means success) if successful, there will be a callback when the power on is complete
Definition at line 1215 of file vc_vchi_tvservice.c.
{
    return vc_tv_sdtv_power_on_id(default_display_number, mode, options);
 }
vc_tv_sdtv_power_on_id()
VCHPRE_ int VCHPOST_ vc_tv_sdtv_power_on_id (uint32_t display_id, SDTV_MODE_T mode, SDTV_OPTIONS_T * options)
Definition at line 1203 of file vc_vchi_tvservice.c.
{
    TV_SDTV_ON_PARAM_T param;
    int success;
    vcos_log_trace("[%s]", VCOS_FUNCTION);
    param.mode = VC_HTOV32(mode);
    param.aspect = (options)? VC_HTOV32(options->aspect) : VC_HTOV32(SDTV_ASPECT_4_3);
    success = tvservice_send_command( VC_TV_SDTV_ON, display_id, &param, sizeof(TV_SDTV_ON_PARAM_T), 1);
    return success;
 }
vc_tv_show_info()
VCHPRE_ int VCHPOST_ vc_tv_show_info (uint32_t show)
Use vc_tv_show_info to show or hide info screen. Only usable in HDMI at the moment.
Parameters
show (1) or hide (0) info screen
Returns
zero if command is successfully sent
Definition at line 1501 of file vc_vchi_tvservice.c.
References vc_tv_show_info_id().
{
    return vc_tv_show_info_id(default_display_number, show);
 }
vc_tv_show_info_id()
VCHPRE_ int VCHPOST_ vc_tv_show_info_id (uint32_t display_id, uint32_t show)
Definition at line 1495 of file vc_vchi_tvservice.c.
References VC_HTOV32, and VCOS_FUNCTION.
Referenced by vc_tv_show_info().
{
    TV_SHOW_INFO_PARAM_T param = {VC_HTOV32(show)};
    vcos_log_trace("[%s]", VCOS_FUNCTION);
    return tvservice_send_command( VC_TV_SHOW_INFO, display_id, &param, sizeof(TV_SHOW_INFO_PARAM_T), 0);
 }
vc_tv_test_mode_start()
VCHPRE_ int VCHPOST_ vc_tv_test_mode_start (uint32_t colour, TV_TEST_MODE_T test_mode)
Use vc_tv_test_mode_start to generate test signal. At the moment only DVI test signal is supported. HDMI must be powered off before this function is called.
Parameters
24-bit background colour (if applicable)
test mode TV_TEST_MODE_T
Returns
whether command was sent successfully (zero means success)
Definition at line 1679 of file vc_vchi_tvservice.c.
References vc_tv_test_mode_start_id().
{
    return vc_tv_test_mode_start_id(default_display_number, colour, test_mode);
 }
vc_tv_test_mode_start_id()
VCHPRE_ int VCHPOST_ vc_tv_test_mode_start_id (uint32_t display_id, uint32_t colour, TV_TEST_MODE_T test_mode)
Definition at line 1672 of file vc_vchi_tvservice.c.
References VC_HTOV32, and VCOS_FUNCTION.
Referenced by vc_tv_test_mode_start().
{
    TV_TEST_MODE_START_PARAM_T param = {VC_HTOV32(colour), VC_HTOV32(test_mode)};
    vcos_log_trace("[%s]", VCOS_FUNCTION);
    return tvservice_send_command( VC_TV_TEST_MODE_START, display_id, &param, sizeof(TV_TEST_MODE_START_PARAM_T), 0);
 }
vc_tv_test_mode_stop()
VCHPRE_ int VCHPOST_ vc_tv_test_mode_stop (void)
Use vc_tv_test_mode_stop to stop the test signal and power down HDMI.
Parameters
none
Returns
whether command was sent successfully (zero means success)
Definition at line 1699 of file vc_vchi_tvservice.c.
References vc_tv_test_mode_stop_id().
{
    return vc_tv_test_mode_stop_id(default_display_number);
 }
vc_tv_test_mode_stop_id()
VCHPRE_ int VCHPOST_ vc_tv_test_mode_stop_id (uint32_t display_id)
Definition at line 1694 of file vc_vchi_tvservice.c.
References VCOS_FUNCTION.
Referenced by vc_tv_test_mode_stop().
{
    vcos_log_trace("[%s]", VCOS_FUNCTION);
    return tvservice_send_command( VC_TV_TEST_MODE_STOP, display_id, NULL, 0, 0);
 }
vc_tv_unregister_callback()
VCHPRE_ void VCHPOST_ vc_tv_unregister_callback (TVSERVICE_CALLBACK_T callback)
vc_tv_unregister_callback removes a function registered with vc_tv_register_callback from the list of callbacks.
Parameters
callback function
Returns
void
Definition at line 477 of file vc_vchi_tvservice.c.
 {
    vcos_assert(callback != NULL);
    vcos_log_trace("[%s]", VCOS_FUNCTION);
    if(tvservice_lock_obtain() == 0)
    {
       uint32_t done = 0;
       uint32_t i;
       for(i = 0; (i < TVSERVICE_MAX_CALLBACKS) && !done; i++)
       {
          if(tvservice_client.callbacks[i].notify_fn == callback)
          {
             tvservice_client.callbacks[i].notify_fn = NULL;
             tvservice_client.callbacks[i].notify_data = NULL;
             done = 1;
          } // if
       } // for
       vcos_assert(done);
       tvservice_lock_release();
    }
 }
vc_tv_unregister_callback_full()
VCHPRE_ void VCHPOST_ vc_tv_unregister_callback_full (TVSERVICE_CALLBACK_T callback, void * callback_data)
vc_tv_unregister_callback removes a function registered with vc_tv_register_callback from the list of callbacks. In contrast to vc_tv_unregister_callback this one matches not only the function pointer but also the data pointer before removal.
Parameters
callback function
Returns
void
Definition at line 512 of file vc_vchi_tvservice.c.
 {
    vcos_assert(callback != NULL);
    vcos_log_trace("[%s]", VCOS_FUNCTION);
    if(tvservice_lock_obtain() == 0)
    {
       uint32_t done = 0;
       uint32_t i;
       for(i = 0; (i < TVSERVICE_MAX_CALLBACKS) && !done; i++)
       {
          if(tvservice_client.callbacks[i].notify_fn == callback &&
             tvservice_client.callbacks[i].notify_data == callback_data)
          {
             tvservice_client.callbacks[i].notify_fn = NULL;
             tvservice_client.callbacks[i].notify_data = NULL;
             done = 1;
          } // if
       } // for
       vcos_assert(done);
       tvservice_lock_release();
    }
 }
vc_vchi_tv_init()
VCHPRE_ int VCHPOST_ vc_vchi_tv_init (VCHI_INSTANCE_T initialise_instance, VCHI_CONNECTION_T ** connections, uint32_t num_connections)
vc_vchi_tv_init is called at the beginning of the application to initialise the client to TV service
Parameters
initialise_instance is the VCHI instance
array of pointers of connections
number of connections (currently this is always 1
Returns
Zero is successful A negative return value indicates failure (which may mean it has not been started on VideoCore).
Definition at line 225 of file vc_vchi_tvservice.c.
References SDTV_OPTIONS_T_::aspect, HDMI_ASPECT_UNKNOWN, TVSERVICE_HOST_STATE_T::hdmi_options, TVSERVICE_HOST_STATE_T::initialised, TVSERVICE_HOST_STATE_T::lock, TVSERVICE_HOST_STATE_T::num_connections, SDTV_ASPECT_4_3, TVSERVICE_HOST_STATE_T::sdtv_current_mode, SDTV_MODE_OFF, TVSERVICE_HOST_STATE_T::sdtv_options, status, TVSERVICE_CLIENT_NAME, VC_FALSE, VC_TVSERVICE_VER, VCHI_VERSION, vcos_assert, vcos_event_create(), VCOS_FUNCTION, VCOS_LOG_CATEGORY, VCOS_LOG_ERROR, vcos_log_register(), vcos_log_set_level(), vcos_mutex_create(), and VCOS_SUCCESS.
{
    int32_t success;
    uint32_t i;
    VCOS_STATUS_T status;
    VCOS_THREAD_ATTR_T attrs;
    static const HDMI_DISPLAY_OPTIONS_T hdmi_default_display_options =
       {
          HDMI_ASPECT_UNKNOWN,
          VC_FALSE, 0, 0, // No vertical bar information.
          VC_FALSE, 0, 0, // No horizontal bar information.
          0               // No overscan flags.
       };
    TV_ATTACHED_DEVICES_T devices;
    if (tvservice_client.initialised)
      return -2;
    vcos_log_set_level(VCOS_LOG_CATEGORY, VCOS_LOG_ERROR);
    vcos_log_register("tvservice-client", VCOS_LOG_CATEGORY);
    vcos_log_trace("[%s]", VCOS_FUNCTION);
    // record the number of connections
    memset( &tvservice_client, 0, sizeof(TVSERVICE_HOST_STATE_T) );
    tvservice_client.num_connections = num_connections;
    status = vcos_mutex_create(&tvservice_client.lock, "HTV");
    vcos_assert(status == VCOS_SUCCESS);
    status = vcos_event_create(&tvservice_message_available_event, "HTV");
    vcos_assert(status == VCOS_SUCCESS);
    status = vcos_event_create(&tvservice_notify_available_event, "HTV");
    vcos_assert(status == VCOS_SUCCESS);
    //Initialise any other non-zero bits of the TV service state here
    tvservice_client.sdtv_current_mode = SDTV_MODE_OFF;
    tvservice_client.sdtv_options.aspect = SDTV_ASPECT_4_3;
    memcpy(&tvservice_client.hdmi_options, &hdmi_default_display_options, sizeof(HDMI_DISPLAY_OPTIONS_T));
    for (i=0; i < tvservice_client.num_connections; i++) {
       // Create a 'Client' service on the each of the connections
       SERVICE_CREATION_T tvservice_parameters = { VCHI_VERSION(VC_TVSERVICE_VER),
                                                   TVSERVICE_CLIENT_NAME,      // 4cc service code
                                                   connections[i],             // passed in fn ptrs
                                                   0,                          // tx fifo size (unused)
                                                   0,                          // tx fifo size (unused)
                                                   &tvservice_client_callback, // service callback
                                                   &tvservice_message_available_event,  // callback parameter
                                                   VC_TRUE,                    // want_unaligned_bulk_rx
                                                   VC_TRUE,                    // want_unaligned_bulk_tx
                                                   VC_FALSE,                   // want_crc
       };
       SERVICE_CREATION_T tvservice_parameters2 = { VCHI_VERSION(VC_TVSERVICE_VER),
                                                    TVSERVICE_NOTIFY_NAME,     // 4cc service code
                                                    connections[i],            // passed in fn ptrs
                                                    0,                         // tx fifo size (unused)
                                                    0,                         // tx fifo size (unused)
                                                    &tvservice_notify_callback,// service callback
                                                    &tvservice_notify_available_event,  // callback parameter
                                                    VC_FALSE,                  // want_unaligned_bulk_rx
                                                    VC_FALSE,                  // want_unaligned_bulk_tx
                                                    VC_FALSE,                  // want_crc
       };
       //Create the client to normal TV service
       success = vchi_service_open( initialise_instance, &tvservice_parameters, &tvservice_client.client_handle[i] );
       //Create the client to the async TV service (any TV related notifications)
       if (success == 0)
       {
          success = vchi_service_open( initialise_instance, &tvservice_parameters2, &tvservice_client.notify_handle[i] );
          if (success == 0)
          {
             vchi_service_release(tvservice_client.client_handle[i]);
             vchi_service_release(tvservice_client.notify_handle[i]);
          }
          else
          {
             vchi_service_close(tvservice_client.client_handle[i]);
             vcos_log_error("Failed to connect to async TV service: %d", success);
          }
       } else {
          vcos_log_error("Failed to connect to TV service: %d", success);
       }
       if (success != 0)
       {
          while (i > 0)
          {
             --i;
             vchi_service_close(tvservice_client.client_handle[i]);
             vchi_service_close(tvservice_client.notify_handle[i]);
          }
          return -1;
       }
    }
    //Create the notifier task
    vcos_thread_attr_init(&attrs);
    vcos_thread_attr_setstacksize(&attrs, 4096);
    vcos_thread_attr_settimeslice(&attrs, 1);
    status = vcos_thread_create(&tvservice_notify_task, "HTV Notify", &attrs, tvservice_notify_func, &tvservice_client);
    vcos_assert(status == VCOS_SUCCESS);
    tvservice_client.initialised = 1;
    // Now try and find a decent default display ID for backward compatibility
    // Priority is Main LCD, Aux LCD, HDMI0, HDMI1
    // Forcing to INVALID by default is for backward compatibility and is used to
    // flag to the system that we should use old non display id commands even if a
    // newer command is requested. ie new linux app on older firmware that does not
    // support display ID based commands
    default_display_number = INVALID_DISPLAY_ID;
    if (vc_tv_get_attached_devices(&devices) != -1 && devices.num_attached > 0)
    {
       default_display_number = DISPMANX_ID_HDMI1;
       // If only one, use it!
       if (devices.num_attached == 1)
          default_display_number = devices.display_number[0];
       else
       {
          int i;
          for (i=0;i<devices.num_attached;i++)
          {
             // If we find an LCD, use it straight away
             if (devices.display_number[i] == DISPMANX_ID_MAIN_LCD)
             {
                default_display_number = DISPMANX_ID_MAIN_LCD;
                break;
             }
             if (devices.display_number[i] == DISPMANX_ID_AUX_LCD)
             {
                default_display_number = DISPMANX_ID_AUX_LCD;
             }
             // If find HDMI0, if we haven't already selected an LCD, use it but keep searching in case main LCD turns up.
             if (devices.display_number[i] == DISPMANX_ID_HDMI0 && default_display_number != DISPMANX_ID_AUX_LCD)
             {
                default_display_number = DISPMANX_ID_HDMI0;
             }
          }
       }
    }
    vcos_log_trace("TV service initialised");
    return 0;
 }
vc_vchi_tv_stop()
VCHPRE_ void VCHPOST_ vc_vchi_tv_stop (void)
vc_vchi_tv_stop is called to stop the host side of TV service.
Parameters
none
Returns
void
Definition at line 388 of file vc_vchi_tvservice.c.
References TVSERVICE_HOST_STATE_T::initialised, and VCOS_FUNCTION.
{
    // Wait for the current lock-holder to finish before zapping TV service
    uint32_t i;
    if (!tvservice_client.initialised)
       return;
    vcos_log_trace("[%s]", VCOS_FUNCTION);
    if(tvservice_lock_obtain() == 0)
    {
       void *dummy;
       vchi_service_release(tvservice_client.client_handle[0]); // to match the use in tvservice_lock_obtain()
       for (i=0; i < tvservice_client.num_connections; i++) {
          int32_t result;
          vchi_service_use(tvservice_client.client_handle[i]);
          vchi_service_use(tvservice_client.notify_handle[i]);
          result = vchi_service_close(tvservice_client.client_handle[i]);
          vcos_assert( result == 0 );
          result = vchi_service_close(tvservice_client.notify_handle[i]);
          vcos_assert( result == 0 );
       }
       // Unset the initialise flag so no other threads can obtain the lock
       tvservice_client.initialised = 0;
       tvservice_lock_release();
       tvservice_client.to_exit = 1; //Signal to quit
       vcos_event_signal(&tvservice_notify_available_event);
       vcos_thread_join(&tvservice_notify_task, &dummy);
       if(tvservice_client.cea_cache.modes)
          vcos_free(tvservice_client.cea_cache.modes);
       if(tvservice_client.dmt_cache.modes)
          vcos_free(tvservice_client.dmt_cache.modes);
       vcos_mutex_delete(&tvservice_client.lock);
       vcos_event_delete(&tvservice_message_available_event);
       vcos_event_delete(&tvservice_notify_available_event);
    }
 }