VideoCore Library: interface/mmal/openmaxil/mmalomx_parameters.h File Reference
mmalomx_parameters.h File Reference
Functions
OMX_ERRORTYPE mmalomx_parameter_get (MMALOMX_COMPONENT_T *component, OMX_INDEXTYPE nParamIndex, OMX_PTR pParam)
OMX_ERRORTYPE mmalomx_parameter_set (MMALOMX_COMPONENT_T *component, OMX_INDEXTYPE nParamIndex, OMX_PTR pParam)
OMX_ERRORTYPE mmalomx_parameter_extension_index_get (OMX_STRING cParameterName, OMX_INDEXTYPE *pIndex)
Detailed Description
OpenMAX IL adaptation layer for MMAL - Parameters related functions
Definition in file mmalomx_parameters.h.
Function Documentation
mmalomx_parameter_extension_index_get()
OMX_ERRORTYPE mmalomx_parameter_extension_index_get (OMX_STRING cParameterName, OMX_INDEXTYPE * pIndex)
Definition at line 235 of file mmalomx_parameters.c.
References MMAL_FALSE, MMAL_TRUE, MMALOMX_COMPONENT_PREFIX, mmalomx_find_parameter_enum(), name, NULL, OMX_ErrorNone, OMX_ErrorNotImplemented, MMALOMX_PARAM_TRANSLATION_T::omx_id, OMX_IndexVendorStartUnused, MMALOMX_PARAM_TRANSLATION_T::omx_name, vcos_strcasecmp(), and vcos_strncasecmp().
 {
    const MMALOMX_PARAM_TRANSLATION_T *xlat;
    MMAL_BOOL_T config = MMAL_FALSE;
    unsigned int i = 0;
    /* Check we're dealing with our extensions */
    if (!vcos_strncasecmp(cParameterName, MMALOMX_COMPONENT_PREFIX, sizeof(MMALOMX_COMPONENT_PREFIX)-1))
       return OMX_ErrorNotImplemented;
    cParameterName += sizeof(MMALOMX_COMPONENT_PREFIX)-1;
    /* Check if we're dealing with a config or param */
    if (!vcos_strncasecmp(cParameterName, "index.config.", sizeof("index.config.")-1))
       config = MMAL_TRUE;
    if (!config && vcos_strncasecmp(cParameterName, "index.param.", sizeof("index.param.")-1))
       return OMX_ErrorNotImplemented;
    if (config)
       cParameterName += sizeof("index.config.")-1;
    else
       cParameterName += sizeof("index.param.")-1;
    /* Loop through all the */
    while ((xlat = mmalomx_find_parameter_enum(i++)) != NULL)
    {
       const char *name = xlat->omx_name;
       /* We only report vendor extensions */
       if (xlat->omx_id < OMX_IndexVendorStartUnused)
          continue;
       /* Strip out the standard prefix */
       if (config)
       {
          if (!strncmp(name, "OMX_IndexConfigBrcm", sizeof("OMX_IndexConfigBrcm")-1))
             name += sizeof("OMX_IndexConfigBrcm")-1;
          else if (!strncmp(name, "OMX_IndexConfig", sizeof("OMX_IndexConfig")-1))
             name += sizeof("OMX_IndexConfig")-1;
          else continue;
       }
       else
       {
          if (!strncmp(name, "OMX_IndexParamBrcm", sizeof("OMX_IndexParamBrcm")-1))
             name += sizeof("OMX_IndexParamBrcm")-1;
          else if (!strncmp(name, "OMX_IndexParam", sizeof("OMX_IndexParam")-1))
             name += sizeof("OMX_IndexParam")-1;
          else continue;
       }
       /* Compare the last part of the name */
       if (!vcos_strcasecmp(name, cParameterName))
       {
          *pIndex = xlat->omx_id;
          return OMX_ErrorNone;
       }
    }
    return OMX_ErrorNotImplemented;
 }
mmalomx_parameter_get()
OMX_ERRORTYPE mmalomx_parameter_get (MMALOMX_COMPONENT_T * component, OMX_INDEXTYPE nParamIndex, OMX_PTR pParam)
Definition at line 316 of file mmalomx_parameters.c.
References OMX_VIDEO_PARAM_AVCTYPE::nPortIndex, OMX_VIDEO_PARAM_AVCTYPE::nSize, OMX_VIDEO_PARAM_AVCTYPE::nSliceHeaderSpacing, NULL, OMX_ErrorBadParameter, OMX_IndexParamVideoAvc, and PARAM_GET_PORT.
 {
    MMALOMX_PORT_T *port = NULL;
    switch(nParamIndex)
    {
    /* All OMX_IndexParamVideo parameters are only partially implemented
     * and we try and use sensible hard-coded values for the rest. */
    case OMX_IndexParamVideoAvc:
       {
          OMX_VIDEO_PARAM_AVCTYPE *param = (OMX_VIDEO_PARAM_AVCTYPE *)pParam;
          uint32_t profile, level, intraperiod;
          PARAM_GET_PORT(port, component, param->nPortIndex);
          if (param->nSize < sizeof(*param))
             return OMX_ErrorBadParameter;
          memset(&param->nSliceHeaderSpacing, 0,
             param->nSize - offsetof(OMX_VIDEO_PARAM_AVCTYPE, nSliceHeaderSpacing));
          mmalomx_get_video_param(port, &profile, &level, &intraperiod);
          param->eProfile = (OMX_VIDEO_AVCPROFILETYPE)profile;
          param->eLevel = (OMX_VIDEO_AVCLEVELTYPE)level;
          param->nPFrames = intraperiod - 1;
          param->bUseHadamard = OMX_TRUE;
          param->nRefFrames = 1;
          param->nAllowedPictureTypes = OMX_VIDEO_PictureTypeI | OMX_VIDEO_PictureTypeP;
          param->bFrameMBsOnly = OMX_TRUE;
          if (param->eProfile != OMX_VIDEO_AVCProfileBaseline)
             param->bEntropyCodingCABAC = OMX_TRUE;
          param->eLoopFilterMode = OMX_VIDEO_AVCLoopFilterEnable;
       }
       return OMX_ErrorNone;
    case OMX_IndexParamVideoMpeg4:
       {
          OMX_VIDEO_PARAM_MPEG4TYPE *param = (OMX_VIDEO_PARAM_MPEG4TYPE *)pParam;
          uint32_t profile, level, intraperiod;
          PARAM_GET_PORT(port, component, param->nPortIndex);
          if (param->nSize < sizeof(*param))
             return OMX_ErrorBadParameter;
          memset(&param->nSliceHeaderSpacing, 0,
             param->nSize - offsetof(OMX_VIDEO_PARAM_MPEG4TYPE, nSliceHeaderSpacing));
          mmalomx_get_video_param(port, &profile, &level, &intraperiod);
          param->eProfile = (OMX_VIDEO_MPEG4PROFILETYPE)profile;
          param->eLevel = (OMX_VIDEO_MPEG4LEVELTYPE)level;
          param->nPFrames = intraperiod - 1;
          param->bACPred = OMX_TRUE;
          param->nAllowedPictureTypes = OMX_VIDEO_PictureTypeI | OMX_VIDEO_PictureTypeP;
       }
       return OMX_ErrorNone;
    case OMX_IndexParamVideoH263:
       {
          OMX_VIDEO_PARAM_H263TYPE *param = (OMX_VIDEO_PARAM_H263TYPE *)pParam;
          uint32_t profile, level, intraperiod;
          PARAM_GET_PORT(port, component, param->nPortIndex);
          if (param->nSize < sizeof(*param))
             return OMX_ErrorBadParameter;
          memset(&param->nPFrames, 0,
             param->nSize - offsetof(OMX_VIDEO_PARAM_H263TYPE, nPFrames));
          mmalomx_get_video_param(port, &profile, &level, &intraperiod);
          param->eProfile = (OMX_VIDEO_H263PROFILETYPE)profile;
          param->eLevel = (OMX_VIDEO_H263LEVELTYPE)level;
          param->nPFrames = intraperiod - 1;
          param->nAllowedPictureTypes = OMX_VIDEO_PictureTypeI | OMX_VIDEO_PictureTypeP;
       }
       return OMX_ErrorNone;
    case OMX_IndexParamVideoMpeg2:
    case OMX_IndexParamVideoWmv:
    case OMX_IndexParamVideoRv:
       {
          OMX_FORMAT_PARAM_TYPE *param = (OMX_FORMAT_PARAM_TYPE *)pParam;
          PARAM_GET_PORT(port, component, param->common.nPortIndex);
          OMX_U32 offset = offsetof(OMX_PARAM_U32TYPE, nU32);
          if (param->common.nSize > sizeof(port->format_param) ||
              param->common.nSize < offset)
             return OMX_ErrorBadParameter;
          memcpy(&param->common.nU32, &port->format_param.common.nU32,
                 param->common.nSize - offset);
          return OMX_ErrorNone;
       }
    case OMX_IndexParamAudioPcm:
    case OMX_IndexParamAudioAac:
    case OMX_IndexParamAudioMp3:
    case OMX_IndexParamAudioDdp:
       {
          OMX_FORMAT_PARAM_TYPE *param = (OMX_FORMAT_PARAM_TYPE *)pParam;
          PARAM_GET_PORT(port, component, param->common.nPortIndex);
          OMX_U32 offset = offsetof(OMX_PARAM_U32TYPE, nU32);
          if (param->common.nSize > sizeof(port->format_param) ||
              param->common.nSize < offset)
             return OMX_ErrorBadParameter;
          memcpy(&param->common.nU32, &port->format_param.common.nU32,
                 param->common.nSize - offset);
          mmalil_format_to_omx_audio_param(param, NULL, port->mmal->format);
          return OMX_ErrorNone;
       }
    case OMX_IndexParamBrcmPixelAspectRatio:
       {
          OMX_CONFIG_POINTTYPE *param = (OMX_CONFIG_POINTTYPE *)pParam;
          PARAM_GET_PORT(port, component, param->nPortIndex);
          param->nX = port->mmal->format->es->video.par.num;
          param->nY = port->mmal->format->es->video.par.den;
          return OMX_ErrorNone;
       }
    case OMX_IndexParamColorSpace:
       {
          OMX_PARAM_COLORSPACETYPE *param = (OMX_PARAM_COLORSPACETYPE *)pParam;
          PARAM_GET_PORT(port, component, param->nPortIndex);
          param->eColorSpace = mmalil_color_space_to_omx(port->mmal->format->es->video.color_space);
          return OMX_ErrorNone;
       }
    case OMX_IndexConfigCommonOutputCrop:
       {
          OMX_CONFIG_RECTTYPE *param = (OMX_CONFIG_RECTTYPE *)pParam;
          PARAM_GET_PORT(port, component, param->nPortIndex);
          param->nLeft = port->mmal->format->es->video.crop.x;
          param->nTop = port->mmal->format->es->video.crop.y;
          param->nWidth = port->mmal->format->es->video.width;
          if (port->mmal->format->es->video.crop.width)
             param->nWidth = port->mmal->format->es->video.crop.width;
          param->nHeight = port->mmal->format->es->video.height;
          if (port->mmal->format->es->video.crop.height)
             param->nHeight = port->mmal->format->es->video.crop.height;
          return OMX_ErrorNone;
       }
    case OMX_IndexConfigCommonScale:
       {
          OMX_CONFIG_SCALEFACTORTYPE *param = (OMX_CONFIG_SCALEFACTORTYPE *)pParam;
          PARAM_GET_PORT(port, component, param->nPortIndex);
          param->xWidth = param->xHeight = 1<<16;
          if (port->mmal->format->es->video.par.num &&
              port->mmal->format->es->video.par.den)
             param->xWidth = mmal_rational_to_fixed_16_16(port->mmal->format->es->video.par);
          return OMX_ErrorNone;
       }
    default:
       return mmalomx_parameter_get_xlat(component, nParamIndex, pParam);
    }
    return OMX_ErrorNotImplemented;
 }
mmalomx_parameter_set()
OMX_ERRORTYPE mmalomx_parameter_set (MMALOMX_COMPONENT_T * component, OMX_INDEXTYPE nParamIndex, OMX_PTR pParam)
Definition at line 483 of file mmalomx_parameters.c.
References OMX_VIDEO_PARAM_AVCTYPE::nPortIndex, OMX_VIDEO_PARAM_AVCTYPE::nSize, NULL, OMX_ErrorBadParameter, OMX_IndexParamVideoAvc, and PARAM_GET_PORT.
 {
    MMALOMX_PORT_T *port = NULL;
    switch(nParamIndex)
    {
    /* All OMX_IndexParamVideo parameters are only partially implemented */
    case OMX_IndexParamVideoAvc:
       {
          OMX_VIDEO_PARAM_AVCTYPE *param = (OMX_VIDEO_PARAM_AVCTYPE *)pParam;
          PARAM_GET_PORT(port, component, param->nPortIndex);
          if (param->nSize < sizeof(*param))
             return OMX_ErrorBadParameter;
          return mmalomx_set_video_param(port, param->eProfile, param->eLevel,
             param->nPFrames + 1);
       }
    case OMX_IndexParamVideoMpeg4:
       {
          OMX_VIDEO_PARAM_MPEG4TYPE *param = (OMX_VIDEO_PARAM_MPEG4TYPE *)pParam;
          PARAM_GET_PORT(port, component, param->nPortIndex);
          if (param->nSize < sizeof(*param))
             return OMX_ErrorBadParameter;
          return mmalomx_set_video_param(port, param->eProfile, param->eLevel,
             param->nPFrames + 1);
       }
    case OMX_IndexParamVideoH263:
       {
          OMX_VIDEO_PARAM_H263TYPE *param = (OMX_VIDEO_PARAM_H263TYPE *)pParam;
          PARAM_GET_PORT(port, component, param->nPortIndex);
          if (param->nSize < sizeof(*param))
             return OMX_ErrorBadParameter;
          return mmalomx_set_video_param(port, param->eProfile, param->eLevel,
             param->nPFrames + 1);
       }
    case OMX_IndexParamVideoMpeg2:
    case OMX_IndexParamVideoWmv:
    case OMX_IndexParamVideoRv:
       {
          OMX_FORMAT_PARAM_TYPE *param = (OMX_FORMAT_PARAM_TYPE *)pParam;
          OMX_U32 offset = offsetof(OMX_PARAM_U32TYPE, nU32);
          PARAM_GET_PORT(port, component, param->common.nPortIndex);
          if (param->common.nSize > sizeof(port->format_param) ||
              param->common.nSize < offset)
             return OMX_ErrorBadParameter;
          memcpy(&port->format_param.common.nU32, &param->common.nU32,
                 param->common.nSize - offset);
          return OMX_ErrorNone;
       }
    case OMX_IndexParamAudioPcm:
    case OMX_IndexParamAudioAac:
    case OMX_IndexParamAudioMp3:
    case OMX_IndexParamAudioDdp:
       {
          OMX_FORMAT_PARAM_TYPE *param = (OMX_FORMAT_PARAM_TYPE *)pParam;
          OMX_U32 offset = offsetof(OMX_PARAM_U32TYPE, nU32);
          PARAM_GET_PORT(port, component, param->common.nPortIndex);
          if (param->common.nSize > sizeof(port->format_param) ||
              param->common.nSize < offset)
             return OMX_ErrorBadParameter;
          memcpy(&port->format_param.common.nU32, &param->common.nU32,
                 param->common.nSize - offset);
          mmalil_omx_audio_param_to_format(port->mmal->format,
             mmalil_omx_audio_param_index_to_coding(nParamIndex), param);
          mmal_port_format_commit(port->mmal);
          return OMX_ErrorNone;
       }
    case OMX_IndexParamBrcmPixelAspectRatio:
       {
          OMX_CONFIG_POINTTYPE *param = (OMX_CONFIG_POINTTYPE *)pParam;
          PARAM_GET_PORT(port, component, param->nPortIndex);
          port->mmal->format->es->video.par.num = param->nX;
          port->mmal->format->es->video.par.den = param->nY;
          mmal_rational_simplify(&port->mmal->format->es->video.par);
          return mmalil_error_to_omx(mmal_port_format_commit(port->mmal));
       }
    case OMX_IndexParamColorSpace:
       {
          OMX_PARAM_COLORSPACETYPE *param = (OMX_PARAM_COLORSPACETYPE *)pParam;
          PARAM_GET_PORT(port, component, param->nPortIndex);
          port->mmal->format->es->video.color_space = mmalil_omx_color_space_to_mmal(param->eColorSpace);
          return mmalil_error_to_omx(mmal_port_format_commit(port->mmal));
       }
    case OMX_IndexParamBrcmVideoCroppingDisable:
       {
          OMX_CONFIG_PORTBOOLEANTYPE *param = (OMX_CONFIG_PORTBOOLEANTYPE *)pParam;
          PARAM_GET_PORT(port, component, param->nPortIndex);
          port->no_cropping = param->bEnabled;
          return OMX_ErrorNone;
       }
    default:
       return mmalomx_parameter_set_xlat(component, nParamIndex, pParam);
    }
    return OMX_ErrorNotImplemented;
 }