VideoCore Library: interface/vmcs_host/linux/vcfilesys.c File Reference
vcfilesys.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <ctype.h>
#include <unistd.h>
#include <sys/stat.h>
#include <sys/statfs.h>
#include <fcntl.h>
#include <errno.h>
#include <assert.h>
#include <limits.h>
#include "interface/vcos/vcos.h"
#include "vcfilesys_defs.h"
#include "vchost.h"
#include <dirent.h>
#include "vc_fileservice_defs.h"
Classes
struct fs_dir
struct file_info_t
Macros
#define VCOS_LOG_CATEGORY (&hostfs_log_cat)
#define _LARGEFILE_SOURCE
#define _LARGEFILE64_SOURCE
#define _FILE_OFFSET_BITS 64 /* So we get lseek and lseek64 */
#define dirent fs_dirent
#define DEBUG_MINOR(...) vcos_log_info(__VA_ARGS__)
#define DEBUG_MAJOR(...) vcos_log_warn(__VA_ARGS__)
#define FILE_INFO_TABLE_CHUNK_LEN 20
Functions
void vc_hostfs_init (void)
void vc_hostfs_exit (void)
int vc_hostfs_close (int fildes)
long vc_hostfs_lseek (int fildes, long offset, int whence)
int64_t vc_hostfs_lseek64 (int fildes, int64_t offset, int whence)
int vc_hostfs_open (const char *inPath, int vc_oflag)
int vc_hostfs_read (int fildes, void *buf, unsigned int nbyte)
int vc_hostfs_write (int fildes, const void *buf, unsigned int nbyte)
int vc_hostfs_closedir (void *dhandle)
int vc_hostfs_format (const char *path)
int vc_hostfs_freespace (const char *inPath)
int64_t vc_hostfs_freespace64 (const char *inPath)
int vc_hostfs_get_attr (const char *path, fattributes_t *attr)
int vc_hostfs_mkdir (const char *path)
void * vc_hostfs_opendir (const char *dirname)
struct fs_dirent * vc_hostfs_readdir_r (void *dhandle, struct fs_dirent *result)
int vc_hostfs_remove (const char *path)
int vc_hostfs_rename (const char *old, const char *new)
int vc_hostfs_set_attr (const char *path, fattributes_t attr)
int vc_hostfs_setend (int filedes)
int64_t vc_hostfs_totalspace64 (const char *inPath)
int vc_hostfs_totalspace (const char *inPath)
void vc_hostfs_scandisk (const char *path)
int vc_hostfs_chkdsk (const char *path, int fix_errors)
Variables
VCOS_LOG_CAT_T hostfs_log_cat
Macro Definition Documentation
_FILE_OFFSET_BITS
#define _FILE_OFFSET_BITS 64 /* So we get lseek and lseek64 */
Definition at line 36 of file vcfilesys.c.
_LARGEFILE64_SOURCE
#define _LARGEFILE64_SOURCE
Definition at line 34 of file vcfilesys.c.
_LARGEFILE_SOURCE
#define _LARGEFILE_SOURCE
Definition at line 31 of file vcfilesys.c.
DEBUG_MAJOR
#define DEBUG_MAJOR (...) vcos_log_warn(__VA_ARGS__)
Definition at line 80 of file vcfilesys.c.
DEBUG_MINOR
#define DEBUG_MINOR (...) vcos_log_info(__VA_ARGS__)
Definition at line 79 of file vcfilesys.c.
Referenced by vc_hostfs_close(), vc_hostfs_closedir(), vc_hostfs_format(), vc_hostfs_get_attr(), vc_hostfs_init(), vc_hostfs_lseek64(), vc_hostfs_mkdir(), vc_hostfs_opendir(), vc_hostfs_readdir_r(), vc_hostfs_remove(), vc_hostfs_rename(), vc_hostfs_set_attr(), and vc_hostfs_write().
dirent
#define dirent fs_dirent
Definition at line 59 of file vcfilesys.c.
FILE_INFO_TABLE_CHUNK_LEN
#define FILE_INFO_TABLE_CHUNK_LEN 20
Definition at line 106 of file vcfilesys.c.
Referenced by vc_hostfs_init().
VCOS_LOG_CATEGORY
#define VCOS_LOG_CATEGORY (&hostfs_log_cat)
Definition at line 28 of file vcfilesys.c.
Function Documentation
vc_hostfs_chkdsk()
int vc_hostfs_chkdsk (const char * path, int fix_errors)
Definition at line 1125 of file vcfilesys.c.
References void().
 {
    (void)path;
    (void)fix_errors;
    return 0;
 }
vc_hostfs_close()
int vc_hostfs_close (int fildes)
Definition at line 194 of file vcfilesys.c.
References DEBUG_MINOR.
 {
    DEBUG_MINOR("vc_hostfs_close(%d)", fildes);
    return close(fildes);
 }
vc_hostfs_closedir()
int vc_hostfs_closedir (void * dhandle)
Definition at line 501 of file vcfilesys.c.
References DEBUG_MINOR, fs_dir::dhandle, NULL, and void().
 {
    struct fs_dir *fsdir = (struct fs_dir *)dhandle;
    int ret = -1;
    DEBUG_MINOR( "vc_hostfs_closedir(%p)", dhandle );
    if (dhandle && fsdir->dhandle)
    {
       (void)closedir(fsdir->dhandle);
       fsdir->dhandle = NULL;
       free(fsdir);
       ret = 0;
    }
    return ret;
 }
vc_hostfs_exit()
void vc_hostfs_exit (void)
Terminate this library. Clean up resources.
Definition at line 169 of file vcfilesys.c.
References NULL, and vcos_log_unregister().
 {
    vcos_log_unregister(&hostfs_log_cat);
    if (p_file_info_table)
    {
       free(p_file_info_table);
       p_file_info_table = NULL;
    }
 }
vc_hostfs_format()
int vc_hostfs_format (const char * path)
Definition at line 534 of file vcfilesys.c.
References DEBUG_MINOR.
 {
    DEBUG_MINOR("vc_hostfs_format: '%s' not implemented", path);
    return -1;
 }
vc_hostfs_freespace()
int vc_hostfs_freespace (const char * inPath)
Definition at line 556 of file vcfilesys.c.
References vc_hostfs_freespace64().
 {
    int ret;
    int64_t freeSpace =  vc_hostfs_freespace64( inPath );
    // Saturate return value (need this in case we have a large file system)
    if (freeSpace > (int64_t) INT_MAX)
    {
       ret = INT_MAX;
    }
    else
    {
       ret = (int) freeSpace;
    }
    return ret;
 }
vc_hostfs_freespace64()
int64_t vc_hostfs_freespace64 (const char * inPath)
Definition at line 594 of file vcfilesys.c.
Referenced by vc_hostfs_freespace().
 {
    char *path = strdup( inPath );
    int64_t ret;
    struct statfs fsStat;
    // Replace all '\' with '/'
    backslash_to_slash( path );
    ret = (int64_t) statfs( path, &fsStat );
    if (ret == 0)
    {
       ret = fsStat.f_bsize * fsStat.f_bavail;
    }
    else
    {
       ret = -1;
    }
    DEBUG_MINOR( "vc_hostfs_freespace64 for '%s' returning %" PRId64 "", path, ret );
    free( path );
    return ret;
 }
vc_hostfs_get_attr()
int vc_hostfs_get_attr (const char * path, fattributes_t * attr)
Definition at line 636 of file vcfilesys.c.
References ATTR_DIRENT, ATTR_RDONLY, and DEBUG_MINOR.
 {
     struct stat sb;
     DEBUG_MINOR("vc_hostfs_get_attr: '%s'", path );
     *attr = 0;
     if ( stat( path, &sb ) == 0 )
     {
         if ( S_ISDIR( sb.st_mode ))
         {
             *attr |= ATTR_DIRENT;
         }
         if (( sb.st_mode & S_IWUSR  ) == 0 )
         {
             *attr |= ATTR_RDONLY;
         }
         return 0;
     }
     return -1;
 }
vc_hostfs_init()
void vc_hostfs_init (void)
Definition at line 139 of file vcfilesys.c.
References assert(), DEBUG_MINOR, FILE_INFO_TABLE_CHUNK_LEN, NULL, vcos_log_register(), vcos_thread_current(), and vcos_thread_get_name().
 {
    // This hostfs module is not thread safe - it allocaes a block
    // of memory and uses it without any kind of locking.
    //
    // It offers no advantage of stdio, and so most clients should
    // not use it. Arguably FILESYS should use it in order to get
    // the FIFO support.
    const char *thread_name = vcos_thread_get_name(vcos_thread_current());
    if (strcmp(thread_name, "FILESYS") != 0 && strcmp(thread_name, "HFilesys") != 0)
    {
       fprintf(stderr,"%s: vc_hostfs is deprecated. Please use stdio\n",
               vcos_thread_get_name(vcos_thread_current()));
    }
    vcos_log_register("hostfs", &hostfs_log_cat);
    DEBUG_MINOR("init");
    // Allocate memory for the file info table
    p_file_info_table = (file_info_t *)calloc( FILE_INFO_TABLE_CHUNK_LEN, sizeof( file_info_t ) );
    assert( p_file_info_table != NULL );
    if (p_file_info_table)
    {
       file_info_table_len = FILE_INFO_TABLE_CHUNK_LEN;
    }
 }
vc_hostfs_lseek()
long vc_hostfs_lseek (int fildes, long offset, int whence)
Definition at line 219 of file vcfilesys.c.
References vc_hostfs_lseek64().
 {
    return (long) vc_hostfs_lseek64( fildes, (int64_t) offset, whence);
 }
vc_hostfs_lseek64()
int64_t vc_hostfs_lseek64 (int fildes, int64_t offset, int whence)
Definition at line 244 of file vcfilesys.c.
References DEBUG_MINOR.
Referenced by vc_hostfs_lseek().
 {
    DEBUG_MINOR("vc_hostfs_lseek(%d,%" PRId64 ",%d)", fildes, offset, whence);
    if (fildes >= file_info_table_len)
    {
       // File descriptor not in table, so this is an error
       DEBUG_MAJOR("vc_hostfs_lseek: invalid fildes %d", fildes);
       return -1;
    }
    else
    {
       // There is entry in the file info table for this file descriptor, so go
       // ahead and handle the seek
       int64_t read_offset = p_file_info_table[fildes].read_offset;
       if (p_file_info_table[fildes].is_fifo)
       {
          // The Videocore is attempting to seek on a FIFO.  FIFOs don't support seeking
          // but, for the benefit of certain Videocore "streaming" file handlers, we
          // will fake limited FIFO seek functionality by computing where a seek
          // would take us to
          if (whence == SEEK_SET)
          {
             read_offset = offset;
          }
          else if (whence == SEEK_CUR)
          {
             read_offset += offset;
          }
          else
          {
             // seeking to the end of FIFO makes no sense, so this is an error
             DEBUG_MAJOR("vc_hostfs_lseek(%d,%lld,%d): SEEK_END not supported on FIFO", fildes, (long long)offset, whence);
             return -1;
          }
       }
       else
       {
          // File is not a FIFO, so do the seek
          read_offset = lseek64(fildes, offset, whence);
       }
       p_file_info_table[fildes].read_offset = read_offset;
       DEBUG_MINOR("vc_hostfs_lseek returning %" PRId64 ")", read_offset);
       return read_offset;
    }
 }
vc_hostfs_mkdir()
int vc_hostfs_mkdir (const char * path)
Definition at line 677 of file vcfilesys.c.
References DEBUG_MINOR.
 {
     DEBUG_MINOR( "vc_hostfs_mkdir: '%s'",  path );
     if ( mkdir( path, 0777 ) == 0 )
     {
         return 0;
     }
     return -1;
 }
vc_hostfs_open()
int vc_hostfs_open (const char * inPath, int vc_oflag)
Definition at line 312 of file vcfilesys.c.
 {
    char *path = strdup( inPath );
    //char *s;
    int flags = 0, ret=errno;
    struct stat fileStat;
    // Replace all '\' with '/'
    backslash_to_slash( path );
 #if 0
    s = path + strlen( path );
    if (( s - path ) >= 4 )
    {
       if ( strcasecmp( &s[ -4 ], ".vll" ) == 0 )
       {
          // The Videocore is asking for a .vll file. Since it isn't consistent with
          // the case, we convert .vll files to all lowercase.
           "vc_hostfs_open: '%s'", path ;
          s--;    // backup to the last character (*s is on the '\0')
          while (( s >= path ) && ( *s != '/' ))
          {
             *s = tolower( *s );
             s--;
          }
       }
    }
 #endif
    DEBUG_MINOR("vc_hostfs_open: '%s'", path);
    flags = O_RDONLY;
    if (vc_oflag & VC_O_WRONLY)  flags =  O_WRONLY;
    if (vc_oflag & VC_O_RDWR)    flags =  O_RDWR;
    if (vc_oflag & VC_O_APPEND)  flags |= O_APPEND;
    if (vc_oflag & VC_O_CREAT)   flags |= O_CREAT;
    if (vc_oflag & VC_O_TRUNC)   flags |= O_TRUNC;
    if (vc_oflag & VC_O_EXCL)    flags |= O_EXCL;
    //while (*path == '\\') path++; // do not want initial '\'
    if (flags & O_CREAT)
       ret = open(path, flags, S_IRUSR | S_IWUSR );
    else
       ret = open(path, flags );
    if (ret < 0 )
    {
       DEBUG_MINOR("vc_hostfs_open(%s,%d) = %d", path, vc_oflag, ret);
    }
    else
    {
       DEBUG_MINOR("vc_hostfs_open(%s,%d) = %d", path, vc_oflag, ret);
    }
    // If the file was successfully open then initialize its entry in
    // the file info table.  If necessary, we expand the size of the table
    if (ret >= 0)
    {
       // File was successfully opened
       if (ret >= file_info_table_len)
       {
          file_info_t *p_new_file_info_table = p_file_info_table;
          int new_file_info_table_len = file_info_table_len;
          // try and allocate a bigger buffer for the file info table
          new_file_info_table_len += FILE_INFO_TABLE_CHUNK_LEN;
          p_new_file_info_table = calloc( (size_t)new_file_info_table_len, sizeof( file_info_t ) );
          if (p_new_file_info_table == NULL)
          {
             // calloc failed
             DEBUG_MAJOR("vc_hostfs_open: file_info_table calloc failed");
             assert( 0 );
          }
          else
          {
             // calloc successful, so copy data from previous buffer to new buffer,
             // free previous buffer and update ptr and len info
             memcpy( p_new_file_info_table, p_file_info_table, sizeof( file_info_t ) * file_info_table_len );
             free( p_file_info_table );
             p_file_info_table = p_new_file_info_table;
             file_info_table_len = new_file_info_table_len;
          }
       }
       assert( ret < file_info_table_len );
       {
          // initialize this file's entry in the file info table
          p_file_info_table[ret].is_fifo = 0;
          p_file_info_table[ret].read_offset = 0;
       }
       // Check whether the file is a FIFO.  A FIFO does not support seeking
       // but we will fake, to the extent supported by the buffered file system
       // on the Videocore, limited FIFO seek functionality.  This is for the benefit
       // of certain Videocore "streaming" file handlers.
       if (fstat( ret, &fileStat ) != 0)
       {
          DEBUG_MINOR("vc_hostfs_open: fstat failed: %s", strerror(errno));
       }
       else if (S_ISFIFO( fileStat.st_mode ))
       {
          // file is a FIFO, so note its fildes for future reference
          p_file_info_table[ret].is_fifo = 1;
          DEBUG_MINOR("vc_hostfs_open: file with fildes %d is a FIFO", ret);
       }
    }
    free( path );
    return ret;
 }
vc_hostfs_opendir()
void* vc_hostfs_opendir (const char * dirname)
Definition at line 702 of file vcfilesys.c.
References DEBUG_MINOR, fs_dir::dhandle, len, NULL, and fs_dir::pathbuf.
 {
    struct fs_dir *fsdir = NULL;
    DEBUG_MINOR( "vc_hostfs_opendir: '%s'", dirname );
    if (dirname && dirname[0])
    {
       fsdir = (struct fs_dir *)malloc(sizeof(struct fs_dir));
       if (fsdir)
       {
          DIR *dhandle;
          int len = strlen(dirname);
          memcpy(fsdir->pathbuf, dirname, len);
          backslash_to_slash(fsdir->pathbuf);
          /* Remove any trailing slashes */
          while (fsdir->pathbuf[len - 1] == '/')
             len--;
          fsdir->pathbuf[len] = '\0';
          dhandle = opendir(fsdir->pathbuf);
          DEBUG_MINOR( "opendir: '%s' = %p", fsdir->pathbuf, dhandle );
          if (dhandle)
          {
             fsdir->pathlen = len;
             fsdir->dhandle = dhandle;
          }
          else
          {
             free(fsdir);
             fsdir = NULL;
          }
       }
    }
    return fsdir;
 }
vc_hostfs_read()
int vc_hostfs_read (int fildes, void * buf, unsigned int nbyte)
Definition at line 441 of file vcfilesys.c.
 {
    if (fildes >= file_info_table_len)
    {
       // File descriptor not in table, so this is an error
       DEBUG_MAJOR("vc_hostfs_read(%d,%p,%u): invalid fildes", fildes, buf, nbyte);
       return -1;
    }
    else
    {
       // There is entry in the file info table for this file descriptor, so go
       // ahead and handle the read
       int ret = (int) read(fildes, buf, nbyte);
       DEBUG_MINOR("vc_hostfs_read(%d,%p,%u) = %d", fildes, buf, nbyte, ret);
       if (ret > 0)
       {
          p_file_info_table[fildes].read_offset += (long) ret;
       }
       return ret;
    }
 }
vc_hostfs_readdir_r()
struct fs_dirent* vc_hostfs_readdir_r (void * dhandle, struct fs_dirent * result)
Definition at line 765 of file vcfilesys.c.
References ATTR_DIRENT, ATTR_NORMAL, ATTR_RDONLY, dirent::d_name, DEBUG_MINOR, fs_dir::dhandle, NULL, fs_dir::pathbuf, fs_dir::pathlen, and vcos_safe_strcpy().
 {
    struct fs_dir *fsdir = (struct fs_dir *)dhandle;
    DEBUG_MINOR( "vc_hostfs_readdir_r(%p)", fsdir );
    if (fsdir && result)
    {
       struct dirent *dent;
       while ((dent = readdir(fsdir->dhandle)) != NULL)
       {
          struct stat statbuf;
          int ret;
          /* Append the filename, and stat the resulting path */
          fsdir->pathbuf[fsdir->pathlen] = '/';
          vcos_safe_strcpy(fsdir->pathbuf, dent->d_name, sizeof(fsdir->pathbuf), fsdir->pathlen + 1);
          ret = stat(fsdir->pathbuf, &statbuf);
          fsdir->pathbuf[fsdir->pathlen] = '\0';
          if (ret == 0)
          {
             vcos_safe_strcpy(result->d_name, dent->d_name, sizeof(result->d_name), 0);
             result->d_size = (statbuf.st_size <= 0xffffffff) ? (unsigned int)statbuf.st_size : 0xffffffff;
             result->d_attrib = ATTR_NORMAL;
             if ((statbuf.st_mode & S_IWUSR) == 0)
                result->d_attrib |= ATTR_RDONLY;
             if (statbuf.st_mode & S_IFDIR)
                result->d_attrib |= ATTR_DIRENT;
             result->d_creatime = statbuf.st_ctime;
             result->d_modtime = statbuf.st_mtime;
             DEBUG_MINOR( "vc_hostfs_readdir_r() = '%s', %x, %x", result->d_name, result->d_size, result->d_attrib );
             break;
          }
       }
       if (!dent)
       {
          DEBUG_MINOR( "vc_hostfs_readdir_r() = NULL" );
          rewinddir(fsdir->dhandle);
          result = NULL;
       }
    }
    else
    {
       result = NULL;
    }
    return result;
 }
vc_hostfs_remove()
int vc_hostfs_remove (const char * path)
Definition at line 833 of file vcfilesys.c.
References DEBUG_MINOR, and fs_dir::pathbuf.
 {
     char *pathbuf = strdup(path);
     int ret = -1;
     DEBUG_MINOR( "vc_hostfs_remove: '%s'", path );
     if (pathbuf)
     {
        backslash_to_slash(pathbuf);
        if ( unlink( pathbuf ) == 0 )
           ret = 0;
     }
     free(pathbuf);
     return ret;
 }
vc_hostfs_rename()
int vc_hostfs_rename (const char * old, const char * new)
Definition at line 869 of file vcfilesys.c.
References DEBUG_MINOR.
 {
     char *oldbuf = strdup(old);
     char *newbuf = strdup(new);
     int ret = -1;
     DEBUG_MINOR( "vc_hostfs_rename: '%s' to '%s'", old, new );
     if (oldbuf && newbuf)
     {
        backslash_to_slash(oldbuf);
        backslash_to_slash(newbuf);
        if ( rename( oldbuf, newbuf ) == 0 )
           ret = 0;
     }
     if (oldbuf)
        free(oldbuf);
     if (newbuf)
        free(newbuf);
     return ret;
 }
vc_hostfs_scandisk()
void vc_hostfs_scandisk (const char * path)
Definition at line 1101 of file vcfilesys.c.
References void().
 {
    (void)path;
    // not yet implemented
 }
vc_hostfs_set_attr()
int vc_hostfs_set_attr (const char * path, fattributes_t attr)
Definition at line 910 of file vcfilesys.c.
References DEBUG_MINOR, and fs_dir::pathbuf.
 {
    char *pathbuf = strdup(path);
    int ret = -1;
    DEBUG_MINOR( "vc_hostfs_set_attr: '%s', %x", path, attr );
    if (pathbuf)
    {
       mode_t mode = 0;
       struct stat sb;
       backslash_to_slash(pathbuf);
       if ( stat( path, &sb ) == 0 )
       {
          mode = sb.st_mode;
          if ( attr & ATTR_RDONLY )
          {
             mode &= ~S_IWUSR;
          }
          else
          {
             mode |= S_IWUSR;
          }
          /* coverity[toctou] Not doing anything security-relevant here,
           * so the race condition is harmless */
          if ( chmod( path, mode ) == 0 )
             ret = 0;
       }
    }
    if (pathbuf)
       free(pathbuf);
    return ret;
 }
vc_hostfs_setend()
int vc_hostfs_setend (int filedes)
Definition at line 965 of file vcfilesys.c.
 {
     off_t   currPosn;
     if (( currPosn = lseek( filedes, 0, SEEK_CUR )) != (off_t)-1 )
     {
         if ( ftruncate( filedes, currPosn ) == 0 )
         {
             return 0;
         }
     }
    return -1;
 }
vc_hostfs_totalspace()
int vc_hostfs_totalspace (const char * inPath)
Definition at line 1043 of file vcfilesys.c.
References vc_hostfs_totalspace64().
 {
    int ret;
    int64_t totalSpace = vc_hostfs_totalspace64(inPath);
    // Saturate return value (need this in case we have a large file system)
    if (totalSpace > (int64_t) INT_MAX)
    {
       ret = INT_MAX;
    }
    else
    {
       ret = (int) totalSpace;
    }
    return ret;
 }
vc_hostfs_totalspace64()
int64_t vc_hostfs_totalspace64 (const char * inPath)
Definition at line 996 of file vcfilesys.c.
Referenced by vc_hostfs_totalspace().
 {
    char *path = strdup( inPath );
    int64_t ret = -1;
    struct statfs fsStat;
    // Replace all '\' with '/'
    if (path)
    {
       backslash_to_slash( path );
       ret = statfs( path, &fsStat );
       if (ret == 0)
       {
          ret = fsStat.f_bsize * fsStat.f_blocks;
       }
       else
       {
          ret = -1;
       }
    }
    DEBUG_MINOR( "vc_hostfs_totalspace for '%s' returning %" PRId64 "", path, ret );
    if (path)
       free( path );
    return ret;
 }
vc_hostfs_write()
int vc_hostfs_write (int fildes, const void * buf, unsigned int nbyte)
Definition at line 479 of file vcfilesys.c.
References DEBUG_MINOR.
 {
    int ret = (int) write(fildes, buf, nbyte);
    DEBUG_MINOR("vc_hostfs_write(%d,%p,%u) = %d", fildes, buf, nbyte, ret);
    return ret;
 }
Variable Documentation
hostfs_log_cat
VCOS_LOG_CAT_T hostfs_log_cat
Definition at line 68 of file vcfilesys.c.