VideoCore Library: host_applications/linux/apps/hello_pi/libs/vgfont/graphics.c File Reference
graphics.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include "vgfont.h"
#include "graphics_x_private.h"
Classes
struct gx_priv_state_t
Macros
#define ATEXT_FONT_SIZE 12 /*< Default font size (font size can be set with *_ext functions). */
#define MAX_DISPLAY_HANDLES 4
#define CHANGE_LAYER (1<<0)
#define CHANGE_OPACITY (1<<1)
#define CHANGE_DEST (1<<2)
#define CHANGE_SRC (1<<3)
#define CHANGE_MASK (1<<4)
#define CHANGE_XFORM (1<<5)
Functions
void gx_priv_save (GX_CLIENT_STATE_T *state, GRAPHICS_RESOURCE_HANDLE res)
void gx_priv_restore (GX_CLIENT_STATE_T *state)
int32_t graphics_initialise (void)
int32_t graphics_uninitialise (void)
VCOS_STATUS_T gx_create_window (uint32_t screen_id, uint32_t width, uint32_t height, GRAPHICS_RESOURCE_TYPE_T image_type, GRAPHICS_RESOURCE_HANDLE *resource_handle)
int32_t graphics_delete_resource (GRAPHICS_RESOURCE_HANDLE res)
int32_t graphics_update_displayed_resource (GRAPHICS_RESOURCE_HANDLE res, const uint32_t x_offset, const uint32_t y_offset, const uint32_t width, const uint32_t height)
int32_t graphics_resource_fill (GRAPHICS_RESOURCE_HANDLE res, uint32_t x, uint32_t y, uint32_t width, uint32_t height, uint32_t fill_colour)
int32_t graphics_resource_render_text_ext (GRAPHICS_RESOURCE_HANDLE res, const int32_t x, const int32_t y, const uint32_t width, const uint32_t height, const uint32_t fg_colour, const uint32_t bg_colour, const char *text, const uint32_t text_length, const uint32_t text_size)
int32_t graphics_resource_render_text (GRAPHICS_RESOURCE_HANDLE res, const int32_t x, const int32_t y, const uint32_t width, const uint32_t height, const uint32_t fg_colour, const uint32_t bg_colour, const char *text, const uint32_t text_length)
int32_t graphics_get_resource_size (const GRAPHICS_RESOURCE_HANDLE res, uint32_t *w, uint32_t *h)
int32_t graphics_get_resource_type (const GRAPHICS_RESOURCE_HANDLE res, GRAPHICS_RESOURCE_TYPE_T *type)
int32_t graphics_bitblt (const GRAPHICS_RESOURCE_HANDLE src, const uint32_t x, const uint32_t y, const uint32_t width, const uint32_t height, GRAPHICS_RESOURCE_HANDLE dest, const uint32_t x_pos, const uint32_t y_pos)
void gx_priv_flush (GRAPHICS_RESOURCE_HANDLE res)
void gx_priv_colour_to_paint (uint32_t col, VGfloat *rgba)
VCOS_STATUS_T gx_priv_resource_fill (GRAPHICS_RESOURCE_HANDLE res, uint32_t x, uint32_t y, uint32_t width, uint32_t height, uint32_t fill_colour)
VCOS_STATUS_T gx_priv_get_pixels (const GRAPHICS_RESOURCE_HANDLE res, void **p_pixels, GX_RASTER_ORDER_T raster_order)
VCOS_STATUS_T gx_create_pbuffer (uint32_t width, uint32_t height, GRAPHICS_RESOURCE_TYPE_T image_type, GRAPHICS_RESOURCE_HANDLE *resource_handle)
GX_PAINT_T * gx_create_gradient (GRAPHICS_RESOURCE_HANDLE res, uint32_t start_colour, uint32_t end_colour)
void gx_destroy_paint (GRAPHICS_RESOURCE_HANDLE res, GX_PAINT_T *p)
VCOS_STATUS_T gx_fill_gradient (GRAPHICS_RESOURCE_HANDLE dest, uint32_t x, uint32_t y, uint32_t width, uint32_t height, uint32_t radius, GX_PAINT_T *p)
VCOS_STATUS_T gx_graphics_init (const char *font_dir)
int gx_is_double_buffered (void)
int32_t graphics_userblt (GRAPHICS_RESOURCE_TYPE_T src_type, const void *src_data, const uint32_t src_x, const uint32_t src_y, const uint32_t width, const uint32_t height, const uint32_t pitch, GRAPHICS_RESOURCE_HANDLE dest, const uint32_t x_pos, const uint32_t y_pos)
int32_t graphics_resource_text_dimensions (GRAPHICS_RESOURCE_HANDLE resource_handle, const char *text, const uint32_t text_length, uint32_t *width, uint32_t *height)
VCOS_STATUS_T gx_render_arrowhead (GRAPHICS_RESOURCE_HANDLE res, uint32_t tip_x, uint32_t tip_y, int32_t w, int32_t h, GX_PAINT_T *p)
int32_t gx_apply_alpha (GRAPHICS_RESOURCE_HANDLE resource_handle, const uint8_t alpha)
int32_t graphics_resource_set_alpha_per_colour (GRAPHICS_RESOURCE_HANDLE res, const uint32_t colour, const uint8_t alpha)
VCOS_STATUS_T gx_get_pixels (const GRAPHICS_RESOURCE_HANDLE res, void **pixels)
VCOS_STATUS_T gx_get_pixels_in_raster_order (const GRAPHICS_RESOURCE_HANDLE res, void **pixels, GX_RASTER_ORDER_T raster_order)
void gx_free_pixels (const GRAPHICS_RESOURCE_HANDLE res, void *pixels)
VCOS_STATUS_T gx_bind_vg (GX_CLIENT_STATE_T *save, GRAPHICS_RESOURCE_HANDLE res)
void gx_unbind_vg (GX_CLIENT_STATE_T *restore)
GX_CLIENT_STATE_T * gx_alloc_context (void)
void gx_free_context (GX_CLIENT_STATE_T *state)
void gx_convert_colour (uint32_t colour, float *dest)
void gx_priv_init (void)
void gx_priv_destroy (void)
int gx_priv_create_native_window (uint32_t screen_id, uint32_t w, uint32_t h, GRAPHICS_RESOURCE_TYPE_T type, GX_NATIVE_WINDOW_T *win, void **cookie)
void gx_priv_finish_native_window (GRAPHICS_RESOURCE_HANDLE_TABLE_T *res, void *current_update)
void gx_priv_destroy_native_window (GRAPHICS_RESOURCE_HANDLE_TABLE_T *res)
int32_t graphics_get_display_size (const uint16_t display_number, uint32_t *width, uint32_t *height)
int32_t graphics_display_resource (GRAPHICS_RESOURCE_HANDLE res, const uint16_t screen_number, const int16_t z_order, const uint16_t offset_x, const uint16_t offset_y, const uint16_t dest_width, const uint16_t dest_height, const VC_DISPMAN_TRANSFORM_T transform, const uint8_t display)
int32_t graphics_update_start (void)
int32_t graphics_update_end (void)
Variables
VCOS_LOG_CAT_T gx_log_cat
Macro Definition Documentation
ATEXT_FONT_SIZE
#define ATEXT_FONT_SIZE 12 /*< Default font size (font size can be set with *_ext functions). */
Definition at line 40 of file graphics.c.
Referenced by graphics_resource_render_text(), and graphics_resource_text_dimensions().
CHANGE_DEST
#define CHANGE_DEST (1<<2)
Definition at line 1205 of file graphics.c.
CHANGE_LAYER
#define CHANGE_LAYER (1<<0)
Definition at line 1203 of file graphics.c.
Referenced by graphics_display_resource().
CHANGE_MASK
#define CHANGE_MASK (1<<4)
Definition at line 1207 of file graphics.c.
CHANGE_OPACITY
#define CHANGE_OPACITY (1<<1)
Definition at line 1204 of file graphics.c.
CHANGE_SRC
#define CHANGE_SRC (1<<3)
Definition at line 1206 of file graphics.c.
CHANGE_XFORM
#define CHANGE_XFORM (1<<5)
Definition at line 1208 of file graphics.c.
MAX_DISPLAY_HANDLES
#define MAX_DISPLAY_HANDLES 4
Definition at line 1201 of file graphics.c.
Referenced by graphics_get_display_size().
Function Documentation
graphics_bitblt()
int32_t graphics_bitblt (const GRAPHICS_RESOURCE_HANDLE src, const uint32_t x, const uint32_t y, const uint32_t width, const uint32_t height, GRAPHICS_RESOURCE_HANDLE dest, const uint32_t x_pos, const uint32_t y_pos)
Definition at line 537 of file graphics.c.
References GRAPHICS_RESOURCE_HANDLE_TABLE_T::alpha, GRAPHICS_RESOURCE_HEIGHT, GRAPHICS_RESOURCE_WIDTH, GX_LOG, GX_PBUFFER, gx_priv_restore(), gx_priv_save(), GRAPHICS_RESOURCE_HANDLE_TABLE_T::height, GRAPHICS_RESOURCE_HANDLE_TABLE_T::pixmap, GRAPHICS_RESOURCE_HANDLE_TABLE_T::type, GRAPHICS_RESOURCE_HANDLE_TABLE_T::u, vcos_assert, VG_DRAW_IMAGE_MULTIPLY, VG_FILL_PATH, VG_IMAGE_MODE, VG_INVALID_HANDLE, VG_MATRIX_IMAGE_USER_TO_SURFACE, VG_MATRIX_MODE, VG_PAINT_COLOR, VG_STROKE_PATH, vgChildImage(), vgCreatePaint(), vgDestroyImage(), vgDestroyPaint(), vgDrawImage(), vgGetError(), vgGetMatrix(), vgLoadIdentity(), vgLoadMatrix(), vgScale(), vgSeti(), vgSetPaint(), vgSetParameterfv(), vgTranslate(), and GRAPHICS_RESOURCE_HANDLE_TABLE_T::width.
 {
    int rc = -1;
    VGfloat old[9];
    uint32_t w, h;
    VGPaint paint = VG_INVALID_HANDLE;
    GX_CLIENT_STATE_T save;
    int is_child = 0;
    VGImage img = VG_INVALID_HANDLE;
    gx_priv_save(&save, dest);
    if (src->type != GX_PBUFFER)
    {
       vcos_assert(0);
       goto finish;
    }
    // create a child image that contains just the part wanted
    w = width == GRAPHICS_RESOURCE_WIDTH ? src->width : width;
    h = height == GRAPHICS_RESOURCE_HEIGHT ? src->height : height;
    if (x==0 && y==0 &&
        w == src->width &&
        h == src->height)
    {
       img = src->u.pixmap;
    }
    else
    {
       is_child = 1;
       img = vgChildImage(src->u.pixmap, x, y, w, h);
       if (img == VG_INVALID_HANDLE)
       {
          vcos_assert(0);
          goto finish;
       }
    }
    vcos_assert(vgGetError()==0);
    vgSeti(VG_MATRIX_MODE, VG_MATRIX_IMAGE_USER_TO_SURFACE);
    vgGetMatrix(old);
    vgLoadIdentity();
    vgTranslate((VGfloat)x_pos, (VGfloat)(dest->height-y_pos));
    vgScale(1.0, -1.0);
    // Do we have a translucency going on?
    if (src->alpha != 1.0)
    {
       VGfloat colour[4] = {1.0,1.0,1.0,src->alpha};
       paint = vgCreatePaint();
       vgSetParameterfv(paint, VG_PAINT_COLOR, 4, colour);
       vgSeti(VG_IMAGE_MODE, VG_DRAW_IMAGE_MULTIPLY);
       vgSetPaint(paint, VG_STROKE_PATH | VG_FILL_PATH);
    }
    vcos_assert(vgGetError()==0);
    vgDrawImage(img);
    vcos_assert(vgGetError()==0);
    vgLoadMatrix(old);
    int err = vgGetError();
    if (err)
    {
       GX_LOG("vg error %x blitting area", err);
       vcos_assert(0);
       rc = -1;
    }
    else
    {
       rc = 0;
    }
 finish:
    if (paint != VG_INVALID_HANDLE)
       vgDestroyPaint(paint);
    if (is_child)
       vgDestroyImage(img);
    gx_priv_restore(&save);
    return rc;
 }
graphics_delete_resource()
int32_t graphics_delete_resource (GRAPHICS_RESOURCE_HANDLE res)
Definition at line 394 of file graphics.c.
References GX_DISPLAY_T::disp, eglDestroySurface(), eglWaitClient(), GX_PBUFFER, gx_priv_destroy_native_window(), gx_priv_restore(), gx_priv_save(), GX_TRACE, GX_WINDOW, GRAPHICS_RESOURCE_HANDLE_TABLE_T::magic, GRAPHICS_RESOURCE_HANDLE_TABLE_T::pixmap, RES_MAGIC, GRAPHICS_RESOURCE_HANDLE_TABLE_T::surface, GRAPHICS_RESOURCE_HANDLE_TABLE_T::type, GRAPHICS_RESOURCE_HANDLE_TABLE_T::u, vcos_assert, vcos_free(), vgDestroyImage(), and vgGetError().
Referenced by main().
 {
    EGLBoolean result;
    if (!res)
    {
       // let it slide - mimics old behaviour
       return 0;
    }
    GX_TRACE("delete resource @%p", res);
    vcos_assert(res->magic == RES_MAGIC);
    if (res->type == GX_PBUFFER)
    {
       GX_CLIENT_STATE_T save;
       gx_priv_save(&save, res);
       vgDestroyImage(res->u.pixmap);
       vcos_assert(vgGetError() == 0);
       gx_priv_restore(&save);
    }
    GX_TRACE("graphics_delete_resource: calling eglDestroySurface...");
    result = eglDestroySurface(display.disp, res->surface);
    vcos_assert(result);
    GX_TRACE("graphics_delete_resource: calling eglWaitClient...");
    eglWaitClient(); // wait for EGL to finish sorting out its surfaces
    if (res->type == GX_WINDOW)
    {
       GX_TRACE("graphics_delete_resource: calling gx_priv_destroy_native_window...");
       gx_priv_destroy_native_window(res);
    }
    res->magic = ~RES_MAGIC;
    vcos_free(res);
    GX_TRACE("graphics_delete_resource: done");
    return 0;
 }
graphics_display_resource()
int32_t graphics_display_resource (GRAPHICS_RESOURCE_HANDLE res, const uint16_t screen_number, const int16_t z_order, const uint16_t offset_x, const uint16_t offset_y, const uint16_t dest_width, const uint16_t dest_height, const VC_DISPMAN_TRANSFORM_T transform, const uint8_t display)
Definition at line 1431 of file graphics.c.
References CHANGE_LAYER, gx_priv_state_t::current_update, graphics_update_start(), GRAPHICS_RESOURCE_HANDLE_TABLE_T::height, GRAPHICS_RESOURCE_HANDLE_TABLE_T::magic, RES_MAGIC, GRAPHICS_RESOURCE_HANDLE_TABLE_T::transform, vcos_assert, vcos_verify, void(), and GRAPHICS_RESOURCE_HANDLE_TABLE_T::width.
Referenced by main().
 {
    DISPMANX_UPDATE_HANDLE_T update;
    int32_t rc;
    int xform_changed;
    if (!res)
    {
       // mimics old behaviour.
       (void)vcos_verify(0);
       return 0;
    }
    vcos_assert(res->magic == RES_MAGIC);
    xform_changed = transform != res->transform;
    res->transform = transform;
    rc = graphics_update_start();
    update = gx.current_update;
    vcos_assert(rc == 0);
    if (display)
    {
       VC_RECT_T src_rect, dest_rect;
       int32_t src_width = res->width;
       int32_t src_height = res->height;
       uint32_t change_flags = CHANGE_LAYER;
       // has the destination position changed?
       uint32_t w = auto_size(dest_width, res->width);
       uint32_t h = auto_size(dest_height, res->height);
       vcos_assert(screen_number == res->screen_id);
       if (gx.screens[screen_number] == 0)
       {
          vcos_assert(0);
          DISPMANX_DISPLAY_HANDLE_T display_handle;
          gx_priv_open_screen(screen_number, &display_handle);
       }
       if ((offset_x != res->dest.x) ||
           (offset_y != res->dest.y) ||
           (h != res->dest.height) ||
           (w != res->dest.width))
       {
          change_flags |= CHANGE_DEST;
          res->dest.x      = offset_x;
          res->dest.y      = offset_y;
          res->dest.height = h;
          res->dest.width  = w;
       }
       if (xform_changed)
          change_flags |= CHANGE_XFORM;
       vc_dispmanx_rect_set( &src_rect, 0, 0, ((uint32_t)src_width)<<16, ((uint32_t)src_height)<<16 );
       vc_dispmanx_rect_set( &dest_rect, offset_x, offset_y, w, h);
       rc = vc_dispmanx_element_change_attributes(update,
          res->u.native_window.egl_win.element,
          change_flags,
          z_order, /* layer */
          0xff, /* opacity */
          &dest_rect,
          &src_rect,
          0, transform);
       vcos_assert(rc==0);
       gx_priv_flush(res);
    }
    else
    {
       vgFinish();
       eglWaitClient();
       rc = vc_dispmanx_element_change_source(update, res->u.native_window.egl_win.element, 0);
       vcos_assert(rc==0);
    }
    rc = graphics_update_end();
    vcos_assert(rc==0);
    return rc;
 }
graphics_get_display_size()
int32_t graphics_get_display_size (const uint16_t display_number, uint32_t * width, uint32_t * height)
Definition at line 1391 of file graphics.c.
Referenced by deinit(), and main().
 {
    DISPMANX_MODEINFO_T mode_info;
    int32_t success = -1;
    DISPMANX_DISPLAY_HANDLE_T disp;
    vcos_assert(width && height);
    *width = *height = 0;
    if(vcos_verify(display_number < MAX_DISPLAY_HANDLES))
    {
       // TODO Shouldn't this close the display if it wasn't previously open?
       if (gx_priv_open_screen(display_number, &disp) < 0)
       {
          vcos_assert(0);
          return -1;
       }
       success = vc_dispmanx_display_get_info(disp, &mode_info);
       if( success >= 0 )
       {
          *width = mode_info.width;
          *height = mode_info.height;
          vcos_assert(*height > 64);
       }
       else
       {
          vcos_assert(0);
       }
    }
    return success;
 }
graphics_get_resource_size()
int32_t graphics_get_resource_size (const GRAPHICS_RESOURCE_HANDLE res, uint32_t * w, uint32_t * h)
Definition at line 519 of file graphics.c.
References GRAPHICS_RESOURCE_HANDLE_TABLE_T::height, and GRAPHICS_RESOURCE_HANDLE_TABLE_T::width.
Referenced by gx_priv_get_pixels(), and render_subtitle().
 {
    if (w) *w = res->width;
    if (h) *h = res->height;
    return 0;
 }
graphics_get_resource_type()
int32_t graphics_get_resource_type (const GRAPHICS_RESOURCE_HANDLE res, GRAPHICS_RESOURCE_TYPE_T * type)
Definition at line 530 of file graphics.c.
References GRAPHICS_RESOURCE_HANDLE_TABLE_T::restype.
 {
    if (type) *type = res->restype;
    return 0;
 }
graphics_initialise()
int32_t graphics_initialise (void)
Definition at line 285 of file graphics.c.
 {
    // dummy initialisation function. This is typically called
    // early in the day before VLLs are available, and so cannot
    // do anything useful.
    return 0;
 }
graphics_resource_fill()
int32_t graphics_resource_fill (GRAPHICS_RESOURCE_HANDLE res, uint32_t x, uint32_t y, uint32_t width, uint32_t height, uint32_t fill_colour)
Definition at line 454 of file graphics.c.
References gx_priv_resource_fill(), gx_priv_restore(), gx_priv_save(), GRAPHICS_RESOURCE_HANDLE_TABLE_T::height, and VCOS_SUCCESS.
Referenced by main().
 {
    GX_CLIENT_STATE_T save;
    gx_priv_save(&save, res);
    VCOS_STATUS_T st = gx_priv_resource_fill(
       res,
       x, res->height-y-height,
       width, height,
       fill_colour);
    gx_priv_restore(&save);
    return st == VCOS_SUCCESS ? 0 : -1;
 }
graphics_resource_render_text()
int32_t graphics_resource_render_text (GRAPHICS_RESOURCE_HANDLE res, const int32_t x, const int32_t y, const uint32_t width, const uint32_t height, const uint32_t fg_colour, const uint32_t bg_colour, const char * text, const uint32_t text_length)
Definition at line 502 of file graphics.c.
References ATEXT_FONT_SIZE, and graphics_resource_render_text_ext().
 {
    return graphics_resource_render_text_ext(res, x, y, width, height,
                                             fg_colour, bg_colour,
                                             text, text_length,
                                             ATEXT_FONT_SIZE);
 }
graphics_resource_render_text_ext()
int32_t graphics_resource_render_text_ext (GRAPHICS_RESOURCE_HANDLE res, const int32_t x, const int32_t y, const uint32_t width, const uint32_t height, const uint32_t fg_colour, const uint32_t bg_colour, const char * text, const uint32_t text_length, const uint32_t text_size)
Definition at line 476 of file graphics.c.
References gx_priv_render_text(), GRAPHICS_RESOURCE_HANDLE_TABLE_T::height, and VCOS_SUCCESS.
Referenced by graphics_resource_render_text().
 {
    /*
    * FIXME: Not at all optimal - re-renders each time.
    * FIXME: Not UTF-8 safe
    * FIXME: much better caching (or any caching)
    */
    VCOS_STATUS_T rc = gx_priv_render_text(
       &display, res,
       x, res->height-y-text_size, width, height, fg_colour, bg_colour,
       text, text_length, text_size);
    return (rc == VCOS_SUCCESS) ? 0 : -1;
 }
graphics_resource_set_alpha_per_colour()
int32_t graphics_resource_set_alpha_per_colour (GRAPHICS_RESOURCE_HANDLE res, const uint32_t colour, const uint8_t alpha)
Definition at line 1127 of file graphics.c.
References GX_ERROR.
 {
    GX_ERROR("Not implemented yet!");
    return 0;
 }
graphics_resource_text_dimensions()
int32_t graphics_resource_text_dimensions (GRAPHICS_RESOURCE_HANDLE resource_handle, const char * text, const uint32_t text_length, uint32_t * width, uint32_t * height)
Definition at line 1051 of file graphics.c.
References ATEXT_FONT_SIZE, and graphics_resource_text_dimensions_ext().
 {
    return graphics_resource_text_dimensions_ext(resource_handle, text, text_length, width, height, ATEXT_FONT_SIZE);
 }
graphics_uninitialise()
int32_t graphics_uninitialise (void)
Definition at line 294 of file graphics.c.
References vcos_assert.
 {
    int i;
    vcos_assert(inited);
    gx_priv_font_term();
    for (i=0; i<GRAPHICS_RESOURCE_HANDLE_TYPE_MAX; i++)
       if (gx_contexts[i])
          eglDestroyContext(display.disp,gx_contexts[i]);
    eglTerminate(display.disp);
    gx_priv_destroy();
    vcos_log_unregister(&gx_log_cat);
    inited = 0;
    return 0;
 }
graphics_update_displayed_resource()
int32_t graphics_update_displayed_resource (GRAPHICS_RESOURCE_HANDLE res, const uint32_t x_offset, const uint32_t y_offset, const uint32_t width, const uint32_t height)
Definition at line 437 of file graphics.c.
References gx_priv_flush(), gx_priv_restore(), and gx_priv_save().
Referenced by main().
 {
    GX_CLIENT_STATE_T save;
    gx_priv_save(&save, res);
    gx_priv_flush(res);
    gx_priv_restore(&save);
    return 0;
 }
graphics_update_end()
int32_t graphics_update_end (void)
Definition at line 1577 of file graphics.c.
References gx_priv_state_t::current_update, gx_priv_state_t::dispman_start_count, DISPMANX_NO_HANDLE, eglWaitClient(), vc_assert, vc_dispmanx_update_submit_sync(), and vcos_verify.
 {
    int32_t success = -1;
    // make sure you are checking the return value of graphics_update_start
    if(vcos_verify(gx.current_update != DISPMANX_NO_HANDLE))
    {
       //check we are in an update
       if(vcos_verify(gx.dispman_start_count > 0))
       {
          //dec the counter
          gx.dispman_start_count--;
          success = 0;
          //is the counter now 0?
          if( 0 == gx.dispman_start_count )
          {
             eglWaitClient();
             if( vc_dispmanx_update_submit_sync( gx.current_update ) != 0 )
             {
                //error
                success = -1;
                vc_assert( 0 );
             }
          }
       }
    }
    return success;
 }
graphics_update_start()
int32_t graphics_update_start (void)
Definition at line 1539 of file graphics.c.
References gx_priv_state_t::current_update, gx_priv_state_t::dispman_start_count, DISPMANX_NO_HANDLE, vc_assert, and vc_dispmanx_update_start().
Referenced by graphics_display_resource().
 {
    int32_t success = 0;
    //check we are not already in an update
    if ( 0 == gx.dispman_start_count )
    {
       gx.current_update = vc_dispmanx_update_start( 10 );
       if( gx.current_update == DISPMANX_NO_HANDLE )
       {
          //error
          success = -1;
          vc_assert( 0 );
       }
    }
    if( success == 0 )
    {
       //inc the counter
       gx.dispman_start_count++;
    }
    return success;
 }
graphics_userblt()
int32_t graphics_userblt (GRAPHICS_RESOURCE_TYPE_T src_type, const void * src_data, const uint32_t src_x, const uint32_t src_y, const uint32_t width, const uint32_t height, const uint32_t pitch, GRAPHICS_RESOURCE_HANDLE dest, const uint32_t x_pos, const uint32_t y_pos)
Definition at line 994 of file graphics.c.
References status.
 {
    VCOS_STATUS_T status;
    VGImageFormat vg_src_type;
    int bytes_per_pixel;
    GX_CLIENT_STATE_T save;
    status = convert_image_type(src_type, &vg_src_type, &bytes_per_pixel);
    if (status != VCOS_SUCCESS)
       return status;
    gx_priv_save(&save, dest);
    if (dest->type == GX_PBUFFER)
    {
       vgImageSubData(dest->u.pixmap,
                      src_data,
                      pitch,
                      vg_src_type,
                      x_pos, y_pos, width, height);
    }
    else if (dest->type == GX_WINDOW)
    {
       // need to invert this as VG thinks zero is at the bottom
       // while graphics_x thinks it is at the top.
       vgWritePixels((uint8_t*)src_data + pitch*(height-1),
                     -pitch,
                     vg_src_type,
                     x_pos, dest->height-y_pos-height, width, height);
    }
    else
    {
       vcos_assert(0);
    }
    if (vgGetError() == 0)
       status = VCOS_SUCCESS;
    else
    {
       vcos_assert(0);
       status = VCOS_EINVAL;
    }
    gx_priv_restore(&save);
    return status;
 }
gx_alloc_context()
GX_CLIENT_STATE_T* gx_alloc_context (void)
Definition at line 1184 of file graphics.c.
References vcos_calloc().
 {
    GX_CLIENT_STATE_T *ret = vcos_calloc(1,sizeof(*ret), "gx_client_state");
    return ret;
 }
gx_apply_alpha()
int32_t gx_apply_alpha (GRAPHICS_RESOURCE_HANDLE resource_handle, const uint8_t alpha)
Definition at line 1113 of file graphics.c.
References GRAPHICS_RESOURCE_HANDLE_TABLE_T::alpha, GX_PBUFFER, GRAPHICS_RESOURCE_HANDLE_TABLE_T::type, and vcos_assert.
 {
    vcos_assert(resource_handle);
    if (resource_handle->type != GX_PBUFFER)
    {
       vcos_assert(0);
       return -1;
    }
    resource_handle->alpha = 1.0*alpha/255;
    return 0;
 }
gx_bind_vg()
VCOS_STATUS_T gx_bind_vg (GX_CLIENT_STATE_T * save, GRAPHICS_RESOURCE_HANDLE res)
Definition at line 1170 of file graphics.c.
References gx_priv_save(), vcos_assert, VCOS_SUCCESS, and vgGetError().
 {
    gx_priv_save(save, res);
    vcos_assert(vgGetError()==0);
    return VCOS_SUCCESS;
 }
gx_convert_colour()
void gx_convert_colour (uint32_t colour, float * dest)
Definition at line 1195 of file graphics.c.
References gx_priv_colour_to_paint().
 {
    gx_priv_colour_to_paint(colour, dest);
 }
gx_create_gradient()
GX_PAINT_T* gx_create_gradient (GRAPHICS_RESOURCE_HANDLE res, uint32_t start_colour, uint32_t end_colour)
Definition at line 874 of file graphics.c.
References gx_priv_colour_to_paint(), gx_priv_restore(), gx_priv_save(), vcos_assert, VG_INVALID_HANDLE, VG_PAINT_COLOR_RAMP_STOPS, VG_PAINT_TYPE, VG_PAINT_TYPE_LINEAR_GRADIENT, vgCreatePaint(), vgGetError(), vgSetParameterfv(), and vgSetParameteri().
 {
    // holds  the two colour stops (offset,r,g,b,a).
    VGfloat fill_stops[10];
    GX_CLIENT_STATE_T save;
    VGPaint paint = VG_INVALID_HANDLE;
    gx_priv_save(&save, res);
    paint = vgCreatePaint();
    if (!paint)
    {
       gx_priv_restore(&save);
       vcos_log("Could not create paint: vg %d\n", vgGetError());
       vcos_assert(0);
       goto finish;
    }
    fill_stops[0] = 0.0;
    gx_priv_colour_to_paint(start_colour, fill_stops+1);
    fill_stops[5] = 1.0;
    gx_priv_colour_to_paint(end_colour, fill_stops+6);
    vgSetParameteri(paint, VG_PAINT_TYPE, VG_PAINT_TYPE_LINEAR_GRADIENT);
    vgSetParameterfv(paint, VG_PAINT_COLOR_RAMP_STOPS, 5*2, fill_stops);
 finish:
    gx_priv_restore(&save);
    return (GX_PAINT_T*)paint;
 }
gx_create_pbuffer()
VCOS_STATUS_T gx_create_pbuffer (uint32_t width, uint32_t height, GRAPHICS_RESOURCE_TYPE_T image_type, GRAPHICS_RESOURCE_HANDLE * resource_handle)
Definition at line 802 of file graphics.c.
References GX_LOG, status, vcos_calloc(), VCOS_ENOMEM, and VCOS_SUCCESS.
 {
    VCOS_STATUS_T status = VCOS_SUCCESS;
    GRAPHICS_RESOURCE_HANDLE h;
    VGImage image;
    VGImageFormat vg_image_type;
    GX_CLIENT_STATE_T save;
    h = vcos_calloc(1,sizeof(*h), "graphics_x_resource");
    if (!h)
    {
       GX_LOG("%s: no memory for resource", __FUNCTION__);
       return VCOS_ENOMEM;
    }
    status = convert_image_type(image_type, &vg_image_type, NULL);
    if (status != VCOS_SUCCESS)
    {
       vcos_free(h);
       return status;
    }
    h->magic     = RES_MAGIC;
    h->context   = gx_contexts[image_type];
    h->config    = gx_configs[image_type];
    h->alpha     = 1.0;
    h->type      = GX_PBUFFER;
    h->width     = width;
    h->height    = height;
    h->restype   = image_type;
    GX_TRACE("Creating pbuffer surface");
    EGLint attribs[] = {EGL_WIDTH, width, EGL_HEIGHT, height, EGL_NONE};
    h->surface = eglCreatePbufferSurface(display.disp, h->config,
                                         attribs);
    if (!h->surface)
    {
       GX_LOG("Could not create EGL pbuffer surface: 0x%x", eglGetError());
       vcos_free(h);
       return VCOS_EINVAL;
    }
    gx_priv_save(&save, h);
    image = vgCreateImage(vg_image_type, width, height, VG_IMAGE_QUALITY_BETTER);
    if (image == VG_INVALID_HANDLE)
    {
       GX_LOG("Could not create vg image type %d: vg error 0x%x",
              vg_image_type, vgGetError());
       eglDestroySurface(display.disp, h->surface);
       vcos_free(h);
       status = VCOS_ENOMEM;
       goto finish;
    }
    h->u.pixmap  = image;
    // fill it with black
    status = gx_priv_resource_fill(h, 0, 0, width, height, GRAPHICS_RGBA32(0,0,0,0xff));
    vcos_assert(status == VCOS_SUCCESS);
    *resource_handle = h;
 finish:
    gx_priv_restore(&save);
    return status;
 }
gx_create_window()
VCOS_STATUS_T gx_create_window (uint32_t screen_id, uint32_t width, uint32_t height, GRAPHICS_RESOURCE_TYPE_T image_type, GRAPHICS_RESOURCE_HANDLE * resource_handle)
Definition at line 313 of file graphics.c.
References status, and VCOS_SUCCESS.
Referenced by main().
 {
    int rc;
    VCOS_STATUS_T status = VCOS_SUCCESS;
    GRAPHICS_RESOURCE_HANDLE h;
    EGLBoolean egl_result;
    void *cookie;
    GX_CLIENT_STATE_T save;
    if (!gx_contexts[image_type])
    {
       GX_LOG("Invalid image type %d", image_type);
       return VCOS_EINVAL;
    }
    h = vcos_calloc(1,sizeof(*h), "graphics_x_resource");
    if (!h)
    {
       GX_LOG("%s: no memory for resource", __FUNCTION__);
       return VCOS_ENOMEM;
    }
    // now need to get the native window
    rc = gx_priv_create_native_window(screen_id,
                                      width, height, image_type,
                                      &h->u.native_window,
                                      &cookie);
    if (rc < 0)
    {
       GX_LOG("%s: could not create native window", __FUNCTION__);
       status = VCOS_ENOMEM;
       goto fail_create_native_win;
    }
    h->magic = RES_MAGIC;
    h->type  = GX_WINDOW;
    h->alpha = 1.0;
    h->surface = eglCreateWindowSurface(display.disp, gx_configs[image_type], &h->u.native_window.egl_win, NULL);
    if (!h->surface)
    {
       GX_LOG("Could not create window surface: 0x%x", eglGetError());
       status = VCOS_ENOMEM;
       goto fail_win;
    }
    egl_result = eglSurfaceAttrib(display.disp, h->surface,
       EGL_SWAP_BEHAVIOR, EGL_BUFFER_PRESERVED);
    vcos_assert(egl_result);
    h->context   = gx_contexts[image_type];
    h->screen_id = screen_id;
    h->width     = width;
    h->height    = height;
    h->restype   = image_type;
    gx_priv_save(&save, h);
    // fill it with black
    status = gx_priv_resource_fill(h, 0, 0, width, height, GRAPHICS_RGBA32(0,0,0,0xff));
    vcos_assert(status == VCOS_SUCCESS);
    gx_priv_finish_native_window(h, cookie);
    gx_priv_flush(h);
    *resource_handle = h;
    gx_priv_restore(&save);
    return status;
 fail_win:
    gx_priv_destroy_native_window(h);
 fail_create_native_win:
    vcos_free(h);
    return status;
 }
gx_destroy_paint()
void gx_destroy_paint (GRAPHICS_RESOURCE_HANDLE res, GX_PAINT_T * p)
Definition at line 909 of file graphics.c.
References gx_priv_restore(), gx_priv_save(), and vgDestroyPaint().
 {
    GX_CLIENT_STATE_T save;
    VGPaint paint = (VGPaint)p;
    gx_priv_save(&save, res);
    vgDestroyPaint(paint);
    gx_priv_restore(&save);
 }
gx_fill_gradient()
VCOS_STATUS_T gx_fill_gradient (GRAPHICS_RESOURCE_HANDLE dest, uint32_t x, uint32_t y, uint32_t width, uint32_t height, uint32_t radius, GX_PAINT_T * p)
Definition at line 919 of file graphics.c.
References GRAPHICS_RESOURCE_HEIGHT, GRAPHICS_RESOURCE_WIDTH, gx_priv_restore(), gx_priv_save(), GRAPHICS_RESOURCE_HANDLE_TABLE_T::height, status, vcos_assert, VCOS_EINVAL, VCOS_ENOMEM, VCOS_SUCCESS, VG_FILL_PATH, VG_PAINT_LINEAR_GRADIENT, VG_PATH_CAPABILITY_ALL, VG_PATH_DATATYPE_S_32, VG_PATH_FORMAT_STANDARD, vgCreatePath(), vgDestroyPath(), vgDrawPath(), vgGetError(), vgSetPaint(), vgSetParameterfv(), vguRoundRect(), and GRAPHICS_RESOURCE_HANDLE_TABLE_T::width.
 {
    /* Define start and end points of gradient, see OpenVG specification,
       section 9.3.3. */
    VGfloat gradient[4] = {0.0, 0.0, 0.0, 0.0};
    VGPaint paint = (VGPaint)p;
    VGPath path;
    GX_CLIENT_STATE_T save;
    VCOS_STATUS_T status = VCOS_SUCCESS;
    if (!paint)
       return VCOS_EINVAL;
    gx_priv_save(&save, dest);
    if (width == GRAPHICS_RESOURCE_WIDTH)
       width = dest->width;
    if (height == GRAPHICS_RESOURCE_HEIGHT)
       height = dest->height;
    gradient[2] = width;
    vgSetParameterfv(paint, VG_PAINT_LINEAR_GRADIENT, 4, gradient);
    vgSetPaint(paint, VG_FILL_PATH);
    path = vgCreatePath(VG_PATH_FORMAT_STANDARD, VG_PATH_DATATYPE_S_32,
                        1.0, 0.0, 8, 8, VG_PATH_CAPABILITY_ALL);
    if (!path)
    {
       status = VCOS_ENOMEM;
       goto finish;
    }
    vguRoundRect(path, (VGfloat)x, (VGfloat)y, (VGfloat)width, (VGfloat)height,
                 (VGfloat)radius, (VGfloat)radius);
    vgDrawPath(path, VG_FILL_PATH);
    vgDestroyPath(path);
    vcos_assert(vgGetError() == 0);
 finish:
    gx_priv_restore(&save);
    return status;
 }
gx_free_context()
void gx_free_context (GX_CLIENT_STATE_T * state)
Definition at line 1190 of file graphics.c.
 {
    vcos_free(state);
 }
gx_free_pixels()
void gx_free_pixels (const GRAPHICS_RESOURCE_HANDLE res, void * pixels)
Definition at line 1165 of file graphics.c.
References vcos_free().
 {
    vcos_free(pixels);
 }
gx_get_pixels()
VCOS_STATUS_T gx_get_pixels (const GRAPHICS_RESOURCE_HANDLE res, void ** pixels)
Definition at line 1136 of file graphics.c.
References gx_priv_get_pixels(), gx_priv_restore(), gx_priv_save(), GX_TOP_BOTTOM, status, and VCOS_SUCCESS.
 {
    VCOS_STATUS_T status = VCOS_SUCCESS;
    GX_CLIENT_STATE_T save;
    gx_priv_save(&save, res);
    /* Default to top-top-bottom raster scan order */
    status = gx_priv_get_pixels(res, pixels, GX_TOP_BOTTOM);
    gx_priv_restore(&save);
    return status;
 }
gx_get_pixels_in_raster_order()
VCOS_STATUS_T gx_get_pixels_in_raster_order (const GRAPHICS_RESOURCE_HANDLE res, void ** pixels, GX_RASTER_ORDER_T raster_order)
Definition at line 1150 of file graphics.c.
References gx_priv_get_pixels(), gx_priv_restore(), gx_priv_save(), status, and VCOS_SUCCESS.
 {
    VCOS_STATUS_T status = VCOS_SUCCESS;
    GX_CLIENT_STATE_T save;
    gx_priv_save(&save, res);
    status = gx_priv_get_pixels(res, pixels, raster_order);
    gx_priv_restore(&save);
    return status;
 }
gx_graphics_init()
VCOS_STATUS_T gx_graphics_init (const char * font_dir)
Definition at line 971 of file graphics.c.
References gx_priv_save(), and NULL.
Referenced by main().
 {
    GX_CLIENT_STATE_T save;
    VCOS_STATUS_T rc;
    gx_priv_save(&save, NULL);
    rc = gx_priv_initialise();
    if (rc == VCOS_SUCCESS)
       rc = gx_priv_font_init(font_dir);
    gx_priv_restore(&save);
    return rc;
 }
gx_is_double_buffered()
int gx_is_double_buffered (void)
Definition at line 988 of file graphics.c.
 {
    return 1;
 }
gx_priv_colour_to_paint()
void gx_priv_colour_to_paint (uint32_t col, VGfloat * rgba)
Map a colour, which the client will have supplied in RGB888.
Definition at line 641 of file graphics.c.
References ALPHA_888_MASK, B_888_MASK, G_888_MASK, and R_888_MASK.
Referenced by gx_convert_colour(), gx_create_gradient(), and gx_priv_resource_fill().
 {
    // with OpenVG we use RGB order.
    rgba[0] = ((VGfloat)((col & R_888_MASK) >> 16 )) / 0xff;
    rgba[1] = ((VGfloat)((col & G_888_MASK) >> 8 )) / 0xff;
    rgba[2] = ((VGfloat)((col & B_888_MASK) >> 0 )) / 0xff;
    rgba[3] = ((VGfloat)((col & ALPHA_888_MASK) >> 24)) / 0xff;
 }
gx_priv_create_native_window()
int gx_priv_create_native_window (uint32_t screen_id, uint32_t w, uint32_t h, GRAPHICS_RESOURCE_TYPE_T type, GX_NATIVE_WINDOW_T * win, void ** cookie)
Create a native window for a surface.
Parameters
screen_id
w width of the window
h height of the window
type color/raster format of the resource
win upon successful return, holds a handle to the native window
cookie
Returns
VCOS_SUCCESS on success, or error code.
Definition at line 1286 of file graphics.c.
References NULL.
 {
    int rc;
    DISPMANX_DISPLAY_HANDLE_T dispmanx_display;
    VC_RECT_T dst_rect;
    VC_RECT_T src_rect;
    DISPMANX_UPDATE_HANDLE_T current_update;
    *cookie = NULL;
    rc = gx_priv_open_screen(screen_id, &dispmanx_display);
    if (rc < 0)
    {
       GX_LOG("Could not open display %d", screen_id);
       goto fail_screen;
    }
    current_update = vc_dispmanx_update_start(0);
    if (!current_update)
    {
       GX_LOG("Could not start update on screen %d", screen_id);
       goto fail_update;
    }
    src_rect.x = src_rect.y = 0;
    src_rect.width = w << 16;
    src_rect.height = h << 16;
    dst_rect.x = dst_rect.y = 0;
    dst_rect.width = dst_rect.height = 1;
    win->egl_win.width = w;
    win->egl_win.height = h;
    VC_DISPMANX_ALPHA_T alpha;
    memset(&alpha, 0x0, sizeof(VC_DISPMANX_ALPHA_T));
    alpha.flags = DISPMANX_FLAGS_ALPHA_FROM_SOURCE;
    DISPMANX_CLAMP_T clamp;
    memset(&clamp, 0x0, sizeof(DISPMANX_CLAMP_T));
    win->egl_win.element = vc_dispmanx_element_add(current_update, dispmanx_display,
       0 /* layer */, &dst_rect,
       0 /* src */, &src_rect,
       DISPMANX_PROTECTION_NONE,
       &alpha /* alpha */,
       &clamp /* clamp */,
       0 /* transform */);
    if ( !win->egl_win.element )
    {
       GX_LOG("Could not add element %dx%d",w,h);
       vc_dispmanx_update_submit_sync(current_update);
       rc = -1;
    }
    // have to pass back the update so it can be completed *After* the
    // window has been initialised (filled with background colour).
    *cookie = (void*)current_update;
    return 0;
 fail_update:
    gx_priv_release_screen(screen_id);
 fail_screen:
    return rc;
 }
gx_priv_destroy()
void gx_priv_destroy (void)
add documentation
Definition at line 1232 of file graphics.c.
References gx_priv_state_t::lock, and vcos_mutex_delete().
 {
    vcos_mutex_delete(&gx.lock);
 }
gx_priv_destroy_native_window()
void gx_priv_destroy_native_window (GRAPHICS_RESOURCE_HANDLE_TABLE_T * res)
Destroy native window bound to surface.
Parameters
res Handle to surface.
Definition at line 1363 of file graphics.c.
References GX_NATIVE_WINDOW_T::egl_win, EGL_DISPMANX_WINDOW_T::element, GRAPHICS_RESOURCE_HANDLE_TABLE_T::native_window, GRAPHICS_RESOURCE_HANDLE_TABLE_T::u, vc_dispmanx_element_remove(), vc_dispmanx_update_start(), vc_dispmanx_update_submit_sync(), and vcos_assert.
Referenced by graphics_delete_resource().
 {
    DISPMANX_UPDATE_HANDLE_T current_update;
    if((current_update = vc_dispmanx_update_start(0)) != 0)
    {
       int ret = vc_dispmanx_element_remove(current_update, res->u.native_window.egl_win.element);
       vcos_assert(ret == 0);
       ret = vc_dispmanx_update_submit_sync(current_update);
       vcos_assert(ret == 0);
    }
    gx_priv_release_screen(res->screen_id);
 }
gx_priv_finish_native_window()
void gx_priv_finish_native_window (GRAPHICS_RESOURCE_HANDLE_TABLE_T * res, void * cookie)
Called after the EGL/VG initialisation of a window has completed following its creation.
Parameters
res ???
cookie ???
Definition at line 1356 of file graphics.c.
References vc_dispmanx_update_submit_sync().
 {
    vc_dispmanx_update_submit_sync((DISPMANX_UPDATE_HANDLE_T)current_update);
 }
gx_priv_flush()
void gx_priv_flush (GRAPHICS_RESOURCE_HANDLE res)
Flush a surface.
Parameters
res Handle to surface.
Definition at line 630 of file graphics.c.
References GX_DISPLAY_T::disp, eglSwapBuffers(), GRAPHICS_RESOURCE_HANDLE_TABLE_T::surface, and vcos_assert.
Referenced by graphics_update_displayed_resource().
 {
    EGLBoolean result;
    result = eglSwapBuffers(display.disp, res->surface);
    vcos_assert(result);
 }
gx_priv_get_pixels()
VCOS_STATUS_T gx_priv_get_pixels (const GRAPHICS_RESOURCE_HANDLE res, void ** p_pixels, GX_RASTER_ORDER_T raster_order)
Definition at line 677 of file graphics.c.
References graphics_get_resource_size(), GRAPHICS_RESOURCE_RGB565, GRAPHICS_RESOURCE_RGB888, GRAPHICS_RESOURCE_RGBA32, GX_LOG, GX_TOP_BOTTOM, GX_TRACE, GRAPHICS_RESOURCE_HANDLE_TABLE_T::restype, status, vcos_assert, VCOS_EINVAL, VCOS_ENOMEM, vcos_malloc(), VCOS_SUCCESS, VG_sABGR_8888, VG_sBGR_565, VG_sXBGR_8888, vgGetError(), and vgReadPixels().
Referenced by gx_get_pixels(), and gx_get_pixels_in_raster_order().
 {
    VCOS_STATUS_T status = VCOS_SUCCESS;
    void *pixels, *dest;
    uint32_t width, height;
    int data_size, pitch;
    VGImageFormat image_format;
    if (!p_pixels)
    {
       status = VCOS_EINVAL;
       goto finish;
    }
    GX_TRACE("%s: res %p", __FUNCTION__, res);
    graphics_get_resource_size(res, &width, &height);
    /* FIXME: implement e.g. gx_get_pitch */
    switch (res->restype)
    {
       case GRAPHICS_RESOURCE_RGB565:
          pitch = ((width + 31)&(~31)) << 1;
          break;
       case GRAPHICS_RESOURCE_RGB888:
       case GRAPHICS_RESOURCE_RGBA32:
          pitch = ((width + 31)&(~31)) << 2;
          break;
       default:
       {
          GX_LOG("Unsupported pixel format");
          status = VCOS_EINVAL;
          goto finish;
       }
    }
    data_size = pitch * height;
    /* NB: vgReadPixels requires that the data pointer is aligned, but does not
       require the stride to be aligned. Most implementations probably will
       require that as well though... */
    pixels = vcos_malloc(data_size, "gx_get_pixels data");
    if (!pixels)
    {
       GX_LOG("Could not allocate %d bytes for vgReadPixels", data_size);
       status = VCOS_ENOMEM;
       goto finish;
    }
    /* FIXME: introduce e.g. GX_COLOR_FORMAT and mapping to VGImageFormat... */
    /* Hand out image data formatted to match OpenGL RGBA format.
     */
    switch (res->restype)
    {
       case GRAPHICS_RESOURCE_RGB565:
          image_format = VG_sBGR_565;
          break;
       case GRAPHICS_RESOURCE_RGB888:
          image_format = VG_sXBGR_8888;
          break;
       case GRAPHICS_RESOURCE_RGBA32:
          image_format = VG_sABGR_8888;
          break;
       default:
       {
          GX_LOG("Unsupported pixel format");
          status = VCOS_EINVAL;
          goto finish;
       }
    }
    /* VG raster order is bottom-to-top */
    if (raster_order == GX_TOP_BOTTOM)
    {
       dest = ((uint8_t*)pixels)+(pitch*(height-1));
       pitch = -pitch;
    }
    else
    {
       dest = pixels;
    }
    vgReadPixels(dest, pitch, image_format, 0, 0, width, height);
    vcos_assert(vgGetError() == 0);
    *p_pixels = pixels;
 finish:
    return status;
 }
gx_priv_init()
void gx_priv_init (void)
add documentation
Definition at line 1227 of file graphics.c.
References gx_priv_state_t::lock, NULL, and vcos_mutex_create().
 {
    vcos_mutex_create(&gx.lock,NULL);
 }
gx_priv_resource_fill()
VCOS_STATUS_T gx_priv_resource_fill (GRAPHICS_RESOURCE_HANDLE res, uint32_t x, uint32_t y, uint32_t width, uint32_t height, uint32_t fill_colour)
Fill an area of a surface with a fixed colour.
Definition at line 652 of file graphics.c.
References GX_LOG, gx_priv_colour_to_paint(), vcos_assert, VCOS_SUCCESS, VG_CLEAR_COLOR, VG_FALSE, VG_SCISSORING, vgClear(), vgGetError(), vgSetfv(), and vgSeti().
Referenced by graphics_resource_fill().
 {
    VGfloat vg_clear_colour[4];
    gx_priv_colour_to_paint(fill_colour, vg_clear_colour);
    vgSeti(VG_SCISSORING, VG_FALSE);
    vgSetfv(VG_CLEAR_COLOR, 4, vg_clear_colour);
    vgClear(x, y, width, height);
    int err = vgGetError();
    if (err)
    {
       GX_LOG("vg error %x filling area", err);
       vcos_assert(0);
    }
    return VCOS_SUCCESS;
 }
gx_priv_restore()
void gx_priv_restore (GX_CLIENT_STATE_T * state)
Restore current EGL client state.
Parameters
state the EGL client state to restore.
Definition at line 255 of file graphics.c.
Referenced by graphics_bitblt(), graphics_delete_resource(), graphics_resource_fill(), graphics_update_displayed_resource(), gx_create_gradient(), gx_destroy_paint(), gx_fill_gradient(), gx_get_pixels(), gx_get_pixels_in_raster_order(), gx_render_arrowhead(), and gx_unbind_vg().
 {
    EGLBoolean egl_result;
    GX_TRACE("gx_priv_restore: eglMakeCurrent: %s, res %x draw_surface %x, surface %x, cxt %x", vcos_thread_get_name(vcos_thread_current()),
       (uint32_t)state->res, (uint32_t)state->draw_surface, (uint32_t)state->read_surface, (uint32_t)state->context);
    // disconnect our thread from this context, so we other threads can use it via
    // this API
    egl_result = eglMakeCurrent(display.disp, EGL_NO_SURFACE, EGL_NO_SURFACE, EGL_NO_CONTEXT);
    vcos_assert(egl_result);
    // now return to the client's API binding
    egl_result = eglBindAPI(state->api);
    vcos_assert(egl_result);
    egl_result = eglMakeCurrent(display.disp, state->draw_surface, state->read_surface, state->context);
    vcos_assert(egl_result);
    if (state->res) state->res->context_bound = 0;
    vcos_mutex_unlock(&lock);
 }
gx_priv_save()
void gx_priv_save (GX_CLIENT_STATE_T * state, GRAPHICS_RESOURCE_HANDLE res)
Save current EGL client state.
Parameters
state upon return, holds the saved EGL client state.
res handle to the surface the EGL client state belongs to (may be NULL).
Definition at line 222 of file graphics.c.
Referenced by graphics_bitblt(), graphics_delete_resource(), graphics_resource_fill(), graphics_resource_text_dimensions_ext(), graphics_update_displayed_resource(), gx_bind_vg(), gx_create_gradient(), gx_destroy_paint(), gx_fill_gradient(), gx_get_pixels(), gx_get_pixels_in_raster_order(), gx_graphics_init(), and gx_render_arrowhead().
 {
    EGLBoolean egl_result;
    vcos_assert(res == NULL || (res->magic == RES_MAGIC));
    vcos_assert(res == NULL || !res->context_bound);
    state->context      = eglGetCurrentContext();
    state->api          = eglQueryAPI();
    state->read_surface = eglGetCurrentSurface(EGL_READ);
    state->draw_surface = eglGetCurrentSurface(EGL_DRAW);
    state->res = res;
    vcos_assert(state->api); // should never be anything other than VG or GL
    vcos_mutex_lock(&lock);
    egl_result = eglBindAPI(EGL_OPENVG_API);
    vcos_assert(egl_result);
    if (res)
    {
       GX_TRACE("gx_priv_save: eglMakeCurrent: %s, res %x surface %x, cxt %x", vcos_thread_get_name(vcos_thread_current()),
          (uint32_t)res, (uint32_t)res->surface, (uint32_t)res->context);
       egl_result = eglMakeCurrent(display.disp, res->surface,
                                   res->surface, res->context);
       vcos_assert(egl_result);
       res->context_bound = 1;
    }
 }
gx_render_arrowhead()
VCOS_STATUS_T gx_render_arrowhead (GRAPHICS_RESOURCE_HANDLE res, uint32_t tip_x, uint32_t tip_y, int32_t w, int32_t h, GX_PAINT_T * p)
Definition at line 1061 of file graphics.c.
References gx_priv_restore(), gx_priv_save(), status, vcos_assert, VCOS_EINVAL, VCOS_ENOMEM, VCOS_SUCCESS, VG_FILL_PATH, VG_PAINT_LINEAR_GRADIENT, VG_PATH_CAPABILITY_ALL, VG_PATH_DATATYPE_S_32, VG_PATH_FORMAT_STANDARD, vgCreatePath(), vgDestroyPath(), vgDrawPath(), vgGetError(), vgSetPaint(), vgSetParameterfv(), and vguPolygon().
 {
    VGfloat gradient[4];
    VGPaint paint = (VGPaint)p;
    VGPath path;
    VCOS_STATUS_T status = VCOS_SUCCESS;
    GX_CLIENT_STATE_T save;
    gx_priv_save(&save, res);
    if (!paint)
    {
       vcos_assert(0);
       status = VCOS_EINVAL;
       goto finish;
    }
    gradient[0] = 0.0; gradient[1] = 0.0;
    gradient[2] = w; gradient[2] = 0.0;
    vgSetParameterfv(paint, VG_PAINT_LINEAR_GRADIENT, 4, gradient);
    vgSetPaint(paint, VG_FILL_PATH);
    path = vgCreatePath(VG_PATH_FORMAT_STANDARD, VG_PATH_DATATYPE_S_32,
                        1.0, 0.0, 8, 8, VG_PATH_CAPABILITY_ALL);
    if (!path)
    {
       status = VCOS_ENOMEM;
       goto finish;
    }
    VGfloat points[] = {
       (VGfloat)tip_x, (VGfloat)tip_y,
       (VGfloat)tip_x + w, (VGfloat)tip_y + h/2,
       (VGfloat)tip_x + w, (VGfloat)tip_y - h/2,
    };
    vguPolygon(path, points, 3, 1);
    vgDrawPath(path, VG_FILL_PATH);
    vgDestroyPath(path);
    vcos_assert(vgGetError()==0);
 finish:
    gx_priv_restore(&save);
    return status;
 }
gx_unbind_vg()
void gx_unbind_vg (GX_CLIENT_STATE_T * restore)
Unbind VG
Definition at line 1178 of file graphics.c.
References gx_priv_restore().
 {
    gx_priv_restore(restore);
 }
Variable Documentation
gx_log_cat
VCOS_LOG_CAT_T gx_log_cat
Definition at line 283 of file graphics.c.