VideoCore Library: opensrc/helpers/libfdt/libfdt_internal.h File Reference
libfdt_internal.h File Reference
#include <fdt.h>
Macros
#define FDT_ALIGN(x, a) (((x) + (a) - 1) & ~((a) - 1))
#define FDT_TAGALIGN(x) (FDT_ALIGN((x), FDT_TAGSIZE))
#define FDT_RO_PROBE(fdt)
#define FDT_SW_MAGIC (~FDT_MAGIC)
Functions
int32_t fdt_ro_probe_ (const void *fdt)
int fdt_check_node_offset_ (const void *fdt, int offset)
int fdt_check_prop_offset_ (const void *fdt, int offset)
const char * fdt_find_string_ (const char *strtab, int tabsize, const char *s)
int fdt_node_end_offset_ (void *fdt, int nodeoffset)
Macro Definition Documentation
FDT_ALIGN
#define FDT_ALIGN (x, a) (((x) + (a) - 1) & ~((a) - 1))
Definition at line 10 of file libfdt_internal.h.
Referenced by fdt_create_with_flags().
FDT_RO_PROBE
#define FDT_RO_PROBE (fdt)
Value:
{                           \
        int32_t totalsize_;             \
        if ((totalsize_ = fdt_ro_probe_(fdt)) < 0)  \
            return totalsize_;          \
    }
Definition at line 14 of file libfdt_internal.h.
Referenced by fdt_get_mem_rsv(), fdt_get_path(), fdt_move(), fdt_node_offset_by_compatible(), fdt_node_offset_by_phandle(), fdt_node_offset_by_prop_value(), fdt_open_into(), fdt_overlay_apply(), fdt_path_offset_namelen(), fdt_subnode_offset_namelen(), and fdt_supernode_atdepth_offset().
FDT_SW_MAGIC
#define FDT_SW_MAGIC (~FDT_MAGIC)
Definition at line 49 of file libfdt_internal.h.
Referenced by fdt_create_with_flags(), fdt_get_string(), and fdt_ro_probe_().
FDT_TAGALIGN
#define FDT_TAGALIGN (x) (FDT_ALIGN((x), FDT_TAGSIZE))
Definition at line 11 of file libfdt_internal.h.
Function Documentation
fdt_check_node_offset_()
int fdt_check_node_offset_ (const void * fdt, int offset)
Definition at line 184 of file fdt.c.
References FDT_BEGIN_NODE, FDT_ERR_BADOFFSET, fdt_next_tag(), FDT_TAGSIZE, and offset.
Referenced by fdt_first_property_offset(), and fdt_next_node().
 {
     if ((offset < 0) || (offset % FDT_TAGSIZE)
         || (fdt_next_tag(fdt, offset, &offset) != FDT_BEGIN_NODE))
         return -FDT_ERR_BADOFFSET;
     return offset;
 }
fdt_check_prop_offset_()
int fdt_check_prop_offset_ (const void * fdt, int offset)
Definition at line 193 of file fdt.c.
References FDT_ERR_BADOFFSET, fdt_next_tag(), FDT_PROP, FDT_TAGSIZE, and offset.
Referenced by fdt_next_property_offset().
 {
     if ((offset < 0) || (offset % FDT_TAGSIZE)
         || (fdt_next_tag(fdt, offset, &offset) != FDT_PROP))
         return -FDT_ERR_BADOFFSET;
     return offset;
 }
fdt_find_string_()
const char* fdt_find_string_ (const char * strtab, int tabsize, const char * s)
Definition at line 270 of file fdt.c.
References len, and NULL.
 {
     int len = strlen(s) + 1;
     const char *last = strtab + tabsize - len;
     const char *p;
     for (p = strtab; p <= last; p++)
         if (memcmp(p, s, len) == 0)
             return p;
     return NULL;
 }
fdt_node_end_offset_()
int fdt_node_end_offset_ (void * fdt, int nodeoffset)
Definition at line 73 of file fdt_wip.c.
References fdt_next_node(), and offset.
Referenced by fdt_del_node(), and fdt_nop_node().
 {
     int depth = 0;
     while ((offset >= 0) && (depth >= 0))
         offset = fdt_next_node(fdt, offset, &depth);
     return offset;
 }
fdt_ro_probe_()
int32_t fdt_ro_probe_ (const void * fdt)
Definition at line 18 of file fdt.c.
References FDT_ERR_BADMAGIC, FDT_ERR_BADSTATE, FDT_ERR_BADVERSION, FDT_ERR_TRUNCATED, FDT_FIRST_SUPPORTED_VERSION, fdt_last_comp_version, FDT_LAST_SUPPORTED_VERSION, FDT_MAGIC, fdt_magic, fdt_size_dt_struct, FDT_SW_MAGIC, fdt_totalsize, and fdt_version.
Referenced by fdt_get_string().
 {
     uint32_t totalsize = fdt_totalsize(fdt);
     if (fdt_magic(fdt) == FDT_MAGIC) {
         /* Complete tree */
         if (fdt_version(fdt) < FDT_FIRST_SUPPORTED_VERSION)
             return -FDT_ERR_BADVERSION;
         if (fdt_last_comp_version(fdt) > FDT_LAST_SUPPORTED_VERSION)
             return -FDT_ERR_BADVERSION;
     } else if (fdt_magic(fdt) == FDT_SW_MAGIC) {
         /* Unfinished sequential-write blob */
         if (fdt_size_dt_struct(fdt) == 0)
             return -FDT_ERR_BADSTATE;
     } else {
         return -FDT_ERR_BADMAGIC;
     }
     if (totalsize < INT32_MAX)
         return totalsize;
     else
         return -FDT_ERR_TRUNCATED;
 }