VideoCore Library: host_applications/linux/apps/hello_pi/hello_mmal_encode/mmal_encode.c File Reference
mmal_encode.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <bcm_host.h>
#include <interface/mmal/mmal.h>
#include <interface/mmal/mmal_format.h>
#include <interface/mmal/util/mmal_default_components.h>
#include <interface/mmal/util/mmal_component_wrapper.h>
#include <interface/mmal/util/mmal_util_params.h>
Functions
void create_rgba_test_image (void *buf, unsigned int length, unsigned int stride)
void mmal_encode_test (MMAL_FOURCC_T encoding, const char *filename)
int main (int argc, const char **argv)
Variables
const unsigned int WIDTH = 512
const unsigned int HEIGHT = 512
const MMAL_FOURCC_T INPUT_ENC = MMAL_ENCODING_RGBA
const unsigned int BYTESPP = 4
const uint32_t RED = 0xff
const uint32_t GREEN = 0xff << 8
const uint32_t BLUE = 0xff << 16
const uint32_t ALPHA = 0xff << 24
Function Documentation
create_rgba_test_image()
void create_rgba_test_image (void * buf, unsigned int length, unsigned int stride)
Definition at line 67 of file mmal_encode.c.
References ALPHA, BLUE, BYTESPP, GREEN, RED, and WIDTH.
Referenced by mmal_encode_test().
 {
    uint32_t* pixel = buf;
    int i;
    for (i=0; i<length/BYTESPP; ++i) {
       switch ((i % stride) / (WIDTH / 8)) {
       case 0: *pixel = RED | GREEN | BLUE; break;
       case 1: *pixel = 0; break;
       case 2: *pixel = RED; break;
       case 3: *pixel = GREEN; break;
       case 4: *pixel = BLUE; break;
       case 5: *pixel = GREEN | BLUE; break;
       case 6: *pixel = RED | BLUE; break;
       case 7: *pixel = RED | GREEN; break;
       }
       *pixel |= ALPHA; // Full alpha
       ++pixel;
    }
 }
main()
int main (int argc, const char ** argv)
Definition at line 233 of file mmal_encode.c.
References bcm_host_init(), and vcos_semaphore_create().
 {
    bcm_host_init();
    if (vcos_semaphore_create(&sem, "encoder sem", 0) != VCOS_SUCCESS) {
       fprintf(stderr, "Failed to create semaphore\n");
       exit(1);
    }
    if (mmal_wrapper_create(&encoder, MMAL_COMPONENT_DEFAULT_IMAGE_ENCODER)
        != MMAL_SUCCESS) {
       fprintf(stderr, "Failed to create mmal component\n");
       exit(1);
    }
    encoder->callback = mmalCallback;
    // Perform test encodings in various formats
    mmal_encode_test(MMAL_ENCODING_PNG, "out.png");
    mmal_encode_test(MMAL_ENCODING_JPEG, "out.jpg");
    mmal_encode_test(MMAL_ENCODING_GIF, "out.gif");
    mmal_encode_test(MMAL_ENCODING_BMP, "out.bmp");
    mmal_wrapper_destroy(encoder);
    vcos_semaphore_delete(&sem);
    return 0;
 }
mmal_encode_test()
void mmal_encode_test (MMAL_FOURCC_T encoding, const char * filename)
Definition at line 88 of file mmal_encode.c.
References MMAL_BUFFER_HEADER_T::alloc_size, MMAL_PORT_T::buffer_num, MMAL_PORT_T::buffer_num_recommended, MMAL_PORT_T::buffer_size, MMAL_PORT_T::buffer_size_recommended, create_rgba_test_image(), MMAL_VIDEO_FORMAT_T::crop, MMAL_BUFFER_HEADER_T::data, MMAL_ES_FORMAT_T::encoding, encoding, MMAL_ES_FORMAT_T::es, MMAL_BUFFER_HEADER_T::flags, MMAL_PORT_T::format, HEIGHT, MMAL_VIDEO_FORMAT_T::height, MMAL_RECT_T::height, MMAL_WRAPPER_T::input, INPUT_ENC, MMAL_PORT_T::is_enabled, MMAL_BUFFER_HEADER_T::length, MMAL_BUFFER_HEADER_FLAG_EOS, MMAL_EAGAIN, MMAL_PARAMETER_JPEG_Q_FACTOR, mmal_port_format_commit(), mmal_port_parameter_set_uint32(), mmal_port_send_buffer(), MMAL_SUCCESS, mmal_wrapper_buffer_get_empty(), mmal_wrapper_buffer_get_full(), MMAL_WRAPPER_FLAG_PAYLOAD_ALLOCATE, mmal_wrapper_port_disable(), mmal_wrapper_port_enable(), MMAL_WRAPPER_T::output, status, MMAL_WRAPPER_T::status, VCOS_ALIGN_UP, vcos_semaphore_wait(), MMAL_ES_SPECIFIC_FORMAT_T::video, WIDTH, MMAL_VIDEO_FORMAT_T::width, MMAL_RECT_T::width, MMAL_RECT_T::x, and MMAL_RECT_T::y.
 {
    MMAL_PORT_T* portIn;
    MMAL_PORT_T* portOut;
    MMAL_BUFFER_HEADER_T* in;
    MMAL_BUFFER_HEADER_T* out;
    MMAL_STATUS_T status;
    int eos = 0;
    int sent = 0;
    int outputWritten = 0;
    FILE* outFile;
    int nw;
    printf("Encoding test image %s\n", filename);
    // Configure input
    portIn = encoder->input[0];
    encoder->status = MMAL_SUCCESS;
    if (portIn->is_enabled) {
       if (mmal_wrapper_port_disable(portIn) != MMAL_SUCCESS) {
          fprintf(stderr, "Failed to disable input port\n");
          exit(1);
       }
    }
    portIn->format->encoding = INPUT_ENC;
    portIn->format->es->video.width = VCOS_ALIGN_UP(WIDTH, 32);
    portIn->format->es->video.height = VCOS_ALIGN_UP(HEIGHT, 16);
    portIn->format->es->video.crop.x = 0;
    portIn->format->es->video.crop.y = 0;
    portIn->format->es->video.crop.width = WIDTH;
    portIn->format->es->video.crop.height = HEIGHT;
    if (mmal_port_format_commit(portIn) != MMAL_SUCCESS) {
       fprintf(stderr, "Failed to commit input port format\n");
       exit(1);
    }
    portIn->buffer_size = portIn->buffer_size_recommended;
    portIn->buffer_num = portIn->buffer_num_recommended;
    if (mmal_wrapper_port_enable(portIn, MMAL_WRAPPER_FLAG_PAYLOAD_ALLOCATE)
        != MMAL_SUCCESS) {
       fprintf(stderr, "Failed to enable input port\n");
       exit(1);
    }
    printf("- input %4.4s %ux%u\n",
           (char*)&portIn->format->encoding,
           portIn->format->es->video.width, portIn->format->es->video.height);
    // Configure output
    portOut = encoder->output[0];
    if (portOut->is_enabled) {
       if (mmal_wrapper_port_disable(portOut) != MMAL_SUCCESS) {
          fprintf(stderr, "Failed to disable output port\n");
          exit(1);
       }
    }
    portOut->format->encoding = encoding;
    if (mmal_port_format_commit(portOut) != MMAL_SUCCESS) {
       fprintf(stderr, "Failed to commit output port format\n");
       exit(1);
    }
    mmal_port_parameter_set_uint32(portOut, MMAL_PARAMETER_JPEG_Q_FACTOR, 100);
    portOut->buffer_size = portOut->buffer_size_recommended;
    portOut->buffer_num = portOut->buffer_num_recommended;
    if (mmal_wrapper_port_enable(portOut, MMAL_WRAPPER_FLAG_PAYLOAD_ALLOCATE)
        != MMAL_SUCCESS) {
       fprintf(stderr, "Failed to enable output port\n");
       exit(1);
    }
    printf("- output %4.4s\n", (char*)&encoding);
    // Perform the encoding
    outFile = fopen(filename, "w");
    if (!outFile) {
       fprintf(stderr, "Failed to open file %s (%s)\n", filename, strerror(errno));
       exit(1);
    }
    while (!eos) {
       // Send output buffers to be filled with encoded image.
       while (mmal_wrapper_buffer_get_empty(portOut, &out, 0) == MMAL_SUCCESS) {
          if (mmal_port_send_buffer(portOut, out) != MMAL_SUCCESS) {
             fprintf(stderr, "Failed to send buffer\n");
             break;
          }
       }
       // Send image to be encoded.
       if (!sent && mmal_wrapper_buffer_get_empty(portIn, &in, 0) == MMAL_SUCCESS) {
          printf("- sending %u bytes to encoder\n", in->alloc_size);
          create_rgba_test_image(in->data, in->alloc_size, portIn->format->es->video.width);
          in->length = in->alloc_size;
          in->flags = MMAL_BUFFER_HEADER_FLAG_EOS;
          if (mmal_port_send_buffer(portIn, in) != MMAL_SUCCESS) {
             fprintf(stderr, "Failed to send buffer\n");
             break;
          }
          sent = 1;
       }
       // Get filled output buffers.
       status = mmal_wrapper_buffer_get_full(portOut, &out, 0);
       if (status == MMAL_EAGAIN) {
          // No buffer available, wait for callback and loop.
          vcos_semaphore_wait(&sem);
          continue;
       } else if (status != MMAL_SUCCESS) {
          fprintf(stderr, "Failed to get full buffer\n");
          exit(1);
       }
       printf("- received %i bytes\n", out->length);
       eos = out->flags & MMAL_BUFFER_HEADER_FLAG_EOS;
       nw = fwrite(out->data, 1, out->length, outFile);
       if (nw != out->length) {
          fprintf(stderr, "Failed to write complete buffer\n");
          exit(1);
       }
       outputWritten += nw;
       mmal_buffer_header_release(out);
    }
    mmal_port_flush(portOut);
    fclose(outFile);
    printf("- written %u bytes to %s\n\n", outputWritten, filename);
 }
Variable Documentation
ALPHA
const uint32_t ALPHA = 0xff << 24
Definition at line 53 of file mmal_encode.c.
Referenced by create_rgba_test_image().
BLUE
const uint32_t BLUE = 0xff << 16
Definition at line 52 of file mmal_encode.c.
Referenced by create_rgba_test_image().
BYTESPP
const unsigned int BYTESPP = 4
Definition at line 49 of file mmal_encode.c.
Referenced by create_rgba_test_image().
GREEN
const uint32_t GREEN = 0xff << 8
Definition at line 51 of file mmal_encode.c.
Referenced by create_rgba_test_image().
HEIGHT
const unsigned int HEIGHT = 512
Definition at line 47 of file mmal_encode.c.
Referenced by mmal_encode_test().
INPUT_ENC
const MMAL_FOURCC_T INPUT_ENC = MMAL_ENCODING_RGBA
Definition at line 48 of file mmal_encode.c.
Referenced by mmal_encode_test().
RED
const uint32_t RED = 0xff
Definition at line 50 of file mmal_encode.c.
Referenced by create_rgba_test_image().
WIDTH
const unsigned int WIDTH = 512
Definition at line 46 of file mmal_encode.c.
Referenced by create_rgba_test_image(), and mmal_encode_test().