VideoCore Library: containers/test/autotest.cpp File Reference
autotest.cpp File Reference
#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <map>
#include <set>
#include <vector>
#include <list>
#include <algorithm>
#include <iomanip>
#include "containers/containers.h"
#include "containers/core/containers_common.h"
#include "containers/core/containers_logging.h"
#include "containers/core/containers_utils.h"
#include "containers/core/containers_io.h"
Classes
class ERROR_LOGGER_T
struct PACKET_DATA_T
struct CONFIGURATION_T
class TESTER_T
Namespaces
std
Macros
#define __cdecl
Typedefs
typedef int64_t PTS_T
typedef uint32_t STREAM_T
typedef std::list< PACKET_DATA_T > ALL_PACKETS_T
typedef std::map< PTS_T, ALL_PACKETS_T::const_iterator > TIMED_PACKETS_T
typedef std::map< STREAM_T, TIMED_PACKETS_T > STREAM_TIMED_PACKETS_T
Functions
uint32_t crc32buf (const uint8_t *buf, size_t len)
ERROR_LOGGER_T & std::ends (ERROR_LOGGER_T &logger)
int main (int argc, char **argv)
Macro Definition Documentation
__cdecl
#define __cdecl
Definition at line 40 of file autotest.cpp.
Typedef Documentation
ALL_PACKETS_T
typedef std::list<PACKET_DATA_T> ALL_PACKETS_T
Definition at line 178 of file autotest.cpp.
PTS_T
typedef int64_t PTS_T
Definition at line 158 of file autotest.cpp.
STREAM_T
typedef uint32_t STREAM_T
Definition at line 175 of file autotest.cpp.
STREAM_TIMED_PACKETS_T
typedef std::map<STREAM_T, TIMED_PACKETS_T> STREAM_TIMED_PACKETS_T
Definition at line 185 of file autotest.cpp.
TIMED_PACKETS_T
typedef std::map<PTS_T, ALL_PACKETS_T::const_iterator> TIMED_PACKETS_T
Definition at line 181 of file autotest.cpp.
Function Documentation
crc32buf()
uint32_t crc32buf (const uint8_t * buf, size_t len)
Definition at line 197 of file crc_32.c.
References crc32file(), len, main(), and UPDC32.
Referenced by TESTER_T::run().
 {
       register uint32_t oldcrc32;
       oldcrc32 = 0xFFFFFFFF;
       for ( ; len; --len, ++buf)
       {
             oldcrc32 = UPDC32(*buf, oldcrc32);
       }
       return ~oldcrc32;
 }
main()
int main (int argc, char ** argv)
Definition at line 1951 of file autotest.cpp.
References TESTER_T::run().
Referenced by crc32buf().
 {
    // Read and parse the configuration information from the command line.
    TESTER_T test(argc, argv);
    // Run the tests and return their error code
    return test.run();
 }