VideoCore Library: interface/khronos/egl/egl_client_config.h File Reference
egl_client_config.h File Reference
#include "interface/khronos/common/khrn_client_platform.h"
#include "interface/khronos/include/EGL/egl.h"
#include "interface/khronos/include/EGL/eglext.h"
#include "interface/khronos/common/khrn_int_image.h"
#include "interface/khronos/egl/egl_int_config.h"
Macros
#define EGL_MAX_CONFIGS 28
#define EGL_CONFIG_MIN_SWAP_INTERVAL 0
#define EGL_CONFIG_MAX_SWAP_INTERVAL 0x7fffffff
#define EGL_CONFIG_MAX_WIDTH 2048
#define EGL_CONFIG_MAX_HEIGHT 2048
Functions
void egl_config_sort (int *ids, bool use_red, bool use_green, bool use_blue, bool use_alpha)
bool egl_config_check_attribs (const EGLint *attrib_list, bool *use_red, bool *use_green, bool *use_blue, bool *use_alpha)
bool egl_config_filter (int id, const EGLint *attrib_list)
bool egl_config_get_attrib (int id, EGLint attrib, EGLint *value)
void egl_config_install_configs (int type)
KHRN_IMAGE_FORMAT_T egl_config_get_color_format (int id)
KHRN_IMAGE_FORMAT_T egl_config_get_depth_format (int id)
KHRN_IMAGE_FORMAT_T egl_config_get_mask_format (int id)
KHRN_IMAGE_FORMAT_T egl_config_get_multisample_format (int id)
bool egl_config_get_multisample (int id)
bool egl_config_bindable (int id, EGLenum format)
bool egl_config_match_pixmap_info (int id, KHRN_IMAGE_WRAP_T *image)
uint32_t egl_config_get_api_support (int id)
bool egl_config_bpps_match (int id0, int id1)
uint32_t egl_config_get_api_conformance (int id)
Macro Definition Documentation
EGL_CONFIG_MAX_HEIGHT
#define EGL_CONFIG_MAX_HEIGHT 2048
Definition at line 83 of file egl_client_config.h.
EGL_CONFIG_MAX_SWAP_INTERVAL
#define EGL_CONFIG_MAX_SWAP_INTERVAL 0x7fffffff
Definition at line 67 of file egl_client_config.h.
EGL_CONFIG_MAX_WIDTH
#define EGL_CONFIG_MAX_WIDTH 2048
Definition at line 75 of file egl_client_config.h.
EGL_CONFIG_MIN_SWAP_INTERVAL
#define EGL_CONFIG_MIN_SWAP_INTERVAL 0
Definition at line 57 of file egl_client_config.h.
EGL_MAX_CONFIGS
#define EGL_MAX_CONFIGS 28
Definition at line 47 of file egl_client_config.h.
Referenced by egl_config_bindable(), egl_config_bpps_match(), egl_config_get_color_format(), egl_config_get_depth_format(), egl_config_get_mask_format(), egl_config_get_multisample(), egl_config_get_multisample_format(), egl_config_match_pixmap_info(), and egl_config_sort().
Function Documentation
egl_config_bindable()
bool egl_config_bindable (int id, EGLenum format)
Definition at line 231 of file egl_client_config.c.
References EGL_MAX_CONFIGS, EGL_NO_TEXTURE, EGL_TEXTURE_RGB, and vcos_assert.
 {
    vcos_assert(id >= 0 && id < EGL_MAX_CONFIGS);
    switch (format) {
    case EGL_NO_TEXTURE:
       return true;
    case EGL_TEXTURE_RGB:
       return bindable_rgb(formats[id].features);
    case EGL_TEXTURE_RGBA:
       return bindable_rgba(formats[id].features);
    default:
       UNREACHABLE();
       return false;
    }
 }
egl_config_bpps_match()
bool egl_config_bpps_match (int id0, int id1)
Definition at line 343 of file egl_client_config.c.
References egl_config_get_color_format(), EGL_MAX_CONFIGS, FEATURES_AND_FORMATS_T::features, FEATURES_UNPACK_ALPHA, FEATURES_UNPACK_BLUE, FEATURES_UNPACK_DEPTH, FEATURES_UNPACK_GREEN, FEATURES_UNPACK_LOCKABLE, FEATURES_UNPACK_MASK, FEATURES_UNPACK_RED, FEATURES_UNPACK_STENCIL, and vcos_assert.
 {
    FEATURES_T config0 = formats[id0].features;
    FEATURES_T config1 = formats[id1].features;
    return
       FEATURES_UNPACK_RED(config0)     == FEATURES_UNPACK_RED(config1) &&
       FEATURES_UNPACK_GREEN(config0)   == FEATURES_UNPACK_GREEN(config1) &&
       FEATURES_UNPACK_BLUE(config0)    == FEATURES_UNPACK_BLUE(config1) &&
       FEATURES_UNPACK_ALPHA(config0)   == FEATURES_UNPACK_ALPHA(config1) &&
       FEATURES_UNPACK_DEPTH(config0)   == FEATURES_UNPACK_DEPTH(config1) &&
       FEATURES_UNPACK_STENCIL(config0) == FEATURES_UNPACK_STENCIL(config1) &&
       FEATURES_UNPACK_MASK(config0)    == FEATURES_UNPACK_MASK(config1);
 }
egl_config_check_attribs()
bool egl_config_check_attribs (const EGLint * attrib_list, bool * use_red, bool * use_green, bool * use_blue, bool * use_alpha)
Definition at line 107 of file egl_client_config_cr.c.
References EGL_ALPHA_MASK_SIZE, EGL_ALPHA_SIZE, EGL_BIND_TO_TEXTURE_RGB, EGL_BIND_TO_TEXTURE_RGBA, EGL_BLUE_SIZE, EGL_BUFFER_SIZE, EGL_COLOR_BUFFER_TYPE, EGL_CONFIG_CAVEAT, EGL_CONFIG_ID, EGL_CONFORMANT, EGL_DEPTH_SIZE, EGL_DONT_CARE, EGL_FALSE, EGL_FORMAT_RGB_565_EXACT_KHR, EGL_FORMAT_RGB_565_KHR, EGL_FORMAT_RGBA_8888_EXACT_KHR, EGL_FORMAT_RGBA_8888_KHR, EGL_GREEN_SIZE, EGL_LEVEL, EGL_LOCK_SURFACE_BIT_KHR, EGL_LUMINANCE_BUFFER, EGL_LUMINANCE_SIZE, EGL_MATCH_FORMAT_KHR, EGL_MATCH_NATIVE_PIXMAP, EGL_MAX_PBUFFER_HEIGHT, EGL_MAX_PBUFFER_PIXELS, EGL_MAX_PBUFFER_WIDTH, EGL_MAX_SWAP_INTERVAL, EGL_MIN_SWAP_INTERVAL, EGL_MULTISAMPLE_RESOLVE_BOX_BIT, EGL_NATIVE_RENDERABLE, EGL_NATIVE_VISUAL_ID, EGL_NATIVE_VISUAL_TYPE, EGL_NON_CONFORMANT_CONFIG, EGL_NONE, EGL_OPENGL_BIT, EGL_OPENGL_ES2_BIT, EGL_OPENGL_ES_BIT, EGL_OPENVG_BIT, EGL_OPTIMAL_FORMAT_BIT_KHR, EGL_PBUFFER_BIT, EGL_PIXMAP_BIT, EGL_RED_SIZE, EGL_RENDERABLE_TYPE, EGL_RGB_BUFFER, EGL_SAMPLE_BUFFERS, EGL_SAMPLES, EGL_SLOW_CONFIG, EGL_STENCIL_SIZE, EGL_SURFACE_TYPE, EGL_SWAP_BEHAVIOR_PRESERVED_BIT, EGL_TRANSPARENT_BLUE_VALUE, EGL_TRANSPARENT_GREEN_VALUE, EGL_TRANSPARENT_RED_VALUE, EGL_TRANSPARENT_RGB, EGL_TRANSPARENT_TYPE, EGL_TRUE, EGL_VG_ALPHA_FORMAT_PRE_BIT, EGL_VG_COLORSPACE_LINEAR_BIT, EGL_WINDOW_BIT, khrn_platform_release_pixmap_info(), name, and platform_get_pixmap_info().
 {
    if (!attrib_list)
       return true;
    while (*attrib_list != EGL_NONE) {
       EGLint name = *attrib_list++;
       EGLint value = *attrib_list++;
       if (name == EGL_RED_SIZE && value != 0 && value != EGL_DONT_CARE)
          *use_red = true;
       if (name == EGL_GREEN_SIZE && value != 0 && value != EGL_DONT_CARE)
          *use_green = true;
       if (name == EGL_BLUE_SIZE && value != 0 && value != EGL_DONT_CARE)
          *use_blue = true;
       if (name == EGL_ALPHA_SIZE && value != 0 && value != EGL_DONT_CARE)
          *use_alpha = true;
       switch (name) {
       case EGL_BUFFER_SIZE:
       case EGL_RED_SIZE:
       case EGL_GREEN_SIZE:
       case EGL_BLUE_SIZE:
       case EGL_LUMINANCE_SIZE:
       case EGL_ALPHA_SIZE:
       case EGL_ALPHA_MASK_SIZE:
          if (value != EGL_DONT_CARE && value < 0) return false;
          break;
       case EGL_BIND_TO_TEXTURE_RGB:
       case EGL_BIND_TO_TEXTURE_RGBA:
          if (value != EGL_DONT_CARE && value != EGL_FALSE && value != EGL_TRUE)
             return false;
          break;
       case EGL_COLOR_BUFFER_TYPE:
          if (value != EGL_DONT_CARE && value != EGL_RGB_BUFFER && value != EGL_LUMINANCE_BUFFER)
             return false;
          break;
       case EGL_CONFIG_CAVEAT:
          if (value != EGL_DONT_CARE && value != EGL_NONE && value != EGL_SLOW_CONFIG && value != EGL_NON_CONFORMANT_CONFIG)
             return false;
          break;
       case EGL_CONFIG_ID:
          if (value != EGL_DONT_CARE && value < 1)
             return false;
          break;
       case EGL_CONFORMANT:
          if (value != EGL_DONT_CARE && (value & ~(EGL_OPENGL_BIT|EGL_OPENGL_ES_BIT|EGL_OPENGL_ES2_BIT|EGL_OPENVG_BIT)))
             return false;
          break;
       case EGL_DEPTH_SIZE:
          if (value != EGL_DONT_CARE && value < 0) return false;
          break;
       case EGL_LEVEL:
          break;
       case EGL_MATCH_NATIVE_PIXMAP:
          /* 1.4 Spec is poor here - says that value has to be a valid handle, but also says that any attribute
           * value (other than EGL_LEVEL) can be EGL_DONT_CARE. It also says that the default value is EGL_NONE,
           * but that doesn't really make sense - sensible to assume that the default is EGL_DONT_CARE, and don't
           * support EGL_NONE as an explicit parameter. (Could theoretically collide with a real handle...)
           */
          if (value != EGL_DONT_CARE) {
             KHRN_IMAGE_WRAP_T image;
             if (!platform_get_pixmap_info((EGLNativePixmapType)(intptr_t)value, &image))
                return false;
             khrn_platform_release_pixmap_info((EGLNativePixmapType)(intptr_t)value, &image);
          }
          break;
       case EGL_MAX_PBUFFER_WIDTH:
       case EGL_MAX_PBUFFER_HEIGHT:
       case EGL_MAX_PBUFFER_PIXELS:
          break;
       case EGL_MAX_SWAP_INTERVAL:
       case EGL_MIN_SWAP_INTERVAL:
          if (value != EGL_DONT_CARE && value < 0) return false;
          break;
       case EGL_NATIVE_RENDERABLE:
          if (value != EGL_DONT_CARE && value != EGL_FALSE && value != EGL_TRUE)
             return false;
          break;
       case EGL_NATIVE_VISUAL_ID:
       case EGL_NATIVE_VISUAL_TYPE:
          break;
       case EGL_RENDERABLE_TYPE:
          if (value != EGL_DONT_CARE && (value & ~(EGL_OPENGL_BIT|EGL_OPENGL_ES_BIT|EGL_OPENGL_ES2_BIT|EGL_OPENVG_BIT)))
             return false;
          break;
       case EGL_SAMPLE_BUFFERS:
       case EGL_SAMPLES:
       case EGL_STENCIL_SIZE:
          if (value != EGL_DONT_CARE && value < 0) return false;
          break;
       case EGL_SURFACE_TYPE:
       {
          int valid_bits = EGL_WINDOW_BIT|EGL_PIXMAP_BIT|EGL_PBUFFER_BIT|
             EGL_MULTISAMPLE_RESOLVE_BOX_BIT|EGL_SWAP_BEHAVIOR_PRESERVED_BIT|
             EGL_VG_COLORSPACE_LINEAR_BIT|EGL_VG_ALPHA_FORMAT_PRE_BIT;
 #if EGL_KHR_lock_surface
          valid_bits |= EGL_LOCK_SURFACE_BIT_KHR|EGL_OPTIMAL_FORMAT_BIT_KHR;
 #endif
          if (value != EGL_DONT_CARE && (value & ~valid_bits))
             return false;
          break;
       }
       case EGL_TRANSPARENT_TYPE:
          if (value != EGL_DONT_CARE && value != EGL_NONE && value != EGL_TRANSPARENT_RGB)
             return false;
          break;
       case EGL_TRANSPARENT_RED_VALUE:
       case EGL_TRANSPARENT_GREEN_VALUE:
       case EGL_TRANSPARENT_BLUE_VALUE:
          if (value != EGL_DONT_CARE && value < 0) return false;
          break;
 #if EGL_KHR_lock_surface
       case EGL_MATCH_FORMAT_KHR:
          switch (value) {
          case EGL_DONT_CARE:
          case EGL_NONE:
          case EGL_FORMAT_RGB_565_EXACT_KHR:
          case EGL_FORMAT_RGB_565_KHR:
          case EGL_FORMAT_RGBA_8888_EXACT_KHR:
          case EGL_FORMAT_RGBA_8888_KHR:
             break;
          default:
             return false;
          }
          break;
 #endif
 #if EGL_ANDROID_recordable
       case EGL_RECORDABLE_ANDROID:
          switch (value) {
          case EGL_DONT_CARE:
          case EGL_TRUE:
          case EGL_FALSE:
             break;
          default:
             return false;
          }
          break;
 #endif
       default:
          return false;
       }
    }
    return true;
 }
egl_config_filter()
bool egl_config_filter (int id, const EGLint * attrib_list)
Definition at line 633 of file egl_client_config_cr.c.
References EGL_ALPHA_MASK_SIZE, EGL_ALPHA_SIZE, EGL_BIND_TO_TEXTURE_RGB, EGL_BIND_TO_TEXTURE_RGBA, EGL_BLUE_SIZE, EGL_BUFFER_SIZE, EGL_COLOR_BUFFER_TYPE, EGL_CONFIG_CAVEAT, egl_config_get_api_support(), egl_config_get_attrib(), EGL_CONFIG_ID, egl_config_match_pixmap_info(), EGL_CONFORMANT, EGL_DEPTH_SIZE, EGL_DONT_CARE, EGL_FORMAT_RGB_565_EXACT_KHR, EGL_FORMAT_RGB_565_KHR, EGL_FORMAT_RGBA_8888_EXACT_KHR, EGL_FORMAT_RGBA_8888_KHR, EGL_GREEN_SIZE, EGL_LEVEL, EGL_LUMINANCE_SIZE, EGL_MATCH_FORMAT_KHR, EGL_MATCH_NATIVE_PIXMAP, EGL_MAX_PBUFFER_HEIGHT, EGL_MAX_PBUFFER_PIXELS, EGL_MAX_PBUFFER_WIDTH, EGL_MAX_SWAP_INTERVAL, EGL_MIN_SWAP_INTERVAL, EGL_NATIVE_RENDERABLE, EGL_NATIVE_VISUAL_ID, EGL_NATIVE_VISUAL_TYPE, EGL_NONE, EGL_RED_SIZE, EGL_RENDERABLE_TYPE, EGL_SAMPLE_BUFFERS, EGL_SAMPLES, EGL_STENCIL_SIZE, EGL_SURFACE_TYPE, EGL_TRANSPARENT_BLUE_VALUE, EGL_TRANSPARENT_GREEN_VALUE, EGL_TRANSPARENT_RED_VALUE, EGL_TRANSPARENT_TYPE, khrn_platform_release_pixmap_info(), name, pixmap, platform_get_pixmap_info(), platform_match_pixmap_api_support(), and UNREACHABLE.
 {
    if (!attrib_list)
       return true;
    while (*attrib_list != EGL_NONE) {
       EGLint name = *attrib_list++;
       EGLint value = *attrib_list++;
       EGLint actual_value;
       if (!egl_config_get_attrib(id, name, &actual_value) )
       {
          UNREACHABLE();
          return false;
       }
       switch (name) {
          /* Selection Criteria: AtLeast */
       case EGL_BUFFER_SIZE:
       case EGL_RED_SIZE:
       case EGL_GREEN_SIZE:
       case EGL_BLUE_SIZE:
       case EGL_LUMINANCE_SIZE:
       case EGL_ALPHA_SIZE:
       case EGL_ALPHA_MASK_SIZE:
       case EGL_DEPTH_SIZE:
       case EGL_SAMPLE_BUFFERS:
       case EGL_SAMPLES:
       case EGL_STENCIL_SIZE:
          if (value != EGL_DONT_CARE && value > actual_value)
             return false;
          break;
          /* Selection Criteria: Exact */
          /*
             Excluding EGL_TRANSPARENT_x_VALUE and EGL_MATCH_FORMAT_KHR which are listed in
             the table as Exact, but seem to have special rules attached to them.
             Excluding EGL_NATIVE_VISUAL_TYPE which is in the ignore list
             Excluding EGL_LEVEL because EGL_DONT_CARE is not allowed
          */
       case EGL_BIND_TO_TEXTURE_RGB:
       case EGL_BIND_TO_TEXTURE_RGBA:
       case EGL_COLOR_BUFFER_TYPE:
       case EGL_CONFIG_CAVEAT:
       case EGL_CONFIG_ID:
       case EGL_MAX_SWAP_INTERVAL:
       case EGL_MIN_SWAP_INTERVAL:
       case EGL_NATIVE_RENDERABLE:
       case EGL_TRANSPARENT_TYPE:
 #if EGL_ANDROID_recordable
       case EGL_RECORDABLE_ANDROID:
 #endif
          if (value != EGL_DONT_CARE && value != actual_value)
             return false;
          break;
       case EGL_LEVEL:
          if (value != actual_value)
             return false;
          break;
          /* Selection Criteria: Mask */
       case EGL_CONFORMANT:
       case EGL_RENDERABLE_TYPE:
       case EGL_SURFACE_TYPE:
          if (value != EGL_DONT_CARE && (value & ~actual_value))
             return false;
          break;
          /* Selection Criteria: Special */
       case EGL_MATCH_NATIVE_PIXMAP:
          if (value != EGL_DONT_CARE) { /* see comments in egl_config_check_attribs */
             EGLNativePixmapType pixmap = (EGLNativePixmapType)(intptr_t)value;
             KHRN_IMAGE_WRAP_T image;
             if (!platform_get_pixmap_info(pixmap, &image)) {
                /*
                   Not actually unreachable in theory!
                   We should have detected this in egl_config_check_attribs
                   It's possible that the validity of pixmap has changed since then however...
                */
                UNREACHABLE();
                return false;
             }
             if (!egl_config_match_pixmap_info(id, &image) ||
                !platform_match_pixmap_api_support(pixmap, egl_config_get_api_support(id)))
             {
                khrn_platform_release_pixmap_info(pixmap, &image);
                return false;
             }
             khrn_platform_release_pixmap_info(pixmap, &image);
          }
          break;
 #if EGL_KHR_lock_surface
       case EGL_MATCH_FORMAT_KHR:
          if (!(value == EGL_DONT_CARE || value == actual_value
             || (value == EGL_FORMAT_RGB_565_KHR && actual_value == EGL_FORMAT_RGB_565_EXACT_KHR)
             || (value == EGL_FORMAT_RGBA_8888_KHR && actual_value == EGL_FORMAT_RGBA_8888_EXACT_KHR)))
          {
             return false;
          }
          break;
 #endif
          /* Attributes we can completely ignore */
       case EGL_MAX_PBUFFER_WIDTH:
       case EGL_MAX_PBUFFER_HEIGHT:
       case EGL_MAX_PBUFFER_PIXELS:
       case EGL_NATIVE_VISUAL_ID:
          /*
          "If EGL_MAX_PBUFFER_WIDTH, EGL_MAX_PBUFFER_HEIGHT,
          EGL_MAX_PBUFFER_PIXELS, or EGL_NATIVE_VISUAL_ID are specified in
          attrib_list, then they are ignored"
          */
       case EGL_NATIVE_VISUAL_TYPE:
          /*
          "if there are no native visual types, then the EGL NATIVE VISUAL TYPE attribute is
          ignored."
          */
       case EGL_TRANSPARENT_BLUE_VALUE:
       case EGL_TRANSPARENT_GREEN_VALUE:
       case EGL_TRANSPARENT_RED_VALUE:
          /*
           "If EGL_TRANSPARENT_TYPE is set to EGL_NONE in attrib_list, then
          the EGL_TRANSPARENT_RED_VALUE, EGL_TRANSPARENT_GREEN_VALUE, and
          EGL_TRANSPARENT_BLUE_VALUE attributes are ignored."
          Possible spec deviation if EGL_TRANSPARENT_TYPE is specified as EGL_DONT_CARE
          and EGL_TRANSPARENT_*_VALUE is also specified?
          */
          break;
       default:
          UNREACHABLE();
          break;
       }
    }
    return true;
 }
egl_config_get_api_conformance()
uint32_t egl_config_get_api_conformance (int id)
Definition at line 337 of file egl_client_config.c.
References egl_config_get_api_support(), EGL_OPENVG_BIT, and FEATURES_UNPACK_MULTI.
 {
    /* vg doesn't support multisampled surfaces properly */
    return egl_config_get_api_support(id) & ~(FEATURES_UNPACK_MULTI(formats[id].features) ? EGL_OPENVG_BIT : 0);
 }
egl_config_get_api_support()
uint32_t egl_config_get_api_support (int id)
Definition at line 291 of file egl_client_config.c.
References ABGR_8888_LT, ABGR_8888_RSO, ABGR_8888_TF, ARGB_8888_LT, ARGB_8888_RSO, ARGB_8888_TF, egl_config_get_color_format(), EGL_OPENGL_ES2_BIT, EGL_OPENGL_ES_BIT, EGL_OPENVG_BIT, RGB_565_LT, RGB_565_RSO, RGB_565_TF, XBGR_8888_LT, XBGR_8888_RSO, XBGR_8888_TF, XRGB_8888_LT, XRGB_8888_RSO, and XRGB_8888_TF.
Referenced by egl_config_filter(), and egl_config_get_api_conformance().
 {
    /* no configs are api-specific (ie if you can use a config with gl, you can
     * use it with vg too, and vice-versa). however, some configs have color
     * buffer formats that are incompatible with the hardware, and so can't be
     * used with any api. such configs may still be useful eg with the surface
     * locking extension... */
 #if EGL_KHR_lock_surface
    /* to reduce confusion, just say no for all lockable configs. this #if can be
     * safely commented out -- the color buffer format check below will catch
     * lockable configs we actually can't use */
    if (egl_config_is_lockable(id)) {
       return 0;
    }
 #endif
    switch (egl_config_get_color_format(id)) {
    case ABGR_8888_RSO: case ABGR_8888_TF: case ABGR_8888_LT:
    case XBGR_8888_RSO: case XBGR_8888_TF: case XBGR_8888_LT:
    case ARGB_8888_RSO: case ARGB_8888_TF: case ARGB_8888_LT:
    case XRGB_8888_RSO: case XRGB_8888_TF: case XRGB_8888_LT:
    case RGB_565_RSO: case RGB_565_TF: case RGB_565_LT:
 #ifndef NO_OPENVG
       return (uint32_t)(EGL_OPENGL_ES_BIT | EGL_OPENVG_BIT | EGL_OPENGL_ES2_BIT);
 #else
       return (uint32_t)(EGL_OPENGL_ES_BIT | EGL_OPENGL_ES2_BIT);
 #endif
    default:
       break;
    }
    return 0;
 }
egl_config_get_attrib()
bool egl_config_get_attrib (int id, EGLint attrib, EGLint * value)
Definition at line 459 of file egl_client_config_cr.c.
Referenced by egl_config_filter().
 {
    FEATURES_T features = formats[id].features;
    switch (attrib) {
    case EGL_BUFFER_SIZE:
       *value = FEATURES_UNPACK_COLOR(features);
       return true;
    case EGL_RED_SIZE:
       *value = FEATURES_UNPACK_RED(features);
       return true;
    case EGL_GREEN_SIZE:
       *value = FEATURES_UNPACK_GREEN(features);
       return true;
    case EGL_BLUE_SIZE:
       *value = FEATURES_UNPACK_BLUE(features);
       return true;
    case EGL_LUMINANCE_SIZE:
       *value = 0;
       return true;
    case EGL_ALPHA_SIZE:
       *value = FEATURES_UNPACK_ALPHA(features);
       return true;
    case EGL_ALPHA_MASK_SIZE:
       *value = FEATURES_UNPACK_MASK(features);
       return true;
    case EGL_BIND_TO_TEXTURE_RGB:
       *value = bindable_rgb(features);
       return true;
    case EGL_BIND_TO_TEXTURE_RGBA:
       *value = bindable_rgba(features);
       return true;
    case EGL_COLOR_BUFFER_TYPE:
       *value = EGL_RGB_BUFFER;
       return true;
    case EGL_CONFIG_CAVEAT:
       *value = EGL_NONE;
       return true;
    case EGL_CONFIG_ID:
       *value = (EGLint)(uintptr_t)egl_config_from_id(id);
       return true;
    case EGL_CONFORMANT:
       *value = egl_config_get_api_conformance(id);
       return true;
    case EGL_DEPTH_SIZE:
       *value = FEATURES_UNPACK_DEPTH(features);
       return true;
    case EGL_LEVEL:
       *value = 0;
       return true;
    case EGL_MATCH_NATIVE_PIXMAP:
       *value = 0;
       return true;
    case EGL_MAX_PBUFFER_WIDTH:
       *value = EGL_CONFIG_MAX_WIDTH;
       return true;
    case EGL_MAX_PBUFFER_HEIGHT:
       *value = EGL_CONFIG_MAX_HEIGHT;
       return true;
    case EGL_MAX_PBUFFER_PIXELS:
       *value = EGL_CONFIG_MAX_WIDTH * EGL_CONFIG_MAX_HEIGHT;
       return true;
    case EGL_MAX_SWAP_INTERVAL:
       *value = EGL_CONFIG_MAX_SWAP_INTERVAL;
       return true;
    case EGL_MIN_SWAP_INTERVAL:
       *value = EGL_CONFIG_MIN_SWAP_INTERVAL;
       return true;
    case EGL_NATIVE_RENDERABLE:
       *value = EGL_TRUE;
       return true;
    case EGL_NATIVE_VISUAL_ID:
       *value = platform_get_color_format(egl_config_get_color_format(id));
       return true;
    case EGL_NATIVE_VISUAL_TYPE:
       *value = EGL_NONE;
       return true;
    case EGL_RENDERABLE_TYPE:
       *value = egl_config_get_api_support(id);
       return true;
    case EGL_SAMPLE_BUFFERS:
       *value = FEATURES_UNPACK_MULTI(features);
       return true;
    case EGL_SAMPLES:
       *value = FEATURES_UNPACK_MULTI(features) * 4;
       return true;
    case EGL_STENCIL_SIZE:
       *value = FEATURES_UNPACK_STENCIL(features);
       return true;
    case EGL_SURFACE_TYPE:
       *value = (EGLint)(EGL_PBUFFER_BIT | EGL_PIXMAP_BIT | EGL_WINDOW_BIT | EGL_VG_COLORSPACE_LINEAR_BIT | EGL_VG_ALPHA_FORMAT_PRE_BIT | EGL_MULTISAMPLE_RESOLVE_BOX_BIT | EGL_SWAP_BEHAVIOR_PRESERVED_BIT);
 #if EGL_KHR_lock_surface
       if (egl_config_is_lockable(id))
       {
          *value |= EGL_LOCK_SURFACE_BIT_KHR;
          if (egl_config_get_mapped_format(id) == egl_config_get_color_format(id))
             *value |= EGL_OPTIMAL_FORMAT_BIT_KHR;      /* Considered optimal if no format conversion needs doing. Currently all lockable surfaces are optimal */
       }
 #endif
       return true;
    case EGL_TRANSPARENT_TYPE:
       *value = EGL_NONE;
       return true;
    case EGL_TRANSPARENT_RED_VALUE:
    case EGL_TRANSPARENT_GREEN_VALUE:
    case EGL_TRANSPARENT_BLUE_VALUE:
       *value = 0;
       return true;
 #if EGL_KHR_lock_surface
    case EGL_MATCH_FORMAT_KHR:
       if (!egl_config_is_lockable(id))
          *value = EGL_NONE;
       else {
          switch (egl_config_get_mapped_format(id))
          {
          case RGB_565_RSO:
             *value = EGL_FORMAT_RGB_565_EXACT_KHR;
             break;
          case ARGB_8888_RSO:
             *value = EGL_FORMAT_RGBA_8888_EXACT_KHR;
             break;
          default:
             UNREACHABLE();
          }
       }
       return true;
 #endif
 #if EGL_ANDROID_recordable
    case EGL_RECORDABLE_ANDROID:
       *value = EGL_TRUE;
       return true;
 #endif
    default:
       return false;
    }
 }
egl_config_get_color_format()
KHRN_IMAGE_FORMAT_T egl_config_get_color_format (int id)
Definition at line 125 of file egl_client_config.c.
References FEATURES_AND_FORMATS_T::color, EGL_MAX_CONFIGS, and vcos_assert.
Referenced by egl_config_bpps_match(), and egl_config_get_api_support().
 {
    vcos_assert(id >= 0 && id < EGL_MAX_CONFIGS);
    return formats[id].color;
 }
egl_config_get_depth_format()
KHRN_IMAGE_FORMAT_T egl_config_get_depth_format (int id)
Definition at line 144 of file egl_client_config.c.
References FEATURES_AND_FORMATS_T::depth, EGL_MAX_CONFIGS, and vcos_assert.
 {
    vcos_assert(id >= 0 && id < EGL_MAX_CONFIGS);
    return formats[id].depth;
 }
egl_config_get_mask_format()
KHRN_IMAGE_FORMAT_T egl_config_get_mask_format (int id)
Definition at line 163 of file egl_client_config.c.
References EGL_MAX_CONFIGS, FEATURES_AND_FORMATS_T::mask, and vcos_assert.
 {
    vcos_assert(id >= 0 && id < EGL_MAX_CONFIGS);
    return formats[id].mask;
 }
egl_config_get_multisample()
bool egl_config_get_multisample (int id)
Definition at line 201 of file egl_client_config.c.
References EGL_MAX_CONFIGS, FEATURES_UNPACK_MULTI, and vcos_assert.
 {
    vcos_assert(id >= 0 && id < EGL_MAX_CONFIGS);
    return FEATURES_UNPACK_MULTI(formats[id].features);
 }
egl_config_get_multisample_format()
KHRN_IMAGE_FORMAT_T egl_config_get_multisample_format (int id)
Definition at line 182 of file egl_client_config.c.
References EGL_MAX_CONFIGS, FEATURES_AND_FORMATS_T::multisample, and vcos_assert.
 {
    vcos_assert(id >= 0 && id < EGL_MAX_CONFIGS);
    return formats[id].multisample;
 }
egl_config_install_configs()
void egl_config_install_configs (int type)
Definition at line 94 of file egl_client_config.c.
References ARR_COUNT, and FEATURES_AND_FORMATS_T::color.
Referenced by client_process_state_init().
 {
    uint32_t i;
    for (i = 0; i != ARR_COUNT(formats); ++i) {
       formats[i].color = (type == 0) ?
          khrn_image_to_rso_format(formats[i].color) :
          khrn_image_to_tf_format(formats[i].color);
    }
 }
egl_config_match_pixmap_info()
bool egl_config_match_pixmap_info (int id, KHRN_IMAGE_WRAP_T * image)
Definition at line 265 of file egl_client_config.c.
References EGL_MAX_CONFIGS, FEATURES_AND_FORMATS_T::features, FEATURES_UNPACK_ALPHA, FEATURES_UNPACK_BLUE, FEATURES_UNPACK_GREEN, FEATURES_UNPACK_RED, KHRN_IMAGE_WRAP_T::format, khrn_image_get_alpha_size(), khrn_image_get_blue_size(), khrn_image_get_green_size(), khrn_image_get_red_size(), and vcos_assert.
Referenced by egl_config_filter().
 {
    FEATURES_T features = formats[id].features;
    KHRN_IMAGE_FORMAT_T format = image->format;
    vcos_assert(id >= 0 && id < EGL_MAX_CONFIGS);
    return
       khrn_image_get_red_size(format)   == FEATURES_UNPACK_RED(features) &&
       khrn_image_get_green_size(format) == FEATURES_UNPACK_GREEN(features) &&
       khrn_image_get_blue_size(format)  == FEATURES_UNPACK_BLUE(features) &&
       khrn_image_get_alpha_size(format) == FEATURES_UNPACK_ALPHA(features);
 }
egl_config_sort()
void egl_config_sort (int * ids, bool use_red, bool use_green, bool use_blue, bool use_alpha)
Definition at line 414 of file egl_client_config_cr.c.
References EGL_MAX_CONFIGS.
 {
    int i, j;
    for (i = 1; i < EGL_MAX_CONFIGS; i++)
       for (j = 0; j < EGL_MAX_CONFIGS - i; j++)
          if (less_than(ids[j + 1], ids[j], use_red, use_green, use_blue, use_alpha)) {
             int temp = ids[j];
             ids[j] = ids[j + 1];
             ids[j + 1] = temp;
          }
 }