VideoCore Library: host_applications/linux/libs/bcm_host/include/bcm_host.h File Reference
bcm_host.h File Reference
#include <stdint.h>
#include "interface/vmcs_host/vc_dispmanx.h"
#include "interface/vmcs_host/vc_tvservice.h"
#include "interface/vmcs_host/vc_cec.h"
#include "interface/vmcs_host/vc_cecservice.h"
#include "interface/vmcs_host/vcgencmd.h"
Macros
#define BCM_HOST_BOARD_TYPE_MODELA 0
#define BCM_HOST_BOARD_TYPE_MODELB 1
#define BCM_HOST_BOARD_TYPE_MODELAPLUS 2
#define BCM_HOST_BOARD_TYPE_MODELBPLUS 3
#define BCM_HOST_BOARD_TYPE_PI2MODELB 4
#define BCM_HOST_BOARD_TYPE_ALPHA 5
#define BCM_HOST_BOARD_TYPE_CM 6
#define BCM_HOST_BOARD_TYPE_CM2 7
#define BCM_HOST_BOARD_TYPE_PI3MODELB 8
#define BCM_HOST_BOARD_TYPE_PI0 9
#define BCM_HOST_BOARD_TYPE_CM3 0xa
#define BCM_HOST_BOARD_TYPE_CUSTOM 0xb
#define BCM_HOST_BOARD_TYPE_PI0W 0xc
#define BCM_HOST_BOARD_TYPE_PI3MODELBPLUS 0xd
#define BCM_HOST_BOARD_TYPE_PI3MODELAPLUS 0xe
#define BCM_HOST_BOARD_TYPE_FPGA 0xf
#define BCM_HOST_BOARD_TYPE_CM3PLUS 0x10
#define BCM_HOST_BOARD_TYPE_PI4MODELB 0x11
#define BCM_HOST_PROCESSOR_BCM2835 0
#define BCM_HOST_PROCESSOR_BCM2836 1
#define BCM_HOST_PROCESSOR_BCM2837 2
#define BCM_HOST_PROCESSOR_BCM2838 3
Functions
void bcm_host_init (void)
void bcm_host_deinit (void)
int32_t graphics_get_display_size (const uint16_t display_number, uint32_t *width, uint32_t *height)
unsigned bcm_host_get_peripheral_address (void)
unsigned bcm_host_get_peripheral_size (void)
unsigned bcm_host_get_sdram_address (void)
int bcm_host_get_model_type (void)
int bcm_host_is_model_pi4 (void)
int bcm_host_is_fkms_active (void)
int bcm_host_is_kms_active (void)
int bcm_host_get_processor_id (void)
Macro Definition Documentation
BCM_HOST_BOARD_TYPE_ALPHA
#define BCM_HOST_BOARD_TYPE_ALPHA 5
Definition at line 63 of file bcm_host.h.
BCM_HOST_BOARD_TYPE_CM
#define BCM_HOST_BOARD_TYPE_CM 6
Definition at line 64 of file bcm_host.h.
BCM_HOST_BOARD_TYPE_CM2
#define BCM_HOST_BOARD_TYPE_CM2 7
Definition at line 65 of file bcm_host.h.
BCM_HOST_BOARD_TYPE_CM3
#define BCM_HOST_BOARD_TYPE_CM3 0xa
Definition at line 68 of file bcm_host.h.
BCM_HOST_BOARD_TYPE_CM3PLUS
#define BCM_HOST_BOARD_TYPE_CM3PLUS 0x10
Definition at line 74 of file bcm_host.h.
BCM_HOST_BOARD_TYPE_CUSTOM
#define BCM_HOST_BOARD_TYPE_CUSTOM 0xb
Definition at line 69 of file bcm_host.h.
BCM_HOST_BOARD_TYPE_FPGA
#define BCM_HOST_BOARD_TYPE_FPGA 0xf
Definition at line 73 of file bcm_host.h.
BCM_HOST_BOARD_TYPE_MODELA
#define BCM_HOST_BOARD_TYPE_MODELA 0
Definition at line 58 of file bcm_host.h.
BCM_HOST_BOARD_TYPE_MODELAPLUS
#define BCM_HOST_BOARD_TYPE_MODELAPLUS 2
Definition at line 60 of file bcm_host.h.
BCM_HOST_BOARD_TYPE_MODELB
#define BCM_HOST_BOARD_TYPE_MODELB 1
Definition at line 59 of file bcm_host.h.
BCM_HOST_BOARD_TYPE_MODELBPLUS
#define BCM_HOST_BOARD_TYPE_MODELBPLUS 3
Definition at line 61 of file bcm_host.h.
BCM_HOST_BOARD_TYPE_PI0
#define BCM_HOST_BOARD_TYPE_PI0 9
Definition at line 67 of file bcm_host.h.
BCM_HOST_BOARD_TYPE_PI0W
#define BCM_HOST_BOARD_TYPE_PI0W 0xc
Definition at line 70 of file bcm_host.h.
BCM_HOST_BOARD_TYPE_PI2MODELB
#define BCM_HOST_BOARD_TYPE_PI2MODELB 4
Definition at line 62 of file bcm_host.h.
BCM_HOST_BOARD_TYPE_PI3MODELAPLUS
#define BCM_HOST_BOARD_TYPE_PI3MODELAPLUS 0xe
Definition at line 72 of file bcm_host.h.
BCM_HOST_BOARD_TYPE_PI3MODELB
#define BCM_HOST_BOARD_TYPE_PI3MODELB 8
Definition at line 66 of file bcm_host.h.
BCM_HOST_BOARD_TYPE_PI3MODELBPLUS
#define BCM_HOST_BOARD_TYPE_PI3MODELBPLUS 0xd
Definition at line 71 of file bcm_host.h.
BCM_HOST_BOARD_TYPE_PI4MODELB
#define BCM_HOST_BOARD_TYPE_PI4MODELB 0x11
Definition at line 75 of file bcm_host.h.
BCM_HOST_PROCESSOR_BCM2835
#define BCM_HOST_PROCESSOR_BCM2835 0
Definition at line 93 of file bcm_host.h.
BCM_HOST_PROCESSOR_BCM2836
#define BCM_HOST_PROCESSOR_BCM2836 1
Definition at line 94 of file bcm_host.h.
BCM_HOST_PROCESSOR_BCM2837
#define BCM_HOST_PROCESSOR_BCM2837 2
Definition at line 95 of file bcm_host.h.
BCM_HOST_PROCESSOR_BCM2838
#define BCM_HOST_PROCESSOR_BCM2838 3
Definition at line 96 of file bcm_host.h.
Function Documentation
bcm_host_deinit()
void bcm_host_deinit (void)
Definition at line 126 of file bcm_host.c.
 {
 }
bcm_host_get_model_type()
int bcm_host_get_model_type (void)
Definition at line 219 of file bcm_host.c.
Referenced by bcm_host_is_model_pi4().
 {
    static int model_type = -1;
    if (model_type != -1)
       return model_type;
    unsigned int revision_num = get_revision_code();
    if (!revision_num)
       model_type = 0;
    // Check for old/new style revision code. Bit 23 will be guaranteed one for new style
    else if (revision_num & 0x800000)
       model_type = (revision_num & 0xff0) >> 4;
    else
    {
       // Mask off warrantee and overclock bits.
       revision_num &= 0xffffff;
       // Map old style to new Type code
       if (revision_num < 2 || revision_num > 21)
          return 0;
       static const unsigned char type_map[] =
       {
          1,   // B rev 1.0  2
          1,   // B rev 1.0  3
          1,   // B rev 2.0  4
          1,   // B rev 2.0  5
          1,   // B rev 2.0  6
          0,   // A rev 2    7
          0,   // A rev 2    8
          0,   // A rev 2    9
          0, 0, 0,  // unused  a,b,c
          1,   // B  rev 2.0  d
          1,   // B rev 2.0  e
          1,   // B rev 2.0  f
          3,   // B+ rev 1.2 10
          6,   // CM1        11
          2,   // A+ rev1.1  12
          3,   // B+ rev 1.2 13
          6,   // CM1        14
          2    // A+         15
       };
       model_type = type_map[revision_num-2];
    }
    return model_type;
 }
bcm_host_get_peripheral_address()
unsigned bcm_host_get_peripheral_address (void)
Definition at line 151 of file bcm_host.c.
Referenced by gpu_fft_get_host_info().
 {
    unsigned address = get_dt_ranges("/proc/device-tree/soc/ranges", 4);
    if (address == 0)
       address = get_dt_ranges("/proc/device-tree/soc/ranges", 8);
    return address == ~0 ? 0x20000000 : address;
 }
bcm_host_get_peripheral_size()
unsigned bcm_host_get_peripheral_size (void)
Definition at line 159 of file bcm_host.c.
Referenced by gpu_fft_get_host_info().
 {
    unsigned address = get_dt_ranges("/proc/device-tree/soc/ranges", 4);
    address = get_dt_ranges("/proc/device-tree/soc/ranges", (address == 0) ? 12 : 8);
    return address == ~0 ? 0x01000000 : address;
 }
bcm_host_get_processor_id()
int bcm_host_get_processor_id (void)
Definition at line 277 of file bcm_host.c.
 {
    unsigned int revision_num = get_revision_code();
    if (revision_num & 0x800000)
    {
       return (revision_num & 0xf000) >> 12;
    }
    else
    {
       // Old style number only used 2835
       return BCM_HOST_PROCESSOR_BCM2835;
    }
 }
bcm_host_get_sdram_address()
unsigned bcm_host_get_sdram_address (void)
Definition at line 166 of file bcm_host.c.
Referenced by gpu_fft_get_host_info().
 {
    unsigned address = get_dt_ranges("/proc/device-tree/axi/vc_mem/reg", 8);
    return address == ~0 ? 0x40000000 : address;
 }
bcm_host_init()
void bcm_host_init (void)
Definition at line 84 of file bcm_host.c.
References vchi_initialise(), vchiq_initialise(), vchiq_instance, VCHIQ_SUCCESS, and vcos_init().
Referenced by deinit(), main(), and runApp().
 {
    VCHIQ_INSTANCE_T vchiq_instance;
    static int initted;
    int success = -1;
    char response[ 128 ];
    if (initted)
     return;
    initted = 1;
    vcos_init();
    if (vchiq_initialise(&vchiq_instance) != VCHIQ_SUCCESS)
    {
       printf("* failed to open vchiq instance\n");
       exit(-1);
    }
    vcos_log("vchi_initialise");
    success = vchi_initialise( &global_initialise_instance);
    vcos_assert(success == 0);
    vchiq_instance = (VCHIQ_INSTANCE_T)global_initialise_instance;
    global_connection = vchi_create_connection(single_get_func_table(),
                                               vchi_mphi_message_driver_func_table());
    vcos_log("vchi_connect");
    vchi_connect(&global_connection, 1, global_initialise_instance);
    vc_vchi_gencmd_init (global_initialise_instance, &global_connection, 1);
    vc_vchi_dispmanx_init (global_initialise_instance, &global_connection, 1);
    vc_vchi_tv_init (global_initialise_instance, &global_connection, 1);
    vc_vchi_cec_init (global_initialise_instance, &global_connection, 1);
    //vc_vchi_bufman_init (global_initialise_instance, &global_connection, 1);
    if ( success == 0 )
    {
       success = vc_gencmd( response, sizeof(response), "set_vll_dir /sd/vlls" );
       vcos_assert( success == 0 );
    }
 }
bcm_host_is_fkms_active()
int bcm_host_is_fkms_active (void)
Definition at line 302 of file bcm_host.c.
 {
    static int active = -1;
    if (active == -1)
       active = bcm_host_is_fkms_or_kms_active(0);
    return active;
 }
bcm_host_is_kms_active()
int bcm_host_is_kms_active (void)
Definition at line 310 of file bcm_host.c.
 {
    static int active = -1;
    if (active == -1)
       active = bcm_host_is_fkms_or_kms_active(1);
    return active;
 }
bcm_host_is_model_pi4()
int bcm_host_is_model_pi4 (void)
Definition at line 270 of file bcm_host.c.
References bcm_host_get_model_type().
 {
    return bcm_host_get_model_type() == 0x11 ? 1 : 0;
 }
graphics_get_display_size()
int32_t graphics_get_display_size (const uint16_t display_number, uint32_t * width, uint32_t * height)
Definition at line 1391 of file graphics.c.
References DISPMANX_MODEINFO_T::height, MAX_DISPLAY_HANDLES, NULL, vc_dispmanx_display_close(), vc_dispmanx_display_get_info(), vc_dispmanx_display_open(), vcos_assert, vcos_verify, and DISPMANX_MODEINFO_T::width.
Referenced by deinit(), and main().
 {
    DISPMANX_MODEINFO_T mode_info;
    int32_t success = -1;
    DISPMANX_DISPLAY_HANDLE_T disp;
    vcos_assert(width && height);
    *width = *height = 0;
    if(vcos_verify(display_number < MAX_DISPLAY_HANDLES))
    {
       // TODO Shouldn't this close the display if it wasn't previously open?
       if (gx_priv_open_screen(display_number, &disp) < 0)
       {
          vcos_assert(0);
          return -1;
       }
       success = vc_dispmanx_display_get_info(disp, &mode_info);
       if( success >= 0 )
       {
          *width = mode_info.width;
          *height = mode_info.height;
          vcos_assert(*height > 64);
       }
       else
       {
          vcos_assert(0);
       }
    }
    return success;
 }