VideoCore Library: interface/khronos/common/khrn_int_image.c File Reference
khrn_int_image.c File Reference
#include "interface/khronos/common/khrn_int_common.h"
#include "interface/khronos/common/khrn_int_image.h"
#include "interface/khronos/common/khrn_int_util.h"
Functions
uint32_t khrn_image_get_bpp (KHRN_IMAGE_FORMAT_T format)
uint32_t khrn_image_get_red_size (KHRN_IMAGE_FORMAT_T format)
uint32_t khrn_image_get_green_size (KHRN_IMAGE_FORMAT_T format)
uint32_t khrn_image_get_blue_size (KHRN_IMAGE_FORMAT_T format)
uint32_t khrn_image_get_alpha_size (KHRN_IMAGE_FORMAT_T format)
uint32_t khrn_image_get_z_size (KHRN_IMAGE_FORMAT_T format)
uint32_t khrn_image_get_stencil_size (KHRN_IMAGE_FORMAT_T format)
uint32_t khrn_image_get_log2_brcm2_width (KHRN_IMAGE_FORMAT_T format)
uint32_t khrn_image_get_log2_brcm2_height (KHRN_IMAGE_FORMAT_T format)
uint32_t khrn_image_get_log2_brcm1_width (KHRN_IMAGE_FORMAT_T format)
uint32_t khrn_image_get_log2_brcm1_height (KHRN_IMAGE_FORMAT_T format)
uint32_t khrn_image_pad_width (KHRN_IMAGE_FORMAT_T format, uint32_t width)
uint32_t khrn_image_pad_height (KHRN_IMAGE_FORMAT_T format, uint32_t height)
uint32_t khrn_image_get_stride (KHRN_IMAGE_FORMAT_T format, uint32_t width)
uint32_t khrn_image_get_size (KHRN_IMAGE_FORMAT_T format, uint32_t width, uint32_t height)
void khrn_image_wrap (KHRN_IMAGE_WRAP_T *wrap, KHRN_IMAGE_FORMAT_T format, uint32_t width, uint32_t height, int32_t stride, void *storage)
Function Documentation
khrn_image_get_alpha_size()
uint32_t khrn_image_get_alpha_size (KHRN_IMAGE_FORMAT_T format)
Definition at line 127 of file khrn_int_image.c.
Referenced by egl_config_match_pixmap_info().
 {
    if (khrn_image_is_color(format) && (format & IMAGE_FORMAT_A)) {
       switch (format & (IMAGE_FORMAT_PIXEL_SIZE_MASK | IMAGE_FORMAT_PIXEL_LAYOUT_MASK)) {
       case (IMAGE_FORMAT_32 | IMAGE_FORMAT_8888): return 8;
       case (IMAGE_FORMAT_16 | IMAGE_FORMAT_4444): return 4;
       case (IMAGE_FORMAT_16 | IMAGE_FORMAT_5551): return 1;
       case (IMAGE_FORMAT_16 | IMAGE_FORMAT_88):   return 8;
       case IMAGE_FORMAT_8:                        return 8;
       case IMAGE_FORMAT_4:                        return 4;
       case IMAGE_FORMAT_1:                        return 1;
       default:                                    UNREACHABLE(); return 0;
       }
    } else {
       return 0;
    }
 }
khrn_image_get_blue_size()
uint32_t khrn_image_get_blue_size (KHRN_IMAGE_FORMAT_T format)
Definition at line 106 of file khrn_int_image.c.
Referenced by egl_config_match_pixmap_info().
 {
    if (khrn_image_is_color(format) && (format & IMAGE_FORMAT_RGB)) {
       switch (format & (IMAGE_FORMAT_PIXEL_SIZE_MASK | IMAGE_FORMAT_PIXEL_LAYOUT_MASK)) {
       case (IMAGE_FORMAT_32 | IMAGE_FORMAT_8888): return 8;
       case (IMAGE_FORMAT_24 | IMAGE_FORMAT_888):  return 8;
       case (IMAGE_FORMAT_16 | IMAGE_FORMAT_4444): return 4;
       case (IMAGE_FORMAT_16 | IMAGE_FORMAT_5551): return 5;
       case (IMAGE_FORMAT_16 | IMAGE_FORMAT_565):  return 5;
       default:                                    UNREACHABLE(); return 0;
       }
    } else {
       return 0;
    }
 }
khrn_image_get_bpp()
uint32_t khrn_image_get_bpp (KHRN_IMAGE_FORMAT_T format)
Definition at line 37 of file khrn_int_image.c.
References IMAGE_FORMAT_1, IMAGE_FORMAT_16, IMAGE_FORMAT_24, IMAGE_FORMAT_32, IMAGE_FORMAT_4, IMAGE_FORMAT_64, IMAGE_FORMAT_8, IMAGE_FORMAT_COMP_MASK, IMAGE_FORMAT_ETC1, IMAGE_FORMAT_INVALID, IMAGE_FORMAT_PIXEL_SIZE_MASK, IMAGE_FORMAT_UNCOMP, IMAGE_FORMAT_YUYV, UNREACHABLE, and vcos_assert.
Referenced by khrn_image_get_stride(), and khrn_image_pad_width().
 {
    vcos_assert(format != IMAGE_FORMAT_INVALID);
    switch (format & IMAGE_FORMAT_COMP_MASK) {
    case IMAGE_FORMAT_UNCOMP:
       switch (format & IMAGE_FORMAT_PIXEL_SIZE_MASK) {
          case IMAGE_FORMAT_1:  return 1;
          case IMAGE_FORMAT_4:  return 4;
          case IMAGE_FORMAT_8:  return 8;
          case IMAGE_FORMAT_16: return 16;
          case IMAGE_FORMAT_24: return 24;
          case IMAGE_FORMAT_32: return 32;
          case IMAGE_FORMAT_64: return 64;
          default:              UNREACHABLE(); return 0;
       }
    case IMAGE_FORMAT_ETC1: return 4;
    case IMAGE_FORMAT_YUYV: return 16;
    default:                UNREACHABLE(); return 0;
    }
 }
khrn_image_get_green_size()
uint32_t khrn_image_get_green_size (KHRN_IMAGE_FORMAT_T format)
Definition at line 85 of file khrn_int_image.c.
Referenced by egl_config_match_pixmap_info().
 {
    if (khrn_image_is_color(format) && (format & IMAGE_FORMAT_RGB)) {
       switch (format & (IMAGE_FORMAT_PIXEL_SIZE_MASK | IMAGE_FORMAT_PIXEL_LAYOUT_MASK)) {
       case (IMAGE_FORMAT_32 | IMAGE_FORMAT_8888): return 8;
       case (IMAGE_FORMAT_24 | IMAGE_FORMAT_888):  return 8;
       case (IMAGE_FORMAT_16 | IMAGE_FORMAT_4444): return 4;
       case (IMAGE_FORMAT_16 | IMAGE_FORMAT_5551): return 5;
       case (IMAGE_FORMAT_16 | IMAGE_FORMAT_565):  return 6;
       default:                                    UNREACHABLE(); return 0;
       }
    } else {
       return 0;
    }
 }
khrn_image_get_log2_brcm1_height()
uint32_t khrn_image_get_log2_brcm1_height (KHRN_IMAGE_FORMAT_T format)
Definition at line 231 of file khrn_int_image.c.
References khrn_image_get_log2_brcm2_height().
 {
    return khrn_image_get_log2_brcm2_height(format) + 3;
 }
khrn_image_get_log2_brcm1_width()
uint32_t khrn_image_get_log2_brcm1_width (KHRN_IMAGE_FORMAT_T format)
Definition at line 226 of file khrn_int_image.c.
References khrn_image_get_log2_brcm2_width().
 {
    return khrn_image_get_log2_brcm2_width(format) + 3;
 }
khrn_image_get_log2_brcm2_height()
uint32_t khrn_image_get_log2_brcm2_height (KHRN_IMAGE_FORMAT_T format)
Definition at line 204 of file khrn_int_image.c.
References vcos_assert.
Referenced by khrn_image_get_log2_brcm1_height().
 {
    vcos_assert(khrn_image_is_brcm1(format) || khrn_image_is_brcm2(format));
    switch (format & IMAGE_FORMAT_COMP_MASK) {
    case IMAGE_FORMAT_UNCOMP:
    {
       switch (format & IMAGE_FORMAT_PIXEL_SIZE_MASK) {
       case IMAGE_FORMAT_1:  return 3;
       case IMAGE_FORMAT_4:  return 3;
       case IMAGE_FORMAT_8:  return 3;
       case IMAGE_FORMAT_16: return 2;
       case IMAGE_FORMAT_32: return 2;
       default:              UNREACHABLE(); return 0;
       }
    }
    case IMAGE_FORMAT_ETC1: return 4;
    case IMAGE_FORMAT_YUYV: return 2;
    default:                UNREACHABLE(); return 0;
    }
 }
khrn_image_get_log2_brcm2_width()
uint32_t khrn_image_get_log2_brcm2_width (KHRN_IMAGE_FORMAT_T format)
Definition at line 182 of file khrn_int_image.c.
References vcos_assert.
Referenced by khrn_image_get_log2_brcm1_width().
 {
    vcos_assert(khrn_image_is_brcm1(format) || khrn_image_is_brcm2(format));
    switch (format & IMAGE_FORMAT_COMP_MASK) {
    case IMAGE_FORMAT_UNCOMP:
    {
       switch (format & IMAGE_FORMAT_PIXEL_SIZE_MASK) {
       case IMAGE_FORMAT_1:  return 6;
       case IMAGE_FORMAT_4:  return 4;
       case IMAGE_FORMAT_8:  return 3;
       case IMAGE_FORMAT_16: return 3;
       case IMAGE_FORMAT_32: return 2;
       default:              UNREACHABLE(); return 0;
       }
    }
    case IMAGE_FORMAT_ETC1: return 3;
    case IMAGE_FORMAT_YUYV: return 3;
    default:                UNREACHABLE(); return 0;
    }
 }
khrn_image_get_red_size()
uint32_t khrn_image_get_red_size (KHRN_IMAGE_FORMAT_T format)
Definition at line 64 of file khrn_int_image.c.
Referenced by egl_config_match_pixmap_info().
 {
    if (khrn_image_is_color(format) && (format & IMAGE_FORMAT_RGB)) {
       switch (format & (IMAGE_FORMAT_PIXEL_SIZE_MASK | IMAGE_FORMAT_PIXEL_LAYOUT_MASK)) {
       case (IMAGE_FORMAT_32 | IMAGE_FORMAT_8888): return 8;
       case (IMAGE_FORMAT_24 | IMAGE_FORMAT_888):  return 8;
       case (IMAGE_FORMAT_16 | IMAGE_FORMAT_4444): return 4;
       case (IMAGE_FORMAT_16 | IMAGE_FORMAT_5551): return 5;
       case (IMAGE_FORMAT_16 | IMAGE_FORMAT_565):  return 5;
       default:                                    UNREACHABLE(); return 0;
       }
    } else {
       return 0;
    }
 }
khrn_image_get_size()
uint32_t khrn_image_get_size (KHRN_IMAGE_FORMAT_T format, uint32_t width, uint32_t height)
Definition at line 273 of file khrn_int_image.c.
References khrn_image_get_stride(), and khrn_image_pad_height().
 {
    uint32_t size = khrn_image_get_stride(format, width) * khrn_image_pad_height(format, height);
 #ifdef WORKAROUND_HW2038
    if (khrn_image_is_brcm1(format) || khrn_image_is_brcm2(format)) {
       uint32_t log2_brcm2_width = khrn_image_get_log2_brcm2_width(format);
       uint32_t log2_brcm2_height = khrn_image_get_log2_brcm2_height(format);
       uint32_t width_in_brcm2s = (width + ((1 << log2_brcm2_width) - 1)) >> log2_brcm2_width;
       uint32_t height_in_brcm2s = (height + ((1 << log2_brcm2_height) - 1)) >> log2_brcm2_height;
       uint32_t hw2038_size =
          ((((height_in_brcm2s - 1) >> 3) << 7) +
          ((width_in_brcm2s - 1) >> 3) + 1) << 6;
       size = _max(size, hw2038_size);
    } /* else: can't bind it as a texture */
 #endif
    return size;
 }
khrn_image_get_stencil_size()
uint32_t khrn_image_get_stencil_size (KHRN_IMAGE_FORMAT_T format)
Definition at line 170 of file khrn_int_image.c.
 {
    if (khrn_image_is_depth(format) && (format & IMAGE_FORMAT_STENCIL)) {
       if (format == DEPTH_32_TLBD || format == DEPTH_COL_64_TLBD)
          return 8;
       vcos_assert((format & IMAGE_FORMAT_PIXEL_SIZE_MASK) == IMAGE_FORMAT_32);
       return 8;
    } else {
       return 0;
    }
 }
khrn_image_get_stride()
uint32_t khrn_image_get_stride (KHRN_IMAGE_FORMAT_T format, uint32_t width)
Definition at line 268 of file khrn_int_image.c.
References khrn_image_get_bpp(), and khrn_image_pad_width().
Referenced by khrn_image_get_size().
 {
    return (khrn_image_pad_width(format, width) * khrn_image_get_bpp(format)) >> 3;
 }
khrn_image_get_z_size()
uint32_t khrn_image_get_z_size (KHRN_IMAGE_FORMAT_T format)
Definition at line 150 of file khrn_int_image.c.
 {
    if (khrn_image_is_depth(format) && (format & IMAGE_FORMAT_Z)) {
       if (format == DEPTH_32_TLBD || format == DEPTH_COL_64_TLBD)
          return 24;
       switch (format & IMAGE_FORMAT_PIXEL_SIZE_MASK) {
       case IMAGE_FORMAT_32: return 24;
       case IMAGE_FORMAT_16: return 16;
       default:              UNREACHABLE(); return 0;
       }
    } else {
       return 0;
    }
 }
khrn_image_pad_height()
uint32_t khrn_image_pad_height (KHRN_IMAGE_FORMAT_T format, uint32_t height)
Definition at line 255 of file khrn_int_image.c.
References IMAGE_FORMAT_BRCM1, IMAGE_FORMAT_INVALID, IMAGE_FORMAT_MEM_LAYOUT_MASK, IMAGE_FORMAT_RSO, and vcos_assert.
Referenced by khrn_image_get_size().
 {
    vcos_assert(format != IMAGE_FORMAT_INVALID);
    switch (format & IMAGE_FORMAT_MEM_LAYOUT_MASK) {
    case IMAGE_FORMAT_RSO: return height;
    case IMAGE_FORMAT_BRCM1:  return round_up(height, (uint32_t) (1 << khrn_image_get_log2_brcm1_height(format)));
    case IMAGE_FORMAT_BRCM2:  return round_up(height, (uint32_t) (1 << khrn_image_get_log2_brcm2_height(format)));
    case IMAGE_FORMAT_BRCM4: return round_up(height, 64);
    default:               UNREACHABLE(); return 0;
    }
 }
khrn_image_pad_width()
uint32_t khrn_image_pad_width (KHRN_IMAGE_FORMAT_T format, uint32_t width)
Definition at line 240 of file khrn_int_image.c.
References IMAGE_FORMAT_BRCM1, IMAGE_FORMAT_INVALID, IMAGE_FORMAT_MEM_LAYOUT_MASK, IMAGE_FORMAT_RSO, khrn_image_get_bpp(), and vcos_assert.
Referenced by khrn_image_get_stride().
 {
    vcos_assert(format != IMAGE_FORMAT_INVALID);
    switch (format & IMAGE_FORMAT_MEM_LAYOUT_MASK) {
    case IMAGE_FORMAT_RSO:
       vcos_assert(!(khrn_image_get_bpp(format) & 7));
       return width;
    case IMAGE_FORMAT_BRCM1:  return round_up(width, (uint32_t) (1 << khrn_image_get_log2_brcm1_width(format)));
    case IMAGE_FORMAT_BRCM2:  return round_up(width, (uint32_t) (1 << khrn_image_get_log2_brcm2_width(format)));
    case IMAGE_FORMAT_BRCM4: return round_up(width, 64);
    default:               UNREACHABLE(); return 0;
    }
 }
khrn_image_wrap()
void khrn_image_wrap (KHRN_IMAGE_WRAP_T * wrap, KHRN_IMAGE_FORMAT_T format, uint32_t width, uint32_t height, int32_t stride, void * storage)
Definition at line 291 of file khrn_int_image.c.
References KHRN_IMAGE_WRAP_T::aux, KHRN_IMAGE_WRAP_T::format, KHRN_IMAGE_WRAP_T::height, NULL, KHRN_IMAGE_WRAP_T::storage, KHRN_IMAGE_WRAP_T::stride, and KHRN_IMAGE_WRAP_T::width.
 {
    wrap->format = format;
    wrap->width = (uint16_t)width;
    wrap->height = (uint16_t)height;
    wrap->stride = stride;
    wrap->aux = NULL;
    wrap->storage = storage;
 }