VideoCore Library: host_applications/linux/apps/hello_pi/libs/ilclient/ilclient.h File Reference
ilclient.h File Reference
#include "IL/OMX_Broadcom.h"
#include "interface/vcos/vcos.h"
Classes
struct TUNNEL_T
This structure represents a tunnel in the OpenMAX IL API.
Macros
#define set_tunnel(t, a, b, c, d)
#define ILC_GET_HANDLE(x) ilclient_get_handle(x)
#define ilclient_ticks_from_s64(s) (s)
#define ilclient_ticks_to_s64(t) (t)
Typedefs
typedef struct _ILCLIENT_T ILCLIENT_T
typedef struct _ILEVENT_T ILEVENT_T
typedef struct _COMPONENT_T COMPONENT_T
typedef void(* ILCLIENT_CALLBACK_T) (void *userdata, COMPONENT_T *comp, OMX_U32 data)
typedef void(* ILCLIENT_BUFFER_CALLBACK_T) (void *data, COMPONENT_T *comp)
typedef void *(* ILCLIENT_MALLOC_T) (void *userdata, VCOS_UNSIGNED size, VCOS_UNSIGNED align, const char *description)
typedef void(* ILCLIENT_FREE_T) (void *userdata, void *pointer)
Enumerations
enum ILEVENT_MASK_T {
ILCLIENT_EMPTY_BUFFER_DONE = 0x1, ILCLIENT_FILL_BUFFER_DONE = 0x2, ILCLIENT_PORT_DISABLED = 0x4, ILCLIENT_PORT_ENABLED = 0x8,
ILCLIENT_STATE_CHANGED = 0x10, ILCLIENT_BUFFER_FLAG_EOS = 0x20, ILCLIENT_PARAMETER_CHANGED = 0x40, ILCLIENT_EVENT_ERROR = 0x80,
ILCLIENT_PORT_FLUSH = 0x100, ILCLIENT_MARKED_BUFFER = 0x200, ILCLIENT_BUFFER_MARK = 0x400, ILCLIENT_CONFIG_CHANGED = 0x800
}
enum ILCLIENT_CREATE_FLAGS_T {
ILCLIENT_FLAGS_NONE = 0x0, ILCLIENT_ENABLE_INPUT_BUFFERS = 0x1, ILCLIENT_ENABLE_OUTPUT_BUFFERS = 0x2, ILCLIENT_DISABLE_ALL_PORTS = 0x4,
ILCLIENT_HOST_COMPONENT = 0x8, ILCLIENT_OUTPUT_ZERO_BUFFERS = 0x10
}
Functions
VCHPRE_ ILCLIENT_T VCHPOST_ * ilclient_init (void)
VCHPRE_ void VCHPOST_ ilclient_destroy (ILCLIENT_T *handle)
VCHPRE_ void VCHPOST_ ilclient_set_port_settings_callback (ILCLIENT_T *handle, ILCLIENT_CALLBACK_T func, void *userdata)
VCHPRE_ void VCHPOST_ ilclient_set_eos_callback (ILCLIENT_T *handle, ILCLIENT_CALLBACK_T func, void *userdata)
VCHPRE_ void VCHPOST_ ilclient_set_error_callback (ILCLIENT_T *handle, ILCLIENT_CALLBACK_T func, void *userdata)
VCHPRE_ void VCHPOST_ ilclient_set_configchanged_callback (ILCLIENT_T *handle, ILCLIENT_CALLBACK_T func, void *userdata)
VCHPRE_ void VCHPOST_ ilclient_set_fill_buffer_done_callback (ILCLIENT_T *handle, ILCLIENT_BUFFER_CALLBACK_T func, void *userdata)
VCHPRE_ void VCHPOST_ ilclient_set_empty_buffer_done_callback (ILCLIENT_T *handle, ILCLIENT_BUFFER_CALLBACK_T func, void *userdata)
VCHPRE_ int VCHPOST_ ilclient_create_component (ILCLIENT_T *handle, COMPONENT_T **comp, char *name, ILCLIENT_CREATE_FLAGS_T flags)
VCHPRE_ void VCHPOST_ ilclient_cleanup_components (COMPONENT_T *list[])
VCHPRE_ int VCHPOST_ ilclient_change_component_state (COMPONENT_T *comp, OMX_STATETYPE state)
VCHPRE_ void VCHPOST_ ilclient_state_transition (COMPONENT_T *list[], OMX_STATETYPE state)
VCHPRE_ void VCHPOST_ ilclient_disable_port (COMPONENT_T *comp, int portIndex)
VCHPRE_ void VCHPOST_ ilclient_enable_port (COMPONENT_T *comp, int portIndex)
VCHPRE_ int VCHPOST_ ilclient_enable_port_buffers (COMPONENT_T *comp, int portIndex, ILCLIENT_MALLOC_T ilclient_malloc, ILCLIENT_FREE_T ilclient_free, void *userdata)
VCHPRE_ void VCHPOST_ ilclient_disable_port_buffers (COMPONENT_T *comp, int portIndex, OMX_BUFFERHEADERTYPE *bufferList, ILCLIENT_FREE_T ilclient_free, void *userdata)
VCHPRE_ int VCHPOST_ ilclient_setup_tunnel (TUNNEL_T *tunnel, unsigned int portStream, int timeout)
VCHPRE_ void VCHPOST_ ilclient_disable_tunnel (TUNNEL_T *tunnel)
VCHPRE_ int VCHPOST_ ilclient_enable_tunnel (TUNNEL_T *tunnel)
VCHPRE_ void VCHPOST_ ilclient_flush_tunnels (TUNNEL_T *tunnel, int max)
VCHPRE_ void VCHPOST_ ilclient_teardown_tunnels (TUNNEL_T *tunnels)
VCHPRE_ OMX_BUFFERHEADERTYPE *VCHPOST_ ilclient_get_output_buffer (COMPONENT_T *comp, int portIndex, int block)
VCHPRE_ OMX_BUFFERHEADERTYPE *VCHPOST_ ilclient_get_input_buffer (COMPONENT_T *comp, int portIndex, int block)
VCHPRE_ int VCHPOST_ ilclient_remove_event (COMPONENT_T *comp, OMX_EVENTTYPE event, OMX_U32 nData1, int ignore1, OMX_U32 nData2, int ignore2)
VCHPRE_ void VCHPOST_ ilclient_return_events (COMPONENT_T *comp)
VCHPRE_ int VCHPOST_ ilclient_wait_for_event (COMPONENT_T *comp, OMX_EVENTTYPE event, OMX_U32 nData1, int ignore1, OMX_U32 nData2, int ignore2, int event_flag, int timeout)
VCHPRE_ int VCHPOST_ ilclient_wait_for_command_complete (COMPONENT_T *comp, OMX_COMMANDTYPE command, OMX_U32 nData2)
VCHPRE_ int VCHPOST_ ilclient_wait_for_command_complete_dual (COMPONENT_T *comp, OMX_COMMANDTYPE command, OMX_U32 nData2, COMPONENT_T *related)
VCHPRE_ void VCHPOST_ ilclient_debug_output (char *format,...)
VCHPRE_ OMX_HANDLETYPE VCHPOST_ ilclient_get_handle (COMPONENT_T *comp)
VCHPRE_ int VCHPOST_ ilclient_get_port_index (COMPONENT_T *comp, OMX_DIRTYPE dir, OMX_PORTDOMAINTYPE type, int index)
VCHPRE_ int VCHPOST_ ilclient_suggest_bufsize (COMPONENT_T *comp, OMX_U32 nBufSizeHint)
VCHPRE_ unsigned int VCHPOST_ ilclient_stack_size (void)
Macro Definition Documentation
ILC_GET_HANDLE
#define ILC_GET_HANDLE (x) ilclient_get_handle(x)
For calling OpenMAX IL methods directory, we need to access the OMX_HANDLETYPE corresponding to the COMPONENT_T structure. This macro enables this while keeping the COMPONENT_T structure opaque. The parameter x should be of the type *COMPONENT_T.
Definition at line 270 of file ilclient.h.
Referenced by audioplay_delete(), audioplay_get_latency(), audioplay_play_buffer(), audioplay_set_dest(), ilclient_suggest_bufsize(), prepareImageDecoder(), and prepareResizer().
ilclient_ticks_from_s64
#define ilclient_ticks_from_s64 (s) (s)
Macro to return OMX_TICKS from a signed 64 bit value. This is the version where OMX_TICKS is a signed 64 bit value, an alternative definition is used when OMX_TICKS is a structure.
Definition at line 958 of file ilclient.h.
ilclient_ticks_to_s64
#define ilclient_ticks_to_s64 (t) (t)
Macro to return signed 64 bit value from OMX_TICKS. This is the version where OMX_TICKS is a signed 64 bit value, an alternative definition is used when OMX_TICKS is a structure.
Definition at line 966 of file ilclient.h.
set_tunnel
#define set_tunnel (t, a, b, c, d)
Value:
do {TUNNEL_T *_ilct = (t); \
  _ilct->source = (a); _ilct->source_port = (b); \
  _ilct->sink = (c); _ilct->sink_port = (d);} while(0)
The set_tunnel macro is a useful function that initialises a TUNNEL_T structure.
Definition at line 260 of file ilclient.h.
Typedef Documentation
COMPONENT_T
typedef struct _COMPONENT_T COMPONENT_T
The COMPONENT_T structure represents an IL component, together with the necessary extra information required by the IL Client API. This structure stores the handle to the OMX component, as well as the event list containing all events sent by this component. The component state structure also holds a pair of buffer queues, for input and output buffers returned to the client by the FillBufferDone and EmptyBufferDone callbacks. As some operations result in error callbacks that can be ignored, an error mask is maintained to allow some errors to be ignored. A pointer to the client state structure is also added.
Definition at line 81 of file ilclient.h.
ILCLIENT_BUFFER_CALLBACK_T
typedef void(* ILCLIENT_BUFFER_CALLBACK_T) (void *data, COMPONENT_T *comp)
The buffer callback function is used for indicating that a component has returned a buffer on a port using client buffer communication.
Parameters
data The data returned from when the callback was registered.
comp The component from which the buffer originated.
Returns
Void.
Definition at line 111 of file ilclient.h.
ILCLIENT_CALLBACK_T
typedef void(* ILCLIENT_CALLBACK_T) (void *userdata, COMPONENT_T *comp, OMX_U32 data)
The generic callback function is used for communicating events from a particular component to the user.
Parameters
userdata The data returned from when the callback was registered.
comp The component structure representing the component that originated this event.
data The relevant data field from the event.
Returns
Void.
Definition at line 97 of file ilclient.h.
ILCLIENT_FREE_T
typedef void(* ILCLIENT_FREE_T) (void *userdata, void *pointer)
The free function is passed into ilclient_enable_port_buffers() and ilclient_disable_port_buffers() and used for freeing the buffer payload.
Parameters
userdata Private pointer passed into ilclient_enable_port_buffers() and ilclient_disable_port_buffers().
pointer Memory address to free, that was previously returned from ILCLIENT_MALLOC_T function.
Returns
Void.
Definition at line 148 of file ilclient.h.
ILCLIENT_MALLOC_T
typedef void*(* ILCLIENT_MALLOC_T) (void *userdata, VCOS_UNSIGNED size, VCOS_UNSIGNED align, const char *description)
The malloc function is passed into ilclient_enable_port_buffers() and used for allocating the buffer payload.
Parameters
userdata Private pointer passed into ilclient_enable_port_buffers() call.
size Size in bytes of the requested memory region.
align Alignment requirement in bytes for the base memory address.
description Text description of the memory being allocated.
Returns
The memory address on success, NULL on failure.
Definition at line 130 of file ilclient.h.
ILCLIENT_T
typedef struct _ILCLIENT_T ILCLIENT_T
The ILCLIENT_T structure encapsulates the state needed for the IL Client API. It contains a set of callback functions used to communicate with the user. It also includes a linked list of free event structures.
Definition at line 55 of file ilclient.h.
ILEVENT_T
typedef struct _ILEVENT_T ILEVENT_T
Each ILEVENT_T structure stores the result of an EventHandler callback from a component, storing the event message type and any parameters returned.
Definition at line 63 of file ilclient.h.
Enumeration Type Documentation
ILCLIENT_CREATE_FLAGS_T
enum ILCLIENT_CREATE_FLAGS_T
On component creation the user can set flags to control the creation of that component.
Enumerator
ILCLIENT_FLAGS_NONE
Used if no flags are set.
ILCLIENT_ENABLE_INPUT_BUFFERS
If set we allow the client to communicate with input ports via buffer communication, rather than tunneling with another component.
ILCLIENT_ENABLE_OUTPUT_BUFFERS
If set we allow the client to communicate with output ports via buffer communication, rather than tunneling with another component.
ILCLIENT_DISABLE_ALL_PORTS
If set we disable all ports on creation.
ILCLIENT_HOST_COMPONENT
Create a host component. The default host ilcore only can create host components by being locally hosted so should only be used for testing purposes.
ILCLIENT_OUTPUT_ZERO_BUFFERS
All output ports will have nBufferCountActual set to zero, if supported by the component.
Definition at line 206 of file ilclient.h.
              {
    ILCLIENT_FLAGS_NONE            = 0x0,
    ILCLIENT_ENABLE_INPUT_BUFFERS  = 0x1,
    ILCLIENT_ENABLE_OUTPUT_BUFFERS = 0x2,
    ILCLIENT_DISABLE_ALL_PORTS     = 0x4,
    ILCLIENT_HOST_COMPONENT        = 0x8,
    ILCLIENT_OUTPUT_ZERO_BUFFERS   = 0x10
 } ILCLIENT_CREATE_FLAGS_T;
ILEVENT_MASK_T
enum ILEVENT_MASK_T
The event mask enumeration describes the possible events that the user can ask to wait for when waiting for a particular event.
Enumerator
ILCLIENT_EMPTY_BUFFER_DONE
Set when a buffer is returned from an input port
ILCLIENT_FILL_BUFFER_DONE
Set when a buffer is returned from an output port
ILCLIENT_PORT_DISABLED
Set when a port indicates it has completed a disable command.
ILCLIENT_PORT_ENABLED
Set when a port indicates is has completed an enable command.
ILCLIENT_STATE_CHANGED
Set when a component indicates it has completed a state change command.
ILCLIENT_BUFFER_FLAG_EOS
Set when a port signals an EOS event.
ILCLIENT_PARAMETER_CHANGED
Set when a port signals a port settings changed event.
ILCLIENT_EVENT_ERROR
Set when a component indicates an error.
ILCLIENT_PORT_FLUSH
Set when a port indicates is has completed a flush command.
ILCLIENT_MARKED_BUFFER
Set when a port indicates it has marked a buffer.
ILCLIENT_BUFFER_MARK
Set when a port indicates it has received a buffer mark.
ILCLIENT_CONFIG_CHANGED
Set when a config parameter changed.
Definition at line 155 of file ilclient.h.
              {
    ILCLIENT_EMPTY_BUFFER_DONE  = 0x1,
    ILCLIENT_FILL_BUFFER_DONE   = 0x2,
    ILCLIENT_PORT_DISABLED      = 0x4,
    ILCLIENT_PORT_ENABLED       = 0x8,
    ILCLIENT_STATE_CHANGED      = 0x10,
    ILCLIENT_BUFFER_FLAG_EOS    = 0x20,
    ILCLIENT_PARAMETER_CHANGED  = 0x40,
    ILCLIENT_EVENT_ERROR        = 0x80,
    ILCLIENT_PORT_FLUSH         = 0x100,
    ILCLIENT_MARKED_BUFFER      = 0x200,
    ILCLIENT_BUFFER_MARK        = 0x400,
    ILCLIENT_CONFIG_CHANGED     = 0x800
 } ILEVENT_MASK_T;
Function Documentation
ilclient_change_component_state()
VCHPRE_ int VCHPOST_ ilclient_change_component_state (COMPONENT_T * comp, OMX_STATETYPE state)
The ilclient_change_component_state() function changes the state of an individual component. This will trigger the state change, and also wait for that state change to be completed. It should not be called if this state change has dependencies on other components also changing states. Trying to change a component to its current state is treated as success.
Parameters
comp The component to change.
state The new state to transition to.
Returns
0 on success, -1 on failure.
Definition at line 743 of file ilclient.c.
Referenced by audioplay_delete(), cleanup(), portSettingsChanged(), and startupImageDecoder().
 {
    OMX_ERRORTYPE error;
    error = OMX_SendCommand(comp->comp, OMX_CommandStateSet, state, NULL);
    vc_assert(error == OMX_ErrorNone);
    if(ilclient_wait_for_command_complete(comp, OMX_CommandStateSet, state) < 0)
    {
       ilclient_debug_output("ilclient: could not change component state to %d", state);
       ilclient_remove_event(comp, OMX_EventError, 0, 1, 0, 1);
       return -1;
    }
    return 0;
 }
ilclient_cleanup_components()
VCHPRE_ void VCHPOST_ ilclient_cleanup_components (COMPONENT_T * list[])
The ilclient_cleanup_components() function deallocates all state associated with components and frees the OpenMAX component handles. All tunnels connecting components should have been torn down explicitly, and all components must be in loaded state.
Parameters
list A null-terminated list of component pointers to be deallocated.
Returns
void
Definition at line 703 of file ilclient.c.
References _COMPONENT_T::comp, error(), _COMPONENT_T::event, ilclient_return_events(), NULL, OMX_ErrorNone, OMX_FreeHandle(), _COMPONENT_T::sema, vc_assert, vcos_event_flags_delete(), vcos_free(), and vcos_semaphore_delete().
Referenced by audioplay_delete().
 {
    int i;
    OMX_ERRORTYPE error;
    i=0;
    while (list[i])
    {
       ilclient_return_events(list[i]);
       if (list[i]->comp)
       {
          error = OMX_FreeHandle(list[i]->comp);
          vc_assert(error == OMX_ErrorNone);
       }
       i++;
    }
    i=0;
    while (list[i])
    {
       vcos_event_flags_delete(&list[i]->event);
       vcos_semaphore_delete(&list[i]->sema);
       vcos_free(list[i]);
       list[i] = NULL;
       i++;
    }
 }
ilclient_create_component()
VCHPRE_ int VCHPOST_ ilclient_create_component (ILCLIENT_T * handle, COMPONENT_T ** comp, char * name, ILCLIENT_CREATE_FLAGS_T flags)
Components are created using the ilclient_create_component() function.
Parameters
handle The client handle
comp On successful creation, the component structure pointer will be written back into comp.
name The name of the component to be created. Component names as provided are automatically prefixed with "OMX.broadcom." before passing to the IL core. The name provided will also be used in debugging messages added about this component.
flags The client can specify some creation behaviour by using the flags field. The meaning of each flag is defined by the ILCLIENT_CREATE_FLAGS_T type.
Returns
0 on success, -1 on failure
Definition at line 295 of file ilclient.c.
Referenced by prepareImageDecoder(), and prepareResizer().
 {
    OMX_CALLBACKTYPE callbacks;
    OMX_ERRORTYPE error;
    char component_name[128];
    int32_t status;
    *comp = vcos_malloc(sizeof(COMPONENT_T), "il:comp");
    if(!*comp)
       return -1;
    memset(*comp, 0, sizeof(COMPONENT_T));
 #define COMP_PREFIX "OMX.broadcom."
    status = vcos_event_flags_create(&(*comp)->event,"il:comp");
    vc_assert(status == VCOS_SUCCESS);
    status = vcos_semaphore_create(&(*comp)->sema, "il:comp", 1);
    vc_assert(status == VCOS_SUCCESS);
    (*comp)->client = client;
    vcos_snprintf((*comp)->name, sizeof((*comp)->name), "cl:%s", name);
    vcos_snprintf((*comp)->bufname, sizeof((*comp)->bufname), "cl:%s buffer", name);
    vcos_snprintf(component_name, sizeof(component_name), "%s%s", COMP_PREFIX, name);
    (*comp)->flags = flags;
    callbacks.EventHandler = ilclient_event_handler;
    callbacks.EmptyBufferDone = flags & ILCLIENT_ENABLE_INPUT_BUFFERS ? ilclient_empty_buffer_done : ilclient_empty_buffer_done_error;
    callbacks.FillBufferDone = flags & ILCLIENT_ENABLE_OUTPUT_BUFFERS ? ilclient_fill_buffer_done : ilclient_fill_buffer_done_error;
    error = OMX_GetHandle(&(*comp)->comp, component_name, *comp, &callbacks);
    if (error == OMX_ErrorNone)
    {
       OMX_UUIDTYPE uid;
       char name[128];
       OMX_VERSIONTYPE compVersion, specVersion;
       if(OMX_GetComponentVersion((*comp)->comp, name, &compVersion, &specVersion, &uid) == OMX_ErrorNone)
       {
          char *p = (char *) uid + strlen(COMP_PREFIX);
          vcos_snprintf((*comp)->name, sizeof((*comp)->name), "cl:%s", p);
          (*comp)->name[sizeof((*comp)->name)-1] = 0;
          vcos_snprintf((*comp)->bufname, sizeof((*comp)->bufname), "cl:%s buffer", p);
          (*comp)->bufname[sizeof((*comp)->bufname)-1] = 0;
       }
       if(flags & (ILCLIENT_DISABLE_ALL_PORTS | ILCLIENT_OUTPUT_ZERO_BUFFERS))
       {
          OMX_PORT_PARAM_TYPE ports;
          OMX_INDEXTYPE types[] = {OMX_IndexParamAudioInit, OMX_IndexParamVideoInit, OMX_IndexParamImageInit, OMX_IndexParamOtherInit};
          int i;
          ports.nSize = sizeof(OMX_PORT_PARAM_TYPE);
          ports.nVersion.nVersion = OMX_VERSION;
          for(i=0; i<4; i++)
          {
             OMX_ERRORTYPE error = OMX_GetParameter((*comp)->comp, types[i], &ports);
             if(error == OMX_ErrorNone)
             {
                uint32_t j;
                for(j=0; j<ports.nPorts; j++)
                {
                   if(flags & ILCLIENT_DISABLE_ALL_PORTS)
                      ilclient_disable_port(*comp, ports.nStartPortNumber+j);
                   if(flags & ILCLIENT_OUTPUT_ZERO_BUFFERS)
                   {
                      OMX_PARAM_PORTDEFINITIONTYPE portdef;
                      portdef.nSize = sizeof(OMX_PARAM_PORTDEFINITIONTYPE);
                      portdef.nVersion.nVersion = OMX_VERSION;
                      portdef.nPortIndex = ports.nStartPortNumber+j;
                      if(OMX_GetParameter((*comp)->comp, OMX_IndexParamPortDefinition, &portdef) == OMX_ErrorNone)
                      {
                         if(portdef.eDir == OMX_DirOutput && portdef.nBufferCountActual > 0)
{
                            portdef.nBufferCountActual = 0;
                            OMX_SetParameter((*comp)->comp, OMX_IndexParamPortDefinition, &portdef);
                         }
                      }
                   }
                }
             }
          }
       }
       return 0;
    }
    else
    {
       vcos_event_flags_delete(&(*comp)->event);
       vcos_semaphore_delete(&(*comp)->sema);
       vcos_free(*comp);
       *comp = NULL;
       return -1;
    }
 }
ilclient_debug_output()
VCHPRE_ void VCHPOST_ ilclient_debug_output (char * format, ...)
The ilclient_debug_output() function adds a message to a host-specific debug display. For a local VideoCore host the message is added to the internal message log. For a Win32 host the message is printed to the debug display. This function should be customised when IL client is ported to another platform.
Parameters
format A message to add, together with the variable argument list similar to printf and other standard C functions.
Returns
void
Definition at line 1367 of file ilclient.c.
 {
    va_list args;
    va_start(args, format);
    vcos_vlog_info(format, args);
    va_end(args);
 }
ilclient_destroy()
VCHPRE_ void VCHPOST_ ilclient_destroy (ILCLIENT_T * handle)
When all components have been deleted, the IL Client structure can be destroyed by calling the ilclient_destroy() function.
Parameters
handle The client handle. After calling this function, this handle should not be used.
Returns
void
Definition at line 193 of file ilclient.c.
References _ILCLIENT_T::event_sema, vcos_free(), VCOS_LOG_CATEGORY, vcos_log_unregister(), and vcos_semaphore_delete().
Referenced by audioplay_delete(), and cleanup().
 {
    vcos_semaphore_delete(&st->event_sema);
    vcos_free(st);
    vcos_log_unregister(VCOS_LOG_CATEGORY);
 }
ilclient_disable_port()
VCHPRE_ void VCHPOST_ ilclient_disable_port (COMPONENT_T * comp, int portIndex)
The ilclient_disable_port() function disables a port on a given component. This function sends the disable port message to the component and waits for the component to signal that this has taken place. If the port is already disabled, this is treated as a success.
Parameters
comp The component containing the port to disable.
portIndex The port index of the port to disable. This must be a named port index, rather than a OMX_ALL value.
Returns
void
Definition at line 764 of file ilclient.c.
References _COMPONENT_T::comp, error(), ilclient_wait_for_command_complete(), NULL, OMX_CommandPortDisable, OMX_ErrorNone, OMX_SendCommand, and vc_assert.
Referenced by portSettingsChanged(), and portSettingsChangedAgain().
 {
    OMX_ERRORTYPE error;
    error = OMX_SendCommand(comp->comp, OMX_CommandPortDisable, portIndex, NULL);
    vc_assert(error == OMX_ErrorNone);
    if(ilclient_wait_for_command_complete(comp, OMX_CommandPortDisable, portIndex) < 0)
       vc_assert(0);
 }
ilclient_disable_port_buffers()
VCHPRE_ void VCHPOST_ ilclient_disable_port_buffers (COMPONENT_T * comp, int portIndex, OMX_BUFFERHEADERTYPE * bufferList, ILCLIENT_FREE_T ilclient_free, void * userdata)
The ilclient_disable_port_buffers() function disables a port in base profile mode on a given component. The port is not tunneled, and has been supplied with buffers by the client.
Parameters
comp The component containing the port to disable.
portIndex The port index of the port to disable. This must be a named port index, rather than a OMX_ALL value.
bufferList A list of buffers, using pAppPrivate as the next pointer that were allocated on this port, and currently held by the application. If buffers on this port are held by IL client or the component then these are automatically freed.
ilclient_free This function is used to free the buffer payloads. If NULL then vcos_free will be used.
userdata The first argument to calls to ilclient_free.
Returns
void
Definition at line 894 of file ilclient.c.
References OMX_PARAM_PORTDEFINITIONTYPE::bEnabled, _COMPONENT_T::comp, OMX_PARAM_PORTDEFINITIONTYPE::eDir, error(), _COMPONENT_T::event, ILCLIENT_EMPTY_BUFFER_DONE, ILCLIENT_EVENT_ERROR, ILCLIENT_FILL_BUFFER_DONE, ILCLIENT_PORT_DISABLED, ilclient_remove_event(), ilclient_wait_for_command_complete(), _COMPONENT_T::in_list, _COMPONENT_T::list, OMX_PARAM_PORTDEFINITIONTYPE::nBufferCountActual, OMX_PARAM_PORTDEFINITIONTYPE::nBufferSize, _ILEVENT_T::next, OMX_BUFFERHEADERTYPE::nInputPortIndex, OMX_BUFFERHEADERTYPE::nOutputPortIndex, OMX_PARAM_PORTDEFINITIONTYPE::nPortIndex, OMX_PARAM_PORTDEFINITIONTYPE::nSize, NULL, OMX_PARAM_PORTDEFINITIONTYPE::nVersion, OMX_VERSIONTYPE::nVersion, OMX_CommandPortDisable, OMX_DirInput, OMX_ErrorNone, OMX_EventCmdComplete, OMX_EventError, OMX_FreeBuffer, OMX_GetParameter, OMX_IndexParamPortDefinition, OMX_SendCommand, OMX_TRUE, OMX_VERSION, _COMPONENT_T::out_list, OMX_BUFFERHEADERTYPE::pAppPrivate, OMX_BUFFERHEADERTYPE::pBuffer, _COMPONENT_T::sema, vc_assert, vcos_event_flags_get(), vcos_free(), VCOS_OR_CONSUME, vcos_semaphore_post(), and vcos_semaphore_wait().
Referenced by audioplay_delete().
 {
    OMX_ERRORTYPE error;
    OMX_BUFFERHEADERTYPE *list = bufferList;
    OMX_BUFFERHEADERTYPE **head, *clist, *prev;
    OMX_PARAM_PORTDEFINITIONTYPE portdef;
    int num;
    // get the buffers off the relevant queue
    memset(&portdef, 0, sizeof(OMX_PARAM_PORTDEFINITIONTYPE));
    portdef.nSize = sizeof(OMX_PARAM_PORTDEFINITIONTYPE);
    portdef.nVersion.nVersion = OMX_VERSION;
    portdef.nPortIndex = portIndex;
    // work out buffer requirements, check port is in the right state
    error = OMX_GetParameter(comp->comp, OMX_IndexParamPortDefinition, &portdef);
    if(error != OMX_ErrorNone || portdef.bEnabled != OMX_TRUE || portdef.nBufferCountActual == 0 || portdef.nBufferSize == 0)
       return;
    num = portdef.nBufferCountActual;
    error = OMX_SendCommand(comp->comp, OMX_CommandPortDisable, portIndex, NULL);
    vc_assert(error == OMX_ErrorNone);
    while(num > 0)
    {
       VCOS_UNSIGNED set;
       if(list == NULL)
       {
          vcos_semaphore_wait(&comp->sema);
          // take buffers for this port off the relevant queue
          head = portdef.eDir == OMX_DirInput ? &comp->in_list : &comp->out_list;
          clist = *head;
          prev = NULL;
          while(clist)
          {
             if((portdef.eDir == OMX_DirInput ? clist->nInputPortIndex : clist->nOutputPortIndex) == portIndex)
             {
                OMX_BUFFERHEADERTYPE *pBuffer = clist;
                if(!prev)
                   clist = *head = (OMX_BUFFERHEADERTYPE *) pBuffer->pAppPrivate;
                else
                   clist = prev->pAppPrivate = (OMX_BUFFERHEADERTYPE *) pBuffer->pAppPrivate;
                pBuffer->pAppPrivate = list;
                list = pBuffer;
             }
             else
             {
                prev = clist;
                clist = (OMX_BUFFERHEADERTYPE *) &(clist->pAppPrivate);
             }
          }
          vcos_semaphore_post(&comp->sema);
       }
       while(list)
       {
          void *buf = list->pBuffer;
          OMX_BUFFERHEADERTYPE *next = list->pAppPrivate;
          error = OMX_FreeBuffer(comp->comp, portIndex, list);
          vc_assert(error == OMX_ErrorNone);
          if(ilclient_free)
             ilclient_free(private, buf);
          else
             vcos_free(buf);
          num--;
          list = next;
       }
       if(num)
       {
          OMX_U32 mask = ILCLIENT_PORT_DISABLED | ILCLIENT_EVENT_ERROR;
          mask |= (portdef.eDir == OMX_DirInput ? ILCLIENT_EMPTY_BUFFER_DONE : ILCLIENT_FILL_BUFFER_DONE);
          // also wait for command complete/error in case we didn't have all the buffers allocated
          vcos_event_flags_get(&comp->event, mask, VCOS_OR_CONSUME, -1, &set);
          if((set & ILCLIENT_EVENT_ERROR) && ilclient_remove_event(comp, OMX_EventError, 0, 1, 1, 0) >= 0)
             return;
          if((set & ILCLIENT_PORT_DISABLED) && ilclient_remove_event(comp, OMX_EventCmdComplete, OMX_CommandPortDisable, 0, portIndex, 0) >= 0)
             return;
       }
    }
    if(ilclient_wait_for_command_complete(comp, OMX_CommandPortDisable, portIndex) < 0)
       vc_assert(0);
 }
ilclient_disable_tunnel()
VCHPRE_ void VCHPOST_ ilclient_disable_tunnel (TUNNEL_T * tunnel)
The ilclient_disable_tunnel() function disables both ports listed in the tunnel structure. It will send a port disable command to each port, then waits for both to indicate they have completed the transition. The errors OMX_ErrorPortUnpopulated and OMX_ErrorSameState are both ignored by this function; the former since the first port to disable may deallocate buffers before the second port has been disabled, leading to the second port reporting the unpopulated error.
Parameters
tunnel The tunnel to disable.
Returns
void
Definition at line 540 of file ilclient.c.
References _COMPONENT_T::comp, error(), _COMPONENT_T::error_mask, ILCLIENT_ERROR_UNPOPULATED, ilclient_wait_for_command_complete(), NULL, OMX_CommandPortDisable, OMX_ErrorNone, OMX_SendCommand, TUNNEL_T::sink, TUNNEL_T::sink_port, TUNNEL_T::source, TUNNEL_T::source_port, and vc_assert.
 {
    OMX_ERRORTYPE error;
    if(tunnel->source == 0 || tunnel->sink == 0)
       return;
    tunnel->source->error_mask |= ILCLIENT_ERROR_UNPOPULATED;
    tunnel->sink->error_mask |= ILCLIENT_ERROR_UNPOPULATED;
    error = OMX_SendCommand(tunnel->source->comp, OMX_CommandPortDisable, tunnel->source_port, NULL);
    vc_assert(error == OMX_ErrorNone);
    error = OMX_SendCommand(tunnel->sink->comp, OMX_CommandPortDisable, tunnel->sink_port, NULL);
    vc_assert(error == OMX_ErrorNone);
    if(ilclient_wait_for_command_complete(tunnel->source, OMX_CommandPortDisable, tunnel->source_port) < 0)
       vc_assert(0);
    if(ilclient_wait_for_command_complete(tunnel->sink, OMX_CommandPortDisable, tunnel->sink_port) < 0)
       vc_assert(0);
    tunnel->source->error_mask &= ~ILCLIENT_ERROR_UNPOPULATED;
    tunnel->sink->error_mask &= ~ILCLIENT_ERROR_UNPOPULATED;
 }
ilclient_enable_port()
VCHPRE_ void VCHPOST_ ilclient_enable_port (COMPONENT_T * comp, int portIndex)
The ilclient_enable_port() function enables a port on a given component. This function sends the enable port message to the component and waits for the component to signal that this has taken place. If the port is already disabled, this is treated as a success.
Parameters
comp The component containing the port to enable.
portIndex The port index of the port to enable. This must be a named port index, rather than a OMX_ALL value.
Returns
void
Definition at line 780 of file ilclient.c.
References _COMPONENT_T::comp, error(), ilclient_wait_for_command_complete(), NULL, OMX_CommandPortEnable, OMX_ErrorNone, OMX_SendCommand, and vc_assert.
Referenced by portSettingsChangedAgain().
 {
    OMX_ERRORTYPE error;
    error = OMX_SendCommand(comp->comp, OMX_CommandPortEnable, portIndex, NULL);
    vc_assert(error == OMX_ErrorNone);
    if(ilclient_wait_for_command_complete(comp, OMX_CommandPortEnable, portIndex) < 0)
       vc_assert(0);
 }
ilclient_enable_port_buffers()
VCHPRE_ int VCHPOST_ ilclient_enable_port_buffers (COMPONENT_T * comp, int portIndex, ILCLIENT_MALLOC_T ilclient_malloc, ILCLIENT_FREE_T ilclient_free, void * userdata)
The ilclient_enable_port_buffers() function enables a port in base profile mode on a given component. The port is not tunneled, so requires buffers to be allocated.
Parameters
comp The component containing the port to enable.
portIndex The port index of the port to enable. This must be a named port index, rather than a OMX_ALL value.
ilclient_malloc This function will be used to allocate buffer payloads. If NULL then vcos_malloc_aligned will be used.
ilclient_free If an error occurs, this function is used to free previously allocated payloads. If NULL then vcos_free will be used.
userdata The first argument to calls to ilclient_malloc and ilclient_free, if these arguments are not NULL.
Returns
0 indicates success. -1 indicates failure.
Definition at line 798 of file ilclient.c.
References error(), _COMPONENT_T::list, and NULL.
 {
    OMX_ERRORTYPE error;
    OMX_PARAM_PORTDEFINITIONTYPE portdef;
    OMX_BUFFERHEADERTYPE *list = NULL, **end = &list;
    OMX_STATETYPE state;
    int i;
    memset(&portdef, 0, sizeof(OMX_PARAM_PORTDEFINITIONTYPE));
    portdef.nSize = sizeof(OMX_PARAM_PORTDEFINITIONTYPE);
    portdef.nVersion.nVersion = OMX_VERSION;
    portdef.nPortIndex = portIndex;
    // work out buffer requirements, check port is in the right state
    error = OMX_GetParameter(comp->comp, OMX_IndexParamPortDefinition, &portdef);
    if(error != OMX_ErrorNone || portdef.bEnabled != OMX_FALSE || portdef.nBufferCountActual == 0 || portdef.nBufferSize == 0)
       return -1;
    // check component is in the right state to accept buffers
    error = OMX_GetState(comp->comp, &state);
    if (error != OMX_ErrorNone || !(state == OMX_StateIdle || state == OMX_StateExecuting || state == OMX_StatePause))
       return -1;
    // send the command
    error = OMX_SendCommand(comp->comp, OMX_CommandPortEnable, portIndex, NULL);
    vc_assert(error == OMX_ErrorNone);
    for (i=0; i != portdef.nBufferCountActual; i++)
    {
       unsigned char *buf;
       if(ilclient_malloc)
          buf = ilclient_malloc(private, portdef.nBufferSize, portdef.nBufferAlignment, comp->bufname);
       else
          buf = vcos_malloc_aligned(portdef.nBufferSize, portdef.nBufferAlignment, comp->bufname);
       if(!buf)
          break;
       error = OMX_UseBuffer(comp->comp, end, portIndex, NULL, portdef.nBufferSize, buf);
       if(error != OMX_ErrorNone)
       {
          if(ilclient_free)
             ilclient_free(private, buf);
          else
             vcos_free(buf);
          break;
       }
       end = (OMX_BUFFERHEADERTYPE **) &((*end)->pAppPrivate);
    }
    // queue these buffers
    vcos_semaphore_wait(&comp->sema);
    if(portdef.eDir == OMX_DirInput)
    {
       *end = comp->in_list;
       comp->in_list = list;
    }
    else
    {
       *end = comp->out_list;
       comp->out_list = list;
    }
    vcos_semaphore_post(&comp->sema);
    if(i != portdef.nBufferCountActual ||
       ilclient_wait_for_command_complete(comp, OMX_CommandPortEnable, portIndex) < 0)
    {
       ilclient_disable_port_buffers(comp, portIndex, NULL, ilclient_free, private);
       // at this point the first command might have terminated with an error, which means that
       // the port is disabled before the disable_port_buffers function is called, so we're left
       // with the error bit set and an error event in the queue.  Clear these now if they exist.
       ilclient_remove_event(comp, OMX_EventError, 0, 1, 1, 0);
       return -1;
    }
    // success
    return 0;
 }
ilclient_enable_tunnel()
VCHPRE_ int VCHPOST_ ilclient_enable_tunnel (TUNNEL_T * tunnel)
The ilclient_enable_tunnel() function enables both ports listed in the tunnel structure. It will first send a port enable command to each port. It then checks whether the sink component is not in loaded state - if so, the function waits for both ports to complete the requested port enable. If the sink component was in loaded state, then this component is transitioned to idle to allow the ports to exchange buffers and enable the ports. This is since typically this function is used when creating a tunnel between two components, where the source component is processing data to enable it to report the port settings changed event, and the sink port has yet to be used. Before transitioning the sink component to idle, this function waits for the sink port to be enabled - since the component is in loaded state, this will happen quickly. If the transition to idle fails, the sink component is transitioned back to loaded and the source port disabled. If the transition succeeds, the function then waits for the source port to complete the requested port enable.
Parameters
tunnel The tunnel to enable.
Returns
0 on success, -1 on failure.
Definition at line 573 of file ilclient.c.
 {
    OMX_STATETYPE state;
    OMX_ERRORTYPE error;
    ilclient_debug_output("ilclient: enable tunnel from %x/%d to %x/%d",
                          tunnel->source, tunnel->source_port,
                          tunnel->sink, tunnel->sink_port);
    error = OMX_SendCommand(tunnel->source->comp, OMX_CommandPortEnable, tunnel->source_port, NULL);
    vc_assert(error == OMX_ErrorNone);
    error = OMX_SendCommand(tunnel->sink->comp, OMX_CommandPortEnable, tunnel->sink_port, NULL);
    vc_assert(error == OMX_ErrorNone);
    // to complete, the sink component can't be in loaded state
    error = OMX_GetState(tunnel->sink->comp, &state);
    vc_assert(error == OMX_ErrorNone);
    if (state == OMX_StateLoaded)
    {
       int ret = 0;
       if(ilclient_wait_for_command_complete(tunnel->sink, OMX_CommandPortEnable, tunnel->sink_port) != 0 ||
          OMX_SendCommand(tunnel->sink->comp, OMX_CommandStateSet, OMX_StateIdle, NULL) != OMX_ErrorNone ||
          (ret = ilclient_wait_for_command_complete_dual(tunnel->sink, OMX_CommandStateSet, OMX_StateIdle, tunnel->source)) < 0)
       {
          if(ret == -2)
          {
             // the error was reported fom the source component: clear this error and disable the sink component
             ilclient_wait_for_command_complete(tunnel->source, OMX_CommandPortEnable, tunnel->source_port);
             ilclient_disable_port(tunnel->sink, tunnel->sink_port);
          }
          ilclient_debug_output("ilclient: could not change component state to IDLE");
          ilclient_disable_port(tunnel->source, tunnel->source_port);
          return -1;
       }
    }
    else
    {
       if (ilclient_wait_for_command_complete(tunnel->sink, OMX_CommandPortEnable, tunnel->sink_port) != 0)
       {
          ilclient_debug_output("ilclient: could not change sink port %d to enabled", tunnel->sink_port);
          //Oops failed to enable the sink port
          ilclient_disable_port(tunnel->source, tunnel->source_port);
          //Clean up the port enable event from the source port.
          ilclient_wait_for_event(tunnel->source, OMX_EventCmdComplete,
                                  OMX_CommandPortEnable, 0, tunnel->source_port, 0,
                                  ILCLIENT_PORT_ENABLED | ILCLIENT_EVENT_ERROR, VCOS_EVENT_FLAGS_SUSPEND);
          return -1;
       }
    }
    if(ilclient_wait_for_command_complete(tunnel->source, OMX_CommandPortEnable, tunnel->source_port) != 0)
    {
       ilclient_debug_output("ilclient: could not change source port %d to enabled", tunnel->source_port);
       //Failed to enable the source port
       ilclient_disable_port(tunnel->sink, tunnel->sink_port);
       return -1;
    }
    return 0;
 }
ilclient_flush_tunnels()
VCHPRE_ void VCHPOST_ ilclient_flush_tunnels (TUNNEL_T * tunnel, int max)
The ilclient_flush_tunnels() function will flush a number of tunnels from the list of tunnels presented. For each tunnel that is to be flushed, both source and sink ports are sent a flush command. The function then waits for both ports to report they have completed the flush operation.
Parameters
tunnel List of tunnels. The list must be terminated with a tunnel structure with NULL component entries.
max The maximum number of tunnels to flush from the list. A value of 0 indicates that all tunnels in the list are flushed.
Returns
void
Definition at line 649 of file ilclient.c.
References error(), ILCLIENT_PORT_FLUSH, ilclient_wait_for_event(), NULL, OMX_CommandFlush, OMX_ErrorNone, OMX_EventCmdComplete, OMX_SendCommand, TUNNEL_T::sink_port, TUNNEL_T::source_port, vc_assert, and VCOS_EVENT_FLAGS_SUSPEND.
 {
    OMX_ERRORTYPE error;
    int i;
    i=0;
    while (tunnel[i].source && (max == 0 || i < max))
    {
       error = OMX_SendCommand(tunnel[i].source->comp, OMX_CommandFlush, tunnel[i].source_port, NULL);
       vc_assert(error == OMX_ErrorNone);
       error = OMX_SendCommand(tunnel[i].sink->comp, OMX_CommandFlush, tunnel[i].sink_port, NULL);
       vc_assert(error == OMX_ErrorNone);
       ilclient_wait_for_event(tunnel[i].source, OMX_EventCmdComplete,
                               OMX_CommandFlush, 0, tunnel[i].source_port, 0,
                               ILCLIENT_PORT_FLUSH, VCOS_EVENT_FLAGS_SUSPEND);
       ilclient_wait_for_event(tunnel[i].sink, OMX_EventCmdComplete,
                               OMX_CommandFlush, 0, tunnel[i].sink_port, 0,
                               ILCLIENT_PORT_FLUSH, VCOS_EVENT_FLAGS_SUSPEND);
       i++;
    }
 }
ilclient_get_handle()
VCHPRE_ OMX_HANDLETYPE VCHPOST_ ilclient_get_handle (COMPONENT_T * comp)
The ilclient_get_handle() function returns the underlying OMX component held by an IL component handle. This is needed when calling methods such as OMX_SetParameter on a component created using the IL client library.
Parameters
comp IL component handle
Returns
The OMX_HANDLETYPE value for the component.
Definition at line 1759 of file ilclient.c.
References _COMPONENT_T::comp, and vcos_assert.
 {
    vcos_assert(comp);
    return comp->comp;
 }
ilclient_get_input_buffer()
VCHPRE_ OMX_BUFFERHEADERTYPE* VCHPOST_ ilclient_get_input_buffer (COMPONENT_T * comp, int portIndex, int block)
The ilclient_get_input_buffer() function returns a buffer that was sent to an input port and that has been returned from a component using the OMX_EmptyBufferDone callback.
Parameters
comp The component that returned the buffer.
portIndex The port index on the component from which the buffer was returned.
block If non-zero, the function will block until a buffer is available.
Returns
pointer to buffer if available, otherwise NULL
Definition at line 1325 of file ilclient.c.
References _COMPONENT_T::event, ILCLIENT_EMPTY_BUFFER_DONE, _COMPONENT_T::in_list, OMX_BUFFERHEADERTYPE::nInputPortIndex, NULL, OMX_BUFFERHEADERTYPE::pAppPrivate, _COMPONENT_T::sema, vcos_event_flags_get(), VCOS_OR_CONSUME, vcos_semaphore_post(), and vcos_semaphore_wait().
Referenced by audioplay_get_buffer().
 {
    OMX_BUFFERHEADERTYPE *ret = NULL, *prev = NULL;
    do {
       VCOS_UNSIGNED set;
       vcos_semaphore_wait(&comp->sema);
       ret = comp->in_list;
       while(ret != NULL && ret->nInputPortIndex != portIndex)
       {
          prev = ret;
          ret = ret->pAppPrivate;
       }
       if(ret)
       {
          if(prev == NULL)
             comp->in_list = ret->pAppPrivate;
          else
             prev->pAppPrivate = ret->pAppPrivate;
          ret->pAppPrivate = NULL;
       }
       vcos_semaphore_post(&comp->sema);
       if(block && !ret)
          vcos_event_flags_get(&comp->event, ILCLIENT_EMPTY_BUFFER_DONE, VCOS_OR_CONSUME, -1, &set);
    } while(block && !ret);
    return ret;
 }
ilclient_get_output_buffer()
VCHPRE_ OMX_BUFFERHEADERTYPE* VCHPOST_ ilclient_get_output_buffer (COMPONENT_T * comp, int portIndex, int block)
The ilclient_get_output_buffer() function returns a buffer that was sent to an output port and that has been returned from a component using the OMX_FillBufferDone callback.
Parameters
comp The component that returned the buffer.
portIndex The port index on the component that the buffer was returned from.
block If non-zero, the function will block until a buffer is available.
Returns
Pointer to buffer if available, otherwise NULL.
Definition at line 1283 of file ilclient.c.
References _COMPONENT_T::event, ILCLIENT_FILL_BUFFER_DONE, OMX_BUFFERHEADERTYPE::nOutputPortIndex, NULL, _COMPONENT_T::out_list, OMX_BUFFERHEADERTYPE::pAppPrivate, _COMPONENT_T::sema, vcos_event_flags_get(), VCOS_OR_CONSUME, vcos_semaphore_post(), and vcos_semaphore_wait().
 {
    OMX_BUFFERHEADERTYPE *ret = NULL, *prev = NULL;
    VCOS_UNSIGNED set;
    do {
       vcos_semaphore_wait(&comp->sema);
       ret = comp->out_list;
       while(ret != NULL && ret->nOutputPortIndex != portIndex)
       {
          prev = ret;
          ret = ret->pAppPrivate;
       }
       if(ret)
       {
          if(prev == NULL)
             comp->out_list = ret->pAppPrivate;
          else
             prev->pAppPrivate = ret->pAppPrivate;
          ret->pAppPrivate = NULL;
       }
       vcos_semaphore_post(&comp->sema);
       if(block && !ret)
          vcos_event_flags_get(&comp->event, ILCLIENT_FILL_BUFFER_DONE, VCOS_OR_CONSUME, -1, &set);
    } while(block && !ret);
    return ret;
 }
ilclient_get_port_index()
VCHPRE_ int VCHPOST_ ilclient_get_port_index (COMPONENT_T * comp, OMX_DIRTYPE dir, OMX_PORTDOMAINTYPE type, int index)
The ilclient_get_port_index() function returns the n'th port index of the specified type and direction for the given component.
Parameters
comp The component of interest
dir The direction
type The type, or -1 for any type.
index Which port (counting from 0).
Returns
The port index, or -1 if not found.
Definition at line 1776 of file ilclient.c.
 {
    uint32_t i;
    // for each possible port type...
    for (i=0; i<sizeof(port_types)/sizeof(port_types[0]); i++)
    {
       if ((port_types[i].dom == type) || (type == (OMX_PORTDOMAINTYPE) -1))
       {
          OMX_PORT_PARAM_TYPE param;
          OMX_ERRORTYPE error;
          uint32_t j;
          param.nSize = sizeof(param);
          param.nVersion.nVersion = OMX_VERSION;
          error = OMX_GetParameter(ILC_GET_HANDLE(comp), port_types[i].param, &param);
          assert(error == OMX_ErrorNone);
          // for each port of this type...
          for (j=0; j<param.nPorts; j++)
          {
             int port = param.nStartPortNumber+j;
             OMX_PARAM_PORTDEFINITIONTYPE portdef;
             portdef.nSize = sizeof(portdef);
             portdef.nVersion.nVersion = OMX_VERSION;
             portdef.nPortIndex = port;
             error = OMX_GetParameter(ILC_GET_HANDLE(comp), OMX_IndexParamPortDefinition, &portdef);
             assert(error == OMX_ErrorNone);
             if (portdef.eDir == dir)
             {
                if (index-- == 0)
                   return port;
             }
          }
       }
    }
    return -1;
 }
ilclient_init()
VCHPRE_ ILCLIENT_T VCHPOST_* ilclient_init (void)
An IL Client structure is created by the ilclient_init() method. This structure is used when creating components, but otherwise is not needed in other API functions as a pointer to this structure is maintained in the COMPONENT_T structure.
Returns
pointer to client structure
Definition at line 158 of file ilclient.c.
References _ILCLIENT_T::event_sema, NULL, vc_assert, VCOS_LOG_CATEGORY, vcos_log_register(), vcos_log_set_level(), VCOS_LOG_WARN, vcos_malloc(), vcos_semaphore_create(), and VCOS_SUCCESS.
Referenced by audioplay_create().
 {
    ILCLIENT_T *st = vcos_malloc(sizeof(ILCLIENT_T), "ilclient");
    int i;
    if (!st)
       return NULL;
    vcos_log_set_level(VCOS_LOG_CATEGORY, VCOS_LOG_WARN);
    vcos_log_register("ilclient", VCOS_LOG_CATEGORY);
    memset(st, 0, sizeof(ILCLIENT_T));
    i = vcos_semaphore_create(&st->event_sema, "il:event", 1);
    vc_assert(i == VCOS_SUCCESS);
    ilclient_lock_events(st);
    st->event_list = NULL;
    for (i=0; i<NUM_EVENTS; i++)
    {
       st->event_rep[i].eEvent = -1; // mark as unused
       st->event_rep[i].next = st->event_list;
       st->event_list = st->event_rep+i;
    }
    ilclient_unlock_events(st);
    return st;
 }
ilclient_remove_event()
VCHPRE_ int VCHPOST_ ilclient_remove_event (COMPONENT_T * comp, OMX_EVENTTYPE event, OMX_U32 nData1, int ignore1, OMX_U32 nData2, int ignore2)
The ilclient_remove_event() function queries the event list for the given component, matching against the given criteria. If a matching event is found, it is removed and added to the free event list.
Parameters
comp The component that returned the matching event.
event The event type of the matching event.
nData1 The nData1 field of the matching event.
ignore1 Whether to ignore the nData1 field when finding a matching event. A value of 0 indicates that nData1 must match, a value of 1 indicates that nData1 does not have to match.
nData2 The nData2 field of the matching event.
ignore2 Whether to ignore the nData2 field when finding a matching event. A value of 0 indicates that nData2 must match, a value of 1 indicates that nData2 does not have to match.
Returns
0 if the event was removed. -1 if no matching event was found.
ilclient_return_events()
VCHPRE_ void VCHPOST_ ilclient_return_events (COMPONENT_T * comp)
The ilclient_return_events() function removes all events from a component event list and adds them to the IL client free event list. This function is automatically called when components are freed.
Parameters
comp The component from which all events should be moved to the free list.
Returns
void
Definition at line 682 of file ilclient.c.
Referenced by ilclient_cleanup_components().
 {
    ilclient_lock_events(comp->client);
    while (comp->list)
    {
       ILEVENT_T *next = comp->list->next;
       comp->list->next = comp->client->event_list;
       comp->client->event_list = comp->list;
       comp->list = next;
    }
    ilclient_unlock_events(comp->client);
 }
ilclient_set_configchanged_callback()
VCHPRE_ void VCHPOST_ ilclient_set_configchanged_callback (ILCLIENT_T * handle, ILCLIENT_CALLBACK_T func, void * userdata)
The ilclient_set_configchanged_callback() function registers a callback to be used when an OMX_EventParamOrConfigChanged event occurs. When the event is received, a pointer to the component structure and the index value that has changed are reported by the callback. The user may then use an OMX_GetConfig call with the index as specified to retrieve the updated information.
Parameters
handle The client handle
func The callback function to use. Calling this function with a NULL function pointer will deregister any existing registered callback.
userdata Data to be passed back when calling the callback function.
Returns
void
Definition at line 281 of file ilclient.c.
References _ILCLIENT_T::configchanged_callback, _ILCLIENT_T::configchanged_callback_data, and func.
 {
    st->configchanged_callback = func;
    st->configchanged_callback_data = userdata;
 }
ilclient_set_empty_buffer_done_callback()
VCHPRE_ void VCHPOST_ ilclient_set_empty_buffer_done_callback (ILCLIENT_T * handle, ILCLIENT_BUFFER_CALLBACK_T func, void * userdata)
The ilclient_set_empty_buffer_done_callback() function registers a callback to be used when a buffer passed to an input port using the OMX_EmptyBuffer call is returned with the OMX_EmptyBufferDone callback. When the event is received, a pointer to the component structure is returned by the callback. The user may then use the ilclient_get_input_buffer() function to retrieve the buffer.
Parameters
handle The client handle
func The callback function to use. Calling this function with a NULL function pointer will deregister any existing registered callback.
userdata Data to be passed back when calling the callback function.
Returns
void
Definition at line 267 of file ilclient.c.
References _ILCLIENT_T::empty_buffer_done_callback, _ILCLIENT_T::empty_buffer_done_callback_data, and func.
Referenced by audioplay_create().
 {
    st->empty_buffer_done_callback = func;
    st->empty_buffer_done_callback_data = userdata;
 }
ilclient_set_eos_callback()
VCHPRE_ void VCHPOST_ ilclient_set_eos_callback (ILCLIENT_T * handle, ILCLIENT_CALLBACK_T func, void * userdata)
The ilclient_set_eos_callback() function registers a callback to be used when the OMX_EventBufferFlag is received with the OMX_BUFFERFLAG_EOS flag set. When the event is received, a pointer to the component structure and port index is returned by the callback.
Parameters
handle The client handle
func The callback function to use. Calling this function with a NULL function pointer will deregister any existing registered callback.
userdata Data to be passed back when calling the callback function.
Returns
void
Definition at line 224 of file ilclient.c.
References _ILCLIENT_T::eos_callback, _ILCLIENT_T::eos_callback_data, and func.
 {
    st->eos_callback = func;
    st->eos_callback_data = userdata;
 }
ilclient_set_error_callback()
VCHPRE_ void VCHPOST_ ilclient_set_error_callback (ILCLIENT_T * handle, ILCLIENT_CALLBACK_T func, void * userdata)
The ilclient_set_error_callback() function registers a callback to be used when the OMX_EventError is received from a component. When the event is received, a pointer to the component structure and the error code are reported by the callback.
Parameters
handle The client handle
func The callback function to use. Calling this function with a NULL function pointer will deregister any existing registered callback.
userdata Data to be passed back when calling the callback function.
Returns
void
Definition at line 239 of file ilclient.c.
References _ILCLIENT_T::error_callback, _ILCLIENT_T::error_callback_data, and func.
 {
    st->error_callback = func;
    st->error_callback_data = userdata;
 }
ilclient_set_fill_buffer_done_callback()
VCHPRE_ void VCHPOST_ ilclient_set_fill_buffer_done_callback (ILCLIENT_T * handle, ILCLIENT_BUFFER_CALLBACK_T func, void * userdata)
The ilclient_set_fill_buffer_done_callback() function registers a callback to be used when a buffer passed to an output port using the OMX_FillBuffer call is returned with the OMX_FillBufferDone callback. When the event is received, a pointer to the component structure is returned by the callback. The user may then use the ilclient_get_output_buffer() function to retrieve the buffer.
Parameters
handle The client handle
func The callback function to use. Calling this function with a NULL function pointer will deregister any existing registered callback.
userdata Data to be passed back when calling the callback function.
Returns
void
Definition at line 253 of file ilclient.c.
References _ILCLIENT_T::fill_buffer_done_callback, _ILCLIENT_T::fill_buffer_done_callback_data, and func.
 {
    st->fill_buffer_done_callback = func;
    st->fill_buffer_done_callback_data = userdata;
 }
ilclient_set_port_settings_callback()
VCHPRE_ void VCHPOST_ ilclient_set_port_settings_callback (ILCLIENT_T * handle, ILCLIENT_CALLBACK_T func, void * userdata)
The ilclient_set_port_settings_callback() function registers a callback to be used when the OMX_EventPortSettingsChanged event is received. When the event is received, a pointer to the component structure and port index is returned by the callback.
Parameters
handle The client handle
func The callback function to use. Calling this function with a NULL function pointer will deregister any existing registered callback.
userdata Data to be passed back when calling the callback function.
Returns
void
Definition at line 209 of file ilclient.c.
References func, _ILCLIENT_T::port_settings_callback, and _ILCLIENT_T::port_settings_callback_data.
 {
    st->port_settings_callback = func;
    st->port_settings_callback_data = userdata;
 }
ilclient_setup_tunnel()
VCHPRE_ int VCHPOST_ ilclient_setup_tunnel (TUNNEL_T * tunnel, unsigned int portStream, int timeout)
With a populated tunnel structure, the ilclient_setup_tunnel() function connects the tunnel. It first transitions the source component to idle if currently in loaded state, and then optionally checks the source event list for a port settings changed event from the source port. If this event is not in the event queue then this function optionally waits for it to arrive. To disable this check for the port settings changed event, set timeout to zero.
Both ports are then disabled, and the source port is inspected for a port streams parameter. If this is supported, then the portStream argument is used to select which port stream to use. The two ports are then tunnelled using the OMX_SetupTunnel function. If this is successful, then both ports are enabled. Note that for disabling and enabling the tunnelled ports, the functions ilclient_disable_tunnel() and ilclient_enable_tunnel() are used, so the relevant documentation for those functions applies here.
Parameters
tunnel The tunnel structure representing the tunnel to set up.
portStream If port streams are supported on the output port of the tunnel, then this parameter indicates the port stream to select on this port.
timeout The time duration in milliseconds to wait for the output port to signal a port settings changed event before returning a timeout failure. If this is 0, then we do not check for a port settings changed before setting up the tunnel.
Returns
0 indicates success, negative indicates failure:
-1: a timeout waiting for the parameter changed
-2: an error was returned instead of parameter changed
-3: no streams are available from this port
-4: requested stream is not available from this port
-5: the data format was not acceptable to the sink
Definition at line 1013 of file ilclient.c.
References error(), and param.
 {
    OMX_ERRORTYPE error;
    OMX_PARAM_U32TYPE param;
    OMX_STATETYPE state;
    int32_t status;
    int enable_error;
    // source component must at least be idle, not loaded
    error = OMX_GetState(tunnel->source->comp, &state);
    vc_assert(error == OMX_ErrorNone);
    if (state == OMX_StateLoaded && ilclient_change_component_state(tunnel->source, OMX_StateIdle) < 0)
       return -2;
    // wait for the port parameter changed from the source port
    if(timeout)
    {
       status = ilclient_wait_for_event(tunnel->source, OMX_EventPortSettingsChanged,
                                        tunnel->source_port, 0, -1, 1,
                                        ILCLIENT_PARAMETER_CHANGED | ILCLIENT_EVENT_ERROR, timeout);
       if (status < 0)
       {
          ilclient_debug_output(
             "ilclient: timed out waiting for port settings changed on port %d", tunnel->source_port);
          return status;
       }
    }
    // disable ports
    ilclient_disable_tunnel(tunnel);
    // if this source port uses port streams, we need to select one of them before proceeding
    // if getparameter causes an error that's fine, nothing needs selecting
    param.nSize = sizeof(OMX_PARAM_U32TYPE);
    param.nVersion.nVersion = OMX_VERSION;
    param.nPortIndex = tunnel->source_port;
    if (OMX_GetParameter(tunnel->source->comp, OMX_IndexParamNumAvailableStreams, &param) == OMX_ErrorNone)
    {
       if (param.nU32 == 0)
       {
          // no streams available
          // leave the source port disabled, and return a failure
          return -3;
       }
       if (param.nU32 <= portStream)
       {
          // requested stream not available
          // no streams available
          // leave the source port disabled, and return a failure
          return -4;
       }
       param.nU32 = portStream;
       error = OMX_SetParameter(tunnel->source->comp, OMX_IndexParamActiveStream, &param);
       vc_assert(error == OMX_ErrorNone);
    }
    // now create the tunnel
    error = OMX_SetupTunnel(tunnel->source->comp, tunnel->source_port, tunnel->sink->comp, tunnel->sink_port);
    enable_error = 0;
    if (error != OMX_ErrorNone || (enable_error=ilclient_enable_tunnel(tunnel)) < 0)
    {
       // probably format not compatible
       error = OMX_SetupTunnel(tunnel->source->comp, tunnel->source_port, NULL, 0);
       vc_assert(error == OMX_ErrorNone);
       error = OMX_SetupTunnel(tunnel->sink->comp, tunnel->sink_port, NULL, 0);
       vc_assert(error == OMX_ErrorNone);
       if(enable_error)
       {
          //Clean up the errors. This does risk removing an error that was nothing to do with this tunnel :-/
          ilclient_remove_event(tunnel->sink, OMX_EventError, 0, 1, 0, 1);
          ilclient_remove_event(tunnel->source, OMX_EventError, 0, 1, 0, 1);
       }
       ilclient_debug_output("ilclient: could not setup/enable tunnel (setup=0x%x,enable=%d)",
                              error, enable_error);
       return -5;
    }
    return 0;
 }
ilclient_stack_size()
VCHPRE_ unsigned int VCHPOST_ ilclient_stack_size (void)
The ilclient_stack_size() function suggests a minimum stack size that tasks calling into with API will require.
Returns
Suggested stack size in bytes.
Definition at line 1832 of file ilclient.c.
References ILCLIENT_THREAD_DEFAULT_STACK_SIZE.
 {
    return ILCLIENT_THREAD_DEFAULT_STACK_SIZE;
 }
ilclient_state_transition()
VCHPRE_ void VCHPOST_ ilclient_state_transition (COMPONENT_T * list[], OMX_STATETYPE state)
The ilclient_state_transition() function transitions a set of components that need to perform a simultaneous state transition; for example, when two components are tunnelled and the buffer supplier port needs to allocate and pass buffers to a non-supplier port. All components are sent a command to change state, then the function will wait for all components to signal that they have changed state.
Parameters
list A null-terminated list of component pointers.
state The new state to which to transition all components.
Returns
void
Definition at line 460 of file ilclient.c.
 {
    OMX_ERRORTYPE error;
    int i, num;
    uint32_t set;
    num=0;
    while (list[num])
       num++;
    // if we transition the supplier port first, it will call freebuffer on the non
    // supplier, which will correctly signal a port unpopulated error.  We want to
    // ignore these errors.
    if (state == OMX_StateLoaded)
       for (i=0; i<num; i++)
          list[i]->error_mask |= ILCLIENT_ERROR_UNPOPULATED;
    for (i=0; i<num; i++)
       list[i]->private = ((rand() >> 13) & 0xff)+1;
    for (i=0; i<num; i++)
    {
       // transition the components in a random order
       int j, min = -1;
       for (j=0; j<num; j++)
          if (list[j]->private && (min == -1 || list[min]->private > list[j]->private))
             min = j;
       list[min]->private = 0;
       random_wait();
       //Clear error event for this component
       vcos_event_flags_get(&list[min]->event, ILCLIENT_EVENT_ERROR, VCOS_OR_CONSUME, 0, &set);
       error = OMX_SendCommand(list[min]->comp, OMX_CommandStateSet, state, NULL);
       vc_assert(error == OMX_ErrorNone);
    }
    random_wait();
    for (i=0; i<num; i++)
       if(ilclient_wait_for_command_complete(list[i], OMX_CommandStateSet, state) < 0)
          vc_assert(0);
    if (state == OMX_StateLoaded)
       for (i=0; i<num; i++)
          list[i]->error_mask &= ~ILCLIENT_ERROR_UNPOPULATED;
 }
ilclient_suggest_bufsize()
VCHPRE_ int VCHPOST_ ilclient_suggest_bufsize (COMPONENT_T * comp, OMX_U32 nBufSizeHint)
The ilclient_suggest_bufsize() function gives a component a hint about the size of buffer it should use. This size is set on the component by setting the OMX_IndexParamBrcmOutputBufferSize index on the given component.
Parameters
comp IL component handle
nBufSizeHint Size of buffer in bytes
Returns
0 indicates success, -1 indicates failure.
Definition at line 1817 of file ilclient.c.
References assert(), error(), ILC_GET_HANDLE, OMX_PARAM_BRCMOUTPUTBUFFERSIZETYPE::nBufferSize, OMX_PARAM_BRCMOUTPUTBUFFERSIZETYPE::nSize, OMX_VERSIONTYPE::nVersion, OMX_PARAM_BRCMOUTPUTBUFFERSIZETYPE::nVersion, OMX_ErrorNone, OMX_IndexParamBrcmOutputBufferSize, OMX_SetParameter, OMX_VERSION, and param.
 {
    OMX_PARAM_BRCMOUTPUTBUFFERSIZETYPE param;
    OMX_ERRORTYPE error;
    param.nSize = sizeof(param);
    param.nVersion.nVersion = OMX_VERSION;
    param.nBufferSize = nBufSizeHint;
    error = OMX_SetParameter(ILC_GET_HANDLE(comp), OMX_IndexParamBrcmOutputBufferSize,
                             &param);
    assert(error == OMX_ErrorNone);
    return (error == OMX_ErrorNone) ? 0 : -1;
 }
ilclient_teardown_tunnels()
VCHPRE_ void VCHPOST_ ilclient_teardown_tunnels (TUNNEL_T * tunnels)
The ilclient_teardown_tunnels() function tears down all tunnels in the list of tunnels presented. For each tunnel in the list, the OMX_SetupTunnel is called on the source port and on the sink port, where for both calls the destination component is NULL and the destination port is zero. The VMCSX IL implementation requires that all tunnels are torn down in this manner before components are freed.
Parameters
tunnels List of tunnels to teardown. The list must be terminated with a tunnel structure with NULL component entries.
Returns
void
Definition at line 515 of file ilclient.c.
References error(), NULL, OMX_ErrorNone, OMX_SetupTunnel(), TUNNEL_T::sink_port, TUNNEL_T::source_port, and vc_assert.
 {
    int i;
    OMX_ERRORTYPE error;
    i=0;;
    while (tunnel[i].source)
    {
       error = OMX_SetupTunnel(tunnel[i].source->comp, tunnel[i].source_port, NULL, 0);
       vc_assert(error == OMX_ErrorNone);
       error = OMX_SetupTunnel(tunnel[i].sink->comp, tunnel[i].sink_port, NULL, 0);
       vc_assert(error == OMX_ErrorNone);
       i++;
    }
 }
ilclient_wait_for_command_complete()
VCHPRE_ int VCHPOST_ ilclient_wait_for_command_complete (COMPONENT_T * comp, OMX_COMMANDTYPE command, OMX_U32 nData2)
The ilclient_wait_for_command_complete() function waits for a message from a component that indicates that the command has completed. This is either a command success message, or an error message that signals the completion of an event.
Parameters
comp The component currently processing a command.
command The command being processed. This must be either OMX_CommandStateSet, OMX_CommandPortDisable or OMX_CommandPortEnable.
nData2 The expected value of nData2 in the command complete message.
Returns
0 indicates success, either the command successfully completed or the OMX_ErrorSameState was returned. -1 indicates that the command terminated with a different error message.
Definition at line 1269 of file ilclient.c.
References ilclient_wait_for_command_complete_dual(), and NULL.
Referenced by ilclient_disable_port(), ilclient_disable_port_buffers(), ilclient_disable_tunnel(), and ilclient_enable_port().
 {
    return ilclient_wait_for_command_complete_dual(comp, command, nData2, NULL);
 }
ilclient_wait_for_command_complete_dual()
VCHPRE_ int VCHPOST_ ilclient_wait_for_command_complete_dual (COMPONENT_T * comp, OMX_COMMANDTYPE command, OMX_U32 nData2, COMPONENT_T * related)
The ilclient_wait_for_command_complete_dual() function is similar to ilclient_wait_for_command_complete(). The difference is that while waiting for the component to complete the event or raise an error, we can also report if another reports an error that terminates a command. This is useful if the two components are tunneled, and we need to wait for one component to enable a port, or change state to OMX_StateIdle. If the other component is the buffer supplier and reports an error, then it will not allocate buffers, so our first component may stall.
Parameters
comp The component currently processing a command.
command The command being processed. This must be either OMX_CommandStateSet, OMX_CommandPortDisable or OMX_CommandPortEnable.
nData2 The expected value of nData2 in the command complete message.
related Another component, where we will return if this component raises an error that terminates a command.
Returns
0 indicates success, either the command successfully completed or the OMX_ErrorSameState was returned. -1 indicates that the command terminated with a different error message. -2 indicates that the related component raised an error. In this case, the error is not cleared from the related component's event list.
Definition at line 1179 of file ilclient.c.
References _COMPONENT_T::comp, ILCLIENT_EVENT_ERROR, ILCLIENT_PORT_DISABLED, ILCLIENT_PORT_ENABLED, ILCLIENT_STATE_CHANGED, NULL, OMX_CommandPortDisable, OMX_CommandPortEnable, OMX_CommandStateSet, and _COMPONENT_T::related.
Referenced by ilclient_wait_for_command_complete().
 {
    OMX_U32 mask = ILCLIENT_EVENT_ERROR;
    int ret = 0;
    switch(command) {
    case OMX_CommandStateSet:    mask |= ILCLIENT_STATE_CHANGED; break;
    case OMX_CommandPortDisable: mask |= ILCLIENT_PORT_DISABLED; break;
    case OMX_CommandPortEnable:  mask |= ILCLIENT_PORT_ENABLED;  break;
    default: return -1;
    }
    if(other)
       other->related = comp;
    while(1)
    {
       ILEVENT_T *cur, *prev = NULL;
       VCOS_UNSIGNED set;
       ilclient_lock_events(comp->client);
       cur = comp->list;
       while(cur &&
             !(cur->eEvent == OMX_EventCmdComplete && cur->nData1 == command && cur->nData2 == nData2) &&
             !(cur->eEvent == OMX_EventError && cur->nData2 == 1))
       {
          prev = cur;
          cur = cur->next;
       }
       if(cur)
       {
          if(prev == NULL)
             comp->list = cur->next;
          else
             prev->next = cur->next;
          // work out whether this was a success or a fail event
          ret = cur->eEvent == OMX_EventCmdComplete || cur->nData1 == OMX_ErrorSameState ? 0 : -1;
          if(cur->eEvent == OMX_EventError)
             vcos_event_flags_get(&comp->event, ILCLIENT_EVENT_ERROR, VCOS_OR_CONSUME, 0, &set);
          // add back into spare list
          cur->next = comp->client->event_list;
          comp->client->event_list = cur;
          cur->eEvent = -1; // mark as unused
          ilclient_unlock_events(comp->client);
          break;
       }
       else if(other != NULL)
       {
          // check the other component for an error event that terminates a command
          cur = other->list;
          while(cur && !(cur->eEvent == OMX_EventError && cur->nData2 == 1))
             cur = cur->next;
          if(cur)
          {
             // we don't remove the event in this case, since the user
             // can confirm that this event errored by calling wait_for_command on the
             // other component
             ret = -2;
             ilclient_unlock_events(comp->client);
             break;
          }
       }
       ilclient_unlock_events(comp->client);
       vcos_event_flags_get(&comp->event, mask, VCOS_OR_CONSUME, VCOS_SUSPEND, &set);
    }
    if(other)
       other->related = NULL;
    return ret;
 }
ilclient_wait_for_event()
VCHPRE_ int VCHPOST_ ilclient_wait_for_event (COMPONENT_T * comp, OMX_EVENTTYPE event, OMX_U32 nData1, int ignore1, OMX_U32 nData2, int ignore2, int event_flag, int timeout)
The ilclient_wait_for_event() function is similar to ilclient_remove_event(), but allows the caller to block until that event arrives.
Parameters
comp The component that returned the matching event.
event The event type of the matching event.
nData1 The nData1 field of the matching event.
ignore1 Whether to ignore the nData1 field when finding a matching event. A value of 0 indicates that nData1 must match, a value of 1 indicates that nData1 does not have to match.
nData2 The nData2 field of the matching event.
ignore2 Whether to ignore the nData2 field when finding a matching event. A value of 0 indicates that nData2 must match, a value of 1 indicates that nData2 does not have to match.
event_flag Specifies a bitfield of IL client events to wait for, given in ILEVENT_MASK_T. If any of these events are signalled by the component, the event list is then re-checked for a matching event. If the ILCLIENT_EVENT_ERROR bit is included, and an error is signalled by the component, then the function will return an error code. If the ILCLIENT_CONFIG_CHANGED bit is included, and this bit is signalled by the component, then the function will return an error code.
timeout Specifies how long to block for in milliseconds before returning a failure.
Returns
0 indicates success, a matching event has been removed from the component's event queue. A negative return indicates failure, in this case no events have been removed from the component's event queue.
-1: a timeout was received.
-2: an error event was received.
-3: a config changed event was received.