VideoCore Library: containers/test/nb_io_win32.c File Reference
nb_io_win32.c File Reference
#include <conio.h>
#include "nb_io.h"
Functions
void nb_set_nonblocking_input (int enable)
int nb_char_available ()
char nb_get_char ()
void nb_put_char (char ch)
Function Documentation
nb_char_available()
int nb_char_available (void)
Returns
Non-zero when there is a character available to read using nb_get_char().
Definition at line 38 of file nb_io_win32.c.
Referenced by main().
 {
    return _kbhit();
 }
nb_get_char()
char nb_get_char (void)
Returns
The next character available from the console, or zero.
Definition at line 43 of file nb_io_win32.c.
Referenced by main().
 {
    char c = _getch();
    _putch(c);   /* Echo back */
    return c;
 }
nb_put_char()
void nb_put_char (char ch)
Put the character out to the console.
Parameters
ch The character to be output.
Definition at line 50 of file nb_io_win32.c.
 {
    _putch(ch);
 }
nb_set_nonblocking_input()
void nb_set_nonblocking_input (int enable)
Set whether console input is non-blocking or not.
Parameters
enable Pass true to set input as non-blocking, false to set it as blocking again.
Definition at line 32 of file nb_io_win32.c.
References void().
Referenced by main().
 {
    /* No need to do anything in Win32 */
    (void)enable;
 }