VideoCore Library: host_applications/vmcs/test_apps/mmalplay/playback.c File Reference
playback.c File Reference
#include <memory.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <stdarg.h>
#include "mmalplay.h"
#include "interface/mmal/mmal_logging.h"
#include "interface/mmal/util/mmal_util.h"
#include "interface/mmal/util/mmal_connection.h"
#include "interface/mmal/util/mmal_util_params.h"
#include "interface/mmal/util/mmal_default_components.h"
Classes
struct MMALPLAY_COMPONENT_T
struct MMALPLAY_T
struct MMALPLAY_CONNECTIONS_T
Macros
#define MMALPLAY_STILL_IMAGE_PAUSE 2000
#define MMALPLAY_MAX_STRING 128
#define MMALPLAY_MAX_CONNECTIONS 16
#define MMALPLAY_MAX_RENDERERS 3
#define MMALPLAY_CONNECTION_IN(cx) (cx)->connection[(cx)->num].in
#define MMALPLAY_CONNECTION_OUT(cx) (cx)->connection[(cx)->num].out
#define MMALPLAY_CONNECTION_ADD(cx) if (++(cx)->num > MMALPLAY_MAX_CONNECTIONS) goto error
#define MMALPLAY_CONNECTION_SET(cx, f) do { (cx)->connection[(cx)->num].flags |= (f); } while(0)
Typedefs
typedef struct MMALPLAY_CONNECTIONS_T MMALPLAY_CONNECTIONS_T
Functions
MMALPLAY_T * mmalplay_create (const char *uri, MMALPLAY_OPTIONS_T *opts, MMAL_STATUS_T *pstatus)
MMAL_STATUS_T mmalplay_play (MMALPLAY_T *ctx)
void mmalplay_stop (MMALPLAY_T *ctx)
void mmalplay_destroy (MMALPLAY_T *ctx)
Variables
VCOS_LOG_CAT_T mmalplay_log_category
Detailed Description
MMAL test application which plays back video files Note: this is test code. Do not use this in your app. It will change or even be removed without notice.
Definition in file playback.c.
Macro Definition Documentation
MMALPLAY_CONNECTION_ADD
#define MMALPLAY_CONNECTION_ADD (cx) if (++(cx)->num > MMALPLAY_MAX_CONNECTIONS) goto error
Definition at line 110 of file playback.c.
MMALPLAY_CONNECTION_IN
#define MMALPLAY_CONNECTION_IN (cx) (cx)->connection[(cx)->num].in
Definition at line 108 of file playback.c.
MMALPLAY_CONNECTION_OUT
#define MMALPLAY_CONNECTION_OUT (cx) (cx)->connection[(cx)->num].out
Definition at line 109 of file playback.c.
MMALPLAY_CONNECTION_SET
#define MMALPLAY_CONNECTION_SET (cx, f) do { (cx)->connection[(cx)->num].flags |= (f); } while(0)
Definition at line 111 of file playback.c.
MMALPLAY_MAX_CONNECTIONS
#define MMALPLAY_MAX_CONNECTIONS 16
Definition at line 53 of file playback.c.
MMALPLAY_MAX_RENDERERS
#define MMALPLAY_MAX_RENDERERS 3
Definition at line 54 of file playback.c.
Referenced by mmalplay_create().
MMALPLAY_MAX_STRING
#define MMALPLAY_MAX_STRING 128
Definition at line 52 of file playback.c.
MMALPLAY_STILL_IMAGE_PAUSE
#define MMALPLAY_STILL_IMAGE_PAUSE 2000
Definition at line 50 of file playback.c.
Typedef Documentation
MMALPLAY_CONNECTIONS_T
typedef struct MMALPLAY_CONNECTIONS_T MMALPLAY_CONNECTIONS_T
Function Documentation
mmalplay_create()
MMALPLAY_T* mmalplay_create (const char * uri, MMALPLAY_OPTIONS_T * opts, MMAL_STATUS_T * pstatus)
Create an instance of mmalplay. Note: this is test code. Do not use it in your app. It will change or even be removed without notice.
Definition at line 353 of file playback.c.
References MMALPLAY_T::component, MMALPLAY_T::event, LOG_TRACE, MMAL_ENOMEM, MMAL_MAX, MMAL_MIN, MMAL_SUCCESS, MMALPLAY_MAX_RENDERERS, NULL, MMALPLAY_CONNECTIONS_T::num, MMALPLAY_T::options, MMALPLAY_OPTIONS_T::output_num, MMALPLAY_T::uri, vcos_semaphore_create(), and VCOS_SUCCESS.
 {
    MMAL_STATUS_T status = MMAL_SUCCESS, status_audio, status_video, status_clock;
    MMALPLAY_T *ctx;
    MMAL_COMPONENT_T *component;
    MMALPLAY_CONNECTIONS_T connections;
    unsigned int i;
    LOG_TRACE("%s", uri);
    if (pstatus) *pstatus = MMAL_ENOMEM;
    /* Allocate and initialise context */
    ctx = malloc(sizeof(MMALPLAY_T));
    if (!ctx)
       return NULL;
    memset(ctx, 0, sizeof(*ctx));
    memset(&connections, 0, sizeof(connections));
    if (vcos_semaphore_create(&ctx->event, "MMALTest", 1) != VCOS_SUCCESS)
    {
       free(ctx);
       return NULL;
    }
    ctx->uri = uri;
    if (opts)
       ctx->options = *opts;
    ctx->options.output_num = MMAL_MAX(ctx->options.output_num, 1);
    ctx->options.output_num = MMAL_MIN(ctx->options.output_num, MMALPLAY_MAX_RENDERERS);
    connections.num = 0;
    /* Create and setup the container reader component */
    component = mmalplay_component_create(ctx, MMAL_COMPONENT_DEFAULT_CONTAINER_READER, &status);
    if (!component)
       goto error;
    status_video = mmalplay_pipeline_video_create(ctx, ctx->reader_video, &connections);
    status_audio = mmalplay_pipeline_audio_create(ctx, ctx->reader_audio, &connections);
    status_clock = mmalplay_pipeline_clock_create(ctx, &connections);
    if (status_video != MMAL_SUCCESS && status_audio != MMAL_SUCCESS && status_clock != MMAL_SUCCESS)
    {
       status = status_video;
       goto error;
    }
    /* Create our connections */
    for (i = 0; i < connections.num; i++)
    {
       status = mmalplay_connection_create(ctx, connections.connection[i].out, connections.connection[i].in,
             connections.connection[i].flags);
       if (status != MMAL_SUCCESS)
          goto error;
    }
    /* Enable our connections */
    for (i = 0; i < ctx->connection_num; i++)
    {
       status = mmal_connection_enable(ctx->connection[i]);
       if (status != MMAL_SUCCESS)
          goto error;
    }
    if (pstatus) *pstatus = MMAL_SUCCESS;
    return ctx;
  error:
    mmalplay_destroy(ctx);
    if (status == MMAL_SUCCESS) status = MMAL_ENOSPC;
    if (pstatus) *pstatus = status;
    return NULL;
 }
mmalplay_destroy()
void mmalplay_destroy (MMALPLAY_T * ctx)
Destroys an instance of mmalplay. Note: this is test code. Do not use it in your app. It will change or even be removed without notice.
Definition at line 534 of file playback.c.
References MMALPLAY_COMPONENT_T::comp, MMALPLAY_T::component, MMALPLAY_T::component_num, MMALPLAY_T::connection, MMALPLAY_T::connection_num, MMALPLAY_T::decoded_frames, MMALPLAY_T::event, LOG_INFO, LOG_TRACE, mmal_component_destroy(), mmal_connection_destroy(), mmal_connection_disable(), MMALPLAY_COMPONENT_T::name, MMAL_CONNECTION_T::name, MMALPLAY_COMPONENT_T::time_cleanup, MMAL_CONNECTION_T::time_disable, MMAL_CONNECTION_T::time_enable, MMALPLAY_T::time_playback, MMALPLAY_COMPONENT_T::time_setup, MMAL_CONNECTION_T::time_setup, MMALPLAY_T::uri, vcos_getmicrosecs(), and vcos_semaphore_delete().
 {
    unsigned int i;
    LOG_TRACE("%p, %s", ctx, ctx->uri);
    /* Disable connections */
    for (i = ctx->connection_num; i; i--)
       mmal_connection_disable(ctx->connection[i-1]);
    LOG_INFO("--- statistics ---");
    LOG_INFO("decoded %i frames in %.2fs (%.2ffps)", (int)ctx->decoded_frames,
             ctx->time_playback / 1000000.0, ctx->decoded_frames * 1000000.0 / ctx->time_playback);
    for (i = 0; i < ctx->connection_num; i++)
    {
       LOG_INFO("%s", ctx->connection[i]->name);
       LOG_INFO("- setup time: %ims",
                (int)(ctx->connection[i]->time_setup / 1000));
       LOG_INFO("- enable time: %ims, disable time: %ims",
                (int)(ctx->connection[i]->time_enable / 1000),
                (int)(ctx->connection[i]->time_disable / 1000));
    }
    /* Destroy connections */
    for (i = ctx->connection_num; i; i--)
       mmal_connection_destroy(ctx->connection[i-1]);
    /* Destroy components */
    for (i = ctx->component_num; i; i--)
    {
       ctx->component[i-1].time_cleanup = vcos_getmicrosecs();
       mmal_component_destroy(ctx->component[i-1].comp);
       ctx->component[i-1].time_cleanup = vcos_getmicrosecs() - ctx->component[i-1].time_cleanup;
    }
    vcos_semaphore_delete(&ctx->event);
    for (i = 0; i < ctx->component_num; i++)
    {
       LOG_INFO("%s:", ctx->component[i].name);
       LOG_INFO("- setup time: %ims, cleanup time: %ims",
                (int)(ctx->component[i].time_setup / 1000),
                (int)(ctx->component[i].time_cleanup / 1000));
    }
    LOG_INFO("-----------------");
    free(ctx);
 }
mmalplay_play()
MMAL_STATUS_T mmalplay_play (MMALPLAY_T * ctx)
Start playback on an instance of mmalplay. Note: this is test code. Do not use it in your app. It will change or even be removed without notice.
Definition at line 429 of file playback.c.
References MMALPLAY_T::audio_clock, MMAL_BUFFER_HEADER_T::cmd, MMALPLAY_T::connection, MMALPLAY_T::connection_num, MMALPLAY_T::event, MMAL_CONNECTION_T::flags, LOG_TRACE, MMAL_CONNECTION_FLAG_TUNNELLING, MMAL_PARAMETER_CLOCK_ACTIVE, mmal_port_parameter_set_boolean(), mmal_queue_get(), MMAL_SUCCESS, MMAL_TRUE, MMAL_CONNECTION_T::queue, MMALPLAY_T::status, MMALPLAY_T::stop, MMALPLAY_T::time_playback, MMALPLAY_T::uri, vcos_getmicrosecs(), vcos_semaphore_wait(), and MMALPLAY_T::video_clock.
 {
    MMAL_STATUS_T status = MMAL_SUCCESS;
    unsigned int i;
    LOG_TRACE("%p, %s", ctx, ctx->uri);
    ctx->time_playback = vcos_getmicrosecs();
    /* Start the clocks */
    if (ctx->video_clock)
       mmal_port_parameter_set_boolean(ctx->video_clock, MMAL_PARAMETER_CLOCK_ACTIVE, MMAL_TRUE);
    if (ctx->audio_clock)
       mmal_port_parameter_set_boolean(ctx->audio_clock, MMAL_PARAMETER_CLOCK_ACTIVE, MMAL_TRUE);
    while(1)
    {
       MMAL_BUFFER_HEADER_T *buffer;
       vcos_semaphore_wait(&ctx->event);
       if (ctx->stop || ctx->status != MMAL_SUCCESS)
       {
          status = ctx->status;
          break;
       }
       /* Loop through all the connections */
       for (i = 0; i < ctx->connection_num; i++)
       {
          MMAL_CONNECTION_T *connection = ctx->connection[i];
          if (connection->flags & MMAL_CONNECTION_FLAG_TUNNELLING)
             continue; /* Nothing else to do in tunnelling mode */
          /* Send any queued buffer to the next component */
          buffer = mmal_queue_get(connection->queue);
          while (buffer)
          {
             if (buffer->cmd)
             {
                status = mmalplay_event_handle(connection, connection->out, buffer);
                if (status != MMAL_SUCCESS)
                   goto error;
                buffer = mmal_queue_get(connection->queue);
                continue;
             }
             /* Code specific to handling of the video output port */
             if (connection->out == ctx->video_out_port)
             {
                if (buffer->length)
                   ctx->decoded_frames++;
                if (ctx->options.stepping)
                   getchar();
             }
             status = mmal_port_send_buffer(connection->in, buffer);
             if (status != MMAL_SUCCESS)
             {
                LOG_ERROR("mmal_port_send_buffer failed (%i)", status);
                mmal_queue_put_back(connection->queue, buffer);
                goto error;
             }
             buffer = mmal_queue_get(connection->queue);
          }
          /* Send empty buffers to the output port of the connection */
          buffer = connection->pool ? mmal_queue_get(connection->pool->queue) : NULL;
          while (buffer)
          {
             status = mmal_port_send_buffer(connection->out, buffer);
             if (status != MMAL_SUCCESS)
             {
                LOG_ERROR("mmal_port_send_buffer failed (%i)", status);
                mmal_queue_put_back(connection->pool->queue, buffer);
                goto error;
             }
             buffer = mmal_queue_get(connection->pool->queue);
          }
       }
    }
  error:
    ctx->time_playback = vcos_getmicrosecs() - ctx->time_playback;
    /* For still images we want to pause a bit once they are displayed */
    if (ctx->is_still_image && status == MMAL_SUCCESS)
       vcos_sleep(MMALPLAY_STILL_IMAGE_PAUSE);
    return status;
 }
mmalplay_stop()
void mmalplay_stop (MMALPLAY_T * ctx)
Stop the playback on an instance of mmalplay. Note: this is test code. Do not use it in your app. It will change or even be removed without notice.
Definition at line 525 of file playback.c.
References MMALPLAY_T::event, MMALPLAY_T::stop, and vcos_semaphore_post().
 {
    ctx->stop = 1;
    vcos_semaphore_post(&ctx->event);
 }
Variable Documentation
mmalplay_log_category
VCOS_LOG_CAT_T mmalplay_log_category
Definition at line 42 of file playback.c.