VideoCore Library: interface/vmcs_host/vc_vchi_gpuserv.h File Reference
vc_vchi_gpuserv.h File Reference
#include "interface/vchiq_arm/vchiq.h"
Classes
struct vpu_job_s
struct qpu_job_s
struct sync_job_s
struct gpu_callback_s
struct gpu_internal_s
struct gpu_job_s
Enumerations
enum { EXECUTE_NONE, EXECUTE_VPU, EXECUTE_QPU, EXECUTE_SYNC }
Functions
VCHPRE_ int32_t VCHPOST_ vc_gpuserv_init (void)
VCHPRE_ void VCHPOST_ vc_gpuserv_deinit (void)
VCHPRE_ int32_t VCHPOST_ vc_gpuserv_execute_code (int num_jobs, struct gpu_job_s jobs[])
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
EXECUTE_NONE
EXECUTE_VPU
EXECUTE_QPU
EXECUTE_SYNC
Definition at line 34 of file vc_vchi_gpuserv.h.
 { EXECUTE_NONE, EXECUTE_VPU, EXECUTE_QPU, EXECUTE_SYNC };
Function Documentation
vc_gpuserv_deinit()
VCHPRE_ void VCHPOST_ vc_gpuserv_deinit (void)
Definition at line 165 of file vc_vchi_gpuserv.c.
References GPUSERV_SERVICE_T::lock, GPUSERV_SERVICE_T::refcount, GPUSERV_SERVICE_T::service, vchi_service_close(), vcos_mutex_lock(), and vcos_mutex_unlock().
 {
    vcos_mutex_lock(&gpuserv_client.lock);
    if (gpuserv_client.refcount > 0 && --gpuserv_client.refcount == 0)
    {
       vchi_service_close(gpuserv_client.service);
       gpuserv_client.service = 0;
    }
    vcos_mutex_unlock(&gpuserv_client.lock);
 }
vc_gpuserv_execute_code()
VCHPRE_ int32_t VCHPOST_ vc_gpuserv_execute_code (int num_jobs, struct gpu_job_s jobs[])
Definition at line 228 of file vc_vchi_gpuserv.c.
References VCHIQ_ELEMENT_T::data, MAX_JOBS, GPUSERV_SERVICE_T::service, VCHIQ_ELEMENT_T::size, vc_gpuserv_init(), vchiq_queue_message(), VCHIQ_SUCCESS, and VCOS_FUNCTION.
 {
    VCHIQ_ELEMENT_T elements[MAX_JOBS];
    int i;
    // hack: temporarily allow calling this function without calling vc_gpuserv_init
    // will be removed later
    if (!gpuserv_client.service)
    {
       vc_gpuserv_init();
       vcos_log_error("%s: called without calling vc_gpuserv_init", VCOS_FUNCTION);
    }
    if (!gpuserv_client.service)
    {
       vcos_log_error("%s: vchiq service not initialised", VCOS_FUNCTION);
       return -1;
    }
    if (num_jobs > MAX_JOBS)
       return -1;
    for (i=0; i<num_jobs; i++)
    {
       elements[i].data = jobs + i;
       elements[i].size = sizeof *jobs;
    }
    if (vchiq_queue_message(gpuserv_client.service, elements, num_jobs) != VCHIQ_SUCCESS)
    {
       goto error_exit;
    }
    return 0;
    error_exit:
    return -1;
 }
vc_gpuserv_init()
VCHPRE_ int32_t VCHPOST_ vc_gpuserv_init (void)
Definition at line 94 of file vc_vchi_gpuserv.c.
References vcos_once().
Referenced by vc_gpuserv_execute_code().
 {
    VCHIQ_SERVICE_PARAMS_T vchiq_params;
    VCHIQ_STATUS_T vchiq_status;
    vcos_once(&gpuserv_client_once, init_once);
    vcos_mutex_lock(&gpuserv_client.lock);
    if (gpuserv_client.refcount++ > 0)
    {
       /* Already initialised so nothing to do */
       vcos_mutex_unlock(&gpuserv_client.lock);
       return VCOS_SUCCESS;
    }
    vcos_log_set_level(VCOS_LOG_CATEGORY, VCOS_LOG_TRACE);
    vcos_log_register("gpuserv", VCOS_LOG_CATEGORY);
    vcos_log_trace("%s: starting initialisation", VCOS_FUNCTION);
    /* Initialise a VCHIQ instance */
    vchiq_status = vchiq_initialise(&gpuserv_client_vchiq_instance);
    if (vchiq_status != VCHIQ_SUCCESS)
    {
       vcos_log_error("%s: failed to initialise vchiq: %d", VCOS_FUNCTION, vchiq_status);
       goto error;
    }
    vchiq_status = vchiq_connect(gpuserv_client_vchiq_instance);
    if (vchiq_status != VCHIQ_SUCCESS)
    {
       vcos_log_error("%s: failed to connect to vchiq: %d", VCOS_FUNCTION, vchiq_status);
       goto error;
    }
    memset(&vchiq_params, 0, sizeof(vchiq_params));
    vchiq_params.fourcc = VCHIQ_MAKE_FOURCC('G','P','U','S');
    vchiq_params.callback = gpuserv_callback;
    vchiq_params.userdata = NULL;
    vchiq_params.version = 1;
    vchiq_params.version_min = 1;
    vchiq_status = vchiq_open_service(gpuserv_client_vchiq_instance, &vchiq_params, &gpuserv_client.service);
    if (vchiq_status != VCHIQ_SUCCESS)
    {
       vcos_log_error("%s: could not open vchiq service: %d", VCOS_FUNCTION, vchiq_status);
       goto error;
    }
    vcos_mutex_unlock(&gpuserv_client.lock);
    return 0;
 error:
    vcos_mutex_unlock(&gpuserv_client.lock);
    return -1;
 }