VideoCore Library: interface/khronos/ext/gl_oes_draw_texture_client.c File Reference
gl_oes_draw_texture_client.c File Reference
#include "interface/khronos/common/khrn_client_mangle.h"
#include "interface/khronos/common/khrn_int_common.h"
#include "interface/khronos/glxx/glxx_client.h"
#include "interface/khronos/common/khrn_client_rpc.h"
#include "interface/khronos/include/GLES/gl.h"
#include "interface/khronos/include/GLES/glext.h"
Macros
#define GL_GLEXT_PROTOTYPES /* we want the prototypes so the compiler will check that the signatures match */
Functions
GL_API void GL_APIENTRY glDrawTexsOES (GLshort x, GLshort y, GLshort z, GLshort width, GLshort height)
GL_API void GL_APIENTRY glDrawTexiOES (GLint x, GLint y, GLint z, GLint width, GLint height)
GL_API void GL_APIENTRY glDrawTexxOES (GLfixed x, GLfixed y, GLfixed z, GLfixed width, GLfixed height)
GL_API void GL_APIENTRY glDrawTexsvOES (const GLshort *coords)
GL_API void GL_APIENTRY glDrawTexivOES (const GLint *coords)
GL_API void GL_APIENTRY glDrawTexxvOES (const GLfixed *coords)
GL_API void GL_APIENTRY glDrawTexfOES (GLfloat x, GLfloat y, GLfloat z, GLfloat width, GLfloat height)
GL_API void GL_APIENTRY glDrawTexfvOES (const GLfloat *coords)
Macro Definition Documentation
GL_GLEXT_PROTOTYPES
#define GL_GLEXT_PROTOTYPES /* we want the prototypes so the compiler will check that the signatures match */
Definition at line 28 of file gl_oes_draw_texture_client.c.
Function Documentation
glDrawTexfOES()
GL_API void GL_APIENTRY glDrawTexfOES (GLfloat x, GLfloat y, GLfloat z, GLfloat width, GLfloat height)
Definition at line 77 of file gl_oes_draw_texture_client.c.
Referenced by glDrawTexiOES(), glDrawTexsOES(), and glDrawTexxOES().
 {
    CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    if (IS_OPENGLES_11(thread)) {
       RPC_CALL5(glDrawTexfOES_impl_11,
                 thread,
                 GLDRAWTEXFOES_ID_11,
                 RPC_FLOAT(x),
                 RPC_FLOAT(y),
                 RPC_FLOAT(z),
                 RPC_FLOAT(width),
                 RPC_FLOAT(height));
    }
 }
glDrawTexfvOES()
GL_API void GL_APIENTRY glDrawTexfvOES (const GLfloat * coords)
Definition at line 92 of file gl_oes_draw_texture_client.c.
 {
    glDrawTexfOES((GLfloat)coords[0],(GLfloat)coords[1],(GLfloat)coords[2], (GLfloat)coords[3],(GLfloat)coords[4]);
 }
glDrawTexiOES()
GL_API void GL_APIENTRY glDrawTexiOES (GLint x, GLint y, GLint z, GLint width, GLint height)
Definition at line 52 of file gl_oes_draw_texture_client.c.
References glDrawTexfOES().
 {
    glDrawTexfOES((GLfloat)x,(GLfloat)y,(GLfloat)x, (GLfloat)width,(GLfloat)height);
 }
glDrawTexivOES()
GL_API void GL_APIENTRY glDrawTexivOES (const GLint * coords)
Definition at line 67 of file gl_oes_draw_texture_client.c.
 {
    glDrawTexfOES((GLfloat)coords[0],(GLfloat)coords[1],(GLfloat)coords[2], (GLfloat)coords[3],(GLfloat)coords[4]);
 }
glDrawTexsOES()
GL_API void GL_APIENTRY glDrawTexsOES (GLshort x, GLshort y, GLshort z, GLshort width, GLshort height)
Definition at line 47 of file gl_oes_draw_texture_client.c.
References glDrawTexfOES().
 {
    glDrawTexfOES((GLfloat)x,(GLfloat)y,(GLfloat)x, (GLfloat)width,(GLfloat)height);
 }
glDrawTexsvOES()
GL_API void GL_APIENTRY glDrawTexsvOES (const GLshort * coords)
Definition at line 62 of file gl_oes_draw_texture_client.c.
 {
    glDrawTexfOES((GLfloat)coords[0],(GLfloat)coords[1],(GLfloat)coords[2], (GLfloat)coords[3],(GLfloat)coords[4]);
 }
glDrawTexxOES()
GL_API void GL_APIENTRY glDrawTexxOES (GLfixed x, GLfixed y, GLfixed z, GLfixed width, GLfixed height)
Definition at line 57 of file gl_oes_draw_texture_client.c.
References glDrawTexfOES().
 {
    glDrawTexfOES(fixed_to_float(x), fixed_to_float(y), fixed_to_float(x), fixed_to_float(width), fixed_to_float(height));
 }
glDrawTexxvOES()
GL_API void GL_APIENTRY glDrawTexxvOES (const GLfixed * coords)
Definition at line 72 of file gl_oes_draw_texture_client.c.
 {
    glDrawTexfOES(fixed_to_float(coords[0]), fixed_to_float(coords[1]), fixed_to_float(coords[2]), fixed_to_float(coords[3]), fixed_to_float(coords[4]));
 }