VideoCore Library: interface/khronos/include/EGL/eglext_brcm.h File Reference
eglext_brcm.h File Reference
Classes
struct egl_image_brcm_vcsm_info
Macros
#define EGLEXT_BRCM_H
#define EGL_NATIVE_PIXMAP_CLIENT_SIDE_BRCM 0x99930B0 /* eglCreateImageKHR server-side target */
#define EGL_IMAGE_FROM_SURFACE_BRCM 0x99930B1 /* eglCreateImageKHR server-side target */
#define EGL_IMAGE_BRCM_MULTIMEDIA 0x99930B2
#define EGL_IMAGE_BRCM_DUPLICATE 0x99930B3 /* a new EGL Image pointing at the same underlying object */
#define EGL_IMAGE_BRCM_RAW_PIXELS 0x99930B4 /* Raw YUV multimedia pixels */
#define EGL_IMAGE_BRCM_MULTIMEDIA_Y 0x99930C0
#define EGL_IMAGE_BRCM_MULTIMEDIA_U 0x99930C1
#define EGL_IMAGE_BRCM_MULTIMEDIA_V 0x99930C2
#define EGL_IMAGE_BRCM_VCSM 0x99930C3
#define EGL_PIXEL_FORMAT_ARGB_8888_PRE_BRCM 0
#define EGL_PIXEL_FORMAT_ARGB_8888_BRCM 1
#define EGL_PIXEL_FORMAT_XRGB_8888_BRCM 2
#define EGL_PIXEL_FORMAT_RGB_565_BRCM 3
#define EGL_PIXEL_FORMAT_A_8_BRCM 4
#define EGL_PIXEL_FORMAT_RENDER_GL_BRCM (1 << 3)
#define EGL_PIXEL_FORMAT_RENDER_GLES_BRCM (1 << 4)
#define EGL_PIXEL_FORMAT_RENDER_GLES2_BRCM (1 << 5)
#define EGL_PIXEL_FORMAT_RENDER_VG_BRCM (1 << 6)
#define EGL_PIXEL_FORMAT_RENDER_MASK_BRCM 0x78
#define EGL_PIXEL_FORMAT_VG_IMAGE_BRCM (1 << 7)
#define EGL_PIXEL_FORMAT_GLES_TEXTURE_BRCM (1 << 8)
#define EGL_PIXEL_FORMAT_GLES2_TEXTURE_BRCM (1 << 9)
#define EGL_PIXEL_FORMAT_TEXTURE_MASK_BRCM 0x380
#define EGL_PIXEL_FORMAT_USAGE_MASK_BRCM 0x3f8
#define EGL_NATIVE_PIXMAP_CLIENT_SIDE_BRCM 0x99930B0 /* eglCreateImageKHR server-side target */
#define EGL_IMAGE_FROM_SURFACE_BRCM 0x99930B1 /* eglCreateImageKHR server-side target */
#define EGL_IMAGE_BRCM_MULTIMEDIA 0x99930B2
#define EGL_IMAGE_BRCM_DUPLICATE 0x99930B3 /* a new EGL Image pointing at the same underlying object */
#define EGL_IMAGE_BRCM_RAW_PIXELS 0x99930B4 /* Raw YUV multimedia pixels */
#define EGL_IMAGE_BRCM_MULTIMEDIA_Y 0x99930C0
#define EGL_IMAGE_BRCM_MULTIMEDIA_U 0x99930C1
#define EGL_IMAGE_BRCM_MULTIMEDIA_V 0x99930C2
#define EGL_IMAGE_BRCM_VCSM 0x99930C3
#define EGL_BRCM_sane_choose_config 1
#define EGL_BRCM_global_image 1
#define EGL_PIXEL_FORMAT_ARGB_8888_PRE_BRCM 0
#define EGL_PIXEL_FORMAT_ARGB_8888_BRCM 1
#define EGL_PIXEL_FORMAT_XRGB_8888_BRCM 2
#define EGL_PIXEL_FORMAT_RGB_565_BRCM 3
#define EGL_PIXEL_FORMAT_A_8_BRCM 4
#define EGL_PIXEL_FORMAT_RENDER_GL_BRCM (1 << 3)
#define EGL_PIXEL_FORMAT_RENDER_GLES_BRCM (1 << 4)
#define EGL_PIXEL_FORMAT_RENDER_GLES2_BRCM (1 << 5)
#define EGL_PIXEL_FORMAT_RENDER_VG_BRCM (1 << 6)
#define EGL_PIXEL_FORMAT_RENDER_MASK_BRCM 0x78
#define EGL_PIXEL_FORMAT_VG_IMAGE_BRCM (1 << 7)
#define EGL_PIXEL_FORMAT_GLES_TEXTURE_BRCM (1 << 8)
#define EGL_PIXEL_FORMAT_GLES2_TEXTURE_BRCM (1 << 9)
#define EGL_PIXEL_FORMAT_TEXTURE_MASK_BRCM 0x380
#define EGL_PIXEL_FORMAT_USAGE_MASK_BRCM 0x3f8
#define EGL_BRCM_perf_monitor 0
#define EGL_BRCM_driver_monitor 1
#define EGL_BRCM_perf_stats 0
#define EGL_proc_state_valid 1
#define EGL_BRCM_flush 1
#define EGL_BRCM_image_wrap 1
#define EGL_IMAGE_WRAP_BRCM 0x9993140
#define EGL_BRCM_image_wrap_bcg 0
#define EGL_IMAGE_WRAP_BRCM_BCG 0x9993141
#define EGL_BRCM_mem_usage 0
Typedefs
typedef const EGLint * attrib_list
typedef const EGLint EGLConfig * configs
typedef const EGLint EGLConfig EGLint config_size
typedef const EGLint EGLConfig EGLint EGLint * num_config
typedef EGLint height
typedef EGLint EGLint pixel_format
typedef EGLint EGLint const void * data
typedef EGLint EGLint const void EGLint data_stride
typedef EGLint EGLint const void EGLint EGLint * id
typedef EGLint * width_height_pixel_format
typedef EGLint hw_bank
typedef EGLint EGLint l3c_bank
typedef EGLint bufSize
typedef EGLint EGLint * length
typedef EGLint EGLint char * xmlStats
typedef EGLBoolean * valid
Functions
typedef EGLBoolean (EGLAPIENTRYP PFNEGLSANECHOOSECONFIGBRCM)(EGLDisplay dpy
typedef void (EGLAPIENTRYP PFNEGLCREATEGLOBALIMAGEBRCMPROC)(EGLint width
Macro Definition Documentation
EGL_BRCM_driver_monitor
#define EGL_BRCM_driver_monitor 1
Definition at line 110 of file eglext_brcm.h.
EGL_BRCM_flush
#define EGL_BRCM_flush 1
Definition at line 146 of file eglext_brcm.h.
EGL_BRCM_global_image
#define EGL_BRCM_global_image 1
Definition at line 67 of file eglext_brcm.h.
EGL_BRCM_image_wrap
#define EGL_BRCM_image_wrap 1
Definition at line 156 of file eglext_brcm.h.
EGL_BRCM_image_wrap_bcg
#define EGL_BRCM_image_wrap_bcg 0
Definition at line 161 of file eglext_brcm.h.
EGL_BRCM_mem_usage
#define EGL_BRCM_mem_usage 0
Definition at line 180 of file eglext_brcm.h.
EGL_BRCM_perf_monitor
#define EGL_BRCM_perf_monitor 0
Definition at line 98 of file eglext_brcm.h.
EGL_BRCM_perf_stats
#define EGL_BRCM_perf_stats 0
Definition at line 124 of file eglext_brcm.h.
EGL_BRCM_sane_choose_config
#define EGL_BRCM_sane_choose_config 1
Definition at line 57 of file eglext_brcm.h.
EGL_IMAGE_BRCM_DUPLICATE [1/2]
#define EGL_IMAGE_BRCM_DUPLICATE 0x99930B3 /* a new EGL Image pointing at the same underlying object */
EGL_IMAGE_BRCM_DUPLICATE [2/2]
#define EGL_IMAGE_BRCM_DUPLICATE 0x99930B3 /* a new EGL Image pointing at the same underlying object */
Definition at line 39 of file eglext_brcm.h.
EGL_IMAGE_BRCM_MULTIMEDIA [1/2]
#define EGL_IMAGE_BRCM_MULTIMEDIA 0x99930B2
Referenced by raspitexutil_update_texture().
EGL_IMAGE_BRCM_MULTIMEDIA [2/2]
#define EGL_IMAGE_BRCM_MULTIMEDIA 0x99930B2
Definition at line 38 of file eglext_brcm.h.
EGL_IMAGE_BRCM_MULTIMEDIA_U [1/2]
#define EGL_IMAGE_BRCM_MULTIMEDIA_U 0x99930C1
Referenced by raspitexutil_update_u_texture().
EGL_IMAGE_BRCM_MULTIMEDIA_U [2/2]
#define EGL_IMAGE_BRCM_MULTIMEDIA_U 0x99930C1
Definition at line 45 of file eglext_brcm.h.
EGL_IMAGE_BRCM_MULTIMEDIA_V [1/2]
#define EGL_IMAGE_BRCM_MULTIMEDIA_V 0x99930C2
Definition at line 46 of file eglext_brcm.h.
EGL_IMAGE_BRCM_MULTIMEDIA_V [2/2]
#define EGL_IMAGE_BRCM_MULTIMEDIA_V 0x99930C2
Referenced by raspitexutil_update_v_texture().
EGL_IMAGE_BRCM_MULTIMEDIA_Y [1/2]
#define EGL_IMAGE_BRCM_MULTIMEDIA_Y 0x99930C0
Referenced by raspitexutil_update_y_texture().
EGL_IMAGE_BRCM_MULTIMEDIA_Y [2/2]
#define EGL_IMAGE_BRCM_MULTIMEDIA_Y 0x99930C0
Definition at line 44 of file eglext_brcm.h.
EGL_IMAGE_BRCM_RAW_PIXELS [1/2]
#define EGL_IMAGE_BRCM_RAW_PIXELS 0x99930B4 /* Raw YUV multimedia pixels */
EGL_IMAGE_BRCM_RAW_PIXELS [2/2]
#define EGL_IMAGE_BRCM_RAW_PIXELS 0x99930B4 /* Raw YUV multimedia pixels */
Definition at line 40 of file eglext_brcm.h.
EGL_IMAGE_BRCM_VCSM [1/2]
#define EGL_IMAGE_BRCM_VCSM 0x99930C3
Definition at line 49 of file eglext_brcm.h.
EGL_IMAGE_BRCM_VCSM [2/2]
#define EGL_IMAGE_BRCM_VCSM 0x99930C3
EGL_IMAGE_FROM_SURFACE_BRCM [1/2]
#define EGL_IMAGE_FROM_SURFACE_BRCM 0x99930B1 /* eglCreateImageKHR server-side target */
EGL_IMAGE_FROM_SURFACE_BRCM [2/2]
#define EGL_IMAGE_FROM_SURFACE_BRCM 0x99930B1 /* eglCreateImageKHR server-side target */
Definition at line 36 of file eglext_brcm.h.
EGL_IMAGE_WRAP_BRCM
#define EGL_IMAGE_WRAP_BRCM 0x9993140
Definition at line 157 of file eglext_brcm.h.
EGL_IMAGE_WRAP_BRCM_BCG
#define EGL_IMAGE_WRAP_BRCM_BCG 0x9993141
Definition at line 162 of file eglext_brcm.h.
EGL_NATIVE_PIXMAP_CLIENT_SIDE_BRCM [1/2]
#define EGL_NATIVE_PIXMAP_CLIENT_SIDE_BRCM 0x99930B0 /* eglCreateImageKHR server-side target */
EGL_NATIVE_PIXMAP_CLIENT_SIDE_BRCM [2/2]
#define EGL_NATIVE_PIXMAP_CLIENT_SIDE_BRCM 0x99930B0 /* eglCreateImageKHR server-side target */
Definition at line 35 of file eglext_brcm.h.
EGL_PIXEL_FORMAT_A_8_BRCM [1/2]
#define EGL_PIXEL_FORMAT_A_8_BRCM 4
EGL_PIXEL_FORMAT_A_8_BRCM [2/2]
#define EGL_PIXEL_FORMAT_A_8_BRCM 4
Definition at line 74 of file eglext_brcm.h.
EGL_PIXEL_FORMAT_ARGB_8888_BRCM [1/2]
#define EGL_PIXEL_FORMAT_ARGB_8888_BRCM 1
Definition at line 71 of file eglext_brcm.h.
EGL_PIXEL_FORMAT_ARGB_8888_BRCM [2/2]
#define EGL_PIXEL_FORMAT_ARGB_8888_BRCM 1
EGL_PIXEL_FORMAT_ARGB_8888_PRE_BRCM [1/2]
#define EGL_PIXEL_FORMAT_ARGB_8888_PRE_BRCM 0
Definition at line 70 of file eglext_brcm.h.
EGL_PIXEL_FORMAT_ARGB_8888_PRE_BRCM [2/2]
#define EGL_PIXEL_FORMAT_ARGB_8888_PRE_BRCM 0
EGL_PIXEL_FORMAT_GLES2_TEXTURE_BRCM [1/2]
#define EGL_PIXEL_FORMAT_GLES2_TEXTURE_BRCM (1 << 9)
Referenced by platform_match_pixmap_api_support().
EGL_PIXEL_FORMAT_GLES2_TEXTURE_BRCM [2/2]
#define EGL_PIXEL_FORMAT_GLES2_TEXTURE_BRCM (1 << 9)
Definition at line 82 of file eglext_brcm.h.
EGL_PIXEL_FORMAT_GLES_TEXTURE_BRCM [1/2]
#define EGL_PIXEL_FORMAT_GLES_TEXTURE_BRCM (1 << 8)
Definition at line 81 of file eglext_brcm.h.
EGL_PIXEL_FORMAT_GLES_TEXTURE_BRCM [2/2]
#define EGL_PIXEL_FORMAT_GLES_TEXTURE_BRCM (1 << 8)
Referenced by platform_match_pixmap_api_support().
EGL_PIXEL_FORMAT_RENDER_GL_BRCM [1/2]
#define EGL_PIXEL_FORMAT_RENDER_GL_BRCM (1 << 3)
Referenced by platform_match_pixmap_api_support().
EGL_PIXEL_FORMAT_RENDER_GL_BRCM [2/2]
#define EGL_PIXEL_FORMAT_RENDER_GL_BRCM (1 << 3)
Definition at line 75 of file eglext_brcm.h.
EGL_PIXEL_FORMAT_RENDER_GLES2_BRCM [1/2]
#define EGL_PIXEL_FORMAT_RENDER_GLES2_BRCM (1 << 5)
Referenced by platform_match_pixmap_api_support().
EGL_PIXEL_FORMAT_RENDER_GLES2_BRCM [2/2]
#define EGL_PIXEL_FORMAT_RENDER_GLES2_BRCM (1 << 5)
Definition at line 77 of file eglext_brcm.h.
EGL_PIXEL_FORMAT_RENDER_GLES_BRCM [1/2]
#define EGL_PIXEL_FORMAT_RENDER_GLES_BRCM (1 << 4)
Referenced by platform_match_pixmap_api_support().
EGL_PIXEL_FORMAT_RENDER_GLES_BRCM [2/2]
#define EGL_PIXEL_FORMAT_RENDER_GLES_BRCM (1 << 4)
Definition at line 76 of file eglext_brcm.h.
EGL_PIXEL_FORMAT_RENDER_MASK_BRCM [1/2]
#define EGL_PIXEL_FORMAT_RENDER_MASK_BRCM 0x78
Definition at line 79 of file eglext_brcm.h.
EGL_PIXEL_FORMAT_RENDER_MASK_BRCM [2/2]
#define EGL_PIXEL_FORMAT_RENDER_MASK_BRCM 0x78
EGL_PIXEL_FORMAT_RENDER_VG_BRCM [1/2]
#define EGL_PIXEL_FORMAT_RENDER_VG_BRCM (1 << 6)
Definition at line 78 of file eglext_brcm.h.
EGL_PIXEL_FORMAT_RENDER_VG_BRCM [2/2]
#define EGL_PIXEL_FORMAT_RENDER_VG_BRCM (1 << 6)
Referenced by platform_match_pixmap_api_support().
EGL_PIXEL_FORMAT_RGB_565_BRCM [1/2]
#define EGL_PIXEL_FORMAT_RGB_565_BRCM 3
Definition at line 73 of file eglext_brcm.h.
EGL_PIXEL_FORMAT_RGB_565_BRCM [2/2]
#define EGL_PIXEL_FORMAT_RGB_565_BRCM 3
EGL_PIXEL_FORMAT_TEXTURE_MASK_BRCM [1/2]
#define EGL_PIXEL_FORMAT_TEXTURE_MASK_BRCM 0x380
EGL_PIXEL_FORMAT_TEXTURE_MASK_BRCM [2/2]
#define EGL_PIXEL_FORMAT_TEXTURE_MASK_BRCM 0x380
Definition at line 83 of file eglext_brcm.h.
EGL_PIXEL_FORMAT_USAGE_MASK_BRCM [1/2]
#define EGL_PIXEL_FORMAT_USAGE_MASK_BRCM 0x3f8
EGL_PIXEL_FORMAT_USAGE_MASK_BRCM [2/2]
#define EGL_PIXEL_FORMAT_USAGE_MASK_BRCM 0x3f8
Definition at line 84 of file eglext_brcm.h.
EGL_PIXEL_FORMAT_VG_IMAGE_BRCM [1/2]
#define EGL_PIXEL_FORMAT_VG_IMAGE_BRCM (1 << 7)
Referenced by platform_match_pixmap_api_support().
EGL_PIXEL_FORMAT_VG_IMAGE_BRCM [2/2]
#define EGL_PIXEL_FORMAT_VG_IMAGE_BRCM (1 << 7)
Definition at line 80 of file eglext_brcm.h.
EGL_PIXEL_FORMAT_XRGB_8888_BRCM [1/2]
#define EGL_PIXEL_FORMAT_XRGB_8888_BRCM 2
EGL_PIXEL_FORMAT_XRGB_8888_BRCM [2/2]
#define EGL_PIXEL_FORMAT_XRGB_8888_BRCM 2
Definition at line 72 of file eglext_brcm.h.
EGL_proc_state_valid
#define EGL_proc_state_valid 1
Definition at line 136 of file eglext_brcm.h.
EGLEXT_BRCM_H
#define EGLEXT_BRCM_H
Typedef Documentation
attrib_list
typedef const EGLint* attrib_list
Definition at line 63 of file eglext_brcm.h.
bufSize
typedef GLsizei bufSize
Definition at line 119 of file eglext_brcm.h.
config_size
typedef const EGLint EGLConfig EGLint config_size
Definition at line 63 of file eglext_brcm.h.
configs
typedef const EGLint EGLConfig* configs
Definition at line 63 of file eglext_brcm.h.
data
typedef GLenum GLsizei GLuint * data
Definition at line 91 of file eglext_brcm.h.
data_stride
typedef EGLint EGLint const void EGLint data_stride
Definition at line 91 of file eglext_brcm.h.
height
typedef GLuint GLuint GLuint height
Definition at line 91 of file eglext_brcm.h.
hw_bank
typedef EGLint hw_bank
Definition at line 118 of file eglext_brcm.h.
id
typedef EGLint * id
Definition at line 91 of file eglext_brcm.h.
l3c_bank
typedef EGLint EGLint l3c_bank
Definition at line 118 of file eglext_brcm.h.
length
typedef GLenum GLchar GLint * length
Definition at line 119 of file eglext_brcm.h.
num_config
typedef const EGLint EGLConfig EGLint EGLint* num_config
Definition at line 63 of file eglext_brcm.h.
pixel_format
typedef EGLint EGLint pixel_format
Definition at line 91 of file eglext_brcm.h.
valid
typedef EGLBoolean* valid
Definition at line 142 of file eglext_brcm.h.
width_height_pixel_format
typedef EGLint* width_height_pixel_format
Definition at line 94 of file eglext_brcm.h.
xmlStats
typedef EGLint EGLint char* xmlStats
Definition at line 119 of file eglext_brcm.h.
Function Documentation
EGLBoolean()
typedef EGLBoolean (EGLAPIENTRYP PFNEGLSANECHOOSECONFIGBRCM)
void()
typedef void (EGLAPIENTRYP PFNEGLCREATEGLOBALIMAGEBRCMPROC)
Referenced by gpu_fft_get_host_info(), graphics_display_resource(), mmal_component_parameter_get(), mmal_component_parameter_set(), nb_set_nonblocking_input(), AmcHandler::onMessageReceived(), raspitexutil_close(), raspitexutil_redraw(), raspitexutil_update_model(), runApp(), vc_container_net_private_maximum_datagram_size(), vc_container_net_private_set_reusable(), vc_dispmanx_resource_write_data(), vc_filesys_size(), vc_hostfs_chkdsk(), vc_hostfs_closedir(), vc_hostfs_scandisk(), vcos_set_log_options(), vcos_thread_create_classic(), and vcos_vlog_default_impl().