VideoCore Library: containers/avi/avi_writer.c File Reference
avi_writer.c File Reference
#include <limits.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "containers/core/containers_private.h"
#include "containers/core/containers_io_helpers.h"
#include "containers/core/containers_utils.h"
#include "containers/core/containers_writer_utils.h"
#include "containers/core/containers_logging.h"
Classes
struct VC_CONTAINER_TRACK_MODULE_T
struct VC_CONTAINER_MODULE_T
Macros
#define CONTAINER_IS_LITTLE_ENDIAN
#define CONTAINER_HELPER_LOG_INDENT(a) 0
#define AVISF_DISABLED 0x00000001 /*< If set stream should not be enabled by default. */
#define AVIF_HASINDEX 0x00000010
#define AVIF_TRUSTCKTYPE 0x00000800
#define AVIIF_KEYFRAME 0x00000010
#define AVI_INDEX_OF_INDEXES 0x00
#define AVI_INDEX_OF_CHUNKS 0x01
#define AVI_INDEX_DELTAFRAME 0x80000000
#define AVI_INDEX_ENTRY_SIZE 16
#define AVI_SUPER_INDEX_ENTRY_SIZE 16
#define AVI_STD_INDEX_ENTRY_SIZE 8
#define AVI_FRAME_BUFFER_SIZE 100000
#define AVI_TRACKS_MAX 3
#define AVI_AUDIO_CHUNK_SIZE_LIMIT
#define AVI_END_CHUNK(ctx)
#define AVI_PACKET_KEYFRAME (VC_CONTAINER_PACKET_FLAG_KEYFRAME | VC_CONTAINER_PACKET_FLAG_FRAME_END)
#define AVI_PACKET_IS_KEYFRAME(flags) (((flags) & AVI_PACKET_KEYFRAME) == AVI_PACKET_KEYFRAME)
Typedefs
typedef struct VC_CONTAINER_TRACK_MODULE_T VC_CONTAINER_TRACK_MODULE_T
typedef struct VC_CONTAINER_MODULE_T VC_CONTAINER_MODULE_T
Functions
VC_CONTAINER_STATUS_T avi_writer_open (VC_CONTAINER_T *p_ctx)
Macro Definition Documentation
AVI_AUDIO_CHUNK_SIZE_LIMIT
#define AVI_AUDIO_CHUNK_SIZE_LIMIT
Value:
16384 /*< Watermark limit for data chunks when 'dwSampleSize'
                                             is non-zero */
Definition at line 66 of file avi_writer.c.
AVI_END_CHUNK
#define AVI_END_CHUNK (ctx)
Value:
do {                                                               \
      if(STREAM_POSITION(ctx) & 1) WRITE_U8(ctx, 0, "AVI_END_CHUNK"); \
   } while(0)
Definition at line 69 of file avi_writer.c.
AVI_FRAME_BUFFER_SIZE
#define AVI_FRAME_BUFFER_SIZE 100000
Definition at line 62 of file avi_writer.c.
Referenced by avi_writer_open().
AVI_INDEX_DELTAFRAME
#define AVI_INDEX_DELTAFRAME 0x80000000
Definition at line 57 of file avi_writer.c.
AVI_INDEX_ENTRY_SIZE
#define AVI_INDEX_ENTRY_SIZE 16
Definition at line 59 of file avi_writer.c.
AVI_INDEX_OF_CHUNKS
#define AVI_INDEX_OF_CHUNKS 0x01
Definition at line 56 of file avi_writer.c.
AVI_INDEX_OF_INDEXES
#define AVI_INDEX_OF_INDEXES 0x00
Definition at line 55 of file avi_writer.c.
AVI_PACKET_IS_KEYFRAME
#define AVI_PACKET_IS_KEYFRAME (flags) (((flags) & AVI_PACKET_KEYFRAME) == AVI_PACKET_KEYFRAME)
Definition at line 75 of file avi_writer.c.
AVI_PACKET_KEYFRAME
#define AVI_PACKET_KEYFRAME (VC_CONTAINER_PACKET_FLAG_KEYFRAME | VC_CONTAINER_PACKET_FLAG_FRAME_END)
Definition at line 74 of file avi_writer.c.
AVI_STD_INDEX_ENTRY_SIZE
#define AVI_STD_INDEX_ENTRY_SIZE 8
Definition at line 61 of file avi_writer.c.
AVI_SUPER_INDEX_ENTRY_SIZE
#define AVI_SUPER_INDEX_ENTRY_SIZE 16
Definition at line 60 of file avi_writer.c.
AVI_TRACKS_MAX
#define AVI_TRACKS_MAX 3
Definition at line 64 of file avi_writer.c.
AVIF_HASINDEX
#define AVIF_HASINDEX 0x00000010
Definition at line 51 of file avi_writer.c.
AVIF_TRUSTCKTYPE
#define AVIF_TRUSTCKTYPE 0x00000800
Definition at line 52 of file avi_writer.c.
AVIIF_KEYFRAME
#define AVIIF_KEYFRAME 0x00000010
Definition at line 53 of file avi_writer.c.
AVISF_DISABLED
#define AVISF_DISABLED 0x00000001 /*< If set stream should not be enabled by default. */
Definition at line 50 of file avi_writer.c.
CONTAINER_HELPER_LOG_INDENT
#define CONTAINER_HELPER_LOG_INDENT (a) 0
Definition at line 35 of file avi_writer.c.
CONTAINER_IS_LITTLE_ENDIAN
#define CONTAINER_IS_LITTLE_ENDIAN
Definition at line 32 of file avi_writer.c.
Typedef Documentation
VC_CONTAINER_MODULE_T
typedef struct VC_CONTAINER_MODULE_T VC_CONTAINER_MODULE_T
VC_CONTAINER_TRACK_MODULE_T
typedef struct VC_CONTAINER_TRACK_MODULE_T VC_CONTAINER_TRACK_MODULE_T
Function Documentation
avi_writer_open()
VC_CONTAINER_STATUS_T avi_writer_open (VC_CONTAINER_T * p_ctx)
Definition at line 1100 of file avi_writer.c.
References VC_CONTAINER_MODULE_T::avi_frame_buffer, AVI_FRAME_BUFFER_SIZE, error(), extension, VC_CONTAINER_MODULE_T::frame_packet, VC_CONTAINER_PRIVATE_T::module, VC_CONTAINER_MODULE_T::null_io, VC_CONTAINER_PRIVATE_T::pf_close, VC_CONTAINER_T::priv, VC_CONTAINER_PACKET_T::size, status, STREAM_SEEKABLE, STREAM_STATUS, VC_CONTAINER_MODULE_T::temp_io, VC_CONTAINER_MODULE_T::tracks, VC_CONTAINER_T::tracks, VC_CONTAINER_PRIVATE_T::uri, VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED, VC_CONTAINER_ERROR_OUT_OF_MEMORY, VC_CONTAINER_SUCCESS, vc_container_writer_extraio_create_null(), vc_container_writer_extraio_create_temp(), VC_FOURCC, vc_uri_find_query(), vc_uri_path_extension(), WRITE_FOURCC, and WRITE_U32.
 {
    const char *extension = vc_uri_path_extension(p_ctx->priv->uri);
    VC_CONTAINER_STATUS_T status = VC_CONTAINER_SUCCESS;
    VC_CONTAINER_MODULE_T *module = 0;
    /* Check if the user has specified a container */
    vc_uri_find_query(p_ctx->priv->uri, 0, "container", &extension);
    /* Check we're the right writer for this */
    if(!extension)
       return VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED;
    if(strcasecmp(extension, "avi") && strcasecmp(extension, "divx"))
       return VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED;
    /* Allocate our context */
    module = malloc(sizeof(*module));
    if(!module) { status = VC_CONTAINER_ERROR_OUT_OF_MEMORY; goto error; }
    memset(module, 0, sizeof(*module));
    p_ctx->priv->module = module;
    /* Create a null i/o writer to help us out in writing our data */
    status = vc_container_writer_extraio_create_null(p_ctx, &module->null_io);
    if(status != VC_CONTAINER_SUCCESS) goto error;
    if(STREAM_SEEKABLE(p_ctx))
    {
        /* Create a temporary i/o writer for storage of index data while we are writing */
        status = vc_container_writer_extraio_create_temp(p_ctx, &module->temp_io);
        if(status != VC_CONTAINER_SUCCESS) goto error;
    }
    else
    {
       module->avi_frame_buffer = malloc(AVI_FRAME_BUFFER_SIZE);
       if(!module->avi_frame_buffer)
          { status = VC_CONTAINER_ERROR_OUT_OF_MEMORY; goto error; }
    }
    module->frame_packet.size = 0;
    p_ctx->tracks = module->tracks;
    /* Write the RIFF chunk descriptor */
    WRITE_FOURCC(p_ctx, VC_FOURCC('R','I','F','F'), "RIFF ID");
    WRITE_U32(p_ctx, 0, "fileSize");
    WRITE_FOURCC(p_ctx, VC_FOURCC('A','V','I',' '), "fileType");
    if((status = STREAM_STATUS(p_ctx)) != VC_CONTAINER_SUCCESS) goto error;
    p_ctx->priv->pf_close = avi_writer_close;
    p_ctx->priv->pf_write = avi_writer_write;
    p_ctx->priv->pf_control = avi_writer_control;
    return VC_CONTAINER_SUCCESS;
  error:
    LOG_DEBUG(p_ctx, "error opening stream");
    p_ctx->tracks_num = 0;
    p_ctx->tracks = NULL;
    if(module)
    {
       if(module->avi_frame_buffer) free(module->avi_frame_buffer);
       free(module);
    }
    return status;
 }