VideoCore Library: interface/vchiq_arm/vchiq_util.c File Reference
vchiq_util.c File Reference
#include "vchiq_util.h"
#include <stdlib.h>
Functions
int vchiu_queue_init (VCHIU_QUEUE_T *queue, int size)
void vchiu_queue_delete (VCHIU_QUEUE_T *queue)
int vchiu_queue_is_empty (VCHIU_QUEUE_T *queue)
int vchiu_queue_is_full (VCHIU_QUEUE_T *queue)
void vchiu_queue_push (VCHIU_QUEUE_T *queue, VCHIQ_HEADER_T *header)
VCHIQ_HEADER_T * vchiu_queue_peek (VCHIU_QUEUE_T *queue)
VCHIQ_HEADER_T * vchiu_queue_pop (VCHIU_QUEUE_T *queue)
Function Documentation
vchiu_queue_delete()
void vchiu_queue_delete (VCHIU_QUEUE_T * queue)
Definition at line 59 of file vchiq_util.c.
References NULL, VCHIU_QUEUE_T::pop, VCHIU_QUEUE_T::push, VCHIU_QUEUE_T::storage, vcos_event_delete(), and vcos_free().
 {
    vcos_event_delete(&queue->pop);
    vcos_event_delete(&queue->push);
    if (queue->storage != NULL)
       vcos_free(queue->storage);
 }
vchiu_queue_init()
int vchiu_queue_init (VCHIU_QUEUE_T * queue, int size)
Definition at line 39 of file vchiq_util.c.
References vcos_assert.
 {
    vcos_assert(is_pow2(size));
    queue->size = size;
    queue->read = 0;
    queue->write = 0;
    vcos_event_create(&queue->pop, "vchiu");
    vcos_event_create(&queue->push, "vchiu");
    queue->storage = vcos_malloc(size * sizeof(VCHIQ_HEADER_T *), VCOS_FUNCTION);
    if (queue->storage == NULL)
    {
       vchiu_queue_delete(queue);
       return 0;
    }
    return 1;
 }
vchiu_queue_is_empty()
int vchiu_queue_is_empty (VCHIU_QUEUE_T * queue)
Definition at line 67 of file vchiq_util.c.
References VCHIU_QUEUE_T::read, and VCHIU_QUEUE_T::write.
 {
    return queue->read == queue->write;
 }
vchiu_queue_is_full()
int vchiu_queue_is_full (VCHIU_QUEUE_T * queue)
Definition at line 72 of file vchiq_util.c.
References VCHIU_QUEUE_T::read, VCHIU_QUEUE_T::size, and VCHIU_QUEUE_T::write.
 {
    return queue->write == queue->read + queue->size;
 }
vchiu_queue_peek()
VCHIQ_HEADER_T* vchiu_queue_peek (VCHIU_QUEUE_T * queue)
Definition at line 89 of file vchiq_util.c.
References VCHIU_QUEUE_T::push, VCHIU_QUEUE_T::read, VCHIU_QUEUE_T::size, VCHIU_QUEUE_T::storage, vcos_event_wait(), and VCHIU_QUEUE_T::write.
 {
    while (queue->write == queue->read)
       vcos_event_wait(&queue->push);
    return queue->storage[queue->read & (queue->size - 1)];
 }
vchiu_queue_pop()
VCHIQ_HEADER_T* vchiu_queue_pop (VCHIU_QUEUE_T * queue)
Definition at line 97 of file vchiq_util.c.
References VCHIU_QUEUE_T::pop, VCHIU_QUEUE_T::push, VCHIU_QUEUE_T::read, VCHIU_QUEUE_T::size, VCHIU_QUEUE_T::storage, vcos_event_signal(), vcos_event_wait(), and VCHIU_QUEUE_T::write.
 {
    VCHIQ_HEADER_T *header;
    while (queue->write == queue->read)
       vcos_event_wait(&queue->push);
    header = queue->storage[queue->read & (queue->size - 1)];
    queue->read++;
    vcos_event_signal(&queue->pop);
    return header;
 }
vchiu_queue_push()
void vchiu_queue_push (VCHIU_QUEUE_T * queue, VCHIQ_HEADER_T * header)
Definition at line 77 of file vchiq_util.c.
References VCHIU_QUEUE_T::pop, VCHIU_QUEUE_T::push, VCHIU_QUEUE_T::read, VCHIU_QUEUE_T::size, VCHIU_QUEUE_T::storage, vcos_event_signal(), vcos_event_wait(), and VCHIU_QUEUE_T::write.
Referenced by khhn_callback(), and khrn_callback().
 {
    while (queue->write == queue->read + queue->size)
       vcos_event_wait(&queue->pop);
    queue->storage[queue->write & (queue->size - 1)] = header;
    queue->write++;
    vcos_event_signal(&queue->push);
 }