VideoCore Library: host_applications/linux/apps/hello_pi/hello_fft/gpu_fft_base.c File Reference
gpu_fft_base.c File Reference
#include <dlfcn.h>
#include "gpu_fft.h"
#include "mailbox.h"
Classes
struct GPU_FFT_HOST
Macros
#define BUS_TO_PHYS(x) ((x)&~0xC0000000)
#define V3D_L2CACTL (0xC00020>>2)
#define V3D_SLCACTL (0xC00024>>2)
#define V3D_SRQPC (0xC00430>>2)
#define V3D_SRQUA (0xC00434>>2)
#define V3D_SRQCS (0xC0043c>>2)
#define V3D_DBCFG (0xC00e00>>2)
#define V3D_DBQITE (0xC00e2c>>2)
#define V3D_DBQITC (0xC00e30>>2)
#define GPU_FFT_USE_VC4_L2_CACHE 1
#define GPU_FFT_NO_FLUSH 1
#define GPU_FFT_TIMEOUT 2000
Functions
int gpu_fft_get_host_info (struct GPU_FFT_HOST *info)
unsigned gpu_fft_base_exec_direct (struct GPU_FFT_BASE *base, int num_qpus)
unsigned gpu_fft_base_exec (struct GPU_FFT_BASE *base, int num_qpus)
int gpu_fft_alloc (int mb, unsigned size, struct GPU_FFT_PTR *ptr)
void gpu_fft_base_release (struct GPU_FFT_BASE *base)
unsigned gpu_fft_ptr_inc (struct GPU_FFT_PTR *ptr, int bytes)
Macro Definition Documentation
BUS_TO_PHYS
#define BUS_TO_PHYS (x) ((x)&~0xC0000000)
Definition at line 34 of file gpu_fft_base.c.
Referenced by gpu_fft_alloc().
GPU_FFT_NO_FLUSH
#define GPU_FFT_NO_FLUSH 1
Definition at line 50 of file gpu_fft_base.c.
Referenced by gpu_fft_base_exec().
GPU_FFT_TIMEOUT
#define GPU_FFT_TIMEOUT 2000
Definition at line 51 of file gpu_fft_base.c.
Referenced by gpu_fft_base_exec().
GPU_FFT_USE_VC4_L2_CACHE
#define GPU_FFT_USE_VC4_L2_CACHE 1
Definition at line 48 of file gpu_fft_base.c.
Referenced by gpu_fft_get_host_info().
V3D_DBCFG
#define V3D_DBCFG (0xC00e00>>2)
Definition at line 42 of file gpu_fft_base.c.
Referenced by gpu_fft_base_exec_direct().
V3D_DBQITC
#define V3D_DBQITC (0xC00e30>>2)
Definition at line 44 of file gpu_fft_base.c.
Referenced by gpu_fft_base_exec_direct().
V3D_DBQITE
#define V3D_DBQITE (0xC00e2c>>2)
Definition at line 43 of file gpu_fft_base.c.
Referenced by gpu_fft_base_exec_direct().
V3D_L2CACTL
#define V3D_L2CACTL (0xC00020>>2)
Definition at line 37 of file gpu_fft_base.c.
Referenced by gpu_fft_base_exec_direct().
V3D_SLCACTL
#define V3D_SLCACTL (0xC00024>>2)
Definition at line 38 of file gpu_fft_base.c.
Referenced by gpu_fft_base_exec_direct().
V3D_SRQCS
#define V3D_SRQCS (0xC0043c>>2)
Definition at line 41 of file gpu_fft_base.c.
Referenced by gpu_fft_base_exec_direct().
V3D_SRQPC
#define V3D_SRQPC (0xC00430>>2)
Definition at line 39 of file gpu_fft_base.c.
Referenced by gpu_fft_base_exec_direct().
V3D_SRQUA
#define V3D_SRQUA (0xC00434>>2)
Definition at line 40 of file gpu_fft_base.c.
Referenced by gpu_fft_base_exec_direct().
Function Documentation
gpu_fft_alloc()
int gpu_fft_alloc (int mb, unsigned size, struct GPU_FFT_PTR * ptr)
Definition at line 131 of file gpu_fft_base.c.
References GPU_FFT_PTR::arm, BUS_TO_PHYS, gpu_fft_get_host_info(), GPU_FFT_BASE::handle, mapmem(), GPU_FFT_BASE::mb, mem_alloc, GPU_FFT_HOST::mem_flg, mem_free(), mem_lock(), GPU_FFT_HOST::mem_map, GPU_FFT_BASE::peri, GPU_FFT_HOST::peri_addr, GPU_FFT_BASE::peri_size, GPU_FFT_HOST::peri_size, qpu_enable(), GPU_FFT_BASE::size, GPU_FFT_PTR::vc, and GPU_FFT_PTR::vptr.
Referenced by gpu_fft_prepare(), and gpu_fft_trans_prepare().
{
     struct GPU_FFT_HOST host;
     struct GPU_FFT_BASE *base;
     volatile unsigned *peri;
     unsigned handle;
     if (gpu_fft_get_host_info(&host)) return -5;
     if (qpu_enable(mb, 1)) return -1;
     // Shared memory
     handle = mem_alloc(mb, size, 4096, host.mem_flg);
     if (!handle) {
         qpu_enable(mb, 0);
         return -3;
     }
     peri = (volatile unsigned *) mapmem(host.peri_addr, host.peri_size);
     if (!peri) {
         mem_free(mb, handle);
         qpu_enable(mb, 0);
         return -4;
     }
     ptr->vc = mem_lock(mb, handle);
     ptr->arm.vptr = mapmem(BUS_TO_PHYS(ptr->vc+host.mem_map), size);
     base = (struct GPU_FFT_BASE *) ptr->arm.vptr;
     base->peri      = peri;
     base->peri_size = host.peri_size;
     base->mb        = mb;
     base->handle    = handle;
     base->size      = size;
     return 0;
 }
gpu_fft_base_exec()
unsigned gpu_fft_base_exec (struct GPU_FFT_BASE * base, int num_qpus)
Definition at line 116 of file gpu_fft_base.c.
References execute_qpu(), gpu_fft_base_exec_direct(), GPU_FFT_NO_FLUSH, GPU_FFT_TIMEOUT, GPU_FFT_BASE::mb, and GPU_FFT_BASE::vc_msg.
Referenced by gpu_fft_execute(), and gpu_fft_trans_execute().
                   {
     if (base->vc_msg) {
         // Use mailbox
         // Returns: 0x0 for success; 0x80000000 for timeout
         return execute_qpu(base->mb, num_qpus, base->vc_msg, GPU_FFT_NO_FLUSH, GPU_FFT_TIMEOUT);
     }
     else {
         // Direct register poking
         return gpu_fft_base_exec_direct(base, num_qpus);
     }
 }
gpu_fft_base_exec_direct()
unsigned gpu_fft_base_exec_direct (struct GPU_FFT_BASE * base, int num_qpus)
Definition at line 88 of file gpu_fft_base.c.
References GPU_FFT_BASE::peri, V3D_DBCFG, V3D_DBQITC, V3D_DBQITE, V3D_L2CACTL, V3D_SLCACTL, V3D_SRQCS, V3D_SRQPC, V3D_SRQUA, GPU_FFT_BASE::vc_code, and GPU_FFT_BASE::vc_unifs.
Referenced by gpu_fft_base_exec().
                   {
     unsigned q, t;
     base->peri[V3D_DBCFG] = 0; // Disallow IRQ
     base->peri[V3D_DBQITE] = 0; // Disable IRQ
     base->peri[V3D_DBQITC] = -1; // Resets IRQ flags
     base->peri[V3D_L2CACTL] =  1<<2; // Clear L2 cache
     base->peri[V3D_SLCACTL] = -1; // Clear other caches
     base->peri[V3D_SRQCS] = (1<<7) | (1<<8) | (1<<16); // Reset error bit and counts
     for (q=0; q<num_qpus; q++) { // Launch shader(s)
         base->peri[V3D_SRQUA] = base->vc_unifs[q];
         base->peri[V3D_SRQPC] = base->vc_code;
     }
     // Busy wait polling
     for (;;) {
         if (((base->peri[V3D_SRQCS]>>16) & 0xff) == num_qpus) break; // All done?
     }
     return 0;
 }
gpu_fft_base_release()
void gpu_fft_base_release (struct GPU_FFT_BASE * base)
Definition at line 172 of file gpu_fft_base.c.
References GPU_FFT_BASE::handle, GPU_FFT_BASE::mb, mem_free(), mem_unlock(), GPU_FFT_BASE::peri, GPU_FFT_BASE::peri_size, qpu_enable(), GPU_FFT_BASE::size, and unmapmem().
Referenced by gpu_fft_release(), and gpu_fft_trans_release().
{
     int mb = base->mb;
     unsigned handle = base->handle, size = base->size;
     unmapmem((void*)base->peri, base->peri_size);
     unmapmem((void*)base, size);
     mem_unlock(mb, handle);
     mem_free(mb, handle);
     qpu_enable(mb, 0);
 }
gpu_fft_get_host_info()
int gpu_fft_get_host_info (struct GPU_FFT_HOST * info)
Definition at line 57 of file gpu_fft_base.c.
References bcm_host_get_peripheral_address(), bcm_host_get_peripheral_size(), bcm_host_get_sdram_address(), dlclose(), dlopen(), dlsym, GPU_FFT_USE_VC4_L2_CACHE, GPU_FFT_HOST::mem_flg, GPU_FFT_HOST::mem_map, GPU_FFT_HOST::peri_addr, GPU_FFT_HOST::peri_size, RTLD_LAZY, and void().
Referenced by gpu_fft_alloc().
{
     void *handle;
     unsigned (*bcm_host_get_sdram_address)     (void);
     unsigned (*bcm_host_get_peripheral_address)(void);
     unsigned (*bcm_host_get_peripheral_size)   (void);
     // Pi 1 defaults
     info->peri_addr = 0x20000000;
     info->peri_size = 0x01000000;
     info->mem_flg = GPU_FFT_USE_VC4_L2_CACHE? 0xC : 0x4;
     info->mem_map = GPU_FFT_USE_VC4_L2_CACHE? 0x0 : 0x20000000; // Pi 1 only
     handle = dlopen("libbcm_host.so", RTLD_LAZY);
     if (!handle) return -1;
     *(void **) (&bcm_host_get_sdram_address)      = dlsym(handle, "bcm_host_get_sdram_address");
     *(void **) (&bcm_host_get_peripheral_address) = dlsym(handle, "bcm_host_get_peripheral_address");
     *(void **) (&bcm_host_get_peripheral_size)    = dlsym(handle, "bcm_host_get_peripheral_size");
     if (bcm_host_get_sdram_address && bcm_host_get_sdram_address()!=0x40000000) { // Pi 2?
         info->mem_flg = 0x4; // ARM cannot see VC4 L2 on Pi 2
         info->mem_map = 0x0;
     }
     if (bcm_host_get_peripheral_address) info->peri_addr = bcm_host_get_peripheral_address();
     if (bcm_host_get_peripheral_size)    info->peri_size = bcm_host_get_peripheral_size();
     dlclose(handle);
     return 0;
 }
gpu_fft_ptr_inc()
unsigned gpu_fft_ptr_inc (struct GPU_FFT_PTR * ptr, int bytes)
Definition at line 182 of file gpu_fft_base.c.
References GPU_FFT_PTR::arm, GPU_FFT_PTR::bptr, bytes, and GPU_FFT_PTR::vc.
Referenced by gpu_fft_prepare(), and gpu_fft_trans_prepare().
                {
     unsigned vc = ptr->vc;
     ptr->vc += bytes;
     ptr->arm.bptr += bytes;
     return vc;
 }