VideoCore Library: interface/vcos/vcos_blockpool.h File Reference
vcos_blockpool.h File Reference
#include "interface/vcos/vcos_types.h"
#include "vcos.h"
Functions
VCOS_INLINE_DECL VCOS_STATUS_T vcos_blockpool_init (VCOS_BLOCKPOOL_T *pool, VCOS_UNSIGNED num_blocks, VCOS_UNSIGNED block_size, void *start, VCOS_UNSIGNED pool_size, VCOS_UNSIGNED align, VCOS_UNSIGNED flags, const char *name)
VCOS_INLINE_DECL VCOS_STATUS_T vcos_blockpool_create_on_heap (VCOS_BLOCKPOOL_T *pool, VCOS_UNSIGNED num_blocks, VCOS_UNSIGNED block_size, VCOS_UNSIGNED align, VCOS_UNSIGNED flags, const char *name)
VCOS_INLINE_DECL void * vcos_blockpool_alloc (VCOS_BLOCKPOOL_T *pool)
VCOS_INLINE_DECL void * vcos_blockpool_calloc (VCOS_BLOCKPOOL_T *pool)
VCOS_INLINE_DECL void vcos_blockpool_free (void *block)
VCOS_INLINE_IMPL VCOS_UNSIGNED vcos_blockpool_available_count (VCOS_BLOCKPOOL_T *pool)
VCOS_INLINE_IMPL VCOS_UNSIGNED vcos_blockpool_used_count (VCOS_BLOCKPOOL_T *pool)
VCOS_INLINE_DECL void vcos_blockpool_delete (VCOS_BLOCKPOOL_T *pool)
VCOS_INLINE_DECL uint32_t vcos_blockpool_elem_to_handle (void *block)
VCOS_INLINE_DECL void * vcos_blockpool_elem_from_handle (VCOS_BLOCKPOOL_T *pool, uint32_t handle)
VCOS_INLINE_DECL uint32_t vcos_blockpool_is_valid_elem (VCOS_BLOCKPOOL_T *pool, const void *block)
VCOS_INLINE_DECL VCOS_STATUS_T vcos_blockpool_extend (VCOS_BLOCKPOOL_T *pool, VCOS_UNSIGNED num_extensions, VCOS_UNSIGNED num_blocks)
Detailed Description
Thread safe, fixed size allocator API.
Definition in file vcos_blockpool.h.
Function Documentation
vcos_blockpool_alloc()
VCOS_INLINE_DECL void* vcos_blockpool_alloc (VCOS_BLOCKPOOL_T * pool)
Allocate a block from the pool
Parameters
pool Pointer to the pool to allocate from.
Returns
a pointer to the newly allocated block or NULL if no blocks were available.
vcos_blockpool_available_count()
VCOS_INLINE_IMPL VCOS_UNSIGNED vcos_blockpool_available_count (VCOS_BLOCKPOOL_T * pool)
Queries the number of available blocks in the pool.
Parameters
pool The pool to query.
vcos_blockpool_calloc()
VCOS_INLINE_DECL void* vcos_blockpool_calloc (VCOS_BLOCKPOOL_T * pool)
Allocate a block from the pool and zero it.
Parameters
pool Pointer to the pool to allocate from.
Returns
a pointer to the newly allocated block or NULL if no blocks were available.
Referenced by vcos_msgq_pool_alloc(), and vcos_msgq_pool_wait().
vcos_blockpool_create_on_heap()
VCOS_INLINE_DECL VCOS_STATUS_T vcos_blockpool_create_on_heap (VCOS_BLOCKPOOL_T * pool, VCOS_UNSIGNED num_blocks, VCOS_UNSIGNED block_size, VCOS_UNSIGNED align, VCOS_UNSIGNED flags, const char * name)
Creates a pool of blocks of a given size within a buffer allocated on the heap.
The heap memory is freed when the block pool is destroyed by calling vcos_blockpool_delete.
Parameters
pool Pointer to pool object
num_blocks The number of blocks required.
block_size The size of an individual block.
align Alignment for block data. Use VCOS_BLOCKPOOL_ALIGN_DEFAULT for default word alignment.
flags Reserved for future use.
name Name of the pool. Used for diagnostics.
Returns
VCOS_SUCCESS if the pool was created.
Referenced by vcos_msgq_pool_create().
vcos_blockpool_delete()
VCOS_INLINE_DECL void vcos_blockpool_delete (VCOS_BLOCKPOOL_T * pool)
Deinitialize a memory pool.
Parameters
pool The pool to de-initialize.
Referenced by _vcos_named_semaphore_deinit(), _vcos_named_semaphore_init(), and vcos_msgq_pool_delete().
vcos_blockpool_elem_from_handle()
VCOS_INLINE_DECL void* vcos_blockpool_elem_from_handle (VCOS_BLOCKPOOL_T * pool, uint32_t handle)
Convert an integer handle back into a pointer. Returns NULL if invalid.
vcos_blockpool_elem_to_handle()
VCOS_INLINE_DECL uint32_t vcos_blockpool_elem_to_handle (void * block)
Return an integer handle for a given allocated block.
vcos_blockpool_extend()
VCOS_INLINE_DECL VCOS_STATUS_T vcos_blockpool_extend (VCOS_BLOCKPOOL_T * pool, VCOS_UNSIGNED num_extensions, VCOS_UNSIGNED num_blocks)
May be called once to allow the block pool to be extended by dynamically adding subpools. The block size cannot be altered.
Parameters
num_extensions The number of extensions that may be created. The maximum is (VCOS_BLOCKPOOL_MAX_SUBPOOLS - 1)
num_blocks The number of blocks to allocate in each in each dynamically allocated subpool.
Returns
VCOS_SUCCESS if successful.
Referenced by _vcos_named_semaphore_init().
vcos_blockpool_free()
VCOS_INLINE_DECL void vcos_blockpool_free (void * block)
Returns a block to the pool.
Parameters
block The block to free.
Referenced by vcos_msgq_pool_free().
vcos_blockpool_init()
VCOS_INLINE_DECL VCOS_STATUS_T vcos_blockpool_init (VCOS_BLOCKPOOL_T * pool, VCOS_UNSIGNED num_blocks, VCOS_UNSIGNED block_size, void * start, VCOS_UNSIGNED pool_size, VCOS_UNSIGNED align, VCOS_UNSIGNED flags, const char * name)
Initialises a block pool to use already allocated (e.g. statically) allocated memory.
Different implementations will incur different overheads. Use VCOS_BLOCKPOOL_SIZE(num_blocks, block_size) to calculate the number of bytes required including overheads for the desired pools.
Parameters
pool Pointer to pool object
num_blocks The number of blocks required.
block_size The size of an individual block.
start The address of the start of the pool.
pool_size The size of the pool in bytes.
align Alignment for block data. Use VCOS_BLOCKPOOL_ALIGN_DEFAULT for default word alignment.
flags Reserved for future use.
name Name of the pool. Used for diagnostics.
Returns
VCOS_SUCCESS if the pool was created.
Referenced by _vcos_named_semaphore_init().
vcos_blockpool_is_valid_elem()
VCOS_INLINE_DECL uint32_t vcos_blockpool_is_valid_elem (VCOS_BLOCKPOOL_T * pool, const void * block)
Checks whether a pointer is an allocated block within the specified pool. Returns true if the block is valid, otherwise, false is returned.
vcos_blockpool_used_count()
VCOS_INLINE_IMPL VCOS_UNSIGNED vcos_blockpool_used_count (VCOS_BLOCKPOOL_T * pool)
Queries the number of used blocks in the pool.
Parameters
pool The pool to query.