VideoCore Library: interface/mmal/openmaxil/mmalomx_core.c File Reference
mmalomx_core.c File Reference
#include "interface/vmcs_host/khronos/IL/OMX_Broadcom.h"
Functions
OMX_ERRORTYPE mmalomx_callback_event_handler (MMALOMX_COMPONENT_T *component, OMX_EVENTTYPE eEvent, OMX_U32 nData1, OMX_U32 nData2, OMX_PTR pEventData)
OMX_API OMX_ERRORTYPE OMX_APIENTRY MMALOMX_EXPORT() OMX_Init (void)
OMX_API OMX_ERRORTYPE OMX_APIENTRY MMALOMX_EXPORT() OMX_Deinit (void)
OMX_API OMX_ERRORTYPE OMX_APIENTRY MMALOMX_EXPORT() OMX_ComponentNameEnum (OMX_STRING cComponentName, OMX_U32 nNameLength, OMX_U32 nIndex)
OMX_API OMX_ERRORTYPE OMX_APIENTRY MMALOMX_EXPORT() OMX_GetHandle (OMX_HANDLETYPE *pHandle, OMX_STRING cComponentName, OMX_PTR pAppData, OMX_CALLBACKTYPE *pCallBacks)
OMX_API OMX_ERRORTYPE OMX_APIENTRY MMALOMX_EXPORT() OMX_FreeHandle (OMX_HANDLETYPE hComponent)
OMX_API OMX_ERRORTYPE MMALOMX_EXPORT() OMX_GetRolesOfComponent (OMX_STRING compName, OMX_U32 *pNumRoles, OMX_U8 **roles)
OMX_API OMX_ERRORTYPE MMALOMX_EXPORT() OMX_GetComponentsOfRole (OMX_STRING role, OMX_U32 *pNumComps, OMX_U8 **compNames)
OMX_API OMX_ERRORTYPE OMX_APIENTRY MMALOMX_EXPORT() OMX_SetupTunnel (OMX_HANDLETYPE hOutput, OMX_U32 nPortOutput, OMX_HANDLETYPE hInput, OMX_U32 nPortInput)
OMX_API OMX_ERRORTYPE MMALOMX_EXPORT() OMX_GetContentPipe (OMX_HANDLETYPE *hPipe, OMX_STRING szURI)
Function Documentation
mmalomx_callback_event_handler()
OMX_ERRORTYPE mmalomx_callback_event_handler (MMALOMX_COMPONENT_T * component, OMX_EVENTTYPE eEvent, OMX_U32 nData1, OMX_U32 nData2, OMX_PTR pEventData)
Definition at line 52 of file mmalomx_core.c.
References MMALOMX_COMPONENT_T::callbacks, MMALOMX_COMPONENT_T::callbacks_data, OMX_CALLBACKTYPE::EventHandler, LOG_DEBUG, and MMALOMX_COMPONENT_T::omx.
Referenced by mmalomx_command_port_disable(), mmalomx_command_port_enable(), mmalomx_mark_process_incoming(), and mmalomx_mark_process_outgoing().
 {
    LOG_DEBUG("component %p, eEvent %i, nData1 %u, nData2 %u, pEventData %p",
              component, (int)eEvent, (unsigned int)nData1, (unsigned int)nData2, pEventData);
    return component->callbacks.EventHandler((OMX_HANDLETYPE)&component->omx,
          component->callbacks_data, eEvent, nData1, nData2, pEventData);
 }
OMX_ComponentNameEnum()
OMX_API OMX_ERRORTYPE OMX_APIENTRY MMALOMX_EXPORT() OMX_ComponentNameEnum (OMX_STRING cComponentName, OMX_U32 nNameLength, OMX_U32 nIndex)
Definition at line 1127 of file mmalomx_core.c.
References LOG_TRACE, mmalomx_registry_component_name(), name, OMX_ErrorBadParameter, OMX_ErrorNoMore, and OMX_ErrorNone.
Referenced by OMX_GetComponentsOfRole().
 {
    const char *prefix, *name;
    name = mmalomx_registry_component_name(nIndex, &prefix);
    LOG_TRACE("cComponentName %p, nNameLength %i, nIndex %i",
              cComponentName, (int)nNameLength, (int)nIndex);
    /* Sanity checking */
    if (!cComponentName)
       return OMX_ErrorBadParameter;
    if (!name)
       return OMX_ErrorNoMore;
    if (nNameLength <= strlen(name) + strlen(prefix))
       return OMX_ErrorBadParameter;
    sprintf(cComponentName, "%s%s", prefix, name);
    LOG_TRACE("cComponentName: %s", cComponentName);
    return OMX_ErrorNone;
 }
OMX_FreeHandle()
OMX_API OMX_ERRORTYPE OMX_APIENTRY MMALOMX_EXPORT() OMX_FreeHandle (OMX_HANDLETYPE hComponent)
Definition at line 1350 of file mmalomx_core.c.
References MMALOMX_COMPONENT_T::cmd_pool, MMALOMX_COMPONENT_T::cmd_queue, MMALOMX_COMPONENT_T::cmd_sema, MMALOMX_COMPONENT_T::cmd_thread, MMALOMX_COMPONENT_T::cmd_thread_used, OMX_COMPONENTTYPE::ComponentDeInit, MMALOMX_COMPONENT_T::lock, MMALOMX_COMPONENT_T::lock_port, LOG_ERROR, LOG_TRACE, MMALOMX_COMPONENT_T::mmal, mmal_component_destroy(), MMAL_FALSE, mmal_pool_destroy(), mmal_queue_destroy(), NULL, MMALOMX_COMPONENT_T::omx, OMX_ErrorInvalidComponent, OMX_ErrorNone, MMALOMX_PORT_T::pool, MMALOMX_COMPONENT_T::ports, MMALOMX_COMPONENT_T::ports_num, status, vcos_mutex_delete(), vcos_semaphore_delete(), vcos_semaphore_post(), and vcos_thread_join().
Referenced by OMX_GetComponentsOfRole().
 {
    MMALOMX_COMPONENT_T *component = (MMALOMX_COMPONENT_T *)hComponent;
    OMX_ERRORTYPE status;
    unsigned int i;
    LOG_TRACE("hComponent %p", hComponent);
    /* Sanity check */
    if (!hComponent)
       return OMX_ErrorInvalidComponent;
    if (component->omx.ComponentDeInit)
    {
       status = component->omx.ComponentDeInit(hComponent);
       if (status != OMX_ErrorNone)
       {
          LOG_ERROR("ComponentDeInit failed");
          return status;
       }
    }
    if (component->cmd_thread_used)
    {
       component->cmd_thread_used = MMAL_FALSE;
       vcos_semaphore_post(&component->cmd_sema);
       vcos_thread_join(&component->cmd_thread, NULL);
    }
    mmal_component_destroy(component->mmal);
    for (i = 0; i < component->ports_num; i++)
       if (component->ports[i].pool)
          mmal_pool_destroy(component->ports[i].pool);
    if (component->cmd_pool)
       mmal_pool_destroy(component->cmd_pool);
    if (component->cmd_queue)
       mmal_queue_destroy(component->cmd_queue);
    if (component->cmd_thread_used)
       vcos_semaphore_delete(&component->cmd_sema);
    vcos_mutex_delete(&component->lock_port);
    vcos_mutex_delete(&component->lock);
    free(component);
    return OMX_ErrorNone;
 }
OMX_GetComponentsOfRole()
OMX_API OMX_ERRORTYPE MMALOMX_EXPORT() OMX_GetComponentsOfRole (OMX_STRING role, OMX_U32 * pNumComps, OMX_U8 ** compNames)
Definition at line 1444 of file mmalomx_core.c.
References OMX_COMPONENTTYPE::ComponentRoleEnum, LOG_DEBUG, LOG_TRACE, MMALOMX_IMPORT, name, OMX_ComponentNameEnum(), OMX_ErrorBadParameter, OMX_ErrorNone, OMX_FreeHandle(), OMX_GetHandle(), OMX_GetRolesOfComponent(), OMX_MAX_STRINGNAME_SIZE, role, and status.
 {
    OMX_ERRORTYPE status;
    OMX_HANDLETYPE handle;
    OMX_COMPONENTTYPE *comp;
    OMX_U8 name[OMX_MAX_STRINGNAME_SIZE], compRole[OMX_MAX_STRINGNAME_SIZE];
    OMX_U32 nNameLength = OMX_MAX_STRINGNAME_SIZE, nIndex = 0;
    OMX_U32 nRoles, nIndexRoles, nComps = 0;
    OMX_CALLBACKTYPE callbacks = {0,0,0};
    LOG_TRACE("role %s, pNumComps %p, compNames %p", role, pNumComps, compNames);
    /* Sanity checks */
    if (!role || !pNumComps)
       return OMX_ErrorBadParameter;
    /* Enumerates components */
    while ((status = OMX_ComponentNameEnum((OMX_STRING)name, nNameLength,
                                           nIndex++)) == OMX_ErrorNone)
    {
       /* Find component */
       status = MMALOMX_IMPORT(OMX_GetHandle)(&handle, (OMX_STRING)name, 0, &callbacks);
       if(status != OMX_ErrorNone) continue;
       comp = (OMX_COMPONENTTYPE *)handle;
       /* Enumerate Roles */
       status = MMALOMX_IMPORT(OMX_GetRolesOfComponent)((OMX_STRING)name, &nRoles, 0);
       if(status != OMX_ErrorNone) continue;
       for (nIndexRoles = 0; nIndexRoles < nRoles; nIndexRoles++)
       {
          status = comp->ComponentRoleEnum(handle, compRole, nIndexRoles);
          if(status != OMX_ErrorNone) break;
          if(!strncmp((char *)role, (char *)compRole, OMX_MAX_STRINGNAME_SIZE))
          {
             /* Found one */
             nComps++;
             if(!compNames) break;
             /* Check if enough space was provided for all the component names */
             if(nComps > *pNumComps) return OMX_ErrorBadParameter;
             strncpy((char *)compNames[nComps-1], (char *)name, OMX_MAX_STRINGNAME_SIZE);
             LOG_DEBUG("found component: %s", name);
          }
       }
       MMALOMX_IMPORT(OMX_FreeHandle)(handle);
    }
    LOG_DEBUG("found %i components", (int)nComps);
    *pNumComps = nComps;
    return OMX_ErrorNone;
 }
OMX_GetContentPipe()
OMX_API OMX_ERRORTYPE MMALOMX_EXPORT() OMX_GetContentPipe (OMX_HANDLETYPE * hPipe, OMX_STRING szURI)
Definition at line 1547 of file mmalomx_core.c.
References LOG_TRACE, MMAL_PARAM_UNUSED, and OMX_ErrorNotImplemented.
 {
    MMAL_PARAM_UNUSED(hPipe);
    MMAL_PARAM_UNUSED(szURI);
    LOG_TRACE("hPipe %p, szURI %s", hPipe, szURI);
    return OMX_ErrorNotImplemented;
 }
OMX_GetHandle()
OMX_API OMX_ERRORTYPE OMX_APIENTRY MMALOMX_EXPORT() OMX_GetHandle (OMX_HANDLETYPE * pHandle, OMX_STRING cComponentName, OMX_PTR pAppData, OMX_CALLBACKTYPE * pCallBacks)
Definition at line 1183 of file mmalomx_core.c.
References MMAL_COMPONENT_T::control, domain, LOG_ERROR, LOG_TRACE, mmal_component_create(), mmal_port_enable(), MMAL_SUCCESS, mmalil_error_to_omx(), mmalomx_registry_component_mmal(), mmalomx_registry_find_component(), OMX_ErrorBadParameter, OMX_ErrorComponentNotFound, OMX_ErrorInsufficientResources, and status.
Referenced by OMX_GetComponentsOfRole().
 {
    OMX_ERRORTYPE status = OMX_ErrorInsufficientResources;
    MMALOMX_COMPONENT_T *component = 0;
    MMAL_COMPONENT_T *mmal_component = 0;
    MMAL_STATUS_T mmal_status;
    unsigned int i, ports_num;
    OMX_PORTDOMAINTYPE domain;
    const char *mmal_name;
    int registry_id;
    LOG_TRACE("pHandle %p, cComponentName %s, pAppData %p, pCallBacks %p",
              pHandle, cComponentName, pAppData, pCallBacks);
    /* Sanity check params */
    if (!pHandle || !cComponentName || !pCallBacks)
       return OMX_ErrorBadParameter;
    /* Find component */
    registry_id = mmalomx_registry_find_component(cComponentName);
    if (registry_id < 0)
       return OMX_ErrorComponentNotFound;
    /* create and setup component */
    mmal_name = mmalomx_registry_component_mmal(registry_id);
    mmal_status = mmal_component_create(mmal_name, &mmal_component);
    if (mmal_status != MMAL_SUCCESS)
    {
       LOG_ERROR("could not create mmal component %s", mmal_name);
       return mmalil_error_to_omx(mmal_status);
    }
    mmal_status = mmal_port_enable(mmal_component->control, mmalomx_buffer_cb_control);
    if (mmal_status != MMAL_SUCCESS)
    {
       LOG_ERROR("could not enable %s", mmal_component->control->name);
       mmal_component_destroy(mmal_component);
       return mmalil_error_to_omx(mmal_status);
    }
    ports_num = mmal_component->port_num - 1;
    component = calloc(1, sizeof(*component) + ports_num * sizeof(*component->ports));
    if (!component)
    {
       mmal_component_destroy(mmal_component);
       return OMX_ErrorInsufficientResources;
    }
    if (vcos_mutex_create(&component->lock, "mmalomx lock") != VCOS_SUCCESS)
    {
       mmal_component_destroy(mmal_component);
       free(component);
       return OMX_ErrorInsufficientResources;
    }
    if (vcos_mutex_create(&component->lock_port, "mmalomx port lock") != VCOS_SUCCESS)
    {
       vcos_mutex_delete(&component->lock);
       mmal_component_destroy(mmal_component);
       free(component);
       return OMX_ErrorInsufficientResources;
    }
    component->omx.nSize = sizeof(component->omx);
    component->omx.nVersion.nVersion = OMX_VERSION;
    component->mmal = mmal_component;
    component->state = OMX_StateLoaded;
    component->callbacks = *pCallBacks;
    component->callbacks_data = pAppData;
    component->ports = (MMALOMX_PORT_T *)&component[1];
    component->registry_id = registry_id;
    component->name = mmalomx_registry_component_name(registry_id, 0);
    component->role = mmalomx_registry_component_roles(registry_id, 0);
    // FIXME: make this configurable
    component->cmd_thread_used = MMAL_TRUE;
    /* Sort the ports into separate OMX domains */
    for (domain = OMX_PortDomainAudio; domain < OMX_PortDomainOther; domain++)
    {
       for (i = 1; i < mmal_component->port_num; i++)
       {
          if (domain == mmalil_es_type_to_omx_domain(mmal_component->port[i]->format->type))
          {
             component->ports[component->ports_num].mmal = mmal_component->port[i];
             component->ports_domain_num[domain]++;
             component->ports_num++;
          }
       }
    }
    LOG_DEBUG("ports: %i audio, %i video",
       component->ports_domain_num[OMX_PortDomainAudio],
       component->ports_domain_num[OMX_PortDomainVideo]);
    /* Setup our ports */
    for (i = 0; i < component->ports_num; i++)
    {
       component->ports[i].component = component;
       if (component->ports[i].mmal->type == MMAL_PORT_TYPE_OUTPUT)
          component->ports[i].direction = OMX_DirOutput;
       component->ports[i].index = i;
       component->ports[i].enabled = MMAL_TRUE;
       component->ports[i].pool =
          mmal_port_pool_create(component->ports[i].mmal, 0, 0);
       if (!component->ports[i].pool)
          goto error;
       component->ports[i].mmal->userdata = (struct MMAL_PORT_USERDATA_T *)&component->ports[i];
    }
    mmal_component->control->userdata = (struct MMAL_PORT_USERDATA_T *)component;
    /* Create our OMX commands queue */
    component->cmd_queue = mmal_queue_create();
    if (!component->cmd_queue)
       goto error;
    component->cmd_pool = mmal_pool_create(MAX_CMD_BUFFERS, 0);
    if (!component->cmd_pool)
       goto error;
    if (component->cmd_thread_used &&
        vcos_semaphore_create(&component->cmd_sema,
                              "mmalomx sema", 0) != VCOS_SUCCESS)
    {
       component->cmd_thread_used = MMAL_FALSE;
       goto error;
    }
    if (component->cmd_thread_used &&
        vcos_thread_create(&component->cmd_thread, component->name, NULL,
                           mmalomx_cmd_thread_func, component) != VCOS_SUCCESS)
    {
       vcos_semaphore_delete(&component->cmd_sema);
       component->cmd_thread_used = MMAL_FALSE;
       goto error;
    }
    /* Set the function pointer for the component's interface */
    component->omx.GetComponentVersion = mmalomx_ComponentGetComponentVersion;
    component->omx.SendCommand = mmalomx_ComponentSendCommand;
    component->omx.GetParameter = mmalomx_ComponentGetParameter;
    component->omx.SetParameter = mmalomx_ComponentSetParameter;
    component->omx.GetConfig = mmalomx_ComponentGetConfig;
    component->omx.SetConfig = mmalomx_ComponentSetConfig;
    component->omx.GetExtensionIndex = mmalomx_ComponentGetExtensionIndex;
    component->omx.GetState = mmalomx_ComponentGetState;
    component->omx.ComponentTunnelRequest = mmalomx_ComponentTunnelRequest;
    component->omx.UseBuffer = mmalomx_ComponentUseBuffer;
    component->omx.AllocateBuffer = mmalomx_ComponentAllocateBuffer;
    component->omx.FreeBuffer = mmalomx_ComponentFreeBuffer;
    component->omx.EmptyThisBuffer = mmalomx_ComponentEmptyThisBuffer;
    component->omx.FillThisBuffer = mmalomx_ComponentFillThisBuffer;
    component->omx.SetCallbacks = mmalomx_ComponentSetCallbacks;
    component->omx.ComponentDeInit = mmalomx_ComponentDeInit;
    component->omx.UseEGLImage = mmalomx_ComponentUseEGLImage;
    component->omx.ComponentRoleEnum = mmalomx_ComponentRoleEnum;
    *pHandle = (OMX_HANDLETYPE)&component->omx;
    return OMX_ErrorNone;
  error:
    MMALOMX_IMPORT(OMX_FreeHandle)((OMX_HANDLETYPE)&component->omx);
    return status;
 }
OMX_GetRolesOfComponent()
OMX_API OMX_ERRORTYPE MMALOMX_EXPORT() OMX_GetRolesOfComponent (OMX_STRING compName, OMX_U32 * pNumRoles, OMX_U8 ** roles)
Definition at line 1398 of file mmalomx_core.c.
References LOG_DEBUG, LOG_TRACE, MMALOMX_MAX_ROLES, mmalomx_registry_component_roles(), mmalomx_registry_find_component(), mmalomx_role_to_name(), OMX_ErrorBadParameter, OMX_ErrorComponentNotFound, OMX_ErrorNone, OMX_MAX_STRINGNAME_SIZE, role, and roles.
Referenced by OMX_GetComponentsOfRole().
 {
    OMX_U32 i, num_roles;
    MMALOMX_ROLE_T role;
    int registry_id;
    LOG_TRACE("compName %s, pNumRoles %p, roles %p", compName, pNumRoles, roles);
    /* Sanity checks */
    if (!compName || !pNumRoles)
       return OMX_ErrorBadParameter;
    if (!roles || *pNumRoles > MMALOMX_MAX_ROLES)
       num_roles = MMALOMX_MAX_ROLES;
    else
       num_roles = *pNumRoles;
    *pNumRoles = 0;
    /* Find component */
    registry_id = mmalomx_registry_find_component(compName);
    if (registry_id < 0)
       return OMX_ErrorComponentNotFound;
    /* Enumerate Roles */
    for (i = 0; i < num_roles; i++)
    {
       role = mmalomx_registry_component_roles(registry_id, i);
       if (!role || !mmalomx_role_to_name(role))
          break;
       if(roles)
       {
          strncpy((char *)roles[i], mmalomx_role_to_name(role), OMX_MAX_STRINGNAME_SIZE);
          LOG_DEBUG("found role: %s", roles[i]);
       }
    }
    LOG_DEBUG("found %i roles", (int)i);
    *pNumRoles = i;
    return OMX_ErrorNone;
 }
OMX_SetupTunnel()
OMX_API OMX_ERRORTYPE OMX_APIENTRY MMALOMX_EXPORT() OMX_SetupTunnel (OMX_HANDLETYPE hOutput, OMX_U32 nPortOutput, OMX_HANDLETYPE hInput, OMX_U32 nPortInput)
Definition at line 1506 of file mmalomx_core.c.
References LOG_DEBUG, LOG_TRACE, NULL, OMX_BufferSupplyUnspecified, OMX_ErrorBadParameter, OMX_ErrorNone, and status.
 {
    OMX_TUNNELSETUPTYPE tunnel_setup = {0, OMX_BufferSupplyUnspecified};
    OMX_ERRORTYPE status = OMX_ErrorNone;
    LOG_TRACE("hOutput %p, nPortOutput %d, hInput %p, nPortInput %d",
              hOutput, (int)nPortOutput, hInput, (int)nPortInput);
    /* Sanity checks */
    if (!hOutput && !hInput)
       return OMX_ErrorBadParameter;
    if (hOutput)
    {
       status = ((OMX_COMPONENTTYPE *)hOutput)->ComponentTunnelRequest(
          hOutput, nPortOutput, hInput, nPortInput, &tunnel_setup);
       if (status != OMX_ErrorNone)
          LOG_DEBUG("OMX_SetupTunnel failed on output port (%i)", status);
    }
    if (status == OMX_ErrorNone && hInput)
    {
       status = ((OMX_COMPONENTTYPE *)hInput)->ComponentTunnelRequest(
          hInput, nPortInput, hOutput, nPortOutput, &tunnel_setup);
       if (status != OMX_ErrorNone)
       {
          LOG_DEBUG("OMX_SetupTunnel failed on input port (%i)", status);
          /* Cancel request on output port */
          if (hOutput)
             ((OMX_COMPONENTTYPE *)hOutput)->ComponentTunnelRequest(
                hOutput, nPortOutput, NULL, 0, NULL);
       }
    }
    return status;
 }