VideoCore Library: interface/khronos/common/linux/khrn_client_rpc_linux.c File Reference
khrn_client_rpc_linux.c File Reference
#include "vchiq.h"
#include "interface/khronos/common/khrn_int_common.h"
#include "interface/khronos/common/khrn_int_ids.h"
#include "interface/khronos/common/khrn_client.h"
#include "interface/khronos/common/khrn_client_rpc.h"
#include <string.h>
#include <stdio.h>
Macros
#define VCOS_LOG_CATEGORY (&khrn_client_log)
#define FOURCC_KHAN VCHIQ_MAKE_FOURCC('K', 'H', 'A', 'N')
#define FOURCC_KHRN VCHIQ_MAKE_FOURCC('K', 'H', 'R', 'N')
#define FOURCC_KHHN VCHIQ_MAKE_FOURCC('K', 'H', 'H', 'N')
Functions
VCHIQ_STATUS_T khrn_callback (VCHIQ_REASON_T reason, VCHIQ_HEADER_T *header, VCHIQ_SERVICE_HANDLE_T handle, void *bulk_userdata)
VCHIQ_STATUS_T khhn_callback (VCHIQ_REASON_T reason, VCHIQ_HEADER_T *header, VCHIQ_SERVICE_HANDLE_T handle, void *bulk_userdata)
VCHIQ_STATUS_T khan_callback (VCHIQ_REASON_T reason, VCHIQ_HEADER_T *header, VCHIQ_SERVICE_HANDLE_T handle, void *bulk_userdata)
void vc_vchi_khronos_init ()
bool khclient_rpc_init (void)
void rpc_term (void)
void rpc_flush (CLIENT_THREAD_STATE_T *thread)
void rpc_high_priority_begin (CLIENT_THREAD_STATE_T *thread)
void rpc_high_priority_end (CLIENT_THREAD_STATE_T *thread)
uint32_t rpc_send_ctrl_longest (CLIENT_THREAD_STATE_T *thread, uint32_t len_min)
void rpc_send_ctrl_begin (CLIENT_THREAD_STATE_T *thread, uint32_t len)
void rpc_send_ctrl_write (CLIENT_THREAD_STATE_T *thread, const uint32_t in[], uint32_t len)
void rpc_send_ctrl_end (CLIENT_THREAD_STATE_T *thread)
void rpc_send_bulk (CLIENT_THREAD_STATE_T *thread, const void *in, uint32_t len)
void rpc_send_bulk_gather (CLIENT_THREAD_STATE_T *thread, const void *in, uint32_t len, int32_t stride, uint32_t n)
uint32_t rpc_recv (CLIENT_THREAD_STATE_T *thread, void *out, uint32_t *len_io, RPC_RECV_FLAG_T flags)
void rpc_begin (CLIENT_THREAD_STATE_T *thread)
void rpc_end (CLIENT_THREAD_STATE_T *thread)
void rpc_use (CLIENT_THREAD_STATE_T *thread)
void rpc_release (CLIENT_THREAD_STATE_T *thread)
void rpc_call8_makecurrent (CLIENT_THREAD_STATE_T *thread, uint32_t id, uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4, uint32_t p5, uint32_t p6, uint32_t p7)
uint64_t rpc_get_client_id (CLIENT_THREAD_STATE_T *thread)
Variables
VCOS_LOG_CAT_T khrn_client_log
Macro Definition Documentation
FOURCC_KHAN
#define FOURCC_KHAN VCHIQ_MAKE_FOURCC('K', 'H', 'A', 'N')
Definition at line 45 of file khrn_client_rpc_linux.c.
Referenced by vc_vchi_khronos_init().
FOURCC_KHHN
#define FOURCC_KHHN VCHIQ_MAKE_FOURCC('K', 'H', 'H', 'N')
Definition at line 47 of file khrn_client_rpc_linux.c.
FOURCC_KHRN
#define FOURCC_KHRN VCHIQ_MAKE_FOURCC('K', 'H', 'R', 'N')
Definition at line 46 of file khrn_client_rpc_linux.c.
VCOS_LOG_CATEGORY
#define VCOS_LOG_CATEGORY (&khrn_client_log)
Definition at line 27 of file khrn_client_rpc_linux.c.
Function Documentation
khan_callback()
VCHIQ_STATUS_T khan_callback (VCHIQ_REASON_T reason, VCHIQ_HEADER_T * header, VCHIQ_SERVICE_HANDLE_T handle, void * bulk_userdata)
Definition at line 102 of file khrn_client_rpc_linux.c.
References ASYNC_COMMAND_DESTROY, vchiq_header_struct::data, vchiq_header_struct::size, vchiq_get_client_id(), VCHIQ_MESSAGE_AVAILABLE, VCHIQ_SUCCESS, and vcos_assert.
Referenced by vc_vchi_khronos_init().
 {
    switch (reason) {
    case VCHIQ_MESSAGE_AVAILABLE:
    {
       int32_t *data = (int32_t *) header->data;
       int32_t command = data[0];
       int32_t *msg = &data[1];
       vcos_assert(header->size == 16);
       // TODO should be able to remove this eventually.
       // If incoming message is not addressed to this process, then ignore it.
       // Correct process should then pick it up.
       uint64_t pid = vchiq_get_client_id(handle);
       if((msg[0] != (uint32_t) pid) || (msg[1] != (uint32_t) (pid >> 32)))
       {
          printf("khan_callback: message for wrong process; pid = %X, msg pid = %X\n",
             (uint32_t) pid, msg[0]);
          return VCHIQ_SUCCESS;
       } // if
       if (command == ASYNC_COMMAND_DESTROY)
       {
          /* todo: destroy */
       }
       else
       {
          PLATFORM_SEMAPHORE_T sem;
          if (khronos_platform_semaphore_create(&sem, msg, 1) == KHR_SUCCESS)
          {
             switch (command) {
             case ASYNC_COMMAND_WAIT:
                khronos_platform_semaphore_acquire(&sem);
                break;
             case ASYNC_COMMAND_POST:
                khronos_platform_semaphore_release(&sem);
                break;
             default:
                vcos_assert_msg(0, "khan_callback: unknown message type");
                break;
             }
             khronos_platform_semaphore_destroy(&sem);
          }
       } // else
       vchiq_release_message(handle, header);
       break;
    }
    case VCHIQ_BULK_TRANSMIT_DONE:
    case VCHIQ_BULK_RECEIVE_DONE:
       UNREACHABLE();
       break;
    case VCHIQ_SERVICE_OPENED:
       vcos_assert_msg(0, "khan_callback: VCHIQ_SERVICE_OPENED");
       break;
    case VCHIQ_SERVICE_CLOSED:
       vcos_assert_msg(0, "khan_callback: VCHIQ_SERVICE_CLOSED");
       break;
    case VCHIQ_BULK_TRANSMIT_ABORTED:
    case VCHIQ_BULK_RECEIVE_ABORTED:
    default:
       UNREACHABLE(); /* not implemented */
    }
    return VCHIQ_SUCCESS;
 }
khclient_rpc_init()
bool khclient_rpc_init (void)
Definition at line 231 of file khrn_client_rpc_linux.c.
 {
    workspace = NULL;
    return platform_mutex_create(&mutex) == KHR_SUCCESS;
 }
khhn_callback()
VCHIQ_STATUS_T khhn_callback (VCHIQ_REASON_T reason, VCHIQ_HEADER_T * header, VCHIQ_SERVICE_HANDLE_T handle, void * bulk_userdata)
Definition at line 81 of file khrn_client_rpc_linux.c.
References UNREACHABLE, VCHIQ_BULK_RECEIVE_ABORTED, VCHIQ_BULK_RECEIVE_DONE, VCHIQ_BULK_TRANSMIT_ABORTED, VCHIQ_BULK_TRANSMIT_DONE, VCHIQ_MESSAGE_AVAILABLE, VCHIQ_SERVICE_CLOSED, VCHIQ_SERVICE_OPENED, VCHIQ_SUCCESS, vchiu_queue_push(), and vcos_event_signal().
 {
    switch (reason) {
    case VCHIQ_MESSAGE_AVAILABLE:
       vchiu_queue_push(&khhn_queue, header);
       break;
    case VCHIQ_BULK_TRANSMIT_DONE:
    case VCHIQ_BULK_RECEIVE_DONE:
       vcos_event_signal(&bulk_event);
       break;
    case VCHIQ_SERVICE_OPENED:
    case VCHIQ_SERVICE_CLOSED:
    case VCHIQ_BULK_TRANSMIT_ABORTED:
    case VCHIQ_BULK_RECEIVE_ABORTED:
       UNREACHABLE(); /* not implemented */
    }
    return VCHIQ_SUCCESS;
 }
khrn_callback()
VCHIQ_STATUS_T khrn_callback (VCHIQ_REASON_T reason, VCHIQ_HEADER_T * header, VCHIQ_SERVICE_HANDLE_T handle, void * bulk_userdata)
Definition at line 60 of file khrn_client_rpc_linux.c.
References UNREACHABLE, VCHIQ_BULK_RECEIVE_ABORTED, VCHIQ_BULK_RECEIVE_DONE, VCHIQ_BULK_TRANSMIT_ABORTED, VCHIQ_BULK_TRANSMIT_DONE, VCHIQ_MESSAGE_AVAILABLE, VCHIQ_SERVICE_CLOSED, VCHIQ_SERVICE_OPENED, VCHIQ_SUCCESS, vchiu_queue_push(), and vcos_event_signal().
 {
    switch (reason) {
    case VCHIQ_MESSAGE_AVAILABLE:
       vchiu_queue_push(&khrn_queue, header);
       break;
    case VCHIQ_BULK_TRANSMIT_DONE:
    case VCHIQ_BULK_RECEIVE_DONE:
       vcos_event_signal(&bulk_event);
       break;
    case VCHIQ_SERVICE_OPENED:
    case VCHIQ_SERVICE_CLOSED:
    case VCHIQ_BULK_TRANSMIT_ABORTED:
    case VCHIQ_BULK_RECEIVE_ABORTED:
       UNREACHABLE(); /* not implemented */
    }
    return VCHIQ_SUCCESS;
 }
rpc_begin()
void rpc_begin (CLIENT_THREAD_STATE_T * thread)
Definition at line 481 of file khrn_client_rpc_linux.c.
References platform_mutex_acquire(), and UNUSED.
Referenced by rpc_call8_makecurrent().
 {
    UNUSED(thread);
    platform_mutex_acquire(&mutex);
 }
rpc_call8_makecurrent()
void rpc_call8_makecurrent (CLIENT_THREAD_STATE_T * thread, uint32_t id, uint32_t p0, uint32_t p1, uint32_t p2, uint32_t p3, uint32_t p4, uint32_t p5, uint32_t p6, uint32_t p7)
Definition at line 503 of file khrn_client_rpc_linux.c.
References CLIENT_MAKE_CURRENT_SIZE, EGLINTMAKECURRENT_ID, CLIENT_THREAD_STATE::merge_buffer, CLIENT_THREAD_STATE::merge_pos, rpc_begin(), RPC_CALL8, rpc_end(), and vcos_assert.
 {
    uint32_t data;
    if (thread->merge_pos == CLIENT_MAKE_CURRENT_SIZE && (memcpy(&data,thread->merge_buffer,sizeof(data)), data == EGLINTMAKECURRENT_ID))
    {
       rpc_begin(thread);
       vcos_log_trace("rpc_call8_makecurrent collapse onto previous makecurrent");
       thread->merge_pos = 0;
       RPC_CALL8(eglIntMakeCurrent_impl, thread, EGLINTMAKECURRENT_ID, p0, p1, p2, p3, p4, p5, p6, p7);
       vcos_assert(thread->merge_pos == CLIENT_MAKE_CURRENT_SIZE);
       rpc_end(thread);
    }
    else
    {
       RPC_CALL8(eglIntMakeCurrent_impl, thread, EGLINTMAKECURRENT_ID, p0, p1, p2, p3, p4, p5, p6, p7);
    }
 }
rpc_end()
void rpc_end (CLIENT_THREAD_STATE_T * thread)
Definition at line 487 of file khrn_client_rpc_linux.c.
References platform_mutex_release(), and UNUSED.
Referenced by rpc_call8_makecurrent().
 {
    UNUSED(thread);
    platform_mutex_release(&mutex);
 }
rpc_flush()
void rpc_flush (CLIENT_THREAD_STATE_T * thread)
Definition at line 300 of file khrn_client_rpc_linux.c.
 {
    merge_flush(thread);
 }
rpc_get_client_id()
uint64_t rpc_get_client_id (CLIENT_THREAD_STATE_T * thread)
Definition at line 525 of file khrn_client_rpc_linux.c.
References vchiq_get_client_id().
Referenced by client_send_make_current().
 {
    return vchiq_get_client_id(get_handle(thread));
 }
rpc_high_priority_begin()
void rpc_high_priority_begin (CLIENT_THREAD_STATE_T * thread)
Definition at line 305 of file khrn_client_rpc_linux.c.
References CLIENT_THREAD_STATE::high_priority, and vcos_assert.
 {
    vcos_assert(!thread->high_priority);
    merge_flush(thread);
    thread->high_priority = true;
 }
rpc_high_priority_end()
void rpc_high_priority_end (CLIENT_THREAD_STATE_T * thread)
Definition at line 312 of file khrn_client_rpc_linux.c.
References CLIENT_THREAD_STATE::high_priority, and vcos_assert.
 {
    vcos_assert(thread->high_priority);
    merge_flush(thread);
    thread->high_priority = false;
 }
rpc_recv()
uint32_t rpc_recv (CLIENT_THREAD_STATE_T * thread, void * out, uint32_t * len_io, RPC_RECV_FLAG_T flags)
Definition at line 427 of file khrn_client_rpc_linux.c.
References len, RPC_RECV_FLAG_BULK, RPC_RECV_FLAG_CTRL, RPC_RECV_FLAG_LEN, RPC_RECV_FLAG_RES, and vcos_assert.
 {
    uint32_t res = 0;
    uint32_t len;
    bool recv_ctrl;
    if (!len_io) { len_io = &len; }
    recv_ctrl = flags & (RPC_RECV_FLAG_RES | RPC_RECV_FLAG_CTRL | RPC_RECV_FLAG_LEN); /* do we want to receive anything in the control channel at all? */
    vcos_assert(recv_ctrl || (flags & RPC_RECV_FLAG_BULK)); /* must receive something... */
    vcos_assert(!(flags & RPC_RECV_FLAG_CTRL) || !(flags & RPC_RECV_FLAG_BULK)); /* can't receive user data over both bulk and control... */
    if (recv_ctrl || len_io[0]) { /* do nothing if we're just receiving bulk of length 0 */
       merge_flush(thread);
       if (recv_ctrl) {
          VCHIQ_HEADER_T *header = vchiu_queue_pop(get_queue(thread));
          uint8_t *ctrl = (uint8_t *)header->data;
          vcos_assert(header->size >= (!!(flags & RPC_RECV_FLAG_LEN)*4 + !!(flags & RPC_RECV_FLAG_RES)*4) );
          if (flags & RPC_RECV_FLAG_LEN) {
             len_io[0] = *((uint32_t *)ctrl);
             ctrl += 4;
          }
          if (flags & RPC_RECV_FLAG_RES) {
             res = *((uint32_t *)ctrl);
             ctrl += 4;
          }
          if (flags & RPC_RECV_FLAG_CTRL) {
             memcpy(out, ctrl, len_io[0]);
             ctrl += len_io[0];
          }
          vcos_assert(ctrl == ((uint8_t *)header->data + header->size));
          vchiq_release_message(get_handle(thread), header);
       }
       if ((flags & RPC_RECV_FLAG_BULK) && len_io[0]) {
          if (flags & RPC_RECV_FLAG_BULK_SCATTER) {
             if ((len_io[0] == len_io[1]) && !len_io[3] && !len_io[4]) {
                /* hopefully should be the common case */
                recv_bulk(thread, out, len_io[2] * len_io[0]);
             } else {
                check_workspace(len_io[2] * len_io[0]);
                recv_bulk(thread, workspace, len_io[2] * len_io[0]);
                rpc_scatter(out, len_io[0], len_io[1], len_io[2], len_io[3], len_io[4], workspace);
             }
          } else {
             recv_bulk(thread, out, len_io[0]);
          }
       }
    }
    return res;
 }
rpc_release()
void rpc_release (CLIENT_THREAD_STATE_T * thread)
Definition at line 498 of file khrn_client_rpc_linux.c.
References UNUSED.
 { // TODO - implement this for linux
    UNUSED(thread);
 }
rpc_send_bulk()
void rpc_send_bulk (CLIENT_THREAD_STATE_T * thread, const void * in, uint32_t len)
Definition at line 394 of file khrn_client_rpc_linux.c.
 {
    if (in && len) {
       //CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
       merge_flush(thread);
       send_bulk(thread, in, len);
    }
 }
rpc_send_bulk_gather()
void rpc_send_bulk_gather (CLIENT_THREAD_STATE_T * thread, const void * in, uint32_t len, int32_t stride, uint32_t n)
Definition at line 405 of file khrn_client_rpc_linux.c.
 {
 #if 1
    if (in && len) {
       //CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
       merge_flush(thread);
       if (len == stride) {
          /* hopefully should be the common case */
          send_bulk(thread, in, n * len);
       } else {
          check_workspace(n * len);
          rpc_gather(workspace, in, len, stride, n);
          send_bulk(thread, workspace, n * len);
       }
    }
 #else
    UNREACHABLE();
 #endif
 }
rpc_send_ctrl_begin()
void rpc_send_ctrl_begin (CLIENT_THREAD_STATE_T * thread, uint32_t len)
Definition at line 328 of file khrn_client_rpc_linux.c.
References vcos_assert.
 {
    //CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    vcos_assert(len == rpc_pad_ctrl(len));
    if ((thread->merge_pos + len) > MERGE_BUFFER_SIZE) {
       merge_flush(thread);
    }
    thread->merge_end = thread->merge_pos + len;
 }
rpc_send_ctrl_end()
void rpc_send_ctrl_end (CLIENT_THREAD_STATE_T * thread)
Definition at line 349 of file khrn_client_rpc_linux.c.
References CLIENT_THREAD_STATE::merge_end, CLIENT_THREAD_STATE::merge_pos, and vcos_assert.
 {
    //CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    vcos_assert(thread->merge_pos == thread->merge_end);
 }
rpc_send_ctrl_longest()
uint32_t rpc_send_ctrl_longest (CLIENT_THREAD_STATE_T * thread, uint32_t len_min)
Definition at line 319 of file khrn_client_rpc_linux.c.
References CLIENT_MAKE_CURRENT_SIZE, len, MERGE_BUFFER_SIZE, and CLIENT_THREAD_STATE::merge_pos.
 {
    uint32_t len = MERGE_BUFFER_SIZE - thread->merge_pos;
    if (len < len_min) {
       len = MERGE_BUFFER_SIZE - CLIENT_MAKE_CURRENT_SIZE;
    }
    return len;
 }
rpc_send_ctrl_write()
void rpc_send_ctrl_write (CLIENT_THREAD_STATE_T * thread, const uint32_t in[], uint32_t len)
Definition at line 340 of file khrn_client_rpc_linux.c.
References CLIENT_THREAD_STATE::merge_buffer, and CLIENT_THREAD_STATE::merge_pos.
 {
    //CLIENT_THREAD_STATE_T *thread = CLIENT_GET_THREAD_STATE();
    memcpy(thread->merge_buffer + thread->merge_pos, in, len);
    thread->merge_pos += rpc_pad_ctrl(len);
    vcos_assert(thread->merge_pos <= MERGE_BUFFER_SIZE);
 }
rpc_term()
void rpc_term (void)
Definition at line 237 of file khrn_client_rpc_linux.c.
 {
    if (workspace) { khrn_platform_free(workspace); }
    platform_mutex_destroy(&mutex);
 }
rpc_use()
void rpc_use (CLIENT_THREAD_STATE_T * thread)
Definition at line 493 of file khrn_client_rpc_linux.c.
References UNUSED.
 { // TODO - implement this for linux
    UNUSED(thread);
 }
vc_vchi_khronos_init()
void vc_vchi_khronos_init ()
Definition at line 169 of file khrn_client_rpc_linux.c.
References vchiq_service_params_struct::callback, vchiq_service_params_struct::fourcc, FOURCC_KHAN, khan_callback(), NULL, status, UNUSED_NDEBUG, vchiq_service_params_struct::userdata, VC_KHRN_VERSION, vchiq_connect(), vchiq_initialise(), vchiq_open_service(), VCHIQ_SUCCESS, vcos_assert, vcos_event_create(), VCOS_SUCCESS, vchiq_service_params_struct::version, and vchiq_service_params_struct::version_min.
 {
    VCOS_STATUS_T status = vcos_event_create(&bulk_event, NULL);
    UNUSED_NDEBUG(status);
    vcos_assert(status == VCOS_SUCCESS);
    if (vchiq_initialise(&khrn_vchiq_instance) != VCHIQ_SUCCESS)
    {
       vcos_log_error("* failed to open vchiq device");
       exit(1);
    }
    vcos_log_trace("gldemo: connecting");
    if (vchiq_connect(khrn_vchiq_instance) != VCHIQ_SUCCESS)
    {
       vcos_log_error("* failed to connect");
       exit(1);
    }
    VCHIQ_STATUS_T khan_return, khrn_return, khhn_return;
    VCHIQ_SERVICE_PARAMS_T params;
    params.userdata = NULL;
    params.version = VC_KHRN_VERSION;
    params.version_min = VC_KHRN_VERSION;
    params.fourcc = FOURCC_KHAN;
    params.callback = khan_callback;
    khan_return = vchiq_open_service(khrn_vchiq_instance, &params, &vchiq_khan_service);
    params.fourcc = FOURCC_KHRN;
    params.callback = khrn_callback;
    khrn_return = vchiq_open_service(khrn_vchiq_instance, &params, &vchiq_khrn_service);
    params.fourcc = FOURCC_KHHN;
    params.callback = khhn_callback;
    khhn_return = vchiq_open_service(khrn_vchiq_instance, &params, &vchiq_khhn_service);
    if (khan_return != VCHIQ_SUCCESS ||
        khrn_return != VCHIQ_SUCCESS ||
        khhn_return != VCHIQ_SUCCESS)
    {
       vcos_log_error("* failed to add service - already in use?");
       exit(1);
    }
    vchiu_queue_init(&khrn_queue, 64);
    vchiu_queue_init(&khhn_queue, 64);
    vcos_log_trace("gldemo: connected");
    /*
       attach to process (there's just one)
    */
 //   bool success = client_process_attach();
 //   vcos_assert(success);
 }
Variable Documentation
khrn_client_log
VCOS_LOG_CAT_T khrn_client_log
Definition at line 57 of file khrn_client.c.