VideoCore Library: interface/mmal/openmaxil/mmalomx_util_params.c File Reference
mmalomx_util_params.c File Reference
#include "interface/vmcs_host/khronos/IL/OMX_Broadcom.h"
#include "mmalomx.h"
#include "mmalomx_util_params.h"
#include "mmalomx_util_params_common.h"
Functions
const MMALOMX_PARAM_TRANSLATION_T * mmalomx_find_parameter_enum (unsigned int index)
const MMALOMX_PARAM_TRANSLATION_T * mmalomx_find_parameter_from_omx_id (uint32_t id)
const MMALOMX_PARAM_TRANSLATION_T * mmalomx_find_parameter_from_mmal_id (uint32_t id)
const char * mmalomx_parameter_name_omx (uint32_t id)
const char * mmalomx_parameter_name_mmal (uint32_t id)
MMAL_STATUS_T mmalomx_param_mapping_generic (MMALOMX_PARAM_MAPPING_DIRECTION dir, const MMALOMX_PARAM_TRANSLATION_T *xlat, MMAL_PARAMETER_HEADER_T *mmal_param, OMX_PTR omx_param, MMAL_PORT_T *mmal_port)
MMAL_STATUS_T mmalomx_param_enum_generic (MMALOMX_PARAM_MAPPING_DIRECTION dir, const MMALOMX_PARAM_TRANSLATION_T *xlat, MMAL_PARAMETER_HEADER_T *mmal_param, OMX_PTR omx_param, MMAL_PORT_T *mmal_port)
MMAL_STATUS_T mmalomx_param_rational_generic (MMALOMX_PARAM_MAPPING_DIRECTION dir, const MMALOMX_PARAM_TRANSLATION_T *xlat, MMAL_PARAMETER_HEADER_T *mmal_param, OMX_PTR omx_param, MMAL_PORT_T *mmal_port)
Function Documentation
mmalomx_find_parameter_enum()
const MMALOMX_PARAM_TRANSLATION_T* mmalomx_find_parameter_enum (unsigned int index)
Definition at line 37 of file mmalomx_util_params.c.
References MMAL_COUNTOF, MMALOMX_PARAM_TRANSLATION_T::mmal_id, MMAL_PARAMETER_UNUSED, and NULL.
Referenced by mmalomx_parameter_extension_index_get().
 {
    unsigned int i, j;
    for (i = 0; i < MMAL_COUNTOF(mmalomx_param_list); i++)
    {
       for (j = 0; mmalomx_param_list[i][j].mmal_id != MMAL_PARAMETER_UNUSED; j++)
       {
          if (!index--)
             break;
       }
       if (mmalomx_param_list[i][j].mmal_id != MMAL_PARAMETER_UNUSED)
          break;
    }
    return i < MMAL_COUNTOF(mmalomx_param_list) ? &mmalomx_param_list[i][j] : NULL;
 }
mmalomx_find_parameter_from_mmal_id()
const MMALOMX_PARAM_TRANSLATION_T* mmalomx_find_parameter_from_mmal_id (uint32_t id)
Definition at line 73 of file mmalomx_util_params.c.
References MMAL_COUNTOF, MMALOMX_PARAM_TRANSLATION_T::mmal_id, MMAL_PARAMETER_UNUSED, and NULL.
Referenced by mmalomx_parameter_name_mmal().
 {
    unsigned int i, j;
    for (i = 0; i < MMAL_COUNTOF(mmalomx_param_list); i++)
    {
       for (j = 0; mmalomx_param_list[i][j].mmal_id != MMAL_PARAMETER_UNUSED; j++)
       {
          if (mmalomx_param_list[i][j].mmal_id == id)
             break;
       }
       if (mmalomx_param_list[i][j].mmal_id != MMAL_PARAMETER_UNUSED)
          break;
    }
    return i < MMAL_COUNTOF(mmalomx_param_list) ? &mmalomx_param_list[i][j] : NULL;
 }
mmalomx_find_parameter_from_omx_id()
const MMALOMX_PARAM_TRANSLATION_T* mmalomx_find_parameter_from_omx_id (uint32_t id)
Definition at line 55 of file mmalomx_util_params.c.
References MMAL_COUNTOF, MMALOMX_PARAM_TRANSLATION_T::mmal_id, MMAL_PARAMETER_UNUSED, and NULL.
Referenced by mmalomx_parameter_name_omx().
 {
    unsigned int i, j;
    for (i = 0; i < MMAL_COUNTOF(mmalomx_param_list); i++)
    {
       for (j = 0; mmalomx_param_list[i][j].mmal_id != MMAL_PARAMETER_UNUSED; j++)
       {
          if (mmalomx_param_list[i][j].omx_id == id)
             break;
       }
       if (mmalomx_param_list[i][j].mmal_id != MMAL_PARAMETER_UNUSED)
          break;
    }
    return i < MMAL_COUNTOF(mmalomx_param_list) ? &mmalomx_param_list[i][j] : NULL;
 }
mmalomx_param_enum_generic()
MMAL_STATUS_T mmalomx_param_enum_generic (MMALOMX_PARAM_MAPPING_DIRECTION dir, const MMALOMX_PARAM_TRANSLATION_T * xlat, MMAL_PARAMETER_HEADER_T * mmal_param, OMX_PTR omx_param, MMAL_PORT_T * mmal_port)
Definition at line 132 of file mmalomx_util_params.c.
References mmal, MMALOMX_PARAM_ENUM_TRANSLATE_T::mmal, MMAL_EINVAL, MMAL_PARAM_UNUSED, MMAL_SUCCESS, MMALOMX_PARAM_MAPPING_TO_MMAL, omx, MMALOMX_PARAM_ENUM_TRANSLATE_T::omx, MMALOMX_PARAM_TRANSLATION_T::portless, MMALOMX_PARAM_TRANSLATION_T::xlat_enum, and MMALOMX_PARAM_TRANSLATION_T::xlat_enum_num.
 {
    uint32_t *mmal = (uint32_t *)(((uint8_t *)mmal_param) + sizeof(MMAL_PARAMETER_HEADER_T));
    uint32_t *omx = (uint32_t *)(((uint8_t *)omx_param) + sizeof(MMALOMX_PARAM_OMX_HEADER_T));
    unsigned int i = 0;
    MMAL_PARAM_UNUSED(mmal_port);
    if (xlat->portless)
       omx -= 1;
    /* Find translation entry in lookup table */
    if (dir == MMALOMX_PARAM_MAPPING_TO_MMAL)
       for (i = 0; i < xlat->xlat_enum_num && xlat->xlat_enum->omx != *omx; i++);
    else
       for (i = 0; i < xlat->xlat_enum_num && xlat->xlat_enum->mmal != *mmal; i++);
    if (i == xlat->xlat_enum_num)
    {
       if (dir == MMALOMX_PARAM_MAPPING_TO_MMAL)
          VCOS_ALERT("mmalomx_param_enum_generic: omx enum value %u not supported", (unsigned int)*omx);
       else
          VCOS_ALERT("mmalomx_param_enum_generic: mmal enum value %u not supported", (unsigned int)*mmal);
       return MMAL_EINVAL;
    }
    if (dir == MMALOMX_PARAM_MAPPING_TO_MMAL)
       *mmal = xlat->xlat_enum[i].mmal;
    else
       *omx = xlat->xlat_enum[i].omx;
    return MMAL_SUCCESS;
 }
mmalomx_param_mapping_generic()
MMAL_STATUS_T mmalomx_param_mapping_generic (MMALOMX_PARAM_MAPPING_DIRECTION dir, const MMALOMX_PARAM_TRANSLATION_T * xlat, MMAL_PARAMETER_HEADER_T * mmal_param, OMX_PTR omx_param, MMAL_PORT_T * mmal_port)
Definition at line 103 of file mmalomx_util_params.c.
References MMAL_PARAMETER_HEADER_T::id, MMAL_EINVAL, MMAL_PARAM_UNUSED, MMAL_SUCCESS, MMALOMX_PARAM_MAPPING_TO_MMAL, MMALOMX_PARAM_OMX_HEADER_T::nSize, MMALOMX_PARAM_TRANSLATION_T::portless, and MMAL_PARAMETER_HEADER_T::size.
 {
    MMALOMX_PARAM_OMX_HEADER_T *omx_header = (MMALOMX_PARAM_OMX_HEADER_T *)omx_param;
    uint8_t *mmal_data = ((uint8_t *)mmal_param) + sizeof(MMAL_PARAMETER_HEADER_T);
    uint8_t *omx_data = ((uint8_t *)omx_param) + sizeof(MMALOMX_PARAM_OMX_HEADER_T);
    unsigned int size = mmal_param->size - sizeof(MMAL_PARAMETER_HEADER_T);
    MMAL_PARAM_UNUSED(mmal_port);
    if (xlat->portless)
       omx_data -= sizeof(OMX_U32);
    if (((uint8_t *)omx_param) + omx_header->nSize !=
          omx_data + size)
    {
       VCOS_ALERT("mmalomx_param_mapping_generic: mismatch between mmal and omx parameters for (%u)",
                  (unsigned int)mmal_param->id);
       return MMAL_EINVAL;
    }
    if (dir == MMALOMX_PARAM_MAPPING_TO_MMAL)
       memcpy(mmal_data, omx_data, size);
    else
       memcpy(omx_data, mmal_data, size);
    return MMAL_SUCCESS;
 }
mmalomx_param_rational_generic()
MMAL_STATUS_T mmalomx_param_rational_generic (MMALOMX_PARAM_MAPPING_DIRECTION dir, const MMALOMX_PARAM_TRANSLATION_T * xlat, MMAL_PARAMETER_HEADER_T * mmal_param, OMX_PTR omx_param, MMAL_PORT_T * mmal_port)
Definition at line 167 of file mmalomx_util_params.c.
References MMAL_RATIONAL_T::den, mmal, MMAL_PARAM_UNUSED, mmal_rational_simplify(), MMAL_SUCCESS, MMALOMX_PARAM_MAPPING_TO_MMAL, MMAL_RATIONAL_T::num, omx, MMALOMX_PARAM_TRANSLATION_T::portless, and MMALOMX_PARAM_TRANSLATION_T::xlat_enum_num.
 {
    MMAL_RATIONAL_T *mmal = (MMAL_RATIONAL_T *)(((uint8_t *)mmal_param) + sizeof(MMAL_PARAMETER_HEADER_T));
    int32_t *omx = (int32_t *)(((uint8_t *)omx_param) + sizeof(MMALOMX_PARAM_OMX_HEADER_T));
    MMAL_PARAM_UNUSED(mmal_port);
    if (xlat->portless)
       omx -= 1;
    if (dir == MMALOMX_PARAM_MAPPING_TO_MMAL)
    {
       mmal->num = *omx;
       mmal->den = xlat->xlat_enum_num;
       mmal_rational_simplify(mmal);
    }
    else
    {
       mmal_rational_simplify(mmal);
       *omx = 0;
       if (mmal->den)
          *omx = mmal->num * xlat->xlat_enum_num / mmal->den;
    }
    return MMAL_SUCCESS;
 }
mmalomx_parameter_name_mmal()
const char* mmalomx_parameter_name_mmal (uint32_t id)
Definition at line 97 of file mmalomx_util_params.c.
References MMALOMX_PARAM_TRANSLATION_T::mmal_name, and mmalomx_find_parameter_from_mmal_id().
 {
    const MMALOMX_PARAM_TRANSLATION_T *xlat = mmalomx_find_parameter_from_mmal_id(id);
    return xlat ? xlat->mmal_name : 0;
 }
mmalomx_parameter_name_omx()
const char* mmalomx_parameter_name_omx (uint32_t id)
Definition at line 91 of file mmalomx_util_params.c.
References mmalomx_find_parameter_from_omx_id(), and MMALOMX_PARAM_TRANSLATION_T::omx_name.
Referenced by mmalomx_param_to_string().
 {
    const MMALOMX_PARAM_TRANSLATION_T *xlat = mmalomx_find_parameter_from_omx_id(id);
    return xlat ? xlat->omx_name : 0;
 }