VideoCore Library: containers/test/uri_pipe.c File Reference
uri_pipe.c File Reference
#include <stdio.h>
#include "containers/containers.h"
#include "containers/core/containers_logging.h"
#include "containers/core/containers_io.h"
#include "nb_io.h"
Macros
#define MAX_BUFFER_SIZE 2048
Functions
int main (int argc, char **argv)
Macro Definition Documentation
MAX_BUFFER_SIZE
#define MAX_BUFFER_SIZE 2048
Definition at line 36 of file uri_pipe.c.
Referenced by main().
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 38 of file uri_pipe.c.
References LOG_INFO, MAX_BUFFER_SIZE, nb_char_available(), nb_get_char(), nb_set_nonblocking_input(), NULL, status, VC_CONTAINER_IO_T::status, VC_CONTAINER_ERROR_EOS, vc_container_io_close(), VC_CONTAINER_IO_MODE_READ, VC_CONTAINER_IO_MODE_WRITE, vc_container_io_open(), vc_container_io_read(), vc_container_io_write(), and VC_CONTAINER_SUCCESS.
 {
    char buffer[MAX_BUFFER_SIZE];
    VC_CONTAINER_IO_T *read_io, *write_io;
    VC_CONTAINER_STATUS_T status;
    size_t received;
    bool ready = true;
    if (argc < 3)
    {
       LOG_INFO(NULL, "Usage:\n%s <read URI> <write URI>\n", argv[0]);
       return 1;
    }
    read_io = vc_container_io_open(argv[1], VC_CONTAINER_IO_MODE_READ, &status);
    if (!read_io)
    {
       LOG_INFO(NULL, "Opening <%s> for read failed: %d\n", argv[1], status);
       return 2;
    }
    write_io = vc_container_io_open(argv[2], VC_CONTAINER_IO_MODE_WRITE, &status);
    if (!write_io)
    {
       vc_container_io_close(read_io);
       LOG_INFO(NULL, "Opening <%s> for write failed: %d\n", argv[2], status);
       return 3;
    }
    nb_set_nonblocking_input(1);
    while (ready)
    {
       size_t total_written = 0;
       received = vc_container_io_read(read_io, buffer, sizeof(buffer));
       while (ready && total_written < received)
       {
          total_written += vc_container_io_write(write_io, buffer + total_written, received - total_written);
          ready &= (write_io->status == VC_CONTAINER_SUCCESS);
       }
       ready &= (read_io->status == VC_CONTAINER_SUCCESS);
       if (nb_char_available())
       {
          char c = nb_get_char();
          switch (c)
          {
          case 'q':
          case 'Q':
          case 0x04:  /* CTRL+D */
          case 0x1A:  /* CTRL+Z */
          case 0x1B:  /* Escape */
             ready = false;
             break;
          default:
             ;/* Do nothing */
          }
       }
    }
    if (read_io->status != VC_CONTAINER_SUCCESS && read_io->status != VC_CONTAINER_ERROR_EOS)
    {
       LOG_INFO(NULL, "Read failed: %d\n", read_io->status);
    }
    if (write_io->status != VC_CONTAINER_SUCCESS)
    {
       LOG_INFO(NULL, "Write failed: %d\n", write_io->status);
    }
    vc_container_io_close(read_io);
    vc_container_io_close(write_io);
    nb_set_nonblocking_input(0);
    return 0;
 }