VideoCore Library: containers/mp4/mp4_writer.c File Reference
mp4_writer.c File Reference
#include <stdlib.h>
#include <string.h>
#include "containers/core/containers_private.h"
#include "containers/core/containers_io_helpers.h"
#include "containers/core/containers_utils.h"
#include "containers/core/containers_writer_utils.h"
#include "containers/core/containers_logging.h"
#include "containers/mp4/mp4_common.h"
Classes
struct VC_CONTAINER_TRACK_MODULE_T
struct VC_CONTAINER_MODULE_T
Macros
#define CONTAINER_IS_BIG_ENDIAN
#define CONTAINER_HELPER_LOG_INDENT(a) (a)->priv->module->box_level
#define MP4_TRACKS_MAX 16
#define MP4_TIMESCALE 1000
#define MP4_64BITS_TIME 0 /* 0 to disable / 1 to enable */
#define MP4_GET_DESCRIPTOR_SIZE(size) ((size) < 0x0080) ? 2 + (size) : ((size) < 0x4000) ? 3 + (size) : 4 + (size)
#define MP4_WRITE_DESCRIPTOR_HEADER(type, size)
Typedefs
typedef struct VC_CONTAINER_TRACK_MODULE_T VC_CONTAINER_TRACK_MODULE_T
typedef struct VC_CONTAINER_MODULE_T VC_CONTAINER_MODULE_T
Functions
VC_CONTAINER_STATUS_T mp4_writer_open (VC_CONTAINER_T *p_ctx)
Macro Definition Documentation
CONTAINER_HELPER_LOG_INDENT
#define CONTAINER_HELPER_LOG_INDENT (a) (a)->priv->module->box_level
Definition at line 38 of file mp4_writer.c.
CONTAINER_IS_BIG_ENDIAN
#define CONTAINER_IS_BIG_ENDIAN
Definition at line 30 of file mp4_writer.c.
MP4_64BITS_TIME
#define MP4_64BITS_TIME 0 /* 0 to disable / 1 to enable */
Definition at line 48 of file mp4_writer.c.
MP4_GET_DESCRIPTOR_SIZE
#define MP4_GET_DESCRIPTOR_SIZE (size) ((size) < 0x0080) ? 2 + (size) : ((size) < 0x4000) ? 3 + (size) : 4 + (size)
MP4_TIMESCALE
#define MP4_TIMESCALE 1000
Definition at line 46 of file mp4_writer.c.
MP4_TRACKS_MAX
#define MP4_TRACKS_MAX 16
Definition at line 45 of file mp4_writer.c.
MP4_WRITE_DESCRIPTOR_HEADER
#define MP4_WRITE_DESCRIPTOR_HEADER (type, size)
Value:
LOG_FORMAT(p_ctx, "descriptor %x, size %i", type, size); _WRITE_U8(p_ctx, type); \
   if((size) >= 0x4000) _WRITE_U8(p_ctx, (((size) >> 14) & 0x7F) | 0x80); \
   if((size) >= 0x80  ) _WRITE_U8(p_ctx, (((size) >> 7 ) & 0x7F) | 0x80); \
   _WRITE_U8(p_ctx, (size) & 0x7F)
Typedef Documentation
VC_CONTAINER_MODULE_T
typedef struct VC_CONTAINER_MODULE_T VC_CONTAINER_MODULE_T
VC_CONTAINER_TRACK_MODULE_T
typedef struct VC_CONTAINER_TRACK_MODULE_T VC_CONTAINER_TRACK_MODULE_T
Function Documentation
mp4_writer_open()
VC_CONTAINER_STATUS_T mp4_writer_open (VC_CONTAINER_T * p_ctx)
Definition at line 1371 of file mp4_writer.c.
References VC_CONTAINER_MODULE_T::brand, error(), extension, VC_CONTAINER_PRIVATE_T::module, MP4_BRAND_3GP5, MP4_BRAND_ISOM, MP4_BRAND_QT, MP4_BRAND_SKM2, VC_CONTAINER_MODULE_T::null, VC_CONTAINER_T::priv, status, VC_CONTAINER_MODULE_T::temp, VC_CONTAINER_MODULE_T::tracks, VC_CONTAINER_T::tracks, VC_CONTAINER_PRIVATE_T::uri, VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED, VC_CONTAINER_ERROR_OUT_OF_MEMORY, VC_CONTAINER_SUCCESS, vc_container_writer_extraio_create_null(), vc_container_writer_extraio_create_temp(), vc_uri_find_query(), and vc_uri_path_extension().
 {
    VC_CONTAINER_STATUS_T status = VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED;
    const char *extension = vc_uri_path_extension(p_ctx->priv->uri);
    VC_CONTAINER_MODULE_T *module = 0;
    MP4_BRAND_T brand;
    /* Check if the user has specified a container */
    vc_uri_find_query(p_ctx->priv->uri, 0, "container", &extension);
    /* Check we're the right writer for this */
    if(!extension)
       return VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED;
    if(strcasecmp(extension, "3gp") && strcasecmp(extension, "skm") &&
       strcasecmp(extension, "mov") && strcasecmp(extension, "mp4") &&
       strcasecmp(extension, "m4v") && strcasecmp(extension, "m4a"))
       return VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED;
    /* Allocate our context */
    module = malloc(sizeof(*module));
    if(!module) { status = VC_CONTAINER_ERROR_OUT_OF_MEMORY; goto error; }
    memset(module, 0, sizeof(*module));
    p_ctx->priv->module = module;
    p_ctx->tracks = module->tracks;
    /* Find out which brand we're going write */
    if(!strcasecmp(extension, "3gp")) brand = MP4_BRAND_3GP5;
    else if(!strcasecmp(extension, "skm")) brand = MP4_BRAND_SKM2;
    else if(!strcasecmp(extension, "mov")) brand = MP4_BRAND_QT;
    else brand = MP4_BRAND_ISOM;
    module->brand = brand;
    /* Create a null i/o writer to help us out in writing our data */
    status = vc_container_writer_extraio_create_null(p_ctx, &module->null);
    if(status != VC_CONTAINER_SUCCESS) goto error;
    /* Create a temporary i/o writer to help us out in writing our data */
    status = vc_container_writer_extraio_create_temp(p_ctx, &module->temp);
    if(status != VC_CONTAINER_SUCCESS) goto error;
    status = mp4_write_box(p_ctx, MP4_BOX_TYPE_FTYP);
    if(status != VC_CONTAINER_SUCCESS) goto error;
    /* Start the mdat box */
    module->mdat_offset = STREAM_POSITION(p_ctx);
    WRITE_U32(p_ctx, 0, "size");
    WRITE_FOURCC(p_ctx, VC_FOURCC('m','d','a','t'), "type");
    module->data_offset = STREAM_POSITION(p_ctx);
    p_ctx->priv->pf_close = mp4_writer_close;
    p_ctx->priv->pf_write = mp4_writer_write;
    p_ctx->priv->pf_control = mp4_writer_control;
    return VC_CONTAINER_SUCCESS;
  error:
    LOG_DEBUG(p_ctx, "mp4: error opening stream");
    if(module)
    {
       if(module->null.io) vc_container_writer_extraio_delete(p_ctx, &module->null);
       free(module);
    }
    return status;
 }
Variable Documentation
pf_func
VC_CONTAINER_STATUS_T(* pf_func) (VC_CONTAINER_T *)
Definition at line 134 of file mp4_writer.c.
type
const MP4_BOX_TYPE_T type
Definition at line 133 of file mp4_writer.c.