VideoCore Library: containers/core/containers_io_helpers.h File Reference
containers_io_helpers.h File Reference
#include "containers/core/containers_io.h"
#include "containers/core/containers_utils.h"
Macros
#define STREAM_POSITION(ctx) (ctx)->priv->io->offset
#define STREAM_EOS(ctx) ((ctx)->priv->io->status == VC_CONTAINER_ERROR_EOS)
#define STREAM_STATUS(ctx) (ctx)->priv->io->status
#define STREAM_ERROR(ctx) ((ctx)->priv->io->status && (ctx)->priv->io->status != VC_CONTAINER_ERROR_EOS)
#define STREAM_SEEKABLE(ctx) (!((ctx)->priv->io->capabilities & VC_CONTAINER_IO_CAPS_CANT_SEEK))
#define PEEK_BYTES(ctx, buffer, size) vc_container_io_peek((ctx)->priv->io, buffer, (size_t)(size))
#define READ_BYTES(ctx, buffer, size) vc_container_io_read((ctx)->priv->io, buffer, (size_t)(size))
#define SKIP_BYTES(ctx, size) vc_container_io_skip((ctx)->priv->io, (size_t)(size))
#define SEEK(ctx, off) vc_container_io_seek((ctx)->priv->io, (int64_t)(off))
#define CACHE_BYTES(ctx, size) vc_container_io_cache((ctx)->priv->io, (size_t)(size))
#define _SKIP_GUID(ctx) vc_container_io_skip((ctx)->priv->io, 16)
#define _SKIP_U8(ctx) (vc_container_io_skip((ctx)->priv->io, 1) != 1)
#define _SKIP_U16(ctx) (vc_container_io_skip((ctx)->priv->io, 2) != 2)
#define _SKIP_U24(ctx) (vc_container_io_skip((ctx)->priv->io, 3) != 3)
#define _SKIP_U32(ctx) (vc_container_io_skip((ctx)->priv->io, 4) != 4)
#define _SKIP_U64(ctx) (vc_container_io_skip((ctx)->priv->io, 8) != 8)
#define _SKIP_FOURCC(ctx) (vc_container_io_skip((ctx)->priv->io, 4) != 4)
#define _READ_GUID(ctx, buffer) vc_container_io_read((ctx)->priv->io, buffer, 16)
#define _READ_U8(ctx) vc_container_io_read_uint8((ctx)->priv->io)
#define _READ_FOURCC(ctx) vc_container_io_read_fourcc((ctx)->priv->io)
#define PEEK_GUID(ctx, buffer) vc_container_io_peek((ctx)->priv->io, buffer, 16)
#define PEEK_U8(ctx) vc_container_io_peek_uint8((ctx)->priv->io)
#define _READ_U16(ctx) vc_container_io_read_le_uint16((ctx)->priv->io)
#define _READ_U24(ctx) vc_container_io_read_le_uint24((ctx)->priv->io)
#define _READ_U32(ctx) vc_container_io_read_le_uint32((ctx)->priv->io)
#define _READ_U40(ctx) vc_container_io_read_le_uint40((ctx)->priv->io)
#define _READ_U48(ctx) vc_container_io_read_le_uint48((ctx)->priv->io)
#define _READ_U56(ctx) vc_container_io_read_le_uint56((ctx)->priv->io)
#define _READ_U64(ctx) vc_container_io_read_le_uint64((ctx)->priv->io)
#define PEEK_U16(ctx) vc_container_io_peek_le_uint16((ctx)->priv->io)
#define PEEK_U24(ctx) vc_container_io_peek_le_uint24((ctx)->priv->io)
#define PEEK_U32(ctx) vc_container_io_peek_le_uint32((ctx)->priv->io)
#define PEEK_U64(ctx) vc_container_io_peek_le_uint64((ctx)->priv->io)
#define WRITE_BYTES(ctx, buffer, size) vc_container_io_write((ctx)->priv->io, buffer, (size_t)(size))
#define _WRITE_GUID(ctx, buffer) vc_container_io_write((ctx)->priv->io, buffer, 16)
#define _WRITE_U8(ctx, v) vc_container_io_write_uint8((ctx)->priv->io, v)
#define _WRITE_FOURCC(ctx, v) vc_container_io_write_fourcc((ctx)->priv->io, v)
#define _WRITE_U16(ctx, v) vc_container_io_write_le_uint16((ctx)->priv->io, v)
#define _WRITE_U24(ctx, v) vc_container_io_write_le_uint24((ctx)->priv->io, v)
#define _WRITE_U32(ctx, v) vc_container_io_write_le_uint32((ctx)->priv->io, v)
#define _WRITE_U64(ctx, v) vc_container_io_write_le_uint64((ctx)->priv->io, v)
#define CONTAINER_HELPER_LOG_INDENT(a) 0
#define LOG_FORMAT_TYPE_UINT LOG_FORMAT_TYPE_UINT_LE
#define LOG_FORMAT_TYPE_STRING_UTF16 LOG_FORMAT_TYPE_STRING_UTF16_LE
#define SKIP_GUID(ctx, n) _SKIP_GUID(ctx)
#define SKIP_U8(ctx, n) _SKIP_U8(ctx)
#define SKIP_U16(ctx, n) _SKIP_U16(ctx)
#define SKIP_U24(ctx, n) _SKIP_U24(ctx)
#define SKIP_U32(ctx, n) _SKIP_U32(ctx)
#define SKIP_U64(ctx, n) _SKIP_U64(ctx)
#define SKIP_FOURCC(ctx, n) _SKIP_FOURCC(ctx)
#define READ_GUID(ctx, buffer, n) _READ_GUID(ctx,(uint8_t *)buffer)
#define READ_U8(ctx, n) _READ_U8(ctx)
#define READ_U16(ctx, n) _READ_U16(ctx)
#define READ_U24(ctx, n) _READ_U24(ctx)
#define READ_U32(ctx, n) _READ_U32(ctx)
#define READ_U40(ctx, n) _READ_U40(ctx)
#define READ_U48(ctx, n) _READ_U48(ctx)
#define READ_U56(ctx, n) _READ_U56(ctx)
#define READ_U64(ctx, n) _READ_U64(ctx)
#define READ_FOURCC(ctx, n) _READ_FOURCC(ctx)
#define READ_STRING(ctx, buffer, sz, n) READ_BYTES(ctx,buffer,sz)
#define READ_STRING_UTF16(ctx, buffer, sz, n) READ_BYTES(ctx,buffer,sz)
#define SKIP_STRING(ctx, sz, n) SKIP_BYTES(ctx,sz)
#define SKIP_STRING_UTF16(ctx, sz, n) SKIP_BYTES(ctx,sz)
#define WRITE_GUID(ctx, buffer, n) _WRITE_GUID(ctx,(const uint8_t *)buffer)
#define WRITE_U8(ctx, v, n) _WRITE_U8(ctx,(uint8_t)(v))
#define WRITE_FOURCC(ctx, v, n) _WRITE_FOURCC(ctx,(uint32_t)(v))
#define WRITE_U16(ctx, v, n) _WRITE_U16(ctx,(uint16_t)(v))
#define WRITE_U24(ctx, v, n) _WRITE_U24(ctx,(uint32_t)(v))
#define WRITE_U32(ctx, v, n) _WRITE_U32(ctx,(uint32_t)(v))
#define WRITE_U64(ctx, v, n) _WRITE_U64(ctx,(uint64_t)(v))
#define WRITE_STRING(ctx, buffer, size, n) WRITE_BYTES(ctx, buffer, size)
#define LOG_FORMAT(ctx, ...) do {} while (0)
#define LOG_FORMAT_TYPE_UINT_LE 0
#define LOG_FORMAT_TYPE_UINT_BE 1
#define LOG_FORMAT_TYPE_STRING 2
#define LOG_FORMAT_TYPE_STRING_UTF16_LE 3
#define LOG_FORMAT_TYPE_STRING_UTF16_BE 4
#define LOG_FORMAT_TYPE_FOURCC 5
#define LOG_FORMAT_TYPE_GUID 6
#define LOG_FORMAT_TYPE_HEX 0x100
Functions
STATIC_INLINE uint8_t vc_container_io_read_uint8 (VC_CONTAINER_IO_T *io)
STATIC_INLINE VC_CONTAINER_FOURCC_T vc_container_io_read_fourcc (VC_CONTAINER_IO_T *io)
STATIC_INLINE uint16_t vc_container_io_read_be_uint16 (VC_CONTAINER_IO_T *io)
STATIC_INLINE uint32_t vc_container_io_read_be_uint24 (VC_CONTAINER_IO_T *io)
STATIC_INLINE uint32_t vc_container_io_read_be_uint32 (VC_CONTAINER_IO_T *io)
STATIC_INLINE uint64_t vc_container_io_read_be_uint40 (VC_CONTAINER_IO_T *io)
STATIC_INLINE uint64_t vc_container_io_read_be_uint48 (VC_CONTAINER_IO_T *io)
STATIC_INLINE uint64_t vc_container_io_read_be_uint56 (VC_CONTAINER_IO_T *io)
STATIC_INLINE uint64_t vc_container_io_read_be_uint64 (VC_CONTAINER_IO_T *io)
STATIC_INLINE uint16_t vc_container_io_read_le_uint16 (VC_CONTAINER_IO_T *io)
STATIC_INLINE uint32_t vc_container_io_read_le_uint24 (VC_CONTAINER_IO_T *io)
STATIC_INLINE uint32_t vc_container_io_read_le_uint32 (VC_CONTAINER_IO_T *io)
STATIC_INLINE uint64_t vc_container_io_read_le_uint40 (VC_CONTAINER_IO_T *io)
STATIC_INLINE uint64_t vc_container_io_read_le_uint48 (VC_CONTAINER_IO_T *io)
STATIC_INLINE uint64_t vc_container_io_read_le_uint56 (VC_CONTAINER_IO_T *io)
STATIC_INLINE uint64_t vc_container_io_read_le_uint64 (VC_CONTAINER_IO_T *io)
STATIC_INLINE uint8_t vc_container_io_peek_uint8 (VC_CONTAINER_IO_T *io)
STATIC_INLINE uint16_t vc_container_io_peek_be_uint16 (VC_CONTAINER_IO_T *io)
STATIC_INLINE uint32_t vc_container_io_peek_be_uint24 (VC_CONTAINER_IO_T *io)
STATIC_INLINE uint32_t vc_container_io_peek_be_uint32 (VC_CONTAINER_IO_T *io)
STATIC_INLINE uint64_t vc_container_io_peek_be_uint64 (VC_CONTAINER_IO_T *io)
STATIC_INLINE uint16_t vc_container_io_peek_le_uint16 (VC_CONTAINER_IO_T *io)
STATIC_INLINE uint32_t vc_container_io_peek_le_uint24 (VC_CONTAINER_IO_T *io)
STATIC_INLINE uint32_t vc_container_io_peek_le_uint32 (VC_CONTAINER_IO_T *io)
STATIC_INLINE uint64_t vc_container_io_peek_le_uint64 (VC_CONTAINER_IO_T *io)
STATIC_INLINE VC_CONTAINER_STATUS_T vc_container_io_write_uint8 (VC_CONTAINER_IO_T *io, uint8_t value)
STATIC_INLINE VC_CONTAINER_STATUS_T vc_container_io_write_fourcc (VC_CONTAINER_IO_T *io, VC_CONTAINER_FOURCC_T value)
STATIC_INLINE VC_CONTAINER_STATUS_T vc_container_io_write_be_uint16 (VC_CONTAINER_IO_T *io, uint16_t value)
STATIC_INLINE VC_CONTAINER_STATUS_T vc_container_io_write_be_uint24 (VC_CONTAINER_IO_T *io, uint32_t value)
STATIC_INLINE VC_CONTAINER_STATUS_T vc_container_io_write_be_uint32 (VC_CONTAINER_IO_T *io, uint32_t value)
STATIC_INLINE VC_CONTAINER_STATUS_T vc_container_io_write_be_uint64 (VC_CONTAINER_IO_T *io, uint64_t value)
STATIC_INLINE VC_CONTAINER_STATUS_T vc_container_io_write_le_uint16 (VC_CONTAINER_IO_T *io, uint16_t value)
STATIC_INLINE VC_CONTAINER_STATUS_T vc_container_io_write_le_uint24 (VC_CONTAINER_IO_T *io, uint32_t value)
STATIC_INLINE VC_CONTAINER_STATUS_T vc_container_io_write_le_uint32 (VC_CONTAINER_IO_T *io, uint32_t value)
STATIC_INLINE VC_CONTAINER_STATUS_T vc_container_io_write_le_uint64 (VC_CONTAINER_IO_T *io, uint64_t value)
uint64_t vc_container_helper_int_debug (VC_CONTAINER_T *ctx, int type, uint64_t value, const char *name, int indent)
uint64_t vc_container_helper_read_debug (VC_CONTAINER_T *ctx, int type, int size, const char *name, uint8_t *buffer, int indent, int b_skip)
VC_CONTAINER_STATUS_T vc_container_helper_write_debug (VC_CONTAINER_T *ctx, int type, int size, const char *name, uint64_t value, const uint8_t *buffer, int indent, int silent)
void vc_container_helper_format_debug (VC_CONTAINER_T *ctx, int indent, const char *format,...)
Detailed Description
Helper functions and macros which provide functionality which is often used by containers
Definition in file containers_io_helpers.h.
Macro Definition Documentation
_READ_FOURCC
#define _READ_FOURCC (ctx) vc_container_io_read_fourcc((ctx)->priv->io)
Definition at line 569 of file containers_io_helpers.h.
_READ_GUID
#define _READ_GUID (ctx, buffer) vc_container_io_read((ctx)->priv->io, buffer, 16)
Definition at line 567 of file containers_io_helpers.h.
_READ_U16
#define _READ_U16 (ctx) vc_container_io_read_le_uint16((ctx)->priv->io)
Definition at line 585 of file containers_io_helpers.h.
_READ_U24
#define _READ_U24 (ctx) vc_container_io_read_le_uint24((ctx)->priv->io)
Definition at line 586 of file containers_io_helpers.h.
_READ_U32
#define _READ_U32 (ctx) vc_container_io_read_le_uint32((ctx)->priv->io)
Definition at line 587 of file containers_io_helpers.h.
_READ_U40
#define _READ_U40 (ctx) vc_container_io_read_le_uint40((ctx)->priv->io)
Definition at line 588 of file containers_io_helpers.h.
_READ_U48
#define _READ_U48 (ctx) vc_container_io_read_le_uint48((ctx)->priv->io)
Definition at line 589 of file containers_io_helpers.h.
_READ_U56
#define _READ_U56 (ctx) vc_container_io_read_le_uint56((ctx)->priv->io)
Definition at line 590 of file containers_io_helpers.h.
_READ_U64
#define _READ_U64 (ctx) vc_container_io_read_le_uint64((ctx)->priv->io)
Definition at line 591 of file containers_io_helpers.h.
_READ_U8
#define _READ_U8 (ctx) vc_container_io_read_uint8((ctx)->priv->io)
Definition at line 568 of file containers_io_helpers.h.
_SKIP_FOURCC
#define _SKIP_FOURCC (ctx) (vc_container_io_skip((ctx)->priv->io, 4) != 4)
Definition at line 565 of file containers_io_helpers.h.
_SKIP_GUID
#define _SKIP_GUID (ctx) vc_container_io_skip((ctx)->priv->io, 16)
Definition at line 559 of file containers_io_helpers.h.
_SKIP_U16
#define _SKIP_U16 (ctx) (vc_container_io_skip((ctx)->priv->io, 2) != 2)
Definition at line 561 of file containers_io_helpers.h.
_SKIP_U24
#define _SKIP_U24 (ctx) (vc_container_io_skip((ctx)->priv->io, 3) != 3)
Definition at line 562 of file containers_io_helpers.h.
_SKIP_U32
#define _SKIP_U32 (ctx) (vc_container_io_skip((ctx)->priv->io, 4) != 4)
Definition at line 563 of file containers_io_helpers.h.
_SKIP_U64
#define _SKIP_U64 (ctx) (vc_container_io_skip((ctx)->priv->io, 8) != 8)
Definition at line 564 of file containers_io_helpers.h.
_SKIP_U8
#define _SKIP_U8 (ctx) (vc_container_io_skip((ctx)->priv->io, 1) != 1)
Definition at line 560 of file containers_io_helpers.h.
_WRITE_FOURCC
#define _WRITE_FOURCC (ctx, v) vc_container_io_write_fourcc((ctx)->priv->io, v)
Definition at line 601 of file containers_io_helpers.h.
_WRITE_GUID
#define _WRITE_GUID (ctx, buffer) vc_container_io_write((ctx)->priv->io, buffer, 16)
Definition at line 599 of file containers_io_helpers.h.
_WRITE_U16
#define _WRITE_U16 (ctx, v) vc_container_io_write_le_uint16((ctx)->priv->io, v)
Definition at line 608 of file containers_io_helpers.h.
_WRITE_U24
#define _WRITE_U24 (ctx, v) vc_container_io_write_le_uint24((ctx)->priv->io, v)
Definition at line 609 of file containers_io_helpers.h.
_WRITE_U32
#define _WRITE_U32 (ctx, v) vc_container_io_write_le_uint32((ctx)->priv->io, v)
Definition at line 610 of file containers_io_helpers.h.
_WRITE_U64
#define _WRITE_U64 (ctx, v) vc_container_io_write_le_uint64((ctx)->priv->io, v)
Definition at line 611 of file containers_io_helpers.h.
_WRITE_U8
#define _WRITE_U8 (ctx, v) vc_container_io_write_uint8((ctx)->priv->io, v)
Definition at line 600 of file containers_io_helpers.h.
CACHE_BYTES
#define CACHE_BYTES (ctx, size) vc_container_io_cache((ctx)->priv->io, (size_t)(size))
Definition at line 557 of file containers_io_helpers.h.
CONTAINER_HELPER_LOG_INDENT
#define CONTAINER_HELPER_LOG_INDENT (a) 0
Definition at line 615 of file containers_io_helpers.h.
LOG_FORMAT
#define LOG_FORMAT (ctx, ...) do {} while (0)
Definition at line 695 of file containers_io_helpers.h.
Referenced by ps_reader_open(), and vc_container_write_bitmapinfoheader().
LOG_FORMAT_TYPE_FOURCC
#define LOG_FORMAT_TYPE_FOURCC 5
Definition at line 703 of file containers_io_helpers.h.
Referenced by vc_container_helper_read_debug(), and vc_container_helper_write_debug().
LOG_FORMAT_TYPE_GUID
#define LOG_FORMAT_TYPE_GUID 6
Definition at line 704 of file containers_io_helpers.h.
Referenced by vc_container_helper_read_debug(), and vc_container_helper_write_debug().
LOG_FORMAT_TYPE_HEX
#define LOG_FORMAT_TYPE_HEX 0x100
Definition at line 705 of file containers_io_helpers.h.
Referenced by vc_container_helper_int_debug().
LOG_FORMAT_TYPE_STRING
#define LOG_FORMAT_TYPE_STRING 2
Definition at line 700 of file containers_io_helpers.h.
Referenced by vc_container_helper_read_debug(), and vc_container_helper_write_debug().
LOG_FORMAT_TYPE_STRING_UTF16
#define LOG_FORMAT_TYPE_STRING_UTF16 LOG_FORMAT_TYPE_STRING_UTF16_LE
Definition at line 623 of file containers_io_helpers.h.
LOG_FORMAT_TYPE_STRING_UTF16_BE
#define LOG_FORMAT_TYPE_STRING_UTF16_BE 4
Definition at line 702 of file containers_io_helpers.h.
Referenced by vc_container_helper_read_debug().
LOG_FORMAT_TYPE_STRING_UTF16_LE
#define LOG_FORMAT_TYPE_STRING_UTF16_LE 3
Definition at line 701 of file containers_io_helpers.h.
Referenced by vc_container_helper_read_debug().
LOG_FORMAT_TYPE_UINT
#define LOG_FORMAT_TYPE_UINT LOG_FORMAT_TYPE_UINT_LE
Definition at line 622 of file containers_io_helpers.h.
LOG_FORMAT_TYPE_UINT_BE
#define LOG_FORMAT_TYPE_UINT_BE 1
Definition at line 699 of file containers_io_helpers.h.
Referenced by vc_container_helper_read_debug(), and vc_container_helper_write_debug().
LOG_FORMAT_TYPE_UINT_LE
#define LOG_FORMAT_TYPE_UINT_LE 0
Definition at line 698 of file containers_io_helpers.h.
Referenced by vc_container_helper_read_debug(), and vc_container_helper_write_debug().
PEEK_BYTES
#define PEEK_BYTES (ctx, buffer, size) vc_container_io_peek((ctx)->priv->io, buffer, (size_t)(size))
Definition at line 553 of file containers_io_helpers.h.
Referenced by asf_reader_open(), avi_reader_open(), flv_reader_open(), id3_metadata_reader_open(), mkv_reader_open(), mp4_reader_open(), mpga_reader_open(), ps_find_start_code(), qsynth_reader_open(), rawvideo_reader_open(), rcv_reader_open(), simple_reader_open(), and wav_reader_open().
PEEK_GUID
#define PEEK_GUID (ctx, buffer) vc_container_io_peek((ctx)->priv->io, buffer, 16)
Definition at line 570 of file containers_io_helpers.h.
PEEK_U16
#define PEEK_U16 (ctx) vc_container_io_peek_le_uint16((ctx)->priv->io)
Definition at line 592 of file containers_io_helpers.h.
PEEK_U24
#define PEEK_U24 (ctx) vc_container_io_peek_le_uint24((ctx)->priv->io)
Definition at line 593 of file containers_io_helpers.h.
PEEK_U32
#define PEEK_U32 (ctx) vc_container_io_peek_le_uint32((ctx)->priv->io)
Definition at line 594 of file containers_io_helpers.h.
PEEK_U64
#define PEEK_U64 (ctx) vc_container_io_peek_le_uint64((ctx)->priv->io)
Definition at line 595 of file containers_io_helpers.h.
PEEK_U8
#define PEEK_U8 (ctx) vc_container_io_peek_uint8((ctx)->priv->io)
Definition at line 571 of file containers_io_helpers.h.
READ_BYTES
#define READ_BYTES (ctx, buffer, size) vc_container_io_read((ctx)->priv->io, buffer, (size_t)(size))
Definition at line 554 of file containers_io_helpers.h.
Referenced by wav_reader_open().
READ_FOURCC
#define READ_FOURCC (ctx, n) _READ_FOURCC(ctx)
Definition at line 643 of file containers_io_helpers.h.
Referenced by wav_reader_open().
READ_GUID
#define READ_GUID (ctx, buffer, n) _READ_GUID(ctx,(uint8_t *)buffer)
Definition at line 634 of file containers_io_helpers.h.
Referenced by wav_reader_open().
READ_STRING
#define READ_STRING (ctx, buffer, sz, n) READ_BYTES(ctx,buffer,sz)
Definition at line 644 of file containers_io_helpers.h.
READ_STRING_UTF16
#define READ_STRING_UTF16 (ctx, buffer, sz, n) READ_BYTES(ctx,buffer,sz)
Definition at line 645 of file containers_io_helpers.h.
READ_U16
#define READ_U16 (ctx, n) _READ_U16(ctx)
Definition at line 636 of file containers_io_helpers.h.
Referenced by wav_reader_open().
READ_U24
#define READ_U24 (ctx, n) _READ_U24(ctx)
Definition at line 637 of file containers_io_helpers.h.
READ_U32
#define READ_U32 (ctx, n) _READ_U32(ctx)
Definition at line 638 of file containers_io_helpers.h.
Referenced by flv_reader_open(), and wav_reader_open().
READ_U40
#define READ_U40 (ctx, n) _READ_U40(ctx)
Definition at line 639 of file containers_io_helpers.h.
READ_U48
#define READ_U48 (ctx, n) _READ_U48(ctx)
Definition at line 640 of file containers_io_helpers.h.
READ_U56
#define READ_U56 (ctx, n) _READ_U56(ctx)
Definition at line 641 of file containers_io_helpers.h.
READ_U64
#define READ_U64 (ctx, n) _READ_U64(ctx)
Definition at line 642 of file containers_io_helpers.h.
READ_U8
#define READ_U8 (ctx, n) _READ_U8(ctx)
Definition at line 635 of file containers_io_helpers.h.
Referenced by flv_reader_open().
SEEK
#define SEEK (ctx, off) vc_container_io_seek((ctx)->priv->io, (int64_t)(off))
Definition at line 556 of file containers_io_helpers.h.
SKIP_BYTES
#define SKIP_BYTES (ctx, size) vc_container_io_skip((ctx)->priv->io, (size_t)(size))
Definition at line 555 of file containers_io_helpers.h.
Referenced by flv_reader_open(), ps_find_start_code(), and wav_reader_open().
SKIP_FOURCC
#define SKIP_FOURCC (ctx, n) _SKIP_FOURCC(ctx)
Definition at line 633 of file containers_io_helpers.h.
Referenced by avi_reader_open(), and wav_reader_open().
SKIP_GUID
#define SKIP_GUID (ctx, n) _SKIP_GUID(ctx)
Definition at line 627 of file containers_io_helpers.h.
SKIP_STRING
#define SKIP_STRING (ctx, sz, n) SKIP_BYTES(ctx,sz)
Definition at line 646 of file containers_io_helpers.h.
SKIP_STRING_UTF16
#define SKIP_STRING_UTF16 (ctx, sz, n) SKIP_BYTES(ctx,sz)
Definition at line 647 of file containers_io_helpers.h.
SKIP_U16
#define SKIP_U16 (ctx, n) _SKIP_U16(ctx)
Definition at line 629 of file containers_io_helpers.h.
Referenced by wav_reader_open().
SKIP_U24
#define SKIP_U24 (ctx, n) _SKIP_U24(ctx)
Definition at line 630 of file containers_io_helpers.h.
SKIP_U32
#define SKIP_U32 (ctx, n) _SKIP_U32(ctx)
Definition at line 631 of file containers_io_helpers.h.
Referenced by avi_reader_open(), and wav_reader_open().
SKIP_U64
#define SKIP_U64 (ctx, n) _SKIP_U64(ctx)
Definition at line 632 of file containers_io_helpers.h.
SKIP_U8
#define SKIP_U8 (ctx, n) _SKIP_U8(ctx)
Definition at line 628 of file containers_io_helpers.h.
STREAM_EOS
#define STREAM_EOS (ctx) ((ctx)->priv->io->status == VC_CONTAINER_ERROR_EOS)
Macro which returns true if the end of stream has been reached
Definition at line 545 of file containers_io_helpers.h.
STREAM_ERROR
#define STREAM_ERROR (ctx) ((ctx)->priv->io->status && (ctx)->priv->io->status != VC_CONTAINER_ERROR_EOS)
Macro which returns true if an error other than end of stream has occurred
Definition at line 549 of file containers_io_helpers.h.
STREAM_POSITION
#define STREAM_POSITION (ctx) (ctx)->priv->io->offset
Macro which returns the current position within the stream
Definition at line 543 of file containers_io_helpers.h.
Referenced by ps_reader_open(), vc_container_helper_read_debug(), and wav_reader_open().
STREAM_SEEKABLE
#define STREAM_SEEKABLE (ctx) (!((ctx)->priv->io->capabilities & VC_CONTAINER_IO_CAPS_CANT_SEEK))
Macro which returns true if we can seek into the stream
Definition at line 551 of file containers_io_helpers.h.
Referenced by avi_writer_open(), and wav_reader_open().
STREAM_STATUS
#define STREAM_STATUS (ctx) (ctx)->priv->io->status
Macro which returns the status of the stream
Definition at line 547 of file containers_io_helpers.h.
Referenced by avi_writer_open(), mp4_reader_open(), vc_container_write_bitmapinfoheader(), vc_container_write_waveformatex(), and wav_reader_open().
WRITE_BYTES
#define WRITE_BYTES (ctx, buffer, size) vc_container_io_write((ctx)->priv->io, buffer, (size_t)(size))
Definition at line 598 of file containers_io_helpers.h.
Referenced by vc_container_write_bitmapinfoheader(), and vc_container_write_waveformatex().
WRITE_FOURCC
#define WRITE_FOURCC (ctx, v, n) _WRITE_FOURCC(ctx,(uint32_t)(v))
Definition at line 675 of file containers_io_helpers.h.
Referenced by avi_writer_open().
WRITE_GUID
#define WRITE_GUID (ctx, buffer, n) _WRITE_GUID(ctx,(const uint8_t *)buffer)
Definition at line 673 of file containers_io_helpers.h.
WRITE_STRING
#define WRITE_STRING (ctx, buffer, size, n) WRITE_BYTES(ctx, buffer, size)
Definition at line 680 of file containers_io_helpers.h.
WRITE_U16
#define WRITE_U16 (ctx, v, n) _WRITE_U16(ctx,(uint16_t)(v))
Definition at line 676 of file containers_io_helpers.h.
Referenced by vc_container_write_bitmapinfoheader(), and vc_container_write_waveformatex().
WRITE_U24
#define WRITE_U24 (ctx, v, n) _WRITE_U24(ctx,(uint32_t)(v))
Definition at line 677 of file containers_io_helpers.h.
WRITE_U32
#define WRITE_U32 (ctx, v, n) _WRITE_U32(ctx,(uint32_t)(v))
Definition at line 678 of file containers_io_helpers.h.
Referenced by avi_writer_open(), vc_container_write_bitmapinfoheader(), and vc_container_write_waveformatex().
WRITE_U64
#define WRITE_U64 (ctx, v, n) _WRITE_U64(ctx,(uint64_t)(v))
Definition at line 679 of file containers_io_helpers.h.
WRITE_U8
#define WRITE_U8 (ctx, v, n) _WRITE_U8(ctx,(uint8_t)(v))
Definition at line 674 of file containers_io_helpers.h.
Function Documentation
vc_container_helper_format_debug()
void vc_container_helper_format_debug (VC_CONTAINER_T * ctx, int indent, const char * format, ...)
Definition at line 35 of file containers_io_helpers.c.
References vc_container_log(), and VC_CONTAINER_LOG_FORMAT.
Referenced by vc_container_helper_int_debug(), vc_container_helper_read_debug(), and vc_container_helper_write_debug().
 {
    char debug_string[512];
    va_list args;
    int result;
    if(indent >= (int)sizeof(debug_string)) return;
    memset(debug_string, ' ', indent);
    va_start( args, format );
    result = vsnprintf(debug_string + indent, sizeof(debug_string) - indent, format, args);
    va_end( args );
    if(result <= 0) return;
    vc_container_log(ctx, VC_CONTAINER_LOG_FORMAT, debug_string);
    fflush(0);
 }
vc_container_helper_int_debug()
uint64_t vc_container_helper_int_debug (VC_CONTAINER_T * ctx, int type, uint64_t value, const char * name, int indent)
Definition at line 54 of file containers_io_helpers.c.
References LOG_FORMAT_TYPE_HEX, vc_container_helper_format_debug(), and VC_CONTAINER_PARAM_UNUSED.
 {
    VC_CONTAINER_PARAM_UNUSED(ctx);
    if(type == LOG_FORMAT_TYPE_HEX)
       vc_container_helper_format_debug(ctx, indent, "%s: 0x%"PRIx64, name, value);
    else
       vc_container_helper_format_debug(ctx, indent, "%s: %"PRIi64, name, value);
    return value;
 }
vc_container_helper_read_debug()
uint64_t vc_container_helper_read_debug (VC_CONTAINER_T * ctx, int type, int size, const char * name, uint8_t * buffer, int indent, int b_skip)
Definition at line 65 of file containers_io_helpers.c.
References GUID_T::bytes, guid, VC_CONTAINER_PRIVATE_T::io, LOG_FORMAT_TYPE_FOURCC, LOG_FORMAT_TYPE_GUID, LOG_FORMAT_TYPE_STRING, LOG_FORMAT_TYPE_STRING_UTF16_BE, LOG_FORMAT_TYPE_STRING_UTF16_LE, LOG_FORMAT_TYPE_UINT_BE, LOG_FORMAT_TYPE_UINT_LE, offset, VC_CONTAINER_T::priv, GUID_T::short0, GUID_T::short1, STREAM_POSITION, utf8_from_charset(), vc_container_assert, vc_container_helper_format_debug(), vc_container_io_read(), vc_container_io_read_be_uint16(), vc_container_io_read_be_uint24(), vc_container_io_read_be_uint32(), vc_container_io_read_be_uint40(), vc_container_io_read_be_uint48(), vc_container_io_read_be_uint56(), vc_container_io_read_be_uint64(), vc_container_io_read_fourcc(), vc_container_io_read_le_uint16(), vc_container_io_read_le_uint24(), vc_container_io_read_le_uint32(), vc_container_io_read_le_uint40(), vc_container_io_read_le_uint48(), vc_container_io_read_le_uint56(), vc_container_io_read_le_uint64(), vc_container_io_read_uint8(), vc_container_io_skip(), and GUID_T::word0.
 {
    int64_t offset = STREAM_POSITION(ctx);
    uint64_t value = 0;
    GUID_T guid;
    if(type == LOG_FORMAT_TYPE_STRING ||
       type == LOG_FORMAT_TYPE_STRING_UTF16_LE ||
       type == LOG_FORMAT_TYPE_STRING_UTF16_BE)
    {
       uint8_t stringbuf[256];
       char utf8buf[256];
       int stringsize = sizeof(stringbuf) - 2;
       if(!buffer)
       {
          buffer = stringbuf;
          if(size < stringsize) stringsize = size;
       }
       else stringsize = size;
       value = vc_container_io_read(ctx->priv->io, buffer, stringsize);
       if(!utf8_from_charset(type == LOG_FORMAT_TYPE_STRING ? "UTF8" : "UTF16-LE",
             utf8buf, sizeof(utf8buf), buffer, stringsize))
          vc_container_helper_format_debug(ctx, indent, "%s: \"%s\"", name, utf8buf);
       else
          vc_container_helper_format_debug(ctx, indent, "%s: (could not read)", name);
       if(size - stringsize)
          value += vc_container_io_skip(ctx->priv->io, size - stringsize);
       return value;
    }
    if(type == LOG_FORMAT_TYPE_UINT_LE)
    {
       switch(size)
       {
       case 1: value = vc_container_io_read_uint8(ctx->priv->io);  break;
       case 2: value = vc_container_io_read_le_uint16(ctx->priv->io); break;
       case 3: value = vc_container_io_read_le_uint24(ctx->priv->io); break;
       case 4: value = vc_container_io_read_le_uint32(ctx->priv->io); break;
       case 5: value = vc_container_io_read_le_uint40(ctx->priv->io); break;
       case 6: value = vc_container_io_read_le_uint48(ctx->priv->io); break;
       case 7: value = vc_container_io_read_le_uint56(ctx->priv->io); break;
       case 8: value = vc_container_io_read_le_uint64(ctx->priv->io); break;
       }
    }
    else if(type == LOG_FORMAT_TYPE_UINT_BE)
    {
       switch(size)
       {
       case 1: value = vc_container_io_read_uint8(ctx->priv->io);  break;
       case 2: value = vc_container_io_read_be_uint16(ctx->priv->io); break;
       case 3: value = vc_container_io_read_be_uint24(ctx->priv->io); break;
       case 4: value = vc_container_io_read_be_uint32(ctx->priv->io); break;
       case 5: value = vc_container_io_read_be_uint40(ctx->priv->io); break;
       case 6: value = vc_container_io_read_be_uint48(ctx->priv->io); break;
       case 7: value = vc_container_io_read_be_uint56(ctx->priv->io); break;
       case 8: value = vc_container_io_read_be_uint64(ctx->priv->io); break;
       }
    }
    else if(type == LOG_FORMAT_TYPE_FOURCC)
    {
       value = vc_container_io_read_fourcc(ctx->priv->io);
    }
    else if(type == LOG_FORMAT_TYPE_GUID)
    {
       value = vc_container_io_read(ctx->priv->io, &guid, 16);
    }
    else
    {
       vc_container_assert(0);
       return 0;
    }
    if(type == LOG_FORMAT_TYPE_GUID)
    {
       if(value == 16)
       {
       vc_container_helper_format_debug(ctx, indent, "%s: 0x%x-0x%x-0x%x-0x%2.2x%2.2x%2.2x%2.2x%2.2x%2.2x%2.2x%2.2x",
             name, guid.word0, guid.short0, guid.short1,
             guid.bytes[0], guid.bytes[1], guid.bytes[2], guid.bytes[3],
             guid.bytes[4], guid.bytes[5], guid.bytes[6], guid.bytes[7]);
       if(buffer) memcpy(buffer, &guid, sizeof(guid));
       }
    }
    else if(type == LOG_FORMAT_TYPE_FOURCC)
    {
       uint32_t val = value;
       vc_container_helper_format_debug(ctx, indent, "%s: %4.4s", name, (char *)&val);
    }
    else
    {
       vc_container_helper_format_debug(ctx, indent, "%s: %"PRIi64, name, value);
    }
    if(b_skip) value = (STREAM_POSITION(ctx) - offset) != size;
    return value;
 }
vc_container_helper_write_debug()
VC_CONTAINER_STATUS_T vc_container_helper_write_debug (VC_CONTAINER_T * ctx, int type, int size, const char * name, uint64_t value, const uint8_t * buffer, int indent, int silent)
Definition at line 167 of file containers_io_helpers.c.
References GUID_T::bytes, guid, VC_CONTAINER_PRIVATE_T::io, LOG_FORMAT_TYPE_FOURCC, LOG_FORMAT_TYPE_GUID, LOG_FORMAT_TYPE_STRING, LOG_FORMAT_TYPE_UINT_BE, LOG_FORMAT_TYPE_UINT_LE, VC_CONTAINER_T::priv, GUID_T::short0, GUID_T::short1, status, vc_container_assert, VC_CONTAINER_ERROR_FAILED, vc_container_helper_format_debug(), vc_container_io_write(), vc_container_io_write_be_uint16(), vc_container_io_write_be_uint24(), vc_container_io_write_be_uint32(), vc_container_io_write_be_uint64(), vc_container_io_write_fourcc(), vc_container_io_write_le_uint16(), vc_container_io_write_le_uint24(), vc_container_io_write_le_uint32(), vc_container_io_write_le_uint64(), vc_container_io_write_uint8(), VC_CONTAINER_SUCCESS, and GUID_T::word0.
 {
    VC_CONTAINER_STATUS_T status = VC_CONTAINER_SUCCESS;
    if(type == LOG_FORMAT_TYPE_STRING)
    {
       value = vc_container_io_write(ctx->priv->io, buffer, size);
       if(!silent)
          vc_container_helper_format_debug(ctx, indent, "%s: \"%ls\"", name, buffer);
       return value == (uint64_t)size ? VC_CONTAINER_SUCCESS : VC_CONTAINER_ERROR_FAILED;
    }
    if(type == LOG_FORMAT_TYPE_UINT_LE)
    {
       switch(size)
       {
       case 1: status = vc_container_io_write_uint8(ctx->priv->io, (uint8_t)value);  break;
       case 2: status = vc_container_io_write_le_uint16(ctx->priv->io, (uint16_t)value); break;
       case 3: status = vc_container_io_write_le_uint24(ctx->priv->io, (uint32_t)value); break;
       case 4: status = vc_container_io_write_le_uint32(ctx->priv->io, (uint32_t)value); break;
       case 8: status = vc_container_io_write_le_uint64(ctx->priv->io, value); break;
       }
    }
    else if(type == LOG_FORMAT_TYPE_UINT_BE)
    {
       switch(size)
       {
       case 1: status = vc_container_io_write_uint8(ctx->priv->io, (uint8_t)value);  break;
       case 2: status = vc_container_io_write_be_uint16(ctx->priv->io, (uint16_t)value); break;
       case 3: status = vc_container_io_write_be_uint24(ctx->priv->io, (uint32_t)value); break;
       case 4: status = vc_container_io_write_be_uint32(ctx->priv->io, (uint32_t)value); break;
       case 8: status = vc_container_io_write_be_uint64(ctx->priv->io, value); break;
       }
    }
    else if(type == LOG_FORMAT_TYPE_FOURCC)
    {
       status = vc_container_io_write_fourcc(ctx->priv->io, (uint32_t)value);
    }
    else if(type == LOG_FORMAT_TYPE_GUID)
    {
       value = vc_container_io_write(ctx->priv->io, buffer, 16);
    }
    else
    {
       vc_container_assert(0);
       return 0;
    }
    if(status)
    {
       vc_container_helper_format_debug(ctx, indent, "write failed for %s", name);
       return status;
    }
    if(!silent)
    {
       if (type == LOG_FORMAT_TYPE_FOURCC)
       {
          vc_container_helper_format_debug(ctx, indent, "%s: %4.4s", name, (char *)&value);
       }
       else if(type == LOG_FORMAT_TYPE_GUID)
       {
          GUID_T guid;
          memcpy(&guid, buffer, sizeof(guid));
          vc_container_helper_format_debug(ctx, indent, "%s: 0x%x-0x%x-0x%x-0x%2.2x%2.2x%2.2x%2.2x%2.2x%2.2x%2.2x%2.2x",
                name, guid.word0, guid.short0, guid.short1,
                guid.bytes[0], guid.bytes[1], guid.bytes[2], guid.bytes[3],
                guid.bytes[4], guid.bytes[5], guid.bytes[6], guid.bytes[7]);
       }
       else
       {
          vc_container_helper_format_debug(ctx, indent, "%s: %"PRIi64, name, value);
       }
    }
    return status;
 }
vc_container_io_peek_be_uint16()
STATIC_INLINE uint16_t vc_container_io_peek_be_uint16 (VC_CONTAINER_IO_T * io)
Peeks an unsigned 16 bits big endian integer from an i/o stream.
Parameters
io Pointer to the VC_CONTAINER_IO_T instance to use
Returns
The integer read. In case of failure during the read, this will return a value of 0.
Definition at line 294 of file containers_io_helpers.h.
References vc_container_io_peek().
 {
    uint8_t value[2];
    size_t ret = vc_container_io_peek(io, value, 2);
    return ret == 2 ? (value[0] << 8) | value[1] : 0;
 }
vc_container_io_peek_be_uint24()
STATIC_INLINE uint32_t vc_container_io_peek_be_uint24 (VC_CONTAINER_IO_T * io)
Peeks an unsigned 24 bits big endian integer from an i/o stream.
Parameters
io Pointer to the VC_CONTAINER_IO_T instance to use
Returns
The integer read. In case of failure during the read, this will return a value of 0.
Definition at line 306 of file containers_io_helpers.h.
References vc_container_io_peek().
 {
    uint8_t value[3];
    size_t ret = vc_container_io_peek(io, value, 3);
    return ret == 3 ? (value[0] << 16) | (value[1] << 8) | value[2] : 0;
 }
vc_container_io_peek_be_uint32()
STATIC_INLINE uint32_t vc_container_io_peek_be_uint32 (VC_CONTAINER_IO_T * io)
Peeks an unsigned 32 bits big endian integer from an i/o stream.
Parameters
io Pointer to the VC_CONTAINER_IO_T instance to use
Returns
The integer read. In case of failure during the read, this will return a value of 0.
Definition at line 318 of file containers_io_helpers.h.
References vc_container_io_peek().
 {
    uint8_t value[4];
    size_t ret = vc_container_io_peek(io, value, 4);
    return ret == 4 ? (value[0] << 24) | (value[1] << 16) | (value[2] << 8) | value[3] : 0;
 }
vc_container_io_peek_be_uint64()
STATIC_INLINE uint64_t vc_container_io_peek_be_uint64 (VC_CONTAINER_IO_T * io)
Peeks an unsigned 64 bits big endian integer from an i/o stream.
Parameters
io Pointer to the VC_CONTAINER_IO_T instance to use
Returns
The integer read. In case of failure during the read, this will return a value of 0.
Definition at line 330 of file containers_io_helpers.h.
References vc_container_io_peek().
 {
    uint8_t value[8];
    uint32_t value1, value2;
    size_t ret = vc_container_io_peek(io, value, 8);
    value1 = (value[0] << 24) | (value[1] << 16) | (value[2] << 8) | value[3];
    value2 = (value[4] << 24) | (value[5] << 16) | (value[6] << 8) | value[7];
    return ret == 8 ? (((uint64_t)value1) << 32)|value2 : 0;
 }
vc_container_io_peek_le_uint16()
STATIC_INLINE uint16_t vc_container_io_peek_le_uint16 (VC_CONTAINER_IO_T * io)
Peeks an unsigned 16 bits little endian integer from an i/o stream.
Parameters
io Pointer to the VC_CONTAINER_IO_T instance to use
Returns
The integer read. In case of failure during the read, this will return a value of 0.
Definition at line 347 of file containers_io_helpers.h.
References vc_container_io_peek().
 {
    uint8_t value[2];
    size_t ret = vc_container_io_peek(io, value, 2);
    return ret == 2 ? (value[1] << 8) | value[0] : 0;
 }
vc_container_io_peek_le_uint24()
STATIC_INLINE uint32_t vc_container_io_peek_le_uint24 (VC_CONTAINER_IO_T * io)
Peeks an unsigned 24 bits little endian integer from an i/o stream.
Parameters
io Pointer to the VC_CONTAINER_IO_T instance to use
Returns
The integer read. In case of failure during the read, this will return a value of 0.
Definition at line 359 of file containers_io_helpers.h.
References vc_container_io_peek().
 {
    uint8_t value[3];
    size_t ret = vc_container_io_peek(io, value, 3);
    return ret == 3 ? (value[2] << 16) | (value[1] << 8) | value[0] : 0;
 }
vc_container_io_peek_le_uint32()
STATIC_INLINE uint32_t vc_container_io_peek_le_uint32 (VC_CONTAINER_IO_T * io)
Peeks an unsigned 32 bits little endian integer from an i/o stream.
Parameters
io Pointer to the VC_CONTAINER_IO_T instance to use
Returns
The integer read. In case of failure during the read, this will return a value of 0.
Definition at line 371 of file containers_io_helpers.h.
References vc_container_io_peek().
 {
    uint8_t value[4];
    size_t ret = vc_container_io_peek(io, value, 4);
    return ret == 4 ? (value[3] << 24) | (value[2] << 16) | (value[1] << 8) | value[0] : 0;
 }
vc_container_io_peek_le_uint64()
STATIC_INLINE uint64_t vc_container_io_peek_le_uint64 (VC_CONTAINER_IO_T * io)
Peeks an unsigned 64 bits little endian integer from an i/o stream.
Parameters
io Pointer to the VC_CONTAINER_IO_T instance to use
Returns
The integer read. In case of failure during the read, this will return a value of 0.
Definition at line 383 of file containers_io_helpers.h.
References vc_container_io_peek().
 {
    uint8_t value[8];
    uint32_t value1, value2;
    size_t ret = vc_container_io_peek(io, value, 8);
    value1 = (value[3] << 24) | (value[2] << 16) | (value[1] << 8) | value[0];
    value2 = (value[7] << 24) | (value[6] << 16) | (value[5] << 8) | value[4];
    return ret == 8 ? (((uint64_t)value2) << 32)|value1 : 0;
 }
vc_container_io_peek_uint8()
STATIC_INLINE uint8_t vc_container_io_peek_uint8 (VC_CONTAINER_IO_T * io)
Peeks an unsigned 8 bits integer from an i/o stream.
Parameters
io Pointer to the VC_CONTAINER_IO_T instance to use
Returns
The integer read. In case of failure during the read, this will return a value of 0.
Definition at line 282 of file containers_io_helpers.h.
References vc_container_io_peek().
 {
    uint8_t value;
    size_t ret = vc_container_io_peek(io, &value, 1);
    return ret == 1 ? value : 0;
 }
vc_container_io_read_be_uint16()
STATIC_INLINE uint16_t vc_container_io_read_be_uint16 (VC_CONTAINER_IO_T * io)
Reads an unsigned 16 bits big endian integer from an i/o stream.
Parameters
io Pointer to the VC_CONTAINER_IO_T instance to use
Returns
The integer read. In case of failure during the read, this will return a value of 0.
Definition at line 70 of file containers_io_helpers.h.
References vc_container_io_read().
Referenced by vc_container_helper_read_debug().
 {
    uint8_t value[2];
    size_t ret = vc_container_io_read(io, value, 2);
    return ret == 2 ? (value[0] << 8) | value[1] : 0;
 }
vc_container_io_read_be_uint24()
STATIC_INLINE uint32_t vc_container_io_read_be_uint24 (VC_CONTAINER_IO_T * io)
Reads an unsigned 24 bits big endian integer from an i/o stream.
Parameters
io Pointer to the VC_CONTAINER_IO_T instance to use
Returns
The integer read. In case of failure during the read, this will return a value of 0.
Definition at line 82 of file containers_io_helpers.h.
References vc_container_io_read().
Referenced by vc_container_helper_read_debug().
 {
    uint8_t value[3];
    size_t ret = vc_container_io_read(io, value, 3);
    return ret == 3 ? (value[0] << 16) | (value[1] << 8) | value[2] : 0;
 }
vc_container_io_read_be_uint32()
STATIC_INLINE uint32_t vc_container_io_read_be_uint32 (VC_CONTAINER_IO_T * io)
Reads an unsigned 32 bits big endian integer from an i/o stream.
Parameters
io Pointer to the VC_CONTAINER_IO_T instance to use
Returns
The integer read. In case of failure during the read, this will return a value of 0.
Definition at line 94 of file containers_io_helpers.h.
References vc_container_io_read().
Referenced by vc_container_helper_read_debug().
 {
    uint8_t value[4];
    size_t ret = vc_container_io_read(io, value, 4);
    return ret == 4 ? (value[0] << 24) | (value[1] << 16) | (value[2] << 8) | value[3] : 0;
 }
vc_container_io_read_be_uint40()
STATIC_INLINE uint64_t vc_container_io_read_be_uint40 (VC_CONTAINER_IO_T * io)
Reads an unsigned 40 bits big endian integer from an i/o stream.
Parameters
io Pointer to the VC_CONTAINER_IO_T instance to use
Returns
The integer read. In case of failure during the read, this will return a value of 0.
Definition at line 106 of file containers_io_helpers.h.
References vc_container_io_read().
Referenced by vc_container_helper_read_debug().
 {
    uint8_t value[5];
    uint32_t value1, value2;
    size_t ret = vc_container_io_read(io, value, 5);
    value1 = (value[0] << 24) | (value[1] << 16) | (value[2] << 8) | value[3];
    value2 = value[4];
    return ret == 5 ? (((uint64_t)value1) << 8)|value2 : 0;
 }
vc_container_io_read_be_uint48()
STATIC_INLINE uint64_t vc_container_io_read_be_uint48 (VC_CONTAINER_IO_T * io)
Reads an unsigned 48 bits big endian integer from an i/o stream.
Parameters
io Pointer to the VC_CONTAINER_IO_T instance to use
Returns
The integer read. In case of failure during the read, this will return a value of 0.
Definition at line 123 of file containers_io_helpers.h.
References vc_container_io_read().
Referenced by vc_container_helper_read_debug().
 {
    uint8_t value[6];
    uint32_t value1, value2;
    size_t ret = vc_container_io_read(io, value, 6);
    value1 = (value[0] << 24) | (value[1] << 16) | (value[2] << 8) | value[3];
    value2 = (value[4] << 8) | value[5];
    return ret == 6 ? (((uint64_t)value1) << 16)|value2 : 0;
 }
vc_container_io_read_be_uint56()
STATIC_INLINE uint64_t vc_container_io_read_be_uint56 (VC_CONTAINER_IO_T * io)
Reads an unsigned 56 bits big endian integer from an i/o stream.
Parameters
io Pointer to the VC_CONTAINER_IO_T instance to use
Returns
The integer read. In case of failure during the read, this will return a value of 0.
Definition at line 140 of file containers_io_helpers.h.
References vc_container_io_read().
Referenced by vc_container_helper_read_debug().
 {
    uint8_t value[7];
    uint32_t value1, value2;
    size_t ret = vc_container_io_read(io, value, 7);
    value1 = (value[0] << 24) | (value[1] << 16) | (value[2] << 8) | value[3];
    value2 = (value[4] << 16) | (value[5] << 8) | value[6];
    return ret == 7 ? (((uint64_t)value1) << 24)|value2 : 0;
 }
vc_container_io_read_be_uint64()
STATIC_INLINE uint64_t vc_container_io_read_be_uint64 (VC_CONTAINER_IO_T * io)
Reads an unsigned 64 bits big endian integer from an i/o stream.
Parameters
io Pointer to the VC_CONTAINER_IO_T instance to use
Returns
The integer read. In case of failure during the read, this will return a value of 0.
Definition at line 157 of file containers_io_helpers.h.
References vc_container_io_read().
Referenced by vc_container_helper_read_debug().
 {
    uint8_t value[8];
    uint32_t value1, value2;
    size_t ret = vc_container_io_read(io, value, 8);
    value1 = (value[0] << 24) | (value[1] << 16) | (value[2] << 8) | value[3];
    value2 = (value[4] << 24) | (value[5] << 16) | (value[6] << 8) | value[7];
    return ret == 8 ? (((uint64_t)value1) << 32)|value2 : 0;
 }
vc_container_io_read_fourcc()
STATIC_INLINE VC_CONTAINER_FOURCC_T vc_container_io_read_fourcc (VC_CONTAINER_IO_T * io)
Reads a FOURCC from an i/o stream.
Parameters
io Pointer to the VC_CONTAINER_IO_T instance to use
Returns
The FOURCC to read. In case of failure during the read, this will return a value of 0.
Definition at line 58 of file containers_io_helpers.h.
References vc_container_io_read().
Referenced by vc_container_helper_read_debug().
 {
    VC_CONTAINER_FOURCC_T value;
    size_t ret = vc_container_io_read(io, (int8_t *)&value, 4);
    return ret == 4 ? value : 0;
 }
vc_container_io_read_le_uint16()
STATIC_INLINE uint16_t vc_container_io_read_le_uint16 (VC_CONTAINER_IO_T * io)
Reads an unsigned 16 bits little endian integer from an i/o stream.
Parameters
io Pointer to the VC_CONTAINER_IO_T instance to use
Returns
The integer read. In case of failure during the read, this will return a value of 0.
Definition at line 174 of file containers_io_helpers.h.
References vc_container_io_read().
Referenced by vc_container_helper_read_debug().
 {
    uint8_t value[2];
    size_t ret = vc_container_io_read(io, value, 2);
    return ret == 2 ? (value[1] << 8) | value[0] : 0;
 }
vc_container_io_read_le_uint24()
STATIC_INLINE uint32_t vc_container_io_read_le_uint24 (VC_CONTAINER_IO_T * io)
Reads an unsigned 24 bits little endian integer from an i/o stream.
Parameters
io Pointer to the VC_CONTAINER_IO_T instance to use
Returns
The integer read. In case of failure during the read, this will return a value of 0.
Definition at line 186 of file containers_io_helpers.h.
References vc_container_io_read().
Referenced by vc_container_helper_read_debug().
 {
    uint8_t value[3];
    size_t ret = vc_container_io_read(io, value, 3);
    return ret == 3 ? (value[2] << 16) | (value[1] << 8) | value[0] : 0;
 }
vc_container_io_read_le_uint32()
STATIC_INLINE uint32_t vc_container_io_read_le_uint32 (VC_CONTAINER_IO_T * io)
Reads an unsigned 32 bits little endian integer from an i/o stream.
Parameters
io Pointer to the VC_CONTAINER_IO_T instance to use
Returns
The integer read. In case of failure during the read, this will return a value of 0.
Definition at line 198 of file containers_io_helpers.h.
References vc_container_io_read().
Referenced by vc_container_helper_read_debug().
 {
    uint8_t value[4];
    size_t ret = vc_container_io_read(io, value, 4);
    return ret == 4 ? (value[3] << 24) | (value[2] << 16) | (value[1] << 8) | value[0] : 0;
 }
vc_container_io_read_le_uint40()
STATIC_INLINE uint64_t vc_container_io_read_le_uint40 (VC_CONTAINER_IO_T * io)
Reads an unsigned 40 bits little endian integer from an i/o stream.
Parameters
io Pointer to the VC_CONTAINER_IO_T instance to use
Returns
The integer read. In case of failure during the read, this will return a value of 0.
Definition at line 210 of file containers_io_helpers.h.
References vc_container_io_read().
Referenced by vc_container_helper_read_debug().
 {
    uint8_t value[5];
    uint32_t value1, value2;
    size_t ret = vc_container_io_read(io, value, 5);
    value1 = (value[3] << 24) | (value[2] << 16) | (value[1] << 8) | value[0];
    value2 = value[4];
    return ret == 5 ? (((uint64_t)value2) << 32)|value1 : 0;
 }
vc_container_io_read_le_uint48()
STATIC_INLINE uint64_t vc_container_io_read_le_uint48 (VC_CONTAINER_IO_T * io)
Reads an unsigned 48 bits little endian integer from an i/o stream.
Parameters
io Pointer to the VC_CONTAINER_IO_T instance to use
Returns
The integer read. In case of failure during the read, this will return a value of 0.
Definition at line 227 of file containers_io_helpers.h.
References vc_container_io_read().
Referenced by vc_container_helper_read_debug().
 {
    uint8_t value[6];
    uint32_t value1, value2;
    size_t ret = vc_container_io_read(io, value, 6);
    value1 = (value[3] << 24) | (value[2] << 16) | (value[1] << 8) | value[0];
    value2 = (value[5] << 8) | value[4];
    return ret == 6 ? (((uint64_t)value2) << 32)|value1 : 0;
 }
vc_container_io_read_le_uint56()
STATIC_INLINE uint64_t vc_container_io_read_le_uint56 (VC_CONTAINER_IO_T * io)
Reads an unsigned 56 bits little endian integer from an i/o stream.
Parameters
io Pointer to the VC_CONTAINER_IO_T instance to use
Returns
The integer read. In case of failure during the read, this will return a value of 0.
Definition at line 244 of file containers_io_helpers.h.
References vc_container_io_read().
Referenced by vc_container_helper_read_debug().
 {
    uint8_t value[7];
    uint32_t value1, value2;
    size_t ret = vc_container_io_read(io, value, 7);
    value1 = (value[3] << 24) | (value[2] << 16) | (value[1] << 8) | value[0];
    value2 = (value[6] << 16) | (value[5] << 8) | value[4];
    return ret == 7 ? (((uint64_t)value2) << 32)|value1 : 0;
 }
vc_container_io_read_le_uint64()
STATIC_INLINE uint64_t vc_container_io_read_le_uint64 (VC_CONTAINER_IO_T * io)
Reads an unsigned 64 bits little endian integer from an i/o stream.
Parameters
io Pointer to the VC_CONTAINER_IO_T instance to use
Returns
The integer read. In case of failure during the read, this will return a value of 0.
Definition at line 261 of file containers_io_helpers.h.
References vc_container_io_read().
Referenced by vc_container_helper_read_debug().
 {
    uint8_t value[8];
    uint32_t value1, value2;
    size_t ret = vc_container_io_read(io, value, 8);
    value1 = (value[3] << 24) | (value[2] << 16) | (value[1] << 8) | value[0];
    value2 = (value[7] << 24) | (value[6] << 16) | (value[5] << 8) | value[4];
    return ret == 8 ? (((uint64_t)value2) << 32)|value1 : 0;
 }
vc_container_io_read_uint8()
STATIC_INLINE uint8_t vc_container_io_read_uint8 (VC_CONTAINER_IO_T * io)
Reads an unsigned 8 bits integer from an i/o stream.
Parameters
io Pointer to the VC_CONTAINER_IO_T instance to use
Returns
The integer read. In case of failure during the read, this will return a value of 0.
Definition at line 46 of file containers_io_helpers.h.
References vc_container_io_read().
Referenced by vc_container_helper_read_debug().
 {
    uint8_t value;
    size_t ret = vc_container_io_read(io, &value, 1);
    return ret == 1 ? value : 0;
 }
vc_container_io_write_be_uint16()
STATIC_INLINE VC_CONTAINER_STATUS_T vc_container_io_write_be_uint16 (VC_CONTAINER_IO_T * io, uint16_t value)
Writes an unsigned 16 bits big endian integer to an i/o stream.
Parameters
io Pointer to the VC_CONTAINER_IO_T instance to use
value The integer to write.
Returns
The status of the operation.
Definition at line 426 of file containers_io_helpers.h.
References bytes, VC_CONTAINER_ERROR_FAILED, vc_container_io_write(), and VC_CONTAINER_SUCCESS.
Referenced by vc_container_helper_write_debug().
 {
    uint8_t bytes[2] = {(uint8_t)(value >> 8), (uint8_t)value};
    size_t ret = vc_container_io_write(io, bytes, 2);
    return ret == 2 ? VC_CONTAINER_SUCCESS : VC_CONTAINER_ERROR_FAILED;
 }
vc_container_io_write_be_uint24()
STATIC_INLINE VC_CONTAINER_STATUS_T vc_container_io_write_be_uint24 (VC_CONTAINER_IO_T * io, uint32_t value)
Writes an unsigned 24 bits big endian integer to an i/o stream.
Parameters
io Pointer to the VC_CONTAINER_IO_T instance to use
value The integer to write.
Returns
The status of the operation.
Definition at line 438 of file containers_io_helpers.h.
References bytes, VC_CONTAINER_ERROR_FAILED, vc_container_io_write(), and VC_CONTAINER_SUCCESS.
Referenced by vc_container_helper_write_debug().
 {
    uint8_t bytes[3] = {(uint8_t)(value >> 16), (uint8_t)(value >> 8), (uint8_t)value};
    size_t ret = vc_container_io_write(io, bytes, 3);
    return ret == 3 ? VC_CONTAINER_SUCCESS : VC_CONTAINER_ERROR_FAILED;
 }
vc_container_io_write_be_uint32()
STATIC_INLINE VC_CONTAINER_STATUS_T vc_container_io_write_be_uint32 (VC_CONTAINER_IO_T * io, uint32_t value)
Writes an unsigned 32 bits big endian integer to an i/o stream.
Parameters
io Pointer to the VC_CONTAINER_IO_T instance to use
value The integer to write.
Returns
The status of the operation.
Definition at line 450 of file containers_io_helpers.h.
References bytes, VC_CONTAINER_ERROR_FAILED, vc_container_io_write(), and VC_CONTAINER_SUCCESS.
Referenced by vc_container_helper_write_debug().
 {
    uint8_t bytes[4] = {value >> 24, value >> 16, value >> 8, value};
    size_t ret = vc_container_io_write(io, bytes, 4);
    return ret == 4 ? VC_CONTAINER_SUCCESS : VC_CONTAINER_ERROR_FAILED;
 }
vc_container_io_write_be_uint64()
STATIC_INLINE VC_CONTAINER_STATUS_T vc_container_io_write_be_uint64 (VC_CONTAINER_IO_T * io, uint64_t value)
Writes an unsigned 64 bits big endian integer to an i/o stream.
Parameters
io Pointer to the VC_CONTAINER_IO_T instance to use
value The integer to write.
Returns
The status of the operation.
Definition at line 462 of file containers_io_helpers.h.
References bytes, VC_CONTAINER_ERROR_FAILED, vc_container_io_write(), and VC_CONTAINER_SUCCESS.
Referenced by vc_container_helper_write_debug().
 {
    uint8_t bytes[8] =
    {
       (uint8_t)(value >> 56),
       (uint8_t)(value >> 48),
       (uint8_t)(value >> 40),
       (uint8_t)(value >> 32),
       (uint8_t)(value >> 24),
       (uint8_t)(value >> 16),
       (uint8_t)(value >> 8),
       (uint8_t) value
    };
    size_t ret = vc_container_io_write(io, bytes, 8);
    return ret == 8 ? VC_CONTAINER_SUCCESS : VC_CONTAINER_ERROR_FAILED;
 }
vc_container_io_write_fourcc()
STATIC_INLINE VC_CONTAINER_STATUS_T vc_container_io_write_fourcc (VC_CONTAINER_IO_T * io, VC_CONTAINER_FOURCC_T value)
Writes a FOURCC to an i/o stream.
Parameters
io Pointer to the VC_CONTAINER_IO_T instance to use
value The FOURCC to write.
Returns
The status of the operation.
Definition at line 415 of file containers_io_helpers.h.
References VC_CONTAINER_ERROR_FAILED, vc_container_io_write(), and VC_CONTAINER_SUCCESS.
Referenced by vc_container_helper_write_debug().
 {
    size_t ret = vc_container_io_write(io, (uint8_t *)&value, 4);
    return ret == 4 ? VC_CONTAINER_SUCCESS : VC_CONTAINER_ERROR_FAILED;
 }
vc_container_io_write_le_uint16()
STATIC_INLINE VC_CONTAINER_STATUS_T vc_container_io_write_le_uint16 (VC_CONTAINER_IO_T * io, uint16_t value)
Writes an unsigned 16 bits little endian integer to an i/o stream.
Parameters
io Pointer to the VC_CONTAINER_IO_T instance to use
value The integer to write.
Returns
The status of the operation.
Definition at line 484 of file containers_io_helpers.h.
References bytes, VC_CONTAINER_ERROR_FAILED, vc_container_io_write(), and VC_CONTAINER_SUCCESS.
Referenced by vc_container_helper_write_debug().
 {
    uint8_t bytes[2] = {(uint8_t)value, (uint8_t)(value >> 8)};
    size_t ret = vc_container_io_write(io, bytes, 2);
    return ret == 2 ? VC_CONTAINER_SUCCESS : VC_CONTAINER_ERROR_FAILED;
 }
vc_container_io_write_le_uint24()
STATIC_INLINE VC_CONTAINER_STATUS_T vc_container_io_write_le_uint24 (VC_CONTAINER_IO_T * io, uint32_t value)
Writes an unsigned 24 bits little endian integer to an i/o stream.
Parameters
io Pointer to the VC_CONTAINER_IO_T instance to use
value The integer to write.
Returns
The status of the operation.
Definition at line 496 of file containers_io_helpers.h.
References bytes, VC_CONTAINER_ERROR_FAILED, vc_container_io_write(), and VC_CONTAINER_SUCCESS.
Referenced by vc_container_helper_write_debug().
 {
    uint8_t bytes[3] = {value, value >> 8, value >> 16};
    size_t ret = vc_container_io_write(io, bytes, 3);
    return ret == 3 ? VC_CONTAINER_SUCCESS : VC_CONTAINER_ERROR_FAILED;
 }
vc_container_io_write_le_uint32()
STATIC_INLINE VC_CONTAINER_STATUS_T vc_container_io_write_le_uint32 (VC_CONTAINER_IO_T * io, uint32_t value)
Writes an unsigned 32 bits little endian integer to an i/o stream.
Parameters
io Pointer to the VC_CONTAINER_IO_T instance to use
value The integer to write.
Returns
The status of the operation.
Definition at line 508 of file containers_io_helpers.h.
References bytes, VC_CONTAINER_ERROR_FAILED, vc_container_io_write(), and VC_CONTAINER_SUCCESS.
Referenced by vc_container_helper_write_debug().
 {
    uint8_t bytes[4] = {value, value >> 8, value >> 16, value >> 24};
    size_t ret = vc_container_io_write(io, bytes, 4);
    return ret == 4 ? VC_CONTAINER_SUCCESS : VC_CONTAINER_ERROR_FAILED;
 }
vc_container_io_write_le_uint64()
STATIC_INLINE VC_CONTAINER_STATUS_T vc_container_io_write_le_uint64 (VC_CONTAINER_IO_T * io, uint64_t value)
Writes an unsigned 64 bits little endian integer to an i/o stream.
Parameters
io Pointer to the VC_CONTAINER_IO_T instance to use
value The integer to write.
Returns
The status of the operation.
Definition at line 520 of file containers_io_helpers.h.
References bytes, VC_CONTAINER_ERROR_FAILED, vc_container_io_write(), and VC_CONTAINER_SUCCESS.
Referenced by vc_container_helper_write_debug().
 {
    uint8_t bytes[8] =
    {
       (uint8_t) value,
       (uint8_t)(value >> 8),
       (uint8_t)(value >> 16),
       (uint8_t)(value >> 24),
       (uint8_t)(value >> 32),
       (uint8_t)(value >> 40),
       (uint8_t)(value >> 48),
       (uint8_t)(value >> 56)
    };
    size_t ret = vc_container_io_write(io, bytes, 8);
    return ret == 8 ? VC_CONTAINER_SUCCESS : VC_CONTAINER_ERROR_FAILED;
 }
vc_container_io_write_uint8()
STATIC_INLINE VC_CONTAINER_STATUS_T vc_container_io_write_uint8 (VC_CONTAINER_IO_T * io, uint8_t value)
Writes an unsigned 8 bits integer to an i/o stream.
Parameters
io Pointer to the VC_CONTAINER_IO_T instance to use
value The integer to write.
Returns
The status of the operation.
Definition at line 404 of file containers_io_helpers.h.
References VC_CONTAINER_ERROR_FAILED, vc_container_io_write(), and VC_CONTAINER_SUCCESS.
Referenced by vc_container_helper_write_debug().
 {
    size_t ret = vc_container_io_write(io, &value, 1);
    return ret == 1 ? VC_CONTAINER_SUCCESS : VC_CONTAINER_ERROR_FAILED;
 }