VideoCore Library: interface/khronos/common/openwfc/khrn_client_platform_openwfc.c File Reference
khrn_client_platform_openwfc.c File Reference
#include "interface/khronos/common/khrn_client_platform.h"
#include "interface/khronos/include/WF/wfc.h"
#include "interface/khronos/wf/wfc_int.h"
Classes
struct WFC_DATA_T
Macros
#define OPENWFC_BOUNCE
#define NUM_OF_ELEMENTS 2
Functions
uint32_t platform_get_handle (EGLDisplay dpy, EGLNativeWindowType win)
void platform_get_dimensions (EGLDisplay dpy, EGLNativeWindowType win, uint32_t *width, uint32_t *height, uint32_t *swapchain_count)
void * platform_wfc_bounce_thread (void *param)
Macro Definition Documentation
NUM_OF_ELEMENTS
#define NUM_OF_ELEMENTS 2
Definition at line 79 of file khrn_client_platform_openwfc.c.
Referenced by platform_wfc_bounce_thread().
OPENWFC_BOUNCE
#define OPENWFC_BOUNCE
Definition at line 44 of file khrn_client_platform_openwfc.c.
Function Documentation
platform_get_dimensions()
void platform_get_dimensions (EGLDisplay dpy, EGLNativeWindowType win, uint32_t * width, uint32_t * height, uint32_t * swapchain_count)
Definition at line 67 of file khrn_client_platform_openwfc.c.
Referenced by platform_memcpy().
 {
    EGL_DISPMANX_WINDOW_T *dwin = check_default(win);
    *width =  dwin->width;
    *height = dwin->height;
    *swapchain_count = 0;
 }
platform_get_handle()
uint32_t platform_get_handle (EGLDisplay dpy, EGLNativeWindowType win)
Definition at line 59 of file khrn_client_platform_openwfc.c.
Referenced by platform_memcpy().
 {
    EGL_DISPMANX_WINDOW_T *dwin = check_default(win);
    return dwin->element;  /* same handles used on host and videocore sides */
 }
platform_wfc_bounce_thread()
void* platform_wfc_bounce_thread (void * param)
Definition at line 81 of file khrn_client_platform_openwfc.c.
References WFC_BOUNCE_DATA_T::context, WFC_BOUNCE_DATA_T::dest_height, WFC_BOUNCE_DATA_T::dest_width, WFC_BOUNCE_DATA_T::device, WFC_BOUNCE_DATA_T::element, NO_ATTRIBUTES, NULL, NUM_OF_ELEMENTS, WFC_BOUNCE_DATA_T::num_of_elements, WFC_BOUNCE_DATA_T::source, WFC_BOUNCE_DATA_T::src_height, WFC_BOUNCE_DATA_T::src_width, WFC_BOUNCE_DATA_T::src_x, WFC_BOUNCE_DATA_T::src_y, WFC_BOUNCE_DATA_T::stop_bouncing, vcos_assert, vcos_sleep(), vcos_verify, WFC_CONTEXT_BG_COLOR, WFC_CONTEXT_TARGET_HEIGHT, WFC_CONTEXT_TARGET_WIDTH, WFC_ELEMENT_DESTINATION_RECTANGLE, WFC_ELEMENT_GLOBAL_ALPHA, WFC_ELEMENT_SOURCE, WFC_ELEMENT_SOURCE_RECTANGLE, WFC_ELEMENT_TRANSPARENCY_TYPES, WFC_ERROR_NONE, WFC_INVALID_HANDLE, WFC_RECT_HEIGHT, WFC_RECT_SIZE, WFC_RECT_WIDTH, WFC_RECT_X, WFC_RECT_Y, WFC_TRANSPARENCY_ELEMENT_GLOBAL_ALPHA, WFC_TRUE, wfcCommit(), wfcCreateElement(), wfcDestroyElement(), wfcGetContextAttribi(), wfcGetError(), wfcInsertElement(), wfcSetContextAttribi(), wfcSetElementAttribf(), wfcSetElementAttribi(), and wfcSetElementAttribiv().
 {
    WFC_BOUNCE_DATA_T *bounce_data = (WFC_BOUNCE_DATA_T *) param;
    uint32_t i;
    int32_t xstep[NUM_OF_ELEMENTS], ystep[NUM_OF_ELEMENTS];
    WFCint dest_rect[NUM_OF_ELEMENTS][WFC_RECT_SIZE];
    WFCint src_rect[WFC_RECT_SIZE];
    WFCElement element_local[NUM_OF_ELEMENTS];
    uint32_t num_of_elements = NUM_OF_ELEMENTS;
    WFCElement *element = element_local;
    // Get context (i.e. screen) dimensions.
    int32_t ctx_width;
    int32_t ctx_height;
    int32_t dest_width, dest_height;
    int32_t x, y;
    bool use_local_elements = (bounce_data->num_of_elements == 0);
    if(!use_local_elements)
    {
       vcos_assert(bounce_data->num_of_elements <= NUM_OF_ELEMENTS);
       vcos_assert(bounce_data->element != NULL);
       num_of_elements = bounce_data->num_of_elements;
       element = bounce_data->element;
    } // if
    // Initialise values
    ctx_width = wfcGetContextAttribi(bounce_data->device,
       bounce_data->context, WFC_CONTEXT_TARGET_WIDTH);
    ctx_height = wfcGetContextAttribi(bounce_data->device,
       bounce_data->context, WFC_CONTEXT_TARGET_HEIGHT);
    // Change background colour
    wfcSetContextAttribi(bounce_data->device,
       bounce_data->context, WFC_CONTEXT_BG_COLOR, 0x0000FFFF);
    float scale = 0.4;
    if(num_of_elements == 1)
       {scale = 0.75;}
    dest_width = bounce_data->dest_width * scale;
    dest_height = bounce_data->dest_height * scale;
    // Define source rectangle
    src_rect[WFC_RECT_X] = bounce_data->src_x;
    src_rect[WFC_RECT_Y] = bounce_data->src_y;
    src_rect[WFC_RECT_WIDTH] = bounce_data->src_width;
    src_rect[WFC_RECT_HEIGHT] = bounce_data->src_height;
    for(i = 0; i < num_of_elements; i++)
    {
       if(use_local_elements)
       {
          // Create and set up element
          element[i] = wfcCreateElement(bounce_data->device,
             bounce_data->context, NO_ATTRIBUTES);
          vcos_assert(element[i] != WFC_INVALID_HANDLE);
          wfcInsertElement(bounce_data->device, element[i], WFC_INVALID_HANDLE);
          if(vcos_verify(wfcGetError(bounce_data->device) == WFC_ERROR_NONE)) {};
       } // if
       else
       {
          // Element created in calling app, so use that
          element[i] = bounce_data->element[i];
       } // else
       wfcSetElementAttribiv(bounce_data->device, element[i],
          WFC_ELEMENT_SOURCE_RECTANGLE, WFC_RECT_SIZE, src_rect);
       // Attach existing source
       wfcSetElementAttribi(bounce_data->device, element[i],
          WFC_ELEMENT_SOURCE, bounce_data->source);
       if(num_of_elements > 1)
       {
          wfcSetElementAttribi(bounce_data->device, element[i],
             WFC_ELEMENT_TRANSPARENCY_TYPES, WFC_TRANSPARENCY_ELEMENT_GLOBAL_ALPHA);
          wfcSetElementAttribf(bounce_data->device, element[i],
             WFC_ELEMENT_GLOBAL_ALPHA, 0.75);
       } // if
       // Define initial destination rectangle
       dest_rect[i][WFC_RECT_X] = i * 100;
       dest_rect[i][WFC_RECT_Y] = i * 10;
       dest_rect[i][WFC_RECT_WIDTH] = dest_width;
       dest_rect[i][WFC_RECT_HEIGHT] = dest_height;
       wfcSetElementAttribiv(bounce_data->device, element[i],
          WFC_ELEMENT_DESTINATION_RECTANGLE, WFC_RECT_SIZE, dest_rect[i]);
       xstep[i] = (i + 1) * 2;
       ystep[i] = (i + 1) * 2;
    } // for
    while(!bounce_data->stop_bouncing)
    {
       for(i = 0; i < num_of_elements; i++)
       {
          // Compute new x and y values.
          x = dest_rect[i][WFC_RECT_X];
          y = dest_rect[i][WFC_RECT_Y];
          x += xstep[i];
          if(x + dest_width >= ctx_width)
             {x = ctx_width - dest_width - 1; xstep[i] *= -1;}
          else if(x < 0)
             {x = 0; xstep[i] *= -1;}
          y += ystep[i];
          if(y + dest_height >= ctx_height)
             {y = ctx_height - dest_height - 1; ystep[i] *= -1;}
          else if(y < 0)
             {y = 0; ystep[i] *= -1;}
          dest_rect[i][WFC_RECT_X] = x;
          dest_rect[i][WFC_RECT_Y] = y;
          // Set updated destination rectangle
          wfcSetElementAttribiv(bounce_data->device, element[i],
             WFC_ELEMENT_DESTINATION_RECTANGLE, WFC_RECT_SIZE, dest_rect[i]);
       } // for
       wfcCommit(bounce_data->device, bounce_data->context, WFC_TRUE);
       vcos_sleep(30);
    } // while
    // Remove elements
    if(use_local_elements)
    {
       for(i = 0; i < num_of_elements; i++)
       {
          wfcDestroyElement(bounce_data->device, element[i]);
       } // for
    } // if
    // Change background colour
    wfcSetContextAttribi(bounce_data->device,
       bounce_data->context, WFC_CONTEXT_BG_COLOR, 0xFF0000FF);
    wfcCommit(bounce_data->device, bounce_data->context, WFC_TRUE);
    return NULL;
 } // platform_bounce_thread