VideoCore Library: containers/simple/simple_writer.c File Reference
simple_writer.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include "containers/core/containers_private.h"
#include "containers/core/containers_io_helpers.h"
#include "containers/core/containers_utils.h"
#include "containers/core/containers_logging.h"
#include "simple_common.h"
Classes
struct VC_CONTAINER_TRACK_MODULE_T
struct VC_CONTAINER_MODULE_T
Macros
#define MAX_TRACKS 4
#define MAX_LINE_SIZE 512
#define ES_SUFFIX "%s.%2.2i.%4.4s"
#define ES_SUFFIX_SIZE 8
Typedefs
typedef struct VC_CONTAINER_TRACK_MODULE_T VC_CONTAINER_TRACK_MODULE_T
typedef struct VC_CONTAINER_MODULE_T VC_CONTAINER_MODULE_T
Functions
VC_CONTAINER_STATUS_T simple_writer_open (VC_CONTAINER_T *)
Macro Definition Documentation
ES_SUFFIX
#define ES_SUFFIX "%s.%2.2i.%4.4s"
Definition at line 45 of file simple_writer.c.
ES_SUFFIX_SIZE
#define ES_SUFFIX_SIZE 8
Definition at line 46 of file simple_writer.c.
MAX_LINE_SIZE
#define MAX_LINE_SIZE 512
Definition at line 43 of file simple_writer.c.
MAX_TRACKS
#define MAX_TRACKS 4
Definition at line 42 of file simple_writer.c.
Typedef Documentation
VC_CONTAINER_MODULE_T
typedef struct VC_CONTAINER_MODULE_T VC_CONTAINER_MODULE_T
VC_CONTAINER_TRACK_MODULE_T
typedef struct VC_CONTAINER_TRACK_MODULE_T VC_CONTAINER_TRACK_MODULE_T
Function Documentation
simple_writer_open()
VC_CONTAINER_STATUS_T simple_writer_open (VC_CONTAINER_T * ctx)
Definition at line 308 of file simple_writer.c.
References error(), extension, LOG_DEBUG, VC_CONTAINER_PRIVATE_T::module, VC_CONTAINER_PRIVATE_T::pf_close, VC_CONTAINER_T::priv, status, VC_CONTAINER_MODULE_T::tracks, VC_CONTAINER_T::tracks, VC_CONTAINER_PRIVATE_T::uri, VC_CONTAINER_ERROR_FORMAT_INVALID, VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED, VC_CONTAINER_ERROR_OUT_OF_MEMORY, vc_uri_find_query(), and vc_uri_path_extension().
 {
    VC_CONTAINER_STATUS_T status = VC_CONTAINER_ERROR_FORMAT_INVALID;
    const char *extension = vc_uri_path_extension(ctx->priv->uri);
    VC_CONTAINER_MODULE_T *module;
    /* Check if the user has specified a container */
    vc_uri_find_query(ctx->priv->uri, 0, "container", &extension);
    /* Check we're the right writer for this */
    if(!extension)
       return VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED;
    if(strcasecmp(extension, "smpl") && strcasecmp(extension, "simple"))
       return VC_CONTAINER_ERROR_FORMAT_NOT_SUPPORTED;
    LOG_DEBUG(ctx, "using simple writer");
    /* Allocate our context */
    module = malloc(sizeof(*module));
    if (!module) { status = VC_CONTAINER_ERROR_OUT_OF_MEMORY; goto error; }
    memset(module, 0, sizeof(*module));
    ctx->priv->module = module;
    ctx->tracks = module->tracks;
    ctx->priv->pf_close = simple_writer_close;
    ctx->priv->pf_write = simple_writer_write;
    ctx->priv->pf_control = simple_writer_control;
    return VC_CONTAINER_SUCCESS;
  error:
    LOG_DEBUG(ctx, "simple: error opening stream (%i)", status);
    return status;
 }