VideoCore Library: host_applications/linux/apps/hello_pi/libs/revision/revision.h File Reference
revision.h File Reference
Macros
#define PROCESSOR_BCM2835 0
#define PROCESSOR_BCM2836 1
#define PROCESSOR_BCM2837 2
#define PROCESSOR_BCM2838 3
Functions
int get_model_type (void)
int is_model_pi4 (void)
int get_processor_id (void)
Macro Definition Documentation
PROCESSOR_BCM2835
#define PROCESSOR_BCM2835 0
Definition at line 28 of file revision.h.
PROCESSOR_BCM2836
#define PROCESSOR_BCM2836 1
Definition at line 29 of file revision.h.
PROCESSOR_BCM2837
#define PROCESSOR_BCM2837 2
Definition at line 30 of file revision.h.
PROCESSOR_BCM2838
#define PROCESSOR_BCM2838 3
Definition at line 31 of file revision.h.
Referenced by deinit(), and main().
Function Documentation
get_model_type()
int get_model_type (void)
Definition at line 59 of file revision.c.
Referenced by is_model_pi4().
 {
    unsigned int revision_num = get_revision_code();
    if (!revision_num)
       return 0;
    // Check for old/new style revision code. Bit 23 will be guaranteed one for new style
    if (revision_num & 0x800000)
       return (revision_num & 0xff0) >> 4;
    else
    {
       // Mask off warrantee and overclock bits.
       revision_num &= 0xffffff;
       // Map old style to new Type code
       if (revision_num < 2 || revision_num > 21)
          return 0;
       static const unsigned char type_map[] =
       {
          1,   // B rev 1.0  2
          1,   // B rev 1.0  3
          1,   // B rev 2.0  4
          1,   // B rev 2.0  5
          1,   // B rev 2.0  6
          0,   // A rev 2    7
          0,   // A rev 2    8
          0,   // A rev 2    9
          0, 0, 0,  // unused  a,b,c
          1,   // B  rev 2.0  d
          1,   // B rev 2.0  e
          1,   // B rev 2.0  f
          3,   // B+ rev 1.2 10
          6,   // CM1        11
          2,   // A+ rev1.1  12
          3,   // B+ rev 1.2 13
          6,   // CM1        14
          2    // A+         15
       };
       return type_map[revision_num-2];
    }
    return 0;
 }
get_processor_id()
int get_processor_id (void)
Definition at line 114 of file revision.c.
Referenced by deinit(), and main().
 {
    unsigned int revision_num = get_revision_code();
    if (revision_num & 0x800000)
    {
       return (revision_num & 0xf000) >> 12;
    }
    else
    {
       // Old style number only used 2835
       return PROCESSOR_BCM2835;
    }
 }
is_model_pi4()
int is_model_pi4 (void)
Definition at line 107 of file revision.c.
References get_model_type().
 {
    return get_model_type() == 0x11 ? 1 : 0;
 }